### ISSUE TITLE
LSP References: show paths relative to LSP root dir (workaround: 'quickfixtextfunc')

### ISSUE THREAD

**Issue by jdujava** [neovim/neovim#30739]
### Problem

Suppose the following scenario:
* Use `vim.lsp.buf.references()` or `telescope.builtin.lsp.references()` on some symbol.
* If a given reference is under the directory of the current file, the path is given nicely as relative w.r.t. this current directory.
* But if a given reference is outside (for example in a sibling directory), the path is given as absolute.

This can be rather unconvenient (leads to large lines, such that the position of the reference in the given line can be clipped).
The screenshot below shows the behavior in Telescope LSP References, but it looks similarly in quickfix window after `vim.lsp.buf.references()`.

![Image](https://github.com/user-attachments/assets/e3bd8ad2-a1c6-4599-8fa6-6f9202fb92f3)

### Expected behavior

It would be nice to have option to display paths as relative to LSP root directory (either just for "outside" references, or even for all). I am not sure if there is a simple way to do it now, or whether it would be best to implement it directly in `vim.lsp.buf.references()` (or somewhere else).

**Comment by glepnir** [comment]
maybe need a opt param in `locations_to_items` do something like 

```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index 882ec22ca..95c428b28 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -1817,7 +1817,7 @@ function M.locations_to_items(locations, offset_encoding)
       local col = M._str_byteindex_enc(line, pos.character, offset_encoding)
       local end_col = M._str_byteindex_enc(end_line, end_pos.character, offset_encoding)

-      table.insert(items, {
+      local item = {
         filename = filename,
         lnum = row + 1,
         end_lnum = end_row + 1,
@@ -1825,7 +1825,8 @@ function M.locations_to_items(locations, offset_encoding)
         end_col = end_col + 1,
         text = line,
         user_data = temp.location,
-      })
+      }
+      table.insert(items, opt.convert and opt.convert(item) or item)
     end
   end
   return items

```

**Comment by mfussenegger** [comment]
There's also `'quickfixtextfunc'` to customize the entries.

E.g. I have something like this in use:

```lua
-- quickfixtextfunc to be used with nvim-jdtls:
-- Turns entries like `jdt://contents/java.xml/[...]/ListDatatypeValidator.class` into `package.name::ClassName: [Class] ListDatatypeValidator`
function M.quickfixtext(opts)
  if opts.quickfix == 0 then
    return nil
  end
  local qflist = vim.fn.getqflist({ id = opts.id, items = 0, title = 0, context = 0 })
  local ctx = qflist.context or {}
  if not ctx.client_id and qflist.title ~= 'Language Server' and qflist.title ~= 'LSP locations' then
    return nil
  end
  local result = {}
  for i, item in pairs(qflist.items) do
    if i >= opts.start_idx and i <= opts.end_idx then
      table.insert(result, string.format('%s|%d %d|%s',
        M.format_uri(vim.uri_from_bufnr(item.bufnr)),
        item.lnum,
        item.col,
        item.text
      ))
    end
  end
  return result
end

function M.format_uri(uri)
  if vim.startswith(uri, 'jdt://') then
    local package = uri:match('contents/[%a%d._-]+/([%a%d._-]+)') or ''
    local class = uri:match('contents/[%a%d._-]+/[%a%d._-]+/([%a%d$]+).class') or ''
    return string.format('%s::%s', package, class)
  else
    local fname = vim.fn.fnamemodify(vim.uri_to_fname(uri), ':.')
    fname = fname:gsub('src/main/java/', 's/m/j/')
    fname = fname:gsub('src/test/java/', 's/t/j/')
    return fname
  end
end

```

You could do something similar to use relative paths.

**Comment by justinmk** [comment]
Is this different than https://github.com/neovim/neovim/issues/15950 ?

**Comment by glepnir** [comment]
can mark as duplicate.

**Comment by aikow** [comment]
I was looking for something similar, and found this issue. The problem I have is that using the lsp keybinds like `grr` (`vim.lsp.buf.references()`) and `gd` ("lsp go to definition"), also open the buffers as absolute paths, instead of relative to the neovim pwd. This can be a bit disconcerting when listing buffers with `:ls` or using a buffer picker. That isn't a problem that can be solved by using `'quickfixtextfunc'`.

I didn't see anything against commenting on old/closed issues, but if I missed something, I can also create create a new one
