### ISSUE TITLE
issue building  [build/src/msgpack-stamp/msgpack-build] Error 2

### ISSUE THREAD

**Issue by stefanpenner** [neovim/neovim#3073]
```
brew install neovim --HEAD
```

output:

```
make[4]: *** [all] Error 2
make[3]: *** [build/src/msgpack-stamp/msgpack-build] Error 2
make[2]: *** [CMakeFiles/msgpack.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```

I tried both release and debug builds.

OS: `OSX 10.10.4`

I can imagine something is funky on my end. Let me know what other info I can provide.

**Comment by stefanpenner** [comment]
running with verbose now, to get more useful info.

**Comment by Pyrohh** [comment]
I recall getting this error a while ago, I could only reproduce it when using make(1). When using Ninja (see [Building Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim)) the issue went away.

**Comment by stefanpenner** [comment]
@Pyrohh the docs suggest merely installing ninja makes the Makefile prefer and use it, is that true?

**Comment by justinmk** [comment]
These non-verbose cmake messages could be anything at all. The only reason I thought https://github.com/neovim/neovim/issues/3071 might be related was because of (1) timing and (2) homebrew formula uses RelWithDebInfo.

However, it turns out the issue happens with Debug as well, so that was my mistake. It's related to 32-bit GCC.

**Comment by stefanpenner** [comment]
```
/usr/local/Cellar/cmake/3.2.3/bin/cmake -P CMakeFiles/msgpack-static.dir/cmake_clean_target.cmake
/usr/local/Cellar/cmake/3.2.3/bin/cmake -E cmake_link_script CMakeFiles/msgpack-static.dir/link.txt --verbose=1
/usr/local/bin/ar cq libmsgpack.a  CMakeFiles/msgpack-static.dir/src/unpack.c.o CMakeFiles/msgpack-static.dir/src/objectc.c.o CMakeFiles/msgpack-static.dir/src/version.c.o CMakeFiles/msgpack-static.dir/src/vrefbuffer.c.o CMakeFiles/msgpack-static.dir/src/zone.c.o
/usr/local/bin/ar: libmsgpack.a: Invalid operation
make[6]: *** [libmsgpack.a] Error 1
make[5]: *** [CMakeFiles/msgpack-static.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [build/src/msgpack-stamp/msgpack-build] Error 2
make[2]: *** [CMakeFiles/msgpack.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
==> Formula
Tap: neovim/homebrew-neovim
Path: /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 7550c35192c0b09f6b1477d9f81479d0e0eacc32
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_45
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/gettext/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by Pyrohh** [comment]
> the docs suggest merely installing ninja makes the Makefile prefer and use it, is that true?

Pretty much, although you might need to run `make distclean` first.

By the way, Is that the whole log? I thought there would be more information :disappointed:

**Comment by stefanpenner** [comment]
It was only the tail end that failed. I meant to also post a gist to the full one. But apparently I forgot. I will do it when I am back on my machine.

Sorry for the partial log

**Comment by stefanpenner** [comment]
ok `make distclean` did in-fact get the system to jump to use `ninja`, but a related issue (potentially on my system) is preventing msgpack to be 


after:
```
git clean -fdx
git pull --ff-only
make
```

```
[19/70] No patch step for 'luajit'
[20/70] No update step for 'luajit'
HOSTCC    host/buildvm_fold.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.s
ASM       lj_vm.o
CC        lj_gc.o
BUILDVM   lj_ffdef.h
CC        lj_err.o
CC        lj_char.o
BUILDVM   lj_bcdef.h
CC        lj_bc.o
CC        lj_obj.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_dispatch.o
CC        lj_vmevent.o
CC        lj_vmmath.o
CC        lj_strscan.o
CC        lj_api.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
CC        lj_opt_mem.o
BUILDVM   lj_folddef.h
CC        lj_opt_fold.o
CC        lj_opt_narrow.o
CC        lj_opt_dce.o
CC        lj_opt_loop.o
CC        lj_opt_split.o
CC        lj_opt_sink.o
CC        lj_mcode.o
CC        lj_snap.o
CC        lj_record.o
CC        lj_crecord.o
BUILDVM   lj_recdef.h
CC        lj_ffrecord.o
CC        lj_asm.o
CC        lj_trace.o
CC        lj_gdbjit.o
CC        lj_ctype.o
CC        lj_cdata.o
CC        lj_cconv.o
CC        lj_ccall.o
CC        lj_ccallback.o
CC        lj_carith.o
CC        lj_clib.o
CC        lj_cparse.o
CC        lj_lib.o
CC        lj_alloc.o
CC        lib_aux.o
BUILDVM   lj_libdef.h
CC        lib_base.o
CC        lib_math.o
CC        lib_bit.o
CC        lib_string.o
CC        lib_table.o
CC        lib_io.o
CC        lib_os.o
CC        lib_package.o
CC        lib_debug.o
CC        lib_jit.o
CC        lib_ffi.o
CC        lib_init.o
AR        libluajit.a
make[2]: *** [libluajit.a] Error 1
make[1]: *** [src/luajit] Error 2
ninja: build stopped: subcommand failed.
make: *** [deps] Error
```
the full error log: https://gist.github.com/stefanpenner/9df178c02745dc84e443

**Comment by Pyrohh** [comment]
I'm glad you ran `git clean -fdx`, as I thought you might be using a `local.mk`, but now I have no idea what the issue could be. I assume you have done everything mentioned on [Building-Neovim#os-x](https://github.com/neovim/neovim/wiki/Building-Neovim#os-x)?

**Comment by stefanpenner** [comment]
> I assume you have done everything mentioned on Building-Neovim#os-x?

I believe I have, but i will carefully repeat my steps again this evening (I could have missed something

**Comment by tarruda** [comment]
This seems to be an issue with OSX binutils and I just reproduced it in my own OSX vm. I have no idea what's the cause, especially because a few days ago it was working fine. The only significant change I remember making was installing apple-gdb through [this formula](https://gist.github.com/shn/4014355)(don't ask me how this could be related).

In any case, I managed to revert the problem with the following steps:

```
rm -rf $(brew --cache)/*
brew uninstall apple-gdb
brew uninstall neovim
brew untap neovim/neovim
brew install binutils
```

I think just installing binutils through homebrew is enough, but I thought it would be a good idea to describe everything I did just in case it's something else.

**Comment by stefanpenner** [comment]
I believe it was apple-gdb, which conflicts with binutils


```
The formula built, but is not symlinked into /usr/local
Could not symlink include/ansidecl.h
Target /usr/local/include/ansidecl.h
is a symlink belonging to binutils. You can unlink it:
  brew unlink binutils

To force the link and overwrite all conflicting files:
  brew link --overwrite apple-gdb

To list all files that would be deleted:
  brew link --overwrite --dry-run apple-gdb

Possible conflicting files are:
/usr/local/include/ansidecl.h -> /usr/local/Cellar/binutils/2.25/include/ansidecl.h
/usr/local/include/bfd.h -> /usr/local/Cellar/binutils/2.25/include/bfd.h
/usr/local/include/bfdlink.h -> /usr/local/Cellar/binutils/2.25/include/bfdlink.h
/usr/local/include/dis-asm.h -> /usr/local/Cellar/binutils/2.25/include/dis-asm.h
/usr/local/include/symcat.h -> /usr/local/Cellar/binutils/2.25/include/symcat.h
/usr/local/share/info/bfd.info -> /usr/local/Cellar/binutils/2.25/share/info/bfd.info
/usr/local/lib/libbfd.a -> /usr/local/Cellar/binutils/2.25/lib/libbfd.a
/usr/local/lib/libopcodes.a -> /usr/local/Cellar/binutils/2.25/lib/libopcodes.a
```

**Comment by stefanpenner** [comment]
Yup confirmed, it was `apple-gdb` that conflicting with `binutils`

**Comment by tarruda** [comment]
Really scary that apple-gdb would do this. I only found it because my OSX is really fresh and I know that the only change I made after building neovim was installing apple-gdb.

**Comment by fdinoff** [comment]
@tarruda Just curious why are you installing apple-gdb? You should be using lldb to debug programs on OS X.

Looking at that formula it looks like the gdb they are using was last updated 3 years ago which was about the time apple switched to clang for all of its development.

**Comment by tarruda** [comment]
>@tarruda Just curious why are you installing apple-gdb? 

No reason except being lazy to learn lldb :smile: 

I actually tried it before and found the commands to be very verbose, which is fine when embedded in another UI, but annoying when used directly from the terminal. So I decided to stick with gdb at least until lldb is fully supported on linux which is my primary development platform.

Plus, I couldn't find an obvious way to use lldb as a replacement to gdb talking to a gdb server(I find it very useful to inspect programs using valgrind's gdbserver)
