### ISSUE TITLE
Fedora COPR repository doesn't work

### ISSUE THREAD

**Issue by Integralist** [neovim/neovim#3075]
I've followed the instructions for `dnf` but it seems there are two problems:

1. `dnf copr enable dperson/neovim` -> `copr` command doesn't exist
2. `dnf --enablerepo dperson/neovim` -> unknown repo

Nothing I try for option two returns anything other than "unknown repo".

I can't access any of the copr links provided in the wiki either.

**Comment by Pyrohh** [comment]
AFAICT, no in the core team is responsible for that repo, so unless someone wants to fix it then we should just remove the instructions in question.

**Comment by fwalch** [comment]
Looks like the whole COPR website is down at the moment? https://copr.fedoraproject.org/ doesn't work.

**Comment by Pyrohh** [comment]
It looks to be back up.

**Comment by fwalch** [comment]
> dnf copr enable dperson/neovim -> copr command doesn't exist

According to [this](https://fedorahosted.org/copr/wiki/HowToEnableRepo), this command should work. Maybe you need to install some additional packages? (I have no idea about Fedora)

**Comment by Integralist** [comment]
Maybe the problem was that the COPR site was down - I wasn't sure if they were related endpoints. I'll give that a go shortly and report back (I'm doing this via a Docker container so it wont take long to verify)

**Comment by Integralist** [comment]
OK so it seems that still doesn't work, it results in the following error:

```bash
No such command: copr. Please use /usr/bin/dnf --help
```

This is using the following Dockerfile:

```Dockerfile
FROM fedora:latest
RUN dnf copr enable dperson/neovim
RUN dnf -y install neovim
```

You can try it yourself by creating the above Dockerfile and executing:

```bash
docker build -t integralist/neovim .
```

If I modify the Dockerfile like so:

```Dockerfile
FROM fedora:latest
RUN dnf --enablerepo dperson/neovim
RUN dnf -y install neovim
```

Then building the image results in the following error:

```bash
Error: Unknown repo: 'dperson/neovim'
```

Admittedly I don't know much about Fedora myself, I'm required to use it for a project - so I don't know if I'm missing any additional packages or not

**Comment by fwalch** [comment]
The docu page I linked above says "you need to have dnf-plugins-core installed".

**Comment by Integralist** [comment]
Thanks @fwalch I totally missed that, and it was indeed the solution:

```Dockerfile
FROM fedora:latest
RUN dnf -y install dnf-plugins-core
RUN dnf -y copr enable dperson/neovim
RUN dnf -y install neovim
```

I've now updated the Wiki page to reflect this.

**Comment by Pyrohh** [comment]
> I've now updated the Wiki page to reflect this: https://github.com/neovim/neovim/wiki/Installing-Neovim#fedora-2122

Thanks @Integralist, much appreciated.
