### ISSUE TITLE
Using `vim.on_key()` stuck at `Press ENTER or...`.

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30752]
### Problem

The only way out is to `kill -INT <pid>`. Other kills work as well.

### Steps to reproduce

Using `nvim --clean`, edit and source the following, get the following for any keystroke.
```
Press ENTER or type command to continue                                                             
Press ENTER or type command to continue                                                             
...
```

```
local ns_id
local function key_cb(key, typed)
    vim.print("key_cb")
    vim.print(string.format("KEYCB: key '%s', typed '%s'", key, typed))
end

ns_id = vim.on_key(key_cb)


key_cb("foo", "bar")

-- The defered function doesn't work. Guess it's never executed.
--vim.defer_fn(function() vim.on_key(nil, ns_id) end, 9000)
```

### Expected behavior

Expect `Ctrl-C` to get out of loop.

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/61f1b091ea97793f9b644cebf6c84cf6bbb4f0bc

### Vim (not Nvim) behaves the same?

Can't reproduce in vim

### Operating system/version

ubuntu

### Terminal name/version

gnone

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
Hmm, an easy solution is to simply disable recursive invocation of `vim.on_key()` callback. The second argument to the callback doesn't currently work properly either when invoked recursively.
