### ISSUE TITLE
no parser for 'lua' language when config not present.

### ISSUE THREAD

**Issue by vext01** [neovim/neovim#30761]
### Problem

OpenBSD pkg maintainer here. A user emailed me a potential bug.

Summary: If you open a Lua file when there is no config file in place, you get a crash.

```
$ mv ~/.config/nvim ~/.config/nvim.orig
$ echo "print('hi')" > a.lua
$ nvim a.lua
```

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/local/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/local/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..Fil
eType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /usr/local/share/nvim/runtime/ftplugin/lua.lua: Vim(runtime):E5113: Error while calling lua chunk: ...local/share
/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'lua' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
        /usr/local/share/nvim/runtime/ftplugin/lua.lua:2: in main chunk
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:36: in function </usr/local/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/local/share/nvim/runtime/filetype.lua:36: in function </usr/local/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/local/share/nvim/runtime/filetype.lua:35: in function </usr/local/share/nvim/runtime/filetype.lua:10>
```

I don't know if this is expected or not.

I can reproduce this on neovim-0.10.2 on OpenBSD-current, but the user says it also happens on neovim-0.10.1 that we shipped with OpenBSD-7.6. They claim it *didn't* happen with neovim-0.9.5 that we shipped with OpenBSD-7.5.

It does not happen if you open the file with `nvim -u NONE a.lua`.

Is it a bug?

### Steps to reproduce

```
$ mv ~/.config/nvim ~/.config/nvim.orig
$ echo "print('hi')" > a.lua
$ nvim a.lua
```

### Expected behavior

No crash(?) Not sure.

### Nvim version (nvim -v)

0.10.2, 0.10.1

### Vim (not Nvim) behaves the same?

no, vim-9.1.707

### Operating system/version

OpenBSD

### Terminal name/version

-

### $TERM environment variable

-

### Installation

OpenBSD package

**Comment by justinmk** [comment]
Is that actually a crash or just a (noisy) error? Does the bsd package include the treesitter parsers? Nvim 0.10 expects the lua treesitter `.so` file to be available on 'runtimepath'.

**Comment by clason** [comment]
This means that you didn't package the tree-sitter-lua parser, which is a required(!) part of the runtime files.

**Comment by vext01** [comment]
Thanks for your responses.

> Is that actually a crash or just a (noisy) error?

It's just a noisy error. Neovim continues to run after you hit enter.

> Does the bsd package include the treesitter parsers?

I've been using them with my config for ages, so I believe(d) so, but now I'm not so sure!

[Here's the packing list for our package](https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/editors/neovim/pkg/PLIST?rev=1.23&content-type=text/x-cvsweb-markup)


The only files I see related to treesitter are:
```
share/nvim/runtime/lua/vim/treesitter/
share/nvim/runtime/lua/vim/treesitter.lua
share/nvim/runtime/lua/vim/treesitter/_fold.lua
share/nvim/runtime/lua/vim/treesitter/_meta.lua
share/nvim/runtime/lua/vim/treesitter/_query_linter.lua
share/nvim/runtime/lua/vim/treesitter/_range.lua
share/nvim/runtime/lua/vim/treesitter/dev.lua
share/nvim/runtime/lua/vim/treesitter/health.lua
share/nvim/runtime/lua/vim/treesitter/highlighter.lua
share/nvim/runtime/lua/vim/treesitter/language.lua
share/nvim/runtime/lua/vim/treesitter/languagetree.lua
share/nvim/runtime/lua/vim/treesitter/query.lua
```

Should we expect some other TS files?

>  Nvim 0.10 expects the lua treesitter .so file to be available on 'runtimepath'.

Our neovim port depends on our existing tree-sitter package, rather than statically including it.

We use `-DUSE_BUNDLED=OFF` to achieve that (but note that we do statically embed some stuff with strict version requirements, like luajit and some related lua libs)

Our tree-sitter package is v0.22.6. Should that be OK?

My guess, based on all of this, is that bundling turns off installing the parsers and it's been working for me because I use the `nvim-treesitter/nvim-treesitter` package which is auto-fetching the parsers.

Does that sound feasible?

Maybe I need to do something similar to what FreeBSD does [here](https://cgit.freebsd.org/ports/tree/editors/neovim/Makefile#n55).

Would it be better for neovim package to bundle the parsers, or for the treesitter package to bundle them (if that's even possible)?

Thanks

**Comment by clason** [comment]
> My guess, based on all of this, is that bundling turns off installing the parsers and it's been working for me because I use the nvim-treesitter/nvim-treesitter package which is auto-fetching the parsers.

Yes.

> Maybe I need to do something similar to what FreeBSD does [here](https://cgit.freebsd.org/ports/tree/editors/neovim/Makefile#n55).

Yes.

> Would it be better for neovim package to bundle the parsers

Yes, since queries are only guaranteed to be compatible with a specific parser version, and you can't expect two editors to agree on which.

**Comment by vext01** [comment]
Thank you! Much appreciated.

**Comment by zeertzjq** [comment]
`USE_BUNDLED_TS_PARSERS` can be set separately
