### ISSUE TITLE
normal command to add blank line above/below cursor

### ISSUE THREAD

**Issue by nikitarevenco** [neovim/neovim#30779]
### Problem

For some people it is quite a common task to add empty space between functions / statements in code. Usually, this is done by using `ok` or `Oj` and then moving to the previous line. But this isn't ideal because:
- it doesn't maintain exact cursor position. if we use a mark, the command becomes a lot longer
- we can't create multiple lines this way by prefixing it with a count 

### Expected behavior

I propose that there will be added 2 default keymappings to add add empty line above and below:

```lua
vim.keymap.set("n", "gL", "<cmd>call append(line('.') - 1, repeat([''], v:count1))<CR>", { desc = "empty line above" })

vim.keymap.set("n", "gl", "<cmd>call append(line('.'), repeat([''], v:count1))<CR>", { desc = "add empty line below" })
```

the keymappings are just a suggestion from me , since `go` and `gO` are both taken and `gl` & `gL` are both available

mnemonic: "L" for "**L**ine"

**Comment by justinmk** [comment]
If we add this we should copy the choices from https://github.com/tpope/vim-unimpaired .

**Comment by nikitarevenco** [comment]
> If we add this we should copy the choices from https://github.com/tpope/vim-unimpaired .

> There are linewise mappings. [<Space> and ]<Space> add newlines before and after the cursor line. [e and ]e exchange the current line with the one above or below it.

Ok, then how about also adding `[e` and `]e` to swap lines? This is functionality that i find myself using quite often.

**Comment by AndreiSva** [comment]
> > If we add this we should copy the choices from https://github.com/tpope/vim-unimpaired .
> 
> > There are linewise mappings. [ and ] add newlines before and after the cursor line. [e and ]e exchange the current line with the one above or below it.
> 
> Ok, then how about also adding `[e` and `]e` to swap lines? This is functionality that i find myself using quite often.


You can very easily swap lines with `ddp`, this is unnecessary.

**Comment by justinmk** [comment]
> swap lines with `ddp`

The use-case for `]e` is that it is dot-repeatable and doesn't set the `"` register.

**Comment by yochem** [comment]
Here's a Lua implementation, adapted from https://github.com/tummetott/unimpaired.nvim and using unimpaired's keymaps.

```lua
vim.keymap.set('[<Space>', function()
    local repeated = vim.fn["repeat"]({""}, vim.v.count1)
    local line = vim.api.nvim_win_get_cursor(0)[1]
    vim.api.nvim_buf_set_lines(0, line-1, line-1, true, repeated)
end, { desc = 'Add empty line above cursor', silent = true })

vim.keymap.set(']<Space>', function()
    local repeated = vim.fn["repeat"]({""}, vim.v.count1)
    local line = vim.api.nvim_win_get_cursor(0)[1]
    vim.api.nvim_buf_set_lines(0, line, line, true, repeated)
end, { desc = 'Add empty line below cursor', silent = true }})
```

If this is a desired feature, I can make a PR for it.
