### ISSUE TITLE
:execute 'normal!' "g\<C-]>" cannot select list tags

### ISSUE THREAD

**Issue by epheien** [neovim/neovim#30789]
### Problem

`:execute 'normal!' "g\<C-]>"` cannot select list tags when there are more than one item.

I can stably reproduce this issue on Ubuntu 22.04, and I expect it to be easily reproduced on other Ubuntu systems as well.

The same steps cannot be replicated in macOS because shm_unlink only has one tag matching.

### Steps to reproduce

nvim --clean
:Man shm_open
(move cursor to shm_unlink word)
:exec 'normal!' "g\<C-]>"

### Expected behavior

list tags to select

### Nvim version (nvim -v)

v0.11.0-dev-958+g45f8f957c

### Vim (not Nvim) behaves the same?

vim has anthoer error

### Operating system/version

ubuntu 22.04

### Terminal name/version

alacritty + ssh on macOS

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by zeertzjq** [comment]
This is working as intended:
```
			{commands} should be a complete command.  If
			{commands} does not finish a command, the last one
			will be aborted as if <Esc> or <C-C> was typed.
```
