### ISSUE TITLE
Neovim freezes when i exit fullscreen mode on OSX

### ISSUE THREAD

**Issue by erf** [neovim/neovim#3079]
Neovim freezes when i exit fullscreen mode on OSX (10.10.4)

Commit: 8cbe5265ef22b7f320b6c0dcabd4e74b97114b0b

**Comment by fmoralesc** [comment]
Does it also freeze on `:winsize`, `set col=` or `set lines=` for you? @mhinz tried the resize patches on iTerm2, but I can't test on OSX directly...

**Comment by erf** [comment]
I can resize the window, but when i try to exit fullscreen mode it hangs (i updated the title and comment).

**Comment by erf** [comment]
Tested in the Terminal Version 2.5.3 (343.7)

**Comment by mhinz** [comment]
Hmm, works for me using the exact same version.

I don't think it makes any difference, but do experience the same behaviour with `nvim -u NONE`? What's  the output of `echo $TERM`?

**Comment by erf** [comment]
1) same problem
2) xterm-256color
3) on iTerm2 it works

I also tried changing the theme to basic

**Comment by erf** [comment]
I found out this only happens when i'm on my external screen via mini display port. 
Resolution 2560x1440

**Comment by erf** [comment]
And probably happened in one of the latest commits. I see there are some changes with screen refresh..

**Comment by mhinz** [comment]
You could check `Console` if there's anything about nvim in the `User Diagnostic Reports` section.

**Comment by erf** [comment]
Could not find anything in Console

**Comment by mhinz** [comment]
What's the output of `ps aux | grep nvim` when nvim is hanging?

**Comment by justinmk** [comment]
Maybe add logging to ui_resize to see the values before exit.

**Comment by erf** [comment]
@mhinz <pre>50722   0.0  0.0  2468560   6776 s001  S+    6:12PM   0:00.06 nvim</pre>
(i had to use iterm2 to write the command..)

**Comment by erf** [comment]
I have this issue on both my home and work macbook pro.

**Comment by danielcotton** [comment]
I can reproduce this - but it's Terminal.app freezing up, not neovim.
I've narrowed it down to [here](https://github.com/neovim/neovim/commit/8cbe5265ef22b7f320b6c0dcabd4e74b97114b0b#diff-3ac88981a139ac0eee448a6bd19c7569R358). If out() isn't called at that point, Terminal.app doesn't hang.

The problem here AFAICT is that Terminal.app seems to attempt to return the size to what it was before full screen, but neovim then tries to resize the window to the same size as when it was full screen. This loops, giving the appearance of hanging. In reality, it's just fluctuating between window sizes.

**Comment by fmoralesc** [comment]
Great find, @danielcotton. Initially that was guarded with a $TERM check, but it was decided it wasn't worth it. We might need to reconsider. What is the $TERM Terminal.app reports? 

Now, a fuller fix would be to include some logic to prevent that resize on certain events.

**Comment by danielcotton** [comment]
Terminal.app defaults to `xterm-256color` but can be set from the GUI to any of the following:

* ansi
* dtterm
* nsterm
* rxvt
* vt52
* vt100
* vt102
* xterm
* xterm-16color
* xterm-256color

**Comment by fmoralesc** [comment]
Ah, in that case it won't help to check for $TERM.

**Comment by erf** [comment]
This is not a problem anymore.

**Comment by fmoralesc** [comment]
Probably a side-effect of #3145.
