### ISSUE TITLE
Slow j and k, but quick arrows?

### ISSUE THREAD

**Issue by fegyi001** [neovim/neovim#30829]
### Problem

I started to experience quite a strange behaviour. The j and k keys started lagging, which makes using them quite unreliable. I was wondering whether my plugins are causing that neovim became slow. But then I realized that the arrow down and up keys are as fast as ever. 

Is it only me? I did not really changed my configuration at all lately.

### Steps to reproduce

open any file
start navigating up and down with j and k

### Expected behavior

The j and k keys should be acting fast.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

vi behaves all right

### Operating system/version

macOS 15.0.1

### Terminal name/version

iTerm2 3.5.5

### $TERM environment variable

screen-256color

### Installation

homebrew

**Comment by clason** [comment]
Always test with `nvim --clean`.

**Comment by fegyi001** [comment]
I realized I messed up my folke/flash.nvim config
