### ISSUE TITLE
vim.lsp.buf.hover() disables diagnostics

### ISSUE THREAD

**Issue by yangkev** [neovim/neovim#30822]
### Problem

Whenever `vim.lsp.buf.hover()` is called, this disables all diagnostics in the buffer.

This can be quite annoying because you have to continuously toggle diagnostics back on again everytime you peak at symbol documentation with `K`.

I'd like for diagnostics to not be disabled whenever `vim.lsp.buf.hover()` is called.

### Steps to reproduce

`minimal.lua`:

```
-- Install Lazy plugin manager if not already installed
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Setup Lazy to manage plugins
require("lazy").setup({
  -- LSP config plugin
  {
    "neovim/nvim-lspconfig",
    config = function()
      local lspconfig = require("lspconfig")

      -- Set up LSP server (e.g., pyright for Python)
      lspconfig.pyright.setup({})

      -- Diagnostics config
      vim.diagnostic.config({
        virtual_text = true, -- Show inline diagnostic messages
        signs = true, -- Show signs in the gutter
        underline = true, -- Underline problematic code
        update_in_insert = false, -- Do not update diagnostics in insert mode
        float = { border = "rounded" },
      })

      -- Keymap for hover
      vim.api.nvim_set_keymap("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", { noremap = true, silent = true })

      -- Enable diagnostics globally
      vim.diagnostic.enable(0)

      -- Optional: Highlight the line with diagnostics
      vim.cmd([[autocmd CursorHold * lua vim.diagnostic.open_float(nil, {focus=false})]])

      -- On attach function to print diagnostics on hover
      local on_attach = function(client, bufnr)
        -- Hover documentation keymap
        vim.api.nvim_buf_set_keymap(
          bufnr,
          "n",
          "K",
          "<cmd>lua vim.lsp.buf.hover()<CR>",
          { noremap = true, silent = true }
        )

        -- Print diagnostics in floating window on cursor hold
        vim.api.nvim_create_autocmd("CursorHold", {
          buffer = bufnr,
          callback = function()
            vim.diagnostic.open_float(nil, { focus = false })
          end,
        })
      end

      -- Attach LSP servers
      lspconfig.pyright.setup({
        on_attach = on_attach,
      })
    end,
  },
})

-- Basic options
vim.o.completeopt = "menuone,noselect"
```
file.py:
```python
from datetime import datetime


datetime.fromisoformat("2024-10-14")
print now  # should show a diagnostic error
```

Run:
```
nvim --clean -u minimal.lua file.py
```

1. See that diagnostics are showing
2. Use `K` to hover over anything, observe that diagnostics go away `vim.diagnostic.is_enabled()` becomes `False`

Here's an [asciinema](https://asciinema.org/a/J7G5zhSlEQ8kmBCZrOJSTk4Dj) that demonstrates this 
![Image](https://github.com/user-attachments/assets/78c1d111-71a4-47b0-a646-ae9964fe68ee)
 

### Expected behavior

I would expect Diagnostics to remain unchanged (and still be enabled if they started enabled) when using `vim.lsp.buf.hover()`.

### Nvim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Vim (not Nvim) behaves the same?

no

### Operating system/version

14.5 (23F79)

### Terminal name/version

alacritty, tmux

### $TERM environment variable

tmux-256color

### Installation

brew

**Comment by justinmk** [comment]
Thank you for the thorough details. Why is lazy.nvim required, are you sure it isn't related? This issue does not occur for me in a lua / LuaLS buffer.

**Comment by yangkev** [comment]
Thanks, I think this is in fact a `lazy.nvim` issue. asked [here](https://github.com/folke/lazy.nvim/issues/1778)
