### ISSUE TITLE
Add lemonade option for `vim.ui.open`

### ISSUE THREAD

**Issue by uthmanmoh** [neovim/neovim#30837]
### Problem

`vim.ui.open` should support [lemonade](https://github.com/lemonade-command/lemonade) as an option, similar to how `lemonade` is an option for the clipboard.

Currently neovim uses `lemonade copy` and `lemonade paste` to support copy and pasting through an ssh connection (see `:h clipboard-tool`), but `lemonade` also supports a `lemonade open` to open url's from within an ssh connection in the host machine.

This should simply just be a change above https://github.com/neovim/neovim/blob/fae4d3fa1b65b7632d048cad2a1beb7afaa61c21/runtime/lua/vim/ui.lua#L168 to add
```lua
elseif vim.fn.executable('lemonade') == 1 then
    cmd = { 'lemonade', 'open', path }
```

I'm willing to make this PR if given approval for the idea, but open to others implementing as well

### Expected behavior

This would allow users to use `vim.ui.open` (through `gx` or other means) to open files/links through an ssh connection

**Comment by justinmk** [comment]
sure, pr welcome
