### ISSUE TITLE
LSP: Error with LSP Semantic Tokens when Zig code contains non-ASCII characters preceded by "\\"

### ISSUE THREAD

**Issue by hmgle** [neovim/neovim#30832]
### Problem

When opening a Zig file containing multi-line strings that start with a backslash followed by non-ASCII characters(e.g., `\\µ`), Neovim encounters an error related to semantic tokens. This issue appears to be related to the implementation of `util._str_byteindex_enc` in `runtime/lua/vim/lsp/util.lua`.

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Ensure Neovim is set up with a Zig LSP (e.g., zls).
2. Create a new Zig file with the following content:

```zig
pub fn main() !void {
    const std = @import("std");
    const a =
        \\µs
        \\
    ;
    std.debug.print("{s}", .{a});
}
```

3. Open the file in Neovim.

### Expected behavior

The Zig code should be parsed correctly, and no error should occur when strings contain `\\` followed by non-ASCII characters. The LSP semantic tokens should be handled properly, without causing an "index out of range" error.

### Nvim version (nvim -v)

NVIM v0.10.2

### Language server name/version

zls 0.13.0

### Operating system/version

Ubuntu 16.04.6 LTS

**Comment by clason** [comment]
Can you please share the concrete (full!) error?

**Comment by justinmk** [comment]
> This issue appears to be related to the implementation of `util._str_byteindex_enc` in `runtime/lua/vim/lsp/util.lua`.

@tris203 is there a PR that @hmgle can try which might fix this?

**Comment by tris203** [comment]
> > This issue appears to be related to the implementation of `util._str_byteindex_enc` in `runtime/lua/vim/lsp/util.lua`.
> 
> @tris203 is there a PR that @hmgle can try which might fix this?

Yes #30747

**Comment by hmgle** [comment]
> Can you please share the concrete (full!) error?

Oh, yes. The error message:
```
Error executing vim.schedule lua callback: ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index
out of range
stack traceback:
        [builtin#36]: at 0x010d175660
        ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'
        ...m-macos-x86_64/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149: index
out of range
stack traceback:
        [builtin#36]: at 0x010d175660
        ...86_64/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'
        ...m-macos-x86_64/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Comment by hmgle** [comment]
> > This issue appears to be related to the implementation of `util._str_byteindex_enc` in `runtime/lua/vim/lsp/util.lua`.
> 
> [@tris203](https://github.com/tris203) is there a PR that [@hmgle](https://github.com/hmgle) can try which might fix this?

Thank you for your response! It worked perfectly.
