### ISSUE TITLE
validate is called with wrong arguments

### ISSUE THREAD

**Issue by temhelk** [neovim/neovim#30848]
### Problem

I got an error where I think validate is called incorrectly after recent commits

```
E5108: Error executing lua [string ":lua"]:1: test: expected n, got number (5)
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	[string ":lua"]:1: in main chunk
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:891: opts.offset_x: expected n, got number (2)
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	/usr/share/nvim/runtime/lua/vim/lsp/util.lua:891: in function 'make_floating_popup_options'
	/usr/share/nvim/runtime/lua/vim/lsp/util.lua:1650: in function 'open_floating_preview'
	.../nvim/lazy/lsp_signature.nvim/lua/lsp_signature/init.lua:608: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/client.lua:683: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

I think this change breaks it: https://github.com/neovim/neovim/commit/0066dd0f653e9321ea77fd54a017e96d457307d3#diff-de132e20a0c678f2ff3234a05d868b0d118561cb72317910e7f28839640ed2e3R936

In this form validate cannot be used with `'n'`

This produces an error: `lua vim.validate("test", 5, "n", true)`
White this does not: `lua vim.validate("test", 5, "number", true)`

### Steps to reproduce

nvim --clean
:lua vim.lsp.util.make_floating_popup_options(1, 1, {offset_x = 1})

### Expected behavior

Should not produce an error

### Nvim version (nvim -v)

v0.11.0-dev-989+g3f3e4837d5

### Vim (not Nvim) behaves the same?

nvim only

### Operating system/version

Linux

### Terminal name/version

doesn't matter

### $TERM environment variable

doesn't matter

### Installation

AUR dev version

**Comment by justinmk** [comment]
Thanks for debugging that, pr welcome if you have a minute.

**Comment by temhelk** [comment]
I opened a pr. I also searched to check whether there are other bad calls like that, and it looks like it was the only one.
