### ISSUE TITLE
vdebug does not work: NvimError: Vim(wincmd):E16: Invalid range: 7wincmd w

### ISSUE THREAD

**Issue by mjacobus** [neovim/neovim#3086]
Hey guys

I got this error when using [this](https://github.com/joonty/vdebug) plugin.

    NvimError: Vim(wincmd):E16: Invalid range: 7wincmd w

I have no idea if this is a nvim bug or a plugin bug, but I decided to post it here because it may be related to some BC and hopefully the stack trace contains important debugging info.

Here is the screenshot:

![vdebug_on_nvim](https://cloud.githubusercontent.com/assets/226834/8848799/9ac10330-313a-11e5-878d-c7ffed34251e.png)

Cheers!

**Comment by mhinz** [comment]
Looks like a plugin issue. It tries to switch to the 7th window in the current tabpage, but it doesn't exist.
