### ISSUE TITLE
Please consider establishing a centralized extension repository, similar to melpa.org for Emacs.

### ISSUE THREAD

**Issue by SadSock** [neovim/neovim#30862]
### Problem

Indeed, it is a valid point. Establishing a centralized plugin repository would greatly benefit companies whose development machines are located within internal networks that do not have direct access to GitHub. By creating a mirror within the company's intranet, the installation of plugins could be facilitated seamlessly.

### Expected behavior

t would be great if a centralized addon repository could be created, taking inspiration from melpa.org for Emacs extensions.

**Comment by clason** [comment]
No.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/24221

Having a centralized index might be feasible eventually, though https://dotfyle.com/neovim/plugins/ is doing a pretty good job currently. But I don't think it will make sense for us to host the actual bits.
