### ISSUE TITLE
`Internal error: qf_fill_buffer()` when updating quickfix list inside of `DiagnosticChanged` callback

### ISSUE THREAD

**Issue by jfly** [neovim/neovim#30867]
### Problem

I'm trying to keep my quickfix list in sync with Neovim's diagnostics through a `DiagnosticChanged` autocmd that calls `vim.diagnostic.setqflist`. This mostly works, but when closing Neovim,I get the following error:

```
Error executing vim.schedule lua callback: Vim:E685: Internal error: qf_fill_buffer()
stack traceback:
        [C]: in function 'setqflist'
        ...wrapped-0.10.2/share/nvim/runtime/lua/vim/diagnostic.lua:808: in function 'set_list'
        ...wrapped-0.10.2/share/nvim/runtime/lua/vim/diagnostic.lua:1963: in function 'setqflist'
        ...eremy/sync/scratch/jfly/2024-10-18-vim-crash/minimal.lua:43: in function <...eremy/sync/scratch/jfly/2024-10-18-vim-crash/minimal.lua:41>
```

It feels like this callback is getting invoked sometime during Vim's shutdown lifecycle when the quickfix list can no longer be written to?

### Steps to reproduce

<details>
<summary>minimal.lua</summary>

```lua
-- Run this file as `nvim --clean -u ./minimal.lua hgttg.py

for name, url in pairs {
  nonels = 'https://github.com/nvimtools/none-ls.nvim',
  plenary = 'https://github.com/nvim-lua/plenary.nvim.git', -- none-ls depends on this
  
  lspconfig = 'https://github.com/neovim/nvim-lspconfig',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

vim.lsp.set_log_level("debug")

require('lspconfig').ruff.setup {}

local null_ls = require("null-ls")
null_ls.setup({
    debug = true,
    sources = {
      null_ls.builtins.formatting.black,
    },
})

vim.api.nvim_create_autocmd('DiagnosticChanged', {
  callback = function(args)
    local window_height = vim.api.nvim_win_get_height(0)
    for i = 1, window_height do
        vim.print(i .. "/" .. window_height .. " filling up the screen")
    end
    vim.print(vim.inspect(args))

    vim.schedule(function()
      vim.diagnostic.setqflist({ open = false })
    end)
  end,
})

vim.cmd "copen"
```
</details>

<details>
<summary>hgttg.py</summary>

```
print(f"don't panic")
print(f"don't panic")
print(f"don't panic"  )
print(f"don't panic")
print(f"don't panic")

```
</details>

Run with both `ruff` and `black` on your PATH:

```
nvim --clean -u ./minimal.lua hgttg.py
```

This will open Neovim with a quickfix list that looks something like this:

![Image](https://github.com/user-attachments/assets/b41ad2c6-56e2-452e-ad13-276a42b6cc6f)

Then, close Neovim with `:qa`. Scroll down through the output until you see the error:

![Image](https://github.com/user-attachments/assets/17f3afc9-e793-4198-9430-eb6208f4ebbb)

<hr>

Sorry for such a complicated "minimal" repo. I've spent many hours trying to simplify this, and just don't have a good enough mental model of Neovim's exit lifecycle to simplify this. Happy to investigate more if folks point me in the right direction.

### Expected behavior

I would expect Neovim to not crash here. In other words: ideally the quickfix buffer would be writeable whenever `DiagnosticChanged` events fire. If that's not feasible, I'd love to know what the right way is to check if the quickfix list is writeable, I haven't been able to find anything that works.

### Nvim version (nvim -v)

I can repro this issue on both `master` (4833a63929a83c11379036ead33913711134015b at time of writing) and Neovim 0.10.2

### Vim (not Nvim) behaves the same?

N/A, this is LSP specific

### Operating system/version

NixOS

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

### Installation

both build from repo and nixpkgs

**Comment by justinmk** [comment]
I suppose you tried reverting https://github.com/neovim/neovim/pull/30820 ?

**Comment by jfly** [comment]
Wow, thank you @zeertzjq for the quick fix! I can confirm that this addresses my issue.
