### ISSUE TITLE
nvim closed on run :bd command

### ISSUE THREAD

**Issue by carlitux** [neovim/neovim#3087]
Hi,

Some times when I run bd command closes nvim and sometimes just close the buffer.

**Comment by mhinz** [comment]
`:bdelete` never closes nvim. Try reproducing it with `nvim -u NONE`.

It's probably a plugin doing magic on the `BufDelete` event. Check `:au BufDelete` for potential culprits.

**Comment by justinmk** [comment]
Lacks details, can't reproduce. Closing.
