### ISSUE TITLE
`vim.version.parse` throws error for invalid version string instead of returning `nil`

### ISSUE THREAD

**Issue by chipsenkbeil** [neovim/neovim#30883]
### Problem

When using `vim.version.parse()` to parse an invalid version string, the function throws an error instead of returning `nil` as described in the documentation.

![Image](https://github.com/user-attachments/assets/e532abe7-af72-401f-80fd-eed07076511a)

### Steps to reproduce

1. Run `nvim -u NONE` to start neovim without any influence of plugins or other scripts.
2. Run `:lua print(vim.inspect(vim.version.parse("1")))` and observe that a version object is printed.
3. Run `:lua print(vim.inspect(vim.version.parse("a")))` and observe that an error is thrown instead of `nil` being printed.

### Expected behavior

Based on the documentation, if the input is invalid, `nil` should be returned. So printing `vim.inspect(vim.version.parse("a"))` should print out `nil`.

### Nvim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1725453128

### Vim (not Nvim) behaves the same?

Not applicable

### Operating system/version

macOS 14.5 (23F79)

### Terminal name/version

wezterm 20230712-072601-f4abf8fd

### $TERM environment variable

xterm-256color

### Installation

brew install neovim

**Comment by justinmk** [comment]
`:lua =vim.version.parse("a")` works for me in Nvim 0.11

0.10.2 is the latest stable version
