### ISSUE TITLE
Invalid syntax in vimfn.lua

### ISSUE THREAD

**Issue by ObserverOfTime** [neovim/neovim#30882]
### Problem

These parameter names are not valid in Lua:
https://github.com/neovim/neovim/blob/9b8907d90508d7b66f025bbd1f5a48a78c5ce035/runtime/lua/vim/_meta/vimfn.lua#L233-L233

### Steps to reproduce

Spotted the issue in [tree-sitter-lua CI](https://github.com/tree-sitter-grammars/tree-sitter-lua/actions/runs/11425185774#summary-31786536598).

### Expected behavior

The generator should rename invalid parameters.

### Nvim version (nvim -v)

v0.11.0-dev-1007+g9b8907d905-dirty

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

konsole 23.08.5

### $TERM environment variable

konsole-256color

### Installation

build from repo

**Comment by justinmk** [comment]
> Spotted the issue in [tree-sitter-lua CI](https://github.com/tree-sitter-grammars/tree-sitter-lua/actions/runs/11425185774#summary-31786536598).

Are you using LuaLS "check" feature? Eventually we want something like that in our CI, once it's mature...

**Comment by ObserverOfTime** [comment]
> Are you using LuaLS "check" feature?

No, it just runs `tree-sitter parse`. But LuaLS also reports the error.

**Comment by justinmk** [comment]
would you mind sending a pr

**Comment by ObserverOfTime** [comment]
For tree-sitter or LuaLS?
