### ISSUE TITLE
latest neovim on arch linux

### ISSUE THREAD

**Issue by sineptic** [neovim/neovim#30885]
### Problem

I upgrade neovim using pacman to latest 0.10.2-2 version and can't start it because
```
nvim: error while loading shared libraries: libmsgpack-c.so.2: cannot open shared object file: No such file or directory
```
and also tree-sitter

When I update it manually, it start to work.
Please update dependencies of arch package.

### Steps to reproduce

update to latest neovim version

### Expected behavior

update dependencies automatically

### Nvim version (nvim -v)

0.10.2-2

### Vim (not Nvim) behaves the same?

-

### Operating system/version

Arch linux 

### Terminal name/version

-

### $TERM environment variable

-

### Installation

Arch

**Comment by zeertzjq** [comment]
Not an Nvim issue
