### ISSUE TITLE
Segfault with fzf and ardagnir/united-front

### ISSUE THREAD

**Issue by rtwo** [neovim/neovim#3089]
This is probably not very important since united-front isn't working with neovim anyway, but its a segfault... 

Commit: 0e65caa40ed9dbd1e06d023cd7eadce16f444f30  

Compilation: /usr/bin/cc -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-par
ameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG
_H -I/home/martin/src/neovim/config -I/home/martin/src/neovim/src -I/usr/include -I/
usr/include -I/usr/include/luajit-2.0 -I/home/martin/src/neovim/.deps/usr/include -I
/home/martin/src/neovim/.deps/usr/include -I/usr/include -I/usr/include -I/usr/inclu
de -I/home/martin/src/neovim/src/nvim/auto -I/home/martin/src/neovim/include        
                                                                                    
Optional features included (+) or not (-): +acl   +iconv    +jemalloc

```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'ardagnir/united-front'
nnoremap <Leader>ff :call fzf#run({
            \'source': 'git ls-files \| grep -v node_modules',
            \'sink' : 'e',
            \'options' : '-m',
            \'down' : '20',
            \'window' : 'vertical',
            \})<Cr>
```

1. Open nvim
2. <leader>ff
4. change window
5. change window back to the terminal
6. :q

After that it crashes very often but not always.

I'v got a number of different segfaults from this:

```
 [Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000048f4ad in free_unref_items (copyID=copyID@entry=6)
    at /home/martin/src/neovim/src/nvim/eval.c:5573
5573	    if ((dd->dv_copyID & COPYID_MASK) != (copyID & COPYID_MASK)
(gdb) bt
#0  0x000000000048f4ad in free_unref_items (copyID=copyID@entry=6)
    at /home/martin/src/neovim/src/nvim/eval.c:5573
#1  0x000000000048f6b2 in garbage_collect () at /home/martin/src/neovim/src/nvim/eval.c:5537
#2  0x00000000005417e7 in before_blocking () at /home/martin/src/neovim/src/nvim/getchar.c:1334
#3  0x000000000056e5b2 in os_inchar (buf=buf@entry=0x7f34d871e94f "", maxlen=maxlen@entry=64, 
    ms=ms@entry=-1, tb_change_cnt=tb_change_cnt@entry=164)
    at /home/martin/src/neovim/src/nvim/os/input.c:97
#4  0x0000000000541a8b in inchar (buf=0x7f34d871e94f "", maxlen=194, wait_time=-1, 
    tb_change_cnt=164) at /home/martin/src/neovim/src/nvim/getchar.c:2460
#5  0x00000000005437e9 in vgetorpeek (advance=advance@entry=1)
    at /home/martin/src/neovim/src/nvim/getchar.c:2280
#6  0x00000000005439f4 in vgetc () at /home/martin/src/neovim/src/nvim/getchar.c:1395
#7  0x0000000000543dd8 in safe_vgetc () at /home/martin/src/neovim/src/nvim/getchar.c:1515
#8  0x0000000000550145 in normal_cmd (oap=oap@entry=0x7ffd782c7fa0, toplevel=toplevel@entry=true)
    at /home/martin/src/neovim/src/nvim/normal.c:491
#9  0x0000000000533428 in main_loop (cmdwin=cmdwin@entry=0, noexmode=noexmode@entry=0)
    at /home/martin/src/neovim/src/nvim/main.c:747
#10 0x000000000053435e in main (argc=<optimized out>, argv=<optimized out>)
    at /home/martin/src/neovim/src/nvim/main.c:534
```

http://pastebin.com/nQJV7U8E 

I can provide more bts if needed.

**Comment by justinmk** [comment]
Thanks for the report. We have several similar issues, e.g. https://github.com/neovim/neovim/issues/3070 so will consider this under the same umbrella.
