### ISSUE TITLE
iTerm2 + neovim on macbook delete button (Fn+BS) issues

### ISSUE THREAD

**Issue by slbug** [neovim/neovim#30900]
### Problem

instead of deleting characters it produces weird symbols. 

### Steps to reproduce

run `nvim --clean` in iTerm2 (Build 3.5.6beta2) on Intel macbook with latest macos sequoia 

type some text, move cursor in middle of text, press Fn+Backspace. 

It was fine few weeks ago actually, I don't know what broke it - new iTerm2, new macos or newer build of neovim.

I've tried remapping keycodes, removed all key mappings from iTerm, used clean bash without any profile or rc files. nothing changes this behaviour. 

Also in iTerm Fn+BS works correct, but when i run `:terminal` from nvim it does this weird chars instead of delete. 

Also it works correctly in regular Terminal app

### Expected behavior

It deletes character

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1016+gca7855c5b-Homebrew

### Vim (not Nvim) behaves the same?

no, 9.0

### Operating system/version

macOS 15.0.1

### Terminal name/version

iTerm2 (Build 3.5.6beta2)

### $TERM environment variable

xterm-256color

### Installation

brew

**Comment by slbug** [comment]
Just checked on stable 3.5.5 iTerm2. It works as expected. So probably it's iTerm issue

**Comment by danbeam** [comment]
Hola,

I know this is an iTerm issue but I was also searching for a fix and summarized my findings here:
https://stackoverflow.com/a/79179408/234201

Hope this helps!
