### ISSUE TITLE
winhl set with win_set_hl_ns and and nvim_set_hl seems to reset when switching buffer

### ISSUE THREAD

**Issue by smilhey** [neovim/neovim#30904]
### Problem

https://github.com/user-attachments/assets/eb873bb1-6472-4e1a-b0c5-4b04861730bd

### Steps to reproduce

nvim --clean then luafile the following code this then hit Space-Z before switching to a different buffer 

```lua 
local M = { enabled = false, ns = vim.api.nvim_create_namespace("Zen") }

vim.api.nvim_set_hl(M.ns, "NormalFloat", { link = "Normal" })

local function zen()
	local zen_width = math.floor(vim.o.columns * 0.7)
	local zen_col = math.floor(vim.o.columns * 0.15)
	if not M.enabled then
		local curr_buf = vim.api.nvim_get_current_buf()
		M.bg_buf = vim.api.nvim_create_buf(false, true)
		vim.bo[M.bg_buf].modifiable = false
		vim.bo[M.bg_buf].buftype = "nofile"
		vim.bo[M.bg_buf].bufhidden = "wipe"
		M.bg_win = vim.api.nvim_open_win(M.bg_buf, false, {
			relative = "editor",
			width = vim.o.columns,
			height = vim.o.lines,
			col = 1,
			row = 1,
			style = "minimal",
			zindex = 20,
			focusable = false,
		})
		M.zen_win = vim.api.nvim_open_win(curr_buf, true, {
			relative = "editor",
			width = zen_width,
			height = vim.o.lines,
			col = zen_col,
			row = 1,
			style = "minimal",
			zindex = 20,
		})
		vim.api.nvim_win_set_hl_ns(M.zen_win, M.ns)
		M.autocmd = vim.api.nvim_create_autocmd("BufWinEnter", {
			desc = "Zen",
			callback = function()
				-- vim.api.nvim_win_set_hl_ns(M.zen_win, M.ns)
				local new_win = vim.api.nvim_get_current_win()
				local is_float = vim.api.nvim_win_get_config(new_win).relative ~= ""
				if is_float then
					return
				else
					vim.api.nvim_del_autocmd(M.autocmd)
					vim.api.nvim_win_close(M.bg_win, true)
					if vim.api.nvim_win_is_valid(M.zen_win) then
						vim.api.nvim_win_close(M.zen_win, true)
					end
					M.enabled = not M.enabled
				end
			end,
		})
	else
		vim.api.nvim_del_autocmd(M.autocmd)
		vim.api.nvim_win_close(M.bg_win, true)
		vim.api.nvim_win_close(M.zen_win, true)
	end
	M.enabled = not M.enabled
end

vim.keymap.set("n", "<space>z", zen, { desc = "Zen" })
```

### Expected behavior

The float window should retain the highlight set with nvim_set_hl for the namespace "Zen"

### Nvim version (nvim -v)

v0.11.0-dev-1013+gc8e47f648

### Vim (not Nvim) behaves the same?

no

### Operating system/version

linux fedora 40

### Terminal name/version

kitty

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
It seems that the priority of `nvim_win_set_hl_ns` and 'winhighlight' doesn't work as documented at all: Whatever is set later takes precedence.

**Comment by shmerl** [comment]
@zeertzjq: What is the correct value that should be passed to `nvim_win_set_hl_ns` if I want to reset existing namespace to default? Both 0 and -1 seem to work, but is there a better choice?

Update:

This place seems to suggest that 0 is the best option (but -1 is also allowed?)

https://github.com/neovim/neovim/blob/master/src/nvim/api/window.c#L435C68-L435C87

**Comment by zeertzjq** [comment]
I don't know.

**Comment by shmerl** [comment]
According to the linked code, 0 seems to be the best choice.
