### ISSUE TITLE
Failed to load parser: uv_dlsym: no error

### ISSUE THREAD

**Issue by srghma** [neovim/neovim#30913]
### Problem

I am trying to make a pr https://github.com/nvim-treesitter/nvim-treesitter/pull/7274

but see an error 

```
Could not load parser for idris2: "...ghtly/share/nvim/runtime/lua/vim/treesitter/language.lua:136: Failed to load parser: uv_dlsym: no error"
```

https://github.com/neovim/neovim/blob/02749de7d5ffa9b0c809f93744d179d508c31206/src/nvim/lua/treesitter.c#L141

this is a treesitter I am trying to add https://github.com/srghma/tree-sitter-idris/commit/087ec56bde076ec7799428f5f9809866f7dfc894

I am using the  master build of neovim https://github.com/srghma/nixpkgs/commit/92ca8d01767adf24f925e1503766d670d2743f6e

### Steps to reproduce

can use the ci config to reproduce this error https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/11479201699/job/31944983585 

### Expected behavior

no error

### Nvim version (nvim -v)

NVIM v0.11.0-dev Build type: Release LuaJIT 2.1.1713773202 /nix/store/7lq4ak61qj6r1ybpnyjxfsi3jhc0cqdb-neovim-unwrapped-nightly/share/nvim

### Vim (not Nvim) behaves the same?

dont know

### Operating system/version

nixos

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

nixos

**Comment by clason** [comment]
I already answered your question at nvim-treesitter.
