### ISSUE TITLE
LSP: `vim.lsp.buf.definition` does not set tagstack

### ISSUE THREAD

**Issue by SanchayanMaity** [neovim/neovim#30926]
### Problem

Since commit 0083e03d6, `vim.lsp.buf.definition` does not seem to set the tag stack. This results in things like `C-o` being completely broken and jumping back to random places.

Seems this is also a known issue as mentioned in #30877 as well. 

### Steps to reproduce

With an LSP server like `clangd` or `rust-analyzer`, jump to a function definition with `vim.lsp.buf.definition` and then press `C-o`. Cursor does not come back to the initial location from where `vim.lsp.buf.definition` was triggered.

### Expected behavior

Jumping with `vim.lsp.buf.definition` and then pressing `C-o` should jump back to the initial location.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1035+g50e63c817

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.14.0 (22a44757)

### $TERM environment variable

tmux-256color

### Installation

Build from repo

**Comment by zeertzjq** [comment]
Do you mean `C-t` instead of `C-o`? `C-o` does not use the tagstack.

**Comment by SanchayanMaity** [comment]
I did mean `C-o` and `C-i`. I forgot when raising the issue that those mappings are with jumplist but that also use to work previous to that commit and still does when I revert the commit locally.

As noted by Kai, `C-t` gives the `E555: At bottom of tag stack` error.
