### ISSUE TITLE
snippets: show indicator for placeholders

### ISSUE THREAD

**Issue by ColinKennedy** [neovim/neovim#30944]
### Problem

In truth I still use LuaSnip so this feature may already exist but I had an idea and wanted to put it out there in case it doesn't exist. When expanding a snippet like `class`, it might make an output like this

```python
class Foo():
    def __init__(self, items) -> None:
        super().__init__()
```

Pressing `<Tab>` might jump the user's cursor to the () in `Foo()`, or maybe to the right of `self`, or maybe to somewhere in the `super()` line. Where will the cursor go? There's no way to know other than to press `<Tab>` or whichever mapping you've added for "jump to next tab stop" in the snippet to find out.

Wouldn't it be nice if the user could know in advance where their cursor will go? I could imagine being able to show that visually would be useful too for debugging.

### Expected behavior

I could imagine a couple ways to show an indicator

#### Extmarks / Inlay Hints
I could imagine a Lua function that can toggle / display the tab stops for the active snippet. So code like this

```python
class Foo():
    def __init__(self, parent) -> None:
        super().__init__(parent)
```

Might become

```python
class ${1:Foo}($2):
    def __init__(self, ${3:parent}) -> None:
        super().__init__(${3:parent})
```

Now there's no ambiguity about

- The order of the tabstops
- Replacing the `parent` text will edit other parts of the same snippet
- Tab stops with no default text are clearly shown

Then add a highlight group for this (default link it to `hl-Comment`, probably) and the indicators are looking good!

#### Highlighting
Basically the same as the previous idea but without the extmarks. Just expose a highlight group over the original text so people can customize the highlight color. In the above example, the words like `parent` or `()` would be a different color to indicate that it is jumpable. It's an okay idea but has 2 problems

- This method assumes that the tab stop position has default text. e.g. you need something to highlight to be able to highlight it. You could highlight the character before-and-after the tab stop position to get around that but it's a bit clunky
- Some tab stop points are shared. e.g. writing in text in one position might auto-fill another position. It's pretty common in snippets for that to happen. This isn't that bad but a bit unideal.

#### Conclusion
Anyway just a thought. It seemed like a useful thing to encourage adoption of the built-in LSP snippets. Maybe this already exists?

**Comment by MariaSolOs** [comment]
@ColinKennedy how is this different from what's currently implemented? Note that non-empty placeholders are highlighted using `hl-SnippetTabstop`, which links to `hl-Visual` by default:

![Image](https://github.com/user-attachments/assets/e90e0346-c9e6-4015-ac0a-d82b1d137e91)

**Comment by ColinKennedy** [comment]
From what you've shown it sounds like the "Highlighting" already exists. If the tab stop has empty default text does that still get shown?

Either way FWIW I think that's good enough. Though I'd consider "Extmarks / Inlay Hints" a nice to have for reasons listed above

```python
class ${1:Foo}($2):
    def __init__(self, ${3:parent}) -> None:
        super().__init__(${3:parent})
```

> - The order of the tabstops
> - Replacing the parent text will edit other parts of the same snippet
> - Tab stops with no default text are clearly shown

But if that doesn't sound that useful I suppose this suggestion can be backlogged / closed. Just wanted to throw out the idea in case it interested the group

**Comment by MariaSolOs** [comment]
> If the tab stop has empty default text does that still get shown?

No, if the tabstop has no placeholder then there's nothing to highlight.

I think that having indicators for the order of the tabstops might be out of scope for the core implementation, but still being able to see something for empty stops does sound like a nice feature to add.
