### ISSUE TITLE
Neovim with 'fsync' hangs on exit sometimes

### ISSUE THREAD

**Issue by Kazy** [neovim/neovim#30948]
### Problem

I've noticed that my Neovim sometimes hanged when I tried to exit for the past few days, forcing me to SIGKILL it.

I've bisected the issue and got to this PR (https://github.com/neovim/neovim/pull/30872) (commit: 8c2d45be77299d6eb70165697bc5c29898cdb25e).

I've managed to find a sure way to reproduce it using [Molten-nvim](https://github.com/benlubas/molten-nvim), but failed to make it work with a minimal example because of a call to `:UpdateRemotePlugin` that doesn't work for some reason (`E482: Can't open file /path/to/manifest for writing: no such file or directory`).

Thank you 🙏 

### Steps to reproduce

- `minimal.lua`

```lua
-- Run this file as `nvim --clean -u ./minimal.lua file.py

for name, url in pairs {
  molten = 'https://github.com/benlubas/molten-nvim',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.keymap.set('n', '<space>m', ':MoltenEvaluateLine<cr>')
```

- `file.py`
```python
# Do <leader>m on this file
print('hello world')

# Then on this line
import duckdb
```

- `mkdir -p $HOME/.local/share/jupyter/runtime`
- `nvim --clean -u minimal.lua file.py`
- Find a way to make `:UpdateRemotePlugin` work.
- You might need `pynvim` and `jupyter_client` installed in a venv first.
- Then do `<space>m` on the first non commentated line. Then same on the second.
- `:q`
- It should hang.

### Expected behavior

No hanging.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1045+gb922b7d6d7

### Vim (not Nvim) behaves the same?

no, not tested

### Operating system/version

6.11.5-zen1-1-zen

### Terminal name/version

Kitty master

### $TERM environment variable

xterm-kitty

### Installation

AUR package, with the git repository updated to the right commit with `makepkg -efsi` in between

**Comment by justinmk** [comment]
Does it happen if you set this option:

    :set nofsync

**Comment by Kazy** [comment]
> Does it happen if you set this option:
> 
> ```
> :set nofsync
> ```

No it doesn't !

**Comment by zeertzjq** [comment]
With the steps I get:
```
You Need to Initialize a Kernel First:
1: python3
```
And after typing `1`:
```
[Molten] Could not initialize kernel named 'python3'.
Caused By: [Errno 2] No such file or directory: '**/jupyter/runtime/kernel-*.json'
```

**Comment by Kazy** [comment]
> With the steps I get:
> 
> ```
> You Need to Initialize a Kernel First:
> 1: python3
> ```
> 
> And after typing `1`:
> 
> ```
> [Molten] Could not initialize kernel named 'python3'.
> Caused By: [Errno 2] No such file or directory: '**/jupyter/runtime/kernel-*.json'
> ```

Ah sorry, forgot to add that you need to create that folder. For me it's `mkdir -p $HOME/.local/share/jupyter/runtime`.

**Comment by zeertzjq** [comment]
Cannot reproduce with Nvim v0.11.0-dev-1054+gd24fb72c33 AUR package

**Comment by Kazy** [comment]
I can't reproduce it either now.. sorry for the waste of time, something must have been buggy with my filesystem or setup. I'll re-open if this happens again.
