### ISSUE TITLE
vim.inspect's options are undocumented

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#30960]
### Problem

`vim.inspect`'s docs show:

```
vim.inspect()                                                  *vim.inspect()*
    Gets a human-readable representation of the given object.

    Return: ~
        (`string`)

    See also: ~
      • |vim.print()|
      • https://github.com/kikito/inspect.lua
      • https://github.com/mpeterv/vinspect
```

and in particular do not mention that inspect takes a second argument which controls its output (actually it seems not to even mention it takes any arguments at all).

### Steps to reproduce

`:h vim.inspect`

### Expected behavior

It seems worthwhile to specifically call out arguments which can be used for suppressing newlines / making `vim.inspect` output shorter, e.g.:

```lua
vim.inspect({ foo = 'bar', baz = 37 }, { newline = ' ', indent = '' })
```

I also find the "See also" section itself slightly confusing. I've glanced over it a few times and never closely looked at the links, because I generally "don't care" about other implementations of `vim.indent` in Lua, and from a quick glance, that's what it had seemed like the links were for -- but that seems completely not the case, as looking at the source code shows `vim.indent` is literally `inspect.lua` vendored. That seems unclear to me, and I think it'd be useful to call that out explicitly so users know this isn't just a tangential see also, it's "more docs are over here".

### Nvim version (nvim -v)

NVIM v0.11.0-dev-973+gb7e896671-Homebrew

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

macOS 15.0.1

### Terminal name/version

Kitty 0.36.4

### $TERM environment variable

xterm-kitty

### Installation

Homebrew --head

**Comment by justinmk** [comment]
Not interested in spending time on this currently. The extra options are not important to mention.

**Comment by ashb** [comment]
Documenting the `depth` option in particular would be very helpful.

**Comment by telemachus** [comment]
All of the options seem worth documenting. I don't understand the decision to ignore them. Re "not...spending time on this," I'll happily make a PR.

**Comment by ashb** [comment]
@telemachus I suspect if someone opens a PR to document them it'd get merged
