### ISSUE TITLE
too many <MouseMove> events when using `&mousemoveevent`

### ISSUE THREAD

**Issue by errael** [neovim/neovim#30965]
### Problem

When `'mousemoveevent'` is true `neovim` can generate dozens of mouse events without changing the character position.

Sample output excerpt, using the test below, showing 30 events at line 13, col 27
```
Move 199 line 13, col 27                                                                            
Move 200 line 14, col 27                                                                            
...
Move 229 line 14, col 27                                                                            
Move 230 line 15, col 27                                                                            
```

### Steps to reproduce

To see the problem, source the following, move the mouse around, examine `:messages`
```lua
local ev = 0
vim.keymap.set('n', '<MouseMove>', function()
    local mp = vim.fn.getmousepos()
    ev = ev + 1
    vim.print(string.format("Move %d line %d, col %d", ev, mp.screenrow, mp.screencol)) 
end)
vim.o.mousemoveevent = true
```

### Expected behavior

Expect only one event per change of mouse character position

In `vim`'s `gui.c::gui_send_mouse_event()` there's
```
// Don't report a mouse move unless moved to a
// different character position.
if (button == MOUSE_MOVE)
```
There's something similar to this in `neovim`'s `mouse.c::jump_to_mouse()` but that seems unrelated to the mouse move event.

I vaguely recall seeing that fractional cells are a thing; but I don't see a way to get the fractional mouse position if this is the idea.

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/54249d051c3e0b97321939e6a3ae3d2e83971ce7

### Vim (not Nvim) behaves the same?

No. Only one event per character pos change since feature introduction: https://github.com/vim/vim/commit/c4cb544cd5beaa864b3893e4b8d0085393c7dbce

### Operating system/version

ubuntu

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by zeertzjq** [comment]
Actually with 'balloonevalterm' this happens in Vim as well:
```vim
let g:ev = 0
func MouseMove()
  let mp = getmousepos()
  let g:ev += 1
  echomsg $'Move {g:ev} line {mp.screenrow}, col {mp.screencol}'
endfunc
nnoremap <MouseMove> <Cmd>call MouseMove()<CR>
if exists('+balloonevalterm')
  set balloonevalterm
endif
set mousemoveevent
```

**Comment by errael** [comment]
Doh! Right, I was comparing apples and oranges (nvim-terminal vs vim-gui). (and what's with needing balloonevalterm for plain vim and not gvim? Sigh.)

> I've not found another terminal emulator that exhibits this behavior, but if GNOME Terminal doesn't change this, 
> maybe something should still be done.

At least it's very cheap to work around.

Are there any requirements/expectations for the gui's in this area? 

-----

BTW, there's some kind of issue with `key_name_entry` table, `get_special_key_name()` and K_MOUSEMOVE. A mouse move comes in as `0xffff9803` but K_MOUSEMOVE is `0xffff9b03` and so in the log there's `DBG ... state_enter:100: input: <t_?g>`

Quick and dirty, the following gets the key to display correctly in the log.
```
  //{ K_MOUSEMOVE,       "MouseMove" },
  { 0xffff9803,       "MouseMove" },
```

**Comment by zeertzjq** [comment]
> BTW, there's some kind of issue with `key_name_entry` table, `get_special_key_name()` and K_MOUSEMOVE. A mouse move comes in as `0xffff9803` but K_MOUSEMOVE is `0xffff9b03` and so in the log there's `DBG ... state_enter:100: input: <t_?g>`
> 
> Quick and dirty, the following gets the key to display correctly in the log.
> 
> ```
>   //{ K_MOUSEMOVE,       "MouseMove" },
>   { 0xffff9803,       "MouseMove" },
> ```

`0xffff9803` is not `<MouseMove>`. It's the result of the `<MouseMove>` mapping (or any mapping whose RHS is a Lua callback).

**Comment by errael** [comment]
Got it. Running a one liner `vim.o.mousemoveevent = true` shows move move events.

**Comment by errael** [comment]
Any idea of an easy to install `gui` that delivers `<MouseMove>` events? (for testing)

**Comment by zeertzjq** [comment]
From its source code it seems that https://github.com/tk-shirasaka/envim supports it. I haven't managed to build it though...

**Comment by errael** [comment]
> From its source code it seems that https://github.com/tk-shirasaka/envim supports that. I haven't managed to build it though...

Oh well; it doesn't have a release. Last week I put together
```diff
diff --git a/src/nvim/api/vim.c b/src/nvim/api/vim.c
--- a/src/nvim/api/vim.c
+++ b/src/nvim/api/vim.c
@@ -396,0 +397,3 @@
+  static int prev_row = -1;
+  static int prev_col = -1;
+
@@ -435,1 +438,7 @@
-  } else if (code != KE_MOUSEMOVE) {
+  } else if (code == KE_MOUSEMOVE) {
+    if (row == prev_row && col == prev_col) {
+      goto theend;
+    }
+    prev_row = row >= 0 ? row : 0;
+    prev_col = col;
+  } else {
@@ -465,0 +475,2 @@
+theend:
+  (void)0;
```
to address this problem. That's how I discovered that `nvim_input_mouse()` isn't used by `TUI`.

I haven't spent the time to track down how `TUI` sends the data to `nvim`. Since there's only one `TUI`, I'd put its fix there. But for `gui`, I'd probably use the above patch (assuming all the gui's go through this); in any event, it's a cheap way to make sure there isn't an issue. I don't know if a future pixel level mouse position is something of interest.

**Comment by zeertzjq** [comment]
You can look at where `check_multiclick()` is called.

**Comment by zeertzjq** [comment]
It's better to make the change `check_multiclick()` and its callers, as `check_multiclick()` already contains related comparisons.
