### ISSUE TITLE
Cannot use both unnamed and unnamedplus clipboards

### ISSUE THREAD

**Issue by zenbro** [neovim/neovim#3096]
```
vim -u NONE
:set clipboard=unnamed,unnamedplus
<insert some text>
yy
"*p
"+p
```
Expected behavior: both `+` and `*` registers should have same yanked text.
Actual behavior: `*` didn't changed, only `+` register have yanked text.

```
NVIM 0.0.0-alpha+201507232235 (compiled Jul 24 2015 21:37:03)
Commit: 7a6bf3f418c5ad94ac2ac71f21275a87d08e87b9

ArchLinux
xsel 1.2.0
```

**Comment by bfredl** [comment]
`clipboard=unnamed,unnamedplus' is wierd, it will set both clipboards but you can't control which will be pasted from. But we should at least support the same behaviour as vim

**Comment by bfredl** [comment]
from the vim help
> When "unnamed" is also included to th eoption, yank operations (but not delete, change or put) will additionally copy the text into register '*'.

seems not to be true in vim; yanks and deletes work the same, as one presumably would expect. We should update the documentation when fixing this.

**Comment by zenbro** [comment]
About `clipboard=unnamed,unnamedplus` behavior in vim:
- All things that copied inside vim will get into both `*` and `+` registers.
- All things that copied to _PRIMARY_ or _CLIPBOARD_ from outside vim will get into the corresponding registers in vim - `*` or `+`.
- When using `p` text will be pasted from `+` register

**Comment by trusktr** [comment]
In OS X, `"*yy` copies to the desktop's clipboard, but this isn't happening in Linux no matter which of the four I try:

```
set clipboard=
set clipboard=unnamed
set clipboard=unnamedplus
set clipboard=unnamed,unnamedplus
```

**Comment by bfredl** [comment]
It shouldn't, "+y ( or cb=unnamedplus and _plain_ yy) are for this purpose.
Den 10 aug 2015 09:56 skrev "Joseph Orbegoso Pea" <notifications@github.com
>:
>
> In OS X, "*yy copies to the desktop's clipboard, but this isn't happening
in Linux no matter which of the four I try:

**Comment by trusktr** [comment]
@bfredl In OS X, the behavior I'm describing is the default out-of-the-box behavior. I'd love to have it in Linux.

**Comment by bfredl** [comment]
But why, "+ does what you want on both osx on linux right?
Den 10 aug 2015 10:06 skrev "Joseph Orbegoso Pea" <notifications@github.com

**Comment by trusktr** [comment]
@bfredl `"*` is much easier to type for me.

**Comment by trusktr** [comment]
And since `"*` works in OS X, why shouldn't it in Linux?

**Comment by fdinoff** [comment]
@trusktr On mac osx `"*` and `"+` go to the same clipboard. On Linux this isn't true. (I might have this backwards and I don't know what the official names are). On linux `"+` go to the standard clipboard which you use with Ctrl-C and Ctrl-V and `"*` goes to the secondary clipboard where normally mouse selection puts stuff into it and middle click pastes.

**Comment by trusktr** [comment]
@fdinoff Indeed, that is the case. I never use middle click. How can we make `'*` also go to the same clipboard as `"+` in Linux?

**Comment by fdinoff** [comment]
@trusktr I can't test this right now but my first guess would be just to map them.

    map "+ "*

**Comment by trusktr** [comment]
@fdinoff Thanks, that works. :) I still see `"+` at the bottom right corner of the screen, but I can live with that.

**Comment by bfredl** [comment]
I do `map <Leader>y "+y` and so on, typing `" [+*][yp]` every time a clipboard operation seems just horrible (at least on many a non-US keyboard)...

**Comment by trusktr** [comment]
@bfredl That's a good idea. On the American keyboard I can do `"*`  by holding left shift with my left pinky, then `"` with my right pinky and `*` with my right pointer finger, so it's not bad compared to `"+` (in which case we need hand acrobatics). :laughing:
