### ISSUE TITLE
How to hide `No clipboard tool available` warning?

### ISSUE THREAD

**Issue by xu-cheng** [neovim/neovim#3097]
I installed neovim on a Linux server. Every time I run neovim, it will show below warning message:

```
clipboard: No clipboard tool available. See :help nvim-clipboard
Press ENTER or type command to continue
```

The thing is I don't need clipboard support on a server connected by ssh. So how do I disable such warning message? Thanks.

**Comment by bfredl** [comment]
You happen to have `set clipboard=unnamed` it your `nvimrc`? Try disabling it in that case. (without it, nvim shouldn't try to load clipboard on startup)

**Comment by xu-cheng** [comment]
Thanks it works. However I found an unexpected behavior.

If my configure file is like this, it will still show the warning message.
```vim
if has('clipboard') && (executable('pbcopy') || executable('xclip') || executable('xsel'))
  set clipboard=unnamed
endif
```

However, if I swap the oder like below, the message will be gone.
```vim
if (executable('pbcopy') || executable('xclip') || executable('xsel')) && has('clipboard')
  set clipboard=unnamed
endif
```

**Comment by bfredl** [comment]
yes `has('clipboard')` must load the provider, which shows the message and is a bit unfornate ( `&&` is short-circuiting so in the 2nd case it is avoided). Perhaps the provider should, in the unavailability branch, instead define `provider#clipboard#call` to show the error message on first yank/paste.

**Comment by xu-cheng** [comment]
I know the short-citcuiting part. It feels strange to me that a condition check would make such change. To be honest, if I didn't accidentally try to test whether `has` need to be blamed, I will never figure this out. 

Anyway close this issue as I have fixed the problem.

**Comment by justinmk** [comment]
> Perhaps the provider should, in the unavailability branch, instead define provider#clipboard#call to show the error message on first yank/paste.

@bfredl Seems like a good idea.

**Comment by bfredl** [comment]
Thinking a bit more of it, that wouldn't work: implementing `provider#clipboard#Call` will set `has("clipboard")` to true. Rather we  want `provider#clipboard#Error` in analogy with the python provider.

**Comment by lkraav** [comment]
Installing `yankring-19.0` cause `nvim-0.1.1` start looking for clipboard always, regardless of the fact I'm in a terminal-only `ssh` environment.

`let g:yankring_clipboard_monitor = (has("nvim") ? 0 : 1)` has silenced the startup warnings, but it does look like there's something off with the algorithm. Thoughts?

**Comment by justinmk** [comment]
@lkraav "always" means "once at startup", or "constantly while I am editing"?

**Comment by lkraav** [comment]
First at startup, then every yank, paste etc operation as well.

**Comment by fishy** [comment]
Is there a way to achieve this:

- This is an SSH server (Linux), so most of the time I don't really need clipboard
- But rarely I will operate on it physically with X, in which case I do need clipboard

Currently the problem is, if I have `xsel` in my `PATH`, with the config of:

```vim
if (executable('pbcopy') || executable('xclip') || executable('xsel')) && has('clipboard')
  set clipboard=unnamed
endif
```

When I'm connecting from SSH, `executable('xsel')` returns `true` because I do have it, but when nvim really tries to use it it will fail because of no DISPLAY, so I'm still seeing the warning.

I guess what I really want is to test if xsel is really usable instead of just `executable('xsel')`

**Comment by ZyX-I** [comment]
@fishy You already have an answer. You say “fail because of no DISPLAY”, why you just do not check that it is present *and* $DISPLAY is present? `:h exists()`.

**Comment by fishy** [comment]
@ZyX-I that works. Thanks!

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7203 should have improved this as much as it can be.
