### ISSUE TITLE
InspectTree: exiting source buffer raises E855

### ISSUE THREAD

**Issue by xudyang1** [neovim/neovim#30986]
### Problem

Exiting source buffer where `:InspectTree` is called raises `E855: Autocommands caused command to abort`

### Steps to reproduce

1. nvim --clean repro.lua
2. `:InspectTree`
3. `:wincmd p | quit`
4. `E855: Autocommands caused command to abort` is reported

Or:

- `nvim --clean  -c 'InspectTree' -c 'wincmd p | quit' repro.lua`

### Expected behavior

No error raised

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu 22.04

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

app image

**Comment by zeertzjq** [comment]
There seems to be another problem:
- Normally, running `:enew` in the only window showing the source buffer will close the `:InspectTree` window.
- However, if `bufhidden=unload` or `bufhidden=delete` or `bufhidden=wipe` is set in the source buffer, running `:enew` in the only window showing it doesn't close the `:InsepctTree` window.
