### ISSUE TITLE
Using CTRL-C to exit visual block insert only inserts text on current line

### ISSUE THREAD

**Issue by dwgrth** [neovim/neovim#30987]
### Problem

Using CTRL-C (instead of ESC) to exit visual block insert mode only inserts the text that was just entered, instead of inserting it in front of the entire selection. Also interestingly, using '.' to repeat the action does the insert correctly.

I tried to create a test for this behaviour, but ran into some issues. Whenever I used `<C-c>` in a `feed()` call, the test just failed with empty output.

When using `nvim_replace_termcodes` and `nvim_feedkeys` to send a `<C-c>`, the test **passes**, which is very strange. The only way I found to reproduce what actually happens is just by not exiting visual block at all before the test ends.

Commit with attempted test:
https://github.com/dwgrth/neovim/commit/794a8f161b8810182ce4536d6936172f222f8e00

### Steps to reproduce

nvim --clean
`iabc<CR>abc<CR>abc<C-c>gg^<C-v>GIxyz<C-c>`

--- Actual output:
xyzabc
abc
abc

### Expected behavior

--- Expected output:
xyzabc
xyzabc
xyzabc

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

yes, 9.1.0016-1ubuntu7.3

### Operating system/version

macOS 14.7

### Terminal name/version

tmux 3.5a

### $TERM environment variable

tmux-256color

### Installation

homebrew

**Comment by zeertzjq** [comment]
This is working as intended. The help only says:
```
Visual-block Insert						*v_b_I*
With a blockwise selection, I{string}<ESC> will insert {string} at the start
of block on every line of the block, provided that the line extends into the
block.  Thus lines that are short will remain unmodified.  TABs are split to
retain visual columns.  Works only for adding text to a line, not for
deletions.  See |v_b_I_example|.
```
It doesn't say `I{string}<C-C>` will behave the same.

**Comment by dwgrth** [comment]
I suppose that's true.  However, it feels like <ESC> and <C-c> are treated equivalently in many cases.

Also, why does '.' do what <ESC> would have done?

See below:

```
nvim --clean
iabc<CR>abc<CR>abc<C-c>gg^<C-v>GIxyz<C-c>.

--- Actual output:
xyxyzzabc
abxyzc
abxyzc
```

**Comment by zeertzjq** [comment]
Usually, Ctrl-C is supposed to cancel pending operations. For example:
```
							*CTRL-C*
CTRL-C			Interrupt current (search) command.
			In Normal mode, any pending command is aborted.
```
```
						*i_CTRL-C*
CTRL-C		Quit insert mode, go back to Normal mode.  Do not check for
		abbreviations.  Does not trigger the |InsertLeave| autocommand
		event.
```

**Comment by dwgrth** [comment]
Found out today that cancelling visual block append with `<C-c>` works the exact same way, which is more proof that this is intended behaviour.
