### ISSUE TITLE
LSP: rust_analyzer: -32802: server cancelled the request

### ISSUE THREAD

**Issue by vikulikov** [neovim/neovim#30985]
### Problem

editor is being interrupted with message `rust_analyzer: -32802: server cancelled the request` while typing on every keystroke after the latest updates of rust-analyzer

### Steps to reproduce using "nvim -u minimal_init.lua"

Just start typing in `main.rs` inside `fn main() {|}` of `cargo new --bin test_project`

```lua
local pattern = 'rust'
local cmd = { '/opt/homebrew/bin/rust-analyzer' }
-- Add files/folders here that indicate the root of a project
local root_markers = { 'Cargo.toml' }
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
    pattern = pattern,
    callback = function(args)
        local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
        local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
        vim.lsp.start({
            name = 'rust-analyzer',
            cmd = cmd,
            root_dir = root_dir,
            settings = settings
        })
    end
})
```

### Expected behavior

There is no this message with interrupt

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Language server name/version

rust-analyzer 0.0.0 (3b3a87fe9 2024-10-27)

### Operating system/version

macos 15.1

**Comment by MariaSolOs** [comment]
Seems to be caused by https://github.com/rust-lang/rust-analyzer/pull/18408/commits/8eef1c52757f1ca444792b22433e696364a2b86d

**Comment by MariaSolOs** [comment]
Hmm I can't reproduce this using rust-analyzer 1.84.0-nightly (1e4f10ba 2024-10-29) and master Neovim. Are you sure that no further settings are needed?

https://github.com/user-attachments/assets/f0df20f4-76b3-4387-bfe8-352dec59acc7

**Comment by glepnir** [comment]
rust-analyzer 0.0.0 (468b5cd43 2024-10-29)


![Image](https://github.com/user-attachments/assets/879058b5-9c87-4e58-950e-0b2ceb3e1a00)

**Comment by vikulikov** [comment]
https://github.com/user-attachments/assets/4d6a6048-25ab-473f-82d5-05d24ecca966

Sorry, thought gif from glepnir is enough. I guess something fast should happen to trigger cancellation of the previous request to the server. fast typing or typing before server has indexed the project

**Comment by Jesse-Bakker** [comment]
Workaround to ignore the `ServerCancelled` error:
```lua

for _, method in ipairs({ 'textDocument/diagnostic', 'workspace/diagnostic' }) do
    local default_diagnostic_handler = vim.lsp.handlers[method]
    vim.lsp.handlers[method] = function(err, result, context, config)
        if err ~= nil and err.code == -32802 then
            return
        end
        return default_diagnostic_handler(err, result, context, config)
    end
end
```

**Comment by samvv** [comment]
I can confirm that this issue affects me too. Using Arch and the problem was introduced after doing `pacman -Suy`.

The workaround of @Jesse-Bakker worked for me, thanks!

**Comment by nagyben** [comment]
> Workaround to ignore the `ServerCancelled` error:
> 
> for _, method in ipairs({ 'textDocument/diagnostic', 'workspace/diagnostic' }) do
>     local default_diagnostic_handler = vim.lsp.handlers[method]
>     vim.lsp.handlers[method] = function(err, result, context, config)
>         if err ~= nil and err.code == -32802 then
>             return
>         end
>         return default_diagnostic_handler(err, result, context, config)
>     end
> end

This might be a stupid question but where's the best place to put this when using lazy.nvim?

**Comment by samvv** [comment]
> > Workaround to ignore the `ServerCancelled` error:
> > 
> > ```lua
> > for _, method in ipairs({ 'textDocument/diagnostic', 'workspace/diagnostic' }) do
> >     local default_diagnostic_handler = vim.lsp.handlers[method]
> >     vim.lsp.handlers[method] = function(err, result, context, config)
> >         if err ~= nil and err.code == -32802 then
> >             return
> >         end
> >         return default_diagnostic_handler(err, result, context, config)
> >     end
> > end
> > ```
> 
> This might be a stupid question but where's the best place to put this when using lazy.nvim?

I just added it at the end of my `config` function of the plugin spec for this plugin.

**Comment by youshitsune** [comment]
For now I have downgraded version of rust-analyzer to 2024-10-14

**Comment by aramrw** [comment]
+ 1

**Comment by fleetvip** [comment]
Downgrade version
:MasonInstall rust-analyzer@2024-10-14

**Comment by dr-kernel** [comment]
How 

> Workaround to ignore the `ServerCancelled` error:
> 
> for _, method in ipairs({ 'textDocument/diagnostic', 'workspace/diagnostic' }) do
>     local default_diagnostic_handler = vim.lsp.handlers[method]
>     vim.lsp.handlers[method] = function(err, result, context, config)
>         if err ~= nil and err.code == -32802 then
>             return
>         end
>         return default_diagnostic_handler(err, result, context, config)
>     end
> end

Where would one put this workaround?

**Comment by praveenperera** [comment]
> Where would one put this workaround?

I put it in my ftplugin/rust: https://github.com/praveenperera/dotfiles/commit/3cd2a6d3c1cc05f3c8f6245e3d918e350859a33a

**Comment by getcisher** [comment]
seem the lua script that put in init.lua not work on astronvim.
Downgrade is seem work for me.

**Comment by praveenperera** [comment]
@getcisher im using astronvim and putting it in after works, see comment above.

**Comment by vext01** [comment]
I have the same on today's Rust and today's Neovim.

**Comment by chardoncs** [comment]
Same here, but it will be gone seconds later.

![Image](https://github.com/user-attachments/assets/5b3dfc98-61e1-4a46-99a9-be826c18fd8f)

I use `nvim-lspconfig` in my config instead and it's simpler:

```lua
local lspconfig = require("lspconfig")
local capabilities = require('cmp_nvim_lsp').default_capabilities()

local function default_config(t)
    for _, name in ipairs(t) do
      lspconfig[name].setup {
        capabilities = capabilities,
      }
    end
  end

default_config({
   -- SNIP --
    "rust_analyzer",
   -- SNIP --
})
```

**Comment by JonoPrest** [comment]
Same is happening to me, downgrading to 2024-10-14 seems to remove the problem 👍🏼

**Comment by athar-qadri** [comment]
I am facing this issue right now with Neovim setup (Lazy). 

any solution available?

**Comment by WhyNotHugo** [comment]
I see that the fix handles the server cancellation and re-issues the request for diagnostics.

Why is the server cancelling the request in the first place?

**Comment by orangecms** [comment]
> I see that the fix handles the server cancellation and re-issues the request for diagnostics.
> 
> Why is the server cancelling the request in the first place?

Referencing https://www.reddit.com/r/rust/comments/1geyfld/rustanalyzer_server_cancelled_the_request_in/ which brought me here; that is a new feature in rust-analyzer that NeoVim hadn't been prepared for, unfortunately. I assume it is so that when many requests get to the server, e.g. when typing quickly, will be debounced or something.

**Comment by zerogtiger** [comment]
Sorry to disturb, ran into this issue again. 

Nvim version info
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678
```
with rust analyzer:       installed version 2025-03-24
any workarounds?

**Comment by liskin** [comment]
> NVIM v0.10.2

Yeah, update to at least v0.10.3
