### ISSUE TITLE
parser(markdown): incremental selection at ending space raises E5108

### ISSUE THREAD

**Issue by xudyang1** [neovim/neovim#31015]
### Problem

Failed to init_selection from incremental_selection. When cursor is at the ending space, calling init_selection raises E5108.

### Steps to reproduce

1. minimal repro.lua:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "nvim-treesitter/nvim-treesitter",
      build = ":TSUpdate",
      event = "VeryLazy",
      cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
      keys = {
        { "<C-j>", desc = "Selection: Increment" },
        { "<C-h>", desc = "Selection: Scope Increment", mode = "x" },
        { "<C-k>", desc = "Selection: Decrement", mode = "x" },
      },
      opts = {
        auto_install = true,
        sync_install = false,
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = false,
        },
        ensure_installed = {
          -- the five parsers should always be intalled
          "c",
          "lua",
          "vim",
          "vimdoc",
          "query",
        },
        incremental_selection = {
          enable = true,
          keymaps = {
            init_selection = "<C-j>",
            node_incremental = "<C-n>",
            scope_incremental = "<C-h>",
            node_decremental = "<C-k>",
          },
        },
      },
      config = function(_, opts)
        if type(opts.ensure_installed) == "table" then
          -- @type table<string, boolean>
          local added = {}
          opts.ensure_installed = vim.tbl_filter(function(lang)
            if added[lang] then
              return false
            end
            added[lang] = true
            return true
          end, opts.ensure_installed)
        end
        require("nvim-treesitter.configs").setup(opts)
      end,
    },
  },
})
```
2. `nvim -u repro.lua a.md`
3. Type `a`, then `hello` with an extra space at the end
4. `<Esc>` or `<C-c>` to exit insert mode, and type `<C-j>` (init selection of incremental_selection)'
5. Error occurs:
```text
E5108: Error executing lua: ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:168: attempt to index local 'node_or_range' (a n
il value)
stack traceback:
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:168: in function 'get_node_range'
        ...im/lazy/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:279: in function 'update_selection'
        ...treesitter/lua/nvim-treesitter/incremental_selection.lua:19: in function <...treesitter/lua/nvim-treesitter/incremental_selec
tion.lua:15>
```

- `:InspectTree` at the ending space points to `inline  ; [0,0] - [0,5]`, this should be `inline ; [0,0] - [0,6]` if the ending space is included into inline.
- For two or more spaces at the end, `:InspectTree` returns `paragraph ; [0,0] - [1,0]`, which is correct

### Expected behavior

Incremental selection should work without error.

### Nvim version (nvim -v)

nightly v0.11.0-dev

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

ubuntu 22.04

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by clason** [comment]
Wrong repo.

**Comment by clason** [comment]
Sorry, I see you were pointed here. I don't think that was good advice. It's not quite clear where the error is (or if indeed there's an error):

* the markdown parser could be capturing the space
* the tree-sitter library could be giving a wrong range in edge cases (this has happened before)
* the incremental selection plugin has a bug 
* the ts-utils module has a bug
* the node handling functions in Nvim have a bug.

Only the last can be handled here, and some work needs to be put in to narrow the options down.

So first step is to remove nvim-treesitter from the equation. Can your produce the error with only built-in functions? (The markdown parser is bundled.) Also check what the tree-sitter CLI (`tree-sitter parse`) produces in this case.

**Comment by xudyang1** [comment]
> Sorry, I see you were pointed here. I don't think that was good advice. It's not quite clear where the error is (or if indeed there's an error):
> 
> * the markdown parser could be capturing the space
> * the tree-sitter library could be giving a wrong range in edge cases (this has happened before)
> * the incremental selection plugin has a bug
> * the ts-utils module has a bug
> * the node handling functions in Nvim have a bug.
> 
> Only the last can be handled here, and some work needs to be put in to narrow the options down.
> 
> So first step is to remove nvim-treesitter from the equation. Can your produce the error with only built-in functions? (The markdown parser is bundled.) Also check what the tree-sitter CLI (`tree-sitter parse`) produces in this case.

`tree-sitter parse` produces:

```text
(document [0, 0] - [1, 0]
  (section [0, 0] - [1, 0]
    (paragraph [0, 0] - [1, 0]
      (inline [0, 0] - [0, 5]))))
```

So, the markdown parser does not parse it correctly as the space is not included in inline. I will reopen the issue at tree-sitter-markdown
