### ISSUE TITLE
Control+Space in :terminal sends <7fffa701>

### ISSUE THREAD

**Issue by jordansissel** [neovim/neovim#3101]
How to reproduce:

1) Start a terminal `:terminal`
2) press control+space together.

In Bash, this will output a bunch of "unknown unicode" characters. In Zsh, this will show <7fffa701>

Googling for 7fffa701 shows one hit (at this time) that points to the neovim gitter; this may just be a weird bug possibly in libvterm (this is just speculation)?

Here's some screenshots of what I mean:

1) Terminator running zsh and writing a ctrl+space

![normal-zsh](https://cloud.githubusercontent.com/assets/131818/8892717/c466cd92-331e-11e5-9fd8-8ae8966f24e0.png)

2) Terminator running nvim and writing ctrl+space in insert mode

![normal-nvim](https://cloud.githubusercontent.com/assets/131818/8892718/d41c5a7c-331e-11e5-8176-94e681206268.png)

3) Terminator running nvim and `:terminal` showing both Bash and Zsh behaviors within neovim's terminal:

![terminal-within-nvim](https://cloud.githubusercontent.com/assets/131818/8892721/e35ececa-331e-11e5-9471-8bb808dd001a.png)

**Comment by jordansissel** [comment]
![stty-diff](https://cloud.githubusercontent.com/assets/131818/8892736/85bee0ba-331f-11e5-90b4-dc85d188b550.png)

Here's a little vimdiff showing `stty -a` differences between neovim :terminal (left) and normal terminal (right)

**Comment by justinmk** [comment]
What's the use-case here? A workaround is to map `<C-@>` (which is how ctrl-space i represented by the host terminal):

    :tnoremap <C-@>

**Comment by blueyed** [comment]
@justinmk 
The use case is to map `<c-space>` (obviously :), e.g.:

> tnoremap <C-@> <C-\><C-n>:tab sp<cr>:startinsert<cr>

(but with `space` instead of `@` - the workaround works).

The bug/issue seems to be that `<c-space>` should be handled like `<c-@>` then?
Using `<c-space>` works with `nnoremap`:

> nnoremap <C-Space> :tab sp \| set nodiff<cr>

**Comment by wleese** [comment]
Not sure if this is related, but a <c-Right> and <c-Left> in the terminal results in:  
<7fffab03><7fffaa03> 

(running neovim compiled from master today, with nvim -u NONE -N)
