### ISSUE TITLE
55 new clang warnings because of dependencies

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#3102]
It seems dependencies compilation is now somehow included in clang analysis, which produces 55 new warnings.
IMO, clang analysis should be restricted to our own code.
Does anybody know how this happened? What changed for this to be like this now?

**Comment by fwalch** [comment]
Sorry about that, should be fixed with neovim/bot-ci#64.

**Comment by elmart** [comment]
Ok, thx. :+1:
