### ISSUE TITLE
LSP: vim.api.nvim_buf_get_name marked as deprecated

### ISSUE THREAD

**Issue by Fuuruko** [neovim/neovim#31033]
### Problem

Probably shouldn't be deprecated
https://github.com/neovim/neovim/blob/b25ae5d328fd58bae5052d1ae19bd1d17a991ea8/runtime/lua/vim/_meta/api.lua#L495

### Steps to reproduce using "nvim -u minimal_init.lua"

-

### Expected behavior

 -

### Nvim version (nvim -v)

0.10.2

### Language server name/version

 -

### Operating system/version

 -

**Comment by zeertzjq** [comment]
It's for `nvim_buf_get_number`, which is deprecated.
