### ISSUE TITLE
`:set commentstring` not working

### ISSUE THREAD

**Issue by yochem** [neovim/neovim#31030]
### Problem

`:set commentstring="-- %s"` doesn't actually set the commentstring. `:lua vim.api.nvim_set_option_value('commentstring', '-- %s', {})` does work.

### Steps to reproduce

1. nvim --clean -u NONE
2. `:set commentstring="-- %s"
3. `:echo &commentstring`
4. Nothing prints

### Expected behavior

Step 4 prints `-- %s`, but currently doesn't print anything. The lua variant works.

### Nvim version (nvim -v)

tested on NVIM v0.10.1 and v0.11.0-dev-1069+g05421c07a2-dirty

### Vim (not Nvim) behaves the same?

Not tried yet.

### Operating system/version

macOS 15.0.1 (24A348)

### Terminal name/version

iTerm 3.5.5

### $TERM environment variable

tmux-256color

### Installation

0.10: homebrew, 0.11: build from source

**Comment by zeertzjq** [comment]
`:h option-backslash`

**Comment by yochem** [comment]
Shit, I'm so sorry 🤦‍♂
