### ISSUE TITLE
`:set term?` fails (but `:echo &term` works)

### ISSUE THREAD

**Issue by errael** [neovim/neovim#31048]
### Problem

Title says it all. In `lua` `vim.o.term` fails; `vim.api.nvim_eval('&term')` is a workaround.

I don't know if this issue is widespread and/or what class of options might be affected.

### Steps to reproduce

Do `:set term?` and observe the error.
```
E518: Unknown option: term?                                                                
```

### Expected behavior

No error, report the same value as `:echo &term`

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/3688a333544251c887d78e6501eec55f0fb685f8

### Vim (not Nvim) behaves the same?

no

### Operating system/version

ubuntu

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by clason** [comment]
`term` is not an option; `set term` fails the same way.

**Comment by errael** [comment]
> `term` is not an option

`:echo &term` works. So does `:he 'term'`. It works in `vim`. And `:he expr-option` says
```
option						*expr-option* *E112* *E113*
&option			option value, local value if possible
```

This issue isn't about `nvim` internals, it's user facing.

**Comment by clason** [comment]
That still doesn't make `term` an option. (And Vim's behavior -- which has a very different terminal implementation -- is irrelevant here.)

**Comment by errael** [comment]
> That still doesn't make `term` an option. (And Vim's behavior -- which has a very different terminal implementation -- is irrelevant here.)

I always thought that something wrapped in `'` was an option. But more to the point, this isn't about "terminal implementation" it's about a consistent UI.

> 
> > This issue isn't about nvim internals, it's user facing.
> 
> The only user-facing thing here (from `:he 'term'`, in fact), is that you can use `&term` to access the current terminal type according to Nvim.

Your ignoring `:he expr-option` which clearly states that something of the form `&name` is an option. 

Closing this as won't fix is fine. But I don't see the use of pretending it's not a bug; maybe it's a documentation bug in `expr-option`.

**Comment by clason** [comment]
> Your ignoring :he expr-option which clearly states that something of the form &name is an option.

No, that is _your_ incorrect reading. It just says that you can access option values this way, not that what you can access this way must be an option.

**Comment by dundargoc** [comment]
> So does :he 'term'.

It directs to `vim_diff.txt` though and mentions `:echo &term` is only for debugging. I think it could be made more explicit in saying "this was removed" instead of faffing around the issue.

**Comment by errael** [comment]
>  saying "`'term'` was removed"

Also removing it would be good ;)

**Comment by dundargoc** [comment]
Another QOL is to have a separate/special error message for removed options to make the transition easier. Something like "x has been removed, read more with `:help x`".

**Comment by dundargoc** [comment]
> Also removing it would be good ;)

Alright, I guess maybe mention "this is an internal option not meant to be used by users" or something. Basically something that tells users to BTFO since it's clearly not meant to be used by them.

As for why it hasn't been removed, I couldn't tell you. I'm going to assume there was a good reason for it but I dunno. I will admit the current special handling is weird, so if anyone is motivated they could investigate why `'term'` wasn't removed.

**Comment by errael** [comment]
In the OP "I don't know if this issue is widespread and/or what class of options might be affected.". If `'term'` is the only one, then no real problem.

**Comment by justinmk** [comment]
This is intentional, and documented.
