### ISSUE TITLE
an API to get client capabilities

### ISSUE THREAD

**Issue by errael** [neovim/neovim#31050]
### Problem

There's no clean way (that I can find) to determine the gui front end. Looking for a way to determine the client, like in a `UIEnter` handler.  Would use the info now so the client name can be put into the title bar. This is especially useful when experimenting with different `gui`s.

I'm guessing some info might also be for other uses. For example, client capabilities. Neither `neovide` nor `goneovim` support `&mousemoveevent`. It would be useful to know this so, for example, a popup compatibility layer could generate an error if a popup feature is requested that requires `&mousemoveevent.

@justinmk #27949 may be loosely related. In particular for a `gui` client, maybe something like `nvim_get_client_info()`.

### Expected behavior

Something like following hack works, but also needs a deferred check after about a second because it takes a while for `Goneovim` to warm up.

```lua
vim.api.nvim_create_autocmd("UIEnter", {
    callback = function()
        if vim.fn.exists(":NeovideFocus") > 0 then
            set_app("Neovide")
        elseif vim.fn.exists(":GonvimFilerOpen") > 0 then
            set_app("Goneovim")
        else
            set_app("Nvim")
        end
        return true
    end
})
```

**Comment by clason** [comment]
`:h nvim_get_chan_info()`

**Comment by errael** [comment]
> `:h nvim_get_chan_info()`

Cool, thanks. `vim.api.nvim_get_chan_info(vim.v.event.chan)` does the trick.

I'll adjust the title to specifically call out client capabilities.

**Comment by clason** [comment]
What do you mean? The channel info returns a `client` table, which contains the name. Do follow the links in the help entry I linked.

**Comment by errael** [comment]
> What do you mean? The channel info returns a `client` table, which contains the name. Do follow the links in the help entry I linked.

I've looked at the docs. Are you talking about the `api_compatible` field?

As mentioned in the OP, I'd like to determine if `&mousemoveevent` is supported by the `gui`. I don't see that info. I've only just started looking at `neovim`, from what I've seen not all clients support everything. Looking forward, which is why I mentioned #27949, this type of information is likely to be generally useful.

**Comment by errael** [comment]
There's `api_level`, where's that defined?

**Comment by errael** [comment]
Ah, `ui_options`. Maybe the enhancement I'm looking for is additional keys in this.

**Comment by clason** [comment]
Then you should open a new issue about that, giving (much) more details about how you expect GUIs to use your proposed protocol extension (which should be specific and implementable).
