### ISSUE TITLE
difficult to get name of gui client during startup

### ISSUE THREAD

**Issue by errael** [neovim/neovim#31057]
### Problem

With `nvim-tui`, after `UIEnter` event, `vim.api.nvim_get_chan_info(chan)` data, which can contain the name, is intermittent.

Guess it's a timing problem, `nvim_set_client_info` since docs say
```
The client ... call this after connecting ... Can be called more than once
```

There's a further complication in general; this information is not always supported. For reference, `neovide` has `client`, but `client.attributes` is nil. `goneovim` does not have `client`, so the `name` is not available. #31052 discusses getting info about what a client supports, might be a catch-22.

### Steps to reproduce

With this somewhere in initialization
```lua
vim.api.nvim_create_autocmd("UIEnter", {
    callback = function(ev)
        local chan = vim.v.event.chan
        local function p(chan) vim.print(string.format("'chan info': %s",
            vim.inspect(vim.api.nvim_get_chan_info(chan), {newline=""}))) end
        p(chan)
        vim.defer_fn(function() p(chan) end, 1000)
        return true
    end
})
```
Then run `nvim`.

Here's an example, the first chan info is from the event handler, the second is from a second later.
```
'chan info': {  client = vim.empty_dict(),  id = 1,  mode = "rpc",  stream = "stdio"}
'chan info': {  client = {    attributes = {      license = "Apache 2",      pid = 1247640,      web
site = "https://neovim.io"    },    methods = vim.empty_dict(),    name = "nvim-tui",    type = "ui"
,    version = {      api_compatible = 0,      api_level = 13,      api_prerelease = true,      majo
r = 0,      minor = 11,      patch = 0,      prerelease = true    }  },  id = 1,  mode = "rpc",  str
eam = "stdio"}                                                                                      
```
Sometimes the first line has all the info.

### Expected behavior

Some way to find out that there's new information about the client. At least something better than having to poll.
Maybe an aucmd-event that signals "new client info available", with a `v:event` key that says where to look for it; in case `nvim_get_chan_info()` is not the only source?

### Nvim version (nvim -v)

https://github.com/neovim/neovim/commit/3688a333544251c887d78e6501eec55f0fb685f8

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

ubuntu

### Terminal name/version

gnome-terminal

### $TERM environment variable

xterm-256color

### Installation

make install

**Comment by bfredl** [comment]
use `ChanInfo` autocmd

**Comment by errael** [comment]
Oops, I looked for something like that. Sorry for the noise.

Thanks.
