### ISSUE TITLE
LSP: symlink clangd problem

### ISSUE THREAD

**Issue by azieba** [neovim/neovim#31064]
### Problem

When you navigate to your project sandbox via symlink and produce the compilation database file for clangd (compilation_commands.json) with this symlink path, the language server will work only on opened files and will not be able to produce symbol index in background.
The issue is described also here: https://www.reddit.com/r/neovim/comments/17t773k/nvim_lspconfig_clangd_wasnt_indexing_all_my_files/

### Steps to reproduce

1. Enable clangd: I have ''neovim/nvim-lspconfig' installed and clang enabled via require('lspconfig').clangd.setup{}
2. Create a symlink to your project. I have /home/user/ssd -> /home_ssd/user, so my symlink path is /home/user/ssd/sources/pioneer and the real path is /home_ssd/user/sources/pioneer.
3. cd to your project using the symlink so the pwd will print the symlink dir
4. Build the compilation database. For https://github.com/pioneerspacesim/pioneer I just need to call ./bootstrap.
5. ln project root directory: ln -s build/compile_commands.json (this is not the problematic symlink)
6. Check contents of compile_commands.json - all files should be with full symlink path like: /home/user/ssd/sources/pioneer/src/lua/core/Import.cpp
7. Run nvim in root of the project.
8. Open some cpp file and try to find references of some symbol, they will be found only in opened file(s).
   .cache/clangd/index will not be creaetd

If the compilation database is created with real paths everything works fine. It can be achieved by navigating to the sandbox via real path:
cd /home_ssd/user/sources/pioneer
and starting:
./bootstrap

### Expected behavior

I should work like in vim with ALE plugin and clangd. Even with the compilation database with symlink paths it can initiate clangd to work properly and find references in the whole project no matter if you navigate to the sandbox via symlink or real path.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1090+g99acc9de55

### Language server name/version

Debian clangd version 16.0.6 (27+b1)

### Operating system/version

Debian testing

**Comment by clason** [comment]
> NVIM v0.9.5

1. please use the latest Nvim version (0.10.2) and ideally test with a nightly appimage
2. make sure nvim (and the clangd started from within nvim) can see the "real" file behind the symlink.

**Comment by azieba** [comment]
> > NVIM v0.9.5
> 
> 1. please use the latest Nvim version (0.10.2) and ideally test with a nightly appimage
It is reproducible in nightly build. I have updated the Nvim version in the bug report.

> 3. make sure nvim (and the clangd started from within nvim) can see the "real" file behind the symlink.> 
I'm not sure what you mean. I can open a file in nvim using the symlink path. It is not a dangling symlink.

> Also, please explain what your "sandbox" actually is.
You know the place where you play with sand and toys, like your local clone of a git repository.

**Comment by clason** [comment]
> You know the place where you play with sand and toys, like your local clone of a git repository.

That's not what people usually mean by ["sandbox" in this context](https://en.wikipedia.org/wiki/Sandbox_(computer_security)). No reason to get snarky.

**Comment by azieba** [comment]
> > You know the place where you play with sand and toys, like your local clone of a git repository.
> 
> That's not what people usually mean by ["sandbox" in this context](https://en.wikipedia.org/wiki/Sandbox_(computer_security)). No reason to get snarky.

https://en.wikipedia.org/wiki/Sandbox_(software_development)

I am sorry, I felt your original comment was a bit condescending.

**Comment by clason** [comment]
Not intended as such; it was a genuine request for clarification.

**Comment by andrewbraxton** [comment]
I've experienced this as well, but I'm fairly certain this is an issue with clangd and not with Neovim.

Check these issues out on clangd's GitHub:

* https://github.com/clangd/clangd/issues/197
* https://github.com/clangd/clangd/issues/629

**Comment by azieba** [comment]
@lewis6991 Why did you close this issue?
1. The issues in clang mentioned by @andrewbraxton talk about adding new option to clangd. When the option is added this will not solve the issue in nvim automatically, it would need to use this new option.
2. As I mentioned the retrovim with ALE plugin is able to behave correctly with the same version of clangd so I do not think it is a clang dproblem or the problem can be solved without changes in clangd.

It also seems to me that the clang issues are about different use case and will probably not solve this problem.

Please reopen.

**Comment by lewis6991** [comment]
Neovim doesn't specify any server options, not does it, or will ever, implement any workarounds for specific servers. Neovim strictly follows the LSP.

This issue will remain closed.

**Comment by azieba** [comment]
If you have a symlink to c or c++ project neovim lsp will fail you because it works according to specification. Is that it?

**Comment by clason** [comment]
I don't see what's Neovim specific about this. This is purely between `clangd` and your `compile_command.json`.

**Comment by azieba** [comment]
Just that it works in Vim and it does not in Neovim. Assuming that Neovim is fine and Vim with ALE is just working because some dirty hacks is premature at the moment imo.

**Comment by lewis6991** [comment]
Could also be due to arbitrary implementation differences. Just because they behave differently doesn't mean either is wrong.

**Comment by andrewbraxton** [comment]
It seems like there's a collection of slightly different issues with symlinks that clangd has. The issue I frequently run into is go-to-definition bringing me to the declaration in the header file instead of the actual definition in the source file when the source file is inside a symlinked directory as represented in compile_commands.json.

Looking at the LSP's logs, we see clangd is indeed returning the header file as the location of the definition (until I manually open the source file, then clangd will start returning the source file):

```
[ERROR][2024-12-29 15:06:22] ...p/_transport.lua:36     "rpc"   "clangd"        "stderr"        "I[15:06:22.150] <-- textDocument/definition(6)\n"
[ERROR][2024-12-29 15:06:22] ...p/_transport.lua:36     "rpc"   "clangd"        "stderr"        "V[15:06:22.150] ASTWorker running Definitions on version 0 of /Users/brax/projects/sandbox/clangd-symlink/main/main.c\n"
[ERROR][2024-12-29 15:06:22] ...p/_transport.lua:36     "rpc"   "clangd"        "stderr"        "I[15:06:22.151] --> reply:textDocument/definition(6) 0 ms\n"
[ERROR][2024-12-29 15:06:22] ...p/_transport.lua:36     "rpc"   "clangd"        "stderr"        'V[15:06:22.151] >>> {"id":6,"jsonrpc":"2.0","result":[{"range":{"end":{"character":8,"line":0},"start":{"character":5,"line":0}},"uri":"file:///Users/brax/projects/sandbox/clangd-symlink/symlink/foo.h"}]}\n\n'
```

So at least in my case, there's clearly nothing Neovim can be expected to reasonably do here. It's simply getting the "wrong answer" from clangd. I think burden of proof would be on OP to prove that Neovim is doing something wrong in his specific case, because it still sounds like a clangd issue -- Neovim has no control over how clangd indexes the project.

**Comment by azieba** [comment]
[clangVim.log](https://github.com/user-attachments/files/18270824/clangVim.log)
[clangNeo.log](https://github.com/user-attachments/files/18270825/clangNeo.log)

Here are the clang logs from Vim where the indexation is triggered and in Neovim where it is not triggered. I cant figure out yet what is the difference that makes the difference.
The compilation database and clang are the same in both cases.

**Comment by andrewbraxton** [comment]
Someone would have to do more digging to figure out the exact reason for the difference and whether it is reasonably 'fixable' in Neovim, but perhaps this clangd issue is more directly relevant to your report?

https://github.com/clangd/clangd/issues/1608

**Comment by azieba** [comment]
Turns out that the option -compile-commands-dir=/home_ssd/q/sources/pioneer passed to clangd makes the difference.

This path is the project root dir with symlink resolved.

So far I have used shell wrapper to add this parameter to clangd to test.
