### ISSUE TITLE
Can't build Neovim on NetBSD

### ISSUE THREAD

**Issue by marchelzo** [neovim/neovim#3107]
I'm running NetBSD 7.0 RC2, and I'm getting the following error while attempting to build Neovim.

```
gmake[3]: Entering directory '/home/marchelzo/neovim/.deps'
[100%] Generating usr/lib/luarocks/rocks/nvim-client
Warning: falling back to curl - install luasec to get native HTTPS support

Error: Build error: Missing build.modules table
CMakeFiles/nvim-client.dir/build.make:51: recipe for target 'usr/lib/luarocks/rocks/nvim-client' failed
gmake[3]: *** [usr/lib/luarocks/rocks/nvim-client] Error 1
gmake[3]: Leaving directory '/home/marchelzo/neovim/.deps'
CMakeFiles/Makefile2:441: recipe for target 'CMakeFiles/nvim-client.dir/all' failed
gmake[2]: *** [CMakeFiles/nvim-client.dir/all] Error 2
gmake[2]: Leaving directory '/home/marchelzo/neovim/.deps'
Makefile:75: recipe for target 'all' failed
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory '/home/marchelzo/neovim/.deps'
Makefile:68: recipe for target 'deps' failed
gmake: *** [deps] Error 2
```

I can see that it's got something to do with `luarocks`, but I have no idea how to fix the problem. Any help would be appreciated.

**Comment by Pyrohh** [comment]
Is LuaRocks available in pkgsrc? If so, could you try this:

```
$ echo "DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_LUAROCKS=OFF" > local.mk
$ gmake distclean && gmake
```

Also, do you have `unzip` installed? Besides that I can't think of anything else at the moment...

**Comment by fwalch** [comment]
Could it be #2445?

**Comment by tarruda** [comment]
You can get more information by running luarocks in verbose mode, this patch should do it:

```diff
diff --git a/third-party/cmake/BuildLuarocks.cmake b/third-party/cmake/BuildLuarocks.cmake
index 14454fa..c85fd6c 100644
--- a/third-party/cmake/BuildLuarocks.cmake
+++ b/third-party/cmake/BuildLuarocks.cmake
@@ -42,7 +42,7 @@ function(BuildLuarocks)
 endfunction()

 # The luarocks binary location
-set(LUAROCKS_BINARY ${HOSTDEPS_BIN_DIR}/luarocks)
+set(LUAROCKS_BINARY ${HOSTDEPS_BIN_DIR}/luarocks --verbose)

 # Arguments for calls to 'luarocks build'
 if(MSVC)
```

**Comment by Pyrohh** [comment]
> Could it be #2445 (add make_plat)?

Ooh, that definitely looks like the problem. @marchelzo please ignore my previous advice.

**Comment by justinmk** [comment]
I think we need a version bump now, e.g. https://github.com/neovim/lua-client/commit/1bcb777a50ab1fb93da6ad5e76baa17c96720361

and then the dep in core will need to be updated.

**Comment by Pyrohh** [comment]
copying my comment from the lua repo:

We can just tell @marchelzo to apply a patch which uses the most recent commit instead of a release tag. Allowing the build to happen on netbsd might uncover a build error, like in #2.

**Comment by Pyrohh** [comment]
@marchelzo please apply the following patch, then run `gmake distclean && gmake`

```patch
diff --git a/third-party/cmake/BuildLuarocks.cmake b/third-party/cmake/BuildLuarocks.cmake
index 14454fa..e5e380b 100644
--- a/third-party/cmake/BuildLuarocks.cmake
+++ b/third-party/cmake/BuildLuarocks.cmake
@@ -122,7 +122,7 @@ if(USE_BUNDLED_BUSTED)
 
   add_custom_command(OUTPUT ${HOSTDEPS_LIB_DIR}/luarocks/rocks/nvim-client
     COMMAND ${LUAROCKS_BINARY}
-    ARGS build https://raw.githubusercontent.com/neovim/lua-client/0.0.1-12/nvim-client-0.0.1-12.rockspec ${LUAROCKS_BUILDARGS} LIBUV_DIR=${HOSTDEPS_INSTALL_DIR}
+    ARGS build https://raw.githubusercontent.com/neovim/lua-client/06b7d8a490ab93116ec7e1388e9e14382915c639/nvim-client-0.0.1-12.rockspec ${LUAROCKS_BUILDARGS} LIBUV_DIR=${HOSTDEPS_INSTALL_DIR}
     DEPENDS busted libuv)
   add_custom_target(nvim-client
     DEPENDS ${HOSTDEPS_LIB_DIR}/luarocks/rocks/nvim-client)

```

**Comment by justinmk** [comment]
By the way, why don't we run luarocks (and anything else for that matter) in [verbose mode](https://github.com/neovim/neovim/issues/3107#issuecomment-125055289) by default? It would reduce friction when people have build issues.

**Comment by Pyrohh** [comment]
The lua-client was updated a while ago to avoid the `Missing build.modules table` error message, and this repo was updated to use the lua-client version containing said fix.

Given that I'll close this, as compilation should actually be able to proceed, and any further compilation failures on NetBSD should probably have separate issues on GH.
