### ISSUE TITLE
Normal mode in cmdline

### ISSUE THREAD

**Issue by xzbdmw** [neovim/neovim#31076]
### Problem

There is a cmdwin entered by \<c-f\> in command line, with full power of vim motions, but in there you lose all the preview feature. Is it possible to support normal mode directly after typing `:`?

### Expected behavior

..

**Comment by phanen** [comment]
https://github.com/smilhey/ed-cmd.nvim

**Comment by justinmk** [comment]
> but in there you lose all the preview feature

So why don't we make that work?

It makes no sense to ask for normal-mode in cmdline-mode.
