### ISSUE TITLE
Crash with invalid link in nvim_set_hl

### ISSUE THREAD

**Issue by OXY2DEV** [neovim/neovim#31094]
### Problem

For some reason, you can set the `link` to a value that is not string.

Then trying to view that highlight group results in a crash.

![Image](https://github.com/user-attachments/assets/ddb217e3-50ec-4e81-8257-658815fb50fc)

### Steps to reproduce

nvim --clean
:lua vim.api.nvim_set_hl(0, "Test", { link = 123456789 })
:hi Test

### Expected behavior

`link` is ignored.
```txt
Test        xxx cleared
```

Or like in vim.

```txt
Test        xxx links to 123456789
```

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1727870382

### Vim (not Nvim) behaves the same?

No, vim 9.1

### Operating system/version

Android

### Terminal name/version

Termux 0.119.0

### $TERM environment variable

xterm-256color

### Installation

System package manager(pkg)

**Comment by zeertzjq** [comment]
A highlight group ID is a number

**Comment by zeertzjq** [comment]
Already fixed by #30040
