### ISSUE TITLE
vim.system does not respect executable file extensions for MS Windows

### ISSUE THREAD

**Issue by Grueslayer** [neovim/neovim#31107]
### Problem

For MS Windows there are multiple file extensions for executable files, like

- exe
- bat
- cmd
- com

These executable will be automatically found by the Windows system itself, like:

```sh
$ where winrm

C:\Windows\System32\winrm.cmd
C:\Windows\System32\winrm.vbs
```

the first one found in `%PATH%` or local directory will be run.

Normal "vim" implementation also respect these correctly (also when called from lua):

```vim
: lua print(vim.fn.executable("winrm"))

1
```

or

```vim
:lua print(vim.fn.system({"winrm"}))

Befehlszeilenprogramm zur Windows-Remoteverwaltung

Die Windows-Remoteverwaltung (WinRM) ist die Microsoft-Implementierung 
des WS-Verwaltungsprotokolls, das eine sichere Kommunikation 
...
```

BUT using `vim.system` there will be a self implemented check for the executable file which does not correctly test for all valid extensions (at least not for `.cmd`) :

```vim
:lua print(vim.inspect(vim.system({"winrm"})))

E5108: Error executing lua ...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'error'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:244: in function 'spawn'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:335: in function 'system'
	[string ":lua"]:1: in main chunk
```

while giving the full executable with extensions runs fine:

```vim
:lua print(vim.inspect(vim.system({"winrm.cmd"})))

{
  _state = {
    cmd = <1>{ "winrm.cmd" },
    done = false,
    handle = <userdata 1>,
    pid = 47000,
    stderr = <userdata 2>,
    stderr_data = {},
    stdout = <userdata 3>,
    stdout_data = {}
  },
  cmd = <table 1>,
  pid = 47000,
  <metatable> = {
    __index = {
      _timeout = <function 1>,
      is_closing = <function 2>,
      kill = <function 3>,
      wait = <function 4>,
      write = <function 5>
    }
  }
}
```

Also the vim function `vim.fn.exepath` behaves normal and gives you the correct path:

```vim
:lua print(vim.fn.exepath("winrm"))

C:\Windows\system32\winrm.CMD
```

### Steps to reproduce

see above

### Expected behavior

All default executable extensions must be respected.

### Nvim version (nvim -v)

v0.11.0-dev-226+g721551210

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

MS Windows 11

### Terminal name/version

wezterm 20241007-103714-ed430415

### $TERM environment variable

xterm-256color

### Installation

repo

**Comment by lewis6991** [comment]
I think this is expected behaviour. `vim.system` is just a wrapper around `vim.uv.spawn`, and I see no reason to give windows special treatment here.

**Comment by Grueslayer** [comment]
@lewis6991 This is fundamental IMHO for creating plugins to run on all systems.

Let's assume you want to execute "npm" or "node" to run some stuff, you'll write

```lua
vim.system({"npm", "-l", "someargs"})
```

and everywhere it runs fine (cause alls Un*x favours incl. MacOS) executables names are identical to the callled name.
Windows needs (like DOS) a fileextension to *mark* what filetype it is and if it should be executable.

So all executables (binary excutable / script executable) will have a different name on Windows BUT would be called the same.

No plugin developer will know if it is a .CMD / .BAT wrapper or compiled to .EXE.

To make it runable everyone needs to call `vim.fn.exepath` in front.

I'm with you it to fix at at `vim.uv.spawn` level!

**Comment by dundargoc** [comment]
Needing to provide a .bat suffix isn't uncommon in general, although it's annoying because it adds friction to cross platform solutions like mentioned. I think it should be "fixed", but I'm unsure at what level. Might be worth taking a look at exepath to see what it does to circumvent this.
