### ISSUE TITLE
Segmentation fault while editing a file

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#3111]
I was editing a file when nvim simply crashed with message `21569 segmentation fault (core dumped)`. I was able to recover my work thanks to the `.swp` file. However, I don't find that dump file. Do you know where I should look ?

The terminal (urxvt) is also non-responsive.

Below is my version of nvim:

```
NVIM 0.0.0-alpha+201507171736 (compiled Jul 18 2015 15:12:46)
Commit: 4d79edccdc0243a02a20ef46184b8f87f2bda290
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/yfful/documents/neovim/build/config -I/home/yfful/documents/neovim/src -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include/luajit-2.0 -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/usr/include -I/home/yfful/documents/neovim/build/src/nvim/auto -I/home/yfful/documents/neovim/build/include
Compiled by yfful@troy
```

**Comment by fmoralesc** [comment]
Please update to a more recent version, there's been some fixes related to segfaults recently.

**Comment by justinmk** [comment]
Thanks for the report. As @fmoralesc mentioned, the version you're using doesn't have https://github.com/neovim/neovim/commit/23cdebd55988a87b9f716ca39e2141c44d10854e . Please try latest.

Even if that doesn't fix it, we have other issues covering the recent segfault insurgence.
