### ISSUE TITLE
after version update to NVIM v0.11.0-dev-1108+g5a86360400

### ISSUE THREAD

**Issue by opaldone** [neovim/neovim#31128]
### Problem

after version update to NVIM v0.11.0-dev-1108+g5a86360400
I have error with golang projects
Error detected while processing VimEnter Autocommands for "*"..function <SNR>3_load_session[4]..script /home/pasha/.config/nvim/sessions/opachat/ses.v
im[39]..BufReadPost Autocommands for "*":                                                                                                             
Error executing lua callback: /opt/nv/share/nvim/runtime/filetype.lua:36: VimEnter Autocommands for "*"..function <SNR>3_load_session[4]..script /home
/pasha/.config/nvim/sessions/opachat/ses.vim[39]..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..s
cript /home/pasha/.local/share/nvim/plugged/vim-go/ftplugin/go/tagbar.vim[59]..function <SNR>80_SetTagbar[1]..go#path#CheckBinPath[8]..go#path#BinPath
[8]..go#util#env[7]..go#util#gobin[1]..<SNR>32_exec[2]..go#util#Shelljoin, line 17: Vim(set):E519: Option not supported: noshellslash                 
stack traceback:                                                                                                                                      
        [C]: in function '_with'                                                                                                                      
        /opt/nv/share/nvim/runtime/filetype.lua:35: in function </opt/nv/share/nvim/runtime/filetype.lua:10> 

### Steps to reproduce

start neovim with saved sessions

### Expected behavior

good

### Nvim version (nvim -v)

v0.11.0-dev-1108+g5a86360400

### Vim (not Nvim) behaves the same?

no vim

### Operating system/version

ubuntu

### Terminal name/version

xterm

### $TERM environment variable

256

### Installation

from zip

**Comment by ribru17** [comment]
See https://github.com/neovim/neovim/pull/28400#issuecomment-2463232687

**Comment by opaldone** [comment]
> See [#28400 (comment)](https://github.com/neovim/neovim/pull/28400#issuecomment-2463232687)

Oh yes, I use vim-go. But I don't understand, sorry :). Should I use an older version or remove fatih/vim-go?

**Comment by ribru17** [comment]
Not sure, sorry :) Just wanted to provide some context, perhaps @famiu  knows?

**Comment by zeertzjq** [comment]
Maybe someone needs to make a PR to vim-go?

**Comment by famiu** [comment]
> Maybe someone needs to make a PR to vim-go?

This seems to be the most straightforward solution as far as I can tell

**Comment by opaldone** [comment]
Thank You very much, I have removed vim-go so far, the issue can be closed

**Comment by happy-dude** [comment]
I'm not sure this ticket should be closed since there is an outstanding bug with `shellslash` being used on non-Windows platforms.

Maybe @famiu can make a new ticket specifically for it?

**Comment by famiu** [comment]
> I'm not sure this ticket should be closed since there is an outstanding bug with `shellslash` being used on non-Windows platforms.
> 
> Maybe [@famiu](https://github.com/famiu) can make a new ticket specifically for it?

It's not a bug, it's fully intended. See `news.txt`

**Comment by happy-dude** [comment]
> > I'm not sure this ticket should be closed since there is an outstanding bug with `shellslash` being used on non-Windows platforms.
> > Maybe [@famiu](https://github.com/famiu) can make a new ticket specifically for it?
> 
> It's not a bug, it's fully intended. See `news.txt`

Sounds good! Created an issue + PR for vim-go to wrap `noshellslash` into a conditional:
https://github.com/fatih/vim-go/issues/3690
https://github.com/fatih/vim-go/pull/3691
