### ISSUE TITLE
[BUG] [terminal-mode] I see "term://.//xxxx:(null)" often, but was expecting "term://.//xxxx:/path/to/foo"

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3113]
For example, I see `term://.//15973:(null)` although I have a valid terminal open:

<img width="720" alt="screen shot 2015-07-28 at 7 32 42 pm" src="https://cloud.githubusercontent.com/assets/297678/8948771/7a16d78a-355f-11e5-9d94-dd3d118fd853.png">

**Comment by ecogiko** [comment]
I get this as well. For me it happens when I save a term:// to a session, close vim, reopen everything and done. The term is now (null).

**Comment by Pyrohh** [comment]
What compiler are you using? I could have sworn that Clang generates code that prints `(null)` when printing a null pointer, i.e., using `%p` in printf(3). I can't seem to find anything about it though...

**Comment by ecogiko** [comment]
I am using gcc.

    ico@arch ~ $ cc -v
    Using built-in specs.
    COLLECT_GCC=cc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/lto-wrapper
    Target: x86_64-unknown-linux-gnu
    Configured with: /build/gcc/src/gcc-5.2.0/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --with-default-libstdcxx-abi=gcc4-compatible
    Thread model: posix
    gcc version 5.2.0 (GCC) 

This is the verbose output from nvim.

    ico@arch build $ vim -v
    NVIM 0.0.0-alpha+201507262350 (compiled Jul 31 2015 01:25:18)
    Commit: ccebc1f8d3b30536bbaab532cc5acc7ba7ec3d4b
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/ico/Code/Repositories/neovim/build/config -I/home/ico/Code/Repositories/neovim/src -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include/luajit-2.0 -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/usr/include -I/home/ico/Code/Repositories/neovim/build/src/nvim/auto -I/home/ico/Code/Repositories/neovim/build/include
    Compiled by ico@arch

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
    For differences from Vim, see :help vim-differences

       system vimrc file: "$VIM/nvimrc"
         user vimrc file: "~/.nvimrc"
     2nd user vimrc file: "~/.nvim/nvimrc"
          user exrc file: "~/.exrc"
      fall-back for $VIM: "/home/ico/.local/share/nvim"

My distro is Arch Linux.

**Comment by trusktr** [comment]
I forgot to note, it happens to me when loading sessions as well.

/#!/JoePea

**Comment by brettanomyces** [comment]
I can get a (null) doing the following

    nvim -u NONE
    :set laststatus=2
    :split term://fish

**Comment by trusktr** [comment]
Confirmed, that reproduces it.

**Comment by trusktr** [comment]
:+1: :sparkles:
