### ISSUE TITLE
Snippets: allow user to not use builtin `<Tab>` keymap

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#31132]
### Problem

Currently after expanding snippet `<Tab>` and `<S-Tab>` are remapped (in Insert and Select mode) to jump between tabstops. After exiting the snippet the original mapping are restored. The problem is if I want to redefine mapping inside tabstop, e.g. depending on `pumvisible()`. 

### Expected behavior

Allow user to opt out of these mappings.

**Comment by glepnir** [comment]
duplicate #30306
