### ISSUE TITLE
Terminal colors inside neovim from normal terminal

### ISSUE THREAD

**Issue by ianks** [neovim/neovim#3114]
When opening a terminal inside Neovim, the line colors are different feel what they should be.

### Specs:

- Terminal: termite
- 24 bit color enabled in Neovim
- color scheme, Seoul 256
- shell: zsh

**Comment by renstrom** [comment]
Are you using iTerm2? If so, what version?

**Comment by fwalch** [comment]
Also, what's `$TERM`? See https://github.com/neovim/neovim/wiki/Troubleshooting#colors-arent-displayed-correctly

**Comment by agustinvinao** [comment]
I have big issues with colors for NVim. When I open vim using the same vimrc content it looks ok. is there any way to set default colors? I've checked the fix in the link posted by fwalch, I've tested with terminal.app, iterm2 and all its the same.

Terminal: terminal.app / iterm
OS: OSX
24 bit color enabled in Neovim
Color scheme: base16-tomorrow or zenburn (screenshots with base16-tomorrow)
Shell: zsh
Tmux: yes

<img width="1137" alt="nvim" src="https://cloud.githubusercontent.com/assets/61054/9009849/17e29cbc-377a-11e5-9cdf-0fe47f716e46.png">
<img width="1137" alt="vim" src="https://cloud.githubusercontent.com/assets/61054/9009850/17e58a9e-377a-11e5-9b18-5d295503e346.png">

**Comment by ZyX-I** [comment]
> Terminal: terminal.app / iterm
> …
> Tmux: yes

This means that your terminal is tmux, not terminal.app or iterm. Tmux is interpreting all escape sequences on its own and then sends whatever escape sequences it thinks is right to send to the currently used terminal to display everything correctly. Since it does not know about 24-bit colors (note: there is a patch available somewhere to make it know) and parts of 24-bit color codes (unless expressed in a form with colons) look like other colors it cannot send right escapes to terminal.app or iTerm, but highlighting is still not completely missing.

You should disable 24-bit colors in NeoVim when using tmux.

**Comment by agustinvinao** [comment]
With let $NVIM_TUI_ENABLE_TRUE_COLOR=0 in my vimrc doesn't fix it.

Should I change any other setting?

By the way, this is how neovim looks outside tmux:

<img width="1113" alt="screen shot 2015-07-31 at 12 09 33 pm" src="https://cloud.githubusercontent.com/assets/61054/9010404/16a9c016-377d-11e5-9a42-81cdc164b441.png">

**Comment by fmoralesc** [comment]
The original issue isn't resolved, reopening.

**Comment by ZyX-I** [comment]
@agustinvinao Is not vimrc too late? AFAIR you can only set this in shell before launching NeoVim.

**Comment by ZyX-I** [comment]
@agustinvinao Look outside tmux means that your terminal emulator supports true color in the same fashion tmux does. Do not know anything about terminal.app, but iterm does not support true color until some second version.

**Comment by agustinvinao** [comment]
@ZyX-I I've tested with ITerm v2 too, all my tests are with "let $NVIM_TUI_ENABLE_TRUE_COLOR=0":

ITerm2 + Tmux + NVim
<img width="1180" alt="item2-tmux-nvim" src="https://cloud.githubusercontent.com/assets/61054/9010817/b5b8c092-377f-11e5-9f3d-ef9e933ddf42.png">

ITerm2 + NVim
<img width="1180" alt="iterm2-nvim" src="https://cloud.githubusercontent.com/assets/61054/9010825/c0b4bf64-377f-11e5-9f87-550d29c9a447.png">

**Comment by ZyX-I** [comment]
@agustinvinao 

1. Which version exactly?
2. I am wrong, and setting it in the vimrc appears to be not too late. But setting it to zero (== non-empty string) is not different from setting it to one (== non-empty string). You need to either unset this variable or set it to the empty string (note: you can’t unlet from within NeoVim).

**Comment by renstrom** [comment]
@agustinvinao Make sure you're using the iTerm2 nightly (http://iterm2.com/downloads/nightly/).

@ianks What if you try another colorscheme, my experience is that some mess with the shell colors (like base16-eighties), and some don't (vim-hybrid).

**Comment by agustinvinao** [comment]
@ZyX-I unsetting $NVIM_TUI_ENABLE_TRUE_COLOR was the solution.

All working good in terminal.app, I'll check @renstrom to update to nightly version.

Great job and its a very nice thing to have this project going on.

**Comment by ZyX-I** [comment]
@agustinvinao 

// For future: do not fool yourself by using `let $… = number`. Environment variable can *never* be anything, but string, so when you use `let $… = 0` zero is implicitly converted into a string. But zero looks like false and `'0'` does not. Usually for “boolean” environment variables set/unset semantics is used (due to historical reasons unset and empty are considered to be the same under most circumstances), especially this is the case in applications where it is easier just to test whether variable is unset then parse it. C apps usually fall into this category, as well as shell apps.

**Comment by justinmk** [comment]
Closing, unless there is a specific issue not covered by the posts above.

**Comment by bigchirv** [comment]
I also have the same problem. As you can see, the colors from the terminal in neovim doesn't correspond to the ones on the right (just the terminal).

![screenshot from 2016-01-27 14-27-10](https://cloud.githubusercontent.com/assets/1088243/12624700/8c377964-c502-11e5-943d-7b187c9fe144.png)

In my ```.bashrc``` I have this:

```bash
#Neovim true color support
export NVIM_TUI_ENABLE_TRUE_COLOR=1
#Neovim cursor shape support
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1
```

My neovim configuration is here: https://github.com/bigchirv/neovim-distribution

I would love to know how can I fix it or, if it is actually a bug, reopen this issue report.

Thanks!

**Comment by renstrom** [comment]
@bigchirv your colorscheme is probably lacking `g:terminal_color_0`-`g:terminal_color_15`.

**Comment by ianks** [comment]
@renstrom I just checked gruvbox, and they are indeed missing `terminal_color_X` AFAICT. Given this is one of the more popular colorschemes, I tend to think that most color schemes will not implement `terminal_color` for quite some time. Maybe it would be reasonable to fallback to reasonable defaults? Is this even possible?

**Comment by bigchirv** [comment]
Thanks @renstrom! Adding the ```g:terminal_color_*``` to my colorscheme did the trick. For not repeating info here and there, here's more information on setting ```g_terminal_color_*```:  https://github.com/neovim/neovim/issues/2897#issuecomment-115464516

**Comment by inakido** [comment]
Hi, I have an issue with the color black inside the terminal emulator. The rest of the colors seem to display right but for some reason black is not inherited from the regular terminal.
I have tried seting `g:terminal_color_*`, but with no result.
In editing mode, all colors are displayed properly.

![2016-03-05-17-37-06](https://cloud.githubusercontent.com/assets/11045073/13548851/b79da910-e2f9-11e5-88be-87ab5d289bf1.png)

**Comment by bloodbornedisease** [comment]
the fact that there still isn't a straightforward way to get neovim to simply use default terminal colors is baffling
