### ISSUE TITLE
Health headings highlight breaks with listchars multispace

### ISSUE THREAD

**Issue by yochem** [neovim/neovim#31145]
### Problem

![Image](https://github.com/user-attachments/assets/75a3e241-d1fd-471d-ad4c-7b9d41223796)

- listchars multispace breaks the visual heading of `:checkhealth`. 
- `:set listchars-=multispace:••` restores the heading. 
- Running `:Inspect` on the space part in the heading only shows the hl group of the heading, so no clue how this multispace gets highlighted.
- `:hi clear Whitespace` (which should highlight listchars) doesn't change anything.

### Steps to reproduce

nvim --clean
:set list listchars+=multispace:++
:checkhealth

### Expected behavior

A continuous header, with or without the listchars char (I don't care if it shows ++ or nothing, but the background should be the same).

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1096+g079e5f4f9b-Homebrew

### Vim (not Nvim) behaves the same?

Does not apply

### Operating system/version

MacOS v14.6.1

### Terminal name/version

iTerm2 3.5.5

### $TERM environment variable

tmux-256color

### Installation

homebrew install --HEAD neovim

**Comment by glepnir** [comment]
higlight is `Whitespace` for mulltispace and you also can disable list in health by using `:au FileType checkhealth set nolist`

**Comment by zeertzjq** [comment]
This seems to be the reverse of #23869
