### ISSUE TITLE
display of a file all scrambled when resizing terminal

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#3115]
I have a terminal with a neovim instance opened. If I want to resize that terminal, the display of the file is all botched. This does not seem to happen if I resize the terminal _slowly_. Could be related to #2528 or #1827 but not exactly the same I think, so I chose to open a new issue for this.

Also I cannot quit nvim until I press `CTRL-C` as it is unresponsive until then. You can see this when the status line at the end prints `airline#...` (cannot read the ... part).

Please see this GIF animation that shows the problem
![test](https://cloud.githubusercontent.com/assets/795879/8982290/b8b20a56-36b7-11e5-80d4-27be1117678b.gif)

**Comment by fmoralesc** [comment]
What terminal is that?

**Comment by scampi** [comment]
This is urxvt

**Comment by scampi** [comment]
btw the version:

```
NVIM 0.0.0-alpha+201507262350 (compiled Jul 28 2015 15:33:42)
Commit: ccebc1f8d3b30536bbaab532cc5acc7ba7ec3d4b
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/yfful/documents/neovim/build/config -I/home/yfful/documents/neovim/src -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include/luajit-2.0 -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/home/yfful/documents/neovim/.deps/usr/include -I/usr/include -I/home/yfful/documents/neovim/build/src/nvim/auto -I/home/yfful/documents/neovim/build/include
Compiled by yfful@troy

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
```

**Comment by justinmk** [comment]
Please re-open if this is still an issue on latest master.

**Comment by scampi** [comment]
Using latest from master (8653000782bc9ab06d865ca96c89ec586ede6411) nvim is now responsive even after resizing the terminal, thanks for the fix!

There is still some UI problem, but fortunately they don't prevent the use of the editor. I tried with `vim` and I also have some scrambling, but they are not as pronounced.
![test](https://cloud.githubusercontent.com/assets/795879/9360305/66126db4-468d-11e5-8ef3-60aa860fc2a4.gif)

**Comment by gonzaloserrano** [comment]
I'm having a similar issue in `NVIM 0.0.0-alpha+201509162200 (compiled Sep 17 2015 10:20:25)`

**Comment by edrpls** [comment]
I have a similar problem when resizing the terminal, I'm using:

NVIM 0.1.4, on iTerm2, Build 3.0.0

**Comment by kaatish** [comment]
My problem is slightly different. Neovim **does redraw** after resizing, but it does not redraw after going fullscreen. I am using Neovim 0.1.6 with Gnome Terminal 3.18.3 on Ubuntu 16.04.
