### ISSUE TITLE
ext_messages: possible offset error on iterating through chunks

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#31166]
### Problem

@luukvbaal @bfredl thank you for #27813. I try to play with the feature, but cannot get correct result for multihighlight messages. In short, 
```lua
    vim.api.nvim_echo({
      {'E', 'ErrorMsg'},
      {'W', 'WarningMsg'},
      {'A', 'DiffAdd'},
      {'C', 'DiffChange'},
    }, false, {})
```
results with chunks `{ { 24, "E", 27 }, { 44, "W", 31 }, { 20, "A", 32 }, { 21, "C", 32 } }`. 

Notice the same values for the two last elements.

### Steps to reproduce

`init.lua`:
```lua
local api = vim.api
local ns = api.nvim_create_namespace('messageRedirection')

local function log(msg)
  if 0 == #vim.trim(msg) then
    return
  end
  vim.schedule(function ()
    api.nvim_buf_set_lines(1, -1, -1, true, vim.split(msg, '\n'))
    vim.cmd.normal 'G'
  end)
end

local function notify(content)
  for _, chunk in ipairs(content) do
    local idAttr = chunk[3]
    local msg = ('[%s -> %s] %s'):format(
      tostring(idAttr),
      vim.fn.synIDattr(idAttr, 'name'),
      chunk[2]
    )
    log(msg)
  end
end

local function redraw()
  vim.schedule(function ()
    vim.cmd.redraw()
  end)
end
api.nvim_create_autocmd('CmdlineEnter', {
  callback = function ()
    vim.ui_detach(ns)
    redraw()
  end
})

api.nvim_create_autocmd({'UIEnter', 'CmdlineLeave'}, {
  callback = function ()
    vim.ui_attach(ns, {ext_messages = true, ext_cmdline = false}, function (event, kind, content, _replace_last)
      if event == 'msg_show' and (kind == 'emsg' or kind == 'echo' or kind == 'lua_error') then
        log(vim.inspect(content))
        notify(content)
      end
      redraw()
    end)
    api.nvim_echo({
      {'E', 'ErrorMsg'},
      {'W', 'WarningMsg'},
      {'A', 'DiffAdd'},
      {'C', 'DiffChange'},
    }, false, {})
  end
})
```

I get
```
{ { 24, "E", 27 }, { 44, "W", 31 }, { 20, "A", 32 }, { 21, "C", 32 } }
[27 -> WarningMsg] E
[31 -> DiffAdd] W
[32 -> DiffChange] A
[32 -> DiffChange] C
```

### Expected behavior

Probably: fixed offset.

### Nvim version (nvim -v)

v0.11.0-dev-1134+gff575b3886

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

**Comment by luukvbaal** [comment]
Oops, I guess I neglected to follow the attr logic when first testing if passing the highlight id worked properly, and then only ever verified single highlight messages. Thanks for the repro, #31167 should fix it.

**Comment by przepompownia** [comment]
Thank you for quick fix, now I see
```
{ { 24, "E", 7 }, { 44, "W", 27 }, { 20, "A", 31 }, { 21, "C", 32 } }
[7 -> ErrorMsg] E
[27 -> WarningMsg] W
[31 -> DiffAdd] A
[32 -> DiffChange] C
```
as expected. 

It would be good to publish in the documentation someday a more detailed explanation of the practical use of the first chunk element that existed before.

**Comment by luukvbaal** [comment]
> It would be good to publish in the documentation someday a more detailed explanation of the practical use of the first chunk element that existed before.

I think that's covered by the docs for [hl_attr_define](https://neovim.io/doc/user/ui.html#ui-event-hl_attr_define) and some earlier excerpts earlier from ui.txt. It's for remote UI's, not vim.ui_attach, hence #27813 :)

**Comment by przepompownia** [comment]
> I think that's covered by the docs for [hl_attr_define](https://neovim.io/doc/user/ui.html#ui-event-hl_attr_define) and some earlier excerpts from ui.txt. It's for remote UIs, not vim.ui_attach, hence [#27813](https://github.com/neovim/neovim/pull/27813) :)

Does it mean that the only way to translate these ids to more usable information is catching `hl_attr_define` event somewhere? This is just out of curiosity, since we have hl ids.

**Comment by luukvbaal** [comment]
Yes, but since that event is not available to vim.ui_attach consumers, your only other option was to use internal functions through FFI. Which I believe is what noice.nvim does.

**Comment by przepompownia** [comment]
A few months ago I tried to understand what was happening in Noice's FFI (and gave up) and ask about attr ids on our matrix chat, but no one responded then. The repro comes from that time and is slightly modified for this issue. I only know about #27813 after the merge. It's a nice feature useful for `cmdheight=0` cases. The next step is to find (or write) a simple notification plugin able to pass highlighted messages and encounter redirection issues.
