### ISSUE TITLE
How to compile neovim with all optional features ?

### ISSUE THREAD

**Issue by atrniv** [neovim/neovim#3116]
I'm trying to compile neovim with the visualextra feature enabled. However I can't seem to figure out how to do it. The help file says I must edit it in the features.h file, however I can't find any file by that name.

**Comment by mhinz** [comment]
Opposed to Vim, Neovim will always build the huge feature set. You can verify this with `:echo has('visualextra')`

**Comment by fmoralesc** [comment]
This seems like a bug in the help files. What was the help file you
consulted?

**Comment by atrniv** [comment]
I found it mentioned in the help file for version. Also I originally came across this because I was trying to use the I key after visually selecting a block and it kept going to only the first line of the block and inserting. A stackoverflow question suggested that it may be because of the visualextra not being compiled. Is this a bug in the visual mode or am I doing something wrong ?

**Comment by atrniv** [comment]
Ah alrite i figured it out. I guess its because the visual block insert does not update till i leave visual block mode.

**Comment by adoyle-h** [comment]
@mhinz Why does not my neovim have the `mouseshape` feature?  `:echo has('mouseshape')` shows `0`.

current version:
```
NVIM v0.1.5-53-g6bb4b9f
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160427-327-hh0jv/build/config -I/tmp/neovim-20160427-327-hh0jv/src -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/tmp/neovim-20160427-327-hh0jv/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160427-327-hh0jv/build/src/nvim/auto -I/tmp/neovim-20160427-327-hh0jv/build/include

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences
```

**Comment by sassanh** [comment]
Same here, `has('mouseshape')` returns 0.

**Comment by ZyX-I** [comment]
@adoyle-h Because this feature is not needed, I have no idea why it exists in first place. We have `guicursor` setting working in terminals which support cursor shape and there is no need to have a setting with duplicate functionality.

**Comment by sassanh** [comment]
@ZyX-I I'm confused, I thought `guicursor` sets terminal cursor (like block, horizontal bar, vertical bar, blink, etc) and `mouseshape` sets mouse pointer shape. Am I missing something?

**Comment by ZyX-I** [comment]
@sassanh I am wrong then, thought about the built-in cursor. Then feature is not supported currently.

**Comment by ZyX-I** [comment]
@sassanh If you need this, open a separate issue: aside from the very few system-dependent or even fewer compile-time features like +debug (I actually know only this) all features present are enabled always. So asking here for “why feature X is missing” is useless, there is no compile-time switch to enable it.

**Comment by sassanh** [comment]
@ZyX-I I see, thanks for clarification. I just thought maybe there are exceptions. I just ran `has('mouseshape')` and it returned 0 and it made me confused. I think neovim documents needs some update to notice `mouseshape is not supported yet` for example.

**Comment by justinmk** [comment]
For reference, the `mouse_shape` field is sent in `mode_info_set` UI event, but it isn't implemented yet.
