### ISSUE TITLE
Sync version of `vim.lsp.buf.code_action`, allowing code actions on save

### ISSUE THREAD

**Issue by fnune** [neovim/neovim#31176]
### Problem

Hi! I made this plugin to call code actions on save. Most of the work was in figuring out that a sync version of `vim.lsp.buf.code_action` is needed, and in coercing Neovim to call code actions synchronously, by inspecting how Neovim calls them synchronously and repeating the code.

This would be much easier, and probably my plugin would not be needed if there were a `vim.lsp.buf.code_action_sync` variant.

### Expected behavior

```lua
-- Can be called on a `BufWritePre` autocmd
vim.lsp.buf.code_action_sync({
  context = { only = { "source.organizeImports" } },
  apply = true,
})
```

### Alternative

Currently this is what I do in my plugin, it's not great:

https://github.com/fnune/codeactions-on-save.nvim/blob/main/lua/codeactions-on-save/main.lua#L15-L37

**Comment by fnune** [comment]
Thanks for linking! A callback does not make the whole thing sync, no? How would that work within e.g. a `BufWritePre` `autocmd`?

**Comment by lewis6991** [comment]
You can use `vim.wait`. We are not providing sync versions for every `vim.lsp.buf.*` function, but we will provide continuations for them. This can then be used with whatever we implement for #19624.

**Comment by aktau** [comment]
> ...but we will provide continuations for them.

OK. That is workable (either coding it in a raw version using `vim.wait()` or using libraries like coop.nvim (https://github.com/neovim/neovim/issues/19624#issuecomment-2466700118).

But, that does require that `vim.lsp.buf.code_action` learns about a `cb` argument. Would that be accepted, or are you not sure about the approach yet?

**Comment by lewis6991** [comment]
> But, that does require that vim.lsp.buf.code_action learns about a cb argument. Would that be accepted, or are you not sure about the approach yet?

Yes eventually, but this will be done for all `vim.lsp.buf` functions in one go.

And going forward, I want to require that all async functions provide a continuation.
