### ISSUE TITLE
Typst: option 'commentstring' is empty

### ISSUE THREAD

**Issue by foxyseta** [neovim/neovim#31178]
### Problem

When using bindings to (un)comment Typst code, I get

```
Option 'commentstring' is empty.
```

However, I can correctly use the same bindings to (un)comment code in buffers associated to different filetypes.

### Steps to reproduce

``` bash
# No config needed
nvim --clean
```

### Expected behavior

Typst code is (un)commented, and no error message is displayed

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: MinSizeRel LuaJIT 2.1.1710398010

### Vim (not Nvim) behaves the same?

vim does not have this feature to being with

### Operating system/version

Alpine Linux 3.21.0_alpha20240923

### Terminal name/version

wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

Alpine Package Manager (APK)

**Comment by clason** [comment]
Please share reproducible steps (including typst code you tested and the exact location you trigger the commenting).

**Comment by foxyseta** [comment]
Actually, when running `nvim --clean a.typ`, and invoking `:set filetype`, I observe that the filetype is detected correctly.

**Comment by clason** [comment]
Yes, but you still need a ftplugin that sets the correct commentstring, and that has been added after the 0.10 release so will only be part of 0.11 (or nightlies).

**Comment by foxyseta** [comment]
I see, thank you! My mistake.
