### ISSUE TITLE
LSP: NeoVim crashes when deleting a line with active diagnostic from gopls

### ISSUE THREAD

**Issue by harrydayexe** [neovim/neovim#31171]
### Problem

I was setting up my new Mac today when I encountered an issue I did not have previously. Not sure if this is an M4 issue (was previously on an Intel based Mac and have since upgraded to M4). 

When deleting a line with a diagnostic log showing from gopls, NeoVim crashes and I have to complete close my terminal to be able to recover. 

I have tested with other LSPs (PyRight and TSServer) and the behaviour was not present on these however I cannot be sure. 

### Steps to reproduce using "nvim -u minimal_init.lua"

1. Create a go file with the gopls LSP active. 
2. Create an error in the file (such as declaring `package main` twice)
3. Delete the line once the diagnostic log appears using `dd`

NeoVim will subsequently hang/crash.

I have noticed in Activity Monitor that the GoPls process sees no noticeable change, however the NeoVim process spikes to 100% CPU time.

### Expected behavior

NeoVim does not hang

### Nvim version (nvim -v)

v0.10.2

### Language server name/version

gopls 0.16.2

### Operating system/version

15.1 (24B2082)

**Comment by zeertzjq** [comment]
Cannot reproduce on Linux

**Comment by harrydayexe** [comment]
I also cannot reproduce this on an intel based Mac, I believe this may be due to Apple Silicon but I am unsure on how to debug this further. If someone can give me any instructions to produce some logs which may be useful in debugging, I am more than happy to follow them and provide the information I can

**Comment by telemachus** [comment]
I cannot reproduce with minimal_init.lua, and I'm also on an Arm Mac running 15.1 and using gopls 0.16.2. (What exact minimal_init.lua did you use?)

**Comment by harrydayexe** [comment]
Let me come up with a minimal init to reproduce the bug, will report back

**Comment by harrydayexe** [comment]
Nevermind this was not an issue with the gopls lsp, I have tracked the issue down to only occurring when the lukas-reineke/indent-blankline.nvim is being used. I will close this thread and open an issue over there
