### ISSUE TITLE
Unable to build WSL Ubuntu

### ISSUE THREAD

**Issue by IamSmeagol** [neovim/neovim#31174]
### Problem

I tried following the steps to build from source, but I faced this error multiple times
```
        [C]: in function 'error'
        ...ocal/src/neovim/src/nvim/generators/gen_declarations.lua:321: in main chunk
        [C]: at 0x55fa46f50350
```

I made sure I had the prerequisites by running `sudo apt-get install ninja-build gettext cmake unzip curl` and I checked the versions of gcc and cmake
gcc version 11.4.0
cmake version 3.22.1

I tried make distclean but it did not fix this issue
The first 112 steps complete, but it fails shortly after the x/~650 (around 650, it changed numbers when I ran cmake a second time)

### Steps to reproduce

- Ensure all build prerequisites are complete
- Clone the repository
- `cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo`

### Expected behavior

The build is successful and I am able to use neovim from source.

### Nvim version (nvim -v)

v0.10.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

WSL Ubuntu 22.04 (Windows 11 23H2)

### Terminal name/version

Windows Terminal v1.21.2911.0

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by dundargoc** [comment]
Not enough info. Can you post the full build logs in a gist?

**Comment by IamSmeagol** [comment]
Here is the [build log](https://gist.github.com/IamSmeagol/3bf0af8044477783e4dd8f5e8edb8e72)
- LuaJIT was built
- It breaks at line 1091

Is there anything else that I can provide that would help?

**Comment by dundargoc** [comment]
Can't recreate it. No clue what could cause this. If you're motivated you can try building with older versions of neovim and see if you can bisect when this problem started.

**Comment by IamSmeagol** [comment]
> If you're motivated you can try building with older versions of neovim and see if you can bisect when this problem started.
I couldn't figure out how to do that, could you please let me know how I could? (Or point me to the right place to learn)

**Comment by zeertzjq** [comment]
`git bisect --help`

**Comment by IamSmeagol** [comment]
Update: I was able to build the latest release v10.2 's binary. I am still waiting for the docs, once it finishes I will try to do a later nightly.

**Comment by IamSmeagol** [comment]
The docs never finished (after waiting a few hours), but I was able to run neovim 10.2 (the help command failed). I tried going to the latest commit and running `make CMAKE_BUILD_TYPE=RelWithDebInfo` but it failed like before. Any idea why it froze at the docs? - no error was given.

**Comment by justinmk** [comment]
try `cmake --build build --verbose` https://github.com/neovim/neovim/blob/3e3a9843004683db142bd17f9bf36a5dab7b7ac8/CMakeLists.txt#L7
