### ISSUE TITLE
neovim hangs on autocomplete

### ISSUE THREAD

**Issue by KIVELV25484-pki** [neovim/neovim#31189]
### Problem

neovim hangs on autocomple, might be related to https://github.com/neovim/neovim/issues/31129

### Steps to reproduce

1. Open typescript file.
2. Type `const foo: Record<>`.
3. On the second angle bracket the instance freezes.

### Expected behavior

Should complete angle bracket.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.0.1

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by Shougo** [comment]
Can you upload the minimal config to reproduce the problem?

**Comment by clason** [comment]
> neovim hangs on autocomple, might be related to https://github.com/neovim/neovim/issues/31129

What does that have to do with autocomplete? That issue is fixed on homebrew; please uninstall and reinstall tree-sitter and neovim to check.

**Comment by KIVELV25484-pki** [comment]
Happens with stock LazyVim. https://github.com/LazyVim/LazyVim/issues/4773#issuecomment-2471369741 mentioned it is a upstream issue.

**Comment by clason** [comment]
Stock LazyVim is not Neovim. Please create a minimal reproducing example without it.

**Comment by clason** [comment]
And if you have not, follow the steps from the linked issue(s): uninstall and reinstall tree-sitter.

**Comment by KIVELV25484-pki** [comment]
🤦 reinstalling did in fact fix the issue. Thanks for your trouble.

**Comment by jamwil** [comment]
Reinstalling neovim and tree-sitter resolved this for me as well.
