### ISSUE TITLE
statusline behavior changed

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#31187]
### Problem

The statusline of an inactive window will be dimmed

### Steps to reproduce

nvim --clean
:let &g:statusline="%#Visual#%{'['.winnr().']'}%#Normal#"
ctrl-w  n
The statusline of an inactive window will be dimmed

### Expected behavior

The old version is not like this

### Nvim version (nvim -v)

NVIM v0.11.0-dev

### Vim (not Nvim) behaves the same?

x

### Operating system/version

linux

### Terminal name/version

x

### $TERM environment variable

x

### Installation

x

**Comment by Shougo** [comment]
`StatusLineNC` is set in default.
It is also set in Vim.

It seems from runtime colorscheme.

**Comment by zgpio** [comment]
> It is not bug. `StatusLineNC` highlight is set in default. It is also set in Vim.
> 
> It seems from runtime colorscheme.

:version
NVIM v0.11.0-dev-310+g9e436251d                                                                                                                                                             Build type: RelWithDebInfo                                                                                                                                                                  LuaJIT 2.1.1716656478

**Comment by zshuzh** [comment]
|                        | `:co default`  | `:co vim` |
| ------------- | ------------- | ------------- |
| `:hi StatusLine` | `cterm=reverse` <br/> `guifg=NvimDarkGrey3` <br/> `guibg=NvimLightGrey3`           |  `cterm=bold,reverse` <br/> `gui=bold,reverse` |
| `:hi StatusLineNC` | `cterm=bold,underline` <br/> `guifg=NvimLightGrey3` <br/> `guibg=NvimDarkGrey3` | `cterm=reverse` <br/> `gui=reverse` |

The old `vim` colorscheme makes the active window's statusline bold, but the new `default` colorscheme makes the inactive window's statusline "dim". It's technically not consistent with previous versions, but I think it looks better now 🤔

**Comment by clason** [comment]
Yes, the default colorscheme was _intentionally_ changed.
