### ISSUE TITLE
rpcconnect(): nvim client <=> server

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3119]
`nvim` should provide client capabilities to connect to and communicate with other `nvim` servers.

**Comment by fmoralesc** [comment]
:+1: This is the reason I made [nvimfs](https://github.com/fmoralesc/nvimfs). Builtin support would be much better.

**Comment by DarkDefender** [comment]
I would love if there was an option to have the clients show the cursor position of other connected clients. IE if two clients are connected to the same server and are editing the same file, the other clients cursor is displayed (perhaps with an other color so one could easily see which cursor belongs to whom).

I'm guessing this is not in the current scope of this feature request though...

**Comment by jalcine** [comment]
@DarkDefender that sounds like something that can be provided via a plug-in; having client report status to main server and then inquiring clients outputting information accordingly.

**Comment by tarruda** [comment]
@fmoralesc cool :smile:

**Comment by tarruda** [comment]
Right now my primary focus is getting 0.1 ready so I cant put much effort on extra features, but since this is commonly requested, here's a starting point for anyone interested in pursuing it:

```diff
`diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index c7c67cf..f6a1fc7 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -6708,6 +6708,7 @@ static struct fst {
   {"resolve",         1, 1, f_resolve},
   {"reverse",         1, 1, f_reverse},
   {"round",           1, 1, f_round},
+  {"rpcconnect",      1, 1, f_rpcconnect},
   {"rpcnotify",       2, 64, f_rpcnotify},
   {"rpcrequest",      2, 64, f_rpcrequest},
   {"rpcstart",        1, 2, f_rpcstart},
@@ -13640,6 +13641,30 @@ static void f_round(typval_T *argvars, typval_T *rettv)
   float_op_wrapper(argvars, rettv, &round);
 }

+// "rpcconnect(address)" function
+static void f_rpcconnect(typval_T *argvars, typval_T *rettv)
+{
+  rettv->v_type = VAR_NUMBER;
+  rettv->vval.v_number = 0;
+
+  if (check_restricted() || check_secure()) {
+    return;
+  }
+
+  if (argvars[0].v_type != VAR_STRING) {
+    EMSG2(_(e_invarg2), "Remote address must be a string");
+    return;
+  }
+
+  uint64_t channel_id = channel_from_address((char *)argvars[0].vval.v_string);
+
+  if (!channel_id) {
+    EMSG(_(e_api_spawn_failed));
+  }
+
+  rettv->vval.v_number = (varnumber_T)channel_id;
+}
+
 // "rpcnotify()" function
 static void f_rpcnotify(typval_T *argvars, typval_T *rettv)
 {
diff --git a/src/nvim/event/socket.c b/src/nvim/event/socket.c
index 347e464..22332d2 100644
--- a/src/nvim/event/socket.c
+++ b/src/nvim/event/socket.c
@@ -144,6 +144,44 @@ void socket_watcher_close(SocketWatcher *watcher, socket_close_cb cb)
   uv_close((uv_handle_t *)watcher->stream, close_cb);
 }

+bool socket_watcher_connect(SocketWatcher *watcher, Stream *stream,
+    int timeout, void *data)
+{
+  bool result = false;
+  uv_connect_t connect;
+  uv_stream_t *server;
+
+  if (watcher->stream->type == UV_TCP) {
+    server = (uv_stream_t *)&stream->uv.tcp;
+    uv_tcp_init(watcher->uv.tcp.handle.loop, (uv_tcp_t *)server);
+    uv_tcp_connect(&connect, &stream->uv.tcp,
+        (const struct sockaddr *)&watcher->uv.tcp.addr, connected_cb);
+  } else {
+    server = (uv_stream_t *)&stream->uv.pipe;
+    uv_pipe_init(watcher->uv.pipe.handle.loop, (uv_pipe_t *)server, 0);
+    uv_pipe_connect(&connect, &stream->uv.pipe, watcher->addr,
+        connected_cb);
+  }
+
+  connect.data = &result;
+  LOOP_PROCESS_EVENTS_UNTIL(watcher->stream->loop->data, NULL, timeout,
+      got_int);
+  got_int = false;
+  stream_init(NULL, stream, -1, server, data);
+
+  return result;
+}
+
+static void connected_cb(uv_connect_t *handle, int status)
+{
+  if (status == 0) {
+    bool *result = handle->data;
+    *result = true;
+  }
+  got_int = true;
+  uv_stop(handle->handle->loop);
+}
+
 static void connection_event(void **argv)
 {
   SocketWatcher *watcher = argv[0];
diff --git a/src/nvim/msgpack_rpc/channel.c b/src/nvim/msgpack_rpc/channel.c
index 0e3b820..571863b 100644
--- a/src/nvim/msgpack_rpc/channel.c
+++ b/src/nvim/msgpack_rpc/channel.c
@@ -147,6 +147,25 @@ uint64_t channel_from_process(char **argv)
   return channel->id;
 }

+uint64_t channel_from_address(const char *address)
+{
+  Channel *channel = register_channel(kChannelTypeSocket);
+  SocketWatcher temp;
+  socket_watcher_init(&loop, &temp, address, NULL);
+  if (!socket_watcher_connect(&temp, &channel->data.stream, -1, channel)) {
+    decref(channel);
+  }
+  incref(channel);  // close channel only after the stream is closed
+  channel->data.stream.internal_close_cb = close_cb;
+  channel->data.stream.internal_data = channel;
+  wstream_init(&channel->data.stream, 0);
+  rstream_init(&channel->data.stream, CHANNEL_BUFFER_SIZE);
+  rstream_start(&channel->data.stream, parse_msgpack);
+  socket_watcher_close(&temp, NULL);
+  LOOP_PROCESS_EVENTS(&loop, NULL, 0);
+  return channel->id;
+}
+
 /// Creates an API channel from a tcp/pipe socket connection
 ///
 /// @param watcher The SocketWatcher ready to accept the connection
```

I haven't tested this much, but I'm able to create channels and call basic msgpack-rpc methods with `rpcconnect` passing the remote nvim's $NVIM_LISTEN_ADDRESS. A more complete PR could include:

- correct implementation of timeout/interrupt for rpcconnect
- basic docs
- an object-oriented vimscript client library that wraps `rpcconnect`/`rpcrequest`
- functional tests


Here's an example(assuming there's a running instance listening on /tmp/nvim):

```vim
let cid = rpcconnect('/tmp/nvim')
let buf = rpcrequest(cid, 'vim_get_current_buffer')
call rpcrequest(cid, 'vim_set_current_line', 'line 1')
echo rpcrequest(cid, 'buffer_get_line_slice', buf, 0, -1, 1, 1)
```

**Comment by justinmk** [comment]
Great! I didn't intend anyone to work on this, but I have been avoiding pursuing actually interesting features until all the other loose ends are tied up.

**Comment by justinmk** [comment]
> an object-oriented vimscript client library that wraps rpcconnect/rpcrequest

If by "object-oriented" you mean "dictionary functions", I would suggest not. There's nothing great about them, and they're harder to debug.

In general I don't think implementing this in vimscript is desirable because it means `nvim` depends on the runtime for this essential functionality.

**Comment by adithep** [comment]
+1

**Comment by samvv** [comment]
I'll give it a shot, but it will take me a while (at the moment I can't even seem to get HEAD working), so if anyone else with more experience can do it, it will be better I guess.

**Comment by ikcalB** [comment]
What about this, guys? Working in terminal inside nvim is nice, opening a file in the current instance should really be a no brainer

**Comment by KillTheMule** [comment]
Check out [nvr](https://github.com/mhinz/neovim-remote) in the mean time.

**Comment by bfredl** [comment]
#8326 is WIP for the builtin implementation.

**Comment by bfredl** [comment]
"rpcconnect" is available as`sockconnect()`, we have other issues for "client server"

**Comment by ikcalB** [comment]
so, `nvr` it is, then?

**Comment by KillTheMule** [comment]
You can also use https://github.com/alopatindev/nvim-send if that fits better (I do use both `nvr` and `nvim-send` in different settings).

**Comment by ikcalB** [comment]
Thanks, happy woth nvr for my use case. Just wanted to know if something had been implemented.
