### ISSUE TITLE
C_/ isn't OK on kitty terminal it seems

### ISSUE THREAD

**Issue by metal3d** [neovim/neovim#31197]
### Problem

I'm using an AZERTY keyboard on Fedora 41.

I'm using LazyVim that bind the key `<C_/>` to open terminal. It works great with Gnome-Terminal, Xterm or even WezTerm.

But, with kitty, the keybinding acts like I only press `/`. 

I thought that was a kitty-terminal problem and reported the bug here https://github.com/kovidgoyal/kitty/issues/8046 (Please disregard the disagreement between the author and me in this conversation.)
The author explains that NeoVim probably not interpret the keybinding as it should.

At this time, and I don't know why, pressing `Ctrl \` acts like if I press `Ctrl Shift /`

### Steps to reproduce

I only installed LazyVim and pressed `Ctrl Shift /` on different terminal emulator

### Expected behavior

To have the same mapping on kitty-terminal than with WezTerm or Gnome terminal

### Nvim version (nvim -v)

v0.10.2 

### Vim (not Nvim) behaves the same?

I don't use vim

### Operating system/version

Fedora Linux 41

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

Fedora Packages

**Comment by mfussenegger** [comment]
Sounds related to https://github.com/neovim/neovim/issues/31045

**Comment by justinmk** [comment]
Then let's consider this a duplicate, don't need a different issue for each AZERTY key.

Also try the development build https://github.com/neovim/neovim/releases
