### ISSUE TITLE
g:markdown_folding is applied on yaml header

### ISSUE THREAD

**Issue by avidseeker** [neovim/neovim#31203]
### Problem

Yaml header is folded when "let g:markdown_folding = 1".

```
---
## title: MWE [4 lines]······························································
```

### Steps to reproduce

Step 1: mwe.md
```markdown
---
title: MWE
---

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
```

Step 2
```sh
nvim -u <(echo "let g:markdown_folding = 1") mwe.md
```

### Expected behavior

Screen rendered as
```
---
title: MWE
---

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
```

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

Linux

### Terminal name/version

xterm

### $TERM environment variable

xterm-256

### Installation

pacman

**Comment by zeertzjq** [comment]
This should be reported to https://github.com/tpope/vim-markdown

**Comment by avidseeker** [comment]
> Vim (not Nvim) behaves the same?
> 
> no, vim 9.1

Curiously, this doesn't happen to Vim.

**Comment by zeertzjq** [comment]
You Vim version is too old
