### ISSUE TITLE
Unable to disable stock syntax highlighting / `:syntax off` ignored

### ISSUE THREAD

**Issue by rwbaskette** [neovim/neovim#31200]
### Problem

`:syntax off` ignored by the editor when in a default, out-of-the-box-state in:

```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

### Steps to reproduce

1) Remove every  neovim configuration file so it is 100% stock ensuring there is no /usr/local config as well
2) Create a `~/.config/nvim/init.lua` file that contains a highlight-able token:
```
vim.opt.background = "light"
```
Note the string highlighting.
3) Restart neovim
4) `:syntax off`, observe the highlight is still enabled

If you load this file in vim9 with no `~/.vimrc` and perform the same actions, it will disable the automatic syntax highlighting

### Expected behavior

Syntax highlighting should be disabled

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 04 2023 10:24:44)

### Operating system/version

Linux 6.1.0-27-amd64, Debian 12

### Terminal name/version

alacritty 0.14.0 (22a44757)

### $TERM environment variable

screen-256color

### Installation

build from repo

**Comment by clason** [comment]
`:lua vim.treesitter.stop()` (`syntax` _is_ off, by default, for Lua files)

**Comment by rwbaskette** [comment]
```
printf '#include<stdio.h>\n\nvoid main() {\n\tprintf("hello\\n");\n }' > ./hello.c; nvim --clean ./hello.c
```

produces:
![Image](https://github.com/user-attachments/assets/d0c0c7d8-a35d-44bf-8d7d-fc2493dfcfd0)

Some literals and strings are green. I can't turn this off in v0.10.2 with `:syntax off` as I can in v0.9.2:

![Image](https://github.com/user-attachments/assets/a6628d86-8b60-4db8-8ebd-88debb5b30b6)

I'm not sure that this is related to treesitter as the treesitter command given has no effect.

Not that I want to lose theLSP for completion and definitions, I just don't want any syntax highlighting

**Comment by zeertzjq** [comment]
`:h lsp-semantic_tolens`

**Comment by rwbaskette** [comment]
Thank you for being responsive. I really appreciate it
