### ISSUE TITLE
Neovim segfaults intermittently when using fzf

### ISSUE THREAD

**Issue by jez** [neovim/neovim#3121]
I haven't yet been able to pin down strict circumstances in which this happens, but intermittently when using the [Vim fzf plugin][1] in Neovim, it segfaults. I'll see if I can't reproduce it more consistently. Has anyone else had this issue?

[1]: https://github.com/junegunn/fzf

**Comment by justinmk** [comment]
known issue, thanks though. https://github.com/neovim/neovim/pull/3029

**Comment by gabrielflorit** [comment]
@justinmk I'm also seeing this issue, running master nvim. What information can I provide to help you? Is there a wiki entry on what logs to report when seeing a runtime crash?

**Comment by justinmk** [comment]
@gabrielflorit https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md

**Comment by justinmk** [comment]
I guess that doesn't actually mention specifics about that. See here for how to get a backtrace:

https://github.com/neovim/neovim/wiki/Development-tips#debugging

**Comment by tarruda** [comment]
Can you all test if this still happens on master?

**Comment by jez** [comment]
I was never able to reliably reproduce it, but I've upgraded to the newest master and I'll let you know if I see it again.
