### ISSUE TITLE
Incorrect indentation after zsh continuation line

### ISSUE THREAD

**Issue by zhengpd** [neovim/neovim#31218]
### Problem

With `nvim -u NORC`, the following zsh code (expected indentation)

```
function test() {                           
  echo 1 \                                  
    && echo 2                               
}                                           
echo 3
```

would be reindented to (unexpected indentation)

```
function test() {                           
  echo 1 \                                  
    && echo 2                               
  }                                         
  echo 3 
```

and with `nvim --clean`, it would be

```
function test() {                           
        echo 1 \                                                                        
                && echo 2                                                               
}                                           
echo 3 
```

### Steps to reproduce

`nvim -u NORC test.zsh # paste and indent above code`

### Expected behavior

Correct bracket `{` indentation after continuation line.

### Nvim version (nvim -v)

v0.10.2

### Vim (not Nvim) behaves the same?

yes, vim 9.0

### Operating system/version

macOS 15.1

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
This should be reported to https://github.com/chrisbra/vim-zsh
