### ISSUE TITLE
E117: Unknown function: `isabsolutepath` - Windows specific

### ISSUE THREAD

**Issue by scottmckendry** [neovim/neovim#31213]
### Problem

The vim function `isabsolutepath` is missing in windows.

### Steps to reproduce

Run `:echo isabsolutepath('C:\Windows')` on the latest stable release for windows.

### Expected behavior

Should return `1`.

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

cannot reproduce on vim 9.1.821

### Operating system/version

Windows 11

### Terminal name/version

wezterm latest stable

### $TERM environment variable

xterm-256color

### Installation

winget

**Comment by zeertzjq** [comment]
It is only available in nightly version

**Comment by brianhuster** [comment]
So can you add it to `:h news` for 0.11?

**Comment by zeertzjq** [comment]
I don't know where to put it

**Comment by justinmk** [comment]
We aren't going to list every vim patch in `:help news`. We communicate the current Vim version by the `v:version`  global. We currently support 8.1 fully, and that will get bumped when we fully support 8.2, and so on.

**Comment by brianhuster** [comment]
What about `VIMSCRIPT` section in `:h news-features`?
