### ISSUE TITLE
Activate mouse support on key modifier

### ISSUE THREAD

**Issue by ElSamhaa** [neovim/neovim#31227]
### Problem

Hello, thanks for the great work.

I understand that mouse events are supported by Neovim. Although I prefer to keep it out of my way by setting `mouse=`, I'm faced with many instances where I needed a quick momentary mouse activation.

### Expected behavior

I suggest using the same shift key modifier to temporarily disable the mouse events capture.

**Comment by justinmk** [comment]
You can enter the cmdline to disable mouse events temporarily. This is explained at `:help default-mouse`.

Using "shift" or whatever is nice but requires terminal support. That is tracked in other issues.

**Comment by ElSamhaa** [comment]
Thanks @justinmk for your quick reply. I understand cmdline is always an option, but some cases are not worth than a single keypress 🙂 

I can't find a relevant open issue enabling this feature. My understanding is that mouse events with or without the shift modifier are correctly forwarded from the terminal to Neovim. I can tell because that is how the inverse is behaving; i.e the momentary deactivation of mouse event captures using the shift key.
