### ISSUE TITLE
Problematic syntax ftplugin files for folding

### ISSUE THREAD

**Issue by avidseeker** [neovim/neovim#31233]
### Problem

`g:javaScript_fold`, `g:php_folding`, and possibly other ftplugin syntax files override folding options.

### Steps to reproduce

init.lua:
```lua
-- vim.g.markdown_fold = 1      -- :set fdm returns manual
-- vim.g.javaScript_fold = 1    -- :set fdm returns syntax
-- vim.g.php_folding = 1        -- :set fdm returns syntax
```

Uncomment the file line by line, then run `nvim -u init.lua`, and check for
`fdm` value.

This doesn't happen in Vim 9.1. Try

```
"let g:markdown_fold = 1
"let g:javaScript_fold = 1
"let g:php_folding = 1
```

### Expected behavior

fdm is default (manual or as set in nvimrc)

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no, vim 9.1

### Operating system/version

unix

### Terminal name/version

xterm

### $TERM environment variable

xterm-256

### Installation

pacman

**Comment by zeertzjq** [comment]
The steps the reproduce don't look right:
- `g:markdown_fold` isn't a thing. There is only `g:markdown_folding`.
- What file did you edit?

**Comment by justinmk** [comment]
Test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by avidseeker** [comment]
>     * `g:markdown_fold` isn't a thing

Typo. I only gave markdown as an example of a filetype plugin that works as expected. In fact, all the following work as expected:

```lua
vim.g.markdown_folding = 1
vim.g.perl_fold = 1
vim.g.r_syntax_folding = 1
vim.g.rst_fold_enabled = 1
vim.g.ruby_fold = 1
vim.g.rust_recommended_style = 0
vim.g.sh_fold_enabled = 1
vim.g.sh_fold_enabled = 3
vim.g.tex_fold_enabled = 1
vim.g.xml_syntax_folding = 1
vim.g.zsh_fold_enable = 1
```

It's only when I add these lines to my init.lua that the issue comes up:

```lua
-- vim.g.javaScript_fold = 1
-- vim.g.php_folding = 1
```

I found this issue by trying to debug why rst plugin not working: see https://github.com/marshallward/vim-restructuredtext/issues/75

>     * What file did you edit?

What do you mean? the config file? `init.lua` for nvim and `vimrc` for vim. I can't seem to replicate this issue in Vim, though.

**Comment by clason** [comment]
We need concrete, reproducible steps including a minimal(!) config we can test with `nvim --clean -u test.lua`.

**Comment by clason** [comment]
The crux of the matter is that we use the exact same runtime files as Vim. So if it works there but not here, something very weird is going on (usually involving treesitter, which makes it a config issue).

**Comment by avidseeker** [comment]
Here's another list of steps

mwe.rst:
```rst
================
Document Heading
================

Heading
=======

Sub-heading
-----------

Paragraphs are separated 
by a blank line.
```

and `nvim --clean -u init.lua +'set fdm' mwe.rst` where `init.lua` is

```lua
vim.g.rst_fold_enabled = 1     
vim.g.markdown_folding = 1      -- :set fdm returns manual
```

So far everything works as expected. rst file has proper folding. Now any of the lines
```lua
vim.g.javaScript_fold = 1    -- :set fdm returns syntax
vim.g.php_folding = 1        -- :set fdm returns syntax
```

and rst folding no longer works.

**Comment by zeertzjq** [comment]
This is a problem with the interaction between individual runtime files. It should be reported to Vim. In Vim it can be reproduced with:
```vim
set nocompatible
let g:rst_fold_enabled = 1
let g:javaScript_fold = 1
filetype plugin on
syntax on
```
