### ISSUE TITLE
The event passed from the TermClose event to the Lua callback function doesn't contain a status key with the process exit code

### ISSUE THREAD

**Issue by melopilosyan** [neovim/neovim#31232]
### Problem

The status(process exit code) is available when calling `nvim_create_autocmd` with vim script as a `command` option. But it's not included in the `event` parameter of the Lua callback function.

### Steps to reproduce

Create a shell script.
```sh
echo -e "echo exiting now\nexit 1" > exit.sh
```

nvim --clean
:= vim.api.nvim_create_autocmd("TermClose", { once = true, command = "echo v:event" })
:terminal sh exit.sh

Note the message "{'status': 1}"

:= vim.api.nvim_create_autocmd("TermClose", { once = true, callback = function(ev) print(vim.inspect(ev)) end })
:terminal sh exit.sh
:messages

Note the table doesn't contain a `status` key.

### Expected behavior

The `event` passed to the Lua callback function should also carry a `status` key with the process exit code.

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Ubuntu 24.04.1

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

Extracted from release binary nvim-linux64.tar.gz

**Comment by zeertzjq** [comment]
No, it's included in `vim.v.event`

**Comment by melopilosyan** [comment]
I see. Appreciate the quick response, @zeertzjq
