### ISSUE TITLE
neovim on dragonflybsd

### ISSUE THREAD

**Issue by bratslavia** [neovim/neovim#3124]
I have been trying to install neovim under dragonflybsd, and appear to have run into (not surprisingly) some of the same issues open/net BSD users have hit, specifically issues https://github.com/neovim/neovim/issues/2445 and https://github.com/neovim/neovim/issues/3107. Just for reference, I also had to apply the [local.mk fix for jemalloc](https://github.com/neovim/neovim/wiki/Building-Neovim#openbsd--current) on openbsd.

I was also getting errors when building msgpack. It appeared to be this error (https://github.com/msgpack/msgpack-c/issues/176), and adding the appropriate !defined (per https://github.com/msgpack/msgpack-c/issues/296) to sysdep.h seemed to fix it.

**Comment by justinmk** [comment]
Since you mentioned #2445, I created https://github.com/neovim/lua-client/pull/14 which may help.

The dragonflybsd project looks really cool :)

**Comment by Pyrohh** [comment]
Since https://github.com/neovim/lua-client/pull/14 was merged a while ago the build should at least be able to proceed, so closing this.
