### ISSUE TITLE
ui-messages: add kind for search pattern messages

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#31244]
### Problem

I am reporting this issue on`:help ui-messages` suggestion, but in practice I found that empty `kind` can cause problems with distinguishing message types. #31205 significantly reduces the issue for me, but it would be good to have named kind for such messages. I don't know how many other cases we'll get an empty kind.

`empty-kind.lua`:
```lua
local api = vim.api
local ns = api.nvim_create_namespace('messageRedirection')

local function log(msg)
  vim.schedule(function ()
    api.nvim_buf_set_lines(1, -1, -1, true, vim.split(msg, '\n'))
    vim.cmd.normal 'G'
  end)
end

api.nvim_create_autocmd('CmdlineEnter', {
  callback = function ()
    vim.ui_detach(ns)
    vim.schedule(function ()
      api.nvim__redraw({statusline = true})
    end)
  end
})

api.nvim_create_autocmd({'UIEnter', 'CmdlineLeave'}, {
  callback = function ()
    vim.ui_attach(ns, {ext_messages = true, ext_cmdline = false}, function (event, kind, content, _)
      if event == 'msg_show' and kind == '' then
        log(vim.inspect(content))
      end
    end)
  end
})
```
- `nvim --clean -u empty-kind.lua empty-kind.lua`
- press `n` and see appended lines

Related to https://github.com/neovim/neovim/issues/27811

@luukvbaal maybe in the wave of your other UI fixes it will be easier to find?

### Expected behavior

Not empty kind for such messages

**Comment by justinmk** [comment]
Makse sense. We have a message kind for `search_count` but not the search pattern.

**Comment by przepompownia** [comment]
Regardless I think about encouraging someone on the Vim side to add an option to silent such messages. Someone please correct me if I missed that option.
