### ISSUE TITLE
Treesitter error on hover: "Attempt to index field '_valid' (a boolean value)"

### ISSUE THREAD

**Issue by MariaSolOs** [neovim/neovim#31246]
### Problem

I'm seeing the following error happen on `master` when using LSP hover:

![Image](https://github.com/user-attachments/assets/43f79f37-1334-47b7-96e6-3365cc76fa5d)

### Steps to reproduce

Using nightly open a Lua file with LuaLS installed. Over any function call invoke LSP hover using the default "K" mapping.

### Expected behavior

No errors on hover.

### Nvim version (nvim -v)

v0.11.0-dev-1184+gcc6992f1ca

### Vim (not Nvim) behaves the same?

No

### Operating system/version

macOS 15.0.1

### Terminal name/version

ghostty

### $TERM environment variable

xterm-ghostty

### Installation

From source

**Comment by MariaSolOs** [comment]
I've bisected the issue to https://github.com/neovim/neovim/commit/235cb5bc5f2553f5a46807267b8705e53f7a14af cc @luukvbaal

**Comment by luukvbaal** [comment]
That commit was driven by designing a redraw API that makes sense in regards to updating the screen/flushing the UI. I am not familiar enough with treesitter to tell if our highlighter's needs differ from that. I have tried to establish that multiple times before in https://github.com/neovim/neovim/pull/28101#issuecomment-2091057965 and https://github.com/neovim/neovim/issues/30696#issuecomment-2452887985 (but got no response).

Haven't been able to reproduce so some steps seem to be missing. Presumably `flush = false` will avoid the error again but in that case `nvim__redraw` shouldn't call `ui_flush()` either. But I suppose this boolean index can also be resolved while keeping the flush, I'm still not sure what would be preferred.

**Comment by MariaSolOs** [comment]
I will add a minimal configuration later today. Based on the error I imagine it requires LSP, Treesitter and `vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'` set.

**Comment by RayGuo-ergou** [comment]
I am seeing the same error with a plugin `nvim-ts-autotag`, here's the line that triggers it: https://github.com/windwp/nvim-ts-autotag/blob/main/lua/nvim-ts-autotag/internal.lua#L250

**Comment by clason** [comment]
> That commit was driven by designing a redraw API that makes sense in regards to updating the screen/flushing the UI. I am not familiar enough with treesitter to tell if our highlighter's needs differ from that. I have tried to establish that multiple times before in [#28101 (comment)](https://github.com/neovim/neovim/pull/28101#issuecomment-2091057965) and [#30696 (comment)](https://github.com/neovim/neovim/issues/30696#issuecomment-2452887985) (but got no response).

By all accounts, it's not the highlighter but other treesitter plugins for which that change was breaking. (The foldexpr is required to reproduce this; I can't reproduce the error with just treesitter highlighting.)

**Comment by folke** [comment]
Haven't looked into the details yet, but just wanted to report some of the things I noticed:
- multi-line completions (using copilot) trigger this issue for me. Single line works fine.
- something seems off with indentation in nightly, which may (or may not) be related
