### ISSUE TITLE
Unable to disable Ctrl-j in Insert Mode in Neovim

### ISSUE THREAD

**Issue by lostlang** [neovim/neovim#31255]
### Problem

I am trying to disable or remap the Ctrl-j key combination in Insert Mode in Neovim, but my attempts are unsuccessful.

### Steps to reproduce

```
vim.keymap.set('i', '<C-j>', '', { noremap = true, silent = true })
```

### Expected behavior

disable `<C-j>` in insert mode

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

VIM - Vi IMproved 9.1 

### Operating system/version

Arch Linux on Windows 10 x86_64

### Terminal name/version

windows terminal

### $TERM environment variable

-

### Installation

pacman

**Comment by justinmk** [comment]
does it happen with `nvim --clean`?

if your terminal doesn't support extended keys, likely you have some other mapping to `<NL>`, which is a synonym for ctrl-j
