### ISSUE TITLE
Copilot is broken with recent changes to `get_language_id`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#31262]
### Problem

Copilot no longer works after: https://github.com/neovim/neovim/commit/989a37a594649528f28432388c0e7e28e8be2753

```lua
Error executing vim.schedule lua callback: .../.local/share/nvim/lazy/copilot.lua/lua/copilot/util.lua:143: bad argument #1 to 'gsub' (string expected, got nil)
stack traceback:
	[C]: in function 'gsub'
	.../.local/share/nvim/lazy/copilot.lua/lua/copilot/util.lua:143: in function 'get_language_id'
	...re/bob/nightly/share/nvim/runtime/lua/vim/lsp/client.lua:1030: in function '_text_document_did_open_handler'
	...re/bob/nightly/share/nvim/runtime/lua/vim/lsp/client.lua:1049: in function '_on_attach'
	...cal/share/bob/nightly/share/nvim/runtime/lua/vim/lsp.lua:665: in function 'buf_attach_client'
	...cal/share/bob/nightly/share/nvim/runtime/lua/vim/lsp.lua:272: in function 'lsp_start'
	...local/share/nvim/lazy/copilot.lua/lua/copilot/client.lua:100: in function 'buf_attach'
	...local/share/nvim/lazy/copilot.lua/lua/copilot/client.lua:254: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

install copilot.lua

### Expected behavior

no error

### Nvim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

nope

### Operating system/version

linux

### Terminal name/version

ghostty

### $TERM environment variable

ghostty

### Installation

bob

**Comment by clason** [comment]
good 😈

**Comment by folke** [comment]
I'm not sure if this is a bug or not.
Previously, the buffer filetype was always passed to `get_language_id`.
With the recent changes, this can now be `nil`.

I've created a PR to fix this on the copilot side, but not sure what the intention is here.

@lewis6991?

**Comment by lewis6991** [comment]
Thanks. Didn't see get_language_id was called there. I'll look into it. The main intention was to simplify the code but I must have made a mistake.

**Comment by lewis6991** [comment]
So one change I made was:

```diff
@@ -342,4 +343,4 @@
---- @param _bufnr integer
---- @param filetype string
-local function default_get_language_id(_bufnr, filetype)
-  return filetype
+--- @param bufnr integer
+--- @param filetype? string
+local function default_get_language_id(bufnr, filetype)
+  return filetype or vim.bo[bufnr].filetype
```

So the bufnr can be passed to get the filetype. Which I think is harmless.

I think the main problem could be from:

![Image](https://github.com/user-attachments/assets/98e6802e-d047-4f85-8aff-2356a73fa5bd)

Which changes the filetype resolution to happen within the notification handler. If the current buffer changes, then this could cause a problem. However, `vim.bo.filetype` should always return a string and never `nil`, which suggests something else is going on.

**Comment by folke** [comment]
ok, great. Thanks!
