### ISSUE TITLE
Add a way to use names for keybinds

### ISSUE THREAD

**Issue by Silverdev2482** [neovim/neovim#31260]
### Problem

When rebinding things the actions you are binding are often confusing, take for example my movement bindings on colemak-dh:
```
vim.keymap.set({'n', 'x', 'o' }, 'n', 'h' )
vim.keymap.set({'n', 'x', 'o' }, 'e', 'j' )
vim.keymap.set({'n', 'x', 'o' }, 'i', 'k' )
vim.keymap.set({'n', 'x', 'o' }, 'o', 'l' )
```
If you don't move with HJKL, but NEIO, what NEIO is bound to makes no scene. If you are rebinding them the default keybind should not be used to describe what is being bound, as you likely aren't using it.

### Expected behavior

I think there should be a way to bind to an action and not a key. Helix has a system somewhat like this. My config with a system like this could look like this:
```
vim.keymap.set({'n', 'x', 'o' }, 'n', 'move_cursor_left' )
vim.keymap.set({'n', 'x', 'o' }, 'e', 'move_cursor_down' )
vim.keymap.set({'n', 'x', 'o' }, 'i', 'move_cursor_up' )
vim.keymap.set({'n', 'x', 'o' }, 'o', 'move_cursor_right' )
```

**Comment by mike325** [comment]
you can always use the option `desc` to add a binding description
```
vim.keymap.set({'n', 'x', 'o' }, 'n', 'h', { desc = 'move_cursor_left' } )
vim.keymap.set({'n', 'x', 'o' }, 'e', 'j', { desc = 'move_cursor_down' } )
vim.keymap.set({'n', 'x', 'o' }, 'i', 'k', { desc = 'move_cursor_up' } )
vim.keymap.set({'n', 'x', 'o' }, 'o', 'l', { desc = 'move_cursor_right' } )
```

It's not the same thing but it gives you an actual description of what the binding it's doing/suppose to do

**Comment by Silverdev2482** [comment]
I have simply been leave a comment after the line to describe the action.

**Comment by clason** [comment]
You can absolutely do that:
```lua
local function do_this_thing()
  ...
end
vim.keymap.set({'n', 'x', 'o' }, 'n', do_this_thing)
```

**Comment by Silverdev2482** [comment]
That works well but it would be nice for me to not define stuff, would it be possible for me to make a plugin with definitions and upstream it?
