### ISSUE TITLE
Drop exrc file support

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3126]
Sub thread of #3120 

Should we keep sourcing .exrc? I couldn't find something that can be done in exrc and not vimrc. The removal involves:
 - remove support for $EXINIT
 - remove the sourcing of all exrc files

**Comment by Pyrohh** [comment]
Assuming we still support ex mode, then I don't think it should be removed for the sake of completeness... that is, unless we're going to remove ex mode imminently :-)

**Comment by justinmk** [comment]
It's not related to ex mode. It's the name for vi's rc file.

**Comment by justinmk** [comment]
Pretty sure I answered this in the other thread.
