### ISSUE TITLE
'rulerformat' does not support "%!" item

### ISSUE THREAD

**Issue by yatinlala** [neovim/neovim#31278]
### Problem

`:h 'rulerformat'` states that 

> The format of this option is like that of 'statusline'.

However,  `:set rulerformat=%!toupper('foo')` returns `E539: Illegal character <!>: rulerformat=%!toupper('foo')`, while `:set statusline=%!toupper('foo')` works as expected.

It seems to me that either 
**(a)**: %! should work (my preferred solution), or
**(b)** docs should be updated to reflect the difference. 

If **(a)** is the way forward, I'm happy to try to patch.

Apologies if I'm missing something obvious here, I've tried to double-check everything but am new to the project 🙏

### Steps to reproduce

nvim --clean
:set rulerformat=%!toupper('foo')

### Expected behavior

ruler is set to `FOO`

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

yes, vim 9.1.697

### Operating system/version

ArchLinux

### Terminal name/version

kitty 0.37.0

### $TERM environment variable

xterm-kitty

### Installation

System Package Manager

**Comment by zeertzjq** [comment]
It's not clear what should be changed here. I think it should be reported to Vim.

**Comment by yatinlala** [comment]
Vim has merged https://github.com/vim/vim/pull/16118
