### ISSUE TITLE
`zz` shifts cursor if line has concealed text

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#31271]
### Problem

`zz` shifts the cursor to the right, as many times as the number of concealed characters before it.

If you press `zz` in the following line in a vim help text (and the cursor is on e.g. the "h" in "highlights")

```
Treesitter uses |nvim_buf_set_extmark()| to set highlights with a default
```

the cursor will shift to the right twice.

### Steps to reproduce

nvim --clean runtime/doc/treesitter.txt -c ':496' -c 'normal 50l'
`zz`

### Expected behavior

Cursor should not change columns

### Nvim version (nvim -v)

081beb3659

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug  3 2024 14:50:46) macOS version - arm64 Included patches: 1-2136, 2142

### Operating system/version

macos

### Terminal name/version

kitty

### $TERM environment variable

screen-256color

### Installation

built manually

**Comment by clason** [comment]
> no, VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Aug 3 2024 14:50:46) macOS version - arm64 Included patches: 1-2136, 2142

Can you try the latest version (>9.1.850)?

**Comment by luukvbaal** [comment]
Same issue is present with "zt" and "zb", and doesn't seem to be present in Vim because it has special logic in main.c for redrawing the cursorline. Adding `wp->w_valid &= ~VALID_VIRTCOL` to `scroll_cursor_top/bot/halfway` fixes the issue.

**Comment by dundargoc** [comment]
Bisected to 595c1a724af9fe93d4ff1df7d5c47e4c9c31a7a6

**Comment by zeertzjq** [comment]
I think this can be simply fixed by:
```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index 6324466dcc..6a02584454 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -158,17 +158,13 @@ static void redraw_for_cursorline(win_T *wp)
 static void redraw_for_cursorcolumn(win_T *wp)
   FUNC_ATTR_NONNULL_ALL
 {
-  if (wp->w_valid & VALID_VIRTCOL) {
-    return;
-  }
-
   // If the cursor moves horizontally when 'concealcursor' is active, then the
   // current line needs to be redrawn to calculate the correct cursor position.
   if (wp->w_p_cole > 0 && conceal_cursor_line(wp)) {
     redrawWinline(wp, wp->w_cursor.lnum);
   }
 
-  if (pum_visible()) {
+  if ((wp->w_valid & VALID_VIRTCOL) || pum_visible()) {
     return;
   }
 
```
