### ISSUE TITLE
TUI: `<C-/>`, `<C-F5>` keys not recognized in tmux/screen

### ISSUE THREAD

**Issue by TRPB** [neovim/neovim#31282]
### Problem

Related: 

- https://github.com/tmux/tmux/issues/4249
- https://www.reddit.com/r/tmux/comments/1gtj6o6/tmux_not_sending_ctrl_commands_to_nvim/

Some Ctrl+ key combinations do not work when running nvim in a multiplexer. The same combination in the same terminal, nvim config and shell work perfectly when not running inside a multiplexer.

I had thought this was a tmux issue but it's 100% reproducible in any combination of:

- zellij, tmux, screen
- zsh, bash, fish
- wezterm, alacritty, kitty

the only common denominator here is nvim, it's mostly likely a nvim issue.

It's not because those multiplexers are already using the key with a clean tmux config `<C-F6>` and `<C-/>` are  not used but do not register in nvim

I have verified this because if I run `emacs -nw` inside tmux and press `Ctrl+/`, `Ctrl-F6` etc it shows "Ctrl-F6 is undefined". I have no idea how to bind it to anything inside emacs but the error appearing verifies that the keypress is being sent to emacs correctly while inside tmux: tmux is not blocking the keypress, it is nvim specific and nvim is not registering the keypress but emacs is.

Several combinations are affected but the ones I've tried myself are `<C-F6>` and `<C-/>`. It's not all `<C-` bindings, any that resolve to a single character instead of a sequence input seem to work as intended. 

If I:

```
tmux
nvim --clean
:term 
> cat
<C-/>
```

the character sequence appears in the terminal exactly the same as when I don't use `tmux`

### Steps to reproduce

```
tmux 
nvim --clean
:nmap <C-/>  <CMD>:term<CR>
```
Press `<C-/>`

### Expected behavior

Terminal should open but nothing happens

It works as intended without starting nvim in tmux first.

### Nvim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

Yes - vim 9.1.719

### Operating system/version

Fedora 39

### Terminal name/version

Kitty 0.37.0

### $TERM environment variable

tmux-256color (tmux), xterm-kitty (zellij), xterm-kitty (outside of tmux where it works as intended)

### Installation

nixvim

**Comment by justinmk** [comment]
> if I run `emacs -nw` inside tmux and press `Ctrl+/`, `Ctrl-F6` etc it shows "Ctrl-F6 is undefined"

in insert-mode if I do `<c-v><c-/>` and `<c-v><c-F5>` I see:

- no tmux
    ```
    <C-/>
    <F29>
    ```
- in tmux
    ```
    ^_
    <S-F5>
    ```

same for you?

**Comment by whoop-t** [comment]
@justinmk You can see the testing here: https://github.com/tmux/tmux/issues/4249#issuecomment-2481982943

Video testing some other ctrl + combos

**Comment by zeertzjq** [comment]
It seems that tmux can only interpret modifyOtherKeys, not kitty keyboard protocol, so extended keys (including `<C-/>`, `<C-.>`, etc.) do not work in terminals that only support kitty keyboard protocol (e.g. kitty, Alacritty), while they do work in terminals that support modifyOtherKeys (e.g. WezTerm, XTerm).

The problem with `<C-F6>` is a duplicate of #8317.

Therefore there is nothing new here.

**Comment by cippaciong** [comment]
Apologies for reviving an old discussion, but in case anyone stumbles upon this issue while troubleshooting like me: there is an open PR to add Kitty keyboard protocol support to tmux. It hasn't been merged yet at the time of writing, but it's being actively reviewed and tested. https://github.com/tmux/tmux/pull/4912
