### ISSUE TITLE
New :LspInfo status page is very hard to read

### ISSUE THREAD

**Issue by sungkang** [neovim/neovim#31291]
### Problem

When there are many active configs on a buffer, the list is a bit too compressed to easily read it.

### Expected behavior

Maybe some minor tweaks to the visuals for better readability.

**Comment by clason** [comment]
> Maybe some minor tweaks to the visuals for better readability.

If you have _concrete_ suggestions, these would be welcome (and a PR even more so).

**Comment by sungkang** [comment]
sure, I'll provide a PR. Thanks!

**Comment by glepnir** [comment]
Maybe a bit too compact and lacks some formatting tweaks.  Are you going to do something on health module or lspinfo? If lspinfo we can move issue to lspconfig

**Comment by justinmk** [comment]
Nothing actionable here.
