### ISSUE TITLE
Using `n` after histadd() appears broken for me on 0.10.2

### ISSUE THREAD

**Issue by srcrip** [neovim/neovim#31290]
### Problem

When using `histadd()` to add a search, although the pattern is added like you'd expect, you cannot hit `n` to go to it. Instead when you hit `n` it acts like that pattern isn't even there. I've confirmed this behavior is happening with no plugins installed at all.

### Steps to reproduce

- search for something like `/foo`
- exit search, and run `:lua vim.fn.histadd("search", "bar")`
- hit `n`

### Expected behavior

You should go to the next instance of 'bar', but instead you go to the next instance of 'foo'.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

MacOS 15

### Terminal name/version

Warp

### $TERM environment variable

xterm-256color

### Installation

Brew

**Comment by justinmk** [comment]
Try the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by srcrip** [comment]
I have been informed that this is actually the normal behavior. `n` goes off of searchpattern register, and popping an item to the top of the search history does not automatically set that register.

However, I would like to leave this open and propose that `histadd` should be given a flag which *does* set the searchpattern as well. it does make sense that these things are stored two different ways, but I think most people using `histadd` would expect the behavior I'm describing.

**Comment by justinmk** [comment]
> propose that `histadd` should be given a flag which _does_ set the searchpattern as well

Request that at https://github.com/vim/vim . Not going to spend time on this here.
