### ISSUE TITLE
scroll buffer while in cmdline

### ISSUE THREAD

**Issue by jukuisma** [neovim/neovim#31309]
### Problem

None of the options listed in `:h scrolling` seem to work when writing ex commands. Some option for scrolling would be especially helpful for previewing `:%s/<regex>` matches.

### Expected behavior

Take:

![Image](https://github.com/user-attachments/assets/a40bce05-4dda-46f4-a93b-83bddadc1275)

Any option to scroll the screen and/or jump to the next match without stopping writing the ex command would be much appreciated. :)

**Comment by jakubbortlik** [comment]
> jump to the next match without stopping writing the ex command

I believe this is achieved by `CTRL-G` and `CTRL-T`, see `: c_CTRL-G`.

**Comment by jukuisma** [comment]
> I believe this is achieved by CTRL-G and CTRL-T, see : c_CTRL-G.

Works just as advertised, thanks! I try my best to avoid using github issues as a help forum, but didn't find this info anywhere.
