### ISSUE TITLE
`inputlist()` doesn't work well with `ext_messages`

### ISSUE THREAD

**Issue by folke** [neovim/neovim#31314]
### Problem

Since #27874, prevents `msg_show` events to be processed realtime, it's no longer possible to show the messages written by `inputlist()`.

The message can only be shown **after** entering something, which makes `inputlist()` useless.

`inputlist()` is used as the default backend for `vim.ui.select`, used by things like code actions.

### Steps to reproduce

* use `ui_attach`
* call `inputlist()`

### Expected behavior

right before `inputlist()` blocks for input, it should be possible for ui consumers to update the ui

### Nvim version (nvim -v)

nightly

### Vim (not Nvim) behaves the same?

no

### Operating system/version

arch

### Terminal name/version

ghostty

### $TERM environment variable

ghostty

### Installation

bob

**Comment by luukvbaal** [comment]
I think `input_list()` is followed by `number_prompt`, whose message event is executed in non-fast context. So while not straight forward, it should be possible to display the `input_list()` message there. I think ideally this should be sent as a single message event though.

**Comment by folke** [comment]
Where do I get that `number_prompt` event? I don't see this is part of `ext_messages` or `ext_cmdline`?

**Comment by folke** [comment]
I get the `inputlist` data as a `msg_show` with and empty kind.

**Comment by folke** [comment]
Here I log everything I receive from `ui_attach` to a log file:

![Image](https://github.com/user-attachments/assets/a949ed63-0cc6-4c2a-b0e6-80d294b63b7e)

**Comment by luukvbaal** [comment]
It was added in https://github.com/neovim/neovim/pull/31279

**Comment by folke** [comment]
Damn, I totally missed that :)
Will update Noice with the changes. Thanks!

**Comment by folke** [comment]
All working great now in Noice!
