### ISSUE TITLE
Add support for highlighting string delimiter for treesitter rules

### ISSUE THREAD

**Issue by bk2204** [neovim/neovim#31315]
### Problem

Many of the traditional Vim syntax highlighting rules end up with patterns matching string delimiters (that is, usually quotation marks).  For instance, Ruby and Rust provide these patterns.

Several colour schemes, including the well-known ir_black and a custom one based off of it that I use, highlight string delimiters differently than the string itself.  For instance, I use a slightly darker shade of green for the delimiters, which helps de-emphasize the delimiters.

The new treesitter rules don't appear to have that distinction, so it's not possible in the general case to colour the delimiters differently anymore.

### Expected behavior

I'd like the ability to do that in the future, though, since I think the treesitter rules are likely to be more useful in future releases.  My recommendation is that, by default, they're coloured as String, and then they can be overridden in a particular scheme if desired.

This will bring feature parity with the older Vim-style rules for many languages and will improve highlighting for other languages where this is not currently possible.

**Comment by clason** [comment]
Sorry, but that's not how it works. Grammars need to expose these entities, then queries can capture them. So you need to open an issue (or, better yet, PR) at the individual grammar repos. (Similarly how changes to the legacy syntax files need to go through the individual maintainers).

**Comment by lewis6991** [comment]
Alternatively you can define a query for the general string and add a predicate to check the beginning text, e.g. if it's `"` or `'`.
