### ISSUE TITLE
Check if a terminal has a running command

### ISSUE THREAD

**Issue by ilan-schemoul** [neovim/neovim#31313]
### Problem

I have keymap to open a terminal.

It is extremely annoying to have a new terminal everytime I use my keymap because then I have 20 different terminals and I can never find the terminal I search for when I need it.

It is useless to open any terminal because then I can open a terminal with a long running command (like node or gcc) and I cannot do anything with it

### Expected behavior

A way, anything, to know if a terminal buffer is running a command or not (I want to know if I'm inside bash/fish and its available for a command. Or if the terminal run something like sleep 100/node and so I cannot do anything with the terminal at all)

**Comment by justinmk** [comment]
Every :terminal has a job-id in the `&channel` read-only option. You can inspect the job's process tree like this:

```
:echo nvim_get_proc_children(jobpid(&channel))
:echo nvim_get_proc(jobpid(&channel))
```

**Comment by ilan-schemoul** [comment]
Alrighty [this](https://github.com/ilan-schemoul/nvim-config/commit/4e27ebabe9d4e819007c770800bac4d5903b8a8d) works much better than my previous [hack](https://github.com/ilan-schemoul/nvim-config/commit/4e27ebabe9d4e819007c770800bac4d5903b8a8d#diff-9454fd7f97bfd3dcf69804b86f0fb5c9ab8c9dde7c9e8d8a668631c98a8ed95aL138) (checking if the name of the terminal is a valid folder name because fish usually sets the title to the current directory when you don't run a command).
Thanks a lot I couldn't find anything affter many hours of googling 👍 
Keep up the great work
