### ISSUE TITLE
Indexing invalid lsp floating window on cursor move

### ISSUE THREAD

**Issue by Bekaboo** [neovim/neovim#31325]
### Problem

If the lsp hover/floating window is closed by user, moving the cursor afterward will make nvim index `vim.w` with the invalid hover window id, hence the error.

### Steps to reproduce

The bug can be reproduced by opening a file and attaching a lsp client that supports hover method, open the hover window, closing the hover window manually, then move the cursor. The following reproduce steps use `bash-language-server` as an example.

1. Install `bash-language-server`
2. `echo "echo 'a'" > test.sh`
3. `nvim --clean test.sh`
4. `:lua vim.lsp.start({ cmd = { 'bash-language-server', 'start' } })`
5. Put the cursor on the "echo" in `test.sh`
6. Press `K` to open the lsp hover window
7. Close the hover window by `:lua for _, win in ipairs(vim.api.nvim_list_wins()) do if vim.fn.win_gettype(win) == 'popup' then vim.api.nvim_win_close(win, {}) end end`
8. Move the cursor and see the error message

### Expected behavior

Should not error if the lsp hover window is already closed

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1219+g46d124a933

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.11.9-arch1-1

### Terminal name/version

alacritty 0.14.0 (22a44757) + tmux 3.5a

### $TERM environment variable

tmux-256color

### Installation

AUR

**Comment by glepnir** [comment]
emm could you try https://github.com/neovim/neovim/pull/31319 ? i guess it also fixed this

**Comment by Bekaboo** [comment]
> emm could you try [#31319](https://github.com/neovim/neovim/pull/31319) ? i guess it also fixed this

Thanks that works
