### ISSUE TITLE
Specify that Neovim doesn't support Vim9script in `:h nvim-from-vim

### ISSUE THREAD

**Issue by brianhuster** [neovim/neovim#31327]
### Problem

Since the release of Vim9 in 2022, the biggest Vim feature that is not (and probably will never be) available in Neovim is Vim9script, not `ttymouse`. So I think it `:h nvim-from-vim` should specify that Nvim doesn't support Vim9script, and suggest users who write vimrc in Vim9script to switch to legacy Vimscript or Lua

I know it has been mentioned in `:h vim_diff`, but I think that file is kinda long, so very likely users will miss it. Also it doesn't have a seperate tag for `vim9script`

### Expected behavior

Just add a few lines to `:h nvim-from-vim` saying something like

```vimdoc

For example, vim9script is not supported, instead Nvim support legacy |Vimscript| and |Lua| as first-class scripting languages. 
If you want to share a |Vimrc| between Nvim and Vim, you should convert it to legacy Vimscript. 
Or if you want to keep Vim9script for Vim9, you can move legacy Vimscript code to a block like this >vim
    if !has('vim9script')
       " legacy script commands go here
       finish
    endif
    vim9script
    # Vim9 script commands go here
<

Or you can maintain seperated Nvim and Vim config, which is more recommended.
```

**Comment by justinmk** [comment]
> I know it has been mentioned in `:h vim_diff`, but I think that file is kinda long,

It's right at the top:

    Nvim differs from Vim in many ways, although editor and Vimscript (not Vim9script)

> Just add a few lines to `:h nvim-from-vim` saying something like

No, that is much too long. `:help nvim` is supposed to be essential, and high-signal, for getting started. Explication is in `:help vim-diff`.

> Also it doesn't have a seperate tag for `vim9script`

I'll add a tag

**Comment by brianhuster** [comment]
From `:h lua-eval`
```
The (dual) equivalent of "vim.eval" for passing Lua values to Nvim is "luaeval".
```
But Neovim doesn't have `vim.eval` in Lua API, but only `nvim_eval` as Nvim API
