### ISSUE TITLE
build: Enable -flto (link-time optimization)

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3136]
I tested by manually setting it in CMakeLists.txt, it compiles without warning. The link phase is much longer, so it should only be enabled on release mode. The resulting binary is 8% smaller \o/.
For the experiment, I add the flag in CMakeLists.txt:113. Where should I put it for release build ?

**Comment by justinmk** [comment]
This hinges on resolution of https://github.com/neovim/neovim/issues/2913 (create `ReleseDev` build).

**Comment by Yamakaky** [comment]
#2913 is closed but no ReleaseDev, should I put thins flag in the Release build ?

**Comment by justinmk** [comment]
Instead of ReleaseDev we have just Dev.

> should I put thins flag in the Release build ?

:+1:

**Comment by mhinz** [comment]
On OSX it results in a 1 Mb smaller binary:

```
4348440	build/bin/nvim
3326216	build/bin/nvim
```

:+1:

**Comment by justinmk** [comment]
> On OSX it results in a 1 Mb smaller binary:

@mhinz  Nice! That's a Release build in both cases?

**Comment by justinmk** [comment]
Reverted #4313 until https://github.com/neovim/neovim/pull/4313#discussion_r53570725 is resolved, to avoid confusion and problems in the meantime.

**Comment by dundargoc** [comment]
Isn't link-time optimization enabled by default nowadays?
