### ISSUE TITLE
defaults: quickfix as builtin diagnostic handler

### ISSUE THREAD

**Issue by yochem** [neovim/neovim#31362]
### Problem

The quickfix list is a very useful builtin feature, especially for showing diagnostics in your workspace / buffer. It however lacks auto-updating of these diagnostics. This is something that new users coming from an IDE (like vscode) might expect, as these IDEs often also have a window with diagnostics below the buffers. It makes the overall experience with using diagnostics in the qflist much better and gives working with diagnostics a more modern feel.

Implementing the qflist as diagnostic handler is fairly trivial thanks to `vim.diagnostic.handler`. However, users might not think to implement this themself. It would be great for discoverability to have this as builtin handler, even when it's turned off as default.

### Expected behavior

I currently use this in my own config:

```lua
vim.diagnostic.handlers["quickfix"] = {
  show = function(_, _, _, _)
    vim.diagnostic.setqflist({ open = false })
  end,

  hide = function(_, _)
    vim.fn.setqflist({}, 'r')
  end
}
```

and that works already quite well.

This solves the problem by creating a diagnostic handler that just sets the qflist with available diagnostics. I think the show function is called on DiagnosticChanged, thus this would update the qflist when the list of diagnostics changes. The cost is minimal, and provides a modern experience for working with diagnostics.

**Comment by justinmk** [comment]
Sounds attractive to me. Waiting for comments / objections.

**Comment by mfussenegger** [comment]
>  The cost is minimal, and provides a modern experience for working with diagnostics.

It does interfere with other functions using the quickfix list. Say you use `lsp.buf.references()` with the intention of going through all of them to change the calls to a different function. You'd jump to the first location, make a change, get new diagnostics and lose the references in the quickfix list.

If this gets added it imho shouldn't be on by default as it would be too invasive and kind of a breaking change.
And if it gets added by default and you've to turn it on - it raises the question why include it if adding it only requires the few lines you posted.

**Comment by yochem** [comment]
Fair. We could also use the loclist for this, although that would probably have the same problem. Another option is to just add this example to the docs. The example given does have some rough edges (pretty much the same as #30868), but works great for people that only want to use the qflist for diagnostics.

**Comment by yochem** [comment]
I've created #31371 for adding this as example in the docs.

**Comment by yochem** [comment]
Thanks for the hostile feedback, lol. no one said it should be done on the main thread. Also, isn't this exactly what the sign, virtual_line and underline handlers do? I don't think `setqflist` is computationally much heavier than setting signs, virtual lines and underlines. A separate diagnostics ui element is indeed a good suggestion, but that has a much higher complexity than this simple addition. I'm aware not everything will use or like this feature, that's why I already suggested it could be opt-in.

I could throw in a `vim.schedule` in the [example docs PR](https://github.com/neovim/neovim/pull/31371) if you prefer that.
