### ISSUE TITLE
Guideline for bit flags

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3140]
I see several ways to do bit flags in the code. Most of the time, it's simply #define for the values and int for the type. I propose this example:

``` c
typedef enum {
    FLAG_A = 1 << 1,
    FLAG_B = 1 << 2,
    FLAG_C = 1 << 3,
} SomeFlags;

SomeFlags flags = FLAG_B | FLAG_C;
SomeFlags fun() {
    return FLAG_A;
}
```

One immediate advantage, in addition to the semantic gain : in gdb, `print flags` outputs `$1 = (FLAG_B | FLAG_C)`, which is pretty neat.
One problem stays : `flags = 123;` works.

What do you think ?

**Comment by ZyX-I** [comment]
Can you point where in C99 specification such behaviour is stated?

Though it looks nicer and I do not see any of the C compilers I have complain for this code. Compilers include pcc-1.1.0-r1, ekopath-6.0.439_p20150707, gcc-4.9.3, tcc-0.9.26-r2, clang-3.6.1-r100. All run with `-pedantic -std=c99 -Wall -Wextra -Wconversion` (except for tcc which was run with `-pedantic -Wall -Wextra -Wconversion -Wunsupported`), actual code:

```C
#include <stdio.h>

typedef enum {
    FLAG_A = 1 << 1,
    FLAG_B = 1 << 2,
    FLAG_C = 1 << 3,
} SomeFlags;

SomeFlags flags = FLAG_B | FLAG_C;
SomeFlags fun(void)
{
    return flags | FLAG_A;
}

int main(void)
{
    printf("%i", fun());
    return 0;
}
```

**Comment by Yamakaky** [comment]
Can you point where in C99 specification such behaviour is stated?

What do you mean ? The gdb stuff ?

I don't see the difference between your code and mine.

I don't think we can design a perfectly typesafe solution, this one looks good enough.

**Comment by ZyX-I** [comment]
@Yamakaky I always thought that enum variable can only take a given set of values (*not* anything else, including bitwise OR of them), but for performance reasons it actually may have any other value (example: if you use uninitialized `bool` value it may appear that for boolean `a` `a != true` and `a != false` at the same time; AFAIR there is a clang sanitizer for catching this kind of problems (not unitialized memory access, but boolean with invalid value)).

Thus I would like to see where specification states that `SomeFlags flags = FLAG_B | FLAG_C;` is valid. I only found that it states that `SomeFlags` should be (compatible with) `char` or some integer type (both signed and unsigned permitted), but not any references that state that this line should be valid or invalid. Maybe key is in the definition of what is meant by “each enumerated type shall be *compatible* with …”. All examples I have found in C99 spec do not use bit operations on a enum.

**Comment by ZyX-I** [comment]
Wait, I have found an interesting thing:

> An implementation may generate warnings in many situations, none of which are
> specified as part of this International Standard. The following are a few of the more
> common situations.
> 
> …
> 
> - A value is given to an object of an enumerated type other than by assignment of an
>   enumeration constant that is a member of that type, or an enumeration object that has
>   the same type, or the value of a function that returns the same enumerated type
>   (6.7.2.2).

(Annex I, common warnings.) `FLAG_B | FLAG_C` is not a member of that type (FLAG_B or FLAG_C would be, but not `FLAG_B | FLAG_C`), an enumeration object (it would be the `flags` variable itself) or a function. Thus standard *suggests* that this code deserves a warning.

**Comment by ZyX-I** [comment]
I have found clang `enum` sanitizer:

> `-fsanitize=enum`: Load of a value of an enumerated type which is not in the range of representable values for that enumerated type.

, but it has nothing against this code or the code that loads enum value scanned from keyboard that cannot be represented by any of the single enum members:

```C
#include <stdio.h>

typedef enum {
    FLAG_0 = 1,
    FLAG_A = 1 << 1,
    FLAG_B = 1 << 2,
    FLAG_C = 1 << 3,
} SomeFlags;

int main(void)
{
    int flags_2;
    scanf("%i", &flags_2);
    SomeFlags flag = flags_2;
    switch (flag) {
        case FLAG_0: puts("0"); break;
        case FLAG_A: puts("A"); break;
        case FLAG_B: puts("B"); break;
        case FLAG_C: puts("C"); break;
        default: printf("%i", flag); break;
    }
    return 0;
}
```

, input `5<CR>`.

**Comment by Grimy** [comment]
> I always thought that enum variable can only take a given set of values.

This is entirely wrong. All `enum`s are simply integer types.

> Thus I would like to see where specification states that SomeFlags flags = FLAG_B | FLAG_C; is valid.

Assigning an integer value to a compatible integer lvalue is valid. Check the sections about assignment and integer types. Also check the section on bitwise or if you have a doubt about the fact that it returns 

However, it’s still very bad style, and most compilers have warnings about it:

    cat enum.c

```typedef enum {
    FLAG_0 = 1 << 0,
    FLAG_A = 1 << 1,
    FLAG_B = 1 << 2,
    FLAG_C = 1 << 3,
} SomeFlags;

int main(void) {
    SomeFlags flags = FLAG_B | FLAG_C;
    (void) flags;
}```

    clang -Weverything enum.c

```enum.c:9:23: warning: integer constant not in range of enumerated type 'SomeFlags' [-Wassign-enum]
    SomeFlags flags = FLAG_B | FLAG_C;
                      ^
1 warning generated.```

    gcc $GCC_FLAGS enum.c

```enum.c:9:23: error: enum conversion in initialization is invalid in C++ [-Werror=c++-compat]
     SomeFlags flags = FLAG_B | FLAG_C;```

(Unfortunately there’s no gcc equivalent to clang’s `-Weverything`, so to get all warnings, you have to list all fifty-ish warning options individually. Here, I use the `GCC_FLAGS` variable to abbreviate).

**Comment by Yamakaky** [comment]
So what do we do ?

**Comment by ZyX-I** [comment]
> This is entirely wrong. All enums are simply integer types.

It is what I said. But I always took it as an *implementation detail*, taken into the standard for compatibility reasons. And I did not propagate it further: “it is equivalent to some integer type -> it may contain any value representable by that type”, and found no explicit propagation.

> (Unfortunately there’s no gcc equivalent to clang’s -Weverything, so to get all warnings, you have to list all fifty-ish warning options individually. Here, I use the GCC_FLAGS variable to abbreviate).

It is not correct to use -Werror=c++-compat for NeoVim project: C99 standard is not compatible with C++, and I guess with this flag it will yield errors for things like `(Type) { .attribute = value }` which are very common. Also I think there is a reason clang did not include -Wassign-enum into -Wall or even -Wextra.

Using enums as @Yamakaky could disable possibility of -fstrict-enums optimization:

> Allow the compiler to optimize using the assumption that a value of enumerated type can only be one of the values of the enumeration (as defined in the C++ standard; basically, a value that can be
> represented in the minimum number of bits needed to represent all the enumerators).  This assumption may not be valid if the program uses a cast to convert an arbitrary integer value to the enumerated
> type.

if it was not C++-only optimization. After reading the description it looks like GCC authors expect this hack to be used *even* in C++ (`g++ -c -Q -O3 --help=optimizers` shows that this one is disabled).

Proposal is compatible with `-fshort-enums` (allocates as less bytes as possible for enum).

I have not found an equivalent for `-Wassign-enum` in GCC man page.

---

My opinion did not change: this variant looks nicer, but rather dangerous. Thus I would prefer keeping flags in the enum, but use standard integer types for actual values. Enum with flag values should not be anonymous for the documentation purposes (i.e. to make it easily referencable). Enum should itself be used for documentation purposes as well: keeps the values together.

**Comment by Yamakaky** [comment]
strict-enums still works : A | B | C is 111, so same width than 100.

**Comment by ZyX-I** [comment]
@Yamakaky It is only about `-fshort-enums`. `-fstrict-enums` says that value of an enumerated type can *only* be one of the values of the enumeration and `A | B | C` is not one of them.

I do not know what exactly compiler does, but this is significant if e.g. compiler has a fast way to compute an index of the first non-zero bit and uses it to construct a jump table for `switch` because it knows that A, B and C can be distinguished by the highest non-zero bit. In this case `A | B | C` will produce the same jump location as `C`, which is incorrect.

Note: I actually do not know whether there is a way to determine an index of first non-zero bit fast, but description of this option makes it clear that it can theoretically enable something like this. More likely I think that for enum with values `0, 1, 2, 3, 4` it will produce an equivalent of `goto *jumps_table[enum_value];` for `switch` without *any* checks about `enum_value` going out of range, but such optimization possibility is not the our case, even though this enum can go out of range too: `4 | 3`.

**Comment by ZyX-I** [comment]
// Also what’s the point in discussing whether C++ optimization can be possibly applied to the suggested code if nobody is going to compile it as C++ in first place?

**Comment by Grimy** [comment]
> keep flags in the enum, but use standard integer types for actual values
Yes, that’s what I would recommend as well. Having a variable of type `SomeFlags` that doesn’t actually hold one of the values of the `SomeFlags` enum creates unnecessary confusion. Using `unsigned int` for flag combinations works identically but is much clearer.

**Comment by Yamakaky** [comment]
Maybe a `typedef uint64_t BitFlags` then ?

**Comment by ZyX-I** [comment]
@Yamakaky Definitely not `uint64_t` or any *single* type: I saw flags represented by variables that have types `char` (in case space is significant), `int`, `unsigned`. I do not think that additional typedef is needed because the fact that some variable contains flags is should already be represented by the variable name.

**Comment by Yamakaky** [comment]
We can do that, but it's not semantic. And with a typedef, we can mask the type used underneath, so if we add a variant, we can change the size.
