### ISSUE TITLE
nvim_buf_get_win

### ISSUE THREAD

**Issue by ilan-schemoul** [neovim/neovim#31415]
### Problem

As far as I know we cannot get the window of buffer. Correct me if I'm wrong.

The only way right now is going through every window and call nvim_win_get_buf everytime and checking the result. It is 0(n) (n = number of window) and takes a bit of time to write and one can make error writing such util.

### Expected behavior

What if instead such basic feature would be provided by nvim with \nvim_buf_get_win\ ? It would be O(1), would be less error prone than writing your own mistake and simpler

**Comment by zeertzjq** [comment]
`:h win_findbuf()`
