### ISSUE TITLE
LSP: dartls: writing hebrew in multiline strings causes error

### ISSUE THREAD

**Issue by eifr** [neovim/neovim#31421]
### Problem

writing hebrew in 3-single-quotes `.dart` file causes error

![Image](https://github.com/user-attachments/assets/99a2e3d2-99a8-43ef-a9a7-8d6bd127f7ef)

### Steps to reproduce using "nvim -u minimal_init.lua"

example:
```dart
final jsonRes = '''
א
''';
```

### Nvim version (nvim -v)

0.10.2

### Language server name/version

dartls

### Operating system/version

kde plasma 6.2.4

**Comment by justinmk** [comment]
Test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by eifr** [comment]
Seems to be fixes on `v0.11.0-dev-1265+g6cdcac4492` 👌
