### ISSUE TITLE
Can't set t_SI and t_EI also #2304

### ISSUE THREAD

**Issue by og01** [neovim/neovim#3142]
Hi I've seen #2304, which shows that these options were removed.

I used them in the past to change my cursor colour in my specific term. (so that my cursor matched the colours used by the airline term).

I very much like this effect.

**Comment by fmoralesc** [comment]
IMHO, this should be done by reimplemementing the guicursor option. With the recent changes on the TUI re: the cursor on mode change, this should be feasible now.

**Comment by og01** [comment]
I understand that enhancments to the guicursor or similar option might be enhanced to allow changing the colour of the cursor, but until then, I was also looking at using autocmd to echo escape codes.

I can't get my escape codes to work, I realise this should almost be a different ticket, but looking at libvterm's escape codes I work out if there is a way to double escape my escape codes so that my terminal gets them.

For reference im looking at something like this:

    autocmd InsertEnter * silent !echo "\033]12;\#0087af\x7"

or

    let &t_SI = "\<ESC>]12;#0087af\x7"

which work in vim.

**Comment by justinmk** [comment]
> `autocmd InsertEnter * silent !echo "\033]12;\#0087af\x7"`

@og01 Does that work in Vim?

**Comment by fmoralesc** [comment]
@og01 Did you try using `prinft`instead of `echo`?

**Comment by justinmk** [comment]
I would not expect `:!echo` nor printf to work in Vim since `:!` invokes a child shell.

**Comment by fmoralesc** [comment]
You are the best kind of correct.

**Comment by vheon** [comment]
I do something similar but redirecting to `/dev/tty` (https://github.com/vheon/vim-cursormode/blob/master/plugin/cursormode.vim#L86)

**Comment by og01** [comment]
Thanks vheon, I will give your suggestion a try

**Comment by justinmk** [comment]
@og01 Does `!echo "\033]12;\#0087af\x7"` work in Vim, or not?

**Comment by gpyh** [comment]
Apparently one needs to set NVIM_TUI_ENABLE_CURSOR_SHAPE=1 as an environment variable in order to interpret the DECSCURS escape sequences. I didn't try with color escape sequences but you might give it a try to see if it fixes your problem.

**Comment by og01** [comment]
Hi @justinmk `!echo "\033]12;\#0087af\x7" works in vim for me, (just tested to be sure).

@vheon Your suggestion seems to work, I used the following config:

    autocmd InsertEnter * silent execute '!echo "\033]12;\#46c7ff\x7" > /dev/tty' | redraw!
    autocmd InsertLeave * silent execute '!echo "\033]12;\#afd700\x7" > /dev/tty' | redraw!

Thanks for your advice.

**Comment by justinmk** [comment]
Thanks, closing this since there is no plan for t_SI or t_EI support.

**Comment by mox-mox** [comment]
The solution suggested by @vheon and @paulgrove work, but at least for me they cause the screen to flicker. I would therefore recommend using this instead:

	autocmd VimEnter    * silent execute '!echo -n "\033]12;\#ff0000\x7" > /dev/tty'
	autocmd InsertEnter * silent execute '!echo -n "\033]12;\#00ff00\x7" > /dev/tty'
	autocmd InsertLeave * silent execute '!echo -n "\033]12;\#ff0000\x7" > /dev/tty'
	autocmd VimLeave    * silent execute '!echo -n "\033]12;\#657b83\x7" > /dev/tty'

The redraw is not really neccessary, the cursor will change colour immediately. But the newline inserted by echo causes the screen to shift up one line, which is undone by redrawing the screen. The obvious solution to this is to just not print that newline in the first place. echos "-n" option does just that: 

    -n     do not output the trailing newline

The autocmd for entering vim makes sure the cursor colour is correct when starting vim, likewise the exit command resets the cursor colour when leaving vim. If somebody knew how to get that colour from the .xdefaults instead of hard-coding it, that would be even nicer.
