### ISSUE TITLE
Visual star selection search (v_star-default) has troubles with <CR> key notation

### ISSUE THREAD

**Issue by robinsonrc** [neovim/neovim#31435]
### Problem

Searching forwards for a selection seems to misbehave when the selected text includes (for example) a `<CR>` key notation

### Steps to reproduce

1. Start up a fresh instance using `nvim --clean`

2. Enter the following text as an example:

```
testing <CR> abc
testing <CR> abc
```

3. Select the first line (for example via `ggV` in Normal mode)

4. Hit `*` to search forwards for the selection

At this point you'll see that the search doesn't happen, and instead the entered text is (unexpectedly I think) changed

### Expected behavior

I'd expect the search to behave as it would if the `<CR>` wasn't present in the text, allowing `n` and `N` to move between the two identical lines

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

No but I don't think it works the same way, vim 9.1.700

### Operating system/version

macOS 14.7.1

### Terminal name/version

Alacritty 0.13.2 (1)

### $TERM environment variable

xterm-256color

### Installation

homebrew

**Comment by justinmk** [comment]
Test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by justinmk** [comment]
confirmed with latest HEAD
