### ISSUE TITLE
LSP: Dynamic capabilities reset `formatexpr`

### ISSUE THREAD

**Issue by 9999years** [neovim/neovim#31430]
### Problem

[`Client:on_attach`](https://github.com/neovim/neovim/blob/49d6cd1da86cab49c7a5a8c79e59d48d016975fa/runtime/lua/vim/lsp/client.lua#L1011-L1037) runs `lsp._set_defaults` (which sets `formatexpr`, among other options) before the user-supplied `on_attach` handler.

I want `formatexpr` to be set to the default so I can use `gq` to wrap text (I use [`conform.nvim`](https://github.com/stevearc/conform.nvim) for format-on-save for language servers that support it), so I set `formatexpr=` in my `on_attach` handler.

But then the LSP [`client/registerCapability`](https://github.com/neovim/neovim/blob/49d6cd1da86cab49c7a5a8c79e59d48d016975fa/runtime/lua/vim/lsp/handlers.lua#L122-L131) handler calls `lsp._set_defaults` again, but without calling the `on_attach` handler.

### Steps to reproduce using "nvim -u minimal_init.lua"

Using the following config, load a Haskell file. The issue can be reproduced with any language server that uses the `client/registerCapability` message to enable formatting support, however.

```lua
local pattern = "haskell"
local cmd = { "haskell-language-server-wrapper", "--lsp" }
local root_markers = { ".git", "cabal.project" }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
    vim.lsp.start({
      name = "haskell-language-server",
      cmd = cmd,
      root_dir = root_dir,
      settings = settings,
      on_attach = function(_client, bufnr)
        vim.api.nvim_buf_set_option(bufnr, "formatexpr", "")
      end,
    })
  end,
})
```

### Expected behavior

My `formatexpr` is not reset.

### Nvim version (nvim -v)

NVIM v0.10.2, Build type: Release, LuaJIT 2.1.1713773202

### Language server name/version

haskell-language-server version: 2.9.0.0 (GHC: 9.8.2)

### Operating system/version

macOS 15.1.1 (24B91)

### Log file

https://gist.github.com/9999years/468188f2acc05f203dec05cfa81d0714

**Comment by 9999years** [comment]
I've worked around this by adding a handler which resets the options:

```lua
--- Call a function for all buffers an LSP client is attached to.
---
--- @param ctx lsp.HandlerContext
--- @param callback function(client: vim.lsp.Client, bufnr: number)
local function for_all_attached_buffers(ctx, callback)
  -- See: https://github.com/neovim/neovim/blob/49d6cd1da86cab49c7a5a8c79e59d48d016975fa/runtime/lua/vim/lsp/handlers.lua#L122-L131
  local client = assert(vim.lsp.get_client_by_id(ctx.client_id))
  for bufnr, _ in pairs(client.attached_buffers) do
    callback(client, bufnr)
  end
end

-- See: vim.lsp.ClientConfig
local client_settings = {
  handlers = {
    ["client/registerCapability"] = function(err, result, ctx, config)
      local default_result =
        vim.lsp.handlers["client/registerCapability"](err, result, ctx, config)
      for_all_attached_buffers(ctx, function(_client, bufnr)
        vim.api.nvim_buf_set_option(bufnr, "formatexpr", "")
      end)
      return default_result
    end,
  },
  -- ...
}
```

I'm not sure what the behavior here should be. Perhaps documenting this behavior would be sufficient, or providing a wrapper like `vim.lsp.with` to allow appending a callback like this.

**Comment by mfussenegger** [comment]
You could also use `gw` instead of `gq`.

Having a way to unset the defaults on new capabilities is tracked with https://github.com/neovim/neovim/issues/24229
