### ISSUE TITLE
Disabling `modeline` option breaks filetype detection for help files, which also disrupts syntax highlighting

### ISSUE THREAD

**Issue by blast-yuki** [neovim/neovim#31468]
### Problem

Disabling the modeline option breaks filetype detection (`vim.bo.filetype` is empty) for help files, which also disrupts syntax highlighting.
After some testing, it works as expected in the v0.9.5 release build. However, all versions up to and including v0.11.0-dev-1287+g8f84167c30 have the same issue as the current latest release (v0.10.2).

### Steps to reproduce

1. init.vim
  `set nomodeline`

2. `nvim --clean -u init.vim`

3. `:h`

#### Error message:
```Error in decoration provider treesitter/highlighter.win:
Error executing lua: ...Az2g/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 2:4. Invalid node type "delimiter":
  (delimiter) @markup.heading.1
   ^

stack traceback:
        [C]: in function '_ts_parse_query'
        ...Az2g/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'
        ...mB6Az2g/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'
        ...mB6Az2g/usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:28: in function 'new'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243: in function 'get_query'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...sr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:178: in function 'prepare_highlight_states'
        ...sr/share/nvim/runtime/lua/vim/tr
```

### Expected behavior

It should correctly detect `vim.bo.filetype` and properly highlight the syntax for help files.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

Not tested

### Operating system/version

Debian 12

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

appimage

**Comment by clason** [comment]
You need to share your `init.vim`. The error message indicates that you have a incompatible queries in your runtimepath. This has nothing to do with filetype detection.

**Comment by clason** [comment]
Needless to say, I cannot reproduce the issue with the steps provided.

**Comment by blast-yuki** [comment]
> You need to share your `init.vim`
It's minimal. It only contains `set nomodeline`.

**Comment by clason** [comment]
And I'm saying that's not enough to reproduce the error.

**Comment by blast-yuki** [comment]
> And I'm saying that's not enough to reproduce the error. And the error message is very telling.

I'm not sure what else should I provide to make it reproducible.
`:e $NVIM_LOG_FILE` is empty though.

**Comment by blast-yuki** [comment]
I tested it in the Termux environment and could not reproduce it too.

**Comment by justinmk** [comment]
Try deleting your $VIMRUNTIME dir completely, then reinstall. 

Or install the latest [development version](https://github.com/neovim/neovim/releases/tag/nightly) and run `:checkhealth`, which has some checks that try to detect a messed up runtime dir.
