### ISSUE TITLE
[LSP,Completion] Clangd function completions add additional space

### ISSUE THREAD

**Issue by ldelossa** [neovim/neovim#31469]
### Problem

When using Neovim's built in LSP completion with clangd, completion of functions result in an extra space being inserted. 

A screencap is included. 

https://github.com/user-attachments/assets/f4396708-ceef-4fcf-b3b1-c7b008894128

### Steps to reproduce

Use:

```
-- on attach method for lsps
local on_attach = function(client, bufnr)
	vim.lsp.completion.enable(true, client.id, bufnr, { autotrigger = false })
end
```
With the clangd LSP config
```
nvim_lsp.clangd.setup({
	capabilities = default_capabilities(),
	on_attach = on_attach,
	on_init = on_init,
	cmd = {
		"clangd",
		"--offset-encoding=utf-16",
		-- this causes a dot symbol next to completion and Neovim does not handle
		-- this well.
		"--header-insertion=never"
	},
})
```

And use completion to insert a function. 

### Expected behavior

No extra space is added to function completion. 

### Nvim version (nvim -v)

NVIM v0.11.0-dev+1267-gc1378413c

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

fedora 40 

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

### Installation

fedora nightly copr

**Comment by justinmk** [comment]
> And use completion to insert a function.

be more specific. I tried your config and tried `ctrl-x ctrl-o` to complete a function, and no space was prepended.

**Comment by ldelossa** [comment]
No autocompletion plugin is being used. 

I can reproduce with `ctrl-x ctrl-o` 

```
:set omnifunc                                                                                                                                                                                         
  omnifunc=v:lua.vim.lsp.omnifunc
```

**Comment by zeertzjq** [comment]
Please provide complete steps to reproduce. There are several undefined symbols in your steps:
- `nvim_lsp`
- `default_capabilities()`
- `on_init`

**Comment by ldelossa** [comment]
Tracked this down to an lsp related settings. Not an nvim problem. Sorry for the noise.
