### ISSUE TITLE
`InsertEnter` and `nvim_get_mode`

### ISSUE THREAD

**Issue by aidancz** [neovim/neovim#31471]
### Problem

can't use `nvim_get_mode` inside `InsertEnter` autocmd callback

### Steps to reproduce

1. prepare file `minimal.lua`

```
vim.opt.showmode = false

vim.api.nvim_create_autocmd({'InsertEnter'}, {callback = function() vim.print(vim.api.nvim_get_mode().mode) end})
```

2. run `nvim --clean -u minimal.lua`

3. press `i` to enter insert mode

4. prompt `n`

### Expected behavior

prompt `i`

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1287+g8f84167c30

### Vim (not Nvim) behaves the same?

not sure

### Operating system/version

6.12.1-arch1-1

### Terminal name/version

st 0.8.5

### $TERM environment variable

st-256color

### Installation

release page

**Comment by zeertzjq** [comment]
This is working as intended.
> Just before starting Insert mode.
