### ISSUE TITLE
How to use the * register for yanking? (I have xsel, but no luck).

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3147]
I'd like to use `"*` to yank in nvim so I can paste to other apps in my MATE desktop. I have xsel installed, which allows me to paste stuff copied outside of neovim with `"*p`, but I can't use `"*` for yanking. I can only copy from neovim with `"+` in order to paste in other apps with `ctrl+v`.

**Comment by fmoralesc** [comment]
Pasting from the PRIMARY clipboard (`*`) is usually done with the middle button. `"*y` shouldn't touch the one that handles `<C-v>` it unless you have `set clipboard=unnamedplus`. There's work ongoing about it.

**Comment by justinmk** [comment]
Assuming this is covered by https://github.com/neovim/neovim/issues/2325

**Comment by trusktr** [comment]
I basically just want `"*` followed by any yank command to copy into the desktop environment clipboard, just like in Neovim for OS X does out of the box. I've had no luck with any of these:

```
set clipboard=
set clipboard=unnamed
set clipboard=unnamedplus
set clipboard=unnamed,unnamedplus
```

**Comment by alerque** [comment]
@truskr Are you sure you are up to date with a recent Neovim build on your Linux systems? And that you don't have any plugins or other stuff in your rc  file that is messing with you? Because this should work as expected right now (and does for me using `set clipboard=unnamedplus`).

**Comment by trusktr** [comment]
@alerque I've got the latest from git, including this: https://github.com/neovim/neovim/pull/3141

I don't want `yy` to yank anywhere other than `0`. I want to explicitly use `"*yy` to yank into the `*` register. That works for you in Linux? I just tried with `nvim -u NONE` so I have no plugins loaded, and it still won't work.

**Comment by fmoralesc** [comment]
`nvim -u NONE` won't load the clipboard provider. You probably want to use `-u NORC`.

**Comment by trusktr** [comment]
@fmoralesc I just tried `-u NORC`, but still no luck.

**Comment by trusktr** [comment]
@fmoralesc Aha, `"*` **does** work, but not like I was expecting: https://github.com/neovim/neovim/issues/3096#issuecomment-129648892

**Comment by trusktr** [comment]
Workaround for Linux: https://github.com/neovim/neovim/issues/3096#issuecomment-129663919
