### ISSUE TITLE
It's the end of 2024, and you are still not quite ready for ARM...

### ISSUE THREAD

**Issue by bpavuk** [neovim/neovim#31503]
### Problem

C'mon, 2025 knocks the door, and I still only have **old** Neovim 0.7 in that forgotten Ubuntu PPA for Aarch64/ARM32 and no Neovim on Arm for Fedora at all unless I compile it myself. Time to provide official ARM releases on every major platform, be it Linux, Windows, or macOS. Right now, I see only macOS support. Is it that difficult to tweak GitHub Actions files, especially given that ARM source releases compile flawlessly? Even if I have to download the RPM/DEBs from the Releases page, it's still much better than compiling from the source.
What if I want to tweak some configs quickly on my Raspberry Pi, or code on a phone (in fact, I do), or for unbeknownst reasons have a shiny new X Elite laptop?
Anyway, ARM is the future. Even such behemoth projects like Blender provide ARM builds in alpha testing.

### Expected behavior

I can just `sudo apt install neovim` or `sudo dnf install neovim` regardless of whether I use ARM or x86. GitHub Actions can handle cross-compilation easily.

**Comment by zeertzjq** [comment]
Search existing issues
