### ISSUE TITLE
mingw: error on startup, "language.lua:107: no parser for 'lua' language"

### ISSUE THREAD

**Issue by abdulbadii** [neovim/neovim#31515]
### Problem

```
$ nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1732813678

```
On Msys2/Mingw64, this nvim upon being launched, init.lua in
`~/.config/nvim/
`
not initialized if file rather simple readable text and without error message, or also on opening certain files, with some error messages 

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: C:\msys64\mingw64\share\nvim\runtime\filetype.lua:35: Error executing lua:
C:\msys64\mingw64\share\nvim\runtime\filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script C:\msys64\mingw64\share\nvim\runtime\ftplugin\lua.lua: Vim(runtime):E5113: Error while calling lua chunk: ...ngw64\share\nvim\runtime/lua/vim/treesitter/language.lua:107: no parser for 'lua' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...ngw64\share\nvim\runtime/lua/vim/treesitter/language.lua:107: in function 'add'
        ...4\share\nvim\runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'

```
...
Pleas help out as previous nvim version it has no this error, so shed a light to solve  

### Steps to reproduce

$ nvim --clean .config/nvim/init.lua

### Expected behavior

Readily performs editing with init.lua file configurations all set

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1732813678

### Vim (not Nvim) behaves the same?

Do not know as never have to do with vim

### Operating system/version

Windows of Msys2

### Terminal name/version

mintty

### $TERM environment variable

xterm

### Installation

Msys2/Mingw64 mainstream repo

**Comment by clason** [comment]
The error message indicates that your installation is broken; please report this to the "mainstream repo" (we do not maintain distro packages; try downloading the provided releases from Github).

**Comment by justinmk** [comment]
> language.lua:107: no parser for 'lua' language

Msys2/Mingw64 (or however you installed) did not install the required runtime files (which includes treesitter parsers).
