### ISSUE TITLE
Wrong syntax highlighter [python]

### ISSUE THREAD

**Issue by maciejczyzewski** [neovim/neovim#3151]
![ups?](https://dl.dropboxusercontent.com/u/103345209/Screenshots/Screenshot%202015-08-10%2001.39.21.png)
It doesn't look healthy...

**Comment by ZyX-I** [comment]
Have you tried doing `:redraw!`? (You may also redraw screen using `<C-l>`.)

**Comment by maciejczyzewski** [comment]
@ZyX-I yep, not working :worried:

**Comment by justinmk** [comment]
Does `:syntax sync fromstart` fix it?

**Comment by maciejczyzewski** [comment]
@justinmk no, but changing `\""""` to `\" """` makes it ok!

**Comment by justinmk** [comment]
The bug is present in Vim, so this is a low priority for us.

**Comment by Grimy** [comment]
It might be low priority, but the fix is trivial. I’m making a PR.
