### ISSUE TITLE
get localized string in lua

### ISSUE THREAD

**Issue by BPplays** [neovim/neovim#31526]
### Problem

there seems to be no way to try and get a string for a specific language or the current language

### Expected behavior

it seems like [neovim/master/src/nvim/po/](https://github.com/neovim/neovim/tree/master/src/nvim/po/) contains localized strings something to use those would be nice, maybe:
```lua
vim.localize.get_string(string, lang)
```
where `lang` is optional to specify the language you want to localize to, it should default to the current language

**Comment by lewis6991** [comment]
In support of this, but not sure if this should be exposed as a public interface. At least to begin with, we should try to add localisation for the messaging we use in Lua core. Once we have that in some manageable state, we can think about exposing something.

For an exposed interface, we would need to introduce another runtime directory (`[rtp]/lang/*`?) where plugins can add their own localisations.

**Comment by dundargoc** [comment]
I don't get it. What is the usecase for you to access editor-specific warnings? They aren't intended to be "public" or reused IIUC.

**Comment by clason** [comment]
Yes, the `po` files are a red herring here. It's about an API for plugins (and our stdlib) to display localized messages.

**Comment by dundargoc** [comment]
That seems pretty ambitious. I've not seen strong indications that plugins write legible messages in any language to begin with, let alone multiple :)

Also yeah, if it involved working with or extending gettext then I'm not touching this with a ten-foot pole.

**Comment by clason** [comment]
The replacement would be `vim.localize`, i.e., a pure Lua solution ;) (And, yes, that's ambitious, and low priority -- but still worth tracking IMO.)

**Comment by lewis6991** [comment]
Yes, this is exactly why I prefaced this with doing it internally first, and revisit an API later once we understand the details.

Having localised messages for our internal Lua code is absolutely something we should do, otherwise we should just remove all localisation.

**Comment by dundargoc** [comment]
> we should just remove all localisation.

Aight bet.

**Comment by BPplays** [comment]
the reason i suggested this is stuff like [nvim-lualine/lualine.nvim](https://github.com/nvim-lualine/lualine.nvim) always displays modes in english and there already seem to be some modes in the .po files.
around line 1866 in [neovim/blob/master/src/nvim/po/ja.po](https://github.com/neovim/neovim/blob/master/src/nvim/po/ja.po) there is a translation for `VISUAL`, `VISUAL BLOCK`, `VISUAL LINE`, `SELECT`, etc, i thought simple stuff like that would be useful

**Comment by dundargoc** [comment]
What part of

Original C Sources ───> Preparation ───> Marked C Sources ───╮ │ ╭─────────<─── GNU gettext Library │ ╭─── make <───┤ │ │ ╰─────────<────────────────────┬───────────────╯ │ │ │ ╭─────<─── PACKAGE.pot <─── xgettext <───╯ ╭───<─── PO Compendium │ │ │ ↑ │ │ ╰───╮ │ │ ╰───╮ ├───> PO editor ───╮ │ ├────> msgmerge ──────> LANG.po ────>────────╯ │ │ ╭───╯ │ │ │ │ │ ╰─────────────<───────────────╮ │ │ ├─── New LANG.po <────────────────────╯ │ ╭─── LANG.gmo <─── msgfmt <───╯ │ │ │ ╰───> install ───> /.../LANG/PACKAGE.mo ───╮ │ ├───> "Hello world!" ╰───────> install ───> /.../bin/PROGRAM ───────╯

do you not understand?

**Comment by zeertzjq** [comment]
`vim.fn.gettext()`

**Comment by justinmk** [comment]
> vim.fn.gettext()

Why isn't that sufficient?

**Comment by BPplays** [comment]
@justinmk 
> Why isn't that sufficient?

i didn't find it when i was googling before.

**Comment by clason** [comment]
Isn't that string `" VISUAL"` (whitespace!)?
