### ISSUE TITLE
Providing a count to `zb` works the same as `zt`

### ISSUE THREAD

**Issue by kkrime** [neovim/neovim#31535]
### Problem

When you give a count to `zb` it behaves the same way if you were to pass in a count to `zt`

### Steps to reproduce

1.  open up a text file that is long enough
2.  scrol down a few times `C-d`
3.  press `10zb`

### Expected behavior

The buffer should be redrawn so that the line on step 3 is 10 lines from the bottom of the window, instead it is 10 lines from the top of the window (as it should be if we used `zt`)

### Nvim version (nvim -v)

NVIM v0.10.2

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

macOS 11.5

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

### Installation

Brew

**Comment by zeertzjq** [comment]
> The buffer should be redrawn so that the line on step 3 is 10 lines from the bottom of the window, instead it is 10 lines from the top of the window (as it should be if we used `zt`)

No. It should put line 10 at the bottom of the window, but if the window has more than 10 lines, it scrolls to the top.
