### ISSUE TITLE
Change the default `&fileencoding` to utf-8

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#3153]
Currently, the default value of the `&fileencoding` option is the empty string, `""`. I suggest changing it to `"utf-8"` for the following reasons:
* UTF-8 is a great encoding, and is now ubiquitous
* The default value of `&encoding` was already changed to `"utf-8"` (see #935)
* `""` isn’t documented as a valid encoding name (see `:help encoding-names`)
* When a file isn’t valid UTF-8, the auto-detection mechanism (described in `:help fileencodings`) will fallback to `"latin1"` anyway.

See also #2676.

**Comment by bfredl** [comment]
>The default value of &encoding was already changed to "utf-8"

Well, in practice The default &enc is the system encoding, and the default fenc="" means reuse &enc. Not that I have against "UTF-8 ALL THE THINGS" ( I did propose #2905 after all) ,just pointing out this is not really analogous to #935

**Comment by Grimy** [comment]
Well, since `&encoding` should always be `"utf-8"` and an empty `&fileencoding` means “reuse the value from &encoding”, `""` and `"utf-8"` are basically two ways of saying the same thing. We should consistently use one or the other, but not both. As of now, the default `&fileencoding` uses `""`, but the default `&fileencodings` uses `"utf-8"`.

My suggestion is to use `"utf-8"` everywhere, since it is more immediately obvious what it does. Another possibility is to change the default of `&fileencodings` to `ucs-bom,,latin1` (see the empty string between the two commas?). This works fine, but is kinda ugly imho.

**Comment by justinmk** [comment]
> an empty &fileencoding means “reuse the value from &encoding”, "" and "utf-8" are basically two ways of saying the same thing

No, because if a user sets a different `'encoding'` then `fenc=""` should default to that. On the other hand I don't see why users should be able to set `'enc'` at all, so I'm neutral on this change. But I'm going to close this because changing it is more than zero work, and there's not a strong argument for or against.
