### ISSUE TITLE
Current vimdoc treesitter syntax should be improved

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#31544]
### Problem

Treesitter for vimdoc(help) is default synax.  So it should be improved.

Treesitter:
![Image](https://github.com/user-attachments/assets/2a4cffae-a621-4b9d-a7ab-225d2b0c5142)

Vim syntax:
![Image](https://github.com/user-attachments/assets/56fb8013-7e62-4f7c-b6a0-e8b716e8afc1)

Problem:

* All tags are link to `@markup.link` in treesitter.  In Vim, each tags(options, link) are different syntax.

* Special characters in tags `'` or `|`, `*` is same highlighted with tag text.

### Expected behavior

Expected behavior:

* Each tags have different highlight.

* Special markup characters should be highlighted in different.

**Comment by lewis6991** [comment]
Highlighting looks fine to me. I'm guessing `'|*` aren't highlighted because they should be concealed.

**Comment by clason** [comment]
They _are_ highlighted; you probably don't have the (new) highlight groups defined. `:h treesitter-highlight-groups` and `:Inspect`.

**Comment by clason** [comment]
If you want to give them a different highlight group, you need to write your own queries (`:InspectTree` and `:EditQuery` will help).

**Comment by Shougo** [comment]
> Highlighting looks fine to me. I'm guessing '|* aren't highlighted because they should be concealed.

I understand the reasoning, and it's not a major inconvenience, but it's clear that Vim's syntax highlighting is superior.
If Neovim make treesitter highlight the default, shouldn't it provide equivalent highlighting in vimdoc?

> They are highlighted; you probably don't have the (new) highlight groups defined. :h treesitter-highlight-groups and :Inspect.

Please read the source code.

https://github.com/neovim/neovim/blob/09d76afe84dd5b895e102dcd8df8ce6271bebfef/runtime/queries/vimdoc/highlights.scm#L19

Where is the different groups highlight?  It seems same highlight `@label` and `@markup.link`.

> If you want to give them a different highlight group, you need to write your own queries (:InspectTree and :EditQuery will help).

Yes, I can change the query.  However, shouldn't the default syntax highlighting be improved? I thought Neovim's policy of adopting treesitter was to make the default better, or am I mistaken?

Of course, I can improve the query and send the PR.  But it is acceptable?
I would like to hear the opinions of the developers. I have heard that discussions should be held before submitting code.

**Comment by clason** [comment]
> I understand the reasoning, and it's not a major inconvenience, but it's clear that Vim's syntax highlighting is superior.

It's not clear to me; quite the opposite.

> Where is the different groups highlight? It seems same highlight @label and @markup.link.

Your issue description stated that these are _not_ highlighted, so that is what I commented on there.

> I thought Neovim's policy of adopting treesitter was to make the default better, or am I mistaken?

Yes, but "better" is in the eye of the beholder. One of the main design goals was to unify the highlight group names across the different languages, so colorschemes no longer have to define hundreds of different(ly named) groups. So adding new _types_ of labels is not something we want to consider. 

And, again, you can customize this to your heart's desire by putting your own queries in your config (either extending or replacing the current ones), so changing the default requires this to be a general improvement (which I'm not yet fully sold on in this case).

**Comment by justinmk** [comment]
> All tags are link to `@markup.link` in treesitter.  In Vim, each tags(options, link) are different syntax.

Why should they be different? If something is a link, how does it help the user to see a link to options (which are always surrounded with single-quotes) highlighted differently than links to non-options?

Arbitrary highlighting differences are just visual noise.

**Comment by Shougo** [comment]
I see. I understand that you want the help links to be displayed like web browser help.

https://neovim.io/doc/user/

I personally prefer the original Vim syntax display, but if there are no other supporters, it can't be helped. I will configure it myself.
