### ISSUE TITLE
LSP: vim.diagnostic.setqflist does not work after usage of vim.lsp.buf.document_symbol

### ISSUE THREAD

**Issue by nNeD5** [neovim/neovim#31540]
### Problem

`vim.diagnostic.setqflist` stop make any changes to `quickfix list` after usage of `vim.lsp.buf.document_symbol`

1. run `vim.diagnostic.setqflist`: it shows diagnostic in quickfix list
2. run `vim.lsp.buf.document_symbol`: it shows symbols
3. run `vim.diagnostic.setqflist`: still shows symbols

But  e.g. `:grep` works fine.

https://github.com/user-attachments/assets/8684f56a-d093-44c0-89a0-1cb085034276

### Steps to reproduce using "nvim -u minimal_init.lua"

1. run `vim.diagnostic.setqflist`: it shows diagnostic in quickfix list
2. run `vim.lsp.buf.document_symbol`: it shows symbols
3. run `vim.diagnostic.setqflist`: still shows symbols

**minimal_init.lua**
```lua
local pattern = 'lua'
local cmd = {'lua-language-server'}
local root_markers = { '.' }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-ls',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings
    })
  end
})
```

As far as I understand the problem is in **share/nvim/runtime/lua/vim/lsp/diagnostic.lua** `function set_list`. It has next code:
```lua
    -- If we already have a diagnostics quickfix, update it rather than creating a new one.
    -- This avoids polluting the finite set of quickfix lists, and preserves the currently selected
    -- entry.
    vim.fn.setqflist({}, _qf_id and 'u' or ' ', {
      title = title,
      items = items,
      id = _qf_id,
    })
```
Changing `vim.fn.setqflist({}, _qf_id and 'u' or ' ',` to just `vim.fn.setqflist({}, ' ',` fix this issue.

### Expected behavior

`vim.diagnostic.setqflist` should put diagnostick in quickfix list

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1334+gca760e645b

### Language server name/version

lua-language-server but probably any

### Operating system/version

6.12.3-arch1-1 Hyprland 0.45.2 built from branch  at commit 12f9a0d0b93f691d4d9923716557154d74777b0a

**Comment by chanha-park** [comment]
it seems like the related PR is https://github.com/neovim/neovim/pull/30868

**Comment by SebasF1349** [comment]
Pr mentions that it will update a previously set qflist. Maybe you need to open the older qf. You can check doing `:colder`

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/blob/ca760e645ba4d1fdb0b6fff3ac98231c3d683306/runtime/lua/vim/diagnostic.lua#L853-L860

@jfly does `set_list` need a flag that tells it whether to use `_qf_id` ? Or is there just a bug here?

**Comment by nNeD5** [comment]
> Is this a correct summary of the bug?:

>  `vim.lsp.buf.document_symbol`, instead of what the user passed to 
> `vim.diagnostic.setqflist`]

Almost, actually, user shouldn't pass anything in `vim.diagnostic.setqflist`.

> `vim.diagnostic.setqflist()`
> Add all diagnostics to the quickfix list

According to docs, you can just call it without arguments to set diagnostics in quickfix list.

**Comment by jfly** [comment]
> Or is there just a bug here?

This is just buggy. When we [update an existing quickfix list](https://github.com/neovim/neovim/blob/442d338cb50e4cf08c58cb82b6d33b6d5df9fb1b/runtime/lua/vim/diagnostic.lua/#L856-L860), we then call [`botright cwindow`](https://github.com/neovim/neovim/blob/442d338cb50e4cf08c58cb82b6d33b6d5df9fb1b/runtime/lua/vim/diagnostic.lua/#L868), which opens the quickfix "window" ("buffer"? "split"? I don't know the right term here, sorry), but this is not necessarily showing the quickfix list we just updated.

The fix would be to explicitly open the correct quickfix list by id, which is what I've done (tried to do) in https://github.com/neovim/neovim/pull/31553. @nNeD5, can you give that PR a shot and let me know if it works?

**Comment by nNeD5** [comment]
works like a charm in https://github.com/neovim/neovim/pull/31553. 

Maybe it's a bit inconsistent that `vim.lsp.buf.document_symbol` always moves focus to the quickfix list, while `vim.diagnostic.setqflist` only does so the first time. However, I personally prefer that neither of them does that, so I’m closing this.
