### ISSUE TITLE
StatusLine custom color group inherits attributes from hl-StatusLine instead of hl-Normal

### ISSUE THREAD

**Issue by matveyt** [neovim/neovim#31568]
### Problem

When setting custom color in StatusLine (by `#ColorGroupName#` string) the attributes get blended with `hl-StatusLine` group, not with `hl-Normal` as it has been earlier.

### Steps to reproduce

nvim --clean
set statusline=%#Directory#%=

" Observe that status line has cyan background
" This is due to ctermfg(Directory) is 'cyan' && cterm(StatusLine) is 'reverse'

### Expected behavior

The background of StatusLine should remain "Normal" (inherited by `hl-Directory`). Applying the attributes (`cterm` / `gui`) from `hl-StatusLine` does not make much sense and is a breaking change.

This change looks as a relatively recent one but I was not able to find out if it was a deliberate decision or not.

### Nvim version (nvim -v)

0.11.0-dev-1344+g17383870dd

### Vim (not Nvim) behaves the same?

no, Vim 9.1.919

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal

### $TERM environment variable

N/A

### Installation

from https://github.com/neovim/neovim/releases

**Comment by luukvbaal** [comment]
#26037 #29976

**Comment by matveyt** [comment]
@luukvbaal Thank you. So this is a deliberate one and I'm close the issue.

However, I should say that in my opinion it's a totally wrong decision that makes colors of a status line (and probably more) unpredictable even for default color scheme.
