### ISSUE TITLE
LSP: oversized hover, signatureHelp window

### ISSUE THREAD

**Issue by kuprTheMan** [neovim/neovim#31574]
### Problem

The hover and signatureHelp widows are all very indented and do not scale with the content inside

Hover:
![Image](https://github.com/user-attachments/assets/3f01f1e6-2533-4c23-a944-a8ad3dfe7551)

signatureHelp:
![Image](https://github.com/user-attachments/assets/d7c6a517-20ef-4a78-96a8-9b5fb4d89eed)

### Steps to reproduce

I set borders like this:

```lua
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview 
local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
  opts = opts or {}
  opts.border = opts.border or "rounded"
  return orig_util_open_floating_preview(contents, syntax, opts, ...)
end```


### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Gentoo

### Terminal name/version

foot

### $TERM environment variable

foot

### Installation

emerge nvim

**Comment by justinmk** [comment]
Test the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by justinmk** [comment]
Seems similar to https://github.com/neovim/neovim/issues/30831

**Comment by glepnir** [comment]
Currently you can set `vim.lsp.buf.hover({max_width=x})`, for example as a percentage of the width of the entire editor or a percentage of the width of the window.

**Comment by justinmk** [comment]
I don't understand how the signatureHelp example in the main description is an example of "not scaling to content". The content is long, and the screen width is wide, and the hover window scaled to fit the available width.

If the dynamic sizing has a bug, that's covered by https://github.com/neovim/neovim/issues/30831
