### ISSUE TITLE
messages: ui_attach: sometimes whitespaces are not preserved in chunks

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#31624]
### Problem

Sometimes message chunks passed to `vim.ui_attach` callback have lost some whitespace characters compared to the built-in UI appearance. 

![Image](https://github.com/user-attachments/assets/8e13b594-f70b-40e7-9bf9-61423b37a37e)

### Steps to reproduce

`init.lua`:
```lua
local api = vim.api
local ns = api.nvim_create_namespace('messageRedirection')

local function log(msg)
  api.nvim_buf_set_lines(1, -1, -1, true, vim.split(msg, '\n'))
  vim.cmd.normal 'G'
end

local function detach()
  api.nvim__redraw({flush = true})
  vim.ui_detach(ns)
  api.nvim__redraw({flush = true})
end

api.nvim_create_autocmd('CmdlineEnter', {callback = detach})

local redirect = true

local function attach()
  if not redirect then
    return
  end
  api.nvim__redraw({flush = true})
  vim.ui_attach(ns, {ext_messages = true, ext_cmdline = false}, function (event, _, content, _)
    if event ~= 'msg_show' then
      return
    end

    vim.schedule(function ()
      log(vim.inspect(content))
      api.nvim__redraw({flush = true})
    end)
  end)
end

api.nvim_create_autocmd({'CmdlineLeave'}, {callback = attach})

api.nvim_create_autocmd({'UIEnter'}, {
  callback = attach
})

api.nvim_create_user_command('MsgRedirToggle', function ()
  redirect = not redirect
  if not redirect then
    detach()
  end
end, {nargs = 0})
```
- `nvim --clean -u init.lua`
- enter `:filter Search hi` command
- enter `:MsgRedirToggle`
- enter `:filter Search hi` command again and compare results, especially look at the chunk contents before `xxx`. I get

![Image](https://github.com/user-attachments/assets/09b523f9-d181-4c45-89e8-f2767d645e7b)

Only the first line has any space before `xxx`.

### Expected behavior

Whitespace characters are preserved in ui_attach callback. 

### Nvim version (nvim -v)

v0.11.0-dev-1380+g7121983c45

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Debian Sid

### Terminal name/version

alacritty

### $TERM environment variable

alacritty

### Installation

from repo

**Comment by luukvbaal** [comment]
I came across this logic (and may have fixed it) when I made a mockup commit that removed the message grid. I'll see if I did, and can extract it.

**Comment by przepompownia** [comment]
#31627 seems to keep whitespaces both on the repro and my [practical usage](https://github.com/przepompownia/msg-show.nvim). Thank you!

![Image](https://github.com/user-attachments/assets/92136fc7-8044-4bf2-80ae-d51313f5861f)
