### ISSUE TITLE
Improving accessibility of current default colorscheme

### ISSUE THREAD

**Issue by saccarosium** [neovim/neovim#31636]
### Problem

# Preface

**Who am I?**

I've been a graphic designer since 2016 and I've work a lot in accessible color
design.

**Resources**

Every test was made using the following websites:
- <https://webaim.org/resources/contrastchecker/>
- <https://colourcontrast.cc/>

**Terms**

- R: Regular
- B: Bold

# Dark Palette

| Color Name | #RGB | Contrast Ratio | AA R | AAA R | AA B | AAA B |
|---|---|---|---|---|---|---|
| Foreground | `#e9ebf2` | 15.19:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Blue | `#a6dbff` | 12.23:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Cyan | `#8cf8f7` | 14.55:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Green | `#b3f6c0` | 14.53:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Red | `#ffc0b9` | 11.63:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Yellow | `#fce094` | 13.98:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Magenta | `#ffcaff` | 13.05:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

## Luminance and Contrast differences

The dark color palette is, on paper, accessible since it doesn't fail a single
contrast scenario. Unfortunately accessibility is not so simple and we also
need to check for difference in luminance between the different colors.

Luminance is the [lightness of a color][1] and, for the worst case of
color-blindes, is the only way they distinguish colors.

There are a lot of differente [type of color blindness][2] but usually, or at
least how I was tought, we create our color palette by reducing the saturation
of color at zero. This is done to ensure that we guide the user's eyes to the
right thing. Turns out having a good luninance ratio between colors make
reading clear for everybody.

To see what I mean leat's but the colors side by side and we try to reduce the
saturation to zero:

![Image](https://github.com/user-attachments/assets/cb6ce95a-1401-406b-9c32-b6f05db284cf)

As we can see, the colors became basically the same grayish color. 

Another more allarming thing is that the foreground has more contrast that any
other color. The issues with this is that we want to use color to highlight
important things so they pop up more to the eyes of the users. In the current
scenario a colored word is actually more difficult to read since the majority
of the text has more contrast.

[1]: https://en.wikipedia.org/wiki/Lightness
[2]: https://en.wikipedia.org/wiki/Color_blindness#Classification

# Light Palette

| Color Name | #RGB | Contrast Ratio | AA R | AAA R | AA B | AAA B |
|---|---|---|---|---|---|---|
| Foreground | `#14161b` | 15.19:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Blue | `#004c73` | 7.73:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Blue | `#007373` | 4.76:1 | :white_check_mark: | | :white_check_mark: | :white_check_mark: |
| Green | `#005523` | 7.58:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Red | `#590008` | 12.34:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Yellow | `#6b5300` | 6.15:1 | :white_check_mark: | | :white_check_mark: | :white_check_mark: |
| Magenta | `#470045` | 13.02:1 | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

## Luminance and Contrast differences

The light palette is in a much more state where with some colors we don't even
pass some tests.

Here the problem described above is much worse because the contrast between
colors is even more drastic and sometimes thing become really difficult to
distinguish between one or another.

![Image](https://github.com/user-attachments/assets/0a9d82e0-96a8-4669-a97f-8443647429a1)

# Colors Hue Problems

While it is a good thing to use neovim's color. It is a lot harder to make the
colorscheme accessible since the hues of the primary colors (blue, cyan and
green) are too similar, witch makes really hard to distinguish syntax element
even for people with normal vision like myself.

### Expected behavior

Make design and luminance ratio between colors more accessible.

**Comment by clason** [comment]
Where are you getting these colors from? They don't look like the default Nvim colorscheme (which _was_ tuned -- with a lot of effort and under constraints -- to be as accessible as possible).

You may be looking at your terminal palette; make sure `termguicolors` is set.

**Comment by saccarosium** [comment]
> Where are you getting these colors from? They don't look like the default Nvim colorscheme 

https://github.com/neovim/neovim/blob/31d6885deba01fe0e7262dca58c94220c2fe32fc/src/nvim/highlight_group.c#L2920

Also if you check the colors that were commited in https://github.com/mbadolato/iTerm2-Color-Schemes. They are the same I've used (you point this out in https://github.com/neovim/neovim/issues/26857#issuecomment-2119185077)

> (which was tuned -- with a lot of effort and under constraints -- to be as accessible as possible).

By witch metric? I've used commonly used tools to check the contrast and this is the result.

**Comment by clason** [comment]
> Also if you check the colors that were commited in https://github.com/mbadolato/iTerm2-Color-Schemes.

Those are not maintained by us.

> By witch metric? I've used commonly used tools to check the contrast and this is the result.

Check out the PRs.

> but usually, or at least how I was tought, we create our color palette by reducing the saturation of color at zero. 

There are much better tools available now (CVD simulators).

**Comment by clason** [comment]
And, it goes without saying, that is just the _default_ colorscheme that is simply meant to be an improvement over the old colorscheme. (Due to the Can't Please Everyone Theorem, it can never be perfect.) If you have specific requirements, you can and should still create your own colorscheme.

**Comment by saccarosium** [comment]
> Either it looks good or it doesn't. Can't please everyone.

Here is not a matter of taste. It is a matter of vision. On the light theme the legibility is not really good.

> In all cases, I'd prefer to increase contrast (including for the Normal fg color). Reducing contrast for almost all text in order to make things "pop" elsewhere is not a good tradeoff.

It is not what I'm suggesting. It should be investigate further.

> it goes without saying, that is just the default colorscheme that is simply meant to be an improvement over the old colorscheme. (Due to the Can't Please Everyone Theorem, it can never be perfect.) If you have specific requirements, you can and should still create your own colorscheme.

Yes, it is true. But you can't forget that the defaults are important. A lot of other IDE users don't change the default colorscheme because it is already good contrast already

> Check out the PRs.

I've already research a bunch before doing this I didn't found nothing... Can you please link them? Would be much appreciated.

**Comment by saccarosium** [comment]
@justinmk can we reopen this issue and maybe change the title to something like "Improove contrast in light theme"?

I want to make clear some things:
- I'm not arguing about the colors themselves, I'm talking about contrast
- I'm not saying to reduce the contrast, I actually saying that we should probably increase it in the light theme
- I get what you are saying about color theory but we need some objective measure to discuss color. "Either it looks good or it doesn't." is not really measurable and it is a matter of taste. Contrast ratio, on the other end is pretty objective and since I do actually like the default colorscheme I would like to make it a bit more accessible (especially the light theme witch I believe needs some love).

**Comment by clason** [comment]
I am sorry, but this topic is done with; it ate enough of all our lives. If you have a specific improvement suggestion, feel free to open a PR; but we will not open the whole can of worms again for a while.

**Comment by jmpolom** [comment]
@justinmk 

> These tools and "color science" are like diet fads and nutrition experts. A bunch of witchcraft.

Wow. What ignorance. Color science is very much not witchcraft though it is heavily dependent on heuristics and the (imperfect) scientific understanding of human biology and neuroscience.

As a user with aging eyes and a full time wearer of corrective lenses, your position is **deeply insulting**. You should step away from making decisions on this topic if you will approach it with this degree of carelessness and ignorance and proceed to block others offering to fix an (obvious) problem.

> If there is something we can adjust to make stuff more usable, great. But it's not going to be driven by these "color science" things.

The initial analysis done by @saccarosium is incomplete because it just looks at contrast against background color. What you're missing is contrast ratios against adjacent colors that are possible with syntax highlighting. This is where the neovim default color scheme becomes _unusable_. However disregarding placing some rigor into the selection of colors as "witchcraft" is absurd and insulting.

> Either it looks good or it doesn't.

Looks good != functional. And looks good according to whom? Yourself? What qualifications have you here again?

If you're going off subjective/aesthetic looks to judge usability that's one aspect that needs re-examination.

> Can't please everyone. And using the Nvim brand colors is a requirement.

Again this is a **deeply insulting** and offensive position to take concerning accessibility. You should step away from this topic if you cannot handle it professionally, while respecting the limits of your own knowledge, allowing others to help out in areas where they have expertise you lack, and (most importantly) providing due consideration for problems those with imperfect vision may have using the tool you contribute to.

Instead it appears you have pushed away a contributor trying to make a sorely needed improvement. The default color scheme is _unusable_ even if you don't have major vision issues. Any default color scheme should be high quality, highly usable and accessible out of the box.

The color on the default is so subtle and so poorly contrasted I have assessed it as functionally useless. Users should not have to pursue 3rd party themes to get basic visual usability from their preferred editor.

**Comment by justinmk** [comment]
> The color on the default is so subtle and so poorly contrasted I have assessed it as functionally useless.

I'm in favor of increasing the contrast a bit. The current lack of contrast was driven by "color science" or whatever.

If you are "insulted", that's your problem. It is not possible to have a colorscheme that everyone likes.

No more emotional posts, please. Last warning.
