### ISSUE TITLE
Coverity is broken

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3163]
```
Lines of code analyzed	6,940
```

The upload process changed recently, we may need to review https://scan.coverity.com/projects/neovim-neovim/builds/new

**Comment by justinmk** [comment]
@neovim/core Coverity build is fixed now, based on the log of the [latest build](https://api.travis-ci.org/jobs/100058774/log.txt?deansi=true):

    423 C/C++ compilation units (99%) are ready for analysis

(Builds since August reported only 3-6 compilation units.) It appears to be an issue with gcc5--that's why local runs worked for some of us (at least my machine has gcc 4.8). 

@fwalch Currently the bot-ci coverity build is using the default `compiler: gcc` (version 4.6). I tried to [set it to gcc 4.9](https://github.com/justinmk/bot-ci/commit/a883f636a4186617089363b352ba217e5fc0f9a6) but the travis log fails:

    $ gcc-4.9 --version
    /home/travis/build.sh: line 45: gcc-4.9: command not found

Any idea why it doesn't work? I tried deleting the caches also.

**Comment by fwalch** [comment]
@justinmk I think GCC 4.9 simply isn't installed on bot-ci. I opened neovim/bot-ci#82.

**Comment by justinmk** [comment]
Note that the coverity queue is insanely long (118 now, was 127 2 days ago...) so I have no idea when we will see actual results from this. Could be weeks at the current rate.

**Comment by justinmk** [comment]
About 50% of the coverity warnings we have are from `.deps/` (jemalloc, luajit, libuv). I configured coverity to ignore luajit.
