### ISSUE TITLE
global `set commentstring` in syntax/dockerfile.vim

### ISSUE THREAD

**Issue by garlicbreadcleric** [neovim/neovim#31649]
### Problem

https://github.com/neovim/neovim/blob/39781be14baff508efd4f99c11786c4228ea2c8d/runtime/syntax/dockerfile.vim#L38 - shouldn't this be `setlocal`? I think it causes comment plugins (like `mini.comment`) to use wrong comment syntax in non-Dockerfiles sometimes after Dockerfile was opened.

### Steps to reproduce

```
:e Dockerfile
:e package.json
:setglobal commentstring
```
returns `# %s`

### Expected behavior

Dockerfile `commentstring` shouldn't be set globally.

### Nvim version (nvim -v)

0.10.2

### Vim (not Nvim) behaves the same?

yes

### Operating system/version

Linux

### Terminal name/version

Konsole

### $TERM environment variable

xterm-256-color

### Installation

https://github.com/neovim/neovim/blob/master/INSTALL.md#pre-built-archives-2

**Comment by justinmk** [comment]
Should be in ftplugin, paired with `b:undo_ftplugin` https://github.com/neovim/neovim/blob/39781be14baff508efd4f99c11786c4228ea2c8d/runtime/ftplugin/c.vim#L20-L28

Guess it was missed in:
https://github.com/neovim/neovim/commit/2f5b8a009280eba995aecf67d1e8d99b7c72c51c

Same problem exists in Vim: https://github.com/vim/vim/blob/6cc3027e544e4389bd665140511a3d347490b102/runtime/syntax/dockerfile.vim#L38
so please report it to https://github.com/vim/vim

**Comment by clason** [comment]
Related: https://github.com/vim/vim/issues/16083 

But be aware that any change to syntax or ftplugin files needs to go through the maintainer listed at the top of the file.
