### ISSUE TITLE
man.lua: "no manual entry for man"

### ISSUE THREAD

**Issue by tunaflsh** [neovim/neovim#31642]
### Problem

`:Man` command is not working on any entry. For example `:Man man` returns
`man.lua: "no manual entry for man"`

### Steps to reproduce

nvim --clean
:Man man

### Expected behavior

Reads the `man` page into the buffer.

### Nvim version (nvim -v)

0.10.2 Release

### Vim (not Nvim) behaves the same?

no, man plugin is external in vim

### Operating system/version

Windows 11, MSYS2/MINGW64

### Terminal name/version

Windows Terminal

### $TERM environment variable

xterm-256color

### Installation

MINGW Packages

**Comment by justinmk** [comment]
Try the latest development version. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.
