### ISSUE TITLE
UI messages: specify whether `msg_show` event is saved in :messages history

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#31643]
### Problem

If I'm not wrong, in `vim.ui_attach` (with `ext_messages = true`) callback there is no way to determine if the message is added to the history or not. 

So far I felt like I had to decide this on my own in each case but I found `msg_hist_off` global that could be passed the callback. 

https://github.com/neovim/neovim/blob/8ef41f590224dfeea2e51d9fec150e363fd72ee0/src/nvim/insexpand.c#L4601-L4611

### Expected behavior

`msg_hist_off` (or maybe its negation) is available from `vim.ui_attach` callback.

**Comment by luukvbaal** [comment]
The proper place forward this information would be `msg_puts_len():hist->msg_puts_display()`:
https://github.com/neovim/neovim/blob/8ef41f590224dfeea2e51d9fec150e363fd72ee0/src/nvim/message.c#L2137

But can you please elaborate how you intend to use this information? Nvim keeps track of the message history internally, which is forwarded with `:messages`.

**Comment by przepompownia** [comment]
At the moment I have mixed both UI messages and notifications in one history table. There is a table with some kinds of messages not intended to save them in that history. It may not be entirely well thought out, but it is useful for me, independently of rendering `msg_history_show` event somewhere (where contents are passed in `kind` and `content` is `nil` - offtopic). 

https://github.com/przepompownia/msg-show.nvim/blob/507dff8e731965decf83942095865e65423757d3/lua/msg-show/notifier.lua#L262-L274

While such information is not passed to the callback, I have to observe each case or looking into Nvim sources if `msg_hist_off` is enabled then (and manually exclude such kind from the custom history if needed).

**Comment by luukvbaal** [comment]
But what is the point of tracking this in the ext_messages implementation when you intend to follow Nvim's internal history exactly, which can be queried whenever with the `ui_msg_history_show` (even if you do not intend to render it I suppose).

**Comment by przepompownia** [comment]
> But what is the point of tracking this in the ext_messages implementation when you intend to follow Nvim's internal history exactly, which can be queried whenever with the `ui_msg_history_show` event (even if you do not intend to render it I suppose).

Not quite exactly but even if so, I (can) appreciate the order of appearing messages in the custom history, regardless of source (UI or vim.notify). 

`msg_history_show` gives only some subset, which may be useful in some cases (and I'd like to still have `:messages` equivalent regardless of what the merged history contains).

**Comment by luukvbaal** [comment]
Not sure I see the point. Either you use Nvim's internal message history, or you keep track of a different history based on your own heuristic; in both cases this new argument doesn't seem too helpful. Maybe @bfredl can chime in.

Besides, (a custom) `vim.notify` seems redundant in the case of an ext_messages implementation. The implementation can already display messages however it sees fit, and the default `vim.notify()` would route messages to it and display it accordingly (and add it to the history).

**Comment by przepompownia** [comment]
> Not sure I see the point. Either you use Nvim's internal message history, or you keep track of a different history based on your own heuristic; in both cases this new argument doesn't seem too helpful. Maybe [@bfredl](https://github.com/bfredl) can chime in.

Not a big problem to not have such information although it could help to define the default choice for cases that I haven't paid much attention to so far (for example because they happened to me rarely).

> Besides, (a custom) `vim.notify` seems redundant in the case of an ext_messages implementation. The implementation can already display messages however it sees fit, and the default `vim.notify()` would route messages to it and display it accordingly (and add it to the history).

Indeed, I didn't found time to make sure if I really need to override `vim.notify` in my usage. Currently the built-in implementation simply uses `nvim_echo`. One detail that I overlooked is no longer present `title` option.

**Comment by luukvbaal** [comment]
One problem with this is that for truncated messages, there is a disconnect between what is added to the message history and the message emitted with `msg_show`. But I think it would make sense to do away with the message truncation when the message grid is removed (hopefully after #27855), since then the `msg_show` consumer is in a better place to decide whether to truncate a message.

So we could add this now despite that caveat, given that it will be irrelevant once we no longer truncate messages, wait with adding it, or also specify whether a truncated message was emitted...

**Comment by luukvbaal** [comment]
@bfredl wasn't opposed to this so I added it to #31661.
