### ISSUE TITLE
Using `vim.lsp.enable('luals')` in `after/ftplugin/lua.lua` not working

### ISSUE THREAD

**Issue by craigmac** [neovim/neovim#31641]
### Problem

I'd like to put my `vim.lsp.enable()` calls in my `after/ftplugin/*.lua` files, but it doesn't seem to work that way? Not sure if this is intended, maybe the docs could point out where the code snippets it shows should live, if it's intended to only be in users init file?

### Steps to reproduce

In `~/.config/nvim/init.lua`:

```lua
vim.lsp.config['luals'] = {
  cmd = { 'lua-language-server' },
  filetypes = { 'lua' },
  root_markers = { '.luarc.json', '.luarc.jsonc', '.stylua.toml', 'stylua.toml', '.luacheckrc', '.git' },
  settings = {
    Lua = {
      runtime = {
        version = 'LuaJIT',
      },
    },
  },
}
```

In `~/.config/nvim/after/ftplugin/lua.lua`:

```lua
vim.lsp.enable('luals')
```

Check that the server wasn't started with:

```
:=vim.lsp.get_clients()[1].server_capabilities
```

But if we move the `vim.lsp.enable('luals')` into the `init.lua` file, it works.

### Expected behavior

Adding `vim.lsp.enable()` call in `after/ftplugin/*.lua` should be possible

### Nvim version (nvim -v)

0.11.0 commit g38f554e9c4

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

macOS

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

source

**Comment by clason** [comment]
The `enable` call should go into your general config (`init.lua` or `plugin`), _not_ a ftplugin or `FileType` autocommand -- that is too late, since `enable` itself sets up such an autocommand. (You may be thinking of `lsp.start()` which is different and more low-level.)

**Comment by justinmk** [comment]
`vim.lsp.enable('luals')` defines a FileType hander.

`after/ftplugin/*.lua` is called after FileType event triggers.

**Comment by craigmac** [comment]
Ok thanks, I'll close this then!
