### ISSUE TITLE
LSP: incorrect code action expansion for `basedpyright` language server

### ISSUE THREAD

**Issue by Rid1FZ** [neovim/neovim#31655]
### Problem

`basedpyright` is an enhanced version of `pyright` language server which supports code actions which imports any module. The problem is, code actions are expanded incorrectly for imports. I can confirm that this language server works perfectly (even in this scenario) in emacs.

### Steps to reproduce

This is the bare-minimal config which can reproduce this issue

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end

vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	spec = {
		{
			"neovim/nvim-lspconfig",
			config = function()
				local lspconfig = require("lspconfig")
				lspconfig.basedpyright.setup({})
			end,
		},
	},
})
```

with this config, following the given steps will reproduce this issue...
1. Install `basedpyright` from `pip`
2. Open any test python file
3. type `shlex.split("echo hi")` or any other code segment which uses any module, but does not import it
4. hover over the module name in the code segment and run command: `lua vim.lsp.buf.code_action()`. It will give a few code suggestions
5. Select the code action with `import` in details (e.g: `import subprocess`, `import shlex`)

### Expected behavior

The code action expands incorrectly and messes the import (typically the first line of code)

before expansion:
![Image](https://github.com/user-attachments/assets/e5717105-9f37-47cf-9f45-6b179678d41b)

after expansion:
![Image](https://github.com/user-attachments/assets/7d6a59c4-8e2b-4535-969a-d755c3785213)

expected behavior:
![Image](https://github.com/user-attachments/assets/fc42e6bb-aaac-4068-a783-78e81a4516e9)

### Nvim version (nvim -v)

0.10.2 Release

### Language server name/version

basedpyright

### Operating system/version

Fedora 41

### Log file

https://gist.github.com/Rid1FZ/6e4f9f8d419e142ac64e72444460e706

**Comment by glepnir** [comment]
Does `:PyrightOrganizeImports` also ?

**Comment by Rid1FZ** [comment]
@glepnir `:PyrightOrganizeImports` works perfectly fine. If I already have some imports, this commands sorts them nicely...

before `:PyrightOrganizeImports`:
![Image](https://github.com/user-attachments/assets/b6507d89-8584-4e26-8504-d251a069e6b4)

after `:PyrightOrganizeImports`:
![Image](https://github.com/user-attachments/assets/e3b32df2-9921-4473-94cb-672be3f190ba)

**Comment by glepnir** [comment]
nvm i deleted comment.  this is reulst from server 

```
  result = { {
      edit = {
        changes = {
          ["file:///Users/mw/workspace/neovim/test.py"] = { {
              newText = "shlex",
              range = {
                ["end"] = {
                  character = 5,
                  line = 0
                },
                start = {
                  character = 0,
                  line = 0
                }
              }
            }, {
              newText = "import shlex\n\n\n",
              range = {
                ["end"] = {
                  character = 0,
                  line = 0
                },
                start = {
                  character = 0,
                  line = 0
                }
              }
            } }
        }
      },
      kind = "quickfix",
      title = "import shlex"
    }, {
      edit = {
        changes = {
          ["file:///Users/mw/workspace/neovim/test.py"] = { {
              newText = "shlex",
              range = {
                ["end"] = {
                  character = 5,
                  line = 0
                },
                start = {
                  character = 0,
                  line = 0
                }
              }
            }, {
              newText = "from shlex import shlex\n\n\n",
              range = {
                ["end"] = {
                  character = 0,
                  line = 0
                },
                start = {
                  character = 0,
                  line = 0
                }
              }
            } }
        }
      },
      kind = "quickfix",
      title = "from shlex import shlex"
    } }

```

**Comment by glepnir** [comment]
because the order of `apply_text_edits`  if change to this will solve problem. therre is revert by https://github.com/neovim/neovim/pull/29212 and relate  https://github.com/neovim/neovim/issues/29202 https://github.com/neovim/neovim/pull/29877

```diff
diff --git a/runtime/lua/vim/lsp/util.lua b/runtime/lua/vim/lsp/util.lua
index 6bee5bc31..593e11739 100644
--- a/runtime/lua/vim/lsp/util.lua
+++ b/runtime/lua/vim/lsp/util.lua
@@ -338,7 +338,7 @@ function M.apply_text_edits(text_edits, bufnr, position_encoding)
     if a.range.start.character ~= b.range.start.character then
       return a.range.start.character > b.range.start.character
     end
-    return a._index > b._index
+    return a._index < b._index
   end)
```

**Comment by glepnir** [comment]
I think you
