### ISSUE TITLE
Request: Support `F_OK` mode parameter via a string for `vim.uv.fs_access()`

### ISSUE THREAD

**Issue by Crypto-Spartan** [neovim/neovim#31666]
### Problem

[`vim.uv.fs_access()`](https://neovim.io/doc/user/luvref.html#uv.fs_access()) currently requires 2 arguments:

- file path
- mode

for the mode argument, it is possible to pass a string containing "R" or "W" or "X".

`vim.uv.fs_access()` is equivalent to [`access(2)`](https://man7.org/linux/man-pages/man2/access.2.html), which supports the values `F_OK`, `R_OK`, `W_OK`, and `X_OK`. `F_OK` tests for the existence of the file. `R_OK`, `W_OK`, and `X_OK` test whether the file exists and grants read, write, and execute permissions, respectively.

Currently, it's not possible to pass a string to _purely_ check for the existence of a file, which is supported by `access(2)`.

### Expected behavior

My request is to support passing a string parameter (such as "F", for example) for the mode argument in `vim.uv.fs_access()`.

**Comment by Crypto-Spartan** [comment]
While I'm not super familiar with neovim's internals personally, this doesn't seem like it would be too difficult to add. Maybe worth a "good first issue" label?

**Comment by zeertzjq** [comment]
Wrong repository. This issue should go to https://github.com/libuv/libuv or https://github.com/luvit/luv/
