### ISSUE TITLE
Improve usability for search/replace "with confirm" back feature

### ISSUE THREAD

**Issue by kbilsted** [neovim/neovim#31678]
### Problem

when search/replacing using `:s/../../gc` one can do `y`and `n` to replace and skip. if you mistakenly pressed either y or n there is no easy way to go back

### Expected behavior

Introduce a `N` action that will go to the previous substitution and re-ask `y/n/a/ql/..`  

The to easiest support is probably if the user mistakenly pressed `n` then he can do a `N` for back, then `y` to replace.

it would be cool if the reverse situation is also supported - that you accidentally replaced something and you can go back `N`, and undo the replace with `n` which then takes the user forward to the next replace spot

**Comment by justinmk** [comment]
> if you mistakenly pressed either y or n there is no easy way to go back

There are quite reasonable steps to achieve this:

```
<c-c>
u
@:
```

**Comment by kbilsted** [comment]
why not allow `u` during a replace ?
