### ISSUE TITLE
“á” character processed as “Esc” key

### ISSUE THREAD

**Issue by gustavo-hms** [neovim/neovim#3168]
If I type the “á” latin character on terminal neovim, it processes the key combo (´+a on my Brazilian keyboard) as if I would press the “Esc” key, leaving insert mode. It does so in every Linux terminal I’ve tested (konsole, xterm, gnome-terminal). Any other vowel with diacritics works as expected (including éíóúàèìòùüãõ)

**Comment by justinmk** [comment]
What `'encoding'` and `'fileencoding'` are you using?

In Vim (not Neovim), can you do these steps:

- insert `á` character
- with the cursor on `á` in normal mode, press `ga`
- what is the output?

**Comment by gustavo-hms** [comment]
`encoding` is set to utf-8.
`fileencoding` doesn’t seem to be relevant here, since this behaviour is observed even in an empty buffer. Anyway, it’s usually utf-8.

Executing `:%!xdd` as you requested, the output is
```
0000000: c3a1 0a                                  ...
```

**Comment by justinmk** [comment]
@gustavo-hms What `:version` are you using? Can you try with latest?

**Comment by gustavo-hms** [comment]
Ok, I was running version 0.0.0-alpha+201508100001 (commit 7d9472ab1b7dc4eb2bb838fb8febcc7a1aab649d).

I’ve just updated it to version 0.0.0-alpha+201508170110 (commit 14d2a90db984c1a0360727c4d9b8337a689fccec) and it’s still not working.

**Comment by justinmk** [comment]
@gustavo-hms This issue may have been fixed by https://github.com/neovim/neovim/pull/3982. Can you try latest master? (`:version` => `v0.1.2-176-gaf5c34f`).

**Comment by gustavo-hms** [comment]
Sorry for the late reply. It’s now working. Thanks!
