### ISSUE TITLE
UI protocol: mode_info_set.cell_percentage is always 0 in terminal mode

### ISSUE THREAD

**Issue by fredizzimo** [neovim/neovim#31685]
### Problem

https://github.com/neovim/neovim/pull/31562 added proper cursor shape and blink support, but unfortunately `cell_percentage` (in the `mode_info_set` event) is always set to 0, which makes the cursor invisible in GUIs like Neovide.

This was first reported here https://github.com/neovide/neovide/issues/2897

### Steps to reproduce

1. Start neovide
2. Open `:terminal` with a bash shell using the default vertical bar cursor shape
3. Observe that the cursor is invisible

### Expected behavior

Neovim should set `cell_percentage` to something reasonable, for example `25` for the vertical bar and `20` for the vertical bar, like the `guicursor` defaults.

Alternatively, it should be documented that 0 is GUI specific, and that the GUI can choose a suitable value. But in that case, it would probably make sense to set the `guicursor` default to 0 as well.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1399+gd1e00a5f6d

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Neovide 0.13.3

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by gpanders** [comment]
https://github.com/neovim/neovim/pull/31703 sets the default percentages to 25 and 20 for vertical and horizontal, respectively. This isn't configurable tho, it's hard coded.

>Alternatively, it should be documented that 0 is GUI specific, and that the GUI can choose a suitable value. But in that case, it would probably make sense to set the guicursor default to 0 as well.

I think this is worth considering too. As I mentioned in the PR, the escape sequences to set the cursor shape in the terminal can't specify things like "cursor width". So if we ever want this to be configurable, it will have to be configured at the UI level, in which case having a value for "the UI decides the width" would make sense.
