### ISSUE TITLE
LSP: client should respond to "workspace/configuration" with latest (dynamic) config

### ISSUE THREAD

**Issue by andremarianiello** [neovim/neovim#31684]
#### Background

I use lspconfig to configure the lsp client in neovim, and I have run into an issue that I could probably figure out how to work around, but I am not a lua expert and I think there is a good argument that this should be changed in neovim itself, so I am creating this issue for both those purposes.

#### Problem

The issue at hand is how neovim communicates workspace configuration to the LSP server. I know that `vim.lsp.start_client` accepts ` settings` table that will be sent in response to `workspace/configuration` requests from the client. AFAICT this makes neovim always respond to `workspace/configuration` with the same response for the life of the client. If I wanted to change my configuration I can send a `workspace/didChangeConfiguration` notification to the server. However, some languages servers rerequest `workspace/configuration` when receiving those notifications. This causes neovim to send the old initial configuration again, overwrite the updates I asked for.

Now I don't think language servers _should_ be requesting configuration again, since after all they receive it in the didChange notification, but given how the [LSP spec talks about `workspace/configuration`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_configuration) I don't think they _shouldn't_ either. This is the part I'm referring to:

> This pull model replaces the old push model were the client signaled configuration change via an event. If the server still needs to react to configuration changes (since the server caches the result of workspace/configuration requests) the server should register for an empty configuration change

Thus I think it makes sense for neovim to handle both paradigms.

#### Workarounds

For servers that exhibit this problem I am working around it by disabling the `workspace.configuration` capability. This makes all configuration updates happen via didChange notifications instead, which works, but seems...not recommended? Especially since LSP spec says that the pull model is meant to replace the push model.

#### Related
I filed an issue for the Haskell LSP side of things in https://github.com/haskell/haskell-language-server/issues/4469

### Expected behavior

I think it would make sense for the neovim client to respond to workspace/configuration requests using the same configuration that was last sent using workspace/didChangeConfiguration. Rather than updating configuration directly on the server by sending a notification, I think it makes the most sense to update the local version of the configuration first, and the trigger a notification using the updated client configuration. I think this more closely models how LSP expects clients to handle their configuration and the communication of that configuration with the server, but I if proven wrong I can take that proof to the language servers to help motivate changing this behavior on their side of this.

**Comment by mfussenegger** [comment]
You can change the `settings` on the client.

For example, to extend the luals workspace library you can do something like:

```lua
local client = vim.lsp.get_clients({ name = "luals" })[1]
table.insert(
  client.settings.Lua.workspace.library,
  os.getenv("HOME") .. "/.config/nvim/pack/plugins/start/nvim-dap/lua"
)
client:notify("workspace/didChangeConfiguration", { settings = client.settings })
```

This should work for both servers which use the playload from the notification and also those that pull the config via `workspace/configuration`

**Comment by andremarianiello** [comment]
That seems like a good option! I'll see if I can get that working

**Comment by andremarianiello** [comment]
I did manage to get that working. I was stuck for a while when I was accidentally using 0.9.1, but using 0.10.3 worked perfectly. Thanks!
