### ISSUE TITLE
system(): gvfs-open with `echo "foo" >&2` fails (stderr related)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#3169]
I've noticed that `gvfs-open http://www.example.com`, which is called from `xdg-open` fails in Neovim, but not Vim with my setup.

    % gvfs-mime --query x-scheme-handler/http
    Default application for 'x-scheme-handler/http': open-in-running-browser.desktop

`open-in-running-browser` is a script that basically calls a browser, which is `firefox` in this case.

`firefox` is a shell script/wrapper to use [firejail](https://l3net.wordpress.com/projects/firejail/):

    #!/bin/sh
    firejail /usr/bin/firefox "$@"

Calling this script directly from Neovim works, but it is the call via `gvfs-open` that triggers the issue.

TEST CASE:
    1. Setup `gvfs-open` to call a script with `firejail /usr/bin/firefox "$@"`
    2. nvim -u NONE -c 'echo system("gvfs-open http://example.com")'

The page won't be opened.

I've noticed that redirecting stderr to a file or /dev/null will not trigger the issue (but redirecting it to stdout still does):

    nvim -u NONE -c 'echo system("gvfs-open http://example.com 2>/tmp/1")'

When calling it manually, this is the output:

    Reading profile /etc/firejail/firefox.profile                                🐍 ? 
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc
    Parent pid 17817, child pid 17818
    Interface           IP                  Mask                Status              
    lo                  127.0.0.1           255.0.0.0           UP                  
    wlan0               192.168.178.33      255.255.255.0       UP                  
    lxcbr0              10.0.3.1            255.255.255.0       UP                  

    Child process initialized

    (process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

    parent is shutting down, bye...

Where this is stderr:

    % gvfs-open http://example.com >/dev/null
    Reading profile /etc/firejail/firefox.profile
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc

    (process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

I've thought that maybe writing something to stderr in general triggers this issue, but the following works at least:

    nvim -u NONE -c 'echo system("echo stderr >&2")'

firejail 0.9.26-1, but also with 0.9.28-1.
gvfs: 1.24.1-1ubuntu1

**Comment by blueyed** [comment]
Running firejail manually with `--debug` shows this, which might be relevant.

However, `nvim -u NONE -c 'echo system("firejail /usr/bin/firefox http://example.com")'` by itself works.

    % firejail --debug /usr/bin/firefox
    Command name #firefox#
    Found firefox profile in /etc/firejail directory
    Reading profile /etc/firejail/firefox.profile
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc
    Reading profile /etc/firejail/disable-common.inc
    Using the local network stack
    Parent pid 24641, child pid 24642
    Initializing child process
    PID namespace installed
    Mounting read-only /bin, /sbin, /lib, /lib64, /usr, /etc, /var
    Mounting tmpfs on /var/lock
    Mounting tmpfs on /var/tmp
    Mounting tmpfs on /var/log
    Mounting tmpfs on /var/lib/dhcp
    Mounting tmpfs on /var/lib/nginx
    Mounting tmpfs on /var/lib/snmp
    Mounting tmpfs on /var/lib/sudo
    Mounting tmpfs on /tmp/firejail/mnt directory
    Create the new utmp file
    Mount the new utmp file
    Disable /home/www-data
    Disable /home/docker
    Disable /home/nix
    Disable /home/tests
    Disable /home/test
    Disable /home/lost+found
    Disable /sbin
    Disable /usr/sbin
    Disable /bin/umount
    Disable /bin/mount
    Disable /bin/fusermount
    Disable /bin/su
    Disable /usr/bin/sudo
    Disable /usr/bin/xinput
    Disable /usr/bin/strace
    Disable /home/daniel/.ssh
    Mounting tmpfs on /home/daniel/.gnome2_private
    Disable /home/daniel/.gnome2/keyrings
    Disable /home/daniel/.pki/nssdb
    Disable /home/daniel/.gnupg
    Disable /home/daniel/.local/share/recently-used.xbel
    Disable /home/daniel/.adobe
    Disable /home/daniel/.macromedia
    Disable /home/daniel/.thunderbird
    Disable /home/daniel/.config/chromium
    Disable /home/daniel/.config/google-chrome
    Remounting /proc and /proc/sys filesystems
    Remounting /sys directory
    Disable /proc/sysrq-trigger
    Disable /proc/sys/kernel/hotplug
    Disable /sys/kernel/uevent_helper
    Disable /proc/irq
    Disable /proc/bus
    Disable /proc/kcore
    Disable /proc/kallsyms
    Mounting a new /boot directory
    Disable /dev/port
    Initialize seccomp filter
    Blacklisting syscall 165 mount
    Blacklisting syscall 166 umount2
    Blacklisting syscall 101 ptrace
    Blacklisting syscall 246 kexec_load
    Blacklisting syscall 304 open_by_handle_at
    Blacklisting syscall 175 init_module
    Blacklisting syscall 313 finit_module
    Blacklisting syscall 176 delete_module
    Blacklisting syscall 172 iopl
    Blacklisting syscall 173 ioperm
    Blacklisting syscall 167 swapon
    Blacklisting syscall 168 swapoff
    Blacklisting syscall 103 syslog
    Blacklisting syscall 310 process_vm_readv
    Blacklisting syscall 311 process_vm_writev
    Blacklisting syscall 133 mknod
    Blacklisting syscall 139 sysfs
    Blacklisting syscall 156 _sysctl
    Blacklisting syscall 159 adjtimex
    Blacklisting syscall 305 clock_adjtime
    Blacklisting syscall 212 lookup_dcookie
    Blacklisting syscall 298 perf_event_open
    Blacklisting syscall 300 fanotify_init
    Blacklisting syscall 312 kcmp
    Ending syscall filter
    SECCOMP Filter:
      VALIDATE_ARCHITECTURE
      EXAMINE_SYSCAL
      BLACKLIST 165 mount
      BLACKLIST 166 umount2
      BLACKLIST 101 ptrace
      BLACKLIST 246 kexec_load
      BLACKLIST 304 open_by_handle_at
      BLACKLIST 175 init_module
      BLACKLIST 313 finit_module
      BLACKLIST 176 delete_module
      BLACKLIST 172 iopl
      BLACKLIST 173 ioperm
      BLACKLIST 167 swapon
      BLACKLIST 168 swapoff
      BLACKLIST 103 syslog
      BLACKLIST 310 process_vm_readv
      BLACKLIST 311 process_vm_writev
      BLACKLIST 133 mknod
      BLACKLIST 139 sysfs
      BLACKLIST 156 _sysctl
      BLACKLIST 159 adjtimex
      BLACKLIST 305 clock_adjtime
      BLACKLIST 212 lookup_dcookie
      BLACKLIST 298 perf_event_open
      BLACKLIST 300 fanotify_init
      BLACKLIST 312 kcmp
      RETURN_ALLOW
    Save seccomp filter, size 424 bytes
    seccomp enabled
    Droping all capabilities
    User namespace (noroot) installed
    Starting /usr/bin/firefox 
    execvp argument 0: /bin/bash
    execvp argument 1: -c
    execvp argument 2: /usr/bin/firefox 
    Child process initialized

    (process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

    parent is shutting down, bye...

**Comment by blueyed** [comment]
Another observation: there is no output from `echo system("gvfs-open ...")`, although I added an `echo` to stdout and stderr into the shell script called by gvfs-open - but that's also true for Vim.

    nvim -u NONE -c 'echo system("gvfs-open http://example.com")'

I've also noticed that `firejail` in the shell script works in general, e.g. `firejail --debug echo OK \> /home/user/tmp/output` - also google-chrome works.
There seems to be an issue running Firefox in particular in this context.

**Comment by blueyed** [comment]
Reported for firejail at: https://sourceforge.net/p/firejail/tickets/27/

**Comment by netblue30** [comment]
Hi blueyed, firejail author here. I've recently moved to https://github.com/netblue30/firejail

I think, and I might be wrong, that when you start firefox you already have another firefox instance running.

```
$ firejail firefox
Reading profile /etc/firejail/firefox.profile                                
Reading profile /etc/firejail/disable-mgmt.inc
Reading profile /etc/firejail/disable-secret.inc
Parent pid 17817, child pid 17818
Interface           IP                  Mask                Status              
lo                  127.0.0.1           255.0.0.0           UP                  
wlan0               192.168.178.33      255.255.255.0       UP                  
lxcbr0              10.0.3.1            255.255.255.0       UP                  

Child process initialized

(process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

parent is shutting down, bye...
```

By default Firefox keeps only one browser process running. When you start a new Firefox process, it looks for an existing one. If one is found, the new process shuts down, and the existing one opens a new tab or a new window. In this case firejail will also shut down, printing "parent is shutting down, bye...".

**Comment by blueyed** [comment]
@netblue30 
Yes, I have an instance running, but a new tab gets opened then usually:

    % firejail /usr/bin/firefox www.example.com
    Reading profile /etc/firejail/firefox.profile
    Reading profile /etc/firejail/disable-mgmt.inc
    Reading profile /etc/firejail/disable-secret.inc
    Reading profile /etc/firejail/disable-common.inc
    Parent pid 10125, child pid 10126
    Child process initialized

    (process:1): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

    parent is shutting down, bye...

It's also strange that it works in Vim, but not Neovim..

**Comment by netblue30** [comment]
I've seen Firefox opening tabs, and I've seen it opening new windows. It could be based on some environment variables in the second Firefox instance. Anyway, they have an option to force a second instance:
'''
$ man iceweasel
[...]
       -no-remote
              Don't  connect  to a running Iceweasel instance. This option can
              be necessary in conjunction to several  of  the  options  above,
              that won't have any effect when an Iceweasel instance is running
              unless -no-remote is used at the same time.
[...]
'''

**Comment by blueyed** [comment]
@netblue30 
That's not the point.  It also happens for google-chrome, as long there's a profile for it (even an empty one triggers it).

**Comment by netblue30** [comment]
Chromium also enforces a single instance. It will open a new window, however there will be a single process group. Can you do a test without any browser window open?

**Comment by blueyed** [comment]
@netblue30 
There's a difference already between Vim and Neovim: the issue is that Neovim somehow triggers something related to stderr that makes firejail fail..

Something interesting in this regard (although it affects stdin):

Running a command via `:!` appears to handle stdin differently than in Vim, e.g. `:!tig %` starts the pager (instead of the log view because a file is passed), and `:!tig log %` says `tig: Ignoring stdin.`.

**Comment by justinmk** [comment]
For starters, Neovim does not try to fake "interactive" shell with `:!` nor `system()`. You need `:terminal` for that. I don't remember the details but there are some differences with pipes/inheritance as well.

**Comment by netblue30** [comment]
Firejail doesn't look at the terminal. In fact it works fine without a terminal, for example when you run servers from your system init scripts. Same for Firefox (GUI program). The terminal, if there is any to begin with, is passed along by system calls such as system, clone, fork, execv, I don't see how firejail or firefox could fail.

**Comment by blueyed** [comment]
> Firejail doesn't look at the terminal

The main issue with Firejail I am seeing here (and why I have reported it on SF.net initially) is that a `--logfile` option would be useful to debug this - because when redirecting stderr it does not fail anymore.

I guess that Neovim is doing something funky/unexpected with stderr, and that's it's really an issue with Neovim.

This works:

    vim -u NONE -c 'echo system("gvfs-open http://www.example.com")'

This (using Neovim instead) does not work:

   nvim -u NONE -c 'echo system("gvfs-open http://www.example.com")'

This (using strace with Vim) *also* does not work:

    strace -f -o O.vim vim -u NONE -c 'echo system("gvfs-open http://www.example.com")'

This (using Neovim with stderr redirected) does work:

    nvim -u NONE -c 'echo system("gvfs-open http://www.example.com 2>/dev/null")'

(using `strace` with the last one also fails)

(`gvfs-open` is configured to use this script):

    #!/bin/bash
    firejail --debug /usr/bin/firefox "$@"

**Comment by netblue30** [comment]
As I understand your problem, we are discussing at least two different issues here.

1. strace

On most Linux platforms strace cannot run SUID binaries. Try out for example "strace ping 127.0.0.1". All your strace examples are breaking because firejail is SUID binary.You need to be root to run SUID binaries in strace.

2. About redirection:

Try to keep it simple, such as:
```
firejail firefox 2>&1 | tee outfile
```
You don't really need special support in any program to do redirection.

**Comment by blueyed** [comment]
It seems we can take ignore firejail for this issue:

Given the following `firefox` wrapper, `nvim -c 'call system("gvfs-open http://example.com/")'` will fail already:

    #!/bin/sh
    echo "foo"
    exec /usr/bin/firefox "$@"

The `echo` triggers it.

I've thought that it was related to firejail, but using it only triggers writing to `stderr`, but using `echo "foo" >&2` in the wrapper above will also trigger the issue.

Sorry for the confusion!

**Comment by justinmk** [comment]
This seems to be a particular symptom of https://github.com/neovim/neovim/issues/4772#issuecomment-219901492
