### ISSUE TITLE
Support 'keymap' for different modes

### ISSUE THREAD

**Issue by aj3423** [neovim/neovim#31693]
### Problem

With the development of customizable keyboard firmware, more and more people start using different keyboard layouts, such as 'colemak'.

They use different workarounds to solve key conflicts, but even the 'best' workaround is not ideal. For example, 'colemak-dh' users have to use a key combination to do `hjkl` movements, that's two keystrokes for a simple movement, not to mention that, there has to be lots of key mappings, and potential problems like plugin key binding conflicts.

Currently, there is the `set keymap=dvorak`, but it's for Insert mode, not for Normal/Visual... modes. And it's designed for people using regular layout(qwerty) to be able to simulate other layouts, not for people who are already using different layouts(hardware layer). 

### Expected behavior

It would be great if there are more options like `nkeymap`, `vkeymap`, `ckeymap`(command mode), `ikeymap`(as the current `keymap`), or similar options. In that case, the problem can be simply solved by adding two keymaps:

-`set nkeymap=dvorak` 
-`set vkeymap=dvorak` 

Without having to re-map everything, and it's compatible to all plugins.

**Comment by zeertzjq** [comment]
This is `'langmap'`
