### ISSUE TITLE
Undercurl error in zellij in neovim

### ISSUE THREAD

**Issue by Daydreamer-riri** [neovim/neovim#31698]
### Problem

Links issue:
- https://github.com/microsoft/terminal/issues/18312

The description of the issue and some discussions are in the above Issue link. Sorry, I'm not very good at summarizing them, so please check the link for details.

It is important to emphasize that the default $TERM in WSL within Windows Terminal is xterm-256color. Under normal circumstances, this poses no issues, and I can have colored undercurls. However, this does not work in zellij. When I set $TERM to vte-256color, I can see colored undercurls in zellij.

![img](https://private-user-images.githubusercontent.com/70067449/395124885-32cc6c13-72c9-4041-a1c4-b5a55aff9508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTcyNzEsIm5iZiI6MTczNDk1Njk3MSwicGF0aCI6Ii83MDA2NzQ0OS8zOTUxMjQ4ODUtMzJjYzZjMTMtNzJjOS00MDQxLWExYzQtYjVhNTVhZmY5NTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDEyMjkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5N2M5ZjcwNWE5Nzk3NTEwNjFmMWVhMWNjYTRjNTAwZDZiZWY0NDVhMjI1NjM2MGEwZjVjZDRiYWMyODY0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yHf0tv8T28FZUY9AH-Na3jMovSAFM60iLkMKLZt-O44)

### Steps to reproduce

- zellij
- nvim --clean
- input `:Term`
- imput `printf '\e[4:3mUnderlined\n'`

### Expected behavior

You can see the normal colored undercurl.

### Nvim version (nvim -v)

NVIM v0.10.2 Build type: Release LuaJIT 2.1.1713484068 Run "nvim -V1 -v" for more info

### Vim (not Nvim) behaves the same?

no

### Operating system/version

wsl ubuntu 2404

### Terminal name/version

Windows Terminal Preview Version: 1.22.3232.0

### $TERM environment variable

xterm-256color

### Installation

bob

**Comment by justinmk** [comment]
Always test the latest development version before reporting an issue. The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. Check `:version` to confirm the version.

**Comment by justinmk** [comment]
> Sorry, I'm not very good at summarizing them, so please check the link for details.

Nope

**Comment by Daydreamer-riri** [comment]
Hi @justinmk, thank you for your quick reply.  I've tried using the latest nightly version and the problem is still recurring:

![Image](https://github.com/user-attachments/assets/528343ea-1621-434b-8a8a-763235d407d9)
> The left is in zellij.

```
❯ nvim --version
NVIM v0.11.0-dev-1401+g7e1c1ff7fc
Build type: RelWithDebInfo
LuaJIT 2.1.1734355927
Run "nvim -V1 -v" for more inf
```

![Image](https://github.com/user-attachments/assets/d44ea1b3-48ca-4107-9577-c25fc8a01240)

**After set TERM**

![Image](https://github.com/user-attachments/assets/02d42a21-7a42-4550-b735-2fd40b2af032)

**Comment by Daydreamer-riri** [comment]
Hi @justinmk, what is the progress? Can we reopen this issue?

**Comment by glepnir** [comment]
https://github.com/zellij-org/zellij/pull/2678
