### ISSUE TITLE
Inspect command tries to use `vim.hl` which is nil

### ISSUE THREAD

**Issue by UtkarshVerma** [neovim/neovim#31709]
### Problem

When I execute `:Inspect`, I get the following error:

```
Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/_inspector.lua:189: attempt to index field 'hl' (a nil value)
stack traceback:
        /usr/share/nvim/runtime/lua/vim/_inspector.lua:189: in function 'show_pos'
        vim/_defaults.lua: in function <vim/_defaults.lua:0>
```

I think this has to do something with the `vim.hl` -> `vim.highlight` change where `_inspector.lua` is still using `vim.hl`.

### Steps to reproduce

1. `nvim --clean <some lua file>`
2. `:Inspect`
3. Get error

### Expected behavior

Should not fail.

### Nvim version (nvim -v)

0.10.3

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Arch Linux

### Terminal name/version

st

### $TERM environment variable

st-256color

### Installation

Arch repos

**Comment by glepnir** [comment]
already fixed by https://github.com/neovim/neovim/pull/31676
