### ISSUE TITLE
incommand Option Not Available in Neovim 0.10.3 Build

### ISSUE THREAD

**Issue by ans9868** [neovim/neovim#31722]
### Problem

The issue arises after downloading and building Neovim 0.10.3 locally on macOS 14.3.1 (Intel). Despite the build completing successfully without any errors, running Neovim in clean mode (nvim --clean) and checking for the incommand option using :echo exists('&incommand') returns 0. This suggests that the incommand feature, which is expected to be part of the Neovim core since version 0.9.0, is not included in the build. There are no build errors or warnings, and all steps for compiling Neovim from source were followed. I am not sure if I am missing a build flag or a or dependency needed for incommand for MacOs or if it is a bug of some sort.

### Steps to reproduce

1. Downloaded the source code for Neovim 0.10.3 from the official repository.
2. Built Neovim locally using the following commands:
make CMAKE_BUILD_TYPE=Release
sudo make install
3. Verified the Neovim binary:
nvim --version 
Confirmed version 0.10.3.
4. Ran nvim --clean to check for the availability of the incommand option using:
:echo exists('&incommand')
Output was 0.

### Expected behavior

The incommand option should be available by default in Neovim 0.10.3 when built from source, as it is a core feature introduced in Neovim 0.9.0. Running :echo exists('&incommand') should return 1, indicating that the feature is present. 

### Nvim version (nvim -v)

NVIM v0.10.3 Build type: Release LuaJIT 2.1.1713484068

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 14.3.1 

### Terminal name/version

Iterm 3.5.10

### $TERM environment variable

xterm-256color

### Installation

https://github.com/neovim/neovim/releases/tag/v0.10.3

**Comment by zeertzjq** [comment]
It's called inccommand, not incommand
