### ISSUE TITLE
LSP misalignment

### ISSUE THREAD

**Issue by CnsMaple** [neovim/neovim#31721]
### Problem

After version 0.10.1 (excluding 0.10.1, and 0.11.*), if there are non English characters, it means that the lsp definition is misaligned.

### Steps to reproduce

```python
a = 1
print("测试", a)
```

0.10.1 and 0.11.*:
![Image](https://github.com/user-attachments/assets/873408bf-6691-485b-b7be-b0273f1d77c2)

it can match

after 0.10.1 version:
![Image](https://github.com/user-attachments/assets/f9cc6d9b-2499-4739-9d86-55b967a3e9b1)

it can not match

Watching a video, a non English character can cause a misalignment of two positions

https://github.com/user-attachments/assets/e17ea5b8-7af1-487c-ace6-0a0bcece4ceb

### Expected behavior

Normal display.

### Nvim version (nvim -v)

multiple

### Vim (not Nvim) behaves the same?

no

### Operating system/version

win11

### Terminal name/version

wezterm

### $TERM environment variable

don't know

### Installation

scoop

**Comment by glepnir** [comment]
Please describe the problem clearly and with a minimal configuration.  are you using vim.lsp.buf.document_highlight or something?

**Comment by CnsMaple** [comment]
@glepnir 
minimal.lua:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    spec = {
        {
            'neovim/nvim-lspconfig',
            lazy = false,
            opts = {
                servers = {
                    pyright = {
                    }
                }
            },
            config = function(_, opts)
                local lspconfig = require('lspconfig')
                for server, config in pairs(opts.servers) do
                    lspconfig[server].setup(config)
                end
            end
        }
    },
})
```

debug.py:
```python
aaa = 12
print("测试", aaa)
```

1. `npm install -g pyright`
2. `nvim -u minimal.lua debug.py`


explain，Now we have variables with three letters，Why three? Because a non ASCII file occupies 2 bytes, three were used for demonstration purposes.
There are now two non ASCII codes in the first parameter of print.
It causes the last two letters of a three letter variable to be unable to be vim.lpsp.buf.definement, only the first letter at the beginning can be vim.lpsp.buf.definement.

Watch videos:

https://github.com/user-attachments/assets/ebe538b4-a955-4933-bf5e-5a1bfb15be70

Only the first letter can be redirected.

If I remove a non ASCII character, it can function normally:

https://github.com/user-attachments/assets/290d37d7-e6de-46cb-b1a5-1dbc5c9be058


If I use 0.10.1 or 0.11*:

https://github.com/user-attachments/assets/84f69491-6843-4ec7-a299-9491cf497a45

**Comment by CnsMaple** [comment]
I think this is a very serious issue, even if no plugins are installed and only lsp is configured, it will still be like this

**Comment by glepnir** [comment]
seems relate recently position_encoding refactor.

**Comment by CnsMaple** [comment]
nightly version is normal

**Comment by glepnir** [comment]
seems like fixed by https://github.com/neovim/neovim/pull/30929

**Comment by CnsMaple** [comment]
This seems to have been fixed 2 months ago, why is this issue still present in 0.10.2 and 0.10.3

**Comment by clason** [comment]
Because that's not how development works. The master branch will become 0.11 when it is done; patch releases contain only bugfixes that can be backported. (Not every fix can, if it involves or is affected by major feature changes that are never backported.)

**Comment by CnsMaple** [comment]
thanks
