### ISSUE TITLE
Add deb packages to releases

### ISSUE THREAD

**Issue by minhaz5000** [neovim/neovim#31731]
### Problem

Can you provide the deb packages for the release build. Debian repository has outdated version of Neovim. The stable bookworm repo contains outdated version 0.7.2-7 and unstable repo contains version 0.9.5-10. Providing the deb package would help a lot.

### Expected behavior

The releases would provide the deb package for debian or dpkg based system. It would solve the problem of installing it manually.

**Comment by kabylkassymov** [comment]
There's an appimage

**Comment by brianhuster** [comment]
Why don't you use appimage? It works in all Linux distro. 

Or you can also use the snap package.

**Comment by minhaz5000** [comment]
Wouldn't a deb package provide better integration with system. I mean providing a deb would be just running cpack on the build.

**Comment by clason** [comment]
Duplicate. Please search closed issues. (And, no, any deb we would provide would just be a reskinned tarball. We are not distro packagers, so you will not get any deeper system integration.)
