### ISSUE TITLE
The script in `:h compl-autocomplete` doesn't work

### ISSUE THREAD

**Issue by brianhuster** [neovim/neovim#31740]
### Problem

Like in title. More details below

### Steps to reproduce

1. Create a file `repro.lua` with the following content
```lua
local triggers = { "." }
vim.api.nvim_create_autocmd("InsertCharPre", {
	buffer = vim.api.nvim_get_current_buf(),
	callback = function()
		if vim.fn.pumvisible() == 1 or vim.fn.state("m") == "m" then
			return
		end
		local char = vim.v.char
		if vim.list_contains(triggers, char) then
			local key = vim.keycode("<C-x><C-n>")
			vim.api.nvim_feedkeys(key, "m", false)
		end
	end
})
```
2. Open the above file in nvim with repro config `nvim  repro.lua --clean -u repro.lua`
3. Add something to the file, try to use `.` to trigger autocompletion
```lua
vim.
```
4. Now, it is expected that completion popup should show, but it doesn't. However, if I use `Ctrl-x Ctrl-n`, it shows.
5. Let's try running `nvim repro.lua --clean -u repro.vim` instead. The content of `repro.vim` is following
```vim
" repro.vim
let s:triggers = [ "." ]

function! s:autocomplete() abort
	if pumvisible() == 1 || state("m") == "m"
		return
	endif
	let char = v:char
	if index(s:triggers, char) != -1
		call nvim_feedkeys(v:lua.vim.keycode('<C-x><C-n>'), "m", v:false)
	endif
endfunction

autocmd! InsertCharPre <buffer> call s:autocomplete()
```

Now, autocompletion works. 

### Expected behavior

Autocompletion should show up in step 3

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1351+gf9dd682621 Build type: RelWithDebInfo LuaJIT 2.1.1732813678

### Vim (not Nvim) behaves the same?

No, Vim doesn't support Nvim Lua API

### Operating system/version

Kubuntu 24.04.1

### Terminal name/version

konsole 23.08.5 and wezterm 20240203-110809-5046fc22

### $TERM environment variable

xterm-256color

### Installation

Snap

**Comment by zeertzjq** [comment]
You need to source the script after loading the buffer.

**Comment by brianhuster** [comment]
Then I hope the document would be clearer on that. Or maybe can I send a pull request that use the Vimscript above with `<buffer>` instead? Because to me it does the same thing as the Lua code, I mean `<buffer` means "current buffer" too, right?
