### ISSUE TITLE
Enable clint on all files, but ignore existing errors

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3174]
I think it is good idea to enable clint.py on absolutely all files to make it check for all new errors. Errors are determined in the following fashion:

1. `bot-ci` (I guess) runs `clint.py` on all files with `--record-errors=fname.json` and saves the result somewhere.

    Specifically this switch (branch clint-find-new-errors in my repository) is saving all errors to the specified file in the format which is the concat of JSON lists (exactly one per line) `[filename, error_lines, error_category]` where `error_lines` is the error line and its direct neighbours (two of them).
2. In the PR clint.py is run for all files with `--suppress-errors=fname.json` where `fname.json` was generated by the script for the current master. All new errors fail clint travis test. New errors are errors which are not listed in the fname.json. Given how `error_lines` list is defined it would be necessary to modify neighbours once the adjacent line is modified. This definition is used to not depend on line numbers which will definitely be modified by the PR and thus limit problems due to modification to neighbours only. Three lines are used to make the error definition more unique: e.g. there are lines like `int<Space>` which are very common.

Wondering what exactly should be done to use this variant? I have modified clint.py (branch [clint-find-new-errors](https://github.com/ZyX-I/neovim/tree/clint-find-new-errors)), but am not sure what should update existing errors list and where it should be located.

**Comment by justinmk** [comment]
> not sure what should update existing errors list and where it should be located.

You can put it in a `clint/index.html` file here:

https://github.com/neovim/doc/tree/gh-pages/reports

**Comment by ZyX-I** [comment]
@justinmk I would not say converting this file to HTML is a good idea. Or you say that file named `index.html` should be a concat of JSON arrays in place of HTML file?

**Comment by justinmk** [comment]
> Or you say that file named index.html should be a concat of JSON arrays in place of HTML file?

Whatever is easiest.
