### ISSUE TITLE
Feature request: tab-local working directories

### ISSUE THREAD

**Issue by HiPhish** [neovim/neovim#3175]
Vim supports `:cd` for a global working directory and `:lcd` for window-specific working directories. There should be something in between for tabs, like a `:tcd` command.

I am filing this issue for reference while I work on it in my fork. At the moment the necessary variables are implemented and the `:tcd` command works, but other commands mess things up again.

**Comment by fmoralesc** [comment]
> other commands mess things up again.

What other commands?

**Comment by justinmk** [comment]
Just FYI, we're trying to concentrate on getting 0.1 completed. Adding non-essential features is low-priority, because necessary discussions about usability and design can take a long time. Please feel free to continue working on your fork in the meantime, but please don't expect it to be merged soon. Also please make sure to read CONTRIBUTING.md and related docs if you didn't already. Thanks!

**Comment by justinmk** [comment]
Something that would lend strength to this idea is if you emailed vim_dev mailing to get an idea of whether there was a reason this feature wasn't already added, e.g. if there are existing mechanisms that can achieve the goal. Also review todo.txt to see if there was already discussion about it.

**Comment by HiPhish** [comment]
Anything tabs related (`ex_splitview`, `ex_tabnew`, `ex_tabmove`). What is giving me a headache is the way directories are handled. I would have expected it to be encapsulated like
~~~~
struct vim_instance {
	// members...
	char_u *working_directory;
	struct tab_page *tabs;
}

struct tab_page {
	// members...
	char_u *working_directory;
	struct window *windows;
}

struct tab_page {
	// members...
	char_u *working_directory;
}
~~~
Obviously not with these exact names, but you get the idea. Instead everything path-related is handled by libuv which magically happens to know about windows and tabs. I have no clue how `ex_pwd` was able to pick up my new variable and echo it. Or how it knows to echo the local directory of a window instead of the editor.

Because of the magic I don't really know where to hook into.

**Comment by HiPhish** [comment]
> but please don't expect it to be merged soon

No problem, I am in no hurry. And yes, I read all the contributor information, I have been resisting my urge to re-format all the files ;)

**Comment by HiPhish** [comment]
The magic how the tab's local directory is found happens in libuv:
~~~~
int uv_cwd(char* buffer, size_t* size) {
  if (buffer == NULL || size == NULL)
    return -EINVAL;

  if (getcwd(buffer, *size) == NULL)
    return -errno;

  *size = strlen(buffer);
  if (*size > 1 && buffer[*size - 1] == '/') {
    buffer[*size-1] = '\0';
    (*size)--;
  }

  return 0;
}
~~~~

The `getcwd` function is what is returning the path: I used LLDB to insert a typo into the buffer (replace one character with another), it was present before the function call and gone afterwards. This means the working directory of the entire program got changed when I called `:tcd`, the next step in finding out when and how that happened.

**Comment by oni-link** [comment]
Just wondering, would `:windo lcd` be equivalent to your `:tcd`?

**Comment by HiPhish** [comment]
> Just wondering, would `:windo lcd` be equivalent to your `:tcd`?
Great, now you tell me after I have nailed it. But `:tcd` is better because it does not touch the windows, one might want windows to inherit the working directory of their parent tab when moving into another tab. I don't see a purpose in it, but it can be done now.

I'll create a PR for code review, the changes are very minimal, only small insertions, only one function was revamped (`post_chdir`). I don't expect the PR to be merged yet, just tell me if my implementation is clean.

**Comment by HiPhish** [comment]
Pull request is up: #3178

**Comment by pgdouyon** [comment]
I'm confused, Neovim and Vim already have tab local working directories.

If I type `:cd ~/some/dir` in one tab, `:pwd` prints out "~/some/dir" for every window in that tab.  If I change to the next tab with `gt` and then `:pwd` it prints out "~" showing that the two tabs have separate working directories.  Changing back to the original tab, `:pwd` still prints out "~/some/dir" for every window in that tab.

Let me know if I'm confused and this feature request has some additional functionality but it sounds like it's just duplicating the built-in functionality.

**Comment by pgdouyon** [comment]
Accidentally deleted my earlier comment, but ignore it in any case, I found I couldn't reliably reproduce the tab-local working directory after getting it working the first time.  I must have some plugin that randomly changes the working directory without changing it back, either that or the current `:cd` implementation is buggy.  Now I'm wondering why it works in the VimCast though...

**Comment by HiPhish** [comment]
@pgdouyon If I were to take a guess I would say that the bug could lie in the `post_chdir` function, that it sets the local directory for the window regardless of whether you typed `:cd` or `:lcd` making it look like `:cd` was tab-local. In my builds, both the one I use for work and the one I'm working on, `:cd` is global.

That Vimcasts episode had quite a lot of people confused in the comments section, including me. When the feature is merged I'll write Drew an email, he can make an addendum to the episode then.

**Comment by HiPhish** [comment]
Now that my PR has been merged I can close this issue as well.

**Comment by mantognini** [comment]
Is `:tcd` known to not work nicely with sessions, or is it just me not using the proper options? When reloading my sessions, only one working directory is set for all tabs.

**Comment by mhinz** [comment]
@mantognini Nope, doesn't work at the moment. I opened https://github.com/neovim/neovim/issues/6678 for further discussion.

**Comment by mantognini** [comment]
@mhinz Thanks, I'll keep an eye on this new thread then! :-)
