### ISSUE TITLE
tutorials are not installed

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#3176]
We forgot to check this, it seems, on #2351. I just updated neovim-git from AUR, and the tutor files are not installed, causing the `:Tutor` command to fail. Would this be enough to fix this in runtime/CMakeLists.txt? I don't really get how this works.

~~~ diff
file(MAKE_DIRECTORY ${GENERATED_RUNTIME_DIR}/syntax)
file(MAKE_DIRECTORY ${GENERATED_RUNTIME_DIR}/syntax/vim)
+ file(MAKE_DIRECTORY ${GENERATED_RUNTIME_DIR}/tutor)
~~~

**Comment by ZyX-I** [comment]
You need to use the lines near ones running `install_helper`. Specifically `file(GLOB_RECURSE RUNTIME_FILES`.

Also `.ci/common/test.sh`, `install_nvim` function.

**Comment by ZyX-I** [comment]
What you suggest here is doing *absolutely* nothing useful.

**Comment by fmoralesc** [comment]
> What you suggest here is doing absolutely nothing useful.

Sure. As I said, I don't know how this works.
