### ISSUE TITLE
Neovim's automatic background update not working inside tmux

### ISSUE THREAD

**Issue by dot-1q** [neovim/neovim#31760]
### Problem

https://github.com/user-attachments/assets/42f52314-257b-4b13-af86-ec44e90c8723

I was testing the automatic background change introduced in #31350 , but such behavior is not being replicated when inside tmux.

### Steps to reproduce

I'm using: 

- Latest neovim nightly build
- Ghostty 1.0.0
- tmux tmux 3.5a

I stared both neovim (`nvim --clean`) and tmux (no `.tmux.conf` file) with default configurations.

### Expected behavior

I expected the background update to propagate even when inside tmux

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1423+g48c09ed4d9

### Vim (not Nvim) behaves the same?

Doesn't have this behavior

### Operating system/version

macOS 15.2

### Terminal name/version

Ghostty 1.0.0

### $TERM environment variable

xterm-ghostty and tmux-256color when inside tmux

### Installation

nightly build

**Comment by dot-1q** [comment]
If I understand correctly, it's related to tmux, so not really fit as a Neovim issue.
Being tracked here: https://github.com/tmux/tmux/issues/4269

**Comment by dundargoc** [comment]
Closing since a fix has been sent to tmux it seems like.
