### ISSUE TITLE
rpc connection becomes non-responsive after large nvim_buf_set_lines request

### ISSUE THREAD

**Issue by dlants** [neovim/neovim#31793]
### Problem

I'm working on an AI / LLM plugin, written in bun.

I'm starting the bun process via jobstart [code](https://github.com/dlants/magenta.nvim/blob/main/lua/magenta/init.lua#L27)

I'm then using the [bunvim driver](https://github.com/wallpants/bunvim) to drive the neovim process.

When the LLM wants to apply some edits to a file, I do the following:
- make sure the file is open in a buffer
- take the contents of the buffer. Apply the edits (in-memory, in bun).
- create a new scratch buffer, and use nvim_buffer_set_lines [code](https://github.com/dlants/magenta.nvim/blob/main/bun/tools/diff.ts#L128) to populate it.
- use diffthis on the original buffer and the scratch buffer to display the diff.

For smaller files this works fine, however for larger files I am running into a weird issue. Here's a sample RPC log:
```
debug 15:16:18.875
{
  message: {
    OUTGOING_RPC_REQUEST: {
      reqId: 622,
      method: 'nvim_buf_set_lines',
      params: [
        131,
        0,
        -1,
        false,
        [
        ... 600 lines or so
        ]
      ]
    }
  }
}

debug 15:16:18.876
{
  message: { INCOMING_RPC_RESPONSE: { reqId: 621, error: null, result: null } }
}

debug 15:16:18.876
{
  message: {
    OUTGOING_RPC_REQUEST: {
      reqId: 623,
      method: 'nvim_buf_set_option',
      params: [ 49, 'modifiable', true ]
    }
  }
}

debug 15:22:07.323
{
  message: {
    INCOMING_RPC_NOTIFICATION: { event: 'magentaKey', args: [ '<CR>' ] }
  }
}

debug 15:22:07.324
{
  message: {
    OUTGOING_RPC_REQUEST: { reqId: 625, method: 'nvim_get_current_win', params: [] }
  }
}
```
As you can see, reqId 622 never receives a response. Also, no subsequent requests receive responses, even though the bun process is still live, and is still sending requests. Also, the neovim process is able to send notifications, which I still receive on the bunvim side, which tells me the socket, and the bunvim code responsible for receving the notifications is running.

This leads me to believe that the neovim code that's responsible for responding to the rpc requests is the part that becomes busted.

I'm not sure what other monitoring I can do to help understand where this might be breaking. I don't see any error messages in the rpc log, or in neovim :messages.

### Steps to reproduce

I'll try and come up with a test case, but wanted to open the issue to track my thinking/progress and maybe get some advise on how to debug further.

### Expected behavior

The size of the set_lines request shouldn't matter.

### Nvim version (nvim -v)

0.10.3

### Vim (not Nvim) behaves the same?

n/a, using neovim api

### Operating system/version

MacOS 14.6.1

### Terminal name/version

ghostty 1.0

### $TERM environment variable

alacritty

### Installation

brew

**Comment by dlants** [comment]
OK, so a bit of progress. I was able to set up a test to reliably crash it from the bun side, using a large file that I noticed crashed it within the codebase.

https://github.com/dlants/magenta.nvim/blob/main/bun/tools/diff.spec.ts#L69

I also tried just running the nvim_buf_set_lines command with the contents of the same file, which worked fine:

```
function LoadFixture()
  local filename = "bun/test/fixtures/toolManager.ts"
  local file = io.open(filename, "r")
  if not file then return end

  local contents = file:read("*a")
  file:close()

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(contents, "\n"))
  vim.api.nvim_set_current_buf(buf)
end
```

Next I'll try invoking the nvim_buf_set_lines via rpc and reduce from there.

**Comment by dlants** [comment]
OK, I was able to repro without bunvim, using just msgpack

https://github.com/dlants/neovim-mini-repro/blob/main/README.md

**Comment by dlants** [comment]
ahha, tried the same thing with python, and it worked fine. So I think the issue is either with bun or node's msgpack :(

**Comment by justinmk** [comment]
Does the issue go away if you use `@msgpack/msgpack` instead of `msgpackr`? I see that your repro uses `msgpackr`, in node-client we are considering switching to `msgpackr`:https://github.com/neovim/node-client/issues/221 so if you find that it's buggy or poorly maintained, please LMK.

Could the issue be related to this?:

> It appears that msgpackr does not support using 0 as an extension type code. [kriszyp/msgpackr#150](https://github.com/kriszyp/msgpackr/issues/150)

**Comment by dlants** [comment]
The issue turned out to actually be in the bunvim plugin, since it used a Bun.connect socket without realizing that it didn't automatically handle buffering: https://github.com/oven-sh/bun/issues/16076#issuecomment-2566165532
