### ISSUE TITLE
Enter Key Registered Twice after coming out of Command mode

### ISSUE THREAD

**Issue by JordanllHarper** [neovim/neovim#31805]
### Problem

When going into command mode, (optionally) typing a command, and pressing `Enter`, the Cursor will move to a new line in the buffer.

This seems to be an issue with `4fb3b57a19` as this issue is not present in `e00cd1ab4060`.

### Steps to reproduce

1. Open a file in Neovim.
2. Type `:` for command mode.
3. Hit Enter.
4. Observe cursor goes 1 line down.

### Expected behavior

The cursor should remain in place after hitting `Enter`.

### Nvim version (nvim -v)

0.11.0-dev-1444+g4fb3b57a19 commit 4fb3b57a19

### Vim (not Nvim) behaves the same?

no

### Operating system/version

macOS 15.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by gpanders** [comment]
I can repro this on kitty, but not on Ghostty.

**Comment by gpanders** [comment]
Oh this is a bug in kitty, when key events are enabled kitty sends the same escape sequence for both press and release events on the enter key:

```
$ printf '\x1b[>3u' ; kitty +kitten show_key -m unchanged ; reset
Press any keys - Ctrl+D will terminate this program
UNIX		send_text
^M		\r
^M		\r
^M		\r
^M		\r
^M		\r
^M		\r
^M		\r
```

**Comment by gpanders** [comment]
On kitty 0.38 (the latest release as of today), kitty sends only a single event (press) for the enter key, even when key events are enabled. This addresses this particular issue, but is itself another problem.

**Comment by gpanders** [comment]
Closing since this is a kitty bug which is fixed in their latest release.
