### ISSUE TITLE
Mapping <LeftRelease> does nothing

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#3182]
Ubuntu-GNOME 15.04
Gnome-terminal
NVIM 0.0.0-alpha+201508151511
nvim -u NONE

I tried
:map \<LeftRelease> :echo "hello"\<CR>

But when I release the left mouse button nothing happens. In plain VIM included with the distribution the mapping does trigger.

**Comment by bfredl** [comment]
Also affects builtin actions on mouse release, such as selecting a window by clicking (and not dragging) the statusline  (as detecting click-without-drag relies on release event).

**Comment by bfredl** [comment]
@tarruda will this be fixed in the next TUI refactor ?

**Comment by tarruda** [comment]
> @tarruda will this be fixed in the next TUI refactor ?

:+1:

**Comment by sach1t** [comment]
This was fixed with pull request #4873 which is already merged into master. I just tried it out right now to make sure and it does print "hello" now.
