### ISSUE TITLE
":Tutor" don't work with precompiled binaries for *Ubuntu

### ISSUE THREAD

**Issue by DarthBlack** [neovim/neovim#3186]
I'm using the Launchpad repository for *Ubuntu users. Then I'm typing in ":Tutor" in normal-mode I only get the message "No tutorial with that name found".

**Comment by justinmk** [comment]
What `:version`? I don't know when the ubuntu repo is updated.

**Comment by DarthBlack** [comment]
`nvim --version` give me that it's compiled Aug 16 0735.

**Comment by fwalch** [comment]
Please update Neovim from the PPA, should be fixed with the latest version.
