### ISSUE TITLE
Not an editor command: Tutor when run with -u NONE

### ISSUE THREAD

**Issue by ajpaulson** [neovim/neovim#3187]
with even a simple nvimrc `:Tutor` runs as expected, but with `nvim -u NONE` it responds with `Not an editor command` - Is the default nvim runtimepath correctly set when `-u NONE`?

**Comment by ajpaulson** [comment]
Update: with `nvim -u NONE` the `runtimepath` does include `/usr/local/share/nvim/runtime` which is where `tutor` is located and sourced from.

Even using a *blank* nvimrc works in correcting this.

**Comment by Pyrohh** [comment]
I don't think this is a bug. `:Tutor` is implemented as a regular plugin, so I think this behaviour is to be expected.

> Even using a blank nvimrc works in correcting this.

What about with no `nvimrc`, but not using `-u NONE`?

**Comment by justinmk** [comment]
It works with `nvim -u NORC`. Plugins (e.g. netrw) do not work with `-u NONE`, even in Vim.

**Comment by ZyX-I** [comment]
@Pyrohh 

1. Since `Tutor` is a regular plugin with `-u NONE` this behaviour is expected. One needs to use `-u NORC`.
2. *Not* including `/usr/local/share/nvim/runtime` with `-u NONE` *is* a bug because it should be the default. But this is a separate issue.
