### ISSUE TITLE
synIDattr(id, 'fg#') does not returns the hex code but the color name

### ISSUE THREAD

**Issue by regnat** [neovim/neovim#3189]
Support for the `synIDattr` function while running neovim with true colors has been added by #3005, but according to [the documentation](http://neovim.io/doc/user/eval.html#synIDattr%28%29), `synIDattr(id, 'fg#')`, `synIDattr(id, 'bg#')` and `synIDAttr(id, 'sp#')` should return the hex codes of the corresponfing colors and not their names.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/4851
