### ISSUE TITLE
msgpack-rpc vim_command doesn't move to normal mode

### ISSUE THREAD

**Issue by sschaef** [neovim/neovim#3191]
If nvim is in insert mode and `vim_command` is sent with argument `:help`, the help page is opened but the insert mode is not left. It is not possible to edit anything though, therefore no mistakes can't be made. Leaving insert mode manually is nevertheless annoying.

**Comment by ZyX-I** [comment]
If you do the following actions in Vim it would exhibit the same behaviour:

    function Test()
        help
    endfunction
    imap a <C-r>=Test()<CR>
    " Type ia

    autocmd CursorHoldI * :sos: 
    " Enter insert mode and wait.

. I think that these problems have similar root.

**Comment by tarruda** [comment]
Insert mode needs to aware of vimscript, this patch should fix the problem(@ZyX-I can you verify?):

```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index 427623e..251c38f 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -504,6 +504,7 @@ edit (

   old_indent = 0;

+  buf_T *insert_buf = curbuf;
   /*
    * Main loop in Insert mode: repeat until Insert mode is left.
    */
@@ -619,6 +620,9 @@ edit (
     if (c == K_EVENT) {
       c = lastc;
       queue_process_events(loop.events);
+      if (should_exit_insert_mode(insert_buf)) {
+        return false;
+      }
       continue;
     }

@@ -864,6 +868,11 @@ doESCkey:

     case Ctrl_R:        /* insert the contents of a register */
       ins_reg();
+      if (should_exit_insert_mode(insert_buf)) {
+        // ins_reg can execute arbitrary vimscript via the expression register
+        // and consequently switch the buffer
+        return false;
+      }
       auto_format(FALSE, TRUE);
       inserted_space = FALSE;
       break;
@@ -8375,3 +8384,9 @@ static char_u *do_insert_char_pre(int c)

   return res;
 }
+
+static bool should_exit_insert_mode(buf_T *insert_buf)
+{
+  return insert_buf != curbuf;
+}
+
```

The `should_exit_insert_mode` function needs to be updated with any condition that requires exiting insert mode(right now I can only think of switching buffers).

**Comment by justinmk** [comment]
This is a feature of `vim_command`. Isn't it _useful_ to be able to execute ex-commands remotely without affecting the current mode? If one wants to force normal mode for some reason, `nvim_input("<C-\\><C-N>")` can be used.
