### ISSUE TITLE
"Segmentation fault" when opening directory that do not own

### ISSUE THREAD

**Issue by genkimarshall** [neovim/neovim#3194]
I can't seem to find this being reported anywhere else. I would guess this is very low priority, but thought I should report because: (A) It seems like undesired behavior that could instead give a warning message, or at least a reasoning as to what happened. and (B) It might be part of some other issue.

The apparent issue: attempting to open a directory whose contents you don't have read access to with neovim exits with a seg fault.

```sh
$ nvim /root/
"/root/" is a directorySegmentation fault (core dumped)
$ sudo nvim /root/
# Opens nvim, like expected.
```

I tried `vim /root/` (normal `vim` version 7.4), and it at least continued to open `vim`, with an error at the bottom: `"/root/" Illegal file name` which is not the most ideal error message but at least more useful, and more along the line of expected behavior IMHO.

OS: Arch Linux x64
`nvim --version`: `0.0.0-alpha+201508151511 (compiled Aug 15 2015 21:52:01)`

Please let me know if I should provide any other details.

**Comment by justinmk** [comment]
Probably the same as https://github.com/neovim/neovim/issues/3164 .

**Comment by genkimarshall** [comment]
Ah, sorry, I should've been able to find that, it does seem to be the same thing. Thanks.
