### ISSUE TITLE
Status of Windows support in install docs

### ISSUE THREAD

**Issue by techtonik** [neovim/neovim#3195]
I am fail to see if Neovim can be used on Windows. It will be nice if installation docs at https://github.com/neovim/neovim/wiki/Installing-Neovim mentioned current status. In particular:

1. Are there any binaries to play with
2. Does it compile on Windows using MinGW or other free toolchain
3. Does it have a native port to VS, i.e. what is the status of #1749

**Comment by justinmk** [comment]
Added a Windows section: https://github.com/neovim/neovim/wiki/Installing-Neovim#windows

> Does it compile on Windows using MinGW or other free toolchain

Yes, though I'm not sure if AppVeyor is building them at present.

> what is the status of #1749

#810 is where the progress is. #1749 has a checklist that also tracks all known items.

**Comment by techtonik** [comment]
@justinmk great! Just what is needed.
