### ISSUE TITLE
":silent loadview" does not suppress errors

### ISSUE THREAD

**Issue by brunobeltran** [neovim/neovim#3196]
As mentioned (and maybe forgotten) in Issue #2194, nvim does not respect a request to "silently" perform a command. In particular, with a nvim at HEAD installed and a blank .nvimrc, the command 

``` vim
silent loadview
```

will generate the output

```
E484: Can't open file /home/$USERNAME/.nvim/view/~=+$FILENAME=
```

In Vim, the behavior is to ignore a missing file whether or not `silent` is specified. This breaks the suggestion documented under `:help loadview` (e.g. http://neovim.io/doc/user/starting.html#:loadview).

Is there a workaround for this (besides the obvious hack of just checking for the existence of the view file, which only applies to this particular usage of the word `silent`)?

Another easy way to reproduce this but is to open stock neovim and type `:silent !echo hello`

The correct behavior here is to print nothing (and, in vim, possibly jumble the screen, forcing a manual redraw with `:redraw!` or `<c-l>`).

In neovim, the word "hello" is actually printed (although the manual redraw is still required.

**Comment by justinmk** [comment]
The issue title seems a bit broad.

**Comment by brunobeltran** [comment]
Doesn't seem so to me. It's one specific keyword, `silent` which is buggy.

**Comment by justinmk** [comment]
What I mean is, are there are other cases where `:silent` is not respected? `:silent echo 'hi'` works as expected, as well as `:silent edit <file>`.

**Comment by brunobeltran** [comment]
Not on my box, and I just built head.

**Comment by brunobeltran** [comment]
Strange, actually, after waking up this morning, I can't reproduce the bug except for commands of the form

`:silent! !shell_command_with_output`

For these commands, the shell output is displayed. Then again, it's not clear to me anymore if this is a bug or intended. 

w.r.t. my other complaints, it looks like I forgot the `!` in my `loadview` commands before, since Vim incorrectly did not require it. 

If `:silent! !echo 'hello'` is supposed to print `hello`, then I should just close the issue. Otherwise, you're right, the title should be made more specific.

**Comment by Cypher1** [comment]
I'm having this as well with

`au BufRead * silent loadview`

**Comment by mhinz** [comment]
I'm not even sure what's the problem here. `:loadview` throwing an error if a file can't be found makes sense to me. To silence errors, use `:silent!` instead.

`:silent !echo foo`? What is that supposed to do? Filtering stdout? What's the use case for this?

`:silent term` makes even less sense to me, it opens an interactive terminal emulator after all.

**Comment by Cypher1** [comment]
The problem is that silent isn't silencing the error.

**Comment by mhinz** [comment]
You mean `silent!`, right? `:silent` silences everything but errors.

**Comment by Cypher1** [comment]
Yes. Also doesn't work for silent!
Note: this is different behavior to vim which is why it causes trouble.

The work around for shortcuts is to use the very nasty:

:execute "try\n    loadview\ncatch\nendtry"

Which correctly silences errors.

**Comment by ZyX-I** [comment]
@Cypher1 It does not silence errors. It ignores exceptions, *transforming errors into exceptions* in process. Difference may be seen if you have some code after a error: e.g.

```VimL
redir => g:s | silent! execute 'echo xxx_nonexistent_var_xxx | echo 42' | redir END
echo g:s
```

will yield two errors (E121 about not existing variable and E15 about invalid expression) and 42.

```VimL
redir => g:s | try | execute 'echo xxx_nonexistent_var_xxx | echo 42' | catch | endtry | redir END
echo g:s
```

will yield nothing because E121 was transformed into an exception (and thus not printed and not captured by `:redir`), E15 ignored and `echo 42` not run because unlike errors, exceptions stop execution.

**Comment by Cypher1** [comment]
That may be, but I am in favor of it acting in the same way as vim. This
change is pretty annoying for :loadview

**Comment by johnmcdowall** [comment]
Experiencing the same issue with a snippet that sets the iTerm title when entering a buffer: 

```
" Set the title of the Terminal to the currently open file
set title
function! SetTerminalTitle()
    let titleString = expand('%:t')
    if len(titleString) > 0
        let &titlestring = expand('%:t')
        " this is the format iTerm2 expects when setting the window title
        let args = "\033];".&titlestring."\007"
        let cmd = 'silent !echo -e "'.args.'"'
        execute cmd
        redraw!
    endif
endfunction

autocmd BufEnter * call SetTerminalTitle()
```

This code executes fine in Vim, but in nvim you get an annoying terminal bell, and the status line jumps up and down temporarily displaying the command output.

**Comment by hagabaka** [comment]
`au BufRead * silent loadview` suppresses the error messages for me now.

**Comment by tartley** [comment]
I used to use `:silent` in Vim to prevent 'grep' output being shown (instead I merely want it to populate the quickfix window) Nowadays in Neovim, my grep output is also shown, with the additional wrinkle that this causes screen corruption that requires a Ctrl-L redraw.

Apologies if this scenario is muddying the waters - I appreciate it is different from the issue's original scenario and is complicated by the inderection through vim's 'grep' command.

**Comment by justinmk** [comment]
I'm confused by the various comments here. Are these requests for breaking compatibility with Vim, or are they bug reports about regressions? In Vim, `:silent grep ...` is not silent at all, and it's even more weird because it requires CTRL-L in some cases. Neither is `:silent !grep`.

**Comment by tartley** [comment]
Beg your pardon if I muddied the waters. It appears you are right and my memory was misleading me. I fired up Vim and :silent does not suppress the output of grep. I could have sworn it used to work that way for me, but perhaps I am just wrong.

**Comment by nikolavp** [comment]
OK so basically loadview in vim doesn't report an error if the file is not found? What I had to do is to change

```viml
silent loadview
```
to
```viml
silent! loadview
```

**Comment by justinmk** [comment]
This was changed in 9b1c9393709a to fix a coverity warning. Not to mention, it's rather dodgy to  silently fail if the file can't be opened. 

Using `:silent!` instead of :`silent` is a completely reasonable approach that lets the user decide, while still being able to get feedback if `:loadview` fails unexpectedly.
