### ISSUE TITLE
True colors not available in terminal mode

### ISSUE THREAD

**Issue by mhartington** [neovim/neovim#3199]
Appears that even if your terminal supports true colors and you've enabled them in neovim, terminal mode in neovim doesn't display correctly.

Normal zsh in Iterm2
<img width="1056" alt="screen shot 2015-08-19 at 7 37 46 am" src="https://cloud.githubusercontent.com/assets/2835826/9355283/c913fdbc-4645-11e5-8557-3c5d34d628f6.png">

Terminal emulation in Neovim (with true colors enabled in my nvimrc)
<img width="1138" alt="screen shot 2015-08-19 at 7 37 29 am" src="https://cloud.githubusercontent.com/assets/2835826/9355284/cc2acc10-4645-11e5-9a49-8ac308ed850b.png">

Is there something else I have to add? Or is not supported in libvterm?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/2571

**Comment by mhartington** [comment]
Ah, alright thanks.
