### ISSUE TITLE
Output control key codes nonfunctional

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#3200]
Settings like `'t_ZH'` and `'t_SI'`, which respectively define the control sequence to output italic text and change the shape of the cursor, can be `:set` (that is, no error is thrown), but have no effect, and `:set t_ZH="\e[3m"` returns `E846: Key code not set: t_ZH`.

This is in tmux inside xterm, with full support for that key code (`echo -e "\e[3mHello, world\e[0m"` works fine in a shell).

I'm using `NVIM 0.0.0-alpha (compiled Aug 18 2015 16:06:52)` in `Ubuntu 15.04`, and this feature works in Vim.

**Comment by justinmk** [comment]
We don't support setting termcap codes from within Neovim at the moment. This feature was removed.

The idea is that users shouldn't need to do this, but *if* users want to continue to fiddle with this stuff, *and* there is a simple way to set termcap/terminfo (via a shell command perhaps), I don't see why would shouldn't let them.

**Comment by qstrahl** [comment]
So do I understand correctly that Neovim does not currently support bold/italic/etc text at all? Or is there some way I should configure my terminal/environment to get Neovim to realise the features are there?

**Comment by justinmk** [comment]
It should work automatically. I think it is discussed in previous issues .

**Comment by qstrahl** [comment]
It doesn't work automatically.

**Comment by justinmk** [comment]
I gathered.

**Comment by qstrahl** [comment]
Could you point me toward some way I could go about figuring out why it
doesn't?

**Comment by qstrahl** [comment]
I'm not clear on the status of this issue. Is this a known issue? Is this a non-issue? Is there something I could be doing to help debug/resolve?

**Comment by tarruda** [comment]
@qstrahl We have temporarily removed the termcap options from nvim. This was done to simplify the effort of isolating the UI layer from the core(where the UI layer can be implemented as a terminal UI or a graphical UI).

Eventually these options will be restored(once I manage to isolate them from the core), but for now the only way to customize terminal codes is to write a custom terminfo file. [Here's](https://github.com/neovim/neovim/issues/2048#issuecomment-78045837) an example of how to do it.

Answering your question:

> So do I understand correctly that Neovim does not currently support bold/italic/etc text at all? Or is there some way I should configure my terminal/environment to get Neovim to realise the features are there?

Yes, Neovim supports bold, italic... as long as your terminal supports it and you have installed a correct terminfo for your terminal

**Comment by justinmk** [comment]
> Here's an example of how to do it.

It's on the wiki as well.
https://github.com/neovim/neovim/wiki/Troubleshooting#my-ctrl-h-mapping-doesnt-work

**Comment by qstrahl** [comment]
Okay, thanks for the clarification; the issue must be with my terminal configuration then.
