### ISSUE TITLE
Show progress indicator of job_control jobs

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#3201]
Is there any way to show an indicator to let the user know that there is a job running asynchronously?. In my case, the process does not return anything until it has finished so I cannot rely on the output being returned by the process

Thanks!
A

**Comment by tarruda** [comment]
I'm not sure I understand your requirements. Do you need to let the user know if there's a job you started still running? If so, all you need is to properly set the "on_exit" callback when calling `jobstart`.

**Comment by pwntester** [comment]
Thanks for the quick response! Im writing a plugin that runs a a scan of the code on user command and uses job_control to run it asynchronously. What I wanted was to show a moving indicator in the status bar (something like the moving |/-\|/-\ spinner) while the job is running. I can call a function to do that and stop it on the on_exit callback like you proposed. The problem I have is how to run a function every n seconds to redraw the indicator without blocking nvim, but I guess thats a regular vi issue. I will see if I get it working otherwise, will just print a static message.

Thanks again,
A

**Comment by tarruda** [comment]
To make this kind of scenario easier, we would need to expose libuv timer API to vimscript so you can asynchronously run callbacks after certain intervals. Right now you could get around it by setting up a separate job that outputs something after regular intervals and use it to drive a spinner, here's an example:

```vim
let s:spinner = {}
let s:chars = ['|', '/', '-', '\']
let s:index = 0
function! s:spinner.on_stdout()
  call setline(1, s:chars[s:index])
  let s:index = (s:index + 1) % len(s:chars)
endfunction

let s:idle = {}
function! s:idle.on_exit()
  call jobstop(s:spinjob)
endfunction

let s:spinjob = jobstart('while true; do echo 1; sleep 0.2; done', s:spinner)
let s:idlejob = jobstart('sleep 5', s:idle)
```

**Comment by justinmk** [comment]
Just to mention, we have an issue for the timers feature: https://github.com/neovim/neovim/issues/1404

But there should be a design discussion and proposal before starting work on that. I also targetted it for the 0.3. milestone, but there is no rush to do it, we can push it back once we re-evaluate milestones after completing 0.1.

**Comment by pwntester** [comment]
Thanks, that worked great!
