### ISSUE TITLE
API: pub/sub events without autocmds

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3205]
One advantage of having an event publish/subscribe feature in the API, which does not marshall through `autocmd`, is that binary data could be worked with, without needing intermediate conversion:
https://github.com/neovim/neovim/issues/74#issuecomment-132890580

**Comment by lewis6991** [comment]
With Lua autocmds that do allow binary data, is there any need for this? Or this is mainly targeted for RPC?

**Comment by lewis6991** [comment]
Lua autocmds can handle binary data.

**Comment by justinmk** [comment]
Yes, avoid Vimscript "typeval" conversion is now possible with Lua event (autocmd) handlers. Autocmds are the central *interface* for editor events, but its legacy plumbing can be skipped or improved without designing a new interface: https://github.com/neovim/neovim/issues/19156
