### ISSUE TITLE
differences between vim and neovim in python lists

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#3212]
Hi

It seems that vim and neovim differs on the list indexing, at least when appending

vim.current.buffer.append("test", 10) will be inserted on different one line above in neovim. I guess one starts counting in 0 and the other one in 1

Cheers,
A

**Comment by justinmk** [comment]
You didn't save how many lines existed in buffer.

**Comment by pwntester** [comment]
The issue affects any non empty buffer with any number of lines as long as you insert the new text somewhere in the middle of the existing text.

Im currently using this wrapper to make my plugin compatible with vim/neovim:

```
def _insert_into_buffer(lines, pos):
  if vim.eval("has('nvim')") == '0':
    vim.current.buffer.append(lines, pos)
  else:
    vim.current.buffer.append(lines, pos-1)
```

All calls to vim.current.buffer.append() in my plugin have been replaced with _insert_into_buffer() calls

**Comment by fwalch** [comment]
`:python import vim; vim.current.buffer.append("a", 0)`

In vim (7.4.778):

```
a
(empty line)
```

In nvim (105a72eabc6f74195b6319471344148726683b9d):

```
(empty line)
a
```
