### ISSUE TITLE
Aborted when opening a dir and a file inside it.

### ISSUE THREAD

**Issue by ivegotasthma** [neovim/neovim#3216]
Hello,

I looked through the issues to see if there is something similar and #3194 looked like it however I am accessing a folder that I own. I have no problem opening the folder and exiting out but when I open a file inside of it and on close out neovim aborts.

This is the message when neovim aborts.

    nvim: /home/ico/Code/Repositories/neovim/.deps/build/src/libuv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.
    Aborted (core dumped)

A short demo.
![gif to show actions](https://i.imgur.com/okjMtRu.gif)

This is the backtrace from gdb.

    (gdb) run
    Starting program: /home/ico/.local/bin/nvim 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    nvim: /home/ico/Code/Repositories/neovim/.deps/build/src/libuv/src/unix/core.c:209: uv__finish_close: Assertion `handle->flags & UV_CLOSING' failed.

    Program received signal SIGABRT, Aborted.
    0x00007ffff6d285f8 in raise () from /usr/lib/libc.so.6
    (gdb) backtrace
    #0  0x00007ffff6d285f8 in raise () from /usr/lib/libc.so.6
    #1  0x00007ffff6d29a7a in abort () from /usr/lib/libc.so.6
    #2  0x00007ffff6d21417 in __assert_fail_base () from /usr/lib/libc.so.6
    #3  0x00007ffff6d214c2 in __assert_fail () from /usr/lib/libc.so.6
    #4  0x00000000006067a0 in uv__finish_close (handle=<optimized out>) at /home/ico/Code/Repositories/neovim/.deps/build/src/libuv/src/unix/core.c:209
    #5  uv__run_closing_handles (loop=0x905200 <loop>) at /home/ico/Code/Repositories/neovim/.deps/build/src/libuv/src/unix/core.c:259
    #6  uv_run (loop=0x905200 <loop>, mode=UV_RUN_DEFAULT) at /home/ico/Code/Repositories/neovim/.deps/build/src/libuv/src/unix/core.c:326
    #7  0x00000000006047a4 in loop_close (loop=0x905200 <loop>) at ../src/nvim/event/loop.c:79
    #8  0x00000000005c8260 in event_teardown () at ../src/nvim/main.c:172
    #9  0x0000000000452e3a in mch_exit (r=0) at ../src/nvim/os_unix.c:180
    #10 0x00000000005c932e in getout (exitval=0) at ../src/nvim/main.c:831
    #11 0x00000000004bff2d in ex_quit (eap=0x7fffffffdd20) at ../src/nvim/ex_docmd.c:5635
    #12 0x00000000004b8798 in do_one_cmd (cmdlinep=0x7fffffffe3d0, sourcing=0, cstack=0x7fffffffdf30, fgetline=0x45747d <getexline>, cookie=0x0)
    at ../src/nvim/ex_docmd.c:2195
    #13 0x00000000004b53a8 in do_cmdline (cmdline=0x0, fgetline=0x45747d <getexline>, cookie=0x0, flags=0) at ../src/nvim/ex_docmd.c:621
    #14 0x00000000004efd14 in nv_colon (cap=0x7fffffffe520) at ../src/nvim/normal.c:4080
    #15 0x00000000004e9178 in normal_cmd (oap=0x7fffffffe5e0, toplevel=true) at ../src/nvim/normal.c:912
    #16 0x00000000005c9095 in main_loop (cmdwin=0, noexmode=0) at ../src/nvim/main.c:747
    #17 0x00000000005c8aae in main (argc=1, argv=0x7fffffffe8c8) at ../src/nvim/main.c:534
    (gdb) 

And neovim's version.

    NVIM 0.0.0-alpha+201508220101 (compiled Aug 22 2015 12:38:24)
    Commit: 105a72eabc6f74195b6319471344148726683b9d
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/ico/Code/Repositories/neovim/build/config -I/home/ico/Code/Repositories/neovim/src -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include/luajit-2.0 -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/home/ico/Code/Repositories/neovim/.deps/usr/include -I/usr/include -I/home/ico/Code/Repositories/neovim/build/src/nvim/auto -I/home/ico/Code/Repositories/neovim/build/include
    Compiled by ico@arch

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
    For differences from Vim, see :help vim-differences

       system vimrc file: "$VIM/nvimrc"
         user vimrc file: "~/.nvimrc"
     2nd user vimrc file: "~/.nvim/nvimrc"
          user exrc file: "~/.exrc"
      fall-back for $VIM: "/home/ico/.local/share/nvim"

**Comment by teto** [comment]
It occured to me as well while editing /proc/net/unix if that can help tracking the behavior.

**Comment by Mike-Now** [comment]
I'm having similar issue which does not occur in the original vim. The minimal .nvimrc reproducing the issue:


     function! CopyToCb()
        if executable('xsel')
        :call system("xsel -ib", getreg('+'))"
        else
        echo 'You must install xsel to persist clipboard'   
        endif
    endfunction

    nnoremap <silent><C-z> :call CopyToCb()\|suspend<cr>

**Comment by justinmk** [comment]
Assuming this was fixed by https://github.com/neovim/neovim/pull/3309 , please report if it's still an issue.
