### ISSUE TITLE
Start in nvim terminal if not already in an nvim terminal from zshrc?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3219]
Is it possible to somehow detect in zshrc if zsh is running inside an nvim terminal, then if not in a terminal start nvim with a terminal?

**Comment by tarruda** [comment]
Add this to the end of your zshrc?
```zsh
if [[ -z $NVIM_LISTEN_ADDRESS ]]; then
	exec nvim +term
fi
```

**Comment by trusktr** [comment]
That worked, thanks @tarruda.

**Comment by ZyX-I** [comment]
@trusktr Note the side effect: previously you could do `zsh -ic 'command'` from outside the nvim. Now `zsh -ic 'command'` will run `nvim +term`, but not `command` once used outside of the environment with `NVIM_LISTEN_ADDRESS` set.
