### ISSUE TITLE
a problem with a mapping

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3220]
i have this mapping in my .vimrc
    imap < expr >< silent >< cr>     neocomplete#mappings#close_popup() .
         \ "\<Plug>(neosnippet_jump_or_expand)"

and it's work great when i presse enter in neocomplete popup it expand neosnippet   but the problem is that < cr> will not work only for that that will not do a return line in insert mode

**Comment by justinmk** [comment]
Please use vi.stackexchange.com for general user questions.
