### ISSUE TITLE
Invalid documentation for job* VimL functions

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3222]
I see that https://github.com/ZyX-I/neovim/blob/1d7a10714f90a7eb525d5c8d89a2967306e15744/runtime/doc/eval.txt#L1873-L1876 references functions `job_*`, while https://github.com/ZyX-I/neovim/blob/1d7a10714f90a7eb525d5c8d89a2967306e15744/runtime/doc/eval.txt#L4062 references functions `job*`. The latter also has more functions then referenced in the former.

Also note the invalid description: while other functions have `{signature}>--{return type}>--{description}`, these ones have `{signature}>--{description}`. (`>--` represents field separator.)

**Comment by justinmk** [comment]
Underscores in user-facing functions are discouraged. Though we should not be extending viml much more.
