### ISSUE TITLE
nnoremap <C-h> <C-w>h not moving to the left split. Other movements are fine.

### ISSUE THREAD

**Issue by harshasrisri** [neovim/neovim#3231]
I request to help me debug this issue as no one else seems to be facing it. 
My split movement mappings are thus:
```
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
```
The j,k,l mappings work just fine as expected. However, <C-h> just moves the cursor one position left in the current split.
The same vimrc is used for vim and nvim. All the mappings work fine on regular vim.

**Comment by justinmk** [comment]
We're working on it. Solution could be a year away though. https://github.com/neovim/neovim/issues/2048

Thanks for the report.
