### ISSUE TITLE
Copying using  "Shift+Left mouse" copies some spaces which are not there in the original text

### ISSUE THREAD

**Issue by Mariappan** [neovim/neovim#3233]
Hi,

My setup is xterm running in VNC from remote server.

For copying text from inside vnc and my laptop, I usuall use shift+left mouse button to select which will copy the contents to the clipboard and paste in laptop.
Copying (using left mouse) works in vim and neovim

But in neovim, some extra whiteline characters(spaces)(which are not actually present in the original copied text) are also getting copied from the source text.

![nvimissue](https://cloud.githubusercontent.com/assets/947300/9459846/b494464e-4b1d-11e5-9d11-a13028c71ee6.png)

I am not seeing this issue in vim. Both vim and neovim uses the same config rc file.

clipboard settings which are automatically setting:
Vim => clipboard=autoselect,exclude:cons|linux
Nvim => clipboard=

PS. If I use putty to connect to the server and copying using the left mouse, I am not facing this issue.

**Comment by bfredl** [comment]
I can reproduce with `nolist` so it is not related to `list`. I would guess that the rewritten TUI driver sometimes emits an extra space before NL, but it is strange then that you won't see it in PuTTY.
(Of course, the issue could be seen as we not implementing `autoselect` yet, so that Shift+Left copying wouldn't be necessary in the `xterm` case)

**Comment by abelosorio** [comment]
I have the same issue here.

I'm using Linux Debian 8.7 with Neovim 0.1.7 on a **local gnome-terminal** console:

```
 NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-jWN9lg/neovim-0.1.7/build/config -I/build/neovim-jWN9lg/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-jWN9lg/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-jWN9lg/neovim-0.1.7/build/include
Compilado por root@x3650

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "/usr/share/nvim"
```
![image](https://cloud.githubusercontent.com/assets/12383055/25336852/c25cb4d2-28cf-11e7-83c4-7fd3bf7f25b0.png)

I got the same issue with both `set mouse=c`, `set mouse=a`, or `set mouse=`.

There is any way to change this behaviors by now?

Thanks

**Comment by justinmk** [comment]
> local gnome-terminal  ... There is any way to change this behaviors by now?

Yes, use the clipboard. Visual-select the text, then `"y+`. `:help clipboard`. (Please don't post clipboard usage issues here, ask on https://vi.stackexchange.com or read the docs)

**Comment by abelosorio** [comment]
Mmmm... In my Debian I can use the clipboard (CTRL + C / CTRL + V) or Mouse selection (Selection / Middle click).

I want to use the Selection / Middle click as I always did in VIM.

Thanks

**Comment by cyb70289** [comment]
Well, looks this issue will never be fixed. After turning to neovim for two weeks, I guess I have to turn back to vim8.

**Comment by justinmk** [comment]
Did anyone here try `nvim -u NONE`?

The actual cause of this problem is in Vim as well: when the `Normal` highlight group is defined Vim (and Nvim) will write text to what is otherwise treated as "negative space".

Try it in "Vim 8":

    vim -u NONE -N +":hi Normal ctermbg=black ctermfg=white"

There's nothing that Vim nor Nvim can do about this.

> I am not seeing this issue in vim. Both vim and neovim uses the same config rc file.

@Mariappan in both Vim and Nvim, please check:

    :verbose hi Normal

**Comment by abelosorio** [comment]
Any workaround?

**Comment by justinmk** [comment]
Workaround is to clear the ctermbg for the Normal highlight group:

    :hi Normal ctermbg=NONE

**Comment by abelosorio** [comment]
Sorry @justinmk but I tried your workaround without any luck. Anyway, I don't enough knowledge of nvim or vim to know if I'm using another setting that overrides the ones you've sent.

**Comment by justinmk** [comment]
@abelosorio Does `nvim -u NONE` have the issue or not?

**Comment by abelosorio** [comment]
No, it doesn't. Running `nvim -u NONE` works fine (though without any plugin).

**Comment by justinmk** [comment]
As mentioned above, please check:

    :verbose hi Normal

**Comment by abelosorio** [comment]
OK @justinmk. I don't fully understand why, but I executed that command as you said and disable my color schema (since it was setting the hightlight values).

I'll continue reading if the problem is the plugin I'm using for the color schema (https://github.com/ayu-theme/ayu-vim) of if it's something else.

Thanks for the help!

**Comment by abelosorio** [comment]
Not sure if it helps to others, but setting
```
hi! Normal guibg=NONE
```
*after* setting the `colorscheme` fix the problem to me.

**Comment by cyb70289** [comment]
Thanks @abelosorio , @justinmk , "hi Normal ctermbg=NONE" fixes my issue.
