### ISSUE TITLE
Cursor stops blinking

### ISSUE THREAD

**Issue by teto** [neovim/neovim#3257]
I am using urxvt and latest head with parameter `URxvt*cursorBlink: true`.

When I open neovim, it starts with the _vim-startify_ homepage and the cursor keeps blinking. As soon as I open a file, in normal mode the cursor does not blink while in insert mode it blinks. I tried the same with vim and it keeps blinking at all times: 
My neovim configuration holds:

```
"let $NVIM_TUI_ENABLE_TRUE_COLOR=0   
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1             
```

I tried disabling NVIM_TUI_ENABLE_CURSOR_SHAPE but the behavior was the same.

**Comment by justinmk** [comment]
To disable `NVIM_TUI_ENABLE_CURSOR_SHAPE` you must _undefine_ it. Setting it to `0` is not enough. We should probably go ahead and change this.

**Comment by teto** [comment]
even when undefining (more exactly commenting, I don't set it as the env var) , problem rests the same.

**Comment by amerlyq** [comment]
I have completely opposite problem. I have in my config for urxvt 9.21
```
URxvt*cursorBlink:          false
```
But cursor blinks in insert mode nevertheless. How to stop this madness?

**Comment by llpamies** [comment]
I have a similar problem in gnome-terminal.

First time I start neovim, cursor blinks in normal mode. I get in&out insert mode, and when back to normal mode the cursor doesn't blink anymore.

**Comment by romgrk** [comment]
@llpamies & others: that is hardcoded https://github.com/romgrk/neovim/tree/cursor_blink

**Comment by amerlyq** [comment]
Hard-code terminfo patching and absence of user-space options? Pity.
It remembers me ```dwm``` and ```st``` -- if you want configure -- DIY and recompile:)

**Comment by justinmk** [comment]
@amerlyq As mentioned above, the current approach is temporary (hence this issue remains open).

**Comment by SageEx** [comment]
@justinmk Any idea when this will be implemented ?

**Comment by romgrk** [comment]
@justinmk is there any specification/previous work around this or still `TODO`?
If still `TODO`, is there any place where this particular issue or more general UI issues can be discussed?

**Comment by justinmk** [comment]
This is low priority. Eventually `t_*` or some equivalent will be provided which allows fiddling with terminal settings.

I don't understand the other question: issue tracker exists for discussion; issues exist to track progress. If issue doesn't have activity it means there is no progress.

**Comment by nhooyr** [comment]
For me, from the moment I start neovim (i have it set to blink in iterm2), the cursor is not blinking until i enter insert or replace mode. Unsetting `NVIM_TUI_ENABLE_CURSOR_SHAPE` and the cursor stops blinking everywhere in neovim.

**Comment by jamessan** [comment]
#5556 is working on fixing this.

**Comment by teto** [comment]
I can now configure 'guicursor' to fix it.
