### ISSUE TITLE
Add missing depencie for lua interpreter in wiki

### ISSUE THREAD

**Issue by GuillaumeSeren** [neovim/neovim#3258]
Hi there,
I was about to compile neovim for a new machine (Debian) and after following the 'Build Prerequisites' of the wiki,
I get an error on my 'cmake ..' 

The 'lpeg' lua package is required for building Neovim
CMake Error at CMakeLists.txt:286 (message):
  A suitable Lua interpreter was not found

So I think it should be added in the wiki to help people to build.

I try to fix by installing lua5.2, lua-lpeg, and lua-messagepack (by luarocks), but still got this error:
-- [/usr/bin/lua] The 'MessagePack' lua package is required for building Neovim
CMake Error at CMakeLists.txt:286 (message):
  A suitable Lua interpreter was not found

I successfully built it before, so maybe it is a new dependency ?

Guillaume.

**Comment by justinmk** [comment]
I saw this too, but I think it's just a timeout issue with the downloads. Try again after `rm -rf build/ .deps/`.

**Comment by GuillaumeSeren** [comment]
@justinmk yes it is true.

After cleaning build and .deps I got a new missing dep libuv
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find LibUV (missing: LIBUV_LIBRARY LIBUV_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibUV.cmake:92 (find_package_handle_standard_args)
  CMakeLists.txt:204 (find_package)

I will try to install libuv0.10-dev to test.

**Comment by GuillaumeSeren** [comment]
Yes by installing libuv0.10-dev and cleaning, I have a new error 
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Msgpack (missing: MSGPACK_LIBRARY MSGPACK_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMsgpack.cmake:46 (find_package_handle_standard_args)
  CMakeLists.txt:207 (find_package)

**Comment by fwalch** [comment]
It should not be required to install libuv, as it is downloaded as part of the build process.

What is the output of `make distclean && make deps`? `make deps` should download and build all dependencies, subsequent `make nvim` (or `make`) should then be able to build Neovim.

**Comment by GuillaumeSeren** [comment]
Yes make deps did get missing dependencies, I missed that part before.

Now cmake is ok, I will build.

Do you think to it should be added in the wiki ?

**Comment by fwalch** [comment]
I think this is already in the wiki. On [Building Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim), it says: "Build Neovim by running make." I'm not sure where you read to use `cmake ..` directly. It is mentioned [here](https://github.com/neovim/neovim/wiki/Building-Neovim#controlling-the-build-for-third-party-dependencies-1588), but there it also explains that you need to build the dependencies first.

**Comment by GuillaumeSeren** [comment]
I should have read it better !

Thank you for helping me.

Guillaume.
