### ISSUE TITLE
Incorrect floating-point zero division results

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3263]
Check the following script:

    echo (1.0/0.0) (-1.0/0.0) (0.0/0.0)

. In Vim this will echo `inf -inf -nan`. In NeoVim this echoes `inf inf inf` for some reason. To get -inf and nan one will need to use `-(1.0/0.0)` and `(1.0/0.0-1.0/0.0)` respectively.

**Comment by oni-link** [comment]
See  f6ace9962d95eb12236083871154c1501f02c556:
```diff
diff --git a/src/eval.c b/src/eval.c
index b164912..d5ed1b1 100644
--- a/src/eval.c
+++ b/src/eval.c
@@ -4275,7 +4275,7 @@ eval6 (
         else if (op == '/') {
           /* We rely on the floating point library to handle divide
            * by zero to result in "inf" and not a crash. */
-          f1 = f1 / f2;
+          f1 = f2 != 0 ? f1 / f2 : INFINITY;
         } else   {
           EMSG(_("E804: Cannot use '%' with Float"));
           return FAIL;


```

**Comment by ZyX-I** [comment]
@oni-link But this change is not correct: division by zero may yield something that is not `inf`. This change is not listed in `vim-diff`, even though `0.0/0.0` resulting in NaN is described in `:h printf-f`.

Ref @tarruda

**Comment by ZyX-I** [comment]
Also note that this change makes comment outdated.

**Comment by oni-link** [comment]
I think this change was made because some sanitizer (-fsanitize=undefined?) complained, but I noticed too that this was different behaviour compared to vim.

**Comment by justinmk** [comment]
In case it matters, I often see this warning on one of my VMs:

```
/home/ubuntu/neovim/src/nvim/eval.c:3982:34: warning: ‘f2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
           f1 = f2 != 0 ? f1 / f2 : INFINITY;
```

**Comment by steveno** [comment]
@justinmk Looking at the code in `eval.c` I wonder if that's a false positive. Perhaps if we cleaned up that section with curly braces around the `if ... else ... endif` statements some of those messages might go away.
