### ISSUE TITLE
:unlet does not remove environment variables

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3265]
```
unlet $VAR
```

yields “E488: Trailing characters” instead of removing the environment variable.

**Comment by justinmk** [comment]
For reference, vim_dev discussion: https://groups.google.com/d/msg/vim_dev/IIrDqVvdpOo/Q2nuImgZEtEJ

**Comment by justinmk** [comment]
fixed /07fbdf4acc3b15ff97acb
