### ISSUE TITLE
:term closes current tab

### ISSUE THREAD

**Issue by gonzaloserrano** [neovim/neovim#3276]
Hey everyone,

I checked the issues opened with the `term` label and some of them are about buffers and splits so maybe this is duplicated but here it goes:

open two tabs: `nvim -u NONE -p first second`
execute `:term ls`
-> the first tab is closed

More info:

Built in OSX with homebrew with `brew reinstall --HEAD neovim`
```
NVIM 0.0.0-alpha+201508221348 (compiled Aug 23 2015 13:42:08)
Commit: be29de1fa2b2dde54f4e43bc12d8bb7a46845308
```

**Comment by justinmk** [comment]
@gonzaloserrano what if you `set hidden` first?

**Comment by gonzaloserrano** [comment]
Hi @justinmk, thanks for the quick response, i get the same behaviour.

**Comment by justinmk** [comment]
Actually, if you do this with Vim:

    vim -u NONE -p first second

then `:bdelete`, both tabs are closed. This is because both tabs are showing the same buffer and there are no other buffers to switch to.

**Comment by gonzaloserrano** [comment]
So this means that you can't use `:term` with tabs i guess, which makes it useless to me because i use tabs all the time.

I was using first `:!` but i was adviced to change to `:term` because it supported color codes but i guess i will need to go back to it and see it without colors.

Well, thanks anyway for your help!

**Comment by justinmk** [comment]
Vim acts the same way _for regular files_. Unless files are also useless to you, I don't follow your reasoning. 

A workflow adjustment could solve your issue. To get a simlar workflow as with `:!`, _currently_, the workaround is this:

    :tabnew|te ls

But we do need to polish a few rough edges around terminal workflow.

**Comment by justinmk** [comment]
We may end up modifying the interactive case of `:!` to use terminals:

https://github.com/neovim/neovim/issues/2765#issuecomment-135205937

This would then allow you to use `:!` as you are used to.

**Comment by gonzaloserrano** [comment]
Sorry, i think i didn't express it correctly, due to my ignorance in vim/neovim internals.

My use case in vim is the following:

- i open a bunch of files in tabs (i have even aliased `vi` to `vi -p`)
- since i use git, i have some maps that execute git commands to the current file/tab (?) like git log -p or git diff
- i vim i had the maps with `:!` but since in neovim i did not have colors, i was adviced to use `:term`. But we have seen that closed the tab i'm editing, which you say is the standard behaviour.

Hope i explained it properly and thanks again for your time.

**Comment by ZyX-I** [comment]
> But we have seen that closed the tab i'm editing, which you say is the standard behaviour.

You are misusing the “tab” term. It is not *closing* any tab, it opens terminal in the current window, effectively replacing the current buffer in the current window. Without `set hidden` or `setlocal bufhidden=hide` this buffer is unloaded (“close” term does not apply to buffers: it may be hidden, unloaded and wiped out, all terms are linked in `:h 'bufhidden'`).

With `set hidden`, `hide term …`, `setlocal bufhidden=hide` buffer becomes hidden. Closing the terminal by default closes the current window, just like closing any other buffer. To overrule this you need to *first* switch to the old buffer and *then* close the terminal. There are plugins which do this for you: e.g. [bufkill](http://www.vim.org/scripts/script.php?script_id=1147) which I use. In this case you need to <s>close terminal</s> wipe out terminal buffer with `:BW`: this plugin tracks which buffers were viewed in the current window and on `:BW` it first switches to previous buffer.

---

Note: `vi -p first second third` does *not* open tabs named first, second and third. It opens *buffers* with such name and three *unnamed* (tab pages have no name, only identifier) tab pages which have three unnamed (for the same reason) (one per tab) windows which display buffers first, second and third. Tab pages have *absolutely nothing* to do with opened files, they are simply collection of windows, which are viewports for buffers, but buffers exist even when no viewports are linked to them.

Never think that `-p` switch makes Vim behave like some other editors which have tabs==buffers, this is wrong.

**Comment by justinmk** [comment]
>  vim i had the maps with :! but since in neovim i did not have colors, i was adviced to use :term. 

Again, as I said above, the current replacement for `:!` is:

    :tabnew|te ls

but https://github.com/neovim/neovim/issues/2765#issuecomment-135205937 may obviate that.

**Comment by gonzaloserrano** [comment]
Hey @ZyX-I thanks for your complete answer. Of course you are totally right!

I just didn't know much about vim/neovim internals or that a tab was a buffer so when `:term` is executed it substitutes the current buffer/tab etc so when it closes the tab buffer is already closed.

I will use @justinmk approach and wait for `:!` to support ANSI escape sequences as stated in https://github.com/neovim/neovim/issues/2765 to move to that.

Thanks guys!

**Comment by justinmk** [comment]
> map <c-g> :tabnew|te git lp %<cr>

You must use `<bar>` instead of `|` in mappings:

    map <c-g> :tabnew<bar>te git lp %<cr>

**Comment by gonzaloserrano** [comment]
Thanks for the tip! 
In the end i'm adding a `%` after `tabnew` like this:
```
map <c-d> :tabnew %<bar>te diffwrapper %:p<cr>
map <c-g> :tabnew %<bar>te git lp %<cr>
```

**Comment by ZyX-I** [comment]
> I just didn't know much about vim/neovim internals or that a tab was a buffer so when :term is executed it substitutes the current buffer/tab etc so when it closes the tab buffer is already closed.

Buffer is *not* closed. Tab is *not* buffer. `:e foo` “hides” the current buffer and opens buffer `foo`. Depending on `&hidden` and `&bufhidden` option “hides” may mean hiding, wiping out, deleting or unloading (last is the default, many people make hiding the default) but `:term` does not do anything different from `:e` regarding the matter. Without plugins like bufkill tabpage is closed when terminal buffer is wiped out, but this behaviour is again not different from `:e foo` and then doing `:bwipeout` (more specifically, tabpage is closed when attempting to close the last window in the tab page and when the current buffer is wiped out using one of the built-in commands current window is closed as well, except when it is the last one).

Also this is not “internals”. This is one of the basic user-facing concepts, constantly misunderstood because nearly nobody reads `:h windows-intro` and almost all other software assigns one tab exactly one file.

If you install bufkill and use `:BW` for closing terminal window (possibly via the `<CR>` mapping) you will get old buffer again without closing the tab window. But if you need to switch back and forth from terminal buffer it is better to open it in another window (using `tabnew` is one of the variants: you cannot open new tab page without opening a new window) because navigation based on buffers is not very convenient.

**Comment by wejrowski** [comment]
I'm using the new tab approach, although I'm wondering.. is there a way to, on closing that term tab, to revert to the last buffer? otherwise I go to the tab to the right =/ ..slightly obnoxious.

**Comment by justinmk** [comment]
@wejrowski A small hack is to prefix `:tabnew` with `-1` (or just `-`) so that the tab opens to the left of the current tab. Currently vim/neovim doesn't have a "previous tab" concept though I would really like to add it.

    :map <c-g> :-tabnew %<bar>te git lp %<cr>

**Comment by wejrowski** [comment]
Hmm sneaky. Exactly what I wanted, thanks!
