### ISSUE TITLE
msgpack not found error

### ISSUE THREAD

**Issue by varun06** [neovim/neovim#3277]
Hi,

I setup neovim today and was able to fix other things apart from this error that I get when I launch nvim. 

<pre>
2015/08/31 11:24:26 [error @ forward_stderr:333] 41515 - Channel 1 stderr:   File "/Library/Python/2.7/site-packages/neovim/__init__.py", line 9, in <module>
    from .api import DecodeHook, Nvim, SessionHook
  File "/Library/Python/2.7/site-packages/neovim/api/__init__.py", line 9, in <module>
    from .nvim import Nvim, NvimEr
2015/08/31 11:24:26 [error @ forward_stderr:333] 41515 - Channel 1 stderr: ror
  File "/Library/Python/2.7/site-packages/neovim/api/nvim.py", line 5, in <module>
    from msgpack import ExtType
ImportError: No module named msgpack
</pre>

I checked and I have msgpack in pip but it is names as msgpack-python. Please help

**Comment by Shougo** [comment]
You should check it in python command.

```
import msgpack
```

I think msgpack package is not installed correctly.

**Comment by varun06** [comment]
Yup, you were right @Shougo. The packages msgpack and trollious were there but pip had some issues. uninstall/install helped and now everything working smoothly.

Thanks.
