### ISSUE TITLE
Update documentation for t_SI and t_EI

### ISSUE THREAD

**Issue by jpalmer** [neovim/neovim#3279]
Neovim doesn't support setting t_SI and t_EI to change the cursor shape in insert / normal modes.

It is mentioned that in the FAQ, you must use 
    
    :let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1

but `:help t_SI`  should also suggest that this setting doesn't do anything

**Comment by justinmk** [comment]
I believe we plan to add back the `t_` functionality. Not sure how much time we can spend updating docs which will later need to be un-updated. There are dozens of these `t_` settings...
