### ISSUE TITLE
vim_input changed?

### ISSUE THREAD

**Issue by rogual** [neovim/neovim#3282]
Hi, it seems that since https://github.com/neovim/neovim/commit/ccdeb91e1206f38773664979bf03694213a2ba80 the expected protocol for calling vim_input has changed.

I'm developing a GUI and ever since that commit my vim_input calls have been behaving weirdly. (Details: https://github.com/rogual/neovim-dot-app/issues/112)

Looking at the Python client I'd hazard a guess that I'm supposed to start sending calls to this function as RPC notifications rather than requests? Is that right?

Forgive my msgpack ignorance, but why is this necessary? (If it is!) Aren't all msgpack-rpc calls async? Shouldn't clients be able to make calls in blissful ignorance of how Neovim handles them internally?

Thanks!

**Comment by rogual** [comment]
More details:

- Only happens with `set showcmd` on

- Getting some strange redraw requests from Neovim to draw the showcmd area. On pressing `[` (when I have bindings set that start with [), Neovim gives me these redraw requests:

    ["cursor_goto", [45, 109]]
    ["put", ["["], ["~"], ["@"], ["ý"]]
    ["cursor_goto", [0, 0]]

    ["visual_bell", []]
    ["cursor_goto", [45, 109]]
    ["put", [" "], [" "], [" "], [" "]]
    ["cursor_goto", [0, 0]]

**Comment by justinmk** [comment]
@equalsraf have you seen this in neovim qt?

**Comment by rogual** [comment]
Doing some more debugging — it seems `vgetc` is returning -25597, though I'm not sure if this indicates a bug.

**Comment by rogual** [comment]
`plain_vgetc` called here: https://github.com/neovim/neovim/blob/master/src/nvim/normal.c#L773

Result passed to `add_to_showcmd` here: https://github.com/neovim/neovim/blob/master/src/nvim/normal.c#L782

**Comment by equalsraf** [comment]
@justinmk I'm not seeing any particular issue like this here, leader keys seem to work ok. Bindings that start with `@` or '[' seem ok too.

@rogual lets try to reduce this into a minimal example. What specific binding is failing for you? Does it fail with -u NONE?

**Comment by rogual** [comment]
Yes, this still happens with -u NONE as long as you `set showcmd`.

It looks like the bindings that fail are any user-defined multi-key bindings, e.g. `nmap [x something`. Built-in bindings like `gj` or `C-w l` are unaffected unless you add a user binding with the same prefix, at which point that prefix starts exhibiting the bad behaviour.

**Comment by rogual** [comment]
Might be worth mentioning that I'm using the `--embed` flag and communicating with nvim via stdin/stdout.

**Comment by equalsraf** [comment]
Here is what I tried so far

- `nmap @z dd`
- `nmap [z dd`
- `nmap <Leader>z dd`
- `nmap gjz dd`
- `nmap <C-w>z dd`

All of these work for me.

I forgot to ask earlier, what is vim_input() returning for each case? Maybe the Neovim buffer is full and the input is not added to the queue.

Just in case - are you doing anything specific for function calls with the ASYNC/DEFERRED attribute?

**Comment by tarruda** [comment]
The ASYNC attribute is for internal use, it is an  accident that its being
exposed to the metadata

**Comment by justinmk** [comment]
Assuming this a confirmed bug then.

**Comment by tarruda** [comment]
> Assuming this a confirmed bug then.

All I meant is that the ASYNC attribute is leaking to the metadata, but it should not be the cause of bugs. `vim_input` should still be safe to call at any time.

> Looking at the Python client I'd hazard a guess that I'm supposed to start sending calls to this function as RPC notifications rather than requests? Is that right?

It is safe to call it as a msgpack-rpc request(the python client does it)

> Forgive my msgpack ignorance, but why is this necessary? (If it is!) Aren't all msgpack-rpc calls async? Shouldn't clients be able to make calls in blissful ignorance of how Neovim handles them internally?

It is not safe to handle most msgpack-rpc API calls in certain states, especially those that execute vimscript. #3029 improved this but I still need to manually enable arbitrary events at some input-handling paths(nvim handles msgpack-rpc events when waiting for input).

`vim_input` is one of the exceptions, as it is always safe to call this function no matter which state nvim is in. Since this is one of the few function required by UI clients, this delay(or the "deferred events" fix) should not affect them.

@rogual do you think you could try reproducing this bug with a lua functional test? This patch should give you a functional test tempate:

```diff
diff --git a/test/functional/ui/input_spec.lua b/test/functional/ui/input_spec.lua
index 81af908..ca9b9a7 100644
--- a/test/functional/ui/input_spec.lua
+++ b/test/functional/ui/input_spec.lua
@@ -1,4 +1,5 @@
 local helpers = require('test.functional.helpers')
+local Screen = require('test.functional.ui.screen')
 local clear, execute, nvim = helpers.clear, helpers.execute, helpers.nvim
 local feed, next_message, eq = helpers.feed, helpers.next_message, helpers.eq
 local expect = helpers.expect
@@ -38,9 +39,35 @@ describe('mappings', function()
     check_mapping('<a-c-s-up>', '<c-s-a-up>')
     check_mapping('<a-s-c-up>', '<c-s-a-up>')
   end)
+
+  describe('with showcmd', function()
+    it('ok', function()
+      local screen = Screen.new()
+      screen:attach()
+      feed('ihello<esc>')
+      screen:snapshot_util({}, true)
+      screen:expect([[
+        hell^o                                                |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+        ~                                                    |
+                                                             |
+      ]])
+    end)
+  end)
 end)

 describe('input utf sequences that contain CSI/K_SPECIAL', function()
+  before_each(clear)
   it('ok', function()
     feed('i…<esc>')
     expect('…')
```

The screen.lua file has more documentation on the format of screen functional tests(plus there are plenty of examples)

**Comment by rogual** [comment]
I have a theory that https://github.com/neovim/neovim/pull/3413 has fixed this.

**Comment by rogual** [comment]
It did!

**Comment by justinmk** [comment]
@rogual Awesome, thanks for followup!
