### ISSUE TITLE
Add message if runtime not found.

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#3283]
Follow-up to #2977. From https://github.com/neovim/neovim/pull/3159#issuecomment-137245616 (@justinmk):

> In the case where provider/clipboard.vim _and_ doc/version7.txt are not found, there should be a different (silent) hint in :messages. That can be a different PR though, it needs #1802.

**Comment by justinmk** [comment]
covered by https://github.com/neovim/neovim/issues/2977
