### ISSUE TITLE
How can I use the NeoVim logo?

### ISSUE THREAD

**Issue by jerryling315** [neovim/neovim#3285]
What is the CC?

**Comment by fwalch** [comment]
From the website:

> The Neovim logo by [Jason Long](http://twitter.com/jasonlong) is licensed under the [Creative Commons Attribution 3.0 Unported License](http://creativecommons.org/licenses/by/3.0/)

What this means is explained on the Creative Commons license page, which is linked above.

**Comment by jerryling315** [comment]
Thanks
