### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by jianjin** [neovim/neovim#3286]
brew install neovim --HEAD
==> Installing neovim from neovim/homebrew-neovim
==> Cloning https://github.com/neovim/neovim.git
Updating /Library/Caches/Homebrew/neovim--git
==> Checking out branch master
==> Downloading https://github.com/libuv/libuv/archive/v1.7.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libuv-1.7.2.tar.gz
==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--msgpack-1.0.0.tar.gz
==> Downloading http://luajit.org/download/LuaJIT-2.0.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--luajit-2.0.4.tar.gz
==> Downloading https://github.com/keplerproject/luarocks/archive/0587afbb5fe8ceb2f2eea16f486bd6183bf02f29.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--luarocks-29.tar.gz
==> Downloading https://github.com/mauke/unibilium/archive/v1.1.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--unibilium-1.1.4.tar.gz
==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea19aa898968eede19e19603.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libtermkey-19603.tar.gz
==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libvterm-7088.tar.gz
==> Downloading https://github.com/jemalloc/jemalloc/releases/download/3.6.0/jemalloc-3.6.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/neovim--jemalloc-3.6.0.tar.bz2
==> Building third-party dependencies.
==> cmake ../third-party -DUSE_BUNDLED_BUSTED=OFF -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PR
==> make VERBOSE=1
:   error: Failed to create '.libs'
make[3]: *** [unibilium.lo] Error 1
make[2]: *** [build/src/unibilium-stamp/unibilium-build] Error 2
make[1]: *** [CMakeFiles/unibilium.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/neovim/homebrew-neovim/issues

**Comment by justinmk** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Did you read that? This is a homebrew issue.
