### ISSUE TITLE
disable jemalloc for CI builds

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3287]
https://github.com/neovim/neovim/pull/3273#issuecomment-137586408

**Comment by fwalch** [comment]
Easiest way is probably to just disable jemalloc if `TRAVIS_CI_BUILD` is set in `CMakeLists.txt`. Look for `CLANG_MSAN`, as setting that also disables jemalloc.

**Comment by fmoralesc** [comment]
Btw, doesn't jemalloc 4.0 support OpenBSD now? If updating makes the original reason to build neovim without jemalloc unnecesary, wouldn't this turn the CI builds into artificial tests?

**Comment by justinmk** [comment]
> If updating makes the original reason to build neovim without jemalloc unnecesary, wouldn't this turn the CI builds into artificial tests?

My understanding is that jemalloc is hiding bugs.

**Comment by fmoralesc** [comment]
Not sure. If jemalloc is preventing segfaults on platforms other than OpenBSD, it might even be doing its job perfectly well and updating to 4.0 would fix the problem. But then again, it might be hiding issues, as you point out.

I'm trying to build without jemalloc now to test if #3273 is really affected by this or something else.

**Comment by justinmk** [comment]
Not going to bother with this for now.
