### ISSUE TITLE
Enable "protected branch" on master 

### ISSUE THREAD

**Issue by Pyrohh** [neovim/neovim#3293]
https://github.com/blog/2051-protected-branches-and-required-status-checks

We have a lot of people with commit bit, so I think this would be very reasonable to employ (once it's available).

**Comment by justinmk** [comment]
Did it a year ago :)

**Comment by Pyrohh** [comment]
Oy vey...

**Comment by fwalch** [comment]
A year ago? I thought protected branches were a brand-new github feature?

**Comment by jszakmeister** [comment]
GotHub has had the ability to protect master for a while now.  Outside of that, it was an all or nothing thing.  The new feature is that you can enable protection on individual branches.

**Comment by justinmk** [comment]
Until now, you had to email GH staff to protect a branch.

**Comment by ZyX-I** [comment]
@justinmk @Pyrohh GH now allows to decline merges to master when build fails. AFAIK this is not enabled and was not possible prior to this update, is it? Also it allows to decline merges until PR is based on top of master. Thus I think this issue needs to be reopened.

**Comment by justinmk** [comment]
> decline merges until PR is based on top of master. 

I'd be fine with this except it means that I can't fix people's commit messages, which are very often not following the guidelines in CONTRIBUTING.md.

**Comment by ZyX-I** [comment]
@justinmk I am not sure I understood correctly. I have read the article on Russian (not marked as the translation) which tells about needing to use “Update branch” button to merge PR if requiring successfull CI builds is enabled, but it does not tell what actually this button does. Though whatever it does I do not think it allows fixing commit messages.

In any case you may take PR and push it as a new branch after modifications. Or require contributor to fix commit messages on his own.

**Comment by ZyX-I** [comment]
@justinmk Also settings suggest that administrators can be allowed to bypass this requirement.

**Comment by justinmk** [comment]
> In any case you may take PR and push it as a new branch after modifications

Correct, but that is an extra step.

> Or require contributor to fix commit messages on his own.

I try to, but it is difficult if there are many PRs I am trying to move forward.

I do not know of any case where we merged something that we did not _want_ to merge.

**Comment by justinmk** [comment]
I have set master branch as "protected", and travis must pass now before merging a PR. The other status checks are not required because they are not reliable.

@neovim/core Note that this change probably means the "rebase" approach for merges will not work. As others have mentioned, rebasing has some disadvantages anyways. But it means contributors must be asked to fix commit messages and other minor problems.
