### ISSUE TITLE
auto cd in terminal

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#3294]
I've just met neovim and I am amazed at the terminal emulator.
However, I think it would be great that the emulator buffer could change its cwd(vim directory) when I type 'cd some/directory' in the command line, so that I can open files under the current directory with ease.

Currently, I hack with the following code in my .nvimrc. However, I wonder if there is a more formal way of doing so.

<pre><code>
fu! Ccd()
    let l=search('\%' . virtcol('.') . 'v\S', 'bW')
    let line = getline(l)
    let cmd=join(split(line)[2:-1],' ') "This assumses there are two space before the real command in addition to the shell prompts
    let arg0 = strpart(cmd, 0, 2)
    let arg1 = strpart(cmd,2, strlen(cmd)-2)
    if arg0=='cd'
       silent! lcd \`=arg1\`
    endif
endfunction

tnoremap \<Cr> \<C-\\>\<C-n>:call Ccd()\<Cr>i\<Cr>
</pre></code>

**Comment by ZyX-I** [comment]
Use `$NVIM_LISTEN_ADDRESS` environment variable and a shell hook like

```Python
#!/usr/bin/env python
# neovim-autocd.py
import neovim
import os

nvim = neovim.attach('socket', os.environ['NVIM_LISTEN_ADDRESS'])
nvim.vars['__autocd_cwd'] = os.getcwd()
nvim.command('execute "lcd" fnameescape(g:__autocd_cwd)')
del nvim.vars['__autocd_cwd']
```
```Shell
# .zshrc
neovim_autocd() {
    [[ $NVIM_LISTEN_ADDRESS ]] && neovim-autocd.py
}
chpwd_functions+=( neovim_autocd )
```

In bash AFAIK you need to save old PWD, and use PROMPT_COMMAND to run neovim-autocd.py when it appears that $PWD ≠ saved PWD.

In any case this is not a NeoVim issue. Write a plugin if needed.

(Note: with my code you need python, neovim PyPI package, but no code in VimL at all.)

**Comment by justinmk** [comment]
@ipod825 check out https://github.com/neovim/neovim/issues/2252 I think it may help with your request here.

**Comment by siphiuel** [comment]
@ZyX-I Thank you for solution! It works, although i had to change the `attach` line to

    nvim = neovim.attach('socket', path=os.environ['NVIM_LISTEN_ADDRESS'])
as it would trigger Python errors. Another thing to note is that it introduces a slight delay when `cd`ing.

**Comment by siphiuel** [comment]
Alternatively, one can use [this script](https://github.com/norcalli/scripts/blob/master/nvas) to correctly pick full file path. It will not `lcd` when navigating through directories in the terminal buffer, but for the stated use case it might be required.

**Comment by kutsan** [comment]
```vim
nnoremap <silent> <Leader>t :50vsplit +enew\ <Bar>\ call\ termopen('cd\ $PWD\ &&\ $SHELL')<CR>
```

What's wrong with this?

**Comment by mefercs** [comment]
map <c-t> :let $VIM_DIR=expand('%:p:h')<CR>:ter bash -c "cd $VIM_DIR;bash"<CR>

bro this fucs with me to open a terminal in the current path, as you can see you only need to type Ctrl + t, to open the terminal(un the current directory)

**Comment by anakin4747** [comment]
```
# ~/.zshrc
neovim_autocd() {
    [[ $NVIM ]] && nvim --server $NVIM --remote-send "<C-\\><C-N>:silent cd $PWD<CR>i"
}
chpwd_functions+=( neovim_autocd )
```

Thank you @ZyX-I!

This works perfectly for me and it doesn't need another script.

The `i` at the end is needed to enter back into terminal mode so your screen doesn't jump on you.

**Comment by justinmk** [comment]
OSC 7 was implemented in https://github.com/neovim/neovim/issues/2252 , see `:help terminal-events`. 

```lua
  vim.api.nvim_create_autocmd({ 'TermRequest' }, {
    desc = 'Handles OSC 7 dir change requests',
    callback = function(ev)
      if string.sub(vim.v.termrequest, 1, 4) == '\x1b]7;' then
        local dir = string.gsub(vim.v.termrequest, '\x1b]7;file://[^/]*', '')
        if vim.fn.isdirectory(dir) == 0 then
          vim.notify('invalid dir: '..dir)
          return
        end
        vim.api.nvim_buf_set_var(ev.buf, 'osc7_dir', dir)
        if vim.o.autochdir and vim.api.nvim_get_current_buf() == ev.buf then
          vim.cmd.cd(dir)
        end
      end
    end
  })
  vim.api.nvim_create_autocmd({ 'BufEnter', 'WinEnter', 'DirChanged' }, {
    callback = function(ev)
      if vim.b.osc7_dir and vim.fn.isdirectory(vim.b.osc7_dir) == 1 then
        vim.cmd.cd(vim.b.osc7_dir)
      end
    end
  })
```
