### ISSUE TITLE
Mouse Resize stops working when :help <doc> is opened

### ISSUE THREAD

**Issue by haata** [neovim/neovim#3296]
Environment:
ArchLinux, konsole
TERM=konsole-256color

nvim -version                                                                                                                                                       [~](hyatt@e7450Mas:pts/2)
NVIM 0.0.0-alpha+201509041956 (compiled Sep  4 2015 22:56:19)
Commit: 77e416b7115fd6bf8f36176f2d0aaa3369167cff
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/yaourt-tmp-hyatt/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-hyatt/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-hyatt/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-hyatt/aur-neovim-git/src/neovim-git/build/include
Compiled by hyatt@e7450Mas

Optional features included (+) or not (-): +acl   +iconv    +jemalloc

Steps to reproduce.
nvim -u blankconfig
:split
<attempt to resize split with mouse, works>
:help vim
<attempt to resize any split, nothing works>
<close the help document>
<attempt to resize split now works again>

Also reproducible in vim. Though set mouse=a is required.

**Comment by justinmk** [comment]
Cannot reproduce. Seems to be fixed.
