### ISSUE TITLE
Toggle fullscreen in visual mode sometimes fails

### ISSUE THREAD

**Issue by erf** [neovim/neovim#3302]
Sometimes when i have selected a few words in visual mode and the toggles to fullscreen and back, the cursor is off, and weird stuff happens when i move around. I use the terminal on osx. 5230aa8de9038733d316788738e86a2501b0acf0

**Comment by justinmk** [comment]
Is this a new issue or how long has it happened?

**Comment by erf** [comment]
Dont know. I just found out about it in the commit i mentioned.

**Comment by erf** [comment]
Toggling fullscreen on El Capitan (OSX) also fails in normal mode

**Comment by justinmk** [comment]
I suppose this is covered by other resize issues like https://github.com/neovim/neovim/issues/5434.
