### ISSUE TITLE
Custom search functions

### ISSUE THREAD

**Issue by lisael** [neovim/neovim#3312]
It would be convenient to have a command syntax like say `:/c/foo` to search `foo` only into comments. Subsequent hit on `n` cycle through the results (`foo` in a comment).

some exemples of possible builtins:
 - `:/s/bar` to search into strings
 - `:/m/fubar` to search only function names...

The user would have the ability to define custom search functions like `:/M/baz` which calls `MyFancySearch("baz")` and returns positions in the buffer.

Maybe the syntax `:/<letter>/` is not elegant and we can think about something better.

**Comment by justinmk** [comment]
Maybe as a plugin. Not backwards compatible, and out of scope for Neovim core.
