### ISSUE TITLE
Buffer truncated

### ISSUE THREAD

**Issue by jordic** [neovim/neovim#3313]
Sometimes, when I open a new buffer it gets truncated and writed to disk... 
I use to work with git, and i can checkout it. But its anoying...

What kind of help or dumps I can provide to improve the bug report?

Thanks in advance!

**Comment by justinmk** [comment]
Can you provide exact steps?

**Comment by jordic** [comment]
Seems something when i user my mouse scrollwheel... 
Open a file in a window, scroll with the mouse wheel and sometimes it hangs, with the buffer truncated.. also on disk.

Can I compile it with some extra flags to get extra debug info?

I can run tip.

**Comment by dnmario** [comment]
Dear Jordi Collell,

The email sent to danielm@tinyhub.tk with subject
"Re: [neovim] Buffer truncated (#3313)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to danielm@tinyhub.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/

**Comment by justinmk** [comment]
@jordic Does it happen if you `set mouse=` ?

Does it happen in Vim with `set mouse=a` ?

**Comment by jordic** [comment]
Currently i have theses settings:
ttymouse=xterm2
set mouse=a

In vim it doesn't happen

**Comment by justinmk** [comment]
Still need an answer: in Neovim, does it happen if you `set mouse=` (this is setting 'mouse' to nothing)?

**Comment by jordic** [comment]
If i set to nothing, my mouse doesn't work... I will try next hours. And post here the results.

**Comment by justinmk** [comment]
What if you use function keys (F4, F5, etc), arrow keys, or pageup/pagedown?

**Comment by jordic** [comment]
It works... for the moment... i just worked for around 1h and half, without mosue, and seems its not hanging.. Tomorrow more!

**Comment by jordic** [comment]
I'm working without mouse, for the past 5 hous and all works well. Seems that the bug is related to the mouse handling...

**Comment by jordic** [comment]
Iep, seems that on the latest release, it doesn't truncate the buffer. Also seems that the behaviour is happening only with when start scrolling with the mouse, on an opened buffer. But not every time.. (still not well reproductible).

My current version is:
NVIM 0.0.0-alpha (compiled Sep  9 2015 20:09:50)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/build/config -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/src -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-Hsd5Go/neovim-0.0.0+git201509090443+1889+13~ubuntu15.04.1/build/include
Compilat per buildd@lgw01-50

**Comment by tarruda** [comment]
@jordic what's your terminal emulator/os/version? Also, `ttymouse` is not used anymore(it will be removed). Mouse is handled by libtermkey which should use the correct codes based on your `$TERM`

**Comment by jordic** [comment]
Xterm with tmux. Ubuntu 15 64bits. I will check if i have ttymouse enabled.

**Comment by jordic** [comment]
Hey, something had changed... right now, the file is not truncated, only the buffer.. and can be reloaded witha a :e! 
The strange thing is that is not happening all the time, only sometimes, if i start scrolling with mousewheel, right after opening the file.

**Comment by cjxgm** [comment]
@jordic What's the output of `echo $TERM` inside tmux?
And, does it reproduce outside tmux?

**Comment by tarruda** [comment]
Since I have no way of reproducing, will postpone this to a later milestone

**Comment by jordic** [comment]
I just updated from the ppa, and also disabled the syntastic, and for the moment the error has gone... 
Perhaps is something related to syntastic, but I'm not sure..
Seems fair to close the ticket.. Because if disabling a plugin the error is not reproductible...

**Comment by tarruda** [comment]
> Seems fair to close the ticket.. Because if disabling a plugin the error is not reproductible...

I'm certain this is not the plugin's fault, especially if it works in Vim. If you say you absolutely can't reproduce the issue anymore(no matter which plugins or settings are used), then I will close.
