### ISSUE TITLE
Inconsistent append() behavior implemented by neovim API

### ISSUE THREAD

**Issue by cHoco** [neovim/neovim#3314]
Hello, neovim append() function exposed by the api isn't consistent with Vim implementation.
To verify the bug:
```
:python import vim; vim.current.buffer.append("Should append as first line", 0)
```
in neovim the line is appended after the first line, instead in vim it's appended on the first as documented by `:help python`

By taking a look at the code I think that the error is in the buffer_insert function. It calls the buffer_set_line_slice() without including the start but including the end. Its behavior should be inverted:
```diff
diff --git a/src/nvim/api/buffer.c b/src/nvim/api/buffer.c
index 12c97cf..ce3e64d 100644
--- a/src/nvim/api/buffer.c
+++ b/src/nvim/api/buffer.c
@@ -467,7 +467,7 @@ void buffer_insert(Buffer buffer,
                    ArrayOf(String) lines,
                    Error *err)
 {
-  buffer_set_line_slice(buffer, lnum, lnum, false, true, lines, err);
+  buffer_set_line_slice(buffer, lnum, lnum, true, false, lines, err);
 }
 
 /// Return a tuple (row,col) representing the position of the named mark
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/3212
