### ISSUE TITLE
No warning when opened file is changed outside Neovim

### ISSUE THREAD

**Issue by clobrano** [neovim/neovim#3326]
When a file is already opened in Neovim and, somehow, modified with another tool (editor, command line, ecc), Neovim does not notify in any way that it is working on a old copy.

**Comment by justinmk** [comment]
What if you run `:checktime` ? Vim in the terminal has this same issue. Request to improve it is here: https://github.com/neovim/neovim/issues/1936

And yes, and I would really like this feature too :)

**Comment by clobrano** [comment]
Yep, `:checktime` does the job, as well as `:edit %`, but one might not remember (or know) that something is changed. 
Looking forward to see this implemented, it's the only big issue before leaving gvim for neovim for good ;)

**Comment by omidfi** [comment]
I came here by searching, there's a working work around in #1936 

```
set autoread
au FocusGained * :checktime
```

**Comment by clobrano** [comment]
@omidfi, thank you, this is an improvement indeed, but there yet, because neovim warns you only when you try to save the file
