### ISSUE TITLE
gnome terminal probleme color

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3337]
os :linux mint 17.1

my probleme is neovim color work like a sharm in konsole and when i switch to gnome terminal i lose color  ,

**Comment by Jackevansevo** [comment]
Ensure your terminal support 256 colours. You can check this with (it should output 256)
```
tput colors
```
You also might want to ensure the $TERM environment variable is set up to handle 256 colours
```
echo $TERM
```

If the term environment variable doesn't output something like 'xterm-256color' you'll want to add the following line to your .bashrc config file
```
export TERM='xterm-256color'
```

This should probably solve your problem as gnome-terminal supports 256 colours

**Comment by justinmk** [comment]
Make sure that `NVIM_TUI_ENABLE_TRUE_COLOR` is unset. Setting it to 0 is not enough.

You need a recent version of gnome terminal if you want true color.

Also, these reports are lacking many details, so please provide more details in the future.
