### ISSUE TITLE
Implement WinClose autocommand-event

### ISSUE THREAD

**Issue by kiritsuku** [neovim/neovim#3338]
The only event type that is similar is `BufWinLeave`, but not enough for me. I need to know when a window is closed.

Right now I have to store all existing windows temporarily on a `WinLeave` event and check if one window is removed in the `WinEnter` event that appears afterwards. With a `WinClose` event this would be a lot simpler.

**Comment by justinmk** [comment]
> Right now I have to store all existing windows temporarily on a WinLeave event and check if one window is removed in the WinEnter

Can't you just compare the count?

**Comment by sschaef** [comment]
On 09/12/2015 11:59 PM, Justin M. Keyes wrote:
>
>     Right now I have to store all existing windows temporarily on a
>     WinLeave event and check if one window is removed in the WinEnter
>
> Can't you just compare the count?
>
No, I need to know which window(s) were closed.

**Comment by sakhnik** [comment]
I need this too. Consider the command `:only`. How could I know that other windows have just been dismissed?

**Comment by wsdjeg** [comment]
I have create a plugin for undo closed windows, and I use QuitPro autocmd event to restore the window info.

**Comment by justinmk** [comment]
I guess we need `QuitPost`? (WinClosePre/Post would have been a better name, we could add a hint in the docs...)
