### ISSUE TITLE
:terminal lines hard-wrapped

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#3341]
### Opening files with gf/gF command

When the text of a file wraps multiple lines neovim is unable to open the file correctly
Example

```
/path/to/the/quick/bro
wn/fox/jump.txt
```

`gf` or `gF` when cursor is on text
will result in a file being opened with the name 
`/path/to/the/quick/bro^Mwn/fox/jump.txt`

**Comment by justinmk** [comment]
At some point I think we should allow alternate "providers" for `gf` (and `gx`). Other than that I am not sure what can be done here.

**Comment by vito-c** [comment]
Well one option is to strip all of the newline characters from the string (only in terminal mode). This will break files that actually have a new line character in them. I would argue that having a new line character in the filename will happen less often then the text wrapping in terminal mode. As an temporary solution.

**Comment by jacobsimpson** [comment]
I think this might be representative of a larger issue.

In a terminal (with width less than 100), run:

```bash
printf '[' ; printf 'a%.0s' {1..100}; printf ']\n'
```

Trying to use 'V' in a terminal to select the whole line will only select the portion of the line the cursor is currently one, not the whole wrapped line.

Trying 'vi[' doesn't get all the text enclosed by the brackets.

Resizing the terminal won't reflow the wrapped line to fit the new terminal size.

**Comment by justinmk** [comment]
Terminal reflow is covered in another issue.

**Comment by snoblenet** [comment]
While we wait for release 0.3 which I believe will fix this issue, I'm successfully using the following hacky work-around:

```
function! GoToFileFromTerminal()
  " because the terminal often inserts line breaks in file paths
  try " try to open the file under the cursor
    exec 'normal gF'
  catch
    try " join the current line with the line above and try again
      set modifiable
      exec 'normal gJgF'
    catch
      try " restore the line break, move down a line and try again
        undo
        exec 'normal jgJgF'
      catch
        undo
        echo 'Could not open file'
      endtry
    endtry
  endtry
endfunction

function! GoToURLFromTerminal()
  " because the terminal often inserts line breaks in URLs
  try " try to open the URL under the cursor
    exec 'normal gx'
  catch
    try " join the current line with the line above and try again
      set modifiable
      exec 'normal gJgx'
    catch
      try " restore the line break, move down a line and try again
        undo
        exec 'normal jgJgx'
      catch
        undo
        echo 'Could not open URL'
      endtry
    endtry
  endtry
endfunction
```

**Comment by justinmk** [comment]
`gf` works `:terminal` now.

Terminal reflow is tracked in https://github.com/neovim/neovim/issues/2514
