### ISSUE TITLE
[Feature Request] Vimscript stopinsert!

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#3346]
The current implantation of vimscripts stopinsert is a bit lacking. When you call stopinsert it does not fire until after the updatetime has transpired. Resulting in plugins having to do work arounds to get it to function correctly. It would be great if there was a way to do stopinsert! and have it leave insert mode immediately. 

@Shougo

**Comment by Shougo** [comment]
@vito-c I think the problem is not feature request.
It seems bug.  But I don't know why.
Normal `:stopinsert` works fine.

**Comment by ZyX-I** [comment]
@vito-c @Shougo  I do not understand what you are talking about. Both in Vim and NeoVim the following works immediately:

    function Foo()
        stopinsert
    endfunction
    inoremap ff <C-o>:call Foo()<CR>
    inoremap kk <C-o>:call Foo()<CR>
    autocmd BufEnter * :call Foo()
    call feedkeys("affakk:new\na\<C-o>\<C-w>w", "t")
    " Note: <C-o><C-w>w misses a redraw, so with set showmode `-- (insert) --` appears at the bottom.

**Comment by Shougo** [comment]
Yes, stopinsert  works in most cases.  But it is not in unite.vim actions.
So we must create reproduce ways for it.

**Comment by vito-c** [comment]
@ZyX-I https://github.com/Shougo/unite.vim/issues/1015 this is the referenced issue with unite.
