### ISSUE TITLE
command history is broken `q:`

### ISSUE THREAD

**Issue by wrigleyster** [neovim/neovim#3347]
The command history (accessed via `q:`) is broken:
Expected behaviour:

1. `q:`
1. move the cursor to the line of a command you wish to execute
1. press `<cr>` aka. Enter
1. The command should execute

actual behaviour:

1. `q:`
1. move the cursor to the line of a command you wish to execute
1. press `<cr>` aka. Enter
1. A newline is entered, nothing is executed.

my installed neovim version:
```
NVIM 0.0.0-alpha+201509140855 (compiled Sep 15 2015 05:09:11)
Commit: 6bcbb18dc88d9b84f71c09450af10f8f537a8a68
Build type: RelWithDebInfo
Compilation: /usr/lib/hardening-wrapper/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/config -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/include
Compiled by jwrigley@admin

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
```

**Comment by justinmk** [comment]
Can't reproduce. Did you try `nvim -u NONE`? I tried `q:` and moved to the end of several commands, in normal mode and instert mode. In all cases, the `<cr>` executes the command.

**Comment by tarruda** [comment]
Does this happen with any command you tried? Can you give more details about the steps and environment(vimrc, plugins) used to reproduce?

**Comment by wrigleyster** [comment]
My sincere apologies. While I had tried to disable my plugins, what I hadn't noticed was that a script I had run shortly after install had appended `nnoremap <cr> O<Esc>j` to my `.nvimrc`. I realise, I should have investigated further. In my defence though, I still cannot fathom why anyone would even want to remap `<cr>`, and so it simply didn't occur to me that something like that might've been the case. It seemed far more natural, that it would've been a typo in some obscure place resulting in undefined behaviour.

Thank you for pointing out my folly.

**Comment by justinmk** [comment]
@wrigleyster No problem, thanks for the followup.
