### ISSUE TITLE
Move script_host.py into Python client?

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#3349]
This came up in the Arch Linux PKGBUILD comments.

When a `:python3` command is executed in an installed Neovim, `script_host.py` is compiled to bytecode, resulting in a `/usr/share/nvim/runtime/autoload/provider/script_host.pyc` file and a `__pycache__` directory.

The package manager doesn't know about these compiled files, though, as this only happens at runtime. The idea is therefore to pre-compile Python code to bytecode in the package creation step (i.e. in or before `make install`). For the python client, this is done automatically by its `setup.py`. For the main neovim package, doing this is a problem, as it would require adding a dependency on Python.

My question is, therefore: What about moving `script_host.py` into the python-client repo? ~~This might also help with certain "out-of-sync" problems between Neovim version and python-client version~~ (actually, this could also make things worse... but conceptually I think the Python repo is the right place for that). `script_host.py` is only used after an `import neovim` succeeded, so we should be able to get the path to the file from there.

In general, I guess all of the `python*.vim` files should _ideally_ be in the python-client repo, but I suspect that's not possible atm.

**Comment by bfredl** [comment]
I wonder if we should implement this simpler by just letting the python-client special-case the string `plugin_host.py`, or in general interpret non-absolute paths relative the `neovim` python module. As all detected remote plugins gets sent as an absolute path, there is no risk of conflict.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/4418
