### ISSUE TITLE
Create new function to return the syntax file applied to a given line in code

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#3350]
Linters such as syntastic or neomake need to apply different checkers on different chunks of code when a file contains two or more languages. A simple example is an HTML page containing Javascript code, but there are other cases as an XML document containing python code in cdata sections.

Syntax highlighting is actually capable of applying different syntax files using syn-include. That information should be available to plugins so that a linter plugin can extract chunks of different languages from a file.

**Comment by lewis6991** [comment]
No longer needed now we have treesitter with injections.
