### ISSUE TITLE
OpenType feature flags support

### ISSUE THREAD

**Issue by johndrinkwater** [neovim/neovim#3352]
Would be great if NeoVim gui version could support this, as some opentype fonts support the feature `zero`, which enables the font to show slashed zeros rather than the default appearance of the font.

It would be great to somehow be able to pass this setting through to the font renderer.

Reference links https://glyphsapp.com/tutorials/slashed-zero https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric#Values

**Comment by justinmk** [comment]
We have tickets/tasks covering UI configuration, but this is not the place for specific GUI feature requests.

**Comment by johndrinkwater** [comment]
Ah. Wouldn’t have opened it if other font feature requests weren’t open too, my bad.
