### ISSUE TITLE
Set shell to bash with argument "-i" makes Neovim to stop

### ISSUE THREAD

**Issue by clobrano** [neovim/neovim#3356]
Adding the command
```
set shell=/usr/bin/bash\ -i
```

to **.nvimrc** (it was already in my .vimrc and it works), neovim does not start any more. The output is just:

```
12:07 $ nvim

[2]+  Stopped                 nvim
```

Without the "-i" flag, neovim starts again as usual

**Comment by ZyX-I** [comment]
@clobrano It definitely should not stop. But this argument in any case should go to `shellcmdflag` option.

**Comment by clobrano** [comment]
I will try with `shellcmdflag`, but with Gvim I had no problems

**Comment by justinmk** [comment]
@ZyX-I were you able to reproduce this? I cannot reproduce it ba6c7a6f5b45ce5d79e6dc4838a967b2299b524c ubuntu x64

**Comment by clobrano** [comment]
Now it is working fine, actually...

**Comment by justinmk** [comment]
Ok. So something in those plugins is doing a CTRL-Z or `:suspend`.

I recommend https://github.com/ludovicchabant/vim-gutentags instead of easytags.

Thanks for followup.

**Comment by clobrano** [comment]
Thank you for the suggestion, I will try it

BR

Il giorno mer 23 set 2015 09:31 AM Justin M. Keyes <notifications@github.com>
ha scritto:
