### ISSUE TITLE
Error build in OS X

### ISSUE THREAD

**Issue by tanrax** [neovim/neovim#3357]
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jszakmeister** [comment]
Can you provide more details?  You fail to mention which OS you are using, whether you're building through homebrew or directly, how you invoked your build... all of which would be helpful to know.

**Comment by tanrax** [comment]
Directly
Only: make

**Comment by jszakmeister** [comment]
Which version of the OS X?  Are you setting CC or MACOSX_DEPLOYMENT_TARGET?  Can you provide the full output of `make VERBOSE=1` in gist?  All I can say at the moment is that master builds fine under Yosemite.

**Comment by jszakmeister** [comment]
It looks like you probably need to run Xcode and let it finish its installation.  `xcode-select --install` from the command line might do the trick too.

**Comment by justinmk** [comment]
See https://github.com/neovim/homebrew-neovim/issues/85

**Comment by tanrax** [comment]
Excuse my English

Running `make VERBOSE=1`

`==== Building LuaJIT 2.0.4 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTLINK  host/minilua
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [host/minilua] Error 1
make[4]: *** [src/luajit] Error 2
make[3]: *** [build/src/luajit-stamp/luajit-install] Error 2
make[2]: *** [CMakeFiles/luajit.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2`

Running `xcode-select --install`

`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by rafi** [comment]
Experiencing the same error on OSX Yosemite 10.10.5 (14F27), xcode-select already installed, manual compile:
```sh
$ make CMAKE_BUILD_TYPE=RelWithDebInfo DEPS_CMAKE_FLAGS=-DUSE_BUNDLED_BUSTED=OFF CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/opt/local" VERBOSE=1

...
[ 62%] Performing install step for 'luajit'
cd /Users/rafi/code/c/neovim/.deps/build/src/luajit && /Applications/Xcode.app/Contents/Developer/usr/bin/make CFLAGS=-fPIC CFLAGS+=-DLUAJIT_DISABLE_JIT CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-DLUA_USE_ASSERT CCDEBUG+=-g BUILDMODE=static install CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc PREFIX=/Users/rafi/code/c/neovim/.deps/usr
==== Building LuaJIT 2.0.4 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTLINK  host/minilua
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [host/minilua] Error 1
make[4]: *** [src/luajit] Error 2
make[3]: *** [build/src/luajit-stamp/luajit-install] Error 2
make[2]: *** [CMakeFiles/luajit.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```

**Comment by fwalch** [comment]
Do the comments there help? https://gist.github.com/jhannah/ebcebe2a55530b67e0de
