### ISSUE TITLE
Syntax on not working in .nvimrc

### ISSUE THREAD

**Issue by goods92** [neovim/neovim#3358]
I have the following lines in my ~/.nvimrc file:

filetype plugin on
syntax on
set t_Co=256
colorscheme tomorrow-night

Syntax highlighting is not working. Whenever I run ":syntax on" within nvim, the highlighting is applied.

**Comment by justinmk** [comment]
Cannot reproduce. What `:version` ?

**Comment by goods92** [comment]
NVIM 0.0.0-alpha+201509181512

**Comment by justinmk** [comment]
We need more precise steps. Does it happen with `nvim -u NONE`?

**Comment by goods92** [comment]
Yes. I run nvim vundle.vim to open my vundle file and every text is white. I use the theme tomorrow-night, if that helps. If I then run :syntax on, the colors change to the correct ones

**Comment by justinmk** [comment]
I'm not following your steps. Are you sourcing a file called "vundle.vim" or are you just opening it like this:

    nvim -u NONE vundle.vim

What's the full output of:

    verbose set background?
    echo $TERM

**Comment by goods92** [comment]
export TERM=xterm-256color ; nvim - did not fix it. It seems that opening nvim never applies :syntax on.
verbose set background :
background=light
        Last set from ~/dotfiles/nvim/nvim.symlink/colors/tomorrow-night.vim

**Comment by justinmk** [comment]
@goods92 Yep, that's the problem Your colorscheme is setting `background=dark` at the wrong time,

https://github.com/goods92/dotfiles/blob/master/nvim/nvim.symlink/colors/tomorrow-night.vim#L29

and N/Vim later incorrectly estimates `background=light` after some highlight operations. This would happen in Vim as well. I don't know where you pulled that theme from but it's not the one here: https://github.com/squarefrog/tomorrow-night.vim

In the future URLs would be appreciated.

**Comment by goods92** [comment]
I will include links in the future.

I pulled the new tomorrow-night theme that you linked to, but am still having the same issue.

**Comment by ldong** [comment]
FYI, now the nvimrc is moved to `~/.config/nvim/init.vim` from `:help nvim-from-vim`

**Comment by mananaBanana** [comment]
I am having a similar issue. I have followed these [instructions](https://github.com/ZyX-I/neovim/blob/42047acb4f07c689936b051864c6b4448b1b6aa1/runtime/doc/nvim_from_vim.txt) for moving from vim to nvim. If I do `nvim -u ~/.vimrc filename.py` it seems to work fine. For some reason it is not reading the rc file from `${XDG_CONFIG_HOME/nvim/init.nvim}`.

**Comment by eyeinsky** [comment]
FYI `export TERM=xterm-256color` was the key for me. tmux in OSX had set it to 'screen' for some reason. So regardless of nvim defaulting to 256 colors the `$TERM` has to be set correctly.
