### ISSUE TITLE
[BUG] Cursorcolumn render breaks

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3361]
Sometimes my cursorcolumn looks like this:

![screenshot from 2015-09-18 19-35-25](https://cloud.githubusercontent.com/assets/297678/9974286/b4b74734-5e3c-11e5-970a-010a35a3211c.png)

No idea how to reproduce. Perhaps it's related to the other rendering issues I've had in https://github.com/neovim/neovim/issues/3328.

**Comment by tarruda** [comment]
@trusktr is this completely random or reproducible only with some files/terminals/fonts? can you reproduce with nvim -u NONE +'set colorcolumn+=..' or with Vim?

**Comment by trusktr** [comment]
I'm not yet sure how to reproduce.
