### ISSUE TITLE
Doesn't render in Tmux in the latest El Capitan beta

### ISSUE THREAD

**Issue by alexlafroscia** [neovim/neovim#3366]
Since updating to the latest El Capitan beta, `nvim` doesn't render inside `tmux`.  It seems like the process starts (based on the label on the Tmux tab) but it doesn't actually show up

![screen shot 2015-09-20 at 2 30 54 pm](https://cloud.githubusercontent.com/assets/1645881/9982277/4a2bad2e-5fa4-11e5-8100-e27e4d5591ef.png)

`vim` doesn't seem to be having the same problem

![screen shot 2015-09-20 at 2 31 06 pm](https://cloud.githubusercontent.com/assets/1645881/9982282/6bd5c018-5fa4-11e5-9fa0-d95f277f6ac8.png)

**Comment by hansrodtang** [comment]
I am running tmux 2.0, a fresh copy of Neovim on OSX El Capitan and I can't reproduce this.

Neovim version: `NVIM 0.0.0-alpha+201509190915 (compiled Sep 21 2015 00:29:55)
Commit: 2417aeebbffe58eab6ac39feac0f64a27aafbee2`

**Comment by ZyX-I** [comment]
I was always running neovim inside tmux (1.9a) for testing and it never has such problem, including on latest commit from #3365. Please check whether `sh -c 'nvim'` has this problem, if it does not then you have some problem in your shell configuration.

**Comment by alexlafroscia** [comment]
`tmux` version: 2.0
`nvim` version: `NVIM 0.0.0-alpha+201509190915 (compiled Sep 20 2015 14:07:24)`
OSX version: 10.11.1

---

I tried `sh -c 'nvim'` and got the same issue

**Comment by justinmk** [comment]
@alexlafroscia Any difference with `nvim -u NONE`?

**Comment by alexlafroscia** [comment]
@justinmk that worked! Does that mean it's something in my Vim config?

**Comment by justinmk** [comment]
Something with your config may be triggering this behavior, but it's certainly something we should fix.

**Comment by alexlafroscia** [comment]
Yeah, I'll starting digging and seeing if I can find whatever's faulty.

**Comment by alexlafroscia** [comment]
Alright, the problem is Ultisnips https://github.com/SirVer/ultisnips

I currently load plugins using `vim-plug`.  If I disable the line that includes that plugin, `neovim` starts to work again.

**Comment by hansrodtang** [comment]
Strange, I have Ultisnips loaded using `vim-plug` myself, no issue here.

**Comment by alexlafroscia** [comment]
@hansrodtang do you think the way that I have Python installed might be messing with things? I just switched to using `pyenv` last week, but hadn't noticed any issues until this morning.  Maybe Ultisnips doesn't like the new way that Python is getting loaded?

**Comment by hansrodtang** [comment]
Tried it with `pyenv` (just pointing `python` to a local copy of 2.7.10) and it seems to be working fine. Your `pyenv` setup could of course be different than my test setup.

**Comment by alexlafroscia** [comment]
Huh, I didn't do anything in particular with it, just installed it through `brew` and used it to install python 3.5.  Nothing custom or anything

**Comment by hansrodtang** [comment]
Tried it with `pyenv` and Python 3.5, works fine here.

**Comment by umurgdk** [comment]
It works for me. But there is an another issue about tmux and el-capitan. It freezes all the system when you quit tmux.

**Comment by mhinz** [comment]
Is this still the case with tmux 2.1 from brew?

**Comment by alexlafroscia** [comment]
@mhinz yeah, I tried it yesterday after closing the issue by accident and saw that, if I install `Ultisnips` it still happens.

**Comment by nhooyr** [comment]
@alexlafroscia it could be `Ultisnips` in combination with some other setting in your init.vim. Try using the `verbose` option as well to check what its freezing on.

**Comment by alexlafroscia** [comment]
I've actually been using Ultisnips again and have been fine lately.  Forgot to close this; I guess someone somewhere fixed the issue :smile:
