### ISSUE TITLE
neovim color white space 

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3367]
neovim color white space  with red color automaticly

**Comment by nicolaiskogheim** [comment]
As a default? Nope.
And I take it you mean trailing white space.

**Comment by 7belrhalmia** [comment]
@nicolaiskogheim  yes
trailling whitespace

**Comment by nicolaiskogheim** [comment]
You could try out this plugin https://github.com/bronson/vim-trailing-whitespace

**Comment by justinmk** [comment]
With `nvim -u NONE` , a simple `set list` will show trailing whitespace.

If you want a red highlight:

```
highlight Trail ctermbg=red guibg=red
call matchadd('Trail', '\s\+$', 100)
```

**Comment by voidplayer** [comment]
This only works on the last window opened

For  example
```nvim -O file1 file2```

Will only have the match on file2.

Any idea how to set it on the config file to make it do this on every window?
