### ISSUE TITLE
fixeol from vim is missing

### ISSUE THREAD

**Issue by johanhelsing** [neovim/neovim#3369]
I assume this is because it was introduced after vim was forked into neovim.

The vim patch:
https://github.com/vim/vim/commit/34d72d4b6c1a2b04a214d8a49b7d22c97bc7a8bc

This feature would be very helpful in order to reduce unnecessary white space changes in commit history when working on projects where newline at end of file is not currently present nor required.

    :set nofixeol

Gives an error

     E518: Unknown option: nofixeol

**Comment by justinmk** [comment]
Thanks, we have https://neovim.io/doc/reports/vimpatch/ which shows all the patches we are missing. PR would be welcome :)
