### ISSUE TITLE
'guisp' highlight attribute is not being passed to remote UIs

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#3370]
The **guisp** attribute in highlight rules is being [ignored](https://github.com/neovim/neovim/blob/7dc241ac782e3a469d73d5f9a7baeba4e6107333/src/nvim/syntax.c#L6432), it is not possible for a remote UI to distinguish between SpellCap/SpellBad/etc (using the default highlights) they are all displayed with undercurl, but **guisp** defines the color for the undercurl.

pingback equalsraf/neovim-qt#43

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/1080 , I should not have closed it.
