### ISSUE TITLE
Can you add how to install neovim into readme?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3372]
i can not find how to install

**Comment by justinmk** [comment]
It is on the wiki and neovim.io main page.

**Comment by HuStmpHrrr** [comment]
it depends on how you want to install. you can use `apt-get`, `yum` in your system, or you can build from source, which is easy too.

**Comment by wsdjeg** [comment]
thankyou  i have add the ppa, and use the apt-get
