### ISSUE TITLE
set autochdir or set noautochdir in nvimrc disables wildmode=list:longest

### ISSUE THREAD

**Issue by rtwo** [neovim/neovim#3374]
I hope I am not missing something obvious but since I can reproduce it with an empty nvimrc ...

1. Add set autochdir or set noautochdir into an otherwise empty nvimrc
2. open nvim and enter `:b<TAB>`
3. Results in :bNext (but expected behavior would be :b - with a list of possible completions)
4. set wildmode (should be list:longest, full)

Repeat the same without autochdir or noautochdir for comparison.

Yes, either option results in the wrong behavior and only leaving it out entirely fixes it.

Just setting the options via command-mode results in the same (wrong) behavior.

NVIM 0.0.0-alpha+201509220803 (compiled Sep 22 2015 15:59:40)
Commit: 1ba081a6735e74446d5e9e05d0fb0bf9cca31f63

**Comment by justinmk** [comment]
Works for me:

    nvim -u NONE -c 'set autochdir'

`:b<tab>` shows a list of completions. `set wildmode?` reports `wildmode=list:longest,full`

**Comment by rtwo** [comment]
@justinmk thats wired, I update libtermkey and libvterm, nothing changed.

hmm, I just compiled nvim myself (I was using archs aur before) and this fixes it. I will experiment a bit to see if I can track down the cause for this.

**Comment by fwalch** [comment]
That's a strange one. I can actually reproduce this. It's not related to the dependencies, as an nvim built with `make USE_BUNDLED_DEPS=OFF` does not have this issue. Even with the problematic nvim, `:set wildmode` *does* report `wildmode=list:longest,full`.

**Comment by fwalch** [comment]
Okay.. steps to reproduce:

```
$ make distclean
$ make deps
$ LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro" make
$ build/bin/nvim -u NONE  -c 'set autochdir'
```

**Comment by rtwo** [comment]
@fwalch thanks for following up on this! I started to slowly doubt my sanity yesterday before going to bed.

**Comment by justinmk** [comment]
Yes, really nice @fwalch. Is it possible to narrow it down to a specific flag?

**Comment by rtwo** [comment]
@justinmk I can't reproduce it without --sort-common

LDFLAGS="-Wl,-O1,--as-needed,-z,relro" make
