### ISSUE TITLE
lag while exiting insert mode

### ISSUE THREAD

**Issue by fauno** [neovim/neovim#3375]
i've using [neovim-git from archlinux's aur](https://aur.archlinux.org/packages/neovim-git/).  currently i'm using an old build (98413a4 that i built from master) that just depends on msgpack-neovim, because since neovim depends on unibilium, libvterm and libtermkey i'm having this annoying issue i didn't have time to solve... until this old build broke :P 

the issue is that in these newer builds, while writing in insert mode and hitting escape to exit from it, it takes 1-2 seconds to comply.  so i either have to stop typing and wait, or the exit process gets cancelled and i end inserting vim commands into the text.

i've no idea what produces this, but it has been consistent since these new dependencies were added.  i've tried this without a vimrc and it happens anyway.

please tell me how can i help debug this issue :)

**Comment by fauno** [comment]
i've just tested with xfce4-terminal instead of [st](http://st.suckless.org) and it works correctly...

**Comment by justinmk** [comment]
Using tmux?

**Comment by fauno** [comment]
@justinmk yes

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/wiki/Troubleshooting#pressing-esc-when-running-nvim-in-tmux-or-gnu-screen-inserts-characters
