### ISSUE TITLE
add flag (like \m and \v) to enable Perl regex syntax

### ISSUE THREAD

**Issue by sunaku** [neovim/neovim#3376]
Hello,

Please add support for a new in-regex flag (similar to the existing `\m` magic and `\v` very-magic ones) that enables Perl regular expression syntax, which you might implement using [the PCRE library](http://www.pcre.org/).

According to my exhaustive perusal of `:help \flag` documentation, there are only 4 regex flags that Vim has not already claimed for itself: g, j, q, y.  Of these, I feel that perhaps `g` (which I read as "grep" or "generic" or "generous") would be the most suitable for this endeavor.

To illustrate, this is how I imagine this flag would work:

```vim
/\g(perl regex syntax goes here)\G(normal vim regex syntax goes here)/
```

The `\g` flag would turn the Perl regex syntax on, whereas the `\G` flag would turn it back off.  This on/off mechanism mirrors that of `\m` and `\M` magic regexps as well as `\v` and `\V` very-magic ones.

Thanks for your consideration.

**Comment by justinmk** [comment]
Going to toss this in with https://github.com/neovim/neovim/issues/3208

Note that Vim regex is a _feature_. I strongly recommend just learning it, it's really not that different from PCRE, it's mostly a superset. People get spooked by a few differences and run away screaming...

**Comment by sunaku** [comment]
Isn't this asking for something much simpler than #3208?   Rather than special `pcre_*()` functions, this request is about adding an in-regex flag that follows Vim's tradition of magic and very-magic flags. :cry:

**Comment by justinmk** [comment]
What is simpler about this? The internal implementation will require the same amount of work. 

The goal as always is to allow external providers to offer these types of features--PCRE is not something I would expect a N/Vim developer to spend much time working on. So #3208 stays open only to keep these requests from being repeated.

**Comment by sunaku** [comment]
Fair enough.  Would you accept a pull request for this feature into NeoVim itself?

**Comment by justinmk** [comment]
It would be best to open an issue that proposes a thoughtful semi-detailed design proposal, and discuss it from there. Usually not a good idea to post a ton of code and ask questions later ;)

Some examples of where specifications were laid out precisely, and later implemented:

- https://github.com/neovim/neovim/issues/999
- https://github.com/neovim/neovim/issues/78

Keep in the mind the role of the Vim syntax engine (regex.c, syntax.c) is woven throughout all of Vim. Bolting-on PCRE is going to be of limited value, and it will be valuable to nail down what your goals are. As I said, I suspect that if the only thing you are looking for is a way to use PCRE for plugins or `/` searches, this could really be served by a plugin.

**Comment by justinmk** [comment]
Also note that there is some very promising work being done on a perl client for Neovim: https://github.com/yanick/Neovim-RPC

**Comment by sunaku** [comment]
Thanks again for your patient consideration. :sweat_smile:  Some folks in the #vim IRC channel and I have been using both the standard regex syntax and the `\v` very magic syntax for years and simply wondered if, since NeoVim was rethinking Vim, perhaps PCRE might finally be supported via another unobtrusive magic flag.
