### ISSUE TITLE
tui: allow the cursor change color depending on the mode

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#3379]
Basically, support what `guicursor` does in gvim, in the TUI too.

This is just something I kinda miss ;)

**Comment by teto** [comment]
related to https://github.com/neovim/neovim/issues/3379

**Comment by fmoralesc** [comment]
@teto, Well, obviously ;) I think you meant https://github.com/neovim/neovim/issues/2583

**Comment by teto** [comment]
fixed.
I am sure you knew about it :p but I think it's nice to link both issues for others and also might help to close orphan issues.

**Comment by justinmk** [comment]
Renamed that issue.
