### ISSUE TITLE
'hlsearch' but no search highlight until I press `n` to go to next term.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3380]
When I start Neovim, `hlsearch` is on.

I then use this mapping to make a search:

``` viml
                nnoremap <silent> <cr> :let searchTerm = '\<'.expand("<cword>").'\>' <bar> let @/ = searchTerm <bar> echo '/'.@/ <bar> call histadd("search", searchTerm) <bar> :call TargetOn()<cr>

                function! TargetOn()
                    set hlsearch
                    set cursorcolumn
                endfunc

```

When I press enter on a word, highlight doesn't turn on as expected. It turns on if I press `n`.

Is this a bug, or am I missing something?

**Comment by trusktr** [comment]
If I instead change the mapping to this:

```viml
                nnoremap <silent> <cr> :let searchTerm = '\<'.expand("<cword>").'\>' <bar> let @/ = searchTerm <bar> echo '/'.@/ <bar> call histadd("search", searchTerm) <bar> set hls<cr>
```

then that works, and highlight will be turned on when I press enter. Note I'm not turning on the the cursorcolumn in that case.

**Comment by justinmk** [comment]
Does it happen in Vim?

**Comment by justinmk** [comment]
Works the same way on Vim.

**Comment by ggVGc** [comment]
Yeah, I recognize this from vim, and have made workarounds for it when writing a plugin. Definitely also consider it a bug.

**Comment by kassio** [comment]
I'd also consider this a bug, I even tried use the `v:hlsearch` to force turn the highlight on, but it didn't work.

**Comment by hauleth** [comment]
@kassio `v:hlsearch` is documented to not work inside functions. However it would be nice to have a way to enable highlight in function anyway as it will allow some nice features like mappings to search by movement.

**Comment by justinmk** [comment]
This is discussed at length in https://github.com/neovim/neovim/issues/5581, which has an misleading title because I renamed it in favor of a more "general" solution. I'll rename it again to mention 'hlsearch'.
