### ISSUE TITLE
doautoall! <nomodeline> FocusLost/FocusGained removes text in command mode

### ISSUE THREAD

**Issue by bambu** [neovim/neovim#3381]
Text in command mode is lost when FocusLost / FocusGained event occurs and after having tab completed to view available complete options. In Neovim.app, this is experienced by entering partial command in command mode (ex `:nno` then pressing tab to get list of complete options, then clicking on a different window. 

This is not limited to Neovim.app. I have been able to reproduce it via the following test script. 

```diff
diff --git a/test/functional/ui/input_spec.lua b/test/functional/ui/input_spec.lua
index 81af908..e0b6d18 100644
--- a/test/functional/ui/input_spec.lua
+++ b/test/functional/ui/input_spec.lua
@@ -1,11 +1,11 @@
 local helpers = require('test.functional.helpers')
 local clear, execute, nvim = helpers.clear, helpers.execute, helpers.nvim
+local Screen = require('test.functional.ui.screen')
 local feed, next_message, eq = helpers.feed, helpers.next_message, helpers.eq
 local expect = helpers.expect
 
 describe('mappings', function()
   local cid
-
   local add_mapping = function(mapping, send)
     local str = 'mapped '..mapping
     local cmd = "nnoremap "..mapping.." :call rpcnotify("..cid..", 'mapped', '"
@@ -40,7 +40,37 @@ describe('mappings', function()
   end)
 end)
 
+describe('cmdline lost on focuslost', function()
+  before_each(clear)
+  it('ok', function()
+    local screen = Screen.new()
+    screen:attach()
+    feed(':nn<tab>')
+    nvim('command',"silent! doautoall <nomodeline> FocusLost") 
+    screen:snapshot_util({}, true)
+    screen:expect([[
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      ~                                                    |
+      :nnorem^                                              |
+    ]])
+    clear()
+  end)
+end)
+
+
 describe('input utf sequences that contain CSI/K_SPECIAL', function()
+  before_each(clear)
   it('ok', function()
     feed('i…<esc>')
     expect('…')
```

When this test is run, the result is:
```
screen:expect([[
                                                       |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
  ~                                                    |
         ^                                              |
]])
```
In the above example there should have been a  `:nnorem` before the cursor. As that is the completion that occurs when typing `:nn` and pressing tab in nvim.

It seems that when nvim is redrawing, it goes to the command line, clears the line and sets the cursor to the position of where it normally would be if it had text. 

This issue was originally expressed in rogual/neovim-dot-app#133. There is a screen shot there displaying how it looks in the UI.

**Comment by justinmk** [comment]
Nice, thanks for the test. I noticed this too. If you type a character, the text shows up again, right? So it's just a drawing problem.

**Comment by bambu** [comment]
yeah it does show back up  after typing any character

**Comment by bambu** [comment]
I found a seemingly related issue. Not sure if I should open a separate issue for it or not. 

If you are in visual mode with something selected, then go into command mode and trigger focus lost, you will still be in visual mode but the visual selection will disappear. 

Not sure how to make a test to track what is displayed visually but here is another way to reproduce it. 
1. Open nvim 
2. type some text and select a portion of it
3. Enter command mode
4. Open python in a different terminal 
5. Enter
```python
from neovim import attach
nvim = attach("socket", "nvim_listen_address")
nvim.command("silent! doautoall <nomodeline> FocusLost")
```
6. Look back at nvim. The visual selection will have disappeared. However you will still be in visual mode.

**Comment by bambu** [comment]
Looks like this issue has already been addressed as this test now passes when ran on the latest version on master branch. Closing this issue.

**Comment by justinmk** [comment]
@bambu I am not aware of anything that would have addressed this. But a PR for the test would be useful.
