### ISSUE TITLE
Caret and char under caret dropping below current line

### ISSUE THREAD

**Issue by x-benclarke** [neovim/neovim#3383]
<img width="293" alt="screen shot 2015-09-24 at 11 57 10" src="https://cloud.githubusercontent.com/assets/10184745/10071669/73e34138-62b3-11e5-8e4b-ae1b9ee58347.png">

**Comment by fmoralesc** [comment]
What terminal is that?

**Comment by x-benclarke** [comment]
iTerm2 nightly

**Comment by fmoralesc** [comment]
Any configuration that might be affection line height?

**Comment by x-benclarke** [comment]
Not that I can see. nvim was working with no problems until I just updated it through homebrew. Here is my line height / font config (doesn't say much though)
<img width="1036" alt="screen shot 2015-09-24 at 12 32 49" src="https://cloud.githubusercontent.com/assets/10184745/10072332/9ebbbdf4-62b8-11e5-8c1b-d775043a39a8.png">

**Comment by fmoralesc** [comment]
Weird. Of those, only Vertical Character Spacing is a candidate for causing this. The only recent change related to character display was https://github.com/neovim/neovim/commit/57836f2b71131decfc1da80b15a2c84f48de4336 I think, and it's unrelated. https://github.com/neovim/neovim/commit/1f90cbb4aed1eb047b36eb4b41e2ad02f9ae3a4f changed the internal data estructure for cells, but it also doesn't seem relevant.

**Comment by x-benclarke** [comment]
I've worked out what's causing the issue. If I set the vertical spacing to 100% in iTerm2 the issue doesn't happen...
<img width="1076" alt="screen shot 2015-09-24 at 12 44 21" src="https://cloud.githubusercontent.com/assets/10184745/10072505/3aef6206-62ba-11e5-8a28-b770fa6bc8d5.png">
But, if I set it to 150%, all the text adjusts correctly, except the caret and what whats under the caret. They default to 100%...
<img width="1068" alt="screen shot 2015-09-24 at 12 44 41" src="https://cloud.githubusercontent.com/assets/10184745/10072533/6d9a83ca-62ba-11e5-8c01-35e987d6bf4f.png">

**Comment by fmoralesc** [comment]
In that case, I would think it's an issue with iTerm, not neovim. Have you tried with other terminals?

**Comment by x-benclarke** [comment]
I have tried it in Mac terminal and the issue doesn't happen. I'll get on to the guys at iTerm and see what they say.
Thanks for your help!

**Comment by x-benclarke** [comment]
It's an iTerm2 issue for sure. Just rolled back the nightly build and has fixed the issue.
