### ISSUE TITLE
Neovim under windows 64

### ISSUE THREAD

**Issue by Remiol** [neovim/neovim#3388]
Windows support is (currently) experimental. 
Go to 
https://ci.appveyor.com/project/equalsraf/neovim 
◦Click the  Win64  build (near the bottom, with this label:  
Environment: GENERATOR=Visual Studio 14 Win64, DEPS_PATH=deps64 ).
◦View the Artifacts tab.
◦Download  Neovim.zip
....
---------------------------------------------------------------------------

There is nothing in the Artifacts tab.
"The build job does not contain any artifacts."

Did I do something wrong?

**Comment by justinmk** [comment]
Hmm, I think #810 is having a problem. @equalsraf can you confirm?

**Comment by equalsraf** [comment]
No, its just the link that is wrong, use https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw

**Comment by equalsraf** [comment]
@justinmk, I've fixed the link in the wiki.

**Comment by justinmk** [comment]
Thanks :)

**Comment by Remiol** [comment]
Thank you, nice!
I have to learn NeoVim better. 
menu.vim doesn't seem to work. 
Don't see the menu I've created in vim.
No tabs as well.
But a nice interface.

**Comment by equalsraf** [comment]
@Remiol correct there is no menu or tabs - feel free to add issues at https://github.com/equalsraf/neovim-qt

**Comment by Remiol** [comment]
any idea what the window command is for:
ln -s _vimrc_.nvimrc ?

I can't seem to import my vimrc config file. 
I also tried to rename it to _nvimrc but that crashed my neovim

**Comment by ZyX-I** [comment]
@Remiol You can use `source` command to load another file. For real symlinks search for “windows create symbolic link”: I know how this is named, but not Windows commands. Though if `_nvimrc` crashes NeoVim then 90% that *any* way of loading the same file will *also* crash NeoVim.

**Comment by equalsraf** [comment]
@Remiol can you share your _nvimrc so I can try it myself?

**Comment by Remiol** [comment]
I imported the wrong vimrc file. No problem using the source command. Thanks. I miss the file menu so I'll wait till neovim reach the 0.1 milestone.

**Comment by Remiol** [comment]
@equalsraf, Just to tell you that here is no neovim.zip in artifacts:  https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw

**Comment by equalsraf** [comment]
@Remiol thanks, the builds are failing, don't know why. The latest working build is https://ci.appveyor.com/project/equalsraf/neovim/build/528

**Comment by Remiol** [comment]
@equalsraf, no problem. I just downloaded the build. :)

**Comment by Remiol** [comment]
The latest build of Neovim doesn't seem to work on windows:
The program can't start because libuv.dll is missing from your computer.
The program can't start because msgpack.dll is missing from your computer.
The program can't start because vcruntime140.dll is missing from your computer.

**Comment by equalsraf** [comment]
libuv.dll, msgpack.dll should be there along the nvim.exe binary. Installing the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145) should fix the vcruntime140.dll.

@Remiol  how are you installing? I can't test right away but we need to update the [install instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows)

**Comment by Remiol** [comment]
@equalsraf, I always did it as indicated here:
https://github.com/neovim/neovim/wiki/Installing-Neovim

**Comment by Remiol** [comment]
Ah. ok. we don't have to copy only the nvim.exe but all files in `\Neovim.zip\bin`. :+1:  Visual C++ for VS2015? I don't install this for the moment. Had many problems with a previous version of VS.

**Comment by equalsraf** [comment]
You don't need to install the entire Visual Studio, only the redistributable dll package.

**Comment by justinmk** [comment]
@equalsraf Can we ship with that instead of requiring installing of the 2015 CRT?

**Comment by Remiol** [comment]
vs_redist.x64.exe has many runtime drivers. They are all loaded in the windows directory. 15 mb, of drivers, more then whatever text editor software entirely. Yes it would me nice to ship this driver within neovim.

**Comment by sethjackson** [comment]
I'm not sure what the license requirements are for doing that but basically any software that uses the MSVC CRT as a DLL should really just use the installer.

I would really shy away from including the runtime directly and point users at the correct installer or run the installer as part of the Neovim install process. HexChat does this for example.

And app-local deployment is not really officially pushed by Microsoft as far as I'm aware (even if it is still sorta-kinda supported).

Further in my experience the supported way of doing things is to use shared linking and install the runtime.

Other avenues are generally incredibly painful and fraught with problems.

**Comment by justinmk** [comment]
> And app-local deployment is not really officially pushed by Microsoft as far as I'm aware

That's true.

> or run the installer as part of the Neovim install process

We do have that option. Perhaps we could still ship it with the portable (non-installer) zip, if we end up offering that.
