### ISSUE TITLE
probleme with mapping

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3390]
hey neovim frinds : 

i have done this mapping in my .nvimrc : 
     au BufWrite *.scss  :silent! !ctags -R<cr>

but i got nothing . it work in vim

**Comment by justinmk** [comment]
If you open a `.scss` file and run `!ctags -R` manually, what output do you see?

**Comment by 7belrhalmia** [comment]
i see a message to presse enter and the command work normally @justinmk

**Comment by justinmk** [comment]
Not enough information. Need reduced steps.
