### ISSUE TITLE
Auto-completion not working?

### ISSUE THREAD

**Issue by nicolas-siplis** [neovim/neovim#3391]
All my Vim plugins and color schemes seem to work fine, but I don't understand why code suggestion/completion does not. It's enabled by default in Vim so I figured the same would apply to Neovim, but that doesn't appear to be the case.

![screenshot from 2015-09-25 15-56-33](https://cloud.githubusercontent.com/assets/13225534/10109574/16775da4-639e-11e5-80a7-6cfe6bb96c34.png)

![screenshot from 2015-09-25 15-56-51](https://cloud.githubusercontent.com/assets/13225534/10109582/1a4605a2-639e-11e5-87f2-4f2fa07b0a0a.png)

**Comment by justinmk** [comment]
> It's enabled by default in Vim

Not sure what you mean by that. You must press CTRL-N or CTRL-P in both Nvim and Vim. Please compare `vim -u NONE -N` with `nvim -u NONE`.

**Comment by nicolas-siplis** [comment]
To get autocompletion in Vim I don't have to do anything, it works out of the box as far as I can tell.

**Comment by justinmk** [comment]
No, there must be a plugin or something doing that.

**Comment by nicolas-siplis** [comment]
The only plugins I have installed are vim-surround and auto-pairs, which shouldn't alter anything related to autocompletion.

In any case, is there any way to achieve the same result in Neovim? Without using plugins, of course.

**Comment by justinmk** [comment]
So, did you try `vim -u NONE -N` ?

**Comment by nicolas-siplis** [comment]
I did, it stripped my color scheme and I had to use Ctrl-N / Ctrl-P for autocompletion (just like you said). However, I prefer not having to press extra keys to see the suggested code, so I was wondering if there was any way to avoid doing so. I'm really new to Vim/Neovim but I'm assuming an autocmd would be the right tool for the job.

**Comment by justinmk** [comment]
Somewhere in your config (or plugins), something is adding an autocmd. What's the output of these commands:

```
au InsertCharPre
au CursorMovedI
```

**Comment by justinmk** [comment]
By the way, check out this video to see why Vim's built-in completion is neat: [Let Vim do the typing]    (https://www.youtube.com/watch?v=3TX3kV3TICU)

**Comment by fwalch** [comment]
If you can't find anything in your personal config, maybe your distro set up some defaults in /etc/vim/ or/etc/vimrc or something like that.

**Comment by Shougo** [comment]
> All my Vim plugins and color schemes seem to work fine, but I don't understand why code suggestion/completion does not. It's enabled by default in Vim so I figured the same would apply to Neovim, but that doesn't appear to be the case.

You seems use neocomplete plugin.
neocomplete does not work in neovim.
You should use deoplete.nvim instead.

**Comment by nicolas-siplis** [comment]
Wow, I'm really sorry! Turns out I had YCM installed, but it was not showing up in the plugins folder.

**Comment by justinmk** [comment]
@nicolas-siplis No problem, thanks for followup. Note that YCM works with Neovim, check `:help nvim-python` for instructions.

**Comment by 4lend** [comment]
Or You can disable you cmp-nvim configuration. I solve it with do that.
