### ISSUE TITLE
Menu commands while in insert terminal mode does not work

### ISSUE THREAD

**Issue by bambu** [neovim/neovim#3393]
This issue was detected at rogual/neovim-dot-app#143. 

Looking into it, it appears that there is no support in [menu.c#1262](https://github.com/neovim/neovim/blob/master/src/nvim/menu.c#L1262) for `TERM_FOCUS` which is the value of `State` at the time when doing calling `emenu` in terminal insert mode. 

I am able to change line 1262 to 

``` c
if (((State & INSERT) || (State & TERM_FOCUS) || restart_edit) && !current_SID) {
```

This in theory should work. However when setting `anoremap` it appears to bind the insert mode mapping incorrectly . This is the output of `:amenu Edit.Show\ Fonts` which was set with `anoremenu &Edit.Show\ Fonts :call MacShowFontSelector()<CR>`

``` vim
500 Show Fonts
    n*   :call MacShowFontSelector()<CR>
    v*   <C-C>:call MacShowFontSelector()<CR><C-\><C-G>
    s*   <C-C>:call MacShowFontSelector()<CR><C-\><C-G>
    o*   <C-C>:call MacShowFontSelector()<CR><C-\><C-G>
    i*   <C-\><C-O>:call MacShowFontSelector()<CR>
    c*   <C-C>:call MacShowFontSelector()<CR><C-\><C-G> 
```

I would imagine that this should be `<C-\><C-N>` as that is the default mapping of escaping terminal mode. Could not find where this gets set in the source code.

**Comment by bambu** [comment]
Here's the test for it 
```lua
describe('emenu Edit.Undo while in terminal mode', function()
    before_each(clear)
    it('ok', function()
        local screen = require('test.functional.ui.screen').new()
        screen:attach()
        nvim('command', 'runtime menu.vim')
        feed(':term cat<cr>')
        nvim('command', 'emenu Edit.Undo')
        screen:snapshot_util({}, true)
        screen:expect([[
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
                                                               |
        -- TERMINAL --                                         |
        ]])

        screen:detach()
        clear()
    end)
end)
```

**Comment by justinmk** [comment]
> I would imagine that this should be `<C-\><C-N>` as that is the default mapping of escaping terminal mode.

Based on `:help CTRL-\_CTRL-G` I think we actually need to make terminal mode respect `'insertmode'`. `CTRL-\_CTRL-G` should work in terminal mode--that's something we missed. Shouldn't be difficult.

We _may_ need a `tnoremenu` command, but I am not familiar with `amenu` nor `emenu`. Consider that a last resort.

**Comment by fdinoff** [comment]
`amenu` should support terminal mode since its supposed to put menus in all modes. Since terminal mode is a new mode `amenu` should also effect it.

From a consistency standpoint I view menu commands to have all the same variations as maps. (With an extra connivence `amenu` command). Given that `tmenu` should also be added.

**Comment by zeertzjq** [comment]
There are now `:tlmenu`, `:tlnoremenu`, `:tlunmenu`
