### ISSUE TITLE
How to use `nvim` with Python extension without installing `neovim` python package into system Python

### ISSUE THREAD

**Issue by vlcinsky** [neovim/neovim#3396]
# Debian discouraging installation of packages by pip into system Python

Debian 8 Jessie comes with Python 2.7.9 which shall allow installing pip by means of `ensurepip`
module.

However, trying that one gets following advice:

```
$ python -m ensurepip
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules For the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.
```

As there is no `python-neovim` package yet, one cannot use `$ sudo apt-get install python-neovim`.
# `nvim` with `neovim` Python package in virtualenv

Here is how I managed installing `neovim` python package into virtualenv and configured `nvim` to
use that.
## Install `neovim` python package into virtualenv

Debian allows `apt-get install` for either `python-virtualenv` or even better `virtualenvwrapper`.

I have created `neovim` virtualenv environment (using virtualenvwrapper):

```
$ mkvirtualenv neovim
(neovim) $
```

and installed `neovim` python package into it:

```
(neovim) $ pip install neovim
```

Then I have found the python interpreter for this virtualenv:

```
(neovim) $ where python
/home/javl/.virtualenvs/neovim/bin/python
/usr/bin/python
```
## Configure `nvim` to use python with installed `neovim` package

`nvim` allows specifying explicit python interpreter in `.nvimrc` so I have added following line
(just to the top of the file):

```
let g:python_host_prog="/home/javl/.virtualenvs/neovim/bin/python"
```

After that, my `nvim` instance works well with python based nvim extensions like 'klen/python-mode'.
# Conclusions
- System-wide installation of any python package is generally not recommended practise (this applies
  not only to Debian or Linux, but to MS Windows or Mac OS too).
- For systems (various Linux distributions) it is fine to use packages provided for this purpose in
  distribution repositories (one would expect e.g. `python-neovim` package for Ubuntu or Debian) as
  these are tested for compatibility with other "officially" provided packages.
- In all other cases it is recommended and also possible installing `neovim` Python package into
  virtualenv and configuring `nvim` to use such python interpreter.

Current `nvim` documentation is proposing installation by means of `pip` and most users will
probably install `neovim` package into global Python. Consider adding instructions for installing
`neovim` into virtualenv as described above.

**Comment by justinmk** [comment]
Thanks a lot.

**Comment by mikew** [comment]
Does `pip install --user neovim` not work?

**Comment by vlcinsky** [comment]
@mikew Good question.

```bash
$ python -m pip install --user neovim
```
plus I have removed the ```let g:python_host_prog="/home/javl/.virtualenvs/neovim/bin/python"``` line from my `.nvimrc`

The installation into --user works and installs the `neovim` package.

Running `nvim` out of virtualenvs works well and does not require the trick with `let g:python_host_prog`.

However, when I open `nvim` while having virtualenv activated, it fails, as packages installed into user site-packages are not visible from virtual environment.

Changing my `.nvimrc` to point explicitly to system-wide python: ```let g:python_host_prog="/usr/bin/python"``` resolved the issue and I was again able using Python based plugins in `nvim` regardless of any virtualenv being active or not.

# Conclusions
- installing python package `neovim` into user site packages is possible
- currently, to prevent any problems with working with activated or deactivated virtualenvs requires use of ```let g:python_host_prog="/some/path/python"``` pointing explicitly to a python, which has `neovim` package installed. It does not matter, if it is system-wide python or a python from some virtualenv with `neovim` package being installed.
- if `nvim` would not pick by default currently active `python` interpreter, but would insist on system-wide one, installation of `neovim` package into user packages would be solution (not considering switching to other user accounts).
- I am not sure, if such behaviour would break some python tools or not (some may try to work with currently activated virtualenv python to provide some functionality).

**Comment by siddharthist** [comment]
@vlcinsky Thanks for the thoughtful issue! I love the idea of not installing any system-wide packages, especially when testing/writing my own plugins.

**Comment by vlcinsky** [comment]
We shall distinguish two use cases:
- global: using python neovim module for generally used neovim plugins
- local python: dealing with currently activated virtualenv for Python development

The global use case shall be stable and shall not depend on actually activated virtualenv python.

The local python use case on the other hand shall try hard to find currently activated virtualenv.

Current status is shaky as switching among different virtualenvs is very common situation and it means, that without having `let g:python_host_prog=...` set, it will mostly not work well.

It would be nice to have nvim behaving by default correctly in these situations, e.g. always trying to pick the python, which is installed in system or which would be found by default without having virtualenv activated.

Anyway, as I lack experience with authoring python-related plugins I cannot evaluate, how this would affect their use and development.

@tcuthbert and @justinmk do you have any good ideas to that? (referring to your participation in #4101)

**Comment by fwalch** [comment]
I guess we could search $_OLD_VIRTUAL_PATH, where virtualenv seems to store the original path, but it seems brittle. Alternatively, we could try to ignore Pythons found in $VIRTUAL_ENV/bin  (temporarily removing it from PATH?).

**Comment by tony** [comment]
The complication introduced by having to look for neovim in python2 and python3 site packages is a royal pain.  I'd like for those who have intimate familiarity with it to consider whether neovim could just automate it somehow.

It relies too much on the user's system and python setup. It creates another set of concerns if we're troubleshooting a plugin. Language-specific plugins are already one of the biggest pain points when it comes to debugging. We can't be totally sure if the user's distinct python setup or library is at fault.

I wish we had a command in neovim where we could just dump any python environment information we had, it'd make it easier to rule out if its the environment at fault, python-client, the user's configuration, the plugin or neovim.

**Comment by fwalch** [comment]
@tony there's https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working, which shows you which Pythons Neovim tried.

**Comment by tcuthbert** [comment]
Although not pretty -
https://github.com/tcuthbert/dotfiles/blob/master/nvim/init.vim#L121 this
helps a lot with working out whats going on when you're using pyenv.

This works well as I swap between osx + linux frequently. The downside is I
need to UpdateRemotePlugins each time I change machine as I sync my
dotfiles to dropbox.


Regards,

Thomas Cuthbert

**Comment by justinmk** [comment]
> I wish we had a command in neovim where we could just dump any python environment information we had, 

`:CheckHealth` addresses this.

Original issue here is addressed by the recently added "PYTHON VIRTUALENVS" section at `:help provider-python`.
