### ISSUE TITLE
Wrong colorscheme in all but first `byobu` tabs

### ISSUE THREAD

**Issue by vlcinsky** [neovim/neovim#3397]
OS: Debian 8 Jessie

Using byobu with screen.

When starting `nvim` in fresh `byobu` session, my `beauty256` colorscheme shows properly.

In any other tabs or splits in byobu or in gnome-terminal `nvim` shows with wrong colorscheme (almost unreadable).

When starting `vim`, colorscheme shows properly in all the cases.

# Different environment

Comparing environmental variables in first and other byobu windows I have found the difference:

First buffer:

    TERM=screen-256color

Other buffers:

    TERM=screen

# Changing `TERM` to `screen-256color` resolves the problem

Setting

    $ export TERM=screen-256color

I can then start `nvim` with my colorscheme properly set up.

I wonder, if I shall consider this bug in byobu or nvim

**Comment by justinmk** [comment]
This is either a problem with your screen/byobu configuration, or it's a byobu bug. Neovim just reads `TERM`, it doesn't change it.

https://github.com/neovim/neovim/issues/2912 will work around this.

Thanks for the great reports!

**Comment by Junzh666** [comment]
> OS: Debian 8 Jessie
> 
> Using byobu with screen.
> 
> When starting `nvim` in fresh `byobu` session, my `beauty256` colorscheme shows properly.
> 
> In any other tabs or splits in byobu or in gnome-terminal `nvim` shows with wrong colorscheme (almost unreadable).
> 
> When starting `vim`, colorscheme shows properly in all the cases.
> 
> # Different environment
> Comparing environmental variables in first and other byobu windows I have found the difference:
> 
> First buffer:
> 
> ```
> TERM=screen-256color
> ```
> 
> Other buffers:
> 
> ```
> TERM=screen
> ```
> 
> # Changing `TERM` to `screen-256color` resolves the problem
> Setting
> 
> ```
> $ export TERM=screen-256color
> ```
> 
> I can then start `nvim` with my colorscheme properly set up.
> 
> I wonder, if I shall consider this bug in byobu or nvim

thanks！it works.
