### ISSUE TITLE
Neovim fails to set titlestring in tmux with 'default-terminal "tmux-256color"'

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#3399]
I am using the following in my tmux conf, which makes Neovim not set the `&titlestring` inside of tmux:

    if-shell '[ "$TERM" = "linux" ]' 'set -g default-terminal "tmux"' 'set -g default-terminal "tmux-256color"'

That boils down to:

    set -g default-terminal "tmux-256color"

It works with Vim itself.

**Comment by justinmk** [comment]
I use `set -g default-terminal "screen-256color"` but it works with `"tmux-256color"` as well on 536c0ba27e79929eb30850d8e11f2ed026930ab3 as it has since at least March. Did you `set title`?

**Comment by blueyed** [comment]
I've just tested it with master (2788f7f) again, and the issue remains.

I'll have to investigate further then probably.  I've also tried it with gnome-terminal instead of urxvt (tmux started from there), and `zsh -f`.

**Comment by blueyed** [comment]
@justinmk 
Do you have a `tmux-256color` terminfo file after all? (see https://github.com/tmux/tmux/blob/master/FAQ#L363-L374)

**Comment by blueyed** [comment]
The difference between non-tmux (and tmux with TERM=xterm-256color) and tmux with `tmux-256color` is that the `unibi_get_str(data->ut, unibi_to_status_line)` and `unibi_get_str(data->ut, unibi_from_status_line)` returns `0` in `tui_set_title` (https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L616) in the latter case.

**Comment by blueyed** [comment]
https://github.com/neovim/neovim/pull/3422 fixes it for me.

@justinmk 
Are you sure you were using TERM=tmux-256color?

**Comment by justinmk** [comment]
@blueyed You're right, I made a mistake somewhere. BTW when I start Vim with tmux-256color it reports:

```
$ vim

E558: Terminal entry not found in terminfo
'tmux-256color' not known. Available builtin terminals are:
    builtin_ansi
    builtin_xterm
    builtin_iris-ansi
    builtin_dumb
defaulting to 'ansi'
```
