### ISSUE TITLE
version: use `git describe` for version string

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3400]
https://github.com/neovim/neovim/pull/3318#issuecomment-143647477

**Comment by fwalch** [comment]
There's a `git_describe` CMake function in `GetGitRevisionDescription.cmake` that we should be able to use for that. But I guess we still need to hardcode some version info in case Git data isn't available (i.e. building from downloaded tarball).

**Comment by justinmk** [comment]
Closed by d0401b04a4ed6a1684091a84bfd262b2b2cb560f
