### ISSUE TITLE
:normal broken, "Can't re-enter normal mode from terminal mode"

### ISSUE THREAD

**Issue by ggVGc** [neovim/neovim#3403]
When in a terminal buffer, executing :normal gives this error message. I understand there's probably some reason for it being introduced(it wasn't there in precious versions of nvim I've tried), but there are multiple scenarios where this seems broken.
Many plugins execute normal mode commands, and this breaks all of them. YankRing is one example, where it executes `:normal gv` in order to select the previous selection. When this runs in :terminal, it instead breaks with this error message.

**Comment by liujoey** [comment]
wellle/targets.vim is another example, when in normal mode in terminal buffer, can't do `vi'` or any text objects selections.

**Comment by tarruda** [comment]
Can you check if #3360 fixes the issue?

**Comment by ggVGc** [comment]
Tried the PR locally, and seems fixed to me. I.e I can execute `:normal <commands>` while in a terminal buffer.
