### ISSUE TITLE
After renaming terminal buffer, loading original buffer destroys terminal without warning

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#3404]
When executing the commands below, the original terminal will get destroyed and a new one will be created without warnings:

```
nvim -u NONE
:te
echo this terminal gets destroyed
<C-\><C-n>
:f gettingdestroyed
:b2
```

**Comment by justinmk** [comment]
Yep, we should not allow renaming terminal buffers at all. It does not make sense, it's like renaming a file.

**Comment by HarmtH** [comment]
I like giving my terminals names, then I know what I'm doing in that terminal. Is there a better way to do that?

**Comment by zeertzjq** [comment]
`:setlocal bufhidden=hide`
