### ISSUE TITLE
Luajit build error on OSX Yosemite

### ISSUE THREAD

**Issue by erf** [neovim/neovim#3406]
I try to run:
<pre>
$ brew reinstall --HEAD neovim
</pre>
on OSX Yosemite, but get the following error:
<pre>
==== Building LuaJIT 2.0.4 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [host/minilua] Error 1
make[3]: *** [src/luajit] Error 2
make[2]: *** [build/src/luajit-stamp/luajit-install] Error 2
make[1]: *** [CMakeFiles/luajit.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/neovim/homebrew-neovim/issues

~ % 
</pre>

Can this be because i installed XCode 6.4 ?

**Comment by justinmk** [comment]
Did you try `xcode-select --install`? See 

https://github.com/neovim/homebrew-neovim/issues/85 https://github.com/neovim/homebrew-neovim/issues/87 https://github.com/neovim/homebrew-neovim/issues/89 https://github.com/neovim/homebrew-neovim/issues/90

**Comment by erf** [comment]
Thanks for you quick reply!
<pre>
~ % xcode-select --install
</pre>
Gives me the following.
<pre>
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
</pre>
I already updated the command line tools, but i then installed xcode 6.4. I now downloaded and installed the command line tools for xcode 7, without effect, but then i reinstalled xcode 7.01, and it works..! But the problem is, xcode 7 screws up my autolayout, so i can't use it.. I need to use xcode 6.4. It's a little troublesome to have to switch between these two versions each time i need to update neovim.. Could this be fixed?

**Comment by fwalch** [comment]
I think you need to have Xcode and Xcode CLT both of the same version, then it should work.

**Comment by erf** [comment]
Yes i need to keep both. Thanks! I think you can close this issue then. Just be aware you need xcode 7 for neovim to install.

**Comment by fwalch** [comment]
> Just be aware you need xcode 7 for neovim to install.

.. or Xcode CLT 6.4, no?

**Comment by erf** [comment]
I uninstalled xcode 7 now and installed xcode CLT 6.4 and that worked as well thanks @fwalch , now i just need to remember not to update them..

**Comment by neumanrq** [comment]
Hm, unfortunately I have Xcode 6.4 installed (Xcode CLT also 6.4) but I ran into the same issues.

**Comment by fwalch** [comment]
You could try just compiling LuaJIT from its tarball. Neovim sets [a few flags](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuajit.cmake#L38-L44), but it's more or less just executing `make`.

**Comment by krisleech** [comment]
I too get this error with XCode 6.4 and XCode CLT 6.4.
