### ISSUE TITLE
iTerm Option key as Esc works in vim but not neovim

### ISSUE THREAD

**Issue by katylava** [neovim/neovim#3412]
I have the following in my .vimrc (which is also my .nvimrc):

```
map <ESC>0 :tabnext<CR>
map <ESC>9 :tabprevious<CR>
```

And in iTerm I have these settings:

<img width="605" alt="preferences" src="https://cloud.githubusercontent.com/assets/10575/10226257/11d83ad8-682c-11e5-84d2-d2aae00b4d41.png">

So when I press Left-option+0 or Left-option+9 I navigate tabs in vim. neovim doesn't seem to recognize whatever iTerm does to send option as esc.

**Comment by tarruda** [comment]
This is a temporary limitation of our terminal UI. Can you configure iterm to send two consecutive Esc bytes instead of one? So for example, instead of sending `\x1b0` left-option+0 will send `\x1b\x1b0`?

The problem is that `map <ESC>0` in nvim only works if the TUI sends the ESC key, and I think libtermkey will eat sequences it doesn't recognize from terminfo.

**Comment by katylava** [comment]
If it's possible to configure iTerm to do that, I don't know how. The little `+` button on the "keys" preference pane only lets me input key combinations. Entering left-option by itself does nothing.

I'll just have to find a different mapping or press the actual escape key in the meantime.

**Comment by justinmk** [comment]
Why not configure iterm to send meta, then use these mappings?

    map <m-0> :tabnext<CR>
    map <m-9> :tabprevious<CR>

**Comment by katylava** [comment]
iTerm warns not to do that:

<img width="420" alt="blank_skitch_document" src="https://cloud.githubusercontent.com/assets/10575/12521865/daaa95ac-c112-11e5-91f6-1fc730e0ad99.png">

But I tried it anyway... it doesn't work.

**Comment by justinmk** [comment]
@katylava What `:version` ? This was fixed a few weeks ago on master.

**Comment by katylava** [comment]
Homebrew-installed...

```
NVIM 0.1.0-dev (compiled Nov 29 2015 14:20:06)
Commit: a03af86cc28d9e755f5941b5dfaf54d003a1ad97
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -W
vla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151129-30439-isavmk/build/config -I/tmp/n
eovim20151129-30439-isavmk/src -I/tmp/neovim20151129-30439-isavmk/deps-build/usr/include -I/tmp/neovim20151129-30439-isavmk/deps-build/usr/include -I/tmp/neovi
m20151129-30439-isavmk/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151129-30439-isavmk/deps-build/usr/include -I/tmp/neovim20151129-30439-isavmk/deps-buil
d/usr/include -I/tmp/neovim20151129-30439-isavmk/deps-build/usr/include -I/tmp/neovim20151129-30439-isavmk/deps-build/usr/include -I/usr/local/opt/gettext/incl
ude -I/usr/include -I/tmp/neovim20151129-30439-isavmk/build/src/nvim/auto -I/tmp/neovim20151129-30439-isavmk/build/include
Compiled by kyl@potentiator.home

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Not sure how to update, but I'll figure it out. Thanks.

**Comment by justinmk** [comment]
Try it with both settings, after upgrading.

**Comment by katylava** [comment]
I upgraded and it works now with `<m-*>` instead of `<Esc>*`. Thanks!

**Comment by justinmk** [comment]
Ok that makes sense, the "meta" option sets the high bit, cf. [iTerm docs](https://www.iterm2.com/documentation-one-page.html):

> The "Meta" option sets the high bit of the input character, and is not compatible with modern systems.

Esc is what we want. Thanks for followup @katylava

**Comment by betoop** [comment]
FYI, I had a similar issue moving to the next word with Option+Right, using the "Natural Text Editing" Keys profile on iTerm. 

I had to change the mapping of `⌥ + →`  to _Send Hex Code_ `0x1b 0x1b 0x5b 0x43`.
Additionally, I did the following mapping: `map <m-right> w<CR>`.
