### ISSUE TITLE
Allow to move tabline to bottom

### ISSUE THREAD

**Issue by kiritsuku** [neovim/neovim#3415]
It doesn't seem to be possible to move the tabline to the bottom, below the statusline. It would be nice if Nvim would support this, especially when one considers that Nvim nowadays can replace some parts of the functionality of tmux. Vim tabs could be used as tmux windows and tmux by default has them at the bottom.

**Comment by justinmk** [comment]
Ultimately the goal (in my opinion) is to make these types of features (such as tabline and statusline) exposed as API calls so that a UI can put them wherever it feels like. E.g.: `vim_tabline_get` and `vim_statusline_get`. 

At present, a UI can already construct a tabline completely without the help of VimL by getting the current buffer properties and then building an arbitrary display based on that.

**Comment by justinmk** [comment]
External UIs can show the tabline anywhere, via `ext_tabline`.

**Comment by aemonge** [comment]
So I would have to modify the neo-vim CLI version to move it ?   Or can it be done by plugin ?

I don't' really understand what would an External UI be..... do know any examples ?

**Comment by justinmk** [comment]
See the wiki.

**Comment by eternaleye** [comment]
@justinmk: I'm not sure I follow. Where on the wiki? Is this in answer to "would I have to modify the cli frontend", "can it be done via a plugin", or "any examples of an external UI"?

**Comment by justinmk** [comment]
UIs can do it : https://github.com/neovim/neovim/wiki/Related-projects#gui

Oni for example. 

That's the current status.

**Comment by bfredl** [comment]
One day a more flexible TUI might be reimplemented on top of modernized external UI protocol. No promises though. (but I think it is more promising than adding more ad-hoc logic to screen.c only for TUI)

**Comment by justinmk** [comment]
Yes, when libtickit is ready a new TUI could be built as a consumer of `ext_*` UI events.

**Comment by justinmk** [comment]
covered by https://github.com/neovim/neovim/issues/1435
