### ISSUE TITLE
Persistent blank zone on tabpage/window after switching tabpage

### ISSUE THREAD

**Issue by romgrk** [neovim/neovim#3418]
Hello,

The following issue arise when switching tabpages. Usually it happens the first time I switch tab, and doesn't repeat after, although I couldn't confirm.
On switching, part of the editor remains blank, as if there was a phantom window.
Illustrated on the image below. (right of the screen)

![screenshot_nvim_blank_2](https://cloud.githubusercontent.com/assets/1423607/10262664/fcea9ace-699f-11e5-83e4-7c62b77e5f17.png)

Further attempts to switch/close windows on the affected tabpage produce more noise on the region.
The tabpage has to be closed. The blank region doesn't appear on other tabpages.
EDIT: After further testing, it seems to reset after spliting/closing windows multiple times.

![screenshot_nvim_blank](https://cloud.githubusercontent.com/assets/1423607/10262665/fceafbae-699f-11e5-9d7e-ca7f8116e31e.png)

**Comment by justinmk** [comment]
Need reduced steps. I haven't seen this behavior on any system.

**Comment by StanislavNikolov** [comment]
Can you give the developers more info? Terminal emulator, special window-management plugins, etc.

**Comment by romgrk** [comment]
GNOME terminal 3.18.0, sometimes through nvim-wrapper (https://github.com/fmoralesc/neovim-gnome-terminal-wrapper)
NVIM 0.0.0-alpha+201510011537 (compiled Oct  2 2015 07:42:46)

Window-managing plugin (of mine): https://github.com/romgrk/winteract.vim
I usually switch tabs through it, which means calling either `:tabnew`, `:tabnext` or `:tab sview %`.

I don't seem to be able to reproduce it right now. I'll update as soon as it happens again, with more detailed info.

**Comment by justinmk** [comment]
So this is an interaction between a plugin and a GUI. It would be best to discuss such issues on the plugin repo or IRC etc, until it can be reproduced with `nvim -u NONE `.

**Comment by fmoralesc** [comment]
@justinmk There isn't really a GUI here, the wrapper is just a custom launcher for gnome-terminal, so the behavior should be the same as outside of it.

**Comment by romgrk** [comment]
As @fmoralesc said.

So it happened again, but I have no more info to provide. The steps this time are:
- `:execute n . 'wincmd w'`
- `<C-W>c`
- blank zone appears

I have it open with the blank zone still appearing, if there is any sort of dump/log I can produce from here, please let me know I'll be happy to provide it.
