### ISSUE TITLE
Expose "startup" phase in runtime

### ISSUE THREAD

**Issue by commonquail** [neovim/neovim#3421]
#2929 introduced [a "startup" phase](https://github.com/neovim/neovim/commit/9468e538694cd16847586c66de6e16ee7a090577#diff-bb912bedf9ba67ca53f13d28e86537b9R638) outside of which some settings cannot be modified. For now, only `encoding` seems to be restricted in this way.

I have a vimrc that sets `encoding`, because I don't want to have to trust the environment, and that auto-sources on write, because I'm lazy. Since the change to `encoding`, this setup causes an error (the new E905). I can find no way to determine if Neovim is presently in the startup phase, so I can't conditionally set `encoding`. I can't *not* set `encoding` because the default value is variable, and disabling auto-sourcing does not really solve the problem, which is that I have to restart Neovim for configuration changes to take effect.

Can this stage be exposed so it can be checked for? The best I can do now is something like `if exists('did_load_ftplugin')`, but only because I enable that later.

```bash
$ nvim --version
NVIM 0.0.0-alpha (compiled Oct  2 2015 20:39:53)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/build/config -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/src -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-bWyI8D/neovim-0.0.0+git201510021926+1924+14~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-36

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by fmoralesc** [comment]
Set up a flag on `VimEnter` and test for it before trying to set up `encoding`:

~~~ vim
au! VimEnter * let g:vimentered = 1
if !exists('g:vimentered')
   set encoding=utf8
endif
~~~

Also see https://github.com/neovim/neovim/pull/2905

**Comment by bfredl** [comment]
a simple but ugly workaround is also

    if &enc != "utf-8"
        set enc=utf-8
    endif

A temporary workaround for `&encoding` would be to allow to always set the current value, like I intend in #2905 , but if we plan to reuse the "only settable on startup" pattern, it would be good with an idiomatic way to check it.

**Comment by bfredl** [comment]
maybe`has("vim_starting")` works for this?

**Comment by fmoralesc** [comment]
`vim_starting` should totally work, yes. :+1:

**Comment by ZyX-I** [comment]
Why bother any conditions if you can simply use EAFP approach?:

```VimL
try
    set encoding=utf-8
catch /^Vim(set):E905:/
endtry
```

**Comment by justinmk** [comment]
`has("vim_starting")` is what you want. You should do this for Vim as well, because changing encoding in Vim at runtime is undefined behavior.
