### ISSUE TITLE
pasting into :term is broken

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3426]
Reduced steps:

1. nvim -u NONE
2. `:terminal`
3. Paste any text (using CMD+V on OSX)
4. Result is `??????a??????`

This breaks pasting into FZF.

**Comment by bambu** [comment]
It works for me doing `:terminal`. However if I do `:terminal ipython` and then paste i get the same type of output. This seems to also work on the homebrew version that i have (2417aeebbffe58eab6ac39feac0f64a27aafbee2)

Pasting to terminal works for me on any commit prior to: 1143b416ab7d8bb1707dab2be2cd9e191f9a03e4

**Comment by ZyX-I** [comment]
Why there are two open issues for this? #3476 contains more messages, so I close this.
