### ISSUE TITLE
Neovim and Linux tty

### ISSUE THREAD

**Issue by orang-outan** [neovim/neovim#3428]
Hello everyone,
I am currently trying to use Neovim in a TTY. There are some issues with the highlighting. 
Neovim doesn't know how to print a Red color with ctermfg=red but with the ansi number that works.
That works too if nvim is launched from tmux. 
I don't know how to remap correctly the colorname to its numbers.

Maybe you have a solution ?
(and where is gone t_Co from vim)

Edit: There is a tricky solution. Activate the True colors support. But this mode is ruled by gui in the highlight config.

**Comment by cacplate** [comment]
if you want true colors, place `let $NVIM_TUI_ENABLE_TRUE_COLOR=1`.
This replace `t_Co` behaviour. I don't know enough to help more, sorry.

**Comment by justinmk** [comment]
I think we need to drop down to 8 colors if TERM=linux

**Comment by jalvesaq** [comment]
The small change below fixes the problem for `TERM=linux`, but not for `TERM=screen` when Tmux is running in Linux TTY.

```diff
diff --git a/src/nvim/main.c b/src/nvim/main.c
index d3cdfe3..cb10898 100644
--- a/src/nvim/main.c
+++ b/src/nvim/main.c
@@ -273,7 +273,10 @@ int main(int argc, char **argv)
     printf(_("%d files to edit\n"), GARGCOUNT);
 
   full_screen = true;
-  t_colors = 256;
+  if (strcmp(getenv("TERM"), "linux") == 0)
+      t_colors = 8;
+  else
+      t_colors = 256;
   check_tty(&params);
 
   /*
```

**Comment by akavel** [comment]
I've tested on my console (tty, TERM=linux), that with ANSI codes I'm able to get ~16 colors (`\033[30m` to `...[37m`, plus `...[30;1m` to `...[37;1m`), and similar number of combinations for background colors (`\033[40m` to `...[47m`, plus `...[40;5m` to `[47;5m`). But nvim seems only to be able to access the "lower" half (8) of fg colors via ctermfg+cterm+term (so I suppose that the same applies for bg colors). Can anybody point out for me where does nvim contain code translating from *ctermfg* & *ctermbg* & *cterm* to final escape codes to be printed on terminal? or what library funcs does it use to do that? I'd try to fix this, but I don't know what funcs to search for...

**Comment by justinmk** [comment]
@akavel checkout syntax.c, start with `do_highlight`.

**Comment by akavel** [comment]
I skimmed over the `do_highlight`, but it seems to mostly set stuff in some table (HL_TABLE). I didn't state this clearly enough, sorry, but what I'm actually having trouble with, is finding the final part, where the actual *escape codes* are generated and *printed to the terminal*. But now that you said, I noticed the func does seem to also do some additional stuff in a few cryptically named calls near the end; is one of them where I should look to find ANSI codes or termcap access? For example, `ui_refresh` or `set_hl_attr`? or does `redraw_all_later` trigger something and I should try to chase that breadcrumb?

**Comment by justinmk** [comment]
@akavel `screen_char` (and `ui_putc` and `ui_puts`) does the printing.

Before that, `syn_id2attr` gets the attribute value, `syn_current_attr` returns that eventually to `win_line()` which is where the magic happens: somewhere in that mess, the global `ScreenAttrs` is updated. `ScreenAttrs` is a parallel structure that applies to `ScreenLines`, which contains the state of the screen, which is used by `screen.c` to draw the screen. See the top of `screen.c` for details.

**Comment by akavel** [comment]
@justinmk thanks, that helped a lot! I've plugged some *fopen("/tmp/dbg")* and *fputs/fwrite/fprintf* into `unibi_out` and `out` funcs in `tui.c` to capture the escape sequences. The captured escape sequences, returned by *unibi_get_str* and *unibi_get_ext_str*, appear to be correct, and match [what is returned by *tput*](http://linuxcommand.org/lc3_adv_tput.php). But the final escape codes are bad as for TERM=linux, resulting in e.g. `\033[312m`, where TERM=linux allows only up to `...[39m`.

Then I tried applying [@jalvesaq's patch](https://github.com/neovim/neovim/issues/3428#issuecomment-187129514), and it really does seem to dramatically improve the situation. With it applied, `:source runtime/syntax/colortest.vim` gives generally correct results. Specifically, looking at colour red:
- *darkred_on_...* — shows correctly as dark red;
- *red_on...* and *lightred_on_...* — show the same ("bright" red); they seem to get the "bold" attribute added (`\033[1m`)
- *..._on_darkred* — shows correctly;
- *..._on_red* and *..._on_lightred* — shows same as *..._on_darkred*; could be better, but is certainly an improvement over current state of affairs.

Ideally, on my Linux PC, the *..._on_lightred* should also emit "blinking" attribute (`\033[5m`), but I'm not sure if that would be ok for everyone — can there be terminals which would actually show it as blinking instead? So, my recommendation would be to go on with the aforementioned patch at the time being. Given that I'd prefer not to steal the contribution, I'd like to ask @jalvesaq here - **are you planning to submit a PR with your patch?** but if you won't reply in a few days, I'll take the liberty of sending a similar patch myself, to advance the situation. Thanks anyway!

As a next step, if the assumption is that "blinking" is really blinking only on "legacy terminals" and neovim is OK with breaking "compatibility" here, then someone could probably try enabling `\033[5m` for light backgrounds, if it would be not too hard.

**Comment by jalvesaq** [comment]
@akavel My patch was an ad hoc change to improve my particular case, and I guess it will not fix anything in other Unix-like systems. Moreover, I almost never use the linux console.  So, please, go ahead and submit the PR, changing anything that you think is necessary. Thanks!
