### ISSUE TITLE
enhancement for nvim_python.txt to provide instructions for testing if python has been installed

### ISSUE THREAD

**Issue by snowch** [neovim/neovim#3429]
There is a possibility for a slight improvement to the nvim_python documentation:

```
==============================================================================
2. Quickstart						 *nvim-python-quickstart*

If you used a package manager to install Nvim, there's a good chance that
it also provides the `neovim` Python package. If it doesn't, follow these
steps to install the package with Python's package manager, `pip`.
```

It would be good if the documentation provided a command here that the user could run to see if the neovim Python package has been installed so they don't have to try and figure out what was installed by their package manager.

```
Note: Depending on your system, `pip` might refer to Python 2 or Python 3,
      which is why the following instructions mention `pip2` or `pip3`
      explicitly. If one of these is not available for you, maybe `pip`
      is what you want.
```

Source: https://github.com/neovim/neovim/blob/master/runtime/doc/nvim_python.txt

**Comment by justinmk** [comment]
@fwalch  has mentioned a function that can be called (what was it?).

You can also just check 

    :echo has('python') has('python3')

**Comment by fwalch** [comment]
@justinmk I think you're referring to https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working
Not sure if that should go into the manual, though.

**Comment by justinmk** [comment]
I don't really know what to do with this. Feel free to send a PR with a concrete suggestion.
