### ISSUE TITLE
Warning messages on resource `.nvimrc` about utf

### ISSUE THREAD

**Issue by jbaum98** [neovim/neovim#3435]
My `.nvimrc` contains the following lines:

    scriptencoding utf-8
    set encoding=utf-8
    set fileencoding=utf-8

When I execute `:so ~/.nvimrc`, I get the following error messages:

    Error detected while processing /home/jake/.nvimrc:
    line    4:
    E905: Cannot set this option after startup: encoding=utf-8

This only happens in neovim, not in vim. I'm on Ubuntu Trusty with Vim 7.4 and Neovim 0.0.0-alpha+201510042257 (compiled Oct  7 2015 15:39:03)

**Comment by justinmk** [comment]
Read the help.

**Comment by languitar** [comment]
What is the solution to this? I can't find anything in the help how to overcome this apart from the reason why it doesn't work.

**Comment by justinmk** [comment]
You don't need to set this option, it is utf8 by default.

**Comment by jamessan** [comment]
Even in Vim, there's no reason to set `'encoding'` again after the initial sourcing of your vimrc.  It's best to guard it if you really want to be able to re-`:source` your vimrc during a running session, just like you need to do for various other things that may be in your vimrc.

```vim
if !exists('g:encoding_set') || !has('nvim')
    set encoding=utf-8
    let g:encoding_set = 1
endif
scriptencoding utf-8
setglobal fileencoding=utf-8
```

Everything encoding related should be performed after `'encoding'` is set and then `'encoding'` should never be changed again for that session.

**Comment by languitar** [comment]
Ok, but scriptencoding should probably also go into the if section. I get the same warning for this setting.

**Comment by jamessan** [comment]
Are you sure you're sourcing the right file?  `:scriptencoding` shouldn't be causing the E905 warning.

**Comment by languitar** [comment]
Strange, you are right. I thought I also received a warning there.
