### ISSUE TITLE
Add strikethrough support in terminal

### ISSUE THREAD

**Issue by sp5** [neovim/neovim#3436]
There's an unmerged [patch](https://groups.google.com/forum/#!msg/vim_dev/yUyvmKIG8-Q/8qqG29Kme2EJ) to add strikethough support to Vim. Most likely very little of the code in the patch can be used.
Once implemented, this could also allow strikethough to work in Neovim's terminal (it currently doesn't).

**Comment by Nudin** [comment]
I've started hacking on this, but unibilium laks support of strikethrough and I don't feel able to edit this too. I opend a [Issue](https://github.com/mauke/unibilium/issues/22) to unibilium.

**Comment by leonerd** [comment]
As commented in unibilium: I'm not aware of there being a standard terminfo entry to describe strikethrough. Even if there is, I've never seen a terminfo entry about any terminal I use that contained it. So you are probably out of luck waiting on this from unibilium.

As a short-term measure you'll have to hack it in some other way. Longer-term when libtickit becomes sufficient to run nvim from, that will handle strikethrough anyway.

**Comment by justinmk** [comment]
see https://github.com/mauke/unibilium/issues/22#issuecomment-325239028

**Comment by jajajasalu2** [comment]
Hey, I'd like to get on this if no one else already is. 

> Sample code to achieve this with unibilium: mauke/unibilium#22 (comment)

An implementation of this in `src/nvim/tui/tui.c` should get this done. Would it be a viable solution?

**Comment by justinmk** [comment]
@jajajasalu2 great! yes, that's the typical way. Shouldn't be much code, we only need someone to test it (preferably with a terminal that actually supports it).

Note that this also should include the `HL_STRIKETHROUGH` changes from https://github.com/vim/vim/commit/cf4b00c856ef714482d8d060332ac9a4d74e6b88 (we don't need the `gui_*` changes from there, Nvim GUIs will simply look at the `:help ui-event-hl_attr_define` event, which also needs a new `strikethrough` field).

**Comment by leonerd** [comment]
If you need a terminal to test it with, note that `pangoterm` supports it ;)

You can try that with

```sh
$ echo -e "\e[9mstrike\e[m"
```

**Comment by Nudin** [comment]
There are plenty of terminals supporting it. Including Konsole (KDE), all libvte based (gnome-, lxde- and xfce-terminal) and fira.

**Comment by unrelentingfox** [comment]
Hello, I am trying to get this functionality to work on macOS using the nightly build, currently v0.5.0-dev+1265-g66f9dd3c6, but I've also tried this on 0.4.0.

My terminal is iterm2 with tmux, which does support strikethrough as far as I can tell from running this command:
`echo -e "\e[9mstrikethrough\e[0m"`

However, inside neovim, when I try doing something like:
`:hi Normal cterm=strikethrough`

Nothing happens. Any idea where I might be going wrong here?

**Comment by mhinz** [comment]
Then your terminfo database is likely out-of-date. `brew install ncurses` should get you ncurses 6.2 with an up-to-date database.

smxx/rmxx needs to be set for your `$TERM`:

```
infocmp -x | grep -E '(rm|sm)xx'
        kUP7=\E[1;7A, rmxx=\E[29m, smxx=\E[9m,
```

Please use https://neovim.discourse.group for further questions about configuration. :)

**Comment by unphased** [comment]
For posterity... It took me a lot of searching to find out that `tic -x` is how you must compile a modified terminfo definition that has these capabilities. This is the proper way to get neovim to understand what to do. 

I was able to get strikethrough finally plumbed through from nvim thru tmux to alacritty by adding `rmxx=\E[29m, smxx=\E[9m,` to my xterm-256color-italic terminfo file and compiling it with `tic -x`. 

Since this is making me realize that my terminfo files and configs are surely out of date, and that the instructions for building alacritty do install an alacritty terminfo file I'm going to see about changing everything, but I'm still in the dark about what TERM to tell tmux to set.
