### ISSUE TITLE
Cursor not being moved left by one column when leaving insert mode

### ISSUE THREAD

**Issue by undergone** [neovim/neovim#3437]
Currently there is no "proper" way to override this behaviour. A number of solutions are available but they all end up breaking something else, at least the ones that I've tried. Ideally there there should be an option to toggle the feature.

I don't know neovim codebase but my assumption would be this shouldn't be a difficult one to implement and many would appreciate it.

**Comment by justinmk** [comment]
> A number of solutions are available but they all end up breaking something else

How would making this configurable avoid breaking those things? This would break plugins. You can add a `InsertLeave` autocmd to achieve this, but I recommend just getting used to it.
