### ISSUE TITLE
Support for Horizontal Scrolling 

### ISSUE THREAD

**Issue by bambu** [neovim/neovim#3440]
Currenlty neovim supports scrolling Up and Down. It appears that there is documentation and references in the code to `<ScrollWheelLeft>` and `<ScrollWheelRight>` for horizontal scrolling. However, for these two cases the code leads to a dead end as the functions that handle scrolling `scroll_redraw`, `nv_mousescroll`, `ins_mousescroll` seem to only take into account scrolling up and down. 

In order to test:
`nvim -u NONE +'norm 100iabcde' +'set nowrap' +':0'`
After nvim loads, try to scroll left/right (need to have either a trackpad or a mouse that allows horizontal scrolling)

**Comment by bambu** [comment]
@justinmk I was able to add support for this, and from what I can tell it works pretty well. However I have a question before submitting a pull request. 

In order to get it to work, i had to pull some code from vim's `gui.c` file which is not in the neovim source. should I put this code in `normal.c` (where the vertical scroll code is) or `tui.c`? 

The functions that I copied over are:
```
gui_do_horiz_scroll
gui_find_longest_lnum
scroll_line_len
```

**Comment by justinmk** [comment]
@bambu `normal.c` or possibly `mouse.c` if you can do it without including `normal.h`.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/3450

**Comment by kassio** [comment]
Should this work on terminal? I'm trying to use horizontal scroll on iTerm2(Build 3.1.beta.3), NVIM v0.2.1-29-g631d55ad, but it's not working.
