### ISSUE TITLE
Add filetype support for LESS / incorrect `vim-patch.sh -l`?

### ISSUE THREAD

**Issue by rosston** [neovim/neovim#3441]
Vim added filetype support for LESS by bringing [vim-less](https://github.com/genoma/vim-less) into the main project. The relevant commit (https://github.com/vim/vim/commit/8feef4ff6253afb9dcc61c40082ed4fbb96b685c) appears to have been added in 7.4.567.

Running `scripts/vim-patch.sh -l` (with git > 2.4, as per the warning) shows neither 7.4.567 nor `8feef4f` as missing patches, but `runtime/ftplugin/less.vim` doesn't exist in `neovim#master`.

It looks like [vim-patch.sh only checking](https://github.com/neovim/neovim/blob/master/scripts/vim-patch.sh#L171) non-versioned commits since `e2719096` (which came after `8feef4f`) is the cause. If I change vim-patch.sh to check non-versioned commits since https://github.com/vim/vim/commit/a162bc555e74c1a4f1b7b49871e292e05141b054, `8feef4f` shows up as a missing patch.

Should vim-patch.sh actually be looking at non-versioned commits even further back? Or should I just submit a PR including `8feef4f`?

**Comment by justinmk** [comment]
You are right, we missed 8feef4ff6253afb9dcc61c40082ed4fbb96b685c. That is my mistake I believe.

> Or should I just submit a PR including 8feef4f?

That would be best :)

**Comment by rosston** [comment]
I tried using vim-patch.sh to apply the patch, but `runtime/doc/tags` doesn't exist anymore, and I ended up with rejects for `runtime/doc/todo.txt`, `runtime/ftplugin/man.vim`, and `runtime/syntax/r.vim`. And the diff is just generally scary to me: https://github.com/vim/vim/commit/8feef4ff6253afb9dcc61c40082ed4fbb96b685c.

I'd love to help, but I'm pretty sure I'm out of my depth here!

**Comment by justinmk** [comment]
Ignore all changes to `man.vim` and even `todo.txt`. Everything else should apply pretty easily, there might be some conflicts with dates, but that is easy to resolve :)

**Comment by justinmk** [comment]
Note to self: update `vim-patch.sh` to discard all changes to `docs/tags` and `man.vim`.

**Comment by rosston** [comment]
Thanks for the guidance! Just added a PR: https://github.com/neovim/neovim/pull/3444

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/3444
