### ISSUE TITLE
Mouse middle button pasting not working in NORMAL mode

### ISSUE THREAD

**Issue by yan12125** [neovim/neovim#3447]
Operating system: Arch Linux
Desktop: xorg-server 1.17.2-4 + xfce4-session 4.12.1-3
Terminal: xfce4-terminal 0.6.3-2
NeoVim: (Installed with AUR script https://aur.archlinux.org/packages/neovim-git/)

```
$ nvim --version 
NVIM 0.0.0-alpha+201510071705 (compiled Oct  8 2015 20:56:22)
Commit: cd6b4af649ac1cfbfa5db82ce299a4c7bb83054e
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/yaourt-tmp-yen/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-yen/aur-neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/yaourt-tmp-yen/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-yen/aur-neovim-git/src/neovim-git/build/include
Compiled by yen@PC951

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"
```

Steps to reproduce:
1. Select some texts in the terminal
2. `/usr/bin/nvim -u NONE`
3. `i` to enter the INSERT mode
4. Hit the mouse middle button
5. `ESC`
6. `:tabe`
7. Hit the mouse middle button

Expected results: the previously selected text pasted in both step 4 and 7
Actual results: texts pasted in step 4 while nothing happens in step 7

Note: If I replace /usr/bin/nvim with /usr/bin/vim in the step 2 and use the following `vimrc`:

```
set nocompatible
set mouse=a
```

Everything works.

**Comment by xsteadfastx** [comment]
the same for me

**Comment by JonathanSeguin** [comment]
I am getting the same behavior

**Comment by yan12125** [comment]
Today I find it suddenly fixed. Now works fine with:
```
xorg-server 1.18.3-1
libinput 1.3.0-2
xfce4-session 4.12.1-4
xfce4-terminal 0.6.3-3
neovim-git 0.1.4.r264.g46a0800-1
```
And according to my package upgrade log, libinput is 1.0.1-1 on 2015/10/11.

I don't know what's the key change, though.

**Comment by giuscri** [comment]
I can reproduce. If I `:set mouse=n` or `:set mouse=a`, it works fine.
