### ISSUE TITLE
Mouse x position wraps after column 255

### ISSUE THREAD

**Issue by gyscos** [neovim/neovim#3451]
With `mouse=a`, mouse actions (clicks or drags) have their `x` position wrapped at column 255. Attempting to click on the character on column 256 clicks the column 0 instead.

On the original `vim`, a worse version of this bug exists, where the mouse cannot click cells after column 123.

To reproduce:
On a large enough `nvim` window, write >255 chars: `260 i a <ESC>` then attempt to click on the last characters of the line with little success.

EDIT: issue appears on `xfce4-terminal`, but not on `gnome-terminal` or on `konsole`. :-S So maybe a terminal issue instead?

**Comment by Hettomei** [comment]
Hi, 

same problem here but when click on 263 char. (262 works, 263 does nothing, 264 send to first char on same line)

To reproduce : 

```bash
# my_file.txt is a file with more than 300 char on first line
nvim -u NONE my_file.txt
:set statusline=%c
# click on char 262,263...
```

```
Ubuntu 14,
nvim --version
NVIM 0.0.0-alpha+201510042257 (compiled Oct  7 2015 09:34:54)
Commit: 7be75a02917b40e5791e3f98d177f833a348df35
```

**Comment by mathias-baumann-sociomantic** [comment]
Someone mentioned that this might be related to the SGR mouse support. Only terminals that support that support columns > 2??.

**Comment by mathias-baumann-sociomantic** [comment]
Regarding ticket #3458, I know that urxvt does NOT support mouse SGR but that they rolled some own invention. Will probably need extra code to support.

**Comment by oux** [comment]
I wasn't able to click after the column 222 on NVIM 0.1.0 on urxvt with and without tmux, I just updated to NVIM 0.1.1, Now I'm blocked on column 255 on urxvt without tmux but still blocked on column 222 with tmux.

**Comment by egmontkob** [comment]
You might find these links useful:
https://www.midnight-commander.org/ticket/2662
https://www.midnight-commander.org/ticket/2956

**Comment by egmontkob** [comment]
Note that the presence of tmux might significantly change the game. I can't recall which extensions it supports (maybe it's not even the same set "inside" and "outside"), but I'm fairily sure it does not necessarily speak the same at the same time in the two directions. E.g. it might receive urxvt-style extension from the emulator and forward xterm-style extension towards the application, or the other way around.

**Comment by egmontkob** [comment]
By far the best solution would be (in the long run, and for the benefit of plenty of apps rather than just neovim) if urxvt added SGR 1006 support. It would be a tiny change to their source. I tried to convince the author a couple of years ago but I totally gave up. Maybe a few popular distros should patch it downstream. Or does anyone feel like trying to convince him?

**Comment by guyzmo** [comment]
I'm also having this issue, with gnome-terminal, and starting at column 231 (included).

**Comment by rivertam** [comment]
having this issue in xfce4 terminal, no tmux or anything.

**Comment by egmontkob** [comment]
xfce4-terminal uses the ancient, unmaintained and freaing buggy gtk2-based VTE widget which does not support the mouse protocol extensions.

**Comment by rivertam** [comment]
@egmontkob Is the solution to not use xfce4-terminal? I don't think I'd have a problem with that, but it wouldn't be non-annoying to convert.

**Comment by egmontkob** [comment]
@rivertam Yup I'm afraid so. You might check out its progress in updating to gtk3-based vte at https://bugzilla.xfce.org/show_bug.cgi?id=11207 but I think it's far from being stable/usable.

The bug definitely shows up in any program that handles mouse and you wish to use that beyond column 223.

**Comment by rivertam** [comment]
Ah, alright then. While we're here, mind recommending an emulator that works right?

**Comment by egmontkob** [comment]
Pretty much every emulator works right. Notable exceptions are the ones based on VTE and GTK+-2; also I don't know if urxvt works or not (it supports a mouse extension, but not the one widely adopted, I don't know if neovim suports that extension or not).

I've been a heavy contributor (maintainer if you wish) to the GTK+-3 based VTE (as well as gnome-terminal a bit), so my personal recommendation goes for any emulator using this (e.g. gnome-terminal, roxterm, terminix, terminator's gtk3 bzr branch etc.). Other choices include xterm, konsole, terminology and probably a few more.

**Comment by rivertam** [comment]
Thanks!

**Comment by guyzmo** [comment]
FYI, after years being happy with vim and older gnome-terminal, I have been having issues with latest (at least within debian stable) gnome-terminal (color support, mouse limit, transparency support being removed...) so I switched to roxterm and I'm very happy (and I even got true colour support for free!). So thank you @egmontkob for your contributions! :-)

**Comment by justinmk** [comment]
If I understand correctly, this is dependent on the terminal, and there's nothing to change on our side.
