### ISSUE TITLE
problem with cursor shape inside Guake terminal

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3455]
when i enable cursor shape 

      let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1 

i get a wired q carracter when i switch to insert mode

**Comment by jszakmeister** [comment]
I bet the VTE version it's using doesn't support the DECSCUSR escape sequences.  IIRC, you need VTE version 0.39.0 or better for it to work.

**Comment by 7belrhalmia** [comment]
@jszakmeister how can i add it to guacke terminal

**Comment by jszakmeister** [comment]
I don't understand your question.  I think the short form is that you can't.  If the underlying VTE library doesn't support it, then Guake doesn't either.

What does `echo $VTE_VERSION` say in your terminal?

**Comment by 7belrhalmia** [comment]
@jszakmeister it give nothing

**Comment by jszakmeister** [comment]
Then the VTE library used by Guake isn't new enough.  Sorry, but you'd either have to build Guake yourself with a newer set of dependencies, upgrade your distro, or something along those lines to fix the issue.

**Comment by Sadario** [comment]
I also get the issue of this rogue, ugly character messing up my Nvim-experience in Guake. Output of "echo $VTE_VERSION" = 4402 (I just installed guake from source). No issue in standard Ubuntu-terminal. 
Whether "let $NVIM_TUI_ENABLE_CURSOR_SHAPE" is set to 0, or 1, does not make a difference. Was working fine a few builds ago.

**Comment by justinmk** [comment]
@Sadario Please see https://github.com/neovim/neovim/wiki/Following-HEAD#20170402
