### ISSUE TITLE
need double <Esc> to quit insert mode and command mode when rsi.vim is loaded

### ISSUE THREAD

**Issue by liujoey** [neovim/neovim#3456]
in neovim, when `tpope/vim-rsi` is loaded, I need to press `<Esc>` twice to quit insert mode or command mode.

I've tested it with both vim and nvim, it only occurs in neovim. In my .nvimrc file I have only one line to load the vim-rsi plugin, no other settings.

my nvim is complied on commit: 536c0ba

**Comment by tarruda** [comment]
Update and recompile, should be fixed

**Comment by liujoey** [comment]
yes, it was fixed, sorry for this stupid issue, I should have update and recompile first :)
