### ISSUE TITLE
Cleanup `iconv` build system flags

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#3457]
`iconv` support was reenabled in #1370 but the iconv detection and code could use some cleanup. A quick grep through the code shows several iconv related flags
1. `USE_ICONV` is defined in src/nvim/iconv.h and can be true if we are linked against iconv or if we support dynamic loading of iconv
2. `HAVE_ICONV_H` is defined by config/CMakeLists.txt if the header is found
3. likewise `HAVE_ICONV` is defined config/CMakeLists.txt, but it is based on the cmake check in CMakeLists.txt (see `Iconv_FOUND`)
4. `DYNAMIC_ICONV` is meant for loading the iconv dll at runtime (even if the header is not available at build time), but it is never set in Neovim - which makes sense for now since this one is only meant for Windows (mbyte.c).  #10708

Do we want to continue supporting `DYNAMIC_ICONV`? Vim uses dynamic loading and distributes the iconv dll [separately](http://www.vim.org/download.php#pc) - If not, the code can be removed, if we want to keep it we need to check some Vim changes (vim/vim/issues/440).

At least some of this can be simplified in CMakeLists.txt and config/CMakeLists.txt if the FindIconv.cmake is changed to handle the header flag. @justinmk this last bit can be tagged as entry level.

**Comment by laserswald** [comment]
I can help with this.

**Comment by equalsraf** [comment]
hi @laserswald. 

> but what do you mean about "handle the header flag"? 

Right now `HAVE_ICONV_H` is set by config\CMakeLists.txt (check_include_files), but that can be moved into FindIconv.cmake.

Likewise for `set HAVE_ICONV 1` since its basically the same as `Iconv_FOUND`

**Comment by laserswald** [comment]
I'll check it out. I think I have it working, but since I have almost zero experience with cmake, it might be wrong.

**Comment by Pyrohh** [comment]
> Do we want to continue supporting DYNAMIC_ICONV? Vim uses dynamic loading and distributes the iconv dll separately - If not, the code can be removed, if we want to keep it we need to check some Vim changes (vim/vim#440).

Do you know if iconv is generally present on modern Windows systems? If so then it'd be nice to remove `DYNAMIC_ICONV` support, although I didn't find much info besides what's on [the Wikipedia page](https://en.wikipedia.org/wiki/Iconv#Ports).

**Comment by equalsraf** [comment]
@Pyrohh AFAIK iconv is not present. Unless its placed in the path by some third party app.

**Comment by justinmk** [comment]
We should distribute iconv with the Windows build.

**Comment by brcolow** [comment]
This looks interesting:
https://github.com/mlocati/gettext-iconv-windows

**Comment by rafin** [comment]
What's the status on this issue? No discussions has occurred for a couple years.
