### ISSUE TITLE
rxvt, urxvt: mouse-scrolling wraps after column ~222

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [neovim/neovim#3458]
When my mouse cursor moves too far to the right it starts scrolling other buffers than the currently focused one:

![bug](https://cloud.githubusercontent.com/assets/2702644/10489482/9de01d40-729d-11e5-8d2d-78fa14fdcae0.gif)

**Comment by mseeber** [comment]
may be related to #3451

**Comment by belak** [comment]
This is almost definitely a duplicate. I'll leave a little more info in #3451.

**Comment by WilliamSnyders** [comment]
Looks like this used to be handled by `set ttymouse=urxvt`, which was removed.

**Comment by justinmk** [comment]
Pretty sure this was fixed long ago.

**Comment by mathias-baumann-sociomantic** [comment]
I just tested v0.2.3-dev and the problem persists.

**Comment by belak** [comment]
@mathias-baumann-sociomantic Can you confirm which terminal you were using? I just tested this with iTerm2 and it seems to be fixed.

**Comment by justinmk** [comment]
@belak it's a rxvt specific issue

**Comment by mathias-baumann-sociomantic** [comment]
The terminal used was `rxvt-unicode (urxvt) v9.21 - released: 2014-12-31`

**Comment by justinmk** [comment]
To clear things up:

- This is the same issue as https://github.com/neovim/neovim/issues/3451
-  Nvim implements SGR mouse protocol (DECSM 1006). This preferable to rxvt protocol (DECSM 1015) for reasons explained in 2011 vim_dev thread ["Mouse reporting and new standards"](http://vim.1045645.n5.nabble.com/Fwd-Mouse-reporting-and-new-standards-td3378370.html)
- rxvt [could easily support](https://github.com/neovim/neovim/issues/3451#issuecomment-198695984) DECSM 1006 but they don't. It's not reasonable to expect every terminal application to deal with rxvt's quirks, specially for non-technical reasons. 

urxvt is the Internet Explorer of terminals. Use a better terminal.
