### ISSUE TITLE
:rshada (without !) overwrites registers

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3463]
According to `:help :rshada`:

> If [!] is given, then any information that is  already set (registers, marks, v:oldfiles, etc.) will be overwritten.

This implies that registers should not be overwritten without `!`. But that is contrary to the behavior I observe.

Steps:

1. Open 2 `nvim -u NONE` instances ("A" and "B")
2. In A, `:let @a='foo'`
3. In B, `:let @a='bar'`
    - `:echo @a` => "bar"
4. In A, `:rshada|wshada!`
    - `:echo @a` => "foo"
5. In B, `:rshada|wshada!`
    - `:echo @a` => "foo"

**Comment by justinmk** [comment]
Actually, this bug was on an old version. It seems to be fixed on 3a970e57dfd48f090f8ccc21567b7974e13d4c68

**Comment by ZyX-I** [comment]
@justinmk No. With bang it uses registers from shada file *always*. Without bang it uses registers from shada file *if they have greater timestamp*. The sequence of steps also suggest that you have swapped 2. and 3., or there is a bug. Or you really used viminfo which does not care about timing (and I do not really remember what exactly was unconditionally pulled in with viminfo).

**Comment by justinmk** [comment]
@ZyX-I I am using shada, not viminfo. I guess this means `:rshada|wshada!` is not a viable way to sync running instances, if one wants to preserve registers. Do you think `:rshada|wshada!` is a bad idea for any other reason?

**Comment by ZyX-I** [comment]
@justinmk `:wshada!` (with bang) is the worst thing to do if you want to keep marks: banged version removes all buffer-local marks, except for the marks which are present in the currently open buffers. To synchronize you may use `:rshada|wshada` (without any bangs), but that will only pull in registers which are newer. `:rshada!` will pull in registers regardless of the time they were defined, but this does not allow you to “push”, and will also unconditionally pull in the history.

If you want real synchronization you need to use `:rshada`/`:wshada` pair (and it should not matter which of the commands comes first). If you want to push data from one instance to another, and do not loose buffer-local marks, you need to use `:wshada! some-other-file` in one instance and `:rshada! some-other-file` in another.

**Comment by ZyX-I** [comment]
Last thing should come with `&shada` setting manipulations, or you will save and pull in something unexpected.
