### ISSUE TITLE
Create default layout with terminal emulator

### ISSUE THREAD

**Issue by carlitux** [neovim/neovim#3467]
There is any way automate some layout like tmux... but inside vim with terminal emulator. like this?

```bash
#!/bin/sh

# first window just neovim
tmux new-session -d -s project
tmux send-keys nvim C-m
tmux split-window -h -p 40 -t project
tmux send-keys gulp C-m

# Second window will run services and so
tmux split-window -v -p 30 -t project

# tmux select-window -t 1
tmux select-pane -t 1

tmux -2 attach-session -d -t project
```

**Comment by justinmk** [comment]
Vim sessions?

**Comment by torpak** [comment]
or you could put the vim commands to create your layout in a viml function and put that function in your .nvimrc then you could run it when ever you would have run the shell script you showed.

**Comment by tarruda** [comment]
This script should be more or less equivalent to your "first session"

```vim
terminal
call jobsend(b:terminal_job_id, "nvim\n")
split | 3wincmd- | terminal
call jobsend(b:terminal_job_id, "gulp\n")
```
