### ISSUE TITLE
E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 3

### ISSUE THREAD

**Issue by KKPMW** [neovim/neovim#3469]
Hello, Neovim Community,

I just updated neovim and after usual:

* rm -r built
* git pull
* make clean
* make install.

And now after starting nvim I get the following error in the terminal (before nvim starts):

     E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 3
     Press ENTER or type command to continue

Then after I press ENTER nvim starts and everything seems to be fine. And if I am opening a file on startup (`nvim file`) then I again get the same error message once nvim is loaded. Press enter and everything seems to be fine again.

I am running nvim from iterm2 on latest macos.

**Comment by oni-link** [comment]
Build directory is `build`. Perhaps the `.deps` directory also needs to be rebuild. Try `make distclean && make`.

**Comment by myitcv** [comment]
I experienced this as well. I removed `~/.viminfo` - which felt like a hack... but it worked.

Guessing `nvim` should try and seamlessly try and upgrade and old format `~/.viminfo`?

**Comment by ZyX-I** [comment]
@myitcv @KKPMW You must *not* have `n~/.viminfo` in `&shada` option (`&viminfo` option is now an alias to `&shada`). If something else you need to remove the file pointed by the option. Format has changed, as well as its location, old format cannot be parsed and will result in different errors. Also the fact that you are setting `n~/.viminfo` means that you need to share viminfo with Vim which can no longer happen: default location for viminfo is `~/.nviminfo`.

**Comment by myitcv** [comment]
@ZyX-I - exactly as you said, I had (without knowing it):

```
set viminfo='1000,f1,\"500,:1000,%,n~/.viminfo
```

Worth throwing an error of sorts if the user has such a setting?

**Comment by KKPMW** [comment]
Thanks for all the fast replies.

@oni-link thanks for the suggestion. Tried with ` make distclean` but that didn't help in this case.

@myitcv thanks for pointing out .viminfo. my nvimrc actually stored those files somewhere internally I tracked them down, removed them and now it seems to be working without a fuss.

@ZyX-I Thanks for pointing that out. After removing all the old .viminfo files - should I also change the option `viminfo` to something else ? Will this:

    set viminfo+=n~/.nvim/tmpfiles/viminfo

still work?

**Comment by ZyX-I** [comment]
@KKPMW After you remove old file any location will work (as long as its path is not greater then MAXPATHL), including `~/.viminfo`. But it is misleading to call shada file `*viminfo`, and specifically `~/.viminfo` will provoke conflicts with Vim: after old viminfo is replaced with ShaDa file Vim can no longer parse new format.

Changing option name to `&shada` is not needed right now, but I plan to make it be removed in some far future.

**Comment by ZyX-I** [comment]
Current convention for ShaDa files is calling them `*.shada`. This is what #3270 expects.

**Comment by kalbasit** [comment]
updated [Following HEAD](https://github.com/neovim/neovim/wiki/Following-HEAD) page with this info.

**Comment by edenzik** [comment]
+1 
Removing `~/.local/share/nvim/shada/main.shada` worked for me.

**Comment by Anenth** [comment]
`mv ~/.vim/viminfo.tmp.f  ~/.vim/viminfo` worked for me.

**Comment by ibnishak** [comment]
Removing all viminfo files from ~/.cache/vim worked for me

**Comment by hawkinchina** [comment]
I need support for vim and neovim both:
it work for me.

if has('nvim')
    set viminfo+=n~/.vim/dirs/viminfo2
else
    set viminfo+=n~/.vim/dirs/viminfo3
endif
