### ISSUE TITLE
mark 0 is not remembered when exiting Nvim

### ISSUE THREAD

**Issue by nschloe** [neovim/neovim#3472]
I used to use

``` vim
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
```

in my `~/.vimrc` to make sure that (neo)vim jumps to the last position when reopening a file. For a few days now, this doesn't work anymore on neovim nightly.

**Comment by justinmk** [comment]
`:verbose set viminfo?`

**Comment by nschloe** [comment]
What does this mean?

**Comment by ZyX-I** [comment]
@nschloe Type in Vim

    :verbose set shada?<CR>

(`viminfo` is now an alias of `shada` and I prefer not to use the deprecated name) and post the result here.

Also, what exactly does “doesn’t work anymore” mean? There are two variants:

1. You opened some file *before* the nighly update or in Vim, closed NeoVim/Vim and opened again *after* the update. This is not going to work: viminfo file where marks were previously contained got replaced with a new format. Same thing will happen if you try to migrate position from NeoVim to Vim: formats are not compatible.
2. You opened some file *after* the nigtly update in NeoVim, closed NeoVim and opened file again in NeoVim, and it does not work. This is a bug.

In the second case (in the first case issue is closed) please provide `verbose set shada?` output, and contents of `~/.nvim/shada/main.shada` file (note: it is a binary file).

**Comment by nschloe** [comment]
```
:verbose set shada?<CR>
```
gives
```
  shada=!,'100,<50,s10,h
```

> You opened some file after the nigtly update in NeoVim, closed NeoVim and opened file again in NeoVim, and it does not work. This is a bug.

That's what I observe. [Here's my `~/.nvim/shada/main.shada`](http://chunk.io/f/71e88f73b61a48c3a517c207a50b7cba).

**Comment by renstrom** [comment]
I get this too, I have this in my `.vimrc`:

```vim
function! SetCursorPosition()
  if &filetype !~ 'svn\|commit\c'
    if line("'\"") > 0 && line("'\"") <= line("$") |
      execute 'normal! g`"zvzz' |
    endif
  end
endfunction
autocmd BufReadPost * call SetCursorPosition()
```

The output of `:verbose set shada?`:

    shada=!,'100,<50,s10,h
      Last set from ~/.vim/plugged/vim-sensible/plugin/sensible.vim

[~/.nvim/shada/main.shada](http://chunk.io/f/ee193783f2bf4e988d40c47e9360a7fa)

**Comment by tarruda** [comment]
Also experiencing this(have the same vimrc snippet as @nschloe). This must be related to shada reading or writing because the position is restored when closing/reopening the file without exiting nvim. Steps to reproduce:

- create a file `bug.vim` with:
```vim
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
```
- enter nvim with `./build/bin/nvim -u bug.vim`
- edit a file with something like `:e src/nvim/eval.c`
- hit ctrl+f a couple of times, remember the line below cursor
- execute `:bdelete`
- open the file again, the cursor should be on the same line as before `:bdelete`
- close nvim and reopen the file, the cursor will be at the first line.

Output of `:echo &shada`: `!,'100,<50,s10,h`

**Comment by ZyX-I** [comment]
I see the error (including strange (line=1, column=0 everywhere) data in the ShaDa file. Will fix this later, currently I only know what change this is related to.

**Comment by nschloe** [comment]
Still doesn't work for me on
```
nvim --version
NVIM 0.1.0 (compiled Nov  2 2015 08:51:59)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/build/config -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/src -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-RZMg8W/neovim-0.0.0+git201511012116+1967+14~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-12

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by tarruda** [comment]
@nschloe can you give more details(steps with `nvim -u NONE`) on how to reproduce? I had the same problem but now it is fixed for me so maybe you're experiencing another bug

**Comment by nschloe** [comment]
How to reproduce with
```
NVIM 0.0.0-alpha (compiled Oct 20 2015 14:37:42)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/build/config -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/src -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-4UZEbL/neovim-0.0.0+git201510192253+1938+14~ubuntu15.04.1/build/include
Compiled by buildd@lcy01-33

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/share/nvim"

```
1. Open a new file with `nvim -u NONE test`
2. Write a bunch of lines.
3. Place the cursor anywhere in the file.
4. Save and close, `:wq`.
5. Reopen, `nvim -u NONE test`.

Find the curser at position 0 in the file.

**Comment by mhinz** [comment]
@nschloe Wait, that can't work. With `-u NONE` no jump is ever done. You can check `:marks` and look for the `"` mark. It should be set and doing ``"` in normal mode should jump to it.

**Comment by nschloe** [comment]
@mhinz Well, the same applies for `nvim` without `-u None`.

I checked `:marks` and `"` is always set to `line 1`, `col 0`, no matter where the cursor is when leaving the file.

**Comment by ZyX-I** [comment]
@nschloe Second Neovim for which you provided `:version` is outdated.

**Comment by nschloe** [comment]
@ZyX-I Well spotted. I upgraded to
```
nvim --version
NVIM 0.1.0-dev (compiled Nov  4 2015 14:52:48)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/build/config -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/src -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-jLLHkG/neovim-0.0.0+git201511041134+1970+14~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-27

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
and still see the same thing, unfortunately.

**Comment by wladston** [comment]
I'm using @renstrom's snippet, and it's working for me.

**Comment by justinmk** [comment]
Cannot reproduce. This was fixed on master. Haven't seen a report that is using a build after 0.1.

**Comment by nschloe** [comment]
I can still reproduce this with
```
$ nvim --version
NVIM 0.1.0-dev (compiled Dec  3 2015 03:19:52)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/build/config -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/src -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-ayqRmI/neovim-0.1.0ubuntu1+git201512022103+2032+15~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-22

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by justinmk** [comment]
@nschloe What commit are you at? Where is that build coming from?

**Comment by nschloe** [comment]
This is from the nightly [PPA build](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) for Ubuntu Wily.

**Comment by justinmk** [comment]
Didn't realize that PPA was building nightly now (nice work @fwalch). In the unlikely event it only builds tagged releases, I just pushed 0.1.1 with the fix. If it's still broken for you after the next PPA update, let's reopen this.

**Comment by nschloe** [comment]
Tried it with the build from an hour ago and still see the issue. Perhaps there is something wrong in the build process of the PPA? I can reproduce this on two different machines. @fwalch, can you reproduce with the PPA builds?

**Comment by fwalch** [comment]
@justinmk PPA packages are built daily from whatever the latest commit in `master` (resp. in the Launchpad bzr mirror of `master`) is.

@nschloe Unfortunately, I can't reproduce this (with 0.1.0ubuntu1+git201512100819+2042+15~ubuntu14.04.1 [Note to self: I guess this should be updated to 0.1.1]). `:marks` shows lines other than `1` for `"`, and using the snippet of your first post in my `init.vim` jumps to the correct position.

**Comment by BohrShaw** [comment]
In my case, the mark `0` is not remembered when exiting Nvim.
(Probably should be in another issue. But this issue title is misleading.)

**Comment by nschloe** [comment]
I started up a clean vagrant box
```
vagrant init https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
```
logged in, did nothing but
 * adding the neovim unstable repo,
 * `apt update`
 * `apt install neovim`
 *  adding 
```
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
```
to `~/.vimrc`.

With this, I can reproduce the error: nvim does not jump back to where I let the cursor in a specific file.

**Comment by nschloe** [comment]
If there's anything else I can do to help debugging this, let me know.

**Comment by wsdjeg** [comment]
@nschloe I am using PPA package,but I can not reproduce it,my os is ubuntu 14.04.
gnome-terminal

**Comment by wsdjeg** [comment]
here is my https://github.com/wsdjeg/DotFiles/blob/master/vimrc#L1193-L1196
```vim
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal g`\"" |
            \ endif
```

**Comment by wsdjeg** [comment]
you should change `if line("'\"") > 1` to `if line("'\"") > 0`

**Comment by nschloe** [comment]
Thanks @wsdjeg for your input! My entire `~/.vimrc` looks like
```
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal g`\"" |
            \ endif
```
right now, but nvim – as opposed to vim – doesn't jump back to the original position when reopening a file.

**Comment by wsdjeg** [comment]
strange,what is your os,and terminal version?
and can you show me the mini vimrc?

**Comment by nschloe** [comment]
I started up a clean (vagrant) box with Ubutu 14.04 (see [the comment above](https://github.com/neovim/neovim/issues/3472#issuecomment-164312612)) and made this
```vim
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal g`\"" |
            \ endif
```
my `~/.vimrc` file (that's all of it). The terminal is bash 4.3.11(1).

**Comment by wsdjeg** [comment]
sorry,it is out of my knowledge，and it is really strange,I also using ubuntu 14.04,but I can not reproduce this issue.

**Comment by nschloe** [comment]
I've reproduced it on two other machines now, one 14.04, one 15.10. Really weird...

**Comment by justinmk** [comment]
@watiko Provided steps to reproduce here: https://github.com/neovim/neovim/issues/4360#issuecomment-189751741

**Comment by gunar** [comment]
Same here with:
```vim
autocmd BufReadPost *
      \ if line("'\"") > 0 && line ("'\"") <= line("$") |
      \   exe "normal! g'\"" |
      \ endif
```

**Comment by jdbytes** [comment]
Has anybody found a workaround?

**Comment by timofonic** [comment]
https://www.reddit.com/r/neovim/comments/3oyy7m/shada_has_landed/  

Over 11 months ago @fmoralesc said...

> [See here] (https://github.com/neovim/neovim/issues/3472). @ZyX-I ZyX-I said he was going to fix this issue.

What happened with this? Any news?

**Comment by justinmk** [comment]
There's a PR open but it fails some tests.

**Comment by nschloe** [comment]
I can still reproduce the bug with

Steps to reproduce (as above):

Start a clean box
```
vagrant init https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
vagrant up
vagrant ssh
```
In the box, do
```
sudo apt-add-repository ppa:neovim-ppa/unstable
sudo apt update
sudo apt install neovim
```
and add
```vim
if has("autocmd")
 au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
```
to `~/.vimrc`.

Open a new file, type a few lines, `:wq`, reopen. nvim jumps to the beginning of the file.

**Comment by gunar** [comment]
Suddenly works again for me :balloon: 

Config
```viml
" Remember cursor position between vim sessions
autocmd BufReadPost *
      \ if line("'\"") > 0 && line ("'\"") <= line("$") |
      \   exe "normal! g'\"" |
      \ endif
```
Nvim
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

**Comment by mhinz** [comment]
@nschloe 

You mentioned `~/.vimrc` all the time. This is a symlink to Neovim's actual vimrc at `~/.config/nvim/init.vim`, right? (Check `:scriptnames` to see which files actually get read.)

If that's not the issue, create this file:

```viml
"
" /tmp/config.vim
"

" Yes, test for > 1, not > 0. There's no use in jumping to line 1,
" if Vim would start at line 1 anyway.
autocmd BufReadPost *
      \  if line("'\"") > 1 && line("'\"") <= line("$")
      \|   exe 'normal! g`"zvzz'
      \| endif

set shada='10,n/tmp/shada
```

Then do this:

```
$ cd /tmp
$ nvim -u config.vim config.vim
6j
:wshada | rshada | marks "
```

It should print the content of a few marks whereas one line should look like this:

```
"      7    0 autocmd BufReadPost *
```

**Comment by nschloe** [comment]
> This is a symlink to Neovim's actual vimrc at ~/.config/nvim/init.vim, right?

It wasn't, and that was probably the issue all along. :/

I had been under the impression that nvim reads vim's config `~/.vimrc` as well (and I remember that it used to).

**Comment by justinmk** [comment]
With https://github.com/neovim/neovim/pull/5908 this should be fixed.

**Comment by rightaway** [comment]
What's the difference between using the 2 alternatives here? One uses backtick the other uses zvzz.

```
'normal! g`"zvzz'

"normal! g`\""
```

**Comment by rafi** [comment]
@rightaway both use <kbd>g</kbd><kbd>`</kbd><kbd>"</kbd>

`zvzz` opens folds in location and centers cursor in window
