### ISSUE TITLE
Can't rely on errno constant checks with libuv

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#3473]
I bumped into this when merging #810 with the recent ShaDa changes, the **errno** checks in shada.c/ [open_file](
https://github.com/neovim/neovim/blob/master/src/nvim/shada.c#L825) fail in windows - they are negative numbers but the error codes are different - e.g. the shada file does not exist but the ENOENT check fails, but the problem is a bit worse than that (potentially for UNIX, see at the end).

From our documentation in [os_open()](https://github.com/neovim/neovim/blob/master/src/nvim/os/fs.c#L195) (also os_mkdir and os_mkdir_recur)

> return file descriptor, or negative `errno` on failure

But here is the problem, the libuv docs [say differently](
http://docs.libuv.org/en/v1.x/errors.html)

> Implementation detail: on Unix error codes are the negated errno (or -errno), while on Windows they are defined by libuv to arbitrary negative numbers.

libuv provides its own error constants e.g. `UV_ENOENT` instead of `ENOENT`.

I ran a quick grep for os_open but it seems we don't rely on the result being errno for those functions (with the exception of shada.c). The other case is the function `stream_set_blocking()` but we never check the return value there either.

Also in libuv [code](https://github.com/libuv/libuv/blob/bf52579f92c30cb6ebb65a007b4f0dab9f135695/src/unix/fs.c#L22)

> /* Caveat emptor: this file deviates from the libuv convention of returning negated errno codes.

i.e. we can't rely on errno when using libuv abstractions.

**Comment by ZyX-I** [comment]
When searching for constants I have only found `UV__NOENT` (two underscores) `ag` now (when I perform global search, and not limit search to headers) finds a number of occurrences of `UV_ENOENT` in various files, but never in headers. I did not perform the search on built sources, so it is possible that they are simply using some generator. `UV__NOENT` was not used because it contains two underscores (which, if I understand correctly, means “libuv private”).

About “i.e. we can't rely on errno when using libuv abstractions”: in the same paragraph it says literally

> The dispatcher in uv__fs_work() takes care of getting the errno to the right place (req->result or as the return value.)

, so no need to care: there is dispatcher that cares.

```
/* Caveat emptor: this file deviates from the libuv convention of returning
 * negated errno codes. Most uv_fs_*() functions map directly to the system
 * call of the same name. For more complex wrappers, it's easier to just
 * return -1 with errno set. The dispatcher in uv__fs_work() takes care of
 * getting the errno to the right place (req->result or as the return value.)
 */
```

. Just ShaDa needs to use libuv constants.

**Comment by equalsraf** [comment]
>. Just ShaDa needs to use libuv constants.

And a quick update to the os_* docs. There might be more cases, I have not checked deeply enough.

> so no need to care: there is dispatcher that cares.

Still investigating on windows, but errno does not seem to be set properly after os_open, for example the function returns -4058 (UV_ENOENT), errno is set to 42 (EILSEQ??), not ENOENT(2)

**Comment by ZyX-I** [comment]
@equalsraf I understand it as *dispatcher* getting proper errno. *Not* the caller. If `os_open` returns `UV_ENOENT` for missing file it is OK, regardless of `errno` value. Dispatcher have taken `errno`, translated it into libuv-own value and put into `open_req.result` (AFAIR which is also the thing returned by `uv_fs_open`). Maybe 42 is some windows-specific value.

**Comment by ZyX-I** [comment]
Problem is `read`: it is not libuv `read` (for some reason in other places where I saw read it was also direct read), so I am not sure whether or not I can use EINT/EAGAIN/ENOMEM there. Same for `write`.

**Comment by justinmk** [comment]
We still need to replace read/write with libuv calls, if I remember correctly.

**Comment by equalsraf** [comment]
Closing since the PRs have been merged, we can open new ones for libuv improvements.
