### ISSUE TITLE
Inserting text with read !cat doesnt work : it doesn't work with any interactive command

### ISSUE THREAD

**Issue by netei** [neovim/neovim#3474]
Running with latest neovim (compiled from 3a970e5    3 days ago),

if I do  

```
nvim -u NONE
:read !cat
```

Cat doesn't wait for stdin to finish to get back to read, so it is not possible to easily copy text from outside of neovim. This works well from inside of normal vim.

I can't use the `+` register because I'm not allowed to have an X server running

**Comment by tarruda** [comment]
This is expected, bang commands use pipes in nvim and wont work with interactive commands properly.

Have you considered using `shift` + `insert` to paste in insert mode? Also see the [`'pastetoggle'`](https://neovim.io/doc/user/options.html#'pastetoggle') option(If your terminal supports bracketed paste, nvim will take care of this automatically)

**Comment by netei** [comment]
I created the mapping for :read !cat because using 'pastetoggle' involves pressing the paste key twice : Once before writing the text, then after ending paste mode.

What I like about my :read !cat is that I had to quit `cat` before going back to vim, so that I'm never in a mode I don't want.

**Comment by netei** [comment]
But nevermind, I will use `set pastetoggle=<F11>`

**Comment by tarruda** [comment]
If you use a terminal that sends bracketed paste sequences(xterm,urxvt...), then you don't need to use a key for pastetoggle, just a plain `shift+insert` while in `-- INSERT --` should work. For now nvim checks `\e[200~`/`\e[201~` for entering/leaving paste mode but this will be configurable in the future.
