### ISSUE TITLE
unable to set an option to have % ignore \( \{ \[ \] \} \)

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#3475]
In original vim, having 'cpoptions' not have M would cause % to skip over backslashed paren-like chars. This is no longer the case: neovim persists in not skipping backslashed parens whether or not M is in 'cpoptions'.

**Comment by ds26gte** [comment]
Looks like this bug is caused by the % as redefined by the automatically loaded plugin matchit.vim, and is not present in the pristine %.

Disabling the loading of matchit.vim (with 'let loaded_matchit = 1' in one's .nvimrc) takes care of this.

Perhaps the automatic loading of matchit.vim shouldn't be allowed.

**Comment by fmoralesc** [comment]
This should probably be fixed by modifying the matchit plugin.

**Comment by justinmk** [comment]
Only upstream change to matchit was in vim/vim@fc39ecf, not related to this issue. So this is a vim bug.

**Comment by mhinz** [comment]
We note in `:h vim-differences` that matchit gets sourced by default and it just happens to remap `%`.
