### ISSUE TITLE
Pasting into :terminal creates junk characters

### ISSUE THREAD

**Issue by rf-** [neovim/neovim#3476]
I think this is probably a known bug, but I couldn't find an issue for it. Pasting into most programs inside a `:terminal` session (pretty much every program I tried except `zsh`) also creates extra junk characters around the clipboard content:

![](https://cloud.githubusercontent.com/assets/345106/10599279/5ab572e2-76b5-11e5-8e26-6a1a28a9ef8e.png)

I imagine this is because neovim has told the terminal it understands bracketed paste mode but then passes the bracketed paste control characters directly into the vterm.

**Comment by tarruda** [comment]
> I imagine this is because neovim has told the terminal it understands bracketed paste mode but then passes the bracketed paste control characters directly into the vterm.

Yes. Latest libvterm has support for sending bracketed paste but we haven't integrated this in Neovim yet.

**Comment by ZyX-I** [comment]
@tarruda Particularly in this case this support is irrelevant. Just you need to understand bracketed paste sent by the *outer* terminal and strip paste start/end sequences, ignoring possible `<C-\>` in the middle.

If there was support then you needed to either send these sequences again when pasting *or not*, depending on the terminal *state*. Additionally send them (depending on the terminal state) when using `p`, or any other way to send charaters to terminal without using terminal mode (except for lower-level `jobsend`).

**Comment by bgourlie** [comment]
I would like to suggest this be fixed before 0.1.  As a daily user who does almost all my terminal work within nvim, this has been a huge pain point.

**Comment by alex-netquity** [comment]
Nothing of substance to contribute, but I would like to voice my desire for a fix. It's wildly annoying as is if you use the built-in terminal often.

+1

**Comment by justinmk** [comment]
Please have patience. This will not block 0.1, but we will maintain a stable branch which will get low-risk bug fixes, and this will be included and released in 0.1.x.

**Comment by alex-netquity** [comment]
Might there be a temporary workaround that would cause `<C-v>` to exit insert mode, `p`, and enter insert mode again?

**Comment by pumbor** [comment]
If you're having bracketed paste woes and are building neovim from source, you can disable bracketed paste entirely by commenting out these lines in tui.c:

    unibi_out(ui, data->unibi_ext.enable_bracketed_paste);
    unibi_out(ui, data->unibi_ext.disable_bracketed_paste);

With this I have no trouble pasting into term or regular buffers. Since bracketed paste seems to be pretty sensitive to individual setups, it would be nice to have an option to disable it entirely from within neovim for environments where it doesn't work seamlessly.

**Comment by bfredl** [comment]
`tnoremap <whatever> <c-\><c-n>"*pi` works but `whatever` cant be `shift-insert` as that is captured by the enclosing terminal, which is a bit infuriating to remember to use a different keystroke. Were already intercepting mouse events, so it shouldn't be too hard to intercept this as well, no? (I suppose one even could `tnoremap` away the byte-sequences without code change, but weird to do this due to a limitation in nvim)

**Comment by ZyX-I** [comment]
@bfredl This depends completely on terminal. Neovim is not “intercepting” any events at all, all its does is telling terminal “I can handle mouse events” and terminal then *allows* mouse events to pass through.

I.e. it is terminal that receives mouse events in *all* cases, just we used some standard escape sequences to change what terminal does with them.

**Comment by ZyX-I** [comment]
I do not know whether there is a way to tell terminal “I can handle `<S-Insert>`”.

**Comment by bfredl** [comment]
I meant the other way around: if one clicks _outside_ of the embedded terminal nvim is handling the mouse-events rather than passing them to the pty process, thats what I meant by "intercepting". By the same logic nvim should be able to handle the paste start/end sequences rather than passing them through (unless of couse the embedded process has expressed interest of these sequences).

> I do not know whether there is a way to tell terminal “I can handle <S-Insert>”.

I don't think so and IMHO thats a good thing: when various modes of middle-click pasting was broken in nvim (or any other app), one could still S-Insert.

**Comment by justinmk** [comment]
> so it shouldn't be too hard to intercept this as well, no

Shouldn't be. Just hasn't gotten done yet.

**Comment by wsdjeg** [comment]
#### with these config neovim show me some bugs
```vim
if has('vim')
    tnoremap <C-Right> <C-\><C-n><C-w><Right>
    tnoremap <C-Left>  <C-\><C-n><C-w><Left>
    tnoremap <C-Up>    <C-\><C-n><C-w><Up>
    tnoremap <C-Down>  <C-\><C-n><C-w><Down>
    tnoremap <esc>     <C-\><C-n>
endif
```
in nvim's terminal,
`<c-right> show ������` same as `<c-left>`
![2016-01-30 23 00 41](https://cloud.githubusercontent.com/assets/13142418/12696413/50bd1542-c7a5-11e5-95e1-cec203a1359b.png)
`<c-up>` show `;5A`
`<c-down>` show `;5B`

**Comment by oni-link** [comment]
Should it be `if has('nvim')` instead of `if has('vim')`?

**Comment by wsdjeg** [comment]
sorry ,it is my fault,everyting works well now.
I just feel strange,why I exec this statement in command-line ,it works well;

**Comment by jessesanford** [comment]
What is the work around for this? Is pasting into a nvim terminal possible yet via any mechanism?

**Comment by justinmk** [comment]
Workaround is to paste into a non-terminal buffer, then yank into any register, then paste that register into the terminal buffer. This could be recorded as a macro. 

But it's about time we fixed this...

**Comment by bfredl** [comment]
you can also paste into the terminal using `"*p` in normal mode in the terminal buffer.

**Comment by wleese** [comment]
Just built from master but still experience this issue. Not sure if https://github.com/neovim/neovim/pull/4412 was meant to be sufficient to fix this?

**Comment by hiberabyss** [comment]
When just open `terminal zsh`,  there is no junk character after pasting. However after execute `ssh host`, there will be junk characters `<7fff9c03>`.
> <7fff9c03>Pasting<7fff9c03>

**Comment by eblade** [comment]
Commenting out the bracketed paste lines in tui.c (as suggested by @pumbor, thanks!) work fine for me. Maybe that should be done in the master branch until the real problem has been figured out?

**Comment by bfredl** [comment]
A better quickfix, that only affects the `:terminal`, could be to add `case K_PASTE: break;` to `terminal_execute` (works for me in urxvt at least)

**Comment by bfredl** [comment]
please try latest master and see if this still is a problem.

**Comment by wleese** [comment]
Works!

**Comment by josephholsten** [comment]
woo! ship it! works-on-my-machine! lgtm! yippee!

**Comment by rf-** [comment]
Looks like it works for me too, so I guess I'll close the issue. Thanks!

**Comment by wsdjeg** [comment]
@bfredl really thanks ,it works well for me
