### ISSUE TITLE
Neovim Not Setting Its Runtime Correctly

### ISSUE THREAD

**Issue by 42f87d89** [neovim/neovim#3483]
Neovim keeps using the vim runtime, and resets every time I restart.

My .[n]vimrc does not seem to source any other files, nor does it touch the runtime itself. I have no plugins installed for either vim or neovim, as I just did a fresh Arch install.

This is what happens if I try to set $VIM or $VIMRUNTIME

    :echo $VIM
    /usr/share/vim
    :let $VIM=/usr/share/nvim
    :echo $VIM
    /usr/share/nvim
Restart nvim

    :echo $VIM
    /usr/share/vim

If I set the $VIMRUNTIME to the nvim directory, the clipboard does not work, indicating that nvim isn't looking at the $VIMRUNTIME variable after startup.
However, if I symbolically link the vim folder to the nvim folder, the clipboard does work properly in nvim, which indicates to me that nvim is infact looking at the vim directory.

**Comment by torpak** [comment]
Try 
```vim
let VIM=/usr/share/nvim
```

**Comment by fwalch** [comment]
> This is what happens if I try to set $VIM or $VIMRUNTIME

Setting `$VIMRUNTIME` from inside the editor with `:let` won't persist across restarts, that's the same behavior as in Vim.

You shouldn't need to set any of these variables at all. The default, as shown in `nvim --version`, is already the correct `/usr/share/nvim`.

I think something is setting one of these variables in your environment. You can try to run Neovim as `VIM= VIMRUNTIME= nvim -c ':h nvim'` to confirm that the correct runtime is used if these variables are not set.

**Comment by 42f87d89** [comment]
Interesting, so the $VIM and $VIMRUNTIME variables are environment variables?
I had assumed they were only valid inside of vim.

It seems like my issue was that somewhere in my rc files I had a line that exported the VIMRUNTIME as /usr/share/vim/vim74.

Now that I removed that, nvim sets those variables to the right values.
