### ISSUE TITLE
Request: patch 7.4.849

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#3492]
[Vim patch 7.4.849](http://ftp.vim.org/vim/patches/7.4/7.4.849) introduced a new insert mode command (`<C-g>U`) which basically does `:undojoin`. This enables plugins like the popular [delimitMate](/Raimondi/delimitMate), for example, to preserve your undo history while modifying the behaviour of insert mode -- very nice feature to have.

**Comment by qstrahl** [comment]
Also -- and I'm not sure how this would be best handled -- delimitMate currently checks `has('patch849')` to see if this feature is available. I'm not sure how `has` works, but ensuring that returns `1` would be helpful to plugins.

**Comment by fwalch** [comment]
See #3306.

**Comment by justinmk** [comment]
@qstrahl Could you check that https://github.com/neovim/neovim/pull/3306 works with delimitmate?

**Comment by qstrahl** [comment]
@justinmk Yup! All good. My compliments to everyone involved :D

**Comment by norcalli** [comment]
Same! I commented 4 days ago, and in 3 days it's fixed. I love this project.
