### ISSUE TITLE
Build fails on debian (libunibilium.so: No such file or directory)

### ISSUE THREAD

**Issue by gnujeremie** [neovim/neovim#3493]
I managed to build neovim some days ago, and now, i wanted to re-build it to update it, but I keep getting this error. 
All the dependencies are installed on my system, I don't know if it's a neovim problem or mine.

$ make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/neovim"
make  -C .deps
make[1]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[2]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
[ 11%] Built target unibilium
[ 23%] Built target jemalloc
[ 35%] Built target msgpack
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
[ 47%] Built target libuv
[ 58%] Built target libvterm
[ 70%] Built target luajit
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
[ 72%] Performing install step for 'libtermkey'
make[4]: Entering directory '/home/jeremie/Programmation/neovim/.deps/build/src/libtermkey'
[ 83%] Built target luarocks
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
[ 85%] Built target busted
[ 86%] Built target lua-messagepack
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Entering directory '/home/jeremie/Programmation/neovim/.deps'
ln -sf termkey_new.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_destroy.3.gz
ln -sf termkey_new.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_new_abstract.3.gz
ln -sf termkey_set_flags.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_get_flags.3.gz
ln -sf termkey_set_canonflags.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_get_canonflags.3.gz
ln -sf termkey_set_buffer_size.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_get_buffer_size.3.gz
ln -sf termkey_set_waittime.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_get_waittime.3.gz
ln -sf termkey_getkey.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_getkey_force.3.gz
ln -sf termkey_start.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_stop.3.gz
ln -sf termkey_start.3.gz /home/jeremie/Programmation/neovim/.deps/usr/share/man/man3/termkey_is_started.3.gz
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
[ 88%] Built target nvim-client
[ 89%] Built target lpeg
gcc: error: /home/jeremie/Programmation/neovim/.deps/usr/lib/libunibilium.so: No such file or directory
Makefile:71: recipe for target 'libtermkey.la' failed
make[4]: *** [libtermkey.la] Error 1
make[4]: Leaving directory '/home/jeremie/Programmation/neovim/.deps/build/src/libtermkey'
CMakeFiles/libtermkey.dir/build.make:73: recipe for target 'build/src/libtermkey-stamp/libtermkey-install' failed
make[3]: *** [build/src/libtermkey-stamp/libtermkey-install] Error 2
make[3]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
CMakeFiles/Makefile2:179: recipe for target 'CMakeFiles/libtermkey.dir/all' failed
make[2]: *** [CMakeFiles/libtermkey.dir/all] Error 2
make[2]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jeremie/Programmation/neovim/.deps'
Makefile:70: recipe for target 'deps' failed
make: *** [deps] Error 2

**Comment by fwalch** [comment]
Can you try `make distclean && make`?

**Comment by gnujeremie** [comment]
Oh God that was fast AND great. Thanks a lot, it fixed the problem.

**Comment by mallochine** [comment]
worked for me too. Honestly, there should be some sort of way to automatically detect this problem and suggest the solution. Would save a lot of time rebuilding from source
