### ISSUE TITLE
Folds with foldmethod=marker keep folding while editing

### ISSUE THREAD

**Issue by jared-skinner** [neovim/neovim#3495]
So, here's the situation:

I have my .nvimrc file (https://github.com/jared-skinner/dotfiles/blob/master/vim/nvimrc) which contains the following:

set modelines=1
............
" vim:foldmethod=marker:foldlevel=0

A snazzy trick I learned so I could organize my rc file with {{{....}}}.

Now, I have noticed in neovim that when I am modifying the contents of one of these folds, the fold will close on me occasionally.  For instance I have entered insert mode and add a single character and had the section fold.  If I keep typing the fold will unfold and my cursor will be back where it is suppose to be.  It seems that after this occurs for one set of key strokes it won't occur for the same set of key strokes (I could then exit insert mode, reenter insert mode and keep typing without issue).

Thanks for all you guys have done.  This is a fantastic project!
Jared

**Comment by justinmk** [comment]
Possibly related to https://github.com/neovim/neovim/issues/3382.

Other than that there isn't enough precise information here to reproduce (we don't have time to bisect everyone's vimrcs, we need reduced steps to reproduce the issue via `nvim -u NONE`).

**Comment by jared-skinner** [comment]
My apologies, I didn't mean to provide you with a needlessly tedious task.  I reduced my .nvimrc file down to the following 5 lines with the same results:

set modelines=1
" This is a fold {{{
	" This is the contents of the fold!
" }}}
" vim:foldmethod=marker:foldlevel=0


Folds seem to work as designed If I chang my .nvimrc file to read 

set foldmethod=marker
set foldlevel=0
" This is a fold {{{
	" This is the contents of the fold!
" }}}

**Comment by justinmk** [comment]
@jared-skinner Thanks

**Comment by jared-skinner** [comment]
I update to the 0.1 release earlier today (you guys are awesome).  I tried modifying my rc file and am no longer seeing the issue, FYI.

**Comment by cormacrelf** [comment]
Bump because this issue is still in 0.2.0.

A _slightly_ better workaround is

    autocmd BufRead *.vim,.*vimrc set foldenable foldmethod=marker foldlevel=0

**Comment by mallochine** [comment]
@cormacrelf did you typo .*vimrc to actually be *.vimrc

**Comment by wsdjeg** [comment]
@jared-skinner do you still get this issue in v0.2.0?

**Comment by cormacrelf** [comment]
@mallochine can’t remember now but I think it should cover .gvimrc too, that was the point
