### ISSUE TITLE
Writing fails with E510

### ISSUE THREAD

**Issue by yyt16384** [neovim/neovim#3496]
After pull #3470 writing sometimes fails with `E510: Can't make backup file`. Manually creating directory `$XDG_DATA_HOME/nvim/backup` works.

**Comment by justinmk** [comment]
Added to https://github.com/neovim/neovim/issues/2676

`'backup'` is not set by default, and `:help 'backup'` suggests that there is not really a reason to do so. `'writebackup'` is really all you need, combined with `'undofile'`, `'swapfile'`, and git.

**Comment by tarruda** [comment]
I have `set nobackup` and this error is still shown to me if I remove `~/.local/share/nvim/backup`

**Comment by justinmk** [comment]
I think that is because `.` was removed from backupdir` default value. @ZyX-I can you confirm

**Comment by ZyX-I** [comment]
@justinmk Indeed this is because `.` was removed. Regarding add back/autocreate: I was saying that `.` should be there since the very beginning of my PR, but this is because `backupdir` has no equivalent for `directory=…//`. Do not remember anybody explaining me why `.` should not be there. I think that more optimal would be autocreate directory, but also support `//`. Prepending `.` to the default is much easier on the other side.

**Comment by yyt16384** [comment]
I think `writebackup` uses `backupdir` too. The directory timestamp is updated when I save a file with `backup` off and `writebackup` on.

**Comment by justinmk** [comment]
Let's add `.` back to unblock 0.1 in the short term.

**Comment by Grimy** [comment]
> Just curious: why use 'backup'?

To make backups, so I can restore them if I inadvertently remove the file or something like that. `writebackup` without `backup` is only useful in case of write failures. `backup` is useful in case of human error, which happens much more often (to me at least).

Before the addition of persistent undo in Vim 7.3, it was also the best way to restore a file to a previous version.

**Comment by fmoralesc** [comment]
I think `.` should be appended, not prepended, so nvim uses the XDG default if possible and the current dir if that doesn't exist. Otherwise, it will never use the XDG value.

**Comment by ZyX-I** [comment]
@fmoralesc I used prepending to avoid backup file name conflicts. Second value is there just for the same reason there are directories after dot in original `&backupdir`.

**Comment by ZyX-I** [comment]
@fmoralesc Also when `&backupdir` is used for `&writebackup` there is another reason for having `.` there: `mv ./a ./b` is usually as simple as removing `a` directory entry and making `b` point to another inode. `mv ~/.local/share/undo/a ./b` may copy `a` file contents in case `.` and `~/.local/share/undo` are on different file systems.
