### ISSUE TITLE
E510: Can't make backup file after neovim update

### ISSUE THREAD

**Issue by Moeryn** [neovim/neovim#3498]
I got the following error after simply update neovim to change 0f9dea2

    E510: Can't make backup file

My backupdir is:

    ~/.local/share/nvim/backup

The directory was not created.
Once created manually the error was removed.

**Comment by terlar** [comment]
I also experienced this issue and I don't even have `backup` enabled. Same solution applied.

**Comment by terlar** [comment]
For me this was due to my config not being loaded, see: https://github.com/neovim/neovim/issues/3499

Might be different in your case since you might be using `backup` anways.

**Comment by justinmk** [comment]
`backupdir` is never auto created unless your vimrc or plugin does so. Though we may add this feature. 

See https://github.com/neovim/neovim/issues/3496#issuecomment-151024493

**Comment by rcdosado** [comment]
i solve this by putting this by creting backup folder in my neovim config dir and definiting this in my init.vim
`set backupdir=~/.config/nvim/tmp/backup`
