### ISSUE TITLE
neovim no longer opens my nvimrc file

### ISSUE THREAD

**Issue by Moeryn** [neovim/neovim#3499]
After an update to 0f9dea2 neovim no longer open my .nvimrc

My .nvimrc is located at:

    /home/user/.nvimrc

    echo $HOME   => /home/user
    echo $VIMRUNTIME => /usr/local/share/nvim/runtime

    set rtp?
     runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after

I manage to open it whith

    nvim -u .nvimrc

**Comment by trimailov** [comment]
+1

I am on OS X 10.11.1

**Comment by casimir** [comment]
There was a breaking change when merging XDG patch https://github.com/neovim/neovim/pull/3470#issuecomment-151018973

**Comment by trimailov** [comment]
Looks like backwards incompatible change.

[How to fix](https://github.com/ZyX-I/neovim/blob/42047acb4f07c689936b051864c6b4448b1b6aa1/runtime/doc/nvim_from_vim.txt#L12-L18)

**Comment by ahmedelgabri** [comment]
Thanks @casimir & @trimailov

**Comment by Moeryn** [comment]
Thx for your fast replies.

It now works.

Is there a way to be updated on these breaking change?
I am following the mailing lists already, but is there an other way?

**Comment by casimir** [comment]
I'd say you need information updates as fast as the software updates. I personally follow the [github issues](https://github.com/neovim/neovim/issues) and update when there is an interesting change. Github remember what you've read so you can use it like a an RSS feed (in some sort).

**Comment by trimailov** [comment]
@Moeryn +1

It would've been nice to have a disclaimer somewhere about such breaking change. 

Though I do not know what will be the greatest solution to this. Personally, after updating `neovim`, I always run `nvim --version` to check latest commit and date, so I could've caught it there.

Even though `nvim` is not `v1.0` it would be great to somehow know breaking changes before they happen.

**Comment by ajpaulson** [comment]
So currently there isn't a per-user config? only a system one? (going by the link @trimailov posted)

Also `$XDG_CONFIG_HOME` is an empty variable on some distros - (on this Ubuntu 15.04 install `$XDG_CONFIG_DIRS` seems to be the equivalent.

Have I missed something about having a local config? should it be under `~/.config/nvim` ?

**Comment by trimailov** [comment]
@ajpaulson: I linked my `.nvimrc` to `~/.config/nvim/init.vim` and it works.

**Comment by ajpaulson** [comment]
yeah - I moved my `~/.nvim` folder to `~/.config/nvim` and renamed my `nvimrc` within it to `init.vim` and it worked (I just need to find a better way of referencing it in case it gets changed again - in my nvimrc I had lines like `call plug#begin('~/.config/nvim/plugged')` )

**Comment by trimailov** [comment]
@ajpaulson: I have my various config files in `~/dotfiles` (e.g. `~/dotifles/nvim/nvimrc`) and link from there, to whatever they should be (e.g. `ln -s ~/dotfiles/nvim/nvimrc ~/.config/nvim/init.vim`). This way all my configs are in the same place and do not need to move anything around.

**Comment by ajpaulson** [comment]
I am symlinking, but my vim/nvim config is separate from the rest of my dotfiles for various reasons.

That aside - I still feel that the documentation accompanying this change isn't quite clear enough that `~/.config/nvim` will be sourced as a local nvim config dir - as the variable mentioned isn't populated on all distros and doesn't appear to be needed.

**Comment by ajpaulson** [comment]
ok - I just re-read the documentation - it's creating that variable whilst creating the directory.

This isn't as clear as it could be for anyone that isn't intimately familiar with brace expansion and such.

I may open a new issue about that

**Comment by ZyX-I** [comment]
@ajpaulson This variable is not created. It just knows the default value and falls back to it.

**Comment by ajpaulson** [comment]
@ZyX-I the first line in the `nvim-from-vim` doc section on config dirs creates and fills the variable

```
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
```

creates `$XDG_CONFIG_HOME` for that shell session and sets it to the expansion of `$HOME/.config`

Though a lot of people who are using nvim may understand about variables yet not realise exactly what this is doing.

The documentation does not mention that it will fallback to `~/.config/nvim/init.vim` and the output of `:version` doesn't even mention this location in any form

**Comment by dbldots** [comment]
i moved my `.nvimrc` to `.config/nvim/init.vim` - which works fine.
however i am using neobundle and therefore tried to move the `neobundle.vim` folder to `.config/nvim/bundle/neobundle.vim` - this does not work.

is anyone else having issues with neobundle/pathogen?

**Comment by tarruda** [comment]
> is anyone else having issues with neobundle/pathogen?

Some plugins could create references to the directory they are installed, so it is safer to reinstall them.

**Comment by Shougo** [comment]
@dbldots You must change neobundle base directory in your nvimrc.

**Comment by dbldots** [comment]
@Shougo aaarrgh. dumb. thanks!

**Comment by ahmedelgabri** [comment]
So will this mean that having the same file as `vimrc` and `nvimrc` won't be a good idea anymore?

**Comment by justinmk** [comment]
@ahmedelgabri It's still completely fine to symlink `~/.config/nvim/init.vim` to your `vimrc`. See See [`:help nvim-from-vim`](https://github.com/ZyX-I/neovim/blob/42047acb4f07c689936b051864c6b4448b1b6aa1/runtime/doc/nvim_from_vim.txt#L12-L18) for quick migration steps.

**Comment by ahmedelgabri** [comment]
@justinmk I'm already doing this. My comment _maybe was not clear_ was about plugins, and I think I misunderstood @tarruda comment.

> Some plugins could create references to the directory they are installed, so it is safer to reinstall them.

I thought plugins keeps references to the directory of the vim for example `~/.vim/` and `~/.config/nvim`. apologies.

**Comment by justinmk** [comment]
> I thought plugins keeps references to the directory of the vim for example ~/.vim/

I haven't seen that, and any plugin that does so is poorly written. At any rate, symlinking `~/.vim/` to `~/.config/nvim` would work around that problem as well.

**Comment by pdf** [comment]
Another side-effect of this change appears to be that the system-wide config is not read if a user config exists, where previous behaviour was to evaluate both, ie - if I symlink `/etc/vim/vimrc` to `/etc/xdg/nvim/init.vim`, users without `~/.config/nvim/init.vim` get the settings from `/etc/xdg/nvim/init.vim` evaluated, but users with `~/.config/nvim/init.vim` do not.

**Comment by ZyX-I** [comment]
@pdf It was chosen not to do this. System-wide config that is always read is `$VIM/sysinit.vim` (controlled by defines), and it is suggested that distribution maintainers do not mess with it. Otherwise you may use `source` in your own `init.vim` if you choose to use distribution configuration file and do not do this if you do not need it.

AFAIR the main concern was that distribution maintainers love to put there different crap. It may be good as the default, but better to rely on user adding everything what is needed to his own `init.vim` file.

**Comment by pdf** [comment]
@ZyX-I we've used the standard behaviour to deploy our own defaults, allowing users to override them if they see fit.  Where is the documentation for this additional breaking change for those that rely on this behaviour?

The justification for this seems pretty weak IMO.  And while users can return to previous behaviour by explicitly sourcing the system configs, they also need to guard this with `has('nvim')` if the configs are shared between vim and nvim.

**Comment by ZyX-I** [comment]
@pdf I checked and do *not* see the “previous behaviour was to evaluate both”. File pointed by `SYS_VIMRC_FILE` define is still sourced, except that I renamed the default. There is *no* other special vimrc files which are additionally sourced. Gentoo Vim ebuild uses exactly this define to source `/etc/vim/vimrc`.

So it is not that I changed behaviour from “source multiple configuration files” to “source only one”. Just I did *not* add sourcing of multiple configuration files.

**Comment by pdf** [comment]
@ZyX-I so, the previous explanation was incorrect?  It looks like anyone who uses a build that hasn't had `SYS_VIMRC_FILE` defined to match standard vim (every package other than Gentoo AFAICT) must symlink `/usr/share/nvim/sysinit.vim` to `/etc/vim/vimrc` to restore previous behaviour.  In that case, this should also be documented.

And it seems odd to claim that this was to avoid the use-case of distros shipping default configurations then claim it's not a problem anyway because packagers can just go ahead and -Define their way around it to restore the old behaviour... :confused:

**Comment by ZyX-I** [comment]
@pdf The problem with multiple vimrc files was discussed and variant “go over `$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS` and collect *all* `init.vim` files” was rejected for the reasons explained. Just when writing my PR I failed to connect Gentoo `/etc/vim/vimrc` with `SYS_VIMRC_FILE` define as it is set to `$VIM/vimrc` by default and such define (specifically `$VIM` in it) associates for me with Vim developers wanting to provide some vimrc.

This confusion is now solved, but it resulted in two my messages contradicting with each other.

**Comment by ajvb** [comment]
How was this not announced or included into the release in a way all users would see this?

Serious bummer that I had to waste an hour trying to figure out what the hell was happening.

**Comment by kosz** [comment]
so much threshold for upgrading. 

i guess if you make it too user friendly, and too easy to setup, many traditional vim users won't be interested ?

**Comment by fwalch** [comment]
@kosz Suggestions on how to make things easier are always welcome! Personally, I don't think having to create two symlinks to use your existing Vim config is too much to ask. Or are you referring to something else?

FWIW, as I think it hasn't been mentioned so far in this thread: breaking changes that affect existing Nvim users are documented at https://github.com/neovim/neovim/wiki/Following-HEAD.

**Comment by daveyarwood** [comment]
I just created a `~/.config/nvim/init.vim` consisting of this:

```
" I don't like this new convention, just source my existing .nvimrc plz
source ~/.nvimrc
```

Boom, problem solved.

**Comment by trimailov** [comment]
ha ha. :+1: :)

**Comment by adelarsq** [comment]
How to make this work on MS Windows?

**Comment by mhinz** [comment]
@adelarsq https://github.com/neovim/neovim/wiki/Installing-Neovim#vimrc-file-in-windows

**Comment by adelarsq** [comment]
@mhinz Didn't work. Maybe something with [NyaoVim](https://github.com/rhysd/NyaoVim)  :confused:

**Comment by will** [comment]
I used @daveyarwood's solution. Thanks!

**Comment by kilbith** [comment]
I blame the developers for breaking the backward compat' and not informing the users about that. Had to investigate a good hour to fix that...

**Comment by fwalch** [comment]
@kilbith We did document it: https://github.com/neovim/neovim/wiki/Following-HEAD#20151026, and it is also explicitly mentioned on https://github.com/neovim/neovim/wiki/Installing-Neovim. Sorry, but I don't see what more we can do. Also, that change was 11 months ago.

**Comment by tweekmonster** [comment]
I want to just comment that I like that Neovim is following the XDG spec and the moment of confusion I had when my configs didn't load hasn't changed my opinion of Neovim.  It actually changed my opinion of where all programs should store configs and temporary files: in standardized user-controlled directories.

**Comment by Pepczenko** [comment]
> Looks like backwards incompatible change.
> 
> [How to fix](https://github.com/ZyX-I/neovim/blob/42047acb4f07c689936b051864c6b4448b1b6aa1/runtime/doc/nvim_from_vim.txt#L12-L18)

Thanks Great reply
