### ISSUE TITLE
Documentation unclear on current location of user's local config

### ISSUE THREAD

**Issue by ajpaulson** [neovim/neovim#3503]
Currently users can have a local config under `~/.config/nvim` with the config file being `~/.config/nvim/init.vim`

Currently `:h nvim-from-vim` isn't fully clear about this and could (and has) cause confusion.

the output of `:version` doesn't even mention any hint of this location.

**Comment by ZyX-I** [comment]
Output of `:version` mentions only compile-time options. Vimrc file location is *no longer* controlled by a compile-time options, so there is no need to put it there.

**Comment by ajpaulson** [comment]
`:version` gives this;

```
   system vimrc file: "$VIM/sysinit.vim"                                                                                                                                                                                                      
  fall-back for $VIM: "/usr/local/share/nvim"
```
these are _not_ compile time options.

Compare to the output of `:version` on vim (and on older versions of nvim)

```
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
```

Listing possible locations for local config files as well as system config files.

**Comment by ZyX-I** [comment]
@ajpaulson They *are*:

1. It is expected that maintainers of the packages use `-DSYS_VIMRC_FILE=needed-location` in `CFLAGS`.
2. On my system the second thing is set to `/home/zyx/a.a/Proj/c/neovim/build/root/share/nvim`: it is the derivative of `CMAKE_INSTALL_PREFIX`.

All other file locations also *are* controlled by defines, with some defaults though.

**Comment by ajpaulson** [comment]
And so - how should a new user (either migrating from Vim or some other editor) find out where to place their local config file?

The documentation really isn't clear on that.
Their is nothing that says `~/.config/nvim/init.vim will be read as your local configuration file if it exists`

**Comment by ajpaulson** [comment]
Grepping through the docs I see that it actually *is* mentioned in `:h starting.txt'

But imagine a new user loading up nvim - they are told to type `:h nvim-intro` for nvim help

This brings up a help doc that does not mention `starting.txt` nor mention where your config should go.

It mentions once that you might try `help.txt` which has `starting.txt` listed after many other help files.

I know that when I first started with Vim I checked `:version` to find out where my config should go, and have seen many other people do the same - If the default start page doesn't mention it, and the first help file you are sent to (`nvim-intro`) doesn't mention it, you could be forgiven for being confused about where it should be located.

**Comment by ZyX-I** [comment]
@ajpaulson It is also mentioned in `:h vim-to-nvim` (needs some basic knowledge of shell) and `vim-differences` (but `$XDG_CONFIG_HOME` is not expanded there). And `:h vimrc` has not gone anywhere. Though documentation clearly needs `:h $XDG_*` for each XDG variable.

**Comment by ajpaulson** [comment]
Yeah - I think that would solve it.

I'm assuming the current tutorial leads to a creation of init.vim in the correct location.
Maybe `starting.txt` should be mentioned in `nvim-intro`

**Comment by fmoralesc** [comment]
The current tutorial still uses the wrong paths, I'll fix it asap.

**Comment by ajpaulson** [comment]
I'm closing this as the most recent commits have made the documentation more clear on this subject
