### ISSUE TITLE
Source compile $HOME

### ISSUE THREAD

**Issue by gambledor** [neovim/neovim#3504]
Compiling from source does not take environment variable $HOME

```
:version
NVIM 0.0.0-alpha+201510260223 (compiled Oct 26 2015 12:15:46)
Commit: 0f9dea2a0e344ded3bd4f8664acfed4fd3381c8e
Build type: Release
Compilation: ....

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by ZyX-I** [comment]
What exactly do you mean by “does not take environment variable $HOME”?

**Comment by gambledor** [comment]
it does not take my $HOME env variable. It does not recognize my $HOME/.nvimrc

**Comment by ZyX-I** [comment]
@gambledor It does not need to take $HOME *at compile time*. `$HOME/.nvimrc` is *no longer* used, use `~/.config/nvim/init.vim`.

**Comment by ZyX-I** [comment]
Also “Neovim not reading `~/.nvimrc`” and “Neovim not using $HOME environment variable” are completely different errors.

**Comment by gambledor** [comment]
It's 'cause in vim we have
  user vimrc file: "$HOME/.vimrc"

**Comment by gambledor** [comment]
Anyway 
***~/.config/nvim/init.vim.***
worked

**Comment by ZyX-I** [comment]
@gambledor In Vim “user vimrc file: "$HOME/.vimrc"” is *only* printing the value of one `#define`. This define is `$HOME/.vimrc` *literally*, what Vim prints will not change if during compilation `$HOME` was unset or set to another value, or even if `$HOME` was unset or set to another value *during runtime*, so this message says nothing about Vim (not) “taking” environment variable `$HOME`, only what it actually tries to source does.
