### ISSUE TITLE
nvim: error while loading shared libraries: libiconv.so.2

### ISSUE THREAD

**Issue by gregf** [neovim/neovim#3506]
Since updating neovim I can no longer open it. It gives me the error.

```
nvim: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```

I'm running debian testing. I don't see a libiconv package to install.

**Comment by justinmk** [comment]
How did you install Neovim?

**Comment by gregf** [comment]
I no longer have this issue. Going to close it.

**Comment by habert-kungu** [comment]
had the same issue installed treesitter
