### ISSUE TITLE
i have add the this into my vimrc why alse show me the error

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3510]
![2015-10-27 00-49-24](https://cloud.githubusercontent.com/assets/13142418/10735787/ae2efa30-7c44-11e5-80de-a97095742332.png)
![2015-10-27 00-49-28](https://cloud.githubusercontent.com/assets/13142418/10735791/ae58330a-7c44-11e5-925d-8db56a01c144.png)

**Comment by wsdjeg** [comment]
![2015-10-27 01-39-08](https://cloud.githubusercontent.com/assets/13142418/10737133/8bff9120-7c4b-11e5-89f3-2ae733c7f3a1.png)

**Comment by tdjordan** [comment]
Try:

> sudo apt-get install python3.5-dev
> sudo pip3 install neovim

**Comment by wsdjeg** [comment]
fixed by sudo apt-get install python3.5-dev

can you tell me where does the python-client has been installed when i use the command behind?

pip3 install --user neovim
or
sudo pip3 install --user neovim
