### ISSUE TITLE
E510: Can't make backup file

### ISSUE THREAD

**Issue by Eriner** [neovim/neovim#3511]
Neovim does not automatically create the needed directory, resulting in a save error due to a non-existant `backup` directory. This was located at `~/.local/share/nvim/backup` for me.

Creating this directory fixed my problem. Neovim should create this directory without manual user intervention. 

For others with this problem, the missing directory can be found by running `:verbose set backupdir`

**Comment by wlhlm** [comment]
#3498

**Comment by Eriner** [comment]
Thanks, didn't see that. Will close this is at is a dupe.
