### ISSUE TITLE
510: Can't make backup file (add ! to override)

### ISSUE THREAD

**Issue by kyren** [neovim/neovim#3512]
Since updating today (77e93a6), I seem to be getting persistent errors with :w

"source/game/scripting/StarLuaAnimationComponent.hpp" E510: Can't make backup file (add ! to override)

didn't happen before updating, the version I was using was some time right after the initial ShaDa merge IIRC.

**Comment by wlhlm** [comment]
#3498

**Comment by kyren** [comment]
Oh, sorry, I should have searched closed issues as well, thank you!
