### ISSUE TITLE
Put socket into $XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#3517]
Happened to forget this during #3470, even though now there is a single entry point.

There are some unaswered questions regarding the matter:
1. Where `$XDG_RUNTIME_DIR` default should be? [Last my suggestion] was
   
   > Now I think most logical is to write a function which will be the expansion of `${TMPDIR:-/tmp}/run-$USER[.$I]` written in C, where `$USER` is obtained using `os_get_user_name`. `.$I` suffix is appended in case `${TMPDIR:-/tmp}/run-$USER` exists, but does not satisfy security restrictions. It would also be logical to check all `${TMPDIR:-/tmp}/run-$USER{,.[1-9][0-9]#}` and get one with greatest `$I` (without suffix it is considered to be I=0) which matches security restrictions, but since we need XDG_RUNTIME_DIR only for creating sockets inside, and do not really care about all Neovim instances writing to the same directory it is not needed I think.
   
   Some alternatives:
   1. Do not make a socket without `$XDG_RUNTIME_DIR` set at all, fail with error message in case this is the only variant of the communication.
   2. `~/.run`, created with necessary permissions if needed.
   3. `/tmp`, socket always lives inside a directory with correct permissions (basically like now, but this will add another subdirectory even if `$XDG_RUNTIME_DIR` is defined). Note that it makes it needed to explain to script authors that `stdpath('XDG_RUNTIME_DIR')` (suggestion from https://github.com/neovim/neovim/pull/3470#issuecomment-150731613) needs to be used in the same fashion.
2. Should `$XDG_RUNTIME_DIR` default to `\\.\pipe` on Windows? This will leave `server_address_new` without a define inside, but it is not a location where you can put anything like you can do with `/run`. This really only matters in case `stdpath()` is implemented.

**Comment by dumblob** [comment]
I vote for `[Last my suggestion]` as it retains safe out-of-box usage of neovim in any random environment.

**Comment by jrobeson** [comment]
I'm confused as to what you mean by the first option.  If XDG_RUNTIME_DIR is set, then I would expect the socket to go in `$XDG_RUNTIME_DIR/nvim.sock` or `$XDG_RUNTIME_DIR/nvim/sock`

**Comment by ZyX-I** [comment]
@jrobeson Note the target of the suggestion: “*XDG_RUNTIME_DIR default*”. What to do with this default is pretty obvious (basically do the same thing as `mktemp`, but with $TMPDIR derived from $XDG_RUNTIME_DIR), what is *not* obvious is what should XDG_RUNTIME_DIR default be or how its absense should be handled.

**Comment by jrobeson** [comment]
you mean default IF absent, because what is there to do otherwise (except using mktemp)?

**Comment by ZyX-I** [comment]
@jrobeson How can you have useful default *if* XDG_RUNTIME_DIR is *not* absent? After there is an agreement on the default for XDG_RUNTIME_DIR socket will in any case be something like `$XDG_RUNTIME_DIR/nvim/socket.z8xP3ZDRKM`. Note: you *can’t* use `$XDG_RUNTIME_DIR/nvim/sock` or any other thing without some unique substring (usually suffix) (not necessary random though, what will exactly be used depends on what will be easier to implement).

**Comment by jrobeson** [comment]
I just had trouble parsing your meaning, but that all sounds fine to me.
