### ISSUE TITLE
Last character of 'directory' is dropped

### ISSUE THREAD

**Issue by yyt16384** [neovim/neovim#3519]
Running `nvim -u NONE --cmd 'set directory=/tmp/foo' abc` does not create swap files in `/tmp/foo`. Instead, it creates `/tmp/fo` and write swap files there.

With `directory` set to `/tmp/foo/a` swap files are written in `/tmp/foo`, and with `directory` set to `/tmp/foo,/tmp/bar` swap files are written in `/tmp/foo` correctly.

It seems that the last character in `directory` get dropped for some reason.

**Comment by Grimy** [comment]
This is caused by a82a059, which added logic to replace the last character of &directory with "//".

**Comment by ZyX-I** [comment]
@Grimy This can’t be caused by a82a059 because it only touches defaults.

**Comment by Grimy** [comment]
My bad, I messed up bisecting. It looks like this is actually caused by a8e18d9.

**Comment by Grimy** [comment]
This is indeed an off-by-one error in a8e18d9. I will submit a PR soon.
