### ISSUE TITLE
Windows: Neovim opens new files as read-only

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#3526]
Similar to #3473 - in [readfile](https://github.com/neovim/neovim/blob/master/src/nvim/fileio.c#L539) we rely on errno being ENOENT after a call to `os_getperm()` and in Windows it isn't.

Also the comment in `os_getperm()` doesn't sound right either, it says

    /// @return `-1` when `name` doesn't exist.

But `os_getperm()` is just a call to `os_stat()` so its possible it fails even when the file exists, returning the actual libuv error code would be best - this works in UNIX right now because errno is used instead.

**Comment by justinmk** [comment]
This was fixed by https://github.com/neovim/neovim/pull/3531, right?
