### ISSUE TITLE
Latest neovim not using .nvimrc

### ISSUE THREAD

**Issue by mttbrstn** [neovim/neovim#3530]
I have just installed the latest commit of neovim (see below for the gory details from `:version`), and when I start it with my usual invocation of `nvim`, it starts as if there is no .nvimrc. Starting it with `nvim -u .nvimrc` gives a lot of errors (mostly related to not loading vim-plug), but sourcing the .nvimrc file once or twice more eventually gets everything working. Prior to this, everything worked just fine.

I'm happy to investigate further, and it may well be that I've missed something. At the moment, I'm not sure quite what to look into. I have tried recreating the .nvim directory as well as reinstalling vim-plug, but that made no difference.

Thanks for whatever help anyone might have.

    NVIM 0.0.0-alpha+201510270107 (compiled Oct 27 2015 09:47:49) 
    Commit: 68e596856828e61a5fed5a515647509b0cd77100
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/hahiss/software/neovim/build/config -I/home/hahiss/software/neovim/src -I/home/hahiss/software/neovim/.deps/usr/include -I/home/hahiss/software/neovim/.deps/usr/include -I/home/hahiss/software/neovim/.deps/usr/include/luajit-2.0 -I/home/hahiss/software/neovim/.deps/usr/include -I/home/hahiss/software/neovim/.deps/usr/include -I/home/hahiss/software/neovim/.deps/usr/include -I/usr/include -I/home/hahiss/software/neovim/build/src/nvim/auto -I/home/hahiss/software/neovim/build/include

    Optional features included (+) or not (-): +acl   +iconv    -jemalloc
    For differences from Vim, see :help vim-differences

    system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/usr/local/share/nvim"

**Comment by ZyX-I** [comment]
.nvimrc location has moved, check `:h vimrc`.

And **do search issues before posting them**.

**Comment by bgourlie** [comment]
I'm sure there were good reasons for making this change, but c'mon, you have ways to inform people of such obvious breaking changes (twitter comes to mind), so they know not to update if they have actual work to do.

**Comment by Tranquility** [comment]
@bgourlie  https://twitter.com/Neovim/status/658635355357319168

**Comment by bgourlie** [comment]
Yes, well, ideally *before* it's too late.

**Comment by adelarsq** [comment]
Don't work on MS Windows.

**Comment by z** [comment]
After sifting through the riddles, I found the simple answer in another issue.

New location is `~/.config/nvim/init.vim`

To keep `~/.nvimrc` you can source it from the new location:

```
mkdir -p ~/.config/nvim
echo 'source ~/.nvimrc' > ~/.config/nvim/init.vim
```
> https://github.com/neovim/neovim/issues/3499#issuecomment-169085397

**Comment by wsdjeg** [comment]
> .nvimrc location has moved, check :h vimrc.
> 
> And do search issues before posting them.

people whe use thumbs down emoji should search more about how to use a project on high develop level. the dev speed of neovim is more high than vim, and you should follow HEAD of the repo, at least follow HEAD of the wiki.and zyx-i is just tall you a better way to find answer.duplicate issue make people who watch this repo annoying.

**Comment by justinmk** [comment]
For breaking changes we are more proactive about notifying people ahead of time. 

This particular change was 9 months ago, though.

**Comment by crazyBaboon** [comment]
> New location is ~/.config/nvim/init.vim

Cool - One less file polluting my home folder!
