### ISSUE TITLE
netrw: hang after pressing 'i' several times

### ISSUE THREAD

**Issue by blai** [neovim/neovim#3534]
Steps to reproduce:

1. navigate to a file
2. (not sure if related, I used [tpope/vim/vinegar](https://github.com/tpope/vim-vinegar) here), type `-` to navigate to `netrw` view
3. hit `i` to change listing styles, first time is fine, but hitting `i` more than once crashes neovim

**Comment by equalsraf** [comment]
@bial can't replicate here (even with vinegar), can you help narrow it down further?

- a gdb trace or a crashdump would be perfect
- what system are you running on (Mac, Linux)?
- I assume you are running the latest version from master

**Comment by blai** [comment]
It seems it is not crashing, but instead taking like forever (1+ minute) whenever I change the listing styles to a tree view. I am on a Mac and updated neovim to latest, but the same problem seems to happen on an older build of neovim as well.

**Comment by blai** [comment]
Hum. I might know why it is slow, my terminal's title was flashing between Python/pbpaste, which I recall that (pbpaste) is know to cause performance issue with `CMAKE_BUILD_TYPE=RelWithDebInfo` (which is the default installation done with homebrew, I will continue digging.

**Comment by justinmk** [comment]
This should have been fixed long ago, see https://github.com/neovim/neovim/issues/1882#issuecomment-71322612

@blai please report `:version`

**Comment by blai** [comment]
```
:version
NVIM 0.0.0-alpha+201510271420 (compiled Oct 27 2015 13:04:18)
Commit: e6525f3ceb861f9c5f7e433a5073f16e8d5babc7
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -st
d=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151027-
57071-iump0u/build/config -I/tmp/neovim20151027-57071-iump0u/src -I/tmp/neovim20151027-57071-iump0u/deps-build/usr/include -I/tmp/neovi
m20151027-57071-iump0u/deps-build/usr/include -I/tmp/neovim20151027-57071-iump0u/deps-build/usr/include/luajit-2.0 -I/tmp/neovim2015102
7-57071-iump0u/deps-build/usr/include -I/tmp/neovim20151027-57071-iump0u/deps-build/usr/include -I/tmp/neovim20151027-57071-iump0u/deps
-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SD
Ks/MacOSX10.11.sdk/usr/include -I/tmp/neovim20151027-57071-iump0u/build/src/nvim/auto -I/tmp/neovim20151027-57071-iump0u/build/include
Compiled by brianlai@ML-BLAI-OSX-SF.local

Optional features included (+) or not (-): +acl   +iconv    -jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by critiqjo** [comment]
Why not replace netrw with dirvish?

**Comment by alistaircolling** [comment]
Hi, I'm getting the same problem.

Steps to reproduce:
1. Open Neovim in a directory or navigate to directory so netrw opens
2. Hit 'i'
3. Neovim freezes and the title of iterm changes to: nvim pbcopy nvim pbpaste pbcopy pbpaste

`$ nvim -v   
NVIM v0.1.6-4-g2f2e729
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160822-70213-ooiatz/build/config -I/tmp/neovim-20160822-70213-ooiatz/src -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/tmp/neovim-20160822-70213-ooiatz/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160822-70213-ooiatz/build/src/nvim/auto -I/tmp/neovim-20160822-70213-ooiatz/build/include
Compiled by alistair@Alistairs-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-2f2e729/share/nvim"
`

**Comment by justinmk** [comment]
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    6  52.341909   0.003000  <SNR>77_NetrwListStyle()
    6  52.051861   0.000520  <SNR>77_NetrwRefresh()
    6  52.051341   0.000393  netrw#LocalBrowseCheck()
    6  52.050616   0.003557  <SNR>77_NetrwBrowse()
    6  51.834015   0.005541  <SNR>77_PerformListing()
    6  51.608953             <SNR>77_NetrwWideListing()
 2668  51.448866   0.072522  provider#clipboard#Call()
 2668  51.282211             <SNR>78_try_cmd()
 2649  51.031181   0.093367  14()
   19   0.345163   0.000767  15()
    6   0.282647   0.003677  <SNR>77_NetrwBrowseChgDir()
   13   0.259907             <SNR>77_NetrwOptionSave()
   19   0.243738   0.241037  <SNR>77_NetrwOptionRestore()
    6   0.089809   0.003466  <SNR>77_NetrwGetBuffer()
   12   0.070944   0.003685  <SNR>77_NetrwSafeOptions()
    9   0.045086   0.009544  ProjectionistDetect()
    1   0.044049   0.000897  <SNR>77_NetrwEnew()
   18   0.038217             <SNR>11_LoadFTPlugin()
    6   0.032095   0.001992  <SNR>77_NetrwListSettings()
   18   0.031022   0.021656  <SNR>14_SynSet()
```

In `NetrwWideListing()`:

```vim
   if has("clipboard")
    sil! let keepregstar = @*
    sil! let keepregplus = @+
   endif
   " ...
   exe "sil! NetrwKeepj norm! 0\<c-v>$hx".w:netrw_bannercnt."G$p"
   " ...
   if has("clipboard")
    sil! let @*= keepregstar
    sil! let @+= keepregplus
   endif
```

This will be slow on Vim, too--that's why Vim added `start_global_changes()` to avoid slowness with `:global`--though not as slow as Nvim.

We should be able to avoid the problem by leveraging `start_global_changes()` in `call_user_func()`.

**Comment by justinmk** [comment]
@alistaircolling would you be able try #5253? (And also check that clipboard feature works)

**Comment by alistaircolling** [comment]
Hiya, v happy to try. I can't seem to checkout the last commit for the [#5232 pull request](https://github.com/neovim/neovim/pull/5253/commits/c79bf4ec99951e42736522bd9362dfe347522c8e). I assume that's what I'd need to do, then rebuild neovim locally. Is there another way I should access the fix? Thanks

**Comment by justinmk** [comment]
@alistaircolling One way is to checkout branch `start_batch_changes` from my fork: https://github.com/justinmk/neovim

**Comment by alistaircolling** [comment]
Yep, works great @justinmk No hanging when pressing 'i' and I've put `clipboard=unnamed` back in my vimrc and I can paste from my system clipboard. It does seem to have a really slight lag when I press 'i' but this is hardly discernible .

Thanks for sorting 👍

**Comment by chrisbra** [comment]
Hi Justin!

On Do, 25 Aug 2016, Justin M. Keyes wrote:

> @chrisbra Was there a technical reason why start_global_changes() does
> not wrap do_cmdline() ?

No, I think the problem was most apparent on Windows doing something 
like :g/^/y on a multi-thousand line buffer. So we only wanted to 
restrict access to the clipboard in that case.

Best,
Christian
-- 
Unbedingter Gehorsam setzt Unwissenheit bei den Gehorchenden voraus.
		-- Charles-Louis de Montesquieu
