### ISSUE TITLE
`.nvimrc` doesn't seem to be loaded up or working and it cannot create backups on editing existing files

### ISSUE THREAD

**Issue by define-private-public** [neovim/neovim#3536]
This was working for me until I installed the latest nightly build:
```
NVIM 0.0.0-alpha (compiled Oct 27 2015 08:52:24)
Commit: ?
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/build/config -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/src -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/.deps/usr/include -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-V7B67w/neovim-0.0.0+git201510270507+1948+14~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-20

Optional features included (+) or not (-): +acl   +iconv    -jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

When I try to open up a new neovim instance, it won't load my `.nvimrc` file, ~~and all of the files that I open are being opened as readonly (e.g. as if I was opening them with `view` instead)~~.

EDIT: I cannot seem to write out existing files unless I `:w!` because it says that It cannot create a backup file.

**Comment by define-private-public** [comment]
Correction:
When I try to `:w` out, it gives me `E510: Can't make backup file (add ! to override)` for files that already exist.  If I try to write out a new file it doesn't give me that error.

**Comment by apriendeau** [comment]
so I ran into this on my other mac, 

```
To start the transition, link your previous configuration so Nvim can use
it:

    mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
    ln -s ~/.vim $XDG_CONFIG_HOME/nvim
    ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
 
```

**Comment by apriendeau** [comment]
but I updated on another machine and its mad that I am not using `~/.nvimrc`. So I dont know what to think right now.

**Comment by define-private-public** [comment]
Okay, moving it to that `.config` directory fixed the startup issue, but I'm still getting `E510` on writing existing files.

**Comment by bruschill** [comment]
@define-private-public I'm getting the same issue with writing existing files.

**Comment by bruschill** [comment]
@define-private-public Have you had any luck getting it figured out?

**Comment by define-private-public** [comment]
Nope.

**Comment by bruschill** [comment]
The default backup directory for swap files is `~/.local/share/nvim/swap`, so in my `init.vim` I added `set backupdir=~/.local/share/nvim/swap` and I stopped getting the error. Let me know if that works for you.

**Comment by apriendeau** [comment]
Yeah, I already had `set backupdir=~/.backups,~/.tmp,~/tmp,/var/tmp,/tmp` in my init.vim so that cured it right away then

**Comment by wlhlm** [comment]
#3496

**Comment by justinmk** [comment]
nvimrc change is covered by https://github.com/neovim/neovim/wiki/Following-HEAD#20151026 and twitter announcement.

The backup write issue is covered by https://github.com/neovim/neovim/issues/3496
