### ISSUE TITLE
Behavior of `:highlight clear` different from original vim

### ISSUE THREAD

**Issue by lzh9102** [neovim/neovim#3537]
NeoVim Version: `e6525f3ceb861f9c5f7e433a5073f16e8d5babc7`
## Description

The `:highlight clear` command works differently than in _vim_. In _vim_, `:highlight default <group> ctermfg=<color>` followed by `:highlight clear <group>` sets the foreground color of `<group>` to `<color>`, but in _neovim_ it does not. Is this an intended behavior?

I tracked down the difference to the functions `set_hl_attr()` and `hl_has_settings()` in `syntax.c`. When executing the `:highlight clear <group>` command in _neovim_, `set_hl_attr()` gets called and sets `sg_attr` of the group to some non-zero value. After that, `hl_has_settings()` will still return `1` for that group because `HL_TABLE()[idx].sg_attr != 0` is true. In _vim_, however, `set_hl_attr()` doesn't modify `sg_attr` of the group, so subsequent `hl_has_settings()` will return `0` for the group.

If `hl_has_settings()` is `1`, All highlight commands with `default` option will be ignored.

This difference breaks some plugins that toggles custom highlighting on and off (for example, `:RainbowToggle` in [rainbow](https://github.com/luochen1990/rainbow). The highlighting is only switched on the first call to `:RainbowToggle`.

NOTE: If omitting the `default` option (`:highlight <group> ctermfg=<color>`), both editors work the same.
## Steps to reproduce
1. Open a syntax-highlighted file (ex. `syntax.c`) in terminal neovim.
2. Navigate until some comments are within the view.
3. Type `:highlight clear Comment`. Now the comments should lose highlighting.
4. Type `:highlight default Comment ctermbg=255`
## Behavior in _vim_

The background color of comments is set to white.
## Behavior in _neovim_

The background color of comments doesn't change.

**Comment by justinmk** [comment]
@lzh9102 Thanks for the detailed report. This appears to be fixed.

> The background color of comments is set to white.

This is the behavior I observe in 0.2. I'm certain that the patch that fixed this is also in 0.1.7
