### ISSUE TITLE
Only loads .nvimrc when specified with -u flag

### ISSUE THREAD

**Issue by benwad** [neovim/neovim#3542]
I recently installed Neovim on Ubuntu from source (using the same location as the 'building from source' instructions). Each time I open Neovim it doesn't seem to load the config file (it's in `~/.nvimrc`) unless I specify it (`nvim -u ~/.nvimrc`). Is this a bug or something to do with the installation location?

**Comment by fwalch** [comment]
See https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

**Comment by ruiafonsopereira** [comment]
Same here. After this `Upgrade: neovim:amd64 (0.0.0+git201510260623+1941+14~ubuntu14.04.1, 0.0.0+git201510270507+1948+14~ubuntu14.04.1)` upgrade, neovim fails to read the folder `autoload` and to load `.vimrc`. Everything was working properly until that update
