### ISSUE TITLE
neovim doesn't load autolad folder

### ISSUE THREAD

**Issue by ruiafonsopereira** [neovim/neovim#3543]
After updating to the latest version, I proceed as described in https://github.com/neovim/neovim/wiki/Following-HEAD#20151026. Despite that neovim loads the `vimrc` file, it is unable to load the vim's `autoload` folder.

**Comment by fmoralesc** [comment]
Did you move the `autoload` folder somewhere in your `runtimepath`?

**Comment by RyanMacG** [comment]
I had this issue too, everything worked fine when I used this structure;

```» ls ~/.config/nvim/
autoload init.vim plugged```

**Comment by justinmk** [comment]
@RyanMacG Right, `autoload` should be directly in `~/.config/nvim/`. What structure were you (and @ruiafonsopereira ) using before?

**Comment by RyanMacG** [comment]
I had previously had everything under `~/.nvim` I just missed the release note, minute I updated everything worked again.

**Comment by ruiafonsopereira** [comment]
@justinmk creating a link to `~/.config/nvim/` seems not to be enough. As @RyanMacG said, the structure should be as follows in order to get this to work:
```
.config/
    .nvim/
        autoload/   # I created a link from Vim's autoload
        bundle/     # Also link from Vim's bundle (or plugged)
```

I'm not sure, but perhaps the release notes should be updated.

**Comment by justinmk** [comment]
> I created a link from Vim's autoload

@ruiafonsopereira  The only directory you need to link is `~/.vim` to `~/.config/nvim`. You have a dot before your `nvim` folder name, that's why it is not working. Documentation does not show a dot.

**Comment by ruiafonsopereira** [comment]
@justinmk I added that dot by mistake (the comment is now updated). First, I linked `~/.vim` to `~/.config/nvim`, which didn't work. To solve that, I needed to link `~/.vim/autoload` to `~/.config/nvim/autoload`.

**Comment by justinmk** [comment]
> To solve that, I needed to link ~/.vim/autoload to ~/.config/nvim/autoload.

That is not necessary. Something else must be misconfigured.

**Comment by ZyX-I** [comment]
@ruiafonsopereira If you have `~/.vim` symlinked to `~/.config/nvim` then `~/.vim/autoload` and `~/.config/nvim/autoload` *are the same directories*. You can’t symlink directory to itself. Most likely all you did is creating symlink `~/.vim/autoload/autoload`.

**Comment by ruiafonsopereira** [comment]
@justinmk, it's a long shot, but what would that be? What would make nvim to fail loading the `autoload` folder?

I say that the `autoload` is not being loaded because I have [vim-plug](https://github.com/junegunn/vim-plug) and [vim-airline](https://github.com/bling/vim-airline) inside, and nvim can't access both.

Thanks.

**Comment by nexusstar** [comment]
@ruiafonsopereira it might be stupid of me to ask but when linking .vim to .config/nvim
 Do you have in .vim init.vim file or only .vimrc?

 In that case you need to make one additional link 

`ln -s ~/.vim/.vimrc ~/.config/nvim/init.vim`

That exactly thing stumbles me for almost two hours. I also use vim-plug and before adding this nvim does not see `autoload` folder.
