### ISSUE TITLE
Use shortcuts on Mac OS with Command key in terminal.

### ISSUE THREAD

**Issue by regedarek** [neovim/neovim#3544]
Hi, 
I digged about it a little but didn't find any solution.
I would like to ask if there is a way to use with NeoVim and Iterm2 ```<D-j>``` shortcut?

I found two PRs: 
https://github.com/neovim/neovim/issues/2190
https://github.com/neovim/neovim/issues/176#issuecomment-37070131

But maybe there are some updates on this.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/2190 is the current state of this.
