### ISSUE TITLE
Terminal buffer is not deleted after changing the cursor position

### ISSUE THREAD

**Issue by ramunas** [neovim/neovim#3548]
The terminal buffer after completing a command is not deleted by pressing any key if the cursor is not at the end of the buffer. The cursor position may be changed with a mouse.

I suppose this bug may be related to #2293.

**Comment by glacambre** [comment]
@ramunas Could you further describe how to reproduce this bug with `nvim -u NORC`? I tried to do `:set mouse=a`, then `:split term://sleep 10` and then entered terminal mode. I waited for the program to exit, moved the cursor by clicking in another buffer and then brought it back to the terminal buffer. I then entered terminal mode again and pressed a key, which closed the terminal window as expected.

**Comment by gpanders** [comment]
The terminal is closed when you send *any* key to the buffer in terminal mode (i.e. "insert" mode for the terminal). If you're in normal mode (which you must be if you're able to move your cursor anywhere in the buffer), pressing a key will not close the buffer.
