### ISSUE TITLE
get some error

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3549]
vim works well
![2015-10-28 23-44-58](https://cloud.githubusercontent.com/assets/13142418/10793996/1ecd1274-7dce-11e5-817a-2cb0aa3e966f.png)
nvim get error
![2015-10-28 23-45-22](https://cloud.githubusercontent.com/assets/13142418/10794071/5dfd1b7e-7dce-11e5-972b-ba110f2b6464.png)

**Comment by justinmk** [comment]
Seems like there is a CRLF line ending somewhere.

**Comment by wsdjeg** [comment]
thank you

**Comment by mhinz** [comment]
@wsdjeg Hi. Can you reproduce this reliably? How?

**Comment by justinmk** [comment]
Pretty sure this was a red-herring related to https://github.com/neovim/neovim/pull/3590

**Comment by wsdjeg** [comment]
thank you ,i will check it tonight,

**Comment by wsdjeg** [comment]
please reopen this issue,it has not been fixed

![2015-11-15 10-08-24](https://cloud.githubusercontent.com/assets/13142418/11166787/ef72922c-8b80-11e5-9255-e768b3c67f2c.png)

**Comment by justinmk** [comment]
@wsdjeg what are minimal steps to reproduce using `nvim -u NONE` ? You did not report `:version`

**Comment by wsdjeg** [comment]
please reopen it @justinmk 
it has not be fixed,
![2015-12-07 20-41-08](https://cloud.githubusercontent.com/assets/13142418/11627079/e47ca3fe-9d22-11e5-8d48-f7deebba727d.png)

![2015-12-07 20-39-59](https://cloud.githubusercontent.com/assets/13142418/11627065/ca260f36-9d22-11e5-930f-1d65e4231833.png)

**Comment by Shougo** [comment]
@wsdjeg In neovim, neocomplete does not work.   You should use deoplete.nvim.

**Comment by wsdjeg** [comment]
i know ,i can delete it ,but also get the error when i use gundo's cammand GundoToggle

**Comment by Shougo** [comment]
@wsdjeg It seems neovim-python's bug.  It is latest version?
I will try it.  Please create the reproduce ways from neovim starting.

**Comment by wsdjeg** [comment]
ok my os is ubuntu ,and i am use ppa day build package,I think it is the latest version.
commands:
```
sudo apt-get remove neovim
sudo apt-get autoclean
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
sudo apt-get install python-dev python-pip python3-dev python3-pip
sudo apt-get install python3.5-dev
```
~/.config/nvim/init.vim

```vim
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'
if 0 | endif
if has('vim_starting')
	if &compatible
		set nocompatible               " Be iMproved
	endif
	set runtimepath+=~/.config/nvim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.config/nvim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/deoplete.nvim'
let g:deoplete#enable_at_startup = 1
let g:JavaComplete_UseFQN = 1
call neobundle#end()
filetype plugin indent on
NeoBundleCheck
syntax on
```

then use :UpdateRemotePlugins 
show me 
![2015-12-07 21-21-20](https://cloud.githubusercontent.com/assets/13142418/11627833/7c6055c6-9d28-11e5-91de-c672b4f5d931.png)

~/.nvimlog this file is not exist

**Comment by wsdjeg** [comment]
here is python python3 and nvim inifo
![2015-12-07 21-22-46](https://cloud.githubusercontent.com/assets/13142418/11627861/b76e7198-9d28-11e5-8375-fd6daf49b06d.png)

**Comment by Shougo** [comment]
@wsdjeg Please upload `pip2 show neovim` and `pip3 show neovim` results.

**Comment by Shougo** [comment]
I think it is same with https://github.com/neovim/neovim/issues/3749

**Comment by wsdjeg** [comment]
i have use this two command intall my py client
pip2 install --user neovim
pip3 install --user neovim
so
![2015-12-07 21-35-36](https://cloud.githubusercontent.com/assets/13142418/11628140/98b8f8fc-9d2a-11e5-9ce7-bbf899c0c113.png)

**Comment by wsdjeg** [comment]
![2015-12-07 21-37-34](https://cloud.githubusercontent.com/assets/13142418/11628158/c05725be-9d2a-11e5-9600-1fff1982a702.png)

**Comment by Shougo** [comment]
@wsdjeg You have installed neovim Python3 module in python3.5.
But your python3 binary is python3.4.  I think something is wrong.

**Comment by Shougo** [comment]
If you want to use Python3.5, the `python3.5` command must be Python3.5.
If you want to use Python3.4, you must install neovim module in Python3.4 path.

**Comment by wsdjeg** [comment]
i just use package manager in ubunutu ,and i can not change the version

**Comment by Shougo** [comment]
@wsdjeg You should check neovim module is installed in your python3.

```
$ python3
>> import neovim
```

**Comment by Shougo** [comment]
I think your correct `g:python3_host_prog` is:

```vim
let g:python3_host_prog = '/usr/bin/python3.5'
```

**Comment by wsdjeg** [comment]
ok change it 
![2015-12-07 21-51-20](https://cloud.githubusercontent.com/assets/13142418/11628452/b39089a4-9d2c-11e5-822c-42ebef98d726.png)

**Comment by wsdjeg** [comment]
wow fied!!
