### ISSUE TITLE
job-control callbacks don't receive newlines

### ISSUE THREAD

**Issue by nerdrew** [neovim/neovim#3555]
I opened this bug on neomake: https://github.com/benekastah/neomake/issues/153

With slow output, the job control callbacks receive partial lines with no way to determine if a complete line was received or not. New line characters seem to be stripped off before passing the "lines" to the callback.

**Comment by tarruda** [comment]
Every item in the list passed to job control callbacks represents a string after a newline(Except the first, of course). If the program outputs: `"hello\nworld"` the corresponding list is `["hello", "world"]`. If the program outputs `"hello\nworld\n"`, the corresponding list is `["hello", "world", ""]`. In other words, you can always determine if the last line received is complete or not.

**Comment by nerdrew** [comment]
```
% cat jobcontrol.vim
function s:JobHandler(job_id, data, event)
  if a:event == 'stdout'
    let str = self.shell.' stdout: '.join(a:data)
  elseif a:event == 'stderr'
    let str = self.shell.' stderr: '.join(a:data)
  else
    let str = self.shell.' exited'
  endif

  call append(line('$'), str)
endfunction
let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_stderr': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }
let job1 = jobstart(['bash'], extend({'shell': 'shell 1'}, s:callbacks))
let job2 = jobstart(['bash', '-c', 'echo -n .; sleep 0.5; echo -n .; sleep 0.5; echo .; sleep 0.5; echo -n .'], extend({'shell': 'shell 2'}, s:callbacks))
```

```
% nvim -u NONE -S jobcontol.vim

shell 2 stdout: .
shell 2 stdout: .
shell 2 stdout: . 
shell 2 stdout: .
shell 2 exited
```

Output should be:
```
% echo -n .; sleep 0.5; echo -n .; sleep 0.5; echo .; sleep 0.5; echo -n .
...
.
```

**Comment by tarruda** [comment]
> It looks like the sleeps are causing the "line" to be read, even though there is no newline.

The `append()` function puts the string in a new line. Here's a small variant of your test:

```vim
let g:chunks = []
function s:JobHandler(job_id, data, event)
  if a:event == 'stdout'
    call add(g:chunks, a:data)
  else
    echo g:chunks
  endif
endfunction

let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }

let job = jobstart(['bash', '-c', 'echo -n .; sleep 0.5; echo -n .; sleep 0.5; echo .; sleep 0.5; echo -n .'], s:callbacks)

```

Which outputs:

```vim
[['.'], ['.'], ['.', ''], ['.']]
```

As expected.

**Comment by nerdrew** [comment]
Hmmmm. I can't tell how to determine where newlines go in the output.

Slight modification: two jobs, one with sleeps, one without:
```
let g:chunks = {}
function s:JobHandler(job_id, data, event)
  if a:event == 'stdout'
    if !has_key(g:chunks, a:job_id)
      let g:chunks[a:job_id] = []
    endif
    call add(g:chunks[a:job_id], a:data)
  else
    echo g:chunks
  endif
endfunction

let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }

let job = jobstart(['bash', '-c', 'echo -n .; sleep 0.3; echo .; echo -n .; echo .; sleep 0.3; echo -n ""; sleep 0.3; echo -n .'], s:callbacks)
let job = jobstart(['bash', '-c', 'echo -n .; echo .; echo -n .; echo .; echo -n ""; echo -n .'], s:callbacks)
```

Actual Output for the 2 jobs:
```
{'1': [['.'], ['.', '.'], ['.', ''], ['.']], '2': [['..', '..', '.']]}
```

Expected output:
```
% echo -n .; echo .; echo -n .; echo .; echo -n ""; echo -n .
..
..
.
```

I think a change similar to this would solve this:
```
% git diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index a1ac713..75a1ca9 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -21502,7 +21502,7 @@ static inline void process_job_event(TerminalJobData *data, ufunc_T *callback,
     while (off < remaining) {
       // append the line
       if (ptr[off] == NL) {
-        list_append_string(event_data.received, (uint8_t *)ptr, off);
+        list_append_string(event_data.received, (uint8_t *)ptr, off + 1);
         size_t skip = off + 1;
         ptr += skip;
         remaining -= skip;
```

**Comment by tarruda** [comment]
> Hmmmm. I can't tell how to determine where newlines go in the output.

It's simple: for every list you receive in a callback, all items except the first represent newlines. Take the previous example output: `[['.'], ['.'], ['.', ''], ['.']]`. If we concatenate according to these rules, the result is "...\n." which match what you'd expect from the sequence of echo commands.

**Comment by ZyX-I** [comment]
@nerdrew No, this change is completely incorrect. `["abc\n"]` is produced for output `"abc\0"`: basically what you do is adding NUL byte. You need to fix the clients:

```VimL
let g:full_stdout = ['']
function s:JobHandler(job_id, data, event)
  if a:event isnot# 'stdout'
    echo g:full_stdout
    return
  endif
  let g:full_stdout = g:full_stdout[:-2] + [g:full_stdout[-1] . get(a:data, 0, '')] + a:data[1:]
endfunction
let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }

let job = jobstart(['bash', '-c', 'echo -n .; sleep 0.3; echo .; echo -n .; echo .; sleep 0.3; echo -n ""; sleep 0.3; echo -n .'], s:callbacks)
```

. This will produce correct lines in `g:full_stdout`: `['..', '..', '.']`. And the line

```VimL
let g:full_stdout = g:full_stdout[:-2] + [g:full_stdout[-1] . get(a:data, 0, '')] + a:data[1:]
```

is the only way to correctly mage two `a:data` arguments. If your code thinks that `data1 + a:data` will produce correct output then *your code* needs to be fixed, not `a:data`.

**Comment by nerdrew** [comment]
Cool. Ok. That works then. Should the `job-control` docs get updated?

Great explanation:
```
for every list you receive in a callback, all items except the first represent newlines
```

Thanks for helping!

**Comment by tarruda** [comment]
> Cool. Ok. That works then. Should the job-control docs get updated?

I agree that the docs may not be clear about some points discussed here. Would you mind sending an improvement to `:h job-control`?
