### ISSUE TITLE
nvimrc file is not picked up with the last version from master

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#3557]
If I open a file with the last version of nvim, my configuration is not picked up. However, if I pass it explicitly using `nvim -u ~/.nvimrc` it works as expected.

Using `git bisect`, I have narrowed down the commit at which point the problem appears https://github.com/neovim/neovim/commit/c2dd07448ff1b2922e8ea14f909a9cbde481e5fc.

I build nvim using the following commands:

```sh
$ rm -r ~/neovim/*
$ make distclean
$ make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=$HOME/neovim" CMAKE_BUILD_TYPE=RelWithDebInfo
$ make install
```

**Comment by wlhlm** [comment]
The default config file location changed recently. See https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

**Comment by scampi** [comment]
right, I forgot about that page... Thanks @wlhlm
