### ISSUE TITLE
xsel logfile location?

### ISSUE THREAD

**Issue by jrobeson** [neovim/neovim#3558]
I'm not sure if neovim should be changing the default or not, but it would be nice to be able to configure the log location or disable the xsel log altogether as it is created even if there is nothing to log.

If we want to set it to something, then it should probably be set to `$XDG_DATA_HOME/nvim`.

According to the man page, it only creates this logfile when detached:

```
       -l filename, --logfile filename
              Specify the file to log errors to when detached. (Default $HOME/.xsel.log)
```

NOTE: this may apply to xclip and/or pb* but I'm not at all familiar with them.

**Comment by justinmk** [comment]
we should probably disable it, or if not possible, specify `$XDG_DATA_HOME/nvim` as you suggest.

**Comment by jrobeson** [comment]
passing `/dev/null` seems to work

**Comment by jrobeson** [comment]
if /dev/null is what you want, then I can submit a PR for that.  But if there are problems that this log could point out, then how would the user ever know?

**Comment by jrobeson** [comment]
i don't think the entry-evel tag is justified until there's an implementation suggestion.

**Comment by justinmk** [comment]
Should be a matter of modifying `runtime/provider/clipboard.vim`

**Comment by jrobeson** [comment]
yeah I know that part, but modified to what?  What if there is a clipboard problem? how will the user ever know?

**Comment by jrobeson** [comment]
I've never really used xsel, so I have no idea if that happens in practice much.

**Comment by justinmk** [comment]
We show an error if it fails.

**Comment by jrobeson** [comment]
in the detach case?

**Comment by Grimy** [comment]
IMHO, the default is perfectly fine. `/dev/null` is completely unacceptable, since it irreversibly destroys potentially useful data regarding the error. `$XDG_DATA_HOME/nvim` complicates things for no good reason (xsel errors are now split between two different locations).

I think the “right thing” is to redirect `xsel`’s logs to a pipe or temp file, and then `echoerr` its contents if there is an error. That’s a good deal of work for not much gain: after using `xsel` for a few years, my .xsel.log is only 18 lines long, and they’re all the same: `XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"`.

**Comment by jrobeson** [comment]
the default isn't fine to me :).  I switched to neovim once the XDG patch was merged to stop more things from junking up my `$HOME`

**Comment by Pyrohh** [comment]
@Grimy stated my main gripes with this suggestion, which is that xsel error logs would now be split in two separate files for not much good reason, and that there is not much benefit.

Not every program implements the XDG spec, e.g., xsel, which is disappointing, but not exactly a big loss. At least in this case--where we have an application which doesn't support the XDG spec--it's easier to just leave it as is compared with emulating XDG stuff.

**Comment by Grimy** [comment]
Yup. This really belongs in xsel’s issue tracker: they should respect XDG by default. There’s not much Neovim can do about it: even if we send xsel’s logs to $XDG_DATA_HOME/nvim (which isn’t XDG-compliant, by the way; it really should be $XDG_DATA_HOME/xsel), xsel will still pollute your home dir when you invoke it from the command-line.

**Comment by jrobeson** [comment]
i figure I'll solve it with a version in my $HOME/bin

**Comment by Grimy** [comment]
Try the following:

    #!/bin/sh

    dest="${XDG_DATA_HOME-$HOME/.config}/xsel"
    mkdir -p "$dest"
    /usr/bin/xsel -l "$dest/log" "$@"
