### ISSUE TITLE
Ruby Support in Ubuntu 15.10

### ISSUE THREAD

**Issue by NerdsvilleCEO** [neovim/neovim#3559]
I tried using vim-plug and it does not load from the ~/.nvim/autoload or the ~/.vim/autoload directory... after doing a bit of digging, it turns out the neovim package for Ubuntu is not compiled with ruby support

Running :echo has('ruby') returns 0... could this be why vim-plug is not working?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1770

**Comment by justinmk** [comment]
But vim-plug uses neovim built-in job control for async, it does not require ruby at all--you must be using a very old version of vim-plug.

**Comment by NerdsvilleCEO** [comment]
I pulled it down from git, I am just switching over to neovim... when I run :PlugInstall in vanilla vim it runs, but for some reason it says command not found in neovim... is there a different directory I have to put autoloads in?

**Comment by justinmk** [comment]
please read `:help nvim-from-vim`

**Comment by NerdsvilleCEO** [comment]
Worked! Thanks! :)
