### ISSUE TITLE
use long form options when calling external tools/programs

### ISSUE THREAD

**Issue by jrobeson** [neovim/neovim#3560]
I'd suggest that the long form names always be used when calling any sort of external tool.

Taking xsel (for clipboards) as an example:

Use `xsel --output --clipboard`
instead of: `xsel -o -b`

**Comment by justinmk** [comment]
@jrobeson PR would be welcome!

**Comment by jrobeson** [comment]
there's no point doing a PR if people don't keep the the standard. If it's not policy, then people won't enforce it when adding new programs (and/or options to programs)

**Comment by justinmk** [comment]
True. This also applies to vim options (`'shellcmdflag'` instead of `'shcf'`) and commands. I've noted this in a pending update to our development guidelines.
