### ISSUE TITLE
Link to changelog in Readme

### ISSUE THREAD

**Issue by HolgerPeters** [neovim/neovim#3564]
I finally found https://github.com/neovim/neovim/wiki/Following-HEAD which is a great resource if you use and update neovim on a daily base. I remember looking for some page like this some days ago and did not find it then.

I suggest linking to this page in the README file so neovim users can quickly follow the changes, especially when they reinstall their neovim installation and find out something is not working as expected.

Would also reduce the amount of tickets in the issue tracker by confused users

**Comment by Pyrohh** [comment]
I think that might be a good idea. Then again, it's mentioned at the top of [Building-Neovim](https://github.com/neovim/neovim/wiki/Building-Neovim) and [Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim) pages in bold...

> Would also reduce the amount of tickets in the issue tracker by confused users

Heh, I don't think anyone actually reads that :-)

**Comment by Pyrohh** [comment]
I added a link to the Following-HEAD page at the top of [Troubleshooting](https://github.com/neovim/neovim/wiki/Troubleshooting) on the wiki, which I think is a good compromise. We've been trying to keep our README.md small, which is why I didn't put the link there.
