### ISSUE TITLE
Neovim fails to build on Arch linux.

### ISSUE THREAD

**Issue by StanislavNikolov** [neovim/neovim#3567]
Following the instructions [here](https://github.com/neovim/neovim/wiki/Installing-Neovim), i couldn't build neovim. The first error i got was:
> CMake Error at /usr/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

Fixed this by installing pkg-config.
Then this happened:
> libtoolize:   error: One of these is required:
libtoolize:                 gm4 gnum4 m4

Fixed with pacman -S m4.

Again, just a bunch of errors:
> /home/stanislav/neovim/.deps/build/src/libuv/autogen.sh: line 44: aclocal: command not found
CMakeFiles/libuv.dir/build.make:105: recipe for target 'build/src/libuv-stamp/libuv-configure' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 127
make[3]: Leaving directory '/home/stanislav/neovim/.deps'
CMakeFiles/Makefile2:216: recipe for target 'CMakeFiles/libuv.dir/all' failed
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: Leaving directory '/home/stanislav/neovim/.deps'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/stanislav/neovim/.deps'
Makefile:70: recipe for target 'deps' failed
make: *** [deps] Error 2

None of the packages I installed were listed in the [prerequisites list](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites). As far as I can tell it wants me to install a bunch of packages to continue. Am I doing something wrong?

**Comment by wlhlm** [comment]
AUR packages assume that you have the `base-devel` group installed, which includes some tools required for building software from source.

https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

```
# pacman -S base-devel
```

**Comment by Pyrohh** [comment]
> AUR packages assume that you have the base-devel group installed

Indeed, and if you were compiling without the PKGBUILD you would have installed base-devel anyways (it's mentioned at the last link you provided @StanislavNikolov).

**Comment by ManIVIctorious** [comment]
Just tried the AUR Package and it compiles just fine
