### ISSUE TITLE
Last builds give a broken neovim

### ISSUE THREAD

**Issue by metal3d** [neovim/neovim#3568]
After having updated neovim on Fedora 22 (via RPM) I contacted author to report some problems:
- .nvimrc seems to not load
- :source .nvimrc doesn't load my plugins
- coloration is borkent
- and so on.

I tried to build myself (master) following documentation and the problem persists.

So I decided to use `git bisect`. After some build, I had this:

```
git bisect bad
Bisecting: 0 revisions left to test after this (roughly 1 step)
[674629be0c8bc02d79d263b1b795ab125e1341e0] os/env: Add functions that can iterate over colon-separated variables
```

I did a new "git bisect bad" and tried. Problem persists:

```
 git bisect bad 
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[c2dd07448ff1b2922e8ea14f909a9cbde481e5fc] option,main: Partial support of XDG base directory specification
```

Finnaly,:
```
git bisect bad
c2dd07448ff1b2922e8ea14f909a9cbde481e5fc is the first bad commit
commit c2dd07448ff1b2922e8ea14f909a9cbde481e5fc
Author: Keerthan Jaic <jckeerthan@gmail.com>
Date:   Tue Aug 4 21:41:38 2015 -0400

    option,main: Partial support of XDG base directory specification
    
    - Add functions that are able to query XDG.
    - Replace defaults for
      - &runtimepath. Does not follow #78.
      - &viewdir.
      - &undodir.
      - &directory.
      - &backupdir. Does not follow #78.
      - vimrc location.
    - Remove user vimrc file line from :version message.

:040000 040000 6beb0f697150887cc897a2d461a4657b06510233 c94c9d0344e5defe6767d07ec2a21b51c46a863d M	src

```

I'm surprised that the problem exists since August without any report. Is there anyone that may have a look ?

Note: to compile, I remove the entire `build` directory. Each of my `git bisect good` are made by launching "nvim" seeing my plugins wirking (vim-airline, NERDTree, and so on), and `git bisect bad` when I open nvim (after install process) and seeing a broken interface.

Thanks a lot.

**Comment by metal3d** [comment]
Note:
This version is ok, wich is "one commit before the reported bad commit "

```
 git log -n1
commit e38cbb93670272d0da15c60222a123b88ec55002
Merge: ea01c40 3e84a91
Author: Justin M. Keyes <justinkz@gmail.com>
Date:   Mon Oct 19 18:53:46 2015 -0400

    Merge pull request #1909 from equalsraf/tb-os_serveraddress
    
    server_address()
```

**Comment by wlhlm** [comment]
The location in which neovim searches for configuration has changed recently. Please refer to https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

**Comment by metal3d** [comment]
Damned, I didn't seen this... my apologies ! And the commit message is correct... "vimrc location".
Next time, I will read the entire commit message.

It's working. Thanks a lot @wlhlm
