### ISSUE TITLE
Asynchronous loading of plugin provider

### ISSUE THREAD

**Issue by critiqjo** [neovim/neovim#3573]
**Performance issue**: The first time python is loaded (e.g. by executing `:python print "hello"`), it takes a few seconds, blocking the UI.

**Proposed solution**: Introduce a new command, say `:LoadProvider` which takes a provider name as parameter and spawns the corresponding process in the background, asynchronously. I can then add `LoadProvider python` to my `init.vim` which won't affect the startup time of Neovim, as well as my python plugins will load superfast.

**Assumption**: Remote plugins do not try to invoke their "remote-part" during startup.

**Extended solution**: Add a `ProviderLoaded` autocommand, as well as global variables of the form `g:loaded_provider_<name>` which will be set to `1` once it's loaded completely. Plugins can leverage this `au` instead of directly invoking provider at start-up.

**Comment by tarruda** [comment]
The remote plugin manifest covers this to a certain extent: After a remote plugin is installed and the manifest is updated, the generated commands/functions/autocommands will spawn the provider on first use.

This doesn't work for the `if_python` emulation though: These plugins often execute python code during startup.

**Comment by critiqjo** [comment]
Improving responsiveness of plugins which execute python code during startup is hard. But as long as that don't happen, we can preload the provider at startup (in a non-blocking way), so that the "first use" will be fast.

**Comment by critiqjo** [comment]
Not a significant gain in performance/responsiveness, and lack of interest... Closing...

**Comment by bfredl** [comment]
I might a PR soon (now that #4384 is merged) that allows this manually by adding a line at start of nvimrc (specifically for python).
