### ISSUE TITLE
provider: Improve error message "Unknown function: provider#python#Call"

### ISSUE THREAD

**Issue by ramunas** [neovim/neovim#3577]
Using the :python command whenever there is no 'neovim' python package installed results in the following error message

E117: Unknown function: provider#python#Call

This is quite unhelpful. It would much better if neovim would give some indication to what the problem is. I would suggest replacing the error with something like the following: 'The neovim package was not found for your python interpreter'.

**Comment by jebberjeb** [comment]
Ran into this myself recently. Is this something people are open to? If so, wouldn't mind taking a shot at a PR.

**Comment by fmoralesc** [comment]
@jebberjeb If you want to tackle this, go ahead ;)

**Comment by jebberjeb** [comment]
Alright, will do.

**Comment by mhinz** [comment]
@jebberjeb Are you working at it or still want to? :)

**Comment by jebberjeb** [comment]
@mhinz jumpin on it now -- need the low hanging fruit!

**Comment by jebberjeb** [comment]
What should the message say exactly?

**Comment by rstacruz** [comment]
This is happening to me still on OS X, with nvim installed via `brew install neovim/neovim/neovim`:

```
→  nvim --version
NVIM 0.1.5
Build type: RelWithDebInfo
```

```
→ pip show neovim
---
Metadata-Version: 1.1
Name: neovim
Version: 0.1.9
```

Even a blank init.vim gets me this error when doing `:python print "hello"`.

**Comment by wsdjeg** [comment]
@ramunas please see https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/python.vim#L22-L25
it is due to the s:prog is '', so the script `finish`ed here, then the function `provider#python#Call` will not be loaded.

**Comment by fwalch** [comment]
@rstacruz try `:CheckHealth"

**Comment by phanimahesh** [comment]
@jebberjeb Have you made any progress on this?

If you can not complete what you started, or could not start this, it's okay, life gets in our way. It would be great if you can share any code in progress, or any pointers that can help people looking to tackle this.

**Comment by eddy-geek** [comment]
FYI, with neovim default install under fedora 25 (`dnf install neovim`) I got this error as python3-neovim is not a dependency.

**Comment by justinmk** [comment]
@eddy-geek Python support is optional, it's not needed unless you have python plugins. That's why it is a separate package.

**Comment by Benhgift** [comment]
@justinmk should it be default though? Vim ships with python3 as the default these days, and a lot of packages use python (I got here from google from my broken vimrc)

**Comment by justinmk** [comment]
> Vim ships with python3 as the default these days

It doesn't. Some distros enable it (linked to specific versions of python). Distros are free to pre-install the neovim python module, though I discourage it.

Anyways, that isn't relevant to this issue, the error message needs improvement regardless.

**Comment by DancingQuanta** [comment]
I kept getting ` Unknown function: provider#python#Call` despite `:checkhealth` confirming that I have python3 and neovim python cilent installed. I started my session with `nvim -u NONE` on windows 10 cmd. The version of nvim is 0.2.2 extracted from a zip file for 64 bit nvim.

**Comment by justinmk** [comment]
@DancingQuanta Try the development version. https://github.com/neovim/neovim/releases

**Comment by DancingQuanta** [comment]
With the latest development version `NVIM v0.2.3-993-g066ef0d8a`, the situation remains identical as with `0.2.2` when nvim is started with `nvim -u NONE`.
The output of `:checkhealth` for python3 is
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "~/Anaconda/python.exe"
  - INFO: Multiple python.exe executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Users\andre\Anaconda3\python.exe
  - INFO: Other python executable: /python.exe
  - INFO: Python3 version: 3.5.4
  - INFO: python.exe-neovim version: 0.2.4
  - OK: Latest python.exe-neovim is installed: 0.2.4
```

**Comment by justinmk** [comment]
> Am I not suppused to be able to use python3 with -u NONE

Correct. `-u NONE` disables plugins, try `-u NORC` instead.

**Comment by DancingQuanta** [comment]
Okay strange. I was trying to make sure my windows neovim picks up python which works now but I wonder why '-u NORC' acts like python provider does not exist. I checked with WSL and it have the same behaviour thougth I have not updated WSL's neovim in a while.

**Comment by bala10298** [comment]
using
pip3 install neovim
solved me this issue
