### ISSUE TITLE
vim plugin are not working since an update

### ISSUE THREAD

**Issue by GCorbel** [neovim/neovim#3582]
Hi,

I updated neovim yesterday and, since this, all plugins does not work. For example, I have `execute pathogen#infect()` that say than the function is undefined. Obviously, I installed pathogen under ~/.nvim/autoload. Colorschemes are not working too.

It works with vim.

**Comment by Pyrohh** [comment]
> Obviously, I installed pathogen under ~/.nvim/autoload

That's the problem: see https://github.com/neovim/neovim/wiki/Following-HEAD#20151026

This should at least start you on the right path:
```
$ mkdir -p ~/.config
$ mv ~/.nvim ~/.config
$ mv ~/.nvimrc ~/.config/nvim/init.vim
```
