### ISSUE TITLE
neovim doesn't use vimrc 

### ISSUE THREAD

**Issue by Nedgang** [neovim/neovim#3586]
Hi all. I am working on Fedora 22, neovim built from source. 
Since the last neovim update, it seems to not use anymore my .nvimrc (I've clone both my .vimrc and .vim to .nvim and .nvimrc).

	lrwxrwxrwx   1 david david   16 28 oct.  18:18 .nvim -> /home/david/.vim
	lrwxrwxrwx   1 david david    6  6 oct.  21:29 .nvimrc -> .vimrc

This is my nvim version:

        david@yoshi:~$ nvim --version
        NVIM 0.1.0 (compiled Nov  2 2015 17:42:04)
        Commit: v0.1.0
        Build type: Debug
        Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/david/neovim/build/config -I/home/david/neovim/src -I/home/david/neovim/.deps/usr/include -I/home/david/neovim/.deps/usr/include -I/home/david/neovim/.deps/usr/include/luajit-2.0 -I/home/david/neovim/.deps/usr/include -I/home/david/neovim/.deps/usr/include -I/home/david/neovim/.deps/usr/include -I/home/david/neovim/.deps/usr/include -I/usr/include -I/home/david/neovim/build/src/nvim/auto -I/home/david/neovim/build/include
        Compiled by david@yoshi

        Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
        For differences from Vim, see :help vim-differences

           system vimrc file: "$VIM/sysinit.vim"
             fall-back for $VIM: "/usr/local/share/nvim"

Thanks

**Comment by wlhlm** [comment]
The default config file location changed recently according to the XDG spec. More at https://github.com/neovim/neovim/wiki/Following-HEAD#20151026
