### ISSUE TITLE
Arrow <NOP> not sourced properly on nvim start

### ISSUE THREAD

**Issue by archmint** [neovim/neovim#3591]
I disabled my arrow keys with

```vim
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
```

It works fine with vim, but when I open a file with `nvim`, I can go into --insert-- mode and press \<Up\> and \<Down\> still. It seems like something isn't being sourced properly. If I run `:so $MYVIMRC`, then the behavior actually stops and I can no longer use \<Up\> and \<Down\> in --insert-- mode. I have no theories but have not seen any other issues with $MYVIMRC not sourcing other things properly with neovim.

NOTE: so you are aware, this is on archlinux with version as follows:

```
NVIM 0.1.0 (compiled Nov  2 2015 18:05:23)
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.0/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
```

**Comment by Grimy** [comment]
I can’t reproduce this. Please try the command `:verbose imap <Up>` and report the results.

**Comment by archmint** [comment]
@Grimy It appears as though it is being reset by YouCompleteMe - but only in neovim ... the weird thing is that I remap after I tell neobundle to use YouCompleteMe.

**Comment by ZyX-I** [comment]
@archmint When you tell Neobundle to use YCM the only thing neobundle needs to do is to add YCM path to `&runtimepath`. It does *not* actually pull in any YCM functionality yet, except that autoload functions become available.

**Comment by Grimy** [comment]
Indeed. If you want to override something that it set by a plugin, you have to do it after the plugin is actually sourced: either in a VimEnter autocommand, or in a `after/plugin/*.vim` file in your runtime.

**Comment by dylnmc** [comment]
Well, I just said that I did it _after_, so looks like a problem.
