### ISSUE TITLE
Editorconfig plugin errors after nvim update to 0.1.0

### ISSUE THREAD

**Issue by lsocrate** [neovim/neovim#3592]
Hi, 
I am running Arch linux and I just updated nvim from AUR to community version 0.1.0. But now my editorconfig plugin is throwing errors on startup.
 
```
Vim(if):Channel was closed by the client
Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
Error detected while processing function <SNR>20_InitializePythonBuiltin..provider#python#Call:
line   15:
E168: :finish used outside of a sourced file
Error detected while processing /home/lsocrate/.config/nvim/plugged/editorconfig-vim/plugin/editorconfig.vim:
line  324:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/3590

**Comment by blueyed** [comment]
@lsocrate 
The real error will still be there probably. Make sure to have python-neovim installed correctly.

**Comment by lsocrate** [comment]
Thanks. :)

**Comment by blueyed** [comment]
@lsocrate 
Can you provide more feedback?  Was python-neovim missing?
I think the issue was initially triggered with Arch's broken package, which got updated in the meantime.

**Comment by lsocrate** [comment]
Honestly, I don't know what happened. I did a complete reinstall of neovim, python-neovim and my plugins and everything started working ok. If you need any specific data or log to debug I would be happy to help.

**Comment by blueyed** [comment]
Thanks for the offer and reporting back, should be fine by now.

Happy (neo)vimming! :)
