### ISSUE TITLE
Escape Key not working as expected with Neovim and Tmux 2.1

### ISSUE THREAD

**Issue by gavsim** [neovim/neovim#3593]
Hi, 

I am trying to migrate across to using Neovim full time but have come across a bug which is preventing me.

I am running Tmux 2.1 and when I launch a new session and run Neovim, whenever I am in insert mode I have to press escape twice to actually exit insert mode. If I only press escape once and then press the letter 'i' I get an 'é' output in insert mode. This does not happen if I am running Neovim not in a Tmux session, but If I run vim both with and without a tmux session I have no problem escaping insert mode etc..

My setup is Neovim 0.1
Tmux 2.1
iTerm 2 nightly

Any help or pointers where I am going wrong would be greatly appreciated.

Thanks

**Comment by wlhlm** [comment]
It may help to reduce tmux `escape-time`. Ref tmux/tmux#131

**Comment by gavsim** [comment]
@wlhlm Thank you, I've reduced it down to 0 and working great!

**Comment by daniely** [comment]
I had the same issue. `set escape-time 0` fixed it for me.

**Comment by butla** [comment]
Any idea why this isn't a problem with standard vim? If this is a tmux issue, then tmux should capture the escape for normal Vim as well. Or does normal Vim somehow deciphers the escape sequence sent to it by Tmux (e.g. when you switch out of insert mode, and immediately issue 'gg') and the thing you expected?

Handling keys in terminal never ceases to amaze me.

**Comment by justinmk** [comment]
It _is_ a problem in Vim. The way the problem manifests is different because Vim doesn't handle meta chords by default.

https://github.com/neovim/neovim/wiki/FAQ#why-doesnt-this-happen-in-vim

**Comment by butla** [comment]
@justinmk Thanks for the explanation. I feel that now this issue thread is complete and will serve posteriority well :)
