### ISSUE TITLE
QB tests failing since shada merge 3 weeks ago...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#3594]
I'm not sure why, but this is what I see in the TAP reports for every platform:

```text
test/functional/eval/msgpack_functions_spec.lua @ 454
Failure message: ./test/functional/helpers.lua:71: Failed to evaluate expression
stack traceback:
./test/functional/helpers.lua:71: in function 'eval'
test/functional/eval/msgpack_functions_spec.lua:457: in function <test/functional/eval/msgpack_functions_spec.lua:454>
```

There's still the ordering problem in the one test too:

```text
test/functional/shada/marks_spec.lua @ 103
Failure message: test/functional/shada/marks_spec.lua:112: Expected objects to be the same.
Passed in:
(string) 'estfile-functional-shada-marks-2'
Expected:
(string) 'Xtestfile-functional-shada-marks'
stack traceback:
test/functional/shada/marks_spec.lua:112: in function <test/functional/shada/marks_spec.lua:103>
```

**Comment by jszakmeister** [comment]
For the shada problem, I've only been able to determine that it appears `v:oldfiles` is not in the expected order.  Looking at the shada files between two different platforms didn't turn up much.  On the surface, they appear to be awfully similar with the entries in the same order.  However, under Linux, `v:oldfiles` has marks-2 coming first, while on other platforms marks comes first.

**Comment by tarruda** [comment]
>  However, under Linux, v:oldfiles has marks-2 coming first, while on other platforms marks comes first.

@ZyX-I any idea what could be causing this? I haven't looked at the code but maybe sorting the list in test(I assume it doesn't matter in production) will fix the issue

**Comment by tarruda** [comment]
Some `table.sort` calls seems to fix the problem:

```diff
diff --git a/test/functional/shada/marks_spec.lua b/test/functional/shada/marks_spec.lua
index f03b330..6818844 100644
--- a/test/functional/shada/marks_spec.lua
+++ b/test/functional/shada/marks_spec.lua
@@ -108,6 +108,7 @@ describe('ShaDa support code', function()
     nvim_command('qall')
     reset()
     local oldfiles = meths.get_vvar('oldfiles')
+    table.sort(oldfiles)
     eq(2, #oldfiles)
     eq(testfilename, oldfiles[1]:sub(-#testfilename))
     eq(testfilename_2, oldfiles[2]:sub(-#testfilename_2))
@@ -115,6 +116,7 @@ describe('ShaDa support code', function()
     eq(tf_full_2, oldfiles[2])
     nvim_command('rshada!')
     local oldfiles = meths.get_vvar('oldfiles')
+    table.sort(oldfiles)
     eq(2, #oldfiles)
     eq(testfilename, oldfiles[1]:sub(-#testfilename))
     eq(testfilename_2, oldfiles[2]:sub(-#testfilename_2))
```

No clue about the failure on `test/functional/eval/msgpack_functions_spec.lua` though, can't reproduce on my machine.

**Comment by jszakmeister** [comment]
> Some table.sort calls seems to fix the problem:

Yeah, I was going to take that approach, but I think order matters.

> No clue about the failure on test/functional/eval/msgpack_functions_spec.lua though, can't reproduce on my machine.

I'm starting to suspect it was knock-on effects of other failures.  Master passed with the exception of the ordering issue.

**Comment by ZyX-I** [comment]
Order did not matter previously with Vim and does not now. Though this error indicates that for some reason order of local mark entries in a ShaDa file is reversed (`v:oldfiles` list is not sorted, and is populated while reading ShaDa file), but this is most likely the result of the `qsort` function application. Alternative fix should be adding `nvim_command('sleep 2')` before the second `edit` in the test.

**Comment by jszakmeister** [comment]
If order doesn't matter, then I'm all for sorting the results.  @tarruda Care to check in your fix?

**Comment by jszakmeister** [comment]
Closing this for now.  The other issues may have been side-effects of another issue, but I don't see it on master now.
