### ISSUE TITLE
neovim is very slow when editing .c files

### ISSUE THREAD

**Issue by teamblubee** [neovim/neovim#3596]
I have a very simple neovim custom build from source. Build command from build directory:
rm -rf * && cmake cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/nvim CMAKE_BUILD_TYPE=Release ../ && make CMAKE_BUILD_TYPE=MinSizeRel && make install

currently I have nvim 0.1.0 installed.

I have vundle installed with a few plugins.
```shell
" My Plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'rhysd/vim-clang-format'
```
this is my init.vim file
```shell
set nocompatible              " be iMproved, required

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/nvim/bundle/Vundle.vim
" set rtp+=/opt/nvim/bundle/Vundle.vim
call vundle#begin('~/.config/nvim/bundle')
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo

Plugin 'Valloric/YouCompleteMe'
Plugin 'rhysd/vim-clang-format'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` 
    " to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` 
"   to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` 
"   to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

let g:python_host_prog  = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'

if !executable('clang-format') && executable('clang-format-3.5')
  let g:clang_format#command = 'clang-format-3.5'
endif

autocmd FileType c nnoremap <buffer> <silent> <C-]> :YcmCompleter GoTo<cr>
set tabstop=4 shiftwidth=4 expandtab

colorscheme elflord
:set cc=80
:set number
:set relativenumber
:syntax on
:set encoding=utf-8
:set scrolloff=3
:set autoindent
:set showmode
:set showcmd
:set hidden
:set wildmenu
:set wildmode=list:longest
:set visualbell
:set cursorline
:set ttyfast
:set ruler
:set backspace=indent,eol,start
:set laststatus=2

"YouCompleteMe
let g:ycm_global_ycm_extra_conf = "~/.config/nvim/.ycm_extra_conf.py"

"adding space when I press enter
:nnoremap <Enter> o<ESC>
:nnoremap <S-Enter> O<ESC>

"nvim terminal emulation window commands
:tnoremap <Esc> <C-\><C-n>
:tnoremap <A-h> <C-\><C-n><C-w>h
:tnoremap <A-j> <C-\><C-n><C-w>j
:tnoremap <A-k> <C-\><C-n><C-w>k
:tnoremap <A-l> <C-\><C-n><C-w>l
:nnoremap <A-h> <C-w>h
:nnoremap <A-j> <C-w>j
:nnoremap <A-k> <C-w>k
:nnoremap <A-l> <C-w>l

set backupdir=~/.config/nvim/vim_bakup/backup//
set directory=~/.config/nvim/vim_bakup/swap//
set undodir=~/.config/nvim/vim_bakup/undo//
```

when I start editing even the simplest main..c file it slows taking even a few seconds from pressing i to go to editing mode, pressing esc and then i again is even slower!

**Comment by ajpaulson** [comment]
Can you try editing a C file without sourcing `YCM` or `vim-clang-format`?
I have some large C files and can't reproduce this - I don't use either of these plugins so they may be causing this.

**Comment by torpak** [comment]
YCM is the culprit. This has nothing to do with neovim. It's exactly the same using regular vim.

**Comment by teamblubee** [comment]
Running some tests on my system, I uses neovim with YCM, neovim without YCM, vim with and without YCM and from prior experience working with neovim and YCM on mac with brew it's not YCM causing the issues.

There is an obvious pause when i use neovim to open almost any document.

**Comment by tarruda** [comment]
I use neovim with YCM to edit neovim C files, something else must be causing this.

**Comment by ajpaulson** [comment]
@teamblubee Have you tried with `nvim -u NONE` ?

I notice that you also have checks to see if a clang-format binary is available (I guess for the vim-clang-format plugin) and that may be an issue. 

To be sure, try with the above command to see if it happens with no user configuration and work up from there.

**Comment by tarruda** [comment]
> I notice that you also have checks to see if a clang-format binary is available (I guess for the vim-clang-format plugin) and that may be an issue.

I remember @oni-link once reported a slowdown with clang-format, caused by the python client. This could be the issue.

**Comment by teamblubee** [comment]
@ajpaulson  I tried running nvim -n NONE

then there's no plugins and it runs fine, could it be the terminal emulator that's slow? Looking at the only other change was on mac I was using iTerm as that's the default and on Debian the default seems to be gnome-terminal.

**Comment by ajpaulson** [comment]
If it runs fine with no plugins then it's most likely one of the plugins.

As @tarruda mentioned, it may be an issue with clang-format caused by the python client.
Test with your standard configuration just with vim-clang-format removed and see how it is.

**Comment by torpak** [comment]
If that doesn't help, you could try a binary search to see which plugin causes the problem. Have you established that it doesn't happen with regular vim?

**Comment by teamblubee** [comment]
@torpak 
totally removing clang format seems that vim-clang-format or python is causing the issue. Is there a way to keep clang-format without making editing code dreadfully slow?

**Comment by ajpaulson** [comment]
Open an issue with the vim-clang-format developer.

Alternatively, call the clang-format binary without using a plugin (personally I simply call it from the shell as needed - you could try mapping to vim commands depending on how you use it)

**Comment by skupr** [comment]
@teamblubee Try profiling:
http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow

**Comment by teamblubee** [comment]
@ajpaulson thanks i'll take it up with the vim-clang-format developer.
@skupr thanks a lot, that's a good tip. I'll run nvim with that for a while and see how things go.

**Comment by torpak** [comment]
The clangformat plugin is AFAIK a very thin python wrapper around the 
clangformat binary. You could do some profiling to find out, what's 
causing the delay. If python is not your thing, it shouldn't be too hard 
to write a set of vimscript functions that use the clangformat binary 
directly.

**Comment by justinmk** [comment]
Clang-format should use the job control features of Neovim. I expect the pause is present in Vim also, assuming clang-format is installed and working.
