### ISSUE TITLE
:bro[wse] ol[dfiles][!] does not prompt for a number

### ISSUE THREAD

**Issue by florentc** [neovim/neovim#3598]
In **VIM** the `:browse oldfiles` (or `:bro ol`) command lists recently opened files and then prompts for a number that matches one of those file to load it.
In **NVIM**, the same command is no different from `:oldfiles` (or `:ol`): it only displays a list of recently opened files. The prompt never shows up.

**Comment by ajpaulson** [comment]
I just compared - in Vim even `:oldfiles' prompts for a number to be input.
In Nvim I get the same behaviour as you describe - the files are numbered, there is the `--MORE--` prompt (shouldn't this be loaded as a quickfix window with scrolling?) and at the end of the list it closes with no prompt.

**Comment by mhinz** [comment]
The prompting code was removed, although I don't know why. If nobody knows a reason against it, I'm gonna put it back in.

**Comment by tarruda** [comment]
> The prompting code was removed, although I don't know why. If nobody knows a reason against it, I'm gonna put it back in.

Could have happened by accident. Was the code present in the first commit?

**Comment by mhinz** [comment]
> Could have happened by accident. Was the code present in the first commit?

Yup, it's missing in the first commit already. And all references to `cmdmod.browse` in general.

**Comment by justinmk** [comment]
@mhinz yes, I opened a reminder issue long ago to restore FEAT_BROWSE. So feel free.

**Comment by mhinz** [comment]
@justinmk Oh, found it.

Since restoring the code should solve this issue, I'll close this issue.

Please direct all follow-up posts to https://github.com/neovim/neovim/issues/2160
