### ISSUE TITLE
Fix color lookup in term_init().

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#3601]
LeoNerd on Gitter:

> please change [this line](https://github.com/neovim/neovim/blob/master/src/nvim/terminal.c#L182) to for(int color_index = 255; color_index >= 0; color_index--) so you'll find the "correct" black

cc @tarruda

**Comment by 14rcole** [comment]
Excuse my lack of knowledge, but I've never contributed to an open source project before.  I cloned the neovim repository and edited the code.  Now do I submit a pull request?  If so, is there some documentation as to what I'm supposed to say in the pull request?  Thanks

**Comment by ajpaulson** [comment]
@14rcole this help article from Github should help with the basics: https://help.github.com/articles/using-pull-requests/

I would also recommending looking at `Contributing.md` in this repository.

**Comment by rainerborene** [comment]
That one line fix is supposed to fix this? See below image.

![wrong_black](https://cloud.githubusercontent.com/assets/101501/11040292/a5eaffaa-86f2-11e5-8069-2490f800d211.jpg)

**Comment by mhinz** [comment]
@tarruda Why isn't this fixed yet? Is the problem more hideous than it seems?

If it's really just that one line fix, we should mark it as `entry-level`.
