### ISSUE TITLE
Unable to bind CTRL-h to anything

### ISSUE THREAD

**Issue by JackDanger** [neovim/neovim#3612]
Steps to reproduce:

Works:
```
$ nvim -U NONE -c 'map <C-j> itype'
```
Then type `CTRL-J` and, as expected, vim enters insert mode and prints the words 'type'

Does not work:
```
nvim -U NONE -c 'map <C-h> itype'
```
Then type `CTRL-h` and the cursor goes back one character. CTRL-h cannot be mapped with `vmap`, `nmap`, etc. either.

This is on latest master (32a9022db11ae0138de44feb5e4dbef64f4ae03b) built

**Comment by khalidchawtany** [comment]
Take a look at [this](https://github.com/neovim/neovim/issues/2048#issuecomment-78045837) issue.

If you want a quick solution, go with @tarruda 's fix:
```
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
```

**Comment by JackDanger** [comment]
Thank you, @khalidchawtany. I'll close this as duplicate.
