### ISSUE TITLE
Yanking into the same registry slot as the macro's being recorded cause macro to be yanked instead.

### ISSUE THREAD

**Issue by chakrit** [neovim/neovim#3613]
The steps to record the macro are as follows:
1. Create a file with `the quick brown fox jumps over the lazy dog.`
2. Opens in vim/neovim
3. `/fox` - Position cursor on the word `fox`
4. `qyve"yxq` - Yank `fox` into `y` while recording macro `y` .
5. `"yp` - Try to paste from the register.
6. Garbage is pasted

Not sure if this is the expected behavior, which also happens in VIM 7.4, or a bug. Either way a comment would be appreciated. Should neovim handles this differently? Shows an error/warning or sometihng?

`nvim --version`

```
NVIM 0.0.0-alpha+201510160154 (compiled Oct 16 2015 17:50:16)
Commit: 3a970e57dfd48f090f8ccc21567b7974e13d4c68
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151016-52297-1k23qbd/build/config -I/tmp/neovim20151016-52297-1k23qbd/src -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/tmp/neovim20151016-52297-1k23qbd/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20151016-52297-1k23qbd/build/src/nvim/auto -I/tmp/neovim20151016-52297-1k23qbd/build/include
Compiled by chakrit@LZ77.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by ZyX-I** [comment]
Can you report this to Vim? I personally think that it makes sense to forbid yanking there with an error.

And not that what pasted is *not* garbage. I have repeated your steps and it pasted `ve"yx` which is exactly what you asked Vim to place there (it is your macros). Garbage would be the mix of yanked and recorded content.

**Comment by chakrit** [comment]
@ZyX-I thanks, I've corrected the title and reported https://github.com/vim/vim/issues/470

**Comment by chakrit** [comment]
So seems the VIM guys don't think this is worth adding : /

**Comment by chakrit** [comment]
@ZyX-I this was fixed in VIM by showing the current macro register https://github.com/vim/vim/commit/a0ed84a26897c994512873a895b9fc54e90c6845

**Comment by justinmk** [comment]
> this was fixed in VIM by showing the current macro register

We merged that patch, so closing this.
