### ISSUE TITLE
Incorrect cursor position in terminal mode

### ISSUE THREAD

**Issue by mli-max** [neovim/neovim#3615]
If this is a duplicate issue, please close it.
I found a strange behavior of terminal.
I am in terminal normal mode and I'm on start of usual terminal input
![screen shot 2015-11-06 at 11 04 41 am](https://cloud.githubusercontent.com/assets/1058433/10993326/8fb3743e-8476-11e5-8186-a61124550a5a.png)
Then I press `i` and I expect to edit in same position but It moves to last of text.
![screen shot 2015-11-06 at 11 05 11 am](https://cloud.githubusercontent.com/assets/1058433/10993341/b2939146-8476-11e5-915d-5ddeaab271ec.png)

Second issue, I can't to remove incorrect symbol in normal mode. I need to move to insert mode.
![screen shot 2015-11-06 at 11 08 47 am](https://cloud.githubusercontent.com/assets/1058433/10993370/f5b6dafa-8476-11e5-8032-080b445283cc.png)

I tried to `:set modifiable` and no result.

**Comment by mhinz** [comment]
This is expected behaviour.

Insert mode jumps to a certain cursor position that is given by the embedded program. You're not supposed to go to normal mode and delete stuff. You only go back to normal mode to switch to other buffers etc.
