### ISSUE TITLE
Building neovim von RHEL5 msgpack dependency fails

### ISSUE THREAD

**Issue by jredies** [neovim/neovim#3617]
I trying to compile neovim without root-rights, on RHEL 5 through a proxyscript.

I compiled cmake with SSL support but

`withproxy make` yields this

```
...
make[3]: Entering directory `/users/is/jredies/.tarballs/neovim/.deps'
[ 83%] Performing configure step for 'msgpack'
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
CMake Error at CMakeLists.txt:194 (ADD_LIBRARY):
  Cannot find source file:

    src/gcc_atomic.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: msgpack
CMake Error: Cannot determine link language for target "msgpack".
CMake Error: Cannot determine link language for target "msgpack-static".
CMake Error: CMake can not determine linker language for target: msgpack-static
-- Generating done
-- Build files have been written to: /users/is/jredies/.tarballs/neovim/.deps/build/src/msgpack-build
make[3]: *** [build/src/msgpack-stamp/msgpack-configure] Error 1
make[3]: Leaving directory `/users/is/jredies/.tarballs/neovim/.deps'
make[2]: *** [CMakeFiles/msgpack.dir/all] Error 2
make[1]: Leaving directory `/users/is/jredies/.tarballs/neovim/.deps'
make: *** [deps] Error 2
```

**Comment by jszakmeister** [comment]
This sounds like msgpack failed to download correctly.  Maybe taking a look at `.deps/build/downloads/cpp-1.0.0.tar.gz` will give you some clues.

**Comment by jredies** [comment]
``neovim/.deps/build/downloads/msgpack/cpp-1.0.0.tar.gz``

is there and unpacks nicely into ``msgpack-c-cpp-1.0.0``

Awesome reaction time, thanks!

**Comment by jszakmeister** [comment]
Hmm... This looks like a bug in msgpack's build.  It haz this in the CMakeLists.txt:

```cmake
IF (MSGPACK_ENABLE_GCC_CXX_ATOMIC)
    LIST (APPEND msgpack_SOURCES
        src/gcc_atomic.cpp
    )
ENDIF ()
```

That source file doesn't exist, though `gcc_atomic.hpp` does, and it appears to be undetected.  What version of CMake are you using?

**Comment by jredies** [comment]
``cmake 3.3.1``

build with

```
./bootstrap --system-curl
./configure --prefix=~/.builds/
make
make install
```

**Comment by jredies** [comment]
What do I do? Report the bug with msgpack? Can I fix it myself?

**Comment by jszakmeister** [comment]
I'd talk to the msgpack guys and see what they have to say.  The may know something more (you need version X of Y or better, and you have something different).

**Comment by hoopoepg** [comment]
as workaround for this issue:
put file gcc_atomic.cpp (from https://github.com/berkus/msgpack/blob/master/src/gcc_atomic.cpp) to same directory where gcc_atomic.hpp located & restart build
