### ISSUE TITLE
css.vim out of date

### ISSUE THREAD

**Issue by lkraav** [neovim/neovim#3625]
This at least partially breaks https://github.com/neovim/neovim/blob/master/runtime/syntax/less.vim which needs an updated version of https://github.com/neovim/neovim/blob/master/runtime/syntax/css.vim.

Gotta sync up to https://github.com/vim/vim/blob/master/runtime/syntax/css.vim

**Comment by mhinz** [comment]
Will be patched by: #3628

**Comment by justinmk** [comment]
@mhinz  css.vim is not in #3628

**Comment by mhinz** [comment]
Oops. I didn't base the branch on master, thus the patch skipped the already updated `syntax/css.vim`.

Fixed by https://github.com/neovim/neovim/commit/69360615803625e8fce7eea0318331678c07d3c8
