### ISSUE TITLE
Autosourcing init.vim doesn't work if saving into a symlink

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#3633]
I have `~/.nvimrc` symlinked to `~/.config/nvim/init.vim`

So I'm editing `~/.nvimrc`. Saving works, but autosourcing config doesn't. I need to use `:so %` to check my changes.

I have this inside `.nvimrc (init.vim`):
```
augroup AutoCommands
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END
```

**Comment by fwalch** [comment]
I think this is not related to `:source` or vimrc handling, but just how autocommands works for any symlink. For example:

```bash
touch a
ln -s a b
# Echoes 'Written to file'
nvim -c "autocmd BufWritePost $(pwd)/a echo 'Written to file'" -c ':w! a'
# Doesn't echo
nvim -c "autocmd BufWritePost $(pwd)/a echo 'Written to file'" -c ':w! b'
```

Replacing `nvim` with `vim` gives the same behavior.

So, in conclusion, I think you'd just need to use `:e $MYVIMRC` for your autocmd to work.

**Comment by ZyX-I** [comment]
@mtglsk `$MYVIMRC` is `…/init.vim`. But you are editing `~/.nvimrc`. How this could possibly work?

**Comment by justinmk** [comment]
> I have ~/.nvimrc symlinked to ~/.config/nvim/init.vim

Try it the other way round.

**Comment by justinmk** [comment]
If you want N/Vim to follow the symlink, you can use `resolve(expand('~/.nvimrc'))` to get the resolved path.
