### ISSUE TITLE
`expand_env_esc` not reliable

### ISSUE THREAD

**Issue by 5paceToast** [neovim/neovim#3634]
See #3562 : on initial testing with using wordexp.h in place of the existing algorithm, expanding completed successfully, but not with the current implementation.

A more robust / reliable method of expanding environment variables is thus needed.

Some initial porting/testing has been done in [my fork](https://github.com/5paceToast/neovim/tree/expand-env-patch), however, through research on how `wordexp(3)` is typically implemented, it's become obvious that this solution is not ideal (e.g the Apple libc delegating it to perl !). Moreover, `wordexp(3)` does not support the current flexible choices that `expand_env_esc` provides: `esc`, `one` and `startstr`. Because of this, `wordexp(3)` implementations fail 4 functional tests. Moreover, OpenBSD does not have a `wordexp(3)` implementation (despite it being standard).

Ideally, a decision on how to increase reliability of the function, adhere to standards, as well as typical usage needs to be done. (e.g _why_ do we need `esc`, `one` and `startstr`? is it to accomodate the current implementation details?)

My current idea is to check against `esc`, `one`, `startstr` and `HAVE_WORDEXP_H`, and if the implementation allows to use `wordexp(3)`, use it, otherwise delegate to the current algorithm. This approach however won't do much but increase complexity of the code for many paths, still cause the breakage for the log files on OpenBSD and is not a long term solution.

**Comment by justinmk** [comment]
#3562 was merged. Nothing actionable here. Need a test case, at least. PR would be great as well.
