### ISSUE TITLE
`:pwd` is not always the same as `python os.getcwd()`

### ISSUE THREAD

**Issue by dan-santana** [neovim/neovim#3636]
To reproduce it, run the following:

```
:python import os
:pwd
:python print os.getcwd()

:cd SOME_DIRECTORY
:pwd
:python print os.getcwd()
```

In Vim, `:pwd` will always be the same as `os.getcwd`, while in Neovim the python command will print the directory where you initially imported the `os` module, and not change after you `:cd` elsewhere.

**Comment by justinmk** [comment]
See also https://github.com/alexgenco/neovim-ruby/pull/22

**Comment by Yggdroot** [comment]
This issue still exists in the latest source NVIM v0.2.1-826-g7bfa440.

**Comment by justinmk** [comment]
No one sent a patch to python-client.

**Comment by Leandros** [comment]
This bugs annoys the hell out of me. Tell me how I can change the `NVIM_LISTEN_ADDRESS` on Windows (it's not picking up env vars in cmd.exe, and nvim refuses to start in bash) and I'll try to fix it.

**Comment by justinmk** [comment]
serverstart() can listen on any (non-existing) address, see `:help serverstart()` for examples.

`nvim.exe` in cmd.exe should work (though it looks ugly), how did you set the env var?

**Comment by Leandros** [comment]
```
$ set NVIM_LISTEN_ADDRESS=nvim-socket
$ nvim
```

The help on `serverstart` is very helpful, though. I got it working by going over a TCP socket.
