### ISSUE TITLE
Vertical split from vimrc doesn't work

### ISSUE THREAD

**Issue by Faerbit** [neovim/neovim#3638]
I have the following lines in my vimrc:
```viml
if argc() == 2
     silent vertical all
endif
```
If I open vim like this: `vim file1 file2` it shows the two files in a vertical split. In vim the files are equally wide displayed. 
In Neovim sadly this isn't the case. Neovim opens them up next to each other but the left file has much less space than the right one.
What confuses me most is that opening them up, one after another(`vim file1` and then `:vsp file2`) works properly.

I am running the following Neovim version:
```
NVIM v0.1.0-28-g94015cd (compiled Nov  9 2015 22:25:59)
Commit: 94015cd13a7d17787042bd003950fc152fa129bb
```
I am running Archlinux 64-bit.

Is there any additional info I could provide?

**Comment by fwalch** [comment]
During startup, the UI is not yet attached, and thus Neovim doesn't know how wide the window is when `:vertical all` is executed. As a workaround, you can do:

```viml
if argc() == 2
  autocmd! VimEnter * silent vertical all
endif
```

**Comment by casimir** [comment]
Talking about workaround I do the same with an alias in my shell's rc `alias nvim='nvim -O'`.

**Comment by justinmk** [comment]
As @fwalch said. Though `autocmd!` with bang will delete other VimEnter handlers.

**Comment by Faerbit** [comment]
While this did fix my original problem this new autocmd now leads to syntax highlighting missing in the second(right) file. This also happens in vim.

**Comment by fwalch** [comment]
Via [StackOverflow](http://stackoverflow.com/a/10525050/249642):

```viml
if argc() == 2
  autocmd VimEnter * nested silent vertical all
endif
```

**Comment by Faerbit** [comment]
Thanks, that fixed it. Thank you for your patience.
