### ISSUE TITLE
Slow insert leave in st terminal

### ISSUE THREAD

**Issue by LK4D4** [neovim/neovim#3639]
Hi, I'm using st(http://st.suckless.org/) with neovim and have pretty bad bug. When I'm trying to leave insert mode and do something it fails, writing some weird symbols and doesn't leave. However if I'm doing it slowly, like `ESC`, then wait, then `j` - it works. It also doesn't work for leaving other modes as well(like visual). I don't see such behavior in `xterm`. I reproduced with 1.0.1 and master versions of neovim.
Thanks!

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/2093

**Comment by LK4D4** [comment]
@justinmk thanks! it is indeed only in tmux, but `set -g escape-time 20` workaround doesn't work for me. Also #2093 is close, should I use it for reporting?

**Comment by wlhlm** [comment]
Does `escape-time 0` work?

**Comment by LK4D4** [comment]
@wlhlm yup, works!
