### ISSUE TITLE
Wrong backupdir default value

### ISSUE THREAD

**Issue by sanpii** [neovim/neovim#3642]
> 'backupdir' 'bdir'      string  (default ".,$XDG_DATA_HOME/nvim/backup")

`.` always exists. Values should not they be inverted?

**Comment by ZyX-I** [comment]
No.

1. `&backupdir` is used also for things like `&writebackup` and it is much faster with `.`.
2. There is no functionality equivalent for `&directory='…//'`. So there is a very high chance of the name conflicts for backup file.

I was not going to remove dot from there until fixing 2 if this will ever be fixed. Also note Vim default:

```
'backupdir' 'bdir'	string	(default for Amiga: ".,t:",
				 for MS-DOS and Win32: ".,$TEMP,c:/tmp,c:/temp"
				 for Unix: ".,~/tmp,~/")
```

: leading dot as well.

**Comment by sanpii** [comment]
Ok, thank you.
