### ISSUE TITLE
Unable to use `<s-cr>` as a mapping

### ISSUE THREAD

**Issue by kurkale6ka** [neovim/neovim#3645]
Hi,

This mapping (`imap <s-cr> <esc>O`) doesn't work because both nvim and xterm think `<s-cr>` is `^M`.

tested with `NVIM v0.1.0-36-g68255df`

**Comment by mhinz** [comment]
Does your terminal emulator distinguish between that? Try in `cat -v`: `<c-v><s-cr>`.

If not, there's nothing Neovim can do about it.

**Comment by kurkale6ka** [comment]
Sorry. As I stated myself, xterm doesn't send that correctly and that is the issue.

On the other hand I have this other mapping `imap <c-cr> <esc>o` which works in pangoterm. Now, pangoterm sends `^[[13;5u` but `^v` in nvim shows `^M`. Not sure why it works then...

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/2886
