### ISSUE TITLE
VimSuspend, VimResume autocmds

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#3648]
I think it would be useful to have autocommand events for suspending and resuming Neovim (`Ctrl-Z`, but might be remapped).

This would be useful to indicate to tmux / https://github.com/christoomey/vim-tmux-navigator that the current pane is not controlled by Vim anymore (and restore it).
Ref: https://github.com/christoomey/vim-tmux-navigator/pull/37.

**Comment by mhinz** [comment]
I'm not sure how many use cases there are for it, but then again it should only take a few lines to add these autocmds.

Opinions?

**Comment by justinmk** [comment]
What about rasiing FocusGained/FocusLost for resume/suspend?

**Comment by ZyX-I** [comment]
@justinmk This is logical, but it needs a way to distinguish between “suspend” and “A-Tab” cases since there are different consequences: e.g. with “A-Tab” plugin may start doing some hard job even in a blocking fashion because it knows it has time. With “suspend” it cannot do anything blocking.

**Comment by justinmk** [comment]
Ok. I suggest names like VimSuspend/VimResume, for parallel form with VimEnter/VimLeave. All of these states are nearly literal equivalents to OS scheduler states.

**Comment by mhinz** [comment]
:+1:

**Comment by tarruda** [comment]
@mhinz better wait until I finish my next PR before working on this. As I said before, I plan to add a lot of flexibility to the TUI, so the kind of hook requested by @blueyed will be simple to add.

**Comment by mhinz** [comment]
Roger that.

**Comment by jeromedalbert** [comment]
> I'm not sure how many use cases there are for it

I like `Ctrl-Z`ing, `git checkout`ing another branch (or do some other file modification), and `fg`ing back to vim.

Just like when I `checktime` on `FocusGained` and `BufEnter`, it would be nice if there was an autocommand for suspending/resuming. Or hook suspending/resuming to `FocusGained` and `BufEnter`. Even better would be to have the `autoread` option automatically do all of this.

Anyways, any news on this?

**Comment by tomprince** [comment]
When using neomake cargo maker, suspending while a maker is running causes cargo to be unusable outside of vim, since cargo uses a lock to serialize work. It would be nice to be able to kill or otherwise interrupt the process when suspending.

**Comment by blueyed** [comment]
@tomprince 
You could use a custom mapping like above, which then cancels all cargo jobs.
Please create an issue for Neomake, and we can discuss it from there.

**Comment by justinmk** [comment]
Adding this autocmd should be easy, if anyone wants to send a PR.

**Comment by zackhsi** [comment]
@jeromedalbert thank you for the snippet, works like a charm :)

One improvement to fix the silent command is to move the bang:

```diff
-noremap <c-z> :suspend<cr>:silent! checktime<cr>
+noremap <c-z> :suspend<cr>:silent !checktime<cr>
```

**Comment by blueyed** [comment]
Posted at vim_dev about it: https://groups.google.com/d/msg/vim_dev/Gb3D0LCaJrI/Rscj4O9CAgAJ

**Comment by felipesere** [comment]
Brief question: how would I check if the current vim instance has support for VimSuspend and VimResume?

**Comment by justinmk** [comment]
@felipesere See `:help exists()`. 

    :echo exists('##VimSuspend')

(Note the double `##`.)

For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.
