### ISSUE TITLE
Segmentation fault after :PlugUpdate<cr> finishes

### ISSUE THREAD

**Issue by khalidchawtany** [neovim/neovim#3658]
I am using the latest version of vim and I almost always get a segmentation fault after ```:PlugUpdate<cr>``` ends.

```
NVIM v0.1.0-39-g3b61598 (compiled Nov 10 2015 23:17:13)
Commit: 3b615980c814eff3fa284dd07b61fbf50885f4ab
Build type: Dev
... 
```
Here is the [link](https://gist.github.com/khalidchawtany/32f78457f011de545526) to the segmentation fault stack trace.

**Update:**
---
```
NVIM v0.1.0-44-g632408a (compiled Nov 11 2015 22:09:30)
Commit: 632408af4a3baa987cc13005675bba63675825cb
Build type: Debug
...
```
[Backtrace](https://gist.github.com/khalidchawtany/4c3646d7e02d24ac2506) of debug build.

**Comment by rainerborene** [comment]
`plug.vim` works fine here. show me your plugin list.

**Comment by khalidchawtany** [comment]
@rainerborene I have a huge list of plug-ins and **NO plugin should be able to cause a segfault**, that is why I am reporting it here :)

Yet let me elaborate a little more ...
If I remove ``` Plug 'thinca/vim-ambicmd' ```, the segfault does not happen. However, this plugin alone does not cause a segfault.

I think segfault is related to the amount of time the update process takes and the time it waits for user input after the it finishes. (I think, this is the reason that, just having ``` Plug 'thinca/vim-ambicmd' ``` does not cause a segfault ) .

About two weeks ago the segfault used to happen if I did not press any key after the process finished for about 5 seconds. Currently it happens after every update.

**Comment by khalidchawtany** [comment]
I just updated **Neovim**, then did an update of my plugins twice and no segfault happened.
I will close this for now, if it happens again, I will reopen it. I hope it is gone for good :)
