### ISSUE TITLE
How to open file in terminal with exists nvim.

### ISSUE THREAD

**Issue by DogLooksGood** [neovim/neovim#3665]
I really like the terminal mode, but I found open file in terminal is inconvenient in terminal mode. I have to use the :e {file path} .

**Comment by justinmk** [comment]
You can do so with a remote script such as this:

https://gist.github.com/tarruda/37f7a3e22996addf8921

Though eventually this will not be dependent on python: https://github.com/neovim/neovim/issues/3119
