### ISSUE TITLE
Rightclick is overriden and does not show terminal context menu

### ISSUE THREAD

**Issue by nagisa** [neovim/neovim#3669]
Neovim’s TUI overrides right-click behaviour and does not allow terminal emulator to show a sometimes useful context menu anymore. 

I sometimes use context menu to open links from terminal (there’s a context menu item for that), but I can’t do that anymore from neovim.

**Comment by wlhlm** [comment]
Cannot reproduce in iTerm with current HEAD. What version are you using? (`nvim --version`)

Does it still happen with `nvim -u NONE`? If not, what is your configuration?

What terminal emulator are you using? Does it work in other terminal emulators?

**Comment by fmoralesc** [comment]
@nagisa Use `set mouse=` to disable this.

**Comment by nagisa** [comment]
Is there a way to only disable special handling for right-click but not middle/left click?

**Comment by bendem** [comment]
Depending on your terminal, you should be able to <kbd>shift</kbd> right click to get your context menu (<kbd>shift</kbd> temporarily disables application overrides to your mouse in most terminals).

**Comment by harshavardhannarla** [comment]
In macos CMD+rightclick is giving nvim rightclick menu , simple rightclick is giving iterm2 rightclick menu

Is there anyway to 
simple rightclick -   nvim rightclick menu

Please help

**Comment by jrmajor** [comment]
@harshavardhannarla In Settings > Pointer > Bindings, there should be “Open Context Menu” item. Change it to something else (e.g. add “⌘” modifier). Now ⌘ + Right Click will open iTerm's context menu, and right click without modifiers will invoke Neovim menu.
