### ISSUE TITLE
listchars highlighted incorrectly with :set cursorline

### ISSUE THREAD

**Issue by lucy** [neovim/neovim#3670]
To reproduce, `:set list cursorline` and type some spaces on different lines.

The current line uses the ctermfg from Normal while others use SpecialKey.
I would expect the selected line to use SpecialKey as well.

**Comment by justinmk** [comment]
This has always irked me. Vim has the same behavior, not sure whether it's considered a bug, but looping in @chrisbra, this is addressed by https://github.com/neovim/neovim/pull/4744.
