### ISSUE TITLE
[Tutor] Set settings so you can read the tutor

### ISSUE THREAD

**Issue by write-your-own-os** [neovim/neovim#3674]
The `tutor` is for (neo)vim beginners, and you shouldn't need to edit the config BEFORE you have read the tutorial for editing the config file. Now it's little of a catch 22 situation.

I suggest that then running `:Tutor`, Neovim automatically set following settings so the reader can use the tutorial fully.

```vimscript
filetype plugin detect on
syntax on
```

I feel this is discussion that doesn't concern #2676.

**Comment by fmoralesc** [comment]
This will get fixed once vim-tutor-mode is updated in the neovim runtime.
