### ISSUE TITLE
Tests fail for Linux on master.

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#3676]
The oldfiles spec tests have ordering issues:

```text
test/functional/ex_cmds/oldfiles_spec.lua @ 34
Failure message: ./test/functional/ui/screen.lua:278: Row 2 didn't match.
Expected: "1: /home/quickbuild/buildagent/workspace/root/neovim/master/testfile1                               "
Actual:   "1: /home/quickbuild/buildagent/workspace/root/neovim/master/testfile2                               "
stack traceback:
./test/functional/ui/screen.lua:278: in function 'wait'
./test/functional/ui/screen.lua:221: in function 'expect'
test/functional/ex_cmds/oldfiles_spec.lua:44: in function <test/functional/ex_cmds/oldfiles_spec.lua:34>
```

and

```text
test/functional/ex_cmds/oldfiles_spec.lua @ 72
Failure message: test/functional/ex_cmds/oldfiles_spec.lua:74: Expected objects to be the same.
Passed in:
(string) '/home/quickbuild/buildagent/workspace/root/neovim/master/testfile1'
Expected:
(string) '/home/quickbuild/buildagent/workspace/root/neovim/master/testfile2'
stack traceback:
test/functional/ex_cmds/oldfiles_spec.lua:74: in function <test/functional/ex_cmds/oldfiles_spec.lua:72>
```

The issue was brought up in #3647, but still exists.  At heart here are tests assuming that oldfiles will maintain order, but Zyx-I contends that the order is actually more interesting than that.

So I think these tests are broken as-is.  I'm not sure what we want to do here.  We could change the tests to expect either ordering, or we need to find a way to get the ordering we want.  Would putting a `wshada` in between the edits get what we want?

You can see the failed report output [here](http://neovim-qb.szakmeister.net/build/3650/tap_report/failed_tests?reportset=functionaltest-linux-64-debug).

**Comment by mhinz** [comment]
Okay, I look into it. But expect it to take some time.

Is there a good way to skip a test temporarily? (Other than commenting out.)

**Comment by mhinz** [comment]
:+1:
