### ISSUE TITLE
mouse release is broken (in TUI)

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#3677]
Neovim doesn't seem to generate mouse release events, at least in the TUI. (tested `xterm` and `urxvt`) The following works in vim

    :map <LeftRelease> :echo "test"<cr>

but not in nvim. Also selecting a window by clicking (without dragging) the statusline works in vim but not in nvim (as detecting click-without-drag relies on release event) . I would need this to implement `autoselect` #2325 efficiently.

I tried to navigate the input handling code, but I don't know where to look beyond

    #define K_LEFTRELEASE   TERMCAP2KEY(KS_EXTRA, KE_LEFTRELEASE)

**Comment by HarmtH** [comment]
Duplicate of #3182

**Comment by bfredl** [comment]
Thanks!
