### ISSUE TITLE
cannot assign output of rpcstart to variable in VimL

### ISSUE THREAD

**Issue by stephenprater** [neovim/neovim#3679]
I'm working on creating a legacy ruby provider similar to the legacy python provider - and have run into a problem.  Feels like I'm missing something obvious, but I can't for the life of me figure out what it would be.

Basically, I cannot access the return value of `rpcstart` assigned to a variable in VimL.

This works fine:

```
:echo rpcstart(s:remote_host_path, [s:plugin_path])
```

I can then `rpcrequest(<whatever>, 'msg')` to that channel at will.

However, assigning that channel id to variable locks Neovim when I attempt to access the variable.

```
let s:some_variable = rpcstart(s:remote_host_path, [s:plugin_path])
echo 'some message'
echo s:some_variable  " << freezes here without output
```

Killing the remote client excutes the rest of the script, but the channel is closed now.

What am I missing here?

**Comment by justinmk** [comment]
Try it with a local variable

**Comment by stephenprater** [comment]
Tried with a local with the same effect.  The variable thing actually is a red herring I think.

```
let l:host = rpcstart(s:remote_host_path, [s:plugin_path])
sleep 500m
if rpcrequest(l:host, 'poll') == 'ok'
    return l:host
endif
```

This actually works - so it's probably a threading issue.  I'm not sure if it's Neovim or the Ruby plugin. Although - given that the code works for the Python provider I'm willing to bet it's in the Ruby bit - I'll move this issue there.
