### ISSUE TITLE
:terminal cursor doesn't match $TERM cursor

### ISSUE THREAD

**Issue by qstrahl** [neovim/neovim#3681]
It looks like NeoVim is manually drawing the cursor in `:terminal` windows, rather than letting the external terminal (in my case, urxvt) draw the cursor. This results in some irksome inconsistency in how my cursor looks in `:terminal` windows vs. how it looks everywhere else, including other buffers in NeoVim. Specifically, I have my terminal cursor set to blink. Everywhere else in NeoVim, my cursor blinks, but in `:terminal` windows, it doesn't.

NeoVim really ought to be letting the external terminal draw the cursor.

**Comment by SageEx** [comment]
Might be realated to #2326
I also have my zsh config in vi mode - means bar cursor in normal mode and pipe cursor in insert mode.
But in `:terminal` windows it doesn't work.
Would be nice to have this feature.

**Comment by qstrahl** [comment]
The problem is this; from @tarruda in #2326:

> libvterm supports cursor shape customization, but `:terminal` uses a virtual cursor which is simply a set of highlight attributes applied to a cell

I'm not sure why it uses a virtual cursor rather than the real terminal cursor... seems to me using the real terminal cursor would be much preferable. Hopefully someone can shed some light on this.

**Comment by tarruda** [comment]
> I'm not sure why it uses a virtual cursor rather than the real terminal cursor... seems to me using the real terminal cursor would be much preferable. Hopefully someone can shed some light on this.

The main reason I followed this approach is because I didn't want to change the UI protocol just to be able to change cursor color from any UI. Using a virtual cursor means :teminal cursor coloring already work from other UIs. This may change later as the UI protocol is refactored.

**Comment by qstrahl** [comment]
> The main reason I followed this approach is because I didn't want to change the UI protocol just to be able to change cursor color from any UI. Using a virtual cursor means :teminal cursor coloring already work from other UIs.

I can understand the desire to be able to change the color/etc of the cursor, but terminals already  support this with escape sequences, without having to bake it in ourselves. Why reimplement what already exists, or am I missing something?

My feeling is that I've already configured my terminal to render the cursor the way I want it to, and NeoVim respects this everywhere except for this one place, for reasons unclear to the end user. With the way it works right now, it's quite literally impossible for me to have a consistent cursor in NeoVim, which is admittedly a triviality, but nonetheless a frustrating one.

**Comment by azag0** [comment]
I just hit this issue since highlighting of matching brackets in neovim running in :terminal (I know...) breaks in my colorscheme because of this. The bracket with the cursor on it becomes darker than the matching one which is rather confusing.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/5556

**Comment by plexigras** [comment]
+1

**Comment by BeaudanBrown** [comment]
I see that this has been referenced as recent as october
I'm wanting the same functionality as SageEx above, very frustrating when I switch to a terminal buffer and start typing only to realise the terminal is in normal mode
Is there anyone still looking into this or have I missed a workaround that will allow this?

I tried a few of the suggestions floating around like `set guicursor=` but with no success

**Comment by maxpiano** [comment]
i have the same problem. i use vi mode in all terminal apps via inputrc, where i have "show-mode-in-prompt" activated, so that my cursor changes from block in normal mode to pipe in insert mode. in nvim the cursor is always a block in terminal mode, preventing me from visually distinguishing between the modes.

**Comment by acdifran** [comment]
I'm running into something similar. When opening a terminal inside nvim the cursor looks fine for normal and replacement mode, but for insert mode it is always a white block no matter what values I set. Is this expected?

**Comment by savchenko** [comment]
> Is this expected?

As far as I understand - yes, please read the whole thread above.

**Comment by BIKA-C** [comment]
Me: Hell yeah, 5 years ago, should be fixed by now
Please! At least a solution? It bugs me a lot.
Never mind, no solution yet.

**Comment by astier** [comment]
@BIKA-C its assigned for the 0.6 milestone. You probably will have to wait a couple years more.

**Comment by solidiquis** [comment]
2022... no end in sight? :/

**Comment by rodhash** [comment]
+1 annoyed by cursor shape in terminal mode, running `v0.8.0-dev+359`

**Comment by kuang22** [comment]
God help me. The solid block in terminal mode realllllly bothers me!

**Comment by etlhsu** [comment]
Looking forward to seeing this feature implemented since even Vim's embedded terminal already has this properly handled...

**Comment by zaiqiang-dong** [comment]
Very much looking forward to it can be resolved as soon as possible
