### ISSUE TITLE
Text munging/double characters in shell output

### ISSUE THREAD

**Issue by alcesleo** [neovim/neovim#3682]
Hey! I find this issue difficult to describe, I hope it is not a double post but I didn't find any other issues for the search terms I could think of - it's easier to show it with pictures:

Here is the output of running `:!man ls`:

![screen shot 2015-11-16 at 20 18 56](https://cloud.githubusercontent.com/assets/2709244/11192154/b035dc34-8c9f-11e5-979f-26883ce43949.png)

Doing the same in Vim:
![screen shot 2015-11-16 at 20 19 27](https://cloud.githubusercontent.com/assets/2709244/11192158/b4f6cfc6-8c9f-11e5-8e23-6aa15dfeec9e.png)

As you can see it's not handling the bold text correctly and doubles characters in groups of 2.

I just updated to the latest neovim, and ran it with `nvim -u NONE` on Mac OSX El Capitan.

Here is the output of `nvim --version`:

```
NVIM 0.1.0-dev (compiled Nov 16 2015 19:27:42)
Commit: ed06071f1f61f625c3fef46e24b57d563852e4c9
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151116-3142-dlfs0v/build/config -I/tmp/neovim20151116-3142-dlfs0v/src -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/tmp/neovim20151116-3142-dlfs0v/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20151116-3142-dlfs0v/build/src/nvim/auto -I/tmp/neovim20151116-3142-dlfs0v/build/include
Compiled by alcesleo@Jimmys-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

The same issue happens in all cases where shell output tries to display these intense/bold type fonts, I initially found it while using ri. I do not believe this was a recent regression, I remember having these problems for a while but I thought something was wrong in `vim-ruby` or someplace else, I just recently realised it happens with all commands and that it didn't do this in vim. Any idea what might be causing this?

Thank you for your great work, I use neovim 8 hours per day and love it! Let me know if I can provide any more details to help find the problem

Cheers

**Comment by justinmk** [comment]
> The same issue happens in all cases where shell output tries to display these intense/bold type fonts,

Yeah this is because `:!` uses pipes in Neovim, and the recommended workaround is `:term`. See also Vim's own `:help gui-pty`.

Covered by https://github.com/neovim/neovim/issues/1496

**Comment by alcesleo** [comment]
Great, thank you!
