### ISSUE TITLE
Add a .desktop file in contrib/

### ISSUE THREAD

**Issue by teto** [neovim/neovim#3689]
This way, one can launch neovim from xdg menu launchers.
Here is a quick working prototype (took ranger.desktop and changed Exec line, would need to update other fields as well):
https://raw.githubusercontent.com/teto/home/771f11346c8a8ca9f6eaed6b65d40f81c7361b4e/local/share/applications/neovim.desktop
It can be installed with:
`xdg-desktop-menu install --novendor neovim.desktop` 

@fmoralesc has concerns that it is not enough in some launchers, for instance gnome's:

```
(fmoralesc) For example, in gnome, when alt-tabbing,
neovim will get grouped with any other terminal instances, and
it will be grouped the same in the taskbar or any dock. iirc
xfce and kde worked similarly.
GNOME's method is kinda complicated. It has
a bias for the DBus interface associated to the program
(linkved via the desktop file). The gnome-terminal wrapper
uses some tricks to do this. So as far as gnome is concerned, the wrapper
really *is* a different application.
```

IMO, a basic .desktop should be enough for most people, and to support gnome's launcher, people can use @fmoralesc gnome-terminal wrapper.

**Comment by justinmk** [comment]
If this were shipped to users, it would live somewhere in `runtime/...` not `contrib/`.

**Comment by teto** [comment]
Made a proposition here https://github.com/neovim/neovim/pull/6006
