### ISSUE TITLE
Colors look distorted in neovim terminal

### ISSUE THREAD

**Issue by mcordell** [neovim/neovim#3690]
Hi all,

I'm having a small issue when true color is enabled for neovim, the shell colors are distorted when running a terminal from within in neovim. Compare these two screenshots (I repeated the same commands more or less in the in app terminal):

**With True color enabled in neovim**:

![screen shot 2015-11-17 at 11 11 01 am](https://cloud.githubusercontent.com/assets/1691120/11222047/1c28249c-8d1d-11e5-9ed4-8025e468f936.png)

**With True color disabled**

![screen shot 2015-11-17 at 11 16 02 am](https://cloud.githubusercontent.com/assets/1691120/11222063/2946fe50-8d1d-11e5-8269-896fdc3ab286.png)

Also here is a "normal" terminal window:
![screen shot 2015-11-17 at 11 22 36 am](https://cloud.githubusercontent.com/assets/1691120/11222137/89503cd0-8d1d-11e5-80c9-69dd3919f05d.png)

Other specifics:
NVIM v0.1.0-77-ged06071 (compiled Nov 17 2015 10:03:29) installed via Homebrew
Running iTerm nightly (Build 2.9.20151023-nightly)
Zsh with zprezto running 'agnoster' theme
gruvbox theme for vim

Thanks for the help!

**Comment by timfeirg** [comment]
have you tried using the stable version of iterm? the screenshot below is taken with latest neovim and stable version of iterm2 (see the version and neovim commit in the screenshot), the colors in neovim terminal pane are exactly the same with a normal iterm2 terminal pane.


![timfeirg_timfeirg-mba____and_about_iterm](https://cloud.githubusercontent.com/assets/4319104/11244386/5c3e9878-8e48-11e5-8f8d-25d2bca6ce62.gif)

**Comment by mcordell** [comment]
Hi timfeirg,

I did try that just now but AFAICT current build (2.1.4) does not support true color. Testing in the terminal confirms this and then when true color is on with neovim it is actually worse:

![screen shot 2015-11-18 at 10 11 39 am](https://cloud.githubusercontent.com/assets/1691120/11249662/249b8c20-8ddd-11e5-90f9-062ef5177b88.png)

**Comment by timfeirg** [comment]
from [this post](https://chris.chowie.net/2015/04/19/True-colour-with-neovim-tmux-and-iterm2/), using the latest iterm2 nightly build & neovim 959f2601f982bb911c83cc6e948f06abd2e9c140 (start with `NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim`), it does look pretty bad

**Comment by DarkDefender** [comment]
I have the same problem with urxvt (with a true color patch) and st in linux. It seems like the colors in the nvim terminal are hard coded when in true color mode.

That's my guess anyways.

**Comment by justinmk** [comment]
Terminal does not work with true color yet, it's a known issue. https://github.com/neovim/neovim/issues/2571
