### ISSUE TITLE
Neovim Windows init.vim location

### ISSUE THREAD

**Issue by jrock2004** [neovim/neovim#3700]
Is the location of init.vim the same as it is on my mac and Linux?

```
$HOME/.config/nvim/
```

**Comment by timfeirg** [comment]
see `:h nvim-from-vim`, use soft link and don't worry about the locations of neovim config files

```shell
    mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
    ln -s ~/.vim $XDG_CONFIG_HOME/nvim
    ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim
```

better take this to [`gitter`](https://gitter.im/neovim/neovim) as this is not really a neovim issue

**Comment by mhinz** [comment]
@timfeirg Windows. :)

@jrock2004 https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L25-L27

**Comment by RedX2501** [comment]
The alternative paths for windows information should definitely go into nvim_from_vim.txt and `Following HEAD` wiki page.

**Comment by masaeedu** [comment]
@mhinz Is this configurable?

**Comment by fuzzybear3965** [comment]
I am also wondering whether or not this is configurable.

**Comment by justinmk** [comment]
`:help xdg`, `:help nvim-from-vim`

**Comment by fuzzybear3965** [comment]
@justinmk, I had read those docs, already, from which it seems that neovim has made the design choice to **not** allow for this to be configured. However, I thought my question might prompt a discussion as to whether or not including such a configuration option would be considered.

**Comment by justinmk** [comment]
Configure how? An environment variable? That would be the XDG bars, already supported.

**Comment by fuzzybear3965** [comment]
I don't know what you mean by "XDG bars", but yes, I mean configure through and environment variable. Yes, the XDG Base Directory Specification is used by `neovim` but the paths to these files are compiled into `neovim` per https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L25-L27. Thus, it appears these paths are not modifiable at runtime.

**Comment by justinmk** [comment]
MYVIMRC env var also is available. And, XDG vars are configurable. The code only applies if those vars are not defined.

**Comment by fuzzybear3965** [comment]
That's beautiful. You're right. The XDG variables are configurable. What about the source code indicates to me that the binary doesn't set those environment variables to those values at runtime but, instead, checks to see if they're defined first?

**Comment by justinmk** [comment]
Not sure what you are asking. If we did not respect defined env vars there would be no purpose to having XDG support.

**Comment by fuzzybear3965** [comment]
I was of the understanding that XDG support meant that certain directory conventions were adopted. I didn't understand that to mean that certain environmental variables are supported. So, my question was: What about the source code that I/@mhinz referenced makes it clear that environment variables can supercede the values of `%LOCALAPPDATA`?

**Comment by justinmk** [comment]
You could just try it.

**Comment by fuzzybear3965** [comment]
That's what I had done in order to confirm that you were right (3 hours ago). I just wanted to know if the fact that the XDG environment variables are evaluated at run-time is made clear in the source code I referenced (i.e. that I should have already known, without testing, that these environment variables would have been checked at run-time)

**Comment by justinmk** [comment]
The code that you linked is used as fallback if the variables don't exist. It is not used if the variables do exist.

**Comment by fuzzybear3965** [comment]
Ah, I [see where that is, now](https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L63). Thank you.

**Comment by nadya-p** [comment]
This is indeed beautiful. Just to sum up, for a Windows user running
`setx /M XDG_CONFIG_HOME "%USERPROFILE%\\.config"`
in an elevated command prompt will bring the neovim config file at the same location relative to the user directory as on Linux.

**Comment by rmolin88** [comment]
According to [this](https://stackoverflow.com/questions/16276139/what-is-the-difference-between-programdata-and-appdata) article `kXDGConfigHome` should be ` "~\\AppData\\Roaming"` for Window OS

**Comment by justinmk** [comment]
@rmolin88 It's not that simple. "roaming" feature may not be available, then it may later appear out of nowhere. That's confusing for users.

None of this is written in stone, MSDN does not address XDG base dir spec. We considered existing implementations and I think the final decision is quite good.

see also https://github.com/neovim/neovim/pull/3470#issuecomment-148945502

**Comment by rmolin88** [comment]
I didn't know that roaming want always present. That makes complicated indeed. Thanks for the reply.

**Comment by bonniesimon** [comment]
> 
> 
> @timfeirg Windows. :)
> 
> @jrock2004 https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L25-L27
> 
> ➡️ `~/AppData/Local/nvim/init.vim`)

This is not the case with WSL2. 
Does anyone have any idea where my nvim init file is in WSL?
I wanna install some plugins!!

**Comment by kramar42** [comment]
@bonniesimon 
It's `~/.config/nvim`. I found that from vim's help at `:h nvim`.

**Comment by cetanu** [comment]
None of the above paths seem to be picked up by neovim for me...

**Comment by itschip** [comment]
I've added a 'init.vim' file in my 'AppData/Local/nvim' but still nothing :(
