### ISSUE TITLE
mac os x copy terminal (does work) vs iterm2 (does not work)

### ISSUE THREAD

**Issue by ephes** [neovim/neovim#3702]
Hi *,

I stumbled across this project a few days ago and really like the idea (I would love to have a modern vim replacement).

On mac os x I noticed that copy does work when I run nvim in the terminal, but not in iterm2. How could I debug this further?

```
nvim --version

NVIM 0.1.0-dev (compiled Nov 16 2015 18:11:34)
Commit: ed06071f1f61f625c3fef46e24b57d563852e4c9
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151116-83520-6ornt0/build/config -I/tmp/neovim20151116-83520-6ornt0/src -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/tmp/neovim20151116-83520-6ornt0/deps-build/usr/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20151116-83520-6ornt0/build/src/nvim/auto -I/tmp/neovim20151116-83520-6ornt0/build/include
Compiled by jochen@Jochens-MacBook-Pro-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by mhinz** [comment]
Hi,

when you say say "copy", you mean yanking something with `y` and then pasting it outside the terminal emulator, e.g. your browser?

If that's the case, have a look at `:h nvim-clipboard` and `:h clipboard-unnamedplus`. (Although I wouldn't know why it would work any different in Terminal.app.)

**Comment by nicolaiskogheim** [comment]
I cannot copy at all from iTerm2. It has been like this for the last couple of commits on HEAD.

By copy, I mean both CMD+C and `"*yy` for instance. It's as if iTerm2 has it's own clipboard now (you'll understand when you read the list below).

This is what happens:

1. Copy text "text from browser" in your internet browser (or any other app for that matter).
2. Paste in iTerm2. Does not paste "text from browser"
3. Copy text "text form iterm" from iTerm2.
4. Paste in iTerm2. Works as expected.
5. Paste in browser. Still pastes "text from browser", not "text from iterm" as expected.
6. Copy "whatever" from browser.
7. Paste in iTerm. Pastes "text from iterm", not "whatever" as expected.


I would conclude with that this issue has nothing to do with neither Vim, nor Neovim.

**Comment by nicolaiskogheim** [comment]
@hansrodtang just enlightened me on what is going on here. This is actually a feature of iTerm2.
Go to *Settings*->*General*, and enable `Applications in terminal may access clipboard`.

When I enabled that option, I could copy from and paste to iTerm2 as one would expect.
There is still something strange here, though. @hansrodtang gets expected behaviour with the option off.

Anyway, hope this helps, @ephes. :)

**Comment by mhinz** [comment]
OSX always comes with two small helper programs that handle the OS clipboard; `pbcopy` and `pbpaste`. Neovim uses those. If you yank something in Neovim with either `"+y` or `"*y`, the clipboard gets fed with the selection. It even works with just `y`, if you have `:set cb=unnamed` or `:set cb=unnamedplus` set.

For this the embedded program needs to be allowed to access the clipboard, of course. :)

**Comment by jsholmes** [comment]
I actually have a similar problem, but it only shows up when running over tmux.

I can copy/paste fine from nvim locally when I have :set cb=unnamedplus

When I try to do the same thing over a tmux session, I get nothing.  I can copy fine from my zsh shell over tmux and I can also copy fine from vim, just not neovim.

**Comment by mhinz** [comment]
@jsholmes `y`/`p` or `cmd+c`/`cmd+v`?

**Comment by croaky** [comment]
Great job on Neovim! I'm really enjoying the speed, particularly for lint-on-save-the-buffer and the parallel `:PlugInstall` / `:PlugUpdate`.

I was having the having the same copy-paste issue so thanks to those posting on this thread for the info.

I'm also using iTerm2 with these settings on Preferences > General:

![screen shot 2015-12-08 at 3 42 02 pm](https://cloud.githubusercontent.com/assets/198/11672096/46cda68a-9dc2-11e5-9388-7b3597cd3e48.png)

At that point, `y` and paste worked.

The `:set mouse=` change was also all I needed in my `~/.vimrc` to get `cmd+C` to work.

Thanks again!

**Comment by choosenvictim** [comment]
I also had similar problem with iTerm. For me, turning on ```Application in terminal may access clipboard``` didn't help.
What actually worked for me is: Profile -> Text -> Blinking Cusror (mark it checked)
Weird !!

**Comment by guillochon** [comment]
Unbelievably, @chosenvictim's solution worked for me too. I dunno what the heck is going on in iTerm2 but this weird combo of options should not be needed to get the clipboard to work normally...

**Comment by broady** [comment]
Worked for me, too. Thank you @chosenvictim !

**Comment by lucalandi** [comment]
I cannot copy paste from iTerm to a chrome window. I can paste instead in Notes. I'm not sure why this is happening.

**Comment by radzhome** [comment]
I'm on build 3.2.5, I can right click and copy but command + c does not work and copy is disabled from the edit menu. All the iterm settings look good as described here. I can copy using command + c in osx terminal just fine.

**Comment by javadba** [comment]
I can confirm this behavior:  ITerm is occasionally  getting "stuck" on old contents of the clipboard.  I can copy and paste fine to other mac apps : so it is not a macOS issue but instead specific to iterm

I am on build 3.1.3: Will have to shut it down I guess and re-install latest version.

**Comment by johnlangfy** [comment]
I'm on iTerm2 build 3.2.7.  I was getting this same issue sporadically until I deselected the following option:
Preferences > General > Selection > Copy to pasteboard on selection
