### ISSUE TITLE
Discourse for the community?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3703]
[Discourse](http://discourse.org) seems to be a really nice forum software nowadays. It has all the good things, like super configurable notifications, @mentions, and GitHub Markdown. It might be nice to host that right on the neovim.io site?

Check it out some live examples:

* https://forums.meteor.com
* http://forums.infamous.io
* http://discourse.wicg.io
* https://forums.hummingbird.me
* http://teh.moe
* https://tekinvestor.no
* https://animeforums.me

And a ton more [here](https://meta.discourse.org/t/please-visit-our-discourse-forum-directory/3102/4).

**Comment by justinmk** [comment]
It does look nice, but gitter is probably fine. Montenegro's and hosting are also out of our time budget IMO.

**Comment by ZyX-I** [comment]
@justinmk Gitter is no replacement for the discourse. But we have mailing list and issue tracker, and combination of this is fine I think.
