### ISSUE TITLE
Crash while mouse-selecting in two-buffer mode

### ISSUE THREAD

**Issue by ivashov** [neovim/neovim#3704]
Steps to reproduce:
1. Open second buffer (Ctr-W v)
2. Drag mouse cursor starting from area right to last character column in right buffer.

Nvim crashes with message:
```
nvim: /build/neovim/src/neovim-0.1.0/src/nvim/window.c:4548: win_drag_vsep_line: Assertion `fr' failed.
```

Archlinux
nvim 0.1.0
konsole

**Comment by ivashov** [comment]
Same issue in vim: https://github.com/vim/vim/issues/486

**Comment by dpelle** [comment]
I have not been able to reproduce it (using vim-7.4.922 on Linux). 
But maybe I misunderstood the steps to reproduce it.

Can you try to reproduce it when running vim with valgrind?

Can you also try after building Vim with asan. You can do that
by rebuilding Vim after un-comenting this line in vim/src/Makefile:

#SANITIZER_CFLAGS = -g -O0 -fsanitize=address -fno-omit-frame-pointer
