### ISSUE TITLE
Pasting from X11 doesn't work when running nvim as super user

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#3705]
With `clipboard=unnamedplus` and xsel. In fact, i don't think nvim even sources my vimrc when run with sudo.

**Comment by Pyrohh** [comment]
No comment on the X11 thing, but

> In fact, i don't think nvim even sources my vimrc when run with sudo.

Assuming your `sudo` is configured to run as root by default, I'm pretty sure this is to be expected.  `$HOME` should be different, so nvim would look for `/root/.config/nvim/init.vim`.
You didn't say, so I'm assuming your `init.vim` is actually in `/home/$LOGNAME/.config/nvim`.

**Comment by Pyrohh** [comment]
Also, do you get any errors when trying to paste from the system clipboard, or just nothing? If `$DISPLAY` isn't copied into the new environment, then I'd expect something like this:

```
xsel: Can't open display: (null)
: Undefined error: 0
```

**Comment by bfredl** [comment]
you could do `sudo xsel -o` outside nvim to quickly check if the X11 environment works.

**Comment by mtglsk** [comment]
With minimal vimrc it seems to work. I'm going to look what else in my init.vim causes the issue.
