### ISSUE TITLE
Wrong shell scripts syntax highlighting in NeoVim but not legacy Vim - outdated sh.vim

### ISSUE THREAD

**Issue by yan12125** [neovim/neovim#3711]
I have a simple shell script:
```Bash
arr=(
    'aaa'
# qq '
    'bbb'
)
```
In NeoVim 959f2601f982bb911c83cc6e948f06abd2e9c140 (with ```syntax/sh.vim``` version 132), it looks like:
![screenshot_2015-11-20_19-00-10](https://cloud.githubusercontent.com/assets/1937689/11298343/2931778a-8fb9-11e5-8ef8-15ab226ec05a.png)
And in Vim 7.4.884 (with ```syntax/sh.vim``` version 137), it looks like:
![screenshot_2015-11-20_19-00-37](https://cloud.githubusercontent.com/assets/1937689/11298354/4d7a7380-8fb9-11e5-8e8f-b533cef26db0.png)
Simply copying sh.vim from legacy Vim fixes the problem. Please update ```syntax/sh.vim``` thanks.

**Comment by justinmk** [comment]
We are behind on runtime updates. Closing this since we don't need individual issues documenting that. Thanks though
