### ISSUE TITLE
:terminal needs a filetype I think?

### ISSUE THREAD

**Issue by jsholmes** [neovim/neovim#3712]
I'd like to be able to disable things like my LengthMatters plugin in a :terminal buffer, but that doesn't seem possible currently.  Maybe I'm missing something?

**Comment by noahfrederick** [comment]
See `:help TermOpen` for the autocommand you can hook into.

**Comment by Pyrohh** [comment]
Using `buftype` seems like a reasonable solution given the special nature of `:terminal` buffers, so I'll close this. Someone please correct me if I'm wrong.

**Comment by rmolin88** [comment]
I second this request. `Autocommands` are fine but why not keep consistent. The main reason is so that you can have `ftplugin` with terminals. There are workarounds but it would be great to have native support.

**Comment by justinmk** [comment]
Asking for terminal buffers to have a single filetype is like asking for non-terminal buffers to have a single filetype. Terminal may be showing any filetype.

**Comment by rmolin88** [comment]
You are right after thinking about it. Thanks @justinmk
