### ISSUE TITLE
An easy way to hide the X in the top right corner?

### ISSUE THREAD

**Issue by paddor** [neovim/neovim#3713]
Hi

The `X` in the tabline is distracting to me. I close my tabs with `:q` or `:tabclose`. How to easily disable it?

Thanks.

**Comment by mhinz** [comment]
Slightly modified from `:h setting-tabline`:

```vim
function! MyTabLine()
  let s = ''
  for i in range(tabpagenr('$'))
    " select the highlighting
    if i + 1 == tabpagenr()
      let s .= '%#TabLineSel#'
    else
      let s .= '%#TabLine#'
    endif

    " set the tab page number (for mouse clicks)
    let s .= '%' . (i + 1) . 'T'

    " the label is made by MyTabLabel()
    let s .= ' %{MyTabLabel(' . (i + 1) . ')} '
  endfor

  " after the last tab fill with TabLineFill and reset tab page nr
  let s .= '%#TabLineFill#%T'

  return s
endfunction

function! MyTabLabel(n)
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)
  return bufname(buflist[winnr - 1])
endfunction

set tabline=%!MyTabLine()
```

**Comment by paddor** [comment]
@mhinz Well, thanks. But this makes my NeoVim crash. I was just filing a new issue to report it and disabling all my plugins and removing stuff out of my `~/.nvimrc` until I realized it's exactly this new code snippet.

Here the text I'd have submitted in a new issue, maybe it helps you fixing this segmentation fault:

>When I open 10 Ruby files together with `nvim -p ...`, it crashes every time right after confirming the `Found a swap file ...` notice.

>* What the answer to that notice is, doesn't seem to matter.
>* It does not crash with `-u NULL`
>* The files are Ruby files.
>* There are no super long lines, nor any non-ASCII characters.
>* emptying my `~/.nvim/bundle/` did not help
>
>[4 nvim crash dumps and the output of `nvim -v`](https://gist.github.com/paddor/166e9125556701a74ef3)

**Comment by mhinz** [comment]
Why do you have to restore from swap files in the first place? Without this, `nvim -u tabrc -p *.rb` works without problems. (Same commit on OSX.) So I guess the found swap file is triggering the problem somehow.

The dumps also show that it crashes in multiple places (1x during syntax highlight refresh, 2x during garbage collection, 1x during autocmd).

Since this is a different problem, could you open a new issue for this? Thanks!
