### ISSUE TITLE
incorrect indenting with open/close braces in comments

### ISSUE THREAD

**Issue by ahe01** [neovim/neovim#3717]
currently vim/neovim gives

```
int f()
{
    if(1){
        // {
        return 0;
    } // <--- (point 1)
    } // <--- (point 2)
```

and 

```
int f()
{
    if(1){
        // }
        return 0;
} // <--- (point 2)
}
```

this problem is caused by function `find_start_brace(void)` in indent_c.c, which calls `findmatchlimit()`, and `findmatchlimit()` won't skip braces in comments. current code can handle situation like `(point 1)` shown above, but fails for `(point 2)`.

**Comment by justinmk** [comment]
Did #3623 help with this?
