### ISSUE TITLE
Hundreds of 'numbered' buffers when starting without file arguments

### ISSUE THREAD

**Issue by ChrisPenner** [neovim/neovim#3719]
Hey everyone! Thanks for all the work you do here!

I've been getting a weird non-deterministic issue lately. From time to time I'll start up `nvim` without any command line args and it will open up with the buffers I had opened previously, but also several extra sequentially numbered buffers with the same file extensions of some of my current files.

For instance, once I opened nvim and had 300 extra buffers named `1.txt 2.txt 3.txt ... 323.txt`
It seems mostly random to me how many of these I get, I've gotten everywhere from 1 or 2, up to 300. They also often start numbering above 1.
Here's a picture of my buffer bar, seems as though it's only odd numbers for some reason:
<img width="993" alt="screen shot 2015-11-22 at 1 32 19 pm" src="https://cloud.githubusercontent.com/assets/6439644/11325818/8e84e0e4-911d-11e5-8bc7-f247aa3556c3.png">

Here's the filepath for one such buffer when I was working on a ruby project:
`chris/sites//private/var/folders/z3/hscpzt5s64q6_n6mpqz6779m0000gn/T/nvimdCYgm8/3.rb` 

Here's my version info (I'm on OSX 10.11.1)
```
nvim --version
NVIM 0.0.0-alpha+201510231011 (compiled Oct 23 2015 10:55:24)
Commit: de4cb766ca381c09fd3f938136c1932ebf008f63
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151023-72141-1vhks9l/build/config -I/tmp/neovim20151023-72141-1vhks9l/src -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/tmp/neovim20151023-72141-1vhks9l/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20151023-72141-1vhks9l/build/src/nvim/auto -I/tmp/neovim20151023-72141-1vhks9l/build/include
Compiled by chris

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Thanks for taking some time to check it out! I hope we can figure this out, it's getting ridiculous.

**Comment by torpak** [comment]
Firstly nvim version is quite old (it is marked alpha and still uses .nvimrc instead of init.vim), you might want to try with a newer version.
Secondly, you could try i it happens with nvim -u (or an empty startup file) to check if a plugin or a specialty in your configuration causes the trouble.
Thirdly you could try if vim does the same with the same plugins/configuration (off cause only possible, if they are all compatible with vim)

**Comment by Pyrohh** [comment]
Yes, all the things @torpak said would be helpful (it's mentioned in [CONTRIBUTING.md](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#reporting-problems)).

@ChrisPenner I'll close this for now, but please re-open if you can still reproduce the issue on a newer version of nvim.
