### ISSUE TITLE
Storing a funcref in a variable can break shada dump

### ISSUE THREAD

**Issue by rf-** [neovim/neovim#3721]
I was seeing this issue because of [a plugin](https://github.com/jdonaldson/vaxe/blob/79d59c8040fff21bdcf86b2d29e79411ad720115/plugin/haxe.vim#L63), but I can repro it manually with `-u NONE`. Here's a passing spec illustrating the behavior:

``` diff
diff --git a/test/functional/shada/variables_spec.lua b/test/functional/shada/variables_spec.lua
index 6225971..439f099 100644
--- a/test/functional/shada/variables_spec.lua
+++ b/test/functional/shada/variables_spec.lua
@@ -82,6 +82,13 @@ describe('ShaDa support code', function()
     eq(0, funcs.exists('g:str_var'))
   end)

+  it('breaks when a funcref is stored in a variable', function()
+    nvim_command('let C = function("escape")')
+    nvim_command('set shada+=!')
+    eq('Vim(wshada):E475: Invalid argument: attempt to dump function reference',
+      helpers.exc_exec('wshada'))
+  end)
+
   it('dumps and loads variables correctly when &encoding is not UTF-8',
   function()
     set_additional_cmd('set encoding=latin1')
```

I don't really understand this part of Vim well enough to know what the correct behavior is, but this was silently breaking shada saves for me. I guess it should probably just omit funcrefs when persisting variables?

**Comment by ZyX-I** [comment]
Note that despite the fact that failing to write ShaDa file in this case is a bug, using global `C` for a temporary variable name for funcref is incorrect: nobody guarantees that this global is either not taken for other purposes or that somebody did not use `C` as a temporary function name.

#3722 makes ShaDa code continue writing in such cases, but it still errors out.
