### ISSUE TITLE
Meta/Alt key: Neovim does not follow the terminal behavior

### ISSUE THREAD

**Issue by fabi1cazenave** [neovim/neovim#3727]
As you know, a terminal emulator has two ways to handle the Alt (Meta) key:
* either it sets the 8th bit of the current character, i.e. `<M-j>` sends an `ê` — that’s what Gvim does;
* or it sends Escape before the character, i.e. `<M-j>` sends `<Esc>j` — which is the default behavior of most terminal emulators (xterm being an exception). Let’s call this the *8bit-clean* mode.

Unlike Vim and all TUI apps that I’ve used so far, Neovim never respects the terminal *8bit-clean* mode when set. This is particularily annoying in a `:terminal` buffer (see #2440), but can also be a blocker for editing any buffer that contains non-ASCII characters because Alt-* shortcuts cannot be used in insert mode any more.

As an example, an 8bit-clean Vim allows to use Alt-j/k instead of Ctrl-n/p in insert mode:
```vim
inoremap <Esc>j <C-n>
inoremap <Esc>k <C-p>
```

But in an non-8bit-clean Vim, this makes it impossible to insert an `ê` or an `ë` — it would trigger a Ctrl-n/p instead.

MacVim had a similar issue that has been solved with the `macmeta` pref:
* when true, the alt key sends Escape;
* when false, the alt key ~~sets the 8th bit~~ works as AltGr.

If it isn’t possible to follow the terminal emulator setting (= *“meta sets 8th bit”* or *“meta sends Escape”*), please consider implementing a similar `meta` setting.

**Comment by fabi1cazenave** [comment]
Similar issues: #2068, #2088.

**Comment by strokirk** [comment]
+1!
This is the issue I've been having. Typing in a language with frequent Unicode symbols is competing with Neovim new 8bit-unclean mode mappings. Would be greatly interested in seeing this fixed!

**Comment by justinmk** [comment]
@fabi1cazenave Please try last master. Note about this mapping:

```
inoremap <Esc>j <C-n>
inoremap <Esc>k <C-p>
```

That will invoke `timeoutlen` for the `<esc>` key in insert-mode (makes sense if you think about it...). You should map `<M-j>` and `<M-k>` instead.

**Comment by strokirk** [comment]
Verified on `NVIM 0.1.2-dev` from nightly.

```
$ nvim -u NONE -c 'imap <m-e> X' -c 'nmap t iåäö <m-e><esc>ZZ' -s <(echo 't') test.txt  
$ cat test.txt 
åäö X
```

**Comment by fabi1cazenave** [comment]
@justinmk this works like a charm, that’s neat!

This is also a great improvement over Vim: when I use a utf8-clean term with Vim, I cannot use any `<M-x>` mapping (hence the `<Esc>x`). With Neovim, everything works as expected — and as you mention, this doesn’t invoke `timeoutlen` any more.
