### ISSUE TITLE
Autocommand on file specified in command line.

### ISSUE THREAD

**Issue by xcambar** [neovim/neovim#3728]
Hello,
No matter how hard I try, I can't get Neomake (but it could be any other command) to execute automatically when I start neovim with `nvim my/file.ext`.
I tried autocommands with `WinEnter,VimEnter,BufReadPost,FileReadPost,...` to no avail.

Interestingly, running `nvim my/file.ext +Neomake` gives me precisely what I'm looking for.

Maybe this behaviour takes its roots from Vim, but I'm still curious if I can achieve that.

---

PS : my ultimate goal is to have Neomake errors in the gutter no matter how I open the file, from neovim itself or direct from the command line...

**Comment by mhinz** [comment]
Did you ask the Neomake author already? I don't know how that plugin works and can only say the the `VimEnter` event works just fine.

Maybe check `:au VimEnter` if another plugin is interferring.

**Comment by xcambar** [comment]
Any idea, @benekastah?

@mhinz Good to know that `+Neomake` runs before `VimEnter`, because when using `au VimEnter`, nothing happens...

**Comment by justinmk** [comment]
@xcambar system details?

**Comment by xcambar** [comment]
MacBook Pro, OSX El Capitan 10.11.1 (15B42)

```
$ nvim --version
NVIM 0.1.0-dev (compiled Nov  9 2015 12:05:13)
Commit: f65e7bf30c8a00696d5740e35d0f84b9aa648b99
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151109-30583-1bigsbr/build/config -I/tmp/neovim20151109-30583-1bigsbr/src -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include -I/tmp/neovim20151109-30583-1bigsbr/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20151109-30583-1bigsbr/build/src/nvim/auto -I/tmp/neovim20151109-30583-1bigsbr/build/include
Compiled by xav@ProXav.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

Anything else?

**Comment by justinmk** [comment]
Seems like a usage question. Please try vi.stackexchange.com
