### ISSUE TITLE
vim-plug's "PlugInstall" not an editor command

### ISSUE THREAD

**Issue by esn89** [neovim/neovim#3729]
I honestly am not sure whether to post this on vim-plug or here.  So apologies in advance.

So right now, I just placed plug.vim in ~/.config/autoload and tried to run :PlugInstall from nvim and the "this is not an editor command" keeps poppin' up.

I have had success with vim-plug in the past on my older machines with neovim, so that is what prompted me to post here.  Anyone else have the same problem?

**Comment by noahfrederick** [comment]
> ~/.config/autoload

You are missing the `nvim` directory in that path: `~/.config/nvim/autoload/`.

**Comment by esn89** [comment]
hmm, i just tried it with the autoload dir and that didn't seem to work.

**Comment by fmoralesc** [comment]
Did you initialized vim-plug in the init.vim file pointing it at the correct path? (`:call plug#begin('~/.config/nvim')`) The command only gets created then.

**Comment by noahfrederick** [comment]
@esn89 In any case, this is almost certainly user error. You should refer to [vim-plug's usage instructions](https://github.com/junegunn/vim-plug#usage).

Note that the `:PlugInstall` command will not be available until the autoload script is sourced, which occurs when you source it manually, or more usually, call one of the autoloaded functions, such as `plug#begin()` in your [init.vim](https://neovim.io/doc/user/starting.html#vimrc).

**Comment by HQupgradeHQ** [comment]
Also if someone like me stuck with no commands on neovim at all , it's because new Plug manager using different syntax , i hope it will save someones time `Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }	`

**Comment by danschumann** [comment]
Random thing for me... read the error messages.  My Plug didn't install on a new computer because git wasn't installed yet... so the auto install script was failing.

**Comment by slalbertojesus** [comment]
If you are on manjaro, make sure to edit the .vimrc in this location:
/home/yourusername/.vim/vimrc

**Comment by darklaser28** [comment]
> Did you initialize vim-plug in the init.vim file pointing it at the correct path? (`:call plug#begin('~/.config/nvim')`) The command only gets created then.

Why don't I have the nvim folder in my .config file ?

**Comment by abd96** [comment]
> > Did you initialize vim-plug in the init.vim file pointing it at the correct path? (`:call plug#begin('~/.config/nvim')`) The command only gets created then.
> 
> Why don't I have the nvim folder in my .config file ?

You may create it yourself!

**Comment by lizsrpr** [comment]
> Did you initialize vim-plug in the init.vim file pointing it at the correct path? (`:call plug#begin('~/.config/nvim')`) The command only gets created then.

Also (since I had this issue) if you make the init.vim file, make sure that it is ".vim" format when its first created. I attempted to create a formatless file, and a txt file with the lines needed inside so that I could then add the ".vim", and it failed because the data wasn't formatted properly as a result of the change in file extension.

**Comment by ronnycoding** [comment]
run `:checkhealth` that works for me to figure out what I've missed on my computer
