### ISSUE TITLE
Ctrl-N Insert completion failing with Tags file not sorted

### ISSUE THREAD

**Issue by 3cooper** [neovim/neovim#3730]
I get the following error when trying to use `ctrl-n` completion:

    Scanning tags.
    E432: Tags file not sorted: tags
    Press ENTER or type command to continue

I can reproduce this with `nvim -u NONE`.  I am running on OS X and installed nvim version 0.1.0 using homebrew.

**Comment by 3cooper** [comment]
I guess this can be closed.  As soon as I submitted this I went back and tried again and now I cannot repeat it.  Before opening the issue I was able to do this in a new version of nvim and did that a few times.  Not sure what is happening now.

**Comment by oscarbailey** [comment]
I had a corrupt tags file in my home directory which produced this error. It was corrupted because I interrupted ctags before it had finished writing to the tags file.
