### ISSUE TITLE
neovim don't use my .nvimrc

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3735]
after my last update of neovim . it doesn't use my .nvimrc

here is what i did . 

git clone https://github.com/neovim/neovim.git ---> make cmake ---> cmake ---> sudo make install

after that i have .nvimrc in home directory . but neovim don't use it

**Comment by ZyX-I** [comment]
It should not. See `:h vimrc`. And it was reported more then once or twice.

**Comment by 7belrhalmia** [comment]
@ZyX-I  how can i fixe that i didn't find the solution

**Comment by ZyX-I** [comment]
Read documentation. `.nvimrc` has moved to another location.
