### ISSUE TITLE
E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 3

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#3736]
i got this error after the last update

**Comment by ZyX-I** [comment]
Are you trying to have viminfo file shared with Vim? In any case you need to remove your viminfo file to make this disappear, or make `&shada` option point to another location (I guess it contains something like `n~/.viminfo` at the end: otherwise its location would change automatically and you would not get the error after update). Note that `&viminfo` option is now an alias to `&shada` option.

**Comment by 7belrhalmia** [comment]
@ZyX-I  so i have to remove my viminfo and viminfo.tmp and replace it with :  shada/main.shada
 in .nvim directory

**Comment by ZyX-I** [comment]
@7belrhalmia You need to *either* remove or replace. By “replacing” I mean configuring neovim to use another location. Also directory is no longer `.nvim`, neovim is following XDG spec.

**Comment by ZyX-I** [comment]
You don’t need to remove anything if neovim will be using different location. But if you want to keep the location you will have to remove the file due to changes in the format.

**Comment by ZyX-I** [comment]
And in any case sharing viminfo file with Vim is no longer possible.

**Comment by 7belrhalmia** [comment]
@ZyX-I  i have removit this to file from ~/.config/nvim/   so iremovit viminfo and viminfo.tmp and i still got the same error

**Comment by 7belrhalmia** [comment]
i have this in my .nvimrc  


"  <!----------------------------conf/viminfo.vim----------------------------------------!>
" Configure VIM's viminfo file
" Tell vim to remember certain things when we exit
"  '500   :  marks will be remembered for up to 500 previously edited files
"  "200   :  will save up to 200 lines for each register
"  :1000  :  up to 1000 lines of command-line history will be remembered
"  %      :  saves and restores the buffer list
"  n/path :  where to save the viminfo files
" Number of files to remember marks for:
set viminfo='500
" Maximum number of lines to save for each register:
set viminfo+=\"100
" " Save and restore the buffer list:
" set viminfo+=%
" Path to write the viminfo file (previously was ~/.viminfo):
let viminfopath='~/.vim/viminfo'
execute "set viminfo+=n".escape(viminfopath, ' ')

**Comment by ZyX-I** [comment]
@7belrhalmia 

    let viminfopath='~/.vim/viminfo'
    execute "set viminfo+=n".escape(viminfopath, ' ')

you should not have these lines at all. In any case it is impossible to share this file.

Also it is *very* bad idea to use `execute` with `set`, for this purposes there is `let &viminfo .= ',n' . escape(viminfopath, ',')`: you are escaping less then a half of the characters which may be present in the path and need to be escaped when you use `execute` + `set`, not to mention the fact that comma needs to be escaped with `\\`.

**Comment by 7belrhalmia** [comment]
i'am sorry i now that i make you lose your time but please help me to become good on neovim . 

now i do like this : 

    let viminfopath='~/.config/nvim/shada/main.shada'

now my sessons 's info are in main.shada the new format of viminfo file 

and 

    let &viminfo .= ',n' . escape(viminfopath, ',')
i don't now what this line do please explained to me simply i'm a biginner but i wont to be a pro

**Comment by ZyX-I** [comment]
@7belrhalmia `let viminfopath` has absolutely nothing to do with the file format and has nothing to do with the definition of the location. The only thing it does is defining the variable `viminfopath`. It is *second* statement that tells [neo]vim about the location (BTW, you are missing backslash from `escape()` argument: I have modified my previous message). And these lines *still* should not be there: the location you are referencing is the default location, so they are not needed, but the fact that previous location was under `~/.vim` means that this configuration is most likely shared with Vim which must not happen.

For more details about what the second statement does check `:h shada-n` (`:h viminfo-n` in Vim).

**Comment by tsaleh** [comment]
Just so others who're hitting this issue like I did find an easy fix:  If you want to use the same `~/.vimrc` file for vim and neovim, and you want to specify the location of your `viminfo` file, then use something like this:

```
if !has('nvim')
  set viminfo+=n~/.vim/viminfo
endif
```
