### ISSUE TITLE
:Explore blocks neovim

### ISSUE THREAD

**Issue by matthiasbeyer** [neovim/neovim#3737]
Whenever I want to enter the `:Explore` vim buffer (the netrw thing) neovim blocks completely for me.
I can then hit Ctrl-C several times until nvim responds again, though I do not get the netrw buffer.
I'm using vim-vinegar so I'm not sure whether this is an issue of the plugin or of neovim itself.

**Comment by ajpaulson** [comment]
Can you reproduce with `nvim -u NONE` ?

**Comment by ajpaulson** [comment]
I have tried to recreate your issue using my init.vim, `nvim -u NONE`, and _only_ vinegar.vim - I cannot reproduce this blocking.

In all attempts the `:Explore` (and variant) window opens instantly.

Can you think of anything else that might be causing this?

**Comment by matthiasbeyer** [comment]
With `nvim -u NONE` `:Explore` is not available. I'm not sure how to load _only_ vinegar.vim, though. I cannot think of other plugins... 

My Mapping should be alright:

```vim
nmap <Leader>e :Explore<CR>
```

?

**Comment by ajpaulson** [comment]
If `:Explore` is unavailable with `nvim -u NONE` then there is something weird going on. I have it available even with `nvim -u NORC` as it has been baked into base neovim.

I loaded only vinegar.vim this way: `nvim -u /path/to/vinegar.vim`

what is the output of `nvim --version` ?

**Comment by mhinz** [comment]
`-u NONE` doesn't load plugins. `:Explore` (note that it's an uppercase command) is provided by the shipped netrw plugin. This is expected behaviour.

**Comment by ajpaulson** [comment]
@mhinz so then _I'm_ getting unexpected behaviour? Because `:Explore` (yes uppercase, yes netrw) is working for me with both `-u NONE` and `-u NORC`
![screenshot from 2015-11-27 15-30-43](https://cloud.githubusercontent.com/assets/1290947/11444317/64392af4-951c-11e5-9d6e-e2a28ddc0835.png)

**Comment by mhinz** [comment]
@ajpaulson `-u NORC` should load netrw just fine, but having it working with `-u NONE` is indeed strange.

**Comment by ajpaulson** [comment]
hmmm - I assumed that NONE sourced global config and NORC didn't source any so it would be the other way round (`:Explore` wouldn't work with NORC but would work with NONE).

I just double checked and realised that I got tripped up by my own logic, and not double checking command completion - NORC working, NONE "not an editor command"

But I can't reproduce this blocking.

@matthiasbeyer that mapping shouldn't cause any slowdown

**Comment by justinmk** [comment]
Probably related to  `'clipboard'`. Covered by https://github.com/neovim/neovim/issues/3726
