### ISSUE TITLE
:make reorders output of stderr and stdout (in some cases)

### ISSUE THREAD

**Issue by xelxebar** [neovim/neovim#3746]
When running :make, neovim seems to reorder stderr and stdout in some cases. Below, I give steps on how to demonstrate the issue on my machine as well as the output of `nvim --version` at the very end.

Note that `nvim` is run as `nvim -u NONE` below. Also, this issue is reproducible in vim 7.4 and I have reported the same issue on the mailing lists over there.

## Reproducing the Behaviour

In a single directory:

Create the following `foo.c` file:

		#include <stdio.h>

		int main()
		{
			printf("This is a message on stdout and should appear first\n");
			fprintf(stderr, "This is a message on stderr and should appear second\n");

			return 0;
		}

Create the following in a `Makefile`:

		run: foo
			@./foo

Let make compile and run the program:

		$ make run
		cc     foo.c   -o foo
		This is a message on stdout and should appear first
		This is a message on stderr and should appear second

Now compare this to when calling `:make run` from `nvim`:

		:make run
		This is a message on stderr and should appear second
		This is a message on stdout and should appear first

## Version Information

		NVIM 0.1.0 (compiled Nov  2 2015 18:05:23)
		Build type: RelWithDebInfo
		Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.0/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
		Compiled by builduser

		Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
		For differences from Vim, see :help vim-differences

		   system vimrc file: "$VIM/sysinit.vim"
		   fall-back for $VIM: "/usr/share/nvim"

**Comment by tarruda** [comment]
I believe this indeterminism is caused by the order the OS notifies nvim about stdout/stderr events. In your terminal you always see the messages in order because both stdout and stderr are the pty slave fd, so from the POV of the terminal there's only one event source.

Neovim OTOH creates separate pipes for stdout and stderr, which means two event sources. The order we get notifications is determined by the OS.

**Comment by xelxebar** [comment]
@tarruda Thank you for the quick response. I definitely jumped the gun here. Adding a `fflush(stdout)` between the `printf` calls preserves order. Sorry for the issue spam.
