### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by gregf** [neovim/neovim#3756]
When I start neovim (no config files present) it just returns Bus error to the console and exists.

I have a strace [here](http://sicp.me/p/ns9NC)

**Comment by xcelq** [comment]
I think i figured it out to a plugin when i did nvim --noplugins it worked but i don't believe i have any plugin installed.

**Comment by Pyrohh** [comment]
Could you provide a backtrace with `gdb`? I don't think strace is too helpful here.

**Comment by justinmk** [comment]
No reply.

**Comment by mallochine** [comment]
lol why no reply?

**Comment by justinmk** [comment]
"No reply" means we asked a question and didn't get a reply. We need a backtrace, as requested above. If you have one, please open a new issue. 

lol.
