### ISSUE TITLE
Accessing vim.current.window (through python-client) breaks CursorHoldI?!

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#3757]
I have found a strange bug when using deoplete, where accessing `self.vim.current.window` through a Python RPC call seems to break the `CursorHoldI` handling?!

See https://github.com/Shougo/deoplete.nvim/issues/81 for more information and a test case (based on deoplete).

I have also tried the latest python-client from Git (https://github.com/neovim/python-client/tree/6c0ec04307442dedc851873504b379f4dcdb33a0) without success.

Why might that happen?
Where can I look further to debug this?

This breaks the feature to display call signatures (`g:jedi#show_call_signatures`) in jedi-vim.

**Comment by blueyed** [comment]
Just calling `self.vim.eval("1")` seems to trigger this issue already (when used as the first statement in
https://github.com/Shougo/deoplete.nvim/blob/fed61ada642b86cf6bb70cb6914628fbe0ac902e/rplugin/python3/deoplete/__init__.py#L46).

/cc @Shougo

**Comment by tarruda** [comment]
> Why might that happen?

I have recently changed how cursor hold is triggered, but I can't immediately say what's causing the issue

> Where can I look further to debug this?

cursorhold is triggered in the [`os_inchar` function](https://github.com/neovim/neovim/blob/master/src/nvim/os/input.c#L108) when `trigger_cursorhold() && !typebuf_changed(tb_change_cnt)` evaluates to true, so you could start by investigating what's causing it to always evaluate to false. There's a chance that watching the `did_cursorhold` global variable will reveal the cause.

**Comment by blueyed** [comment]
Seems to be related to `&& s->ca.cmdchar != K_EVENT` at https://github.com/neovim/neovim/blob/a03af86cc28d9e755f5941b5dfaf54d003a1ad97/src/nvim/normal.c#L1108 (added in e5165bae11).

**Comment by blueyed** [comment]
Also commenting this line fixes it (but breaks maybe something else?): https://github.com/neovim/neovim/blob/a03af86cc28d9e755f5941b5dfaf54d003a1ad97/src/nvim/edit.c#L613

**Comment by tarruda** [comment]
> Also commenting this line fixes it (but breaks maybe something else?):

According to the comment, cursorhold should not trigger while processing multi-key commands such as `<c-v>`

> Seems to be related to && s->ca.cmdchar != K_EVENT at

Close, I think the line which causes the bug is this one: https://github.com/neovim/neovim/commit/e5165bae1139221ef752bccd582c7bd7474e6747#diff-ce1f54750dd541783db1cf9a24120ba8R1221

That is because the same "special key" is used for both cursorhold and other events, and we need a way to distinguish so `did_cursorhold` will be set to false properly. I need to think about this for a while

**Comment by Shougo** [comment]
Reproduced.
CursorHoldI autocmd is not triggered using neovim Job API....

**Comment by PonderingGrower** [comment]
+1 for this issue.

**Comment by blueyed** [comment]
@tarruda 
Any new insights / update on this front?

It's a very subtle, but very annoying bug.

**Comment by blueyed** [comment]
@tarruda 
FYI, a similar issue regarding the popup menu was fixed in #4461 - in case that helps to narrow this one down.

**Comment by justinmk** [comment]
The root cause of this issue may also affect timers: https://github.com/neovim/neovim/pull/4624#issuecomment-222052654

**Comment by blueyed** [comment]
Here is a minimal test case:

`t.vim`:

```vim
set noshowmode
set updatetime=100

let s:init = 0

function! F()
  if !s:init
    call _init_channel()
    call rpcnotify(g:_channel, 'completion_begin')
  endif
  let s:init = 1
endfunction

augroup test
  au CursorHoldI * echom 'CHI'
  au InsertEnter * call F()
augroup END
```

`~/.vim/rplugin/python/debug_issue3757.py`:

```python
@pynvim.plugin
class Limit(object):
    def __init__(self, vim):
        self.vim = vim

    @pynvim.function('_init_channel', sync=True)
    def init_channel(self, args):
        self.channel_id = self.vim.channel_id
        self.vim.vars['_channel'] = self.vim.channel_id

    @pynvim.rpc_export('completion_begin')
    def completion_begin(self):
        foo = self.vim.current.window
```

After `:UpdateRemotePlugins` running `nvim -u t.vim`:

1. enter insert mode
2. 'CHI' is not displayed
3. exit insert mode
4. enter it again, it gets triggered

As for deoplete, it does this on InsertEnter always by default (a remote call),
and therefore CursorHoldI never works with it there then.

**Comment by blueyed** [comment]
There is something else in my vimrc though - even with deoplete disabled and invalid python host progs CursorHoldI does not work when going into insert mode the first time.
Even with `:noauto call feedkeys('i')`.

**Comment by blueyed** [comment]
Ok, the other issue is due to vim-startify: using `i` from the startify buffer does not trigger CursorHoldI the first time, but it works later and/or when using `e` (for a new buffer) first.
I've used the following to test it at the top of my vimrc
```
set noshowmode
au CursorHoldI * echom 'CHI!'
set updatetime=100
```
/cc @mhinz

**Comment by blueyed** [comment]
However, startify alone also does not trigger it, using this vimrc, and the `i` to go to insert mode there directly.
```vim
scriptencoding utf8                                                                                                                                             set noloadplugins                                                                                                                                               let &runtimepath = expand('<sfile>:p:h') . ',' . &runtimepath                                                                                                   runtime plugin/startify.vim                                                                                                                                                                                                                                                                                                     set noshowmode                                                                                                                                                  au CursorHoldI * echom 'CHI!'                                                                                                                                   set updatetime=100
```

I hope the above rplugin test case is minimal enough to investigate from your side, and then I can check if it also fixes startify in my setup.

**Comment by mhinz** [comment]
`t.vim` misses `g:_channel` and `_init_channel()`.

**Comment by taigacute** [comment]
[My question](https://github.com/neoclide/coc.nvim/issues/414), is it related to this?

**Comment by gelguy** [comment]
Smaller `vimrc` to reproduce the issue by using a timer instead of rpc
```vim
set noshowmode
set updatetime=100

let s:init = 0

function! F()
  if !s:init
    call timer_start(0, {-> 1})
  endif
  let s:init = 1
endfunction

augroup test
  au CursorHoldI * echom 'CHI'
  au InsertEnter * call F()
augroup END
```

Refer to https://github.com/neovim/neovim/blob/c6cd6081b8c449fa9890c18b5e2151e3af9bd45d/src/nvim/edit.c#L643-L644
`K_EVENT` prevents `CursorHold` events from triggering. If this is changed to
```vim
  if (key != K_EVENT) {
    did_cursorhold = true;
  }
```
the above `vimrc` will work as expected.

What I'm worried about is the comment about `K_EVENT`... I'm not well-versed enough in that area of code to understand the implications of changing the code here.

**Comment by blueyed** [comment]
@gelguy 
Thanks for this.  I hope to look into this during the next week.

**Comment by blueyed** [comment]
Actually with the above vimrc from @gelguy you can also see it without a timer already: it is not triggered while staying in insert mode, inserting something, and then waiting..?!
Added the above patch to https://github.com/neovim/neovim/pull/3758.

I agree with @tarruda that this should likely be refactored / fixed properly by adding this to the state, and using a timer instead - OTOH the timeout in `os_inchar` is the `updatetime` already, so it kind of makes sense to handle it right there, in case of reading nothing because of a timeout.
