### ISSUE TITLE
vim-airline wrong BG and overflowing

### ISSUE THREAD

**Issue by cHoco** [neovim/neovim#3763]
Hello, sorry for the pretty bad report. I wasn't able to track the source of the problem myself so I'll post the issue here.
When the text of the current function provided by Tagbar vim plugin displayed in the statusline by vim-airline overflows in one of the other components the background of the other components isn't rendered properly. Also when having two splits one next to the other the status line overflows from one window to the other.
Here's a screenshot that shows the problem:

When there is enough space:
<img width="490" alt="screen shot 2015-11-29 at 13 41 02" src="https://cloud.githubusercontent.com/assets/85527/11457055/e3254068-969e-11e5-91c7-2705d475eed3.png">

When the tag bar component overflows in another component:
<img width="483" alt="screen shot 2015-11-29 at 13 40 47" src="https://cloud.githubusercontent.com/assets/85527/11457057/e54365fa-969e-11e5-893e-3522bb08f628.png">

The same issue isn't present with vim that's why I'm posting here.
Here's the min vimrc I can reproduce the issue with.

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'majutsushi/tagbar'
Plug 'bling/vim-airline'
call plug#end()
set laststatus=2
```

**Comment by fmoralesc** [comment]
I can confirm.

**Comment by mhinz** [comment]
I noticed that it only happens at a certain width of 2 columns for me. If I make the window bigger or smaller, the right side gets highlighted as expected.

**Comment by cHoco** [comment]
I was trying to track this down today and found out that `build_stl_str_hl` neovim version is different from vim one. It was refactored in this pull request: https://github.com/neovim/neovim/pull/3339 
I confirmed that the bug was introduced by that pull.
I'll try and take a look what change introduced the bug, but since others probably already know that code better I'll tag people that worked on that pull request. @justinmk @war1025

**Comment by justinmk** [comment]
Thanks @cHoco !

**Comment by cHoco** [comment]
This patch solves the issue for me, others may try to test it:
``` diff
diff --git a/src/nvim/buffer.c b/src/nvim/buffer.c
index 7978dc8..d2e1f04 100644
--- a/src/nvim/buffer.c
+++ b/src/nvim/buffer.c
@@ -3745,11 +3745,10 @@ int build_stl_str_hl(
       // Put a `<` to mark where we truncated at
       *trunc_p = '<';
 
-      // Advance the pointer to the end of the string
-      trunc_p = trunc_p + STRLEN(trunc_p);
-
       // Fill up for half a double-wide character.
       while (++width < maxwidth) {
+        // Advance the pointer to the end of the string
+        trunc_p = trunc_p + STRLEN(trunc_p);
         *trunc_p++ = fillchar;
         *trunc_p = NUL;
       }
```

I'm not entirely sure why moving this back in would be correct, since the reasoning given int he pull request for moving it out seems correct to me.

**Comment by wsdjeg** [comment]
thanks @cHoco
