### ISSUE TITLE
Middle-click paste not working in cmdline

### ISSUE THREAD

**Issue by memeplex** [neovim/neovim#3765]
With `mouse=a` I can middle-click and shift-middle-click paste on insert mode, but only shift-middle-click paste on cmdline mode. That is, at the terminal level middle-click is working, but at nvim level it's just working for insert mode. Moreover it works for both modes in plain old vim. The facts that it works in one mode but not in the other, that it works for the terminal and that it works for vim, are pointing out to a bug in nvim.

**Comment by justinmk** [comment]
Isn't this same as
https://github.com/neovim/neovim/issues/2468 ?
