### ISSUE TITLE
disable cmdline, or accept height=0

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#3766]
In a GUI environment, one might want to draw the command line in a more fancy way (i.e., transparent floating bubble). Is there a way (or plan) to disable the command line, or accept zero height and hence make it disappear?

Similar to what was asked here:
http://stackoverflow.com/questions/7770413/remove-vim-bottom-line-with-mode-line-column-etc

Right now :set cmdheight=0 is not accepted.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/1004
