### ISSUE TITLE
neovim build fail on luacheck behind proxy

### ISSUE THREAD

**Issue by kwon-young** [neovim/neovim#3769]
Hi,
I have a neovim installation behind a proxy.
When i tried to pull and build the latest version of neovim, the build fail at 95% when trying to download luacheck.

I work on a Ubuntu 15, with the latest version of neovim.

```
[ 95%] Generating usr/bin/luacheck
Warning: falling back to curl - install luasec to get native HTTPS support
Cloning into 'luacheck'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

Error: Failed cloning git repository.
CMakeFiles/luacheck.dir/build.make:51: recipe for target 'usr/bin/luacheck' failed
make[3]: *** [usr/bin/luacheck] Error 1
make[3]: Leaving directory '/home/kwon-young/Prog/neovim/.deps'
CMakeFiles/Makefile2:336: recipe for target 'CMakeFiles/luacheck.dir/all' failed
make[2]: *** [CMakeFiles/luacheck.dir/all] Error 2
make[2]: Leaving directory '/home/kwon-young/Prog/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kwon-young/Prog/neovim/.deps'
Makefile:70: recipe for target 'deps' failed
make: *** [deps] Error 2
```

i have set my environment proxy configuration

```
export HTTP_PROXY=http://username:passwd@proxy.addres:portnumber
export HTTPS_PROXY=https://username:passwd@proxy.addres:portnumber
```
i have set my proxy for git

```
git config --global http.proxy http://username:passwd@proxy.addres:portnumber
git config --global https.proxy https://username:passwd@proxy.addres:portnumber
```

**Comment by mhinz** [comment]
Hmm, luarocks is handling the cloning. See if this old trick helps:

```
git config --global url."https://".insteadOf git://
```

**Comment by kwon-young** [comment]
That fixed the issue. 
Thank for your answer !

I think i'm going to update the wiki for troubleshooting on building with proxy

**Comment by Sean-Der** [comment]
@kwon-young This hit me today as well (built neovim on a host with no internet)

I think the fix is luacheck should be available in tree, starting with https://github.com/neovim/neovim/commit/818f926eb0ad1cdb3ca60a9f08682b50df4094e3 I am unable to build.

**Comment by mhinz** [comment]
@Sean-Der Depends.

Assuming the build system didn't add new dependencies, internet connection should only be needed for the initial `make`, since all the third-party stuff must be downloaded (libtermkey, libuv, luajit, busted, ...). 

All subsequent `make`s should work without internet connection without any problem.

**Comment by mhinz** [comment]
@kwon-young Since luacheck updated its rockspec, it should work now even without that git workaround. (It now tries git and https.)

**Comment by kwon-young** [comment]
I've recompiled neovim from scratch from behind a proxy, and everything compile fine, so i don't think it is necessary to reopen this issue.
