### ISSUE TITLE
Odd characters when pasting in insert mode in a terminal buffer

### ISSUE THREAD

**Issue by aandrieiev** [neovim/neovim#3771]
When copy-pasting from the system clipboard into a terminal buffer in insert mode, there are some odd question mark characters (perhaps, binary info not matching any unicode code points?) surrounding the copied text: `test text -> ??????test text??????` 

Reproducible through `nvim -u NONE`, `:sp term://bash`, `i`, `Cmd-V` 

Note: pasting from Neovim's clipboard, e.g. `yy` + `p` works as expected

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/3476
