### ISSUE TITLE
nvim :! won't show output until newline (while vim's will)

### ISSUE THREAD

**Issue by memeplex** [neovim/neovim#3772]
Try `:!echo -n x; sleep 2` in both vim and nvim.

Now try `:!echo x; sleep 2`.

This behavior is wrong as feedback to the user is delayed. For example, python unittest shows a sequence of dots `....`, one for each passed test, and you won't see any point until all tests are done.

**Comment by mhinz** [comment]
Neovim's `:!` invokes a non-interactive shell. See `:h :term` for interactive input.

**Comment by memeplex** [comment]
I don't think this is related to the shell being interactive or not. Using `-ci` won't do it.

**Comment by ZyX-I** [comment]
@mhinz This is irrelevant: it is buffering issue. (BTW, Vim by default also does not use an interactive shell: you should’ve said “neovim does not connect shell to a (pseudo-)tty”.)

**Comment by mhinz** [comment]
Oh, pardon. I mixed something up here. `:!` reads from a pipe connected to the output of an external program whereas `:term` connects to a PTY.

**Comment by ZyX-I** [comment]
@mhinz I am not familiar with these code, but I would say that this is neovim libuv usage issue and not libuv issue: `jobstart()` with the same input invokes `on_stdout` callback immediately.

**Comment by cthulhua** [comment]
I dug into this some. The callback's function for shell command output to the screen is buffered, similarly to shell output to a vim buffer; nothing gets written out until a newline or EOF are seen - see https://github.com/neovim/neovim/blob/master/src/nvim/os/shell.c#L453

It looks like the change was introduced in this commit: https://github.com/neovim/neovim/commit/3b435621a55ffada58f9c2c991c61fc50b358c01

I also took a closer look at os/shell.c's write_output function - it's for writing shell command output to the screen directly as well as to buffers (with two boolean params intertwined through the function to manage the differences between the two use cases), and only has 2 call sites, one for each case. I did some work to fix this bug, and in doing so, spun out a write_output_screen function that is not buffered and fixes this bug. See https://github.com/cthulhua/neovim/blob/feature-dont-buffer-shell-output/src/nvim/os/shell.c#L435

If this path looks right, I can claim the issue and make a pull request from the above fork, with the cleanup/simplification to the write_output function for buffers as well. I want to be sure this is the correct behavior, though.

**Comment by justinmk** [comment]
@cthulhua Thanks for looking. Did you try just changing the call site to send `false` instead of `true`?

**Comment by cthulhua** [comment]
@justinmk yeah, that accomplished the same as my change (it does insert SOH in place of NULLs though).
Unfortunately, I've noticed a problem here - with both those fixes, we insert extra newlines
For example, the command `:!echo -n foo; sleep 3; echo -n bar; sleep 3` behaves as follows:

Version | behavior
------- | --------
vim 7.4 | `foo` wait 3 seconds `bar` wait 3 seconds
neovim 0.1.0 | wait 6 seconds `foobar`
set EOF flag/write_output_screen | `foo\n` wait 3 seconds `bar\n` wait 3 seconds

I'm going ahead and claiming this issue - I'll work on getting Neovim to behave the same way as vim here, and adding some tests.

**Comment by cthulhua** [comment]
d'oh, I can't assign issues. I'll just continue working on this an put put a PR

**Comment by justinmk** [comment]
Great!

**Comment by mhinz** [comment]
@cthulhua :+1: for working at this.

And by the way, only people from the Neovim org can assign issues to other people from the org.

**Comment by oni-link** [comment]
@memeplex, looks like e9061117a5b8f195c3f26a5cb94e18ddd7752d86 fixed this problem.
