### ISSUE TITLE
Double clink on a word with a mouse goes to insert mode and doesn't copy all  the URL

### ISSUE THREAD

**Issue by oren** [neovim/neovim#3773]
In vim, double click allows me to mark a word (or URL) which copies it to the clipboard.
in nvim it goes to insert mode and in the case of a URL it have another annoying side effect - it doesn't copy the entire URL.

I have the following lines in .Xresources in order to make urls clickable. i am not sure if that's relevant but I just wanted to elaborate more about my issue.
```
xterm*charClass: 33:48,36-47:48,58-59:48,61:48,63-64:48,95:48,126:48
*VT100*translations: #override Meta <Btn1Up>: exec-formatted("x-www-browser '%t'", PRIMARY)
```

**Comment by fwalch** [comment]
That's probably because of the `mouse=a` default in nvim. Try if `:set mouse=` fixes your problem.

**Comment by oren** [comment]
That solved the highlighting problem - the entire URL (or word) is highlighted. Thanks! 

Interestingly (and maybe not related to that ticket) is that in nvim (unlike vim) a marked text is not being copied to my clipboard. Here is my .vimrc file - https://github.com/oren/dotfiles/blob/master/x1/.vimrc
Notice that all the `set clipboard` lines are commented and vim is copying fine.

**Comment by oren** [comment]
i realized that in order for the copy to work properly i do need one line: `set clipboard=unnamed`. still, it only work with vim. not nvim. i added it to my .vimrc file.

**Comment by oren** [comment]
since the text is not being copied to the clipboard i'll investigate more and create a separate issue with accurate steps to reproduce. thanks.
