### ISSUE TITLE
API: nvim_buf_set_option() does not trigger autocmds

### ISSUE THREAD

**Issue by watiko** [neovim/neovim#3776]
``` lua
local helpers = require('test.functional.helpers')
local nvim = helpers.meths
local clear, eq = helpers.clear, helpers.eq
local curbuf, buf = helpers.curbufmeths, helpers.bufmeths
local source, execute = helpers.source, helpers.execute

describe('au FileType *', function()
  before_each(function()
    clear()
    source([[
      fu! AutoCommand(match)
        let g:ret = a:match
      endfu
      let g:ret = ''
    ]])

    execute('au FileType * :call AutoCommand(expand("<amatch>"))')
  end)

  it('should be called through :set', function()
    execute('set ft=vim')
    eq(curbuf.get_option('ft'), nvim.get_var('ret'))
  end)

  it('should be called through :setbufvar', function()
    local curbufnr = curbuf.get_number()
    execute('call setbufvar(' .. curbufnr  .. ', "&ft", "vim")')
    eq(curbuf.get_option('ft'), nvim.get_var('ret'))
  end)

  it('should be called through neovim\'s api', function()
    curbuf.set_option('ft', 'vim')
    eq(curbuf.get_option('ft'), nvim.get_var('ret'))
  end)
end)
```

This spec will fail. Is this behavior intended?

**Comment by watiko** [comment]
I found the both `switch_win` and `switch_buffer` are used in `set_option_value_for` and they prevent nvim from executing `autocmd`s.
https://github.com/neovim/neovim/blob/v0.1.0/src/nvim/api/private/helpers.c#L755
https://github.com/neovim/neovim/blob/v0.1.0/src/nvim/api/private/helpers.c#L770
https://github.com/neovim/neovim/blob/v0.1.0/src/nvim/window.c#L5288-L5291
```c
/*
 * Make "buf" the current buffer.  restore_buffer() MUST be called to undo.
 * No autocommands will be executed.  Use aucmd_prepbuf() if there are any.
 */
```
https://github.com/neovim/neovim/blob/v0.1.0/src/nvim/window.c#L5233-L5240
```c
/*
 * Set "win" to be the curwin and "tp" to be the current tab page.
 * restore_win() MUST be called to undo, also when FAIL is returned.
 * No autocommands will be executed until restore_win() is called.
 * When "no_display" is TRUE the display won't be affected, no redraw is
 * triggered, another tabpage access is limited.
 * Returns FAIL if switching to "win" failed.
 */
```

However nvim will execute `autocmd`s when we set option globally through `vim_set_option`.
https://github.com/neovim/neovim/blob/v0.1.0/src/nvim/api/vim.c#L370

I think these behavior are odd and are not consistent.

**Comment by watiko** [comment]
We needs to use `aucmd_prepbuf()` and to add `noautocmd`s equivalent feature for flexibility and upstream Vim's feature OptionSet (#3753).
(Maybe we should also treat window like  https://github.com/vim/vim/commit/ba117c23dfd1146aca3235bea172df17a48bccee)

ping @tarruda

**Comment by watiko** [comment]
Vim(if_python) and NeoVim(api) do not treat `autocmd`s in setting option which is local to window/buffer  (`FileType` and `Syntax`).

**Comment by justinmk** [comment]
What's the status of this now that #3753 is merged?

**Comment by watiko** [comment]
`OptionSet` is triggered

**Comment by watiko** [comment]
Of course `OptionSet` is also not triggered through `buffer_set_option()` and `window_set_option()`.
Hmm, I think, `aucmd_prepwin()` (no existence) is required.

**Comment by justinmk** [comment]
For reference:

- The first 2 tests (which are calling vimscript via `helpers.execute() .. nvim_input()` ) succeed.
- The last one (which uses direct API) fails.

> However nvim will execute autocmds when we set option globally through vim_set_option.

That seems like the bug to me. The API is generally low-level and isn't supposed to trigger the endless array of Vimscript side-effects. _Except_ if vimscript is invoked, e.g. via `nvim_eval()`, `nvim_input()`, and `nvim_command()`, possibly also `nvim_call()`.

I think the task here is:

1. Document the behavior of all API functions in light of the above.
2. Fix `nvim_set_option()` so that it is consistent with the behavior of `nvim_buf_set_option()`.

**Comment by justinmk** [comment]
@yagebu Any interest in looking at this since you are familiar with `nvim_set_option` ?

**Comment by yagebu** [comment]
Will do.
