### ISSUE TITLE
Buffer reappear after every start even when deleted with :bd

### ISSUE THREAD

**Issue by MaikKlein** [neovim/neovim#3781]
Buffer reappear after every start even when deleted with :bd or :bdelete or :%bdelete. Any idea what could cause this?

My config contains `set viminfo^=%`

**Comment by mhinz** [comment]
It's a bug in ShaDa (it's `'shada`', not `'viminfo'` in Neovim) that was fixed after the 0.1 release: https://github.com/neovim/neovim/commit/ec8e60a055d75d7c78242957c87f574e360273a2

Please try updating.
