### ISSUE TITLE
Add a soft wrap width option

### ISSUE THREAD

**Issue by JelteF** [neovim/neovim#3784]
Currently vim soft wraps lines at the width of the screen. I would like to have an option to specify a column width where should be wrapped so my full screen terminal is not filled with text.

**Comment by mhinz** [comment]
You mean.. `:h 'textwidth'`?

**Comment by JelteF** [comment]
No, that way it will hard wrap, adding a new line charactar, at that point. I want a width at which a long line will continue on the following line in vim, but without adding a new line. 

The only thing I can find that is related is this https://stackoverflow.com/questions/989093/soft-wrap-at-80-characters-in-vim-in-window-of-arbitrary-width
However, this resizes the terminal, which is not what I want. I want it to display an empty terminal on the rest of the screen.

**Comment by justinmk** [comment]
Just create a new vertical window, or use something like goyo.vim.

https://github.com/junegunn/goyo.vim

**Comment by glow12121** [comment]
As someone who edits long markdown texts on Neovim, I agree that soft-wrapping texts at a given line length is very useful functionality.

Something like `max-width` in html or `wrap_width` in Sublime Text.

Opening split windows is a workaround that isn't convenient.

Hope this functionality is added eventually: https://github.com/neovim/neovim/issues/4386

**Comment by codr1** [comment]
:lua vim.opt.columns = 120
