### ISSUE TITLE
Update documentation to include neovim port from Macports as an installation option in OS X

### ISSUE THREAD

**Issue by wladston** [neovim/neovim#3785]
Recently a port for neovim was released in Macports:

https://www.macports.org/ports.php?by=name&substr=neovim

This greatly facilitates building neovim in OS X for people who do not use Homebrew (like me), so I think it should be mentioned on neovim's build and install docs. I can make the pull request myself if you explain exactly what and how you would change.

**Comment by justinmk** [comment]
Awesome. But, no PR needed--you can edit the wiki directly:

https://github.com/neovim/neovim/wiki/Installing-Neovim
