### ISSUE TITLE
CTRL-C fails to interrupt autocmd loop

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#3789]
Sometimes my neovim just randomly hangs when I use mappings. Well i think it has to do with mappings but I'm not sure. So I decided to figure out how to reproduce it and it turns out it has something to do with mappings (not specific mappings, any mappings because it also has happened with other stuff). But this is how I've been able to reproduce it most of the time. It just seems to happen if I spam this mapping

```
    autocmd FileType vim nnoremap <expr> <leader>u getline('.') =~ '^\v\s*"\|^\s*$' ? '' : "I\"\<esc>j"
```

It checks if the current line is a comment or empty and if not it comments it out. So I spam it for a while and then add a number and it just magically hangs. This isn't 100% it's so random and has nothing to do with the mapping, its just magically been happening to me.

I tested on linux and OSX.

Here is a log from when I start neovim to once it hangs. It just keeps repeating those commands at the very bottom which leads to the hang. Anything else anyone needs to debug it I can likely provide. (its really long so it might take time to load)
https://gist.githubusercontent.com/nhooyr/4107226581edc8a1d38a/raw/9a88d1f1097fa756b28213166fd12a95fa68b968/log

**Comment by nhooyr** [comment]
ok well I got it it happens if I type \5 (\ is my leader). seems to be related to a plugin. ill close this issue.

**Comment by ZyX-I** [comment]
@nhooyr If Neovim hangs due to the plugin, but the plugin cannot be interrupted by `<C-c>` then this has good probability of being a Neovim bug, possibly triggered by a plugin bug.

**Comment by nhooyr** [comment]
It cannot be interrupted, I'll reopen it.

**Comment by nhooyr** [comment]
Confirmed neovim bug, the exact same vim config works perfectly without the hang.

**Comment by vimeitor** [comment]
You can also add kien/ctrlp.vim to the list. It's not possible to C-c it while searching in a directory with a lot of files.

**Comment by nhooyr** [comment]
I think I found another related bug. This time you press <ESC><NUM>dd where <NUM> is any number. It freezes neovim and you cannot exit with control-c. I'm not sure if its related to plugins or what. I can get control back after a while, not something I press, it just magically gives me back control. It is something related to my config though for sure. I'll look into the exact reasons once I get home tonight.

**Comment by mattsawyer77** [comment]
Maybe not too helpful, but I just installed neovim 1.1 (also tried HEAD, same behavior) on arch and am having issues with hangs. I have the exact same config on a Mac but have never seen a hang there.

**Comment by justinmk** [comment]
@nhooyr Is this still an issue? Can you narrow it down?

**Comment by nhooyr** [comment]
I've got no idea, I haven't encountered it since. I'll try and reproduce soon.

**Comment by kazuoteramoto** [comment]
I still have random hangs, just got one. I could not reproduce with the minimal examples in this thread. Its usually happens when exiting from insert to normal using ESC. Its just hangs, without any extra CPU or I/O usage. Its hangs for several seconds. Its also usually with modified files (buts this is probabily related to the fact that its hangs when exiting insert).

Most of my hangs is when editing long .tex files but this can be just because I spent much more time on those.

**Comment by justinmk** [comment]
@kazuoteramoto Are you sure this isn't https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed ?

In general, "me too" reports without exact version number and reduced test cases aren't helpful. Especially since you mentioned the steps have nothing to do with this report.

**Comment by kazuoteramoto** [comment]
I don't use tmux. I replied because you asked if this still happens. I will delete my comment was it not relevant.

**Comment by justinmk** [comment]
@kazuoteramoto what's 'ttimeoutlen' and 'ttimeout'? Try `set ttimeoutlen=50`. (notice _two_ t's)

**Comment by timfeirg** [comment]
I'm able to reproduce this using [my vimrc](https://github.com/timfeirg/workspace-setup/blob/master/.nvimrc), neovim almost always freezes after opened up for a relatively short period of time.

And if I use the `:PlugUpdate` command within neovim, there's very high chance that it hangs immediately.

I've tried to determine whether it's the plugins, or the vim configs, but I really can't narrow it down to produce a minimum `.nvimrc` that can firmly reproduce this issue. I tried to disable the plugins one by one, remove the configuration lines block by block, every time I thought I'm close, neovim starts to randomly hang.

I've tested this under:

* NVIM v0.2.0
* NVIM v0.2.1-dev

**Comment by petobens** [comment]
@timfeirg see https://github.com/neovim/neovim/issues/6950

**Comment by justinmk** [comment]
I've updated the title of this issue, it's not related to #6950. See https://github.com/neovim/neovim/issues/3789#issuecomment-162176671

**Comment by yakschuss** [comment]
I just started using Neovim, noticed that it's hanging as well. I'm _sure_ that's not helpful, but I also don't understand what's happening.

**Comment by nhooyr** [comment]
Since we don't have a definite repro and its been 2.5 years, going to close.

**Comment by nhooyr** [comment]
I have also not encountered this since.

**Comment by chunkhang** [comment]
> You can also add kien/ctrlp.vim to the list. It's not possible to C-c it while searching in a directory with a lot of files.

I face the same issue with ctrlpvim/ctrlp.vim as well.
