### ISSUE TITLE
Terminal output closes Completion menu

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#3792]
The Completion menu will close when standard out/error is sent to a terminal buffer.

Repro steps
- open neovim
- terminal bash
- `while :; do echo foo; done` 
- switch back to text buffer and try to open completion menu. It will open and close very quickly try with sleep 1 so you can actually see it open

NVIM `0.1.0 (compiled Nov 26 2015 23:44:21)`

**Comment by justinmk** [comment]
I believe this is the same issue as https://github.com/neovim/neovim/issues/3416 . I re-titled that issue to help with finding it.
