### ISSUE TITLE
cursor does not match cursorcolumn

### ISSUE THREAD

**Issue by jiajunhuang** [neovim/neovim#3794]
steps to reproduce it:
:set cursorcolumn
:help intro
:421
wwwww

**Comment by mhinz** [comment]
It happens because of concealed characters from the `help` filetype. It's the same in Vim.

I'll have a look.

**Comment by chrisbra** [comment]
Hm, as far as I can see, the mentioned patch does not fix this issue. I think this is another one of the conceal bugs still open in Vim

**Comment by zeertzjq** [comment]
Closing as there is no mention of what the expected behavior should be.
