### ISSUE TITLE
Brew Install Problem

### ISSUE THREAD

**Issue by JamesPinkerton4** [neovim/neovim#3797]
I'm using a mac. I ran brew install neovim/neovim/neovim and got the following problem:

Error: undefined method `desc' for Formulary::Formulae::Neovim:Class
Please report this bug:
    http://git.io/brew-troubleshooting

I tried to nvim <filename> after and nothing happened. The wiki says the binary is called nvim?

**Comment by justinmk** [comment]
Did you read http://git.io/brew-troubleshooting?

Also, please report brew issues at https://github.com/neovim/homebrew-neovim
