### ISSUE TITLE
[FIXED]  UpdateRemotePlugins fails with an exception 

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3800]
my os is ubuntu 
i install neovim by these commands
```shell
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
sudo apt-get install python-dev python-pip python3-dev python3-pip
```
use this two command intall my py client

`sudo pip2 install  neovim`

pip2 install ok

`sudo pip3 install  neovim`

pip3 install get error https://github.com/neovim/neovim/issues/3510

fixed by `sudo apt-get install python3.5-dev`

~/.config/nvim/init.vim
```vim
let g:python_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/bin/python3'
if 0 | endif
if has('vim_starting')
    if &compatible
        set nocompatible               " Be iMproved
    endif
    set runtimepath+=~/.config/nvim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.config/nvim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/deoplete.nvim'
let g:deoplete#enable_at_startup = 1
let g:JavaComplete_UseFQN = 1
call neobundle#end()
filetype plugin indent on
NeoBundleCheck
syntax on
```
then get the same error as https://github.com/neovim/neovim/issues/3749
```
Vim(let):E903: Could not spawn API job
Error detected while processing function <SNR>43_UpdateRemotePlugins..<SNR>43_RegistrationCommands..remote#host#Require..<SNR>43_RequirePythonHost:
line   21:
E605: Exception not caught: Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be
 available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
Error detected while processing function <SNR>43_UpdateRemotePlugins..<SNR>43_RegistrationCommands..remote#host#Require:
line   10:
E171: Missing :endif
Error detected while processing function <SNR>43_UpdateRemotePlugins:
line    5:
E171: Missing :endif

```
then i checked my python version in command line
i find python3's version is python3.4
![2015-12-07 21-37-34](https://cloud.githubusercontent.com/assets/13142418/11628158/c05725be-9d2a-11e5-9600-1fff1982a702.png)
so i do this 
![2015-12-07 21-51-20](https://cloud.githubusercontent.com/assets/13142418/11628452/b39089a4-9d2c-11e5-822c-42ebef98d726.png)
after this python and python3 in command line show 
![2015-12-07 22-21-37](https://cloud.githubusercontent.com/assets/13142418/11629086/e8607794-9d30-11e5-905b-496a335f61f3.png)
then update init.vim and can use UpdateRemotePlugins
![2015-12-07 22-22-57](https://cloud.githubusercontent.com/assets/13142418/11629117/23efb1c6-9d31-11e5-928e-448db279f66e.png)

**Comment by wsdjeg** [comment]
@Shougo i have finished it ,can you have a check

**Comment by wsdjeg** [comment]
deoplete works well
![2015-12-07 22-24-31](https://cloud.githubusercontent.com/assets/13142418/11629146/583c81ca-9d31-11e5-9189-a94786cb5642.png)

**Comment by justinmk** [comment]
@wsdjeg If this is [FIXED] please close the issue.

**Comment by wsdjeg** [comment]
ok i close it
