### ISSUE TITLE
ubuntu installation without clipboard support

### ISSUE THREAD

**Issue by s-mage** [neovim/neovim#3808]
Hi!

I installed nvim via ubuntu ppa (as in wiki), tried to copy to clipboard, but it doesn't work.
I tried to `:help nvim_clipboard` but `Sorry, no help for nvim_clipboard`.

It's not related to clipboard, but I have the same with python plugin support, `no help for nvim_python`.

```
s@yoga:~$ nvim --version
NVIM 0.1.1 (compiled Dec  6 2015 21:23:33)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/build/config -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/src -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-RTAy33/neovim-0.1.0ubuntu1+git201512061515+2035+15~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-18

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by Pyrohh** [comment]
I think there's something wrong with your installation, as the `:help` command+args you've provided works fine on my system.

**Comment by Pyrohh** [comment]
Does it still happen with `nvim -u NONE`? Is the environment variable `VIMRUNTIME` set to anything? Try unsetting it if so.

**Comment by s-mage** [comment]
Yes, it still happens with `nvim -u NONE`. And `VIMRUNTIME` is not set.

**Comment by s-mage** [comment]
And no `:help vim-differences` too, btw. I suspect there is no nvim-related help at all.

**Comment by mhinz** [comment]
There's no env variable, but within nvim you can refer to it, right?
```
:echo $VIMRUNTIME
```
`:h vim_diff` would look for this file `:e $VIMRUNTIME/doc/vim_diff.txt`.

**Comment by s-mage** [comment]
@mhinz 

```
:echo $VIMRUNTIME
/usr/share/vim/vim74
```

wow! When I set 

```
export VIMRUNTIME=/usr/share/nvim/runtime/
```

all the help appeared. And clipboard started to work too. Awesome, thank you!

**Comment by wsdjeg** [comment]
fixd by `sudo apt-get install xclip`
@s-mage

**Comment by fwalch** [comment]
Related: #2977

**Comment by s-mage** [comment]
@wsdjeg no, it fixed by setting right runtime.
In fact, in my bashrc `VIM=/usr/share/vim` variable was set with comment `for neovim code completion`. I guess in earlier versions it was needed.

**Comment by wsdjeg** [comment]
the latest version nvim support system clipboard?
as the doc writes ,we need to istall xclip

**Comment by Shougo** [comment]
@wsdjeg neovim supports the clipboard feature.  But to use it, you must install the external commands like xclip.

**Comment by wsdjeg** [comment]
got it ,thanks,
