### ISSUE TITLE
bash vim mode

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#3810]
I like to use vim mode in bash by putting in .bashrc:
```
set -o vi
```
However, the input/normal mode in bash conflicts with nvim input/normal mode when opening a :term.

Has anyone though about this problem?

**Comment by ZyX-I** [comment]
@llpamies It cannot possibly conflict unless you created a mapping that translates `<Esc>` to `<C-\><C-n>`.

**Comment by llpamies** [comment]
My mistake. What does not work is the CTRL+W h to switch between split windows out of the bash. Bash is capturing the CTRL+W (delete word).

**Comment by justinmk** [comment]
@llpamies You can `:tnoremap <c-w> <c-\><c-n><cw>` or you can just escape from terminal ("insert") mode before using CTRL-W.
