### ISSUE TITLE
[Backwards Incompatability]: ttimeout

### ISSUE THREAD

**Issue by dsimmons** [neovim/neovim#3815]
**Observed in:** NeoVim 0.1.0
**OS:** Likely affects all operating systems, but verified on OSX.
**Environment:** Independent of the terminal and/or terminal multiplexer used.

Related, continuation of #2017.

#### Context

In vanilla Vim, there's a built-in ~1s delay following a keycode (`:h keycodes`) to, for instance, allow for `keycodes` to be used in mappings. In particular, `<ESC>` is one of those `keycodes` (related: `:h esckeys`).

**To observe:** In INSERT mode, hit `<ESC>` to exit and immediately follow it up with `<SHIFT>+O` to re-enter INSERT mode on the line above. On my terminal, a capital "O" appears momentarily, followed by a ~1s delay, and finally the desired action taking place.

To "solve" (avoid) this, one of the most common practices is to enable the `ttimeout` setting and to set `ttimeoutlen` to be very short (commonly < 250ms). For instance, see [the relevant line](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L28) in [tpope's vim-sensible](https://github.com/tpope/vim-sensible).

#### Enter NeoVim

Entirely independent of normal Vim, NeoVim doesn't have the aforementioned delay (for reasons that I don't completely understand). Thus, `ttimeout` and `ttimeoutlen` aren't necessary in pure NeoVim.

However, assuming that it ***is*** set -- for instance, having ported an existing `.vimrc` -- ***the resultant observed behavior is entirely different*** as compared to Vim.

**To observe:** In INSERT mode, hit `<ESC>` to exit, **immediately** followed by `j`. You should see that a special character (`ê`) is output as opposed to having exited INSERT mode and gone down a line.

#### Commentary

With the above said, I don't quite know what the best answer is.

At the very least, in the interest of an easy upgrade path for existing Vim users to migrate to using NeoVim, this difference should be more explicitly called out. Anecdotally, having had just made the transition myself, it threw me for a loop for quite a while before I realized what was happening.

Alternatively, @justinmk proposed that we don't allow this setting to be specified entirely.

Finally, on a related note (but far outside of the scope of a solution to this issue specifically), it might be worth having a utility like `brew doctor` at our disposal to alert (especially new) users of settings that aren't 1:1 in NeoVim. I could imagine various warning levels:

1. Settings that are no longer necessary in NeoVim and/or that have no effect.
2. Settings that have ***different*** behavior in NeoVim.
3. Settings that have been ***removed*** in NeoVim.

This may could be in *addition* to what's located in the docs (as far as highlighting differences) and/or any warnings/errors thrown at runtime. So it'd really just be a quick, easy sanity check -- that way, you'd get a blatantly obvious "CAUTION: You're likely to encounter issues if you proceed as-is.".

Again, outside of this issue specifically (but it as one instance of where a utility like this may help), I can't imagine this is the last time we'll see some way in which Vim and NeoVim don't behave exactly the same. For any such cases, there may not be a simple solution that can be resolved without the user's involvement. I'd personally much rather NeoVim defer to me to correct inconsistencies versus "fixing them for me" (eg. turning something off) and potentially altering my user experience in an unexpected way.

Just a thought :smile:

**Comment by tmcw** [comment]
To distill the previous conversation about this issue, what's the current recommended workaround for this issue?

**Comment by justinmk** [comment]
@tmcw https://github.com/neovim/neovim/wiki/Troubleshooting#pressing-esc-when-running-nvim-in-tmux-or-gnu-screen-inserts-characters

**Comment by tmcw** [comment]
What about if you aren't using tmux or screen, and using iTerm2?

**Comment by dsimmons** [comment]
@tmcw: Per my local testing previously, this issue not only occurs outside `tmux` and `screen` both, but I can *also* reproduce it consistently in `Terminal.app` (as opposed to `iTerm2`).

**Comment by dsimmons** [comment]
Apologies, this was resolved in the originating thread (#2017) and I forgot to close this!

:clap:
