### ISSUE TITLE
when the buffers is more than the weight of the windows,the colored background will disappear！

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3817]
here is the plugin link
https://github.com/bling/vim-airline
![2015-12-10 23-19-24](https://cloud.githubusercontent.com/assets/13142418/11719381/6befe8a4-9f95-11e5-9db9-063ecbfca13e.png)
![2015-12-10 23-19-30](https://cloud.githubusercontent.com/assets/13142418/11719380/6be6fe1a-9f95-11e5-922b-bebcbd49e574.png)

**Comment by wsdjeg** [comment]
@bling
can you fix this ,I find it works well in vim

**Comment by justinmk** [comment]
Is this not a duplicate of #3763 ?

**Comment by wsdjeg** [comment]
a litter different,but can be closed ,i will waitting @3763 been fixed

**Comment by wsdjeg** [comment]
has not been fixed ,my version is NVIM 0.1.1 (compiled Dec 10 2015 15:24:08)

**Comment by wsdjeg** [comment]
fixed  thanks
