### ISSUE TITLE
how to start a neovim java plugin?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3820]
is there any possible wirte an neovim plugin by java,for examplet open an java background servise ,and use the vim script,we can use some func comunication with this java service.and i find https://github.com/fdinoff/neovim-java-client this project has not update,and 
the auther also do not know how to use
https://github.com/fdinoff/neovim-java-client/issues/6

**Comment by brcolow** [comment]
The neovim-java-client that you linked is your best bet. It is not true when you say "the auther also do not how to use". The author of neovim-java-client attempted to help you but as usual your responses were confusing, vague, and seemingly haphazardly put together. neovim-java-client allows you to call into the Neovim API via msgpack-rpc, as all the API clients do (or at least attempt to) listed on the Wiki "Related Projects Page".

**Comment by wsdjeg** [comment]
sorry for misunderstand,i will read more info about it ,

**Comment by wsdjeg** [comment]
ok let close this and  talk about it in the Java client repo
