### ISSUE TITLE
Starting neovim from terminal into existing neovim.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#3827]
I've got this basic thing:

```zsh
nvim() {
    if [[ -z $NVIM_LISTEN_ADDRESS ]]; then
        # not running inside nvim
        /usr/bin/nvim "$@"
    else
        python -c "from neovim import attach; nvim = attach('socket', path='$NVIM_LISTEN_ADDRESS'); nvim.command('tabnew $1');"
    fi
}
```

It seems to always open files relative to my home dir. It also can only accept arguments for the edit command.

Is there a more robust version somewhere?

**Comment by trusktr** [comment]
Alright, here's a slightly better one that opens a file relative to the pwd of the shell if it's no an absolute path.

```py
nvim() {
    if [[ -z $NVIM_LISTEN_ADDRESS ]]; then
        # not running inside nvim
        /usr/bin/nvim "$@"
    else
        python -c "from neovim import attach; import os; file = '$1'; file = file if file.startswith('/') else '$(pwd)/'+file; nvim = attach('socket', path='$NVIM_LISTEN_ADDRESS'); nvim.command(\"tabnew %s\" % (file));"
    fi
}
```

**Comment by ZyX-I** [comment]
@trusktr You must not use `$1` or any other `$…` like this: there are loads of values which will break your code. For passing arguments to Python there are two variants: `NEOVIM_LISTEN_ADDRESS` may be accesses via `os.environ` dictionary. Current working directory is accessed using `os.getcwd()`. Other arguments may be passed like you pass them to `nvim` (`"$@"`) and accessed via `sys.argv`.

Note that directory named literally `/home/trusktr/', __import__('shutil').rmtree('\x2Fhome\x2Ftrusktr'), '` is a valid directory name. Also I have seen and created loads of normal files with names which contain `'` inside.

**Comment by trusktr** [comment]
> Current working directory is accessed using `os.getcwd()`

That's what I thought, but it doesn't. I tried changing the pwd with `os.chdir('$(pwd)')`, but the result is the same always: nvim reads the path from my home folder, and I'm guessing this is because the parent nvim (which is already running when I'm trying the commands) has started in my home folder. So, as a workaround, that's why I'm doing

```py
file = '$1'; file = file if file.startswith('/') else '$(pwd)/'+file;
```

and then the parent nvim opens the absolute path that I'm giving it (instead of the relative path).

You're right, this all fails when I do something like `nvim -u NONE`, and then it tries to edit a file called "-u". But, oh well, I almost never type anything other than a file name when I use the `nvim` command, so this at least works the vast majority of the time in my case.
