### ISSUE TITLE
neovim captures Shift-insert paste into terminal of suspended instance

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#3828]
When you copy something into the primary clipboard inside nvim, suspend it to get to the terminal you're running in, and then paste with Shift-insert or Middle click, the text is not printed on the command line, and neovim seems to interpret the text as a macro.

Steps to reproduce:

- open nvim with "nvim -u NONE"
- type the string "this is a test" in that buffer
- yank the substring "is a test" into the '*' register
- suspend that instance of nvim
- attempt to paste the string into the same terminal with Shift-insert or Middle click

Observations:
- Text does not appear at the command prompt
- when bringing nvim back into the foreground the string "s a test" has been inserted into the file

Version:
```
NVIM 0.1.1 (compiled Dec  5 2015 22:03:57)
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.1/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

System:
`4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

I've been using xterm, but gave it a quick check with two random other terminal emulators -- roxterm and termite -- and observed the same symptoms.

I apologise I haven't tested this on the latest version, or found which commit started this behaviour, but the binary from a default 'make'  wouldn't allow yanking to the X clipboards, and I'm feeling rather lazy right now.

**Comment by bfredl** [comment]
I suspect this is analogous to #3895, provider is suspended when nvim is, might be fixed by #3944 .

**Comment by bfredl** [comment]
Should be fixed now, reopen if still problem.

**Comment by hardenedapple** [comment]
It doesn't seem to be solved -- I'm seeing the same problem on commit 297075bf47d09437deb82266c61cd830dc8d72eb

I don't think I can reopen it -- do you mind doing that?
Thanks.

**Comment by bfredl** [comment]
Which one of `xsel` and/or `xclip` do you have?

**Comment by hardenedapple** [comment]
I have `xsel`, but I've attempted with `xclip` and seen the same results.

**Comment by bfredl** [comment]
Hmm, I cannot reproduce, neither with `<c-z>` nor `:suspend`. I tried `xterm` and `urxvt`. The relevant logic is actually in libuv. If you `make distclean && make` and try again do you still see it?

**Comment by bfredl** [comment]
And another thing: are you sure you are using master runtime files and not older installed runtime?

**Comment by hardenedapple** [comment]
You're right --- my mistake -- I was using the older installed runtime.

Thanks.
