### ISSUE TITLE
Incomplete detection of tex files

### ISSUE THREAD

**Issue by beoldhin** [neovim/neovim#3829]
I have a latex project with multiple .tex files and use \include{} to include subfiles. Vim detects all the tex files, however neovim detects only the main file having the includes (subfiles have only \chapters and \sections).

I did the folllowing: "diff /usr/share/nvim/runtime/filetype.vim /usr/share/vim/vim74/filetype.vim" and the output lists multiple differences, including the "let lpat" which looks suspicious (simpler) for this case. Is neovim using some old file?

I am using the latest neovim from ppa.

**Comment by justinmk** [comment]
Yes, we're behind on runtime updates.

See:

- doc: https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim
- example: https://github.com/neovim/neovim/pull/2659
