### ISSUE TITLE
Vim-plug plugin update doesn't finish

### ISSUE THREAD

**Issue by beoldhin** [neovim/neovim#3830]
I've used "vim +PlugUpgrade +PlugUpdate +qall" and it has worked: it waits until all the plugins have been updated and it returns to the command line after that. When I use it with nvim, the +PlugUpgrade works but when it reaches the +PlugUpdate part, the window is prematurely closed and the control is given back to the command line (no errors reported). The same however works in interactive mode (":PlugUpdate" written in nvim): window is not closed too soon.

I've used latest nvim from ppa in this test.

**Comment by justinmk** [comment]
See https://github.com/junegunn/vim-plug/issues/104
