### ISSUE TITLE
Lost syntax highlighting, something wrong with runtimepath

### ISSUE THREAD

**Issue by JayBusch** [neovim/neovim#3840]
Somewhere along the way into my new excursion into neovim I have lost my syntax highlighting.

I don't think I did anything extreme enough to warrant this and I feel I've exhausted my abilities to debug it in a timely fashion so I will ask for help here.

The symptoms are that as I said, syntax highlighting stopped working.  Executing nvim with -V9 produces a log file that contains the following error:

```
line 13: sourcing "/usr/local/share/nvim/runtime/ftoff.vim"
Error detected while processing /usr/local/share/nvim/runtime/ftoff.vim:
line   11:
E216: No such group or event: filetypedetect *
finished sourcing /usr/local/share/nvim/runtime/ftoff.vim
continuing in function plug#end
```

and then proceeds to do a lot of searching for ftoff.vim and then filetype.vim.

It includes looking in the folder /usr/local/share/nvim/runtime which is where I have confirmed these files to exist, and that path and all the others included in that particular search are part of runtimepath as retrieved by :set runtimepath

I'm not sure why it is not finding files that are clearly there and don't appear corrupt to the naked untrained eye; but I am very frustrated getting my neovim setup nearly ready for production use and suddenly having this critical (to my sanity) feature suddenly disabled.

Here is my entire ~/.config/nvim/init.vim as well in case it will help anyone willing to help me.  I have uninstalled each of my plugins one at a time and tested in between to try and isolate if any of them are to blame and the problem persists no matter what is installed.

```
colorscheme darkblue
call plug#begin('~/.config/nvim/autoload/plugged')
Plug 'critiqjo/lldb.nvim'
Plug 'scrooloose/nerdtree'
Plug 'https://github.com/benmills/vimux.git'
Plug 'https://github.com/jalcine/cmake.vim.git'
Plug 'https://github.com/rhysd/vim-clang-format.git'
call plug#end()
```

**Comment by mhinz** [comment]
```
call plug#begin('~/.config/nvim/autoload/plugged')
```
should probably be
```
call plug#begin('~/.config/nvim/plugged')
```

**Comment by JayBusch** [comment]
That may be correct, and I have now switched it to your suggestion as well as ran :PlugInstall in order to install my plugins at that path, but my syntax highlighting still doesn't work and the output from nvim -V9 has not changed.  Thank you for the suggestion though.

**Comment by JayBusch** [comment]
Well... the culprit seems to be......

```
colorscheme darkblue
```

Commenting out that line restores my syntax highlighting, so does switching to it or any other colorscheme besides default.

I think this is still a bug, but at least my life can continue.

**Comment by Pyrohh** [comment]
I can't reproduce this using nvim version 158dc2b7a74a2eafbac76ad16ebac45185a3fdcd and the latest vim-plug; is the issue still present after running `:PlugUpgrade`?

Anyways, vim-plug does some stuff related to `filetype` during initialization, so I wonder if that's related to it. What happens if you put `colorscheme` after `call plug#end()`?

**Comment by JayBusch** [comment]
My nvim is a pull from HEAD:master right before I opened this ticket.   I just now, per your suggestion, called PlugUpgrade and it seemed to upgrade vim-plug; and after restarting nvim I had syntax highlighting (there is no coloscheme call in my init.vim file at all now), but when using the command ```:coloscheme darkblue``` I immediately lost syntax highlighting again.  Obviously the command comes after all of init.vim has been processed including ```call plug#end()```.

**Comment by ajpaulson** [comment]
the darkblue colorscheme has:
```
if exists("syntax_on")
	syntax reset
endif
```
near the start (as do several of the colorschemes in runtime) - does this behaviour happen with any of the shipped colorschemes or _only_ darkblue?

**Comment by justinmk** [comment]
Cannot reproduce. Does it happen in Vim? 

Please try vi.stackexchange.com for usage questions.
