### ISSUE TITLE
Autocommand for buffer change event

### ISSUE THREAD

**Issue by erf** [neovim/neovim#3843]
I can't find an autocommand for buffer change event. I would like to use neomake to lint on every change i do to the buffer.

**Comment by justinmk** [comment]
`TextChanged` and `TextChangedI` are probably the closest thing. But usually linters inspect the contents of the file-on-disk, so you should really invoke Neomake on save (`BufWrite`).

**Comment by erf** [comment]
So i need to save file on TextChanged and then call neomake ?

**Comment by justinmk** [comment]
No. For general Vim usage questions try http://vi.stackexchange.com/
