### ISSUE TITLE
Neovim does not recognize enter key from windows console

### ISSUE THREAD

**Issue by RedX2501** [neovim/neovim#3850]
While trying out the latest version from equalsraf appveyor build I could not start neovim, problems with my configuration:
```
Error detected while processing C:\Users\uidw8099\AppData\Roaming\nvim\init.vim:
line   90:
E484: Can't open file d:\Playground\neovim\Neovim\bin\syntax\syntax.vim
line  563:
E185: Cannot find color scheme 'zenburn'
Press ENTER or type command to continue
```

Everything is fine and I understand why i get the message.

But i cannot make it continue, I can press the ENTER key as much as I want in the windows console it will not read it.

**Comment by equalsraf** [comment]
Console support is currently broken in Windows. Messages will be printed to stdout, but no input is accepted.

There should be a warning message in the console about this, but since the input is stuck an error its not being printed - i.e. its being printed too late.

**Comment by justinmk** [comment]
See #810 for progress on Windows.
