### ISSUE TITLE
Opening a directory in python opens a buffer

### ISSUE THREAD

**Issue by danihodovic** [neovim/neovim#3853]
First of all this isn't neovim specific behaviour, it happens in vim too.

If I open a directory by using `:e dir` it opens up a directory like selector where I can choose what file I'd like to open. If I do this in python by `:py vim.command('e dir')` it opens that directory as a buffer.

![vim-dir-py2](https://cloud.githubusercontent.com/assets/5557301/11838026/b8bc0ae8-a3e4-11e5-9bf5-4a5f75e070d8.png)
![vim-dir-py2](https://cloud.githubusercontent.com/assets/5557301/11838059/ecc4acaa-a3e4-11e5-9096-058cf0677713.png)

**Comment by mhinz** [comment]
This issue should be re-opened here: https://github.com/neovim/python-client

FWIW, it's the same behaviour in Vim.

When you do `:e /tmp`, the netrw plugin is used. My guess is that the python provider doesn't take plugins into account.

**Comment by justinmk** [comment]
> Or maybe it's autocmd related. 

It's that. netrw (and any other directory browser plugin) works by listening to BufEnter.

**Comment by danihodovic** [comment]
So there is no way to have netrw work when opening a directory in python?

**Comment by justinmk** [comment]
@danihodovic After the `:e dir` command, you could force the BufEnter event via `:doautocmd BufEnter`.

I am not sure if there is a reason we don't want autocmds firing via the API. I know that, for example, we intentionally disable them for API methods like `get_lines`.

**Comment by danihodovic** [comment]
@justinmk Thanks!
