### ISSUE TITLE
<c-l> inside tmux difference between neovim and vim.

### ISSUE THREAD

**Issue by KKPMW** [neovim/neovim#3854]
I noticed that neovim and vim behave differently when trying to do `<c-x> <c-l>` (line completion) inside of tmux. Vim seems to work fine, while in neovim `<c-l>` is interpreted as tmux shortcut rather than neovim command.

Is this expected behavior or a minor bug?

**Comment by justinmk** [comment]
Can't reproduce. Need more details.

**Comment by KKPMW** [comment]
False alarm. Tracked it down to leftovers from vim in my tmux-config:

    # Smart pane switching with awareness of vim splits
    is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|vim|ssh|mosh?)(diff)?$"'
    bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
    bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
    bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
    bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
    bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

Removing these lines solved the issue. My mistake.

**Comment by justinmk** [comment]
No problem, thank you for the followup!
