### ISSUE TITLE
Very slow when using colorschemes

### ISSUE THREAD

**Issue by stantonnet** [neovim/neovim#3861]
Hey, 

Issue I am seeing is that with any colorscheme I am seeing a lot of slowness when scrolling up/down to a new page. 

Plugins:
```
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh'  }
Plug 'fatih/vim-go', { 'for': 'golang' }
Plug 'morhetz/gruvbox'
call plug#end()
```
nvim --version
```
NVIM 0.1.1 (compiled Dec 17 2015 11:33:29)
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20151217-48103-zj7c56/build/config -I/tmp/neovim20151217-48103-zj7c56/src -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/tmp/neovim20151217-48103-zj7c56/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20151217-48103-zj7c56/build/src/nvim/auto -I/tmp/neovim20151217-48103-zj7c56/build/include
Compiled by john@john-mbp.stantonnet.com

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by nicolaiskogheim** [comment]
> scrolling up/down to a new page

Do you mean scrolling in a freshly opened buffer?

**Comment by stantonnet** [comment]
No,  I have a 100 line script. When I start scrolling down the off screen text loads really slow.  I have tried going all the way to the bottom and scrolling up and its the same.

**Comment by nicolaiskogheim** [comment]
Does this happen if you run nvim without plugins? If not, try with one plugin at a time, and see if it's one of them causing it.

`nvim -u NONE` to run nvim without vimrc.

**Comment by stantonnet** [comment]
```nvim -u NONE``` works great. 

I remove the colorscheme plugin and everything is great. But as soon I use use a colorscheme(plugin/adding directly to colors dir) it slows down. I have tried 3-4 schemes.

**Comment by justinmk** [comment]
Which color scheme precisely? Please provide URL.

**Comment by justinmk** [comment]
Does it happen with all colorschemes? Or only specific ones?

**Comment by stantonnet** [comment]
Seems with all schemes. I have tried the below so far. 

https://github.com/morhetz/gruvbox
https://github.com/freeo/vim-kalisi
https://github.com/sickill/vim-monokai

Plus a few others that I cant remember.

**Comment by mseeber** [comment]
Does that happen with the colorschemes enabled but syntax highlighting turned off?

**Comment by stantonnet** [comment]
Yes it still happens with syntax is set to off.

**Comment by justinmk** [comment]
What terminal (including version)? Did you try another terminal?

**Comment by stantonnet** [comment]
iTerm2 Build 2.9.20151213-nightly

With the native terminal app it is actually worse.. very slow opening.

**Comment by wsdjeg** [comment]
do you tried gnome terminal it works well for me

**Comment by stantonnet** [comment]
No, I am using a mac.

**Comment by justinmk** [comment]
What does `:echo $TERM`  report?

**Comment by stantonnet** [comment]
xterm-256color

**Comment by justinmk** [comment]
Out of ideas. 

Does it happen in Vim?

**Comment by stantonnet** [comment]
Nope, it works fine in vim.

**Comment by stantonnet** [comment]
So, I just rebooted and its working fine now. No delays. 

Thanks for all the suggestions.

**Comment by pbassut** [comment]
I'm having this issue when using badwolf color scheme. As soon as I disable it, nvim runs pretty damn fast.

**Comment by mzavoloka** [comment]
That's actually a hard-to-catch bug in original vim (or its interoperation with X).

I had this issue in xfce with any terminal when maximizing or side-docking a window with already opened original vim inside it.
While moving cursor, in htop this xorg process starts taking a lot of CPU:
`/usr/lib/Xorg -nolisten tcp :0 vt1`
After maximizing a terminal window you start experiencing this lag, and you can stop the lag by either:
1. supend vim with Ctrl+Z
2. Alt+Tab to another application
3. go to another workspace and back
And voila, your vim again works smoothly.

So, to reproduce it, try these steps:
0. Ensure you have a setting in your ~/.vimrc like `color default` (any colorscheme) and that your $TERM is not 'vt100'.
1. Open new terminal window
2. Open any file with vim that has few rows inside
3. Maximize window with a hotkey or dock window to left/right with a hotkey
4. Try moving your cursor around with j,k

The lag doesn't appear if you have $TERM variable set to vt100. All other setting like xterm, xterm-256-color, rxvt, rxvt-unicode, konsole, ... etc. lead to this lag.
Also the lag doesn't appear if you don't have any colorscheme setting in your ~/.vimrc. So, it looks like a colorscheme setting bug.

Just don't know where to find a solution to this bug, just posting a problem here...

**Comment by mzavoloka** [comment]
Oops, sorry for saying 'any terminal', just tested it with in xterm and it has no lags.
The lags appear in xfce4-terminal and urxvt.
Super strange bug, so hard to detect it ))
