### ISSUE TITLE
:terminal buffer keeps its dimensions in another tab 

### ISSUE THREAD

**Issue by firedev** [neovim/neovim#3864]
I am using `:term` quite extensively, thank you for that.

However given 2 tabs with *the same* terminal buffer in each, the buffer doesn't extend into the area marked with `::::::::` in the second tab even if there is no horizontal split.

I know tmux is limiting the window area when there are clients with different terminal size are connected. It is probably what is going on here too, but it would be cool to be able to use the full height for scrollback buffer if possible.

Thanks.

```
+------------+-----------+
| code       |           |
|            | $ term    |
|            +-----------+
|            | other     |
+------------+-----------+
```
```
+------------+-----------+
| code       |           |
|            | $ term    |
|            | ::::::::: |
|            | ::::::::: |
+------------+-----------+
```

**Comment by justinmk** [comment]
Seems related to https://github.com/neovim/neovim/issues/2514 ?

**Comment by firedev** [comment]
Oh yeah reflow would be great.

**Comment by trusktr** [comment]
This one *is* quite tricky. Question: how do we know when the terminal has static output, versus a program is redrawing stuff over and over in a specific size window (I.e. an ncurses app,a NeoVim instance, htop, etc). We can't have different size renderings of those apps unless those apps somehow support that themselves first).

**Comment by trusktr** [comment]
And, those apps would need to use the same API. "Hey app, render these three sizes then give me the output".

**Comment by justinmk** [comment]
A simple, partial solution to this is to resize the vterm terminal when a tab is switched-to. That won't help with the case of showing the same terminal in multiple splits in the _same_ tabpage, and it will be wonky if multiple clients are viewing the same terminal. But it fixes the common case.

**Comment by trusktr** [comment]
Good idea. If there's only one desktop window (one client) maybe it can just resize to the focused window, even if on the same tab.
