### ISSUE TITLE
Key mapping not working in neovim

### ISSUE THREAD

**Issue by balinterdi** [neovim/neovim#3865]
First of all, thank you for neovim. I switched over to it in about 10 minutes and all my plugins, settings and key mappings just kept working, except for one key mapping, which might be a bug or might just be me :)

I have the following few mappings in my config file to switch b/w panels a bit faster:

    "key mapping for window navigation
    map <C-h> <C-w>h
    map <C-j> <C-w>j
    map <C-k> <C-w>k
    map <C-l> <C-w>l

All of these are working except the <C-h>, it behaves like just pressing `h`, it moves the caret one char to the left. I have found out that there was a conflict with a mapping set by one of my plugins so I disabled that other one. Now, when I ask what key `<C-h>` is mapped to all I get is the above one:

    :map <c-h>  => <C-H> <C-W>h

And yet it does not work. All of the other movements do. It also does in plain vim.

Could you tell me what I'm doing wrong? Thank you.

**Comment by dylanaraps** [comment]
Possibly related to this: https://github.com/neovim/neovim/issues/2048

**Comment by balinterdi** [comment]
Thank you, indeed my issue seems like a duplicate of that one, so I guess this one can be closed.

**Comment by ilovejs** [comment]
how to map Up key in neovim ?
