### ISSUE TITLE
New VimL implementation incompatibilities

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#387]
Here I will list all incompatibilities between old and new VimL implementations. Some may be fixed, so it is also a place for discussion. Please discuss incompatibilities with separate issues in separate issues.

Full list was moved to https://gist.github.com/ZyX-I/4af839e000e7eada347d.

**Comment by snaz0211** [comment]
th translate.lua -model demo-model_epochX_PPL.t7 -src Quran/src-test.txt -output pred.txt
translate.lua: invalid argument for option -model: if set, the file must exist
Try 'translate.lua -h' for more information, or browse the documentation in the docs/ directory.

Kindly solve my problem. Suggest me the solution for it.

**Comment by bfredl** [comment]
Resolution: Neovim will use vim script with `scriptversion 1` unmodified. For better behaviors and performance, use lua.
