### ISSUE TITLE
UpdateRemotePlugins fails

### ISSUE THREAD

**Issue by LastSecondsToLive** [neovim/neovim#3870]
Similar to [Issue #3749](https://github.com/neovim/neovim/issues/3749) I get an exception while executing `UpdateRemotePlugins`.

I'm on a Mac and python2 and python3 is installed.
`which python` prints `/usr/local/bin/python`.
`which python3` prints `/usr/local/bin/python3`.
NeoVim is freshly installed via brew as well. 

Here you can see my python versions:
```
Matthias@MacBookPro ~/.config/nvim$ python
Python 2.7.11 (default, Dec  5 2015, 14:44:53) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
Matthias@MacBookPro ~/.config/nvim$ python3
Python 3.5.1 (default, Dec  7 2015, 21:59:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I currently try to install [lldb.nvim](https://github.com/critiqjo/lldb.nvim). My `~/.config/nvim/init.vim` looks like this: 
```
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

call plug#begin('~/.config/nvim/plugged')
Plug 'critiqjo/lldb.nvim'
call plug#end()
```

`echo has('python')` as well as `echo has('python3')` prints a `1`.
`py print(1+2)` and `py3 print(3+4)` work as well.

This is the error message I get, when I try to `UpdateRemotePlugins`:
<img width="1067" alt="screen shot 2015-12-20 at 1 49 33 am" src="https://cloud.githubusercontent.com/assets/16366523/11915921/3c7d7248-a6bc-11e5-852c-c6de506e7db0.png">

**Comment by Shougo** [comment]
> call plug#begin()

`call plug#end()`

Please update your neovim and your python/python3 neovim modules to the latest version.

`pip2 install neovim --upgrade`, `pip3 install neovim --upgrade`

**Comment by LastSecondsToLive** [comment]
Wow, that's what I call fast. The `

**Comment by LastSecondsToLive** [comment]
Wow, that's what I call fast. Sorry, the close and reopen was a mistake as well as the `begin()`-`end()` switch (I got it right in my `init.vim`). For the two python neovim modules updates I get: `Requirement already up-to-date`

**Comment by Shougo** [comment]
Your neovim binary seems not latest version.

**Comment by LastSecondsToLive** [comment]
How can I check this? How should I proceed? I installed neovim via brew today. Should I reinstall it with brew or via some other source?

**Comment by Shougo** [comment]
I recommend to build it manually.
https://github.com/neovim/neovim/wiki/Building-Neovim
It is easy than Vim.

**Comment by wsdjeg** [comment]
same as me .but i have fixed,it is due to you have diff version py3 or py2
https://github.com/neovim/neovim/issues/3800

**Comment by Shougo** [comment]
And lldb is installed?

In the FAQ in lldb.nvim

```
This plugin does not work / stopped working!!

    Try :UpdateRemotePlugins, and restart Neovim.
    Try running the test script test/run.sh, and see how it goes. If you encounter an error during import lldb, see this issue.
```

https://github.com/critiqjo/lldb.nvim/issues/6#issuecomment-127192347

**Comment by LastSecondsToLive** [comment]
@wsdjeg I don't think this is my problem. You updated python3.4.3 to python3.5. I already have python3.5.
@Shougo This seems really interesting. Indeed I get an error while running test/run.sh (lldb is installed though). I'll report in a few minutes!

**Comment by LastSecondsToLive** [comment]
@Shougo I'm really confused now. I just sat here for an hour looking for files/modifying paths and so on. I'm currently stuck at this comment: 

>Yay! But that's strange! When you import lldb, this file is executed: /usr/lib/python2.7/dist->packages/lldb/__init__.py, but _lldb.so is in /usr/lib/python2.7/dist-packages/lldb-3.6/ !!!
>Copy that link to /usr/lib/python2.7/dist-packages/lldb/_lldb.so and try importing again, if it works, try >:UpdateRemotePlugins
>
>Good luck!!

The previous step, was to find `_lldb.so`. I did with `locate`and found two files (different locations as in the comment, but the comment found two files as well). My paths are this:

```
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/Python/lldb/_lldb.so
/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/Python/lldb/_lldb.so
```

Do you understand what I should do next? I don't understand, what is meant with "`Copy that link..`".
I really hope to get this to work, I was already excited to debug inside of nevoid...

**Comment by Shougo** [comment]
Unfortunately, it seems not neovim issue.
You should create new issue in lldb.nvim and ask the author.

**Comment by LastSecondsToLive** [comment]
@Shougo Yeah, you are right. Should I close this thread now? Or would you prefer it to keep this open and I'll report back after I found a solution?

**Comment by Shougo** [comment]
I think to close it is better.
And if you find a solution, you can write the report.
