### ISSUE TITLE
why I can not use jobstart with java?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3872]
here is my Foo.java
```java
public class Foo{
    public static void main(String[] args){
    System.out.println("helloworld");
    }
}
```
I hava compile my java file 

job.vim

```vim
let s:save_cpo = &cpo
set cpo&vim

function! s:JobHandler(job_id,data,event) abort
      if a:event == 'stdout'
        let str = self.shell.' stdout: '.join(a:data)
      elseif a:event == 'stderr'
        let str = self.shell.' stderr: '.join(a:data)
      else
        let str = self.shell.' exited'
      endif
      echo str
endfunction

let s:callbacks = {
            \ 'on_stdout': function('s:JobHandler'),
            \ 'on_stderr': function('s:JobHandler'),
            \ 'on_exit': function('s:JobHandler')
            \ }

let job2 = jobstart(['java','-cp','/home/wsdjeg/.vim/bundle/Mysql.vim','Foo'], extend({'shell': 'shell 1'}, s:callbacks))

let &cpo = s:save_cpo
unlet s:save_cpo

```

vim -u NONE -S job.vim only show me  shell 1 exit

**Comment by ZyX-I** [comment]
@wsdjeg And running

    java -cp /home/wsdjeg/.vim/bundle/Mysql.vim Foo ; echo $?

works and echoes `helloworld\n0`? Also check whether

    java -cp /home/wsdjeg/.vim/bundle/Mysql.vim Foo &>/tmp/output </dev/null ; echo $?

works and echoes `0` and puts `helloworld` to `/tmp/output`. (Though </dev/null is not correct to emulate `job*`, this should not matter with your specific program and redirecting stdin is there to make no standard streams be connected to a tty because `jobstart()` will not use a tty.)

**Comment by wsdjeg** [comment]
my os is ubuntu ,and i am using gnome-terminal,
i just want to get the output of my java app,

**Comment by ZyX-I** [comment]
@wsdjeg ? This does not answer the questions. If these commands do not work in terminal this is not a neovim issue.

**Comment by wsdjeg** [comment]
ok i think every thing is in this pic
![2015-12-20 23-53-14](https://cloud.githubusercontent.com/assets/13142418/11918652/e7161922-a774-11e5-8e5e-1aa360ad922c.png)

**Comment by ZyX-I** [comment]
@wsdjeg There is another idea: check value of `$PATH` in both shell and neovim. Both need to contain path to java executable (found by `which java`).

**Comment by wsdjeg** [comment]
terminal:
echo $PATH
```
/home/wsdjeg/tools/android-sdk-linux/tools:/home/wsdjeg/tools/android-sdk-linux/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/wsdjeg/.fzf/bin
```
which java show `/usr/bin/java`

neovim:

:echo $PATH 
same as terminal

: echo system('java Foo')   show helloworld

**Comment by ZyX-I** [comment]
@wsdjeg Actually I should have asked you to test another thing: replace `echo str` with `echomsg str` and check whether callback was run with `messages` and *not* by checking what it displays right away.

I mean that *everything works fine*. But you are using invalid way to test how it works.

**Comment by ZyX-I** [comment]
Specifically doing two echoes in a row means that second echo will overwrite message from the first. Reproduced by e.g.

    fu T()
        echo col('.')
    endfu
    nnoremap <expr> T T()
    execute "normal" "iabc\eTT"

: will show `1` in place of `3` because second `T` overwrites result from the first.

**Comment by wsdjeg** [comment]
sorry :msg show me 
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"autoload/mysqlvim/job.vim" 23L, 667C
 stdout: helloworld
 exited
```

**Comment by ZyX-I** [comment]
@wsdjeg Which clearly shows you that callback was run correct number of times.
