### ISSUE TITLE
vertical split like newspaper columns style

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#3896]
Sometimes I write long Latex files in VIM and I found it annoying not having more vertical space to be able to easily move my eyes around the chapter I working on. So what I do is to split the window vertically, and split the chapter between the two splits as I show here:
![existing-vs](https://cloud.githubusercontent.com/assets/452871/11984647/d09d7222-a971-11e5-9c63-7eeba251a51f.png)

However, it is not completely convenient since there is no way to automatically scroll the right split when I manually scroll the left one. I would want to lock them, so the right one starts displaying the last line of the left one (plus one), like here:
![lines-aligned](https://cloud.githubusercontent.com/assets/452871/11984671/1fb520e4-a972-11e5-9ea1-ed985d7e59db.png)

In some cases it is also nice to split in three columns:
![three-cols](https://cloud.githubusercontent.com/assets/452871/11984679/319a5716-a972-11e5-9168-0e9c537b8ef9.png)

It would be nice to have a command like ":colsplit n" that splits the window into 'n' parts and locks the content as I showed, automatically scrolling them. I do not know if that would be something easily doable in a plugin, or it would be better to have it in the core. Any comments or suggestions?

**Comment by Wibjarm** [comment]
This is exactly what the [scrollbind option](http://vimdoc.sourceforge.net/htmldoc/options.html#'scrollbind') does.  Try this as an init.vim snippet, which gives you a :Bindsplit [number] command:
```viml
function! s:bindsplit(...) abort
    if a:0
        let l:count=(a:1 - 1)
    else
        let l:count=1
    endif
    echom l:count
    let l:curwin=winnr()
    for i in range(1, l:count)
        vsplit
        setlocal noscrollbind
        execute "normal! z+"
        setlocal scrollbind
    endfor
    execute l:curwin . "wincmd w"
    setlocal scrollbind
endfunction
command! -nargs=? -bar Bindsplit call s:bindsplit(<args>)
```
Maybe not the prettiest and I haven't exactly tested it extensively, but that should hopefully do roughly what you want.

**Comment by jcorbin** [comment]
fwiw, I've made a small plugin out of @Wibjarm 's function above https://github.com/jcorbin/vim-bindsplit
