### ISSUE TITLE
API/UI: nvim_ui_attach blocks on startup if nvim is waiting for input ("Press Enter")

### ISSUE THREAD

**Issue by rhysd** [neovim/neovim#3901]
Hi,

I'm creating Neovim frontend and have a trouble with `vim_ui_attach` rpc API.

When swap file already exists or some error is output while loading `init.vim`,  Neovim outputs it to command line because screen is not prepare yet.  And Neovim requires user input (e.g. selecting how to handle swap file).

When frontend starts Neovim process and calls `vim_ui_attach`,  it doesn't return until user inputs anything.  Of course no `redraw` event is sent and frontend can't render screen.  It means that user can't see nothing and thinks that frontend hangs.

I'm considering I should add `-n` and disable swapfile to avoid this problem.  But it doesn't solve this problem completely because error output while loading `init.vim` requires any key input.  I finally need to write timeout logic on calling `vim_ui_attach` to avoid this problem in all cases.

Is there any better way to handle this?  At least neovim-qt and neovim-dot-app seem not to handle this.

**Comment by tarruda** [comment]
I'm aware of this problem and currently working to fix it, see https://github.com/equalsraf/neovim-qt/issues/50#issuecomment-144577335 and https://github.com/neovim/neovim/issues/3646 for details

**Comment by rhysd** [comment]
Thank you for the answer (and sorry for late response).

I understood now you're working in progress and I'll wait for the fix :smile:

FYI, current workarounds are following:

- NyaoVim now disables swapfile by adding `-n` to command line option [here](https://github.com/rhysd/NyaoVim/blob/master/renderer/nyaovim-app.ts#L63).
- And now `g:nyaovim_version` is defined by `--cmd` option hence users can see the variable instead of `gui_running` currently.

But I can't add workaround for error message on start up yet.

**Comment by tarruda** [comment]
> I understood now you're working in progress and I'll wait for the fix :smile:

Sorry for the slow progress lately, I've been traveling with my family for the past month and it's been hard to maintain focus. I will get back to working at full speed next week.

FWIW, ATM I'm working on a C library that will take care of most UI <-> neovim boilerplate required for UI implementations(including all startup boilerplate that was described in https://github.com/equalsraf/neovim-qt/issues/50). I will also update some language-specific clients(node.js/lua) to use this library so nyaovim and other clients can benefit from its features more easily :). The end goal of this library to reduce the work required for implementing custom UIs(or other clients like plugin hosts) as much as possible.

**Comment by rhysd** [comment]
Thank you for the explanation and link.

New UI handling architecture looks better than current one!  It is reasonable to make `nvim` entry point of program instead of UI executable.

**Comment by rhysd** [comment]
@tarruda 

Hi, I was asked 'Can lines be set?' in below issue.

https://github.com/rhysd/NyaoVim/issues/19

Currently, our Neovim frontend should specify `lines` and `cols` when calling `attach` function.  But it should be able to be set by user such as `:set lines=36`.
So I think `lines` and `cols` should be passed when `nvim` process spawns frontend process if users specifies them.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/9024 .
