### ISSUE TITLE
Helptags generation causes dependency graph cycle.

### ISSUE THREAD

**Issue by lyuts** [neovim/neovim#3904]
Looks like dependencies for make targets that generate helptags end up being in a cycle which causes the build to fail.

Output of make:
[neovim_make_log.txt](https://github.com/neovim/neovim/files/72577/neovim_make_log.txt)

CMake's generated file:
[neovim_runtime_dir_build_make.txt](https://github.com/neovim/neovim/files/72578/neovim_runtime_dir_build_make.txt)
According to this file tags depend on arabic.txt
```
runtime/doc/tags: runtime/doc/arabic.txt
```

```arabic.txt``` in its turn depends on itself and ```autocmd.txt``` (and others)

```
runtime/doc/arabic.txt: runtime/doc/arabic.txt
runtime/doc/arabic.txt: runtime/doc/autocmd.txt
```
and ```autocmd.txt``` depends back on ```arabic.txt``` (and others)
```
runtime/doc/autocmd.txt: runtime/doc/arabic.txt
```

The problem is not limited to just ```arabic.txt``` or ```autocmd.txt```. All helptags files have this type of dependency issue.

**Comment by justinmk** [comment]
@lyuts What is the exact cmake invocation that fails for you? Though I have seen a warning about this before, it did not cause any failure.

**Comment by lyuts** [comment]
The build I'm working on is a FreeBSD port which configures neovim as:
```
cmake -DLUA_PRG=${LUA_CMD} -DUSE_BUNDLED_DEPS=OFF ..
```
But it looks like the main difference with this build is ```make``` that is being used. By default, it is BSD make. GNU make seems to drop the dependency if it causes a cycle. While I'm using a workaround for now by forcing GNU make for this port build it might be worth actually fixing the make target dependency graph. I don't know how other versions of GNU make behave when they encounter a cycle. The make targets generation seems to live in ```runtime/CMakeLists.txt```. I can take a look at it when I get time.

**Comment by lyuts** [comment]
To get better idea on how people configure builds: How do you guys run cmake:
- in git repo root
- in a build/ directory under git repo root
- in a build/ directory outside git repo root
- other
?

**Comment by justinmk** [comment]
For my local builds I just run `make` at the project root. So does [our CI build](https://github.com/neovim/neovim/blob/master/.travis.yml#L10).

> in a build/ directory outside git repo root

Our main build script uses the same project-relative build directory: https://github.com/neovim/neovim/blob/master/.travis.yml#L18

However, at least one of our other build scripts (which runs daily) invokes `cmake` directly to redirect the deps directory: https://github.com/neovim/bot-ci/blob/master/ci/common/deps-repo.sh#L37

**Comment by lyuts** [comment]
The most naive and straightforward change I could think of is something like this (will create a pull request once we agree on how to handle this):

https://github.com/lyuts/neovim/commit/1dd1d94c6080c0f6a4c928f3287b5e793992fef0

Right now basically we get a cross product of target * dependecy. With this change we (a) drop dependency on the target itself and (b) drops already used dependencies while ensuring each of ```runtime/doc/*.txt``` file gets mentioned at least once.

Also, from my investigation it looks like most vulnerable type of build is the one that runs cmake in git repo root. The way build works right now it figures out runtime files (referenced by DOCFILES), copies them to a build directory (referenced by BUILDDOCFILES) and then generating tags from copied files. Each element in BUILDDOCFILES depends on DOCFILES. When running cmake in git repo root nothing will be copied, because build directory is $PWD, values in DOCFILES are equivalent to BUILDDOCFILES which leads to these cycles.

Something else that I'd like to figure out is if we actually need to copy ```runtime/doc/*.txt``` files for help tags generation.

**Comment by justinmk** [comment]
I see no problem with that change. Would feel better if @jszakmeister peeked at it, but it's probably safe as long as `make install` seems to install the doc tags as usual.

**Comment by lyuts** [comment]
Is @jszakmeister reviewing pull requests or should I just wait for his feedback in this thread?

**Comment by justinmk** [comment]
@lyuts Please send a PR. It's a low-risk change; as long as `:help` still works after `make install` I don't see what harm it could do.

**Comment by lyuts** [comment]
Sumbitted pull request #3983. ```:help``` works.
