### ISSUE TITLE
Setting a build prefix

### ISSUE THREAD

**Issue by andrewdalecramer** [neovim/neovim#3909]
Could someone please tell me how to set a prefix when building?

I'm tearing my hair out over this and just can't figure it out. IT restricts us to hell so I'm trying to build nvim and put it in my ~/local directory with all the other things I've had to build (like vim7.4, tmux and even cmake).

I've looked at https://github.com/neovim/neovim/issues/2111 but when I try

cmake -DCMAKE_INSTALL_PREFIX=$FOO

it can't find LIBUV. I've got it to successfully build with an incorrect prefix using gmake but then it (obviously) can't find any of it's files when I run it from the build location.

**Comment by mhinz** [comment]
OS?

Try `gmake distclean && gmake CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=$FOO`.

**Comment by andrewdalecramer** [comment]
CentOS 6.7. Got further this time using your suggestion but failed with these lines

-- ...
-- Build files have been written to: /home/uqacrame/src/libs/neovim
touch build/.ran-cmake
gmake  -C build
gmake[1]: Entering directory `/home/username/src/libs/neovim/build'
gmake[1]: *** No targets specified and no makefile found.  Stop.
gmake[1]: Leaving directory `/home/username/src/libs/neovim/build'
gmake: *** [nvim] Error 2

with

neovim$ ls -a build/
.  ..  .ran-cmake  .ran-third-party-cmake

**Comment by justinmk** [comment]
Need verbose build log.

**Comment by Pyrohh** [comment]
> Need verbose build log.

Yes, that might help. Closing for now.
