### ISSUE TITLE
[RFC] Results of translation

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#392]
VimL to lua translator parser though incomplete yet has reached the state when you can get some meaningful translation results. Thus I have some questions about how the result should look like:

Consider the following VimL code

``` VimL
function Error()
    throw 'E42'
endfunction
function A()
    try
        while 1
            echo 'HERE0'
            if Error()
                let a = 1 + 1
                return 1
            endif
        endwhile
    catch /^E42/
        echo HERE 'HERE'
    finally
        echo 'THERE'
    endtry
    echo 'THERE2'
endfunction
call A()
```

. It can be translated to the following Lua:

``` Lua
f.Error = function(state)
    vim.commands.throw(state, 'E42')
    return vim.zero
end
f.A = function (state)
    local l = vim.scope()
    local ok, err, return_value_1 = pcall((function (state)
        while (vim.number("1")) do
            vim.commands.echo(state, 'HERE0')
            if f.Error(state) then
                l.a = vim.add(state, vim.number("1"), vim.number("1"))
                return vim.number("1")
            end
        end
        return nil
    end), vim.trying(state))
    err = vim.get_error(err)
    local fin = function()
        vim.commands.echo(state, 'THERE')
        return nil
    end
    if (not ok) then
        if (vim.error_matches(state, err, '^E42')) then
            vim.commands.echo(state, l.HERE, 'HERE')
        else
            return_value_2 = fin()
            error(err)
        end
    end
    return_value_2 = fin()
    if (return_value_2 ~= nil) then
        return return_value_2
    end
    if (return_value_1 ~= nil) then
        return return_value_1
    end
    vim.commands.echo(state, 'THERE2')
    return vim.zero
end
f.A(state)
```

Questions:
1. I had to use `vim.add` in place of `1 + 1`. Reasoning: `a + b` generally may fail, but the results of the failure depend on `state.trying`, so I can’t just use `a + b`. Vim uses global trylevel, but we don’t need globals. Wondering whether it should be kept as-is, numbers (and other VimL values) should receive a metatable which handles such situations based on thread-local state or anybody has better idea.
2. `vim.zero`: I cannot use lua numbers because lua does not have integers and there are significant differences in integers and floats: like `string(1.0) !=string(1)`, `1.0 . "abc"` is error and so on. So I probably will have to do like python does: pregenerate a number of integers. All new integers are lua userdata.
   
   Alternative: luajit has 64-bit integers. They cannot be used in their condition (`1LL + 1.0` is `2LL`, but should be `2.0`), but maybe someone more experienced can tell how they did this and whether we can do the same: extend Lua syntax to accept new literals. Or at least use whatever they used (I heard a word “liteuserdata”) to implement our integers, still using `vim.number("1.0")`. This means though that we throw away lua support, sticking with luajit (currently only tests require luajit).
3. As something may fail while execution continues `l.a` need to be a table with special metatable which restricts `nil` values (`vim.add()` will return `nil` on failure) from being added. In any case `l` has to have a different metatable because it should restrict locked variables from being overwritten and throw proper errors if variable was not found.
4. Globals. I did not ever work with embedding lua so I wonder whether I can just make things like options pseudo-table global variable. I.e. does embedding new vim instance mean new lua interpreter instance or not.
5. `:try` block produces rather bloated code. Any ideas on how to make it less bloated?
6. Non-fatal errors are represented as `nil` values. Any operation on a `nil` value produces a `nil` value. But this still adds incompatibility: all operands are computed, while in Vim if there is error on one side of addition other side is not computed. So I probably have to stick with `vim.add`, but make it look like `vim.add(state, op1, op2func, op2arg1, …)`.
7. Lua prepends the location of the error to the error message. So I have to use error marker. But location of the error include file name. So I use NUL as a error marker as it is the only character which ultimately cannot be contained in a filename or in a error string. Any better ideas?

(axillary definitions that are needed to make this run:

``` Lua
vim = {
    add=function(state, a1, a2) return a1 + a2 end,
    number=function(n) return tonumber(n) end,
    dictionary=function(d) return d end,
    scope=function() return vim.dictionary({}) end,
    trying=function(state)
        local new_s = {}
        for k, v in pairs(state) do
            new_s[k] = v
        end
        new_s.trying = true
        return new_s
    end,
    message=function(state, m)
        if not state.silent then
            print (m)
        end
    end,
    get_error=function(err)
        return err:gsub('.*%x00', '')
    end,
    error_matches=function(state, str, pattern)
        return str:match(pattern)
    end,
    commands={
        echo=function(state, ...)
            local m = ''
            for i, v in ipairs{...} do
                if (i > 1) then
                    m = m .. ' '
                end
                m = m .. v
            end
            vim.message(state, m)
        end,
        throw=function(state, m)
            if (state.trying) then
                error('\0'..m)
            else
                vim.message(state, m)
            end
        end,
    }
}
f = {}
state = {trying=false, silent=false}
vim.zero = vim.number("0")
```

**Comment by bfredl** [comment]
While this was a worthwhile initiative, with the advance of the lua plugins (and vim9script plugins at the other side of the pond) this is not relevant anymore.

Resolution: Neovim will use vim script with `scriptversion 1` unmodified. For better behaviors and performance, use lua.
