### ISSUE TITLE
redraw issue after iTerm2 fullscreen + airline.vim

### ISSUE THREAD

**Issue by lvht** [neovim/neovim#3929]
Open iTerm, and start NeoVim. Then, maxmize iTerm, but NeoVim didn't redraw the tui.

My NeoVim's version is 0.1.1 under Mac OS X EI.

<img width="1280" alt="nvim" src="https://cloud.githubusercontent.com/assets/2030591/12073822/39d3821e-b16e-11e5-83b5-878301876059.png">

**Comment by wsdjeg** [comment]
same as me ,

**Comment by wsdjeg** [comment]
hi @justinmk  the milestone 0.2 means virsion 0.1.2 or version 0.2.0?

**Comment by justinmk** [comment]
Patch releases (0.1.2) are not tracked as milestones. See semver.org

**Comment by sethjackson** [comment]
I saw this recently on `gnome-terminal` too recently (nvim compiled from master a couple of weeks ago). I am also using airline. I wonder if that is causing it?

**Comment by JDongian** [comment]
Running gnome-terminal on Arch Linux without powerline, I am unable to reproduce this bug.

**Comment by wsdjeg** [comment]
@justinmk I hava test neovim without airline,can not reproduce this bug,I think it is the issue of between  airline and neovim ,maybe @bling should know about this bug.

**Comment by justinmk** [comment]
We have some redraw bugs for sure. Unlikely that airline is the root cause.

**Comment by wsdjeg** [comment]
thanks, got it, waitting to be fixed @justinmk

**Comment by matthewtodd** [comment]
Short-term workarounds, while we're here:

* [Suspend](http://vimdoc.sourceforge.net/htmldoc/starting.html#suspend) nvim, then `fg` back in from the shell.
* Send nvim a(nother?) [SIGWINCH](http://www.delorie.com/gnu/docs/glibc/libc_478.html): `pkill -WINCH nvim`

**Comment by jiegec** [comment]
Using airline, tmux, vim-tmux-focus-events(does it help?), I cannot reproduce it.

**Comment by justinmk** [comment]
@matthewtodd  A simple CTRL-L should suffice. Does it not?

**Comment by matthewtodd** [comment]
@justinmk Interestingly, CTRL-L doesn't suffice.

Poking around further, I can confirm iTerm2 is indeed sending a `SIGWINCH` on entering and exiting fullscreen mode (`ruby -e 'Signal.trap("WINCH") { puts "WINCH!" }; while true; end'`), and that iTerm2 doesn't seem to be a diagnostic factor: I see the same no-redraw behavior running nvim in Terminal.

I don't always see it; it seems to vary with the contents of the current buffer. (Small `Rakefile` works, larger ~1K `Gemfile` doesn't.) I thought line length, number of lines, or overall size might matter, but I can't reproduce it munging a simple text file full of `x`'s and newlines.

Will see if I can narrow it down over the next couple of days.

**Comment by wsdjeg** [comment]
@justinmk I do not know why,after update the neovim ,this issue appears,but I remamber ,it works well one day ago.really do not know why!
![2016-02-05 21-24-25](https://cloud.githubusercontent.com/assets/13142418/12847519/dbd38424-cc4e-11e5-95eb-a13a3544f578.png)
but `neovim -u NONE` works well I will try to fine out which plugin cause this issue
![2016-02-05 21-26-01](https://cloud.githubusercontent.com/assets/13142418/12847563/28d91572-cc4f-11e5-8469-7d87efbf0422.png)
![2016-02-05 21-26-06](https://cloud.githubusercontent.com/assets/13142418/12847564/28e528da-cc4f-11e5-9b1a-4d7455978c8d.png)

**Comment by justinmk** [comment]
@wsdjeg Please only add _new_ information to issues. Your comment does not add any useful information. Please do not show screenshots.

**Comment by aspidites** [comment]
First, note that I am using the following plugins:
- vim-plug
- vim-sensible
- vim-kalisi
- jellybeans.vim
- wombat256.vim
- lightline.vim
- haskell-vim
- supertab
- neomake
- emmet-vim

I first uninstalled all plugins except vim-plug and commented out every line in my init.vim file. Problem went away. I then re-enabled all lines that didn't pertain to vim-plug (such as enabling line numbers, etc). No problem. Next, I only added the following lines to my init.vim:

```vim
call plug#begin(~/.config/nvim/plugged')
call plug#end()
```
The issue returns as described in the original bug report. Next, I removed those two lines and manually installed each of the plugins above one by one. The only plugin that exhibited the erroneous behavior was vim-sensible.

That is, the only two plugins that cause the issue to appear are vim-sensible and vim-plug. That leads me to believe that something that those two plugins have in common may be the root cause of this odd refresh behavior.

**Comment by erf** [comment]
The issue seems to resolve when i set `set nolazyredraw` - thanks @aspidites

**Comment by aspidites** [comment]
@erf - I have to disable both lazyredraw and syntax enable in order for the problem to disappear.

**Comment by wsdjeg** [comment]
@justinmk I found in neovim ,if I  encounter this issue, `<C-l>` do not help,but `:mode` can refresh the screen!

**Comment by justinmk** [comment]
@wsdjeg Did you map `<c-l>` to something else?

**Comment by wsdjeg** [comment]
no <c-l> has no mappings.

**Comment by wsdjeg** [comment]
also in ubuntu 's desktop setting,if I move the terminal's menu to desktop statulien,this issue will gone.
here is the setting picture,but in chinese,but if anyone use ubuntu I think he know what it is.
![2016-02-26 23-25-28](https://cloud.githubusercontent.com/assets/13142418/13356447/4580f932-dce0-11e5-8751-5bce9bb42c38.png)
![2016-02-26 23-25-39](https://cloud.githubusercontent.com/assets/13142418/13356448/45813ed8-dce0-11e5-8399-6abe77b68eaa.png) move to first one ,this issue will gone

**Comment by aspidites** [comment]
Thanks for the tip @wsdjeg. I've bound this in my init.vim for now, which isn't ideal, but certainly better than having to disable useful features.

**Comment by obidan** [comment]
I'm having the exact same issue but using Vim. I don't think this is a neovim problem.

**Comment by obidan** [comment]
Also,  any syntax enabling seemed to trigger the bug for me as well . Deleting plugins one by one, I realised that if any words appear in the text as highlighted in another color  then the issue happens.
Just got the new Ubuntu patch and, I"m having the issue using C++ and YouCompleteMe but it happens once every 4-5  refreshes , so rather inconsistently.

**Comment by shenchsh** [comment]
@lvht It seems that you can solve this problem by disable native full screen windows in iterm2.
Iterm2: Preferences->general-> Native full screen windows.

**Comment by ssreekanth** [comment]
@ivht workaround works fine, when switching iterm to full screen mode. However, the issue is still there when exiting from full screen.

**Comment by obidan** [comment]
Can anyone pinpoint as to what is causing this exactly? This isn't an iterm problem as I"m experiencing it on Ubuntu and isn't a neovim problem as I'm experiencing it on classic vim.  @wsdjeg 's  solution works if vim-airline is disabled, but doesn't work with vim-airline on.

**Comment by timfeirg** [comment]
can you try disable the `disable session-initiated window resizing` in iterm2?

<img width="910" alt="preferences" src="https://cloud.githubusercontent.com/assets/4319104/16713180/a83fc5f2-46d1-11e6-95df-bb390133da0b.png">

**Comment by osenvosem** [comment]
The same issue here.

**Comment by nicknisi** [comment]
I was seeing this issue as well, specifically while running neovim in tmux in iTerm. However, this appears to be fixed after I upgraded to tmux 2.3.

**Comment by kiviok** [comment]
Hi. I just uncheck the box "Native full screen windows" in Preferences->General (iTerm) and thats worked!!
try it.

**Comment by justinmk** [comment]
Merging this issue with https://github.com/neovim/neovim/issues/4884
