### ISSUE TITLE
nvim gets confused when active window is set to the same value multiple times over msgpack-rpc 

### ISSUE THREAD

**Issue by sschaef** [neovim/neovim#3931]
The following series of commands over the msgpack-rpc connection seem to confuse nvim:

```
vim_set_current_window n
vim_input "<C-w>"
vim_set_current_window n
vim_input "s"
```

`n` is an arbitrary window number but needs to be the same in both cases. The use case here is that the window should be split horizontally. This is done through entering the `<C-w>s` key sequence. My UI sends two events to achieve that, one for the `<C-w>` and one for the `s`. In addition to that I set the active window before each key event, which nvim doesn't like at all. The moment when the active window is set to the same window that was already set, it doesn't seem to be possible anymore to get back responses. Both key events are correctly received on the nvim side but nvim seems to wait for a processing signal before it sends back a response to the requests. Somehow it doesn't recognize that after the `s` is received, the command can be processed.

It was quite easy to solve the problem by just not sending signals the very same window id multiple times as the active window id. However, it took me quite some time to find out the origin of this problem. In order to improve experience better for users it should be explicitly stated in the documentation what happens to ongoing key sequences when the window is updated to value of the already active window. I think it is best to just ignore such an window update in such a case and in case the window id changes, the former key sequence should be processed or if that is not possible canceled.

**Comment by justinmk** [comment]
> Somehow it doesn't recognize that after the `s` is received, the command can be processed.

The `s` is never received, because `<C-W>` is blocked waiting for input. The second call to `vim_set_current_window` blocks until input is received.

Note that `nvim_input` is asynchronous so input could be sent by the user or another client. `vim_set_current_window` is synchronous. See `:help nvim_set_current_win` and `:help nvim_input` (the "Attributes" note).

Confirmed in the python client:

```
n.input("<C-W>")
n.request("nvim_set_current_win")
```

Merging this issue with #6159.
