### ISSUE TITLE
could my editing goals be your goals?

### ISSUE THREAD

**Issue by jlettvin** [neovim/neovim#3934]
Here are features I value:

1. rotate through notepad/vi/emacs key-bindings and style with a single key (I use ctrl-minus).
2. use 10 unique cursors to identify up to 10 simultaneous users.
3. each user chooses key-bindings on-the-fly as wanted without affecting others.
4. update converted markup in separate window if markup engine is specified.
4.1. See: http://rote.training/?client=rote&page=Support.UnitTest (self-documenting markup)

There are goals we might not have in common.

For me, limiting content to a very small source input and target output is important.
Your goals are likely to include handling gigabyte size files.

For me, a visible gap with specialized cursor like ❶ to identify an actively editing user is good.
Traditionally, a cursor is either a thin line between chars or an inverted color char.

I value keeping special characters as "marks" in the text (may be visible or invisible).
I know of no editors that make marks visible.

Currently, I restrict the front-end to three functions, key input, rendering output, and metadata display.
My server back-end does ALL the work, and I believe this is what you aim for as well.

These are just a few early interactions with which I hope to inspire you.
I am interested in providing modules, like my markdown language.
It is specialized for small footprint page delivery for science and engineering communications.

Please let me know if I might yet be a contributor to neovim?

**Comment by justinmk** [comment]
Your goals concern behaviors in the [front-end/UI](https://github.com/neovim/neovim/wiki/Related-projects#gui-projects) domain, not the Neovim core. Our goal is to make `nvim` flexible enough to meet the needs of such front-ends.

> `1.` rotate through notepad/vi/emacs key-bindings and style with a single key (I use ctrl-minus).

Vim/Neovim existing keymap features can achieve this via basic user configuration AFAIK.

> `2.` use 10 unique cursors to identify up to 10 simultaneous users.

Realistically I doubt this will be a priority as a core feature in the near future. But it is already accomplished to some degree by Neovim plugins such as [floobits](https://github.com/Floobits/floobits-neovim).

> `3.` each user chooses key-bindings on-the-fly as wanted without affecting others.

This is a basic feature of the floobits plugin mentioned above.

> `4.` update converted markup in separate window if markup engine is specified.

If I understand correctly, this has been done by several different authors. Here's one example: https://github.com/rhysd/NyaoVim#ui-plugin-examples

> Currently, I restrict the front-end to three functions, key input, rendering output, and metadata display.
> My server back-end does ALL the work, and I believe this is what you aim for as well.

Yes. 

> I am interested in providing modules, like my markdown language.
> It is specialized for small footprint page delivery for science and engineering communications.
> Please let me know if I might yet be a contributor to neovim?

The core Neovim project can't pretend to manage specialized applications beyond the standard runtime files. See [related projects](https://github.com/neovim/neovim/wiki/Related-projects) for various third-party applications built with Neovim. Certainly you are invited to add to that list, and let us know how the API etc can be improved (or send a PR to do so, after discussing the design).

**Comment by jlettvin** [comment]
Thank you for your detailed response.  I will research these vigorously;
especially floobits.
It's nice to see that others share my enthusiasm for remote pair
programming.

I am strong in Python.  Yet, the way I developed my front and back ends
I went completely narrow-scope with node/socket/jquery since
the support and reliable distribution of a common basis is higher.
No compilation necessary, it just works from source alone.

I will download and experiment with neovim before meddling more deeply.

On Sat, Jan 2, 2016 at 10:10 PM, Justin M. Keyes <notifications@github.com>
wrote:

> Your goals concern behaviors in the front-end/UI
> <https://github.com/neovim/neovim/wiki/Related-projects#gui-projects>
> domain, not the Neovim core. Our goal is to make nvim flexible enough to
> meet the needs of such front-ends.
>
> 1. rotate through notepad/vi/emacs key-bindings and style with a single
> key (I use ctrl-minus).
>
> Vim/Neovim existing keymap features can achieve this via basic user
> configuration AFAIK.
>
> 2. use 10 unique cursors to identify up to 10 simultaneous users.
>
> Realistically I doubt this will be a priority as a core feature in the
> near future. But it is already accomplished to some degree by Neovim
> plugins such as floobits <https://github.com/Floobits/floobits-neovim>.
>
> 3. each user chooses key-bindings on-the-fly as wanted without affecting
> others.
>
> This is a basic feature of the floobits plugin mentioned above.
>
> 4. update converted markup in separate window if markup engine is
> specified.
>
> If I understand correctly, this has been done by several different
> authors. Here's one example:
> https://github.com/rhysd/NyaoVim#ui-plugin-examples
>
> Currently, I restrict the front-end to three functions, key input,
> rendering output, and metadata display.
> My server back-end does ALL the work, and I believe this is what you aim
> for as well.
>
> Yes.
>
> I am interested in providing modules, like my markdown language.
> It is specialized for small footprint page delivery for science and
> engineering communications.
> Please let me know if I might yet be a contributor to neovim?
>
> The core Neovim project can't pretend to manage specialized applications
> beyond the standard runtime files. See related projects
> <https://github.com/neovim/neovim/wiki/Related-projects> for various
> third-party applications built with Neovim. Certainly you are invited to
> add to that list, and let us know how the API etc can be improved (or send
> a PR to do so, after discussing the design).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neovim/neovim/issues/3934#issuecomment-168455286>.
>



-- 
This e-mail is from Jonathan D. Lettvin, and may contain information that
is confidential or privileged. If you are not the intended recipient, do
not read, copy or distribute the e-mail or any attachments. Instead, please
notify the sender and delete the e-mail and any attachments. Thank you.

Jonathan D. Lettvin
