### ISSUE TITLE
Ability to create new operators

### ISSUE THREAD

**Issue by azure-satellite** [neovim/neovim#3937]
I believe operators to be baked into the core ideology that modal editing brings. Recently I implemented an operator myself using the excellent plugin https://github.com/kana/vim-operator-user and thought it'd be really great (and perfectly fit to become a core feature IMO) if vim had a built-in way to create new operators. While kana's plugin is very useful, you can still see that it has to work around a limitation that was partly described in http://stackoverflow.com/questions/1533565/how-to-get-visually-selected-text-in-vimscript, namely that there's no easy way to get the text selected in a visual selection.

It'd be awesome if there was a function `new_operator(name, callback)` where `callback(selected_text, mode)` and `mode` could be `block`, `char` or `line`. Then `new_operator` would define a `<Plug>(name)` mapping the user can map like `map gs <Plug>(name)`.

Maybe @kana could give more insight

**Comment by bfredl** [comment]
I don't know how related, but in #3708 I'm implementing an (internal) function to acquire the visual selection text (also without needing to exit/reenter visual mode. This is more complicated that one would expect, although the modified SO solution I think handle all "reasonable" cases, except for block mode). This could be exported as API and/or vimscript function.

**Comment by ZyX-I** [comment]
Vim always had a way to create new operators, with a callback as well: see `:h 'operatorfunc'`. I do not see any reason to have a new function.

(Note though that I would not use examples listed in documentation: valid way to define an operator is

    function Operator(func)
        let &opfunc = a:func
        return 'g@'
    endfunction

    function DoSomething(type, ...)
        " Do something
    endfunction

    nnoremap <expr> gs Operator('DoSomething')

: listed examples do not accept count before the operator.)

The problem is non-intrusive way to get text between the marks: see my answer in the question you linked. But this can be hidden into an autoload library, without any changes to the core.

**Comment by ZyX-I** [comment]
(And note that I have nearly as complex solution for blockwise as well. All solutions are actually used in translit3 plugin: https://bitbucket.org/ZyX_I/translit3/src/435d0845939e89d2f37673e3cf7f6dbf73d4c69c/autoload/translit3.vim#cl-2167 for characterwise, https://bitbucket.org/ZyX_I/translit3/src/435d0845939e89d2f37673e3cf7f6dbf73d4c69c/autoload/translit3.vim#cl-2321 for blockwise.)

**Comment by justinmk** [comment]
Besides above comments, making `mode()` more useful and reliable would be really convenient.

But I never understood the point of kana's textobj plugin: it requires a comparable amount of code as the built-in `g@` approach.

**Comment by azure-satellite** [comment]
@ZyX-I I wasn't aware of `g@` and `operatorfunc`. That seems to be indeed what I was looking for. All your points are true so I'm closing this issue since it's invalid.
