### ISSUE TITLE
Shada: Wrong permissions?

### ISSUE THREAD

**Issue by danbruegge** [neovim/neovim#3941]
Hi,
for me it looks like, the shada permissions wrong when run a fresh neovim install.

    $ ls -l /home/dan/.local/share/nvim
    total 12K
    drwx------ 2 dan dan 4.0K Jan  4 10:25 shada
    drwxr-xr-x 3 dan dan 4.0K Dec  9 09:24 site
    drwxr-xr-x 2 dan dan 4.0K Jan  4 08:51 swap

    $ ls -l /home/dan/.local/share/nvim/shada
    total 8.0K
    -rw------- 1 dan dan 78 Jan  4 10:25 main.shada
    -rw------- 1 dan dan 78 Jan  4 10:42 main.shada.tmp.a
    -rw------- 1 dan dan 78 Jan  4 10:44 main.shada.tmp.b

Neovim fires this error:
![nvim-shada](https://cloud.githubusercontent.com/assets/1296438/12087145/ed402f4c-b2d0-11e5-944d-51f542d72096.png)

How can i fix this?

**Comment by mhinz** [comment]
Hmm, the permissions look sane to me.

- Can you reproduce this every time?
- Can you reproduce it with a simple `:quit` (which is what line 8 in `close()` actually does)?
- How did you install Neovim?

**Comment by danbruegge** [comment]
1. yep, i've 3 machines with the same issue. 1 completely new and 2 old ones.
2. yep, only the startify error msg disappears
3. on archlinux, the standard package from the repo (https://www.archlinux.org/packages/community/x86_64/neovim/)

I have this issue since neovim switched to shada. First i managed it by changing the permissions. After i resort my dotfiles repo and changed a lot of symlinks, the error came back.

**Comment by ZyX-I** [comment]
@danbruegge Permissions are expected and intentional: rw to user, nothing to anybody else. Error has absolutely nothing to do with permissions: which word of “attempt to dump function reference” is not clear? You need to find the variable like `F` which contains the function reference and remove it. Also you need to update Neovim: now this error is not causing dumping ShaDa file to stop (#3721).

**Comment by ZyX-I** [comment]
Though note that even after updating this error is not going away, only E136 errors will go away and ShaDa will continue to function properly.

**Comment by mhinz** [comment]
I still don't understand what the issue is. The error message isn't clear it all. It says what happens, but not what it means.

There's a global variable that references a function? `:h E475` talks of an invalid argument given to a command.

**Comment by ZyX-I** [comment]
@mhinz E475 talks about invalid argument, not about invalid argument *given to a command*. Actually the piece of code that gives this error message is shared with `msgpackdump()` function and E475 always talked about invalid argument given to a function.

**Comment by danbruegge** [comment]
Ok, i removed the vaxe plugin till the maintainer merges the pull-request. Error is caused by vaxe plugin. https://github.com/jdonaldson/vaxe/pull/88

Thanks for the help.

**Comment by ZyX-I** [comment]
I think I will rewrite the error: new would look something like

    E951: Error while dumping %s, %s: attempt to dump function reference

First %s is replaced with something like `variable g:varname`. Second %s is replaced with something like `itself` (`let F=function('tr')`) or `key F index 1` (`let F={'F': [0, function('tr')]}`).
