### ISSUE TITLE
does neovim contains python client?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3942]
from https://neovim.io/doc/user/nvim_python.html
> 2. Quickstart						 *nvim-python-quickstart*

> If you used a package manager to install Nvim, there's a good chance that
it also provides the `neovim` Python package. If it doesn't, follow these
steps to install the package with Python's package manager, `pip`.

I can not understand this statement 
> ` If you used a package manager to install Nvim, there's a good chance that
it also provides the `neovim` Python package`

does it means neovim contains python client?
I am using this command to install neovim,and my os is ubuntu
sudo apt-get install neovim

**Comment by wsdjeg** [comment]
should I use sudo apt-get install neovim-python ?

**Comment by justinmk** [comment]
It depends on the distribution. In general, no. Probably we should remove that sentence.

**Comment by wsdjeg** [comment]
got it, thanks ,now I am using pip,and everythings works well ,I think this sentence will make some people confused，maybe only need to change like this or something else

>If you used a package manager to install Nvim, there's a good chance that
it also provides the neovim Python package. If it doesn't, follow these
steps to install the package with Python's package manager, pip.
to 

>If you used a package manager to install neovim, there's a good chance that
it also provides the python-neovim package which is the python-client for neovim, If you can not install python-neovim with your current package manager,please follow these
 steps to install the package with Python's package manager, pip.
