### ISSUE TITLE
better support for user defined clipboards (like tmux buffer integration)

### ISSUE THREAD

**Issue by cazador481** [neovim/neovim#3948]
I see 2 things happening.  If I use the & register, the call is sent + as the register being used instead of &.  
Also for some cases such as using reg 5 the provider isn't called at all.

**Comment by bfredl** [comment]
Is there even a `&` register in `/n/vim` ? what i]it supposed to do ?

**Comment by bfredl** [comment]
Can't find it in latest `vim` doc, perhaps you meant something else? can you post complete commands + expected vs actual behaviour?

**Comment by cazador481** [comment]
Any keyboard key can be a register in vim.  By default they are just separate register locations.  I am trying to capture the & register and use that to map to the tmux copy/paste buffer.
https://github.com/cazador481/fakeclip.neovim  Has the code to attach the tmux buffer to the & register.  Once apon a time it used to work, but the underlying clipboard code change a few months ago, and now it doesn't pass the correct register value. to the get call.

**Comment by cazador481** [comment]
Code to show problem.  In provider/clipboard.vim modify the provider#clipboard#Call function to
```
function! provider#clipboard#Call(method, args)
    echo a:args
    return call(s:clipboard[a:method],a:args,s:clipboard)
endfunction
```

This will show what the args passed to the clipboard provider is.
When i do 
"&yy on a line containing endfunction
I get 
```
[['endfunction', ''], 'V', '+']
```
I expect 
```
[['endfunction', ''], 'V', '&']
```

By adding the following to the beginning of clipboard.get(reg)
```
echom "register is". a:reg
```
You get the which register you are getting from
so when I do
"&p
I get
```
register is +
```
I expect to get
```
register is &
```

**Comment by bfredl** [comment]
That only worked by accident, If you have the right option (too lazy to find it...), you will se that `"&` was aborted and you only did `pp`, and I presume you had `clibboard=unnamed[plus]` and tmux also in some of the `+`/`*`.
A usecase like your is something we definitely want to support though, ideally something simpler than having to copy and modify the entire provider (which is intended for the system clipboard only), like maybe just two autocommand definitions in your case.

**Comment by bfredl** [comment]
However adding _new_ registers like `&` should probably be discussed on vim_dev, because if vim later adds a builtin register we made user-definable, vim and nvim will forever have an unneccessary incompatibility.

**Comment by cazador481** [comment]
I do have have clipboard set to clipboard=unnamedplus.
Is there a bug to track the request for my usecase of adding user configurable registers?

**Comment by bfredl** [comment]
I think it was discussed before somewhere, but not a separate issue. Let's keep this one open.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/6030
