### ISSUE TITLE
Windows version is not starting due to missing dll's

### ISSUE THREAD

**Issue by ZeerDonker** [neovim/neovim#3950]
Downloaded the latest green build.  

Followed the instructions on the wiki.

On windows 10 gave the issue that it did not find the following dll's: 
 vcruntime140d.dll 
 ucrtbased.dll

**Comment by mhinz** [comment]
@equalsraf ^

**Comment by equalsraf** [comment]
The wiki instructions need updating. @ZeerDonker you seen to be using one of the debug builds, can you check with the ones that say `Configuration: Release`?

**Comment by ZeerDonker** [comment]
This is a release: 
https://ci.appveyor.com/project/equalsraf/neovim/build/527/job/61u03ov5nsgdb552/artifacts

Which still complains about a missing dll. 
vcruntime140d.dll

**Comment by equalsraf** [comment]
@ZeerDonker what about these? https://ci.appveyor.com/project/equalsraf/neovim/build/538

**Comment by Shougo** [comment]
@ZeerDonker I think you need to install VC++2015 runtime.

https://www.reddit.com/r/Python/comments/3o5nhr/the_program_cant_start_because_vcruntime140ddll/
https://www.microsoft.com/en-us/download/details.aspx?id=48145
