### ISSUE TITLE
"set visualbell" writes bad char to screen

### ISSUE THREAD

**Issue by Eriner** [neovim/neovim#3955]
running `nvim -u NONE`, followed by `:set visualbell`
Entering insert mode and pressing the left-arrow key produces the following: https://i.eriner.me/nvim_visualbell.png

Not sure what broke this, but it had to have been within the last few days. I thought at first it was one of my plugins that broke this, but that is obviously not the case.

**Comment by justinmk** [comment]
For terminal issues we always need to know:

- the value of `$TERM`
- the actual terminal you are using and its version

`:version` of neovim is also required for all issues.

**Comment by Eriner** [comment]
```
print $TERM
screen-256color

pacman -Qi xfce4-terminal | grep 'Version'
Version        : 0.6.3-2

NVIM v0.1.1-167-g0298b00 (compiled Jan  6 2016 06:22:44)                                                   
Build type: Dev
```

**Comment by Eriner** [comment]
Ah, it seems that a mis-delete in my environment set my TERM from `xterm-256color` to `screen-256color`. Though, that begs the question, is that still the intended behaviour? I assume it must be, but to be fair, I don't know much about (the backend of) terminal multiplexers.
