### ISSUE TITLE
mouse cursor up to column 222 on tmux/urxvt not possible

### ISSUE THREAD

**Issue by oux** [neovim/neovim#3957]
On vim I use the set ttymouse=urxvt to be able to move cursor after column 222 on a urxvt.
Note with vim 7.4 it doesn't work on tmux.
On Neovim ttymouse has been removed but I didn't found any additional option or workaround do be able to use the mouse after column 222 (on urxvt, with or without tmux)

**Comment by justinmk** [comment]
`:version`
