### ISSUE TITLE
Accented characters don't working

### ISSUE THREAD

**Issue by adelarsq** [neovim/neovim#3959]
On Windows, some characters (~, ` and ´) are not being shown when typed on insert mode (<space> + ~ for example). ~ don't work on the command and normal modes.

This is a missing feature?

**Comment by justinmk** [comment]
Cannot reproduce with `nvim-qt.exe` from 18 October, `nvim` version 0.1.1.

You gave almost no information. Are you using a non-US keyboard layout, or input method (IME)?

**Comment by adelarsq** [comment]
So isn't a missing feature.
Yes. Its a non-US keyboard ([ABNT BR](https://upload.wikimedia.org/wikipedia/commons/1/17/KB_Portuguese_Brazil.svg)).
Version 0.1.0:
```
λ nvim --version
NVIM 0.1.0-dev (compiled Nov  8 2015 22:56:09)
Commit: 27f0fa51e9ca886c87159ee1e2c394426d64d128
Build type: Debug
Compilation: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe /DWIN32 /D_WINDOWS /W3 /D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONST
_NO_DEPRECATE -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/deps32/usr/include -IC:/projects/n
vim/deps32/usr/include -IC:/projects/neovim/deps32/usr/include/luajit-2.0 -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appvyr-win20122ppveyor@appvyr-win20122

Optional features included (+) or not (-): -acl   -iconv    -jemalloc
For differences from Vim, see :help vim-differences

  fall-back for $VIM: "C:/projects/neovim/INSTALL/share/nvim"
```
From where I can get this 0.1.1 version compiled for Windows? I did get from [1](https://github.com/equalsraf/neovim-qt/releases) and [2](https://github.com/rhysd/NyaoVim)(`npm install -g nyaovim`) :neutral_face:

**Comment by justinmk** [comment]
Can you try [these instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows) (using neovim-qt, not nyaovim) to see if it happens there?

**Comment by adelarsq** [comment]
I will close this issue, since I don't have the machine anymore.
