### ISSUE TITLE
Why do you remove the build date of the neovim in the version output?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3960]
as you know ,most people use the package manager install the neovim ,in ubuntu it is apt,and i am using the PPA source,it is daily build version ,it will be updated everyday, if you remove the build date,I can not find which commit of neovim I am using now!
I know it is not good idea show the date afte version number,but it should be shown below.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/3952

https://github.com/neovim/neovim/pull/3811

**Comment by wsdjeg** [comment]
hi @justinmk how could i see which commit my neovim is? I am not build from source, I am using apt

**Comment by fwalch** [comment]
@wsdjeg Try `sudo apt-cache show neovim  | grep Version`.

**Comment by wsdjeg** [comment]
thanks it works for me ,show me these
```
Version: 0.1.1ubuntu1+git201601081959+2117+16~ubuntu16.04.1
Version: 0.1.1ubuntu1+git201601072029+2114+16~ubuntu16.04.1
```
