### ISSUE TITLE
Running with :! sends EOF

### ISSUE THREAD

**Issue by ararslan** [neovim/neovim#3961]
Consider the following simple Python program:

```python
n = int(raw_input())
print "Got", n
```

Running this from Vim with `:!python %` waits for input then prints accordingly. However, when running this from NeoVim, it exits immediately with an error:

    Traceback (most recent call last):                                                                  
      File "test.py", line 1, in <module>                                                              
        n = int(raw_input())                                                                            
    EOFError: EOF when reading a line                                                                   
    shell returned 1

So for whatever reason, NeoVim seems to be sending EOF to the buffer. This seems like it could be related to #3772 but what do I know? ¯\\\_(ツ)\_/¯

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/1496

**Comment by ararslan** [comment]
@justinmk: Very sorry, didn't see that one. Thanks for your quick response!
