### ISSUE TITLE
Neovim doesn't take up entire terminal window

### ISSUE THREAD

**Issue by Yackback** [neovim/neovim#3971]
It seems that when I use neovim, it doesn't use up all of the terminal space for it's window, leaving a small space shown here on the right side: http://i.imgur.com/EZMnlZK.png. This happens on both terminator and gnome-terminal, as originally I thought it was due to terminator.

I know this may not be the biggest priority right now, but I figured I could post it as it is a problem for someone ricing their desktop.

**Comment by ZyX-I** [comment]
Space Neovim can occupy is defined by the terminal emulator. This issue has absolutely nothing to do with Neovim unless you can e.g. use `echo` in shell to put something into that place.

Also note that left space is smaller then width of one glyph in a used fixed-width font. This means that space in question *cannot* be occupied by any symbol.
