### ISSUE TITLE
generic tag infrastructure

### ISSUE THREAD

**Issue by wberrier** [neovim/neovim#398]
It seems that vim currently has support for ctags and cscope.

Some features (ie: tagstack) aren't available to generic plugins.

http://www.gnu.org/software/global/globaldoc_toc.html#Features_0028Vim_0029

In order to gain access to this for gnu global, a cscope interface had to be provided.

Here's an excerpt from an email exchange I had with gnu global's author Shigio YAMAGUCHI:

---

> Question: what was been the barrier to adding a tag stack to gtags.vim?

Because tag stack interface is not made public in VIM.
Since tag stack is hard coded in ctags and cscope interface,
we cannot use the facility without using cscope interface.

Elvis editor's way is very interesting.

---

It would be nice if the necessary hooks were exposed to allow any tagging system.  

Considering that Shigio integrated gnu global into several editors, it may be worth a look at investigating the method Elvis used.

**Comment by euclio** [comment]
@justinmk any interest in reopening this? I think it would be useful for language server plugins which currently have to resort to the jumplist to provide tag-like functionality.

**Comment by justinmk** [comment]
Yes, this is inevitable for LSP etc.

**Comment by aktau** [comment]
Just a question: what are the salient features the tag stack has over the jump list that would be useful for plugins?

**Comment by justinmk** [comment]
@aktau The tag stack specifically is useful because it works even when one has jumped all over the place. The "chain of tags" is a separate stack than jumps. I use it myself quite often, it's almost subconscious.

Regarding the more general nature of this request: `taglist()` and other tags-related features are Vim's "symbol index". Vim and plugins leveraging that index don't actually care where the "tags" come from. The "tags" should be settable by a more advanced backend. AFAIK currently that's not possible, unless one generates a fake ctags file.

**Comment by aktau** [comment]
Perhaps it would be nice to have a more unified interface. I see language plugins doing things like:

```vim
if get(g:, "go_def_mapping_enabled", 1)
  " these are default Vim mappings, we're overriding them to make them
  " useful again for Go source code
  nnoremap <buffer> <silent> gd :GoDef<cr>
  nnoremap <buffer> <silent> <C-]> :GoDef<cr>
  nnoremap <buffer> <silent> <C-LeftMouse> <LeftMouse>:GoDef<cr>
  nnoremap <buffer> <silent> g<LeftMouse> <LeftMouse>:GoDef<cr>
  nnoremap <buffer> <silent> <C-w><C-]> :<C-u>call go#def#Jump("split")<CR>
  nnoremap <buffer> <silent> <C-w>] :<C-u>call go#def#Jump("split")<CR>
  nnoremap <buffer> <silent> <C-t> :<C-U>call go#def#StackPop(v:count1)<cr>
endif
```

(This is from fatih/vim-go)

I'm just wondering what improvements we would get from allowing plugins to hook in at a lower (higher?) level than just overriding the "go to tags" functionality.

At least it'd be more consistent, since `:tn` and such would work.

**Comment by justinmk** [comment]
> I'm just wondering what improvements we would get from allowing plugins to hook in at a lower (higher?) level than just overriding the "go to tags" functionality.

Other than "go to tags",

1. `taglist()` allows (1) querying and (2) highlighting (relevant to your recent vim-gutentags issue)
2. tag stack

The alternative is to introduce a One True code-navigation interface. cscope already has overlap with the Vim's "tags" concepts. Both are ad-hoc and incomplete, as usual.

Making "tags" extensible doesn't preclude the One True code-navigation interface. I think both are warranted.

**Comment by garyburd** [comment]
> I'm just wondering what improvements we would get from allowing plugins to hook in at a lower (higher?) level than just overriding the "go to tags" functionality.

The improvement is that a plugin can share nvim's tag stack instead of using a plugin specific stack as vim-go does.

**Comment by aktau** [comment]
Seems reasonable, thanks for the explanation.

I've found some elvis(1) docs regardng tags: http://elvis.the-little-red-haired-girl.org/elvisman/elvistag.html.

The relevant bit:

> 14.8 The tagprg option
>
> As an alternative to Elvis' "restrictions" method for finding tags, you can set the tagprg option to a shell command line which locates the tags.
When you give a :tag command, Elvis evaluates the tagprg option's value using the simpler expression syntax. Any instance of $1 in the value will be replaced with the command-line arguments. Also, any text inside parentheses will be evaluated; this gives you a way to access other options' values, so you can do things like pass the value of the tags option to the program so it knows which tags files to search through.
>
> The resulting string is then executed, and its output is parsed as though it was a tags file. All of the tags that it outputs are considered to be matches, since using tagprg disables the use of restrictions.
>
> Elvis builds a list of the matches, and sorts them using the same history mechanism that is uses with restrictions. However, the "name:+value" and "name:-value" sorting hints are not detected in the arguments.
>
> Once the list has been built, Elvis moves the cursor to the first match. You can step through all matches in the list by hitting ^] or by giving the :ta command with no arguments, as usual.
> 
> Note that the program's output should be in the standard tags file format. At a minimum, this means "tagname TAB filename TAB address". If you want to use a function searching program that uses a different format, you'll need to pipe its output through a custom-made filter that converts its output to the standard tags format.
>
> One common technique is to use the :local command in an alias, to set tagprg temporarily for a single search. The :text alias in lib/elvis.ali is an example of this.

**Comment by chrisbra** [comment]
you might be interested in the tagfunc patch, that is floating around

**Comment by aktau** [comment]
@chrisbra, seems neat. Looks like [you're carrying this patch](https://github.com/chrisbra/vim-mq-patches/blob/master/tagfunc). What are you using it for (and how)?

As an aside, a crazy idea: it may be possible to extricate the hairy ctags/cscope code from the C tree (and make it quite efficient): [LuaJIT mmap for Windows](https://gist.github.com/ColonelThirtyTwo/4667673), UNIX is "trivial" ([this one](https://github.com/geoffleyland/lua-mmapfile) seems to do both UNIX and win32). `mmap` being "required" to avoid loading a possibly large tags file in memory while still running a bog-standard binary search on it. 

Then again with some proper refactoring the C equivalents could be nicer too, the current ctags/cscope mixture is quite... interesting. 

I also understand that the idea is to allow Neovim to be built with PUC Lua as well, which would disallow relying on the jit module.

**Comment by chrisbra** [comment]
I am not using it. I just picked it up and trying to push it for inclusion with Vim (not very successful however) every once in a while.

**Comment by justinmk** [comment]
> mmap being "required" to avoid loading a possibly large tags file in memory while still running a bog-standard binary search on it.

The idea is to serve Nvim with "tags" without actually using a tags backend. So a tags file wouldn't be involved, unless I'm missing something.

**Comment by aktau** [comment]
> The idea is to serve Nvim with "tags" without actually using a tags backend. So a tags file wouldn't be involved, unless I'm missing something.

Yes, it was just an aside statement. I was talking about externalizing the currently builtin ctags (and cscope) backend if we decide to go ahead with tagfunc/tagprg.

**Comment by aktau** [comment]
Just ignore the aside please. I just realized `taglist()` takes a Vim regex, which nobody wants to rebuild in another language. A cleanup of the C code at some point is the best we can do.

**Comment by justinmk** [comment]
Covered by `taglist()` and `'tagfunc'`  https://github.com/neovim/neovim/pull/11199
