### ISSUE TITLE
Suggestion: Increase `minline` in syntax file

### ISSUE THREAD

**Issue by htfy96** [neovim/neovim#3986]
For example, `minline` of html is only 10, which often causes incorrect behavior of highlighter. 

There are already tips (http://vim.wikia.com/wiki/Fix_syntax_highlighting) talking about this problem, and I found that the highlighter `html.vim` was written in 2005 or earlier (https://github.com/vim/vim/commits/master/runtime/syntax/html.vim). At that time HTML files were simple, and Javascripts embeded in them were relatively short, therefore `10` was enough. 

However, today's HTML often includes very long javascripts, and our computer runs faster than 10 years ago. Increasing `10` to `50` might be acceptable and provide better out-of-box user experience.
![screenshot from 2016-01-11 21-47-32](https://cloud.githubusercontent.com/assets/8121231/12235172/f03c42c6-b8ac-11e5-99f9-c31791de9776.png)

**Comment by wsdjeg** [comment]
I think you should open this issue in vim_dev,it is runtime file

**Comment by justinmk** [comment]
@htfy96 Reasonable observation, but yes, please send it to the maintainer email listed in the `runtime/syntax/html.vim` (or whatever) file, and also to vim_dev.
