### ISSUE TITLE
open big file (919990 lines) cost 25 seconds

### ISSUE THREAD

**Issue by huawenyu** [neovim/neovim#3987]
1) Issue 1:

<terminal-1>
```Shell
➜  ~  wc -l /tmp/log.tel
919990 /tmp/log.tel
➜  ~  time nvim /tmp/log.tel
nvim /tmp/log.tel  1.07s user 6.45s system 85% cpu 8.770 total
➜  ~  nvim /tmp/log.tel
```

start date in <terminal-2>
```Shell
➜  date
Mon Jan 11 13:33:20 PST 2016
➜  date
Mon Jan 11 13:33:45 PST 2016
```
2) Issue 2:

when I use plugin VOom, get the outline will take more than 20 seconds.

**Comment by justinmk** [comment]
- please try with `nvim -u NONE /tmp/log.tel`
- please compare with `vim -u NONE /tmp/log.tel` (_vim_, not _nvim_)
- please tell us your `:version` for vim and nvim

**Comment by huawenyu** [comment]
Another more lines (1706544) log file at home
===================================

Issue 1 not exists even enable plugins
--------------------------------------------------
nvim 3s
vim 2s

nvim is the version git clone from github these two days.

Issue 2 the VOom use more than 100s
----------------------------------------------------

but vim which open the VOom's outline only take several seconds.

vim version
---------------
vim.basic --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:32)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org

neovim version
--------------------
vi --version
NVIM v0.1.2-190-g50db031
Build type: Release

**Comment by ZyX-I** [comment]
VOom is using Python interface. I think it is doing far more RPC requests then it should. Profiling VOom by creating a wrapper script like

    #!/bin/sh
    python -m cProfile -o /tmp/profile "$@"

and pointing Neovim to use it via `g:python_host_prog` (I would really prefer doing this via configuration, but so far I see only how to do this via wrapper script) would be helpful.

**Comment by huawenyu** [comment]
python profile
==============

➜  cat python_profile.sh 
#!/bin/bash
/usr/bin/python -m cProfile -o /tmp/py_profile "$@"

➜  tail ~/.vimrc

let g:python_host_prog = "/home/test/script/python_profile.sh"
"let g:python_host_prog = "/usr/bin/python"

error message
-------------

if use python direct in vimrc, no error message:

let g:python_host_prog = "/usr/bin/python"

if use profile script, nvim have error message:

let g:python_host_prog = "/home/test/script/python_profile.sh"


```  nvim error
Error detected while processing function voom#Init:
line   40:
E117: Unknown function: provider#python#Call
Press ENTER or type command to continue
```

**Comment by ZyX-I** [comment]
@huawenyu Have you made the wrapper script executable?

**Comment by huawenyu** [comment]
Sure. Have update my last comment.

**Comment by ZyX-I** [comment]
@huawenyu It appears that cProfile does not support `-c`. So the scrapper script needs to look like

```Shell
#!/bin/sh
printf '<%s>' "$@" >> /tmp/pargs
echo "$$" >>/tmp/pargs
mkdir -p /tmp/profile
if test $# -ge 2 && test "x$1" = x-c ; then
  tmpfile="$(mktemp)"
  echo "$2" > "$tmpfile"
  shift
  shift
  python -m cProfile -o /tmp/profile/$$ "$tmpfile" "$@"
elif test $# -ge 1 && test "x${1#-}" = "x$1" ; then
  python -m cProfile -o /tmp/profile/$$ "$@"
else
  exit 1
fi
```

: this works for me. Tested with additionally set `let g:python_host_skip_check = 1` in order not to bother myself with also making whatever checks used work.

**Comment by huawenyu** [comment]
This is the profile's output top 10 functions:
```Shell
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pstats
>>> p = pstats.Stats('12316')                                                                  
>>> p.sort_stats('cumulative').print_stats(10)
Tue Jan 12 11:08:52 2016    12316

         4608032 function calls (4427353 primitive calls) in 27.288 seconds

   Ordered by: cumulative time
   List reduced from 801 to 10 due to restriction <10>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    44956    0.200    0.000   34.266    0.001 /usr/local/lib/python2.7/dist-packages/trollius/base_events.py:1121(_run_once)
        1    0.016    0.016   27.288   27.288 /tmp/tmp.SVCqOqND0Q:1(<module>)
        1    0.000    0.000   27.237   27.237 /usr/local/lib/python2.7/dist-packages/neovim/__init__.py:22(start_host)
        1    0.000    0.000   27.236   27.236 /usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py:43(start)
        1    0.000    0.000   27.236   27.236 /usr/local/lib/python2.7/dist-packages/neovim/api/common.py:233(run)
        1    0.000    0.000   27.236   27.236 /usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py:93(run)
        5    0.000    0.000   27.235    5.447 /usr/local/lib/python2.7/dist-packages/trollius/base_events.py:299(run_forever)
        3    0.000    0.000   27.235    9.078 /usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/async_session.py:56(run)
        3    0.000    0.000   27.235    9.078 /usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/msgpack_stream.py:35(run)
        3    0.000    0.000   27.235    9.078 /usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/event_loop/base.py:124(run)


<pstats.Stats instance at 0x7fb94e40c8c0>
>>> 
```

**Comment by huawenyu** [comment]
@ZyX-I open a log file still slow, test a new file in the office

vi 'with plugins' only take 1 seconds.
neovim 'with no plugins' take 3 seconds, even :qa also take 1 seconds.
```Shell
➜  wc -l /tmp/log.tel 
238521 /tmp/log.tel

➜  vi /tmp/log.tel

➜  nvim -u NONE /tmp/log.tel
➜  ~  date                                      
Tue Jan 12 11:42:32 PST 2016
➜  ~  date
Tue Jan 12 11:42:35 PST 2016
```

**Comment by ZyX-I** [comment]
@huawenyu Do not print stats, post the file. Top 10 functions are useless. Also it is better to post this to VOom as well since most likely (if no anomalies will appear, just calls time increase due to changed nature of Python-editor interaction) issue will be redirected to them.

**Comment by huawenyu** [comment]
The VOom is fast when used in vim.

[python_profile.zip](https://github.com/neovim/neovim/files/88080/python_profile.zip)

**Comment by ZyX-I** [comment]
@huawenyu IPC interface cannot possibly be as fast as in-process communication. So if there are no anomalies it is VOom which will have to adapt because Neovim could not.

**Comment by huawenyu** [comment]
@ZyX-I So maybe the 2nd issue is relative to VOom.

Do you have any ideal about the 1st issue? It happened in the office, not at home.

**Comment by justinmk** [comment]
@huawenyu Can you provide the file or is it private data?

> vi 'with plugins' only take 1 seconds.
> neovim 'with no plugins' take 3 seconds, even :qa also take 1 seconds.

What about the next time? If you repeat the steps, is it the same result each time?


Could be related:

- https://github.com/neovim/neovim/pull/3309#discussion_r39183283
- https://github.com/neovim/neovim/pull/3309#discussion_r39183336

I've been meaning to revisit those issues, which were confirmed as performance regressions in https://github.com/neovim/neovim/issues/3486

**Comment by huawenyu** [comment]
Can this valgrind file have some usefule about the problem ?
![1](https://cloud.githubusercontent.com/assets/4951149/12280649/8a45ddc2-b944-11e5-8720-5f5155f1bbbf.png)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/3486 maybe have resolved this. Please try on latest master (report `:version` if issue persists).

**Comment by huawenyu** [comment]
It's better now.

NVIM v0.1.2-358-g130611f
Build type: Debug

> $ nvim -u NONE /tmp/log.tel
About 2 seconds

> $ vi /tmp/log.tel
About 1 seconds
