### ISSUE TITLE
Editorconfig builtin support

### ISSUE THREAD

**Issue by Yamakaky** [neovim/neovim#3988]
It would be nice for neovim to support [editorconfig](http://editorconfig.org/) by default, maybe simply by including [this plugin](https://github.com/editorconfig/editorconfig-vim).

**Comment by justinmk** [comment]
"Nice to have" is a non-starter unless the cost is really zero. But the cost of shipping default plugins is far from zero, because it means someone must maintain them, regressions are filed (rightfully) against the core project, etc.

**Comment by steveno** [comment]
There are multiple ways to "support" it. It might not be worth the effort to go through the effort with the plugin, but neovim may still want to consider including a configuration file similar to how projects like angular.js do:

https://github.com/angular/angular.js/blob/master/.editorconfig

**Comment by justinmk** [comment]
It wouldn't make sense for a text editor to include a `.editorconfig`, because that's equivalent to a project-wide modeline. 

I just looked at https://github.com/editorconfig/editorconfig-vim and noticed it depends on python, so that really makes it unlikely.

**Comment by Pyrohh** [comment]
> It wouldn't make sense for a text editor to include a .editorconfig, because that's equivalent to a project-wide modeline.

Maybe I'm misunderstanding you, but I don't see how that's a bad thing. We have a coding style that people should adhere too, and http://editorconfig.org/#example-file makes it seem like configuration can be done on a per-file basis if needed.

> I just looked at https://github.com/editorconfig/editorconfig-vim and noticed it depends on python, so that really makes it unlikely.

I'm pretty sure @steveno is just talking about including a `.editorconfig` text file in the root repo, so the Python dep. wouldn't complicate things for us, right?

Do you mean it would be more work for contributors

**Comment by steveno** [comment]
@Pyrohh Yes. I was only suggesting including a ```.editorconfig``` file.

**Comment by justinmk** [comment]
Yes, I thought the suggestion was intended for end-users. I guess someone could drop it into `contrib/` but definitely not at root level.

**Comment by mcepl** [comment]
> I just looked at https://github.com/editorconfig/editorconfig-vim and noticed it depends on python, so that really makes it unlikely.

@justinmk  I know this bug is not about editorconfig plugin in the end, but just FYI there is https://github.com/sgur/vim-editorconfig which is pure VimScript and works just fine (I have added couple of patches myself).

**Comment by mcepl** [comment]
Yup, I am present on it as well, but the issue seem to be quite stalled (as most vim issues are until neovim makes the change ;)).

**Comment by justinmk** [comment]
https://github.com/sgur/vim-editorconfig/tree/master/autoload/editorconfig looks depressingly over-architected.

**Comment by mcepl** [comment]
> https://github.com/sgur/vim-editorconfig/tree/master/autoload/editorconfig looks depressingly over-architected.

Well, “over-architected” is always a bit in the eye of beholder. OTOH, it is really lovely to maintain, just one file per option. My PR to add those two options was just https://github.com/sgur/vim-editorconfig/pull/19.

**Comment by itsmeboy0** [comment]
Might be of interest:
https://github.com/gpanders/editorconfig.nvim

**Comment by mfussenegger** [comment]
With @gpanders already maintaining a editorconfig plugin maybe it would be worth to re-consider this?

Usually it is the users choice to use a certain plugin, but I think with editorconfig the situation is a bit different because there are two parties, the users and the maintainers. If a maintainer checks in an `.editorconfig` file they want contributors to use these settings. (Otherwise they'll likely reject a PR, or linting will fail anyway)

Currently contributors would need to make a conscious choice to opt-in by installing a plugin, and they might not even be aware of `.editorconfig` at all.
I think reversing that, so that they'd have to opt-out, would help maintainers everywhere to reduce CI waste and friction due to ill-formatted PRs
