### ISSUE TITLE
libtermkey is deprecated

### ISSUE THREAD

**Issue by ronisbr** [neovim/neovim#3991]
Hi guys!

I'm trying to add neovim package to openSUSE default repository and it turns out that one of its dependencies `libtermkey` is deprecated as per http://www.leonerd.org.uk/code/libtermkey/
>Note: This project is now DEAD; end-of-life. There will likely be no further releases.
>All of the code will be migrated into libtickit instead. libtermkey should not be used for new programs; use libtickit.

My question is: what should I do? Should I start to use the mirror https://github.com/neovim/libtermkey ? Will it be maintained?

Thanks!
Ronan

**Comment by justinmk** [comment]
Thanks for the report. We're aware of that, but there is nothing to replace libtermkey _with_ until its author (@leonerd) merges it into libtickit ;)

**Comment by ronisbr** [comment]
Thanks @justinmk!

**Comment by leonerd** [comment]
Additionally, I'm aware that neovim is using it. The big scary deprecation warning is there to stop *new* projects using it. I'm not going to leave neovim without a replacement path.

**Comment by ronisbr** [comment]
good! thanks @leonerd!
