### ISSUE TITLE
right-click sent FocusLost.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#3998]
here is my mini vimrc only one line,my os is ubuntu ,gnome-terminal.
```
autocmd FocusLost * :let g:cnt=get(g:, 'cnt', 0) + 1 | echomsg 'FocusLost' g:cnt
```
open a file with neovim 
`:message`
the type right-click in the message area, the message will be close ,and show me FocusLost 1
`:message` again
type right-click ,same as before,and show FocusLost 2
`:message` agagin
type `Alt` them show me FocusLost 6
`:message` again 
type `win`  which is `super` as os 7

EDIT:  I have test another terminal `terminator`  it works well ,but also some other button treated as FocusLost.I think maybe this butten sand an `esc` to the terminal

**Comment by justinmk** [comment]
What is `set mouse` ?

**Comment by wsdjeg** [comment]
I have tested `set mouse=` and  `set mouse=a `,get the same reslut,

**Comment by ZyX-I** [comment]
@justinmk `set mouse` should not be relevant, mouse events are not converted to FocusLost or something is completely wrong.

**Comment by justinmk** [comment]
Well, if the host terminal is showing a menu on right-click, wouldn't it makesense for FocusLost to fire?

**Comment by ZyX-I** [comment]
@justinmk It is terminal business to send FocusLost. Konsole does not do this.

Also note that with Vim FocusLost (GTK GUI) does not close messages. Have not checked the popup, but I guess it is not closed as well.

**Comment by wsdjeg** [comment]
gvim works well,vim in gnome-terminal works well,only neovim's message and popupmenu well be closed on right click,and this happebd not only when click on the message area,but also on the main area

**Comment by wsdjeg** [comment]
Anyone can help me ,is you are using ubuntu ,can you try with this issue?

**Comment by wsdjeg** [comment]
@justinmk I have change to ubuntu 14.04LTS,and this issue is gone.I think it is the issue of gnome-terminal, not neovim itself

**Comment by justinmk** [comment]
Thanks for followup. Must be libvte https://github.com/GNOME/vte

**Comment by wsdjeg** [comment]
thanks ,by the way,I think there is  no need to use the daily build ubuntu os now ,just waitting for the release version.

**Comment by wsdjeg** [comment]
@justinmk I just test in ubuntu 16.04(daily build) in virturlbox,
in gnome-terminal ,neovim still has this issue,gnome-terminal version is 3.18.2;
but now I am using ubuntu 14.04 with gnome-terminal 3.12.3,everything works well.

**Comment by justinmk** [comment]
Sounds like a configuration issue.

**Comment by wsdjeg** [comment]
not configuration issue,all test in same config,just with different gnome-terminal version

**Comment by ZyX-I** [comment]
@wsdjeg I guess he meant gnom-terminal configuration issue. Also note that we cannot and should not do anything with gnome-terminal sending FocusLost. It it the responsibility of terminal to send FocusLost and if you think it should not send FocusLost on certain events you need to go to to gnome-terminal bug tracker.

But we can and should do something with redraw on FocusLost and it was the meaning of the issue referenced from your previous issue that was closed as duplicate.

**Comment by justinmk** [comment]
For reference, FocusLost redraw issue: https://github.com/neovim/neovim/issues/3416

**Comment by wsdjeg** [comment]
agree with you @zyx-i
