### ISSUE TITLE
:term + 'shell' with arguments

### ISSUE THREAD

**Issue by FriedSock** [neovim/neovim#3999]
I used to have `set shell=/bin/bash\ --login` in my nvimrc, but after updating to latest HEAD I get the error
`E902: "/bin/bash --login" is not an executable`

Is it no longer possible to pass arguments as part of the shell command?

**Comment by justinmk** [comment]
Most likely a result of https://github.com/neovim/neovim/pull/3980. cc @ZyX-I no good deed goes unpunished!

**Comment by gmg137** [comment]
My profile is set to nvimrc does not work?
Use only. config/nvim/init.vim

**Comment by mhinz** [comment]
@gmg137 That is correct. See `:h vimrc`.

**Comment by ZyX-I** [comment]
@justinmk This must not be the result of #3980: I added unquoting and backslash processing inside quotes, not removed splitting.

**Comment by ZyX-I** [comment]
@justinmk And this setting works for me.

**Comment by ZyX-I** [comment]
@justinmk And note the location of the error message. You *cannot* enter this code path with something like `system(string)`: tv_to_argv will exit earlier. So this is completely impossible that *any* change to `&shell` processing will emit E902 unless tv_to_argv was also changed.

This is at 3b94756, which is after my PR was merged.

**Comment by ZyX-I** [comment]
Though updating to bf7bc4d did not change anything.
