### ISSUE TITLE
Browse oldfiles

### ISSUE THREAD

**Issue by bounceme** [neovim/neovim#4011]
After using :browse oldfiles there should be a prompt asking for the number of the file you want to choose but this doesn't appear in neovim. also it would be nice to be able to search in this interface with "/"

**Comment by mhinz** [comment]
`:browse` was removed. Use `:oldfiles!` instead.

**Comment by sethjackson** [comment]
We should probably add a note to `vim_diff.txt` that `:browse` has been removed.

**Comment by Pyrohh** [comment]
Good point, but it should be mentioned that it's a no-op, i.e., not *completely* removed.

**Comment by sethjackson** [comment]
> Good point, but it should be mentioned that it's a no-op, i.e., not completely removed.

:+1:
