### ISSUE TITLE
Standard style of casts

### ISSUE THREAD

**Issue by cacplate** [neovim/neovim#4023]
I've noticed that the default, when casting, is to write like this: `(type)variable`. But I have seen examples done like this: `(type) variable` (notice the space). Do you think we need a standard way writen in the style guide and enforced by `clint.py`?

**Comment by sethjackson** [comment]
I would prefer that there is a standard and that the linter enforces it. So :+1: from me.

Don't know how hard this would be for the linter to do though.

**Comment by cacplate** [comment]
@ZyX-I I noticed you used the second in the `shada.c` file. What are your thought?

**Comment by ZyX-I** [comment]
I usually use something like `\((?:const\x20)?{type}(?:\x20\*+(?:const(?!\))?)*\)\x20`: i.e. with space before casted expression and a space before `*` in case of pointer casts, if using something like `const type *const *const` cast looks like `(const {type} *const *) {expr}` (actually may also write third `const` in a cast, but this is better not to do).
