### ISSUE TITLE
Light/dark blocks at the end of each line

### ISSUE THREAD

**Issue by sirex** [neovim/neovim#4040]
Today, after updating neovim from PPA on Ubuntu 14.04 to version `NVIM 0.1.2-dev`, standard theme `desert` (from `/usr/share/vim/vim74/colors/desert.vim`) only with Python files started to show single space character with light background at the end of each line.

Here is how it looks:

![shot-001](https://cloud.githubusercontent.com/assets/297583/12386055/8e892166-bdca-11e5-9efa-f82a5c65dde1.png)

`$NVIM_TUI_ENABLE_TRUE_COLOR` is set to `1`.

Link to the desert theme: http://www.vim.org/scripts/script.php?script_id=105

Maybe something has changed?

How can I get rid of these light spaces at the end of each line?

**Comment by henrik-farre** [comment]
I have dark blocks at the end :)

Running neovim in urxvt 9.21-3 with tmux 2.1-1 and NVIM_TUI_ENABLE_TRUE_COLOR is not set

**Comment by jbradaric** [comment]
This seems to be introduced with vim patch 7.4.721. This issue is fixed when vim patch 7.4.729 is applied, but that patch also introduces new issues and makes some tests fail.

**Comment by jbradaric** [comment]
This is probably fixed since #4012 has been merged.

**Comment by sirex** [comment]
Just upgraded to `0.1.1ubuntu1+git201` form PPA (`http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu trusty main`), not sure if this pach is included into this release, but blocks are still visible.

**Comment by justinmk** [comment]
@sirex Based on the timestamps in http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/devel/ it will not get this change until 9pm today.

**Comment by sirex** [comment]
I can confirm, that after today's upgrade to `neovim-0.1.1ubuntu1+git20160` from PPA, this bug is gone.
