### ISSUE TITLE
Link in FAQ is broken

### ISSUE THREAD

**Issue by LucasCampos** [neovim/neovim#4043]
In the [Technical-FAQ](https://github.com/neovim/neovim/wiki/Technical-FAQ) the link to convince the reader to use Lua is broken. The link can be found [here](http://blog.datamules.com/blog/2012/01/30/why-lua/).

**Comment by fwalch** [comment]
It's a wiki, so you're welcome to make improvements yourself :-)

**Comment by Pyrohh** [comment]
archive.org is down too, so I just removed the link for now.

**Comment by justinmk** [comment]
Well, that link was valuable, so I suggest waiting for it to recover and/or find a mirror.

**Comment by Pyrohh** [comment]
I think so too, as I mentioned it [in the commit message](https://github.com/neovim/neovim/wiki/Technical-FAQ/_history).

I'll check back tomorrow and see if archive.org is back up, unless someone beats me to it.
