### ISSUE TITLE
% command in markdown file not work well

### ISSUE THREAD

**Issue by dgeibi** [neovim/neovim#4051]
Arch Linux
NVIM 0.1.1 (compiled Dec  5 2015 22:03:57)

in markdown file or md file

"%" can only make the cursor move from "(" to the matching ")", "[" to "]" or "{" to "}" **ONCE**!

**Comment by mhinz** [comment]
This also happens in Vim and seems to be related to the `matchit.vim` plugin.

**Comment by dgeibi** [comment]
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 13 2016 12:07:37)
Garbage after option argument: "-version"
More info with: "vim -h"
```
in the lastest vim, the bug is fixed.

**Comment by mhinz** [comment]
It's not fixed for me on 7.4.1112.

**Comment by chrisbra** [comment]
@mhinz A CC should be okay. Usually I notice it then. Unfortunately, I did not get any notice for this one here. I'll check the problem here

**Comment by chrisbra** [comment]
I think, this patch fixes it https://groups.google.com/forum/#!topic/vim_dev/wT28u7JLhUk

**Comment by wsdjeg** [comment]
why I can not reproduce this issue?
test my 
```
rm ~/.vimrc
vim test.md
```
type into {aaaaaaaaaaaaaaaaaa}

then I can use `%` jump between `{`and `}` anytimes as I want

os ubuntu 14.04
![2016-01-26 19 46 35](https://cloud.githubusercontent.com/assets/13142418/12579783/885fad68-c465-11e5-9a17-1461a196d6a4.png)

**Comment by dgeibi** [comment]
on Arch Linux
vim 7.4.1089-1 can't reproduce this issue
but neovim 0.1.1-2 can

**Comment by chrisbra** [comment]
On Di, 26 Jan 2016, Xavier Peng wrote:

> on Arch Linux
> vim 7.4.1089-1 can't reproduce this issue
> but neovim 0.1.1-2 can

Make sure to source the matchit plugin.

Christian
-- 
Ein Hacker macht einen Fehler nur einmal versehentlich. Dann immer mit Absicht.

**Comment by dgeibi** [comment]
Thanks @chrisbra . After applying your patch, "%" works well. But I'm still confused that vim can't reproduce this issue.

```
diff --git a/usr/share/vim/vim74/macros/matchit.vim b/usr/share/nvim/runtime/plugin/matchit.vim
index 70867b1..74c1a1e 100644
--- a/usr/share/vim/vim74/macros/matchit.vim
+++ b/usr/share/nvim/runtime/plugin/matchit.vim
@@ -303,7 +303,7 @@ fun! s:CleanUp(options, mode, startline, startcol, ...)
       let regexp = s:Wholematch(matchline, a:1, currcol-1)
       let endcol = matchend(matchline, regexp)
       if endcol > currcol  " This is NOT off by one!
-       call cursor(0, endcol)
+       execute "normal!" . (endcol - currcol) . "l"
       endif
     endif " a:0
   endif " a:mode != "o" && etc.
```

**Comment by chrisbra** [comment]
I have the problem in Vim as well. What is your patch for?

**Comment by dgeibi** [comment]
It's not a patch. Just compare two matchit.vim in vim74 and neovim. Copying matchit.vim from vim74 to neovim don't work at all.

**Comment by wsdjeg** [comment]
I just test this in win7,with gvim ,a nd can not reproduce this issue,
test file 
test.md
```markdowd
{
[  (  { test  }   ) ]
}
```
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:33:40)
MS-Windows 32 位控制台版本
编译者 mool@tororo
大型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+arabic          +ex_extra        -mouseshape      +tag_binary
+autocmd         +extra_search    +multi_byte      +tag_old_static
-balloon_eval    +farsi           +multi_lang      -tag_any_white
-browse          +file_in_path    -mzscheme        -tcl
++builtin_terms  +find_in_path    -netbeans_intg   -tgetent
+byte_offset     +float           +path_extra      -termresponse
+cindent         +folding         -perl            +textobjects
+clientserver    -footer          +persistent_undo +title
+clipboard       +gettext/dyn     -postscript      -toolbar
+cmdline_compl   -hangul_input    +printer         +user_commands
+cmdline_hist    +iconv/dyn       -profile         +vertsplit
+cmdline_info    +insert_expand   -python          +virtualedit
+comments        +jumplist        -python3         +visual
+conceal         +keymap          +quickfix        +visualextra
+cryptv          +langmap         +reltime         +viminfo
+cscope          +libcall         +rightleft       +vreplace
+cursorbind      +linebreak       -ruby            +wildignore
+cursorshape     +lispindent      +scrollbind      +wildmenu
+dialog_con      +listcmds        +signs           +windows
+diff            +localmap        +smartindent     +writebackup
+digraphs        -lua             -sniff           -xfontset
-dnd             +menu            +startuptime     -xim
-ebcdic          +mksession       +statusline      -xterm_save
+emacs_tags      +modify_fname    -sun_workshop    -xpm_w32
+eval            +mouse           +syntax
```

**Comment by FernandoTorres** [comment]
Got the same issue using Vim 7.4 (and 7.3) on OSX 10.11.4.

I also tried deleting the `matchit.vim` file from my `~/.vim/plugins` folder since it is supposed (verified) that the plugin comes with Vim on its installation folder, but lost the matching behaviour on html tags (I guess I went back to the basic % behaviour).

This only happened on .markdown files

All the matchit.vim files are version 1.13.2, although I found a couple of differences among the system installed file and mine under `~/.vim/plugins`. Anyways, the misbehaviour is the same in all cases.

I also tried disabling all the other plugins ... same result.

**Comment by adriaanzon** [comment]
This happens to me as well. In php files it only occurs on brackets `[]`, just like https://github.com/neovim/neovim/issues/3299.

After I run `:MatchDebug` the problem goes away temporarily.

**Comment by lfilho** [comment]
Also happening to me. Latest Nvim (0.2.0). And using https://github.com/vim-scripts/matchit.zip
Should I not use that matchit plugin but only the one that ships with (n)vim?

**Comment by justinmk** [comment]
f96dfae52fe5ec211f6cfdf539882f2d10806374 already fixed this.

> Should I not use that matchit plugin but only the one that ships with (n)vim?

Correct.
