### ISSUE TITLE
Weird symbol/character in front of filename when opening new file

### ISSUE THREAD

**Issue by inconvergent** [neovim/neovim#4057]
Whenever I open a file I get a weird glyph in front of the filename in the lower left (status line?).

![example](https://pbs.twimg.com/media/CZK7pXeVIAAlx8W.jpg)

I have tried to remove all plugins (with no luck), but attached image has airline enabled.

When I start editing the symbol goes away. 

Behaviour is independent of file type, and I am not using screen/tmux etc. 

My .vimrc (nvim/init.vim) is here: https://github.com/inconvergent/.dotfiles/blob/master/vimrc

Output from `nvim --version`

    NVIM 0.1.2-dev
    Build type: RelWithDebInfo
    Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/build/config -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/src -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-jQr9Z8/neovim-0.1.1ubuntu1+git201601181844+2175+16~ubuntu14.04.1/build/include
    Compiled by buildd@lgw01-41

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
    For differences from Vim, see :help vim-differences

     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/usr/share/nvim"

I'm using gnome-terminal in Ubuntu.

Happy to post more info if you let me know what you need.

**Comment by wsdjeg** [comment]
I also use gnome terminal ,but can not reproduce this issue ,can you try with `nvim -u NONE -N`

**Comment by inconvergent** [comment]
I just did. It does not happen when i start vim that way. 

Bried both 

`nvim -u NONE -N` (then open file)
and 
`nvim -u NONE -N filename.txt` 

Both are fine.

**Comment by wsdjeg** [comment]
what is the output of `tput colors` in terminal?

**Comment by inconvergent** [comment]
256

**Comment by wsdjeg** [comment]
what is the version of your gnome-terminal ,maybe you can try with 
```shell
sudo add-apt-repository ppa:gnome3-team/gnome3-staging
sudo apt-get update
sudo apt-get install gnome-terminal
sudo add-apt-repository -r ppa:gnome3-team/gnome3-staging

```

**Comment by inconvergent** [comment]
GNOME Terminal 3.6.2

I'd rather not mess with the terminal on this computer (at work) right now. I'll try your suggestion when I get home.

**Comment by inconvergent** [comment]
problem goes away when i comment out 

`:set title`

from my .vimrc file.

**Comment by wsdjeg** [comment]
3.6.2 has a lot bug with neovim ,also can not enable ture color,and I think this issue is cause by gnome-termianl

**Comment by wsdjeg** [comment]
if you want to use the latest version of gnome-terminal ,remanber remove the source list after installing ,
```
sudo add-apt-repository -r ppa:gnome3-team/gnome3-staging
```

**Comment by inconvergent** [comment]
Thanks. i'll post when I've tried newer terminal.

**Comment by inconvergent** [comment]
I got impatient and installed new terminal. the behaviour described above persists. (removing :set title hides/fixes the issue).

**Comment by wsdjeg** [comment]
really Strange ,I am using ubuntu 14.04, and everthing works well

**Comment by inconvergent** [comment]
This isn't exactly a major issue for me. And it might very well be some other weird interaction on my system, but i'll leave that decision to someone else.

**Comment by wsdjeg** [comment]
hmm,there is no `set title` in my vimrc -_-

**Comment by justinmk** [comment]
> I got impatient and installed new terminal. the behaviour described above persists.

Is it a libvte-based terminal? If so, then nothing would change, assuming you are still using the same version of libvte. https://github.com/neovim/neovim/issues/3875

**Comment by justinmk** [comment]
Going to assume this is covered by https://github.com/neovim/neovim/issues/3875. Still would like to know the version of libvte being used.

**Comment by inconvergent** [comment]
Thanks for your replies. libvte info below:

    Package: libvte-2.90-9
    Status: install ok installed
    Priority: optional
    Section: libs
    Installed-Size: 1123
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: amd64
    Source: vte3
    Version: 1:0.36.3-1ubuntu1~trusty1
    Depends: libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.10.0), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk-3-0 (>= 3.3.18), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.22.0), libtinfo5, libx11-6, libvte-2.90-common (= 1:0.36.3-1ubuntu1~trusty1)
    Description: Terminal emulator widget for GTK+ 3.0 - runtime files
     The VTE library provides a terminal emulator widget VteTerminal for
     applications using the GTK+ toolkit. It also provides the VtePTY object
     containing functions for starting a new process on a new
     pseudo-terminal and for manipulating pseudo-terminals.
     .
     This package contains the runtime library, needed by programs using the
     VTE widget with GTK+ 3.0.
    Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
