### ISSUE TITLE
Cannot open nvim from within nvim

### ISSUE THREAD

**Issue by 3cooper** [neovim/neovim#4062]
I understand this might be a dumb issue, but its something that I was able to do in vim that I can not do in neovim.

I have a command I run that can take the current file, diff it to CVS, and it opens the diff in vimdiff.  When trying to do this in neovim I get the following:

~~~~
:!nvim

Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...

Vim: Finished.
 [?1049h [H [J [?2004h [?1004h [8;24;80t [1;1H [m  [38;5;188m [48;5;233m                                                                                 [2;1H
shell returned 1

Press ENTER or type command to continue
~~~~

Here I am just trying to open nvim but the same thing happens when I pass files and the diff option.  I am running 0.1.1 on OS X 10.11.2.  I have switched to opening a tab and diffing there, but in this case I prefer to open a new instance of the editor so I don't add unwanted items to my buffer list.  Any help would be great.

**Comment by ThomasFeher** [comment]
You could use the build-in terminal and start neovim there using `:terminal nvim`

**Comment by 3cooper** [comment]
I thought about that but didn't like the idea of nesting nvim instances.  Thanks.

**Comment by wsdjeg** [comment]
I think `:terminal vim ` or `:terminal nvim` will works better than  window's gvim ,gvim also open a black cmd windows.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/1496
