### ISSUE TITLE
Add missing bzl filetype detection

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#4067]
vim/vim@60cce2fb73 includes support for the "bzl" (http://bazel.io) filetype in vim, but it hasn't been merged into neovim. Can we pull it in?

**Comment by Shougo** [comment]
You can create the Pull request like this.

https://github.com/neovim/neovim/pull/4066

**Comment by dbarnett** [comment]
Yep, just wanted to confirm I wasn't missing something. Are all vim patches pulled in individually as cherry-picks, or does anyone periodically merge all/most runfile changes or evaluate the complete diff? It's surprising that the "Last change" date comes from a cherry-pick and reflects the date of the _newest_ change, not the oldest.

**Comment by fwalch** [comment]
@dbarnett Usually, these PRs are created with `scripts/vim-patch.sh` (so "cherry-picked", one commit here for each Vim commit). Runtime patches *should* be merged in chronological order to minimize merge conflicts, but it doesn't always happen like that.

**Comment by dbarnett** [comment]
Okay, I'm running into a lot of merge conflicts from some very old runtime files in neovim that aren't matching the diff LHS. I spent some time backtracking to try to find a sequence of patches to cleanly get from there to here, but it gets really confusing with the nonsense dates and version numbers. Is it okay to just merge the files I care about from that runtime update? Or can someone figure out what patches we need to get sh.vim updated to say `" Version:		137` instead of `" Version:		132`?

**Comment by justinmk** [comment]
By "very old" do you mean earlier in 2015? We're still behind a few runtime patches. Better to start with the oldest one (just run `./scripts/vim-patch.sh -l` to list the missing patches).
