### ISSUE TITLE
:Man clobbers $MANWIDTH

### ISSUE THREAD

**Issue by george-b** [neovim/neovim#4068]
It appears `man.vim` overrides `$MANWIDTH` with the current window width.

https://github.com/neovim/neovim/blob/bcbcf235f61bd75f965f35897784ea618fe7acb8/runtime/autoload/man.vim#L78

* This produces a man page formated differently then when simply opened from
  `man` on the command line if `$MANWIDTH` is set.

* If `$MANWIDTH` is not set, but `textwdith` is set within the editor the output
  again may not be formatted as one may expect.

Odds are one of the above will be set.

* We could simply remove the line and if `$MANWIDTH` is not set long lines are
  wrapped per the user configuration/ default.

* We could override `$MANWIDTH` to be the same as `textwidth`. One could argue
  that we have asked the man page to be viewed in the editor and as such should
  conform to the default formatting of text as in the rest of our windows.

I'm leaning towards the later option. We could make this a variable which can be
set from a user's config file but as no-one has complained about this before I
think we can keep this to a one line change :smile: 

I would note the above is true for Vim as well.

**Comment by george-b** [comment]
Would people be open to a pull request to the effect of something like the following?

```diff
--- a/runtime/autoload/man.vim
+++ b/runtime/autoload/man.vim
@@ -75,7 +75,7 @@ function man#get_page(...) abort

   setlocal modifiable
   silent keepjumps norm! 1G"_dG
-  let $MANWIDTH = winwidth(0)
+  let $MANWIDTH = &textwidth
   silent exec 'r!/usr/bin/man '.s:cmd(sect, page).' | col -b'
   " Remove blank lines from top and bottom.
   while getline(1) =~ '^\s*$'
```

**Comment by justinmk** [comment]
@george-b If MANWIDTH is set it should never be overridden, right? I suggest:

- respect MANWIDTH if it's set
- else use `winwidth()` if it is less than `&textwidth` (DWIM)
- else use `&textwidth`

We should also adjust on window-resize. But there isn't a "window resized" event...?

**Comment by george-b** [comment]
> @george-b If MANWIDTH is set it should never be overridden, right?

This is what I'm not sure of (see the forth bullet point in my original comment). Then again I think the odds of these being different are slim to none (provided both are set).

> * else use `winwidth()` if it is less than `&textwidth` (DWIM)

Again I'm not certain here, what the are the odds of the `winwidth` being less than `textwidth` in a general layout? Would a user typically have splits open that can't fit `textwidth` without wrapping? Granted with man pages this may be not as nicely formatted until a window is closed but then this comes to your point about events for windows being resized.

**Comment by justinmk** [comment]
If we're not going to respect MANWIDTH then I don't see what's wrong with the current logic as-is.

> , what the are the odds of the winwidth being less than textwidth in a general layout?

**Comment by george-b** [comment]
> If we're not going to respect MANWIDTH then I don't see what's wrong with the current logic as-is.

Currently IMHO text is not formatted as expected, that is unless both `$MANWIDTH` and `textwdith` are not set.

I don't disagree with your points it was just uncertainty on my part. I can look into modifying this to behave as per your original reply.
