### ISSUE TITLE
:Tutor doesn't work

### ISSUE THREAD

**Issue by VorT3x** [neovim/neovim#4071]
Info:
OS: OS X 10.11.3
NVim: 0.1.1 

Steps to reproduce:
1) Open nvim
2) Type command :Tutor

Expected result:
Tutorial will be launched.

Actual result:
```
Error detected while processing function tutor#TutorCmd..<SNR>89_GlobTutorials:
line    5:
E684: list index out of range: 0
E116: Invalid arguments for function s:GlobPath(&rtp, 'tutor/'.s:Locale()[0].'/'.a:name.'.tutor')
E15: Invalid expression: s:GlobPath(&rtp, 'tutor/'.s:Locale()[0].'/'.a:name.'.tutor')
line    7:
E121: Undefined variable: l:locale_tutors
E116: Invalid arguments for function len(l:locale_tutors) == 0
E15: Invalid expression: len(l:locale_tutors) == 0
line   10:
E121: Undefined variable: l:locale_tutors
E116: Invalid arguments for function extend
No tutorial with that name found
```

**Comment by fmoralesc** [comment]
OK, I think I know what is going on here. @VorT3x, can you report what is the value of `v:lang` in your build? Also, does this happen in a properly setup nvim or by running it from the build dir?

**Comment by VorT3x** [comment]
Hi @fmoralesc,

This is fully configured nvim instance. 
:lang says: `Current language: "C"`

Or how I can check v:lang?

Regards,
Dmitri

**Comment by fmoralesc** [comment]
Hm, that might be part of the issue. Please execute `:echom v:lang` within nvim and tell me the output. 

I think the language detection code in `:Tutor` might be faulty, and it isn't handling your setup properly.

**Comment by VorT3x** [comment]
`echom v:lang` result is `C`

**Comment by fmoralesc** [comment]
OK, thanks. I guess I didn't remember to account for the "C" locale, my bad.

Can you test if this version of s:Locale() (in `runtime/autoload/tutor.vim`) fixes it?

~~~ vim
function! s:Locale()
    if exists('v:lang') && v:lang =~ '\a\a'
        let l:lang = v:lang
    elseif $LC_ALL =~ '\a\a'
        let l:lang = $LC_ALL
    elseif $LANG =~ '\a\a'
        let l:lang = $LANG
    else
        let l:lang = 'en_US'
    endif
    return split(l:lang, '_')
endfunction
~~~
If not possible, don't worry, I'll open a PR any way.

**Comment by VorT3x** [comment]
@fmoralesc 

I've checked it! Now :Tutor works! :+1: 
Good job!

**Comment by fmoralesc** [comment]
;)

**Comment by Rapid-Turtle** [comment]
> Hm, that might be part of the issue. Please execute `:echom v:lang` within nvim and tell me the output.
> 
> I think the language detection code in `:Tutor` might be faulty, and it isn't handling your setup properly.

Running this code seems to have solved the problem in my case.

**Comment by Password-Classified** [comment]
I had this same issue @dlogvinenko but I solved it by not opening neovim in a folder, but just by typing `nvim` in the terminal. If you then run `:Tutor` it should work. `:Tutor` does not work when a file has been opened or a folder has been opened at the same  time.
