### ISSUE TITLE
I love Lua, but

### ISSUE THREAD

**Issue by lexazloy** [neovim/neovim#4077]
Hi.

Remarks:
* I know developers already choose Lua.
* I have read [Technical-FAQ](https://github.com/neovim/neovim/wiki/Technical-FAQ).
* I have read issues a-la "Lua vs X".

But until i have change to speak and change spotlight alternative to developers i will try. :)

First. Lua is great. Lua codebase is small, longlife, "lick clean". Its perfect.

Except one thing: `end`. Every block end w/ `end`.  And its terrible.

[MPV](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua):
```lua
                            end
                        end
                    end
                end
            end
        end
```

[Awesome WM](https://github.com/awesomeWM/awesome/blob/master/lib/awful/keygrabber.lua):
```lua
                return false
            end
        else
            return false
        end
    end
    return true
end
```
[ngx_lua_waf](https://github.com/loveshell/ngx_lua_waf/blob/master/waf.lua):
```lua
				end
			end
		end
    end
else
    return
end
```

And end, end,  end,  end,  end...

Opps. I mean etc, etc, etc, etc. :)

Its how NeoVim plugins will be looks like.

How about language that everybody know or familiar w/?
Language that exists everywhere.
Language that support C-like master race syntax?

That super-duper language dont exists? Wrong. Cmon ppl, its ECMAScript.

Look at [Duktape](https://github.com/svaarala/duktape). Its small, embeddable, portable implementation of ECMA-262. At all it has Lua-like API.

`Technical-FAQ` says:
> Lua is a very small language

Duktape: check.

> it provides everything we need to implement a language like Vimscript, which was created to configure and script the editor.

Check.

> Python or Ruby have over Lua are their huge library collections, but that isn't a factor for our main use case which is to remove thousands of lines of C by using Lua as a Vimscript runtime.

Check.

> If you are still not convinced about Lua, you might want to read this post.

Replace "Lua" to "Duktape" (ignore DuktapeJIT :)) and check.

end

**Comment by justinmk** [comment]
Don't need more drive-by half-thoughts.

**Comment by wsdjeg** [comment]
@justinmk I think the most important thing is to fix the compatibility between VIM and, so that VIM users easily go to the NEOVIM, we need more supporters to find and fix problems,I just read the message in gitter.im, It is a important year for neovim.
