### ISSUE TITLE
neovim shrinks roxterm on startup

### ISSUE THREAD

**Issue by fxkr** [neovim/neovim#4081]
When I start neovim in a roxterm window that is not maximized, the roxterm window (!) gets resized to 4 rows x 15 cols. The bug doesn't happen in gnome-terminal, xterm and urxvt.

git bisect tells me that 6048e95f33161420f9d863a2ce5ccf9464df2dba is the first bad commit

(Additionally, during testing roxterm crashed once while resizing a roxterm window with nvim in it and once when nvim resized roxterm on startup.)

**Comment by justinmk** [comment]
Are you setting `'lines'` in your vimrc? See https://github.com/neovim/neovim/issues/2403.

> roxterm crashed once while resizing a roxterm window with nvim in it

That's a roxterm bug.

**Comment by fxkr** [comment]
I tested it without a vimrc/nvimrc.

To be sure I just tested it with `nvim -u NORC` and `nvim -u NONE` too, same behavior.

And if the problem was #2403, I'd expect the window to be resized to 24x80. But it gets much smaller than that. Actually, I wouldn't expect the terminal emulator window to be resized due to #2403 at all.

So this here is probably not a duplicate of #2403.
