### ISSUE TITLE
Echoing very long line may result in crash or hang at exit

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#4084]
Consider the following code:

```
nvim -u NONE --cmd 'let l=[]' --cmd 'call map(range(1024*1024), "extend(g:, {\"l\": [g:l]})")' --cmd 'echo (l)'
```

If you press `<C-c>` while line is still echoed Neovim crashes. If you wait and type `:qa<CR>` it will hang and if you happen to connect with the debugger while hanging it will SEGV which is pretty weird. More weird is the stack trace after SEGV: lots of `garbage_collect->set_ref_in_ht->eval_to_number` recursive calls with incorrect line numbers and incorrect arguments (expr=eval_to_number+157 to eval_to_number up until last item on the stack where it is NULL), same for `<C-c>`.

Tested on 4172ce4eb078fe63cf3696dd10f9bdf47cd70eb1 with WIP https://github.com/ZyX-I/neovim/commit/2fe7ac179dfbd4ca157d7b0d23ee8f08e07db8b4 which should not affect the bug.

**Comment by justinmk** [comment]
Seems to be fixed on master. Didn't crash, printed out the string, ended with press-enter prompt, then loaded UI after pressing enter. CTRL-C case cancels and exits without showing UI.
