### ISSUE TITLE
some coloured highlighted text in a terminal buffer does not have its foreground/background set

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4085]
<img width="1440" alt="screen shot 2016-01-23 at 11 31 18 pm" src="https://cloud.githubusercontent.com/assets/10180857/12534510/1003c620-c22a-11e5-812e-87a9d8eac148.png">

As you can see in that screenshot I have a terminal buffer opened. In this terminal buffer I have a script that generates a rectangular matrix with the text `colour\d+` where `\d+` represents a unique colour number in the terminal. 

Using the number I colour each item's fg and bg. Now if I enter normal mode and search for `colour\d+` for some reason I do not understand only colour0, colour16 and colour232 are highlighted though I can cycle through every item by pressing `n`. 

You can also see my cursor in the middle showing the text that is coloured.

Script for testing looks like this (zsh but may run in bash):

``` zsh
typeset -Ag FX FG BG

FX=(
reset     $'\e'"[00m"
bold      $'\e'"[01m" no-bold      $'\e'"[22m"
italic    $'\e'"[03m" no-italic    $'\e'"[23m"
underline $'\e'"[04m" no-underline $'\e'"[24m"
blink     $'\e'"[05m" no-blink     $'\e'"[25m"
reverse   $'\e'"[07m" no-reverse   $'\e'"[27m"
)

for i in {0..255}; do
    FG[$i]=$'\e'"[38;5;${i}m"
    BG[$i]=$'\e'"[48;5;${i}m"
done

function lsc() {
echo -en "$FX[bold]"
for i in {0..255}; do
    echo -en "$BG[$i]"
    echo -en "$FG[$i]"
    printf "%+12s" "colour$i"
    if (( ($i + 1) % 8 == 0 )); then
        printf "\n"
    fi
done
echo -e "$FX[reset]"
}
```

Just run lsc after sourcing it.

**Comment by justinmk** [comment]
Possibly related: https://github.com/neovim/neovim/issues/3459

**Comment by nhooyr** [comment]
Fixed at some point.
