### ISSUE TITLE
seemingly random colours in terminal buffer?

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4087]
<img width="1440" alt="screen shot 2016-01-24 at 12 18 57 am" src="https://cloud.githubusercontent.com/assets/10180857/12534621/33f705a0-c230-11e5-826e-76cbb7f96bbd.png">

Notice at the bottom left how the colour of the `/` and `l` are purple with a darker bg? Very weird. it happens in random spots for me as well, they show up as just random black spots in the buffers. I've noticed them from time to time. The colours are of my `Function` highlight group. Now if I leave terminal mode and enter normal mode. 

<img width="1440" alt="screen shot 2016-01-24 at 12 19 04 am" src="https://cloud.githubusercontent.com/assets/10180857/12534618/2a5f6712-c230-11e5-9f99-f784245dbd4d.png">

Tis gone.

**Comment by justinmk** [comment]
Merging with https://github.com/neovim/neovim/issues/3459 unless minimal repro steps can show otherwise.
