### ISSUE TITLE
how to set colorscheme of terminal buffer?

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4088]
I an using gruvbox for neovim ,and with the `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` in my vimrc,but the colorscheme is different in terminal buffer.
![2016-01-24 14 41 19](https://cloud.githubusercontent.com/assets/13142418/12534904/994a5fb0-c2a8-11e5-9c89-5f7d3e402364.png)
![2016-01-24 14 41 27](https://cloud.githubusercontent.com/assets/13142418/12534905/994b7a58-c2a8-11e5-8f58-7f5994a148c4.png)

**Comment by nhooyr** [comment]
Its using whatever your shell's colors are. This isn't a neovim issue. You have to configure zsh/bash or whatever shell you use yourself.

**Comment by wsdjeg** [comment]
I know,but it is still different with my gnome-terminal,maybe it is due to gnome-terminal's color setting
![2016-01-24 15 25 10](https://cloud.githubusercontent.com/assets/13142418/12535012/ace83abe-c2ae-11e5-862c-59ce34488442.png)
![2016-01-24 15 26 04](https://cloud.githubusercontent.com/assets/13142418/12535014/ce6bb904-c2ae-11e5-8746-83e50b5af0ce.png)

**Comment by wsdjeg** [comment]
also do not same as Xterm
![2016-01-24 15 27 30](https://cloud.githubusercontent.com/assets/13142418/12535019/069b98da-c2af-11e5-9904-d76fd4ad68e1.png)

**Comment by wsdjeg** [comment]
@brcolow thanks ,so move to #2912

**Comment by wsdjeg** [comment]
@nhooyr I have find how to fix this issue ;

you see 
![2016-01-30 21 15 37](https://cloud.githubusercontent.com/assets/13142418/12695894/a1f848e6-c796-11e5-9e47-43eb0ce257ec.png)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6597 allows per-window colorschemes.
