### ISSUE TITLE
:terminal - cells are sometimes not updated

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4099]
#4087 was closed because it was merged with #3459 I'm not sure if it has anything to do with #3459 but I found a way to reproduce it 100%.

https://youtu.be/Mc_h7yiKXpY

Let me know if the quality sucks.

**Comment by justinmk** [comment]
I appreciate the effort of making the video, but it's difficult for me to see what the steps are. We need minimal steps to reproduce using `nvim -u NONE` (without plugins). Otherwise it's just guesswork or very time-consuming.

Note: Next time just leave a comment on the original issue.

**Comment by nhooyr** [comment]
This is an interesting bug but I think I got it so you can reproduce it as well. But its still pretty weird. This video should explain it fairly clearly but I'll outline below.

You need to have the line `syntax on` in your init.vim. If you create a terminal and if you are in normal mode you can actually highlight brackets and parenthesis (if you don't have `syntax on` in your init.vim but type it in afterwards, you can't highlight the brackets which is why the bug doesn't appear but you can still use `%` to jump to matching braces). 

These braces take on the highlight group of `MatchParen` obviously and for some reason when you go into Insert mode the highlight groups at those specific characters aren't reset so even though the parenthesis aren't at that spot anymore if say you type a newline, the colours are and whatever text is there turns into those colours.

Took me hours to get this right. Feels gud.

https://www.youtube.com/watch?v=tJ_hTGWFZp0&feature=youtu.be

**Comment by justinmk** [comment]
The steps you described work with `nvim -u NONE` ?

**Comment by nhooyr** [comment]
No. It only works when `syntax on` is in the startup file. So it has to be `nvim u init.vim`. Only one line, `syntax on`.

**Comment by justinmk** [comment]
Ok, video was very thorough ;) I get it now. Some color cells are not getting updated.  

Link for posterity: https://youtu.be/tJ_hTGWFZp0?t=304

**Comment by nhooyr** [comment]
Also, what did you think about the end. Half of the screen disappearing because of changing the syntax to on or off? lol

**Comment by nhooyr** [comment]
I found a much better way to reproduce (what I think is this bug). Start nvim with NORC because we need parenthesis highlighting.

1. `print "dsajdsjdsjadasjdajsdsjereqwo" > test`
2. `nvim -u NORC`
3. Type `(dasdsds)` into the empty buffer in insert mode
4. Save as anything.
5. Go to start of the buffer with '^'
6. `:e test<CR>`
7. Do not move the cursor and carefully look, some of the text is highlighted from the previous MatchParen color.

**Comment by justinmk** [comment]
Is this still an issue? `:terminal` redraw logic was changed a bit.

**Comment by nhooyr** [comment]
No idea, I'll try and check these and my other older issues over the weekend.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9494 brings a lot of fixes from libvterm. Assuming this is fixed, or we need an updated/new ticket with perhaps minimal steps.
