### ISSUE TITLE
bells in the terminal

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4102]
I use weechat as my IRC client and I'd like to run it inside of neovim but I never get any notifications. Normally if I run it in tmux I get a bell ring whenever I get a notification but inside of neovim nothing.

**Comment by atommclain** [comment]
Build on OS X 10.10.5 with commit 91254bd9d
tested on terminal.app 2.5.3 and iTerm 2.1.1

nvim -u NONE
:terminal
echo -en '\x07'|cat -

I do hear the bell

**Comment by justinmk** [comment]
Thanks @atommclain
