### ISSUE TITLE
finddir(name, path),findfile(name, path) return empty string in ubuntu!

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4105]
os ubuntu 14.04
terminal gnome-terminal 3.12.3
reproduce step

```
mkdir foo
cd foo
mkdir .bar
nvim -u NONE
:e quux/baz.vim
:echo finddir('.bar/', 'quux;')
```

as @airblade says in os he get `.bar/`,but I get empty string in ubuntu.

cc @artur-shaik @mattn

**Comment by wsdjeg** [comment]
Both happened in vim and neovim with ubuntu

**Comment by fmoralesc** [comment]
Why would you expect otherwise? The `quux` dir is not created when you do `:e quux/baz.vim', nor is the current directory changed.

**Comment by wsdjeg** [comment]
I know `quux` is not created. current dir is not changed is is `foo/` 
It should same as MAC OS ,show me `.bar/`,nor a empty string

**Comment by fmoralesc** [comment]
So the issue is that the *path* argument for finddir() doesn't need to actually exist, but only be part of the directory section of the name of some opened buffer? That doesn't seem right. Directory traversal in nvim doesn't work like that, it traverses the actual filesystem. Perhaps nvim's current rules are more strict than vim's (see https://github.com/neovim/neovim/pull/3273), but I remember vim working fundamentally like this too.

**Comment by wsdjeg** [comment]
@airblade can reproduce this issue in ubuntu ,but it works well in MAC OS,please see the link I show you above

**Comment by airblade** [comment]
Personally I feel MacVim is an anomaly and that `finddir()` should traverse the actual filesystem.

**Comment by fmoralesc** [comment]
Yeah, I wonder why and how MacVim is doing that.

**Comment by wsdjeg** [comment]
I think it issue is what is dir_current_file, 
`echo expand('%:p:h')`

**Comment by tyru** [comment]
@wsdjeg Why do you often mention to @mattn ?
I'm sorry if i was wrong, neither @mattn is neovim's maintainer nor your father.

**Comment by wsdjeg** [comment]
because ,it is same issue in javacomplete2,and mattn also comment it that commit !!
https://github.com/artur-shaik/vim-javacomplete2/pull/173

**Comment by tyru** [comment]
Okay, so you should write about that at least.

And, vim-javacomplete2 has no relationship with this issue.
You should write it in above thread you wrote.

**Comment by tyru** [comment]
> Okay, so you should write about that at least.

Because, @mattn doesn't know this thread context.
If you mention to him *with no reason* , @mattn gets confused and frustrated because he has not any interest with neovim's bug.
He is not your handyman.

**Comment by wsdjeg** [comment]
@tyru I know he does not use neovim ,I mention to him because he use vim ,and his os is windows,and this issue also happend in vim with ubuntu 14.04, also I have test gvim in win7,also encount this issue.

**Comment by wsdjeg** [comment]
sorry I just add jc2 link in vim-rooter's issue,
and add link of vim-rooter here ,It is my fault

**Comment by wsdjeg** [comment]
```
$ mkdir foo && cd foo
$ mkdir .bar
$ vim quux/baz.vim
```
[in vim]
`:echo finddir('.bar/', 'quux;')`    OS X show `.bar/` ubuntu show empty string
`:echo finddir('.bar\', 'quux;')`    Win7 show empty string

**Comment by mattn** [comment]
at least, the code should not work correctly. because vim/nvim search `.bar` in `quux`. see `:help finddir`.

**Comment by mattn** [comment]
As far as i can see, it's not a bug. maybe, you have `quux/.bar` on ubuntu but not have it on windows.

**Comment by wsdjeg** [comment]
it says ` Supports both downwards and upwards recursive directory searches`;
so if the second args is not begin with `/`(linux) or `[A-Z]:` it should same as
`finddir(name,getcwd().F_sep.path)`

**Comment by wsdjeg** [comment]
`echo finddir('.bar/', getcwd().'/quux;')` show me `.bar`

**Comment by wsdjeg** [comment]
`echo finddir('.bar\', getcwd().'\quux;')` also show me `.bar` in win

**Comment by wsdjeg** [comment]
> you have quux/.bar on ubuntu but not have it on windows
```
tree:
 - foo
     |-.bar
     |-quux\baz.vim(the directory quux has not been created)
```

**Comment by mattn** [comment]
put comma.

You need to specify `{path}` as absolute path like below.

```
:echo finddir('.bar', fnamemodify('quux', ':p:gs?\?/?') . ';')
```
and substitute backslashes to slashes for windows.

**Comment by mattn** [comment]
FYI, you can't contains backslashes in `{path}`. Because backslashes in `{path}` is handled as escaped characters.

**Comment by wsdjeg** [comment]
> echo finddir('.bar\', getcwd().'\quux;') also show me .bar\ in win

but why this show me `.bar\` in windows?

**Comment by mattn** [comment]
maybe you set shellslash?

**Comment by wsdjeg** [comment]
no I just install gvim ,and with the default vimrc ;
`set shellslash?`
show me `noshellslash`

**Comment by mattn** [comment]
then, probably, the example code you've wrote in above escape `;` with backslash like `\;`. So disabled upward searching, maybe.

**Comment by wsdjeg** [comment]
both `:echo finddir('.bar\', 'quux;')` and `:echo finddir('.bar\', 'quux\;')` show empty string

**Comment by mattn** [comment]
BTW, why you don't specify the `{path}` as absolute path?

**Comment by wsdjeg** [comment]
I also want specity that as absolute path,but can not get the absolute filepath of a new file in a new directory;
https://github.com/airblade/vim-rooter/blob/a3b9500ebda69f90d16a567da9a39693919489ea/plugin/rooter.vim#L72-L88
`fnameescape(expand('%:p:h'))` show me only `Test/testnew` in ubuntu ,not `/home/wsdjeg/Test/testnew`

let me do more test tonight.

**Comment by mattn** [comment]
```
	:p	Make file name a full path.  Must be the first modifier.  Also
		changes "~/" (and "~user/" for Unix and VMS) to the path for
		the home directory.  If the name is a directory a path
		separator is added at the end.  For a file name that does not
		exist and does not have an absolute path the result is
		unpredictable.  On MS-Windows an 8.3 filename is expanded to
		the long name.
```
help says `:p` return full path.

**Comment by wsdjeg** [comment]
I know,but if i open new file in new path ,it show me not full path ,as you can see above

**Comment by mattn** [comment]
at the first, you should figure-out which occur this issue.
* vim/nvim
* vim-router

**Comment by wsdjeg** [comment]
vim-rooter
when open a new file in a new directory ,can not autochange to the rootdir of the project

**Comment by wsdjeg** [comment]
but in os x ,it works well

**Comment by mattn** [comment]
I trouble with pointing out the bug of vim about unexpected usage or spec of vim.

**Comment by wsdjeg** [comment]
thanks all the same,all I can do is write a func to fix vim-rooter in my os!

**Comment by fmoralesc** [comment]
Having seen all this, I think @wsdjeg just needs to use a wrapper around finddir that has the behavior he wants, or propose something like that to the plugins he is using.

The current semantics for `finddir()` are fine - it should traverse the actual filesystem, as @airblade points out above; it's weird that they are inconsistent across platforms, but perhaps the underlying io/fs operations are different also. If someone can report on how that works, it would be of help.

Also, when you create a buffer for `quux/baz.vim` and the quux dir doesn't exist, what happens is that `quux/baz.vim` will be the *name* of the buffer, but *not a relative path*. Try this:
~~~ vim
e quux/baz.vim
echo expand('%:p')
!mkdir quux
w
echo expand('%:p')
cd quux
w
e baz.vim
echo expand('%:p')
~~~
As you see, the name of the buffer and the path differ. This is so because *buffers need not be linked to files*, but they will always have a name regardless. (n)vim can't *guess* you are planning to write to disk - such a guess could have ill consequences and in many cases would be unwelcome, so it can't be the default behavior. In sum: I strongly feel that OSX behavior is wrong here, *contra* @wsdjeg.

**Comment by airblade** [comment]
@wsdjeg Just save the new file and then the intermediate directory will be created and `finddir()` will be able to find it.  IMHO MacVim is the one with the bug.

**Comment by wsdjeg** [comment]
ok got it .bug's bug is really bug!so should we close this issue?
