### ISSUE TITLE
I get 2 tabs after autoindent enabled.

### ISSUE THREAD

**Issue by were** [neovim/neovim#4106]
When editing `C/C++/HTML`, it gives me 2 tabs for autoindent.

But this phenomenon does not occur when writing `python`.

How can I disable 2 tabs?

**Comment by ZyX-I** [comment]
This means that your `&shiftwidth` is twice the value of `&tabstop`, you need to fix this (also alter `&softabstop`). To view option documentation use commands like `:h 'shiftwidth'`. For questions there is neovim mailing list.

**Comment by were** [comment]
I tried to set `shitwidth` before which did not help.

**Comment by were** [comment]
Sorry to disturb, it is solved.
