### ISSUE TITLE
Weird characters inserted in status and window

### ISSUE THREAD

**Issue by zoqaeski** [neovim/neovim#4110]
I often run neovim using the gnome-terminal wrapper, and I've noticed lately that I'm getting a sequence of weird characters appearing in the status line and in the main edit window. The string usually consists of some unprintable characters + Ptmux + some more unprintable characters. They don't  get written to the file, or even appear to be editable: typing continues underneath them on the original text. Refreshing or redrawing the window usually clears them, but they'll occasionally reappear at random.

It definitely seems to be [this issue](https://github.com/fmoralesc/neovim-gnome-terminal-wrapper/issues/10), but the maintainers there have flagged it as an External issue, so maybe it's neovim instead? It could also have to do with #4057, except in my case I don't get the scrambled text if I just run neovim normally from the shell, either in tmux or plain gnome-terminal.

![Screenshot](https://cloud.githubusercontent.com/assets/172912/12604985/9dbbb292-c514-11e5-9df2-87b8c7cba0a9.png)

I couldn't seem to capture a screenshot of the garbled text appearing in the main window, as it would disappear if I switched focus and reappear after the screenshot was taken :confused: 

EDIT. Gotcha!

![Another screenshot](https://cloud.githubusercontent.com/assets/172912/12605031/03b60250-c515-11e5-9918-a69b9511876a.png)

**Comment by justinmk** [comment]
Same as https://github.com/neovim/neovim/issues/3875 ?

It's odd that there are so many reports of this in the last couple weeks. Any chance you could try to bisect it to a specific commit? (If it still happens at a November commit, probably not worth going further back)

**Comment by zoqaeski** [comment]
I tried a handful of commits going back to early December spaced roughly every couple of days apart, and it happened in all of them. The earliest I tried was `7f8365e3027880d1ddec7f02281b5922ab29ac0c` that was pushed on December 12.

**Comment by justinmk** [comment]
The tmux DCS ("Ptmux") is coming from `TMUX_WRAP` in `tui/tui.c`. Merging with https://github.com/neovim/neovim/issues/3875
