### ISSUE TITLE
CTRL-U and CTRL-D improvement

### ISSUE THREAD

**Issue by JAremko** [neovim/neovim#4114]
My proposal is binding  `0` `C-d` and `0` `C-u` to reset the `scroll` value to its default(half a scree)

Motivation:

`C-u` and` C-d` are  somewhat special,  because they can remember the prefix value: 

[docs](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-D)
```org
                            *CTRL-D*
CTRL-D Scroll window Downwards in the buffer.  The number of
              lines comes from the 'scroll' option (default: half a
              screen).  If [count] given, first set 'scroll' option
              to [count].  The cursor is moved the same number of
              lines down in the file (if possible; when lines wrap
              and when hitting the end of the file there may be a
              difference).  When the cursor is on the last line of
              the buffer nothing happens and a beep is produced.
              See also 'startofline' option.
              {difference from vi: Vim scrolls 'scroll' screen
              lines, instead of file lines; makes a difference when
              lines wrap}
```
While this is really useful feature, it's something handy to quickly revert to the defaults in a straightforward and consistent way. Using `0` prefix is logical and easy to remember.

**I understand that this is a really minor improvement, but it is easy to implement with a simple VimL  expression and It's a good default behavior.**

```viml
map <silent> 0<c-d> :set scroll=0<CR> 
```

# Cheers!

**Comment by justinmk** [comment]
I'd recommend `1<c-d>` personally. We can't rebind `0` to anything because it already serves a purpose. Thanks though.

**Comment by JAremko** [comment]
@justinmk  You mean `0` `0`  combination  or just a `0`? Can you elaborate? I'm just curious :smile:
