### ISSUE TITLE
Cannot bind C-h

### ISSUE THREAD

**Issue by belak** [neovim/neovim#4123]
`nmap <C-h> <C-w>h`

The above line in my nvim init does not appear to work. The C-h is interpreted as a backspace. Note that C-w C-h still works and C-w h also works. This behavior also works correctly in vim.

I'm using NVIM v0.1.2-371-g1574c4a compiled from the archlinux PKGBUILD with no other changes. I'm in gnome-terminal and TERM is set to xterm-256color. Let me know if you need any other info. I'd be happy to provide it.

**Comment by mhinz** [comment]
See https://github.com/neovim/neovim/issues/2048 the for issue and  https://github.com/neovim/neovim/issues/2048#issuecomment-78045837 for a possible solution.
