### ISSUE TITLE
Is the neovim process/job stopping on purpose w/an external command?

### ISSUE THREAD

**Issue by da99** [neovim/neovim#4125]
I was wondering if anyone w/[CtrlP](https://github.com/ctrlpvim/ctrlp.vim)  also experiences the nvim process stopping when using a custom search command. `fg 1` is required to bring it back.  Is this because CtrlP has not started using NeoVIM's job control?  

(I'm on Arch 64, nvim Release build (v0.1.2-398-g8f22031, master, non-HEAD)

**Comment by wsdjeg** [comment]
you mean `fg` just call back `ag`? and `fg 1` call back neovim ?

**Comment by da99** [comment]
Maybe this screenshot will clear things up:
![nvim](https://cloud.githubusercontent.com/assets/1551848/12693902/d31d27c8-c6df-11e5-9b7d-ec202b1da7c2.png)

**Comment by wsdjeg** [comment]
does that means there are two backgroud jobs,one is nvim ,and other is `ag`?

**Comment by wsdjeg** [comment]
I can not use `ctrl+z` close neovim ,because the ctrlp is too fast for me ,and ctrl+z in ctrlp buffer just means mark the file :smile: 
so I can not reproduce it ,sorry for that

**Comment by da99** [comment]
I'm also not pressing `ctrl+z`. 
It happens by itself after calling CtrlP w/ a custom external command (either  `ag ...`, `find ...`, `git ls-files`, etc.).
But you're right. There are now two jobs.
I can also reproduce it by typing:
    :call split(system(printf("ls %s", ".")), "\n")
or
    :call systemlist(printf("ls %s", "."))
CtrlP uses function calls like those when using "custom" external commands.  It uses regular VimScript for it's default file system interaction. That would explain why it runs fine... until I start customizing it. But, I don't understand why you're using `ag` w/ Neovim + CtrlP, and it's not stopping the process for you by itself. I've also used different combination of terminal emulators and shells.

**Comment by da99** [comment]
Here are examples of what I mean by customizing CtrlP in `init.vim`:

    let g:ctrlp_user_command = 'git --git-dir=%s/.git ls-files -oc --exclude-standard'
    let g:ctrlp_user_command = 'ag %s -l --nocolor --nogroup --hidden -g "" --depth 3'
    let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

**Comment by wsdjeg** [comment]
I also use ag as ctrlp's command ,but it wil not autoclose.
here is my config
https://github.com/wsdjeg/DotFiles/blob/master/vimrc#L554-L617

**Comment by wsdjeg** [comment]
also you can use 
```vim
let g:ctrlp_user_command = {
                \ 'types': {
                \ 1: ['.git', 'cd %s && git ls-files'],
                \ 2: ['.hg', 'hg --cwd %s locate -I .'],
                \ },
                \ 'fallback': 'ag %s -i --nocolor --nogroup --hidden
                \ --ignore out
                \ --ignore .git
                \ --ignore .svn
                \ --ignore .hg
                \ --ignore .DS_Store
                \ --ignore "**/*.pyc"
                \ -g ""'
                \ }
```
but I thing `git ls-file`  is not a good choice,because `git ls-files` use same backgroud feature as ag,but only show the files which has been added into repo.

**Comment by da99** [comment]
There is a flaw in your (@wsdjeg) init.vim:

        let g:ctrlp_user_command = ['ag %s -i --nocolor --nogroup --hidden ...  ']

That's that wrong format. If you use an array it has to be: in this format: `[root_marker, listing_command, fallback_command]` (More info here: [Line 315 in CtrlP doc](https://github.com/ctrlpvim/ctrlp.vim/blob/master/doc/ctrlp.txt#L315)  )

CtrlP is likely ignoring it and using it's default search method. In your case, turn it into a string:


        let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden ...  '

**Comment by da99** [comment]
I can't get `ag` to work w/CtrlP (yet), but everything else is working well: `find`, `git ls-files`.
It might have to do with the fact that I'm using `NeoBundle` like your (@wsdjeg) config. I was using [Pathogen](https://github.com/tpope/vim-pathogen) in my config.  I will close this issue shortly after reading more about [NeoBundle](https://github.com/Shougo/neobundle.vim).

**Comment by da99** [comment]
Thanks again to @wsdjeg for taking the time to reproduce the error. That was very generous.

**Comment by wsdjeg** [comment]
> That's that wrong format. If you use an array it has to be: in this format: [root_marker, listing_command, fallback_command] (More info here: Line 315 in CtrlP doc )

thanks,just because I remove the roo_marker,so it works well for me :smile:

**Comment by da99** [comment]
Ok. So the problem was my init.vim:

     set shellcmdflag=-ic

I had overlooked that. It was making the shell calls interactive. (More info. at `:help shellcmdflag`) This would also explain why gVim would occasionally freeze X11 and vim would stop or crash unexpectedly after system upgrades. 
I must of mis-typed that ages ago and forgot it was there. A HUGE mistake on my part. `Pathogen` and all the other plugins were not the problem. NeoVim is

**Comment by wsdjeg** [comment]
:+1:
