### ISSUE TITLE
has('python') fails inside sandbox unless called first outside of one

### ISSUE THREAD

**Issue by ressu** [neovim/neovim#4126]
My init.vim started failing with an odd flow of messages and after quite some debugging it turns out that if `has('python')` is called from inside a sandbox without first calling it outside of one, will cause it to fail with a consistent stream of errors.

This can be easily reproduced by starting vim without any config (`nvim -u NONE`) and executing
`:sandbox call has('python')`. Neovim will produce a number of errors.

If you run `:call has('python')` before the above line, there is no error and python detection works as it is supposed to.

This was reproduced with NVIM 0.1.2-dev from the ubuntu PPA, dated git201601290523

**Comment by Shougo** [comment]
Reproduced.
The remote plugins provider cannot be called from sandbox.

**Comment by lewis6991** [comment]
I don't think `sandbox` is a feature we want to develop further.
