### ISSUE TITLE
What happens when $NVIM_TUI_ENABLE_TRUE_COLOR=1 in `xterm-256color`?

### ISSUE THREAD

**Issue by da99** [neovim/neovim#4127]
This is not an issue, but a question on what happens when NVIM_TUI_ENABLE_TRUE_COLOR is used.

Below is a terminal emulator where TERM=xterm-256color. They both use the same theme and same init.vim file, except for one difference:
Left: NVIM_TUI_ENABLE_TRUE_COLOR is commented out.
Middle: NVIM_TUI_ENABLE_TRUE_COLOR is set to 1.
Right: How the terminal and shell normally look.
![colors](https://cloud.githubusercontent.com/assets/1551848/12695458/b8594ac2-c714-11e5-8573-902cad30003d.png)

Is this normal for NVIM_TUI_ENABLE_TRUE_COLOR? I'm  not trying to get true color. I'm asking because I'm curious if this is the correct behaviour. I've used this on different shells and terminals and they all have the same behaviour as pictured above.

**Comment by wsdjeg** [comment]
why do not use gnome-terminal ?
t
#### rue color terminal in ubuntu 14.04
```sh
sudo add-apt-repository ppa:gnome3-team/gnome3-staging
sudo apt-get update
sudo apt-get install gnome-terminal
sudo add-apt-repository -r ppa:gnome3-team/gnome3-staging
```

**Comment by wsdjeg** [comment]
you can see the pic in my dotfile,with true color

**Comment by da99** [comment]
You're right. I was mistaken that some of the terminal emulators I used supported true-color. I tried it in gnome-terminal and it works great. My mistake. Thanks again.
