### ISSUE TITLE
Ultisnips not working

### ISSUE THREAD

**Issue by dougcoates** [neovim/neovim#4128]
I cannot expand ultisnips snippets in neovim, though ultisnips is working fine in vim with the exact same vimrc. There are no errors messages or anything in the logs seems to be useful. 

The output of `verbose imap <tab>` seems to be correct, it gives:

```
 i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>                                                                                                              
 Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
```

My `~/.config/nvim/init.vim`: http://pastebin.com/jT3AnU1x. When regular vim is started with this configuration file everything works as it should, so I suppose this is an issue with neovim?

**Comment by justinmk** [comment]
Please search the issue tracker.

**Comment by duganchen** [comment]
I just searched the issue tracker. There were no previous issues relevant to this, as far as I can tell.

**Comment by justinmk** [comment]
Need more info than "cannot expand ultisnips".

**Comment by duganchen** [comment]
It's obvious that this issue is the same one logged on UltiSnip's tracker, where the response was "I can't support neovim".

https://github.com/SirVer/ultisnips/issues/512#issuecomment-221703009

Oh well...

Can you be more specific about what more info you need?

**Comment by carlitux** [comment]
I am using ultisnips and I can expand with this setup... 

```vim
call dein#add('SirVer/ultisnips') "{{{
  let g:UltiSnipsExpandTrigger="<tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-j>"
  let g:UltiSnipsJumpBackwardTrigger="<c-k>"
" }}}
```

Now maybe the issue is on expand or jump... but you can split on many key maps

**Comment by justinmk** [comment]
> It's obvious that this issue is the same one logged on UltiSnip's tracker,

That's useful information. I left a comment there.

**Comment by justinmk** [comment]
@dougcoates @duganchen Is python working? (`echo has('python')` should return 1). Did you try the steps in https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working ?

**Comment by duganchen** [comment]
I just posted this update on the UltiSnips ticket. I'm going to reproduce it here.

While I cannot speak for @dougcoates, I just did a test with neovim 0.14 and init.vim that contains only the following:

    syntax on
    call plug#begin('~/.config/nvim/plugged')
    Plug 'SirVer/ultisnips'
    call plug#end()

And that did actually work for me.

@dougcoates, can you confirm?

**Comment by justinmk** [comment]
- It should work even without `syntax on` since Neovim does that by default. (Might be worth confirming that it still works in that case)
- If you can narrow down the plugin or setting that causes the problem, that will help a lot.

**Comment by duganchen** [comment]
I just tried the following. I restored my usual init.vim, erased ~/.vim/plugged (I use vim-plug, which I'd last updated yesterday), and then reinstalled the entire set with :PlugInstall. UltiSnips started working then.

Whatever plugin was causing the problem, I don't think I can be of any more help in finding it.

**Comment by k-cross** [comment]
Are you using a build with or without python support? I'm pretty sure UltiSnips requires that baked in and neovim is trying to make communication through msgpack. That's my understanding of it.
