### ISSUE TITLE
Clipboard error : Can't open display

### ISSUE THREAD

**Issue by Herz3h** [neovim/neovim#4130]
Upon starting nvim i get an error message :

`clipboard: error: Error: can't open display: null`

This is on a remote Centos 6.7 x32 machine. What should i do ?

**Comment by justinmk** [comment]
Please read the wiki and/or search the issue tracker.

**Comment by Herz3h** [comment]
I already installed xlip/xsel

**Comment by justinmk** [comment]
If you are remoting into machine, then a X server is not available. This wouldn't work on Vim or any other remote terminal program. Unless you are using forwarding.

**Comment by Herz3h** [comment]
How do i disable the annoying message then when starting nvim ?

**Comment by justinmk** [comment]
:help 'clipboard'
