### ISSUE TITLE
crashing when restoring winview after opening a preview window

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4132]
I'm using deoplete to reproduce this.

Open a file that will open the preview window for autocomplete. 
Add these two autocmds (essentially they make sure the preview window doesn't cause the main window to move when it opens or closes).

``` vim
autocmd InsertEnter * let g:view=winsaveview()
autocmd WinEnter * call winrestview(g:view)
```

Enter insert mode, go to the very bottom of the file. Then type something that will trigger autocomplete and bam it crashes.

**Comment by Shougo** [comment]
@nhooyr You should create minimal init.vim.

**Comment by nhooyr** [comment]
Oh it has nothing to do with going to the bottom of the file. It just crashes. I'll add a init.vim.

**Comment by nhooyr** [comment]
Here is the init.vim
```vim
call plug#begin('.')
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-jedi', { 'for': 'python'}
call plug#end()

autocmd InsertEnter * let g:view=winsaveview()
autocmd WinEnter * call RestoreView()
function! RestoreView()
	if exists("g:view")
		call winrestview(g:view)
	endif
endfunction

let g:deoplete#enable_at_startup = 1
imap <silent><expr><Tab> pumvisible() ? "\<c-n>" : deoplete#mappings#manual_complete()
```

1. `nvim -u init.vim
2. `:PlugInstall`
3. `:q`
4. `nvim -u init.vim`
5. `:UpdateRemotePlugins`
6. `:q`
7. `nvim -u init.vim python.py`
8. Import something and thens start scrolling through the autocomplete options with tab and bam it crashes. 

I had to create a mapping for tab because I think I discovered a different unrelated bug in deoplete (it still happens without the mapping but its easier to reproduce like this).

**Comment by nhooyr** [comment]
@justinmk shouldn't this be labeled a bug as well? Its very simple to reproduce with the above steps.

**Comment by watiko** [comment]
I can reproduce it and there is similar issue.

Steps to reproduce: 

```sh
mkdir -p /tmp/test_comp && cd $_

git clone https://github.com/davidhalter/jedi-vim.git --depth 1
(cd jedi-vim && git submodule update --init --depth 1)
cat test.vim
```

```vim
set rtp+=jedi-vim
let g:jedi#popup_select_first = 0

autocmd InsertEnter * let g:view=winsaveview()
autocmd WinEnter * call RestoreView()
function! RestoreView()
  if exists("g:view")
    call winrestview(g:view)
  endif
endfunction
```

```sh
vim -u test.vim test.py -c 'exe "normal iimport re\<ESC>"'
```

type `o<C-j>re.<C-n><C-n>` then SEGV.

This issue may affect both vim and nvim. (I don't know whether jedi is relevant or not.)

**Comment by watiko** [comment]
@nhooyr I was wondering why did you use `InsertEnter`. Is it meaningful?

**Comment by nhooyr** [comment]
@watiko essentially I was trying to create a vim script solution for #4135 

E.g. start insert mode, save the windows and their positions, and then when entering the preview window, restore those positions.

**Comment by watiko** [comment]
@nhooyr I see. Perhaps `CompleteDone` and `:set splitbelow` will help you.

**Comment by nhooyr** [comment]
@watiko thats not my issue, it's that the preview window pushes up the other windows. it moves my entire setup which I find annoying.

**Comment by justinmk** [comment]
Cannot reproduce using the steps in https://github.com/neovim/neovim/issues/4132#issuecomment-191308664 .

Tested Nvim 0.4.0 987619d with ASAN enabled.
