### ISSUE TITLE
preview window option to not cause window to scroll when closed/opened

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4135]
With autocomplete and such, if the preview window is opened or closed it causes other windows to scroll. E.g (c is the cursor position)
```
+----------------+
|                |
|                |
|   C            |
|                |
|                |
+----------------+
```
After opening preview
```
+----------------+
|                |
|   C            |
|                |
+----------------+
|                |
+----------------+
```
Notice how the cursor position went up (it scrolled) even though the preview window wouldn't have covered it? This gets really annoying sometimes and the opposite happens when it is closed. Ideally there should be an option for the following behaviour

```
+----------------+
|                |
|                |
|   C            |
|                |
|                |
+----------------+
``` 
After opening preview
```
+----------------+
|                |
|                |
|   C            |
+----------------+
|                |
+----------------+
```

Of course if the preview window will indeed cover the cursor then the top window should be scrolled like it is now, but if the preview window will not cover the cursor, then it should not cause the window to scroll. I tried fixing this with some vim script in #4132  but that led to weird bugs.

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/3933
