### ISSUE TITLE
Set background/foreground color for :term

### ISSUE THREAD

**Issue by tamagokun** [neovim/neovim#4141]
Are there options to configure foreground/background color to be different than colorscheme?

I've searched through issues on here and in :help, but didn't see anything.

I did however find someone using:

```
let g:terminal_color_background="#2d2d2d"
let g:terminal_color_foreground="#cccccc"
```

but that doesn't seem to work.

**Comment by evanandrewrose** [comment]
You can try:

`:highlight Normal ctermbg=233 ctermfg=251`

Neovim supports the [xterm 256 color palette](https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg).

**Comment by tamagokun** [comment]
I'm trying to specify bg/fg colors for a `:terminal` buffer specifically, not regular neovim buffers. Hard to explain, and hard to google.

**Comment by romgrk** [comment]
@tamagokunn I have been wondering about this specific issue for a long time. Haven't found the solution yet, but I know it's possible. I remember once opening my nvim, and having a black-backgrounded terminal buffer, with a normal buffer with normal bg; but since then, havent been able to reproduce. If you want to delve deeper into this, good luck. You carry all my hopes.

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/1457.

There might be a way to do it with the `g:terminal_color_` color thing but that's kind of a temporary hack IMO.

**Comment by tamagokun** [comment]
I don't think this is necessarily covered by #1457. Looking in `terminal.c` I can see that the vterm gets set up with a default bg and fg color. I suppose I could use a 256-color palette using the `g:terminal_color_` options, but I have been using neovim's true color support, so I believe the fg/bg values are just rgb colors and are not pulled from the 256-color palette.

It would be great if there was an option to specify the fg/bg that could be picked up when the terminal is inited. I think i'll try to do a PR for this.

**Comment by justinmk** [comment]
> It would be great if there was an option to specify the fg/bg that could be picked up when the terminal is inited.

Why only fg/bg? We don't want special-case options. We want generalized facilities. Why wouldn't #1457 cover that?

**Comment by tamagokun** [comment]
I think it would cover it as long as the vterm emulation is updated to support colorschemes. I don't think it does currently, correct? It pulls colors straight from term and then allows slight customization with the `terminal_color` options. If that is the direction that neovim is headed, I think it's great! Definitely a great approach to fix a lot of the additional color customizations that people want.

My only concern is if it will ever get done. Is it a large change? Or just not high priority? The issue is pretty dated. Sorry if that sounded like I am a complete jerk, I just can't come up with a better way to put it. I am extremely humble to the neovim members and what they are trying to do. Neovim is freaking great.

**Comment by justinmk** [comment]
@bfredl Has been working in earnest on buffer-local highlighting, though not necessarily #1457 specifically I think the work he is doing is paving the way. E.g. https://github.com/neovim/neovim/pull/1817

**Comment by tamagokun** [comment]
Ohh, that's excellent!

**Comment by bfredl** [comment]
Actually just a buffer-local `g:terminal_color_` , you could say `b:terminal_color_` is prioritized if present, (and possibly change to specify highlight group instead of just color) would be closer "in spirit" to #1817 . Surely #1457 would be nice, but it would need to mess much more with `screen.c` and likely also `syntax.c` than #1817 .

**Comment by justinmk** [comment]
See `:h nvim-terminal-emulator-configuration`, `b:terminal_color_*` should already work. But it only works with NVIM_ENABLE_TRUE_COLOR.

I guess `b:terminal_color_bg` and `b:terminal_color_fg` wouldn't be any worse that the current hack. So I retract my earlier objection.

**Comment by tamagokun** [comment]
I was using tmux to manage splits and windows, etc. Recently, nvim inside of tmux has been really slow, so i've switched to using nvim straight through iterm. I thought it was a nice idea to just manage splits and windows between editors and terminals right inside of neovim! I think its still a very cool idea, but I am just picky about colors. I prefer a lighter editor and a darker terminal.

**Comment by justinmk** [comment]
> Recently, nvim inside of tmux has been really slow

Hmm, that's weird. Do you mean this? https://github.com/neovim/neovim/wiki/Troubleshooting#esc-in-tmux-or-gnu-screen-is-delayed 

> I prefer a lighter editor and a darker terminal.

Sure, I understand. #1457 should cover that.

**Comment by tamagokun** [comment]
No, it seemed mainly to be a problem with rendering speeds (redraws perhaps?) Scrolling was really sluggish and clunky. The time from command -> visible change also seemed a bit delayed.

I wasn't able to pinpoint if it was a problem with my tmux setup, or nvim, but when I ran nvim without tmux, I couldn't believe how much better everything felt.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6597 allows per-window colorschemes.

**Comment by tamagokun** [comment]
mind blown. Thanks for bringing this to my attention!
