### ISSUE TITLE
Crash on Windows8

### ISSUE THREAD

**Issue by rhysd** [neovim/neovim#4146]
Hi,

I tried Neovim on Windows and got crash report on executing `nvim` command.  I know that Neovim discarded CUI support on Windows but I'm not sure that this is a current normal behavior for Neovim on Windows.
Below is a sequence I tried.

1. Download Neovim.zip from [here](https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw/job/9sscwbh0fdqryx0s/artifacts) and unarchive it to `C:\Neovim`
2. Add `C:\Neovim\bin` to `$PATH`
3. Open PowerShell
4. Execute `nvim`

'nvim.exe stopped execution' window was shown and it reported:

```
Signature of problem:
  Event name:	APPCRASH
  App name:	nvim.exe
  App version:	0.0.0.0
  App timestamp:	56a41584
  Module name:	VCRUNTIME140.dll
  Module version:	6.3.9600.18146
  Module timestamp:	5650b9bb
  Exception code:	c0000135
  Exception offset:	00000000000ec540
  OS version:	6.3.9600.2.0.0.256.4
  Locale ID:	1041
  Additional info1:	ac05
  Additional info2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional info3:	ac05
  Additional info4:	ac0507478d1c5bd693cfc4fe3987e900
```

- Environment
  - Windows 8.1

**Comment by justinmk** [comment]
Can you get a stack trace?

**Comment by rhysd** [comment]
Could you tell me how to do that?  (Or is there document for that?)  I looked wiki (e.g. [here](https://github.com/neovim/neovim/wiki/Development-tips)) but couldn't find. I'm sorry I'm not familiar with development in Windows.

**Comment by equalsraf** [comment]
To get a trace you would need cdb or windbg

This [SO answer](http://stackoverflow.com/questions/11432940/what-does-error-code-0xc0000135-mean-when-starting-a-net-application) seems to point at missing DLLs. Maybe there is some issue with the installed c++ redistributables. It is also strange that it refers specifically to `VCRUNTIME140.dll`

**Comment by rhysd** [comment]
I tried [this instruction](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows) and it doesn't say to install any DLLs for Neovim.exe installation.  So I didn't install Visual C Runtime to my machine...

**Comment by equalsraf** [comment]
Can you try installing visual studio 2015 c++ redistributables and see if the problem is fixed.?

**Comment by rhysd** [comment]
Ah, you're right.  I installed VC++ 2015 Runtime and it works.  Thank you for help :bow:

**Comment by equalsraf** [comment]
Thanks, I've updated the wiki install instructions.
