### ISSUE TITLE
slow delete by pressing x

### ISSUE THREAD

**Issue by boboRAY** [neovim/neovim#4148]
I'm using neovim on OSX 10.11 (on iTerm2 and default terminal)
and encounter a obvious lag when deleting by pressing x

I have check my default vim and macvim, they don't have this problem

Can anyone tell what's happening here?

**Comment by justinmk** [comment]
Can you repro it with `nvim -u NONE ` ?

**Comment by boboRAY** [comment]
Hi,
run in `nvim -u NONE` is all good!

**Comment by mhinz** [comment]
And do Neovim and Vim use the same vimrc? Check `:nmap x` for potential culprits.

**Comment by boboRAY** [comment]
@mhinz, yes they all use same `.vimrc`
and `:verb namp x` return "No mapping found"

**Comment by boboRAY** [comment]
@mhinz  Yes, they all use same `.vimrc`
and `:verb nmap x` return "No mapping found"

**Comment by wsdjeg** [comment]
what is the out put of `:nmap x`
do you map something line `xx` or `xy`,then neovim need to wait for you to press the second key

**Comment by justinmk** [comment]
@boboRAY what is `:set clipboard?`

**Comment by boboRAY** [comment]
@justinmk  it return `clipboard=unnamed`

**Comment by boboRAY** [comment]
descript more detail about my issue
press `x` one by one wont cause lag

but when long press `x`, cursor will disappear and deleting will be laggy and out of control

**Comment by justinmk** [comment]
Unset clipboard. This is covered by other issues.
