### ISSUE TITLE
Change Y to yank to end of line (map Y y$)

### ISSUE THREAD

**Issue by saamalik** [neovim/neovim#416]
Even the current ViM documents state this for **Y**:

```
yank [count] lines [into register x] (synonym for
yy, |linewise|).  If you like "Y" to work from the
cursor to the end of line (which is more logical,
but not Vi-compatible) use ":map Y y$".
```

Since we're no longer Vi-compatible, can we please make _Y_ consistent with all the other capital letter  commands.

**Comment by TotalKrill** [comment]
Is it time to revisit this yet?

**Comment by justinmk** [comment]
It was revisited and rejected in https://github.com/neovim/neovim/issues/2676. It was rejected because it's not an overwhelming improvement.

**Comment by saheratarch** [comment]
Finally.
