### ISSUE TITLE
Don't hide cursor for filter(shell?) commands

### ISSUE THREAD

**Issue by mkoskar** [neovim/neovim#4160]
Whenever filter command is running cursor is hidden for the duration of it. That usually results in unnecessary disruptive cursor flash when started from mapping. 

Trying with `silent` or `lazyredraw` doesn't help.

Note that in Vim cursor is not hidden but moves to command line.

**Comment by justinmk** [comment]
I think this was improved with the various UI/TUI refactorings, at least compared to what I remember. Otherwise please mention steps to reproduce from `nvim -u NORC`.
