### ISSUE TITLE
strange characters in ctrlp search in neovim with fish shell

### ISSUE THREAD

**Issue by shangsunset** [neovim/neovim#4161]
greetings, 

when using ctrlp in neovim, there are always weird character in the last line
![screen shot 2016-02-03 at 7 22 47 pm](https://cloud.githubusercontent.com/assets/3700269/12804071/a2ff0688-cabd-11e5-8167-9ee6dda7f6fa.png)

Im not exactly sure what does this issue belong to. it could be fish, neovim, or ctrlp.

i did some experiments. i tried doing the ctrlp search in a project with: 
zsh + neovim, 
fish + vim, 
neovim + fish.

and strange character only appear when i use neovim in fish shell.

update:
sometimes this happens too, which never happened before neovim.
![screen shot 2016-02-03 at 10 23 29 pm](https://cloud.githubusercontent.com/assets/3700269/12804874/e43a1276-cac4-11e5-8ded-5b90bd471653.png)

any idea?

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/1496. See also https://github.com/neovim/neovim/issues/3682

**Comment by shangsunset** [comment]
Hi, i dont see how #1496 and #3682 cover this issue. its not about `:terminal`.

**Comment by justinmk** [comment]
I was thinking CtrlP depends on `system()` or `:!` having PTY behavior. But I don't think that's the case.

What version of fish are you using? What is `$TERM`, `$SHELL`, and `&shell`?

**Comment by shangsunset** [comment]
Hey, 

fish, version 2.2.0

sorry, im not really sure if i got your second question but is this what you were looking for? 
`$TERM` is `xterm-256color`, `$SHELL` is `/usr/local/bin/fish`

i dont know how to output `$shell`.

**Comment by justinmk** [comment]
`:echo &shell` inside nvim.

**Comment by shangsunset** [comment]
the output is `/usr/local/bin/fish`

**Comment by justinmk** [comment]
Ok. Need minimal steps to reproduce. Something more minimal than "Install fish and CtrlP".

**Comment by shangsunset** [comment]
i dont think its because of fish. just discovered it happens in zsh too

**Comment by justinmk** [comment]
Ok, so even more vague than before.

**Comment by shangsunset** [comment]
lol sorry. yea, i understand its very vague from my description. i wish i could provide more useful info.
