### ISSUE TITLE
Unnecessary file change when loading buffer

### ISSUE THREAD

**Issue by musaffa** [neovim/neovim#4162]
While loading or reloading any buffer on an ember app, Neovim changes the file itself and triggers an unnecessary new build in ember. The problem doesn't occur with Vim. Ember Cli uses [sane](https://github.com/amasad/sane) with [watchman](https://github.com/facebook/watchman). So I created a simple project like this:
```
/fileload-test
  /index.js
  /application.css
  /node_modules
```
node_modules is generated when I run `npm install sane` inside the project directory.

```Javascript
// index.js
var sane = require('sane');
var watcher = sane('./', {glob: ['**/*.css'], watchman: true});
watcher.on('ready', function () { console.log('ready'); });
watcher.on('change', function (filepath, root, stat) { console.log('file changed', filepath); });
watcher.on('add', function (filepath, root, stat) { console.log('file added', filepath); });
watcher.on('delete', function (filepath, root) { console.log('file deleted', filepath); });
```
```CSS
/* application.css */
body {
  padding: 10px;
}
```
Now I run `node index.js` and it outputs `ready` in the console. If I just load the `application.css` or reload it by `:e` command in neovim, the console states that application.css file has been changed. But if I do the same with Vim/Vi, it doesn't change the file (which is the expected behaviour). Triggering a file change and subsequently new builds when not necessary is giving me a quite a headache during my ember app development.

My system configuration:

Neovim - 0.1.2-dev
Vim - 7.4.1129
Watchman - 3.9.0
OS - Linux 3.13.0-27-generic Ubuntu 14.04 64bit

I set a minimal `.vimrc` setup for this test:
```vim
set nowritebackup
set nobackup
set noswapfile
```

**Comment by demersus** [comment]
I'm experiencing this as well

**Comment by justinmk** [comment]
```
set nowritebackup
set nobackup
set noswapfile
```

Do these settings change the behavior?

**Comment by musaffa** [comment]
Yes to eliminate them as causes from the test. The problem occurs with or without them.

**Comment by demersus** [comment]
I can confirm the same thing.  With those settings in my init file, the problem still persists.

**Comment by eblade** [comment]
I have the same problem. I'm running an inotify-based file-push script that gets to do a lot of extra pushing because of this.

**Comment by aloiscochard** [comment]
Running into same issue, I'll try to find a workaround to in script in the meantime by filtering in some way to extra events.

**Comment by musaffa** [comment]
@justinmk I'm eagerly waiting for the fix. I had to switch to using vim again for this problem. And I think the whole bunch of programmers who set guard on the file change events are experiencing the same problem. Any chance to fix it soon?

**Comment by justinmk** [comment]
@musaffa A reduced test case (that does not require installing something like node) would greatly facilitate fixing this. Otherwise I'm starting with nothing, and there are other tasks which start with more-than-nothing, which must be addressed first...

**Comment by musaffa** [comment]
@justinmk There's a similar issue #4200 reported with `inotifywait`. If you need more info about that test setup, please let me know.

**Comment by justinmk** [comment]
@musaffa Steps in #4200 are a good start, thanks.

**Comment by terciodemelo** [comment]
Has anyone been able to fix or workaround this problem? It's been specially hard on me when working with a **lot** of tests.

**Comment by Shougo** [comment]
@terciodemelo I have fixed it.
