### ISSUE TITLE
Can't open man pages with '-' or '.' sybmols in the name from nvim -c

### ISSUE THREAD

**Issue by george-b** [neovim/neovim#4165]
Doing running `nvim -c ':Man git-log'` will open the man page for git rather than git-log. However this does work if I run `:Man git-log` from a running nvim instance.

Also a '.' character seems to cause the rest of the argument to be dropped regardless of starting from a running nvim instance or not. For example `:Man limits.conf` will always return the error of 'No manual entry for limits'.

Please let me know if these two items should be filed as separate issues.

**Comment by justinmk** [comment]
Does it work if you escape the hyphen?

**Comment by george-b** [comment]
> Does it work if you escape the hyphen?

Can the hyphen be escaped? Sorry if this is a silly question I'm wrapping this in single quotes.

Whilst the changes in PR#4168 are still under review it fixes the issue for me.

**Comment by george-b** [comment]
Oops hit "Close and comment rather than "Comment", apologies.

**Comment by george-b** [comment]
Oops hit "Close and comment rather than "Comment", apologies.

**Comment by wsdjeg** [comment]
same issue for me ,but `man git-log` works well in terminal buffer.
also works well with `:te man git-log`

**Comment by justinmk** [comment]
> Can the hyphen be escaped? Sorry if this is a silly question I'm wrapping this in single quotes.

Some programs are dumb about the way they parse hyphen-prefixed options, and sending `\-` will workaround it. But yeah #4168 is the real fix.

**Comment by ZyX-I** [comment]
@justinmk How it can workaround? If program receives `\-` literally it would interpret it as `\-` and not `-`, I do not know many applications which interpret `\-` as `-`. If shell receives `\-` it is by no means different from `-` because backslash will be removed by shell.

**Comment by justinmk** [comment]
>  If program receives \- literally it would interpret it as \- and not -

That's what I mean. Shell invocation looks like `foo '\-bar'`. [pt](https://github.com/monochromegane/the_platinum_searcher/) has this bug and I've seen it elsewhere as well.

**Comment by ZyX-I** [comment]
@justinmk Which bug? `pt` is using regular expressions, so it is absolutely fine to interpret `\-` as `-- '-'`. if it does Similar reasons for `grep`, `ag`, etc and `tr` (no regex, but it allows escaping).

**Comment by justinmk** [comment]
Without the escape it is interpreted as an option.

**Comment by george-b** [comment]
> Some programs are dumb about the way they parse hyphen-prefixed options (single quotes are only seen by the shell)

Yeah this is where I got confused because I am running from the shell e.g.

```sh
nvim -c ':Man git-log'
```

Anyway the previously mentioned PR will sort this out.
