### ISSUE TITLE
Newline is not printed after message when reading from stdin

### ISSUE THREAD

**Issue by george-b** [neovim/neovim#4177]
When Neovim reads from stdin upon exit there is a message displayed which does not end in a newline. As such the user's prompt us placed on the same line containing the text from when Neovim exited.

``` sh

[cflcs01:~]% echo foo | nvim -u NONE  -c ':q!' -
Nvim: Reading from stdin...
"-stdin-" 1L, 4C"-stdin-" 1L, 4C[cflcs01:~]%
```

This is not the case for Vim.

``` sh
[cflcs01:~]% echo foo | vim -u NONE  -c ':q!' -
Vim: Reading from stdin...

[cflcs01:~]%
```

**Comment by brettanomyces** [comment]
This appears to not be an issue when using fish-shell.

**Comment by amiryal** [comment]
+1, verified with `NVIM 0.1.3-dev`, quite annoying.

**Comment by wsdjeg** [comment]
same in gnome-terminal ,but I think maybe it is not issue ,just tell you read in 1 lines and 4 chars

**Comment by wsdjeg** [comment]
maybe you mean it should be 
```
[cflcs01:~]% echo foo | nvim -u NONE  -c ':q!' -
Nvim: Reading from stdin...
"-stdin-" 1L, 4C"-stdin-" 1L, 4C
[cflcs01:~]%
```

**Comment by george-b** [comment]
Huh this no longer appears to be the case, not sure where/ when it got fixed. Closing.

**Comment by george-b** [comment]
Opps, sorry this is still the case, I closed this thinking it was resolved as I've added a newline as the first item in my `$PS1`

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/5956
