### ISSUE TITLE
vim-airline colors not displaying properly

### ISSUE THREAD

**Issue by gkze** [neovim/neovim#4180]
Hi,

I'm using the same `.vimrc` across both Vim and Neovim (one is symlinked to the other). With a clean setup, my airline colors look like this:
<img width="395" alt="screen shot 2016-02-05 at 2 37 07 pm" src="https://cloud.githubusercontent.com/assets/3131232/12861170/5017787e-cc16-11e5-8843-4545a6252127.png">

However, when launch Neovim, vim-airline looks like this:
<img width="538" alt="screen shot 2016-02-05 at 2 36 47 pm" src="https://cloud.githubusercontent.com/assets/3131232/12861186/7534f91a-cc16-11e5-9baa-f1d82cf8de25.png">

I've wiped all config & re-installed both Vim and Neovim from scratch, but the issue keeps persisting. Here's a link to my `.vimrc`:
https://gist.github.com/gkze/fa910b0e8628433059f4

Please let me know if I'm missing anything, thank you!

**Comment by wsdjeg** [comment]
please update neovim and airline,this issue has been fixed

**Comment by gkze** [comment]
Thank you! Closing out
