### ISSUE TITLE
Make file references non-existing file

### ISSUE THREAD

**Issue by btalpers** [neovim/neovim#4199]
The make file references https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz
This file fails to download, which I assume means it does not exist on the server or is no publicly accessible. This causes the make step of the installation to fail.

[ 13%] Performing download step for 'unibilium'
-- file: /home/bennett/install/neovim/.deps/build/downloads/unibilium/v1.2.0.tar.gz
-- downloading...
     src='https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz'
     dst='/home/bennett/install/neovim/.deps/build/downloads/unibilium/v1.2.0.tar.gz'
     timeout='none'
CMake Error at /home/bennett/install/neovim/third-party/cmake/DownloadAndExtractFile.cmake:74 (message):
  error: downloading
  'https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz' failed

**Comment by fwalch** [comment]
The file definitely exists. GitHub is having some issues at the moment (tarballs from other repos also cannot be downloaded). Please try again in a few minutes.

**Comment by btalpers** [comment]
Ok, thank you!
