### ISSUE TITLE
Is it normal for "CLOSE_WRITE,CLOSE" inotifywait event on opening a file?

### ISSUE THREAD

**Issue by da99** [neovim/neovim#4200]
I've tried various combinations of settings below:

    set noswapfile
    set nobackup
    set nowritebackup
    "  nvim -u NONE

 In all cases, opening a file leads to a `CLOSE_WRITE,CLOSE` using 

    inotifywait --monitor --event close_write  -r some/path/dir/

This doesn't happened in Vim.  Is this normal for Neovim?

**Comment by fmoralesc** [comment]
This is probably the same as #4162, and might be coming from libuv.

**Comment by justinmk** [comment]
Maybe time to upgrade libuv? It's been awhile.

**Comment by da99** [comment]
It seems like a duplicate. I'm closing it. Thanks @fmoralesc
