### ISSUE TITLE
Powerline stops working when truecolor is enabled

### ISSUE THREAD

**Issue by Boelensman1** [neovim/neovim#4201]
For some reason, when the NVIM_TUI_ENABLE_TRUE_COLOR environment variable is set, the powerline symbols seem to stop working. See below for screenshots, the second screenshot is how it is supposed to be.

`export NVIM_TUI_ENABLE_TRUE_COLOR=1 && nvim`
![image](https://cloud.githubusercontent.com/assets/1338743/12903754/65846814-ceca-11e5-9379-3f5d950d9724.png)

`unset NVIM_TUI_ENABLE_TRUE_COLOR && nvim`
![image](https://cloud.githubusercontent.com/assets/1338743/12903767/7a597edc-ceca-11e5-914b-795fe6dd4e9d.png)

This is happening since I updated neovim today.

My $TERM is xterm-256color and I am using gnome-terminal.

**Comment by Boelensman1** [comment]
Just noticed that the line numbers are weird as well, so its not just the powerline symbols.

**Comment by ZyX-I** [comment]
What terminal are you using? Though in any case this does not look like symbols that stop working, this looks like whatever plugin you are using (airline?) is setting invalid background/foreground color.

**Comment by ZyX-I** [comment]
And number color is controlled by a colorscheme and if you colorscheme is not setting guifg/guibg properly it is exactly what Neovim should show with NVIM_TUI_ENABLE_TRUE_COLOR.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/wiki/Following-HEAD#20160204
and https://github.com/neovim/neovim/issues?q=is%3Aissue+airline+is%3Aclosed
