### ISSUE TITLE
nvim doesn't respond properly after it is suspended and resumed

### ISSUE THREAD

**Issue by mananaBanana** [neovim/neovim#4206]
Working on putty. ssh-ing to an ubuntu 14.04 machine.
Steps to reproduce the bug:
1. `nvim filename.py`
2. Suspend nvim (in normal mode only) with Ctrl-Z.
3. Run `bg` first. nvim is continued and suspended again as it can't run in background
4. Follow `bg` with `fg` command. 

neovim opens the document but it doesn't respond and instead prints the keys pressed on the first line of the document.
vim works fine with the same steps.

**Comment by bfredl** [comment]
also after doing this nvim is killed on `^C`

**Comment by justinmk** [comment]
Cannot reproduce, ssh-ing to ubuntu. Possibly helped by https://github.com/neovim/neovim/commit/36c0ec6dd49c8c1a57eaa0b9f9d3c44792582f37.

Please re-open or leave a comment (and say precise `:version`) if this is still an issue on master.
