### ISSUE TITLE
Switching to buffer with many lines = slow

### ISSUE THREAD

**Issue by Ploppz** [neovim/neovim#4208]
On my laptop, nvim 'freezes' for some seconds if I switch to a buffer - in a different tab or window - that has anything more than 500 lines. And this delay is proportional to the number of lines - about 5 seconds for 10000 lines.

I'm using `nvim 0.1.2`.

**Comment by justinmk** [comment]
It didn't happen with a previous version (which is...)? does it happen in vim using the same config

**Comment by Ploppz** [comment]
I'm not sure if it happens in `0.1.1`. Doesn't happen on my desktop which has `0.1.1`. I can update to `0.1.2` when I come home and see. It doesn't happen in vim with the same configs - in vim it's instant.

**Comment by Shougo** [comment]
@Ploppz If does not happen in `0.1.1`, could you execute `git bisect` to detect the bad commit?

**Comment by Ploppz** [comment]
Doesn't happen in either version on my desktop, only on my laptop. I downgraded to `0.1.1` on my laptop and have the exact same problem in that version.

**Comment by Shougo** [comment]
@Ploppz You should create minimal config and the reproduce ways from NeoVim starting.
It is easy to test by other people.

**Comment by justinmk** [comment]
Need steps to reproduce. Or try latest version (0.1.7).
