### ISSUE TITLE
E185: Cannot find color scheme 'monokai'

### ISSUE THREAD

**Issue by versido** [neovim/neovim#4209]
Error message **E185: Cannot find color cheme 'monokai' **was appeared while i am trying to activate :colorscheme monokai 

I have followed vim colorcheme general tutorial to import monokai.vim into /usr/share/vim/vim74/colors and then I configure vimrc but the theme is doesn't work... 

The monokai.vim that i used, from sickill repo. https://github.com/sickill/vim-monokai

**Comment by justinmk** [comment]
>  /usr/share/vim/vim74/colors 

That's not Neovim's runtime files location.
