### ISSUE TITLE
Odd `caw` behavior going into insert state when `c` is pressed

### ISSUE THREAD

**Issue by landaire** [neovim/neovim#4215]
I have some weird behavior with `caw` where if I type `caw` while over a dash, then press quickly `<ESC>lcaw`, I'm put back into insert mode at the previous position without deleting the previous word. Here's a video of the issue: https://youtu.be/8cQxvbkTwyA

Expected behavior: neovim should delete the word my cursor is on and put me in the insert state
Actual behavior: neovim does *not* delete the word my cursor is on and puts me in the insert state when I press `c` as if I had pressed `i`.

I cannot reproduce this with vim. This also does not occur if I type slower.

vim info:

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

neovim info:

```
NVIM v0.1.2-483-g827e267
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160208-25905-hnbgoj/build/config -I/tmp/neovim20160208-25905-hnbgoj/src -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/tmp/neovim20160208-25905-hnbgoj/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160208-25905-hnbgoj/build/src/nvim/auto -I/tmp/neovim20160208-25905-hnbgoj/build/include
Compiled by lander@uoeno.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

**Comment by landaire** [comment]
This actually probably is *not* a problem with neovim and instead a problem with my `init.vim` or one of my plugins (what kind of evil person would do this?). I just tried with `neovim -u NONE` and can't seem to reproduce.

**Comment by landaire** [comment]
Weird, looks like the issue is with `vim-airline`.

**Comment by landaire** [comment]
I'm going to re-open this as it may be a compatibility issue. I cannot reproduce this with the plugins enabled in vim either. I previously thought that airline wasn't enabled in vim, but turns out it is.

**Comment by sudostack** [comment]
@landaire did you ever figure out what it was? I'm experiencing the same issue

**Comment by justinmk** [comment]
> then press quickly `<ESC>lcaw`, I'm put back into insert mode

This just sounds like https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by landaire** [comment]
Nah I don't think that I was using tmux at the time. If you look at my video there's no tmux status bar. I don't recall what the fix is unfortunately.

**Comment by justinmk** [comment]
@landaire That may be the case, but if this is happening _now_ then the linked FAQ item is likely reason.

**Comment by sudostack** [comment]
I don't use tmux, but for me, the issue seems to stem from the deoplete plugin. It doesn't exhibit this odd behavior when I commented out of my `init.vim`, removed it using `PlugClean`, and restarted...

**Comment by justinmk** [comment]
That sounds like https://github.com/neovim/neovim/issues/6166
