### ISSUE TITLE
TUI cursor shape in tmux not working

### ISSUE THREAD

**Issue by mcchrish** [neovim/neovim#4219]
With the latest neovim build from master and with the minimal vimrc:
```
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
```
The cursor doesn't change when going into insert mode in a tmux but works fine with regular terminal. Using iterm2 beta Build 2.9.20160113.

**Comment by jszakmeister** [comment]
You might want to look at #3165 and the [updated man page](https://github.com/neovim/neovim/blob/master/man/nvim.1#L379).  There were some changes recently to how tmux wrapping was done.  I believe @mreed1 was going to update "Following HEAD" on the wiki, but that doesn't look like it was done yet.

**Comment by mcchrish** [comment]
It worked now when I added this to my `.tmux.conf`:
```
set -ga terminal-overrides ',*:Ss=\eE[%p1%d q:Se=\eE[2 q'
```
Yes, I guess this should be spotted in Following HEAD since it's a breaking change.

Thanks @jszakmeister.

**Comment by mreed1** [comment]
> I believe @mreed1 was going to update "Following HEAD" on the wiki, but that doesn't look like it was done yet.

I've been delaying :grin: 

Thanks both of you, I've just updated the page.

**Comment by giulioungaretti** [comment]
It seems to me that it does not work in in iTerm on osX.

**Comment by mhinz** [comment]
@giulioungaretti It should work with a relatively recent build and a stable release of iTerm2. What Neovim and iTerm2 versions do you use?

**Comment by giulioungaretti** [comment]
@mhinz I just nuke the comment  because it disappeared with a new item nightly build :/ 
With  the very last neovim  from head and very last iterm  and tmux  all is good.

**Comment by troym9731** [comment]
Adding `set -ga terminal-overrides ',*:Ss=\eE[%p1%d q:Se=\eE[2 q'` using Iterm2 v3.0.5, Neovim 0.1.4, and tmux 2.2 doesn't seem to work for me.

**Comment by Hultner** [comment]
I'm having this problem as well. Tried both setting the terminal override in tmux and enbaled cursor shape and true color in my .vim.rc. Works fine outside tmux (that's how I noticed the feature at all), now I've tasted the sweet nectar and want it inside my tmux.
