### ISSUE TITLE
How we should mark private functions?

### ISSUE THREAD

**Issue by daynin** [neovim/neovim#4226]
Hello, I want to try to refactor some code, but I can't find style guide about a proper way of private functions marking.

I've read following:

- https://github.com/neovim/neovim/issues/338
- https://github.com/neovim/neovim/issues/323
- https://github.com/neovim/neovim/wiki/C-Refactorings-and-Code-Smells-Catalog

there are different assumptions about how to do this, but there is no decision about it.

**Comment by justinmk** [comment]
There is no guideline yet, though I would like to know how @neovim/core feels about requiring `_` prefix on private functions.

For newly-added, exported ("global") functions there _is_ a guideline: prefix them with a consistent prefix that indicates the module "namespace". E.g. in `message.c`, functions should be named like  `msg_foo`.

**Comment by bfredl** [comment]
what does private function mean here? Just `static` functions or also helper functions for a multi-file subsystem, like  `msgpack_rpc/helpers.c` ?

**Comment by tarruda** [comment]
> There is no guideline yet, though I would like to know how @neovim/core feels about requiring _ prefix on private functions.

I don't think its necessary, but maybe we should start prefixing static functions with the module name, just like global functions. More than once I have accidentally set break on multiple private functions that happen to have the same name, so prefixing with the module name should improve debugging a bit.

**Comment by daynin** [comment]
@bfredl 

> what does private function mean here? Just static functions or also helper functions for a multi-file subsystem, like msgpack_rpc/helpers.c ?

No, a private function is a function with some behavior which we can extract from another function to improve the simplicity of refactored function, but it is useless for using it outside of the module.

For example, we have the following function from `nvim/strings.c`:

```c
/*
 * Make string "s" all upper-case and return it in allocated memory.
 * Handles multi-byte characters as well as possible.
 */
char_u *strup_save(const char_u *orig)
  FUNC_ATTR_NONNULL_RET FUNC_ATTR_MALLOC FUNC_ATTR_NONNULL_ALL
{
  char_u *res = vim_strsave(orig);

  char_u *p = res;
  while (*p != NUL) {
    int l;

    if (enc_utf8) {
      int c = utf_ptr2char(p);
      int uc = utf_toupper(c);

      /* Reallocate string when byte count changes.  This is rare,
       * thus it's OK to do another malloc()/free(). */
      l = utf_ptr2len(p);
      int newl = utf_char2len(uc);
      if (newl != l) {
        // TODO(philix): use xrealloc() in strup_save()
        char_u *s = xmalloc(STRLEN(res) + (size_t)(1 + newl - l));
        memcpy(s, res, (size_t)(p - res));
        STRCPY(s + (p - res) + newl, p + l);
        p = s + (p - res);
        xfree(res);
        res = s;
      }

      utf_char2bytes(uc, p);
      p += newl;
    } else if (has_mbyte && (l = (*mb_ptr2len)(p)) > 1)
      p += l;                 /* skip multi-byte character */
    else {
      *p = (char_u) TOUPPER_LOC(*p);  // note that toupper() can be a macro
      p++;
    }
  }

  return res;
}
```

we can try to extract and refactor this part:

```
      /* Reallocate string when byte count changes.  This is rare,
       * thus it's OK to do another malloc()/free(). */
      l = utf_ptr2len(p);
      int newl = utf_char2len(uc);
      if (newl != l) {
        // TODO(philix): use xrealloc() in strup_save()
        char_u *s = xmalloc(STRLEN(res) + (size_t)(1 + newl - l));
        memcpy(s, res, (size_t)(p - res));
        STRCPY(s + (p - res) + newl, p + l);
        p = s + (p - res);
        xfree(res);
        res = s;
      }

      utf_char2bytes(uc, p);
      p += newl;
```

As a result, we get a function which would be useless for other modules.

@justinmk @bfredl @tarruda
What do you think about it?

**Comment by bfredl** [comment]
Just marking it as static should be fine, but it is good to check that the name is not already used as @tarruda said. Acually I had the problem in #1817 that two different subsystem used the `map_` prefix even for _public_ functions, which caused some conflicts when adding includes.

**Comment by daynin** [comment]
Ok, thank you!
