### ISSUE TITLE
How can Neovim implement scrolling based on screen-lines in long strings of wrapped text?

### ISSUE THREAD

**Issue by publicus** [neovim/neovim#4232]
First, thanks to you all for your work on this project. I just found out about Neovim, and while I don't write C, I'm interested to help with things like documentation as I'm able!

One feature in Vim that has been often-requested by prose writers is the ability to scroll based on screen-lines specifically through _long_ soft-wrapped lines (i.e., when `:set wrap` is used and lines are > 1,000 characters). "Long lines" here are what many writers consider "paragraphs," though I understand that Vim just sees them as lines (having said that, I'll call them paragraphs below).

To clarify, the issue isn't just needing to use `gk` or `gj` to move through soft-wrapped lines. Rather, it's that when approaching the end of a soft-wrapped paragraph, scrolling down by two screen-lines so that the cursor is on the first line of the new paragraph causes the new paragraph to "jump" up and completely fill the screen. The issue is well-summarized (with screenshots) [here](http://stackoverflow.com/questions/27751462/scrolling-long-wrapped-lines-in-vim).

Ideally, there would be a setting for prose-writers that wouldn't require using `textwidth` and `formatoptions += at` to automatically hard-break lines at a given number of characters (this works for things like Markdown, but is difficult to use when, e.g., copying and pasting into a LibreOffice Writer or Word document).

This feature was requested at [least](http://vim.1045645.n5.nabble.com/Long-lines-and-scrolling-td1183898.html) [twice](http://vim.1045645.n5.nabble.com/Scrolling-Long-Lines-Revisited-Again-td5031203.html) on the Vim mailing list (most recently in 2011, if I remember correctly), but seems never to have been further discussed or implemented. I'm writing it up here to see whether Neovim has a way to readily handle this, and if not, to ask how it could be implemented. I'm open to contributing (I can write Python and some Viml), but am not sure if this could be handled by a plugin or if it would need to be incorporated into the core codebase. Given the number of blog, forum, and StackExchange posts I've read on the topic, I suspect that there are quite a few prose writers out there who would benefit from this.

**Comment by dumblob** [comment]
I would also benefit from a non-jumping behaviour (I'm using `gk` `gj` all the time as I remaped `k` `j` to them, because many text files I need to work with have often extremely long lines - thousands of characters).

**Comment by tombh** [comment]
I would also love to see this. From a lot of googling I believe the nearest we currently have to this is a VimL hack: https://vi.stackexchange.com/a/11383

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/7172
