### ISSUE TITLE
ft=dircolors highlighting for color sequences disappears after ~5s

### ISSUE THREAD

**Issue by karlch** [neovim/neovim#4236]
When editing a dircolors file, e.g. LS_COLORS, the highlighting of special color sequences disappears after around 5 seconds. This also happens with `nvim -u NONE` after enabling syntax manually via `:synax enable`. The issue does not appear in vim.

Screenshots for better explanation:
1. Without highlighting
![nvim-no-dircolors](https://cloud.githubusercontent.com/assets/12006766/12973710/a988455e-d0ae-11e5-9e04-22585e1f8e59.png)
2. With highlighting
![vim-with-dircolors](https://cloud.githubusercontent.com/assets/12006766/12973714/b233b878-d0ae-11e5-964a-4d9fb353e25e.png)

Neovim version:
```
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.2/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
```

Vim version (shortened):
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 11 2016 00:20:26)
Included patches: 1-1294
Compiled by Parabola GNU/Linux-libre
Huge version with GTK2 GUI.
```

Operating System: Parabola GNU/Linux-libre (up-to-date)
Both neovim and vim are installed from the official packages.

TERM: screen-256color (using TERM=xterm-256color doesn't make a difference)

The syntax files for dircolors are equivalent in nvim and vim. I have also started nvim via `VIMRUNTIME=/usr/share/vim/vim74 nvim LS_COLORS` which results in a lot of python errors (expected), but the coloring issue persists.

EDIT: my update script must have played me a trick, but the issue persists in the exact same way under neovim 0.1.2 -> version info updated

**Comment by EdJoJob** [comment]
Can also confirm on OSX El Capitan in iTerm2 (Build 2.9.20160206)
TERM: screen-256color
nvim from homebrew `brew install neovim/neovim/neovim --HEAD`
```NVIM v0.1.3-89-g5af9ae9
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160217-32733-73f2ec/build/config -I/tmp/neovim20160217-32733-73f2ec/src -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/tmp/neovim20160217-32733-73f2ec/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160217-32733-73f2ec/build/src/nvim/auto -I/tmp/neovim20160217-32733-73f2ec/build/include
Compiled by eevans43@C02QP6H2G8WN

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"```

**Comment by justinmk** [comment]
Well that's just weird.

**Comment by watiko** [comment]
```sh
$ function test_highlight() {
  $1 -Nu NONE -i NONE \
    -c 'hi default test ctermfg=1' \
    -c 'hi clear test' \
    -c 'hi default test ctermfg=1' \
    -c 'hi test'
}
$ test_highlight vim
test           xxx ctermfg=1
$ test_highlight nvim
test           xxx cleared
```

I think this is the problem.

**Comment by watiko** [comment]
d8f3458ec745cf56dc692b55cc76d8323dbbfc53 introduced this bug.

NOTE: gcc5 require chrry-picking 34b5cee533e457cb72314a0fcca4c227bde8487a

ping @tarruda

**Comment by AdnoC** [comment]
It looks like when the dircolors syntax plugin [clears its highlight groups](https://github.com/neovim/neovim/blob/master/runtime/syntax/dircolors.vim#L190) it isn't clearing the [syntax group as well](https://github.com/neovim/neovim/blob/master/runtime/syntax/dircolors.vim#L189).
