### ISSUE TITLE
Unable to parse certain function definitions

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#425]
The following function definitions are not forbidden and can be used to implement things like function decorators:

```
execute 'function Abc()'
    echo 'Inside a function'
endfunction


command -nargs=1 -bang Function function<bang> <args>

Function Def()
    echo 'Inside a function 2'
endfunction
```

. Did not see this in a wild, but I remember myself once wanting to use second variant to toggle tracing of specific functions (if I required tracing more you would see a whole framework with functions that cannot be parsed as a block).

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/issues/387#issuecomment-983045154
