### ISSUE TITLE
:UpdateRemotePlugins Fails (Python3 + Windows 7 + Neovim + Neovim-QT)

### ISSUE THREAD

**Issue by brcolow** [neovim/neovim#4253]
Minimal init.vim:

``` viml
let g:python3_host_prog='C:\Python34\python.exe'  
```

`echo has('python3')` = 1

However, upon doing `:UpdateRemotePlugins` I get the following error:

![nvim_update_remote_plugins_error](https://cloud.githubusercontent.com/assets/6589866/13030437/7bcd3816-d268-11e5-8c0e-08a33a4e8e34.png)

(Sorry about the screenshot, I am not sure how to yank `:messages`).

**Comment by harila** [comment]
I got this same error on win81 and nyouvim. I'll post logs tomorrow when I get to my work PC.

**Comment by wsdjeg** [comment]
is it same issue as #3749 and or #3800 ?

**Comment by Shougo** [comment]
https://github.com/neovim/python-client/issues/157

It seems same error.

> raise NotImplementedError

Too bad.

**Comment by Shougo** [comment]
> is it same issue as #3749 and or #3800 ?

No.  It is Windows only problem.

**Comment by harila** [comment]
Ok here is my python log

`2016-02-12 11:50:34,440 [ERROR @ base_events.py:default_exception_handler:1090] 5252 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x014FF9B0>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\windows_events.py", line 425, in recv
    self._register_with_iocp(conn)
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\windows_events.py", line 606, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid
2016-02-12 11:50:34,441 [ERROR @ base_events.py:default_exception_handler:1090] 5252 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))>
Traceback (most recent call last):
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Users\johndoe\AppData\Local\Programs\Python\Python35-32\lib\asyncio\proactor_events.py", line 122, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "C:\Users\johndoe\AppData\Roaming\Python\Python35\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 47, in connection_lost
    self._on_error(exc.message if exc else 'EOF')
AttributeError: 'OSError' object has no attribute 'message'
`

**Comment by equalsraf** [comment]
First things first, the attribute error is a consequence of `Exception.message` which was deprecated some in 2.6 (and maybe does not work at all in python 3?). Quick patch to fix that.

```diff
diff --git a/neovim/msgpack_rpc/event_loop/asyncio.py b/neovim/msgpack_rpc/event_loop/asyncio.pyindex 3e23c1b..7f83493 100644
--- a/neovim/msgpack_rpc/event_loop/asyncio.py
+++ b/neovim/msgpack_rpc/event_loop/asyncio.py
@@ -44,7 +44,7 @@ class AsyncioEventLoop(BaseEventLoop, asyncio.Protocol,

     def connection_lost(self, exc):
         """Used to signal `asyncio.Protocol` of a lost connection."""
-        self._on_error(exc.message if exc else 'EOF')
+        self._on_error(exc.args[0] if exc else 'EOF')

     def data_received(self, data):
         """Used to signal `asyncio.Protocol` of incoming data."""
@@ -55,7 +55,7 @@ class AsyncioEventLoop(BaseEventLoop, asyncio.Protocol,

     def pipe_connection_lost(self, fd, exc):
         """Used to signal `asyncio.SubprocessProtocol` of a lost connection."""
-        self._on_error(exc.message if exc else 'EOF')
+        self._on_error(exc.args[0] if exc else 'EOF')

     def pipe_data_received(self, fd, data):
         """Used to signal `asyncio.SubprocessProtocol` of incoming data."""
```

Now the actual error

```
2016-02-15 22:56:16,536 [ERROR @ base_events.py:default_exception_handler:1090] 1816 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x000001FDE2BF0BA8> transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "c:\Users\raf\AppData\Local\Programs\Python\Python35\lib\asyncio\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "c:\Users\raf\AppData\Local\Programs\Python\Python35\lib\asyncio\windows_events.py", line 425, in recv
    self._register_with_iocp(conn)
  File "c:\Users\raf\AppData\Local\Programs\Python\Python35\lib\asyncio\windows_events.py", line 606, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid
```

This is different from neovim/python-client#157 (that deals with named pipes) this one is about stdin/stdout.

**Comment by maxwell-k** [comment]
@equalsraf  Which part of the code is dealing with stdin/stdout?  I'd love to help with this issue. With the latest python-client I get straight to the actual error on both Python 2.7.11 and 3.4.3 on Windows 7 64 bit.

**Comment by equalsraf** [comment]
@maxwell-k stdio connections are established [here](https://github.com/neovim/python-client/blob/master/neovim/msgpack_rpc/event_loop/asyncio.py#L89). I'm not sure what is the current support for stdin/out in asyncio for Windows using the Proactor event loop. It seems we are not alone in this, quick googling points me to [SO question](http://stackoverflow.com/questions/31510190/aysncio-cannot-read-stdin-on-windows), a [gist](https://gist.github.com/nathan-hoad/8966377) and an [issue](https://github.com/python/asyncio/issues/213)

Sidenote: has anyone tried installing pyuv in Windows with Python3? That could work too, if asyncio does not.

**Comment by maxwell-k** [comment]
I haven't used it but the [appveyor builds](https://ci.appveyor.com/project/saghul/pyuv) for [pyuv](https://github.com/saghul/pyuv) pass all of the tests on Windows

**Comment by justinmk** [comment]
This seems to be fixed. `:UpdateRemotePlugins` works, and `python print("foo")` works.
