### ISSUE TITLE
checktime sometimes does not alert on changed files

### ISSUE THREAD

**Issue by chirayuk** [neovim/neovim#4256]
Please note that this is different from issue 3326.

I have a file with no modifications in the vim buffer.  If I try to save the file, I get a `WARNING: The file has been changed since reading it!!! Do you really want to write to it (y/n)?` prompt.  So I run `:checktime`.  Nothing happens.  The file isn't reloaded from disk.  I try to save the file again.  Same warning.  No amount of running `:checktime` is able to get neovim to notice that it's changed on disk and prompt me to load the file from disk (or auto load when autoread is set.)

It might be related to this mainline vim patch (since nvim also has a `fileio.c`)

```
Patch 7.2.210
Problem:    When a file that is being edited has its timestamp updated outside
            of Vim and ":checktime" is used still get a warning when writing
            the file. (Matt Mueller)
Solution:   Store the timestamp in b_mtime_read when the timestamp is the only
            thing that changed.
Files:      src/fileio.c
```

**Comment by justinmk** [comment]
What are the steps to reproduce this, using `nvim -u NONE`?
