### ISSUE TITLE
Junk characters while pasting (Windows+NyaoVim) clipboard unamed

### ISSUE THREAD

**Issue by harila** [neovim/neovim#4257]
There is random junk characters in the paste when clipboard is set to unamed. 
set clipboard=unnamed

This does not happen when "set clipboard" is at its default setting.

Steps to repeat:
Set clipboard to unamed

:enew
Write something
yy
p

![capture](https://cloud.githubusercontent.com/assets/7919817/13041476/26f5fd06-d3c0-11e5-9add-a2d8ce031b88.PNG)

**Comment by equalsraf** [comment]
Cheers

Its a known issue with #810 (https://github.com/equalsraf/neovim/commit/228d875b354cca8c0b03d5a95a4ccd656d0b1abc) for some reason using `winclip -m` sometimes causes this. I'm open to suggestions, or alternatives.

**Comment by jasonwilliams200OK** [comment]
@equalsraf, can we build an inline utility using win32 functions for clipboard manipulation?
https://msdn.microsoft.com/en-us/library/windows/desktop/ff468801.aspx

Here is an example wrapper with pretty basic calls: [pbcopy.c](https://github.com/cava/winclip/blob/master/pbcopy.c) & [pbpaste.c](https://github.com/cava/winclip/blob/master/pbpaste.c)

Here is a usage with encoding and cleanup: https://github.com/SaitoAtsushi/gauche-clipboard/blob/master/gauche_clipboard.c

**Comment by equalsraf** [comment]
@jasonwilliams200OK I was playing with something similar last week. ([win32yank](https://github.com/equalsraf/win32yank), [binary](https://ci.appveyor.com/project/equalsraf/win32yank/build/4/artifacts)). The junk characters seem to be a consequence of an improper check for NULL (or some other wrong assumption about the wide char string size/terminator).

Sometimes there are also trailing \r characters (which makes sense since the docs say lines are separated by CRLF). I've tried to strip those as part of the clipboard tool, but they still show up in some cases (perhaps the cmd shell puts them there), maybe those need to be handled by neovim internally.

**Comment by jasonwilliams200OK** [comment]
@equalsraf, the Rust solution looks great! I saw usage of `CF_UNICODETEXT` followed by `OsString::from_wide`. Wouldn't it cause double encoded?

Probably we can try by capturing a raw string from clipboard and also try with a manual conversion stub like:

C++[11]
```cpp
inline static std::string wstring_to_string(const std::wstring& wstr)
{
    std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> wchar_converter;
    return wchar_converter.to_bytes(wstr);
}
```

C
```c
inline static char* wstring_to_char_ptr(const wchar_t* wstr)
{
    int len = wcslen(wstr)+1; // or try strlen for 1-byte char?
    int room = WideCharToMultiByte(CP_UTF8, 0, wstr, len, NULL, 0, NULL, NULL);
    char* strTo = (char*) malloc(room);
    WideCharToMultiByte(CP_UTF8, 0, wstr, len, strTo, room, NULL, NULL);
    return strTo;
}
```

Then test with the most advanced UTF-8 chars in the text.

**Comment by equalsraf** [comment]
> @equalsraf, the Rust solution looks great! I saw usage of CF_UNICODETEXT followed by OsString::from_wide. Wouldn't it cause double encoding?

It just converts utf16 (from the clipboard CF_UNICODETEXT) to utf8 (which is used internally in Rust). Rust just treats the clipboard data as a cast to a u16 pointer. from_wide converts the array to a utf8 string.

I was under the impression WideCharToMultiByte CP_UTF8 could fail in some codepage environments. But can't find a reference now :S

**Comment by harila** [comment]
Was this resolved? With the latest build and a quick test I could not replacate this issue anymore? Can somebody else confirm?

**Comment by equalsraf** [comment]
> Was this resolved?

Sort of :D I replaced winclip with [win32yank](https://github.com/equalsraf/win32yank) so it should be solved.

I'm still unsure about the newline conversions ([here](https://github.com/equalsraf/neovim/commit/3cc1d922f1d53bba338127ad1c7331710e4706ae#diff-0893c05aff15c6899d56cb0d4f8139f7R51)) we are replacing \r\n with \n when pasting from the clipboard, and replacing \n with \r\n when yanking into the clipboard, so you might want to keep an eye out for weird multi-line issues

**Comment by equalsraf** [comment]
This can be closed, it was a bug in the clipboard provider anyway.
