### ISSUE TITLE
List Remote Plugin Hosts

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#4261]
I would like to be able to view the list of currently connected remote hosts. Currently `:echo serverlist()` will display the list of servers connected but what about rpchosts?

**Comment by justinmk** [comment]
related: https://github.com/neovim/neovim/pull/6743

**Comment by justinmk** [comment]
:echo nvim_list_chans()

It's up to clients/hosts to call `nvim_set_client_info` to identify themselves, as advised in `:help dev-api-client`. For example, latest [pynvim](https://github.com/neovim/pynvim/commit/631006341165fb71498ecb9ed5720a36237b64af) does this.
