### ISSUE TITLE
stdout data broken into two lines when the len of data more than 8346 chars;

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4266]
I encounter this issue from https://github.com/artur-shaik/vim-javacomplete2/issues/193#issuecomment-184226233
as the javacomplete2 use job_control featue get the stdout of `mvn --file pom.xml dependency:build-classpath -DincludeScope=test`,but if the output info longer than 8346 chars,the info afterward will not be got;
I think the core vimscript is here
https://github.com/artur-shaik/vim-javacomplete2/blob/master/autoload/javacomplete/classpath/maven.vim#L26-L27
and
now the stdout date length is 12488 chars
in vim they are the one line
but in neovim they are in two lines
you see here is the `:message`  in neovim
![2016-02-15 23-08-58](https://cloud.githubusercontent.com/assets/13142418/13052362/70f65148-d439-11e5-8130-a9548f1eede2.png)
@artur-shaik with my pool english,may be I miss some important info for this issue,will you supplement any thing?

**Comment by wsdjeg** [comment]
ok I will create a script for this test.
```vim
let g:Test_Home = fnamemodify(expand('<sfile>'), ':p:h:h:gs?\\?/?')
exec "set rtp+=".g:Test_Home
let g:Mysql_vim_Home = fnamemodify(expand('<sfile>'), ':p:h:h:gs?\\?/?')
fu! Test()
    call jobstart(['mvn','--file',g:Mysql_vim_Home . join(['','pom.xml'],'/'),'help:effective-pom', 'dependency:build-classpath', '-DincludeScope=test'], s:compile_lib_callbacks)
endf
let g:flag = 0
fu! s:Compile_lib_JobHandler(job_id,data,event) abort
    if a:event == 'stdout'
        for msg in filter(a:data,'v:val !~ "^\\s*$"')
            if msg =~ 'Dependencies classpath:'
                let g:flag = 1
            endif
            if msg !~ "^[" && msg !~ "^\\s*\<" && g:flag
                echomsg "====> data "
            endif
        endfor
    endif
endfunction

let s:compile_lib_callbacks = {
            \ 'on_stdout': function('s:Compile_lib_JobHandler'),
            \ 'on_stderr': function('s:Compile_lib_JobHandler'),
            \ 'on_exit': function('s:Compile_lib_JobHandler')
            \ }

```

and the pom.xml is 
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.wsdjeg.javalibs</groupId>
    <artifactId>JavaLibs</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>JavaLibs</name>
    <url>http://maven.apache.org</url>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>1.6.0</version>
        </dependency>
        <dependency>
            <groupId>com.jcabi</groupId>
            <artifactId>jcabi-github</artifactId>
            <version>0.23</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
in vim ,there should only has one message ,but in neovim  this break into two data

**Comment by wsdjeg** [comment]
can test with `nvim -u test/test.vim`,and the `pom.xml` should be in current dir, `./pom.xml`

**Comment by mhinz** [comment]
I don't see `Dependencies classpath:` even once in the POM, so `g:flag` never gets set and there should be no output at all.

**Comment by wsdjeg** [comment]
> Why don't you print out the actual msg for debugging purposes?

I have print it out in above pictures,it is too long,so I just print it's length

**Comment by wsdjeg** [comment]
easy test script,without any other program
```vim
fu! Test()
    call jobstart(['echo',g:test], s:compile_lib_callbacks)
endf
let g:test = ""
while len(g:test) < 10000
    let g:test .= "a"
endwhile
fu! s:Compile_lib_JobHandler(job_id,data,event) abort
    if a:event == 'stdout'
        for msg in a:data
            if msg =~ '^\\s*$'
                echomsg '<empty>  : '.len(a:data)
            else
                echomsg '<noempty>  : '.len(a:data)
            endif
        endfor
    endif
endfunction

let s:compile_lib_callbacks = {
            \ 'on_stdout': function('s:Compile_lib_JobHandler'),
            \ 'on_stderr': function('s:Compile_lib_JobHandler'),
            \ 'on_exit': function('s:Compile_lib_JobHandler')
            \ }
```

nvim -u test.vim
call Test()

**Comment by mhinz** [comment]
```vim
fu! Test()
  call jobstart(['echo',g:test], s:compile_lib_callbacks)
endf

let g:test = repeat('a', 8200)

fu! s:Compile_lib_JobHandler(job_id,data,event) abort
  if a:event == 'stdout'
    echomsg string(map(a:data, 'len(v:val)'))
  endif
endfunction

let s:compile_lib_callbacks = {
      \ 'on_stdout': function('s:Compile_lib_JobHandler'),
      \ 'on_stderr': function('s:Compile_lib_JobHandler'),
      \ 'on_exit': function('s:Compile_lib_JobHandler')
      \ }
```

Output:

```
[8192]
[8, 0]
```

libuv's buffers are 8 kibibyte (8192 bytes), so longer lines get broken in several parts.

**Comment by bfredl** [comment]
To be clear here, are you only interested in the complete output after the job exited, or do you also want to interpret output  while the job is running ?

**Comment by fmoralesc** [comment]
> Either libuv or Neovim uses buffers with the size of 8 kibibyte (8192 bytes), so longer lines get broken into several parts.

There it is: https://github.com/libuv/libuv/search?utf8=%E2%9C%93&q=8192

**Comment by bfredl** [comment]
It is not a bug, but it might be a usability problem. We could ship a helper function in the runtime that collects data the correct way, and calls a callback once the job exits with the complete stdout as a list of (unbroken) lines. (if I understood  @wsdjeg use case correctly).

Also I think our docs are unclear, they also mention `join(a:data)` which almost never is the wanted thing.

**Comment by bfredl** [comment]
From job_control.txt:
```
- The arguments passed to `JobHandler()` are:

  0: The job id
  1: If the event is "stdout" or "stderr", a list with lines read from the
     corresponding stream. For "exit", it is the status returned by the
     program.
  2: The event type, which is "stdout", "stderr" or "exit".
```

we need to clarify "list of lines" ( if the last element is not the empty string, then it is an incomplete line that might be continued on the next call)

**Comment by wsdjeg** [comment]
if this is clear date will break after 8192,it is easy for me to update javacomplet2 to follow libuv,and I just want get the reault without missing,do not main it is in one line or two.

**Comment by justinmk** [comment]
@wsdjeg Could you see if this is still a problem on latest master? I wonder if https://github.com/neovim/neovim/pull/4646 fixed it.

**Comment by justinmk** [comment]
This appears to be the same (documentation) issue as https://github.com/neovim/neovim/pull/4950#discussion_r68512337

**Comment by ramunas** [comment]
I came across this very same issue. It would be really helpful that you updated the docs to reflect what is really passed to the job handlers at both places: jobstart() and job_control.txt.

It also would be nice to have a handler that is called where the lines are not broken since it is the more common use case and less surprising (the user should not need to worry about the buffer sizes and the joining of lines). I suppose, jobstart() could be configured with an entry in {opts} to change the behaviour of calling  on_stdout and on_stderr.

**Comment by bfredl** [comment]
@ramunas That is on my TODO list. I suspect the really common use case is to get the entire stdout/stderr (this would be useful internally as well, see the TODO in python provider in #4723 ), which could be supported i.e. by a `on_stdout_close` callback when EOF is received that will get the entire stream (possibly with some size limit, so a lot memory can't get consumed, if huge output is expected the user will need to care about buffering)

**Comment by ramunas** [comment]
@bfredl That's good to know. I think you are right about the use case, however, I think it is till worth providing the one I described.

**Comment by justinmk** [comment]
> which could be supported i.e. by a `on_stdout_close` callback when EOF is received

Just a surface distinction, but I would prefer passing the full stdout in `on_exit` (discussed  at https://github.com/neovim/neovim/issues/5023#issuecomment-231550745 ).
