### ISSUE TITLE
[0.1.1 -> 0.1.2] langmap got fixed

### ISSUE THREAD

**Issue by trusktr-goin** [neovim/neovim#4275]
After updating from 0.1.1-2 to 0.1.2-1 on Arch Linux, `set langmap` stopped working as it was in 0.1.1.

I use

```viml
                set langmap=hHjkKi;iIhjJk

                noremap <c-i> <c-k>
                noremap <c-j> <c-h>
                noremap <c-k> <c-j>
                noremap <c-h> <c-i>

                noremap <a-i> <a-k>
                noremap <a-j> <a-h>
                noremap <a-k> <a-j>
                noremap <a-h> <a-i>

                noremap <c-a-i> <c-a-k>
                noremap <c-a-j> <c-a-h>
                noremap <c-a-k> <c-a-j>
                noremap <c-a-h> <c-a-i>

                noremap <c-s-i> <c-s-k>
                noremap <c-s-j> <c-s-h>
                noremap <c-s-k> <c-s-j>
                noremap <c-s-h> <c-s-i>
```

In theory, I shouldn't have to use the extra mappings below the `set langmap` and the `set langmap` should be enough to cause those mappings to be unnecessary. Has there been any work done relating to https://github.com/neovim/neovim/issues/2199 perhaps?

**Comment by trusktr-goin** [comment]
The behavior I had in 0.1.1 was that I also had these mapping for switching tabs (this code is what follows after the previous snippet):

```viml
                map <a-h> <a-left>
                map <a-l> <a-right>
                map j <a-left>
                map l <a-right>
                nnoremap <a-left> gT
                nnoremap <a-right> gt
```

Now, after updating to 0.1.2, pressing alt+j makes the cursor move upwards instead of the expected of switching to the leftward tab.

**Comment by justinmk** [comment]
langmap does not seem relevant.

> alt+j makes the cursor move upwards instead of the expected of switching to the leftward tab.

alt+j will do whatever `<M-j>` is mapped to. Looks like you are using recursive maps, so not totally sure what it's resolving to in your case.

https://github.com/neovim/neovim/pull/3982

**Comment by justinmk** [comment]
Hmm. The second comment threw me off. Need sleep.

**Comment by trusktr-goin** [comment]
Seems like the problem in #2199 has been fixed! Woot woot.

So, this actually works now (no need for the extra mappings, and the mapping in the second snippet works ):

```js
                set langmap=hHjkKi;iIhjJk

                "noremap <c-i> <c-k>
                "noremap <c-j> <c-h>
                "noremap <c-k> <c-j>
                "noremap <c-h> <c-i>

                "noremap <a-i> <a-k>
                "noremap <a-j> <a-h>
                "noremap <a-k> <a-j>
                "noremap <a-h> <a-i>

                "noremap <c-a-i> <c-a-k>
                "noremap <c-a-j> <c-a-h>
                "noremap <c-a-k> <c-a-j>
                "noremap <c-a-h> <c-a-i>

                "noremap <c-s-i> <c-s-k>
                "noremap <c-s-j> <c-s-h>
                "noremap <c-s-k> <c-s-j>
                "noremap <c-s-h> <c-s-i>

                map <a-h> <a-left>
                map <a-l> <a-right>
                map h <a-left>
                map l <a-right>
                nnoremap <a-left> gT
                nnoremap <a-right> gt

```

**Comment by justinmk** [comment]
> Seems like the problem in #2199 has been fixed! 

@trusktr-goin  Can that issue be closed, or can you condense it into a revised issue with only the remaining relevent parts?

**Comment by trusktr-goin** [comment]
Yep, we can close #2199 that issue now (I don't have the button to close it though). Sweeeeeeeeeeeeeeeeeeeeet.
