### ISSUE TITLE
after updating for the last nvim i get this error

### ISSUE THREAD

**Issue by 7belrhalmia** [neovim/neovim#4278]
viminfo: Illegal starting char in line: ^A<ce>V<c4>gIU<85><a9>generator<c4>^Dnvim<a7>version<c4>^XNVIM v0.1.0-108-g57a5745<a9>max_kbyte
E575: viminfo: Illegal starting char in line: <a3>pid<cd>^Sƨencoding<c4>^Eutf-8^E<ce>Vô^U><83><a2>rc<91><c4>0^Ix.ServeHTTP(http.ResponseWriter, *http.Request)<a1>n0<a2>rt^A^E<ce>Vø^G^V<83><a2>rc<91><c4>^H^Ix = mux<a1>n1<a2>rt^A^E<ce>Vóg><83><a2>rc<91><c4>0^Ix.ServeHTTP(http.ResponseWriter, *http.Request)<a1>n2<a2>rt^A^E<ce>Vò}&<83><a2>rc<91><c4>^X^Ihf:=map[string][string]<a1>n3<a2>rt^A^E<ce>Vò{̂<83><a2>rc<98><c4>^Xtype patHandler struct {<c4>^K^Ipat string<c4>^M^Ihttp.Handler<c4>^A}<c4>^]type PatternServeMux struct {<c4>^W^Ihandlers map[string][]<c4>^A}<c4>
E575: viminfo: Illegal starting char in line: <a1>c^M^H<ce>V<bb><f1><bf>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^O<a1>c^M^H<ce>V<bb><f1><bf>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l
E575: viminfo: Illegal starting char in line: <a1>c^M^H<ce>V<bb><f1><bf>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^O<a1>c^M^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^]<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^Y<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^\<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^X<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^]<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^Y<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^\<a1>c"^H<ce>V<bb><f1><fb>5<83><a1>f<c4>*/home/belr/Gopro
E575: viminfo: Illegal starting char in line: ^H<ce>V<c4>fH5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^I<a1>c
E575: viminfo: Illegal starting char in line: ^H<ce>V<c4>fs2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^Q^H<ce>V<c4>fv-<83><a1>f<c4> /home/belr/.config/nvim/init.vim<a1>l<cd>^D]<a1>c^K^H<ce>V<c4>f<8c>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^Q^H<ce>V<c4>f<cc>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^Q^H<ce>V<c4>f<ea>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c^A^B<ce>V<a9><99>^M^Q<83><a2>sp<c4>^Cctr<a2>scâsh<c3>^C
E575: viminfo: Illegal starting char in line: <ce>V<a9><ae><87>8<84><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l<<a1>c^Q<a1>nw
E575: viminfo: Illegal starting char in line: <ce>V<c4>gI2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P
E575: viminfo: Illegal starting char in line: <ce>V<c4>f<e9>8<84><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c^B<a1>n^
E575: viminfo: Illegal starting char in line: <ce>V<c4>f<e9>8<84><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c^B<a1>n.^K<ce>Vó<fa>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^R^K<ce>Vó<fa>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c<^K<ce>Vó<fa>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^R^K<ce>Vó<fa>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c<^K<ce>Vó<fa>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^R^K<ce>Vó<fa>5<83><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^P<a1>c<^K<ce>Vó<fa>2<82><a1>f<c4>*/home/belr/Goprogram/src/myprogram/main.go<a1>l^R^K<ce>Vó<fa>5<83><a1>f<c4>*

**Comment by justinmk** [comment]
Looks like your `main.shada` file was replaced with something weird.

**Comment by jcrben** [comment]
fyi, in my case it seems this was caused by an environment variable I'd set to use XDG for vim:

```
# per https://tlvince.com/vim-respect-xdg
# commenting out while using neovim
# export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
```
