### ISSUE TITLE
Is there a way to set a quickfix title?

### ISSUE THREAD

**Issue by nerdrew** [neovim/neovim#4279]
`cgetexpr`, `setqflist`, etc will set `w:quickfix_title` to the name of the command. https://github.com/benekastah/neomake uses `cgetexpr ''` or `lgetexpr ''` to create an empty list and items are appended async. The `statusline` for such quickfix / location list windows is unhelpfully: `cgetexpr ''`. It would be nice to set `w:quickfix_title` to a custom string based on the make command being used.

Something like: `new_qf_list 'ag --vimgrep --smart-case needle'` and have `w:quickfix_title` set to `ag --vimgrep --smart-case needle`

**Comment by mhinz** [comment]
I'm not sure I understand. :) You want extra code added to Neovim, for a rather specific use case, when the plugin itself could simply set `w:quickfix_title` itself?

**Comment by ZyX-I** [comment]
@mhinz How you can set `w:quickfix_title` without opening a window? AFAIR vim-dev had discussion about `setqftitle` and alternatives (some modification to `setqflist()`). And AFAIK such change was never in.

**Comment by ZyX-I** [comment]
@mhinz Also this action *will not* set quickfix title internally, so when you close quickfix window and reopen it `w:quickfix_title` will be the old string.

**Comment by mhinz** [comment]
Oh, so that's the problem. It wasn't clear from the description.

Reference: https://groups.google.com/forum/#!topic/vim_dev/X7VVPd4Do5s

How do we deal with changes that should be inherited from Vim but are TODO'd? The [latest patch](https://12985092515833507022.googlegroups.com/attach/8f4bb279ca5f1340/vim-setqflist_title_2.diff?part=0.1&view=1&vt=ANaJVrGfm02Td85JFFFSC8EjhU9NludwWdrNYkuyxuw2mMTPleLzIBumf293OnRnxzoM3sFayotIaPael5t4EuUrfOmjsX6QDDEfwAFgZWPZHLIqRnCmVVk) looks easy enough.

**Comment by justinmk** [comment]
> How do we deal with changes that should be inherited from Vim but are TODO'd?

It doesn't have much bearing on us unless Bram's tealeaves strongly suggest he is going to merge it upstream soon (e.g. it was clear the `:cdo` patch was going to be merged soon, so we waited on it).

**Comment by mhinz** [comment]
Okay.

@blueyed Will you send a PR? I'd take over otherwise.

**Comment by nerdrew** [comment]
Sorry I wasn't clear in the original description. The use case I have in mind is for neomake (though I think it is generally applicable): I open a new empty quickfix list, then add items to it from an async job. The quickfix list title ends up being `cgetexpr ''` since that's what is used to create an empty list. I'd like to be able to create a quickfix list with an arbitrary title and then add items to that list later.

Here's my hackaround in neomake: https://github.com/nerdrew/neomake/commit/60836329f36c6ad3810f04f9650e0661109031bb

I add my desired title as a comment after `cgetexpr ''` so it persists across `:cnewer` and `:colder`

**Comment by blueyed** [comment]
@mhinz
Please take it, I do not have time for it currently.

**Comment by ZyX-I** [comment]
Should be solved by #4337
