### ISSUE TITLE
Option not supported: guifont [Windows]

### ISSUE THREAD

**Issue by zovt** [neovim/neovim#4282]
Seems like neovim is built without guifont support on windows

**Comment by equalsraf** [comment]
@zovt there is no guifont option at the moment. Different GUIs have different ways to handle this. For neovim-qt its the :Guifont command https://github.com/equalsraf/neovim-qt/wiki/GUI#how-to-change-the-font

**Comment by justinmk** [comment]
'guifont' is now available and is forwarded to UIs. https://github.com/neovim/neovim/pull/7520
