### ISSUE TITLE
Add support for `filename:line_number` syntax

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#4283]
This format has become extremely common for stack traces output and test runners.

I know you can run vim with `vim +line_number filename`, but it would be incredibly handy to be able to just copy/paste from a stack trace and have vim Just Work®.  I can accomplish this other ways, but I wanted to see if there was support for it here.

**Comment by phanimahesh** [comment]
This can be solved by a plugin already, like https://github.com/bogado/file-line.

But it is a good nice-to-have. Neovim can probably ship the linked plugin or something similar by default.

**Comment by justinmk** [comment]
https://github.com/kopischke/vim-fetch should achieve this.

I think this is already covered by https://github.com/neovim/neovim/issues/1281

**Comment by jfelchner** [comment]
@justinmk thank you. :)
