### ISSUE TITLE
Default color scheme is slightly different from vim's

### ISSUE THREAD

**Issue by 5nizza** [neovim/neovim#4285]
The color for keywords (for example `set`) is lighter on the right (vim), 
and it is imho better (more visible on dark screens):
(neovim on the left, vim on the right)

![side-by-side](https://cloud.githubusercontent.com/assets/928552/13139649/6066516c-d64f-11e5-8905-af15422f3ca7.png)

Version NVIM 0.1.3-dev, OS 3.13.0-77-generic #121-Ubuntu, gnome-terminal 3.6.2.

(if this was resolved already -- just say so, please hint how to change this for nvim, and close the issue:-)

**Comment by justinmk** [comment]
what colorscheme is this? by "default" you must mean your distro's default. Please link to or paste the full colorscheme.

**Comment by 5nizza** [comment]
sorry, I don't understand you, @justinmk.
Calling `:colorsheme` in neovim returns `default`.
NVIM, OS, terminal versions are written above.
I also just git cloned nvim version `00347ec781cf64c8e9c81dde456312f70ec3f4cb` from the github,
started it with `VIMRUNTIME=/usr/share/vim/vim74 nvim ./some_file` and got the same colors.

Also:
``` 
in vim:
:hi Statement
Statement      xxx term=bold ctermfg=3 gui=bold guifg=Brown

in nvim:
:hi Statement
Statement      xxx ctermfg=130 gui=bold guifg=Brown
```

**Comment by phanimahesh** [comment]
I believe the default colorscheme for your system will be at `/usr/share/vim/vim74/colors/default.vim`. Can you please locate that file and paste its contents?

**Comment by justinmk** [comment]
That just doesn't look anything like the default color scheme, but maybe you have different colors configured at the terminal level.

Anyways, are we missing term=bold in our default. vim?

**Comment by 5nizza** [comment]
After some trying, I figured out that the 'default' colorscheme in my case is equivalent to 'peachpuff'.
When calling in nvim `:colorscheme peachpuff`, the colors become equivalent to vim's default (and hence to vim's `peachpuff`).
But it is not clear why nvim has a different color 'by default' for Statement in my case.
I will probably add `:colorscheme peachpuff` into nvim config somewhere..
If that is not a bug, feel free to close the case. Thank you!

@phanimahesh vim's default.vim = nvim's defaul.vim:

```
cat /usr/share/vim/vim74/colors/default.vim

" Vim color file
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last Change:	2001 Jul 23

" This is the default color scheme.  It doesn't define the Normal
" highlighting, it uses whatever the colors used to be.

" Set 'background' back to the default.  The value can't always be estimated
" and is then guessed.
hi clear Normal
set bg&

" Remove all existing highlighting and set the defaults.
hi clear

" Load the syntax highlighting defaults, if it's enabled.
if exists("syntax_on")
  syntax reset
endif

let colors_name = "default"

" vim: sw=2
```

**Comment by mkoskar** [comment]
During some unrelated testing of mine I've noticed that `default` colorscheme is different in Vim (`vim -N -u NONE`) from NVim (`nvim -u NONE`) until explicit `:colorscheme default` is done in Vim. I've noticed it for background color of tabs. Could it be related? seems like a Vim bug to me.

**Comment by nhooyr** [comment]
Cannot reproduce this. They are the exact same for me.

**Comment by cemeyer** [comment]
They're still different (nearly 4 years later) despite having identical SHA1 default.vim's with terminology 1.4.1, FWIW.  It's like nvim is using the bold or bright versions of each foreground color instead of the regular variant (except strings and string substitutions swap from red and dark purple to light purple and red, respectively).  neovim 0.4.2, vim 8.0.0962.

As the other guy said, `:colorscheme peachpuff` in nvim looks like vim's `default` on my terminal.  Hope it helps somebody else.

**Comment by bew** [comment]
Can you check the value of `set background?`, iirc neovim has some logic to detect a dark background and enables `background=dark` for better text visibility in that case.

**Comment by cemeyer** [comment]
In neovim, with `colorscheme default`, I see `background=dark`.  With `peachpuff`, I see `background=light`.

**Comment by jam1015** [comment]
Hey I know I'm late to the party here, but I can confirm that neovim reads color files differently than macvim on my computer.  I copied the ``` ~/.vim/colors/default.vim``` file to ```~/.config/nvim/colors``` and got different results when I set ```colorscheme: default``` in vim and macvim in the terminal (run using ```macvim -v```.   I tested this again using a copy of default called ```default_copy.vim``` to make sure that ```default``` wasn't a special case.

**Comment by timmyjose** [comment]
I know this is a closed issue, but I had to report my findings as well. I'm a Vim user, now trying out neovim. My preferred colour scheme is the builtin `desert` colour scheme. 

Here is the same file showing up different in neovim (top) and vim (bottom):

![image](https://user-images.githubusercontent.com/2051158/84568999-f7ae7680-ada0-11ea-8cdc-efd27b9545bd.png)

I felt that there was something jarring when I opened up the file I was working on, and immediately realised that the colours were off. For reference, I am using tmux on iTerm2 with a dark background. 

Also, to doubly confirm so, I even downloaded the `desert.vim` file and placed it in the `~/.config/nvim/colors` folder. No change, of course.

Is this something that can be understood better, or no?

**Comment by glacambre** [comment]
Have you also tried to download and use Vim's haskell syntax file? The 
differences might be in the syntax groups being defined.

**Comment by timmyjose** [comment]
> Have you also tried to download and use Vim's haskell syntax file? The differences might be in the syntax groups being defined.

Yeah, you were right. I saw your comment even as I realised that I had not `PlugInstall`ed the plugins for nvim. Hah!
