### ISSUE TITLE
Zoomwin like ability ootb?

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#4286]
I always thought zoomwin should be default in vim, ie pressing ^WO should maximize current window, pressing it again should restore previous splits.

**Comment by justinmk** [comment]
Please see existing issue.

**Comment by phanimahesh** [comment]
FYI: The old issue is https://github.com/neovim/neovim/issues/997.

**Comment by mtglsk** [comment]
Thanks.

**Comment by justinmk** [comment]
Though https://github.com/neovim/neovim/issues/997 was closed, the functionality needed to support this and other use cases is covered by https://github.com/neovim/neovim/issues/3933
