### ISSUE TITLE
Can't start another vim inside neovim

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4287]
I use command like
```
!git commit -a
```
to commit files inside vim, but it not works inside neovim, and I got the error message:

<img width="822" alt="screen shot 2016-02-18 at 9 04 52 pm" src="https://cloud.githubusercontent.com/assets/251450/13144086/4bb05c70-d683-11e5-88b3-eb2bef4a5a35.png">

It doesn't looks like a bug, but how can I commit the files with another vim started without using of `<ctrl-z>` and `fg`?

**Comment by fmoralesc** [comment]
Open a `:terminal` buffer and launch the command from there.

**Comment by chemzqm** [comment]
@fmoralesc I've tried  `:terminal` and `:terminal echo 1`, it always get stucked and I can't do anything except close terminal,  I've using the latest neovim from `brew install --HEAD neovim`

**Comment by fmoralesc** [comment]
To leave the terminal mode you need to use <C-\><C-n>, that way you can go back to your other buffers or execute vim commands.

**Comment by chemzqm** [comment]
@fmoralesc whenever I use that command, neovim would stucked and I can do nothing.
There's something weird happened with neovim and my configuration, I can use that command with `nvim -u NONE`

**Comment by fmoralesc** [comment]
Without using `-u NONE`, check the output of `:map <C-\>`, perhaps something is interfering.

**Comment by chemzqm** [comment]
@fmoralesc I've fixed the problem, I have statusline plugin calling `git rev-parse --abbrev-ref HEAD` by `system` command to get current branch, I fixed it by make the function ignore terminal buffer

**Comment by chemzqm** [comment]
`ternimal` is great, thanks for your help.
