### ISSUE TITLE
<abuf> not works for TermClose autocmd

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4291]
I  write some vimscript like:
```
command! -nargs=? Nrun :call s:TernimalRun(<q-args>)

function! s:TernimalRun(cmd)
  execute '5new'
  call termopen(a:cmd, {
        \ 'on_exit': function('s:OnExit'),
        \ 'buffer_nr': bufnr('%'),
        \})
  execute 'wincmd p'
endfunction

function! s:OnExit(...) dict
  let lines = getbufline(self.buffer_nr, 1, '$')
endfunction

function! s:OnTermClose(buf)
  echo a:buf
endfunction

augroup neorun
  autocmd!
  autocmd TermClose * :call s:OnTermClose(+expand('<abuf>'))
augroup end
```
so I can run `:Nrun git push` to start git push in a split buffer,  but after reading all the documentation about terminal and job_control, I can't find the way of get the exit code.  So I went to check the buffer lines on exit, but the lines would always be empty strings (looks like the event triggered earlier than the buffer change). I thought TermClose autocmd might works, but I can only get current buffer by `expand('<abuf>')` which should be the terminal buffer.

**Comment by justinmk** [comment]
Thanks for the useful observations. Here's what I found:

- `expand('<abuf>')` in `TermClose` returns the buffer _number_
- `bufname(expand('<abuf>'))` in `TermClose` is useless, the buffer was already destroyed(?)
- `getbufline(self.buffer_nr, 1, '$')` in `on_exit` is also useless (as you observed), again because `on_exit` is fired after the terminal buffer is destroyed.

**Comment by justinmk** [comment]
Closing this since things actually seem to be working, it's just VimL quirks.

**Comment by chemzqm** [comment]
@justinmk for the exit code, it works, but the problem is the buffer number is wrong, try this:
```
autocmd TermClose * :echo expand('<abuf>')
```
and use:
```
:sp +term
```
to open a split terminal buffer, then
```
sleep 5 && exit
```
navigate to the buffer below, and you can see the echo result is current buffer number, but it should be terminal buffer number.

I've tried the callback function like:
```
function! s:OnExit(...) dict
  echo a:000
endfunction
```
but only get empty list, looks like I have to always set the arguments explicitly,

**Comment by mhinz** [comment]
Yea, the code simply returns `curbuf`, which obviously leads to problems in an async environment. I'll look into it.
