### ISSUE TITLE
Pasting specific text using terminal shortcut in insert mode sets "paste" randomly

### ISSUE THREAD

**Issue by XrXr** [neovim/neovim#4292]
1. Copy `http://stackoverflow.com/questions/2861627/paste-in-insert-mode`
2. Enter insert mode
3. Press and hold `ctrl+shift+v`

It should change to `-- INSERT (paste) --` shortly. If you keep pasting it would switch paste mode on and off randomly

**Comment by atommclain** [comment]
Looking at `:help paste` it looks like you either need to call `:set paste` and `:set nopaste` or map a keyboard command to paste toggle.

9a3b7f Gentoo 2.2 Bash 4.3.42 connected via iTerm 2.1.1
nvim -u NONE
:set paste<ESC>
i // `-- INSERT (paste) --`
<⌘-v> // Paste for OS X
http://stackoverflow.com/questions/2861627/paste-in-insert-mode // appears

**Comment by atommclain** [comment]
I think I misunderstood your original issue, can you provide repro steps with vim? I tried to repro this with vanilla vim and I can't get it to go into insert paste mode after pasting.

**Comment by XrXr** [comment]
The repo case is in the original issue, pasting the text causes neovim to go in and out of `:set paste` mode randomly

**Comment by atommclain** [comment]
I see, since it wasn't going into -- INSERT (paste) -- mode for me, I thought you were saying that is the behavior that it should be exhibiting.

Does it repro with `nvim -u NONE`?

**Comment by XrXr** [comment]
Yes it does. I guess I should be posting my system info..

NVIM v0.1.3-128-gf887037 On Arch Linux with gnome-terminal

**Comment by tjdevries** [comment]
I also have a similar problem. I can send my information maybe sometime later today. Not sure exactly what text triggers it thought.

**Comment by wsdjeg** [comment]
I can not reproduced with latest neovim in gnome-terminal in ubuntu,but what is your gnome-terminal version,as I know the old version and the latest version both has issue with neovim,I am using 3-16-2

**Comment by myitcv** [comment]
I also have a similar problem, happens randomly. I don't have a set of repro steps at this stage but will post them when I do.

**Comment by wsdjeg** [comment]
and I think you should know in neovim `|bracketed-paste-mode| is built-in and enabled by default.`

**Comment by myitcv** [comment]
@wsdjeg - that is an interesting and important point.

**Comment by wsdjeg** [comment]
so we do not switch to paste mode before we paste something by using `<c-v>` or `<c-s-v>`(this is default in gnome-terminal)

**Comment by XrXr** [comment]
@wsdjeg I'm using gnome-terminal 3.18.2

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/3566

**Comment by wsdjeg** [comment]
`3.18.2 `  ok, can you reproduce my issue?
here is link https://github.com/neovim/neovim/issues/3998
https://github.com/neovim/neovim/issues/3969

**Comment by XrXr** [comment]
@wsdjeg I tried both, don't have issues here.

**Comment by wsdjeg** [comment]
what is your os?

**Comment by wsdjeg** [comment]
ok ,maybe it is just issue in ubuntu

**Comment by e-kwsm** [comment]
Also in Debian jessie.

**Comment by e-kwsm** [comment]
On debian jessie, this behaviour is still (76ea97c) observed: `<PASTE>` is inserted to the end and switched into `paste` mode.
This is OCCASIONAL and I cannot reproduce by myself, though...

**Comment by e-kwsm** [comment]
I'm not sure why, but now I can reproduce the behavior in my environment.



- `nvim --version`: NVIM v0.2.3-1499-g7c4bb23ff
Build type: RelWithDebInfo
LuaJIT 2.0.5
- Vim (version: ) behaves differently? Yes
- Operating system/version: Debian Jessie 9.3
- Terminal name/version: GNOME Terminal 3.22.2 Using VTE version 0.46.1 +GNUTLS
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Copy the following code

```
#%Module
set prefix /usr/local/tbb/2018_U2/linux_intel64_gcc_cc6.3.0_libc2.24_kernel4.9.0_release
prepend-path CPLUS_INCLUDE_PATH $prefix/include
prepend-path LIBRARY_PATH $prefix/lib
prepend-path LD_LIBRARY_PATH $prefix/lib
prepend-path LD_RUN_PATH $prefix/lib
```

and

```
nvim -u NORC
" paste from clip-board
```

### Actual behaviour
`<PASTE>` is inserted in the end and `paste` mode is turned on.

![paste](https://user-images.githubusercontent.com/11627708/34722301-9f12cee4-f589-11e7-9f51-9ae57bb7d461.gif)

### Expected behaviour
`<PASTE>` is not inserted and `nopaste` remains.

**Comment by moorchegue** [comment]
Still an issue. v0.3.1.

Try pasting the contents of this file in the paste mode for example: https://git.archlinux.org/pacman.git/plain/proto/PKGBUILD.proto

I've never had this problem with Vim.

**Comment by pappasam** [comment]
I've experienced this issue ever since switching to Neovim over a year ago. It's not a deal breaker, but I'm surprised the issue is closed (since it's definitely still affecting users)

* OS: Linux Mint 19.2
* Neovim Version: v0.4.0-dev (latest nightly build)

**Comment by MaxNoe** [comment]
Still and issue with 0.4.2

**Comment by moorchegue** [comment]
Interestingly enough with a fresh nvim installation on a new computer this problem doesn't seem to exist anymore. I started to suspect that it was in fact one of the plugins that was causing it.
