### ISSUE TITLE
Terminal cursor position goes to last line when creating/destroying splits

### ISSUE THREAD

**Issue by fevin86** [neovim/neovim#4293]
- Neovim version: 0.1.2
- Operating system: OSX
- Terminal emulator: Iterm2
### Actual behaviour

In term normal mode, cursor position moves to the last line when adding/deleting a split.
### Expected behaviour

The cursor position should be stay same.
### Steps to reproduce
- open nvim
- :vs | te (create a terminal split)
- press enter to generate lines to fill terminal screen
- enter normal mode then go to first line of terminal split
- close the other split

**Comment by exider** [comment]
I can confirm this.


NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/build/config -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/src -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-2G4J_c/neovim-0.1.2ubuntu1+git201602171545+2283+17~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-16

**Comment by justinmk** [comment]
Cannot reproduce on current HEAD 7e6980a . Maybe related: https://github.com/neovim/neovim/pull/6185
