### ISSUE TITLE
Detect for python3  could add more than 60ms at startup time

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4297]
- Neovim version: 0.1.3-dev
- Operating system: Mac OSX
- Terminal emulator: iterm2

Use command
```
echo '' > startup.txt && nvim --startuptime startup.txt
```
and open `startup.txt`, I got 
```
107.022 066.101 065.718: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/python3.vim
```
Change the line
```
let [s:prog, s:err] = provider#pythonx#Detect(3)
```
 in `python3.vim` to
```
let [s:prog, s:err] = ['python3', '']
```
and use the nvim command again, the startup time becomes
```
037.321  000.740  000.464: sourcing /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/provider/python3.vim
```
and my vim become fast again.

60ms is too much for me, it's much more than the total source time of all my plugins.
I thought using a environment variable might be better.

**Comment by mhinz** [comment]
Please see `:h g:python3_host_skip_check`.

**Comment by wsdjeg** [comment]
python3_host_skip_check is removed?

**Comment by bfredl** [comment]
@wsdjeg instead set `g:python3_host_prog` to the executable for quick startup.

**Comment by justinmk** [comment]
see also `:help g:loaded_python3_provider`
