### ISSUE TITLE
Use <Ctrl+{h,j,k,l}> in Terminal Mode not working

### ISSUE THREAD

**Issue by hhsnopek** [neovim/neovim#4300]
- Neovim version: v0.1.2, v0.1.3-140-gaf67f02
- Operating system: OSX 10.11.3
- Terminal emulator: iTerm 2 (Build 2.9.20151213-nightly)

### Actual behaviour
Terminal commands are executed

### Expected behaviour
`.nvimrc`/nvim bindings should take priority over terminal cmds

### Steps to reproduce
1. Add mappings below
```
" These don't work
tnoremap <C-j> <C-\><C-w>j
tnoremap <C-k> <C-\><C-w>k
tnoremap <C-l> <C-\><C-w>l
tnoremap <C-h> <C-\><C-w>h

" Escape works
tnoremap <ESC> <C-\><C-n>
tnoremap <C-\> <Esc>

" These work
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-h> <C-w>h
```
2. restart nvim or `:source ~/.nvimrc`
3. press any mapping combination to switch panes

**Comment by justinmk** [comment]
tnoremap <C-j> <C-\><C-w>j

should be `tnoremap <C-j> <C-\><C-n><C-w>j`

**Comment by hhsnopek** [comment]
oops, thank you @justinmk :smile:
