### ISSUE TITLE
Buffer location list get copied after split

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4305]
- Neovim version: v0.1.3-112-g3e3db58
- Operating system: Mac OS
- Terminal emulator: Iterm2

### Actual behaviour
Location list would be copied to other split buffer

### Expected behaviour
Location list should not be copied to other buffer after split 

### Steps to reproduce
* nvim -u NONE tmp
* Add some text to tmp file
* `:lexpr getline(1,'$')`
*  Open a random split window like `:h`
*  Use `lopen` or `echo getloclist(1)` to check the lcoation list

**Comment by mhinz** [comment]
It's the same in Vim, see `:h location-list`:

```
When a window with a location list is split, the new window gets a copy of the location list.
```

**Comment by ZyX-I** [comment]
Location lists do not apply to buffers, they apply to windows. And @mhinz is right about that being an expected behaviour.
