### ISSUE TITLE
$NVIM_TUI_ENABLE_CURSOR_SHAPE causes konsole terminal to reset to default font size when entering insert mode

### ISSUE THREAD

**Issue by drzel** [neovim/neovim#4309]
- Neovim version: NVIM 0.1.3-dev
- Operating system: Linux (Kubuntu 14.04)
- Terminal emulator: Konsole: 2.13.2

### Actual behaviour
With $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1, after enlarging or shrinking font size in Konsole, entering insert mode will restore to the default font size.

### Expected behaviour
Should be able to enlarge or shrink font size as needed and enter insert mode without it reverting to default.

### Steps to reproduce
In init.vim: `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1`

- Open Konsole
- Start Neovim
- Increase font size (Ctrl +)
- Enter insert mode

Font should revert to default size.

**Comment by fmoralesc** [comment]
This sounds like a konsole bug.

**Comment by justinmk** [comment]
@drzel Can you report to konsole?

**Comment by silky** [comment]
this is now happening again, even though it didn't used to.

**Comment by silky** [comment]
and actually, it happens irrespective of the `NVIM_TUI_ENABLE_CURSOR_SHAPE` setting.
