### ISSUE TITLE
Window of terminal buffer can't be restored when setting sessionoptions-=blank

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#4311]
- Neovim version: 0.1.3
- Operating system: Mac OX
- Terminal emulator: iTerm2

### Actual behaviour
The terminal buffer would be restored without the associated window

### Expected behaviour
The terminal buffer should be restored with the associated window

### Steps to reproduce
* nvim some_file
* :set sessionoptions-=blank
* :mksession! tmp.vim
* nvim -S tmp.vim

I don't like blank window, so I want them get removed when session restored,  and I think window with terminal buffers should not belongs to blank window.

**Comment by justinmk** [comment]
Ah, I get it: the `:term://` buffers _are_ restored in the session, but their windows are not. It's because `bt_nofile` returns truthy for buftype=terminal. I'll see if this can be fixed without much work.
