### ISSUE TITLE
Nvim not loading plugins any longer after update

### ISSUE THREAD

**Issue by 4Digits** [neovim/neovim#4312]
- Neovim version: NVIM 0.1.3-dev
- Operating system: Linux Mint 17.01
- Terminal emulator: -

### Actual behaviour

I recently upgraded Neovim, which is not starting correctly with my `.nvimrc`.
I noticed that the configuration file now has to be placed in `.config/nvim/init.vim`,
so I sourced my old file within it: `source ~/.nvimrc`

When I now start neovim I get the following errors:

```
Error detected while processing /home/myuser/.nvimrc:
line   16:
E117: Unknown function: plug#begin
line   19:
E492: Not an editor command: Plug 'scrooloose/nerdtree'^I^I^I^I^I^I" Filesystem in sidebar
line   20:
E492: Not an editor command: Plug 'kien/ctrlp.vim'^I^I^I^I^I^I^I" Fuzzy finder
line   21:
E492: Not an editor command: Plug 'bling/vim-airline'^I^I^I^I^I^I" Status / tabline
line   22:
E492: Not an editor command: Plug 'scrooloose/syntastic'^I^I^I^I^I^I" Syntax checking
line   23:
E492: Not an editor command: Plug 'ervandew/supertab'^I^I^I^I^I^I" <Tab> insert completion
line   24:
E492: Not an editor command: Plug 'tpope/vim-surround'^I^I^I^I^I^I" Parentheses, brackets, etc.
line   25:
E492: Not an editor command: Plug 'mattn/emmet-vim'^I^I^I^I^I^I^I" Abbreviations similar to Emmet
line   26:
E492: Not an editor command: Plug 'tpope/vim-fugitive'^I^I^I^I^I^I" Git wrapper
line   27:
E492: Not an editor command: Plug 'airblade/vim-gitgutter'^I^I^I^I^I" Shows a git diff in the 'gutter'
line   28:
E492: Not an editor command: Plug 'freeo/vim-kalisi'^I^I^I^I^I^I^I" Kalisi colorscheme
line   29:
E492: Not an editor command: Plug 'Yggdroot/indentLine'^I^I^I^I^I^I" Indent lines
line   32:
E117: Unknown function: plug#end
line   38:
E185: Cannot find color scheme 'kalisi'
```

### Expected behaviour

Neovim should correctly load all plugins like before.

### Steps to reproduce

-

**Comment by fmoralesc** [comment]
You don't have vim-plug installed in a location neovim uses; you would have to put it in or link it to`~/.config/nvim/autoload/`.

**Comment by mhinz** [comment]
You probably only moved your vimrc to `~/.config/nvim/init.vim`, but the whole configuration (`~/.vim`) is expected to be under `~/.config/nvim` now. That's not the case, so `~/.config/nvim/autoload/plug.vim` can't be found which leads to Neovim not knowing `plug#begin` and `:Plug` etc.

See `:h nvim-configuration` or https://github.com/mhinz/vim-galore/blob/master/content/neovim.md#configuration
