### ISSUE TITLE
Building fails on Debian Jessie 8.3 (using current Git sources)

### ISSUE THREAD

**Issue by KurtPfeifle** [neovim/neovim#4316]
- Neovim version: Sources from current Git repository ()
- Operating system:
- Terminal emulator:

Today I tried to build neovim on OS X Yosemite (10.10.5) and Debian Jessie (8.3). There was no problem to build it on OS X, but on Debian Jessie I ran into an error (with some more details + context given below): **`./.deps/build/src/libuv/autogen.sh: Bad substitution`**

### Actual behaviour

```
kp@lenjessie2:git.neovim > make
make  -C .deps
make[1]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[2]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
[ 11%] Built target jemalloc
make[3]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
[ 23%] Built target unibilium
make[3]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
[ 34%] Built target libtermkey
make[3]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
make[3]: Entering directory '/home/kp/svn-stuff/git.neovim/.deps'
[ 36%] Performing configure step for 'libuv'
/home/kp/svn-stuff/git.neovim/.deps/build/src/libuv/autogen.sh: 43: /home/kp/svn-stuff/git.neovim/.deps/build/src/libuv/autogen.sh: Bad substitution
CMakeFiles/libuv.dir/build.make:100: recipe for target 'build/src/libuv-stamp/libuv-configure' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 2
make[3]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
CMakeFiles/Makefile2:204: recipe for target 'CMakeFiles/libuv.dir/all' failed
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kp/svn-stuff/git.neovim/.deps'
Makefile:70: recipe for target 'deps' failed
make: *** [deps] Error 2
``` 

#### All the required pre-requisits are installed:

```
kp@lenjessie2:git.neovim > sudo apt-get install libtool libtool-bin autoconf automake cmake g++ pkg-config unzip libmsgpack-dev libuv-dev libluajit-5.1-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libuv0.10-dev' instead of 'libuv-dev'
autoconf is already the newest version.
automake is already the newest version.
cmake is already the newest version.
g++ is already the newest version.
libtool is already the newest version.
libtool-bin is already the newest version.
libuv0.10-dev is already the newest version.
libluajit-5.1-dev is already the newest version.
libmsgpack-dev is already the newest version.
pkg-config is already the newest version.
unzip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

kp@lenjessie2:git.neovim > dpkg -l  libtool libtool-bin autoconf automake cmake g++ pkg-config unzip libmsgpack-dev libuv-dev libluajit-5.1-dev 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version        Architecture  Description
+++-========================-==============-=============-=====================================================
ii  autoconf                 2.69-8         all           automatic configure script builder
ii  automake                 1:1.14.1-4     all           Tool for generating GNU Standards-compliant Makefiles
ii  cmake                    3.0.2-1        amd64         cross-platform, open-source make system
ii  g++                      4:4.9.2-2      amd64         GNU C++ compiler
ii  libluajit-5.1-dev:amd64  2.0.3+dfsg-3   amd64         Just in time compiler for Lua - development files
ii  libmsgpack-dev           0.5.7-3        amd64         binary-based efficient object serialization library
ii  libtool                  2.4.2-1.11     all           Generic library support script
ii  libtool-bin              2.4.2-1.11     amd64         Generic library support script (libtool binary)
un  libuv-dev                <none>         <none>        (no description available)
ii  pkg-config               0.28-1         amd64         manage compile and link flags for libraries
ii  unzip                    6.0-16+deb8u2  amd64         De-archiver for .zip files
```

### Expected behaviour

```
[ 11%] Built target jemalloc
[ 23%] Built target unibilium
[ 34%] Built target libtermkey
[ 46%] Built target libuv
[ 57%] Built target libvterm
[ 69%] Built target luajit
[ 81%] Built target luarocks
[ 92%] Built target msgpack
[ 94%] Built target busted
[ 95%] Built target luacheck
[ 97%] Built target nvim-client
[ 98%] Built target lua-messagepack
[100%] Built target lpeg
[100%] Built target clean-shared-libraries
[100%] Built target third-party
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C build
[  0%] Generating auto/ex_docmd.c.generated.h, ../../include/ex_docmd.h.generated.h
[  0%] Generating auto/path.c.generated.h, ../../include/path.h.generated.h
[  3%] Generating auto/version.c.generated.h, ../../include/version.h.generated.h
[  3%] Generating auto/os/env.c.generated.h, ../../include/os/env.h.generated.h
[  3%] Generating auto/ex_docmd.c.generated.h, ../../include/ex_docmd.h.generated.h
[  3%] Generating auto/os/env.c.generated.h, ../../include/os/env.h.generated.h
[  3%] Generating auto/path.c.generated.h, ../../include/path.h.generated.h
[  3%] Generating auto/version.c.generated.h, ../../include/version.h.generated.h
[ 81%] Built target nvim
[ 81%] Built target sjiscorr
[ 96%] Built target translations
[ 96%] Built target shell-test
[ 96%] Built target tty-test
[100%] Generating copy_docfiles
[100%] Generating doc/tags
[100%] Built target runtime
```

### Steps to reproduce

1. Install Debian Jessie.
2. Run **`sudo apt-get update && sudo apt-get upgrade`**.
3. Run **`sudo apt-get install build-essential libtool libtool-bin autoconf automake cmake g++ pkg-config unzip libmsgpack-dev libuv-dev libluajit-5.1-dev`**
4. Run **`make $HOME/svn-stuff && cd $HOME/svn-stuff`**.
5. Run **`git clone https://github.com/neovim/neovim.git git.neovim`**.
6. Run **`make`**.

**Comment by justinmk** [comment]
Seems like a libuv build issue. It's been awhile since we updated libuv...

**Comment by glaubitz** [comment]
KurtPfeilfe:

You did not test-build the package in a clean build-environment. Please use sbuild or pbuilder to build the package as otherwise there is no means to make sure the problem doesn't lie somewhere on your system.

Also, neovim builds fine on unstable/experimental [1], so I'm not sure there is a bug here at all.

> [1] https://buildd.debian.org/status/fetch.php?pkg=neovim&arch=amd64&ver=0.1.2-1&stamp=1456089747

**Comment by justinmk** [comment]
That too. @KurtPfeifle Are you able to build libuv by itself?

**Comment by jamessan** [comment]
At least libmsgpack-dev and libuv0.10-dev shouldn't be installed through apt.  The versions in Jessie are too old, and having the system installed versions can cause problems when trying to use the bundled versions.

**Comment by KurtPfeifle** [comment]
@glaubitz:

> *"You did not test-build the package in a clean build-environment."*

No, I didn't.

I followed the instructions given here:

* https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

Also, I've never used `pbuilder` or `sbuild` before. AFAIU, these are tools to build binary Debian packages from Debian source packages. But I want to build from Git sources, because I want to follow the week-by-week development progress of Neovim.

Where would I fetch current Debian source packages?

**Comment by KurtPfeifle** [comment]
@justinmk:

> *"Seems like a libuv build issue. It's been awhile since we updated libuv..."*

For a test, I removed `libuv01.0` and replaced it by `libuv1` and `libuv1-dev` from the *jessie-backports*  repository.

This didn't work either.

Also, the Wiki says (here:  https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) that `libuv-dev` should be installed on Debian (and this then leads to installation of `libuv0.10-dev`).

If this Wiki instruction is wrong, please update it to one that works.

**Comment by KurtPfeifle** [comment]
@jamessan:

> *"At least libmsgpack-dev and libuv0.10-dev shouldn't be installed through apt."*

If that's an official statement by the Neovim developer team, then please correct the Wiki instructions how to build Neovim from sources.

> *"The versions in Jessie are too old, and having the system installed versions can cause problems when trying to use the bundled versions."*

I added the *jessie-backports* repository and  installed `libuv1-dev` and `libuv1` instead of `libuv0-dev`, but this gave the same error message(s).

**Comment by glaubitz** [comment]
> If it is a requirement to use pbuilder or sbuild if I wan to build on Debian (Jessie), then please say so in the Wiki build instructions.

Umh, I'm not a neovim developer, I'm a Debian developer and what I said isn't really new or exotic, it's common sense when building packages.

> Also, I've never used pbuilder or sbuild before.

And you blame other people for that?

> AFAIU, these are tools to build binary Debian packages from Debian source packages.

Which is what you want to do when you work on Debian.

> But I want to build from Git sources, because I want to follow the week-by-week development progress of Neovim.

Then you should be familiar enough with the build system and building software from source. It's not for everyone and you cannot expect developers to give support for users who, on one hand, want to use development versions of software but, on the other hand, do not have enough expertise to fix the issues that arise with such versions themselves.

If you use git snapshots, you should know what you're doing.

> If this Wiki instruction is wrong, please update it to one that works.

Neovim is in currently work-in-progress on many fronts. Any documentation is going to be outdated the moment it's been written.

> If that's an official statement by the Neovim developer team, then please correct the Wiki instructions how to build Neovim from sources.

Just build and install neovim in an unstable chroot. The build dependencies on Debian Jessie are apparently just too old.

**Comment by jamessan** [comment]
> Just build and install neovim in an unstable chroot. The build dependencies on Debian Jessie are apparently just too old.

They're too old in unstable too.  msgpack-c, neovim, and libvterm are only in experimental currently.  That being said, if he's building from git then all the dependencies are downloaded and built unless specified otherwise.

> /home/kp/svn-stuff/git.neovim/.deps/build/src/libuv/autogen.sh: 43: /home/kp/svn-stuff/git.neovim/.deps/build/src/libuv/autogen.sh: Bad substitution

At least from the initial information you provided, libuv is having issues building.  Looking at [autogen.sh](https://github.com/libuv/libuv/blob/5467299450ecf61635657557b6e01aaaf6c3fdf4/autogen.sh#L43), that's the call to libtoolize.  I would suggest taking a look at why that's failing in your environment.

**Comment by KurtPfeifle** [comment]
@glaubitz:

> *"Umh, I'm not a neovim developer, I'm a Debian developer and what I said isn't really new or exotic, it's common sense when building packages."*

But I do not want to build *packages*. I just want to compile *binaries* from the Neovim Git sources, following the instructions from the Neovim Wiki.

I want to keep my official Debian packages of Neovim, and I want to install my self-compiled binaries into `/usr/local/` (like it or not -- that's my affair, not yours), using/testing these whenever I want...

>> *"Also, I've never used pbuilder or sbuild before.*
>
> And you blame other people for that?"

No, sorry. I didn't want to blame anyone. I shouldn't have mentioned this. My bad.

> *"Please use sbuild or pbuilder to build the package as otherwise there is no means to make sure the problem doesn't lie somewhere on your system."*

And you blame me for not using pbuilder or sbuild, when I follow the Neovim Wiki instructions (https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) which does not mention pbuilder nor sbuild when compiling on Debian?!

> *"Which is what you want to do when you work on Debian."*

Thanks for telling me what I "want to do". I'll take it into consideration.

> *"Then you should be familiar enough with the build system and building software from source."*

I am familiar enough with different systems in order to very frequently build `Ghostscript`, `GhostPDL`, `MuPDF`, `Poppler`, `ImageMagick`, `Pandoc`, `dactyl`, `PDF.js`, `Tabula-Extractor`, `CUPS`, `cups-filters` and other software from their respective sources.

> *"It's not for everyone [...]"*

True and agreed.

> *"[...] and you cannot expect developers to give support for users who, on one hand, want to use development versions of software but, on the other hand, do not have enough expertise to fix the issues that arise with such versions themselves."*

I'll suppress a personal expletive here and just point out, that *some* developers ***do*** want feedback, even from non-developer users, concerning their development versions. And they *all* certainly want feedback, if their published build instructions do not work!

So please, refrain treating users as "too stupid" and stop patronizing. Please let the Neovim developers decide by themselves what *they* want their build instructions to be, and don't interfere with your currently beside-the-point pbuilder and sbuild advice unless that becomes the only officially recommended way to build Neovim on Debian.

**Comment by KurtPfeifle** [comment]
@jamessan:

> *"At least from the initial information you provided, libuv is having issues building. Looking at autogen.sh, that's the call to libtoolize. I would suggest taking a look at why that's failing in your environment."*

I was already looking at autogen.sh, but couldn't spot where the problem is.

That's why I opened this issue here.

I'm at my wits' end.

We'll see if other Debian users also have problems. Or if, over time, somebody else can spot the problem with my specific build environment, should it in general work flawlessly on Debian Jessie.

Thanks for caring.

**Comment by KurtPfeifle** [comment]
@jamessan:

> *"Looking at autogen.sh, that's the call to libtoolize. I would suggest taking a look at why that's failing in your environment."*

Ok, I experimented a bit -- without fully understanding what I'm doing.

I commented out line 42 of *`.deps/build/src/libuv/autogen.sh`*. Instead of

```bash
set -ex
```

it now reads

```bash
# set -ex
```

Results:

1. The build process completes,
1. `make install` puts the binary into `/usr/local/`.
1. `/usr/local/bin/nvim` starts up.
1. There is no obvious problem when using this instance of Neovim.
1. I'm happy for now.

Maybe someone who's really in the clue can now investigate why said line no. 42 causes the problem it does and make the appropriate modifications to the sources or to the Wiki build instructions.

**Comment by KurtPfeifle** [comment]
Please note that my successful build used `libuv1{,-dev}` (from the `jessie-backports* repository, not `libuv0.10{,-dev}' after commenting out the line saying `set -ex` in `autoconf.sh`. 

If you want, I can revert back to the "standard" distro `libuv0.10{,-dev}` packages and test these too.

**Comment by jamessan** [comment]
For what it's worth, I setup a minimal jessie chroot, installed the dependencies listed on the wiki and started a build.  libuv built fine for me, so there does seem to be something specific to @KurtPfeifle's environment that's affecting this.

I tried both with current HEAD and changing back to libuv 1.7.3, which was what was being used when this issue was first reported.

**Comment by glaubitz** [comment]
> For what it's worth, I setup a minimal jessie chroot, installed the dependencies listed on the wiki and started a build. libuv built fine for me, so there does seem to be something specific to @KurtPfeifle's environment that's affecting this.

Yeah, that's what I was suspecting the whole time. But @KurtPfeifle apparently knew better ...

**Comment by KurtPfeifle** [comment]
@jamessan:

1. Did you notice my comments saying

    > *"The build process completes."* and *"my successful build used ...."*

    So, to repeat: I was able to build successfully after

    1. Installing the `"libuv1{,-dev}"` packages from the *jessie-backports* repository.
    1. Commenting out line 42 of *autogen.sh* saying `"set -ex"`.

    However, I do not understand why using/keeping `"set -e -x"` in *autogen.sh* would cause the reported `"Bad substitution"` error message.

2. You write:

    > *"I setup a minimal jessie chroot, installed the dependencies listed on the wiki and started a build. libuv built fine for me [...]"*

    I was not aware that we are supposed to build libuv ourselves. The Wiki's instruction said (and still does say): *`"sudo apt-get install [...] libuv-dev [...]"`* -- which does not sound exactly like *"You have to build libuv yourself"* !

----

But anyway, thanks for devoting your time and effort to my problem, @jamessan  :-)

**Comment by KurtPfeifle** [comment]
@glaubitz:

Stop talking trash. 

I ***didn't*** "know better".

I was asking for help. 

And I was pointing out that the Wiki instructions didn't and still do not work as they currently stand.

**Comment by jamessan** [comment]
@KurtPfeifle Unless otherwise specified when you run `make`, various dependencies including libuv are built automatically.  This automatic build of libuv is what failed for you in the original report.

I suspect that the failure or success of your build had nothing to do with whether the Debian packages of libuv (either the ones from jessie or jessie-backports) were installed, but is related to something else in your environment.  My initial suggestion to remove those packages was simply to try and remove some potential sources of noise in the process, since I knew that libuv was going to be built anyway.

My attempt at reproducing your scenario succeeded without me having to make any changes to the libuv source that was downloaded by the build process.  That is why it seems there is something else in your environment that is causing the problem.

I'm not sure why the wiki suggests installing packages that are automatically built, but those instructions worked just fine for me in the jessie chroot.  It's not as simple as `they don't work`.

**Comment by KurtPfeifle** [comment]
@jamessan:

> *"when you run* ***`make`***, *various dependencies including libuv are built automatically."*

Thanks for your explanations, James.

I was not aware of that (but earlier, I had run `"grep libuv Makefile"` which didn't return a result)  -- and I didn't understand (and still don't), why then the Wiki lists as build-prerequisite an installation of the `libuv-dev` package.

> *"It's not as simple as* ***`they don't work`*** *"*

You've convinced me now  :-)

Thanks for your patience. 

I'm a happy Neovim/bleedingedge user now, also on Debian (after it works on OSX since a while already).

**Comment by jamessan** [comment]
I just removed those packages from the instructions.  The Debian/Ubuntu section was the only one that listed them.

Anyone who goes through the trouble to disable the automatic building of the third-party dependencies should also be able to figure out what packages they need to install.

**Comment by jhinrichsen** [comment]
I ran into the same problem, my system was missing libuv1-dev and texinfo packags.

**Comment by justinmk** [comment]
If installing texinfo solves the problem, most likely it's by accident, because texinfo _depends on_ something that Nvim's build needs. texinfo itself isn't required by Nvim's build AFAIK.
