### ISSUE TITLE
viml syntax: wrong highlight for "fu! zvim#test()"

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4321]
- Neovim version:

```
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-
security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG 
-Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-
protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS 
-DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-1or27S/neovim-
0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/build/config -I/build/neovim-1or27S
/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/src -I/build/neovim-1or27S
/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-
1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/usr
/include/luajit-2.0 -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-1or27S/neovim-0.1.2ubuntu1+git201602210704+2291+17~ubuntu15.10.1/build/include
编译者 buildd@lgw01-37

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/share/nvim"
```
- Operating system: ubunut 15-10
- Terminal emulator:gnome-terminal 3.16.2
### Actual behaviour

hilight error

``` vim
fu! zvim()
endf
```

here `z` has same color as `fu`
### Expected behaviour

`z` should has same color as `vim`
### Steps to reproduce
1. nvim -u NONE
2. syntax enable
3. e test.vim

**Comment by fmoralesc** [comment]
Can't reproduce. `zvim` should be highlighted as an Error:
![captura de pantalla de 2016-02-22 17-39-20](https://cloud.githubusercontent.com/assets/221465/13224975/3ad250e2-d98b-11e5-84f6-3705534ec2cc.png)

**Comment by wsdjeg** [comment]
do you use `vim -u NONE`?
and what is your nvim version.I found it works well in vim

**Comment by fmoralesc** [comment]
Yes, `nvim -u NONE`. This is the latest version.

**Comment by wsdjeg** [comment]
can not understand why it is diff from mine.and why it is a error

**Comment by fmoralesc** [comment]
The reason it is shown as an Error is that user defined viml functions can't begin with a lowercase letter, unless it is a scope identifier. So, `zvim` is an Error, but `s:zvim` is OK.

The reason `z` is shown differently  might be that the syntax file for viml expects the scope to be next and in lowercase. Compare 
~~~
fun! z
~~~
and 
~~~
fun! s:zvim()
endfun
~~~

**Comment by wsdjeg** [comment]
but why
fu！ zvim#Test()
endf
same

**Comment by wsdjeg** [comment]
hi @fmoralesc I think this is a issue ,and not been fixed,let me show you some pics,
![2016-02-23 16-48-59](https://cloud.githubusercontent.com/assets/13142418/13246249/5cfa62d2-da4d-11e5-82b8-99aec1faab96.png)
I think the only second third and the last one should be hi as error

**Comment by fmoralesc** [comment]
OK, I can reproduce that. I think I know what the issue is. That z gets highlighted as a `vimCommand`.

In `runtime/syntax/vim.vim`, the function definitions are defined like this:
~~~ vim
syn cluster	vimFuncList	contains=vimCommand,vimFunctionError,vimFuncKey,Tag,vimFuncSID
~~~
but I think it should be like this:
~~~ vim
syn cluster	vimFuncList	contains=vimFunctionError,vimFuncKey,Tag,vimFuncSID
~~~
However, you should probably contact the maintainer of the file upstream, drchip (see the header of the file), since he knows best.

**Comment by justinmk** [comment]
Aren't we sorta maintaining our own vim.vim now, since it is autogenerated?

**Comment by fmoralesc** [comment]
Not this part of it.

**Comment by fmoralesc** [comment]
It might be a collision in the autogenerated part of the file, though, because I can confirm this doesn't happen in vim...

**Comment by justinmk** [comment]
Seems to be fixed.

**Comment by wsdjeg** [comment]
@justinmk hi,I still can reproduce this issue in master.
![2017-01-17_163x64](https://cloud.githubusercontent.com/assets/13142418/22020934/b1e25d1c-dcf5-11e6-9898-556ca31b79e6.png)

`z` still has same color as `fu` and `endf`.

**Comment by justinmk** [comment]
That wasn't the test case given in the original report...

**Comment by wsdjeg** [comment]
Yeah, sorry, thanks for changging the title.

**Comment by justinmk** [comment]
cannot reproduce this on NVIM v0.4.0-381 7fcf2f926

**Comment by wsdjeg** [comment]
Yeah, it seems has been fixed.
