### ISSUE TITLE
New gendeclarations.lua from #4216 makes "empty" recompiles slow

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#4326]
- Neovim version: since 8d7ab23
- Operating system: Arch Linux
- Terminal emulator: urxvt

### Context 
I migrate legacy test, therefore I execute make with a `TEST_FILE=some_file.lua` environment quite often in order to run a single test. Since #4216 (8d7ab23) this takes *very* long. 
### Actual behavior 
`make && time make functional TEST_FILE=` reports a time around 35 secs for the "empty" make call.
### Expected behavior
It should be around 1-3 secs (was below 2 secs before)
### Steps to reproduce
`make && time make functional TEST_FILE=` 
This will run make to recompile everything as necessary and the measure the time for an "empty" make run (one that should not need to build anything and then tries to run no test file, which was the fasted test I could think of :-)

**Comment by justinmk** [comment]
I noticed this too, it regenerates the auto-generated files over and over. @bfredl Should we revert that change, or any idea what the problem is?

**Comment by bfredl** [comment]
I noticed it as well. We need a marker that the regeneration did happen after the original source was changed. I tried to add the `.i` as a third output but it didn't help. (It was okay before to have a output that wasn't updated, I wonder what the difference is now). I then tried to remove the `.h` outputs but then cmake complains about missing source files. Some of the cmake experts could take a look at `src/nvim/CMakeLists.txt:151`

**Comment by bfredl** [comment]
Aha, the order of `OUTPUT` matters, placing the `.i` file first removes this problem, but it breaks #4216 ...

**Comment by lucc** [comment]
Can we check if the .c file is newer than the .generated.h file in gendeclarations.lua? I tried this:
```diff
diff --git a/scripts/gendeclarations.lua b/scripts/gendeclarations.lua
index 637f4cd..40660e0 100755
--- a/scripts/gendeclarations.lua
+++ b/scripts/gendeclarations.lua
@@ -7,7 +7,12 @@ local preproc_fname = arg[4]
 
 
 local lpeg = require('lpeg')
+local lfs = require('lfs')
 
+local newer = function (file_name_1, file_name_2)
+  return lfs.attributes(file_name_1, 'modification') >
+	 lfs.attributes(file_name_2, 'modification')
+end
 local fold = function (func, ...)
   local result = nil
   for i, v in ipairs({...}) do
@@ -166,6 +171,8 @@ if fname == '--help' then
   print()
   print'  gendeclarations.lua definitions.c static.h non-static.h preprocessor.i'
   os.exit()
+elseif not newer(fname, non_static_fname) and not newer(static_fname, non_static_fname) then
+  os.exit()
 end
 
 local preproc_f = io.open(preproc_fname)
```
But it did not change anything. I admit I was to lazy to check if my code does what it should anyways.

**Comment by bfredl** [comment]
The problem is not in ` gendeclarations.lua` but in `src/nvim/CMakeLists.txt`. We need a way to say the gendeclarations target was built without causing the dependent `.o` target to be rebuilt, unless the "real" dependencies `.generated.h` was changed and not just the marker. In a plain makefile it could be done with nested calls to make to separate the steps (or maybe even without) but I don't know how to express it in cmake.

**Comment by lucc** [comment]
I had a look through the cmake files and the generated make files and found one problem:

The generated headers depend on the gendeclarations.lua script but they are only updated if the updated version is *different* from the old version and not if they are newer then *all* dependencies. 

So if the script is newer than the generated header the makefile tries to rebuild the header but the script will not update it because the new generated header is not different from the old generated header.

Some code to illustrate this:
```sh
make # be sure that everything is up to date
touch -d -10years scripts/gendeclarations.lua # make the script really old
time make # takes around 6 seconds for me
time make # still 6 seconds
touch scripts/gendeclarations.lua # make the script really new
time make # all headers are out of date, takes around 20 secs for me
time make # headers still out of date because the script is still newer, still 20 secs
```
On the run that takes 6 secs some headers are still regenerated (or at least tried). I do not yet understand why the makefile considers them out of date.

**Comment by bfredl** [comment]
Because these `.c` files where touched since the last `make clean` or actual update of the generated headers. (it's basically the same problem with both the source dependencies and the script dependency)

**Comment by lucc** [comment]
Thanks @bfredl, after `make clean` the time from my last post changed from 6 secs to a very acceptable 1 sec (20 secs are still the same and unacceptable).

So a temporary fix is to run `make clean && touch -d -10years scripts/gendeclarations.lua`.

**Comment by bfredl** [comment]
though `make clean` should work as a workaround without messing with the age of `scripts/gendeclarations.lua`
