### ISSUE TITLE
cannot download jemalloc while compiling

### ISSUE THREAD

**Issue by xsmyqf** [neovim/neovim#4331]
- Neovim version:
    commit 75f6817a5161949ca2ab08e36b8e0772b8d7da16
- Operating system:
    debian 8 jessie
- Terminal emulator:
    gnome-terminal
### Actual behaviour
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/home/xieshuai/tools/nvim"
make  -C .deps
make[1]: Entering directory '/home/xieshuai/source/neovim/.deps'
make[2]: Entering directory '/home/xieshuai/source/neovim/.deps'
make[3]: Entering directory '/home/xieshuai/source/neovim/.deps'
make[3]: Leaving directory '/home/xieshuai/source/neovim/.deps'
make[3]: Entering directory '/home/xieshuai/source/neovim/.deps'
[  1%] Performing download step for 'jemalloc'
-- file: /home/xieshuai/source/neovim/.deps/build/downloads/jemalloc/jemalloc-4.0.2.tar.bz2
-- downloading...
     src='https://github.com/jemalloc/jemalloc/releases/download/4.0.2/jemalloc-4.0.2.tar.bz2'
     dst='/home/xieshuai/source/neovim/.deps/build/downloads/jemalloc/jemalloc-4.0.2.tar.bz2'
     timeout='none'
CMake Error at /home/xieshuai/source/neovim/third-party/cmake/DownloadAndExtractFile.cmake:74 (message):
  error: downloading
  'https://github.com/jemalloc/jemalloc/releases/download/4.0.2/jemalloc-4.0.2.tar.bz2'
  failed

    status_code: 52
    status_string: "Server returned nothing (no headers, no data)"
    log: Hostname was NOT found in DNS cache
    Trying 192.30.252.129...

  Connected to github.com (192.30.252.129) port 443 (#0)

  successfully set certificate verify locations:

    CAfile: none
    CApath: /etc/ssl/certs

  SSLv3, TLS handshake, Client hello (1):

  

CMakeFiles/jemalloc.dir/build.make:82: recipe for target 'build/src/jemalloc-stamp/jemalloc-download' failed
make[3]: *** [build/src/jemalloc-stamp/jemalloc-download] Error 1
make[3]: Leaving directory '/home/xieshuai/source/neovim/.deps'
CMakeFiles/Makefile2:134: recipe for target 'CMakeFiles/jemalloc.dir/all' failed
make[2]: *** [CMakeFiles/jemalloc.dir/all] Error 2
make[2]: Leaving directory '/home/xieshuai/source/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/xieshuai/source/neovim/.deps'
Makefile:70: recipe for target 'deps' failed
make: *** [deps] Error 2

### Expected behaviour
to be compiled
### Steps to reproduce
into git local folder,and compile,then the error is reported

**Comment by phanimahesh** [comment]
Could be a transient issue. I can access the jemalloc release file as expected. Can you retry after a while?

**Comment by justinmk** [comment]
Please try again. We can't do anything about network issues.
