### ISSUE TITLE
TabNew triggered after TabEnter

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#4333]
- Neovim version: NVIM v0.1.3-211-g47b529
- Operating system: Ubuntu 14.04.3 LTS
- Terminal emulator: Gnome-terminal

### Actual behaviour
TabNew is triggered after TabEnter

### Expected behaviour
According to the documentation, TabNew should be triggered before TabEnter. It also makes more sense so you can do initialisation work in TabNew?

### Steps to reproduce
:au TabEnter * echom "TabEnter"
:au TabNew * echom "TabNew"
:tabnew

#### Output:
TabEnter
TabNew

#### Expected output:
TabNew
TabEnter

**Comment by mhinz** [comment]
Confirmed. I'm looking into it.
