### ISSUE TITLE
TabNew and TabNewEntered not triggered on a tab split buffer

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#4334]
- Neovim version: NVIM v0.1.3-211-g47b529
- Operating system: Ubuntu 14.04.3 LTS
- Terminal emulator: Gnome-terminal
### Actual behaviour

TabNew and TabNewEntered are not triggered on a tab split.
### Expected behaviour

TabNew and TabNewEntered are triggered on a tab split.
### Steps to reproduce

:au TabNew \* echom "TabNew"
:au TabNewEntered \* echom "TabNewEntered"
:tab split
#### Output:

Nothing
#### Expected output:

TabNew
TabNewEntered

**Comment by justinmk** [comment]
@fmoralesc thoughts?

**Comment by fmoralesc** [comment]
I think I didn't consider the `:tab` command, so some code paths might not be covered in the original patches (I remember the points where tabs are created are all over the place); my bad. I might take a look at it later, but I'm a bit busy with other things atm.

**Comment by justinmk** [comment]
@fmoralesc no worries I just wanted to check that this was not intentional

**Comment by fmoralesc** [comment]
I will have to check what is going on to be sure (perhaps the `:tab` command itself is doing something weird), but I'm pretty sure it was an oversight.

**Comment by HarmtH** [comment]
I found another, Ctrl-W + T also doesn't trigger the autocmd's.

**Comment by justinmk** [comment]
Probably the same codepath. Thanks for the report!

**Comment by HarmtH** [comment]
TabNewEntered still isn't triggered on a ```:tab split```, although TabNew is. This bug report shouldn't be closed yet.

**Comment by dmerejkowsky** [comment]
Can confirm the bug is still here for `:tab split`

I have an other failing test to prove it here:
dmerejkowsky/neovim@4313e1b08ea724f8524ebfa92879726797135e06
