### ISSUE TITLE
Zero width control characters insert spaces with shell ex commands

### ISSUE THREAD

**Issue by atommclain** [neovim/neovim#4338]
- Neovim version: 9a3b7fa90
- Operating system: Gentoo 2.2
- Terminal emulator: iTerm 2.1.1 (connected to remote system)

Discovered while researching https://github.com/neovim/neovim/issues/4142 and https://github.com/neovim/neovim/issues/2958

Running a shell command that echoes multiple bell symbols followed by text shifts text to the right.
### Actual behaviour

Text preceded by zero width control bell character is shifted to the right.
### Expected behaviour

Text should start in the first column.
### Steps to reproduce

```
nvim -u NONE
:!echo -en '\x07\x07\x07\x07text'
// prints
    text
// instead of
text
```

vim 7.4.769 with same configuration exhibits expected behavior

**Comment by justinmk** [comment]
#7844 outputs bell chars as `^G`. 

```
:!echo -en '\x07\x07\x07\x07text'
^G^G^G^Gtext
```

This is a design decision.

**Comment by bfredl** [comment]
The only design decision in #7488 is that we actually can determine what happens on each control char. We could easily change it emit bell, just add it to the list of bytes sent directly to msg_putc (just as ^M was changed)

**Comment by justinmk** [comment]
Would that work for other control codes like colors? Currently colors are rendered as `hl-SpecialChar`.  E.g. `:!bash -i`:

    ^[[0;30m^[[47mSSH^[[0m ^[[0;32mjustin@foo ^[[36m~/foo^[[0m^[[0;33m (test u=)^[[0m

**Comment by bfredl** [comment]
It is a question of effort. Supporting bell is a trivial one-line change (message.c already supports it, we just need to ask it, so we could just as well do it now, while colors requires implementing or integrating a ANSI control code parser. And the such parser we should  (eventually) integrate is `:terminal`.
