### ISSUE TITLE
function keys in neovim terminals

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4343]
- Neovim version:

```
NVIM v0.1.3-229-g8160e87
Build type: Dev
```

I'm on OSX with iTerm2.
### Actual behaviour

Function keys in neovim terminals aren't translated correctly.
The bytes sent are 

```
[253 191 191 188 186 149]
[253 191 191 188 182 149]
[253 191 191 188 178 149]
[253 191 191 188 174 149]
[253 191 191 188 170 149]
[253 191 191 188 166 149]
[253 191 191 188 162 149]
[253 191 191 188 158 149]
[253 191 191 188 154 149]
[253 191 191 188 146 149]
[253 191 191 188 182 186]
```

F1-F10 and then the last one is F12
### Expected behaviour

They should be translated as so.

```
[27 79 80]
[27 79 81]
[27 79 82]
[27 79 83]
[27 91 49 53 126]
[27 91 49 55 126]
[27 91 49 56 126]
[27 91 49 57 126]
[27 91 50 48 126]
[27 91 50 49 126]
[27 91 50 52 126]
```

F1-F10 and then the last one is F12
### Steps to reproduce
1. `nvim -u NONE`
2. `:term htop`
3. None of the function keys will do anything because htop won't recognize them.

@justinmk suggested using the demo program for libtermkey
I got the following output
https://gist.github.com/nhooyr/6967365f16a7052cf9e3

Seems normal.

Then @justinmk also suggested reverting #3982, but that didn't fix it either.

**Comment by justinmk** [comment]
Thanks for the great report! I don't think this is a priority for 0.2 but PRs are welcome.

**Comment by nhooyr** [comment]
I'll look into it when I have time.

**Comment by nhooyr** [comment]
I went back to the first first commit where terminal mode was introduced, still wouldn't work.

**Comment by rjmill** [comment]
I think I have a mostly working solution for this. Converting vim's `K_F*` keys to VTerm keycodes using VTERM_KEY_FUNCTION(n) has F5-F12 working pretty well. F1-F4 produce letters P-S along with some newlines.

Interestingly enough, htop seems to recognize and accept all the function keys (even F1-F4) and work as expected.

I'll open a [WIP] pull request for this and start working on a fully working solution.

**Comment by rjmill** [comment]
More info:
I've discovered where the P-S characters are coming from using this script:
 `for x in {1..12}; do; echo -n "F$x "; tput kf$x | cat -A; echo; done`

**output in rxvt-unicode**
```
F1 ^[[11~
F2 ^[[12~
F3 ^[[13~
F4 ^[[14~
F5 ^[[15~
F6 ^[[17~
F7 ^[[18~
F8 ^[[19~
F9 ^[[20~
F10 ^[[21~
F11 ^[[23~
F12 ^[[24~
```

**output in nvim's terminal**
```
F1 ^[OP
F2 ^[OQ
F3 ^[OR
F4 ^[OS
F5 ^[[15~
F6 ^[[17~
F7 ^[[18~
F8 ^[[19~
F9 ^[[20~
F10 ^[[21~
F11 ^[[23~
F12 ^[[24~
```

Also worth noting that not only does this fix work fine in htop, but it also works fine in bash. The extra characters being output might just be a problem with zsh not handling libvterm's different keycodes properly and have nothing to do with nvim. (It could also be something with oh-my-zsh. I'll look into that too.)

**Comment by rjmill** [comment]
Scratch all that. Tested this in gnome-terminal, and it exhibits the same wonky behavior as nvim's terminal.

Also, for anyone dealing with similar issues with function keys in the future, this is a good read: http://aperiodic.net/phil/archives/Geekery/term-function-keys.html 
(The takeaway in this case is to expect nvim's terminal to function more like gnome-terminal or xterm than urxvt.)
