### ISSUE TITLE
Where to put the _nvimrc?

### ISSUE THREAD

**Issue by kdurant** [neovim/neovim#4345]
- Neovim version:  0.1.3-dev
- Operating system: Win10
- Terminal emulator:

Where to put the _nvimrc?  $HOME that vim used or $XDG_CONFIG_HOME?

PS: Nvim syntax highlighting is enabled by default，But my Nvim syntax highlighting is unenabled

**Comment by brcolow** [comment]
https://neovim.io/doc/user/nvim_from_vim.html

**Comment by mhinz** [comment]
The path can be found here: https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L25-L27

:arrow_right: `~/AppData/Local/nvim/init.vim`

**Comment by wsdjeg** [comment]
> ~/AppData/Local/nvim/init.vim

he has tried with this,but not work ,because in his nvim, `echo expand('~') show E:\home`

**Comment by mhinz** [comment]
@wsdjeg Try `~/AppData/Local/nvim/config/nvim/init.vim`.

**Comment by wsdjeg** [comment]
@kdurant  I think the best way to fix this issue ,you should do like this
open neovim,now your neovim shou has no init.vim
then use this command `:edit ~/AppData/Local/nvim/init.vim` or `:edit ~/AppData/Local/nvim/config/nvim/init.vim` just as @mhinz says

**Comment by kdurant** [comment]
@mhinz @wsdjeg     I try ` ~/AppData/Local/nvim/config/nvim/init.vim ` and `~/AppData/Local/nvim/config/nvim/init.vim `, but still not work.
init.vim only one statement `set number`

**Comment by mhinz** [comment]
Since you pasted the same path twice, yes, that's the correct one. ;]

Check `:scriptnames`. It lists all sourced files in order.

**Comment by kdurant** [comment]
@mhinz 
```
  1: E:\Neovim\share\nvim\runtime\plugin\gzip.vim
  2: E:\Neovim\share\nvim\runtime\plugin\man.vim
  3: E:\Neovim\share\nvim\runtime\plugin\matchit.vim
  4: E:\Neovim\share\nvim\runtime\plugin\matchparen.vim
  5: E:\Neovim\share\nvim\runtime\plugin\netrwPlugin.vim
  6: E:\Neovim\share\nvim\runtime\plugin\rplugin.vim
  7: E:\Neovim\share\nvim\runtime\autoload\remote\host.vim
  8: E:\Neovim\share\nvim\runtime\plugin\rrhelper.vim
  9: E:\Neovim\share\nvim\runtime\plugin\shada.vim
 10: E:\Neovim\share\nvim\runtime\plugin\spellfile.vim
 11: E:\Neovim\share\nvim\runtime\plugin\tarPlugin.vim
 12: E:\Neovim\share\nvim\runtime\plugin\tohtml.vim
 13: E:\Neovim\share\nvim\runtime\plugin\tutor.vim
 14: E:\Neovim\share\nvim\runtime\plugin\vimballPlugin.vim
 15: E:\Neovim\share\nvim\runtime\plugin\zipPlugin.vim
 16: E:\Neovim\share\nvim\runtime\autoload\provider\clipboard.vim
```

**Comment by fwalch** [comment]
According to [this](https://github.com/neovim/neovim/wiki/Installing-Neovim#vimrc-file-in-windows), it should be just %userprofile%\AppData\Local\nvim\init.vim?

**Comment by mhinz** [comment]
@fwalch Hmm, I think it can't be right according to https://github.com/neovim/neovim/blob/master/src/nvim/os/stdpaths.c#L25

@kdurant If you put your `init.vim` into `E:\Neovim\share\nvim\runtime\plugin` it will just get loaded as a normal plugin, but doesn't count as a real vimrc which gets loaded as first script. I'm no Windows user, and we're not officially supporting Windows yet, but quite a lot of users use Neovim on Windows already.

Code doesn't like, so it should be `%LOCALAPPDATA%\nvim\config\nvim\init.vim`. Maybe `%LOCALAPPDATA` is not `E:\Users\you\AppData\Local` for some reason? Can you expand `%LOCALAPPDATA` in `cmd.exe` or powershell, just to be sure?

**Comment by equalsraf** [comment]
If you are building/running from #810 It should be %LOCALAPPDATA%/nvim/init.vim 

@kdurant can you check in Neovim what is the output of the following commands?

- `:echo $LOCALAPPDATA`
- `:echo $APPDATA`
- `:echo $MYVIMRC`

@mhinz in master/stdpaths.c the path is indeed nvim/config (but this was changed because nvim was then append to the path so nvim/config/nvim), see https://github.com/equalsraf/neovim/commit/9f9c2e65852271b3a5ca58046826b44b1ec6d8a6

**Comment by mhinz** [comment]
@equalsraf Hmm, I thought that was done on purpose, to avoid having both, XDG home and data, in the same directory (`%LOCALAPPDATA%`). But then again, Windows support is your metier and you're doing a great job. :+1:

**Comment by equalsraf** [comment]
@mhinz you are not wrong its actually that:

- Configuration files are saved under %LOCALAPPDATA%\nvim
- Data files are saved under %LOCALAPPDATA%\nvim-data
