### ISSUE TITLE
How to setup tern_for_vim ?

### ISSUE THREAD

**Issue by neovimuser** [neovim/neovim#4347]
Forst of all: I'm a beginner.

- Neovim version: NVIM 0.1.3-dev
- Operating system: Ubuntu 15.10
- Terminal emulator: 3.16.2

### Actual behaviour
https://github.com/ternjs/tern_for_vim not working.

### Expected behaviour
https://github.com/ternjs/tern_for_vim working. 

### Steps to reproduce
0. From https://github.com/neovim/neovim/wiki/Installing-Neovim I chose ppa:neovim-ppa/unstable.
1. Then I installed nodejs using https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions ("... /setup_4.x | ...") and the down below "build-essential"
2. https://github.com/ternjs/tern_for_vim says at the bottom to add "tern#is_show_argument_hints_enabled" but I'm not sure how it has to look like. I added "let g:tern#is_show_argument_hints_enabled = 1" to my ~/.config/nvim/init.vim but tern for vim is not working.
I didn't use any package manager like the description says ("If you use Pathogen or something similar, ...") but just extracted https://github.com/ternjs/tern_for_vim/archive/master.zip to their belonging vim folder structure in ~/.config/nvim/*.
Also, some installing tutorials say one needs YouCompleteMe for tern_for_vim. Do I need it for tern_for_vim to work? 

Has anyone please a small setup guide how to setup tern_for_vim (preferably without any package manager or additionally needed plugins, if there's a way)?

**Comment by mhinz** [comment]
This issue tracker is usually about Neovim development, not user problems (especially since it also applies to Vim.) Closing.

---

Anyway, did you run `npm install` in `~/.config/nvim` as the [README](https://github.com/ternjs/tern_for_vim#manual) suggests? Is `node` a global executable?

**Comment by carlitux** [comment]
@neovimuser also don't forget do 'npm install' inside tern_for_vim directory, add the .eslintrc to the project directory.

**Comment by neovimuser** [comment]
Yes I did run:
:~/.config/nvim$ npm install
npm WARN package.json tern_for_vim@0.5.0 No README data
tern@0.17.0 node_modules/tern
├── acorn@2.7.0
├── typescript@1.0.1
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── enhanced-resolve@0.9.1 (graceful-fs@4.1.3, tapable@0.1.10, memory-fs@0.2.0)
└── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
$

**Comment by carlitux** [comment]
looks like you did wrong 

```bash
ls .config/nvim
UltiSnips bundle    init.vim
```

plugins goes inside 
```bash
ls .config/nvim/bundle
MatchTag                        flux.vim                        tagbar                          vim-css-color                   vim-jsx                         vim-repeat
NeoBundle.lock                  gitv                            tcomment_vim                    vim-css3-syntax                 vim-less                        vim-scriptease
NrrwRgn                         gundo.vim                       tern_for_vim                    vim-easymotion                  vim-localvimrc                  vim-snippets
PreserveNoEOL                   html5.vim                       typescript-vim                  vim-easytags                    vim-markdown                    vim-speeddating
ZoomWin                         javascript-libraries-syntax.vim ultisnips                       vim-endwise                     vim-minimap                     vim-startify
ack.vim                         neobundle.vim                   unite-tag                       vim-expand-region               vim-misc                        vim-stylus
auto-pairs                      neoinclude.vim                  unite.vim                       vim-fetch                       vim-multiple-cursors            vim-surround
base16-vim                      neomru.vim                      vim-abolish                     vim-fugitive                    vim-mustache-handlebars         vim-tmux-navigator
dash.vim                        nerdtree                        vim-airline                     vim-gitgutter                   vim-node                        vim-virtualenv
deoplete-jedi                   scss-syntax.vim                 vim-airline-themes              vim-jade                        vim-obsession                   vim-visual-star-search
deoplete.nvim                   searchtasks.vim                 vim-bufkill                     vim-javascript                  vim-octave                      vimproc.vim
editorconfig-vim                syntastic                       vim-bundler                     vim-jsbeautify                  vim-rails
emmet-vim                       tabular                         vim-coffee-script               vim-json                        vim-relativity
```

**Comment by neovimuser** [comment]
Ok, now I did it how suggested:
:~/.config/nvim/bundle/tern_for_vim$ npm install
npm WARN prefer global typescript@1.0.1 should be installed with -g
tern_for_vim@0.5.0 /home/test/.config/nvim/bundle/tern_for_vim
└─┬ tern@0.17.0 
  ├── acorn@2.7.0 
  ├─┬ enhanced-resolve@0.9.1 
  │ ├── graceful-fs@4.1.3 
  │ ├── memory-fs@0.2.0 
  │ └── tapable@0.1.10 
  ├─┬ glob@3.2.11 
  │ ├── inherits@2.0.1 
  │ └── minimatch@0.3.0 
  ├─┬ minimatch@0.2.14 
  │ ├── lru-cache@2.7.3 
  │ └── sigmund@1.0.1 
  └── typescript@1.0.1 
$

**Comment by mhinz** [comment]
@carlitux `bundle` is nothing Vim knows about. It's just a common convention used by plugin managers (which he doesn't use).

**Comment by neovimuser** [comment]
I think so but if I put it out of bundle and put it in plugin and $ npm install again, there's no output (maybe because I have already installed it?):
:~/.config/nvim/plugin/tern_for_vim$ npm install
$

**Comment by carlitux** [comment]
@mhinz yeah I thought that, but at least his path should be ~/.config/nvim/tern_for_vim. ?

**Comment by carlitux** [comment]
@neovimuser use omnicomplete just fire the feature in nvim when javascript file is loaded in buffer. If still not working run :messages to see the logs.

**Comment by neovimuser** [comment]
Is omnicomplete the same as tern_for_vim where I can see all the available methods, not only the ones that are used in a file?

**Comment by carlitux** [comment]
I saw it as a hook to get the autocomplete data (maybe someone else could explain the real concept)... tern_for_vim provides that data. See :messages sometimes .eslintrc has errors and don't works.

**Comment by neovimuser** [comment]
Ok, I'll have to see how to get tern_for_vim running.. but so far, tern_for_vim doesn't need YouCompleteMe, right?

**Comment by carlitux** [comment]
No, it doesn't need.

**Comment by carlitux** [comment]
@neovimuser if you like neovim you can start using https://github.com/Shougo/deoplete.nvim and I put the sources for ternjs https://github.com/carlitux/deoplete-ternjs... this work faster with async feature.
