### ISSUE TITLE
Resizing GNOME Terminal window with keyboard shortcuts doesn't resize neovim.

### ISSUE THREAD

**Issue by drzel** [neovim/neovim#4354]
- Neovim version: NVIM 0.1.3-dev
- Operating system: Linux (Ubuntu 15.10)
- Terminal emulator: GNOME Terminal 3.16.2

### Actual behaviour
Resizing with keyboard shortcuts doesn't redraw screen. Dragging screen with mouse works fine.

### Expected behaviour
Screen should be redrawn either way.

### Steps to reproduce
Open nvim in gnome-terminal, go fullscreen (F11) or maximise (Ctrl + Super + Up), vim doesn't resize. Intermittently works as expected for some reason.

**Comment by wsdjeg** [comment]
https://github.com/neovim/neovim/issues/3929
###Duplication

**Comment by wsdjeg** [comment]
same environment as me ,and you can use `:mode` command,map it before this issue be fixed
