### ISSUE TITLE
E685: internal error: get_tv_string_buf()

### ISSUE THREAD

**Issue by iamcco** [neovim/neovim#4355]
- Neovim version: NVIM 0.1.3-dev Build type: RelWithDebInfo
- Operating system: Ubuntu15.10
- Terminal emulator: gnome-termianl v3.16.2

### Actual behaviour
E685: internal error: get_tv_string_buf()

### Steps to reproduce

viml
```
:call setloclist(0, [])
```

**Comment by wsdjeg** [comment]
you should update neovim ,I report this bug yesterday via gitter, it has been fixed by 
https://github.com/neovim/neovim/commit/b6170db1a1c6cec55b0cd0075b54b8370650aa14
