### ISSUE TITLE
ShaDa: marks for recent cursor positions not set

### ISSUE THREAD

**Issue by badeip** [neovim/neovim#4360]
- Neovim version: NVIM v0.1.3-244-g3e0fab6 (Sat Feb 27 16:42:53 2016)
- Operating system: Linux
- Terminal emulator: iTerm2

### Actual behaviour
E20: Mark not set

### Expected behaviour
Open of file associated with previous cursor position
(this works as expected in vanilla vim)

from `:h marks`
...
Numbered marks '0 to '9 are quite different.  They can not be set directly.
They are only present when using a viminfo file viminfo-file.  Basically '0
is the location of the cursor when you last exited Vim, '1 the last but one
time, etc.  Use the "r" flag in 'viminfo' to specify files for which no
Numbered mark should be stored.  See viminfo-file-marks.

### Steps to reproduce
open file
quit nvim
start nvim
press '0

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/issues/3472

Unfortunately, no one has been able to narrow down the conditions that cause this. I can't reproduce it.

**Comment by watiko** [comment]
I can reproduce it.

* Nvim: master
* OS: Ubuntu 15.10
* Term: Gnome Terminal 3.16.2

```
cd /tmp
mkdir shada && cd $_

echo "a\nb\nc" > test
nvim -u NONE -i test.shada test -c q
nvim -u NONE -i test.shada test -c "normal '0"
```

`nvim test.shada`
```
Header with timestamp 2016-02-28T08:56:35:
  % Key______  Value
  + encoding   "utf-8"
  + generator  "nvim"
  + max_kbyte  10
  + pid        15856
  + version    "NVIM v0.1.3-246-gba1348e"
Jump with timestamp 2016-02-28T08:56:23:
  % Key  Description  Value
  + f    file name    "/tmp/shada/test"
  + l    line number  1
  + c    column       0
Jump with timestamp 2016-02-28T08:56:33:
  % Key  Description  Value
  + f    file name    "/tmp/shada/test"
  + l    line number  1
  + c    column       0
Replacement string with timestamp 1970-01-01T09:00:00:
  @ Description__________  Value
  - :s replacement string  ""
Local mark with timestamp 2016-02-28T08:56:35:
  % Key  Description  Value
  + f    file name    "/tmp/shada/test"
  + n    name         '"'
  + l    line number  1
  + c    column       0
History entry with timestamp 2016-02-28T08:56:35:
  @ Description_  Value
  - history type  CMD
  - contents      "qa"
```

**Comment by nschloe** [comment]
I can confirm that this reproduces the error.

**Comment by jdbytes** [comment]
I am having the issue. It's been almost a year since this was reported.  Has anybody found a workaround?

**Comment by wreed4** [comment]
I also see this.  Nvim 0.2.2, shada=!,'100,<50,s10,h

**Comment by nschloe** [comment]
@wreed4 Check out [this thread](https://github.com/neovim/neovim/issues/3472) – I had been dealing with the wrong config file all along. Perhaps that fixes the issue for you as well.

**Comment by wreed4** [comment]
@nschloe oh, no I'm definitely reading the right config file.  Plus I'm not setting my shada to anything anyways.  But i'm loading quite a few plugins/colorschemes/etc. definitely hitting the right config.  ~/.config/nvim/init.vim is symlinked to ~/.vim/vimrc

**Comment by wreed4** [comment]
I'm not actually trying to do anything that requires a config file though.. supposedly, these marks will be set by default. so launching with `nvim -u NONE`, I edit a file, jump to a line, quit.  Then `nvim -u NONE` and `:marks`... nothing. I DO see `'A` which I set previously though.. just not 0-9...
