### ISSUE TITLE
Support for invoking `nvim -R` as `view`

### ISSUE THREAD

**Issue by amiryal** [neovim/neovim#4366]
When invoked as `view`, Vim normally switches to read-only mode, as if invoked as `vim -R`.

### Actual behaviour
- Neovim version: `NVIM 0.1.3-dev`
- Operating system: Debian-based Linux

When the `view` executable is a symlink to `nvim`, invoking it simply starts Neovim with no special behaviour.

### Steps to reproduce
```
sudo update-alternatives --install /usr/bin/view view /usr/bin/nvim 60
sudo update-alternatives --config view  # choose nvim
view /some/writeable/file
```

**Comment by fwalch** [comment]
This has  been removed by https://github.com/neovim/neovim/pull/2008.

**Comment by amiryal** [comment]
Ok, edited the [Wiki page](https://github.com/neovim/neovim/wiki/Installing-Neovim) accordingly, but still wondering, if Neovim is to be a drop-in replacement, why it wouldn’t implement all of Vim’s interfaces that a user might expect.

**Comment by justinmk** [comment]
> why it wouldn’t implement all of Vim’s interfaces that a user might expect.

It does implement `-R`. The reason for removing the "view" alias magic is given in the linked issues: it is totally pointless.
