### ISSUE TITLE
pip install neovim wrong

### ISSUE THREAD

**Issue by whdxwym** [neovim/neovim#4368]
- Neovim version:0.1.3-dev
- Operating system:debian jessie
- Terminal emulator:gnome-terminal
### Actual behaviour

```
!!! WARNING !!! The Trollius project is now deprecated!
```

。。。
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

**Comment by wsdjeg** [comment]
what command did you use?

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/blob/master/stack/linux.md
```
Q:how to install neovim in ubuntu? A:

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
sudo apt-get install python python3 python-dev python3-dev python-pip python3-pip
pip2 install --user neovim
pip3 install --user neovim
```

**Comment by bfredl** [comment]
You don't get a traceback or anymore output than `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)` ?

What are the full steps to reproduce?
