### ISSUE TITLE
Syntax dissapears when switching to set background=dark

### ISSUE THREAD

**Issue by mtglsk** [neovim/neovim#4372]
- Neovim version: 0.1.3-dev
- Operating system: ubuntu 16.04
- Terminal emulator: xterm

### Actual behaviour

Syntax highlighting dissapears

### Expected behaviour

Syntax should be shown.

### Steps to reproduce

Open some file. Then `:h nvim-from-vim` followed by `:set background=dark`. Syntax highlight is gone. Thats how it triggers for me.

**Comment by justinmk** [comment]
This is standard Vim behavior. It also varies per colorscheme logic.

**Comment by mtglsk** [comment]
Only happens in xterm (maybe the whole 24bit approximation it does causes it). Libvte seems to render ok.

**Comment by justinmk** [comment]
Terminal is not relevant. It's a function of your colorscheme. Try a different colorscheme.
