### ISSUE TITLE
Disabling alternate_screen doesn't work

### ISSUE THREAD

**Issue by netei** [neovim/neovim#4381]
- Neovim version:  v0.1.2-369-g50393ef
- Operating system: Red Hat Enterprise Linux Server release 6.6 (Santiago)
- Terminal emulator: Putty
- tmux version : master v2.2, e9d369a09e48ea8f940958025c8444988d31e840

### Actual behaviour

When closing neovim after setting `set t_ti= t_te=`, the buffer is not showed to the screen

### Expected behaviour

When closing neovim after setting `set t_ti= t_te=`, the shown text should be shown to the terminal.

### Steps to reproduce

Under tmux (with an empty ~/.tmux.conf), version 2.1

run
 
    nvim -u NONE

Inside nvim 

    :set t_ti= t_te=
    :q!

With vim (VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 24 2015 09:42:24), the closed buffer is still on the output of the terminal.

Strangely, this doesn't happen when outside of tmux (eg both vim and neovim handle it properly)

**Comment by tarruda** [comment]
> Strangely, this doesn't happen when outside of tmux (eg both vim and neovim handle it properly)

This is really strange, considering nvim removed t_* options some time ago

**Comment by mhinz** [comment]
All the `t_*` options are no-ops at the moment, since Neovim works quite different in the respect now. It's planned to re-add them in some form later on, though.

**Comment by netei** [comment]
> > Strangely, this doesn't happen when outside of tmux (eg both vim and neovim handle it properly)

> This is really strange, considering nvim removed t_* options some time ago

I just tested without tmux, and without running the commands, and it still works (so it works even without `t_ti` and `t_te`. 

TERM is : 

    echo "$TERM"
    screen-256color

I guess my default terminal doesn't support alternate screens

**Comment by netei** [comment]
> All the t_* options are no-ops at the moment

Maybe it would be good to remove them from the helpfiles then ? And maybe also echo a warning when you set them ?

**Comment by justinmk** [comment]
> Maybe it would be good to remove them from the helpfiles then ?

I think we intend to restore them, though.

This issue is covered by https://github.com/neovim/neovim/issues/3432 , so closing.
