### ISSUE TITLE
failed to load python host when executing nvim from certain paths

### ISSUE THREAD

**Issue by namanbharadwaj** [neovim/neovim#4383]
- Neovim version: 0.1.3-dev
- Operating system: Ubuntu 14.04 LTS
- Terminal emulator: gnome-terminal

### Actual behaviour
nvim fails to start cleanly (python host issue) if I start it from a deeper path, but going up a directory causes everything to work correctly:

```
$ pwd
/home/naman/clear/projects/all-the-things/traintrack/affirm/traintrack

$ nvim dbsession.py
# function jedi#init_python[3]..<SNR>53_init_python[31]..jedi#force_py_version[2]..jedi#setup_py_version[14]..provider#python#Call[9]..remote#host#Require[10]..<SNR>42_RequirePythonHost, line 15
# Vim(if):Channel was closed by the client
# Failed to load python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.

$ cd ../
$ nvim traintrack/dbsession.py
# everything works as normal
```

I attempted to set `NVIM_PYTHON_LOG_FILE=/home/naman/nvim-log nvim dbsession.py`, but it doesn't seem to have any effect.

### Expected behaviour
Obviously, nvim should behave similarly no matter where you start it from.

### Steps to reproduce
Provided above.

**Comment by bfredl** [comment]
is the log file empty? what happens if you do `python -c "import neovim"` at this path?

**Comment by namanbharadwaj** [comment]
@bfredl thanks, I didn't think to try that, but `python -c "import neovim"` makes the problem obvious.

It's to do with the fact that the neovim `__init__.py` does `import logging`, which resolves to a relative import when there's a `logging.py` in the current directory. Closing.

**Comment by bfredl** [comment]
> It's to do with the fact that the neovim __init__.py does import logging, which resolves to a relative import when there's a logging.py in the current directory.

sounds like a bug. Thanks for reporting.

**Comment by namanbharadwaj** [comment]
btw, I think this can be fixed with a `from __future__ import absolute_import` at the top of `neovim/__init__.py`, but I'm not sure how portable that is.

**Comment by bfredl** [comment]
`absolute_import` is in python2.6 so it should be fine :+1:
