### ISSUE TITLE
viml -> python -> thread => error

### ISSUE THREAD

**Issue by tex** [neovim/neovim#4385]
- Neovim version:

NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.2/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Operating system:

ArchLinux

- Terminal emulator:

URXVT

### Actual behaviour

https://github.com/tex/vimpreviewpandoc/issues/4

```
Exception in thread Thread-1:                                                         
Traceback (most recent call last):                                                    
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner              
    self.run()                                                                        
  File "<string>", line 199, in run                                                   
  File "<string>", line 183, in pandoc                                                
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 160, in write 
    self.redirect_handler(data)                                                       
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 58, in <lambda
>                                                                                     
    sys.stderr = RedirectStream(lambda data: nvim.err_write(data))                    
  File "/usr/lib/python2.7/site-packages/neovim/api/nvim.py", line 209, in err_write  
    return self._session.request('vim_err_write', msg)                                
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 230, in request  
    return walk(self._in, self._session.request(name, *args, **kwargs),               
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 81, in r
equest                                                                                
    v = self._yielding_request(method, args)                                          
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 146, in 
_yielding_request                                                                     
    return parent.switch()                                                            
AttributeError: 'NoneType' object has no attribute 'switch'                           
```

Neovim is broken afterwards: trying to open a plain fail causes these errors:

```
line   18:                                                                            
Invalid channel "1"                                                                   
Error detected while processing function <SNR>171_OnBufferVisit..provider#python#Call:
                                                                                      
line   18:                                                                            
Invalid channel "1"                                                                   
Error detected while processing function <SNR>171_OnBufferVisit..<SNR>171_OnFileReadyT
oParse..provider#python#Call:                                                         
line   18:                                                                            
Invalid channel "1"                                                                   
Invalid channel "1"                                                                   
```

### Expected behaviour

No error

### Steps to reproduce

Install https://github.com/tex/vimpreviewpandoc plugin, open konqueror, open .md (markdown) in neovim.

**Comment by bfredl** [comment]
I don't think writing to stderr is safe in a thread in vim as well, rather this exception is probably hiding the "real" exception. Or maybe it worked by accident in vim as stderr was empty?

**Comment by tex** [comment]
Can you please explain in a detail what do you mean? I'm not very experienced in writting vim plugins - this is my first - basically I want to execute application (pandoc) in such way that it doesn't block vim/neovim. Nothing is required to be returned back to vim.
Thanks!

**Comment by fmoralesc** [comment]
@tex Hi there! I'm the maintainer of the vim-pandoc plugin, which uses job control in nvim for this, perhaps take a look at my implementation.

**Comment by tex** [comment]
Thanks @fmoralesc ! I'll look at your implementation.

**Comment by tex** [comment]
Can you point me where exactly should look at please?

**Comment by fmoralesc** [comment]
Sorry, sure: vim-pandoc builds the pandoc invocation first and then passes it to nvim as a job, see here: https://github.com/vim-pandoc/vim-pandoc/blob/master/pythonx/vim_pandoc/command.py#L265-L274

**Comment by bfredl** [comment]
I meant the error in the topmost post is because another thread tries to write to stderr, which is not allowed at least not in neovim. I  looked in vim's `if_py_both.py` which looks like it has some threading logic but I don't know what to say about this
```
/*
 * obtain a lock on the Vim data structures
 */
    static void
Python_Lock_Vim(void)
{
}

/*
 * release a lock on the Vim data structures
 */
    static void
Python_Release_Vim(void)
{
}
```
(from `vim/src/if_py_both.h`, not neovim)

**Comment by tex** [comment]
Thanks for your help and guidance! I fixed the problem.

**Comment by fmoralesc** [comment]
@tex Great! Cool plugin btw ;)
