### ISSUE TITLE
Mouse selection issues in :term

### ISSUE THREAD

**Issue by kurkale6ka** [neovim/neovim#4391]
- Neovim version: NVIM v0.1.3-293-g576c5f7
- Operating system: Arch Linux
- Terminal emulator: xfce4-terminal 0.6.3
### Actual behaviour

with :set mouse=a, I am unable to select more than a few characters at a time
### Expected behaviour

Freely select text with mouse
### Steps to reproduce
- nvim
- :term
- nvim (so nvim within nvim). Now write at least 5/6 lines of text and try to select with mouse

Relates to: https://bugs.launchpad.net/pangoterm/+bug/1516727

**Comment by mhinz** [comment]
Hmm, and this only happens in terminal buffers?

**Comment by kurkale6ka** [comment]
Only in terminal buffers yes (nvim/:term/nvim).
In fact I was in tmux but I just tested outside and the behaviour is the same

**Comment by justinmk** [comment]
Cannot reproduce with Nvim 0.3.2. Tested with all combinations of `set mouse=` and `set mouse=a` in the parent and child Nvims.
