### ISSUE TITLE
Workaround gnome-terminal cursor changing bug

### ISSUE THREAD

**Issue by egmontkob** [neovim/neovim#4395]
- Neovim version: v0.1.3-293-g576c5f7
- Operating system: Ubuntu Xenial beta
- Terminal emulator: vte/gnome-terminal

As pointed out at https://bugzilla.gnome.org/show_bug.cgi?id=762963, gnome-terminal (and other VTE based terminals) don't immediately change the cursor shape when neovim changes from insert to command mode or vice versa.

I just fixed this simple bug in VTE git, and will be released in the 0.42.5 and 0.44.0 tarballs.

In the mean time, neovim could probably come up with a workaround for older VTE versions.

I believe that if changing the cursor shape doesn't happen in the middle of a long series of emitted escape sequences and normal text, but rather at the very beginning or very end of the series, then the bug is not triggered. Also if you flush the output right after emitting the cursor changing sequence and make a small pause then it shouldn't occur either.

Up to you whether it's worth it...

**Comment by fmoralesc** [comment]
Thanks for the info, @egmontkob

**Comment by megalithic** [comment]
also seeing the issue in iterm2-nightly (20160314), and latest neovim (NVIM v0.1.3-348-ge7a9c00) running inside tmux 2.1 on osx 10.10.5.

**Comment by egmontkob** [comment]
The fix (vte-0.42.5) has arrived to Ubuntu Xenial beta, which will be a 5-year support distro.

This decreases the usefulness of any workaround. If I was a neovim developer, I'd probably focus on other issues and close this one as wontfix :-D

**Comment by fmoralesc** [comment]
Agreed.
