### ISSUE TITLE
Searching using `/` from a vimscript function does not highlight

### ISSUE THREAD

**Issue by still-dreaming-1** [neovim/neovim#4397]
- Neovim version: 0.1.3-dev
- Operating system: Linux Mint 17.3 64 bit Cinnamon
- Terminal emulator: GNOME Terminal 3.6.2

### Actual behaviour
Searches without highlighting or replacing last search
### Expected behaviour
Normal Vim `/` search which searches, highlights, and replaces last search
### Steps to reproduce
With this in your config:
```
function! MyFunction()
    execute "normal! /foo\<enter>"
endfunction
```
Enter this command: `:call MyFunction()`

**Comment by mhinz** [comment]
It's the same in Vim. Use `:normal! /foo^M` instead. `^M` is entered via `<c-v><c-m>`.

See: http://vim.wikia.com/wiki/Using_normal_command_in_a_script_for_searching

**Comment by still-dreaming-1** [comment]
@mhinz Sorry I realized my mistake after posting, I am editing it for an actual problem hopefully

**Comment by still-dreaming-1** [comment]
Done editing now. I have tested exactly what is entered here. Hehe...

**Comment by mhinz** [comment]
I think that's related to `:h function-search-undo`.

**Comment by mhinz** [comment]
A possible workaround would be something like:

```vim
function! s:test(query)
  execute 'normal! /'. a:query ."\<cr>"
  let @/ = a:query
endfunction

command! Test call s:test('foo')
```

In this case the `execute 'normal! ..'` can also be replaced by the `:h search()` function.

**Comment by still-dreaming-1** [comment]
@marvim  Thank you! That is exactly the relevant section in the help which also reveals this is very intentional. The workaround you provided is great! `let @/ = a:query` is the key! I ended up using that in conjuntion with `normal! n` to achieve what I needed.

**Comment by still-dreaming-1** [comment]
Actually that workaround is not working as well as I thought. It still does not highlight the search unless the user had already searched on something. So if you load up a fresh Neovim and try it, it does not highlight the search :( Any other ideas?

**Comment by justinmk** [comment]
Can you try http://vi.stackexchange.com/ ? Issue tracker is not for usage questions. Unless behavior is different in Vim this is not a bug.

**Comment by still-dreaming-1** [comment]
@justinmk Sorry yeah, I thougth it was a bug at first but your right.

**Comment by mhinz** [comment]
That, or come to our Gitter channel. :-)  (Hint: `command! Test set hlsearch | call s:test('foo')`)
