### ISSUE TITLE
provide "ModeChanged" event (and fix "mode()")

### ISSUE THREAD

**Issue by bsmith89** [neovim/neovim#4399]
Following in the footsteps of #4322, I'd like to ask about an autocmd event.

There are already "CmdwinEnter"  and "CmdwinLeave" events, but those are for the `q:` buffer, not the command line (i.e. `:`)

As a use case, I'd like to be able to toggle line numbering between relative and absolute when in normal mode versus on the command line.

**Comment by ZyX-I** [comment]
Why do you need such toggling? In ranges you may use `-` and `+` to refer to lines relative to cursor: `-1,+1p` will print cursor line and one line above and below.

**Comment by arecarn** [comment]
This might also be helpful for creating plugins that operate on visual blocks.

 I created the plugin [selection.vim](https://github.com/arecarn/selection.vim) that works around this this issue with some hacks, but having new autocmds would make doing something like this more idiomatic in vimscript

**Comment by arecarn** [comment]
Hmm maybe I'm even thinking about something different like CmdlineEnterPre so one could check if they were in visual mode before invoking a command.

**Comment by bfredl** [comment]
:+1: but I remember discussion on gitter if we should add `ModeChanged` instead of needing to define specific autocommands every mode.

Also we could either fix `mode()` to return `v` on `v:echo mode()<cr>` or add `realmode()` if that turns out to break existing plugins.

**Comment by justinmk** [comment]
> CmdlineEnterPre so one could check if they were in visual mode before invoking a command.


If `getcmdline()` starts with `'<,'>` then visual mode was present ;)

**Comment by bfredl** [comment]
It's hard to see that if you `<c-u>` as you often need to in a mapping.

**Comment by mtglsk** [comment]
I think the most obvious usage for this is toggling ignorecase / smartcase...

**Comment by arecarn** [comment]
If getcmdline() starts with '<,'> then visual mode         was present ;)

One could also enter in those marks manually once you enter the command line. 

Even if you entered from visual mode and used those marks. You would still have no information about from which visual mode you entered from which might be important if you wanted a command to operate on a visual block.

**Comment by ZyX-I** [comment]
@arecarn Which visual mode was used is accessible via `visualmode()`.

**Comment by arecarn** [comment]
@ZyX-I I guess I sort of forgot about that, but it's hard to act on something like that. since it is the last visual mode not the current one.

Like @bfredl  already mentioned, a better solution would be fixes to `mode()` or a new `realmode()` function.

**Comment by bfredl** [comment]
I was was wrong about `mode()`, `mode()` just does what it is asked for. The behavior is because when the command inside `vmap :<c-u>...<cr>` is executing, nvim has already completely left visual mode.

**Comment by ZyX-I** [comment]
@arecarn `realmode()` is not correct name, that should be `prevmode()`: `mode()` returns currently active mode always, it is not its fault that in many cases currently active is command mode. `visualmode()` behaviour is actually strange, I thought it should return latest mode: as if data for visualmode() is changed immediately when you *enter* mode and not when you *exit* it.

I do not see the help stating explicitly that behaviour, but given that it states explicitly that inside visual mode you should use `mode()` I guess Bram does know about this fault and does not consider it a bug.

**Comment by lilydjwg** [comment]
I'm considering fixing  #2325 then I see this. If we had ModeChanged events, we could implement expected X selection handling with an external program that sets the ownship when visual mode is activated, then handle over the selected text on paste requests.

**Comment by vimpostor** [comment]
FYI I am working on this right now.
The vim patch is already done at https://github.com/vim/vim/pull/8856

I will implement this for neovim too.

**Comment by clason** [comment]
> FYI I am working on this right now.
> The vim patch is already done at [vim/vim#8856](https://github.com/vim/vim/pull/8856)
> 
> I will implement this for neovim too.

Just to make sure: It's easier for us to port the vim patch when it's merged rather than have a parallel PR (if at all feasible) to link the two and avoid difficulties down the road with porting follow-up patches.

**Comment by vimpostor** [comment]
> Just to make sure: It's easier for us to port the vim patch when it's merged rather than have a parallel PR (if at all feasible) to link the two and avoid difficulties down the road with porting follow-up patches.

Sure no problem.
Should I port it when its merged, or don't you actually need my help with that, as that is part of your usual vim commit monitoring process?

**Comment by clason** [comment]
There's no such (automated) thing, unfortunately, so if you could port it, that'd be great! (You can use the `scripts/vim-patch.sh` to get the PR started, but it will require manual changes.)
