### ISSUE TITLE
ShaDa loading is slow than viminfo loading

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#4404]
- Neovim version:  0.1.3-dev
- Operating system: Manjaro Linux
- Terminal emulator: st

### Actual behaviour
ShaDa loading is slow than viminfo loading.

### Expected behaviour
More faster ShaDa loading.

### Steps to reproduce

`$ nvim --startuptime start.txt`
`$ vim --startuptime start.txt`

Compare the two results.

My results:

vim

```
017.531  000.653: loading plugins
017.572  000.041: loading packages
018.457  000.885: inits 3
018.819  000.362: reading viminfo
020.655  001.836: setup clipboard
020.673  000.018: setting raw mode
020.680  000.007: start termcap
020.702  000.022: clearing screen
021.014  000.312: opening buffers
021.075  000.061: BufEnter autocommands
021.077  000.002: editing files in windows
021.215  000.138: VimEnter autocommands
021.217  000.002: before starting main loop
022.134  000.917: first screen update
022.137  000.003: --- VIM STARTED ---

```

neovim

```
024.951  001.012: loading plugins
024.956  000.005: inits 3
037.335  012.378: reading ShaDa
038.254  000.919: clearing screen
038.577  000.323: opening buffers
038.681  000.104: BufEnter autocommands
038.687  000.006: editing files in windows
038.951  000.265: VimEnter autocommands
038.956  000.004: before starting main loop
047.134  008.179: first screen update
047.141  000.007: --- NVIM STARTED ---
```

0.362 (viminfo) vs 12.78 (ShaDa)

**Comment by ZyX-I** [comment]
This is absolutely nothing without viminfo and shada contents.

**Comment by justinmk** [comment]
@Shougo Are the contents of viminfo equivalent to the shada contents? If you delete, say, 50% of the shada file, how is the time for `reading ShaDa` affected?

**Comment by Shougo** [comment]
> @Shougo Are the contents of viminfo equivalent to the shada contents? If you delete, say, 50% of the shada file, how is the time for reading ShaDa affected?

The configuration is same.  Yes, I think the ShaDa file is different from the viminfo file.
But why ShaDa is 30x slower loading than viminfo?
I think 2x ~ 3x slower is no problem.
I think the ShaDa loading can be more faster.

**Comment by justinmk** [comment]
Merging with https://github.com/neovim/neovim/issues/4855 which has more details.
