### ISSUE TITLE
nvim after pip3 install neovim returns command not found -- no executable?

### ISSUE THREAD

**Issue by joshcho** [neovim/neovim#4405]
- Neovim version: 0.1.0 (I presume, haven't been able to open it yet.)
- Operating system: OS X 10.11.3
- Terminal emulator: iTerm2
- Pip3 version: 8.0.2

### Actual behaviour

Installed neovim with following commands as per instructions:
`brew install python3`
`pip3 install neovim`
Then I `nvim` or `neovim`, but returns `command not found`
`pip3 show neovim` returns `/usr/local/lib/python3.5/site-packages`

But at site-packages, I cannot run neovim. No executable? I tried `pip3 install virtualenv` and `virtualenv` worked on command line, and it runs the .py executable in the site-packages directory. So the PATH isn't the problem.

It must be something simple, but for the life of me I can't find the problem.

### Expected behaviour

`neovim` should work after `pip3 install neovim` and resetting zsh.

### Steps to reproduce

`brew install python3`
`pip3 install neovim`
`nvim` -> `No command found.`
??

## Additional Information

`echo $PATH` returns `/Users/chominist/.rvm/gems/ruby-2.1.4/bin:/Users/chominist/.rvm/gems/ruby-2.1.4@global/bin:/Users/chominist/.rvm/rubies/ruby-2.1.4/bin:/Users/chominist/.local/bin:.git/safe/../../bin:/Users/chominist/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/chominist/.cabal/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/texbin:/usr/bin/python:/Users/chominist/.rvm/bin:/Users/chominist/.cabal/bin/:/usr/local/lib/python3.5`
`echo $PYTHONPATH` returns empty.

This is for installing [Deoplete](https://github.com/Shougo/deoplete.nvim#requirements)

**Comment by wsdjeg** [comment]
please see the installtion in the wiki, `pip3 install neovim` is just a nvim-client for python, you need install neovim core project.

**Comment by wsdjeg** [comment]
see here 
https://github.com/neovim/homebrew-neovim/blob/master/README.md

**Comment by joshcho** [comment]
I brew uninstalled neovim before pip3 installing neovim, thinking latter would replace the former. Thanks!
