### ISSUE TITLE
Prompting for downloading en_us spell file

### ISSUE THREAD

**Issue by albertnetymk** [neovim/neovim#4406]
- Neovim version:
Ubuntu PPA: 	0.1.2ubuntu1+git201603021455+2346+17~ubuntu14.04.1 

- Operating system:
Ubuntu 14.04

- Terminal emulator:
xterm

### Actual behaviour
`set spelllang=en_us spell` fires `SpellFileMissing` event with `en_us` argument, and Neovim can't find `en_us` spell file.

### Expected behaviour
`SpellFileMissing` should be fired with `en`, and Neovim should download `en.utf-8.spl` from vim ftp server.

### Steps to reproduce

1. Put 'set spelllang=en_us spell' in `~/.config/nvim/init.vim`.
2. Start Neovim using `nvim`, and prompted with:

```
Cannot find spell file for "en_us" in uft-8
Do you want me to try downloading it?
(Y)es, [N]o:
```
### Other info

Maybe this is useful:
With `nvim -u NORC -c 'set spelllang=en_us spell'`, I got two prompts. The first asks for downloading `en` spell file. Say "No" to this one, and second prompt asks for downloading "en_us" spell file.

**Comment by unsignedzero** [comment]
I'm having the same problem on my Arch Linux Arm box.

**Operating System** 
Arch Linux Arm

**Neovim version:**
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/lib/distcc/bin/cc -march=armv5te -O2 -pipe -fstack-protector --param=ssp -buffer-size=4 -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-param eter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=aut o -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim/src/build/config -I/bui ld/neovim/src/neovim-0.1.2/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/ usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/sr c/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Terminal Emulator**
None, running it over SSH.

**Comment by zostay** [comment]
I am getting this with a recent homebrew build on OS X Yosemite too. Even if you agree to the download, the download fails twice. 

These files definitely do not exist:

http://ftp.vim.org/pub/vim/runtime/spell/en_us.utf-8.spl
http://ftp.vim.org/pub/vim/runtime/spell/en_us.ascii.spl

The vim site seems to have replaced these with en.utf-8.spl files and then a diff file to be applied within en/en_US.diff.

**Comment by justinmk** [comment]
@zostay Thanks for noticing that. Vim made a change to spellcheck recently, but I think the spell files are  still backwards compatible. So we need to change the names.

**Comment by justinmk** [comment]
> SpellFileMissing should be fired with en

@albertnetymk Why is this the expected behavior? I'm not sure we should change this because Vim fires the event with `en_us` as well (assuming it can't find the spellfile). Instead, the `runtime/autoload/spellfile.vim` could be modified to look for `en` if `en_us` is not found.

**Comment by justinmk** [comment]
This was a bug in #3027. Working on a fix.
