### ISSUE TITLE
Replace vim with nvim in runtime/macros/less.sh

### ISSUE THREAD

**Issue by henrik-farre** [neovim/neovim#4407]
- Neovim version:
v0.1.3-278-g2ee37cc

- Operating system:
ArchLinux

- Terminal emulator:
urxvt + tmux

### Actual behaviour
$> man ssh
/usr/share/nvim/runtime/macros/less.sh: line 13: vim: command not found

### Expected behaviour
nvim is used to open man page

### Steps to reproduce
export PAGER="/usr/share/nvim/runtime/macros/less.sh"
export MANPAGER="sh -c \"col -b | /usr/share/nvim/runtime/macros/less.sh -c 'set ft=man nomod nolist number!' -\""

man ssh

**Comment by djrenren** [comment]
Working on it! (this is my first neovim contribution so I'll probably do something wrong)

**Comment by jrobeson** [comment]
this can be closed now right?
