### ISSUE TITLE
How to set :terminal background color

### ISSUE THREAD

**Issue by lewisthompson** [neovim/neovim#4408]
- Neovim version: v0.1.3-303-ged1925e
- Operating system: OSX 10.11
- Terminal emulator: iTerm2

I'd like to use the `:terminal` emulator built in to neovim.  Unfortunately I've been unable to find a way to set the background color for the terminal.  I'd like it to stand out vs the other splits.

fwif I'm using `let $NVIM_TUI_ENABLE_TRUE_COLOR=1` and have tried setting `g:terminal_color_0-15` with no success.

**Comment by justinmk** [comment]
Buffer-local highlighting isn't implemented yet.  Please see:

- https://github.com/neovim/neovim/issues/4141#issuecomment-185345102
- https://github.com/neovim/neovim/issues/1457
