### ISSUE TITLE
Would it be possible to cache folds for a window?

### ISSUE THREAD

**Issue by choco** [neovim/neovim#4414]
Manual folds are lost and other fold types are recomputed when leaving a buffer even if the buffer wasn't deleted (i.e it's hidden) and the window we used to show it is still "alive"
I would expect that opening a couple of files in neovim `nvim file1 file2` and switching between them in the same window wouldn't lose folds state and/or recompute folds. This problem can be solved with mkview but it's incredibly slow, especially if the files is big and with many folds.

**My usecase:**
Since folding using anything that isn't the marker method or indentation method is super slow I personally use two plugins that allow for faster syntax folding (https://github.com/Konfekt/FastFold) and saving of folds state (https://github.com/kopischke/vim-stay). The first computes the folds with the method you prefers and "converts" them in manual folds, the seconds just saves the state in view files.
This works extremely well with files that aren't too big or don't have a large number of folds.
Everything start to fall a part when dealing with really big files with a lot of folds. For example when opening the eval.c source of neovim it can take up to 4-5 seconds to switch back and forth to it because the view file must be executed every time we enter the buffer to restore folds state.

**Comment by justinmk** [comment]
Might be better to optimize `mkview`. But in all cases, if the content of a file doesn't change, it's trivial to verify that using a checksum, so yes, there's no reason we should need to recompute a darn thing in that case.

**Comment by lewis6991** [comment]
Pretty sure this isn't a problem anymore. There's also treesitter highlighting now which I think is more efficient for C.

AFAIK folds in vim are cached and I've never had problems with `eval.c` which is given as an example.

Reopen if I'm wrong.
