### ISSUE TITLE
Wrong PATH used when shell=zsh

### ISSUE THREAD

**Issue by ff2000** [neovim/neovim#4417]
- Neovim version:
NVIM v0.1.3-317-gbd81239
Build type: Gentoo
Compilation: /usr/lib64/distcc/bin/clang -march=sandybridge -mno-aes -O2 -pipe -ggdb -Wno-error -Wconversion  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include
Compiled by portage@TP_L520

Optional features included (+) or not (-): +acl   +iconv    -jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
- Operating system:
Gentoo Linux

- Terminal emulator:
urxvt

### Actual behaviour
I installed neovim-remote into ~/bin. My PATH contains ~/bin. But running `:!nvr` results in command not found. `:set shell=bash` and nvr is found. Also dash and fish seem to work.

`:echo $PATH` -> `/home/franz/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3:/usr/games/bin`
`:!echo $PATH` -> `/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.3:/usr/games/bin`
```
:!nvr

zsh:1: command not found: nvr
Shell beendet 127
```

### Expected behaviour
neovim should get PATH right not depending on nvim's `shell`-variable.

Btw: vim also suffers from the same issue, setting shell=bash also works for vim.

### Steps to reproduce
Drop a random executable script into a non-standard PATH dir. Prepend that dir to $PATH. Open neovim and run `:set shell=zsh` (You might need to install zsh first). Then try to run that command in neovim.

**Comment by justinmk** [comment]
> My PATH contains ~/bin.

What does `:echo $PATH` say in nvim? What does `:!echo $PATH` say?

**Comment by justinmk** [comment]
> Btw: vim also suffers from the same issue, setting shell=bash also works for vim.

This seems a bit suspect. @ZyX-I @tarruda @mhinz also use zsh, maybe they can confirm this.

**Comment by mhinz** [comment]
A bit hard to answer without knowing the environment.

Generally, `:echo $PATH` and `:!echo PATH` should be the same. That makes sense considering that a new process gets a copy of the the parent process. If `shell=zsh`, it means that `:!` will start a _non-interactive_ and _non-login_ shell. You can verify that like this:

```
$ zsh -c 'echo $-'
$ nvim
:!echo $-
```

`$-` won't contain neither `i` (interactive) nor `l` (login). This again means that `/etc/z{profile,shrc,login}` and `~/.z{profile,shrc,login` will not be read, only `/etc/zshenv` and `~/.zshenv`. Are those mangling `$PATH` by any chance?

**Comment by ff2000** [comment]
Ok, thx for your answers. I simply relied on zprezto doing the right thing in .zshenv:
```zsh
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
```
My .zprofile adjusts the path. So something is wrong with those checks.
After moving path adjustment from .zprofile to .zshenv `:!echo $PATH` also contains ~/bin. But .zprofile also does other things that might be important, so I need to find a fix for the above lines.

I close this issue as the problem is not within neovim.

**Comment by smutch** [comment]
I have been having the same problem and did not find a satisfactory solution by checking the referenced issues in this thread.  For reference, if anyone else is still having this problem then the following provides a workaround.

First create a shell script somewhere (e.g. `~/.config/nvim/wrapper.sh`) with the following, adjusting any paths etc. as necessary:

``` sh
#!/bin/sh
SHLVL=1 exec zsh "$@"
```

Give it executable permissions, then set the shell option in your `init.vim` to point to it:

``` vimscript
set shell=$HOME/.config/nvim/wrapper.sh
```

Now when shell commands are executed, `$SHLVL` will be set and `.zprofile` will be sourced.
