### ISSUE TITLE
Different setting for :terminal's shell

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4422]
I would like to set `shell` to a minimal shell (for performance reasons; `set shell=/bin/dash`), but then use the value from `$SHELL` for `:term`.

I've tried to work around this by using a custom command `Term`, but that has different behaviour with regard to quoting (for `:Term echo $TERM` it will print `$TERM` and not the actual value of it, like with `:term echo $TERM`).

```
fun! MyTerm(...)
  echom string(a:000)
  let s_shell = &shell
  let &shell = $SHELL
  enew
  if a:0
    call termopen(a:000)
  else
    call termopen(&shell)
  endif
  let &shell = s_shell
  startinsert
endfun
com! -nargs=* Term call MyTerm(<f-args>)
```

While I can imagine that the wrapper can be made to work in the same way as `:term` eventually, I think a new setting `'shell_term'` (defaulting to `'shell'`) would be better.

I've also tried `au TermOpen * let &shell = 'zsh'`, but that's too late apparently.

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/issues/2292
