### ISSUE TITLE
Provide an API to get current milliseconds

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4433]
According to http://vim.1045645.n5.nabble.com/Add-milliseconds-to-strftime-td5724772.html it seems like there's not way to get this time resolution on the (Neo)Vim side.

Related: https://github.com/neovim/neovim/issues/1404

I would like to use this to distinguish if an async process should be started, but without calling it (Python) directly to check the time(out).

**Comment by justinmk** [comment]
`reltime()` has microsecond-accuracy. https://github.com/neovim/neovim/pull/839

It can be formatted with reltimestr().

**Comment by blueyed** [comment]
@justinmk 
Thanks!  (used in https://github.com/Shougo/deoplete.nvim/pull/212)

I guess it should be added to the doc with e.g. `strftime()`?!

**Comment by justinmk** [comment]
Yes, for sure. I had a hard time finding it myself.

**Comment by blueyed** [comment]
As per https://github.com/neovim/neovim/issues/5301 `reltime()` is not really the current time though.
`strftime('%s')` is an option, but the docs say that it might not be portable.

My use case is a log prefix with Neomake, where a more granular resolution than seconds is needed.

**Comment by tweekmonster** [comment]
@blueyed I actually added a way to get the current time with nanosecond precision in #5189 (not merged).

Specific lines: https://github.com/tweekmonster/neovim/blob/d15365479a8a1dc484247fb6dbe100128d3a0eb0/src/nvim/os/time.c#L123-L131

It could be used make a `localtimef()` Vim function.  I can't attest to whether or not it's truly the best way to get the fractional time, but it was accurate enough for my needs.  It probably needs the `init_time_*` variables reset once in a while so it'll be less affected by crossing time boundaries.

**Comment by ankitcr7-afk** [comment]
Hey people I'm a beginner and wish to contribute can any one please guide me as i have never done a contribution. It would be a great help.
Thank You

**Comment by wsdjeg** [comment]
This ia very useful for writting log, hepo it can be implemented soon. :)

**Comment by gpanders** [comment]
You can use `vim.loop.now()` in Lua (or `luaeval('vim.loop.now()')` from Vim script).

**Comment by wsdjeg** [comment]
@gpanders thanks, but if I want to get time string like `21:58:30`, I can use `strftime('%H:%M:%S')`, but how to get `21:58:30:768`

**Comment by gpanders** [comment]
`string.format("%s:%d", os.date("%H:%M:%S"), vim.loop.now() % 1000)`

**Comment by zeertzjq** [comment]
It seems `uv.now()` can start counting at any arbitrary millisecond, so this is not really accurate.

**Comment by wsdjeg** [comment]
hmm, the format should be changed, because somtimes I got:

```
[ SpaceVim ] [22:31:51:864] [ Info  ] init spacevim root dir:C:/Users/wsdjeg/.SpaceVim/
[ SpaceVim ] [22:31:51:14] [ Info  ] Startup with no argv, current dir is used: ~\.SpaceVim
```

I think it should be:

```
[ SpaceVim ] [22:31:51:864] [ Info  ] init spacevim root dir:C:/Users/wsdjeg/.SpaceVim/
[ SpaceVim ] [22:31:51:014] [ Info  ] Startup with no argv, current dir is used: ~\.SpaceVim
```


--------------



Wang Shidong

**Comment by wsdjeg** [comment]
Ok, thanks, the comment has been edited, but no email notification, sorry.

**Comment by wsdjeg** [comment]
> It seems `uv.now()` can start counting at any arbitrary millisecond, so this is not really accurate.

yeah, please see these log: line 2 and line 3

```
[ SpaceVim ] [22:36:12:943] [ Info  ] global_dir is: C:/Users/wsdjeg/.SpaceVim.d/
[ SpaceVim ] [22:36:12:943] [ Info  ] start to apply config [glob]
[ SpaceVim ] [22:36:12:025] [ Info  ] SpaceVim server startup at:\\.\pipe\spacevim-nvim-server
[ SpaceVim ] [22:36:12:147] [ Info  ] the func has been added to mode:syntax-checking
[ SpaceVim ] [22:36:13:358] [ Info  ] the func has been added to mode:spell-checking
```

**Comment by zeertzjq** [comment]
AFAIK there is currently no API to get **absolute** time in milliseconds.

**Comment by lewis6991** [comment]
libuv added `uv_gettimeofday()` in 1.28.0 ([ref](https://github.com/libuv/libuv/issues/1197)). This is currently accessible in Neovim as `vim.uv.gettimeofday()`.

**Comment by dundargoc** [comment]
Shall we close this then? Or am I misinterpreting your comment @lewis6991 ?

**Comment by lewis6991** [comment]
I believe a solution exists here, so closing this.

If it is not sufficient, then issue can be re-opened.

**Comment by aidancz** [comment]
This example is provided for convenience:

```lua
local get_time = function()
	local second, microsecond = vim.uv.gettimeofday()
	local second_format = os.date("%Y-%m-%d %H:%M:%S", second)
	local microsecond_format = string.format("%06d", microsecond)
	local time = second_format .. " " .. microsecond_format
	return time
end

local print_time = function()
	print(get_time())
end

-- test:
print_time()
```
