### ISSUE TITLE
YouCompleteMe server shutdown on E716: Key not present in Dictionary: setShowHidden'

### ISSUE THREAD

**Issue by guilala** [neovim/neovim#4434]
- Neovim version: NVIM v0.1.3-331-gd9ecd06
- Operating system: Ubuntu
- Terminal emulator: Terminator

### Actual behaviour
The ycmd server SHUT DOWN

### Expected behaviour
Auto completion on Javascript file, using TernJs

### Steps to reproduce
Follow steps to install YouCompleteMe with Tern, and just open a Javascript file.

### Stdout

```
/tmp/ycm_temp/server_37444_stdout.log" 0L, 0C
Error detected while processing function <SNR>105_ToggleLogs[3]..provider#python3#Call:
line   18:
NvimError(b'Vim(call):E716: Key not present in Dictionary: setShowHidden',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/session.py", line 181, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python3.5/dist-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python3.5/dist-packages/neovim/plugin/host.py", line 66, in _on_request
    rv = handler(*args)
  File "/usr/local/lib/python3.5/dist-packages/neovim/plugin/host.py", line 152, in <lambda>
    decoder = lambda fn, hook, *args: fn(*hook.walk(args))
  File "/home/guilala/Code/Bash/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
neovim.api.nvim.NvimError: b'Vim(call):E716: Key not present in Dictionary: setShowHidden'
```

**Comment by guilala** [comment]
Nerdtree can bump into similar issue:

[Nerdtree issue](https://github.com/scrooloose/nerdtree/pull/544)

Error detected while processing function <SNR>43_BufReadHandler[3]..<SNR>43_NERDTreeFindFile[2]..<SNR>40_findAndRevealPath:
line   33:
E716: Key not present in Dictionary: setShowHidden

**Comment by justinmk** [comment]
Not a neovim issue.

**Comment by guilala** [comment]
When it seams that youcompleteme isn't currently compatible with neovim, or the other way around: both neovim, and youcompleteme developers find that unimportant.

While vim itself is nice, neovim's arguments against it are important. So i wouldn't switch back to vim just for youcompleteme myself. But it's just impossible for an opensource software end- user, to have to fix every issue himself. Thanks anyway...

**Comment by tarruda** [comment]
@guilala YouCompleteMe has good compatibility with nvim. In the few scenarios where it's incompatible, it is due to a bug in the python API emulation(which we try to fix ASAP)

What @justinmk meant is that this doesn't seem like an nvim issue: The exception message states that `setShowHidden` is missing, so it seems like a bug in one of your python plugins(possibly Nerdtree) triggered the exception.

**Comment by wsdjeg** [comment]
@guilala 
I am using ycm in neovim with ubuntu,but my terminal is gnome-terminal,IMO,if you encounter any issue,you should show us the info as more as possible.
1. what is your os version,terminal version,neovim version,python version,
2. reproduce step
also it is better test it in `nvim -u NONE` or show us the minivimrc,it will be easy for us to find what the issue is.

**Comment by wsdjeg** [comment]
and here is what I got by searching  from github
https://github.com/scrooloose/nerdtree/pull/544/files

**Comment by guilala** [comment]
Thanks for the quick replies :+1 , and it's very good to know ycm does work with nvim! I already tried running nvim without nerdtree, but still same ycm server crash issue occurs. Likely related to Python API indeed.

**Comment by tarruda** [comment]
@guilala can you link to a nvimrc(preferably a minimal one) that reproduces the issue?

**Comment by guilala** [comment]
When i use a minimun nvim/init.vim i don't get a server crash, rather this:

* init.vim:
```
call plug#begin('~/.vim/plugged')

Plug 'Valloric/YouCompleteMe' 

call plug#end()

let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'
```

* stderr.log
```
guilala box cat /tmp/ycm_temp/server_35923_stderr.log 
2016-03-15 11:20:54,345 - DEBUG - No global extra conf, not calling method YcmCorePreload
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/guilala/.vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 183, in <module>
    Main()
  File "/home/guilala/.vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 160, in Main
    if not CompatibleWithCurrentCoreVersion():
  File "/home/guilala/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/server_utils.py", line 50, in CompatibleWithCurrentCoreVersion
    import ycm_core
ImportError: dynamic module does not define init function (PyInit_ycm_core)
```

**Comment by guilala** [comment]
When running an init.vim with only ycm, ycm's std output is completely different, and was easy to fix with "g:ycm_path_to_python_interpreter". But it's unfortunate that the errors from plugins can obfuscate each other's output. I guess isolating plugins more is not possible?

Anyhow, now ycm Javascript autocompletion is working here, my list of editor- must- haves are satisfied for Neovim. Now i can easily ditch Webstorm, etc, in favour of Neovim, for nodeJs and front- end development. You can imagine the amount of recourses (and frustration) that freed up :-) !!
