### ISSUE TITLE
Error detected while processing function <SNR>104_NetrwBrowseChgDir:

### ISSUE THREAD

**Issue by piknik** [neovim/neovim#4435]
- Neovim version: 0.1.2
- Operating system: Linux 4.4.3-1
- Terminal emulator: urxvt

### Actual behaviour
![neovim](https://cloud.githubusercontent.com/assets/3429961/13689506/48fc3a74-e6f7-11e5-9558-654d1bab585b.png)

This error gets displayed when using netrw (:Ex). It doesn't always happen, but when it does, it occurs every time when opening a file, until I restart Neovim, then it's gone. Also, when this error occurs and I select a file for opening, it doesn't open in the same split, it opens in another instead. Also, all of the splits in the same tab get changed to netrw.
The second error, "E16: Invalid range: keepj keepalt 3wincmd w" appears only for half a second before disappearing.
It has happened a few times for the past couple weeks (since around last week of February), so I am sure it's some kind of bug and not memory errors.

### Expected behaviour
Should work as usual all the time

### Steps to reproduce
Cannot reproduce easily. Maybe leave neovim on for days in a row.

**Comment by piknik** [comment]
If anyone needs some kind of logs or dump, I'd be happy to provide it, but I don't know how. I would need help with that.

**Comment by Shougo** [comment]
It is netrw's bug.
It is the invalid issue in neovim.

**Comment by piknik** [comment]
Was hoping since netrw comes with neovim that it would be looked into. Netrw hasn't been updated since 2014, and there doesn't seem to be a way to report this bug, so it seems like it could be a dead project.

Seems to me like I should check out NERDTree...

**Comment by justinmk** [comment]
Thanks for the report, but we don't maintain netrw. We pull in updates from Vim.

**Comment by chrisbra** [comment]
@piknik netrw is maintained, it's just that he does not develop his plugins using github. You can however provide feedback, by emailing him directly. And he provides nighty builds on his website.

**Comment by wsdjeg** [comment]
you can disable netrw,and just use vimfiler instead

**Comment by piknik** [comment]
@wsdjeg Didn't know about vimfiler, thanks for the suggestion! It seems as light as netrw with a few more features.
I've sent this bug to the netrw developer.
