### ISSUE TITLE
:terminal colors don't match

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#4436]
- Neovim version:
NVIM v0.1.3-336-gbb020df
Build type: Dev

- Operating system:
OSX 10.10.5

- Terminal emulator:
Build 2.9.20160206

#### neovim:
```
colorscheme molokai
$ echo $TERM
xterm-256color
```
`ls -l` in neovim terminal:
![image](https://cloud.githubusercontent.com/assets/820137/13694423/09be5bae-e70a-11e5-9f3f-792ae6c13a79.png)

#### iterm2:
```
$ echo $TERM
xterm-256color
$ echo $NVIM_TUI_ENABLE_TRUE_COLOR
1
```
`ls -l` in terminal emulator:
![image](https://cloud.githubusercontent.com/assets/820137/13694388/d3ee5be6-e709-11e5-8d5d-eb1d3242692f.png)

### Expected behaviour
I would expect neovim term colors to match iterm2 colors
### Steps to reproduce

**Comment by justinmk** [comment]
can you see if https://github.com/neovim/neovim/pull/4350 fixes this for you?

**Comment by vito-c** [comment]
what's the best way to build that sha on osx?

**Comment by mhinz** [comment]
@vito-c 

```
$ git clone https://github.com/neovim/neovim.git
$ cd neovim
$ git fetch origin pull/4350/head
$ git checkout FETCH_HEAD
$ make
$ build/bin/nvim
```

**Comment by vito-c** [comment]
@mhinz thanks :)

**Comment by vito-c** [comment]
same result

**Comment by justinmk** [comment]
@vito-c Are the results different with `NVIM_TUI_ENABLE_TRUE_COLOR` disabled? (Your report indicates you have it enabled, right?)

**Comment by vito-c** [comment]
When using the head version of neovim the issue only happens when I have NVIM_TUI_ENABLE_TRUE_COLOR set.

When I unset NVIM_TUI_ENABLE_TRUE_COLOR on the head version of neovim it works as expected.

The PR you linked has the same results as the head version of neovim

**Comment by justinmk** [comment]
Thanks. I don't grok the vterm init logic yet, but I bet @DarkDefender might know the answer to this.

**Comment by DarkDefender** [comment]
@vito-c, @justinmk yes, if neovim is in true color mode, you need to manually specify the terminal colors with g:terminal_color*. Otherwise it will use the default ANSI vterm colors.

**Comment by justinmk** [comment]
`bash` is not using RGB colors. So if you run `nvim` without true-color, it will match `bash`.

In true color mode, we offer `:help nvim-terminal-emulator-configuration` to configure RBG ("true") colors.  [Here's a block](https://github.com/neovim/neovim/pull/2076#issuecomment-84462473) to copy-paste for future reference:

```vim
let g:terminal_color_0  = '#2e3436'
let g:terminal_color_1  = '#cc0000'
let g:terminal_color_2  = '#4e9a06'
let g:terminal_color_3  = '#c4a000'
let g:terminal_color_4  = '#3465a4'
let g:terminal_color_5  = '#75507b'
let g:terminal_color_6  = '#0b939b'
let g:terminal_color_7  = '#d3d7cf'
let g:terminal_color_8  = '#555753'
let g:terminal_color_9  = '#ef2929'
let g:terminal_color_10 = '#8ae234'
let g:terminal_color_11 = '#fce94f'
let g:terminal_color_12 = '#729fcf'
let g:terminal_color_13 = '#ad7fa8'
let g:terminal_color_14 = '#00f5e9'
let g:terminal_color_15 = '#eeeeec'
```

**Comment by sassanh** [comment]
@justinmk I think these 16 colors are not enough, I tried to print 5 lines with background and foreground set to color 99 using tput in neovim and in terminal (I'm using iTerm2) and these colors are different.
The problem is programs like htop, clang++, django, npm (some message they show in color), fish, etc are different in normal terminal and in neovim. It's kinda annoying. So are these programs using hex codes in normal terminal and 256 color code in neovim? If yes please let me know if there were any discussion about it on github so that I can follow it there. If no, do you know anyway I can set the exact same 256 colors from my terminal in neovim?

**Comment by dkarter** [comment]
I'm experiencing the same issue too. 

Expected (iTerm2)
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/551858/34473126-6d860586-ef34-11e7-9d59-d77412c4bb48.png">

Actual (NeoVim Terminal with termguicolor running inside iTerm2)
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/551858/34473143-8ea26bec-ef34-11e7-9314-c65b6194e32d.png">

Left: NeoVim Terminal, Right: iTerm2
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/551858/34473414-da9ad04a-ef37-11e7-9178-6284334243ad.png">

Has anyone found a solution?

Also @justinmk that help file you pointed to seems to no longer be there in the latest NeoVim.

**Comment by sassanh** [comment]
Thanks for screenshots, things look like the same on my machine for htop.

**Comment by alok** [comment]
I still have this issue, even after using the lastest build from master that uses the new libvterm. Is that to be expected?

<img width="1440" alt="Screenshot 2019-09-11 10 33 05" src="https://user-images.githubusercontent.com/8325708/64720773-18e3de80-d480-11e9-8cd7-bcf797ca593d.png">
