### ISSUE TITLE
First column highlight after set spelllang

### ISSUE THREAD

**Issue by MartinBrugnara** [neovim/neovim#4437]
- Neovim version: v0.1.3-338-g1c066e6
- Operating system: OSX 10.11.3 (15D21)
- Terminal emulator: Terminal (terminfo: xterm-256color)

### Actual behaviour
- Set spellchecker lang
- Highlights (like when selecting in visual mode) first charter for each line

### Expected behaviour
- Set spellchecker lang

### Steps to reproduce
`set spelllang=en`

**Comment by mhinz** [comment]
I can't reproduce that with `nvim -u NONE`.

**Comment by MartinBrugnara** [comment]
Indeed, sorry.
Shall I post my .virmrc or report to 3rd party ?

**Comment by mhinz** [comment]
Yea, let's try that. Most probably your init.vim or one of your plugins searches for `^`, the beginning of the line. You can verify that by doing:

```vim
:set spelllang=en
:echo histget('search', -1)
```

**Comment by MartinBrugnara** [comment]
@mhinz removing `powerline` plugin resolved the issue.

Eventough is more probable that I had messed up with the configuration of powerline than its a problem of the plugin itself.

I will try to find it out and in case report to the plugin project.

Thank you for the help!
