### ISSUE TITLE
"No matching autocommands" message after loading neovim

### ISSUE THREAD

**Issue by rsmith31415** [neovim/neovim#4445]
- Neovim version: 0.1.3-dev
- Operating system: Ubuntu GNOME 15.10
- Terminal emulator: gnome-terminal

### Actual behaviour
There is a "No matching autocommands" message after loading neovim and this seems to be triggered by specific plugins (e.g. Plugin 'bling/vim-airline', Plugin 'scrooloose/syntastic')

### Expected behaviour
This message shouldn't appear.
### Steps to reproduce
I noticed this happens in the latest version of neovim. The message doesn't show up when I comment out those plugins. This is my init.vim file:

```
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'Raimondi/delimitMate'
Plugin 'hdima/python-syntax'
Plugin 'scrooloose/syntastic'
Plugin 'tomasr/molokai'
Plugin 'KevinGoodsell/vim-csexact'
Plugin 'kien/ctrlp.vim'

set encoding=utf-8
set t_Co=256
colorscheme badwolf
" monokai, gruvbox, badwolf, molokai, distinguished, xoria256
"set incsearch
syntax on
set undodir=~/.config/nvim/undodir
set undofile
set undolevels=1000 
set undoreload=10000
set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
set linebreak
set laststatus=2
set noshowmode
set nohlsearch
set clipboard=unnamedplus
runtime macros/matchit.vim
let g:airline_powerline_fonts = 1

tnoremap <Esc> <C-\><C-n> 
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/commit/1c066e671d0ebd632071b87b4d0e15dcdc659535 should have fixed this already. Can you check if line 133 of host.vim looks like this:

https://github.com/neovim/neovim/commit/1c066e671d0ebd632071b87b4d0e15dcdc659535#diff-56c8fc368678358892f215c76bd2178cR133

**Comment by rsmith31415** [comment]
Thanks. Yes, that fixes it.

**Comment by halfCheese** [comment]
I looked in host.vim, and it does not have function! remote#host#LoadRemotePluginsEvent. Would adding the function fix the problem?

**Comment by Shougo** [comment]
@halfCheese Your host.vim seems old.  Please update neovim.
