### ISSUE TITLE
Error detected while processing function <SNR>2_lod_cmd

### ISSUE THREAD

**Issue by daenney** [neovim/neovim#4447]
- Neovim version: 0.1.2
- Operating system: OS X 10.11.3
- Terminal emulator: iTerm2

### Actual behaviour
nvim loads with both Startify and NERDTree enabled but also throws an error message.

```
Error detected while processing function <SNR>2_lod_cmd:
line    2:
E580: :endif without :if:  endif
```

```viml
autocmd VimEnter * if !argc() | Startify | NERDTree | wincmd w | endif
```

### Expected behaviour

nvim loads with both Startify and NERDTree enabled without any additional error messages. Or, if there is something truly wrong with the `autocmd` line give a more helpful description of what is wrong.

### Steps to reproduce

* Have vim-startify and nerdtree plugins available
* Add this to `$XDG_CONFIG_HOME/nvim/init.vim`:
```viml
autocmd VimEnter * if !argc() | Startify | NERDTree | wincmd w | endif
```
* Start `nvim` with no arguments.

**Comment by wsdjeg** [comment]
I can not reproduce it.here is my start up screen,
![2016-03-13 18-34-04](https://cloud.githubusercontent.com/assets/13142418/13728168/40f8575e-e94a-11e5-802b-bd2dbfb4d1aa.png)

**Comment by daenney** [comment]
For me if I uncomment the `autocmd VimEnter * if !argc() | Startify | NERDTree | wincmd w | endif` it works. When I have it active, it still works, it just throws that additional error message :confused:.

**Comment by daenney** [comment]
Oh, found it.

I had NERDTree loaded through Plug but configured as `Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }`. Switching it over to `Plug 'scrooloose/nerdtree'` fixed it.

**Comment by wsdjeg** [comment]
how about 
`autocmd VimEnter * if !argc() | Startify | NERDTreeToggle | wincmd w | endif`
maybe no need disable lazy load

**Comment by daenney** [comment]
Oh, d'oh, `NERDTree` vs `NERDTreeToggle`. Can't believe I didn't see that. Sorry for the noise and thanks for the help!

**Comment by shmerl** [comment]
@daenney: To avoid constant loading, you can also do this:

    Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeTabsToggle' }
    Plug 'jistr/vim-nerdtree-tabs', { 'on': 'NERDTreeTabsToggle' }
