### ISSUE TITLE
Neovim crashes when sourcing a vimball on Windows

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#4450]
- Neovim version: 0.1.3-dev ([Neovim](https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw) + [Neovim-Qt](https://github.com/equalsraf/neovim-qt/releases)) 
- Operating system: Windows 10

### Actual behaviour

Neovim crashes when sourcing Nvim-R vimball.

### Expected behaviour

The plugin is installed.

### Steps to reproduce

 - Download https://github.com/jalvesaq/Nvim-R/releases/download/v0.9.1/Nvim-R.vmb
 - Open it with Neovim-Qt
 - `:so %`

**Comment by equalsraf** [comment]
Does this still happen? I'm using 667f53f and cannot reproduce.

**Comment by jalvesaq** [comment]
I was using the binary that was available at https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw
I don't know how to build neovim on Windows. Is it already possible to build neovim on Windows from github.com/neovim/neovim ?

**Comment by jalvesaq** [comment]
Note: I have put this line in my ~/_vimrc:
```
set runtimepath=$HOME/AppData/Local/nvim,$VIMRUNTIME,$HOME/AppData/Local/nvim/after
```
Then, I used Gvim to install the Vimball.

**Comment by jalvesaq** [comment]
It is working fine now!
