### ISSUE TITLE
Python: accessing vim.current.window closes popupmenu (rplugin)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4452]
- Neovim version: NVIM v0.1.3-344-gb030c90
- Operating system: Linux
- Terminal emulator: rxvt-unicode

### Actual behaviour

Accessing `vim.current.window.cursor` in a remote plugin will close any opened popup menu.
This seems to be the case for all properties on `vim.current.window` (at least also for `buffer`), but not `vim.current` itself.  The same applies to calling `vim.funcs.foo()`.

I've noticed this in the context of deoplete, which does this to check if the position has changed:

https://github.com/Shougo/deoplete.nvim/blob/816bea3a9a0c5a1cc53488256d452edea04cb70a/rplugin/python3/deoplete/deoplete.py#L315-L317

It does not seem to be a problem when calling it through `pyeval` in `i_CTRL-R_=`:

> =pyeval('vim.funcs.pumvisible()')

That will insert 1, but keep the popupmenu / completion mode.

This is maybe a bug with https://github.com/neovim/python-client?! /cc @bfredl 

/cc @Shougo

**Comment by bfredl** [comment]
Hmm, this would imply `vim_get_current_window` is popupmeny-safe but not `window_get_cursor` .  A quick glance it looks like `window_get_cursor` is pure (it doesn't fiddle with curwin/curbuf). Are you sure `vim.current.window` is safe ?

**Comment by blueyed** [comment]
> Are you sure `vim.current.window` is safe ?

No, was meant to say `vim.current`.

**Comment by Shougo** [comment]
@blueyed Please provide the reproduce ways.  I will try it.

**Comment by blueyed** [comment]
@Shougo 
It's rather complex because it's in the internals of deoplete..  you can see it from a minimal vimrc (like the one below), and then by invoking completion through `InsertEnter` (e.g. `A`) and pressing `Ctrl-P` right away.  Using `let g:deoplete#auto_complete_delay = 1000` makes it easier in case the completion is not slow enough.

`Ctrl-P` will open Vims internal completion, and then deoplete finishes (especially with the `sleep`) and triggers this issue (via `check_position`, linked above already).

        set rtp+=~/.vim/neobundles/deoplete
        syntax on
        filetype plugin indent on
        set tabstop=4
        set shiftwidth=4
        set expandtab
        let g:deoplete#enable_at_startup = 1
        let g:deoplete#auto_complete_delay = 1000

**Comment by blueyed** [comment]
btw: I've tried the following, but it will also close the popup menu already:

    diff --git i/rplugin/python3/deoplete/deoplete.py w/rplugin/python3/deoplete/deoplete.py
    index f9b9431..456b888 100644
    --- i/rplugin/python3/deoplete/deoplete.py
    +++ w/rplugin/python3/deoplete/deoplete.py
    @@ -53,6 +53,12 @@ def __init__(self, vim):
             self.__profile_start = 0
     
         def completion_begin(self, context):
    +        if self.__vim.eval('pumvisible()') == 1:
    +            return

@bfredl 
Where is this happening in the code?

**Comment by bfredl** [comment]
the bug is likely in nvim itself, in `src/nvim/edit.c`

**Comment by bfredl** [comment]
Seems a missing K_EVENT case, could you try #4461 ?

**Comment by Shougo** [comment]
I can reproduce the problem.
Yes, all RPC calls close the popupmenu.

**Comment by blueyed** [comment]
@Shougo 
It's not the RPC call by itself (IIRC), but only when certain things get accessed.
IIRC just `return`ing would not trigger it.

#4461 fixes it for me.

**Comment by Shougo** [comment]
> It's not the RPC call by itself (IIRC), but only when certain things get accessed.

The self access is not RPC call...

**Comment by blueyed** [comment]
That's what I mean.. (because you've said that all RPC calls close the popupmenu).

Accessing or returning `self.__vim` for example also won't trigger it (from within the RPC call).
