### ISSUE TITLE
Centre items in status/tagline

### ISSUE THREAD

**Issue by tpict** [neovim/neovim#4454]
Currently we can align text to the left or right hand side of the statusline and tagline by using the ```%=``` delimiter. Would it be possible to add an extra delimiter so that text can be centre-aligned?

**Comment by tjdevries** [comment]
@justinmk, I would be willing to take a look at the work for this enhancement. I have not yet contributed to the project, but I've been a long time lurker and been using Neovim for several months. I could use a little guidance on where I should start looking for this, if that would be alright.

**Comment by mhinz** [comment]
@tjdevries It happens in  `build_stl_str_hl()` and makes use of an enum from `options_defs.h` (search for `STL_`). If you search for `STL_MIDDLEMARK` in that function, you find the place where it separates between left and right alignment.

**Comment by tjdevries** [comment]
Awesome! Thanks for the help. I will start looking at that this week.

**Comment by tjdevries** [comment]
@motdef, check out #4489 and let me know if that's the general idea you were thinking of. I have a picture of a current working version that I have. There's still quite a bit more work to be done, but the idea is definitely there now.

You can now use `%[` and `%]` to center text in the middle of your statusline.

**Comment by motdef** [comment]
That's pretty much what I had in mind. Nice work :)

**Comment by tjdevries** [comment]
Awesome :+1: I still have to work out several truncation issues, and some different combinations of `%[` and `%]` with `%=`. It does look quite cool having some text centered there.

**Comment by tjdevries** [comment]
#4489 has been closed. This is now implemented :D. 

This issue can be closed I think.

**Comment by X3eRo0** [comment]
does this work? I tried it and it doesnt work in the latest neovim
