### ISSUE TITLE
Line numbers show in terminal when selected from buffers

### ISSUE THREAD

**Issue by tpict** [neovim/neovim#4455]
- Neovim version: NVIM v0.1.3-240-gb16b27a
- Operating system: OS X 10.11.3
- Terminal emulator: iTerm2
### Actual behaviour

When a terminal is opened with :terminal, line numbers are hidden from the active window. However, if an existing terminal buffer is selected in a window, line numbers are shown.
### Expected behaviour

Displaying line numbers on terminal buffers should be consistent (possibly configurable).
### Steps to reproduce
1. Start Neovim and :set number
2. Create split
3. Start terminal with :terminal
4. Navigate to second window
5. Select the terminal buffer created in step 3. It will be shown with line numbers.

![screen shot 2016-03-15 at 18 20 43](https://cloud.githubusercontent.com/assets/12588098/13789163/b1f979ba-eada-11e5-827b-b1486ecad5b0.png)

This doesn't seem to happen if the split is created after the terminal is spawned, and then one of the windows is cycled to a file and back to the terminal again

e: the version number quoted is for nvim built with #4350 but I've confirmed this to be present in the master branch too
e2: edit for clarity

**Comment by nhooyr** [comment]
confirmed over here as well. Now I remember why I had an autocmd to set nonumber for terminal buffers. I guess I just forgot to report the issue.

**Comment by justinmk** [comment]
`'number'` is a window-local setting. If you navigate to a help document, it will also look weird. Terminals are initialized with certain settings, but we can't change window-local settings just because you show an existing terminal inside that window (that would make you very unhappy in most cases).

**Comment by wamoyo** [comment]
So, can we configure terminal windows in neovim to not show line numbers?

**Comment by justinmk** [comment]
Yes, it's not any different than regular buffers in that regard. This has been answered before and it's a usage question.

**Comment by justinmk** [comment]
`:terminal` doesn't have much special-casing for `'number'` any more, and the original repro steps here no longer apply.

There are other discussions about further refinement.
