### ISSUE TITLE
:terminal command does not exit cleanly when :qall

### ISSUE THREAD

**Issue by kballenegger** [neovim/neovim#4457]
- Neovim version:

```
NVIM 0.1.2
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/build/config -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/src -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/build/src/nvim/auto -I/tmp/neovim20160314-13381-o61n23/neovim-0.1.2/build/include
```
- Operating system: OS X
- Terminal emulator: iTerm2
### Actual behavior

When running something in a terminal session (e.g. running a server that binds to a port), and quitting vim with `:qall`, the process is not stopped gracefully.
### Expected behavior

When quitting vim (`:qall`) with a terminal buffer open, `SIGINT` is sent to the process running in all terminal buffers, and the process is kept alive long enough to handle the signal.
### Steps to reproduce

```
$ cat > ./dev
#!/bin/bash

postgres -D db/pg &
memcached &
shotgun --server=thin --port=8000 config.ru &

function interupt {
    kill $(jobs -p | tr -s ' ' | cut -d' ' -f 3)
}

trap interupt SIGINT SIGTERM
wait
sleep 1
$ chmod +x ./dev
$ nvim
```

In vim:
- `:te ./dev`
- `:qall`

Notice, the subprocesses are still running:

```
$ ps aux | grep memcached
kenneth         85521   0.0  0.0  2485676   1292 s010  S+    2:01PM   0:00.01 memcached
```

**Comment by HarmtH** [comment]
Terminals should transmit a SIGHUP when closed ('Hanging UP'), not SIGINT/SIGTERM/SIGKILL/etc. The Neovim terminal also seems to do that.

**Comment by Shougo** [comment]
I think it is same issue.
https://github.com/neovim/neovim/issues/4778

**Comment by justinmk** [comment]
Verified that `:terminal` sends SIGHUP with the script below.
Also verified that macOS Terminal.app sends SIGHUP when it is closed.

As @HarmtH noted and according to [wiki](https://en.wikipedia.org/wiki/SIGHUP),

> SIGHUP ... is sent to a process when its controlling terminal is closed.

Also,

> shell ... will often intercept the signal and ensure that all stopped processes are continued before sending the signal to child processes ...
> This can be circumvented in two ways. Firstly, ... `nohup`. ... Secondly, ... `disown` ... removes the process group from the shell's job table (so they will not be sent SIGHUP)

So,

- SIGHUP seems to be correct; 
- sending some other signal would break common tools like `nohup`; and 
- propagation of the signal is up to the shell in any case.


```sh
#!/bin/bash

function handle_sigint {
  echo sigint >> dev.log
}
function handle_sigterm {
  echo sigterm >> dev.log
}
function handle_sighup {
  echo sighup >> dev.log
}

trap handle_sigint SIGINT
trap handle_sigterm SIGTERM
trap handle_sighup SIGHUP
wait
sleep 100
```
