### ISSUE TITLE
Merging patches from upstream doc: missing some prerequisites 

### ISSUE THREAD

**Issue by fflorent** [neovim/neovim#4458]
If we follow the documentation of this page: https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

We miss some prerequisites, for example that we need to clone neovim and make sure our repository is pointed by `origin` and the upstream repo by `upstream` (might be obvious), and that we need hub (https://github.com/github/hub) to make it run.

Florent

**Comment by fflorent** [comment]
Moreover, it seems like there are some issues while pushing a PR. What did I do wrong : 
````
Creating pull request.
✘ github.com username: github.com password for [RFC] vim-patch:7.4.1574 (never stored): Error creating pull request: Unauthorized (HTTP 401)
Bad credentials
````

BTW, thanks for all the work you do :).

Florent

**Comment by justinmk** [comment]
Hub isn't required, it's optional. I don't use hub at all. I suppose the wiki could be tweaked, but there's a risk of providing too much detail. We must assume some familiarity with git.

**Comment by fflorent** [comment]
The problem isn't the familiarity with Git, it's the context, the requirement of the script provided (hub is required), etc. 

Florent

**Comment by justinmk** [comment]
Hub is only required for creating a pull request via that script feature. You can create the pull request without using the script.
