### ISSUE TITLE
Unnormal Highlight behavior under TrueColor mode

### ISSUE THREAD

**Issue by lvht** [neovim/neovim#4463]
- Neovim version:0.1.2
- Operating system:ArchLinux
- Terminal emulator:st+tmux

### Actual behaviour
after enable the true color mode by
```
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
```
I cannot use the **ctermfg** to set the frontcolor, but the **guifg** works. And **guifg=Red** works, but the **guifg=bg** doesn't.
### Expected behaviour
I can use **ctermfg=bg** to set the frontcolor.
### Steps to reproduce
- open neovim and input something like:
```
> hello
> test
```
- execute `:let $NVIM_TUI_ENABLE_TRUE_COLOR=1`
- execute `:syntax match lv /^>/`
- execute `:highlight lv  ctermfg=bg`, not work
- execute `:highlight lv  ctermfg=red`, not work
- execute `:highlight lv  gui=bg`, not work
- execute `:highlight lv  gui=red`, **work** the leading`>`'s color is set to red

**Comment by justinmk** [comment]
guifg/guibg are used in true-color mode. Not cterm.

**Comment by justinmk** [comment]
fixed in https://github.com/neovim/neovim/pull/5319
