### ISSUE TITLE
long echo in the tabline function leads to visual glitches

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#4464]
- Neovim version:
```
NVIM v0.1.3-350-gc94575f
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -
g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim2016031
6-25892-trk07q/build/config -I/tmp/neovim20160316-25892-trk07q/src -I/tmp/neovim20160316-25892-trk07q/
deps-build/usr/include -I/tmp/neovim20160316-25892-trk07q/deps-build/usr/include -I/tmp/neovim20160316
-25892-trk07q/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160316-25892-trk07q/deps-build/usr/incl
ude -I/tmp/neovim20160316-25892-trk07q/deps-build/usr/include -I/tmp/neovim20160316-25892-trk07q/deps-
build/usr/include -I/tmp/neovim20160316-25892-trk07q/deps-build/usr/include -I/usr/local/opt/gettext/i
nclude -I/usr/include -I/usr/include -I/tmp/neovim20160316-25892-trk07q/build/src/nvim/auto -I/tmp/neo
vim20160316-25892-trk07q/build/include
Compiled by nhooyr@aubble

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```
- Operating system: OSX 10.11.3
- Terminal emulator: iTerm2 Beta

### Actual behaviour
Echoing a string from the tabline function that results in the `Press enter or type command to continue` prompt leads to visual glitches. The prompt never disappears.

### Expected behaviour
That the prompt will disappear.

### Steps to reproduce
```vim
function! Tabline()
  let s = ''
  for i in range(&columns)
    let s .= '#'
  endfor
  echo s
endfunction
set tabline=%!Tabline()
set showtabline=2
```

Use the above as the init.vim when starting neovim. Then press enter or type anything to try and get rid of the prompt, but it never disappears.

As always, here is a visual: https://youtu.be/Trd6iLjKiDE

This also happens in vim.

**Comment by nhooyr** [comment]
Also, for the above code, should the prompt even be displayed? The string fits perfectly fine in the number of columns, there is no need for the prompt.

**Comment by justinmk** [comment]
I'm not sure this is actually a bug, though it could be mitigated by https://github.com/neovim/neovim/issues/1029.

> press enter or type anything to try and get rid of the prompt, but it never disappears.

The tabline and statusline are constantly being redrawn, so `Tabline()` is evaluated each time.

> should the prompt even be displayed? The string fits perfectly fine in the number of columns, there is no need for the prompt.

It's bounded by `SHOWCMD_COLS` if I'm not mistaken.
