### ISSUE TITLE
Filetype is not set in a terminal buffer

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#4465]
- Neovim version: NVIM 0.1.3-dev
- Operating system: OSX
- Terminal emulator: Terminal

### Actual behaviour
`:set ft` yields `filetype=`

### Expected behaviour
Filetype should be set to something reasonable so that plugins can hook into it.

I use the [numbers](https://github.com/myusuf3/numbers.vim) plugin, and they have an option for disabling line numbers on buffers with specific filetypes.  Because terminals don't have one, I can't fix it.

**Comment by nhooyr** [comment]
`set buftype` will be `terminal`.

**Comment by Shougo** [comment]
I think terminal buffer should not have the filetype.

**Comment by justinmk** [comment]
I agree, terminal is not a single filetype. Different filetypes may be applicable to different terminal contents--just like a normal buffer.

**Comment by TyOverby** [comment]
Thanks for comments, now I agree that the problem is with the plugin.
