### ISSUE TITLE
syntax off in init.vim doesn't working

### ISSUE THREAD

**Issue by iyee** [neovim/neovim#4467]
- Neovim version:
0.1.2
- Operating system:
OS X 10.11.3
- Terminal emulator:
iTerm 2

### Actual behaviour
both syntax on/off setting behave the same

### Expected behaviour
Don't hightlight syntax, just as Vim does

### Steps to reproduce
edit `~/.config/nvim/init.vim` , add `syntax off`

**Comment by wsdjeg** [comment]
please see help vim_diff

**Comment by iyee** [comment]
@wsdjeg Had read through vim_diff.txt but didn't find anything related, could you be more specific, please?

**Comment by fmoralesc** [comment]
syntax is enabled by default, but this still should work as expected (I thought we had covered this case when introducing this change). /cc @justinmk

**Comment by iyee** [comment]
@fmoralesc https://github.com/neovim/neovim/wiki/Following-HEAD shows on Feb 14th `syntax on` turns into a default value, but version `0.1.2` released on 12th according to https://github.com/neovim/neovim/releases , I'm confused.

**Comment by fmoralesc** [comment]
I can't reproduce in HEAD, so if possible I would suggest upgrading. Also take in consideration the syntax can get enabled even if you have `syntax off` in your init file if, for example, you put it before a `colorscheme` command. Also, some plugin managers enable syntax highlighting themselves, you need to make sure it is disabled after they work (for example, after `plug#end()` in the case of vim-plug).

**Comment by iyee** [comment]
@fmoralesc Yes, you're right. I was doing the copy&paste with organizing work from .vimrc to init.vim and  the `vim-go` plugin re-enabled syntax highlighting, reordering settings solves my problem, thanks a lot.

**Comment by gpanders** [comment]
@confuzeus Please provide a minimal working example that demonstrates the issue.


This correctly disables syntax highlighting, so the issue is likely something with your configuration.

```bash
echo 'syntax off' > test.vim
nvim --clean -u test.vim
```
