### ISSUE TITLE
Channel was closed by the client

### ISSUE THREAD

**Issue by gambledor** [neovim/neovim#4469]
- Neovim version: 0.1.3-355-g6b22a74
- Operating system: Mac OS X Yosemite
- Terminal emulator: Terminal
- Python version: 2.7.10
- Python neovim version: 0.1.5
- msgpack-python version: 0.4.7

### Actual behaviour
function provider#python#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
Failed to load python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.

**Comment by mhinz** [comment]
When? What about `~/.nvimlog` or the Python log file?

**Comment by gambledor** [comment]
here it is:
2016/03/18 15:15:43 [error @ forward_stderr:333] 16476 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/18 15:15:43 [error @ forward_stderr:333] 16476 - Channel 1 stderr:   File ".../Library/Python/2.7/lib/python/site-packages/neovim/__init__.py", line 66, in start_host
    host.start(plugins)
  File ".../Library/Python/2.7/lib/python/site-packages/neovim/plugin/host.py", line 47, in
2016/03/18 15:15:43 [error @ forward_stderr:333] 16476 - Channel 1 stderr:  start
    lambda: self._load(plugins))
  File ".../Library/Python/2.7/lib/python/site-packages/neovim/api/common.py", line 244, in run
    self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
2016/03/18 15:15:43 [error @ forward_stderr:333] 16476 - Channel 1 stderr: .../Library/Python/2.7/lib/python/site-packages/neovim/msgpack_rpc/session.py", line 118, in run

2016/03/18 15:15:43 [error @ forward_stderr:333] 16476 - Channel 1 stderr:     raise self._setup_exception
ImportError: No module named script_host

2016/03/18 15:15:43 [error @ call_set_error:743] 16476 - msgpack-rpc: Channel was closed by the client
2016/03/18 15:15:47 [info @ main:533] 16476 - Starting Neovim main loop.

**Comment by Shougo** [comment]
@gambledor Your neovim-python and neovim are latest version?
I think it seems be old.

**Comment by gambledor** [comment]
On El Capitan the only way I've succeeded to update neovim  is by  the following command 
`pip install --upgrade --force-reinstall neovim --user`
