### ISSUE TITLE
yaml syntax does not highlight negative numbers correctly

### ISSUE THREAD

**Issue by jleclanche** [neovim/neovim#4472]
- Neovim version: 0.1.2
- Operating system: Linux
- Terminal emulator: QTerminal

Negative numbers are not highlighted correctly in yaml files. For example:

```yaml
_obj:
  m_Shader: !pptr {file: 2, path: -7544049189052248055}
```

In this, `2` is highlighted correctly as a number, but `path` is highlighted as a string.

Interestingly, negative numbers with decimal points are highlighted correctly.

**Comment by mhinz** [comment]
It's the same in Vim. And it's not a string, it's `PlainScalar`.

Tell the maintainer or put `highlight link yamlPlainScalar yamlInteger` in your vimrc.

**Comment by jleclanche** [comment]
@mhinz ah ok. I don't believe this is the correct behaviour though. They're both serialized from ints and back into ints.

**Comment by mhinz** [comment]
Actually, ZyX seems to be the maintainer.

@ZyX-I ^

**Comment by jleclanche** [comment]
This is why this looks weird, btw:

![screen](https://cloud.githubusercontent.com/assets/235410/13896640/2ddd1ed8-ed9c-11e5-9d21-66b5d79282e1.png)
