### ISSUE TITLE
Cursor Shape doesn't change immediately

### ISSUE THREAD

**Issue by khamer** [neovim/neovim#4474]
- Neovim version: 0.1.3-dev
- Operating system: Ubuntu 15.10
- Terminal emulator: termite, roxterm

While this is not working properly in termite and roxterm, I tested and saw this work properly in both xterm and rxvt-unicode. I expect this affects all libvte terminals.

### Actual behaviour

I have `let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1` in .config/nvim/init.vim. It's pretty easy to get the cursor shape out of sync with the current mode in neovim.

### Expected behaviour

With  `$NVIM_TUI_ENABLE_CURSOR_SHAPE=1` set, it shouldn't be possible to get these out of sync.

### Steps to reproduce

Here's two different ways to duplicate this issue. The second issue can be easily duplicated while editing nearly any file, but here are instructions that don't require anything existing.

#### IBeam while in command mode

1. Run neovim.
2. Hit `i` then `<Escape>`.
3. Cursor is still an IBeam despite being in normal mode.

#### Block while in insert mode

1. Run neovim.
2. Hit `i`, enter some text (`test`), hit `<Escape>`, then `i` again.
3. Cursor is still a block despite being in insert mode.

**Comment by khamer** [comment]
As a workaround, this appears to work:

```vim
au InsertEnter,InsertChange * silent redraw!
au VimEnter,InsertLeave * silent redraw!
```

I suspect it has something to do with whether the terminal redraws when the cursor shape is changed.

**Comment by Shougo** [comment]
It seems libvte implementation problem.
You should report the problem to libvte developers.

**Comment by fmoralesc** [comment]
I think this was reported, there was even a PR about this: https://github.com/neovim/neovim/pull/3110 

I think vte 0.42.5 introduces some changes that will improve this, so I think we should just wait on that instead of introducing some ad hoc fix, backwards compatibility notwithstanding.

**Comment by Shougo** [comment]
Oh, nice.  I understand.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/3110 might still be worth it if we can do it for libvte older than 0.42.5.

**Comment by fmoralesc** [comment]
OK, I'll rebase just in case.

**Comment by fmoralesc** [comment]
BTW, I can confirm vte3 0.42.5 (it just landed in Arch) fixes this.

**Comment by teto** [comment]
Confirms it is fixed in termite as well with latest vte-ng.

**Comment by justinmk** [comment]
Mostly addressed externally.
