### ISSUE TITLE
Ctrl+Z doesn't work when nvim is running inside tmux

### ISSUE THREAD

**Issue by andrenho** [neovim/neovim#4475]
- Neovim version: 0.1.2
- Operating system: Arch Linux
- Terminal emulator: urxvt 9.22, tmux 2.1

### Actual behaviour

When pressing Ctrl+Z to suspend neovim, it doesn't do anything. This only happens when running inside tmux, when running directly in the terminal it does suspend.

### Expected behaviour

It should suspend (send nvim into background).

### Steps to reproduce

1. Run tmux.
2. Inside tmux, open nvim.
3. Press Ctrl+Z. Nothing happens.

**Comment by mseeber** [comment]
I do have basically the same configuration and can not reproduce this. Neither in st or urxvt. Does this also happen in other terminal emulators?

**Comment by andrenho** [comment]
I just found the problem: it was because I had the option 
`set -g default-terminal "putty-256color"`
in my tmux.conf. Removing it solved the problem.

It is strange, however, that I hadn't have the same problem with vim.

**Comment by crondog** [comment]
I think this is the same issue as https://github.com/neovim/neovim/issues/3100#issuecomment-158294410

**Comment by justinmk** [comment]
Agreed, thanks @crondog
