### ISSUE TITLE
opening socket in viml

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#4479]
Is it possible to open socket in plain vim without remote plugins?

I wan't to do something like this which is currently supported in vim with jobs and channels.

``` vim
function! s:Handler(handle, msg)
    echom a:handle
    echom a:msg
endfunction

let handle = ch_open('localhost:8000', {'mode': 'json'})
call ch_sendexpr(handle, 'hello', function('s:Handler'))
```

``` js
var net = require('net');
net.createServer(function(socket){
    socket.on('data', function(data){
        var request = JSON.parse(data);
        console.log('received', request);
        setTimeout(function () {
            var response = [
                request[0],
                request[1]
            ];
            console.log('sending', response);
            socket.write(JSON.stringify(response));
        }, 2000);
    });
}).listen(8000);
```

I'm currently writing an aync library so it works in both neovim and vim. https://github.com/prabirshrestha/async.vim
Currently I have jobs working but would like to make sockets work too.

**Comment by ZyX-I** [comment]
You need serverstart(). Even though it claims to open a TCP socket or a named pipe, I see it opening UNIX domain socket when running like `serverstart('/tmp/test.sock')`. Also note that Neovim *already* creates sockets.

Using TCP sockets is not secure, though documentation of `serverstart()` says that this is also an option.

In any case this will use usual msgpack-rpc API, there is no strict equivalent to `ch_open` I know about.

**Comment by tarruda** [comment]
If you want to communicate using a custom protocol, you can always use job
control with netcat

**Comment by justinmk** [comment]
> Is it possible to open socket in plain vim without remote pluginss?

Yes, but it requires speaking msgpack, not JSON as in your sample code. Or else use job control with netcat as @tarruda mentioned.

I am not sure we need the exact equivalent of Vim's API, but perhaps we should offer a JSON compat layer over the msgpack API, so that clients can have structure communication without installing any lib assuming JSON is ubiquitous).

**Comment by justinmk** [comment]
Merging this with #3119
