### ISSUE TITLE
Incorrect viml t_vb syntax highlighting (or missing documentation on a change)

### ISSUE THREAD

**Issue by michael-younkin** [neovim/neovim#4482]
- Neovim version: 0.1.3-dev
- Operating system: Ubuntu Linux
- Terminal emulator: gnome-terminal
### Actual behaviour

In my `.config/nvim/init.vim` file, `t_vb` in `set t_vb=` is highlighted as if it were an error.
### Expected behaviour

It should be highlighted like any other option.
### Steps to reproduce

`nvim .config/nvim/init.vim` and look at a line with `set t_vb=`. The `t_vb` of the line will be highlighted like an error.

**Comment by michael-younkin** [comment]
I found another option with a similar problem. In `if &shell =~# 'fish$'`, `shell` is highlighted as if it was an error.

**Comment by fmoralesc** [comment]
The highlighting of the `t_xx` options is intentional because they don't have any effect in nvim and we wanted to make that explicit to the user. 

I can reproduce the `shell` thing, but I don't have a clue how that came to pass. It seems to be detecting that as the `:shell` command, which was removed in nvim. But it is clearly an error for nvim to match it there.

**Comment by michael-younkin** [comment]
Gotcha. It seems like the `terminal-options` section of the help pages needs a lot of editing then. It would also be helpful if this was mentioned in `vim-differences`.

In the syntax file for vim, `shell` is not listed under `vimOnlyOption`. Maybe `vimOnlyCommand` isn't only matching commands? I'm not sure how to debug this because I don't know where the keyword lists are being generated. :(

**Comment by fmoralesc** [comment]
I think the `t_xx` options might be re-introduced in some form in the future, so this should be updated then. I imagine this is why the docs on `terminal-options` have not been updated. 

`vimOnlyCommand` in this case is contained in a `vimIsCommand`, and I suspect the definition for that is somewhat odd. In this case, I think  the `&` is not matched as anything (is skipped?), which causes the next token (the `s`) to trigger the `vimIsCommand` match:
``` vim
syn match vimIsCommand	"\<\h\w*\>"	contains=vimCommand,vimOnlyCommand
```

**Comment by michael-younkin** [comment]
Even if the `t_xx` options might change later, wouldn't it be helpful to have them listed in `vim-differences` now so people can see that something changed?
