### ISSUE TITLE
<Esc> ignored in Command-line mode if additional characters are typed quickly

### ISSUE THREAD

**Issue by michael-younkin** [neovim/neovim#4483]
- Neovim version: 0.1.3-dev
- Operating system: Ubuntu Linux
- Terminal emulator: fish

### Actual behaviour
If I press `:`, enter some text, press escape to exit, and then within 1-2 seconds press another character, my press of the escape key is ignored and additional key presses continue going to the command line.

### Expected behaviour
Pressing `<Esc>` while in command-line mode should immediately exit that mode (unless `<Esc>` is remapped).

### Steps to reproduce
1. Press `:`
2. Type any characters (except `<Esc>`)
3. Press `<Esc>` and then quickly press another character. You will still be in command-line mode when you should have transitioned back to normal mode.

**Comment by brettanomyces** [comment]
FWIW i am unable to reproduce this issue with the following setup

Neovim version: 0.1.3-350-gc94575f
Operating System: Xubuntu
Terminal emulator: fish

**Comment by justinmk** [comment]
If you're running tmux, see https://github.com/neovim/neovim/wiki/Troubleshooting#esc-in-tmux-or-gnu-screen-is-delayed

And in either case, see `:help 'timeout'`.

**Comment by michael-younkin** [comment]
Thanks!
