### ISSUE TITLE
[stty: stdin isn't a terminal]

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#4484]
- Neovim version: 0.1.2
- Operating system: OS X El Capitan
- Terminal emulator: Iterm2

### Actual behaviour
Airline shows [stty: stdin isn't a terminal] as the output of msgfmt (provided by po.vim).

### Expected behaviour
The right message

### Steps to reproduce
Install po.vim, install airline, open a po file.

The problem is neovim doesn't provide a real terminal to external programs, so some programs print a "stty: stdin isn't a terminal" error in the beginning of their output. I had this issue with jedy.vim too, I modified it to ignore this message by changing this line:

        let s:def_py = system('python -c '.shellescape('import sys; sys.stdout.write(str(sys.version_info[0]))'))

to this:

        let s:def_py = split(system('python -c '.shellescape('import sys; sys.stdout.write(str(sys.version_info[0]))')), "\n")[1]

In case of jedy I can ask its author to fix this, but in case of po.vim... well as far as I know last commit is for 2009. I think this can be solved by applying one of these solutions:
1. Provide a real terminal for external programs.
2. Ignore debug messages in case of external programs unless explicitly asked to not to.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1496

**Comment by sassanh** [comment]
@justinmk ok it was misleading, my problem was that `$TERM` variable wasn't "xterm-256" and there were problems with my terminfo settings, after setting it to "xterm-256" it got solved. All these months I was wondering how everyone is ok with such an annoying bug till someone told me he doesn't have this issue on his machine.

**Comment by justinmk** [comment]
What was your TERM ?

**Comment by sassanh** [comment]
It was "xterm-256-italic" but now I think the problem was with my terminfo build, because after rebuilding it even works with "xterm-256-italic".
