### ISSUE TITLE
Build errors when installing on OSX

### ISSUE THREAD

**Issue by addepar-andy** [neovim/neovim#4485]
- Neovim version: 0.1.2 (i think)
- Operating system: OSX (el cap)
- Terminal emulator: zsh

i run `brew install neovim` and it dies:

```
/bin/sh: line 1: 52139 Abort trap: 6           /tmp/neovim20160322-27850-1az1sx0/neovim-0.1.2/build/bin/nvim -u NONE -i NONE -es --headless -c helptags\ ++t\ . -c quit
make[2]: *** [runtime/doc/tags] Error 134
make[1]: *** [runtime/CMakeFiles/runtime.dir/all] Error 2
make: *** [all] Error 2
```

the `gist-log` is here: https://gist.github.com/anonymous/d544d0d30869fe758dd1

**Comment by zchee** [comment]
@addepar-andy This problem also occur use self-builded llvm-clang or apple-clang. but I do not know solution.
but, If you have time, try self-build neovim without Homebrew.
Maybe successful build.
See neivim Wiki.

@neovim-devepolers
If use not built-in clang (not Apple provide), this error occurs from a previous.

If you need more information for Segmentation fault(?), I can debug using the lldb.

**Comment by zchee** [comment]
@addepar-andy and, I don't remember much...
If you install `gettext` or `homebrew/dupes/libiconv` package use Homebrew, but does not link to `/usr/local/***` (`brew link ...`), also occur this error.

Please check it.

**Comment by kopischke** [comment]
I don't think this has anything to do with compilers or dependencies: `make` aborts because `nvim` returns a non-zero result when generating help tags, as far as I can tell from its error message (see the [GNU make error messages, for lack of a better word, documentation](https://www.gnu.org/software/make/manual/html_node/Error-Messages.html)). Now why it does do **that** is beyond me…

**Comment by zchee** [comment]
@kopischke but, It occurs even if self start the nvim (`./build/bin/nvim`)
The error code is the same.

In this case, `make` or `ninja` command can build(link) binary.
and execute nvim at the end of the Makefile. and generating the tag. (with `--headless` and etc...)
Error at this timing.

Also, If use Xcode built-in clang(all cmake settings is the same value), not occurred error.
I think the problem is in the compiler(or etc...)

**Comment by justinmk** [comment]
Usually this happens because of https://github.com/neovim/neovim/issues/4183#issuecomment-180969619

Though I've not seen it on OSX.

**Comment by retrone** [comment]
@justinmk Apple just released updated command line tools and new Xcode in last 2-3 days, if this is a new issue, maybe that is why it's happening now on Mac OS?

**Comment by iammerrick** [comment]
I'm seeing this on the updated command line tools / el cap.

**Comment by iammerrick** [comment]
Not sure if it is helpful but here are my corresponding gist-logs and version:

https://gist.github.com/d87175670ab8306c044d - 0.1.2

**Comment by interstellar716** [comment]
I have the exact same problem. Just installed a clean copy of OSX 10.11.4 and the latest version of Xcode (7.3 7D175).  
`brew install --HEAD neovim` works fine though.

**Comment by zchee** [comment]
@justinmk and all
I also reproduced latest `OS X 10.11.4 (15E65)` and `Xcode 7.3 (7D175)` with Homebrew.
It does not reproduce in the `ninja` self-build.

I will determine the cause later. Wait a moment, please.

**Comment by zchee** [comment]
I understand.
Homebrew 0.1.2 stable has not` _FORTIFY_SOURCE` check patch.
https://github.com/neovim/neovim/commit/e7615ddc22944504685d0ba3957626af9354148a 
Therefore, works fine in `--HEAD`.

So, We need add
`"-DCMAKE_C_FLAGS_RELWITHDEBINFO='-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1'"]`
```ruby
cmake_args = std_cmake_args + ["-DDEPS_PREFIX=../deps-build/usr",
                               "-DCMAKE_BUILD_TYPE=#{build_type}",
                               "-DCMAKE_C_FLAGS_RELWITHDEBINFO='-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1'"]
```

**Comment by justuswilhelm** [comment]
I've had the same error with a fresh install of OS X. Using `--HEAD` solved the issue. Thanks for the hint @zchee

**Comment by zchee** [comment]
@justinmk Solved by https://github.com/neovim/homebrew-neovim/pull/138

**Comment by interstellar716** [comment]
Thank you! It works perfectly fine now.
