### ISSUE TITLE
fzf + airline causes wait

### ISSUE THREAD

**Issue by teto** [neovim/neovim#4487]
- Neovim version: 
  NVIM v0.1.3-355-g6b22a74 Build type: Debug
- Operating system: Ubuntu 15.10
- Terminal emulator: termite
### Actual behaviour

I have this mapping: `nnoremap <leader>m :FzfMarks<CR>` that opens a buffer with a list of marks. My leader is space. In neovim when I press `<leader>m` the fzf buffer appears but is empty (https://transfer.sh/4L5L1/2016-03-23-165047-956x508-scrot.png) until I press an arrow key, for instance right, and then I see in the Fzf input field `[C` (for left key) or `[D` (for right key). If I press A/Z/E, nothing happens.
Then I delete the [C from the selection fields and can see my marks.
### Expected behaviour

I expect pressing `nnoremap <leader>m :FzfMarks<CR>` to display my marks directly with an empty input.
I have the expected behavior with vim in termite, or with neovim in urxvt. Only neovim+termite fails.

**Comment by wsdjeg** [comment]
I think it only happen in neovim ,as @Shougo says ,it is an issue about neovim.

here is same issue.
https://github.com/Shougo/unite.vim/issues/1121

**Comment by teto** [comment]
I am not sure I get the problem/solution.

I did some more tests, apparently, the hang appears when there is a pipe in the fzf command (I use fzf.vim plugin). For instance, the :Files command works;
`term://.//8901:/home/teto/.local/share/fzf/bin/fzf -m --prompt '/h/t/ns3off2'/ --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimHv0lo8/9[-] `
All the other fzf.vim commands exhibit the previously described behavior:
`
:Buffers
 term://.//8851:cat "/tmp/nvimHv0lo8/8"|/home/teto/.local/share/fzf/bin/fzf +m -x --tiebreak=index --ansi -d "\t" -n 2,1..2 --prompt="Buf> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimHv0lo8/7[-] 
:Colors
term://.//9016:cat "/tmp/nvimHv0lo8/11"|/home/teto/.local/share/fzf/bin/fzf +m --prompt="Colors> " > /tmp/nvimHv0lo8/10[-]
:Marks
:cat "/tmp/nvimHv0lo8/14"|/home/teto/.local/share/fzf/bin/fzf +m -x --ansi --tiebreak=index --header-lines 1 --tiebreak=begin --prompt "Marks> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimHv0lo8/13[-] 
:History
cat "/tmp/nvimHv0lo8/16"|/home/teto/.local/share/fzf/bin/fzf -m --prompt "Hist> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimHv0lo8/15[-]
:GitFiles
:git ls-tree --name-only -r HEAD|/home/teto/.local/share/fzf/bin/fzf -m --prompt "GitFiles> " --expect=ctrl-v,ctrl-x,ctrl-t > /tmp/nvimHv0lo8/17[-]`
The common aspect is the pipe in the command.

**Comment by autechy** [comment]
Having same issue, but it seems terminal doesn't matter as its happening in both termite and urxvt for me.

But i tried disabling some plugins one by one and found out that fzf buffer started to behave normally without vim-airline.

I have neither ideas why it is this way nor skills to narrow the problem down though.

**Comment by teto** [comment]
good catch !  Indeed disabling airline makes it work.

2016-04-10 22:43 GMT+02:00 Roman Serkov <notifications@github.com>:

**Comment by justinmk** [comment]
This is a fundamental problem of the way K_EVENT is implemented. See https://github.com/neovim/neovim/issues/3757

**Comment by autechy** [comment]
I did tinker a bit more with vim-airline config and figured a temporary workaround for those interested:

`let g:airline_section_b       = ""`

It does disable git branch indicator in though, keep that in mind.

**Comment by justinmk** [comment]
Gather various accounts of this issue, here's what we know currently:

 from  and https://github.com/junegunn/fzf/issues/556#issuecomment-214444885 : 

- [this system() call in airline](https://github.com/vim-airline/vim-airline/blob/985f3d3ecada29a037cac87299c61a0a5f71fe31/autoload/airline/extensions/branch.vim#L76) combined with fzf causes a wait
- https://github.com/neovim/neovim/issues/4487#issuecomment-202515290 suggests that pipes are a factor

So the circumstances causing this issue appear to be (1) a `system()` call invoked from the statusline combined with (2) a `:terminal` invocation involving pipes and (3) some unknown subset of fzf behavior.

If someone can provide steps to reproduce _without_ fzf and airline it's very likely this can be fixed.

**Comment by jez** [comment]
To add to @justinmk's comment above, the current workaround to disable the `system()` call from running is to disable vim-airline's branch extension:

```viml
let g:airline#extensions#branch#enabled = 0
```

**Comment by justinmk** [comment]
## Resolution/Summary

See https://github.com/neovim/neovim/issues/4487#issuecomment-222346850 .  Not actionable with current information. Cannot reproduce the issue. With the changes to job control since this was reported, maybe the behavior improved.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
