### ISSUE TITLE
Segfault when using setqflist

### ISSUE THREAD

**Issue by nerdrew** [neovim/neovim#4490]
- Neovim version: homebrew head

```
% vi --version
NVIM 0.1.3-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160322-96473-1896z33/build/config -I/tmp/neovim20160322-96473-1896z33/src -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/tmp/neovim20160322-96473-1896z33/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160322-96473-1896z33/build/src/nvim/auto -I/tmp/neovim20160322-96473-1896z33/build/include
```

- Operating system: 

```
% uname -a
Darwin hog.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

- Terminal emulator: iterm2

### Actual behaviour
Segfault

### Expected behaviour
Jump to the error

### Steps to reproduce
```
vi +:"call setqflist([], 'r', 'boom')" "+:caddexpr 'init.vim:1:a'" "+:caddexpr 'init.vim:2:a'" +:cope +:"call setqflist([], 'r', 'booma')" "+:caddexpr 'init.vim:3:a'" "+:caddexpr 'init.vim:4:a'" +:cn init.vim
```

Related PR: https://github.com/neovim/neovim/pull/4337
Related issue in neomake: https://github.com/benekastah/neomake/pull/316

cc @mhinz

**Comment by mhinz** [comment]
It's also reproducable with:

```
nvim +"caddexpr 'file:1:line'" +"call setqflist([], 'r')" +cope +"caddexpr 'file:1:line'" +"caddexpr 'file:1:line'"
```

And only when `'r'` is provided. If it's not given or `' '` or `'a'` it works as expected.

The segfault happens in `cn_next()` -> `qf_jump()`.

**Comment by Jun-T** [comment]
It seem the problem is that `qi->qf_lists[idx].qf_ptr` is not reset correctly in the function `qf_free()`, which is called from `setqflist([], 'r')`. At lines 1889 and 1890 of quickfix.c, only `qf_title` and `qf_index` are reset, while `qf_ptr` keeps pointing to the xfree()ed memory. Then this wrong value of `qi->qf_lists[idx].qf_ptr` is used at line 1307 in `qf_jump`(), and finally causes a segfalut at line 1330-1331 when accessing `qf_ptr->qf_valid`.

I've created a PR #4493.
