### ISSUE TITLE
Terminal: weird sequence entered into terminal when re-entering insert mode

### ISSUE THREAD

**Issue by songgao** [neovim/neovim#4494]
- Neovim version: NVIM 0.1.3-dev
- Operating system: OS X 10.11.3
- Terminal emulator: iTerm 2 Build 2.9.20160313

### Actual behaviour
In the terminal (`:term`), when entering insert mode from normal mode, weird sequence is entered. If not running any program, i.e., in `zsh`, it causes my shell to execute one of previous commands.

### Expected behaviour
Enter the terminal with original state before normal mode.

### Steps to reproduce
Please see [this asciinema](https://asciinema.org/a/35k4su67mrgnbg7d2suihiioe)

### Other notes
- nvim configuration: please see [here](https://github.com/songgao/dotfiles/blob/0f9feca6d5e1c4f7a0c4d0bcfefdd2ecd2196e95/confs/.config/nvim/init.vim)
- Could this be related to #3476 ?

**Comment by justinmk** [comment]
If you're not pasting (or sending bracketed-paste sequences in some other manner), it's not related to https://github.com/neovim/neovim/issues/3476.

> Please see this asciinema

Seems like a plugin is invoking a `<Plug>` mapping followed by a call to `feed_Popup`. Please bisect your configuration to find the minimal steps to reproduce this.

**Comment by songgao** [comment]
Thanks @justinmk . Seems to be caused by `vim-scripts/AutoComplPop` plugin. Following is the minimum config that can reproduce this:

```
call plug#begin('/tmp/plugged')
Plug 'vim-scripts/AutoComplPop' " autocomplpop
call plug#end()
```

Should I open a new issue here or submit one for AutoComplPop?

Thanks!

**Comment by justinmk** [comment]
You need to disable that plugin for terminal buffers. Ideally, AutoComplPop should do this out of the box--so, I suggest raising an issue there, if the author is willing. There's nothing Neovim can do about this.

**Comment by songgao** [comment]
Got you. Thanks @justinmk !
