### ISSUE TITLE
Yank to system clipboard (OSX) doesn't work

### ISSUE THREAD

**Issue by pippocode** [neovim/neovim#4496]
- Neovim version: 
NVIM v0.1.3-363-g2e2b575
Build type: Release

- Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 29 2015 15:04:50)
MacOS X (unix) version
Included patches: 1-769

- Operating system:
System Version:	OS X 10.11.4 (15E65)
Kernel Version:	Darwin 15.4.0

- Terminal emulator:
Terminal with and withot tmux

### Actual behaviour
When I copy from neovim (register + or * ) I have this message:
"clipboard: provider is not available"
Any other register (not system) works.

In vim    :echo has("clipboard")   returns 1
In nvim  :echo has("clipboard")   returns 0

Both :set clipboard?  returns  clipboard=unnamedplus

I installed pbcopy/pbpaste that, in neovim (:!pbcopy in visual-mode) cancel the row (but it puts the text into system clipboard as well).

I have Vim and Nvim builded fromc source.

No problem in copy from system and paste to nvim

### Expected behaviour
I can't put anything in the system clipboard from nvim

### Steps to reproduce
Write something in nveovim, then V"+y the message "clipboard: provider is not available" and with cmd-v nothing happens (or paste previous copied text from other app).

**Comment by mhinz** [comment]
What's the output of `:echo exectuable('pbcopy')`?

**Comment by pippocode** [comment]
The output is 1

**Comment by timfeirg** [comment]
I'm on `NVIM v0.1.3-364-gae68609`, `os x 10.11.4 (15E65)` and I can't reproduce.
how did you build neovim @pippocode ? if you didn't use homebrew, could you rebuild using `brew reinstall --HEAD neovim` and see if the problem still exists?

**Comment by pippocode** [comment]
Thank you for the feedback.
I reinstall with brew... but the problem still exist.

**Comment by MadCoder** [comment]
@pippocode your problem is tmux here, see e.g. http://www.economyofeffort.com/2013/07/29/reattach-to-user-namespace-the-fix-for-your-tmux-in-os-x-woes/

**Comment by MadCoder** [comment]
IOW this is not an nvim issue.

**Comment by pippocode** [comment]
Without tmux the problem is still present.

**Comment by pippocode** [comment]
Maybe this can help. Result of nvim --version:

nvimNVIM v0.1.3-363-g2e2b575
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/myhome/bin/neovim/build/config -I/Users/myhome/bin/neovim/src -I/Users/myhome/bin/neovim/.deps/usr/include -I/Users/myhome/bin/neovim/.deps/usr/include -I/Users/myhome/bin/neovim/.deps/usr/include/luajit-2.0 -I/Users/myhome/bin/neovim/.deps/usr/include -I/Users/myhome/bin/neovim/.deps/usr/include -I/Users/myhome/bin/neovim/.deps/usr/include -I/Users/myhome/bin/neovim/.deps/usr/include -I/sw/include -I/sw/include -I/Users/myhome/bin/neovim/build/src/nvim/auto -I/Users/myhome/bin/neovim/build/include

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

**Comment by timfeirg** [comment]
@pippocode is the problem showing only with your `.nvimrc`? then the problem is with your configurations.

your compilation is very different from mine, the compiler and flags aren't the same... using homebrew it's like this:

```shell
$ vi --version
NVIM v0.1.3-364-gae68609
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160325-93783-jmrp70/build/config -I/tmp/neovim20160325-93783-jmrp70/src -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/tmp/neovim20160325-93783-jmrp70/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160325-93783-jmrp70/build/src/nvim/auto -I/tmp/neovim20160325-93783-jmrp70/build/include
Compiled by timfeirg@timfeirg-mba-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

I don't know about the codebase at all, but it seems like the only difference now is in the build process, I think you can try remove all the neovim stuff and `$ brew reinstall --HEAD neovim`, it will build a dev neovim for you, specified by the [`formular`](https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb)

hope it helps

**Comment by pippocode** [comment]
Mmmmh... some problems here

`[100%] Generating doc/tags
cd /tmp/neovim20160329-6204-j19kvz/neovim-0.1.2/build/runtime/doc && /tmp/neovim20160329-6204-j19kvz/neovim-0.1.2/build/bin/nvim -u NONE -i NONE -es --headless -c helptags\ ++t\ . -c quit
/bin/sh: line 1: 30602 Abort trap: 6           /tmp/neovim20160329-6204-j19kvz/neovim-0.1.2/build/bin/nvim -u NONE -i NONE -es --headless -c helptags\ ++t\ . -c quit
make[2]: *** [runtime/doc/tags] Error 134
make[1]: *** [runtime/CMakeFiles/runtime.dir/all] Error 2
make: *** [all] Error 2
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  `https://github.com/neovim/homebrew-neovim/issues``


Should I remove MacPort?

**Comment by pippocode** [comment]
```
~  nvim --version                                                                                           
NVIM 0.1.3-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160329-89636-14q4y51/build/config -I/tmp/neovim20160329-89636-14q4y51/src -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/tmp/neovim20160329-89636-14q4y51/deps-build/usr/include -I/sw/include -I/usr/include -I/sw/include -I/tmp/neovim20160329-89636-14q4y51/build/src/nvim/auto -I/tmp/neovim20160329-89636-14q4y51/build/include
Compiled by user@comp.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```
Still broken :(

**Comment by timfeirg** [comment]
I'm clueless.

* so neovim can't use system clipboard but vim is all good?
* does this problem emerged only in recent versions? are there any old neovim release that works? if that's the case I think you could `git-bisect` and create a issue

**Comment by pippocode** [comment]
Yes, neovim can't use system clipboard but vim is all good.
I will try if there are old neovim releases that works.

Thank you for the feedback.

**Comment by pippocode** [comment]
Bisecting the repository I've not found a good commit (until 34dba3d, then I stop research). I think the issue is a system problem :(

Thank you all for the support.

**Comment by pippocode** [comment]
For a strange reason Neovim base himself on the untouchable vim installation in /usr/bin/vim path.

```
/usr/bin/vim --version                                                                      
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 28 2015 19:46:19)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path 
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv 
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent 
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape 
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype 
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn 
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs 
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary 
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```
This has neither -clipboard nor -lua option active and version is 7.3

```
> echo $VIM 
/Users/myuser/.vim
> echo $VIMRUNTIME                                                                            
/Applications/MacVim.app/Contents/Resources/vim/runtime
```

**Comment by fwalch** [comment]
From your last comment: So you have the `$VIM` and/or `$VIMRUNTIME` environment variables set to Vim paths? If yes, then Neovim can't find its runtime.

**Comment by pippocode** [comment]
THANK YOU! This solve the issue.
```
>echo $VIMRUNTIME                                                                          
/usr/local/share/nvim 
> echo $VIMRUNTIME
/usr/local/share/nvim/runtime
```
Now clipboard works!!!

**Comment by jamessan** [comment]
@pippocode You shouldn't be manually setting those environment variables.  Both Vim and Neovim set them appropriately internally.
