### ISSUE TITLE
Question: Is it possible to view images in neovim terminal?

### ISSUE THREAD

**Issue by ranranking** [neovim/neovim#4502]
Since some terminal emulators now have view inline images, for example iTerm2.9, is it possible for neovim running in these terminal emulators also view images in terminal mode?

**Comment by fmoralesc** [comment]
It is possible, but it is kind of glitchy:
![captura de pantalla de 2016-03-29 00-51-32](https://cloud.githubusercontent.com/assets/221465/14092605/767fa346-f548-11e5-9953-b19540615790.png)

**Comment by ranranking** [comment]
This is so cool! how did you achieve this?

**Comment by fmoralesc** [comment]
I didn't do anything, really. For this example, I just ran w3m inside gnome-terminal. The $TERM is `xterm-256color`, but that is common.

**Comment by fmoralesc** [comment]
`w3m` inside `:terminal` inside `nvim` inside `gnome-terminal`, I mean.

**Comment by ranranking** [comment]
oh, you are using w3m. In iTerm, there is a inline viewer called imgcat. It is not for online use. In terminal mode, I type imgcat, nothing shows up. This is how it looks like:
<img width="917" alt="screen shot 2016-03-28 at 5 06 38 pm" src="https://cloud.githubusercontent.com/assets/7812475/14092959/8db11c0c-f507-11e5-8b06-72d1f4b31905.png">

**Comment by fmoralesc** [comment]
Ah, right, that seems to use a different format altogether.

**Comment by justinmk** [comment]
This is covered in other issues.

**Comment by ranranking** [comment]
@justinmk hi, can you give me the link of the issues? I don't know which one you are talking

**Comment by justinmk** [comment]
@ranranking Here's the other issues I was thinking of:

- https://github.com/neovim/neovim/issues/4056#issuecomment-189534568
- https://github.com/neovim/neovim/issues/4349 (this is still open)

Please see the discussion in those issues for full background.
