### ISSUE TITLE
blockwise copy/paste doesn't work

### ISSUE THREAD

**Issue by MadCoder** [neovim/neovim#4503]
- Neovim version: NVIM 0.1.3-dev ae686092f807adbbb578b8ae2c2200654f9df8c1
- Operating system: OS X
- Terminal emulator: Apple Terminal

### Actual behaviour
start with this text, cursor top-left position
```
abcd
abcd
```

type `C-v` `j` `k` `y` `P`

result is:

```
ab
ab
abcd
abcd
```

### Expected behaviour
result should be:

```
ababcd
ababcd
```

**Comment by justinmk** [comment]
Did you search existing issues?

**Comment by MadCoder** [comment]
I confess I did not because it's a recent regression (I built HEAD last week or so and it worked), and I didn't see anything in the last page of issues

**Comment by MadCoder** [comment]
actually this is a straight dupe of #1822

**Comment by MadCoder** [comment]
actually this is not a dupe because #1822 didn't fix OS X, so I think this is just a follow up radar

**Comment by MadCoder** [comment]
but it really is #1822 after all, the github UI confuses the hell out of me
