### ISSUE TITLE
Artifacts in buffer

### ISSUE THREAD

**Issue by ibash** [neovim/neovim#4506]
- Neovim version: NVIM 0.1.2
- Operating system: OSX 10.11.14
- Terminal emulator: iTerm2

### Actual behaviour
Artifacts in buffers are shown until I move my cursor over them. For example, in the first screenshot see the "238m". After highlighting it with my cursor it goes away (in second screenshot). (Also note the "3" on the border between buffers, that's another artifact)

![screen shot 2016-03-30 at 10 31 27 am](https://cloud.githubusercontent.com/assets/204566/14151472/e4ddc960-f662-11e5-9d5c-76707a5f9541.png)
![screen shot 2016-03-30 at 10 31 39 am](https://cloud.githubusercontent.com/assets/204566/14151477/ec6e311a-f662-11e5-9b28-2383ed674e53.png)

### Expected behaviour
No artifacts

### Steps to reproduce
I don't have reliable reproduction steps. They seem to appear when splitting buffers a/ opening files with ctrl-p. If this is not a duplicate issue I can try to find reliable reproduction steps.

**Comment by justinmk** [comment]
Seems similar to https://github.com/neovim/neovim/issues/3875 and https://github.com/neovim/neovim/issues/3505

**Comment by ibash** [comment]
Interesting -- the other issues suggest that it was linux only, but I'm using osx.
