### ISSUE TITLE
Get Neovim to run on the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by philix** [neovim/neovim#4507]
I know. I know. Nothing launched yet.

Just wanted to have it here since this may change our perspective on building for Windows and Cygwin.

/cc @equalsraf 

http://techcrunch.com/2016/03/30/be-very-afraid-hell-has-frozen-over-bash-is-coming-to-windows-10/

**Comment by tarruda** [comment]
This is really cool, I had no idea that this project existed

**Comment by equalsraf** [comment]
Completely unexpected really. There are also some hints about updates to the console with VT100 compatibility and color codes.

**Comment by philix** [comment]
> This is really cool, I had no idea that this project existed

I just watched Scott Hanselman and Canonical employees demoing and chatting about it. It's Ubuntu minus the Linux kernel – syscalls are handled by the NT kernel.

You can access the Windows files through `/mnt/c/` and `/` refers to the `...AppData\Local\lxss\rootfs`.

> There are also some hints about updates to the console with VT100 compatibility and color codes.

Yes. They explicitly said there are people working to make sure Vim, tmux, emacs... work well in the terminal.

**Comment by Anachron** [comment]
I would say we should not focus on supporting neovim on the Windows System for Linux wrapper, but the other way around. 

We cannot do any fixes anyway, so I am not sure why this issue is open?

**Comment by philix** [comment]
@Anachron 

> ...since this may change our perspective on building for Windows and Cygwin.

**Comment by justinmk** [comment]
@philix we have an open issue for cygwin IIRC.

**Comment by aikeru** [comment]
For anyone interested I've spent a little time tracking this on the uservoice: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13390779-neovim-crashes-on-bash-on-windows

I've been adding a comment each time I try a new insider build and get the same result (which is every time).

**Comment by aikeru** [comment]
As I reported on the uservoice...

> Woohoo!!! With nvim --version reporting "NVIM 0.1.5-dev" and Windows 10 Insider Preview build 14366 this appears to be working now! (running nvim does not crash and opens to the info screen, basic editing works, haven't tested much beyond this yet).
> 
> Thanks you Microsoft!! :D
> 

:)

**Comment by timeyyy** [comment]
@aikeru you should close the issue at microsoft

**Comment by trusktr** [comment]
Just tried Neovim on WSL, and it failed with the stable ppa, but worked with the unstable ppa.

**Comment by gglanzani** [comment]
@trusktr If you compile it yourself, it works like a charm.

IO speed is, alas, still an issue with WSL so your experience might be degraded (from time to time).

**Comment by tdehaeze** [comment]
It's also working for me with the unstable ppa, awesome!!

**Comment by adamwallace** [comment]
the unstable ppa is the stable ppa

**Comment by timnolte** [comment]
@adamwallace great to hear.
