### ISSUE TITLE
Building from source (make) fails on Linux

### ISSUE THREAD

**Issue by tswilkinson** [neovim/neovim#4511]
- Neovim version: newest (latest git commit)
- Operating system: Debian Jessie
- Terminal emulator: none

### Actual behaviour
`> make`
`...`
`[ 94%] Generating usr/bin/busted`

`Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec`
`CMakeFiles/busted.dir/build.make:51: recipe for target 'usr/bin/busted' failed`
### Expected behaviour
Successful build.
### Steps to reproduce
I get this same error message every time I run make, even on a completely fresh machine with nothing else installed.  [NOTE: I don't know whether this is relevant: I am using [crouton](https://github.com/dnschneid/crouton/), which may mean that I am missing some system tools or something.  I really have no idea what effect this has.]

**Comment by timfeirg** [comment]
>Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec
CMakeFiles/busted.dir/build.make:51: recipe for target 'usr/bin/busted' failed

it's probably a network issue, the build fails because it can't download https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec.
