### ISSUE TITLE
Cannot remap Ctrl-H when using tmux

### ISSUE THREAD

**Issue by alexoj** [neovim/neovim#4512]
- Neovim version: `NVIM v0.1.3-368-g4b8f273` (current master)
- Libtermkey version: `416adba` (current master)
- Operating system: Arch Linux
- Terminal emulator: tmux inside urxvt (`TERM=screen-256color`)

### Actual behaviour
C-h gets aliased to backspace, mapping `<C-h>` does nothing and mapping `<BS>` changes the behavior of both backspace and C-h.
### Expected behaviour
Can remap both keys independently.
### Steps to reproduce
1. Inside a terminal, run tmux.
2. Verify that the TERM environment variable gets changed to `screen` or `screen-256color` (default settings)
3. Run `nvim -u NONE`, and source the following:
```
set nocp
map <c-h> :echo "control h"<cr>
map <bs> :echo "bs"<cr>
```
4. Press ctrl-h, `bs` is logged, press backspace, `bs` is logged.

The same sequence works as expected in Vim, as well as in Neovim if tmux is not used.

I've dug around a bit and I suspect the problem is that in screen's terminfo, `^H` is set as `cub1` (which I guess is backspace) and it gets interpreted that way, but I'm at a loss as to how to solve it.

**Comment by brcolow** [comment]
See #2048.

**Comment by alexoj** [comment]
Sorry, didn't see it was duplicated.
