### ISSUE TITLE
:edit without resetting view? Is this possible?

### ISSUE THREAD

**Issue by zhimsel** [neovim/neovim#4513]
- Neovim version: 0.1.2
- Operating system: OSX 10.10
- Terminal emulator: iTerm2

### Actual behaviour
1. open file
2. do something that affects the view, like creating a fold (`zfj`)
3. reload the file from disk (`:edit`)
4. view is reset (fold is destroyed)

### Expected behaviour
When reloading a file from disk, the view should be preserved. Is that even possible with how neovim handles views? Having your fold state, scroll position, etc be reset when reloading the file (say, by doing a [`HunkRevert`](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter.vim#L219) from `vim-gitgutter`) is very inconvenient.

**Comment by kopischke** [comment]
Shameless plug: until this is possible in Vim or Neovim (which would be helpful, I agree) you can use my [vim-stay](https://github.com/kopischke/vim-stay) plugin for that.

**Comment by zhimsel** [comment]
@kopischke unfortunately, `vim-stay` interferes with `fzf`, which is way more useful to me: https://github.com/zhimsel/dotfiles/commit/611ba360c81a2ec145c54e0955b95714a313009b

**Comment by kopischke** [comment]
@zhimsel not off the top of my head, no, considering this is the first time I hear of it. I am bit surprised, TBH, to hear of such a conflict, as *stay* is a glorified `mkview` / `loadview` wrapper, but I’d love to investigate, especially as I have gotten [another rather puzzling report](https://github.com/kopischke/vim-stay/issues/24). Could you [create an issue on the stay repo](https://github.com/kopischke/vim-stay/issues) consolidating the info strewn over the *fzf* issues?

**Comment by kopischke** [comment]
Semi-OT: this is a _bona fide_ bug of _vim-stay_, tracked in https://github.com/kopischke/vim-stay/issues/27. Will be solved in the next release, so my recommendation to OP still stands.

**Comment by zhimsel** [comment]
Issue in kopischke/vim-stay#27 was fixed. Closing.
