### ISSUE TITLE
In :terminal pressing HOME, END, CTRL+<Left/Right> keys don't move the cursor when using zsh autosuggestions

### ISSUE THREAD

**Issue by wleese** [neovim/neovim#4514]
- Neovim version: v0.1.3-368-g4b8f273
- Operating system: Ubuntu 16.04
- Terminal emulator: terminator (but tested various others)

### Actual behaviour
In :terminal, HOME, END, CTRL+Left/Right keys doesn't move the cursor in bash or zsh shells

### Expected behaviour
Jump to beginning of the line

### Steps to reproduce
Set your default shell to zsh
install oh-my-zsh
..from their github: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone git://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
put this in .zshrc:
```
export ZSH=/home/wleese/.oh-my-zsh # <--- username, not sure if ~ is okay
source $ZSH/oh-my-zsh.sh
plugins=(git last-working-dir compleat vagrant web-search wd)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=250'
zle-line-init() {
  zle autosuggest-start
}                                                                                                                
zle -N zle-line-init
```
nvim -u NONE -N 
:terminal
// (term://.//8642:/bin/zsh)
abc<home>
// nothing happens for HOME and END. For  CTRL+Left/Right I get after typing "abc":
// abc<7fffab03><7fffaa03>

**Comment by fmoralesc** [comment]
I can't reproduce the behavior for HOME and END, but I can for the CTRL-x combos.

**Comment by wleese** [comment]
I read somewhere that pressing ctrl+v in a shell and then a second key will display some kind of key code. So here goes:

in nvim terminal home and end:
^[[H ^[[F

In a normal terminal where things work:
^[OH ^[OF

**Comment by wsdjeg** [comment]
@fmoralesc In neovim'terminal buffer, HOME and END works well for me ,and I never use ctrl+HOME or ctrl+END ,because in terminal buffer we edit only in one line.and I have try with `ctrl+v ctrl+ HOME` or `ctrl+v ctrl+END` both show me `^C`,same as in termite.

**Comment by wleese** [comment]
I just downloaded a Ubuntu 15.04 VM which doesn't experience this problem. I'll try to bring it as close as possible to the system on which I was experiencing issues and report back.

**Comment by wsdjeg** [comment]
16.04 has a lot issue about neovim,I have open some issue about it.but it is not due to neovim itself,so these issue has been closed.if you are using ubuntu,maybe 15.10is the best.15.04 has some bugs about mysql,and been fixed in 15.10

**Comment by wsdjeg** [comment]
if you want to use `CTRL+<Left/Right>` move cursor between words.you need set some thing in ～/.inputrc.

please see bash in arch wiki

**Comment by DarkDefender** [comment]
I'm running gentoo and I do not have this problem. Home, End and Ctrl+arrow keys works as expected in neovim terminal.

**Comment by justinmk** [comment]
Almost certainly TERM is not correct.

**Comment by wleese** [comment]
Nope, not a problem with term. In both the failure situation and working situation TERM is set the same.

I found the problem with this in my .zshrc configuration:

```
source ~/.zsh/zsh-autosuggestions/autosuggestions.zsh
AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=250'
# Enable autosuggestions automatically.
zle-line-init() {
  zle autosuggest-start
}                                                                                                                
zle -N zle-line-init
```

What this usually does is while I'm typing, suggest commands from history inline. This somehow breaks neovim's handling of HOME and END keys.

**Comment by wleese** [comment]
I've solved this for my old machine by updating the plugin and removing:

```
zle-line-init() {
  zle autosuggest-start
}                                                                                                                
zle -N zle-line-init
```
..which no longer worked with the latest version of the plugin anyway.

**Comment by justinmk** [comment]
So can we close this? "Install OMZ" is not a reduced repro.

**Comment by wleese** [comment]
Sure thing.

**Comment by wsdjeg** [comment]
@wleese if you like this feature,you can put some this in to you inputrc
```
~/.inputrc

"\eOd": backward-word
"\eOc": forward-word
```

see [link](https://wiki.archlinux.org/index.php/Bash)

**Comment by wleese** [comment]
@wsdjeg doesn't work - I guess that's a new bug :)
