### ISSUE TITLE
BufReadPre is not invoked for external resources in :tabe

### ISSUE THREAD

**Issue by yan12125** [neovim/neovim#4516]
- Neovim version: Both 0.1.2-1 from Arch Linux official package [1] and neovim-git 0.1.2.r373.gb8643f6-1 from AUR [2] are affected.
- Operating system: Arch Linux x86_64 up-to-date
- Terminal emulator: xfce4-terminal 0.6.3-2

[1] https://www.archlinux.org/packages/community/x86_64/neovim/
[2] https://aur.archlinux.org/packages/neovim-git/
### Steps to reproduce
1. Write a simple test-vimrc: `autocmd BufReadPre * !ls`
2. `nvim -u ./test-vimrc`
3. `:tabe ./test-vimrc`
4. `:tabe http://httpbin.org/headers`
### Actual behaviour

Only the first `:tabe` call (step 3) invokes `!ls`. The second `:tabe` does nothing.
### Expected behaviour

`!ls` is executed in both `:tabe` calls
### Notes
- This bug is originally reported at https://github.com/Valloric/YouCompleteMe/issues/2053, and YCM developers believe it's a Vim bug.
- The same bug occurs on legacy vim as well. I don't use legacy vim anymore, so I just report it here.

**Comment by justinmk** [comment]
Works on master (`0.2`).

Note: `http://` files won't be handled unless plugins are loaded, it requires netrw.
