### ISSUE TITLE
ctrlp-cmatcher no longer works

### ISSUE THREAD

**Issue by thegranddesign** [neovim/neovim#4518]
- Neovim version: v0.1.3-366-ga9e0d73 
- Operating system: OSX 10.11.4
- Terminal emulator: iTerm2 w/ Tmux

Based on the talk you all have of keeping compatibility with vim (at least for now) I thought you all would like to know that the [ctrlp-cmatcher](https://github.com/JazzCore/ctrlp-cmatcher) has stopped working.

I'm not sure exactly what's causing it, or if it's even an issue with Neovim, but I thought you all would like to know.  Basically it works on initial load, but any attempt to search fails.

If this isn't something that you all are interested in, feel free to close it.

There's no ability to create issues on the matcher's repo so I'm copying the maintainer here as well.
/cc @JazzCore

**Comment by ZyX-I** [comment]
Can you show how exactly “any attempt to search fails”?

Also why you say that “there’s no ability to create issues on the matcher’s repo” if there is JazzCore/ctrlp-cmatcher#35 and I have “New issue” button working?

**Comment by thegranddesign** [comment]
@ZyX-I don't know how I missed that hahahaha I'll close this in favor of the other issue.
