### ISSUE TITLE
vim-patch:7.4.746 causing slowdown in tag jumps

### ISSUE THREAD

**Issue by bernastoc** [neovim/neovim#4528]
- Neovim version: v0.1.3-378-g28d3def
- Operating system: centos 6.5
- Terminal emulator: gnome-terminal / makes no difference
### Actual behaviour

CTRL-] jumps to tag under cursor with 1-2 second delay
### Expected behaviour

Prior to vim-patch:7.4.746 (commit 73234bfec6f9aa1741b30d19817284cd26392376) tag jumps were instantaneous.
### Steps to reproduce

in init.vim:
set ignorecase
set smartcase

Build ctags with following command: 
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .
set ic (ignore case)
open file and use CTRL-] to jump to a tag
revert commit 73234bfec6f9aa and compare.

Edit: I figured out that I can mitigate the problem by forcing tag search to match case by setting the following in init.vim:
set tagcase=match
Otherwise tag-matching uses the same case-matching settings as search. I'm using ignorecase with smartcase, which is more CPU intensive. Obviously, this means that tag search will be less functional but it's a decent workaround IMO.

**Comment by ezuk** [comment]
Hi there; sorry for reviving this, but this issue is killing my use of Neovim, and actually only appeared in nvim 0.2. Is there an update on this, or any recommendations on how I can make ctags usable again?

**Comment by jamessan** [comment]
@ezuk, the referenced commit has been in Neovim for months, so if you're just now seeing an issue, it likely isn't related to that commit.

Can you bisect to see what commit actually affected the performance for you?

Note also that tag lookup is exponential with respect to the number of tags in the tag file.  I have a PR (vim/vim#1046) open to fix that, which seems to be making it closer to getting applied upstream.

**Comment by ezuk** [comment]
Thank you for the super-fast response, @jamessan! While bisecting isn't an option for me, the issue came up after upgrading to 0.2 from the prev milestone. 

I was now able to resolve it by adding this to my vimrc:

```
set tags=tags
set path=.
```

**Comment by bernastoc** [comment]
Not that you need it, but I modified the original comment to include a workaround.

**Comment by ezuk** [comment]
Thanks @bernastoc! I've added that to my vimrc as well, just for good measure. 🎉

**Comment by jamessan** [comment]
The tag lookup improvements I mentioned [earlier] have been merged.  Can you see if this improves the performance for your use case?

[earlier]: https://github.com/neovim/neovim/issues/4528#issuecomment-262315207

**Comment by jamessan** [comment]
Closing since all the tag performance patches have been merged.  Please reopen if you are still having problems.
