### ISSUE TITLE
Python 2 library YouCompleteMe fails to load

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#4529]
- Neovim version: NVIM 0.1.3-dev
- Operating system: OSX
- Terminal emulator: Terminal

After following the instructions from `:help nvim-python`, I attempted to install [valloric/YouCompleteMe](https://github.com/valloric/YouCompleteMe) but hit this error.

```
Error detected while processing function provider#python#Call:
line   18:
no request handler registered for "python_execute"
Error detected while processing function youcompleteme#Enable..<SNR>93_SetUpPython..provider#python#Call:
line   18:
no request handler registered for "python_execute"
```

**Comment by renstrom** [comment]
Check `~/.nvimlog`, it usually contains hints as to why Python isn't loaded properly.

**Comment by bfredl** [comment]
make sure to use recent neovim master (if you don't already) as well as latest version of the neovim pip package.

**Comment by NoctuaNivalis** [comment]
I've had the same issue since updating the neovim pip packages this morning.

- Neovim version: NVIM 0.1.2
- Operating system: Void Linux
- Terminal emulator: urxvt
- `pip show neovim`:```Metadata-Version: 1.1
Name: neovim
Version: 0.1.7
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
License: Apache
Location: /usr/lib/python2.7/site-packages
Requires: msgpack-python, trollius, greenlet
Classifiers:```

**Comment by TyOverby** [comment]
@bfredl Thanks!  Updating (even from an install only a week old) seems to have fixed it!

**Comment by iolloyd** [comment]
I still have the same issue
- Neovim version NVIM 0.1.2
- OS: Mac os x
- Terminal: Iterm 2
- `pip show neovim`:
---
Metadata-Version: 2.0
Name: neovim
Version: 0.1.7
Summary: Python client to neovim
Home-page: http://github.com/neovim/python-client
Author: Thiago de Arruda
Author-email: tpadilha84@gmail.com
Installer: pip
License: Apache
Location: /Users/lloyd/.pyenv/versions/ccp/lib/python2.7/site-packages
Requires: trollius, msgpack-python, greenlet
Classifiers:

**Comment by bfredl** [comment]
You need nvim 0.1.3 for the latest python client.
