### ISSUE TITLE
[Feature Request] Allow unmapping of all default bindings

### ISSUE THREAD

**Issue by Anachron** [neovim/neovim#4532]
- Neovim version: Not relevant
- Operating system: Linux (but also not relevant)
- Terminal emulator: Termite (still not relevant)

### Actual behaviour
I want to overwrite all default mappings with custom ones.
Use-Case: My keyboard is german and a lot of keys simply don't make any sense.
Instead of writing a big list of all the things that changed, I would rather have a list with all the mappings.

Right now I would have to overwrite every single used mappings with noop first.

### Expected behaviour
I would like to have a unmapping-function so in my vimrc-file I can redo all mappings again and this will make things more clear for me.

### Steps to reproduce
Open neovim and realize there is no unmap command for default mappings.

**Comment by fmoralesc** [comment]
Can this be emulated with a 'keymap' (see `:help mbyte-keymap`)?

**Comment by Anachron** [comment]
I think you mean the keymap option in http://vimdoc.sourceforge.net/htmldoc/mbyte.html?
Well that would be possible, but I also don't think some mappings make sense by default. 

Example: I don't like `hjkl` and I would rather have them as `wasd`.

**Comment by fmoralesc** [comment]
You can create a keymap, and then also create the new extra mappings.

**Comment by Anachron** [comment]
Sorry, I don't really understand? If I create my mbyte-keymap, the default keymappings will be cleared?
The thing is: There are some default bindings that are in my way.

**Comment by fmoralesc** [comment]
The keymap translates all the key presses, so I can imagine you can reorder everything to your liking.

**Comment by Anachron** [comment]
There are some features that I don't need so I don't want to have that keybinding. 
Like disabling arrow-keys and similiar stuff. 

I think it's just much more clear and clean to undo all mappings and just list those that I want to use. 
Besides, there are issues if you don't unmap the defaults that it will delay some keys that are already bound.

Example: I bind g but gg is already bound, so the g motion will be delayed.

**Comment by justinmk** [comment]
> I think it's just much more clear and clean to undo all mappings and just list those that I want to use. 

That's not a strong case for changing the entire foundation of the current system. 

`'keymap'` and `'langmap'` exist for your purpose. The "default bindings" are not bindings. They should be regarded as function names. Changing the name of a function doesn't make sense. Calling the function from an alias _does_ make sense.

**Comment by dirkson** [comment]
I also want this.

**Comment by CoreyCole** [comment]
Anyone arriving from google: Disable *specific* keymaps
```lua
vim.cmd("map <S-Down> <Nop>")
vim.cmd("map <S-Up> <Nop>")
```
