### ISSUE TITLE
Substitutions should be confined to the highlighted area in Visual Block mode

### ISSUE THREAD

**Issue by RomanHargrave** [neovim/neovim#4534]
- Neovim version: 0.1.3-dev
- Operating system: Debian Testing GNU/Linux 4.4
- Terminal emulator: Terminator/Guake (Gnome Terminal Derivatives)

### Actual behaviour

Applying a substitution to a Visual Block region replaces things outside the Visual Block, as if it were performed in Visual Line mode with the same start and end-points.

### Expected behaviour

The substitution should only apply within the visual block.

### Steps to reproduce

Apply a substitution within a visual block

**Comment by ZyX-I** [comment]
There is no way to “apply a substitution to a visual block”. You may apply substitution to a range of lines and that range of lines is exactly what appears when you press `:` in visual mode. There is a way to use `\%V` zero-width atom in a regular expression to limit substitution to a visual block only.

This was already discussed somewhere in vim-dev, but there is no easy way to fix this problem with the current code base and problem is not too problematic to be worth the hassle.

**Comment by ZyX-I** [comment]
(It is also not impossible to construct a plugin which will take visual block, put it into temporary buffer, apply substitution, save results and close buffer, replace the visual area with the results.)
