### ISSUE TITLE
FileType autocmds executed on every buffer change

### ISSUE THREAD

**Issue by jdpopkin** [neovim/neovim#4536]
- Neovim version: NVIM 0.1.2
- Operating system: OSX 10.11.1
- Terminal emulator: Terminal.app
### Actual behaviour

Neovim executes FileType autocmds every time I enter a buffer with the given filetype.
### Expected behaviour

Vim (7.4) executes FileType autocmds when a buffer's filetype is first determined (by opening the file, setting filetype, etc.).
### Steps to reproduce

`nvim`, then:

```
:e tmp
:augroup foo
:au foo FileType ruby :execute "normal! ggOhello"
:e tmp.rb
:w 
:b # 
:b # 
```

In Neovim, if you follow these steps, you end up with a file `tmp.rb` with the text

```
hello
hello
```

In Vim, you end up with this in `tmp.rb`:

```
hello
```

Is this an intentional change from Vim? I haven't been able to find find documentation of such a change (I tried searching the git log --pretty=fuller for [fF]ile[tT]ype). If so, I find it counterintuitive - the filetype hasn't changed, only the buffer has.

This affects a couple of vim plugins, like vim-orgmode (see https://github.com/jceb/vim-orgmode/blob/master/ftplugin/orgmode/plugins/TagsProperties.py#L201 - this bug causes a fairly serious performance problem where new InsertLeave listeners are attached every time the user enters a `.org` buffer). I know it's probably best practice to set a buffer-local variable to avoid running code like this more than once (like in https://github.com/neovim/neovim/blob/2e2b5759cf806b5ca1d4e94316d40acb17878ae2/runtime/ftplugin/sass.vim#L7), but I don't want to read through all my plugins to find and fix the FileType autocmds.

**Comment by justinmk** [comment]
Steps are missing `:augroup END`. In that case issue is not present.

Vim has same behavior.

**Comment by jdpopkin** [comment]
Are you reproducing those same steps I posted and observing the same behavior in both Vim and Neovim? When you do so, do you see another "hello" at the top of the `tmp.rb` buffer each time you `:b #` between buffers? I understand that it was an oversight to leave out `:augroup END`, but this is just a simple test case for a real-world problem in a real-world plugin caused by a difference in behavior between (my version of) Vim and (my version of) Neovim.

Nonetheless, when I do:

    :e tmp
    :augroup foo
    :au foo FileType ruby :execute "normal! ggOhello"
    :augroup END
    :e tmp.rb
    :w 
    :b # 
    :b # 

I have two hellos in `tmp.rb`.

Which versions of Vim/Neovim are you using?

**Comment by justinmk** [comment]
This happens with `nvim -u NONE` ?

**Comment by jdpopkin** [comment]
No, because `nvim -u NONE` implies no `filetype plugin on`, which implies filetype doesn't get set _ever_. 

But if I run `nvim -u NONE` then call `:filetype plugin on` before running those steps, I get the same result (two `hello`s).

**Comment by jdpopkin** [comment]
`shoug1` in IRC reported that they see this same behavior in Vim 7.4.1716. I'll try upgrading Vim to confirm that it's an upstream problem.

**Comment by justinmk** [comment]
I can reproduce in `NVIM v0.1.3-350-gc94575f` and Vim 7.4.52.

In both cases, it only happens once. In both cases it does _not_ happen if `'hidden'` is reset (`:set nohidden`). So this is related to `'hidden'`.

**Comment by justinmk** [comment]
@jdpopkin Can I assume you will followup with Vim about this?

**Comment by jdpopkin** [comment]
I'll do it tonight.

**Comment by justinmk** [comment]
As explained in https://github.com/vim/vim/issues/738 , this is by design. The entire purpose of 'hidden' is to keep files in memory. If you use 'nohidden' then you are by definition asking for the file to be unloaded and reloaded.

> If the `hidden` option isn't set, the buffer is completly deleted from vim when you switch to another buffer and once you do `:b #` to reopen it, Filetype detection will kick in again, since this is like completly new loading of the buffer. So this is expected behaviour.
