### ISSUE TITLE
vim-patch.sh errors

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#4539]
- Neovim version: https://github.com/neovim/neovim/commit/90e8bdc8985c19ea22c13020359b222c0bcb8ef0

Trying to use the script gives the following 2 problems:

```
./scripts/vim-patch.sh-l
Updating Vim sources in '/home/pips/Devel/neovim/neovim/.vim-src'.
Already up-to-date.
✔ Updated Vim sources.

Vim patches missing from Neovim:
fatal: ambiguous argument 'v7.4.602..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

<Instructions snipped>
```

```

pips@Rambazamba:~/Devel/neovim/neovim$./scripts/vim-patch.sh -s
vim-patch.sh: 'hub' not found in PATH or not executable.
```

I'm on gentoo linux, my git is version 2.7.3. I do indeed not have an executable called hub, but I don't know where I'd get that (not a google-friendly name). I'd welcome any pointers (is that the right place to ask anyways?)!

**Comment by wlhlm** [comment]
https://github.com/github/hub

**Comment by KillTheMule** [comment]
Figures... thanks! I installed that, and I can only assume it fixes the 2nd error. The first still persists though, even after aliasing 'git' to 'hub' as recommended by the 'hub' page.

**Comment by justinmk** [comment]
I think this is because we only fetch a certain depth, yet we're missing patches too far back.
