### ISSUE TITLE
NVIM_TUI_ENABLE_CURSOR_SHAPE not respected when using neovim within tmux

### ISSUE THREAD

**Issue by megalithic** [neovim/neovim#4541]
- Neovim version: NVIM v0.1.3-383-g90e8bdc
- Operating system/version: OS X 10.11.4
- Terminal name/version: iTerm2 Build 2.9.20160405-nightly
- Tmux version: 2.1
- `$TERM`: /usr/local/bin/zsh

### Actual behaviour

When using `nvim` within a tmux session, cursor shape changes are not recognized. Though, when using `nvim` outside of a tmux session, cursor shape changes ARE recognized. This did work correctly for both tmux sessions, as well as outside of tmux, one to two months ago (I don't have a build number to confirm, unfortunately).

### Expected behaviour

When flipping between insert and command mode, inside AND outside of a tmux session, the setting, `let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1`, should permit the cursor shape to change between vertical bar and block, respectively.

### Steps to reproduce using `nvim -u NONE`

1. `tmux`
1. `nvim -u NONE`
1. press `i` key
1. *incorrect behavior:* cursor shape stays as a block shape
1. press `ESC` key
1. cursor shape stays as a block shape
1. `:q!`
1. `exit` to leave tmux
1. `nvim -u NONE`
1. press `i` key
1. *correct/expected behavior:* cursor shape changes to a vertical bar
1. press `ESC` key
1. *correct/expected behavior:* cursor shape changes back to a block shape

As mentioned, this behavior used to be correct in a previous version of neovim, but I wasn't able to confirm the build number, nor have gone through a `git bisect` to narrow down the commit that introduced the unexpected behavior.

**Comment by megalithic** [comment]
Self-closing this issue; a gentleman in #neovim found the fix, (his dotfiles commit with the fix): https://github.com/nathanaelkane/dotfiles/commit/9607d826b9d408595de2e3fe7de0abec1e94fa86.

Adding `set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'` to tmux.conf fixes it. 

Will report back if something about this changes.

**Comment by thrawny** [comment]
Neovim version: NVIM v0.1.3 (via homebrew)
Operating system/version: OS X 10.11.4
Terminal name/version: iTerm2 Build 2.9.20160313
Tmux version: 2.1
$TERM: /usr/local/bin/zsh

I added the fix to my .tmux.conf
`set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'`

However now when I type `i` inside neovim I get the following inside the buffer: `\eE[5 q`
And if I press ESC: `\eE[2 q`

And the cursor is always a block. Everything works fine outside tmux.

Any idea what is causing this?
