### ISSUE TITLE
Terminal disappears after repeated :bnext/:bprev

### ISSUE THREAD

**Issue by eblade** [neovim/neovim#4544]
- Neovim version: Master/v0.1.3
- [ ] Vim behaves differently?
    - Vim version:
- Operating system/version: Fedora 23 / Linux jne 4.4.6-300.fc23.x86_64 #1 SMP Wed Mar 16 22:10:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version: gnome-terminal 3.18.3
- `$TERM`: xterm-256color

### Actual behaviour

Nvim looses the term buffer when switching buffers with `:bnext`/`:bprev` commands.

This stopped working very recently, around April 6th, not sure exactly what commit. 

### Expected behaviour

The term buffer should not be lost.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE`
2. `:term`
3. `<C-\><C-n> to leave `TERMINAL` mode
4. `:edit test` to get a new buffer
5. `:bprev` to move back to term
6. `:bnext` to move to regular buffer "test"
7. `:bprev` to  move back to term again

Here the term buffer has disappeared. `:ls` does not show it. Any combination of `:bnext` and `:bprev` repeated seems to cause the issue.

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/issues/3340 and https://github.com/neovim/neovim/issues/4420
