### ISSUE TITLE
filetype plugin indent on behaviour(python files)

### ISSUE THREAD

**Issue by monkoose** [neovim/neovim#4545]
- Neovim version: v.0.1.2
- [ ] Vim behaves differently? Yes
    - Vim version: 7.4
- Operating system/version: ArchLinux 4.4.5-1-ARCH SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
- Terminal name/version: xfce4-terminal
- `$TERM`: xterm

### Actual behaviour
If filetype plugin indent is on, then in python files(can't reproduce it in any other filetypes) when you press `<CR>` inside brackets, braces and parentheses it jumps to a new line with 2 tabs(8 spaces)
before:
`print(|)`
after:
`print(`
`--------|)` - == space
With this problem any automatch plugins(delimitmate etc.) broken in python files
If filetype plugin indent on commented out - behaves as expected. Vim behaves as expected with `filetype plugin indent on`

### Expected behaviour
When you press `<CR>` inside brackets, braces or parentheses it should just jump to a new line
before:
`print(|)`
after:
`print(`
`|)`

### Steps to reproduce using `nvim -u NONE`
1. `nvim -u NONE`
2.  With nvim -u NONE you can't reproduce it
3. But you can add in the blank init.vim `filetype plugin indent on`, then try to edit *.py

**Comment by monkoose** [comment]
Hm.
Just rechecked, vim just with `filetype plugin indent on` in .vimrc behaves identically as nvim, so there is some diffirence in my configs somewhere. Because with all plugins and options vim behaves as i need, but nvim not.
Any solution then how to fix this indentation problem if it is not nvim problem?

**Comment by altairmn** [comment]
Hey

Did you find the fix for this? I'm using NVIM v0.2.2 on Ubuntu 17.10. The bug occurs only when I use `:set filetype=python`
