### ISSUE TITLE
highlight link is broken - "E414: group has settings, highlight link ignored"

### ISSUE THREAD

**Issue by ggustafsson** [neovim/neovim#4549]
- Neovim version: NVIM 0.1.3
- [X] Vim behaves differently?
    - Vim version: VIM - Vi IMproved 7.4
- Operating system/version: Mac OS X 10.11.4
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### Actual behaviour
I cannot run "highlight link" after having cleared the group that I link to. E.g:

```
highlight clear CursorColumn                                                       
highlight link  CursorColumn StatusLine
```

This should work but it doesn't work in Neovim. I get the following error:

<img width="567" alt="screen shot 2016-04-09 at 10 04 17" src="https://cloud.githubusercontent.com/assets/595501/14402603/35ee64e2-fe3b-11e5-8073-8df68f9ece47.png">

E414: group has settings, highlight link ignored

And the group does not have settings:

<img width="567" alt="screen shot 2016-04-09 at 10 04 54" src="https://cloud.githubusercontent.com/assets/595501/14402607/46b0ca86-fe3b-11e5-8e8f-34c9ea759cab.png">

CursorColumn   xxx cleared

### Expected behaviour

I expect the highlight linking to work just like it does in Vim.

<img width="567" alt="screen shot 2016-04-09 at 10 11 54" src="https://cloud.githubusercontent.com/assets/595501/14402619/83277af0-fe3b-11e5-8836-8de05f2144c5.png">

CursorColumn   xxx links to StatusLine

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE`
2. highlight clear CursorColumn
3. highlight link  CursorColumn StatusLine

**Comment by justinmk** [comment]
Maybe related: https://github.com/neovim/neovim/issues/4236#issuecomment-185141589

**Comment by bharadwaj-raju** [comment]
Workaround: use `highlight!` which links ignoring the "settings".

**Comment by eddyekofo94** [comment]
@bharadwaj-raju It worked, thanks.. can you please explain in what it does exactly?
