### ISSUE TITLE
Add b:qflisttype read-only variable

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4550]
This is necessary to distinguish quickfix windows from location list windows.

There's an old patch on vim_dev (posted on 12/10/14 by @mattn): https://groups.google.com/d/msg/vim_dev/GIjn9QRyLag/M_8AJ5_UkMoJ / https://gist.github.com/mattn/6c8942fa063c2f3953bc.

The core change is quite tiny:

``` diff
--- a/src/quickfix.c    Mon Dec 08 04:16:45 2014 +0100
+++ b/src/quickfix.c    Wed Dec 10 18:26:51 2014 +0900
@@ -2433,6 +2433,8 @@
        set_option_value((char_u *)"fdm", 0L, (char_u *)"manual",
                                   OPT_LOCAL);
 #endif
+       set_internal_string_var("b:qflisttype", (curwin->w_llist_ref
+                       == NULL) ? "quickfix" : "location");
    }

    /* Only set the height when still in the same tab page and there is no
```

It would be nice for plugins to have this information.
See the vim_dev thread for workarounds that are needed for this currently.

Similar to the title patch for `setqflist` it seems like this might not get into Vim for a while, so Neovim could go ahead in this case, too.

In the same direction it would be useful to have functions to get the quickfix window for a tab, and the location list for a window directly.

**Comment by justinmk** [comment]
Rather that provide a `b:` variable, I would prefer if this were provided as part of https://github.com/neovim/neovim/issues/3933. E.g.:

```vim
echo winlayout()['loclist']
```

**Comment by blueyed** [comment]
btw: this is provided through the vim-qf plugin in a smart way: in `after/ftplugin/qf.vim` `b:isLoc` gets set:
https://github.com/romainl/vim-qf/blob/54c18ae1d2b300868321e15c9867eee7cb0a0bad/after/ftplugin/qf.vim#L30

**Comment by rafi** [comment]
This could really improve qflist vs. loclist functionality, like toggling a specific list window visibility.
[vim-qf](https://github.com/romainl/vim-qf) doesn't recognize an empty location-list.

**Comment by justinmk** [comment]
`:help getqflist()`
