### ISSUE TITLE
Use of uninitialized value in os_isdir when generating helptags

### ISSUE THREAD

**Issue by telotortium** [neovim/neovim#4556]
- Neovim version: v0.1.4-10-gbf2c2b3
- Vim behaves differently? N/A
- Operating system/version: Ubuntu 14.04
- Terminal name/version: iTerm2 Build 2.9.20160313 running Mosh (mosh-1.2.4-98-ga2a34ef) running Tmux 2.1
- `$TERM`: screen-256color

### Actual behaviour

When helptags are generated during the build process with the command

```
cd $HOME/misc/build/neovim/build/runtime/doc && $HOME/misc/build/neovim/build/bin/nvim -u NONE -i NONE -e --headless -c helptags\ ++t\ . -c quit
```

Msan crashes the program with the message `SUMMARY: MemorySanitizer: use-of-uninitialized-value $HOME/misc/build/neovim/build/../src/nvim/os/fs.c:69 os_isdir` and the following trace (note that I'm installing to ~/.local/share/nvim/runtime -- this may be important in interpreting the trace):

```
==10450== WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fe3a785a2a2 in os_isdir $HOME/misc/build/neovim/build/../src/nvim/os/fs.c:69:7
    #1 0x7fe3a7853cd9 in vim_version_dir $HOME/misc/build/neovim/build/../src/nvim/os/env.c:447:7
    #2 0x7fe3a78510e7 in vim_getenv $HOME/misc/build/neovim/build/../src/nvim/os/env.c:617:26
    #3 0x7fe3a778762a in set_runtimepath_default $HOME/misc/build/neovim/build/../src/nvim/option.c:459:28
    #4 0x7fe3a7782587 in set_init_1 $HOME/misc/build/neovim/build/../src/nvim/option.c:689:3
    #5 0x7fe3a729a762 in early_init $HOME/misc/build/neovim/build/../src/nvim/main.c:208:3
    #6 0x7fe3a729b226 in main $HOME/misc/build/neovim/build/../src/nvim/main.c:235:3
    #7 0x7fe3a5109ec4 in __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:287
    #8 0x7fe3a671087c in _start ($HOME/misc/build/neovim/build/bin/nvim+0xdb87c)

  Uninitialized value was created by an allocation of 'request' in the stack frame of function 'os_stat'
    #0 0x7fe3a785d640 in os_stat $HOME/misc/build/neovim/build/../src/nvim/os/fs.c:265

SUMMARY: MemorySanitizer: use-of-uninitialized-value $HOME/misc/build/neovim/build/../src/nvim/os/fs.c:69 os_isdir
Exiting
```

### Expected behaviour

No use of uninitialized value.

### Steps to reproduce

1. Build Neovim with Msan enabled: `CC=clang-3.5 CXX=clang++-3.5 nice make -j8 CMAKE_EXTRA_FLAGS="-DCLANG_MSAN=ON -DCMAKE_INSTALL_PREFIX=$HOME/.local" CMAKE_BUILD_TYPE=Debug`.

**Comment by justinmk** [comment]
Though the backtrace is slightly different because of changes in the codepath, this is the same MSan case discussed in https://github.com/neovim/neovim/pull/2807#discussion-diff-32729362. In that discussion @fwalch and I concluded that this is a false positive, because of MSan's lack of visibility into libuv. Sadly, since that time our MSan build has been failing on this case (see [any recent build](https://travis-ci.org/neovim/neovim/jobs/122088553), making it useless.

For those reasons I'll close this, but @telotortium if you have insight as to why that conclusion is mistaken please do say so.
