### ISSUE TITLE
neovim does not clear its last print after exiting when using with tmux

### ISSUE THREAD

**Issue by alexandnpu** [neovim/neovim#4561]
- Neovim version: v0.1.4-19-gfe4d814
- [X] Vim behaves differently?
    - Vim version: 7.4.1589
- Operating system/version: OS X EI Capitan
- Terminal name/version: ITerm2 2.1.4
- `$TERM`: xterm-256color
- tmux version: 2.1
- tmux configuration : set-window-option -g alternate-screen off

### Actual behaviour
neovim does not clear the bottom status after exit when using with tmux.

### Expected behaviour
vim exit with clearing its status line, while neovim keeps the status together with the bash prompt

### Steps to reproduce using `nvim -u NONE`

1. set the above tmux configuration option, which is to prevent vim clear the screen after exiting.
2. start tmux
3. start vim inside tmux
4. type some words and save it.
5. exit neovim
6. you will see that "xxxxL, xxxC is written" together with the bash prompt.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/3432
