### ISSUE TITLE
Weird red mark on bottom-right corner when using airline (just upgrade to nvim 0.1.3)

### ISSUE THREAD

**Issue by rawaludin** [neovim/neovim#4564]
- Neovim version: 0.1.3
- [x] Vim behaves differently?
- Vim version: 7.4.1090
- Operating system/version: OSX 
- Terminal name/version: iTerm2 / Build 2.9.20160313
- `$TERM`: xterm-256color-italic
### Actual behaviour

This not happened when I'm using nvim 0.1.2. I just upgraded to 0.1.3 and this red mark shown.
### Expected behaviour

Should be no red mark
### Steps to reproduce using `nvim -u NONE`
1. `nvim -u NONE`
2. Install vim airline
3. Edit any files
4. red mark shown on bottom right

My airline config:

```
" ----- vim-airline/vim-airline settings -----
let g:airline_theme = 'papercolor'
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline_detect_paste=1
let g:airline#extensions#tabline#enabled = 1
```

<img width="681" alt="screen shot 2016-04-12 at 9 59 38 am" src="https://cloud.githubusercontent.com/assets/1274849/14448780/f78eba1e-0095-11e6-9e42-4af86ebb450a.png">

**Comment by wsdjeg** [comment]
this is airline issue.and also happened in  vim. please update vim

**Comment by maccius** [comment]
I believe that this is triggered by having the Syntastic plugin enabled.  I'm not sure if it's a desired behavior or not, but it's not a NeoVim issue.
