### ISSUE TITLE
Airline Overflows on Startup

### ISSUE THREAD

**Issue by danprince** [neovim/neovim#4567]
- Neovim version: 1.4-dev
- [x] Vim behaves differently?
    - Vim version: 7.4
- Operating system/version: Xubuntu 15
- Terminal name/version: urvxt v9.21
- `$TERM`: screen-256color

### Actual behaviour
![](https://i.imgur.com/76BPMMk.png)

_Screenshot from Neovim 1.4-dev_

### Expected behaviour
![](https://i.imgur.com/gq6Ekp0.png)

_Screenshot from Vim 7.4_

### Steps to Reproduce
Open a file, then move the cursor away from line 1. Close and re-open. This bug seems to be directly related to this setting:

```viml
let g:airline_powerline_fonts = 1
```

If I comment or 0 that variable, I can't recreate the overflow at all.

**Comment by justinmk** [comment]
There are many similar issues related to airline: https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+airline

Can you check that this is not a duplicate? Are you using the latest version of airline? (this may have been fixed in recent airline)
