### ISSUE TITLE
Part of the asynchronous job output is cut off

### ISSUE THREAD

**Issue by radoslawroszkowiak** [neovim/neovim#4569]
- Neovim version: NVIM 0.1.4-dev
- [x] Vim behaves differently? Yes, issue does not exist
    - Vim version: 7.4.712

- Operating system/version: Xubuntu 15.10
- Terminal name/version: terminator, xterm, xfce4-terminal
- `$TERM`: `xterm`

### Actual behaviour
When using neomake plugin (https://github.com/benekastah/neomake) I'm experiencing the problem that when the linter report is long, the results are shown only for the part of a file. Neomake && Vim run without this issue. It seems that in my case this is caused by the asynchronous job output being cut to 64KB. So, when the linter output is 100KB, 36KB is cut off. When it's, say, 150KB, in my case 128KB will be OK with 22KB cut off, so it works okay up to multiplicands of 64KB as it seems.

I've tested it with some simple text file and simple vim script and it confirms that the output is cut. Just part of the file (which corresponds to 64KB) is shown. I don't know if that's intended for some reason or if there is some fix / workaround. I don't know Vim / Neovim source code and maybe I'm missing something obvious. If so - I'm sorry (and thanks for pointing out my possible mistake / misconfiguration).

### Expected behaviour

The output is not cut off. All the job output can be processed.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE -S ./vimtest.vim`

I attach two files zipped: vimtest.vim and file.txt - example text file to be processed.
[nvim_test.zip](https://github.com/neovim/neovim/files/217609/nvim_test.zip)

**Comment by oni-link** [comment]
Has probably something to do with the output stream being stopped, the libuv loop being active and processing the job termination.

What seems to fix the problem of missing output for me is to empty the ring buffer and with it starting the stdout stream before libuv becomes active. But I hope there is a better solution.

cc @tarruda

```diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 5477e79..2cc4e72 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -22305,18 +22310,22 @@ static void on_job_output(Stream *stream, TerminalJobData *data, RBuffer *buf,
   // The order here matters, the terminal must receive the data first because
   // process_job_event will modify the read buffer(convert NULs into NLs)
   if (data->term) {
-    terminal_receive(data->term, ptr, count);
+    terminal_receive(data->term, ptr, r);
   }
 
   if (callback) {
-    process_job_event(data, callback, type, ptr, count, 0);
+    char *tmp = xmemdup(ptr, r);
+    rbuffer_consumed(buf, r);
+    process_job_event(data, callback, type, tmp, r, 0);
+    xfree(tmp);
+  } else {
+    rbuffer_consumed(buf, r);
   }
-
-  rbuffer_consumed(buf, count);
 }

```
