### ISSUE TITLE
question about a terminal mode mapping

### ISSUE THREAD

**Issue by rockneverdies55** [neovim/neovim#4570]
I tried to map `<C-p>` to open [FZF](https://github.com/junegunn/fzf) window when in terminal input mode *(because `<Esc><Esc><C-p>` is little tedious)*. And it seems like having something like the following does it correctly:

`tnoremap <C-p> <C-\><C-n>:FZF<CR>`

and launches FZF window. However, within FZF window if I try to move up within the search results via `<C-p>` key, it reloads FZF window. 

Is there a way to get around this?

**Comment by wsdjeg** [comment]
why do not use fzf itself hotkey? for me ,I just need type into `~~<tab>`

**Comment by justinmk** [comment]
use `au TermOpen * nn <buffer> ...`. 

Issue tracker is not for usage questions.

**Comment by rainerborene** [comment]
I had the same issue today. Here's a quickfix:
```VimL
function! s:fzfterm()
  if match(b:term_title, 'fzf') > -1
    tmap <buffer> <c-j> <c-j>
    tmap <buffer> <c-k> <c-k>
    tmap <buffer> <c-l> <c-l>
    tmap <buffer> <c-h> <c-h>
  endif
endfunction

au TermOpen * call <sid>fzfterm()
```
