### ISSUE TITLE
:find on a terminal buffer opens a wrong path

### ISSUE THREAD

**Issue by BohrShaw** [neovim/neovim#4572]
- Neovim version: 0.1.3
- Operating system/version: ArchLinux
- Terminal name/version: Xfce-terminal with Zsh as the default shell
- `$TERM`: xterm-256color

### Actual behaviour

It seems another terminal is spawned but failed.

### Expected behaviour

Open the path `~/.config/nvim/init.vim`.

### Steps to reproduce using `nvim -u NONE`

`nvim -u NORC +'set path+=~/.config | term' +'find nvim/init.vim'`

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/issues/4299
