### ISSUE TITLE
[LUA 5.3] bitwise operations in core

### ISSUE THREAD

**Issue by ignatenkobrain** [neovim/neovim#4575]
There are in `CMakeLists.txt` in LUA_DEPENDENCIES module `bit` which is not compatible with Lua 5.3. They merged bitwise operations in lua itself, so would be great to use it instead.

**Comment by tarruda** [comment]
We probably won't ever use lua 5.3 considering Mike Pall won't support it in luajit. It's not like we need lua 5.3  anyway, for the vimscript translator it is only being used as a target for generated code(There can still be lua 5.3 remote plugins, of course)

**Comment by ignatenkobrain** [comment]
Problem is that we don't have lua 5.2 in the Fedora... We have luajit, but will it work when lua is 5.3...

**Comment by justinmk** [comment]
@tarruda Is Lua 5.1-compatible code not forward-compatible with Lua 5.3? 

> There are in CMakeLists.txt in LUA_DEPENDENCIES module bit which is not compatible with Lua 5.3. 

Can we just omit this dependency if 5.3 is being used? @ignatenkobrain are you able to send a PR?

**Comment by tarruda** [comment]
> Problem is that we don't have lua 5.2 in the Fedora... We have luajit, but will it work when lua is 5.3...

For now we only need luajit, you don't need to install lua 5.2

> @tarruda Is Lua 5.1-compatible code not forward-compatible with Lua 5.3?

I think it is not compatible: https://github.com/keplerproject/lua-compat-5.3

Even if it was compatible, we couldn't use any lua 5.3 features in order to maintain compatibility with luajit , so there would be little purpose in linking against lua 5.3

**Comment by justinmk** [comment]
> Even if it was compatible, we couldn't use any lua 5.3 features in order to maintain compatibility with luajit , so there would be little purpose in linking against lua 5.3

Yes, understood. I am considering cases for package managers, etc., where a system may have lua 5.2/5.3 and installing an older version might not be desired.

**Comment by Plotnus** [comment]
yup, ended up bailing on source build. My path to quiting was "cd build; cmake .." then I failed for no lua so I build lua5.3 from source. Then I see I need to install luarocks so I install that. Then I see the bit about how I need a bit module. But this bit module is only applicable to lua5.2 and lua 5.1. So, I install lua5.2 it overwrote my "lua" version to 5.2, so I reinstall lua5.3. Then I run cmake again and I get the info about not having the bit.lua module... then I quit... looks like I'll only be installing neovim from a package manager now it's time to remove all that lua stuff I no longer need... bleh. For all the neovim as the new vim stuff I read. Installing vim from source worked with no/minimal hitches.

**Comment by zhaozg** [comment]
I Persist on luajit, so please not.
