### ISSUE TITLE
Long :term output wraps to other splits

### ISSUE THREAD

**Issue by bronzehedwick** [neovim/neovim#4581]
- Neovim version: 0.1.3
- Operating system/version: OS X 10.10.5
- Terminal name/version: iTerm2 Build 2.9.20160415-nightly
- `$TERM`: xterm-256color
### Actual behaviour

Long terminal output that would run off the edge of the screen wraps to other open splits (easiest to see with a vertical split). See screenshot below.

![screen shot 2016-04-15 at 11 21 23 am](https://cloud.githubusercontent.com/assets/637174/14566617/445c81e0-02fe-11e6-9f26-f42bf036a92b.png)
### Expected behaviour

Long terminal output wraps under the terminal line, like `:set wrap`.
### Steps to reproduce using `nvim -u NONE`
1. `nvim -u NONE`
2. `:vsp`
3. `:terminal`
4. Some process that with long output that would normally wrap, e.g. `npm install`

**Comment by KillTheMule** [comment]
This seems not the case using nvim 0.1.2, nvim -u NONE, and `ls -l` in a somewhat small terminal, in an xterm.

**Comment by bronzehedwick** [comment]
Tried on nvim 0.1.3 with `ls -l` in a small term and also didn't find the issue, but was able to reproduce  again with an `npm install`. Perhaps it's the character that npm uses for progress (the solid block)?

**Comment by justinmk** [comment]
@bronzehedwick Can you provide more precise steps? I installed `npm 2.15.9` and nodejs 4.x, then

```
mkdir t
cd t
npm init --yes
`npm install neovim
```

but the fancy process bars did not appear.
