### ISSUE TITLE
Windows: Heap corruption call_user_func()/cat_func_name()

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#4582]
I've come across a heap corruption error in Windows, so far I have not been able to reproduce in Unix.

- Neovim version:  #810
- [x] Vim behaves differently?
- Operating system/version: Windows

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE`
2.  source the following script
3. :call Very_long_function_name_its_absurd_but_it_happens_sometimes_because_its_life()

```vim
" The called function needs to be s: for this to happen, see cat_func_name()
" K_SPECIAL
function! s:Very_long_function_name_its_absurd_but_it_happens_twice()
endfunction

function! Very_long_function_name_its_absurd_but_it_happens_sometimes_because_its_life()
	call s:Very_long_function_name_its_absurd_but_it_happens_twice()
endfunction
```

It seems the buffer allocated for `sourcing_name` ([here](https://github.com/neovim/neovim/blob/4eb58273cde14f360c41ad98461b423a87ba3fd1/src/nvim/eval.c#L21044)) is too small.

For this particular example:

- `sourcing_name` gets allocated with len **165** 
- the final string is 166 bytes long - `function Very_long_function_name_its_absurd_but_it_happens_sometimes_because_its_life[140694538682369]..<SNR>1_Very_long_function_name_its_absurd_but_it_happens_twice`

I tried reproducing in Linux with valgrind without success. Still seems plausible the issue could apply in Unix. That %zu value does not seem right either, so maybe the unexpected size comes from that. Isn't linenr_T defined as long?

**Comment by justinmk** [comment]
@equalsraf `%zu` is indeed wrong. If you change it to `"%" PRId64` is it fixed?

**Comment by equalsraf** [comment]
> If you change it to "%" PRId64 is it fixed?

No not really.  sizeof(linenr_T) == 4, %ld fixes it though.

The original vim patch was 879 https://github.com/vim/vim/commit/1d6328ca00fc6cfe37b1f5e038ec23f443258886 which uses '%d', merged in https://github.com/neovim/neovim/pull/4259

**Comment by justinmk** [comment]
@equalsraf I believe `"%" PRId64` and casting the linenr_T to `int64_t` is what we normally do. Can you try that?

**Comment by equalsraf** [comment]
Ah, ok that works

```diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 7beddbf..6c2c4e0 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -21064,8 +21064,8 @@ call_user_func (
   {
     if (save_sourcing_name != NULL
         && STRNCMP(save_sourcing_name, "function ", 9) == 0) {
-      vim_snprintf((char *)sourcing_name, len, "%s[%zu]..",
-                   save_sourcing_name, save_sourcing_lnum);
+      vim_snprintf((char *)sourcing_name, len, "%s[%"PRId64"]..",
+                   save_sourcing_name, (int64_t)save_sourcing_lnum);
     } else {
       STRCPY(sourcing_name, "function ");
     }
```

**Comment by justinmk** [comment]
@equalsraf I'll create a patch real quick.

**Comment by oni-link** [comment]
We could allocate not enough memory if we use a 64 bit number:
```c
  size_t len = (save_sourcing_name == NULL ? 0 : STRLEN(save_sourcing_name))
               + STRLEN(fp->uf_name) + 20;
```
My count: 
```c
size_t len2 = 
  STRLEN(save_sourcing_name) 
  +strlen("9223372036854775807")   // int64_t 19 chars (for values >0)
  +strlen("[]..")  // see format string
  +strlen("<SNR>")+STRLEN(fp->uf_name)-3  // see cat_func_name()
  +1  // NUL
```

**Comment by justinmk** [comment]
@oni-link Thanks :) Do you want to make a PR?

**Comment by oni-link** [comment]
@justinmk, I send a PR.
