### ISSUE TITLE
Mapping <c-h> to <c-w>h doesn't work

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#4584]
- Neovim version: 0.1.3
- [x] Vim behaves differently?
    - Vim version: All versions
- Operating system/version: OS X 10.11
- Terminal name/version: ITerm2
- `$TERM`: xterm-256color

### Actual behaviour
Mapping <c-h> to <c-w>h doesn't work

### Expected behaviour
It to work.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE`
2. :map <c-l> <c-w>l
3. :map <c-h> <c-w>h
4.: :vs
5. <c-l> #switches to right pane
6. <c-h> #doesn't do anything
7. <c-w>h # switches to left pane

**Comment by hath995** [comment]
https://github.com/neovim/neovim/issues/2048 It's actually an iTerm2 issue, but tarruda has a fix in this thread.

**Comment by sassanh** [comment]
@hath995 thanks
