### ISSUE TITLE
curly-braces-names do not work when used as a scope

### ISSUE THREAD

**Issue by gregorias** [neovim/neovim#4587]
- Neovim version: 1.4.40
- [Y] Vim behaves differently?
    - Vim version: 7.4.1113

### Actual behaviour

When evaluating {scope}:variable_name the evaluation function treats {scope} as a separate variable name and throws an error.

### Expected behaviour

{scope}:variable_name get evaluated correctly as a single name.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE`
2. :let scope = "g"
3. :let g:message = "test message"
4. :echo {scope}:message
5. Throws an error, but should print "test message"

This bug was introduced with vim's patch 7.4.1105 in commit 11cf3680e4e9c0dd9308d9df60b78ada15a30003. Vim has fixed it in patch 7.4.1113.

I would make the patch myself, but I am unsure on how to test it correctly.

**Comment by KillTheMule** [comment]
Strange the bug would appear in nvim, since 7.4.1105 is not merged...

There's a test added in https://github.com/vim/vim/commit/4119cf80e1e534057680f9543e73edf7967c2440, you could simply take that over.

**Comment by gregorias** [comment]
Done in #4589
