### ISSUE TITLE
NULL lists are represented as NIL

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#4596]
- Neovim version: ca280c28b464239de85152a2d1230bfc678f7358

### Actual behaviour

NIL in https://github.com/neovim/neovim/blob/ca280c28b464239de85152a2d1230bfc678f7358/test/functional/shada/compatibility_spec.lua#L275

### Expected behaviour

Empty list there.

I am currently rewriting vim_to_object to use non-recursive function and I would suggest to not keep this behaviour: all other typval_T code is supposed to treat such lists as empty fixed lists.

**Comment by bfredl** [comment]
I agree with the expected behavior of vim_to_object, but I wonder if `getreg()` is supposed to return NULL list to start with. Seems inconsistent as it otherwise returns a mutable list, and it can crash vim/neovim:  https://groups.google.com/forum/#!topic/vim_dev/54smHb4DVlM
