### ISSUE TITLE
Konsole colorcolumn does not work

### ISSUE THREAD

**Issue by nickaleks** [neovim/neovim#4606]
Archlinux
Qt: 5.6.0
KDE Frameworks: 5.21.0
Konsole: 15.12.3
Option 'set colorcolumn=80' does not do anything. Same option in vim works perfectly fine. The problem seems to be in konsole only, because in terminator it works.

**Comment by justinmk** [comment]
Could be related to `$TERM`, which was requested by the issue template...

Invariably this boils down to a colorscheme (which you did not mention) doing something wrong, or NVIM_TRUE_COLOR being set inappropriately.

Closing this since details weren't provided.
