### ISSUE TITLE
InsertLeave autocmd not working since 0.1.2.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#4609]
Every since I updated to 0.1.2, `InsertLeave` doesn't work in my `init.vim`.

I have something like this:

```viml
            function! InsertStatuslineColor(mode)
                if a:mode == 'i'
                    hi statusline guibg=#ef4d4a guifg=#222222 ctermfg=red
                elseif a:mode == 'r'
                    hi statusline guibg=#4e8dcb guifg=#222222 ctermfg=blue
                else
                    hi statusline guibg=#8a7cf4 guifg=#333333 ctermfg=purple
                endif
            endfunction

            " default statusline color in Normal mode
            au BufEnter * hi statusline guibg=#69bf64 guifg=#222222 ctermfg=green
            au BufEnter * hi statuslinenc guibg=#222222 guifg=#414141 ctermfg=8
            au BufEnter * hi vertsplit guibg=#222222 guifg=#222222 ctermfg=8
            au BufEnter * hi signcolumn guibg=#252525 ctermfg=8
            au BufEnter * hi linenr guibg=#292929 guifg=#444444 ctermfg=8

            au InsertEnter * call InsertStatuslineColor(v:insertmode)
            au InsertChange * call InsertStatuslineColor(v:insertmode)
            au InsertLeave * hi statusline guibg=#69bf64 guifg=#222222 ctermfg=green
```

Whenever I leave INSERT mode, that `hi` command isn't executed.

I have tried this while no plugins are loaded, and the result is the same (`InsertLeave` not fired).

**Comment by trusktr** [comment]
As a workaround, I can replace the InsertLeave line with:

```viml
            au CursorMoved * hi statusline guibg=#69bf64 guifg=#222222 ctermfg=green
```

which happens to work exactly as I expected the InsertLeave version to work because coincidentally the cursor moves back by one space after leaving INSERT mode. The only downside is now that CursorMoved autocmd is executed all the time when I move around, although the result isn't visually apparent since it sets the colors to the same colors over and over.

**Comment by justinmk** [comment]
Is this still an issue? This would be a rather popular bug, I think.
