### ISSUE TITLE
Relevant older vim patches

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#4611]
I've made this small list:

https://github.com/neovim/neovim/wiki/Relevant-old-patches-from-vim

It's just an overview, but if you see anything on this list you want stuff done for (worked on porting, marked NA, done some research on), just let me know and I'll give it a shot. I might extend this later.

**Comment by philix** [comment]
You know about https://neovim.io/doc/reports/vimpatch/, right?

**Comment by Shougo** [comment]
https://neovim.io/doc/reports/vimpatch/ does not support untagged patches.

**Comment by KillTheMule** [comment]
I know, but I wanted a more detailed list for tracking the patches before 1000 and writing down some thoughts and related things.

**Comment by justinmk** [comment]
Thanks @KillTheMule !
