### ISSUE TITLE
PKGBUILD no longer recognized as bash script

### ISSUE THREAD

**Issue by bradst** [neovim/neovim#4613]
- Neovim version: 0.1.3 [git HEAD](https://github.com/neovim/neovim/commit/ba9bdb3e70722942049fc17c52ef3d9eea866256)
- [?] Vim behaves differently?
    - vanilla Vim does not automatically recognize PKGBUILD files as bash scripts, but the standard `vim-runtime` package on Arch Linux *does*, by manually patching `filetype.vim` before packaging
- Operating system/version: Arch Linux

This is a regression introduced in commit https://github.com/neovim/neovim/commit/946807898be444e824afeac548ab04ba3b2466ba .

### Actual behaviour
`filetype` is unset or set to `conf` (depending on if the first line starts with a `#`), no/incomplete syntax highlighting as a result
### Expected behaviour
`call SetFileTypeSH("bash")` is called when opening a PKGBUILD file, setting `filetype=sh`. This was the case until commit https://github.com/neovim/neovim/commit/946807898be444e824afeac548ab04ba3b2466ba .
### Steps to reproduce using `nvim -u NORC`
1. `nvim -u NORC PKGBUILD`
2.  `:set filetype?`

**Comment by justinmk** [comment]
> This is a regression introduced in commit 9468078 .

Thanks for tracking that down. Vim is the same: https://github.com/vim/vim/blob/f882d9f89dbe24ab1ba4bc88529bef28242fd2ed/runtime/filetype.vim#L1865

Could you please raise an issue at https://github.com/vim/vim ? We don't want to fork `filetype.vim` in case this was done for a reason.

**Comment by fwalch** [comment]
> We don't want to fork filetype.vim in case this was done for a reason.

I guess we kind of did, back in #1087.

**Comment by justinmk** [comment]
I mean if it was done intentionally, we need to find out.

**Comment by fwalch** [comment]
> I mean if it was done intentionally, we need to find out.

You mean that Vim intentionally removed it? It was never in Vim, I only added it to Neovim (and inadvertently forked filetype.vim) in #1087.

**Comment by justinmk** [comment]
Oh, got it :) Let's add it back then.

**Comment by bradst** [comment]
Thanks!

**Comment by fwalch** [comment]
Sent an email to Bram; the changes of #1087 will be included in Vim's runtime, too.
