### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by chkl** [neovim/neovim#4616]
- Neovim version: commit:  ba9bdb3e70722942049fc17c52ef3d9eea866256
- [x] Vim behaves differently?
    - Vim version: 7.4
- Operating system/version: Debian Jessie
- Terminal name/version: konsole/gnome-terminal and zsh
- `$TERM`: xterm

### Actual behaviour
No highlighting of searched strings after typing `/`

### Expected behaviour
Vim should highlight occurrences of the search string.

### Steps to reproduce using `nvim -u NONE`

1. `nvim -u NONE `
2. `:set hlsearch`
3. `/string`

### Extra Information
It's not only limited to search, it rather seems that no highlighting at all works. For example nvim also doesn't highlight matching parenthesis.

**Comment by KillTheMule** [comment]
Try setting $TERM to xterm-256color.

**Comment by chkl** [comment]
That fixes it, quick and painless. Thank you!
