### ISSUE TITLE
neovim build broken on OpenBSD

### ISSUE THREAD

**Issue by bonds** [neovim/neovim#4620]
- Neovim version: master
- Operating system/version: OpenBSD 5.9-stable

### Actual behaviour
````
~/s/neovim (master|✔) ❯❯❯ gmake                     Wed Apr 20 09:37:35 PDT 2016
ninja  -C .deps
ninja: Entering directory `.deps'
[1/7] Performing build step for 'luv-static'
FAILED: cd /home/scott/src/neovim/.deps/build/src/luv-static-build && /usr/local/bin/cmake --build . && /usr/local/bin/cmake -E touch /home/scott/src/neovim/.deps/build/src/luv-static-stamp/luv-static-build
[ 50%] Building C object CMakeFiles/luv.dir/src/luv.c.o
In file included from /home/scott/src/neovim/.deps/build/src/luv/src/luv.c:41:
/home/scott/src/neovim/.deps/build/src/luv/src/dns.c: In function 'luv_getaddrinfo':
/home/scott/src/neovim/.deps/build/src/luv/src/dns.c:167: error: 'AI_V4MAPPED' undeclared (first use in this function)
/home/scott/src/neovim/.deps/build/src/luv/src/dns.c:167: error: (Each undeclared identifier is reported only once
/home/scott/src/neovim/.deps/build/src/luv/src/dns.c:167: error: for each function it appears in.)
/home/scott/src/neovim/.deps/build/src/luv/src/dns.c:171: error: 'AI_ALL' undeclared (first use in this function)
*** Error 1 in . (CMakeFiles/luv.dir/build.make:63 'CMakeFiles/luv.dir/src/luv.c.o': /usr/bin/cc   -I/home/scott/src/neovim/.deps/usr/includ...)
*** Error 1 in . (CMakeFiles/Makefile2:68 'CMakeFiles/luv.dir/all')
*** Error 1 in /home/scott/src/neovim/.deps/build/src/luv-static-build (Makefile:128 'all')
ninja: build stopped: subcommand failed.
Makefile:75: recipe for target 'deps' failed
gmake: *** [deps] Error 1
~/s/neovim (master|✔) ❯❯❯                           Wed Apr 20 09:37:49 PDT 2016
````
### Expected behaviour

Neovim builds successfully, like it used to.

### Steps to reproduce

1. `git clone --recursive https://github.com/neovim/neovim`
2. `cd neovim`
3. `echo 'CMAKE_EXTRA_FLAGS += -DENABLE_BUNDLED_JEMALLOC=OFF' > local.mk`
4. gmake

**Comment by equalsraf** [comment]
luvit/luv doesn't check for systems where those defines don't exist, should be easy to fix. Sadly I don't have an OpenBSD machine right now, if anyone can get a PR going upstream that would be ideal.

**Comment by bonds** [comment]
I don't have the skills necessary to fix the problem, unfortunately. But I can setup an internet accessible OpenBSD box+account for you to test with, if that would help.

**Comment by equalsraf** [comment]
@bonds thanks but I've got my hands on one now.

**Comment by equalsraf** [comment]
I've pushed some fixes upstream https://github.com/luvit/luv/pull/232 its not perfect yet but it should get us further. I did not check yet and likely wont be able to for a several days, if someone runs into runtime issues when executing lua, try setting LD_PRELOAD=/usr/lib/libpthread.so

**Comment by bonds** [comment]
Verified fixed on master. Thank you! You made my day!
