### ISSUE TITLE
Build process does not handle spaces

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#4621]
- Neovim version: HEAD @a7a0bf54e3f339f7bf1f97dee44546cdcd926b1d
- Operating system/version: OSX 10.10.5
- Terminal name/version:
- iTerm 2.9:
### Actual behaviour

```
cd neovim
make
...
[…]
...
-- extracting...
     src='/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/neovim/.deps/build/downloads/luajit/LuaJIT-2.0.4.tar.gz'
     dst='/Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/neovim/.deps/build/src/luajit'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 24%] No patch step for 'luajit'
glibtoolize: putting auxiliary files in '.'.
[ 25%] No update step for 'luajit'
[ 26%] No configure step for 'luajit'
[ 28%] No build step for 'luajit'
checking for xsltproc... /opt/local/bin/xsltproc
checking for gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
[ 29%] Performing install step for 'luajit'
==== Building LuaJIT 2.0.4 ====
glibtoolize:   error: linking '/opt/local/share/libtool/build-aux/ltmain.sh' to './' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 1
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
checking whether the C compiler works... clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/usr"'
clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/usr"'
...
[...]
...
[ 30%] No build step for 'jemalloc'
[ 32%] Performing install step for 'jemalloc'
install -m 644 include/jemalloc/jemalloc.h /Volumes/Macintosh HD/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include/jemalloc
install: /Volumes/Macintosh: Inappropriate file type or format
make[4]: *** [install_include] Error 71
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [build/src/jemalloc-stamp/jemalloc-install] Error 2
make[2]: *** [CMakeFiles/jemalloc.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2
```
### Expected behaviour

Variables expanding to pathnames are quoted so spaces (which are a standard thing for the OSX drives) are handled correctly.

I am not sure what caused this since I successfully compiled nvim a few months back.

**Comment by mikewadsten** [comment]
Looks like it's due to jemalloc not quoting the install path. See [here](https://github.com/jemalloc/jemalloc/blob/b2c0d6322d2307458ae2b28545f8a5c9903d7ef5/Makefile.in#L320).

I think the switch to jemalloc happened a few months ago? Which could explain this issue.

**Comment by justinmk** [comment]
can someone send a PR to https://github.com/jemalloc/jemalloc ?

**Comment by mikewadsten** [comment]
I'll do it.

**Comment by mikewadsten** [comment]
Based on these lines, it looks like the luajit (or libuv?) build may have the same issue:

```
==== Building LuaJIT 2.0.4 ====
glibtoolize:   error: linking '/opt/local/share/libtool/build-aux/ltmain.sh' to './' failed
make[3]: *** [build/src/libuv-stamp/libuv-configure] Error 1
make[2]: *** [CMakeFiles/libuv.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
checking whether the C compiler works... clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/usr"'
clang: error: no such file or directory: 'HD/Users/Rasmus/Downloads/Sources/neovim/.deps/usr"'
...
[...]
...
[ 30%] No build step for 'jemalloc'
```

**Comment by mikewadsten** [comment]
Okay, so I've tried for a while to fix jemalloc's `Makefile.in`, and I can't find any, shall we say prior art on the best way to address this issue.

Pretty much every Google result I can find concludes with "just symlink /Volumes/Macintosh HD/ to /Volumes/Macintosh_HD/" or something along those lines. And from my own findings, the Makefile syntax seems to preclude just throwing quotes around every use of those variables.

Throwing quotes around the declarations of `BINDIR` et al. at the top of Makefile.in doesn't help, since those quotes stick around as literal quotes in the resulting Makefile, leading to errors like this:

```
gcc: error: HD/Users/mike/git/jemalloc/build/lib/libjemalloc.2.dylib: No such file or directory
make: *** [lib/libjemalloc.2.dylib] Error 1
```

Interestingly, it seems like the configure script (or libtool, or something in the toolchain) may do some escaping of whitespace, since I see this in my `./autogen.sh` output in jemalloc when I change autogen.sh to set my prefix appropriately:

```
PREFIX             : /Volumes/Macintosh\ HD/Users/mike/git/jemalloc/build
BINDIR             : /Volumes/Macintosh HD/Users/mike/git/jemalloc/build/bin

▽
DATADIR            : /Volumes/Macintosh\ HD/Users/mike/git/jemalloc/build/share
INCLUDEDIR         : /Volumes/Macintosh HD/Users/mike/git/jemalloc/build/include
LIBDIR             : /Volumes/Macintosh HD/Users/mike/git/jemalloc/build/lib
MANDIR             : /Volumes/Macintosh\ HD/Users/mike/git/jemalloc/build/share/man
```
which is reflected in the Makefile itself:
```
# Configuration parameters.
DESTDIR =
BINDIR := $(DESTDIR)/Volumes/Macintosh HD/Users/mike/git/jemalloc/build/bin
INCLUDEDIR := $(DESTDIR)/Volumes/Macintosh HD/Users/mike/git/jemalloc/build/include
LIBDIR := $(DESTDIR)/Volumes/Macintosh HD/Users/mike/git/jemalloc/build/lib
DATADIR := $(DESTDIR)/Volumes/Macintosh\ HD/Users/mike/git/jemalloc/build/share
MANDIR := $(DESTDIR)/Volumes/Macintosh\ HD/Users/mike/git/jemalloc/build/share/man
```

If I escape all those paths, I actually get an assertion in ld:

```
0  0x10063aa44  __assert_rtn + 144
1  0x1006625d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x100645f81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
3  0x100688bf8  ld::tool::InputFiles::makeFile(Options::FileInfo const&, bool) + 796
4  0x10068aa80  ld::tool::InputFiles::parseWorkerThread() + 472
5  0x7fff8e3c205a  _pthread_body + 131
6  0x7fff8e3c1fd7  _pthread_body + 0
0  0x10063aa44  __assert_rtn + 144
A linker snapshot was created at:
	/tmp/libjemalloc.2.dylib-2016-03-20-220421.ld-snapshot
ld: Assertion failed: (cfiStartsArray[i] != cfiStartsArray[i-1]), function parse, file /SourceCache/ld64/ld64-242.2/src/ld/parsers/macho_relocatable_file.cpp, line 1748.
1  0x1006625d5  mach_o::relocatable::Parser<x86_64>::parse(mach_o::relocatable::ParserOptions const&) + 3175
2  0x100645f81  mach_o::relocatable::Parser<x86_64>::parse(unsigned char const*, unsigned long long, char const*, long, ld::File::Ordinal, mach_o::relocatable::ParserOptions const&) + 375
collect2: error: ld returned 1 exit status
make: *** [lib/libjemalloc.2.dylib] Error 1
```

---

All this said, the reason the fix isn't "put quotes around all those variables" is that the generated Makefile relies heavily on variables provided in configure.ac, and many of those use variables such as BINDIR. Some of these variables are used in other variable declarations (so we have to worry about whether the quotes stick around or not), and others in both rule names and rule bodies (quotes around the rule name are treated literally it seems...).

I'm starting to lean toward the "don't use paths with spaces in them" solution...

**Comment by justinmk** [comment]
@mikewadsten Thanks. http://stackoverflow.com/a/9838604/152142 and http://savannah.gnu.org/bugs/?712 agree with your conclusion. This is basically blocked until someone can prove otherwise.

**Comment by themightyoarfish** [comment]
I use Macports so I am not clear what you mean, but I will try to install the deps manually some time.

**Comment by justinmk** [comment]
## Resolution/Summary

- This is a bug in `make` (see above).
- Neovim is a CMake project, it doesn't depend on `make`. You can use `ninja` or any other generator...
    - ..._unless_ you are also building the "bundled" dependencies. In that case, the workaround is to not build "bundled" dependencies. Nothing we can do about the build systems in third-party projects.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
