### ISSUE TITLE
Interactive Shell Always Shows "Bright" Black as Bright Black

### ISSUE THREAD

**Issue by thegranddesign** [neovim/neovim#4623]
- Neovim version: v0.1.3-366-ga9e0d73
- [x] Vim behaves differently?
    - Vim version: 7.4
- Operating system/version: OSX 10.11.4
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

### Actual behaviour

I have my gitconfig setup to show the "plain" text in a diff as a darker shade so that the diff stands out more.  I currently have it set to `black bold`, which, for my colorscheme I've set in iTerm2 is a dark gray but not even close to black.

When I show a diff in Neovim's interactive terminal however, it shows up as completely black.  It appears as though the other colors are correct.

![image](https://cloud.githubusercontent.com/assets/17790097/14696663/b034ad96-0742-11e6-84b1-10872fa95441.png)

### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/17790097/14696669/b71015c4-0742-11e6-904c-f71b2902b45f.png)

### Steps to reproduce using `nvim -u NONE`

I did try this on my setup with `-u NONE` and everything disabled (including my shellfiles which do some colorscheme goodness.  The behavior changed up a bit.  Again, all the colors came through except for the `black bold` which this time showed up as white instead of black.

![image](https://cloud.githubusercontent.com/assets/17790097/14696746/4825cafe-0743-11e6-94fd-d27c0ae74ad1.png)

### iTerm Profile Color Settings

![image](https://cloud.githubusercontent.com/assets/17790097/14696775/752a0c5e-0743-11e6-9c4d-54af2f5ebf10.png)

**Comment by justinmk** [comment]
@thegranddesign Are you using true color?

**Comment by thegranddesign** [comment]
@justinmk when I execute that command I get `E480: No match: g:terminal_color`

I enabled true color which I was not previously using and that does now show the colors in their proper color.  So thank you for pointing me to that! 👍 

I also read through every comment on like 3 issues involving this, but everything seemed to point to the fact that you all were allowing the emulator to decide how to show bold fonts (whether by bolding the font or by using bright colors) rather than adding an option to Neovim.  That sounds great to me.  So I'm a little confused why these settings in iTerm:

![image](https://cloud.githubusercontent.com/assets/17790097/14701469/29f2805e-076b-11e6-8afb-3d907287180c.png)

Would have been causing the bold ANSI code to not show as a bright color.  Especially when it shows properly in Tmux and iTerm.  It seem as though Neovim is not, in fact, allowing the emulator to decide how to show bold fonts.

Am I misunderstanding something?
