### ISSUE TITLE
os_breackcheck() crashes

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#4635]
See https://github.com/neovim/neovim/pull/4070#discussion_r50626558

I've started investigating from a symptoms point of view. If you look at https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L96, there are 3 calls to `eq`. The third produces the crash (well, I've confirmed it actually the call to `buflist_findpath`, of course), but _only_ if the other 2 happen before. If you comment out 1 or 2 of them, everything passes (I tried all possible combinations).

Slightly below, there's https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L110. The crash happens at line 117, but _only_ if line 114 is there. If you comment out line 114 (and ofc 127 and 131 so you don't get a lua error), the test passes.

The crash does not happen at https://github.com/neovim/neovim/blob/master/test/unit/buffer_spec.lua#L134.

I've run the tests selectively using TEST_FILTER. I'll try to produce a minimal example later on.

**Comment by KillTheMule** [comment]
I've made a small crash test file at https://github.com/KillTheMule/neovim/commit/409a19547b87e6be40501be1198e5be4490db386, the results seem really strange. Might have to learn how to use gdb...

**Comment by justinmk** [comment]
@oni-link Diagnosis suggests that we just need to call event_init() in the unit-test initialization:

> Looks like for unittest `buffer_spec.lua` somehow the queue `loop.uv.pending_queue` was not initialized (`event_init()` or `loop_init()` was not called?) or was left in an undefined state after use.
The queue is not empty but it's `prev` and `next` pointer point to `NULL`.

https://github.com/neovim/neovim/pull/4642 should fix this.
