### ISSUE TITLE
Tests are hanging in QB on master...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#4637]
It's not clear to me what is happening, but tests on all platforms are hanging under QB.

Here's the log from the Linux build:

```text
21:18:36,617 INFO  - ok 120 - dictionary change notifications watcher is triggered by remove()
21:18:36,617 INFO  - # test/functional/dict_notifications_spec.lua @ 95: dictionary change notifications watcher is triggered by extend()
21:18:36,617 INFO  - ok 121 - dictionary change notifications watcher is triggered by extend()
21:18:36,617 INFO  - # test/functional/dict_notifications_spec.lua @ 111: dictionary change notifications watcher is triggered with key patterns
21:35:45,314 INFO  - Terminating launched command gracefully...
21:35:45,357 WARN  - Terminated
21:35:45,359 WARN  - Vim: Caught deadly signal 'SIGTERM'
21:35:45,359 WARN  -
21:35:45,359 WARN  - Vim: Finished.
21:35:45,362 WARN  - Terminated
21:35:45,502 INFO  - ok 122 - dictionary change notifications watcher is t
21:35:45,503 INFO  - Executing post-execute action...
21:35:45,504 ERROR - Step 'master>buildall>build-node?testNode=linux-64>build-and-run-tests>build-and-run-tests-parameterized?buildType=Debug>run-tests>run-functional-tests' is failed.
[snipped traceback]
```

You can see after 17 minutes QB terminated the build.  The other platforms look similar, though not in identical spots.  And the way the output is broken, I suspect there's something buffered somewhere So we can't be sure if it's 122 that's hanging or not.

I tried running just the dict_notifications_spec.lua file itself and had no issues.  So there's something else going on here.  In the past the long build paths used by QB has brought up some issues, so it could be something like that.  There was nothing in the ~/.nvimlog file to help narrow it down either.

**Comment by bfredl** [comment]
Another point where the qb tests often hang is
```
12:43:38,179 INFO  - # test/functional/terminal/tui_spec.lua @ 151: tui can handle arbitrarily long bursts of input
12:46:46,814 INFO  - Unable to terminate launched command gracefully, terminating forcibly instead...
12:46:46,817 DEBUG - Executing command: kill -9 40332
```
Not that I think this test is broken in particular, just that it takes up a big portion of the test time would make it likely for a timeout to kill the job at this point.

**Comment by jszakmeister** [comment]
I also meant to say that if I back up to a7a0bf54e3f339f7bf1f97dee44546cdcd926b1d, then things appear to run successfully.

**Comment by justinmk** [comment]
> if I back up to a7a0bf5, then things appear to run successfully.

Hmm, that leaves only 3d7a6e4, 5ebffaa, or cef624e as possible causes, at a glance.

**Comment by jszakmeister** [comment]
I believe #4718 fixes the problems on QB.  Several times we've had issues where the longer paths in QB cause the tests to hang because nvim is asking the user to press a key.  It'd be nice if we could find a better to prevent this other than putting silent in front of the command.

It would also be nice if QB wasn't ignored when these issues occurred. :-(  I set it up, but I wasn't necessarily volunteering to chase down every problem that occurs in QB and not Travis--especially if it doesn't appear related to QB itself.

**Comment by brcolow** [comment]
Out of curiosity...why is it that the tests don't fail in Travis but do in QB...they are testing the exact same things, right? Why do "press enter" prompts not cause a problem in Travis?

**Comment by jszakmeister** [comment]
@brcolow The paths on QB tend to be longer than those running under Travis (`/home/user/buildagent/workspace/root/neovim/master` vs `/home/user/neovim`).  The difference is enough to trigger these issues in one and not the other.  Unfortunately, there is no good indication that is what's going on--the test just hangs.

**Comment by bfredl** [comment]
can we run lua code triggered by the timeout condition or is the job already dead at that point? In principle we could attach a screen and display the nvim screen state at the timeout event. This might require a bit more event processing allowed at wait-for-input states (which might actually mitigate some of these issues). Some discussion in #4624 (that PR enables processing in sleep, wait-for-input will be a followup PR).

**Comment by jszakmeister** [comment]
@bfredl Good question.  I'm not sure if there's a way to "proceed, but fail and run this code (and leave the process running)".  Plus, there would be cross-platform things to deal with (the tests run on Linux, OS X, and FreeBSD right now, but could be others in the future, including Windows).
