### ISSUE TITLE
neovim sends terminal control codes in silent Ex mode

### ISSUE THREAD

**Issue by rkitover** [neovim/neovim#4640]
- Neovim version: master
- [x ] Vim behaves differently?
  - Vim version: 7.4
- Operating system/version: Mac OS X El Capitan
- Terminal name/version: iterm latest
- `$TERM`: screen-256color
### Actual behaviour

This command flashes the screen to blank and back:

``` bash
nvim -Es +'sleep 1100 m' +q
```
### Expected behaviour

No terminal control codes should be printed.
### Steps to reproduce using `nvim -u NONE`

``` bash
nvim -u NONE -Es +'sleep 1100 m' +q
```

**Comment by justinmk** [comment]
Try `--headless`:

    nvim --headless -u NONE -Es +'sleep 1100 m' +q
