### ISSUE TITLE
Slow copying/cutting after mouse selection

### ISSUE THREAD

**Issue by pgkos** [neovim/neovim#4650]
- Neovim version: 0.1.3
  `NVIM 0.1.3
  Build type: RelWithDebInfo
  Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.3/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include`
  `Optional features included (+) or not (-): +acl   +iconv    +jemalloc`
- also occurs with latest Neovim (from git, version 0.1.5) on OS X
- [X] Vim behaves differently? There is no delay in Vim (need to `:set mouse=a`)
- Operating system/version: Arch Linux/OS X
- Terminal name/version: Konsole/Tilda/iTerm2 on OS X/etc.
- `$TERM`: xterm-256color
### Actual behaviour

Neovim hangs for a few seconds while copying (`y`) or cutting (`d`) text selected using the mouse after auto-switching to visual mode (while working on a file with unsaved changes).
### Expected behaviour

No delay.
### Steps to reproduce using `nvim -u NORC`
1. Open a file (`nvim -u NORC somefile`, can be a small text file with just a few lines).
2. Input a few new lines of text.
3. Select some text (the selection must span several lines) using the mouse in the terminal (Neovim automatically switches to visual mode).
4. Copy or cut the selected text.
5. Neovim hangs for a few seconds and does not respond to keyboard/mouse.

The issue disappears/does not occur if:
- the file is saved before copying the selected text
- only one line is selected
- the window is scrolled out of the selected area (using the mouse wheel)
- the text is selected using the keyboard only

**Comment by justinmk** [comment]
Maybe https://github.com/neovim/neovim/pull/7203 mollifies this?
