### ISSUE TITLE
Make `:confirm bd` work for terminal buffers

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4651]
It would be nice if `:confirm bd` would work as with a changed buffer: it should ask for confirmation instead of requiring you to use `:bd!`:

> E89: term://.//15810:… will be killed(add ! to override)

Relevant code: https://github.com/neovim/neovim/blob/ef205c3851fda637af49b5517bee60e6a62275ed/src/nvim/buffer.c#L953-L975.

Here `!buf->terminal` is checked for in the block that uses the dialog.
I think there could be a new `dialog_terminal_kill` for this.
- Neovim version: v0.1.5-24-gef205c3

**Comment by Asheq** [comment]
Also, I think that if the `confirm` option is set, `:bd `should behave the same as `:confirm bd`
