### ISSUE TITLE
Please sign release tags

### ISSUE THREAD

**Issue by rillian** [neovim/neovim#4656]
- Neovim version: 0.1.4

I'd like to have gpg-signed release tags to verify when building. Any developer tool is a target for malware injection.

### Actual behaviour

```
$ git tag -v v0.1.4
object 4dcd19d9bc2417051ddbda177010ca8c0cb2cf73
type commit
tag v0.1.4
tagger Justin M. Keyes <justinkz@gmail.com> 1461549919 -0400

NVIM v0.1.4
error: no signature found
error: could not verify the tag 'v0.1.4'
```
### Expected behaviour

`git tag -v vX.Y.Z` should verify a signature.

**Comment by justinmk** [comment]
Good idea. Will do this from now on.

**Comment by rillian** [comment]
Thanks!

**Comment by rillian** [comment]
Can you please push a signed v0.1.5 tag?

**Comment by justinmk** [comment]
Sorry about that. Give me until tomorrow. And I'll add this to `release.sh` script so it is not overlooked next time.

**Comment by justinmk** [comment]
@rillian Since overwriting 0.1.5 isn't really an option, we'll release 0.1.6 in the next few days, and it will be signed.

**Comment by justinmk** [comment]
0.1.6 is signed.

**Comment by rillian** [comment]
It is! Thanks.

@justinmk I wasn't able to find a matching key on any keyservers, and this one doesn't match the one on https://keybase.io/justinmk/ Is the signing public key available somewhere?

**Comment by justinmk** [comment]
@rillian updated https://keybase.io/justinmk

**Comment by rillian** [comment]
Confirmed now. Thanks!
