### ISSUE TITLE
Build fails on Debian due to `busted` dependency download

### ISSUE THREAD

**Issue by tswilkinson** [neovim/neovim#4658]
- Neovim version: latest Git HEAD
- Operating system/version: Debian Jessie

### Actual behaviour
    $ make distclean && make
    ...
    [ 96%] Generating usr/bin/busted

    Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec
    CMakeFiles/busted.dir/build.make:51: recipe for target 'usr/bin/busted' failed
    make[3]: *** [usr/bin/busted] Error 1
    make[3]: Leaving directory '/home/tom/neovim/.deps'
    CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/busted.dir/all' failed
    make[2]: *** [CMakeFiles/busted.dir/all] Error 2
    make[2]: Leaving directory '/home/tom/neovim/.deps'
    Makefile:76: recipe for target 'all' failed
    make[1]: *** [all] Error 2
    make[1]: Leaving directory '/home/tom/neovim/.deps'
    Makefile:75: recipe for target 'deps' failed
    make: *** [deps] Error 2

### Expected behaviour
Successful build.

I am using [crouton](https://github.com/dnschneid/crouton/), which may mean that I am missing some dependency.  However, building neovim from source on the Ubuntu version of crouton works.

**Comment by jszakmeister** [comment]
This looks like more of a GitHub issue than ours.  I assume that since you got that far many of the other dependencies downloaded fine.  So it looks like a hiccup on the GitHub end.

**Comment by tswilkinson** [comment]
Could I download the mentioned file manually somehow?  Would that help?

I have built neovim by writing `make -i` instead, so that `busted

**Comment by jszakmeister** [comment]
Hmmm... good question, but I think it's being installed via Luarocks--so I don't know.  Do you have `wget` installed?  I know we've run into issues in the past if it's not.

> I have built neovim by writing make -i instead, so that busted is not downloaded. It seems fine... what is busted even doing anyway?

busted is used to run the tests.

**Comment by tswilkinson** [comment]
Yes, I do have `wget` installed, along with all of the build prerequisites listed on the wiki.

**Comment by jszakmeister** [comment]
:-(  I'm afraid you're going to have to dig in a bit and see if you can get more information out of the build.  It sounds to me like something is missing.  Perhaps the tools don't support SSL, or the like.  The place to start would probably be [here](https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuarocks.cmake#L118) where busted in being installed and seeing if you can't get something a little more verbose about the issue.  Perhaps simply changing "build <URL>" to "build --verbose <URL>" might be enough to get some more information.  Luarocks has been notoriously bad on letting us know what the actual problem is though. :-(

**Comment by tswilkinson** [comment]
Ah... sorry could you specifically suggest some things to type in?  I have no idea what I'm doing.

For instance, where do I change `build` to `build --verbose`?

**Comment by jszakmeister** [comment]
That was the link I had in my response.  Here: https://github.com/neovim/neovim/blob/master/third-party/cmake/BuildLuarocks.cmake#L120

I'm sorry I can't give you more to run on.

**Comment by tswilkinson** [comment]
OK, now I get:

```shell
make[3]: Entering directory '/home/tom/neovim/.deps'
Scanning dependencies of target busted
make[3]: Leaving directory '/home/tom/neovim/.deps'
make[3]: Entering directory '/home/tom/neovim/.deps'
[ 96%] Generating usr/bin/busted

io.popen:       'pwd' 2> /dev/null

os.execute:     cd '/home/tom/neovim/.deps' && test '-e' '/home/tom/neovim/.deps/usr/lib/luarocks/rocks'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && test '-d' '/home/tom/neovim/.deps/usr/lib/luarocks/rocks'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && test '-e' '/home/tom/neovim/.deps/usr'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && test '-d' '/home/tom/neovim/.deps/usr'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && test '-e' '/home/tom/neovim/.deps/usr'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && mkdir -p '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828'
Results: 1
  1 (number): 0

os.execute:     cd '/home/tom/neovim/.deps' && test '-d' '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828'
Results: 1
  1 (number): 0

os.execute:     cd '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828' && 'wget' --no-check-certificate --no-cache --user-agent='LuaRocks/scm linux-x86_64 via wget' --quiet --timeout=30 --tries=1  --output-document  '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828/busted-2.0.rc11-0.rockspec' 'https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec'
Results: 1
  1 (number): 1024

os.execute:     cd '/' && rm '-rf' '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828'
Results: 1
  1 (number): 0

Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec
CMakeFiles/busted.dir/build.make:51: recipe for target 'usr/bin/busted' failed
make[3]: *** [usr/bin/busted] Error 1
make[3]: Leaving directory '/home/tom/neovim/.deps'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/busted.dir/all' failed
make[2]: *** [CMakeFiles/busted.dir/all] Error 2
make[2]: Leaving directory '/home/tom/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tom/neovim/.deps'
Makefile:75: recipe for target 'deps' failed
make: *** [deps] Error 2
```

**Comment by jszakmeister** [comment]
It looks like this is the command failing:

```text
os.execute:     cd '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828' && 'wget' --no-check-certificate --no-cache --user-agent='LuaRocks/scm linux-x86_64 via wget' --quiet --timeout=30 --tries=1  --output-document  '/tmp/luarocks_luarocks-rockspec-busted-2.0.rc11-0-2828/busted-2.0.rc11-0.rockspec' 'https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec'
Results: 1
  1 (number): 1024
```

Is it possible to try and run a similar command in your crouton environment and see what happens?  I'd leave off the `--quiet` so that wget can print the issue to stderr.  Maybe then you'll have a better understanding of what exactly is causing it to fail.

**Comment by tswilkinson** [comment]
Neovim now builds, even on a completely fresh chroot.  What changed?!?
I get this:

```
[ 96%] Generating usr/bin/busted

Missing dependencies for busted:
say >= 1.3-0
lua_cliargs >= 2.5-0, < 3.0.rc-1
luassert >= 1.7.8-0
lua-term >= 0.1-1
luafilesystem >= 1.5.0
mediator_lua >= 1.1.1-0
dkjson >= 2.1.0
luasocket >= 2.0.1
penlight >= 1.3.2-2

Using https://luarocks.org/say-1.3-1.rockspec... switching to 'build' mode
Updating manifest for /home/tom/neovim/.deps/usr/lib/luarocks/rocks
say 1.3-1 is now built and installed in /home/tom/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)

Using https://luarocks.org/lua_cliargs-2.5-5.src.rock... switching to 'build' mode
```

I think that the build succeeded once a long time ago, and then started failing again, so I'm wary of saying that this is permanently fixed.  Should I just keep trying to build and alert you if it fails again?

**Comment by tswilkinson** [comment]
@jszakmeister And we're back to failing again.  Again.

The output of `wget --no-check-certificate ...` without `--quiet` is:

    converted 'https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec' (ANSI_X3.4-1968) -> 'https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec' (UTF-8)
    --2016-05-08 14:05:29--  https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 213.120.234.106, 213.120.234.122
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|213.120.234.106|:443... connected.
    GnuTLS: A TLS fatal alert has been received.
    GnuTLS: received alert [0]: Close notify
    Unable to establish SSL connection.

[This](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=738625) looks relevant.  It suggests that using the IP address instead of the hostname would help.  Is that worth a shot?  How do I find the IP address of the link? (Sorry for the amateurish questions!)

**Comment by justinmk** [comment]
https://github.com/mirleft/ocaml-tls/issues/293 seems related. At any rate this is out of our control.
