### ISSUE TITLE
tab drag requires mouse to stay in tab bar

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#4663]
- Neovim version: 0.1.2
- [x] Vim behaves differently? Vim version:
  VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  6 2014 14:32:04)
  Compiled by root@apple.com
- Operating system/version: OS X 10.10.2 (14C109)
- Terminal name/version: iTerm 2.1.4
- `$TERM`: xterm-256color

### Actual behaviour
Dragging tabs works as long as mouse stays in the tab bar. When mouse leaves tab bar and goes into a buffer while still dragging, it begins highlighting text and stops dragging the tab.

### Expected behaviour
Leaving the tab bar while dragging a tab should still drag the tab according to the mouse' horizontal position despite being vertically displaced into a buffer.

### Steps to reproduce using `nvim -u NORC`
I'm not sure how I enabled mouse drag of tabs. Is it a plugin? I have to wade through my huge vimrc to find out. If so, then maybe this isn't a bug with neovim, and the plugin just works differently in each.

**Comment by brcolow** [comment]
I believe tab dragging is enabled with:

`set mouse=a`

**Comment by justinmk** [comment]
Is it confirmed that Vim behaves differently using the same configuration?

**Comment by fmoralesc** [comment]
I can confirm that is the case with a vim with
~~~ vim
set mouse=a
~~~

**Comment by fmoralesc** [comment]
@justinmk I meant this doesn't happen in vim ;) We might be missing some logic in the tui.

**Comment by trusktr** [comment]
> Is it confirmed that Vim behaves differently using the same configuration?

@justinmk Yep indeed.

**Comment by sach1t** [comment]
I looked into this a bit. The code that handles the dragging is a bit different compared to vim. I managed to make the code the same, however it turns out that there may be a bigger issue. In vim, clicking results in two mouse events a mouse button press and a mouse button release. But, in neovim clicking results in only a mouse button press event.

**Comment by sach1t** [comment]
Despite the issue mentioned above, I did manage to get the desired behavior. But, it is more of a hack.

**Comment by sach1t** [comment]
The pull request above, however, is not a hack.
