### ISSUE TITLE
set cb=unnamedplus ineffective lately?

### ISSUE THREAD

**Issue by ds26gte** [neovim/neovim#4665]
`set cb=unnamedplus` used to let me use Neovim `y` and `p` with the system clipboard. This has stopped working recently. (I do continue to have `xsel` in my `PATH`.)

**Comment by ds26gte** [comment]
Bug more basic than that.  Even if `xsel` and `xclip` are present in `PATH`, yanking to registers `+` and `*` produce the error `clipboard: provider not available`.

**Comment by justinmk** [comment]
There's almost no information here. The clipboard works for many people. Can you provide the details requested by the issue template?

**Comment by ds26gte** [comment]
Thanks. My error. I didn't have the system `autoload` directory in my `$VIMRUNTIME`.
