### ISSUE TITLE
job: set flag during exit (similar to v:dying)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4666]
It would be useful in job exit handlers to know if they should care about modifying (result) buffers etc, which is often not necessary when Vim is exiting.

For the jobs API this could be provided by a flag to the exit handler, but it might be useful to have a variable similar to `v:dying` for this, e.g. `v:exiting`.

This was briefly discussed with @justinmk on IRC.

**Comment by justinmk** [comment]
[Notes from the gitter discussion]

Use case: allows job handlers to be skipped when exiting (neomake, fzf, dispatch-neovim, etc) => helps performance

v:dying is for abnormal exits. You could try setting a flag during VimLeave, but I wonder if the exit handlers are being flushed before or after that event. I guess they should flush after VimLeavePre, but before VimLeave. Then you could set a flag in VimLeavePre. But a `dying` or `exiting` flag in the job callback would be more elegant.
