### ISSUE TITLE
PKGBUILD files aren't recognized as bash scripts by runtime/filetype.vim

### ISSUE THREAD

**Issue by phijor** [neovim/neovim#4667]
- Neovim version: `NVIM v0.1.5-69-g81e0874`
- [ ] Vim behaves differently? Vim version: --
- Operating system/version: `NVIM v0.1.5-69-g81e0874`
- Terminal name/version: `termite v11`
- `$TERM`: `xterm-termite`

### Actual behaviour
Openening a `PKGBUILD` file does not set filetype to `bash`.

### Expected behaviour
Openening a `PKGBUILD` file should set filetype to `bash`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC PKGBUILD
:set filetype
```

### Possible fixes
75f164c introduced filetype-association for `PKGBUILD`s, but  this got overwritten when applying 9468078. Re-add `PKGBUILD*` to the autocmd.

**Comment by fwalch** [comment]
Thanks for giving such a detailed report! Finally got around to fix that; see #4668.
