### ISSUE TITLE
Question: ARM build for Ubuntu?

### ISSUE THREAD

**Issue by justinkelly** [neovim/neovim#4672]
Hi Neovim,

Just wondering if there could be an ARM build of Neovim?

The Ubuntu PPA currently has only amd64 and i386 builds 
* https://code.launchpad.net/~neovim-ppa/neovim-ppa/neovim

I'm not sure if all the dependencies are available for arm 

related: https://github.com/neovim/neovim/issues/2089

Cheers

Justin

**Comment by mklein994** [comment]
What are you looking to use it for? There's a port for Android (see the [wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#android)).

**Comment by justinkelly** [comment]
thanks @mklein994  - using Ubuntu on arm (chromebooks)

also rasppi/CHIP/and those other arm/linux boards

**Comment by jamessan** [comment]
Debian has arm [builds](https://packages.debian.org/experimental/neovim).

**Comment by justinkelly** [comment]
thanks @jamessan !

CC'ing the Ubuntu PPA crew ( @fwalch @jszakmeister @tarruda )

@fwalch - could an arm build in your ubuntu ppa be added?

**Comment by fwalch** [comment]
I enabled the armhf build. For some reason, Ubuntu doesn't have libluajit-5.1-dev for arm64, so I can't enable that..

**Comment by jamessan** [comment]
Debian didn't have arm64 until recently.  The package was using a whitelist of supported architectures until it was [changed](https://anonscm.debian.org/cgit/pkg-lua/luajit.git/commit/?id=4b0a757331579eb3ba855b91d01f2d3fb2a7360e) for the 2.1.0 beta uploads.

**Comment by justinkelly** [comment]
thanks!!! neovim just installed on ubuntu arm !!

```
(trusty)justin@localhost:~$ nvim -v   
NVIM 0.1.5-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/arm-linux-gnueabihf-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/build/config -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/src -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-u57eps/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu14.04.1/build/include
Compiled by buildd@bos01-arm64-024

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

(trusty)justin@localhost:~$ 
```

**Comment by justinkelly** [comment]
closing
