### ISSUE TITLE
Make :bd not require ! to delete a terminal buffer

### ISSUE THREAD

**Issue by still-dreaming-1** [neovim/neovim#4683]
- Neovim version: NVIM 0.1.5-dev
- Operating system/version: Linux Mint 17.3 Cinnamon 64 bit
- Terminal name/version: zsh 5.0.2 (x86_64-pc-linux-gnu)
- `$TERM`: xterm-256color
### Actual behaviour

`:te` to open a terminal buffer.
`Ctrl+\` + `Ctrl+n` Go to normal mode.
`:bd` to delete the terminal buffer.
It says 

> E89: term://.//5513:/bin/zsh will be killed(add ! to overwride)
### Expected behaviour

Delete the buffer without requiring !
### Steps to reproduce using `nvim -u NORC`

`:te` to open a terminal buffer.
`Ctrl+\` + `Ctrl+n` Go to normal mode.
`:bd` to delete the terminal buffer.
It says "E89: term://.//5513:/bin/zsh will be killed(add ! to override)

I think this makes more sense because otherwise you can never close terminal buffers without ! at the end. It is not like sometimes the shell is not running when the terminal buffer is running.

**Comment by still-dreaming-1** [comment]
Sorry, I didn't mean to enter this yet, I was still editing it.

**Comment by Melkor333** [comment]
In my opinion it makes way more sense as it his right now.
I don't want to be able to accidentally delete a buffer with `:bd` when something's not written and like that I don't want to accidentally kill an open shell if any process may be running inside of it without enforcing it.

**Comment by still-dreaming-1** [comment]
@Melkor333 The problem with the behavior as described here is you can never delete a terminal buffer using `:bd`. It is not like sometimes it won't let you do that if there is a running process and sometimes you can if there is not, unless that has changed since this was reported.

**Comment by justinmk** [comment]
@still-dreaming-1 :+1:

**Comment by arcseldon** [comment]
Am in total agreement with the OP on this. The issue remains Open almost 2 years on. Any update on plans to support this?

**Comment by arcseldon** [comment]
For now, just use `bd!` - frustratingly `:bw` doesn't work so `https://github.com/jlanzarotta/bufexplorer` cannot be used to delete the buffer using either the `bd` or `bw` commands

**Comment by arcseldon** [comment]
Just in case others use the vim `bufexplorer` plugin, have added a [Feature Request](https://github.com/jlanzarotta/bufexplorer/issues/69) - as that was my primary motivation for asking here too :)

**Comment by kdheepak** [comment]
I'm also interested in this feature. Are there any plans to add this?

**Comment by mitchellwrosen** [comment]
Hi, I see this issue has been resolved but I'm still experiencing this with stock neovim:

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld11

Features: +acl +iconv +tui
```

I'm unable to close a fresh terminal (opened with `:term`) using `:bd`. Do I misunderstand the issue or the fix? Thanks.

**Comment by zeertzjq** [comment]
Only works if job is already stopped

**Comment by mitchellwrosen** [comment]
Yeah - does the shell itself count as a "job"? I would assume no - otherwise, it seems just as convenient to kill a terminal buffer (using `Ctrl+D` in the shell) as it is to use a vim command `:bd!`. I'm not even sure how to kill the shell, but keep the buffer alive, then close the buffer with `:bd`.

**Comment by nyngwang** [comment]
> I'm not even sure how to kill the shell, but keep the buffer alive [...]

Did you mean to keep the window there(replacing the terminal buffer with normal one) after the shell itself gets closed?

**Comment by weibeld** [comment]
It seems that when you exit the shell with `exit`, you can delete the buffer with `:bd`. However, as long as the shell is running (even if no other command is running), you need to use `:bd!`.
