### ISSUE TITLE
Behavior of init.vim autocommands has changed, due to neovim's enabling syntax and filetypes by default

### ISSUE THREAD

**Issue by bradst** [neovim/neovim#4684]
- Neovim version: 0.1.4 [git HEAD](https://github.com/neovim/neovim/commit/cd3461b0047a7327d08ffd30b8d30fd6b92da399)
- [?] Vim behaves differently? Vim version:
  - vim does not run `filetype plugin indent on` and `syntax on` by default
- Operating system/version: Arch Linux
- Terminal name/version: any
- `$TERM`: any
### Actual behaviour

[Since recently](https://github.com/neovim/neovim/pull/4223), neovim enables filetypes and syntax by default. [Following HEAD](https://github.com/neovim/neovim/wiki/Following-HEAD) states that users can simply delete those lines from their configuration. However, if the user removes `filetype plugin indent on` from their configuration, `autocmd FileType` lines in `init.vim` may no longer override settings applied by a filetype plugin. For example, `autocmd FileType * setlocal formatoptions-=ro` does not override `formatoptions` applied by a filetype plugin unless `filetype plugin indent on` has _already_ been run before the autocommand is defined. The new syntax/filetype default is applied by neovim _after_ init.vim, so if `filetype plugin indent on` is removed from `init.vim`, affected autocommands will not work as expected.
### Expected behaviour

User configurations should continue to work as expected, or documentation should be updated to inform users how to update their `init.vim`.
### Steps to reproduce using `nvim -u NORC`

This issue depends on a minimal `init.vim`, so here are two:

This is an example of a working config before neovim supported enabling syntax/filetypes by default:

```
" before.vim
filetype plugin indent on
autocmd FileType * setlocal formatoptions-=ro
```

This next config is an example of a user following the documentation and removing the `filetype` line, which is assumed to be redundant with the new default:

```
" after.vim
autocmd FileType * setlocal formatoptions-=ro
```

We also need a file that will trigger an `ftplugin` which sets `formatoptions`:

```
$ echo '# comment' > test.conf
```

Now we are ready:

```
nvim -u before.vim test.conf
:set fo?
```

You should see `formatoptions=jcql`. This is the expected behavior; `ro` options have been removed by the autocommand.

```
nvim -u after.vim test.conf
:set fo?
```

You should see `formatoptions=jcroql`. The `ro` options have **not** been removed by the autocommand.

**Comment by justinmk** [comment]
Confirmed. The old behavior accidentally works because users "probably" call `:filetype plugin indent on` _before_ setting up autocmds. So the user's autocmds run after the `:filetype` autocmds. 

A workaround is to setup the FileType handler on VimEnter:

    au VimEnter * au FileType * setlocal formatoptions-=ro

However that workaround doesn't work for files loaded from the command line (`nvim file1 file2 ...`), because VimEnter happens _after_ those files are loaded. `:edit` on the buffer fixes it.

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/7367
