### ISSUE TITLE
tempfile_spec.lua fails

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#4685]
... on current master (https://github.com/neovim/neovim/commit/cd3461b0047a7327d08ffd30b8d30fd6b92da399). The reason is that upon [creation of a tempdir](https://github.com/neovim/neovim/blob/cd3461b0047a7327d08ffd30b8d30fd6b92da399/src/nvim/fileio.c#L5123) a socket named '0' is created in that directory, so that [this assertion](https://github.com/neovim/neovim/blob/cd3461b0047a7327d08ffd30b8d30fd6b92da399/test/unit/tempfile_spec.lua#L24) fails (actually it could of course also be the other lines of the test that create the socket as a side effect).

I reverted the changes to `fileio.c` until 2dfc8de1cf59a2db2b873837946549f631d06d71, but the test still would fail. I haven't even been able to find out if the test is wrong or the behavior of nvim, so maybe someone else can look at this. Thanks!

Also, there is this weird issue where `make unittest` fails with a Segfault and outputs

> 
> [55/55] cd /home/pips/Devel/neovim/neovim/build && /usr/bin/cmake -DBUSTE...d -DTEST_TYPE=unit -P /home/pips/Devel/neovim/neovim/cmake/RunTests.cmake
> FAILED: cd /home/pips/Devel/neovim/neovim/build && /usr/bin/cmake -DBUSTED_PRG=/home/pips/Devel/neovim/neovim/.deps/usr/bin/busted -DLUA_PRG=/home/pips/Devel/neovim/neovim/.deps/usr/bin/luajit -DWORKING_DIR=/home/pips/Devel/neovim/neovim -DBUSTED_OUTPUT_TYPE=utfTerminal -DTEST_DIR=/home/pips/Devel/neovim/neovim/test -DBUILD_DIR=/home/pips/Devel/neovim/neovim/build -DTEST_TYPE=unit -P /home/pips/Devel/neovim/neovim/cmake/RunTests.cmake
>●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●-- Output to stderr:
> E474: No container to close: ]
> E474: Closing list with curly bracket: }
> E474: Closing dictionary with square bracket: ]
> E474: Trailing comma: ]
> E474: Expected value after colon: }
> E474: Expected value: }
> E474: Comma not inside container: ,
> E474: Duplicate comma: ,1]
> E474: Comma after colon: ,}
> E474: Using comma in place of colon: ,}
> E474: Leading comma: ,}
> E474: Leading comma: ,]
> E474: Colon not inside container: :
> E474: Using colon not in dictionary: :]
> E474: Unexpected colon: :}
> E474: Duplicate colon: :1}
> E474: Expected null: n
> E474: Expected true: t
> E474: Expected false: f
> E474: Unfinished escape sequence: "\
> E474: Unfinished unicode escape sequence: "\u"
> E474: Expected four hex digits after \u: \uXXXX"
> E474: Unknown escape sequence: \?"
> E474: ASCII control characters cannot be present inside string: ^I"
> E474: Only UTF-8 strings allowed: <c2>"
> E474: Only UTF-8 code points up to U+10FFFF are allowed to appear unescaped: ?"
> E474: Expected string end: "
> E474: Failed to convert string "?" from UTF-8
> E474: Missing number after minus sign: -
> E474: Missing number after decimal dot: -1.
> E474: Missing exponent: -1.0e
> E474: Unidentified byte: ?
> E474: Trailing characters: ?
> E474: Unexpected end of input: [1
> E474: Missing number after minus sign: -
>
>CMake Error at /home/pips/Devel/neovim/neovim/cmake/RunTests.cmake:39 (message):
>  Running unit tests failed with error: Segmentation fault.

(The dotted chars don'tshow up in my xterm, this is what c&p carries over). This is related to [decode_spec.lua](https://github.com/neovim/neovim/blob/master/test/unit/eval/decode_spec.lua#L87), but running `TEST_FILE=test/unit/eval/decode_spec.lua make unittest` passes successfully.

**Comment by KillTheMule** [comment]
Ok, so the socket is the listening socket  from the msgpack-rpc server, see https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/server.c#L39 and https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/server.c#L79. That tells me that it's supposed to be there and the test needs to be fixed. This is contained in oni-link's https://github.com/neovim/neovim/pull/4646.

That leaves the weird failure of decode_spec.lua. Can anyone confirm that this is happening for other people, or did I screw up something here?

**Comment by justinmk** [comment]
> That leaves the weird failure of decode_spec.lua. Can anyone confirm that this

tempfile_spec.lua is the only unittest failing for me on 2 different systems.

**Comment by jamessan** [comment]
@KillTheMule If you change https://github.com/neovim/neovim/blob/master/src/nvim/regexp_nfa.c#L6081 to call `fast_breakcheck` instead, does that make the crash go away?

**Comment by KillTheMule** [comment]
Hey yeah, that did indeed make the error go away!

**Comment by jszakmeister** [comment]
I don't know if I have the right fix (I thought about adding the socket to the list of acceptable entries), but I took a different approach in #4718 and deleted the temp folder both before and after the test--at the moment, the area is only cleared after the test, and it doesn't take into account a previous test may have littered the temp area.  That seemed to help, though I wonder if we should be looking at the directory contents at all.
