### ISSUE TITLE
Crash on ex commands (e.g. `:a` or `:i`)

### ISSUE THREAD

**Issue by Qeole** [neovim/neovim#4686]
- Neovim version: Ubuntu PPA version (0.1.5+) (see also error message below)
- Bug was first noticed on 2016-04-29
- Operating system/version: Kubuntu 16.04 (4.4.0-21-generic)
- Terminal name/version: Konsole (Qt: 5.5.1 / KDE Frameworks: 5.18.0 / Konsole: 15.12.3)
- `$TERM`: xterm

### Actual behaviour

Segmentation fault when trying to enter a ex command, such as `:a` (append) or `:i` (insert).

Error message:

    nvim: /build/neovim-7CtV1h/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu16.04.1/src/nvim/ex_getln.c :4297 : hist_char2type:  l'assertion « false » a échoué.

(In English: _“false” assertion has failed_)

### Steps to reproduce using `nvim -u NORC`

1. Open neovim (`nvim -u NORC`, or with a init.vim file for what it matters here).
2. In normal mode, type `:a` (or `:i`) and hit `<Enter>`.

### GDB output

    (gdb) set logging on
    Copying output to gdb.txt
    (gdb) run nvim
    Starting program: /usr/bin/nvim nvim
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff55ff700 (LWP 26394)]

    Thread 1 "nvim" received signal SIGABRT, Aborted.
    0x00007ffff6f0e418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type. # English: No file or directory of this type
    (gdb) bt
    #0  0x00007ffff6f0e418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00007ffff6f1001a in __GI_abort () at abort.c:89
    #2  0x00007ffff6f06bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x641a7c "false", 
        file=file@entry=0x64c6f0 "/build/neovim-7CtV1h/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu16.04.1/src/nvim/ex_getln.c", line=line@entry=4297, 
        function=function@entry=0x64cb70 "hist_char2type") at assert.c:92
    #3  0x00007ffff6f06c82 in __GI___assert_fail (assertion=0x641a7c "false", file=0x64c6f0 "/build/neovim-7CtV1h/neovim-0.1.2ubuntu1+git201604292220+2458+19~ubuntu16.04.1/src/nvim/ex_getln.c", 
        line=4297, function=0x64cb70 "hist_char2type") at assert.c:101
    #4  0x00000000004b7ee9 in ?? ()
    #5  0x00000000004bc951 in ?? ()
    #6  0x0000000000497832 in ex_append ()
    #7  0x00000000004adcc7 in do_cmdline ()
    #8  0x0000000000520753 in ?? ()
    #9  0x0000000000529a29 in ?? ()
    #10 0x00000000005b3a34 in state_enter ()
    #11 0x0000000000520d06 in normal_enter ()
    #12 0x00000000004300b1 in main ()
    (gdb) c
    Continuing.
    Impossible d'obtenir les registres: Aucun processus de ce type. # English: Impossible to get the registers: No process of this type.
    Impossible d'obtenir les registres: Aucun processus de ce type.
    Impossible d'obtenir les registres: Aucun processus de ce type.
    [Thread 0x7ffff55ff700 (LWP 26394) exited]

    Program terminated with signal SIGABRT, Aborted.
    The program no longer exists.
    The program is not being run.

**Comment by ZyX-I** [comment]
I am wondering whether I should mark this as duplicate if bug was created *after* the PR which fixes it (#4676).

**Comment by Qeole** [comment]
Erf, I am so sorry I missed it :-/
Does the fact that it was created after the fix prevent it from being a duplicate?

**Comment by ZyX-I** [comment]
@Qeole The problem is that PR which fixes it is a *PR* (@watiko posted this issue as a comment: https://github.com/neovim/neovim/pull/4593#discussion_r61580174). And this is an *issue*. So I am not really sure this should be closed immediately as a duplicate or kept until merging the PR.
