### ISSUE TITLE
install trouble

### ISSUE THREAD

**Issue by marcus7777** [neovim/neovim#4687]
after 

    sudo add-apt-repository ppa:neovim-ppa/unstable
    sudo apt-get update

    ...
    http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/jessie/main/binary-amd64/Packages 404

**Comment by wlhlm** [comment]
> ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/__jessie__/main/binary-amd64/Packages

It appears you're trying to use the _Ubuntu_ PPA under Debian, which is not supported. See #2211 for Debian packages.

**Comment by justinmk** [comment]
Thanks @wlhlm
