### ISSUE TITLE
add option to automatically delete swap file if recovery succeeds and matches file contents

### ISSUE THREAD

**Issue by johnLate** [neovim/neovim#4689]
Enhancement request:

When neovim loads a file that already has an existing swap file and the user has chosen "recovery", one possible result is "Recovery completed. Buffer contents equal file contents. You may want to delete the .swp file now."

For me this means that I will perform these steps after a crashed session: `nvim FILE` -> `r`ecover -> "Buffer contents equals file contents." -> `:e` -> `d`elete.

It would be very convenient if the swap file was deleted automatically in that case. I think it should be an option.

Let's say an option will be introduced and it will be called "autodeleteredundandwapafterrecovery", then the message could be altered to:

- "You may want to delete the .swp file now (**no**autodeleteredundandwapafterrecovery)."
- "The .swp file has been deleted (autodeleteredundandwapafterrecovery)."

(The option should get a better name, of course.)

**Comment by justinmk** [comment]
This is covered by https://github.com/neovim/neovim/issues/1455, if I'm not mistaken.
