### ISSUE TITLE
Terminal Mode Very Fragile About Exiting From Normal Mode

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#4709]
- Neovim version: v0.1.3-366-ga9e0d73
- [x] Vim behaves differently? Vim version: N/A
- Operating system/version: 10.11.4
- Terminal name/version: iTerm2 nightly
- `$TERM`: screen-256color

### Expected behaviour

Typically when working with windows/tabs, the mode that you're in when you exit the original window/tab is the same mode you're in when you get to your destination window/tab.  This is difficult to see when using they keyboard to navigate (since you have to be in normal mode typically to switch), but I tested it with the mouse and inside insert mode and behaves consistently.

### Actual behaviour

Coming back to a terminal buffer, even if I left it in normal mode, reverts it to terminal mode.

### Steps to reproduce using `nvim -u NORC`

* `nvim -u NORC`
* `:tabe | term ls`
* Enter normal mode by pressing `<C-\><C-n>`
* Switch tabs back to the first (you're in normal mode as expected)
* Switch tabs back to the terminal tab (you're back in terminal mode)
* Press a key to move the cursor (since you should be in normal mode)
* Tab closes

**Comment by jfelchner** [comment]
BTW, I can see why there's an argument for this case if the terminal connection is still open, but in my opinion should not be the case if the process has finished.

**Comment by justinmk** [comment]
> Switch tabs back to the terminal tab (you're back in terminal mode)

 This is not default behavior. You must have an autocmd or plugin doing this.

**Comment by jfelchner** [comment]
@justinmk I'll message back here when I track it down.  Sorry for the bother.
