### ISSUE TITLE
terminal: conditionally wait for "Process exited" keypress

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#4713]
I have a request, and I'll leave it up to the more knowledgeable maintainers to tell me if this is reasonable or if there's an underlying issue that would make more sense to fix.

I often run things via keyboard shortcuts:
- tests
- custom git commands
- custom shell commands

where, I know 99% of the time they're going to run successfully and when they run successfully, I don't care about the output.  However after each run I have to press a key to clear the screen.  Although a minor issue, doing it dozens of times a day starts to get annoying.

So my question is, would there be a way to pass something to `term` that could say "Hey, if this thing runs successfully, just close the window, otherwise, wait for me to press a key."?

**Comment by bfredl** [comment]
If you start the terminal using `termopen()` you can specify a job exit handler, that depending on status could close the terminal (say, if it is focused).

**Comment by justinmk** [comment]
I have some ideas for this.

**Comment by jfelchner** [comment]
@justinmk odds something like this will make it into the next release?

**Comment by rafaqz** [comment]
+1 

Also any ideas how to actually skip the required keypress using a termopen() on_exit handler? as a workaround?

**Comment by manasthakur** [comment]
@justinmk Any updates on this?

**Comment by FractalWire** [comment]
@justinmk Any updates on this ?

**Comment by jfelchner** [comment]
@justinmk does any code updates within the last few years make this easier to accomplish?

**Comment by JosefLitos** [comment]
Maybe we can do it for a basic terminal, but what about let's say ranger? If I use that plugin, it stays opened in my buffer until I go there and give it an <Enter>.
