### ISSUE TITLE
`"+y` only can copy 77 lines.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#4719]
- Neovim version: master
- Operating system/version:arch
- Terminal name/version:termite
- `$TERM`:xterm-termite

### Actual behaviour
can not yark more than 77 lines to neovim.but paste to firefox works well.please see the reproduce way
### Expected behaviour
make paste works well.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
1.` V` " select current line
2. `77j`  " selete 78 lines
3. `"+y` yark to `+`
4. switch to other neovim opened in another terminal windows. `"+p` paster. will get `E353: Nothing in register +`
5. but in firefox or other apps, `ctrl + v` works well

**Comment by wsdjeg** [comment]
BTW, I am using `xsel`

**Comment by bfredl** [comment]
so yank actually works put paste doesn't? Does it not depend how long those lines are? It is more likely we are hitting some bytes limit in job control than 77 lines being special.

**Comment by wsdjeg** [comment]
@bfredl yes, it depend the length of the lines. I just tried in other file, it is 90+ lines.yank works well with any lines.but paste doesn's,but `ctrl + v` works well in other app, such as firefox,so I think it is issue with neovim's paste function

**Comment by wsdjeg** [comment]
I just try this file;
https://github.com/wsdjeg/DotFiles/blob/master/syntax_checkers/java/javac.vim

yank from line 344, then only 77 line works well

**Comment by justinmk** [comment]
@wsdjeg Does #4646 fix this issue?

**Comment by wsdjeg** [comment]
@justinmk no,I still get this message `E353: Nothing in register +`

**Comment by wsdjeg** [comment]
which tools do you recommend to use? xclip or xsel or something else?

**Comment by wsdjeg** [comment]
@bfredl maybe it is same issue as 
https://github.com/kfish/xsel/issues/13

**Comment by wsdjeg** [comment]
@bfredl @justinmk I just test with `xclip`, it works well, so I switch to using xclip. and this issue is because xsel only can deal with less than 40000 chars.

so clossing.

**Comment by justinmk** [comment]
https://github.com/kfish/xsel/pull/16 was merged, can we close this?

**Comment by wsdjeg** [comment]
@justinmk yeah , thanks
