### ISSUE TITLE
Unrelated (beyond the range) text getting highlighted when substitution

### ISSUE THREAD

**Issue by typeless** [neovim/neovim#4725]
- Neovim version:
NVIM v0.1.5-92-g490804e

- [ ] Vim behaves differently? Vim version:
**Vim 7.4 has the same problem**.

- Operating system/version:
Ubuntu 14.04 Server  64bit

- Terminal name/version:
TeraTerm v4.89 (login via SSH from Windows 10 to the Ubuntu server)

- `$TERM`:
xterm-256color

### Actual behaviour
The matched pattern of **all lines** are highlighted.

### Expected behaviour
The matched pattern of  **the specified range of lines** are highlighted.

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
```
1. Find any text file with more than 10 lines
2. Under normal mode: type the following command,
```
:1,2s/^/\t/g
```

**Comment by justinmk** [comment]
This is how `set hlsearch` works. It shows matches of the last pattern, irrespective of range (which isn't part of the pattern.
