### ISSUE TITLE
windows: shift-insert doesn't paste

### ISSUE THREAD

**Issue by yoava333** [neovim/neovim#4726]
- Neovim version:
- [x] Vim behaves differently? Vim version: 9.4
- Operating system/version: windows 10 x64
- Terminal name/version: neovim-qt
- `$TERM`:

### Actual behaviour
when i do shift+insert instead of paste I'm getting `<S-Insert>`

### Expected behaviour
text pasted from the clipboard.

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
i <S-Insert>
```

**Comment by justinmk** [comment]
Can you respond to the questions in https://github.com/neovim/neovim/issues/4706#issuecomment-216781363 ?

**Comment by justinmk** [comment]
This particular issue is a matter for neovim-qt (it just needs to capture s-insert and invoke paste, if I'm not mistaken)
