### ISSUE TITLE
Random characters get inserted in blanc spaces after scrolling

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#4732]
- Neovim version: .15-129
- [x] Vim behaves differently? Yes Vim version: 7.4.1797
- Operating system/version: Arch Linux
- Terminal name/version: Juicy SSH (android)
- `$TERM`: xterm-256 
### Actual behaviour: Upon loading a document get  random insertion of characters in blanc spaces, after scrolling for example with G. This is using neovim with empty init.vim for testing purposes. This might be a Juicy SSH terminal emulator issue, however there is no such problem with current VIM version. This happens with or without TMUX.

The added characters are removed upon reloading of document. This problem is recent have not had problems with Juicy and neovim in the past. I would try with another SSH client on android but all the others are not even usable really.
### Steps to reproduce using `nvim -u NORC`

Load any document. And scroll for example with G.

nvim -u NORC

?

**Comment by justinmk** [comment]
> The added characters are removed upon reloading of document.

Is it just a visual issue, or is it actually modifying the file contents?

Feel free to re-open if this problem exists on latest master, but please provide steps to reproduce that don't involve a phone.

**Comment by VVVFO** [comment]
I have encountered this as well (extremely rarely but usually with larger files), which is just random characters appearing inside long whitespace (in my case, it was some characters appearing in the long tabbing part in a multi-line Java argument list), it is just a visual glitch and those characters are not really inserted, and navigating to that position and `r<space>` does not remove the phantom character. My Neovim version is v0.2.1-dev on macOS.

**Comment by VVVFO** [comment]
Oh by the way I was using tmux (master branch as of July 2017) last time it occurred. I tried but cannot seem to be able to reproduce it.
