### ISSUE TITLE
[RFC] Convert magic to a string and allow all four options to be configured (magic, nomagic, very magic, very nomagic)

### ISSUE THREAD

**Issue by hashhar** [neovim/neovim#4745]
- Neovim version: NVIM 0.1.5-dev
- Operating system/version: Ubuntu GNOME 15.10
- Terminal name/version: Gnome-terminal 3.16.2
- `$TERM`: xterm-256color

### Actual behaviour
Only `magic` and `nomagic` can be set.

### Expected behaviour
I propose adding the other two options as well and converting `magic` to a string from a boolean that takes:
- `nomagic`
- `magic`
- `very magic`
- `very nomagic`

### Why?
I believe that all of the settings should be accessible to the user and be configurable and saveable (meaning I don't have to type /\v every time). And blackslashitis is bad.

**Comment by justinmk** [comment]
> converting magic to a string from a boolean

That would break plugins.

> configurable and saveable 

Never set `'nomagic'`. It will break many plugins, including built-in such as netrw. `'magic'` is a basic assumption. I would rather propose we _remove_ the option than add extra functionality to it.

You can map `nnoremap / /\v` if you really want searches to always be "very magic". But I don't recommend it, for [this reason](https://www.reddit.com/r/vim/comments/374pxy/moving_up_the_36_chambers_of_vim_entered_the/crjo512), repeated below:

---

`'magic'` is actually a good balance once you get used to abusing `/` as a workhorse for quick-and-dirty motion. Think about it: `.*^$[]` are really useful, but most of the time you want everything *else* to be literal. 

- The default ("magic") mode should be thought of as: only a few *commonly-used* special chars are considered special. This is for quick-and-dirty work. `.*^$[]` are very commonly needed when searching, so they are considered special by default "magic".
    - It's somewhat annoying that `+()` are not special, but again, `+` is a special case of `*` and `()` are for grouping, so this is beyond the common case. 
    - The idea of `'magic'` is that you *usually* want `/` to do a *literal* search (except for the workhorse `$^[].*` functions).
- Any time you're doing real work, use `\v` ("very magic"). Everything that can be special, is special.

When in doubt, just plop a `\v` at the front of your expression.

    :g/\vfoo+/d

**Comment by hashhar** [comment]
Thanks a lot for the detailed response and the reasoning behind this design.
