### ISSUE TITLE
jobstart() documentation unclear about recommended usage

### ISSUE THREAD

**Issue by airblade** [neovim/neovim#4746]
The `jobstart()` docs say:

```
jobstart({cmd}[, {opts}])               {Nvim} *jobstart()*
        Spawns {cmd} as a job.  If {cmd} is a |List|, it will be run
        directly.  If {cmd} is a |string|, it will be roughly 
        equivalent to
            :call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'], ...)
        NOTE: read |shell-unquoting| before constructing any lists 
        with 'shell' or 'shellcmdflag' options.  The above call is 
        only written to show the idea, one needs to perform unquoting 
        and do split taking quotes into account.
```

I can't tell whether I should set `{cmd}` to a list or a string.  Which is "better"?

The [job control usage](https://neovim.io/doc/user/job_control.html#job-control-usage) docs show examples like:

``` viml
 let job2 = jobstart(['bash', '-c', 'for i in ...[snip]'], ...)
```

– which suggests to me that this construction is recommended:

``` viml
:call jobstart([&shell, &shellcmdflag, cmd], ...)
```

But the NOTE in the `jobstart()` docs says, basically, that `[&shell, &shellcmdflag, cmd]` will somehow break in the face of quotes.  The problem the NOTE is talking about sounds (a) a bit tricky and (b) like it has a correct solution.  If that's so, shouldn't it be built into NeoVim?  That would be a lot safer and easier than forcing every person who calls `jobstart()` to figure out whether they need to unquote stuff and how to do it.

Thanks!

**Comment by jamessan** [comment]
If you don't need to leverage any shell-specific functionality, then just run the command directly with a list -- `call jobstart(['command', 'arg1', 'arg2', ...], ...)`.

The problem that docs are referring to when you use a shell (either implicitly by providing a string `{cmd}` or explicitly in a list `{cmd}`) is that you then have to worry the quoting of the command string you give to the shell.

**Comment by airblade** [comment]
By shell-specific do you mean stuff like pipes and redirection?

**Comment by jamessan** [comment]
Yes.

**Comment by airblade** [comment]
Ok, well my `{cmd}` uses pipes and redirection.  Should I make it a string or a list?  And why can't NeoVim figure out the quoting for me?

**Comment by jamessan** [comment]
I'd just make it a string.  Treat it just like you do using `system()`.

As far as the quoting, Neovim can't figure it out for you for the same reason that (Neo)Vim can't figure out the quoting for you when you run commands through `system()`.  How is (Neo)Vim supposed to know what you need quoted or whether you've done appropriate quoting yourself?

**Comment by justinmk** [comment]
Just to be clear, `call jobstart(['command', 'arg1', 'arg2', ...], ...)` _does_ quote each argument literally. But the "string" variant `call jobstart('command "arg1" "arg2"')` of course does not.

**Comment by jamessan** [comment]
> Just to be clear, call jobstart(['command', 'arg1', 'arg2', ...], ...) does quote each argument literally

No quoting should be necessary in that case because the command is directly executed (as if one were using execvp).  There's no shell involved, so there's no need for quoting.  At least that's the implication of

> If {cmd} is a List, it will be run directly.

**Comment by justinmk** [comment]
> There's no shell involved, so there's no need for quoting.

Yep, that's what I mean by "literally". As in, the user doesn't need to worry about quoting--it is "automatic". I was not sure if that was clear in the discussion.

**Comment by airblade** [comment]
Thank you @jamessan and @justinmk, I understand now.  Much appreciated!

**Comment by ZyX-I** [comment]
> – which suggests to me that this construction is recommended:

You understand it wrong. `&shell` plus `&shellcmdflag` may invoke *any* shell, including ones that are not POSIX-compatible. And with *any* argument, including `-i` which will enable aliases which you most likely do not want. Example invokes *exactly* bash, *exactly* non-interactive which means you are much less dependent on the sanity of the user (user may find it convenient to use fish, so he sets shell to /bin/fish and, blah, your script does not work; or has `-ic` in &shellcmdflag and `alias cat=less` which will break your script with `cat -n file`; etc).

So if you need to run your command in shell I would advise against *both* using `&shell` *and* using raw string. `jobstart(['sh', '-c', …])` is better. You must understand that using &shell in any fashion puts restrictions which are close to impossible to even *list*: who knows what user have put there (there are some valid expectations without meeting which user will see many plugins break… assuming your plugin is not the first one on this list that user has tried). Using `['sh', '-c', …]` implies just one restriction: your plugin should be run in some \*nix system (i.e. cygwin, linux, Mac OS, but not windows; depending on what exactly you run you may already have this restriction). Using jobs to emulate pipes is the most verbose variant, but most portable.

Note that once you use `jobstart(['sh', '-c', …])` you can no longer use `shellescape()` to escape strings passed to shell: it is not necessary that `shellescape()` for one shell that is in &shell will work for POSIX shell. You will have to write the replacement yourself.

**Comment by airblade** [comment]
@ZyX-I Ah, of course. Thank you very much.
