### ISSUE TITLE
Color scheme broken / highlight groups fail silently

### ISSUE THREAD

**Issue by bugeats** [neovim/neovim#4747]
- Neovim version: NVIM v0.1.5-172-gd02cfe8
- Operating system/version: OS X 10.11.4
- Terminal name/version: iTerm 2 Build 2.9.20160426
- `$TERM`: xterm-256color

### Actual behaviour

Colors are lost / highlight groups are not taking effect.

### Expected behaviour

Colors groups should take effect. 

I see some recent commits related to highlight groups, and it appears to have broken my color theme. Maybe [my custom color scheme](https://github.com/bugeats/dotfiles/blob/master/src/config/nvim/colors/mine.vim) was relying on buggy features? I am doing some unconventional grouping and linking.

**Comment by justinmk** [comment]
@bugeats Does your colorscheme work in Vim (what version)?

cc @AdnoC

**Comment by bugeats** [comment]
No, doesn't work in Vim.

I developed my custom scheme using Neovim and it's been working for months. It's very possible I'm doing something goofy.

**Comment by justinmk** [comment]
Can  you give a 2-line example of a link/group with expected behavior vs actual.

Are you using `set termguicolors`?

**Comment by bugeats** [comment]
Not using `set termguicolors`, no.

It appears that something deeper has changed:

    brew switch neovim 0.1.0
    nvim -u NONE

Using the command `:hi Normal guifg=#FF0000` does as expected and sets text to red.

----

Now for HEAD:

    brew switch neovim HEAD
    nvim -u NONE

The same command `:hi Normal guifg=#FF0000`, does not change the text color.

**Comment by jamessan** [comment]
Have you seen https://github.com/neovim/neovim/wiki/Following-HEAD#20160511?

**Comment by bugeats** [comment]
Derp. That fixed it. Thanks @jamessan 

@justinmk please close and disregard this ticket.

**Comment by Dridi** [comment]
@justinmk with current master my highlights disappear if I `set termguicolors`, is this a known problem? Is there an issue I can subscribe to? #5294 seems to be the closest match with this one.
