### ISSUE TITLE
Windows: :terminal support

### ISSUE THREAD

**Issue by halfCheese** [neovim/neovim#4748]
- Neovim version: 0.1.5-dev
- Vim behaves differently? Vim version: N.A.
- Operating system/version: Windows 10 x64
- Terminal name/version: nvim-qt & nyaovim
- `$TERM`:
### Actual behaviour

:term results in an error
`E903: Process for command "cmd.exe" could not be spawned`
### Expected behaviour

:term activates the terminal
### Steps to reproduce using `nvim -u NORC`

nvim -u NORC

:term

**Comment by justinmk** [comment]
Current state of `:term` on Windows is dictated by https://github.com/rprichard/winpty/issues/63 and #810.

**Comment by equalsraf** [comment]
I'm unable to test :term in my current environment, but just in case anyone is following #810 now uses the latest winpty version (0.4).

**Comment by justinmk** [comment]
@halfCheese Try #6383

**Comment by tutysara** [comment]
@justinmk How to try #6383, use the development build?

**Comment by justinmk** [comment]
@tutysara On that PR there is an appveyor link. It has "artifacts" for each build type, use one of the artifacts.
