### ISSUE TITLE
Recent neovim updates break true color support 

### ISSUE THREAD

**Issue by Treri** [neovim/neovim#4749]
- Neovim version: homebrew-neovim HEAD(d02cfe8)
- Operating system/version: OS X 10.11.2
- Terminal name/version: iTerm2-2_9_20160426
- `$TERM`: xterm-256color

I installed homebrew-neovim HEAD today, and I found the true color support is broken. Then I uninstalled neovim HEAD, and  installed 0.1.4 from homebrew, it is good.

I used gruvbox colorscheme.

### Actual behaviour
**homebrew-neovim HEAD version**

You can see, vim-airline is also broken

![qq20160513-1](https://cloud.githubusercontent.com/assets/2631733/15242072/80422dd4-1926-11e6-9919-f976cc159985.png)

### Expected behaviour
**homebrew-neovim 0.1.4 version**

![qq20160513-0](https://cloud.githubusercontent.com/assets/2631733/15242093/9bb8c65e-1926-11e6-9ef7-96cf7916c996.png)

**Comment by khalidchawtany** [comment]
@Treri read this section [following HEAD](https://github.com/neovim/neovim/wiki/Following-HEAD).

**Comment by chrisbra** [comment]
you might also need to update vim-airline.

**Comment by Treri** [comment]
Oops 
Thanks all you very much
