### ISSUE TITLE
:Man opens the man page in a new tab by default

### ISSUE THREAD

**Issue by dmerejkowsky** [neovim/neovim#4751]
- Neovim version: 0.1.4
- [x] Vim behaves differently? Vim version: 7.4.1797
- Operating system/version: Linux

### Actual behaviour

`:Man git` opens the man in an other tab

### Expected behaviour

`:Man git` opens a new buffer in the same window

### Notes:

Looks like this was changed by this commit: 4fb75d61c2c52ac25de96763788775f5e2d27dd7, coming from PR #1878

My use case for `:Man` is to be able to copy/paste or read options or examples from the man page. while I'm writing some code. Having it in an other tab is inconvenient.

Maybe we can add an option to make the tab opening optional?

**Comment by justinmk** [comment]
> Looks like this was changed by this commit: 4fb75d6, coming from PR #1878

It was intentional, to avoid clobbering the alternate buffer, layout, etc.

**Comment by dmerejkowsky** [comment]
Looks like we can close this now that the rewrite of the man plugin is merged :)
