### ISSUE TITLE
Clear highlight doesn't work 

### ISSUE THREAD

**Issue by edi9999** [neovim/neovim#4767]
- Neovim version: NVIM 0.1.5-dev
- [x] Vim behaves differently Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28) Included patches: 1-1689
- Operating system/version: Xubuntu
- Terminal name/version:  xfce4-terminal 0.6.3 (Xfce 4.12)
- `$TERM`: screen-256color

### Actual behaviour

The statements still have syntax highlighting

### Expected behaviour

The statements shouldn't have any more syntax highlighting

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e codefile
:syntax on 
:hi Statement term=NONE cterm=NONE ctermfg=NONE ctermbg=NONE gui=NONE guifg=NONE guibg=NONE
```

See this screenshot: (Left is neovim, right is vim) 

![selection_040](https://cloud.githubusercontent.com/assets/2071336/15286398/09c8fee2-1b5d-11e6-8af2-b1992dcd08be.png)

**Comment by edi9999** [comment]
This makes the following colorscheme : https://github.com/robertmeta/nofrils colorful, where its main purpose is to remove most colors

**Comment by justinmk** [comment]
If you revert https://github.com/neovim/neovim/commit/d02cfe80618bb85cc1cc4a19a9cfc69ae64b98af is it fixed?

**Comment by edi9999** [comment]
Indeed, reverting the d02cfe8 fixes it

**Comment by AdnoC** [comment]
Huh, I'l take a look at this. I only tested https://github.com/neovim/neovim/commit/d02cfe80618bb85cc1cc4a19a9cfc69ae64b98af with `hi clear`. I didn't think of manually clearing all the fields.

**Comment by AdnoC** [comment]
I didn't realize I needed to clear the sg_attr field of the highlight group if it was manually cleared. The pull request fixes it.

**Comment by edi9999** [comment]
Works indeed, thanks !
