### ISSUE TITLE
Visual selection to X primary selection does not work

### ISSUE THREAD

**Issue by schoettl** [neovim/neovim#4773]
- Neovim version: 0.1.4
- [x] Vim behaves differently? Vim version: 7.4
- Operating system/version: Arch Linux 1.4
- Terminal name/version: termite
- `$TERM`: screen-256color

### Actual behaviour

`nvim -u NORC`, type some text and select text in visual mode using `v` or `V`.

Now try to paste the X primary selection into another window using middle mouse button. This does not work. Some old primary selection is pasted but not the selected text from nvim.

### Expected behaviour

Selected text should be pasted.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# type some text and select text in visual mode using v or V.
# paste it to another window using middle mouse button.
```

**Comment by DarkDefender** [comment]
Neovim defaults to "mouse=a". Vim defaults to "mouse=". I you want the same default behaviour in neovim just add "set mouse=" in you init file or use shift if you want to copy text without yanking.

**Comment by schoettl** [comment]
I think it does not have anything to do with `mouse`. For the visual selection I use `v` or `V`. Vim brings selected text automatically to X primary.

**Comment by justinmk** [comment]
>  I use v or V. Vim brings selected text automatically to X primary.

Then you or your distro are setting `clipboard=unnamed`. You need to set that in Neovim as well. This works in neovim, except for block-selection (open issue already exists).

**Comment by schoettl** [comment]
`clipboard=unnamed` does not help because it's about yanking, deleting or changing text.

This issue is not about yanking text to any X clipboard. It's about that selected text should automatically goes to X primary selection.

It's rather `clipboard=autoselect`. But `:set clipboard=autoselect` does not work: Invalid argument. Why?

I found that the defaults for `clipboard` are different in vim and nvim.

**Comment by brcolow** [comment]
@schoettl Please see https://github.com/neovim/neovim/pull/3708

**Comment by schoettl** [comment]
Thank you @brcolow ! Good to see that there is an open issue.
