### ISSUE TITLE
add fish syntax highlighting

### ISSUE THREAD

**Issue by aeosynth** [neovim/neovim#4774]
fish is a somewhat popular shell, and it would be nice if syntax highlighting were supported by default

**Comment by brcolow** [comment]
Have you seen https://github.com/dag/vim-fish (or some of the other seemingly more up-to-date forks?)?

Given that:

- It is very easy to add this plugin to your `init.vim` (say by using [vim-plug](https://github.com/junegunn/vim-plug), [dein.vim](https://gitter.im/Shougo/dein.vim), etc.).

- Neovim tries to stay runtime compatible with upstream Vim.

I would say this has little chance of happening unless Vim itself adds ftplugin support for the fish shell. 

However, this will only happen if someone takes on the responsibility of being a maintainer of the syntax file. As you can see from browsing through the various [ftplugins](https://github.com/neovim/neovim/tree/master/runtime/ftplugin), each one has a maintainer listed at the top of the file. If you are interested in being the maintainer of the fish ftplugin I would recommend opening this issue upstream (by either opening an issue on the Vim issue tracker or using the vim_dev mailing list). Then if/when it gets added to Vim, Neovim can quickly add the upstream patch.

**Comment by justinmk** [comment]
For ftplugin/syntax updates, send a PR to https://github.com/vim/vim
