### ISSUE TITLE
Strange Explore behaviour

### ISSUE THREAD

**Issue by tomchipchase** [neovim/neovim#4775]
- Neovim version: 0.1.5-dev
- [x] Vim behaves differently? Vim version: 7.4
- Operating system/version: Debian Jessie
- Terminal name/version:urxvt/9.20
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
Opening an `:Explore` in a split pane is sometimes moving focus back to a different pane, and make it impossible to go back to the pane with Explore tree in it (with keyboard shortcuts, or clicking on it with the mouse). Sometimes triggered by doing a `/` search inside the pane, sometimes triggered just by opening it.

### Expected behaviour
Opening `:Explore` should leave me in the same pane, and not prevent me from selecting it.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

I can't reproduce it 100% every time, but I come accross it every time I use it using my current workflow, which involves opening several split panes running one or two terms, and between 2-3 files displayed in a pane at one time. The problem occurs when I use `:Explore` to try to navigate to open a different file (but not necessarily the first time I try to do it). I have been able to reproduce it as a different user with no `init.vim` file (as sudo).

**Comment by justinmk** [comment]
Could be a bug in netrw (which is full of bugs). Can you confirm it doesn't happen in a newer version of Vim (which ships with newer netrw)?

**Comment by klingberg** [comment]
I also experience this problem in later builds. It works fine in v0.1.4. I have not managed to narrow it down to what triggers the bug, seems quite random. I have not tested newer version of netrw in Vim.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/4890
