### ISSUE TITLE
File detected as HTML incorrectly

### ISSUE THREAD

**Issue by KevinSjoberg** [neovim/neovim#4776]
- Neovim version: NVIM 0.1.4
- [ ] Vim behaves differently? Vim version:
- Operating system/version: OS X El Capitan, Version 10.11.4
- Terminal name/version: iTerm2, Build 2.9.20160510
- `$TERM`: screen-256color

### Actual behaviour

I have a SLIM file, `application.html.slim` which contents a layout written in [Slim](http://slim-lang.com/). Here is an excerpt from the file.

```slim
doctype html
html
  head
    title Application
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "header"

  body class="#{body_class}"
```

Vim and Nvim incorrectly detects this file as html and thus, setting the filetype to `html` incorrectly. The culprit is found here https://github.com/neovim/neovim/blob/master/runtime/scripts.vim#L242-L244. The current regex is too generic and detects `doctype html` as a `<!DOCTYPE` declaration in HTML.

### Expected behaviour

I'd expect Vim and Nvim to not detect the file as `HTML` and by extension not setting the `filetype` setting.

### Steps to reproduce using `nvim -u NORC`

```slim
doctype html
html
  head
    title Slim Examples
    meta name="keywords" content="template language"
    meta name="author" content=author
    javascript:
      alert('Slim supports embedded javascript!')

  body
    h1 Markup examples

    #content
      p This example shows you how a basic Slim file looks like.

      == yield

      - unless items.empty?
        table
          - items.each do |item|
            tr
              td.name = item.name
              td.price = item.price
      - else
        p
         | No items found.  Please add some inventory.
           Thank you!

    div id="footer"
      = render 'footer'
      | Copyright © #{year} #{author}
```

Create a file named `file.html.slim` with the above contents. Then do the following:

```
nvim -u NORC
:e file.html.slim
:filetype detect
:set filetype?
```

**Comment by brcolow** [comment]
Does adding:

```viml
au BufRead,BufNewFile *.html.slim set filetype=slim
```

To your `init.vim` fix the issue?

**Comment by KevinSjoberg** [comment]
@brcolow Yes, this is what I'm currently doing to solve this. I still think we should solve the root cause which is the faulty regex in `scripts.vim`.

**Comment by justinmk** [comment]
So how about a PR? It would be better to send it to https://github.com/vim/vim though.

**Comment by KevinSjoberg** [comment]
@justinmk sure, I'll submit a patch to Vim, shall I submit a PR to Neovim porting it over as well?

**Comment by justinmk** [comment]
@KevinSjoberg We merge the runtime patches in-order, starting with oldest. So no need to send a PR for this individual change, though a catch-up of the runtime patches wouldn't be unwelcome.
