### ISSUE TITLE
:term should expand %, #

### ISSUE THREAD

**Issue by cprn** [neovim/neovim#4777]
- Neovim version: 0.1.5-dev
- [X] Vim behaves differently? Vim version: 7.4 (2013 Aug 10, compiled Oct 21 2015 13:03:51)
- Operating system/version: Ubuntu Gnome 16.04
- Terminal name/version: GNOME Terminal 3.18.2 + Screen version 4.03.01 (GNU) 28-Jun-15
- `$TERM`: screen-256color

### Actual behaviour
`nvim` doesn't wait for input and breaks the command execution instead
### Expected behaviour
`nvim` should wait for input, like `vim` did.

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:!php -a
```

**Comment by jamessan** [comment]
Neovim runs external commands via a pipe, so you're not going to be able to directly interact with them.  You can use the terminal instead -- `:term php -a`.  Or just start a terminal buffer on its own and run `php -a` from the shell there.

**Comment by brcolow** [comment]
For more information please see https://github.com/neovim/neovim/issues/1496

**Comment by cprn** [comment]
`php -a` is just a minimal example from the top of my head needed to reproduce the issue.

The real problem is availability of ex mode `vim`'s features like `%` and `#` expansion and modifiers (see `help :_%`), `<C-R>` coursor sensitive registers unpacking (see `:help c_<C-R>`), special meaning template tags like `<cword>` and `<amatch>` (see `help :<cword>`) - these are all often useful when calling interactive commands and impossible to use in `nvim`(?).

**Comment by justinmk** [comment]
> - `%` and `#` expansion and modifiers (see `help :_%`),
> - `<C-R>` coursor sensitive registers unpacking (see `:help c_<C-R>`),
> - special meaning template tags like `<cword>` and `<amatch>` (see `help :<cword>`)

@cprn I assume you mean that `tabnew | term %` does nothing useful. Because, `:term %` already works.

If we make `:term` open a split (as `:help` does), then `%`, `<C-R><C-W>`, `<cword>`, etc., will be more useful.

**Comment by cprn** [comment]
Okay, I re-edited my comment so it wouldn't confuse any one.

@justinmk No, I meant `ctrl-z` or spawning new terminal window as suggested by **jamessan** and then using `vim` expansions won't obviously work. The `:term` command, though, works nicely and I actually prefer it without opening a new split so I'm fully happy here, thanks again for your help.

**Comment by justinmk** [comment]
@cprn then I don't understand what your request is at present.

**Comment by cprn** [comment]
> Description of this changed `!` behavior should be described in `:help nvim-features-changed`.

**Comment by justinmk** [comment]
This is now mentioned in `:help nvim-features-changed`.
