### ISSUE TITLE
Separate cursor-update events sent to UI

### ISSUE THREAD

**Issue by romgrk** [neovim/neovim#4783]
Currently, cursor "move-to" events are sent indifferently to the [T]UIs, while they should be separated as follow:
- cursor as an insertion-point (user cursor)
- cursor as a draw-point (for the UI; but this assumes a terminal-like interface rendering)

**Comment by justinmk** [comment]
> , cursor "move-to" events 

Specifically the `cursor_goto` UI event.

[Externalizing](https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=label%3Aui-ext%20) UI components ("widgets") somewhat diminishes the need.

However, a backwards-compatible way of addressing this is to simply include an additional item in the `cursor_goto` tuple, e.g.:

    ["cursor_goto", row=Integer, col=Integer, user=Boolean]

**Comment by justinmk** [comment]
Will be addressed by https://github.com/neovim/neovim/pull/8221#issuecomment-379544339
