### ISSUE TITLE
:make - zsh:1: command not found: tee

### ISSUE THREAD

**Issue by breerly** [neovim/neovim#4785]
- Neovim version: 0.1.4
- [ ] Vim behaves differently? Vim version: behaves the same, VIM 7.3
- Operating system/version: OSX 10.11.5
- Terminal name/version: default terminal
- `$TERM`: xterm-256color

### Actual behaviour

```
:!make  2>&1| tee /var/folders/7b/0zlyf0254fjf66sphzcgv24r0000gn/T/nvimCjtI67/2

zsh:1: command not found: tee
shell returned 127

E40: Can't open errorfile /var/folders/7b/0zlyf0254fjf66sphzcgv24r0000gn/T/nvimCjtI67/2
Press ENTER or type command to continue
```

### Expected behaviour

Runs make file

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:make
```

**Comment by justinmk** [comment]
Can't reproduce with bash. Does it only happen with zsh?

**Comment by breerly** [comment]
Happens with bash as well, and ironically, produces the same output:

```
zsh:1: command not found: tee

shell returned 127

Press ENTER or type command to continue
```

**Comment by fwalch** [comment]
@breerly I think you'd need to `:set shell=bash` first.

Cannot reproduce with zsh.. what does `:!which tee` show? `:!tee`?

**Comment by justinmk** [comment]
Seems like an environment problem. Try http://vi.stackexchange.com/ .
