### ISSUE TITLE
RemotePlugin registration fails on Windows

### ISSUE THREAD

**Issue by robinkjoy** [neovim/neovim#4795]
- Neovim version: 0.1.5-dev
- Operating system/version: Windows 7

### Problem
On windows 7 with python3 plugin registration fails and message to run UpdateRemotePlugin keeps popping up. But it **works** if backslashes in plugin path in -rplugin~ file is replaced with forward slashes. Example:
```
call remote#host#RegisterPlugin('python3', 'C:\Users\user.u\neovimfiles\plugged\deoplete.nvim\rplugin\python3\deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'opts': {}, 'type': 'function'},
     \ ])
```
to
```
call remote#host#RegisterPlugin('python3', 'C:/Users/user.u/neovimfiles/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:true, 'name': '_deoplete', 'opts': {}, 'type': 'function'},
     \ ])

```

**Comment by bfredl** [comment]
the problem is that we generate viml code where we should use a machine readable format (msgpack/json). For now the fix would be to escape the strings.
