### ISSUE TITLE
let vmap = xmap

### ISSUE THREAD

**Issue by Konfekt** [neovim/neovim#4797]
To correct a poor design choice by `Vim`, how about if `NeoVim` by default
- made `vmap` create a map in `visual` mode, but not `select` mode, and
- made `map` create maps in `normal`, `visual` and `operator-pending` mode, but not `select` mode ? 

Poor design choice, 
- because `vmap` looks like it creates a mapping in `Visual` mode and many fall for this trap, and
- because, for example for movement commands, it is common to create a map in `normal`, `visual` and `operator-pending` mode. Currently, this must be achieved by a separate `n/x/omap`.

**Comment by Konfekt** [comment]
I close it for the time being, as it is something to be thought about once NeoVim 1.0 is out and currently has little priority.

**Comment by ZyX-I** [comment]
@Konfekt This is incompatible with Vim and incompatible with current behaviour, so if this is to be thought about once Neovim 1.0 is out then in case of positive resolution actual implementation would be delayed until 2.0. Before 1.0 we can change the behaviour.

**Comment by justinmk** [comment]
No idea why this is still open.
