### ISSUE TITLE
dgj no longer behaves the same as dj

### ISSUE THREAD

**Issue by ibrahimtencer** [neovim/neovim#4803]
- Neovim version: 0.1.5-dev
- [x] Vim behaves differently? Vim version: 7.4
- Operating system/version: Ubuntu
- Terminal name/version:
- `$TERM`: xterm

### Actual behaviour

dgj deletes from the current cursor position to the position directly below it

### Expected behaviour

It should delete the current line and the next line, as in vim.

(Same thing happens for dgk, btw.)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
asdf<cr>jkl;<esc><up><left>dgj
```

**Comment by DarkDefender** [comment]
I think this is an intended change in Vim. I get the same behaviour in Vim 7.4.1821.

**Comment by wsdjeg** [comment]
it is same behaves with vim, not an issue;
