### ISSUE TITLE
End key not working from PuTTY (Home key works)

### ISSUE THREAD

**Issue by mbirth** [neovim/neovim#4809]
- Neovim version: 0.1.5-dev (from Ubuntu PPA, today)
-  Vim behaves differently? Vim version: 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
- Operating system/version: Ubuntu 16.04 on armv7l (Raspberry Pi 2)
- Terminal name/version: PuTTYNG 0.66
- `$TERM`: xterm-256color
### Actual behaviour

End key doesn't do anything. (Works everywhere else, though.)
### Expected behaviour

End key making cursor go to end of line. (Works in vim.)
### Steps to reproduce using `nvim -u NORC`

```
TERM=xterm-256color nvim -u NORC somefile.txt
```

(And then press [End].)

Setting TERM to `putty-256color` makes the End key work. However, as it works with vim and `xterm-256color`, this is kind of a regression.

**EDIT:** Using `putty-256color`, the arrow keys (without any modifier key) jump to the next/previous word instead of the next/previous character. Setting TERM back to `xterm-256color` restores normal behaviour of the arrow keys.

**Comment by justinmk** [comment]
We've upgraded libtermkey since this, and changed some parts of input handling. Please try latest master.

**Comment by mbirth** [comment]
Using the current nightly build (0.1.7ubuntu1+git201701161236+3064+23~ubuntu16.10.1) from the PPA, it's still the same behaviour: End key no worky. Should I try again with tomorrow's nightly?

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/6014
