### ISSUE TITLE
Navigation with netrw splits has stopped

### ISSUE THREAD

**Issue by pengux** [neovim/neovim#4810]
- Neovim version: NVIM v0.1.5-263-g34957f7
- [ ] Vim behaves differently? Vim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 22 2016 09:03:56)
- Operating system/version: Mac OS X, El Capitan 10.11.4 (15E65)
- Terminal name/version: ITerm2 (Build 2.9.20160519-nightly)
- `$TERM`: screen-256color

### Actual behaviour
1. Open a file
2. Create a vertical split.
3. Moving to vertical split
4. Open netrw (explorer) in that new split.
5. Navigate up in the folders twice
6. Cursor automatically jumps to previous split and now you cannot navigate back to the netrw split

### Expected behaviour
6. Be able to navigate back to netrw split with C-w l

### Steps to reproduce using `nvim -u NORC`
1. Type command :Vexplore
2. Open a file
3. Move to right split (C-w l)
4. Type command :Explore

**Comment by justinmk** [comment]
Is it fixed in a later version of netrw?

**Comment by chrisbra** [comment]
Am 2016-05-23 14:34, schrieb Peter Nguyen:
> * Neovim version: NVIM v0.1.5-263-g34957f7
>  	* Vim behaves differently? Vim version: VIM - Vi IMproved 7.4 (2013
> Aug 10, compiled May 22 2016 09:03:56)
>  	* Operating system/version: Mac OS X, El Capitan 10.11.4 (15E65)
>  	* Terminal name/version: ITerm2 (Build 2.9.20160519-nightly)
>  	* $TERM: screen-256color
> 
> ACTUAL BEHAVIOUR
> 
>  	* Open a file
>  	* Create a vertical split.
>  	* Moving to vertical split
>  	* Open netrw (explorer) in that new split.
>  	* Navigate up in the folders twice
>  	* Cursor automatically jumps to previous split and now you cannot
> navigate back to the netrw split
> 
> EXPECTED BEHAVIOUR
> 
>  	* Be able to navigate back to netrw split with C-w l
> 
> STEPS TO REPRODUCE USING NVIM -U NORC
> 
>  	* Type command :Vexplore
>  	* Open a file
>  	* Move to right split (C-w l)
>  	* Type command :Explore
> 

sounds like vim/vim#484 and should be fixed with a newer netrw

**Comment by justinmk** [comment]
Thanks @chrisbra

**Comment by pengux** [comment]
But my vim has patch up to 1832, and that issue is reported to be fixed in 7.4.1368. How can I upgrade netrw?

**Comment by chrisbra** [comment]
On Mo, 23 Mai 2016, Peter Nguyen wrote:

> But my vim has patch up to 1832, and that issue is reported to be
> fixed in 7.4.1368. How can I upgrade netrw?

download the latest version from the upstream author:
http://www.drchip.org/astronaut/vim/#NETRW

Best,
Christian
-- 
Wie man sein Kind nicht nennen sollte: 
  Pit Zabecker

**Comment by pratz** [comment]
I installed the latest version of netrw.vba (:so %), but I am getting below error

```
***sorry*** this version of netrw requires vim v7.4 with patch#1558
```

Neovim version

```
NVIM 0.1.5-dev
```

**Comment by KillTheMule** [comment]
As you can see at https://neovim.io/doc/reports/vimpatch/, patch 1558 is not yet ported to nvim. You could try the netrw from here: https://github.com/vim/vim/commit/e0fa3742ead676a3074a10edadbc955e1a89153d.

**Comment by pratz** [comment]
@KillTheMule thanks buddy, works fine.

**Comment by killtheliterate** [comment]
May be writing too soon, but I was seeing this happen *every time* I opened a split. I just removed `set autochdir` from my `init.vim` for an unrelated reason, and `netrw` seems to be behaving again. Fingers crossed.

**Comment by justinmk** [comment]
Fixed by https://github.com/neovim/neovim/pull/4890
