### ISSUE TITLE
extended marks

### ISSUE THREAD

**Issue by timeyyy** [neovim/neovim#4816]
I have implemented a python text editor plugin for rich text editing.

I want to have vim style movements. So I implemented pynvimtk.

I need to refactor the rte to work with nvim. I want to Implement a nvim plugin.

The nvim gui would forward all bold/italic etc calls to the plugin. The cursor position and text would be analyzed and the required events generated back to the gui. Saving and loading functions would be provided that read the marks from the buffer and allow the styling to be persisted.

However a missing feature is arbtirarily named marks. There are a few cases of people asking for this feature on stackoverflow and the like. 

For me personally the new marks could be orthogonal to the existing implementation. I was thinking a similar api to how tk tags work.

This feature would mean the editing of rte documents with nvim inside our nvim guis.

**Comment by bfredl** [comment]
Implementing new marks for plugin should not be hard, the question would be the design. One could imagine storing a hash table mapping strings (arbitrary names) to line numbers, but both simpler and safer would be to map unique mark ids (generated by nvim) to positions.

```
buffer_add_mark(buf, lineno, ...) -> mark_id`
buffer_get_mark(buf, mark_id)
buffer_del_mark(buf, mark_id) #or maybe update_mark
```
where we of course need a distinguishing name for the feature as `get_mark` already exists.

`mark_adjust` could also emit events to plugins that subscribe them when their marks get moved.

**Comment by justinmk** [comment]
> arbtirarily named marks

I've long wanted this as well. Marks are powerful because they follow text edits, so they are very useful for many applications. We need a design as @bfredl mentioned. I also wonder if allowing more marks could have a performance impact, given the extra bookkeeping. Even so, fixing the perf issue would be worth the effort.

**Comment by bfredl** [comment]
For the moment a line renumbering is basically O((nbr of lines in buffer) + (nbr of marks in buffer)) so as long as we don't expect multiple marks per line we should be fine. (plus the operations are conditional increments of integers, so it is hardly an expensive operation anyway)
Of course, that will change if we in the future support marks for positions within lines, but that would be a change that will have much larger repercussions.

**Comment by ZyX-I** [comment]
@bfredl I do not understand how renumbering may depend on number of lines in buffer. See `#one_adjust` used by `mark_adjust()` from `mark.c`: it is O(1) (note that *all* marks are *always* checked, so giving different line1 and line2 will not affect number of `#one_adjust*` calls). Also multiple marks per line are both expected and common: check how many things are already considered marks there.

Also see `mark_col_adjust()` just after that function: positions within lines *are* supported and also *are* adjusted and I see not much reasons to not implement this in `buffer_add_mark`.

**Comment by bfredl** [comment]
I meant the actual cost of moving the lines, but given the complexity of `memline.c` it might amortize to something less. I should have said multiple _number_ of marks per line, in a file with 1000 lines we don't expect a large multiple of 1000 marks.

I see, but why does then not something as simple as inserting text adjust the columns (which is likely the first thing one would check to see if the feature is supported or not)?

**Comment by ZyX-I** [comment]
That function is called in four places, I guess it is simply a “new” addition created for specific purpose (joining lines and reformatting text). Or it is simply too complex to be called always.

I do not know whether this will work, but here is an idea for optimization if `mark_col_adjust` is too slow: `mark_col_adjust` should only queue adjustments and apply them at the same time as GC runs (i.e. when waiting for input), or when any mark is actually requested (queues are per-buffer, using global marks triggers emptying all queues); all entries in queues have unique incremented ID which is also attached to marks and adjustments apply only to less recent marks.

---

I do not see any difference between “multiple marks per line” and “multiple number of marks per line”. Part with “in a file with …” I did not understand at all. Maybe you meant “we don’t expect number_of_marks ~ O(number_of_lines)”?

**Comment by bfredl** [comment]
I just meant that while it is very expected to a have a few lines with many marks, the concern here is the total number of marks, we don't (yet) expect a single line to have multiple marks _on_ _average_ (except for heavy use of `bufhl`, but it already groups  highlights together to a single "mark" for the point of view of `mark_adjust`) . If column adjusting gets more precise, users and plugins will use column marks a lot more (like rich text as @timeyyy mentioned) and the situation will change, of course. 

Ideally a new data structure should equally support the queries "where are these named marks" and "what are all the marks in this line/region" to be very cheap. bufhl currently optimizes only for the later as it expects redraws to happen more often than renumberings and global highlight clearing.

**Comment by timeyyy** [comment]
is the better design here a vim unaware solution? An implementation like any other text editor might have. Completely unaware of jumplist and existing vim marks?

**Comment by bfredl** [comment]
Depends what you mean with "vim unaware". I would expect this to use `mark_adjust`, but I don't see how this feature could be related to the jumplist?

**Comment by timeyyy** [comment]
Jumplist was just an irrelevant example. I meant things such as "mymark.

For the internal implementation I have found 2 nice examples. They seem similar enough. 

https://github.com/GNOME/gtk/blob/master/gtk/gtktextmark.c
http://core.tcl.tk/tk/artifact/ced75a1f1d9c93ff

I will be using them as a basis for the design

**Comment by justinmk** [comment]
@timeyyy how will it follow edits?

**Comment by timeyyy** [comment]
@justinmk as far as i can tell if i call the SET_XFMARK macro things should work. I will start with just a hashmap as @bfredl suggested and we can go from there.

**Comment by timeyyy** [comment]
@mhinz feel free to throw in name suggestions for the new arbitrary marks
we can do a poll after we collect some names

**Comment by mhinz** [comment]
Oh, I was only 63% serious when I said it on Twitter, but it was mainly a reaction to: https://github.com/neovim/neovim/pull/5031#discussion_r70189881

(That said, I actually do prefer `extmark` over `arbmark`.)

**Comment by timeyyy** [comment]
How should i receive and return positions? tk does it as strings

"row.col"

i would be in favour of 2 integers. is it possible to return a tuple or something in c?

**Comment by bfredl** [comment]
Return it as a `ArrayOf(Integer,2)` like `buffer_get_mark` (a list of two numbers in vimscript).

**Comment by timeyyy** [comment]
@justinmk ok so i had no idea how i would follow the edits.

> mark_col_adjust  should only queue adjustments and apply them at the same time as GC runs (i.e. when waiting for input), or when any mark is actually requested

i will do as @ZyX-I suggested and queue all adjustments and then apply them when the gc runs or when the information is requested

**Comment by ZyX-I** [comment]
@timeyyy Note that I will not be surprised if you will find yourself needing to do like I said, *but* apply adjustments to some marks immediately because these marks are used more often.

Other possible hack is “empty queue (applying adjustments to *all* marks) at GC, but apply adjustments to a specific mark when it was requested”: if you have incrementing-only adjustment ID also attached to marks (which was introduced so that *creating* a new mark does not trigger potentially slow adjustment application) this is completely possible.

**Comment by timeyyy** [comment]
@ZyX-I does this queue of adjustments already exist?

**Comment by bfredl** [comment]
I wonder if it is is premature optimization to start with implementing the queuing. We could start with just applying the change directly, and then look in what cases it is too slow. As long as all marks we have accurate column adjustment for are stored in the same btree, we could also just cache the pointer to the current line in this structure, so only marks on the current line would be considered, i.e. when inserting text inside a line.

**Comment by timeyyy** [comment]
is memline.c the correct place to be collection adjustments?

**Comment by ZyX-I** [comment]
@timeyyy Currently adjustments are done in `mark.c`.

**Comment by timeyyy** [comment]
@ZyX-i meant from where should i call `extmark_col_adjust`, all changes to the buffer that modify the colum position will need to tcall this function

**Comment by bfredl** [comment]
There is no specific place, you have to go though the various operations that can change the column (putting/deleting/inserting text/etc) and add the call. (this could be done incrementally)

**Comment by timeyyy** [comment]
ok, i read this from `memline.c` and thought there was some functions that only do editing to the buffer.

>  * memline.c: Contains the functions for appending, deleting and changing the
 * text lines. The memfile functions are used to store the information in

**Comment by bfredl** [comment]
AFAIK memline only operates on entire lines at a time. Look at `ops.c:do_put` for instance, it will ask memline to replace every line changed by a char-wise or block-wise paste.

**Comment by timeyyy** [comment]
@bfredl In the spirit of minimizing calls over rpc, should functions such as mark_next, return a tuple of names and positions? Also mark_names could do the same.

**Comment by bfredl** [comment]
Yes, that would be good.

**Comment by timeyyy** [comment]
[Here](http://blog.atom.io/2015/06/16/optimizing-an-important-atom-primitive.html) is how githum made the atom editor handled moving marks more effectively. :S

**Comment by bfredl** [comment]
Well, as long as this implement marks (and not ranges), there would essentially be two modes, of what happens when text containing the marks get deleted. Either the mark gets removed, or it is placed at the offset where the deleted text once was. Though in the spirit of being a line editor I could imagine a third mode: the mark gets invalidated by any change happening at the same line (not sure it would be very useful; once I thought of this behavior for bufhl, but I didn't implement it back then as it was not a very big benefit for the intended use case).

**Comment by timeyyy** [comment]
> mm, it seems that atom as well are using line/col positions and offsets in their implementation, the article glosses over that by only using single-line example

> Björn Linse 21:34
In fact it does the "optimal" thing: use relative column positions within a line, but absolute columns when comparing marks on different lines

**Comment by bfredl** [comment]
For full reference: https://github.com/atom/marker-index/blob/master/src/native/marker-index.cc

Note it seems quite complex. For instance keeping four hash tables at every node (not only leaves) in the binary three. It is probably better to do something simpler in the first PR, and after that do optimizations profiled by actual usage. Already by the suggestion above we are in a far better position that atom before its optimization: column changes only update marks on the same line, and if we group together marks on the same line, like bufhl does, the cost of line changes will only scale with the number of lines with marks, not the total number of marks.

**Comment by timeyyy** [comment]
I'm having trouble understanding `mark_adjust`

if i have a mark at line 2, and join it with line 1, `col_adjust` will invalidate the mark or `col_adjust_nodal` will set it to line1, 

the args passed to `mark_adjust` in the example above are
`  line1=2, lin2=2, amount=MAX, amount_after = -1`

`col_adjust` does like it should, but how is it that the mark ends up at row1 ?

**Comment by timeyyy** [comment]
found it,  the deleted lines are restored in do_join, although mark_adjust is never called there... code seems quite complex
```
 for (t = (linenr_T)count - 1;; t--) {
    cend -= currsize;
    memmove(cend, curr, (size_t)currsize);
    if (spaces[t] > 0) {
      cend -= spaces[t];
      memset(cend, ' ', (size_t)(spaces[t]));
    }
    mark_col_adjust(curwin->w_cursor.lnum + t, (colnr_T)0, (linenr_T)-t,
 ```

**Comment by teto** [comment]
we are good now, aren't we :) ?

**Comment by bfredl** [comment]
yes, missing pieces is tracked in #13243 and other issues :D
