### ISSUE TITLE
Guide on how to use true color GUI colorscheme in TUI?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#4818]
I'd like to use [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim), which only work in the terminal.

My customized version of base16-eighties looks like this in a GUI:

![screen shot 2016-05-25 at 11 55 31 am](https://cloud.githubusercontent.com/assets/297678/15552580/e1913e98-226f-11e6-9ee8-2963de3ba140.png)

while the same thing in TUI looks like this:

![screen shot 2016-05-25 at 11 57 55 am](https://cloud.githubusercontent.com/assets/297678/15552585/e9587bbe-226f-11e6-88b3-7598b3d43125.png)

How would one make this theme work in TUI?

**Comment by trusktr** [comment]
I also tried 

```
export NVIM_TUI_ENABLE_TRUE_COLOR=1
```

but that result in base16-eighties looking like this:

![screen shot 2016-05-25 at 12 06 50 pm](https://cloud.githubusercontent.com/assets/297678/15552909/7e282324-2271-11e6-920e-f8db5cf3629b.png)

and it also breaks the previously-working-in-tui hybrid theme:

![screen shot 2016-05-25 at 12 10 25 pm](https://cloud.githubusercontent.com/assets/297678/15552929/98282350-2271-11e6-8f45-300ef011c014.png)

**Comment by megalithic** [comment]
@trusktr is this related? https://github.com/neovim/neovim/wiki/Following-HEAD#20160511

**Comment by justinmk** [comment]
The guide is: colorschemes should stop being clever about setting `cterm*` or `gui*`. They should set _both_. Colorschemes which behave differently depending on whether they detect "gui" are broken.

**Comment by ZyX-I** [comment]
@justinmk I do not see that colorscheme depending on gui_running. The single exception at the top of the file is there for different reason and can be easily disabled.
