### ISSUE TITLE
clang 3.4 on OSX asserts while compiling the klib'ed event.c

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#482]
This is just a tracker issue, I've already [described the problem on the llvm bugtracker](http://llvm.org/bugs/show_bug.cgi?id=19351).

**Comment by elmart** [comment]
It seems they finally addressed this. Finally. Let's see if it works for us when it's made available. It's been a long time for us wanting to be able to compile on OS X using last clang.

**Comment by aktau** [comment]
It seems like it'll take until llvm 3.8 to be incorporated. So let's revisit that for next year and keep with AppleClang for the time being :).
