### ISSUE TITLE
Port the new win_getid() function from vim

### ISSUE THREAD

**Issue by pengux** [neovim/neovim#4824]
Some plugins are using the relative new function win_getid() which provides a unique id to windows and this id will remain even if the window numbering changes. But as neovim does not yet implement his function, it throws errors instead.

- Neovim version: v0.1.5-263-g34957f7
- [ ] Vim behaves differently? Vim version: 7.4 (patches 1-1847)
- Operating system/version: Mac OS X
- Terminal name/version: iTerm2
- `$TERM`: screen-256color
- netrw version: Updated May 26, 2016 (v157f)

### Actual behaviour
With latest version of netrw, when the buffer window receive focus it generates an error:

`E117: Unknown function: win_getid`

### Expected behaviour
No error should be generated when a buffer window receive focus again

### Steps to reproduce using `nvim -u NORC`
Cannot reproduce if there are no plugins using the win_getid() function.

**Comment by justinmk** [comment]
Yes, we need to port that patch. PR would be welcome, but we cannot manage issues for every missing Vim patch. Consider porting the patch instead :)

**Comment by Shougo** [comment]
> Some plugins are using the relative new function win_getid() which provides a unique id to windows and this id will remain even if the window numbering changes. But as neovim does not yet implement his function, it throws errors instead.

It seems the plugins error.
They should check `win_getid()` exists.

**Comment by bfredl** [comment]
Solved in #5117
