### ISSUE TITLE
Is it possible to make 'look up in Dash' and 'Search with Google' hotkey selections work?

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#4834]
Here are the hotkeys I am referring too : 

![2016-05-28 at 22 59](https://cloud.githubusercontent.com/assets/6391776/15629950/e44a5cfe-2527-11e6-904e-ecb48e26c36d.png)

Essentially I can select text and then press one of these hotkeys to either search in Google or search documentation in [Dash](https://kapeli.com/dash). However this does not work in vim.

Is there some way I can make it work as I really wish to have these hotkeys be present for me.

Thank you a lot for any help.

- Neovim version: 0.1.4
- Operating system/version: OS X  ver. 11.11.5
- Terminal name/version: iTerm ver.  2.9.2

**Comment by ZyX-I** [comment]
Quick googling found this plugin: https://github.com/rizzatti/dash.vim/blob/master/autoload/dash.vim#L110. I guess you may use similar technique to search with Google.
