### ISSUE TITLE
How to use nvim new bottom line with opened file name for several files?

### ISSUE THREAD

**Issue by a93ushakov** [neovim/neovim#4836]
`nvim 0.1.4`, installed via `linuxbrew`.

**Comment by justinmk** [comment]
What is "new bottom line"? For usage questions, try the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Comment by a93ushakov** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/13286493/15633291/7e64488e-25b1-11e6-9124-6efb264daa19.png)

**Comment by wsdjeg** [comment]
I can not understand what you mean.that is statusline, you can show current file name on the statusline, if you want show all the files you opened, you need plugin, such as vim-airline, but the file list is show on the tab line above.

see my DotFiles, there are some pictures.

https://github.com/wsdjeg/DotFiles
