### ISSUE TITLE
YouCompleteMe code appended randomly when moving around with arrow keys in insert mode

### ISSUE THREAD

**Issue by dvejmz** [neovim/neovim#4838]
- Neovim version: NVIM 0.1.4
- [Y] Vim behaves differently? Vim version: Problem doesn't occur in vim.
- Operating system/version: Have seen this happening on Arch Linux and Fedora 23.
- Terminal name/version: Have seen this occur in urxvt and Konsole 15.12.3.
- `$TERM`:
### Actual behaviour

When in insert mode, the following string will be inserted into the text every time I press the up or down arrow keys.

![snapshot7](https://cloud.githubusercontent.com/assets/9487006/15633068/14af2ed2-259c-11e6-8561-9f40706dabfa.png)

Text transcript of the screenshot:

```
pumvisible() ? "\pumvisible" : "\
```

This occurs often but randomly and it will persist for the entirety of the session. Loading or creating a different file will not fix the issue. It only goes away if neovim is relaunched.
### Expected behaviour

The string is not randomly inserted into the text when moving around with the arrow keys.
### Steps to reproduce using `nvim -u NORC`

This will not occur if no plugins are loaded as I think it's an issue between YouCompleteMe and neovim. Moreover, there is not a concrete set of steps to follow to reproduce it, it just occurs when spending some time editing a file.
### Comments

I am pretty sure this is a conflict between the YouCompleteMe autocompletion plug-in and neovim, as it doesn't occur in vim (latest version, tested on Arch Linux) and it doesn't occur anymore if YCM is disabled in neovim.

From what I can gather, the string that gets randomly inserted (which is always the same string) is part of YCM's code. Any ideas?

**Comment by wsdjeg** [comment]
You should create mini vimrc, now we can not test for it. the issue maybe due to your imap for Up and down;
show me the result of 
`:imap <Up>` and `imap <Down>`

**Comment by wsdjeg** [comment]
and you should use
```vim
        inoremap <expr> <Down>     pumvisible() ? "\<C-n>" : "\<Down>"
        inoremap <expr> <Up>       pumvisible() ? "\<C-p>" : "\<Up>"
```

**Comment by LiamMayfair** [comment]
The output for the commands you told me is the following

    i  <Up>        *@pumvisible() ? '<Up>' : '<C-R>=<SNR>37_FlushBuffer()<CR><Up>'
    i  <Down>      *@pumvisible() ? '<Down>' : '<C-R>=<SNR>37_FlushBuffer()<CR><Down>'

I will also try and add those two lines of code of yours to my init.vim and see what happens.

**Comment by wsdjeg** [comment]
where does you defind the imap for up and down before. where is the `FlushBuffer` func? 

please test by exec the map in vim's cmdline instead of add into init.vim, the config you just added has beed overwrite by other plugin.

**Comment by scps950707** [comment]
I meet this problem too, after google for answer [here](https://groups.google.com/forum/#!topic/ycm-users/Gt7FDiS-06M)
```
Just as a reference to anyone who comes across this with the same issue,  I found that the plugin Townk/vim-autoclose was causing the conflict. This plugin is old and hasn't been updated in a while and causes quite a few other conflicts.
I removed it and used Raimondi/delimitMate instead. 
```
I fix this problem

**Comment by justinmk** [comment]
`$TERM` wasn't mentioned, it's likely a problem there or a wrong `'ttimeout'` (and/or `escape-time` in tmux).

**Comment by AljoschaMeyer** [comment]
Just to potentially save others some googling:
This happened to me only when running inside tmux (with the default configuration). Fixed it by putting `set -s escape-time 0` into the file `~/.tmux.conf`.

**Comment by hbutau** [comment]
If you have  the plugin:Townk/vim-autoclose, please remove it from your .vimrc file. When i disabled it my auto complete works fine

**Comment by calbertts** [comment]
I had to restart vim after removing vim-autoclose to make it work.
