### ISSUE TITLE
Focus events cause redraw

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#4840]
The command `nvim -u NORC -c 'echom "foo"' -c 'mess'` in tmux (with `set focus-events on`), will not stop at the hit-ENTER prompt.
Also, if you then manually call `:mess` the output will be removed (as if Enter was pressed) when focus is lost again.
- Neovim version: v0.1.5-329-g748898b
- Vim behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode
- `$TERM`: tmux-256color

**Comment by wsdjeg** [comment]
@blueyed same issue as #3969?

**Comment by blueyed** [comment]
@wsdjeg 
That's a bit too confusing.

This issue here is apparently related to receiving unwanted info with the search command, too, i.e.:

1. Start search command (`/`)
2. Move focus away from neovim.
3. `<80><fd>a` gets inserted

That's apparently what closes the "hit-ENTER" message then, too?!

Mouse events appear there, too - e.g. left click is `<80><fd>,` (this makes it related to your (initial issue)).

**Comment by revolter** [comment]
I've got the same problem. So if I run `:version` for example and change to another app and back again, the command output window is gone. Though, if I use the search command like in the comment above, I don't get `<80<fd>` printed out.

**Comment by justinmk** [comment]
In general, when an event is received on the queue it causes a redraw. For certain events like FocusLost we should avoid a redraw.
