### ISSUE TITLE
Effects of histdel() does not persist

### ISSUE THREAD

**Issue by justinnhli** [neovim/neovim#4848]
- Neovim version: v0.1.5-215-gc9b1ad3
- [X ] Vim behaves differently? Vim version: 7.3
- Operating system/version: OS X Yosemite (10.10.5)
- Terminal name/version: iTerm 2.1.4
- `$TERM`: xterm-256color

### Actual behaviour
Calling `histdel()` on the command history deletes the history for the current session, but does not persist across sessions.

### Expected behaviour
History should remain deleted on neovim restart

### Steps to reproduce using `nvim -u NORC`

1. Start neovim `nvim -u NORC`
2. Create a command history with `:tabnew`
3. Check that command is saved with `q:`
4. Delete history with `:call histdel(':')`
5. Check that history is cleared with `q:`
6. Quit and restart neovim
7. History in `q:` should remain cleared, but isn't.

**Comment by ZyX-I** [comment]
Vim has exactly the same behaviour:

    % vim -u NONE -i /tmp/viminfo -N --cmd 'call histadd(":", "test")' --cmd cq
    % vim -u NONE -i /tmp/viminfo -N --cmd 'call histdel(":", "test")' --cmd cq
    % cat /tmp/viminfo | grep '^:test'
    :test

Problem is that there is no way to know whether `test` entry is the deleted one or the new one coming from another session (and deleted entries are not actually kept).

The only way to fix this is to keep deleted history entries list, but this again is not going to help if you have more then one Neovim instance running: other Neovim instances will simply write that history line again if they were run before histdel and exit after. And I do not like the idea of keeping deleted entries in the file marked as deleted. Note that e.g. shells have *no* way to delete history entries at all, except for “kill all shells, edit the file” which works with Neovim as well (need to edit with `-i NONE` if done by Neovim).

**Comment by BenSYZ** [comment]
Sensitive info was record in main.shada, but I cannot delete it. Finally, I found out a very ungraceful way to remove the history, but it works: Copy main.shada, edit, and move it back. Open neovim, there will be an error message. Close and reopen it, then there is no error message anymore.

**Comment by justinmk** [comment]
> Sensitive info was record in main.shada, but I cannot delete it.

You can, via `:wshada`. You also didn't say what Nvim version you are using.

**Comment by BenSYZ** [comment]
Sorry for not reading the manual carefully, and thanks for your reply. I've tried `:wshada`, and it works fine.Thanks again!

Because I did not find a solution to solve this problem, I tried to post a way to do it. By the way, my neovim version info:

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```
