### ISSUE TITLE
Error with Python when starting YouCompleteMe on Neovim only

### ISSUE THREAD

**Issue by ChickenNuggers** [neovim/neovim#4850]
- Neovim version: 0.1.4
- [X] Vim behaves differently? Vim version: 7.4.1797
- Operating system/version: Arch Linux
- Terminal name/version: Terminator
- `$TERM`: xterm-256color

### Actual behaviour

YouCompleteMe is unable to load and gives Neovim-specific error output.

### Expected behaviour

YouCompleteMe loads

**Problem is specific to YouCompleteMe with Neovim and therefore could not be reproduced without my Neovim RC file.**

**Relevant issue in [Valloric/YouCompleteMe](https://github.com/Valloric/YouCompleteMe): https://github.com/Valloric/YouCompleteMe/issues/2189**

**Comment by brcolow** [comment]
What exactly do you mean by "the standard Neovim RC file"?

**Comment by ChickenNuggers** [comment]
Sorry, fixed that.

**Comment by bfredl** [comment]
I don't think this is ycm specific. `:python2 print "test"` or `:python3 print("test")` probbaly give the same error.

**Comment by bfredl** [comment]
Do you have latest python package version?
`pip2 install --upgrade neovim`
`pip3 install --upgrade neovim`

**Comment by Shougo** [comment]
Please use nvim-python-doctor and upload the result here.

https://github.com/tweekmonster/nvim-python-doctor

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working and report the results of following all steps mentioned there. The YCM issue doesn't mention any of the steps taken, so probably this will be resolved by following https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working.

**Comment by ChickenNuggers** [comment]
@Shougo the only problems listed was that the python doctor couldn't detect whether the Python package was installed because I installed it the OS-recommended way instead of via pip. It still exists; if I were to install it via pip it would be the exact same without errors. Also @bfredl this happens only when YCM is used. If I take YCM out, it works fine.

**Comment by ChickenNuggers** [comment]
@justinmk I followed the issues for `python-support-isnt-working` and got `/usr/bin/python2` and a blank line - just like running `-u NORC`.

**Comment by justinmk** [comment]
@ChickenNuggers Can you report the results here? There's no information here so far.

**Comment by ChickenNuggers** [comment]
Here's my Vim RC file:

```vimscript
filetype plugin indent on
syntax on

set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set mouse=a
set cmdheight=2
set number
set modeline
set notimeout ttimeout ttimeoutlen=200
set pastetoggle=<F11>
set fillchars+=vert:\ ,fold:―
set cursorcolumn relativenumber cc=80 cul
set clipboard+=unnamedplus

" Automatically place quotes
let g:AutoPairs = {'(':')', '[':']', '{':'}',"'":"'",'"':'"', '`':'`', '<': '>'}
" Color overrides
let g:jellybeans_overrides = { 'VertSplit': { 'guifg': '262626', 'guibg': '262626', 'attr': '', 'ctermfg': '235', 'ctermbg': '235' } }
" Airline and Bufferline
let g:airline#extensions#bufferline#enabled = 1
let g:bufferline_active_buffer_left = '['
let g:bufferline_active_buffer_right = ']'

" set noexpandtab

let g:python_host_prog='/usr/bin/python2'

map Y y$

nnoremap <C-L> :nohl<CR>
nnoremap <C-S> :w<CR>
nnoremap <C-Q> :qa<CR>
nnoremap ,, <C-W><C-W>
inoremap ?? <C-O>:YcmCompleter GetDoc<CR>
inoremap <C-S> <C-O>:w<CR>
inoremap <C-Q> <C-O>:qa<CR>
inoremap jj <ESC>
inoremap <C-K> <C-O>dd
nmap <C-N> :bn<CR>
nmap <C-P> :bp<CR>

filetype off                  " required

"let g:ycm_server_python_interpreter = '/usr/bin/python'
"let g:ycm_confirm_extra_conf = 0

runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" show invisibles
set listchars=tab:▸\ ,eol:¬
nmap <leader>l :set list!<CR>
set nolist

" Syntax highlighting
set background=dark
colorscheme jellybeans

filetype plugin indent on

" UltiSnips configuration
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger=",,"
let g:UltiSnipsJumpForwardTrigger="nn"
let g:UltiSnipsJumpBackwardTrigger="pp"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" UltiSnips filetype automatic
autocmd FileType * exec 'UltiSnipsAddFiletypes ' . expand('<amatch>')

" NERDTree tree
autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Powerline
let g:airline_powerline_fonts = 1
autocmd VimEnter * AirlineTheme wombat

hi Normal ctermbg=none
highlight NonText ctermbg=none
highlight LineNr ctermbg=none
highlight ColorColumn ctermbg=none
```

I'm using the YouCompleteMe plugin and on startup, in `:messages`, I'm getting the error:

```
function provider#python#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
Failed to load python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
```

**Comment by justinmk** [comment]
> If I take YCM out, it works fine.

So `:python print("test")` works? And `has('python')` returns 1?

**Comment by ChickenNuggers** [comment]
Yes, and yes.

**Comment by justinmk** [comment]
Can you confirm that you ran `pip2 install --upgrade neovim`? And, what version of the `neovim` python module does pip report?

**Comment by ChickenNuggers** [comment]
I can't confirm I've run `pip2`; running that makes me uneligible for support for my OS ("bla bla use pacman or gtfo bla bla"). I've found a dependency error that it depends on the `six` module which isn't included as a dependency when it should be. Error's with the OS.

**Comment by justinmk** [comment]
@ChickenNuggers Thanks for followup.

**Comment by bfredl** [comment]
> running that makes me uneligible for support for my OS

You can always use `pip install --user` to avoid messing with files managed by pacman.

**Comment by jtyers** [comment]
For those who hit this issue on Arch, running `pacman -S python-neovim` (i.e. installing the Python client for Neovim) fixes this without having to install `pip` packages.
