### ISSUE TITLE
Reading the shada file sometimes takes a ridiculously long time

### ISSUE THREAD

**Issue by Grimy** [neovim/neovim#4855]
- Neovim version: 0.1.5-dev
- Vim behaves differently. Vim version: 7.4.1718
- Operating system/version: Fedora 22
- Terminal name/version: XTerm(314)
- `$TERM`: xterm-256color

### Actual behaviour

nvim sometimes takes several seconds to start. I attached an `strace` to look at what it was doing; turns out it’s slowly reading the shada file:

```
open("/home/grimy/data/nvim/shada/main.shada", O_RDONLY|O_CLOEXEC) = 15
read(15, "\1", 1)                       = 1
read(15, "\316", 1)                     = 1
...
read(15, "\222\2\304\0053 + 3", 9)      = 9
read(15, "", 1)                         = 0
close(15)                               = 0
```

Omitted from the above snippet are **8533** more `read` calls, for a total of only **82903** characters! Torvalds has an [infamous quote](https://lkml.org/lkml/2012/7/6/495) on this subject (not reproduced here because it’s needlessly offensive). The point still stands that reading an average of *nine bytes* per system call is terrible for performance.

### Expected behaviour

nvim takes ~20ms to start.

### Steps to reproduce using `nvim -u NORC`

I’m not sure, this seems to happen at random. It’s probably dependent on the contents of the shada file.

**Comment by justinmk** [comment]
I've noticed this too on an underpower 32-bit VM. I'm sure it wasn't intentional to read 1 byte at a time, so hopefully this hint will lead to a fix--thanks for digging into it.

**Comment by ZyX-I** [comment]
It was intentional, I was going to replace this with some buffered reader if it would be too slow. Problem is that I have not found ready-to-use buffered readers in the core and forgot to ask about them.

**Comment by jamessan** [comment]
Maybe something like [CCAN]'s [rbuf] module would be useful.

[CCAN]: http://ccodearchive.net/
[rbuf]: http://ccodearchive.net/info/rbuf.html

**Comment by justinmk** [comment]
We have 2 ring buffer implementations, though one of them is rather specialized.

**Comment by ZyX-I** [comment]
That specialized (rbuffer.c?) implementation was what I would consider using for our buffered `fread()`. But one needs this `fread()` implementation at first, and current code does not (or I failed to find) have something like this.

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/4865
