### ISSUE TITLE
E431 on reading TAGS file from R language

### ISSUE THREAD

**Issue by pasha2718** [neovim/neovim#4856]
- Neovim version: 0.1.4
- [x] Vim behaves differently? Vim version: 7.4.1797
- Operating system/version: latest Arch Linux with 4.5.4-1-ARCH kernel
- Terminal name/version: rxvt-unicode (urxvt) v9.22
- `$TERM`: screen-256color  (running under TMUX 2.2)

### Actual behaviour
- From R console, generate TAGS file with `rtags(ofile='TAGS',verbose=TRUE)`
- From Nvim normal mode, invoke `:tag x` command
- Receive error E431: 

```
E431: Format error in tags file "/path/to/correct/TAGS"
Before byte 2
```

### Expected behaviour
- Expect wildmenu of tags in project
- This works in vim 7.4 on the same machine with the same TAGS file

#### Create stub program

```
nvim -u NORC
:e foo.R
a <- function() {}
b <- function() {}
:q
```

#### Run R to create tags file

```
Rscript --vanilla --verbose -e "rtags(ofile='tags',verbose=TRUE)"
```

#### Go back into Nvim to test and fail

```
nvim -u NORC
:tag a
E431: Format error in tags file "tags"
Before byte 2
E426: tag not found: a
```

This happens with TAGS or tags files.  I see that the R-generated TAGS file is in etags format, with a Hex 12, then a file name,length, then letter, Hex 127, function, Hex 1, coordinates.  The vim tags talks about tabs in there, so I'm wondering if this is ctags vs etags or something.  But, vim 7.4 parses this file fine.

(also I *do* contribute monthly on bountysource.com - this is a groundbreaking project)

**Comment by oni-link** [comment]
Looks like rtags only produces tags in Emacs' etags format and support for that format was removed in nvim (`:h vim_diff.txt`).

**Comment by pasha2718** [comment]
Ok that's why, if the support was removed.  So, I'll find a way to convert it; out of scope for this list.  I'll close the ticket with thanks.

**Comment by justinmk** [comment]
universal-ctags has support for R: https://github.com/universal-ctags/ctags/blob/master/parsers/r.c

Could you comment on whether it seems to do a decent job?

Restoring FEAT_EMACS_TAGS isn't terribly intrusive, but it does add enough noise to the source that it does not seem worth keeping if equivalent ctags functionality is available.

**Comment by oni-link** [comment]
`tags` file created with universal-ctags works for me for the given example.

**Comment by pasha2718** [comment]
`tags` file from universal-ctags works with a full-sized project over here.  I'll exuberantly switch over; no need for FEAT_EMACS_TAGS on this end.  Thanks for the quick reply - nvim rocks.
