### ISSUE TITLE
installing through brew overwrites system python

### ISSUE THREAD

**Issue by tkossak** [neovim/neovim#4864]
- Neovim version: 0.1.4
- [x] Vim behaves differently? Vim version:7.4
- Operating system/version: Linux Mint 17.3 x64 Cinnamon
- Terminal name/version: gnome-terminal 3.6.2
- `$TERM`: screen-256color

### Actual behaviour
I install neovim with `brew install neovim/neovim/neovim` and it also installs its own python in `$HOME/.linuxbrew/bin/python` clobbering system `/usr/bin/python` (because during brew installation PATH was updated with `export PATH="$HOME/.linuxbrew/bin:$PATH"`). Is there any way to install/use neovim without clobbering my system python?

```
$ which python
/home/kossak/.linuxbrew/bin/python
```

### Expected behaviour
```
$ which python
/usr/bin/python
```

### Steps to reproduce:

```
brew install neovim/neovim/neovim
which python
```

**Comment by jamessan** [comment]
Shouldn't this be filed against homebrew's neovim formula (or homebrew itself) instead of neovim?

**Comment by justinmk** [comment]
Seems like a linuxbrew issue. Only mention of python in our formula looks pretty harmless:

https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb

**Comment by tkossak** [comment]
I'm sorry for posting in wrong place. I reposted it [here](https://github.com/neovim/homebrew-neovim/issues/159)
