### ISSUE TITLE
Use % to jump between #ifdef & #endif

### ISSUE THREAD

**Issue by gngshn** [neovim/neovim#4866]
- Neovim version:0.15-349
- [ yes ] Vim behaves differently? Vim version:7.4
- Operating system/version:Ubuntu 14.04
- Terminal name/version:gnome-terminal
- `$TERM`:xterm

### Actual behaviour
when the cursor is on the text after #ifdef, the % can not jump to the #endif or #else 
### Expected behaviour
% can do this, because vim can do this
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by hakbra** [comment]
This seems to be an issue with the matchit plugin.
Using nvim -u NONE it works as expected.
However, after doing `:source /usr/local/share/nvim/runtime/plugin/matchit.vim` it does not work anymore. This plugin is not enabled by default in vim which is why it works there.

**Comment by mhinz** [comment]
I can't reproduce this. It should work both ways:

1. `nvim -u NONE`: built-in `%` knows how to handle `#if` etc. by default

1. `nvim -u NORC`: loads the matchit plugin by default (opposed to Vim where `runtime macros/matchit.vim` or `packadd matchit` directly in recent versions is needed)

**Comment by hakbra** [comment]
As expected, `nvim -u NORC` gives a matchit mapping when running `:verb nmap %`:
```
n  %           * :<C-U>call <SNR>4_Match_wrapper('',1,'n') <CR>
Last set from /usr/local/share/nvim/runtime/plugin/matchit.vim
```

Vim does not source macros on startup, but the issue can be reproduced in vim also by running
`runtime macros/matchit.vim` proving that matchit is the culprit

**Comment by gngshn** [comment]
This is the result of the output of :verb nmap % after doing nvim -u NORC
```
n  %           * :<C-U>call <SNR>9_Match_wrapper('',1,'n') <CR>
        Last set from /usr/local/share/nvim/runtime/plugin/matchit.vim
```

**Comment by mhinz** [comment]
There you go, the matchit plugin, which overwrites `%` and gets loaded by default, doesn't do what you want.

If you don't want Neovim to load matchit, put `let loaded_matchit = 1` in your config.

**Comment by justinmk** [comment]
Please file against vim/vim or contact the maintainer of matchit.
