### ISSUE TITLE
restore default cursor shape after exit

### ISSUE THREAD

**Issue by AlexVKO** [neovim/neovim#4867]
- Neovim version: 0.1.4
- Operating system/version: osX El Captain
- Terminal name/version: zsh 5.2
- `$TERM`: iterm3
### Actual behaviour And Steps

When I leave from NEOVIM or when I change tmux panel from NEOVIM,  the cursor shape change
EDIT: It happens outside of tmux as well.

 1)  on terminal
![screen shot 2016-06-02 at 4 56 21 am](https://cloud.githubusercontent.com/assets/8848152/15737922/1ea638c8-287f-11e6-87f5-3569ba4d04ef.png)

2) on nvim
![screen shot 2016-06-02 at 4 57 18 am](https://cloud.githubusercontent.com/assets/8848152/15737944/442dd286-287f-11e6-82d9-2a539a6684f2.png)

3) on terminal
![screen shot 2016-06-02 at 5 00 51 am](https://cloud.githubusercontent.com/assets/8848152/15738227/ba467116-2880-11e6-9202-17cb207c1df0.png)

Even If I remark the "Vertical Bar" option on Iterm preferences...
### Expected behaviour

When I leave the neovim, the cursor shape has to be the default for the iterm3 configuration.

**Comment by justinmk** [comment]
@blueyed is https://github.com/neovim/neovim/pull/3165 relevant here?

**Comment by blueyed** [comment]
@AlexVKO 
Does it only happen with tmux for you?

It happens also without it for me:

    % zsh -f
    % printf "\e[6 q"
    # Cursor is a bar
    % nvim
    # Go to insert mode and back to get a block cursor, then quit.
    # Cursor is a block now.

**Comment by AlexVKO** [comment]
@blueyed 
No, it happens without tmux as well...

**Comment by blueyed** [comment]
JFI: I did not notice this myself probably because I set the cursor shape in my shell itself: block when executing a command, and bar when coming back.

**Comment by jszakmeister** [comment]
I assume this is because NVIM_TUI_ENABLE_CURSOR_SHAPE is enabled, and the cursor shape feature assumes you're default terminal cursor is a block cursor.  Unfortunately, there isn't a way to query the terminal about the current cursor shape, which makes it impossible to restore correctly. :-(  So, if you don't like the behavior, the only real choice right now is to not enable NVIM_TUI_ENABLE_CURSOR_SHAPE.

**Comment by taecilla** [comment]
I know which is the terminal cursor shape. Can I set it back to vertical bar on VimLeave?

**Comment by jszakmeister** [comment]
@taecilla I honestly don't know.  I'd say give it a try and see.  I think the terminal clean up is one of the last things to happen though, so I wouldn't be surprised if it fails.

**Comment by waltarix** [comment]
@taecilla I hope this will help. It works for me.

```vim
autocmd VimLeave * call system('printf "\e[5 q" > $TTY')
```

**Comment by taecilla** [comment]
Thanks @waltarix, but it doesn't work here :( I'm following HEAD, iTerm.

Another annoying detail: Neovim always starts in normal mode so the cursor should be a block however the it is the same as the terminal, a bar in my case.

**Comment by justinmk** [comment]
> Another annoying detail: Neovim always starts in normal mode so the cursor should be a block however the it is the same as the terminal, a bar

That, at least, is trivial to fix.

As [mentioned](https://github.com/neovim/neovim/issues/4867#issuecomment-223725876) and also evidenced by [this vte commit](https://mail.gnome.org/archives/commits-list/2014-November/msg03991.html) as well as [ctlseqs descriptions](invisible-island.net/xterm/ctlseqs/ctlseqs.html), there is no way to query the cursor shape.

Related to https://github.com/neovim/neovim/issues/3688#issuecomment-250934766 I think the best way forward is to expose these behaviors through API methods. So users can do something like this:

    au VimLeave * call nvim_cursor_set_shape("vertical-bar")

**Comment by mfojtik** [comment]
FYI, the only solution that worked for me so far is to add this alias for bash:

```
alias nvim="nvim;printf '\033]50;CursorShape=1\x7'"
```

I think that being able to set the cursor shape on `VimLeave` would be nice.

**Comment by xbeta** [comment]
+1 would love this feature

**Comment by joelostblom** [comment]
If you are running gnome-terminal (and maybe others, I haven't tested) with zsh, a workaround is to enable vi-mode in zsh and make the cursor change shape between command and insert mode (just like in neovim). As per [this SO answer](http://unix.stackexchange.com/a/327572/65850), add this snippet to your `~/.zshrc`:

```bash
### Activate vi / vim mode:
bindkey -v

# Remove delay when entering normal mode (vi)
KEYTIMEOUT=5

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]] || [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ $KEYMAP == main ]] || [[ $KEYMAP == viins ]] || [[ $KEYMAP = '' ]] || [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

# Start with beam shape cursor on zsh startup and after every command.
zle-line-init() { zle-keymap-select 'beam'}
```

**Comment by ryenus** [comment]
based [@mfojtik's solution](https://github.com/neovim/neovim/issues/4867#issuecomment-251646269),  with the function call saved:

```
_RESET_CURSOR='\033]50;CursorShape=1\x7'
PS1="$_RESET_CURSOR$PS1"
```

See [iTerm2 Proprietary Escape Codes](https://www.iterm2.com/documentation-escape-codes.html).

**Comment by justinmk** [comment]
The 'guicursor' option is now respected in the terminal where possible. So it can be used to set cursor shape on VimLeave. This sets all cursor modes to "block" shape, with blinking disabled:

    :au VimLeave * set guicursor=a:block-blinkon0

See `:help 'guicursor'` to set it as needed.

**Comment by FreddieOliveira** [comment]
I'm using macOS, iTerm2, zsh and tmux. But I also experienced the issue on my Ubuntu using gnome-terminal. My original cursor shape is underline and nvim miscofigs it to block. All suggestions here work correctly to restore the cursor shape in the **current tmux pane** when exiting nvim. The problem is, when creating a new pane or window (even after closing nvim), the cursor shape will be messed anyway. It's like if when opening nvim it changes the cursor config inside zsh internal configuration.

To reproduce:
1. Open tmux
1. Open nvim (from now on your cursor shape doomed for the rest of its life)
1. Open a new tmux window/pane (cursor will be messed)
1. Close nvim (cursor will restore to correct shape, **but only here**)
1. Open a new tmux window/pane (cursor continues to be messed)

And that's it. You can't restore it (you have to keep typing those `echo -ne` every time you open a new pane/window). The only way is to close iTerm2 and open again.

**Comment by justinmk** [comment]
@FreddieOliveira please open a new issue.

**Comment by jamessan** [comment]
> All suggestions here work correctly to restore the cursor shape in the **current tmux pane** when exiting nvim. The problem is, when creating a new pane or window (even after closing nvim), the cursor shape will be messed anyway.

Assuming we're waiting to change the cursor style until after we've switched to the alt screen, this sounds like either a terminal or a tmux bug.
