### ISSUE TITLE
No instructions for .vimrc in install docs

### ISSUE THREAD

**Issue by tecfu** [neovim/neovim#4876]
There are no instructions pertaining to ***.vimrc*** on the [install page](https://github.com/neovim/neovim/wiki/Installing-Neovim).

Does neovim use a .vimrc? Is it called something else? Does it have any syntax changes? Will vim-based plugin managers like Vundle and Neobundle work with Neovim? Where is this documentation?

A how-to (or at least a link to a how-to) that explains the correct name of the .vimrc file for neovim, as well as how to install vim plugins in neovim should be present in the ***install*** section of the docs.

**Comment by justinmk** [comment]
It's in the user manual.

**Comment by justinmk** [comment]
I think we should automatically create init.vim if ran without arguments.

**Comment by tecfu** [comment]
While I see that the manual is available online, I don't think there's any compelling reason to exclude this information from the docs on github. 

Its unnecessarily burdensome for a new user to have to consult the manual for this information, its unlikely to be the first place people look, and the 'manual' documentation online is formatted for a terminal and far less accessible than it could be. 

Really, let's improve this.

**Comment by tecfu** [comment]
Reading through the [manual](https://neovim.io/doc/user/starting.html) under the section vimrc, there's no discussion on renaming .vimrc => .nvimrc or anything of the like.

**Comment by KillTheMule** [comment]
It's [here](https://neovim.io/doc/user/starting.html#initialization), also linked [here](https://neovim.io/doc/user/starting.html#$VIM), although the link in the latter does not work.

> Really, let's improve this.

If you have a good idea, I think too that it could use a bit more exposure in the docs.

**Comment by justinmk** [comment]
It's right beneath FAQ on https://github.com/neovim/neovim/wiki

I suppose adding that link to FAQ and Install page isn't bad idea.

**Comment by justinmk** [comment]
Added more pointers on the wiki:

- https://github.com/neovim/neovim/wiki/Installing-Neovim
- https://github.com/neovim/neovim/wiki/FAQ#where-should-i-put-my-config-vimrc

**Comment by tecfu** [comment]
Awesome. Thanks.
