### ISSUE TITLE
When opening multiple instances they all have the same working directory

### ISSUE THREAD

**Issue by BlackEdder** [neovim/neovim#4883]
- `nvim --version`: NVIM 0.1.5-dev
- Vim (version: ) behaves differently?
Yes, each instance has the working directory of where it was opened
- Operating system/version:
Ubuntu (MATE) 14.04
- Terminal name/version: terminology
- `$TERM`: screen-256color

### Actual behaviour

Opening multiple nvim instances (from different locations) will all have the same working directory set

### Expected behaviour

They all set the working directory to the place where opened.

This seems to be dependent on the frontend. nvim-qt works as expected.

**Comment by BlackEdder** [comment]
I thought nvim-qt was working as expected, but after opening a new file with :e the working directory was suddenly changed to another value.

**Comment by KillTheMule** [comment]
Are you sure you do not have `set autochdir` in your init.vim?

**Comment by BlackEdder** [comment]
autochdir is not in my init.vim.

My workflow is always that I go to the root dir of a project and then open nvim/vim there. This allows me to open files relative to the root dir. i.e.:

```
:e source/file1.d
:e source/file2.d
```

autochdir would then change the directory to source/, but that does not happen (and I'd hate that behaviour :) )

**Comment by justinmk** [comment]
Are they all connecting to the same NVIM_LISTEN_ADDRESS?

I can't reproduce this, it would be quite a noticeable bug...

**Comment by BlackEdder** [comment]
I haven't changed the NVIM_LISTEN_ADDRESS, so it uses the default behaviour. 

I am using fish shell, so maybe the way the NVIM_LISTEN_ADDRESS is set in the front end does not work with fish?

**Comment by justinmk** [comment]
Can you provide more details. _Which_ directory do they always have? If you shutdown all instances, and start from a new directory, say `/home/foo/bar/baz` (something that is not a home directory nor root), you're saying every instance thereafter uses that same directory? 

I see you deleted the `nvim -u NORC` part from the issue template... but that's important: we need to be sure plugins aren't getting in the way. So, does it happen with `nvim -u NORC` ?

**Comment by BlackEdder** [comment]
I seem to be unable to reproduce this at the moment.

I tend to not shut down my machine (just suspend) and always have multiple nvim instances open (one per project (different projects have different virtual desktops)). And this has been happening "randomly" on and off over the last couple of months.

Thinking about it it might well happen every time after I updated neovim, without restarting all the instances. 

I'll close this issue for now and try to keep an eye on things. Will re open if it happens again/I can reproduce it.

Sorry for the noise.

**Comment by justinmk** [comment]
No problem, thanks for followup.
