### ISSUE TITLE
add serverlisten() function

### ISSUE THREAD

**Issue by mnosefish** [neovim/neovim#4886]
From  my post at /r/neovim:

> I'd like to create a custom alias in /Applications to Neovim.app using the command NVIM_LISTEN_ADDRESS=/tmp/nvimsocket gnvim so I can get synctex to work properly. This is pretty easy in *nix, but I can't seem to figure out how to do it in OSX. Any ideas?

My understanding is the addition of a `serverlisten()` function would allow this to be specified within init.vim, obviating the need for custom shortcuts or any such thing.

**Comment by mhinz** [comment]
What is the actual problem and how is `serverlisten()` supposed to solve it?

**Comment by justinmk** [comment]
@mhinz The problem is that NVIM_LISTEN_ADDRESS cannot be set at runtime. So I suggested serverlisten().

**Comment by phodge** [comment]
It seems like this issue can be closed now that `serverstart()` is a thing:
https://neovim.io/doc/user/eval.html

**Comment by justinmk** [comment]
@phodge You're right. For the use case @mnosefish describes, `rpcconnect()` is needed. I don't know why I thought a new issue was needed for this. It is covered by https://github.com/neovim/neovim/issues/3119
