### ISSUE TITLE
mkdir() and writefile() expect different character encodings on Windows

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#4889]
- `nvim --version`: 0.1.5-dev MINGW_64 (from https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw, build 926)
- Vim (version: ) behaves differently? No bug.
- Operating system/version: Windows 10
- Terminal name/version: Neovim-Qt
- `$TERM`: ""
### Actual behaviour

`writefile()` fails.
### Expected behaviour

`writefile()` should work in a directory with accented characters created by `mkdir()`.
### Steps to reproduce using Neovim-Qt:

```
call mkdir("nó")
call writefile(["line 1"], "nó/cego")
```

If I manually create the directory `nÃ³`, then Neovim's `writefile()` works.

**Comment by ZyX-I** [comment]
What does `mkdir()` actually create? Also I see that in “if I manually create the directory …” directory name is spoiled, can you use ASCII-only (i.e. something like `n\u00F3` or `n\xC3\xB3`).

**Comment by jalvesaq** [comment]
Sorry, I forgot to say that `nÃ³` is how `nó` (UTF-8) is seen in an text editor that can only see Latin-1.
I am not on Windows now to test again with the escape codes, but the fact is that the second line of the code above does not work, and this is the bug.

The ASCII-only code of `nó` is `n\xC3\xB3` as @ZyX-I has typed.

**Comment by equalsraf** [comment]
Interesting, the call to mkdir seems ok in my system

- `call mkdir("nó")` creates `nó`
- bit try removing the slash and it succeeds `call writefile(["line 1"], "nócego")`, create a file named `nÃ³cego`

f_writefile uses mch_fopen, [which is a defined as fopen](https://github.com/neovim/neovim/blob/master/src/nvim/macros.h#L114), so in this case libuv is not handling it for us. I count \>40 uses of the function.

Probably can reuse what @justinmk already used in https://github.com/neovim/neovim/pull/4837

**Comment by justinmk** [comment]
Use of `acp_to_enc()` in Vim source may (or not) be insightful here.

**Comment by equalsraf** [comment]
I can no longer reproduce this in Windows.

**Comment by jalvesaq** [comment]
I confirm that the bug is fixed. Thank you!
