### ISSUE TITLE
Tutor section 4.2 search doc typo

### ISSUE THREAD

**Issue by wushuzh** [neovim/neovim#4893]
- `nvim --version`: 0.1.4
- Vim (version: ) behaves differently? NA
- Operating system/version: All
- Terminal name/version: NA
- `$TERM`: ""

### Actual behaviour
In Tutor, Lession 4.2 The SEARCH COMMAND line 474
> 1. In Normal mode type the / character. Notice that it and the cursor
       appear at the bottom of the screen as with the : command.

### Expected behaviour
type / will not lead to : command, the description is not correct/accurate.

### Steps to reproduce using `nvim -u NORC`
NA

I've not opened issue before. If I have done anything wrong, please kindly notice me.
```
nvim -u NORC

```

**Comment by KillTheMule** [comment]
The description is accurate, you missed that part:

> **as with the** : command.

**Comment by wushuzh** [comment]
OK, I feel it a bit misleading: Maybe I am wrong, English is not my first language.

Thanks for the quick response.
