### ISSUE TITLE
Failed to build on mac os x(El Capitan)

### ISSUE THREAD

**Issue by xiongmao86** [neovim/neovim#4896]
I try to build the nvim on os x and failed with config.log showing stdio.h not found. When I build jemalloc myself, it turns out OK. 

I checked the different config.log, the problem is the CMake set the DEPS_C_COMPILER as **"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"** and this compiler **doesn't find** stdio.h but **"gcc"** **does**.

I checked the cc -v and find out the CMake version needs to add "-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk". 

It's probably the CMake team's responsibility to change the code. The Darwin Module is old. But it would be nice *to have a work around*. It's difficult to figure out how to write. Can someone please pull a request. Or if you don't have time, I can try to figure it out, with some help.

Thanks.

**Comment by jszakmeister** [comment]
I think you're going to have to show more information here.  FWIW, myself and others build on OS X El Capitan all the time, and it's installable via Homebrew with little issues.  So it seems like something in your environment is the root cause.

**Comment by xiongmao86** [comment]
Well, when I "make" at root, the config.log says can't find stdio.h, but autoconf and configure the checking for gcc found gcc. So either Externalproject_Add is not run in your case, or something with environment is wrong, or bother. So what can we do now? How to rule out the impossible situation?

**Comment by mhinz** [comment]
- When you say `gcc` do actually mean `gcc` or `clang` in disguise? How did you install gcc?
- Please paste the full output of `cc -v` and `gcc -v`.

**Comment by xiongmao86** [comment]
It's clang in disguise, I don't know when I installed it, might be installed by xcode in the posts I searched.

gcc -v:
`
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

cc -v:
`Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/ToolChains/XcodeDefault.xctoolchain/usr/bin`

Oh, I used the <code>button but it still looks like crap...

**Comment by xiongmao86** [comment]
conftest.c:
`/* end confdefs.h.  */
#include <stdio.h>
int
main ()
{
    FILE *f = fopen ("conftest.out", "w");
    return ferror (f) || fclose (f) != 0;

  ;
  return 0;
}
`

cc -v -o conftest conftest.c
`Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/ToolChains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 264.3.102 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0 -fdebug-compilation-dir /Users/Rui-Mac/source/temp/testjemalloc -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/53/w9dxkz7122sbzpqr98tx9vt40000gn/T/conftest-c29704.o -x c conftest.c
clang -cc1 version 7.3.0 (clang-703.0.31) default target x86_64-apple-darwin15.5.0
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
conftest.c:2:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.`

gcc -v -o conftest conftest.c
`Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.11.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 264.3.102 -v -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fdebug-compilation-dir /Users/Rui-Mac/source/temp/testjemalloc -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.11.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/53/w9dxkz7122sbzpqr98tx9vt40000gn/T/conftest-e417bb.o -x c conftest.c
clang -cc1 version 7.3.0 (clang-703.0.31) default target x86_64-apple-darwin15.5.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -o conftest /var/folders/53/w9dxkz7122sbzpqr98tx9vt40000gn/T/conftest-e417bb.o -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a`

**Comment by mhinz** [comment]
Try `xcode-select --install` and follow the instructions. My guess is that you don't even have a `/usr/include` directory which comes with the Xcode developer tools.

**Comment by xiongmao86** [comment]
Oh, you are right. That's my problem. Sorry for the inconvenient.
