### ISSUE TITLE
(Feature request) Hex editor, or an ability to write a plugin for it

### ISSUE THREAD

**Issue by rr-** [neovim/neovim#4901]
I am looking for alternatives to creating [hexvi](https://github.com/rr-/hexvi) which is somewhat huge task for one person, esp. that 90% of the tasks reiterate what has been done in Vim: searching, buffers, tabs, undo, command parsing, hotkey parsing, yadda yadda....

I know of `xxd` trick but it's worthless, as you can't search, view integers, jump to nth byte, do anything actually except for uncomfortable byte insertion and removal. Plus it's unbearably slow for big files.

My proposition is to have better control over things such as `isprint` so we can script our way around it with views of the same buffer.
- `isprint` shouldn't override user settings regarding ASCII characters (including new lines!)
- ability to display character such as `?` or `.` for nonprintable characters
- visual wrap at nth column rather than window edge

This should be enough to have two views of the same buffer with different options.

EDIT: I now see that the msgpack API might be very helpful. I didn't expect it to be this powerful already :+1:

**Comment by justinmk** [comment]
> visual wrap at nth column rather than window edge

https://github.com/neovim/neovim/issues/4386

**Comment by rr-** [comment]
I think it might be also essential to be able to have the lines be divided by n characters rather than the newline character. This lets the line numbers to become row offsets.

Perhaps these options don't make sense alone, but if you combine them (wrap at nth column, always display each character with fixed-width template, split rows by n characters) these are pretty much what defines a hex editor.

**Comment by justinmk** [comment]
> ability to display character such as ? or . for nonprintable characters

That can be done with `matchadd()` and "conceal" feature. Other request is covered by https://github.com/neovim/neovim/issues/4386.
