### ISSUE TITLE
Terminal Can't Scroll Shell (i.e. `!`) Output

### ISSUE THREAD

**Issue by gmatht** [neovim/neovim#4902]
- `nvim --version`: NVIM 0.1.5-dev Build type: RelWithDebInfo Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/build/config -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/src -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-dRTlnv/neovim-0.1.4ubuntu1+git201606080425+2579+20~ubuntu16.04.1/build/include Compiled by buildd@lgw01-23 Optional features included (+) or not (-): +acl +iconv +jemalloc +tui For differences from Vim, see :help vim-differences system vimrc file: "$VIM/sysinit.vim" fall-back for $VIM: "/usr/share/nvim"
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: Ubuntu 16.04
- Terminal name/version: xfce4-terminal 0.6.3
- `$TERM`: xterm

### Actual behaviour

   :!seq 0 200

Displays the last page of output, I cannot scroll with xfce scroll bars or Shift-PgUp, nor using vim navigation keys (i.e. Up Arrow)

### Expected behaviour

Vim navigation keys don't work (Up Arrow), but terminal scrolling works (Shift-PgUp)

### Steps to reproduce using `nvim -u NORC`
nvim -u NORC
:!seq 0 200
Shift-PgUp

**Comment by mhinz** [comment]
`:!` works a bit different in Neovim, yes, but compared to Vim we have two different means to running external commands, `:!` and `:terminal`. The latter should be used for anything interactive or where the output needs to be scrollable (since it's thrown into a terminal buffer).

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes
