### ISSUE TITLE
Automatic history merge between multiple instances

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#4905]
- `nvim --version`: NVIM 0.1.4
- Vim (version: ) behaves differently?
- Operating system/version: OS X - El Capitan
- Terminal name/version: Iterm2
- `$TERM`: xterm-256color

### Actual behaviour
History is not merged "automatically" between nvim instances.

### Expected behaviour
History getting merged automatically between nvim instances.

### Steps to reproduce using `nvim -u NORC`

Run 2 nvim instances (nvim -u NORC), write a command in first and hit enter, hit `:` in second instance and press up, you see history is not merged.
I can share command history by running `:wshada! /tmp/q` in first and running `:rshada! /tmp/q` in second. But it's manually not "automatically".

**Comment by jamessan** [comment]
No where is it claimed that the ShaDa file is merged in realtime.  [:help shada-merging] states

> When writing ShaDa files with `:wshada` without bang or at regular exit 
information in the existing ShaDa file is merged with information from current 
Neovim instance.

If you want the merging to happen automatically during an nvim session, you'll need to setup an autocmd to do so.  Something like

```vim
au CursorHold * wshada | rshada
```

[:help shada-merging]: https://neovim.io/doc/user/starting.html#shada-merging

**Comment by mhinz** [comment]
Or even `FocusGained` and `FocusLost` instead of `CursorHold`, if your terminal emulator supports it.

(Personally I prefer the non-shared history, because I usually use two different processes on purpose.)

**Comment by justinmk** [comment]
Here's what I use:

    augroup nvimrc_aucmd
      autocmd!
      " https://github.com/neovim/neovim/issues/3463#issuecomment-148757691
      autocmd CursorHold,FocusGained,FocusLost * rshada|wshada
    augroup END


https://github.com/justinmk/config/blob/bb1469f870f0a9a8613802513ff5acdf1e1e19fe/.vimrc#L270-L274

**Comment by sassanh** [comment]
Thanks for the info guys, the problem is in the README.md of the project it's written under "What's been done so far" section: "Automatic history merge between multiple editor instances", I guess we should replace "automatic" with "ability to". @jamessan 

I don't know if I prefer the shared history or not. I should try it.
