### ISSUE TITLE
YcmCompleter FixIt crashes with NvimError: Index out of bounds in Nvim 0.1.4

### ISSUE THREAD

**Issue by wreed4** [neovim/neovim#4907]
- `nvim --version`:NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /home/user/wreed/.linuxbrew/bin/gcc-5 -Os -w -pipe -march=native -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/build/config -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/src -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/deps-build/usr/include -I/home/user/wreed/.linuxbrew/include -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/build/src/nvim/auto -I/tmp/neovim-20160609-34338-fhv7mf/neovim-0.1.4/build/include

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/user/wreed/.linuxbrew/Cellar/neovim/0.1.4/share/nvim"

- Vim (version:VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  9 2016 11:58:45)
Included patches: 1-1817
 ) behaves differently?
- Operating system/version: REHL (old)
- Terminal name/version: bash
- `$TERM`: screen-256color

### Actual behaviour
When calling :YcmCompleter FixIt.......
Error detected while processing function <SNR>81_CompleterCommand[18]..provider#python#Call:
line   18:
NvimError('Index out of bounds',)
Traceback (most recent call last):
  File "/home/user/wreed/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 181, in handler
    rv = self._request_cb(name, args)
  File "/home/user/wreed/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/home/user/wreed/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/neovim/plugin/host.py", line 69, in _on_request
    rv = handler(*args)
  File "/home/user/wreed/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 77, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
NvimError: Index out of bounds

### Expected behaviour
Not an error 
### Steps to reproduce using `nvim -u NORC`
Obviously, it can't be reproduced with -u NORC, but here's how to reproduce it normally.
delete the ';' at the end of a line in a c++ file, and call :YcmCompleter FixIt  on that line.  

I've seen related issues, but this was supposedly fixed in march.  Not sure if it's not released yet or something.. Sorry if this is already a known thing. 

https://github.com/Valloric/YouCompleteMe/issues/2018

**Comment by jamessan** [comment]
According to tarruda's [comment] in the YCM issue, this is a bug in [python-client].  Looking at the commit history there, this should have been fixed by neovim/python-client#209.

[comment]: https://github.com/Valloric/YouCompleteMe/issues/2018#issuecomment-193816539
[python-client]: https://github.com/neovim/python-client

**Comment by bfredl** [comment]
It is on python client master but released yet. I will make a release now in the weekend.

**Comment by bfredl** [comment]
python module version 0.1.9 released with the fix.

**Comment by wreed4** [comment]
Works great! Thank you!
