### ISSUE TITLE
Colours have changed in 0.1.5

### ISSUE THREAD

**Issue by pdoak** [neovim/neovim#4910]
- `nvim --version`:0.1.5-dev
- Vim (version: ) behaves differently?
- Operating system/version: OSX 10.11.5
- Terminal name/version:iTerm Build 3.0.20160606-nightly
- `$TERM`:

### Actual behaviour 

After upgrading to 0.1.5 from 0.1.4, the colours have changed using the same colour scheme `oceanic next`. In particular:

1. the background in no longer black
2. the text is no longer white
3. the spelling highlighting is underlined from red

See pictures below

### Expected behaviour

The colours should be the same as under 0.1.4

### Colors using 0.1.4
<img width="983" alt="screen shot 2016-06-11 at 22 15 10" src="https://cloud.githubusercontent.com/assets/1565586/15987555/6f9c68d2-3023-11e6-9742-d81fc4593ff4.png">

### Colors using 0.1.5
<img width="983" alt="screen shot 2016-06-11 at 22 16 13" src="https://cloud.githubusercontent.com/assets/1565586/15987554/51b59d84-3023-11e6-9eaf-069bd8474a61.png">

**Comment by justinmk** [comment]
are you using true color?

**Comment by pdoak** [comment]
Yes, this is in my init.vim

`let $NVIM_TUI_ENABLE_TRUE_COLOR=1`

**Comment by fmoralesc** [comment]
You have to use `set termguicolors` now. See https://github.com/neovim/neovim/wiki/Following-HEAD#20160511

**Comment by pdoak** [comment]
That worked. Thank you. I will make a note to check the changes next time.
