### ISSUE TITLE
Tutor: [d]elete[$] (Lesson 2.2) No confirmation/checkmark

### ISSUE THREAD

**Issue by dragon788** [neovim/neovim#4913]
- `nvim --version`:  0.1.5-dev
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 16.04
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color
### Actual behaviour

Line 231 has a right arrow indicating there is "work to be done" to correct the line.
There is no X to indicate when the task is failing, if you delete after the period it does show the checkmark.
### Expected behaviour

There is an X and then a Checkmark to indicate when the task is completed.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:231 (goto line 231)
f. (goto period)
l (right one character)
d$
```

**Comment by brcolow** [comment]
Ping @fmoralesc

**Comment by fmoralesc** [comment]
I'll try to give some time to this later this week, once I finish the last paper for this semester... ;)
