### ISSUE TITLE
nvim is slowly in tmux

### ISSUE THREAD

**Issue by fundon** [neovim/neovim#4917]
- `nvim --version`: 0.1.4
- Operating system/version: Mac OS
- Terminal name/version: fish 2.3.0
- `$TERM`:  screen-256color

### Actual behaviour

When open nvim in tmux, nvim is very slowly, and when trigger Esc, need some times.

```
time nvim
        7.01 real         3.51 user         1.29 sys
```

### Expected behaviour

Out side the tmux

```
time nvim
        1.54 real         0.21 user         0.11 sys
```

**Comment by fwalch** [comment]
Did you see https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed?

**Comment by fundon** [comment]
I disabled all plugins. Nvim started quickly.

**Comment by mhinz** [comment]
So, can this be closed?
