### ISSUE TITLE
softtabstop's value always set to shiftwidth

### ISSUE THREAD

**Issue by TheDevelo** [neovim/neovim#4921]
- `nvim --version`: 0.1.5-dev
- Vim (version: 7.4 ) behaves differently? Yes, bug does not occur.
- Operating system/version: Linux Mint 17
- Terminal name/version: xterm + screen 4.03.01
- `$TERM`: xterm-256color

### Actual behaviour
softtabstop's value is set to shiftwidth's value even if softtabstop is set to a non-negative number.
### Expected behaviour
softtabstop's value should only be set to shiftwidth's when softtabstop is set to a negative number. Otherwise, softtabstop should be disabled if set to 0 and uses the value set if positive and non-zero.

**Comment by mhinz** [comment]
- Steps to reproduce with `nvim -u NORC`?
- `:set smarttab?`? It's enabled by default in nvim, see `:h nvim-defaults`.

**Comment by TheDevelo** [comment]
Thanks, that was my problem. I feel like an idiot now.
