### ISSUE TITLE
Double left mouse click is not available in tagbar

### ISSUE THREAD

**Issue by gngshn** [neovim/neovim#4922]
- `nvim --version`:NVIM v0.1.5-451-g28cc5a0
- Vim (version: 7.4) behaves differently?
double mouse click in tagbar is OK.
- Operating system/version:
ubuntu14.04
- Terminal name/version:
GNOME Terminal 3.12.3
- `$TERM`:
xterm
### Actual behaviour
Have no effect.

### Expected behaviour
double click on tag can jump to tag.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

in nvim exec
:source ~/.config/nvim/plugged/tagbar/plugin/tagbar.vim
:source ~/.config/nvim/plugged/tagbar/autoload/tagbar.vim
:TagbarOpen

```
double click on tag still have no effect.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/4887
