### ISSUE TITLE
neovim-ppa binary 404 Not Found

### ISSUE THREAD

**Issue by zchee** [neovim/neovim#4926]
I was tried install neovim on CI(Bitbucket pipeline) service.
and, I used the apt-get for install of neovim because troublesome to build on the CI.

but failed install, that url are not found.
http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/jessie/main/binary-amd64/Packages

Is this procedure is deprecated?
https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu
```bash
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim
```

**Comment by jamessan** [comment]
It sounds like you're running Debian (specifically the Jessie release) instead of Ubuntu.  The [PPA] provides packages for Ubuntu.

[PPA]: https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

**Comment by zchee** [comment]
ahh, that's correct!
I used `golang:1.7beta1` docker image, it's based Debian.
https://github.com/docker-library/golang/blob/2372c8cafe9cc958bade33ad0b8b54de8869c21f/1.7/Dockerfile

Thanks! and sorry 😱
close.
