### ISSUE TITLE
Windows: ":!start" spec

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#4927]
From the [removed](https://github.com/neovim/neovim/pull/4923/) `win32-!start` tag:

```
Normally, Vim waits for a command to complete before continuing (this makes
sense for most shell commands which produce output for Vim to use).  If you
want Vim to start a program and return immediately, you can use the following
syntax on W95 & NT:
        :!start [/min] {command}
The optional "/min" causes the window to be minimized.
```

This issue is just a note for future reference. I didn't check whether #810 already address this totally.

**Comment by equalsraf** [comment]
Ultimately `!start` is no different than using `!` with any other command.

If the shell is the default cmd.exe then`!start cmd` and `!start /min cmd` work fine. With shell=powershell there is a `start` alias that produces the same effect, but the `/min` flag causes an error (which is normal).

**Comment by janlazo** [comment]
Is `:h :!start` still relevant after https://github.com/neovim/neovim/pull/6497?
It's not a special command anymore for Neovim in Windows.

**Comment by justinmk** [comment]
That's the purpose of this issue: Vim treats it as yet another special case; should Nvim? I don't know if we should, but at least https://github.com/neovim/neovim/issues/5844 made some related request.

However, Vim's special behavior has its own bugs: https://github.com/vim/vim/pull/1570#issuecomment-287741424 (note: that issue is closed, but it's not actually fixed)

So maybe we should just close this issue (and update the doc). Also would like @ skywind3000's opinion on https://github.com/vim/vim/pull/1570#issuecomment-287741424

**Comment by janlazo** [comment]
For #5844, is it because `:!` commands are expected to escape in Vim with `sxe` and `sxq` but Neovim doesn't use them so the user has to escape the commands themselves?

@justinmk I agree on closing this issue and updating the doc (`:h vim-differences`?).

**Comment by janlazo** [comment]
Is `:!start` also a special case handled by cygwin Vim or does it run `/usr/bin/start.exe`?

**Comment by justinmk** [comment]
As @janlazo [explained](https://github.com/neovim/neovim/issues/5844#issuecomment-295119927) `:!start` in Nvim 0.3 on Windows does not block the UI, so the main purpose is achieved.

Don't need to match Vim bug-for-bug here. Documented in #7783.
