### ISSUE TITLE
neomake E421 guifg guibg error with NVIM_TUI_ENABLE_TRUE_COLOR=1

### ISSUE THREAD

**Issue by chrzrdx** [neovim/neovim#4931]
- `nvim --version`: 
```
NVIM 0.1.4
Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
```
- Operating system/version: Arch Linux, 64-bit
- Terminal name/version: st-0.6
- `$TERM`: `xterm-termite` and `st-256color` and `rxvt-unicode-256color`

### Actual behaviour

Enabling `Neomake` plugin causes error on every first write to file. (This is with the colorscheme `gruvbox` loaded)
```
"init.vim" 28L, 638C written
Error detected while processing function neomake#signs#DefineHighlights:
line   11:
E421: Color name or number not recognized: ctermfg=#fabd2f guifg=#fabd2f ctermbg=#3c3836 guibg=#3c3836
Press ENTER or type command to continue
```
If the `NVIM_TUI_ENABLE_TRUE_COLOR` flag is not set, Neomake doesn't complain. 

Minimal `init.vim` : 
```
" AUTOINSTALL VIM-PLUG {{{
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
"}}}

call plug#begin('~/.config/nvim/plugged')

let $NVIM_TUI_ENABLE_TRUE_COLOR=1

Plug 'benekastah/neomake', { 'on': ['Neomake'] }
autocmd! BufWritePost * Neomake

call plug#end()
```

### Expected behaviour

Should write file gracefully. Loaded colorschemes should enable ctermfg, guifg etc correctly

### Steps to reproduce using `nvim -u init.vim` (minimal init.vim provided)

On any of the three terminals above (`st`, `termite` with truecolour support and `rxvt` without it), execute : `nvim -u init.vim samplefile` and then save the file. Error message pops up.
```
"samplefile" [New] 0L, 0C written
Error detected while processing function neomake#signs#DefineHighlights:
line   11:
E421: Color name or number not recognized: ctermfg= guifg= ctermbg=Grey guibg=Grey
```

**Comment by mhinz** [comment]
This is a neomake issue. Please create an issue for them.

---

Assuming the colorscheme sets this:

```
Question       xxx ctermfg=2 gui=bold guifg=SeaGreen
```

Now, with `$NVIM_TUI_ENABLE_TRUE_COLOR=1` (or `:set termguicolors` in more recent versions), neomake tries to do this:

```vim
hi NeomakeInfoSignDefault ctermfg=SeaGreen guifg=SeaGreen ctermbg=Grey guibg=Grey
```

That doesn't work, `SeaGreen` is no valid value for `ctermfg`. That's where the E421 is coming from.

**Comment by chrzrdx** [comment]
Thank you. I'm now following up on this issue there. :)
