### ISSUE TITLE
Large Foreign-language JSON file triggering E475 on Windows

### ISSUE THREAD

**Issue by alekulyn** [neovim/neovim#4937]
- `nvim --version`:  NVIM 0.1.5-dev
- Vim (version: ) behaves differently?  Not sure.
- Operating system/version:  Windows 10 64-bit

I have a large (28 mb) foreign-language json file that I'm trying to load via NERDTree.  However, whenever it finishes loading and I try to switch buffers, I get a `E475:  Invalid Argument: Channel doesn't exist` error.  I've grabbed the latest MSys64 build from @equalsraf appveyor, and forced the neovim modules in python2 and python3 to upgrade, but none of those solutions worked.  I've loaded a different, much-smaller foreign language JSON file with the same format, and it works just fine.

The function with the error differs.  Sometimes it's <SNR>103_on_event, sometimes <SNR>106_on_event, and sometimes <SNR>113_on_event.

![Nvim_error](https://cloud.githubusercontent.com/assets/3824241/16169230/0d5d526a-352f-11e6-8c59-59cc2e0fa3e5.png)

**Comment by justinmk** [comment]
Use `:scriptnames` to find the script corresponding to the number. E.g. for 103_on_event, find the script numbered 103. Then find the `s:on_event` function in that script.

**Comment by ZyX-I** [comment]
@justinmk Using `:set more | verbose function <SNR>103_on_event` is more efficient.

**Comment by alekulyn** [comment]
Turns out deoplete's handlers.vim was throwing an error at ```call rpcnotify(g:deoplete#_channel_id, 'deoplete_on_event', context)```.  I don't know how to fix it, but at least I know where it is.

**Comment by Shougo** [comment]
@alekulyn What is the `:CheckHealth` result?
neovim-python is the latest version?

**Comment by alekulyn** [comment]
@Shougo, it says that its not an editor command.

**Comment by Shougo** [comment]
Hm.  Your neovim Windows build is not the latest version.
And, I don't know if deoplete works in Windows environment.

**Comment by alekulyn** [comment]
@Shougo, deoplete was working just fine with other, smaller files.

**Comment by Shougo** [comment]
Hm.
You should create minimal init.vim.

**Comment by justinmk** [comment]
Please try again with the latest appveyor artifacts from https://github.com/neovim/neovim/wiki/Installing-Neovim#windows
