### ISSUE TITLE
Where do I place the manually downloaded dependency package?

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#4940]
Hi, I'm trying to build neovim from source, I know neovim will automatically download some dependency  packages for me. But I'm Chinese, you know, where network connection to foreign site  is  troublesome.

Currently I encounter this error. I manage to manually download the package. Where should I put it to in order to help the make procedure go on?

```
Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/Olivine-Labs/busted/v2.0.rc11-0/busted-2.0.rc11-0.rockspec
make[3]: *** [usr/bin/busted] Error 1
make[3]: Leaving directory xxx/.dep
```

**Comment by roxma** [comment]
I downloaded the package to my local file system, and change the url into file path in the cmakefile. problem solved. never mind.

**Comment by Abbyyan** [comment]
Thank you very much!

**Comment by Abbyyan** [comment]
> I downloaded the package to my local file system, and changed the url into file path in the cmakefile. problem solved. never mind.
Sorry to bother you . I got the same problem and want to ask how to set the url . Could you give an example? Thanks a lot !
