### ISSUE TITLE
[question] why neovim isn't distributed under the GPLv3 license?

### ISSUE THREAD

**Issue by ninrod** [neovim/neovim#4942]
Just want to know the decisions that led the team to pick up Apache instead of GPLv3.

**Comment by justinmk** [comment]
Why not?

**Comment by mhinz** [comment]
It's Apache 2.0 / Vim license, not MIT.

**Comment by jamessan** [comment]
See #878 and #370 for previous discussions.

**Comment by ninrod** [comment]
I think choosing GPL over other licenses could only be appreciated in light of the philosophical line layed down by stallman in this post: [cang vs free software](https://gcc.gnu.org/ml/gcc/2014-01/msg00247.html). Mainly: 

```txt
For GCC to be replaced by another technically superior compiler that
defended freedom equally well would cause me some personal regret, but
I would rejoice for the community's advance.  The existence of LLVM is
a terrible setback for our community precisely because it is not
copylefted and can be used as the basis for nonfree compilers -- so
that all contribution to LLVM directly helps proprietary software as
much as it helps us.
```

**Comment by jamessan** [comment]
There is a world of difference between the leverage licensing a compiler under the GPL provides vs. licensing an editor under the GPL. While I understand and empathize with the sentiment in that post, I don't think it's a very applicable argument in this case.

**Comment by ZyX-I** [comment]
This issue was already discussed as pointed by @jamessan and such discussions tend to generate a lot of flame. So please move to those issues (and first check arguments there), I am closing *and locking* this one.
