### ISSUE TITLE
Visual block replace operation over non-ASCII characters crashes Neovim

### ISSUE THREAD

**Issue by zoqaeski** [neovim/neovim#4943]
- `nvim --version`: 

```
NVIM v0.1.5-480-gd5ddebe
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-git/src/neovim-git/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-git/src/neovim-git/build/src/nvim/auto -I/build/neovim-git/src/neovim-git/build/include
Compiled by zoqaeski@computer
    
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
    
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
````    

- Vim (version: ) behaves differently? Yes
- Operating system/version: Arch Linux x86-64
- Terminal name/version: Terminix 1.0.0 (also occurs with neovim-qt-git r332.adc7a2d)
- `$TERM`: screen-256color

### Actual behaviour
Typing a malformed Compose key sequence causes neovim to crash.

### Expected behaviour
Neovim drops invalid key sequence and silently ignores it.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i
hahača
hahača
hahača
hahača
hahača
```
Visual block select the `č`s and try to replace it with an invalid sequence (Compose m m is one), that is `r Compose m m`. You get a segfault op_replace 'n >= 0' failed in ops.c:1689, and the terminal is completely borked, spewing out loads of escape sequences.

I tested it a number of times: 
* just doing a straight replace from normal mode 
* replace from visual mode 
* replace from visual block mode
* plain insert mode

The crash only occurs in visual block mode and only when you try to replace a non-ASCII character.

**EDIT** It looks like this is occurring regardless of what you replace the non-ASCII character with.
```
nvim -u NORC
5iač<CR><ESC>ggl<C-v>4jrm
```
CRASH but
```
nvim -u NORC
5iac<CR><ESC>ggl<C-v>4jrm
```
works.

**Comment by justinmk** [comment]
I would have thought this were fixed by https://github.com/neovim/neovim/pull/4574.

@zoqaeski Would you mind posting a backtrace? See https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux for instructions. `thread apply all bt full` result would be most helpful.

**Comment by zoqaeski** [comment]
Here you go: https://gist.github.com/ce3b62ed6a41723e1968b64d79b6792c

Three backtraces from gdb, `bt`, `thread apply all bt` and `thread apply all bt full`. I also have a coredump from that session that I could provide if it would help you. Anything else I could do/provide?

(As someone who is currently working on a multilingual LaTeX document, this bug is driving me nuts right now because I've had to recover source files that many times.)

**Comment by justinmk** [comment]
@zoqaeski Reverting c2a18216114bae75b6d6a2c7f1a68db04578abce might fix it. cc @cacplate

**Comment by zoqaeski** [comment]
How would I go about that to test it? I'm currently just following HEAD using the Archlinux `neovim-git` AUR package.

**Comment by cacplate** [comment]
Definitely my fault. I will look into it but not before sunday unfortunately. You may want to revert if it's too long.

**Comment by cacplate** [comment]
@zoqaeski can you confirm that the pull I made fix the bug?
```
 fpr = "!sh -c 'nr=\"$1\" ; shift ; git fetch upstream refs/pull/$nr/head:pr-$nr \"$@\"' -"
```
This is a snippet given to me by @ZyX-I to fetch pull requests. Just put the alias in your .gitconfig and `git fpr 4963`. You will have a new branch named `pr-4963` and you can test it there.

**Comment by zoqaeski** [comment]
Done and can confirm that your pull did indeed fix the bug (at least, from
testing using the example one-liner in the original report).

Also neat git alias :)

**Comment by cacplate** [comment]
Great. I believe there is still some work to be done on the PR but it will probably land in master soon enough.
