### ISSUE TITLE
terminal: incorrect width if 'number' column is enabled

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#4953]
- `nvim --version`: a2ecbc2cc093d6639b8d3e0262909191dfa9aba4
- Operating system/version: archlinux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

Commit a2ecbc2cc093d6639b8d3e0262909191dfa9aba4 breaks colored terminal.
Works fine on 7df9dd3
### Actual behaviour

Terminal currently looks like this.

![brokenterm](https://cloud.githubusercontent.com/assets/151506/16306928/b0ad6fe8-395f-11e6-9aae-464332495b41.png)
### Expected behaviour

Same thing on 7df9dd3.

![goodterm](https://cloud.githubusercontent.com/assets/151506/16306966/dab50be8-395f-11e6-9aa7-9adcc64c5541.png)

**Comment by justinmk** [comment]
Possibly this was working "by accident" before https://github.com/neovim/neovim/pull/4929. Seems like the resize is not taking the `'number'` column into account. If you `:set nonumber` does it work correctly?

**Comment by raichoo** [comment]
Good idea. Yeah that actually works.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/2651

**Comment by KillTheMule** [comment]
I encountered this today. A workaround is putting 

```viml
autocmd TermOpen * set nonumber
```

into your `init.nvim`

**Comment by zeertzjq** [comment]
Does this bug still exist?

**Comment by justinmk** [comment]
Looks ok to me. Test:

```
nvim --clean
set nu
te top
```
