### ISSUE TITLE
"echo v:servername" should not be empty on socket creation failure.

### ISSUE THREAD

**Issue by khalidchawtany** [neovim/neovim#4954]
- `nvim --version`: NVIM v0.1.5-487-ga2ecbc2
- Operating system/version: OS X 10.11.5
- Terminal name/version: iTerm2 - Build 3.0.20160620-nightly
- `$TERM`: xterm-256color
### Actual behaviour

When neovim fails to create a server socket `:echo v:servername` prints nothing. 
### Expected behaviour

Neovim should warn the user about it is failure to create the socket (Maybe the reason too. eg: Permission issue).

**Comment by justinmk** [comment]
Warning is printed in $NVIM_LOG_FILE. Example:

```
nvim --listen /
:edit $NVIM_LOG_FILE

WRN 2022-10-18T15:25:44.081 ?.20926    server_start:166: Failed to start server: illegal operation on a directory: /
```
