### ISSUE TITLE
1,100bd invalid range - unexpected error

### ISSUE THREAD

**Issue by alexbyk** [neovim/neovim#4958]
- `nvim --version`: NVIM 0.1.5-dev
- Vim (version: ) behaves differently: VIM - Vi IMproved 7.4 
- Operating system/version: UBUNTU 14.04
- Terminal name/version: gnome-terminall

### Actual behaviour
Invalid range error
### Expected behaviour
Delete buffers by range
### Steps to reproduce using `nvim -u NORC`

```
:1,100bd
```

**Comment by jamessan** [comment]
You don't have a buffers 1-100, so they can't be deleted.  Vim has the same behavior.

**Comment by alexbyk** [comment]
@jamessan no, if I have buffers 6, 10, 33 vim closes them.

**Comment by jamessan** [comment]
Then you're using an older version of vim. That's been changed to validate the range.
