### ISSUE TITLE
Statusline & command-line occupying same line, bizarre results

### ISSUE THREAD

**Issue by ivanbrennan** [neovim/neovim#4960]
- `nvim --version`: NVIM 0.1.4
  Build type: RelWithDebInfo
  Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/build/config -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/src -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/local/include -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/build/src/nvim/auto -I/tmp/neovim-20160515-76047-blsy2n/neovim-0.1.4/build/include
  Compiled by ivan@MachineCode.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.4/share/nvim"
- Vim (version: 7.4.1941) behaves differently? Yes. I cannot reproduce this bug in Vim.
- Operating system/version: OS X 10.11.5
- Terminal name/version: iTerm 2.1.4 and Terminal.app 2.6.1
- `$TERM`: xterm-256color
### Actual behaviour

The statusline and command-line end up occupying the same line, so that ex commands are typed on what appears to be the statusline. Then, if the statusline is hidden, scrolling down the buffer fails to display further buffer contents.
### Expected behaviour

Typed ex commands always appear below the statusline if present. Hiding the statusline does not interfere with display of buffer contents.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC /usr/share/dict/words

:set laststatus=0
:vsp
:copen
:set laststatus=1
:cclose
^W^H
:echo "I'm typing on the statusline"
^L
:echo "I'm typing on it again"
:set laststatus=0
^E^E^E... (scroll down left split and watch it fill up with blank lines)
^W^L
^E^E^E... (scroll down right split and confirm that those lines are not blank)
```

**Comment by justinmk** [comment]
cannot repro this on NVIM v0.4.0-381 7fcf2f926

**Comment by ivanbrennan** [comment]
I can no longer repro either :+1:
