### ISSUE TITLE
terminal: display issue with ambiguous-width chars (emoji, ...)

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#4976]
- `nvim --version`: NVIM v0.1.5-530-gae9cb1f
- Operating system/version: archlinux
- Terminal name/version: gnome-terminal 3.20.2
- `$TERM`: xterm-256color
### Actual behaviour

![brokenterm](https://cloud.githubusercontent.com/assets/151506/16388589/2013ee9c-3c9a-11e6-9f87-dcac26083c28.png)

It looks like this has been introduced with ae9cb1fe07d34289ebe4a929bfca8a07aab85b9f. I'm using the `__terlar_git_prompt` which is shipped with `fish`. The behavior manifests when the git working directory is dirty. The terminal is pretty much unusable in this state since the cursor itself is off-by-one.
### Expected behaviour

![goodterm](https://cloud.githubusercontent.com/assets/151506/16388612/33701f2e-3c9a-11e6-974c-f8c781e56ce7.png)

**Comment by raichoo** [comment]
I reverted 6e79a4d7f640369834d782fb71c62e8bf14b2dc3 and it turns out that this seems to be the culprit.

**Comment by justinmk** [comment]
That's surprising. @ZyX-I does this make any sense to you?

**Comment by jamessan** [comment]
```diff
-26A0..26BD;N     # So    [30] WARNING SIGN..SOCCER BALL
-26BE..26BF;A     # So     [2] BASEBALL..SQUARED KEY
+26A0;N           # So         WARNING SIGN
+26A1;W           # So         HIGH VOLTAGE SIGN
```

U+26A1 ( ⚡) was changed from N(arrow) to W(ide).  Neovim thinks the glyph should take up more space than the other relevant components do.  Rebuilding the rest against the updated Unicode data would likely fix it, but I'm not sure what the other relevant parts are.

**Comment by ZyX-I** [comment]
“Other relevant parts” should be at least libvterm. Also terminal emulator in which you run Neovim, but that thinking different should yield different kind of bug.

If you have screen/tmux/etc (something which needs to know widths, tmux needs this due to vertical splits and also because it needs to know when to wrap) then they also.

**Comment by raichoo** [comment]
`pacman` reports the following for `libvterm`

> community/libvterm 0.1.git1.c4317a6-2
>     Abstract library implementation of a VT220/xterm/ECMA-48 terminal emulator

I'm not running in `screen` or `tmux` just a plain old `gnome-terminal`.

**Comment by justinmk** [comment]
Can someone send a patch, or should we revert 6e79a4d ?

**Comment by skattyadz** [comment]
Is it possible to update the title of this issue? I'm experiencing a very similar problem with an emoji in my prompt and the title wouldn't have led me to this issue

Thanks all

**Comment by ZyX-I** [comment]
What libvterm is using to get character widths? If it is something different from Neovim (I guess it is), maybe it is a good idea to make libvterm have a settable global `int (*vterm_utfwidth)(int character) FUNC_ATTR_PURE;` which Neovim may set to its own function. This will not fix problems with terminal emulator Neovim is running in, but should fix #6822 and prevent same problems in the future.

Ref @leonerd

**Comment by leonerd** [comment]
libvterm has its own ideas, from mgk25's function:
http://bazaar.launchpad.net/~libvterm/libvterm/trunk/view/head:/src/unicode.c

It should be relatively simple to turn that function call into a library hook that can be replaced if required.

**Comment by leonerd** [comment]
A small update: I've now updated `libvterm` to understand the unicode "fullwidth" and "wide" sizes, so it should cope better with this.

```
719: Paul "LeoNerd" Evans 2018-09-03 Initial attempt at better handling of double-widt...
```
