### ISSUE TITLE
Closing terminal window from script causes insert mode to remain on

### ISSUE THREAD

**Issue by hkupty** [neovim/neovim#4977]
- `nvim --version`: NVIM v0.1.5-475-ga2ecbc2
- Vim (version: ) behaves differently? N/A
- Operating system/version: MacOX El Capitan (10.11.5)
- Terminal name/version:  iTerm2 3.0.2
- `$TERM`: xterm-256color

### Actual behaviour
When closing a term window from a script, if entering a term triggers input mode it will remain on input mode after closing term

### Expected behaviour
Should be at normal mode

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:au BufEnter * if &buftype == "terminal" | startinsert | endif
:vsp | term "Same for sp | term
<C-\><C-n><C-W>l "same for <C-W>j if horizontal split
:exec bufwinnr("$")." wincmd w" | q
```

**Comment by justinmk** [comment]
Vim behaves the same way if you close a split from insert-mode with e.g. `<c-o>:q<cr>`, so this is by design.

**Comment by hkupty** [comment]
:+1:
