### ISSUE TITLE
TabNewEntered is not triggered when using <CTRL-W> T

### ISSUE THREAD

**Issue by dmerejkowsky** [neovim/neovim#4979]
- `nvim --version`: NVIM v0.1.5-536-g9fb8adf
- Vim (version: ) behaves differently? N/A
- Operating system/version: Arch Linux
- Terminal name/version: XFCE terminal
- `$TERM`: xterm

### Actual behaviour

TabNewEntered is not triggered when using `<CTRL-W> T`

### Expected behaviour

TabNewEntered should be triggered

### Steps to reproduce

```vim
" in bug.vim
function! OnTabEntered()
  echom "new tab"
endfunction

autocmd TabNewEntered * :call OnTabEntered()
```

```
nvim -u bug.vim
:e foo.c
:split
<CTRL-W> T # no message
:tabnew  # message is printed
```

Note: I've written a failing test on [my branch](https://github.com/dmerejkowsky/neovim/compare/master...tabentered-bug)

No clue on how to fix, though :P

**Comment by fmoralesc** [comment]
I think this will fix it:
~~~ diff
diff --git a/src/nvim/window.c b/src/nvim/window.c
index 4eaba3a..1298248 100644
--- a/src/nvim/window.c
+++ b/src/nvim/window.c
@@ -251,11 +251,14 @@ newwindow:
       if (win_new_tabpage((int)Prenum, NULL) == OK
           && valid_tabpage(oldtab)) {
         newtab = curtab;
-        goto_tabpage_tp(oldtab, TRUE, TRUE);
-        if (curwin == wp)
-          win_close(curwin, FALSE);
-        if (valid_tabpage(newtab))
-          goto_tabpage_tp(newtab, TRUE, TRUE);
+        goto_tabpage_tp(oldtab, true, true);
+        if (curwin == wp) {
+          win_close(curwin, false);
+        }
+        if (valid_tabpage(newtab)) {
+          goto_tabpage_tp(newtab, true, true);
+          apply_autocmds(EVENT_TABNEWENTERED, NULL, NULL, false, curbuf);
+        }
       }
     }
     break;
~~~

**Comment by dmerejkowsky** [comment]
@fmoralesc  Applied your patch, test still fails. Will have a look later, this may be a good starting point :)

**Comment by fmoralesc** [comment]
Ah, I tried it manually and it worked, so there's that ;) At any rate, I think the choices are either to modify it there, or modify the `goto_tabpage_tp` function so it handles new tabs.

**Comment by dmerejkowsky** [comment]
Aha! It was a bug in the test, using `<CTRL-W>` instead of `<C-W>`

I've made a MR with your patch :)

**Comment by HarmtH** [comment]
This bug was actually a sort of duplicate of #4334, could you have a look at that one too again @fmoralesc @dmerejkowsky ?
