### ISSUE TITLE
Color escape sequences mess up terminal when running external programs

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#4990]
- `v0.1.5-447-ge247e3a`:
- Vim (version: 7.4 1-1558) behaves differently? Yes
- Operating system/version: OSX 10.10.5
- Terminal name/version: iTerm 3.0.4
- `xterm-256color`:

### Actual behaviour
Running an external command which uses color escape sequences (such as `:!ipython %`) gives this:

```
:!clear; echo This is Python devouring  test.py ...; ipython -i test.py

 [3J [H [2JThis is Python devouring test.py ...
Python 2.7.11 (default, Mar  3 2016, 09:39:14)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

  [0;34m In [  [1;34m 1  [0;34m ]:   [0m
Do you really want to exit ([y]/n)?
```

### Expected behaviour
In classic vim it works (and is actually colored)
```
This is Python devouring test.py ...
Python 2.7.11 (default, Mar  3 2016, 09:39:14)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:
```
It works with the built-in terminal emulator, but I don't wan't to change my custom commands do that they are not compatible with vim anymore.

### Steps to reproduce using `nvim -u NORC`
1. Open python file
2. run `:!ipython -i %`
3. admire fallout

**Comment by ZyX-I** [comment]
This question was already raised muliple times: e.g. #3474, there is even a [FAQ entry](https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes).
