### ISSUE TITLE
Installing plugins with vim-plug over ssh gives error E440 

### ISSUE THREAD

**Issue by edi9999** [neovim/neovim#4998]
- `nvim --version`:  

```
NVIM 0.1.5-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=fo
rmat-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -W
extra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-s
trong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE
-I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/build/config
-I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/src -I/build/
neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/.deps/usr/include -I/b
uild/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/.deps/usr/include
 -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/.deps/usr/in
clude -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/.deps/u
sr/include -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04.1/.d
eps/usr/include -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235+2620+20~ubuntu16.04
.1/.deps/usr/include -I/usr/include -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git201606301235
+2620+20~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-GvBvnu/neovim-0.1.4ubuntu1+git20160
6301235+2620+20~ubuntu16.04.1/build/include
Compiled by buildd@lgw01-22




Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences




   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) woks fine
- Operating system/version: Ubuntu 16.04
- Terminal name/version: ssh
- `$TERM`: screen-256color

See this issue : https://github.com/junegunn/vim-plug/issues/499
### Actual behaviour

Here's a minimal .vimrc : 

```
set nocompatible
syntax enable
call plug#begin()
Plug 'rking/ag.vim', {'on': 'Ag'}
Plug 'vim-scripts/ReplaceWithRegister'
call plug#end()
```

Then do 

```
ssh myip
# Inside the ssh shell : 
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
exit
# exit from ssh
ssh myip nvim +PlugInstall +qall
```

This crashes with an error : 

```
"[Plugins]" [New File]
Error detected while processing function <SNR>7_job_handler[23]..<SNR>7_reap[10]..<SNR>7_bar:
line    3:
E440: undo line missing
```
### Expected behaviour

It should be installing the plugins. It crashes with an internal error instead. It works fine with standard vim.

**Comment by jamessan** [comment]
Can you reproduce the behavior by running `sh -c 'nvim +PlugInstall +qall'`?

**Comment by edi9999** [comment]
I get the same error if I first interactively connect to thte machine with ssh, and then run `sh -c 'nvim +PlugInstall +qall'` in the same bash session.

Strangely, If I use the same minimal .vimrc locally, and run `sh -c 'nvim +PlugInstall +qall'`, I don't get the problem

**Comment by timfeirg** [comment]
`vim-plug` uses `git clone https://git::@github.com/%s.git` to clone the plugins, could @edi9999  try a `git clone` via https on the remote machine (on which `PlugInstall` would fail) to verify that this wasn't a network issue on that particular machine?

**Comment by edi9999** [comment]
I have no issue when I just do a git clone via https on the remote machine.

**Comment by edi9999** [comment]
The problem seems to happen because of the `+qall`.

nvim +PlugInstall runs some async jobs, and +qall tries to kill them, which is the cause of the bug

**Comment by edi9999** [comment]
Probably related to Probably related to https://github.com/junegunn/vim-plug/issues/104

**Comment by edi9999** [comment]
It has to do with python-nvim not being installed, if I install it with `pip install neovim`, it works fine

**Comment by justinmk** [comment]
https://github.com/junegunn/vim-plug/issues/104 was fixed, and nvim also offers `jobwait()`.
