### ISSUE TITLE
build automation / devops tasks

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#5000]
There are various build "automation" or "devops" tasks that we could use help with. 

If you want to help, then:

- Find a task in the bot-ci repo: https://github.com/neovim/bot-ci/issues
- Send a PR to the bot-ci repo: https://github.com/neovim/bot-ci/
- Do not ask if you can help. Just send a PR.

### Background

The Nvim build system lives in the Neovim repo ([.ci/](https://github.com/neovim/neovim/tree/master/.ci), [cmake](https://github.com/neovim/neovim/blob/master/CMakeLists.txt), [.travis.yml](https://github.com/neovim/neovim/blob/master/.travis.yml)). That is not the scope of this ticket. 

This ticket is an invitation to help with other _automation tasks_, which are maintained in the [bot-ci](https://github.com/neovim/bot-ci) repo.  The [README](https://github.com/neovim/bot-ci#marvim-bot-ci) explains how it works. It's **very simple**. It's literally just a few scripts invoked by Travis CI, which perform tasks such as:

- publishing the user manual
- publishing static analysis reports
- pushing to coverity
- pushing nightly builds
- various other reports
- _and anything else you can think of (ideas/help wanted!)..._

**Comment by narendravardi** [comment]
@justinmk, has anyone taken this?

Can I work on this?

**Comment by AbhishekSinghDhadwal** [comment]
@justinmk , can I contribute to fixing this issue ?

**Comment by justinmk** [comment]
What task from neovim/bot-ci#12 would you be able to work on?

**Comment by justinmk** [comment]
If you want to work on C, why not take a ticket from Neovim repo instead of bot-ci?

**Comment by AbhishekSinghDhadwal** [comment]
Oh,okay. Thanks !
