### ISSUE TITLE
netrw :Explore command closes current opened buffer

### ISSUE THREAD

**Issue by caneta** [neovim/neovim#5006]
- `nvim --version`: 0.1.5-dev
- Vim (version: 7.4.1907) behaves differently? yes
- Vim netrw version: 156
- Neovim netrw version: 155
- Operating system/version: Ubuntu Linux 12.04
- Terminal name/version: gnome-terminal 3.12.3
- `$TERM`: xterm

### Actual behaviour
If I open a file with Vim and then I want to open anther one with `:Explore`, the current opened buffer is kept and I get two buffers opened.

Trying to do the same with nvim, netrw closes the current opened buffer and replace it with new chosen file.

### Expected behaviour
I expect to keep the current opened buffer when running the `:Explore` command in Neovim too.

### Steps to reproduce using `nvim -u NORC`

```
vim index.html
:Explore
:ls
# Current file listed

nvim index.html
:Explore
:ls
# No buffer listed, the current one has been closed by netrw

```

**Comment by ZyX-I** [comment]
This looks like you simply do not have `set hidden` in your vimrc used by Neovim. In this case such behaviour is expected.

**Comment by caneta** [comment]
But I have `set hidden` on both: in Vim and Neovim test cases reported above, typing `:set hidden?` I get `hidden`.

**Comment by mhinz** [comment]
@caneta  We have to catch up on a few runtime patches. Check `:echo g:loaded_netrwPlugin`. In Vim it's v156, in Neovim v155.

**Comment by caneta** [comment]
Yes, I had reported netrw versions in my first post, so will wait for that.
Anyway, is that behaviuor reproducible with steps described? Someone who tried it?

**Comment by KillTheMule** [comment]
You could update netrw manually to see if that fixes it.

**Comment by caneta** [comment]
@KillTheMule so you encounter the same issue?
How to do what are you suggesting?

**Comment by KillTheMule** [comment]
No, I do not use netrw, and do not have a chance to test right now. You can download the latest version at http://www.drchip.org/astronaut/vim/index.html#NETRW (or from http://github.com/vim/vim, not sure what version they're at).

**Comment by caneta** [comment]
Ok thanks...and how can I do to install it, substituting the bundled one?

**Comment by KillTheMule** [comment]
That would be the easiest way, just overwrite that one file. Be sure to make a backup of the old one though, it might give you trouble.

**Comment by caneta** [comment]
Ok, I confirm that using netrw version 156 solves this issue for Neovim.

My test steps follows:
1. I've downloaded the latest Vim version at time of writing: [7.4.1989](https://github.com/vim/vim/releases), which contains netrw v156
2. I've made a backup of Neovim netrw-v155 files inside `/usr/share/nvim/runtime/autoload`:
```
netrwFileHandlers.vim
netrw_gitignore.vim
netrwSettings.vim
netrw.vim
```
3. I've copied the same files (netrw-v156) from `vim-7.4.1989/runtime/autoload` to `/usr/share/nvim/runtime/autoload`, updating the netrw plugin

4. Starting neovim and reproducing steps described in my first post I get that the issue is solved: Neovim behaves exactly as Vim

@mhinz one side note: the `:echo g:loaded_netrwPlugin` command give me always v155, even after my manual upgrade to v156. I saw the correct version looking at the top-right corner of netrw screen when I run `:Explore`

**Comment by justinmk** [comment]
This bug is in the runtime plugins (which we import from Vim). We can't afford to track every single problem with the runtime plugins in the Neovim issue tracker, because we aren't going to fork the runtime plugins in most cases (especially netrw, syntax plugins, etc.).
