### ISSUE TITLE
Add vterminal and sterminal commands

### ISSUE THREAD

**Issue by gilmrjc** [neovim/neovim#5009]
As mentioned in #3192 the command to open a terminal window should be implemented using :sterminal and :vterminal commands.

**Comment by mhinz** [comment]
`:vterminal` as a shortcut for something as short as `:vsplit | terminal` or `:vs +te`?

I'd vote against this, but wait for others to chime in. :)

**Comment by mhinz** [comment]
No one chimed in and it's easy to create your own commands for this, if `:vs | te` is still too long. Closing.

**Comment by jamessan** [comment]
The only command that would need to be added is `:sterminal`.  Then `:vert` could be used to modify the direction or `:tab` to push the split to a new tab.
