### ISSUE TITLE
Shift+tab in the embedded terminal doesn't work as expected

### ISSUE THREAD

**Issue by rjmill** [neovim/neovim#5011]
- `nvim --version`: v0.1.5-560-ga535868
- Vim (version: ) behaves differently? N/A
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode-256color v9.22
- `$TERM`: rxvt-unicode-256color
### Actual behaviour

Using shift+tab in nvim's embedded terminal plops out a weird character. (It looks different depending on what shell you're using and whether or not you're using tmux.)
### Expected behaviour

Using shift+tab does whatever it's configured to do in the terminal.
### Steps to reproduce using `nvim -u NORC`

Open an embedded terminal in nvim and hit shift+tab.

```
nvim -u NORC
:te
<S-TAB>
```

**Comment by rjmill** [comment]
shift+tab is being converted to a single key `K_S_TAB`, and the shift modifier is being removed before being converted to VTERM key codes.

Handling `K_S_TAB` in `terminal.c`'s `convert_key()` by manually setting `VTERM_MOD_SHIFT` and returning `VTERM_KEY_TAB` fixes this issue. If there are no objections, I can go ahead and submit a pull request after I make sure this doesn't break anything else.

**Comment by justinmk** [comment]
No objections. Thanks for digging into it!

**Comment by justinmk** [comment]
Though the next question will be what to do with `K_S_END`, `K_S_F1`, `K_S_F2`....

**Comment by justinmk** [comment]
I think we should instead investigate whether `mod_mask & MOD_MASK_SHIFT` should be set earlier in the input process (`keymap.c`, most likely). And then the question is whether the `K_S_*` variants are needed at all. For example, here we are checking both cases:

https://github.com/neovim/neovim/blob/a5358688bc91b2d72bf4eddea7938003d1fcde93/src/nvim/edit.c#L989-L1001                                  

but I have a feeling the `K_S_` stuff is leftover legacy...

**Comment by rjmill** [comment]
Yeah, the shift stuff looks pretty wonky. I was looking into the function keys too, and I think I got F5-F12 working, but F1-F4 are tricky because of how VT220 expects the key codes. It might be something that requires a change in VT220 itself.

I'm not 100% sure, but I think `mod_mask & MOD_MASK_SHIFT` are set earlier, but are converted to their `K_S_*` equivalent before terminal-ifying them. I'll play around with this a bit and report back with my findings.

**Comment by justinmk** [comment]
> 'm not 100% sure, but I think mod_mask & MOD_MASK_SHIFT are set earlier, but are converted to their `K_S_*` equivalent before terminal-ifying them.

In that case it would be good enough to un-convert it, if possible, right when it gets to the terminal logic.

We can save the mass-removal of `K_S_*` (if it's even appropriate) for later.

**Comment by rjmill** [comment]
>We can save the mass-removal of K_S_* (if it's even appropriate) for later.

For now, I can just drop the `K_S_*` versions of the keys into switch statement before their unshifted counterparts and let it fall through after applying the shift modifier. That switch statement is going to be huge and messy after I add the function keys, their shifted versions, and the other shifted special keys that aren't working right now.

A mass-removal of `K_S_*` probably isn't feasible though. I think the special keys (including the shifted versions) are being converted to `K_*` so vim can treat each of them as a single character.

I think a cleaner solution might be to split off the terminal keymapping logic before it "vim-ifies" the keycodes. As things are right now, nvim is converting the terminal key codes from terminal codes to vim characters and then back to terminal codes. The way the code is currently set up, I don't think it would be too terribly complicated to make this refactor, and having the terminal keymapping logic live in the same area as the rest of the keymapping logic seems fairly sensible to me.

I can go either way on this, so I'm curious to hear what others think about it.

**Comment by justinmk** [comment]
> That switch statement is going to be huge and messy after I add the function keys, their shifted versions, and the other shifted special keys that aren't working right now.

That's fine.  A single isolated messy switch is low-risk. This isn't a function that's going to see lots of changes, special cases, or inline logic.

**Comment by justinmk** [comment]
fixed by https://github.com/neovim/neovim/pull/5014

**Comment by sassanh** [comment]
Great, now we can remove the hacks and shift-tab can work both in neovim and in other terminal apps. Thanks.
