### ISSUE TITLE
Incorrect type highliting for C++ cast operators when using vim-cpp-enhanced-highlight

### ISSUE THREAD

**Issue by sittim** [neovim/neovim#5016]
- `nvim --version`: `Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/build/config -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/src -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/.deps/usr/include -I/usr/include -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/build/src/nvim/auto -I/build/neovim-Zj1EMO/neovim-0.1.4ubuntu1+git201607061313+2636+20~ubuntu15.04.1/build/include
Compiled by buildd@lgw01-05`

- Vim (version: 7.4) behaves differently?  Yes
- Operating system/version: Ubuntu 15.04
- Terminal name/version: `GNOME Terminal 3.14.2`
- `$TERM`: xterm-256color

### Actual behaviour
- C++
- **vim-cpp-enhanced-highlight** https://github.com/octol/vim-cpp-enhanced-highlight
- **File type** cpp
- Code Snipped:

```cpp
#include <stdint.h>
uint8_t a;
uint32_t b = static_cast<uint8_t>(a)
char k;
char j = reinterpret_cast<char>(k);
```

`reinterpret_cast<type>(var)` does not highlight correctly, see label 1 and 2

![selection_022](https://cloud.githubusercontent.com/assets/8825037/16654549/502d556e-4424-11e6-9385-cba18f03c438.png)

### Expected behaviour

Same conditions in VIM, with **vim-cpp-enhanced-highlight**

![selection_023](https://cloud.githubusercontent.com/assets/8825037/16654695/e940b822-4424-11e6-9938-fa85b9dc4bdd.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by mhinz** [comment]
This is most likely a runtime "issue". We usually don't alter those, but port them from Vim from time to time.

**Comment by sittim** [comment]
Updating runtime from official VIM repo, does not resolve the issue

Copied the the c.vim and cpp.vim from the VIM official repo to nvim/runtime/syntax directory, restarted terminal.

**Comment by justinmk** [comment]
@sittim Can you try a more recent version of vim (say 7.4.1800+)?

**Comment by jamessan** [comment]
> This is most likely a runtime "issue" (runtime/syntax/{c,cpp}.vim in this case).

vim-cpp-enhanced-highlight is what's providing the augmented syntax highlighting, so the upstream syntax highlighting isn't particularly relevant.

@sittim Are you sure you're using the same version of vim-cpp-enhanced-highlight in both Vim and NeoVim?  Do you have any of the addons configuration variables let in your Vim config that aren't also set in the NeoVim config?

With your cursor in the word that's being highlighted differently, can you post the results of the below command from both Vim and NeoVim?

```vim
:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
```

**Comment by mhinz** [comment]
@jamessan But it could reuse groups or clusters from the shipped runtime. It's only "enhancing" after all. :)

**Comment by sittim** [comment]
## 1. Per @justinmk 
 Built VIM from source:
```bash
~/ws-ccs/hw_1_5$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  7 2016 10:22:23)
Included patches: 1-1993
Compiled by sporty@sporty-XPS13-9333
```
Same result:
![selection_024](https://cloud.githubusercontent.com/assets/8825037/16656881/5d21fad6-442e-11e6-9c55-266dbb6f77db.png)

## 2. Per @jamessan 
Copied ~/.vimrc to ~/.config/nvim/init.vim
**Issue went away**, but what can be causing it?  So now I am into process of elimination.

**Comment by sittim** [comment]
OK

I can be such an idiot, this causes the issue:
`let g:cpp_experimental_template_highlight = 1`

It helps with templates, breaks the cast.
