### ISSUE TITLE
Syntax coloring in foldtext and Folds on specific columns

### ISSUE THREAD

**Issue by romgrk** [neovim/neovim#5034]
Duplicate of https://github.com/neovim/neovim/issues/2197, but I also wanted to check if a PR on this would be get merged. 
Though I haven't looked at the fold code, is this reasonnably implementable?

The title also mention folds on specific columns; this is in expectation of an hypothetic (G)UI, that could display more funky stuff. I've been toying with UI implementation and the biggest drawback is the lack of exposure of what nvim knows about stuff displayed on screen.

**Comment by justinmk** [comment]
> Duplicate of #2197, but I also wanted to check if a PR on this would be get merged. 

Sure, anything with decent test coverage will get merged unless it totally doesn't fit with typical vim or neovim "UX". 

(p.s.: You can just ask in that issue, next time.)

> Though I haven't looked at the fold code, is this reasonnably implementable?

No idea.
