### ISSUE TITLE
Vim-patch: Convert plugins to packages

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#5040]
This issue is here to point out an easy entry-level task. After jamessan's [monumental effort](https://github.com/neovim/neovim/pull/4648) in porting the packages functionality of vim to neovim, there are some patches from vim that convert existing plugins to the new format. If you want to get your feet wet contributing to neovim, that would be an easy starting task.

Here's the list (I might have missed something, let me know if so):

- https://github.com/vim/vim/releases/tag/v7.4.1673
- https://github.com/vim/vim/releases/tag/v7.4.1675
- https://github.com/vim/vim/releases/tag/v7.4.1676

Check [here](https://neovim.io/doc/reports/vimpatch/) to see if any of these have already been ported.

If you're interested, the [wiki](https://github.com/neovim/neovim/wiki#developers) contains some helpfull comments. Don't hesitate to join the team on [gitter](https://gitter.im/neovim/neovim) to get help, offer support or simply chat.

Would someone please tag this as `entry-level`? Should we maybe cleanup the `entry-level`-issues, since most of them aren't really `entry-level` anymore? From my own experience I find it pretty confusing for newbies.

**Comment by mhinz** [comment]
I really wonder how many people are actually using these packages. Not that many, I assume. If at all, probably the `dvorak` or maybe the `swapmouse` package.

https://github.com/vim/vim/releases/tag/v7.4.1674 doesn't apply to us (at the moment), since we don't have `remote_expr()` and friends.

**Comment by KillTheMule** [comment]
Jamessan mentioned that it's very usefull for the people packaging for the distributions. And since the feature was ported, it at least makes sense to stay with upstream I'd say.

My main motivation is to expose easy entry-level tasks though, and these pretty much fit the bill. It's not like they hurt :)

I've removed 1674 from the list, thanks!

**Comment by jamessan** [comment]
> I really wonder how many people are actually using these packages.

Are you questioning whether they should be removed instead of made more accessible?  The suggested patches just make it easier to use the scripts.

**Comment by mhinz** [comment]
> Are you questioning whether they should be removed instead of made more accessible?

The former, but I didn't want to suggest to remove them, because compatibility and all that.

**Comment by justinmk** [comment]
I thought we did remove most of those plugins, already. Which plugins specifically are we talking about?

P.s.: we don't want logipat.

**Comment by KillTheMule** [comment]
Ah yeah, 1672 (dvorak) has been removed. Should we mark [1674](https://github.com/vim/vim/releases/tag/v7.4.1674) and [1672](https://github.com/vim/vim/releases/tag/v7.4.1672) as NA?

**Comment by justinmk** [comment]
Yes.

BTW, the dvorak plugin was removed because `runtime/keymap/dvorak.vim` serves the same purpose.

**Comment by KillTheMule** [comment]
Ports done by @munyari, thanks!
