### ISSUE TITLE
String_eq from map.c is incorrect

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#5046]
```
static inline bool String_eq(String a, String b)
{
  return strncmp(a.data, b.data, MIN(a.size, b.size)) == 0;
}
```

will return true if

1. a is `\0a` and b is `\0b`.
2. a is `a` and b is `ab`.

if this is intended this should be documented, but otherwise it 1. must use `memcmp`, not `strncmp` and 2. return false if `a.size != b.size`, not use MIN.

**Comment by dmerejkowsky** [comment]
Note that the function does not seem to be used anywhere :)
