### ISSUE TITLE
How can I have cmd + c work in neovim in iTerm on macOS?

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#5052]
- `nvim --version`: 0.1.4
- Operating system/version: macOS ver.  10.11.5
- Terminal name/version: iTerm v. 3.0.4

### Actual behaviour

When I select text and press cmd + c, it does not copy text to the system clipboard. Can I make this work? I know I can use 'y' to copy text and that works, however I have certain functions like 'search selected text in google' that require me to use cmd + c to copy the text. Is it possible to make this work? 

### Expected behaviour

I select text, press cmd + c and the text gets copied to my clipboard.

Thank you for any help on this.

**Comment by mhinz** [comment]
Opposed to Vim, Neovim uses `mouse=a` by default. That means Vim uses the mouse for its own visual selections, so that iTerm won't even see them.

Either put `set mouse=` in your init.vim, or hold `alt` while making the selection. See `:h 'mouse'` for more information.

**Comment by nikitavoloboev** [comment]
I have tried putting 'set mouse=' in my init.vim but this does not work. It still does not save my selection to the clipboard.

**Comment by mhinz** [comment]
What's the output of `:verb set mouse?`?

**Comment by nikitavoloboev** [comment]
Here is what I get : 

![2016-07-12 at 12 04](https://cloud.githubusercontent.com/assets/6391776/16763382/de10a3ba-4828-11e6-942e-e5ff05d5ced9.png)

After pressing enter, it just goes away.

**Comment by mhinz** [comment]
Hmm.. When you say "select text", you mean using the mouse, right?

**Comment by nikitavoloboev** [comment]
Just normal text selection with V. But selecting text with the mouse doesn't work as well. It selects the text, but pressing cmd + c on it, does not copy it to my clipboard.

**Comment by mhinz** [comment]
Well, it doesn't work like that. :) It's not possible in Vim either.

If you select something in Vim (that is with `v` and friends or with the mouse while `mouse=a`), iTerm never sees that selection, so `cmd+c` won't work either.

If you really need to use `cmd+c`, you have to use the mouse for selecting and set `mouse=`. I suggest fixing your script to use the output of `pbpaste` instead.

**Comment by nikitavoloboev** [comment]
I see. Well I just need it to have my dash selection and google selection working. That is I select text, press a hotkey and it will search documentation or google. I also want to add snippets to typinator from selection and all that require the use of cmd + c.

I am not sure what I should modify to have it working. I really want this to work and I want to have it work without me having to select text with the mouse. So is there any way that iTerm to see and trigger cmd + c properly while I select text with v and friends?

Thank you for your help.

**Comment by justinmk** [comment]
Use clipboard=unnamed

**Comment by nikitavoloboev** [comment]
I have the line 'set clipboard=unnamed' in my init.vim already. This only allows me to have the text I copy with 'y' to be brought to system clipboard but I still cannot use cmd + c.  Is that the command you meant?

**Comment by justinmk** [comment]
Ok, yes. You could setup iterm to send a unique sequence when cmd C is pressed. Then you could map that sequence in n/vim.

**Comment by nikitavoloboev** [comment]
hey justinmk,

I am very new to nevim and vim and I am really not sure how I can do such a thing. How would I setup my iTerm in this way?

Thank you a lot for your help.

**Comment by chemzqm** [comment]
@nikitavoloboev 
<img width="847" alt="screen shot 2016-07-12 at 11 19 15 pm" src="https://cloud.githubusercontent.com/assets/251450/16772513/28044658-4887-11e6-8c4e-740d52bf4583.png">
and you can remap <ctrl>+c to save content to clipboard like:

  vnoremap <M-c> "+y

**Comment by nikitavoloboev** [comment]
@chemzqm 

This seems to nearly work. However there are two issues : 

1. Now for some reason, when I try to open anything with nevim, it says that 'No mapping is found' like so : 

![2016-07-12 at 19 20](https://cloud.githubusercontent.com/assets/6391776/16776454/b6472682-4865-11e6-9537-a0b921717a01.png)

2. Now cmd + c seems to cut the text rather than copy.

What should I do to correct these issues. Also I am not really sure why this works. Now when I press command + c, it sends and escape sequence?

Thank you for your help.

**Comment by justinmk** [comment]
@nikitavoloboev Need you to share your precise configuration. Preferably by reproducing it using `nvim -u NORC` (not your entire init.vim).

**Comment by nikitavoloboev** [comment]
@justinmk 
the command ```nvim -u NORC``` just opens a new nvim window, is that what it should do?

I am not sure how I can share my precise configuration with you.

**Comment by justinmk** [comment]
My comment was a bit confusing. anyways, I guess just post your init.vim somewhere

**Comment by chemzqm** [comment]
@nikitavoloboev I've corrected the mapping, try typing `:vnoremap <M-c> "+y` and use `option` + `c` to check if selected content copied to your system clipboard.

**Comment by nikitavoloboev** [comment]
@justinmk 

[Here](https://github.com/nikitavoloboev/dotfiles/blob/master/vim/nvim/nvimrc) is my init.vim.

@chemzqm 

I am not really sure how does the mapping work as +y is commented out for me due to " being a comment : 

![2016-07-12 at 23 09](https://cloud.githubusercontent.com/assets/6391776/16783795/f007dd88-4885-11e6-9c2e-20b3bb97e399.png)

I tried putting it and trying out option + c and it does not work. Also I want to have cmd + c working for that if I can and not option + c.

**Comment by ahuigo** [comment]
We could make iterm2 send `Esc+<multi-chars>`
```
" config iTerm2 keys: Esc+Ac, Esc+As, Esc+Aa
vnoremap <M-A>c "+y
nnoremap <M-A>s :up<CR>
inoremap <M-A>s <C-o>:up<CR>
nnoremap <M-A>a ggVG

```

**Comment by amit777** [comment]
in case anyone else comes here via google search, I ended up using MacVim (brew install macvim), and it works perfectly with CMD+C etc.  I haven't used it extensively yet, but it seems to work great.

**Comment by ekoputrasentosa** [comment]
well, as mention above to recognize CMD key in mac it maps to <D ->, but only works in macVim
but why limiting on using cmd key, i just remapping the ' "+y ' to literally Control key ( <C-c> ), and it works fine for me if i need to copy something from vim to my system clipboard

**Comment by HiWilliam** [comment]
This [link](https://www.reddit.com/r/neovim/comments/136j9fy/comment/jiqg26f/?utm_source=share&utm_medium=web2x&context=3) has the solution for the problem and it worked for me

**Comment by justinmk** [comment]
> This [link](https://www.reddit.com/r/neovim/comments/136j9fy/comment/jiqg26f/?utm_source=share&utm_medium=web2x&context=3) has the solution for the problem and it worked for me

That link does not say anything about cmd+c ?

**Comment by HiWilliam** [comment]
> > This [link](https://www.reddit.com/r/neovim/comments/136j9fy/comment/jiqg26f/?utm_source=share&utm_medium=web2x&context=3) has the solution for the problem and it worked for me
> 
> That link does not say anything about cmd+c ?

i had tried the setting and cmd+c can copy the selected text normaly

**Comment by RepinsPL** [comment]
Solution that works for me is:
1) In "iTerm Settings -> Profiles" create duplicate of your default profile and call it "neovim"
2) In "neovim profile -> Keys -> Key Mappings" add Shortcut for "Cmd+c" to send text "+y
![Image](https://github.com/user-attachments/assets/aefc0301-6023-4e62-9747-dbe6acd3ff8c)

3) In "neovim profile -> Advanced -> Automatic profile switching" add "&nvim" to switch iterm from default profile to neovim profile when nvim is run
![Image](https://github.com/user-attachments/assets/1e1fe1be-00ac-4976-bdb9-6342560e20df)

Due to creating separate profile for neovim which is switched on only when nvim is run, in normal terminal Cmd+c will still work (instead of pasting strange letters). Iterm will automatically switch back to default profile after closing nvim.

**Comment by justinmk** [comment]
@RepinsPL that is completely unnecessary with modern terminals such as iTerm2, which supports CSI u: https://iterm2.com/documentation-csiu.html

Any terminal that supports CSI u or kitty keyboard protocol will send "super" and Nvim will recognize it as a `<D-x>` keycode. So you can map:

    xnoremap <D-c> "+y
