### ISSUE TITLE
Provide a way to set title of existing quickfix/location list

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5056]
For fugitive I've looked into setting the quickfix/loclist title for `:Log`, which uses `:grep/:lgrep` internally.

A hack would be to call `setqflist(getqflist(), 'r', new_title)` / `setloclist(0, getloclist(0), 'r', new_title`, but that is ineffective and triggers selection of the list's first item, and the help for `setqflist` mentions the following (which sounds like it might even get changed in the process):

> Note that the list is not exactly the same as what |getqflist()| returns.

I think new methods `setqflisttitle(title)` and `setloclisttitle(number, title)` would be helpful in this regard, and would make it easier to detect if setting the title is supported (since Vim still does not has included the patch for it).

I would suggest bringing this up for Vim also / first, in case I am not missing something.

Related PR: https://github.com/neovim/neovim/pull/4337 (adding title for `setqflist`/`setloclist`).

**Comment by ZyX-I** [comment]
I think that there should not be any new methods, but API functions `void vim_set_qflist_title(String)` and `void win_set_loclist_title(Window, String)`. With API functions exported to Vim new methods will be automatically added, also somebody (AFAIR, @justinmk in #5031) mentioned that default choice for new features should be API-only and I agree here. If Vim will create such function, then we will add it here for compatibility.

BTW, should not your example be `setqflist([], 'a', new_title)`? I remember discussion in vim-dev regarding `'a'` that should not reset which list item is selected. If this works or can be made working no changes are needed at all.

**Comment by blueyed** [comment]
I have tried "a", but it looked like the title would only be used for new lists?

I agree that the API approach makes sense.

**Comment by blueyed** [comment]
I think in this regard Neovim should use the same API as Vim (i.e. Vim's patch(es)), where `setqftitle` got a dict for the 3rd argument.

**Comment by justinmk** [comment]
@blueyed This is already covered by a Vim patch, so we can close this?

**Comment by blueyed** [comment]
@justinmk 
Well, we used some patch (I was pushing) in Neovim, so the API for `setqflist` is now different:
`setqflist({list} [, {action}[, {title}]])` in Neovim vs. `setqflist({list} [, {action}[, {what}]])` in Vim.

The main patch seems to be v7.4.2200 - https://github.com/vim/vim/commit/d823fa9.

But yeah, let's close this particular issue then - assuming that with the patch the API in Neovim gets changed to Vim's.

**Comment by blueyed** [comment]
https://github.com/neovim/neovim/pull/5352 is about the patch.

**Comment by lervag** [comment]
@blueyed It seems that the neovim version is not properly documented. The docs in neovim are the same as for Vim, but the implementation is as you specify.

If you prefer, I could open a new issue for this.

As a plugin dev, I would much prefer that Vim and neovim behaved the same here.

**Comment by jamessan** [comment]
@lervag Neovim was recently updated to use the same API as Vim, although the old Neovim-specific API works (but is not documented) so as not to break backwards compatibility.

**Comment by lervag** [comment]
Great, happy to hear it! :)
