### ISSUE TITLE
vimFuncName keywords not defined in runtime/syntax/vim.vim

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5060]
This is used by scriptease (https://github.com/tpope/vim-scriptease/blob/b9720e64c676f0c747a3829e1f0b1b86daedefd8/plugin/scriptease.vim#L720) to append `()` for `K` with functions.

It was lost in https://github.com/neovim/neovim/commit/e1cc0fe.

It seems like the `genvimvim.lua` script needs to be extended, and should probably also restore/keep other groups that are defined in Vim?!

/cc @ZyX-I

**Comment by blueyed** [comment]
Oh, it gets generated and installed correctly (`/usr/share/nvim/runtime/syntax/vim/generated.vim`), but does not seem to be included then?!
Not sure if it should get inlined at https://github.com/neovim/neovim/blob/c40dff6453a3f4655981ba7a49dbcace0240f5fc/runtime/syntax/vim.vim#L6 or included from there, e.g. via `:runtime`?!

**Comment by ZyX-I** [comment]
When loading syntax `s:SynSet` from `synload.vim` sources *both* `syntax/vim.vim` and `syntax/vim/*.vim`, so current setup is correct.

**Comment by mhinz** [comment]
@blueyed Is your `$VIMRUNTIME` really pointing to `/usr/share/nvim/runtime` or maybe to `$neovimrepo/runtime` instead? The latter wouldn't work, because the generated stuff lands in `$neovimrepo/build/runtime` instead.

**Comment by blueyed** [comment]
Ah, ok - `generated.vim` is being loaded (3 times! - caused by my config/plugins probably though), but missing the functions.

> syn keyword vimFuncName contained 

#5062 fixes it.

Seems to be broken since a while already: f350655dd.
