### ISSUE TITLE
Can nvim expand tab only after text.

### ISSUE THREAD

**Issue by gngshn** [neovim/neovim#5063]
I mean that at the beginning of a line. tab is tab. after that, if a type a text, then tab goes to space.
`$` means begin of line 
```
$<tab>sdlfjsdfj<space>*8fsdlf
$sldkfjlsdjf<space>*8sdlkfjsdfkj
```

**Comment by gngshn** [comment]
If there isn't a feature of nvim, may NeoVim can add this feature?

**Comment by KillTheMule** [comment]
Shouldn't that be doable with an `inoremap` and a bit of vimscript? I'm really not a viml master myself, but I'd guess this isn't too hard to do.

**Comment by chemzqm** [comment]
@gngshn `:h smarttab` that's a feature of vim.

**Comment by KillTheMule** [comment]
I don't think `smarttab` covers _this_ use case, since he wants a tab at the beginning. Maybe I'm missing some sort of combination with `tabstop`, `softtabstop` and such, so maybe you could elaborate?

**Comment by jamessan** [comment]
@KillTheMule This part of the help for `'smarttab'` seems to be the relevant tidbit.

> When 'expandtab' is not set, the number of spaces is minimized by using <Tab>s.

**Comment by KillTheMule** [comment]
Arggs I misread `blanks` as `spaces`. Still I could not get this to work, but it's not my usecase, so no need to bother... that's probably a question for reddit or stackoverflow anyways :)

**Comment by jamessan** [comment]
Ah, no, `'smarttab'` doesn't do it.  That only changes the number of columns that `<Tab>` inserts depending on where the cursor is in the line, not which characters are used to insert the columns.

Looks like an imap would be needed.

**Comment by justinmk** [comment]
Usage questions should be asked at vi.stackexchange.com
