### ISSUE TITLE
Neovim looks ugly with terminal width lesser than 83

### ISSUE THREAD

**Issue by pickfire** [neovim/neovim#5064]
Hi, I just found out that neovim looks somewhat ugly when being used with a 80 characters width terminal (which most terminals use) and it needs 83 character to look nice instead.
- `nvim --version`: 0.1.4
- Vim (version: ) behaves differently? 7.3 and above
- Operating system/version: Linux peak 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux
- Terminal name/version: st git
- `$TERM`: st-256color
### Actual behaviour

This is what neovim looks like during startup

![2016-07-08-122521_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677344/43d37ed6-4507-11e6-9249-65cc4728d6d2.png)

The new `Tutor` for neovim which have good feature

![2016-07-08-122550_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677345/43d777b6-4507-11e6-90d1-55410e714c22.png)
### Expected behaviour

Compared to vim which is gracefully centered

![2016-07-08-122627_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677346/43d9c278-4507-11e6-8ea3-286b01dc12ef.png)

But the old help page definitely looks a lot neater

![2016-07-08-122616_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/16677343/43d2e3a4-4507-11e6-8e34-be19f8cb26e4.png)
### Steps to reproduce using `nvim -u NORC` (not affected)

This issue is replicated from https://github.com/fmoralesc/vim-tutor-mode/issues/30

I think those `|` folds aren't necessary for beginners so disabling them would be good.

**Comment by justinmk** [comment]
@pickfire I don't see a problem with the _intro_ page. Is this report specifically about `:Tutor`? And is there any problem with our help page?

**Comment by fmoralesc** [comment]
@justinmk It is. I am also considering removing the foldcolumn, that might give some more leeway.

**Comment by pickfire** [comment]
@justinmk Yeah, the help page is still the same which vim uses. But I think it's better to move the intro one line above so that it looks cleaner with one space above and one space below.

**Comment by justinmk** [comment]
Oh, I get it. The intro was trimmed already on master (upcoming 0.1.5).

**Comment by pickfire** [comment]
@justinmk Thanks a lot for the information.

**Comment by fmoralesc** [comment]
I'm reopening this because there's ongoing work pending.

**Comment by justinmk** [comment]
There are several `:Tutor` issues open, let's assume this one will be covered when that plugin gets updated.

**Comment by pickfire** [comment]
@justinmk Lately neovim still looks weird on `:Tutor` on **v0.2.2** so I think some commits broke it?

**Comment by fmoralesc** [comment]
@pickfire This is what it looks in HEAD. v0.2.2 is too old.

![screenshot from 2018-01-01 11-18-20](https://user-images.githubusercontent.com/221465/34466993-9719d232-eee5-11e7-9365-66622e24c77d.png)

**Comment by fmoralesc** [comment]
I'm dealing with this in #7801.
