### ISSUE TITLE
implement partials (needed for timer callback) vim-patch 7.4.1559,...

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#5065]
- `nvim --version`:NVIM v0.1.5-802-g5573e1a
- Vim (version: ) behaves differently?  Yes, Vim is no error.
- Operating system/version: Manjaro Linux
- Terminal name/version: st 0.6
- `$TERM`: st-256color
### Actual behaviour

```
Error detected while processing function 216:
line    1:
E121: Undefined variable: self
Error detected while processing function 216:
line    1:
E15: Invalid expression: self.count
Error detected while processing function 216:
line    2:
```
### Expected behaviour

No error.
### Steps to reproduce using `nvim -u NONE`

``` vim
" test.vim
let counter = {'count': 0}
function! counter.call(timer)
  echomsg self.count
  let self.count += 1
endfunction
let timer = timer_start(1000, counter.call, {'repeat': 0})
```

```
nvim -u NONE test.vim
:so test.vim
```

@bfredl Can you check it?

**Comment by bfredl** [comment]
This is the vim partial feature that needs to be ported.

**Comment by bfredl** [comment]
patches 7.4.1559, 1577, 1581, 1585, 1586, 1589, 1606, 1607, 1608, 1639, 1644, 1645, 1646, 1656, 1687, 1688, 1715, 1717, 1719, 1731, 1836, 1839, 1853, 1860, 1875,

**Comment by Shougo** [comment]
This is my patches list.

1559 partial
1563 test_partial
1564 function() fix
1577 dict func (Note: broken)
1580,1581,1582 1577 fix
1585,1586,1589 partial fix
1590 shadow variable
1605 partial test
1606, 1607 parital fix
1608 string() for partial
1638, 1639 partial garbage collect
1644 string() fix
1645 dictionary fix
1720 partial test
1836 partial fix
1839 get() partial
1842 get() funcref
