### ISSUE TITLE
Please recognize `reportbug-*` as ft=mail

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#5069]
Debian's vim configuration includes the following line, which I think
would make sense to incorporate upstream:

```vim
autocmd BufRead reportbug-* set ft=mail
```

**Comment by justinmk** [comment]
We track Vim's runtime files for things like syntax and ftplugins, and would prefer not to maintain of fork of them in most cases. Can you report it to  https://github.com/vim/vim ?

**Comment by joshtriplett** [comment]
Done: https://github.com/vim/vim/issues/928

**Comment by jamessan** [comment]
Thanks. I had been thinking about doing that, but hadn't gotten around to it yet.
