### ISSUE TITLE
Opening files is very very slow

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#5072]
- `nvim --version`: 0.1.5-dev
- Operating system/version: Ubuntu 14.04
- Terminal name/version: Gnome Terminal

### Actual behaviour
Opening a new file stalls for about 3 full seconds before displaying the file. Actually... digging around a bit. This only seems to happen with .styl or .jade files. Maybe it's the way it's trying to grab syntax highlighting information. 

Any ideas?

**Comment by mhinz** [comment]
Can you paste an example file on Github? Makes it easier to reproduce.

Until then, here a few general tips: https://github.com/mhinz/vim-galore#debugging

**Comment by wamoyo** [comment]
Doesn't reproduce with `nvim -u NORC` which means....? It's got something to do with a plugin I'm using?

**Comment by KillTheMule** [comment]
Not neccessarily, but it means something in your `init.vim` is causing it. do a binary search: Delete / comment out one half, repeat with other if no change, then split the problematic half and repeat. That way you can find out what causes this (maybe first just try for the plugins, they're of course kinda suspicious). Report back with your findings :)

**Comment by wamoyo** [comment]
Okay so I've got a mess of problems now. Vundle seems to be the first in line. Here's my .vimrc: https://github.com/wamoyo/vimrc/blob/master/.vimrc

This might be a matter of the paths, but updating them to the .config/nvim/bundle didn't seem to help. I just got a whole set of new errors. I feel like I should be taking a 'neovim' approach to installing plugins. I'd like to be forward thinking in this aspect. 

Is there a neovim package manager built in? Something I can read about in the docs.

**Comment by mhinz** [comment]
There's no package manager built in, and Vundle itself shouldn't be the problem.

At a quick glance I saw nothing terrible in your init.vim as well, so I'd try uncommenting your plugins first.

**Comment by wamoyo** [comment]
Went through a long debugging process. Switched package managers to vim plug, and got almost everything working. Jade (recently renamed to pug) syntax highlighting doesn't work. And copy pasting from in and out of nvim doesn't work. Looking through closed issues on your repo, but haven't found a solution that works for me yet.

Thanks for being so prompt and helpful here : )
