### ISSUE TITLE
:term Open in new split?

### ISSUE THREAD

**Issue by rgavs** [neovim/neovim#5073]
### Expected behavior:
At least personally, I expected :term to open in its own split
### Actual behavior:
I have however been unsatisfied when manipulating multiple splits and having :term open in place of the current split, but I imagine this is just a personal preference/design decision

**Comment by mhinz** [comment]
It's easy to combine Vim's commands to do it, so you can open it in the current window _or_ open a new window for it. But supposing it would open a window on its own, there wouldn't be a (good) way to "unwindow" it, if needed.

So, doing what you want is really just `:split | terminal` or `:vsplit | terminal` (or `:vs | te` or `:vs +te`).

```vim
command! -nargs=* T split | terminal <args>
command! -nargs=* VT vsplit | terminal <args>
```

**Comment by symphony2014** [comment]
But how can I resize this with init percent (like : 30% height)?

**Comment by tekknolagi** [comment]
@symphony2014 I think you can do `:split | resize 20 | term`

**Comment by ChristopherLClark** [comment]
Why does everyone seem to think there isn't a good way to unwindow a terminal? You can just `exit` and then escape and you are in command mode again.

**Comment by kflu** [comment]
I'm also suprised to see this is different from vim, in vim:

* `:ter` opens terminal in horizontal split
* `:vert ter` opens terminal in vertical split
* `:tab ter` opens terminal in new tab

**Comment by tusqasi** [comment]
More ways:
`:belowright split |terminal`
`:topleft split |terminal`
