### ISSUE TITLE
Support varying hlsearch by type of pattern (search versus substitution)

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#5075]
I noticed that neovim defaults to enabling `hlsearch`, so I spent some time trying to get used to it.  I found that when I searched for a pattern (with `/` or `?` or `*` or `#`), I typically liked the automatic highlighting; however, I found it obtrusive after a substitution (`s///`).

Could neovim offer a new variant of `hlsearch` that distinguishes between the type of search?  In particular, neovim could remember if the pattern came from a search or a substitution, and support enabling `hlsearch` only for the former but not the latter.  (vim's standard behavior of highlighting interactive substitutions with the `c` modifier should remain; that already uses the separate `hl-IncSearch` highlight.)

**Comment by ZyX-I** [comment]
Vim at 7.x already recorded both `:s//` patterns and interactive search patterns separately (and saved them in viminfo, as well as it is recorded what was the last), you may see traces of this behaviour in `:h :~` and adjacent topics. `&hlsearch` uses whatever appears to be stored in `@/` and `:s` also alters it.

**Comment by joshtriplett** [comment]
That sounds promising.  I don't think there are any hooks that would allow implementing this behavior in vimL, though; I think it'd still need an additional option or variant.

**Comment by Grimy** [comment]
It’s completely possible to achieve this in VimL. You may want to look at `:help :keeppatterns`. In particular, `:keeppatterns s/pattern/subst` will perform the subsitution without setting `@/` to `pattern` (and thus doesn’t cause highlighting).

To make this easier, I suggest adding `command! -range=% -nargs=1 S keeppatterns <line1>,<line2>s<args>` to your init.vim.

**Comment by justinmk** [comment]
Assuming the workaround is sufficient.
