### ISSUE TITLE
porting 7.4.{2055,2057,2058}

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#5081]
If ported, it should be `src/nvim/eval/list.c`, not `src/nvim/list.c`, also list definitions are to be moved to `eval/list.h`. (Same for dictionaries.)

Though I once wanted to move most of the typval_T-related stuff to `src/nvim/eval/typval.{c,h}`, not split them per-type. Specifically, what Bram moved to list.c and dict.c, clear_tv, GC, probably something else found after inspecting what is left.

**Comment by ZyX-I** [comment]
Actually second paragraph is a question whether 2057 and 2055 are to be ported or my variant should be accepted instead.

**Comment by ZyX-I** [comment]
Also 2058.

**Comment by ZyX-I** [comment]
2063 (that splits internal functions) is not the case, but it should be `eval/funcs.{c,h}`. Though I found it moves `tv_islocked` somewhere which should belong to eval/typval.c… Guess no patches should be ported (automatically, I mean), refactoring should be redone instead.

**Comment by ZyX-I** [comment]
I am currently doing refactoring and have a different plan:

- eval/typval: base typval_T manipulations
- eval/executor: ex_eval plus functions like ex_let which for some reason live in eval.c.
- eval/expressions: evalN functions. To be replaced with implementation that is based on similar file from luaviml branch.
- eval/gc: GC, obviously.

To be completed in a number of PRs.

Ping @justinmk

**Comment by justinmk** [comment]
@ZyX-I Completely fine with me.

**Comment by siddharth2610** [comment]
Is anyone working on this issue or can i work on this

**Comment by justinmk** [comment]
@siddharth2610 Please go ahead. Try to send small, isolated changes, not one giant change. Especially in the beginning, so that we can discuss sooner than later.

**Comment by siddharth2610** [comment]
Can you give some information about where to start from

**Comment by justinmk** [comment]
If the information in this PR isn't already enough, I think this is not the task one should start with :)

**Comment by jamessan** [comment]
@ZyX-I What parts of this are still relevant after your eval/{executor,typval} refactor?

**Comment by ZyX-I** [comment]
@jamessan Everything: eval/typval was refactored, others net (also eval/executor and eval/gc). Minus eval/expressions: I am currently writing a proper parser now.

**Comment by justinmk** [comment]
Based on https://github.com/neovim/neovim/issues/5081#issuecomment-234772243 is this still entry-level? And does this issue need to remain open?

**Comment by ZyX-I** [comment]
Moving things like `f_…` elsewhere is easy, but takes time. Should be still entry-level.

**Comment by justinmk** [comment]
@siddharth2610 So here is a task to start with: create two new files  `eval/funcs.c` and ` eval/funcs.h`. Using https://github.com/vim/vim/commit/73dad1e64cb42842d8259cb1a255a6fa59822f76#diff-ab0e9d9a1cba9d54d8f6e98913901833 as a reference, move some functions from `eval.c` to `eval/funcs.c`. For example, `get_function_name()` and `get_expr_name()`.

**Comment by siddharth2610** [comment]
Ok sure .

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/11828 , though there may be followup work.

**Comment by doubleloop** [comment]
potential followup patches:
```
eval.c
patch 8.1.1933: the eval.c file is too big  (tag: v8.1.1933)

evalfunc.c
patch 8.1.2042: the evalfunc.c file is too big  (tag: v8.1.2042)
patch 8.1.1989: the evalfunc.c file is still too big  (tag: v8.1.1989)
patch 8.1.1981: the evalfunc.c file is too big  (tag: v8.1.1981)
patch 8.1.1763: evalfunc.c is still too big  (tag: v8.1.1763)
patch 8.1.1734: the evalfunc.c file is too big  (tag: v8.1.1734)
patch 8.1.1687: the evalfunc.c file is too big  (tag: v8.1.1687)
patch 8.1.1608: the evalfunc.c file is too big  (tag: v8.1.1608)
patch 8.1.1608: the evalfunc.c file is too big  (tag: v8.1.1607)
patch 8.1.1584: the evalfunc.c file is getting too big  (tag: v8.1.1584)
```
