### ISSUE TITLE
`git gc` on repo

### ISSUE THREAD

**Issue by dperson** [neovim/neovim#5083]
On a fresh clone of the repo:

```
$ du -sh /tmp/neovim; (cd /tmp/neovim; git gc --aggressive --prune=all); du -sh /tmp/neovim 
79M     /tmp/neovim
Counting objects: 44891, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (43402/43402), done.
Writing objects: 100% (44891/44891), done.
Total 44891 (delta 31597), reused 12259 (delta 0)
53M     /tmp/neovim
```

Taking 26M extra space it seems like it's time to garbage collect and merge the cleaned-up `.git` files back in. Thanks.

**Comment by ZyX-I** [comment]
We are not github admins, we cannot do this.

**Comment by ZyX-I** [comment]
Also don’t use `git gc --aggressive`: http://stackoverflow.com/a/28721047/273566.
