### ISSUE TITLE
API for inspecting swapfiles

### ISSUE THREAD

**Issue by nyarly** [neovim/neovim#5086]
`nvim --version`: 0.1.4
- Vim (version: ) behaves differently? Eh? Vim can be built to run Ruby, but that's a workaround. See below.
- Operating system/version: OS X
- Terminal name/version: iTerm2
### Actual behaviour

When opening a file for which there is a swapfile, Neovim (and Vim) opens an irritating dialog about what to do. While it's a personal preference that the swapfile be recovered if there are changes and deleted otherwise, and there is an autocmd event to support this, Neovim doesn't have the hooks for vimscript to inspect the swapfile to make a determination
### Expected behaviour

That there be a function e.g. `swapfile()` that would return a dictionary of salient information about the swapfile so that `SwapExists` autocommands could make informed decisions.

For an example of what I'm looking for and how it was used in Vim, see the Ruby script at https://gist.github.com/nyarly/f7318fc17b47ca1d0abec77d79577da9

**Comment by nyarly** [comment]
Fair enough, but this always felt like a monstrous hack. Look at it: it depends on the binary format of the swapfile. I think I had to rummage around in Vim's header files to find that in the first place. It's (neo)vim's file format, and I shouldn't be up in its business like that.

**Comment by justinmk** [comment]
Besides an API, a lot could be gained by going a bit further with common-sense default decisions. Some ideas in [Domaian Conway's autoswap plugin](https://github.com/thoughtstream/Damian-Conway-s-Vim-Setup/blob/59981573773d682abb81df209c20e505ae7b703e/plugin/autoswap_mac_linux.vim#L55-L71).

https://github.com/neovim/neovim/issues/1610 also suggested "Delete All".

**Comment by justinmk** [comment]
`swapinfo()` function added in 24b7462b3cbf9a70f07f0a8e8da562a365cdc37a.

**Comment by nyarly** [comment]
@justinmk That's awesome - I'm thrilled!
