### ISSUE TITLE
Neovim ignores ftplugins

### ISSUE THREAD

**Issue by themightyoarfish** [neovim/neovim#5088]
Maybe I'm missing something obvious, but I have not found any documentation about why this would occur. It also did not happen before I upgraded to El Capitan from Yosemite.

- `nvim --version`: 
```
NVIM v0.1.5-630-g291c3c6
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Volumes/Data/Downloads/Sources/neovim/build/config -I/Users/Rasmus/Downloads/Sources/neovim/src -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/Users/Rasmus/Downloads/Sources/neovim/.deps/usr/include -I/opt/local/include -I/opt/local/include -I/Volumes/Data/Downloads/Sources/neovim/build/src/nvim/auto -I/Volumes/Data/Downloads/Sources/neovim/build/include
Compiled by Rasmus@rasmus-macbook-pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim (version: 7.3) behaves differently? Yes
- Operating system/version: OSX 10.11.5
- Terminal name/version: iTerm 3.0.4
- `$TERM`: xterm-256color

### Actual behaviour
Filetype plugins are ignored by neovim

### Expected behaviour
Neovim loads appropriate filetype plugins in `~/.vim/ftplugin/` (symlinked to `~/.config/nvim/.vim`)

### Steps to reproduce
1. Make `.vimrc` like this:
```
filetype on
filetype plugin indent on
syntax on
```
2. Have a filetype plugin in `~/.config/nvim/.vim/ftplugin` with custom mapping or such
3. Open file with that filetype
4. Mapping doesn't work

**Comment by mhinz** [comment]
`~/.vim` should point to `~/.config/nvim`, not `~/.config/.vim`.

**Comment by themightyoarfish** [comment]
Sorry, I mistyped.

**Comment by mhinz** [comment]
So, it works now? Can this issue be closed?

**Comment by themightyoarfish** [comment]
No, it doesn't work, the typo was merely in the report above. I set the links according to the `vim-differences` document. The `init.vim` file is correctly sourced, and also plugins (I use Vundle), but no ftplugins, as revealed by `:scriptnames`.

**Comment by mhinz** [comment]
Try this:

- put `echomsg "SUCCESS!"` into `~/.config/nvim/ftplugin/test.vim`
- run `nvim -u NORC --cmd 'filetype plugin on'` (or just `nvim -u NORC`, since `filetype plugin indent on` gets set by default/
- execute `:set ft=test`

You should see the "SUCCESS!" message in the command-line. If that's the case, there's something wrong in your `init.vim`.

**Comment by themightyoarfish** [comment]
I don't see the message.

**Comment by KillTheMule** [comment]
Might just be another typo in your report, but it's `~/.config/nvim`, NOT `~/.config/.nvim`.

**Comment by themightyoarfish** [comment]
Yeah, was a typo. I noticed however that when removing all the links to redo them, `XDG_CONFIG_HOME` is not set. I'm investigating, but I don't know where it usually gets set.

**Comment by KillTheMule** [comment]
I don't think it's usually set by most distributions, that's why we all point you to `~/.config` which is the default.

**Comment by jamessan** [comment]
If `$XDG_CONFIG_HOME` isn't set in the environment, then `$HOME/.config` is used instead.

**Comment by themightyoarfish** [comment]
Right, my mistake, I left `mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}` out, since the directory already existed, and did not realize the variable get set there.

**Comment by antonk52** [comment]
I think I am facing the same problem as the original author. I've checked the symlinks and everything looks as expected. aAlso tested by coping files to `~/.config/nvim` directly).

I have a `after/ftplugin/markdown.vim` file where I set a few defaults. This file is being sourced when I open a markdown file in regular vim, but not neovim. It does get sourced however if do `set ft=markdown` explicitly, though it is sourced on file open.

I've tried the suggestion by @mhinz by launching nvim with `nvim -u NORC --cmd 'filetype plugin on'` and also `nvim -u NONE --cmd 'filetype plugin on'`, yet results remain the same. The ftplugin files would not get sourced on editor/file open.

mMy current nvim and vim version are

<details>
<summary>
NVIM v0.4.4
</summary>
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes
 -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GE
NERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210210-5048-17yb4h2/neovim-0.4.4/build/config -I/tmp/n
eovim-20210210-5048-17yb4h2/neovim-0.4.4/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/
include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210210-5048-17yb4h2/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210210-5048-17yb4h2/neovim-0.4.4
/build/include
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4_1/share/nvim"
</details>

<details>
<summary>
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 18 2021 00:20:25)
</summary>
macOS version - x86_64
Included patches: 1-2525
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_info      -farsi             +langmap           +mouse_sgr         +profile           +tag_binary        +virtualedit
+arabic            +comments          +file_in_path      +libcall           -mouse_sysmouse    -python            -tag_old_static    +visual
+autocmd           +conceal           +find_in_path      +linebreak         +mouse_urxvt       +python3           -tag_any_white     +visualextra
+autochdir         +cryptv            +float             +lispindent        +mouse_xterm       +quickfix          -tcl               +viminfo
-autoservername    +cscope            +folding           +listcmds          +multi_byte        +reltime           +termguicolors     +vreplace
-balloon_eval      +cursorbind        -footer            +localmap          +multi_lang        +rightleft         +terminal          +wildignore
+balloon_eval_term +cursorshape       +fork()            +lua               -mzscheme          +ruby              +terminfo          +wildmenu
-browse            +dialog_con        +gettext           +menu              +netbeans_intg     +scrollbind        +termresponse      +windows
++builtin_terms    +diff              -hangul_input      +mksession         +num64             +signs             +textobjects       +writebackup
+byte_offset       +digraphs          +iconv             +modify_fname      +packages          +smartindent       +textprop          -X11
+channel           -dnd               +insert_expand     +mouse             +path_extra        -sound             +timers            -xfontset
+cindent           -ebcdic            +ipv6              -mouseshape        +perl              +spell             +title             -xim
-clientserver      +emacs_tags        +job               +mouse_dec         +persistent_undo   +startuptime       -toolbar           -xpm
+clipboard         +eval              +jumplist          -mouse_gpm         +popupwin          +statusline        +user_commands     -xsmp
+cmdline_compl     +ex_extra          +keymap            -mouse_jsbterm     +postscript        -sun_workshop      +vartabs           -xterm_clipboard
+cmdline_hist      +extra_search      +lambda            +mouse_netterm     +printer           +syntax            +vertsplit         -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/us
r/local/lib -o vim -lncurses -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/loc
al/lib -L/usr/local/Cellar/perl/5.32.1/lib/perl5/5.32.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -L/usr/local/opt/python@3.9/Frameworks/Python.fr
amework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation -lruby.3.0 -L/usr/local/Cellar/ruby/3.0.0_1/lib
</details>

**Comment by PsiPhire** [comment]
I'm also running into this issue. I've noticed that `after/ftplugin/markdown.vim` does get executed if I open vim with a markdown file, but if I open it with another file (e.g. a python file) and then open a markdown file in a new buffer, `after/ftplugin/markdown.vim` doesn't actually get run.

**Comment by Jarmos-san** [comment]
@zander-lee I had the same concern but I found some closure on #12951.
