### ISSUE TITLE
Get different executables for (non-)gui colors

### ISSUE THREAD

**Issue by hoschi** [neovim/neovim#5089]
To use true color support I have to set `termguicolors`, see https://github.com/neovim/neovim/wiki/Following-HEAD#20160511

But not every terminal I use support the full color range, like urxvt. Previously this worked fine with the environment variable, but with `termguicolors` I don't get it to work. My try was to create a second `init-truecolor.vim`:
```
set termguicolors
source ~/dotfiles/nvim/init.vim
```
and run `nvim -u ~/dotfiles/nvim/init-truecolor.vim`, but this doesn't work. Any other suggestions?

- `nvim --version`: 0.1.5-630-g291c3c6
- Operating system/version: Arch
- Terminal name/version: gnome-terminal/urxvt
- `$TERM`: xterm-256color

**Comment by tweekmonster** [comment]
Take a look at `:h terminal-emulator-configuration`.  You'll need to set base palette's colors using `g:terminal_color_[0-15]` to `#rrggbb` values.

Here's mine for reference:
```
let g:terminal_color_0  = '#000000'
let g:terminal_color_1  = '#ff5555'
let g:terminal_color_2  = '#50fa7b'
let g:terminal_color_3  = '#f1fa8c'
let g:terminal_color_4  = '#bd93f9'
let g:terminal_color_5  = '#ff79c6'
let g:terminal_color_6  = '#8be9fd'
let g:terminal_color_7  = '#f8f8f2'
let g:terminal_color_8  = '#555555'
let g:terminal_color_9  = '#ff5555'
let g:terminal_color_10  = '#50fa7b'
let g:terminal_color_11  = '#f1fa8c'
let g:terminal_color_12  = '#bd93f9'
let g:terminal_color_13  = '#ff79c6'
let g:terminal_color_14  = '#8be9fd'
let g:terminal_color_15  = '#f8f8f2'
```

**Comment by ZyX-I** [comment]
@tweekmonster How is this related?

@hoschi You may always use `:let &termguicolors = !empty('$NVIM_TUI_ENABLE_TRUE_COLOR')`. If you have working setup that uses environment variables it is not impossible to continue using them.

**Comment by tweekmonster** [comment]
@ZyX-I ah crap, I misread the issue.

**Comment by hoschi** [comment]
@ZyX-I thanks, this works
