### ISSUE TITLE
:UpdateRemotePlugins is unstable

### ISSUE THREAD

**Issue by hkupty** [neovim/neovim#5090]
- `nvim --version`: `NVIM v0.1.5-630-g291c3`
- Vim (version: ) behaves differently? N/A
- Operating system/version: `4.6.4-1-ARCH`
- Terminal name/version: `termite v11`
- `$TERM`: `xterm-256color`

### Actual behaviour
Sometime I have to double `:UpdateRemotePlugins` so it can understand a remote plugin has updated (i.e. added a function). If I don't, it says it has no host registered for that plugin. Also, no matter how many times I call `:UpdateRemotePlugins`, `:CheckHealth` always returns that plugins are out of date and no plugins are registered (see message below).

```
Checking: Remote Plugins
  Status: Out of date
  Messages:
    * "deoplete.nvim" is not registered.
    * "iron.nvim" is not registered.
    * Run :UpdateRemotePlugins
```

### Expected behaviour
Running `:UpdateRemotePlugins` once after clean install of remote plugins should just work.

### Steps to reproduce using `nvim -u NORC`
I don't know how is this supposed to be done, but simply installing [hkupty/iron.nvim](http://github.com/hkupty/iron.nvim) and running `:UpdateRemotePlugins` should just trigger the problem.
Running the command a second time _normally_ fixes it.

**Comment by tweekmonster** [comment]
Do you know if a `.-rplugin~` file is generated somewhere?  This may be fixed once #5050 is merged.

**Comment by hkupty** [comment]
Yes, there is a `.init.vim-rplugin~` at `~/.config/nvim` which is regenerated on `:UpdateRemotePlugins.

**Comment by tweekmonster** [comment]
Try deleting it and run `:UpdateRemotePlugins` to be sure that it's actually being re-written.  If it does, check the contents and make sure that the path to the plugins matches with what actually exists.

**Comment by hkupty** [comment]
Yes, after removing and running the command again it is regenerated and points to the correct path

**Comment by tweekmonster** [comment]
Is this more about the `:CheckHealth` report?  That command can only report on what is already loaded vs what it sees in `runtimepath`.  `:CheckHealth` doesn't read the manifest file itself.  When you run `:UpdateRemotePlugins` the manifest is written, but is still not considered "loaded" until Neovim is restarted.  After restarting `:CheckHealth` shouldn't report that you need to run `:UpdateRemotePlugins`.

**Comment by hkupty** [comment]
`:CheckHealth` is misleading but not the problem here. I understand it might need improvements.

The thing is I sometimes have to double run `:UpdateRemotePlugins` after updating my plugins. I believe that something is preventing the remote host to identify the plugin.

I'll post the error message here as soon as I'm back to my computer.

**Comment by hkupty** [comment]
That's weird. I'm unable to reproduce the error now.
It happens when I update my remote plugins (via vim-plug) and normally it's when I change functions body even when not changing its signature.
It says something about no handler defined for command.

Anyway, I'll close this for now. Is it ok if I reopen it if it happens again?
