### ISSUE TITLE
Tmux Cursor shape not working properly

### ISSUE THREAD

**Issue by troym9731** [neovim/neovim#5096]
- `nvim --version`: NVIM 0.1.4
- Vim (version: ) behaves differently? (7.4) Yes
- Operating system/version: OS X 10.11.6
- Terminal name/version: iTerm2 v3.0.5
- `$TERM`: xterm-256color

### Actual behaviour
Cursor does not change shape when going into insert mode while using tmux. It works just fine outside of tmux.

### Expected behaviour
Cursor shape changes to vertical bar when in insert mode.

### Steps to reproduce
Wasn't sure how to use `nvim -u NORC` to properly set `$NVIM_TUI_ENABLE_CURSOR_SHAPE`. So I used a config file with just `let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1`. That works outside of tmux, but not within.

Following this issue: https://github.com/neovim/neovim/issues/4219, I also set `set -ga terminal-overrides ',*:Ss=\eE[%p1%d q:Se=\eE[2 q'`. However, that doesn't work for me either. 

I was hesitant to make an issue, as I can't seem to find anyone else in the past few months currently experiencing this problem, which would mean the problem is me haha. But with the problem persisting even with a one line nvim/init.vim, I'm unsure what to do next for debugging.

**Comment by brcolow** [comment]
Try setting your `$TERM` to screen-256 when using tmux by adding:

`set -g default-terminal "screen-256color"`

to your tmux.conf

**Comment by troym9731** [comment]
Nope, no luck :/

**Comment by KillTheMule** [comment]
Did you see https://github.com/neovim/neovim/wiki/FAQ#cursor-shape-doesnt-change-in-tmux?

**Comment by mhinz** [comment]
I can't reproduce this with almost (iTerm 3.0.4 instead of 3.0.5) environment. Neither with v0.1.4 (which is ~450 patches behind) nor master. I don't let tmux override any terminfo entries.

@troym9731 `nvim -u NORC --cmd 'let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1'` Does this work for you?

**Comment by Kjir** [comment]
I can reproduce the issue as well and with the instructions from the FAQ I don't get different results. On the other hand, @mhinz 's trick works for me.

iTerm: 3.0.4
nvim: 0.1.4 (the one from `brew install neovim`)
tmux: 2.2
$TERM: screen-256color

**Comment by Kjir** [comment]
Disregard my previous comment: if I put `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1` in my `init.vim` it does work as expected, so I actually do *not* reproduce the bug!

**Comment by troym9731** [comment]
I'm using tmux 2.2. Following your comment, it still didn't work inside tmux. However, you mentioned not having any terminal overrides in your `.tmux.conf`. So I started commenting out lines in my `.tmux.conf`, and found that `set -g terminal-overrides ',xterm-256color:Tc'` was causing the issue. Looks like adding the `-a` option fixed it for me... `set -ga terminal-overrides ',xterm-256color:Tc'`. 

I hardly know anything about what goes into a terminal, so I'm unsure what was really causing all this. But I really appreciate all the help you guys gave me, so thanks everybody!

**Comment by pyaf** [comment]
Note: restart terminal to see the changes :)

**Comment by luong-komorebi** [comment]
A note if you are using tmux with a custom term-info (like many tutorials in the internet instructs you to have something like - *italic* in vim)
This is what you want inside your tmux.conf 
```
set -g default-terminal 'tmux-256color' # replace this with your custom term-info name
set -ga terminal-overrides ',*:Tc' # this is for 256 color
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' # this is for the cursor shape
```

**Comment by justinmk** [comment]
@luong-komorebi that's only necessary in some cases. Newer tmux on newer systems should not need that. 

see also

- https://github.com/neovim/neovim/issues/9598#issuecomment-462243536
- https://github.com/tmux/tmux/issues/1137#issuecomment-339675774
- https://github.com/neovim/neovim/pull/9601
