### ISSUE TITLE
Delay when switching from insert to edit mode

### ISSUE THREAD

**Issue by tsujigiri** [neovim/neovim#5098]
I often save the file immediately after switching from insert mode to edit mode, pressing ESC. neovim has a slight delay, after which it switches. When I type `:w` within that delay, it doesn't get registered as a command by neovim, but typed into the buffer. The switch to edit mode is then also not happening.

- `nvim --version`:

```
NVIM 0.1.4
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.4/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: 7.4.1910) behaves differently?

Sometimes has a delay, too. It writes the `:w` to the buffer, but after switching it gets removed again and the file is written.

- Operating system/version:

Arch Linux

- Terminal name/version:

Gnome Terminal 3.20.2-1

- `$TERM`:

`screen`

### Actual behaviour

When in insert mode, quickly typing <ESC>:w does not exit insert mode and writes the file, it just writes ":w" to the buffer.

### Expected behaviour

Insert mode is exited, the file is written, nothing is written to the buffer.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
aaaaaaaa<ESC>:waaaa

```

**Comment by fmoralesc** [comment]
https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
