### ISSUE TITLE
Match and %-jump between angle brackets (<>) by default

### ISSUE THREAD

**Issue by kalikiana** [neovim/neovim#5099]
I've got this line in my init.vim and it's been one of the basics to have while I was using vim for some time.

set mps+=<:>

With neovim aiming for a better out of the box experience, could this be a default? I imagine it would be useful for many people.

**Comment by KillTheMule** [comment]
Sounds like a nobrainer. Does anyone know why it's not in vim? `:h mps` specifically mentions this example. Does it conflict with any setting of matchit.vim? Maybe with the setting that lets you jump between html tags?

**Comment by fmoralesc** [comment]
This is enabled by default in html files, for what other filetypes would this be useful?

**Comment by Grimy** [comment]
Off the top of my head: Java (generics), C++ (templates), Perl (many many uses), XML (tags), Rust (type arguments), VimL (key-notation), PostScript (dictionaries), Ruby (%q<a b c> notation).

**Comment by fmoralesc** [comment]
I think adding this to those filetypes might be better idea than setting it as a global default.

**Comment by justinmk** [comment]
As a runtime change, the change should be sent to vim_dev, and the individual maintainers of the ftplugins or whatever.

**Comment by tweekmonster** [comment]
Just an FYI: The maintainer is @benjifisher, but his activity seems to be low on Github.  There's an [annoying issue](https://github.com/benjifisher/matchit.zip/pull/2) with matchit.vim that I think should've been fixed a long time ago, but the PR has been sitting since last year.
