### ISSUE TITLE
!cat shows tabs as 1 space

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim#5100]
- `nvim --version`: v0.1.5-634-g0595da8
- Vim (version: master) behaves differently? Yup.
- Operating system/version: OSX 10.11.6
- Terminal name/version: iTerm 3.0.4
- `$TERM`: xterm-256color

### Actual behaviour

Tabs are shown as (or got replaced by?) **1** space.

### Expected behaviour

Tabs are shown as **8** spaces.

### Steps to reproduce using `nvim -u NORC`

```
$ echo '\tfoo' > test
$ nvim -u NORC +'!cat test'
```

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/4376
