### ISSUE TITLE
Opening a mail in /tmp/ kills neovim and xterm its running in

### ISSUE THREAD

**Issue by matthiasbeyer** [neovim/neovim#5101]
- `nvim --version`:

```
NVIM 0.1.4
Build type: Release
Compilation: /nix/store/r8b456lwk0n1hinz92hwqsgb28c987b3-gcc-wrapper-5.4.0/bin/gcc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/config -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/src -I/nix/store/5hnxqh49wh4dy30zs92wh2axdslyvdzy-libuv-1.9.1/include -I/nix/store/f7mqgnazmd320mlklaxx2pn0jh1b2nv5-libmsgpack-1.1.0/include -I/nix/store/fi7ad4pb3bwsr4cl4x5cna0kd5wwlhrm-luajit-2.1.0-beta1/include -I/nix/store/scwrbpkhqxiyj89ilj68vagzaz7jh9i5-unibilium-1.2.0/include -I/nix/store/4d3ckfmmc5a5ziknc8a1wa9y8dfifvlh-libtermkey-0.18/include -I/nix/store/0bpgyf3vqvbczd8v37r5qr88dxi0qdc2-neovim-libvterm-2015-11-06/include -I/nix/store/mlmag0vp4i0cfs8q8yxyhrjsi1aaq9mz-jemalloc-4.1.1/include -I/nix/store/dkcy3lp6j988jw8sycvag3brgi6qnkxi-glibc-2.23-dev/include -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/src/nvim/auto -I/tmp/nix-build-neovim-0.1.4.drv-0/neovim-v0.1.4-src/build/include
Übersetzt von nixbld

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "
/nix/store/3a91azkd5hkjm0r1fcfai6qgrp51hhzc-neovim-0.1.4/share/nvim"
```

- Vim (version: ) behaves differently?
- Operating system/version: NixOS:
    * System: 16.09pre86979.d458029 (Flounder)
    * Nix version: nix-env (Nix) 1.11.2
    * Nixpkgs version: "16.09pre86979.d458029"
- Terminal name/version: xterm 325
- `$TERM`: xterm

### Actual behaviour

nvim gets killed, xterm gets killed as well.

### Expected behaviour

File gets opened

### Steps to reproduce using `nvim -u NORC`

Calling nvim with `-u NORC` works. The point is, that with nixos, I can checkout older generations of my system, and my setup also rolls the nvim configuration back, if I checkout an older generation. So the only thing that isn't covered by this rollback thing is my filetype plugin stuff.

Although, I have my filetype plugin stuff in a git repository and I tried some older versions of these files, and it still crashed.

Can someone help me debug this?

**Comment by justinmk** [comment]
Is there a crash dump?

**Comment by matthiasbeyer** [comment]
@justinmk where would this crashdump live?

It _seems_ that this is either because of the filetype (mail, of course) or because of the location. I would rather say because of the location, because if I `cat /tmp/mutt-...something > ~/foobar` and open `foobar` with nvim, it works.

**Comment by matthiasbeyer** [comment]
Ah, yes. If I do the `cat` thing from above, it doesn't set the `ft`. If I manually `:set ft=mail`, neovim crashes.

**Comment by matthiasbeyer** [comment]
For completeness, this is my `ftplugin/mail.vim`:

```viml
" mails
" -----
setlocal textwidth=70
setlocal wrap

setlocal fo=aw

set colorcolumn=71
```

**Comment by matthiasbeyer** [comment]
I do not believe anymore that this is a nvim bug and reported in https://github.com/NixOS/nixpkgs/issues/17170 in my distribution packages. I guess this will be pushed further upstream as soon as we figure out where the problem is.

Thank you, @justinmk, for your attention on this. I will close this now.

**Comment by matthiasbeyer** [comment]
It seems (see my latest comments in https://github.com/NixOS/nixpkgs/issues/17170) that this is actually a neovim problem.

So I'm reopening this.

**Comment by matthiasbeyer** [comment]
A guess of mine is, that the latest changes to xterm in my distro changed something inside xterm which isn't handled by neovim. Here is the diff https://github.com/NixOS/nixpkgs/pull/16604/commits/a98ae8e1526055c347409540d3d5c9dd104b81cb.

It _seems_ like reverting this patch for my local system and rebuilding xterm without this option fixes my problem.

**Comment by justinmk** [comment]
If xterm gets killed, it will take nvim with it. Alternatively, if nvim happens to send some sequence to xterm that causes xterm to crash, that is also a xterm bug. Maybe Vim doesn't send that sequence for some reason.

There's no repro steps here ("install nixos" is not a minimal repro). And so far there's no mention of a segfault or abort, so not a "crash".

We can re-open this if a more narrow problem is identified.

**Comment by matthiasbeyer** [comment]
Note that this was indeed an issue with xterm and the `decLocator` feature, as more-or-less documented here: https://github.com/NixOS/nixpkgs/issues/17170

Disableing the `decLocator` feature solved the issue for me. Sorry for the noise in your issue tracker!
