### ISSUE TITLE
ctrl-[ doesn't stop inserting

### ISSUE THREAD

**Issue by ijt** [neovim/neovim#5104]
- `nvim --version`: v0.1.5-643-g8c1fb99
- Vim (version: ) behaves differently? All of them
- Operating system/version: Ubuntu 12
- Terminal name/version: ssh + tmux
- `$TERM`: screen-256color

### Actual behaviour
Hit 'i' to start inserting. Type some stuff. Hit ctrl-[ to stop inserting. Hit j and k to move around. Instead of moving around, j's and k's get inserted.

### Expected behaviour
ctrl-[ should stop inserting immediately.

### Steps to reproduce using `nvim -u NORC`
Huh?

```
nvim -u NORC

```

**Comment by KillTheMule** [comment]
Can't reproduce, probably something about ssh/tmux. Did you check https://github.com/neovim/neovim/wiki/FAQ?

**Comment by ijt** [comment]
You're right, I tried it without tmux and the problem went away. But that's
not a workable solution for me because tmux is so useful.

**Comment by fmoralesc** [comment]
Did you try https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed ? CTRL-key presses are sent to the terminal as ESC-prefixed codes.

**Comment by justinmk** [comment]
It's covered in the FAQ, linked above. Tmux has its own "escape time" which sits in between the terminal and the application (nvim).

**Comment by ijt** [comment]
This works fine in Vim. Why make users jump through hoops to get sane
behavior out of the box?
