### ISSUE TITLE
Open a new buffer with filetype option (or similar) set

### ISSUE THREAD

**Issue by azbshiri** [neovim/neovim#5108]
- `nvim --version`: v0.1.5-645-g4633e3b
- Vim (version: ) behaves differently? No
- Operating system/version: Fedora 23
- Terminal name/version: tinyterm
- `$TERM`: xterm-256color

### Actual behaviour
enew blah balah
### Expected behaviour
enew blah:ft=foo blah:ft=bar
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by mhinz** [comment]
I'm not even sure what this is about. Is this a feature request? What's your use case?

What's wrong with `:enew | set ft=blah`?

**Comment by azbshiri** [comment]
yeah, it's a feature request. but you already had the solution so this issue should be closed.
