### ISSUE TITLE
s$^$\=capture("s/^//gn") Locks Neovim into Sandbox mode

### ISSUE THREAD

**Issue by Tarmean** [neovim/neovim#5118]
- `nvim --version`:
NVIM 0.1.5-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/build/config -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/src -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-D20Zw5/neovim-0.1.4ubuntu1+git201607120443+2644+20~ubuntu16.04.1/build/include
Compiled by buildd@lgw01-59

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Operating system/version: Ubuntu 16.04.1 LTS
- Terminal name/version: Konsole 15.12.3
- `$TERM`: screen-256color

### Actual behaviour
Neovim softlocks in Sandbox mode
### Expected behaviour
Neovim inserts the result of `s/^//gn` at the start of the line

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:s$^$\=capture("s/^//gn")
```

**Comment by jamessan** [comment]
Seems like Bram hit the same problem when implementing `execute()`.
