### ISSUE TITLE
getpos("'[") returns [0, 1, 1, 0] in autocmd

### ISSUE THREAD

**Issue by edi9999** [neovim/neovim#5121]
With the following vimrc

```
set nocompatible

function! StripTrailingWhitespace()
    echom(string(getpos("'[")))
    echom("post")
endfunction

augroup Filetypes
  autocmd!
  autocmd FileType * autocmd BufWritePre <buffer> :call StripTrailingWhitespace()
augroup END
```

then : 

edit a file : 

```
vim .bashrc
y}        "yank a paragraph
}          "go one paragraph down
}p        "paste the paragraph
:echom(string(getpos("'[")))   "returns [0, 19, 1, 0]
:w                                           " returns [0, 1, 1, 0]
```

Neovim version is : 

```
NVIM v0.1.5-280-g176f223
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
```

The issue also occurs on vim 

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  2 2016 10:02:17)
Included patches: 1-1868
```

**Comment by jamessan** [comment]
Performing a write sets the `'[` and `']` marks to the range of the buffer which was written.  In the case of `:w`, that is the entire buffer.

The fact that this happens by the time `BufWritePre` is called is documented in `:help autocmd-use`.

**Comment by justinmk** [comment]
> Performing a write sets the '[ and '] marks to the range of the buffer which was written. In the case of :w, that is the entire buffer.

I've been wondering if there is any reason we could not change this. Does anyone (or any plugin) actually find this behavior useful?

**Comment by jamessan** [comment]
Yes, any plugin that needs to know the range of the buffer that's being written.  At the very least, I rely on it for `BufWriteCmd`/`FileWriteCmd` in [vim-gnupg](https://github.com/jamessan/vim-gnupg).

I recall having a thorough discussion about the merits of this behavior before with @paradigm and can dig that up if it's desired.

**Comment by edi9999** [comment]
Ok, I didn't read the help enough, it seems that yes, this behavior is well documented. I just find it strange since the '[ and '] are used to store multiple things (last paste and last edit or last save)

**Comment by jamessan** [comment]
Last paste, edit, or save are all the same type of thing -- the last modification.  However, you're right that it is representing multiple things.  It's either the last modification or the last yank.

**Comment by tweekmonster** [comment]
I apparently didn't read that part of the doc either.  This threw me off when I made [spellrotate](https://github.com/tweekmonster/spellrotate.vim).  It's using `'[` and `']` to keep track of the replaced word.  At the time, I wasn't sure if it was a bug when it would start looking for spell suggestions using the entire buffer.

`:help autocmd-use` is probably the last place I would ever think to look in this case.  Maybe the documentation for `'[` and `']` should also mention `These are changed on the *ReadPre, *ReadPost, *WriteCmd, *WritePre, and *AppendPre autocmd.  See: |autocmd-use|.`

**Comment by justinmk** [comment]
> At the very least, I rely on it for BufWriteCmd/FileWriteCmd in vim-gnupg.

So if a user saved/restored `'[` and `']` in BufWritePre, BufWritePost, that wouldn't interfere with BufWriteCmd, right? Asking for a friend.

**Comment by jamessan** [comment]
> So if a user saved/restored '[ and '] in BufWritePre, BufWritePost, that wouldn't interfere with BufWriteCmd, right? Asking for a friend.

I'm not quite sure what you're friend would need to save/restore.  The marks are already set by the time those events are triggered.  If they weren't, then the range of the write would need to be communicated by some other mechanism... but why invent another mechanism to communicate the range?
