### ISSUE TITLE
The terminal buffer is gone after buffer switch

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#5122]
- `nvim --version`:  

```
NVIM v0.1.5-851-g56f1780
Build type: Debug
```

- Vim (version: ) behaves differently?  N/A
- Operating system/version:  Manjaro Linux
- Terminal name/version: st 0.6
- `$TERM`: st-256color

### Actual behaviour
The terminal buffer is not listed after buffer switch.

### Expected behaviour

The ternimal buffer is listed.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NONE

1. :terminal
2. :edit file
3. :buffer 1
4. :ls
5. :buffer 2
6. :ls
```

Note:  The behavior is not occurred if you set `hidden` option.

**Comment by mhinz** [comment]
See https://github.com/neovim/neovim/issues/2368 and https://github.com/neovim/neovim/issues/3340.

**Comment by Shougo** [comment]
I get it.  Thanks.
