### ISSUE TITLE
Strange issue with indentation while formatting

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#5123]
# Steps to reproduce
1. Open the provided `test.tex` file with the provided `minivimrc` file with `nvim -u minivimrc test.tex`
2. First observe that the file is already indented properly: `gg=G`
3. Next observe that the indentation becomes wrong when the text is formatted with `gggwG`

I'm using neovim 0.1.4 on Arch Linux.
## Comment

The test file is in LaTeX format, but this is not relevant. However, it is very difficult to make a good minimal test file example as the bug occurs seemingly randomly.

I noticed the bug while working on a `formatexpr` for [vimtex](https://github.com/lervag/vimtex), see [here (vimtex issue #436)](https://github.com/lervag/vimtex/issues/436#issuecomment-234905144).

I do not understand what is happening here, but I did notice that the `getline` function returns something different, when the indent expression was called from `gw`. In particular, it return longer lines, as if the lines had been joined together. It was still called for all the lines, though.

I've also asked about this phenomenon on [vi.stackexchange.com](http://vi.stackexchange.com/questions/8964/can-someone-explain-the-strange-behaviour-with-indenting-during-reformatting). Here I've noted from a discussion on one of the answers that the implicit use of the `indentexpr` could be documented better for `gw` and `gq`.

This bug is also [reported for Vim](https://github.com/vim/vim/issues/951). At the moment, people there seem to consider it as simply a "peculiarity", but I don't get a good explanation for why I should accept that this is not a bug. I was hoping that someone here might consider it and perhaps find a way to fix it. If so, then I think we could submit a patch for Vim as well.
# minivimrc

``` vim
set textwidth=79
set indentexpr=MyIndent()

function! MyIndent()
  let l:nprev = prevnonblank(v:lnum - 1)
  if l:nprev == 0 | return 0 | endif

  let l:cur = getline(v:lnum)
  let l:prev = getline(l:nprev)

  let l:indent  = max([Count(l:prev, '(') - Count(l:prev, ')'), 0])
  let l:indent -= max([Count(l:cur, ')') - Count(l:cur, '('),   0])

  return indent(l:nprev) + &sw*l:indent
endfunction

function! Count(line, pattern)
  let sum = 0
  while 1
    if match(a:line, a:pattern, 0, sum + 1) == -1
      return sum
    endif
    let sum += 1
  endwhile
endfunction
```
# test.tex

``` tex
Therefore, in that case the observed dynamics cannot be truly
Markovian. We can still approximately capture the observed density dynamics
with eq.~\ref{eq:fpe}; however the local coefficients are then effectively
averages over the co-evolving unobserved distribution. For example, $\vec
v(\vec x,t)=\int p(\vec x^u|\vec x,t)v(\vec x,\vec x^u,t)dx^u$. This has some
important consequences. First, the effective Markovian coefficients $\vec v,
\lambda, D$, will generally depend on time, reflecting the time evolution of
the hidden $p(\vec x^u)$ over the time scale of the experiment. Second, the
effective coefficients may also depend on the initial condition: a cell
population started concentrated around label $\vec x_0$ implies a certain
distribution over $x^u$ when sampled at label $\vec x$ some time later; another
population started around $\vec x_1$ carries a different history when it, too,
visits $\vec x$ later. Therefore, for instance the effective drift $\vec v(\vec
x)$ will be different in the two cases. We conclude that, if unobserved degrees
of freedom have dynamics on the time scale of the experiment eq.~\ref{eq:fpe}
is an approximation whose coefficients become \emph{non-universal} (dependent
on intial conditions) and \emph{time-dependent}.
```

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. 

Tracked upstream at https://github.com/vim/vim/issues/951.
