### ISSUE TITLE
:term does not work 

### ISSUE THREAD

**Issue by crusoexia** [neovim/neovim#5125]
- `nvim --version`:
NVIM v0.1.5-372-gd97a97d
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160605-3327-ezr9eu/build/config -I/tmp/neovim-20160605-3327-ezr9eu/src -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160605-3327-ezr9eu/build/src/nvim/auto -I/tmp/neovim-20160605-3327-ezr9eu/build/include
Compiled by crusoexia@Crusoe-Mac.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
- Vim (version: ) behaves differently? N/A
- Operating system/version: OSX 10.10.5
- Terminal name/version: iterm2 3.0.5
- `$TERM`:zsh: command not found: xterm-256color

### Actual behaviour
:term does not work, it only print the log
<img width="348" alt="screen shot 2016-07-29 at 2 39 57 pm" src="https://cloud.githubusercontent.com/assets/5928754/17239930/6fcc5c62-559a-11e6-9d81-e49365565ccb.png">

but if use `nvim -u NORC`, the command works

### Expected behaviour
:term should works

**Comment by justinmk** [comment]
If you want `--login` (not recommended at all), set `shellcmdflag`. Don't `set shell=bash\ --login`.
