### ISSUE TITLE
[RFC] Using libuv private API uv_translate_sys_error?

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5128]
While rebasing #810 I came across the new check for libuv's `uv_translate_sys_error()` used in [os/fs.c](https://github.com/neovim/neovim/blob/5f1a153831d480180b2203120cff776d771ec1a4/src/nvim/os/fs.c#L400). The check succeeds and the code works with gcc/mingw however it seems the function is internal to libuv, definitely not part of the libuv headers.

Maybe the symbol is accidentally exported in the libuv library and gcc is too permissive, but MSVC will not build with a reference error. Its also not the first time the CMake's function check has behaved differently in Windows, although in this case I consider MSVC is doing the right thing.

Upstream issue  https://github.com/libuv/libuv/issues/79 that proposes exposing the API

How exactly should we address this

1. Import the libuv code for uv_translate_sys_error(), the function itself is fairly simple. And given our current use the possibility breakage seems low - or at least lower than the alternative
2. Wait for (or rather push) upstream
3. Is there anything we should be doing in CI to detect this? compiler flags, etc

**Comment by jamessan** [comment]
Using `-Wimplicit-function-declaration` would probably help catch this. Although it's not exposed in the headers, the CMake check is probably testing linking, which will work since it doesn't have hidden visibility.  Also, remember that C will assume a function returning int if it can't find a declaration, which is what uv_translate_sys_error does.

**Comment by jamessan** [comment]
Let's see if #5129 works like I think it should. :)

**Comment by jamessan** [comment]
Hmm, CMake doesn't detect uv_translate_sys_error on the Linux builds, so `-Wimplicit-function-declaration` doesn't catch anything.  @equalsraf can you try that commit in the mingw build?

**Comment by jamessan** [comment]
Or is the problem that CMake's function detection when using MSVC incorrectly flags the function as present, which then causes MSVC to error out?

**Comment by equalsraf** [comment]
No, MSVC reports it as not found, while mingw reports it as found ([logs](https://ci.appveyor.com/project/equalsraf/neovim/branch/tb-mingw))

**Comment by jamessan** [comment]
Hmm, why is CMake reporting uv_translate_sys_error is [not found] for the msys build but then we see the implicit declaration [warnings] indicating we're building as if it were found?

[not found]: https://ci.appveyor.com/project/equalsraf/neovim/build/941/job/5so0vrschra07i3t#L1791
[warnings]: https://ci.appveyor.com/project/equalsraf/neovim/build/941/job/5so0vrschra07i3t#L2525

**Comment by jamessan** [comment]
Ah, because HAVE_UV_TRANSLATE_SYS_ERROR is explicitly defined in equalsraf/neovim@62298f06ec7018f03298764ea04230835d0934b1.

**Comment by jamessan** [comment]
Is the [fallback] code not working on Windows?

[fallback]: https://github.com/neovim/neovim/blob/5f1a153831d480180b2203120cff776d771ec1a4/src/nvim/os/fs.c#L402-L405

**Comment by equalsraf** [comment]
Yes the fallback does not work, for now I will just import the function and maybe start a PR upstream.

Sorry for the extra noise, I was under the impression the function was being detected in Unix builds.

**Comment by justinmk** [comment]
> Import the libuv code for uv_translate_sys_error(), the function itself is fairly simple. And given our current use the possibility breakage seems low - or at least lower than the alternative

In favor of this, just put a TODO on the function and include URL to the upstream PR.

**Comment by equalsraf** [comment]
> In favor of this, just put a TODO on the function and include URL to the upstream PR.

Already done as part of #5130 (#810 has a lousier fix, that I'll remove later)
