### ISSUE TITLE
:terminal doesn't inherit $TERM environment variable

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#5138]
- `nvim --version`: NVIM v0.1.5-664-gfaca814 (+acl +iconv +jemalloc +tui)
- Operating system/version: Linux 4.4.6-gentoo
- Terminal name/version: rxvt-unicode v9.21
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
When starting neovim with `nvim -u NORC`, `:echo $TERM` displays `rxvt-unicode-256color`. However, when running `:term echo $TERM`, `xterm-256color` is displayed.

### Expected behaviour
`:term echo $TERM` should display `rxvt-unicode-256color`.

This bug prevents me from using backspace correctly. I've currently added `[ "$NVIM_LISTEN_ADDRESS" != "" ] && export TERM=rxvt-unicode-256color` to my .zshrc as a temporary fix but I'd rather not resort to such hacks.

**Comment by ZyX-I** [comment]
It *must not* display `rxvt-unicode-256color`. `:terminal` is terminal emulator on its own, and *it* interprets incoming escape sequences, *not* `rxvt-unicode`. Escape sequences sent to `rxvt-unicode` are sent from Neovim TUI  and have nothing to do with escape sequences sent by app to Neovim’s `:terminal`, except that terminal buffer contents and highlighting is the result of interpretation.

So using $TERM you suggest will result in wrong understanding regarding which sequences app may send: it sends them for libvterm, not for rxvt-unicode.

**Comment by ZyX-I** [comment]
If you need to fix backspace, file a bug report regarding backspace problem, not regarding how you think it should be fixed. But first search  issue tracker, there is a number of different TUI keyboard input handling issues.

**Comment by ZyX-I** [comment]
Note that backspace sent to application under `:terminal` also passes through Neovim: first TUI receives it from  tty, converts to internal representation and only then resends to `:terminal` tty. There is no direct connection between rxvt-unicode and `:terminal` tty as well, so it also cannot justify incorrect $TERM you suggest.
