### ISSUE TITLE
Neovim-qt executable doesn't open file passed as argument

### ISSUE THREAD

**Issue by sevcsik** [neovim/neovim#5150]
Version: NVIM 0.1.5-dev (appveyor build from two weeks ago)
Operating system: Windows 10 Enterprise (neovim-qt)
Terminal: Both CMD.exe and Cygwin

Steps to reproduce:
1. Open a CMD window
2. Type `"<path to neovim-qt>\bin\nvim-qt.exe" asd.txt`

Excepted result: asd.txt is opened
Actual result: no file opened

**Comment by justinmk** [comment]
See https://github.com/equalsraf/neovim-qt/pull/155
