### ISSUE TITLE
UpdateRemotePlugins requires root access

### ISSUE THREAD

**Issue by DJMcMayhem** [neovim/neovim#5152]
- `nvim --version`: NVIM 0.1.5-dev
- Operating system/version: Ubuntu 16.04.1.LTS
- Terminal name/version: XTerm(322)
- `$TERM`: xterm-256color

### Actual behaviour

When calling `:UpdateRemotePlugins`, I get this error:

    Error detected while processing function remote#host#UpdateRemotePlugins:
    line   16:
    E482: Can't create file /usr/share/nvim/runtime/.filetype.vim-rplugin~

Unless I launch neovim as root, in which case I get:

    remote/host: generated the manifest file in "/usr/share/nvim/runtime/.filetype.vim-rplugin~"

### Steps to reproduce using `nvim -u NORC`

I put [this python file](https://github.com/jacobsimpson/nvim-example-python-plugin/blob/master/rplugin/python/nvim-example-python-plugin.py) in `~/.config/nvim/rplugin/python/test.py`. Then launch neovim from my home directory with `nvim -u NORC`, and call `:UpdateRemotePlugins`.

On a slightly meta note, I have never raised issues on this repo, so I'm not sure if I have correctly provided enough information. Should I have provided *every single feature* listed by `nvim --version`? Also, I'm not sure if this would make more sense on the [neovim-python-client](https://github.acom/neovim/python-client) repo. Let me know if I need to change anything.

**Comment by mhinz** [comment]
How did you install Neovim? Did you compile from source as root by any chance?

In any way, `/usr/share` is certainly the wrong directory. What's the output of `nvim --version | grep fall-back`?

**Comment by DJMcMayhem** [comment]
I installed it through `apt-get`. I recently (as in, a couple of days ago) did `sudo apt-get upgrade nvim`

Here is the output from that command:

    nvim --version | grep fall-back
    fall-back for $VIM: "/usr/share/nvim"

**Comment by mhinz** [comment]
What's the output of `:echo $MYVIMRC`?

**Comment by tweekmonster** [comment]
This should be fixed in #5050

**Comment by DJMcMayhem** [comment]
Ah, that would probably be it. I don't have a nvimrc, since I'm developing for neovim, but do most of my writing/editing in regular vim.

**Comment by tweekmonster** [comment]
@DJMcMayhem Yeah, you should be able to create a blank `$XDG_CONFIG_HOME/nvim/init.vim` script to make the problem go away.  Or use `nvim -u testrc.vim` (I think).

**Comment by DJMcMayhem** [comment]
@tweekmonster I added an nvimrc to `~/.config/nvim/init.vim`, and that does fix the problem. However, I don't feel like closing this issue just yet, since I don't think there should have to be an nvimrc for the rplugin file to be placed in a folder with sufficient permissions. Maybe I'll look into this myself and see if I can fix it. 

BTW, on an unrelated note, I recognize you from the vim stack exchange site!

**Comment by jamessan** [comment]
> However, I don't feel like closing this issue just yet, since I don't think there should have to be an nvimrc for the rplugin file to be placed in a folder with sufficient permissions.

Right, that's what #5050 is going to address when it's merged.

**Comment by tweekmonster** [comment]
> However, I don't feel like closing this issue just yet, since I don't think there should have to be an nvimrc for the rplugin file to be placed in a folder with sufficient permissions.

What @jamessan said.  Sorry, I should've stated that #5050 _will_ fix this issue.

> BTW, on an unrelated note, I recognize you from the vim stack exchange site!

Hi! 😊
