### ISSUE TITLE
:Tutor : d$ leaves a character behind

### ISSUE THREAD

**Issue by diravan** [neovim/neovim#5153]
- `nvim --version`: NVIM 0.1.5-dev
- Vim (version: ) behaves differently? 7.4 included patches: 1-1689, Yes
- Operating system/version: Ubuntu 16.04.1.LTS
- Terminal name/version: GNOME Terminal 3.18.3
- `$TERM`: xterm-256color
### Actual behaviour

Inside the tutor and, apparently, only there d$ do not delete the entire line but it leaves behind the last character on the line. For example 

Hello -> o
### Expected behaviour

The complete line should be deleted
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Tutor
d$ on any line
```

**Comment by diravan** [comment]
I have just realized that c$ presents the wrong same behaviour, again only inside the tutor.

**Comment by justinmk** [comment]
covered by https://github.com/neovim/neovim/issues/6389
