### ISSUE TITLE
Make `nvim` open a new buffer in the current session if in a terminal buffer.

### ISSUE THREAD

**Issue by ticki** [neovim/neovim#5155]
I imagine that this could be achieved through an environment variable ($NVIM_IN_TERMINAL_BUFFER) telling if the session is currently in a terminal buffer. This would be set when the child process is spawned. `nvim`, when executed, will then check if this is set, and if so, it will execute a escape code and then exit. This escape code tells the `:te` buffer to open the file in that session.

This would make a lot of things easier.

**Comment by ZyX-I** [comment]
That was already discussed somewhere. Cannot find exact issue though.

**Comment by justinmk** [comment]
Thanks for the suggestion, it is definitely a feature many want, and I would suggest enabling it by default somehow. See https://github.com/neovim/neovim/issues/4351 and https://github.com/neovim/neovim/issues/1750 , merging this with those.

**Comment by tsani** [comment]
@ticki it's possible to achieve this using the `nvr` program, with a shell script like this:

```
test -n "$NVIM_LISTEN_ADDRESS" && which nvr > /dev/null && exec nvr --remote $@
```

I personally have a script similar to this, that when failing to find a controlling neovim instance will simply spawn a new one. That way I can use the same command both inside and outside of neovim to edit files.

**Comment by hhsnopek** [comment]
@tsani link to your script? I'd love to use that 😁

**Comment by tsani** [comment]
@hhsnopek https://github.com/tsani/dotfiles/blob/master/nvim/bin/e
