### ISSUE TITLE
How can I have alt-1 work in ITerm2 in OS X?

### ISSUE THREAD

**Issue by seanDot7** [neovim/neovim#5162]
I map `<M-1>` to 1gt to switch to tab1, but it does not work.

**Comment by mhinz** [comment]
`nnoremap <a-1> 1gt` should work just fine.

**Comment by seanDot7** [comment]
Sorry, I just tried but it failed.

**Comment by mhinz** [comment]
I just edited my above post, please read it again.

**Comment by seanDot7** [comment]
Thank you so much!!!! It works.

**Comment by mhinz** [comment]
You're welcome!
