### ISSUE TITLE
All plugins does not work when cd to certain directory except the ~?

### ISSUE THREAD

**Issue by seanDot7** [neovim/neovim#5163]
nvim --version:
Vim (version: ) behaves differently?
Operating system/version: OS X EI Captain 10.11.5
Terminal name/version: ITerm2

Actual behaviour
When I cd to my project directory and run nvim, all plugins does not work, e.g. my solarized syntax highlight is missing. But when I cd to ~(my home directory), all plugins work.
Expected behaviour
I can use plugins as vim no matter what my current directory is.

**Comment by justinmk** [comment]
The [issue template](https://github.com/neovim/neovim/blob/master/ISSUE_TEMPLATE.md) asks for information. Please provide the information.

**Comment by seanDot7** [comment]
I have updated my issue.

**Comment by nhooyr** [comment]
What is `$XDG_CONFIG_HOME` set to?

**Comment by seanDot7** [comment]
Sorry, I set `$XDG_CONFIG_HOME ` to `~/.nvim`, but I put all my configuration files to `~/.config/nvim`. Now the problem has been solved.

**Comment by nhooyr** [comment]
Great! Go ahead and close the issue.
