### ISSUE TITLE
Unable to jobstart pyfile 

### ISSUE THREAD

**Issue by rohanpai** [neovim/neovim#5165]
NVIM 0.1.5-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160615-9717-1i98lg1/build/config -I/tmp/neovim-20160615-9717-1i98lg1/src -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160615-9717-1i98lg1/build/src/nvim/auto -I/tmp/neovim-20160615-9717-1i98lg1/build/include
Compiled by rohanpai@Rohans-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

### Actual behaviour
in my vim plugin 

```
            let job2 = jobstart(['pyfile '. s:path  .';'], extend({'shell': 'shell 2'}, s:callbacks))
```

```"app.go" 119L, 4122C
Error detected while processing function LookupSymbol:
line   18:
E902: "pyfile /Users/rohanpai/.config/nvim/plugged/my-plugin/plugin/plug.py;" is not an executable```
### Expected behaviour

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by mhinz** [comment]
`jobstart(['pyfile', s:path], ...)`

**Comment by justinmk** [comment]
pyfile is a vimscript command. Jobstart is for execution of programs on your $PATH.

**Comment by rohanpai** [comment]
@justinmk  thanks, is it possible to execute a vimscript command in a background thread for neovim?

**Comment by bfredl** [comment]
Python code specifically can be run async with `:py vim.async_call(python_function)` though you can't use pyfile, you need to process reasonable chunks of the buffer yourself. (Though it could still block python code, spawn a python thread if you do long running cpu work, async_call is thread-safe)
