### ISSUE TITLE
Please support disabling the "stop at start position" behavior of Ctrl-W and Ctrl-U

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#5167]
- `nvim --version`:
```
NVIM v0.1.5-642-g2dd9f33
Build type: None
Compilation: /usr/lib/ccache/cc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/neovim/build/config -I/tmp/neovim/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by josh@x

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: 7.4) behaves differently? No.
- Operating system/version: Debian GNU/Linux, latest unstable
- Terminal name/version: gnome-terminal 3.20.2
- `$TERM`: xterm-256color

### Actual behaviour

As documented in `:help i_backspacing`, even with `backspace=start`, "CTRL-W and CTRL-U stop once at the start position".

### Expected behaviour

With an appropriate new option set (for instance, `:set backspace+=nostop`), Ctrl-W would always delete a word backward by the definition of a word, ignoring where the last insert operation started.

### Steps to reproduce using `nvim -u NORC`

- `nvim -u NORC`
` `:set backspace=indent,eol,start`
- Hit `i` for insert mode.
- Type `abc`.
- Hit Escape.
- Hit 'a' to append.
- Type `def`.
- Press Ctrl-W.  Notice that it deletes `def` but not `abc`.

**Comment by ZyX-I** [comment]
I have simply mapped `<C-w>` to `<C-\><C-o>"_db` and it works fine. New option is not needed.

**Comment by joshtriplett** [comment]
This seems in the same spirit as the `backspace` option itself; it'd be possible to get the same effect as `:set backspace=eol` by rebinding backspace, for instance, but it's nicer to have the option available for the common change of behavior.

**Comment by justinmk** [comment]
@joshtriplett The problem with adding unnecessary options is it makes the documentation much more difficult to comprehend for 100% of users. That is the UX cost, not mentioning the extra codepath and test coverage needed.

**Comment by frangio** [comment]
The mapping proposed by @ZyX-I is not a reasonable alternative to me, because unlike `<C-w>` it affects undo history.

**Comment by justinmk** [comment]
@frangio Does `:undojoin` help?

**Comment by frangio** [comment]
No. I tried mapping `<C-w>` to `<C-\><C-o>:undojoin | normal "_db` but the undo history is the same.
I also tried using `:undojoin` in combination with `:startinsert` in case it was an issue with `<C-o>`. I can't think of any other way to use `:undojoin` that might help.

I personally think Vim should have a way to execute commands during insert mode without affecting undo history.
