### ISSUE TITLE
man.vim: last file completion option is automatically selected

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5173]
- `nvim --version`: NVIM v0.1.5-703-gdc1b799
- Vim (version: 7.4) behaves differently? No
- Operating system/version: OSX El Capitan 10.11.6
- Terminal name/version: Iterm2 3.0.5
- `$TERM`: xterm-256-colour
### Actual behaviour

With `wildmode=list,full`, `:Man ./<TAB>` completes the last file automatically.

See nhooyr/neoman.vim#17 and [runtime/autoload/man.vim](https://github.com/neovim/neovim/blob/4dc4efc36fad058298d69d4b2533beded3293c33/runtime/autoload/man.vim#L260)
### Expected behaviour

No completion done at all, only candidates listed.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildmode=list,full
:Man ./<TAB>
```

**Comment by justinmk** [comment]
Reporting to vim/vim would be get more attention on this.

**Comment by nhooyr** [comment]
Opened at vim/vim#969

**Comment by nhooyr** [comment]
Remember to remove https://github.com/neovim/neovim/blob/40c76741c187f5bf35101e65252226030d5b72e5/runtime/autoload/man.vim#L270 once this is resolved.

**Comment by nhooyr** [comment]
Shall we just close this since its a vim bug? @justinmk
