### ISSUE TITLE
Some colors are not present

### ISSUE THREAD

**Issue by haifengkao** [neovim/neovim#5178]
highlight has no effect for certain colors
neovim sends gray color to nyaovim when the color has been set to `seagreen3`.
Some colors, such as `seagreen` (not `seagreen3`), work without any problems.
Please refer to the discussion https://github.com/rhysd/NyaoVim/issues/71#issuecomment-238017847
- `VIM v0.1.5-684-gbfa8378`:
- Vim (version: MacVim snapshot 74) behaves differently? Yes
- Operating system/version: OSX 10.11
- Terminal name/version: iTerm
- `$TERM`: xterm-256color
### Actual behaviour

![act](https://cloud.githubusercontent.com/assets/4080524/17457576/7191e86a-5c2e-11e6-9343-747eec0278eb.jpg)
### Expected behaviour

![exp](https://cloud.githubusercontent.com/assets/4080524/17457575/6f748dbc-5c2e-11e6-9e7f-168b91d5850e.jpg)
### Steps to reproduce using `nvim -u NORC`
- enable true color in nvim
- execute nyaovim
- `:hi Comment guifg=seagreen3`

**Comment by justinmk** [comment]
Probably missing in the color table.

**Comment by haifengkao** [comment]
@justinmk seagreen3 is in the [color table]( https://github.com/neovim/neovim/blob/2e2b5759cf806b5ca1d4e94316d40acb17878ae2/runtime/rgb.txt ), but I cannot find where neovim references it.

**Comment by romgrk** [comment]
syntax.c @ 7520
Not referenced

**Comment by rhysd** [comment]
@haifengkao Thank you reporting this.

This looks to happen only when remote UI API used.  Non-highlighted colors (normal fg and normal bg) seem to be sent on `highlight_set` event via RPC.

**Comment by rhysd** [comment]
I found color table in syntax.c.

https://github.com/neovim/neovim/blob/1f7304b84681f3afae55d762e28f1ec6efe375a6/src/nvim/syntax.c#L7525

`seagreen3` (and other many colors) is not included in it.

**Comment by justinmk** [comment]
> :let rgb_file should be implemented.

@haifengkao  Where is that used in Vim (not Neovim)? I see one mention in the help for FVWM.

**Comment by haifengkao** [comment]
It is also in Vim Book :)
![2016-12-08 3 54 35](https://cloud.githubusercontent.com/assets/4080524/20984318/a66b8316-bcfa-11e6-93c5-fa3568cd8ae5.jpg)

and [vim-seattle](https://github.com/mbbill/vim-seattle). 

```vim

function! s:read_rgb_txt()
    let rgb_file = $VIMRUNTIME."/rgb.txt"
    let rgb_lines = readfile(rgb_file)
    let ret = {}
    " each line is like r g b name
    for line in rgb_lines
        let s = split(line)
        let key = tolower(s[3])
        let ret[key] = printf("%02x", str2nr(s[0])).
                    \printf("%02x", str2nr(s[1])).
                    \printf("%02x", str2nr(s[2]))
    endfor
    return ret
endfunction
```
It's a new project, maybe you can ask the author( @mbbill ) about its usage. He is also the author of the popular `undotree` plugin. He is definitely more knowledgeable than I am.

**Comment by chrisbra** [comment]
rgb_file is not implemented in vim. However Vim will read $VIMRUNTIME/rgb.txt when needed (gui_get_color_cmn() in term.c since 7.4.1792 or so)
