### ISSUE TITLE
neovim fails to install with homebrew

### ISSUE THREAD

**Issue by jamesalbert** [neovim/neovim#5179]
- Vim version: 7.4
- Operating system/version: OSX El Capitan 10.11.15
- Terminal name/version: default mac terminal?
- `$TERM`: xterm-256color

### Actual behaviour

[log](http://pastebin.com/UaFkK1rN)

This is the first and only command I did to install (unsuccessfully) neovim. Followed the install [docs](https://github.com/neovim/homebrew-neovim/blob/master/README.md).

**Comment by justinmk** [comment]
see https://github.com/neovim/homebrew-neovim/issues/166
