### ISSUE TITLE
Arrow keys do not work in Bash for Windows

### ISSUE THREAD

**Issue by gglanzani** [neovim/neovim#5191]
- `nvim --version`: 0.1.5-dev
- Vim (version: ) behaves differently? Yes
- Operating system/version: Bash for Windows
- Terminal name/version: Fish
- `$TERM`: xterm

### Actual behaviour
Up arrow inserts 'A'
### Expected behaviour
Move up
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
< press up arrow>
```

On the internet I've found that this is fixed by setting `:set term=builtin_ansi` that obviously doesn't work with neovim. Sorry if this ends up being trivial, I've googled quite a bit before opening.

**Comment by justinmk** [comment]
Try TERM=xterm-256color

**Comment by justinmk** [comment]
Though I don't see why regular xterm should not also have all the features of its colorful counterpart...

**Comment by gglanzani** [comment]
@justinmk You mean `export TERM=xterm-256color` in the terminal? If that's what you mean, then it doesn't work :(

**Comment by justinmk** [comment]
It's misconfigured terminfo then. The reason `set term=builtin_ansi` works in Vim is because that ignores terminfo. We don't have that.

**Comment by gglanzani** [comment]
@justinmk Could you be more specific? Misconfigured terminfo at the Bash layer, the terminal emulator layer (i.e. cmder or the default bash terminal emulator from Microsoft). What I mean is: is there something I could do to fix it?

**Comment by justinmk** [comment]
terminfo is a file that configures the terminal. What that means in the context of win10's linux system, I am not sure.

We could try to enhance our built-in handling.

**Comment by gglanzani** [comment]
I'm using [wsl-terminal](https://github.com/goreliu/wsl-terminal/) now (bonus: 256 colors!) and while it reports itself like the default one, there the arrows work.

**Comment by Geofff** [comment]
Switching terminal doesn't really fix the issue, this issue still exists when using cmd.exe or Cmder, and most likely others as well. If this is an issue with terminfo, can the local terminfo be changed to fit? Is there a way to rebind arrow keys directly? In vim you have something like `set t_ku=^[OA`, is that possible in neovim?

**Comment by mqudsi** [comment]
Can we please re-open this issue? It has not been fixed, using a different terminal emulator is not an "issue closed" solution.

**Comment by gglanzani** [comment]
Yeah it's a bummer. 

New Windows insiders releases work a bit better, but still not quite yet (i.e. the arrow keys sometimes work, sometimes they output [A or something)

**Comment by justinmk** [comment]
> In vim you have something like `set t_ku=^[OA`, is that possible in neovim?

https://github.com/neovim/neovim/issues/2204 may help, so something like this could be done:

    set <Right>=^[...
    set <Left>=^[...

Other than that, we're waiting on WSL.

**Comment by gglanzani** [comment]
@justinmk 

Here's the thing:

I've put this in my `init.vim`

```viml
set <Right>=^[C
set <Left>=^[D
set <Up>=^[A
set <Down>=^[B
```

When opening nvim, the first time a press {R,L,U,D}, then the cursor moves accordingly.

The second time, however, it doesn't. 

For example, if I press UUDD:

U (cursor moves up), U (cursor doesn't do anything), D (cursor moves down) D (cursor doesn't do anything)

I have no idea what be could causing this behavior, but it sure seems very strange (also: in Vim they just work).

**Comment by justinmk** [comment]
`set <Right>=...` isn't going to work until https://github.com/neovim/neovim/issues/2204 is fixed.

**Comment by gglanzani** [comment]
@justinmk Ah, thanks. Anyway, I've just tried this:

```viml
set t_ku=^[OA
set t_kd=^[OB
set t_kr=^[OC
set t_kl=^[OD
```

And it works slightly better, but I still do get misses sometimes

**Comment by mqudsi** [comment]
I've been using this mapping and it works for me:

```
:map ^[[D h
:map ^[[C l
:map ^[[A k
:map ^[[B j

```

**Comment by justinmk** [comment]
@mqudsi oh, yes, that's perfectly fine as well.

**Comment by mqudsi** [comment]
Actually, I'm mistaken with my mapping in the previous comment. I had this working on my last laptop, but I don't know what happened to it. You need to remap based off the mode, if I recall correctly, and exit insert mode before pressing those keys. I'll try to re-experiment and post back.

**Comment by mqudsi** [comment]
I think this is closer to what I had:

```
  :map ^[[D h
  :map ^[[C l
  :map ^[[A k
  :map ^[[B j
 
  :map! ^[[D <Left>
  :map! ^[[C <Right>
  :map! ^[[A <Up>
  :map! ^[[B <Down>
```

**Comment by justinmk** [comment]
This should work as well:

```
  :map ^[[D <Left>
  :map ^[[C <Right>
  :map ^[[A <Up>
  :map ^[[B <Down>

  :map! ^[[D <Left>
  :map! ^[[C <Right>
  :map! ^[[A <Up>
  :map! ^[[B <Down>
```

**Comment by gglanzani** [comment]
@justinmk @mqudsi It still fails sometimes (both within and out of tmux), i.e. it works in general, but every 4-5 presses it misses.

**Comment by justinmk** [comment]
@gglanzani What's the output of this command:

    :set ttimeout? ttimeoutlen?

Could you also try the [mappings](https://github.com/neovim/neovim/issues/5191#issuecomment-265512798) with `nvim -u NORC` ?

**Comment by gglanzani** [comment]
```
nottimeout
timeoutlen=-1
```

`nvim -u NORC` gives me the same results.

But, again, this is the case for the bash.exe UI. With wsl-terminal the problems are gone.

**Comment by mqudsi** [comment]
@gglanzani I can't say it doesn't fail, but it certainly doesn't fail every four or five keypresses for me. In all events, I would argue that is a different bug and should have a different issue opened. One is a simple key map issue, the other would be a much more complicated potential race condition somewhere.

**Comment by gglanzani** [comment]
This is now fixed in the latest Insider Preview (Slow and Fast ring)

**Comment by dukebarman** [comment]
I have a same problem with arrows but in conemu + wsl (bash on windows). In only wsl it works.

**Comment by justinmk** [comment]
@dukebarman Try 0.2.1, read `:help $TERM` (0.2.1).
