### ISSUE TITLE
Package directory not added to runtimepath

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#5193]
- `nvim --version`: NVIM v0.1.5-729-gabb0928
- Vim 7.4.2181 behaves differently? Yes.
- Operating system/version: Linux Ubuntu 16.04
- Terminal name/version: Tmux 2.1 on gnome-terminal 3.18.3
- `$TERM`: screen-256color

### Actual behaviour
The command `SayHello` does not exist.

### Expected behaviour
The command `SayHello` exists and works.

### Steps to reproduce using `nvim -u NORC`

First, create a plugin containing the command `SayHello`:
```
mkdir -p ~/.local/share/nvim/site/pack/foo/start/MyPlugin/plugin
echo "command SayHello echo 'Hello'" > ~/.local/share/nvim/site/pack/foo/start/MyPlugin/plugin/myplugin.vim
```
Then, test it:
```
nvim -u NORC
:SayHello
```

**Comment by justinmk** [comment]
Did you try packload ?

**Comment by jalvesaq** [comment]
The command `:packloadall` makes no difference, and Vim does not need it.

**Comment by jamessan** [comment]
Is `~/.local/share/nvim/site` in your `'runtimepath'`?

**Comment by jalvesaq** [comment]
Yes, it is.

**Comment by jalvesaq** [comment]
The command `:packadd vimball` also does not work. But, putting this in the `init.vim` solves the problem:
```
set packpath=/usr/local/share/nvim/runtime,~/.local/share/nvim/site
```
The option 'packpath' is not empty in Vim. This is the reason for the difference in behavior between Vim and Neovim.

**Comment by jamessan** [comment]
I'll take a look at this.  `'packpath'` is supposed to be inheriting the value of `'runtimepath'`, which is why I asked if the directory was present there.

**Comment by jalvesaq** [comment]
Thanks!
