### ISSUE TITLE
Documentation: ~/.local/share/nvim/site/pack or ~/.config/nvim/pack ?

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#5196]
- `nvim --version`: v0.1.5-731-g006f9c0

This is not a bug report; just a quibble.

The documentation refers to `~/.local/share/nvim/site/pack` as the proper place to put Vim packages. In my opinion, the `~/.local/share/nvim` directory should continue to be used for storing hidden things, like shada and swap subdirectories which are created by nvim itself. A plugin similarly to vim-plug which would automatically add, remove and update plugins from github and other sources could save the plugins in `~/.local/share/nvim/site/pack/plugged/start`. However, for plugins added manually by users, I think `~/.config/nvim/pack/foo/start` is more appropriate because users should be guided to put all their configuration files, including plugins, into the same directory: `~/.config/nvim`.

Please, feel free to close this issue if you disagree.

**Comment by ZyX-I** [comment]
$XDG_CONFIG_HOME is for user *configuration*. Plugins are *not* configuration, they are third-party blobs normally not modified by user and thus are to be placed to $XDG_DATA_HOME. $XDG_DATA_HOME is not for “hidden” things, it is for “data files” that are not edited by user.

**Comment by jalvesaq** [comment]
Thanks for clarifying! It makes sense.
