### ISSUE TITLE
True color not showing in 0.1.5-dev

### ISSUE THREAD

**Issue by mjswensen** [neovim/neovim#5208]
- `nvim --version`: **0.1.4 & 0.1.5-dev**
- Vim behaves differently? **N/A**
- Operating system/version: **OS X & Ubuntu 14.04 Server**
- Terminal name/version: **tested with iTerm2 (Build 3.0.7) and Hyperterm (Build 0.7.1.36)**
- `$TERM`: **`xterm-256color` for both environments.**

On Mac OS X, I installed Neovim using `brew`. On a headless Ubuntu Server VM, I installed it via `ppa:neovim-ppa/unstable`. They use the same `init.vim`, which set `let $NVIM_TUI_ENABLE_TRUE_COLOR=1`.

### Actual behaviour

True color is not enabled on the Ubuntu host:

![notruecolor](https://cloud.githubusercontent.com/assets/1591879/17570664/9411138c-5f0a-11e6-97ce-f5f633f134c1.png)

### Expected behaviour

Using the same `init.vim`, and with the same value for `$TERM`, true color shows as expected on 0.1.4 on OS X:

![truecolor](https://cloud.githubusercontent.com/assets/1591879/17570669/99a503d0-5f0a-11e6-9c25-f896e3f0f9b9.png)

### Steps to reproduce using `nvim -u NORC`

N/A

**Comment by KillTheMule** [comment]
Did you see https://github.com/neovim/neovim/wiki/Following-HEAD#20160511?

**Comment by mjswensen** [comment]
@KillTheMule That was the ticket. Thank you kindly!
