### ISSUE TITLE
Segmentation fault when error pops during use of expression (=) register

### ISSUE THREAD

**Issue by romgrk** [neovim/neovim#5209]
- `nvim --version`: NVIM v0.1.5-329-g748898b
- Vim (version: ) behaves differently?
- Operating system/version: Arch
- Terminal name/version: Terminix
- `$TERM`: xterm-256color
### Steps
- `"=string(jobs)<CR>p`

where `jobs` is likely undefined
where `p` is mapped to `<Plug>(miniyank-autoput)` from the nvim-miniyank plugin, which translates to the following function:

``` viml
" TODO: put autocommand plz
function! miniyank#startput(cmd,defer) abort
    let s:pastelist = miniyank#read()
    let s:cmd = a:cmd
    let s:visual = index(["v","V","\026"], mode()) >= 0
    let s:count = string(v:count1)
    if a:defer
        let first = [getreg(v:register,0,1), getregtype(v:register), v:register] 
        " SEGFAULT HERE
        if !miniyank#fix_clip(s:pastelist, first)
            call miniyank#add_item(s:pastelist, first)
        endif
    end
    return ":\<c-u>call miniyank#do_putnext()\015"
endfunction
```

Backtrace: https://gist.github.com/romgrk/19cf9586d3f4e2de23fc1bf67417d4a6
Segfault on `list_idx_of_item()`

**Comment by justinmk** [comment]
@ZyX-I did a lot of work related to the expression register, which entailed lots of new test coverage.

Please comment if this issue is still reproducible in Nvim 0.3.0+
