### ISSUE TITLE
Different env when using  gnome-terminal -x nvim 

### ISSUE THREAD

**Issue by MaikoID** [neovim/neovim#5216]
- `nvim --version`:

NVIM 0.1.5-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/build/config -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/src -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-bJ5Lu7/neovim-0.1.4ubuntu1+git201608091410+2698+20~ubuntu14.04.1/build/include
Compiled by buildd@lcy01-29

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently?
 There is no :terminal command in VIM

- Operating system/version:
Ubuntu 14.04 x64

- Terminal name/version:
gnome-terminal with ZSH

- `$TERM`:
xterm

### Actual behaviour
If I start NVIM using gnome-terminal -x as: `gnome-terminal -x nvim` option I get a strange behaviour where I need no enter my SSH password for each remote git command.

### Expected behaviour
No behave differently from the two steps start, open gnome-terminal and start NVIM with nvim;
If I manually start gnome-terminal and start nvim I'm not asked for my SSH password if I use :Gfetch, from fugitive plugin, or if I open the NVIM terminal with :terminal  and do a git fetch;

### Steps to reproduce using `nvim -u NORC`
the same as described above

```
nvim -u NORC

```

**Comment by MaikoID** [comment]
I just discover the neovim-qt and my life is complete now, using neovim-qt the :terminal works as expected

**Comment by justinmk** [comment]
We don't have control over what environment we inherit. That's more of a desktop/distro/shell thing.

Glad you like neovim-qt 😂  @equalsraf has done great work there.
