### ISSUE TITLE
[man] q Keybindung does not work when opening other manpages with <c-]>

### ISSUE THREAD

**Issue by rumpelsepp** [neovim/neovim#5219]
- `nvim --version`: 
```
NVIM v0.1.5-739-gdb37510
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/makepkg/neovim-git/src/neovim-git/build/config -I/tmp/makepkg/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/makepkg/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/makepkg/neovim-git/src/neovim-git/build/include
Compiled by stefan@kronos

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Operating system/version: Arch Linux, up to date
- Terminal name/version: termite
- `$TERM`: xterm-256color

When using the recently introduced man plugin, one can close nvim with the keybinding <kbd>q</kbd>. But, when other manpages have been opened using <kbd>ctrl</kbd> + <kbd>]</kbd> the <kbd>q</kbd> keybinding does not work any more. Then I have to close nvim with the `:q` command.

I would expect that <kbd>q</kbd> works under all circumstances, when browsing manpages.

**Comment by nhooyr** [comment]
Can you add reproduction steps with `nvim -u NORC`?

**Comment by rumpelsepp** [comment]
I can reproduce it with e.g.
```
nvim -u NORC -c 'set ft=man' -c 'Man crontab'
```

I can close nvim with <kbd>q</kbd>. But when I have opened another page using <kbd>ctrl</kbd> + <kbd>]</kbd> then I get a `E444: Cannot close last window` error.

**Comment by nhooyr** [comment]
This was intended. If you open a manpage when you are already in neovim, the q mapping becomes `<c-w>c`. If you open neovim as `$MANPAGER`, it is `:q`. See nhooyr/neoman#16 and https://github.com/neovim/neovim/pull/4449#discussion_r56021575

**Comment by nhooyr** [comment]
You can get your desired behaviour by

```zsh
export MANPAGER='nvim -c "au filetype man nnoremap <buffer> q :q<CR>" -c "set ft=man" -'
```

If opened from as `$MANPAGER`, neovim will always use `:q` as the close mapping on manpages. You could also just set

```vim
au filetype man nnoremap <buffer> q :q<CR>
```

In your init.vim so it is always mapped as `:q<CR>`.

**Comment by rumpelsepp** [comment]
Thank you for your answer!

I haven't configured `$MANPAGER` directly due to some weird problem with one of my plugins. Thus, I have created a wrapper script for invoking nvim as the manpager. But this way, the mapping is not created, as I don't invoke nvim the desired way using `$MANPAGER`. Thanks for the hint with autocmds, it fixes my problem!
