### ISSUE TITLE
'gui_running' is not set to 1 after vim_ui_attach called

### ISSUE THREAD

**Issue by rhysd** [neovim/neovim#5220]
- `nvim --version`:

```
NVIM 0.1.5-dev
Build type: Release
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160806-20909-wszeyk/build/config -I/tmp/neovim-20160806-20909-wszeyk/src -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/tmp/neovim-20160806-20909-wszeyk/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160806-20909-wszeyk/build/src/nvim/auto -I/tmp/neovim-20160806-20909-wszeyk/build/include
Compiled by rhayasd@Corgi.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/local/Cellar/neovim/HEAD-4dc4efc/share/nvim"

```

- Vim (version: ) behaves differently?

N/A in Vim

- Operating system/version: OS X 10.11
- Terminal name/version: iTerm2 2.14
- `$TERM`: `screen`

### Actual behaviour

`has('gui_running') == 0`

### Expected behaviour

`has('gui_running') == 1`

### Steps to reproduce using `nvim -u NORC`

Write below code as `test.js` and execute it with `$ node test.js`.  I'm using Node.js v6.3.1.

```javascript
const attach = require('neovim-client');
const cp = require('child_process');

const proc = cp.spawn('nvim', ['-u', 'NONE', '-N', '--embed']);
attach(proc.stdin, proc.stdout, (_, nvim) => {
    nvim.uiAttach(80, 24, true, () => {
        nvim.eval('has("gui_running")', (_, output) => {
            console.log('OUTPUT:', output);
        });
    });
});
```

It says `OUTPUT: 0`.

AFAIK, it output `1` at early of this year.

**Comment by equalsraf** [comment]
I believe this was changed intentionally earlier this year in https://github.com/neovim/neovim/pull/4155 and gui_running is never 1. What weer you using the `gui_running` check for? There are alternatives:

- for plugins it really should be '0' for compatibility with Vim
- color schemes can be fixed to avoid using this check (see #4155)
- GUIs can provide you with other ways to do this e.g. ginit.vim
-

**Comment by rhysd** [comment]
Thank you for your answer.  I wrote some configurations for GUI in `init.vim`.  I didn't know `ginit.vim` and will try it.

**Comment by justinmk** [comment]
ginit.vim is GUI specific. Not part of the core.

**Comment by rhysd** [comment]
yeah, it's not a problem.  I was queried related to NyaoVim.

**Comment by justinmk** [comment]
`has('gui_running')` is now supported in Nvim 0.9 https://github.com/neovim/neovim/pull/22382
