### ISSUE TITLE
Using alt in insert mode regression

### ISSUE THREAD

**Issue by peteruhnak** [neovim/neovim#5222]
Vim supported using `<alt>+{h|j|k|l}` to exit insert mode and move in a particular direction ( http://vim.wikia.com/wiki/Avoid_the_escape_key#Use_Alt.2FMeta_In_a_Terminal ).

Is this something that has been dropped, or is it just a missing feature?

**Comment by justinmk** [comment]
Alt is now alt. You can map `<A-f>`. Alt as ESC is not supported.
