### ISSUE TITLE
notmuch vim - ruby based plugin not working

### ISSUE THREAD

**Issue by sencer** [neovim/neovim#5223]
- `nvim --version`: 0.1.5-dev
- Vim (version: 7.4 1-1795) behaves differently? Yes
- Operating system/version: Ubuntu Gnome 3.16
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour

`:NotMuch` command loaded from `notmuch.vim` distributed with the software gives this error:

> Error detected while processing function <SNR>25_NotMuch[499]..<SNR>25_folders:
> line    2:
> W, [2016-08-14T10:40:08.480557 #12989]  WARN -- Neovim::Host: got unexpected error #<NoMethodError: undefined method `query' for nil:NilClass>
> Error detected while processing function <SNR>25_NotMuch[499]..<SNR>25_folders[2]..provider#ruby#Call:
> line   17:
> undefined method `query' for nil:NilClass

### Expected behaviour

It should load the emails included in the notmuch database. Normal vim does this. 

The ruby code opens VIM::Buffer class, and appends `query` method to it, as well as others. For some reason I believe there might be a problem with modifying native classes in the ruby host.

`:CheckHealth` gives:

> Checking: Ruby
>   Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
>   Host Executable: /usr/local/bin/neovim-ruby-host
>   Host Version: 0.2.4

### Steps to reproduce using `nvim -u NORC`

If not much source is at `/opt/notmuch`:

```
nvim -u NORC

:source /opt/notmuch/vim/notmuch.vim
:NotMuch

```

It requires `set nocp` in regular vim before sourcing.

**Comment by fwalch** [comment]
Ping @alexgenco

**Comment by alexgenco** [comment]
I'll take a look

**Comment by alexgenco** [comment]
The ruby provider supports defining methods on core classes, e.g. this works:

```
:ruby class VIM::Buffer; def foo; append(0, "hi"); end; end
:ruby $curbuf.foo
```

The problem is we're calling `query` on `nil`. Which means there's probably a race condition where Ruby is being executed but the `$curbuf` global isn't defined yet.

I'm having a really hard time getting notmuch working on my macbook pro. @sencer would you mind reproducing this with the environment variables `NVIM_RUBY_LOG_FILE=/tmp/nvim.log` and `NVIM_RUBY_LOG_LEVEL=debug` and attaching the  `/tmp/nvim.log` file to a comment here (it will be a lot of text). That should at least narrow down the source of the exception.

**Comment by sencer** [comment]
Here it is:
[nvim.txt](https://github.com/neovim/neovim/files/417206/nvim.txt)

**Comment by alexgenco** [comment]
Ok sorry for the delay on this. Looks like the problem was that the Ruby provider didn't persist instance variables between requests. I've pushed a [fix](https://github.com/alexgenco/neovim-ruby/commit/d7ad8e88ce93b1295b7f272a9bf91f3c006f26de), @sencer can you try building `neovim-ruby` from master via `rake install` and see if it resolves your problem?

**Comment by sencer** [comment]
It is fixed. Thanks!

**Comment by alexgenco** [comment]
[v0.2.5](https://rubygems.org/gems/neovim/versions/0.2.5) pushed to rubygems, cheers

**Comment by mulianov** [comment]
v0.3.0
Error detected while processing function <SNR>23_NotMuch[493]..provider#ruby#Call:     
line   17:                                                                             
Channel was closed by the client                                                       
Error detected while processing function <SNR>23_NotMuch[497]..<SNR>23_folders[1]..<SNR
>23_new_buffer[6]..provider#ruby#Call:                                                 
line   17:                                                                             
Invalid channel "2"                                                                    
Error detected while processing function <SNR>23_NotMuch[497]..<SNR>23_folders[2]..prov
ider#ruby#Call:                                                                        
line   17:                                                                             
Invalid channel "2"

**Comment by alexgenco** [comment]
@mulianov do you get the same error with v0.2.5? If not I probably pushed a regression.

**Comment by mulianov** [comment]
It's not working for me similarly:

> Error detected while processing function <SNR>23_NotMuch[493]..provider#ruby#Call:
> line   17:
> Channel was closed by the client
> Error detected while processing function <SNR>23_NotMuch[497]..<SNR>23_folders[1]..<SNR>
> 23_new_buffer[6]..provider#ruby#Call:
> line   17:
> Invalid channel "4"
> Error detected while processing function <SNR>23_NotMuch[497]..<SNR>23_folders[2]..provi
> der#ruby#Call:
> line   17:
> Invalid channel "4"
>

**Comment by alexgenco** [comment]
Is there anything in `~/.nvimlog`? Also, could you start up nvim using `NVIM_RUBY_LOG_LEVEL=debug NVIM_RUBY_LOG_FILE=/tmp/nvim.log nvim` and try again? Then attach `/tmp/nvim.log` to this thread?

**Comment by mulianov** [comment]
I am sorry for having bothered you. it was a bug in notmuch ruby bindings.

**Comment by alexgenco** [comment]
No worries, here to help 😄

**Comment by c0nn3r** [comment]
I am having this problem with command-t (even after compiling the c-bindings).

**Comment by justinmk** [comment]
@c0nn3r Are you sure that's not a bug in command-t? Does the same setup work in Vim?

**Comment by c0nn3r** [comment]
@justinmk The same setup works in Vim.

**Comment by alexgenco** [comment]
@c0nn3r I can't reproduce on my macbook pro. What is your OS, vim version, nvim version, and neovim-ruby version (`neovim-ruby-host -V`)?

**Comment by sencer** [comment]
For some reason I deleted all my gems, and reinstalled neovim gem. Now I am receiving the same error as  @mulianov ([https://github.com/neovim/neovim/issues/5223#issuecomment-241804773]).

CheckHealth output is clean, and the log is attached. Can you look at that?

[nvim.ruby.log.txt](https://github.com/neovim/neovim/files/518375/nvim.ruby.log.txt)

**Comment by sencer** [comment]
My bad. Apparently, I also need to install `mail` gem.

**Comment by serussell** [comment]
@mulianov, what was the bug, and how did you resolve it?  I'm having a similar channel issue related to the notmuch plugin from github.com/imain/notmuch-vim.
