### ISSUE TITLE
man with MANPAGER "nvim -c 'set ft=man' -" hangs, while `man $PAGE | nvim -c 'set ft=man' -` doesn't

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#5230]
Hi guys! When I heard nvim now supported neat builtin highlighted and linked manpages (from neoman, I suppose?) I know I needed to try this out. Here goes:

- `nvim --version`: NVIM v0.1.5-771-gdfb6a51
- Operating system/version: Linux 3.16.0-77-generic
- Terminal name/version: rxvt-unicode-256color
- `$TERM`: rxvt-unicode

### Actual behaviour

```bash
$ export MANPAGER="nvim -c 'set ft=man' -"
$ man write
```

Never shows the nvim interface. The process list shows a zombie Python process and the its parent nvim process wainting in `epoll_wait`.

I've updated the Python plugin with the following:

```
pip2 install --upgrade --user neovim ; pip3 install --upgrade --user neovim
```

### Expected behaviour

I expect the behaviour of:

```bash
$ export MANPAGER="nvim -c 'set ft=man' -"
$ man write
```

And

```bash
man write | nvim -c 'set ft=man' -
```

To be the same.

However, the former hangs, while the latter doesn't.

I strace'd both the hanging and non-hanging variants and believe to have identified a crucial difference:

Good (`pid(man) = 31976 (not seen here)`, `pid(nvim) = 31977`, `pid(python2) = 32005`):

```
$ cat nvim.good.strace | grep -nP '^(31975|31977|32005).*(CHLD|exited.with)' | column -ts ':' 
...
333     31977 rt_sigaction(SIGCHLD, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7fc7493ffcb0},  <unfinished ...>
15087   31977 rt_sigaction(SIGCHLD, {0x655a80, ~[RTMIN RT_1], SA_RESTORER, 0x7f6c9f558330}, NULL, 8) = 0
15090   31977 clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f6c9fb67a90) = 32005
15291   32005 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
16306   32005 +++ exited with 0 +++
...
```

Bad:  (`pid(man) = 21502`, `pid(nvim) = 21512`, `pid(python2) = 21521`):

```
$ cat nvim.bad.strace | grep -nP '^(21502|21512|21521).*(CHLD|exited.with)' | column -ts ':'
...
13934  21512 rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [CHLD], 8) = 0
13936  21512 rt_sigaction(SIGCHLD, {0x655a80, ~[RTMIN RT_1], SA_RESTORER, 0x7f0149c3e330}, NULL, 8) = 0
13938  21512 rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
13939  21512 clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f014a24da90) = 21521
14139  21521 rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
15143  21521 +++ exited with 0 +++
15157  21502 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=21512, si_uid=287026, si_status=SIGINT, si_utime=46, si_stime=4} ---
...
```

Said another way, in the "good" variant, nvim does not block `CHLD` signals. In the bad variant, it blocks them (before cloning, and doesn't unblock them). Therefore, it cannot receive the SIGCHLD from the python process exiting `*`. It just hangs there in `epoll_wait`.

Perhaps this is a libuv bug. I'm not sure what causes it to be so different.

**NOTE**: The process hierarchies are a bit different in the good/bad variants:

```
GOOD
- 31975 (sh)
  - 31977 (nvim)
    - 32005 (python2, exited)
  - 31976 (man)

BAD
- 21502 (man)
  - 21512 (nvim)
    - 32005 (python2, zombie)
```

It might be that when man spawns nvim, it sets up the signal mask a bit differently, and therefore libuv reacts differently to that. I'm also a bit weirded out that this works fine on OSX.

`*`: Note that this is just getting the version of the Python plugin, this is the invocation: `python2 -c import sys; sys.path.remove(""); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader("neovim") is None))`.

### Steps to reproduce using `nvim -u NORC`

I'm afraid this works perfectly fine. Most likely because it doesn't try to start Python :).

**Comment by nhooyr** [comment]
There was a user on reddit complaining of this bug [here](https://www.reddit.com/r/vim/comments/4xkyah/til_builtin_man_pager_in_vim/d6i8b85).

**Comment by pjrt** [comment]
And here is that guy. Ok, so the issue wasn't in my RC. Good cuz I could not figure out what in my RC could be causing this.

**Comment by aktau** [comment]
So, for the time being, I was running with:

```bash
export MANPAGER=nvim -u NORC '+set background=dark' '+set ft=man' -
```

To avoid the Python stalling issue. This works, it loads the first manpage as I indicated above.

However, going to a linked man-page, such as `mesg(1)`, by going to that symbol and pressing `ctrl-[`, manages to lock up nvim. This time, I seem to have a zombie `uname -s` process.

Funnily enough, I have this in my `.zshrc`:

```bash
# Set manpager to nvim if possible. Highlighted linkable mampages!
if command -v nvim >/dev/null 2>&1 ; then
  # See github https://github.com/neovim/neovim/issues/5230.
  if [[ "$(uname -s)" == "Linux" ]] ; then
    export MANPAGER="nvim -u NORC '+set background=dark' '+set ft=man' -"
  else
    export MANPAGER="nvim '+set ft=man' -"
  fi
fi
```

Perhaps nvim tries to spawn a zsh, which loads .zshrc, which runs `uname`, which... can't exit because ... Hmm, I don't understand things anymore, something very weird is going on.

An `execsnoop` trace:

```
20:30:13.391897    PID   PPID ARGS
20:30:15.002704    746  31482 man write
20:30:15.015840    753    746 preconv -e UTF-8
20:30:15.015912    755    746 tbl
20:30:15.016054    757    746 nroff -mandoc -rLL=123n -rLT=123n -Tutf8
20:30:15.016598    758    746 nvim -u NORC +set background=dark +set ft=man -
20:30:15.017138    760    759 locale charmap
20:30:15.018113    761    757 groff -mtty-char -Tutf8 -mandoc -rLL=123n -rLT=123n
20:30:15.018924    762    761 troff -mtty-char -mandoc -rLL=123n -rLT=123n -Tutf8
20:30:15.018997    763    761 grotty
20:30:20.159494    768    758 /usr/bin/zsh -c uname -s
```

Showing that it is indeed nvim which spawns `/usr/bin/zsh -c uname -s`. I soon discovered it's not because of my config though, which only accidentally uses `uname -s`:

```
neovim$ ag 'uname -s'
runtime/autoload/man.vim
18:  if !has('win32') && $OSTYPE !~? 'cygwin\|linux' && system('uname -s') =~? 'SunOS' && system('uname -r') =~# '^5'
```

There's definitely something funking going on with subprocesses.

**Comment by nhooyr** [comment]
I'm looking into man-db's source code to see if I can figure out what it's doing.

**Comment by nhooyr** [comment]
Man uses http://libpipeline.nongnu.org/libpipeline.3.html to start the process and I think the code that does that is here http://git.savannah.gnu.org/cgit/man-db.git/tree/src/man.c#n1565

**Comment by nhooyr** [comment]
I added some printf statements and it looks like it is freezing on this line http://git.savannah.gnu.org/cgit/man-db.git/tree/src/man.c#n1908

**Comment by justinmk** [comment]
Bisected to 2dcae28328c1.

**Comment by aktau** [comment]
`signal_*_deadly()` doesn't appear to do interesting things: https://github.com/neovim/neovim/blob/3dd3d129d3a4644c3f2c4de4df4b2ceda380448e/src/nvim/os/signal.c#L129

I keep on thinking this is because of libuv. I think it handles SIGCHLD, or rather the blocking of SIGCHLD, differently based on the current signal mask. It requires a careful read-through of process.c and signal.c:

- https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L457:

```c
int uv_spawn(uv_loop_t* loop,
             uv_process_t* process,
             const uv_process_options_t* options) {
  // ...
  uv_signal_start(&loop->child_watcher, uv__chld, SIGCHLD);
  // ...
}
```

- https://github.com/libuv/libuv/blob/v1.x/src/unix/process.c#L48:

```c
static void uv__chld(uv_signal_t* handle, int signum) {
   // ...
    do
      pid = waitpid(process->pid, &status, WNOHANG);
    while (pid == -1 && errno == EINTR);
    // ...
}
```

- https://github.com/libuv/libuv/blob/v1.x/src/unix/signal.c#L289

```c
int uv_signal_start(uv_signal_t* handle, uv_signal_cb signal_cb, int signum) {
  // ...
  /* If the signal handler was already active, stop it first. */
  if (handle->signum != 0) {
    uv__signal_stop(handle);
  }

  uv__signal_block_and_lock(&saved_sigmask);

  /* If at this point there are no active signal watchers for this signum (in
   * any of the loops), it's time to try and register a handler for it here.
   */
  if (uv__signal_first_handle(signum) == NULL) {
    err = uv__signal_register_handler(signum);
    if (err) {
      /* Registering the signal handler failed. Must be an invalid signal. */
      uv__signal_unlock_and_unblock(&saved_sigmask);
      return err;
    }
  }

  handle->signum = signum;
  RB_INSERT(uv__signal_tree_s, &uv__signal_tree, handle);

  uv__signal_unlock_and_unblock(&saved_sigmask);
  // ...
}
```

But who knows, maybe I'm totally off. It could be that in one case Neovim spawns a thread and passes processes between them (or different libuv event loops), and in the other case it doesn't. Who's most familiar with the process spawning code at this point?

**Comment by aktau** [comment]
`SIG_SETMASK` can only be found in one place in libuv:

```c
static void uv__signal_unlock_and_unblock(sigset_t* saved_sigmask) {
  if (uv__signal_unlock())
    abort();

  if (pthread_sigmask(SIG_SETMASK, saved_sigmask, NULL))
    abort();
}
```

**Comment by justinmk** [comment]
> It could be that in one case Neovim spawns a thread and passes processes between them (or different libuv event loops), and in the other case it doesn't.

TUI runs on a different thread, but system() does not interact with that. And VimL runs on only one libuv loop, the global `main_loop`. One can test without the TUI thread by invoking nvim with `--headless`:

    export MANPAGER="nvim -u NORC --headless '+set background=dark' '+set hidden ft=man' +'Man ls' -"
    man printf

Note the `Man ls` command in the `MANPAGER` command. When bisecting, I found that doing `:Man foo` was enough to reproduce the bug after invoking nvim as a manpager.

With the above steps, `htop` shows `uname` as a zombie, though ctrl-c is enough to kill both processes...

**Comment by justinmk** [comment]
Maybe obvious, but this makes the bug go away:

```diff
diff --git a/src/nvim/event/libuv_process.c b/src/nvim/event/libuv_process.c
index a68badcc8f12..7c5d4fd08a46 100644
--- a/src/nvim/event/libuv_process.c
+++ b/src/nvim/event/libuv_process.c
@@ -55,6 +55,11 @@ bool libuv_process_spawn(LibuvProcess *uvproc)
     return false;
   }
-
+  sigset_t mask, prevmask;
+  sigemptyset(&mask);
+  sigaddset(&mask, SIGCHLD);
+  sigprocmask(SIG_UNBLOCK, &mask, &prevmask); // unblock SIGCHLD, get previous mask
+
   proc->pid = uvproc->uv.pid;
   return true;
 }
```

**Comment by justinmk** [comment]
[This post](http://unix.stackexchange.com/a/85365/14626) shows a nice way to observe the signals being blocked for a process. 

Even with Vim, SIGCHLD is blocked:

```
export MANPAGER=".vim-src/src/vim -N -u NORC '+set hidden ft=man' -"
VIMRUNTIME=/home/vagrant/neovim2/runtime/ man printf
cat /proc/2759/status
...
SigBlk: 0000000000010000
...
```

`:echo printf('%b', 0x0000000000010000) => 10000000000000000`, the 17th (1-indexed) bit corresponds to SIGCHLD:

```
kill -l
...
16) SIGSTKFLT   17) SIGCHLD     18) SIGCONT     19) SIGSTOP     20) SIGTSTP
...
```

When `vim` is invoked normally (not via MANPAGER), `SigBlk: 0000000000000000`.

Same results for `nvim`. Further confirmed by adding this code to nvim and vim:

```c
sigset_t mask, prevmask;
sigemptyset(&mask);
sigprocmask(SIG_UNBLOCK, NULL, &prevmask);
if (sigismember(&prevmask, SIGCHLD)) {
  EMSG("SIGCHLD is in mask");
} else {
  EMSG("SIGCHLD _not_ in mask");
}
```

Placing that code in Vim's `mch_call_shell` suggests that it does not even temporarily unblock SIGCHLD. So Nvim gets stuck in `epoll_wait`, why? Stepping through `libuv_process_spawn` with gdb shows that, after calling `uv_spawn`,  `nvim` is not blocked until control returns to the event loop:

    process_wait > loop_poll_events > uv_run > uv__epoll_wait

> Perhaps this is a libuv bug

@aktau I'm not very familiar with the conventions and lore of signals. 

- Is it normal that the signal mask is inherited? 
- The typical pattern for blocking SIGCHLD before spawning a process, is "block, spawn, then immediately unblock". Does this point to a bug in man-db, given that SIGCHLD remains blocked after spawning vim/nvim? 

cc @saghul since I believe we have enough information  to see whether it is worth opening a libuv issue.

**Comment by justinmk** [comment]
RFC at https://github.com/neovim/neovim/pull/5243
