### ISSUE TITLE
'K' to open manpages should use better section order for code filetypes

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#5233]
- `nvim --version`:
```
NVIM v0.1.5-642-g2dd9f33
Build type: None
Compilation: /usr/lib/ccache/cc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/neovim/build/config -I/tmp/neovim/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by josh@x

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 7.4.1829) behaves differently? No.
- Operating system/version: Debian GNU/Linux latest sid
- Terminal name/version: gnome-terminal 3.20.2
- `$TERM`: xterm-256color

### Actual behaviour

In a C program, pressing `K` on `rmdir` gives the manpage for the command-line tool rmdir in section 1, rather than the syscall in section 2.

### Expected behaviour

In a C program, pressing `K` on `rmdir` should show the rmdir manpage in section 2.

In a shell script, pressing `K` on rmdir should show the rmdir manpage in section 1.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC testfile.c
Go into insert mode and type rmdir.
Hit escape
Press K
```

**Comment by nhooyr** [comment]
You can press `2K` to go into section 2 of the manpage under the cursor.

**Comment by joshtriplett** [comment]
True, but I'd love to have it work more automatically, reordering the search order when editing a programming language (versus a shell script or similar).

**Comment by nhooyr** [comment]
You could just remap it in whatever filetype you want, e.g.

```vim
autocmd FileType c nnoremap K 2K
```

By default this will use section two for the manpages, but fallback to the default if it cannot be found in section 2. I think this is exactly what you want.

**Comment by joshtriplett** [comment]
@nhooyr Nice idea!

I do think supporting that by default would provide a better experience, though.

**Comment by nhooyr** [comment]
Whoops fixed.

I'll think about supporting it by default. In that case, I'd rather be able to specify a list of sections, e.g. 2,3 first instead of just 2 or just 3. The current plugin doesn't support this.

**Comment by joshtriplett** [comment]
@nhooyr Exactly; a programming language would want to use a different section order, not just a single preferred section.

**Comment by nhooyr** [comment]
I'll add this in an upcoming PR I'm working on for `:Mangrep`.

**Comment by justinmk** [comment]
This would be a ftplugin change. Man.vim should not be doing clever stuff. 

And generally for standard behaviors the Vim convention is predictability rather than DWIM..

**Comment by nhooyr** [comment]
Regardless, I think this could be a very useful feature, outweighing it's "magical" feel. For example, it is much more intuitive to prioritize sections 2 and 3 for C filetypes instead of whatever man does by default. It doesn't make sense to press `K` on `printf` in a C file and instead of `printf(3)`, it takes you to `printf(1)`.

**Comment by justinmk** [comment]
It should be changed in the ftplugin for C then.

**Comment by nhooyr** [comment]
Adding this was a one line change. https://github.com/nhooyr/neovim/commit/c1ace49b96178419f47032dd56edf70df2e92005#diff-2451f3ce2ccfcf4300067af16309cd75L117

So now, in the c ftplugin, we can just set `let b:man_default_sections = '3,2'`. That's it!

Is this OK?

**Comment by justinmk** [comment]
> So now, in the c ftplugin, we can just let b:man_default_sections = '3,2'

That seems reasonable.

**Comment by joshtriplett** [comment]
@nhooyr Awesome!

**Comment by nhooyr** [comment]
It's a slightly bigger change now, but still very small.

https://github.com/nhooyr/neovim/commit/389f3e9df94588a17801606c342eba23e40f0770
