### ISSUE TITLE
Segmentation fault when using Unite grep

### ISSUE THREAD

**Issue by balta2ar** [neovim/neovim#5234]
I recompiled nvim using its PKGBUILD: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/neovim
I only set -DCMAKE_BUILD_TYPE=Debug to make sure backtraces are nicer and disabled stripping (default behavior in ArchLinux).
- `nvim --version`:

NVIM 0.1.5
Build type: Debug
Compilation: /usr/bin/cc -g -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/bz/prg/src/other/editor/nvim/src/build/config -I/home/bz/prg/src/other/editor/nvim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/bz/prg/src/other/editor/nvim/src/build/src/nvim/auto -I/home/bz/prg/src/other/editor/nvim/src/build/include
Compiled by bz@boltx64

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui  
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
- Vim (version: ) 7.4 Included patches: 1-2143. **I could not make vim segfault in this scenario**
- Operating system/version: ArchLinux (remote)
- Terminal name/version: terminator 0.96 (client, on Ubuntu 12.04)
- `$TERM`: screen-256color
- tmux: tmux 2.2 (remote)
### Actual behaviour

neovim segfaults when I perform Unite grep and cancel the search using `Ctrl-C`.
### Expected behaviour

Unite should cancel the search without segfaulting.
### Steps to reproduce using `nvim -u NORC`

Segfault happens when I search over my project. For the purpose of reproducibility I've managed to reproduce the issue when I search in files of the plugins I'm using. Sorry this isn't exactly minimal set of files, but the segfault happens rather ofter on these files (not 100% every time, unfortunately). Sometimes I have to run the command about 5-6 times before it crashes.

``` bash
mkdir nvim-segfault && cd nvim-segfault

mkdir -p ~/.cache/dein/repos/github.com/Shougo
git clone https://github.com/Shougo/dein.vim ~/.cache/dein/repos/github.com/Shougo/dein.vim

wget -O repos.txt http://sprunge.us/JKOX
for f in `cat repos.txt `; do echo ">> $f"; git clone "https://github.com/$f"; done

wget -O min.vim http://sprunge.us/RSTK
nvim -N -u min.vim -n -c "Unite grep:.::def"
```

After that, while search is still running, I occasionally press arrow keys, and if I press `Ctrl-C`, neovim often segfaults at this point with a slight delay.

Here are several backtraces that I have managed to save:

[http://sprunge.us/KiYf](http://sprunge.us/KiYf)
[http://sprunge.us/CSLX](http://sprunge.us/CSLX)
[http://sprunge.us/ZSdi](http://sprunge.us/ZSdi)

I can share whole core dumps if necessary.

I'm slightly hesitant whether I should have reported this issue to Unite repo, but I figured plugins should not crash the editor. Maybe @Shougo knows more about this behavior.
# Appendix

minimal [vimrc](http://sprunge.us/RSTK):

``` vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
if &compatible
  set nocompatible
endif
call dein#begin('~/.cache/dein-segfault')
call dein#add('Shougo/dein.vim', {'rtp': ''})
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
call dein#add('Shougo/unite.vim')
call dein#end()
if dein#check_install()
    call dein#install()
endif

filetype plugin indent on
syntax enable
set nocompatible
```

list of my [plugins](http://sprunge.us/JKOX):

```
Shougo/dein.vim
luochen1990/rainbow
kshenoy/vim-signature
tacroe/unite-mark
tweekmonster/impsort.vim
terryma/vim-multiple-cursors
scrooloose/syntastic
neomake/neomake
AndrewRadev/linediff.vim
SirVer/ultisnips
honza/vim-snippets
Valloric/ListToggle
Valloric/MatchTagAlways
mileszs/ack.vim
osyo-manga/vim-over
osyo-manga/vim-anzu
haya14busa/incsearch.vim
haya14busa/incsearch-fuzzy.vim
haya14busa/vim-asterisk
Shougo/deoplete.nvim
zchee/deoplete-jedi
Shougo/neoinclude.vim
Shougo/context_filetype.vim
Shougo/echodoc.vim
racer-rust/vim-racer
rust-lang/rust.vim
Chiel92/vim-autoformat
fatih/vim-go
tmux-plugins/vim-tmux
chase/vim-ansible-yaml
davidhalter/jedi-vim
nsf/gocode
klen/python-mode
dbsr/vimpy
Konfekt/FastFold
scrooloose/nerdcommenter
scrooloose/nerdtree
t9md/vim-quickhl
terryma/vim-expand-region
paradigm/vim-multicursor
Olical/vim-enmasse
pelodelfuego/vim-swoop
tpope/vim-markdown
jtratner/vim-flavored-markdown
nelstrom/vim-markdown-preview
tpope/vim-pastie
tpope/vim-repeat
tpope/vim-surround
tpope/vim-unimpaired
vim-scripts/VimExplorer
vim-scripts/bufexplorer.zip
vim-scripts/matchit.zip
tomtom/tcomment_vim
vim-scripts/taglist.vim
majutsushi/tagbar
dag/vim2hs
eagletmt/ghcmod-vim
eagletmt/neco-ghc
sk1418/Join.git
Shougo/unite.vim
Shougo/unite-outline
tsukkee/unite-tag
Shougo/neomru.vim
vim-scripts/Vim-R-plugin
junegunn/vim-easy-align
justinmk/vim-syntax-extra
metakirby5/codi.vim
ludovicchabant/vim-gutentags
ntpeters/vim-better-whitespace
easymotion/vim-easymotion
dahu/vim-fanfingtastic
wellle/targets.vim
kana/vim-textobj-user
rhysd/vim-textobj-anyblock
kana/vim-textobj-lastpat
kana/vim-textobj-entire
kana/vim-textobj-line
kana/vim-textobj-indent
beloglazov/vim-textobj-quotes
bps/vim-textobj-python
glts/vim-textobj-comment
Julian/vim-textobj-brace
lucapette/vim-textobj-underscore
reedes/vim-textobj-quote
reedes/vim-textobj-sentence
saaguero/vim-textobj-pastedtext
thinca/vim-textobj-between
vim-scripts/ReplaceWithRegister
kana/vim-operator-user
kana/vim-smartword
triglav/vim-visual-increment
flazz/vim-colorschemes
guns/xterm-color-table.vim
mhinz/vim-signify
szw/vim-maximizer
thinca/vim-qfreplace
vim-scripts/greplace.vim
vim-airline/vim-airline
vim-airline/vim-airline-themes
jaxbot/semantic-highlight.vim
junegunn/fzf
junegunn/fzf.vim
beloglazov/vim-online-thesaurus
AndrewRadev/splitjoin.vim
chrisbra/NrrwRgn
sheerun/vim-polyglot
schickling/vim-bufonly
```

**Comment by justinmk** [comment]
Thanks, this is the correct place to report, segfaults are always bugs.

Does it happen without vimproc?

**Comment by Shougo** [comment]
Unite grep depends on vimproc.

**Comment by justinmk** [comment]
There's no other grep mode of Unite that works without vimproc? We need to narrow down what's required to reproduce the issue.

**Comment by Shougo** [comment]
> There's no other grep mode of Unite that works without vimproc? 

Yes,  I think it is `libcall()` compatibility bug.

**Comment by justinmk** [comment]
I thought so too, but didn't see `libcall` in the backtraces.

**Comment by Shougo** [comment]
@balta2ar Can you reproduce it without grep source?
For example, "file_rec/async" source uses vimproc but "file_rec" source does not use vimproc.

**Comment by balta2ar** [comment]
@Shougo @justinmk I couldn't manually reproduce the segfault without vimproc. I've tried running file_rec and file_rec/neovim several times, it was fine. Could you please suggest an automation script that would allow me to run the test automatically and repeatedly for a while? For example, start nvim, run Unite file_rec, wait several seconds, do several `j` keypresses, `Ctrl-C`, and then quit. I'm afraid I can't get beyond running Unite file_rec with my Vimscript skills.

**Comment by justinmk** [comment]
@balta2ar Does https://github.com/neovim/neovim/pull/6070 help with this?

**Comment by balta2ar** [comment]
@justinmk I've tried several times and couldn't reproduce it manually.  Feel free to close now or when merged.
