### ISSUE TITLE
:Man does not accept command modifiers

### ISSUE THREAD

**Issue by milsen** [neovim/neovim#5235]
- `nvim --version`:
```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Übersetzt von builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"
```
- Vim (version: 7.4.2143) behaves differently? In vim with `ftplugin/man.vim` enabled `:Man` does not accept command modifiers either. But with `let g:ft_man_open_mode = 'vert'`, vertical splits are always opened (this option does not exist in neovim anymore).
- Operating system/version: Arch Linux
- Terminal name/version: termite v11
- `$TERM`: xterm-termite

### Actual behaviour
`:vertical Man printf` opens a horizontal split (on the top) with the man-page just like `:Man printf`.
`:rightbelow Man printf` does the same thing.

### Expected behaviour
`:vertical Man printf` should open a vertical split, `:rightbelow Man printf` a horizontal split on the bottom. `:Man` should behave like `:help` in that regard.

To quote the help-page:
```
|:Man| accepts command modifiers. For example, to use a vertical split: >
     :vertical Man printf
```

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:vertical Man printf
```

**Comment by nhooyr** [comment]
See #5210
