### ISSUE TITLE
Windows: functionaltest os.remove() fails to remove directories `Permission Denied`

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5236]
- Windows: 8.1

test/functional/helpers.lua rmdir() uses os.rmdir() to [remove empty folders](https://github.com/neovim/neovim/blob/master/test/functional/helpers.lua#L390), this works in POSIX but not in windows. This is causing some of the functional tests to error out.

This appears to be the expected behaviour ([SO](http://stackoverflow.com/questions/29532422/lua-os-remove-folder-results-in-permission-denied)). I expected lfs.rmdir (https://github.com/keplerproject/luafilesystem/issues/4) to work as a replacement here, but I'm getting the same error instead.

The following tests are failing because of this

- getcwd_spec.lua
- recover_spec.lua

**Comment by justinmk** [comment]
Could use the nvim function instead.

**Comment by equalsraf** [comment]
The problem with nvim_call('delete', path) is that it may depend on what the test is doing e.g. the current working directory for nvim might be different from the toplevel test dir.

**Comment by equalsraf** [comment]
`lfs.rmdir()` actually works sometimes, I think `rdmir()` returns EACCESS if another process holds a handle to the same directory.

Attempting to close the neovim process with `qa!` or session:close() does not seem to work, possibly because the following call is done before the process is actually terminated. Changing the working path with `execute("cd /")` works with a tleast one test.

**Comment by justinmk** [comment]
> The problem with nvim_call('delete', path) is that it may depend on what the test is doing e.g. the current working directory for nvim might be different from the toplevel test dir.

Could change to an absolute path:

    helpers.execute("call delete(fnamemodify('"..path.."', ':p'))

If EACCES is caused by the file being open in `nvim`, then deleting it from `nvim` with `delete()` should work.

**Comment by equalsraf** [comment]
Ended up doing all of the above, on a case by case basis. Not a full fix, but fixes one test and helps with the other, will continue this later:

```diff
diff --git a/test/functional/ex_cmds/recover_spec.lua b/test/functional/ex_cmds/recover_spec.lua
index 0c97857..bb82276 100644
--- a/test/functional/ex_cmds/recover_spec.lua
+++ b/test/functional/ex_cmds/recover_spec.lua
@@ -6,8 +6,6 @@ local execute, eq, clear, eval, feed, expect, source =
   helpers.execute, helpers.eq, helpers.clear, helpers.eval, helpers.feed,
   helpers.expect, helpers.source
 
-if helpers.pending_win32(pending) then return end
-
 describe(':recover', function()
   before_each(clear)
 
@@ -23,11 +21,10 @@ describe(':preserve', function()
   local swapdir = lfs.currentdir()..'/testdir_recover_spec'
   before_each(function()
     clear()
-    helpers.rmdir(swapdir)
     lfs.mkdir(swapdir)
   end)
   after_each(function()
-    helpers.rmdir(swapdir)
+    helpers.call('delete', swapdir, 'rf')
   end)
 
   it("saves to custom 'directory' and (R)ecovers (issue #1836)", function()
diff --git a/test/functional/helpers.lua b/test/functional/helpers.lua
index e30dcc7..d5c1841 100644
--- a/test/functional/helpers.lua
+++ b/test/functional/helpers.lua
@@ -423,9 +423,9 @@ local function rmdir(path)
       end
     end
   end
-  local ret, err = os.remove(path)
+  local ret, err = lfs.rmdir(path)
   if not ret then
-    error('os.remove: '..err)
+    error('lfs.rmdir: '..path..' '..err)
   end
   return ret
 end
diff --git a/test/functional/legacy/getcwd_spec.lua b/test/functional/legacy/getcwd_spec.lua
index dcb56eb..ae6e57d 100644
--- a/test/functional/legacy/getcwd_spec.lua
+++ b/test/functional/legacy/getcwd_spec.lua
@@ -4,12 +4,12 @@ local helpers = require('test.functional.helpers')(after_each)
 local eq, eval, source = helpers.eq, helpers.eval, helpers.source
 local call, clear, execute = helpers.call, helpers.clear, helpers.execute
 
-if helpers.pending_win32(pending) then return end
-
 describe('getcwd', function()
   before_each(clear)
 
   after_each(function()
+    -- Windows: leave directory or rmdir() fails
+    execute('cd /')
     helpers.rmdir('Xtopdir')
   end)
```

**Comment by justinmk** [comment]
Working on this in https://github.com/neovim/neovim/pull/5362.

**Comment by justinmk** [comment]
@equalsraf https://github.com/neovim/neovim/pull/5362 with the `lfs.rmdir` change seems to fix the "Permission denied" error I observed with the `'directory' option` functional test. I also added a delayed retry to `helpers.rmdir()` to work around the possibility that the nvim session is slow to exit (which I think should help with [this](https://github.com/neovim/neovim/issues/5236#issuecomment-241876716)).

**Comment by equalsraf** [comment]
> I also added a delayed retry to helpers.rmdir() to work around the possibility that the nvim session is slow to exit (which I think should help with this).

I think you can also work around it with `:cd /`

**Comment by justinmk** [comment]
@equalsraf In the case of https://github.com/neovim/neovim/pull/5362, `:cd /` wouldn't help because CWD is not what's holding the handle, but `set directory=...`.

However `qall!` combined with the other changes in https://github.com/neovim/neovim/pull/5362 seems to work correctly. (As you noted, `qall!` _without_ the changes is not sufficient; but `qall!` fixed the final case where a file--not a directory--was locked.)

So I think the `:cd /` workarounds can be removed, and if necessary, replaced by `qall!` (in the case of teardown).
