### ISSUE TITLE
man.vim: mdocml support

### ISSUE THREAD

**Issue by stpx** [neovim/neovim#5240]
- `nvim --version`: NVIM 0.1.5
- Operating system/version: VoidLinux

[runtime/autoload/man.vim#L6-L12](https://github.com/neovim/neovim/blob/4dc4efc36fad058298d69d4b2533beded3293c33/runtime/autoload/man.vim#L6-L12)

`man -P cat` and `man -w` are not supported on VoidLinux and some BSD's that use [mdocml](http://mdocml.bsd.lv/) as the default manpage viewer.

Possible solution for `man -P cat`:
 `env PAGER=cat man` should work with different `man(1)` implementations.

Possible solution `man -w`:
`manpath(1)`? I believe `man-db`, FreeBSD, Mac OSX all have `manpath(1)`.

**Comment by nhooyr** [comment]
Oh, I didn't know about `manpath(1)`. That could be used to fix autocompletion but thing is, we use `man -w` to verify if man can open a particular file. I'll fix this.

**Comment by nhooyr** [comment]
As for `man -P`, we used to use `env` but I thought that `man -P` was a bit more clean. I'll revert and use `env MANPAGER=cat` instead.

**Comment by nhooyr** [comment]
Nevermind, looks like [mdocml](http://mdocml.bsd.lv/man/man.1.html) supports `-w` for finding the path of a manpage, it just doesn't isn't an alias for `manpath` like on OSX/Linux.

**Comment by stpx** [comment]
Right. mdocml doesn't provide `manpath(1)` but I email the maintainer and he said may provide an minimal implementation that just spits out the manpath.

**Comment by nhooyr** [comment]
So then only autocompletion doesn't work. It won't work until upstream adds `manpath` because otherwise, we do not know where to search for man files.

I'll fix the first issue though.

**Comment by stpx** [comment]
With the first issue fixed; your correct, just autocompletion doesn't work

**Comment by nhooyr** [comment]
Ok, so the first issue is fixed in #5210.

**Comment by pickfire** [comment]
Looks like neovim 2.0 does not work well with mdocml, when I pressed <kbd>K</kbd>, I got the following error since `man` in mdocml does not support reading from path.

   man.vim: command error (39) env MANPAGER=cat MANWIDTH=194 man /usr/share/man/man3/alloca.3.gz: man: No entry for /usr/share/man/man3/alloca.3.gz in the manual.

**Comment by nhooyr** [comment]
@pickfire Does it support reading from the path via some flag?

**Comment by pickfire** [comment]
@nhooyr Unfortunately, nope.
