### ISSUE TITLE
system({cmd}, {large input}) aborts

### ISSUE THREAD

**Issue by ghost** [neovim/neovim#5241]
- `nvim --version`: 0.1.6-dev
- Vim (version: ) behaves differently? mac-vim 7.4.2196 have normal features
- Operating system/version: mac os 10.11.5
- Terminal name/version: iterm 
- `$TERM`: xterm-256color-italic

**Comment by justinmk** [comment]
We can't debug every possible plugin. Can you provide specific details? An error message? Things that did or did not work?

**Comment by manielng** [comment]
![screen shot 2016-08-25 at 09 29 30](https://cloud.githubusercontent.com/assets/18302598/17953513/a6ab3494-6aa6-11e6-8c5f-fcf2ed5cda04.jpg)

**Comment by manielng** [comment]
I can't open markdown file now

**Comment by nhooyr** [comment]
Copy and paste it please.

**Comment by nhooyr** [comment]
There is already an open issue for this: suan/vim-instant-markdown#98

**Comment by justinmk** [comment]
This is definitely a bug in nvim. Somehow we're hitting an assertion. Should be easy to get a backtrace, but wow do we have a lot of segfaults to investigate.

**Comment by manielng** [comment]
this is another error when i open nvim without file: 
error caught in request handler 'python_eval ('ycm_state.NativeFiletypeCompletionUsable()',)':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/neovim/plugin/script_host.py", line 154, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/Users/klauoth/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 291, in NativeFilet
ypeCompletionUsable
    self.NativeFiletypeCompletionAvailable() )
  File "/Users/klauoth/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 286, in NativeFilet
ypeCompletionAvailable
    vimsupport.CurrentFiletypes() ] )
  File "/Users/klauoth/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 276, in FiletypeCom
pleterExistsForFiletype
    exists_completer = SendCompleterAvailableRequest( filetype )

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 28: ordinal not in range(128)

**Comment by justinmk** [comment]
@manielng Your last comment just looks like your `neovim` python module (`pip install --upgrade neovim`) is old. Please try `:CheckHealth`, and if that doesn't give any clues, report in a separate issue.

**Comment by justinmk** [comment]
@manielng Regarding the original issue: that plugin requires `instant-markdown-d`. What does 

    :!instant-markdown-d

show?

**Comment by justinmk** [comment]
To reproduce, download [issue5241.txt](https://github.com/neovim/neovim/files/438565/issue5241.txt)  (from https://github.com/suan/vim-instant-markdown/issues/98), then:

    call system('curl -X PUT -T - http://localhost:8090/ &>/dev/null &', join(readfile('issue5241.txt', 0)))

Observations:

- Dependent on the size of the file (maybe a buffer-flush race).
    - The attached file is enough to abort on OSX 10.10.5
    - On ubuntu, try increasing the file by 4x.
- Not caused by #4646.

**Comment by manielng** [comment]
@justinmk it shows:
![screen shot 2016-08-26 at 14 38 14](https://cloud.githubusercontent.com/assets/18302598/17996395/305d12b2-6b9b-11e6-8b3f-2fce9c917881.jpg)

**Comment by manielng** [comment]
@justinmk I updated the python module , there are no error now, thanks!
