### ISSUE TITLE
nvim --version output does not match nightly tag in git

### ISSUE THREAD

**Issue by cschol** [neovim/neovim#5265]
nvim --version:
NVIM v0.1.6-22-g97c6d80
[snip]

git describe nightly
v0.1.5-22-g97c6d80

Why is there a difference in minor version number?

**Comment by fwalch** [comment]
This is an unfortunate problem with Git's output vs semver.org's specifications.

In Semantic Versioning, the ordering is like `0.1.6-22 < 0.1.6-23 < 0.1.6`. In Git, `0.1.5-22` means "22 commits since the `0.1.5` tag.
