### ISSUE TITLE
Cannot write/append to a fifo (named pipe)

### ISSUE THREAD

**Issue by xrchz** [neovim/neovim#5267]
- `nvim --version`:
```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Previous nvim version behaves differently
```
NVIM 0.1.4
```
- Operating system/version: GNU, Linux 4.5.4
- Terminal name/version: termite v11
- `$TERM`: `xterm-termite`

### Actual behaviour
Make a fifo (named pipe) and read from it, then write (append) to it from nvim. The buffer contents are not read by the fifo and nvim freezes up.
```
mkfifo /tmp/test
cat /tmp/test
```
while
```
nvim -u NORC
ihello<ESC>
:w>>/tmp/test
```
### Expected behaviour
Writing succeeds and returns, and the contents of the buffer are visible via `cat`. This is the case with nvim 0.1.4.

**Comment by oni-link** [comment]
Opening a pipe with `O_RDONLY` set and `O_NONBLOCK` cleared would block until a thread would open it for writing (`open(3)`):
```diff
diff --git a/src/nvim/os/fs.c b/src/nvim/os/fs.c
index e63b8b6..b05c466 100644
--- a/src/nvim/os/fs.c
+++ b/src/nvim/os/fs.c
@@ -164,7 +164,7 @@ int os_nodetype(const char *name)
   // saves us the hassle.
 
   int nodetype = NODE_WRITABLE;
-  int fd = os_open(name, O_RDONLY, 0);
+  int fd = os_open(name, O_RDONLY | O_NONBLOCK, 0);
   switch(uv_guess_handle(fd)) {
     case UV_TTY:         // FILE_TYPE_CHAR
       nodetype = NODE_WRITABLE;
```
With this patch your example seems to work.

**Comment by aktau** [comment]
Is there any reason @oni-link's patch can't be included? I'm no longer very familiar with this code (and didn't know `os_nodetype` existed), usually changing things to non-blocking can have unpredictable effects, but maybe the effect of that fd is limited?

**Comment by justinmk** [comment]
I just haven't had a chance to write a test for it.
