### ISSUE TITLE
syntax folding + completion (Ctrl+N) is slow

### ISSUE THREAD

**Issue by phuongnd08** [neovim/neovim#5270]
- `nvim --version`: 0.14-dev
- Vim (version: ) behaves differently? Nope. VIM is painfully slow when Syntax Folding is on, too
- Operating system/version: Mac OSX 10.10.5
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color
### Actual behaviour
Turn on Syntax Folding, Then collapse all the fold, then expand one fold and type Ctrl+N. It takes very a long delay until Neovim start to respond
### Expected behaviour
Neovim offer autocomplete after a fraction of second
### Steps to reproduce using `nvim -u NORC`
(no idea)

**Comment by Shougo** [comment]
It is well known Vim problem.

The workaround is to use FastFold plugin.
https://github.com/Konfekt/FastFold

You should report it in github vim issues pages or write the patch :-)

https://www.reddit.com/r/neovim/comments/50c3tz/the_fastfold_plugin_seems_to_be_a_workaround_for

**Comment by phuongnd08** [comment]
Thanks, this plugin does help :D. I was under the impression that neovim was out so bugs can be more easily fixed compare to vim.

**Comment by tjdevries** [comment]
If you submit the pull request, it has a very high likelihood of getting included here. That is not always the case in the Vim dev community. We will also do our best to provide you with feedback along the way!

**Comment by Shougo** [comment]
>  I was under the impression that neovim was out so bugs can be more easily fixed compare to vim.

If you think so, you can do it!
I don't think it is easy to fix.

**Comment by chrisbra** [comment]
Am 2016-08-31 04:01, schrieb TJ DeVries:
> If you submit the pull request, it has a very high likelihood of
> getting included here. That is not always the case in the Vim dev
> community. We will also do our best to provide you with feedback along
> the way!

To be fair, although this is a well known bug, no one has ever
analyzed or profiled Vim and suggested a fix.

So it is not fair, to claim, we would not fix it. In fact, I believe
a PR would have been as well included in Vim pretty fast.

Best,
Christian

**Comment by justinmk** [comment]
> I was under the impression that neovim was out so bugs can be more easily fixed compare to vim.

Some parts have been refactored; many new features have been added; well-designed PRs with good test coverage are merged very quickly.

As @chrisbra noted, for any Vim code inherited by Neovim (i.e., code we didn't totally refactor), the challenges associated with fixing a bug are essentially the same for both projects.

Neovim has not significantly changed Vim logic related to syntax/regex/folding/normal/...

**Comment by phuongnd08** [comment]
It's superb to be have this issue fixed. Thank you @justinmk
