### ISSUE TITLE
Some bugs on windows 10 and neovim-qt

### ISSUE THREAD

**Issue by thebergamo** [neovim/neovim#5271]
- `NVIM v0.1.6-833-g35f67ee`
- Windows 10
- Powershell

### Actual behaviour
I install neovim-qt and after open a file, neovim shows a blank screen, when I try arrow down or up, sometimes the content of file are showed, but not entire just some pieces. This behaviour are followed in normal and edit mode.

![](https://puu.sh/qTPlv/c1dae34dfc.png)
![](https://puu.sh/qTPnn/bb29f4eb57.png)

**Comment by equalsraf** [comment]
Since this seems to be an issue with neovim-qt can you close this issue here, I already opened a new one in https://github.com/equalsraf/neovim-qt/issues/175

**Comment by thebergamo** [comment]
@equalsraf thks!
