### ISSUE TITLE
neovim 0.1.5 colors within tmux are off.

### ISSUE THREAD

**Issue by flounders** [neovim/neovim#5272]
- `nvim --version`: NVIM 0.1.5
- Vim (version: ) behaves differently? 7.4
- Operating system/version: Arch Linux (up to date as of 2016-08-30)
- Terminal name/version: urxvt 9.22
- `$TERM`: tmux 2.2

### Actual behaviour

Filetype information is no longer visible.
Airline-theme colors for insert mode have a much brighter background. Using solarized dark. To see the difference [https://imgur.com/gallery/sPjFl](https://imgur.com/gallery/sPjFl)

When I run nvim outside of tmux it works fine.

### Expected behaviour

Colors should appear as they do in vim, and filetypes should be visible.

### Steps to reproduce

This is with vim-plug and the plugins are already installed.

```
nvim -u test.txt
```

[test.txt](https://github.com/neovim/neovim/files/445958/test.txt)

**Comment by brcolow** [comment]
Is your `$TERM` set to "screen-256color"? If not, you can set this in tmux.conf using:

`set -g default-terminal "screen-256color"`

Can you try this and report back?

**Comment by gglanzani** [comment]
@brcolow Same problem here. I have that line in my ~/.tmux.conf

**Comment by flounders** [comment]
Okay just got in this morning, had to restart my machine. Before my $TERM value was screen, now it's screen-256color and it's working fine.

**Comment by fwalch** [comment]
For reference: https://github.com/neovim/neovim/wiki/FAQ#colors-arent-displayed-correctly

**Comment by gglanzani** [comment]
For me it still doesn't work on Windows Subsytem for Linux inside Tmux (works fine outside tmux though). I've checked with both `set -g default-terminal "screen-256color"` and `set -g default-terminal "screen-256color-bce"`.

I see nvim (or tmux) is desperately trying to show the proper colors, but they are nowhere near the colors showed without tmux. If I can help with debugging in any way, let me know :)

**Comment by justinmk** [comment]
Does your version of tmux support truecolor?

**Comment by gglanzani** [comment]
That did the trick, thanks @justinmk
