### ISSUE TITLE
incorrect fname_case?

### ISSUE THREAD

**Issue by SolaWing** [neovim/neovim#5273]
`echo has('fname_case')` **return 1** in my **macbook pro 13inch 2015**.

but my `File System Personality:  Journaled HFS+` is case insensitive.

this cause my objc `*.h` file be recognized as `*.H` and set to cpp file
- `nvim is the newest HEAD version installed from brew`
- MacVim return 0.

**Comment by nhooyr** [comment]
I can reproduce on my Macbook Pro 15 inch 2015 with macOS Sierra.

**Comment by jamessan** [comment]
The fun part about the Mac filesystems are that they can be configured either way.  By default, if I remember right, they are case insensitive & case preserving (similar to NTFS).

I'm not sure if there's a good way to detect this at runtime, especially since OS doesn't dictate filesystem.

**Comment by nhooyr** [comment]
How about we create a file with a uppercase name in a temporary directory and then attempt to read it with a lowercase name?

**Comment by jamessan** [comment]
Every time nvim starts?

**Comment by nhooyr** [comment]
Why not? We can just delete the temp directory afterwards.

**Comment by nhooyr** [comment]
What's the use case for `fname_case` anyway? It's only used in of `runtime/filetype.vim` for defining autocmds for different extensions. As in, when the file system is case sensitive, a `BufRead` autocmd for `*.rd,*.Rd` is defined. Imo, there is no point in doing that, you should assume that the file system is case sensitive and work from there. You aren't saving much by avoiding a few autocmds for some extensions. So I agree with the current behaviour of always setting `fname_case` to 1.

**Comment by jamessan** [comment]
`fname_case` is basically a runtime way of exposing some decisions that are also being made in the C code.  Search for `USE_FNAME_CASE`.

**Comment by SolaWing** [comment]
I don't care if add some autocmd. But for triggering incorrect autocmds.
Suppose I have following autocmd:
```vim
autocmd BufNewFile,BufRead *.h echom "*.h"
autocmd BufNewFile,BufRead *.H echom "*.H"
```
when I edit `a.h`, both autocmds are triggered.
call
```vim
doautocmd BufNewFile a.h
```
also trigger both.
and I only want to trigger `*.h`

**Comment by nhooyr** [comment]
@SolaWing  Only `*.h` is triggered for me.

@jamessan gotcha. Either way, all I'm saying is I don't see much benefit in setting `fname_case` accurately.

**Comment by SolaWing** [comment]
@nhooyr Oh, I have fileignorecase to ease my typing in cmd line. Thank you for made me noticing this different.

**Comment by justinmk** [comment]
So Vim considers macOS case-insensitive? Should we follow that?

**Comment by jamessan** [comment]
> So Vim considers macOS case-insensitive?

Yes, since the default filesystem (and filesystem options) used for macOS _are_ case insensitive.

**Comment by justinmk** [comment]
We define `USE_FNAME_CASE` for macOS, as Vim does. It corrects buffer names after they've been loaded, it doesn't affect wildmode completion AFAICT. 

I get the same result as https://github.com/neovim/neovim/issues/5273#issuecomment-243657679 from the given test case, and https://github.com/neovim/neovim/issues/5273#issuecomment-243659026 confirms that there was confusion, so this issue doesn't seem valid.

I did notice that we don't set `USE_FNAME_CASE` for Windows, I'll make a PR for that.
