### ISSUE TITLE
Reading multiple files in for loop reads first line of each file, then remainder of each file

### ISSUE THREAD

**Issue by skylerberg** [neovim/neovim#5274]
- `nvim --version`: 0.1.6-dev
- Vim (version: ) behaves differently? No, vim 7.4 also has this bug.
- Operating system/version: Ubuntu 14.04 upgraded to Linux kernel 4.2.3-040203-generic
- Terminal name/version: gnome-terminal, running tmux
- `$TERM`: screen-256color

### Actual behaviour

running the following command:
```
:for f in split(globpath('.', '*'), '\n')
:  exe 'r' f
:endfor
```
Reads the first line of each file, puts this text in the document, then reads the rest of each file. See reproduction for an example.

### Expected behaviour

Each file is read in one at a time, preferably the first file is read entirely, then the next and so on an so forth.

### Steps to reproduce using `nvim -u NORC`

Creating the following three files

a:
```
Line 1, file a
Line 2, file a
Line 3, file a
```
b:
```
Line 1, file b
Line 2, file b
Line 3, file b
```
c:
```
Line 1, file c
Line 2, file c
Line 3, file c
```

run the following in the  same directory as these files:
```
nvim
:for f in split(globpath('.', '*'), '\n')
:  exe 'r' f
:endfor
```
This results in the following text:
```

Line 1, file a
Line 1, file b
Line 1, file c
Line 2, file c
Line 3, file c
Line 2, file b
Line 3, file b
Line 2, file a
Line 3, file a
```

### Notes
I have tried this many different times with different numbers of files with different contents and the pattern is always the same. The first line of each file, then the rest of each file after that.

**Comment by skylerberg** [comment]
I should note that I am totally new to vimscript (this is one of my first for-loops). It is possible that I have just messed something up here. However, since I can't conceive of a way where the output I am seeing makes sense, I am reporting it as a bug.

**Comment by ZyX-I** [comment]
This is not a bug, absolutely. `:read` puts file contents after a specific line, by default the curent one. So it first reads first file, places cursor at the first line of the new content, then reads the second file, placing it after the first line of the first file, etc. If you need different results then you must specify line to place file contents after (e.g. `']` for each iteration, but the first one).

Additionally, do not use `split(glob*(…), '\n')`, `\n` is absolutely valid character to place in `$PATH` and you almost definitely do not need to depend on &suffixes and &wildignore options. Neither do `exe 'r' f`. First should be written as `globpath('.', '*', 1, 1)` (it returns a list), second should use `fnameescape()` around `f`.

**Comment by skylerberg** [comment]
Ah, @ZyX-I you are completely correct. Thanks for the pointers!
