### ISSUE TITLE
no syntax highlighting in tty terminals (ctrl-alt-fn) when TERM=linux

### ISSUE THREAD

**Issue by dodona2** [neovim/neovim#5284]
- `nvim --version`: NVIM 0.1.6-dev

- Vim (version: ) behaves differently?

- Operating system/version: mint:17.3
- Terminal name/version:
- `$TERM`: linux

### Actual behaviour
no syntax highlighting in tty terminals (ctrl-alt-fn) when TERM=linux
### Expected behaviour
syntax highlighting in tty terminals (ctrl-alt-fn) when TERM=linux
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
works. However colorscheme is default instead of happy-haping as configired in init.vom
```

**Comment by nhooyr** [comment]
`nvim -u NORC` does not read your init.vim. That is what `NORC` means. This is an issue with your configuration. Bisect your init.vim to find the cause.

**Comment by dodona2** [comment]
well, why does it work fine in a xterm and not in a tty console?

**Comment by fmoralesc** [comment]
The tty console is 8-color only, so nvim might be translating the colors into the reduced palette. See `:help cterm-colors`.

**Comment by dodona2** [comment]
interesting is, that installing vim from git doesn't build a tty trouble binary. Ole vim works out-of-the-box. Therefore it must be a neovim problem.

**Comment by justinmk** [comment]
Vim shows 256 colors in TERM=linux?

**Comment by dodona2** [comment]
don't know if it can display 256 colors. However vim displays happy-hacking color set in a linux tty. I just did a ln -s ~/.config/nvim/init. vim ~/.vimrc. Thats it.

**Comment by justinmk** [comment]
I don't know what happy-hacking color set is, and a web search turns up junk results. So please be less vague.

**Comment by fmoralesc** [comment]
It's
https://github.com/YorickPeterse/happy_hacking.vim/blob/master/colors/happy_hacking.vim

**Comment by justinmk** [comment]
> don't know if it can display 256 colors. However vim displays happy-hacking color set in a linux tty. 

It displays the same colors as in xterm? What does `echo &t_Co` say?

>  I just did a ln -s ~/.config/nvim/init. vim ~/.vimrc. Thats it.

You must also symlink `~/.vim` to `~/.config/nvim`. 

You already mentioned that the default colorscheme works with TERM=linux, so this is a configuration issue, not "syntax highlighting doesn't work". 

While we would like to help with configuration issues, we can't use the issue tracker to do so. Please use http://vi.stackexchange.com/ instead.

If there is a _concrete_, _reliable_, non-regressive change that can be made to nvim to avoid any confusion you ran into, please do describe that change.

It's possible that Vim (or your distro's patched version of Vim) now somehow detects when a TERM=linux tty supports 256 colors. But I'd be surprised.

**Comment by dodona2** [comment]
'You must also symlink ~/.vim to ~/.config/nvim. 
I did that, just because I symlinked /usr/local/share/vim/.../colors to ~/.config/nvim. Without the 'colors' subdir a symlink doesn't make any sense, as I use no plugins etc..
Thus ole vim from git displays happy-hacking color set in a linux tty correctly, whereas neovim unfortunately doesn't. I'm not happy to conclude that.

**Comment by justinmk** [comment]
You have `~/.config/nvim/colors/happyhacking.vim` ? And the colorscheme is loaded, but colors don't display? And 

    :syntax

reports the syntax groups enabled for whatever filetype you've loaded?

Please be more clear in your descriptions.

**Comment by justinmk** [comment]
I tried the colors linked by @fmoralesc . It required putting [this line](https://github.com/YorickPeterse/happy_hacking.vim/blob/master/colors/happy_hacking.vim#L20) at the end. This is a known issue with Vim. 

Then it shows colors, though only 8 colors are used.

I don't know why it works with your Vim without that change, but it's a long-standing known issue with Vim, inherited in Nvim. Without more details about your configuration, we can't guess.
