### ISSUE TITLE
New color group: CurrentSearch

### ISSUE THREAD

**Issue by vaxXxa** [neovim/neovim#5287]
Now we have colorgroup `Search` and can easily change highlight color for search term:
```
hi Search cterm=NONE ctermfg=grey ctermbg=blue
```

But only with that one option really hard to see your current position in all highlighted positions:
![screenshot 2016-09-02 17 38 48](https://cloud.githubusercontent.com/assets/139175/18207547/3b84380c-7134-11e6-99a2-33ec1db21297.png)

Maybe, you can add new color group for current search position? Something like that `CurrentSearch`. So, I will see all yellow highlighted words, and current highlighted red word, for instance.

Make sens?

P.S. I know many workarounds with binding n, N, * to some VimL function, but this approach is not good, cause has many conflicts with nice vim search plugins, like [`henrik/vim-indexed-search`](https://github.com/henrik/vim-indexed-search).

**Comment by vaxXxa** [comment]
I also like idea about counter highlight, like in Sublime Text:
![screenshot 2016-09-02 21 33 35](https://cloud.githubusercontent.com/assets/139175/18214319/051ae240-7155-11e6-8510-d0ac5f9a15c3.png)

**Comment by noahfrederick** [comment]
See existing issue: https://github.com/neovim/neovim/issues/4600

As far as I know, no one has put forth a proposal with [specifics](https://github.com/neovim/neovim/issues/4600#issuecomment-212071784).

**Comment by justinmk** [comment]
In addition to @noahfrederick's comment, can't this already be done via `\%#` and `matchadd()`? That won't conflict with any plugin.

**Comment by davidszotten** [comment]
also interested in this. @justinmk could you possibly elaborate on your suggestion with `\%#` and `matchadd()`?
