### ISSUE TITLE
Neovim throws E41 with getcwd() in non-existent dir

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5291]
When calling `getcwd()` in/for a non-existent directory, Neovim throws `E41: Could not display path.`, while Vim just returns an empty string.

This was introduced in https://github.com/neovim/neovim/commit/ec71d87b8140ae097158f7e219b26701aed8158e.

I've started to add try-catch around it in my vimrc, but then also external plugins like vim-dispatch etc are affected.

I think the behavior should be the same as with Vim.

TEST CASE:

```
1. mkdir /tmp/foo
2. cd /tmp/foo
3. nvim
4. :!rmdir /tmp/foo
5. :echo getcwd()
```

**Comment by justinmk** [comment]
cc @HiPhish

**Comment by HiPhish** [comment]
I'm onto it. This should be a simple one, there is only one line where the error is thrown.

**Comment by HiPhish** [comment]
I got it, now just to write the tests.

**Comment by HiPhish** [comment]
@justinmk I have a problem with writing the test. Here is what I got:

```
-- Test what happens when a directory does not exist
describe('Printing the working directory when it does not exist', function ()
  local temp_dir = 'Xtest-functional-ex_cmds-cd_spec.temp'
  before_each(function()
    clear()
    lfs.mkdir(temp_dir)
  end)

  after_each(function()
    lfs.rmdir(temp_dir)
  end)

  it('returns an empty string', function()
    execute('cd ' .. temp_dir)
    -- lfs.rmdir(temp_dir)
    local working_dir = call('getcwd')
    eq('', working_dir)
  end)
end)
```

Once I uncomment the line `lfs.rmdir(temp_dir)` the test gets stuck indefinitely. And yes, it is this particular test this time. As long as the line is commented the test will continue and of course fail. I don't know what the issue is, because if I try those steps manually in my shell it works without problems:

```
mkdir foo
~/Developer/neovim/build/bin/nvim
# In Neovim press :cd foo/
# In Neovim press C-Z
rmdir foo
fg
# In Neovim press :echo getcwd()
# Get an empty string back with no "press enter" prompt or anything
```

**Comment by HiPhish** [comment]
PR is up at #5292, including the faulty test.
