### ISSUE TITLE
Python provider does not check multiple `python` executables in $PATH

### ISSUE THREAD

**Issue by equalsraf** [neovim/neovim#5293]
Lets say I have two python.exe in my $PATH, one in C:\Python35\python.exe and another in C:\Python27\python.exe. The python provider will only find one but not the other. This happens because the provider uses `exepath()` that only returns the first match found in $PATH.

The issue is not windows specific, but it might be more annoying there because the default instalation of python names the executable python.exe for both python 2 and 3. A quick workaround is to create a link e.g. `mklink python3.exe python.exe` in the python3 instalation directory.

**Comment by justinmk** [comment]
Would this mean iterating through every directory in $PATH?

**Comment by equalsraf** [comment]
> Would this mean iterating through every directory in $PATH?

Yes. A bit harder in Windows (see `is_executable_in_path()`) because it also requires iterating over $PATHEXT.

Perhaps changing `is_executable_in_path` to return a list of paths instead of `abspath`. If performance is a concern, pass in a max paths limit too.

**Comment by justinmk** [comment]
Doesn't python Windows installer add a `py3` alias these days? Iterating through directories seems terribly expensive and prone to bugs and user confusion. And nvim python provider offers g: python_host_prog as well.

**Comment by equalsraf** [comment]
Yes `g: python_host_prog` works around the problem, I mostly added the issue just in case someone was having the same problem.

It also prevents the functional tests from python3 (or 2 depending on $PATH order) from running on windows, unless we either set the option or create the link.

> Iterating through directories seems terribly expensive

`is_executable_in_path()` is already iterating through $PATH, it just stops on the first match.

> and prone to bugs and user confusion.

True. From a cmd line perspective the provider is doing the right thing.

There is a component mentioned in the docs ([section 3.4](https://docs.python.org/3/using/windows.html#python-launcher-for-windows)) that seems to do the trick. Calling `py` runs the python interpreter, the python version can controlled using the environment variable `PY_PYTHON`

Maybe the provider can be changed to use this.

**Comment by justinmk** [comment]
What about py3 ?

**Comment by equalsraf** [comment]
> What about py3 ?

Cannot find it in my system, maybe its an install option.

**Comment by justinmk** [comment]
Won't `pip` have the same problem as this? Then we would also need to explain to the user how to install the `neovim` python module to the correct "site". So I am wondering how many people will be helped by this, or if it will just cause more/different support burden.

We'll be going to a lot of trouble to support python's brain damage. As well as violating basic assumptions about PATH searching conventions.

> It also prevents the functional tests from python3 (or 2 depending on $PATH order) from running on windows, unless we either set the option or create the link.

Is it not reasonable/possible to create a link (or set `g:python_host_prog`) on appveyor? If this is for local dev, wouldn't just having one or the other typically be good enough?

**Comment by equalsraf** [comment]
> Won't pip have the same problem as this?

Surprisingly there is a pip2 and pip3.exe.

Lets leave it as is then. Its enough that this is captured as an issue. Found an issue upstream - https://bugs.python.org/issue21506 - maybe it gets fixed for the python 3.6 installer.

> Is it not reasonable/possible to create a link (or set g:python_host_prog) on appveyor?

I'll figure out something for Appveyor later. Apparently you can just copy the binary around :D https://github.com/mesonbuild/meson/blob/master/.appveyor.yml#L16

**Comment by justinmk** [comment]
> Apparently you can just copy the binary around

In fact, the python dev recommends that and may use that to solve the installer issue:

https://bugs.python.org/issue21506#msg251820
