### ISSUE TITLE
Poor performance with termguicolors and spell

### ISSUE THREAD

**Issue by landaire** [neovim/neovim#5294]
- `nvim --version`: 

```
NVIM v0.1.6-51-g0253766
Build type: Dev
```
- Vim (version: ) behaves differently?

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep  2 2016 17:55:49)
```

**Yes**, vim behaves differently.
- Operating system/version: macOS 10.12 Beta (16A313a)
- Terminal name/version: iTerm2 `Build 3.0.20160823-nightly`
- `$TERM`: `xterm256-color`
### Actual behaviour

When `termguicolors` and `spell` are both set, nvim will lag when moving lines in long files with lots of misspelled words.
### Expected behaviour

nvim should not lag.
### Steps to reproduce using `nvim -u init.vim`

Download the sample file: [profile.txt](https://github.com/neovim/neovim/files/454124/profile.txt)

init.vim:

```
set nocompatible

" Show the line number (hard to notice the lag without it)
set number
set relativenumber

" Enable spellcheck
setlocal spell spelllang=en_us

" Enable truecolor support
set termguicolors
```

```
nvim -u init.vim profile.txt

```

Jump to the end of file (`G`) and move the cursor around. You should notice the line number on the left doesn't update immediately when you press j/k.

Now comment either the `setlocal spell` line or `set termguicolors` (either one) and you should no longer notice the lag. @justinmk and I were discussing it in gitter and [he suggested that it could be because in truecolor mode neovim uses an underline for misspelled words, whereas out of truecolor mode it highlights the word](https://gitter.im/neovim/neovim?at=57cc93ec29ee4a67058f4ebb). This would make sense because vim does **not** replicate this behavior (at least on my machine).

**Comment by justinmk** [comment]
Nothing we can do about this. Use a faster terminal.

**Comment by hrqmonteiro** [comment]
Same thing here. I use the fastest terminal (alacritty) and if i set "termguicolors" vim is unusable. Is literally the slowest and glitchiest thing when moving lines. Don't know what to do.
