### ISSUE TITLE
create variables for the neovim config and data directories

### ISSUE THREAD

**Issue by docwhat** [neovim/neovim#5297]
I applaud the change to using the `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` variables for storing data, etc.

However, calculating those values in a cross platform way is complicated.

The best work around I have for the `~/.config/nvim` directory is `let g:my_nvim_dir = fnamemodify(expand('<sfile>'), ':p:h')` from the `init.vim`.

I have no idea about calculating the data home, short of a sequence of if statements.

It would be nice to have something like `g:neovim_config_dir` and `g:neovim_data_dir` as variables that scripts, plugins, etc. could use.

**Comment by ZyX-I** [comment]
These should be function used like `xdg_dirs('DATA_DIRS')` that returns a list: used directories depend on environment variables which may be modified in VimL.

**Comment by justinmk** [comment]
I suggest `base_dirs()` or `get_config_paths()` or some other more generic name. XDG is too obscure for most users, and we may want this function to return paths to sub-directories and file paths that are not precisely XDG-related, e.g. the path to the rplugin file.

**Comment by fwalch** [comment]
This should be relatively easy to implement, I think? Added `entry-level` tag; feel free to remove if you disagree.

**Comment by Lakshya1605** [comment]
I would like to work on this. It might take a little time, though. I am new here.Please can someone get me started

**Comment by justinmk** [comment]
@Lakshya1605 we are happy to help with specific questions. See CONTRIBUTING.md for general introduction.

**Comment by phmarek** [comment]
I'm running with the (IRC-provided) line in my `init.vim`
```
let $VIMUSERRUNTIME = fnamemodify($MYVIMRC, ':p:h')
```

**Comment by docwhat** [comment]
Just a summary of the info on the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html):

* `XDG_CONFIG_HOME` is a single directory for configuration files (write).
* `XDG_DATA_HOME` is a single directory for user data (write).
* `XDG_CACHE_HOME` is a single directory for cache (non-essential) data (read/write).
* `XDG_RUNTIME_DIR` is a single directory for runtime (sockets, pidfiles, locks) files (read/write).
* `XDG_CONFIG_DIRS` is a `:` separated list for reading configs, with decreasing importance. `XDG_CONFIG_HOME` is always considered first. (read)
* `XDG_DATA_DIRS` is a `:` separated list for reading data, with decreasing importance. `XDG_DATA_HOME` is always considered first. (read)

**Comment by ZyX-I** [comment]
List is easier to work with. What is “(read)”/etc in your message? If I understand this right, then all “(write)” are “(read/write)” at best and specifically XDG_CONFIG_HOME is better considered “(read)”: you should not be writing anything to user configuration directory, with exceptions like `:mkvimrc` which generate configuration files at user request: though creating default/template configuration if it does not exist is not uncommon, Neovim does not do this without explicit request.

BTW, do you know that if in zsh you add a directory with colon to `$path` (array bound to `$PATH`) you will be able to run executables from there, even though this is not going to work with `$PATH` (string, colon-separated “list”). Do not think this is commonly used though, `$path` will not contain the new addition in one piece even in a spawned zsh (e.g. like running `zsh -c 'echo $path'`, as opposed to using subshells with `$(command)` or `(command)`).

**Comment by docwhat** [comment]
I'm a rusty C coder, but I threw together a patch in #6272 that adds just `get_xdg_home()`.  I figured a second method could be added for the lists (dirs): `get_xdg_dirs()`.

This lines up nicely with the stuff in `stdpaths.c`

The "read" and "write" was just me summarizing the XDG documentation.  The documentation for `XDG_CONFIG_HOME` is:

> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.

Re: Zsh -- Yup, I use `$path` and `$fpath` to manage my paths in my startup scripts and then use `typeset -xU fpath path` to make them unique and export. https://github.com/docwhat/dotfiles

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/5297#issuecomment-244797635

**Comment by docwhat** [comment]
How about `get_config_path()` and`get_data_path()`?

I can drop the `XDG_CACHE_HOME` variable.  That way these match `stdpaths_user_conf_subpath()` and `stdpaths_user_data_subpath()`

**Comment by justinmk** [comment]
Why not a single function, `stdpath({what})`? The `{what}` argument determines what path is returned. We may add more in the future.

**Comment by docwhat** [comment]
I like `stdpath()`.  I'm not familiar enough with Vim docs (I mean, I read them, but not enough to catch on to any official conventions).  Should the docs use `{what}` or `{string}`? (My current RFC PR uses `{string}`)

**Comment by justinmk** [comment]
> Should the docs use {what} or {string}? (My current RFC PR uses {string})

It should be like an argument name, rather than the argument type. `{what}` is common, maybe `{type}` is better.
