### ISSUE TITLE
Suggestion for a new name

### ISSUE THREAD

**Issue by freeasinbear** [neovim/neovim#5303]
Hi,

I don't want to pretend you to take this too seriously, because I understand that even if you would like the idea, you would lose all the visibility previously gained with the name neovim, but I thought a cool name that might interest you:

VIMP: Vi IMproved, IMProved 
or also
Vi IMP, IMP as imp, also synonymous of small agile (also a funny counterpart for "nano")

I also think the pronunce sounds better for the tongue.
What do you think?

**Comment by jszakmeister** [comment]
See #272.  It's been discussed before, and it's not going to happen.
