### ISSUE TITLE
Terminal split and relativenumber cuts off the end of lines

### ISSUE THREAD

**Issue by tecywiz121** [neovim/neovim#5310]
- `nvim --version`: NVIM 0.1.6-dev
- Operating system/version: Ubuntu 14.04.4 LTS
- Terminal name/version: GNOME Terminal 3.6.2
- `$TERM`: xterm-256color
### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/135535/18317545/875b7392-74ec-11e6-9cde-c6dfa1602694.png)
### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/135535/18317566/98e3a206-74ec-11e6-95b1-112ece87371d.png)
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:vsplit
<C-w>r
:terminal
<C-\><C-n>
:set relativenumber
i
123456789
<C-\><C-n>
:set norelativenumber
```

Depending on the width of your screen and length of your prompt, some of the 1-9 numbers will be missing with relativenumber turned on, and show up when relativenumber is turned off.

**Comment by nhooyr** [comment]
Confirmed here. Looks like the width of the screen is being calculated incorrectly.

**Comment by nhooyr** [comment]
This also happens with `:set number`.

**Comment by cybogado** [comment]
I'm seeing a similar issue that manifests it self only when a tmux panel is not 100% height of the window.

the following "render" show a session of neovim in a "10x175" tmux pane with a new file.

```
1  _
~
~
~
~
~
~
~
[No Name] ... status bar

```

After pressing <CR> 8 times in insert mode :

```
 7654321 1
 654321 2
 54321 3
 4321 4
 321 5
 21 6
 1 7
8  _
[No Name] ... status bar

```

**Comment by cybogado** [comment]
I've checked "winheight", "winwidth", "screencol" and "screenrow" and they seem to be sane.

**Comment by cybogado** [comment]
I've also used : 
``` bash
$ echo -en "\e[18t"
```

to check the reported size of the window and it seemed legit.

**Comment by cybogado** [comment]
Updating to "HEAD" on brew made the problem go away.

**Comment by nhooyr** [comment]
Not for me, I'm running latest master and I can reproduce.

**Comment by tecywiz121** [comment]
Including the commit hash would probably be useful to know if/when it was resolved, if either of you have it handy.

**Comment by nhooyr** [comment]
I was able to reproduce with at least 13db9236fe5ec5cd69ac8aa80b5adcc3db842cbe

**Comment by tecywiz121** [comment]
Still happening in b630074

**Comment by justinmk** [comment]
Patch welcome.
