### ISSUE TITLE
[bug]  paste is disfigured in visual block mode when clipboard has unnamed set

### ISSUE THREAD

**Issue by ninrod** [neovim/neovim#5311]
- `nvim --version`: NVIM v0.1.6-72-gfe06e2a (GIT HEAD as of 2016.09.07)
- Vim (version: 7.4 patchlevel 2342 - GIT HEAD) behaves differently? yes. vim works as expected.
- Operating system/version: OSx
- Terminal name/version: iterm2
- `$TERM`: xterm256-color

### Actual behaviour
an yanked block from a visual block selection 
is disfigured when user pastes the same block over another visual block selection when clipboard has `unnamed or unnamedplus` among its configurations. 

### Expected behaviour
paste functions as expected

### Steps to reproduce using `nvim -u NORC`

- setup

```viml
nvim -u NORC
:set clipboard+=unnamed
```
- sample buffer

```txt
1 1 
1 1 

z a b
z c d
```

0. yank operation: visually block select the `1 1 1 1` square, then yank.
0. select operation: visually select the `a b c d` square. now paste.

expected result:

```txt
1 1 
1 1 

z 1 1
z 1 1 
```

actual disfigured result:

```txt
1 1
1 1

z 
z 
1 1
1 1
```

**Comment by justinmk** [comment]
I believe this is a known issue.

**Comment by ninrod** [comment]
Oh. So it is a duplicate?

**Comment by justinmk** [comment]
Yes

**Comment by bfredl** [comment]
See issue #1822 

I hope resurrect #4523 soon and add modularization, so that someone else can fill in the macOS part...

Until then https://github.com/neovim/neovim/issues/1822#issuecomment-233152833 might work on OS X as well.
