### ISSUE TITLE
Error when compiling neovim on Windows using MinGW

### ISSUE THREAD

**Issue by andalou** [neovim/neovim#5313]
I'm compiling neovim on Windows 7 with MinGW. I did:

mkdir build-deps
cd build-deps
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=C:/progs/nvim ..\third-party

and I got:

<hr/>
[...]
process_begin: CreateProcess(NULL, cc -Wall -Wextra -Wno-unused-parameter -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 -c -o src/fs-poll.o src/fs-poll.c, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile.mingw:84: recipe for target 'src/fs-poll.o' failed
mingw32-make[3]: *** [src/fs-poll.o] Error 2
CMakeFiles\libuv.dir\build.make:112: recipe for target 'build/src/libuv-stamp/libuv-build' failed
mingw32-make[2]: *** [build/src/libuv-stamp/libuv-build] Error 2
CMakeFiles\Makefile2:205: recipe for target 'CMakeFiles/libuv.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/libuv.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
<hr/>

I noticed that the file 'build-deps\build\src\libuv\Makefile.mingw'
contains 'CC ?= gcc'. I think it should be 'CC = gcc'.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by fwalch** [comment]
FWIW, [here](https://github.com/neovim/neovim/blob/master/.ci/build.bat) is how Neovim is (successfully) built on AppVeyor with MinGW.

**Comment by brcolow** [comment]
Ping @equalsraf

**Comment by equalsraf** [comment]
Try this in your console before calling cmake, you might want to clean the build deps first

```
set CC=gcc
```

Unrelated but you can also use `-DDEPS_PREFIX=C:/progs/nvim ..\third-party\usr` instead of CMAKE_INSTALL_PREFIX.
