### ISSUE TITLE
Codestyle wiki Link is unreadable in firefox 48.0.1

### ISSUE THREAD

**Issue by toogley** [neovim/neovim#5317]
The [Codestyle Link](https://neovim.io/develop/style-guide.xml) inside [this overview wiki page](https://github.com/neovim/neovim/wiki) is very hard to read, as it isn't formatted in my browser (Mozilla Firefox 48.0.1)

![2016-09-10-003907_1177x879_scrot](https://cloud.githubusercontent.com/assets/9417950/18405065/1eaf4cf6-76ef-11e6-88a4-d53e67ddc61e.png)

-----------------

However, if i try to paste sth from this xml file, the formatting seems correct, as expected:

```
for (int i = 0; i < 3; i++) { }
        int j = ++i;  // OK: ++i is used as an expression.
      
      
        for (int i = 0; i < 3; ++i) { }
        ++i;  // BAD: ++i is used as a statement.

```

**Comment by brcolow** [comment]
Could not reproduce on Windows 10 with Firefox versions:

43.0.1
47.0
47.0.1

I can't seem to upgrade past 47.0.1...perhaps I am not on the same release channel? Btw, what OS did this happen on? Looks *nixy to me.

**Comment by toogley** [comment]
@brcolow I use fedora 24.

**Comment by toogley** [comment]
Ah, i found the issue. I just had forgotten to enable scripts on that site...

=> works.
