### ISSUE TITLE
Make sure each header can be included separately

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#5321]
Currently some headers have implicit dependencies which are not caught right there because this header happened to be included after some other header. Generally this problem could’ve been solved by setting up IWYU as proposed in #549, but this is rather hard. Commit https://github.com/ZyX-I/neovim/commit/ab026c76812f0c520825c0b3e3e4518b1d40083c (note: will be replaced in the future due to probable rebasing and squashing with some `fixup!` commits) implements much easier test that just checks that code like

```
#include "{Neovim header}"
int main(int argc, char **argv) { return 0; }
```

compiles and currently there are lots of headers which fail this test (at that point there were 47 of them). Fixing this problem should be relatively easy, so I am opening this entry-level issue.

**Comment by iamvoid13** [comment]
Hey ZyX-I, I want to work on this issue.

**Comment by j3by** [comment]
Hey, I'm not sure if this helps but I think you spelt "BUILD" wrong in test.sh line 78.

**Comment by vyasgiridhar** [comment]
Can you point me to some example file? It would be difficult to comb through all those files.

**Comment by Riyuzakii** [comment]
@ZyX-I I am a first-timer and i would like to try and fix this issue, could you direct me to the files that need to be changed.

**Comment by justinmk** [comment]
So the task here is:

1. pick an item from the `NO_SINGLE_CHECK_HEADERS` list in `src/nvim/CMakeLists.txt`. 
2. Remove that item.
3. Run `make check-single-includes`
4. Fix the includes so that `make check-single-includes` passes.

**Comment by samjjc** [comment]
hey, you mind if i work on this one, (first time contributing to open source)

**Comment by justinmk** [comment]
Just send a PR.

**Comment by dedmass** [comment]
Quick question since this is my first time contributing to a large project like this.
Example:
`hardcopy.h` needs `exarg_T` from `nvim/ex_cmds_defs.h` and also needs `char_u` from `nvim/types.h` (which is eventually included in `nvim/ex_cmds_defs.h`). Is it preferable to include both headers for robustness or is it fine to simply include the single header `nvim/ex_cmds_defs.h`?

**Comment by justinmk** [comment]
Both. Because the final goal is "include what you use".

**Comment by dedmass** [comment]
Okay I'll go back and double check all of those then.

**Comment by justinmk** [comment]
It's not super important for this phase to do that, but since you asked I mention it.

**Comment by dedmass** [comment]
Yeah it's not hard to do so I'll try to take care of it as I go.

**Comment by ZyX-I** [comment]
You may find yourself in a situation where you need to introduce a dependency cycle (which obviously won’t work), leave header be imlicitly dependending on inclusion some other header first (basically what check-single-includes is against) or split up header into header.h and header_defs.h. Feel free to do the latter, but note #6371: it is preferred to follow advices from there (functions, enum constants, more docs, etc). At this stage “headers must include only `…_defs.h`” is not relevant.

**Comment by dedmass** [comment]
Is there a recommended way to include `size_t`?

**Comment by FlorianGit** [comment]
Hey, I thought this would be a good first issue to pick up and focussed on create a pull request asap to avoid double work. However, soon after I realised that with my linux machine I won't be able to check the win_defs header. So it is still up for the taking.
I tried to clean up as good as possible (close pull request, remove branch), but if there's more I can do, please let me know.

**Comment by justinmk** [comment]
The Windows specific headers should still be fixed, but this issue doesn't need to remain open. 99% of the work was done.
