### ISSUE TITLE
automate fixing the ctrl-h mapping issue

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5322]
This frequently pops up on the communication platforms neovim uses (gitter/irc/reddit) where someone doesn't understand why their ctrl-h mapping doesn't work. We always link them to the FAQ which explains why and how to fix but I think that maybe we should include a fix for this by default. It would make neovim work with less problems and I can't see much reason to oppose it (maybe the argument that neovim shouldn't mess with a system level file, but I think that anything that makes switching from vim to neovim smoother for new users is a priority).

At least until the terminal library that neovim uses (libtermkey?) is patched with a fix.

So we check their `$TERM` entry's description and if the `key_backspace` description is incorrect, we fix it and then begin to use libtermkey.

**Comment by justinmk** [comment]
@leonerd Has a perl script to do this, but I'm not sure if it was "shippable". Perhaps he could post it and someone could polish it.

Other option is to fork and inline libtermkey, adding the termios fallback. It's end-of-life so forking it wouldn't be any trouble for us, and it's relatively small at ~3k LOC.

@leonerd, what is the status of merging libtermkey to libtickit?

**Comment by nhooyr** [comment]
Inlining it doesn't sound too hard so if we do go with that, I think I can do it.

**Comment by justinmk** [comment]
Ok, might want to get other opinions before moving forward on that :>

**Comment by leonerd** [comment]
@justinmk I haven't started it yet. When I do, it might take an hour, or it might take three weeks, or anything inbetween. I'm not sure though in the short-term how that will help you - I didn't think neovim was able to use libtickit directly yet for a number of missing features; gathered up in my "v0.3 milestone" on LP.

**Comment by leonerd** [comment]
As to asking termios - ultimately you're just trading one problem for another. Who's to say termios is any more correct about that than terminfo is?

Ultimately that was the reason for my terminfo-fixing script. Rather than trying to query bits of state on the wrong machine to ask what the backspace key would send if the user would press it, just ask the user to *actually* press that key and record what byte it *actually* sends. Then you are *guaranteed* to be correct with no further guesswork.

Can neovim just do that?

User types 

  :fixbackspace

Neovim prints "OK, please press the Backspace key". User does so. We record the byte and remember that forever more for this terminal.

Done.

**Comment by justinmk** [comment]
@leonerd You had a script hacked up to do that, right? Can you post it somewhere?

**Comment by nhooyr** [comment]
Though that is a nice solution, it'd be nice if it was automatic and required zero user intervention. We're still gonna get people confused until they read the FAQ or ask on IRC and then we direct them to the command.

**Comment by bfredl** [comment]
Which makes me curious, is there some terminal (that people actually use) where DEL (127) means something else than backspace? I e, is the presence of DEL on stdin enough to conclude it means backspace (so ctrl-h means ctrl-h) ?

**Comment by nhooyr** [comment]
And even then, most people will consider it terminal magic because they won't understand what's going on and why they need to do this. Very few people want to read up on why, they just want it to work.

**Comment by leonerd** [comment]
@nhooyr It can't be "automatic without user intervention". This is the entire problem. Since databases **are known to lie**, the only way to find out what byte the backspace key sends when it is pressed is to ask the user to press it and find out which byte that is.

I hate this situation as much as you; but short of going around all the OS vendors and banging their heads together until the databases definitely don't lie, this is the only other way I know of out of the problem.

**Comment by leonerd** [comment]
@bfredl I don't see how we'd make use of that information. It is awkwardly sequenced. *After* we see a DEL byte, we can conclude that's the backspace key and so if we see a literal BS byte from here on, we know it must be a real <key>Ctrl-H</key>. But until we've seen that byte, we can't know. If the BS byte arrives first, which is it?

**Comment by leonerd** [comment]
@justinmk If you really want it, find a copy http://paste.debian.net/818943/

Feel free to hack/adjust/polish/repackage, whatever.

**Comment by bfredl** [comment]
Do we even really need this information so desperately? Couldn't a literal Ctrl-h  just trigger the `<c-h>` mapping if it exists and if it doesn't exist the `<bs>` mapping? (non-remapped they do the same in all modes, right?) DEL will always trigger `<bs>` mapping then, if DEL don't mean anything else (again, in terminals that people actually use).

**Comment by leonerd** [comment]
@bfredl That's a little fragile but I don't really see why not. It's reasonably pragmatic and probably satisfies most people. Remains to be seen in practice if the differing behaviours in the two cases would end up confusing more people anyway though

**Comment by bfredl** [comment]
Yes, it could be confusing in a terminal where BS=ctrl-h, but in general I think users possibly needing adjusting or add a `:[nore]map` command (which is the command one would expect to use to modify the meaning of keys) will be less confusing, than being told to run a command to fix some database that apparently neovim insists relying on even if they know it's broken.

**Comment by justinmk** [comment]
:+1:

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/5693 will bring us on par with Vim, so this issue isn't likely to get attention. Though such a utility would still be welcome.

**Comment by nhooyr** [comment]
Ctrl-H mappings still don't work outside of the box for me. I'm using latest neovim from master.

**Comment by justinmk** [comment]
@nhooyr Please run a Debug build and check `~/.nvimlog`, you should see lines like this:

```
2017/01/04 04:39:35 INFO  27319/tui_tk_ti_getstr:999: libtermkey:kbs=^H                                                      
2017/01/04 04:39:35 INFO  27319/tui_tk_ti_getstr:1004: libtermkey:kdch1=^[[3~
```

What does it say in your case? Also:

    stty -a | grep erase

**Comment by nhooyr** [comment]
I'll run a debug build, sec.

https://gist.github.com/627d0bb5b05dca8a6785a5596014a5dc

**Comment by justinmk** [comment]
> Ctrl-H mappings still don't work 

Just to be clear, what happens with these mappings:

```
:nn <bs> :echo "bs"<cr>
:nn <c-h> :echo "ch"<cr>
```

**Comment by nhooyr** [comment]
bs is printed.

**Comment by nhooyr** [comment]
@justinmk dammit, i can't seem to build. I get https://gist.github.com/134259a8f9824dfa7953fcd82211cc48

this is after all the deps and what not have been downloaded.

**Comment by justinmk** [comment]
@nhooyr After that change, to build locally a `rm -rf build .deps` was needed, else a similar build error would happen. It sounds like your nvim is using an older libtermkey (which is still supported, if the newer one isn't available).

**Comment by nhooyr** [comment]
@justinmk that was a fresh clone. This was happening before too, I asked on the gitter but I didn't end up solving it.

**Comment by nhooyr** [comment]
Sorry, here is the proper full error: https://gist.github.com/1daee7488f2a7214165b8dbb7253e289

**Comment by justinmk** [comment]
Regarding the original question: are you sure the nix package, or whatever you were running, is running libtermkey 0.19?

**Comment by nhooyr** [comment]
aha, that's it https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/libraries/libtermkey/default.nix

I'll update it thanks!

But for the build issue, any ideas?

**Comment by nhooyr** [comment]
Works perfectly now 👍
