### ISSUE TITLE
slow to retrieve v:oldfiles

### ISSUE THREAD

**Issue by haifengkao** [neovim/neovim#5323]
- `nvim --version`: NVIM v0.1.5
- Vim (version: ) behaves differently? N/A
- Operating system/version: OSX 10.11
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

I am trying to improve the performance of [nfasd](https://github.com/haifengkao/nfasd).
The recent files are retrieved with the following python script
``` python
    nvim = attach('child', argv=["nvim", "--embed"])
    nvim.command('let nfasd_history = v:oldfiles')
    history = nvim.vars['nfasd_history']
```

### Actual behaviour
`nvim.command('let nfasd_history = v:oldfiles')` takes 0.5~1 secs to finish

### Expected behaviour
`nvim.command('let nfasd_history = v:oldfiles')` should take less than 0.2 secs

It takes less than 1ms to retrieve the variable value `history = nvim.vars['nfasd_history']`.
Why does it take so long to execute `let nfasd_history = v:oldfiles`?

**Comment by justinmk** [comment]
What happens if you just do

    history = nvim.vars['v:oldfiles']

**Comment by justinmk** [comment]
Can't reproduce, it's instantaneous for me with a large shada file. Can you check your neovim python module version? Please run `:CheckHealth`.

**Comment by ZyX-I** [comment]
@justinmk `nvim.vars['v:oldfiles']` must not work. If it works (does not work for me), it is a bug. To retrieve `v:` variable one should use `nvim.vvars['oldfiles']`.

**Comment by ZyX-I** [comment]
@haifengkao Most performant solution is to parse ShaDa file directly, unlike viminfo ShaDa format is documented and is considered to be a part of the API. `nvim.command` will finish executing only after vimrc, plugins, VimEnter autocommands, etc have been parsed, so 0.5~1 seconds to finish may be fine depending on user configuration. Performance should be partially increased when nvim is run with `--noplugin`.

The only problem with ShaDa parsing should be determining where ShaDa file is located given that user may specify other location: you may need another command-line option, configuration setting or something like this.

**Comment by ZyX-I** [comment]
Regarding `--noplugin`: do not forget that plugins may also alter ShaDa file location (“plugin” in a sense “\*.vim file located in {rtp_dir}/plugin directory or one of its sub(sub)\*directories”, it may actually be some user file).

**Comment by ZyX-I** [comment]
@justinmk You should be able to reproduce this by putting `sleep 1` into vimrc. And I see why `nvim.vvars` *must not* be used: variables are queried during `sleep`, so you have good chances to get nothing (better reproducible with `sleep 10`).

No, actually not: this hack with `command` can neither succeed to neutralize the sleep, so it appears that `nvim.command` does not wait for initialization to finish and @haifengkao should use something different. Though with `sleep 10` even using `nvim.feedkeys(':let…\n', 'n')` does not work. I can only imagine `nvim.feedkeys` (it is executed after sleep) and a cycle which periodically queries `nvim.vars['nfasd_history']` until it does not result in a KeyError.

**Comment by haifengkao** [comment]
@justinmk  oops. I didn't log in github for almost a week. Guilty as charged :(
`history = nvim.vars['nfasd_history']` is less than 2ms.

@ZyX-I You are right. `history = nvim.vars['v:oldfiles']` doesn't work. 
Your answer does make sense. It's possible that I have to wait for the nvim to finish initialization.

`where ShaDa file is located given that user may specify other location` 
You are also right about it. In `nfasd` 0.12, I have switched nfasd to parse ShaDa in the default location directly. However, if the user changed the ShaDa to some other locations, I cannot know it in advance, because it still takes 0.5 ~ 1 secs to get current ShaDa location.

Do you have any better solutions?
