### ISSUE TITLE
libtermkey state

### ISSUE THREAD

**Issue by glensc** [neovim/neovim#5340]
[sorry to write here, but neovim/libtermkey project has no Issues enabled]

i noticed http://www.leonerd.org.uk/code/libtermkey/ says :
> Note: This project is now DEAD; end-of-life. There will likely be no further releases.
> 
> All of the code will be migrated into libtickit instead. libtermkey should not be used for new programs; use libtickit.

is there plans to switch to [libtickit](http://www.leonerd.org.uk/code/libtickit/) instead?

if not, could you enable project management (issues) in your fork:
https://github.com/neovim/libtermkey/

and make some kind of release (git tag)

and actually say it's continuation or fork, not mirror

i ask this as i'm packaging neovim for a linux distro

**Comment by fwalch** [comment]
> is there plans to switch to libtickit instead?

That's the general idea, but there are no concrete plans. I assume it will be a long time before that happens.

> i ask this as i'm packaging neovim for a linux distro

You can just package libtermkey 0.18, as [Arch](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libtermkey) or [Debian](https://packages.debian.org/sid/libtermkey1) did.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/3991#issuecomment-170946627

Thanks for looking out though.
