### ISSUE TITLE
Conceal(level/cursor) breaks mouse selection with unicode chars

### ISSUE THREAD

**Issue by DarkDefender** [neovim/neovim#5341]
- `nvim --version`:
  `NVIM v0.1.6-100-gfee961c
  Build type: RelWithDebInfo`
- Vim (version: ) behaves differently?
  Vim 7.4.769 doesn't seem to have this problem (haven't tried any newer versions)
- Operating system/version:
  Gentoo
- Terminal name/version:
  Urxvt 
- `$TERM`:
  rxvt-unicode-256color
### Actual behaviour

When using `set conceallevel=2 concealcursor=niv` the mouse cursor selects text with a huge offset, if the line you try to select has unicode chars. For example:

```
  ᾗ ᾘ ᾙ ᾚ ᾛ ᾜ ᾝ ᾞ ᾟ ᾠ ᾡ ᾢ ᾣ ᾤ ᾥ ᾦ ᾧ ᾨ ᾩ ᾪ ᾫ ᾬ ᾭ ᾮ ᾯ ᾰ ᾱ ᾲ ᾳ ᾴ ᾶ ᾷ Ᾰ Ᾱ Ὰ Ά ᾼ ᾽ ι ᾿
                    ^                              ^
        (Click to select here)                    (The column that gets selected instead)

```
### Expected behaviour

The correct text column should be selected regardless of conceal settings
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set conceallevel=2 concealcursor=niv 
```

**Comment by justinmk** [comment]
cc @tweekmonster

**Comment by justinmk** [comment]
@DarkDefender could you try reverting https://github.com/neovim/neovim/pull/5087

**Comment by DarkDefender** [comment]
@justinmk reverting #5087 fixes the problem, yes.

**Comment by justinmk** [comment]
Maybe the [STRLEN call](https://github.com/neovim/neovim/pull/5087/files#diff-6150092d3aedd06ecc90a9fc24de2892R615) just needs to be fixed.

**Comment by jamessan** [comment]
Should that `STRLEN` be `mb_string2cells` instead?

**Comment by tweekmonster** [comment]
> Should that STRLEN be mb_string2cells instead?

Actually, I should've used `scroll_line_len()` since it accounts for tabs.  But, I think I pointer arithmetic is needed with `mb_ptr_adv()` and `mb_ptr_back()` instead of using an char increments.

**Comment by tcbbd** [comment]
Found the same problem with Chinese text, any progress?

**Comment by justinmk** [comment]
No progress. Someone needs to carry https://github.com/neovim/neovim/issues/5341#issuecomment-247825900 forward.

**Comment by tweekmonster** [comment]
I think I just figured this out.  I'll update #5822 sometime today.
