### ISSUE TITLE
Generating nvim.pot

### ISSUE THREAD

**Issue by shitfSign** [neovim/neovim#5342]
os           :  win7-64 
platform : msys2 mingw64

CMake Error at F:/CProject/neovim/cmake/RunXgettext.cmake:4 (list):
  list sub-command SORT requires list to be present.
src\nvim\po\CMakeFiles\translations.dir\build.make:378: recipe for target 'src/nvim/po/nvim.pot' failed
mingw32-make.exe[2]: **\* [src/nvim/po/nvim.pot] Error 1
CMakeFiles\Makefile2:1230: recipe for target 'src/nvim/po/CMakeFiles/translations.dir/all' failed
mingw32-make.exe[1]: **\* [src/nvim/po/CMakeFiles/translations.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make.exe: **\* [all] Error 2

I do not know what the problem is not dependent loss.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/blob/master/.ci/build.bat#L20 for hints on how we build on appveyor (a Wndows environment).

Perhaps we should add a msys2 section to https://github.com/neovim/neovim/wiki/Building-Neovim 

cc @equalsraf

**Comment by equalsraf** [comment]
> Perhaps we should add a msys2 section to https://github.com/neovim/neovim/wiki/Building-Neovim 

We definitely should, there is a point about this and some notes in https://github.com/neovim/neovim/issues/5229. I've been holding off on it until we clarified a few other points. But it wouldn't hurt.

It seems the build is having issues when executing `xgettext` to generate nvim.pot.

```
CMake Error at F:/CProject/neovim/cmake/RunXgettext.cmake:4 (list):
list sub-command SORT requires list to be present.
```

It seems the variable holding the list could be empty.

@shitfSign can we get a full log, preferably with `mingw32-make VERBOSE=1`?

**Comment by shitfSign** [comment]
@equalsraf 
where a full log?

**Comment by equalsraf** [comment]
> where a full log? 

I meant the complete output when you call mingw32-make.

I think this is also saved in build/CMakeFiles/CMakeOutput.log and build/CMakeFiles/CMakeError.log

**Comment by shitfSign** [comment]
@equalsraf


[1.txt](https://github.com/neovim/neovim/files/474556/1.txt)
[CMakeError.txt](https://github.com/neovim/neovim/files/474564/CMakeError.txt)
[CMakeOutput.txt](https://github.com/neovim/neovim/files/474559/CMakeOutput.txt)

**Comment by 0017031** [comment]
I've had same problem as @shitfSign .
The root cause is that windows-command-line can't take the single-quote. 
At  neovim\src\nvim\po\CMakeLists.txt , around line 51

`  add_custom_command(
    OUTPUT nvim.pot
    COMMAND ${CMAKE_COMMAND}
        -DXGETTEXT_PRG=${XGETTEXT_PRG}
        -DPOT_FILE=${NVIM_POT}
        -DSEARCH_DIR=${CMAKE_CURRENT_SOURCE_DIR}
        "'-DSOURCES=${NEOVIM_RELATIVE_SOURCES}'"
        -P ${PROJECT_SOURCE_DIR}/cmake/RunXgettext.cmake
    DEPENDS ${NEOVIM_SOURCES})`

**Comment by justinmk** [comment]
@0017031 would you mind sending a PR?

**Comment by 0017031** [comment]
@justinmk  : Let me try, but I'm new to here and not familiar with the PR format.

**Comment by justinmk** [comment]
@0017031 Does [this change](https://github.com/neovim/neovim/pull/5620/files) fix the issue for you if you apply it locally?
