### ISSUE TITLE
Not linking against libiconv

### ISSUE THREAD

**Issue by jerowe** [neovim/neovim#5346]
- `nvim --version`: 0.1.5
- Vim (version: ) 7.4 behaves differently?
- Operating system/version: Linux version 3.10.0-327.10.1.el7.x86_64 
- Terminal name/version: Guake
- `$TERM`: xterm-256color

I'm trying to install neovim on a server where I don't have root access. My build tools (cmake, autconf, automake, libtool, and libiconv) are from an anaconda environment from the  [conda-forge](https://github.com/conda-forge/)

I'm also trying to build a conda package of neovim on a docker image, which is getting different errors and I will raise another ticket for that. ;-) It would make me so happy to have this installed as a part of my dev images!

### Actual behaviour
```bash
> LD_LIBRARY_PATH="/path/to/env/lib" make
> LD_LIBRARY_PATH="/path/to/env/lib" make install
> ldd `which nvim`
        
linux-vdso.so.1 =>  (0x00007ffc075d9000)
 **libiconv.so.2 => not found**
 librt.so.1 => /lib64/librt.so.1 (0x00007f18c236d000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f18c2151000)
 libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f18c1f38000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00007f18c1d33000)
 libm.so.6 => /lib64/libm.so.6 (0x00007f18c1a31000)
 libutil.so.1 => /lib64/libutil.so.1 (0x00007f18c182e000)
 libc.so.6 => /lib64/libc.so.6 (0x00007f18c146c000)
 /lib64/ld-linux-x86-64.so.2 (0x00007f18c2584000)
> LD_LIBRARY_PATH="/path/to/env/lib" nvim --version
(is fine)
```
### Expected behaviour
>nvim --version

### Steps to reproduce using `nvim -u NORC`
What is this?

```
nvim -u NORC

```

**Comment by jszakmeister** [comment]
That looks to me like libiconv is not installed on your server, but was present in the build environment.  Can't do much about that.  You need to build it in a way that's appropriate for the environment that you are in.

**Comment by jerowe** [comment]
I'm not sure what you mean. It is installed, just not in a default location. Is there no way to have it pick up on that library outside of that location?

**Comment by jszakmeister** [comment]
You need to use `LD_LIBRARY_PATH=/path/to/env nvim` to have it do that.  Passing `LD_LIBRARY_PATH` in front of make does nothing, unfortunately (except to make make and anything it launches look it that path for dependencies first).  There's more information [here](http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html) about how that works.

You also have the possibility of using a tool like `chrpath` to do what you want as well.  I've had varied degrees of success with that one in the past though.

**Comment by jerowe** [comment]
Alright. Thanks for answering. ;-)
