### ISSUE TITLE
xfce4-terminal: restore from suspend opens in tiny size

### ISSUE THREAD

**Issue by JelteF** [neovim/neovim#5350]
- `nvim --version`: 0.1.6-dev
- Vim (version:  7.4 1-2156 ) behaves differently? Yes, it does not have this bug.
- Operating system/version: Ubuntu 16.04.1
- Terminal name/version: Xfce4-terminal 0.6.92 (xfce 4.12), version 0.6.3 does not trigger this bug.
- `$TERM`: xterm-256color

### Actual behaviour
After sending nvim with a vsplit to background with ^Z it is shortly opened very small before changing to the correct terminal size. This changes the vsplit layout.

### Expected behaviour
It uses the full size of the terminal and the vsplit layout is unchanged.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:vs
^Z
fg
```

With my current nvimrc the small state is even kept, making it even more annoying.

**Comment by fwalch** [comment]
Reminds me of https://github.com/neovim/neovim/issues/3245

**Comment by justinmk** [comment]
> Xfce4-terminal 0.6.92 (xfce 4.12), **version 0.6.3 does not trigger this bug.**

@JelteF So this regressed on a newer version of xfce4-terminal? Did you report it to that project? See also #3245 mentioned by @fwalch .

**Comment by JelteF** [comment]
I just added a bug report to the xfce bugtracker: https://bugzilla.xfce.org/show_bug.cgi?id=12859

**Comment by f2404** [comment]
Hi guys, I'm xfce4-terminal developer.
In #3245, some magic command was mentioned, and it indeed makes the terminal shrink: `printf '\e[8;40;100t'`. Could you please give me a hint about what this command does and how it should be treated?
Thanks.

**Comment by f2404** [comment]
Okay, I've figured out that the command is supposed to change terminal dimensions to 40 rows x 100 columns. It was a matter of a proper handler for vte signal - commit https://git.xfce.org/apps/xfce4-terminal/commit/?id=483c4feb56b834f04a25ac63e1319b40d6c2c548 seems to fix the issue for both the command and the neovim scenario described above.

**Comment by justinmk** [comment]
@f2404 Thanks!
