### ISSUE TITLE
copied someones vim mappings - doesn't work in nvim (nnoremap <silent> <expr>)

### ISSUE THREAD

**Issue by ferologics** [neovim/neovim#5361]
- `nvim --version`: NVIM 0.1.5; Build type: RelWithDebInfo
- Vim (version: ) behaves differently?
- Operating system/version: yosemite
- Terminal name/version: iterm 2 latest
- `$TERM`:

λ source .config/nvim/init.vim

Expected a string, but instead found a redirection
.config/nvim/init.vim (line 299):     nnoremap <silent> <expr> j (winheight(0)-1) . "\<C-u>"

from sourcing file .config/nvim/init.vim
called on standard input

source: Error while reading file '.config/nvim/init.vim'

### Actual behaviour

?

### Expected behaviour

thought you can use multiple paramateres

### Steps to reproduce

https://github.com/linduxed/colemak.vim/blob/master/plugin/colemak.vim

put inside your init.vim

**Comment by ferologics** [comment]
maybe I'm not supposed to source it from the terminal ......

**Comment by aliksend** [comment]
but nor [your plugin](https://github.com/linduxed/colemak.vim) nor [original](https://github.com/jooize/vim-colemak) still isn't working under neovim
