### ISSUE TITLE
dead links on bountysource.com

### ISSUE THREAD

**Issue by toogley** [neovim/neovim#5363]
Hey.

### first dead link

to cite from: [boutysource.com](https://salt.bountysource.com/teams/neovim):

> workflows like integration with REPLs and debuggers.

where the word "debuggers" links to the dead page https://github.com/neovim/neovim/blob/master/contrib/neovim_gdb/neovim_gdb.vim, whereas it should link to https://github.com/neovim/neovim/blob/master/contrib/gdb/neovim_gdb.vim

### second dead link

To cite:

> Cross platform built-in GUI, a C port/refactor of the pygtk GUI prototype

where the word "pygtk" links to the dead page https://github.com/neovim/python-client/blob/master/neovim/ui/gtk_ui.py

**Comment by justinmk** [comment]
Thanks. I will update the bountysource page when the newsletter goes out, soon.

**Comment by justinmk** [comment]
Fixed.
