### ISSUE TITLE
ctrl-c should always cancel rpcrequest()

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5364]
While debugging deoplete-jedi, I've just added some `print('foo')` to the server's init method (https://github.com/blueyed/deoplete-jedi/blob/1607a657fb564e53caf44562d3ae77881690f186/rplugin/python3/deoplete/sources/deoplete_jedi/server.py#L144), and this causes Neovim to lock up when executing `:call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')`.

This happens through this rpcrequest:

``` vim
  call rpcrequest(g:deoplete#_channel_id,
\ 'deoplete_enable_logging', a:level, a:logfile)
```

(https://github.com/Shougo/deoplete.nvim/blob/8abb7e3bfc6229c509345a050f19d645ce79059b/autoload/deoplete.vim#L32-L33)

The handler is this (I added the `return` at the top to make sure it's not something else):

``` python
    @neovim.rpc_export('deoplete_enable_logging', sync=True)
    def enable_logging(self, level, logfile):
        return
        logger.setup(self.__vim, level, logfile)
        self.__deoplete.debug_enabled = True
```

Using `strace -f` I see this when focusing the Neovim terminal window:

```
[{EPOLLIN, {u32=0, u64=0}}], 1024, -1) = 1
3162  08:54:26 read(0, "\33[I", 4095)   = 3
3162  08:54:26 write(13, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
3159  08:54:26 <... epoll_wait resumed> [{EPOLLIN, {u32=13, u64=13}}], 1024, -1) = 1
3162  08:54:26 <... write resumed> )    = 8
3159  08:54:26 read(13,  <unfinished ...>
3162  08:54:26 futex(0x7fdcc3e2389c, FUTEX_WAIT_PRIVATE, 141, NULL <unfinished ...>
3159  08:54:26 <... read resumed> "\1\0\0\0\0\0\0\0", 1024) = 8
3159  08:54:26 futex(0x7fdcc3e2389c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fdcc3e23898, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
3162  08:54:26 <... futex resumed> )    = 0
3159  08:54:26 epoll_wait(10,  <unfinished ...>
3162  08:54:26 futex(0x7fdcc3e23870, FUTEX_WAKE_PRIVATE, 1) = 0
3162  08:54:26 epoll_wait(16, [{EPOLLIN, {u32=0, u64=0}}], 1024, -1) = 1
```

And this when trying to abort it using `Ctrl-C`:

```
3162  08:54:31 read(0, "\3", 4095)      = 1
3162  08:54:31 write(13, "\1\0\0\0\0\0\0\0", 8) = 8
3159  08:54:31 <... epoll_wait resumed> [{EPOLLIN, {u32=13, u64=13}}], 1024, -1) = 1
3162  08:54:31 futex(0x7fdcc3e2389c, FUTEX_WAIT_PRIVATE, 143, NULL <unfinished ...>
3159  08:54:31 read(13, "\1\0\0\0\0\0\0\0", 1024) = 8
3159  08:54:31 futex(0x7fdcc3e2389c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fdcc3e23898, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
3162  08:54:31 <... futex resumed> )    = 0
3159  08:54:31 epoll_wait(10,  <unfinished ...>
3162  08:54:31 futex(0x7fdcc3e23870, FUTEX_WAKE_PRIVATE, 1) = 0
3162  08:54:31 epoll_wait(16, [{EPOLLIN, {u32=0, u64=0}}], 1024, -1) = 1
```

While there is maybe something wrong with deoplete's client/server in that case (e.g. "foo" triggers some internal bad state), Neovim should be able to abort the `rpcrequest` always.

I just wanted to mention this already, and could try to come up with a more simplified test case.

The `strace` for the `print('foo')`:

```
6378  09:04:45.480639 write(1, "foo\n", 4) = 4
6373  09:04:45.480887 <... read resumed> "foo\n", 4096) = 4
6373  09:04:45.481569 mmap(NULL, 175075328, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f693de25000
6373  09:04:45.481881 read(9,  <unfinished ...>
6378  09:04:45.482427 write(3, "deoplete_jedi: server PID: 6378\n", 32) = 32
6378  09:04:45.483592 write(3, "Starting server.  sys.path = ['/"..., 598) = 598
6378  09:04:45.483937 write(1, "\33\0\0\0\200\2(K\3K\5K\2X\5\0\0\0finalq\0K\0tq\1.", 31) = 31
6373  09:04:45.484135 <... read resumed> "\33\0\0\0\200\2(K\3K\5K\2X\5\0\0\0finalq\0K\0tq\1.", 175071232) = 31
6373  09:04:45.484264 read(9,  <unfinished ...>
6378  09:04:45.484320 read(0, 
```

PID 6378 is the server (`python -u /home/daniel/.vim/neobundles/deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi/server.py --desc-length 0 --docstrings --debug`), 6373 is the deoplete Python host (`/usr/bin/python3 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/daniel/.vim/neobundles/deoplete/rplugin/python3/deoplete`).

fd 1 of 6378 is `1 -> 'pipe:[1768552]'`.
- `nvim --version`: NVIM v0.1.6-89-g2daf54e

**Comment by justinmk** [comment]
> could try to come up with a more simplified test case.

@blueyed If you can provide reduced steps, I should be able to address this. I've been digging into ctrl-c handling in the last couple days.

**Comment by blueyed** [comment]
@justinmk 
I'd be happy to help you with that.
I think it's not trivial, but might be related to https://github.com/neovim/neovim/issues/3757, and you've linked to https://github.com/neovim/neovim/pull/4624#issuecomment-222052654 yourself a while ago.

**Comment by diefans** [comment]
Is it possible, that you are confusing the stdio pipe of the msgpack-rpc with your print? If thats the case your should print to stderr...

**Comment by bfredl** [comment]
Is this still an issue/confirmed to be a nvim issue? Bad behavior in rplugins can cause lock-ups, it is not necessarily a nvim bug.

As for the `print('foo')` issue, I believe it was covered by https://github.com/neovim/pynvim/pull/377

**Comment by justinmk** [comment]
> Neovim should be able to abort the `rpcrequest` always

Does ctrl-c abort rpcrequest() now? If not, that seems like reason to keep this open.

**Comment by bfredl** [comment]
Related: https://github.com/neovim/neovim/issues/7546

**Comment by justinmk** [comment]
Merging with #7546
