### ISSUE TITLE
Rendering issues on external displays

### ISSUE THREAD

**Issue by sherzinger** [neovim/neovim#5365]
- `nvim --version`: 0.1.5 & 0.1.6-dev
- Vim (version: ) behaves differently?: Yes, this issue is not present in vim (tested with 8.0)
- Operating system/version: OSX 10.11.6
- Terminal name/version: iterm2(Build 3.0.20160802) and Terminal.app have the same issue
- `$TERM`: xterm-256color

This is the issue: http://imgur.com/a/NKMP3
TL;DW: Random numbers fragments a la 38;5;223m on arbitrary positions within vim

- it also happens with -u NONE
- it DOES NOT happen on the built-in display on my mac book
- the issue is independent of the used colorscheme

**Comment by justinmk** [comment]
This is the same as https://github.com/neovim/neovim/issues/3875 , right?

**Comment by sherzinger** [comment]
You are right, it's the same issue.
The workaround does not work for me.

I'm subscribed to #3875 now and available for testing potential fixes.

**Comment by justinmk** [comment]
@sherzinger Please try latest master. #5436 was merged, it may help with your issue.
