### ISSUE TITLE
Multiple repeats for macro @register seem to be broken

### ISSUE THREAD

**Issue by josefcs** [neovim/neovim#5367]
- `nvim --version`: NVIM 0.1.6-dev
- Vim (VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 16 2016 10:50:38) ) behaves differently? yes
- Operating system/version: Ubuntu 16.04.1 LTS
- Terminal name/version: GNOME-Terminal 3.18.3
- `$TERM`: GNOME-Terminal 3.18.3

### Actual behaviour

Macro registers are not executed n times, but the command-chain stops with the '@' sign entered.

Open neovim, paste the text:
`aaaa bbbb cccc dddd eeee ffff gggg`

In normal mode, go to the first char. Then press:
`qqf xq`

This records the deletion of a space.
Now, if you try to repeat it, e.g.
`5@q`

The command ends at '@' and only '@q' is executed. Hence the output is:

`aaaabbbb|cccc dddd eeee ffff gggg`

### Expected behaviour

The result should be q repeated n times, e.g.:
`aaaabbbbccccddddeeeeffffgggg`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i
aaaa bbbb cccc dddd eeee ffff gggg
<ESC>
0
qqf xq
5@q
```

**Comment by justinmk** [comment]
Can't reproduce on `NVIM v0.1.6-119-g7b6786f6f9b8`. Result for me is `aaaabbbbccccddddeeeeffffgggg`. Also compared Vim 8.x and the result is the same.

**Comment by justinmk** [comment]
Can you post the full `nvim -v` output?

**Comment by josefcs** [comment]
Had access to another machine. I can't reproduce this myself on any other machine.

The error does not occur:
- on other machines I had access to
- nvim login shell via ctrl+alt+F2
- vim (on any machine)

Sorry for the fuzz! It seems there is something wrong with my desktop environment (unity) which seems to dislike just neovim.

```
$ nvim -v
NVIM 0.1.6-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/build/config -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/src -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-rL3Sku/neovim-0.1.5ubuntu1+git201609201032+2778+21~ubuntu16.04.1/build/include
Übersetzt von buildd@lgw01-56

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"
```

**Comment by justinmk** [comment]
@josefcs I see you're running with de locale, maybe try `LC_ALL=C`. And compare the result of `:lang` on the non-working system vs the working system. Though I can't imagine why that would cause a problem.

**Comment by josefcs** [comment]
@justinmk The locale didn't do it. There was something wrong with the "Alt Gr" Key in the console (needed for @). Everytime I pressed it, there was some flicker. However, after Hours of trying, I was not able to resolve it and switched to Gnome, where it runs without problems.

One interesting thing is, that it worked in vim, so this could be some "system/tool-process" that reacted to neovims input mode. But apart from that I don't see any possibility to fix or investigate this.
