### ISSUE TITLE
Unable to navigate to directories in netrw after switching to another app and returning

### ISSUE THREAD

**Issue by alistaircolling** [neovim/neovim#5375]
NVIM 0.1.6-dev
Build type: Debug

- Vim 7.4 works as expected
- OSX 10.10.5
- iTerm 3.0.9

### Actual behaviour

1. Open a directory containing other directories
2. Change to another application in the OS e.g. Chrome
3. Change back to iTerm
4. Select directory to open
5. Directory will not open

![Actual behaviour](https://cloud.githubusercontent.com/assets/111540/18750497/3e1a5c28-80d3-11e6-8a2e-a99070c46f45.gif)

### Expected behaviour

1. Open a directory containing other directories
2. Change to another application in the OS e.g. Chrome
3. Change back to iTerm
4. Select directory to open
5. Directory will open

**Comment by justinmk** [comment]
Does it work if you 

    set mouse=

(note: _nothing_ after the `=`)

**Comment by alistaircolling** [comment]
That fixes it @justinmk !

**Comment by justinmk** [comment]
@alistaircolling It may be a bug in netrw. You might want to report to netrw maintainer (easy way: create a bug at https://github.com/vim/vim)
