### ISSUE TITLE
TERMINAL mode destroyed upon switching focus

### ISSUE THREAD

**Issue by physkets** [neovim/neovim#5377]
- `nvim --version`: _0.1.5_
- Vim (version: _8.0.5_) behaves differently? _Not Applicable_
- Operating system/version: _Arch Linux_
- Terminal name/version: _gnome-terminal_
- `$TERM`: _xterm-256color_

### Actual behaviour

I use four `:split` screens, with one of them in terminal mode (so I can run htop). Now, once in the screen with the terminal mode, I can not move to another using Ctrl+W. But thanks to nvim's mouse support, I can shift focus to another by clicking. But now, when I shift focus back to the erstwhile terminal split screen (via Ctrl-W or mouse click), it no longer is. I am in NORMAL mode now!

### Expected behaviour

* Be able to shift out of a TERMINAL split screen using Ctrl-W (or maybe not).
* Be able to shift into a TERMINAL split screen without changing it into a NORMAL one.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC file1
:vsplit file2
:split
:terminal
*attempt a Ctrl-W to shift focus; unsuccessful*
*mouse click on oneof the other screens; successful*
*shift back (mouse-click or Ctrl-W) to see TERMINAL split is now NORMAL*
```

**Comment by justinmk** [comment]
Press `i` in the terminal buffer

**Comment by physkets** [comment]
Shoot...  I am sorry.

**Comment by justinmk** [comment]
No problem

**Comment by nhooyr** [comment]
Also, use `<C-\><C-n>` to exit terminal mode back to normal mode.
