### ISSUE TITLE
Please document how to make nvim read vim configuration

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#5382]
I've managed to get nvim to read my vim configuration; please consider documenting the steps to do this:

```sh
ln -s ../.vim ~/.config/nvim
ln -s ../.vimrc ~/.vim/init.vim
```

- `nvim --version`:
```text
NVIM 0.1.5
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-hjTJUq/neovim-0.1.5=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-hjTJUq/neovim-0.1.5/build/config -I/build/neovim-hjTJUq/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-hjTJUq/neovim-0.1.5/build/src/nvim/auto -I/build/neovim-hjTJUq/neovim-0.1.5/build/include
Compiled by buildd@x86-grnet-01

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim behaves differently? N/A
- Operating system/version: Debian GNU/Linux, current unstable
- Terminal name/version: gnome-terminal 3.22.0
- `$TERM`: xterm-256color

**Comment by KillTheMule** [comment]
It's [here](https://neovim.io/doc/user/nvim.html#nvim-from-vim).

**Comment by joshtriplett** [comment]
@KillTheMule ...well, I feel silly.  I didn't find that.  Thanks!

(I do think relative symlinks make more sense, since they'll work even across systems without depending on the path to your home directory.)

**Comment by justinmk** [comment]
Patch welcome :)

**Comment by ZyX-I** [comment]
Relative symbolic links are not a good choice for documentation: if ~/.config is a symlink to something (e.g. to `~/repos/homedir/.config`) then your commands will not work correctly. Absolute links are *safer*, and if user cares then he already knows what is the difference and how to create either and may use relative links without guidance.
