### ISSUE TITLE
Inserting special characters with digraph does not work

### ISSUE THREAD

**Issue by 5nizza** [neovim/neovim#5385]
- `nvim --version`: `NVIM 0.1.6-dev`
- Vim (version: 7.4) behaves differently!
- Operating system/version: `ubuntu 16.04 LTS 4.4.0-38-generic`
- Terminal name/version: `GNOME Terminal 3.18.3`
- `$TERM`: `xterm-256color`

### Actual behaviour
In neovim, pressing `Ctr-K` followed by `FA` inserts `<FocusLost>FA`

### Expected behaviour
In vim, pressing `Ctr-K` followed by `FA` inserts ∀

**Comment by justinmk** [comment]
Works for me. What are the steps using `nvim -u NORC`? This will show the actual configuration needed to reproduce the issue. Seems like you have a mapping that is interfering. What does 

    :verbose <c-k>

show?

**Comment by 5nizza** [comment]
Steps using `nvim -u NORC` are the same.

If I type: `:verbose <c-k>`, then it says `E488: Trailing characters`.

If type `:verbose <c-k>` (where `<c-k>` means `press <c-k>`), then it shows `:verbose <FocusLost>FA` while vim results in `:verbose ∀`.

I just tried in `quake` terminal -- it works there. hm.

**Comment by 5nizza** [comment]
@justinmk which gnome-terminal do you have?

**Comment by justinmk** [comment]
In xterm what TERM ?

**Comment by 5nizza** [comment]
`echo $TERM` in `xterm` shows `xterm`.
Note that in `guake` (where neovim digraphs works as expected) also prints `xterm`.

**Comment by justinmk** [comment]
Seems like a terminfo mismatch. Try a different TERM.  Are you using tmux in any case?

**Comment by 5nizza** [comment]
`tmux` is not installed.

Not sure i understood you about `TERM` -- I tried calling in gnome-terminal `export TERM=gnome-terminal` before using neovim, didn't help (the same with setting to `xterm` instead of `xterm-256color`).

**Comment by justinmk** [comment]
Ok. Help needed. Supporting every random terminal configuration is low priority.

**Comment by fwalch** [comment]
Can't reproduce in gnome-terminal 3.20.2 on Arch Linux (`TERM=xterm-256color`) and 3.6.2 on Ubuntu (`TERM=xterm`).

**Comment by 5nizza** [comment]
hm, may be indeed it is my weird configuration of gnome-terminal (i recently played with "themes" for gnome-terminal), as suggested by @justinmk.
I will ask guys around to check if they can reproduce it, if not -- close the issue.
(though it is still interesting why vim _does_ work)

**Comment by justinmk** [comment]
It's a fact that Vim goes to great lengths to support numerous terminal situations. Neovim completely replaced Vim's terminal code, and this resulted in some better handling of "common scenarios" (and most important: abstracted the terminal so that we can have completely externalized UI handling), but worse handling of uncommon scenarios. 

It's possible this is just a bug in the way we handle some input sequence. If you can provide the sequence of bytes to reproduce this issue we may be able to fix it.

**Comment by 5nizza** [comment]
I checked on another computer -- digraph neovim works there.
I am closing the issue (unlikely i will have time to dig for the reasons of non-working on my setup).
thank you!

**Comment by nexusstar** [comment]
@5nizza I have similar problem and found the culprit to be my configuration.I manage to find what set the wrong mapping with `:verbose imap <c-k>` not just `:verbose <c-k>` later just outputs `E488: Trailing characters`
