### ISSUE TITLE
Colorscheme broken in v0.1.5

### ISSUE THREAD

**Issue by munyari** [neovim/neovim#5390]
- `nvim --version`: 0.1.5
- Vim (version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 15 2016 10:11:05))
- Operating system/version: 4.7.4-1-ARCH x86_64 GNU/Linux
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: screen

Upon upgrading to 0.1.5 my colorscheme broke. I use [vim-gotham](https://github.com/whatyouhide/vim-gotham). The wrong colors are displayed. In 0.1.4, it looked like this:
![2016-04-19-155839_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5841072/18848722/b1dc12aa-83fd-11e6-9bdc-fffbc5f74fad.png)

This is what it looks like in 0.1.5:
![2016-09-26-152443_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5841072/18848700/9137290e-83fd-11e6-9477-232cf99d1761.png)

I see the issue with the following vimrc:
```vim
call plug#begin('~/.vim/plugged')
Plug 'whatyouhide/vim-gotham'
call plug#end()

colorscheme gotham

set termguicolors
```

This is after running `:PlugClean` to ensure that no other plugins are interfering. Also, worth noting that it doesn't seem to work at all for me in vim 8

**Comment by justinmk** [comment]
Move set termguicolors to the top.

**Comment by munyari** [comment]
Hey Justin. Still doesn't work unfortunately.

![2016-09-27-092249_1920x1080_scrot](https://cloud.githubusercontent.com/assets/5841072/18875590/64dbf8fc-8494-11e6-83d9-baefb39bc055.png)

**Comment by munyari** [comment]
Ooh, nevermind, seems to be working now...

**Comment by justinmk** [comment]
Does your terminal support "true color"? Please try vi.stackexchange.com, this isn't a nvim issue.

**Comment by munyari** [comment]
Ah, you're right - it's the terminal. Seems that urxvt does not have true color support, works in st.

**Comment by munyari** [comment]
I got it, true color support was added in June, the current release in arch repos is from January. Thanks for the help in resolving this!
