### ISSUE TITLE
:terminal output completes pending op (d, y, ...)

### ISSUE THREAD

**Issue by benwr** [neovim/neovim#5398]
I started using neovim last week, and one of my favorite features is the built-in terminal. It's extremely convenient. I'm coming from Emacs + Evil, and one of my longtime gripes was that eterm is terrible. Somehow neovim's terminal is exactly right, except for a few minor issues. In this case, if I have a big terminal window, output in the terminal can screw up input into text buffers.

```
NVIM v0.1.5
Build type: Debug
Compilation: /usr/lib/ccache/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/ben/sources/neovim/build/config -I/home/ben/sources/neovim/src -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/usr/include -I/home/ben/sources/neovim/build/src/nvim/auto -I/home/ben/sources/neovim/build/include
Compiled by ben@[redacted]

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim: N/A (doesn't have built-in terminal)
- Operating system/version: Ubuntu 14.04
- Terminal name/version: st 0.7, urxvt 9.19
- `$TERM`: xterm-256color
### Actual behaviour

When a program prints lots of things in TERMINAL mode, typing `d` in text buffers immediately deletes a line, as though you had typed `dd`. With _really_ high volume output, other weird things seem to happen, but they're harder to reproduce without spamming so hard that my computer freezes.
### Expected behaviour

`d` should wait for a text object as an argument, as it does in normal situations.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i
some text 1
some text 2
some text 3
some text 4
<Esc>
<C-w>s
:term
while true; do yes | head -n 50; sleep 0.01; done # maybe tweak this to be more intense (shorter sleep, more lines of yes), depending on your system
<C-\><C-n>
<C-w>j
d
```

**Comment by fwalch** [comment]
Alternative reproduction steps in #5417.

**Comment by justinmk** [comment]
Is this the same as https://github.com/neovim/neovim/issues/3720 ?

I plan to spend a lot of time the next 2 months working on `:term` bugs.
