### ISSUE TITLE
`o` and `O` should enter TERMINAL mode in term buffer

### ISSUE THREAD

**Issue by benwr** [neovim/neovim#5399]
In a term buffer in Normal mode, one would expect that `o` and `O`, being "keys that enter insert mode" would cause a switch to TERMINAL mode. Instead, you get "E21: Cannot make changes, 'modifiable' is off". A workaround is to set `nnoremap o A<Return>` and `nnoremap O I<Return><Up>`, but this is hacky (and means that they'll (incorrectly) send `<Return>` to the terminal)

```
NVIM v0.1.5
Build type: Debug
Compilation: /usr/lib/ccache/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/ben/sources/neovim/build/config -I/home/ben/sources/neovim/src -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/home/ben/sources/neovim/.deps/usr/include -I/usr/include -I/home/ben/sources/neovim/build/src/nvim/auto -I/home/ben/sources/neovim/build/include
Compiled by ben@[redacted]

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Vim: N/A (doesn't have built-in terminal)
- Operating system/version: Ubuntu 14.04
- Terminal name/version: st 0.7, urxvt 9.19
- `$TERM`: xterm-256color
### Actual behaviour

`o` and `O` cause E21 when in Normal mode on a terminal buffer.
### Expected behaviour

Should enter TERMINAL mode
### Steps to reproduce using `nvim -u NORC`

```
`nvim -u NORC`
:term
o
```

**Comment by justinmk** [comment]
What about `nnoremap <buffer> o i` ?

I think we should have a ftplugin for terminal buffers that sets up things like this.

**Comment by justinmk** [comment]
OTOH why would you *not* expect `o` to send `<return>` ? Why not use `i` ?

**Comment by benwr** [comment]
Is there an easy way to set a keybinding specifically for the `:term` buffer (but in normal mode)?

**Comment by justinmk** [comment]
Check 'buftype' and set a buffer local mapping (see my first comment).

**Comment by benwr** [comment]
I maintain that it's a bug that `o` throws an error - the docs say

"Sending input is possible by entering terminal mode, which is achieved by pressing any key that would enter insert mode in a normal buffer", ergo `o` should enter terminal mode.

**Comment by benwr** [comment]
I appreciate the pointer, though!

**Comment by justinmk** [comment]
Yes. I think we should just allow terminal buffers to be modifiable.

**Comment by justinmk** [comment]
Actually that won't work because all insert-mode input must be forwarded to the child process.

**Comment by ZyX-I** [comment]
@benwr Or documentation needs to be fixed. I personally would be fine with only `i` entering terminal mode and nothing else, because anything else is impossible to make consistent with non-terminal buffers without doing some assumptions regarding input processing of the underlying application (I mean, do things like `nnoremap I i<Home>`, `nnoremap a i<Right>`, etc for teminal buffers: like you suggested, but not just `o` and `O`, *all* keys except `i` should be affected).

**Comment by shtanton** [comment]
This seems to have been forgotten about, we should decide if we are going to update the docs and have only `i` enter terminal mode, or stay consistent with the docs and have `o` and `O` enter terminal mode.

Might as well pick one and close the issue 'cos it's not gonna take long
