### ISSUE TITLE
The plugin tpope/vim-fugitive can't work with neovim

### ISSUE THREAD

**Issue by z1003031335** [neovim/neovim#5401]
- `nvim --version`: NVIM 0.1.5
- Vim (version: ) behaves differently?
- Operating system/version:Arch Linux 4.7.4-1-ARCH
- Terminal name/version:urxvt v9.22
- `$TERM`:screen-256color

### Actual behaviour
Not an editor command
### Expected behaviour
Gstatus should open a window showing information about git status
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by KillTheMule** [comment]
Works for me.

**Comment by fwalch** [comment]
Well, if you call nvim with NORC, fugitive is not available because the initrc is not loaded. But I guess that is not the real problem? You can provide a minimal init.vim instead of reproduction steps with NORC in this case.

**Comment by justinmk** [comment]
This is a usage issue. Try stackoverflow.

**Comment by z1003031335** [comment]
@fwalch  This is my minimal init.vim. 
`let mapleader = ' '
set clipboard=unnamedplus

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()

" ----------------------------------------------------------------------------
" vim-fugitive {{
" ----------------------------------------------------------------------------
nmap     <Leader>gs :Gstatus<CR>gg<c-n>
nnoremap <Leader>d :Gdiff<CR>
" }}
`

**Comment by z1003031335** [comment]
@KillTheMule I have found source of the problem,it will works only you being a git directorty.
However,vim has no the this problem.

**Comment by brcolow** [comment]
Cannot reproduce on Vim 8.0 on Windows. I get "Not an editor command" got `Gstatus` when not in a file that is not in a git repository. In other words, for me, Vim and Neovim behave the *same*.
