### ISSUE TITLE
It is long that that pressing o takes time at the first time

### ISSUE THREAD

**Issue by z1003031335** [neovim/neovim#5402]
- `nvim --version`: NVIM 0.1.5
- Vim (version: ) behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: Urxvt 9.22
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by KillTheMule** [comment]
Can't reproduce. What file are you using it on/in?

**Comment by z1003031335** [comment]
@KillTheMule Whatever file,i have a newly finding not only pressing o but also pressing I,A,i and a cause the problem as well,nevertheless,it only effects the first time operation.
