### ISSUE TITLE
v:count broken in command-line window

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#5404]
- `nvim --version`: NVIM v0.1.6-175-g7246750
- Vim (version: 8.0.17) behaves differently? yes
- Operating system/version: Ubuntu 14.04
- Terminal name/version: n/a
- `$TERM`: n/a

### Actual behaviour
v:count always return 0 in command-line window
v:count1 always return 1 in command-line window

### Expected behaviour
v:count returns given count in command-line window, or 0 when no count given
v:count1 returns given count in command-line window, or 1 when no count given

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:map _x :<C-U>echo "the count is " . v:count<CR>
q:
3_x
```

**Comment by jamessan** [comment]
I've confirmed the problem.  It exists at least as far back as 0.1.1 and works correctly in Vim 7.3.001, so it's not a missing patch.  We've regressed somewhere.
