### ISSUE TITLE
<c-v>{sequence} inserts sequence name instead of actual bytes

### ISSUE THREAD

**Issue by teto** [neovim/neovim#5405]
- `nvim --version`: NVIM v0.1.6-167-g22dfe69
- Vim (version: ) behaves differently? Yes, in vim <c-tab> triggers a "termite" search, tried in urxvt but can't see the output, seems like some sort of space.
- Operating system/version: ubuntu 16.04.1
- Terminal name/version:  termite v10-20-g22c1191
- `$TERM`: xterm-termite
### Actual behaviour

nvim prints `<FocusLost>`
### Expected behaviour

Would expect to read `<c-tab>` instead
### Steps to reproduce using `nvim -u NORC`

go into insert mode, `<c-v><c-tab>`

In fact in some cases, it triggers the termite search input, in which case nvim might receive a `<FocusLost>` event but if I look at https://github.com/thestinger/termite, <C-Tab> should "start scrollback completion".
IMO, the c-tab is intercepted by termite so that may not be a proper "bug" but @bfredl told me that the `<FocusLost>` should not be displayed hence the issue.

**Comment by justinmk** [comment]
What happens (or what is printed) if you do `<c-v><c-tab>` in your shell (e.g. bash) out side of nvim?

> @bfredl told me that the <FocusLost> should not be displayed hence the issue.

This happens with some "key symbols", e.g. it also happens for me with `<c-v><bs>` (literal 4-char string `<BS>` is inserted). 

This bug has existed for awhile, not sure if anyone bothered to report it until now. It bothers me, but I've wondered if it actually harms anything.

**Comment by teto** [comment]
in bash, it opens the termite search input, it not print any character in
the prompt.
I've been using neovim since its inception but I noticed only now - this is
my day - that I get the same behavior in neovim (<FocusLost>) gets printed
when I press media keys.

Overall it's pretty harmless.


2016-09-30 0:35 GMT+02:00 Justin M. Keyes <notifications@github.com>:

**Comment by justinmk** [comment]
>  (<FocusLost>) gets printed when I press media keys.

Oh, that's a bit more problematic than just after ctrl-v. Do your media keys actually cause focus to be lost (e.g. they bring up some other application)?

Can you run `showkey -a` and send the results of 

1. pressing a media key
2. pressing ctrl-tab

**Comment by teto** [comment]
It just prints `<FocusLost>` without parentheses (I closed the parenthesis too early sorry).
`showkey -a` show nothing when pressing either C-Tab or mediakeys. The mediakeys are intercepted by my WM (www.i3wm.org) and call an "mpd" command in background. I don't see any change in my focus but i3 must certainly change it to send the mpd command otherwise termite would not send  a FocusLost to neovim. 
The C-Tab is as usual intercepted by termite.

**Comment by justinmk** [comment]
Just for reference, can you try mapping <FocusLost> in insert-mode?

    :inoremap <FocusLost> foo

then, is "foo" inserted instead?

**Comment by teto** [comment]
In insert mode without <c-v>, "foo" is inserted, otherwise beahvior remains the same

**Comment by justinmk** [comment]
Hmm, weird. For me, with that `inoremap`, `foo` is correctly inserted when focus is lost; and without that map, nothing is inserted. 

You _did_ confirm with `nvim -u NORC`, yes?

**Comment by teto** [comment]
sorry, with nvim -u NORC it works as you say.

**Comment by justinmk** [comment]
@teto If you can find minimal steps to reproduce, that will help a lot.

**Comment by justinmk** [comment]
Seems to be fixed.
