### ISSUE TITLE
malloc_zone_unregister Error in macOS Sierra

### ISSUE THREAD

**Issue by DongjunLee** [neovim/neovim#5415]
- `nvim --version`: n/a
- Vim (version: ) behaves differently? n/a
- Operating system/version: macOS Sierra 10.12
- Terminal name/version: iTerm2 3.0.9
- `$TERM`: n/a
### Actual behaviour

``` bash
nvim bot.py
nvim(5921,0x7fffe29063c0) malloc: *** malloc_zone_unregister() failed for 0x7fffe28fc000
```
### Expected behaviour

``` bash
nvim bot.py
```

execute Neovim
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

n/a

need help!

**Comment by justinmk** [comment]
It's fixed in jemalloc upstream. We might need to upgrade to that version.

**Comment by justinmk** [comment]
@DongjunLee You can work around the issue by disabling jemalloc:

    rm -rf build/ && CMAKE_EXTRA_FLAGS='-DENABLE_JEMALLOC=0' make

**Comment by brcolow** [comment]
https://github.com/jemalloc/jemalloc/commit/19c9a3e828ed46f1576521c264640e60bd0cb01f

**Comment by DongjunLee** [comment]
@justinmk , @brcolow  Thanks, i'll check it.
