### ISSUE TITLE
Keychains not working while process running in terminal emulator 

### ISSUE THREAD

**Issue by gboehl** [neovim/neovim#5417]
- `nvim --version`: 0.1.5
- Operating system/version: Linux 4.7.3-2
- Terminal name/version: urxvt v9.22
- `$TERM`: xterm-256color

### Actual behaviour
I am running some python simulations or latex compilations in the terminal emulator. While processes are running, I can not make use of keychains (`dd`, `wc`,...) or, respectively, single keys will be interpreted as such.

### Expected behaviour
Keychains are working independently of whether processes are running or idle.

### Steps to reproduce using `nvim -u NORC`

Create and save a file `~/gulp`:
```
#!/bin/bash

GULP=0
while [ $GULP -lt 9 ]; do
    echo "Gulp."
    sleep 1
done
# don't delete this line :(
```
Run `nvim -u NORC `, open a terminal emulator (`split term://bash`) and run the file in there by `bash ~/gulp`. While running, go back to the `gulp`-buffer and press `d` on the not-to-be-deleted line. It will be handled as if you would have pressed `dd`. Same is valid for `wd` etc.

**Comment by fwalch** [comment]
Sounds similar to #5398

**Comment by gboehl** [comment]
Yes, sounds very much like it.

**Comment by fwalch** [comment]
Okay.. then I'll go ahead and close this as a duplicate.
