### ISSUE TITLE
Perceptible lag with showmatch option (editing c++ code)

### ISSUE THREAD

**Issue by Zouch** [neovim/neovim#5423]
- `nvim --version`: `NVIM 0.1.6-dev - Build type: RelWithDebInfo`
- Operating system/version: Ubuntu 16.04
- Terminal name/version: gnome-terminal, terminator has the same lag though
- `$TERM`:  xterm-256color

### Actual behaviour
When writing c++ code there is sometimes a noticeable lag.
For example if I type `void Foo()<cr>{<cr>}` there is a lag after the first `<cr>` which sometimes even drops the second one. 
This can also easily be seen because the second bracket takes a while to automatically unindent.

[Here is a vim profiling log](https://gist.github.com/Zouch/89f7d8ee32b22585bf806b0257af2929) (generated using [this SO post](http://stackoverflow.com/a/12216578/4717805))

I don't know if it is a bug with this option but I can't remember having this lag with vim (actually I'm not sure wether I was using it at all...)

[Here is my init.vim, just in case](https://github.com/Zouch/nvim)

(I validated the `showmatch` is what is causing the lag here by removing all plugins and toggling the option)

**Comment by justinmk** [comment]
It's a known issue, in Vim as well. Try this:

```vim
let g:matchparen_timeout = 20
let g:matchparen_timeout = 20
```
