### ISSUE TITLE
nvim does not redraw its window after maximizing terminal

### ISSUE THREAD

**Issue by hiqua** [neovim/neovim#5434]
- `nvim --version`:
  NVIM v0.1.6-182-gb1edc8a
  Build type: Debug
  Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/hiq/code/repositories/neovim/build/config -I/home/hiq/code/repositories/neovim/src -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/home/hiq/code/repositories/neovim/.deps/usr/include -I/usr/include -I/home/hiq/code/repositories/neovim/build/src/nvim/auto -I/home/hiq/code/repositories/neovim/build/include
  Compiled by hiq@hiq-lptp-deb

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui  
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
- Vim (version: ) behaves differently?
  Yes, with:
  VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07)
  Included patches: 1-488, 576
- Operating system/version:
  Debian Jessie
- Terminal name/version:
  GNOME Terminal 3.14.1
- `$TERM`:
  screen-256color (with tmux)
  xterm (without tmux)
### Actual behaviour

nvim does not redraw itself automatically; instead it only fills the same amount of space, even though there is more available.
### Expected behaviour

The vim window should redraw itself automatically and fill the whole terminal window.
### Steps to reproduce using `nvim -u NORC`

Open a terminal window which is not maximized, then

```
nvim -u NORC $SOME_VERY_BIG_FILE
```

While the file is loading, maximize the window. Stop opening the file using CTRL-C (as far as I can tell it also works if I allow nvim to load the file, as long as I can maximize the window at the same time).

I have had this bug with neovim for quite some time now. Using git-bisect, I found that commit @eb001a4abd2fbc740547c127807b2fc8367cc187 could be the culprit. The reason why I did not report it earlier is that I was unable to reproduce it, until I realized that lengthening the loading time by using a large file makes it easier.

Here is a screenshot of what happens:
![screenshot from 2016-10-05 13 39 23](https://cloud.githubusercontent.com/assets/3812042/19112779/0bb6fcb2-8b07-11e6-9007-7d2de7304b05.png)

**Comment by justinmk** [comment]
Thanks for adding repro insight which was lacking in https://github.com/neovim/neovim/issues/4884.

**Comment by hiqua** [comment]
This might indeed be the same bug or related, although note that I can reproduce it without tmux and with nvim -u NONE. Feel free to merge or close the issue if appropriate.

**Comment by Maltimore** [comment]
I have this problem too. Has it been noted that it only occurs when maximizing the terminal window, but not when you resize the window (by "pulling" the edge of the window with the mouse)?

**Comment by gwerbin** [comment]
@Maltimore Can confirm on OSX. For some reason I assumed it was an iTerm bug.

**Comment by juliohm** [comment]
Can confirm the issue. NVIM 0.1.7 installed from Arch Linux repos.

**Comment by justinmk** [comment]
This was fixed by https://github.com/neovim/neovim/commit/34e5654f2166fea0ae78a6260e8b961be4b07f1d
