### ISSUE TITLE
Proxy and `ERROR: Failed to run healthcheck for "provider" plugin.`

### ISSUE THREAD

**Issue by cprn** [neovim/neovim#5435]
- `nvim --version`: NVIM 0.1.6-dev
- Vim (version: ) behaves differently? not applicable
- Operating system/version: Ubuntu 15.10
- Terminal name/version: GNOME Terminal 3.18.2
- `$TERM`: screen-256color

### Actual behaviour

`curl` used in `health#provider` fails to connect on system behind proxy:

```
health#provider#check
================================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    Vim(let):E474: Unidentified byte: <!DOCTYPE html PUBLIC "-//W3C//DTD [...]
```

### Expected behaviour

`curl` call from `/usr/share/nvim/runtime/autoload/health/provider.vim` uses `$HOME/.curlrc` and respects its settings (including proxy) or uses local `env` variables:
- https_proxy
- no_proxy

### Steps to reproduce using `nvim -u NORC`

```
echo proxy=localhost:8080 > ~/.curlrc
export https_proxy=localhost:8080
nvim -u NORC
:CheckHealth
```

As a test I tried to change the behavior with the following patch:
```diff
--- provider.vim       2016-10-05 16:48:27.029307493 +0200
+++ provider.vim.new   2016-10-05 18:20:25.153283823 +0200
@@ -34,7 +34,7 @@
 function! s:download(url) abort
   let content = ''
   if executable('curl')
-    let content = system(['curl', '-sL', "'", a:url, "'"])
+    let content = system(['curl', '-sL', '--proxy', 'localhost:8080', "'", a:url, "'"])
   endif
 
   if empty(content) && executable('python')
```

Unfortunatelly it didn't work as the function falls back to `python` solution which fails for the same reason.

**Comment by justinmk** [comment]
I think you need `HTTPS_PROXY` for https (vs `http_proxy` for non-SSL), according to `man curl`.

Another thing to try: does it work if you force `--config ~/.curlrc`? Something like this (untested):

    let content = system(['curl', '-sL', '--config', expand('~/.curlrc'), "'", a:url, "'"])

**Comment by cprn** [comment]
It doesn't fall back to python but still ignores proxy settings. I tried to use absolute path as well but still fails. No idea why. The same behaves as expected when run from shell:
- fails in clean environment without `.curlrc`
- works in clean environment with `.curlrc` in home dir
- works witch environment variables set and without `.curlrc` in home dir

**Comment by justinmk** [comment]
Does it work if you change the array in the system() call to a string?

    let content = system('curl -sL --config'.expand('~/.curlrc').shellescape(a:url))

**Comment by cprn** [comment]
> IIRC the array variant doesn't inherit the environment.

Must be it! Your line works beautifully and so does this (`env` variables get inherited):

```diff
--- provider.vim.old    2016-10-05 20:02:16.751462644 +0200
+++ provider.vim        2016-10-05 20:01:10.551351949 +0200
@@ -34,7 +34,7 @@
 function! s:download(url) abort
   let content = ''
   if executable('curl')
-    let content = system(['curl', '-sL', "'", a:url, "'"])
+    let content = system('curl -sL '.shellescape(a:url))
   endif
 
   if empty(content) && executable('python')
```

**Comment by gfairchild** [comment]
I just ran into this same issue running 0.1.5.

**Comment by justinmk** [comment]
Inheriting the environment wasn't the issue, it was just malformed argument list. (For the record, I confirmed that `system([...])` with a list argument _does_ inherit the environment.)
