### ISSUE TITLE
Mechanism to auto-install/auto-update gem

### ISSUE THREAD

**Issue by docwhat** [neovim/neovim#5437]
Currently, if the neovim gem is not installed, I get this message:

```
$ vim
function provider#ruby#Call[8]..remote#host#Require[13]..provider#ruby#Require, line 10
Vim(if):Channel was closed by the client
rbenv: neovim-ruby-host: command not found
Failed to load ruby host. You can try to see what happened by starting Neovim with the environment variable $NVIM_RUBY_LOG_FILE set to a file and opening the generated log file.Also, the host stderr is available in messages.
Press ENTER or type command to continue
```

Instead, it would be nice if it did something like:

```
$ vim
Your ruby is missing the neovim gem.  Attempting to install...
Successfully installed the neovim gem
Press ENTER or type command to continue
```

This could try doing `gem install`, then `gem install --user-install`, and then fall back to `sudo`.  Possibly with prompts for each one.

It would also be nice if it figured out where the `neovim-ruby-host` command was by asking `ruby` instead of assuming it is in the path.  e.g. `RbConfig::CONFIG["bindir"]` or something similar.

[My configuration files](https://github.com/docwhat/dotfiles/tree/master/config/nvim)

This is with all the versions of 1.6 neovim I have played with.  And this ticket was ported from alexgenco/neovim-ruby#23

**Comment by docwhat** [comment]
cc: @alexgenco

**Comment by fwalch** [comment]
Related: https://github.com/neovim/neovim/issues/5238 `has('ruby')` always returns 1
Fixing that should get rid of the error message

**Comment by docwhat** [comment]
It depends on if `has('ruby')` means it has `ruby` installed or if neovim has access to `ruby` via the `neovim-ruby-host` command.

I would think if `ruby` was available, it would be nice to try to connect to it and help the user through the process; as good UX design.

Equally, there should be a way to tell neovim to "hush up, I don't want you to talk to that ruby". 😪

**Comment by justinmk** [comment]
> Your ruby is missing the neovim gem.  Attempting to install...

It would be nice, but also a huge time-sink to get it right for all environments (which is a never-ending task...). `:CheckHealth` is hopefully a useful middle-ground.

> figured out where the neovim-ruby-host command was by asking ruby instead of assuming it is in the path

If you know a way to ask ruby, please leave a note at https://github.com/neovim/neovim/issues/5238

> Equally, there should be a way to tell neovim to "hush up, I don't want you to talk to that ruby".

`g:ruby_host_prog`, similar to `g:python3_host_prog` for the python provider?

**Comment by justinmk** [comment]
Tagging this `wontfix` for the reasons above.
