### ISSUE TITLE
true hardwrap

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#5443]
We can set tw=80 for instance, for hardwrap however editing the line in middle will increase the total length of the line beyond 80 characters, in fact it is possible to get arbitrarily long lines this way. This is extremely uncomfortable since many commands will no longer work as intended like go to end beginning of line.  I imagine this is less of a problem for code, but for something like latex, markdown it is a huge problem. I think something like fo+=a is meant to partially address this but it only make sense for plain text (if that). In latex, markdown there are commands that like to be on their own line and fo+=a will mess with that.

Edit:
Here is a more explicit summary: 1) Give an option to make hardwrap at tw=X behave **visually** as  softwrap at tw=X, although the latter does not exist yet, it can be simulated with a plugin like Goyo for example.
2) Or what would be sufficient  and probably much easier to implement is to give an option so that all commands which have to do with lines, work with visual lines. Commands like D, dd, go to end of line, etc.

**Comment by phanimahesh** [comment]
`autocmd InsertLeave * gqip` in case you are working with just text?

IMO, autoformatting text is tricky, especially when mixed with code.

You have listed a few issues, all known, but there are no _actionable_ items there. Concrete suggestions will help. Or, would you like to start a discussion on what can be done about this? In that case, mailing list may be better, it has a larger audience.

Can you please edit this to include a one-line summary of what you'd like to see?

**Comment by justinmk** [comment]
This could be done with a `CursorMovedI` plugin, no?

**Comment by yashamon** [comment]
I made an edit with explicit suggestions.

**Comment by yashamon** [comment]
I think perhaps the suggestion 2) is not just simpler but more desirable, since it helps also people preferring to work purely with softwrap. So perhaps I should just repost with the second suggestion as the main proposal?

**Comment by lewis6991** [comment]
Closing as unplanned since there hasn't been any further desire for this.
