### ISSUE TITLE
regression: mis-aligned Chinese characters

### ISSUE THREAD

**Issue by ahlks** [neovim/neovim#5448]
- `nvim --version` :v0.1.6-190-g91d13bd
- Vim (version: ) behaves differently?
- Operating system/version: linux 4.4.0-2-deepin-amd64
- Terminal name/version: deepin terminal
- `$TERM`:xterm-256color

   Question:
When I open a window, I scroll the window with Chinese characters, the contents of the other window display will be affected, the Chinese character display is abnormal

**Comment by mhinz** [comment]
Is it the same in Vim?

**Comment by justinmk** [comment]
@ahlks This sounds like #3875. Do any of the workarounds in there "fix" the issue? E.g., does scrolling up/down 1 line fix it? 

Are you using airline.vim plugin? Does disabling it help? 

If you follow [these steps](https://github.com/neovim/neovim/issues/3875#issuecomment-243247625) (using a Chinese-character file) does the problem occur?

Does the problem occur with [this minimal vimrc](https://github.com/neovim/neovim/issues/3875#issuecomment-243414272) ?

Does [this workaround](https://github.com/neovim/neovim/issues/3875#issuecomment-244374084) fix the issue?

**Comment by ahlks** [comment]
I have not tried on vim.
It does not occor In previous versions, but after the recent update, it always occur
I have not used airline.vim plugin, and @justinmk  your steps is no effect.
I think neovim itself causes the bug

**Comment by justinmk** [comment]
> It does not occor In previous versions, but after the recent update,

What was the previous version you were using? Can you upload a Chinese-character file which causes the issue? 

If you know how to bisect using git, that would be most helpful.

**Comment by ahlks** [comment]
version v0.1.6-123-g764f576 is normal
using version: v0.1.6-201-g4408431
two picture, one is normal other isn't normal
![zhengchang](https://cloud.githubusercontent.com/assets/20379044/19218850/23f57f78-8e37-11e6-9e64-605a95deda86.png)
![yichang](https://cloud.githubusercontent.com/assets/20379044/19218854/38c1ec7a-8e37-11e6-8f6c-d9d3185d6ee6.png)

**Comment by justinmk** [comment]
Thanks. Without a sample file (not screenshot), it might be difficult for others to reproduce. Can you [git bisect](https://git-scm.com/book/tr/v2/Git-Tools-Debugging-with-Git#Binary-Search) to find the exact commit that caused the problem? We know that 764f576 is good and 4408431 is bad. So then try a commit in the middle of those. And so on...

**Comment by ahlks** [comment]
@justinmk 
9e1c659666b5909b0ebb77406db42bc6892659d6 is the first bad commit
commit 9e1c659666b5909b0ebb77406db42bc6892659d6
Author: James McCoy <jamessan@jamessan.com>
Date:   Thu Sep 22 00:58:46 2016 -0400

    vim-patch:7.4.1697
    
    Problem:    Display problems when the 'ambiwidth' and 'emoji' options are not
                set properly or the terminal doesn't behave as expected.
    Solution:   After drawing an ambiguous width character always position the
                cursor.
    
    https://github.com/vim/vim/commit/cb0700844c1274fe8bc0ceaffaee0ad21c406f30

**Comment by justinmk** [comment]
@ahlks Thanks! If you can try Vim 7.4.1697 (or later), that will tell us whether we caused this bug or if it is a Vim bug. Could be related to https://github.com/neovim/neovim/pull/5372#issuecomment-248815370.

**Comment by ahlks** [comment]
I try Vim 7.4a.017 and Vim 8.0, and did not cause the bug

**Comment by qvacua** [comment]
I guess the quick and dirty fix would be something like https://github.com/qvacua/neovim/commit/ca8a0b3d0ea6791cabe683b867a9a7598d3256d9. But it's strange that vim does not have the problem even when it checks `utf_ambiguous_width()` first...

If you want to,

1. I could create a PR, but it's really a _quick and dirty_ fix... One probably should look into `mb_ptr2cells` and `utf_ambiguous_width()`.
2. I could look into this a bit further...

**Comment by jamessan** [comment]
Well, as  I mentioned in https://github.com/neovim/neovim/pull/5372#issuecomment-248815370, I'm not sure what the equivalent of Vim's `screen_cur_col = 9999;` would be in Neovim.  In Vim, this appears to be used to trigger forced repositioning of the cursor in `windgoto`:

```c
 9012     void
 9013 windgoto(int row, int col)
 9014 {
...
 9036     if (col != screen_cur_col || row != screen_cur_row)
 9037     {
...
 9066         if (row >= screen_cur_row && screen_cur_col < Columns)  <== false since screen_cur_col is 10000
 9067         {
...
 9242         }
 9243         else
 9244             cost = 999;
 9245  
 9246         if (cost >= goto_cost)  <== true
 9247         {
 9248             if (noinvcurs)
 9249                 screen_stop_highlight();
 9250             if (row == screen_cur_row && (col > screen_cur_col)  <== false
 9251                                                              && *T_CRI != NUL)
 9252                 term_cursor_right(col - screen_cur_col);
 9253             else
 9254                 term_windgoto(row, col);  <== Call term_windgoto
 9255         }
```

However, the next call to `windgoto` happens the next time `screen_char` is called, where as I forced the flush to happen right away by calling `flush_cursor_update`.  Does this help?

```diff
diff --git i/src/nvim/ui.c w/src/nvim/ui.c
index 648d633..82087ce 100644
--- i/src/nvim/ui.c
+++ w/src/nvim/ui.c
@@ -399,7 +399,6 @@ static void send_output(uint8_t **ptr)
     col++;
     if (utf_ambiguous_width(*p)) {
       pending_cursor_update = true;
-      flush_cursor_update();
     } else if (mb_ptr2cells(p) > 1) {
       // double cell character, blank the next cell
       UI_CALL(put, NULL, 0);
```

It's also not clear to me why we have the `UI_CALL(put, NULL, 0);` in the `mb_ptr2cells(p) > 1` branch.  There doesn't seem to be equivalent code in Vim.  Vim just increments the column by 1 (which we also do).

**Comment by qvacua** [comment]
Without the `UI_CALL(put, NULL, 0)`-call the UI probably has to compute by itself whether the char is stored as single- or double-cell in the backend. In Vi it's not nec' maybe because it somehow clears the (complete?) grid and therefore knows that the next cell is already `NULL`?

Anyhow, `utf_ambiguous_width(*p)` returning `1` for double-cell chars is odd...

**Comment by jamessan** [comment]
Does removing the `flush_cursor_update();` call help at all?

**Comment by qvacua** [comment]
As far as I can see it, the problem is that for many chars `UI_CALL(put, NULL, 0)` is not called because they get caught in the first `if`-block. (At least that's the reason why VimR's rendering is broken)

**Comment by justinmk** [comment]
@tarruda Any chance you could verify the suggestions here? Also see https://github.com/qvacua/neovim/commit/7e2fc807ba709613b48b4c304ab333112e74a117

**Comment by qvacua** [comment]
I think I have found the issue (I'm not quite sure about the solution though): the order of the `if`-blocks is correct (or is not the problem). You have to use `utf_ambiguous_width(*((int*)p))` instead of just `(*p)`. If we use `*p`, only the first byte of the char gets evaluated by `utf_ambiguous_width` which is not enough sine we want to evaluate multibyte chars. What I'm not sure about is, does the `while (*p >= 0x20)` guarantee that the char at hand is `int`-long??? (A quick test with VimR did not reveal any problem though...)

I don't know why Vim does not have the same problem...

**Comment by jamessan** [comment]
> You have to use `utf_ambiguous_width(*((int*)p))` instead of just `(*p)`.

Ah, good catch.  In Neovim, `p` is `uint8_t *` but in Vim it is directly accessing `ScreenLinesUC` which is an array of `u8char_T` (which is itself a typedef for `int`, assuming `int` is at least 32-bits long).

So, the question becomes, how is it that we're going from storing data about the screen in terms of `uint32_t` (`ScreenLinesUC` is an array of `uint32_t` in Neovim) but sending it to the UIs as `uint8_t`?

**Comment by jamessan** [comment]
> how is it that we're going from storing data about the screen in terms of `uint32_t` (`ScreenLinesUC` is an array of `uint32_t` in Neovim) but sending it to the UIs as `uint8_t`?

Nevermind, that's handled by the `mb_ptr2len` call, which determines how much data (starting at `p`) will be sent.

**Comment by jamessan** [comment]
Although, that does make me wonder if there are any endian issues.

**Comment by qvacua** [comment]
If endianness might the problem, then Vim also would have the same issue, no?

So, up the possible endian problem, you guys think that the type-punning to `int` will fix the problem?

**Comment by jamessan** [comment]
Well, endianness isn't an issue yet (and never will be for Vim) since I don't think there are many people running nvim on one system and an nvim front-end on another system (with a different endianness).

**Comment by jamessan** [comment]
Also, Vim's code doesn't use a `char *` here like we are.  It directly passed `ScreenLinesUC[offset]` into `utf_ambiguous_width`.  Neovim's problem is that when we get to the UI code, we're dealing with an array of `char *` and need to convert that back to a `uint32_t` for the call to `utf_ambiguous_width`.

**Comment by justinmk** [comment]
> whether there's a defined byte ordering for data sent from nvim to a UI.

msgpack [is big-endian](https://github.com/msgpack/msgpack/blob/master/spec.md). 
And de/serialization implementations are [expected to handle it](https://github.com/msgpack/msgpack/issues/107).

@tarruda's [libmpack](https://github.com/tarruda/libmpack) (which we use for lua-client, but not in core nvim, yet) handles endianness (`mpack_is_be()`).

> I don't think it's going to be generally safe to just treat the char * as an int *

Could we check `#ifdef ORDER_BIG_ENDIAN` as in `shada.c:be64toh()`?   https://github.com/neovim/neovim/blob/4a8b75be0f7279dac2ad98c1e95263e9b35b74b7/src/nvim/shada.c#L3153

**Comment by tarruda** [comment]
Endianess is not an issue, all screen data is sent as utf-8.

> Neovim's problem is that when we get to the UI code, we're dealing with an array of char * and need to convert that back to a uint32_t for the call to utf_ambiguous_width.

AFAIR, when implementing/testing the UI protocol there was no need to use uint32_t codepoints because nvim will always sends precise coordinates of where to draw characters. For example, let's say at position (1, 2) there are 3 chinese characters with column width of 2, followed by an english character of width 1, it would send the following instructions:

- goto (1, 2)
- output utf-8 data for the 3 chinese characters
- goto (7, 2) (6 cells characters jumped)
- output utf-8 data for the english character

It's been some time since I've written this code so I may be missing something, but I at least remember clearly that it was my intent to never have UIs calculating cells where characters should be positioned.

Does this bug happen in any utf-8 terminal(urxvt for example). Anyone tried on other UIs?

**Comment by justinmk** [comment]
> Anyone tried on other UIs?

It happens in the terminal and in VimR (a remote GUI), at least. Note that the bug was introduced in a [recent commit](https://github.com/neovim/neovim/commit/9e1c659666b5909b0ebb77406db42bc6892659d6) after trying to adapt [this vim patch](https://github.com/vim/vim/commit/cb0700844c1274fe8bc0ceaffaee0ad21c406f30).

**Comment by tarruda** [comment]
@ahlks can you post a file with the characters that reproduce this issue?

**Comment by haifengkao** [comment]
@tarruda I can
```
他在他的經典之著《中立和集體安全》中說明:「人類之所以會發生戰爭,不是因為人類是惡的或沒有國家社會意識的,而是因為國家讓我們成為保守的 而且是智慧有限的人們。」 
```

See above issue for screenshots.

**Comment by qvacua** [comment]
I did some more experiment and I think that the endianness is indeed a problem. For example, let's assume we do `send_output(하)`, then (on a Mac, little-endian)

```
p = ed 95 98 00, thus
*((uint32_t *)p) = 00 98 95 ed, but
하 = 00 ed 95 98
```

So do we have to use sth. like

```
static uint32_t convert_le_utf8_to_be(uint32_t target, size_t length)
{
  uint32_t shifted = target << ((4 - length) * 8);
  
  return ((shifted >> 24) & 0x000000ff) |
         ((shifted <<  8) & 0x00ff0000) |
         ((shifted >>  8) & 0x0000ff00) |
         ((shifted << 24) & 0xff000000);
}

static void send_output(uint8_t **ptr)
{
  ...
  uint32_t p_as_utf8 = *((uint32_t *) p);
  if (utf_ambiguous_width(convert_le_utf8_to_be(p_as_utf8, clen)) {
    ...
  } ...
  ...
}
```

Makes sense?

**Comment by jamessan** [comment]
What about just using `utf_ptr2char`?

**Comment by qvacua** [comment]
@jamessan -_- I did not know about that function (as you might have guessed, I'm not familiar with NeoVim's code base...). Does it do the same thing? 😅

**Comment by jamessan** [comment]
Can you test if this also fixed the issue?

```diff
diff --git i/src/nvim/ui.c w/src/nvim/ui.c
index 648d633..b16ef42 100644
--- i/src/nvim/ui.c
+++ w/src/nvim/ui.c
@@ -397,7 +397,7 @@ static void send_output(uint8_t **ptr)
     size_t clen = (size_t)mb_ptr2len(p);
     UI_CALL(put, p, (size_t)clen);
     col++;
-    if (utf_ambiguous_width(*p)) {
+    if (utf_ambiguous_width(utf_ptr2char(p))) {
       pending_cursor_update = true;
       flush_cursor_update();
     } else if (mb_ptr2cells(p) > 1) {
```

**Comment by qvacua** [comment]
It fixes the problem with Korean and Chinese chars, but Emojis like 😎, which should occupy two cells, run into the ambiguous `if`-block since  `utf_ambiguous_width` returns `>0` for all Emojis (`intable(emoji_all, ARRAY_SIZE(emoji_all), c)`)... But that seems to be intentional (why?)...

**Comment by jamessan** [comment]
Well, all the "ambiguous" check does is see if the cursor needs to be force-updated next time something is output.  That's this commit:

```
commit cb0700844c1274fe8bc0ceaffaee0ad21c406f30
Author: Bram Moolenaar <Bram@vim.org>
Date:   Sat Apr 2 22:14:51 2016 +0200

    patch 7.4.1697
    Problem:    Display problems when the 'ambiwidth' and 'emoji' options are not
                set properly or the terminal doesn't behave as expected.
    Solution:   After drawing an ambiguous width character always position the
                cursor.
```

As far as the width being used for :sunglasses:, that depends on what it's Unicode codepoint is.  At a guess, it's probably below U+1F000, so it's this commit that's causing that behavior:

```
commit 6a08454b93784c92296d4c08456401cbaa74c9d5
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Mar 24 18:24:58 2016 +0100

    patch 7.4.1642
    Problem:    Handling emoji characters as full width has problems with
                backwards compatibility.
    Solution:   Only put characters in the 1f000 range in the emoji table.
```

**Comment by jamessan** [comment]
@qvacua I updated the diff in https://github.com/neovim/neovim/issues/5448#issuecomment-253038460.  Does that also work?  If so, I think that properly aligns us with Vim's behavior (which may need to be revisited later).

**Comment by qvacua** [comment]
Yes, with that https://github.com/neovim/neovim/issues/5448#issuecomment-253038460 I did not see any problem with Korean/Chinese chars. However, as I mentioned, Emojis are treated as single-cell characters, because `utf_ambiguous_width` returns `>0` for all Emojis... I think that this contradicts the implementation of `utf_char2cells`...

**Comment by jamessan** [comment]
> Emojis are treated as single-cell characters, because utf_ambiguous_width returns >0 for all Emojis...

No, that's not the case.  `utf_ambiguous_width` only determines whether or not the cursor needs an update after displaying a certain character.  `utf_char2cells` stills reports all Emoji >= U+1F000 as 2 cells.  Any Emoji < U+1F000 are reported as a single cell due to the commit I mentioned earlier:

```
commit 6a08454b93784c92296d4c08456401cbaa74c9d5
Author: Bram Moolenaar <Bram@vim.org>
Date:   Thu Mar 24 18:24:58 2016 +0100

    patch 7.4.1642
    Problem:    Handling emoji characters as full width has problems with
                backwards compatibility.
    Solution:   Only put characters in the 1f000 range in the emoji table.
```

While this may be something that can be refined more, we're at least on par with Vim here.  The issues you're seeing in nvim should also be seen in vim, and should be handled independently from the text alignment problems.

**Comment by qvacua** [comment]
> `utf_char2cells` stills reports all Emoji >= U+1F000 as 2 cells.
Yes, that's right and therefore the `UI_CALL(put, NULL, 0)` should be made for those chars, too, thus something like

```
if (utf_ambiguous_width(utf_ptr2char(p))) {
  ...
}

if (mb_ptr2cells(p) > 1) { // not else if here as the current implementation
  ...
}
```

such that the (remote) UI treats them as double cell chars.

**Comment by jamessan** [comment]
Ah, right.  Vim's code always adds the NUL, and then handles the cursor/col adjustment.

```c

 8129         buf[utfc_char2bytes(off, buf)] = NUL;
 8130  
 8131         out_str(buf);
 8132         if (utf_ambiguous_width(ScreenLinesUC[off]))
 8133             screen_cur_col = 9999;
 8134         else if (utf_char2cells(ScreenLinesUC[off]) > 1)
 8135             ++screen_cur_col;
```

**Comment by jamessan** [comment]
Hmm, but Vim doesn't advance the column again for any emoji.  Is that right?

What about this:
```diff
diff --git i/src/nvim/ui.c w/src/nvim/ui.c
index cf5e95f..eb50041 100644
--- i/src/nvim/ui.c
+++ w/src/nvim/ui.c
@@ -397,13 +397,14 @@ static void send_output(uint8_t **ptr)
     size_t clen = (size_t)mb_ptr2len(p);
     UI_CALL(put, p, (size_t)clen);
     col++;
-    if (utf_ambiguous_width(utf_ptr2char(p))) {
-      pending_cursor_update = true;
-    } else if (mb_ptr2cells(p) > 1) {
+    if (mb_ptr2cells(p) > 1) {
       // double cell character, blank the next cell
       UI_CALL(put, NULL, 0);
       col++;
     }
+    if (utf_ambiguous_width(utf_ptr2char(p))) {
+      pending_cursor_update = true;
+    }
     if (col >= width) {
       ui_linefeed();
     }
```

Performing the `UI_CALL` has to happen before `pending_cursor_update`, otherwise the cursor isn't placed properly.

**Comment by jamessan** [comment]
Although, I do see a difference in the way :sunglasses: is aligned between vim and nvim, regardless of whether the suggested patch above is applied.

nvim's initial rendering is the same, but if you force a redraw, the emoji is drawn a little lower.  Move the cursor back over the emoji and it is rendered at the same height it initially was.

![Emoji Alignment](http://imgur.com/n4bgUzT)

**Comment by qvacua** [comment]
Your last patch works well. However, at least with VimR I don't have the vertical alignment problem you described. Maybe that's some rendering issue of the terminal you're using?

**Comment by jamessan** [comment]
> Your last patch works well.

Great.  Just pushed it.

**Comment by wsdjeg** [comment]
@jamessan thanks,I got same issue, an it is fixed in master now.
