### ISSUE TITLE
`make PREFIX` fails after `make distclean`

### ISSUE THREAD

**Issue by chandru2012** [neovim/neovim#5458]
- `nvim --version`: 0.1.5
- Vim (version: ) behaves differently?
- Operating system/version: centos 6.5
- Terminal name/version: ssh
- `$TERM`: xterm-256color
### Command

make PREFIX=$HOME/local/bin/neovim CMAKE_BUILD_TYPE=Release
### Output

make[3]: usr/bin/luarocks: Command not found
CMakeFiles/mpack.dir/build.make:60: recipe for target 'usr/lib/luarocks/rocks/mpack' failed
make[3]: **\* [usr/lib/luarocks/rocks/mpack] Error 127
make[3]: Leaving directory '/home/ubuntu/neovim-0.1.5/.deps'
CMakeFiles/Makefile2:571: recipe for target 'CMakeFiles/mpack.dir/all' failed
make[2]: **\* [CMakeFiles/mpack.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/neovim-0.1.5/.deps'
Makefile:83: recipe for target 'all' failed
make[1]: **\* [all] Error 2
make[1]: Leaving directory '/home/ubuntu/neovim-0.1.5/.deps'
Makefile:75: recipe for target 'deps' failed
make: **\* [deps] Error 2

**Comment by justinmk** [comment]
Did you check https://github.com/neovim/neovim/wiki/Building-Neovim#centos--rhel--fedora ?

luarocks should be downloaded automatically and stored in `.deps` unless you specified `USE_BUNDLED_DEPS=0`. Without more information we can't know why luarocks isn't available in this case.

**Comment by chandru2012** [comment]
I found luarocks bin, lib, share folders were installed in $HOME/local/bin/neovim,
than i moved those files to .deps/usr/bin, .deps/usr/lib, .deps/usr/share respectively, than compilation was successful but neovim installed in /usr directory instead of directory $HOME/local/bin/neovim  that i provided for make's PREFIX argument

**Comment by chandru2012** [comment]
@justinmk
please check my previous comment, i did not faced any problem with libuv even though autoconf version in linux is 2.63

**Comment by mhinz** [comment]
`PREFIX` was added just recently, but you try to use 0.1.5?

If so, you'll have to use this instead:

```
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PATH=$HOME/local" CMAKE_BUILD_TYPE=Release
```

**Comment by chandru2012** [comment]
Thanks @mhinz 
Compilation successful but **make install** installing in /usr directory instead of specified directory
### command
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PATH=$HOME/local" CMAKE_BUILD_TYPE=Release

**Comment by mhinz** [comment]
Try removing `build/` first, then use `make` and `make install` again.

**Comment by chandru2012** [comment]
yes did but still same effect, not installing in preferred directory

**Comment by chandru2012** [comment]
yes please see my previous comments that is what i am doing from the beginning i.e ```$HOME/local/bin/neovim```

**Comment by mhinz** [comment]
No, without the `/bin/`. Everything is installed to that directory, not only an executable. 

And argh, it has to be `-DCMAKE_INSTALL_PREFIX`, not `-DCMAKE_INSTALL_PATH`. (That's the exact reason `PREFIX` was introduced..)

So, for completeness:

```
$ rm -r build
$ make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/local/neovim"
$ make install
```

Afterwards nvim will be installed at `$HOME/local/neovim/bin/nvim`, thus `$HOME/local/neovim/bin` should be part of your `$PATH` environment variable.

**Comment by chandru2012** [comment]
@mhinz thanks, its working now

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/5447#issuecomment-252849167
