### ISSUE TITLE
Broken OSX clipboard

### ISSUE THREAD

**Issue by pippocode** [neovim/neovim#5460]
- `nvim --version`: 0.1.5
- Vim (version: 8.0) behaves differently? No. The registers ```'+``` and ```'*``` are missing
- Operating system/version: macOS 10.12 (16A323)
- Terminal name/version: Terminal
- `$TERM`: screen-256color

### Actual behaviour
the command output of
```
:reg
```
has not ```'+``` neither ```'*``` register; the message ```clipboard: error: ``` is there instead
I can't put anything in the system clipboard (mine is ```'+``` register)

Any idea?
thanks

**Comment by justinmk** [comment]
`:help clipboard`

**Comment by pippocode** [comment]
This didn't help.

For future reference: the issue seems to be in tmux environment. Outside of tmux all is fine.
