### ISSUE TITLE
XDG_* environment variables with doubled values source twice

### ISSUE THREAD

**Issue by BertramScharpf** [neovim/neovim#5462]
- 0.1.4:

This is sure a problem of Gentoo (maybe Xfce of URxvt).
### Actual behaviour

When I am
- on Gentoo Linux (not on FreeBSD!)
- in Xfce4
- starting urxvt
- running directly zsh (not inside tmux!)

then I get XDG_\* paths with doubled values.

  % echo $XDG_DATA_DIRS 
  /usr/local/share:/usr/share:/usr/share
  % echo $XDG_CONFIG_DIRS 
  /etc/xdg:/etc/xdg

This sources the plugins under these directories twice
what leads to errors after unbanged function declarations.
### Expected behaviour

The misbehaviour is definitely not Neovim's fault.
Anyway it could be desirable that Neovim detects
the doubled directories and won't source the plugins
a second time.

**Comment by grawlinson** [comment]
Can confirm the first case occurs on Arch Linux using URXVT & ZSH.

```shell
$ echo $XDG_DATA_DIRS 
/usr/share:/usr/share:/usr/local/share
```

These are the only XDG_* environment variables that show up:

```shell
XDG_CURRENT_DESKTOP  XDG_RUNTIME_DIR      XDG_SEAT_PATH        XDG_SESSION_DESKTOP  XDG_SESSION_PATH     XDG_VTNR           
XDG_DATA_DIRS        XDG_SEAT             XDG_SESSION_CLASS    XDG_SESSION_ID       XDG_SESSION_TYPE
```

**Comment by justinmk** [comment]
h1. Task

Modify `src/nvim/os/stdpaths.c` so that duplicate directories are skipped when resolving `XDG_DATA_DIRS` and `XDG_CONFIG_DIRS` .

**Comment by bryanhonof** [comment]
Could I give this a shot?

**Comment by blueyed** [comment]
@bryanhonof sure!

**Comment by tox2ik** [comment]
If you want do be smart about this, then the paths should be resolved like `realpath` or `readlink` does and only remove the resulting duplicate paths and probably broken links too.
