### ISSUE TITLE
jobstart() throws exception for non-exe (when using argv) / and not -1 with string

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5465]
`nvim --version`: v0.1.6-180-geeec0ca

`:let job = jobstart(['nonexe'])` throws `E902: "nonexe" is not an executable`, but the documentation says:

> Returns:
> …
> - -1 if {cmd}[0] is not executable.  

On top of this `:let job = jobstart('nonexe') | echo job` does not return -1, but an incrementing Job ID.

**Comment by justinmk** [comment]
> On top of this `:let job = jobstart('nonexe') | echo job` does not return -1, but an incrementing Job ID.

That's because unlike `jobstart(['nonexe'])` (with brackets), `jobstart('nonexe')` _cannot_ fail, except for the case where `'shell'` is not executable. However, I added a test to cover this anyway.
