### ISSUE TITLE
layout in a mess with Tagbar plugin

### ISSUE THREAD

**Issue by jackywu** [neovim/neovim#5469]
- `nvim --version`: NVIM 0.1.6-dev
- Operating system/version: Sierra ，10.12 
- Terminal name/version: iterm2，Build 3.0.10 
- `$TERM`: xterm-256color

### Actual behaviour

open markdown and tagbar, ctrl+u OR ctrl-d to page navigator, or enter p in tagbar split window,  these actions result in layout in a mess.

![screen shot 2016-10-12 at 09 12 55](https://cloud.githubusercontent.com/assets/587955/19294124/8708e402-905c-11e6-8787-6add0c10953d.png)

### Expected behaviour

this is the right layout without any keyboard action.

and vim work fine with tagbar bundle.

![screen shot 2016-10-12 at 09 13 32](https://cloud.githubusercontent.com/assets/587955/19294209/1c9f9380-905d-11e6-8073-49db9fbea7db.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
- u NORC will not load any plugin , so can not reproduce the problem.

**Comment by justinmk** [comment]
Probably the same as https://github.com/neovim/neovim/issues/5448. Can you try https://github.com/neovim/neovim/pull/5461?
