### ISSUE TITLE
Running nvim in a neovim terminal should not create a nested neovim

### ISSUE THREAD

**Issue by tecywiz121** [neovim/neovim#5472]
This is pretty much a feature request. I'd like running `nvim file.txt` from inside the neovim terminal emulator to open the file in the already existing neovim instance instead of nesting it.

Could be implemented by aliasing `nvim` (or by modifying `PATH`) inside the terminal emulator to a special binary that sends commands to the controlling neovim instance.

**Comment by jamessan** [comment]
See #5155.  This can be achieved using [nvr](https://github.com/mhinz/neovim-remote).

**Comment by tecywiz121** [comment]
Woops, sorry! That's an awesome tool, just wish it was as simple as typing `nvim`. Thanks :)

**Comment by victoriastuart** [comment]
@tecywiz121 -- this was also a big desireable for me. I use Krusader as my file manager on an Arch Linux system, and neovim as my de facto text editor.  To open files from Krusader in the existing nvim session, here is what I did; I hope it helps you, others!  ;-)

---

https://github.com/mhinz/neovim-remote

    cd /mnt/Vancouver/apps
    git clone https://github.com/mhinz/neovim-remote

neovim-remote installed in home env (Python 3.6.4):

    cd /mnt/Vancouver/apps/neovim-remote/
    sudo pip3 install neovim-remote

* Open files always in the same nvim no matter which terminal you're in.
 ** If you just run nvr -s, a new nvim process will start and set its address to /tmp/nvimsocket automatically.
 ** Now, no matter in which terminal you are, nvr file will always work on that nvim process. That is akin to emacsclient from Emacs.

* Set neovim as default MIME type -- sequentially navigate:

```
Krusader
right-click on file (e.g. some_file.txt)
Properties
General tab
File Type Options
[Add Neovim if not present]
Select Neovim
Edit...
Application tab
Command: nvr-s
```

* Quit existing nvim session
* (From now on) start Neovim with: `nvr`
* NOW, when I double-click a file in Krusader (set via "File Type Options" to open with neovim via "nvr -s"), it will open in the EXISTING nvim session!! :-D
