### ISSUE TITLE
neovim should never flicker

### ISSUE THREAD

**Issue by zhou13** [neovim/neovim#5473]
### Actual behaviour

vim/neovim flickers when I scroll, very obvious when `cursorline` is on.  GIF Example: http://stackoverflow.com/questions/25170389/flickering-screen-when-scrolling-in-gvim

### Expected behaviour

Flicker means that there is a black frame inserted between screen refresh.  A well-written software will use double buffer to avoid this.

**Comment by justinmk** [comment]
Nvim-qt has very little flicker. Did you try it? Which UI are you talking about? If TUI, please mention which terminal emulators you tried.

**Comment by zhou13** [comment]
Just tried it and it works super smoothly! Thank you for the information. I am using xfce-terminal, so it is the vte3 emulator.

**Comment by justinmk** [comment]
PRs improving this are welcome, but this request is too general. So, closing.
