### ISSUE TITLE
ftplugin/shada.vim: Error writing shada file

### ISSUE THREAD

**Issue by HarmtH** [neovim/neovim#5482]
- `nvim --version`: v0.1.6-234-g8cc760a
- Vim (version: ) behaves differently? n/a
- Operating system/version: n/a
- Terminal name/version: n/a
- `$TERM`: n/a
### Actual behaviour

```
Error detected while processing function shada#get_binstrings[1]..shada#strings_to_sd[9]..<SNR>23_shada_convert_strings[87]..<SNR>23_shada_eval[1]..msgpack#eval:
line  126:
E605: Exception not caught: char-invalid:Invalid integer character literal format: ''
Error detected while processing function shada#get_binstrings[1]..shada#strings_to_sd[9]..<SNR>23_shada_convert_strings:
line   87:
E170: Missing :endwhile
```

I did not manually change my shada file before. Just opened it cleanly and tried to write it.
### Expected behaviour

Shada file is written
### Steps to reproduce using `nvim -u NORC`

I'm not going to post my whole shada file, I will try to narrow it down to the bad line.

**Comment by HarmtH** [comment]
Offending shada file:
```
Header with timestamp 2016-10-14T16:00:40:
  % Key______  Value
  + encoding   "utf-8"
  + generator  "nvim"
  + max_kbyte  10
  + pid        29264
  + version    "NVIM v0.1.6-234-g8cc760a"
History entry with timestamp 2015-12-11T12:08:49:
  @ Description_  Value
  - history type  SEARCH
  - contents      "^\\s*let\\s\\+b:atp_LocalColors\\>"
  - separator     ''
```

**Comment by HarmtH** [comment]
Seperator should not be empty, I have no idea how I managed to do that

**Comment by HarmtH** [comment]
Using ```#``` or ```*``` for searching gives an empty separator and seems to be the problem.

**Comment by justinmk** [comment]
> Using # or * for searching gives an empty separator

Is that happening with `nvim -u NORC`? Can you give precise steps?

**Comment by HarmtH** [comment]
Yes it is, and no problem:
```
nvim -u NORC -i sha.shada
ibla bla<esc>*:qa!
nvim -u NORC sha.shada
```
Observe the empty seperator.

**Comment by justinmk** [comment]
I see, this not a problem with the `'shada'` feature, it's a bug in the `runtime/ftplugin/shada.vim` plugin. A workaround is:

```
:noau e sha.shada
:noau w sha.shada
```

That allows writing the file, but of course doesn't help if you're actually trying to edit the shada file by hand.

**Comment by HarmtH** [comment]
Ah sorry didn't see the ambiguity. I was indeed trying to modify my shada file.

**Comment by justinmk** [comment]
There is extensive coverage of the shada plugin in `test/functional/plugin/shada_spec.lua`. Adding a failing test there may give insight.
