### ISSUE TITLE
NeoVim v0.1.5 `make` fail on Fedora 23

### ISSUE THREAD

**Issue by unclechu** [neovim/neovim#5489]
As I understand `make` from project root directory should download and build anything I need but I got an error that it can't find `luarocks`.
```bash
$ uname -a
Linux unclefarm23 4.7.6-100.fc23.x86_64 #1 SMP Mon Oct 3 18:15:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
`make` command:
```bash
make distclean && make PREFIX=$HOME/neovim-v0.1.5-git
```
Log from this command: https://pastebin.com/DrQamz0N
Commit hash: `5b8255e251e121b814826d127a383bf3054cac80` (`v0.1.5` tag)

**Comment by mhinz** [comment]
v0.1.5 doesn't know about PREFIX. Use this instead:

```
make distclean && make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim-v0.1.5-git
```

**Comment by justinmk** [comment]
Even so, based on https://github.com/neovim/neovim/pull/5447#issuecomment-252937387 I think we need to revert the PREFIX commit.

also refrence https://github.com/neovim/neovim/issues/5458

**Comment by unclechu** [comment]
@mhinz your solution works for me, thanks a lot (but fix it, you missed double quote at the end of the line).
