### ISSUE TITLE
IWYU: remove superfluous includes with include-what-you-use

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#549]
Google has a tool called [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) that can detect redundant/unnecesary/... header includes. This would be a great way to automatically clean up the includes list in the style of the Golang compiler. As a nice bonus, it could speed up builds as the dependency tree will get smaller. If it's reasonably fast my suggestion would be to run it with travis.

I currently haven't got the time to experiment with this tool, but if anyone does, that would be nice.

This issue was inspired by #548.

---
- concrete case for IWYU: https://github.com/neovim/neovim/issues/918
- Related article: http://zeuxcg.org/2010/11/15/include-rules/
- CMake support for IWYU: http://stackoverflow.com/a/30951493/152142

**Comment by hunterwerlla** [comment]
Is this still a problem? It seems like it would not take very long to run include-what-you-use on every source file and test that it still compiles. I ran it on some source files and its seems that superfluous includes, or includes that should be added, still exist.

**Comment by justinmk** [comment]
@hunterwerlla Follow the discussion starting with https://github.com/neovim/neovim/issues/549#issuecomment-54023726 for the current state of affairs. Help is wanted to address this, if you are inclined.

**Comment by ZyX-I** [comment]
I think it is possible to work around: when using IWYU run it on a partially preprocessed headers: basically all `#ifdef INCLUDE_GENERATED_DECLARATIONS` sections replaced with generated content.

**Comment by kylo252** [comment]
@justinmk, is this still up for grabs? 

Related https://github.com/neovim/neovim/issues/6371

**Comment by justinmk** [comment]
# Status

- IWYU seems to run on our sources now https://github.com/neovim/neovim/pull/19875 , and is now mentioned in CONTRIBUTING.md https://github.com/neovim/neovim/pull/19891
- TODO: can IWYU be automated in our build / CI?

**Comment by dundargoc** [comment]
Clang now has [include-fixer](https://clang.llvm.org/extra/clang-include-fixer.html). I played around with it for a bit and it seemed more accurate than IWYU, so could be worth switching to that instead.

**Comment by dundargoc** [comment]
This is done. See https://github.com/neovim/neovim/issues/6371#issuecomment-1887951816 for more information.
