### ISSUE TITLE
NeoVim v0.1.5 building using `cmake` fail on Fedora 23

### ISSUE THREAD

**Issue by unclechu** [neovim/neovim#5490]
So, since I can't build it just using `Makefile` (see #5489 ) I tried to do this using `cmake`, sad but without any success.

I have got error that I need `mpack` that I couldn't find in my distro repos, installed this using `luarocks`, then I get error about `bit` Lua package, that doesn't exist in Fedora repos too, tried install it with `luarocks` (`luarocks install luabitop`) and got this error:
```
Installing https://luarocks.org/luabitop-1.0.2-1.src.rock...
Using https://luarocks.org/luabitop-1.0.2-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include -c bit.c -o bit.o
bit.c: In function ‘barg’:
bit.c:83:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
 #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
  ^

Error: Build error: Failed compiling object bit.o
```
I found [website of the library](http://bitop.luajit.org/index.html) and saw that last release was in 2012, also noticed that last release "add compatibility with both 5.1 and 5.2" and I'm using 5.3. So, why we need compatibility between 5.1 and 5.2? Lua doesn't follow semver? It looks like this.

Guys from #lua on freenode told me that I don't need this lib anymore, because bitwise operations invented in 5.3 and this lib may be incompatible with 5.3. So, again, it looks like Lua doesn't follow semver, that feels surprisingly for me.

What can I do about that?

**Comment by unclechu** [comment]
**UPD** from #lua on freenode:
```text
<Coldseeker> lua versioning seems to be "Incarnation.Major.Minor", rather than the usual "Major.Minor.Patch"
<rjek> Approximately yes
<rjek> 5.3.0 was a major release 
```

**Comment by justinmk** [comment]
Yes, we don't support lua 5.3. We support luajit, lua 5.1 and maybe 5.2.
