### ISSUE TITLE
syntax: vim: vimCommand not recognized correctly

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5491]
- `nvim --version`: v0.1.6-180-geeec0ca
- Vim (version: ) behaves differently? Yes

In a `ft=vim` file, `scriptencoding` and other commands are not recognized as `vimCommand` at the beginning of a line, e.g.:

```vim
scriptencoding utf-8
```

It works when the line is indented (`    scriptencoding utf-8`).

It looks like the fixed list of commands has been replaced by `syn match   vimCommand contained	"\<z[-+^.=]\="` in Neovim (a98a699).
I cannot see what the `\<z` would refer to.  Is it related to `:syn-ext-match`?

/cc @justinmk

**Comment by blueyed** [comment]
I have looked into this when I've noticed that `shell` gets highlighted as `vimOnlyCommand` with:

    let argv = &shell.' '.&shellcmdflag.' '.shellescape(join(argv))

**Comment by justinmk** [comment]
If it's a non-generated part of the syntax file feel free to post a patch.

**Comment by blueyed** [comment]
Oh, I should have known that this gets generated (https://github.com/neovim/neovim/issues/5060), but forgot.

For some reason it was not installed correctly, but `make install` again fixed it.
