### ISSUE TITLE
Very strange cursor movement in Quickfix window.

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#5496]
- `nvim --version`: v0.1.6-250-g0fa4f98
- Vim (version: ) behaves differently? 8.0.32
- Operating system/version: Debian 8 + linux 3.16 x64
- Terminal name/version: both xshell 4 and mintty in cygwin
- `$TERM`:
### Actual behaviour

cursor in quickfix window get rewind to first line after ":caddexpr"
### Expected behaviour

qf cursor position should not be changed when something appended to quickfix.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.vim
:so test.vim
```

here is the source of test.vim:

``` VimL
copen 4
cexpr "1"
caddexpr "2"
caddexpr "3"
caddexpr "4"
caddexpr "5"
wincmd j
set number
exec "normal gg"
exec "normal 5G"
caddexpr "why cursor in qf moved to line 1 after caddexpr ?"
```

Cursor is supposed to be in line 5, but it moves to the top line after a `:caddexpr`

Vim 8.0.32 will not change the cursor position.
But neovim will, that's strange,
I am porting my plugin from vim 8 to neovim.
async job running in background and continue outputing to quickfix window in realtime,

It is necessary for people to explore the output immediately in quickfix while the job is running.
but exploring will be interrupted by moving cursor to the top line automatically 
when there is a new line appended to quickfix.

my plugin is handy in vim, but this 'rewind issue' in neovim, make it difficult to use.

a lot of plugins will use quickfix to display outputs of background jobs, It is not a good user experience to get cursor rewind after each ":caddexpr".

Is that an issue ? or something like a special FEATURE in neovim ?

**Comment by justinmk** [comment]
Could you compare an older version of Vim  ? We're missing some quickfix patches.

**Comment by skywind3000** [comment]
I have tried version vim 7.4.576, and 7.3
it behaves exactly the same with neovim, but it is a very ancient vim version now.

**Comment by justinmk** [comment]
Ok, so this will be fixed once we merge those patches.

**Comment by jamessan** [comment]
Is this the same issue you opened on the vim tracker, which was closed because you found extra spaces on the end of your `normal` commands?

**Comment by jamessan** [comment]
Nevermind. I should have read the full description first.

**Comment by skywind3000** [comment]
thanks very much

**Comment by skywind3000** [comment]
quickfix window will play a more important role in the feature after async job system has been widely used.
Hope it will get better in neovim.

and thank u very much

**Comment by justinmk** [comment]
> Cursor is supposed to be in line 5, but it moves to the top line after a :caddexpr

Fixed on master. Thanks for the report, and test case @skywind3000

**Comment by skywind3000** [comment]
thanks for your hard work I will try it later
