### ISSUE TITLE
E227: mapping already exists for gx

### ISSUE THREAD

**Issue by KKPMW** [neovim/neovim#5498]
Error when mapping `gx` to `<nop>`:

    Error detected while processing /opt/local/share/nvim/runtime/plugin/netrwPlugin.vim:
    line   82:
    E227: mapping already exists for gx

---

used `.vimrc`:

    filetype indent plugin on
    noremap gx <nop>

---

version ouput:

NVIM 0.1.5
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -pipe -Os -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_editors_neovim/neovim/work/neovim-0.1.5/config -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_editors_neovim/neovim/work/neovim-0.1.5/src -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_editors_neovim/neovim/work/neovim-0.1.5/src/nvim/auto -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_editors_neovim/neovim/work/neovim-0.1.5/include
Compiled by macports@PMW.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

---

The above .vimrc gives no error when using vim.

**Comment by KKPMW** [comment]
Sorry, forgot to add "nocompatible" there. With `set nocompatible` vim produces the same error as well.

**Comment by justinmk** [comment]
That's a netrw bug. It needs to be reported to vim_dev mailing list.
