### ISSUE TITLE
wish: diff-mode and ignoring parts for diffing

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#5510]
"diff-mode" would benefit if there was a way to define patterns to ignore content, eg. by "normalizing" parts of the text that match these patterns to a single space (or the pattern ID, though that wouldn't be "ignoring" any more).

For example, disassembly is likely to have different address column data; these "changes" should be ignored, but the rest of lines should be compared as usual. I don't want to remove all the possibly different data, because that makes matching up with the binary much harder.

Perhaps the `conceal` framework would be a nice starting value, and the "cchar" equivalent could specify the string to use instead (defaulting to some unique pattern ID?)

**Comment by phmarek** [comment]
Example: generated jump targets
```diff
-    276d:      0f 82 db 00 00 00       jb     284e <__function.isra.27+0xfe>
+    276d:      0f 82 db 00 00 00       jb     284e <__function.isra.26+0xfe>
```

Example: code reordering, different locations
```diff
-    ccd7:      0f 85 1c 01 00 00       jne    cdf9 <do_unqueued_work+0x239>
+    ccd7:      0f 85 a1 00 00 00       jne    cd7e <do_unqueued_work+0x1ce>
```

**Comment by justinmk** [comment]
Thinking on this more, this should already be possible via `'diffexpr'` , see https://github.com/neovim/neovim/issues/1466#issuecomment-62908113

If someone can outline concrete improvements to make that less cumbersome, that would be worth considering.

**Comment by phmarek** [comment]
Well, perhaps `diffexpr` and some external program can solve that. But IMO that's "just pushing the responsibility away". On the other hand, though, nvim already _doesn't_ do the diff itself, but calls out to `diff` by default. So adding an internal diff-algorithm plus this change needs much more than "just" ignoring parts of text when comparing.

Still, that won't make incremental hiding of changes easy (as I hoped to get via some `conceal`-like nvim-internal feature).

Thanks for the answer; I guess I'll need to write a wrapper for `wdiff` or so.

**Comment by justinmk** [comment]
> adding an internal diff-algorithm 

Ok, that's generically covered by https://github.com/neovim/neovim/issues/1007. 

There was a promising thread a earlier this year on vim_dev: https://groups.google.com/d/msg/vim_dev/dAXpcpHmVw4/YRTt1h0sBAAJ could be worth reviving that discussion and get Bram's comments.

**Comment by chrisbra** [comment]
FWIW, you can use [vim-diff-enhanced](https://github.com/chrisbra/vim-diff-enhanced) to ignore part of a buffer
