### ISSUE TITLE
Ignore word spelling on a per-file basis (ShaDa file?)

### ISSUE THREAD

**Issue by HaleTom** [neovim/neovim#5513]
When writing text, I like to be able to type `]s` and find that there are no spelling errors. This requires that all the the not-spelling-errors are added to a `spell-file` somewhere.

Some files contain specific jargon which I don't want to add to a global `spell-file`, nor do I want to bother with using a separate `spell-file` for each file.

Could the ShaDa file support:
* `zG` - Ignore this word in the current *session*

Or, perhaps a new:
* `zF` ignore this word in the current *file*

**Comment by justinmk** [comment]
> nor do I want to bother with using a separate spell-file for each file.

Though it's not convenient, this would be the mechanism that might make the most sense, implemented by a plugin. I would lean towards that rather than adding some parallel feature to viminfo/shada.

Is there some reason a plugin couldn't satisfy this?
