### ISSUE TITLE
option 'set title' bug: window title stuck in nvim when i quit nvim

### ISSUE THREAD

**Issue by liangguohuan** [neovim/neovim#5516]
- `nvim --version`: 0.1.6-dev
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 14.04.5 LTS
- Terminal name/version: Gnome-Terminal: 3.6.2
- `$TERM`: xterm-256color

                   add options 'set title' to  file 'init.vim'

### Actual behaviour
the terminal still keep the title what nvim set when i quit nvim, It is chaos really.
### Expected behaviour
the terminal window title can be recover like vim when i quit nvim
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment]
It's a known issue, with some nuance: https://github.com/neovim/neovim/issues/4063

Help would be appreciated in fixing this, but it's not a priority otherwise.
