### ISSUE TITLE
Question: Does Neovim work with Vim 8.0 features?

### ISSUE THREAD

**Issue by pcgeek86** [neovim/neovim#5520]
Hey folks, I'm not a huge Vim user (yet), but I'm just curious to know if Neovim works with the new Vim 8.0 features, like channels, jobs, packages, async I/O, etc.?

**Comment by tweekmonster** [comment]
For async jobs/channels the short answer is: No.  This is a detail that mainly concerns plugin developers.  Though, nvim's is arguably much easier to understand and use.  @justinmk recently went into detail about this: https://www.reddit.com/r/neovim/comments/58nrwv/neovim_api_comparison_with_vim_channels/

I think packages are already ported.  You can look at `:h vim-differences` for anything notable.

**Comment by justinmk** [comment]
> if Neovim works with the new Vim 8.0 features, like channels, jobs, packages, async I/O, etc.?

Nvim supports Vim packages, and generally we merge in all Vim features. 

However, we don't have near-term plans to support Vim8's jobs API. Nvim has a better, more reliable jobs API, and many other features that Vim8 does not have (see `:help nvim-features`). Vim8 "channels" are similar to the old Vim netbeans API, which we've never supported; instead we have a structured API with [numerous clients](https://github.com/neovim/neovim/wiki/Related-projects#api-clients) (you can think of a client as an "SDK"). Vim8 does not have any clients/SDKs, and does not support externalized UIs at all.

**Comment by pcgeek86** [comment]
Thanks for the quick responses, folks. Very helpful information. Just trying to get an understanding of how Neovim fits into the picture. 

That's great that Neovim supports client SDKs. Are the SDKs provided with a primary intent of allowing Neovim to be embedded in graphical applications, or something else?

I see Vim / Neovim as benefiting more from outgoing hooks (eg. debuggers, code linting, code auto-completion), versus incoming hooks, but I'm curious to hear what reasons the hooks are provided for.

**Comment by justinmk** [comment]
The clients are two-way. You can use them to build plugins.

**Comment by wsdjeg** [comment]
@pcgeek86 I just build a irssi like chat plugin for tecent qq, a chinese chat program. the plugin is based on neovim's job feature. it is much better than vim8!

**Comment by mitermayer** [comment]
> However, we don't have near-term plans to support Vim8's jobs API. Nvim has a better, more reliable jobs API

The problem is that this increases complexity for vim plugin development when having to support both vim8 (jobs/channels) and neovim.

How much effort is involved in allowing a basic level support?

**Comment by wsdjeg** [comment]
@mitermayer you can use : 
https://github.com/wsdjeg/job.vim
> this is old version of async.vim

https://github.com/SpaceVim/SpaceVim/blob/dev/autoload/SpaceVim/api/job.vim
> This is SpaceVim's job api

or

https://github.com/prabirshrestha/async.vim
> a better plugin wroten by @prabirshrestha
