### ISSUE TITLE
Implement "CTRL-G"/"CTRL-T" for 'incsearch'

### ISSUE THREAD

**Issue by sscherfke** [neovim/neovim#5525]
This vim feature is quite useful and currently missing in neovim:
https://vimhelp.appspot.com/cmdline.txt.html#c_CTRL-G

Also see this question on stackoverflow:
http://stackoverflow.com/questions/40192919/how-to-go-to-the-next-incremental-search-occurrence-then-continue-adding-to-the

**Comment by Shougo** [comment]
This feature is introduced by Vim 7.4.2259 and 7.4.2268.
They are not merged in neovim.

**Comment by justinmk** [comment]
We merge most Vim patches. Help is welcome to speed it up :)

https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

**Comment by Shougo** [comment]
@sscherfke You can port them if you really needed the feature.
