### ISSUE TITLE
seg fault hard

### ISSUE THREAD

**Issue by NikolaMandic** [neovim/neovim#5531]
- `nvim --version`: 0.1.5
- Vim (version: ) behaves differently? works
- Operating system/version: Mac not siera
- Terminal name/version: iterm2 build 3.0.9 zsh tmux 256 colors 
- `$TERM`: screen-256color

### Actual behaviour
seg fault once i try to use unite to git grep trought repo where there is a file with one line that is huge like minified javascript
so I do unite git grep and if it matches one big line BOOM seg fault while vim works

### Expected behaviour
git grepped output to vim unite window
### Steps to reproduce using `nvim -u NORC`
assumption:
there is a big line that once goes trough git grep and into window of neovim it crashes

**Comment by justinmk** [comment]
Seems the same as https://github.com/neovim/neovim/issues/5234 . If you can produce a different backtrace or different steps to reproduce, we can re-open this.
