### ISSUE TITLE
New highlight group for quickfix current line

### ISSUE THREAD

**Issue by CallumHoward** [neovim/neovim#5536]
Currently the selected line in the quickfix window is highlighted with the Search hilighting group.
It would be nice to have a seperate highlight group linked to Search by default as discussed [here](http://stackoverflow.com/questions/13220073/vim-highlight-quickfix-selected-line-with-color-different-than-search).
A patch for Vim8 to achieve this can be found [here](https://gist.github.com/anishsane/5125b87ea4cddb43985496abd26a43e7).

**Comment by tweekmonster** [comment]
This was implemented a couple months back in #5156.  You can use the `QuickFixLine` highlight group.

**Comment by CallumHoward** [comment]
That's great news, thanks! Apologies for the duplicate issue.
