### ISSUE TITLE
Just-in-time compilation for Vimscript

### ISSUE THREAD

**Issue by tbodt** [neovim/neovim#5537]
Would have to be a pretty long-term thing, but this would make vim a lot snappier for people with a lot of plugins, like me. I'm pretty sure the main thing slowing vim down is executing vimscript, this could speed things up without needing to rewrite all your plugins with a client/server model.

Just an idea.

**Comment by justinmk** [comment]
Would lua not be a reasonable alternative to that?

Also keep in mind, there are usually bottlenecks that cause things to be slow. Those bottlenecks can be solved. Even if vimscript were 10x faster, if you install 10x more plugins, you're back to where you started. 

Plugin design is the main factor. You can install 1000 (one thousand) plugins. If the plugins are autoloaded, it won't slow down startup. If they are only activated in contexts where they are useful, then again, there won't be much performance penalty.

For performance-critical logic (e.g. activated on `CursorMoved`), lua plugins might be an improvement, or job-control/async approach. JIT isn't going to change the fundamentals there.

**Comment by mudox** [comment]
Can the community provides a special Lua plugin programming documentation topic page.
For example to publish some typical articles to promote Lua plugin programming officially, such as:  

- Introduction to Neovim Lua Plugin Programming
- Neovim Lua Plugin Programming: Getting Started
- Neovim Lua API Reference  

And a Lua plugin index page (Maybe it can start with a really simple catalog page, and grow to be like PyPI like site)

Forgive me if I missed something, so far the information of Lua plugin programing are scattered among various issue threads.

Is it the right time point to start a official Lua plugin programming promotion? I think there will be quite a amount of people who are interested in learn about this (or switch to it after they get enough information) .

**Comment by phanimahesh** [comment]
One of the long term goals is to create a good lua api, and a viml -> lua transpiler targeting this api, so that what ends up executing is lua, anyway. Neovim is a fork of vim, and we want to make use of the vim plugin ecosystem. I don't think it would be a good idea to fragment the ecosystem by promoting lua plugins, right now.

When vimscript doesn't suffice or is too slow/clunky to work with, plugins can be written in any language, as a remote plugin. lua is supported via nvim-lua-client, if my memory serves me right.

**Comment by tbodt** [comment]
So there's going to be a vimscript to lua converter, and then lua can be just-in-time-compiled? Sounds cool!
