### ISSUE TITLE
Yanking inside cmdwin doesn't respect 'clipboard'

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/neovim#5544]
- `nvim --version`:

```
NVIM v0.2.0-1-g242c3d5
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/config -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/pkgbuild-0/neovim-git/src/neovim-git/build/include
Compiled by root@bianca

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0 Included patches: 1-46) behaves differently? Yes
- Operating system/version: Linux (Arch – rolling release)
- Terminal name/version: termite
- `$TERM`: xterm-termite
### Actual behaviour

Yanking with `clipboard=unnamedplus` inside a command-line window doesn't yank to the `+` register
### Expected behaviour

Yanking with `clipboard=unnamedplus` inside a command-line window yanks to the `+` register
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set clipboard=unnamedplus
q:
yy
:registers
```

Inside the command-line window returns in:

```
:echo v:register
+
```

**Comment by justinmk** [comment]
Does reverting https://github.com/neovim/neovim/commit/4af6ec746c821078859469adc46cf7bef5c629fa fix this?

**Comment by mhinz** [comment]
> Does reverting 4af6ec7 fix this? (just comment out this line and the end_batch_changes() below it)

Confirmed!

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/commit/3a59b04c1997a697c3428bcfcf4fa9e875e718dd / https://github.com/neovim/neovim/pull/5409 for related discussion about the states involved. 

A maybe inelegant way to fix this would be to call `end_batch_changes()` before ending cmdwin state.
