### ISSUE TITLE
Track vim8 patches

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#5551]
There were already the first ported patches from vim8, but we do not track them. `version.c` is only for vim7 patches. Shouldn't that be added as long as the number of patches is low? I'd prepare a PR, but I'm unsure how it should be done, should we just add another array to `version.c`?

**Comment by justinmk** [comment]
My plan was to just finish up v7 and use `git log --grep=vim-patch:8\.` to backfill version.c when we're ready. Should work just fine.

**Comment by KillTheMule** [comment]
Oh, if it is that easy... well then, less work to do :)
