### ISSUE TITLE
Segmentation fault: vs_current_line()

### ISSUE THREAD

**Issue by davidpdrsn** [neovim/neovim#5553]
- `nvim --version`: 0.1.5
- Vim (version: ) behaves differently? Don't have Vim installed. All in on NeoVim ❤️ 
- Operating system/version: macOS 10.12.1
- Terminal name/version: Terminal 2.7.1
- `$TERM`: screen-256color

### Actual behaviour

NeoVim segfaults on me several times a day.

Sometimes I get no message at all. Sometimes I get this message:

![screen shot 2016-10-31 at 15 47 12](https://cloud.githubusercontent.com/assets/718941/19859236/d84aa8a0-9f84-11e6-9c35-d6d6523ae5bd.png)

Could this be because of some plugin? My `init.vim` can be found [here](https://github.com/davidpdrsn/dotfiles/blob/master/nvim/init.vim).

Grepping for `vs_current_line` in `~/.config/nvim` gives me nothing.

### Expected behaviour

No segmentation fault.

### Steps to reproduce using `nvim -u NORC`

Haven't been able to find a pattern in the segfaults.

**Comment by justinmk** [comment]
@davidpdrsn I see `vs_with_current_line` in the screenshot. The strings `vs_with_current_line` nor `vs_current_line` exist in the neovim source, it might be text that wasn't redrawn? (You would be most able to answer that question, see if that string was on-screen or in some buffer you have open.) 

Next time the crash happens it should be easy to get a backtrace on macOS, see [here](https://github.com/neovim/neovim/wiki/Development-tips#backtrace-macos--osx).

**Comment by justinmk** [comment]
No reply. The information provided points towards a zsh segfault, not nvim.
