### ISSUE TITLE
Segfault when going to very large line number using :LineNumber

### ISSUE THREAD

**Issue by akashin** [neovim/neovim#5555]
- `nvim --version`:
```
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/config -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/src -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/build/include
Compiled by acid@macbook

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
```
- Vim (version: 7.4) behaves differently?  
In regular vim everything works as expected
- Operating system/version:  
macOS, Version 10.12.1
- Terminal name/version:   
iTerm2, Build 3.0.11
- `$TERM`:   
xterm-256color

### Actual behaviour
```
:99999999999999999999999999Assertion failed: (errno != ERANGE), function getdigits, file /tmp/neovim-20160924-3000-16aeltp/neovim-0.1.5/src/nvim/charset.c, line 1743.
[1]    21949 abort      nvim /tmp/newfile
```
### Expected behaviour

Go to the last line of file
### Steps to reproduce using `nvim -u NORC`

Open any file with vim
```
nvim -u NORC /tmp/newfile
```
Try to go to very far line:
```
:999999999999999999999999999
```

**Comment by mhinz** [comment]
Can't reproduce with 0.1.6 on Sierra:

```
$ nvim -u NORC /tmp/newfile
1000i9<esc>
y0
:<c-r>"<cr>
```

**Comment by oni-link** [comment]
In debug mode we have an assert that catches too big numbers (`> INTMAX_MAX`) in `getdigits_safe()`. That is what @akashin triggers.

**Comment by jamessan** [comment]
Except this was a `RelWithDebInfo` build.  That shouldn't have the debug asserts, should it?

**Comment by jamessan** [comment]
Oh, we do enable assertions for that.

```
108 # Enable assertions for RelWithDebInfo.
109 if(CMAKE_C_FLAGS_RELWITHDEBINFO MATCHES DNDEBUG)
110   string(REPLACE "-DNDEBUG" "" CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO}")
111 endif()
```

**Comment by mhinz** [comment]
Oh. I blame the [Homebrew formula](https://github.com/neovim/homebrew-neovim/blob/master/Formula/neovim.rb#L131-L136).

You have to `brew install neovim --with-release` to get the `Release`. IMHO, it should be opt-out instead. Something like `brew install neovim --with-debug-info` to get `RelWithDebInfo`.

**Comment by justinmk** [comment]
We decided awhile ago that we want assertions and symbols by default, even for end-users. RelWithDebInfo supposedly doesn't have a performance cost (except size).

>  In debug mode we have an assert that catches too big numbers (> INTMAX_MAX) in getdigits_safe() (older versions catch this in getdigits())

Where is the assert in `getdigits_safe()` ?

**Comment by jamessan** [comment]
It's not in getdigits_safe.  It's in getdigits, which is what getdigits_long is calling for the `:[range]` uses.

There are a lot of places in Vim which expect numbers to get clamped to the range of the data type, which we're now violating with this assert.  I'm not that this specific assert is worthwhile.

**Comment by jamessan** [comment]
I noticed that we have some other functions which have a `_strict` variant.  If we think there are valid places to use the getdigits family of functions with the asserts, then how about exposing those through `getdigits*_strict` instead?

**Comment by justinmk** [comment]
@jamessan Sounds good to me. I wasn't real happy with the `_safe` idiom.

**Comment by ngortheone** [comment]
This still happens on latest master debug build

`build/bin/nvim -u NORC +9999999999999999999999999999999`

Gives me
```
Assertion failed: (ret == OK), function getdigits, file ../src/nvim/charset.c, line 1630.
         Abort trap: 6
```

But **not** happens on release build.

@justinmk Not sure if this is a bug and whether something has to be fixed.

**Comment by justinmk** [comment]
@ngortheone Release build  compiles-out `assert()` statements. That's why we like `RelWithDebInfo` build type.

**Comment by ngortheone** [comment]
> build compiles-out assert() statements. That's why we like RelWithDebInfo build type.

That makes sense. What doesn't is that Release version behaves normally. It just jumps to the last line in the file (I tried multiple very big files ~ 20 Mb of text) 
I expected Release version to crash or show some kind of buggy/unexpected behaviour

**Comment by justinmk** [comment]
That's not really unexpected. We added the assert as a strict check. That's why @jamessan  [suggested](https://github.com/neovim/neovim/issues/5555#issuecomment-257732193) changing the approach so that by default this family of functions is _not_ strict, and instead introduce `foo_strict` variants.
