### ISSUE TITLE
Sh/Bash syntax highlighting can't handle command substitutions

### ISSUE THREAD

**Issue by gwerbin** [neovim/neovim#5559]
### Actual behaviour

Command substitutions using "$()" are highlighted as if they were syntax errors: [example](http://imgur.com/a/nyi1H). Text inside the command substitutions is correctly highlighted the same as text between backquotes ("`").

### Expected behaviour

Nested command substitutions either do not have any special syntax highlighting, or have their own syntax highlighting.

I'm not sure exactly why this comes up as an error since AFAIK both forms of command substitution ("$()" and "`") are in the POSIX standard. So even though the filetype is really "sh" and not "bash," this shouldn't be flagged as an error unless you're on some ancient Solaris machine, in which case you're probably not using Neovim anyway. It looks more like a "never got around to it" oversight than a "bug" as such.

This behavior is identical in Vim, but as I have high hopes for the Neovim project I'm reporting it here 😉

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC anything.sh
# "$( anything )" --> red highlighting
```

#### `nvim --version`
```
NVIM v0.1.6-254-gfbd6b10
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DDI
Compiled by greg@cpe-74-71-171-115.nyc.res.rr.com

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-fbd6b10/share/nvim"
```
#### Vim () behaves differently?
```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses
```

No

#### Operating system/version:

OS X "El Capitan" 10.11.6

#### Terminal name/version:

```
zsh 5.2 (x86_64-apple-darwin15.0.0)
```

#### `$TERM`:

```
xterm-256color
```

**Comment by mhinz** [comment]
`nvim -u NORC --cmd 'let is_bash = 1' anything.sh` should work.

See `:h ft-bash-syntax` for the explanation.

**Comment by jamessan** [comment]
As is described in `:help ft-sh-syntax`, the sh syntax file covers syntax highlighting for POSIX sh, ksh, bash, and bourne shells.  If there's no information indicating otherwise, the syntax highlighting will default to bourne, _specifically_ to nudge you to provide the relevant hints about what type of shell you're targeting.

There are various ways you can do that.  If you're writing a Bash script, then you should really have `bash` in the `#!` line.  If it's not an executable script (and therefore has no `#!`) you can help by naming it `.bash`.

Alternatively, let one of the `g:is_...` variables in your init.vim to provide the hint about what syntax you're generally targeting.

**Comment by mhinz** [comment]
Relevant code: https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/syntax/sh.vim#L19-L42

> This behavior is identical in Vim, but as I have high hopes for the Neovim project I'm reporting it here

We're glad to hear that, but, except for some rare cases, we use the same runtime files as Vim does. If there were a real issue, it would have to be reported to the @vim_dev mailing list.

**Comment by justinmk** [comment]
> as I have high hopes for the Neovim project I'm reporting it here

We're willing to make changes in cases where Vim out of touch, if there's a good reason for it and Vim refuses to adapt. But in general, Neovim doesn't exist to debug or maintain Vim syntax files.

**Comment by gwerbin** [comment]
@jamessan I should have mentioned that the script in question had `#! /usr/bin/env bash` in the shebang, but a `.sh` file extension. So something is still going wrong between there and https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/syntax/sh.vim#L291-L304 .

@justinmk understood 100%. If I file a report and this gets fixed in Vim, will it get merged downstream? (Somewhat off-topic, but how is the Neovim in general handling minor upstream changes? I'm not talking about reimplementing major Vim 8 features, just fixes like the one we're discussing, or changes to the documentation)

**Comment by jamessan** [comment]
I just created a test file using that `#!` and it was detected/highlighted properly.

```sh
$ printf '#! /usr/bin/env bash\nFOO=$(ls)\n' > foo.sh
$ nvim -u NORC foo.sh
:echo get(b:, 'is_bash', 0)
1
```

We regularly work on [merging] upstream changes (both patches and runtime updates) from Vim, so it's just a matter of time and effort to get such changes.

[merging]: http://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim

**Comment by mhinz** [comment]
What happened in jamessan's case:

- If you attempt to open a file with `.sh` extension, [this autocmd](https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/filetype.vim#L1861) gets triggered.
- It calls `SetFileTypeSH()` with the first line from the file, hoping to find a shebang.
- If there's "bash" [anywhere in the first line](https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/filetype.vim#L1896-L1903), `let b:is_bash = 1` gets set automatically.
- The last line in `SetFileTypeSH()` calls `SetFileTypeShell("sh")` which again executes [setfiletype sh](https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/filetype.vim#L1936) on the last line.
- This leads to `runtime/syntax/sh.vim` getting sourced, where `b:is_bash` most likely gets [set again](https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/syntax/sh.vim#L24). (In case someone manually runs `set ft=sh`.)
- Eventually the `shCommandSub` syntax group [gets defined](https://github.com/neovim/neovim/blob/01f1028496bd1a402ad1b11c311291ec96335b70/runtime/syntax/sh.vim#L298).

If you see something different, it would be worth investigating.
