### ISSUE TITLE
nvim ought to restore `!O_NONBLOCK` when it backgrounds itself

### ISSUE THREAD

**Issue by leonerd** [neovim/neovim#5560]
- `nvim --version`: NVIM 0.1.5  (debian/testing)
- Vim (version: ) behaves differently?
- Operating system/version: Linux
- Terminal name/version: pangoterm
- `$TERM`: xterm

When it backgrounds itself, a regular `vim` will not leave `O_NONBLOCK` set on stdin:

    $ perl -MIO::Handle -E 'say "O_NONBLOCK" if !STDIN->blocking'

    $ vim
    ^Z
    [1]+  Stopped                 vim

    $ perl -MIO::Handle -E 'say "O_NONBLOCK" if !STDIN->blocking'

Whereas, `nvim` does:

    $ perl -MIO::Handle -E 'say "O_NONBLOCK" if !STDIN->blocking'

    $ nvim
    ^Z
    [1]+  Stopped                 nvim

    $ perl -MIO::Handle -E 'say "O_NONBLOCK" if !STDIN->blocking'
    O_NONBLOCK

This doesn't seem to affect readline but does affect some programs; e.g. `git add -p`. If I try to

    $ git add -p

at this point, the `git` command receives an `-1 (EAGAIN)` result out of `read(0, ...)` and promptly exits.

**Comment by leonerd** [comment]
Dupe #5459

**Comment by jamessan** [comment]
Same as #5459, which has been fixed (and is cherry-picked into the Debian package, when that makes it to testing).
