### ISSUE TITLE
clipboard: handle $DISPLAY change

### ISSUE THREAD

**Issue by awoodx** [neovim/neovim#5563]
I've been running nvim on a remote machine. I use ssh -X to login into the machine and use the dtach program to keep nvim running if I log off (screen / tmux will work too).

The $DISPLAY environment variable is set by ssh, but can change the next time I login. This causes nvim's copy / paste to break. I think because the xclip program was started with the old $DISPLAY. 

Is it possible to tell nvim to reset the $DISPLAY without restarting nvim?

Thanks!

**Comment by justinmk** [comment]
Didi you try `:let $DISPLAY=...`? 

If that doesn't work take a look at `runtime/autoload/provider/clipboard.vim`, maybe `xsel` or `xclip` need to be restarted.

**Comment by awoodx** [comment]
That worked! Thanks justin.
