### ISSUE TITLE
Highlight search (:hlsearch) does not work under GNU screen

### ISSUE THREAD

**Issue by martsbradley** [neovim/neovim#5564]
martin@:app $ nvim --version
NVIM v0.2.0-32-g18bc5aa
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/martin/Software/C/neovim/neovim/build/config -I/home/martin/Software/C/neovim/neovim/src -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/home/martin/Software/C/neovim/neovim/.deps/usr/include -I/usr/include -I/home/martin/Software/C/neovim/neovim/build/src/nvim/auto -I/home/martin/Software/C/neovim/neovim/build/include
Compiled by martin@laptop

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/martin/Software/C/neovim/install/share/nvim"

 ++++++++++++++++++++++++++++++++++++++++++++
- Operating system/version:
Debian Stable
martin@:app $ cat /etc/debian_version 
8.6
martin@:app $ uname -a
Linux laptop 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
++++++++++++++++++++++++++++++++++++++++++++
- Terminal name/version: 

martin@:app $ echo $TERM
screen
++++++++++++++++++++++++++++++++++++++++++++

### Actual behaviour
Under GNU screen the found keywords are not highlighted.

The normal vim does not  have the same issue.
martin@:app $ /usr/bin/vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07)

Debian 
### Expected behaviour
Under GNU screen the found keywords are highlighted

### Steps to reproduce using `nvim -u NORC`

```
martin@:app $ screen --version
Screen version 4.02.01 (GNU) 28-Apr-14

1. Start gnu screen
2. nvim -u NORC
3: :set hlsearch
4. Search for some text.

Changing the environment variable TERM to xterm
export TERM=xterm

Allows nvim to highlight the words.
The legacy vim does not have that issue.


```

**Comment by justinmk** [comment]
Try `TERM=screen-256color`.

> legacy vim does not have that issue.

For various reasons Nvim cares more about what terminfo says than Vim does.
