### ISSUE TITLE
Startup Error Message after nvim update

### ISSUE THREAD

**Issue by hwine** [neovim/neovim#5566]
- `nvim --version` (from homebrew):
```NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/build/config -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/src -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161106-93889-tyuk92/neovim-0.1.6/build/include
Compiled by hwine@hwin-28520

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"
```
- Vim (version: ) behaves differently?
- Operating system/version: Mac OSX Sierra (10.12.1)
- Terminal name/version: `xterm`

### Actual behaviour
Starting nvim after upgrade to nvim 0.1.6 (from 0.1.4) gave:
```
Error detected while processing function remote#define#AutocmdBootstrap[1]
```
And would clear after pressing enter, but re-appear on every start of neovim.

### Expected behaviour
Either
* no error, or
* recommendation in error message to run `:UpdateRemotePlugin` which fixes it.

Google search for the error message pointed me at #2258, (from 2015) which mentioned possibly addressing the error message side of it ([comment](https://github.com/neovim/neovim/issues/2258#issuecomment-90288322)). Seems like that part might have gotten missed.

Note: if `:UpdateRemotePlugin` should be run after every upgrade, let me know and I'll work with the homebrew end of it.

**Comment by justinmk** [comment]
So `:UpdateRemotePlugins` solved the issue? We do try to detect problems in `:CheckHealth`, which should always be run after upgrading.

Some good ideas for improving, mitigating, or eliminating `:UpdateRemotePlugins` are discussed in https://github.com/neovim/neovim/issues/5532. I believe that covers this.

**Comment by hwine** [comment]
afaict, `:CheckHealth` is not run by the brew neovim install/upgrade process. I'll file a bug on that with homebrew.
