### ISSUE TITLE
Can't download binary build for Windows

### ISSUE THREAD

**Issue by r44083** [neovim/neovim#5568]
I can not download nvim binary package from this page (see windows chapter):
[https://github.com/neovim/neovim/wiki/Installing-Neovim](https://github.com/neovim/neovim/wiki/Installing-Neovim)

**Comment by KillTheMule** [comment]
Works for me. What exactly is your problem?

**Comment by r44083** [comment]
Do you test it on "Neovim-Qt build" downloading only? I mean that links with names "32bit build" and "64bit build" don't work.

**Comment by justinmk** [comment]
both links work from here

**Comment by r44083** [comment]
Very strange.. This links still unavailbale from me.

**Comment by r44083** [comment]
I check thees links again and now all links working. Thx
