### ISSUE TITLE
`:CheckHealth` doesn't want to run if plasticboy's markdown syntax files

### ISSUE THREAD

**Issue by rafaeln** [neovim/neovim#5569]
- `nvim --version`: 0.2.0-dev
- Operating system/version: Ubuntu 14.04
- Terminal name/version: urxvt v9.21
- `$TERM`: tmux-it-256color

### Actual behaviour

When I run `:CheckHealth` while using [plasticboy's vim-markdown syntax files](https://github.com/plasticboy/vim-markdown), I get the following error message. If I remove that plugin and use the builtin markdown syntax, all goes fine.

~~~text
Error detected while processing function health#check[10]..<SNR>87_enhance_syntax:
line   24:
E28: No such highlight group name: markdownCodeBlock
~~~

**Comment by justinmk** [comment]
@rafaeln Thanks for reporting
