### ISSUE TITLE
job API: get detailed jobinfo and a list of jobs.

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#557]
Something that could be improved for the job control module is to use Job pointers instead of ids. I used ids in the first place because I didn't knew how to associate arbitrary pointers with vimscript objects(not sure if it's possible). Perhaps @ZyX-I has some advice on this matter? If we used Job pointers we could also get rid of the job table and use a linked list to keep track of running jobs.

We also need APIs for getting detailed job info such as pid(probably a `jobinfo` function that returns a dictionary) and a list of jobs.

**Comment by bfredl** [comment]
assuming `nvim_list_chans()` and `nvim_get_chan_info()` covers this.
