### ISSUE TITLE
alt key bindings no longer work

### ISSUE THREAD

**Issue by glensc** [neovim/neovim#5576]
```
" nice bindings for navigating between files
map <Esc>n :bnext<CR>
map <Esc>p :bprevious<CR>
map <Esc>l :ls<CR>
map <Esc>1 :buffer 1<CR>
map <Esc>2 :buffer 2<CR>
```

- `nvim --version`: 0.1.5, 0.1.6
- Vim (version: all versions) behaves differently: works
- Operating system/version: Linux, OSX
- Terminal name/version: gnome-terminal, mate-terminal, screen, iterm2
- `$TERM`: xterm, screen

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:map <Esc>l :ls<CR>
```

Now press `alt`+`l` -> nothing happens in nvim

**Comment by justinmk** [comment]
ESC is ESC. Try <A-foo> instead.

**Comment by justinmk** [comment]
`<A-....>`

**Comment by glensc** [comment]
why did you close this? it's regression vim->neovim! and alt key sends esc+foo sequence.

is this documented in neovim incompatibilities list?

**Comment by justinmk** [comment]
Just change the mappings to: 

```
map <A-n> :bnext<CR>
map <A-p> :bprevious<CR>
map <A-l> :ls<CR>
map <A-1> :buffer 1<CR>
map <A-2> :buffer 2<CR>
```

> it's regression

It's not a regression, `<Esc>` means "escape". `<A-...>` means "alt".

> is this documented in neovim incompatibilities list?

Not even gVim works with the mappings you have.  Specifying `<Esc>a` as a mapping only works by accident, because of an implementation detail. `<M-a>` (or `<A-a>`) is the correct way to specify a meta/alt mapping.

**Comment by glensc** [comment]
thanks for the detailed reply!

**Comment by glensc** [comment]
@justinmk care to give example how to define the bindings compatible with vim/nvim? perhaps some  function?

**Comment by justinmk** [comment]
```
if has('nvim')
  ...
else
  ...
endif
```

**Comment by glensc** [comment]
is there way to reuse adding definitions? duplicating large blocks between `if` and `else` is just bad practice. what i have in mind, is either add function that adds definition either for vim or nvim, and defining bindings go via that function.

**Comment by glensc** [comment]
least i was able to come up with.
this could probably improved by vim/nvim best practices (which i'm not aware of):

```vim
" vim/nvim compatible alt key binding
" https://github.com/neovim/neovim/issues/5576
if has('nvim')
    " map <A-n> :bnext<CR>
    function! s:alt_key(key)
        return "<A-". a:key . ">"
    endfun
else
    " map <Esc>n :bnext<CR>
    function! s:alt_key(key)
        return "<Esc>". a:key
    endfun
endif

function! s:map_alt(key, action)
    exec "map " . s:alt_key(a:key). " " a:action
endfun

function! s:imap_alt(key, action)
    exec "imap " . s:alt_key(a:key). " " a:action
endfun
```

```diff
-map <Esc>n :bnext<CR>
-map <Esc>p :bprevious<CR>
-map <Esc>l :ls<CR>
-map <Esc>1 :buffer 1<CR>
-map <Esc>2 :buffer 2<CR>
-map <Esc>3 :buffer 3<CR>
-map <Esc>4 :buffer 4<CR>
-map <Esc>5 :buffer 5<CR>
-map <Esc>6 :buffer 6<CR>
-map <Esc>7 :buffer 7<CR>
-map <Esc>8 :buffer 8<CR>
-map <Esc>9 :buffer 9<CR>
-map <Esc>0 :buffer 10<CR>
-map <Esc>u :bunload<CR>
-map <Esc>e :e <C-D>
+call s:map_alt("n", ":bnext<CR>")
+call s:map_alt("p", ":bprevious<CR>")
+call s:map_alt("l", ":ls<CR>")
+call s:map_alt("1", ":buffer 1<CR>")
+call s:map_alt("2", ":buffer 2<CR>")
+call s:map_alt("3", ":buffer 3<CR>")
+call s:map_alt("4", ":buffer 4<CR>")
+call s:map_alt("5", ":buffer 5<CR>")
+call s:map_alt("6", ":buffer 6<CR>")
+call s:map_alt("7", ":buffer 7<CR>")
+call s:map_alt("8", ":buffer 8<CR>")
+call s:map_alt("9", ":buffer 9<CR>")
+call s:map_alt("0", ":buffer 10<CR>")
+call s:map_alt("u", ":bunload<CR>")
+call s:map_alt("e", ":e <C-D>")

-       map <Esc>\ :call CommentToggle()<CR>j
-       imap <Esc>\ <ESC>:call CommentToggle()<CR>j
-       map <Esc>' :call CommentToggle()<CR>j
-       imap <Esc>' <ESC>:call CommentToggle()<CR>j
+       call s:map_alt("\\", ":call CommentToggle()<CR>j")
+       call s:imap_alt("\\", "<ESC>:call CommentToggle()<CR>j")
+       call s:map_alt("'", ":call CommentToggle()<CR>j")
+       call s:imap_alt("'", "<ESC>:call CommentToggle()<CR>j")
```

**Comment by MartyMcFlyInTheSky** [comment]
How is the alt key mapping different than the ESC keymapping? I was lead from [this stackoverflow post](https://vi.stackexchange.com/questions/2350/how-to-map-alt-key) to believe mapping ESC was the proper way. How does neovim have a way to distinguish alt sequences over the tty? I thought only ASCII keycodes are recognised?
