### ISSUE TITLE
:CheckHealth doesn't recognised 

### ISSUE THREAD

**Issue by alistaircolling** [neovim/neovim#5577]
- `nvim --version`: NVIM v0.2.0-52-g0213e99
- Vim (version: ) behaves differently? n/a
- Operating system/version: 10.10.5 Mac OSX
- Terminal name/version: iterm 
- `$TERM`: zsh command not found xterm-256color

### Actual behaviour
Run ':CheckHealth'
E492: Not an editor command: CheckHealth

### Expected behaviour
Details why my python config isn't working

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

It works when I run this version!

**Comment by justinmk** [comment]
VIMRUNTIME is being set somewhere in your shell or init.vim

**Comment by stephaneeybert** [comment]
I also have this message E492: Not an editor command: CheckHealth when typing in the :CheckHealth command under neovim 0.8.3
