### ISSUE TITLE
inccommand does not work with :smagic///

### ISSUE THREAD

**Issue by SageEx** [neovim/neovim#5578]
- `nvim --version: v0.2.0-52-g0213e99 (latest master)`
- Operating system/version: `ArchLinux`
- Terminal name/version: `st`, `xterm`
- `$TERM`: `xterm-256color`

### Actual behaviour
``:%smagic`` does not work with ``inccommand``
### Expected behaviour
``inccommand`` should work with all ``%s*`` variants
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
set inccommand=split
```

**Comment by justinmk** [comment]
> inccommand should work with all %s* variants

What other variants? Supporting `:argdo`, `:cdo`, `:bufdo` will be a bigger task, though it is "planned".

**Comment by SageEx** [comment]
Thanks a lot.
