### ISSUE TITLE
inccommand preview doesn't disappear when browsing command history

### ISSUE THREAD

**Issue by emptyflask** [neovim/neovim#5585]
- `nvim --version`: NVIM v0.2.0-52-g0213e99

### Actual behaviour
When browsing through previous commands, if a `s/find/replace` command is shown, it shows the preview on the open file. When moving on to another command in the history, the preview is not removed.

### Expected behaviour
The find/replace preview should only be shown when a find/replace command is active.

**Comment by justinmk** [comment]
I assume you are talking about ctrl-n/ctrl-p. I noticed this as well, didn't personally care. There is a small advantage: it reduces "bouncing" of the screen as you go through the history.
