### ISSUE TITLE
inccommand in line substitution highlights all matches in the file

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#5589]
- `nvim --version`:

```
NVIM v0.2.0-52-g0213e99
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/config -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/src -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/src/nvim/auto -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/include
Compiled by yfful@troy

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Linux troy 4.8.6-2-ck #1 SMP PREEMPT Fri Nov 4 22:25:35 EDT 2016 x86_64 GNU/Linux
- Terminal name/version: termite v12
- `$TERM`: xterm-termite

### Actual behaviour

Every matches in the file are highlighted eventhough line substitution `:s/foo` is used.

### Expected behaviour

It should highlight the matching parts only in the current line.

### Steps to reproduce using `nvim -u NORC`

```sh
nvim -u NORC +'set icm=nosplit'
```

![output](https://cloud.githubusercontent.com/assets/795879/20214055/b23d3524-a803-11e6-929d-a27a8018ef11.gif)

**Comment by justinmk** [comment]
I can't reproduce this. What are the steps to reproduce with `nvim -u NORC` ?

**Comment by CallumHoward** [comment]
I can reproduce this behaviour with both `nvim -u NORC +'set icm=nosplit'` and `nvim -u NORC -i NONE` and then `:set icm=nosplit`. 
steps were, write some gibberish:
```
foo
fool
foolish
```
with the cursor on the last line do `:s/foo`, all occurrences of foo are highlighted, but only the last line should be as `:%s` is not used.

**Comment by scampi** [comment]
@CallumHoward what you explained is exactly the problem at hand. I updated the description of the issue accordingly; when I opened this issue, I didn't realise what I was experiencing was because the match was on the current line (all matches in the file highlighted confused me).
