### ISSUE TITLE
incommand still highlights matches even if the pattern is empty

### ISSUE THREAD

**Issue by scampi** [neovim/neovim#5591]
- `nvim --version`:

```
NVIM v0.2.0-52-g0213e99
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/config -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/src -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/.deps/usr/include -I/usr/include -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/src/nvim/auto -I/tmp/makepkg/yfful-neovim/src/yfful-neovim/build/include
Compiled by yfful@troy

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Linux troy 4.8.6-2-ck #1 SMP PREEMPT Fri Nov 4 22:25:35 EDT 2016 x86_64 GNU/Linux
- Terminal name/version: XTerm(327)
- `$TERM`: xterm-256color

### Actual behaviour

I start writing a pattern in the `substitute` command and then I want to remove it. As I delete the last character of the pattern, the matches of that last character are still being highlighted.

⚠️  Also, check the line **67** in the GIF, the two letters `dd` are highlighted, although there is only one `d` in the pattern.

### Expected behaviour

Since the pattern is empty, nothing should be highlighted anymore.

### Steps to reproduce using `nvim -u NORC`

```sh
nvim -u NORC +'set icm=nosplit'
```

![output](https://cloud.githubusercontent.com/assets/795879/20214831/74726098-a808-11e6-8d5a-a1d4902e28e1.gif)

**Comment by justinmk** [comment]
This is a feature.

**Comment by drewbailey** [comment]
Is there a way to disable this?

**Comment by justinmk** [comment]
`:set nohlsearch`
