### ISSUE TITLE
Lambda support

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#5601]
neovim should support the lambda feature after partial feature.
https://github.com/neovim/neovim/pull/5529

The lambda pathces list are:

1989: map()/filter() funcref
2002: map()/filter() crash
2044: lambda
2076: lambda fix
2090: substitute() lambda support
2096: lambda
2104: userfunc
2119: closure
2120: closure
2121: has('lambda')
2132: test_partial.vim
2134: function()
2136: clojure
2137: funcref()
2139: delfunction crash
2142: funcref()
2143: closure
2197: userfunc
2198: test_partial
2233: funcref() fix
2235: evalfunc

**Comment by adriaanzon** [comment]
This can be closed now that #5771 has been merged, right?
