### ISSUE TITLE
set inccommand=nosplit/split slow on huge files

### ISSUE THREAD

**Issue by teto** [neovim/neovim#5602]
- `nvim --version`:
```
 nvim --version                                                                                 
NVIM v0.2.0-52-g0213e99
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/teto/neovim/build/config -I/home/teto/neovim/src -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/usr/include -I/home/teto/neovim/build/src/nvim/auto -I/home/teto/neovim/build/include
Compilé par teto@sirius
```
- Terminal name/version: termite

### Actual behaviour
I type `:%s/` and nvim displays ':%' but then nvim blocks and I haveto wait ~500ms before seeing `:%s`. Same for the subsequent letters  `:%s/ blocks` etc...
Same behavior for both split/nosplit. I've got a pretty good machine there.

### Expected behaviour
Should not block ? like substitute only the visible screen or add a warning in help.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c "set inccomand=nosplit" hugefile.txt
:%s/
```

**Comment by justinmk** [comment]
For reference: "huge file" here means "180MB" and `:s%/<CR>` with `'inccommand'` disabled takes 500ms. So it makes sense that `'inccommand'` would cause a corresponding slowdown on each incremental keypress.

This can be mitigated by (1) checking `char_avail()`, and (2) checking a timeout in the `do_sub()` hotpath.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/5607 implements the following for dealing with slow/big files:

- If `:substitute` preview takes too long, `'inccommand'` is deactivated for the current command-line.
    - The time limit is controlled by `'redrawtime'`, which defaults to 2 seconds.
- If `:substitute` is a bit slow and you type many characters, the preview is skipped for the in-between states.
- CTRL-C cancels a slow `:substitute` preview.
