### ISSUE TITLE
Improve command mode experience (as-you-type ido style autocomplete, hide command line)

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#5605]
Okay, I've spend half an hour written this issue, but for some reason it's gone. I don't want to retype everything, so I'll try to be brief.

I would like to have as-you-type autocomplete in command line similar to the the way its done in emacs ido plugin.
Say i want to change the buffer. *x* is used to indicate highlighting.
I type
`:*b*{ b | bd | bufdo }` - this what command line should look like
I type space and vim should be smart enough to know that the thing I typed is a command and if user typed space after that it means he accepted completion. If I would pressed `enter` here it should execute the first match, which wouldn't do anything in this case.
So i type `space`.
`:b { foo.txt | bar.txt | .vimrc }`
Vim already can determine completions options if I would press tab and even show them in wildmenu, so It shouldn't be hard to show them this way as I type. If I would want foo.txt at this point all I would have to do is press enter and If I'd want something else I could type partial match and wait for to be the first option or I could press `tab` or `S-tab` to cycle between options similar to how wildmenu works now. If completions take too long, say in `find` command in a very large codebase vim could show something like
`f{ file | files | filetype | finally }` etc
`f {...}`
Completions of course should work asynchrounsly, so that user wouldn't have to wait for them. Logic is pretty simple. At each keypress create Future (Promise name it as you like) that would have list of completion options when it's done. If user pressed another button and the future isn't ready yet, cancel the future and create another.

Another way I'd like command mode to be improved is by giving user ability to hide command line when it's not used. Right now it always takes one line at the bottom of the screen, although it isn't used most of the time.

There are many plugins that are trying to workaround this vim/neovim limitation (SkyBison, Ctrl-p, Commant-t, Unite, Denite) in some way or another, so It clearly is important to many people.
I think this deserves to be in vanilla neovim.

Command line experience and lacking of this features bugs me so much I'm ready to implement them myself. My C knowledge is rusty and incomplete, but I'm willing to learn. I spent about 15 minutes trying to understand where is the code that handles command mode and  completions but without any result. So I would appreciate help in navigating the code and understanding it's structure.

**Comment by Delapouite** [comment]
https://github.com/neovim/neovim/issues/5604
