### ISSUE TITLE
special characters are not handled in normal mode

### ISSUE THREAD

**Issue by rafaelxyz** [neovim/neovim#5610]
- `nvim --version`:
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/build/config -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/src -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-D9ttIT/neovim-0.1.5ubuntu1+git201611140054+2891+22~ubuntu14.04.1/build/include
Compiled by root@lcy01-29

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently? all
- Operating system/version: ubuntu 14.04
- Terminal name/version: xterm
- `$TERM`:screen-256color

### Actual behaviour
inputting r" in normal mode does not change the character under cursor to "
### Expected behaviour
character should have been changed
### Steps to reproduce using `nvim -u NORC`

open any file and try to do replace or move operations with special characters like / = " and it will fail.

```
nvim -u NORC
```

**Comment by justinmk** [comment]
> open any file and try to do replace or move operations with special characters like / = " and it will fail.

Works just fine for me, as well as the ~12 different environments running the test suite. There must be some other factor needed to reproduce this issue.

**Comment by rafaelxyz** [comment]
It was a mapping issue in my configuration. Thanks for the response.
