### ISSUE TITLE
Background process with high CPU usage

### ISSUE THREAD

**Issue by benwaffle** [neovim/neovim#5612]
- `nvim --version`:
```
NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.6/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Linux 4.8.6, Arch

### Actual behaviour
The process is running in the background, at 100% cpu usage, without a terminal. I believe I closed the terminal while a paste was in progress (ctrl-shift-v in insert mode, not `"+p`). The orphaned process was reparented to PID1

### Expected behaviour
nvim quits when you close the terminal

### Steps to reproduce using `nvim -u NORC`
Copy a large file, paste it in (ctrl-shift-v), and close your terminal while it's pasting. Unfortunately, I can't reproduce.

I ran `perf record` before I killed the process: [perf.zip](https://github.com/neovim/neovim/files/593030/perf.zip). You can unzip the file and run `perf report` to see the data. tl;dr `input_enqueue` and `rbuffer_get` take up all of the time

**Comment by justinmk** [comment]
Could be helped by  https://github.com/neovim/neovim/pull/4448.

**Comment by lewis6991** [comment]
Not sure this is a problem anymore.

Reopen if I'm wrong.

**Comment by justinmk** [comment]
Besides https://github.com/neovim/neovim/pull/4448 , https://github.com/neovim/neovim/pull/30056 may be related.
