### ISSUE TITLE
drop command not working correctly with :tab modifier

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#5616]
- `nvim --version`: v0.2.0-73-g10c72cd
- Vim (version: ) behaves differently? vim doesn't have drop command
- Operating system/version: MacOS
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Actual behaviour

If tab have split windows, `:tab drop` command always open a new tab

### Expected behaviour

`:tab drop` command should open exists window when possible.

### Steps to reproduce using `nvim -u NORC` 

```
nvim -u NORC
nvim -p foo bar
# split window in other tab
gt
:vs
gt
:tab drop bar
```
If works fine without `:vs` command.

**Comment by oni-link** [comment]
vim needs to be compiled with a `GUI` if you want to use `drop`. nvim and vim do the same thing for your test case. 

If a horizontal split is used, it works as expected, so this could be a bug.
