### ISSUE TITLE
E874: (NFA) Could not pop the stack

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim#5618]
- `nvim --version`: `v0.2.0-90-g108d54b` and `v0.1.6`
- Vim 8.0.84 behaves differently
- Operating system/version: macOS Sierra
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: slightly customized `xterm-256color`

### Actual behaviour

```
Error detected while processing function rubycomplete#Complete[22]..provider#ruby#Call:
line   17:
W, [2016-11-16T14:08:22.251688 #24861]  WARN -- Neovim::Host: got unexpected error #<Argu
mentError: Vim(let):E874: (NFA) Could not pop the stack !>
Error detected while processing function rubycomplete#Complete[22]..provider#ruby#Call:
line   17:
Vim(let):E874: (NFA) Could not pop the stack !
Error detected while processing function rubycomplete#Complete:
line   22:
E171: Missing :endif
```

### Expected behaviour

Some kind of completion -- no such error for sure.

### Steps to reproduce using `nvim -u NORC`

Using omni-completion in a Ruby buffer (therefore `omnifunc=rubycomplete#Complete`) after `~/.`:

```
$ nvim -u NORC test.rb
i~/.<c-x><c-o>
```

**Comment by mhinz** [comment]
It's most probably an issue in the Ruby client, but other people would probably search for an issue like this here anyway.

CC @alexgenco

**Comment by justinmk** [comment]
Does it happen if you revert https://github.com/neovim/neovim/pull/5609 ? Also bisecting ~1 month ago would be valuable to check.

**Comment by mhinz** [comment]
Reverting #5609 didn't help, neither did going back to a commit from 2 months ago.

Hard to tell if #5204 is related, but the explanation from @stephenprater, that `rubycomplete.vim` is more or less broken with Neovim's approach of handling plugins makes sense to me.

**Comment by stephenprater** [comment]
Yeah - the way that the built in Ruby omnicompletion works is basically never going to work with Neovim's approach - it's super hard to read, but I'm pretty sure it's doing a lot of reflection / introspection within Vim's internal interpreter, so sort of obviously, that's not going to work with the sidecar process.  

I was thinking about maybe replacing it with a Neovim client for https://github.com/dgutov/robe

**Comment by justinmk** [comment]
The steps worked for me on 0.2.

**Comment by alem0lars-yoroi** [comment]
I'm still having the same issue:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/etc/xdg/nvim/cache/vimplug/deoplete.nvim/rplugin/python3/deoplete/
source/omni.py", line 96, in gather_candidates
[deoplete]     self.__omnifunc, 0, context['complete_str'])
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/api/nvim.py", line 230, i
n call
[deoplete]     return self.request('nvim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/api/nvim.py", line 131, i
n request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/lib64/python3.4/site-packages/neovim/msgpack_rpc/session.py",
line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Vim(return):W, [2017-02-09T09:09:59.432917 #27
997]  WARN -- Neovim::Host: got unexpected error #<ArgumentError: Vim(let):E874: (NFA)
 Could not pop the stack !>'
[deoplete] Error occurred calling omnifunction: rubycomplete#Complete.  Use :messages
for error details.
```

**Comment by justinmk** [comment]
Version?
