### ISSUE TITLE
Random exits at random times

### ISSUE THREAD

**Issue by jcmuller** [neovim/neovim#5625]
- `nvim --version`: v0.2.0-66-g0c799a8
- Vim (version: 7.4-1-1689) behaves differently? Yes
- Operating system/version: Linux 4.4.0-47-generic, Ubuntu 16.04
- Terminal name/version: GNOME Terminal/3.18.3
- `$TERM`: screen-256color (when in tmux -- same result when TERM=xterm-256color outside of tmux)

### Actual behaviour
NeoVim randomly exits without any message or stack trace. There is no telling how long it will take before it does. I have to revert to using gVim :(

### Expected behaviour
NeoVim doesn't exit randomly.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Running `nvim -DVerrors.log`, the last lines are:
```
Executing FocusGained Auto commands for "*"
autocommand :if has('clipboard') | call <SID>YRFocusGained() | endif

Error detected while processing function <SNR>151_YRFocusGained[15]..<SNR>151_YRCheckClipboard[20]..provider#clipboard#Call[1]..412[4]..<SNR>152_try_cmd:
line    2:
E5677: Error writing input to shell-command: EPIPE
```

**Comment by justinmk** [comment]
Likely the same issue as https://github.com/neovim/neovim/issues/5558, I'll push a fix soon.

**Comment by jcmuller** [comment]
Thanks for the prompt response! I'll disable YankRing for the time being.

**Comment by justinmk** [comment]
The crash should be fixed, on master. But you may see `E5677` now, this is expected. See `:help E5677`.

However I don't see anywhere in yankring that is writing to a "backgrounded" shell command. Perhaps `provider/clipboard.vim` is triggering this somehow.
