### ISSUE TITLE
Remove statusline 

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#5626]
How do I remove the status line?

**Comment by mhinz** [comment]
`:h 'laststatus'`

**Comment by wamoyo** [comment]
Thanks, man!

**Comment by Golam-moula** [comment]
> :h 'laststatus'

so how do i remove it?

**Comment by Golam-moula** [comment]
set laststatus=0

**Comment by charbelnicolas** [comment]
For now, if you have a tab with various windows, you always get a status line no matter what. It would be nice if there was a way to completely disable/remove status lines for all windows.

vim.opt.laststatus = 0

![20221005_195038](https://user-images.githubusercontent.com/14960414/194189766-5fed3509-4ca3-4c47-85e1-ec6d1071090a.png)

vim.opt.laststatus = 2

![20221005_194933](https://user-images.githubusercontent.com/14960414/194189814-91a8fee7-834a-402f-b52d-ed417c6146a5.png)

vim.opt.laststatus = 3

![20221005_195002](https://user-images.githubusercontent.com/14960414/194189842-ea59de31-6394-4766-a219-1bdad8a5e4b2.png)

There is no way to get rid of it completely :(

**Comment by Shougo** [comment]
@charbelnicolas Please see this.

https://github.com/neovim/neovim/issues/18965

The statusline is used as window separator.  It cannot be removed completely.

**Comment by turkishfilms** [comment]
Id vote yes on laststatus=4 meaning no stl ever. not one window or two or horizontal or anything. i want all code.

**Comment by danrasmuson** [comment]
@mhinz Can we reopen this issue?

`set laststatus=0` does not completely remove all status lines

![CleanShot 2024-05-14 at 17 01 23](https://github.com/neovim/neovim/assets/4013767/9434c58b-072e-4a2f-986b-cde01aba93a9)

**Comment by 0rtz** [comment]
Yeah, this is a weird behavior imo. We should have an ability to hide statusline completely
