### ISSUE TITLE
neovim freezes waiting for password of openssl when trying to cryptography a file

### ISSUE THREAD

**Issue by ronisbr** [neovim/neovim#5631]
- `nvim --version`: 0.1.6
- Vim (version: ) 8.2 behaves differently? yes
- Operating system/version: openSUSE Tumbleweed
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour
I'm trying to use openssl to cryptography a file in neovim. The command is:
```
%!openssl enc -aes-256-cbc -a -salt -in %
```
It shows the message to type the password, but then it freezes.

### Expected behaviour
After typing the password for the first time, it must appear the message to type the password again.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Write something and save the file
%!openssl enc -aes-256-cbc -a -salt -in %
It will show the message to type the password, but then everything will be frozen.
```

Notice that I can perform this action in Vim.

**Comment by oni-link** [comment]
Does using <C-j> instead of <cr> (enter) helps?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/1496

**Comment by ronisbr** [comment]
Hi @oni-link,
Thanks very much, it indeed worked 👍
