### ISSUE TITLE
Unmapping global mappings in buffer-local way

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#5645]
- `nvim --version`: 0.2.0-104-g5f02608

A lot of plugins define buffer-local mappings that often conflict with the user's global mappings. e.g. [vimagit](https://github.com/jreybert/vimagit/issues/new) defines `N` to jump to the last git hunk, but I have a mapping that causes it to find the last search and show its search index. 

`unmap <buffer> N` will wipe the local mapping, but there doesn't seem to be a way to wipe the global mapping from a single buffer.

Is there a way to do that, or could it be made an option like `<buffer>`?

**Comment by wsdjeg** [comment]
buffer-local mappings well overwrite the global mappings in current buffer, it is feature, I think you can use different mappings for the feature you want;
BTW neovim support `<M-` `<D-` and so on, I think it is more easy get it in neovim than vim.

**Comment by justinmk** [comment]
`<nowait>` might be helpful, unless the mapping is exactly the same. In that case it's simply a problem that you should report to the plugin author. You can also use `:mapclear <buffer>` to clear all buffer-local mappings, then selectively opt-in to the mappings you actually _want_ from a plugin.
