### ISSUE TITLE
setreg not working with '*'

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#5646]
- `nvim --version`: v0.2.0-104-g5f02608
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: OSX 10.11.6
- Terminal name/version: iTerm2 3.0.20161119-nightly
- `$TERM`: screen-256color

### Actual behaviour

I have a function (source [here](https://gist.github.com/jfelchner/2dcc458b56dd1a7f1ca1d15c3a7af594)) which saves off the unnamed register, performs a place, and then sets the unnamed register back to the value it was before the place.  This works fine in vim and worked fine in Neovim until I updated a few weeks ago.

Currently in Neovim `setreg` doesn't set the unnamed register.  If I change `*` to another register (eg `a`) it sets `a` just fine.  But it will not set `*`.

### Steps to Reproduce

The minimal `.vimrc` you'll need is https://gist.github.com/jfelchner/4c1bb011a7883c28ce9a7651ac88ea9d

Using this `.vimrc` in Vim 7.4 results in the correct behavior.  Commenting `clipboard` results in the current Neovim behavior.  That is to say if `clipboard` is set to `unnamed`, the unnamed register is allowed to be set with Vim.  If it is not set to `unnamed`, the unnamed register is not able to be set.

With Neovim, whether `clipboard` is set or not results in the unnamed register not being able to be set.

Here is a video demonstration:

https://www.dropbox.com/s/itragvz9q85y0sk/neovim-setreg-issue.mp4?dl=1

As a side note, notice that there is a _very_ distinct lag compared to Vim.

**Comment by jfelchner** [comment]
@justinmk there was a patch somewhere (maybe it was in IRC) and now (after a reformat) I've lost it.  This kills me multiple times a day.  Can you help?

**Comment by bfredl** [comment]
I can't see the difference. without `cb=unnamed`, `setreg('*', 'text')` will change the `*` register but not the unnamed register, in both vim and nvim. with `cb=unnamed` both registers are changed, same in vim and nvim. What are minimal steps to reproduce the actual difference?

**Comment by bfredl** [comment]
Sorry I was to quick, the bug only happens when `setreg()` is inside a function,  due to `clipboard_needs_update` optimization which delays unnamed clipboard yank inside vimscript. Probably `clipboard_needs_update` should be set to false in the `*name == '*'` branch in `adjust_clipboard_name` when `writing` so the the delayed unnamed write doesn't overwrite the later exlicit `setreg()`.

**Comment by rawaludin** [comment]
Has there been any resolution for this?

**Comment by jfelchner** [comment]
@justinmk I know there is limited development time, but this has been broken for almost two years and there is a ready [patch to fix it](https://gist.github.com/jfelchner/1e00b8ae8d3e901d94213d6db5495e5a).  Is there any chance we can get this in any time soon with a test to ensure it doesn't happen again?

I'm having to apply this every time I reinstall neovim which makes upgrading a huge pain.

**Comment by KillTheMule** [comment]
@jfelchner How about submitting a PR?

**Comment by bfredl** [comment]
@jfelchner That patch doesn't seem generic, it just limits the places the optimization applies to. Rather we should fix the correctness of the optimization as I mentioned (which I think can be done, I will try it later)

**Comment by bfredl** [comment]
something like this (haven't tested yet, but to give the idea):

```git
diff --git a/src/nvim/ops.c b/src/nvim/ops.c
index b39b139f9..9031dfd44 100644
--- a/src/nvim/ops.c
+++ b/src/nvim/ops.c
@@ -5566,6 +5566,9 @@ static yankreg_T *adjust_clipboard_name(int *name, bool quiet, bool writing)
 
   if (explicit_cb_reg) {
     target = &y_regs[*name == '*' ? STAR_REGISTER : PLUS_REGISTER];
+    if (writing && (cb_flags & (*name == '*' ? CB_UNNAMED : CB_UNNAMEDPLUS))) {
+      clipboard_needs_update = false;
+    }
     goto end;
   } else {  // unnamed register: "implicit" clipboard
     if (writing && clipboard_delay_update) {
```

Though it doesn't do the right thing for `cb=unnamed,unnamedplus`, would need separate global flags for each register for that.

**Comment by bfredl** [comment]
I will test it myself when I get time.

**Comment by jfelchner** [comment]
@justinmk I know you all have a ton of priorities but it's been 2.5 years and this seems like a small fix.  Can we PLEASE get this into 0.4?

**Comment by justinmk** [comment]
I'm workin on a PR now. This would have gone a lot faster if someone sent a PR with a test case. I see that there's some sample code given, but still it takes time to interpret before/after cases, especially since I personally don't care at all about the `*` register.

**Comment by jfelchner** [comment]
@justinmk thank you so much! And I don't know C at all or I would've been happy to help.
