### ISSUE TITLE
Vim 8 new variables

### ISSUE THREAD

**Issue by fsouza** [neovim/neovim#5647]
I know that neovim doesn't guarantee forward compatibility with Vim, but Vim 8 introduced some [new variables](https://github.com/vim/vim/blob/182707ac10d77359bf7a87c6b23ce4025d5b0ad4/runtime/doc/version8.txt#L315-L341) that are useful for plugin authors, and if plugins start using those variables, they won't be compatible with neovim. 

It already happened in vim-go (see fatih/vim-go#1108), and I imagine it's going to happen to other plugins as well.

Is there any plan to support those variables in neovim?

**Comment by jamessan** [comment]
We routinely working on [merging upstream patches] back into Neovim, where applicable.  This particular patch ([7.4.2071]) is one that we intend to merge (i.e., it isn't marked `NA` in [src/nvim/version.c]).  It just takes time.

We've got ~60 such patches in [queue] right now, but each one takes review and potentially additional work.

[merging upstream patches]: http://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim
[7.4.2071]: https://github.com/vim/vim/releases/tag/v7.4.2071
[src/nvim/version.c]: https://github.com/neovim/neovim/blob/5f0260808cf3712718555ee177476b8aefd78280/src/nvim/version.c#L374
[queue]: https://github.com/neovim/neovim/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20vim-patch%20in%3Atitle

**Comment by fsouza** [comment]
@jamessan nice to know, thank you! :-D

**Comment by brcolow** [comment]
I gave it a shot: https://github.com/neovim/neovim/pull/5648

**Comment by justinmk** [comment]
Closed by #5648

**Comment by fsouza** [comment]
@brcolow @justinmk @jamessan thanks!
