### ISSUE TITLE
The witdh of the popup menu for code completion is too small. Vervose function signatures cannot be displayed correctly.

### ISSUE THREAD

**Issue by alnavv** [neovim/neovim#5649]
Should be a "variable" to set the width of the popup menu.

**Comment by Shougo** [comment]
Please upload the screenshot.

**Comment by justinmk** [comment]
There are no details in this request.

**Comment by languitar** [comment]
I think I can provide some details for this as I have the same wish.

In case the completion is triggered close to the right border of the terminal, it might look something like this:
![2017-11-08t11 04 16 01 00](https://user-images.githubusercontent.com/1336287/32543028-c14f2e94-c474-11e7-9cdd-8a73cd9c2217.png)
In some situations this makes the entries indistinguishable and completion pretty useless.

It would be nice if there was an option to specify a minimum width of the completion popup and in case the width cannot be held, the origin of the popup could be shifted to the left, away from the cursor position. As there is always only one of these popups, I don't see a strong reason why it always has to appear at the cursor location.

**Comment by Shougo** [comment]
@languitar It is the same in Vim.
You should request the feature in Vim issues.

**Comment by jamessan** [comment]
Sounds a bit like [Debian bug #450481](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=450481).  I made a patch for it back then.  Might be worth seeing if it still applies cleanly and solves the problem.

**Comment by Shougo** [comment]
Oh.  It is already applyed?

**Comment by jamessan** [comment]
No.  It sat on the todo list for 3 years and then disappeared.

**Comment by Shougo** [comment]
It can be applyed in neovim?

> No. It sat on the todo list for 3 years and then disappeared.

Hm...

**Comment by languitar** [comment]
So any chance to reopen this issue? Or how to proceed?

**Comment by chrisbra** [comment]
request at the vim tracker I believe, including the link to the debian bug and patch

**Comment by nponeccop** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/528415/33234599-614b5984-d200-11e7-87a2-d34ccdfaf57d.png)

The screen has some 150 columns of space, but the popup uses only a small fraction of it. This can be a problem of deoplete plugin or of the source it used, in principle, so I have no idea where to start.
 Note the `..`

**Comment by Shougo** [comment]
> The screen has some 150 columns of space, but the popup uses only a small fraction of it. This can be a problem of deoplete plugin or of the source it used, in principle, so I have no idea where to start.

This is not neovim problem.
It just your configuration problem.

`:help g:deoplete#max_menu_width`

**Comment by nponeccop** [comment]
So we answered the original @alnavv question. There is such variable, in fact. And @languitar issue seems to be unrelated
