### ISSUE TITLE
Appending to a hidden buffer via python api moves  cursor in unrelated window

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#5650]
- `nvim --version`:

```
NVIM v0.2.0-27-g01f1028
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/languitar/.cache/pacaur/neovim-git/src/neovim-git/build/config -I/home/languitar/.cache/pacaur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/languitar/.cache/pacaur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/languitar/.cache/pacaur/neovim-git/src/neovim-git/build/include
Compiled by languitar@jaco

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: Archlinux  64
- Terminal name/version: termite
- `$TERM`: `xterm-termite`

### Actual behaviour

I am using https://github.com/bfredl/nvim-ipy for working in python. This plugin, when connecting to a remote service, creates a new window and uses the contained buffer for showing its interaction with that service. If you hide that buffer and execute any action that produces output in the hidden buffer, the cursor in you current (completely unrelated) window moves around, despite the fact that the plugin only interacts with its own buffer.

I have created a simplified plugin to demonstrate only this behavior: https://github.com/languitar/nvim-bufferbug

### Expected behaviour

If text is appended to a hidden buffer, unrelated windows and buffers should not be changed and the cursor should stay at the respective position.

### Steps to reproduce using `nvim -u NORC`

1. Clone https://github.com/languitar/nvim-bufferbug somewhere and move cwd to the cloned directory
1. `nvim -u init.vim`
1. `:UpdateRemotePlugins`
1. restart vim the same way
1. Open a file containing a few lines: `:e some file`
1. `:BufferBugInit`
1. Move to the opened window and `:q`
1. In the remaining windows with the text file to edit move the cursor somewhere and call `:BufferBug`

The cursor will move around.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/7756
