### ISSUE TITLE
Man cannot open specific section  from command line

### ISSUE THREAD

**Issue by quinoa42** [neovim/neovim#5655]
- `nvim --version`:
Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/build/config -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/src -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161117-95208-3e6vc/neovim-0.1.6/build/include
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"

- Vim (version:7.4 ) behaves differently? yes (using SuperMan.vim)
- Operating system/version: OS X Sierra
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour

`nvim -c "Man 3 printf"` or `nvim -c "Man printf(3)` result as opening `printf(1)`.

### Expected behaviour

Open `printf(3)`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c "Man printf(3)"
nvim -u NORC -c "Man 3 printf"
```
Both will open `printf(1)` instead. However, call `:Man 3 printf` or `:Man printf(3)` inside neovim do work.

**Comment by mhinz** [comment]
Interesting. At the time of the execution `v:count1` does not default to 1 yet and the plugin does `v:count0 == v:count1` to check if the section was explicitly given. (So, it really executes `Man 0 printf` which is `Man 1 printf`....)
