### ISSUE TITLE
Feature request: cmdline mode for RPC api

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#5661]
I need the RPC tell me if current mode is cmdline, but currently it only send `"insert", "replace" and "normal"` and I noticed `normal` is send on `mode_change` when user enter command line.

I need this because I want change system input method to default after user leave cmdline, because user could be searching with chinese input, then they have to change input method manually to use normal mode.  

I managed to do this by change the code

``` diff
diff --git a/src/nvim/api/ui.c b/src/nvim/api/ui.c
index 56b41f1..9178538 100644
--- a/src/nvim/api/ui.c
+++ b/src/nvim/api/ui.c
@@ -271,6 +271,8 @@ static void remote_ui_mode_change(UI *ui, int mode)
     ADD(args, STRING_OBJ(cstr_to_string("insert")));
   } else if (mode == REPLACE) {
     ADD(args, STRING_OBJ(cstr_to_string("replace")));
+  } else if (mode == CMDLINE) {
+    ADD(args, STRING_OBJ(cstr_to_string("cmdline")));
   } else {
     assert(mode == NORMAL);
     ADD(args, STRING_OBJ(cstr_to_string("normal")));
diff --git a/src/nvim/ui.c b/src/nvim/ui.c
index eb50041..3e31b90 100644
--- a/src/nvim/ui.c
+++ b/src/nvim/ui.c
@@ -537,6 +537,8 @@ static void ui_mode_change(void)
     mode = REPLACE;
   else if (State & INSERT)
     mode = INSERT;
+  else if (State & CMDLINE)
+    mode = CMDLINE;
   else
     mode = NORMAL;
   UI_CALL(mode_change, mode);
```
I know this may break something, but please consider.

**Comment by bfredl** [comment]
I don't see any reason against it. It seems that we lack tests for `ui_mode_change`, probably because before #4432 there was no simple way for testing ui state beyond the screen state. I will look into the tests.

**Comment by chemzqm** [comment]
I thought it's just not supported, the documentation of RPC don't have cmdline mode.

**Comment by bfredl** [comment]
@chemzqm Feel free to open a PR based on your suggested changes. I think what is needed more is documentation update (in `msgpack_rpc.txt`, line 392-394) and adding a test ( following the tests in #5666 ). Otherwise I will look into it myself later.

**Comment by chemzqm** [comment]
Great, I will send a PR.
