### ISSUE TITLE
TUI: change the colors of the host terminal/UI

### ISSUE THREAD

**Issue by Soares** [neovim/neovim#5668]
- `nvim --version`:

        NVIM 0.1.6

        Build type: RelWithDebInfo
        Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/config -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/src -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161109-5888-vdlxxw/neovim-0.1.6/build/include
        Compiled by nate@Athena

        Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
        For differences from Vim, see :help vim-differences

           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"

- Vim (version: 7.4.1910) behaves differently? Yes
- Operating system/version: Mac OSX Yosemite 10.10.5
- Terminal name/version: iTerm2
- `$TERM`: `xterm-256color`

### Actual behaviour

Choose a base16 shell file, such as [this one](https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-google-dark.sh). The idea is that you can source this to change the colors of the host terminal. (This is useful, e.g., when you have a transparent terminal background, so you tell nvim not to paint a background, and you want the host terminal's background color to change colors when vim changes color schemes.)

So you go ahead and `:!eval sh /path/to/the/base16-theme-dark.sh` and... nothing happens. Presumably because `nvim` kindly evals the script in a throwaway process rather than the host terminal, which is great. I don't object to that. The question is, is there any way to source the file in such a way that it does change the colors of a host terminal?

FWIW, this works fine in vim.

### Expected behaviour

I expected there to be *some* way to change the host terminal colors from inside nvim. (If not, this represents a loss of functionality wrt vim, albeit an understandable one -- the new behavior of `:!` is better than the old behavior in vim, despite the fact that this loss of functionality exists).

It's pretty plausible that the functionality still exists somehow and I just couldn't find it by reading the docs.

### Steps to reproduce using `nvim -u NORC`

1. Make sure that nvim has not painted any color on the background (i.e., that the color of the background is whatever the terminal color currently is)
2. `:!eval sh /path/to/base16-theme-dark.sh`
3. Observe that the underlying terminal theme does not change.

You can also try it in vim and verify that it works in vim.

**Comment by justinmk** [comment]
You could try `system('printf ...')` (see [here](https://github.com/neovim/neovim/issues/4867#issuecomment-250911566)). It doesn't seem to work for all users, in some cases redirecting to `$TTY` or `$(tty)` works, or maybe `/dev/stdout`.

The more general solution for writing directly to the terminal is to provide a new API function, e.g. `nvim_ui_write()`. And for general UI capabilities I think we should [expose capability-specific functions](https://github.com/neovim/neovim/issues/4867#issuecomment-250944435).

**Comment by Soares** [comment]
Thanks for the suggestion! `system('printf ...')` doesn't work for me in any of those various forms, but I appreciate the tip (and it may work for some). Exposing capability-specific functions sounds promising to me.

Also: thanks for all your hard work.

**Comment by justinmk** [comment]
Since Nvim 0.3.0 the stderr stream is exposed as `v:stderr` and  `chansend()` can write raw bytes to it. That means if you're running the TUI, this will write to the terminal:

    :call chansend(v:stderr, {string or array})

So arbitrary sequences can be sent to the terminal, which is what `base16-theme-dark.sh` wants to do from the original request here.
