### ISSUE TITLE
popupmenu_external should not complete words directly

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#5672]
- `nvim --version`: NVIM v0.2.0-97-gacbce46
- Operating system/version:  MacOS

### Actual behaviour

I'm trying to use `nvim_ui_attach` with `popupmenu_external` is true, and found it always complete the words directly after the trigger key pressed:

![2016-11-26 21_10_04](https://cloud.githubusercontent.com/assets/251450/20641062/7a69ee70-b42a-11e6-9d0f-d063e85118cb.gif)

I've tried different setting of `completeopt`, all have the same issue.

### Expected behaviour

Should not perform auto complete when popupmenu is shown.

**Comment by bfredl** [comment]
It doesn't look like it has "commited" to the completion immediately, as `popupmenu_hide` is not sent directly. Does `<c-n>`and `<c-p>` still work to select different items?

Does it happen even with "longest" in `completeopt` ?

**Comment by chemzqm** [comment]
It's my mistake, it should work like this, closing this.
