### ISSUE TITLE
RPC API commands interrupt input

### ISSUE THREAD

**Issue by Chad-** [neovim/neovim#5685]
- `nvim --version`:
`NVIM v0.2.0-122-g7be113d
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN`
- Operating system/version: Window 10

### Actual behaviour
When an RPC command is sent in between `input` commands, the input is 'interrupted' (probably not the right word for this). In this example session with the python client, the goal is to change a word using `cw`:

```
>>> nvim.current.line
'Test Line'
>>> nvim.input("c")
1
>>> nvim.current.line
'Test Line'
>>> nvim.input("w")
1
>>> nvim.current.line
'wTest Line'
```

When `nvim.current.line` is called in between `c` and `w`, nvim switches to insert mode and inserts a `w`.

### Expected behaviour
Continuing from the previous session, if `nvim.current.line` is not called in the middle it works as expected.

```
>>> nvim.input("<esc>")
5
>>> nvim.input("b")
1
>>> nvim.input("c")
1
>>> nvim.input("w")
1
>>> nvim.current.line
' Line'
```

Is there any way to get around this behavior?

**Comment by justinmk** [comment]
Probably the same as https://github.com/neovim/neovim/issues/3720. Either we need to restore the operator-pending state or block RPCs totally during that state. This will be a priority after 0.2 is released, but until then the priority is stabilizing Neovim on Windows.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/7230
