### ISSUE TITLE
Terminal resize issue

### ISSUE THREAD

**Issue by BigfootN** [neovim/neovim#5688]
### General Information

- `nvim --version`: 0.2.0
- Operating system/version: Archlinux
- WM: Cinnamon
- Graphic drivers: nvidia
- Terminal name/version: rxvt-unicode-patched v9.2
- `$TERM`: rxvt-unicode-256color

### Actual behaviour

Hello,

I am having an issue with neovim when launching it from a fullscreen terminal. Here is a screenshot:

![2016-11-29-160404_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1183923/20714844/9f6ab9c8-b64d-11e6-9609-8140d8b7db95.png)

As you can see there is a little gap on the bottom and the right of neovim, between the editor and the borders of the terminal.

### Steps to reproduce using `nvim -u NORC`

When using `nvim -u NORC` I think that the behavior is actually the same. It's hard to tell since the background color of the terminal and neovim are the same.

I hope that the information given will help you.
Thank you very much in advance

**Comment by justinmk** [comment]
As far as I know there's nothing that an application running inside a terminal can do about this. You can:

- adjust your terminal font size so that the rows and columns better the screen, or 
- use a terminal emulator that always fits the screen (and fills the negative space with the background color), or
- change your terminal background color to match the nvim background color
    - Perhaps there's a way for nvim to do this. Can you check if Vim does it?

**Comment by jamessan** [comment]
Or change the WM to honor the size hints from the terminal (since it's probably setting size hints to match the multiple of the font size).

**Comment by BigfootN** [comment]
Thank you for your answers, 
I think I'll then try several solutions/options, such as changing neovim or the terminal background in order to have the same background color. I also found out that there is option for urxvt that sets the internal borders, but haven't tried it yet. I'll also try changing my WM.

Thank you very much for all your help
