### ISSUE TITLE
Use Vim's syntax files?

### ISSUE THREAD

**Issue by physkets** [neovim/neovim#5689]
- `nvim --version`: **0.1.7**
- Vim (version: **8.0.86**) behaves differently? **YES**
- Operating system/version: **Arch Linux**
- Terminal name/version: **Gnome Terminal 3.22.1**
- `$TERM`: **xterm-256color**

Can't neovim use vim's syntax files? 

Vim's syntax files for some languages were recently updated to include recent revisions in those languages, and I do not see those changes when I use neovim, so I assume that it doesn't use vim's files.

**Comment by justinmk** [comment]
We do use Vim syntax files. But we're a few months behind. Help in merging patches is welcome.

**Comment by physkets** [comment]
Okay, so the following are the syntax directories of neovim and vim:
https://github.com/neovim/neovim/tree/master/runtime/syntax
https://github.com/vim/vim/tree/master/runtime/syntax

I looked through a few neovim syntax files, and they seem to be exactly the same as the ones at vim. So how exactly can I help? (I ask because I've never really used git or github (other than to raise such issues)) Do I 'fork' neovim and paste the vim syntax files, and request a 'merge'? Or is there a better way? Or is it something else that I should do?

**Comment by mhinz** [comment]
@physkets https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim
