### ISSUE TITLE
Repeat works reuses unnamed register. Bug or a feature?

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#5690]
Suppose I want to get from this a,b to this 'a','b'. Yeah, yeah, yeah, I know about surround plugin.
The cursor is on the start of line I'm doing `cw<bsp>'<C-r>"`. I have delimitMate plugin, so this would end in `'a',b`. Now all I need is to repeat the same action on b. But if I'll do that I'll end up with `'a','a'`. Can't find anything on this in docs.

I've skimmed through the source code, but haven't been able to figure out what exactly `start_redo` is doing.

Seems to me (and because this is the way evil-mode in emacs does this also I think I'm not the only one) that this isn't what should happen.
If repeat command should repeat last change it seems logical that it should work like a automatic macros. I mean it should save the the keys that user pressed to do the last change and just repeat them. At least this seems to mirror the context of "last change" more closely.

**Comment by mhinz** [comment]
I assume you meant `cw'<c-r>"'`.

No idea why you think that checking the behaviour of evil-mode would be a good idea. HInt: check in Vim instead. ;-)

You didn't say how you repeat, but I assume using `.`. That repeats the last text change and uses the `.` register, not the unnamed register. See `:reg .`.

**Comment by purpleP** [comment]
@mhinz I know what I can use to achieve what I want, it's just inconvenient to do so.
Why is repeat command uses `.` register instead of capturing entered text like recording a macro does?

As to why I'm checking evil mode behaviour I'll tell you why.
If you would use search in operator pending mode with `hlsearc`h on vim would highlight the search matches. There is no reason to do that and some neovim developers think of this as a bug.
Evil-mode doesn't do that. In some aspects it's a better vim than vim.

So while you closed that, you haven't answered the core question here. What behaviour is really useful for `.`. I think it should be what most of users want, not what vim or vi does.

**Comment by mhinz** [comment]
Does @vim_dev know about that `hlsearch` behaviour and what is their opinion about it? Even if they wouldn't fix it, we _could_ do it Neovim, since it _appears_ to be a simple bugfix.

But changing the behaviour of `.` would be a breaking change, and that won't happen in Neovim if it doesn't happen in upstream as well.

**Comment by bfredl** [comment]
`.` does not mean "repeat the last complete key sequence as if it was a macro", it repeats the action. In this case replace the word with text typed in insert mode, so it remembers the actual text inserted, not the exact sequence of keys that happened to produce this text. `.` works similar if visual mode was invoked as part of the action, it remembers the extent of the region, not the sequence of motion operators defining the region.

I not saying a more macro like .-operator wouldn't be useful, but if only that existed and not the action-`.`, it would be less useful than right now, as it would just be a shorthand for defining macro and there will be no simple way (in general) of achieving what `.` does now

**Comment by purpleP** [comment]
@bfredl I get all that and the concern about backward compatibility. What I don't get is who exactly using this behaviour and how? I can't make up a use case for that. So maybe doing a poll on tweeter or something will be more reasonable. And then with the results of the poll we can try to convince (or not depending on the results) Bram to change this.

**Comment by mhinz** [comment]
Let's talk about the technical side and imagine we abuse macros for it somehow. When exactly would you start recording keys and when would you end?

**Comment by purpleP** [comment]
@mhinz well, I don't have enough time to think about this properly, but sn't this a solved problem already in vim, because vim already doing almost the same thing for `.` operator?

The logic I think basically like this. if this key combination is changing text we record it until returning to normal mode.
Like
`f` - is not an operator
`space` - is not an operator, move cursor to next space
`c` - is operator, start recording
`2` - in recording state, 2 is a count, so the change isn't completed yet, we need to keep recording.
`w` - in recording state, w is a text-object, change isn't completed, keep recording
`some replacement text` - in insert mode, recording until escape
`esc` - stop recording

One problem with that is that we need to know what key is currently bounded to know what it's doing, but that should be possible.
