### ISSUE TITLE
rgb_file and Xresources

### ISSUE THREAD

**Issue by Uroc327** [neovim/neovim#5695]
`syntax.txt` states, that neovim should support a custom `rgb_file` (currently not implemented #5178 ).

I think it would make sense, especially looking at GUI frontends, to instruct nvim to also read the colormap from Xresources to determine rgb values of X colors.

What do you think? Would you merge this into the usual color name <-> rgb mapping or create some extra option/functionality?

**Comment by justinmk** [comment]
> also read the colormap from Xresources to determine rgb values of X colors.

Why? Wouldn't that be the responsibility of a GUI (e.g. https://github.com/equalsraf/neovim-qt ) ?

**Comment by Uroc327** [comment]
Hm.. I thought that this could/would be consistent with the suggested `let rgb_file = "/usr/X11/lib/X11/rgb.txt"` which is using X11 data, too. But probably I confused something there.

When does vim convert color names to rgb codes anyway? In console nvim (or `nvim_ui_attach` with `rgb` set to `false`) this sounds like the terminals/frontends task and in gui vim (with `rgb` set) vim only handles with rgb values coming from `guifg`/`guibg`.

One exception I can see at the moment is, when there is no `gui..` color specified. Then vim would need to convert from the `cterm..` color to some rgb value. As this is meant for guis and its nearyl impossible to get the original color name from a rgb value, it seems consitent to me (as a gui user), to query the Xresources colormap.

**Comment by justinmk** [comment]
`rgb_file` appears to be yak shaving for the `fvwm.vim` syntax file. (Note the `fvwm.vim` tag above that section of syntax.txt.) Also even in the Vim (not Neovim) source, 

    git grep -E '\brgb_file\b'

returns only 2 lines both of which are the aforementioned doc. So, I have no idea what the purpose of that paragraph is.

The whole `4. Syntax file remarks` section of syntax.txt is an exasperating amount of useless details that should have been coalesced into a common convention.
