### ISSUE TITLE
When creating a newline C/C++ from a commented line, It always starts the next line off with a comment

### ISSUE THREAD

**Issue by define-private-public** [neovim/neovim#5696]
- `nvim --version`: NVIM 0.2.0-dev
- Vim (version: ) N/A
- Operating system/version: Ubuntu 16.10
- Terminal name/version: 
- `$TERM`: xterm

### Actual behaviour
If I'm editing a comment in a C or C++ file (that has the extension `.c` or `.cpp`.), and when I press enter and the end of the comment, it starts off the newline with line commented out.  This is useful if I'm doing multi-line comments, but I typically don't.  This is driving me nuts.

I've noticed it only does this when when `filetype plugin indent on` is found in my `init.vim` file.  This is needed for NeoBundle.  I do not have any other C or C++ related scripts installed.

### Expected behaviour
I don't want any comment markers on my newlines.

**Comment by wsdjeg** [comment]
not issue of neovim.
:h comments

**Comment by mhinz** [comment]
```vim
autocmd FileType c,cpp setlocal formatoptions-=r
```

See `:h 'fo'` and `:h fo-table`.

**Comment by define-private-public** [comment]
@mhinz Thanks!  that works great.
