### ISSUE TITLE
neovim is slow with UltiSnips

### ISSUE THREAD

**Issue by DarkDeepBlue** [neovim/neovim#5702]
While using the UltiSnips plugin, nvim is really slow. This is an effect not seen on vim itself. The log files show the clear difference in performance.

- `nvim --version`:
NVIM v0.2.0-6-g3979c6c
Build type: Release
Compilation: /usr/bin/cc -Wconversion -Ofast -s -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE […]

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

- Vim (version: 8.0) behaves differently?
Vim itself has no performance issues with the same configuration using the same plugins.

- Operating system/version: ArchLinux 4.8.11
- Terminal name/version: zsh 5.2 running in urxvtd
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
After starting nvim with the UltiSnips plugin, nvim is very slow even before using any snippets.

For demonstation, the same operations were made in nvim and vim. After opening a file, one single snippet expansion was used. While it takes only 0.039952s  in vim, it takes 0.493287s in nvim. The log files show that the python provider slows down the execution.

[nvim_profile.txt](https://github.com/neovim/neovim/files/627037/nvim_profile.txt)
[vim_profile.txt](https://github.com/neovim/neovim/files/627038/vim_profile.txt)

### Expected behaviour

The performance of vim is expected without any performance issues.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -u nvim.txt
```
[nvim.txt](https://github.com/neovim/neovim/files/627073/nvim.txt)

After that expand a random UltiSnips snippet. Compare the result with vim.

**Comment by chemzqm** [comment]
Add these lines of code and modify the python path to yours would help.
```
  let g:loaded_python_provider = 1
  let g:python_host_skip_check=1
  let g:python_host_prog = '/usr/local/bin/python'
  let g:python3_host_skip_check=1
  let g:python3_host_prog = '/usr/local/bin/python3'
```

**Comment by DarkDeepBlue** [comment]
After adding the additional configuration for python it still does not have the desired effect. I verified the python paths and if the variables are set in nvim correctly. Are there other options I can try out?

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   44   1.306211   1.201427  provider#python3#Call()
    3   0.652454   0.652330  UltiSnips#ExpandSnippetOrJump()
   27   0.413976             UltiSnips#CursorMoved()
    1   0.376851   0.000377  <SNR>19_deoplete_lazy_enable()
    1   0.373192   0.000048  deoplete#enable()
    1   0.371070   0.000253  deoplete#initialize()
    1   0.370232   0.000290  deoplete#init#_initialize()
    1   0.369095   0.000362  deoplete#init#_channel()
    2   0.303913   0.000281  remote#host#Require()
    2   0.303631   0.303570  provider#pythonx#Require()
    1   0.199442   0.000195  remote#define#FunctionBootstrap()
    1   0.168703             _deoplete()
    9   0.109916             UltiSnips#TrackChange()
    5   0.012536   0.004762  deoplete#init#_context()
    5   0.009899   0.000478  <SNR>48_completion_delayed()
    3   0.009421   0.000173  <SNR>48_completion_begin()
   39   0.007566             <SNR>24_Highlight_Matching_Pair()
    7   0.005796   0.003439  <SNR>46_vimoption2python()
    2   0.004555   0.000253  <SNR>48_on_event()
    3   0.003741             UltiSnips#LeavingInsertMode()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   44   1.306211   1.201427  provider#python3#Call()
    3   0.652454   0.652330  UltiSnips#ExpandSnippetOrJump()
   27              0.413976  UltiSnips#CursorMoved()
    2   0.303631   0.303570  provider#pythonx#Require()
    1              0.168703  _deoplete()
    9              0.109916  UltiSnips#TrackChange()
   39              0.007566  <SNR>24_Highlight_Matching_Pair()
    5   0.012536   0.004762  deoplete#init#_context()
    3              0.003741  UltiSnips#LeavingInsertMode()
   12              0.003676  deoplete#util#uniq()
    7   0.005796   0.003439  <SNR>46_vimoption2python()
   13              0.001830  deoplete#util#get_input()
    1   0.001932   0.000772  remote#host#RegisterPlugin()
   10              0.000750  deoplete#util#get_buffer_config()
    9              0.000695  <SNR>48_completion_check()
    5   0.009899   0.000478  <SNR>48_completion_delayed()
   23              0.000404  deoplete#util#set_default()
    1   0.376851   0.000377  <SNR>19_deoplete_lazy_enable()
    1   0.369095   0.000362  deoplete#init#_channel()
    3   0.001013   0.000304  <SNR>48_is_skip()

**Comment by justinmk** [comment]
Do you  have antivirus or some other process inspection daemon ?

**Comment by DarkDeepBlue** [comment]
No, I don't have such daemons or anything similar.
How can I provide more information for you?

**Comment by justinmk** [comment]
You could try `:CheckHealth`. Do you have "autotrigger" enabled? See https://github.com/SirVer/ultisnips/issues/593 -- this option spams the RPC channel, so it's slow. It could be worked around, but UltiSnips chose not to.

**Comment by DarkDeepBlue** [comment]
At least it’s much better now after applying `au! UltiSnips_AutoTrigger.`.

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   11   0.368854   0.189144  provider#python3#Call()
    1   0.179711   0.000129  remote#host#Require()
    1   0.179582   0.179552  provider#pythonx#Require()
    1   0.141614   0.141602  UltiSnips#ExpandSnippetOrJump()
    7   0.021477             UltiSnips#CursorMoved()
    2   0.005240   0.000227  <SNR>48_completion_delayed()
    2   0.005013   0.000095  <SNR>48_completion_begin()
    2   0.004421   0.001730  deoplete#init#_context()
   10   0.001790             <SNR>24_Highlight_Matching_Pair()
    2   0.001344   0.000046  deoplete#util#vimoption2python()
    2   0.001297   0.000819  <SNR>46_vimoption2python()
    1   0.001037             UltiSnips#LeavingInsertMode()
    4   0.000926             deoplete#util#uniq()
    6   0.000679             deoplete#util#get_input()
    2   0.000496   0.000150  <SNR>48_is_skip()
    2   0.000279   0.000041  deoplete#util#get_next_input()
    2   0.000274             <SNR>48_completion_check()
    4   0.000264             deoplete#util#get_buffer_config()
    2   0.000114             <SNR>48_is_skip_textwidth()
    1   0.000069             <SNR>48_on_insert_char_pre()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   11   0.368854   0.189144  provider#python3#Call()
    1   0.179582   0.179552  provider#pythonx#Require()
    1   0.141614   0.141602  UltiSnips#ExpandSnippetOrJump()
    7              0.021477  UltiSnips#CursorMoved()
   10              0.001790  <SNR>24_Highlight_Matching_Pair()
    2   0.004421   0.001730  deoplete#init#_context()
    1              0.001037  UltiSnips#LeavingInsertMode()
    4              0.000926  deoplete#util#uniq()
    2   0.001297   0.000819  <SNR>46_vimoption2python()
    6              0.000679  deoplete#util#get_input()
    2              0.000274  <SNR>48_completion_check()
    4              0.000264  deoplete#util#get_buffer_config()
    2   0.005240   0.000227  <SNR>48_completion_delayed()
    2   0.000496   0.000150  <SNR>48_is_skip()
    1   0.179711   0.000129  remote#host#Require()
    2              0.000114  <SNR>48_is_skip_textwidth()
    2   0.005013   0.000095  <SNR>48_completion_begin()
    1              0.000069  <SNR>48_on_insert_char_pre()
    4              0.000048  deoplete#util#convert2list()
    2   0.001344   0.000046  deoplete#util#vimoption2python()
```

Could you give me a hint where to place it exactly in the config files? If I do it in `~/.config/nvim/init.vim`, I get the following error.

```
Error detected while processing /home/syrex/.config/nvim/init.vim:
line  382:
E216: No such group or event: UltiSnips_AutoTrigger
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
What are the Vim numbers?

Anyway, it's possible to make fast plugins in Neovim. The compatibility layer for legacy plugins works well, but it's not perfect. There's not much else we can do.

**Comment by DarkDeepBlue** [comment]
I provided the results for vim in [vim_profile.txt](https://github.com/neovim/neovim/files/627533/vim_profile.txt) above.

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.039952   0.039895  UltiSnips#ExpandSnippetOrJump()
   13   0.003134             <SNR>30_Highlight_Matching_Pair()
    8   0.002317             UltiSnips#CursorMoved()
    3   0.002003             UltiSnips#TrackChange()
    1   0.000170             UltiSnips#LeavingInsertMode()
    1   0.000051             <SNR>53_compensate_for_pum()
    1   0.000036             ScreenMovement()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   0.039952   0.039895  UltiSnips#ExpandSnippetOrJump()
   13              0.003134  <SNR>30_Highlight_Matching_Pair()
    8              0.002317  UltiSnips#CursorMoved()
    3              0.002003  UltiSnips#TrackChange()
    1              0.000170  UltiSnips#LeavingInsertMode()
    1              0.000051  <SNR>53_compensate_for_pum()
    1              0.000036  ScreenMovement()
```

For now I will use it as it is and switch to vim if the performance bothers me too much. Hope to see really fast plugins in the future. :)

Thank you for solving the issue.

**Comment by Shougo** [comment]
> For now I will use it as it is and switch to vim if the performance bothers me too much. Hope to see really fast plugins in the future. :)

The compatibility layer calls Python process.
It is slow.  No magic for it.
You should not load UltiSnips when file opening.
Lazy load UltiSnips is better when insert enter autocmd.

**Comment by DarkDeepBlue** [comment]
This improves the startup time, but the real performance issue is the compatibility layer which has to be used anyway.

**Comment by Shougo** [comment]
You can use other snippet plugin...

**Comment by DarkDeepBlue** [comment]
As I have written earlier the performance right now is something I can live with more or less. I understand that it cannot be improved regarding UltiSnips on neovim.

In fact I switched to vim-snippets for vim and neovim a while ago because I thought the performance issues come from UltiSnips itself. After I realized that it has something to do with neovim, I switched back on vim. Reason for that is that UltiSnips is more advanced and supports a few things I like. Also, the syntax is more pleasing for me.

If you have any suggestions für a better snippet plugin for neovim, go ahead.

**Comment by DarkDeepBlue** [comment]
Actually, your neocomplete works pretty well.

**Comment by DarkDeepBlue** [comment]
Aaaand it works with vim, too!
I can’t believe I missed it the first time!
Thank you for the hint very much. That’s really great now.

**Comment by Shougo** [comment]
> Actually, your neocomplete works pretty well.

neosnippet?

I want to rewrite neosnippet for neovim using the remote plugin feature.
It will be the best snippet plugin for neovim.

**Comment by DarkDeepBlue** [comment]
Yes, I mean neocomplete with neosnippet.

I’m using neosnippet for now and this is great.
Later, I will definitely try out your improvement on it.
Thank you for your work.
