### ISSUE TITLE
Missing conceal characters in TeX syntax file

### ISSUE THREAD

**Issue by AntoineGagne** [neovim/neovim#5703]
I have been working with `tex` files recently with the following lines in my `.vimrc`:

```vim
set cole=2
let g:tex_conceal='adgms'
```
to display the TeX commands as unicode character in math equations. It works correctly for most of the symbols. However, some of the symbols such as `\iota`, `land`, `lor` and others seems to be missing. 

Here are some examples of what I mean:

![example_1](https://cloud.githubusercontent.com/assets/6211479/20839933/7b946338-b87c-11e6-8d06-81e1bc86565c.png)

![example_2](https://cloud.githubusercontent.com/assets/6211479/20840005/c4a9a6e6-b87c-11e6-8cbd-1b81a99ddd12.png)

I tried adding them to the `runtime/syntax/tex.vim` file in a [fork](https://github.com/AntoineGagne/neovim) of `neovim`. I compiled `neovim` by installing the dependencies and running `make` in the clone of the fork. However, when I try running the executable `build/bin/nvim` on a `tex` file, it seems to look for the global installation and tells me:

```
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
```

What am I doing incorrectly?

I am not sure if it is the correct place to post this since this is my first time trying to contribute to an open source project. Sorry if this issue does not respect the guidelines or if it is not the good place for this kind of question.

Thank you for your time!

**Informations about my system:**

- OS: *Ubuntu 16.04 LTS*
- Terminal name: `pantheon-terminal`
- `$TERM`: `xterm-256color`
- `nvim --version`: `NVIM 0.2.0-dev`

**Comment by zauguin** [comment]
Thanks. This always bugged me, but I was to lazy to add them myself.

I tried the syntax file from your fork and got multiple Invalid Expression errors, because you used non-breaking spaces instead of regular ones.

For neovim to use your local runtime directory instead of the global one, you have to point the `VIMRUNTIME` environment variable to the `runtime`  directory.

**Comment by AntoineGagne** [comment]
Thanks for the answer and for pointing out about the non-breaking spaces!

**Comment by jamessan** [comment]
Sorry that no one mentioned this sooner, but we don't change the runtime files without good reason to do so.  Instead, we want the runtime patches to go to their maintainer (listed at the top of the file), get integrated into Vim, and we'll merge them as part of our regular patch merging from Vim.

**Comment by AntoineGagne** [comment]
Ah I didn't know! I'll close this issue and the related PR then.

**Comment by jamessan** [comment]
Thanks for taking the time to help, and I hope to see your changes in a future merge of runtime files! :)
