### ISSUE TITLE
Visual mode overwrite paste from ". (last inserted text) rings bell and doesn't insert text

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#5709]
- `nvim --version`:
0.1.6
- Vim (version: ) behaves differently?
8.0 -- No, same problem
- Operating system/version:
Arch linux
- Terminal name/version:
XTerm(327)
- `$TERM`:
xterm-256color

### Actual behaviour
Start nvim with `nvim -u NONE`
Insert the text `hello world` into the buffer.
While pasting the last inserted text works normally (`".p` puts the text into the current buffer), pasting that register in visual mode to replace the current selection rings the bell and just removes the selected text without replacing it.

```
ihello world<Esc>
0ve".p
```

End up with
```
 world
```
in the buffer and still in visual mode

### Expected behaviour
I would expect that the word `hello` were replaced by `hello world` -- the contents of the `".` register.

End up with
```
hello world world
```
in the buffer, and in normal mode.

**Comment by justinmk** [comment]
That does look like a bug. cc @chrisbra @brammool
