### ISSUE TITLE
setpos() ignores "bufnum" argument if {expr} is a lowercase mark

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#5713]
`:help setpos()` mentions an argument `"bufnum"` that determines the buffer a mark should be put in.
This argument is respected for uppercase marks, but not for lowercase marks.
This is reasonable (though I personally would like `setpos()` to be able to set marks in other buffers), but the help doesn't mention this anywhere.

It's also strange that attempting to change buffers with `setpos('.', [bufnr('#'), 1, 1, 0])` alerts the user that having a different buffer is an error, while attempting to set a mark with `setpos("'d", [bufnr('#'), 1, 1, 0])` doesn't tell the user that the `"bufnum"` argument is an error.

### Demonstration of the behaviour.
With the files
`test.txt`
```
First line of test.txt
Some filler words
```

`test2.txt`
```
First line of test2.txt
These are some words
```

`nvim -u NONE test.txt test2.txt`
```
bufdo 1mark d
call setpos("'d", [1, 2, 0, 0])
```
observe that the mark `'d` in the current buffer (`test2.txt`) is on the second line, while mark `'d` in the first buffer (`test.txt`) is still on the first line.

### Suggestion

I think that either `:help setpos()` should mention this (see the diff below), or it should allow setting the mark in a different buffer.

```diff
diff --git a/runtime/doc/eval.txt b/runtime/doc/eval.txt
index 9c6cbd5..0870f08 100644
--- a/runtime/doc/eval.txt
+++ b/runtime/doc/eval.txt
@@ -6098,7 +6098,8 @@ setpos({expr}, {list})
 		current buffer.  Setting the cursor is only possible for
 		the current buffer.  To set a mark in another buffer you can
 		use the |bufnr()| function to turn a file name into a buffer
-		number.
+		number. If {expr} is a lowercase mark the current buffer is
+		always used.
 		Does not change the jumplist.
 
 		"lnum" and "col" are the position in the buffer.  The first
```

**Comment by hardenedapple** [comment]
I just had a quick look at this, and it appears the following patch changes the current behaviour to match the documentation.

```diff
diff --git a/src/nvim/mark.c b/src/nvim/mark.c
index 6453c41..addf16d 100644
--- a/src/nvim/mark.c
+++ b/src/nvim/mark.c
@@ -135,7 +135,17 @@ int setmark_pos(int c, pos_T *pos, int fnum)
     return FAIL;
   if (islower(c)) {
     i = c - 'a';
-    RESET_FMARK(curbuf->b_namedm + i, *pos, curbuf->b_fnum);
+    buf_T *buf = curbuf;
+    if (fnum != curbuf->b_fnum) {
+        buf = firstbuf;
+        while (buf != NULL && buf->b_fnum != fnum) {
+            buf = buf->b_next;
+        }
+        if (buf == NULL) {
+            return FAIL;
+        }
+    }
+    RESET_FMARK(buf->b_namedm + i, *pos, fnum);
     return OK;
   }
   if (isupper(c)) {
```

I'm not sure whether you guys feel the behaviour or documentation should be changed, but looked for this based on the title change.

There are only two places where the function `setmark_pos()` is called, one is from `setmark()` where the `fnum` argument is hard-coded to be of the current buffer, and the other from the `setpos()` function itself, so I doubt this will have adverse effects.
I ran the test suite and everything seemed fine.

I can add a test for this specific behaviour if needed -- I wasn't quite sure where to put it or whether having tests for every vimL function is thought of as overkill.

**Comment by justinmk** [comment]
> whether having tests for every vimL function is thought of as overkill.

Not at all. The more the merrier.

@chrisbra This seems like a change Vim would want as well.

**Comment by chrisbra** [comment]
Am 2016-12-06 12:09, schrieb Justin M. Keyes:
>> whether having tests for every vimL function is thought of as
>> overkill.
> 
> Not at all. The more the merrier.
> 
> @chrisbra [1] This seems like a change Vim would want as well.

Yeah, I saw it. CC @brammool
