### ISSUE TITLE
Refactor code that uses the "two-iteration loop" anti-pattern for code reuse

### ISSUE THREAD

**Issue by philix** [neovim/neovim#572]
See https://github.com/neovim/neovim/commit/1ab6cf47bd4218c303459efd288456e51f46033b for an example of refactoring of code that uses this anti-pattern.

Using static functions is a much cleaner and less tricky way of reusing blocks of code.

See https://github.com/neovim/neovim/blob/master/src/buffer.c#L1857, for example:

EDIT: this example is already being fixed by @harsh1kumar on #678. Find a different one if you want to work on this issue.

```c
  /*
   * attempt == 0: try match with '\<', match at start of word
   * attempt == 1: try match without '\<', match anywhere
   */
  for (attempt = 0; attempt <= 1; ++attempt) {
    if (attempt > 0 && patc == pat)
      break; /* there was no anchor, no need to try again */

    //...

    /*
     * round == 1: Count the matches.
     * round == 2: Build the array to keep the matches.
     */
    for (round = 1; round <= 2; ++round) {
      // ...
```

Extracting a function to do the matching according to a parameter would work here.

`git grep "<= 1" | grep for` returns more than 10 results that look like occurrences of this anti-pattern.

**Comment by justinmk** [comment]
Any sensible refactor is welcome as long as it includes good test coverage. But addressing this particular anti-pattern en masse is a low priority, so let's close this issue.
