### ISSUE TITLE
Disable QuickFixLine highlighting

### ISSUE THREAD

**Issue by yefim** [neovim/neovim#5722]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? No, vim behaves the same.
- Operating system/version: macOS 10.12.1
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour

Quickfix window has the first (current) line highlighted.

### Expected behaviour

Allow the user to disable the highlighting.

### Steps to reproduce using `nvim -u NORC`

* Open quickfix window
* See first line is highlighted
* Wish there was a way to disable it

I've attached a screenshot where I've styled the quickfix highlight to be as unobtrusive as possible but I really wish there was a way to disable the highlight or make it transparent or something so that all the quickfix rows match :)

![screenshot 2016-12-06 13 29 07](https://cloud.githubusercontent.com/assets/1170843/20944795/9fb11dac-bbb9-11e6-9cbf-15f4c37ad0b3.png)

**Comment by justinmk** [comment]
To disable the visual effect of a highlight, link it to the "Normal" group:

    :highlight! link QuickFixLine Normal

**Comment by yefim** [comment]
@justinmk looks like this no longer works in version 0.2.2.

**Comment by strboul** [comment]
The solution proposed by @justinmk (with `QuickFixLine`) worked but the first line was still with a different syntax highlighting. For those who come across this issue can try the following:
```vim
highlight QuickFixLine cterm=bold ctermfg=none ctermbg=none
```
