### ISSUE TITLE
Autocmd for remote plugin on VimEnter is slow

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#5728]
- `nvim --version`: NVIM v0.2.0-44-g8089292 Build type: Release
- Vim (version: ) behaves differently? No
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Actual behaviour

Autocmd registered from remote plugin could cost ~150ms on startup, even with `sync=False` flag. 

### Expected behaviour

I thought is should be no more than 10ms when using `rpcnotify`

### Steps to reproduce using `nvim -u NORC`

Create a simple remote plugin in `rplugin/python3/my.py`
```
    import neovim

    @neovim.plugin
    class Limit(object):
        def __init__(self, vim):
            self.vim = vim

       @neovim.autocmd('VimEnter', pattern='*', sync=False)
        def on_enter(self):
            return

```

Add this plugin to runtimepath 

Run `:UpdateRemotePlugin`

use command:
```
nvim --startuptime tmp.txt
```

The time used by `VimEnter autocommands` would be increased more than 150ms.

I tried with `sync=True`, and it even worse.

Since I just want to start a server on VimEnter, I changed the code to use jobstart and normal VimEnter autocmd, the time of `VimEnter autocommands` increased no more than 10ms

**Comment by mhinz** [comment]
See `:h g:python_host_check` and the following options, especially the `skip_check`.

**Comment by justinmk** [comment]
Why does `g:python_host_skip_check` exist? What happens if user has `g:python_host_skip_check=1` but it's a lie?

**Comment by mhinz** [comment]
It prevents shelling out to `python -c 'import sys; print(sys.version_info[0])` (_simplified_) and always assumes "the Python installation is working".

If neither `g:python_host_prog` and `g:python_host_skip_check` are set, there could be multiple calls to `exepath()` and `system()`.

`provider#pythonx#Detect()` could need some love, though.

**Comment by chemzqm** [comment]
@mhinz I have these lines in my vimrc:
```
let g:python_host_skip_check=1
let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_skip_check=1
let g:python3_host_prog = '/usr/local/bin/python3'
```
But it doesn't help too much:

* Without autocmd of VimEnter

        181.817  064.025: VimEnter autocommands

* With  VimEnter autocmd and python host skip check

        341.260  229.980: VimEnter autocommands

* With  VimEnter autocmd and **without** python host skip check

        322.555  210.953: VimEnter autocommands

   even a litte faster 😕  

* With  VimEnter autocmd and **without** python host skip check and using `sync=True`

        331.298  220.584: VimEnter autocommands

seems nothing different, but could be much slower when more code inside python handler.

**Comment by mhinz** [comment]
Maybe that's just the time starting a Python process costs in general? Maybe there are ways to improve the startup performance in [python-client](https://github.com/neovim/python-client), but apart from that I don't see how to improve this further.

That happens only once, though. You can check that after starting nvim, there will be a Python child process that acts as the host.

Maybe there's a better way to achieve what you're trying to do?

**Comment by chemzqm** [comment]
@mhinz I've tried to add VimEnter autocmd to more plugins , the startup time didn't make any noticeable difference, so I think you're right.

**Comment by justinmk** [comment]
What good is g:python_host_skip_check doing then? Would be nice to remove that option if possible.

**Comment by mhinz** [comment]
Since "having a working installation" is specific to the system anyway, we could probably drop it in favor of just having `g:python_host_prog`.

I could refactor `runtime/autoload/provider/pythonx.vim`, if you want.

CC @bfredl

**Comment by chemzqm** [comment]
@mhinz https://gist.github.com/chemzqm/faa1f6bac2eddc3c15026c1109a8e69f

**Comment by justinmk** [comment]
@mhinz 👍

**Comment by bfredl** [comment]
At least `g:python3_host_skip_check` should be implied by `g:python3_host_prog` (if the user specifies an executable, it should be trusted), but I won't mind if it was completely removed.

**Comment by justinmk** [comment]
@bfredl That's what I was thinking too. `g:python3_host_prog` can serve the purpose of `g:python3_host_skip_check` (if any). And `g:python3_host_skip_check` and be removed from the docs and silently ignored.

**Comment by chemzqm** [comment]
@mhinz It only need `1ms` to start process, but it cost more than `150ms` to check if the process is running ok in `https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L35`

I've profiled with:

``` viml
  let start = reltime()
  try
    let channel_id = jobstart(args, s:job_opts)
    echo reltimestr(reltime(start))
    if rpcrequest(channel_id, 'poll') ==# 'ok'
      echo reltimestr(reltime(start))
      return channel_id
    endif
```

**Comment by Shougo** [comment]
> @mhinz It only need 1ms to start process, but it cost more than 150ms to check if the process is running ok in https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L35

Yes, it is the same overhead for me.

**Comment by Shougo** [comment]
I have tested my.py VimEnter.

```
087.841  076.407: VimEnter autocommands
```

It is 76ms in master.
Unfortunately, #5856 does not work.  So I cannot test the optimization.

**Comment by chemzqm** [comment]
I was AFK for some time, will look into this issue again later

**Comment by Shougo** [comment]
#5856 does not fix the problem.
I think the wait is needed for VimEnter.

**Comment by bfredl** [comment]
#6743/#6742 will fix the problem.

**Comment by Shougo** [comment]
> #6743/#6742 will fix the problem.

Why it fixes the problem?
The remote plugins are loaded immediately?

**Comment by bfredl** [comment]
No, it simply enables to do the host initialization in a completely async fashion. So `autocmd("VimEnter", sync=False)` will check if the host is ready, if not, it will be delayed until `ChannelInfo` event. Of course `sync=True` will still be slow.

Moreover we should enable the same for legacy script hosts but it will require plugin/user intervention (made up names, probably hasn't dedicated autocmd):
```
if has("nvim")
  RequireHost python-legacy
  autocmd HostLoaded python-legacy call CodeUsingPython()
else
  call CodeUsingPython()
end

func CodeUsingPython()
  py import whatever
  ...
endfunc
```
or maybe even
```
  HostAsync python-legacy call CodeUsingPython()
```

**Comment by Shougo** [comment]
Ah, OK.  It seems better.

When #6743 #6742 is merged?

#5856 is not needed?

**Comment by bfredl** [comment]
#6742 will take some time, #5856 can be merged in the meanwhile if it is noticeable improvement.

**Comment by Shougo** [comment]
OK.  I think #5856 improves the performance.

**Comment by StillStealSteel** [comment]
@chemzqm Will test it lately. Thank you. 
If it works is there any chance that this would be added in the master? 
Yes i understand that startup errors for majority of users is more important, but maybe as an option that turn off by default?

**Comment by StillStealSteel** [comment]
@chemzqm Thank you. It works like a charm.

**Comment by Shougo** [comment]
> Nothing can be done on deoplete side? As i understand it's python provider that is slow, right?

It is not related to deoplete.
deoplete already implements async initialization and deoplete does not use VimEnter autocmd.

**Comment by ysmolsky** [comment]
It looks like this issue was never fixed. My setup yields this:
```
129.574  060.340: opening buffers
129.597  000.024: BufEnter autocommands
129.600  000.003: editing files in windows
130.665  000.909  000.909: sourcing /Users/thorn/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
130.985  000.029  000.029: sourcing /opt/local/share/nvim/runtime/autoload/provider.vim
304.827  174.288: VimEnter autocommands
304.836  000.009: UIEnter autocommands
304.839  000.003: before starting main loop
305.762  000.211  000.211: sourcing /Users/thorn/.vim/bundle/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
```

I have read the whole thread, but I do not see clear path to resolution. I have tried the path from @ chemzqm, but it does not reduce the time for `VimEnter autocommands`

What next steps could be taken to fix this problem?

**Comment by justinmk** [comment]
Covered by : 

- https://github.com/neovim/neovim/issues/4439
- https://github.com/neovim/neovim/issues/5532
