### ISSUE TITLE
Some gui highlights are missing

### ISSUE THREAD

**Issue by Uroc327** [neovim/neovim#5730]
- `nvim --version`:
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -pipe -march=native -fomit-frame-pointer -O3 -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fstack-protector-strong -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/config -I/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/src/nvim/auto -I/tmp/portage/app-editors/neovim-0.1.7/work/neovim-0.1.7_build/include
Compiled by portage@Horus

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0) does behave differently
- Operating system/version: Gentoo Linux ~amd64
- Terminal name/version: URxvt 9.22
- `$TERM`: rxvt-uincode-256color

### Actual behaviour

When `highlight`ing some groups, the `guifg`/`guibg` arguments are not respected.

### Expected behaviour

Respect the colors I specify.

### Steps to reproduce

This was not reproducable for me using `nvim -u NORC` instead I head to use the following setup

```
> cat init_bug.vim
hi Normal                                          guifg=#F8F8F8 guibg=#1B1B1B
hi Type                     ctermfg=2              guifg=#8EB33B
hi Statement                ctermfg=130            guifg=#AF5F00
hi Comment                  ctermfg=4              guifg=#72B3CC
hi Constant                 ctermfg=1              guifg=#C75646
hi Special                  ctermfg=9              guifg=#E09690
hi PreProc                  ctermfg=5              guifg=#C8A0D1
hi Visual      term=reverse             ctermbg=8                guibg=#5D5D5D
hi Search      term=reverse ctermfg=0   ctermbg=3  guifg=#000000 guibg=#D0B03C
hi SearchBlink term=reverse ctermfg=0   ctermbg=13 guifg=#000000 guibg=#FBB1F9
hi NonText                  ctermfg=6              guifg=#218693
hi SpecialKey               ctermfg=6              guifg=#218693
hi DiffAdd                  ctermfg=10  ctermbg=2  guifg=#1B1B1B guibg=#8EB33B
hi DiffChange               ctermfg=13  ctermbg=5  guifg=#1B1B1B guibg=#C8A0D1
hi DiffDelete                                      guifg=#1B1B1B guibg=#C75646
hi DiffText                                        guifg=#1B1B1B guibg=#218693

nvim -u init_bug.vim
:hi <group-name>
```

The following `<group-name>`s did not work for me (including the effective colors):
- `Type           xxx ctermfg=2 gui=bold guifg=SeaGreen`
- `Statement      xxx ctermfg=130 gui=bold guifg=Brown`
- `Comment        xxx ctermfg=4 guifg=Blue`
- `Constant       xxx ctermfg=1 guifg=Magenta`
- `Special        xxx ctermfg=5 guifg=SlateBlue`
- `PreProc        xxx ctermfg=5 guifg=Purple`

The other highlight groups seemed to have the correct gui colors.

**Comment by justinmk** [comment]
> The following `<group-name>`s did not work for me

How is that related to the color names? The effect of groups depends on your filetype and syntax definition.

Are you comparing gVim or terminal Vim? Did you `set termguicolors` in your init.vim?

**Comment by Uroc327** [comment]
I don't know the relation.
Probably I did not make my actual point clear enough. When you type `:hi Statement` in nvim, you get the String `Statement xxx ctermfg=130 gui=bold guifg=Brown` returned, altough in the rc file `Statement` should have highlight `hi Statement ctermfg=130 guifg=#AF5F00`.
The same is true for the mentioned other groups. The groups I have not mentioned but have `hi`s for, work perfectly fine.

It does not matter which Vim I compare, as I do not look at the colors printed on the screen. I only look at the output of `:highlight`.

I do not have set `termguicolors`.

**Comment by justinmk** [comment]
Oh. That's because nvim enables syntax and filetype detection by default. If you add these lines to the end of `init_bug.vim`, you'll see the same behavior in Vim:

    filetype plugin indent on
    syntax on

If you don't like this default Nvim behavior, just disable it in your init.vim or via `--cmd`, or `-c`. For example, if you add these lines to the `top` of `init_bug.vim`, you'll find that `nvim -u init_bug.vim` behaves as you expect.

    filetype off
    syntax off

**Comment by Uroc327** [comment]
The Vim setup I'm comparing to has

    filetype plugin indent on
    syntax on

and that's excatly the behavior I want and excpect. But it is not the behavior I get. Instead a `hi Statement ctermfg=130 guifg=#AF5F00` in my `init_bug.vim` results in

    :hi Statement                                                                                                                                                                                                                                                                                                      
    Statement      xxx ctermfg=130 gui=bold guifg=Brown
    Press ENTER or type command to continue

**Comment by justinmk** [comment]
> The Vim setup I'm comparing to has

Are those commands before or after your `:hi` commands? This is important.

> Instead a `hi Statement ctermfg=130 guifg=#AF5F00` in my init_bug.vim results in

You get that in which editor, after doing what?

**Comment by Uroc327** [comment]
They are before of course.

The behaviour I described in the last sentence of my previous post is the one I get in neovim.
Executing `:hi Statement` in Vim, I get the following

    :hi Statement
    Statement      xxx term=bold ctermfg=130 gui=bold guifg=#AF5F00
    Press ENTER or type command to continue

The `guifg` field contains different values in Vim and Nvim.

**Comment by justinmk** [comment]
If I add these lines to the top of `init_bug.vim`

```
filetype plugin indent on
syntax on
```

And then do this:

```
:hi Statement
Statement      xxx ctermfg=130 gui=bold guifg=#AF5F00
````

You can see that the result is the same (except for the lack of `term` field, which doesn't exist in Nvim)

**Comment by Uroc327** [comment]
I thought, 

    filetype plugin indent on
    syntax on

Is the default in nvim. Why do I have to explicitly state it in my init file?

**Comment by justinmk** [comment]
It is the default. It is applied immediately after your init.vim is evaluated (documented at `:help startup`).

> Why do I have to explicitly state it in my init file?

`:filetype` and `:syntax on` execute scripts. Those scripts override the results of your `:highlight` commands. If you want to call `:highlight` in your startup then you need to explicitly tell nvim to run `:filetype` and `:syntax` _before_ you call `:highlight`. Nvim will see that you called `:filetype` and/or `:syntax` and won't try to re-run them.

This normally isn't a problem because colorschemes clear all highlights anyway, so you really should do any `:highlight` commands by handling `autocmd ColorScheme` as mentioned above.
