### ISSUE TITLE
Is there a way to rebind command + c to yank text on macOS?

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#5731]
- `nvim --version`: 0.1.7
- Operating system/version: macOS ver. 10.11.6
- Terminal name/version: iTerm : 3.0.12
### Actual behaviour
You visually select some text and press cmd + c. Nothing happens. 

### Expected behaviour
You visually select some text and press cmd + c. Text is copied into your clipboard buffer like what 'y' yank command does.

### Problem
Essentially I am asking for a way to turn on meta key support in neovim. I really need to rebind command + c to actually copy text the same way 'y' command does.

Thank you.

**Comment by jamessan** [comment]
According to `:help key-notation`, `<D-...>` is the format for mapping the command key.  Something like `vnoremap <D-c> y` should do what you want.

That being said, this is really something that should asked on community sites like vi.stackexchange.com or in our IRC/gitter channel.  It's not a bug.

**Comment by nikitavoloboev** [comment]
I tried using `vnoremap <D-c> y` and that didn't work.

**Comment by justinmk** [comment]
This cannot work in the terminal except at the iTerm2 level. You can configure iTerm2 to send a random sequence of bytes for certain cmd-foo chords, and then 

    nnoremap <random bytes> ...

However, we have support for this in any GUI that sends `<D-...>` chords. I believe neovim-qt and NyaoVim and some others do so. Maybe try https://github.com/qvacua/vimr
