### ISSUE TITLE
Question about TextYankPost event

### ISSUE THREAD

**Issue by machakann** [neovim/neovim#5735]
- `nvim --version`: 0.1.7
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode/9.22
- `$TERM`: rxvt-unicode-256color

### Expected behaviour
I just want to ask that:

* TextYankPost event is triggered also in scripting
* TextYankPost event  interrupts  scripting (like InsertCharPre)

Are the above two expected behaviors ?

### Steps to reproduce using `nvim -u NORC`

```vim
function! ShowCursorWord() abort
  normal! yiw
  execute printf("echomsg '%s'", @@)
endfunction

autocmd TextYankPost * echomsg 'TextYankPost'

call setline(1, 'foo')
normal! 1G
call ShowCursorWord() 
" 'TextYankPost' first
" 'foo' later
```

**Comment by justinmk** [comment]
> TextYankPost event is triggered also in scripting

Yes, this is expected. It would be easy to avoid this if we wanted to (just check `current_SID == 0`), but I don't think it would make sense. In general, plugins should not be changing with the user's registers--unless that's the purpose of the plugin, in which case, the TextYankPost event _should_ apply.

> TextYankPost event interrupts scripting (like InsertCharPre)

Can you clarify what you mean by "interrupts"? Does it prevent or break the InsertCharPre event?

**Comment by justinmk** [comment]
> " 'TextYankPost' first
> " 'foo' later

The sample script you gave is not sufficient to conclude that. Vim and Neovim processes a redraw (`:echomsg`) in "batches", so comparing the behavior of `setline()` doesn't tell us anything.

Try this script instead: 

```vim
let @a=''
function! ShowCursorWord() abort
  normal! yiw
  let @a.="ShowCursorWord\n"
endfunction

autocmd TextYankPost * let @a.="TextYankPost\n"

let @a.="foo\n"
call ShowCursorWord()
```

After `:source`ing that script, `:echo @a` shows:

```
foo
TextYankPost
ShowCursorWord
```

which is the order of events I would expect.

**Comment by machakann** [comment]
What I mention as 'interrupt' is that, for instance, TextChanged event does not interrupts scripting. It is delayed to trigger.

```vim
let @a=''
function! ShowCursorWord() abort
  normal! ifoo
  normal! diw
  let @a.="ShowCursorWord\n"
endfunction

autocmd TextChanged * let @a.="TextChanged\n"

let @a.="foo\n"
call ShowCursorWord()
```

`:source` and `:echo @a` to show 'TextChanged' later than 'ShowCursorWord':

```
foo
ShowCursorWord
TextChanged
```

However, actually, what I really wanted to ask has been already replied. 

My script needs TextYankPost but I was afraid that someone complain me about unintended triggering in another plugin. (Though we could solve it to get rid of `:normal` command or just use `:noautocmd` command)  Now I am relieved to hear that. Everything is clear now. Thank you!
