### ISSUE TITLE
:terminal : derive cursor style from host terminal

### ISSUE THREAD

**Issue by alex-ac** [neovim/neovim#5740]
- `nvim --version`:
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161129-35198-kf4eqg/neovim-0.1.7/build/config -I/tmp/neovim-20161129-35198-kf4eqg/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20161129-35198-kf4eqg/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161129-35198-kf4eqg/neovim-0.1.7/build/include
Compiled by alex-ac@95.108.174.208-red.dhcp.yndx.net

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```
- Operating system/version: MacOS 10.12.1
- Terminal name/version: iTerm 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour
`:terminal` uses block cursor instead of default terminal cursor:
<img width="315" alt="screen shot 2016-12-09 at 11 45 51" src="https://cloud.githubusercontent.com/assets/986723/21042834/15809bfa-be05-11e6-8b17-dcd950e9e636.png">

### Expected behaviour
I expected to see cursor set in the iterm settings.
<img width="360" alt="screen shot 2016-12-09 at 11 48 37" src="https://cloud.githubusercontent.com/assets/986723/21042909/74047be2-be05-11e6-8672-92f287876b4c.png">

I found several settings for `:terminal` cursor (`hl TermCursor` & `hl TermCursorNC`) but there is no way to use underline as a cursor.

### Steps to reproduce using `nvim -u NORC`

```
# Set underline cursor in the terminal settings
nvim -u NORC
:terminal<cr>
```

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/5556 is a step towards detecting tty cursor settings. But we should restore the `'guicursor'` option have it be respected by the TUI as well as `:terminal`.

**Comment by justinmk** [comment]
> but there is no way to use underline as a cursor.

Nvim supports `guicursor` in the terminal.

Any more sophisticated feature-detection is covered by https://github.com/neovim/neovim/issues/7490
