### ISSUE TITLE
CheckHealth more specific with sensible.vim search

### ISSUE THREAD

**Issue by msoucy** [neovim/neovim#5751]
- `nvim --version`: v0.2.0-78-g5082af4
- Vim (version: ) behaves differently? Does not exist in vim
- Operating system/version: Fedora 25
- Terminal name/version: urxvt256c
- `$TERM`: `rxvt-unicode-256color`

### Actual behaviour

`:CheckHealth` will give an error message, despite sensible.vim not being loaded

### Expected behaviour

`:CheckHealth` is silent or gives `INFO` instead

### Steps to Reproduce:

* Install [vim-plug](http://github.com/junegunn/vim-plug)
* Use the [conditional activation instructions(https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation):

```vim
function! Cond(cond, ...)
    " Conditionally enable plugins for vim-plug
    let opts = get(a:000, 0, {})
    return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

Plug 'tpope/vim-sensible', Cond(!has('nvim'))
```

* Run `:CheckHealth`

### Steps to reproduce using `nvim -u NORC`

```sh
git clone https://github.com/tpope/vim-sensible ~/nvimtmp/plugged/vim-sensible
nvim -u NORC
```
```vim
:set rtp+=~/nvimtmp
:CheckHealth
```

### Possible fix

Possibly test using `get(g:, 'loaded_sensible', 0)` instead

**Comment by brcolow** [comment]
Sounds right. Any chance of a PR?

**Comment by justinmk** [comment]
Good idea, thanks.
