### ISSUE TITLE
C-@ skipping words (C-Space doesn't)

### ISSUE THREAD

**Issue by wesbland** [neovim/neovim#5762]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? Yes (version: 7.4)
- Operating system/version: CentOS Linux release 7.2.1511
- Terminal name/version: GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
- `$TERM`: screen-256color

### Actual behaviour

On Linux (or at least, when sshing from MacOS to Linux with iterm2+tmux), when typing CTRL+space, my cursor skips to the beginning of the next word (as if I had pressed `w` in normal mode). When in nvim (same version) on my local machine (MacOS 10.12), the cursor doesn't move.

### Expected behaviour

I expect the cursor to not move on any system by default (because the combination should be unmapped). It is used commonly by cscope plugs to map to open a tag in a new split (or vertical split). 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

In Linux, open a buffer with words, type `CTRL+space`.

```

### Notes

Based on a bit of research, it seems that the issue is a combination of nvim+iterm2 (and possibly tmux).

When I do this:

```
nmap <unique> <C-Space><C-Space>s :vert scs find s <C-R>=expand("<cword>")<CR><CR>
```

I get the expected result, but when I do this:

```
nmap <unique> <C-@><C-@>s :vert scs find s <C-R>=expand("<cword>")<CR><CR>
```

I get character jumping. I confirmed that this doesn't happen when I use the built in Terminal.app without tmux. I haven't tried all combinations of the three.

**Comment by justinmk** [comment]
https://github.com/neovim/libtermkey/commit/416adba8c000bd2a70efc881283249d03a56553b may affect this. That change will be pulled in by https://github.com/neovim/neovim/pull/5758

**Comment by justinmk** [comment]
> When I do `nmap <unique> <C-Space> ...` I get the expected result,

`<c-space>` is the way to map ctrl-space. Other forms are accidental, and not supported.
