### ISSUE TITLE
Windows: system clipboard (register * and +)

### ISSUE THREAD

**Issue by konofeev** [neovim/neovim#5766]
Sorry for my bad english.

Undisclosed nvim parameters and systems, because I want to ask a general question.

The documentation states:

> Clipboard access is implicitly enabled if any of the following clipboard tools
> are found in your `$PATH`.
>   - xclip
>   - xsel (newer alternative to xclip)
>   - pbcopy/pbpaste (Mac OS X)
>   - lemonade (for SSH)
>   - doitclient (for SSH)

Do I understand that these utilities are designed for * unix and MacOS?
If so, what solutions there are for OS Windows 7?
If Windows 7 operating system clipboard should work by default, then point out the error details, and has faced.

Thank you for your help and support.

**Comment by brcolow** [comment]
Neovim on Windows is shipped with the [win32yank](https://github.com/equalsraf/win32yank) binary which works as a clipboard tool.

**Comment by konofeev** [comment]
Thank you very match.

**Comment by equalsraf** [comment]
The should be fixed in master, with the addition of win32yank.exe to the Neovim install.
