### ISSUE TITLE
Commit 0f681c8 breaks deoplete

### ISSUE THREAD

**Issue by rschmitt** [neovim/neovim#5767]
- `nvim --version`: NVIM v0.2.0-134-g988ab580
- Vim (version: ) behaves differently? This is a regression within neovim
- Operating system/version: macOS Sierra 10.12.1
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour

When [deoplete](https://github.com/Shougo/deoplete.nvim) is enabled, merely typing into a buffer in insert mode causes the following error message with every keystroke:

`Using <SID> not in a script context: s:completion_delayed`

In addition to deoplete, [heatseeker integration](https://github.com/rschmitt/heatseeker) has also been broken by this commit; trying to open a selected file or file results in a `Too many arguments for function` error.

### Expected behaviour

These errors should not occur.

### Steps to reproduce using `nvim -u NORC`

Assuming [NeoBundle](https://github.com/Shougo/neobundle.vim) is installed in the usual fashion:

```
nvim -u NORC
:set runtimepath+=~/.vim/bundle/neobundle.vim/
:call neobundle#begin(expand('~/.vim/bundle/'))
:NeoBundle 'Shougo/deoplete.nvim'
:call neobundle#end()
:call deoplete#enable()
itest # enter insert mode and type anything
```

**Comment by rschmitt** [comment]
Crap. #5765 actually *does* fix this bug, but *not* the Heatseeker integration issue. I'll try to write up a new bug report for that separate issue.

**Comment by Shougo** [comment]
OK.  I should fix the problem.
Please create the issue in deoplete.
