### ISSUE TITLE
b.options['filetype'] returns object of type different from Vim

### ISSUE THREAD

**Issue by equal-l2** [neovim/neovim#5768]
- `nvim --version`: `NVIM v0.2.0-134-g988ab58`
- Vim (version: `8.0.0130` ) behaves differently? yes
- Operating system/version: macOS 10.12.1
- Terminal name/version: `iTerm2 3.0.12`
- `$TERM`: `xterm-256color`

### Actual behaviour
NVim shows
`['']`
(returns `str`)
### Expected behaviour
Vim shows
`[b'']`
(returns `bytes`)
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:python3 import vim
:python3 print([b.options['filetype'] for b in vim.buffers])
```

Is the difference intended?

**Comment by justinmk** [comment]
Vim is returning a byte array, with an unknown encoding. Neovim returns an actual UTF8-encoded string. This is a feature.

**Comment by ZyX-I** [comment]
Vim is returning this because it is what Vim has. There are no strictly UTF-8-encoded strings in some string options, e.g.

    let &commentstring = "\xFF%s"

is a valid assignment, regardless of what &encoding value is. Some options do not allow some characters, but most of time string options are either “[array of] enum” option or options which may contain any bytes at least in some position.

Specifically

    let &commentstring = "\xFF%s"
    py3 import vim
    py3 print(vim.current.buffer.options['commentstring'])

is UnicodeDecodeError:

```
Error detected while processing function provider#python3#Call:
line   18:
UnicodeDecodeError('utf-8', b'\xff%s', 0, 1, 'invalid start byte')
Traceback (most recent call last):
  File "/home/zyx/.local/lib64/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 185, in handler
    rv = self._request_cb(name, args)
  File "/home/zyx/.local/lib64/python3.4/site-packages/neovim/api/nvim.py", line 151, in filter_request_cb
    result = request_cb(self._from_nvim(name), args)
  File "/home/zyx/.local/lib64/python3.4/site-packages/neovim/plugin/host.py", line 74, in _on_request
    rv = handler(*args)
  File "/home/zyx/.local/lib64/python3.4/site-packages/neovim/plugin/host.py", line 160, in decoder
    return fn(*walk(decode_if_bytes, args, decode))
  File "/home/zyx/.local/lib64/python3.4/site-packages/neovim/plugin/script_host.py", line 75, in python_execute
    exec(script, self.module.__dict__)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by justinmk** [comment]
In https://github.com/neovim/python-client/issues/41 wasn't it decided to return `str`?

**Comment by ZyX-I** [comment]
@justinmk It returns `str` on both Python versions in *old* API, which also results in UnicodeDecodeError’s raised by seemingly innocent constructs. In API added by me it returns `bytes` on both versions (in Python-2 `str is bytes`), this is easier to handle when writing Python-23 code then `str (2) + str (3)` or `unicode (2) + str (3)` since Python-2 does not have `surrogateescape` error handler.

**Comment by ZyX-I** [comment]
Specifically `vim.eval` is old API. `vim.Buffer.__getitem__` (indexing) is also old (except that `vim.Buffer` class existed but was not explicitly exported before one of my patches). `vim.bindeval`, `vim.**.options`, `vim.**vars` is new.

**Comment by ZyX-I** [comment]
Somewhat like a full list of pros and cons like I see them:

- Any string which you may find in \*Vim could be represented.
- Consistent across Python versions: `bytes` in both versions.
- On Python-3 it would be harder for plugin authors to forget about the fact that they do not live in a happy unicode world, thus missing weird bugs (result of using `surrogateescape` error handler is not accepted everywhere).
- Absence of conversion makes code a bit faster (for Vim and for authors which can stay with `bytes`: explicit `bytes.decode` in Python code will be a bit slower then doing the same thing in pure C, can’t say what’s with `neovim` module).

Cons:

- Text is not expected to be `bytes` in Python-3, code will be less idiomatic. In some places `bytes` object could not be used.
- Plugin authors needs to deal with decoding on his own. In Neovim now it is enough to decode from `utf-8`, but Vim users need to remember that they may face different `&encoding`s.
