### ISSUE TITLE
<C-]> or K doesn't jump to another section in man when : is mapped to other key

### ISSUE THREAD

**Issue by Frefreak** [neovim/neovim#5776]
- `nvim --version`: v0.2.0-137-g5855f30 and 0.1.7
- Vim (version: ) behaves differently? yes. In vim 8.0.86, **C-]** not works but **K** works (no mapping).
- Operating system/version: Arch Linux
- Terminal name/version: Konsole 16.08.3
- `$TERM`: xterm-256color

### Actual behaviour
when pressing **K** or **<C-]>** in man with cursor under a section name, e.g. (`termio(7)` in the **SEE ALSO** subsection of `echo(3)`), nvim doesn't jump to that section. No error or sometimes E21.
### Expected behaviour
nvim jumps to that section.
### Steps to reproduce using `nvim -u NORC`

```
man 3 echo | nvim - -u NORC -c 'set ft=man' -c 'nnoremap ; :' -c 'nnoremap : ;'
# then Gkk and the cursor is on certain section name, pressing K or c-] does not work
```
In **[runtime/ftplugin/man.vim](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/man.vim#L34-L35)** `nmap` is used to map those 2 keys, change to `nnoremap` and they function correctly. Seems like the noremap version is more appropriate here?

**Comment by jamessan** [comment]
Cc @nhooyr

**Comment by mhinz** [comment]
> Seems like the noremap version is more appropriate here?

Yup, that's clearly a bug. It used to be a `<plug>` mapping once, hence the `nmap`.
