### ISSUE TITLE
Debian package missing? (Lubuntu 16.04.1 LTS)

### ISSUE THREAD

**Issue by entangledloops** [neovim/neovim#5778]
### Actual behaviour

$ sudo apt-get install neovim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package neovim

### Expected behaviour

Installs.

### Additional Info

My system is up-to-date.

os:
	LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
	Distributor ID:	Ubuntu
	Description:	Ubuntu 16.04.1 LTS
	Release:	16.04
	Codename:	xenial

**Comment by mhinz** [comment]
According to [this](http://packages.ubuntu.com/search?keywords=neovim&searchon=names&suite=all&section=all), it's only in zesty.

**Comment by jamessan** [comment]
Either way, there's nothing that can be done about which distributions carry neovim by the neovim team.  That's up to the individual distributions and their maintainers.

**Comment by entangledloops** [comment]
@jamessan Okay, got it. Thanks for the prompt response.
