### ISSUE TITLE
Visual block paste behaves differently depending on direction cursor selected it

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#5781]
- `nvim --version`:
0.1.7
- Vim (version: ) behaves differently?
8.0 No, same problem
- Operating system/version:
Arch linux
- Terminal name/version:
XTerm(327)
- `$TERM`:
xterm-256color

### Actual behaviour
With the test file
`test.txt`
```
Line of text 1
Line of text 2
```

Open the file with `nvim -u NONE`
Visually select the two words `Line` at the start of each line with visual block mode.
`G0<C-v>ke`
Paste something (e.g. filename)
`"%p`

The file is now
```
test.txt of text 1
 of text 2
```

### Expected behaviour
The file should contain
```
test.txt of text 1
test.txt of text 2
```

### Extra information
If the visual block is selected by starting at the top of the range and moving down, then we see the expected behaviour.
i.e. `gg0<C-v>je"%p` gives the expected behaviour.

### Explanation
This is because when the selection has been created from moving backwards in the file, then `curbuf->b_visual` has its end position after its start position, and the blockwise visual put code doesn't account for this.

The code below appears to fix this, but I'm going to look for a better solution.

```diff
diff --git a/src/nvim/ops.c b/src/nvim/ops.c
index b1fea32..0a47eb6 100644
--- a/src/nvim/ops.c
+++ b/src/nvim/ops.c
@@ -3036,7 +3036,9 @@ void do_put(int regname, yankreg_T *reg, int dir, long count, int flags)
         }
         if (VIsual_active)
           lnum++;
-      } while (VIsual_active && lnum <= curbuf->b_visual.vi_end.lnum);
+      } while (VIsual_active &&
+              (lnum <= curbuf->b_visual.vi_end.lnum ||
+               lnum <= curbuf->b_visual.vi_start.lnum));
 
       if (VIsual_active) {  /* reset lnum to the last visual line */
         lnum--;
```

### Related, not sure whether bug or not
In the same function, there is a comment that makes it seem like the current behaviour is a bug when pasting a linewise register over a blockwise selection.
```
      /* Must be "p" for a Visual block, put lines below the block. */
      curwin->w_cursor = curbuf->b_visual.vi_end;
```
I read this to mean that the line should always be put at the end, but if the selection was made by moving the cursor backwards in the file, then the register is put just after the first visually selected line.

**Comment by justinmk** [comment]
cc @chrisbra

**Comment by chrisbra** [comment]
thanks. Saw that already and wanted to check it, but haven't had much time lately.

**Comment by justinmk** [comment]
@hardenedapple Does https://github.com/vim/vim/commit/9957a10d0f0c34d8083af6ed66e198e4796038e0 allowed https://github.com/neovim/neovim/issues/5782 to be simplified?

**Comment by hardenedapple** [comment]
Not really, I fixed that part with [these lines](https://github.com/neovim/neovim/blob/043d8ba422b4f35d82e8acef8438248de94ab167/src/nvim/ops.c#L3086-L3088)
