### ISSUE TITLE
--noplugin is counteracted by "set all&"

### ISSUE THREAD

**Issue by kurkale6ka** [neovim/neovim#5783]
- `nvim --version`: NVIM v0.2.0-149-gaa4ef89
- Vim (version: ) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: sakura version is 3.3.4-2
- `$TERM`: xterm-256color

### Actual behaviour
using `nvim --noplugin` has no effect because of `:set all&` at the beggining of my vimrc

### Expected behaviour
No plugins should be loaded

### Workaround
```
if ! &loadplugins
   set all& noloadplugins
else
   set all&
endif
```

### Solution
`:set all&` shouldn't set `loadplugins` when `nvim --noplugin` has been used

**Comment by tweekmonster** [comment]
If you're doing this because you want to source your vimrc at runtime, you should probably be using:

```vim
if !has('vim_starting')
  set all&
endif
```

`--noplugin` should be respected when starting nvim.  Plugins will still be loaded if you source the vimrc at runtime.  I think this behavior is correct and doesn't need to be fixed.

**Comment by kurkale6ka** [comment]
Hi,

> you want to source your vimrc at runtime

Can you explain please. Not sure I fully understand what you are saying.

I use `set all&` in my vimrc at the very top because I want to make sure all options I don't explicitly set get a default value and not something imposed by `/etc/vimrc` for instance. I still want this if I re-source my vimrc

**Comment by Shougo** [comment]
@kurkale6ka I think you should ask it in vim_dev.

**Comment by justinmk** [comment]
`--noplugin` sets an option. `set all&` sets other options, one of which is `'loadplugins'`. It is pretty silly that `--noplugin` does nothing different than `--cmd 'set noloadplugins'`.

**Comment by kurkale6ka** [comment]
Similarly, `all&` sets `'diff` to off even when starting nvim with `-d` (diff mode)

**Comment by kurkale6ka** [comment]
Also noticed that setting `all&` sets `lines` to 24 even though in `:help :set-&` it's stated that the value wouldn't change

**Comment by justinmk** [comment]
FWIW, `:set all&` is not necessary with Nvim because distros don't usually ship their own quirky defaults, unlike what was done historically with Vim.
