### ISSUE TITLE
system() throws error on `grep -m` commands with large input

### ISSUE THREAD

**Issue by pgdouyon** [neovim/neovim#5791]
- `nvim --version`: 0.1.7 RelWithDebInfo
- Vim (version: ) behaves differently? *Yes, no error*
- Operating system/version: macOS Sierra 10.12.1
- Terminal name/version: iTerm2 3.0.12
- `$TERM`: xterm-256color

### Actual behaviour
Neovim throws:
`E5677: Error writing input to shell-command: EPIPE`

### Expected behaviour
No error

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:call system("grep -m 50 'foobar'", repeat(['foobar'], 5000))
```

My guess is that what's actually happening is that system() is throwing an error because the command returns before Neovim has finished writing to its stdin.  Possibly the stdin's buffer size is smaller than 5000.  An even more trivial example that also fails is: `:call system("true", repeat(['foobar'], 5000))`.

If it helps, I recently upgraded from 0.1.5 to 0.1.7 where this broke so the change in behavior must have happened somewhere in between.

**Comment by justinmk** [comment]
EPIPE is the OS telling us the pipe closed. The difference between 0.1.5 and 0.1.7 is that we now report this error, before we just silently ignored it. Ignoring the error (with a try-catch or `silent!`) should be equivalent to the previous behavior.

To reliably write input to a job, use `jobstart()` and `jobsend()`.

**Comment by pgdouyon** [comment]
Ahh sorry about that, I tried the `try/catch` and when that didn't work opened up this issue.  Don't know why I didn't think to try `silent!` but that seems to fix it.  I'm guessing `try/catch` is evaluated in a sandbox and the result is thrown away if an error is raised.

Would you be okay with adding this kind of edge case to the documentation?  Right now `:h E5677` only mentions reading from backgrounded shell commands rather than foregrounded shell commands who close their input pipe early.  I could send a pull request this weekend or next for it.
