### ISSUE TITLE
Popovers like in Atom

### ISSUE THREAD

**Issue by alexdrupal** [neovim/neovim#5794]
Hello

It it possible to implement popovers like it is done in atom. See attached screenshot
I know there is full Electron GUI option, but I don't want to use it because it will slow nvim.
All I want to is to make popovers a bit prettier. Hope that make sense.
![vim1](https://cloud.githubusercontent.com/assets/38625/21316355/67ce27d8-c611-11e6-80be-5dd08e2aaeb9.png)

**Comment by jamessan** [comment]
That sounds like Vim's [balloon eval] functionality, which was removed in the initial culling of Vim code.  I recall there's an intention to bring it back in some form.

[balloon eval]: http://vimhelp.appspot.com/debugger.txt.html#balloon-eval

**Comment by chemzqm** [comment]
That's GUI stuff, BTW, the balloon eval is quite slow for gvim or MacVim, almost useless and GUI author could make use of remote RPC call, that could be better.

**Comment by Tehnix** [comment]
Related PR https://github.com/neovim/neovim/pull/6619

**Comment by wsdjeg** [comment]
@alexdrupal before the floate windows is implement, I use conceal for this feature, see this gif

![2017-11-30-10-04-40](https://user-images.githubusercontent.com/13142418/33409543-8d953d18-d541-11e7-918f-ecfc8f007005.gif)

This feature is a unmerged PR for SpaceVim: https://github.com/SpaceVim/SpaceVim/pull/1036

maybe vim bug: https://github.com/vim/vim/issues/2388

**Comment by Tehnix** [comment]
@wsdjeg that looks awesome! Any chance this could be made into something more general? E.g. you'd just supply it a message and it will display that message on the line below.

**Comment by wsdjeg** [comment]
I could separate it from SpaceVim as a single plugin, but it only works well after the vim bug shown above is fixed.

**Comment by Tehnix** [comment]
That would be great, if it's not too much of a hassle :) I'd very much like to use it for something like you are doing. Do you know if it has the same issue in Neovim?

**Comment by wsdjeg** [comment]
@Tehnix yeah, this issue also happened in neovim.

**Comment by justinmk** [comment]
closed by #6619. Further enhancements to "popup API" are tracked in https://github.com/neovim/neovim/issues/9663 et al.
