### ISSUE TITLE
gn behaves inconsistently / unlike vim

### ISSUE THREAD

**Issue by pieterkockx** [neovim/neovim#5796]
neovim 0.1.7
vim doesn't have this inconsistency

The inconsistent behavior occurs when searching for one character that appears at least twice on the same line.
When the cursor is after the first matching character and you enter gn the behavior is as if ngnn was entered.

Example:

<buffer contents>
yyyAxxxAxxxA

(put cursor on a y character)
(search for A)
/A
(put cursor on an x character)
gn
*inconsistent behavior*

**Comment by jamessan** [comment]
This might be fixed by merging [v7.4.2100](https://github.com/vim/vim/releases/tag/v7.4.2100).

**Comment by pieterkockx** [comment]
For the record, I encountered this border-case while using these (very convenient) mappings:

vnoremap * "9y:let @/ = "\\V" . escape(@9, '\/')<CR>ngn
vnoremap # "9y:let @/ = "\\V" . escape(@9, '\/')<CR>

**Comment by cedric-sun** [comment]
Just want to mention that Vim 7.4.1689 has this bug too.
