### ISSUE TITLE
xclip/xsel process not terminated when exiting nvim

### ISSUE THREAD

**Issue by mbudde** [neovim/neovim#5799]
- `nvim --version`: 0.1.5ubuntu1+git201612182239+2975+22~ubuntu14.04.1
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu 14.04
- Terminal name/version: Gnome Terminal 3.6.2
- `$TERM`: xterm-256color

### Actual behaviour
Yanking text to the `+` register when using the xclip or xsel clipboard providers, starts an xclip/xsel process. Exiting Neovim does not stop this process.

### Expected behaviour
After exiting Neovim, I would expect the xclip/xsel process to have been terminated.

### Steps to reproduce using `nvim -u NORC`
```console
$ pgrep -la xsel   # no process started
$ nvim -u NORC foo
V"+y
:q
$ pgrep -la xsel
12375 xsel --nodetach -i -b
```
https://asciinema.org/a/a4gq9al2rnmb5rzvbg9mdgzna

**Comment by justinmk** [comment]
0.1.5 is very old. Can you try a newer version?

**Comment by mbudde** [comment]
It's not the 0.1.5 release, it's a nightly snapshot from the [Ubuntu PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) from 2016-12-18.

**Comment by mbudde** [comment]
Please reopen this issue.

**Comment by justinmk** [comment]
The current behavior is intentional, see https://github.com/neovim/neovim/pull/3944

**Comment by bfredl** [comment]
Indeed, this simply how clipboard ownership in X11 works. The xsel process will terminate as soon as some other program takes ownership of the clipboard.

**Comment by mbudde** [comment]
I see. The reason I stumbled into this feature is that the xsel process blocks `logout` in a login-shell from proceeding. I have instead worked around this by killing xsel in `.bash_logout`.
