### ISSUE TITLE
editing a man file opens in readonly mode

### ISSUE THREAD

**Issue by wavded** [neovim/neovim#5806]
- `nvim --version`:
- Vim (version: ) behaves differently? Yes
- Operating system/version: MacOS Seirra
- Terminal name/version: iTerm 3
- `$TERM`:

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161128-5095-1l3mqnf/neovim-0.1.7/build/config -I/tmp/neovim-20161128-5095-1l3mqnf/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161128-5095-1l3mqnf/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161128-5095-1l3mqnf/neovim-0.1.7/build/include
Compiled by wavded@wavded.local

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

### Actual behaviour

```sh
nvim foo.man
```

Opens a new file in readonly mode.

### Expected behaviour

I would expect to be able to edit the file as how it works in vim with a vanilla config.

**Comment by jamessan** [comment]
[This] part of `ftplugin/man.vim` should probably be in `autoload/man.vim`'s `s:read_page` instead, since the filetype isn't _solely_ used for rendered man pages.

**Comment by nhooyr** [comment]
Why do you need to edit a file with the extension `.man`?

**Comment by jamessan** [comment]
> Why do you need to edit a file with the extension .man?

Why does it matter?  If the file isn't being rendered by read_page, why should all of those settings be set instead of letting the user edit the file?

**Comment by nhooyr** [comment]
I'm not against the change, I was just wondering why one would need to edit a file with the extension `.man`.

**Comment by jamessan** [comment]
Because that's the extension the file has. :)

**Comment by wavded** [comment]
@nhooyr authoring man pages?  But also what @jamessan said, seems odd to restrict someone access to a file they own based on its extension.

**Comment by nhooyr** [comment]
@wavded man pages aren't authored with `.man` extensions, they use their sections. that's why I was asking.

I'll cook up a PR later today to fix this.

**Comment by wavded** [comment]
@nhooyr thanks for the explanation and the upcoming fix.

**Comment by jamessan** [comment]
> man pages aren't authored with .man extensions

For what it's worth, there are [~6500 `.man` files][1] in the various source packages that make up Debian, so it's not entirely uncommon. :-)

[1]: https://gist.github.com/jamessan/58bdaf72bc744353ff8828a86df2bc91

**Comment by nhooyr** [comment]
@jamessan are those the rendered pages (vim has these)? If so, they aren't necessary with the plugin. You can just do `:Man ./somepath` to render and open a manpage from a local path. Then you can just use `:e` to re-render every time you change the source.

**Comment by wavded** [comment]
@nhooyr I'm no man expert but a few the tutorials i was playing around with (which led to this issue) had you saving things as `.man` files.  I do see other ones using other naming conventions but whatevs.  Seems like it should be editable nonetheless.

**Comment by jamessan** [comment]
> are those the rendered pages (vim has these)?

No, they aren't.  For example, xscreensaver's man sources for it's hacks all use the `.man` extension ([abstractile.man]).

[abstractile.man]: https://github.com/Zygo/xscreensaver/blob/master2/hacks/abstractile.man

**Comment by nhooyr** [comment]
Alright, thanks for letting me know.
