### ISSUE TITLE
Built-in support for popup tips

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#5808]
Hi, I just noticed that [jedi-vim](https://github.com/davidhalter/jedi-vim) has a fancy magic, with `g:jedi#show_call_signatures` option enabled,

![image](https://cloud.githubusercontent.com/assets/4538941/21413290/1a5f7f34-c831-11e6-8771-f4b66078bac2.png)

I havn't take a deep look into the plugin, yet, but I belive it's not a clean implementation. For example, even if I don't change any text, the change symbol will be on after the signature is shown, and even after the tip is hidden. And this feature has some other wierd issues with neovim.

![image](https://cloud.githubusercontent.com/assets/4538941/21413325/5106b7c8-c831-11e6-84e0-ce39e4cf5951.png)

I think it would be a good choice to have built-in support for this kind of tips. Then it would be easy for other plugins to have the same feature without any magic.

**Comment by justinmk** [comment]
The jedi feature works by editing the actual buffer; you're right that it's a fragile hack. Real support for arbitrary popups is something that many of us want, it's covered by other issues. https://github.com/neovim/neovim/issues/5794
