### ISSUE TITLE
Ubuntu 14.04 apt-get update failed with neovim's ppa

### ISSUE THREAD

**Issue by chenkan1994** [neovim/neovim#5811]
Hello everybody:

I'm currently working on a Ubuntu 14.04 x86 desktop, and I want to install neovim, but after I ran this command:
```shell
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
```
errors occured:
```shell
W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/trusty/main/i18n/Translation-en  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Ubuntu 14.04 is a LTS version, and it should still be supported for now.

Thanks

**Comment by jamessan** [comment]
This isn't a neovim issue.  It's an apt or network problem.  Try updating again.

**Comment by chenkan1994** [comment]
@jamessan I have updated for tens of times... none of them worked. So you guys are not going to solve this problem?

**Comment by fwalch** [comment]
As @jamessan said, this is not a Neovim issue, so there is nothing we can do to fix it. I just updated Neovim  from the PPA on 14.04 without any issues.

**Comment by chenkan1994** [comment]
@fwalch OK, got it. Thanks anyway!

**Comment by arian-granular** [comment]
@jamessan  I'm having the same exact issue as chenkan1994 and it looks like only xenial and devel have packages: http://ppa.launchpad.net/neovim-ppa/stable/ubuntu/dists/

compare to: http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu/dists/

I'm fine with using unstable if it's not worth the time to support 14.04 since it is relatively close to EOL. If that's the case I'll update the wiki install article so other people don't needlessly create issues

**Comment by kuzyo** [comment]
Having such errors on 14.04:
```
W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/neovim-ppa/stable/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

```
Do I need to just start to ue unstable version ?

**Comment by justinmk** [comment]
@kuzyo See above. Currently, stable is published for xenial only.

**Comment by arian-granular** [comment]
@justinmk do you know if there's any plans for stable builds for the older versions in the near future? I'm happy to update the wiki so y'all (hopefully) stop getting pinged about this in issues if it's only going to be for xenial for the foreseeable future.

**Comment by justinmk** [comment]
Let's assume it is xenial-only for now.

**Comment by kimsnj** [comment]
> Let's assume it is xenial-only for now.

https://github.com/neovim/neovim/wiki/Installing-Neovim should be updated to state that users with versions older than Xenial should used neovim/unstable.
With ubuntu 14.04, my first interaction with neovim was this error.
