### ISSUE TITLE
Request for Android support

### ISSUE THREAD

**Issue by rmolin88** [neovim/neovim#5819]
It would be great if you could look into this [issue](https://github.com/termux/termux-packages/issues/568). All the needed info is there. If not please let me know.

Thanks in advance.

**Comment by justinmk** [comment]
I looked at it when it was reported. It looks like a very time consuming problem.

**Comment by justinmk** [comment]
...related to a third party package. Without a more narrow boundary on the problem,  it's unlikely anyone can help.

**Comment by rmolin88** [comment]
Understood. Thanks for looking into it.
