### ISSUE TITLE
incsearch segfaults on neovim

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#5820]
- `nvim --version`: 

```
NVIM v0.2.0-164-gc1d1493, Build type: RelWithDebInfo
```

- Operating system/version: macOS 10.11.6
- Terminal name/version: iterm nightly
- `$TERM`: xterm-256color

### Actual behaviour

With the mappings below, `nvim` segfaults whenever I attempt to do a search. The plugin creator told me to ask here about it.

### Expected behaviour

No segfault.

### Steps to reproduce

Using this `init.vim`,

```
set runtimepath+=~/.config/nvim/bundle/incsearch.vim
set runtimepath+=~/.config/nvim/bundle/incsearch-index.vim

let g:incsearch#auto_nohlsearch = 1
let g:indexed_search_mappings = 0
let g:incsearch#magic = '\v'
let g:incsearch#separate_highlight = 1
let g:incsearch#do_not_save_error_message_history = 1

map / <Plug>(incsearch-forward)
```

attempting to search should fail with a segfault.

**Comment by jamessan** [comment]
Yeah, already reported in #5769.
