### ISSUE TITLE
Colors in terminal emulator are wrong in ipython and pdb++

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#5836]
My neovim version is 1.7. I'm on ubuntu 16.10 gnome-terminal.
```
echo $TERM                                                                                             
xterm-256color 
```
this is what I get
![nvim - vimrc_001](https://cloud.githubusercontent.com/assets/6205841/21492847/6d8458f8-cc21-11e6-892b-c90f62d0a3bb.png)
this is what it should look like
![michael michael-hp-elitedesk-800-g1-sff -vimconf_002](https://cloud.githubusercontent.com/assets/6205841/21492850/7017cff0-cc21-11e6-95af-02c4696bf917.png)

What's wierd by the way is that I don't use neither `export NVIM_TUI_ENABLE_TRUECOLOR` nor `set termguicolors`, but  I seem to get correct solarized colorscheme inside both vim and neovim (both inside and outside tmux). At least I can't spot a difference with gvim, emacs etc. Even after reading wiki I still don't understand how all that works. I mean I know that colors made with escape sequences, but what exactly `termguicolors` and `NVIM_TUI_ENABLE_TRUECOLOR` (or whaterver it's called) does? Both of them don't change anything for me.

**Comment by justinmk** [comment]
termguicolors only has a purpose if your terminal and tmux version supports true color. NVIM_TUI_ENABLE_TRUECOLOR is obsolete, it does nothing.

**Comment by purpleP** [comment]
@justinmk Umh... Why is my issue closed? It's certainly not resolved. I have true Colorado support in terminal and tmux.

**Comment by justinmk** [comment]
What are the steps to reproduce?

**Comment by purpleP** [comment]
@justinmk `nvim -u NONE -c 'call termopen("/tmp/colorcheck.sh")'`
where `colorscheck.sh` is this script
```awk
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
and setting `termguicolors` isn't changing anything.

**Comment by justinmk** [comment]
Ah, it wasn't clear that `:terminal` was being used in the original report. I think you need to set `b:terminal_color_*`. See `:h terminal-emulator-configuration`.

See other issues for discussion: https://github.com/neovim/neovim/search?q=terminal_color&type=Issues&utf8=%E2%9C%93

**Comment by purpleP** [comment]
@justinmk Okay, thanks for answering. I've read this issues previously and no one clearly answers the question of whether neovim terminal does or does not support true colour.
Judging by mentioning 'colour palette' it does not, but can you confirm that? And why is that so? Maybe I'll have the time to look at it someday. Although frankly I've just only started to looking at neovim codebase.

**Comment by purpleP** [comment]
Can someone point me to a link that would explain for example why `xterm-256color` means true colour support? I mean, it says 256, not 16 million, right? And stuff like that. Because I'm confused about all that.

**Comment by justinmk** [comment]
It's hard to give a direct answer because of the unlimited combinations of OSes, terminals, historical quirks, and configuration.

Side note: We do have tentative plans to auto-detect true-color terminals, but even that only works for _some_ terminals, so the problem never actually "goes away" for all users. 

`:terminal` does support true color, technically, IIRC. But `b:terminal_color_` is needed for some reason I don't remember.
