### ISSUE TITLE
Cannot remap `<C-h>`

### ISSUE THREAD

**Issue by Serabe** [neovim/neovim#5837]
- `nvim --version`: 0.1.7
- Vim (version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 25 2016 16:10:01)) behaves differently? Yes
- Operating system/version: MacOS X 10.12.2
- Terminal name/version: iTerm2 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour

I use the following configuration a lot:

```vim
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
```

And all of them work except for `<C-h>` that just acts as normal `h`. `:verbose map` gives me:

```vim
n  <C-H>       * <C-W>h  Last set from ~/.config/nvim/init.vim
```

Testing this with a clean `init.vim` with only those 4 lines reproduces the problem.

### Expected behaviour

I expect pressing `h` while pressing control key to behave like `<C-w>h`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:nnoremap <C-h> <C-w>h
:vs
<C-w>l
<C-h>
```

This also does not work, but remaps successfully `<C-l>`

```
nvim -u NORC
:nnoremap <C-h> <C-w>h
:nnoremap <C-l> <C-w>l
:vs
<C-l>
<C-h>
```

In this case, `<C-l>` works but `<C-h>` does not.

I've tried other remaps without success:

```
nvim -u NORC
:nnoremap <C-h> :echo "Remapped!"<CR>
<C-h>
```

Shows nothing but:

```
nvim -u NORC
:nnoremap <C-l> :echo "Remapped!"<CR>
<C-l>
```

Shows "Remapped!"

Thank you for taking a look at this!

**Comment by mhinz** [comment]
See (the very long) https://github.com/neovim/neovim/issues/2048 for how to fix your terminfo library for your current Neovim version.

Or use master where this issue is already fixed: https://github.com/neovim/neovim/pull/5758
