### ISSUE TITLE
[request] Please consider to adopt recent quickfix patchs since vim 7.4.1800 +

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#5840]
1. cbottom/lbottom
2. the old quickfix code will rewind the cursor to the first line if plugin call `caddexpr` which is totally unacceptable when background job is continue populating the quickfix window. (eg. a build job / grep which will output progress in quickfix window in realtime). The latest quickfix code in vim will not rewind the cursor to the first line when `caddexpr` is been invoked.
3. Poor performance to call "caddexpr", NeoVim get stuck if I insert 50 lines in it every second in a timer. But I can insert more than 1000 lines in quickfix every second.

Making a patch for NeoVim is beyond my ability. As a plugin author, I think quickfix will play a more important role since asynchronous apis were born . It will be much convinience if NeoVim could improve it.

**Comment by jamessan** [comment]
Those were merged earlier today in #5761.
