### ISSUE TITLE
Noticeable lag between pressing a key and echo it to screen.

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#5841]
- `nvim --version`: 0.1.6-250
- Vim (version: ) behaves differently? 8.0.133
- Operating system/version: debian8 
- Terminal name/version: Xshell4
- `$TERM`: xterm

### Actual behaviour
There is a noticeable lag between pressing a key and echo it to screen.

### Expected behaviour
As smooth as vim.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set compatible
:syntax on
:e xxxxxx.cpp
```

Than repeat pressing page down. or input something in insert mode .
btw: My NeoVim is running on my nas: 
4 x Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz
8GB Ram
Debian 8 x64

**Comment by mhinz** [comment]
`:set compatible` should throw an error, since it doesn't exist in Neovim anymore and `:syntax on` is on by default.

- Please update your Neovim to the latest release (0.1.7) and try again.
- For testing purposes, try another terminal emulator than "Xshell4".

**Comment by skywind3000** [comment]
typo , set compatible -> nocompatible

**Comment by skywind3000** [comment]
I am trying to build the latest version, but get stuck:

```VimL
skywind@airvm1:~/software/neovim$ make
make  -C .deps
make[1]: Entering directory '/home/skywind/software/neovim/.deps'
make[2]: Entering directory '/home/skywind/software/neovim/.deps'
make[3]: Entering directory '/home/skywind/software/neovim/.deps'
make[3]: Leaving directory '/home/skywind/software/neovim/.deps'
[  9%] Built target gperf
make[3]: Entering directory '/home/skywind/software/neovim/.deps'
make[3]: Leaving directory '/home/skywind/software/neovim/.deps'
[ 18%] Built target jemalloc
make[3]: Entering directory '/home/skywind/software/neovim/.deps'
make[3]: Leaving directory '/home/skywind/software/neovim/.deps'
[ 27%] Built target unibilium
make[3]: Entering directory '/home/skywind/software/neovim/.deps'
make[3]: Leaving directory '/home/skywind/software/neovim/.deps'
make[3]: Entering directory '/home/skywind/software/neovim/.deps'
[ 28%] Performing install step for 'libtermkey'
make[4]: Entering directory '/home/skywind/software/neovim/.deps/build/src/libtermkey'
gcc: error: /home/skywind/software/neovim/.deps/usr/lib/libunibilium.so: No such file or directory
Makefile:71: recipe for target 'libtermkey.la' failed
make[4]: *** [libtermkey.la] Error 1
make[4]: Leaving directory '/home/skywind/software/neovim/.deps/build/src/libtermkey'
CMakeFiles/libtermkey.dir/build.make:65: recipe for target 'build/src/libtermkey-stamp/libtermkey-install' failed
make[3]: *** [build/src/libtermkey-stamp/libtermkey-install] Error 2
make[3]: Leaving directory '/home/skywind/software/neovim/.deps'
CMakeFiles/Makefile2:237: recipe for target 'CMakeFiles/libtermkey.dir/all' failed
make[2]: *** [CMakeFiles/libtermkey.dir/all] Error 2
make[2]: Leaving directory '/home/skywind/software/neovim/.deps'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/skywind/software/neovim/.deps'
Makefile:75: recipe for target 'deps' failed
make: *** [deps] Error 2
skywind@airvm1:~/software/neovim$ 
```

0.1.6 had been successfully compiled. but the latest version failed (git pull origin master, just now)
It will take me some time to figure out what's wrong. 

And then I can check the latest version and feed you back.

**Comment by mhinz** [comment]
Maybe `make distclean && make` helps?

**Comment by justinmk** [comment]
Try TERM=xterm-256color

**Comment by mhinz** [comment]
@justinmk Changing TERM helps against `libunibilium.so` not being found?

**Comment by justinmk** [comment]
No, that suggestion was for the original issue.

**Comment by skywind3000** [comment]
Successful, `make distclean && make `  works. And it appears there is no lag in the latest version.
Thanks. I will try it for some days, right now it can be closed.
