### ISSUE TITLE
Maximal Mintty/Xshell window is reseted by newly open NeoVim

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#5843]
- `nvim --version`: 0.2.0 211 g9009c20
- Vim (version: ) behaves differently? 8.0.133
- Operating system/version: client (Windows 7 x64), server (debian jessie 64)
- Terminal name/version: Mintty 2.7.2 Xshell 4.0, 
- `$TERM`: xterm

### Actual behaviour
Maximal Mintty/Xshell window is resized and repositioned by newly open NeoVim.

### Expected behaviour
Terminal emulators will not be 

### Steps to reproduce using `nvim -u NORC`
1. Maximize the mintty (from cygwin) window 
2. ssh to debian server from mintty.
3. run `nvim -u NORC`

This is a cygwin mintty terminal with maximal size, and I already login my debian jessie:
![neovim3](https://cloud.githubusercontent.com/assets/3035071/21545271/29299f82-ce11-11e6-8e97-fd489052dbe6.png)

After starting neovim, mintty windows was repositioned, look at the window border, it is different from the previous screen capture (almost 4-5 pixels).
![neovim4](https://cloud.githubusercontent.com/assets/3035071/21545273/2d9fd446-ce11-11e6-88a2-d089e03fd24f.png)

This is another example, I login my server via Xshell 4, and Xshell windows is maximal:
![neovim1](https://cloud.githubusercontent.com/assets/3035071/21545260/181e4530-ce11-11e6-8df7-dd613a3f68a3.png)

After starting neovim, Xshell window has been moved far away from origin position
![neovim2](https://cloud.githubusercontent.com/assets/3035071/21545265/1f7a1a66-ce11-11e6-8878-3f2a4c9a850d.png)

**Comment by justinmk** [comment]
This happens with `nvim -u NORC`?

**Comment by skywind3000** [comment]
`nvim -u NORC` still has the same problem.

**Comment by ewapptus** [comment]
I'm having this issue too. VIM works fine.

After starting NVIM the mintty window is pushed slightly left and the title bar grows by about the same amount, pushing the window down so that the bottom is slightly below Windows start menu. It is very annoying :)

NVIM verison is 0.1.7.
Client operating system version is Windows 10 x64
Server operating system is CentOS 7.3.1611 x86_64
Mintty version is 2.7.4 (x86_64-pc-cygwin)
And environemt variable $TERM is xterm.

**Comment by alxndr13** [comment]
+1

**Comment by alxndr13** [comment]
**note**: i used the "neovim"-package in the arch repositories, where i encountered the above described bug. Today i tried the latest git commit and build neovim from source. I didnt encounter the issue with the lastest git build. So it may be fixed somewhere in between.

**Comment by skywind3000** [comment]
awesome ! expecting the next stable release.

**Comment by lanedraex** [comment]
This issue is not fixed for me.

Tested it on `NVIM v0.2.1-1061-g1de5b04`, with Windows `10.0.15063` and Mintty as well.

I run nvim from the [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) with Ubuntu `16.04.3 LTS`

Vim behaves as expected, Mintty stays on fullscreen.

**Comment by lanedraex** [comment]
Updating [mintty](https://github.com/mintty/wsltty)  to `v1.8.5.2` fixed this issue.

The window stays maximized and doesn't move in `NVIM v0.2.2`.

**Comment by boulund** [comment]
I just updated to [wsltty](https://github.com/mintty/wsltty) version `1.9.0.2` and I still have this issue. 

Every time I launch `nvim` (I have version `0.2.2`) on the command line when running the terminal window in full screen mode, it pops back into maximized windowed mode. This introduces the top bar on top of the window and shifts all the window contents down a bit, which is very frustrating. 

No such issues when running VIM version `8.1.209`.

**Comment by justinmk** [comment]
This should be fixed in Nvim 0.4.x with commit 533d4a36ec03626e9d796ef7e2a9aa3c0e1ce7bf. Make sure your build includes that commit.
