### ISSUE TITLE
man.vim: bold and underline highlighting

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5846]
I've seen this requested on reddit and brought up on the gitter a few times before. In particular, see https://www.reddit.com/r/neovim/comments/5kvy7d/using_neovim_as_manpager_is_there_a_way_to/ for what I mean.

Currently, we throw away all the backspaces that indicate which text should be bolded/underlined, instead we need to do something similar to https://github.com/nhooyr/neovim/pull/1

**Comment by mhinz** [comment]
And is there anything blocking it?

**Comment by nhooyr** [comment]
Nothing, just haven't gotten around to it yet.

**Comment by nhooyr** [comment]
I'm working on it now, hopefully I can get a PR done today.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/7623
