### ISSUE TITLE
nvim xsel not working properly?

### ISSUE THREAD

**Issue by teamblubee** [neovim/neovim#5853]
```shell
vi --version
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -O2 -pipe -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing -Wconversion -O2 -pipe -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wno-c11-extensions -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/usr/ports/editors/neovim/work/.build/config -I/usr/ports/editors/neovim/work/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/ports/editors/neovim/work/.build/src/nvim/auto -I/usr/ports/editors/neovim/work/.build/include
Compiled by root@blubee.me

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```
- Operating system/version: FreeBSD 12-CURRENT

```shell
 pkg info | grep rxvt
rxvt-unicode-9.22              Clone of the terminal emulator rxvt modified to support Unicode

- `$TERM`: rxvt-unicode-256
```

### Actual behaviour
Nothing gets copied to the clipboard, I can copy directly from the terminal by CTRL+ALT+C and paste with CTRL+ALT+V but visual highlighting some text in neovim and < , >y+ doesn't copy to the system registers.

### Expected behaviour
copy selected text to the system registers. I've had neovim work as expected on previous setups on FreeBSD before.

![xsel-error](https://cloud.githubusercontent.com/assets/2129150/21580527/61aee4b0-d038-11e6-8268-a27c05044f6f.png)

**Comment by justinmk** [comment]
If you call these commands from a shell, what happens?

    xsel --nodetach -i -b foo
    xsel --nodetach -i -p foo
    xsel -o -p
    xsel -o -b

**Comment by teamblubee** [comment]
none of those commands work for me

```shell
me@blubee:~ % xsel --nodetach -i -b foo
xsel 0.04 23072002

Command line interface to the X selections

usage:  xsel action [options]
actions:
   -p or --paste
      Paste the current X selection (if any) to stdout and
      and exit.
   -c or --copy
      Copy the input from stdin to the X selection. Note that
      the X selection model has no concept of selection buffer
      on the server. Rather, the client that holds the current
      selection makes it available to the other clients and
      has to wait until someone requests it. Hence, xsel forks
      and serves the selection requests until someone else
      claims the selection.
      The copied string can also be given on command line
      rather than through stdin: --copy "string to copy".
   -m or --merge
      Same as -c, but merge the input to the current selection
      instead of overwriting it.
options:
   -s SELECTION or --selection SELECTION
      Where SELECTION is either "PRIMARY", "SECONDARY" or
      "CLIPBOARD". Selects which X selection to use. For -p,
      the default is to first try PRIMARY, and if it is empty,
      then SECONDARY and finally CLIPBOARD. For -c and -m, the
      default is PRIMARY.
```

version: xsel-0.04.1_5                  Access X11 selection buffer from command line

**Comment by justinmk** [comment]
Perhaps we should check the version of xsel.

**Comment by teamblubee** [comment]
That might be a good option. On this machine I 0.04.1 is the latest version. I am not exactly sure which version is recommended by the docs but this threw me for a loop because I had both xsel and xclip installed but xsel was installed first. I don't think that it should matter which one installs first.

It looks like nvim sees xsel and just tries that and chokes if the version is below the threshold you guys tested against.

**Comment by mhinz** [comment]
Yup, it simply uses the first executable it finds and checks xsel before xclip: https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L48-L59

If old versions of xclip are known to work without change, we probably should prioritize xclip over xsel.

But then, old versions of xsel should work just as well, so.. @teamblubee Could you please reinstall xsel and paste the output of `xsel --version`?

**Comment by teamblubee** [comment]
@mhinz my version of xsel doesn't even have the version flag.

if I try to run any other command than xsel -[p|c|m|s] it'll just print out the help message, I already posted that above.

From my package manager xsel returns:
```
xsel-0.04.1_5                  Access X11 selection buffer from command line
```

```
FreeBSD blubee.me 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r310698: Wed Dec 28 23:37:51 CST 2016     root@me:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by justinmk** [comment]
> we probably should prioritize xclip over xsel. 

Previously we prioritized xsel because it gave us more control. IIRC xclip does not support "custom" clipboards, e.g. the VIMENC thing used by Vim/Nvim to mark block region. But it looks like we gave up on that for xsel: https://github.com/kfish/xsel/pull/8

Anyways, why don't we fallback to xclip if xsel fails (and xclip is available)?

**Comment by mhinz** [comment]
I guess `xclip` is just returning 0 in this case, otherwise @teamblubee should see [an error](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim#L23-L29).

**Comment by justinmk** [comment]
@teamblubee what does this print?

```
xsel -o -b
echo $?
```

**Comment by teamblubee** [comment]
@justinmk I cannot use those commands. Any command other that -p -c -m -s will not work.

```
me@blubee:~ % xsel -o -b
xsel 0.04 23072002

Command line interface to the X selections

usage:  xsel action [options]
actions:
   -p or --paste
      Paste the current X selection (if any) to stdout and
      and exit.
   -c or --copy
      Copy the input from stdin to the X selection. Note that
      the X selection model has no concept of selection buffer
      on the server. Rather, the client that holds the current
      selection makes it available to the other clients and
      has to wait until someone requests it. Hence, xsel forks
      and serves the selection requests until someone else
      claims the selection.
      The copied string can also be given on command line
      rather than through stdin: --copy "string to copy".
   -m or --merge
      Same as -c, but merge the input to the current selection
      instead of overwriting it.
options:
   -s SELECTION or --selection SELECTION
      Where SELECTION is either "PRIMARY", "SECONDARY" or
      "CLIPBOARD". Selects which X selection to use. For -p,
      the default is to first try PRIMARY, and if it is empty,
      then SECONDARY and finally CLIPBOARD. For -c and -m, the
      default is PRIMARY.
me@blubee:~ % echo $?
1
me@blubee:~ % 
```

after that command i typed xsel -p and got this output

``` shell
me@blubee:~ % xsel -p
me@blubee:~ % xsel -o -b
xsel 0.04 23072002

Command line interface to the X selections

usage:  xsel action [options]
actions:
   -p or --paste
      Paste the current X selection (if any) to stdout and
      and exit.
   -c or --copy
      Copy the input from stdin to the X selection. Note that
      the X selection model has no concept of selection buffer
      on the server. Rather, the client that holds the current
      selection makes it available to the other clients and
      has to wait until someone requests it. Hence, xsel forks
      and serves the selection requests until someone else
      claims the selection.
      The copied string can also be given on command line
      rather than through stdin: --copy "string to copy".
   -m or --merge
      Same as -c, but merge the input to the current selection
      instead of overwriting it.
options:
   -s SELECTION or --selection SELECTION
      Where SELECTION is either "PRIMARY", "SECONDARY" or
      "CLIPBOARD". Selects which X selection to use. For -p,
      the default is to first try PRIMARY, and if it is empty,
      then SECONDARY and finally CLIPBOARD. For -c and -m, the
      default is PRIMARY.
me@blubee:~ % echo $?
1
me@blubee:~ % 
me@blubee:~ % 
```

so it does know what's in the main register. If I type xsel -c it just creates a huge white window... Not exactly sure that that does.

actually looking at it further when I do xsel -p a white window will flash across the screen then disappear. on xsel -c the window stays, it looks like a bug in xsel.

**Comment by jamessan** [comment]
If I'm reading the output right (`xsel 0.04 23072002`), you have a 14+ year old version of xsel. The 1.0.0 release (last release listed in the changelog) is only 9 years old.

I'm all for not requiring bleeding edge versions of software, but it is possible to update your version of xsel?

**Comment by justinmk** [comment]
> me@blubee:~ % xsel -o -b
> ...
> me@blubee:~ % echo $?
> 1

That confirms that we can check `v:shell_error` after trying `xsel -o -b`, then fall back to `xclip`.

**Comment by justinmk** [comment]
@teamblubee Can you try #5868 ?
