### ISSUE TITLE
Unable to build for Odroid C2 with DietPi

### ISSUE THREAD

**Issue by joshuamcginnis** [neovim/neovim#5861]
I've been trying to build neovim for Odroid C2 running [DietPi](http://dietpi.com/) for the last few days with no luck. I suspect I'm close but perhaps you can help me take it to completion.

#4714 covers a similar issue, but using the information provided, I've still been unable to get a proper build going.

Here's what I've done so far:

- `make && make install` https://github.com/msgpack/msgpack-c
- `sudo apt-get install lua5.1 luarocks libuv0.10-dev`
- `sudo luarocks install lpeg mpack`

To build:
- `make distclean`
- `mkdir build && cd build`
- `cmake -DCMAKE_INSTALL_PREFIX=$HOME/neovim ..`

Output:
```
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done   
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info     
-- Detecting CXX compiler ABI info - done                          
-- CMAKE_BUILD_TYPE not given, defaulting to 'Dev'.
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2.            
-- Performing Test HAS_OG_FLAG                                                                                                                                                    
-- Performing Test HAS_OG_FLAG - Success                                                                                                                                         
-- Performing Test HAS_ACCEPTABLE_FORTIFY                                                                                                                                         
-- Performing Test HAS_ACCEPTABLE_FORTIFY - Success                                                                                                                               
-- Performing Test HAS_WVLA_FLAG                                                                                                                                                  
-- Performing Test HAS_WVLA_FLAG - Success                                                                                                                                        
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG                                                                                                                               
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG - Success                                                                                                           
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG                  
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG - Success
-- Performing Test HAS_DIAG_COLOR_FLAG     
-- Performing Test HAS_DIAG_COLOR_FLAG - Success                  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")                 
-- Looking for dlopen in dl                  
-- Looking for dlopen in dl - found            
-- Looking for kstat_lookup in kstat
-- Looking for kstat_lookup in kstat - not found
-- Looking for kvm_open in kvm
-- Looking for kvm_open in kvm - not found
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - found
-- Looking for perfstat_cpu in perfstat
-- Looking for perfstat_cpu in perfstat - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for sendfile in sendfile
-- Looking for sendfile in sendfile - not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  **Could NOT find LibUV (missing: LIBUV_LIBRARY LIBUV_INCLUDE_DIR)**
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibUV.cmake:105 (find_package_handle_standard_args)
  CMakeLists.txt:306 (find_package)


-- Configuring incomplete, errors occurred!
```

In the aforementioned issue, @ZyX-I mentioned that `luv` was not needed, but it seems the build continues to fail.

Any ideas on other things I can try? Thanks!

**Comment by jamessan** [comment]
libuv and luv are different things.  What's failing here is finding libuv, and Neovim definitely needs that.  The reason it's failing is that your libuv is too old (0.10).  You'll need to either install libuv1-dev (if it's available) or uninstall libuv0.10-dev and run `make deps` from the top-level directory.

**Comment by joshuamcginnis** [comment]
I've uninstalled `libuv0.10-dev` and installed `libuv1-dev`. That resolved the `libuv` issue, but I'm now getting the following error message regarding `unibilium`. 

```
-- Found LibUV: /usr/lib/aarch64-linux-gnu/libuv.so                                                                                                                               -- Found Msgpack: /usr/local/lib/libmsgpackc.so (found suitable version "2.0.0", minimum required is "1.0.0")                                                                     -- Could NOT find unibilium (missing:  UNIBILIUM_LIBRARY UNIBILIUM_INCLUDE_DIR)                                              
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):                                                                                    
  Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY                                                                                                                          
  LIBTERMKEY_INCLUDE_DIR)                                                                                                        
Call Stack (most recent call first):                                                                 
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)                                                                                   
  cmake/FindLibTermkey.cmake:44 (find_package_handle_standard_args)                                                                                                        
  CMakeLists.txt:322 (find_package)                                                                                                                                               
                                                                                                                                                                                  
                                                                                                                                                                                  -- Configuring incomplete, errors occurred!
```

`unibilium` is not an available package, so I tried to build it from source and it failed with:

```
tools/unibi-put.c:1:0: warning: -fsanitize=address not supported for this target
 /*
 ^
tools/unibi-put.c: In function 'main':
tools/unibi-put.c:87:13: warning: missing braces around initializer [-Wmissing-braces]
             unibi_var_t vars[9] = {0};
             ^
tools/unibi-put.c:87:13: warning: (near initialization for 'vars[0]') [-Wmissing-braces]
libtool: compile:  cc -I. -Wall -std=c99 -std=gnu99 -pedantic -Wall -Wextra -Wundef -Wshadow -Wbad-function-cast -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Winline -Wdisabled-optimization -O2 -pipe -fstack-protector-all -fsanitize=address -fsanitize=undefined -c tools/unibi-put.c -o tools/unibi-put.o >/dev/null 2>&1
libtool --mode=link --tag=CC cc -fsanitize=address -fsanitize=undefined -o tools/unibi-put libunibilium.la tools/unibi-put.lo
libtool: link: cc -fsanitize=address -fsanitize=undefined -o tools/.libs/unibi-put tools/.libs/unibi-put.o  ./.libs/libunibilium.so
/usr/bin/ld: cannot find libasan_preinit.o: No such file or directory
/usr/bin/ld: cannot find -lasan
/usr/bin/ld: cannot find -lubsan
collect2: error: ld returned 1 exit status
Makefile:69: recipe for target 'tools/unibi-put' failed
make: *** [tools/unibi-put] Error 1
rm tools/unibi-put.lo
```

**Comment by justinmk** [comment]
> unibilium is not an available package, so I tried to build it from source and it failed with:

@joshuamcginnis According to [this](https://github.com/mauke/unibilium/pull/18#issuecomment-219191415) maint.mk is "supposed to be used by the maintainer". And that's the only file that mentions `-fsanitize`. Perhaps there's a way to build without those `-fsanitize` options?

**Comment by justinmk** [comment]
Ah, it's because of [this](https://github.com/mauke/unibilium/blob/master/Makefile#L2). IOW it expects to be a non-git tarball if you're "not a maintainer". Try commenting-out those lines in the Makefile.

**Comment by joshuamcginnis** [comment]
I'll try it now. Which lines should I comment - just `include maint.mk`? There are about seven lines that reference unibilium.

**Comment by jamessan** [comment]
Alternatively, let our third-party builds take place but disable ones that you expect to be installed already.

From the top-level directory run `make deps DEPS_CMAKE_FLAGS="-DUSE_BUNDLED_LIBUV=OFF -DUSE_BUNDLED_MSGPACK=OFF ..."` and then try to build neovim.

**Comment by joshuamcginnis** [comment]
OK, getting closer.

I've done the following:
```make deps DEPS_CMAKE_FLAGS="-DUSE_BUNDLED_LIBUV=OFF -DUSE_BUNDLED_MSGPACK=OFF -DUSE_BUNDLED_LUAROCKS=OFF -DUSE_BUNDLED_LUAJIT=OFF"```

Then I tried to build again and got:
```
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2.
-- Found Iconv                              
-- Checking Lua interpreter /usr/local/bin/lua
-- [/usr/local/bin/lua] The 'bit' lua package is required for building Neovim
CMake Error at CMakeLists.txt:409 (message):
  A suitable Lua interpreter was not found.      
                                               
                                                   
-- Configuring incomplete, errors occurred!          
```

At this point, I've installed `lua5.1 luarocks libuv1-dev` via apt and `lpeg mpack` via luarocks. I tried to install luabittop via luarocks and got:

```
sudo luarocks install luabitop
Installing https://luarocks.org/luabitop-1.0.2-1.src.rock
gcc -O2 -fPIC -I/usr/local/include -c bit.c -o bit.o
bit.c: In function ‘barg’:
bit.c:83:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
 #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
  ^

Error: Build error: Failed compiling object bit.o
```

**Comment by justinmk** [comment]
If none of the `LUA_NUMBER_*` symbols expected by [bit.c](https://github.com/LuaDist/luabitop/blob/master/bit.c#L66-L84) are defined, it could be you have a new (lua 5.3) version of lua, which only defines `LUA_NUMBER_FMT`:

https://github.com/lua/lua/blob/master/luaconf.h

This commit confirms that LUA_NUMBER_DOUBLE was removed in 5.3:

https://github.com/lua/lua/commit/2b4975dca710510a7b94f1f9bef97814d1349f95

**Comment by jamessan** [comment]
> -- Checking Lua interpreter /usr/local/bin/lua

This is probably the problem.  You're not using the system lua5.1.

**Comment by joshuamcginnis** [comment]
Yup, that was the issue. I was finally able to get a build! But I have couple of remaining questions.

For future users, here was the approach I took to get a successful build on Odroid C2:
* `make && make install` https://github.com/msgpack/msgpack-c
* `sudo apt-get install lua5.1 luarocks libuv1-dev`
* `sudo luarocks install lpeg && sudo luarocks install mpack && sudo luarocks install luabitop`
* Build all other third-party dependencies: 
`make deps DEPS_CMAKE_FLAGS="-DUSE_BUNDLED_LIBUV=OFF -DUSE_BUNDLED_MSGPACK=OFF -DUSE_BUNDLED_LUAROCKS=OFF -DUSE_BUNDLED_LUAJIT=OFF"`
* Build neovim: `mkdir build` && `cd build` &&  `cmake -DCMAKE_INSTALL_PREFIX=$HOME/neovim ..`

It appears the binary was installed at `$HOME/neovim/bin/nvim`. Do I need to now add this to my $PATH in order to execute `nvim`? Not sure why I would want the build in my home directory anyway.

How do I deal with updates to neovim and any updates to the dependencies with this modified build procedure?

How would I uninstall neovim and third-party deps should I need to do so in the future?

I'm happy to update documentation for other Odroid / DietPi or work on a PR to make installation easier for users PR if you'd like.

**Comment by justinmk** [comment]
> It appears the binary was installed at $HOME/neovim/bin/nvim

That's controlled by `-DCMAKE_INSTALL_PREFIX=$HOME/neovim`, which you mentioned in your notes.

>How do I deal with updates to neovim and any updates to the dependencies with this modified build procedure?
> How would I uninstall neovim and third-party deps should I need to do so in the future?

There isn't any good way, that's what a package system is for--to "encode" these steps so that they can be automated. 

> I'm happy to update documentation for other Odroid / DietPi 

We don't have a place for system-specific notes on "hacking up a build". We _do_ have wiki pages for 

- "Installing from a _package_" 
- [Build Pre-requisites](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisite)

> or work on a PR to make installation easier for users PR if you'd like.

That would be great! But as mentioned above, given that apt-get is available on the system, really the only thing that makes sense is to create a package. Neovim is available in Debian and (soon?) Ubuntu, so perhaps just some tweaks are needed or it will matriculate down to Odroid, eventually? Where/when/how does Odroid get its apt packages?

- It might make sense to send a PR to unibilium so that its `Makefile` skips `maint.mk` if an env var is present, or something like that.
