### ISSUE TITLE
Could NOT find unibilium

### ISSUE THREAD

**Issue by joshuamcginnis** [neovim/neovim#5867]
This is an update to #5861 since it was closed prior to resolution. 

I'm trying to build neovim for Odroid C2 with DietPi and have been unsuccessful thus far with all of the methods provided so far.

Per #4714, I've installed most third-party dependencies using apt and luarocks since `make deps` appears to not support the Odroid / Arm64 platform. I'm now trying to do a build via:

- make distclean
- mkdir build && cd build
- cmake -DCMAKE_INSTALL_PREFIX=$HOME/neovim ..

The latest error is "Could NOT find unibilium". `unibilium` is not available via apt and an attempt to build it from source resulted in an error that I'm happy to provide.

```
-- Found LibUV: /usr/lib/aarch64-linux-gnu/libuv.so                                                                                                                               -- Found Msgpack: /usr/local/lib/libmsgpackc.so (found suitable version "2.0.0", minimum required is "1.0.0")                                                                     -- Could NOT find unibilium (missing:  UNIBILIUM_LIBRARY UNIBILIUM_INCLUDE_DIR)                                              
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):                                                                                    
  Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY                                                                                                                          
  LIBTERMKEY_INCLUDE_DIR)                                                                                                        
Call Stack (most recent call first):                                                                 
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)                                                                                   
  cmake/FindLibTermkey.cmake:44 (find_package_handle_standard_args)                                                                                                        
  CMakeLists.txt:322 (find_package)
```  
Are there any other ideas on what I can try to resolve this? My thanks in advance.

**Comment by jamessan** [comment]
> This is an update to #5861 since it was closed prior to resolution.

It was closed because the problems are environmental, not a Neovim problem.  We can still keep discussing things there, even though it's closed and I would prefer to do that instead of opening a new issue for every step.

**Comment by living1069** [comment]
> 
> 
> This is an update to #5861 since it was closed prior to resolution.
> 
> I'm trying to build neovim for Odroid C2 with DietPi and have been unsuccessful thus far with all of the methods provided so far.
> 
> Per #4714, I've installed most third-party dependencies using apt and luarocks since `make deps` appears to not support the Odroid / Arm64 platform. I'm now trying to do a build via:
> 
>     * make distclean
> 
>     * mkdir build && cd build
> 
>     * cmake -DCMAKE_INSTALL_PREFIX=$HOME/neovim ..
> 
> 
> The latest error is "Could NOT find unibilium". `unibilium` is not available via apt and an attempt to build it from source resulted in an error that I'm happy to provide.
> 
> ```
> -- Found LibUV: /usr/lib/aarch64-linux-gnu/libuv.so                                                                                                                               -- Found Msgpack: /usr/local/lib/libmsgpackc.so (found suitable version "2.0.0", minimum required is "1.0.0")                                                                     -- Could NOT find unibilium (missing:  UNIBILIUM_LIBRARY UNIBILIUM_INCLUDE_DIR)                                              
> CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):                                                                                    
>   Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY                                                                                                                          
>   LIBTERMKEY_INCLUDE_DIR)                                                                                                        
> Call Stack (most recent call first):                                                                 
>   /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)                                                                                   
>   cmake/FindLibTermkey.cmake:44 (find_package_handle_standard_args)                                                                                                        
>   CMakeLists.txt:322 (find_package)
> ```
> 
> Are there any other ideas on what I can try to resolve this? My thanks in advance.

do not try to compile it, so many bugs are waiting ...
