### ISSUE TITLE
Language changed after an update

### ISSUE THREAD

**Issue by marceloboeira** [neovim/neovim#5873]
- `nvim --version`:
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161229-52522-8vbvjk/neovim-0.1.7/build/config -I/tmp/neovim-20161229-52522-8vbvjk/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161229-52522-8vbvjk/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161229-52522-8vbvjk/neovim-0.1.7/build/include
Compilé par marceloboeira@DwightSchrute

Включені (+) або не включені (-) компоненти: +acl+iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```
- Operating system/version: `MacOS 10.12.2 Beta 2`
- Terminal name/version:
```
zsh --version
zsh 5.2 (x86_64-apple-darwin16.0)
```
- `$TERM`: xterm-256color

### Actual behaviour

After updating to the last version it changed the language to French.
My OS' language was never French, always English.

### Expected behaviour

Don't change the language after an update.

**Comment by justinmk** [comment]
This is almost certainly environmental. What does this report from `nvim`:

```
:echo  $VIMRUNTIME $LC_ALL
:lang
```

**Comment by shizeeg** [comment]
it's not French it's Ukrainian :)
I guess it's `LANG=uk_UA.UTF-8` (which is Ukrainian), instead of `LANG=en_GB.UTF-8` (which is UK English)

**Comment by justinmk** [comment]
`fichier vimrc système` appears in `po/fr.po`, and `Включені` appears in `po/uk.po`. Hmm.

Still wondering about previous questions.

**Comment by marceloboeira** [comment]
@shizeeg in the version is Ukranian, but inside the 'interface' is in French. Really bizzar.

**Comment by marceloboeira** [comment]
@justinmk 

`:echo  $VIMRUNTIME $LC_ALL`

`/usr/local/Cellar/neovim/0.1.7/share/nvim/runtime`

-----

`:lang`

`Langue courante pour : "C"`

**Comment by jamessan** [comment]
What does the shell command `locale` show?

**Comment by marceloboeira** [comment]
@jamessan nice catch! 
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by jamessan** [comment]
`LC_CTYPE` doesn't look correct.  If you run `env LC_CTYPE=C nvim`, does that fix things?

**Comment by marceloboeira** [comment]
@jamessan nope, but I have tried this:

```
$ export LANG=C
$ locale
LANG="C"
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
$ nvim
```
Then it works!

**Comment by light2yellow** [comment]
I experience exactly the same problem with exactly the same OS/software configuration and my output is the same as @marceloboeira. But it is in Russian instead. Exporting C works but I wonder if this is ok to use this variable on macos because other apps are somehow not broken.

**Comment by justinmk** [comment]
@marceloboeira @light2yellow Does Vim have any such weird behavior under the same conditions?

**Comment by marceloboeira** [comment]
@justinmk nope, I opened to check, it is in English (the expected/default language for me).

**Comment by light2yellow** [comment]
@justinmk no, it somehow deals with it. Running with above locale settings yields normal English interface.

**Comment by light2yellow** [comment]
@justinmk so I asked about this on #macosx irc and they said that the locale (if I understood them right) should be set through osx apis (and not gathered from `locale` (which seems ridiculous to me that I need to manually set locale in unix but they call it "apple style")).

**Comment by jamessan** [comment]
Maybe we need the equivalent of [this](https://github.com/vim/vim/blob/6abda995a57306028c3dc5c62c9b15858e5a3bcf/src/os_mac_conv.c#L572-L592) in nvim.

**Comment by justinmk** [comment]
@jamessan That looks promising. Promoted out of "todo".

**Comment by lunixbochs** [comment]
Just had a user trigger this because Sublime doesn't pass the shell environment, so :+1: (though I'll maybe implement `mac_lang_init` in Python as a workaround).

**Comment by mike3run** [comment]
Plop this in your `init.vim`

```
language en_US
```

**Comment by jamessan** [comment]
If you were having this problem, can you try reverting any workaround you had and then use the build from #7704?
