### ISSUE TITLE
Mark 0 not opening last edited file

### ISSUE THREAD

**Issue by kurkale6ka** [neovim/neovim#5875]
- `nvim --version`: NVIM v0.2.0-258-gc56411ed8
- Vim (version: ) behaves differently? yes. in Vim the last edited file is opened
- Operating system/version: Arch Linux
- Terminal name/version: Sakura
- `$TERM`: xterm-256color

### Actual behaviour
Error message: `E20: Mark not set`

### Expected behaviour
Go to last edited file

### Steps to reproduce using `nvim -u NORC`

- open a file
- exit
- start nvim again
- use `0

**Comment by justinmk** [comment]
Thanks. See https://github.com/neovim/neovim/issues/3472

**Comment by justinmk** [comment]
With https://github.com/neovim/neovim/pull/5908 this should be fixed.
