### ISSUE TITLE
inccommand: Command in visual mode causes visual selection to disappear

### ISSUE THREAD

**Issue by DarkDeepBlue** [neovim/neovim#5888]
- `nvim --version`: NVIM v0.2.0-280-ge21aef1e (Release)

- Vim (version: 8.0.86) behaves differently?
No such issues with vim.

- Operating system/version: ArchLinux 4.8.15
- Terminal name/version: urxvt
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
After selection of a few lines and calling something like `:sort`, the selection disappears visually after entering 'o'. The lines are still sorted after calling `:sort`. The issue seems to be triggered by different inputs like `:sa`, `:sh`, `:sk` and others.

### Expected behaviour
Disappearence of the visual selection after execution of the entered command.

### Steps to reproduce using `nvim -u NORC`
This issue cannot be triggered using `nvim -u NORC` and emerges if `set inccommand=split` is set in the configuration file.

**Comment by jamessan** [comment]
Can you bisect which part of your configuration/plugins is causing this?  As you state, it works fine with `-u NORC` and it works fine for me with my full setup, so there's something specific to your environment.

**Comment by DarkDeepBlue** [comment]
The issue seems to be triggered by `set inccommand=split`.

**Comment by jamessan** [comment]
I started looking into this, and `VIsual_active` is unset as soon as the `:` is pressed to enter command-line mode.  The problem is that something is then causing a redraw, which causes the UI to be made aware that visual mode is no longer active.

**Comment by justinmk** [comment]
Oh, this is actually the same root cause as https://github.com/neovim/neovim/issues/5912. I think it won't be much trouble, we need to check for a non-word character in `cmd_can_preview()`. Or something like that.

**Comment by DarkDeepBlue** [comment]
Awesome, thanks. That really bothered me for some reason.
