### ISSUE TITLE
Job output handler gets passed previous output with sleep in handler

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#5889]
- `nvim --version`: v0.2.0-282-g7a344c79 (also with v0.1.7 and v0.1.0)
- Vim (version: 8.0.86) behaves differently!
- Operating system/version: Arch Linux

### Actual behaviour

With the following program `1` is passed to the handler always, but it should be `1`, …, `5`.
This is caused by the `sleep` in the handler itself (simulating more processing):

```vim
function! s:handler(job, data, event)
  echom "handler" string([a:job, a:data, a:event])

  if a:event ==# 'stdout'
    sleep 200m
  endif
endfunction

if has('nvim')
  call jobstart(['bash', '-c', 'for i in $(seq 1 5); do echo $i; sleep 0.1; done'], {
        \ 'on_stdout': function('s:handler'),
        \ 'on_exit': function('s:handler')})
else
  function! s:vim_handler(channel, output)
    call s:handler(a:channel, a:output, 'stdout')
  endfunction
  call job_start(['bash', '-c', 'for i in $(seq 1 5); do echo $i; sleep 0.1; done'], {
        \ 'out_cb': function('s:vim_handler')})
endif
```

```
handler [1, ['1', ''], 'stdout']
handler [1, ['1', ''], 'stdout']
handler [1, ['1', ''], 'stdout']
handler [1, ['1', ''], 'stdout']
handler [1, ['1', ''], 'stdout']
handler [1, 0, 'exit']
```

Vim's output:
```
handler [channel 0 open, '1', 'stdout']
handler [channel 0 open, '2', 'stdout']
handler [channel 0 open, '3', 'stdout']
handler [channel 0 open, '4', 'stdout']
handler [channel 0 open, '5', 'stdout']
```

(I came across this when looking into https://github.com/vim/vim/issues/1320 again, which is about Vim calling the exit handler while still in the output handler.)

**Comment by oni-link** [comment]
While still in the callback, the `sleep` command polls input/processes events and can call the callback again. Problem is that used input in the stream buffer is only consumed after returning from the callback. So callbacks from callbacks see their data start from the position of the first callback.

Try this patch:

```diff
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index a046b2a28..357c5dd83 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -23140,11 +23140,10 @@ static void on_job_output(Stream *stream, TerminalJobData *data, RBuffer *buf,
     terminal_receive(data->term, ptr, count);
   }
 
+  rbuffer_consumed(buf, count);
   if (callback->type != kCallbackNone) {
     process_job_event(data, callback, type, ptr, count, 0);
   }
-
-  rbuffer_consumed(buf, count);
 }
 
 static void eval_job_process_exit_cb(Process *proc, int status, void *d)
```

**Comment by blueyed** [comment]
> While still in the callback, the `sleep` command polls input/processes events and can call the callback again.

What other events might cause this?
I've seen that `redraw` (only in Vim?) might also trigger it.

The patch fixes the (rather severe) issue, thanks!

The `sleep` in this case is just an abstraction of callback handlers taking a while (but then this is also only an issue if `redraw` or something similar is being called).

**Comment by oni-link** [comment]
I did not use a copy because `process_job_event()` is "copying" `buf`. Is there another thread that could access the `RBuffer` in the meantime?

`xmemdup` use:
Is it guaranteed that we always read from the start of the ring buffer?  If not, we should use `rbuffer_read()` to copy the buffer somewhere else.

**Comment by jamessan** [comment]
> Is it guaranteed that we always read from the start of the ring buffer?

`process_job_event` certainly assumes that the data is contiguous.

> Is there another thread that could access the RBuffer in the meantime?

I guess I was being overcautious.
