### ISSUE TITLE
statusline filename modifier for current tab directory

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5891]
`expand(%:.)` prints the filename relative to the current global directory. We could add a new modifier or perhaps we could also just change it to print the filename relative to the current window directory and if that is not set, then check the current tab directory, and if that is not set, only then use the global directory.

related vim/vim#1357

**Comment by justinmk** [comment]
There can be only one "current directory", and that's decided by the innermost scope. `expand('%:.')` is already relative to the window-local and tab-local CWD as appropriate.

**Comment by nhooyr** [comment]
It's not working in the `'statusline'` option at least. https://asciinema.org/a/7l7ndtkjoh057niasxn6yuy1k

**Comment by nhooyr** [comment]
Also, not sure why but the statusline filename didn't immediately become relative to the directory I had `:lcd` into. weird

**Comment by justinmk** [comment]
`getcwd({winnr})` should solves this, no?
