### ISSUE TITLE
terminal buffer name should reflect running command

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5898]
- `nvim --version`: NVIM 0.2.0-dev at 23b39ebb24d6468d6dda76ffbb88f1fd3b99501c
- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.12.2
- Terminal name/version: 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
The title of a terminal buffer does not change based on the command running within the shell. E.g., open a new terminal buffer and just type cat, the buffer name of the terminal still have whatever shell you are using inside it instead of cat.

### Expected behaviour
It should change.

**Comment by jamessan** [comment]
The buffer name itself shouldn't change, but you could have the status line reflect the currently running command.  Support for that was already implemented in #5026.

**Comment by nhooyr** [comment]
Perfect, thanks!

**Comment by nhooyr** [comment]
it looks like there is a problem with #5026. With long directories `b:term_title` gets cut off

**Comment by nhooyr** [comment]
See https://asciinema.org/a/959ihxzxhhz7v0bppxlxu6ndf

**Comment by jamessan** [comment]
Or there's a limit on the string length we get back from libvterm, since we're just setting what libvterm [hands to us](https://github.com/neovim/neovim/blob/1fee9a7151b30435947475fb410029397725f2ac/src/nvim/terminal.c#L647-L651).  @leonerd?

**Comment by leonerd** [comment]
Ahhhhh this one :)

Yes; buffer sizes to blame in summary. libvterm needs a bit of a hack around to avoid that. It's on my TODO list. In fact, it's one of the main reasons for /not/ yet having declared a v0.1 release.

**Comment by justinmk** [comment]
We can close this then. Thanks @leonerd!
