### ISSUE TITLE
clipboard: error: when yanking

### ISSUE THREAD

**Issue by pdoak** [neovim/neovim#5900]
- `nvim --version`: NVIM v0.2.0-212-gd2998a0
- Vim (version: ) behaves differently? Vi IMproved 8.0
- Operating system/version: OS X 10.12.2
- Terminal name/version: iTerm2 Build 3.0.20170105-nightly
- `$TERM`:xterm-256color-italic

### Actual behaviour

When I yank some text I see the following message in the command line: clipboard: error:. This only happens within a tmux window. If I run nvim from iTerm, the error does not occur.

### Expected behaviour

No error message and the text is copied to the system clipboard.

### Steps to reproduce using `nvim -u NORC`
The same thing happens although I don't see the error messages in the command line but if I look at :reg, I see the error messages in two registers.
```
nvim -u NORC

```

**Comment by justinmk** [comment]
Cc @mhinz

**Comment by pdoak** [comment]
On rebooting this issue seems to have resolved itself. On will keep monitoring to see if it returns.

**Comment by ppiet** [comment]
Same issue here, and rebooting does not help. Any hints for how to debug this?

**Comment by ppiet** [comment]
The issue reproduces only in tmux, I suspect this might be caused by Plug 'roxma/vim-tmux-clipboard'. Nvm, apologies for the noise!
