### ISSUE TITLE
Possible memory leak in clear_tv

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#5901]
It appears that lists like `[&l [1], *l]` may produce a memory leak preserving until mark&sweep GC run (https://github.com/neovim/neovim/pull/5826#issuecomment-271038993). Need allocator logging from #5119 to construct a unit test, fixing should be trivial if I am right.

**Comment by ZyX-I** [comment]
Do not actually see a leak, but see something strange in case of `[&l [], *l]`: unlike `[&l [1], *l]` it first frees the inner list and then all `listitem_T` objects. I would expect it first free first listitem_T and then the list and then second listitem_T what it does if list is non-empty.

**Comment by ZyX-I** [comment]
Actually it is right in case of `[&l [], *l]`: ordering is the result of that memory leak: it is `list_unref` of the outer list which frees the inner list while it should be freed by `clear_tv` earlier.

**Comment by ZyX-I** [comment]
This is why nobody saw the leak: can’t construct an example right now which will show the leak and not just unexpected ordering of frees.

**Comment by justinmk** [comment]
Does https://github.com/neovim/neovim/pull/5826#issuecomment-270981109 suggest that we need another build type in the travis matrix?

**Comment by ZyX-I** [comment]
@justinmk Problem was reproducible on RelWithDebInfo build with sanitizers enabled (though I think it was not necessary), but not on debug build (actually I have no idea why, debug build must’ve also been affected by that `assert()` failure). Are not travis builds debug-only with other types built by quickbuild?

**Comment by justinmk** [comment]
@ZyX-I Right, I'm thinking we should have a RelWithDebInfo build running sanitizers.
