### ISSUE TITLE
"E724: unable to correctly dump variable with self-referencing container" when using incsearch

### ISSUE THREAD

**Issue by george-b** [neovim/neovim#5902]
- `nvim --version`: NVIM 0.2.0-dev
- Vim (version: ) behaves differently? Yes no error
- Operating system/version: SLES 11 SP3
- Terminal name/version: PuTTY/ tmux
- `$TERM`: screen-256color

### Actual behaviour

When searching with the incsearch plugin this error is thrown on every character that is typed, e.g.

```vim
function incsearch#_go[5]..<SNR>48_get_input[12]..105[4]..103[1]..119[9]..118[10]..117[23]..116[22]..115[8]..88[2]..168[1]..<SNR>58_call[3]..381[1]..<SNR>87_on_searching[2]..<SNR>87_on_char[26]..<SNR>87_move_cursor[19]..<SNR>49_dictfunction, line 1 Vim(let):E724: unable to correctly dump variable with self-referencing container/b
function incsearch#_go[5]..<SNR>48_get_input[12]..105[4]..103[1]..119[9]..118[10]..117[23]..116[22]..115[8]..88[2]..168[1]..<SNR>58_call[3]..381[1]..<SNR>87_on_searching[2]..<SNR>87_on_char[26]..<SNR>87_move_cursor[19]..<SNR>49_dictfunction, line 1 Vim(let):E724: unable to correctly dump variable with self-referencing container/ba
function incsearch#_go[5]..<SNR>48_get_input[12]..105[4]..103[1]..119[9]..118[10]..117[23]..116[22]..115[8]..88[2]..168[1]..<SNR>58_call[3]..381[1]..<SNR>87_on_searching[2]..<SNR>87_on_char[26]..<SNR>87_move_cursor[19]..<SNR>49_dictfunction, line 1 Vim(let):E724: unable to correctly dump variable with self-referencing container/bar
```

### Expected behaviour

No errors to be thrown

### Steps to reproduce using `nvim -u NORC`

```
git clone https://github.com/haya14busa/incsearch.vim.git ~/src/incsearch
nvim -u NORC
:set rtp+=~/src/incsearch
:source ~/src/incsearch/plugin/incsearch.vim
:source ~/src/incsearch/autoload/incsearch.vim
:nmap / <Plug>(incsearch-forward)
/<Type any character>
```

I don't recall seeing this when testing PR #5826 some time ago so I guess it's one of the more recent commits that introduces this.

It seems a similar report of seeing this error came up here:

https://github.com/neovim/neovim/pull/5529#issuecomment-269512372

Sorry for the hasty report I have to dash, I'll take a more in depth look at this later and follow up with any details I can provide.

**Comment by tonyhb** [comment]
+1 also getting this in 40c76741c187f5bf35101e65252226030d5b72e5

**Comment by justinmk** [comment]
@tonyhb Are you using incsearch.vim, or some other plugin is also doing this? 

FWIW, the reasoning for the error is explained in the [comments here](https://github.com/neovim/neovim/pull/5529#issuecomment-271083517). incsearch.vim could use `get()` to get the name of a dict function.

**Comment by tonyhb** [comment]
Yup, it's all incsearch :)

**Comment by michaelmior** [comment]
Without knowing the details, whether or not this could be fixed in incsearch, it would be nice if it were possible to retain compatibility with vim if possible.

**Comment by xeyownt** [comment]
For info, as proposed by ZyX-l [here](https://github.com/neovim/neovim/pull/5529#issuecomment-271084596), the issue can be silented like this in haya14busa/incsearch.vim@213994f:

``` diff
 function! s:dictfunction(dictfunc, dict) abort
-  let funcname = '_' . matchstr(string(a:dictfunc), '\d\+')
+  silent! let funcname = '_' . matchstr(string(a:dictfunc), '\d\+')
```

I guess this does not fix the underlying problem, but at least it works.

**Comment by george-b** [comment]
This problem no longer presenting after https://github.com/haya14busa/incsearch.vim/pull/134.

As I  and others have only reported this with the incsearch plugin I'm closing this, maintainers feel free to re-open of course if you wish.

**Comment by justinmk** [comment]
For reference, to change the behavior in nvim so that it doesn't give an error, @ZyX-I gave the steps here: https://github.com/neovim/neovim/pull/5529#issuecomment-271541590

If the issue comes up frequently we can revisit that.
