### ISSUE TITLE
command modifiers should accept a range

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5911]
- Vim (version: 8) behaves differently? no

in #4449 @dumblob wanted to make the `K` mapping in manpages open in a vertical split. That works fine, except until you try it with a count. This is because `:vertical` does not accept a range, I think it should as then it would become very easy to map `:vertical Man`.

I also opened vim/vim#1362

**Comment by ZyX-I** [comment]
Commented on the Vim issue.

**Comment by ZyX-I** [comment]
I agree with Bram here. Discussion goes in vim/vim#1362.
