### ISSUE TITLE
inccommand range errors

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#5912]
- `nvim --version`: v0.2.0-341-gca7a5c0
- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.12.2
- Terminal name/version: iTerm 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
with `'inccommand'` set to `split` or `nosplit`, typing something like `:10s` gives a range error.

### Expected behaviour
 I don't think it should, as this makes it difficult to pass a count to `:split`. Even if that is something not usually done interactively, it feels unclean.

### Steps
1. `nvim -u NORC`
2. `:set inccommand=nosplit`
3. `:10s`

**Comment by jamessan** [comment]
I can't reproduce that locally with v0.2.0-371-g8a596202.
