### ISSUE TITLE
CCTreeLoadDB cscope.out - results in errors

### ISSUE THREAD

**Issue by alexbriskin** [neovim/neovim#5922]
- `nvim --version`:0.1.6
- Vim (version: ) behaves differently? NO - tested on 7.4.52
- Operating system/version:Ubuntu 14.04
- Terminal name/version:GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
- `$TERM`:xterm

### Actual behaviour
Error detected while processing function 166[4]..140[6]..141[21]..100[8]..39:
line    1:
E716: Key not present in Dictionary: <fe>
E15: Invalid expression: self.mappings[submatch(1)]
Error detected while processing function 166[4]..140:
line    6:
E171: Missing :endif

### Expected behaviour
cscope.out should be read by CCTree plugin
### Steps to reproduce using `nvim -u NORC

`

```
nvim -u NORC

```
![2 1](https://cloud.githubusercontent.com/assets/16564519/21798560/cade66ea-d71d-11e6-891c-3ba6fada066d.png)
![cctrree_nvim-u_norc](https://cloud.githubusercontent.com/assets/16564519/21798631/30c1731c-d71e-11e6-9a37-2a8a3f67d189.png)

**Comment by justinmk** [comment]
> cscope.out should be read by CCTree plugin

Report to the maintainer of CCTree plugin, not to nvim/vim.
