### ISSUE TITLE
Terminal width ignores foldcolumn

### ISSUE THREAD

**Issue by Melkor333** [neovim/neovim#5923]
- `nvim --version`:NVIM 0.1.7 (brew install)
- Vim (version: ) behaves differently? Doesn't have native shell integration
- Operating system/version: macOS Sierra 10.12.2
- Terminal name/version: iTerm2 3.0.13
- `$TERM`:xterm-256color

### Actual behaviour

When I have `set foldcolumn=1`, it isn't calculated into the dimensions of a terminal. Every open terminal is one character too wide.
Other than `set relativenumber`, the foldcolumn variable is used in every neovimterminal (When I open a new terminal, it has the column spacing set by foldcolumn, but the relative numbers are left away. I guess this is intended...?)

### Expected behaviour

When foldcolumn is set, the terminal width should be equally lower.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
echo $COLUMNS
exit
:set foldcolumn=1
:term
echo $COLUMNS
```

the second time $COLUMNS should be one less than the first time.

**Comment by justinmk** [comment]
Seems to be fixed on current HEAD. Related:https://github.com/neovim/neovim/pull/9551
