### ISSUE TITLE
Ctrl + left/right arrow prints question marks in terminal

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#5925]
- `nvim --version`:

```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: archlinux64
- Terminal name/version: termite/roxterm (vte) and xterm
- `$TERM`: xterm / xterm-256color

### Actual behaviour

Using `Ctrl` + left or right arrow keys inside the terminal emulator renders strange question marks with broken width.

### Expected behaviour

Word-wise navigation as common for readline-based programs.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
Ctrl + left arrow
```

**Comment by rjmill** [comment]
This is an issue with the neovim terminal emulator. For certain key combinations, there are problems translating from vim's internal representation of keys to terminal keycodes. It's being worked on here: https://github.com/neovim/neovim/pull/5014

**Comment by justinmk** [comment]
@languitar Can you try #5014 ?
