### ISSUE TITLE
Make `set mouse=` or `set mouse=c` the default

### ISSUE THREAD

**Issue by mmikowski** [neovim/neovim#5938]
- `nvim --version`:
```
VIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/build/config -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/src -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/.deps/usr/include -I/usr/include -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/build/src/nvim/auto -I/build/neovim-_7RAuS/neovim-0.1.5ubuntu1+git201701121145+3046+22~ubuntu16.10.1/build/include
Compiled by root@lgw01-38

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently?
Terminal cut and paste in 7.4.1829 (and all other known prior version) works, where it doesn't work on neovim.

- Operating system/version:
```bash
$ uname -a
Linux wilddogpro 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Terminal name/version:
```bash
$ konsole -v
Qt: 5.6.1
KDE Frameworks: 5.26.0
Konsole: 16.04.3
```

- `$TERM`:
```bash
$ konsole -v
Qt: 5.6.1
KDE Frameworks: 5.26.0
Konsole: 16.04.3
```

### Actual behaviour

X cut and paste does not work as it does in Vim versions < 8.  I cannot use the mouse to select from the terminal and paste elsewhere. This works fine in Vim.  This stopped me from adopting neovim for over **12 months** after I started *paying* for it.  As a drop-in replacement for VIM, it **failed** because of this one setting, and I spent hours trying to solve this variation.

### Expected behaviour

X cut and paste should work as in Vim <8.  I should be able to use the mouse to select and copy text.
This would be consistent with the vast majority of vim installations, as Mac tends to only ship ancient versions of frickn everything by default (vim 4, prolly), and Linux distros haven't yet widely adopted version 8.

### Steps to reproduce using `nvim -u NORC`

``` bash
$ nvim -u NORC

# 1. Select text with cursor
# 2. Press RMB and pray for drop down menu
# 3. Cuss for 1-2 minutes because the #@!$%! context menu never appears
```

### Solution

Make `set mouse=` or `set mouse=c` the default as with all prior versions of vim.

**Comment by justinmk** [comment]
One problem is that `set mouse=` isn't a good default for GUIs; however `:h gui-mouse` makes yet another exception for that. 

In any case we should only default to `set mouse=a` if we are certain the clipboard works. 

> This stopped me from adopting neovim for over 12 months

If nvim showed its own right-click menu that had copy/paste clipboard options, would that have avoided your confusion? If nvim showed a message like `See ":help 'mouse'" to change mouse behavior` during mouse activity, would that have been enough of a hint?

**Comment by fmoralesc** [comment]
👍 to @justinmk's idea of a right click popup menu (a menu system is overdue).

**Comment by mmikowski** [comment]
@justinmk @fmoralesc Either a drop-down menu or `See ":help mouse" to change mouse behavior` would certainly have helped in either case.  I do believe that changing this default behavior would help Neovim adoption and support.

**Comment by justinmk** [comment]
@mmikowski Can you try:

    set mouse=a mousemodel=popup

and

    set mouse=a mousemodel=popup_setpos

Does that improve things? What's still missing?

**Comment by fmoralesc** [comment]
@justinmk I think @mmikowski would wants nvim to pass the right click to the terminal when you change `mousemodel` to `popup*`. Neither nvim nor vanilla vim do this, I think.

**Comment by justinmk** [comment]
With iTerm2 mousemodel=popup does show the terminal's right-click menu.

**Comment by fmoralesc** [comment]
Neither xterm (duh), most VTE-based terminals (gnome-terminal, xfce4-terminal) or konsole do it. Oddly enough, [sakura](http://www.pleyades.net/david/projects/sakura/) does.

**Comment by justinmk** [comment]
Ok, cancel that then.

**Comment by fmoralesc** [comment]
I wish it was that easy! I think nvim needs some kind of story for a menu system, then a popup menu for the terminal could be implemented that worked as @mmikowski expects; in that case I think `mousemodel=popup_setpos` should be made default.

**Comment by fmoralesc** [comment]
For reference: sakura does it because it swallows all right presses! Not a great model to follow.

**Comment by mmikowski** [comment]
@fmoralesc @justinmk I think the right way to look at this is as a business.  The question I would apply is "what change would result in the greatest increase of revenue and support for neovim?"  The answer *for me* was that X cut-n-paste was painfully confusing to set up, and I could see that being a major and common barrier to meet our business objectives!

I don't think we need to over complicate the issue.  I think a fast pretty-good solution is better than something that proceeds at a Perl6 pace :).  Perhaps the best solution would be both a doc update *and* a change to `set mouse=` so the default behavior remains as people expect *and* those looking for more have an easy-to-find solution.  Maybe just a link in `README.md` to the Wiki page.

**Comment by justinmk** [comment]
There are lots of things going on at the moment, we'll get to this. We had 7 releases in 1 year so I don't think it's comparable to perl6.

**Comment by mmikowski** [comment]
@justinmk No offence meant with the Perl6 comment!  :)

**Comment by mmikowski** [comment]
@justinmk I tried as requested:

```vim
set mouse=a mousemodel=popup
set mouse=a mousemodel=popup_setpos
```

*Does that improve things? What's still missing?*
Cutting and pasting using the X clipboard doesn't work with either (LMB click results in nothing).  So it doesn't improve things.

**Comment by justinmk** [comment]
> require that vim and neovim have the same behaviors.

For which behaviors? 
Not even Vim 8 has the same behavior as Vim 7 under certain conditions, so that's difficult.

**Comment by mmikowski** [comment]
@justinmk 

>> require that vim and neovim have the same behaviors.

> For which behaviors?
> Not even Vim 8 has the same behavior as Vim 7 under certain conditions, so that's difficult.

RMB does not open a X-clipboard menu with either setting.  Using `set mouse=` I'm able to get consistent behavior across all my devices.

**Comment by jamessan** [comment]
> RMB does not open a X-clipboard menu with either setting.

Right, because `mouse=a` makes the terminal pass mouse handling through to (n)vim.

> Using set mouse= I'm able to get consistent behavior across all my devices.

Ok, so set that in your vimrc / init.vim.  As Justin hinted at earlier, even Vim 8 sets `mouse=a` by default (when no user vimrc is present).  It's best to be explicit about your preferences.

**Comment by mmikowski** [comment]
> Ok, so set that in your vimrc / init.vim. As Justin hinted at earlier, even Vim 8 sets mouse=a by default (when no user vimrc is present). It's best to be explicit about your preferences.

No need to be pedantic @jamessan, I am far from a neophyte.  My vimrc is 162 lines long and is network shared over dozens of machines. **My** issue was resolved weeks ago by adding one line. The issue is figuring out what that line should be was a *major* PITA and a blocker for my universal adoption of neovim for a year.

My concern is that we are limiting adoption and financial support of neovim by not using defaults consistent with the vast majority of vim installations in use today and at least for another 6 months.  A quick search of neovim issues shows that I am not alone.

**Comment by jamessan** [comment]
> The issue is figuring out what that line should be was a major PITA

Understood.  I saw many similar complaints when I shipped the Vim update to Debian that changed this behavior, and I provided feedback to Bram then about why this isn't a good default.  I've done the same within Neovim and we will look into improving the default behavior.

> My concern is that we are limiting adoption and financial support of neovim by not using defaults consistent with the vast majority of vim installations in use today and at least for another 6 months.

First, I don't know why you keep harping on the money aspect of things.  That's not a driving factor in neovim development.  We are not a business.

Second, we explicitly deviate from "defaults consistent with the vast majority of vim installations" in many ways, ideally in ways that improve the user experience.  Do those choices always work out well?  No, but we use the feedback to inform our decisions going forward.

We understand that there are improvements to make here and will get to them in due time.

**Comment by jamessan** [comment]
@justinmk In Vim, `'mousemodel=popup*` only works in the GUI.

**Comment by mmikowski** [comment]
@jamessan thanks for the response.  You see my point.  Let me clarify one aspect however:

> First, I don't know why you keep harping on the money aspect of things. That's not a driving factor in neovim development. We are not a business.

Ah, but neovim *is* a business. If contributors donate enough the developers can focus full-time on the project and accelerate adoption and support.  It's a virtuous cycle, and neovim can either leverage it or lose it to other competitors like vim 8.  It's not about "making money" but achieving a goal, and money is an important tool to help us get there.

Put another way, if money is *not* a driving factor, then how do I get the $340 I've contributed to neovim back?  Right :)

**Comment by justinmk** [comment]
FWIW, the funding has undoubtedly accelerated the progress of the project. Personally I think the "skeleton crew" model of most open source projects is bad for open source, and I hope that OSS funding becomes more common. But if this were a business the P&L would be grim :)

**Comment by mmikowski** [comment]
Thanks @justinmk and @jamessan!

**Comment by cjxgm** [comment]
> I should be able to use the mouse to select and copy text.

Hold down <kbd>shift</kbd> and you can use mouse to select and copy text.

With <kbd>shift</kbd> held down, both Xterm and gnome-terminal stops passing mouse handling through to TUI programs. I assume iTerm and iTerm2 do the same thing.

Is this so rarely known?

**Comment by fmoralesc** [comment]
The contextual menu (which blocks a better solution for this) could be reimplemented as a plugin once floating windows (https://github.com/neovim/neovim/pull/6619) and https://github.com/neovim/neovim/pull/6322 are merged.

**Comment by mmikowski** [comment]
@cjxgm  I will try the shift key today.  This may be a simple and good solution but it does not appear discoverable.

**Comment by tbodt** [comment]
@cjxgm iTerm does the same thing but with option.

**Comment by lourenko** [comment]
@cjxgm Is there another form to select text without using shift (but with same effect)?
> Hold down shift and you can use mouse to select and copy text.

**Comment by justinmk** [comment]
I am trying this mapping:

    nnoremap <M-LeftMouse> <Cmd>set mouse=<Bar>autocmd CursorMoved * ++once set mouse=nv<CR>

I think this could be a good way to have 'mouse' enabled by default while still providing an ergonomic, platform-generic way to disable the mouse temporarily.
