### ISSUE TITLE
can not use {value} in return statement.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#5945]
I have test in both vim and neovim. both of them have this issue, maybe is a bug.
here is a example:
I have a foo.vim in autoload:
autoload/test/foo.vim
```viml
fu! test#foo#test()
    return 1
endf
```
```viml
fu! Test(a)
     try
        return test#{a:a}#test()
     catch /^Vim\%((\a\+)\)\=:E117/
        return 0
    endtry
endf
```
then `call Test('foo')` does not work.

but if I change Test() to 
```viml
fu! Test(a)
    let a = 0
     try
        let a = test#{a:a}#test()
     catch /^Vim\%((\a\+)\)\=:E117/
    endtry
    return a
endf
```

then `echo Test('foo')` show me 1.

**Comment by justinmk** [comment]
The `{foo}` thing is really not a recommended feature of VimL. Its use is discouraged.

**Comment by ZyX-I** [comment]
I.e. try changing to `return call('test#' . a:a . '#test', [])`: Vim 7.\* has enough features to omit using curly braces names (specifically `call()` and indexing a dictionary: `g:['test#' . a:a . '#test']`). Though it is first time I hear about deprecating them.

Beware that `call('Test#' . a:a . '#test', [])` will not work if `Test#foo#test` is a variable with function reference in it, but `Test#{a:a}#test` should work.

**Comment by ZyX-I** [comment]
How `Test('foo')` does not work? I see it working perfectly, but failing to catch exception with e.g. `Test('bar')`.

**Comment by wsdjeg** [comment]
> How Test('foo') does not work?

oh, sorry, `Test('foo')` works well, but we can not catch the exception with `Test('bar')`.
