### ISSUE TITLE
terminal + ZSH shell visual bug

### ISSUE THREAD

**Issue by whitecolor** [neovim/neovim#5958]
- `nvim --version`: 0.2.00dev
- Vim (version: ) behaves differently?
- Operating system/version: Windows 10 Ubuntu bash
- Terminal name/version: https://github.com/mintty/wsltty (the same in standard bash terminal)
- `$TERM`: xterm-256color 

I use [ZSH](https://github.com/robbyrussell/oh-my-zsh), solirized ZSH_THEME="agnoster" theme

### Actual behaviour
Command line prefix seem to be shifted for one character) that causes such visual bug:
![image](https://cloud.githubusercontent.com/assets/736697/21965665/64f3d41a-db86-11e6-8deb-c44f2d7bded0.png)

### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/736697/21965630/b9f124b4-db85-11e6-9dbe-658c143e0c73.png)

with tmux:
![image](https://cloud.githubusercontent.com/assets/736697/21965740/05f33526-db88-11e6-9137-cd38885d8bec.png)

### Steps to reproduce 
- Install neovim on Ubuntu bash shell
- install `apt-get install zsh`
- set ` ZSH_THEME="agnoster"` in `~/.zshrc`
- `:terminal` in nvm, launch `zsh` shell

**Comment by justinmk** [comment]
Thanks for the report. Is the cursor also "off by one"? I think this is the same as https://github.com/neovim/neovim/issues/4976.

**Comment by whitecolor** [comment]
Going to be fixed soon?

**Comment by justinmk** [comment]
Explained in the linked issue.
