### ISSUE TITLE
Cannot use ctrl space

### ISSUE THREAD

**Issue by blelump** [neovim/neovim#5960]
Hi!

I have had `<NUL>` character assigned to the `g:UltiSnipsExpandTrigger` variable, but somehow it stopped to work properly (see steps to reproduce below). I've done a neovim update a week ago or so and today updated it again, but it didn't help. May it be related to the neovim itself?

- `nvim --version`: NVIM 0.2.0-dev; Build type: RelWithDebInfo neovim-0.1.7ubuntu1+git201701151345+3058+23~ubuntu14.04.1
- Vim (version: 7.4 (2013 Aug 10, compiled Aug 05 2016 16:48:20)) -- in Vim it works or at least Ctrl-space emits `^@`
- Operating system/version: Ubuntu 14.04.5
- Terminal name/version: gnome-terminal
- `$TERM`: xterm

### Actual behaviour

`Ctrl + space` emits space character in insert mode

### Expected behaviour

`Ctrl + space` emits `^@` character in insert mode

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
enter insert mode
type Ctrl-V
type Ctrl-space
Space character is the output whereas I'd expect ^@
```

**Comment by justinmk** [comment]
> I have had `<NUL>` character assigned

Assigned how? Can you try `nnoremap <c-space> ...`?

> Ctrl + space emits space character in insert mode

That's what nvim does if it doesn't find a mapping to input. It's a known (cosmetic) issue (which is in the issue tracker somewhere). It you actually mapping the chord to something, it won't do that.

> May it be related to the neovim itself?

I believe it's because we upgraded libtermkey recently and it made a change to improve recognition of ctrl-space.

**Comment by jamessan** [comment]
This is the change that happened in libtermkey:

<details><summary><pre>
revno: 358
committer: Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
branch nick: libtermkey
timestamp: Tue 2015-12-29 12:37:19 +0000
message:
  Correct handling of ASCII NUL to imply Ctrl-Space</pre></summary>
diff:

```diff
=== modified file 't/02getkey.c'
--- t/02getkey.c        2014-03-05 01:11:45 +0000
+++ t/02getkey.c        2015-12-29 12:37:19 +0000
@@ -6,7 +6,7 @@
   TermKey   *tk;
   TermKeyKey key;

-  plan_tests(31);
+  plan_tests(35);

   tk = termkey_new_abstract("vt100", 0);

@@ -69,6 +69,14 @@
   is_int(key.code.sym,    TERMKEY_SYM_ESCAPE,  "key.code.sym after Ctrl-Escape");
   is_int(key.modifiers,   TERMKEY_KEYMOD_CTRL, "key.modifiers after Ctrl-Escape");

+  termkey_push_bytes(tk, "\0", 1);
+
+  is_int(termkey_getkey(tk, &key), TERMKEY_RES_KEY, "getkey yields RES_KEY after Ctrl-Space");
+
+  is_int(key.type,           TERMKEY_TYPE_UNICODE, "key.type after Ctrl-Space");
+  is_int(key.code.codepoint, ' ',                  "key.code.codepoint after Ctrl-Space");
+  is_int(key.modifiers,      TERMKEY_KEYMOD_CTRL,  "key.modifiers after Ctrl-Space");
+
   termkey_destroy(tk);

   return exit_status();

=== modified file 'termkey.c'
--- termkey.c   2015-03-04 23:29:11 +0000
+++ termkey.c   2015-12-29 12:37:19 +0000
@@ -729,7 +729,13 @@

 static void emit_codepoint(TermKey *tk, long codepoint, TermKeyKey *key)
 {
-  if(codepoint < 0x20) {
+  if(codepoint == 0) {
+    // ASCII NUL = Ctrl-Space
+    key->type = TERMKEY_TYPE_KEYSYM;
+    key->code.sym = TERMKEY_SYM_SPACE;
+    key->modifiers = TERMKEY_KEYMOD_CTRL;
+  }
+  else if(codepoint < 0x20) {
     // C0 range
     key->code.codepoint = 0;
     key->modifiers = 0;
```
</details>

**Comment by justinmk** [comment]
Assuming `nnoremap <c-space>` works, I don't see a problem here.

**Comment by blelump** [comment]
@justinmk , @jamessan , thanks guys, binding to `<c-space>` works !
