### ISSUE TITLE
[Suggestion] Auto insert when bracketed paste in normal mode, or replace when in visual mode

### ISSUE THREAD

**Issue by thalesmello** [neovim/neovim#5968]
- `nvim --version`:

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170112-23131-1s2gdp8/neovim-0.1.7/build/config -I/tmp/neovim-20170112-23131-1s2gdp8/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170112-23131-1s2gdp8/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170112-23131-1s2gdp8/neovim-0.1.7/build/include
Compiled by thales@Thaless-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

- Operating system/version: Mac OS X
- Terminal name/version: iTerm2 v3
- `$TERM`: screen-256color

### Actual behaviour

When I press `Cmd+v` in normal mode, Vim actually interprets the keys as raw input.

Plugins such as [bracketed-paste-mode](https://github.com/ConradIrwin/vim-bracketed-paste) do just that when in normal mode.

However, the plugin above doesn't work by processing the bracketed escape sequences. I figured this because of the `'bracketed-paste-mode'` option, which apparently only works in insert mode.

### Expected behaviour

I expect the bracketed paste to automatically enter insert mode when I press `Cmd+v`

### Steps to reproduce using `nvim -u NORC`

Suppose that I have `ccHello World`, and press `Cmd+v` in normal mode, I expect to see the raw text in the buffer.

However, it's interpreted as a raw command, yielding `Hello world`.

**Comment by jamessan** [comment]
> When I press Cmd+v in normal mode, Vim actually interprets the keys as raw input.

Cmd+v doesn't do anything in nvim, so I'm assuming that's something your terminal recognizes or you've mapped.  Either way, yes, Vim interprets it as input.  That's what it is.

> I expect the bracketed paste to automatically enter insert mode when I press Cmd+v

Why?  That's pretty presumptuous.  What if I'm pasting a command?  If you want it to paste in insert mode, then enter insert mode.

Bracketed paste just allows us to detect the contents of a paste and toggle the `'paste'` option during it, so that mappings aren't expanded, stair-case indentation doesn't occur, etc.

**Comment by justinmk** [comment]
Full control over paste behavior, including the feature requested here, will be enabled by https://github.com/neovim/neovim/pull/4448

**Comment by thalesmello** [comment]
@jamessan 

Bracketed paste is a special form of paste, which wraps the text with \e200 and \e201 (if I'm not mistaken about the code numbers).

Those codes get correctly interpreted by Vim 8.0, which allow for plugins such as `bracketed-paste-mode` to work. However, that same plugin does nothing in Neovim, as the scape sequences aren't passed down to the mappings. I imagines it was indeed the case because of [issue 937](https://github.com/neovim/neovim/issues/937), which implemented auto `set paste` in insert mode.

@justinmk That was exactly what I was looking for. Thank you for indicating it.

**Comment by jamessan** [comment]
@thalesmello Yes, the scripts don't see those sequences with nvim because nvim natively understands bracketed paste.
