### ISSUE TITLE
How to exit nested terminal with `<c-\><c-n>` instead of `<c-\><c-\><c-\><c-\><c-n>`?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#5978]
Currently, typing `<c-\><c-n>` exits terminal mode on the top-most terminal. If we have nested terminals and each nested terminal has an instance of NeoVim running, how can we have the opposite behavior so that typing `<c-\><c-n>` exits terminal mode of the deepest neovim instance that is focused?

The behavior would be like this:

- `<c-\><c-n>` would exit the deepest neovim instance's TERMINAL mode back to NORMAL mode. Pressing `<c-\><c-n>` again would do nothing.
- Switching to a text buffer window in that instance then going to INSERT mode, then typing `<c-\><c-n>` would exit INSERT mode back to NORMAL mode. Pressing `<c-\><c-n>` again would do nothing.
- To go one level up to the parent terminal neovim, we'd type `<c-\><c-\><c-n>`. Or, if we want to go two levels up at once, we'd type `<c-\><c-\><c-\><c-n>`.
- Once we are any level higher, typing `<c-\><c-n>` sends that same command to that level, as expected. It would behave the same as it did at the deepest level, but for the current level.
- To go a level deeper, we would focus that window in the current level, and press `a`, `i`, or etc. For example, if a branch of windows down the terminal neovim tree all are terminal buffers, then pressing `iiii` would traverse four levels deeper.
- As a bonus, if the lower levels are focused on terminal windows, then typing `2i` would go two levels deeper. In the case the deeper terminals aren't focused on terminal windows, then we go deeper until a terminal isn't focused, then silently fail.
- As a bonus, There'd be some way to style the `colorscheme` to reflect which level neovim is focused.
- As a huge bonus, There'd be a way to make this work with neovim instances that are inside SSH sessions of the parent neovim's terminal.

Is there some way to make this happen (at least the non-bonus parts)?

**Comment by trusktr** [comment]
This would be a huge workflow improvement for me. I really really like having the nested workspaces.

On a similar note, maybe NeoVim just needs a way to have nested tabs? That would be helpful too. It would also be very easy to make `<c-\><c-n>` focus on the parent tab group. However, this would still require the above bonus parts if it will work across SSH instances. I often find myself with a local parent neovim, and a child neovim via SSH, so the sub-tabs wouldn't work in that case, but I'd still like to interact the same way.

**Comment by trusktr** [comment]
Here's a shot of my outer neovim (local) and inner neovim (via SSH in the out neovim's terminal):

<img width="780" alt="screen shot 2017-01-19 at 5 40 02 pm" src="https://cloud.githubusercontent.com/assets/297678/22132360/65092c6c-de6e-11e6-8053-117683306b58.png">

If for some reason I need to ssh somewhere else and go another level deeper, I have to press `<c-\><c-\><c-\><c-n>` to exit the 3rd level's terminal each time, which is bothersome in the workflow.

**Comment by justinmk** [comment]
Isn't this covered by https://github.com/neovim/neovim/issues/3118? 

Can the presence of `$NVIM_LISTEN_ADDRESS` be used to create a mapping that works around the issue in the meantime?
