### ISSUE TITLE
How to input text into the terminal windows by vimscript

### ISSUE THREAD

**Issue by huawenyu** [neovim/neovim#5979]
I'm implement a neovim GDB frontend plugin base on python-client, but have a issue about inputting a text by vimscript into terminal windows and let it execute.

```
-----------------
window-1: source file
-----------------
window-2: terminal: running gdb
<gdb> 
-----------------
```

So here could I execute the following script and enter "next" into the terminal-gdb-window and make gdb execute command `next`?

```vim
function! GdbNext()
    let src = 0
    let currentWinNr = winnr()
    for nr in range(1, winnr('$'))
        if getwinvar(nr, "&buftype") == "terminal"
            silent exec nr . "wincmd w"
            exec ":norm next"
        endif
        silent exec currentWinNr . 'wincmd w'
    endfor
endfunction

map <F5> :call GdbNext()<CR>
```

**Comment by huawenyu** [comment]
Maybe we can use rpc-notify the event to GDB-python interface, but that require GDB-python block by calling asynio_obj.run_until_complete(run()).

**Comment by justinmk** [comment]
When a `:terminal` starts (also via `termopen()`), it creates a job, and the job id is given in `b:terminal_job_id` for convenience. The job can be read/written like any other job. Use `jobsend()` to write to a job. This will send the string "next" to the terminal job:

    call jobsend(b:terminal_job_id, "next\n")

**Comment by justinmk** [comment]
By the way, tarruda wrote a GDB integration here:

https://github.com/neovim/neovim/blob/master/contrib/gdb/neovim_gdb.vim

I suggest using that as a starting point.

**Comment by huawenyu** [comment]
I'm writing this GDB frontend which start from [tarruda](https://github.com/neovim/neovim/blob/master/contrib/gdb/neovim_gdb.vim)
https://github.com/huawenyu/neogdb.vim

More features like:
  - support breakpoints in local list, also disable breakpoints
  - support auto save/load breakpoints
  - support backtrace in quickfix
  - support auto break on functionname or file:linenumber
