### ISSUE TITLE
`:!command` does not handle bold characters

### ISSUE THREAD

**Issue by khwon** [neovim/neovim#5980]
- `nvim --version`: 0.1.7
- Vim (version: 8.0-194) behaves differently? Yes
- Operating system/version: macOS Sierra 10.12.2
- Terminal name/version: iTerm2 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
with `nvim -u NONE` and `:!man 2 chdir`, bold characters are printed out twice without bold attr
```
CHDIR(2)                    BSD System Calls Manual                   CHDIR(2)

N NA AM ME E
     c ch hd di ir r, f fc ch hd di ir r -- change current working directory

S SY YN NO OP PS SI IS S
     # #i in nc cl lu ud de e < <u un ni is st td d. .h h> >
```
### Expected behaviour
bold characters should be printed once, with bold attribute

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!man 2 chdir
```

**Comment by justinmk** [comment]
Thanks for the report. See https://github.com/neovim/neovim/issues/2958. This issue will be implicitly addressed by https://github.com/neovim/neovim/issues/5431 if/when `:!` is reworked internally to use `:term`.

Is there some reason you don't want to use `:te man 2 chdir` or `:Man 2 chdir` ?

**Comment by khwon** [comment]
`:te man 2 chdir` and `:Man 2 chdir` works currently, but it has different behavior with vim when I vertically split the screen via `:vs`.
It might be design decision, but in vim it opens in whole area not current buffer.
Also in default setting both for vim and nvim, shift+k maps to `:man `.

**Comment by justinmk** [comment]
`:Man` accepts modifiers, so `:tab Man foo` opens in a new tab if you want. (We'd like to give that behavior to `:te` in the future.)

**Comment by khwon** [comment]
Thanks a lot!
Now it works great (even better) after I remap shift-k via following code.
```
if has("nvim")
  map K :tab Man <C-R><C-W><CR>
endif
```

**Comment by justinmk** [comment]
Can also set keywordprg:

    :setlocal keywordprg=:tab\ Man
