### ISSUE TITLE
Messages from python calls get truncated

### ISSUE THREAD

**Issue by BonarBeavis** [neovim/neovim#5984]
- NVIM 0.2.0-dev
- Ubuntu-Gnome 16.10
- gnome-terminal
- xterm-256color

### Actual behaviour

Messages from python calls get truncated. 

```
...
File "/usr/local/lib/python3.5/dist-packages/tasklib/backends.py", line 281, in execute_command                                                                         
    raise TaskWarriorException(error_msg)                                                                                                                                 
tasklib.backends.TaskWarriorException: Using alternate .taskrc file /home/someone/.taskrc                                                                                  
Configu
```
### Expected behaviour

Message continues after `Configu`

**Comment by justinmk** [comment]
I see `...` so I'm guessing this is a bug with the `:!` throttling. Can you list the steps you took?

**Comment by BonarBeavis** [comment]
I inserted the `...` ...

It happens when I commit changes with the [taskwiki plugin](https://github.com/tbabej/taskwiki/issues/121). Something goes wrong there and I can not debug it, because of the truncated message.


![screenshot from 2017-01-21 18-16-41](https://cloud.githubusercontent.com/assets/3330855/22176287/20a371aa-e007-11e6-987e-bc21c7cf2074.png)

`:message` does not produce the output either.

**Comment by justinmk** [comment]
> :message does not produce the output either.

Ok, that confirms that "shell output throttling" is not the issue.

> Can I simulate somehow an error with the python provider to check if the message gets truncated too?

Yes, just do something python doesn't like:

```
:py3 print(foo)

Error detected while processing function provider#python3#Call:                                                  
line   18:                                                                                                       
Traceback (most recent call last):                                                                               
  File "<string>", line 1, in <module>                                                                           
NameError: name 'foo' is not defined
```

**Comment by BonarBeavis** [comment]
I can reproduce it:
`nvim -u NORC` and then `:py3 print(foo)` works fine, but when "foo" is replaced by a very long string the message gets truncated.

**Comment by justinmk** [comment]
@BonarBeavis How long? I tried a 2674 character string with `:py3 print()`, no output was truncated. What version of python 3 client does `:CheckHealth provider` report?

**Comment by BonarBeavis** [comment]
It works with 2674 characters in single line. Try this:
Copy this line following line:
Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...
Place the cursor on foo in `:py3 print(foo)` and paste the line about 20 times and the press `<CR>`

**Comment by BonarBeavis** [comment]
Output `:CheckHealth provider`

```markdown
health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xclip

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13
```

**Comment by tbabej** [comment]
I wanted to report this behaviour some time ago, but then I found the following pull request in `python-client`

https://github.com/neovim/python-client/pull/221

maybe this is root of the problem? (I performed no testing, I just put this off until the pull gets merged :))

**Comment by justinmk** [comment]
I don't see how that PR would fix this issue. @tbabej do you have a better way to reproduce the reported issue here?

**Comment by justinmk** [comment]
> nvim -u NORC and then :py3 print(foo) works fine, but when "foo" is replaced by a very long string the message gets truncated.

That actually happens in the python REPL as well, the limit of 200 for the NameError comes from python itself.
