### ISSUE TITLE
Weird behavior for feedkeys() and nvim_input()

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#5987]
- `nvim --version`: 0.1.7 and  v0.2.0-451-g10864cd9              
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour

- `feedkeys()` doesn't  respect special keys in the command line.
- `nvim_input()` causes redraws.

### Steps to reproduce using `nvim -u NORC`

The following was tested over the defaults for `wildmenu` and relevant settings, but I forgot to take screenshots using `-u NORC`. 

As a sanity test:
```
noremap <Tab> :echom "hi!"<cr>
```
![captura de pantalla de 2017-01-21 19-16-35](https://cloud.githubusercontent.com/assets/221465/22176591/5bd1c838-e00e-11e6-97ad-6526ca1ef41e.png)

which is expected.
```
noremap <RightMouse> :<c-i>
noremap <RightMouse> :call feedkeys(":\<tab>")<cr>
noremap <RightMouse> :exe ':call feedkeys(":\<tab>")'<cr>
````
all have the same output:
![captura de pantalla de 2017-01-21 19-17-01](https://cloud.githubusercontent.com/assets/221465/22176595/6b7ab614-e00e-11e6-87af-7f01c21d9278.png)
which means feedkeys isn't sending `<C-I>` in a way that triggers the completion.

```
noremap <RightMouse> :call nvim_input(":<tab>")<cr>
```
![captura de pantalla de 2017-01-21 19-17-20](https://cloud.githubusercontent.com/assets/221465/22176598/742ed4ac-e00e-11e6-8a43-6bd6cdea64c5.png)

which doesn't correspond to the expected behavior:
![captura de pantalla de 2017-01-21 19-22-56](https://cloud.githubusercontent.com/assets/221465/22176622/25a2f4ac-e00f-11e6-9d74-a8f43a767578.png)

Moreover, if I send two consecutive `<tab>`s, we can see the completion wasn't finalized, the wildmenu was simply redrawn over:

```
noremap <RightMouse> :call nvim_input(":<tab><tab>")<cr>
```
![captura de pantalla de 2017-01-21 19-17-46](https://cloud.githubusercontent.com/assets/221465/22176601/89c9c9c0-e00e-11e6-82fe-8ba3c6baa87a.png)

**Comment by fmoralesc** [comment]
To keep the wildmenu active, I need to keep the right button pressed, which is just slightly odd, and I can't figure out a way to prevent it.

**Comment by justinmk** [comment]
First can you compare the feedkeys behavior to Vim? It has tons of options that affect the way it works.

**Comment by fmoralesc** [comment]
vim has the same behavior for `feedkeys()`:
![captura de pantalla de 2017-01-21 19-50-11](https://cloud.githubusercontent.com/assets/221465/22176844/e4e0bdb0-e012-11e6-85db-635ce945df98.png)

**Comment by ZyX-I** [comment]
This is expected: first, to make `feedkeys()` work you must supply `t` as a second argument (so input is treated exactly as typed). Second, `feedkeys()` is not needed: see `:h 'wildcharm'`. I have no idea why it was needed to have both `&wildchar` and `&wildcharm` setting (in fact, why it was needed to have *any* of these settings, this makes creating robust mappings with behaviour like you want rather tricky) and set only the second by default, but I live fine with both `&wildchar` and `&wildcharm` set to 9 (tab character).

I think that you need code like

```VimL
nnoremap <expr> lhs [execute(':set wildcharm=9'), ":\t"][1]
```

(basically, set `&wildcharm` to tab and then do what you want).

**Comment by fmoralesc** [comment]
Thanks for the heads up, @ZyX-I . I wasn't really that worried about the behavior of `feedkeys()`, but with that of `nvim_input()` (I was using `feedkeys()` as a contrast) here. However, @justinmk seems to be right that it is caused by some redrawing logic, and since that seems to be a known issue I'll close this since it doesn't seem to provide any new info.
