### ISSUE TITLE
Unexpected character after update

### ISSUE THREAD

**Issue by dikiaap** [neovim/neovim#5990]
- `nvm --version`: NVIM 0.2.0-dev
- VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 18 2017 12:42:32)
- Operating system/version: Ubuntu
- Terminal name/version: lxterminal, tested in tty too
- `$TERM`: xterm-256color

I was updating neovim and this character suddenly appear. Before updating, this isn't happen.
Tested in vim, all is fine.

![screenshot from 2017-01-22 10-01-13](https://cloud.githubusercontent.com/assets/8542502/22179596/1484cc8c-e08b-11e6-9ab8-c83c1bbe4012.png)
![screenshot from 2017-01-22 10-01-00](https://cloud.githubusercontent.com/assets/8542502/22179597/15498a68-e08b-11e6-9451-cb5778505feb.png)

**Comment by jamessan** [comment]
That's probably due to ef753a76.  If you put `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` in your init.vim, does that fix the problem?

**Comment by justinmk** [comment]
Yes, your terminal should ignore unknown sequences.

**Comment by justinmk** [comment]
@dikiaap What does `echo $VTE_VERSION` report? Also if you can find out what version of libvte your system uses, please include that.

**Comment by dikiaap** [comment]
@justinmk Already fixed this. I did `echo $VTE_VERSION` command and there is nothing results

**Comment by dikiaap** [comment]
libvte-2.19-0 Version 0.42.5-1ubuntu1
libvte9 Version 1:0.28.2-5ubuntu3

**Comment by kantsdog** [comment]
Just wondering, why has this been marked closed? Is `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` the final solution? Respectfully, it seems to me like it would be good to not have user-configuration be the fix.

**Comment by jszakmeister** [comment]
@kantsdog It's not that simple.  Terminals have all kinds of brokenness, and this is one of them.  Many support changing the cursor shape, but do it in one of two different ways.  And while there are ways to query whether or not a terminal supports the feature, most do not implement the mechanism.  So we're stuck with user configuration until the situation improves. :-(

**Comment by justinmk** [comment]
I made a change that enables cursor shape by default. It looks like the state of terminals having even basic fallback behavior is worse than expected, so I'll switch it back to opt-in instead of opt-out.

I guess querying will be the only way this can be automatically enabled, because of all the broken terminals out there.

**Comment by kantsdog** [comment]
@justinmk Thanks for changing it back to the default. Had I not found the solution in this thread, Neovim would have become unworkable for me and people in my situation, so switching it back to opt-in seems like a good call from my perspective.

@jszakmeister Thanks for the helpful and informative explanation of terminals in all their brokenness.

**Comment by prlz77** [comment]
Thank you very much. I have also realized that unsetting TERM when calling nvim does also "fix" this issue.

**Comment by jamessan** [comment]
@prlz77 Unsetting TERM is a very heavy-handed approach to "fix" this.  Just add `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` in your init.vim

**Comment by prlz77** [comment]
@jamessan I changed it when I discovered this thread. Thank you anyway!

**Comment by rsleiman** [comment]
@jamessan It worked as you suggested. Thank you!.

**Comment by prlz77** [comment]
The problem is back after the last update.  

I am using terminator and TERM=xterm-256color. My nvim version is v0.2.0-dev.

It persists even with $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0.

![nvim](https://cloud.githubusercontent.com/assets/1070504/24743893/4a22ca38-1ab0-11e7-9afc-ee7bd9d25964.png)

**Comment by justinmk** [comment]
Please see https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by prlz77** [comment]
Thank you, the problem persisted even with `set guicursor=` because a plug-in was overriding it. 

I solved it with` export VTE_VERSION="100"` (https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal)

**Comment by tarciozemel** [comment]
I'm still having this issue of unexpected weird chars every time I type some command or change for Insert Mode.

Sadly, I've already tried all the solutions shown here and nothing.

![captura de tela de 2017-08-09 14 32 39](https://user-images.githubusercontent.com/133777/29135179-a52385be-7d0f-11e7-8b88-0555cfd4eb5e.png)

All this madness it's just ":x"...

* Ubuntu 14.04.5 LTS
* Terminal Guake 0.8.10
* NVIM v0.2.1-dev

**Comment by justinmk** [comment]
@tarciozemel #6997 should address your issue when it's merged soon.

**Comment by oppsig** [comment]
Also solved my problem with
export VTE_VERSION="100"

**Comment by ZelphirKaltstahl** [comment]
Question about this issue: Is it likely to be fixed in time, without users having to specify some variable like `VTE_VERSION`?

I've updated my NeoVim time and time again hoping it would be fixed, but maybe I am waiting for naught and there is no way it's simply going to work without having to set some variable?

(What does `VTE_VERSION` even do? Will it break other in terminal stuff?)

**Comment by ydajwz123** [comment]
The similar situation only occurs when I use 'sudo'. If I use nvim normally, everythin is ok. But if I use nvim with 'sudo' , changing mode(such as 'inserting mode, command mode) comes with a unexpected char 'q' (only one character 'q'). Is this the same as the problem you've disscused above?

**Comment by teto** [comment]
@ydajwz123 sudo changes your environment and the loaded config so it can be several things. You can `:set guicursor=` in the system config and overwrite it in your local one. See https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

**Comment by kabasakalis** [comment]
In my case  `$NVIM_TUI_ENABLE_CURSOR_SHAPE = 0`  wasn't enough,  I had to set `set guicursor=` in my `init.vim` to get rid of the issue in terminator and guake.

**Comment by teto** [comment]
@kabasakalis  $NVIM_TUI_ENABLE_CURSOR_SHAPE got removed a year ago (bootom of https://github.com/neovim/neovim/wiki/Following-HEAD)

**Comment by kabasakalis** [comment]
@teto  Right, I don't have time to follow the changelog. And I noticed you already mentioned guicursor in a comment above, so I am deleting my comment.

**Comment by jcarizza** [comment]
I also have the problem on Terminator an tmux. I had set the VTE_VERSION on my init.vim and fixed the problem:
```
let $VTE_VERSION="100"
```
