### ISSUE TITLE
no motion or scroll in terminal output

### ISSUE THREAD

**Issue by mayanksuman** [neovim/neovim#5991]
- `nvim --version`: v0.2.0-139-g8c9cccb
- Vim (version: ) behaves differently? - Yes.
- Operating system/version: Debian 8.6
- Terminal name/version: zsh 5.0.7
- `$TERM`: xterm-256color

### Actual behaviour
After giving and terminal command that span multiple screen, only the end or lowest portion of output is shown. Although the complete output of command is there in terminal but user can not scroll the output.
### Expected behaviour
User should be able to scroll the output by using motion keys.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!man ls
```
Even piping the output through less like ```:!man ls|less``` do not help. I have checked nvim v0.1.7, the problem persist there also.

**Comment by justinmk** [comment]
Ah, I see. When you said "terminal command" in the other issue I thought you were referring to `:terminal`. It's a known issue that `:!` does not support interactive applications like `less`. https://github.com/neovim/neovim/issues/1496

A workaround in the meantime is to use `:terminal`:

    :te ls

For manpages you can also use `:Man ls`.

**Comment by mayanksuman** [comment]
@justinmk Thanks!

Yes, ```:Man ls``` allows scrolling.
I think that to maintain compatibility with vim, ```:man ls``` or any command producing multiple screen output should also open the output in a nvim buffer (just like ```:Man ls```). This will help in supporting the formatting and scrolling through command output.

**Comment by mkschreder** [comment]
The fact that :! does not work properly and discards text is one of the reasons I feel I must go back to normal vim for now. Is there a way to fix :! so that it does not discard long lines and multiline text? Now I can not even do :grep because it discards most of the output.

**Comment by justinmk** [comment]
@mkschreder `:grep` fills the quickfix list. Did you try `:copen` ?
