### ISSUE TITLE
Bug with cursor in Neovim terminal, with zsh theme including git

### ISSUE THREAD

**Issue by JulioJu** [neovim/neovim#5992]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? : irrelevant
- Operating system/version: Arch Linux
- Terminal name/version: Terminator 1.90, XTerm(327) or tty
- `$TERM`: xterm-256color

### Actual behaviour

In Neovim terminal, there is a bug with cursor when we use an oh-my-zsh theme who displayed a git prompt in the same line of the cursor, and a git folder with no committed content. In this case,  a new character is insterted not after the cursor, but before.

### Steps to reproduce using `nvim -u NORC`

For example, with the following .zshrc (with "tjkirch_mod theme"), and of course `nvim -u NORC` :
```
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="tjkirch_mod"
source $ZSH/oh-my-zsh.sh
```
When we open a new Neovim terminal (`:e terminal`), if we go to a git directory with uncommitted changed (e.g. `touch ~/.oh-my-zsh/tmp.txt && cd ~/.oh-my-zsh'), there is a bug with the cursor : a new character is insterted not after the cursor, but before.

In "~/.oh-my-zsh/themes/tjkirch_mod.zsh-theme", if we remove `$(git_prompt_info)`, this bug isn't produced.

With oh-my-zsh and the the "tjkirch" theme, this bug not occured, although there is `$(git_prompt_info)`. But `$(git_prompt_info)` isnt on the same line than the cursor.

The minimal oh-my-zsh theme who cause this error is : 
```
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}⚡"
PROMPT='$(git_prompt_info)  '
```
But the following theme doesn't cause this error
```
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}⚡"
PROMPT='$(git_prompt_info
)  '
```

**Comment by justinmk** [comment]
> ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}⚡"

Thanks for the report. This is the same as https://github.com/neovim/neovim/issues/4976.

The workaround is to use some other character instead of U+26A1 ( ⚡) .
