### ISSUE TITLE
Cursor behaves strangely in st

### ISSUE THREAD

**Issue by funeralismatic** [neovim/neovim#5994]
- `nvim --version`: `NVIM v0.2.0-458-g7255f008`
- Vim (version: `none`) behaves differently?
- Operating system/version: Gentoo
- Terminal name/version: `st 0.7`
- `$TERM`: `st-256color`

### Actual behaviour
In insert mode it looks like:

![too wide cursor](https://0x0.st/O2-.png)

It can be at least 6 blocks width and increases when move cursor left.

### Expected behaviour
Normal 1x1 symbol cursor in insert mode.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:
```
And I see 6x1 symbols cursor as in insert mode.

**Comment by jamessan** [comment]
Does anything change if you put `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` in your init.vim?

**Comment by funeralismatic** [comment]
>`let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0`

Fixed.

**Comment by deathbeam** [comment]
For me cursor shape is changing properly when using st.

**Comment by justinmk** [comment]
@deathbeam What version?

**Comment by jalvesaq** [comment]
The cursor shape is changing properly for me too (st 0.6 and st 0.7).

@funeralismatic Did you install st with `sudo make clean install` or just run it from the local directory?
The output of `sudo make clean install` says that 4 entries are written to /etc/terminfo, and I guess that without these entries the cursor shape might not work.

**Comment by jalvesaq** [comment]
Update: The cursor shape does not change if nvim is running in a tmux session. In this case, the cursor keeps its single cell block shape.

**Comment by justinmk** [comment]
@jalvesaq See https://github.com/neovim/neovim/wiki/FAQ#cursor-shape-doesnt-change-in-tmux

**Comment by funeralismatic** [comment]
@jalvesaq

>@funeralismatic Did you install st with sudo make clean install or just run it from the local directory?
The output of sudo make clean install says that 4 entries are written to /etc/terminfo, and I guess that without these entries the cursor shape might not work.

I installed it using the package manager, so all the data has been installed properly. Without terminfo it's impossible to use some ncurses applications.
