### ISSUE TITLE
Neovim text becomes garbled when switching terminal tabs or windows/desktops

### ISSUE THREAD

**Issue by aaronbabaron** [neovim/neovim#5998]
![messed up](https://cloud.githubusercontent.com/assets/15972357/22190943/a1336346-e0db-11e6-89a6-7848be90bef6.png)
This is what my tab looks like when i switch terminal tabs or windows/desktops in general. It happens pretty consistently, is there any fix for this?

**Comment by justinmk** [comment]
What about the questions in the issue template (all of them)? Did this start happening recently vs an older version of nvim?

**Comment by aaronbabaron** [comment]
I'm using the most recent version of nvim I believe. I'm on Ubuntu 16.04 and am using zsh with prezto. My nvim is compiled with Python

**Comment by justinmk** [comment]
Did this start happening recently vs an older version of nvim? Or you are a new user?

**Comment by aaronbabaron** [comment]
I am a new user, I installed neovim a week or two ago

**Comment by justinmk** [comment]
Does it happen in Vim? Does CTRL-L cause the screen to fix itself?  Does it happen if you put:

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

in your init.vim (vimrc) and restart nvim?

**Comment by aaronbabaron** [comment]
i'm unsure if it happens in vim. it does happen even if i add that line and if i press ctrl + l it tries to fix it but fails

it seems it only happens when i increase the text size using ctrl shift +

**Comment by justinmk** [comment]
If CTRL-L doesn't fix it I don't know what else to do. Could you try a different font?

**Comment by justinmk** [comment]
Should be helped by the `updating_screen` check.
