### ISSUE TITLE
Broken characters in command-mode

### ISSUE THREAD

**Issue by fraxx001** [neovim/neovim#5999]
- `nvim --version`: 0.1.7ubuntu1+git201701221410+3082+23~ubuntu16.04.1
- Vim (8.0) behaves differently? yes
- Operating system/version: Ubuntu 16.04 LTS
- Terminal name/version: terminator
- `$TERM`: xterm

### Actual behaviour
Since the neoupdate over apt (deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial main).
I got an borken character string when entering command mode:
When starting neovim everything is alright:
![neovim_issue01](https://cloud.githubusercontent.com/assets/8928247/22199821/cb21b55a-e15c-11e6-84f6-775c64ae7e69.png)
after entering commandmode:
![neovim_issue02](https://cloud.githubusercontent.com/assets/8928247/22199837/df73a43c-e15c-11e6-893a-4d524c8f002f.png)
after leaving:
![neovim_issue03](https://cloud.githubusercontent.com/assets/8928247/22199869/fd6b92a6-e15c-11e6-8271-76749c08d3af.png)
Encoding in neovim is set to utf8. 

### Expected behaviour
Not to show this.

### Steps to reproduce
I upgraded neovim using apt-get and installt textlive-full. I can't tell if there is a relationship between this actions. reinstallation and removing of texlive didn't fix it.

**Comment by justinmk** [comment]
It's because we recently enabled `NVIM_TUI_ENABLE_CURSOR_SHAPE` by default, and your terminal (perhaps an old version of libvte, which terminator uses) is broken. Workaround is to 

    :set $NVIM_TUI_ENABLE_CURSOR_SHAPE=0

I'm going to revert the change that enable this by default, soon. Other issues already cover this, so closing.

**Comment by jaawerth** [comment]
Just a note for anyone else who stumbles across this - I was experiencing garbled text without switching tabs/windows after upgrading to 0.2.0, and this fixed it for me as well.

Thanks!

**Comment by kheaactua** [comment]
Setting `$NVIM_TUI_ENABLE_CURSOR_SHAPE` to 0 fixed this for me for a long time, but this restarted happening to me today.

This is with the regular Ubuntu 14.04.5 terminal, libvte-common version `1:0.28.2-5ubuntu1`, nvim version `v0.2.1-dev` (from the ppa: `0.2.0ubuntu1+git201707081551+3515+26~ubuntu14.04.1`), `TERM=xterm-256color`.

Whenever I enter nvim, pretty much everything I do draws `:[2 q` at the cursor

**Comment by fraxx001** [comment]
I had the same problem today:
set guicursor=

In init.vim fixed this

**Comment by kheaactua** [comment]
@fraxx001 Nice, that seems to have fixed it!

**Comment by blkwtkns** [comment]
Thank you @fraxx001 , your suggestion worked!

**Comment by pazzumpazzutu** [comment]
Thanks @fraxx001, this worked for me as well. 
However I had this issue only when using nvim (v0.2.0 installed from ubuntu 16.04 repositories) within tmux over an ssh connection. My TERM is initially set to "xterm-256color" and then it is changed to "screen-256color" by tmux. I do this trick to display the colors the way I want and make the nvim template I use work from within tmux as well. 
Differently from the main problem in this thread, the issue was appearing for me all the time and not only when in command mode. Thanks again and looking forward to see this fixed by default in the next releases.
