### ISSUE TITLE
kPlus distinguish with + 

### ISSUE THREAD

**Issue by lecheel** [neovim/neovim#6001]
- `nvim --version`: v0.2.0-425-ga062cd4
- Vim (version: )  Vi IMproved 8.0 is working for kPlus ^[ok
- Operating system/version: ubuntu 15.10
- Terminal name/version:
- `$TERM`:xterm

### Actual behaviour
kPlus map same as +

### Expected behaviour
kPlus is different with +

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment]
Try with `TERM=xterm-256color`

**Comment by lecheel** [comment]
Added TERM="xterm-256color"  is same

**Comment by justinmk** [comment]
What are the _exact_ steps you're doing? Are you mapping to `<kPlus>`? Press a keypad key?

**Comment by lecheel** [comment]
for example 
nmap + <Plug>(expand_region_expand)
nmap <kPlus> :GitGutterNextHunk<cr>  

but only expand_region_expand as + and kPlus

**Comment by justinmk** [comment]
Should be fixed in 0.3. Try HEAD from https://github.com/neovim/neovim/releases .

**Comment by justinmk** [comment]
## Resolution/Summary

See https://github.com/neovim/neovim/issues/9780.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
