### ISSUE TITLE
remote python plugin command does not get created

### ISSUE THREAD

**Issue by akulakov** [neovim/neovim#6003]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently?
- Operating system/version: Mac OS X sierra
neovim-dot-app

### Actual behaviour
:UpdateRemotePlugins successfully registers this plugin
plugin is defined as shown:

```
  @neovim.plugin
  class Django(object):
      @neovim.command("TestCmd", range='', nargs='*')
      def test_cmd(self, args, range):
          self.vim.command('echo "hello"')
```
Get error 'TestCmd' not an editor command

**Comment by justinmk** [comment]
Did you restart neovim after UpdateRemotePlugins? Currently that's required, though we'd like to simplify the process in the future.
