### ISSUE TITLE
Nvim changes default cursor style in terminal

### ISSUE THREAD

**Issue by himanshub16** [neovim/neovim#6005]
- `nvim --version`: 0.2.0--dev
- Operating system/version: Ubuntu 16.04
- Terminal name/version: GNOME-Terminal 3.18.3
- `$TERM`: xterm-256color

### Actual behaviour
My terminal cursor style is set to *I-Beam*, which after opening `nvim` changes to *block* and remains even after closing nvim.

### Expected behaviour
nvim should abide by the default terminal cursor style. Even if it doesn't, and sticks to block style cursor, it should not affect the cursor style of the current session in the terminal after closing. Presently, one has to restart the terminal or open a new terminal window to revert the settings.
Even changing the settings in the terminal settings doesn't affect.

### Steps to reproduce using `nvim -u NORC`
* Open nvim with cursor style as "i-beam". The cursor style changes.
* Close nvim. The cursor style changes to block.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/4867 and `man nvim`. Add

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

to your init.vim

**Comment by binaryreverse** [comment]
What actually solved my issue was to disable cursor changing in my .vimrc (or init.vim):

`set guicursor=`

**Comment by nomasprime** [comment]
Thanks @binaryreverse, this fixed the issue for me too.

**Comment by binaryreverse** [comment]
You're welcome.

**Comment by musm** [comment]
I'm getting this issue on 0.5 using Windows Terminal. I tried the suggested fixes to no avail.

**Comment by musm** [comment]
Oh my bad, I thought on Windows the  XDG_CONFIG_HOME  defaults to ~/.config not  ` ~/AppData/Local`
Setting the `XDG_CONFIG_HOME `  environment variable to `$HOME/.config` and using the suggested fix 
```
set guicursor=

```

worked

Note:
```
let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

```

did not work for me

**Comment by PalanixYT** [comment]
This is actually all wrong! The best thing to do would be to make a VimLeave that resets your cursor to your terminals!
`
augroup Shape
		autocmd!
		autocmd VimLeave * set guicursor=a:ver90
augroup END`

you have to replace "ver90" with your right cursor!

see 
https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-or-suspending-and-resuming-nvim
for more info.

also run 
:help 'guicursor'
for more info!

**Comment by sainivasmangu** [comment]
@PalanixYT hey!
`var90` changes my cursor to beam. I wanted to change it to underline. I couldn't find anything since I didn't know what to search for(tried "cursor notations", "cursor", "vim cursor code", "cursor code"). Can you tell me where I can find more info on this? Thanks in advance.

**Comment by PalanixYT** [comment]
for more info just run `:help 'guicursor'`

replace "ver90" with "horxx" replace the xx with the number

**Comment by sainivasmangu** [comment]
so `ver` is vertical! that makes so much sense i didn't see that i'm sorry
