### ISSUE TITLE
Default behavior of `:edit`

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#6010]
I notice that if I try to do this to edit a filename with spaces
```vim
:e filename with spaces
```

I get the error `E172: only one filename allowed`. If I can only edit one file anyway, shouldn't a better default behavior be to treat the rest of the line as a filename (up to separators like pipes, which would have to be escaped if in filenames)?

**Comment by tweekmonster** [comment]
Makes sense to me.  Same thing happens with:

```vim
:enew
:w filename with spaces
```

This is where it's happening: [ex_docmd.c#L4020-L4039](https://github.com/neovim/neovim/blob/25427ae892ccbb537a718c8abfbd4c79d9f94091/src/nvim/ex_docmd.c#L4020-L4039)

```c
    // Replace any other wildcards, remove backslashes.
#ifdef UNIX
    /*
     * Only for Unix we check for more than one file name.
     * For other systems spaces are considered to be part
     * of the file name.
     * Only check here if there is no wildcard, otherwise
     * ExpandOne() will check for errors. This allows
     * ":e `ls ve*.c`" on Unix.
     */
    if (!has_wildcards)
      for (p = eap->arg; *p; ++p) {
        /* skip escaped characters */
        if (p[1] && (*p == '\\' || *p == Ctrl_V))
          ++p;
        else if (ascii_iswhite(*p)) {
          *errormsgp = (char_u *)_("E172: Only one file name allowed");
          return FAIL;
        }
      }
#endif
```

I'm not exactly sure how advantageous ``:e `ls ve*.c` `` is considering tab completion works pretty well and it'll show the error `E77: Too many files` if the glob matches more than one.  It also displays `E79: Cannot expand wildcards` if the glob matches nothing.

**Comment by justinmk** [comment]
This comment convinces me that the current behavior serves no purpose:

```
     * Only for Unix we check for more than one file name.
     * For other systems spaces are considered to be part
     * of the file name.
```

**Comment by mhinz** [comment]
I agree that the behaviour could be improved and I'm usually for breaking changes, but this?

This will only lead to users complaining about our (as opposed to Vim's) `:edit` being broken. Moreoever, it would also break _many_ plugins, since they all use some variant of:

```viml
execute 'edit' fnameescape(filename_with_spaces)
```

And now, as if filename handling wasn't bad enough already, you have to distinguish between Vim and Neovim all the time.

My cost-benefit calculation says "nope". :>

**Comment by justinmk** [comment]
I didn't foresee any breakage here. Escaped filenames still are handled correctly, no?

**Comment by mhinz** [comment]
Hmm, you're right.

I played a bit around with just the block removed that tweekmonster mentioned, and it seems to work as expected already?

```
" edit "foo bar" (there should be only one match)
:e `ls foo*`

" edit "foo bar"
:e foo bar

" edit "foo\bar"
:e foo\\bar

" edit "foo|bar"
:e foo\|bar

" edit "foo\|\ bar"
:exe 'edit' fnameescape('foo\|\ bar')
```

Only one test breaks:

```
[  ERROR   ] /data/repo/neovim/test/functional/legacy/arglist_spec.lua @ 214: argument list commands test for :argedit command
```

**Comment by tbodt** [comment]
Sounds pretty useful1

**Comment by tbodt** [comment]
So useful that I managed to avoid pressing the shift key while typing the exclamation point

**Comment by mhinz** [comment]
(Please use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) on the first post, if you want to express your feelings without adding new content to this thread, thanks.)

**Comment by tbodt** [comment]
(ok)

~Theodore

**Comment by andylima** [comment]
What if Vim extends the :edit command in the future to accept multiple filenames? I.e.:
```
:edit file1 file2 file3
```

**Comment by clobrano** [comment]
Any chance to port this change on VIM first and only then on Neovim?

**Comment by chrisbra** [comment]
sure, ask on vim-dev (or open a ticket von Vims issue tracker). I personally doubt it, that Bram will change it however.

**Comment by justinmk** [comment]
@clobrano We would only make this change if it doesn't break plugins.

**Comment by fervic** [comment]
Why can't it open multiple buffers instead? Same behavior as when you run `nvim file1 file 2 file3` from the command line.

**Comment by justinmk** [comment]
@fervic `:n` and `:args` already do that, and it also would not be backwards-compatible.

**Comment by justinmk** [comment]
If someone wants to send a PR for this, let's try it out on master and see if the world ends.
