### ISSUE TITLE
`system()` outputs extra junk when running neovim inside of tmux

### ISSUE THREAD

**Issue by jncornett** [neovim/neovim#6015]
- `nvim --version`:
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170107-86229-pb9wz2/neovim-0.1.7/build/config -I/tmp/neovim-20170107-86229-pb9wz2/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170107-86229-pb9wz2/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170107-86229-pb9wz2/neovim-0.1.7/build/include
Compiled by xxx

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```
- Vim (version: ) behaves differently? The Vim below works as expected.
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct  5 2016 16:04:34)
Included patches: 1-898
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv           
```
- Operating system/version:
macOS Sierra 10.12.2

- Terminal name/version:
iTerm2 3.0.13

- `$TERM`:
xterm-256color

### Actual behaviour
When running Neovim inside of Tmux, the `system()` function outputs a tmux escape sequence. This breaks vim plugins which parse results from system calls. Example:
`:echo system('echo')` outputs `^[Ptmux;^[^[]50;CursorShape=0^G^[\hello`.
Running Neovim without Tmux works normally.
Tmux version: tmux 2.3
I have run with/without a custom `.tmux.conf` and the result is the same.
### Expected behaviour
Running the command inside of tmux should just output `hello`.

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC <<EOF
:echo system("echo hello")
EOF
```

**Comment by mhinz** [comment]
I'm just writing to say that the issue is apparently a bit more subtle. WIth almost the same stack and versions I can't reproduce it neither with v0.1.7 from homebrew nor master.

- macOS 10.12.**3**
- TERM: `tmux-256color`

Try putting this in your `.tmux.conf`:

```
set-option -g  default-terminal 'screen-256color'
```

Does it make any difference after restarting the tmux server?

**Comment by jncornett** [comment]
So I left out a small detail. I am using fish as my login shell. I edited my `~/.tmux.conf` to `set -g default-shell /bin/bash` and the erroneous behavior goes away. I'm going to do some further investigation.

**Comment by jncornett** [comment]
fish, version 2.4.0

**Comment by justinmk** [comment]
@jncornett You're sure this happens with `nvim -u NORC`? You didn't `'shell'` or `'shellcmdflag'` to something non-default? And what's `$NVIM_TUI_ENABLE_CURSOR_SHAPE` ?

**Comment by jncornett** [comment]
@justinmk Yes, I definitely used `nvim -u NORC`. nvim is inheriting the shell from the environment, which in my case is fish. The workaround for me is to set `shell` to something other than fish in my rcfile:

    set shell=/bin/bash

This fixes the problem, but has the obvious side-effect of changing the shell used by `:terminal`. Since I do not use `:terminal` heavily, (and don't mind using bash) this is a satisfactory solution for me. However, I feel that the `system()` function should *probably* use something like `/bin/sh` by default instead of the `shell` option, as the current behavior can result in somewhat cryptic bugs (as evidenced above). To provide larger context, I first discovered this bug while using the file search feature in [vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) and it was not at all apparent what the problem was at first.

**Comment by justinmk** [comment]
This is an issue with your environment, see https://github.com/neovim/neovim/issues/7353#issuecomment-334276005
