### ISSUE TITLE
Scheme syntax highlighting not R7RS-compatible

### ISSUE THREAD

**Issue by kozross** [neovim/neovim#6018]
- `nvim --version`: 
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently? Not applicable
- Operating system/version: Parabola GNU/Linux
- Terminal name/version: xfce4-terminal 0.8.3
- `$TERM`: xterm-256color

### Actual behaviour

Neovim's Scheme highlighting does not take [R7RS][1] changes to comment syntax into account. Specifically:

- R7RS block comments (``#| stuff stuff stuff |#``) do not get highlighted as comments (R7RS 2.2).
- R7RS datum comments (``#; (foo bar baz)``) do not get highlighted as comments (R7RS 2.2).

### Expected behaviour

Both of the above forms should be recognized as comments.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC sample.scm
i
#| This will not highlight as a comment, 
even though it should, as this is how R7RS does multi-line comments |#
#; (neither will this)
;; This will, though
```
[1]: http://trac.sacrideo.us/wg/raw-attachment/wiki/WikiStart/r7rs.pdf

**Comment by chrisbra** [comment]
You need to direct issues about runtime files to their respective 
maintainers. However in your case, reading the documentation is enough:

,---- :h scheme.vim
| MzScheme-specific stuff will be used if b:is_mzscheme or g:is_mzscheme
| variables are defined.
`----

**Comment by kozross** [comment]
@chrisbra I'm happy to direct this issue about ``scheme.vim`` to whoever maintains it. As far as the MzScheme thing goes, this is a complete red herring - MzScheme no longer exists (it's now called Racket), and even then, Racket (by default, at least as far as I know) isn't R7RS-compatible either.

**Comment by jamessan** [comment]
Neovim just merges the runtime files from Vim, so this should be addressed through the syntax file's maintainer (mentioned at the top of the file).  If/when the fix makes it into Vim, we'll eventually merge it back.
