### ISSUE TITLE
Stderr logging to open buffer at startup

### ISSUE THREAD

**Issue by sir-wiggles** [neovim/neovim#6021]
- `nvim --version`: 
``` 
NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/build/config -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/src -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/.deps/usr/include -I/usr/include -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/build/src/nvim/auto -I/build/neovim-T1FL9H/neovim-0.1.7ubuntu1+git201701261450+3090+23~ubuntu16.10.1/build/include
Compiled by root@lcy01-21

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) behaves differently? doesn't show error logs in buffer 
- Operating system/version: Ubuntu 16.10 (also happend on 16.04)
- Terminal name/version: gnome-terminal 3.20.2 
- `$TERM`: xterm-256color

### Actual behaviour
When I start neovim I get error messages showing up in the buffer obstructing text and won't go away until I scroll it off the screen.  

![nvim-error](https://cloud.githubusercontent.com/assets/1188878/22381960/8a841096-e478-11e6-9110-e8258000b64f.png)

I've tried removing my `init.vim` file to be a blank `init.vim` file wondering if it was a plugin issue but the problem still appears.

![nvim-error-no-init vim](https://cloud.githubusercontent.com/assets/1188878/22382128/2e8f5a74-e479-11e6-9660-4afc18b67153.png)

Looks like the error is coming from here https://github.com/neovim/neovim/blob/master/src/nvim/log.c#L124

It's interesting that I can't select the error message while in visual mode or with the mouse.  It's like part of the background.

If the file is small enough to fit in the buffer without needing to scroll then the message doesn't appear; however, if the file is larger than the buffer then the error message appears.  This video should explain what I mean.  Note `vim` is aliased to `nvim` here:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1188878/22383342/41db3b48-e47e-11e6-8daa-5ab8ccb2d37f.gif)

### Expected behaviour

No error logs to show up in buffer

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by oni-link** [comment]
Does setting another log file help: `NVIM_LOG_FILE=err.txt nvim`
Otherwise `nvim 2>err.txt` to redirect stderr.

**Comment by justinmk** [comment]
This shouldn't happen with RelWithDebInfo. How did you install? Or how did you build ?

**Comment by sir-wiggles** [comment]
@justinmk installed it though the PPA but since posting this I've been running into a lot of random core dumps to the point I can't really use neovim anymore.  I'm going to try and install it though source and see if I have better luck.

**Comment by jamessan** [comment]
@sir-wiggles I'd suggest trying the new [stable ppa] instead of using the nightly releases.

[stable ppa]: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

**Comment by sir-wiggles** [comment]
@jamessan oh man I didn't realize I was using the unstable ppa 😳. Thanks for pointing that out. Although building from source appeared to have fixed it but I'll give the stable ppa a shot. Sorry for the trouble.

**Comment by justinmk** [comment]
Is the unstable ppa setting LOG_LEVEL ?
