### ISSUE TITLE
copy-pasting from neovim to thunderbird : no carriage returns

### ISSUE THREAD

**Issue by tgirod** [neovim/neovim#6026]
- `nvim --version`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) didn't try
- Operating system/version: Archlinux
- Terminal name/version: Gnome Terminal 3.22.1
- `$TERM`: xterm-256color

### Actual behaviour

With `set clipboard+=unnamedplus`, select and yank some text in neovim. Then, paste it in a new message in thunderbird.

Result: the text is pasted as one single line, and consecutive whitespaces are reduced to a single one.

I also tried in firefox, and everything is fine if I paste in a simple textarea like this one, but I have the same problem if I paste in a rich text edit box such as etherpad.

Of course if I select and copy some content from the terminal outside of nvim, it is pasted properly.

### Expected behaviour

Having my text pasted as-is.

**Comment by tgirod** [comment]
Answering myself: I've installed xsel instead of xclip, and now everything works. So I guess neovim is not the culprit here!

**Comment by reederz** [comment]
@tgirod I had the same issue, thanks for the solution. It seems like this solution should be added to documentation somewhere.
