### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by alexbyk** [neovim/neovim#6027]
- `nvim --version`:NVIM 0.2.0-dev (from the neovim repo)
- Operating system/version: ubuntu
- `$TERM`: xterm-256color

Yesterday all was fine. Today mouse doesn't work. Scroll works fine, but click does nothing.  I think the latest update  did this.

**Comment by justinmk** [comment]
Add `:set mouse=a` to your init.vim.

**Comment by alexbyk** [comment]
Thanks! Works!
