### ISSUE TITLE
scripts under `after` dir do not run

### ISSUE THREAD

**Issue by akulakov** [neovim/neovim#6028]
- `nvim --version`: 0.1.7

scripts under `after` directory do not get run, and do not show up in :scriptnames listing
I created `rtp`/after/main.vim with an xmap mapping, which does not run.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Comment by ZyX-I** [comment]
@justinmk This looks like a bug description.

@akulakov Script in `after/main.vim` must not be run. Pretend that you need to place `main.vim` in any other directory in `rtp` and then add `after` between the directory path and location where you placed the file: `after` directories are by no means special, it is just a convention to add some directories with `after` trailing path component to `&runtimepath` by default. I think resulting location would be something like `after/plugin/main.vim`.

**Comment by akulakov** [comment]
Thanks ZyX! I did try it under after/plugin/ , but did not add `after/` to my rtp. Now it works.

**Comment by ZyX-I** [comment]
@akulakov You don’t need to add `after` to `&rtp` if it already is there (and there are already many after directories). If it is *not* there and yet scripts from there are loaded it is a *bug*.
