### ISSUE TITLE
configurable clipboard provider

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6029]
### Actual behaviour
In #5927 the behaviour of the clipboard provider was changed to only check for pbcopy on macOS. I followed an article http://brettterpstra.com/2014/02/19/remote-pbcopy-on-os-x-systems/ to create remote versions of pbcopy and pbpaste on my linux server. This is working fine for now but when I update my neovim to the latest master, it will break because neovim will not check for my pbcopy/pbpaste scripts as it is not running on macOS.

### Expected behaviour
I think the provider executable should be configurable. Only if it is not explicitly set, should neovim try to guess.

**Comment by equalsraf** [comment]
This came up earlier in https://github.com/neovim/neovim/issues/6013, and this one might be a way to fix it.

**Comment by nhooyr** [comment]
There is no clipboard-html in neovim. at least it isn't documented in `:h 'cb'`.

**Comment by equalsraf** [comment]
@nhooyr there isn`t. I just added the mention because if this issue is fixed, then implementing the html clipboard becomes trivial.

**Comment by BohrShaw** [comment]
And on Android [Termux](http://termux.com/), `termux-clipboard-set` and `termux-clipboard-get` are available.
