### ISSUE TITLE
tnoremap does not recognize <bar>

### ISSUE THREAD

**Issue by DanySpin97** [neovim/neovim#6031]
- `nvim --version`: 0.1.7
- Operating system/version: Arch Linux 4.9.6-1-ARCH
- Terminal name/version: Simple Terminal 0.7, fish 2.4.0
- `$TERM`: st-256color

### Actual behaviour
Neovim execute first command and does not recognize \<bar> and execute second command.

### Expected behaviour
Neovim execute the two commands  divided by \<bar> one after another.

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:tnoremap <F7> <C-\><C-n> <bar> :q <CR>
:term
<F7>
```

**Comment by justinmk** [comment]
The `<bar>` here would send `|` to the terminal input stream. You need `:`  before `<bar>`.

**Comment by justinmk** [comment]
> Neovim execute the two commands divided by <bar> one after another.

With the mapping you have, the bar is sent in normal mode. You need `:` before it.

**Comment by jamessan** [comment]
Or just remove `<Bar>` altogether.  There's no command that's being separated from `:q<CR>`.  The mapping should really just be `tnoremap <F7> <C-\><C-n>:q<CR>`.

You should also be careful with whitespace in your mappings.  Everything in the right-hand side of the mapping is used, so the spaces in `<bar> :q <CR>` would be used just as if you typed them.

**Comment by DanySpin97** [comment]
Thank you for explanation.
