### ISSUE TITLE
Syntax file isn't applied when using packadd

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#6034]
- `nvim --version`: 1.7
- Vim (version: ) 8.0

I've tried to move from vim-plug into even more minimalistic native vim plugin management. Everything seems to work, except one thing.

Syntax files from plugins aren't loaded, so I see default syntax. I was confused at first, but then I tried to use vim and it uses correct syntax file.

```
#ftplugin/after/python.vim
packadd! python-syntax

pack/packages/opt/python-syntax
├── CHANGES.txt
├── folding-ideas
│   ├── python.vim.1.13
│   └── python.vim.1.14
├── LICENSE
├── README.rst
├── syntax
│   └── python.vim
├── syntax.txt
├── test.py
└── TODO.txt

2 directories, 9 files
```

So to reproduce you should create `pack` folder and than add optional plugin with python-syntax and then tried to load it from `ftplugin/after` file.

**Comment by justinmk** [comment]
Without knowing more about your setup, I wonder if this is related to https://github.com/neovim/neovim/issues/4684. Do you have `filetype plugin ...` and `syntax enable` in your init.vim?

**Comment by purpleP** [comment]
Here is my vimrc https://github.com/purpleP/vimconf/blob/master/vimrc, and of course I have `filetype plugin` and `syntax enable`. I've just noticed that [indent script](https://github.com/Vimjas/vim-python-pep8-indent) isn't working in neovim also with `packadd`, while with vim8 it works.

**Comment by purpleP** [comment]
By the way, I've been able to enable custom syntax highlighting by making a symlinking syntax file into `~/.vim/syntax`

**Comment by justinmk** [comment]
> By the way, I've been able to enable custom syntax highlighting by making a symlinking syntax file into ~/.vim/syntax, and the same goes for indent script.

? That just sounds like a misconfigured `'runtimepath'` or plugin manager.

**Comment by purpleP** [comment]
@justinmk Well, that's the thing, right? I'm not using any plugin manager now except the one that comes with vim8. The one that `help packages` talks about. And in vim8 everything is working, but not in neovim.

**Comment by justinmk** [comment]
So what's `echo &rtp` for both vim and nvim?

**Comment by purpleP** [comment]
nvim
```
/etc/xdg/nvim
/etc/xdg/nvim/after
/etc/xdg/xdg-ubuntu/nvim
/etc/xdg/xdg-ubuntu/nvim/after
/home/michael/.config/nvim
/home/michael/.config/nvim/after
/home/michael/.linuxbrew/Cellar/neovim/0.1.7/share/nvim/runtime
/home/michael/.local/share/nvim/site
/home/michael/.local/share/nvim/site/after
/home/michael/.vim/pack/packages/opt/ale
/home/michael/.vim/pack/packages/opt/deoplete-jedi
/home/michael/.vim/pack/packages/opt/jedi-vim
/home/michael/.vim/pack/packages/opt/jedi-vim/after
/home/michael/.vim/pack/packages/opt/python-syntax
/home/michael/.vim/pack/packages/opt/switch.vim
/home/michael/.vim/pack/packages/opt/ultisnips
/home/michael/.vim/pack/packages/opt/ultisnips/after
/home/michael/.vim/pack/packages/opt/vim-python-pep8-indent
/home/michael/.vim/pack/packages/start/delimitMate
/home/michael/.vim/pack/packages/start/denite.nvim
/home/michael/.vim/pack/packages/start/deoplete.nvim
/home/michael/.vim/pack/packages/start/supertab
/home/michael/.vim/pack/packages/start/vim-abolish
/home/michael/.vim/pack/packages/start/vim-colors-solarized
/home/michael/.vim/pack/packages/start/vim-commentary
/home/michael/.vim/pack/packages/start/vim-easymotion
/home/michael/.vim/pack/packages/start/vim-exchange
/home/michael/.vim/pack/packages/start/vim-fugitive
/home/michael/.vim/pack/packages/start/vim-indent-object
/home/michael/.vim/pack/packages/start/vim-repeat
/home/michael/.vim/pack/packages/start/vim-surround
/home/michael/.vim/pack/packages/start/vim-textobj-user
/home/michael/.vim/pack/packages/start/vim-tmux-focus-events
/home/michael/.vim/pack/packages/start/vim-unimpaired
/usr/local/share/nvim/site
/usr/local/share/nvim/site/after
/usr/share/kubuntu-default-settings/kf5-settings/nvim
/usr/share/kubuntu-default-settings/kf5-settings/nvim/after
/usr/share/nvim/site
/usr/share/nvim/site/after
/usr/share/ubuntu/nvim/site
/usr/share/ubuntu/nvim/site/after
/usr/share/upstart/systemd-session/nvim
/usr/share/upstart/systemd-session/nvim/after
/usr/share/upstart/xdg/nvim
/usr/share/upstart/xdg/nvim/after
/var/lib/snapd/desktop/nvim/site
/var/lib/snapd/desktop/nvim/site/after
```
vim

```
/home/michael/.vim/pack/packages/opt/jedi-vim
/home/michael/.linuxbrew/share/vim/vim80
/home/michael/.linuxbrew/share/vim/vimfiles
/home/michael/.linuxbrew/share/vim/vimfiles/after
/home/michael/.vim
/home/michael/.vim/after
/home/michael/.vim/pack/packages/start/vim-fugitive
/home/michael/.vim/pack/packages/opt/ale
/home/michael/.vim/pack/packages/opt/deoplete-jedi
/home/michael/.vim/pack/packages/opt/jedi-vim/after
/home/michael/.vim/pack/packages/opt/python-syntax
/home/michael/.vim/pack/packages/opt/switch.vim
/home/michael/.vim/pack/packages/opt/ultisnips
/home/michael/.vim/pack/packages/opt/ultisnips/after
/home/michael/.vim/pack/packages/opt/vim-python-pep8-indent
/home/michael/.vim/pack/packages/start/delimitMate
/home/michael/.vim/pack/packages/start/denite.nvim
/home/michael/.vim/pack/packages/start/deoplete.nvim
/home/michael/.vim/pack/packages/start/supertab
/home/michael/.vim/pack/packages/start/vim-abolish
/home/michael/.vim/pack/packages/start/vim-colors-solarized
/home/michael/.vim/pack/packages/start/vim-commentary
/home/michael/.vim/pack/packages/start/vim-easymotion
/home/michael/.vim/pack/packages/start/vim-exchange
/home/michael/.vim/pack/packages/start/vim-indent-object
/home/michael/.vim/pack/packages/start/vim-repeat
/home/michael/.vim/pack/packages/start/vim-surround
/home/michael/.vim/pack/packages/start/vim-textobj-user
/home/michael/.vim/pack/packages/start/vim-tmux-focus-events
/home/michael/.vim/pack/packages/start/vim-unimpaired
```

@justinmk Well, I'm not using vim anymore, but I would like to have ability to run both vim and neovim, especially after neovim started to have problems with FocusLost/FocusGained events (it's really annoying when using tmux) and I really miss `<C-g>` `<C-t>` for next/previous partial search match.

**Comment by purpleP** [comment]
@justinmk Is there anything else I can do to help resolve this?

**Comment by justinmk** [comment]
Writing a test (even if it's just a shell script) will help a lot. @jamessan any idea about this?

**Comment by jamessan** [comment]
It looks odd that in nvim's `&rtp` there are both `~/.vim` and `~/.config/nvim` directories listed.  This sounds like a bad user environment.

If you're trying to share your config between vim and nvim, then I would highly suggest following the steps listed in `:help nvim-from-vim`.

**Comment by purpleP** [comment]
@jamessan Well, of course I did.

```
(.venv)9:44 ~ % ls -lah ~/.config/nvim
lrwxr-xr-x  1 myuser  staff    25B Jan  8  2016 /Users/myuser/.config/nvim -> /Users/myuser/.vim
(.venv)9:44 ~ % ls -lah ~/.config/nvim/init.vim
lrwxr-xr-x  1 myuser  staff    27B Jan  8  2016 /Users/myuser/.config/nvim/init.vim -> /Users/myuser/.vimrc
```

@justinmk I don't see how to automate testing this. I can create a docker container though. How about that?

**Comment by justinmk** [comment]
We need a reduced steps , that demonstrate an actual bug. Not an entire computer.

Instead of symlinking the config, copy it and clean up the rtp manipulation so that is is equivalent to Vim's.
