### ISSUE TITLE
execute() should clear cmdline

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6035]
- `nvim --version`: master
- Vim (version: ) behaves differently? yes, in vim, it works well
- Operating system/version: arch
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Actual behaviour
execute() do not clear cmdline
### Expected behaviour
execute() should clear cmdline
### Steps to reproduce using `nvim -u NORC`
test.vim
```viml
let g:testvim_test = 'hello neovim'
let g:testoldversion = 0

fu! Test()
    let list = []
    if has('patch-7.4.2010') && !g:testoldversion
        for var in getcompletion('g:testvim_','var')
            call add(list, var . ' = ' . string(get(g:, var[2:] , '')))
        endfor
    else
        redraw
        for var in filter(map(s:execute('let g:'), "matchstr(v:val, '\\S\\+')"), "v:val =~# '^testvim_'")
            call add(list,'g:' . var . ' = ' . string(get(g:, var , '')))
        endfor
    endif
    return list
endf

function! s:execute(cmd) abort
  if exists('*execute')
    return split(execute(a:cmd), "\n")
  endif

  redir => output
  execute a:cmd
  redir END
  return split(output, "\n")
endfunction
```
reproduce step:
1. nvim -u test.vim
2. `:echo Test()[0]` get `g:testvim_test = 'hello neovim'`
3. `:let g:testoldversion = 1`
4. `:echo Test()[0]` get `:echo Test()[0]            g:testvim_test = 'hello neovim'`

**Comment by wsdjeg** [comment]
this issue is found in https://github.com/SpaceVim/SpaceVim/pull/186

**Comment by jamessan** [comment]
Can you test #5975?

**Comment by wsdjeg** [comment]
@jamessan I am not sure if it is some issue with my config, but it still does not work well for me.

**Comment by justinmk** [comment]
Why is this a problem? Avoiding redraws is a good thing. Can you call `:redraw`?

**Comment by wsdjeg** [comment]
@justinmk This is different in vim, and redraw does not work, the output still has `echo Test()` at the begin.

**Comment by justinmk** [comment]
Sorry, I misunderstood the report.

**Comment by justinmk** [comment]
I see the problem, this only happens if you `:echo Test()[0]` as a user from the cmdline. If you add this to the end of the script, then source the script:

    :echo Test()[0]

There's no problem. Nor if you store the result in a variable and then echo the variable.

    let g:a= Test()[0]

**Comment by wsdjeg** [comment]
yes, I have trid use `let g:a= Test()[0]` in my plugin, and it works, but I think this maybe a bug.

**Comment by justinmk** [comment]
It is a bug. It can be worked around by adding `:redraw` to the beginning of `Test()` (or anywhere before the call to execute()).

**Comment by wsdjeg** [comment]
I have trid to add redraw at the beginning of Test(), but it does not work, BTW, I am using neovim 0.1.7, and has('patch-7.4.2010') return 0。

**Comment by justinmk** [comment]
Hmm, confirmed. I would guess `keep_msg` is not being updated for some reason. Even with `:redraw!`, the column still isn't updated so it looks like this:

```
                        g:testvim_test = 'hello neovim'
```

**Comment by wsdjeg** [comment]
Thanks, and a easy way to reproduce is :
`:echo type(execute('au'))`

you will see
`:echo type(execute('au'))      1`
instead of 
`1`

**Comment by liushapku** [comment]
Today I dug into the source code of both `vim` and `neovim` and identified the cause of difference: `vim` calls `msg_col = 0` at the end of function `f_execute()` while `neovim` does not do that. Adding a `msg_col = 0` to the end of `f_execute()` simply solves the problem.

------------------------------
Using @wsdjeg's test case I cannot see the problem, perhaps because I ran using `nvim -u NONE` and no autocmd is installed. I created the following test case which should be saved in a file and then in Ex mode, type `:so {the_file}`.

    call execute('echo 12345678')
    echo 'see where I am'

If the "see where I am" starts from col 1, then it is correct and compliant to vim's behavior. `nvim` will display the string from col 9.

**Comment by liushapku** [comment]
Acutally, simply set it to 0 will make the following `echon` behave differently. I created a [PR](https://github.com/neovim/neovim/pull/9319) to fully address this issue. 

A test script is saved at [here](https://gist.github.com/liushapku/109d32188464c2c8ae1a8c4bc43a97f8). I don't know how to add test to the repo. Each `call Testxa()` should generate exactly the same result as `call Testxb()` where `x=1,2,3,4`.

**Comment by janlazo** [comment]
I tried patching vim-patch:8.1.0569 and vim-patch:8.1.0571 for this issue but the tests fail because assertion with value from `screenchar`. Anyone who wants to port them should consider lua tests instead if the `screenchar` tests in `src/nvim/testdir/` are required for compatibility.
