### ISSUE TITLE
No function name syntax coloring in C/C++

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#6037]
```
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-pN7CDA/neovim-0.1.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-pN7CDA/neovim-0.1.7/build/config -I/build/neovim-pN7CDA/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-pN7CDA/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-pN7CDA/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- I tested vim, and it looks like it also fails to highlight function names for C and C++.
- Operating system/version: Debian Linux testing (Stretch).
- Terminal name/version: Konsole 16.12.0
- `$TERM`: xterm-256color

### Actual behaviour
Function names aren't syntax colored
### Expected behaviour
Function names should be syntax colored (works in other languages).

**Comment by ZyX-I** [comment]
Neovim team does not have enough developers to maintain non-Neovim-specific runtime files separately from Vim where Bram also defers maintainership to other developers (though not in this case). You need to contact maintainer listed at the top of the file – and since he is @brammool himsel you can just use https://github.com/vim/vim/issues.
