### ISSUE TITLE
man.vim: "man ascii" fails while viewing ft=c file

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6039]
The "3,2" sections preference of man.vim on C files is useful, but if it fails it should fallback to searching without a section. While viewing a C filetype, `:Man ascii` fails:

    man.vim: command error (21) man -w -s 3,2 ascii: No manual entry for ascii

Because "ascii" is only found in section 7. It should try without a section if the "preferred" sections fail.

cc @nhooyr

**Comment by nhooyr** [comment]
It should fallback: https://github.com/neovim/neovim/blob/3803314f7808838fc8c627915878631383ee612d/runtime/autoload/man.vim#L180-L182

**Comment by nhooyr** [comment]
Oh, nevermind, I see, another regression from #5734
