### ISSUE TITLE
escape character (001B) in prompt

### ISSUE THREAD

**Issue by klausweiss** [neovim/neovim#6041]
- `nvim --version`:
    NVIM v0.2.0-492-g3803314
    Build type: Release
- Vim (version: ) behaves differently? 7.4, everything's ok in Vim
- Operating system/version: Xubuntu 16.10, kernel 4.9.7 (fresh install, nvim is one of the first applications installed)
- Terminal name/version: terminator 0.98 / xfce4-terminal 0.6.3
- `$TERM`: xterm-256color

### Actual behaviour
There is an unexpected `001B` character along with `[2 q` or `[6 q` in prompt regardless of the font. When I start typing it is covered by the characters that I've typed.

I attach the screenshots after typing:
`:`
![nvim_prompt_001b](https://cloud.githubusercontent.com/assets/11031002/22516066/dbfa5d24-e8a4-11e6-8101-0f82918e2c1b.png)
`:e`
![nvim_prompt_001b_e](https://cloud.githubusercontent.com/assets/11031002/22516076/e26cd86c-e8a4-11e6-9cf5-ae202fb282da.png)
`:e ~/`
![nvim_prompt_001b_e_home](https://cloud.githubusercontent.com/assets/11031002/22516083/eae0f19a-e8a4-11e6-99c4-4f6b0380beb1.png)
After going back to normal mode:
![nvim_prompt_001b_esc](https://cloud.githubusercontent.com/assets/11031002/22516089/f3d5f354-e8a4-11e6-97c0-79f7e3a14a82.png)

It has nothing to do with `init.vim`, as I've commented out every line and the problem still occurs, but if you need it, [here it is](https://github.com/klausweiss/dotfiles/blob/master/neovim-config/init.vim).

**Comment by jamessan** [comment]
Add `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` to your init.vim.

**Comment by klausweiss** [comment]
Unfortunately nothing's changed. I've both with and without `$`.

**Comment by klausweiss** [comment]
Thanks, I could not manage to find the answer but now I see there are plenty of them. I hope someone will find this thread (:

**Comment by NoOutlet** [comment]
I will confirm that I have found this thread after getting so hopeless that I was preparing to install a new operating system. Thank you. Perhaps if this thread had not existed I would have found a duplicate, but I had not found one in previous searches, so who knows?

**Comment by madranet** [comment]
*Halle-blody-lujah!* --I've also just found this, after tearing my hair out for over an hour, trying to find out why this was happening.  

![screenshot from 2017-03-05 13-38-53](https://cloud.githubusercontent.com/assets/669658/23587660/1b51f0f0-01a9-11e7-97f0-11fdcbdf0e6f.png)

I initially thought my `zsh` shell was at fault, as the escape chars were most prominent in my command-line, after exiting `nvim`. So spent many a happy time seeing how deep went the rabbot hole of following the numerous *"Just comment in/out the following in your ~/.zshrc..."* 'solutions' that I found while searching the net.

Only, when it dawned on me that I was only seeing these odd chars in the terminal after exiting `nvim` and not following any other terminal commands, did I make the link with `nvim` and find this answer --which actualy worked!

Thanks!

PS: Oddly enough, I only saw this behaviour in Xubuntu [in both XFCE Terminal and Gnome Terminal].  Using the exact same `init.vim` in Ubuntu and OSX, I had no issues.

@jamessan --care to explain what `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` actually does and why it fixes the problem?

**Comment by jamessan** [comment]
@madranet Well, the man page explains what `$NVIM_TUI_ENABLE_CURSOR_SHAPE` does.  There was a change in default behavior to enable cursor shaping, but some terminals a) don't understand those escape codes and b) echo the unknown escape codes to the terminal.  a) isn't a big deal except when b) also happens, because then you get these visual glitches.

**Comment by maxwell-oroark** [comment]
Tried this, but unfortunately no dice.

**Comment by Shougo** [comment]
@maxwell-oroark `set guicursor=`
`$NVIM_TUI_ENABLE_CURSOR_SHAPE` is removed.

**Comment by maxwell-oroark** [comment]
thanks @Shougo this worked.

**Comment by Robinlovelace** [comment]
Confirmed, adding this to init.vim works:

```
:set guicursor=
```

**Comment by chrissound** [comment]
How is this not bug?

**Comment by jamessan** [comment]
It _is_ a bug... in the terminal emulator.  It's printing unknown escape sequences to the terminal instead of swallowing them.

**Comment by chrissound** [comment]
@jamessan thanks for explaining

**Comment by Nepoxx** [comment]
I wouldn't call it a bug but an unsupported feature.

That being said, maybe we could use the opportunity to track which terminal emulators don't support it and open issues on their repos?

I was having this issue with guake which is reported here: https://github.com/Guake/guake/issues/882

**Comment by smprather** [comment]
I'm still seeing these junk-characters when I exit nvim in Mate terminal (ie, Gnome terminal). However, `:set guicursor=` is not fixing it. Any other ideas for workaround? I am using nvim 0.7.

When running in Mate, via strace, I see this on the way out:
write(1, "\33[?1049h\33[22;0;0t\33[?1h\33=\33[?2004h", 32)

When running in KiTTY (ssh to machine from Windows), I see this on the way out:
write(1, "\33[?1049h\33[?1h\33=", 15)

Why is it printing the extra characters for Mate?

**Comment by smprather** [comment]
I just tried 0.7.2 and it is fixed. Thanks!
