### ISSUE TITLE
Open nvim man page in new tmux pane

### ISSUE THREAD

**Issue by mustaqimM** [neovim/neovim#6047]
- `nvim --version`: 0.1.7
- Operating system/version: Linux manjaro 4.9.6-1-MANJAROx86_64
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Expected behaviour
Open man pages using the nvim MANPAGER utility: `nvim -c 'set ft=man' -` to open man pages in a tmux pane. I'm trying to get it to open but it doesn't.

**Comment by justinmk** [comment]
Isn't this a tmux question? Why is it reported here?

**Comment by mhinz** [comment]
@mustaqimM See https://neovim.io/community.
