### ISSUE TITLE
Ctrl-W (hjkl) remember last window not just stop on first/last window

### ISSUE THREAD

**Issue by mcchrish** [neovim/neovim#6051]
Probably a feature request, or I haven't just parsed the help docs enough to see an existing option.

- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? No
- Operating system/version: MacOS Sierra
- Terminal name/version: iterm2 version 3
- `$TERM`:

### Actual behaviour

So the following behavior:
```
|CTRL-W_h|	CTRL-W h	   go to Nth left window (stop at first window)
|CTRL-W_j|	CTRL-W j	   go N windows down (stop at last window)
|CTRL-W_k|	CTRL-W k	   go N windows up (stop at first window)
|CTRL-W_l|	CTRL-W l	   go to Nth right window (stop at last window)
```
And let's say we have 3 split window such that, there's one vertical split on the left and two horizontal spits on the left. The active window is the bottom one on the right.
1. `ctrl-w h` moves the cursor to the left window.
2. `ctr-w l` moves the cursor to the *top* window on the right.

### Expected behaviour
To remember which window on the right where the cursor last was.

1. `ctrl-w h` moves the cursor to the left window.
2. `ctr-w l` moves the cursor to the *bottom* window on the right.

Expected behavior is how tmux does it with it's panes.

**Comment by justinmk** [comment]
`ctrl-w ctrl-w` goes to the previous window.

**Comment by nelstrom** [comment]
@mcchrish you might find the actual behaviour less surprising if you try this experiment. Recreate the 3 splits that you described in your issue, then follow these steps:

1. make the tall split active
1. press `H` to position your cursor at the top of the window
1. press `<C-w>l` and it should activate the top-right split

Now try this:

1. make the tall split active
1. press `L` to position your cursor at the bottom of the window
1. press `<C-w>l` and it should activate the bottom-right split

**Comment by mcchrish** [comment]
@nelstrom I see. So it really depends on the position of the cursor, not always going to the very top split.

@justinmk It's not the same behaviour as the one I expected though.

Actually I didn't mind about the current behaviour until I started trying the built-in terminal as a tmux replacement.

**Comment by justinmk** [comment]
@mcchrish This isn't something we would change in the core. It could be implemented as plugin without any problems. (If there _is_ a problem that blocks a reliable plugin from being implemented--for example, lack of information about the current window layout--then it would make sense to fix that problem.)
