### ISSUE TITLE
when would the chat reopen?

### ISSUE THREAD

**Issue by official4code** [neovim/neovim#6056]
### Actual behaviour
Gitter

404. This is not the chat you're looking for. Sorry. :(

### Expected behaviour
it should be working.

**Comment by mhinz** [comment]
It should work again.

This is no Neovim issue though. Follow https://twitter.com/gitchat for updates on Gitter's status.

**Comment by official4code** [comment]
it still isn't working. 😞

**Comment by jamessan** [comment]
I'm sorry it's still not working for you, but there's _nothing_ we can do about it.  You should be discussing this with the Gitter folks, either on Twitter as @mhinz already suggested or on their GitHub repository -- https://github.com/gitterHQ/gitter.

**Comment by mhinz** [comment]
Maybe check your internet connection. It works for me (and the others I talked to ;-)) for hours already.

**Comment by official4code** [comment]
still not working and my internet is perfect.
