### ISSUE TITLE
tui: shell command output is slow

### ISSUE THREAD

**Issue by wchargin** [neovim/neovim#6057]
- `nvim --version`: NVIM 0.2.0-dev: works on git master; regression in
  Ubuntu package neovim-0.1.7ubuntu1+git201702031636+3103+23 from
  working neovim_0.1.7ubuntu1+git201701311642+3097+23
- Vim (version: 7.4) behaves differently? yes; it has no issue
- Operating system/version: Linux Mint 17.3 LTS
- Terminal name/version: gnome-terminal 3.6.2
- `$TERM`: xterm-256color-italic

### Note on the versions above

I use the neovim-unstable PPA:
```
deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu trusty main
```
I cannot reproduce the problem against git commit 6d4e08d2, which is
master at the time of writing. The problem began when I upgraded from
the 2017-01-31 package to the 2017-02-03 package via the normal upgrade
process. Using dpkg, I can switch between these two packages to
consistently demonstrate that this is the cause of the problem. I can
provide these packages upon request.

### Actual behaviour

When using a shell command (`:!hello`), output can be very slow. It
looks like there is a minimum amount of time between lines being
displayed, as the lines appear at a very steady pace. This means that a
command that takes under a second to execute in a terminal (or in an
older packaged version of nvim) takes about two seconds to execute now.

### Expected behaviour

Text should fly by.

### Steps to reproduce using `nvim -u NORC`

Open `nvim -u NORC test.tex`, and add some content like this:

```tex
\documentclass{article}

\usepackage{tikz}  % this generates more output

\begin{document}

Hello, world!

\end{document}
```

Then, run `:! pdflatex %<CR>`. This command takes 0.208s to execute in a
terminal, but about 2 seconds to execute in neovim as the text scrolls
by.

Note that I cannot reproduce the problem simply by using `seq 1 10000`
or `seq 1 10000 >&2`, but I can absolutely consistently reproduce it
using pdflatex as above.

**Comment by justinmk** [comment]
Thanks for reporting this, it's an interesting test case for 0e75438a388f91c6219d2f22ade0472b067f5dca which was reverted.

I'm having trouble with your steps, though. I see the output below without any delay, which I assume isn't right:

```
:!pdflatex test.tex                                                                                                          
                                                                                                                             
This is pdfTeX, Version 3.1415926-1.40.10 (TeX Live 2009/Debian)                                                             
entering extended mode                                                                                                       
(./test.tex                                                                                                                  
LaTeX2e <2009/09/24>                                                                                                         
Babel <v3.8l> and hyphenation patterns for english, usenglishmax, dumylang, noh                                              
yphenation, loaded.                                                                                                          
(/usr/share/texmf-texlive/tex/latex/base/article.cls                                                                         
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class                                                       
(/usr/share/texmf-texlive/tex/latex/base/size10.clo))                                                                        
                                                                                                                             
! LaTeX Error: File `tikz.sty' not found.                                                                                    
                                                                                                                             
Type X to quit or <RETURN> to proceed,                                                                                       
or enter new name. (Default extension: sty)                                                                                  
                                                                                                                             
Enter file name:                                                                                                             
! Emergency stop.                                                                                                            
<read *>                                                                                                                     
                                                                                                                             
l.4 ^^M                                                                                                                      
                                                                                                                             
!  ==> Fatal error occurred, no output PDF file produced!                                                                    
Transcript written on test.log.                                                                                              
shell returned 1   
```

Is there a way to install pdflatex without 200MB of `sudo apt-get install texlive-latex-base`?

**Comment by justinmk** [comment]
@wchargin The issue with the ubuntu package will disappear in a day or so once the PPA updates itself from master. Keeping this issue open as a reference for the commit mentioned above.

**Comment by wchargin** [comment]
@justinmk Wow: thanks for the quick response! I can confirm that 0e75438
was the first bad commit and 4b7d3ae was the first good commit for me as
well. I'm happy to wait for the PPA update.

Sorry about the large install needed to reproduce. :-) If it's easy to
explain why `pdflatex` triggers this problem while `seq` does not, I'd
be interested, but if not then no worries.

**Comment by wchargin** [comment]
I've upgraded to neovim_0.1.7ubuntu1+git201702071400+3117+23, which
works without a hitch! Thanks.

**Comment by justinmk** [comment]
> Keeping this issue open as a reference for https://github.com/neovim/neovim/commit/0e75438a388f91c6219d2f22ade0472b067f5dca

Whatever race helgrind saw at that time (in function `update_size`, later renamed to `tui_guess_size`) is no longer reported.
