### ISSUE TITLE
command ":" and "/" 's error with Terminator

### ISSUE THREAD

**Issue by dcy** [neovim/neovim#6062]
- `nvim --version`: 0.1.7ubuntu1+git201702050011+3111+23~ubuntu16.04.1
- Vim (version: ) behaves differently? Vim works fine
- Operating system/version: Ubuntu 16.04
- Terminal name/version: terminator 0.98
- `$TERM`: xterm

### Actual behaviour
When i type ":q" command it will show ":q[6 q"
![2017-02-06-114548_131x83_scrot](https://cloud.githubusercontent.com/assets/1137238/22634109/d5c04e4e-ec61-11e6-85e7-612f7846a52b.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
The same
```

**Comment by justinmk** [comment]
Add `let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` to your init.vim, or use a newer version of libvte (which terminator uses).

**Comment by dcy** [comment]
I searched the other issues, found that ```export VTE_VERSION="100"``` works.

**Comment by justinmk** [comment]
Don't need that. See the wiki page "following HEAD".

**Comment by linweilin17** [comment]
> I searched the other issues, found that `export VTE_VERSION="100"` works.

nice to see this! Thank you!
