### ISSUE TITLE
command-line window (q:) initial cursor shape is wrong

### ISSUE THREAD

**Issue by rafaeln** [neovim/neovim#6074]
- `nvim --version`: NVIM 0.2.0-dev (just updated from the PPA)
- Vim (version: VIM - Vi IMproved 8.0 Included patches: 1-207 ) behaves differently? yes
- Operating system/version:Linux X240 4.4.0-62-generic 14.04.1-Ubuntu
- Terminal name/version: rxvt-unicode v9.21
- `$TERM`: rxvt-unicode-256color

### Actual behaviour

When you enter the command-line window, the cursor is in insert mode (straight bar)

### Expected behaviour

When you enter the command-line window, the cursor is in normal mode (block)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:<c-f>
```

or

```
nvim -u NORC
q:
```

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/4867 and `man nvim`. Add

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

to your init.vim

**Comment by rafaeln** [comment]
@justinmk, this isn't the same issue as #4867.
In #4867 people wanted to restore the default shape of the cursor when they left nvim back to the terminal.
This bug report is about the fact that, without ever leaving nvim, whenever one goes from normal mode to command-line window with `q:`, or from command-line prompt to commandline window with `ctrl-f`, the initial shape of the cursor is wrong.

**Comment by justinmk** [comment]
Did you try the steps above? I guess I pasted the wrong issue number, but there are many other duplicate issues to search for...

**Comment by justinmk** [comment]
Ah, I get it now. You are ok with the changing cursor shapes, but don't want a bar in cmdline mode. And the initial bar in `q:` is definitely wrong.

**Comment by Shougo** [comment]
I have tested it, and I have reproduced.
The cursor is bar in normal mode in command-line window.

**Comment by rafaeln** [comment]
This seems to have been fixed. Either accidentally or on purpose...

**Comment by justinmk** [comment]
Intentionally. We publish more granular mode change events now.
