### ISSUE TITLE
Mouse interoperability gone?

### ISSUE THREAD

**Issue by Maltimore** [neovim/neovim#6082]
- `nvim --version`: 0.2.0-dev
- Operating system/version: Ubuntu 16.04
- Terminal name/version: GNOME Terminal

Since I updated nvim today (with apt update and upgrade), all mouse interoperability is gone. Before I could click into splits to select them, could drag the split borders with the mouse, and could position the cursor by clicking. I don't know exactly when I last updated, but I'm thinking it was no more than a week ago. I have not touched the .vimrc, and the same problem exists with -u NORC.

**Comment by justinmk** [comment]
Add `:set mouse=a` to your init.vim. It's removed temporarily until we can offer a solution that makes "everyone" happy.

**Comment by Maltimore** [comment]
Thank you @justinmk !
(For future reference, is there some changelog where I could've seen that you made this change without bothering you with a github issue?)

**Comment by justinmk** [comment]
Normally we would mention it at https://github.com/neovim/neovim/wiki/Following-HEAD but I had tentative hopes to resolve the situation before 0.2 is released.

**Comment by Maltimore** [comment]
got it, thanks again!
