### ISSUE TITLE
Joining lines (`J`, `gJ` and so on) removes leading symbol like *

### ISSUE THREAD

**Issue by e-kwsm** [neovim/neovim#6085]
- `nvim --version`: v0.2.0-550-g5b8fac8 (Release)
- Vim (version: 7.4) behaves differently? yes
- Operating system/version: Debian 8.7 (jessie)
- Terminal name/version: GNOME Terminal 3.14.1
- `$TERM`: xterm-256color

### Actual behaviour
Joining lines `^[*#-%]\s*$`, `^[*#-%]\s\+\S`, or `^%.` removes the leading character(s).
For example, joining
```
* a
* b
```
by `J`, `gJ`, `:j`, or `:j!` (including visual mode) gives
```
* a b
```
They inserts a space between `a` and `b`.

But joining lines `^[*#-]\S` behaves correct. For example joining
```
*a
*b
```
by `J` gives
```
*a *b
```

### Expected behaviour
vim behaves as expected. In case of `J`,
```
* a * b
```

### Steps to reproduce using `nvim -u NORC`
1. `nvim -u NORC`
2. insert lines like above
3. hit `J` etc on a line except the last

**Comment by fmoralesc** [comment]
Try reproducing this with `nvim -u NONE`.

**Comment by e-kwsm** [comment]
Even if `nvim -u NONE`.

**Comment by chrisbra** [comment]
tweak your formatoptions setting

**Comment by fmoralesc** [comment]
Yes, it seems like `&fo` includes `j` by default. I can't remember having changed that when going through the changes to default settings...

**Comment by fmoralesc** [comment]
Well, as a matter of fact I made that change: https://github.com/neovim/neovim/pull/2669 

We took that setting from sensible.vim (https://github.com/tpope/vim-sensible/blob/4b7535921819a5b2e39be68f81109ea684232503/plugin/sensible.vim#L57).

**Comment by e-kwsm** [comment]
I see. Due to `j` in `formatoptions`.
But `ft` is not set and I don't intend `*` etc are comment leader.
Why `%` behaves differently?

Also, at present joining
```
# a
* b
```
gives
```
# a b
```
I don't think this is good.

**Comment by fmoralesc** [comment]
`j` in `&formatoptions` uses (I think) the values in `&comments `. Now, it seems like `*` shouldn't behave this way by default, because one would expect it to have this behavior only if in context it represents a comment continuation. That is,

```
/* 
*
* 
*/
```
should join as `/* */`, but 
```
* 
*
*
``` 
should join as `* * *`, as you expect. I think this is an issue in both vim and nvim.

**Comment by LudwikJaniuk** [comment]
I'm sorry for bringing this up, but how is this closed without a fix? Comments in code files are one thing, but J-ing the following lines in a regular .txt:
```
lorem ipsum -
-
```
produces:
```
lorem ipsum -
```
Vim does not do this. I believe it is very much not sensible behavior, and insidious when editing e.g. csv files.

**Comment by chrisbra** [comment]
it is a configuration issue.

**Comment by bfredl** [comment]
'comments' is set by filetype. seems it is set to `fb:-,fb:*,n:>` for `text` but the builtin default ( `s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-` ) for `csv`. Perhaps another value would be a better default for csv?

Though it is easy to disable for all filetypes in init.vim:

    set formatoptions-=j
