### ISSUE TITLE
Any way to show "OPERATOR" in statusline when in operator pending mode?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#6086]
Is this possible?

If not, I'd like it to be a feature request to have some way to hook into that (an `autocmd`?) so we can for example change the status line to make it obvious we are in operator-pending mode.

This would be great because people just starting to learn vim can have obvious indication about operator pending. What I find is that often times they press a key on accident, and don't realize they are in operator pending mode, then they try to do another combo which fails and they don't immediately know why.

**Comment by justinmk** [comment]
`'showcmd'` helps with this. But I suppose it makes sense. It's going to be noisy though.

**Comment by saurabh-kumar-vit** [comment]
I would like to take up this task. 
But I am new to open source contribution and don't know how to get started. It would be very help full if you could point me to some files and docs that will help me complete this task.

**Comment by justinmk** [comment]
First thing to read is https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md

[wiki](https://github.com/neovim/neovim/wiki) has all relevant information or links to relevant information.

**Comment by saurabh-kumar-vit** [comment]
Thank you! I will get on it right away.

**Comment by justinmk** [comment]
[Oni](https://github.com/onivim/oni) does this (try `di` or `da`; note that `d` by itself is a "motion" which is not a separate "state").

So Nvim emits this info as a UI event, and it works. For TUI it's conceivable that we might make it easier for plugins to listen to UI events.
