### ISSUE TITLE
configurable margin between line numbers and code

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#6092]
It'd be super sweet to configure the spacing between the line number section and the code. For example, right now it is permanently `0`:

<img width="296" alt="screen shot 2017-02-10 at 9 33 28 pm" src="https://cloud.githubusercontent.com/assets/297678/22851507/9ad239d0-efd8-11e6-8190-4e41fc01b77a.png">

The following mockup shows what it would look like if we could configure the spacing to be `1` so the code doesn't butt up against the line number column:

<img width="296" alt="screen shot 2017-02-10 at 9 33 28 pm" src="https://cloud.githubusercontent.com/assets/297678/22851514/1002866a-efd9-11e6-8a30-5d504d0f1661.png">

This would be cool!

**Comment by varreli** [comment]
Yeah I've been trying unsuccessfully to do a workaround for this. The spacing is very tight. Pax.

**Comment by craigjmidwinter** [comment]
It would be cool to have this configurable on an element by element basis in a syntax highlighter for a format like .fountain

**Comment by cbrintnall** [comment]
Any progress on this? Surprised it isn't supported across any of the Vi forks.

**Comment by justinmk** [comment]
> Any progress on this? Surprised it isn't supported across any of the Vi forks.

Started in https://github.com/neovim/neovim/pull/6373 but then abandoned. Waiting for someone to take ownership.

**Comment by malyutinegor** [comment]
Still no any progress on this?

**Comment by varreli** [comment]
Thanks I think I resolved it .. I don't remember how.

**Comment by xdevs23** [comment]
This would be really cool to have, it's a bummer it isn't available yet.

**Comment by Victarry** [comment]
Hope this will be implemented soon~

**Comment by hrqmonteiro** [comment]
I really hope this would be a thing that gets implemented.

**Comment by nkcfan** [comment]
@trusktr May I ask what is your font?

**Comment by varreli** [comment]
Not sure I'll check but also this issue is easily resolved in config - I
lost track of this thread sorry.

**Comment by siduck76** [comment]
this would be really cool to add. At least a right margin for the line number would do
