### ISSUE TITLE
:terminal does not use command modifiers

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6093]
- `nvim --version`: NVIM v0.2.0-574-g14fc482
- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.12.3
- Terminal name/version: iTerm 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
`vertical terminal` opens a terminal in the current split.

### Expected behaviour
it should open a terminal by first vertically splitting

**Comment by ZyX-I** [comment]
`:terminal` does not open a new window. Hence it *must not* use modifiers that affect commands that do.

**Comment by ZyX-I** [comment]
This question was already discussed in some other issue. I do not remember any resolution, but my opinion is that Neovim is missing `:sterminal` and `:vterminal` commands. Which will also be affected by modifiers. Though currently you can use either `vsplit | terminal` or `vsplit term://…` to do what you need.

**Comment by ZyX-I** [comment]
#3192

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/5431.
