### ISSUE TITLE
set termguicolors and tmux -2

### ISSUE THREAD

**Issue by hholst80** [neovim/neovim#6096]
- `nvim --version`:

```
NVIM v0.2.0-574-g14fc482
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/neovim/build/config -I/neovim/src -I/neovim/.deps/usr/include -I/neovim/.deps/usr/include -I/neovim/.deps/usr/include -I/neovim/.deps/usr/include -I/neovim/.deps/usr/include -I/neovim/.deps/usr/include -I/usr/include -I/neovim/build/src/nvim/auto -I/neovim/build/include
Compiled by root@1fa19c7b0dd9

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```

- Operating system/version:

centos 7

- Terminal name/version:

tmux -2

- `$TERM`:

`screen-256color`

### Actual behaviour

![image](https://cloud.githubusercontent.com/assets/6200749/22855832/b3fad4cc-f086-11e6-8514-f0195f28232a.png)

### Expected behaviour

![image](https://cloud.githubusercontent.com/assets/6200749/22855835/c5475912-f086-11e6-8168-01b33a3a6702.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC init.vim
nvim init.vim
```

**Comment by justinmk** [comment]
`tmux -2` explicitly uses 256 colors, not millions. There's nothing nvim can do about this.

**Comment by hholst80** [comment]
@justinmk Tmux approximates the RGB truecolor value requested with the nearest value in the 256-colour palette as far as I understand. It should work no worse than 256-color mode and certainly not render in black and white.

![image](https://cloud.githubusercontent.com/assets/6200749/22858426/7f602320-f0bd-11e6-9eca-fb45b61c8e9e.png)

**Comment by hholst80** [comment]
I'll do some more digging into this but clearly `:set termguicolors` works fine with nvim, from within tmux. 

It is not clear why I need to have this black magic in my config: 

```
set t_8f=^[[38;2;%lu;%lu;%lum  " Needed in tmux
set t_8b=^[[48;2;%lu;%lu;%lum  " Ditto
```

which renders as good as 256 color:

![image](https://cloud.githubusercontent.com/assets/6200749/22858485/5aa32ca6-f0bf-11e6-8c15-6c624dd49c2e.png)

**Comment by justinmk** [comment]
Here's the format we're using: https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L929-L932

**Comment by hholst80** [comment]
I managed to simplify quite a lot today and I think that the problem above might be valid, but it can also be solved outside neovim.

tl,dr; The behavior of neovim inside a tmux session depends on the setting of TERM *before* tmux is launched. TERM=xterm leads to weird behavior but `set termguicolors` just works (TM) if you set TERM=xterm-256color before launching tmux.

1. export TERM=xterm-256color (or set :XTerm*Term: xterm-256color in your ~/.Xresource file. Don't forget to xrdb -merge it!)
2. Use `set termguicolors` in `init.vim` and don't use the special  t_* hacks^Wsettings mentioned above.
3. Start tmux with or without -2 - it does not matter. You also should not need to specify any terminal what so ever in your tmux.conf. Note that tmux will set TERM=screen but don't worry about that. As long as you have set `set termguicolors` everything will work. 
4. Only if you use `set noguitermcolors` (this is the default!) you will need to set the term to `screen-256color` in your tmux.conf or set TERM=screen-256color before launching nvim inside tmux.

I used xterm (322-1ubuntu) and not some compatible terminal like gnome-terminal. If you are using another terminal YMMV. Tested against tmux 2.3 (latest stable) and NVIM v0.2.0-574-g14fc482.

**Comment by poiati** [comment]
I don't know if the issue is related but it seems like the `set termguicolors` does not work inside tmux. When I launch neovim inside tmux I get the same colors as I'm running it outside tmux and without termguicolors set.

My TERM env is set to xterm-256color in and out of tmux. I'm using ubuntu and gnome-terminal.

**Comment by justinmk** [comment]
@poiati Are you sure your tmux version supports true color?

**Comment by poiati** [comment]
I'm using tmux 2.2, the one from ubuntu 16.10 official repo. The only color that changes in the absence of termguicolors is the background:

![screenshot from 2017-02-26 11-26-27](https://cloud.githubusercontent.com/assets/21452/23340522/82d68346-fc16-11e6-995e-60a7cd92022b.png)

![screenshot from 2017-02-26 11-26-49](https://cloud.githubusercontent.com/assets/21452/23340525/856bae60-fc16-11e6-98b0-01d5a1de3af0.png)

**Comment by jdebp** [comment]
The problem with `termguicolors` is described in #5089, which really was not closed with a satisfactory resolution.  The problem is that one's `init.vim`has to magically know whether the terminal is 24-bit RGB colour capable.  `&term` is not the answer; that has been removed.  `&t_Co` is not the answer; that only reflects the number of indexed colours not the number of direct colours.

I have just made a doco change in #6816 (93081c34be37ef65760a471067d24047681ab6fe) to `:help term-dependent-settings` that should indicate the way to address this.

**Comment by justinmk** [comment]
See @jdebp 's comment above.

**Comment by justinmk** [comment]
> When TERM is xterm before starting tmux, nvim will not display colors correctly even after changing TERM inside tmux

@LunarLambda In that case _tmux_ has decided to disable _its_ truecolor support because of the TERM value.

Whereas in Vim/Nvim, `set termguicolors` almost always forces Vim/Nvim to send truecolor sequences regardless of TERM value.
