### ISSUE TITLE
Documentation suggestion: remote copy using xclip and ssh -X

### ISSUE THREAD

**Issue by hholst80** [neovim/neovim#6097]
The command `:CheckHealth` recommends that clipboard is setup using tools but clipboard documentation implies that SSH copy-paste needs to use advanced tools such as lemonade.

I think there is a much simpler solution good enough for most of nvim users that need copy-paste working over SSH:

1. Login to the remote box using `ssh -X user@machine` from X11 machine.
2. Install `xclip` 
3. Make sure `$DISPLAY` is set to something like `localhost:10`
4. (personal preference) set `set clipboard+=unnamedplus`
5. nvim will, via `xclip`, copy data to the X11 server.

I think this so useful it should be documented somewhere but I am not sure where.

**Comment by justinmk** [comment]
That's rather platform-specific. Would prefer to keep the docs mostly platform-agnostic.

**Comment by justinmk** [comment]
If you can think of a concise way to present this at `:h clipboard` please send a PR.

**Comment by hholst80** [comment]
I will see if I can find a formulation that fits the tone of `:h clipboard` if I can find a way to make this work together with Windows. It should work as-is on both Linux and MacOS.
