### ISSUE TITLE
match pairs "{ }"

### ISSUE THREAD

**Issue by friartek** [neovim/neovim#6102]
- `nvim --version`:  0.1.7
- Vim (version: 8.0 ) behaves differently? Depends on use case.
- Operating system/version:  funtoo(gentoo)  Funtoo Linux - baselayout 2.2.1
- Terminal name/version:  termit/3.0.0,    QTerminal/0.7.1,   xfce4-terminal/0.8.3,  tmux/2.3
- `$TERM`:  xterm-256color, xtem-256color, xterm-256color, screen-256color,

### Actual behaviour

This may need more then one issue opened to cover everything.  Although I'm experiencing issues with braces "{ }" matching on zsh(also tested as sh), some of what I found may also involve other matched pairs, depending on a particular program language.  Vim 7.4 was the worse, Vim 8.0 was better, but moving to nvim 0.1.7 helped even more. There are still issues.

I have attached  a file with example code to allow one to check what I am seeing.

It would appear that syntax _highlighting_, command _%_ and _folding_ do not share all the same code when trying to match braces.  The best way to see what is going on is to open the file and place the cursor over a brace to see where matching appears(or doesn't appear) then using the % command and see where the cursor moves(or doesn't move) to.  In the case where a brace is commented out, I would expect "vim" to ignore it, but this is not the case.  In the case of where a brace is part of output of an echo command, this may be harder to detect, but I believe this to should be ignored.  Also matching behaves differently depending on whether the whole output string is quoted or not.  

Then there is the folding.  Folding appears to just look for the first "}}}" to complete the fold.  As the test file will show, when there is "code" that has the three braces, folding stops at the first occurrence.  There is no checking for this.  But highlighting and the % command both check for this.

### Expected behaviour
What I expected is included in the above statement.
Maybe I am expecting to much, but I hope not.

Sorry is someone is reading this before I finished editing.  No sure what happened, but while editing the description, I hit some key that caused it to submit before I was through.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
[vim_nvim_brace_n_fold_test_script.txt](https://github.com/neovim/neovim/files/769215/vim_nvim_brace_n_fold_test_script.txt)

**Comment by ZyX-I** [comment]
I do not see any issue description here.

**Comment by friartek** [comment]
Sorry, but I hit some key that caused the issue to submit before I was finished. Just finished editing and adding the information.  Hopefully it is clear enough.  But to see what is going on, you need to check the test file.

**Comment by friartek** [comment]
@ZyX-I  can this be reopened, or do I need to resubmit?

**Comment by justinmk** [comment]
We have requests for "better syntax". What's different about this one?

**Comment by ZyX-I** [comment]
@justinmk I remember discussions of using syntax for matching pairs (% and highlighting). But I do not remember folding in these discussions.

BTW, for my projects I normally select ▶ and▲ as fold markers, that normally does not cause problems because these characters are not expected to appear in the source code.

**Comment by friartek** [comment]
@justinmk   Not actually sure what "better syntax" means.  Are you asking about z-shell(zsh) vs some other shell?  Or do you need an actual code example instead of the simplified example I submitted?  If it is actual code, for the folding issues, the following line is what caused folding to stop:

MAddr="${(j::)${(Oas::)${${${(z)${(s:@:)${Addr}}[2]}:r}:gs/./}}}"

A nested group of 7(if I counted right) instructions that splits, word splits, substitutes, reorders, joins the info from one variable and sets another.  It so happens to have three braces "}}}" grouped together.  This kind of nesting is not unique as far as I know.  Perl can get very convoluted.

Is this what you mean, or am I totally off the mark?

**Comment by justinmk** [comment]
@friartek That was kind of my point, the request here is almost as vague as the other requests to "improve the syntax engine". 

Syntax analysis is regex-based currently. Using a real parser would help avoid the weaknesses of the regex approach. That's covered by #719. Related: #6052.

There are several approaches being discussed, one is to using semantic engines via LSP etc., another is to use PEG, e.g. [scintillua](https://foicica.com/scintillua/). And adding generalized facilities like `nvim_buf_add_highlight()` (already implemented) as well as more advanced features alluded to in #6052.

**Comment by friartek** [comment]
Pictures worth a thousand words.

vim_syntax_match_001.png  cursor over brace of commented out line, match to closing brace of function
vim_syntax_match_002.png  % and cursor moved to closing brace of function match to top brace of function
vim_syntax_match_003.png  % again and cursor exchanges postion with match as expected.

vim_syntax_match_009.png  cursor over brace at end of [something] test, match at the function closing brace not at end of "test" brace, % just switches positions.

Putting  the cursor on any of the three fold closing braces "}}}" come up with "incorrect" results for the match.

Does this help clarify what is going on.

![vim_syntax_match_001](https://cloud.githubusercontent.com/assets/10067283/22866282/4986a04a-f139-11e6-840e-a79e1c0b1d02.png)
![vim_syntax_match_002](https://cloud.githubusercontent.com/assets/10067283/22866288/5ba5b6e4-f139-11e6-8b67-e4ea1934d47a.png)
![vim_syntax_match_003](https://cloud.githubusercontent.com/assets/10067283/22866290/631e5fac-f139-11e6-8c22-6ac3e616d697.png)
![vim_syntax_match_009](https://cloud.githubusercontent.com/assets/10067283/22866291/68621f94-f139-11e6-8e50-dbb240210e68.png)

**Comment by justinmk** [comment]
`matchparen.vim` is the plugin that provides the coloring. `matchit.vim` provides the `%` feature. It's true that they don't share code. If they have bugs, it would be bested to report to the maintainers of those plugins, listed [here](https://github.com/neovim/neovim/blob/master/runtime/plugin/matchit.vim#L3) and [here](https://github.com/neovim/neovim/blob/master/runtime/plugin/matchparen.vim#L2).

In this case it's probably good enough to report at [Vim's repo](https://github.com/vim/vim).

We don't want to maintain forks of those plugins in Neovim unless there's a really good reason to do so.

**Comment by friartek** [comment]
There was an issue already open on Vim where the same thing was happening with brackets `[`.  Vim [#1445](https://github.com/vim/vim/issues/1445)  Added this to it.  FYI
