### ISSUE TITLE
has('unnamedplus') is always 0

### ISSUE THREAD

**Issue by ntrrgc** [neovim/neovim#6103]
- `nvim --version`: 0.1.7
- Vim 8.0 1-314 behaves differently
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour

`:echo has('unnamedplus')` prints 0, even though xsel is installed and `:set clipboard+=unnammedplus` actually works.

### Expected behaviour

`has('unnamedplus')` should return 1 if and only if the system clipboard is available for use in NVim, as in Vim.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo has('unnamedplus')
```

**Comment by jamessan** [comment]
That's not a feature listed in `:help feature-list`, which is probably why it was missed.  It should be easy enough to add support for that by treating it the same as `has('clipboard')`.

**Comment by Kurt-Bonatz** [comment]
@jamessan This seems slightly more complex than that. Vim uses a riduculious number of macros and guards to populate its has_list[] (the list of features to check against) to handle cases like this. [See evalfunc.c#L5854-L5856](https://github.com/vim/vim/blob/e90858d0229444b3cd16b1cd3a8d61a24c435705/src/evalfunc.c#L5854-L5856) (vim patch 7.4.2063 moved f_has() from eval.c to evalfunc.c) :
``` c
#if defined(FEAT_CLIPBOARD) && defined(FEAT_X11)
	"unnamedplus",
#endif
```
However for Neovim while Unix is an easily checked macro, determining if the clipboard is available is done by checking for its provider live. [See f_has() eval.c#L10470-L10633](https://github.com/neovim/neovim/blob/6e9f329d051cf6bf6d83dbe5335f86a1752ec45a/src/nvim/eval.c#L10470-L10633):
``` c
/// "has()" function
static void f_has(typval_T *argvars, typval_T *rettv, FunPtr fptr)
{
   ...
  if (!n && eval_has_provider(name)) {
    n = true;
  }

  rettv->vval.v_number = n;
}
...
bool eval_has_provider(char *name)
{
#define check_provider(name) \
  if (has_##name == -1) { \
    has_##name = !!find_func((uint8_t *)"provider#" #name "#Call"); \
    if (!has_##name) { \
      script_autoload((uint8_t *)"provider#" #name "#Call", false); \
      has_##name = !!find_func((uint8_t *)"provider#" #name "#Call"); \
    } \
  }

  static int has_clipboard = -1;
  static int has_python = -1;
  static int has_python3 = -1;
  static int has_ruby = -1;

  if (!strcmp(name, "clipboard")) {
    check_provider(clipboard);
    return has_clipboard;
  } else if (!strcmp(name, "python3")) {
    check_provider(python3);
    return has_python3;
  } else if (!strcmp(name, "python")) {
    check_provider(python);
    return has_python;
  } else if (!strcmp(name, "ruby")) {
    check_provider(ruby);
    return has_ruby;
  }

  return false;
}
```

Which makes it non-trivial to just add "unnamedplus" to Neovim's has_list[] with guards (in the case where the user has unix but not a system clipboard). It also seems like a bad idea to manually check for it in the method to only return 1 vs 0. Let me know if you come to a different conclusion.

**Comment by justinmk** [comment]
One way to handle this would be to add a `check_provider(unnamedplus)` call, then add a `runtime/autoload/provider/unnamedplus.vim` stub that just wraps `runtime/autoload/provider/clipboard.vim`.

**Comment by jamessan** [comment]
@Kurt-Bonatz I'm aware of the intricacies of how both code bases determine this.  That's specifically why I suggested having `has('unnamedplus')` effectively be a synonym for `has('unix') && has('clipboard')`.  It would be the closest to the original intent.

The could easily be achieved by doing something like the below code at the top of `f_has`:

```c
if (strnicmp(name, "unnamedplus") == 0) {
#ifdef UNIX
  n = eval_has_provider("clipboard");
#endif
  rettv->vval.v_number = n;
  return;
}
```

**Comment by Kurt-Bonatz** [comment]
@jamessan I apologize for coming across as condescending as it was not my intention. That was the first time I had ever seen either files, and I was confused by what you meant with `has('unix') && has('clipboard')` as it didn't seem that straight forward.

I prefer your solution to stubbing a provider as @justinmk suggested. I'll put up a pull request tonight akin to:
``` c
    } else if (STRICMP(name, "syntax_items") == 0) {
       n = syntax_present(curwin);
#ifdef UNIX
    } else if (STRICMP(name, "unnamedplus") == 0) {
       n = eval_has_provider("clipboard");
#endif
    }
}
```

Thanks for the help and clarification! Also any help pointing me towards if/where this is tested I'll look into adding coverage for it.

**Comment by ntrrgc** [comment]
Thanks! 😄
