### ISSUE TITLE
Health Check spits out an error when checking for the Ruby provider when the Ruby provider is disabled.

### ISSUE THREAD

**Issue by TheDoctorsLife** [neovim/neovim#6107]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? no
- Operating system/version: Linux 4.9.9_1 on the Void Linux Distro.
- Terminal name/version: Terminator 1.0
- `$TERM`: xterm-256color

### Actual behaviour
Neovim spits out:
![error screenshot](http://i.imgur.com/xeIWXIO.png)
### Expected behaviour
Neovim should just say that ruby is disabled and go about its day rather than erroring out.

### Steps to reproduce using `nvim -u NORC`
You need to add ``let g:loaded_ruby_provider = 1`` to your nvim init.vim config file, then:

```
nvim -u NORC
:CheckHealth
```

**Comment by justinmk** [comment]
Ah, this wasn't an anticipated situation. Thanks for reporting.

**Comment by blueyed** [comment]
Hmm.. within jedi-vim I assumed/suggested to use `0` instead: https://github.com/davidhalter/jedi-vim/pull/674#discussion_r100897101.
This makes it easier to check for then also having to look for the `Call` function (https://github.com/neovim/neovim/commit/9451647d9b9218f679afdf26edddab383b0898a7#diff-2d7f214e0c52c9cb5f1601bdfe0e46b6R233).

**Comment by justinmk** [comment]
@blueyed Thanks for the notice. Is that a convention/trick that you've seen used elsewhere? It's not documented at `:h provider` and I thought that it might be rather confusing to users if `0` still loads the plugin. Though, on reflection, I cannot think of any reason why a user would set it to `0`. So I'll revert that change.

**Comment by blueyed** [comment]
@justinmk 
What do you want to revert?
I mean that a user could/should have set it to `0` already to disable it.. the outcome is the same, but then it makes more sense to query it from other places (where 0 means it has been disabled, and 1 means it was loaded really).
I think it's good that `exists` is used here, and therefore 0 and 1 can have different meaning.. (only speaking for the Python provider(s)).

**Comment by blueyed** [comment]
I was looking at the source to find this, when seeing how `has('python')` can be avoided in Neovim (when a user wants to disable it).

**Comment by justinmk** [comment]
@blueyed I need to revert [this](https://github.com/neovim/neovim/commit/9451647d9b9218f679afdf26edddab383b0898a7#diff-8a1575ab1d8124f012f64c63cdaf6de3R7), right?

**Comment by blueyed** [comment]
@justinmk 
Yes.

**Comment by TheDoctorsLife** [comment]
Yeah no problem, won't have noticed it if I wasn't having issues at the time installing the ruby provider. (Though I got it fixed) Glad I was of service!
