### ISSUE TITLE
Cursor flickering at right bottom of popup menu, with `noshowmode`

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#6115]
reproduce steps:

```
nvim -u NONE  -S test.vim test.vim
```

Enter insert mode, then press  `<c-x><c-o>`, then `"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk...."`

![animation](https://cloud.githubusercontent.com/assets/4538941/22916933/bb80f284-f2bc-11e6-8058-c0ec8ab0aeab.gif)

minimal vimrc

```vim
func! Foo(init,base)
        if a:init
                " col 1
                return 0
        endif
        let l:matches =  ['abcdef','abcdefg','abcdefghijkl','abcdeghijkl']
        return { 'refresh':'always', 'words': l:matches }
endfunc

set omnifunc=Foo
set completeopt=menu,menuone,noinsert,noselect
set noshowmode
```

**Comment by justinmk** [comment]
Cannot reproduce this on NVIM v0.4.0-501 35362495c (macOS + Terminal.app with/without tmux)
