### ISSUE TITLE
Tabclose and switch to left tab feature

### ISSUE THREAD

**Issue by samuelololol** [neovim/neovim#6116]
Hi, there was a patch/todo on vim
https://groups.google.com/forum/#!topic/vim_dev/3fq0WJmlHeg

Is there any chance for Neovim to complete this feature?

**Comment by justinmk** [comment]
Probably Vim would accept it if there were test coverage. Test coverage is also required for it to be accepted to Neovim.

Though I would prefer instead adding a "previous tab" concept, that would be more useful.

**Comment by powerman** [comment]
In Vim I've used this (in vimrc):
```vim
""" After closing a tab open previous tab instead of next tab.
let s:leave_tab = 0
autocmd TabLeave *      let s:leave_tab = tabpagenr()
autocmd TabEnter *      if tabpagenr() != 1 && tabpagenr() == s:leave_tab | tabprevious | endif
```
Looks like it's time to rewrite this in Lua…
