### ISSUE TITLE
Descriptive Maps

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#6123]
I was thinking about trying to add some introspection to mappings built into nvim. I have seen a few plugins out there, and worked on one myself, that would allow you to inspect your mappings with some information in them. Most of them rely on adding a plugin, so I don't see widespread adoption of them, and some of them are slow because they're implemented in vimscript, as opposed to being builtin parts of the maps.

Seeing some presentations of spacemacs, with the abiilty to see what a mapping means (in human words) in real time, inspired me to think about how to get something done like that in vim. I think other plugin maintainers could certainly use something like this, for example a host could be made for denite or similar plugins that would get all your mappings and your descriptions, and you could search through them. It would also be helpful for people when they get a new plugin, they could see what mappings that plugin has without have to dig through all the docs again. It would also allow people to have more "living documentation" where the comments they write in the code show up in front of the user, rather than having to keep two locations for information (where you write the code and the `docs/` folder).

I was thinking about trying to add some stuff into nvim so people could do something like this:

```vim
" Not sure I like one more than the other here...

" Add a new modifier to a map, with a "end" modifier, where a description can be added
nnoremap <describe> lhs rhs
    \ <description> Now I can type whatever I want to describe this.

" New command where you specify the mode, the lhs and then a description.
nnoremap lhs rhs
if has('nvim-version')
    describe n lhs Now I can type whatever I want to describe this
endif
```

Then you would be able to get them with the `maparg` command:

```vim

let map_dict = maparg('lhs', 'n', v:false, v:true)
echo map_dict
" { ..., 'description': 'Now I can type whatever I want to describe this'}
```

I guess a couple questions:
    - Does anyone have any other suggestions, better ideas for this concept?
    - If implemented, would this be accepted?
    - Does anyoen have any idea if this would get accepted at Vim?

Anyways, I'm open to suggestions or rejections :)

**Comment by justinmk** [comment]
Might want to make it tags-based somehow, so that documentation can be used as the "single source of truth". That also encourages documentation. For one's custom mappings this would require something like `~/.config/nvim/doc/init.txt`, but I don't think that's any different than having a bunch of `:define` commands in one's vimrc.

**Comment by tjdevries** [comment]
Hmm, I thin tags-based would be very difficult. I already did some exploring into how vim defines its mappings, and there are a couple places where it would be pretty easy to hook into the system to put the description field into the same struct as the rest of the mapping, and then display it in `maparg`. I'm not sure how you would be able to do that with the tags-based way.

In terms of implementation, the first one is quite easy actually, the problem is that if you then source your init.vim in an older version of nvim, or in Vim itself, you'll get errors. That's why I suggested the second one, so that you could just wrap it in a version check or something similar to that.

**Comment by tjdevries** [comment]
I rather like the way emacs does this with:

```
(defvar my-var-or-other-stuff t
  "A description right with the variable")
```

So I was trying to go with something like that.

**Comment by tweekmonster** [comment]
In terms of portability and a more-broad way of adding simple descriptions for more than just maps, what about using `#!` which is effectively a comment:

```vim
#!doc: describe next eligible map or command
nmap ...
```
The "next eligible map or command" would be any map or command that's created after the doc line has been seen within a scope (maybe just the script's scope).  This could cover dynamically created maps and commands.  Once the doc has been used to describe something, it's discarded.

I'd say that this should only be a single line to encourage keeping it short.

For referencing docs:

```vim
#!doc: See |some_tag|
nmap ...
```

The "See" part being optional.  Problem here is that vim's docs aren't consistent enough to be machine readable.  And multiple tags could be lumped into the same place to describe a workflow instead of the key itself.  If it's displayed literally in some special buffer, `<cr>` on a tagged doc line could jump to the doc page.

**Comment by justinmk** [comment]
> put the description field into the same struct as the rest of the mapping, 

Holding all these descriptions in memory seems wasteful. That's why tags or some other offline index, seems more appropriate.

> , what about using #! which is effectively a comment

We generally avoid non-trivial VimL extensions.

**Comment by tweekmonster** [comment]
> We generally avoid non-trivial VimL extensions.

What about adding the line number to the `maparg()` return dict?  With the `sid` and `lnum`, a plugin could easily do this kind of parsing by scanning backward for a doc comment.

**Comment by justinmk** [comment]
> What about adding the line number to the maparg() return dict? With the sid and lnum, a plugin could easily do this kind of parsing by scanning backward for a doc comment.

No objection, but... to get descriptions for all of the built-in mappings we would need to parse the existing docs. So doesn't it make sense to use the docs as the definitions?

**Comment by fmoralesc** [comment]
Couldn't the docs (as a general list of user defined mappings, like the one for installed plugins) be generated from these doc comments too?

Also: what will the data be? Just the description or the description plus a short name too?

**Comment by justinmk** [comment]
> Couldn't the docs (as a general list of user defined mappings, like the one for installed plugins) be generated from these doc comments too?

Yes they could, but first they would need to be extracted from the existing docs...

**Comment by tweekmonster** [comment]
```vim
:vimgrep /^|:\@!/gj $VIMRUNTIME/doc/index.txt
```

**Comment by tweekmonster** [comment]
> So doesn't it make sense to use the docs as the definitions?

It makes sense for the built in docs, but definitely wouldn't for existing plugin docs.  It could be a case for encouraging a documentation format, but that doesn't take care of the cases where maps are defined from user configs.

The idea behind @tjdevries's request is giving a searchable live view of "what should I press to do X?" which wouldn't work if the keys are based on what's hard coded in the docs.  This could also add another facet of information for the idea of implementing a searchable command palette.

**Comment by tjdevries** [comment]
> Holding these descriptions ... in memory seems wasteful.

I think we could just set an option for this. If people don't want to have descriptions populated, we can just not read them or store them.

I personally don't see the majority of these descriptions being longer than something like:

`Split window to the top right`

We already keep the lhs, rhs, and several other variables for the mappings in memory. I don't think anyone has been two concerned about their mappings taking up 80k of mem, so I don't really see why they would complain about 160k of mem. I personally would trade off a lot more than that to get introspection that plugin authors could all agree on. This would make plugin and feature discovery much easier.

I can understand the concern though. I just think the people who will see the most impact are the people who already have many plugins installed, other processes running (like a python interpreter), etc.

> What about adding the line number to the maparg()

I see this as viable, but would then mean if you wanted the information for all the mappings, nvim would have to open and read through all the files to get the documentation (at least, I'm assuming that's what it would have to do). That seems a lot less efficient than just storing them directly. And then you'd probably cache them anyways, so you're back in the same location.


As for parsing the docs, I had an idea a bit ago that maybe we could generate `quickref.txt` from some machine readable original format, like yaml, lua or something like that. The output would be done during build, but this way you could also get the information on the builtin items in Vim as well. Although I would think that's probably for a different issue or PR. I'm not as concerned immediately with getting information from vanilla nvim.

I think if we had an ability for an accessible definition to be written near or at the same time as a mapping (and then maybe later for functions or variables) then someone will probably just write a vim docs generator from those mappings. And then you would just paste those into your vim docs for your plugin.

@tweekmonster is correct that the main idea I want to have is a live updating command pallete that would allow users to not only see their mappings, but what they do (or what the plugin authors intended them to do). Could be searchable by lhs, rhs and/or description depending on how the author implemented it (denite source, fzf plugin, etc.).

And finally, I think we could just put somewhere in the documentation about this, a helper function for people to use in the meantime if they wanted to include descriptive mappings but still be compatible with vim or older version of nvim. Users themselves could just choose to be using a new version nvim and not have to worry about it. The function could be something like:


```vim
function! s:safe_map(mode, modifiers, lhs, rhs, description)
  if has('nvim-feature')
    let map_string = printf('%s %s <describe> %s %s <description> %s',
          \ a:mode, a:modifiers, a:lhs, a:rhs, a:description)
  else
    let map_string = printf('%s %s %s %s',
          \ a:mode, a:modifiers, a:lhs, a:rhs)
  endif

  execute map_string
endfunction
`

**Comment by tweekmonster** [comment]
> I see this as viable, but would then mean if you wanted the information for all the mappings, nvim would have to open and read through all the files to get the documentation (at least, I'm assuming that's what it would have to do). That seems a lot less efficient than just storing them directly. And then you'd probably cache them anyways, so you're back in the same location.

Yes, but it would at least be on demand.  People who don't like the idea of it won't have anything to complain about.  Besides, nvim is reasonably fast at reading files.  With minor optimizations like sorting the maps by source so you're not re-opening scripts.

I wrote this the other day (shut up):

```vim
function! s:runtime_grep(globpat, ...) abort
  if !a:0
    echohl ErrorMsg
    echomsg 'A pattern is required'
    echohl None
    return
  endif

  let pattern = join(a:000)
  call setqflist([], 'r')

  for path in globpath(&runtimepath, a:globpat, 0, 1)
    if filereadable(path)
      try
        execute 'vimgrepadd /'.pattern.'/gj' path
      catch
      endtry
    endif
  endfor

  if !empty(getqflist())
    copen
  endif
endfunction

command! -nargs=+ RtpGrep call s:runtime_grep(<f-args>)
```

`:RtpGrep **/*.vim ^\s*fu\%[nction]\>` is reasonably fast considering it's scanning all lines in all scripts.  A script for parsing map descriptions would have a limited set of files and target line numbers.

> As for parsing the docs, I had an idea a bit ago that maybe we could generate quickref.txt from some machine readable original format, like yaml, lua or something like that.

This is ideal, but we would be left holding the bag for re-documenting things from upstream.  I think vimdoc is here to stay as long as nvim wants to maintain compatibility with upstream.

> s:safe_map()

This is a decent idea, but this would require plugin authors to maintain "official" boilerplate that might break if the implementation changes.  This would be better if it was a standard function from nvim, but, you know...

![upstream](https://cloud.githubusercontent.com/assets/111942/23084876/9d020c08-f532-11e6-956b-fec50182c1ef.jpg)

**Comment by justinmk** [comment]
An admitted weakness of the tags-based definitions is that it won't be context-dependent. If a plugin is currently active in a buffer, it needs to be able to describe the currently active mappings (where the _same_ LHS may have a different description in some other filetype).

But let's step back. The main task before worrying about any of this, is exposing the mappings programmatically so that fuzzy-finders can actually traverse them. That's going to be far more interesting (and valuable for many other purposes) than the minor question of where to store the descriptions and how to associate descriptions with the mappings.

So step 1 is:

1. Add an API function `nvim_get_keymap({scope}, {mode})`.

**Comment by tjdevries** [comment]
What would the scope parameter specify?

**Comment by wsdjeg** [comment]
I like this feature, before this feature I use Unite to implement this feature.
![2017-02-01_1359x723](https://cloud.githubusercontent.com/assets/13142418/22507351/24af0d74-e8c0-11e6-985e-4a1404b629ed.png)

**Comment by justinmk** [comment]
@tjdevries scope would be "t", "w", or "b".

**Comment by tjdevries** [comment]
@justinmk Where would you recommend building this?

**Comment by justinmk** [comment]
`src/nvim/api/vim.c`

**Comment by tjdevries** [comment]
@justinmk , When using `nvim_get_keymap('buffer', 'n')` would you expect ONLY buffer mappings or (buffer mappings + non-overlapping global mappings) or some other combination I can't seem to think of.

**Comment by justinmk** [comment]
I can see arguments for both, so whichever is easier.

**Comment by tjdevries** [comment]
What about instead of passing in a string, you could pass in a dictionary. 

It could look something like

```vim
{'global': false, 'buffer': false}  " Returns empty list
{'global': false, 'buffer': true}   " Returns list of only buffer mappings
{'global': true, 'buffer': false}   " Returns list of only global mappings.
{'global': true, 'buffer': true}    " Returns list of mappings, with possible overlapping mappings (or we could try and eliminate those)
```

This could also let us add more options in the future. If we added a tab mapping or something like that. Other options would just be assumed false I think.

We could even switch the argument order and make the scope optional, and just have it default to the desired functionality if we wanted.

**Comment by jamessan** [comment]
> We could even switch the argument order and make the scope optional, and just have it default to the desired functionality if we wanted.

I think having the mode first, if we're not just going to use a dictionary, does make more sense.  It's the most common discriminator that would be used.  Other discriminators should, which will likely be optional, should come after it.

**Comment by tjdevries** [comment]
Any examples of an api function that has optional parameters?

**Comment by justinmk** [comment]
> What about instead of passing in a string, you could pass in a dictionary.
> This could also let us add more options in the future.

This is something I've been meaning to nail down, so we can extend API functions in a backwards-compatible way. Per msgpack RPC protocol, function parameters are sent as an array "over the wire". But in most clients, those parameters are bound to an arity. E.g., I just tried adding a `String dummy` parameter to `nvim_get_api_info`, and the python client broke.

How about this: design the API with reasonable parameters, but add a dummy dict as the last parameter "just in case". E.g. in the case of `get_keymap`:

```c
    nvim_get_keymap(String mode, String scope, Dictionary reserved_, Error *err)
```

I'll document this pattern in `:help develop.txt` somewhere.

**Comment by ZyX-I** [comment]
I do not agree with https://github.com/neovim/neovim/issues/6123#issuecomment-280782882: making thing reachable is indeed needed, but this question is rather trivial and is going to be easier to implement: just take internal structures and convert them into API types.

---

I more like the idea with comments, but no “line number then backscan” and different syntax. The problem with “line number then backscan” is that you can no longer offload defining mappings or other things to another function, and this is handy if you want to do something like frawor allows you to do: e.g. have plugin-specific leader without lots of copy-pastes of lengthy options and `:execute`. Also there is an example of language which always keeps documentation: Python. And it works fine. So I think that for descriptions it would be logical to do the following: make comments starting with `""` saved internally and automatically attached to whatever is the next definition of function/mapping/abbreviation/command/sign/variable (on first iteration it is probably better to just make `:let` discard this data because it raises many questions regarding the implementation), otherwise only discarded when script ends. Additionally make this reachable via the API, but given that now there is no API for defining anything, but variables it may just as well be a part of the argument (i.e. not something which alters state). Dictionary argument with definition is the best option in almost all cases: even signs and functions have enough properties to store them in a dictionary, anything else except variables have more.

Some examples:

```VimL
"" Plugin which does foo
scriptencoding utf-8
" Special-case: `scriptencoding` discards documentation, later saves it somewhere as script documentation

"" Discarded

" Empty line discards documentation

"" Do foo
""
"" :param Number x: Do it with x.
""
"" :return: :math:`x * 10`
function Foo(x)
    return x * 10
endfunction

echo get(function('Foo'), 'doc')
verbose function Foo " Prints documentation above the function

"" Do foo
command -count Foo :call Foo(<count>)

verbose command Foo

function s:DefineMap(lhs, rhs)

    " But only empty line which follows documentation comment

    execute 'nnoremap' get(g:, 'g:foo_leader', '<leader>f').get(get(g:, 'foo_map_overrides', {}), a:lhs, a:lhs) a:rhs
endfunction

"" Do foo
call s:DefineMap('f', ':Foo<CR>')

"" Discarded
```

---

I do not like the idea of dummy parameters: how would you know in advance that it is (not) needed? Better versioned API somewhere, was not this discussed already? When initiating connection request a specific version and when altering API keep an adapter for some specified time so that dispatcher may select proper one. And dummies are also too limited: with versioned API you can decide e.g. that ordering of arguments was inconsistent and reorder them without bumping major version of the application (i.e. stay compatible), only bumping major version of the API. You can never do anything like this with dictionaries.

**Comment by ZyX-I** [comment]
BTW, issue title talks about descriptions. Let’s discuss *descriptions* here, move `nvim_get_keymap` discussion to the PR. Or rename the issue and discuss descriptions elsewhere.

**Comment by justinmk** [comment]
> making thing reachable is indeed needed, but this question is rather trivial and is going to be easier to implement: 

Depends on how the descriptions part is implemented. Extending VimL to support a new syntax doesn't help Lua scripts nor API clients. So the bare minimum is that some sort of function is needed which associates mappings with descriptions. The internals of that function could, later, be re-used if VimL is extended with the comment sugar.

> I do not like the idea of dummy parameters: how would you know in advance that it is (not) needed? 

The contract of such the "reserved" Dictionary is that any args added there in the future _must_ be optional.

> Better versioned API somewhere, was not this discussed already?

We do version the API. But if we need to extend a function we have to create a new function, we can't add optional arguments.

> When initiating connection request a specific version and when altering API keep an adapter for some specified time so that dispatcher may select proper one

That would be better, but that's not implemented. And it's more complicated. Let's not let perfect get in the way of good.

**Comment by ZyX-I** [comment]
> Depends on how the descriptions part is implemented. Extending VimL to support a new syntax doesn't help Lua scripts nor API clients. So the bare minimum is that some sort of function is needed which associates mappings with descriptions. The internals of that function could, later, be re-used if VimL is extended with the comment sugar.

If we have a function that returns a dictionary describing mapping (basically we have it (`maparg()`) and plan to also add an API with the list) there is nothing to discuss: it is already a convention that keys may be added to the returned dictionary without considering it a breaking change.

**Comment by justinmk** [comment]
> If we have a function that returns a dictionary describing mapping (basically we have it (maparg()

There's no function that returns _all_ mappings AFAIK. That's what `get_keymap` is for.

>  there is nothing to discuss: it is already a convention that keys may be added to the returned dictionary without considering it a breaking change.

Sorry, I am confused. We need a function that assigns a description to a mapping, like this:

    nvim_assoc_desc_with_mapping(Integer map_id, String desc)

What did you have in mind?

**Comment by ZyX-I** [comment]
@justinmk I am saying that there is `maparg()` which will return descriptions once they are added. There is a PR with function which returns a list of mappings in a dictionary and nobody doubts that once descriptions are there they may be added to those dictionaries. So there basically is nothing to discuss regarding how to return the descriptions, only how to attach them.

> Sorry, I am confused. We need a function that assigns a description to a mapping, like this:

This subthread was replying to the comment regarding “stepping back and adding function which lists mappings”: there is nothing to discuss about this step in this issue.

**Comment by ZyX-I** [comment]
Regarding `nvim_assoc…`: I am against this. There should be functions `void nvim_define_{entity}(Dictionary  definition, Boolean unique)`: for mappings they may take whatever `maparg(,,, 1)` or new function returns and define a mapping. And Dictionary may contain `description` key: no assoc, add descriptions at definition. I do not know a real use-case when this is not enough.

For VimL there is comments suggestion.

**Comment by justinmk** [comment]
I see now. When I said "associate" you took that to mean at retrieval-time, but I mean define-time.

Regarding the name, `nvim_assoc` was pseudo-code, not a real suggestion. `nvim_define_{entity}` sounds good.

**Comment by ZyX-I** [comment]
I was actually missing such function for `translit3`: needed to run previously defined mappings at some condition only, otherwise run translit3 own mappings. Ended up with creating this function on top of `execute`.

**Comment by tjdevries** [comment]
Now that we have `nvim_get_keymap()`, I've been thinking of this again.

What if we did something like this:

1. Add more types to the `v:t_*` types, including `v:t_mapping`, or potentially `v:t_n_map`, `v:t_i_map`, etc.
2. Add a function `nvim_describe()` where it looks like:

```vim
" call nvim_describe(type, identifier_dict?, description)
call nvim_describe(v:t_map, {'mode': 'normal', 'lhs': ',ex'}, 'This is an example mapping')
```

and then `nvim_get_keymap()` would return `{ ..., 'description': 'This is an example mapping' }`

**Comment by tjdevries** [comment]
I suppose something like `nvim_describe_map('mode', 'lhs', 'description')` would be fine too. And we could just add more as time goes on

**Comment by ZyX-I** [comment]
@tjdevries I would rather go with `nvim_set_doc(Dictionary what, String id, String doc)`. Here `what` is something like `{type: function}` or `{type: "map", mode: "n"[, buffer: 42]}`. Given `set` there should be `get` as well. Maybe `doc` should be `Dictionary`, type-specific (e.g. for mappings it should be something like `{summary: "Frobnicates text", description: "Does a good job at frobnicating text which means transforming it into a useless crap", count: true, register: false, variants: ["characterwise", "linewise"]}` (summary and description are universal, count and register are specific for normal and visual mode mappings, variants is specific to visual mode, etc; function should be able to describe arguments and return separately, etc)).

BTW in some vim-dev thread it was mentioned that `maparg()` output (lhs and rhs) is not reliable. I `nvim_get_keymap` also has this flaw. (Specifically: it should correctly handle both `set cpo-=<  | nnoremap <C-x> <C-c>` and `set cpo+=< | nnoremap <C-x> <C-c>`, current tests reveal that it does not.)

**Comment by ZyX-I** [comment]
I actually more like the idea of `Dictionary doc` with the necessary structure: in any case decent documentation system is assumed to allow specifying such things in a parsable way, in this case we are just wanting to get the results of parsing rather then text to be parsed. It is also a hint to whoever will want to e.g. write a Sphinx plugin for VimL regarding what properties certain VimL entities may have.

**Comment by tjdevries** [comment]
if we specify the structure of each of the different kinds of dictionaries, why not just have different functions?

It seems like a lot to keep track of when using one function with so many permutations. Why not just `nvim_set_doc_map(mode, ...)`?

**Comment by ZyX-I** [comment]
@tjdevries I am imagining a single entry point to new internal documentation system. Also there are not only many differences, but many similarities as well. So either one function. One *file* `src/nvim/api/doc.c` with unique prefix like `nvim_doc` if you don’t like that. But by no means no `nvim_set_doc_map`, if documentation system is there it should be there in one piece.

By the way, why everybody forgot about abbreviations when desiging `nvim_get_keymap`? Menus also have some similarities to mappings, though much less (does nvim-qt display them and if yes how it obtains the menus?).

**Comment by tjdevries** [comment]
Okay, I think the `nvim_set_doc` is fine. I also like the `Dictionary doc` as well. 

As for abbreviations, I figured if someone wanted it, it would be easy to make `nvim_get_abbreviations`. I'm not sure about menus.

**Comment by ZyX-I** [comment]
Which structure to use for obtaining menus was once discussed somewhere in vim-dev. No patches were made though and no more discussion happens ATM.

**Comment by fmoralesc** [comment]
Re: menus: What about https://github.com/neovim/neovim/pull/6322?

**Comment by ZyX-I** [comment]
Forgot about that PR.

**Comment by justinmk** [comment]
Strongly agree with https://github.com/neovim/neovim/issues/6123#issuecomment-312079452 . 

In general I strongly discourage introducing new opaque types, it makes interop more difficult for no reason. E.g., jobs in Nvim are just integers, in Vim they are opaque types. Opaque types are nice for encapsulation and ownership, but emacs (and vim, accidentally) have proven that is counterproductive for a text editor: openness and convention is better.

**Comment by jdhao** [comment]
I do not know about the internal implemntation, but forget about viml and keep it unchanged. Would it be easier that key map description things be done only for Lua apis, i.e., add description to key mappings for nvim_buf_set_keymap() and nvim_set_keymap()?  It makes more sense to give the mapping description when you define it (perhaps adding a field in the `opts` param), not after you have defined it and use some other functions to add a description to it.

If keymap description is done, plugins like [which-key.nvim](https://github.com/folke/which-key.nvim) could benefit by showing pretty description for keymap. Currently, it only shows the raw mappings, which does not make much sense, especially when a user use a config distribution like [LunarVim](https://github.com/LunarVim/LunarVim) and is not very familiar with what that mapping does.

FYI, this is what which-key.nvim currently shows if I press my leader key:

![image](https://user-images.githubusercontent.com/16662357/137623364-8eda6063-1fb0-4170-a8f2-aedae85c2e05.png)

**Comment by justinmk** [comment]
> i.e., add description to key mappings for nvim_buf_set_keymap() and nvim_set_keymap()

No objection to adding an option to those APIs. We also are in favor of adding Luadoc support (would require treesitter).

**Comment by jjant** [comment]
How do we add descriptions with `vim.keymap.set`?

**Comment by zeertzjq** [comment]
Use the `desc` key in `opts`

**Comment by jjant** [comment]
Thanks! That should probably be in the help.
