### ISSUE TITLE
Strange characters on command bar when pressing i for insert mode.

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [neovim/neovim#6125]
- `nvim --version`:

        NVIM 0.2.0-dev
        Build type: RelWithDebInfo
        Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/build/config -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/src -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-A3ZgHq/neovim-0.1.7ubuntu1+git201702122009+3130+23~ubuntu16.04.1/build/include
        Compiled by root@lgw01-53

        Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
        For differences from Vim, see :help vim-differences

           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently?

This is the first neovim version I installed.

- Operating system/version:

    Xubuntu 16.04.1

- Terminal name/version:

    xfce4-terminal 0.6.3

- `$TERM`:

    xterm

### Actual behaviour

When I press `i` for entering insert mode, I see a not properly displayed character in the command input bar:

### Expected behaviour

There should only be the color `:` displayed, not some strange character.

### Steps to reproduce using `nvim -u NORC`

1. press `i`.

Here is a screenshot:

![neovim-screen](https://cloud.githubusercontent.com/assets/11130348/22986296/4f6658d8-f3ab-11e6-95e6-de25bab60785.png)

**Comment by tweekmonster** [comment]
This is a known issue.  See #5990

**Comment by ZelphirKaltstahl** [comment]
@tweekmonster Thanks! Solved. Did not find that one before, but reading it makes the situation clear and explains, why I could not find it before, when searching for open issues : )

**Comment by tweekmonster** [comment]
Glad it helped!   To be fair, I couldn't find that issue it without searching for the solution. 😁  There's more than a few ways to describe this issue.

**Comment by juandavilau** [comment]
In my case i solve it installing gnome-terminal.
