### ISSUE TITLE
no nvim-qt.exe

### ISSUE THREAD

**Issue by badugi** [neovim/neovim#6126]
No nvim-qt.exe in the windows 64build zip file when trying to install neovim, therefore unable to install the windows version of neovim.

**Comment by fmoralesc** [comment]
nvim-qt is an independent project, so you'll have to install it from upstream (https://github.com/equalsraf/neovim-qt/releases).

**Comment by jamessan** [comment]
According to a recent [update] to the Installing-Neovim wiki page, nvim-qt is supposed to be included now.  @justinmk has been working on getting the Windows releases ready, which includes shipping nvim-qt along with nvim.

[update]: https://github.com/neovim/neovim/wiki/Installing-Neovim/_compare/1d13ec3dc3cecfcea5b40333bcc18671c959b738...25785589caa8f3249d03cef6f183a2e01bb32a5a

**Comment by badugi** [comment]
thanks. I'll check from time to time if the windows releases are ready yet.

**Comment by justinmk** [comment]
Yes that was a premature edit. Give me until end of today.
