### ISSUE TITLE
Pasting with _term's_ paste function in insert mode turns weird 

### ISSUE THREAD

**Issue by ozra** [neovim/neovim#6127]
- `nvim --version`: 0.1.7 (built from source)
- Vim (version: 7.4, patches: 1-1832) behaves differently
- Operating system/version: Ubuntu 16.10
- Terminal name/version: gnome-terminal/3.18.3
- `$TERM`: `xterm-256color: command not found`

I just tried out nvim - with symlink to my `.vimrc` (blowfish crypt was the only thing not working) - but it behaves mysteriously for a reoccurring case of mine: 

I very often copy/paste using the terms key commands, because I need to copy from/to vim in a ssh or such, from local vim, term or web-page.

1. copy some text from a terminal (`<C-S-c>`), web-browser (`<C-c>`) or other
2. go to another term where I run vim, locally or via ssh => enter insert mode => ctrl+shift+v - pasting with terms func

For this case I tried copying from _vim_ in term, plain term output and firefox into _nvim_, using insert-mode and terminals paste command (I need that for the ssh situation).

On a sidenote: If I use `p` it works as it should (nvim syncs with the clipboard).

### Actual behaviour
- Each line is indented _one space_ deeper then the previous
- Tab-key now suddenly inserts tabs instead of spaces

### Expected behaviour
- See the text as it looked where I copied it from (vim works - I have that "don't-auto-indent-pastes" flag in)
- Tab-key should continue to indent 3 spaces just as before paste - just as configured.

**Comment by justinmk** [comment]
> I have that "don't-auto-indent-pastes" flag in)

You mean 'pastetoggle'? Or 'paste'? Try _not_ setting that. 

It's a known issue. Problem will be addressed by https://github.com/neovim/neovim/pull/4448

**Comment by ozra** [comment]
Alright.

**Comment by ozra** [comment]
Just a quick follow up, please hint me what, if anything, to do with it: as soon as I paste anything in insert mode `softabstops` seems to be set to `0` which makes it jump eight steps, and at some point, can't figure out how/why, it inserts tabs instead.

And, yes it's the `paste` flag I've got - I do this "cross boundaries" quiet often, so I haven't bothered with a solution to get autoindenting in. I guess I could simply make sure autoindent/magic/whatever is enforced off in my conf, just so no other conf turns it on implicitly - to get rid of the paste flag.

**Comment by justinmk** [comment]
Nothing is clear. When are you setting the paste flag, precisely?

**Comment by ozra** [comment]
It's been constantly set the last five years or so X-/
The odd thing about the ordeal, was the softabstops loosing its value - I figured that was worth noting.

**Comment by justinmk** [comment]
that is not how that feature is supposed to be used and I presume it is breaking all kinds of things.

**Comment by ozra** [comment]
perhaps - it has worked so far in oldschool vim without troubles, however, once again, I just wanted to point to the fact that those vars lost their values, which might indicate something of goofyness in the code beyond the misuse of some feature. Thatäs my ordeal.
Anyway - if it's not helpful, just close the issue, ok :-)
Keep up the good stuff!
