### ISSUE TITLE
Installing Neovim on Ubuntu Trusty causes Vim to read Neovim config files, causing errors.

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#6133]
- `nvim --version`: Doesn't matter
- Vim (version: ) 7.4
- Operating system/version: Ubuntu Trusty
- Terminal name/version: Not relevant
- `$TERM`: Not relevant

### Actual behaviour

After installing Neovim on Ubuntu Trusty, Vim (for some odd reason) reads Neovim config files and throws errors because of that (for obvious reasons), when `vim` is ran inside of a Neovim TERMINAL.

### Expected behaviour

Vim should not read Neovim configs.

### Steps to reproduce using `vim`

For example:

```sh
> sudo apt-get install neovim
> nvim
# type :term<cr>
> which vim
/usr/bin/vim
> vim
Error detected while processing /usr/share/nvim/runtime/plugin/rplugin.vim:
line   15:
E216: No such group or event: CmdUndefined * call remote#host#LoadRemotePluginsEvent(   'CmdUndefined', expand('<amatch>'))
Press ENTER or type command to continue
```

When outside of a Neovim terminal, this does not happen.

**Comment by tjdevries** [comment]
Pretty sure that's from setting `$VIMRUNTIME` or something like that. Not sure what could really be done about that.

**Comment by justinmk** [comment]
Right, VIMRUNTIME. Set it appropriately if your want to run Vim in `:terminal`.

**Comment by jamessan** [comment]
We probably shouldn't export `$VIMRUNTIME` into `:terminal`'s environment.

**Comment by justinmk** [comment]
Well, that would be a special case. No strong opinion about it though.

**Comment by jamessan** [comment]
`$VIMRUNTIME` is already a special case. :) The user isn't expected to set it in their environment, unless they specifically want to deviate from nvim's default.
