### ISSUE TITLE
HOME/END key doesn't work in nvim which is run in tmux.

### ISSUE THREAD

**Issue by ya790206** [neovim/neovim#6134]
- `nvim --version`: 0.1.7 or v0.2.0-558-g13ce5fd
- Operating system/version: Ubuntu 16.04
- Terminal name/version: GNOME Terminal 3.18.3
- `$TERM`: xterm-256color
- tmux version: 2.1 or 2.4

### Actual behaviour

HOME/END key doesn't work in nvim which is run in tmux.

### Expected behaviour

HOME/END key should work in nvim which is run in tmux.

### Steps to reproduce using `nvim -u NORC`

$ tmux
$ nvim -u NORC

HOME/END key doesn't work in any mode.

**Comment by justinmk** [comment]
xterm-256color isn't correct when running in tmux. Use screen-256color. If it still doesn't work, home/end keys are covered in other issues, e.g. https://github.com/neovim/neovim/issues/6014

**Comment by ya790206** [comment]
It works after I set $TERM to screen-256color. Thanks.

**Comment by semihalf-ostruszka-andrzej** [comment]
I do have this problem (and setting TERM=screen-256color is not a solution for me).
Don't want to open another issue for the same problem - should I?  The actual setup is:
## General
OS: Ubuntu 16.04.4 LTS
term: GNOME Terminal 3.18.3
nvim: 0.2.2 (from the ppa repository)
## Non-tmux config
$TERM (outside of tmux):
```
$ infocmp | grep 'term\|khome\|kend'
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
	kcuu1=\EOA, kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
```
In this setup nvim works correctly - reacts to them in normal/insert and insert <HOME>/<END> when pressed after ^V.

## Tmux config:
$TERM (inside tmux):
```
$ infocmp | grep 'screen\|khome\|kend'
#       Reconstructed via infocmp from file: /lib/terminfo/s/screen-256color
screen-256color|GNU Screen with 256 colors,
        kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
```
tmux: 2.1 (from the ubuntu's repository)
In this setup I see correct sequences being sent by the terminal (ESC[1~ and ESC[4~) in shell when quoted however nothing happens in tmux (nothing being shown when pressed after ^V).  In the same tmux when I run vim I the keys are handled properly (the only difference I see from the above setup with nvim is that when pressed after ^V I get the terminal sequence chars and not <HOME>/<END>).

I would appreciate any tip how to fix that (if anybody reads this old post :)).
Best regards
Andrzej

**Comment by aostruszka** [comment]
I do have this problem (and setting TERM=screen-256color is not a solution for me).
Don't want to open another issue for the same problem - should I?  The actual setup is:
## General
OS: Ubuntu 16.04.4 LTS
term: GNOME Terminal 3.18.3
nvim: 0.2.2 (from the ppa repository)
## Non-tmux config
$TERM (outside of tmux):
```
$ infocmp | grep 'term\|khome\|kend'
#	Reconstructed via infocmp from file: /lib/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
	kcuu1=\EOA, kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP,
	kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
```
In this setup nvim works correctly - reacts to them in normal/insert and insert <HOME>/<END> when pressed after ^V.

## Tmux config:
$TERM (inside tmux):
```
$ infocmp | grep 'screen\|khome\|kend'
#       Reconstructed via infocmp from file: /lib/terminfo/s/screen-256color
screen-256color|GNU Screen with 256 colors,
        kcuu1=\EOA, kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
        khome=\E[1~, kich1=\E[2~, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
```
tmux: 2.1 (from the ubuntu's repository)
In this setup I see correct sequences being sent by the terminal (ESC[1~ and ESC[4~) in shell when quoted however nothing happens in tmux (nothing being shown when pressed after ^V).  In the same tmux when I run vim I the keys are handled properly (the only difference I see from the above setup with nvim is that when pressed after ^V I get the terminal sequence chars and not <HOME>/<END>).

I would appreciate any tip how to fix that (if anybody reads this old post :)).
Best regards
Andrzej
PS. If you happen to see this comment twice - sorry.  Previously I entered it from the wrong account.

**Comment by aostruszka** [comment]
Sorry for the noise, I got here via the google search and only found #8027 later.  Will wait for the upgrade.

**Comment by abouteiller** [comment]
Problem still exists when using `TERM=tmux-256color` with version neovim 0.2.2 and tmux 2.6.

**Comment by blackdracula18** [comment]
btw i still have this problem, HOME and END keys aren't working
even though my term is set to  256color

**Comment by mfiano** [comment]
Same issue here

**Comment by statquant** [comment]
My too on nvim v0.5.0-23-gafd576ee9 and tmux 2.5and TERM=xterm-256color

**Comment by redhatturtle** [comment]
Same problem here, started a few weeks ago only.

- OpenSUSE Tumbleweed
- Keys work on ZSH in tmux and in vim
- TMUX 3.1c
- $TERM = tmux-256color or screen-256color
- NVIM v0.4.4

```
NVIM v0.4.4
Build type: RelWithDebInfo
moonjit 2.2.0
Compilation: /usr/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.4.4/build/include
Compiled by abuild@OBS

Features: +acl +iconv +tui
```

**cat -v** in tmux
- Home = `^[[1`
- End = `^[[4

**Comment by lywschxd** [comment]
Same issue here on NVIM v0.4.4 and TERM=xterm-256color

**Comment by cryptomilk** [comment]
Add the following to your `.tmux.conf`:

```
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
```

**Comment by yriveiro** [comment]
> bind-key -n Home send Escape "OH"
> bind-key -n End send Escape "OF"

It took me a week to get to your comment, you save me :)

**Comment by kyb3rcipher** [comment]
> Add the following to your `.tmux.conf`:
> 
> ```
> bind-key -n Home send Escape "OH"
> bind-key -n End send Escape "OF"
> ```

print("Thank you <3");

**Comment by tacerus** [comment]
This solution makes it work in `nvim`, but in the shell, in which I use HOME and END as well, this now prints a bunch of "OH"'s and "OF"'s.

I don't quite understand why the "default" behavior (with `term=screen`) works in `vim` but not in `nvim`, but I assume I will have to look into automatically setting the remote TERM, which is a bit cumbersome to do as I work on a lot of different remote operating systems with different levels of access.

**Comment by dereckson** [comment]
I concur with tacerus, using a proper recommended configuration, ie:
* TERM at "xterm-256color" OUTSIDE tmux
* TERM at "screen-256color" or "tmux-256color" for italics support INSIDE tmux
* no rebinding at tmux level

A very coherent HOME/END output is produced from guake, terminator and gnome-terminal (three libvte based) terminals:

```
$ tput khome | cat -v; echo
^[[1~
$ tput kend | cat -v; echo
^[[?1l^[>
```

Those keys are correct for the terminfo and termcap configuration for "screen-256color".

Those keys work on:

- bash and nano (GNU readline)
- vim
- zkbd/zle (a mechanism to configure shortcuts for zsh)

Neovim seems clearly the only software not to support an UNHACKED term configuration, so I'm afraid the different tmux "fixes" broke it.

**Comment by dundargoc** [comment]
@dereckson mind opening a new issue? I don't want to reopen this since there's a lot of noise in this thread.

**Comment by randomizedthinking** [comment]
After playing with the issue, I found that the keys `^[[1~` and `^[[4~` are not received by neovim.

The following configurations do NOT work. Seems these escaped sequences are filtered out by neovim.

```vimrc
inoremap ^[[1~ <Home>
inoremap ^[[4~ <End>
```

**Comment by Sleepful** [comment]
For any using kitty terminal, add this to the kitty.conf

```
# key codes necessary when using nvim + tmux + kitty
map home send_text all \x1b[7~
map end send_text all \x1b[8~
```
