### ISSUE TITLE
ubuntu 16.10 stable release not found in the ppa

### ISSUE THREAD

**Issue by ilcn** [neovim/neovim#6140]
- `nvim --version`: stable
- Vim (version: ) behaves differently?
- Operating system/version: ubuntu 16.10
- Terminal name/version: zsh
- `$TERM`:

### Actual behaviour
neovim package not found in the stable ppa, but found in the unstable ppa.
from apt:

W: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/neovim-ppa/stable/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by praveendhawan** [comment]
Even when I tried to install using apt I got the same message.

**Comment by ilcn** [comment]
If you have the same environment, please try the unstable release. I was able to get it there.

**Comment by timeyyy** [comment]
the ubuntu section has recently been updated, https://github.com/neovim/neovim/wiki/Installing-Neovim, have you tried following the directions there?

**Comment by ilcn** [comment]
ooops, seems to be the same issue. I figured it out just by trying the unstable PPA, but definitely skipped that line. 
Thanks
