### ISSUE TITLE
neovim remains in insert mode after leaving terminal mode and opening a manpage

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6144]
- `nvim --version`: NVIM v0.2.0-574-g14fc482
- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.12.3
- Terminal name/version: iTerm 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
With the below augroup, if you open a manpage after leaving terminal mode, you will end up in insert mode in the manpage.

### Expected behaviour
Neovim should be in normal mode in the manpage.

### Steps to reproduce
init.vim:
```vim
augroup nhooyr_terminal
  autocmd!
  autocmd BufEnter term://* startinsert
augroup END
```

(these steps are incorrect, see https://github.com/neovim/neovim/issues/6144#issuecomment-281021454)
```
nvim -u init.vim
:terminal
<C-N><C-\>
:Man printf
```

Now you'll be in insert mode in the man page. I don't think this should happen. Neovim should exit insert mode and be in normal mode by the time the manpage is opened.

**Comment by justinmk** [comment]
That means  BufEnter is triggered by Man, right?

**Comment by nhooyr** [comment]
Even if it is, the pattern is `term://*` so it shouldn't match. So insert mode shouldn't be entered.

It's even weirder. It actually requires the following steps:

```vim
nvim -u init.vim
:split
:terminal
<C-N><C-\>
:Man printf
```

For some reason, the `:split` is necessary to reproduce.

**Comment by justinmk** [comment]
What I mean is BufEnter seems to be triggered on the `term://` buffer. Isn't it possible that Man is doing that somehow (perhaps temporarily switching to the `term://` buffer)?

**Comment by nhooyr** [comment]
~~Seems like you're right, it seems to be `s:find_man()` in `autoload/man.vim` that is triggering this. I added a BufLeave autocmd but it does not fix this.~~

~~I also noticed that you have to be on the terminal split in order to trigger this. On any other open window, it does not work.~~

Ok so I figured it out, what's happening is just `startinsert | split`. The reason the `BufLeave` autocmd doesn't work is because of https://github.com/neovim/neovim/blob/ddab4661f7acad985096138b0c29a2b7e569022a/runtime/autoload/man.vim#L50-L52

The reason you have to call `:Man` from the terminal split is because `s:find_man` searches all the windows and after it leaves a terminal window, the `BufLeave` autocmd is triggered and insert mode is left, but if it ends up on the same window it started, it does not leave, it does a `noautocmd split` so the `BufLeave` autocmd is not triggered.

I've got a fix for this coming up in a few minutes.
