### ISSUE TITLE
Packaging: Windows appveyor build does not have :GuiFont etc

### ISSUE THREAD

**Issue by raghur** [neovim/neovim#6145]
- `nvim --version`: NVIM v0.2.0-621-ge901868f
- Vim (version: ) behaves differently? NA
- Operating system/version: Windows 8.1
- Terminal name/version:
- `$TERM`:

### Actual behaviour
Missing `:GuiFont` and related in the packaged nvim-qt binary

### Expected behaviour
Should be able to use `:Guifont`

### Steps to reproduce using `nvim -u NORC`
Follow instructions for windows installation on wiki. open nvim-qt and try :GuiFont

**Comment by justinmk** [comment]
Working on it.

**Comment by raghur** [comment]
unzipping the latest nvim-qt from equalsraf's appveyor over neovim.zip seems to fix it. It's due to the missing runtime files that are bundled in neovim-qt.

https://blog.rraghur.in/2017/02/neovim-on-windows.html
-R
