### ISSUE TITLE
ex in init.vim

### ISSUE THREAD

**Issue by nvanggaard** [neovim/neovim#6146]
- `nvim --version`:
0.1.7

- Vim (version: ) behaves differently?
8.0
- Operating system/version:
Arch Linux 4.9.8-1-ARCH

- Terminal name/version:
- `$TERM`:
Termite v12

### Actual behaviour
When i open nvim in it uses the .vimrc config if I have `set ex` in my `init.vim` file.
If I remove the `set ex` it only uses `init.vim`

### Expected behaviour
Not to use .vimrc

### Steps to reproduce:
make a init.vim file which only contains:
`set ex`

**Comment by wsdjeg** [comment]
I just read `:h 'ex'`, and I think it is `.nvimrc` instead of `.vimrc`. BTW my neovm is 0.1.7

**Comment by jamessan** [comment]
Please provide exact instructions on how to reproduce the issue and a clear description of the problem.  As already noted, nvim reads `.nvimrc` not `.vimrc` when `'exrc'` is set.

In attempting to reproduce what I think you are describing, I added `set exrc` to my init.vim and then started nvim from my home directory (which also has a `.vimrc` file).  According to `:scriptnames`, my `init.vim` was loaded and my `.vimrc` was not, as expected.

**Comment by nvanggaard** [comment]
Well, it turns out that I have a nvim (upps) so yes that is what it read.

But I only used `set ex` in init.vim to achieve that NOT `set exrc`

**Comment by justinmk** [comment]
'ex' is an abbreviation of 'exrc', see `:help 'ex'`. What did you expect it to do?

**Comment by nvanggaard** [comment]
I don't know what I have been doing. 

Seems like a mistake from my side - I'm a bit tired. Sorry for wasting your time :)

Keep up the good work !
