### ISSUE TITLE
make <CTRL-L> map to :mode by default

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6152]
Sometimes neovim does not correctly resize (there are several open issues for this).

My instinct is to press <C-L> but that does not work because <C-L> only redraws with the current screen size, it does not check if the screen size has changed. I can trivially remap it to `:mode` which does check for the screen size, but I think it should do so by default since I don't think there is any harm.

**Comment by justinmk** [comment]
I would assume the difference is intentional. Not sure we should change it just to workaround a bug.

**Comment by justinmk** [comment]
resize issues should be mostly resolved by https://github.com/neovim/neovim/pull/6259 and https://github.com/neovim/neovim/pull/6202
