### ISSUE TITLE
holding <C-C> in :!sudo -s makes neovim bug out

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6153]
- `nvim --version`: NVIM v0.2.0-574-g14fc482
- Vim (version: ) behaves differently? Yes
- Operating system/version: macOS 10.12.3
- Terminal name/version: iTerm 3.0.13
- `$TERM`: xterm-256color

### Actual behaviour
When spamming `<C-C>` in `:!sudo -s` neovim bug outs. The sudo process is never killed and continues to prompt in insert mode! It's really hard to explain this in words so I just made a video: https://youtu.be/yWSBTWciUSM

### Expected behaviour
Neovim should not bug out and the `<C-C>` should cancel the sudo command.

### Steps to reproduce
1. `nvim -u NORC`
2. `:!sudo -s`
3. Hold `<C-C>`
4. Now enter insert mode and type, should be super laggy
5. Press enter once or twice and you should see the password prompt appear
6. Repeat step 5 again
7. Now neovim should be normal

Also related #1716

**Comment by jamessan** [comment]
> 3. Hold `<C-C>`
> 4. Now enter insert mode and type, should be super laggy

I don't see how you get from 3 to 4.  Since `<C-c>` doesn't actually kill sudo, nvim doesn't get input focus back.

Either way, this is a known issue for anything trying to read directly from the pty, since nvim runs all `:!` commands via a pipe.  You can see the same behavior using gpg.

**Comment by nhooyr** [comment]
Nvim does get input focus back. See the video. After I hold `<C-C>` and it sudo goes away, the text I type into the buffer remains even though sudo is reading my `<CR>`. It's weird.

**Comment by justinmk** [comment]
Can we not consider this a case of https://github.com/neovim/neovim/issues/1496 ?

**Comment by nhooyr** [comment]
Maybe, I'm not sure which is why I created the issue. It's really weird that `<C-C>` causes this behaviour, even if `:!` is not interactive. Why is sudo just not killed? Why does it cause typing in neovim to kind of lag as I type in after. Why does sudo's password prompt just appear at the top again?

**Comment by jamessan** [comment]
> Can we not consider this a case of #1496 ?

Probably.

**Comment by justinmk** [comment]
> Why does it cause typing in neovim to kind of lag as I type in after

see https://github.com/neovim/neovim/issues/1044#issuecomment-51449458
