### ISSUE TITLE
Garbage in seen in status line

### ISSUE THREAD

**Issue by figgis** [neovim/neovim#6154]
- `nvim --version`: NVIM v0.2.0-618-gb0bbe82 Build type: RelWithDebInfo
- Vim (version: ) behaves differently? No garbage seen
- Operating system/version: Linux lnxfredpl1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
- Terminal name/version: xfce4-terminal 0.6.3 (Xfce 4.10)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

using gnome-terminal I don't have a issue. xfce4-terminal gives garbage. See attached screenshot.

```
$ nvim -u NORC --noplugin
[2 q

Just do :qa and garbage is shown
![nvim](https://cloud.githubusercontent.com/assets/124234/23160195/da474f10-f825-11e6-9cbc-7063b44fa2cc.png)

```

**Comment by figgis** [comment]
![nvim](https://cloud.githubusercontent.com/assets/124234/23160254/0e1d6bda-f826-11e6-8e27-8cd46f12f087.png)

**Comment by justinmk** [comment]
Please search existing issues

**Comment by figgis** [comment]
I did, sorry If I missed something...

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/5990#issuecomment-281132122

**Comment by squarism** [comment]
Just adding that you could try `:set guicursor=` in your `init.vim`.  This worked for me but existing issues have been changing.  So note the date of my comment (future me from google etc).
