### ISSUE TITLE
Neovim not resizing correctly when split resizing in terminator

### ISSUE THREAD

**Issue by xeyownt** [neovim/neovim#6156]
- `dpkg -l | grep neovim`: `0.1.7ubuntu1+git201702201654+3152+23~ubuntu16.04.1`
- Vim (version: ) behaves differently?   `YES`
- Operating system/version: `Ubuntu 16.04.1`
- Terminal name/version: terminator  -  `1.97~ppa3~local` (this is terminator ported on GTK3, from [launchpad](https://bugs.launchpad.net/terminator/+bug/1030562/comments/101) )
- `$TERM`: `xterm-256color`

### Actual behaviour
Neovim does not adapt to new terminal size when splitting (vertical or horizontal) in terminator.

### Expected behaviour
... Well, Neovim should adapt correctly I guess ;-)

### Steps to reproduce using `nvim` (**not** `nvim -u NORC`, sorry for that)
* Open brand new terminator, and maximize it.
* Start neovim.
* Hit `Ctrl-Shift-E` to split vertically or `Ctrl-Shift-O` to split horizontally.
* Notice that neovim now occupies a much narrower space (usually like 10-char wide for vert. split, and like 5-char high for horiz split).

As far as I remember, this bug occured since first version of nvim I tried, like 6 month ago. Also, when in a terminator, you manage to get neovim to have the correct size (for instance with Ctrl-Shift-Z or such), then it seems not possible anymore to reproduce the problem. This would hint to an non-initialized variable or something.

**Comment by xeyownt** [comment]
Correction:
* I noticed the **`nvim -u NORC**` after I posted: Indeed, the bug **does NOT** occur with `-u NORC`...
* So I dig further, and in fact the bug somewhat occurs with `vim.gnome` as well, but in fact regular vim automatically resizes itself correctly when the focus shift from the new terminal to vim terminal. I.e., doing `Ctrl-Shift-E`, you noticed vim is not correctly sized, but doing `Ctrl-Shift-N` (go to next terminal), vim resizes itself correctly when pressing a navigation key (or edit...)

I'll identify who the f*ck is messing with nvim in my plugins...

**Comment by xeyownt** [comment]
Ok, it is *[vim-airline](https://github.com/vim-airline/vim-airline)*...

**Comment by nhooyr** [comment]
There are several issues already open about this.

**Comment by xeyownt** [comment]
I created a bug report in vim-airline, [bug 1409](https://github.com/vim-airline/vim-airline/issues/1409).

**Comment by xeyownt** [comment]
Here the picture. Notice that the text is too much folded, you can also see that in the vim-airline line. Also, some garbage text remains. 

![image](https://cloud.githubusercontent.com/assets/16546024/23200159/184cd07a-f8d3-11e6-8b3b-e931ae192e8e.png)

**Comment by xeyownt** [comment]
For info, Chrisbra closed the bug on vim-airline, telling the issue was fixed in vim in vim/vim@6b40f30 and vim/vim@c10f0e7.

**Comment by brcolow** [comment]
Okay, we will eventually port those patches to Neovim. If you want to lend a hand in order to expedite the process check out [merging patches from upstream vim](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) in the Wiki.

**Comment by justinmk** [comment]
Thanks for reporting. This is covered by other issues.
