### ISSUE TITLE
Switching to fullscreen scrambles airline.

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#6157]
- `nvim --version`: v0.2.0-624-gddab4661
- Vim (version: ) behaves differently? yes
- Operating system/version: Archlinux
- Terminal name/version: gnome-terminal 3.22.1
- `$TERM`: gnome-256color

### Actual behaviour

After switching to fullscreen changing modes scrambles the status line.

### Expected behaviour

Statusline should not be scrambled

### Steps to reproduce

This needs airline to break so NORC is not helpful here.

Start `nvim` in non-maximized terminal, switch to full screen. Switch modes repeatedly.

![screenshot from 2017-02-22 16-12-54](https://cloud.githubusercontent.com/assets/151506/23217647/4bd5e0e8-f91a-11e6-8d66-81f38504cd7f.png)

**Comment by raichoo** [comment]
Workaround: move `nvim` process to background (CTRL-z) and bring it back to foreground.

**Comment by justinmk** [comment]
Does CTRL-L and/or `:mode` also work around it?

**Comment by raichoo** [comment]
´CTRL-L` does not seem to work, it only removes some of the garbage on screen but the status line is still corrupted. `:mode` however does the job.

**Comment by raichoo** [comment]
I've managed to reproduce this error with `nvim -u NORC`. Here are the steps:

- open a new terminal, it should be minimized.
- go into "insert" mode
- switch to full screen mode
- switch between normal and insert mode repeatedly.

This makes the statusline move upward by one line every time you leave insert mode.

**Comment by raichoo** [comment]
I have a feeling that this might be caused by a combination of `wayland` and `gnome-terminal`. Due to problems with `wayland` I had to switch back to `Xorg` and things seem to work fine now.
