### ISSUE TITLE
terminal mode behaviour is inconsistent

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6165]
I find it awkward that a terminal is in terminal mode when created but not when navigated to. When I create a new file with `:new`, I am in normal mode whereas when I create a new terminal, I am in terminal mode (effectively insert mode). This throws me off as when I create terminals as I expect them to be in normal mode, not terminal mode.

What's more is that terminal's behave just like regular buffers when navigating to them, as they don't enter terminal mode automatically, they only do that when created.

I think we should change it so that either terminal mode is automatically entered when navigating to a terminal (consistent with what happens when they are created) or a terminal buffer should begin in normal mode when created (consistent with what happens when a terminal is navigated to).

I think option 2 is better because it's more consistent with how other buffers are handled.

**Comment by justinmk** [comment]
Users can change it if they want, but the right thing to do by default is to never enter insert-mode by default. There's no reason for terminal  buffers to be a "trap" when navigating or switching to them.

Also we should provide `<M-h/j/k/l>` mappings that navigate windows in all modes.

**Comment by nhooyr** [comment]
I'll open a PR for this stuff today.

**Comment by justinmk** [comment]
Thanks. Most of the work will be fixing up the tests, though you should be able to just add `:startinsert` call in most cases.

**Comment by nhooyr** [comment]
I'll open a PR for the mappings later.

**Comment by nelstrom** [comment]
This issue reminded me of [this comment](https://github.com/neovim/neovim/pull/2076#issuecomment-76998265), which sets up the `<M-h/j/k/l>` mappings. I experimented for a while with using the suggested `au WinEnter *pid:* call feedkeys('i')` autocommand, but I found it annoying the way that navigating to a terminal buffer meant I couldn't navigate out of it using the usual `<C-w>{h,j,k,l}` window switching commands. As @justinmk said, the terminal buffers became a "trap". I like the direction that #6173 is going, by defaulting to Normal mode on creation of a new terminal buffer.

**Comment by nelstrom** [comment]
I'd love to see this issue resolved. I've come to expect new `:terminal`s to start off in Normal mode and I keep on being surprised when that's not the case!

@nhooyr Is there anything I can do to help?

**Comment by nhooyr** [comment]
I don't have the time right now to finish that PR off.

You can fork it and create a new PR and finish it off. I'll close mine.

**Comment by nelstrom** [comment]
@nhooyr please keep your PR open for the time being. If I can make the time, I'll use your work as a reference and see if I can have a go at fixing this.

**Comment by nhooyr** [comment]
Ok, no problem.

**Comment by jonahfang** [comment]
When I switch to terminal buffer from other normal file buffer, sometimes the terminal buffer still enter insert mode automatically.
