### ISSUE TITLE
Noevim and Xresources internalBorder

### ISSUE THREAD

**Issue by BigfootN** [neovim/neovim#6171]
Hello,

I am using `URxvt` as terminal. In my `.Xresources` file I have set `URxvt*internalBorder:30`, but when I launch `neovim` there is this enormous gap around `neovim` in my terminal. Is there a way for `neovim` to ignore this setting ?

Thank you very much in advance

**Comment by justinmk** [comment]
How do you "ignore" it in other terminal applications such as nano, Vim, etc?

**Comment by justinmk** [comment]
What version of Neovim?

**Comment by BigfootN** [comment]
Thank for your quick answer.

To answer your your first question, I haven't even tried. To be honest,  for the moment I am interested in neo vim.  And to answer your second question, I am using the package `neovim-git` from Archlinux.

Thank you very much again

**Comment by justinmk** [comment]
If you have a specific request please describe it. We can't answer configuration questions or debug individual environments on the issue tracker.
