### ISSUE TITLE
shell script is not highlighted correctly when a default value of a variable is specified

### ISSUE THREAD

**Issue by lo48576** [neovim/neovim#6178]
- `nvim --version`: NVIM 0.1.7
- Vim (version: 8.0) behaves differently?: yes
  * vim-8.0's syntax highlighting seems to work correctly.
- Operating system/version: gentoo linux (amd64), kernel 4.9.6-r1
  * `uname --kernel-name --kernel-release --machine --operating-system`: Linux 4.9.6-gentoo-r1 x86_64 GNU/Linux
- Terminal name/version: xterm-327
- `$TERM`: `xterm-256color`

### Actual behaviour
Nvim doesn't highlight shell script correctly if:

- the default value of a variable is enclosed with doublequotes `"`, or
- the default value has variable reference (like `${FOO}`).

Additionaly:

- If the default value is enclosed with doublequotes `"` and has a slash `/`:
  * code after the line is also highlighted wrongly.

### Expected behaviour
Highlight them correctly (as vim-8.0).

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:syntax on
:set ft=sh
(input code like `FOO=${BAR:-"abc${BAZ}def"}`)
```

<hr />

vim 8.0: `vim -u NORC --cmd 'syntax on' vim8.sh`
![screenshot-2017-02-26-195258 0900](https://cloud.githubusercontent.com/assets/1246590/23339145/19411330-fc5f-11e6-88e8-f6bdc3dbd9d1.png)

<hr />

nvim 0.1.7: `nvim -u NORC --cmd 'syntax on' nvim.sh`
![screenshot-2017-02-26-195259 0900](https://cloud.githubusercontent.com/assets/1246590/23339149/2792499a-fc5f-11e6-91e4-e6684aaedc7a.png)

<hr />

nvim 0.1.7: `nvim -u NORC`, `:syntax on`, `:set ft=sh`, and manual input
![screenshot-2017-02-26-200547 0900](https://cloud.githubusercontent.com/assets/1246590/23339157/5b55840e-fc5f-11e6-9e24-8c9ddae69f45.png)
Note that last two `if`, `then` and `fi` are not highlighted correctly in nvim.

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track runtime issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. 

Since this problem appears to be fixed in Vim, it will also be fixed in Neovim once we merge the relevant patch from Vim. See https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim
