### ISSUE TITLE
Clearing message after really invoke command (e.g. :marks)

### ISSUE THREAD

**Issue by h-youhei** [neovim/neovim#6183]
- `nvim --version`: 0.1.7
- Vim 8.0 behaves differently? no
- Operating system/version: Arch Linux
- Terminal name/version: urxvt, xterm

Nvim keeps message only when to type : now.
But I want nvim to keep message until  really invoke command.

### Actual behaviour
`:ls<CR>:`
`:marks<CR>:`
nvim keeps message.

`:marks<CR>m`
nvim clears message.

```
:nnoremap ; :
;ls<CR>;
```
nvim clears message.

### Expected behaviour
`:marks<CR>m`
nvim keeps message.

```
:nnoremap ; :
;ls<CR>;
```
nvim keeps message.

### What is benefit of the behavior
`:marks<CR><grave>` offer the way to select mark with message.
`:registers<CR>"` offer the way to select register with message.

**Comment by justinmk** [comment]
Can't this be done with a plugin using execute() ?

**Comment by h-youhei** [comment]
Thank you.
```
function! MarkWithMes()
  marks
  let c = nr2char(getchar())
  execute 'normal! m' . c
  redraw
endfunction

nnoremap m :call MarkWithMes()
```
works how I want.
