### ISSUE TITLE
Popup menu not displaying properly with  long completion in two windows

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#6184]
- `nvim --version`:

```
NVIM v0.2.0-1252-g1f8a3da
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/roxma/.local_software/tmp/neovim/build/config -I/home/roxma/.local_software/tmp/neovim/src -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/home/roxma/.local_software/tmp/neovim/.deps/usr/include -I/usr/include -I/home/roxma/.local_software/tmp/neovim/build/src/nvim/auto -I/home/roxma/.local_software/tmp/neovim/build/include
Compiled by roxma@localhost.localdomain

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/hom
```

- Operating system/version:
```
[roxma@localhost demo]$ uname -a
Linux localhost.localdomain 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

- Terminal name/version:
- `$TERM`:
```
[roxma@localhost demo]$ echo $TERM
xterm-256color
```

### Actual behaviour

![output](https://cloud.githubusercontent.com/assets/4538941/23347053/51d71232-fcda-11e6-941e-ebc73a8ae84c.gif)

- start neovim with minimal vimrc: `nvim -u foo.vim` 
- use `<c-n>` to trigger popup menu

minimal vimrc `foo.vim`:

```vim
set completeopt=menu,menuone,noinsert,noselect
set nowrap
```

**Comment by Shougo** [comment]
This problem is occurred in Vim?
If so, it should be reported in Vim repository.

**Comment by tweekmonster** [comment]
I can confirm this is happening in Vim 7.4.1689 and 8.0.344.  It happens when the buffer scrolls horizontally to display the cursor at the end of the completion.

![compl](https://cloud.githubusercontent.com/assets/111942/23390848/8a68c8b6-fd3e-11e6-88f8-447b55b6474a.gif)

**Comment by Shougo** [comment]
OK.  This is Vim problem.  It should be reported.

**Comment by justinmk** [comment]
@jamessan Mentioned an existing patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=450481#19

**Comment by jamessan** [comment]
Well, I didn't actually check if it was the same issue.  I just recalled a patch related to pmenu from ages ago.  @tweekmonster said it didn't help.

**Comment by tweekmonster** [comment]
I didn't see any effect from the patch.  This is how I applied it:

```diff
diff --git a/src/nvim/popupmnu.c b/src/nvim/popupmnu.c
index 89180f7..6f8cc8c 100644
--- a/src/nvim/popupmnu.c
+++ b/src/nvim/popupmnu.c
@@ -269,6 +269,18 @@ redo:
       if (pum_width < PUM_DEF_WIDTH) {
         pum_width = PUM_DEF_WIDTH;
       }
+    } else if (col > PUM_DEF_WIDTH || col > max_width) {
+      // align right pum edge with "col"
+      pum_col = col - max_width - pum_scrollbar;
+      pum_width = pum_col - pum_scrollbar;
+
+      if (pum_width > max_width + kind_width + extra_width + 1
+          && pum_width > PUM_DEF_WIDTH) {
+        pum_width = max_width + kind_width + extra_width + 1;
+        if (pum_width < PUM_DEF_WIDTH) {
+          pum_width = PUM_DEF_WIDTH;
+        }
+      }
     }
   } else if (Columns < def_width) {
     // not enough room, will use what we have
```

Not sure if that's right.

---

From my understanding of the problem, only the pum area is updated while its active.  When the buffer horizontally scrolls, the pum's area is changed, but nothing is done to restore the cells under the old area.  This is what I came up with to fix it:

```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index ecc794f..59927cf 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -4334,6 +4334,14 @@ static int ins_complete(int c, bool enable_pum)
   int n;
   int save_w_wrow;
   int insert_match;
+  static win_T *lastwin = NULL;
+  static colnr_T lastcol = 0;
+
+  if (lastwin != curwin) {
+    lastwin = curwin;
+    lastcol = curwin->w_leftcol;
+  }
+
 
   compl_direction = ins_compl_key2dir(c);
   insert_match = ins_compl_use_match(c);
@@ -4821,6 +4829,11 @@ static int ins_complete(int c, bool enable_pum)
   compl_was_interrupted = compl_interrupted;
   compl_interrupted = FALSE;
 
+  if (lastcol != curwin->w_leftcol) {
+    redraw_later(CLEAR);
+    lastcol = curwin->w_leftcol;
+  }
+
   return OK;
 }
 ```

![compl](https://cloud.githubusercontent.com/assets/111942/23439666/c07db298-fde5-11e6-99b8-9319becf3532.gif)

It's a little heavy handed with the `CLEAR`, but I don't think anyone would consider long completions or tiny windows to be normal enough for it to matter.

Is there a better way of keeping track of the last `w_leftcol`?

**Comment by jamessan** [comment]
> I didn't see any effect from the patch.

Yeah, it was a shot in the dark.  Looking back at the Debian bug, it's a different issue with the pmenu. :)

As far as your patch, the gif looks good. :) Not sure if there's a better way to handle that.  Maybe propose the current patch upstream and see what happens?

**Comment by tweekmonster** [comment]
@jamessan https://github.com/vim/vim/pull/1524
