### ISSUE TITLE
No scala syntax file?

### ISSUE THREAD

**Issue by RatanRSur** [neovim/neovim#6189]
I wanted to make a PR against the scala syntax file but it doesn't seem to be in the neovim source tree (whereas it is in the vim source tree). Is there a reason it is not in here?

**Comment by mhinz** [comment]
We merge the runtime patches from Vim, so it will pop up in our tree sooner or later.

For the same reason we recommend users to send runtime changes either to the [maintainer](https://github.com/vim/vim/blob/226c53429109f24e31c17016aedfd7fbf7a9aa50/runtime/syntax/scala.vim#L2-L6) or [vim_dev](https://groups.google.com/forum/#!forum/vim_dev).

Thanks!

**Comment by RatanRSur** [comment]
Sure :) I'll reach out to the maintainer over there. Do you know when the next time these will be merged? Considering scala's popularity it seems like high time for it to be supported out of the box.

**Comment by mhinz** [comment]
Whenever someone takes the time to do it. Could be you! :-)

Basically we merge two different kinds of patches from Vim:

1. Normal patches that improve the editor (C code). Not all apply to Neovim, though. We slowly getting closer to being on par with Vim for these kind of patches. (Over 1600 commits by now.)
2. Runtime patches (VimL code). Mostly merged in batches whenever someone feels the urge to do it. We clearly could need a helping hand here.

---

BTW, in this particular case it seems to be good enough to send the PR to https://github.com/derekwyatt/vim-scala, which will merged into Vim later.
