### ISSUE TITLE
Backtick expressions with shell=fish

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#6216]
- `nvim --version`: v0.2.0-754-g32a9808b
- Vim (version: ) behaves differently?
- Operating system/version: Archlinux
- Terminal name/version: gnome-terminal
- `$TERM`: gnome-256color

### Actual behaviour

Using backtick expressions results in an error with `set shell=fish`.

```

    E79: Cannot expand wildcards
    E479: No match 

```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

- `:set shell=fish`
- `:args `echo somefile`

```

**Comment by justinmk** [comment]
We have fish support in `make_filter_cmd`. This may be a matter of adding support to `mch_expand_wildcards`. Perhaps @euclio has looked into this, or can comment on whether this makes sense?

**Comment by raichoo** [comment]
I've created a little patch, review and input appreciated.

**Comment by raichoo** [comment]
Fixed.
