### ISSUE TITLE
Allow plugins to register new API functions for other plugins to call

### ISSUE THREAD

**Issue by SirVer** [neovim/neovim#622]
This is related, but independent to https://github.com/neovim/neovim/pull/509

I played around with the async API that was recently implemented and it got me really excited for the future. I started thinking about how I can implement my plugin UltiSnips in a way that would work with neovim.

Right now, when UltiSnips is loaded it instantiates a Singleton that is the facade for all users of UlitSnips (VimL and python) and implements methods to add new snippets dynamically or query for snippets that can be expanded in the current scope.

This approach will not work with neovim of course. So I request an API to register new RPCs that neovim routes between plugins. Something like 

```
register_rpc("UltiSnips_SnippetsInCurrentScope", python_method_to_call)
```

and any other plugin that wants to call this method should be able to with neovim guaranteeing that the UltiSnips process is up and running.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/5269

**Comment by justinmk** [comment]
Addressed by https://github.com/neovim/neovim/pull/6743
