### ISSUE TITLE
WSL / bash-on-Windows: clipboard support

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#6227]
I have experience with lowlevel development on both Windows and Linux, but I'm wondering if anyone can give me any insight on how/where to implement the clipboard provider for Windows. I've been using (and rely invaluably on) nvim under Bash on Windows.

All insight would be appreciated!

**Comment by justinmk** [comment]
Thanks for helping out!

Perhaps [win32yank](https://github.com/equalsraf/win32yank) could be modified so that it can run in WSL. cc @equalsraf 

If not, some other command-line tool that interects with the clipboard is what I would suggest. The Nvim clipboard "provider" system works pretty well these days, so that model should be followed. 

https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim

**Comment by equalsraf** [comment]
The implementation for the clipboard provider can be seen in https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/clipboard.vim, in all cases it calls a program to get/set the clipboard (xsel, pbcopy, etc depending on the system).  For windows the only available provider is win32yank.

For Bash on Windows you need a program that fullfils this role (get/set the clipboard). I dont known if the windos subsystem for linux provides any API to access the clipboard. If it doesn't then you need a way to call a windows binary that can.

A quick google search reveals this issue https://github.com/Microsoft/BashOnWindows/issues/1069#issuecomment-265864419, the comment suggests it is possible to call a windows binary from bash. I have not looked deeper into it yet, but it seems possible to call win32yank.

**Comment by equalsraf** [comment]
If the previous assumption does not hold, but you can find another way to establish communication between the WSL and a windows program I'd be happy to implement it in win32yank.

**Comment by mqudsi** [comment]
You can directly call Windows binaries from a WSL shell; I have a small shell script I've aliased to `pbcopy` (a holdover from my Mac days) that simply pipes stdin to C:\Windows\System32\clip.exe to copy data to the clipboard.

Windows does _not_ have an equivalent of Mac's pbpaste, so I just wrote this: https://github.com/neosmart/paste (MIT-licensed, should be no problems using it or its binaries).

There's unfortunately basically zero APIs for bash-Windows interop, the only things you have are the ability to call win32 binaries and access to the filesystem via the `/mnt/x/` mount point. To that end, I have no way of _cleanly_ identifying the correct path to clip.exe. For instance, while on my machine it is `/mnt/c/windows/system32/clip.exe`, it is very possible that for someone else with their particular Windows installation, it is actually `/mnt/d/win10/system32/clip.exe`

Now we can work around this with some bash magic (checking the output of `mount`, testing the contents of `/mnt/$x/windows/`, etc) or I can just throw up another binary that will replicate clip.exe's behavior (copy from stdin to the Windows clipboard) and throw it up on github just like with the paste utility from above. That would probably be the cleanest way of doing this, upon reflection.

I'm not sure how cool you guys are with shipping a binary with neovim (along w/ its source, of course) because it's not exactly easy to cross-compile the copy/paste executables to run on the Windows subsystem from within WSL, but unlike Linux & co., Windows has been ABI stable since forever and the attached executable will actually (or should, as I haven't yet tested it) run on Windows 2000 through Windows 10, on both 32-bit and 64-bit platforms, i.e. if there are no moral/philosophical arguments against including a copy.exe and paste.exe with the neovim source distribution to enable system register support under WSL, then there should be no _technical_ reason against doing so due to compatibility issues, etc.

Sorry for the lengthy comment, and apologies if I repeated things that were already glaringly obvious to you - I'm new and don't have any previous metric by means of which I can judge what is already known about Windows to the neovim devs and what isn't :)

For what (little) it's worth, I can also provide signed  (MS Authenticode) binaries to allay and security concerns.

[paste.zip](https://github.com/neovim/neovim/files/822808/paste.zip)

**Comment by justinmk** [comment]
> I'm not sure how cool you guys are with shipping a binary with neovim (along w/ its source, of course) 

We already ship binaries with the Windows package. But it would be nice if win32clip could serve a dual-purpose instead of shipping 3 binaries for the similar purpose. But whatever works is fine in the meantime.

**Comment by mqudsi** [comment]
I just had a look at win32yank. Props on the rust implementation. If you already ship this binary with Windows, you should actually be able to just call it directly even on WSL.

FWIW though, my quick look at win32yank revealed a bug the first commit of my own paste also had, which is the lack of data format checks which can (will?) cause nvim to hang or paste rubbish if the clipboard contains binary or other non-text data.

[The latest versions of paste](https://github.com/neosmart/paste) do away with all dependencies (including the standard library) so it's a lot more barebones than win32yank, but you can feel free to steal any code you want from there for win32yank.

**Comment by equalsraf** [comment]
Thanks @mqudsi, I'll definitely have look

> The latest versions of paste do away with all dependencies (including the standard library) so it's a lot more barebones than win32yank

Awesome, the more clipboard providers the merrier.

Important bit, Neovim expects new line chars comming from the clipboard to be UNIX style (\n) so win32yank has a couple flags to convert back and forth.

**Comment by luzhlon** [comment]
`sudo ln -s /mnt/d/Neovim/bin/win32yank.exe /usr/bin/win32yank`

**Comment by justinmk** [comment]
Assuming @luzhlon's suggestion resolves this. 

Added to FAQ, https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

**Comment by gglanzani** [comment]
@justinmk No, it does not. See https://github.com/equalsraf/win32yank/issues/3

**Comment by justinmk** [comment]
@gglanzani How does that bug preclude closing this issue, which is about being able to access the clipboard in general?

**Comment by bfredl** [comment]
Isn't the issue really that `systemlist()` can't distinguish stdout from stderr? There is many situations where a provider legitimately might print something to stderr.

**Comment by justinmk** [comment]
@euclio has a patch for that I believe, but no PR yet.

**Comment by gglanzani** [comment]
@justinmk Sorry to be pedantic, but I had the impression that you said that, given @luzhlon suggestion to link win32yank, you could access the clipboard and therefore the bug could be close.

My point was that you can indeed access the clipboard, but because of this https://github.com/equalsraf/win32yank/issues/3 you always get `Unable to translate current working directory. Using C:\Users\G` yanked into neovim.

@bfredl Indeed, removing stderr would help :)

**Comment by ryanerwin** [comment]
Note that in `function! provider#clipboard#Executable()` the `exists('$DISPLAY') && executable('xsel') ` check happens before the win32yank.exe check... Since win32yank.exe wouldn't be found on Linux systems, I would recommend checking for that immediately after 'pbcopy'...

I typically run ssh with X11 forwarding enabled in case I want to start `VcXsrv` to view a remote document.... So $DISPLAY is set, and some utility that I installed brought in `xsel` as a dependency... So even after I had win32yank.exe setup, I was still unable to find it...

That said, can't we find a way to make this work expected out of the box instead of requiring an extra symlink? Being part of Windows, the WSL install base could grow quite fast, and it would be nice to save all of those users from to dig into this :-)

**Comment by alynna** [comment]
This works for me:
ln -nfs /mnt/c/Windows/System32/clip.exe /usr/local/bin/clip:

Use like this:
uptime | clip:

**Comment by trusktr** [comment]
Where does `/mnt/d/Neovim/bin/win32yank.exe` come from? Do I need to build win32yank and place it there first?

**Comment by luzhlon** [comment]
@trusktr  `/mnt/d/Neovim`(`D:/Neovim`) is the directory of neovim in my computer, you can replace it with appropriate one.

**Comment by trusktr** [comment]
I installed it with `sudo apt-get install neovim`. I see `which nvim` -> `/use/bin/nvim`

**Comment by jschmold** [comment]
Off topic, but I can't believe someone didn't take the opportunity to call the executable "wank32"

**Comment by niklaskorz** [comment]
I updated the wiki page on the neovim wiki to make it more general and understandable. You can give it another shot with my instructions @trusktr.

**Comment by aohmusi** [comment]
What about this? (copy from [my comment in StackExchange](https://vi.stackexchange.com/questions/12376/vim-on-wsl-synchronize-system-clipboard-set-clipboard-unnamed/20231?fbclid=IwAR0-MhWeZ2JB2lgl0v59x_JKpo7KWi7iJjaNPukr-Vy6ZTVvCP40xVIhhzQ#20231))


```
if system('uname -r') =~ "Microsoft"
  augroup Yank
    autocmd!
    autocmd TextYankPost * :call system('clip.exe ',@")
  augroup END
endif
```

`uname` is a Linux terminal command which returns OS info, such that it will return `Linux` for WSL. Whereas with `-r` flag, the command returns release info of OS, thus it should include "Windows".

`TextYankPost` is a vim event (see `:h TextYankPost` in vim), which detect your text yank activity.

`clip.exe` is a Windows command prompt's command in WSL (see `CLIP /?` in command prompt) which copy `text` or return from a `command` into clipbord via `text | clip.exe` or `command | clip.exe`. Here the `clip.exe` is executed from vim by vim function `system`.

**Comment by justinmk** [comment]
@aohmusi in Nvim you can check `has('wsl')` instead of `system('uname -r') =~ "Microsoft"`, see `:help feature-list`. 

I think we don't use `clip.exe` because it doesn't work perfectly for some cases.
