### ISSUE TITLE
crashed character

### ISSUE THREAD

**Issue by usjeong** [neovim/neovim#6230]
- `nvim --version`: 0.2.0-dev
- Vim (version: ) behaves differently?
- Operating system/version: ubuntu 16.04
- Terminal name/version:
- `$TERM`: zsh

### Actual behaviour
![neovim-crashed-character](https://cloud.githubusercontent.com/assets/24615141/23638114/f7d1c616-0322-11e7-80a9-2cf0a07f2666.png)
some character(?) crashed 
using with jedi, supertab
just tab and space then appear crashed character

### Expected behaviour
appear autocomplete popup

### Steps to reproduce using `nvim -u NORC`
don't appear crashed character, may be reason that supertab don't act and still crashed character in vim status line

```
nvim -u NORC
```

**Comment by justinmk** [comment]
what is a "crashed character"?

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/4867 and `man nvim`. Add

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

to your init.vim, then restart nvim.

**Comment by usjeong** [comment]
thanks alot
