### ISSUE TITLE
fix `cw` and `cW` special case

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#6234]
I've stumbled across this talk on [Vim irregularities](https://vimeo.com/135055397) and what really struck me was the `cw` and `cW` special case. I've never really realized that this was handled differently but can recall situations where this caught me off guard but I went "Oh well, I must have done something wrong… proceed!" and never gave it much thought afterwards. Until now.

Here is an example from the talk. We have the following line:

```
Cool Vim
```

With the cursor on the first letter of the word `Cool`. Lets hit `dwiNeo` and change it into `Neo` here's the result.

```
NeoVim
```

Yep, that makes sense. I've used the word motion here so this should have happened.

Using `d` and then switching to insert mode does not really make that change repeatable so shouldn't we be using `c` for that? But if we do the same with `cwNeo` we get the following result:

```
Neo Vim
```

The reason for this is a special case that is mentioned in the documentation.

```
Special case: "cw" and "cW" are treated like "ce" and "cE" if the cursor is
on a non-blank.  This is because "cw" is interpreted as change-word, and a
word does not include the following white space.
```
I honestly believe that this special case does more harm than good, I want to to able to replace `dwi` with `cw` and make it work just as my muscle memory remembers the motion. It does not throw me off that often but it still happens and I find it somewhat annoying.

Since this special case only seems to be there because `vi` did it that way and we have dropped compatibility anyway, wouldn't it be a good idea to drop this irregularity as well? Yes, that would mean that some people would need to retrain `cw` into `ce` but at least we could get rid of that inconsistency.

**Comment by justinmk** [comment]
There's a patch on vim_dev by @chrisbra to make it optional. We could start with that, make it the default (on master), see what breaks, and then decide if it should stay optional.

**Comment by raichoo** [comment]
I've applied the patch here https://github.com/neovim/neovim/issues/6234

**Comment by nelstrom** [comment]
I think this irregularity is responsible for me programming my fingers to always use `ciw` or `caw` instead of `cw` and `cW`. I'm happy to pay one extra keystroke to be not surprised.

**Comment by justinmk** [comment]
Users who want to try the new option can do this:

```vim
if has('nvim-0.2')                                                                                                                                        
  set cpoptions-=_                                                                                                                                        
endif
```
