### ISSUE TITLE
nvim :term in a large enough window / pane causes a process abort

### ISSUE THREAD

**Issue by chasephillips** [neovim/neovim#6238]
- `nvim --version`:

NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170120-82589-w8ltn5/neovim-0.1.7/build/config -I/tmp/neovim-20170120-82589-w8ltn5/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Co
ntents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170120-82589-w8ltn5/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170120-82589-w8ltn5/neovim-0.1.7/build/include
Compiled by cmp@az.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

- Vim (version: ) behaves differently?  Didn't test -- vim doesn't support :term
- Operating system/version: macOS Sierra Version 10.12.3
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Actual behaviour

1. Open iTerm2, create a new local terminal instance.
2. Expand the terminal to 1280 columns by 112 rows.  (eg. printf '\e[8;112;1280t')
3. Run nvim.
4. Run ':term' to create a new terminal.
5. Process aborts (ie. "[1] 25880 abort nvim" with the process exiting)

I found that creating a new vertical split then running :term doesn't trigger the bug.  The window and view has to be big enough to trigger the bug.  Under a certain column size in the window, the bug doesn't happen.

### Expected behaviour

1. Open iTerm2, create a new local terminal instance.
2. Expand the terminal to 1280 columns by 112 rows.  (printf '\e[8;112;1280t')
3. Run nvim.
4. Run ':term' to create a new terminal.
5. A new terminal is created and nvim continues to run as expected.

### Steps to reproduce using `nvim -u NORC`

1. Open iTerm2, create a window that is 1280 columns by 112 rows.
2. Run `nvim -u NORC`
3. Run `:term`.

**Comment by justinmk** [comment]
@prakashdanish Did you try in iTerm2? @chasephillips can you check whether this occurs on Nvim 0.2.2/3?

**Comment by prakashdanish** [comment]
@justinmk yes, I'm using iterm2 nightly version `Build 3.1.20170512-nightly` with the same window settings as stated in the issue description.

**Comment by justinmk** [comment]
This issue was probably hidden by https://github.com/neovim/neovim/pull/7547 which causes `:terminal` to resize its width less often.

**Comment by justinmk** [comment]
Can't reproduce this, and no backtrace was given. If it's still an issue, post a backtrace:

https://github.com/neovim/neovim/wiki/Development-tips#backtrace-macos--osx
