### ISSUE TITLE
mappings to <Nop> wait forever

### ISSUE THREAD

**Issue by aeruder** [neovim/neovim#6241]
I was trying to get some help with a short config in #vim on freenode and posted this short config.
Reproduced on vim 8.0.430 (See vim/vim#1548) and neovim v0.2.0-780-g087acd79

```vim
" Use this as your vimrc with vim -u <thisfile> <thisfile>
"
" Expected behavior:
"    Press <space>, wait a second, it does nothing
"    Then press <space><space>, it prints out hi
"
" What it does:
"     Press <space>, wait a second, it does nothing
"     Then future pressing of <space> results in it immediately hitting
"       the <Nop> mapping -- there is literally no way to hit the
"       <space><space> mapping
"     If you press any other key (like j or k or whatever), it goes back to
"     the original behavior of letting you press <space><space>
"
" Any way to change this behavior?
set nocompatible
set showcmd
nnoremap <Space>           <Nop>
nnoremap <Space><Space>    :echom "hi"<Cr>
```

Have since discovered that it *only* has issues with \<Space\> being mapped to \<Nop\>, if \<Space\> is mapped to \<Esc\> or any other action, this works fine.

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/83f4cbd973731872b633d6ba0caf850fb708d70c was ported in  https://github.com/neovim/neovim/commit/3b744f1ea273949069523a7d66d43f9ac1115317
