### ISSUE TITLE
DirChanged does not change getcwd()

### ISSUE THREAD

**Issue by ferranpm** [neovim/neovim#6260]
- `nvim --version`: v0.2.0-754-g32a9808bc
- Vim (version: ) behaves differently? 
- Operating system/version: Linux, Mac OS
- Terminal name/version: xterm, gnome termial
- `$TERM`: xterm-256color

### Actual behaviour
When firing the function attached to a DirChanged with `:lcd` or `:tcd` getcwd() and v:event['cwd'] do not always have the destination dir value.

### Expected behaviour
getcwd() and v:event['cwd'] should return the directory after it was changed

### Steps to reproduce using `nvim -u NORC`
source this snippet and change the directory a couple times with `:lcd` to see the values are not always correct.

```
augroup guiau
    autocmd!
    autocmd DirChanged * call s:update_dir(v:event)
augroup END

function! s:update_dir(event)
    echoerr 'Event directory: ' . a:event['cwd']
    echoerr 'getcwd(): ' . getcwd()
endfunction

set statusline=%f%=%{getcwd()}
```

[https://asciinema.org/a/106785](https://asciinema.org/a/106785)

#6054 might be realted

**Comment by justinmk** [comment]
>  change the directory a couple times with :lcd to see the values are not always correct.

If you use `:cd` though, it works. Right?

**Comment by ferranpm** [comment]
Yes
