### ISSUE TITLE
Strange characters after pressing remaped <Tab>

### ISSUE THREAD

**Issue by BSDinis** [neovim/neovim#6267]
- `nvim --version  0.2.0-dev`:
- Operating system/version: Ubuntu MATE 16.04 LTS
- Terminal name/version: zsh 5.1.1
- `$TERM`: xterm-256color

I have remapped the <Tab> key to <Esc>. This used to work just fine, but after some update, every time I get out of insert mode with <Tab>, 5 characters, [2 q, appear. Once I leave that line, they disappear. When I exit nvim, the following appears: [2 q% .

I have no clue as to what is happening

[vimrc.txt](https://github.com/neovim/neovim/files/836983/vimrc.txt)

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/4867 and `man nvim`. Add

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 0

to your init.vim, then restart nvim.

**Comment by BSDinis** [comment]
It worked just fine, thanks
