### ISSUE TITLE
add function for converting virtual columns to byte offsets

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6270]
`nvim_buf_add_highlight` handles the `col_start` argument as a byte offset, and therefore has the same limitation as `matchaddpos()`, which is that it is not easy to highlight text with multibyte characters before (or in) it.

With `matchadd()` the common pattern appears to be using `\%C.\{L\}v` to match from column C with len L.

One workaround appears to be using `matchstrpos()`, but that is not really straight-forward:
```vim
        let ts = &tabstop
        set tabstop=1
        try
            let pos = matchstrpos(getline(a:lnum), '\%'.a:col.'v.')
        finally
            let &tabstop = ts
        endtry
        if pos[1] == -1
            return a:col
        endif
        return pos[1] + 1
```

**Comment by blueyed** [comment]
btw: it would be useful to query existing highlights also.  I came across this with Neomake's tests.

**Comment by bfredl** [comment]
The rationale was that `add_highlight` would be used with external tools, which would know the byte count but not the virtual column count (dependent on unicode logic, and not even well defined `'ambiwidth'`). But doesn't most vim functions count columns in bytes anyway (for the same reason I presume)? At least `getpos()` and `col()` does, and it would be strange for `add_highlight` to behave differently than marks (as bufhl one day hopefully will use extended marks). 

Rather than complicating the api of `add_highlight` (and other functions dealing with columns), wouldn't it be better to add functions converting between (byte) columns and virtual columns?

**Comment by bfredl** [comment]
It seems `virtcol()` can easily convert bytes to virtual columns, but `col()` can't do the reverse...

**Comment by blueyed** [comment]
@bfredl 
Yes, a function like that would be needed.
Basically what my code above tries to do (which it probably not covers everything and should really not be needed in the context of an editor!).
There was some (stalled) discussion about a `colnr()` patch in 2014: https://groups.google.com/forum/#!topic/vim_dev/2DYfyTuo7G0

As for `col()`: it seems like the use case of giving it a line and column is rather useless, given that it returns the same column apparently.  But changing that would be weird, too.

**Comment by bfredl** [comment]
I don't see why you want to use virtual columns with matchaddpos/add_highlight in neomake really. In neomake/neomake#924 all column offsets seems to be calculated using `len(str)`, which count bytes.

**Comment by blueyed** [comment]
@bfredl 
I think https://github.com/neomake/neomake/pull/924 is not that affected by this.

I came across this when handling columns from external linters, which report the char and not the byte usually.

In Neomake the highlighting module uses `nvim_buf_add_highlight` for Neovim.
The column offset is based on the linter's output / input (usually chars), while the length might then be built manually in Vimscript, either just based on the linter's input (in case of JSON etc, where it is provided), or when extracting a match from the errorlist entry (i.e. match "Undeclared variable '%s'" to find out where %s starts/ends).

(It might be relevant if you are using `'errorformat'`/qf parsing or not (at least there's also a `vcol` property), but I don't think so)

In general it's mostly always character and not byte offsets.
It complicates things that Vim's "visual column" is similar to "character offset", but with regard to `virtcol()` not really (given tabs and other settings).

**Comment by bfredl** [comment]
I see.
"character" is not really well-defined, it can mean code point or grapheme cluster (where the rules differ between unicode versions) depending on the circumstances.  Seems that `strchars(str[:byteidx], cc )` can convert byte indices to both, depending on the `cc` flag. Probably there should be a function that just  does the reverse, which should be a lot simpler than involving the full machinery of display columns (depending on options like `tabstop`, `ambiwith`). I would suspect most linters are just using code points, but I could be wrong...

**Comment by bfredl** [comment]
@blueyed Looks like the relevant function already exists, `byteidxcomp(str, pos)` and `byteidx(str, pos)`, though the naming is juxtaposed, `byteidxcomp` is what you would use for non-composing-aware codepoint count, and `byteidx` for counting composed graphemes... 

What neomake needs is to do I guess is to add one (or two) error format specifier distinct from both `%v` and `%c` for codepoint (and grapheme) count, and convert to bytes using `byteidxcomp()` (and `byteidx()`). For instance `cargo`/`rustc` seems to count codepoints, so `byteidxcomp()` should be used.

**Comment by justinmk** [comment]
Can we close this?

**Comment by blueyed** [comment]
Yes, thanks.

I will have to check out `byteidxcomp` and `byteidx`.

I think they should be made more easy to discover in the docs however - but that's also a Vim issue.

**Comment by justinmk** [comment]
Looks like `:help string-functions` is the place to check.

**Comment by blueyed** [comment]
Yes, but maybe also frome places where I looked at.

**Comment by bfredl** [comment]
For whatever reason they don't use `str` prefix like all other string functions. They should probably be mentioned in `strchars` and maybe `strgetchar`. Also `strcharidx` would be more logical, you get the idx of a char not of a byte...
