### ISSUE TITLE
Wrong/Weird colors with :!

### ISSUE THREAD

**Issue by iasj** [neovim/neovim#6273]
- `nvim 0.1.7`:
-  uname -a
```console
Linux Acer 4.10.1-1-ARCH #1 SMP PREEMPT Sun Feb 26 21:08:53 UTC 2017 x86_64 GNU/Linux
```
- Terminal name/version:
termite v12

- `$TERM`:
scree-256color

### Actual behaviour
When I hit
```
:make recompile
```
from inside neovim, in order to invoke the target `recompile` in my Makefile, the colors appear like this:
![neovim-output](https://cloud.githubusercontent.com/assets/7888397/23893076/e5066eca-087b-11e7-8616-fdec56bb0116.png)

I'm using `tput setaf <color-number>` to put some colors in my Makefile.

### Expected behaviour
However, if I hit `make recompile` directly in the terminal, it appears like expected:
![normal-output](https://cloud.githubusercontent.com/assets/7888397/23893158/3b1a01c8-087c-11e7-9be7-ada7f2a60766.png)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:make recompile
```

I hope that is all the information you guys need.

**Comment by justinmk** [comment]
In nvim `:!` uses pipes, not a tty. See https://github.com/neovim/neovim/issues/5431 and https://github.com/neovim/neovim/issues/1496

**Comment by iasj** [comment]
Thanks. It really helped. My workaround was using `:term` with `|` and `:tabnew`. 
Like this: `:tabnew|term make recompile`.

If someone wants to map this, just put `<bar>` instead of `|`, otherwise it will never work. The `tabnew` is for creating another tab before, so it prevents your current buffer from being closed. 

That is an amazing feature, congrats.

**Comment by iasj** [comment]
Hey. It is me again. I now have created an unconfortble compilation rotine after making mappings. Here is my map:

```vim
inoremap <F11> <esc>:wall<cr>:tabnew<bar>term make <cr>
nnoremap <F11> <esc>:wall<cr>:tabnew<bar>term make <cr>
inoremap <F12> <esc>:wall<cr>:tabnew<bar>term make tests<cr>
nnoremap <F12> <esc>:wall<cr>:tabnew<bar>term make tests<cr>
```

then after the program `make` is done, by pressing any key, neovim closes the window that is openned, but it doesn't return to the right tab I was before. That is really unconfortble, but I can live with that. But of course, if someone has any work around this, I would really appreciate any help.

**Comment by justinmk** [comment]
We're going to change that default behavior, but meanwhile you can add `:stopinsert` to prevent "press any key" from closing the buffer. This takes you to normal mode. E.g.:

    nnoremap <F12> <esc>:wall<cr>:tabnew<bar>exe 'term make tests'<bar>stopinsert<cr>
