### ISSUE TITLE
Use javascript instead of cindent for html scripts

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#6283]
Take a look at this commit: https://github.com/vim/vim/commit/690afe1fef87e7eef6fb7343a926617d5f7315fa#diff-c5802b9fe6ca7e175ecf7f5f3bea690eR28

Vim is using `indent/javascript` instead of cindent since that commit. I think it's good idea to have that update here too.

This is a related discussion: https://github.com/pangloss/vim-javascript/issues/588

**Comment by jamessan** [comment]
We're continuously merging patches and runtime updates from Vim.  There doesn't need to be a specific issue to request that.  We'll get to this update in due time.

**Comment by sassanh** [comment]
Great, is there any page demonstrating these due times so that I can follow this?

**Comment by justinmk** [comment]
@sassanh https://neovim.io/doc/reports/vimpatch/

**Comment by sassanh** [comment]
Thanks

**Comment by sassanh** [comment]
@justinmk  The referenced patch seems to be in vim version 8 but it seems like all the patches in https://neovim.io/doc/reports/vimpatch/ are patches from 7.4. Am I missing something?

**Comment by justinmk** [comment]
@sassanh We are merging patches from vim8 where possible, but aren't tracking them until we finish 7.4.

**Comment by sassanh** [comment]
I see, thanks for info.

**Comment by sassanh** [comment]
@jamessan @justinmk Just a quick question, why https://neovim.io/doc/reports/vimpatch/ is empty? Last time I checked it it had a huge list. Are you done merging 7.4 patches?

**Comment by justinmk** [comment]
@sassanh could be a bug in the script.

**Comment by sassanh** [comment]
I see, thanks for quick response.

**Comment by Shougo** [comment]
Have you read 8.0.257 patch?
It is for Filelist patch.
neovim has not the file.

https://github.com/vim/vim/commit/e0b66da69123815076b38c0c074a1c6aca5dfd27

**Comment by sassanh** [comment]
Thanks for quick response. Sorry, seems like 257 is not the related patch. How can I find out the related patch for this commit: https://github.com/vim/vim/commit/690afe1fef87e7eef6fb7343a926617d5f7315fa#diff-c5802b9fe6ca7e175ecf7f5f3bea690eR28?

**Comment by Shougo** [comment]
You should use `./scripts/vim-patch.sh -l` instead.
https://neovim.io/doc/reports/vimpatch/ does not support the runtimeupdate.

**Comment by Shougo** [comment]
https://github.com/vim/vim/commit/690afe1fef87e7eef6fb7343a926617d5f7315fa seems already merged.

**Comment by sassanh** [comment]
neovim repository is just awesome, not just because it contains neovim, but also because of the fantastic guys behind it responding quickly to issues. I'm really thankful.

**Comment by Shougo** [comment]
You can contribute to the patch merging :-)

**Comment by sassanh** [comment]
Where can I read about the instructions on merging patches?

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md
