### ISSUE TITLE
Tests litter the tmp area

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#6291]
I was looking into the latest failures on QB and discovered that the /tmp area had so many leftover files in it, that under FreeBSD it ran into problems creating more links in the /tmp area when trying to build jemalloc--causing the FreeBSD build to fail on the build-deps step.  It looks like most of the stray files are caused by the unit tests not cleaning up after themselves.  A simple run showed that 442 directories were created and left lingering in /tmp.

While this may seem like a QB issue, it's really a developer-oriented one.  We really shouldn't pollute someone's machine this way and should do our best to clean up after ourselves.  I'll come up with some solution to help isolate the temp files for the QB builds (setting TMPDIR helps considerably, but Lua's `os.tmpname()` always creates a `/tmp/lua_XXXXX` filename and ignores the env variable).

**Comment by justinmk** [comment]
Good catch. This might be tough, `:[range]!` silently creates temp files but I'm not sure if they are removed after.

**Comment by jszakmeister** [comment]
I think it's creating the vim temporary directory for lots of tests and they're not getting cleaned up.  It's a bit tedious to add something to fix that to every test teardown though.  I wonder if we shouldn't just formulate our own TMPDIR while running the tests so that most of the results stay in the workspace somewhere?

**Comment by justinmk** [comment]
We could try enabling 'noshelltemp'. And make it stronger if needed.

**Comment by justinmk** [comment]
I see that `$TMPDIR` is already supported (I thought you were using a pseudonym). Yes, let's do that...

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/issues/5394

**Comment by justinmk** [comment]
> setting TMPDIR helps considerably,

Done in https://github.com/neovim/neovim/pull/6395

> but Lua's os.tmpname() always creates a /tmp/lua_XXXXX filename and ignores the env variable).

Fixed in https://github.com/neovim/neovim/pull/6395
