### ISSUE TITLE
Terminal windows inside TMUX do not execute :tnoremap mappings

### ISSUE THREAD

**Issue by stephenprater** [neovim/neovim#6301]
I feel like this is probably a misalignment of TERM values or there's some entry I can make to the terminfo database to make this work - but I'm not sure where to start.

- `nvim --version`: NVIM v0.2.0-853-g27e1b2d
- Vim (version: ) behaves differently? NA
- Operating system/version: OSX - 10.12.3
- Terminal name/version: ITERM2
- `$TERM`: screen-256color

### Actual behaviour

Mappings beginning with Ctrl are not executed in terminal windows.

### Expected behaviour

The should be.

### Steps to reproduce using `nvim -u NORC`

Within Tmux:

Set up a terminal mapping like so:

`tnoremap <C-k> <C-\><C-n>:echo 'hello'<CR>`

open a terminal window.

press `<C-k>`

### Further Information

Unintercepted control sequences are passed to the terminal without issue - so in the above case if you were to try `<C-a>` you'd see the cursor go to the beginning of the line - while `<C-k>` does nothing.

**Comment by justinmk** [comment]
echo is erased after redraw. Try echomsg

**Comment by stephenprater** [comment]
echomsg doesn't work either.  I think this might be legit.  It doesn't matter what the `:tnoremap` command executes - it never gets done.

**Comment by justinmk** [comment]
What happens if you do this:

```
:tnoremap <C-k> <C-\><C-n>:echomsg 'hello'<CR>
:terminal
<C-\><C-N>
:call nvim_input('i<C-k>')
```

For me, that prints "hello".

**Comment by stephenprater** [comment]
Yes, that prints "hello" for me too.

This only doesn't work when the terminal mode is within a tmux session. 

Given than `nvim_input` works it makes me doubly suspicious that the problem is somehow with what tmux is sending.  Is there a place to log what nvim _thinks_ it received from the keyboard?

**Comment by justinmk** [comment]
I'm using tmux. So, I can't reproduce this. If this were a Nvim bug, many people would encounter it. That suggests there is some environmental issue.

> Is there a place to log what nvim thinks it received from the keyboard?

You can try sending a key from tmux: enter tmux command-mode, then do this:

    :send-keys i C-k

**Comment by stephenprater** [comment]
That worked and pointed me to the solution.  Indeed it was an environment problem.

Thanks a lot for your help.
