### ISSUE TITLE
The links to the Windows builds in the Wiki are broken

### ISSUE THREAD

**Issue by jkurei** [neovim/neovim#6302]
I've no idea if this is the correct way to report this kind of thing, but tweeting at or emailing someone feels even more annoying.

- `nvim --version`: None
- Vim (version: ) behaves differently? Yes, the links work
- Operating system/version: Windows :(

### Actual behaviour

Error 400

### Expected behaviour

Download of .exe or .msi file

### Steps to  #reproduce

- Go to https://github.com/neovim/neovim/wiki/Installing-Neovim#windows
- Click on "64bit build"

```
$ wget https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_64
 --2017-03-17 12:06:11--  https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master
Resolviendo ci.appveyor.com (ci.appveyor.com)... 138.91.141.243
Conectando con ci.appveyor.com (ci.appveyor.com)[138.91.141.243]:443... conectado.
Petición HTTP enviada, esperando respuesta... 400 Bad Request
2017-03-17 12:06:13 ERROR 400: Bad Request.
```

**Comment by justinmk** [comment]
curl -LO https://ci.appveyor.com/api/projects/neovim/neovim/artifacts/build/Neovim.zip?branch=master&job=Configuration%3A%20MINGW_64

Works for me. Try a different client or a different network. Nothing else we can do.
