### ISSUE TITLE
Windows: `:edit 'foo\"bar'` swapfile error

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6316]
```
edit 'foo\"bar'
E303: Unable to open swap file for "'foo"bar'", recovery impossible
```

See also `:help win32-quotes` in Vim's help.

**Comment by janlazo** [comment]
`vim -u NONE --cmd 'foo\"bar'` results in the default startup screen with no filename
`vim -u NONE --cmd "set encoding=utf-8" 'foo\"bar'` causes the swap error.

**Comment by bounceme** [comment]
https://support.microsoft.com/en-us/help/177506/error-message-filename-is-invalid-or-cannot-contain-any-of-the-following-characters , i'm not sure if that is more a convention they enforce in 'finder' or if it really is impossible

**Comment by justinmk** [comment]
I guess we can close this. Thanks.

**Comment by ZyX-I** [comment]
In NTFS this is possible (it accepts any UTF-16 characters in file names, but `/` and zero; note that normally POSIX filesystems store a raw sequence of non-NUL bytes so this variant is more limited), but you will have AFAIK unsolvable problems with Windows APIs if you try to use the resulting file there. In FAT\*: generally the same, yet default mount options do not allow certain special characters even on linux.
