### ISSUE TITLE
Jumping to closing/opening parenthesis sometimes doesn't work in shell files

### ISSUE THREAD

**Issue by dumblob** [neovim/neovim#6334]
- `nvim --version`: NVIM 0.1.7 (Build type: Release)
- Vim (version: ) behaves differently? no
- Operating system/version: Arch Linux 4.9.13-1-lts x86_64
- Terminal name/version: xterm
- `$TERM`: xterm

### Actual behaviour
The closing parenthesis `)` are matched inside of the `case` construct as closing parenthesis of an opening parenthesis outside of the `case` construct. This has two consequences:

1. One can't use `%` for jumping to the opening/closing parenthesis.
2. Pressing `%` in normal mode upon `(` or `)` sometimes freezes neovim for about a second (but not longer than 2 seconds).

There might be other cases when jumping doesn't work, but let's start with this one.

### Expected behaviour
The `)` inside of the `case` construct (or rather the whole `case` construct) should be skipped when jumping using `%` from `(` or `)` outside of a `case` construct.

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC
i  " switch to insert mode
subshell_function() (
  _cnt=4

  for _x; do
    case "$_x" in
      --)
        _ddash='found'
        break ;;
      -r|-rf|-fr)
        _recur='found'
        continue ;;
      -f)
        continue ;;
      -*)
        [ -z "$_ddash" ] && {
          printf '%s\n' '-* option found before any --' >&2
          exit 1
        } ;;
      *) [ -z "$_recur" ] && [ -d "$_x" ] && {
        printf '%s is a directory\n' "$_x" >&2
        exit 1
      } ;;
    esac
  done

x=$((0+0))
)
<ESC>  " switch to normal mode
" go to the last ) with a cursor
%  " jump to the second ( on the very first line
```

**Comment by dumblob** [comment]
Related: https://github.com/neovim/neovim/issues/6102

**Comment by justinmk** [comment]
The reply is the same as for #6102, and runtime files in general. Unless someone wants to fork the related syntax files and commit to maintaining them, we depend on Vim and the existing maintainers to deal with this.
