### ISSUE TITLE
terminal: impossible to globally set 'scrollback'

### ISSUE THREAD

**Issue by yagebu** [neovim/neovim#6337]
- `nvim --version`: NVIM v0.2.0-924-ga1732b46 (via brew install neovim --HEAD)
- Operating system/version: MacOS 10.12.3

### Actual behaviour

In a normal buffer:
`:set scrollback` outputs `scrollback=-1`
`:set scrollback=-1` fails with `E474: Invalid argument: scrollback=-1`

In a terminal buffer:
`:set scrollback` outputs `scrollback=1000` (this should set global and local scrollback)
`:set scrollback=9999` outputs `scrollback=9999`

In a new terminal buffer (opened after the previous commands):
`:set scrollback` outputs `scrollback=1000`

### Expected behaviour

In a normal buffer:
`:set scrollback` outputs `scrollback=-1`
`:set scrollback=-1` would ideally set the local and global option without failing.

In a terminal buffer:
`:set scrollback` outputs `scrollback=1000` (this should set global and local scrollback)
`:set scrollback=9999` outputs `scrollback=9999`

In a new terminal buffer (opened after the previous commands):
`:set scrollback` outputs `scrollback=9999`

### Comment

The current behaviour for `scrollback` is inconsistent with the way that buffer local options are documented to behave. `:set`ting it should set both the global and local value, currently it's impossible to set the global value.

It doesn't seem necessary to have a separate default for terminal and other buffers. The option only has an effect in terminal buffers so the other default can probably just be removed.

The restriction that this option can only be set from a terminal buffer seems unnecessary too. Again, it has no effect in other buffers, so allowing it to be set there as well shouldn't do any harm. The current behaviour prohibits from setting a default in one's `init.vim`.

If these proposed changes are agreeable, I could try preparing a PR.

**Comment by justinmk** [comment]
> The current behaviour for scrollback is inconsistent with the way that buffer local options are documented to behave. 

It's "local to buffer" as documented (see `:h 'binary'` for example). "global-local" is different. I guess it's a bit unexpected, so we can make it global-local. Currently, you can set a different default by using an autocmd:

    au TermOpen * setlocal scrollback=...

> It doesn't seem necessary to have a separate default for terminal and other buffers. The option only has an effect in terminal buffers so the other default can probably just be removed.

Why should the option value be incorrect for normal buffers? 

> The restriction that this option can only be set from a terminal buffer seems unnecessary too. Again, it has no effect in other buffers, so allowing it to be set there as well shouldn't do any harm

Making it an error is better than silently ignoring the action.

**Comment by justinmk** [comment]
PR making it global-local, with a test, would help. Thanks

**Comment by yagebu** [comment]
> It's "local to buffer" as documented (see :h 'binary' for example). "global-local" is different. I guess it's a bit unexpected, so we can make it global-local.

Thanks, this distinction makes sense. I find the `local-options` doc confusing as it only seems to be talking about `global-local` without saying it:

> When editing a new buffer, its local option values must be initialized.  Since
the local options of the current buffer might be specifically for that buffer,
these are not used.  Instead, for each buffer-local option there also is a
global value, which is used for new buffers.  With ":set" both the local and
global value is changed

---

> Why should the option value be nonsense for normal buffers?

> Making it an error is better than silently ignoring the action.

`'lispwords'` is an example of a `global-local` options that's nonsense in most buffers and can be set without errors, so I don't think it would be terribly inconsistent to allow setting it in any buffer.

**Comment by yagebu** [comment]
> :setlocal scrollback=foo in a normal buffer should continue to be an error, but :set scrollback=foo in any buffer should not be an error. Not sure if the option system will allow that... if not, then it's probably ok to allow :setlocal scrollback=foo in a normal buffer, but silently set the local value to -1 and the global value to foo.

👍 . Will try to implement that.

**Comment by yagebu** [comment]
> It's "local to buffer" as documented (see :h 'binary' for example).

Actually it is not. The "local to buffer" options have global values too, so for example `:set binary` will set it locally and globally (and hence it would be used for all newly created buffers). Currently for `scrollback` the global value can be set with `:set` or `:setglobal` in a terminal buffer, it is just ignored.

There seem to be only two options that (sensibly, but undocumentedly) will always use the default value: `bt`, `bh`. Well, and `scrollback`. The global value can still be set for them though...

The global-local options are slightly weird. They need some reserved value, which when set as the local option tells nvim to use the global value. For strings it's an empty string, for 'autoread' it's `-1` and for 'undolevels' it's the ridiculous `-123456`. I don't think it's worth the effort to make `scrollback` global-local.

**Comment by justinmk** [comment]
> so for example :set binary will set it locally and globally (and hence it would be used for all newly created buffers). 

That seems bizarre. But whatever. If you want to make it work like that, OK. But please try to continue to maintain -1 for normal buffers.
