### ISSUE TITLE
CheckHealth gives warning "virtualenv appears to be inactive" with python3 virtualenv and python installed via nix

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#6347]
nvim version 0.1.7

I've installed python with `nix` package manager

```
echo $VIRTUAL_ENV
/Users/mihaildoronin/code/my-projects/easyconf/.easyconf`

echo exepath('python3')
/Users/mihaildoronin/.nix-profile/bin/python3
```
From the `CheckHealth` I can see that it expects them to be the same. But `exepath` shows the   the python executable that was used when creating virtuenv with `python3 -m venv ...`

**Comment by tweekmonster** [comment]
What exactly is the issue?  It's correctly warning you that calling `python3` will not be using what's in `$VIRTUAL_ENV`.

If `$VIRTUAL_ENV` exists, it's very likely that you'd expect that a plugin calling `system('python3 -m site')` would actually be using `$VIRTUAL_ENV/bin/python3`.

**Comment by purpleP** [comment]
@tweekmonster Yes, I would expect that. However for some reason while I'm in virtualenv seems that `system('python3 -m site')` would use systems python, not the one from virtualenv.

And the real issue for me is that deoplete-jedi somehow seems to ignore `python3_host_prog` and showing message where it can't find `project_venv/bin/python` whereas it's actually there.

**Comment by justinmk** [comment]
What's the request for neovim in this report?

**Comment by purpleP** [comment]
@justinmk Are you saying that if I start neovim while inside virtualenv it would use global python and that's how it supposed to be?

**Comment by tweekmonster** [comment]
@purpleP Did you follow the link in the suggestion?  http://vi.stackexchange.com/a/7654/5229

It's because, for whatever reason, `$VIRTUAL_ENV` exists and `$PATH` was not updated to be `$VIRTUAL_ENV/bin:$PATH`.  This is usually due to an rc script resetting `$PATH`.

**Comment by tweekmonster** [comment]
> @justinmk Are you saying that if I start neovim while inside virtualenv it would use global python and that's how it supposed to be?

He's asking what you're expecting to be changed.

IMO, the warning worked as expected.  There's nothing to be done unless you're suggesting a change to the message.

**Comment by purpleP** [comment]
@tweekmonster Yes, I followed that, it doesn't explains what happens to me. My zshrc is have `export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"` in it. But is also have `cd .` in it at the end. And I have hook that activates virtualenv if it exists in the directory when I change directories. So what I want right now is to fully understand what's happening. And then I can probably suggest how to make message clearer.

**Comment by justinmk** [comment]
You have "cd ." in your zshrc ?

**Comment by purpleP** [comment]
@justinmk yes, so that chpwd hooks would be executed.

**Comment by justinmk** [comment]
Well, that may be the problem. If your setup depends on a magic "cd" happening, it's not going to run for a non-interactive shell, such as when `system()` or `jobstart()` is executed...

**Comment by tweekmonster** [comment]
@purpleP The problem is explained in the link:

> Because .zshrc is not always sourced, while .zshenv is guaranteed to be sourced.

It's clarified here: http://zsh.sourceforge.net/Intro/intro_3.html

> `.zshenv` is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path, plus other important environment variables. `.zshenv` should not contain commands that produce output or assume the shell is attached to a tty.

**Comment by purpleP** [comment]
@tweekmonster No, it's not explained. I've added `cd .` into `~/.zshenv` and nothing have changed. I still don't understand what's the problem.

**Comment by tweekmonster** [comment]
If your `cd .` magic is based on the `chpwd` function, it just won't work in a non-interactive shell.  That is the absolute best explanation I can give you.

**Comment by purpleP** [comment]
@tweekmonster Does `zsh -c 'echo $PATH` echoes path non-intractively?
