### ISSUE TITLE
build: undefined reference to `termkey_hook_terminfo_getstr' on Alpine Linux

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6356]
https://github.com/neovim/neovim/commit/af2e629be4d20dda334a7c6ca817f5599956e4ff seems to cause Neovim failing to build in Alpine Linux:

```
[ 97%] Linking C executable ../../bin/nvim
CMakeFiles/nvim.dir/tui/input.c.o: In function `term_input_init':
/vim/neovim-master/src/nvim/tui/input.c:38: undefined reference to `termkey_hook_terminfo_getstr'
collect2: error: ld returned 1 exit status
```

Using `make 'CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=/vim-build/nvim_master         -DENABLE_JEMALLOC=OFF' 'DEPS_CMAKE_FLAGS=        -USE_BUNDLED=OFF         -DUSE_BUNDLED_JEMALLOC=OFF         -DUSE_BUNDLED_BUSTED=OFF`

libtermkey (0.18-r0)
libtermkey-dev (0.18-r0)

I have tried using Alpine edge\, but it seems to behave similar:
```
/vim/neovim-master/src/nvim/eval.c: At top level:
cc1: warning: unrecognized command line option '-Wno-static-in-inline'
CMakeFiles/nvim.dir/tui/input.c.o: In function `term_input_init':
/vim/neovim-master/src/nvim/tui/input.c:38: undefined reference to `termkey_hook_terminfo_getstr'
collect2: error: ld returned 1 exit status
make[3]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3791: bin/nvim] Error 1
make[2]: *** [CMakeFiles/Makefile2:154: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[1]: *** [Makefile:150: all] Error 2
make: *** [Makefile:61: nvim] Error 2
```

But there it downloads `libtermkey-0.19.tar.gz`and installs it into `.deps`.

The same happens when turning off any use of bundled libs, i.e. just using `make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$VIM_PATH"`.
However it says then `Found LibTermkey: /usr/lib/libtermkey.so` - and therefore apparently does not use the one installed into `.deps`?!

Finally, not installing `libtermkey-dev` and `libtermkey` fails as follows:
```
…
make[1]: Leaving directory '/vim/neovim-master/.deps'
cd build && cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/vim-build/nvim_master ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Replacing -O3 in CMAKE_C_FLAGS_RELEASE with -O2.
-- Performing Test HAS_OG_FLAG
-- Performing Test HAS_OG_FLAG - Success
-- Performing Test HAS_ACCEPTABLE_FORTIFY
-- Performing Test HAS_ACCEPTABLE_FORTIFY - Success
-- Performing Test HAS_WVLA_FLAG
-- Performing Test HAS_WVLA_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_STRONG_FLAG - Success
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG
-- Performing Test HAS_FSTACK_PROTECTOR_FLAG - Success
-- Performing Test HAS_DIAG_COLOR_FLAG
-- Performing Test HAS_DIAG_COLOR_FLAG - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.3.2") 
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for kstat_lookup in kstat
-- Looking for kstat_lookup in kstat - not found
-- Looking for kvm_open in kvm
-- Looking for kvm_open in kvm - not found
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - not found
-- Looking for perfstat_cpu in perfstat
-- Looking for perfstat_cpu in perfstat - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for sendfile in sendfile
-- Looking for sendfile in sendfile - not found
-- Found LibUV: /vim/neovim-master/.deps/usr/lib/libuv.a  
-- Found Msgpack: /vim/neovim-master/.deps/usr/lib/libmsgpack.a (found suitable version "1.0.0", minimum required is "1.0.0") 
-- Found unibilium: /usr/lib/libunibilium.so  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibTermkey.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:323 (find_package)
```

**Comment by blueyed** [comment]
I was not using `-DUSE_BUNDLED=OFF` in `DEPS_CMAKE_FLAGS` after all (forgot the `D` prefix).

It works then using:
```
    make CMAKE_BUILD_TYPE=Release \
      CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$VIM_PATH \
        -DENABLE_JEMALLOC=OFF" \
      DEPS_CMAKE_FLAGS="\
        -DUSE_BUNDLED_JEMALLOC=OFF \
        -DUSE_BUNDLED_LIBUV=OFF \
        -DUSE_BUNDLED_LUAJIT=OFF \
        -DUSE_BUNDLED_LUAROCKS=OFF \
        -DUSE_BUNDLED_LUV=OFF \
        -DUSE_BUNDLED_LIBTERMKEY=OFF" \
```
(but only with https://github.com/neovim/neovim/pull/6357)

**Comment by blueyed** [comment]
So the probelm arises if libtermkey is installed, and Neovim wants to use a bundled version, which then fails because it does not use the bundled version when linking.

I would have assumed that https://github.com/neovim/neovim/pull/6357  fixes it, but it still fails when using it with empty `DEPS_CMAKE_FLAGS`..?!
(it uses "/usr/lib/libtermkey.so" then instead of the version from `.deps`)

Shouldn't the `.deps` location be used in https://github.com/neovim/neovim/blob/60620091ae4d7b42db1f91431509b1bb82328cb4/cmake/FindLibTermkey.cmake#L12-L18?

**Comment by justinmk** [comment]
@blueyed are you able to gist the verbose build log for the latest variant here? @jszakmeister any idea here?

**Comment by blueyed** [comment]
@justinmk 
Could do, but not before tomorrow.
For reference: it happened (and hopefully still happens (with the changes from above)) with the Neovim support being added to vim-testbed: https://github.com/tweekmonster/vim-testbed/pull/9.

**Comment by mqudsi** [comment]
fwiw and for anyone googling this, installing the neovim package from the FreeBSD binary packages manager fails with the same error after upgrading an old VM from 0.1.7 to 0.2.0 release on FreeBSD 10.3-RELEASE-p6.

It seems to actually be a different problem since upgrading libtermkey to the latest available (0.2.0) from the previous (0.18) resolves the matter; so that's likely just a bug in the FreeBSD package in that the dependency on libtermkey doesn't have a high enough version.

**Comment by justinmk** [comment]
@blueyed Is this still an issue?

**Comment by UncleGoogle** [comment]
I've just get it after upgrate on openSUSE to ver. `neovim-0.2.2-3.1.x86_64.rpm`
`nvim: symbol lookup error: nvim: undefined symbol: termkey_hook_terminfo_getstr`


problem solved by upgrading libtermkey1 to `libtermkey1-0.20-1.1.x86_64.rpm`

**Comment by justinmk** [comment]
I guess the version check isn't working. Seems like the wrong headers are found?

**Comment by jamessan** [comment]
> I guess the version check isn't working.

The version check happens at build time.  There's nothing we can do to enforce the runtime library is the same version.  That requires the packager to set the right runtime dependencies.

I don't know about the RPM world, but Debian packages specify when symbols are introduced so library dependencies can be properly versioned based on the symbols being used.

**Comment by jamessan** [comment]
> I think the issue itself is about building, but not picking the version from .deps:

Yeah, I was responding to UncleGoogle's comments which appear to be about packaged versions.

The problem described in your earlier comment definitely exists.  I've run into it before, but haven't had time to dig into it.

**Comment by dundargoc** [comment]
Is this still a problem?

**Comment by blueyed** [comment]
Closing as per https://github.com/neovim/neovim/issues/6356#issuecomment-396417872.
