### ISSUE TITLE
[Project] Headers refactoring, IWYU

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6371]
Current header files have the problem with implicit dependencies/blocks meaning that you must include headers in a specific order in some cases. In addition to this incremental compilation does not work well because when you include header because you need some specific type from it you also pull in function declarations which depend on the C file. The fix to the situation was discussed already, but I do not remember a separate issue. Thus suggestion: refactor header files in turns:

1. Refactor header files according to https://neovim.io/doc/user/dev_style.html#dev-style-header
2. Make clint check that headers depend only on _defs.h.
3. Make IWYU check header files.

---

Actual plan:

- [x] Document the above (in `:help develop` or `:help dev-style`)
- [x] Add a way to test that that each header can be included separately (#6396).
- [x] PR which runs IWYU, with errors from all files ignored.
- [x] Per-header PR, new _defs.h headers must pass IWYU. This part can be marked entry-level.
     - The list of files left are documented as code in `Makefile`.
- [x] Add clint checks, with errors from all files ignored.
- [x] Fix remaining clint checks.
     - The list of files not linted with clint are documented as code in `src/clint.py`.

**Comment by dundargoc** [comment]
This is effectively fixed. There are some files ignored in `clint.py` but removing them causes more churn than it's worth. We could add IWYU to CI but it's too unstable and weird so it'll likely cause confusion with contributors who won't understand why it fails sometimes. I will therefore close this.

**Comment by dundargoc** [comment]
Next item on the agenda may be to replace IWYU with e.g. include-fixer as it's pretty disappointing.
