### ISSUE TITLE
Can't remove scrollbars and top menu from UI

### ISSUE THREAD

**Issue by CodingJonas** [neovim/neovim#6382]
- `nvim --version`: 0.1.7
- Vim (7.4) behaves differently?
- Operating system/version: Ubuntu 16.04 with i3wm
- Terminal name/version: zsh 5.1.1
- `$TERM`: xterm-256color

### Actual behaviour
I always see the scrollbar on the right, although the button for scrolling fills out the complete scrollbar, as if the document would be less then one page long.

![screenshot from 2017-03-28 10-43-48](https://cloud.githubusercontent.com/assets/15234763/24396461/922fd9c4-13a3-11e7-8218-808d12f32f6e.png)

I used this in my vimrc and it worked without problems:
```
set guioptions-=m  " Remove menu bar
set guioptions-=T  " Remove toolbar
set guioptions-=r  " Remove right-hand scrollbar
set guioptions-=L  " Remove left-hand scroll bar
```
The same lines in my init.vim do nothing.

### Expected behaviour
The scrollbar and top menu should simply not be there.

**Comment by justinmk** [comment]
That's your terminal
