### ISSUE TITLE
Odd characters on backspace

### ISSUE THREAD

**Issue by mark-schultz** [neovim/neovim#6386]
**- `nvim --version`:**
NVIM v0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/build/config -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/src -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-PRAh57/neovim-0.1.7ubuntu1+git201703241730+3255+23~ubuntu16.04.1/build/include
Compiled by root@lcy01-14

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
**- Vim (version: ) behaves differently?**

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     

**The issue is not present in Vim**

- Operating system/version:

`uname -a` returns:

Linux chrx 4.8.17-galliumos #1 SMP PREEMPT galliumos4 Thu Feb 23 02:27:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

GalliumOS is an Xubuntu variant based on version 16.04. 

- Terminal name/version:

xfce4-terminal 0.6.3 (Xfce 4.12)

- `$TERM`:

### Actual behaviour
[On backspace in insert mode, odd characters appear and persist](https://i.imgur.com/BFkjvIA.png)
### Expected behaviour
Backspace should delete the character without creating extra "noise"

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Problem doesn't appear to be present in nvim -u NORC.
From this, I'm guessing the issue is in my `init.vim` file, which is [here](https://paste.ubuntu.com/24268728/).

I'm new to both Vim and Nvim, so I'm not particularly attached to that init file.  I believe I got it from [vim-bootstrap](https://vim-bootstrap.com/), so it's confusing why it may be introducing errors.

**Comment by jamessan** [comment]
Add let `$NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` to your init.vim, or use a newer version of libvte (which xfce4-terminal uses).

**Comment by justinmk** [comment]
What does this say ?

    :verb map! <BS>

**Comment by mark-schultz** [comment]
Adding `let NVIM_TUI_ENABLE_CURSOR_SHAPE = 0` seems to fix the problem.

**Comment by mark-schultz** [comment]
The fix seems to work completely for .txt and .init files, but on .py files the behavior is still there.

`:verb map! <BS>` says `        Last set from ~/.config/nvim/plugged/delimitMate/plugin/delimitMate.vim 
`
