### ISSUE TITLE
E121: Undefined variable: b:netrw_curdir

### ISSUE THREAD

**Issue by lswith** [neovim/neovim#6388]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? No. It is a bug in vim as well: https://github.com/vim/vim/issues/1311
- Operating system/version: Mac OSX
- Terminal name/version: iTerm 2
- `$TERM`: xterm-256color

**Comment by ZyX-I** [comment]
Currently we do not maintain runtime files, except for Neovim-specific ones. Fix will be there after it is merged in Vim.
