### ISSUE TITLE
Tutor:  "d$" does not work properly 

### ISSUE THREAD

**Issue by ipylypiv** [neovim/neovim#6389]
- `nvim --version`:
NVIM v0.2.0-989-g6fbcbeb
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/igor/work/opensource/neovim/build/config -I/home/igor/work/opensource/neovim/src -I/home/igor/work/opensource/neovim/.deps/usr/include -I/home/igor/work/opensource/neovim/.deps/usr/include -I/home/igor/work/opensource/neovim/.deps/usr/include -I/home/igor/work/opensource/neovim/.deps/usr/include -I/home/igor/work/opensource/neovim/.deps/usr/include -I/home/igor/work/opensource/neovim/.deps/usr/include -I/usr/include -I/home/igor/work/opensource/neovim/build/src/nvim/auto -I/home/igor/work/opensource/neovim/build/include
Compiled by root@ilaptop

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

- Vim (version: ) behaves differently?
N/A
- Operating system/version:
Ubuntu, Linux 4.10-rc7

- Terminal name/version:
Yakuake: 2.9.9

- `$TERM`:
xterm

### Actual behaviour
In Tutor mode command `d$` deletes all characters to the end of line, except the last one.

### Expected behaviour
In Tutor mode command `d$` deletes all characters to the end of line.

### Steps to reproduce using `nvim -u NORC`
run `:Tutor`
put cursor in the middle of line
run `d$`

**Comment by justinmk** [comment]
Confirmed. cc @fmoralesc

**Comment by fmoralesc** [comment]
The standing issues are all the to the way the plugin handles the check
regions. I will try to find a way to make it more robust, I have an idea
for now.
