### ISSUE TITLE
Tagbar plugin doesn't work on windows

### ISSUE THREAD

**Issue by cmaughan** [neovim/neovim#6391]
- `nvim --version`:NVIM v0.2.0-1064-gc5c539b6
- Operating system/version:Win10
- Terminal name/version:cmd.exe

After installing the tagbar plugin, I can't launch it because "ctags.exe --version" doesn't work.  The same config works fine in gVim.  This seems to be something to do with the way that ctags is being called in neovim's system() command.  At least the escaping seems to be the same, but the system call fails in the windows case (yes, I have ctags in the path, and gVim finds it no problem)

Repro: 
Add tagbar:
https://github.com/majutsushi/tagbar
Hit CTRL+T to bring it up.

**Comment by timeyyy** [comment]
https://github.com/neovim/neovim/pull/6387

**Comment by justinmk** [comment]
Thanks, this is covered as mentioned above
