### ISSUE TITLE
Neovim in an ssh session in konsole emits spurious "q" characters in prompts

### ISSUE THREAD

**Issue by shlomif** [neovim/neovim#6403]
- `nvim --version`:
```
shlomif@lap:~$ /home/shlomif/apps/neovim/bin/nvim --version
NVIM v0.2.0-1089-g8d13955
Build type: Debug
Compilation: /home/shlomif/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/shlomif/Download/unpack/file/vim/neovim/build/config -I/home/shlomif/Download/unpack/file/vim/neovim/src -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/.deps/usr/include -I/usr/include -I/home/shlomif/Download/unpack/file/vim/neovim/build/src/nvim/auto -I/home/shlomif/Download/unpack/file/vim/neovim/build/include
Compiled by shlomif@localhost.localdomain

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/shlomif/apps/neovim/share/nvim"

shlomif@lap:~$ 
```
- Vim (version: ) behaves differently? yes, it does
- Operating system/version: Fedora 25 x64 and Mageia Linux x64 v6
- Terminal name/version: konsole 16.12.3
- `$TERM`: xterm-256color
- Using ssh

### Actual behaviour

When editing the MAX_SEED line on this file in konsole in an ssh session, nvim emits random "q" characters on the screen.

```
#!/usr/bin/env python

import re
import sys
from os.path import expanduser, isfile
import json

if sys.version_info > (3,):
    xrange = range

MAX_SEED = 500

home = expanduser("~")

basedir = home + "/Backup/Arcs"

STATE_FN = basedir + "/FC_SOLVE_SUMMARIZE_RESULTS--state.json"

extract_len_re = re.compile(r'(?<=Length: )(-?[0-9]+)')


def extract(l):
    return int(extract_len_re.search(l).group(1))


NUM_DEALS = 32000


def calc_init_state():
    state = {'start_nums': [], 'reached_seed': 1, 'mysum': 0,
             'my_num_improved': 0, 'my_max': 0, 'output': '', }
    with open(basedir + "/FC_SOLVE_SUMMARIZE_RESULTS--fif-10.cat.txt") as fh:
        for l in fh:
            state['start_nums'].append(extract(l))
    assert len(state['start_nums']) == NUM_DEALS

    state['run_nums'] = list(state['start_nums'])

    return state


def write_state(state):
    with open(STATE_FN, 'w') as fh:
        fh.write(json.dumps(state))


if not isfile(STATE_FN):
    write_state(calc_init_state())

state = None
with open(STATE_FN) as fh:
    state = json.loads(fh.read())

print("Seed\tN\tSum\tMax")
sys.stdout.write(state['output'])
for seed in xrange(state['reached_seed'], MAX_SEED + 1):
    with open(basedir +
              "/fcs-summary-len-seed/lens-theme1--seed=%d.txt" % seed) as fh:
        i = 0
        for l in fh:
            new = extract(l)
            if new >= 0:
                delta = state['run_nums'][i] - new
                if delta > 0:
                    orig = state['start_nums'][i]
                    if state['run_nums'][i] == orig:
                        state['my_num_improved'] += 1
                    state['mysum'] += delta
                    init_delta = orig - new
                    if init_delta > state['my_max']:
                        state['my_max'] = init_delta
                    state['run_nums'][i] = new
            i += 1
    out_line = ("%d\t%d\t%d\t%d" %
                (seed, state['my_num_improved'],
                 state['mysum'], state['my_max']))
    state['output'] += out_line + "\n"
    print(out_line)

state['reached_seed'] = MAX_SEED
write_state(state)

``` 
### Expected behaviour

It should not emit them.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC sum.py
/500
R
<Esc>
:w
```

Note: it does not happen in : 1. vim 2. xterm 3. outside ssh.

**Comment by justinmk** [comment]
in your init.vim, put:

    let $NVIM_TUI_ENABLE_CURSOR_SHAPE=0

**Comment by shlomif** [comment]
Thanks, @justinmk ! This fixes the problem when I don't specify `-u NORC` but it still happens with `-u NORC`  specified. Is this a konsole bug?

**Comment by jamessan** [comment]
Yes.  It echoes unrecognized escape codes to the user instead of swallowing them.  Also, it apparently doesn't support cursor shaping.

Why is your `$TERM` set to xterm-256color instead of konsole-256color?  That may also help resolve the issue.

**Comment by shlomif** [comment]
On Thu, 30 Mar 2017 06:06:44 -0700
James McCoy <notifications@github.com> wrote:

> Yes.  It echoes unrecognized escape codes to the user instead of swallowing
> them.  Also, it apparently doesn't support cursor shaping.
> 

ah. well, it works fine outside ssh.

> Why is your `$TERM` set to xterm-256color instead of konsole-256color?  That
> may also help resolve the issue.
> 

Setting TERM to konsole-256color made the problem persist with `-u NORC` and
also later caused the shell's "reset" command to malfunction.

	-- @shlomif

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Original Riddles - http://www.shlomifish.org/puzzles/

Scary thought of the day: The Princess Bride - the 3-D remake.

**Comment by justinmk** [comment]
Since it was emitting "q" that means we didn't detect konsole, and instead assumed DECSCUSR support. @shlomif can you check in the same scenario, if `$KONSOLE_PROFILE_NAME` env var is found? Or any other `$KONSOLE_` env var, or any other thing that might be used to detect that konsole is running?

**Comment by shlomif** [comment]
On Sat, 01 Apr 2017 17:26:39 -0700
"Justin M. Keyes" <notifications@github.com> wrote:

> Since it was emitting "q" that means we didn't detect konsole, and instead
> assumed DECSCUSR support. @shlomif can you check in the same scenario, if
> `$KONSOLE_PROFILE_NAME` env var is found? Or any other `$KONSOLE_` env var,
> or any other thing that might be used to detect that konsole is running?
> 

Hi all!

In a konsole tab before sshing I get this:

```
shlomif@lap:~$ env | grep KONSOLE
KONSOLE_DBUS_SERVICE=:1.4496
KONSOLE_PROFILE_NAME=Shell
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_DBUS_SESSION=/Sessions/4
shlomif@lap:~$ 
```

after sshing to localhost I get this:

```
shlomif@lap:~$ env | grep KONSOLE
shlomif@lap:~$ 

```

hope it helps and thanks!

Regards,

	Shlomi Fish

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://shlomifishswiki.branchable.com/Self-Sufficiency/

Always reach for the stars! Because even if you miss… You’ll be miles away
from me with your motivational bullshit.
    — http://is.gd/PuH02m

**Comment by justinmk** [comment]
@shlomif Thanks! That explains it. We can't detect console in that case. Best we can do is disable cursor shaping by default if we aren't sure about the terminal. I'm working on that now.

**Comment by shlomif** [comment]
On Sun, 02 Apr 2017 02:39:54 -0700
"Justin M. Keyes" <notifications@github.com> wrote:

> @shlomif Thanks! That explains it. We can't detect console in that case. Best
> we can do is disable cursor shaping by default if we aren't sure about the
> terminal. I'm working on that now.
> 

Thanks, Justin! And - you're welcome.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Aphorisms - http://www.shlomifish.org/humour.html

When a FLOSS developer says they will work on something, he or she means
“maybe”.

**Comment by ZyX-I** [comment]
What prompt functionality emits those `q`s? I do not think that this exists just to bother DECSUSR cursor shaping users. And why is neither TERM_PROGRAM nor NVIM_TUI_ENABLE_CURSOR_SHAPE in documentation, somewhere inside `:h 'guicursor'`?

@shlomif You may force konsole recognition by exporting `TERM_PROGRAM=Konsole`

**Comment by justinmk** [comment]
> What prompt functionality emits those qs? I do not think that this exists just to bother DECSUSR cursor shaping users. 

Not sure I understand the question, but the logic is in `tui_set_cursor` (latest master).

> And why is neither TERM_PROGRAM nor NVIM_TUI_ENABLE_CURSOR_SHAPE in documentation, somewhere inside :h 'guicursor'?

Because NVIM_TUI_ENABLE_CURSOR_SHAPE was a temporary hack. It's not supported at all as of yesterday: it was removed. I'm working on a PR that allows disabling cursor control codes by `:set guicursor=`.

TERM_PROGRAM was just a mistake most likely taken from macOS, we never mentioned it anywhere and don't support it. It's also going to be removed today.

**Comment by ZyX-I** [comment]
> Not sure I understand the question, but the logic is in tui_set_cursor (latest master).

I mean that  when you write DECSUSR sequences to konsole they are not just ignored, but produce some result (even though this result are spurious `q`). This looks like some misused feature: e.g. a timer.

> TERM_PROGRAM was just a mistake most likely taken from macOS, we never mentioned it anywhere and don't support it. It's also going to be removed today.

And how user are supposed to tell that he is using Konsole? Setting KONSOLE_DBUS_SERVICE e.g. on remote is not going to be a good idea: there is no relevant service on the remote and these variables are most likely there because they are used by something.

**Comment by justinmk** [comment]
> And how user are supposed to tell that he is using Konsole? Setting KONSOLE_DBUS_SERVICE e.g. on remote is not going to be a good idea: there is no relevant service on the remote and these variables are most likely there because they are used by something.

What about KONSOLE_PROFILE_NAME?

**Comment by ZyX-I** [comment]
As long as there are only two distinct variants of setting the cursor one of which is used only by Konsole this is fine..

**Comment by shlomif** [comment]
On Tue, 04 Apr 2017 06:26:53 -0700
"Justin M. Keyes" <notifications@github.com> wrote:

> Closed #6403 via #6432.
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
“So, who the hell is Qoheleth?” - http://shlom.in/qoheleth

The more money Chuck Norris comes across, the less problems he sees.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by tiberiuichim** [comment]
I still get this problem, even with 

```
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=0
```

I don't have this problem with vim. I have neovim 0.2.1-dev

**Comment by jkhsjdhjs** [comment]
The error is occuring again with neovim 0.2.1
As @tiberiuichim mentioned, `set guicursor=` fixes it.
But why was it reimplemented?

**Comment by illtown** [comment]
I can confirm that bug reappeared after version update.
Moreover, it can be reproduced locally under usual text console (no X), no need for konsole or ssh.
And the fix works.

**Comment by justinmk** [comment]
Depends on $TERM. None of the last 3 reports are actionable without mentioning that.

**Comment by phi-mah** [comment]
I'm also hitting this bug with version 0.2.1.
```
echo $TERM                                                                                                                     ~
xterm-256color
```
Without exactly knowing what it does, `set guicursor=` helped...

**Comment by z3ntu** [comment]
Happens to me too: `$TERM` is `xterm-256color`.

**Comment by justinmk** [comment]
I don't understand the "me too" reports. The problem is explained clearly: it's a Konsole bug. It can be fixed by disabling 'guicursor', like this:

    set guicursor=

No need to say "me too".

**Comment by z3ntu** [comment]
Actually this seems to happen just as the root user. When I run `touch /tmp/a; nvim -u /tmp/a`, nvim works fine but when I run `touch /tmp/a; sudo nvim -u /tmp/a` I get the `q` after pressing `i`...

**Comment by justinmk** [comment]
When running as root, your personal user config isn't used, and Nvim by default changes the cursor shape. This is a design choice: we chose to enable cursor-shaping by default when $TERM suggests that it's ok to do so. 

Any half-decent terminal, even if it doesn't implement cursor-shaping, should ignore the cursor-shape sequences. The fact that people use some broken terminals that don't ignore the unknown sequences isn't going to change the default.

**Comment by jkhsjdhjs** [comment]
@z3ntu If you have `$EDITOR` exported as `nvim` you can use `sudoedit` to edit files with your user nvim config as root.

**Comment by z3ntu** [comment]
When I export/set the variable `KONSOLE_PROFILE_NAME` to something (ssh, sudo, etc), it fixes the issue. Setting `guicursor=` just disables the line cursor and makes the cursor blocky again. Is there a config option so I don't have to set `KONSOLE_PROFILE_NAME` manually but still have the line-cursor?

**Comment by justinmk** [comment]
> Is there a config option so I don't have to set KONSOLE_PROFILE_NAME manually but still have the line-cursor?

We could look for `TERM=xterm-konsole`.

The problem here is that `TERM=xterm-256color` is nonsense if you're running Konsole, because Konsole isn't xterm-compliant.

**Comment by carlosvigil** [comment]
I'm getting this issue on macOS with Cathode app.

**Comment by z3ntu** [comment]
@justinmk It looks like there are several konsole-* $TERM variables supported by ncurses (e.g. `konsole-256color`). xterm-konsole is not one though and sends warnings in some applications.

**Comment by justinmk** [comment]
@z3ntu Thanks, good to know. 

> xterm-konsole is not one though and sends warnings in some applications

Could you try `konsole-xterm` instead? What about `konsole` ?

Added support for `konsole-256color` in https://github.com/neovim/neovim/pull/7802.

**Comment by z3ntu** [comment]
There's no "konsole-xterm" provided by ncurses, just the following
```
/usr/share/terminfo/k/konsole-16color   /usr/share/terminfo/k/konsole-linux    /usr/share/terminfo/k/konsole-vt420pc
/usr/share/terminfo/k/konsole-256color  /usr/share/terminfo/k/konsole-solaris  /usr/share/terminfo/k/konsole-xf3x
/usr/share/terminfo/k/konsole-base      /usr/share/terminfo/k/konsole-vt100    /usr/share/terminfo/k/konsole-xf4x
```

**Comment by jonlandrum** [comment]
I couldn't change `guicursor` because I'm already modifying that, so changing `$TERM` to `konsole-256color` did the trick for me.

**Comment by Chandelier309** [comment]
The 'q' only happens when I'm using `sudo nvim something`. But don't show up when run nvim as a common use or super user. (Of course neither in Xterm)
And I tried the solutions, like set guicursor or $TERM, still have the 'q'. 
I'm using Konsole 17.12.2 and NVIM v0.2.2. What's wrong ?

**Comment by justinmk** [comment]
@jonlandrum If you are changing `guicursor` that implies the feature works. If it works you wouldn't have this issue. 

Locking this issue, there are enough "me too" comments.
