### ISSUE TITLE
Lua: define LUA_NOCVTS2N

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6407]
Lua by default has this behavior:

    "10" + 1 = 11.0

We can make the built-in lua a bit more strict by enabling some settings. AFAICT luajit supports this also. https://github.com/lua/lua/blob/e354c6355e7f48e087678ec49e340ca0696725b1/luaconf.h#L692

see https://twitter.com/pchapuis/status/847542893271293953

There could be other settings worth enabling. Like VimL, this is a application-specific language that we control, so if there are some things we want to change, we can.

cc @ZyX-I @raichoo @jamessan

**Comment by jamessan** [comment]
1. VimL behaves the same way.
2. Do we really have control? What if there are other modules that have these implicit conversions, which a plugin wants use?

**Comment by justinmk** [comment]
This also is one of the main reasons Lua (and, sure, VimL) has a different operator for catenation vs addition.

**Comment by ZyX-I** [comment]
What’s the point? We are going to receive a bunch of issues “my lua script does not work as expected” and tell everybody this is configurable behaviour configured as we need and not a bug?

BTW what is this setting going to do with unary plus? AFAIR unlike `string + number` I used that as `tonumber()` myself.

**Comment by justinmk** [comment]
Fair enough
