### ISSUE TITLE
Unable to open password protected file in zip archive

### ISSUE THREAD

**Issue by doomnuggets** [neovim/neovim#6408]
- `nvim --version`: NVIM 0.1.7
- Vim (version: ) behaves differently?
- Operating system/version: Linux arch 4.10.5-1-ARCH x86_64 (Arch Linux)
- Terminal name/version: terminator 1.91
- `$TERM`: xterm-256color

### Problem

When trying to open a file inside a password protected zip archive the zip password prompt seems to hang *"forever"*.

(If you need more information let me know).

### Actual behaviour

The password prompt is unresponsive and hangs "forever".

### Expected behaviour

The password prompt consumes the entered password and opens the file.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e ~/path/to/file.zip
try to open a file inside the password protected zip archive.
```

**Comment by jamessan** [comment]
This is due to external commands being run connected to a pipe instead of a tty.  See https://github.com/neovim/neovim/issues/1496 and https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes.
