### ISSUE TITLE
"Failed to load {python,python3} host" problem

### ISSUE THREAD

**Issue by someneat** [neovim/neovim#6414]
- `nvim --version`: 

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/bin/gcc-4.8 -Os -w -pipe -march=native -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/tmp/neovim-20170329-7422-5x2qy7/neovim-0.1.7/build/config -I/tmp/neovim-20170329-7422-5x2qy7/neovim-0.1.7/src -I/home/someneat/local/linuxbrew/include -I/home/someneat/local/linuxbrew/include -I/home/someneat/local/linuxbrew/include -I/home/someneat/local/linuxbrew/include -I/home/someneat/local/linuxbrew/include -I/home/someneat/local/linuxbrew/include -I/usr/include -I/tmp/neovim-20170329-7422-5x2qy7/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170329-7422-5x2qy7/neovim-0.1.7/build/include
Compiled by someneat@local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/someneat/local/linuxbrew/Cellar/neovim/0.1.7/share/nvim"
```
- Vim (version: `8.0 with patches 1-525`) behaves differently? - Yes
- Operating system/version: Ubuntu 14.04 (4.4.0-59-generic <span>#</span>80~14.04.1-Ubuntu)
- Terminal name/version: Using ssh
- `$TERM`: screen-256color

### Actual behaviour

Start Neovim with no plugins installed (empty `~/.config/nvim/init.vim`). `:echo has('python')` and `:echo has('python3')` both return `1`.

`:python print 'hello'`  returns an error:
```
function provider#python#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```
and so does `:python3 print('hello')`:
```
function provider#python3#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
```

### Expected behaviour
Both should print `hello` in the command line.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:python print 'hello'
:python3 print('hello')
```

### Other information
Neovim is installed via `Linuxbrew`. Both `python` and `python3` are installed locally using `Linuxbrew` as well. Also I have the latest python modules installed via `pip install neovim` and `pip3 install neovim` (also performed ). `CheckHealth` returns this:
```
## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /home/someneat/local/linuxbrew/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/someneat/local/linuxbrew/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13
```

Setting the $NVIM_PYTHON_LOG_FILE and performing the above `:python print 'hello'` and `:python3 print('hello')` give the following logs.

for python2:
```
2017-03-30 10:56:53,481 [DEBUG @ msgpack_stream.py:send:33] 4904 - sent [0, 1, 'vim_get_api_info', ()]
2017-03-30 10:56:53,482 [DEBUG @ base.py:send:113] 4904 - Sending 'vim_get_api_info'
2017-03-30 10:56:53,482 [DEBUG @ base.py:run:138] 4904 - Entering event loop
2017-03-30 10:56:53,482 [DEBUG @ msgpack_stream.py:_on_data:54] 4904 - waiting for message...
2017-03-30 10:56:53,482 [DEBUG @ msgpack_stream.py:_on_data:56] 4904 - received message: [0, 1, 'poll', []]
2017-03-30 10:56:53,482 [DEBUG @ async_session.py:_on_request:86] 4904 - received request: poll, []
2017-03-30 10:56:53,482 [DEBUG @ msgpack_stream.py:_on_data:54] 4904 - waiting for message...
2017-03-30 10:56:53,483 [DEBUG @ msgpack_stream.py:_on_data:59] 4904 - unpacker needs more data...
2017-03-30 10:56:53,483 [DEBUG @ msgpack_stream.py:_on_data:54] 4904 - waiting for message...
```
for python3:
```
2017-03-30 10:56:59,497 [DEBUG @ msgpack_stream.py:send:33] 4923 - sent [0, 1, b'vim_get_api_info', ()]
2017-03-30 10:56:59,497 [DEBUG @ base.py:send:113] 4923 - Sending 'b'\x94\x00\x01\xb0vim_get_api_info\x90''
2017-03-30 10:56:59,499 [DEBUG @ base.py:run:138] 4923 - Entering event loop
2017-03-30 10:56:59,499 [DEBUG @ msgpack_stream.py:_on_data:54] 4923 - waiting for message...
2017-03-30 10:56:59,499 [DEBUG @ msgpack_stream.py:_on_data:56] 4923 - received message: [0, 1, b'poll', []]
2017-03-30 10:56:59,499 [DEBUG @ async_session.py:_on_request:86] 4923 - received request: b'poll', []
2017-03-30 10:56:59,499 [DEBUG @ msgpack_stream.py:_on_data:54] 4923 - waiting for message...
2017-03-30 10:56:59,499 [DEBUG @ msgpack_stream.py:_on_data:59] 4923 - unpacker needs more data...
2017-03-30 10:56:59,500 [DEBUG @ msgpack_stream.py:_on_data:54] 4923 - waiting for message...
```

The weird thing is that I have another machine with the same versions of OS, Neovim, python and python3 (but different CPU) which works perfectly. I would appreciate if anyone can give me some advice on where and what I should check to solve this issue. Thank you very much.

**Comment by justinmk** [comment]
Currently the only option is to attach a debugger  to the python process to see  why it closes the channel.

**Comment by someneat** [comment]
@justinmk Thanks for your prompt response! That's the kind of advice I was looking for. I'll try that and see if I can hunt down the problem.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/4468 . Without further information this is essentially the same issue, so merging with that.

**Comment by someneat** [comment]
Thanks for the pointer @justinmk. Yes from the error message point of view it can be considered the same issue.

In my case, I managed to fix the problem which actually had nothing to do with Neovim. Similar issues can be found in #2258 and #4470, where my solution was:
```pip install --no-cache-dir --upgrade --force reinstall neovim```
and
```pip3 install --no-cache-dir --upgrade --force reinstall neovim```.
The `--no-cache-dir` option which disables the cache was the key. There are people reporting that the reinstall fixing their problems, but I think none of them mentioned about the cache problem I ran into, and thus I decided to leave a note which might be of help for someone else having a similar problem.

I followed the procedure described [here](https://github.com/neovim/python-client#usage-through-the-python-repl):

1. start Neovim with `NVIM_LISTEN_ADDRESS=/tmp/nvim nvim` in a terminal
2. in another terminal execute `python` or `python3`:
```
Python 3.6.1 (default, Mar 30 2017, 19:12:03)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neovim import attach
>>> nvim = attach('socket', path='/tmp/nvim')
[1]    19837 illegal hardware instruction (core dumped)  python3
```
and the same happened for `python` as well. So somehow there are binaries which are compiled for newer processors.

Well, although I haven't fully understood the details, the problem was due to `pip`'s cache shared among different machines (yes it might be a rare case, my home directory is shared on the network across multiple machines). Some cached data from a newer CPU (probably some binaries that get installed with `pip install nevoim` and/or `pip3 install neovim`) got installed to this older machine and caused the problem. Therefore giving the `--no-cache-dir` or removing the cache directory and performing a reinstall was the way to fix it.

Thank you very much again @justinmk for your kind response.

**Comment by justinmk** [comment]
@someneat Thanks for the followup!

**Comment by gsagula** [comment]
My general feeling is that whatever involves python becomes painful. What a garbage environment to work with!

**Comment by OrionRandD** [comment]
I had this error as well and what I did was just create a symlink from python3 to python
ln -s /usr/bin/pytho3 /us/bin/python
