### ISSUE TITLE
[feature request] Add extension points allowing arbitrary modification of UI behaviour, particularly off-by-none mode

### ISSUE THREAD

**Issue by ewtoombs** [neovim/neovim#6416]
For a description of the kinds of UI behaviour modifications that would be made possible, see #6415. But the idea is it would allow neovim to basically behave like any editor you want—variations of the big three, emacs, notepad, vi; kakoune-style object-verb command order in normal mode, whatever.

The specifics of what this instrumentation would look like are eluding me right now. In fact, it was my understanding that neovim already had this capability, but I guess I was wrong. But this is what I could come up with:

Define two separate objects, one for the UI state and for the state of the text file. Cursor position would be part of the UI state and not part of the file state. Implement a simple interface for file events and operations and one for UI events and operations. Implement an object, called a controller, which consumes all UI and file events and decides what file and UI operations to do in response. Allow for the UI and file states to be connected with different controllers.

Functionality common to many controllers could be encapsulated into objects like parsers, code completion handlers, code navigators (i.e. ctrl-], ctrl-o), and syntax highlighters. Controllers written in a language like python could even inherit from base controllers, allowing for variations in a certain basic editing behaviour, so that off-by-none and any other possible variations on the vi style would inherit from a base vi controller class.

Or I don't know, whatever is most appropriate for neovim. Whatever extension points @justinmk meant when he said "That being said, we're definitely open to adding extension points that make it possible to achieve [off-by-none]. But this won't be a core feature."

**Comment by justinmk** [comment]
"arbitrary modification of UI behavior" is extremely vague. We have ongoing work to externalize parts of the UI. But the current description here means we could never close this issue, since there will always be parts of the UI that are not (yet) arbitrarily modifiable. 

Could you open a specific request, or just a PR?

**Comment by ewtoombs** [comment]
I agree, just that phrase is extremely vague. That's why I supplemented it with examples of the kind of thing that could be made possible, i.e. emacs, MSVC/notepad, kakoune, or off-by-none modes. Still not super great, but not so vague as just the phrase you quoted by itself. And I gave actually a very specific example of a UI modification in the issue I linked to. As for the later paragraph describing implementation, if it makes no sense within the context of neovim, pay no attention to it. Actually, I was hoping you could help fill in some gaps. What exactly did you mean when you said extension points?

**Comment by justinmk** [comment]
"emacs, MSVC, kakoune" don't narrow down the goal.

> Actually, I was hoping you could help fill in some gaps. What exactly did you mean when you said extension points?

I don't know. It requires someone to take the lead on the task and figure out exactly what parts need to be changed to achieve the goal. And that person isn't going to be me.
