### ISSUE TITLE
konsole: Mouse selection is brittle

### ISSUE THREAD

**Issue by lourenko** [neovim/neovim#6426]
- `nvim --version`: NVIM v0.2.0-1086-g6964b67 Build type: RelWithDebInfo
- Vim (version: ) behaves differently? Yes, select correctly.
- Operating system/version: Ubuntu 16.04.2 LTS
- Terminal name/version: Konsole
- `$TERM`: xterm-256

### Actual behaviour
Impossible to select only some characters of a word using the mouse left key.
### Expected behaviour
When using `mouse=a` option, select only some characters of a word.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set mouse=a
```
Write `print` in the screen. Try to select the sequence `pri` (visual or insert mode) using the left key of mouse.

**Comment by justinmk** [comment]
If you revert https://github.com/neovim/neovim/pull/6411 does it work? Or when did this start happening? Did it work on older versions of nvim?

**Comment by lourenko** [comment]
I don't have tried to revert #6411 neither work on an older version of nvim.
Although, it seems to affect only konsole. I have tried Xterm, gnome
terminal,
etc, and nvim work as expected in all of these.

Marcos Lourenço

**Comment by justinmk** [comment]
@lourenko you are using 'termguicolors', correct? Workaround is to unset 'guicursor' (or disable 'termguicolors', but that's more drastic):

    :set guicursor=

@lourenko Also what does `:echo $KONSOLE_PROFILE_NAME` say?

**Comment by lourenko** [comment]
Correct @justinmk, but even if I unset 'guicursor' this do not work.
`:echo $KONSOLE_PROFILE_NAME` returns `normal`.
