### ISSUE TITLE
Broken Characters in Command Mode and with vim-latex

### ISSUE THREAD

**Issue by fraxx001** [neovim/neovim#6430]
- `nvim --version`: NVIM v0.2.0-dev
- Vim (version: ) behaves differently?  yes
- Operating system/version: Linux ubuntu-tower 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Terminal name/version:
- `$TERM`: xterm
- Terminal Emulator: terminator 0.98

### Actual behaviour
Open a .tex/.cpp/.c file (with vim-latex plugin):
When inserting some text, there is always a bad encoding string in textfield 
after the newly inserted characters and in the command 
field. The Error occurs with and without $NVIM_TUI_ENABLE_CURSOR_SHAPE=0.

### Expected behaviour
Not to do this.

### Steps to reproduce using `nvim -u NORC`
Without plugins the command strings shows bad character string
and shows a broken string after using the replace button r. In Vimtex 
or programming environment 
this also occurs in inserting mode and the broken encoding is always
visible after inserting the first char.

nvim -u NORC

**Comment by teto** [comment]
could you paste the string you see ? NVIM_TUI_ENABLE_CURSOR_SHAPE is not used anymore see https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by justinmk** [comment]
We're in an awkward state. I'm working on a PR that will allow disabling cursor shaping if 'guicursor' is empty.

**Comment by fraxx001** [comment]
Hey,
here a screenshot.
![scrrenshot](https://cloud.githubusercontent.com/assets/8928247/24614621/0ce2a826-188c-11e7-88a6-dd5f0d899fff.png)

thx

**Comment by teto** [comment]
I just installed terminator  but printf "\x1b[3 q" doesn't change the cursor as it does on vte based terminals (and terminator looks vte-based). Looking into the doc.

**Comment by justinmk** [comment]
Depends on the libvte version. Older libvte would print the sequences as reported.

**Comment by teto** [comment]
but we have a check for the VTE version that disables cursor updates. 
`  } else if (!vte_version || atoi(vte_version) >= 3900) {`

@fraxx001 could you give `echo $VTE_VERSION` ?

**Comment by fraxx001** [comment]
The variable is empty

**Comment by teto** [comment]
Yep it seems that terminator is written in python and removes the VTE_VERSION value :s 
```
if os.environ.has_key('VTE_VERSION'):
        del os.environ['VTE_VERSION']
```
I could not find how to dynamically configure the cursor ? can you just configure it on startup in ~/.config/terminator/config cursor_shape =  ?
if that's the case that's sad for an emulator IMO. Maybe we should change the check to 
` (vte_version && atoi(vte_version) >= 3900) {`

**Comment by justinmk** [comment]
> Maybe we should change the check to (vte_version && atoi(vte_version) >= 3900) { (and add checks for xterm etc).

We'll be more conservative in initializing 'guicursor'. If e.g. VTE_VERSION is not found, we disable it. But if user explicitly sets 'guicursor' we send the terminal codes anyways.

**Comment by teto** [comment]
Meanwhile @fraxx001 you can do `export VTE_VERSION="100"` and nvim-dev should work without updating the cursor.

**Comment by fraxx001** [comment]
Ok thank you @teto  this quick fix works.  I like the splitting feature in terminator and can't find another terminal emulator which can fork into a new terminal window with same working directory but if it conflicts so hard with nvim I will use an other in the future.

**Comment by teto** [comment]
@fraxx001 terminator should not cause any problem with the coming up PRs.
Nevertheless, if you like the splitting feature, I can only recommand you to try a tiling window manager (WM), such as www.i3wm.org. This gives a unified approach across applications to window management. As for the current working directory, you can mimic that behaviour with close to all terms (termite has a script to do it or you can use xcwnd and call an emulator with the required parameter to set the current working directory).
