### ISSUE TITLE
Gutter on both sides

### ISSUE THREAD

**Issue by xelra** [neovim/neovim#6438]
It would be really great if it were possible to have two gutters.

Using relativenumbers is great if you make edits in small files. When editing long files, absolute numbers are a lot more convenient for jumping across the file.

While editing files, I've been in the situation where I wanted to switch between relative and absolute numbers quite often.

Having relative numbers in one gutter and absolute numbers in the other gutter, would really be a great feature.

Thank you for considering.

**Comment by tjdevries** [comment]
Just so you know, you can have both of them on at the same time.

Not saying this isn't a good idea for other things, but just to let you know :)

**Comment by lewis6991** [comment]
Implementable as a plugin. Not enough demand to warrant adding this directly to core.
