### ISSUE TITLE
:Context command not available

### ISSUE THREAD

**Issue by pdoak** [neovim/neovim#6446]
- `nvim --version`: NVIM v0.2.0-704-gbe65fd88
- Vim (version: ) behaves differently? 8.0
- Operating system/version: 10.12.4
- Terminal name/version: iTerm Build 3.1.20170226-nightly
- `$TERM`: tmux-256color

### Actual behaviour

Isssueing `:ConText` gives error`E492: Not an editor command`

### Expected behaviour

Compiles context document

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Context

```

**Comment by pdoak** [comment]
@justinmk : Why was this closed. Did I do something wrong?

**Comment by justinmk** [comment]
No context was provided.

`:helpgrep Context` doesn't show a `:Context` command, so it has nothing to do with nvim. Also the error shows `:ConText` which is different than the step you provided.

**Comment by pdoak** [comment]
Sorry, I made a typo in the `Steps..` part but it was correctly stated in the `Actual behavior`. The `:ConText` command is part of `vim`. Is this functionality not going to be supported in `nvim`?

**Comment by jamessan** [comment]
No, it isn't part of vim.  You must have some additional plugins installed (either in your ~/.vim directory or system-wide) that aren't part of vim.

```sh
$ git log -1 --oneline
ba6ec1829 patch 8.0.0543: test_edit causes older xfce4-terminal to close
$ ag 'Con[tT]ext' runtime | grep com
runtime/doc/quickref.txt:1076:Context-sensitive completion on the command-line:
runtime/syntax/cmusrc.vim:41:syn keyword cmusrcBindContext   contained common library playlist queue
runtime/syntax/cmusrc.vim:218:syn keyword cmusrcSBindContext  contained common library playlist queue
runtime/autoload/rubycomplete.vim:732:            next if m.name != "IRB::Context" and
```

**Comment by pdoak** [comment]
@jamessan : Thank you for the explanation. I am slightly confused as I don't believe that I have any plugins installed relating to ConText.

The [ConText wiki](http://wiki.contextgarden.net/Vim) page states the following:

> Using ConTeXt in Vim
> 
> Nikolai Weibull was the first one who wrote context.vim files and submitted them to the official Vim repository. They are part of the official Vim 7 and were expanded and improved in Vim 8.

That suggests that it comes as part standard Vim.

Any help to help me get this similar functionality in nvim is much appreciated.

**Comment by jamessan** [comment]
Yes, there are runtime/{syntax,ftplugin,indent}/context.vim files in both Vim and Neovim.  The addition of the `:ConTeXt` command (note the casing, which doesn't match any of the ways you've typed it so far :smile:), was only added after maintenance of those files was taken over by Nicola Vitacolonna in https://github.com/vim/vim/commit/46fceaaa8d1447a9588736d86eb4908214187b08#diff-045f75c5055490f93ff3ffc6c6ced931.

So this will eventually get merged, but we haven't gotten to it yet.

**Comment by pdoak** [comment]
@jamessan : Sorry about not typing it correctly!! Thanks for letting me know. Do you have any ideas as to when this code might get merged.
