### ISSUE TITLE
[Feature Request] provide plugin developers the context information based on the cursor

### ISSUE THREAD

**Issue by pencilcheck** [neovim/neovim#6448]
https://github.com/scrooloose/nerdcommenter/issues/280

Quoting from @alerque  in the original issue
```Vim doesn't provide (at least not readily) context sensitive information about what type of language block you are it. As far as NerdCommenter is concerned this is pretty much a one shot deal. Either the filetype is plain JS (in which case you get plain JS comments) or it is JSX, in which case you get React style comments. It doesn't try to parse the surrounding lines to toggle back and forth between language modes.```

Just wondering if neovim can provide plugin developers the context information based on the cursor on it. Since JSX can be written in a JS file and they need different syntax highlighting and file type handling but they are all in the same file.

**Comment by justinmk** [comment]
This is up to ftplugin authors to deal with. External tools like LSP could help, see https://github.com/neovim/neovim/issues/5522

If there is some specific change needed in nvim core, please open a request for that.
