### ISSUE TITLE
Unable to install NeoVim on macOS 10.12

### ISSUE THREAD

**Issue by Integralist** [neovim/neovim#6450]
![screen shot 2017-04-06 at 9 33 07 am](https://cloud.githubusercontent.com/assets/180050/24745058/255bb8f8-1aac-11e7-9657-43e279d1914a.png)

### Steps taken

```
cd /private/tmp

$ curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   593    0   593    0     0   1330      0 --:--:-- --:--:-- --:--:--  1329
100 7224k  100 7224k    0     0  2095k      0  0:00:03  0:00:03 --:--:-- 3044k

$ tar xzf nvim-macos.tar.gz

$ ./nvim-osx64/bin/nvim

# NOTHING HAPPENS AT THIS POINT
# NEOVIM DOESN'T LOAD
# STAYS ON BLANK TERMINAL SCREEN
```

**Comment by Integralist** [comment]
I've equally tried installing from Homebrew (something I've done successfully in the past), but it equally stalls?

**Comment by Integralist** [comment]
Hi @justinmk 

So both `./nvim-osx64/bin/nvim -u NONE` and `./nvim-osx64/bin/nvim -u NONE +'set guicursor='` do the same, nothing happens. Just the blank terminal shell

**Comment by justinmk** [comment]
Latest build works for me in yosemite in Terminal.app and iTerm2. What terminal are you using? (In general, please answer the questions in the issue template)

**Comment by Integralist** [comment]
> In general, please answer the questions in the issue template

Apologies...

- `nvim --version`: N/A
- Vim (version: `8.0`) behaves differently? N/A
- Operating system/version: `macOS Sierra 10.12`
- Terminal name/version: standard mac terminal application
- `$TERM`: `screen-256color`

**Comment by Integralist** [comment]
Here's the result of the debug...

```
$ ./nvim -D
Entering Debug mode.  Type "cont" to continue.
cmd: augroup nvim_terminal
>cont
```

Immediately hangs

**Comment by justinmk** [comment]
$TERM: screen-256color

Hmm. Are you in tmux or screen? Could you try without tmux/screen, with `TERM=xterm-256color`

**Comment by Integralist** [comment]
OK, so it seems (can't believe I'm going to say this...) a "turn it off/on" appears to have resolved the problem 😞
