### ISSUE TITLE
Get rid of vim_strrchr()

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#6471]
@ZyX-I  is getting rid of `vim_strbyte()` (#6460). I noticed we also have `vim_strrchr()`:

```c
/*
 * Search for last occurrence of "c" in "string".
 * Return NULL if not found.
 * Does not handle multi-byte char for "c"!
 */
char_u *vim_strrchr(const char_u *string, int c)
  FUNC_ATTR_NONNULL_ALL FUNC_ATTR_PURE
{
  const char_u *retval = NULL;
  const char_u *p = string;

  while (*p) {
    if (*p == c)
      retval = p;
    mb_ptr_adv(p);
  }
  return (char_u *) retval;
}
```

It specifically mentions that it doesn't handle multi-byte `c`, but it does skip over bytes that are part of a multi-byte UTF8 sequence. A bit odd.

Likely we could resolve that in a similar way as @ZyX-I's `vim_strchr` rework: https://github.com/neovim/neovim/pull/6460/commits/d611d337072ea907686258e21e08fb2bdb25be06.

There's a couple of edge cases to take into account. For example, if `c >= 0x80`, then the current code would never match anything. Reason: the loop always synchronizes to the first byte of a UTF8 encoded unicode codepoint, which is always `< 0x80`. Anything over `0xFF` would have never matched anyway.

So perhaps we need to also review all callsites (only 9) and see if we can't just use plain `strrchr` or use @ZyX-I's trick of interpreting `c` as a codepoint, encoding it as UTF-8, and searching for it with `strstr`.

```
rg -g '!strings.c' 'vim_strrchr\(' | wc -l
9
```

**Comment by bfredl** [comment]
I would guess this function was useful for some dbcs encodings that are not self-synchronized, i e 00-7F can both be ASCII and second byte of two-byte sequence, so you can't trivially search backwards. But with UTF-8 as nvim now only uses this is not an issue, `strrchr` should work to reliably find ASCII chars like `/`

**Comment by aktau** [comment]
>  But with UTF-8 as nvim now only uses this is not an issue, strrchr should work to reliably find ASCII chars like /

Indeed :).

**Comment by doubleloop** [comment]
should't this be closed after (https://github.com/neovim/neovim/commit/22311457ab60be9335f8e630c8b794340d39e466) ?

**Comment by janlazo** [comment]
Yes
