### ISSUE TITLE
neovim build fails when building penlight dependency

### ISSUE THREAD

**Issue by cschol** [neovim/neovim#6472]
With current master branch of neovim (1813076c), the build fails when building the `penlight` dependency. My system is Ubuntu 14.04.2.

`make distclean` and rebuild does not resolve this issue.

Build Output:

[ 95%] Generating usr/lib/luarocks/rocks/penlight/1.3.2-2

Missing dependencies for penlight:
luafilesystem

Using https://luarocks.org/luafilesystem-1.6.3-2.src.rock... switching to 'build' mode
/usr/bin/cc -O2 -fPIC -I/home/dood/src/neovim/.deps/usr/include/luajit-2.0 -c src/lfs.c -o src/lfs.o
/usr/bin/cc -shared -o lfs.so -L/home/dood/src/neovim/.deps/usr/lib src/lfs.o
Updating manifest for /home/dood/src/neovim/.deps/usr/lib/luarocks/rocks
luafilesystem 1.6.3-2 is now built and installed in /home/dood/src/neovim/.deps/usr (license: MIT/X11)

Archive:  penlight-1.3.2-core.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of penlight-1.3.2-core.zip or
        penlight-1.3.2-core.zip.zip, and cannot find penlight-1.3.2-core.zip.ZIP, period.

Error: Directory penlight-1.3.2 not found inside archive penlight-1.3.2-core.zip
make[3]: *** [usr/lib/luarocks/rocks/penlight/1.3.2-2] Error 1
make[3]: Leaving directory `/home/dood/src/neovim/.deps'
make[2]: *** [CMakeFiles/penlight.dir/all] Error 2
make[2]: Leaving directory `/home/dood/src/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/dood/src/neovim/.deps'
make: *** [deps] Error 2

**Comment by justinmk** [comment]
It failed to download for some reason. That's up to your network. Just try again, or try on a different network.
