### ISSUE TITLE
Alt bindings don't work sometimes

### ISSUE THREAD

**Issue by kuon** [neovim/neovim#6476]
- `nvim --version`:
```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- Operating system/version:
`Linux orochi 4.10.8-1-ARCH #1 SMP PREEMPT Fri Mar 31 16:50:19 CEST 2017 x86_64 GNU/Linux`
- Terminal name/version:
`fish, version 2.5.0` on terminator 1.91
- `$TERM`: `xterm-256color`

### Actual behaviour

I have the following bindings in my `init.vim`

```
" Use alt-[hjkl] to select the active split!
nmap <M-h> :wincmd h<CR>
nmap <M-j> :wincmd j<CR>
nmap <M-k> :wincmd k<CR>
nmap <M-l> :wincmd l<CR>

```

Note: I tried with `<C-w>hjkl` and I have the same problem.

The bindings works, but sometimes, don't. It's not related to how fast I type it.

When the bindings don't work, it just moves the cursor as alt was not pressed. (and yes, my keyboard is fine). Pressing <alt-hjkl> again eventually works (or I give up and type <C-w>hjkl manually).

### Expected behaviour

The binding should work all the time.

### Steps to reproduce using `nvim -u NORC`

I'm unable to reproduce it with 100% success.

----

I understand this issue is a bit blurry, and could be caused by terminator, my X11 server or whatever, but this behaviour might ring a bell to people familiar with neovim source code.

**Comment by justinmk** [comment]
ttimeoutlen=50

**Comment by kuon** [comment]
While it fixed the issue and I appreciate the answer, would you care to elaborate why the behaviour was random and unrelated to the speed I typed the shortcut?

**Comment by kuon** [comment]
After working with that setting for a day, it did not fully fix the problem. I feel the behaviour is less frequent, but there are still time when it doesn't work.

**Comment by justinmk** [comment]
@kuon Are you using screen or tmux? See https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

Anyways, this has been discussed numerous times, please search the issue tracker.

**Comment by kuon** [comment]
No I'm not using either screen of tmux.

I read nearly a dozen issues about the alt key but it goes in all directions and it's hard to tell what still applies and what has been patched. The general conclusion is that there is no "proper" way of making alt work.

I guess I'll find another binding that is not using alt.
