### ISSUE TITLE
errors.tar.gz are downloaded as part of running cmake

### ISSUE THREAD

**Issue by jamessan** [neovim/neovim#6484]
#6482 introduces unnecessary network access to the build with no (obvious to me) way to disable it.  Network access is forbidden in many distro build environments, so this is likely going to break their builds even though they'll never be running clint in the first place.

**Comment by ZyX-I** [comment]
I think this is a matter of adding `EXCLUDE_FROM_ALL 1` to `ExternalProject_add`.

**Comment by ZyX-I** [comment]
https://github.com/neovim/neovim/commit/c8243ad071f6cfcb9650ee00c53feadaaf7d90d5

**Comment by jamessan** [comment]
Thanks!

**Comment by ZyX-I** [comment]
Not so easy actually. This argument was added in CMake 3.1.0, so will have to rework to abstract that via a separate cmake file.

**Comment by ZyX-I** [comment]
And ExternalProject may not appear in a separate script because it uses define_property which is not scriptable.
