### ISSUE TITLE
make \r and \n more consistent when substituting

### ISSUE THREAD

**Issue by toogley** [neovim/neovim#6502]
To cite [a stackoverlfow answer of "Why is \r a newline for Vim?"](
http://stackoverflow.com/a/12388814):

>    ## When Searching
>    \n is newline, \r is CR (carriage return = Ctrl-M = ^M)
>    ## When Replacing
>    \r is newline, \n is a null byte (0x00).

I think it'd make sense to provide an option to replace the above functionality with sth more consistent.

Maybe:

* \n is always newline
* \r is always carriage return
* \N is null byte (0x00)

**Comment by justinmk** [comment]
You can use `:cabbrev` to alias this if it bothers you. I can't imagine how providing an option for this would be justified, not to mention it will break plugins.
