### ISSUE TITLE
Cursor highlight after `:highlight clear|syntax reset`

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6508]
After `:highlight clear|syntax reset`, `:hi Cursor` looks like this:

    Cursor         xxx cleared

gVim does this:

    Cursor         xxx guifg=bg guibg=fg  

ref https://github.com/junegunn/seoul256.vim/pull/41#issuecomment-293611409

**Comment by cyansprite** [comment]
`:verbose hi Cursor`
Cursor         xxx guifg=#ffffff
        Last set from ~/.config/nvim/colors/cyansprite.vim
This will make the cursor inverse without going to a black cursor, it's a temp fix I have found.

**Comment by justinmk** [comment]
@zhou13 Any insight into this? I'm guessing we are missing some logic from gvim.

**Comment by zhou13** [comment]
https://github.com/vim/vim/blob/c96272e30e2b81e5e0c8418f09d9db4e2fcd5d73/src/syntax.c#L6881
