### ISSUE TITLE
Mouse single click is the same with double click.

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#6510]
- `nvim --version`: latest
- Vim (version: ) behaves differently? yes
- Operating system/version:
- Terminal name/version:
- `$TERM`: xterm

### Actual behaviour
Mouse single click is the same with double click.
### Expected behaviour
Single click is single click.
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment]
Maybe try TERM=xterm-256color

Also what terminal (as the template asked)?

**Comment by justinmk** [comment]
Did TERM=xterm-256color help?

**Comment by Yggdroot** [comment]
No help.

**Comment by justinmk** [comment]
Well, it works for me in iterm2 with HEAD, and https://github.com/neovim/neovim/issues/4887 is in 0.1.7, covered by functional tests. So we're going to need more information or a reduced test case.

**Comment by justinmk** [comment]
Can you try another terminal? Seems like your setup is not working well with nvim, and probably is the same situation causing https://github.com/neovim/neovim/issues/6522. 

We can try to support "xshell" somehow but first we need to know what's different about it.
