### ISSUE TITLE
NeoVim loads `after` scripts before packages

### ISSUE THREAD

**Issue by nelstrom** [neovim/neovim#6511]
- `nvim --version`: NVIM v0.2.0-751-g8bbdef1
- Vim version: 8.0.543
- Operating system/version: OS X 10.12.4
- Terminal name/version: iterm2 3.0.15
- `$TERM`: xterm-256color

### Actual behaviour

`after` directories are loaded before the packages.

### Expected behaviour

`after` directories should be loaded after packages.

### Steps to reproduce using `nvim -u NORC`

Wipe out existing NeoVim configuration, then install the [tabular](https://github.com/godlygeek/tabular) plugin in a package.

    rm -rf ~/.config/nvim
    mkdir -p ~/.config/nvim/pack/bundle/start/
    cd ~/.config/nvim/pack/bundle/start/
    git clone git@github.com:godlygeek/tabular.git

Then create a file for configuring tabular after it's loaded:

    mkdir -p ~/.config/nvim/after/plugin
    touch ~/.config/nvim/after/plugin/tabular_extra.vim

Launch neovim:

    nvim -u NORC

And inspect the loaded scripts:

    :scriptnames
      1: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/filetype.vim
      2: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/ftplugin.vim
      3: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/indent.vim
      4: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/syntax/syntax.vim
      5: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/syntax/synload.vim
      6: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/syntax/syncolor.vim
      7: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/gui_shim.vim
      8: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/gzip.vim
      9: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/health.vim
     10: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/man.vim
     11: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/matchit.vim
     12: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/matchparen.vim
     13: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/netrwPlugin.vim
     14: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/rplugin.vim
     15: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/rrhelper.vim
     16: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/shada.vim
     17: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/spellfile.vim
     18: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/tarPlugin.vim
     19: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/tohtml.vim
     20: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/tutor.vim
     21: /usr/local/Cellar/neovim/HEAD-8bbdef1/share/nvim/runtime/plugin/zipPlugin.vim
     22: ~/.config/nvim/after/plugin/tabular_extra.vim
     23: ~/.config/nvim/pack/bundle/start/tabular/plugin/Tabular.vim

The `tabular_extra.vim` script should appear after the `Tabular.vim` script.

In Vim 8.0.543 it works correctly:

    :scriptnames
      1: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/getscriptPlugin.vim
      2: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/gzip.vim
      3: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/logiPat.vim
      4: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/manpager.vim
      5: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/matchparen.vim
      6: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/netrwPlugin.vim
      7: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/rrhelper.vim
      8: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/spellfile.vim
      9: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/tarPlugin.vim
     10: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/tohtml.vim
     11: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/vimballPlugin.vim
     12: /usr/local/Cellar/vim/8.0.0543/share/vim/vim80/plugin/zipPlugin.vim
     13: ~/dotfiles/vim/pack/bundle/start/tabular/plugin/Tabular.vim
     14: ~/dotfiles/vim/after/plugin/tabular_extra.vim
     15: ~/dotfiles/vim/pack/bundle/start/tabular/after/plugin/TabularMaps.vim

**Comment by justinmk** [comment]
8bbdef1 doesn't have 6baa669c10518b8751904a31899feb897fb7c995. Updating to HEAD should fix it.

**Comment by nelstrom** [comment]
@justinmk that fixed it. Thanks!

**Comment by nelstrom** [comment]
Closed by #6326.
