### ISSUE TITLE
third-party fails to download unibilium archive from GitHub

### ISSUE THREAD

**Issue by jpedrick** [neovim/neovim#6515]
- `nvim --version`: dd391bfca1f37093ba556f5da6a7f3eb81147fc0
- Vim (version: ) behaves differently? N/A
- Operating system/version: RHEL 5.6
- Terminal name/version: N/A
- `$TERM`: N/A

### Actual behaviour
```
make[3]: Entering directory `/local/home/jpedrick/neovim/.deps'
[  1%] Performing download step for 'unibilium'
-- file: /home/jpedrick/neovim/.deps/build/downloads/unibilium/v1.2.0.tar.gz
-- downloading...
     src='https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz'
     dst='/home/jpedrick/neovim/.deps/build/downloads/unibilium/v1.2.0.tar.gz'
     timeout='none'
CMake Error at /home/jpedrick/neovim/third-party/cmake/DownloadAndExtractFile.cmake:74 (message):
  error: downloading
  'https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1
```

### Expected behaviour
unibilium downloads and builds

### result from curl command line 
- curl needs 'location' option to follow redirect to 'code load.github.com' or link needs to be updated to support new GitHub api.
```
curl https://github.com/mauke/unibilium/archive/v1.2.0.tar.gz
<html><body>You are being <a href="https://codeload.github.com/mauke/unibilium/tar.gz/v1.2.0">redirected</a>.</body></html>%                                                                 
(17-04-13 18:43:01) <0> [~/neovim]
```

**Comment by jamessan** [comment]
> result from curl command line
> 
> curl needs 'location' option to follow redirect to 'code load.github.com' or link needs to be updated to support new GitHub api.

Which is different from the result in CMake:

> status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

Whatever libcurl CMake is using needs to be rebuilt to support https.

**Comment by jamessan** [comment]
See also the discussion starting [here](https://github.com/neovim/neovim/issues/2273#issuecomment-87047437).
