### ISSUE TITLE
Building without internet acess

### ISSUE THREAD

**Issue by nemith** [neovim/neovim#6518]
- `nvim --version`: 1.7
- Operating system/version: Centos 7

I am trying to build neovim on a server without internet access using only and it fails since luarocks dependencies are fetched during build time.  This is in order to have reproducible builds.

Is there a way to prefetch these?  

```
[ 70%] Generating usr/lib/luarocks/rocks/mpack
yes
checking for perfstat_cpu in -lperfstat... no
checking for pthread_mutex_init in -lpthread... Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /builddir/.cache/luarocks/https___luarocks.org/manifest
yes
checking for clock_gettime in -lrt... Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/ - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-
org/moonrocks-mirror/master/manifest - /builddir/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master_/manifest
yes
checking for sendfile in -lsendfile... Warning: Failed searching manifest: Failed fetching manifest for http://luafr.org/moonrocks/ - Failed downloading http://luafr.org/moonrocks/manifest - /builddir/.cache/luarocks/http___luafr.org_moonrocks_/manifest
no
checking for socket in -lsocket... Warning: Failed searching manifest: Failed fetching manifest for http://luarocks.logiceditor.com/rocks - Failed downloading http://luarocks.logiceditor.com/rocks/manifest - /builddir/.cache/luarocks/http___luarocks.logic
editor.com_rocks/manifest
Error: Could not find a result named mpack.
make[2]: *** [usr/lib/luarocks/rocks/mpack] Error 1
make[1]: *** [CMakeFiles/mpack.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
no
```

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies

https://github.com/neovim/neovim/pull/1588

**Comment by nemith** [comment]
So I do manually download and put luarocks into .deps/build/src.  It's more about the rocks themselves.

I don't see how the link helps, or maybe i am not understanding it correctly.

**Comment by ZyX-I** [comment]
@nemith There is [“how to build without ‘bundled’ dependencies”](https://github.com/neovim/neovim/wiki/Building-Neovim#how-to-build-without-bundled-dependencies) subsection. I always use this variant and apparently somebody copied the command I was using without understanding why arguments are there.

In this case you do not touch .deps at all. I actually did `touch .deps` to create a regular file so that any call like `mkdir .deps` if I happen to accidentally run top-level Makefile will fail.
