### ISSUE TITLE
remove() with {end} does not return removed items

### ISSUE THREAD

**Issue by cohama** [neovim/neovim#6521]
- `nvim --version`: NVIM v0.2.0-1305-g58d2ce9bd
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/config -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/packerbuild-1000/neovim-git/neovim-git/src/neovim-git/build/include
Compiled by cohama@grape

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently? yes
- Operating system/version: Arch Linux
- Terminal name/version: LilyTerm 0.9.9.4
- `$TERM`: xterm

### Actual behaviour
In neovim,
```vim
echo remove([1,2,3,4,5], 2, 3)
" => []
```

### Expected behaviour
Vim behaves
```vim
echo remove([1,2,3,4,5], 2, 3)
" => [3, 4]
```

**Comment by justinmk** [comment]
> Vim (version: ) behaves differently? yes

which vim version exactly?

**Comment by AlexMasterov** [comment]
@justinmk 

Windows 10 (15063)
`nvim --version`: 
* NVIM v0.2.0-1304-g45b5ebea
* NVIM v0.2.0-1307-gc70ab1a2
```viml
echo remove([1,2,3,4,5], 2, 3)
" => []
```

**Comment by jamessan** [comment]
I can reproduce on Linux with NVIM v0.2.0-1307-gc70ab1a2 using a Release/RelWithDebInfo build with gcc. The Debug build works fine as does clang across Release, Debug, and RelWithDebInfo.

```
$ gcc --version
gcc (Debian 6.3.0-12) 6.3.0 20170406
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by justinmk** [comment]
Can't repro with `gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)` and `RelWithDebInfo`. @jamessan if you go back to c35420558bed (before #5119) does it still occur?

**Comment by jamessan** [comment]
> @jamessan if you go back to c354205 (before #5119) does it still occur?

Nope.

**Comment by jbradaric** [comment]
The following change somehow fixes the problem (using `gcc version 6.3.1 20170306 (GCC)`). But this code should be equivalent to the old code.

```
diff --git a/src/nvim/eval.c b/src/nvim/eval.c
index 0663e19b..bd4bc277 100644
--- a/src/nvim/eval.c
+++ b/src/nvim/eval.c
@@ -13265,7 +13265,8 @@ static void f_remove(typval_T *argvars, typval_T *rettv, FunPtr
fptr)
             emsgf(_(e_invrange));
           } else {
             tv_list_remove_items(l, item, item2);
-            l = tv_list_alloc_ret(rettv);
+            tv_list_alloc_ret(rettv);
+            l = rettv->vval.v_list;
             l->lv_first = item;
             l->lv_last = item2;
             item->li_prev = NULL;
```

**Comment by ZyX-I** [comment]
@jbradaric I am wondering, what if you remove `FUNC_ATTR_MALLOC` from `tv_list_alloc_ret` instead? The latest GCC documentation now clarifies WTF this attribute means (AFAIR it was initially very vague, so I used it for many functions just based on “this function returns an allocated memory” criteria): https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-malloc-function-attribute. FUNC_ATTR_MALLOC usage now needs to be revised: in this case returned storage breaks both “the pointer P returned by the function cannot alias any other pointer valid when the function returns” (gc_first_list) and “moreover no pointers to valid objects occur in any storage addressed by P” (l->lv_used_prev). `tv_list_alloc` and `tv_dict_alloc` are also not correct.

**Comment by jbradaric** [comment]
@ZyX-I Removing `FUNC_ATTR_MALLOC` from `tv_list_alloc_ret` fixes the problem.

**Comment by ZyX-I** [comment]
Can’t find where it was vague (web.archive.org shows basically the same description at May 2015). Maybe I just read that not thoroughly enough.

**Comment by jbradaric** [comment]
@ZyX-I There might be some functions other than `tv_list_alloc` and `tv_dict_alloc` which shouldn't use `FUNC_ATTR_MALLOC`.

**Comment by ZyX-I** [comment]
@jbradaric I have checked all 70 found occurrences of FUNC_ATTR_MALLOC. Hope I have not missed some case: #6528.
