### ISSUE TITLE
seting 'guicursor' does not take effect

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#6522]
- `nvim --version`: 0.2.0-977
- Vim (version: ) behaves differently? yes
- Operating system/version: all
- Terminal name/version: all
- `$TERM`: xterm-256color

### Actual behaviour
For example, `set guicursor=a:blinkon0`, the cursor still blinks.
Especially, I want to hide the cursor, `set guicursor=a:xxx`, but the command hasn't any effect, while the cursor will disappear in Vim.

### Expected behaviour
After `set guicursor=a:blinkon0`, the cursor does not blink.
After `set guicursor=a:xxx`, the cursor disappears.

### Steps to reproduce using `nvim -u NORC`
As described above.

```
nvim -u NORC

```

**Comment by justinmk** [comment]
That's an old version.

**Comment by Yggdroot** [comment]
I don't know what do you mean, v0.2.0-1305-g58d2ce9 also has this issue.

**Comment by Yggdroot** [comment]
0.2.0-977 is my version compiled about 4 days ago, I thought it is the latest version. You said it is older, so I recompiled a latest version and checked the issue again, it still exists.
```
./build/bin/nvim -u NONE -c 'set guicursor=n:block,i:ver25' -c 'set guicursor=a:blinkon0'
```
and 
```
./build/bin/nvim -u NONE -c 'set guicursor=n:block,i:ver25'
:set guicursor=a:blinkon0
```
do not work for me either.

I tried `nvim -u NONE`, then run command `:verb set guicursor`,  it shows `   guicursor=`.

**Comment by justinmk** [comment]
Is your cursor blinking before nvim starts?

> Operating system/version: all
> Terminal name/version: all

It can't be that you tested "all" systems and terminals since it works for many people.

**Comment by justinmk** [comment]
> 0.2.0-977 is my version compiled about 4 days ago

That version is weeks old, not 4 days.

**Comment by AlexMasterov** [comment]
@justinmk
My cursor is always black. Seting `guicursor` also does has no effect.

**Build:** 0.2.0-1304-g45b5ebea (GUI)
**OS:** Windows 10 (15063)

**Comment by Yggdroot** [comment]
The cursor blinks always, before and after setting the option.
I tested it on windows and linux, but I did not test it on Mac os, maybe it's not right to say `all`.

**Comment by justinmk** [comment]
> The cursor blinks always, before and after setting the option.

Even _before_ starting nvim? Please, in the future, be more precise in your comments. We've wasted a lot of time going back and forth because your comments are vague.

It sounds like your terminal is set to blink its cursor, but the term codes used by nvim aren't working. That means either your terminal doesn't support changing the cursor behavior, OR we aren't using the correct term codes for your terminal. So what are the correct term codes to change the cursor behavior in your terminal?

**Comment by Yggdroot** [comment]
I mean: 
1, `nvim -u NONE` , after entering, the cursor blinks.
2, before I run command `:set guicursor=a:blinkon0`, the cursor blinks.
3, after  `:set guicursor=a:blinkon0`, the cursor still blinks.
I never said `before starting nvim`.
I'll close this issue.

**Comment by justinmk** [comment]
> I never said before starting nvim.

Right. I asked specifically about it. But still didn't get a direct answer.

**Comment by macthecadillac** [comment]
I have the exact same issue.

`nvim --version`: NVIM v0.2.0
Vim (version: ) behaves differently? yes
Operating system/version: Debian 9
Terminal name/version: Konsole 16.12.0
`$TERM`: xterm-256color

It is the released version, not some development version (I triple checked). Also, my terminal cursor does not blink before I launch Neovim but it does after I launched then closed Neovim. Apart from `set guicursor=a:blinkon0` having no effect on stopping the cursor from blinking, it seems any `guicursor` setting will automatically trigger blinking. From my observation, the only way that would stop the cursor from blinking is to `set guicursor=`.

Thanks.

**Comment by justinmk** [comment]
@macthecadillac Does it happen with `nvim -u NORC` ? What about terminals other than Konsole?

**Comment by macthecadillac** [comment]
In Konsole, with `nvim -u NORC` the cursor blinks in normal mode and the cursor of the terminal itself starts blinking after Neovim was run once. For comparison, I installed XFCE terminal and tried it and the same thing doesn't happen (no normal mode blinking, the terminal cursor doesn't blink after quitting Neovim), so it seems to be a Konsole specific problem.

Thanks

**Comment by justinmk** [comment]
nvim -u NORC +'set guicursor='

In konsole ?

**Comment by macthecadillac** [comment]
It still blinks (tested in a fresh session so the cursor didn't blink before Neovim was launched). Only that now the cursor doesn't change shape in insert mode.

**Comment by butla** [comment]
(For future people looking here) I also couldn't disable blinking in Konsole (KDE's terminal emulator), but found a workaround in #6665. Now waiting for neovim 0.2.1.
