### ISSUE TITLE
 Indentation of the curly braces not working after setting hi PhpParent

### ISSUE THREAD

**Issue by marekkon** [neovim/neovim#6529]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently? Yes (hearsay, I don't use Vim)
- Operating system/version: Arch
- Terminal name/version: st (git)
- `$TERM`: st-256color

### Problem description and steps
Is this neovim bug:
[description](https://github.com/2072/PHP-Indenting-for-VIm/issues/52)

**Comment by marekkon** [comment]
Can anyone look at it? I do not see this at any milestone, and this thing is really annoying.

**Comment by justinmk** [comment]
Are you still on 0.1.7 ...?

**Comment by marekkon** [comment]
I'm on nvim 0.2.0.
Installed vim (8.0.987) same problem even with original php.vim files.

**Comment by justinmk** [comment]
> Installed vim (8.0.987) same problem even with original php.vim files.

Not sure what that means. Vim has the same problem? Or, you copied the vim php.vim files to nvim's runtime, and nvim still has the problem? That doesn't sound right.

**Comment by marekkon** [comment]
I have not tested this in vim before, but vim has the same problem.

**Comment by chrisbra** [comment]
please give a reproducible example, start with `vim -u NONE -N`

**Comment by marekkon** [comment]
1. `vim -u NONE -N`
2. `filetype indent on`
3. `syntax enable`
4. `set ignorecase`
5. `colorscheme test`
6. open php file

The most important condition is that colorscheme must be set before `set filetype=php` or before vim/neovim sets it automatically.
Without `ignorecase` braces are aligned but shifted one tab to the right, regardless of the type of indentation, eg.:
```php
function test()
    {
    }
```

Content of the colorscheme:
```vim
hi clear
let g:colors_name = "test"
hi PhpParent        guifg=#ffffff
```

After some additional testing I found out that if I comment out lines 790-792 from `/usr/share/vim/vim80/indent/php.vim` this error disappears.

Same with neovim.

**Comment by jamessan** [comment]
This is an issue with the indent script.  Continue the discussion there.  When it's fixed, it will propagate to vim and neovim.
