### ISSUE TITLE
jobstop not killing processes with SIGKILL

### ISSUE THREAD

**Issue by w0rp** [neovim/neovim#6530]
- `nvim --version`: 0.1.7
- Operating system/version: Linux Mint 17.3
- Terminal name/version: Konsole 2.14.2
- `$TERM`: xterm

### Actual behaviour

Calling `jobstop()` on a process which does not respond to SIGTERM will not later send SIGKILL, per `:help jobstop()`.

### Expected behaviour

`jobstop()` should kill the process with effectively `kill -9` after 2 seconds of waiting, in the background.

### Additional Information

I am not certain if this is happening on all machines, or on specific machines, etc. I started getting a few users of my plugin ALE reporting issues with processes hanging around when they are running NeoVim on Mac OSX, and I'm pretty certain `jobstop()` is being called with the job ID. Vim 8 users of the plugin don't seem to be having the same issues. After some experimenting, I was finally able to put together a simple Vim script for reproducing the bug, as far as I'm aware.

I'll create this issue, and see if others can reproduce the same bug. If there is no bug, and there's something or other I can do in my plugin to fix this instead, then I'll be just as happy.

### Steps to reproduce using `nvim -u NORC`

Run these lines of VimL.

```vim
" Run a command which doesn't respond to SIGTERM, and kill it right away.
call jobstop(jobstart('/bin/bash -c ''trap true SIGTERM; sleep 20000000000000'''))
" Wait longer than the 2 second timer for calling SIGKILL
sleep 3
" A PID will be printed here.
echo system('pgrep -f ''sleep 20000000000000''')
```

**Comment by justinmk** [comment]
@w0rp Thanks for the repro, that will help a lot.

**Comment by mhinz** [comment]
The SIGKILL kills the `bash` process, but not `sleep` because that's a child process.

**Comment by w0rp** [comment]
Maybe that's the bug then. Killing the process should kill the child processes, or there should be some way of doing that.

**Comment by justinmk** [comment]
@w0rp In Vim what `job_stop()` invocation are you using? In Vim, happens if you do `job_stop({job}, "kill")` ?

I think the problem is we send the signal to the process, not its group. Vim sends to the process group (see `mch_stop_job()`. On Windows it iterates all processes... `terminate_all()`).

In `children_kill_cb` we iterate "watched children" but I wonder if that really is doing what it implies. `loop->children` is never magically filled with children AFAICT.

**Comment by w0rp** [comment]
In Vim 8, running `job_stop(job, 'kill')` will kill the process and its children.

```vim
call job_stop(
\    job_start(['/bin/bash', '-c', 'trap true SIGTERM; sleep 20000000000000']),
\    'kill'
\)
" Nothing will be printed here, unless you have something running already.
echo system('pgrep -af ''^sleep 20000000000000''')
```

I had to change the pgrep regex slightly, as it was matching the command generated by Vim 8's `system` function itself. (`prep -af ...` prints the actual sleep command in NeoVim for me.) I also had to pass the arguments in a `List` to get it to behave more like NeoVim in this case. (My plugin does basically this just for Vim 8.)

One thing I noticed here is that `job_stop()` in Vim without the `'kill'` argument will actually kill both processes here, but results will vary for other long running commands, like compilers.

**Comment by mhinz** [comment]
Since libuv doesn't seem (https://github.com/libuv/libuv/pull/836) to provide a proper way to handle child processes, I guess we should copy Vim's approach.

For Unix, this works:

```diff
diff --git i/src/nvim/event/process.c w/src/nvim/event/process.c
index 4429a65f9..2b284c68a 100644
--- i/src/nvim/event/process.c
+++ w/src/nvim/event/process.c
@@ -266,0 +267,2 @@ static void children_kill_cb(uv_timer_t *handle)
+    int pid = -getpgid(proc->pid);
+
@@ -268,2 +270,2 @@ static void children_kill_cb(uv_timer_t *handle)
-      ILOG("Sending SIGTERM to pid %d", proc->pid);
-      uv_kill(proc->pid, SIGTERM);
+      ILOG("Sending SIGTERM to pid %d", pid);
+      uv_kill(pid, SIGTERM);
@@ -272,2 +274,2 @@ static void children_kill_cb(uv_timer_t *handle)
-      ILOG("Sending SIGKILL to pid %d", proc->pid);
-      uv_kill(proc->pid, SIGKILL);
+      ILOG("Sending SIGKILL to pid %d", pid);
+      uv_kill(pid, SIGKILL);
```

And for Windows.. well, `terminate_all()`. :>

**Comment by oni-link** [comment]
@mhinz, do we change the process group for jobs so that it is different from nvim's process group? Otherwise this would also kill nvim.

**Comment by NickeZ** [comment]
@oni-link According to alexchricton in this issue you should do that yes https://github.com/rust-lang/cargo/issues/3950

**Comment by justinmk** [comment]
FWIW the win32 API also appears to have the concept of a process group:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684863(v=vs.85).aspx

though it looks like the only time libuv sets the CREATE_NEW_PROCESS_GROUP flag is for UV_PROCESS_DETACHED:

https://github.com/libuv/libuv/blob/87df1448a48fb64c2b9ebe37e3344f7e5b81dd88/src/win/process.c#L1074

perhaps there is a way to modify the process group after we `uv_spawn` it, or maybe there is an option we can pass to `uv_spawn()` ?

**Comment by jonhoo** [comment]
On UNIX it is certainly necessary to kill the entire process group (which has to be separate from nvim's), otherwise detached children will not also be killed. As @NickeZ referred to above (rust-lang/cargo#3950), this is important for builder tools that spawn a number of separate build processes, but does not relay signals to them (I'm only currently aware of this being the case for Rust's `cargo`, but I'm sure there are others). This is currently a major issue for both neovim syntastic clones (neomake/neomake#1216 and w0rp/ale#380), so landing a fix to this would be really nice!

**Comment by Earnestly** [comment]
Consider sending `HUP` to the process leader.  This is normally how you handle things in shell scripting from a `trap` to terminate all children (e.g. `kill -s HUP 0`).  Probably not as reliable as you'd like it though.

**Comment by mhinz** [comment]
To make it clear: the code I posted above works; at least on macOS. I haven't tested for other OS.

To make it clear: the [diff posted above](https://github.com/neovim/neovim/issues/6530#issuecomment-294323685) works as expected on macOS.

It takes the negated PID of the job's PID and kills the job and all its children. So, at least on macOS, the job _does_ create a new process group.

**Comment by Earnestly** [comment]
In the hope this might help with https://github.com/neomake/neomake/issues/1704 I applied this patch (slightly modified against master, see below), but while this patch is the "Right Thing" to do regardless, it didn't make any difference.

```diff
diff --git a/src/nvim/event/process.c b/src/nvim/event/process.c
index 8371d3cd4..6a016f745 100644
--- a/src/nvim/event/process.c
+++ b/src/nvim/event/process.c
@@ -263,6 +263,7 @@ static void children_kill_cb(uv_timer_t *handle)
 {
   Loop *loop = handle->loop->data;
   uint64_t now = os_hrtime();
+  int pid = -getpgid(proc->pid);
 
   kl_iter(WatcherPtr, loop->children, current) {
     Process *proc = (*current)->data;
@@ -275,9 +276,8 @@ static void children_kill_cb(uv_timer_t *handle)
       int sig = proc->type == kProcessTypePty && elapsed < KILL_TIMEOUT_MS * 2
                     ? SIGTERM
                     : SIGKILL;
-      ILOG("Sending %s to pid %d", sig == SIGTERM ? "SIGTERM" : "SIGKILL",
-           proc->pid);
-      uv_kill(proc->pid, sig);
+      ILOG("Sending %s to pid %d", sig == SIGTERM ? "SIGTERM" : "SIGKILL", pid);
+      uv_kill(pid, sig);
     }
   }
 }
```

**Comment by Shougo** [comment]
Why the issue is suspended?

* neovim can use terminate_all() from Vim source code for Windows.

* https://github.com/neovim/neovim/issues/6530#issuecomment-294323685  patch exists.

Related issue? https://github.com/neovim/neovim/issues/7691

**Comment by miuirussia** [comment]
Any news?

**Comment by mhinz** [comment]
This needs a bit more work than meets the eye.

A normal `jobstart()` doesn't create a new process group. Not good. In the meantime we got `jobstart(..., {'detach': 1})` which _does_ create a new process group. Good.

But in the best case we would want it to work for both cases. Unfortunately I don't see a way to create a new process group with libuv without also creating a detached process.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8107 should fix this.
