### ISSUE TITLE
fails to compile on arm6v

### ISSUE THREAD

**Issue by 257** [neovim/neovim#6542]
- `nvim --version`: git, HEAD
- Vim (version: ) behaves differently? VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 14 2017 17:37:41)
- Operating system/version: Linux rootpiorg.raspberrypiarmv6j_hardfp 4.9.16-gentoo #10 SMP PREEMPT Mon Apr 17 11:40:31 EDT 2017 armv7l Intel(R) Core(TM) i3-2130 CPU @ 3.40GHz GNU/Linux 
- Terminal name/version: rxvt-unicode-256color
- `$TERM`: rxvt-unicode-256color

### Actual behaviour
fails to compile neovim; see logs here:
https://gist.github.com/257/9f332dece2e506b8ecdca98b45459686
### Expected behaviour
compile neovim

**Comment by ZyX-I** [comment]
Log shows luajit crashing. Given that we are not using ffi (with which crashing could be our bug) in this case this is not our bug. And still, does it compile with lua?

**Comment by jamessan** [comment]
As @ZyX-I mentioned on gitter, this is because LuaJit crashed.

```
/bin/sh: line 1: 13757 Segmentation fault      (core dumped) /usr/bin/luajit /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/scripts/gendeclarations.lua /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto/eval.c.generated.h /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include/eval.h.generated.h /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto/eval.i
```

You can use Lua instead.  If you can still reproduce this with the latest LuaJit from their Git repo, I would suggest reporting the issue there (although they'll want a reduced test case).

**Comment by 257** [comment]
[`with just lua`](https://gist.github.com/1c2708e690c1c101595d1e8a967c59f9
); still failing

**Comment by jamessan** [comment]
No, it's still using luajit.

```
-- Checking Lua interpreter /usr/bin/luajit
-- Using the Lua interpreter /usr/bin/luajit.
...
/bin/sh: line 1: 31383 Segmentation fault      (core dumped) /usr/bin/luajit /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/scripts/gendeclarations.lua /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto/eval.c.generated.h /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include/eval.h.generated.h /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto/eval.i
```

**Comment by ZyX-I** [comment]
@257 How did you make sure that this is just lua?

@jamessan In gitter I asked him to replace luajit executable with lua executable because it is easier then change the ebuild to use lua (especially since I am not sure how to do this). So this log does not mean he is (not) using lua, in both cases it would be /usr/bin/luajit.

**Comment by 257** [comment]
there is a USE flag for that which seems to be ignored for some reason.

**Comment by ZyX-I** [comment]
@257 It only alters what package depends on, not what lua build system will use. Ebuild needed to supply -DLUA_PRG to change that, given what luajit USE is for it would be perfectly legal and correct.

**Comment by 257** [comment]
i unmerged luajit manuall and  i guess an ``emerge --changed-use --update --deep neovim`` is needed for portage to pick the USE changes up; in any case it now seems tobe building fine.

`-- Checking Lua interpreter /usr/bin/lua
`
`
-- Using the Lua interpreter /usr/bin/lua.
`
