### ISSUE TITLE
Cannot not yank large amounts of text to the system clipboard.

### ISSUE THREAD

**Issue by CrashyBang** [neovim/neovim#6545]
- `nvim --version`:  NVIM v0.2.0-dev
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 16.10
- Terminal name/version: MATE Terminal 1.16.0
- `$TERM`: screen

### Actual behaviour

Hey folks having some really weird issues with the system clipboard and nvim, I have checked `:help clipboard` I have `xsel` installed (and have also tried `xclip`).

If I copy a small amount (1 line) of text using `yy` I can:
1) Use `p` to paste in nvim
2) Use `i` then `ctrl`+`shift`+`v` to paste in nvim
3) Paste using `ctrl`+`v` in GUI app

If I copy a large amount of text (130 lines) using visual mode and `y` I can:
1) Use `p` to paste in nvim
2) Use `i` then `ctrl`+`shift`+`v` to paste in nvim
3) **NOT** Paste using `ctrl`+`v` in GUI app

I have also tried using `"+p` to copy directly to the `+` register but I have experienced excatly the same issue.

I have also tried with a minimal init.vim i.e just set `clipboard+=unnamedplus` and no difference, there does seem to be a delay when I try to `ctrl`+`v` with the large amount of text but then after a few seconds whatever I am trying to paste into becomes responsive again and nothing has been pasted. I wondered if it was something to do with `xsel` but the exact same thing happened with `xclip`

### Expected behaviour

When using `set clipboard+=unnamedplus` I expect `y` (yanking) to copy to system clipboard.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

Wasn't sure what to do here?

**Comment by justinmk** [comment]
> NOT Paste using ctrl+v in GUI app

By "GUI app" you mean some other app? If `ctrl+shift+v` works in nvim, that suggests clipboard has the data. Can you check xsel or xclip on the command line?

    xsel -o -b

or 

     xclip -o -selection clipboard

**Comment by riteme** [comment]
I have some similar experiences on **Neovim 0.3.1** on **Ubuntu 18.04**. I cannot copy *>= 4k characters* in one line via `V"+y` in nvim and paste them into **Visual Studio Code 1.30.2** and text fields on web pages in **Google Chrome 71.0.3578.98**. It seems that 4k is the boundary on my computer since copying & pasting 3999 characters is OK.

**Comment by justinmk** [comment]
@riteme  please post the "clipboard" section of `:checkhealth` . Also see if 0.3.4 appimage fixes the issue: https://github.com/neovim/neovim/releases/tag/v0.3.4

**Comment by riteme** [comment]
"clipboard" section of `:checkhealth` in nvim 0.3.1 (from launchpad) and nvim 0.3.1 appimage:

```
## Clipboard (optional)
  - OK: Clipboard tool found: xsel
```

"clipboard" section of `:checkhealth` in nvim 0.3.4 appimage:

```
## Clipboard (optional)
  - OK: Clipboard tool found: xclip
```

Finally nvim 0.3.4 appimage fixes this issue. Thanks a lot!

**Comment by justinmk** [comment]
Must be a problem with `xsel`. Nvim 0.3.2 defaults to `xclip`.

**Comment by mhinz** [comment]
Old xsel? https://github.com/kfish/xsel/issues/13
