### ISSUE TITLE
setting custom leader with set pastetoggle causes problems when typing in Insert mode

### ISSUE THREAD

**Issue by turnspike** [neovim/neovim#6551]
- `nvim --version`:
NVIM v0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/build/config -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/src -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-_yeThP/neovim-0.1.7ubuntu1+git201704191303+3344+23~ubuntu16.04.1/build/include
Compiled by root@lgw01-52

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently?
Yes
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.

- Operating system/version: Ubuntu 16.04.2 LTS
- Terminal name/version: 
zsh 5.1.1 (x86_64-ubuntu-linux-gnu) 
also confirmed on /bin/bash --version: GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)

- `$TERM`: xterm-256color

### Actual behaviour
Only the following on startup, no plugins or other customizations loaded:

_~/.config/nvim/init.vim:_
```
let mapleader = "\<space>"
set pastetoggle=<leader>t
```

While in Insert mode, pressing the space bar rapidly will show a <20> in the bottom right of the screen. Cursor position and keys may be swallowed/missed. When plugins etc are also loaded the problem becomes more pronounced. 
 
### Expected behaviour
While in Insert mode, pressing the space bar rapidly inserts spaces.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
These two lines are sufficient to reproduce:

```
let mapleader = "\<space>"
set pastetoggle=<leader>t
```

I have also confirmed the problem under Termux/Android/ARM:
NVIM v0.2.0-dev
Build Type: MiniSizeRel

Simply removing _"set pastetoggle"_ seems to resolve. **So easy workaround at least.** :)

If I try let mapleader = "," then type "," rapidly in Insert mode I also get "," echoed in the bottom right of screen. My standard vimrc is massive with loads of plugins, and just commenting out "set pastetoggle" is enough to fix this issue. Please note again that I tested this error with the simple two line config and no plugins, on two separate systems.

This problem has only happened in the last week or so and I do update nvim frequently.

**Comment by justinmk** [comment]
`:set showcmd` is the default since a few weeks ago. Perhaps you want `:set noshowcmd`.

**Comment by turnspike** [comment]
thanks for looking at this, just to clarify, this behavior is preventing whatever the leader key is set to from being typed. So if my leader is <space>, I can no longer reliably type any spaces in Insert mode. I'll test later to see if :set noshowcmd helps.

**Comment by justinmk** [comment]
That's how pastetoggle works. Same thing happens in vim.

Don't use pastetoggle.

**Comment by evmorov** [comment]
@turnspike, thank you so much! I've spent so much time trying to catch this bug and find workaround.
