### ISSUE TITLE
ERROR Couldn't open USR_LOG_FILE

### ISSUE THREAD

**Issue by JasonB579** [neovim/neovim#6556]
- `nvim --version`:
```
NVIM v0.2.0-1400-gf0c1201
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by jason@jason-XPS-15-9550

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

- Operating system/version: Ubuntu 16.04
- Terminal name/version: GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)

### Actual behaviour
I recently reinstalled Ubuntu and with that I rebuilt Neovim. I'm getting this odd error now whenever I open any file using nvim:
> 2017/04/20 13:45:24 ERROR 4145/open_log_file:124: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
>2017/04/20 13:45:24 INFO  4145/tui_get_stty_erase:1093: stty/termios:erase=
>2017/04/20 13:45:24 ERROR 4145/open_log_file:124: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
>2017/04/20 13:45:24 INFO  4145/tui_tk_ti_getstr:1110: libtermkey:kbs=
>2017/04/20 13:45:24 ERROR 4145/open_log_file:124: Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
>2017/04/20 13:45:24 INFO  4145/tui_tk_ti_getstr:1115: libtermkey:kdch1=[3~

Neovim still runs without any problem, but I just don't feel terribly comfortable having an error which occurs every time I open a file. Any help with this would be greatly appreciated!

### Expected behaviour
Run without error output.

### Steps to reproduce using `nvim -u NORC`
Not sure for this...

**Comment by justinmk** [comment]
Either USR_LOG_FILE env var is set to an invalid path, or `~/.nvimlog` is not writable. 

You can avoid this entirely by not building a Debug build type (which is the default when building from source), instead choose RelWithDebInfo:

```
rm -rf build
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
```

**Comment by bfredl** [comment]
Not sure if related, but in #6539 I also sometimes get this error, but only on OS X during the TUI tests.

**Comment by JasonB579** [comment]
Permissions were the issue! I didn't solve it by rebuilding (I may take care of that later), I just used `sudo chown <user> ~/.nvimlog`. It's probably just a short-term solution, but It'll do for now. Thanks!
