### ISSUE TITLE
nvim_set_option() should update ":verbose set ..."

### ISSUE THREAD

**Issue by firedev** [neovim/neovim#6561]
- `nvim --version`: NVIM v0.2.0-84-g7c513d64
- Vim (version: ) behaves differently? I would think so
- Operating system/version: OS X
- Terminal name/version: iTerm
- `$TERM`: screen-256colors

I have this issue when `noexpandtab` is turns on by itself after a while. Tried to describe it here because I am not 100% sure this is a legit bug: 

https://vi.stackexchange.com/questions/12178/expandtab-noexpandtab-toggles-by-itself-in-neovim

For a long time, I have disregarded this thinking it is some plugin acting up. But then a friend who uses fairly minimalistic Neovim setup shared his frustration for the same behaviour.

It goes like this — you go about your work day and at some point in time it starts using tabs instead of spaces in all files. So I have to issue

```
:set et
:retab
```
To get the current file back on track, but the problem is the new `noexpandtab` setting becomes  "global" after that, so in the end I just restart Neovim. It might, of course, be a faulty plugin, but if this is actually a bug then more people should have been experiencing it.

**Comment by justinmk** [comment]
Are you using sleuth!

**Comment by justinmk** [comment]
What does 

    : verbose set expandtab?

report after the issue happens?

**Comment by firedev** [comment]
Hi, no. It might be some plugin but I can't pinpoint which one. And that happens quite rare, like once a week or something considering I am coding all day every day.

Thank you for the suggestion, will try next time. Wasn't sure how to trace it.

**Comment by firedev** [comment]
Common plugins between our configs:

```
AndrewRadev/splitjoin.vim
AndrewRadev/vim-eco
Shougo/deoplete.nvim
Xuyuanp/nerdtree-git-plugin
airblade/vim-gitgutter
junegunn/fzf
kana/vim-textobj-user
kchmck/vim-coffee-script
mtscout6/vim-cjsx
mxw/vim-jsx
scrooloose/nerdtree
tpope/vim-abolish
tpope/vim-dispatch
tpope/vim-fugitive
tpope/vim-repeat
tpope/vim-surround
vim-airline/vim-airline
vim-airline/vim-airline-themes
vim-ruby/vim-ruby
```

**Comment by justinmk** [comment]
Did you grep for "expandtab" and `\bet\b` in your plugins?

**Comment by firedev** [comment]
Thanks for more suggestion, after filtering for `et` the list can be narrowed down to the following:

```
vim-gitgutter
nerdtree
vim-dispatch
vim-fugitive
vim-repeat
vim-surround
vim-airline
vim-airline-themes
vim-ruby
```

**Comment by jaymiejones86** [comment]
@firedev I have been having the same issues for quite some time, with Ruby files.
I have been reloading the NeoVim config instead and that makes it work but I need to do it for each split I have, which I eventually do what you do and restart NeoVim.

I have not been able to narrow it down very well either, so far I have not been able to reproduce, it seems quite random, which I am sure it is not.

**Comment by firedev** [comment]
Thanks, @jaymiejones86 I know this is the real thing, hoping communal experience might help to pinpoint it.

@justinmk `:verbose set et?` outputs only `noexpandtab`

**Comment by ilesm** [comment]
I have this problem too. I don't have any useful repro info yet. I've switched from MacVim to NeoVim. This never happened with MacVim (i.e. I had `expandtab` set in my .vimrc and it never got unset.) I haven't made any NeoVim-specific changes to my .vimrc files yet. I've just figured out that somehow, sometimes, `noexpandtab` is getting set in NeoVim.

**Comment by justinmk** [comment]
@ilesm What version of MacVim? The built-in runtime files cover a lot, and they are updated regularly. 

Which filetype does it tend to occur in?

**Comment by firedev** [comment]
@justinmk It can be any type of file, but since I mostly edit Ruby or JS so for me the answer would be Ruby or JS files. But now saying that I should add that it's been a while since I had this issue. I think what changed is I have replaced `neomake` with `ale`, `deoplete` with `nvim-completion-manager` and `easymotion` with your `vim-sneak`. Maybe this is something in those plugins. There are some other differences but these I think are the ones where I have removed plugins.

**Comment by jaymiejones86** [comment]
@firedev slightly off topic, any reason for replacing `neomake` with `ale`, `deoplete`?

**Comment by firedev** [comment]
@jaymiejones86 `ale` is linting while I am editing and fixes simple stuff when I save. Not saying that you can't do this with `neomake`, but it just worked. `nvim-completion-manager` is something I wanted to try, if that makes any difference since I am struggling setting up proper code intel and completion so I was wondering if it could help. And `vim-sneak` just looked more lightweight but I do not seem to be using it and wasn't really using `easymotion` either.

**Comment by justinmk** [comment]
@firedev in https://github.com/neovim/neovim/issues/6561#issuecomment-297959347 you reported that `:verb set et?` doesn't return a modifying script, I wonder if this is because a remote plugin (deoplete) changed the value. 

We need to enhance `nvim_{buf,win,}_set_option()` so that there is some indication of which channel/client changed the option, if it was not a VimL script. (Also looks like `:luafile` does not update the `:verbose` result)

**Comment by firedev** [comment]
@justinmk Nice, let me put `deoplete` back to see if it is going to happen again. 

@ilesm Do you use any of the plugins I've mentioned?

**Comment by DestyNova** [comment]
@firedev did you figure out what was setting `noexpandtab`? I'm seeing this too, recently, and thought it might be the vim-orgmode plugin... but I couldn't find where it might be setting the variable.

I'm running neovim-0.2.2ubuntu2+git201804022019-60e96a4-f2f288d.

Plugins I'm running:
```
danro/rename.vim
eagletmt/neco-ghc
easymotion/vim-easymotion
edkolev/tmuxline.vim
elixir-lang/vim-elixir
elmcast/elm-vim
freeo/vim-kalisi
itchyny/lightline.vim
jakwings/vim-pony
jceb/vim-orgmode
junegunn/fzf
junegunn/vim-easy-align
metakirby5/codi.vim
Shougo/deoplete.nvim
slashmili/alchemist.vim
tpope/vim-abolish
tpope/vim-fugitive
tpope/vim-speeddating
zchee/deoplete-jedi
```

**Comment by justinmk** [comment]
@DestyNova the issue is https://github.com/neovim/neovim/issues/7994

**Comment by DestyNova** [comment]
Thanks @justinmk, that seems right -- I've noticed `<Paste>` get appended occasionally when pasting from the `+` register or shift-insert, in insert mode.

**Comment by mellery451** [comment]
sorry to pile on here, but does `:verbose set [option]?` work at _all_ for anybody? I get nothing for any of the standard options (many of which I at least explicitly set in my .rc), so I'm confused about this functionality. I've just updated to 273d2cd for the latest change above, but still nothing reported by `:verbose set sw?` for instance. The reason I care is that I'm having a similar issue with `shiftwidth` getting mysteriously changed in the middle of an editing session and I have no idea the cause.
