### ISSUE TITLE
Crash in ex mode

### ISSUE THREAD

**Issue by sander2** [neovim/neovim#6568]
Just something I came across when fuzzing Neovim. Should this be fixed? It's not likely ever to be accidentally stumbled upon.. It's caused by a failing assertion in `getdigits()` in `charset.c`.

### Actual behaviour
Neovim crashses

### Expected behaviour
Neovim produces an error message

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
Q9999999999999999999<enter>
```

**Comment by jamessan** [comment]
See https://github.com/neovim/neovim/issues/5555

**Comment by sander2** [comment]
Ah. Sorry for the duplicate. Closing this.
