### ISSUE TITLE
Lua "stdlib" (standard library)

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6580]
We may want to include some small, robust, lua modules as part of the Nvim runtime. (Keeping in mind: where possible it is preferable to have Nvim be the "standard library", i.e. wrap internal vim/libuv/API functions.)

Possible candidates:

- http://leafo.net/lapis/reference/utilities.html
- https://github.com/torch/paths
- https://github.com/jaawerth/fennel-nvim
- https://github.com/bakpakin/Fennel (pretty print, repl)
- https://github.com/luafun/luafun util lib
- https://github.com/rxi/lume util lib
- howl editor: https://github.com/howl-editor/howl/tree/master/lib/howl/util
- similar to penlight? https://github.com/luapower/luapower-all
- webserver: https://github.com/lpereira/lwan

Related: https://github.com/neovim/neovim/pull/8677
Related: https://github.com/neovim/neovim/pull/7123

### Nvim-Lua guidelines

- https://github.com/neovim/neovim/pull/8677#issuecomment-402102325
- https://github.com/neovim/neovim/pull/8677#issuecomment-403737119

### Lua doctsrings

- ~~Looks like [ldoc](https://github.com/stevedonovan/ldoc) is the least-terrible solution. (It's not actively maintained but it's still used by penlight, and we only need it for the [parsed info](https://stevedonovan.github.io/ldoc/manual/doc.md.html#Internal_Data_Representation), not the other fancy features).~~ Resolved by https://github.com/neovim/neovim/pull/9740

### Lua "module" policy

- Most functions should live directly on `vim.`, not in child modules. We own the `vim.*` module; the only "forbidden" names are those claimed by legacy `if_lua`:
   ```
   $ vim
   :lua for k,v in pairs(vim) do print(k) end
   buffer
   open
   window
   lastline
   firstline
   type
   line
   eval
   dict
   beep
   list
   command
   ```
- Any child modules (`vim.*)` that we _do_ introduce should not be named `vim.helpers`, but something meaningful. And they should be rare.

Lua code can live in one of two places: 

1. The runtime (`runtime/lua/vim/`), thus not available with `nvim -u NONE`. 
    - This is for "nice to have, but non-essential" features. E.g. the `inspect` and `lpeg` modules live here.
2. Compiled-into `nvim` itself (`src/nvim/lua/`).
    - **Guideline:** "If there's doubt, put it in the runtime".

**Comment by bfredl** [comment]
We can also have `.lua` files in the source that get's compiled into the nvim binary.

**Comment by prabirshrestha** [comment]
I would also love to have some of the modules built into lua.

- json parse/stringify
- async http/socket support. (useful for many features like github issues/username autocomplete, npm package.json autocomplete and anything that can talk to http. Might also need some crypto apis to save access tokens)
- globs/wildcards file path
- file change notifications - https://groups.google.com/d/msg/vim_dev/oubHkRbdQW0/TZYUUQftAgAJ - should be available in vimscript too
- url/querystring parser and encoder/decoder

**Comment by justinmk** [comment]
> json parse/stringify

What's the advantage vs the existing `json_encode/decode`?

> async http/socket support.

We ship ssl-enabled `curl` with Neovim on windows. Does that not solve most use-cases?

**Comment by ZyX-I** [comment]
@prabirshrestha json handling is in VimL. globs also are.

@bfredl #4411 makes one such file built-in; intended for compatibility layer, but currently only containing `return {}` and a comment. It is compiled into a long `const char[]` blob.

**Comment by bfredl** [comment]
it might make sense to expose jobs/sockets in lua so they can use them directly without conversion via typvals. Actually it might not be that complicated: add a `kCallbackLua` variant to `Callback`. the jobs code can check for the lua kind and call the lua callback directly. Other usecases can rely on `callback_call` to do the conversion.

> What's the advantage vs the existing json_encode/decode?

The advantage could be not requiring double conversion and less memory allocation. But if it actually matters in a realistic usecase I don't know.

**Comment by fmoralesc** [comment]
What about lpeg? It would be useful quite generally for handling data and text parsing.

**Comment by tjdevries** [comment]
Do we have access to things like: https://github.com/luvit/luv in #4411 ?

That might be nice to have.

**Comment by tjdevries** [comment]
(it seems like we do after just trying that out, at least from building it on that branch. Cool!)

**Comment by bfredl** [comment]
Letting Lua use the uv main loop via luv might be interesting. But note it will not be safe to call arbitrary nvim functions in a uv callback directly. Instead we need something like `nvim.async_call` in the python-client.

**Comment by prabirshrestha** [comment]
My feature requests were based on limited knowledge of writing vim lua plugins so some of these feature might already be there or I'm still scratching my head on how to accomplish it.

@justinmk / @ZyX-I Can you post an example of how to use json_encode/decode in lua. I want the api to be simple as something like ```local json = vim.json_encode(var1)``` so I don't need to use `eval`. If it is already there you can ignore this request.

@justinmk curl.exe is bundled but then all vim plugin writers would need to write a wrapper for it duplicating the effort. I would want to do something like this ```http.get('address.com', callback)``` so within few minutes I can be achieve my goals instead of trying to understand the curl parameters and making sure it correctly escapes the parameters in all major OS.
https://github.com/mattn/webapi-vim/blob/e76f2da9a8f292a999a95ae688534f76c2dca9bd/autoload/webapi/http.vim#L125-L280

@ZyX-I globs/wildcards file path: might be update the lua docs on how to use this given that it is a very common scenario. Can I use this without eval directly on `vim` object?

@tjdevries exposing entire luv would be great but not sure if this would be too much.

**Comment by ZyX-I** [comment]
@prabirshrestha Currently you need to use `vim.api.nvim_call_function('funcname', {args})`.

**Comment by tjdevries** [comment]
Maybe something like this: https://github.com/gvvaughan/typecheck

Not sure if there are better examples, but could be nice to have some idea about expected types of certain functions.

**Comment by jdonaldson** [comment]
Really glad to see luv getting some attention.  It's not completely documented, but it's not terribly difficult to sort out the method usage.  Hopefully more people using it will increase the amount of helpful information available.  I've been opening up some PR in libuv for related functionality that I think would be useful:

https://github.com/libuv/libuv/issues/1315
https://github.com/libuv/libuv/issues/1198
https://github.com/libuv/libuv/issues/1197

If all those get into libuv, and then into luv, I think it will end up simplifying a lot of the maintenance required for neovim and the lua runtime.

**Comment by tjdevries** [comment]
how can we `require` `vim.api.*` in lua source files?

**Comment by ZyX-I** [comment]
@tjdevries `vim` is a global in my PR, it is always there. This is because I intended to add compatibility layer and in Vim `vim` is not `require()`d.

**Comment by tjdevries** [comment]
after `:luafile ...` what is the best way to call a function defined in lua from within vim?

**Comment by ZyX-I** [comment]
@tjdevries `luaeval('func(_A)', arg)` I think.

**Comment by ZyX-I** [comment]
Or `luaeval('func(unpack(_A))`, [arg1, …])`.

**Comment by tjdevries** [comment]
is there any way to do something like registering a function, similar to a `lua-host`?

**Comment by ZyX-I** [comment]
@tjdevries PR intended to provide a basis for VimL lua compatibility code without too much churn (i.e. without defining complicated objects in C) on my side and a basis for extending editor functionality in lua on @justinmk side, less on mine (though my PR where most code was taken from needed lua for this and not compatibility). So far it only contains C Vim compatibility layer (i.e. all Ex commands and functions Vim has) and API bindings (that is what should allow “defining complicated objects without using C”).

**Comment by tjdevries** [comment]
I think having json support would be really nice in lua. I've been working on writing the lsp client for neovim, and I'd prefer if I could write as much of it as possible with lua that doesn't depend on API functions (like creating the message request), as it makes calling it much easier to call from other lua functions. Also, the testing is a lot simpler as well.

**Comment by tjdevries** [comment]
I'd also like to suggest lpeg so people could use it to use lpeg to do syntax highlighting more quickly. At least it seems that that would be possible.

**Comment by aktau** [comment]
I'd like to second the inclusion of lpeg, although I noticed that lpeg gets compiled into a shared library here:

```
$ locate --regex 'lpeg.*\.so'
/home/aktau/github/neovim/neovim-profile-tags/.deps/usr/lib/lua/5.1/lpeg.so
```

It's already part of the build stack because of that ugly C header parse thing I made all that time ago (*shamecube*).

Though maybe what we really need is some sort of dependency manager so people can get their own modules...

**Comment by aktau** [comment]
**UPDATE**: I've not been very clever, the docs even mention an example with lpeg:

```
$ nvim -c ':help :luado'
							*:luado*
:[range]luado {body}	Execute Lua function "function (line, linenr) {body}
			end" for each line in the [range], with the function
			argument being set to the text of each line in turn,
			without a trailing <EOL>, and the current line number.
			If the value returned by the function is a string it
			becomes the text of the line in the current turn. The
			default for [range] is the whole file: "1,$".

Examples:
>
	:luado return string.format("%s\t%d", line:reverse(), #line)

	:lua require"lpeg"
	:lua -- balanced parenthesis grammar:
	:lua bp = lpeg.P{ "(" * ((1 - lpeg.S"()") + lpeg.V(1))^0 * ")" }
	:luado if bp:match(line) then return "-->\t" .. line end
```

And this works, I just tested it. I'm not sure where Neovim is getting the lpeg shared library. I only see it in my `.deps` folder.

There's a way to test. But the result is different depending on whether I supply the ex command to nvim from the command line or in a running instance. From a regular nvim instance:

```
:lua print(package.searchpath('lpeg', package.cpath)) 
/home/aktau/github/neovim/neovim/.deps/usr/lib/lua/5.1/lpeg.so 

:lua print(package.cpath)
./?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/github/neovim/neovim/.deps/usr/lib/lua/5.1/?.so;/usr/local/lib/
lua/5.1/loadall.so  
```

I'm unsure why the .deps folder is in my lua path... Any idea @ZyX-I?

Sometimes it doesn't seem to work for me.

```
$  nvim -c "lua print(package.searchpath('lpeg', package.cpath))"
nil                                                                                                                            
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/home/aktau/.luarocks/lib/lua/5.1/lpeg.so'                                                         
^Ino file './lpeg.so'                                                                                                          
^Ino file '/usr/local/lib/lua/5.1/lpeg.so'                                                                                     
^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/lpeg.so'                                                                          
^Ino file '/usr/lib/lua/5.1/lpeg.so'                                                                                           
^Ino file '/usr/local/lib/lua/5.1/loadall.so' 

$ nvim -c "lua print(package.cpath)"
/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/us
r/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/l
ocal/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;/usr/loca
l/lib/lua/5.1/?.so;/home/aktau/.luarocks/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so nil
```

**EDIT**: Turns out, there was (is?) something wrong with my terminal session there. I'm betting that has something to do with my le/lj aliases which export a custom lua path (https://github.com/aktau/dotfiles/blob/master/.zshrc-extra), which stays active even after invoking the command.

Which leads to some pertinent questions: 

1. **should the users' `$LUA_(C)PATH` be respected**?
2. The LPeg example in the docs won't work if the user doesn't have LPeg installed. Maybe we should be showing what one can do with something that doesn't depend on external libraries, _or_ include LPeg by default.
3. Add something to the docs explaining how users can make sure their own Lua libraries are found.

**Comment by ZyX-I** [comment]
It would be nice to have something like Python has regarding &runtimepath handling: it gets modules from `$RTP_DIR/python{2,3,x}`.

**Comment by ZyX-I** [comment]
Tried to mess up with `setmetatable(package, mymeta)` where `mymeta` defines `__index` which dynamically overrides `package.path` and `package.cpath` and it failed. Could only hook setting `&runtimepath` then because trying to create own loader for `package.loaders` needs replicating

> the searcher for module foo will try to open the files ./foo.so, ./foo.dll, and /usr/local/foo/init.so, in that order. Once it finds a C library, this searcher first uses a dynamic link facility to link the application with the library. Then it tries to find a C function inside the library to be used as the loader. The name of this C function is the string "luaopen_" concatenated with a copy of the module name where each dot is replaced by an underscore. Moreover, if the module name has a hyphen, its prefix up to (and including) the first hyphen is removed. For instance, if the module name is a.v1-b.c, the function name will be luaopen_b_c.

provided only `package.loadlib` which is not fun and does not look “clean”.

**Comment by ZyX-I** [comment]
Ref #6789.

**Comment by luzhlon** [comment]
Hi, I think there should be a simple implementation for neovim's api.

This is an example written by me. 

https://github.com/luzhlon/.vim/tree/dev/lua/nvim
https://github.com/luzhlon/.vim/blob/dev/lua/nvim.lua

**Comment by wbthomason** [comment]
Something like https://github.com/torch/paths or https://github.com/moteus/lua-path would be extremely useful to bundle.

**Comment by wbthomason** [comment]
Has there been any movement on this issue? If not, what would it take to promote this out of `todo`? I think adding a standard library for Lua would make writing native Lua plugins much more tenable/a much stronger feature of Neovim.

**Comment by justinmk** [comment]
@wbthomason : @KillTheMule and I both have related PRs. It's high on the priority list. Moved to 0.4.

**Comment by wbthomason** [comment]
@justinmk: Ah, wonderful! I'll look there to see if/how I can help. Thanks!

**Comment by justinmk** [comment]
## Resolution/Summary

- https://github.com/neovim/neovim/pull/9301 gives the "shape" for adding new Nvim-Lua stdlib functions.
    - [luafun](https://github.com/luafun/luafun) and [lume](https://github.com/rxi/lume) have a lot of goodies that we should incorporate. Help wanted.
    - With https://github.com/neovim/neovim/pull/9740 we have documentation generated from docstrings on each Lua function.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
