### ISSUE TITLE
Extra character "ff" appeared after ':' when enter ":" in normal mode

### ISSUE THREAD

**Issue by douglasyin** [neovim/neovim#6584]
- `nvim --version`:
```
NVIM v0.2.0-1451-g7f6d3d3
Build type: Debug
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -
...
...
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

```
- Vim (version: ) behaves differently?

 vim version 7.4.8056 is OK.

- Operating system/version:

OSX 10.12.4

- Terminal name/version:

iterm2 Build 3.0.15

- `$TERM`:

xterm-256color

### Actual behaviour
string "ff" displayed on cursor when I enter insert mode, or enter ":" in normal mode
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
NORC mode is OK

screenshots:

<img width="260" alt="2017-04-25 13 23 35" src="https://cloud.githubusercontent.com/assets/6890111/25370091/f1583a86-29ba-11e7-870a-74753b5e1396.png">

<img width="335" alt="2017-04-25 13 24 04" src="https://cloud.githubusercontent.com/assets/6890111/25370103/0a708c76-29bb-11e7-832b-2f858c794dfb.png">

**I found this happend after commit c703d0529b3c4f6485d6ce6f37033d4658356b05**

```
commit c703d0529b3c4f6485d6ce6f37033d4658356b05
Author: Justin M. Keyes <justinkz@gmail.com>
Date:   Sat Apr 22 18:19:37 2017 +0200

    'guicursor': iTerm: Set cursor color.

    iTerm uses proprietary escape codes to set cursor color.
    https://www.iterm2.com/documentation-escape-codes.html
```

**Comment by kassio** [comment]
I'm having a similar problem, but I wasn't able to replicate this `NORC`.

**Comment by mhinz** [comment]
@douglasyin @kassio 

Does it happen inside and outside of tmux? (Just in case you're using it.)

**Comment by justinmk** [comment]
Seems like a iterm bug. It works on an old version.

**Comment by kassio** [comment]
My setup is:
* iterm: Build 3.0.15
* neovim: HEAD (updated daily)
```
$ nvim -v
NVIM v0.2.0-1462-ga0acb2e1
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170425-80637-t5ueq5/build/config -I/tmp/neovim-20170425-80637-t5ueq5/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170425-80637-t5ueq5/build/src/nvim/auto -I/tmp/neovim-20170425-80637-t5ueq5/build/include
Compiled by kborges@13592-storage

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-a0acb2e/share/nvim"
```
* **no tmux**
* my [nvimfiles](https://github.com/kassio/nvimfiles)

![error](https://cloud.githubusercontent.com/assets/120483/25391871/24066fde-29cf-11e7-9236-d858b77c9888.gif)

**Comment by mhinz** [comment]
@kassio https://github.com/kassio/nvimfiles/blob/master/init.vim#L101

The `nCursor` highlight group doesn't exist in your case, right? (`:hi nCursor`)

Try just `Cursor` (default highlight group) instead.

**Comment by kassio** [comment]
@mhinz I was just writing about that, I think you're right, when I set a value for `nCursor` (the highlight group I use on `guicursor`), the ghost chars doesn't seem to appear. Although, the cursor colors are not working 100 percent:

* minimal vimrc:
```viml
set rtp-=/Users/kborges/.config/nvim
set rtp-=/Users/kborges/.config/nvim/after

hi! Cursor ctermfg=1 ctermbg=1 guifg=#FF0000 guibg=#FF0000
set guicursor=a:block-Cursor/Cursor-blinkon0
```
![nvim-cursor](https://cloud.githubusercontent.com/assets/120483/25392537/cc67af02-29d0-11e7-9286-dd4c751c5954.gif)

However it works when the cursor is not a block:
![nvim-cursor2](https://cloud.githubusercontent.com/assets/120483/25392623/1385caf4-29d1-11e7-8747-61f4b482df50.gif)

**Comment by mhinz** [comment]
Okay, thanks for the info. We have an idea where it happens now. We're investigating!

**Comment by jamessan** [comment]
#6585 should avoid the artifacts when an invalid highlight group is specified in `'guicursor'`.

Getting iTerm to set the color regardless of shape is another endeavor, which I'll let someone else handle. :)

**Comment by mhinz** [comment]
@kassio You will also have to put `set termguicolors` in your minimal vimrc. (Currently undocumented in `:h 'gcr'`.)

**Comment by renstrom** [comment]
I'm still seeing this with running the latest v0.2.3dev (cca407b43e62d5e1abdfc59ae47b0e24eacc5807).

```vim
set rtp+=~/.vim/plugged/gruvbox

set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
\,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
\,sm:block-blinkwait175-blinkoff150-blinkon175

set termguicolors
set background=dark
colorscheme gruvbox
```

Any of these actions will fix the problem:

- Disable cursor blinking
- Disable `termguicolors`
- Comment out [this](https://github.com/morhetz/gruvbox/blob/cb4e7a5643f7d2dd40e694bcbd28c4b89b185e86/colors/gruvbox.vim#L558) line in the `colors/gruvbox.vim`:
  ```vim
  call s:HL('Cursor', s:none, s:none, s:inverse)
  ```
