### ISSUE TITLE
in remote UI, terminal cursor doesn't move in insert mode

### ISSUE THREAD

**Issue by dzhou121** [neovim/neovim#6601]
- `nvim --version`: NVIM v0.2.0-1470-g67552621
- Vim (version: ) behaves differently?
- Operating system/version: macOS
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Only happens in remote UI, TUI is fine. I can see the event 'cursor goto' to the same position after the screen redrawing is done. 

I guess this due to go to saved cursor position after redraw terminal even if it's the active buffer

https://github.com/neovim/neovim/blob/master/src/nvim/terminal.c#L1167

But I don't understand why this won't affect TUI.

**Comment by justinmk** [comment]
Hmm, didn't see that issue on nvim-qt remote UI. Can anyone report about other UIs?

**Comment by dzhou121** [comment]
It turns out to be a bug in my remote ui. Apologies.
