### ISSUE TITLE
Neovim doesn't fille whole terminal.

### ISSUE THREAD

**Issue by voider1** [neovim/neovim#6602]
- `nvim --version`: 0.1.7
- Vim (version: ) behaves differently?: No
- Operating system/version: MacOS Sierra
- Terminal name/version: iTerm 3.0.15
- `$TERM`: xterm-256color

### Actual behaviour
The left and right sides are not filled with Neovim.
### Expected behaviour
Neovim fills the whole terminal.

![image](https://cloud.githubusercontent.com/assets/6877671/25482015/2873f168-2b50-11e7-9ca7-95fac8e49897.png)

**Comment by justinmk** [comment]
Search closed issues. This isn't something nvim has control over.
