### ISSUE TITLE
Allow remote UIs to manage system clipboards

### ISSUE THREAD

**Issue by realh** [neovim/neovim#6603]
I think it would be a good idea if remote UIs could act as the clipboard provider for nvim. That should work much better than the current system when nvim and client are running on separate hosts. If it managed all clipboards, not just * and +, it would also allow clients that manage multiple windows with separate nvim instances to share the clipboards between those instances without having to sync shada.

It might be possible to do this already by overriding the existing provider-clipboard, but I know very little about VimL etc and don't know exactly how that could be done. But I think it would require an extra script to be installed in nvim's runtime, so it would be more practical to build it into the API.

**Comment by justinmk** [comment]
> If it managed all clipboards, not just * and +, 

By "clipboards" you mean "registers" here.

> it would also allow clients that manage multiple windows with separate nvim instances to share the clipboards between those instances without having to sync shada. ... build it into the API.

In general, I think a very good direction for Nvim to drive towards is general "p2p"-like capabilities, which allows sharing all kinds of data. Registers will be part of that. 

p2p is nominally covered by https://github.com/neovim/neovim/issues/1180 though the discussion is a bit out of date.

The first step towards p2p-like capabilities, before anything more seamless, is for nvim to be able to discover other nvims (like `--serverlist`, but more seamless and less centralized). 

> It might be possible to do this already by overriding the existing provider-clipboard, 

https://github.com/neovim/neovim/pull/6030
