### ISSUE TITLE
:p, <sfile>, and mangled windows paths

### ISSUE THREAD

**Issue by PhDyellow** [neovim/neovim#6605]
- `nvim --version`: v0.2.0-1468-g68733a80
- Vim (version: ) behaves differently? 
- Operating system/version: Win10
- Terminal name/version: nvim-qt
- `$TERM`: NA

### Actual behaviour
When I attempt to use the :p file name modifier on a file in Windows to a path that is not a child of the current working directory, the returned filename is mangled.

I suspect this is related to issue [#2471 Windows: expand('%:p') returns inconsistent slashes](https://github.com/neovim/neovim/issues/2471) 

Using the directory structure below and `:pwd` returning `D:\nvim_debug\dir3`, if I call 
`:echo  fnamemodify('..\dir2\file2.vim', ':p')`
I get 
`D:\nvim_debug\dir3\..dir2^Lile2.vim`

But if I start with a unix style string:
`:echo  fnamemodify('../dir2/file2.vim', ':p')`
 I get
`D:\nvim_debug\dir2\file2.vim`

This will only happen when the path has `..\`

The problem is that `expand('<sfile>')`, used by some plugins, provides a relative `..\` in the path.  

### Expected behaviour
The :p file name modifier should return the path with no relative separators.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
set up a directory structure like so:

D:\nvim-debug
 - dir1\[file1.vim](https://github.com/neovim/neovim/files/963249/file1.txt)
 - dir2\[file2.vim](https://github.com/neovim/neovim/files/963251/file2.txt)
 - dir3\

Start `nvim-qt.exe -- -u NORC`

`:cd` to dir3

`:so ..\dir1\file1.vim`

file1.vim sources file2.vim.

`:messages` will show the output, screenshot attached 
![messages](https://cloud.githubusercontent.com/assets/7740661/25510885/b0279342-2c06-11e7-93b5-924225594f34.png)

The problem only occurs when `:so ` uses relative paths.

**Comment by janlazo** [comment]
I can reproduce with `fnamemodify(bufname('%'), ':p')`, used in dirvish.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7349 may fix this
