### ISSUE TITLE
Notifying nvim when a UI gains or loses focus

### ISSUE THREAD

**Issue by realh** [neovim/neovim#6610]
- `nvim --version`:
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-wew7PE/neovim-0.1.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-wew7PE/neovim-0.1.7/build/config -I/build/neovim-wew7PE/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-wew7PE/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-wew7PE/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: 8.0.0197) behaves differently? No, same behaviour
- Operating system/version: Debian testing/unstable amd64
- Terminal name/version: N/A
- `$TERM`: N/A

### Actual behaviour
Bearing in mind your advice on reddit to use
`autocmd CursorHold,FocusGained,FocusLost * rshada|wshada`
I thought it would be a good idea for my GUI client to call `doauto FocusGained` and `doauto FocusLost` when appropriate, because I couldn't find another way in the API for a GUI to notify nvim of these events. But if a user hasn't set up any autocmds for those events they'll see the message "No matching autocommands" in its status line.

### Expected behaviour
This isn't exactly unexpected, but the message is unwanted in this case. Is there a better way for the GUI to notify nvim of focus events? If not, I suppose I could use a more complicated command that parses the result of `au FocusGained` to test whether any autocommands are defined for those events first, but that seems a bit cumbersome and hacky.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:doauto FocusGained
```

**Comment by mhinz** [comment]
```vim
if exists('#FocusGained')
  doautocmd FocusGained
endif
```

**Comment by jamessan** [comment]
Or

```vim
silent doautocmd FocusGained
```

**Comment by realh** [comment]
Thanks. They both look like good solutions, but I prefer the 'exists' one, just in case someone wants to use echo in their autocommands for debugging or something.

**Comment by justinmk** [comment]
This is currently the recommended approach, any request for better API mechanisms should start a new issue with some proposed design/API.
