### ISSUE TITLE
Error when building latest pull of neovim, using MinGW

### ISSUE THREAD

**Issue by andalou** [neovim/neovim#6617]
When building the latest pull of neovim on Windows 7 using MinGW I get:

```
[...]
[ 28%] Performing build step for 'msgpack'
[  8%] Building C object CMakeFiles/msgpackc.dir/src/objectc.c.obj
C:\home\caesar\neovim\build-deps\build\src\msgpack\src\objectc.c:1:0: error: -fP
IC ignored for target (all code is position independent) [-Werror]
 /*
 ^
cc1.exe: all warnings being treated as errors
CMakeFiles\msgpackc.dir\build.make:62: recipe for target 'CMakeFiles/msgpackc.dir/src/objectc.c.obj' failed
mingw32-make.exe[5]: *** [CMakeFiles/msgpackc.dir/src/objectc.c.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/msgpackc.dir/all' failed
mingw32-make.exe[4]: *** [CMakeFiles/msgpackc.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make.exe[3]: *** [all] Error 2
CMakeFiles\msgpack.dir\build.make:109: recipe for target 'build/src/msgpack-stam
p/msgpack-build' failed
mingw32-make[2]: *** [build/src/msgpack-stamp/msgpack-build] Error 2
CMakeFiles\Makefile2:274: recipe for target 'CMakeFiles/msgpack.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/msgpack.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

The command line I used is:
```
cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=C:/progs/nvim ..\third-party
```

Many thanks in advance,

Cesar

**Comment by justinmk** [comment]
It failed to build msgpack library. We didn't change anything there, perhaps try git bisect. Or delete deps and build directories and try again.

**Comment by justinmk** [comment]
Btw what steps did you follow to get a build environment on Windows? Are those written down somewhere? We need to add that to the wiki.

**Comment by jamessan** [comment]
> We didn't change anything there

Well, I did recently bump the msgpack-c version.

If you revert https://github.com/neovim/neovim/commit/d92add8a4b00d5e87fd367ae2656ac5ba87a8f06 and then `make distclean`, `make`, does it build?

**Comment by andalou** [comment]
To build under Windows I only followed the steps on:
https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msys2

Apparently it isn't possible anymore to build with MinGW under Windows!

The last time I managed to build neovim with MinGW was last year in October.

**Comment by justinmk** [comment]
Well, it clearly builds on appveyor :p

**Comment by justinmk** [comment]
Maybe https://github.com/neovim/neovim/pull/8084 helps. Closing this anyway, no followup.
