### ISSUE TITLE
systemlist(['doesnotexist']) does not return a list

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6626]
`:echo string(systemlist(['doesnotexist']))` displays `''`.

It should return an list instead probably?!

Vim returns `['zsh:1: command not found: doesnotexist']` in this case, when using `:echo systemlist('doesnotexist')` - since it does not support passing in a list.
Neovim behaves the same (when using a string instead of a list).

Related commit: c8d5e9230 (jobstart(:( Return -1 if cmd is not executable. #5671)
(Neovim 0.1.7 throws `E902`)

- `nvim --version`: v0.2.0-1507-g0df1b6655

**Comment by ZyX-I** [comment]
> but :echo string(systemlist(['doesnotexist'])) == '' displays 0.

You are comparing string `''''''` to string `''`. Of course, this is not going to work: remove `string()`. And given that it may return a list, use `is#`: `systemlist(['doesnotexist']) is# ''`.

As for the Vim return: we are not using any shell in case of the list, this the whole point of this form. So it should not return errors from zsh. I would suggest that `systemlist()` should return an error in case of not executable like it used to, but systemlist() documentation states that empty string is exactly what you should get: https://github.com/neovim/neovim/blob/master/runtime/doc/eval.txt#L7426.

**Comment by blueyed** [comment]
> You are comparing string '''''' to string ''

Yeah, noticed that (and removed it) - sorry for the confusion.

**Comment by justinmk** [comment]
> Vim returns ['zsh:1: command not found: doesnotexist'] in this case, when using :echo `systemlist('doesnotexist')`

- Behavior of `systemlist('doesnotexist')` is the same as Vim.
- As @ZyX-I mentioned, `systemlist([...])` doesn't exist in Vim. It is intended to be a synchronous alternative to `jobstart([...])`, and behaves as such.

> It should return an list instead probably?!

When would this be helpful? You must check `v:shell_error` before doing anything with the result anyways, right? Else you could be processing an error message instead of an expected output.

> I would suggest that systemlist() should raise an error in case of not executable like it used to

That would revert https://github.com/neovim/neovim/issues/5465. One should always check `v:shell_error`, it doesn't help to have to wrap the calls in try-catch or `:silent!`.

**Comment by blueyed** [comment]
Thanks, let's close this issue then.

**Comment by ZyX-I** [comment]
@justinmk #5465 talks about jobstart, not about systemlist. It is not impossible to one throw error and the other not.

**Comment by blueyed** [comment]
Re-opening.

1. One difference between Vim (or rather using `systemlist` with a string) and Neovim (when using a list) is that the former sets `v:shell_error` to 127 ("not found") with `systemlist('notfound')`, where the latter sets it to `-1` (`systemlist(['notfound'])`).
I think the latter should use `127` also for "command not found".

2. And then `systemlist()` supporting a list should be documented after all.

**Comment by ZyX-I** [comment]
@blueyed Check on Windows, I very much doubt that is going to return 127. Vim is passing shell exit code as-is, it may be not consistent even on linux: if I set shell to `/usr/bin/rcsh` `v:shell_error` would be 1 and not 127 (rcsh is a port of Plan 9 rc shell, renamed from rc to rcsh to avoid name conflict with OpenRC).

**Comment by ZyX-I** [comment]
@blueyed And it is documented, `systemlist()` says that it is like `system()` and `system()` has necessary documentation.

**Comment by ZyX-I** [comment]
So I am closing as function behaves like it should be with current documentation, but opening #6631 because I do not think that documented behaviour is actually valid.
