### ISSUE TITLE
system*([]) and jobstart() are not throwing errors on error conditions

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6631]
This is after #6626: it is closed, but I no longer think that behavior from documentation is valid.

The points:

1. `systemlist(['xxxnonexistentcommandxxx']) is# ''` describes error condition and may be used in conjunction with -1 v:shell_error, but the documentation does not say you can actually do so: `:h v:shell_error` only says “is *often* used when the command could not be executed”. *Often*, not always. And no description of what “could not be executed” exactly means.
2. When jobstart/systemlist error out immediately they point at exact position where bug is located, and if script author is following best practices (some of which include abort in function definition) that would not do unneeded things and propagate further. When functions return something on error and it is not handled then you get bugs somewhere else which do not describe exactly what happened (How “E900: Invalid job id” somewhere else may be considered *better* then E806 right out there? Or plugin silently not doing anything at all because callbacks are not run and author did not check for -1?). Additionally for systemlist() that would be something about using string where list is expected (like E686 from writefile), just … strings do support indexing, `len()` and do not error out when index is out of range, so the amount of places where unhandled string return would immediately error out is limited.
3. Neither `system*([])` nor `jobstart()` are compatible with Vim, so it would not be a problem.
4. Unlike e.g. `grep foo file` returning 1 it is very much unlikely that not found command indicates a normal operation and not some problem: if author intended to check for executable, most likely he used `executable()`, EAFP approach is not very popular with VimL.

**Comment by justinmk** [comment]
The current behavior is intentional and was requested in https://github.com/neovim/neovim/issues/5465. 

If plugin authors want robust logic, they can check the jobid and `v:shell_error`.

**Comment by ZyX-I** [comment]
@justinmk The #5465 pointed out that behaviour *does not match documentation*. I do not see @blueyed requesting to fix this in any particular way in that issue, only pointed out at mismatch. Requiring to check jobid and v:shell_error without any help from the Vim can highly be “robust”, I have expanded that in 2.

ADT with `Result { OK(resurt), Error(error) }` returns or forcing checked exceptions work the best here, but we only have regular errors and exceptions.

**Comment by justinmk** [comment]
I'm OK with either approach.

**Comment by justinmk** [comment]
Fixed by #11234 b3686b1597ea202de464df72a88fb5c76fd1b814
