### ISSUE TITLE
dictwatcheradd(b:, 'changedtick', ...)

### ISSUE THREAD

**Issue by realh** [neovim/neovim#6635]
A `TextChanged` or `TextChangedI` event is fired every time the text is modified at all, so I'm concerned it might be a little inefficient to subscribe to it over RPC. What I want is an event that only triggers when `changedtick` changes from 0 to NZ or vice-versa, so I can use it to show an indicator in the GUI.

I tried `autocmd OptionSet modified ...` but that only seems to work when the option is changed explicitly with `:set`, not if it's changed internally as a result of the text being edited.

**Comment by justinmk** [comment]
Seems that `dictwatcheradd()` doesn't work for `b:changedtick` (@ZyX-I should it?):

```vim
function! OnDictChanged(d,k,z)
echomsg string(a:k) string(a:z)
endfunction
call dictwatcheradd(b:, 'changedtick', 'OnDictChanged')
```

@realh But for your specific case, you can just check `b:changedtick` in the autocmd before calling rpcnotify():

    au TextChanged * if b:changedtick < 2 | call rpcnotify(...) | endif

**Comment by ZyX-I** [comment]
@justinmk Not the way it is implemented, would need to call `tv_dict_watcher_notify` explicitly in `buf_set_changedtick` if you want to.

**Comment by ZyX-I** [comment]
By the way, tv_dict_watcher_notify is doing allocating, setting values and freeing regardless of whether it is needed (there are some watchers to notify) or not. Wondering how this impacts performance.

**Comment by ZyX-I** [comment]
I see, function is simply not called if there are no watchers, so most of time this is not a problem.

**Comment by realh** [comment]
> `au TextChanged * if b:changedtick < 2 | call rpcnotify(...) | endif`

I tried that, and it doesn't seem to work. Is that what you meant with the stuff about dict_watcher, it means `au TextChanged` doesn't currently work?

**Comment by justinmk** [comment]
>  but the value of b:changedtick starts at 3 for the first notification (pressing 'o' in an empty buffer), and 

What `b:changedtick` considers a "tick" is mostly an implementation detail. Try `if b:changedtick < 4` instead, or whatever.

> continues to increase even when I press 'u'.

That's how changedtick works.

**Comment by bfredl** [comment]
> . Try if b:changedtick < 4 instead, or whatever.

I guess it could vary across change types. Better to set a flag whether the notification was already sent or not.

**Comment by realh** [comment]
>> but the value of b:changedtick starts at 3 for the first notification (pressing 'o' in an empty buffer), and
> What b:changedtick considers a "tick" is mostly an implementation detail. Try if b:changedtick < 4 instead, or whatever.

>> continues to increase even when I press 'u'.
> That's how changedtick works.

OK, I misunderstood it, I thought it was for counting the buffer modifications and would therefore decrement on undo. As it is, there doesn't seem to be an easy way for me to detect when a buffer's modified flag changes so I can display a '+' in the title bar etc.

**Comment by justinmk** [comment]
Just add another check for `&modified`

**Comment by realh** [comment]
The trouble with that is I'd either have to have an RPC round trip on every TextChanged event or set up a considerably more complicated autocmd with a variable that stores the previous value of b:modified. I guess the latter isn't too onerous, but I'm not done with the vimscript n00b questions, sorry. `modified` is buffer-local, so if I try to refer to that and my variable that tracks it as `&l:modified` and `b:old_mod` in the body of my autocmd, will those expressions always refer to the buffer on which the event was triggered, or to the buffer which was current at the time the autocmd was run?

**Comment by justinmk** [comment]
What exactly do you want? You said you need to be notified when the buffer is modified. But you also need to be notified when it is not modified. If you don't want an RPC on each input, a timer would make more sense.

**Comment by realh** [comment]
I want to know when the modified state changes. I'd like to have my GUI windows show some indication of modified buffers, in addition to the '+' in the status bar that nvim draws. So it needs to know both when the flag is set and when it's cleared (which can be caused by undos as well as saving). It will also make it easier to handle the user trying to close a window, because the GUI will be able to check its internal list of buffer state instead of having to send a series of asynchronous requests.

**Comment by realh** [comment]
This seems to work (generating the autocmd from C++):

    s << "autocmd " << nvim_.get_augroup()
        << " TextChanged,TextChangedI,BufReadPost,FileReadPost,FileWritePost * "
        << "if !exists('b:old_mod') || b:old_mod != &modified"
        << "|let b:old_mod = &modified"
        << "|call rpcnotify("
        << nvim_.get_channel_id()
        << ", 'modified', str2nr(expand('<abuf>')), &modified)"
        << "|endif";
