### ISSUE TITLE
Nothing happens when clicking and dragging over text

### ISSUE THREAD

**Issue by macthecadillac** [neovim/neovim#6639]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? N/A
- Operating system/version: Debian 9
- Terminal name/version: Konsole 16.12.0
- `$TERM`: xterm-256color

### Actual behaviour
1. When clicking and dragging over text in normal mode, nothing happens.
2. When clicking on an out-of-focus split, nothing happens.

### Expected behaviour
At least from Neovim v0.1.7, I expect the following to happen:
1. When clicking and dragging over text in normal mode, the editor switches from normal  to visual mode and highlights the text that my mouse cursor dragged over
2. When clicking on an out-of-focus split, the editor switches focus to the split I clicked on

### Steps to reproduce using `nvim -u NORC`
The above description should have been self-explanatory enough for the reproduction of the issue.

Thanks.

**Comment by fmoralesc** [comment]
We reverted the `mouse`setting  default, you can enable it with
``` vim
set mouse=a
```

**Comment by justinmk** [comment]
Thanks for the report. As @fmoralesc explained we have temporarily reverted the mouse=a default until we can make it behave better for all users.

**Comment by macthecadillac** [comment]
Thanks. I think perhaps you should also consider putting that in Following HEAD or somewhere so users like me won't be surprised.
