### ISSUE TITLE
nvim.exe starts headless-mode by default on Windows, 0.20 64bit

### ISSUE THREAD

**Issue by costincaraivan** [neovim/neovim#6640]
- `nvim --version`: NVIM v0.2.1-4-g9847be58
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: Windows 7 Enterprise 6.1.7601 Service Pack 1 Build 7601
- Terminal name/version: conhost.exe
- `$TERM`: empty

### Actual behaviour

\> nvim.exe
Nvim headless-mode started.
Listening on:
        \\.\pipe\nvim-12432-0
Press CTRL+C to exit.
^C

### Expected behaviour

\> nvim.exe
[nvim opens a tab with an empty buffer.]

### Steps to reproduce using `nvim -u NORC`

nvim -u NORC

**Comment by equalsraf** [comment]
The TUI is still not working in Windows, thats why it starts in headless mode by default. See https://github.com/neovim/neovim/pull/6315.
