### ISSUE TITLE
Tilde + space yields space instead of tilde using United States-International kb layout

### ISSUE THREAD

**Issue by rafguns** [neovim/neovim#6642]
- `nvim --version`: NVIM v0.2.1-4-g9847be58
- Vim (version: 7.4.965) behaves differently? yes
- Operating system/version: Windows 8.1
- Terminal name/version: nvim-qt
- `$TERM`: NA

### Actual behaviour

My keyboard layout is [United States-International](https://support.microsoft.com/en-us/help/306560/how-to-use-the-united-states-international-keyboard-layout-in-windows-7,-in-windows-vista,-and-in-windows-xp). When I press, e.g., `~` followed by space bar, the output is a space.

The same behaviour exists for all keys that can be used to create international characters: APOSTROPHE ( ' ) key, QUOTATION MARK ( " ) key, ACCENT GRAVE ( ` ) key, TILDE ( ~ ) key, or ACCENT CIRCUMFLEX, also called the CARET key, ( ^ ) key. 

### Expected behaviour

The expected behaviour is that `~` followed by space bar yields a tilde as output.

The behaviour for other combinations is correct: `~` followed by `n` yields `ñ`, and `~` followed by `q`yields `~q`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

- Set your keyboard layout to United States-International.
- Start `nvim-qt.exe -- -u NORC`
- Press `i` to enter INSERT mode (not strictly necessary, happens in other modes as well)
- Press `~` followed by space bar.

**Comment by justinmk** [comment]
Does it happen in the TUI? Try the appveyor artifact from https://github.com/neovim/neovim/pull/6315

**Comment by rafguns** [comment]
I checked against [this build](https://ci.appveyor.com/project/neovim/neovim/build/13123/job/4jg5b983jri5ho5k/artifacts). The bug does not occur in the TUI, so I guess it is somehow related to `nvim-qt.exe`?

**Comment by justinmk** [comment]
Yes. Cc @equalsraf

**Comment by equalsraf** [comment]
Yes its an issue with nvim-qt, https://github.com/equalsraf/neovim-qt/issues/179#issuecomment-244522196, when handling dead keys.

**Comment by rafguns** [comment]
For what it's worth, pressing tilde twice gives me *two* tildes, same for other dead keys. So the current way to get one tilde is tilde - tilde - backspace.

**Comment by benutzerball** [comment]
I still have this problem on NVIM v0.2.1-25-g2e3b78d1, but only when running nvim-qt and not in a terminal.

**Comment by justinmk** [comment]
Covered in the nvim-qt project.

**Comment by mmmattos** [comment]
This problem persists in NVIM 0.4.4  running in `nvim-qt`.
Was it fixed in 2018? or is it still the same issue?

**Comment by Mupu** [comment]
I'm also still having the same issue on NVIM 0.5.0 nvim-qt

**Comment by EdwinWenink** [comment]
Same issue on NVIM 0.5.1 nvim-qt

**Comment by zeertzjq** [comment]
Isn't this tracked by <https://github.com/equalsraf/neovim-qt/issues/270>?

**Comment by andalou** [comment]
I'm still having the same issue on NVIM 0.8.0 nvim-qt
