### ISSUE TITLE
:[count] resize [arg] is undocumented and strange

### ISSUE THREAD

**Issue by edanaher** [neovim/neovim#6643]
- nvim version 0.1.7, checked source on github master

### Actual behaviour

Judging by the source and brief experiments, `:[count] resize [arg]` applies the resize to window `count`, but any relative resizes (e.g., `[count] resize +1`) resizes relative to the *current* window, not window `count`.

This is clear from the source of ex_resize in src/nvim/ex_docmd.c: if `eap->addres_count > 0`, `wp` is set to the appropriate window, but then if the argument starts with + or -, n is changed by `curwin->w_width` (or height), not `wp->w_width`.

Also, AFIACT, the [count] argument is completely undocumented in `:help resize`; the help only shows `:res[ize] -N` applying to the current window.

### Expected behaviour

When given a count, :resize should apply to window `count` as if it were run with that as the current window.  And this behavior should be documented in windows.txt

### Steps to reproduce using `nvim -u NORC`
This is a good way to see what's happening; simpler repros I've found are extremly confusing:
```
nvim -u NORC
:vsp
:sp
:resize +5
:3 wincmd w
:sp
:1 resize +1
:1 resize +2
:1 resize -2
:1 resize -1
```
Note that in the later resizes, window 1 is resized relative to window 3's size, not its own.  This makes sense, but it is extremely confusing if the windows are not next to each other; e.g., making window 3 a bit taller and then relative resizing window 2 makes no sense at all.

**Comment by glacambre** [comment]
This seems to be fixed on master:
- `X resize +2` will make window X 2 lines taller regardless of size of the current window.
- The documentation for `:h resize` mentions the count:
```
:{winnr}res[ize] [+-]N
		Like `:resize` above, but apply the size to window {winnr}
		instead of the current window.
```

So I'm going to close this issue :).
