### ISSUE TITLE
Crash after :h

### ISSUE THREAD

**Issue by poldie** [neovim/neovim#6648]
- `nvim --version`:  The windows v0.2.0 64 bit zip file
- Vim (version: ) behaves differently? n/a
- Operating system/version: Windows 7 enterprise build 7601 (64 bit, 8 core, 16 gb ram).
- Terminal name/version: n/a (occurs when launched from windows explorer or cmd prompt)
- `$TERM`: n/a

### Actual behaviour
"The Neovim process has crashed" and a retry box.  Retry might do nothing, or take you back into neovim.
### Expected behaviour
Not crashing.
### Steps to reproduce using `nvim -u NORC`
:h
:q 

do this a few times and it'll crash.  Once it's crashed you might not be able to run neovim again until you've tried 5 or 10 times.  It might crash on :h not :q.  The editor window might be tiny on the next run.

I see no log files.  The help doesn't suggest any way of enabling logging. There's nothing in the admin logs.  

I get exactly the same problem with a very new windows 10 vm (64 bit, on virtualbox, hosted on the same win 7 box).

I didn't have the VCRUNTIME140.dll in the path; i've copied it into neovim's bin folder; no different. Same problem with 32 and 64 bit neovim.  

```
nvim -u NORC

```

**Comment by ZyX-I** [comment]
@poldie Could it be run again immediately if you use `-i NONE`?

If yes, could you answer the following questions:

- What is ShaDa file contents during crashes and also right after the last crash at startup?
- Is behaviour reproducible if you use `-i new.shada` (if yes, better post contents of new.shada during crashing and right after the last crash at startup)?

If no, no need to bother, with `-i NONE` it should not be related to ShaDa. Not sure what other state may be preserved on Windows.

**Comment by poldie** [comment]
-i isn't a valid option for nvim-qt. It is for nvim. I'm unfamiliar with the interplay between these two exes and I haven't been running nvim before running nvim-qt.  Trying nvim first doesn't seem to make any difference.

**Comment by jamessan** [comment]
To pass options through to nvim, just include them after a `--`.  For example, `neovim-qt -- -i new.shada`.

**Comment by poldie** [comment]
nvim-qt -- -i NONE
makes no difference.

This problem has been reported in comments in the Hacker News article on neovim's v0.2.0 release:

https://news.ycombinator.com/item?id=14244586

**Comment by ZyX-I** [comment]
So the state due to which nvim-qt crashes is not in a ShaDa file.

**Comment by justinmk** [comment]
@poldie Can you try `nvim.exe -u NONE` (not `nvim-qt.exe`) from the artifact in [this build](https://ci.appveyor.com/project/neovim/neovim/build/13165) (after the build completes, in a few minutes).

**Comment by poldie** [comment]
@justinmk That does nothing.

**Comment by justinmk** [comment]
What in the world does "does nothing" mean?

**Comment by poldie** [comment]
@justinmk  What happens when you type REM in a dos prompt? Nothing.  I'm not sure how else to describe it.

**Comment by justinmk** [comment]
What does `chcp` command in the console report? And, is `C:\apps\Neovim\bin` writable?

**Comment by poldie** [comment]
C:\apps\Neovim\bin>chcp
Active code page: 850

The folder is writable.

**Comment by poldie** [comment]
I have Sophos antivirus on the win 7 machine.   But not on the win10 vm.   I can try on my home win 7 vm tonight which definitely has no anti-virus.

**Comment by smorks** [comment]
This seems related to #6646?

I tried running `nvim.exe -u NONE` from the build above, and i got the same thing, it just exited right away. I tried running it a bunch more times, and occasionally, it would actually bring up the UI. It seems almost random as to when it actually runs, and when it doesn't.

**Comment by justinmk** [comment]
Merging with #6646
