### ISSUE TITLE
viminfo file causes "E576: Failed to parse ShaDa file"

### ISSUE THREAD

**Issue by cookiengineer** [neovim/neovim#6652]
- `nvim --version`: 0.2.0
- Vim 8 behaves differently? Yes, works. (But that's expected, as viminfo file is different for neovim)
- Operating system/version: Arch Linux (up-to-date, non-testing)
- Terminal name/version: GNOME Terminal, (U)XTerm
- `$TERM`: xterm-256color

### Actual behaviour

When opening `nvim`, it will create a `viminfo` file; but it will keep saying that the file is broken. When closing all vim instances, manually removing all `viminfo` and `viminfo.tmp.*` files and starting nvim again, it will keep saying the same message.

```bash
nvim /opt/whatever/my/file.js
E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 3
```

However, the viminfo file is encoded with msgpack (at least it shows up broken and unreadable) and has the generator set to NVIM v0.2.0:

![screenshot of viminfo file](https://i.imgur.com/9ZEL3sf.png)

### Steps to reproduce using `nvim -u NORC`

Honestly I have no idea how to reproduce. Maybe use my [.vim](https://github.com/cookiengineer/.vim) to reproduce? I've tried to reproduce what setting and what plugin causes this, but I had no luck yet.

Is there a simple way to "enforce" neovim to simply always override the `viminfo` file without that annoying warning?

Starting `nvim -u NORC` works perfectly fine without issues.

**Comment by ZyX-I** [comment]
You must not use the same file for Vim and Neovim, Neovim no longer supports viminfo, using its own format. I think that the file is specified by your configuration setting `&viminfo` option (specifically appending something like `n/path/to/file` to it) somewhere.

**Comment by jamessan** [comment]
You have

```vim
set viminfo+=n~/.vim/viminfo
```

in your vim config.  Vim and nvim use incompatible formats, but nvim treats `'viminfo'` as a pass-thru for `'shada'`, so you're telling two different tools to use the same file.

You should change that part of your configuration to

```vim
if !has('nvim')
    set viminfo+=~/.vim/viminfo
endif
```

**Comment by cookiengineer** [comment]
@jamessan Thank you, that did the trick!

**Comment by jamessan** [comment]
Note that this issue has been discussed before.  You could have searched for `E576` to see previous discussions.
