### ISSUE TITLE
No neovim 0.2.x in ~neovim-ppa/+archive/ubuntu/unstable

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#6654]
For some reason, neovim is stuck at 0.1.7 in https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

**Comment by jamessan** [comment]
No, you're not.  The version number in the package is misleading.  It's built from the HEAD of the git repo, so it is 0.2.0 content.

**Comment by shmerl** [comment]
Ah, thanks for the clarification.
