### ISSUE TITLE
inconsistent path separator behavior with vim and neovim 

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#6657]
- `nvim --version`: v0.2.1-15-g08b23d08
- Vim (version: ) behaves differently? vim 8.0  1-594
- Operating system/version: win10
- Terminal name/version: cmd

### Actual behaviour
```
d:\tmp/hello.txt
```

### Expected behaviour
```
d:\tmp\hello.txt
```

### Steps to reproduce using `nvim-qt -- -u NORC`. For vim use `vim -u NORC`

```
:e d:\tmp/hello.txt
:echo expand ('%:p')
```

Note: `d:\tmp\hello.txt` doesn't need to exist on disk.

Seems like nvim doesn't normalize using the shellslash option.

This one also seems to have a problem.
```
:set shellslash
:e d:\tmp/hello.txt
:echo expand('%:p')
```

vim shows `d:/tmp/hello.txt` while nvim shows `d:\tmp/hello.txt`

**Comment by janlazo** [comment]
Is this resolved with https://github.com/neovim/neovim/pull/7349?

**Comment by prabirshrestha** [comment]
Thanks. The issue is resolved.
