### ISSUE TITLE
Always prefer win32yank on Windows

### ISSUE THREAD

**Issue by gglanzani** [neovim/neovim#6658]
- `nvim --version`: 0.2.1
- Operating system/version: Windows 10 Creator update

### Actual behaviour
On Windows I would expect win32yank to take precedence over lemonade (when in the $PATH). This however doesn't happen. Is there any way to force it?

### Expected behaviour
On Windows win32yank should be preferred?

**Comment by justinmk** [comment]
The idea is that if you have lemonade, it's assumed you want to actually use it.

https://github.com/neovim/neovim/pull/6030 allows configuration.

**Comment by gglanzani** [comment]
@justinmk It's borderline :)

I have lemonade for when I start nvim from WSL, otherwise I'm happy with win32yank :)

Great that #6030 fixes that. I think we can close this.
