### ISSUE TITLE
v0.2.0 changes cursor style from underline to block

### ISSUE THREAD

**Issue by mkozjak** [neovim/neovim#6662]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? Yes
- Operating system/version: MacOS Sierra
- Terminal name/version: MacOS Sierra Terminal.app
- `$TERM`: xterm-256color

### Actual behaviour

nvim resets my terminal cursor from underline to block once vim is opened and left.

### Expected behaviour

Underlined cursor in both terminal and nvim.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:q
```

This started happening after upgrading to 0.2.0

**Comment by teto** [comment]
try `set guicursor=` and it should disable cursor updates.

**Comment by mkozjak** [comment]
Nice!
