### ISSUE TITLE
spellfile.vim uses incorrect XDG path on Windows

### ISSUE THREAD

**Issue by gglanzani** [neovim/neovim#6664]
- `nvim --version`: 0.2.1
- Operating system/version: Windows 10 Creators Update

### Actual behaviour
When calling `:set spell` nvim throws

```
Failed to create C:\Users\G/.local/share/nvim/site/spell
...
```

Note that the folder with the correct slashes exists and contains the spl and sug file.

### Expected behaviour
`:set spell` should work

### Steps to reproduce using `nvim -u NORC`

```
nvim.exe -u NORC
nvim-qt.exe --server ...
:set spell
```

**Comment by jamessan** [comment]
The problem has nothing to do with the slashes.  `spellfile#WritableSpellDir()` is hard-coding the use of `$HOME."/.local/share/nvim/site/spell"`, but then `spellfile#GetDirChoices()` looks through `&rtp` for the spell directory.

Windows doesn't use `$HOME."/.local/share"` for its runtime directory.

We need #6272 to get merged and then should adapt `spellfile.vim` to use that instead of hard-coded paths.

**Comment by jamessan** [comment]
A short-term fix would be to add a `has('win32')` check and return the appropriate path in `spellfile#WritableSpellDir()`.

**Comment by gglanzani** [comment]
@jamessan Thanks for the pointer. I've create `site` inside my $XDG_DATA_HOME and moved the spell folder there and now it works.

**Comment by gglanzani** [comment]
I've added a note on the wiki https://github.com/neovim/neovim/wiki/Installing-Neovim/4e670496e71d7dd537f11b661ddd28c29ba7243d

A bit of background: I've noticed that in `spellfile.vim` there was a check for `$XDG_DATA_HOME/nvim/site`. If that is present, then `$XDG_DATA_HOME/nvim/site/spell` becomes the spell folder. I hope this helps someone.

**Comment by janlazo** [comment]
Workaround in $LOCALAPPDATA/nvim/init.vim because of `&rtp` check

```viml
let s:base_dir = expand('<sfile>:p:h')

if has('win32')
  function! spellfile#WritableSpellDir()
    " expand() is for consistent slashes based on the value of &shellslash
    return expand(s:base_dir . '/spell')
  endfunction
endif
````
