### ISSUE TITLE
Cursor is not restored to previous state after exiting nvim

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#6665]
NVIM v0.2.1-dev, installed on Ubuntu 14.04.5, accessed remotely from current Debian testing and Konsole. TERM is set to xterm-256color.

Before entering nvim, I have non blinking block cursor in the terminal. My cursor setting for nvim is as follows:

    set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor

It's useful to have blinking cursor in the editor, but after exiting I expect it to set things back they were. However after exiting nvim, cursor continues blinking.

**Comment by justinmk** [comment]
Terminals do not provide a way to query the cursor style, so this can't be solved in general. To work around it, use a VimLeave autocmd:

    au VimLeave * set guicursor=a:block-blinkon0

I've add this to the FAQ. https://github.com/neovim/neovim/wiki/FAQ#cursor-style-isnt-restored-after-exiting-nvim

**Comment by shmerl** [comment]
@justinmk: I get some weird results in Konsole.

When I'm doing: `set guicursor=a:block-blinkon1` - the cursor stops blinking. And doing `set guicursor=a:block-blinkon0` makes it blink.

**Comment by justinmk** [comment]
@shmerl Thanks, that is a bug. It was flipped around for Konsole. Fixed: https://github.com/neovim/neovim/commit/0502ac47fb5391889d1eed9d7c378a87e35d7882

**Comment by butla** [comment]
@shmerl This also fixes it for me, thanks!
@justinmk Too bad that fix was one day too late for the release. Do you have an estimated date for the new release?

**Comment by justinmk** [comment]
it's on the milestone

**Comment by butla** [comment]
Oh, just noticed that if I do `set guicursor+=a:block-blinkon1`, the curor will not be changing shape in insert mode.

**Comment by ericrbg** [comment]
Is there something equivalent to writing `"\x9b\x33\x20\x71"` on output? All the `guicursor` options work, but I can't find one that writes DECSCUSR 0, just to set it to a specific value instead.
