### ISSUE TITLE
win: NVIM v0.2.0 nvim-win64.zip wrong version

### ISSUE THREAD

**Issue by paulburlumi** [neovim/neovim#6669]
- `nvim --version`:
NVIM v0.2.1-6-g9b1cad7c
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT
32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wst
rict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla
-fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/b
uild/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:
/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/m
sys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src
/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN
Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui
- Vim (version: ) behaves differently? N/A
- Operating system/version: Windows 7 Enterprise Service Pack 1 [Version 6.1.7601]
- Terminal name/version: cmd.exe
- `$TERM`: N/A

### Actual behaviour
From the Releases page on github.com:
https://github.com/neovim/neovim/releases
Navigate to the NVIM v0.2.0 section
Under Downloads click on the nvim-win64.zip link
This will download a zip file from here:
https://github.com/neovim/neovim/releases/download/v0.2.0/nvim-win64.zip
When I unpack the zip file and run `nvim --version` I get:
NVIM v0.2.1-6-g9b1cad7c
### Expected behaviour
When I unpack the zip file and run `nvim --version` I expected to get something like:
NVIM v0.2.0-?-g52727d98
It appears the wrong version is being offered for download from the releases page.

**Comment by justinmk** [comment]
That's the correct version. It's 6 commits later than 0.2 because some Windows fixes were included after 0.2 was tagged.
