### ISSUE TITLE
Windows - :CheckHealth crashes

### ISSUE THREAD

**Issue by TheCycoONE** [neovim/neovim#6672]
- `nvim --version`:
From PR #6670
```
NVIM v0.2.1-23-gc15502eb
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla
-fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui

For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
- Vim (version: ) behaves differently?
vim doesn't have CheckHealth

- Operating system/version:
Windows Server 2008 R2 Version 6.1.7601

- Terminal name/version:
ConsoleZ or cmd

- `$TERM`:

### Actual behaviour
Displays the following error
```
Running healthchecks...Assertion failed!

Program: c:\Users\sbaker\Neovim\bin\nvim.exe
File: src/win/handle-inl.h, Line 159

Expression: 0

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
The exit code is 3.

### Expected behaviour
Should display neovim health information

### Steps to reproduce using `nvim -u NORC`

```
nvim --headless -c ":CheckHealth" -u NORC

```
### Note
The error does not occur when I run through an msys2 environment, either directly or through nvim-qt, but always happens outside of the msys2 environment (directly or through nvim-qt)

**Comment by jamessan** [comment]
This is an assert in [libuv](https://github.com/libuv/libuv/blob/cb0cc7346d1c2b5bdf2bd89e4006a50fb6f9c3dd/src/win/handle-inl.h#L159).  The handle type appears to be unknown when trying to cleanup a handle after running a process.

**Comment by equalsraf** [comment]
Cant reproduce :S but to be fair I do not have python/ruby which is likely most of the work done in checkhealth.

@TheCycoONE these builds should have debug symbols (https://ci.appveyor.com/project/equalsraf/neovim) but they are still not finished.

**Comment by justinmk** [comment]
Can't reproduce with/without ruby, nor with/without the neovim ruby gem. I have python2 neovim module installed, but not python3. 

@TheCycoONE can you try this:

```
:edit $VIMRUNTIME/autoload/health/provider.vim
```

1. Find `health#provider#check()`, then comment-out the call to `s:check_ruby()`. 
2. Restart nvim-qt
3. `:CheckHealth`
    - If crash still occurs, go to step (1), comment-out another `s:check_*` call. 

Hopefully this narrows down the problem. 

Another thing to try: comment out the call to `jobwait()` (line 67). `:CheckHealth` won't work correctly, but if it doesn't crash that at least tells us the problem is a bug in jobwait() (which I supsect).

**Comment by TheCycoONE** [comment]
Commenting out `call s:check_python(2)` prevents the crash.

Commenting out the jobwait on line 67 does not prevent the crash.

Bisecting s:check_python(version) shows that the crash happens at `let [pyname, pythonx_errs] = provider#pythonx#Detect(a:version)`

I do not know where that function is defined.

**Comment by justinmk** [comment]
`provider#pythonx#Detect` is defined in:

    :edit $VIMRUNTIME/autoload/provider/pythonx.vim

**Comment by TheCycoONE** [comment]
The failure is around line 94 of that file:
```
"let prog_ver = system([ a:prog , '-c' ,
  "      \ 'import sys; ' .
  "      \ 'sys.path.remove(""); ' .
  "      \ 'sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); ' .
  "      \ 'import pkgutil; ' .
  "      \ 'exit(2*int(pkgutil.get_loader("neovim") is None))'
  "      \ ])
```

I think it's trying to run the cygwin python2.

**Comment by TheCycoONE** [comment]
Seems likely it's not that line, I just need to simulate a shell error of 2.

**Comment by TheCycoONE** [comment]
python2.7 is not the issue, the issue is `python`.

I'm not sure why it thinks it can find `python`, it does not appear in the path.

I added
```
 if a:prog == 'python'
    return [0, 'found python but not checking it']
  endif
```
to pythonx.vim at line 86 (after the prog_path ==$ '' block), and now I get:
```
## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    Checking C:\cygwin64\bin\python2 caused an unknown error. (-1, output: ) Report this at https://github.com/neovim/neovim
    C:\cygwin64\bin\python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    python found but not checking it
  - ERROR: Python provider error
    - SUGGESTIONS:
      - provider/pythonx: Could not load Python 2:
          Checking C:\cygwin64\bin\python2 caused an unknown error. (-1, output: ) Report this at https://github.com/neovim/neovim
          C:\cygwin64\bin\python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          not checking python
  - INFO: Executable: Not found
```
with no crash.

From cmd:
```
c:\Users\sbaker\Neovim\bin>python
'python' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by justinmk** [comment]
pythonx#Detect() tries different variations: `python`, `python2.6`, etc. The exit code of 2 indicates that `pkgutil.get_loader("neovim")` is failing.

Anyways, it shouldn't crash, so we may need to add a guard in `system()` implementation to avoid that libuv assert.

**Comment by TheCycoONE** [comment]
Additionally:
`python2.7.exe` exists, there also exists in `C:\cygwin64\bin` two cygwin symlink files `python` and `python2` which can't be interpreted outside of cygwin. It's those that are causing the failure. They are not executable.

**Comment by justinmk** [comment]
> It's those that are causing the failure. They are not executable.

What's the minimum vimscript needed to cause the crash for you? E.g.:

    :call system(['/path/to/cygwin/python', ...])

Just passing a non-executable file to `system([])` isn't enough to reproduce the issue, on my machine.

**Comment by TheCycoONE** [comment]
Just `let prog_ver = system([ a:prog ])` is enough.

`a:prog` here is just `python` with no path. I don't know how the lookup works in `system` but in `cmd.exe` only exe or cmd files are considered and nothing is found for `python` or `python2`

Note that `python2` doesn't cause the issue - it just causes that `Checking C:\cygwin64\bin\python2 caused an unknown error. (-1, output: ) Report this at https://github.com/neovim/neovim` error which I guess I'm reporting now.

**Comment by justinmk** [comment]
If you do this from your `:` prompt--not the pythonx function--does it crash?

    :call system(['python'])

> I don't know how the lookup works in system but in cmd.exe only exe or cmd files are considered and nothing is found for python or python2

It iterates through `%PATH%` and `%PATHEXT%`. In Nvim, try this:

    :let $PATH='C:\Windows\system32;C:\Windows;'

then try again. does it crash?

**Comment by TheCycoONE** [comment]
Does not crash when called from `:` prompt.

**Comment by TheCycoONE** [comment]
Verified my findings again with a fresh neovim share.

One other thing to note. Using string syntax instead of list syntax for system.
```
let prog_ver = system( a:prog . ' -c ''' .
        \ 'import sys; ' .
        \ 'sys.path.remove(""); ' .
        \ 'sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); ' .
        \ 'import pkgutil; ' .
        \ 'exit(2*int(pkgutil.get_loader("neovim") is None)) '''
        \ )
```
avoids the crash:

```
## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    Checking C:\cygwin64\bin\python2 caused an unknown error. (1, output: 'python2' is not recognized as an internal or external command,
    operable program or batch file.
    ) Report this at https://github.com/neovim/neovim
    C:\cygwin64\bin\python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    Checking C:\cygwin64\bin\python caused an unknown error. (1, output: 'python' is not recognized as an internal or external command,
    operable program or batch file.
    ) Report this at https://github.com/neovim/neovim
  - ERROR: Python provider error
    - SUGGESTIONS:
      - provider/pythonx: Could not load Python 2:
          Checking C:\cygwin64\bin\python2 caused an unknown error. (1, output: 'python2' is not recognized as an internal or external command,
          operable program or batch file.
          ) Report this at https://github.com/neovim/neovim
          C:\cygwin64\bin\python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          Checking C:\cygwin64\bin\python caused an unknown error. (1, output: 'python' is not recognized as an internal or external command,
          operable program or batch file.
          ) Report this at https://github.com/neovim/neovim
  - INFO: Executable: Not found

```

**Comment by TheCycoONE** [comment]
I wouldn't trust anything at this point.
Adding
```
 let foo = a:prog
  if a:prog == 'python'
    foo = 'python'
  endif
```
just above the system call also prevents the crash. Note that foo is completely unused. Must be memory corruption somewhere.

**Comment by janlazo** [comment]
For `s:check_interpreter` in `$VIMRUNTIME/autoload/provider/pythonx.vim` , can the system call for python version use `prog_path`, output of `exepath(a:prog)`, to force the cygwin python? If not, can we use ['cmd', '/c', a:prog, ...] because the crash doesn't happen with string form?

**Comment by TheCycoONE** [comment]
@janlazo I think the current feeling is that the crash is caused by a memory access violation somewhere possibly unrelated that corrupts the system call. There are quite a few no opt changes to the vim script I tried that prevent the crash, like the foo variable I pasted above.

**Comment by justinmk** [comment]
@TheCycoONE would you be able to check if this happens on master? Pre-built zips for windows are here: https://github.com/neovim/neovim/releases

**Comment by TheCycoONE** [comment]
Sorry, I missed that comment. I no longer have the system that experienced the issue and rarely use Windows anymore.
