### ISSUE TITLE
running nvim under python subprocess module can't find python

### ISSUE THREAD

**Issue by wreed4** [neovim/neovim#6674]
- `nvim --version`:
NVIM v0.1.7
Build type: Release
Compilation: /home/user/wreed/.linuxbrew/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/user/wreed/tmp/neovim/build/config -I/home/user/wreed/tmp/neovim/src -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/home/user/wreed/tmp/neovim/.deps/usr/include -I/usr/include -I/home/user/wreed/tmp/neovim/build/src/nvim/auto -I/home/user/wreed/tmp/neovim/build/include
Compiled by wreed@fxdeva14

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/user/wreed/neovim/share/nvim"

- Vim (version: ) behaves differently? yes
- Operating system/version: (Red Hat 4.4.7-17)
- Terminal name/version: bash 4.1.2(1)-release
- `$TERM`: screen-256color

### Actual behaviour
on startup: 
Error detected while processing /home/user/wreed/.vim/init.vim:
line    7:
E117: Unknown function: provider#python#Call
Error detected while processing /home/user/wreed/.vim/bundle/vim-lvimrc/plugin/lvimrc.vim:
line    1:
E117: Unknown function: provider#python#Call
line   13:
E117: Unknown function: provider#python#Call

after startup, error on :python print("hello")

### Expected behaviour
Not those errors :)

### Steps to reproduce using `nvim -u NORC`
open python, import subprocess
subprocess.call(['nvim'])

**Comment by wreed4** [comment]
I should note neovim works perfectly fine normally.

**Comment by justinmk** [comment]
VIMRUNTIME is needed so that nvim can find the standard plugins, which are required for python support.

**Comment by wreed4** [comment]
So how do I make that not invalid? And why would it be invalid when running under python as the subprocess module should forward the exact environment if not told otherwise?

**Comment by v3t3a** [comment]
I don't know if is usefull or not, but I don't reproduce. Seems to be specific.
* I try with both python 2 and 3
* Debian 8 jessie
* Latest version of neovim (NVIM v0.2.1-22-g2b3cb2c)

**Comment by justinmk** [comment]
> So how do I make that not invalid? And why would it be invalid when running under python as the subprocess module should forward the exact environment if not told otherwise?

I don't know. That's a debugging task that I can't perform for you.

**Comment by v3t3a** [comment]
@wreed4 Can you just try with the latest version ?
Just to see if this is a version problems or not.
