### ISSUE TITLE
No autoload folder for user...

### ISSUE THREAD

**Issue by farebord** [neovim/neovim#6675]
- `nvim --version`: v0.2.1.6
- Operating system/version: Windows 10
- Terminal name/version: -
- `$TERM`: -

### Actual behaviour
No autoload folder for user working

### Expected behaviour
vim-plug being autoloaded

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by jamessan** [comment]
You need to create the directory for your personal configuration, just like in Vim.  As described in `:help vimrc`, the config goes under `$XDG_CONFIG_HOME\nvim` (which defaults to `$HOME\AppData\Local\nvim` on Windows).   You would create the `autoload` directory there.
