### ISSUE TITLE
Long timeout with input locking after executing error resulting command with Ctrl-o

### ISSUE THREAD

**Issue by Cerule** [neovim/neovim#6679]
- `nvim --version`: 0.1.7 . I heard this is present in newer version aswell.
- Vim (version: ) behaves differently? Yes
- Operating system/version: Linux, openSUSE tumbleweed
- Terminal name/version: yakuake 3.0.4 (konsole 16.12.3)
- `$TERM`: xterm-256color

### Actual behaviour
When in Insert mode, hitting C-o (to enter 1 command in Command mode and return) and doing a search with /, if string is not found input is locked for about 5 s before anything can be done.

### Expected behaviour
Best IMO would be to leave error output but not to lock input at all like it's in Normal mode. If locking has to be there, the duration should be as brief as possible. In Vim 8.0 it's about 1s.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
i for Insert mode, hit C-o, "/" to search, type any string, hit enter and try to give input.

**Comment by justinmk** [comment]
Seems ok in `NVIM v0.3.1-89-g5c309b0d6a7b`
