### ISSUE TITLE
Cannot allocate color SlateBlue when using :Ranger in terminal during adding a new file

### ISSUE THREAD

**Issue by wikimatze** [neovim/neovim#6682]
- `nvim --version`: NVIM v0.2.1-7-g13ec5214
- Vim (version: ) behaves differently? It actually works on vim
- Operating system/version: Ubuntu 14.04
- Terminal name/version: xfce4-terminal 0.6.3
- `$TERM`:

### Actual behaviour

Hi, when I'm using https://github.com/ranger/ranger (latest version 1.8.0) with the https://github.com/francoiscabrol/ranger.vim (latest version https://github.com/ranger/ranger/commit/ccbcfc60810cba1ef79677a714746d40b34e34e7) plugin. When I'm in nvim and open the ranger dialog with `:Ranger` in nvim `:Terminal`  and create a new file in ranger with :e nvim.txt` I get the following error:

```sh
Error detected while processing /usr/local/share/nvim/runtime/syntax/syncolor.vim:
line 46:
E254: Cannot allocate color SlateBlue
E254: Cannot allocate color SlateBlue
E254: Cannot allocate color SlateBlue
E254: Cannot allocate color SlateBlue
```

### Expected behaviour

`:Ranger` in nvim `:Terminal`  and create a new file in ranger with :e nvim.txt` works without any error

### Steps to reproduce using `nvim -u NORC`

Here is my minimal init.vim

```
call plug#begin('~/.config/nvim/plugged')
Plug 'francoiscabrol/ranger.vim', '902bb5c'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()
```

Please not, that https://github.com/junegunn/vim-plug needs to be installed in `~/.config/nvim/plugged`. Now start nvim and type `:PlugInstall`.

When I delete the else case on line 43 in `/usr/local/share/nvim/runtime/syntax/syncolor.vim` the error is gone.

**Comment by xxoolltt** [comment]
I just find a solution .  Maybe you need the file : "/usr/share/vim/vim74/rgb.txt "
I download the file ,and it works

**Comment by wikimatze** [comment]
Hi @xxoolltt I have this file in the location you mentioned. Where should I download it so that the error goes away?

**Comment by chrisbra** [comment]
to the nvim runtime directory (which should happen automatically during a make install)

**Comment by justinmk** [comment]
Ah, rgb.txt is not installed in $VIMRUNTIME. Still not clear to me why this file is needed at all, but whatever. Easy to fix.

**Comment by chrisbra** [comment]
because it is needed to parse color names (at least in Vim)

**Comment by justinmk** [comment]
It's not really needed, it's just "how we've always done it".

related: https://github.com/neovim/neovim/issues/5695 

SlateBlue is a built-in color name, see https://github.com/neovim/neovim/pull/5733

I cannot reproduce the error. I tried this:

```
nvim -u NORC
:hi Special term=bold cterm=NONE ctermfg=DarkMagenta ctermbg=NONE gui=NONE guifg=SlateBlue guibg=NONE
:hi Underlined term=underline cterm=underline ctermfg=DarkMagenta gui=underline guifg=SlateBlue
```

No error. Also tried with `:set bg=light`.

**Comment by wikimatze** [comment]
@xxoolltt a simple `sudo cp /usr/share/vim/vim74/rgb.txt /usr/local/share/nvim/runtime` solved the problem, thank you very much. Maybe the issue is buried within ranger. I can take care of that missing file when I'm compiling a new version of nvim.

**Comment by justinmk** [comment]
@wikimatze https://github.com/neovim/neovim/commit/69e33087716ce67bfda5f67a42f83d77906111f7 should "fix" this issue by including rgb.txt during install. Since we still have that file in our source tree, might as well install it.

Would like to know the real cause of this issue, but that will be a time-sink.

**Comment by wikimatze** [comment]
I'm with you. Thanks for the commit, so in the next version of nvim I can get rid of the line in my installation.
