### ISSUE TITLE
Echoed lambda behaves strangely

### ISSUE THREAD

**Issue by bounceme** [neovim/neovim#6689]
- `nvim --version`:0.2
- Vim (version: ) behaves differently?
yes, the message is echoed normally, at first column
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Actual behaviour
messages is shifted with whitespace to the right, looks like showcmd is temp enabled for the next keystroke too
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by bounceme** [comment]
minimal example:
```
function! g:EchoL(...)
  return {...->execute('echon "odd whitespace <-"')}
endfunction
echom EchoL()()
```

do echom in cmdline

**Comment by justinmk** [comment]
This is a known quirk with execute()
