### ISSUE TITLE
Not able to scroll and click any items in tagbar, after upgrade to nvim 0.2.0

### ISSUE THREAD

**Issue by vbauerster** [neovim/neovim#6690]
- `nvim --version`:
```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170504-56175-1sqbqd/neovim-0.2.0/build/config -I/tmp/neovim-20170504-56175-1sqbqd/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170504-56175-1sqbqd/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170504-56175-1sqbqd/neovim-0.2.0/build/include
Compiled by vbauer@icebook

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```
- Vim (version: ) behaves differently?
Vim 8.0 behaves same, but in previous version of nvim 0.7.0 everything was OK. I mean, I was able to click items and scroll with mouse inside tagbar window.
- Operating system/version:
macOS Sierra 10.12.4
- Terminal name/version:
iTerm2 Build 3.0.15
- `$TERM`:
xterm-256color

### Actual behaviour

Not able to scroll and click any items in [tagbar](https://github.com/majutsushi/tagbar) window, after nvim upgrade to v0.2.0. In nvim v0.7.0 I was able to scroll and click items inside tagbar window (it worked even in tmux session). Now it doesn't work in pure terminal nor inside tmux session.

### Expected behaviour

Working mouse events inside tagbar window

Do I miss some setting which enables mouse events? Or should I report to tagbar branch?

**Comment by fmoralesc** [comment]
The default setting for `mouse` changed (it made things confusing for people who wanted to paste using the mouse [sigh... /aside]), you can use `set mouse=a`.

**Comment by justinmk** [comment]
We have temporarily reverted the mouse=a default. This is unfortunate, but we didn't want to hold back the 0.2 release for it. We'll restore it in the future. In the meantime, add this to your init.vim:

    set mouse=a

Added to wiki: https://github.com/neovim/neovim/wiki/Following-HEAD#20170403

**Comment by vbauerster** [comment]
Thank you guys!
