### ISSUE TITLE
cursor doesn't display correctly on terminator when running commands

### ISSUE THREAD

**Issue by haySwim** [neovim/neovim#6691]
- `nvim --version`:
Bisected to commit ef753a76b95425e22638005f813cb2f22c6a0cfc

- Vim (version: ) behaves differently?

- Operating system/version:
Ubuntu 16.04 (KDE Neon)

- Terminal name/version:
- `$TERM`:
xterm
Using terminator terminator 0.98

Terminator config:
[global_config]
  suppress_multiple_term_dialog = True
  title_font = DejaVu Sans Mono 9
  title_use_system_font = False
[keybindings]
[layouts]
  [[default]]
    [[[child1]]]
      parent = window0
      type = Terminal
    [[[window0]]]
      parent = ""
      type = Window
[plugins]
[profiles]
  [[default]]
    background_color = "#002b36"
    background_image = None
    font = DejaVu Sans Mono 13.5
    foreground_color = "#bdd67b"
    login_shell = True
    palette = "#073642:#dc322f:#859900:#b58900:#268bd2:#d33682:#2aa198:#eee8d5:#002b36:#cb4b16:#586e75:#657b83:#839496:#6c71c4:#93a1a1:#fdf6e3"
    split_to_group = True                                                                                                                                                        
    use_system_font = False                                                                                                                                                      
  [[test]]                                                                                                                                                                       
    background_image = None                                                                                                                                                      
    palette = "#282a36:#6272a4:#4e9a06:#c4a000:#3465a4:#75507b:#06989a:#44475a:#44475a:#ef2929:#50fa7b:#fce94f:#729fcf:#ad7fa8:#8be9fd:#f8f8f2"

### Actual behaviour
Pressing : changes the cursor to undisplayable unicode ([2 q) [like so, bottom left corner](http://i.imgur.com/nPzfgM3.png) and writes that to stdout on :quit 

### Expected behaviour
Pressing : changes the cursor to displayable unicode, doesn't write it to stdout on :quit

### Steps to reproduce using `nvim -u NORC`

```
terminator
nvim -u NORC

Press :
```

**Comment by justinmk** [comment]
`:help guicursor`

**Comment by haySwim** [comment]
> What version are you currently using? 0.2 tries to avoid auto-enabling guicursor for known-broken terminals.

I'm using 0.2, it seems to work with the steps I described without adding `set guicursor=`, but when I start using my .vimrc even with `set guicursor=` added with ctrl-p, I'm seeing the unknown CSI sequences in ctrl-p's windows, although I guess that's a ctrl-p issue now.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal

ctrlp sets 'guicursor'. It shouldn't do that if 'guicursor' is empty.

**Comment by haySwim** [comment]
I could be another one of my plugins... 

Anyhow, it works fine with konsole and it's probably time I switched over to tmux anyhow. Thanks for your help!
