### ISSUE TITLE
Neovim locks up when using :term on windows 

### ISSUE THREAD

**Issue by TyOverby** [neovim/neovim#6692]
- `nvim --version`:
```
NVIM v0.2.1-6-g9b1cad7c
Build type: Release
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc -tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
- Operating system/version: Windows 
- Terminal name/version: Windows command prompt

### Actual behaviours

When I open up a `:term` window, the regular "C:\foo\bar" text is printed, but as soon as I enter insert mode on the terminal, I neovim freezes.  Typing anything in while the frozen does nothing, but if I hit escape while its frozen, eventually neovim will unfreeze and go back to normal mode.

### Expected behaviour

neovim should not freeze, and it should allow me to type things into the terminal

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
```

This is on a brand new windows install with no software installed other than Visual Studio 2017 and Google Chrome.

**Comment by jamessan** [comment]
This is a known limitation.  It was part of the release notes:

> `:terminal` is not supported on Windows, yet. (Planned for 0.2.1)
