### ISSUE TITLE
tabstop bug causes crash

### ISSUE THREAD

**Issue by bounceme** [neovim/neovim#6696]
- `nvim --version`: 0.2
- Vim (version: ) behaves differently? yes, no crash
- Terminal name/version: iterm2
- `$TERM`:

### Actual behaviour

:set sw=0
:let &ts = -1
[Command Line] VIM                                                                                                         2705,1         Bot
Assertion failed: (result >= 0 && result <= INT_MAX), function get_sw_value, file /tmp/neovim-20170502-6538-rfsywu/neovim-0.2.0/src/nvim/option.c, line 6690.
Abort trap: 6

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set sw=0
:let &ts = -1
```

**Comment by justinmk** [comment]
There's a PR open for this.

**Comment by dumbl3d0re** [comment]
The linked PR is aimed to be part of v. 0.2.2 since Sep. 16.  Should this issue reflect that?
