### ISSUE TITLE
Single/Double quotes strange behavior.

### ISSUE THREAD

**Issue by farebord** [neovim/neovim#6698]
- `nvim --version`: 0.2.1
- Vim (version: ) behaves differently? 8
- Operating system/version: Windwos 10
- Terminal name/version: powershell/cmd
- `$TERM`: -

### Actual behaviour
When I try to enter a single quote or double quote I have to press the key twice, and as a result I get to single or double quotes. Also if I press space after pressing single/double quote key it will enter a space and no quote will appear.
i<"> = 
i<"><"> = ""

### Expected behaviour
i<"> = "
i<"><"> = ""

### Steps to reproduce using `nvim -u NORC`
i<">
```
nvim -u NORC

```

**Comment by jamessan** [comment]
This sounds like #6642.
