### ISSUE TITLE
:terminal on Windows freezes nvim

### ISSUE THREAD

**Issue by farebord** [neovim/neovim#6699]
- `nvim --version`: v0.2.1
- Vim (version: ) behaves differently? -
- Operating system/version: Windows 10
- Terminal name/version: cmd.exe
- `$TERM`:

### Actual behaviour
:terminal<cr>
cls (or try to type anything, it doesnt work.)
I press i to insert mode - neovim freezes until i press <ALT-F4>

### Expected behaviour
:terminal<cr>
cls
(clean screen)

### Steps to reproduce using `nvim -u NORC`
:terminal <cr>
cls<cr>
```
nvim -u NORC

```

**Comment by jamessan** [comment]
This is a known limitation.  It was part of the release notes:

> `:terminal` is not supported on Windows, yet. (Planned for 0.2.1)
