### ISSUE TITLE
cexpr/lexpr

### ISSUE THREAD

**Issue by jrpotter** [neovim/neovim#6702]
- `nvim --version`: 0.2
- Vim (version: ) behaves differently? No
- Operating system/version: macOS Sierra/10.12.4
- Terminal name/version: Terminal/2.7.2 (388.1)
- `$TERM`: xterm256-color

While playing around with a plugin earlier today, I was caught up by the behavior of cexpr/lexpr with a local errorformat set. Namely, functions dealing with the quickfix/location list windows always use the global setting, which I feel is counterintuitive. Here are two threads discussing this and a potential patch (which was reverted for backwards compatibility):
https://groups.google.com/forum/#!msg/vim_use/UAC54sqT1G4/cIxehPEnBAAJ
https://groups.google.com/forum/#!msg/vim_dev/qFWC-08BsPs/Ga_kPL5yAgAJ

Any thoughts on perhaps applying this patch to neovim? I personally think it makes sense for quickfix related commands to continue using the global errorformat, but location lists, which are bound to a given window, would benefit from using the local value. Not sure if conformity to vim would trump making this change though.

**Comment by justinmk** [comment]
Is it going to break fugitive, dispatch.vim, ... ? 

Aren't there other ways already?

**Comment by jrpotter** [comment]
Yeah, after mulling it around a bit I realized this probably doesn't make much sense. Was just an annoyance I had and figured would bring up as there have been previous discussions regarding this topic.
