### ISSUE TITLE
nvim-qt on Windows: * (asterisk) not working

### ISSUE THREAD

**Issue by simonced** [neovim/neovim#6703]
- `nvim --version`:

```
NVIM v0.2.1-25-g2e3b78d1
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw32/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw32/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

- Vim (version: ) behaves differently?

The nvim binary and other vim versions (including 8) will do a search in insert mode.
Also the `*` will appear in the text in insert mode.

- Operating system/version: 

Windows 10 (creators update) Japanese

- Terminal name/version:

qt version (graphical client)

- `$TERM`:

windows command prompt (but not concerned by the current issue)

### Actual behaviour

nothing happens

### Expected behaviour

search of word under cursor in normal mode
`*` sign in insert mode

### Steps to reproduce using `nvim -u NORC`

the qt version doesn't support such option  
`nvim` works in windows command promt.

**Comment by MMDF** [comment]
Same issue here. Cannot type asterisk and therefore cannot access the clipboard register.

**Comment by justinmk** [comment]
`call nvim_input('*')` is all that nvim needs. Closing in favor of https://github.com/equalsraf/neovim-qt/issues/325
