### ISSUE TITLE
Can't noremap <S-F10> in nvim-qt on Windows

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#6706]
- `nvim --version`: NVIM v0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? yes
- Operating system/version: Windows 7 64 bits
- Terminal name/version: nvim-qt
- `$TERM`:

### Actual behaviour
Pressing `<S-F10>` got nothing after remapping it.

### Expected behaviour
`<S-F10>` can actually work.

### Steps to reproduce using `nvim -u NORC`

start nvim-qt.exe

```VimL
:nnoremap <S-F10> :echo 10<cr>
```

then press S-F10, nothing happened.
but shift + (F1 - F9) worked.

I have four important plugins which is setup to be triggered by S-F9 to S-F12.
That bug will force me to change my habit, but it is too hard to change because of muscle memory.

**Comment by justinmk** [comment]
This needs to be handled at https://github.com/equalsraf/neovim-qt/issues/279

`:call nvim_input('<s-f10>')` works so there's nothing more that can be done in Nvim core.
