### ISSUE TITLE
wrong behavior in `hi Float` for cpp syntax

### ISSUE THREAD

**Issue by originalsouth** [neovim/neovim#6711]
- `nvim --version`: 
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
- Vim (version: ) NVIM v0.1.7 (works)
- Operating system/version: archlinux
- Terminal name/version: gnome-terminal 2.24.1 (VTE 0.48.2), tmux 2.4
- `$TERM`: `screen-256color`

In my color scheme I'm using:
`hi Float             guifg=#eb2121   guibg=NONE      guisp=NONE      gui=NONE`
`hi Number        guifg=#f0ad6d    guibg=NONE      guisp=NONE      gui=NONE`
see https://github.com/originalsouth/nvimrc/blob/master/colors/inkpot.vim

### Actual behaviour
In NVIM 0.2.0 a statement like `printf("%g\n",1.0+1.0);` colors the `1` as defined by `hi Number` and the `.0` ad defined by `hi Float` in cpp only (not in c).

See image for example: c left, cpp right (the `1` is yellowish where the `.0` is redish):

![nvim0 2 0-hi-float](https://cloud.githubusercontent.com/assets/5300799/25891121/2775a3b8-3570-11e7-8ef6-ee0ad7a2c5a1.png)

## Expected behaviour 

As in NVIM 0.1.7 (or older versions) where the floats in the statement `printf("%g\n",1.0+1.0);` are colored according to `hi Float` both in cpp and c.

See image for example: c left, cpp right (`1.0` is redish):

![nvim0 1 7-hi-float](https://cloud.githubusercontent.com/assets/5300799/25891153/46985f7e-3570-11e7-9cc4-a10fd4abe9c6.png)

Purely downgrading the neovim package solves this problem.
Tested with neovim --noplugin

### Steps to reproduce using `nvim -u NORC`
Could not reproduce with `nvim -u NORC`

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Syntax plugins (e.g. for ruby/java/YAML) are maintained by the maintainer listed at the top of the plugin file. Please report to that person, or to https://github.com/vim/vim. Thanks!

**Comment by originalsouth** [comment]
Thanks for the reply. Fair. I'll try to report there once I reproduce the bug in vim. Thanks!

**Comment by originalsouth** [comment]
Link to upstream bug report: https://github.com/vim-jp/vim-cpp/issues/46
