### ISSUE TITLE
C generator: document conventions

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#6712]
- document conventions: https://github.com/neovim/neovim/pull/6618#issuecomment-300437034
- ~~make [suggested change](https://github.com/neovim/neovim/pull/6618#issuecomment-300438987):~~ 
  >  ~~remove `*.c.generated.h` file completely. We do not need declarations if we can just put definitions before the place where they are used and file does not look like functions inside it are being used internally.~~

**Comment by ZyX-I** [comment]
@justinmk You misspelled my suggestion. I was suggesting to remove *new* such files *from that PR*. I.e. generated static functions’ declarations *for files generated there*, not *for all files*.

**Comment by ZyX-I** [comment]
Removing for all files requires reordering static functions and caring about the order in the future. It is not what I would ever want to do. Removing new files there requires just stopping generating them and removing a few lines.

**Comment by ZyX-I** [comment]
And additionally, problems with attributes some of which need to be near declarations, but not near definitions.

**Comment by ZyX-I** [comment]
src/nvim/README.md?
