### ISSUE TITLE
Misleading error message if finding Python fails.

### ISSUE THREAD

**Issue by vext01** [neovim/neovim#6715]
In CheckHealth:

```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - INFO: Executable: /usr/local/bin/python2.7
  - ERROR: Command error -1: python -c from neovim import VERSION as v; print("{}.{}.{}{}".format(v.major, v.minor, v.patch, v.prerelease))
```

Note the quotes are missing from the output, but are actually there.

**Comment by mhinz** [comment]
Why did you create an issue _after_ opening a [PR with the fix](https://github.com/neovim/neovim/pull/6714)?

**Comment by vext01** [comment]
This is different. I didn't fix the quoting in the PR, only the interpreter path.

**Comment by ZyX-I** [comment]
Quotes are not there. Plugin is using list for arguments, so that are separate strings and not quoted something, so quoted command is not readily available. Since that is for reading by humans I would be fine with the current state, but some people may probably want to copy-paste that to shell and run themselves which needs quotes to be there.

**Comment by janlazo** [comment]
If single-quoting can't work, can that python command be placed in some `tempname()`.py to get around the quoting issue to avoid escaping issues with cmd.exe?

**Comment by justinmk** [comment]
@janlazo it's only for display

**Comment by janlazo** [comment]
Double-quoting the command and using single quotes for the format brackets doesn't break on sh and cmd.exe for me.

```sh
python -c "from neovim import VERSION as v; print('{}.{}.{}{}'.format(v.major, v.minor, v.patch, v.prerelease))"
```
```viml
  let nvim_version = s:system(['python', '-c',
        \ '"from neovim import VERSION as v; '.
        \ 'print('{}.{}.{}{}'.format(v.major, v.minor, v.patch, v.prerelease))"'],
\ '', 1, 1)
```

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/6721

**Comment by ZyX-I** [comment]
@janlazo This yields an incorrect command, it would not print anything.
