### ISSUE TITLE
Remote plugin async command blocks nvim

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#6720]
Maybe Im understanding remote plugins incorrectly, but I tried something like:
```
    @neovim.command('SleepEcho', range='', nargs='*', sync=False)
    def command_handler(self, args, range):
        time.sleep(5)
        self.vim.command('redraw | echo "Woke up"')
```

I was expecting to be able to use nvim while the process was sleeping (or doing a long computation), but what Im experiencing is that the screen does not reflect any of the commands or text Im editing while the command is running the sleep, and when returning back from the sleep, all those modifications are applied. Am I missing something?

Thanks,
A

**Comment by justinmk** [comment]
That's not what I observe. Though I used `self.nvim` instead of `self.vim`. (Are you using an old version of the python "neovim" module? More generally, please fill out the questions from the issue template)

**Comment by pwntester** [comment]
Thanks for the quick response, here are the details about my env:
- `nvim --version`: NVIM v0.2.0-104-g5f02608
- Vim (version: ) behaves differently? Its a neovim specific issue
- Operating system/version: OSX Sierra
- Terminal name/version: iTerm2
- `$TERM`: screen-256color
- neovim python plugin: neovim-0.1.13

**Comment by justinmk** [comment]
So, you followed the same steps I listed above?

**Comment by mhinz** [comment]
@pwntester 

What's the exact code you tested? I use the same environment as you and this example works for me:

```python
#!/usr/bin/env python3

import neovim
import time

@neovim.plugin
class Neovim:
    def __init__(self, vim):
        self.vim = vim

    @neovim.command('SleepEcho', range='', nargs='0', sync=False)
    def command_handler(self, args, range):
        time.sleep(5)
        self.vim.command('redraw | echo "Woke up"')
```

**Comment by pwntester** [comment]
@justinmk yep, followed same steps and still have the issue
@mhinz Exact same code (except for class name)

Just updated to NVIM v0.2.1-146-g147b4b6, same problem

**Comment by pwntester** [comment]
So, if I enter insert mode and come back to normal mode before executing the command, it works as expected.
If you enter the command right after starting nvim, I get the problem

**Comment by mhinz** [comment]
Start Neovim and do `:scriptnames`. Is `~/.local/share/nvim/rplugin.vim` sourced?

**Comment by justinmk** [comment]
Works fine for me. Did you try `nvim -u NORC` ? (This will still find the rplugin, because `rplugin.vim` is part of your "user data", not "configuration")

**Comment by pwntester** [comment]
That works. So, some plugin is messing up?

**Comment by justinmk** [comment]
Or some option (which could be a nvim bug). Can you narrow it down?

**Comment by pwntester** [comment]
Seems to be an issue with deoplete plugin. Can you try to reproduce before filing the bug there? Thanks

**Comment by Shougo** [comment]
> Seems to be an issue with deoplete plugin.

What is the deoplete issue?
I don't know.

**Comment by pwntester** [comment]
Well, not sure if its a deoplete issue. I was trying to find out if someone could try to verify on its end.
For me, running the steps described by @justinmk in #comment1 having deoplete installed result on the issue described in this ticket (neovim blocks until async commands ends). Uninstalling/disabling deopletes, result in being able to use neovim while the command is running asynchronously.

**Comment by justinmk** [comment]
> neovim blocks until async commands ends

Are you sure it _blocks_? Does CTRL-L or `:mode` show the screen? 

If it is really "blocked" this may be the same issue as https://github.com/neovim/neovim/issues/5364
