### ISSUE TITLE
[Suggestion] std library type functions using lua

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#6723]
Maybe this could go in a different neovim repository (think something like neovim/standard.nvim).

We could leverage lua to do a lot of cool things very easily for us in terms of adding more capability to the standard vim library.

For example:

```vim
function! std#string#byte(s, i) abort
  return luaeval('string.byte(_A.s, _A.i)', {'s': a:s, 'i': (a:i + 1)})
endfunction

function! std#string#upper(s) abort
  return luaeval('string.upper(_A)', a:s)
endfunction
```

Now I know some of these we have available written in C in `eval.c` but other items (for tables, lists, etc.) might have a lot of benefit from writing in Lua. Also, we wouldn't really have much code to maintain because the logic is all written by the Lua people.

**Comment by justinmk** [comment]
I don't follow. This proposal is about VimL wrappers, or how is it different from https://github.com/neovim/neovim/issues/6580 ?

**Comment by ZyX-I** [comment]
@justinmk #6580 suggests lua modules, this suggests VimL functions. Just this is very inconcrete and examples provided by @tjdevries are very useless: first one is just `char2nr(a:s[a:i])` and second is just `toupper(a:s)`, and I am very unsure that lua `string.upper` works better then Vim `toupper()` and not the opposite.

**Comment by justinmk** [comment]
We should continue to build out the "stdlib", but this will also continue to be usable by both VimL and Lua. Even in the case of https://github.com/neovim/neovim/issues/6580, all of this should be callable from VimL.

Maybe something like `v:lua` which exposes the entire Lua global module.
