### ISSUE TITLE
if_python does not respect if/else in vimL

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#6727]
### Actual behaviour
Running with `nvim -u NONE test.vim` where `test.vim` is the below:

```vimL
python3 import vim
python3 << EOF
def insert_text(text):
  vim.current.buffer.append(text, 1)
EOF

function! Insert_text2()
  if b:changedtick == 0
    call append(line('$'), 'in first clause')
    python3 insert_text('Running python first clause')
  else
    call append(line('$'), 'in second clause')
    python3 insert_text('Running python second clause')
  endif
endfunction
```

Then in that nvim instance, doing
```
source %
call Insert_text2()
```

Then you see that both `python3` lines run while only the relevant `call append()` line is triggered.

### Expected behaviour
Should not trigger both `python3` lines.

**Comment by justinmk** [comment]
I just noticed this as well.

**Comment by jamessan** [comment]
This is a regression from 0.1.7.

**Comment by jamessan** [comment]
Introduced by 3d48c35d6bfa83ba3ae621fa9ec3f512da199f59.

cc @ZyX-I

**Comment by ZyX-I** [comment]
The `script_get()` is now supposed to return NULL in case of `eap->skip`. It indeed does so, but only when using `<<`, I missed additional condition inside `if (cmd[0] != '<' || cmd[1] != '<' || eap->getline == NULL)` case.

**Comment by ZyX-I** [comment]
Actually, a ternary in `return` there is enough.
