### ISSUE TITLE
snap package

### ISSUE THREAD

**Issue by popey** [neovim/neovim#6728]
The neovim developers should consider making a snap of neovim and pushing it to the snap store for Linux users. If there was a snap [1] package of neovim available in the store, then new users could easily install it via "snap install neovim" and it would be kept up to date automatically whenever the neovim developers release a new version.

The method for making snaps is pretty straightforward, and once setup can be automated via build.snapcraft.io, travis, or launchpad. If configured, every commit which lands in master will trigger a new build directly to the store automatically for all supported architectures. Adventurous users can "snap install neovim --edge" to subscribe to the edge channel, indicating they're ok with the risk of using bleeding edge builds. More conservative users can use the stable channel. Optionally you could push beta releases to beta & candidate channels too.

Given how the version of neovim in the Debian archives is quite old, and the LTS version of Ubuntu (which has some millions of users) doesn't have it at all, this would be a great way to reach those users. One snap package would work on Linux Mint 18, Ubuntu 14.04, 16.04, 17.04, Debian 9, Elementary OS [2]. More distributions are being added all the time, but the neovim team wouldn't have to do anything to enable that, the snap team do.

Anyone up for the challenge? :)

There is a forum [3] where you can get help when making the snapcraft configuration file. 

[1] http://snapcraft.io/
[2] https://snapcraft.io/docs/core/install
[3] http://forum.snapcraft.io/

**Comment by justinmk** [comment]
We have an [AppImage script](https://github.com/neovim/neovim/commit/3c0cc028b7e787e3e87f21976d8b6333bf488219) that works well. We will auto-publish it to the [releases page](https://github.com/neovim/neovim/releases/).

Though I'm not opposed to also publishing snap, what's the advantage?

**Comment by popey** [comment]
Snaps have a few features that I don't think you'd get from appimage. 

  * Discovery: New users don't need to hunt down your github or web page to find an image to install/download, just run one line on their existing system. ```snap install neovim``` for example.
  * Auto-update: As soon as you push a new release to the store, within minutes your users get the new version, or immediately if they ```snap refresh```
  * Rollback: if something goes wrong in an update, users can roll back to a previous release easily and keep their config/data
  * Channels: You can have multiple versions of neovim active in the store. Users choose level of risk by selecting a channel. If you're doing a beta testing session, put the beta release in that channel and testers can ```snap install neovim --beta``` to get the new goodness, then switch to stable when the beta is over.
  * Tracks: You can support multiple stable releases in the store. So you could have the 0.1 branch in one track and 0.2 in another. You can publish updates to both, separately and have some users on each. Users who want to be 'sticky' on 0.1 can stay there. Very useful if 0.x is a breaking release, as it allows people to stay on existing version, and continue to get updates (if you push them).
  * Metrics: The store provides aggregated details about how many people are running each release, and geographic location. This might be useful for you to focus development effort, translation drives etc.

I think those are the main ones.

**Comment by justinmk** [comment]
https://github.com/vim/vim/pull/1709 may be useful if anyone wants to work on this. Though there is still the question of uploading the package to the snap "store", that should be [automated in bot-ci](https://github.com/neovim/bot-ci).

**Comment by GarethH96** [comment]
> vim/vim#1709 may be useful if anyone wants to work on this. Though there is still the question of uploading the package to the snap "store", that should be automated in bot-ci.

Here you go: https://build.snapcraft.io/

**Comment by still-dreaming-1** [comment]
I could be wrong, but AppImage seems like it is only about a way to get a program to run on many Linux distributions, whereas snap is about that plus a distribution channel / package manager / store where you can search for things and keep your programs up to date. I know the Solus distribution is committed to staying compatible with snap packages, which I don't think they would do unless they believed it was well designed.

**Comment by trialism** [comment]
Someone made a snap for neovim: https://uappexplorer.com/snap/ubuntu/neovim-kalikiana

"Contact: https://github.com/neovim/neovim/issues" - I don't know how legit is that snap.

Also, it'd be nice to have a flatpak/snap package because appimage doesn't have an update system except appimageupdate but then we would need to run that on all appimages and neovim's appimage - according to the updater - doesn't support updates.

**Comment by trialism** [comment]
I planned to create a flatpak but neovim doesn't have a stable tarball(at 0.2.2): https://github.com/neovim/neovim/releases and that's required at flathub.org

**Comment by justinmk** [comment]
> neovim doesn't have a stable tarball(at 0.2.2):

Huh? Is this a complaint about the lack of `1.0`? That flathub's mistake. All Neovim releases are stable, that's the point of releases.

**Comment by jamessan** [comment]
There's also this tidbit from their "submit an app" page:

> Currently flathub is focused on graphical desktop applications and not CLI/TUI applications.

**Comment by trialism** [comment]
@justinmk no, 0.2.2 would be a stable release but there's no tarball for linux. There are packages for windows, mac and appimage.

@jamessan I'd try to convince them with the `Terminal=true` .desktop configuration(it'd open neovim in the default terminal) and that their point is unfair because neovim is a famous editor. Also, there are GUIs for neovim so, creating a neovim "platform" would be desirable.

**Comment by trialism** [comment]
The flatpak package is almost ready however, I can't install the dependencies. The rule is to download the dependencies first than build them later but I can't use the third-party installer in neovim's make like that. I also can't use network connection and can't access `/usr`. Is there any way to tell `cmake ../third-party` to don't try to download the packages if they're already present?

**Comment by fwalch** [comment]
@trialism Try ` -DUSE_EXISTING_SRC_DIR=ON`

**Comment by trialism** [comment]
@fwalch due to that it won't build the 3rd-party deps.

**Comment by trialism** [comment]
`libtool:   error: cannot find the library '' or unhandled argument '/usr/lib'` - this is an error during the build of unibilium. Any idea what is this?

**Comment by kalikiana** [comment]
Hey there!

I'm the person who made the snap mentioned above. Seeing the thread, I was motivated to clean it up and rebase it on master. Proposed a PR #7918

**Comment by trialism** [comment]
@kalikiana hi, how does it work with neovim's remote support?

**Comment by kalikiana** [comment]
@trialism Can you be more specific? Are you talking about NeoVIM-specific API? The snap's built following the official recommendation ie. using `make` and uses the bundled deps.

**Comment by trialism** [comment]
@kalikiana have you tried it with remote python/ruby etc. plugins?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/7918

**Comment by fbruetting** [comment]
@trialism What’s the status with your flatpak effort? I’d like to see that very much, also vim is on flathub meanwhile… :)

**Comment by trialism** [comment]
@fbruetting I gave up on sandboxing non-proprietary software. And if you'd create a flatpak image for vim or neovim then you'd either need to include every interpreter into your package or give it access to almost everything. Also, think about root access and visudo...

**Comment by fbruetting** [comment]
Even if `nv` gets full root access, it would be a way better solution for cross-distribution installation, and for newer distributions like Fedora Silverblue/CoreOS, software should get installed via Flatpak, while rpm-layering is not that appreciated.

And why is there a need for including interpreters? Even terminal emulators can be shipped as flatpaks.

**Comment by trialism** [comment]
@fbruetting flatpak images are bloated and much harder to maintain. For cross-distro packaging neovim already has an appimage.

If you want to use the remote api in a certain language then your app needs access to the interpreter. Editors, terminal emulators and similar software don't need sandboxing at all.

**Comment by andrewebdev** [comment]
Snap package would have been nice. Don't know why there is so much opposition to is since it would have made my life as a user really easy right now, since I've had to spend my morning cleaning out a old nvim version and try to upgrade just because plugins don't support old api anymore. Would have been so much easier with a snap package.

@trialism snap packages can still be installed in `--classic` confinement which would not sandbox it.

**Comment by justinmk** [comment]
See #7918

**Comment by andrewebdev** [comment]
@trialism As pointed out to my by a user on Telegram:

> from reddit:
> "sgorf
> I am a Debian developer and an Ubuntu developer. I trust a snap, even a classic snap, far more than I trust a third party upstream apt repository. Third party upstream repositories break systems all the time. I know this because I get bug reports from their victims.
> 
> Typically they're well intentioned but it's their dependency needs that break things. This isn't the case with snaps, even classic snaps.
> 
> Well intentioned but broken changes to the system when not needed for dependency purposes are far fewer in number."

It was also pointed out that `--classic` is also intended as a temporary stopgap until there is appropriate support for mediating the particular access that the snap requires

**Comment by jamessan** [comment]
@andrewebdev FWIW, I am the Debian maintainer for neovim's packages and those are the exact same packages that get used for Neovim's [stable PPA](https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable), modulo any changes needed for backporting.
