### ISSUE TITLE
Strange lazyredraw behavior

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#6729]
- `nvim --version`:
```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build/config -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170505-72607-jjidmu/neovim-0.2.0/build/include
Compiled by sassanharadji@MacBook-Pro

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```
- Operating system/version:
macOS Sierra 10.12.4
- Terminal name/version:
ITerm Build 3.0.20170212-nightly
- `$TERM`:
xterm-256color

### Actual behaviour
if I `let &lines=&lines+1` screen flickers.
If I `set lazyredraw` and then `let &lines=&lines+1` in cmdline, screen doesn't flicker then if I call `redraw` it still doesn't flicker. But if I execute:
```
set lazyredraw
let &lines=&lines+1 | redraw
```
(`let &lines` or `set lines` doesn't matter)
it flickers. My conclusion is that if redraw is called immediately after setting lines screen flickers.

### Expected behaviour
Maybe there's some logic behind this behavior, but with my knowledge I think this behavior is not consistent.

### Steps to reproduce using `nvim -u NORC`
It doesn't happen with `nvim -u NORC` but I guess it's just because `nvim -u NORC` is so light compared to my setup. Maybe `nvim -u NORC` has this problem in a 100MH cpu. Btw, no commands sourced in my installed plugins is called between `let &lines=&lines+1` and `redraw` when they're separated by a pipe, `redraw` executes immediately after `let &lines...`.
```
nvim -u NORC

```

**Comment by dylnmc** [comment]
I have noticed this as well. I could figure out for quite a while what was going wrong. after simplifying my entire vimrc to just my `set ...` options, I was puzzled as to what it could be. I actually guessed that it might be lazyredraw pretty early on (first or second guess).

If `'relativenumber'` and `'lazyredraw'` are both enabled, then I get really noticeable and annoying cursor flickering just to the right of the column where numbers are displayed at the bottom (just above the statusline).

**Comment by JeanMertz** [comment]
I ran into this issue as well.

This _kind of, sort of_ reduces the flicker, but it's still not great:

```vim
function! LazyLinesAdd2(timer)
    set lines+=2
    setl nolazyredraw
endfunction

setl lazyredraw
let s:do = timer_start(10, 'LazyLinesAdd2')

autocmd BufLeave * setl lines-=2
```

**Comment by blueyed** [comment]
Would be good to know if that happens in Vim also already.

For me it happens sometimes only with `nvim -u NONE -c 'set lazyredraw'` and `:let &lines=&lines+1 | redraw`.

Could not see it with Vim, but when using `vim -Nu NONE -c 'set writedelay=10' -c 'set lazyredraw'` it still shows that the whole screen is being redrawn.

**Comment by sassanh** [comment]
This issue seems to be resolved in my quick test.
