### ISSUE TITLE
Possibility to set `cmdheight` to 0

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#6730]
It's a feature request. Currently vim/nvim accepts only "positive" number for `cmdheight` so there's no way to hide cmdline without hacks. It'd be great to let it happen. Maybe some plugins can benefit from this feature by hiding cmdline when their window is open (ctrlp for example does this and I guess it does so with some magic.) I tried setting lines, it works but with flickers. Would be much better to give users the ability to hide cmdline explicitly with no hack.

**Comment by jamessan** [comment]
See #1004.
