### ISSUE TITLE
Make the 'Normal' highlight a normal highlight

### ISSUE THREAD

**Issue by teto** [neovim/neovim#6738]
- `nvim --version`: 0.2-dev
- Vim (version: VIM - Vi IMproved 8.0 Rustines incluses : 1-446, 446-45) behaves differently? yes

### Actual behaviour
While writing tests for a highlight API such as nvim_hl_from_name/id in https://github.com/neovim/neovim/pull/6566 (not pushed yet), I realized that asking for the 'Normal' group generates an error, aka:
```
nvim -u NORC -c ':hi Normal'
```
Generates  `E411: highlight group not found: Normal` unlike vim.
When you look at :help hl-Normal, it says it belongs to the default highlights. Then when looking at syntax.c, the id=0 is special cased in ways it doesn't need to be. There is a +1 / -1 index tweaking dance all over syntax.c which makes the code harder to read than it should be.

I believe inserting a 'Normal' hl in place 0 would allow to get rid of most complexity.

**Comment by teto** [comment]
main problem `nvim -u NORC -c ':hi Normal'` was solved. Rest is implementation detials.

**Comment by glacambre** [comment]
@teto
>Rest is implementation detials.

What remains to be done to be able to close this issue? :)

**Comment by teto** [comment]
last time I remember there was an issue with backwards compatibility if setting Normal highlight ID to 0 as I wanted.  let's close and reopen if someone wants it/works on it.
