### ISSUE TITLE
+num64

### ISSUE THREAD

**Issue by sassanh** [neovim/neovim#6744]
Does neovim support `+num64`? Currently when I `:echo 100000000000` it prints `1215752192`. Should I enable something in compile time?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/5621

>  Should I enable something in compile time?

No, all features are always enabled.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/5621 is needed to enable the functionality.
