### ISSUE TITLE
Nvim exit with error, when use Undefined variable in VimEnter event.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6745]
- `nvim --version`: master
- Vim (version: ) behaves differently? yes
- Operating system/version: arch
- Terminal name/version: termite
- `$TERM`:

### Actual behaviour
in neovim I get:
```
Error detected while processing function SpaceVim#autocmds#VimEnter:nvim: /home/wsdjeg/src/neovim/src/nvim/strings.c:439: vim_strchr: Assertion `c >= 0' failed.
Aborted (core dumped)
```
and neovim exit with error.

but in vim8 I get

```
Error detected while processing function Test:
line    2:
E121: Undefined variable: g:wsd
```
and vim do not exit.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u test.vim
```
test.vim
```
fu! Test()
for a in g:wsd
endfor
endf
augroup Testnvim
au!
autocmd VimEnter * call Test()
augroup END  
```

**Comment by justinmk** [comment]
cc @zyx-i

**Comment by oni-link** [comment]
Just guessing: New version of `vim_strchr()` has no `assert()` anymore. An update should fix it.

**Comment by wsdjeg** [comment]
this issue was fixed？

**Comment by justinmk** [comment]
Did you check?

**Comment by wsdjeg** [comment]
sorry，mosttime I use mail to get notification，so I hope there is a comment when issue was closed。

I will check master branch tonight。
