### ISSUE TITLE
Using neovim with sudo does not load init.vim file

### ISSUE THREAD

**Issue by CodingJonas** [neovim/neovim#6746]
- `nvim --version`: v0.2.0
- Vim (version: ) behaves differently?
- Operating system/version: 4.10.13-1-ARCH
- Terminal name/version:
- `$TERM`:rxvt-unicode-256color

### Actual behaviour
When I edit a file with super user (`sudo nvim xyz.txt`) rights the init.vim file is not loaded. Neovim is still working, but without any personal settings or plugins.

### Expected behaviour
I want to use my configuration file.

### Steps to reproduce using `nvim -u NORC`
Opening any file with `sudo nvim xyz.txt`.

**Comment by jamessan** [comment]
The sudo configuration determines whether `$HOME` is set to the calling user or the user that you're changing to.  There's nothing nvim can do about that.  You can use `sudoedit`, though, to run the editor as your user instead of as root.

**Comment by aemonge** [comment]
Here is the link for the suggested plugin :)
https://vimawesome.com/plugin/sudoedit-vim

**Comment by jamessan** [comment]
@aemonge I wasn't suggesting a plugin. I was suggesting the sudoedit (or `sudo -e`) command that comes with sudo.

**Comment by aemonge** [comment]
@jamessan  in that case I'm glad I posted the plugin, so user's can choose between solutions :+1:

**Comment by sahilrajput03** [comment]
`sudo -e nvim myFile`

is the solution, and key thing is that files are saved only when you exit nvim. Thanks for this awesomeness. @jamessan

**Comment by CodingJonas** [comment]
I recommend to stick with @jamessan answer. It's not safe to use `sudo (n)vim` as this allows arbitrary command execution and if the editor crashes you might have a faulty file. It's safer to simply use `sudoedit`, and all tools will function with this as expected.

**Comment by sahilrajput03** [comment]
> I recommend to stick with @jamessan answer. It's not safe to use `sudo (n)vim` as this allows arbitrary command execution and if the editor crashes you might have a faulty file. It's safer to simply use `sudoedit`, and all tools will function with this as expected.

The problem I faced with that solution is that I couldn't save the file unless I exit the editor. Do you propose anything that I missed with that solution that I can try?

**Comment by CodingJonas** [comment]
Using `sudoedit` I don't think it's possible to achieve this. The bigger question: using `sudoedit` or not, is out of scope for this Github issue I would say :)
