### ISSUE TITLE
Non-proportional window resizing on window close

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#6748]
- `nvim --version`: NVIM v0.2.1-182-g6e4e70f
- Vim (version: ) behaves differently? Can't test right now.
- Operating system/version: Linux 4.9.6-gentoo-r1
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: xterm-256color

### Actual behaviour
With the following window layout:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
¦   e   ¦
---------
```
Closing the window 'e' will result in this layout:
```
---------
¦ a ¦ b ¦
¦   ¦----
----¦   ¦
¦ c ¦ d ¦
---------
```
### Expected behaviour
I expected the layout to be proportional:
```
---------
¦ a ¦ b ¦
---------
¦ c ¦ d ¦
---------
```
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c "vs | windo sp" -c "sp | wincmd J | close" 
```

I believe this behaviour has been introduced in the last three months as I don't recall this happening before. I wanted to try it on previous versions but somehow couldn't get them to build.

**Comment by justinmk** [comment]
That's up to your config, and Vim works the same way. `:set equalalways`.

**Comment by glacambre** [comment]
Thank you for your answer, I didn't try turning this setting on as the help doc says it's on by default.
I tried doing
```
nvim -u NORC -c "set equalalways | vs | windo sp" -c "sp | wincmd J | close" 
```
It didn't work, the behaviour is the same as described in my first message. Am I doing something wrong?

**Comment by justinmk** [comment]
Thanks for the repro! That does seem like a regression. Vim 8.0.567 also has the same behavior.
