### ISSUE TITLE
can I develop plugins for neovim in c/cpp

### ISSUE THREAD

**Issue by oskarz1234** [neovim/neovim#6749]
Is there any way that i can make a plugin for nvim in c/cpp

**Comment by justinmk** [comment]
Yes, see https://github.com/neovim/neovim/wiki/Related-projects . Use the projects there as reference implementations.

However, there is not yet a "host" for c/cpp which will automatically discover c/cpp plugins. Compare the [go-client](https://github.com/neovim/go-client) which does support discovery of go plugins.
