### ISSUE TITLE
segmentation fault, :function print

### ISSUE THREAD

**Issue by bounceme** [neovim/neovim#6750]
https://github.com/pangloss/vim-javascript/issues/950

and the fix
https://github.com/pangloss/vim-javascript/pull/952/files

**Comment by jamessan** [comment]
Why does nvim crashing need a fix in the runtime files?

Also, I'm curious about https://github.com/pangloss/vim-javascript/pull/949#issuecomment-301378726 in terms of the incompatibilities you noted.

**Comment by bounceme** [comment]
this is unrelated to the runtime files, it is just a possibly reproducible segfault.

actually this incompatibility is also present in vim8.0
```
echom matchstr(" sdfsfsf\n sfdsdfsdf",'[^\n]*')
" sdfsdf (nvim,vim8.596)
"  sdfsfsf^@ sfdsdfsdf (vim7.4.898)
```

**Comment by justinmk** [comment]
`0verbose function Foo` works for me. Without a repro can't do anything with this.
