### ISSUE TITLE
mintty TUI

### ISSUE THREAD

**Issue by ahirschberg** [neovim/neovim#6751]
- `nvim --version`: NVIM v0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 09:05:56)`
- Operating system/version: Windows 7 x64
- Terminal name/version: Git Bash `version 4.4.12(1)-release (x86_64-pc-msys)`
- `$TERM`: xterm

### Actual behaviour
Running nvim from git bash yields the following:
```
Alex@XXXXXX MINGW64 ~
$ nvim
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...

Vim: Finished.

Alex@XXXXXX MINGW64 ~
$
```
The vim UI flashes on the screen for a split-second, then the above is shown and control is returned to the shell

### Expected behaviour
Nvim should open. Interestingly, `nvim` works correctly from cmd.exe. Vim works correctly from both.

### Steps to reproduce using `nvim -u NORC`

In git bash on Windows 7:
```
nvim -u NORC
```

**Comment by justinmk** [comment]
You can't run the win32 version in msys.

> Vim works correctly from both.

Is the absolute path to `vim` the same in both cases? I would guess no.

**Comment by justinmk** [comment]
`vim` is shipped with GFW and  it probably appears earlier in the $PATH than the win32 vim.

**Comment by janlazo** [comment]
if user logins in for git-bash, then the error happens.
If the user runs the shell only (sh.exe or bash.exe) or runs git-cmd.exe, then nvim TUI runs.

**Comment by justinmk** [comment]
Still waiting for answers to my above questions.

**Comment by bimlas** [comment]
Both works for me.

Tried out opening Git Bash (`git version 2.12.2.windows.2`, x64), then

```
# VIM 8.0.0567 x86
$ /c/app/vim/vim80/vim.exe
# NVIM v0.2.1-190-g53d93210 x86
$ /c/app/neovim/bin/nvim.exe
```

Maybe it's an alias instead of Neovim itself? I think because of the `Vim:` prefix in the messages.

**Comment by ahirschberg** [comment]
@justinmk I don't have vim explicitly on my %PATH%, so in cmd I have to fully qualify it to `"C:\Program Files\Git\usr\bin\vim.exe"`. However, it still runs properly. The vim I'm using is provided by git bash. Not sure if that answers your questions.

I think nvim is compiled 64 bit :
```
AlexH@A22102AlexH MINGW64 /usr/bin
$ nvim --version
NVIM v0.2.1-25-g2e3b78d1
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

Neovim path (added to %PATH% in windows)
```
Alex@XXXXXX MINGW64 /usr/bin
$ which nvim
/c/Users/alex/Documents/Neovim/bin/nvim
```

According to the git-bash properties, it's at version `2.12.2.windows.2`

**Comment by justinmk** [comment]
> don't have vim explicitly on my %PATH%, so in cmd I have to fully qualify it to "C:\Program Files\Git\usr\bin\vim.exe". However, it still runs properly

"In cmd" means in mintty?

**Comment by ahirschberg** [comment]
Cmd as in cmd.exe

**Comment by justinmk** [comment]
Ok, again, that's not the same thing. Try "C:\Program Files\Git\usr\bin\vim.exe" in git bash,  I.e. the same place where nvim has the reported issue.

**Comment by ahirschberg** [comment]
`/c/Program\ Files/Git/usr/bin/vim` works properly. That is expected, as git-bash just mounts its Program Files install folder as `/` in the simulated bash environment.

**Comment by justinmk** [comment]
@ahirschberg Sorry, I didn't realize that "Git" was in the absolute path you mentioned. You are comparing the git bash version of Vim to the win32 version of Nvim. What I would like to know is if the win32 version of Vim works in git bash. It's not surprising that the git bash version of Vim works in git bash.

So please, try the absolute path to the _win32_ version of Vim. Not the version of Vim that ships with git bash.

**Comment by bimlas** [comment]
As I know, running native Windows programs on Msys is possible; `cmd.exe` or even `notepad.exe` from Git-Bash works for example.

I tried out 64 and 32 bit versions of Neovim on Windows 7 x64 in Git Bash, Git-Cmd and plain bash.exe and it always worked. 

To be correct, I copied it to *c:\app\nvim\* instead of *c:\Program Files (x86)\nvim\* and it dropped this error message when I tried to run (from Git Bash too):

```
$ nvim -u NORC
E484: Can't open file C:/Program Files (x86)/nvim/share/nvim\syntax\syntax.vim
Press ENTER or type command to continue
```

Pressing enter did nothing, the terminal did not respond. Then I tried out with `-u NONE` flag and it worked. As I found in the documentation (`:help -u`):

```
		When {vimrc} is equal to "NORC" (all uppercase), this has the
		same effect as "NONE", but plugins and syntax highlighting are
		not skipped.
```
It seems that this path is hard coded, because copying *c:\app\nvim\share\* to *c:\Program Files (x86)\nvim\share\* solved the problem.

So back to the topic: @ahirschberg, can you try with `-u NONE` flag too (your path is `/c/Users/alex/Documents/Neovim/bin/nvim` as you [wrote above](https://github.com/neovim/neovim/issues/6751#issuecomment-301781527))? And to response to @janlazo's [comment](https://github.com/neovim/neovim/issues/6751#issuecomment-301662089), how do you starting Git Bash?

**Comment by ahirschberg** [comment]
I see, I didn't realize you meant the actual ViM windows installation. I actually don't currently have it installed, but I'll go ahead and install it and let you know.

I'm positive that my Neovim installation is x64, or at least the windows x64 build on their downloads page [here](https://github.com/neovim/neovim/wiki/Installing-Neovim). I just redownloaded it to verify.

**Comment by ahirschberg** [comment]
Vim.exe version output (from the gvim80 installer package on vim.org):
```$ /c/Program\ Files\ \(x86\)/Vim/vim80/vim.exe --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 19:48:19)
MS-Windows 32-bit console version
Included patches: 1-586
Compiled by mool@tororo
Huge version without GUI.  Features included (+) or not (-):
+acl             +ex_extra        -mouseshape      +tag_old_static
+arabic          +extra_search    +multi_byte      -tag_any_white
+autocmd         +farsi           +multi_lang      -tcl
-balloon_eval    +file_in_path    -mzscheme        +termguicolors
-browse          +find_in_path    -netbeans_intg   -tgetent
++builtin_terms  +float           +num64           -termresponse
+byte_offset     +folding         +packages        +textobjects
+channel         -footer          +path_extra      +timers
+cindent         +gettext/dyn     -perl            +title
+clientserver    -hangul_input    +persistent_undo -toolbar
+clipboard       +iconv/dyn       -postscript      +user_commands
+cmdline_compl   +insert_expand   +printer         +vertsplit
+cmdline_hist    +job             +profile         +virtualedit
+cmdline_info    +jumplist        -python          +visual
+comments        +keymap          -python3         +visualextra
+conceal         +lambda          +quickfix        +viminfo
+cryptv          +langmap         +reltime         +vreplace
+cscope          +libcall         +rightleft       +wildignore
+cursorbind      +linebreak       -ruby            +wildmenu
+cursorshape     +lispindent      +scrollbind      +windows
+dialog_con      +listcmds        +signs           +writebackup
+diff            +localmap        +smartindent     -xfontset
+digraphs        -lua             +startuptime     -xim
-dnd             +menu            +statusline      -xpm_w32
-ebcdic          +mksession       -sun_workshop    -xterm_save
+emacs_tags      +modify_fname    +syntax
+eval            +mouse           +tag_binary
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjCi386/ /Ox /GL -DNDEBUG  /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_HUGE /Fd.\ObjCi386/ /Zi
Linking: link /RELEASE /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386  /nodefaultlib libcmt.lib  user32.lib          WSock32.lib  /PDB:vim.pdb -debug
```

And git bash output:
```
$/c/Program\ Files\ \(x86\)/Vim/vim80/vim.exe
Vim: Error: This version of Vim does not run in a Cygwin terminal
```

So this one is 32 bit, and detects that it doesn't run in Cygwin. Interesting

**Comment by ahirschberg** [comment]
@bimlas :
Running with `-u NONE` gives the same output:
```
$ /c/Users/alex/Documents/Neovim/bin/nvim -u NONE
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...

Vim: Finished.
```
I am starting git bash from the start menu, which is a shortcut to the `git-bash.exe` file in git's program files folder.

Also, here's some interesting console output when starting with cmd.exe, running git bash from there, and running nvim within git bash: [https://hastebin.com/iyiwivifab](https://hastebin.com/iyiwivifab). It seems to segfault frequently on `:q`

**Comment by justinmk** [comment]
"Output is not to a terminal" means that nvim thinks the current streams are not TTY streams. On Windows that is determined by the win32 API function `GetConsoleMode()`. That [won't work] with mintty.

There is a way to [detect mintty](https://github.com/mintty/mintty/issues/482#issuecomment-265844179) (from Vim, incidentally, but there's also a [git patch mentioned here](https://github.com/BurntSushi/ripgrep/issues/94#issuecomment-261745480)). But I'm not sure our current TUI will work since the libuv tty stream is expecting the standard win32 Console API. (@equalsraf does that sound right?)

However it might [just work](https://github.com/BurntSushi/ripgrep/issues/117#issuecomment-261741511) if we emit ANSI escape codes if mintty is detected. Would be easy to try.

This [ripgrep thread](https://github.com/BurntSushi/ripgrep/issues/94#issuecomment-261745480) has good info.

This could be a straightforward task if someone wants to work on it:

1. Port the [vim](https://github.com/mintty/mintty/issues/482#issuecomment-265844179) or [git](https://github.com/BurntSushi/ripgrep/issues/94#issuecomment-261745480) hack to detect a mintty TTY.
2. Modify `os_isatty` to try that method if `uv_guess_handle` returns false.
3. Modify `term_input_init` to use `rstream_init_fd` (I think? cc @equalsraf)

> Git Bash, Git-Cmd and plain bash.exe and it always worked.

Are you using mintty? I don't see how that's possible. IIRC bash.exe launches cmd.exe. Not sure what you mean by "Git Bash", it could be the old cmd.exe-based terminal or the new mintty one.

**Comment by janlazo** [comment]
@justinmk Yes. I have git-bash.exe in C:\Program Files\Git. I click it in explorer.exe and the terminal title is `/usr/bin/bash --login -i`. `TERM` and `SHELL` are set and the TUI is mintty.exe.

@bimlas You can click sh.exe, or bash.exe in the bin/ subdirectory of the GFW install folder to run them inside cmd.exe. You can use git-cmd.exe and, from its root directory, run either `.\bin\bash.exe --login -i` or `.\usr\bin\bash.exe --login -i` to run bash.exe. nvim TUI works because, underneath, it's cmd.exe TUI.

**Comment by mmikeww** [comment]
Git ships its own version of Vim in Git's own subdirectory and uses that in git bash

**Comment by bimlas** [comment]
@justinmk, @janlazo: I disabled Mintty on GFW installation, so it's using native Windows terminal.

**Comment by jeffgreenca** [comment]
@justinmk I did a quick mock implementation, following your 3 step sketch, and there must be more to it than using rstream_init_fd.  

After I hard code ```os_isatty``` and ```term_input_init``` to work with mintty, when I launch my build via git-bash, the TUI doesn't load, cursor just waits until I CTRL-C to terminate.

```
jeff@laptop MINGW64 ~/Documents/GitHub/neovim
$ ./build/bin/nvim.exe -u NONE

CTRL-C
```

I'd be happy to help but need some guidance about how to code the ```term_input_init``` function to work with mintty.

**Comment by erw7** [comment]
I think that in step 3 we also need to change it to use `uv_pipe_init` with `terminfo_start`.  With that change, [my branch](https://github.com/erw7/neovim/tree/feature-work-with-mintty) succeeded to run Windows native nvim in mintty using the following wrapper script.

```bash
#!/usr/bin/bash

export COLUMNS=$(tput cols)
export LINES=$(tput lines)
restore_termios=$(stty --save)
stty -ixon -inlcr -icrnl -icanon -echo -iexten -isig
nvim.exe $*
stty $restore_termios
```

But I think that this change is not necessary for the following reasons.

- As written in the [Git for Windows FAQ](https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it), we can run console programs like nvim on mitty by using winpty.
- Now that we can compile nvim on Cygwin, we can now create nvim linking `msys-2.0.dll`.
- As far as the [source code](https://github.com/vim/vim/blob/0bd052ba12f672b46415ed1d5d1d2597a326f85a/src/main.c#L2559) is concerned, Windows native vim will not work with mintty.

**Comment by justinmk** [comment]
@erw7 great info! So we should just show a warning and exit.

**Comment by justinmk** [comment]
@erw7 would you be willing to take over https://github.com/neovim/neovim/pull/7660 ? Mostly just need someone to test that it works, and make a small change like this:

```
if msys_tty_on_handle(...) {
    // show a message and exit
}
```

**Comment by justinmk** [comment]
@erw7 , @Marwes  said they did not have time to continue working on the PR.

> And I think that terminal mode will not be switched even if we change termios internally, without tcsetattr().

Can't we use `tcsetattr()` ?

**Comment by Marwes** [comment]
Yeah, go ahead. This is not really my are so it would take quite a while for me to get anywhere.

**Comment by erw7** [comment]
I succeeded in running Windows native nvim on mintty, by dynamic linking cygwin1.dll or msys-2.0.dll  without wrapper script. There are still many problems. But after cleanup the code, I would like to take over #7660 and create a pull request.

**Comment by erw7** [comment]
I have created a #8271.

**Comment by erw7** [comment]
Cygwin has been using `ConPTY` since version 3.1. The latest version of `msys2-runtime` is also based on Cygwin 3.1.4. Now, Windows native `nvim` runs on `mintty`. Some day Git for Windows will also be based on Cygwin 3.1.

Note: Since the use of `ConPTY` is not the default in MSYS2, you need to `set MSYS=enable_pcon`.

**Comment by chrisbra** [comment]
FWIW: The latest [git-for-windows snapshot 2.27.0-rc1](https://github.com/git-for-windows/git/releases/tag/v2.27.0-rc1.windows.1) already includes this change as experimental feature

**Comment by LeonT-A** [comment]
> Note: Since the use of `ConPTY` is not the default in MSYS2, you need to `set MSYS=enable_pcon`.

Thank you! 

I was already using a .bat to launch git-bash.exe with a custom `HOME` variable, and adding the `MSYS` variable before launching git-bash.exe allowed me to run nvim. I'm very new to nvim and only use the vanilla settings, so I'm not sure how it'll hold up when adding plugins.

OS: Windows 10 v2004
Git-Bash: PortableGit-2.28.0-64-bit
NeoVim: 0.4.3

**Comment by justinmk** [comment]
> Now, Windows native `nvim` runs on `mintty`. Some day Git for Windows will also be based on Cygwin 3.1.

So we can close this? Do we need to any update documentation to mention `set MSYS=enable_pcon`?

**Comment by BladeMight** [comment]
> Now, Windows native nvim runs on mintty

Can't seem to get that behavior, running `nvim` in my case gives(msys2) nothing:


<details>
<summary>Info</summary>

```sh
$ mintty --version
mintty 3.4.4 (x86_64-pc-msys)
$ ./nvim --version
NVIM v0.5.0-dev+1062-gcc1851c9f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-378

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

```

</details>

setting `set MSYS=enable_pcon` doesn't do any changes.... [demo-gif](https://i.imgur.com/5dWzwJH.gif)

**Comment by erw7** [comment]
@BladeMight Perhaps your version of Windows does not meet the requirements. `ConPTY` was implemented in the Windows 10 "October 2018 Update". Therefore, earlier versions of Windows still require `winpty` in order to run Windows native `nvim` on `minntty`.

**Comment by BladeMight** [comment]
@erw7 Thanks for pointing out to the `winpty`, through it nvim works now in mintty. And one thing is strange: I have Windows version 1909, which should have that "October 2018 Update" as well... and still it didn't work.

**Comment by erw7** [comment]
@BladeMight Sorry, I did not see your deom-gif. You will need to set `enable_pcon` to the `MSYS` environment variable before running `mintty`. Change `c:\msys64` to match your environment and try running it as follows:

```
c:\msys64\usr\bin\env MSYS=enable_pcon /usr/bin/mintty
```

**Comment by BladeMight** [comment]
@erw7 Starting mintty that way makes nvim to *consume* keyboard input, I can now quit using `:q`(tho its not displayed in mintty), but mintty still not displaying anything...

**Comment by Freed-Wu** [comment]
Can neovim support Msys2 or Cygwin? Now it cannot be installed by msys's pacman or cygwin's apt-cyg, even if it is installed, it cannot work in mintty, like <https://github.com/neovim/neovim/issues/11112>.

**Comment by LunarLambda** [comment]
What is the current state of this? Does it work? Not work? Is it being worked on?

**Comment by justinmk** [comment]
# Status

Based on the above reports, `nvim` does run in mintty.

The remaining issue is that we need to detect this and set 'shell' and related options defaults correctly:

> running `nvim` from Git Bash on a Windows 10 machine. The `nvim` editor functions normally and can read plugins correctly. However, it also starts in ex mode with a garbage search (`:/1818/1818/1818`). More importantly, running shell commands from `nvim` with ! returns `/usr/bin/bash: /s: No such file or directory`
> ... running `:checkhealth` reveals `/usr/bin/bash: /s: No such file or directory`

**Comment by LunarLambda** [comment]
I tried it, it seems to work fine. Didn't try anything fanciful yet but editing files works fine.

Although suspending with Ctrl-Z seems to hang the editor.

**Comment by justinmk** [comment]
@LunarLambda thanks for testing, does that mean 'shell' is also correctly set to bash? Does `:!ls` work?

> Although suspending with Ctrl-Z seems to hang the editor.

https://github.com/neovim/neovim/issues/6660

**Comment by LunarLambda** [comment]
`shell` gets set to the windows path to the shell I use in msys (which is zsh)

`:!ls` throws a weird error ("can't open input file /s")

Same Ctrl-Z hang when using bash, though

**Comment by justinmk** [comment]
> Although suspending with Ctrl-Z seems to hang the editor.

Fixed in https://github.com/neovim/neovim/pull/20523

> `:!ls` throws a weird error with both bash and zsh ("can't open input file /s")

This remaining issue is covered by https://github.com/neovim/neovim/issues/16957

So we can close this, since the Nvim TUI is otherwise working in mintty. 🎉
