### ISSUE TITLE
Symantec quarantined "nvim.exe" with threat warning "WS.Reputation.1"

### ISSUE THREAD

**Issue by papesch** [neovim/neovim#6752]
- `nvim --version`: 
NVIM v0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? 
I have vim 8 installed on my system (C:\Program Files\vim\) and it does not have this problem
- Operating system/version: 
windows 7 pro, 32 bit
- Terminal name/version: 
using nvim-qt.exe on windows
- `$TERM`: n/a

### Actual behaviour
1 downloaded nvim-win32.zip 
2 unzipped to "D:\apps\Neovim"
3 navigated to "D:\apps\Neovim\bin" in windows explorer
4 double clicked nvim-qt.exe
5 error message "The Neovim process has crashed [Retry]"
6 Symantec Endpoint Protection Notification dialog appeared. It has decided to quarantine the file "nvim.exe" as a security risk called "WS.Reputation.1"
7 dismissed the Symantec message
8 clicked [Retry] on the Neovim message
9 a Neovim window appears with no contents

### Expected behaviour
a. should not trigger any virus scanners
b. if the nvim.exe file gets quarantined or crashes then perhaps nvim-qt.exe should just exit. Retry does nothing in this case.
c. would be nice if nvim-qt.exe wrote something to a log (or notified the user) when a fatal error like this occurs

### Steps to reproduce using `nvim -u NORC`
Restored the file "nvim.exe" from quarantine and NeoVim now runs correctly from both terminal (cmd.exe) and GUI (nvim-qt.exe)

### Screenshots
![image](https://cloud.githubusercontent.com/assets/16142896/26088600/3d9a4578-3a4c-11e7-9a53-dd01040e6d36.png)
![image](https://cloud.githubusercontent.com/assets/16142896/26088620/4d4e2d5e-3a4c-11e7-9789-0d7a4449f02c.png)

**Comment by FSMaxB** [comment]
It looks like Symantec essentially doesn't like new files that aren't widespread (because not many clients have automatically sent it in as a sample or something), see [here](https://community.norton.com/en/forums/clarification-wsreputation1-detection).

I doubt that neovim can do anything about it except explicitly report all false detections to Symantec and hoping for them to fix it.

**Comment by papesch** [comment]
OK, I've submitted a report to Symantec. I hope other people getting this error will do the same.
https://submit.symantec.com/false_positive/standard/

**Comment by papesch** [comment]
Email received from Symantec:

> In relation to submission 32285.
>
>Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:
>```
>    File name: nvim.exe
>    MD5: 54fb87d450672cbed66b95f9deeda901
>    SHA256: f5487c4dd1cb9ff8f8d68f5c55f947a3dc5a0611268fbb31d03e58a0b1b58478
>    Note: Whitelisting may take up to 24 hours to take effect via Live Update
>```
:smile:

**Comment by justinmk** [comment]
@papesch Thanks for doing that! We have plans to sign the package to avoid this: https://github.com/neovim/neovim/issues/5433 No idea when that will happen though.
