### ISSUE TITLE
Neovim changes shape of cursor from default terminal settings.

### ISSUE THREAD

**Issue by Dark-Passenger** [neovim/neovim#6753]
- `nvim --version`:0.2
- Vim (version: ) behaves differently? yes
- Operating system/version: centos 7
- Terminal name/version: tilix 1.5.6(https://github.com/gnunn1/tilix)
- `$TERM`: xterm-256color

### Actual behaviour
cursor shape changes to block size. in normal mode and is line in insert mode.
### Expected behaviour
cursor should not change.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Note : after this version upgrade esckeys setting too doesnt work(unknown option) is it related ?

**Comment by teto** [comment]
Yopu can do "set guicursor=" to disable that behavior. See https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by Dark-Passenger** [comment]
awesome thanks. Guess I should be reading stuff.
Another thing set esckeys doesnt seem to be working ... I couldnt find that though. any reason ...

**Comment by justinmk** [comment]
esckeys isn't supported, it's always "enabled". If you're having problems with Fn or arrow keys make sure `$TERM` is correct and check open issues.
