### ISSUE TITLE
Async jobs breaking commands

### ISSUE THREAD

**Issue by miguelbacalhau** [neovim/neovim#6754]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently? yes
- Operating system/version: Ubuntu 16.10
- Terminal name/version: st(with tmux), gnome-terminal
- `$TERM`: screen-256color(st with tmux), xterm-256color(gnome-terminal)

### Actual behaviour
Not sure what is causing this but it seems related to the async feature.

I noticed the problem while using the [w0rp/ale](https://github.com/w0rp/ale) plugin.

Whenever I enter a `dd` command to delete a line if in between the pressing of the first and second `d` ale runs then the line is deleted right after the first `d` this causes weird behavior. It might be happening in other scenarios but this one is the most noticeable for me.

### Expected behaviour
Commands should not be affected by background stuff.

Whenever I press `dd` should delete the line on the second `d` press even when ale runs in between.

The issue does not happen on vim 8.

### Steps to reproduce
**Don't know how to reproduce without ale.**

Install the ale plugin.
Use the php file below.
Move the cursor to the line with the `if`.
Press `d` 3 times.
Two line are deleted while only one should be.

```php
<?php

namespace A\B;

class One
{

    public function test($a)
    {
        if ($a) {
            echo $a;
        }

        return $a;
    }
}

```

**Comment by justinmk** [comment]
Thanks for the report, this is a known issue. https://github.com/neovim/neovim/issues/6166
