### ISSUE TITLE
Behavior of `:terminal` with no `{cmd}` is undocumented

### ISSUE THREAD

**Issue by nelstrom** [neovim/neovim#6756]
- `nvim --version`: v0.2.1-188-g597d65b4
- Operating system/version: Mac OS 10.12.4
- Terminal name/version: iTerm 3.0.15
- `$TERM`: xterm-256color

### Actual behaviour

[`:help :terminal`](https://neovim.io/doc/user/various.html#%3Aterminal) only documents the `:terminal {cmd}` form of the command. There's no description of what happens when running `:terminal` with no arguments.

### Expected behaviour

The documentation should describe both forms: `:terminal` and `:terminal {cmd}`.

For reference, the `:edit` command comes in various forms, each of which has its own helptag:

* [`:help :edit`](https://neovim.io/doc/user/editing.html#%3Aedit)
* [`:help :edit!`](https://neovim.io/doc/user/editing.html#%3Aedit%21)
* [`:help :edit_f`](https://neovim.io/doc/user/editing.html#%3Aedit%21_f)
* etc...

Following this convention, it might make sense to have separate entries for `:help :terminal` and `:help :terminal_c`. I'm not convinced that it's worthwhile creating separate entries for the versions of the command with and without a `!`

**Comment by justinmk** [comment]
`:edit` has quite different behavior than `:edit {file}`. Separate entries can be really confusing for users, no user ever looks up `:help :edit_f`. And that's why almost no one knows about `:file {cmd}`: it's hidden 1 page below the description of `:help :file`.

**Comment by nelstrom** [comment]
Fair point. (And to prove your point, I didn't know about `:file {name}` until you told me about it!)

**Comment by ZyX-I** [comment]
@justinmk Not actually different: `:edit`, `:edit %` and `:execute 'edit' fnameescape(expand('%:p'))` do quite the same thing.
