### ISSUE TITLE
TextChangedI when pumvisible

### ISSUE THREAD

**Issue by prabirshrestha** [neovim/neovim#6758]
(copy from https://github.com/vim/vim/issues/1691. No reply for more than a week so cross posting it in neovim)

Currently `TextChangedI` isn't triggered when the popup menu is visible. This means all autocomplete plugins have to use timer based hacks.
Would it be possible to have a new event something like `TextChangedIEx` which is triggered regardless of popup menu being visible or not? This way I could use timer as fallback instead in [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim). All other async completion plugins - [completor.vim](https://github.com/maralla/completor.vim), [deoplete](https://github.com/Shougo/deoplete.nvim), [ncm](https://github.com/roxma/nvim-completion-manager) also seems to use timer based hacks.
I'm also writing a [language server plugin for vim](https://github.com/prabirshrestha/vim-lsp) and see a use case here to detect text document changes.

//cc @Shougo @roxma

**Comment by chrisbra** [comment]
there was:
https://groups.google.com/d/msg/vim_dev/DrDYKWUeHVY/7WbPrVVZCAAJ

**Comment by prabirshrestha** [comment]
Awesome. Some how I seem to have missed the email notifications from google groups.

**Comment by prabirshrestha** [comment]
We now have TextChangedP in both vim and neovim.
