### ISSUE TITLE
less.sh, less.vim ctl seqs

### ISSUE THREAD

**Issue by crocket** [neovim/neovim#6762]
`/usr/bin/nvimpager` is a symlink to `/usr/share/nvim/runtime/macros/less.sh`

- `nvim --version`:

```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/config -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/include
Compiled by root@gentoo

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version: GentooLinux
- Terminal name/version: st-0.7
- `$TERM`: `screen` because I run tmux on st

### Actual behaviour

TTY-37 control sequences are shown verbatim in nvimpager when I execute `man less`. This is what I get.

![2017-05-19_fri_02 52 42](https://cloud.githubusercontent.com/assets/748856/26231364/c313e332-3c89-11e7-9b3c-7f577f9790ed.png)

### Expected behaviour

TTY-37 control sequences should be processed properly.

### Steps to reproduce

```
PAGER=nvimpager man less
```

**Comment by jdebp** [comment]
These are not ANSI escape codes.  For starters, there is not a single escape character in that screenshot.

These are the control sequences that were understood by Model 37 Teletypes.  They are not ANSI-_anything_.

A small subset of the TTY-37 control sequences is understood by `more` and `less`, in a very limited way.  A more complete set is understood by [the `ul` filter](http://jdebp.eu./Proposals/ul-manual-page.html).

**Comment by crocket** [comment]
I didn't know well about ANSI escape codes. How can I make nvimpager understand TTY-37 control sequences?

**Comment by justinmk** [comment]
@crocket If you're only using this for man pages, try the snippet from `:help man.vim`:

    export MANPAGER="nvim -c 'set ft=man' -"

man.vim has seen a lot of attention in Nvim. Whereas `less.sh` and `less.vim` are essentially unused.

**Comment by crocket** [comment]
`MANPAGER="nvim -c 'set ft=man' -"` is acceptable but needs more attention, too.

man less

![2017-05-20_sat_02 53 13](https://cloud.githubusercontent.com/assets/748856/26272441/13fb9ea6-3d53-11e7-8bbd-a7bef370830e.png)

MANPAGER="nvim -c 'set ft=man' -" man less

![2017-05-20_sat_02 53 50](https://cloud.githubusercontent.com/assets/748856/26272443/1cf837a8-3d53-11e7-8c91-4e2052064749.png)

**Comment by jdebp** [comment]
Off the top of my head: one way to make `less.vim` work would be to have it filter the input through `ul` within a `:terminal`.

**Comment by jdebp** [comment]
But personally I take the approach of [switching my manual system from the TTY-37 control sequences from 1968 to the the ECMA-48 control sequences of 1976](http://jdebp.eu./Softwares/nosh/italics-in-manuals.html), allowing me to see true boldface and italics in my manual pages, as is there in the original source documents, rather than underlines and blue.  (-:

Additionally, and for what it is worth, when dragged kicking and screaming forward into the 1970s, the manual system displays real boldface and italics inside an nvim `:terminal` (when the terminal that nvim is outputting to itself supports boldface and italics, of course).

**Comment by boojum** [comment]
`less.sh` can handle ANSI escape sequences with @powerman's imporoved version of `AnsiEsc.vim`, which can be found [here](https://github.com/powerman/vim-plugin-AnsiEsc). Perhaps it could be assimilated into `less.vim`?

**Comment by justinmk** [comment]
`MANPAGER="nvim -c 'set ft=man' -"` handles SGR sequences since  https://github.com/neovim/neovim/pull/7623 .
