### ISSUE TITLE
:set termcap displays nothing, contrary to the doco

### ISSUE THREAD

**Issue by jdebp** [neovim/neovim#6763]
In vim, `:set termcap` prints the termcap settings, as documented (`term.txt` section 2).

It does nothing in nvim.

**Comment by fmoralesc** [comment]
Actually, nvim does not support the `t_XX` settings, so that is to be expected. See `:help termcap-options`. `term.txt` doesn't mention `set termcap`, unless you are cross-checking with vim's documentation, which doesn't apply anyway.

**Comment by jdebp** [comment]
Gah!  It does if one accidentally picks up version 0.1.7 from ports instead of version 0.2 .

Nonetheless, doing _nothing_ for the `termcap` option seems questionable, given that (say) `:set wibble` yields `Unknown option: wibble`.

**Comment by fmoralesc** [comment]
Agree on that last point, although failing silently is not so bad, given that the (lack of) output is at least accurate (there are no values for the `t_XX` settings). Maybe it was kept for compatibility reasons (no idea)?
