### ISSUE TITLE
Replace messing with process environment managed by libc with dictionary managed by Neovim

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6765]
The idea came up when discussing #6764:

Python rather then messing with its `char **environ` and various environment-modifying functions holds environment in a dictionary instead, constructing strings for `execve` when needed (do not remember, but it would be completely logical to cache that). Doing so in Neovim will naturally resolve issues with `unlet $environ`, and greatly ease implementation of `jobstart(, {'env': …})` (#4970) (better have something similar for `system()`), `String nvim_environ_get(String)` (also `void …set(String, String)` and `void …del(String)`) and `Dictionary nvim_environ_dump(void)`. That will also allow us to create bash exported (`export -f bashfunc`) functions: after shellshock events environment variable names are `BASH_FUNC_bashfunc%%` and we can only read that after messing with `&isident` which does not look like a good idea and still does not allow to do `let $BASH_FUNC_bashfunc%% = 'smth'`, only `echo $BASH_FUNC_bashfunc%%`.

There may be performance issues instead though which raises a question about implementing caching, but I guess that may be easily resolved with the help of existing dictionary watchers. Also python lives with this problem (if any) somehow.

// BTW, I think I have came up with better names then in #4970.

**Comment by ZyX-I** [comment]
Filtering out environment variables for `:terminal` should be also easier with the facility in question.

**Comment by jdebp** [comment]
This is the approach taken by many programs where there is potentially a lot of user-specifiable manipulation of the environment for an `exec()`ed program, from shells to everything that uses [Bernstein `pathexec_env()`](http://cr.yp.to/lib/pathexec.html).  The downside is that one has to watch internal dependencies within the language runtime library on its own copy of the environment.  They aren't affected by modifications to the application-maintained copy of the environment.  The effects show up in things like locale, message, and time manipulation library functions.

**Comment by ZyX-I** [comment]
@jdebp I see the problem: needs workarounds for lua (`os.getenv`, `io.popen`, third-party). Would have to suggest half-dict solution then: still a dictionary and uv_spawn users will use our own `char **env`, but dictionary callbacks will also update standard in-process environment: I can probably mess up with any lua standard library functions, but there still will be users of non-standard ways of spawning processes and like this due to deficiences of lua standard library.

BTW, also found an interesting thing: C99 we are using defines `getenv` and that’s all. No 3-argument `main()` (argc, argv, environ), no `[un]setenv` or `putenv`, no `extern char **environ`. (Actually there neither are any members of `exec*` function family, but we are using libuv for that.)

**Comment by jdebp** [comment]
All of that comes from other standards.  POSIX, for starters.

**Comment by ZyX-I** [comment]
@jdebp Standards are mentioned in `man setenv` and others. It is just strange nothing is in C99.

**Comment by justinmk** [comment]
This was "partially" implemented in #7920 , see `os/env.c:envmap` . That's more of a cache, but it works mostly as suggested in this ticket. 

> needs workarounds for lua (`os.getenv`, `io.popen`, third-party

Lua case is addressed by #9686.
