### ISSUE TITLE
Is nvim 0.2 in the stable PPA?

### ISSUE THREAD

**Issue by evaryont** [neovim/neovim#6767]
- `nvim --version`: Reports 0.1.7
- Operating system/version: Running in Ubuntu on Windows, 16.04.2 LTS
- Terminal name/version: mintty
- `$TERM`: Linux

I've added the stable PPA using `sudo add-apt-repository ppa:neovim-ppa/stable` as per the wiki, and installed the neovim package. However, the version in both the apt metadata as well as the internal version both state 0.1.7. What I'm confused about is whether this is similar to #6654, and it's actually 0.2.0?

Looking at the upload dates, I suspect not. If so, consider this a request to upload updated .deb packages.

**Comment by justinmk** [comment]
It's being worked on. Thanks for reporting.

**Comment by evaryont** [comment]
Is there anything I can do to help? I noticed that the PPA still hasn't been updated.

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/issues/6794 is likely a blocking issue.  I haven't been able to upload 0.2 to Debian yet because of it and expect to hit the same issue in the PPA.

I've started updating some of the other packages in the PPA, though.
