### ISSUE TITLE
Cursor/Folding misbehaves when evaluating 'foldexpr' with terminal activity

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#6769]
- `nvim --version`: v0.2.1-dev 20170515
- Vim (version: ) behaves differently? n/a
- Operating system/version: Ubuntu 16.04
- Terminal name/version: 
- `$TERM`:

### Actual behaviour
The cursor jumps to another position without being commanded.
### Expected behaviour
The cursor should stay where it was been placed.
### Steps to reproduce using `nvim -u NORC`

1. Clone https://github.com/tpope/vim-markdown to `~/.vim/bundle/vim-markdown`.
1. Download the test file [foo.md][1].
1. `nvim -u NORC --cmd 'set rtp+=~/.vim/bundle/vim-markdown|let g:markdown_folding = 1' +'term top' +'e + foo.md'`.
1. Exit Insert Mode and wait several seconds.

[1]:https://gist.githubusercontent.com/bohrshaw/74d4744948bba8d8774005437c483bb6/raw/99a2fab3f2943445d07a907c8712f4eec80cfa91/foo.md

**Comment by bohrshaw** [comment]
Also, probably due to this bug, closed markdown foldings would be expanded sometimes.

**Comment by justinmk** [comment]
I can reproduce with the standard markdown ftplugin.

    nvim -u NORC --cmd 'let g:markdown_folding = 1' +'term top' +'e https://gist.githubusercontent.com/bohrshaw/74d4744948bba8d8774005437c483bb6/raw/99a2fab3f2943445d07a907c8712f4eec80cfa91/foo.md'

**Comment by bohrshaw** [comment]
This issue should be given a high priority.

Almost all my custom foldings are now opening/closing randomly when I use `:terminal` as a shell extensively, especially if a `foldexpr` is defined like this in a `modeline`:

    " vim:foldmethod=expr foldexpr=getline(v\:lnum)=~'{{{$'?'a1'\:getline(v\:lnum)=~'}}}$'?'s1'\:getline(v\:lnum)=~#'\\v^(\ \ )\?(if|fu)'?'a1'\:getline(v\:lnum)=~#'\\v^(\ \ )\?end'?'s1'\:'=':

**Comment by phodge** [comment]
I've noticed that a hidden `:term top` window causes the command-line display to be cleared every couple of seconds. E.g., if you use `:echo g:markdown_folding` to see the value of the global variable, it gets blanked out very quickly. _But_ this bug only occurs if you only have a single window.

**Comment by zeertzjq** [comment]
Does this bug still exist?
