### ISSUE TITLE
nvim.1 manual page installed to the wrong place

### ISSUE THREAD

**Issue by jdebp** [neovim/neovim#6771]
On FreeBSD `make install` places the manual at `/usr/local/share/man/man1/nvim.1`.

The correct location, per [hier(7)](https://freebsd.org/cgi/man.cgi?query=hier&sektion=7), is `/usr/local/man/man1/nvim.1` .

**Comment by justinmk** [comment]
seems to be driven by `CMAKE_INSTALL_MANDIR` though I don't see where that is set, nor do I see cmake documentation about it.

**Comment by jdebp** [comment]
Perhaps you can make something of [the GNUInstallDirs doco](https://cmake.org/cmake/help/v3.8/module/GNUInstallDirs.html).

**Comment by justinmk** [comment]
@jdebp Thanks, yes it documents `CMAKE_INSTALL_MANDIR` => `DATAROOTDIR/man`. `DATAROOTDIR` is read-only, but `CMAKE_INSTALL_MANDIR` may be settable.

**Comment by jdebp** [comment]
The `man` command does not look there for manual pages, yes.

**Comment by jdebp** [comment]
I have been building 0.2 directly from source.

Looking at how version 0.1 is built in ports, [I find that this variable is set differently](https://svnweb.freebsd.org/ports/head/editors/neovim/Makefile?revision=428479&view=markup#l28)
```
CMAKE_ARGS=  -DLUA_PRG:FILEPATH="${LUA_CMD}"  \
  -DCMAKE_INSTALL_MANDIR:PATH="${MANPREFIX}/man" \
  -DDEPS_PREFIX:PATH="${LOCALBASE}"
```

Also, the FreeBSD port maintainers [think that your compiler flags are wrong](https://svnweb.freebsd.org/ports/head/editors/neovim/files/patch-CMakeLists.txt?revision=425833&view=markup&pathrev=428479#l7) and that [you have forgotten about DragonFly BSD](https://svnweb.freebsd.org/ports/head/editors/neovim/files/patch-src_nvim_os_pty__process__unix.c?revision=425833&view=markup&pathrev=428479#l8).

**Comment by justinmk** [comment]
Thanks for pointing those changes out. We never received those patches, nor any report until now. I'll send a PR shortly.

> you have forgotten about DragonFly BSD.

That tends to happen when the 1000s of distros in the world define random symbols :)

**Comment by justinmk** [comment]
@jdebp So will $MANPREFIX do the right thing for you? (I'm surprised cmake doesn't use this automatically...")

**Comment by justinmk** [comment]
@jdebp can you try #6777

**Comment by jdebp** [comment]
They aren't "distros", and [there are just over 20 macros](http://jdebp.eu./FGA/predefined-macros-platform.html).  I'll undo my local bodges and give it a go.

**Comment by jamessan** [comment]
@jdebp I think Justin's point was that we don't know the intricacies of all the various places that people are going to be using/building Neovim.  We rely on the people that have the domain knowledge we don't have to contribute relevant changes back to us so they can benefit everyone instead of simply fixing thing in their corner of the world.

In my opinion, and experience, as a maintainer for a distribution, that feedback to upstream is one of the most important parts of the role.  It's disappointing to hear of fixes second-hand, especially when they appear to be pretty straight forward.

> @vext01 any reason those changes weren't upstreamed here?

Probably because @vext01 works on the OpenBSD port, but the linked patches are in FreeBSD. :)

> `-DCMAKE_INSTALL_MANDIR:PATH="${MANPREFIX}/man"`

Is `${MANPREFIX}` going to be set in the environment when a user is building from our repo, or is that specific to the ports' makefiles?  Is this variation in paths (`/usr/local/man` vs. `/usr/share/man`) something that should be handled directly in CMake instead of having every (Free?)BSD user/porter remember to change?

**Comment by vext01** [comment]
> Probably because @vext01 works on the OpenBSD port, but the linked patches are in FreeBSD. :)

Indeed. FreeBSD is outside of my area.

I've not encountered this problem on OpenBSD, but the ports tree may be making sure the manuals go in the right place automatically.

FWIW, we also put manuals in `/usr/local/man/...`.

**Comment by justinmk** [comment]
> I've not encountered this problem on OpenBSD, but the ports tree may be making sure the manuals go in the right place automatically.

As I believe @jamessan intimated, I would have expected cmake to deal with this. Maybe cmake on FreeBSD has a bug. Anyways, I need a FreeBSD user to test #6777, we will need to hardcode the path if  MANPREFIX doesn't work. @vext01 BTW is MANPREFIX defined in your env?

**Comment by jamessan** [comment]
Although, I notice now that we're using CMake's GNUInstallDirs module, so that may be steering us in the wrong direction for systems that don't follow GNU conventions.

**Comment by justinmk** [comment]
@jamessan Ah, right. So now I just need an answer about MANPREFIX...

**Comment by vext01** [comment]
I don't see any MANPREFIX in my cmake flags or environment. I've also (quickly) grepped the cmake sources for special handling, but can't seem to find any...

**Comment by justinmk** [comment]
@jdebp https://www.freebsd.org/cgi/man.cgi?query=hier&sektion=7 is confusing. The actual `man` entry in the table is listed under `/usr/share`. But the entry for `local/` says:

> Exceptions are	the man directory	(directly under	local/ rather than under	local/share/)

This doesn't make sense. Is that the line you are referencing?

**Comment by jamessan** [comment]
That's saying `/usr/local` follows the same hierarchy as `/usr`, except that the `man` directory is directly under `/usr/local` instead of under `/usr/local/share`.
