### ISSUE TITLE
Cannot resize panes using mouse or switch back from terminal

### ISSUE THREAD

**Issue by marvel64** [neovim/neovim#6776]
- `nvim --version`: 0.2.0
- Vim (version: ) Not tested
- Operating system/version: macOS 10.12.4
- Terminal name/version: iTerm2 (Build 3.0.15)
- `$TERM`: xterm-256color

### Actual behaviour
After upgrading from nvim v0.1.7 to v0.2.0 via homebrew today, I cannot resize panes using the mouse
anymore nor can I switch away from the terminal emulator pane.

I have not set any mouse options in my `init.vim`.

Thanks!

**Comment by lsrdg** [comment]
About the mouse issue: https://github.com/neovim/neovim/wiki/Following-HEAD#20170403

**Comment by kevlarr** [comment]
This is marked as a duplicate, but is there actually an open issue regarding "mouse resize"? This is still an issue.

**Comment by justinmk** [comment]
:set mouse=a

**Comment by kevlarr** [comment]
Ah forgive me, I had tried that with no luck, but I might have been having an iTerm issue. Click target is very small (much narrower than the pane separation bar) but it *does* work
