### ISSUE TITLE
Cursor is not always restored if Neovim was suspended

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6779]
- `nvim --version`: bde46fdeceec8f9dd675f0e31080d732308573d9
- Terminal name/version: konsole+tmux+two panes

### Steps to reproduce using `nvim -u NORC`

```
# Run tmux with two vertically split panes, cursor in second (rightmost) one.
nvim -u NONE -i NONE --cmd $'function S()\nsuspend\nendfunction' --cmd 'inoremap <expr> X S()' --cmd 'call feedkeys("iX", "t")'
```

### Actual behaviour

Cursor stays being vertical line, perfectly reproducible, but only when using konsole+tmux+two panes and not

- pure konsole
- same tmux session, but another window with only one pane
- if I put `sleep 100m` before `suspend`.

So there is some race condition obviously. Not sure whether it is worth fixing.

### Expected behaviour

Cursor should be a block after suspending Neovim.

**Comment by justinmk** [comment]
> Cursor should be a block after suspending Neovim

Cursor shape isn't queryable so Nvim can't know what to restore it to. See 
 https://github.com/neovim/neovim/issues/4396

**Comment by ZyX-I** [comment]
@justinmk Neovim *does* restore it. Just it does not do so under specific conditions.

**Comment by justinmk** [comment]
Ah, IIRC restore it to block unconditionally.

**Comment by ZyX-I** [comment]
@justinmk Also if you can’t restore it correctly, do not set it by default. This is another argument for making `guicursor` empty by default and do not set or restore anything unless user asked to do this himself.

Though I thought it (should) restores to the cursor from normal mode, not to the block unconditionally.

**Comment by justinmk** [comment]
That is a valid point, but not important enough. Most users aren't using `nvim -u NONE`. For VTE terminals there is a possible solution: https://github.com/neovim/neovim/issues/4396#issuecomment-302945410

**Comment by ZyX-I** [comment]
@justinmk Note that conditions are highly specific: you need tmux *and* two panes *and* suspend shortly after changing shape. Could be uneasy to reproduce on another machine.

---

Many things which are applicable for `-u NONE` are also applicable for new users. E.g. I am using konsole and have configured non-block as a cursor. Wanted to try out Neovim and it messed up my cursor. This may be more important then users that have already set up their configuration.

**Comment by justinmk** [comment]
New users almost certainly will be happy to have mode specific cursor shaping. Let's take a risk here.

**Comment by ZyX-I** [comment]
@justinmk Given that there are nearly zero terminal applications which behave like Neovim by default which makes its behaviour highly unexpected?

**Comment by justinmk** [comment]
Most terminal applications don't bother to use advanced terminal options, users are expected to figure it out. That's the status quo that we should challenge.

For `nvim -u NONE` it might make sense to choose the safe route.

**Comment by justinmk** [comment]
Is this still an issue?

**Comment by rjhornsby** [comment]
running nvim 0.4.4 here, installed via homebrew on macOS

> Is this still an issue?

I think so? I'm hitting the same issue. I run iTerm2 v3.4.3, and have the terminal cursor set to a vertical line, blinking. Exiting nvim normally (as opposed to just suspending) doesn't put the cursor back the way it was, but rather switches the terminal cursor to match nvim - a non-blinking, filled box style. A terminal `reset` will restore the cursor to a line, but the blink is still gone. Close/reopen the terminal window to fix.

Unlike what @ZyX-I found, it doesn't seem limited to tmux, or any other mode/condition AFAICT. The reproduction condition might be more generally iTerm2.

As seen on SO, the workaround is to disable cursor changes with `set guicursor=` in `~/.config/nvim/init.vim` It's not a huge deal and I'm fine leaving my configuration this way, but found #6779 while digging around for info and thought I'd mention the behavior.

**Comment by kyprifog** [comment]
Could this be related to an issue I am seeing where ESC doesn't exit normal mode completely in nvim and I get stuck with "m-2" trying to move lines?

**Comment by zeertzjq** [comment]
Cannot reproduce. The last two comments are unrelated to this issue.
