### ISSUE TITLE
guifont and guioptions should be removed from docs

### ISSUE THREAD

**Issue by mihaifm** [neovim/neovim#6783]
Some gui specific settings were removed from neovim, however they still show up in the documentation.

Also things like `gui_running` still appear in `:help feature-list`

**Comment by justinmk** [comment]
Updated the feature-list and removed gui_running references.

guifont and guioptions are things we plan to restore.

**Comment by wsdjeg** [comment]
hmm, why remove gui_running feature?

**Comment by jamessan** [comment]
> hmm, why remove gui_running feature?

What would you expect `has('gui_running')` to return when you have multiple UIs attached to nvim (let's say nvim-qt and running nvim in a terminal)?
