### ISSUE TITLE
Install fails on CentOS 7

### ISSUE THREAD

**Issue by stilley2** [neovim/neovim#6785]
- `nvim --version`: v0.2.0
- Operating system/version: CentOS7
- Terminal name/version: GNOME Terminal 3.14.3
- `$TERM`: xterm-256color

### Actual behaviour

Attempting to install using the Copr repo as described [here](https://github.com/neovim/neovim/wiki/Installing-Neovim#centos-7--rhel-7) yields the following:

```bash
Loaded plugins: auto-update-debuginfo, fastestmirror, langpacks, priorities


File contains no section headers.
file: file:///etc/yum.repos.d/dperson-neovim-epel-7.repo, line: 2
'<!doctype html>\n'
```

### Expected behaviour

File installs using as any other yum package.

**Comment by justinmk** [comment]
we don't maintain that package, can you contact the maintainer at https://copr.fedorainfracloud.org/coprs/dperson/neovim/ ?

**Comment by stilley2** [comment]
Ah I see. Will do, thanks.
