### ISSUE TITLE
tui: fix_terminfo() is a mess and does a poor job

### ISSUE THREAD

**Issue by jdebp** [neovim/neovim#6795]
3255118fae6664338f6b95aaadfea5dacd0dc944 in #6793 documents the three separate tasks that `fix_terminfo()` tries to do simultaneously, and so ends up doing poorly.  These should be separated out.

On operating systems like FreeBSD, which do not have terminfo, we follow the code path of creating a dummy empty terminal description and then populating it.  The population queries the `TERM` environment variable and depending from what it is writes various terminal capabilities into the description.  A whole bunch of `unibi_set_if_empty()`s is, just for starters, untidy and inefficient.  It's a Poor Man's termcap Reader, without the benefit of a real termcap database.  It instead uses a compiled-in one, disguised as code.  And every new capability used has to have another line of code introducing it for non-terminfo operating systems.

There are three better approaches.

The first better approach would be to switch to plain old `unibi_set_ext_str()` et al..  But that's still a database disguised as code.  And unibilium provides a better way to do this, by far.

The second better approach would be to have something that falls back to reading FreeBSD termcap and turning it into terminfo internally.  There are two problems with this.  First, termcap databases are in different forms and in different places on different operating systems.  The BSDs, for example, nowadays store it as a Berkeley DB file.  It seems a lot of wasted effort to chase down how lots of operating systems do termcap in order to have a termcap compatibility shim.  In any case, nvim is the wrong place for it.  Such a thing, if it were to exist, belongs in libunibilium .

The third better approach is to take advantage of `unibi_from_mem()` and the fact that in its test suite unibilium comes with some handy compiled binary terminfo entries for `screen`, `tmux`, and `xterm`.  These are not the half-baked versions with most of the parts missing that `fix_terminfo()` builds in the non-terminfo case,, but fairly complete terminfo records.  In the absence of terminfo, nvim could just fall back to using a few such built-in compiled terminfo entries.

Ironically, this would bring the terminfo and non-terminfo behaviours closer together, as the subsequent patch-where-terminfo-is-wrong code would be identical for both paths; and the resulting terminal descriptions would be, too.

**Comment by justinmk** [comment]
Sounds good, but why does efficiency matter? That code is only run once. Do you notice a slowdown?

 And it's not a huge amount of code so i personally don't care if it's ugly. But if someone wants to take ownership of it and shepherd it through the inevitable bug reports we can start down that path. 

NB in general we want to move away from caring about terminfo/cap , and choose sane defaults based on TERM. so the second approach is out of scope.

**Comment by jdebp** [comment]
Efficiency is just for starters, as I said.  Look how the recent DECSLRM/DECSTBM scrolling support that I did necessitated additions to this function to fake the extra unibi capabilities.  And then there were further additional fakeries for the cursor motion optimizations.  Every time that something more like that comes along, there's more fakery to add, replete with `if (term == Konsole) else if (term == Linux) else if ...` statements.  But `unibi_from_mem()` allows one to start with a fairly full terminfo entry, without need for progressively faking up each new capability that gets used, that is also fairly close to the real terminfo entries; close enough that it actually needs some of the same fixups.  

Remember maintainability.  Years from now, the person maintaining this should not be faced with pages of code hand-creating terminfo descriptions from scratch by conditionally setting individual capabilities based upon lots of subtly different `if` statements individually matching multiple values of `TERM`.  That's a maintenance nightmare.  For starters, the maintainer has to duplicate all of the work of determining which terminal should have which capability, just to ensure that xe is not messing something up when making changes.  

It's already reaching that level.  It's already important to remember which `if` statements include PuTTY and which do not, for example; and not obvious to the casual maintainer why PuTTY is a separate case, without that maintainer going and testing what control sequences PuTTY supports, replicating what I did.  But this is why this sort of stuff belongs in a terminfo database (either an external one or a small hardwired fall-back internal one) and not in nvim code.

You realize, given #6792 and #6793, that I didn't just file this idly, right?  (-:

**Comment by justinmk** [comment]
>  But unibi_from_mem() allows one to start with a fairly full terminfo entry, without need for progressively faking up each new capability that gets used, that is also fairly close to the real terminfo entries

> Remember maintainability. Years from now, the person maintaining this should not be faced with pages of code hand-creating terminfo descriptions from scratch by conditionally setting individual capabilities based upon lots of subtly different if statements individually matching multiple values of TERM

Sure, pages of code is too much. Up to now just it hasn't got out of control. Maintainability is a high priority. Only "frozen" code doesn't need to be maintained. Seems like the code isn't frozen though, since you have found numerous problems.

> You realize, given #6792 and #6793, that I didn't just file this idly, right? (-:

Your attention to this area is _greatly_ appreciated, for sure.

**Comment by aktau** [comment]
> Sure, pages of code is too much. Up to now just it hasn't got out of control. Maintainability is a high priority. But "frozen" code doesn't need to be maintained. Seems like the code isn't frozen though, since you have found numerous problems.

I beg to differ. Even very stable code could use simplification, if only for future readers to more easily figure out what it does. Sometimes the code itself doesn't need to change, but it needs to be used.

> Your attention to this area is greatly appreciated, for sure.

I would echo the same sentiment, when @leonerd showed me the difference between Neovim and stock Vim in terms of raw output to the terminal. I was surprised to learn that Neovim's output seemed far more redundant (and there was definitely more of it). The SSH use case is also quite important, for me personally. So, a big thanks from this user, @jdebp.

@leonerd, would you be so kind of pasting either the tool or the terminal code output difference you pasted back then?

**Comment by teto** [comment]
It's great to see people look at the TUI code. It's not easy to review when you are not used to terminal capabilities and its terminology ("DECSLRM" etc) so I want to have a look but could not gather enough time. Using the backup terminfo in libunibilium seems worth exploring rather then slowly recreate it in neovim.

This is not the first time that neovim is shown to be "more talkative" than vim. Would it be possible to have a testsuite to compare vim vs neovim and maybe even use it to detect change in verbosity ? like using ttyrec to register a session done with vim, another session with neovim and compare the lengths of the tracks.
As a sidenote, I have been working on TUI cursor stuff and the most annoying part is to manually test changes across the different terminals. I don't want to sidetrack the discussion but if someone knows how to do it I am all ears (was thinking of comparing screenshots but that harldy seems like a good idea).

**Comment by justinmk** [comment]
> the most annoying part is to manually test changes across the different terminals.

You can test terminal responses using a `:terminal` and hooking up a `on_stdout` handler. We have some tests doing that. This would at least verify that for a given `$TERM` we send/receive expected sequences.

**Comment by jdebp** [comment]
e4919f3d45311704802e64a61e8ce600e9c0fbd5 now exists.  There's some more testing on a few remaining terminal emulators to be done, and I might bundle in a fix for #6803 before initiating the pull request.  Note that there are already some accompanying doco changes in another commit.

**Comment by justinmk** [comment]
> There are three better approaches.
> The first better approach would be to switch to plain old unibi_set_ext_str() et al.. 
> ...
> The second better approach would be to have something that falls back to reading FreeBSD termcap and turning it into terminfo internally. 
> ...
> The third better approach is to take advantage of unibi_from_mem() ... just fall back to using a few such built-in compiled terminfo entries.

In #6816 we took the third approach.
