### ISSUE TITLE
Unexpected paragraph jump

### ISSUE THREAD

**Issue by SuperCuber** [neovim/neovim#6797]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? Didn't check
- Operating system/version: Archlinux, all packages updated
- Terminal name/version: Termite (latest archlinux's)
- `$TERM`: xterm-256color (Changed in zshrc)

### Actual behaviour
Unexpected `}` jumps to middle of paragraph in attached file
### Expected behaviour
`}` should jump to the end of the paragraph
### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
Open attached dir_colors file
Go to line 94
Press `}`
Cursor jumps to line 102 as opposed to expected line 141.
```

File couldn't be attached because of no extension, [here](https://github.com/SuperCuber/dotfiles/blob/2177b30ed2e1785759e3a35ab888bd6a8ef64987/dir_colors)'s a link to it.

**Comment by chrisbra** [comment]
that is because `}` moves to the next paragraph. And a paragraph also ends at certain nroff macros like `.pp` which happens to be what is on line 94. You can `:set paragraphs=` and have a expected behaviour.

**Comment by justinmk** [comment]
Thanks @chrisbra
