### ISSUE TITLE
new functions for multi-byte aware indexing and splicing

### ISSUE THREAD

**Issue by OliverUv** [neovim/neovim#68]
frogonwheels_ entered the irc with a question we should consider at some point. Apparently, multi-byte character handling is working unintuitively. Allegedly, it's an issue that Bram has been avoiding. Here is what he had to say (I have done some cleanup, summarized, clarified):

If you do `let idx=1 | while idx < strlen(txt) | let idx+=1 | let ch = txt[idx] | endwhile` then it's going through byte-wise rather than char wise. Essentially, Vim indexes lines per byte, not per character. This leads to complications when plugins try to get character n from the current line.

All the code that loops through characters in a string, or expects the column number to be the same as the index into the line (which happens all the time) will be broken as soon as you have multibyte characters.

`col('.')` indexes the current column you are in (ie for display) and people do `getline('.')[col('.')]` to get the current character, but that doesn't work for multibyte. You'd have to do `matchstr(getline('.'), '^\(\zs.\)\{'.col('.').'}')` to get the correct character. Since regexp indexing is character-wise. This doesn't even take into account the fact that some multibyte chars go over 2 columns.

Currently the only safe way of indexing strings in a character-length independent way is to use `'.\{'.n.'}`.

The Windows solution to this problem is to use ucs2-le character encoding - which will work until people start using multi-word characters (given that ucs2 is still multi-byte, just less likely to encounter it).

So either it's gotta be internally handled as wide characters (which is in itself limiting, but less so) which is the Windows approach.

A problem arises if we don't have constant-size characters: If you define `txt[idx]` to be character-wise, then your `txt[idx]` ends up being an ord(n) operation and the loop becomes bad, so you have to have some kind of indexing or something.

grayb__ observes: There's nothing too expensive about keeping a codebase multibyte safe, the problem is all the code that assumes 7 or 8 bit ascii.

I assume this is something we'll want to do far in the future, so it might be best to archive this issue under an appropriate label.

**Comment by Yamakaky** [comment]
Did you consider using an external unicode library ? It would replace all the utf_* functions, with (hopefully) better support.

**Comment by aktau** [comment]
The utf8 support in vin from the C side seems plenty fine to me. How would
you imagine an external library improving things?

**Comment by Yamakaky** [comment]
I don't have any example, but I know there are a lot of corner-cases with unicode, so maybe it would improve the support. Also, I saw a lot of c str functions in the code, which doesn't support unicode well.

**Comment by justinmk** [comment]
So, conclusions from this thread:

> Just reviewed eval.c: string indexing is O(N) (length information is not saved). Will be O(1) once you [use lua functions](https://github.com/neovim/neovim/issues/68#issuecomment-39663476).

And, actionable item from this thread:

- introduce new functions for multi-byte aware indexing and splicing

**Comment by justinmk** [comment]
HN recently had a [discussion about Python 3 Unicode string objects](https://news.ycombinator.com/item?id=10752434) which I found enlightening. 

> give up on random access by characters. You almost never need it; in the most frequent case where you do (using indexOf or equivalent to search for a substring, and then breaking on it), you can solve the problem by returning a type-safe iterator or index object that contains a byte offset under the hood, and then slicing on that. Go, Rust, and Swift have all gone this route.

> Python 3 unicode string object makes very little sense given real world situations. It wastes enormous amount of memory in many common scenarios for no reason at all other than to facilitate O(1) access to charpoints which is completely inappropriate for text processing anyways.

https://news.ycombinator.com/item?id=10752727

> But in practice, we get the indexes from methods like str.find() or re.match(), and we treat them as more or less opaque, so we don't end up slicing grapheme clusters very often in practice. Grapheme cluster slicing requires a big Unicode table in memory anyway, so in the rare case that you need it, you can pay the high performance cost for using it.

> And let me ask you this: what do I get when I write:
> ```
>    x = "a"
>    y = "\u0301"
> ```
> Is the resulting len(x + y) == 1? But len(x) == 1 and len(y) == 1?

**Comment by myitcv** [comment]
For what it's worth, I like the Go approach to strings, unicode, normalisation etc:

https://blog.golang.org/strings
https://blog.golang.org/normalization

**Comment by justinmk** [comment]
Addressed by `strgetchar()`. https://github.com/neovim/neovim/pull/5527
