### ISSUE TITLE
scrolling is messed up 

### ISSUE THREAD

**Issue by lukatendai** [neovim/neovim#6802]
NVIM v0.2.1-237-gf4fddbf
Build type: Release
Fedora 25 64bit

When open more than one panel, the scrolling mess up the whole screen... for example I see 1;191s in the top0left corner. Moving, resizing window fixes issue, I guess the terminal redraws content.

VIM works corectly

This issue appeared after commit 0de7b17d03e2de18adcc9e7db27483160c4ac052

**Comment by jdebp** [comment]
Which terminal?  

This is a known problem for some terminals that claim to be xterm and set the `TERM` environment variable to `xterm`, but that actually are not; in particular:
* versions of GNOME Terminal (3.14.1 on one of my systems) which do not set the `COLORTERM` environment variable and so do not trigger the existing recognition of GNOME Terminal
* LXTerminal
* MATE Terminal

Is your terminal one of those, or something else?

I have fixed all of these, which I have found, as part of the work that I am doing for #6795.  The fix, alas, is to positively decode "real" xterm rather than treat everything that claims to be `xterm` as xterm.

The [local fix](http://jdebp.eu./FGA/fix-terminology.html) for GNOME Terminal and MATE Terminal users is to explicitly set the `COLORTERM` environment variable to `gnome-terminal`.

**Comment by lukatendai** [comment]
you are 100% correct; when I run `TERM="" nvim` then everything works as before...

**Comment by jdebp** [comment]
I still have a few remaining terminal emulators to test it on, but e4919f3d45311704802e64a61e8ce600e9c0fbd5 should fix this for you, when it is merged.  As part of the same work in another commit, I have updated the on-line help and `:help xterm-scroll-region` will tell you more, as on Vim.

**Comment by dncnmcdougall** [comment]
FYI: I am on `st` and am having this problem. I have `TERM="xterm-256color"`. And I experience this problem.

**Comment by chrisallenlane** [comment]
FWIW, I too am using `st` and am experiencing this problem. Like @lukatendai stated, however, running `TERM="" nvim` resolves the problem for me.

I forget why (I think I had something to do with SSH?), but I remember I needed `st` to "lie" about being `xterm` for some reason. As a workaround, I'm probably just going to `alias nvim="TERM='' nvim"` and call it a day.

I'm happy to share additional information with the maintainers, if I can be of any service.

**Comment by jdebp** [comment]
No need.  As I said, it's a known problem.  I found it during testing about 2 hours before this issue was posted.  I am confident that I have fixed it.  There's a fix in the pipeline, which I have tested and almost finished.  The best thing that you can do is crank up `st` again when the fix has made it into the main version, and tell me that it is all better now.  (-:

**Comment by FuzzOli87** [comment]
Just want to chip in that Tilix terminal also has this issue.

**Comment by jakob-lundberg** [comment]
Also ROXTerm.

**Comment by blueyed** [comment]
I've seen this using TERM=rxvt-unicode-256color, and #6816 fixes it for me.

**Comment by JCavallo** [comment]
@jdebp #6816 fixed this for alacritty as well, thanks a lot

**Comment by JiriChara** [comment]
I set `COLORTERM=gnome-terminal` and have no more display issues. Thanks @jdebp!

**Comment by BonarBeavis** [comment]
```vim
let $COLORTERM = "gnome-terminal"
```
Fixes the issue with artifacts, but 

```vim
set titlestring
```

does not work anymore.

**Comment by delijati** [comment]
`TERM="" nvim` works in LXTerminal

**Comment by pyrho** [comment]
Can confirm `TERM="" nvim` works with [Termite](https://github.com/thestinger/termite) on `82907ab`.

**Comment by amireldor** [comment]
Happens to me with mate-terminal. `TERM="" nvim` fixes the issue.

I compiled neovim from the 'master' branch. Worth noting when I compiled `v0.2.0`, the **issue did not happen**. A regression?

**Comment by blueyed** [comment]
@amireldor 
I think https://github.com/neovim/neovim/pull/6816 might fix it.

That also applies to the previous "workaround" comments: please try that PR and provide feedback there, or wait until it lands.

**Comment by amireldor** [comment]
@blueyed 
Stuff is good with this! Commented in the PR. Saw you're about to merge this, good luck and thanks.

**Comment by justinmk** [comment]
Closed by #6816

**Comment by delijati** [comment]
The refactor produces all black and white when i set `TERM="" nvim` but without i get some broken artefact's. I use now  `TERM=tmux-256color`.

**Comment by offa** [comment]
This is related to #6982.

**Comment by dm319** [comment]
I think this has just arrived from the neovim-ppa for my ubuntu-mate 16.04 installation - thank you for all the hard work fixing this.

**Comment by pjrt** [comment]
I'm getting this issue with urxvt:

```
λ echo $TERM
rxvt-unicode
```

Running `TERM=""` fixes it (but I lose some features like highlighting matching parens).

**Comment by feoh** [comment]
Also seeing this with Kubuntu 18.10, nvim built from source with latest master.
```
feoh@yamato:~$ uname -a
Linux yamato 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
feoh@yamato:~$ echo $TERM
xterm-256color
feoh@yamato:~$ echo $COLOR
$COLORFGBG  $COLORTERM  
feoh@yamato:~$ echo $COLOR
$COLORFGBG  $COLORTERM  
feoh@yamato:~$ echo $COLORTERM 
truecolor
feoh@yamato:~$ nvim --version
NVIM v0.3.2-826-g87d67814e
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/home/feoh/src/personal/neovim/build/config -I/home/feoh/src/personal/neovim/src -I/home/feoh/src/personal/neovim/.deps/usr/include -I/usr/include -I/home/feoh/src/personal/neovim/build/src/nvim/auto -I/home/feoh/src/personal/neovim/build/include
Compiled by feoh@yamato

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
feoh@yamato:~$ 
```

**Comment by maotora** [comment]
I still have this issue.

Using Xterm on ArchLinux.

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include #You actually scrolled this far!! 🙌
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
I too confirm that using `TERM="" nvim` fixes the issue.
