### ISSUE TITLE
doco: terminfo, not termcap

### ISSUE THREAD

**Issue by jdebp** [neovim/neovim#6803]
`:help termcap` says
>On Unix the terminfo database or termcap file is used.  This is referred to as "termcap" in all the documentation.

This is in fact not true.  nvim uses unibilium, which only uses terminfo.  See #6795 for why it's probably not a good idea to try to add a termcap shim layer.  

The doco should read
>On Unix the terminfo database is used.  

without the second sentence; everywhere that the doco uses "termcap" to mean terminfo it should be revised to actually call it "terminfo"; and the `*termcap*` help anchor should be moved to vim_diff or to deprecated.

A second sentence, per #6795, would read:
> If terminfo is not available, nvim uses some built-in terminfo descriptions.

**Comment by justinmk** [comment]
This was addressed by #6816. 

see also https://github.com/neovim/neovim/pull/7105 , in the documentation "TUI" means "host terminal" and "terminal" means "embedded terminal emulator", to avoid endless verbose qualifiers.
