### ISSUE TITLE
nvim re-sources markdown/html/css/javascript/vb support when it does not need to

### ISSUE THREAD

**Issue by frioux** [neovim/neovim#6804]
- `nvim --version`:

```
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UFyCc4/neovim-0.1.7=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UFyCc4/neovim-0.1.7/build/config -I/build/neovim-UFyCc4/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-UFyCc4/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-UFyCc4/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) all versions have the same problem
- Operating system/version: Ubuntu 17.04
- Terminal name/version:
- `$TERM`: screen-256color

### Actual behaviour

nvim takes a long time (a few seconds) to load an argument list.

### Expected behaviour

Should be instant

### Steps to reproduce using `nvim -u NORC`

```
mkdir -p ~/.config/nvim/ftdetect
echo 'autocmd BufNew,BufNewFile,BufRead *.md :set filetype=markdown' > ~/.config/nvim/ftdetect/markdown.vim
mkdir testing
cd testing
touch {1..500}.md
nvim -u NORC
:args *
```

### Discussion

I know that this can be fixed by leaving `BufNew` out of the autocmd events above, but this doesn't happen with other filetypes.  I am pretty sure it's something wrong with the `vb` filetype as replacing the contents of the vb syntax file fixes it.  [You can read more about this problem here](https://groups.google.com/forum/#!topic/vim_use/m7t32w_n6wc).  The vim maintainers seem relatively uninterested in fixing this, but I thought maybe neovim would want to fix it.  I am happy to provide more details if you'd like, though this is easily reproducably.

**Comment by frioux** [comment]
Sure, they will probably take a patch.

-- 
Sent from a telephone. Pardon my brevity.

On May 24, 2017 11:44 AM, "Christian Brabandt" <notifications@github.com>
wrote:

The vim maintainers seem relatively uninterested in fixing this, but I
thought maybe neovim would want to fix it.
I don't think so. I think we have not yet correctly identified the problem
in the code.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neovim/neovim/issues/6804#issuecomment-303815471>, or mute
the thread

**Comment by jamessan** [comment]
Based on the linked discussion, I see no need to have this issue open.  There appears to be a consensus growing about the cause of the behavior and we'll eventually merge any resulting patch.
