### ISSUE TITLE
TOhtml is not capturing the word differences

### ISSUE THREAD

**Issue by sandosh143** [neovim/neovim#6805]
- Vim (version: 7.4.629) 
- Operating system/version: CentOS release 6.8 (Final) 2.6.32-642.1.1.el6.centos.plus.x86_64
- Terminal name/version: /dev/pts/1
- `$TERM`: xterm

### Actual behaviour
I am using the diffchar.vim plugin to get the character level differences between 2 files. In the terminal I am able to see the character differences but when i try to convert that to html using TOhtml its not capturing the character differences. Its capturing only the line differences.

### Expected behaviour
TOhtml need to capture the character level differences but it is not happening now.

### Steps to reproduce using `nvim -u NORC`
Install the diffchar.vim plugin and run the below command to compare the 2 files using "vimdiff" or "vim -d"

`vimdiff <file1> <file2> -c :TOhtml -c wqa`

```
Character level differences in the terminal or shell:
![exact difference](https://cloud.githubusercontent.com/assets/28937486/26428258/edc80f82-409d-11e7-870b-cd91c04398fa.JPG)

After converting to html file its not showing the character differences:
![line difference](https://cloud.githubusercontent.com/assets/28937486/26428257/edb69c02-409d-11e7-9d7c-1159a637258c.JPG)

**Comment by jamessan** [comment]
Thanks for reporting this problem!

We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. If Vim changes something in the same file, it takes time to figure out the differences.

Please send this issue to the maintainer listed at the top of the file.  Once the maintainer fixes it and submits it to Bram, we'll be able to merge the fix from Vim.
