### ISSUE TITLE
mouse glitches + NERDTree

### ISSUE THREAD

**Issue by alexbyk** [neovim/neovim#6810]
- `nvim --version`:NVIM v0.2.1-dev
- Vim (version: ) behaves differently? 
- Operating system/version: "Ubuntu 16.04.2 LTS"
- Terminal name/version: default
- `$TERM`: xterm-256color

Mouse scrolling causes glitches and strange symbols in NERDTree window
![image](http://alexbyk.com/nvim.png)

Also I got some errors like "error while processing modelines. unknown option https" and have no idea what causes it.

Here is a config file I use https://github.com/alexbyk/rcfiles/blob/master/init.vim

**Comment by justinmk** [comment]
Are you using Konsole? ("default" is not a terminal name. What terminal are you using to run nvim?)

> got some errors like "error while processing modelines. unknown option https" and have no idea what causes it.

Somewhere in your config there is a comment that looks like `vim: ...`. Can't say where without the exact error message, your linked init.vim doesn't have that line.

**Comment by alexbyk** [comment]
@justinmk it's GNOME Terminal 3.18.3

**Comment by jdebp** [comment]
I apologize for the CSI sequences down the left-hand side.  Your terminal is wrongly claiming to be Xterm, but does not support what genuine Xterm does.  #6816 will fix this for you.

**Comment by justinmk** [comment]
Closed by #6816
