### ISSUE TITLE
Release mode still causes Assertions

### ISSUE THREAD

**Issue by lukatendai** [neovim/neovim#6814]
I am using master,
NVIM v0.2.1-238-g45626de
Build type: Release
It is release build but stile once per while when my vim-go plugin has a problem, nvim crashes with message
`"-stdin-" nvim: /workspace/neovim/.deps/build/src/libuv/src/unix/fs.c:1236: uv_fs_stat: Assertion 'path != NULL' failed.`

`[1] 9565 abort (core dumped) nvim`

This is my build script:

`rm -r build && make clean && make all CMAKE_BUILD_TYPE=Release`

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/4370

**Comment by lukatendai** [comment]
well... vim gracefully reports an error and it does not crash

**Comment by justinmk** [comment]
@lukatendai What Vim error are you referring to?

**Comment by lukatendai** [comment]
path != NULL -- this problem occurs also in vim, the only difference is that neovim will crash and vim will just display error and will do nothing. I understand that it is not neovim bug... but changing compiler flags in release mode might help. There is nothing more annoying than the crash of the code editor.  Thank you for helping...

**Comment by justinmk** [comment]
Interesting. What is the exact error message?

**Comment by lukatendai** [comment]
if I remember I will write down when it happens in vim again, but the error mentions the same problem "path is NULL" or something like that...

**Comment by lukatendai** [comment]
yesterday neovim crashed 3 times because of this assertion 'path != NULL' failed. Why it cannot just log the fact the path is null and just move forward... Even if this is a plugin fault, it should not bring down the whole editor... Ugh... so annoying!!! ;(

**Comment by justinmk** [comment]
Again, need to know the exact error message.

**Comment by jameskyle** [comment]
"-stdin-" nvim: /home/james/Projects/neovim/.deps/build/src/libuv/src/unix/fs.c:1236: uv_fs_stat: Assertion `path != NULL' failed.

**Comment by justinmk** [comment]
As mentioned above, this is covered by https://github.com/neovim/neovim/issues/4370 .

When I asked for an error message, I was referring to the "vim error message" mentioned in https://github.com/neovim/neovim/issues/6814#issuecomment-304082891

**Comment by lukatendai** [comment]
https://goo.gl/photos/mH7CzQp5iEEDRXTs5

Here is the error from vim

**Comment by justinmk** [comment]
Thanks! That looks like a hint.

    "-stdin-" E212: Can't open file for writing

**Comment by lukatendai** [comment]
The issue appears when there is wrong structure of the code, for example some times when I add only if{} without any condition and then save the file. Then the code should be formatted and crash happens. What is more it happens in vim and neovim... But only neovim crashes. Clearly it's a problem with plugin... However like I said before it should not crash the editor.

**Comment by lukatendai** [comment]
finally it is fixes!!!!!!!! now I can go back to neovim ;) Thanks.
