### ISSUE TITLE
nvim-qt has poor kerning with monitor scale factor of 150% on Windows 10 Pro

### ISSUE THREAD

**Issue by Iiridayn** [neovim/neovim#6817]
- `nvim --version`: v0.2.1-6
- Operating system/version: Windows 10 Pro
- Terminal name/version: n/a
- `$TERM`: n/a

### Actual behaviour

GUI uses wide kerning on monitor with scaling of 150%. Looks fine on monitor with scaling of 200%.

### Expected behaviour

GUI looks fine on monitor with scaling of 150%.

### Steps to reproduce using `nvim -u NORC`

run `nvim-qt`, move to a monitor with scaling of 150%, type a sentence or two. Move to a normal monitor (100% or 200% scaling), note how the text looks pretty normal. Compare again with dragging it to the other monitor. It would appear that the font size is reduced, but the width of each character and the window remain constant, resulting in excessive spacing.

**Comment by jamessan** [comment]
This should be reported in [neovim-qt's](https://github.com/equalsraf/neovim-qt) repo.
