### ISSUE TITLE
Run luacheck for all lua files in src

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6818]
Lua files in src are growing more and more complex, so it should be a good idea to lint them as test files. In #6789 I have added linting for `src/nvim/lua/vim.lua`, but there is a bunch of other files in src, primary lists and generators, latter are rather complex and have started to contain modules. Enabling RunLuacheck.cmake for them should be a good idea.

Marking this as entry-level because despite of big number of errors all should be easy to fix: after all, luacheck is not a static analyzer.

**Comment by sameedali** [comment]
Hi,
I'm interested in working on this. Is there a specific luacheck config file I have to follow? I checked the reference you posted and couldn't find where the specified style guide is. Could you please help me out here.

**Comment by ZyX-I** [comment]
What “specified style guide”? There is not one yet for lua files.

**Comment by sameedali** [comment]
I was just confirming if there was a project specific luacheck config that I have to follow.
I ran luacheck without specifying a config and Im getting a lot of errors. Ill start by fixing them.

**Comment by ZyX-I** [comment]
@sameedali It would be good idea to wait until #6789 is merged.

**Comment by ZyX-I** [comment]
Though not for fixing luacheck errors, but for adding tests. Or you can just take that branch, rebase and start PR on that basis, then rebase again when it gets merged to remove unwanted commits.

**Comment by sameedali** [comment]
okay. I'll do that

**Comment by justinmk** [comment]
There is a luacheck file in the project. Just do a search..

**Comment by ZyX-I** [comment]
I did not intentionally use any for #6789, after finding the location of the luacheck file in `tests` I think this means default. Should say that short of `cache` none of other rules are applicable outside of tests.

**Comment by sameedali** [comment]
https://github.com/neovim/neovim/compare/master...sameedali:master

So here are the changes I have made. Please look at them and let me know if they are ok

**Comment by ZyX-I** [comment]
@sameedali Can you make a PR? This variant is not commentable and I can’t see that you have not broken something while PR will make CI run.

Also it is generally bad idea to make any changes directly to `master` branch, be it your master or not: with your `master` this is harder to operate with git this way and you can have only one “your” `master` while it is completely possible that you have multiple PRs.

**Comment by sameedali** [comment]
Thanks Ill keep this mind. I made a PR aswell: https://github.com/neovim/neovim/pull/6911

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/10414
