### ISSUE TITLE
Terminal Colors seem Broken

### ISSUE THREAD

**Issue by frioux** [neovim/neovim#6822]
- `nvim --version`: `NVIM v0.2.1-dev`
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu 17.04
- Terminal name/version: Terminator 1.90, XTerm(324)
- `$TERM`: screen-256color, xterm-256color

### Actual behaviour

It looks to me like somehow the colors and the bytes are out of sync (ie the emoji are confusing the terminal.)

![zfp-selection-100](https://cloud.githubusercontent.com/assets/8163/26529755/e43e2d7c-437a-11e7-995e-afea3d9b6c4e.png)

### Expected behaviour

![zfp-selection-099](https://cloud.githubusercontent.com/assets/8163/26529753/d97208f0-437a-11e7-9744-b23ddf89ba15.png)

### Steps to reproduce using `nvim -u NORC`

I use zsh and have [a complicated prompt](https://github.com/frioux/dotfiles/blob/master/zsh/rc/S60_prompt) that you can clone and install.  If I can reduce it I will.

```
nvim -u NORC
:terminal
```

**Comment by guyzmo** [comment]
did you try hitting <kbd>C</kbd>-<kbd>L</kbd> in normal mode to see if that changes anything? I'm also an heavy emoji-unicode user, and I confirm that big emojis like 💀💣🖖🍻🏁👍📚😇📝🙌🔖 mess up the display in `:term`. And don't even try to do that with `:term` in neovim running in tmux or screen 😁

**Comment by frioux** [comment]
Nah no luck.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/4976

There's no good solution to this. All layers must agree: your terminal, tmux, nvim, ...

**Comment by blueyed** [comment]
@frioux 
There is some internal define/switch to make nvim use wcwidth, maybe that helps?

**Comment by frioux** [comment]
I don't really care enough to rebuild nvim at this time.  I don't use it a whole lot but have heard good things and wanted to give it a try.  I'll wait until it's a little more polished.

**Comment by justinmk** [comment]
Polished compared to what? This issue will occur with various combinations of terminals no matter what choice we make.

**Comment by frioux** [comment]
Vim and a terminal in a different window 😉

--
