### ISSUE TITLE
Dependency gperf build error: Segmentation fault

### ISSUE THREAD

**Issue by zuxfoucault** [neovim/neovim#6824]
Build command: `make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/local/neovim"`

```
/bin/sh: line 1: 19046 Segmentation fault      (core dumped) /usr/bin/cmake -DPREFIX=/home/zuxfoucault/space/environment/neovim_tmp/neovim_test/.deps/build -DDOWNLOAD_DIR=/home/zuxfoucault/space/environment/neovim_tmp/neovim_test/.deps/build/downloads/gperf -DURL=http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz -DEXPECTED_SHA256=767112a204407e62dbc3106647cf839ed544f3cf5d0f0523aaa2508623aad63e -DTARGET=gperf -DUSE_EXISTING_SRC_DIR=OFF -P /home/zuxfoucault/space/environment/neovim_tmp/neovim_test/third-party/cmake/DownloadAndExtractFile.cmake
```
Env: centos 6.8 gcc 4.4.7 autoconf 2.69 cmake 2.8.12.2

Any advice and suggestions will be appreciated!

**Comment by justinmk** [comment]
We could commit the gperf result to source. That would need to be automated in https://github.com/neovim/bot-ci

Other than that, it's a gperf bug.

**Comment by zuxfoucault** [comment]
Thanks for the prompt response!
I looked up the `neovim/.deps/build/downloads/gperf/gperf-3.0.4.tar.gz` file. The size of the file is zero. It seems the .dep automation process did not successfully download the file (or something happened making the content of file gone) during `make`.

If I want to manually build dependencies, should I just prefix the install location to .dep folder? I don't quite sure the directory structure of the .dep directory.

**Comment by justinmk** [comment]
Sounds like a network issue.  Just retry.

**Comment by zuxfoucault** [comment]
Same result. I did it several times, and I can wget the tar.gz manually....
I am wondering how to build those dependencies in .dep folder?

**Comment by justinmk** [comment]
You don't need to build the deps manually, you can install the deps using your system package manager. In that case, set `USE_BUNDLED_DEPS=off` before building. Do `make distclean` before trying this, else the previous cached cmake config will be used.

**Comment by zuxfoucault** [comment]
Thanks!
