### ISSUE TITLE
Feature request: disable status and command line in 

### ISSUE THREAD

**Issue by vorner** [neovim/neovim#6825]
I've a habit of „nesting“ or „stacking“ tui commands ‒ run mutt, vim inside that, run a script that runs another mutt inside and runs another vim inside, etc... This is well supported by vim or mutt, as it just leaves the terminal be and lets the thing inside do whatever it likes.

However, nvim insists on starting a new terminal emulator to run the command inside. This would be fine, except that it adds the status line and command line, eating two lines of the space the command inside could use. These wasted lines actually accumulate as more stacking happens. I managed to get rid of the status line, but the command line is still there.

It would be great if I could use some sort of `:terminal --fullscreen` or `:run-in-my-terminal` command which would either get rid of the command line for the duration of that „internal“ command, or worked in a similar way to mutt or old vim. I like the features of nvim (especially better support for code completion plugins), but I don't really want to change my way of operating too much (like using nvim as a kind of window manager, etc).

- `nvim --version`:

```
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/lib64/distcc/bin/x86_64-pc-linux-gnu-gcc -O2 -march=corei7-avx -pipe -ggdb2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/config -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.2.0/work/neovim-0.2.0_build/include
Compiled by root@ruth

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version:

Gentoo linux

- Terminal name/version:

urxvt

- `$TERM`:

rxvt-unicode-256color

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/1004
