### ISSUE TITLE
Can not display unicode char correctly

### ISSUE THREAD

**Issue by icymind** [neovim/neovim#6826]
- `nvim --version`: >= 0.2.0
- Vim (version: 8) behaves differently? yes
- Operating system/version: OSX 10.11.6
- Terminal name/version: iTerm 2 3.0.15
- `$TERM`: screen-256color

### Actual behaviour
This issue happens when use custom colorscheme(solarized, gruvbox, onedark, tender, flattened and so on...).

If there's a line with unicode char in it and the line is beyond current screen.
When you reach the line by press "j", the unicode char in the line can not display.

### Expected behaviour
The unicode char should display. (nvim 0.1.7 works well)
### Steps to reproduce using `nvim -u`

- content of demo.txt
```bash
line 1
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
line 10
line 11
line 12
line 13
line 14
line 15
line 16
line 17
line 18
line 19
line 20
line 21
line 22
line 23
line 24
line 25
line 26
line 27
line 28
line 29
line 30
line 31
line 32
line 33
line 34
line 35
line 36
line 37
line 38
line 39
some unicode char after semicolon: 测试
line 41
line 42
line 43
```
- content of demo.vim
```bash
call plug#begin('~/.config/nvim/plugged')
Plug 'lifepillar/vim-solarized8'
call plug#end()
color solarized8_dark
```
- reproduce by:
```
nvim -u demo.vim demo.txt
```

  - when reach line 40 from line 0 by pressing "j" or using "40gg", the text "测试" can not display.The text shows unless you press Ctrl-L or Shift-v 
![window_2017-05-30 00 51 20_mliqrd](https://cloud.githubusercontent.com/assets/1908329/26557215/28f20508-44d2-11e7-8270-a9b5571b8751.jpg)
  - when reach line 40 by Ctrl-f or G, the unicode text display correctly. 
![window_2017-05-30 00 55 10_salkhz](https://cloud.githubusercontent.com/assets/1908329/26557296/ab7280ac-44d2-11e7-93f7-f4e56d29937e.jpg)

**Comment by justinmk** [comment]
> nvim 0.1.7 works well

Can you bisect to the problem commit ?

**Comment by icymind** [comment]
@justinmk sorry?

**Comment by icymind** [comment]
update: The issue only happen when use tmux.

**Comment by justinmk** [comment]
What does `:lang` report ?

**Comment by icymind** [comment]
Current language: "C"

**Comment by justinmk** [comment]
That would explain it.

**Comment by icymind** [comment]
Should I change lang?
I change neovim lang by `:lang zh_CN.utf-8/UTF-8/zh_CN.utf-8/C/zh_CN.utf-8/zh_CN.utf-8`, 
But nothing happen, unicode char not showing up as before

**Comment by justinmk** [comment]
LC_ALL env var

**Comment by wujunchuan** [comment]
Me too,my solution is fore neovim to fresh itself.
add below snippet to your config:
```
"Ctrl + l 的默认功能是清空并「重新绘制」当前的屏幕，就和 :redraw! 的功能一样。下面的这个映射就是执行重新绘制，并且取消通过 / 和 ? 匹配字符的高亮，而且还可以修复代码高亮问题
"快捷键 <leader>l
nnoremap <leader>l :nohlsearch<cr>:diffupdate<cr>:syntax sync fromstart<cr><c-l>
```

**Comment by jdebp** [comment]
Instead of mapping bodges, try changing the `LC_ALL` environment variable so that you are in something other than the `C` locale, as M. Keyes already (but cryptically) said.

**Comment by justinmk** [comment]
`LC_ALL=C` by definition does not support unicode. As explained above, set it to a unicode locale.
