### ISSUE TITLE
man.vim: error `b:man_sect` undefined on `set ft=man` when buffer is `set nomodifiable`

### ISSUE THREAD

**Issue by olmokramer** [neovim/neovim#6828]
```
$ nvim --version
NVIM v0.2.1-258-g1b7a9bf4d
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/olmo/.cache/pacaur/neovim-git/src/neovim-git/build/config -I/home/olmo/.cache/pacaur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/olmo/.cache/pacaur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/olmo/.cache/pacaur/neovim-git/src/neovim-git/build/include
Compiled by olmo@arch-desk

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: latest) behaves differently? Yes.
- Operating system/version:
```
$ uname -a
Linux arch-desk 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
```
- Terminal name/version:
```
$ urxvt --version
urxvt: "version": unknown or malformed option.
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
$ echo $TERM
rxvt-unicode-256color
```

### Actual behaviour
I used [ViewDoc](https://github.com/powerman/vim-plugin-viewdoc/blob/master/plugin/viewdoc_man.vim) to view manpages in Vim, but when I recently switched to NeoVim I started getting the following error when I open any man page:

```
Error detected while processing function man#init_pager:
line    2:
E21: Cannot make changes, 'modifiable' is off
E21: Cannot make changes, 'modifiable' is off
Error detected while processing /usr/share/nvim/runtime/syntax/man.vim:
line   29:
E121: Undefined variable: b:man_sect
E15: Invalid expression: b:man_sect =~# '^[23]'
Press ENTER or type command to continue
```

Then when I press any key to continue the correct man page does show up.

From the error above I thought I'd comment the line of the ViewDoc plugin that changes the filetype of the buffer, so that the `man` syntax file wasn't executed, and indeed that solved my problems.

So I went looking in `$VIMRUNTIME/syntax/man.vim` and found
```vim
if !exists('b:man_sect')
  call man#init_pager()
endif
if b:man_sect =~# '^[23]'
  " ...
```
And in `$VIMRUNTIME/autoload/man.vim`
```vim
function! man#init_pager() abort
  execute 'silent keeppatterns keepjumps %substitute,.\b\|\e\[\d\+m,,e'.(&gdefault?'':'g')
  " ...
```
Note the `%substitute`, which requires the buffer to be modifiable (there are other modifying commands in `man#init_pager()`). However, because ViewDoc had set the buffer to be `setlocal nomodifiable` before it does `setlocal ft=man`, the substitute fails and causes `man#init_pager()` to abort *before setting* `b:man_sect` and so `b:man_sect` is still undefined after the call to `man#init_pager()` in the syntax file, and so an error is generated on the `if b:man_sect =~# '^[23]'` line...

I haven't really checked *why* things are this way, but I find it really strange that a *syntax* depends on the *modifiability* of a buffer... What are your views on this?

### Expected behaviour

No errors when setting any syntax, just because the file is `set nomodifiable`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set nomodifiable
:set ft=man
```

**Comment by jamessan** [comment]
Cc @nhooyr

**Comment by nhooyr** [comment]
I agree. I'll work on this soon.

**Comment by olmokramer** [comment]
Awesome! I forgot to mention, but I'd be willing to work on a PR to fix this, I just thought I'd check with you what direction to go... I can think of numerous ways to fix this, the easiest being
```vim
set modifiable
if !exists('b:man_sect')
  call man#init_pager()
endif
set nomodifiable
```
but that feels like a hack, and I've not checked that `man#init_pager()` doesn't actually change anything (though it doesn't seem to...) so maybe you guys want something else :)

**Comment by olmokramer** [comment]
Wait, that should be
```vim
let _m = &modifiable
set modifiable
" ...
let &modifiable = _m
```

**Comment by nhooyr** [comment]
I think that code should not be there at all. Its a syntax file, it should not be modifying the file at all. Though, I'm not sure if there is a better solution, especially one with backwards compatibility. Let me think about this for a bit and I'll get back to you.

**Comment by nhooyr** [comment]
Ok I thought about it. Turns out, this was intended. See #5630.

I think we should break up `man#init_pager` into two separate functions, `man#init_b:sect` and `man#init_pager`.

https://github.com/neovim/neovim/blob/838277e28a6c8ea600a49292cd2837b155265dc6/runtime/autoload/man.vim#L380-L388

Remove that part of the code into the `man#init_b:sect` function and call that from the syntax file.

Following that, we need to add a call in the `man#init_pager` function to `man#init_b:sect` and then also replace the `man#init_pager` call in the syntax file with `man#init_b:sect`.

Lastly, we need to replace the check at https://github.com/neovim/neovim/blob/838277e28a6c8ea600a49292cd2837b155265dc6/runtime/ftplugin/man.vim#L9 with `let s:pager = has('vim_starting')`

That should be all that is necessary.

**Comment by nhooyr** [comment]
Also, add a comment to the line in the syntax file calling `man#init_b:sect` referencing this issue because its not clear why that line is there.

**Comment by nhooyr** [comment]
Dammit, my suggested solution will not work. The [code](https://github.com/neovim/neovim/blob/838277e28a6c8ea600a49292cd2837b155265dc6/runtime/autoload/man.vim#L380-L387) that finds the section and name of the man page will not work if the escape codes are not deleted.

Gonna think about a better way to fix this while not breaking #5630.

**Comment by nhooyr** [comment]
This code was added into the syntax file because of #5574. However, rather than editing the syntax file, we could just ask users to https://github.com/neovim/neovim/issues/5574#issuecomment-261641128

This means we can just get rid of that entire if statement and assume that the ftplugin is sourced before the syntax file. I think this is the cleanest solution.

**Comment by justinmk** [comment]
> Can't you just get rid of syntax on in your init.vim? There is no need for it in neovim

Unfortunately we can't do that. `syntax on` is still needed if users depend on it happening before they load colorschemes, etc.

**Comment by nhooyr** [comment]
I don't understand, why would users depend on `syntax on` happening before loading colorschemes?

**Comment by nhooyr** [comment]
Ah they would depend on it in case they wanted to style specific syntax groups?
