### ISSUE TITLE
Terminal now has line numbers (respects relativenumber settings)

### ISSUE THREAD

**Issue by gibfahn** [neovim/neovim#6832]
- `nvim --version`: `NVIM v0.2.1-260-g43f40b8e` (homebrew)

<details><summary>Full version info:</summary>

```
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170530-83002-b1dl0v/build/config -I/tmp/neovim-20170530-83002-b1dl0v/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170530-83002-b1dl0v/build/src/nvim/auto -I/tmp/neovim-20170530-83002-b1dl0v/build/include
Compiled by gib@Gibsons-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-43f40b8/share/nvim"
```

</details>

- Vim (version: ) behaves differently: N.A.
- Operating system/version: macOS Sierra
- Terminal name/version: Terminal.app
- `$TERM`: `xterm-256color` (also happens with `TERM= nvim -u NORC`)

### Actual behaviour

Relative line numbers appear in Terminal mode

### Expected behaviour

No line numbers, and no relative line numbers in Terminal mode (which was the case before).

### Steps to reproduce:

```
nvim -u NORC
:set number
:set relativenumber
:term
<C-\><C-n>
7j
```

![image](https://cloud.githubusercontent.com/assets/15943089/26675854/52008cb6-46bd-11e7-96b5-daa9d976a4a5.png)

**Comment by gibfahn** [comment]
Sorry if this is a duplicate.

I did see https://github.com/neovim/neovim/pull/6796 , which suggests that line numbers will now be respected, but relative line numbers won't.

Previously there were no line numbers at all, which seems like the least surprising default to me.

**Comment by justinmk** [comment]
You can set the option locally in a TermOpen autocmd.  The least surprising thing is to not change the user's settings, so we don't. It at least avoids "bounce" if you have `number` enabled.

**Comment by justinmk** [comment]
This is mentioned in the doc as well.

**Comment by gibfahn** [comment]
Sorry, I must have been doing something wrong. This is now working for me:

```
au TermOpen * setlocal nonumber norelativenumber
```

**Comment by mmlb** [comment]
@justinmk the docs state `'relativenumber' is disabled in |Terminal-mode| (and cannot be enabled)`, but I can do `set relativenumber` from a terminal buffer. Am I misinterpreting something? https://asciinema.org/a/XGUyLnBwFwg0VFc6w9OmpxHPa

**Comment by justinmk** [comment]
@mmlb terminal buffer may be in any mode: normal, visual, etc. terminal _mode_ is the "insert mode" of a terminal buffer. This is a separate mode, documented at `:help terminal-mode`.

**Comment by mmlb** [comment]
got it, thanks for the clarification.
