### ISSUE TITLE
colorscheme set in .vimrc, applied improperly when in tty

### ISSUE THREAD

**Issue by physkets** [neovim/neovim#6833]
- `nvim --version`: **0.2.0**
- Vim (version: **8.0.586** ) behaves differently? **Yes! It works as expected in Vim**
- Operating system/version: **Manjaro (rolling release - latest update)**
- Terminal name/version: **konsole 17.04.1**
- `$TERM`: **linux**

### Actual behaviour

In my _.vimrc_, I have the following, which decides the colorscheme:
```
if ( $TERM == 'linux' )
    colorscheme koehler
else
    colorscheme solarized
endif
```
I use this, so that when I use neovim in a tty, I get a colorscheme that works well with the dark background, and 8 colours. Otherwise, when I have 256 colours, and the appropriate backgroud, I use _solarized_.

But, when I now open a file, while on tty, it does not initially use all colours for syntax highlighting. I then have to type `:colorscheme koehler`, which then fixes it.

### Expected behaviour

It should produce the correct colouring that the 'linux' term is capable of producing. When I use Vim, this problem does not occur.

### Steps to reproduce using `nvim -u NORC`

Under this, the colorscheme is set to 'default', so there is no point.

**Comment by justinmk** [comment]
If you are using 0.2.0, you don't have https://github.com/neovim/neovim/pull/6673 which is on master and might fix the issue. cc @jdebp

**Comment by physkets** [comment]
Oh! Cool! In that case, I will wait for it to reach my distro. Thanks!
