### ISSUE TITLE
There is a bug when deleting a whole python-buffer using `del b[:]`

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#6835]
- `nvim --version`: NVIM v0.2.0-1473-g569110
- Vim (version: ) behaves differently? The same.
- Operating system/version: `Linux 2.6.32-504.8.1.el6.x86_64` 
- Terminal name/version: xshell
- `$TERM`: xterm

### Actual behaviour
```python
python << EOF

import vim
import time
with open("aaa.txt", 'r+') as f:
    aaa = f.readlines()
aaa = [line.rstrip("\r\n") for line in aaa]

vim.command("vsp test.txt | setlocal ul=-1")
b = vim.current.buffer
vim.command("hide")

EOF

function! Test()

python << EOF

del b[:] # there is an issue here

vim.command("vsp test.txt")

start = time.time()
b[:] = aaa
print(time.time() - start)

EOF
endfunction

map <F5> :call Test()<CR>
```
source the code, then run test by pressing `<F5>` for several times, close the test.txt buffer window every time before pressing `<F5>`, you will find it takes longer and longer time to set the buffer with `b[:] = aaa`.
If `del b[:]` is removed, everything works well. I think there is a bug here.

### Expected behaviour
It takes nearly the same time every time after pressing `<F5>`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Attachments:

- [issue.vim](https://github.com/Yggdroot/sample/blob/master/issue.vim)
- [aaa.txt](https://github.com/Yggdroot/sample/blob/master/aaa.txt)

**Comment by Yggdroot** [comment]
`NVIM v0.2.1-280-g45d92e2` also has this issue.

**Comment by Yggdroot** [comment]
Find the root cause now. If `set foldmethod=manual`, everything goes well. If `&foldmethod == 'indent'`, there is the issue.
But I think this issue should not exist even though `&foldmethod == 'indent'`.

**Comment by justinmk** [comment]
IIUC this is a general performance problem with the syntax/indent engine. 

Covered by other issues.
