### ISSUE TITLE
How about updating LuaJIT?

### ISSUE THREAD

**Issue by concatime** [neovim/neovim#6836]
THIS IS NOT AN ISSUE.
I wanted to make a pull request, but I saw that the [link](https://github.com/neovim/neovim/blob/c1026ff4b3b6500c06d5a2233214addbb41936cb/third-party/CMakeLists.txt#L96) point to internal LuaJIT [repo](https://github.com/neovim/deps), consisting of [sources](https://github.com/neovim/deps/tree/master/src/luajit) and a raw [tarball](https://github.com/neovim/deps/blob/master/opt/LuaJIT-2.0.4.tar.gz) file.
Since LuaJIT-2.0.5 is [out](https://luajit.org/changes.html), I suggest to migrate.

**Comment by justinmk** [comment]
@concatime PR welcome. Simply change the [link](https://github.com/neovim/neovim/blob/c1026ff4b3b6500c06d5a2233214addbb41936cb/third-party/CMakeLists.txt#L96), then the deps repo will be automatically updated by our CI bot.
