### ISSUE TITLE
:Terminal on Windows is not working

### ISSUE THREAD

**Issue by gynet** [neovim/neovim#6838]
- `nvim --version`:
NVIM v0.2.0
- Operating system/version: 
Windows 10 Version	10.0.15063 Build 15063
- Terminal name/version: 
cmd.exe

### Actual behaviour
Type " :terminal" and it just hang and not accept any input
### Expected behaviour
The terminal should accept commands and output results

**Comment by jamessan** [comment]
This is a known limitation.  It was part of the release notes:

> `:terminal` is not supported on Windows, yet. (Planned for 0.2.1)

There's ongoing work on this issue in #6383.
