### ISSUE TITLE
"qfdo", similar to "argdo" or "g//"

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#684]
I'd hope for a `:qfdo` feature, that combines `:argdo` and `:g`.

What I'm trying to achieve is:

  * Search for some string (`:grep` or `:Ggrep`)
  * For each location, do something. Eg. look whether the same code block has some other string in it, and if it doesn't, add it somewhere.

So it's like `:g//`, but using positions across multiple files. Alternatively, something similar to `:argdo` - but that would run only once per file, and not once per quickfix entry.

Thanks for listening.

**Comment by elmart** [comment]
Closing. This might be nice to consider in a future release.

**Comment by justinmk** [comment]
@elmart Note the milestone is set to "vNext"

**Comment by elmart** [comment]
@justinmk Ok. Just different criteria again. I had noted 'vNext', but thought we wanted to leave open only those relevant for current release. The other ones could be reopened later. Clearly that's not what you were doing. So, reopening.

**Comment by lucc** [comment]
Close in favor of #2927?

**Comment by phmarek** [comment]
Well, I'd think `:qfdo` to be more intuitive, but the feature seems to be the same.

Thanks!

**Comment by fwalch** [comment]
FYI, the other patch also has `:qfdo`, not only `:qdo`.
