### ISSUE TITLE
build warning: TYPVAL_ENCODE_CONV_EMPTY_DICT: nonnull argument ‘tv’ compared to NULL

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#6847]
I have seen this warning since a while when building Neovim:

```
../src/nvim/eval/typval.c: In function ‘_typval_encode_nothing_convert_one_value’:
../src/nvim/eval/typval.c:1737:10: warning: nonnull argument ‘tv’ compared to NULL [-Wnonnull-compare]
       if (tv != NULL) { \
          ^
../src/nvim/eval/typval_encode.c.h:398:9: note: in expansion of macro ‘TYPVAL_ENCODE_CONV_EMPTY_DICT’
         TYPVAL_ENCODE_CONV_EMPTY_DICT(tv, tv->vval.v_dict);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Removing the `if` check seems to fix it, but @ZyX-I should comment on this (according to `git-blame`).

**Comment by ZyX-I** [comment]
This macro is used in more then one place, at least one time it is directly `TYPVAL_ENCODE_CONV_EMPTY_DICT(NULL`.

**Comment by ZyX-I** [comment]
Would suggest to check whether you can construct a cast to remove this warning.
