### ISSUE TITLE
Can't build from source anymore due to -Werror

### ISSUE THREAD

**Issue by pjrt** [neovim/neovim#6848]
I used to be able to build by just doing:

```
sudo rm -rf build
make distclean
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
````

However, at some point in the last month (because I usually rebuild once a month or so) I wasn't able to build anymore due to this error.

```
/home/pjrt/code/vim/neovim/.deps/build/src/msgpack/include/msgpack/unpack_template.h:238:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 ++p;
                 ^~~
/home/pjrt/code/vim/neovim/.deps/build/src/msgpack/include/msgpack/unpack_template.h:240:13: note: here
             default:
             ^~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [CMakeFiles/msgpackc-static.dir/build.make:87: CMakeFiles/msgpackc-static.dir/src/unpack.c.o] Error 1
```

It seems that -Werror is being turned on for me, but I don't see why. Searching for `-Werror` in the codebase shows that -Werror should only be on for CI-Travis. 

Any idea how I could disable it locally?

**Comment by justinmk** [comment]
> It seems that -Werror is being turned on for me, but I don't see why. Searching for -Werror in the codebase shows that -Werror should only be on for CI-Travis.

Distros set some CFLAGS. We do backflips to unset `_FORTIFY_SOURCE` for this reason. I suppose we could do something similar for `-Werror` but it would not always be the right thing to do, unlike with `_FORTIFY_SOURCE`.

see also https://github.com/neovim/neovim/issues/6846

**Comment by pjrt** [comment]
@justinmk Ah, that sucks. 

I'm not sure where I should pass that `-Wnoerror` flag (note that I'm a noob at C and Make). 

Currently I have this `local.mk` file which I call when I want to upgrade:

```
all:

rebuild:
		sudo rm -rf build
		make distclean
		make CMAKE_BUILD_TYPE=RelWithDebInfo -Wnoerror
		sudo make install -Wnoerror
```

**Comment by justinmk** [comment]
Try this:

    make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-Wno-error"

**Comment by pjrt** [comment]
That didn't work :(

I guess I can wait for msgpack's release.

**Comment by jamessan** [comment]
`-Werror` is set by msgpack-c in their own [CMakeLists.txt].

[CMakeLists.txt]: https://github.com/msgpack/msgpack-c/blob/5ebed34376221974ce829148ab27887fe23f6fb8/CMakeLists.txt#L230-L235

**Comment by pjrt** [comment]
msgpack claims to have fixed this in their latest release. It stills fails for me so I'm guessing something needs to be bumped in neovim?

**Comment by FuzzOli87** [comment]
@pjrt Getting the same failure here. It looks like the bundled msgpack is 2.1.1

If you copy ```contrib/local.mk.example``` to the root of the repo as ```local.mk``` and uncomment ```DEPS_CMAKE_FLAGS += -DUSE_BUNDLED_MSGPACK=OFF``` it'll use your system installed msgpack version. 

Now whether or not that breaks anything I can't tell you since I just did it. But if they are following SemVer then it shouldn't.

**Comment by jamessan** [comment]
@FuzzOli87 There are breaking changes between 1.x and 2.x in msgpack-c, but we've already accounted for those in neovim.

@pjrt When #6885 is merged, building the bundled dependencies with gcc-7 should be fixed.
