### ISSUE TITLE
How can i build localization

### ISSUE THREAD

**Issue by jysuk7394** [neovim/neovim#6857]
I want to build localization(ko.UTF-8.po)

The result I want is that the neovim intro and neovim error message is printed in korean.

How can i do it? please help me!

**Comment by teto** [comment]
Check https://github.com/neovim/neovim/wiki/Building-Neovim#localization

`make -C build check-po-ko.UTF-8 `could help for instance

**Comment by justinmk** [comment]
Yes, translations are appreciated. Please send a PR if you can.

**Comment by jysuk7394** [comment]
Thank you for your help. I've done what you told me, but the language of nvim will continue to be output in English. How can I print the neovim intro part in Korean?  I would like a little more detailed explanation.

**Comment by justinmk** [comment]
You probably need to `make install` after editing the file. Then make sure `:lang` shows the expected language.
