### ISSUE TITLE
Neovim for windows on cygwin

### ISSUE THREAD

**Issue by sohnryang** [neovim/neovim#6865]
- `nvim --version`:

```
NVIM v0.2.1-25-g2e3b78d1
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw32/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw32/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
- Vim (version: 8.0) behaves differently? yes.
- Operating system/version: Windows 7/10 (running cygwin)
- Terminal name/version: Cmder 2016.12.6
- `$TERM`: xterm-256color

### Actual behaviour

I fire up neovim with `nvim` command.

It shows a error.

```
E484: Can't open file /etc\syntax\syntax.vim
```

### Expected behaviour

The neovim should start.

### Steps to reproduce using `nvim -u NORC`

Type this command
```
nvim -u NORC
```

**Comment by justinmk** [comment]
> Vim (version: 8.0) behaves differently? yes.

No, the win32 version of Vim does not run in cygwin. It just happens that you are running the cygwin build of vim, which is included with cygwin.

Nvim cygwin support is covered by https://github.com/neovim/neovim/issues/873#issuecomment-292168963

**Comment by sohnryang** [comment]
Then how can I build neovim on cygwin?

I can't build neovim with this command.

```
make CMAKE_BUILD_TYPE=RelWithDebInfo
```

Also, I heard it is [impossible](https://gist.github.com/equalsraf/efa3337718cd973de5713c3a84b10fc7).

**Comment by sohnryang** [comment]
It seems it fails when building lua-related component.
