### ISSUE TITLE
Repaint issues with vertical split windows

### ISSUE THREAD

**Issue by urandom** [neovim/neovim#6866]
- `nvim --version`:
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/build/config -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/src -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/.deps/usr/include -I/usr/include -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/build/src/nvim/auto -I/build/neovim-4mniNA/neovim-0.2.0ubuntu1+git201706071405+3465+26~ubuntu17.04.1/build/include
Compiled by root@lcy01-08

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Operating system/version:
ubuntu 17.04
- Terminal name/version:
tilix 1.5.8/gnome-terminal 3.20.2
- `$TERM`: xterm-256color

### Actual behaviour
Vertical repaint issue on scrolling. The contents of the non-scrolling window starts to disappear as if it's being scrolled as well. It repaints itself line by line when it's active and the cursor line is being moved.

Horizontal split has no issues.

### Expected behaviour
No repaint issues.

### Steps to reproduce using `nvim -u NORC`
Open a sufficiently long file
```
nvim -u NORC $file

```
:vsplit

// start scrolling

**Comment by jamessan** [comment]
This is likely the same as https://github.com/neovim/neovim/issues/6802 which should be improved by https://github.com/neovim/neovim/pull/6816, if you're able to test that out.
