### ISSUE TITLE
Starting a job from a timer callback while `d` for deletion is active deletes a line

### ISSUE THREAD

**Issue by w0rp** [neovim/neovim#6867]
- `nvim --version`: 0.17 and 0.2.1-dev (That's what I tested with)
- Vim 8 doesn't have the same issue.
- Operating system/version: Kubuntu Linux
- Terminal name/version: Konsole 16.12.3
- `$TERM`: xterm-256color

### Actual behaviour

A line is deleted.

### Expected behaviour

The line shouldn't be deleted, as I didn't press anything else.

### Steps to reproduce using `nvim -u NORC`

Create a file, say `~/test.vim`, containing the following

```vim
function! StartJob(...) abort
    call jobstart('echo foo')
endfunction

call timer_start(1000, function('StartJob'))
```

Then open a file with some lines in it, like so.

```
a
b
c
```

Move to the last line in the file, type `:source ~/test.vim` or whatever your filename is to run the VimL code above, and press the `d` key before the timer expires without pressing any other keys. After the call to `jobstart()`, the line will be deleted.

This issue was first reported in ALE here: https://github.com/w0rp/ale/issues/529

**Comment by jamessan** [comment]
Likely the same root cause as #6166.

**Comment by w0rp** [comment]
Yeah, that is probably true.
