### ISSUE TITLE
Chocolatey uses a weird installation path

### ISSUE THREAD

**Issue by terrycloth** [neovim/neovim#6872]
Sorry, if this has been answered somewhere already, I couldn't find it... I just installed neovim 0.2.1-25-g2e3b78d1 from the Chocolatey CLI 0.10.6.1 on Windows 10 x86_64 Home Edition version 1703, OS Build 15063.332.

nvim and nvim-qt seem to work as usual, except that `choco` used a strange default installation path: `C:\Windows\SysWOW64\Get-ToolsLocation\neovim\Neovim`. Why would it be installed anywhere other than `Program Files`? And if installing to a nonstandard location, why not add it to the Path environment variable?

I thought at first that the Chocolatey installer script was broken, and it took a while to find the nvim executable.

**Comment by jamessan** [comment]
We don't maintain Chocolatey or its installation recipe for neovim.  You would need to discuss this with the Chocolatey folks.

**Comment by terrycloth** [comment]
That would explain why I couldn't find it documented anywhere. 😝 Thanks.
