### ISSUE TITLE
[Question] A Todo-List / Tasks plugin?

### ISSUE THREAD

**Issue by piotryordanov** [neovim/neovim#6873]
Is there a `neovim` plugin that works like a `todo` where i can create lists, sublists, complete tasks, archive them etc.. 

Something similar to the `[tasks](https://atom.io/packages/tasks)` plugin in atom.

**Comment by guyzmo** [comment]
this question would better be suited for the [vim-use](https://groups.google.com/forum/#!forum/vim_use) mailing list than this bug tracking. For your question, you will find [vim-wiki](https://github.com/vimwiki/vimwiki) useful.

Some other resources you might want to check out:

- https://www.reddit.com/r/vim/comments/4ms4z0/org_mode_which_plugin_to_use_vimorganizer_or/
- https://www.slant.co/versus/2124/8769/~vimwiki-plugin-for-vim_vs_org-mode

**Comment by piotryordanov** [comment]
I think i don't completely understand how `vim` plugins work with `neovim`. I'll look more into the resources. Thank you very much :)
