### ISSUE TITLE
TUI gliches when scrolling splitted windows

### ISSUE THREAD

**Issue by clobrano** [neovim/neovim#6884]
- NVIM v0.2.1-dev
- VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35) does not show the same issue.
- OS:	Ubuntu 17.04
- $TERM: xterm-256color
- GNOME Terminal 3.20.2

### Actual behaviour

Vertical splitted windows do not scroll independently.
When one window scrolls, the other scrolls as well and shows glitches (some text disappears, some is changed).

This behavior appeared only after upgrade to nvim 0.2.1-dev from a version <0.2 (sorry but I don't remember witch version, the only thing I know for sure is that it wasn't 0.2.0)

### Expected behaviour
Vertical splitted windows scroll independently and no glitches appears (as in VIM)

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:e <file>
:vsplit
[scroll one of the two windows with keys]
```

**Comment by jamessan** [comment]
This is likely the same as https://github.com/neovim/neovim/issues/6802 which should be improved by https://github.com/neovim/neovim/pull/6816, if you're able to test that out.
