### ISSUE TITLE
drag and drop not supported on Windows

### ISSUE THREAD

**Issue by bon-ami** [neovim/neovim#6886]
- `nvim --version`: 0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? 8.0.3
- Operating system/version: Windows 7
- Terminal name/version:
- `$TERM`:

### Actual behaviour
drag a text file into Neovim from Explorer. Nothing happens.
### Expected behaviour
It is opened

**Comment by jamessan** [comment]
Even in Vim this was a GUI-specific feature.  This support would need to be implemented in the various GUI front-ends.
