### ISSUE TITLE
initial window too small

### ISSUE THREAD

**Issue by bon-ami** [neovim/neovim#6887]
- `nvim --version`:0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently?8.0.3
- Operating system/version:Windows 7
- Terminal name/version:
- `$TERM`:

### Actual behaviour
nvim-qt.exe opens with only three lines and 25 columns of input area.
### Expected behaviour
its size is the last time I close it, at least the size of a normal application.

**Comment by jztsaurabh** [comment]
getting same issue in
OS: windows 10
terminal name: default NeoVim terminal

**Comment by jamessan** [comment]
This is a neovim-qt [issue](https://github.com/equalsraf/neovim-qt/issues/251).
