### ISSUE TITLE
Terminal colors using Base16

### ISSUE THREAD

**Issue by KevinSjoberg** [neovim/neovim#6897]
- `nvim --version`: 

NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170511-4071-ij6a26/neovim-0.2.0/build/config -I/tmp/neovim-20170511-4071-ij6a26/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170511-4071-ij6a26/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170511-4071-ij6a26/neovim-0.2.0/build/include
Compiled by kevinsjoberg@Kevins-MacBook-Pro.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"

- Operating system/version:

Mac OS 10.12.5

- Terminal name/version:

iTerm 2 Build 3.0.15

- `$TERM`:

xterm-256color

### Actual behaviour

I'm using [Base16 Shell](https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-default-dark.sh) together with the [Base16 iTerm2 256 color variation](https://github.com/chriskempson/base16-iterm2/blob/master/base16-default.dark.256.itermcolors) and [Base16 Vim](https://github.com/chriskempson/base16-vim/blob/master/colors/base16-default-dark.vim). The [Base16 Shell](https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-default-dark.sh) is being sourced within my `.bashrc` like follows:

```
[ -f "$HOME/.config/base16-shell/scripts/base16-default-dark.sh" ] && . "$HOME/.config/base16-shell/scripts/base16-default-dark.sh"
```

It works perfectly. Running [colortest](https://github.com/chriskempson/base16-shell/blob/master/colortest) yields the correct results.

**In iTerm2**
![iterm](https://user-images.githubusercontent.com/503025/27169467-54680df6-51aa-11e7-82f3-cb5a80a9730d.png)

**In tmux**
![tmux](https://user-images.githubusercontent.com/503025/27169481-5ef85ec4-51aa-11e7-9838-6ad31a87fb90.png)

In Neovim however, running colortest in the terminal emulator (`:term`) yields the incorrect result.

**Neovim with `set termguicolors`**
![neovim](https://user-images.githubusercontent.com/503025/27169550-9dd08b94-51aa-11e7-8671-0ebffad330d8.png)

**Neovim with `set notermguicolors`**
![neovim-no-true-color](https://user-images.githubusercontent.com/503025/27169672-1f8d7c28-51ab-11e7-869a-5e8d1cc94a66.png)

### Expected behaviour

I'd expect the colors to be correct within Neovim's terminal as well.

**Comment by justinmk** [comment]
This is covered in closed issues as well as :help terminal-config

**Comment by KevinSjoberg** [comment]
@justinmk I honestly tried to find previous issues before creating this one. Would you mind linking an issue covering this? `:help terminal-config` doesn't exist.

**Comment by KevinSjoberg** [comment]
The colorscheme I'm using is setting the `{g,b}:terminal_color_$NUM` variables.

```vim
  let g:terminal_color_0 =  "#181818"
  let g:terminal_color_1 =  "#ab4642"
  let g:terminal_color_2 =  "#a1b56c"
  let g:terminal_color_3 =  "#f7ca88"
  let g:terminal_color_4 =  "#7cafc2"
  let g:terminal_color_5 =  "#ba8baf"
  let g:terminal_color_6 =  "#86c1b9"
  let g:terminal_color_7 =  "#d8d8d8"
  let g:terminal_color_8 =  "#585858"
  let g:terminal_color_9 =  "#ab4642"
  let g:terminal_color_10 = "#a1b56c"
  let g:terminal_color_11 = "#f7ca88"
  let g:terminal_color_12 = "#7cafc2"
  let g:terminal_color_13 = "#ba8baf"
  let g:terminal_color_14 = "#86c1b9"
  let g:terminal_color_15 = "#f8f8f8"
  let g:terminal_color_16 = "#dc9656"
  let g:terminal_color_17 = "#a16946"
  let g:terminal_color_18 = "#282828"
  let g:terminal_color_19 = "#383838"
  let g:terminal_color_20 = "#b8b8b8"
  let g:terminal_color_21 = "#e8e8e8"
  let g:terminal_color_background = g:terminal_color_0
  let g:terminal_color_foreground = g:terminal_color_7
  if &background == "light"
    let g:terminal_color_background = g:terminal_color_7
    let g:terminal_color_foreground = g:terminal_color_2
  endif
```

They variables are present when checking their values but `colortest` still reports the wrong. Would appreciate any light in this matter.

**Comment by cwegener** [comment]
I'm looking for the same information.

`:help terminal-config` seems unrelated to the issue.
