### ISSUE TITLE
just regular navigation and insert is slow

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#6899]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? NVIM v0.2.0
- Operating system/version: Darwin nero.local 16.0.0 Darwin Kernel Version 16.0.0
- Terminal name/version: iterm2
- `$TERM`:  screen-256color

### Actual behaviour
slow
### Expected behaviour
fast

### Steps to reproduce using `nvim -u NORC`

1.  press and hold `i`

I noticed navigating the file using `h`,`j`,`k`,`l` buttons was pretty brutally slow. When I tried the same in `vim` I'm not having problems. 

Doing the same in `vim` is far faster than `nvim` for me at this time.

**Comment by mhinz** [comment]
You can reproduce this slowness with `nvim -u NORC` in _any_ filetype?

**Comment by justinmk** [comment]
This just started happening? You just installed 0.2?  Comparing it to which version?

**Comment by danielb2** [comment]
> You can reproduce this slowness with nvim -u NORC in any filetype?

just a blank file is what I used to test it.

> This just started happening? You just installed 0.2? Comparing it to which version?

I've had 0.2 for awhile, but I thought it was just my computer being slow because I was doing some video encoding for a bit too.

I just tried this on my FreeBSD machine and I can't reproduce it there

**Comment by justinmk** [comment]
Could be showcmd and ruler options. Make sure you are comparing identical settings. 

    :set

shows all settings.

**Comment by justinmk** [comment]
And I bet Terminal.app isn't slow. Iterm is just slow, I don't know how anyone can use it.

**Comment by danielb2** [comment]
settings are the same.

So i did manage to find out some more things.

Terminal.app it works about the same for both nvim and vim

The bigger difference seems to be `nvim + tmux (split screen) + iterm` vs `vim + tmux (split screen) + iterm`

**Comment by justinmk** [comment]
And you aren't using master? Could you try https://github.com/neovim/neovim/pull/6816

**Comment by danielb2** [comment]
I'm closing this because I found that when I edit files I really care about, there's no noticeable speed decrease in nvim. Thanks for the help
