### ISSUE TITLE
How to persist the terminal?

### ISSUE THREAD

**Issue by piotryordanov** [neovim/neovim#6900]
I love the `:term` feature, but I can't seem to wrap my head around it. Docs and Wiki didn't help!

My desired behavior is to open `:term` in a new buffer and run something like `nodemon myserver.js`, then go back to my buffer and edit normally only to jump back there to read error logs or restart the server. Essentially, this would totally remove the need for `iterm` tabs, or `tmux`.

However, whenever I quite the term buffer using `<c-\><c-N>` or by simply clicking on a buffer in the `statusline`, whatever was running in the `term` session dies. 

Is this how things are supposed to be, or did I miss something in the docs?

Thank you!

**Comment by mhinz** [comment]
The statusline usually doesn't show any buffer one could click on. (Do you mean the tabline?) Also just pressing `<c-\><c-n>` shouldn't end anything, just switch from terminal to normal mode.

1. Do `:set hidden` and try again.
2. If (1) didn't work, can you reproduce it with `nvim -u NORC`?

**Comment by piotryordanov** [comment]
`:set hidden` solved the problem. Thank you 👍 

I'm not sure if it is the statusline or not. I was referring to the topbar that `Airline` creates.

Thanks for the swift response!

**Comment by piotryordanov** [comment]
Btw, if i exit the term buffer then get back to it, I need to scroll down to bottom with `gg`. Is there a way to always have this happen on buffenter?

**Comment by mhinz** [comment]
Hm, that too shouldn't happen by default. At least I can't reproduce it with `nvim -u NORC`. The cursor is always at the bottom for me.

Maybe you prefer to get back into terminal mode right away anyway. I'm using this:

```vim
if has('nvim')
  autocmd BufEnter term://* startinsert
endif
```

**Comment by piotryordanov** [comment]
Alright, that does it for me. Thx!
