### ISSUE TITLE
Completely broken scrolling with split buffers (e.g. :vsp)

### ISSUE THREAD

**Issue by haasn** [neovim/neovim#6901]
- `nvim --version`: NVIM v0.2.1-339-gf8e3bc63e
- Vim (version: 8.0.0386-r1) behaves differently? Yes
- Operating system/version: Gentoo Hardened ~amd64
- Terminal name/version: rxvt-unicode-9.22-r1
- `$TERM`:rxvt-unicode-256color

### Actual behaviour
Scrolling around in one buffer displaces and eventually completely corrupts the parts of the screen containing other buffers.

### Expected behaviour
Buffers scroll independently and without visual corruption.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# insert a few hundred lines
:vsp
# scroll around in first buffer
```

### Additional information

0de7b17d03e2de18adcc9e7db27483160c4ac052 is the first bad commit according to `git bisect`

**Comment by haasn** [comment]
Image example of corruption:

![corruption](https://0x0.st/lHU.png)

No idea how this has managed to stay in master for so long. Is it only affecting me?

**Comment by jamessan** [comment]
This is likely the same as https://github.com/neovim/neovim/issues/6802 which should be improved by https://github.com/neovim/neovim/pull/6816, if you're able to test that out.

> No idea how this has managed to stay in master for so long.

Master can break.  If you don't want to deal with that, then use the releases.  While we try to keep master stable, sometimes we don't find issues until something lands or we know something's not quite complete but we want broader feedback.

> Is it only affecting me?

No, it's been reported numerous times.

**Comment by haasn** [comment]
> Master can break. If you don't want to deal with that, then use the releases. While we try to keep master stable, sometimes we don't find issues until something lands or we know something's not quite complete but we want broader feedback.

Fair enough, the problem is that I tried downgrading to the latest release assuming it would be stable and all that happened is that it started randomly crashing on me instead. :D
