### ISSUE TITLE
Running Terminal Command In New Tab Causes Status Text to Be Displayed as First Line

### ISSUE THREAD

**Issue by jfelchner** [neovim/neovim#6902]
- NVIM v0.2.1-182-g6e4e70f5
- Vim 8.0 behaves differently? Yes
- Operating system/version: macOS 10.12
- Terminal name/version: iTerm2
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
echo "foobar" > hello.txt
nvim -u NORC hello.txt
```

paste the following into the command line:

```vim
function! g:RunTerminalCommand()
  tabnew %

  execute 'term echo abc e'
endfunction
```

then run:

```vim
exec g:RunTerminalCommand()
```

You'll notice that `-- TERMINAL --` shows up as the first line in the terminal output in the new tab before the command is even run.  This happens to be `-- TERMINAL --` here but can be anything that is in the status bar in other situations.

Additionally whenever the `echo` happens, where the `d` should be, it simply shows the `T` from `TERMINAL` because any spaces don't put a literal space but instead just skip over the text that was there.  This seems significant.

**Comment by jfelchner** [comment]
BTW, this used to work on a previous version of Neovim but broke when I upgraded to `g6e4e70f5`.

**Comment by jfelchner** [comment]
Also FWIW this happens in many other situations where random status line jibberish shows up and sometimes even a `redraw!` doesn't fix it.  But the above situation is the only basic reproducible scenario I could come up with.

**Comment by justinmk** [comment]
What was the previous version that didn't have this issue? Or roughly how old was it? Was it after the 0.2 release?

**Comment by jfelchner** [comment]
@justinmk I want to say that it was prior to 0.2.0 where the behavior was correct. I want to say that I was on 0.1.0 stable but I'm not 100%.

**Comment by justinmk** [comment]
cannot reproduce with  v0.4.0-631 24a9516ff
