### ISSUE TITLE
None of the vim built-in functions seem to be available

### ISSUE THREAD

**Issue by kheaactua** [neovim/neovim#6903]
- `nvim --version`: v0.2.1-25-g2e3b78d1
- No built-in functions seem to be available
- Operating system/version: Windows 10
- Terminal name/version: Powershell
- Installed with `choco`
- Manually added nvim to my environment's `$env:path`

### Actual behaviour

None of the system commands seem to work.  i.e. this is what I got from tying to use fzf
```
Error detected while processing c:\tmp\tmp.vim
line 3:
E492: Not an editor command: system("git-rev-parse --show-toplevel", a)
```

So I wrote a little `tmp.vim` file where I tried other built in functions like `str2float`, *etc*, and I got the same error.

Then I opened nvim without a `.vimrc`, *i.e*.  `nvim -u /NUL`, and I still couldn't run system commands.

### Expected behaviour

To run the `system` command

### Steps to reproduce using `nvim -u NORC`

Create a vim file with a build-in function in it, 
`c:\tmp\tmp.vim`:
```
system("git status")
```

```
nvim -u NORC c:\tmp\tmp.vim
```
Then source it
`:so %`

**Comment by jamessan** [comment]
`system()` is a function, not a command.  You have to `:call` it or otherwise use it as part of a statement.  Any of

```vim
let out = system('git status')
echo system('git status')
call system('git status')
```

will work, depending on what you're trying to do.
