### ISSUE TITLE
Double clicking left mouse button on tags doesn't work

### ISSUE THREAD

**Issue by iaz3** [neovim/neovim#6904]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently? 8.0. Vim has the expected behaviour
- Operating system/version: Arch Linux
- Terminal name/version: Konsole 17.04.2
- `$TERM`: xterm-256color

### Actual behaviour
In nvim: Double clicking tags selects the subject name.

In vim: Double clicking tags jumps to the subject.

### Expected behaviour
nvim: Double clicking tags jumps to the subject.

vim: Actual

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

Start nvim

type :helpbars

Double Click on "bars" example tag
```

**Comment by jdebp** [comment]
I can reproduce this with nvim 0.2.1 but it is not what is stated and nvim is working as documented.  When I invoke nvim with `nvim -u NORC` I get `mouse=`.  The highlighting of the word "bars" is being done by the terminal emulator.  

You can demonstrate this with 0.2.1:
* Use `nvim -u NORC -c 'set mouse=|help bars'`, move the nvim cursor up a few lines, and then left-double-click on "bars".  The nvim cursor does not move and the help window remains where it is.
* Use `nvim -u NORC -c 'set mouse=a|help bars'`, move the nvim cursor up a few lines, and then left-double-click on "bars".  The nvim cursor moves and the window is scrolled to place "bars" at the top.

**Comment by iaz3** [comment]
How come this behavior doesn't work by default in nvim, but does in vim?

How can i get the desired behavior?

Should the help page be updated to describe actual nvim behavior then?

**Comment by fmoralesc** [comment]
@iaz3 You should use `set mouse=a` (or `set mouse=h` if you only want to use the mouse in help files).

@justinmk Do you think the default for `mouse` should be changed to `h`, if not `a`?

**Comment by iaz3** [comment]
how do i do that?

**Comment by fmoralesc** [comment]
You add that to your init.vim file, which should be at ~/.config/nvim/init.vim (you might need to create it).

**Comment by justinmk** [comment]
> How come this behavior doesn't work by default in nvim, but does in vim?

It won't work in Vim if you create a vimrc.
