### ISSUE TITLE
Deadlock test in server_requests_spec.lua hangs on the OS X QB node...

### ISSUE THREAD

**Issue by jszakmeister** [neovim/neovim#6905]
I haven't had time to track down why, but the following test hangs in `server_requests_spec.lua` on the OS X node:

```lua
  describe('when connecting to its own pipe adress', function()
    it('it does not deadlock', function()
      local address = funcs.serverlist()[1]
      local first = string.sub(address,1,1)
      ok(first == '/' or first == '\\')
      local serverpid = funcs.getpid()

      local id = funcs.sockconnect('pipe', address, {rpc=true})

      funcs.rpcrequest(id, 'nvim_set_current_line', 'hello')
      eq('hello', meths.get_current_line())
      eq(serverpid, funcs.rpcrequest(id, "nvim_eval", "getpid()"))

      eq(id, funcs.rpcrequest(id, 'nvim_get_api_info')[1])
    end)
  end)
```

The hang occurs when calling `nvim_set_current_line`.  I'm not sure what the hang up is, but the test never moves beyond there.  I'm also not sure what to do about a test like this.  Hanging things up is bad.  It'd be nice if there was a way to stage things so that the test could be recognized as a failure and move on.

This appears to always happening on the OS X node, which is why QB is failing every time.

**Comment by justinmk** [comment]
Thanks for the heads up, we are working on this in https://github.com/neovim/neovim/pull/6851

**Comment by justinmk** [comment]
The hint about `nvim_set_current_line` is recorded in the commit message for ca4633bfe4d0f58bd5fb7343d282fafb71f3a3ee, so I think this issue can be closed.
