### ISSUE TITLE
man.vim: mdocml does not support reading from a path

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#6906]
@pickfire reported this in https://github.com/neovim/neovim/issues/5240#issuecomment-308612803

mdocml's `man` does not support reading from a path but man.vim needs to.

I think the easiest fix here is to open a issue with mdocml requesting that a flag be added to allow reading from a path.

Though, I don't think it is absolutely necessary for man.vim to be reading from a path. Its been over a year so I don't remember why I added it. I'll try and see if it is really required or it was just for simplification. If it turns out its not necessary, I'll create a PR to fix this issue.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/9120 implies that man.vim works with systems using `mdocml`.
