### ISSUE TITLE
sub-replace-expression fails

### ISSUE THREAD

**Issue by aklt** [neovim/neovim#6910]
- `nvim --version`: NVIM 0.2.1-dev

- Vim (version: v8.0.0069) behaves differently, yes!

- Operating system/version: Arch Linux kernel 4.11.3
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: screen-256color

### Actual behaviour
I have a script that I test with both vim and nvim and there seems to
be a bug in nvim.  Vim does not error, but nvim performs a bad substitution:

    https://travis-ci.org/aklt/rel.vim/builds/244342842#L4303

Instead of making a substitution resulting in `when compiled` nvim 
inserts the `sub-replace-expression` into the string resulting in 
`when=nr2char("0x"\ .\ submatch(1))compiled`

The culprit is this expression in `rel.vim`:

````vimL
let needle = escape(substitute(needle,                                                                                        
     \ '%\(\x\x\)', '\=nr2char("0x" . submatch(1))', 'g'), ' ')  
````
The code is here: https://github.com/aklt/rel.vim/blob/nvim-bug/plugin/rel.vim#L113

### Expected behaviour
I expected nvim to behave as vim and replace %20 with a space and not wth
the expression. 

### Steps to reproduce using `nvim -u NORC`

I have tried to isolate a simpler case, but I have failed in the time I had.  The bug should be possible to reproduce by cloning:

    https://github.com/aklt/rel.vim.git

and running `./test.sh`

**Comment by ZyX-I** [comment]
AFAIK this is what you will see should you try to use `\=` in replacement while evaluating `\=` in replacement: Vim used to fail that silently in this exact manner, but now does not so. E.g. check

    echo substitute('a', '.', '\=substitute(submatch(0), ".", "\\=1", "")', "")

(in Vim this echoes `1`, in Neovim `=1`). So this is a matter of porting some yet unparted match.

**Comment by aklt** [comment]
I would like to also mention that tried one variation.  instead of `'\=...'` i used a `funcref('s:SomeFunc')` to a function that does the replacement and the behaviour was the same.

**Comment by justinmk** [comment]
@aklt does it happen in vim 7.4?

**Comment by aklt** [comment]
@justinmk I have tried to get my rel.vim script to function in vim 7.4, but there is some issue with `funcref()`s that's keeping it from working properly.  I bisected to find the minimum vi version needed to get it running and came to vim v8.0.0020 as the minimum vim
version where everything works correctly, see:

    https://github.com/vim/vim/commit/6100d02aab7c8294b581cb299250eea164b50e9d

which makes me think that there was a problem with using funcref's and the regex engine
not being reentrant before that vim version.  I did not look deeply into this, though.

**Comment by aklt** [comment]
@ZyX-I is right and the same is true for funcrefs in vim74:

```vimL
fun! s:Foo(a)
  return substitute(a:a[0], '\w\+', '\="0x" . submatch(0)', 'g')
endfun

echomsg s:Foo(['a b c', 'a b c'])
echo substitute('a bee is not an a', '\w\+', funcref('s:Foo'), 'g')
```
this outputs
```
0xa 0xb 0xc
="0x" . submatch(0) ="0x" . submatch(0) ="0x" . submatch(0) ="0x" . submatch(0) ="0x" . submatch(0) ="0x" . submatch(0)
```
but in vim >= 8.0.0020 it outputs
```
0xa 0xb 0xc
0xa 0xbee 0xis 0xnot 0xan 0xa
```

**Comment by jamessan** [comment]
Ok, then this will be addressed as we continue to merge Vim patches.

**Comment by aklt** [comment]
Alright.  Can you estimate if this is on the horizon?

**Comment by jamessan** [comment]
The fix was just merged to master.

**Comment by aklt** [comment]
Nice, thanks!
