### ISSUE TITLE
Cursorshape a underscore a bar with `rhysd/clever-f.vim`

### ISSUE THREAD

**Issue by zhou13** [neovim/neovim#6913]
- `nvim --version`:
````
NVIM v0.2.1-339-gf8e3bc63
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170616-13628-1xng0hg/build/config -I/tmp/neovim-20170616-13628-1xng0hg/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170616-13628-1xng0hg/build/src/nvim/auto -I/tmp/neovim-20170616-13628-1xng0hg/build/include
Compiled by yichao.zhou

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f8e3bc6/share/nvim"
````
- Vim (version: ) behaves differently?
Yes
- Operating system/version:
MacOS
- Terminal name/version:
iTerm2
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`
1.  Install plugin `Plug 'rhysd/clever-f.vim'`

2. Open an empty file, e.g., ':tabe'

3.  Type `iaaaa<Esc>0dfa`

### Actual behaviour

Cursor shape becomes a underscore

### Expected behaviour

Cursor shape shouldn't change.

### workaround
To change the cursor back, press `fa`.

**Comment by teto** [comment]
i think you are missing an escape before the 0 ?
Shape depends on you guicursor configuration, cursor enters pending mode I believe but after the operation it is restored here.

**Comment by zhou13** [comment]
>i think you are missing an escape before the 0 ?

Github eats everything within `<>`.  I edited the description.

> Shape depends on you guicursor configuration

with both `guicursor=` and default guicursor, I can reprocedure this bug.  

> Shape depends on you guicursor configuration, cursor enters pending mode I believe but after the operation it is restored here.

The bug is that after `dfa` nvim does not restore the cursor shape.

**Comment by jdebp** [comment]
Is rhysd/clever-f.vim a necessary part of this?  Can this be reproduced without that plug-in?

**Comment by zhou13** [comment]
No.

**Comment by justinmk** [comment]
Is clever-f setting `guicursor` ?

**Comment by justinmk** [comment]
No reply, assuming this is a plugin bug.

**Comment by rhysd** [comment]
Note: This is an expected behavior. When operator pending mapping (in this case, `d`) is entered, cursor shape is changed to underscore. clever-f.vim does not affect the cursor shape. So cursor shape remains to be underscore.

**Comment by zhou13** [comment]
@rhysd Why this is expected?  How can I continue to use neovim after a `dfx`...

**Comment by zhou13** [comment]
@rhysd This seems to be a plugin bug.  After I disable `g:clever_f_hide_cursor_on_cmdline`, everything works.

In `clever_f`, it has
````
if g:clever_f_hide_cursor_on_cmdline
    let guicursor_save = &guicursor
    set guicursor=n:block-NONE
    let t_ve_save = &t_ve
    set t_ve=
endif
````
