### ISSUE TITLE
Neovim doesn't redraw window expanded by mouse events

### ISSUE THREAD

**Issue by alexbyk** [neovim/neovim#6919]
This is a dup. of
https://github.com/vim-airline/vim-airline/issues/1496#issuecomment-310583285
because it may be a neovim issue

#### environment

- vim: NVIM 0.1.7
- vim-airline: fde2511201399048e34f8e9460d8c6cb5cb066d8
- OS: Ubuntu 16.04
- Have you reproduced with a minimal vimrc: yes
- What is your airline configuration: ???
if you are using terminal:
- terminal: GNOME TERmINAL
- $TERM variable: xterm-256color
- color configuration (:set t_Co?):
if you are using Neovim:
- does it happen in Vim: no

#### actual behavior

![](http://alexbyk.com/neovim-full.png)

## Description
When I use neovim with this plugin, expanding window by double clicking on the title or by clicking on the "expand window button" doesn't affect neovim aria. Expanding by CTRL+SUPER+UP works ok by the way. Without this plugin all works fine.

**Comment by justinmk** [comment]
CTRL-L redraws the window. This is a known issue.

**Comment by alexbyk** [comment]
@justinmk I tried, CTRL-L and :redraw! doesn't have any affect on this
