### ISSUE TITLE
Jokes in documentation

### ISSUE THREAD

**Issue by gwerbin** [neovim/neovim#6922]
Should we keep jokes in the documentation?

I just made a PR for a particular joke removal (https://github.com/neovim/neovim/pull/6921), because the docs were already making my head hurt and the pun in question only made it hurt worse.

Then I found https://github.com/neovim/neovim/blob/09f849b60000c2d401d82f2b2fb2badde5583658/runtime/doc/index.txt#L1052. My first instinct was to amend my PR to delete this line too, but something made me think twice.

Are these jokes precious to the community at all? Do they make the docs friendlier, or are they distracting? Should I/we be on the lookout to delete them?

**Comment by jamessan** [comment]
My suggestion would be to take this up with upstream if you want to see a change.  I don't see a reason to deviate on these, since all it's going to do is make it harder for us to merge runtime changes with no real gain.

**Comment by justinmk** [comment]
Agree with @jamessan
