### ISSUE TITLE
Unicode display incorrect for bang command

### ISSUE THREAD

**Issue by letientai299** [neovim/neovim#6923]
- `nvim --version`:
```
NVIM v0.2.1-dev
Build type: RelWithDebInfo
```

- Operating system/version:

```
> uname -a
Linux PC 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Terminal name/version:

```
> echo $TERM
xterm-256color
```

### Actual behaviour

- Unicode display incorrectly when running extenal program using bang syntax (`!`)

### Expected behaviour

- Unicode should be display correctly.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:silent !echo Xin chào

```

Result:

![image](https://user-images.githubusercontent.com/8386780/27505646-7fdd2e2e-58d7-11e7-81f3-356c75978c71.png)

Note that if we read the output to vim buffer, then the result is correct. I think this is an encoding issue.

**Comment by justinmk** [comment]
Most likely `:lang` is wrong or `$LC_ALL`. Does `:te echo Xin chào` work?

Covered by other open issues.

**Comment by bfredl** [comment]
The issue is that `:!` output is horribly broken in general. But there is probably an issue for that already as well...

**Comment by letientai299** [comment]
@justinmk `:te echo Xin chào` work. Thanks for the hint. I can use that tip as a workaround for my workflow. But I would like to solve the original issues also.

I've tried `export LC_ALL=en_US.UTF-8`, and in vim, `:lang` show the correct language (en_US.UTF-8). nvim `:terminal` and all other kinds of buffer work as expected. Only bang `!` fails.

 Could you give me some hints to troubleshoot further?
