### ISSUE TITLE
Multiline copy and paste between vertical split windows mess up display

### ISSUE THREAD

**Issue by altunyurt** [neovim/neovim#6925]
- `nvim --version`: v0.2.1-dev
- Vim (version: ) behaves differently? yes
- Operating system/version: linux mint 4.10.0-22-generic
- Terminal name/version: xfce4-terminal 0.6.3
- `$TERM`:xterm-256color

### Actual behaviour
multi line copy and pasting between two vertical splitted files mess up the source window. target window is displayed correctly, but the source window behaves as if it has also been pasted in some blank lines. Please see the screenshots 

![1](https://user-images.githubusercontent.com/126674/27516808-b4521a1e-59c9-11e7-95a3-b44c1c92f03f.png)

![2](https://user-images.githubusercontent.com/126674/27516812-bcdf12f4-59c9-11e7-957e-eaf8837c8f86.png)
![3](https://user-images.githubusercontent.com/126674/27516811-bcd5520a-59c9-11e7-82ef-fbf1e4801d00.png)

### Expected behaviour

source window should not be affected 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

**Comment by justinmk** [comment]
TUI issue. Covered by other issues. Try https://github.com/neovim/neovim/pull/6816
