### ISSUE TITLE
rpcstop() in VimLeave causes assertion in wstream_write

### ISSUE THREAD

**Issue by SanD94** [neovim/neovim#6926]
- `nvim --version`: v0.2.1-dev
- Vim (version: 7.4) behaves differently? No problem
- Operating system/version: Ubuntu 16.04
- Terminal name/version: tmux 2.1
- `$TERM`: screen-256color

### Actual behaviour

after :wq command, this error is occurred:
``nvim: /build/neovim-nR03bp/neovim-0.2.0ubuntu1+git201706241146+3485+26~ubuntu16.04.1/src/nvim/event/wstream.c:77: wstream_write: Assertion `!stream->closed' failed.
Aborted (core dumped)``
File is saved correctly but error occurs.

### Expected behaviour
Error should not be occurred.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
I didn't find a way of reproducing the error using the command. 
```

**Comment by justinmk** [comment]
What plugins are you using?

**Comment by SanD94** [comment]
plugin list is here :

call dein#add('Shougo/dein.vim')
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')
call dein#add('vim-airline/vim-airline')
call dein#add('Shougo/deoplete.nvim')
call dein#add('flazz/vim-colorschemes')
call dein#add('zchee/deoplete-jedi')
call dein#add('xolox/vim-misc')
call dein#add('xolox/vim-easytags')
call dein#add('artur-shaik/vim-javacomplete2')
call dein#add('pangloss/vim-javascript')
call dein#add('mxw/vim-jsx')

**Comment by sanga** [comment]
same issue here.

my plugins are:

```
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Chiel92/vim-autoformat'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'jremmen/vim-ripgrep'
Plug 'neomake/neomake' | Plug 'dojoteef/neomake-autolint'
Plug 'rbgrouleff/bclose.vim'
Plug 'sickill/vim-pasta'
Plug 'sjl/gundo.vim'
Plug 'scrooloose/nerdtree'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'Yggdroot/indentLine'
Plug 'airblade/vim-gitgutter'
" themes
Plug 'rakr/vim-one'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'flazz/vim-colorschemes'
Plug 'machakann/vim-highlightedyank'
Plug 'frankier/neovim-colors-solarized-truecolor-only'
Plug 'jacoborus/tender.vim'
Plug 'mhartington/oceanic-next'
" language-support
Plug 'JuliaEditorSupport/julia-vim'
Plug 'plasticboy/vim-markdown'  " untested/needs config
Plug 'elzr/vim-json'
Plug 'ekalinin/Dockerfile.vim'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'othree/yajs.vim'
Plug 'pangloss/vim-javascript'
Plug 'gavocanov/vim-js-indent'
Plug 'klen/python-mode'
Plug 'zchee/deoplete-jedi'
Plug 'rust-lang/rust.vim'
call plug#end()
```

**Comment by sanga** [comment]
cross-referencing across both of our lists of plugins I see deoplete is common. I just nuked that from my config, and I have had a crash in the last 5 mins. I don't think that crash repoed 100% of the time (so perhaps I'm just lucky) but I feel like it should have crashed at this point - so perhaps related to deoplete/deoplete-jedi

**Comment by sanga** [comment]
Added deoplete and deoplete-jedi back => crashed on second file edited.

**Comment by danielmanesku** [comment]
I can reproduce this as well. It is enough to open nvim, do a small change and exit with `:wq`. Content gets saved, but assertion error gets printed.

Minimal init.vim to reproduce this is:
```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'Shougo/deoplete.nvim'
call vundle#end()

let g:deoplete#enable_at_startup = 1
```

**Comment by felipesere** [comment]
Same here. Removing deplete helped.

**Comment by viniciusarcanjo** [comment]
Same here, for nvim 0.1.7 or 0.2. 


I've rolled back deoplete to an old commit and I don't see this problem anymore, if you use dein as a plugin manager you can:

```
call dein#add('Shougo/deoplete.nvim', { 'rev': '2eb3fa5' })
```

https://github.com/viniciusarcanjo/dotfiles/commit/060604442160de88662ce1082b6b9159f48cb691

I didn't bisect each commit though, I just picked a commit that I knew that was working in the begining of this month.

**Comment by Shougo** [comment]
I think https://github.com/Shougo/deoplete.nvim/commit/49362f71d6dea30549db2f145a53ca672046b9af causes the problem.
I have removed the code.

Note:  I just want to improve neovim exit time when deoplete using.
And I have not reproduce the problem in my environment.

**Comment by justinmk** [comment]
Maybe we need to disallow `rpc*()` functions in VimLeave. @Shougo your callbacks can check `v:exiting` (this is not in Vim) to avoid doing work during shutdown. Does that help?

**Comment by viniciusarcanjo** [comment]
@Shougo Thanks for this quick update. I've just upgraded and It's working.

**Comment by Shougo** [comment]
> @Shougo your callbacks can check v:exiting (this is not in Vim) to avoid doing work during shutdown. Does that help?

I don't understand it.
Can you upload the example?
I don't know why it improves the exit slowness.

**Comment by justinmk** [comment]
@Shougo see https://github.com/neovim/neovim/issues/4666 . You can check `v:exiting` and skip work if it is not equal to `v:null`.

**Comment by Shougo** [comment]
OK.  I will check it.

**Comment by SyrakuShaikh** [comment]
After upgrading `deoplete` today, this problem is solved.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/7081
