### ISSUE TITLE
:terminal colors are inconsistent when using termguicolors

### ISSUE THREAD

**Issue by hobarrera** [neovim/neovim#6929]
- `nvim --version`:
```
$ nvim --version
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Operating system/version: ArchLinux amd64
- Terminal name/version: tmux 2.5 inside termite 12
- `$TERM`: tmux-256color

### Actual behaviour

A terminal opened via `:terminal` has different colours from those of a normal terminal (evident via PS1, or any command that has any colour, like `ls`).

### Expected behaviour

Both should be the same.

### Steps to reproduce using `nvim -u NORC`

```
set termguicolor
:terminal
```

The effect is *slightly* different without `NORC` not sure why, but still somewhat broken.

![2017-06-25t23 28 45 253934090-03 00](https://user-images.githubusercontent.com/730811/27522655-4fdb24ba-5a17-11e7-86eb-df9c6b66a867.png)

Since the issues is about colours, a screenshot is really worthwhile:

* Upper left: `:te` inside `nvim` without `termguicolors`. Note that the terminal has 24-bit colour support, but the PS1 colours are slightly off.
* Upper right: `:te` inside `nvim` with `terminguicolors`. Note that most colours are not even printed or rounded to a close 256 one, **but** the terminal's PS1 seems to be using 24-bit colours.
* Bottom left: Normal terminal.
* Bottom right: `:te` inside `nvim -u NORC` without `termguicolors`. Running **with** termguicolors has the exact same result, so both are broken.

My 24-bit-color script is available [here](https://gitlab.com/hobarrera/dotfiles/blob/master/home/.local/bin/24-bit-colour).

**Comment by DarkDefender** [comment]
I am only able to reproduce this if run "set termguicolors" outside of init.vim (IE I do it manually). I do not use tmux though...

I assume you have termguicolors set in your init.vim?

**Comment by hobarrera** [comment]
Yes, I set `termguicolors` in init.vim. Except for the `nvim -u NORC` test, of course.

Just in case: is your terminal 24-bit-color compatible?

**Comment by justinmk** [comment]
To test with `-u NORC`, you need to use `--cmd`. 

    nvim -u NORC --cmd 'set termguicolors'

This is documented at `:h  termguicolors`

**Comment by hobarrera** [comment]
Oh, for the `NORC` test I'd just run `:set termguicolors` manually.

I tried running `nvim -u NORC --cmd 'set termguicolors'`. Terminal colours don't match those of a normal terminal either.

Here's another set of screenshots. Top: normal terminal, Bottom: `nvim -u NORC --cmd 'set termguicolors` (then `:terminal`). Note than while 24-bit colours match, terminal colours don't:

![2017-06-26t21 44 46 100301127-03 00](https://user-images.githubusercontent.com/730811/27566043-d508c880-5ad1-11e7-9951-75ffe341cf6e.png)

**Comment by DarkDefender** [comment]
That is because nvim does not have a way to figure out the host terminal colors when running in truecolor mode. You have to set them manually with `let g:terminal_color_X = #000000` where `X` is the colornumber 0-15.

**Comment by hobarrera** [comment]
Uhm, isn't there a way around this? I'd basically have to duplicate my terminal settings inside my vim settings, which is pretty much not-DRY, and kind of a pain to maintain.

**Comment by DarkDefender** [comment]
Not currently, no.

Because of how the built in terminal works, it is really hard if not impossible to seperate indexed colors and true colors (it only outputs rgb values).

**Comment by hobarrera** [comment]
Bummber. Thanks for the help though.

TBH, I'm trying to find something that can replace `:sh[ell]`, any better suggestions? I tried <kbd>ctrl</kbd>+<kbd>z</kbd>, but the difference is that quitting that terminal kills [neo]vim, rather than bring it back up.

**Comment by ZyX-I** [comment]
> Uhm, isn't there a way around this? I'd basically have to duplicate my terminal settings inside my vim settings, which is pretty much not-DRY, and kind of a pain to maintain.

@hobarrera Just write a plugin which will query your terminal settings and duplicate them in Neovim. Everything needed is scriptable, though “query” part may be less so, depending on how terminal configuration is stored.

It is also possible to use something like https://bitbucket.org/ZyX_I/formatvim/src/424e045946fb76e74f0e9c6a1490695b35076116/tools/getcolors.pl?at=default&fileviewer=file-view-default, the file is specifically designed to automatically get 256 colors out of random terminal emulator and store that in a YAML file without needing to know how settings are stored. If you use that you will have to run the script yourself each time you update your terminal emulator’s settings though.
