### ISSUE TITLE
native x64 win32yank builds for Windows

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#6933]
Currently, it seems that neovim [requires the x86 MSVC redistributables](https://github.com/neovim/neovim/wiki/Installing-Neovim) even for the x64 neovim builds for Windows:

> x86 version is required, even on 64-bit systems, for win32yank.exe

Just wondering what it would take to have win32yank.exe built as x64 in the 64-bit Windows build script for neovim.

**Comment by jsteinaker** [comment]
New guy here. About a year ago this commit changed the target platform in win32yank's repo. I'm not familiar with the build system, but seems to be a mather of checking which platform are targeting. Besides that, @equalsraf must have had a good reason for the change, so he probably could give you an explanation.
equalsraf/win32yank@2474c33e6b7719b3be39d730f3826f2175cdc743

**Comment by jsteinaker** [comment]
Well, I've made a fork of win32yank's repo. Some quick update to the Rust dependencies, and after making a thousand mistakes with AppVeyor configuration it's working. I've made 32 and 64 bit versions, you could try downloading the zip, replacing win32yank.exe in Neovim's folder and uninstalling x86 MSVC to see what happens. Also, a dumpbin must reveal that is a pure 64-bit exe.

Of course, if it's working I can make a pull request. After that it would be a mather of checking platform in CMake's config files to download the binaries corresponding to the Neovim version we're building.

**Comment by justinmk** [comment]
> After that it would be a mather of checking platform in CMake's config files to download the binaries corresponding to the Neovim version we're building.

:+1:
