### ISSUE TITLE
how to switch between command(shell) window and edit window?

### ISSUE THREAD

**Issue by meagon** [neovim/neovim#6934]
I cannot switch command(shell) window into edit window?

I have a question, how to switch command(shell) window and edit window?

**Comment by imomaliev** [comment]
@meagon If you mean embeded terminal `<C-\><C-N>`

```
:h terminal-emulator-input

To send input, enter terminal mode using any command that would enter "insert
mode" in a normal buffer, such as |i| or |:startinsert|. In this mode all keys
except <C-\><C-N> are sent to the underlying program. Use <C-\><C-N> to return
to normal mode. |CTRL-\_CTRL-N|

Terminal mode has its own |:tnoremap| namespace for mappings, this can be used
to automate any terminal interaction. To map <Esc> to exit terminal mode: >
    :tnoremap <Esc> <C-\><C-n>
```
If you mean command mode just use `<Esc>` or `<C-[>`

**Comment by dncnmcdougall** [comment]
I have the mappings
`tnoremap <Esc> <C-\><C-n>

tnoremap <C-w>h <C-\><C-n><C-w>h
tnoremap <C-w>j <C-\><C-n><C-w>j
tnoremap <C-w>k <C-\><C-n><C-w>k
tnoremap <C-w>l <C-\><C-n><C-w>l
`
The first makes escape return to normal mode as @imomaliev  mentioned. Note that <C-c> is still passed through to the terminal which is useful for interrupting commands.
The later four let me navigate through windows as I would other windows. As such in terminal in insert mode I can press <C-w>l and, as expected, I jump to the window on the right.  This makes it feal as though the terminal window is just like any other window.
