### ISSUE TITLE
NeoVim thought my terminal didn't support cursor shapes?

### ISSUE THREAD

**Issue by legolord208** [neovim/neovim#6935]
- `nvim --version`: NVIM 0.1.7
- Operating system/version: Linux Mint KDE 18.1 Serena
- Terminal name/version: Konsole: 16.04.3
- `$TERM`: `xterm`

**Note:** The behavior didn't change with either `xterm-256color`, `konsole`, `konsole-256color` or anything I've tried.

### Actual behaviour

I just switched from Linux Mint to Linux Mint KDE.  
In Linux Mint KDE, I had to set `NVIM_TUI_ENABLE_CURSOR_SHAPE`.

### Expected behaviour

Cursor shapes worked perfectly in Linux Mint (non-KDE), without this variable.
It makes me wonder why this is required here.

### Steps to reproduce

Setup a Linux Mint KDE vm? idk.

**Comment by fmoralesc** [comment]
From [Following HEAD](https://github.com/neovim/neovim/wiki/Following-HEAD#20170402):

> Support for $NVIM_TUI_ENABLE_CURSOR_SHAPE was removed. Use the guicursor option to control cursor styling. 

There's more information in the link.

**Comment by legolord208** [comment]
Nice, didn't scroll up. Will adapt to using that.

Still... Why didn't NeoVim detect it's supported? What's the technical difference between Linux Mint and Linux Mint KDE?

**Comment by fmoralesc** [comment]
The most recent stable version *is* 0.2.0, my guess is Mint and Mint KDE's repos are not in sync. This might affect both nvim and your terminal emulator (konsole?).

**Comment by legolord208** [comment]
Sorry, didn't realize.
They both use the same underlying repo... So I'd really think they are.

**Comment by fmoralesc** [comment]
Are you using the same terminal as before? Mint defaults to gnome-terminal, or something Vte based, while Mint KDE uses konsole. Konsole requires some code that I think landed only for 0.2 (https://github.com/neovim/neovim/blame/master/src/nvim/tui/tui.c#L659, https://github.com/neovim/neovim/pull/6044)

**Comment by legolord208** [comment]
Yeah, I switched console to Konsole in Mint as well. Might be a different version, but I kinda doubt it.

**Comment by justinmk** [comment]
Issue tracker is not for questions about old releases.

**Comment by legolord208** [comment]
Oh, so it's fixed in a newer release? Cool!
