### ISSUE TITLE
nvim_get_keymap output is unreliable

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6937]
- `nvim --version`: ea75966e4232dc4a3693cbc4a572f2116c49b138
- Vim (version: 8.0.658) behaves differently? No if you consider maparg() buggy. N/A if you don’t.

Consider the following shell commands:

```
% bin/nvim --cmd 'set cpo+=< | nnoremap <C-X> <C-c>' --cmd 'set cpo&vim | echo nvim_get_keymap("n")' --cmd cq
[{'expr': 0, 'noremap': 1, 'lhs': '<C-X>', 'mode': 'n', 'nowait': 0, 'silent': 0, 'sid': -2, 'rhs': '<C-c>', 'buffer': 0}]
% bin/nvim --cmd 'set cpo-=< | nnoremap <C-X> <C-c>' --cmd 'set cpo&vim | echo vim_get_keymap("n")' --cmd cq
[{'expr': 0, 'noremap': 1, 'lhs': '<C-X>', 'mode': 'n', 'nowait': 0, 'silent': 0, 'sid': -2, 'rhs': '<C-c>', 'buffer': 0}]
```

. It is clear that with `<` in `&cpo` `<C-X>` is `<LT>C-X>` actually, but the output in both cases is exactly the same. Also if I use `<C-x>` in the example it transforms to `<C-X>` when interpreted as Ctrl+X, but `<C-c>` does not.

I would expect `nvim_get_keymap` output to not rely on options, and especially not rely on options that were set at the time mapping was defined given that there is even no way to know what they were. Also lhs and rhs should be uniform, so if Ctrl+X is `<C-X>` in lhs Ctrl+C should be `<C-C>` in rhs (though better go with `<C-x>` and `<C-c>` instead: modifiers capitals, non-modifiers small).

---

Note that `maparg()` has the same problem:

```
% vim --cmd 'set cpo-=< | nnoremap <C-X> <C-c>' --cmd 'set cpo&vim | echo maparg("\<C-X>", "n", 0, 1)' --cmd cq
{'silent': 0, 'noremap': 1, 'lhs': '<C-X>', 'mode': 'n', 'nowait': 0, 'expr': 0, 'sid': -2, 'rhs': '<C-c>', 'buffer': 0}
 % vim --cmd 'set cpo+=< | nnoremap <C-X> <C-c>' --cmd 'set cpo&vim | echo maparg("<LT>C-X>", "n", 0, 1)' --cmd cq
{'silent': 0, 'noremap': 1, 'lhs': '<C-X>', 'mode': 'n', 'nowait': 0, 'expr': 0, 'sid': -2, 'rhs': '<C-c>', 'buffer': 0}
```

(Note: vim now.) But this one is more restricted with backwards compatibility, especially for `rhs` (help explicitly states “as typed”, no such thing for `lhs` though).

**Comment by justinmk** [comment]
> I would expect nvim_get_keymap output to not rely on options

Strongly agree, this should be a general proclivity of the API.

In the meantime we can remove the `<` flag from 'cpoptions'.

**Comment by ZyX-I** [comment]
There is additional comment which prevents your PR from being a fix: check with `nnoremap <LT>C-X> <LT>C-C>` mapping: both `nvim_get_keymap` and `maparg` are incorrect here (report `<C-X>` as `lhs`) (though note that Vim has fixed `maparg` since then).
