### ISSUE TITLE
stty/termios altered, and not restored, after jobstart(...on_stdout)

### ISSUE THREAD

**Issue by Julian** [neovim/neovim#6938]
- `nvim --version`:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```
- Operating system/version:
Multiple -- OSX latest + Arch Linux
- Terminal name/version:
Multiple -- iTerm2 latest + gnome-terminal latest + Terminator latest
- `$TERM`:
Multiple -- xterm-256color outside tmux, screen-256color inside tmux

### Actual behaviour

Running the jobstart breaks ^C and others unless the terminal is reset

### Expected behaviour

Not that

### Steps to reproduce using `nvim -u NORC`

**Run:**

```
reset; stty; nvim -u <(echo '                                                                                                                                     
    function! s:Pass(job_id, data, event)
    endfunction
    call jobstart(["true"], {"on_stdout": function("s:Pass")})
') +startinsert
```

My `stty` initially shows:

```
speed 38400 baud; line = 0;                 
iutf8                                       
-iexten                                     
```

(slightly different on the other machines).

**Then**
* Leave insert mode
* Hit ^Z and send nvim to the background
* *Type* `fg` to bring it to the foreground (oddly, for me, hitting ^Z again does not actually trigger the issue, but it looks like I have some terminal reset things happening in that keybinding, so it's possible it would have happened there too)
* Send nvim back to the background with another ^Z
* Observe that `stty` now contains things like (for me):
```
speed 38400 baud; line = 0;                 
-brkint -icrnl iutf8                        
-isig -iexten                               
```

and that ^C now inserts the literal rather than sending SIGINT, until a terminal reset is performed.

The above seems to be a minimal reproducer for me, in that if I don't run the jobstart, everything's fine, and if I don't pass on_stdout, things are also OK.

**Comment by justinmk** [comment]
Thanks for the clear steps. I don't see `-icrnl` on my end, but I can confirm that the `stty` result is different, after following your steps, after even a single ^Z. Also confirmed that `jobstart` is required.

**Comment by justinmk** [comment]
@Julian Can you post the `strace` output with plugins and shada disabled? Like this:

```
reset; stty; nvim -i NONE -u <(echo '                                                                                                                                     
    function! s:Pass(job_id, data, event)
    endfunction
    call jobstart(["true"], {"on_stdout": function("s:Pass")})
') +'set loadplugins' +'filetype off' +'syntax off' +startinsert
```

**Comment by justinmk** [comment]
I can't reproduce this with Terminal.app nor iTerm, nvim version `v0.2.1-371-g2b377d8`.

**Comment by Julian** [comment]
Hey @justinmk thanks for having a look so quick! Will get you an strace as soon as I get back to my Linux box -- for now, just to make sure, attached is a `script(1)` demo recorded in iTerm2.app showing the same behavior -- might be some other variables involved, is there a chance this was fixed in between 0.2.0 and the 0.2.1 you have? I can probably give that a shot.

[nvim.txt](https://github.com/neovim/neovim/files/1115889/nvim.txt)

**Comment by Julian** [comment]
Attaching the strace too:

[strace.txt](https://github.com/neovim/neovim/files/1116225/strace.txt)

**Comment by Julian** [comment]
@justinmk also confirming that I still see the issue even after upgrading to NVIM v0.2.1-398-g82907ab5f

**Comment by justinmk** [comment]
@Julian could you try https://github.com/neovim/neovim/pull/6990 ? Since I can't reproduce the issue, it will help if you can try that. I think it's not a solution, but want to eliminate that possibility.

> Observe that stty now contains things like:

```
speed 38400 baud; line = 0;                 
-brkint -icrnl iutf8                        
-isig -iexten    
```

That looks like what libtermkey does in `termkey_start()`.

But the fact that `jobstart()` is required is weird. We don't alter termios (except for PTY children).

I think it might be a race: in main.c, `source_startup_scripts()` is called earlier than `ui_builtin_start()`.

Can you reproduce the issue if you delay the call to `jobstart()` ? E.g., do it manually from the command line, instead of in a startup script.

**Comment by Julian** [comment]
@justinmk thanks for tryin' to tackle this so quickly --

Interestingly, not only does that PR not fix it, it even further mangles the terminal output, such that now stty says:

```
speed 38400 baud; line = 0;
                           -brkint -icrnl iutf8
                                               -opost
                                                     -isig -iexten
                                                                  %                                                                                                             
```

It does look like though that you're right and this doesn't happen if I call the jobstart after vim is up -- but I started tracking this down basically because my vimrc calls jobstart, so my "real" code is actually triggering the issue :/

**Comment by justinmk** [comment]
https://github.com/neomake/neomake/issues/1704#issuecomment-343757207 suggests that there is definitely a weakness somewhere in the job-control subsystem, that allows jobs to modify the terminal settings of the parent nvim.

**Comment by justinmk** [comment]
@Julian Could you try HEAD (3bf57c117120327930fb39935d1672558f58d148 or later)? After https://github.com/neovim/neovim/pull/8107 jobs always start in their own session. I guess that could make a difference about how the tty or termios behaves.

**Comment by justinmk** [comment]
Let's take this off the board. If it's still not fixed just leave a comment. Thanks!

**Comment by Julian** [comment]
This is unfortunately still happening here on 0.3.0.

**Comment by justinmk** [comment]
> this doesn't happen if I call the jobstart after vim is up -- but I started tracking this down basically because my vimrc calls jobstart

Is it still the case that the problem happens only if you call jobstart in your vimrc/init.vim?

**Comment by Julian** [comment]
Same repro seems to work for me on 0.3.0, and here's what stty ends up being:

```
  ⊙  stty                                                                                                                                                                                    Julian@Magbook speed 38400 baud;
                 ignbrk -brkint -icrnl -imaxbel iutf8
                                                     -opost tab3
                                                                -isig -iexten -echoe -echok
```

**Comment by Julian** [comment]
@justinmk yeah seems like it as well

**Comment by zeertzjq** [comment]
Does this bug still exist?
