### ISSUE TITLE
nvim over mosh and ultisnips

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#6943]
- `nvim --version`: .2.1. dev
- Vim (version: 8.0.628) behaves differently? Yes
- Operating system/version: Arch 2017, July
- Terminal name/version: xterm
- `$TERM`: xterm-256color

### Expected behaviour: Mosh buffers all key strokes and paints instantly locally, then syncing with remote if there is connection latency. There should be no visible latency, (though there will be rollbacks if latency is huge). Vim does behave correctly. 
Additional note: I first noticed this around beginning of Fall 2016, but at that time was no longer using nvim over mosh so did not report, thinking it a transient issue. Before that I was running nvim over mosh constantly and did not have this issue.
### Steps to reproduce using `nvim -u NORC`
Add plugin ultisnips, run nvim over mosh, press a key and hold, the painting of the key will periodically stutter in NVIM, not so in VIM. Removing the plugin strangely fixes the issue.
```
nvim -u NORC

```

**Comment by justinmk** [comment]
What does ultisnips have to do with it? What specific operations exhibit the symptom? Please provide specific steps to demonstrate the issue, e.g. 

```
nvim -u NORC
# install ultisnips, fine...
???? 
```

**Comment by yashamon** [comment]
I added more detail for reproduction.

**Comment by justinmk** [comment]
So it affects _any_ action, not just ultisnips-specific ones? What happens if you remove CursorMoved autocmds:

    :au! UltiSnips CursorMoved

**Comment by yashamon** [comment]
Yeah any action. au! UltiSnips CursorMoved gives error no such group or event.

**Comment by justinmk** [comment]
Can you post the result of:

```vim
:put =execute('au')
```

**Comment by yashamon** [comment]
Here is the output of :put =execute('au') 
greped for UltiSnips (otherwise it is 10000 line file)

UltiSnips_AutoTrigger  InsertCharPre
    *         call UltiSnips#TrackChange()
UltiSnips_AutoTrigger  TextChangedI
    *         call UltiSnips#TrackChange()
UltiSnips_AutoTrigger  InsertCharPre
    *         call UltiSnips#TrackChange()
UltiSnips_AutoTrigger  TextChangedI
    *         call UltiSnips#TrackChange()
UltiSnips_AutoTrigger  InsertCharPre
    *         call UltiSnips#TrackChange()
UltiSnips_AutoTrigger  TextChangedI
    *         call UltiSnips#TrackChange()

**Comment by justinmk** [comment]
Try

    :au! UltiSnips_AutoTrigger

> greped for UltiSnips

Did you do a case-insensitive search?

**Comment by yashamon** [comment]
yep case insensitive.
I just wanted to update that this is not limited to mosh, the same thing happens over SSH, in vim there is virtually no stagger in painting a pressed key (I guess my latency is fairly low), but it begins to stagger in nvim.

**Comment by justinmk** [comment]
So can you try `:au! UltiSnips_AutoTrigger` ? I guess by "painting a key" you mean in insert-mode, which was no mentioned anywhere in this report.

**Comment by yashamon** [comment]
Yes insert-mode. :au! UltiSnips_AutoTrigger fixes the issue.

**Comment by yashamon** [comment]
This seems to have been an issue with my mosh client, as changing it fixed
the problem.
