### ISSUE TITLE
Drawing corruption after returning to nvim from iddle.

### ISSUE THREAD

**Issue by phcerdan** [neovim/neovim#6944]
- `nvim --version`: 0.2.0
- Vim (version: 8.0, but any ) behaves differently? Yes
- Operating system/version: Archlinux
- Terminal name/version: GNOME Terminal 3.24.2 Using VTE version 0.48.3 +GNUTLS
- `$TERM`: tmux-256color

### Actual behaviour
When I come back to neovim after a while (for example next day), if I go to insert mode and write,  it insert new lines, and become unreadable,  or if  I move the cursor between buffers ( only tested in a tmux session), the layout gets corrupted, inserting lines above the command line. See images:  
![nvim_bug1](https://user-images.githubusercontent.com/3021667/27765876-8dba53fa-5f12-11e7-825c-ced320d2d515.png)
Moving the cursor to other buffer: 
![nvim_bug2](https://user-images.githubusercontent.com/3021667/27765877-8dd4c3e8-5f12-11e7-8710-a6dc39e75906.png)
Writing in insert mode produces garbage:
![nvim_bug3](https://user-images.githubusercontent.com/3021667/27765933-f0c3a5b8-5f13-11e7-9769-c608bbb9e7b7.png)

The more I move, the more lines I appear. It is solved just restarting the session. (:qa, nvim -S Session.vim)

This has been happening to me in 1.7 as well.

### Expected behaviour
No problems drawing.

### Steps to reproduce using `nvim -u NORC`
I am not sure how to reproduce it. Or how to provide better information. But in vim, with the same plugins doesn't happen.
```
nvim -u NORC

```

**Comment by justinmk** [comment]
As a workaround, try CTRL-L or the `:mode` command.

> This has been happening to me in 1.7 as well.

Then it's covered by other redraw issues. Thanks for reporting though.

**Comment by phcerdan** [comment]
`:mode` does it, thanks @justinmk
