### ISSUE TITLE
macOS: hangs/freezes/crash with jemalloc 5.0.0

### ISSUE THREAD

**Issue by renstrom** [neovim/neovim#6950]
- `nvim --version`:

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170625-90171-qde9qd/neovim-0.2.0/build/config -I/tmp/neovim-20170625-90171-qde9qd/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170625-90171-qde9qd/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170625-90171-qde9qd/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0/share/nvim"
```

- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.12.5
- Terminal name/version: iTerm2 (3.0.5)
- `$TERM`: xterm-256color

### Actual behaviour

As mentioned in https://github.com/neovim/neovim/issues/5681#issuecomment-312048808. Running `:PlugUpdate` is a mostly guaranteed way to hang Neovim. You need at least a dozen plugins though, the more you have, the higher the chance of it hanging.

It also sometimes happen for me when saving a buffer, I assume it's because [w0rp/ale](https://github.com/w0rp/ale) starts linters in the background. Or if it's related to plugins using the Python API.

### Expected behaviour

Not hanging 😄 

### Steps to reproduce using `nvim -u vimrc`

N/A

### Steps to reproduce

Using this `vimrc` and running `:PlugUpdate` will basically always result in Neovim hanging and you have to manually kill it with `kill -9`.

```
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'Quramy/tsuquyomi' | Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'Raimondi/delimitMate'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'airblade/vim-gitgutter'
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'fs111/pydoc.vim'
Plug 'junegunn/vim-peekaboo'
Plug 'junegunn/rainbow_parentheses.vim'
Plug 'junegunn/vim-easy-align', {'on': ['<Plug>(EasyAlign)', 'EasyAlign']}
Plug 'justinmk/vim-sneak'
Plug 'kshenoy/vim-signature'
Plug 'ludovicchabant/vim-gutentags'
Plug 'majutsushi/tagbar'
Plug 'mhinz/vim-grepper'
Plug 'dominikduda/vim_current_word', {'on': 'VimCurrentWordToggle'}
Plug 'rust-lang/rust.vim', {'for': 'rust'}
Plug 'sbdchd/neoformat'
Plug 'sheerun/vim-polyglot'
Plug 'srstevenson/vim-picker'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-python/python-syntax'
Plug 'w0rp/ale'
Plug 'wellle/targets.vim'
Plug 'ajmwagar/vim-dues'
Plug 'chriskempson/base16-vim'
Plug 'joshdick/onedark.vim'
Plug 'lifepillar/vim-solarized8'
Plug 'mbbill/vim-seattle'
Plug 'nanotech/jellybeans.vim'
Plug 'rakr/vim-one'
call plug#end()
```

**Comment by Shougo** [comment]
The vimrc seems long.
Can you reduce the lines?

**Comment by renstrom** [comment]
Not really. Or yes, you can reduce the number of plugins. But as I mentioned, the more plugins you have, the higher the chance is for Neovim to hang. And with this many it's basically 100% chance. Using only a handful can also hangs Neovim, but it's not guaranteed.

**Comment by renstrom** [comment]
And going by the last few comments in https://github.com/neovim/neovim/issues/5681#issuecomment-312048808, it seems like it's only macOS that's affected.

**Comment by equal-l2** [comment]
Could you try with neovim without jemalloc?
To disable jemalloc, first you need edit line 62 of formula like this:
```diff
-      system "cmake", "..", *std_cmake_args
+      system "cmake", "..", "-DENABLE_JEMALLOC=OFF", *std_cmake_args
```
Then, install neovim with `--build-from-source` option.

**Comment by renstrom** [comment]
@equal-l2 yes, that seems to solve the issue. At least from some my initial tests (ran `:PlugUpdate` a couple of times using my regular `.vimrc`).

**Comment by renstrom** [comment]
I guess this is mostly a duplicate of https://github.com/neovim/homebrew-neovim/issues/219.

**Comment by petobens** [comment]
The problems indeed seems to have started with/after https://github.com/Homebrew/homebrew-core/pull/14485. In my case it happens (randomly) with/without jemalloc. 
As mentioned by @renstrom , this only seems to occur  on mac .

**Comment by renstrom** [comment]
@petobens did you verify that it actually got built without jemalloc
(i.e. `nvim --version` returns `-jemalloc` instead of `+jemalloc`)?

**Comment by petobens** [comment]
@renstrom you were right. I was still getting `+jemalloc`. Will test without jemalloc and see if the freezing reappears. Thanks

**Comment by Fenkiou** [comment]
Thought I disabled jemalloc, but not compiling from source did it. Thanks @equal-l2.

Let you know if any freeze occurs again.

**Comment by gavsim** [comment]
Just to add that I have been experiencing the same hanging for a good few days now when running plug update.

**Comment by justinmk** [comment]
see https://github.com/neovim/homebrew-neovim/issues/219

@javian can we pin to jemalloc 4.5 ?

**Comment by javian** [comment]
Ok I won't touch it then . Glad there's an upstream fix =)

**Comment by timfeirg** [comment]
I'm still seeing this with on jemalloc 5.0.1, NVIM v0.2.1-414-g008b604ba 
And then I rollback jemalloc to 4.5, this is still happening.

**Comment by renstrom** [comment]
I can confirm that rebuilding Neovim with jemalloc 5.0.1 didn't solve the issue for me either. Unless it was sneakingly using some other version. Here's my steps:

```bash
$ brew uninstall neovim
$ brew cleanup
$ brew update
$ brew install --verbose --build-from-source neovim
```

Not sure how I can double check what version it was built with?

**Comment by javian** [comment]
@renstrom `brew linkage neovim` should display all libraries, find jemalloc there to verify that its using the correct one from homebrew. It probably points to the opt directory so you need to check which version of jemalloc is linked which I think `brew info jemalloc` will.

**Comment by renstrom** [comment]
Thanks. Just double checked and it's indeed using jemalloc 5.0.1 (and the issue is still present).

```
$ brew info jemalloc
jemalloc: stable 5.0.1 (bottled), HEAD
malloc implementation emphasizing fragmentation avoidance
http://www.canonware.com/jemalloc/
/usr/local/Cellar/jemalloc/5.0.1 (16 files, 1.6MB) *
  Poured from bottle on 2017-07-03 at 09:11:32
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/jemalloc.rb

$ brew linkage neovim
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libutil.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/jemalloc/lib/libjemalloc.2.dylib (jemalloc)
  /usr/local/opt/libtermkey/lib/libtermkey.1.dylib (libtermkey)
  /usr/local/opt/libuv/lib/libuv.1.dylib (libuv)
  /usr/local/opt/libvterm/lib/libvterm.0.dylib (libvterm)
  /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib (msgpack)
  /usr/local/opt/unibilium/lib/libunibilium.0.dylib (unibilium)

$ ls -l /usr/local/opt/jemalloc
lrwxr-xr-x  1 peter  admin  24 Jul  3 09:11 /usr/local/opt/jemalloc@ -> ../Cellar/jemalloc/5.0.1
```

**Comment by justinmk** [comment]
@timfeirg (and others) can you use the same steps to verify the caes of jemalloc 4.5  ?

**Comment by timfeirg** [comment]
here's what I've done:

```
$ brew switch jemalloc 4.5.0
Cleaning /usr/local/Cellar/jemalloc/4.5.0
Cleaning /usr/local/Cellar/jemalloc/5.0.1
11 links created for /usr/local/Cellar/jemalloc/4.5.0
$ brew reinstall --HEAD --build-from-source neovim
$ brew linkage neovim
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libutil.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/jemalloc/lib/libjemalloc.2.dylib (jemalloc)
  /usr/local/opt/libtermkey/lib/libtermkey.1.dylib (libtermkey)
  /usr/local/opt/libuv/lib/libuv.1.dylib (libuv)
  /usr/local/opt/libvterm/lib/libvterm.0.dylib (libvterm)
  /usr/local/opt/luajit/lib/libluajit-5.1.2.dylib (luajit)
  /usr/local/opt/msgpack/lib/libmsgpackc.2.dylib (msgpack)
  /usr/local/opt/unibilium/lib/libunibilium.0.dylib (unibilium)
```

And neovim still hangs sometimes. @justinmk

**Comment by javian** [comment]
@timfeirg do you get the same result if you build it from source outside of homebrew ? The build process is different so it might be good to determine that as well.

**Comment by yakschuss** [comment]
just wanted to add that it's not just Plug that's causing the hang, I'm using minpac (https://github.com/k-takata/minpac) and am having the same issue

**Comment by equal-l2** [comment]
FYI static linking may mitigate this issue.
cf. https://github.com/neovim/homebrew-neovim/pull/204

(Bundled jemalloc will be statically linked, so using bundled one can also have the same effect)

**Comment by leonfeng** [comment]
Just want to mention that VimR is not affected by this issue. I installed VimR after experiencing hangs in the terminal, and it hasn't frozen up once. Plug works perfectly too.

**Comment by equal-l2** [comment]
>VimR is not affected by this issue. 

I think this is because neovim used by VimR is built with bundled dependency, which means jemalloc is statically linked.

**Comment by equal-l2** [comment]
I noticed `PlugUpdate 1` (Update packages with 1 thread) doesn't cause hang.
Probably more threads makes more likely to hang.

**Comment by ahmedelgabri** [comment]
I have the same issue & it's not only with `PlugUpdate`, it's very random in my case. Sometimes it's freezes when I'm yanking, pasting, editing, etc... even sometimes it works fine with `PlugUpdate`

**Comment by mhinz** [comment]
For all homebrew users: a `brew upgrade` should get a new bottle of neovim now.

Please see if the new version fixes all your problems.

**Comment by shawnyeager** [comment]
@mhinz Worked for me. Thanks.
