### ISSUE TITLE
echo "\x80" outputs `~@<80>` which looks like two characters

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#6954]
- `nvim --version`: https://github.com/neovim/neovim/commit/35898cff5d1d6dc60e0d7b87bfe106539453b031
- Vim (version: 8.0.692) behaves differently? Yes

### Steps to reproduce

```
nvim -u NONE -i NONE -N --headless --cmd 'echo "\x80"' --cmd cq
```

### Expected behaviour

It should output `<80>` like Vim does. Or only `~@` at least.

### Actual behaviour

Outputs `~@<80>`.

**Comment by ZyX-I** [comment]
The problem is also seen on e333957a1a9ae64b7daa36e08fd1df583114d4ba, so it is certainly *not* my fault.

**Comment by justinmk** [comment]
This has been there for years.

**Comment by ZyX-I** [comment]
This issue is one of the bugs introduced by that my big refactoring commit: efa2682e3b513c4a33d987dc651db5913feff21a.

**Comment by justinmk** [comment]
I've seen it elsewhere, e.g. on FocusLost (though I did not find minimal steps).

    :echo "\<FocusLost>"

returns `~@<80>~@^Ca`. I guess that should return `<FocusLost>`.

**Comment by ZyX-I** [comment]
@justinmk Not actually. It should print just what it prints minus `~@`.
