### ISSUE TITLE
echo getchar() == "\<Esc>" return 0 when I press <Esc>

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6956]
I found an issue with neovim and gvim, but I am not sure if this is  correct. I test it in neovim-master and gvim8.0.

in both neovim and gvim, `:echo getchar() == "\<Esc>"` return 0 when I press `<Esc>`,  but `:echo getchar() == "\<Left>"` return 1 when I press `<left>`.

BTW I have test `<Up>`, `<Right>`, `<Home>`, `<End>`, both works well.

**Comment by ZyX-I** [comment]
While this is strange, it is documented: `getchar()` returns either a number (which needs to be passed to `nr2char()` then) or a string, do read documentation this is right in the second paragraph.

And do not use `==` for string comparison, use `is#`: it is case-sensitive always (`==` depends on `&ignorecase` option) and does not compare true with zero (`"\<Esc>" == 0` yields 1).

**Comment by wsdjeg** [comment]
@ZyX-I I have test `:echo getchar() is# "\<Esc>"` then press `<Esc>`, still return 0.

**Comment by ZyX-I** [comment]
@wsdjeg I did not say this is what you should do specifically for `<Esc>`. It is a *single byte*, it will return a *number*. What normally is done is *first* convert `getchar()` output to a string *if* its output is number and only then do anything with it at all: e.g. just always use wrapper

 ```VimL
function Getchar(...)
    let ret = call('getchar', a:000)
    return (type(ret) == type(0) ? nr2char(ret) : ret)
endfunction
```

**Comment by wsdjeg** [comment]
Nice,  thanks, I got it.
