### ISSUE TITLE
Cannot paste non-ascii data to vim command line

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#6964]
- `nvim --version`: `0.2.0-dev`
- Operating system/version: Ubuntu
- Terminal name/version: fish
- `$TERM`: xterm-256color

### Actual behaviour
I'm unable to put yanked text to the vim command line if that text is unicode/non-ascii. ASCII text works fine.

### Expected behaviour
Yanked text should always be put the same, regardless of its content.

### Steps to reproduce using `nvim -u NORC`
First, create a document containing a UTF-8 character:
`echo '&ndash;' | recode html..utf8 > test.txt` (result attached)

`nvim -u NORC test.txt`

* `v→y`
* `<CTRL-R>"`

Expected contents of the vim command line buffer: `:–`
Actual contents of the vim command line buffer: `:<t_^^~@<80>>`

**Comment by ZyX-I** [comment]
Unable to reproduce, I am assuming you meant something like this in steps to reproduce:

    echo $'\xE2\x80\x93' > test.txt
    nvim -u NORC test.txt -s <(echo -n $'vy:\C-r"')

Can you post the output of `locale` (shell command), `:echo &encoding` and actual `nvim --version` output? And first repeat all tests with Neovim nightly, it should report 0.2.1. Specifically I checked with v0.2.1-442-g69f0847cc.

And for the record, `fish` is not a terminal, it is a shell. By “terminal” “terminal emulator” is meant, that is something like gnome-terminal, konsole, etc.

**Comment by mqudsi** [comment]
Trying again with the code from git solved the problem. It seems the latest release is broken in this regard and it has been fixed since then.
