### ISSUE TITLE
tabmove semantics are weird

### ISSUE THREAD

**Issue by Laaas** [neovim/neovim#6965]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently? Irrelevant

### Expected behaviour
Doing `tabm <tab index>` should move the current tab to that index.

### Actual behaviour
Moving to a higher tab index works as expected, but when trying to move to a lower tab index, it moves to that index + 1.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
tabnew
tabnew
tabmove 1
tabmove 3
```
I don't know if this also happens in standard vim, but even if it does, I really think this should be changed in neovim. It's very annoying and makes no sense to me.

**Comment by chrisbra** [comment]
that works as documented. It moves the current tabpage after the given index.

**Comment by jamessan** [comment]
We're not going to deviate from Vim on something like this.  As mentioned, this is the documented behavior:

```
:tabm[ove] [N]						*:tabm* *:tabmove*
:[N]tabm[ove]
		Move the current tab page to after tab page N.  Use zero to
		make the current tab page the first one.  Without N the tab
		page is made the last one.
```
