### ISSUE TITLE
Shada slow down?

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#6966]
- `nvim --version`: .2.1
- Vim (version: ) behaves differently? NA
- Operating system/version: Arch July 2017,
- Terminal name/version: urxvt
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC` Not sure.

```
nvim -u NORC

```

**Comment by justinmk** [comment]
How big ... ?

**Comment by yashamon** [comment]
Last time this happened, I was working on mostly just three projects and the shada was around 14k lines.

**Comment by ZyX-I** [comment]
@yashamon I do not quite understand where it is slow (what “auto save”? ShaDa files are written on exit only. And what does “working with a file which has large ShaDa history” mean? ShaDa is not attached to any files), or what the size is. ShaDa file is a binary file, it can’t have 14k lines by itself; to make it editable by the user Neovim ships with a plugin which transforms file into readable representation.

**Comment by yashamon** [comment]
I meant the autosave plugin that  auto saves on mode change insert to normal for instance. 
>>And what does “working with a file which has large ShaDa history” mean? Well I had three projects that I was working extensively on, the slow down in save operation happened with those projects. Opening a different file the behavior seemed normal. I don't know if Shada is really at fault  (which is why I put "?") but wiping out shada does fix the behavior, for some reason. Also running with nvim -u NORC.
However as Shada is only written on exit, maybe there is something else going on that I am missing.

**Comment by ZyX-I** [comment]
@yashamon This is answer to only one of two questions, and not descriptive as well: “autosave” is rather common name to point to specific plugin. This may be http://www.vim.org/scripts/script.php?script_id=4521 since it is in top search results, but I am not sure and name does not match. Also I do not see plugin writing ShaDa files and ShaDa files are not supposed to be either read or written when writing files, though they are normally read when reading files.

**Comment by ZyX-I** [comment]
@yashamon I would suggest to do a profiling:

    profile start /tmp/profile.log
    profile func *
    profile file *
    …
    qall

(profile data is saved to /tmp/profile.log on exit only).

**Comment by mhinz** [comment]
> (profile data is saved to /tmp/profile.log on exit only)

(or on `:profile dump`)

**Comment by yashamon** [comment]
ZyX-I, the problem appears on any save including manual :w. Which is why I didn't specify the plugin since it is clearly not the culprit. Sorry for being unclear in the description. (I changed it.) The specific name of the plugin: https://github.com/vim-scripts/vim-auto-save. I don't understand what you mean by didn't answer second question. I will try profiling when I get a chance, I already wiped my Shada but it was backed up.

**Comment by ZyX-I** [comment]
@yashamon Second was “And what does “working with a file which has large ShaDa history” mean? ShaDa is not attached to any files”, when I was writing the comment you did not do edits to yours and I only remember large quote of my comment.

**Comment by justinmk** [comment]
>  but wiping out shada does fix the behavior, for some reason. Also running with nvim -u NORC.

`nvim -u NORC` still uses the shada info. So if this fixes the issue, there's some other autocmd or plugin that is causing the issue. Not shada.
