### ISSUE TITLE
possible key input processing/displaying error

### ISSUE THREAD

**Issue by MartinBrugnara** [neovim/neovim#697]
If key is pressed while nvim is saving, 
the key's char is displayed at the end of the status line,
but the "command" is buffered.
After few milliseconds the line disappears and the action linked to the key is executed.
Note: no changes are made to the saving file name.

It happen even while pressing more keys.

Ex:
> :w
> "handler.go" [converted] 42L, 736C written
press keys. eg "dd"
> "handler.go" [converted] 42L, 736C writtendd
after few ms the line where the cursor is get deleted.

**Comment by justinmk** [comment]
Unlikely that this will be addressed, if it is still a problem at all.
