### ISSUE TITLE
How can I prevent split-window when scrolling to not clear lines from adjacent split

### ISSUE THREAD

**Issue by nexusstar** [neovim/neovim#6971]
- `nvim --version`: NVIM v0.2.1-dev
Build type: RelWithDebInfo
- Vim (version: 7.4) behaves differently? YES
- Operating system/version: Ubuntu 16.04.2 LTS
- Terminal name/version: zsh 
- `$TERM`:

### Actual behaviour
when scrolling split-window it clears lines in adjacent split
![peek 2017-07-06 14-42](https://user-images.githubusercontent.com/1746003/27909498-958a5860-6259-11e7-87b6-6a06685b40ba.gif)

### Expected behaviour
not to clear visible lines in split
![peek 2017-07-06 14-43](https://user-images.githubusercontent.com/1746003/27909506-a4a40378-6259-11e7-9367-e95e6293a998.gif)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
: e <<filename>>
:vsp
jj <<to bellow visible lines>>
kk << to top>>
```

**Comment by jamessan** [comment]
This is likely the same as https://github.com/neovim/neovim/issues/6802 which should be improved by https://github.com/neovim/neovim/pull/6970, if you're able to test that out.
