### ISSUE TITLE
can not change cursor to vertical bar.

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#6978]
- `nvim --version`: mater
- Vim (version: ) behaves differently? no
- Operating system/version: arch
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Actual behaviour
by default when goto insert mode the cursor change to a `_`, but I think it should be `|`.
### Expected behaviour
`set guicursor=a:ver25-blinkon10` can change cursor to `|`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
set guicursor=a:ver25-blinkon1
```

you will see the cursor shape is `_`.

**Comment by teto** [comment]
I can reproduce this even with TERM=vte . Will try to look into it.

**Comment by wilywampa** [comment]
I am seeing this issue as well after updating nvim on homebrew.

```
NVIM v0.2.1-516-g226603a8d
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-un
used-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80356-jco96o/build/conf
ig -I/tmp/neovim-20170707-80356-jco96o/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I
/usr/include -I/tmp/neovim-20170707-80356-jco96o/build/src/nvim/auto -I/tmp/neovim-20170707-80356-jco96o/build/include
Compiled by jniehus@MacBook-Pro-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-226603a/share/nvim"
```

**Comment by justinmk** [comment]
So this is a regression? Did it work before #6816 ?

**Comment by DarkDefender** [comment]
Just FYI, I can not reproduce this in urxvt, xfce4-terminal or alacritty with current master. So I don't know what is going wrong here...

**Comment by justinmk** [comment]
@wsdjeg Did `set guicursor=a:ver25-blinkon1` work in an older version of Nvim? What libvte (**not** libvterm) version is termite using? And what version of termite (as requested by the issue template)?

**Comment by wsdjeg** [comment]
in old neovim, before 6816,  `set guicursor=a:ver25-blinkon10` will change my cursor to a blink `|`. so I think it works well in old nvim.

my termite version is `termite v12`, I do not know how to check version of `libvte`.

**Comment by DarkDefender** [comment]
Termite uses a fork of libvte to add some features:
https://github.com/thestinger/termite/tree/v12#dependencies

If you are using a recent version of that fork, then it seems like the version should be 0.48.2

**Comment by DarkDefender** [comment]
I upgraded to vte 0.48.3 and tried again with xfce4-terminal. I still do not see a horizontal bar instead of a vertical bar. So I don't think this is a problem with vte itself.

@wsdjeg Does it change anything if you change `TERM` to `xterm-256color` ? This is what xfce4-terminal is set to by default.

**Comment by wilywampa** [comment]
> So this is a regression? Did it work before #6816 ? cc @jdebp

This worked in NVIM v0.2.1-442-g69f0847cc and does not work in NVIM v0.2.1-516-g226603a8d

I'm in iTerm2 on macOS Sierra with `guicursor=`:

```
    let &guicursor = 'n-v-c-sm:block-blinkwait1000-blinkon500-blinkoff500,'
        \          . 'i-c-ci-ve:ver25-blinkwait1000-blinkon500-blinkoff500,'
        \          . 'r-cr-o:hor20-blinkwait1000-blinkon500-blinkoff500'
```

**Comment by wsdjeg** [comment]
@DarkDefender `export TERM=xterm-256color` fix this issue.

**Comment by DarkDefender** [comment]
@wsdjeg I not sure, but I think that it might then be that the termite terminfo is not correct. If I understand the recent changes correctly, then neovim now trusts/uses the terminfo more than before. So if the terminfo is not correct then there will be problems.

**Comment by wilywampa** [comment]
Another data point: I can still get a vertical bar both inside and outside of tmux with `TERM=xterm-256color`. I assume it causes other issues inside tmux though.

**Comment by justinmk** [comment]
If you are using tmux  TERM is only two choices:

screen-256color
tmux-256color

Pick one.

**Comment by wilywampa** [comment]
?

`screen-256color` is what I've picked already. I'm just saying this particular problem goes away when I temporarily change to `xterm-256color` for testing.

**Comment by DarkDefender** [comment]
@wilywampa Is the problem still there if you use tmux-256color instead?

**Comment by wilywampa** [comment]
When I try `tmux-256color` the cursor is always a blinking block regardless of mode.

**Comment by ahmedelgabri** [comment]
@justinmk I'm using tmux with `TERM=tmux-256color` & the cursor doesn't change while outside of tmux with `TERM=xterm-256color` the cursor works fine.

**Comment by jdebp** [comment]
DarkDefender has hit the nail on the head.  Check your terminfo record for the `tmux` terminal type you are using, using the `infocmp` tool.  If it does not contain `Ss` and `Se` entries, then you should bring it up to date.  Those are what tell nvim how to change your cursor shape when it is talking to a tmux terminal.  Ironically, this is a terminfo extension that was pioneered by the very program that you are using, tmux.

Read `:help cursor-shape` for the details and also `:help terminfo`.

**Comment by jdebp** [comment]
For those of you not using tmux, if you update your terminfo to add `Ss` and `Se` you will make _both_ tmux and nvim happy, as they both look for these.  As the help explains, nvim tries to fill in for some terminal types, including libvte ones.  The detection of libvte is done by looking for the `VTE_VERSION` environment variable and checking the version therein.  

If that is not set, _nvim cannot know what to do_.  libvte has to be positively decoded, because there are terminal types that lie about being Xterm and that do not work well with DECSCUSR.  This includes older versions of libvte.  So you must ensure that nvim has this way to know that you are using a libvte terminal emulator and what version of libvte it is.

**Comment by justinmk** [comment]
Since we have a builtin tmux terminfo, why don't we always use that?

**Comment by wilywampa** [comment]
I used the tmux `terminal-overrides` described [here](https://github.com/neovim/neovim/issues/6778#issuecomment-302944787) (`set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'`) and I'm still getting the underscore instead of vertical bar. I tried modifying the screen-256color terminfo to add the two capabilities but when I attempt to compile it I get `terminal 'screen-256color': unknown capability 'Ss'`. Am I still doing something wrong?

**Comment by teto** [comment]
I have VTE_VERSION=4802 TERM=vte with termite HEAD. termite does not provide "Ss" or "Se". Thus nvim enter this code
```
    } else if (
        // per MinTTY 0.4.3-1 release notes from 2009
        putty
        // per https://bugzilla.gnome.org/show_bug.cgi?id=720821
        || (vte_version >= 3900)
        // per tmux manual page and per
        // https://lists.gnu.org/archive/html/screen-devel/2013-03/msg00000.html
        || screen) {
      // Since we use the xterm extension, we must map it to the unextended form
      data->unibi_ext.set_cursor_style = (int)unibi_add_ext_str(ut, "Ss",
          // "\x1b[%?" 
          // "%p1%{4}%>" "%t%p1%{2}%-"     // a bit of a bodge for extension values
          // "%e%p1"              // the conventional codes are just passed through
          "\x1b[%p1%d q");       // <----- I MODIFIED THIS LINE AND COMMENTED THE PREVIOUS
      ILOG("this happens too %d",data->unibi_ext.set_cursor_style );

```
The default given seems like the source of the problem as if I replace by a simple version it fixes the problem. I don't know terminfo syntax so I am not sure what the rest does or if it's a VTE parsing pb.
I've added Ss and Se but have yet to install it. Is it possible to log from which file the TERMINFO was loaded ? or add some unibilium flag just to help testing ?

**Comment by DarkDefender** [comment]
@teto and @wilywampa does #6997 fix this for you guys?

**Comment by wraithy** [comment]
@DarkDefender I can confirm that your branch fixes the problem. The guicursor options work correctly regardless of tmux. I also removed the `set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'` and that made no difference.

One thing I did notice was that setting `hor[N]` in guicursor always produced a one pixel underscore, regardless of N. I don't think this is relevant to your change though - it's probably just my terminal.

**Comment by wilywampa** [comment]
@DarkDefender #6997 did fix this problem for me. Thanks!

**Comment by rafaeln** [comment]
This might have broken something for me. 

Now I can only get the different cursor shapes directly under rxvt 9.21 (even though both `infocmp | grep Ss` and `infocmp | grep Se` give me no output (which I interpret as meaning that both `Ss` and `Se` are absent from my terminfo)).

When I enter tmux, I can't get the cursor shapes anymore (I used to be able to before updating to the latest head version).
