### ISSUE TITLE
Implement consistent way to return errors from functions

### ISSUE THREAD

**Issue by stefan991** [neovim/neovim#698]
Many functions in `src/os` only return a bool to indicate success or failure. There is currently no way to get the error that caused a failure. See this comment from @jszakmeister https://github.com/neovim/neovim/pull/619#discussion-diff-12368524.

I don't think we should use libuv error codes directly, because we should be able to handle errors in a consistent way, even if they are not from libuv. The same approach should be used in the whole codebase (or at least new code).  We may need to consider the already implemented vim errors, see `help errors`.

**Comment by justinmk** [comment]
Some improvements were made towards this, but otherwise it's not concrete enough to have a "done" state.
