### ISSUE TITLE
[fifo/socket][READ ERRORS]

### ISSUE THREAD

**Issue by mkoskar** [neovim/neovim#6980]
- `nvim --version`: NVIM v0.2.1-511-g105d680ae
- Vim (version: 8.0.0628) behaves differently? yes
- Operating system/version: Linux 4.11.5-1-ARCH SMP PREEMPT x86_64 GNU/Linux
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode-256color

I'm using vim/nvim as a pager, and for it I'm doing a bit of trick which is working fine generally but recently (actually for quite some time already) causing an error in `nvim` but only for some input.

Reasons for the trick (see below) were mainly for `vim` (getting rid of "reading from stdin" message and also starting UI asap to smooth the experience), and I suspect that the whole behavior I'm seeing in `nvim` is due to the fact that reading from stdin is done differently now (I gather because of TUI vs. core separation?). I'm wondering though if this error I'm seeing is OK (it's expected) or should be fixed/handled somehow.

This works OK:
```
$ echo testing | bash -c 'exec 8<&0 0<&1 ; nvim -u NONE -c "edit /dev/fd/8"'
or
$ bash -c 'exec 8<&0 0<&1 ; nvim -u NONE -c "edit /dev/fd/8"' <<<testing
```

With binary content it **doesn't**:
```
$ cat /usr/bin/false | bash -c 'exec 8<&0 0<&1 ; nvim -u NONE -c "edit /dev/fd/8"'
```

and error message is:
```
[fifo/socket][READ ERRORS] 0L, 0C
```

Although following **does** work:
```
$ bash -c 'exec 8<&0 0<&1 ; nvim -u NONE -c "edit /dev/fd/8"' </usr/bin/false
```

**Comment by jamessan** [comment]
Can you see if #6977 works any better?

**Comment by mhinz** [comment]
Yup, #6977 fixes this.

Before:

```
"/dev/fd/8" [fifo/socket][READ ERRORS] 0L, 0C
```

After:

```
"/dev/fd/8" [readonly][noeol] 30L, 17760C

**Comment by mkoskar** [comment]
Yes me too, I confirm #6977 fixes this!
I thought this will be one peculiar issue not very easy to solve, but how wrong I was, haha.
Thanks, I guess this can be closed then.
