### ISSUE TITLE
Downgrade to 0.1.17?

### ISSUE THREAD

**Issue by yifanchen** [neovim/neovim#6981]
- `nvim --version`: 0.2.1
- Vim (version: ) behaves differently? Running slowly
- Operating system/version: macOS Sierra
- Terminal name/version: iTerm 
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

Hey I am on 0.2.1 now, is there a way downgrade it to 0.1.17?

**Comment by ZyX-I** [comment]
Just remove existing installation and install 0.1.17. Even if you don’t have it available via the means you installed Neovim originally, you can always build from source, using `v0.1.17` tag.

In any case, this is not Neovim issue, packages are not maintained here.
