### ISSUE TITLE
neovim doesn't wait for motion on delete command under heavy load

### ISSUE THREAD

**Issue by jakalope** [neovim/neovim#6988]
- `nvim --version`: 0.2.0
- Vim (version: 8.0.0702) behaves differently? Yes. Since Vim 8's terminal is not complete, I attempt to repro by tying up all my cores in a separate terminal and Vim 8 does not exhibit the problem.
- Operating system/version: MacOS 10.12.5  (also present on Ubuntu 14.04 / terminator / nvim 0.2.0)
- Terminal name/version: iTerm2 3.0.15
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:vs term://bash       " create a terminal split
$$ cd ~/workspace/vim             # go to vim source
$$ make distclean && ./configure  # clean and configure
$$ make -j && make install        # tie up all cores (this is key)
<C-\><C-n>      " drop out of terminal mode
<C-w>hi         " go to text buffer and start insert mode
asdfasdf<CR>    " enter some lines of text
fdasfdsa<Esc>d  " start a delete command
```

### Actual behaviour

At this point, the current line is deleted in full,
without waiting for a motion. Interestingly, in the lower
right corner, the 'd' indicator is still present after the
line has been deleted.

### Expected behaviour

The `d` command should do nothing until a motion or
`<Esc>` are pressed.

**Comment by jakalope** [comment]
Just confirmed this is also the case in 0.1.7.

**Comment by jakalope** [comment]
I can also repro by running `find ${HOME}` instead of by building. Which means my 4 core machine is not under heavy load but the terminal is scrolling quite fast.

**Comment by dm1try** [comment]
confirm
> so it seems to be related to having the terminal within neovim. Possibly fast-scrolling text.

output  for `while true; do sleep 1; echo test; done` leads to such behavior too; so it's somehow related to terminal output in general(?)

**Comment by jakalope** [comment]
Whilst running the following in my vsplit term:
```
while [[ 1 ]]; do find ${HOME}; done
```
I ran `syntime on` and `syntime report` with the following output:
```
  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.049149   14660  7330    0.001098    0.000003  pbFloat            \<-\?\d*\(\.\d*\)\?
  0.030733   7330   0       0.000921    0.000004  pbInt              -\?\<\d\+\>
  0.004701   7330   0       0.000089    0.000001  pbString           '
  0.001740   7330   0       0.000080    0.000000  pbString           "
  0.001417   7330   0       0.000071    0.000000  pbComment          \/\*
  0.001246   7330   0       0.000014    0.000000  pbInt              \<0[xX]\x+\>
  0.001236   7330   0       0.000021    0.000000  pbComment          //

  0.090222   58640
```

**Comment by jakalope** [comment]
I just ran `while true; do sleep 1; echo test; done` and removed the split, leaving the terminal hidden and it still repros (still causes `d` to delete a line within 1 second).

**Comment by jdebp** [comment]
I meant to report this myself.  It's not load related, as I have seen this on a lightly loaded machine.  It appears to occur when there is a terminal running _and_ that terminal is processing output.  I haven't narrowed it down to what kind of output, e.g. whether it only happens when the terminal is scrolling or whether just printing stuff over and over on a single line also triggers it; and whether the amount of output is relevant somehow.  But I have confirmed that it only happens when the terminal is not sitting idle with no output to process.

**Comment by justinmk** [comment]
Incidentally, I've been looking into this today. `:set notimeout` is a workaround. Same issue as https://github.com/neovim/neovim/issues/6166

Thanks for the reports.
