### ISSUE TITLE
vim-airline: mouse click on AirlineSelectTab disables its ability to resize buffer splits

### ISSUE THREAD

**Issue by randomizedthinking** [neovim/neovim#6996]
- `nvim --version`: v0.2.0
- Vim (version: v8.0.550) behaves differently? yes, differently
- Operating system/version: Debian Stretch
- Terminal name/version: urxvt 9.22
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

First, clone the vim-airline project to `~/.vim/plugged/vim-airline`; then create a file `debugrc` with the following content.

```
set mouse=nicr
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#switch_buffers_and_tabs = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1

nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4

set runtimepath+=~/.vim/plugged/vim-airline/
source ~/.vim/plugged/vim-airline/plugin/airline.vim
source ~/.vim/plugged/vim-airline/autoload/airline.vim
```

### Actual behaviour

1. `nvim -u NORC`
2. `:so debugrc`
3. `:e debugrc`

At this step, the vim-airline plugin is activated. The top line with `debugrc` on it is the AirlineSelectTab area.

4. `:sp`

By then, one should be able to resize the buffer split by mouse click and drag.

5. Use mouse to click the AirlineSelectTab area.

Now, the mouse mysteriously losses its ability to resize buffer split.

### Expected behaviour

The expected behavior is that after Step 5, mouse can still resize buffer split.

I also submitted a report to vim-airline, yet they think it could be a neovim problem. You can find it at: https://github.com/vim-airline/vim-airline/issues/1508.

**Comment by justinmk** [comment]
Is this the same as https://github.com/neovim/neovim/issues/5400 ?

**Comment by randomizedthinking** [comment]
Yes, it is the same. At least, vim v8.0 does not have the problem. Not sure whether vim 7.4 has it or not, then can determine whether it is a regress or due to miss of some patches in vim8.

**Comment by justinmk** [comment]
It's our bug. Not a missing patch.
