### ISSUE TITLE
Disabled colorscheme inside Tmux - set termguicolors?

### ISSUE THREAD

**Issue by taq** [neovim/neovim#6999]
- `nvim --version`: v0.2.1-dev
- Vim (version: ) behaves differently? Yes, works fine
- Operating system/version: Ubuntu 17.04
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

Last update today disabled all the colorschemes inside Tmux. Using classical Vim, works ok inside Tmux. Using Neovim, just get monochromatic colors. But using `NORC`, it loads ok. Disabling plugin by plugin and config by config, I found that using `set termguicolors` as before gives me that behaviour. I'm using it on a `sourced` file on my `init.vim`. Something changed?

### Expected behaviour

Colors working ok inside Tmux using the same configurations as before.

**Comment by offa** [comment]
Possible related to #6982.

**Comment by jamessan** [comment]
@taq The exact version from `nvim --version` should be provided as the tmux issues should already be resolved in master, due to #6991.

**Comment by taq** [comment]
Hey @jamessan and @offa! Didn't see #6982 and #6991 while searching here, sorry. Probably the same thing as there. I'll close it here, thanks!
