### ISSUE TITLE
'guicursor' colors bleed into all tmux panes/windows when in iterm2.

### ISSUE THREAD

**Issue by bluz71** [neovim/neovim#7001]
Hello Neovim support,

I did a search and could not find an existing issue for this; apologies if my searching was poor. Feel free to close if this is a repeat.

Version:
- nvim 0.2.0
- tmux 2.5
- iterm2 3.0.15

Here is the minimal *init.vim*:

```
syntax on
set termguicolors
set guicursor=n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor
hi Cursor guibg=#528bff

autocmd VimLeave * set guicursor=a:block-CursorReset
highlight CursorReset guibg=#9e9e9e
```

Inside iterm2 start *tmux* and create a few windows. In the first window launch *nvim*; you should see a blue cursor, then change to a different tmux window, the terminal cursor will now be the same blue color as configured for *nvim*.

My testing on Linux yields different results, both *xterm* and *gnome-terminal* do not suffer this issue. The cursor is only blue in *nvim*. Note, I am also using tmux 2.5 and nvim 0.2.0 version on Linux.

The desired result is the Linux result; cursor coloring just like cursor shape changing should be confined to the *nvim* edit window/pane only.

Many thanks.

**Comment by DarkDefender** [comment]
Did this work without issue before?
If not, then I think that this problem might not be a fixable problem.

You can take a look at the specific code here:
https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L1618-L1623

As you can see, there is a specific if path for item. And there is a tmux wrapper function attached to it. Unless the tmux wrap has been added in error, it is highly likely that tmux does not support the specific iterm terminal code for cursor color. So if you do not wrap it, tmux would not change cursor color and most likely print garbage at the cursor position when trying to change color.

**Comment by DarkDefender** [comment]
BTW, you can try it out yourself in tmux by running:
xterm style:
`echo -ne "\033]12;#528bff\007"`
iterm style:
`echo -ne "\033]Pl528bff\\033\\"`

If the iterm style work in a tmux terminal outside of nvim, then this should be fixable.

**Comment by bluz71** [comment]
Ok,

`echo -ne "\033]Pl528bff\\033\\"` --> changes cursor in normal iterm2

`echo -ne "\033]Pl528bff\\033\\"` --> has **no** effect when run in tmux 2.5 inside iterm2

Yep, tmux 2.5 on iterm2 is not a good combination for cursor color resetting upon window changing. Once *nvim* changes the cursor color ALL tmux panes will have the same color inside iterm2.

I can't say what happened with tmux 2.4 since I only started playing with *nvim* cursor coloring very recently and homebrew has no good downgrade story.

Indeed this may not be fixable; strange since it works fine on vte terminals and xterm. First world problems.

I don't mind if this is closed; I've disabled cursor color in my *vimrc*.

**Comment by DarkDefender** [comment]
@bluz71 It is not that strange that it work with vte and xterm really.

It seems to me that out of all the terminals that supports changing cursor color, only iterm has it's own special terminal code to do so. Tmux most likely only supports the xterm code. IE, it knows what the code does and does the right thing. 

However it doesn't support the iterm style and therefore does not know what to do with it.

Ideally, iterm should implement support for the xterm style code and solve it that way.

**Comment by justinmk** [comment]
It's a known issue https://github.com/neovim/neovim/blob/0a7e7e0ecfff2d9b261f964c0e79e6575d655218/src/nvim/tui/tui.c#L1618-L1627

```c
if (iterm || iterm_pretending_xterm) {
   // FIXME: Bypassing tmux like this affects the cursor colour globally, in
   // all panes, which is not particularly desirable.  A better approach
   // would use a tmux control sequence and an extra if(screen) test.
   data->unibi_ext.set_cursor_color = (int)unibi_add_ext_str(
   ut, NULL, TMUX_WRAP(tmux_wrap, "\033]Pl%p1%06x\033\\"));
   } else if (xterm) {
   data->unibi_ext.set_cursor_color = (int)unibi_add_ext_str(
   ut, NULL, "\033]12;#%p1%06x\007");
   }
```

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/6778
