### ISSUE TITLE
termguicolors broke after upgrade

### ISSUE THREAD

**Issue by hholst80** [neovim/neovim#7003]
- `nvim --version`:

```
neovim/xenial 0.2.0ubuntu1+git201707091951+3517+26~ubuntu16.04.1 amd64 [upgradable from: 0.2.0ubuntu1+git201707011648+3496+26~ubuntu16.04.1]
```

- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 16.04
- Terminal name/version: tmux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

hard to reproduce since termguicolors must be set in ~/.config/nvim/init.vim

### Actual behaviour

black and white colorschmes when using termguicolors.

### Expected behaviour

truecolor/256 color support in colorschemes.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/6997

**Comment by DarkDefender** [comment]
I'm working on a different pull request for the colors stuff. Stay tuned.

**Comment by DarkDefender** [comment]
Can you see if #7004 fixes it?

**Comment by ExpandingMan** [comment]
I am using tmux and experiencing this as well.  None of the suggestions in the FAQ were helpful.

**Comment by carlitux** [comment]
@ExpandingMan I am using tmux and fixed in this way tmux config

```bash
set -g default-terminal "tmux-256color"
```

with ncurses > 6.x.x to use ncurses terminfo database

**Comment by ExpandingMan** [comment]
Thanks, but this did not fix it for me.

**Comment by DarkDefender** [comment]
@ExpandingMan does my pull request fix it?

**Comment by snahor** [comment]
@DarkDefender your PR works great

**Comment by bohrshaw** [comment]
@carlitux 's workaround works for me.

**Comment by justinmk** [comment]
`set -g default-terminal "tmux-256color"` is not really a workaround, though. TERM needs to be correct, in most cases the terminal can't be detected otherwise.

**Comment by Yuri-M-Dias** [comment]
Restarting tmux with @carlitux's idea works here, but it breaks fish with tmux(and other stuff), as they expect the `screen-256color`, which was what I had set up before. The autocomplete gets kinda broken, so not really worth to keep this for now. I'm using the latest from `apt` too.

Fish complains:
```
<W> fish: Could not set up terminal.
<W> fish: TERM environment variable set to 'tmux-256color'.
<W> fish: Check that this terminal type is supported on this system. 
<W> fish: Using fallback terminal type 'ansi'.
machine^Ctput: unknown terminal "tmux-256color"                  
```

Even Less complains about it:
```
WARNING: terminal is not fully functional
```

I'll test it with @DarkDefender's PR later and report it.

**Comment by chiuczek** [comment]
I've found a similar issue. In an ordinary terminal nvim works as expected with all colours, but in tmux everything is black and white. If I `export TERM="tmux-256color"` then I get some colours, but a limited palette, and it breaks my zsh prompt

**Comment by carlitux** [comment]
@chiuczek how it breaks your zsh prompt? do you have the latest ncurses installed and using the terminfo data from it?

**Comment by chiuczek** [comment]
@carlitux To be honest I don't know, I haven't delved that deep into terminal setup. My zsh prompt uses some special characters and right aligned info, none of which show when I change `TERM`, zsh says `can't find terminal definition for tmux-256color`.

**Comment by jamessan** [comment]
Then you should be using `screen-256color`.

**Comment by chiuczek** [comment]
`screen-256color` works in that zsh looks right, but nvim then has no colours. If I use `screen-256color` outside tmux I also get no colours in nvim. I still get colours in nvim when I run it from a bare terminal (where `TERM` is `xterm-256color`)

**Comment by jamessan** [comment]
1. You shouldn't be using `screen-256color` outside of tmux/screen.
2. Yes, we know the colors aren't working right.  That's what #7004 is working on fixing.

**Comment by chiuczek** [comment]
#7004 did not fix the issue for me, in fact it broke the workaround which I was using, and now it's impossible to get any colours in nvim on tmux

**Comment by justinmk** [comment]
@chiuczek @Yuri-M-Dias what about https://github.com/neovim/neovim/pull/7037 ?

**Comment by chiuczek** [comment]
#7037 works, I'm getting colours in tmux as expected

**Comment by Yuri-M-Dias** [comment]
@justinmk #7037 works here too, the colors are back. With the previous mentioned "screen-256color" variable too.

**Comment by mvrozanti** [comment]
I think this is happening to me after a system update. Neovim works only outside of `tmux`. Can anyone share a [temp]fix?

**Comment by justinmk** [comment]
@mvrozanti This was resolved last year. Without mentioning versions or or details about your environment, your comment has no context. Ask on https://gitter.im/neovim/neovim or https://vi.stackexchange.com .
