### ISSUE TITLE
First run sudo nvim creates ~/.local/share/nvim as user root

### ISSUE THREAD

**Issue by wizzat** [neovim/neovim#7006]
- `nvim --version`:

~ $ nvim --version
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UFyCc4/neovim-0.1.7=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UFyCc4/neovim-0.1.7/build/config -I/build/neovim-UFyCc4/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-UFyCc4/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-UFyCc4/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

- Vim (version: ) behaves differently? Yes
- Operating system/version: Ubuntu-gnome 17.04
- Terminal name/version: default terminal
- `$TERM`:
~ $ echo $TERM
xterm-256color

### Steps to reproduce using `nvim -u NORC`
rm -rf ~/.local/share/nvim
sudo nvim /etc/resolv.conf
nvim abc.txt
E886: System error while opening ShaDa file /home/mroberts/.local/share/nvim/shada/main.shada for reading: permission denied
Press ENTER or type command to continue

```
nvim -u NORC

```

### Actual behaviour
Creates directory as root user

### Expected behaviour
Doesn't create directory as root user

**Comment by fwalch** [comment]
See https://github.com/neovim/neovim/issues/4551#issuecomment-219788479 and following.

**Comment by wizzat** [comment]
Nice - thanks. I actually did search too. O.o
