### ISSUE TITLE
Cursor position rewinded in quickfix window after reopen it.

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#7014]
- `nvim --version`: NVIM v0.2.1-514-g1e59215d7
- Vim (version: ) behaves differently? yes
- Operating system/version: Win7 64bits
- Terminal name/version: neovim-qt
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:copen 5
:caddexpr "1\n2\n3\n4\n5\n\n6\n7\n8\n9"
:normal G

:cclose
:copen 5
```

### Actual behaviour
cursor in quickfix window rewinded to the first line after the second `:copen 5`

### Expected behaviour
Cursor should stay at the same position after reopen. 

In a rapid edit-compile-edit cycle, I use F10 to toggle quickfix window and check erros frequently. The rewinding confused me every time I reopen the quickfix window.

**Comment by justinmk** [comment]
Wasn't this a recent Vim patch?

**Comment by skywind3000** [comment]
oh, that's true.

**Comment by justinmk** [comment]
Still occurs in 0.3.0.

**Comment by justinmk** [comment]
also happens in `vim --clean` 8.2.2029

there must be an option that needs to be set. closing until then
