### ISSUE TITLE
Getting around the lack of support for interactive commands in :w !command?

### ISSUE THREAD

**Issue by sejdm** [neovim/neovim#7016]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently? Yes, vim 8.0 behaves differently
- Operating system/version: Ubuntu 16.04
- Terminal name/version: Tmux or SimpleTerminal
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
`urlview` is a commandline program meant to read text form the stdin, output a list of urls that it finds in that text, and wait for you to select the url to open in an external browser. In vim, I can do `w !urlview` to send the buffer contents to `urlview` and select the correct link within vim, but I am aware that neovim does not allow interactive commands like this with `w !`. However, is there any work around using :terminal or anything else rather than having to use vimscript or python? 

`:terminal` seems to take care of `:!interactivecommand`, but can it also take care of `:w !interactivecommand` or `:%w!interactivecommand` (anything that involves piping the contents of the buffer)?  I could, of course, save the contents to a temporary file, and hack out something, but that would be rather messy and perhaps slower. I cannot yet think of example other than `urlview` but it would be nice to not have to exclude commands that need some further information via the stdin to process the contents of the buffer that was piped into it.

Thanks!

**Comment by aktau** [comment]
AFAIK, the Vim plugin delivered with fzf uses the tempfile solution (+ :terminal) that you suggested. I'm not sure if there's anything better out there...

**Comment by sejdm** [comment]
Thanks, that is disappointing! I had assumed that a plugin would probably use some vimscript function that, though verbose (unlike the vim one-liner), did not at least need a temp file. 

Even a named pipe does not help because it gets blocked and prevents the command from running in :terminal.

**Comment by mhinz** [comment]
`:term urlview %`?

**Comment by sejdm** [comment]
@mhinz Thanks, I suppose your solution works because it is essentially replacing % by the filename? Therefore, I suppose one cannot apply this solution to a selection, but only the entire file, right? Plus it is forcing you to save the buffer, although that is not a very serious problem in many cases. Also, I suppose this cannot give you an interactive filter (one that filters the text based on some user input) like `%!interactivetextfilter` would do in vim?

Nevertheless, the solution is quite an improvement and definitely useful in certain cases! Thanks!

**Comment by mhinz** [comment]
Yup, what you said.

I don't know the current state, but I think the goal is to make `:!` (and friends) to be interactive (again).

See: https://github.com/neovim/neovim/issues/1496

**Comment by justinmk** [comment]
Yes, covered by https://github.com/neovim/neovim/issues/1496 and https://github.com/neovim/neovim/issues/5431

**Comment by ZyX-I** [comment]
One may use `jobsend()` with `termopen()` in place of `:terminal` (needed function for its output, could use `b:terminal_job_id` instead), this allows piping text. Wrap that with a command with `-range` to make it easier to use. `:terminal urlview %` needs to be `:terminal urlview %:S`, first variant does not care about escaping.

@justinmk BTW, should not all our special variables have `nvim` prefix, including terminal ones?

**Comment by ZyX-I** [comment]
No, `termopen()` with `jobsend()` does not work for urlview. Need to either create another pipe and just close it or somehow send EOF without actually closing the channel. If I am not mistaking, current API allows neither.

**Comment by justinmk** [comment]
> should not all our special variables have nvim prefix, including terminal ones?

I guess. But I think we should commit to  "real options" rather than these special variables.
