### ISSUE TITLE
system() call to interactive program slow to execute

### ISSUE THREAD

**Issue by lifepillar** [neovim/neovim#7019]
- nvim 0.2.0 (installed with `brew install neovim`)
- Vim 8.0.703 has no issue
- Operating system/version: macOS Sierra 10.12.5
- Terminal name/version: Terminal.app/iTerm2 Nightly
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

Make sure `tput` and `fzf` are found in your `$PATH`.

```
nvim -u NORC
:call system(printf('tput cup %d >/dev/tty; tput cnorm >/dev/tty; echo "Hello" |fzf -m --height 20 >out.txt 2>/dev/tty', &lines))
```

### Actual behaviour

`fzf` opens after a couple of seconds. After pressing Enter to close `fzf`, Vim enters Replace mode.

### Expected behaviour

`fzf` should open immediately, and close immediately after pressing Enter (ctrl-l is needed to redraw the screen). Vim should stay in Normal mode.

### Other comments

I use the command above with Vim without problem. There's probably a better way in NeoVim (using `:terminal`? Suggestions are welcome). Anyway, the behaviour looks buggy to me.

**Comment by ZyX-I** [comment]
`system()` is not supposed to call any interactive applications. You should either use `:term` or `jobstart()` with `'pty': 1` in options.

**Comment by ZyX-I** [comment]
Also see https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes.
