### ISSUE TITLE
Incorrect `clipboard: no provider` message

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7020]
```
NVIM v0.2.1-442-g69f0847
Build type: Release
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/mqudsi/random/neovim/build/config -I/home/mqudsi/random/neovim/src -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/usr/include -I/home/mqudsi/random/neovim/build/src/nvim/auto -I/home/mqudsi/random/neovim/build/include
Compiled by mqudsi@ZBook
```

Before anything else: I'm not sure if my `g:clipboard` syntax is correct. By default, `nvim` is not detecting a clipboard provider in my WSL installation (which is probably another bug). So I manually execute `let g:clipboard = ['win32yank']` after which `:CheckHealth` reports success:

```
 ## Clipboard (optional)
SUCCESS: Clipboard tool found: win32yank
```

However, trying to use the system clipboard register (`*`) causes `nvim` to throw the following message:
> clipboard: No provider. Try ":CheckHealth" or ":h clipboard".

**Comment by jamessan** [comment]
Do you have both the 32-bit (and 64-bit if you have 64-bit nvim) Visual Studio 2015 C++ redistributable installed, as mentioned in the [wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim#pre-built-archives)?

**Comment by mqudsi** [comment]
Yes, because I'm able to execute win32yank.exe from the command line just fine.

**Comment by mqudsi** [comment]
Also: if it *were* a missing runtime libraries issue, this would still be a bug since the provider *is* installed, just misbehaving (basically if `:CheckHealth` returns success for the clipboard provider, a different message should be shown that provides actually helpful information about the problem.)

**Comment by justinmk** [comment]
let g:clipboard = ['win32yank']

Yeah, `:CheckHealth` is just not rigorous enough here. The only valid structure of `g:clipboard` is shown at `:help g:clipboard`.

**Comment by mqudsi** [comment]
@justinmk so I saw that before, but I presumed that was the syntax for defining a custom provider. How do I specify that win32yank should be used?

**Comment by justinmk** [comment]
Paste the example from `:help g:clipboard` into your init.vim and change `'tmux ...'` with the appropriate values. E.g.:

```vim
let g:clipboard = {
          \   'name': 'win32yank-wsl',
          \   'copy': {
          \      '+': 'win32yank.exe -i --crlf',
          \      '*': 'win32yank.exe -i --crlf',
          \    },
          \   'paste': {
          \      '+': 'win32yank.exe -o --lf',
          \      '*': 'win32yank.exe -o --lf',
          \   },
          \   'cache_enabled': 0,
          \ }
```

If `win32yank.exe` is not in your `$PATH` make it an absolute path.

Note that Nvim already should use win32yank out of the box, if `executable('win32yank')` returns non-zero (does it, for you?)

**Comment by mqudsi** [comment]
No, I understand that. I just thought that there was some way to tell g:clipboard to use a pre-existing "dictionary" instead of defining my own (as in, the win32yank dictionary is defined somewhere for neovim to use, so maybe I should be able to tell neovim to use it instead of having to redefine it).

**Comment by mqudsi** [comment]
fwiw, `cache_enabled: 1` works under Windows (I didn't expect it to).
