### ISSUE TITLE
Replace win32yank.exe with a solution that doesn't require MSVC runtime

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7022]
Currently, neovim uses `win32yank.exe` to interact with the system clipboard on Windows and under WSL.

I initially mentioned WSL system clipboard support in #6227 and learned about `win32yank.exe`, but not before I had written my own clipboard provider for Windows/WSL: https://github.com/neosmart/paste

After learning that `win32yank.exe` provided the same functionality and could be used for the same purpose, I was more than happy to leave things at that. This is a bit awkward since I am suggesting replacing something with my own code, but I want to make sure I'm clear that I was perfectly fine with `win32yank.exe` being the system clipboard provider under Windows and WSL in all the months since then and would not be suggesting this if I did not objectively think this was a better approach.

win32yank.exe is built with rust, which apart from requiring the entire rust build toolchain to be installed, means that it is also linked against the MSVC (or, optionally, the mingw runtime) and requires the runtime to be installed to use win32yank.exe

By contrast, `paste.exe` does not use the C/C++ runtime at all, which means it has zero dependencies and no build requirements aside from a working C compiler. The `paste` binaries will run on all versions of Windows without any additional requirements.

I imagine that removing runtime requirements will make using nvim on Windows/under WSL much more straightforward and will aid in making debugging clipboard provider issues a lot easier (e.g. the first response to #7020, which is what triggered my posting this issue in the first place).

(I think `paste` is missing some functionality required by neovim that `win32yank` currently provides. I'll be more than happy to fix that if someone could point it out (iirc it had something to do with line endings).)

**Comment by justinmk** [comment]
> requiring the entire rust build toolchain to be installed, 

To build it only. I certainly don't have the rust tool chain.

Nvim itself requires the ms crt. Discussed elsewhere.

Not opposed to a better solution, but the premise here is questionable.

**Comment by mqudsi** [comment]
I did not realize win32yank and neovim were linked against the same runtime; there is no point in this discussion if that is the case. 

(No one should ask if the runtime is installed if one is reporting a clipboard provider error, if that is really the case.)

**Comment by jamessan** [comment]
There's a win32yank PR that's open to build both 64-bit and 32-bit binaries.  In the meantime, only a 32-bit binary is built (and bundled with nvim).  If you're installing the 64-bit nvim, then you need to install _both_ the x86 and x86_64 VC redist, otherwise win32yank will silently fail, similar to how @mqudsi reported in #7020.

I was seeing this for a few weeks on one of my Windows systems, and updated the wiki with the instructions I quoted once I figured out this was the problem.

So, what needs to happen is to get the win32yank PR resolved and then include the proper win32yank build with nvim.

**Comment by jamessan** [comment]
> There's a win32yank PR that's open to build both 64-bit and 32-bit binaries

Ah, that's been merged already and there's a v0.0.4 win32yank release which produces both binaries.  Looks like we just need to handle the nvim side of things now.

**Comment by mqudsi** [comment]
Any reason we can't statically compile the rust win32yank binary for the msvc target? How much larger does it become?

cc @equalsraf

**Comment by justinmk** [comment]
@mqudsi you mean include the ms CRT? Or what, exactly? In the original report you mentioned needing rust to be installed, which only applies to developers. What exactly is the problem you are having now?

**Comment by mqudsi** [comment]
It's the original issue with the unneeded dependency on MSVCRT, the request is to statically link against MSVC's libc equivalent so that dependency can be dropped. But I suppose this can just be closed since CRT is a dependency for neovim anyway. I just ran into the issue because I was using only win32yank from the binary distribution while compiling everything else from scratch under WSL.
