### ISSUE TITLE
Need to select line _below_ status line when resizing panes with mouse

### ISSUE THREAD

**Issue by gordonbazeley** [neovim/neovim#7025]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 22 2017 03:02:45).  Yes - works as expected 
- Operating system/version: macOS Sierra 10.12.5
- Terminal name/version: iTerm2 Build 3.0.15
- `$TERM`: screen-256color: command not found

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Can't reproduce in this mode since mouse seems not to be operational
Repro steps in normal operation
:e [file_1]
:sp [file_2]
Using the mouse select the status line of file_1 and try to resize the pane - doesn't work
Using the mouse select the line below the status line of file_1 and try to resize the pane - does work

I've tried disabling all plugins but that didn't make a difference.  I can't see any current issues that relate to this.

### Actual behaviour
Clicking the status line of a pane and moving the mouse up or down does nothing 
Clicking the line below the status line of a pane and moving the mouse up or down resizes pane

### Expected behaviour
Clicking the status line of a pane and moving the mouse up or down resizes pane

**Comment by justinmk** [comment]
> Can't reproduce in this mode since mouse seems not to be operational

Try like this:

```
nvim -u NORC
:set mouse=a
```

**Comment by gordonbazeley** [comment]
thanks @justinmk I should have thought of that :-) I've tried as suggested and mouse pane resizing works as it should.  Does that suggest a setting issue perhaps?

**Comment by justinmk** [comment]
Maybe. If you can reduce it to a specific option or plugin, that will help diagnose.

**Comment by gordonbazeley** [comment]
Spent ages playing round trying to recreate by disabling config settings to no avail. Have installed head and the issue is addressed - closing
