### ISSUE TITLE
build: download/install win32yank on WSL

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7031]
Running neovim from master under WSL on Windows 10 15063.483:
```
NVIM v0.2.1-556-gd72db1a
Build type: Release
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/mqudsi/random/neovim/build/config -I/home/mqudsi/random/neovim/src -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/home/mqudsi/random/neovim/.deps/usr/include -I/usr/include -I/home/mqudsi/random/neovim/build/src/nvim/auto -I/home/mqudsi/random/neovim/build/include
Compiled by mqudsi@ZBook

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

Running `:CheckHealth` returns the following:

```
17 health#provider#check                                                                                             
18 ========================================================================                                          
19 ## Clipboard (optional)                                                                                           
20   - WARNING: No clipboard tool found. Clipboard registers will not work.                                          
21     - SUGGESTIONS:                                                                                                
22       - :help clipboard        
```

Searching for win32yank:
```
mqudsi@ZBook /m/c/U/Mahmoud> find / -iname 'win32yank*' 2>/dev/null
mqudsi@ZBook /m/c/U/Mahmoud>
```

(that search includes the neovim build directory)

**Comment by justinmk** [comment]
How can nvim know it's running on Windows, from WSL?

**Comment by mqudsi** [comment]
```
C:\Users\Mahmoud>$ uname -a
Linux ZBook 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by justinmk** [comment]
So `if grep -q Microsoft /proc/version; ...; fi` is the shell manifestation of such a check. Other changes needed to the build files:

- Modify `third-party/cmake/GetBinaryDeps.cmake` to work on WSL
- Move or duplicate the call to `GetBinaryDep(TARGET "win32yank_...` in `third-party/CMakeLists.txt`

PR welcome.

**Comment by mqudsi** [comment]
I believe that test should work because this is my current (working) configuration:

	 if !empty(matchstr(system("uname -a"), "microsoft"))                                                              
	     let g:clipboard = {                                                                                           
	         \ 'name': 'win32yank',                                                                                    
	         \ 'copy': {                                                                                               
	         \   '+': '$home/.config/nvim/wslnoerr.sh win32yank.exe -i --crlf',                                        
	         \   '*': '$home/.config/nvim/wslnoerr.sh win32yank.exe -i --crlf',                                        
	         \   },                                                                                                    
	         \ 'paste': {                                                                                              
	         \   '+': '$home/.config/nvim/wslnoerr.sh win32yank.exe -o --lf',                                          
	         \   '*': '$home/.config/nvim/wslnoerr.sh win32yank.exe -o --lf',                                          
	         \   },                                                                                                    
	         \ 'cache_enabled': 1,                                                                                     
	         \ }                                                                                                       
	 endif

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/10812 claims that this isn't an issue? 

In any case this seems a bit roundabout and no one has stepped up.
