### ISSUE TITLE
:CheckHealth should test copy/paste to g:clipboard 

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7032]
To make `:CheckHealth` more definitive and to avoid issues such as #7020, aside from fixes like 72c38b5 that check the syntax of `g:clipboard`, perhaps `:CheckHealth` could try copying a value by executing both `g:clipboard.copy.*` and `g:clipboard.copy.+` and seeing if the output of the commands `g:clipboard.paste.*` and `g:clipboard.paste.+` return the same values?

**Comment by jamessan** [comment]
That would disturb any existing data in the clipboard, as well as (in X environments) changing the application asserting ownership for those selections. I don't think that is acceptable.

**Comment by mqudsi** [comment]
@jamessan Good point. You can easily restore the existing contents, though.

**Comment by mqudsi** [comment]
At the very least, you can test that the contents point to a valid path and are executable, even if you do not run them?

**Comment by justinmk** [comment]
I suppose it might be defensible since `:CheckHealth` is a voluntary act.

**Comment by justinmk** [comment]
`:CheckHealth` now checks a bit more structure, and gives clearer instructions about using `:h g:clipboard` as a template. I don't think we're going to take this further, `clipboard.vim` does raise an error if yank fails:

    clipboard: failed to execute: foo
