### ISSUE TITLE
executable() issues (possibly with trailing characters)

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7034]
Running `master` under WSL, I'm seeing some odd behavior for `executable()` but I'm not sure how to pin down the problem. 

```vim
let racer=system('which racer')
echo racer "/home/mqudsi/.cargo/bin/racer
echo executable(racer) "0
let racer='/home/mqudsi/.cargo/bin/racer'
echo executable(racer) "1
```

I imagine it's an issue with line endings or something else being tagged on to my variable as a result of the output of the `system` call. I'm not sure if there's a bug here or not. Should invisible characters trailing the output of a system command be included in the output of `system()`? Should `executable()` strip these out? Is it working as intended?

**Comment by jamessan** [comment]
> I imagine it's an issue with line endings or something else being tagged on to my variable as a result of the output of the system call.

Yes, the output of `system()` isn't manipulated, so you get any line endings that are output.

> Should invisible characters trailing the output of a system command be included in the output of system()?

Yes.  There's no reason for `system()` to change the output.

> Should executable() strip these out?

No.

If you want the contents of the line from `which` without line endings, then you either need to strip them or use `systemlist()`.

**Comment by mqudsi** [comment]
Thanks for clarifying.
