### ISSUE TITLE
Background color not drawn on mouse scroll or when new lines are added

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7035]
Running neovim `master` under WSL executed in a bash (well, fish) session in a cmd.exe window, I've noticed that while colors are working perfectly in neovim, background colors are not explicitly redrawn in certain cases.

Here's how my terminal looks initially, with a colorscheme (evening) loaded, `t_Co=256`, `background=dark`:

<img width="525" alt="initial view" src="https://user-images.githubusercontent.com/606923/28242928-012d1de2-697f-11e7-8b6b-2407eebf132b.png">

Scrolling down natively (ctrl+f) works fine:
<img width="525" alt="scroll with ctrl f" src="https://user-images.githubusercontent.com/606923/28242929-0a68e896-697f-11e7-9abb-5a3edded6b16.png">

But if I scroll back up with the mouse (`mouse=a`), the background is not redrawn correctly:
<img width="525" alt="scroll with mouse" src="https://user-images.githubusercontent.com/606923/28242932-23b355d4-697f-11e7-8b5d-354a00cce9bd.png">

Similarly, jump to the bottom (`G`) and it displays fine:
<img width="525" alt="jump to bottom" src="https://user-images.githubusercontent.com/606923/28242935-3acd71aa-697f-11e7-81db-2c2c04373e75.png">

But add a new line (`o<CR><CR><CR><CR><CR><CR>`) and the lines added to the buffer do not have their background drawn correctly:

<img width="525" alt="add new lines" src="https://user-images.githubusercontent.com/606923/28242936-4c18fe98-697f-11e7-8315-92681babe8ba.png">

At any point that the background color is off, ctrl+L fixes it (so it's not a `t_ut` issue or similar, bce is not wrong, it's just missing (I think)).

**Comment by justinmk** [comment]
This is usually related to a `$TERM` mismatch (the issue template requests those values for good reason).

**Comment by mqudsi** [comment]
I'm sorry, I should have included that.
I have `TERM` set to `xterm-256color` which is likely the correct value for conhost/WSL.

**Comment by justinmk** [comment]
@mqudsi do you still see this on master?

**Comment by mqudsi** [comment]
Yeah, as of v0.2.1-809-g85f3084

<img width="1148" alt="vim colors" src="https://user-images.githubusercontent.com/606923/29583501-f1bc8444-8745-11e7-9c1e-8e8ae1771f07.png">


I configured my terminal to be the same background color as my theme to work around the problem, but for this test I just used a random theme (soda).

**Comment by mqudsi** [comment]
There definitely are issues with BCE on conhost/WSL: https://github.com/Microsoft/BashOnWindows/issues/1706

But I'm not sure if that's what we're seeing here. If it's a BCE issue, would ctrl+L make everything look OK (because that's what currently happens).

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7624 defaults the built-in terminfos to disable BCE. But that only helps here if Nvim doesn't find a terminfo in your environment. If the terminfo in your environment claims BCE then Nvim will use that feature.

**Comment by justinmk** [comment]
#7624 was updated to disable BCE always, except if XTERM_VERSION env var is defined.
