### ISSUE TITLE
termguicolors broken in tmux

### ISSUE THREAD

**Issue by iredelmeier** [neovim/neovim#7041]
**This is similar to #7003 but still broken for me after #7004**

- `nvim --version`:
```
NVIM v0.2.1-566-ga76da96
```
Built from `a76da96e86cc338dd5d8ff2f6014cff68e055ce9`
- Vim (version: ) behaves differently?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 02 2017 06:40:50)
Included patches: 1-134
Modified by pi-rho
Compiled by buildd@lcy01-12
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
-clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -Wall -Wextra -g -O2 -fPIE -Wformat -Werror=format-security -fstack-protector-all -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,nodlopen -Wl,-z,nodump -Wl,-z,noexecstack -Wl,-z,noexecheap -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux   -lacl -lattr -lgpm -ldl   -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt        
```
Behaves the same as neovim
- Operating system/version: Ubuntu 16.10
- Terminal name/version: tmux
- `$TERM`: screen-256color (xterm-256color outside of tmux)

### Steps to reproduce using `nvim -u NORC`

Since `termguicolors` must be set at startup, here's a minimal vimrc:

```
set bg=dark
colorscheme desert
set termguicolors
```

### Actual behaviour

Neovim only uses colours from my terminal's colour scheme (black/white/bold)

### Expected behaviour

Colour support (256 if not truecolor)

**Comment by ExpandingMan** [comment]
This still seems broken for me as well, though I'm having a difficult time determining what commit I'm on since I am using the Ubuntu repo and `nvim --version` just returns `NVIM v0.2.1-dev` for me.

**Comment by RaitoBezarius** [comment]
Same here, adding `TERM=xterm-256color neovim` "fix" it.

**Comment by ik9999** [comment]
>Same here, adding TERM=xterm-256color neovim "fix" it.

Doesn't change anything for me. Still only white/black colors inside tmux. Tried both xterm-256color and screen-256color.

Version 0.1.7 works fine though.

**Comment by RaitoBezarius** [comment]
> Doesn't change anything for me. Still only white/black colors inside tmux. Tried both xterm-256color and screen-256color.

Hm, you're right, I was testing with vim for some reason instead of nvim. Sorry for that.

**Comment by ExpandingMan** [comment]
Believe it or not, this is *still* broken for me.  Absolutely nothing seems to fix it.  I am using tmux and for me `TERM=screen`.  Setting the `TERM` to any other value does not seem to help.

To make matters worse, I am using the Ubuntu repository and am unable to see what commit I am using, however, it did update today, so it would seem to have to be today's commit.

When I do `nvim --version` I get the following
```
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git2017073
01215+3562+26~ubuntu16.04.1/build/config -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/src -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/
build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-
4J_7ch/neovim-0.2.0ubuntu1+git201707301215+3562+26~ubuntu16.04.1/build/include
Compiled by root@lgw01-22

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by ik9999** [comment]
It is most likely a nightly build. Nightly build doesn't include this fix.
https://github.com/neovim/neovim/compare/nightly...master
You can see it here.

**Comment by justinmk** [comment]
TERM=screen is not valid ... use `TERM=screen-256color` or `TERM=tmux-256color`

**Comment by ik9999** [comment]
Colors do work in an actual release. Thanks.

**Comment by ExpandingMan** [comment]
Ok, this *finally* works for me!  Thanks all.

By the way `TERM=screen` still works.  Just so you know, there are definitely instructions for tmux out there that are instructing people to set `TERM=screen`.  Currently I am set up to use true color, so I was afraid that `screen-256color` would break that.

**Comment by jamessan** [comment]
Older tmux releases didn't have their own terminfo entry, so you _did_ have to use a variant of `TERM=screen`, of which `TERM=screen-256color` is the one to use to indicate support for more colors.  With contemporary tmux/terminfo, you should use `TERM=tmux-256color`, but `TERM=screen-256color` is still viable.

**Comment by cideM** [comment]
The only thing that worked for me was `tmux set-option -ga terminal-overrides ",xterm-256color:Tc"`. I use alacritty and `$TERM` is set to `xterm-256color`, tmux version is 2.6, neovim version 0.2.0 from pacman. None of the other proposed solutions worked for me. I could use `tmux` or `tmux -2`, set different `$TERM` values in alacritty and/or tmux, only the above mentioned line fixed the color issue *for me*
