### ISSUE TITLE
Printing `[2 q` in command prompt

### ISSUE THREAD

**Issue by wamoyo** [neovim/neovim#7049]
- `nvim --version`: NVIM v0.2.1-dev
- Vim (version: 7.4) behaves differently? Yes. Behaves normally.
- Operating system/version: Ubuntu 14.04
- Terminal name/version: Gnome Terminal 3.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:

```

### Actual behaviour

Prints [2 q to the command area at the bottom, as in photo...

![screenshot from 2017-07-18 18 50 47](https://user-images.githubusercontent.com/1170326/28343194-1ad32d00-6bea-11e7-8159-7a64d01325da.png)

### Expected behaviour

Prints just the : with a blinking cursor as usual when expecting user to enter command.

Also, it prints that `[2 q` in random places when pressing Esc, and does weird things when highlighting lines. I can't tell what's wrong. My editor seems drunk : )

**Comment by justinmk** [comment]
Looks like your terminal doesn't support cursor shaping. Newer versions of gnome-terminal do. 

We try to detect this via `VTE_VERSION`, may it's empty in your env for some reason.

To disable cursor shaping, see `:help guicursor`. It's enabled by default because it's 2017.

**Comment by wamoyo** [comment]
Woohoo! That sounds solvable : ) 
```
$ echo $VTE_VERSION
3603
```

**Comment by justinmk** [comment]
Arg, this is a regression.

**Comment by wamoyo** [comment]
Anything I can do to help?

**Comment by justinmk** [comment]
If you can try https://github.com/neovim/neovim/pull/6997 that would help.

**Comment by wamoyo** [comment]
Hmmm... Not really sure what to do. 

Put `"\x1b[%p1%d q"` in `set guicursor=`?

**Comment by stanislas-brossette** [comment]
Hello, I have observed the same bug since I updated nvim. Only a few differences on my system (terminal and VTE versions) 
nvim --version: NVIM v0.2.1-dev
Vim (version: 7.4) behaves differently? Yes. Behaves normally.
Operating system/version: Ubuntu 14.04
Terminal name/version: Gnome Terminal 3.6.2
$TERM: xterm-256color
$VTE_VERSION 3409
Have you found a fix?

**Comment by Shougo** [comment]
@stanislas-brossette You can test #6997.

**Comment by tclauzier** [comment]
Disabling cursor shapes (see command in `:help guicursor`) helped to fix it on Guake (Ubuntu 17.04).
Thanks for the tip @justinmk :)

**Comment by jumbosushi** [comment]
I've had this issue for a while since I didn't know how to google for this. Just tried `:help guicursor` disabling trick and it totally worked 🎉  Thanks for the tip!

**Comment by stianlagstad** [comment]
I also had to set `:set guicursor=` in my `.vimrc` to avoid this problem, using Ubuntu 16.04.

**Comment by justinmk** [comment]
FAQ entry for those finding this issue: https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes
