### ISSUE TITLE
Tab seems to cause error in json_decode

### ISSUE THREAD

**Issue by AGhost-7** [neovim/neovim#7058]
- Vim (version:  8.0.0056) behaves differently? works fine in normal vim
- `nvim --version`:
```
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/build/config -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/src -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-ZBoJGe/neovim-0.2.0ubuntu1+git201707120406+3519+26~ubuntu16.04.1/build/include
Compiled by root@lgw01-50

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- Operating system/version: Ubuntu 16.04.2 LTS
- Terminal name/version: gnome-terminal
- `$TERM`: "screen-256color"

### Steps to reproduce using `nvim -u NORC`

```
let str = '{"a": "	"}'
call json_decode(str)
```

### Actual behaviour
Getting error "ASCII control characters cannot be present inside string"

### Expected behaviour
parses the string

**Comment by ZyX-I** [comment]
According to https://tools.ietf.org/html/rfc7159#page-8, JSON strings may contain unescaped

1. Characters U+0020 and U+0021.
2. U+0023 to U+005B.
3. U+005D to U+10FFFF.

Tab being U+0009 is not present in any of the above intervals.

**Comment by ZyX-I** [comment]
I would suggest to open bug in Vim bug tracker instead, strictly following RFC7159 makes it more likely that your JSON will be parsed correctly by various tools then inventing your own dialect: e.g. tab in that position will not be parsed by Python built-in json package either. Parser not following the standard encourages creating data which requires specific parser and is not really interchangable: e.g. your string will not be parsed like you want by Python `json` package from standard library. Neither it will be parsed by `JSON.parse` in my browser (vivaldi, chromium-based).

**Comment by AGhost-7** [comment]
Ok thats a bit odd since I wasn't running into this issue when I was calling the github api from python. Sorry for wasting your time.

**Comment by justinmk** [comment]
From https://stackoverflow.com/a/19799355/152142 (first google hit for "json tab"):

> if json text is provided inside a Python string literal then you need double escape the tab:

    foo = '{"My_string": "Foo bar.\\t Bar foo."}'

So JSON expects `"\\t"`

**Comment by AGhost-7** [comment]
My issue right now is not with string literals, but rather when I call the github api I get a JSON response back. I'm using jobstart to call curl, which gives me a list of the response from github's api. When I try to parse the JSON, I get the error in this bug. Not sure if the reason is because the escaped tabs are being interpreted at some point, probably missing something.

**Comment by justinmk** [comment]
GitHub's API looks like it returns the right thing. Also, I don't see anything being munged by Nvim job control. Confirmed with this script:

https://gist.github.com/6c3f3a87ac5edaf15a5f565d034ce641

```vim
let g:chunks = []
function! s:JobHandler(job_id, data, event) dict
  if a:event == 'stdout'
    let str = self.shell.' stdout: '.join(a:data)
  elseif a:event == 'stderr'
    let str = self.shell.' stderr: '.join(a:data)
  else
    let str = self.shell.' exited'
  endif

  call append(line('$'), str)
  if type([]) == type(a:data)
    for line in a:data
      call add(g:chunks, line)
    endfor
  endif

endfunction
let s:callbacks = {
      \ 'on_stdout': function('s:JobHandler'),
      \ 'on_stderr': function('s:JobHandler'),
      \ 'on_exit': function('s:JobHandler')
      \ }
let job2 = jobstart(['bash', '-c', 'for i in {1..10}; do echo "\\t\\n\\r" $i!; done'], extend({'shell': 'shell 2'}, s:callbacks))
```

**Comment by ZyX-I** [comment]
@AGhost-7 You have incorrectly written `s:chunk_handler`: `a:data` may contain *incomplete* line. You must not add first line to `chunks`, append it to the last line instead.

**Comment by ZyX-I** [comment]
@AGhost-7 Basically line `abcdefg` may arrive as `['abc']` and `['defg']`. Should it be `abc\nefg` it may arrive as e.g. `['abc', '']` and `['efg']` or `['abc']`, `['', 'efg']`, or even `['ab']`, `['c', 'efg']`. What your code is doing is creating newlines where there were none.

**Comment by AGhost-7** [comment]
Oh I see, so that must explain why using `join` before decoding makes it work. Thanks for the help guys!

**Comment by ZyX-I** [comment]
@justinmk I remember this issue arised before. Is not the example of correct joining somewhere in documentation as a result? Can’t find it.

**Comment by ZyX-I** [comment]
@AGhost-7 Just start `'stdout'` and `'stderr'` lists as `['']`. Then appending will be as simple as

```VimL
let chunks[-1] .= a:data[0]
let chunks += a:data[1:]
```

**Comment by justinmk** [comment]
@ZyX-I that's an open documentation task. I never got around to it because until https://github.com/neovim/neovim/issues/7058#issuecomment-317197069 I did not see such a succinct explanation. Going to use that :)
