### ISSUE TITLE
Failed to open multibyte filename on Windows passed by command argument

### ISSUE THREAD

**Issue by yuntan** [neovim/neovim#7060]
- `nvim --version`: master 4bcc70b2b5b02e3a6048b55a4390739570db3524
- Vim (version: 8.0) behaves differently? Yes
- Operating system/version: Windows 10 (**Japanese locale**)
- Terminal name/version: powershell.exe (ConEmu)
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. Create text file as multibyte filename (ex. 日本語.txt)
2. Open 日本語.txt with vim `vim -u NORC .\日本語.txt`
3. `:echo bufname('%')` returns `.\日本語.txt`
3. Write something and save
2. Open 日本語.txt with nvim `nvim -u NORC .\日本語.txt`
1. Nothing shown in the buffer
1. `:echo bufname('%')` returns `.\<93><fa><96>{<8c><ea>.txt`

### Actual behavior
[![https://gyazo.com/4b74d937fc39f3afcbdb60f2b43eb739](https://i.gyazo.com/4b74d937fc39f3afcbdb60f2b43eb739.png)](https://gyazo.com/4b74d937fc39f3afcbdb60f2b43eb739)

### Expected behavior
vim screenshot (`encoding` not set correctly)
[![https://gyazo.com/f260d3873dd7a0af259a908465d4d73f](https://i.gyazo.com/f260d3873dd7a0af259a908465d4d73f.png)](https://gyazo.com/f260d3873dd7a0af259a908465d4d73f)

**Comment by yuntan** [comment]
Note that I can open 日本語.txt by `:e 日本語.txt` in neovim.

**Comment by justinmk** [comment]
Similar but not the same as https://github.com/neovim/neovim/issues/4889

Somewhere between receiving the argument and loading the buffer...

**Comment by yuntan** [comment]
Encoding of argument (**argv of https://github.com/neovim/neovim/blob/master/src/nvim/main.c#L221) is  cp932 on Japanese locale Windows. It should be converted to utf-8, I think. This problem may also occurs on Korean and Chinese locale Windows.

**Comment by yuntan** [comment]
vim dose this in `int get_cmd_argsW(char ***argvp)` https://github.com/vim/vim/blob/9f1f49b839fbc5d099301d5318a5e1e70dd59b7c/src/os_win32.c#L6876 called from `main` https://github.com/vim/vim/blob/9f1f49b839fbc5d099301d5318a5e1e70dd59b7c/src/main.c#L131

**Comment by justinmk** [comment]
Thanks for digging that up. On unix-likes we only support utf8 terminals, but on Windows we can't expect that.

**Comment by bfredl** [comment]
IIRC the code detecting "default" (system) encoding (which we still allow different from UTF-8) only was restored on unix, not for windows.

**Comment by yuntan** [comment]
Tried to fix the issue (not tested enough)
https://github.com/yuntan/neovim/commit/008ba42e4dd0b34a2fa23a62210c4a5dcb2daf44#diff-21cf87db76bbcab0a3b5054f99b4ef85R245

**Comment by justinmk** [comment]
Revisited in https://github.com/neovim/neovim/pull/31193
