### ISSUE TITLE
Bracketed paste isn't handled in command-line mode

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#7066]
## NOTE
I'm **assuming** it's a problem with bracketed paste, I haven't looked into the cause in any way (I'm a little busy at the moment).
Maybe the title should be something else -- I thought this the most likely to attract those knowledgeable on the area.

- `nvim --version`:
v0.2.0
- Vim (version: ) behaves differently?
8.0, yes behaves as expected.
- Operating system/version:
Arch Linux
- Terminal name/version:
XTerm(330)
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NONE
:lmap - _
:lmap _ -
:set iminsert=1
:set imsearch=-1
iTEST-THIS<esc>"*yiW
/<Shift-Insert>
```

### Actual behaviour
While `TEST_THIS` was what was written in the buffer, pressing `<Shift-Insert>` (or `<Mouse-2>`) at the search prompt inserts `TEST-THIS`, not `TEST_THIS`

n.b. same happens with `:cmap` instead 
### Expected behaviour
`TEST_THIS` should be inserted.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/4448
