### ISSUE TITLE
Weird fold fillchars display on certain UTF8 characters

### ISSUE THREAD

**Issue by minijackson** [neovim/neovim#7086]
- `nvim --version`:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"
```
- Vim (version: 8.0 (2016 Sep 12, compiled Jul 16 2017 07:38:19)) behaves differently? **Yes**
- Operating system/version: Arch Linux x86_64 (rolling release)
- Terminal name/version: st 0.7 with tmux
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set fdm=marker
:set fillchars=fold:─
i{{{
hello
}}}<ESC>
za
```

Please note that this is not happening for all non-ASCII characters. It seems to me that it's happening for characters that ends with '00':

- ─ (U+2500): **buggy**
- ━ (U+2501): works
- ┰ (U+2530): works
- ╀ (U+2540): works
- ▀ (U+2580): works
- ☀ (U+2600): **buggy**
- ☁ (U+2600): works
- ✀ (U+2700): **buggy**
- ✁ (U+2701): works
- ⤀ (U+2900): **buggy**
- ⤁ (U+2901): works

### Actual behaviour

The fold chars are all spaced between each other with sometimes wild appearances of some junk chars.

Forcing a redraw removes those junk characters.

Screen of the bug after redraw in case some people cannot reproduce this bug:
![Screen of the bug after redraw](https://user-images.githubusercontent.com/1200507/28722965-a8484dbe-73b5-11e7-9daa-9a5dbc22c799.png)

### Expected behaviour

All UTF8 characters should be treated equally ! 😠

Also, screen with the "BOX DRAWINGS HEAVY HORIZONTAL" (U+2501):

![screen with the "BOX DRAWINGS HEAVY HORIZONTAL"](https://user-images.githubusercontent.com/1200507/28723123-0fd7e444-73b6-11e7-8187-20c47c5533b2.png)

Happy to help in any way I can 😉

**Comment by ZyX-I** [comment]
Since you pointed out correlation with least significant byte and used pretty old characters, all having ambiguous width this looks like yet another 0x80 byte issue (UTF-8 representation of those U+xx00 characters end with `0x80`). The 0x80 byte is used internally for encoding some special keys like `<Up>`.

**Comment by ZyX-I** [comment]
It looks like some unmerged Vim patch: vim-8.0.0 also has the same problem.

**Comment by jamessan** [comment]
That would be [v8.0.0518](https://github.com/vim/vim/releases/tag/v8.0.0518).
