### ISSUE TITLE
build: make execinfo dependency optional?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#7099]
`execinfo.h` seems to be required since 5fc775e2e, for `log_callstack`.

This is assumed to be there on Linux, but on Alpine Linux, it requires the `libexecinfo-dev` package.

Therefore I wanted to ask / clarify if this is assumed to be a requirement now, or if `log_callstack` should be optional?
It says "Currently Linux-only." anyway, and that could be then changed to include the execinfo requirement.

**Comment by blueyed** [comment]
Still fails on Alpine Linux with `libexecinfo-dev`:
```
[100%] Linking C executable ../../bin/nvim
CMakeFiles/nvim.dir/log.c.o: In function `log_callstack':
/vim/neovim-neovim/neovim-master/src/nvim/log.c:181: undefined reference to `backtrace'
collect2: error: ld returned 1 exit status
make[3]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:4082: bin/nvim] Error 1
```

**Comment by blueyed** [comment]
execinfo.h looks like this there:

```
#ifndef _EXECINFO_H_
#define _EXECINFO_H_

#ifdef __cplusplus
extern "C" {
#endif

int     backtrace(void **, int);
char ** backtrace_symbols(void *const *, int);
void    backtrace_symbols_fd(void *const *, int, int);

#ifdef __cplusplus
}
#endif

#endif /* _EXECINFO_H_ */
```

**Comment by justinmk** [comment]
Oops, sorry. I'll add proper detection.

**Comment by blueyed** [comment]
Still not clear to me why it fails with the package being installed on Alpine?
Is `__cplusplus` not defined there?

**Comment by justinmk** [comment]
No idea, but we can use cmake `check_c_source_compiles()` to avoid the issue.
