### ISSUE TITLE
cygwin: build fails when linking

### ISSUE THREAD

**Issue by sohnryang** [neovim/neovim#7106]
- `nvim --version`: trying to build v0.2.0
- Vim (version: ) behaves differently? no comment
- Operating system/version: Windows 10 Pro x64 running Cygwin 2.881 x86
- Terminal name/version: mintty 2.7.8
- `$TERM`: xterm

It seems to fail when linking.
I generated `Makefile` in `build` directory with this command.

```
cmake -DUSE_BUNDLED_JEMALLOC=OFF -G 'Unix Makefiles' ..
```

I attached `log.txt`, which is generated with `make > log.txt 2> log.txt` command.

[log.txt](https://github.com/neovim/neovim/files/1186213/log.txt)

**Comment by justinmk** [comment]
Is this a continuation of https://github.com/neovim/neovim/issues/7079 ? Can https://github.com/neovim/neovim/issues/7079 be closed ?

**Comment by sohnryang** [comment]
It seems that "stack protector" is causing errors.

Also, It is not related with #7079.

**Comment by justinmk** [comment]
Did you get past the issue in #7079 , or what's the status of it?

**Comment by sohnryang** [comment]
I (painfully) installed dependency with hand, instead of building `.third_party` directory.

**Comment by sohnryang** [comment]
Do you think the problem can be solved by disabling stack protector?

**Comment by justinmk** [comment]
I don't think so. Looks like a more basic issue.

**Comment by sohnryang** [comment]
Then how can I manage to build neovim in cygwin?

**Comment by justinmk** [comment]
Hmm, maybe it's worth a try. https://github.com/rlaager/docsis/issues/20#issuecomment-103557491

> Then how can I manage to build neovim in cygwin?

I can't answer that any time soon.

**Comment by sohnryang** [comment]
I disabled stack protector, and no I see this error.

```
[  0%] Linking C executable ../../bin/nvim.exe
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x300): undefined reference to `setupterm'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x34f): undefined reference to `ncwrap_strfnames'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x386): undefined reference to `ncwrap_strnames'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x39a): undefined reference to `tigetstr'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x4df): undefined reference to `ncwrap_strfnames'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x4f8): undefined reference to `ncwrap_cur_term'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x50b): undefined reference to `ncwrap_cur_term'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x536): undefined reference to `ncwrap_cur_term'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x549): undefined reference to `ncwrap_cur_term'
/usr/local/lib/libtermkey.a(driver-ti.o):driver-ti.c:(.text+0x5ec): undefined reference to `setupterm'
collect2: error: ld returned 1 exit status
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3893: bin/nvim.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:2913: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by justinmk** [comment]
Those errors were also in your previous log. Maybe `sys/termios.h` needs to be included instead of `termios.h`, on cygwin.

**Comment by sohnryang** [comment]
Well, I have both `sys/termios.h` and `termios.h`, but I see these errors.

**Comment by justinmk** [comment]
Looks like there is a cygwin build of Nvim here: https://github.com/cascent/neovim-cygwin

Maybe @cascent can share some hints about changes needed to Nvim, or environment requirements?
