### ISSUE TITLE
:redrawstatus erases ex-mode completions

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7108]
I was using an async timer in the background to unnecessarily redraw the status line (I'm still not sure why the status line updates constantly without it), but in doing so I discovered that an async `:redraws` command would wipe out the completions for ex mode.

Here's an example:

```vim
let s:spinner_index = 0
let s:spinner_states = ['.', 'o', 'O', '°', 'O', 'o', '.'] 
function! StartSpinner()
    let s:spinner_timer = timer_start(250, 'SpinSpinner', {'repeat': -1})
endfunction
function! SpinSpinner(timer)
    let s:spinner_index = float2nr(fmod(s:spinner_index + 1, len(s:spinner_states)))
    :redraws
endfunction
function! SpinnerStatus()
    return s:spinner_states[s:spinner_index]
endfunction
```

If you `:call StartSpinner()` and then enter ex mode and type in, say `:h<TAB>` the completions for `h` will pop up above the prompt, but at the next 250ms interval when `:redraws` is called, the completions will disappear.

```
NVIM v0.2.1-612-g3b45f676c
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/Users/mqudsi/Random/neovim/build/config -I/Users/mqudsi/Random/neovim/src -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Users/mqudsi/Random/neovim/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/Users/mqudsi/Random/neovim/build/src/nvim/auto -I/Users/mqudsi/Random/neovim/build/include
Compiled by mqudsi@QBook.lan

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by justinmk** [comment]
The explicit purpose of `:redrawstatus` is to do what you are asking it not to do (completions appear where the statusline is). 

I suppose we could ignore it if wildmenu is showing, and see if it breaks anything.

**Comment by mqudsi** [comment]
Hahaha, go figure.

Is the status line automatically recomputed every n milliseconds anyway? I presumed I would have to manually trigger the redraw when if my text changed without an accompanying action.

**Comment by jamessan** [comment]
Sounds like upstream's https://github.com/vim/vim/commit/8603356bf41e4aa5fe1d7cffe3ee003745c167a6 might be related.
