### ISSUE TITLE
Basic authentication for headless mode (or server)

### ISSUE THREAD

**Issue by LER0ever** [neovim/neovim#7112]
I usually run a nvim headless on my server and connect with Windows GUI. **It would be really useful and secure to have a password protected --headless** or even --server/--remote.

How I use headless (in case it helps)
- On the server, Run `NVIM_LISTEN_ADDRESS=0.0.0.0:6846 nvim --headless`
- In Windows CMD, run `nvim-qt.exe --server MY_SERVER_ADRESS:6846`
- And I have a local nvim-qt able to edit remote files (and it's pretty fast)

But **anyone knowing the address can connect to my headless nvim**, that's why an authentication would be helpful.

- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently?
- Operating system/version: Manjaro Linux
- Terminal name/version: Terminator
- `$TERM`: xterm-256color

**Comment by justinmk** [comment]
You can use named pipes on windows (or domain sockets on unix) instead of TCP. And it is strongly recommended that you do so.

For TCP auth see https://github.com/neovim/neovim/issues/4443

**Comment by LER0ever** [comment]
@justinmk I went through #4443, but didn't see any clue for a Windows Neovim-Qt to connect to a Unix neovim. Can you please give a hint on how can I use neovim over unix domain sockets?

**Comment by jamessan** [comment]
> But anyone knowing the address can connect to my headless nvim, that's why an authentication would be helpful.

Personally, I would use ssh (PuTTY/plink) with port forwarding so the port isn't exposed on the remote host.  It's only exposed through the SSH connection's port forward.  Then you would set `NVIM_LISTEN_ADDRESS` to your local IP/port.
