### ISSUE TITLE
Strange characters in the cmdline (on Windows, SecureCRT)

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#7113]
- `nvim --version`: NVIM v0.2.1-618-gdc3c06e73
- Vim (version: ) behaves differently? yes
- Operating system/version: Linux airvm1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2
- Terminal name/version: SecureCRT Version 8.1.3
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

1. start nvim without plugin:

```text
nvim.appimage -u NORC
```

2. enter `:q` without press `<CR>`

```
:q
```

You will find another strange `q` appears in the cmdline, like these:

```
:qq
```

You have entered only one "q", but two "q" appeared.
![neovim2](https://user-images.githubusercontent.com/3035071/28914429-35c09202-786e-11e7-8d8f-f9102da2a07e.png)

and if you edit a while , you will find strange characters every where (which should not exist).
![neovim](https://user-images.githubusercontent.com/3035071/28914432-37e13fbe-786e-11e7-83e3-78385a8d6afd.png)

SecureCRT is a popular terminal emulator on Windows:

https://www.vandyke.com/products/securecrt/

Hope this issue could be solved.

```
nvim -u NORC
```

**Comment by justinmk** [comment]
This means the terminal doesn't support cursor shaping. Disable guicursor.

    :set guicursor=

**Comment by justinmk** [comment]
If TERM we're set correctly this issue might not occur.

**Comment by skywind3000** [comment]
That works, thanks.

**Comment by justinmk** [comment]
After a web search, I can't find anything that says what `$TERM`  SecureCRT actually implements. If it doesn't support cursor-shaping then `$TERM=xterm` is wrong. If the wrong `$TERM` is reported then things will break, theres nothing we can do about that.

If you know of a way to detect SecureCRT so that we can automatically disable cursor-shaping, please do mention it.

**Comment by skywind3000** [comment]
![securecrt](https://user-images.githubusercontent.com/3035071/29004183-109dcc9e-7af6-11e7-815d-02df6ebffc2e.png)

SecureCRT supports lots of $TERM emulation.

**Comment by justinmk** [comment]
It doesn't really "support" it if it breaks when xterm cursor shaping codes are sent.
