### ISSUE TITLE
expand("%:p") broken with files opened with relative paths on Windows

### ISSUE THREAD

**Issue by AdnoC** [neovim/neovim#7117]
- `nvim --version`: v0.2.1-25-g2e3b78d1
- Vim (version: ) behaves differently? Yes
- Operating system/version: Windows
- Terminal name/version: nvim, nvim-qt
- `$TERM`: NA

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Starting at `C:\Coding` (`cd C:\Coding`).

With a directory `exampleDir` existing at `C:\Coding\exampleDir` (`mkdir exampleDir`)

#### Open a file with a relative path:

Open neovim without any files

`neovim -u NORC`

Open a file with a path relative to the current directory

`:e .\example.txt` (the `\` is important)

##### OR

Open a file with a relative path (this happens if you use tab completion in powershell (at least for me))

`nvim -u NORC .\example.txt`

#### Then

Running `echo expand("%:p")` will output `C:\Coding\.\example.txt`.

Move to a different directory

`:cd example`

Running `echo expand("%:p")` will output `C:\Coding\exampleDir\C:\Coding\.\example.txt`

### Actual behaviour

`expand("%:p")` seems to append the name passed as an argument to the path where vim was opened.

If the current file was opened with a relative path that relative path isn't removed.

If you `:cd` to a directory that is a child of the directory where you opened neovim, `expand("%:p")` breaks even worse, outputting paths that are absolute nonsense.

If you move to a different directory it seems to concatenate the current directory to the output of what `expand("%:p")` was before you moved.

When opening a file while neovim is already opened, this bug only occurs if you use `\` as the path separator instead of `/`. Both separators causes problems when passing the file as an argument when opening neovim.

This is related to https://github.com/neovim/neovim/issues/6605, but I decided to make a new issue because the problem is more general than described in that issue.

### Expected behaviour

Output the absolute path of the current file regardless of how it was opened or whether you changed directories since opening.

In all cases in the example above it should output `C:\Coding\example.txt`.

**Comment by justinmk** [comment]
A good start would be to apply https://github.com/neovim/neovim/issues/2471#issuecomment-271193714 and fix up the tests. Then write additional test cases for the repro steps outlined in this issue.

**Comment by aignas** [comment]
I'd like to do this if no one is against.
