### ISSUE TITLE
set mouse not to 'a' by default

### ISSUE THREAD

**Issue by GodefroyClair** [neovim/neovim#7126]
- `nvim --version`: v0.2.0
- `vim --version` : 8.0.44 (same behavior)
- Operating system/version: Mac OS 10.12.5
- Terminal name/version: iTerm2 3.0.15
- `$TERM`: xterm-256

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set mouse

```

### Actual behaviour
return 'mouse='
documentation says "(default : 'a')" (and until I updated neovim & vim, this was how it was behaving...) 

### Expected behaviour
return 'mouse=a' 
...and to be able to use the mouse with nvim the way it is suppose to ;-)

Thx!

**Comment by justinmk** [comment]
Documentation has been updated, but we haven't released 0.2.1 yet.

**Comment by GodefroyClair** [comment]
Thx @justinmk . So this has changed... Can I know why ?

**Comment by justinmk** [comment]
All breaking changes are always mentioned in the "following HEAD" wiki page. https://github.com/neovim/neovim/wiki/Following-HEAD#20170403
