### ISSUE TITLE
Tutor isn't foolproof enough

### ISSUE THREAD

**Issue by legolord208** [neovim/neovim#7128]
- `nvim --version`: `NVIM v0.2.0`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Tutor
/-->
h
x
```

Another example is `dw` when at the end of the line

### Actual behaviour

It starts to delete "behind the scenes" code itself and leaks
`-->  this here {expect:this here}`

### Expected behaviour

It should disallow deletion of the arrow and other things that may leak the behind the scenes markup.

EDIT: You can also manually type `---> test {expect:test}` anywhere and it'll actually make another prompt.

**Comment by fmoralesc** [comment]
The latest changes to `:Tutor`  remove all this 'behinds the scenes stuff', this shouldn't happen anymore in master. The only thing that could still happen is that the lines get out of sync, but I'll fix that once the #5031 stuff is merged.

**Comment by justinmk** [comment]
Going to consider this closed since it is addressed on master (0.2.1) already.
