### ISSUE TITLE
Neovim resets cursor in iTerm

### ISSUE THREAD

**Issue by nikitavoloboev** [neovim/neovim#7130]
- `nvim --version`: v0.2.0
- Vim (version: ) behaves differently?
- Operating system/version: 10.11.6 
- Terminal name/version: iTerm Build 3.1.beta.5
- `$TERM`:

### Actual behaviour

Go to neovim. Don't reset my cursor.

### Expected behaviour

Go to neovim, reset the cursor.

It did not reset the cursor before. Not really sure why that happens now.

Here is a screencast of it happening : http://quick.as/R0wYSxqQ9 

Thank you for any help.

**Comment by nikitavoloboev** [comment]
`set guicursor=` fixed it

**Comment by arunvelsriram** [comment]
After setting `set guicursor=` neovim is using the same cursor config as iterm. 

I would like to use the default cursor config for neovim. neovim shouldn't be interfering with iterm's config.
