### ISSUE TITLE
error message for "echo" if "-eval" in the version

### ISSUE THREAD

**Issue by mallochine** [neovim/neovim#7131]
Easy, small usability bug I found in the normal vim 7.4 -- I was wondering if neovim fixed this or not.

### Setup
vim 7.4, Small version without GUI. -eval

### Repro
when I do something like `echo "hi"`, I don't get an error. I wasted an hour or two trying to figure out what was going on.

### Expected Behavior
I'd like to see an error message saying that echo is not supported due to "-eval" feature not compiled in. That would've saved me an hour or so.

### Further Notes
Quite possibly this behavior has already been fixed in Neovim, but not sure...

**Comment by jamessan** [comment]
Neovim always builds with all features.  I would suggest taking a look at [`:help vim-diff`](https://neovim.io/doc/user/vim_diff.html) to see all the major departures from Vim.
