### ISSUE TITLE
gx inside of a man page is broken

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#7136]
- `nvim --version`:
```
NVIM v0.2.1-661-ge13b4a21c
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170808-3469-faefp5/build/config -I/tmp/neovim-20170808-3469-faefp5/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170808-3469-faefp5/build/src/nvim/auto -I/tmp/neovim-20170808-3469-faefp5/build/include
Compiled by ahmed@thebox.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e13b4a2_1/share/nvim"
```

- Vim (version: ) behaves differently? Yes
- Operating system/version: macOS Sierra 10.12.6
- Terminal name/version: iTerm2 Build 3.1.20170801-nightly
- `$TERM`: `tmux-256color` in tmux, `xterm-256color` otherwise

### Steps to reproduce using `nvim -u NORC`

```sh
export MANPAGER="nvim -u NORC +'set ft=man' -"
```

Then open a `man` page, find a URL & in normal mode do `gx`

`:verbose map gx` returns this

```
v  gx            <Plug>NetrwBrowseXVis
        Last set from /usr/local/Cellar/neovim/HEAD-e13b4a2_1/share/nvim/runtime/plugin/netrwPlugin.vim
n  gx            <Plug>NetrwBrowseX
        Last set from /usr/local/Cellar/neovim/HEAD-e13b4a2_1/share/nvim/runtime/plugin/netrwPlugin.vim
```

If I test vim only with this `export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man' -\""` it works fine but I'm not sure if we can compare both with different commands like this.

### Actual behaviour
1- it failed & errored out
2- When I did `CTRL+C` to exit (`ESC` didn't work), it opened a random app (textedit)
3- Open a new buffer with a different file randomly I assume from history?

Here is a gif (click to enlarge)
![man](https://user-images.githubusercontent.com/63876/29091437-418da8d6-7c83-11e7-8b71-6051fcc9c866.gif)

### Expected behaviour
- To open the URL in the browser, don't open a random app or a file.

**Comment by justinmk** [comment]
'iskeyword' is `iskeyword=@,48-57,_,192-255` in both vim and nvim from a man.vim buffer, so not related to that.

   undefined variable: fname

this just looks like a netrw bug. Can you check the netrw version in both cases?

**Comment by ahmedelgabri** [comment]
@justinmk how can I check the version of netrw?

**Comment by justinmk** [comment]
`:echo g:loaded_netrwPlugin`

**Comment by ahmedelgabri** [comment]
in neovim & vim, it's `v156`

**Comment by justinmk** [comment]
Can't read the error message in your gif. That's the next step.

**Comment by ahmedelgabri** [comment]
This is the error message

```
Error detected while processing function netrw#BrowseX:
line    4:
E121: Undefined variable: fname
E15: Invalid expression: (a:remote == 0 && isdirectory(a:fname)) || (a:remote == 1 && fname =~ '/$' && fname !~ '^https\=:')
:!elinks 'https://github.com/Homebrew/brew/issues' -source > '/var/folders/v1/4hv3mbqd7yv0sypr3gbst7j80000gn/T/nviml1nLN6/1'
```

**Comment by chrisbra** [comment]
Have the same netrw version in upstream vim, don't know why it does not occur in Vim, the problem seems to exists there as well.

I have been looking into it, it seems this patch should fix it:
```patch
diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
index 76485c2f3..ef19511e5 100644
--- a/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw.vim
@@ -4970,7 +4970,7 @@ fun! netrw#BrowseX(fname,remote)
 "  call Dfunc("netrw#BrowseX(fname<".a:fname."> remote=".a:remote.")")

   " if its really just a directory, then do a "gf" instead
-  if (a:remote == 0 && isdirectory(a:fname)) || (a:remote == 1 && fname =~ '/$' && fname !~ '^https\=:')
+  if (a:remote == 0 && isdirectory(a:fname)) || (a:remote == 1 && a:fname =~ '/$' && a:fname !~ '^https\=:')
    norm! gf
 "   call Dret("netrw#BrowseX : did gf instead")
   endif
```

CC @cecamp

**Comment by cecamp** [comment]
Christian Brabandt wrote:
>
> Have the same netrw version in upstream vim, don't know why it does
> not occur in Vim, the problem seems to exists there as well.
>
> I have been looking into it, it seems this patch should fix it:
>
> diff --git a/runtime/autoload/netrw.vim b/runtime/autoload/netrw.vim
> index 76485c2f3..ef19511e5 100644
> --- a/runtime/autoload/netrw.vim
> +++ b/runtime/autoload/netrw.vim
> @@ -4970,7 +4970,7 @@ fun! netrw#BrowseX(fname,remote)
>  "  call Dfunc("netrw#BrowseX(fname<".a:fname."> remote=".a:remote.")")
>
>    " if its really just a directory, then do a "gf" instead
> - if (a:remote == 0 && isdirectory(a:fname)) || (a:remote == 1 &&
> fname =~ '/$' && fname !~ '^https\=:')
> + if (a:remote == 0 && isdirectory(a:fname)) || (a:remote == 1 &&
> a:fname =~ '/$' && a:fname !~ '^https\=:')
>     norm! gf
>  "   call Dret("netrw#BrowseX : did gf instead")
>    endif
>
> CC @cecamp <https://github.com/cecamp>
>
>
That fix was in my copy (v162m); its always best to check to see if the
development version has the problem addressed already.  You can get my
development versions from
http://www.drchip.org/astronaut/vim/index.html#NETRW.

Regards,
Chip Campbell

**Comment by chrisbra** [comment]
Ah good to know. I guess this will then be fixed eventually.

(It was easier for me to check the Vim source and fix it locally there, then going to my virtual machine, finding the source URL, download and extract it and check the source there. You might want to think about setting up a github mirror for your vim projects. It makes it easy to check the source in the browser)

**Comment by ahmedelgabri** [comment]
@chrisbra I tried your patch & it doesn't work for me, do I need to do anything else other than editing this file in my case `/usr/local/Cellar/neovim/HEAD-e13b4a2_1/share/nvim/runtime/autoload/netrw.vim`?

**Comment by justinmk** [comment]
@ahmedelgabri did you restart nvim?

**Comment by ahmedelgabri** [comment]
@justinmk Yes I did

**Comment by ahmedelgabri** [comment]
I also think this issue might be related https://github.com/vim/vim/issues/1386

**Comment by chrisbra** [comment]
did you still get the error message? you shouldn't. if gx still doesn't work, then there is another problem. Read the help at `:h netrw-debug` to figure out what is going on.

**Comment by ahmedelgabri** [comment]
I don't get an error message now, I do this message (was testing with `man brew`). Which I assume it's fine.

```
:!elinks 'https://github.com/Homebrew/brew/issues' -source > '/var/folders/v1/4hv3mbqd7yv0sypr3gbst7j80000gn/T/nvimWVs0Fj/1'
```

And then the same exact behavior in my first gif happens again, it opens text edit & then a random buffer. 

The test was done the same before with 

```zsh
export MANPAGER="nvim -u NORC +'set ft=man' -"
```
