### ISSUE TITLE
Automatically delete the swap file in the straightforward recover, save, and exit case

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7137]
Pursuant to #1455, I think a step in the right direction apart from making over the swap file confirmation dialog would be to simply show it less often, where possible.

In particular, I believe this particular case is both common enough and straightforward enough to be implemented, though I heartily welcome reasons not to do so:

1. `touch foo.bar`
2. `nvim foo.bar`
3. enter some text without saving
4. in another terminal, `kill -SIGTERM $nvim_pid`
5. `nvim foo.bar`

In this straightforward case of a swap file that post-dates the original exists on disk (so they have not diverged), attempting to open the original for editing will cause the swap file dialog to be shown. 

6. `R` to recover the swap file
7. `ZZ` to save and exit

At this point, neovim is aware that a) the swap file was recovered, b) the save being done shares a history with the swap file

My proposal is for neovim to either a) delete the swap file, or b) rename the swap file to something else so that it still exists but doesn't get loaded automatically.

Proposed behavior, continuing from the step above:

8. `nvim foo.bar`
9. _neovim loads and displays the file, without prompting to restore the swap file_

actual, current behavior continuing with the steps from above:

8. `nvim foo.bar`
9. _neovim prompts to recover the swap file which, despite it already having been dealt with_

There are many other cases for swap file management and many fringe cases that should be carefully considered, but unless I'm mighty mistaken, this should be a straightforward case that is easily addressed.

**Comment by justinmk** [comment]
Swap annoyance is IMO one of the major low-hanging fruits where usability could be improved. The other being the "Press ENTER" nonsense.

I move this and https://github.com/neovim/neovim/issues/1455 to 0.3

**Comment by mqudsi** [comment]
@justinmk you are referring to the prompt on plugin (among others) error output?

**Comment by toogley** [comment]
what about integrating https://github.com/gioele/vim-autoswap to solve this issue?

**Comment by ZyX-I** [comment]
I do not like the idea of autoswap, specifically two out of three automatic choices: first, it is the context switching which is not only what I would not want, but that is also *highly* unreliable: not only I do not bother to set up window titles, but it is also not going to handle e.g. yakuke tabs well. And has no code for Windows as well. And also definitily could not switch to *backgrounded* Vim’s which with my workflow is the most likely reason for me to press `q` on the prompt. And will not deal with the fact that I have some Vim’s inside tmux and some not. Second, I sometimes really do want to edit one file from two instances at once and typing `e` is far easier then getting rid of readonlyness.

**Comment by justinmk** [comment]
closed by https://github.com/neovim/neovim/pull/9956

**Comment by mqudsi** [comment]
@samhaaf-dar ”closed by xxxx” means that the issue has been addressed and is resolved by the patch in the linked PR. In other words, this issue was only closed because it was fixed (although in other cases “closed by xxx” can also be because it was obviated). If you have an up to date version of Neovim, you shouldn’t be seeing this problem and shouldn’t be needing a work around for the original problem described in my first post.
