### ISSUE TITLE
neovim + konsole = blinking cursor

### ISSUE THREAD

**Issue by gaydenko** [neovim/neovim#7138]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently? 8.0.722
- Operating system/version: Up to date Manjaro Linux
- Terminal name/version: Konsole 17.04.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Start nvim -u NORC

### Actual behaviour

Cursor is blinking

### Expected behaviour

Cursor is steady.

I have tried `set guicursor=` and `set guicursor=n:blinkon0` with the same result, that is nothing changed.

Working (that is free from the blinking problem) variants are:

neovim + xterm
vim + konsole (or any other terminal I have tried)

**Comment by justinmk** [comment]
This is a known bug in 0.2.0, confusingly, `set guicursor=n:blinkon1` is needed instead of `set guicursor=n:blinkon0`. :(

It's been fixed in master already.

**Comment by gaydenko** [comment]
@justinmk Thanks for the clarification! - the workaround does work.

**Comment by JackHasaKeyboard** [comment]
@justinmk Only stops it from blinking in normal mode, still blinks in insert and command-line mode.
