### ISSUE TITLE
system() outputs some guicursor stuff

### ISSUE THREAD

**Issue by rstacruz** [neovim/neovim#7146]
- `nvim --version`: v0.2.0
- Vim (version: 8.0) behaves differently? yes, it works in vim
- Operating system/version: Mac OS Sierra
- Terminal name/version: iTerm2 3.1.beta6 + tmux 2.5 (no config)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Use `system()`.

```
nvim -u NORC
:echo system("bash -c echo")
```

### Actual behaviour

The result of `system()` has some _Ptmux_ stuff.

```
^[Ptmux;^[^[]1337;CursorShape=0^G^[\

Press ENTER or type command to continue
```

### Expected behaviour

Vim doesn't show the Ptmux part:

```
Press ENTER or type command to continue
```

- Setting `set guicursor=` has no effect.
- This does not happen when using iTerm2 without tmux.

**Comment by rstacruz** [comment]
GIF in action:

![system](https://user-images.githubusercontent.com/74385/29168335-04b2681e-7e01-11e7-91c8-b2b3dc5b8d37.gif)

**Comment by DarkDefender** [comment]
I think this is related to #7067.

Are you using fish as your shell by any chance?

**Comment by justinmk** [comment]
@DarkDefender thanks for mentioning that, I thought this sounded familiar. Updated the title for #7067
