### ISSUE TITLE
gq indents html text inappropriately

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7148]
- `nvim --version`: v0.2.1-639-g5cc4ea3
- Vim (version: ) behaves differently? yes
- Operating system/version: WSL
- Terminal name/version: conhost
- `$TERM`: xterm-256color

Given this document fragment saved as `test.html`:

```html
<p>Until next time,</p>

<p>The NeoSmart Team</p> <small>You signed up for these emails when you
downloaded one of our free utilities - probably EasyBCD. If you prefer
not to receive this and other computer-related tips, advice, or
information, <a href="[unsubscribe]">please click here to remove
your name and email from our list</a>.</small></div>
</div> </body> </html>
```

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.html
:set tw=80
VGgq
```

### Actual behaviour

The text in the buffer becomes

```html
<p>Until next time,</p>

<p>The NeoSmart Team</p> <small>You signed up for these emails when you
        downloaded one of our free utilities - probably EasyBCD. If you prefer
        not to receive this and other computer-related tips, advice, or
                information, <a href="[unsubscribe]">please click here to remove
                        your name and email from our list</a>.</small></div>
</div> </body> </html>
```

### Expected behaviour

Under vim, the same action results in the following:

```html
<p>Until next time,</p>

<p>The NeoSmart Team</p> <small>You signed up for these emails when you
downloaded one of our free utilities - probably EasyBCD. If you prefer not to
receive this and other computer-related tips, advice, or information, <a
href="[unsubscribe]">please click here to remove your name and email from our
list</a>.</small></div> </div> </body> </html>                           
```

**Comment by mhinz** [comment]
It's a runtime issue: https://github.com/vim/vim/commit/3ec574f2b549f456f664f689d6da36dc5719aeb9#diff-c5802b9fe6ca7e175ecf7f5f3bea690e

**Comment by mhinz** [comment]
It's the same in Vim if you use `vim -Nu NONE -c 'filetype indent on | setf html' test.html`. It's just that Neovim enables `filetype plugin indent on` by default (unless `-u NONE` is used).

When `:filetype` shows `indent` as on, Vim will source `$VIMRUNTIME/indent/html.vim` on `:set ft=html`. That file gets used on `gq` from now on.

If it doesn't get sourced, `gq` uses hardcoded formatting (since `'formatexpr`' is empty and `'formatoptions'` doesn't matter in this case).

**Comment by mqudsi** [comment]
Ok, does that mean that there is a bug in the HTML indent file, then?

It's not just a matter of indenting vs not indenting, it's sometimes increasing the indent level on a new line without the presence of a new tag (but not always).

**Comment by jamessan** [comment]
Looks like it, but that should be discussed with the maintainer of the indent file.

**Comment by mqudsi** [comment]
@jamessan shouldn't bugs in files that ship with neovim have open tickets in the neovim repo, even if resolution is upstream?

**Comment by jamessan** [comment]
Why? It's not something we're specifically going to address, other than merging the eventual runtime patch from Vim.  Keeping it open is just overhead for us.  There's enough other things to deal with, without also managing issues for something we're not working on.

**Comment by mqudsi** [comment]
Well, at the end of the day it affects neovim users. If, for instance, the maintainer of `foo` indent files that are used by pretty much all of neovim's base has a really screwed up file and isn't fixing the bug, then neovim either patches it in their distribution of `foo`'s syntax file or searches for an alternative indent file provider for `foo`.

Regardless of the resolution, it's something that by virtue of including in the default distribution is to some extent or the other, "neovim's problem" and should have an eye kept on the issue, if only so you could point other users to the issue in question and say "tracked here."

At least that's how I've seen it done in other projects that are suffering from upstream bugs. I mean, the cognitive overhead of an open issue tagged "upstream-bug" is pretty minimal (esp. when we're not talking about a zero-inbox approach to issue management).

**Comment by justinmk** [comment]
Fair enough, we have `bug-vim` for "upstream bug". Leaving this open in `unplanned` milestone.

**Comment by mqudsi** [comment]
Thank you for reconsidering. Go neovim!

**Comment by mhinz** [comment]
I don't see anyone in here who has reported this to Vim. Unless that's the case, it will never get fixed.

If it gets reported, I'll gladly reopen this.

**Comment by mqudsi** [comment]
The HTML indent file is maintained by Brad. I reported it here: https://github.com/vim/vim/issues/8553
