### ISSUE TITLE
Emoji modifiers are broken

### ISSUE THREAD

**Issue by BrandonMathis** [neovim/neovim#7151]
- `nvim --version`: v0.2.0
- OSX 10.11.6
- iTerm 3.0.15
- `$TERM`: xterm-256color-italic

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
👍🏼
💪🏼
```

### Actual behaviour
![screen shot 2017-08-11 at 10 47 28 am](https://user-images.githubusercontent.com/362269/29218430-cbd1b27a-7e82-11e7-8559-93b6ea900bc9.png)

### Expected behaviour
![screen shot 2017-08-11 at 10 37 03 am](https://user-images.githubusercontent.com/362269/29218433-ccd2149e-7e82-11e7-9510-149e8f44dce6.png)

Emoji's are suddenly displaying odd. I'm not sure if this is a UTF-8 issue or issue specific to emoji but neovim seems to insist to display both characters that make up an emoji. When there is only one character (ie:👖) then neovim will display emptyspace after the emoji.

**Comment by justinmk** [comment]
> Emoji's are suddenly displaying odd

"Sudden" compared to what previous circumstances ?

**Comment by jamessan** [comment]
> Maybe [this](http://blog.mzikmund.com/2017/01/working-with-emoji-skin-tones-in-apps/) could help?

I don't think that's actually relevant for (n)vim.  That's describing how to produce the right byte sequence when a user wants to apply a skin tone to an emoji.

We already have that byte sequence in the buffer.  The issue is that the emoji isn't being displayed as expected.

Is iTerm able to display that emoji independently of nvim (e.g., by running `cat emoji.txt`)?

**Comment by jspieker** [comment]
[Vim can](http://i.imgur.com/DOkAQnf.jpg) but [cat can't](http://i.imgur.com/sv2wYPp.png).

**Comment by bfredl** [comment]
Is that just not the shell highlighting a missing final newline?

**Comment by jspieker** [comment]
> Is that just not the shell highlighting a missing final newline?

Whoops, yeah you're right. I had assumed it was a leftover from my custom font.

**Comment by justinmk** [comment]
What about older versions of Vim 8? Maybe someone can narrow it down to see which vim patch solved the issue?

**Comment by zeorin** [comment]
Is there any progress on this issue? I'm using the "Warning Sign" emoji as a warning indicator for ALE, and isn't rendered correctly:

![2018-06-06-150954_2271x1214_scrot](https://user-images.githubusercontent.com/1187078/41040084-b1c09306-699b-11e8-8bfb-5e5c92baa62d.png)

Once I move the cursor over the lines in question, the spacing returns to normal:

![2018-06-06-151650_2049x1485_scrot](https://user-images.githubusercontent.com/1187078/41040429-abb31a1e-699c-11e8-8fe4-689b343c36cb.png)

The spacing is off again if I change buffers and then back again, resize the terminal window, or suspend (CTRL+Z) and then resume (`fg`) the neovim process.

Unicode sequence: `U+26A0️ U+FE0F`. [`U+FE0F`](https://codepoints.net/U+FE0F) is supposed to not have any width, and change the preceding Unicode glyph to an emoji equivalent if there is one.

The "Police Cars Revolving Light" emoji that I use for errors is just one code point (U+1F6A8) and doesn't seem to have this problem.

**Comment by dkasak** [comment]
Yeah, it seems that none of the emojis requiring `U+FE0F` for their fully-qualified variant work correctly.

Some other examples are 

- ☁️
- ❤️
- ☂️
- ✏️
- ✂️
- ☎️
- ✈️

**Comment by yatli** [comment]
I have compiled a list of all emoji codepoints as of 12.0, here:
https://github.com/yatli/fvim/blob/master/emoji.tsv

It seems that the neovim is sticking to an older standard (perhaps 9.0?), and thus the following problems:


1. not packing the compositions into a single cell in the grid.

my frontend (fvim) display a composition as multiple cells, for example, `👨‍💻` is placed in 3 cells `U+1F468 U+200D U+1F4BB`:
![image](https://user-images.githubusercontent.com/20684720/57906325-24494380-78ac-11e9-807a-e0eb3785af90.png)


2. interpreting a wide emoji as narrow.

for example @dkasak mentioned ❤️, is shown in fvim as:
![image](https://user-images.githubusercontent.com/20684720/57906443-93269c80-78ac-11e9-9f1e-49a401c28def.png)
..where the next character is placed in the cell right after the emoji.


FYI I've also processed the table into a table for emoji lookup, here:
https://github.com/yatli/fvim/blob/b0d10340e9d87887fa9d0bc9150e0c12761087be/wcwidth.fs#L302

**Comment by bfredl** [comment]
@yatli 

> It seems that the neovim is sticking to an older standard (perhaps 9.0? according to some fragments of code and comments I saw), 

The unicode tables are up to date, but nvim doesn't understand ZWJ (200d), which can turn two non-composing chars into a single grapheme. It would be possible to replace nvim's internal algorithm with the one from libutf8proc (which will be a dependency due to tree-sitter anyway), though it will require a bit of work, and could introduce regressions/bugs.

> not packing the compositions into a single cell in the grid.

Is 'emoji' option set?

**Comment by yatli** [comment]
yes `emoji` is set (though turning it off does not cause neovim to behave differently)

**Comment by dkasak** [comment]
The problematic emojis I listed do not appear to be to related to ZWJ since it is not used there. This is how the emojis in my list above render for me in neovim (inside kitty, which does not have problems with U+FE0F in general):

Cursor before emoji:
![Cursor before emoji](https://i.imgur.com/oMESwo3.png)

Cursor after emoji:
![Cursor after emoji](https://i.imgur.com/1pCY3gt.png)

**Comment by yatli** [comment]
@dkasak yes, can confirm that. These glyphs are regarded as "narrow" by neovim.

**Comment by bfredl** [comment]
Weird, 0x2764 is part of `emoji-data.txt` (and `intable(emoji_all, ARRAY_SIZE(emoji_all), 0x2764)` return true). It it supposed to become wide by either 'ambiwith' or 'emoji' (depending on if it was "ambiguous" or "narrow" initially).

**Comment by bfredl** [comment]
Only codepoints above 0x1F000 is considered to be emoji for the 'emoji' option apparently. https://github.com/neovim/neovim/blob/master/src/nvim/generators/gen_unicode_tables.lua#L253 . 
Probably 0xFE0F modifier should make it double-width, but some refactors will be needed for nvim to consider composing chars to affect width.

**Comment by yatli** [comment]
@bfredl is there a case that  ❤️(0x2764) alone without 0xFE0F makes it non-double-width? If not, I think it's better to just pick it from the lookup table, and not use 0xFE0F as an indicator, right?

**Comment by bfredl** [comment]
I think 0xFE0F means that the preceding character is considered to be a text char on its own, and only with the modifier it is an emoji.

**Comment by yatli** [comment]
I just looked up the unicode standard -- it is conflicting somehow.
0x2764 is listed as a valid codepoint, here: http://www.unicode.org/emoji/charts-12.0/emoji-list.html#2764
0x2764 has a mandatory VS, here: https://www.unicode.org/Public/emoji/12.0/emoji-sequences.txt

😕

**Comment by bfredl** [comment]
In my browser ❤ alone is a black heart, only with modifier it becomes a big red heart ❤️.  If I understand https://www.unicode.org/emoji/charts-12.0/text-style.html (bottom left) correctly these chars are only considered emoji (so that emoji width applies) with the modifier sequence.

**Comment by dkasak** [comment]
bfredl is correct. `U+2764` is not a [fully-qualified emoji](http://unicode.org/reports/tr51/#def_fully_qualified_emoji) on its own. It needs to be followed by one of two presentation selectors, either `U+FE0F` to select the emoji variant or `U+FE0E` to select the text variant. See the [Presentation Style](http://unicode.org/reports/tr51/#Presentation_Style) of TR51.

**Comment by yatli** [comment]
Understood. :)
In this case we’d need a slightly more complex mechanism.

**Comment by yatli** [comment]
TR51 states that, a base codepoint without a presentation selector will fall back to its default presentation:
![image](https://user-images.githubusercontent.com/20684720/57966566-5c24b980-7986-11e9-98d1-4580571138dc.png)

0x2764 indeed has text presentation as its default fallback (from [wikipedia](https://en.wikipedia.org/wiki/Emoji)):
![image](https://user-images.githubusercontent.com/20684720/57966647-73b07200-7987-11e9-84f2-c07768810fd0.png)


On Windows10, even without the selector, 0x2764 should be double-width.
Here's a few samples (VSCode, Notepad, MS World, Chromium in a row):
![image](https://user-images.githubusercontent.com/20684720/57966618-3350f400-7987-11e9-9e57-d991c619f0e3.png)


@bfredl does "❤" appear wide on your browser?

**Comment by bfredl** [comment]
@yatli In firefox it is narrow black heart. In chromium (desktop and mobile) it is a narrow red heart. The modifier is always needed to make it double width.

> On Windows10, even without the selector, 0x2764 should be double-width.

What does this even mean?  Terminal programs can run on one platform and be displayed on another over ssh, so they have to follow some kind of standard. Arbitrarily changing unicode semantics on each platform doesn't sound very useful.

**Comment by yatli** [comment]
I think it means that there is no standard specifying that the default presentation is narrow.

**Comment by yatli** [comment]
To understand this problem better I'll check how it behaves on other platforms.

**Comment by bfredl** [comment]
@yatli In a variable width font the width can be whatever. The relevant question for us is how the char is suppose to be behave in a _monospace_ font, where Unicode should classify it as either singe, double or ambigous width.

**Comment by yatli** [comment]
Yes I agree the misalignment in the screenshot is not that helpful for the conversation :)  
Both instances use the same monospace font `Iosevka Term Slab` though, just FYI

Searching through the threads from the unicode maillist I come across [this piece of information](https://unicode.org/pipermail/unicode/2018-March/006314.html):

>I think that fixed-width rendering properties for East-Asian characters was
>meant only for rendering letters or symbols as plain-text, not for the new
>rendering with emoji styles.
>If the symbols are rendered as emojis, these properties don't apply at all,
>the Emojis style overrides that completely.
>
>Note that when characters have both styles (notably the oldest dingbats),
>there's a variant selector available to select the emoji (EAW ignored)
>style vs. plain-text style (where EAW is suitable). Characters that have
>only Emoji styles and no selectors should not have any EAW property (only
>the default one applicable to all Emojis).
>
>
>2018-03-05 8:58 GMT+01:00 Oren Watson via Unicode <unicode at unicode.org>:
>
>> EAW is used in fixed-width settings to distinguish characters that should
>> take up one space versus two. I would also prefer that all these be
>> considered wide, since otherwise it causes format problems in these
>> settigns.
>> (unfortunately fixed-width appear to be largley ignored by unicode... ��)
>>
>> On Sun, Mar 4, 2018 at 10:54 PM, fantasai via Unicode <unicode at unicode.org
>> > wrote:
>>
>>> Why are the new emoji like U+1F600 Grinning Face EAW=Wide
>>> when other dingbats like U+263A Smiling Face are EAW=Neutral?
>>> This is making it difficult to have consistent formatting
>>> across emoticons. Also, emoji aren't really CJK context only
>>> now, are they.
>>>
>>> https://unicode.org/cldr/utility/character.jsp?a=1F600&B1=Show
>>> https://unicode.org/cldr/utility/character.jsp?a=263A&B1=Show
>>>
>>> ~fantasai
>>>
>>
>>
>>

---------------------

So, it appears that the width of a character is decided by the property "EAW" (east-asian width) attached to each property.
If selector 0xF is used, EAW should be ignored completely (even width=2 wouldn't be safe, but I guess it mostly works).
If the desired presentation is text, then EAW should be considered. For most emoji codepoints that don't explicitly define this, it backs off to "Neutral".

The possible values for EAW are:

- Ambiguous (A)
- Fullwidth (F)
- Halfwidth (H)
- Narrow (Na)
- Neutral (N)
- Wide (W)

So it's not "narrow" either.

**Comment by bfredl** [comment]
according to https://unicode.org/reports/tr11/ "Neutral" is closer to Narrow. Quoting:


> ED7. Neutral (Not East Asian): All other characters. Neutral characters do not occur in legacy East Asian character sets. By extension, they also do not occur in East Asian typography. For example, there is no traditional Japanese way of typesetting Devanagari. Canonical equivalents of narrow and neutral characters may not themselves be narrow or neutral respectively. For example, U+00C5 Å LATIN CAPITAL LETTER A WITH RING ABOVE is Neutral, but its decomposition starts with a Narrow character.

 >   Strictly speaking, it makes no sense to talk of narrow and wide for neutral characters, but because for all practical purposes they behave like Na, they are treated as narrow characters (the same as Na) under the recommendations below.


Å (the letter, not ångström) is always single-width in monospace fonts.

**Comment by bfredl** [comment]
> @bfredl does this make sense for you?

Yes. 

> Fully-qualified emojis in emoji presentation, and those default to emoji presentation, are most probably wide (depending on Emoji style specifications)

So when 'emoji' option is set, 0x2764 0xFE0F should become wide. But not 0x2764 alone.

**Comment by yatli** [comment]
Cool. :)
> So when 'emoji' option is set, 0x2764 0xFE0F should become wide. But not 0x2764 alone.
Definitely, because 0x2764 defaults to (TEXT, Neutral).

However, for 0x231B and 0x1F004, they default to (Emoji, EAW_Ignored) so they're probably wide.

**Comment by yatli** [comment]
Here are two tables covering the cases I mention:

1. [These codepoints defaults to wide, in text mode](https://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:East_Asian_Width=Wide:])
2. [These codepoints defaults to Emoji, so if 0xFE0E is not used, it should be wide, and if 0xFE0E is used, we should look up 1)

**Comment by bfredl** [comment]
started sketching implementation https://github.com/neovim/neovim/pull/10026

**Comment by justinmk** [comment]
Explication of extended grapheme clusters: https://hsivonen.fi/string-length/

Example from that article returns `11` currently, but it should return `2`.

    :echo strdisplaywidth("🤦🏼‍♂️")

**Comment by blueyed** [comment]
11 corresponds to what you are seeing when pasting it (also in Vim): `:echo strdisplaywidth("🤦🏼<200d>♂️")`

**Comment by zapling** [comment]
Not sure if related but I have a similar issue when I open an file with certain emojis. I'm using kitty terminal and reported the issue there, as it was "working" in xfce4-terminal, although it looks weird in that one too.

xfce4-terminal
![Screenshot_2020-07-01_13-02-37](https://user-images.githubusercontent.com/15123086/86248999-f5288b00-bbae-11ea-84c6-48827caddf82.png)

kitty
![Screenshot_2020-07-01_13-03-02](https://user-images.githubusercontent.com/15123086/86248843-ba265780-bbae-11ea-86bb-fa4bb7f951a0.png)

Weird thing is it looks OK when running `neovim -u NONE`

![Screenshot_2020-07-01_15-26-09](https://user-images.githubusercontent.com/15123086/86249315-6a945b80-bbaf-11ea-9c8f-02d2695ca0c5.png)
I tracked it down to a combination of `colorcolumn` and `colorscheme gruvbox`. If I disable both the `colorscheme` and `colorcolumn` it renders correctly. I'm pretty lost on what is wrong.

![Screenshot_2020-07-01_15-31-21](https://user-images.githubusercontent.com/15123086/86249716-f27a6580-bbaf-11ea-97da-3ff1d43f3549.png)

**Comment by subnut** [comment]
@justinmk It's been almost 3 years since this issue opened. Any ETA? Anyone working on this?

**Comment by christianparpart** [comment]
In order to get an external contribution rolling: Dear neovim developers, what code paths are needed to be touched to attempt working on that. I'd say I've enough experience with unicode and terminals (working from the other side of life), that I'd see if I can give it a try at least.

**Comment by KillTheMule** [comment]
> 
> 
> In order to get an external contribution rolling: Dear neovim developers, what code paths are needed to be touched to attempt working on that. I'd say I've enough experience with unicode and terminals (working from the other side of life), that I'd see if I can give it a try at least.

Did you see https://github.com/neovim/neovim/issues/7151#issuecomment-493676396? That should give some ideas... otherwise I suggest joining the gitter chat where the devs will surely try to get you started.

**Comment by mb720** [comment]
@zapling: I have a similar issue with kitty 0.19.1 and can easily reproduce it like this:

  1. `nvim -u NONE emoji_problem`: Everything is rendered fine at the moment. The contents of `emoji_problem` are below.
  2. `:set cursorline`
  3. Move the cursor up and down to see lines duplicated.

[Here's a GIF](https://i.imgur.com/d8gHdZ7.gif) demonstrating these three steps and the visual glitch.

The file `emoji_problem` has this content:

    This is the first line ♟️
    Here comes the second line
    Now the third line

I'm on Arch Linux 5.9.2 running Sway 1.5.1.

Some observations:

  * As mentioned before, not all emojis cause this. 🐧 works fine, for example. The [chess pawn emoji](https://emojipedia.org/chess-pawn/) uses codepoint U+FE0F.
  * I could reproduce this without starting Sway: Also in the default Linux terminal (where `echo $TERM` produces `linux`) Neovim doesn't render the lines of `emoji_problem` correctly.
  * Vim 8.2 with `:set cursorline` renders the file correctly.

**Comment by zapling** [comment]
@mb720 I think the problem is that neovim doesn't render some emojis as wide etc when it should. I have noticed a bunch of weird of issues when having emojis in the buffer. I had a look at the neovim code, but couldn't not figure it out as I'm not that familiar with C (nor neovim codebase). Unfortunately this seems to be low in the list for neovim maintainers (based on the lack of updates).

I moved emojis to a separate file so I wouldn't need to have that buffer open so often. You can fix the rendering temporary with `ctrl + l `.

**Comment by benwoodward** [comment]
I'm experiencing weird issues with 🕵️‍♀️. It displays as `🕵️<200d>♀️`, and typing has the effect of moving the cursor + any typed characters backwards. Also, movement keys in normal mode will duplicate the current character backwards. It's not updating the buffer, it's just rendering characters with an incorrect position offset on the screen.

![neovim-emoji-issue](https://user-images.githubusercontent.com/1472981/100527066-dac50d00-3233-11eb-99da-e8585c738543.gif)

**Comment by Rich-YoYo** [comment]
Just to report that this problem (ie - a space being rendered after the character) is also occurring with the character '↗' (U+2197) and the other 3 'slanting' arrows in the group. It doesn't happen with the horizontal/vertical characters (eg, '↑' (U+2191)) though.

Problem does not occur with vim; only nvim. NVIM v0.4.4

**Comment by Rich-YoYo** [comment]
Just spotted after posting the above, that my browser is showing the slanting arrow with a blue background, and the vertical arrow as plain. This suggests that the browser is treating these differently too

**Comment by glyh** [comment]
I've seen emojis turned into something like `ï<8b><8b>`, is that the same as this issue?

BTW, I found both vim and neovim has issue on the displaying, but vi can perfectly display emojis.

**Comment by zeertzjq** [comment]
> I've seen emojis turned into something like `ï<8b><8b>`, is that the same as this issue?

I cannot reproduce, and this is unlikely to be the same issue.

**Comment by kovasap** [comment]
I'm having this issue as well.  This manifested for me when editing a markdown table, which made it very confusing to understand which lines were where:

```

| Tool | Specialty      | Data Entry | Data Export | Analysis | DB Comparison | Recommendations |
|------------------------------------------|----------------|------------|-------------|----------|---------------|-----------------|
| t    | Food           | 🛠️         | 🛠️          |  ✔️               | ✔️             | 🚫              |
| t    | Food           | 🛠️         | 🛠️          | ✔️ ✔️               | ✔️             | 🚫              |
| t    | Food           | 🛠️         | 🛠️          | ✔️               | ✔️                          | 🚫              |
| t    | Food           | 🛠️         | 🛠️          | ✔️ ✔️               | ✔️             | 🚫              |

```

**Comment by bonsairobo** [comment]
This issue has been open for a long time. Any plans for a fix?

**Comment by clason** [comment]
PR welcome.

**Comment by bonsairobo** [comment]
@clason OK I can start from nothing and try to fix it, but would appreciate if a maintainer could offload any context.

**Comment by clason** [comment]
It doesn't add _anything_ useful; it's just a complaint ("why isn't this fixed yet?!").

**Comment by bonsairobo** [comment]
@clason I was not complaining, just stating a fact. Sorry if it came off poorly. I just want to help, but I'm feeling like you're shutting me down just for posting here and asking about ideas for a fix.

**Comment by tmillr** [comment]
> I was not complaining, just stating a fact. Sorry if it came off poorly. I just want to help, but I'm feeling like you're shutting me down just for posting here and asking about ideas for a fix.

![first-time-james-franco](https://github.com/neovim/neovim/assets/45028928/e815fd9e-0c9e-4099-afd9-379fe66f15ce)

**Comment by erf** [comment]
Not really familiar with the Neovim codebase but i'd thought i'd chip on this as I've been working on my own [editor](https://github.com/erf/vid) which focuses on correct rendering and cursor movement with regards to Emojis / grapheme clusters. Perhaps i could share some light on some challenges regarding this issue.

One thing i'm thinking in regards of Neovim is that text and especially characters should be both represented and written to the terminal in terms of grapheme clusters or user-perceived character. This is probably a big undertaking / refactor of legacy code.

Another thing is that cursor movement should consider the emoji width based on the latest Unicode standard and the [EastAsianWidth](https://www.unicode.org/Public/15.0.0/ucd/EastAsianWidth.txt), emoji presentation style etc.. there exists [libraries](https://github.com/JuliaStrings/utf8proc) that helps with this.

Also Neovim should check the terminal for [mode 2027](https://github.com/contour-terminal/terminal-unicode-core) to determine how to render emoji characters.

For a nice summary of grapheme clusters, emojis and terminals you could check out [this blog entry](https://mitchellh.com/writing/grapheme-clusters-in-terminals) written by Mitchell Hashimoto who currently works on the Ghostty terminal (currently in beta).

I would love to see Neovim kept up to date with the latest Unicode / terminal standards!

**Comment by bfredl** [comment]
looking into on integrating utf8proc grapheme implementation to support more emoji clusters: #30014
