### ISSUE TITLE
Erroneous characters appearing at prompts and cursor

### ISSUE THREAD

**Issue by RomanHargrave** [neovim/neovim#7155]
```
NVIM v0.2.1-675-gcb914bfd3
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/local/src/neovim_stuff/neovim/build_deb/config -I/usr/local/src/neovim_stuff/neovim/src -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/local/src/neovim_stuff/neovim/.deps/usr/include -I/usr/include -I/usr/local/src/neovim_stuff/neovim/build_deb/src/nvim/auto -I/usr/local/src/neovim_stuff/neovim/build_deb/include
Compiled by roman@SuperTurboAirConditioner

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/usr/local/src/neovim_stuff/neovim/_package/neovim/usr/share/nvim"
```

- Operating system/version: Debian testing
- Terminal name/version: Konsole 16.12.0
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

`nvim -u NORC` and open any prompt (search, command, etc...)

### Actual behaviour

Displays ghost `q` following prompt character, e.g.:

`:q` when empty, or `:q<what you type>`

The `q` is visual only, and does not effect input.

In search mode, the `q` overwites the first character of the expression, but does not effect the search.

Entering insert mode, q is also displayed (not written) at the cursor.

### Expected behaviour

`:` when empty, or `:<what you type>`

**Comment by RomanHargrave** [comment]
I [recorded](https://www.youtube.com/watch?v=aexqd8n3WGo) a session with the bug. Notice the command line in the lower left.

**Comment by RomanHargrave** [comment]
This appears to be an issue with the terminal emulator and the latest version of neovim. I tried recording an asciinema session, but the issue was not visible.

**Comment by RomanHargrave** [comment]
Starting neovim in an environment configured such that `os_term_is_nice()` returns false eliminates the issue.

It's likely the case that a new control sequence introduced at some point between `g06ed7a18` and `gcb914bfd3` is causing the issue.

**Comment by justinmk** [comment]
But `os_term_is_nice` isn't called anywhere, on master ...

**Comment by RomanHargrave** [comment]
Then something else that checks `KONSOLE_` and `TERM` environment variables has an effect on behaviour.

**Comment by justinmk** [comment]
can you confirm that https://github.com/neovim/neovim/pull/6997 fixes it for you ?

**Comment by RomanHargrave** [comment]
Yes @justinmk
