### ISSUE TITLE
terminal buffer enters insert mode if clicked on from insert mode buffer

### ISSUE THREAD

**Issue by kennylevinsen** [neovim/neovim#7164]
- `nvim --version`: 0.2.0 (release)
- Vim (version: ) behaves differently? N/A (no term support in Vim unless something happened while I wasn't looking)
- Operating system/version: Arch Linux 14/08/2017
- Terminal name/version: GNOME Terminal 3.20.2 (different host)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set mouse=a
:vsp term://bash
<C-W>l
i
"click in the terminal buffer with your mouse
```

### Actual behaviour
Terminal buffer is selected and in insert mode. I often end up trying to write immediately, leading to an ocean of not modifiable errors. Exiting insert mode and reentering brings you to the proper terminal mode.

### Expected behaviour
Terminal buffer enters terminal mode *or* normal mode. It should never enter insert mode.

**Comment by ZyX-I** [comment]
@kennylevinsen Vim does support `:terminal` now, though Bram again is writing entirely his own implementation. And, as usual, it is a feature which needs to be enabled at compile time.

**Comment by kennylevinsen** [comment]
@ZyX-I Ah, fair enough. It's been quite a while since I bothered following what Bram is up to. I doubt that a comparison is necessary for this issue. :)

**Comment by ZyX-I** [comment]
@kennylevinsen Actually, vim-8.0.946 has the same behaviour. Maybe even the same method of fixing, Bram did check our implementation after all.

**Comment by kennylevinsen** [comment]
In that case I should have debugged it earlier so that the bug wasn't ported to Vim! I have been hitting this bug *forever*, but was always too busy to figure out exactly what combination of button pushing caused the peculiar state.

Thanks for reporting the simplified version to vim/vim.

**Comment by asmodeus812** [comment]
Is this issue going to get any attention, it is quite annoying ? Has been opened since 0.2v
