### ISSUE TITLE
ubuntu 16.10 unstable release not updating in ppa

### ISSUE THREAD

**Issue by gstewart** [neovim/neovim#7170]
- `nvim --version`: NVIM v0.2.1-dev
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 16.10
- Terminal name/version: zsh
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour
The neovim package for yakkety (ubuntu16.10) from [ppa:neovim-ppa/unstable](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) has not been updating since 20170720. The packages for the other ubuntu versions have up to date builds.

The last package version built for yakkety was `0.2.0ubuntu1+git201707201346+3537+26~ubuntu16.10.1`.

The packages for other ubuntu versions all have up to date versions like `0.2.0ubuntu1+git201708151735+3596+26~ubuntu17.10.1` as of today.

**Comment by jamessan** [comment]
16.10 is EOL as of 2017/07/20 -- https://wiki.ubuntu.com/Releases.  You should upgrade to a new Ubuntu release.
