### ISSUE TITLE
scroll/ctlrl+e/ctrl+y with wrapped lines

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7172]
(neo)vim's behavior with soft-wrapped lines longer than the current buffer is a well-documented problem; navigation without jumping between hard lines is impossible if it means the start of the current line would be scrolled out of view.

While I understand the behavior with regards to the default vim motions, my question is specifically regarding `<c-e>` and `<c-y>`. The default behavior of these commands is to scroll the buffer by one line up/down. 

Would it be possible to work around the long-standing wrapped long lines issue by having `<c-e>` and `<c-y>` scroll one soft-wrapped line up/down _even if the start of the current line is no longer in view_?

**Comment by justinmk** [comment]
`gj`, `gk` move the cursor by one screenline. But AFAICT the specific feature requested here can't be implemented in a mapping or plugin: adjusting the viewport with CTRL-E or CTRL-Y goes to the next physical line, regardless of the cursor's "virtual" line.

**Comment by mqudsi** [comment]
Would "save position, jump to first/last virtual line, `g[kj]`, restore saved position" be a valid workaround?

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/8715 .
