### ISSUE TITLE
CCTree plugin loads DB in vim but not neovim

### ISSUE THREAD

**Issue by lorienhu** [neovim/neovim#7175]
- `nvim --version`: NVIM v0.2.1-608-g8eb54c5de
- Vim (version: ) behaves differently? YES - works in vim 8.0
- Operating system/version: Debian 9.1
- Terminal name/version: alacritty
- `$TERM`: xterm-256color

### Steps to reproduce

* Generate cscope DB in C project with cscope -R -b -q
* Use foorc
```
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'hari-rangarajan/CCTree'
call vundle#end()
filetype plugin indent on
```

```
nvim -u foorc
:CCTreeLoad cscope.out
```

### Actual behaviour
cscope.out is not loaded and this error displays:
```
Error detected while processing function 168[4]..142[6]..143[21]..102[8]..41:
line    1:
E716: Key not present in Dictionary: <96>
E15: Invalid expression: self.mappings[submatch(1)]
Error detected while processing function 168[4]..142:
line    6:
E171: Missing :endif
Press ENTER or type command to continue

```

### Expected behaviour
cscope.out loads correctly (as it does in Vim 8)

I saw #5922 which is similar, however, this works for me in vim but not nvim.

**Comment by justinmk** [comment]
@lorienhu Is this still happening on HEAD? (https://github.com/neovim/neovim/commit/a043899ba255524b7421579b9bd6112801f09247 )

**Comment by rmolin88** [comment]
I am still getting the error.
```
NVIM v0.2.3-500-g797d66ecf
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

```

**Comment by justinmk** [comment]
Error detected while processing function 168[4]..142[6]..143[21]..102[8]..41:

I don't want to debug this plugin's 5-deep dictionary function callstacks. Seems like no one else to wants to, either.  

Please open a new issue with _minimal_ steps to reproduce.  Until then we don't have any information to work with here. The plugin is 3000 lines of code.  The bug very well could be in the plugin itself.

**Comment by rmolin88** [comment]
@justinmk you are right in that nobody wants to debug the plugin. However, this seems strange:

![image](https://user-images.githubusercontent.com/5428479/35296460-16e90e22-004a-11e8-86ce-3f90b1a9094b.png)
![image](https://user-images.githubusercontent.com/5428479/35296491-3346d482-004a-11e8-9f75-fb03bbaa2e2b.png)

The steps in the description still hold to reproduce the issue.
