### ISSUE TITLE
Feature request: forward extra information with `v:completed_item`

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#7179]
## Description

Currently if I put a `{'word': 'ffffoo', 'snippet': 'bar'}` into the `complete-items` with the `complete()` call, and select the item, the `v:completed_item` doesn't have the `snippet` field.

This example shows what I mean:

minimal vimrc:

```vim
filetype plugin indent on
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=u
tf-8

set completeopt=menu,menuone,noinsert,noselect

func Foo()
        call complete(1, [{'word': 'ffffoo', 'snippet': 'bar'}])
        return ""
endfunc

imap <silent> f  <c-r>=Foo()<CR>
```

![peek 2017-08-18 10-13](https://user-images.githubusercontent.com/4538941/29442481-58635b40-8404-11e7-94cd-57a5af5e5667.gif)

In this case, `v:completed_item` is:

```
{'word': 'ffffoo', 'menu': '', 'info': '', 'kind': '', 'abbr': ''} 
```

While I'm expecting

``` 
{'word': 'ffffoo', 'menu': '', 'info': '', 'kind': '', 'abbr': '', 'snippet': 'bar'} 
```

## Why?

Current implementation of [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) uses the `info` field to inject and forward the snippet information, in order to support snippet expansion of the completed item.

But polluting the `info` field has side effect, it's wierd if a user is using `set completeopt+=preview`.   https://github.com/roxma/nvim-completion-manager/issues/116
 has some gif showing what I mean. The preview window shows useless `snippet@0` sometimes.

I'm not sure there's any better workaround for this. So I'm posting the feature request here.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/blob/master/src/nvim/edit.c#L3596

Unfortunately, it is impossible in the current implementation(cptext).
Because the selected candidate is hard coded.

**Comment by Shougo** [comment]
I may fix the problem without fixing v:completed_item.

To fix v:completed_item, the completion system must be rewritten.
It is very hard.

**Comment by Shougo** [comment]
My solution is to add `v:completion_list` variable.
It saves the previous completion list.

Note: It works only for `omnifunc`, `completefunc` and `complete()`.

The snippet plugins can get the complete information without injecting.

**Comment by roxma** [comment]
Considering different completion item may have the same `word` field, I think it needs an extra index variable to find the item in the list.

**Comment by Shougo** [comment]
> Considering different completion items may have the same word field, I think it needs an extra index variable to find the item in the list.

You can check it by `abbr`, `info` and `menu`.

**Comment by roxma** [comment]
Is it possible to add an extra dict into `v:completed_item`, without rewriting the completion system? It would be something like `v:completed_item['extra']`, which forwards the `item['extra']` object in the completion-items.

**Comment by Shougo** [comment]
>  It would be something like `v:completed_item['extra']`, which forwards the `item['extra']` object in the completion-items.

`item['extra']` must be String.
It can be added.  But it is useless.

**Comment by roxma** [comment]
Yeah. I cannot find the function to store the dict. 

In this case nvim could store the object by `json_encode` internally into `cptext`, and finally `json_decode` it into `v:completed_item`

**Comment by Shougo** [comment]
Current completion system problem:  The candidates list is the list of string.  The all atributes must be string.
So I have said "the rewrite of the completion system is needed.".

**Comment by Shougo** [comment]
> In this case nvim could store the object by json_encode internally into cptext, and finally json_decode it into v:completed_item

Hm...

**Comment by bfredl** [comment]
Who has decided it must be string?

**Comment by Shougo** [comment]
I think Bram.
It is hard to extend.  But it is optimized for the memory.

**Comment by bfredl** [comment]
But the current completion list is a very temporary data structure, no need to micro-optimize memory usage.

**Comment by Shougo** [comment]
Yes...

**Comment by Shougo** [comment]
https://github.com/vim/vim/pull/2608

The PR is available for Vim.

**Comment by uinput** [comment]
The PR was merged in patch 8.0.1493 (https://github.com/vim/vim/commit/9b56a57cdae31f7a2c85d440392bf63d3253a158)
@Shougo Will this suffice to fix https://github.com/Shougo/deoplete.nvim/issues/619?

**Comment by Shougo** [comment]
Yes.  But it takes more time.
I will port Vim 8.0.1493 before.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/8003

I have added user_data support in neosnippet.
