### ISSUE TITLE
Crash when trying to echo a backspace

### ISSUE THREAD

**Issue by Puzomor** [neovim/neovim#7181]
- `nvim --version`:  0.2.1-25-g2e3b78d1
- Vim (version: 7.4) doesn't crash.
- Operating system/version: Windows 10 64-bit
- Terminal name/version: both cmd and powershell

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:execute("!echo ".expand("\b"))
```

### Actual behaviour
`nvim` crashes with 

> Assertion failed!
> 
> Program: D:\Neovim\Neovim\bin\nvim.exe
> File: C:\projects\neovim\src\nvim\ui.c, Line 533
> 
> Expression: new_col >= 0
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> 

`nvim-qt` 
>Neovim exited with status code (3) `[Retry]`

Restarts normally with retry.

**Comment by oni-link** [comment]
Was probably fixed in #6618. File `ui.c` does not use `assert()` anymore. Can you try a newer version of nvim?

**Comment by Puzomor** [comment]
Latest build for Windows x64 available on the website doesn't have the problem fixed, and the latest package I can get on my arch is even older. Maybe some fellas that are building from source can confirm that it's indeed been fixed, since I can't?

**Comment by justinmk** [comment]
What does "last build" mean? Did you try https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip ? What does `:version` report?
