### ISSUE TITLE
":grep 'foo|bar'" splits at | (but ":echo 'foo|bar'" does not)

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7190]
Is it possible for neovim to either escape by default the arguments to `:grep` and `grpprg` or else provide a mechanism by means of which a user could specify a transform for the arguments before they are sent to `grpprg` in place of `$*?` (perhaps by providing a variable that will used as the argument to the `escape` function or by providing a different special variable other than `$*` that will provide shell-escape arguments)

**Comment by justinmk** [comment]
doesn't this work?

    :exe 'grep '.shellescape(...)

**Comment by mqudsi** [comment]
Given the search regex `unordered_(set|map)<wcstring`, I can get that to work when searching manually (btw, it doesn't work with your edited reply, but with your original minus `fnameescape` it does):

   :exe '!rg --vimgrep ' . shellescape("unordered_(set|map)<wcstring")

But how can I get it to so that executing it as `:grep unordered_(set|map)<wcstring` will escape the arguments directly?

**Comment by justinmk** [comment]
did you try surrounding in single-quotes (this won't work with cmd.exe on windows, of course)

    :let &grepprg="grep -n '$*' /dev/null"

**Comment by mqudsi** [comment]
Yeah, it doesn't help:

```
:!rg --vimgrep 'unordered_(set 2>&1| tee /tmp/nvim6Z6TZz/3

/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
shell returned 1
```

**Comment by justinmk** [comment]
oh, you need to escape the bar:

    :let &grepprg="rg --vimgrep '$*'"
    :grep unordered_(set\|map)<wcstring
                         ^--- escape this for vim (not the shell)

This could be fixed if we marked `:grep` to disallow commands that follow it. That makes sense to me.

**Comment by justinmk** [comment]
It might be worthwhile if there were some prefix that could be placed at the `:` prompt that internally does `fnameescape()`. On the other hand, it might not be worthwhile if it can be implemented in a `:command`:

    :command! -nargs=+ Literal exe fnameescape('<args>')

Then this works:

    :Literal grep foo|bar

but this still doesn't (and can't)

    :Literal grep foo%bar#baz

**Comment by KillTheMule** [comment]
> Somehow I feel like @KillTheMule mentioned something like this last year :>

If so, I can't remember, sorry :( My search-fu did not turn up anything as well.

**Comment by mqudsi** [comment]
Yeah, this is a tough question, the additional special argument was the "most compatible" thing I could think of.  So just like there's `$*` that passes the arguments, `$@` can provide vim & shell-escaped arguments. 

I don't think providing a prefix really solves the problem, as the idea is to not have to think about what I'm entering when I have a pattern I want to search for.

**Comment by justinmk** [comment]
> So just like there's $* that passes the arguments, $@ can provide vim & shell-escaped arguments.

The `|` has already been parsed by the then. Can't really change how that works, without changing the rules of VimL. E.g. in this case, after the command (`:grep`) is recognized, then the parser must go back and re-evaluate the entire input string.

**Comment by mqudsi** [comment]
If it's playing by the VimL parser rules, shouldn't simply placing the search term in quotes do the trick? I presumed it would follow shell rules, i.e. simply placing a special character in quotes should change its parsing behavior, which is why you can type `echo "|"` in whatever shell and it'll work.

I see that works for `:echo "foo|bar"`, so why can't `:grep "foo|bar"` be treated the same while preserving the behavior of `grep foo | bar` ?

**Comment by justinmk** [comment]
> I see that works for :echo "foo|bar", so why can't :grep "foo|bar" be treated the same

Ha! That's a very good question. Seems like a bug.

**Comment by mqudsi** [comment]
Which one is the bug? (fingers-crossed that it's `:grep` that's the bug and not `:echo`).

**Comment by justinmk** [comment]
`:grep`. @chrisbra what are your thoughts?

**Comment by justinmk** [comment]
The problem is that echo expects a VimL expression. `:grep` has no such restriction, so quoted aren't matched. And it would get complicated if you have nested quotes , should it be treated as VimL or shell ?

**Comment by chrisbra** [comment]
not quite sure. you are probably right with the VimL thing however.

**Comment by ZyX-I** [comment]
I would not say that guessing what user meant is a good idea: leave the behaviour as-is. If `:grep` command was only recently introduced I would suggest to treat it much like `:!`, `:terminal`, etc: they all treat `|` as a part of the command arguments (BTW, for some reason Bram did *not* choose to make `|` a part of `:terminal` arguments). Note: no detection of quotes or the like, *always* part of the command. If you add some detection now it will yield *yet another* kind of command with different rules for `|`/`"`/`\` handling and there already are much of them:

1. Command accepts multiple expressions like `:echo`: `|` may be a part of VimL string or `||`, `"` always starts a string, `\` is not special unless in double quoted string context.
2. Command accepts single expression like `:let`: `|` may be a part of VimL string or `||`, `"` may start a comment if expression already ended, `\` is not special unless in double quoted string context.
3. Command accepts “verbatim” argument like `:normal`: `|` and `"` are always in a command argument, `\` is backslash.
4. Regular command like `:put`: `|` separates commands, `"` starts a comment, `\` may do escaping of `"` or `|`.
5. Separatable command like `:map`: `|` separates commands, `"` is in command arguments, `\` may do escaping of `|`.

I am not sure I have listed all kinds of argument treatment, but five kinds are already too much to add another, you won’t see such a mess in any other language I know.

**Comment by lacygoill** [comment]
@mqudsi As a workaround, once [`8.1.2401`](https://github.com/vim/vim/releases/tag/v8.1.2401) has been ported to Nvim, you could try this mapping:

    nno <c-g>g :<c-u>cgete system("rg --vimgrep ''")<c-r>=setcmdpos(29)[-1]<cr>

Press `C-g g`, and the command-line should be populated with:

    :cgete system("rg --vimgrep ''")
                                 ^
                                 cursor right before this quote

Then you can write your pattern `unordered_(set|map)<wcstring`, and Nvim should correctly grep for the complete pattern, without stopping at the bar.

In case of any issue, you can increase the verbosity level to 4 to make Nvim print the exact shell command which is executed:

    :4verb cgete system("rg ...")
     ^^^^^

At the top of Nvim's pager, you should see a line looking like this:

    Executing command: "'/usr/local/bin/zsh' '-c' 'rg ...'"

**Comment by lacygoill** [comment]
Much more verbose alternative, but which works right now:

    nno <c-g>g :<c-u>call setqflist([], ' ', {'lines': systemlist('rg --vimgrep ""')})<bar>cw<c-r>=setcmdpos(61)[-1]<cr>
