### ISSUE TITLE
neovim shell command with parameters

### ISSUE THREAD

**Issue by iamkarlson** [neovim/neovim#7194]
vim 8.0 works well with following mapping
```
    nnoremap <F11> :silent !start "c:\Program Files\ConEmu\ConEmu64.exe" -single -dir "%:p:h"<CR>
```
but with neovim I'm getting an error: 
:silent !start "c:\Program Files\ConEmu\ConEmu64.exe" -single -dir "%:p:h"
The system cannot find the file -single.

- Operating system/version: Windows 10

```
NVIM v0.2.1-780-g5b32bce73
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

```

**Comment by justinmk** [comment]
`:!start` in Windows vim has some special-case behavior. We haven't implemented that yet; we just call the actual Windows `start` command. It might work if you quote the whole thing, so that it is a single argument to `start` (the nested unescaped quotes are usually what cmd.exe expects):

    nnoremap <F11> :silent !start ""c:\Program Files\ConEmu\ConEmu64.exe" -single -dir "%:p:h""<CR>

Going to consider this covered by #4927. 

Thanks for reporting.

**Comment by iamkarlson** [comment]
But that worked well in vim, why did neovim change that behaviour??

**Comment by justinmk** [comment]
We didn't change it, rather we haven't implemented it yet. Vim also has problems with the special case behavior, it's not always perfect.
