### ISSUE TITLE
Delete marks

### ISSUE THREAD

**Issue by roberbnd** [neovim/neovim#7198]
- `nvim --version`:  v0.2.0
- Vim (version:  8.0  ) behaves differently? yes
- Operating system/version: Archlinux
- Terminal name/version: Tilix
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
```
prompt -> nvim -u NORC test
 write a random text
aaa
bbb
ccc

go to line 1 'aaa'
:mark z
:marks  -> shows the mark 'z'
:wq
prompt -> nvim -u NORC test
:marks  -> shows the mark 'z'
delmark z  
:marks  -> doesn't show the mark 'z'
 :q
prompt -> nvim -u NORC test
:marks  -> shows the mark 'z'
```
### Actual behaviour

doesn't delete the marks

### Expected behaviour
delete marks

I found this because I want to use the plugin https://github.com/kshenoy/vim-signature/  

and never delete my marks and in vim I can do it

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/4444

https://github.com/neovim/neovim/issues/4295

**Comment by roberbnd** [comment]
Hi I red the comments and documentation and 
:wshada! = works
:wshada  = doesn't work
doesn't save the change.

**Comment by gennaro-tedesco** [comment]
Are there any news about a possible fix for this? I saw [this](https://github.com/neovim/neovim/issues/4288) and [this other](https://github.com/neovim/neovim/issues/4295) discussion, neither with a definitive answer. Or perhaps it will not be addressed at all (meaning one has to manually append in every single call, command, and function `:wshada!`)?
