### ISSUE TITLE
Autocmd filetype not executing when entering file

### ISSUE THREAD

**Issue by Mike-Now** [neovim/neovim#7199]
- `nvim --version`:
NVIM v0.2.0
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.2.0/build/config -I/builddir/build/BUILD/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.2.0/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.2.0/build/include
Compiled by mockbuild

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
- Vim (version: ) behaves differently?
- Operating system/version: Fedora 26
- Terminal name/version: tilix
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
create file  ~/.config/nvim/ftplugin/python.vim with the following code inside it:

`autocmd filetype python echomsg "foo"`

create file.py

run nvim -u NORC --cmd 'filetype plugin on' file.py
```

### Actual behaviour
Message 'foo' does not appear
Message 'foo' appears after set ft=python command
### Expected behaviour
Message 'foo' should appear upon entering the file

**Comment by chrisbra** [comment]
Yes, that is because your initial filetype autocommand is only sourced the first time when you edit a python file. So you edit a python file, vim reads the ftplugin/python.vim config file and creates the new python autocommand. So you probably want to skip the `autocomnd filetype python` part, if you are already using the ftplugin/python directory.

**Comment by jamessan** [comment]
Usage questions are better asked on https://vi.stackexchange.com.
