### ISSUE TITLE
Neovim Doesn't load a plugin which uses `b:did_ftplugin` while Vim does

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#7200]
I don't know if it's a problem with the plugin or the editor. I believe it's the editor because Vim behaves differently.

```
$ nvim --version
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: 8.0) behaves differently? **YES**
- Operating system/version: Arch Linux
- Terminal name/version (`$TERM`): `rxvt-unicode-256color`

### Steps to reproduce
```
cd ~/.config
mv nvim nvim.tmp
mkdir nvim
cd nvim
mkdir -p pack/not-loading/start
git clone https://github.com/lervag/vimtex pack/not-loading/start/tex
curl 'http://abacus.bates.edu/~etowne/beamersample.tex' -O
nvim beamersample.tex
:VimtexCompile
```

### Actual behaviour

`nvim` doesn't call `vimtex#init()` in `pack/not-loading/start/tex/ftplugin/tex.vim` because the 2nd condition `if exists('b:did_ftplugin')` comes out as true and the `tex.vim` `finish`es it.

### Expected behaviour

`nvim` will load `vimtex` just like `vim`.

**Comment by teto** [comment]
Sounds like a runtime error ? Might be fixed when we merge some runtime patch (though I can't find the incriminated patch).

**Comment by jamessan** [comment]
The problem is that nvim is loading the system-wide ftplugin/tex.vim before the pack's ftplugin/tex.vim.  There's a Vim patch that we need to merge.

**Comment by jamessan** [comment]
This may be the same as #6869.
