### ISSUE TITLE
CTRL-^ Does not toggle language characters in insert mode

### ISSUE THREAD

**Issue by timlag1305** [neovim/neovim#7207]
I looked through the Issue Tracker and couldn't find any related Bug Report so I figured I would put this out there.
- `nvim --version`:
```
NVIM v0.2.1-25-g2e3b78d1
Build type: RelWithDebInfo
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Optional features included (+) or not (-): -acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
- Vim (version: ) behaves differently? Yes:
```
VIM -Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 20.01:28)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-586
```
- Operating system/version: Windows 10 Enterprise
- Terminal name/version: (using GUI) nvim-qt.exe
- `$TERM`: N/A

### Steps to reproduce
Create the following file according to http://vim.wikia.com/wiki/Insert-mode_only_Caps_Lock#Using_a_keymap
`~\AppData\Local\nvim\keymap\insert-only_capslock.vim`
i.e.
```
" Toggle Caps Lock by pressing Ctrl-^, but only for insert and command mode.
let b:keymap_name = "CAPS"
loadkeymap
a A
b B
c C
d D
e E
f F
g G
h H
i I
j J
k K
l L
m M
n N
o O
p P
q Q
r R
s S
t T
u U
v V
w W
x X
y Y
z Z

A a
B b
C c
D d
E e
F f
G g
H h
I i
J j
K k
L l
M m
N n
O o
P p
Q q
R r
S s
T t
U u
V v
W w
X x
Y y
Z z
```

Add the following to your `init.vim`:
```
set imsearch=-1
set keymap=insert-only_capslock
set iminsert=0
```
### Actual behaviour
In insert mode, I type CTRL-^ and expect my keymap to toggle so that I can insert in all caps without pressing the caps lock button. Instead, I get the following in `:messages`: `E23: No alternate file`
It looks like neovim is trying to toggle between current and alternate file names. This does not happen in Vim.
### Expected behaviour
In insert mode, I type CTRL-^ and expect my keymap to toggle so that I can insert in all caps without pressing the caps lock button. This works in vim. If you add the init.vim to your .vimrc and add the keymap file to your .vim/keymap directory, you should see the "correct" behavior. See `:h i_CTRL-^` for expected behavior.

**Comment by justinmk** [comment]
Sounds like you are in normal mode.

Did you try the console version, i.e. 

    nvim.exe

**Comment by timlag1305** [comment]
I just tried in nvim.exe and it worked fine i.e. according to the Expected behavior. Does this indicate an issue with nvim-qt? If so, I can close this issue and reference it from that repository.

**Comment by jamessan** [comment]
It's probably related to equalsraf/neovim-qt#270.

**Comment by alex-shamshurin** [comment]
Has anybody any solution for this?
