### ISSUE TITLE
Support new "iterm2" entry from terminfo.src (2017-08-16)

### ISSUE THREAD

**Issue by lbschenkel** [neovim/neovim#7209]
Thomas Dickey created a dedicated entry for "iterm2" in the ncurses-6.0-20170819 release:
https://lists.gnu.org/archive/html/bug-ncurses/2017-08/msg00025.html
http://invisible-island.net/ncurses/terminfo.src.html#tic-iterm2

When setting `$TERM` to this new entry, NeoVim might fail to detect the terminal as being "iterm".

I have created a patch for it here:
https://github.com/neovim/neovim/compare/master...lbschenkel:iterm2?expand=1

In case you like this approach, I can create a PR (or feel free to pull the commit).

**Comment by lbschenkel** [comment]
I noticed that
https://github.com/neovim/neovim/blob/5cc4ea38c01e5307a7bfa7b2e238d69e1062c194/runtime/doc/term.txt#L46
probably needs updating as well, but I'm not sure how to best phrase "set terminal to 'iterm2' if the entry exists in your terminfo database, otherwise 'iterm'" in a concise way.

**Comment by justinmk** [comment]
> but I'm not sure how to best phrase "set terminal to 'iterm2' if the entry exists in your terminfo database, otherwise 'iterm'" in a concise way.

why does the user need to care? Can't they always set iterm2, and we will fallback as needed?

**Comment by lbschenkel** [comment]
Because you can only set `$TERM` to `iterm2` if your `terminfo` is recent enough to have the new definition (it can take months/years for this change to be incorporated by distros). In case you don't have the definition, no `ncurses`-based programs will be able to work (nor most other programs that rely on terminfo) since they won't know how to control the terminal.

**Comment by justinmk** [comment]
But that's the case for any TERM value.

**Comment by lbschenkel** [comment]
Nope, it doesn't. So let me take a step back here: up until now, iTerm2 users had two choices when setting `$TERM`:

1. Do nothing, and let iTerm2 set `$TERM` to `xterm-256color` (the default). For NeoVim that's usually good enough, since NeoVim knows it's iTerm2 pretending to be XTerm and amends the capabilities accordingly. But for other apps this is not ideal since they think they're talking to XTerm and the capabilities/sequences/keys are not exactly the same. Even for NeoVim it's not ideal since it treats anything set in terminfo as being authoritative, and the terminfo for `xterm` is not the optimal one for iTerm2.

2. Set `$TERM` to `iterm` (either via iTerm2 preferences or manually). NeoVim still recognizes it as being iTerm2 and amends any missing capabilities accordingly. That's the best for other apps since they'll use the proper sequences/capabilities/keys. Even for NeoVim it's better since the authoritative sequences in terminfo are the ones suitable for iTerm2.

However, I noticed that the terminal definition for `iterm` had some missing sequences and I posted to the ncurses mailing list to suggest amending it. Thomas Dickey, the ncurses maintainer, revisited the existing `iterm` entry (which was actually very old, it was made for the original iTerm, before the iTerm2 fork) and made the following changes:

1. amended `iterm` to reflect the actual capabilities of the *old* iTerm.app, pre-fork
2. created a new `iterm2` entry for *new* iTerm2 fork, the one everybody is using, which accurately describes the terminal capabilities (for example, adds missing italics, adds missing keybindings, etc.)

So... if you happen to have a terminfo database newer than 2017-08-19, the optimal `$TERM` for iTerm users is now `iterm2`. `iterm` describes the legacy version and is not the best choice of the terminal any longer (but probably still better than `xterm`). However, if you do set `$TERM` to `iterm2` and for some reason `$TERM_PROGRAM` is not set (ssh session, for example) then NeoVim will fail to detect the terminal as being iTerm2 and all the workarounds/augmentation of the terminal capabilities in `tui.c` for iTerm2 will not kick in. This is the issue I raised and this is what my patch fixes.

Is it a bit more clear now? (In retrospect I should included this explanation in the initial description.)

**Comment by justinmk** [comment]
Yep, thanks. Definitely we should enable the tui.c workarounds/augmentation for TERM=iterm2. I think we should also tell unibilium that TERM=iterm2 if we detect iterm _in any way_ (either because the user set TERM=iterm, or we noticed TERM_PROGRAM, etc.)

**Comment by lbschenkel** [comment]
Do you want me to create a PR for the changes in NeoVim? The reason I didn't is because I wanted to discuss the issue before submitting a fix to a non-existing issue.

**Comment by justinmk** [comment]
@lbschenkel give your explication above, and the changes in #7214, it's most correct to say that "iterm" terminfo is NOT built-in now, right? We have "iterm2" terminfo built-in, but the old, classic capabilities are different.

**Comment by lbschenkel** [comment]
That's right. But this phrasing only makes sense when you have a new terminfo, because otherwise the `iterm` definition applies to both iTerm and iTerm2 (it was really made for the former, but it's the closest definition available for the latter).

The whole thing can be confusing to understand and to explain. I don't know if there's anybody out there that still holds on to iTerm. Maybe the less confusing thing, moving forward, would be for NeoVim to always use the term "iTerm2" in both the documentation and code comments for the sake of clarity.

**Comment by justinmk** [comment]
Sure, but we're in a very messy transition for the next few years thanks to Thomas. terminfo entries will vary on systems for years, and "iterm" will mean something different. And literally 99% of users have no idea nor care about any of this.

**Comment by lbschenkel** [comment]
I agree. For NeoVim purposes, what I suggest is to be pragmatic and forget that iTerm exists. A `$TERM` of either `iterm` or `iterm2` should be interpreted that the terminal is iTerm2. This is already what the code does anyway.

In case you're interested I may have suggestions on how this could be handled better, but introducing more heuristics in the way of how `$TERM` is handled may not be something that is very appealing to you. It's probably wiser to wait and see how/when the upstream terminfo changes land into distros before doing anything more complicated.

**Comment by justinmk** [comment]
> In case you're interested I may have suggestions on how this could be handled better, but introducing more heuristics in the way of how $TERM is handled may not be something that is very appealing to you. 

Definitely interested if it improves the common case. The TUI workarounds will always be a mess, but it's a self-contained mess and it makes things better for users.
