### ISSUE TITLE
marks are lost after neovim is quit

### ISSUE THREAD

**Issue by xc1427** [neovim/neovim#7210]
neovim version: 0.2.0
os: macOS 10.12 sierra
terminal: iterm2 2.1.1
`$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```vim
echo "blabla" > bug.vim
nvim -u NORC
:e bug.vim
ma    " set mark `a`
:q
:nvim bug.vim -u NORC
:marks
```

### Actual behaviour
No mark `a` is found
### Expected behaviour
mark `a` is found

**Comment by justinmk** [comment]
Can't reproduce. This would be a rather annoying bug, that would have been noticed long ago, so maybe there's something different about your environment. Maybe the state file (`:help shada`) is not accessible by nvim. Can you try this:

```
nvim -u NORC -i myshada bug.vim
ma
:q
nvim -u NORC -i myshada bug.vim
marks
```

If that works, then there must be a problem with the default shada path on your system. Normally this path is `~/.local/share/nvim/shada/main.shada` unless you have `$XDG_DATA_HOME` set. See `:help xdg`.
