### ISSUE TITLE
c/c++ invalid syntax highlighting

### ISSUE THREAD

**Issue by pavard** [neovim/neovim#7211]
- `nvim --version`:
NVIM v0.2.0
- Vim (version: ) behaves differently?
VIM - Vi IMproved 8.0
- Operating system/version:
arch linux
- Terminal name/version:
- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`
```
cat > test.cpp << EOF
-TAB-#if 0
-TAB-#else
-TAB-#endif
// endif and any code below will not be highlighted
EOF
```
nvim -u NORC test.cpp

### Actual behaviour
code highlight doesn't work find

### Expected behaviour
code highlight works fine

I tried to put c.vim part of vim - the problem went away.

**Comment by justinmk** [comment]
This bug is present in Vim 8.0.1101. cc @chrisbra @brammool

**Comment by pavard** [comment]
@justinmk  there is no bug in 8.0.1176.

> I tried to put c.vim part of vim - the problem went away.

**Comment by chrisbra** [comment]
isn't that just a missing runtime update for neovim?

**Comment by justinmk** [comment]
@chrisbra Nvim has all runtime updates since 5 days ago. I'll check that I didn't mess something up.

**Comment by pavard** [comment]
ok.
