### ISSUE TITLE
Pasting a filename into the prompt should not enter paste mode

### ISSUE THREAD

**Issue by emma-borhanian** [neovim/neovim#7212]
- `nvim --version`: NVIM v0.2.1-540-gc4ac3ffbe
- Operating system/version: Ubuntu 14.04.5 LTS
- Terminal name/version: GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
" The long list of a's must be pasted
:e aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
:show paste?
```

### Actual behaviour
Paste is enabled

### Expected behaviour
Paste should not be enabled.

I do not want to enter paste mode when I paste a filename into the prompt. There's no correlation between wanting to paste a filename into the prompt, and wanting to be in paste mode when I'm actually editing the file.

I suggest not entering paste mode automatically if the cursor is currently entering text into the prompt.

**Comment by justinmk** [comment]
This seems like the converse of #7066. In any case, the solution is something like #4448.

Merging this with #7066.
