### ISSUE TITLE
Python support feature request - for some features like YouCompleteMe plugin

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7213]
- `nvim --version`: 0.2.1-814-g0f2873c
- Vim (version: ) behaves differently?
Stalled when install with YoucompleteMe plugin
- Operating system/version: Windows 10
- Terminal name/version: ConEmu
- `$TERM`:
> nvim
```
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support.
Press ENTER or type command to continue
```
NVIM v0.2.1-814-g0f2873c
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
```
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support.
Press ENTER or type command to continue
```
I have to put control + C to exit the program.

### Expected behaviour
I have installed Anaconda3 and can run python from command line:
```
> python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
Expect to run You Complete Me plugin in Nvim windows environment.

Any idea why? 
Thanks

**Comment by Shougo** [comment]
Please read `:help provider-python`.
You have not installed python provider for neovim.

**Comment by justinmk** [comment]
Run `:CheckHealth`, see also https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working
