### ISSUE TITLE
term buffer dies when switching buffers

### ISSUE THREAD

**Issue by plexigras** [neovim/neovim#7215]
When i open a terminal by doing `:terminal zsh` and then switch to another buffer the buffer the term buffer dies and with it anything that runs inside it.

weirdly i can create another buffer without the term buffer dying i just cant switch between buffers.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6280 will fix this.
https://github.com/neovim/neovim/issues/2368 is a similar issue.

Thanks for reporting.
