### ISSUE TITLE
inccomand: performance improvement #6949 wrong for `nosplit`

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#7220]
In the `nosplit` case, depending on the height of the preview window does the wrong thing. Either the height is greater than the number of matches in the current window, in which case we search too long (minor performance implication). If we have more matches in the current window than the height of the preview window, not all of them will be highlighted.

Now that I think of it, it might also be wrong in the split case when we have a lot of matches in the original window but a small preview window height.

I'd probably tackle this in the next few days, if no one else wants to do it :) I'll need a bit of handholding, gitter beware :D

**Comment by justinmk** [comment]
Thanks! Noticed this too.
