### ISSUE TITLE
Make not parallel safe

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7223]
I know neovim uses ninja which automatically parallelises as needed, but currently if you check out a clean copy of the source and manually specify a `-jN` parameter to `make` (chalk it down to old habits), odds are the build will fail because some of the instructions in the Makefile or one of its `$(MAKE)` targets are executed in an order that leaves the build in an inconsistent/invalid state.

This is extra low priority, but the Makefile should definitely be structured with all the dependencies correctly specified so that when executed in a multithreaded fashion the build still succeeds.

**Comment by bfredl** [comment]
I use `make -j4` everyday without problems. Could you give example of two rules that are racy with each other?

**Comment by mqudsi** [comment]
I'm not familiar enough with the neovim build script to debug this manually; I'll close it for now and re-open when/if I have a repro.

I think the problem only occurs when rebuilding from scratch; basic incremental rebuilds that shell out to ninja are fine.

**Comment by mqudsi** [comment]
It bothered me too much to close it without knowing for a fact it was reproducible so I tackled this again.

I have a log of the build failing when executed after `make distclean` with `-j32`; the same procedure on the same machine always succeeds when executed without the `-j32` parameter.

From memory, it's the same failure as my past experiences: it's unable to build libuv. That would explain why there's no problem running `make -j4` when only neovim has changed (and not building the dependencies).

[build_j32.txt](https://github.com/neovim/neovim/files/1307826/build_j32.txt)
[build_noj.txt](https://github.com/neovim/neovim/files/1307825/build_noj.txt)

**Comment by justinmk** [comment]
@mqudsi Maybe I didn't look closely enough, could you excerpt the lines from those logs where the error(s) are reported? I didn't see any.

**Comment by justinmk** [comment]
Assuming this was fixed by https://github.com/neovim/neovim/pull/7697 . Else need the info requested above.

**Comment by mqudsi** [comment]
Sorry; but yes, it was the luarocks dependency that was being breaking on parallel build.
