### ISSUE TITLE
diffsplit throws E315 if cursor is on line number greater than the file being diffed

### ISSUE THREAD

**Issue by joshuarubin** [neovim/neovim#7226]
- `nvim --version`: 

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

- Vim (version: ) behaves differently?

Yes, vim 8.0.997 does not throw an error in this situation.

- Operating system/version:

MacOS Sierra

- Terminal name/version:

Alacritty

- `$TERM`:

xterm-256color

### Steps to reproduce using `nvim -u NORC`

Where `<file0>` is a file with more lines than `<file1>` and the cursor is on a line number greater than the number of lines in `<file1>`:

```
nvim -u NORC <file0>
:diffsplit <file1>
```

### Actual behaviour

Throws `E315: ml_get: invalid lnum: 412`

### Expected behaviour

Does not throw error

**Comment by chrisbra** [comment]
Guessing missing Vim patch [8.0.0044](https://github.com/vim/vim/releases/tag/v8.0.0044)

**Comment by justinmk** [comment]
@joshuarubin since you're comparing the development version of Vim, maybe you can try the development version of Nvim :)

**Comment by justinmk** [comment]
0044 is in the "merged" column of https://neovim.io/doc/reports/vimpatch/, so closing unless this is repro'd on master.

**Comment by joshuarubin** [comment]
Updating to HEAD (`v0.2.1-815-g7bfa4406c`) did indeed resolve this. Thank you. I guess I just didn't know what to search for...
