### ISSUE TITLE
Proposal: include a --init to bootstrap new users with a beginner init.vim

### ISSUE THREAD

**Issue by thalesmello** [neovim/neovim#7228]
Taking a look at other existing cli tools, there it's a somewhat common pattern to include some kind of `init` mode (e.g. eslint, npm, tsc), which bootstraps the user with a sample configuration file.

Considering Neovim has a big focus on usability, it could possibly help newcommers to get started with Neovim.

Suppose the following workflow:

If the user has no `~/.config/nvim/`, the command `nvim --init` would output something like:

```
Welcome to Neovim! We created a configuration file for you at
~/.config/nvim/init.vim

We recommend you to version control your configuration files, so that it's easy to setup your Neovim in the future.
```

If the user already has a `~/.config/nvim/` folder, it would output:

```
It looks like you already have configuration files.

Take a look at ~/.config/nvim/. You could either modify them, or remove the folder in case you don't want those files.
```

Finally, the created output file could be something like:

```
" This sets the leader key. Think of it as a namespace for your mappings.
let mapleader = "\<space>"

" This creates a mapping to save the current file when the user presses `<space>w`
nnoremap <leader>w :write<cr>

" This sets live substitution when using `:%s /pattern/substitution/g`
set inccommand=split
```

The contents of the default configuration file could be improved over time, but I think that having a way of intuitively creating that file, with good comments and examples would be really good for newcomers.

What do you guys think?

**Comment by dmerejkowsky** [comment]
I've tried doing that in one of my previous projects.

The code was surprisingly quite hard to write, and quite hard to test too.

I'd prefer we'd focus on good defaults and nice documentation instead.

My 2 cents.

**Comment by justinmk** [comment]
I have some ideas about how to reduce friction creating a blank init.vim. But a sample one, no. Agreed that we should commit to defaults or don't bother.
