### ISSUE TITLE
Aliases - wont accept user aliases as in :terminal ls

### ISSUE THREAD

**Issue by oldgaro** [neovim/neovim#7229]
As every terminal user, we defined a lot of aliases. But I am unable to open :terminal with my own aliases as an argument.

it does accept: 
`: terminal ls`

But not mine own alias  `ls -l` :
`:terminal ll `

------------------------------
- `nvim --version`: v0.2.0
- Vim (version: ) behaves differently? nope!
- Operating system/version: Arch Linux 
- Terminal name/version: st 0.7
- `$TERM`:  st-truecolor

### Steps to reproduce using `terminal ll`

```
: terminal ll

```

### Actual behaviour

` zsh:1: command not found: ll`
`[Process exited 127]
`

### Expected behaviour
```
-rwxr-xr-x 1 garo garo  8376 Sep  1 22:31  compiled
-rw-r--r-- 1 garo garo 15905 Aug 31 03:07 'C Programming: A Modern Approach - Summary.txt'
-rw-r--r-- 1 garo garo   634 Sep  1 22:09  dweight2.c
-rw-r--r-- 1 garo garo   735 Sep  1 21:56  dweight.c
-rw-r--r-- 1 garo garo   519 Sep  1 19:54  Makefile
-rw-r--r-- 1 garo garo   404 Sep  1 19:56  pun.c

```

**Comment by justinmk** [comment]
Depends on your .bashrc
