### ISSUE TITLE
Colors in Neovim terminal should follow vim colors by default 

### ISSUE THREAD

**Issue by bearcatsandor** [neovim/neovim#7238]
In my init.vim i had to provide  let g:terminal_color_0  = '#5f5f87' ... let g:terminal_color_27 = '#ffffff'  to get neoterm to match my vim colorscheme.

Is there a way to make neoterm match the current vim colorscheme by default?  Could this be read if it were launched with 'nvim +term' as well?

Why isn't' this the default behavior?

**Comment by justinmk** [comment]
Please search existing issues.

**Comment by bearcatsandor** [comment]
Thank you, but i did that before i posted, for about 6 pages and didn't find a match.  Would you mind linking the issue you found that matches it here in case others have trouble as well?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/4696 and https://github.com/neovim/neovim/issues/7018

**Comment by bearcatsandor** [comment]
Yeah that's what i thought would be linked. This is not a duplicate. It's a different issue.  I'm not talking about matching colors as defined in the terminal emulator that spawns it or truecolor.

I'm saying that if i set up a colorscheme in vim, i'd like the colors in the terminal to match automatically. In other words, if i have 'colorscheme alduin' in my init.vim it would be nice if neovim could apply the g:terminalcolor variables for me so that the terminal buffer matches, unless i specifically instruct it not to in the settings.

**Comment by justinmk** [comment]
Hmm. You mean e.g. `g:terminal_color_0` would be set by `:hi Keyword`? 

Which color numbers should be controlled by which syntax groups?
