### ISSUE TITLE
CMake ignores install prefix for manpages

### ISSUE THREAD

**Issue by raichoo** [neovim/neovim#7239]
Hi,

I've set my `CMAKE_INSTALL_PREFIX` to something else rather than `/usr/local` yet when doing `gmake install` this happens:

```
-- Install configuration: "Release"
-- Up-to-date: /usr/local/man/man1/nvim.1
```
All the other files get installed where I expect them to be.

Kind regards,
raichoo

**Comment by justinmk** [comment]
what OS?

**Comment by raichoo** [comment]
Ah right forgot about that. FreeBSD.

**Comment by justinmk** [comment]
I think what's needed is to document   `$CMAKE_INSTALL_PREFIX` and `$CMAKE_INSTALL_MANDIR`.

**Comment by justinmk** [comment]
@raichoo does CMAKE_INSTALL_MANDIR solve your issue? Any comments on https://github.com/neovim/neovim/issues/6771 ?

**Comment by raichoo** [comment]
Ah sorry, for not replying. Yeah, it seems to work just fine when setting CMAKE_INSTALL_MANDIR.

**Comment by yggdr** [comment]
Having the same problem here: how do I actually set CMAKE_INSTALL_MANDIR?
    gmake CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/local -DCMAKE_INSTALL_MANDIR=$HOME/local" CMAKE_BUILD_TYPE=Release install
seems to ignore it entirely.

**Comment by justinmk** [comment]
@yggdr Remember that cmake caches your previous configuration, try `rm -rf build`.

**Comment by Snaipe** [comment]
CMAKE_INSTALL_MANDIR acts like CMAKE_INSTALL_LIBDIR/BINDIR: it should represent the name of the directory (or subpath) *relative to* CMAKE_INSTALL_PREFIX, where it's going to be installed, like `man`. It shouldn't be an absolute path.

Incidentally, [this](https://github.com/neovim/neovim/blob/1cf377f23af1115430752ab2717ad937d9989e2f/cmake/InstallHelpers.cmake#L6) doesn't seem right.

**Comment by justinmk** [comment]
@Snaipe You're contradicting https://github.com/neovim/neovim/issues/6771 , correct? Need someone to explain which is correct.

**Comment by Snaipe** [comment]
No -- it's just that the right macro should be used for the right situation.

If a distribution relies on MANPREFIX to specify a different install prefix than the CMAKE_INSTALL_PREFIX, it's fine, but I think overriding CMAKE_INSTALL_FULL_MANDIR might be better according to the [cmake docs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html)

**Comment by Snaipe** [comment]
Actually, reading through the sources of GNUInstallDirs at different versions, it seems that CMAKE_INSTALL_FULL_* variables are overwritten, and CMAKE_INSTALL_* variables may be absolute.

However, I'm pretty sure that using CMAKE_INSTALL_PREFIX rather than /usr/local when MANPREFIX isn't defined would be better.

**Comment by justinmk** [comment]
> However, I'm pretty sure that setting CMAKE_INSTALL_MANDIR to $CMAKE_INSTALL_PREFIX/man rather than /usr/local/man when MANPREFIX isn't defined would be better.

Again that will regress #6771. I don't care one way or other, BSD users need to figure this out and wake me up when it's decided.

... :)

**Comment by Snaipe** [comment]
I don't really see how that would regress anything. If the line I mentioned earlier is changed to `${CMAKE_INSTALL_PREFIX}/man`, then it's going to be expanded to /usr/local/bin by default, which is the current behaviour.

Users specifying CMAKE_INSTALL_PREFIX to /usr (like OP) would then have a man path of /usr/man, which seems more sensible than /usr/local/man, and MANPREFIX would still be accounted for.

**Comment by justinmk** [comment]
> If the line I mentioned earlier is changed to ${CMAKE_INSTALL_PREFIX}/man, then it's going to be expanded to /usr/local/man by default

@Snaipe I feel like it was the first thing I tried and there was some issue. Maybe I'm wrong though. Can you try it and send a PR if it works?

**Comment by krishnakumarg1984** [comment]
@justinmk This seems to have regressed recently. I am trying to build neovim-0.9.2 on a shared linux machine without admin privileges, and have set `CMAKE_INSTALL_PREFIX` to `$HOME/bin` and yet, the `make install` stage fails by trying to write the manpages to `/usr/local/share/man` (or `/usr/share/man` , can't remember).
