### ISSUE TITLE
php.vim is outdated

### ISSUE THREAD

**Issue by GeneralFailer** [neovim/neovim#7240]
I'm having an issue with the last line there not getting indented.
```
if ($name && $email && $gender && $comments) {
                echo "<p>Thank you, <b>$name</b>, for the following comments:<br>
                        <code>$comments</code></p>
                        <p>We will reply to you at <i>$email</i>.</p>\n";
echo $greeting;
```
In Vim this works fine.

**Comment by teto** [comment]
vim runtime is ported with some delay so that should get fixed some time in the future.

**Comment by justinmk** [comment]
Neither the vim version nor nvim version were mentioned. We don't need reminders to merge vim's runtime, since that is an ongoing task.

**Comment by GeneralFailer** [comment]
Both are up-to-date. I just thought that 2 years is a bit much.

**Comment by chrisbra** [comment]
[this](https://github.com/2072/PHP-Indenting-for-VIm/) seems to be the upstream version. So you can use that one and check if that works. Other than that, there haven't been many updates to indent/php.vim, only
vim/vim@3ec574f2b549f456f664f689d6da36dc5719aeb9 (which only changes `&sw` to `shiftwidth()` function, so this isn't to blame probably) and vim/vim@e0720cbf63eb3045be8d965e3182c0c392c7b5e9 (which is more likely to be the version that fixes your issue). There were no more updates this year.

**Comment by GeneralFailer** [comment]
Yeah, I had tried that one.
>I just thought that 2 years is a bit much.
nvm, it's not actually that old.

**Comment by chrisbra** [comment]
> Yeah, I had tried that one.

And it didn't work? Then perhaps you should report it upstream, so that it can be fixed for both vim and nvim. Also, if it doesn't work, compare your indent settings for both nvim and vim, if that script isn't to blame, there must be a difference between both programs.


>> I just thought that 2 years is a bit much.

>nvm, it's not actually that old.

Not sure, what you are trying to say here.

**Comment by GeneralFailer** [comment]
It works fine both in Vim and upstream, hence the report title.

I tried to correct myself, so yeah, never mind.
