### ISSUE TITLE
Neovim is unable to listen to a process while spawning a listen at port arg

### ISSUE THREAD

**Issue by Khalian** [neovim/neovim#7242]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? Not tried. 
- Operating system/version: MacOSX. Sierra
- Terminal name/version: iTERM2. 
- `$TERM`: echo $TERM: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
NVIM_LISTEN_ADDRESS=127.0.0.1:7650 nvim
freeport 7065                                                                                                                                                                
```
### Actual behaviour
No process running on port 7065

### Expected behavior
Something should be listening to that port. 

This is a huge deal breaker. I am trying to hook an intelliJ instance to neovim server, and it does not find the process. Please help!!!!!!!!!!!!!!!

**Comment by justinmk** [comment]
7650 is different than 7065.

Also, you can start more servers via `serverstart()` in nvim:

    :call serverstart('127.0.0.1:7065')

**Comment by Khalian** [comment]
Erm, I am going to go and bury my head in sand to drain my embarrassment for a while.
