### ISSUE TITLE
Error storm not interrupted by ctrl+c

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7246]
Running v0.2.1-809-g85f3084 (which is after all the work on stderr collectors), I ran into an error storm that I couldn't bypass with ctrl+c (i.e. I had to keep pressing enter until all the error output was exhausted).

Here's a screenshot that shows what happened (and when the ctrl+c interrupts occurred):

![image](https://user-images.githubusercontent.com/606923/30140956-c45a1328-933d-11e7-99c2-47a547ed7cb8.png)

This was an error in a deoplete source, which would be using the rplugin interface and the corresponding error collector.

(I'm upgrading to `master` now, in case it's been since fixed).

Obviously I will try to isolate this and get a proper, reproducible case.

**Comment by teto** [comment]
yep deoplete (or its sources) has a tendancy to generate long and painful errors. It would be better off in a new buffer IMO.

**Comment by bfredl** [comment]
It seems that deoplete sends multiline error messages one line at a time instead of all at once, which should trigger only one "press ENTER"

**Comment by justinmk** [comment]
Assuming this can be fixed in deoplete. cc @Shougo

**Comment by mqudsi** [comment]
I took a look at the deoplete source and a closer look at the error stream I posted above. While, yes, this can be worked around on @Shougo's end, I think there is actually an underlying problem in neovim's rplugin control flow here.

If you look at the error, it's not _deoplete_ that's writing to stderr, it's python reporting an unhandled exception.

Here's a better example:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/usr/home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 151, in gather_candidates
[deoplete]     params)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 318, in get_completion
[deoplete]     tu = self.get_translation_unit(fname, args, buf)
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 305, in get_translation_unit
[deoplete]   File "/usr/home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     tu = self.index.parse(fname, args, buf, flags)
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 2322, in parse
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 151, in gather_candidates
[deoplete]     self)
[deoplete]     params)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 2440, in from_source
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 318, in get_completion
[deoplete]     raise TranslationUnitLoadError("Error parsing translation unit.")
[deoplete]     tu = self.get_translation_unit(fname, args, buf)
[deoplete] clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/sources/deoplete_clang.py", line 305, in get_translation_unit
[deoplete] Could not get completions from: clang.  Use :messages for error details.
[deoplete]     tu = self.index.parse(fname, args, buf, flags)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 2322, in parse
[deoplete]     self)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/zchee/deoplete-clang/rplugin/python3/deoplete/clang/clang/cindex.py", line 2440, in from_source
[deoplete]     raise TranslationUnitLoadError("Error parsing translation unit.")
[deoplete] clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
[deoplete] Could not get completions from: clang.  Use :messages for error details.
```

I am not a python deveolper, so please correct me if I'm wrong, but it seems to me that deoplete is raising a python exception and the python interpreter is dumping the unhandled exception to stderr, which neovim's stderr collector then writes out to the vim error log, one line at a time.

If so, this should be re-opened.

**Comment by bfredl** [comment]
This was fixed in the native python exception printer some while ago. Can you reproduce it outside of deoplete? the `[deoplete]` at start of each line makes it seem it is deoplete writing it.

**Comment by bfredl** [comment]
If fact you can see a "natively" caught `KeyboardInterrupt` being correctly printed as a multi-line errmsg in the screenshot.
