### ISSUE TITLE
No colors in NeoVim terminal.

### ISSUE THREAD

**Issue by chenw30030** [neovim/neovim#7247]
I recently switched from `vim 8.0.952` to `nvim v0.2.0`, the latest stable version from `Ubuntu`'s ppa, and while the colors are the same in the editor, I realized that I have no colors in the `nvim` terminal. I have searched this Github for a while and haven't found a solution. How can I fix it?

1. I am using `gnome terminal 3.18.3` on `Ubuntu 16.04.2` .
2. I have `set termguicolors` and `colorscheme base16-default-dark` in `init.vim`.
3. I have `256color` and `truecolor`.
4. I did `export TERM=xterm-256color`.
5. `g:terminal_color_0`-`g:terminal_color_15` values are set in `base16-default-dark.vim`.

**Comment by teto** [comment]
first, lying about gnome-terminal being xterm doesn't look like a good idea. See `:h TERM`
Then saying it supports only 256colors should conflict with termguicolors.
As for the g:terminal_color_0, I've never used that so I can't say.

**Comment by justinmk** [comment]
"no colors" meaning black and white? What is the value of g:terminal_color_0 ? What if you don't set a color scheme, are there colors then?

**Comment by chenw30030** [comment]
@justinmk Yes. The value is "#181818". Still black and white when the colorscheme is removed.

@teto Sorry I don't follow. Should I have done something different with the xterm? I got that it supports `256colors` from http://www.robmeerman.co.uk/unix/256colours.

**Comment by justinmk** [comment]
Are there colors if you run without your configuration?

    nvim -u NORC +':terminal'

**Comment by chenw30030** [comment]
@justinmk 
That seems to work. Does that mean there is a conflict with one of my vimrc plugins?

**Comment by justinmk** [comment]
1. known issue.
2. probably. 

> Otherwise, do I have to resort to choosing a new colorscheme? Even then, it seems termguicolors may still present problems

No, termguicolors works fine with colorschemes.

we can try to fix specific problems, but the steps to reproduce the issue need to be minimized, otherwise we spend too much time debugging people's configurations.

**Comment by chenw30030** [comment]
Do you know any other threads here that answers the first question? I am not sure what terms to use in the search box.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/5431 is the umbrella issue, 2nd item listed there:

>  `:!` should use `:terminal` internally. Closes #2958 #4338. Doesn't affect `:read !foo` etc. See #5396. Use cases: #5580.

**Comment by XVilka** [comment]
I have a similar bug. If I run `nvim` in `:terminal` it also shows only black-and-white mode. Would be nice to have the possibility to nest multiple nvims into each other.

**Comment by justinmk** [comment]
> Would be nice to have the possibility to nest multiple nvims into each other.

That should already work. I guess you mean if the nested nvim has `set termguicolors` ? Did you try with `set notermguicolors` in the nested nvim?

**Comment by XVilka** [comment]
Yes, I meant if nested nvim has `set termguicolors`. Otherwise, if I `set notermguicolors` it's OK, shows colors properly.

**Comment by justinmk** [comment]
Ok, that's a known issue, and doesn't sound like the issue @chenw30030 described (correct me if wrong)

**Comment by justinmk** [comment]
Please create a new issue if you find minimal steps to reproduce.
