### ISSUE TITLE
Terminal title isn't changed when startup is slow and starting in insert mode in a terminal buffer

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7248]
- `nvim --version`: NVIM v0.2.1-855-gcb912a3ed
- Operating system/version: Linux 4.12.5-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC --cmd 'execute("set titlestring=" . $NVIM_LISTEN_ADDRESS) | set title | startinsert | !sleep 1' term://sh
```

### Actual behaviour
Title isn't set until terminal insert mode is left. If either `sleep 1` or `startinsert` is removed, everything works as expected.

### Expected behaviour
Title should be set as soon as possible.

**Comment by justinmk** [comment]
@glacambre Thanks for the clear repro steps.

**Comment by glacambre** [comment]
It's the least I can do, thank you for your hard work.
