### ISSUE TITLE
Feature request - Add python and lua dlls to Nvim directory for portable

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7251]
- `nvim --version`: 0.2.1
- Vim (version: ) behaves differently? No
- Operating system/version: Windows 10
- Terminal name/version: CMD
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
Some plugin requires Lua or Python or Ruby
### Expected behaviour
Add Python36.dll, or lua53.dll or ruby...dll  or similar method to Nvim bin directory to run NVim without having to install those required programs.

Sorry, I don't know much about computer science. I learn to use Nvim for editing text and learn programming with python only.

Thank you.

**Comment by duytrung** [comment]
I used to use the computer in the university and it does not have the requires programs installed. Installation requires admin right and permission from the IT staffs.

**Comment by bfredl** [comment]
Hmm, but how did you install neovim if you didn't have permission?

**Comment by duytrung** [comment]
I extract the Neovim zip to my USB and run from neovim-qt. I prefer

**Comment by bfredl** [comment]
It is out of scope for the standard binary distribution. But it would be entirely possible for someone to make a portable "bundle" with neovim+python+required python packages and binary dependencies. Plus whatever glue trickery needed for all to find all in relative paths. 

Lua is always builtin, should be no issue there.

**Comment by jamessan** [comment]
Note that Neovim requires more than _just_ the dlls.  Unlike Vim, we don't embed the interpreters in Neovim.  We run the external interpreters and RPC between nvim/interpreters.

**Comment by justinmk** [comment]
@duytrung as @bfredl mentioned, Lua is always built-in to Nvim. `:lua`, `:luafile`, `luaeval()`, etc. will always work. But new-style

You may find some old plugins that need the vim `if_lua` feature. We haven't implemented that compatibility layer yet.

> You can add portable versions of the interpreters you want (e.g., WinPython) to

Yes, _those projects_ (python, ruby, ...) need to do the work of providing portable versions of their products. It's too much work for us to maintain some universal mega-bundle. And it's not worth it, anyway: we ship with Lua and VimL. That should be enough in a locked-down environment.

**Comment by duytrung** [comment]
Thanks for all replies. I know tha I can copy Python and other program binaries to my usb as well but I'm not sure how to "link" so that the program can work in this case.  For example put the path in an init.vim with relative path to the USB drive.
Any idea?

Thanks

**Comment by justinmk** [comment]
There is no linking step.

**Comment by bfredl** [comment]
I think he just meant for nvim to find python in a path relative to nvim. And then there is finding the python packages in a path relative to nvim/python. Both will require some (small) amount of code.

**Comment by bfredl** [comment]
but maybe not the later, if pip of a portable python is smart enough to install "inline" the portable lib dir...
