### ISSUE TITLE
missing ga_concat_esc() C function

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7256]
from vim-patch: 
https://github.com/vim/vim/commit/2368917d8f0c0a997eac7a51ddfaa748dc528392

Currently Vim uses that function only for printing `assert_*` results. Without it we may get friction when merging Vim tests, etc.

**Comment by androidpcguy** [comment]
I would like to take on this issue, as it's my first time contributing.

**Comment by acferreir4** [comment]
Would you also like ga_concat calls to be replaced with calls to ga_concat_esc?

**Comment by justinmk** [comment]
@acferreir4 only in the equivalent cases where that's done in Vim.
