### ISSUE TITLE
Scrolling after a :!make

### ISSUE THREAD

**Issue by Bamban** [neovim/neovim#7259]
Hi,
When compiling stuff, I like to use :!make to avoid exiting nvim.
The typical behavior of vim was to print the output of make in the terminal vim was opened. Thanks to this behavior, I could scroll up and down to read the log. When hitting enter and getting back to vim, I could also CTRL-z / fg to read the output of the `make` command and scroll up.
How can I reproduce this behavior with Neovim ? For the moment, not only the log is thrown away but neither can I scroll up and down in the log before pressing enter.
Thanks for your help !

**Comment by justinmk** [comment]
`:make` (without `!`) will populate the quickfix list. This is, in fact, the main (and original) purpose of the quickfix list. Use `:copen` to see the list.

You can also use `:terminal` (`:te` for short).

Your specific issue is covered by https://github.com/neovim/neovim/issues/1496

see also https://github.com/neovim/neovim/issues/5431
