### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by Khalian** [neovim/neovim#7263]
- `nvim --version`:NVIM v0.2.0
Build type: Release
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

- Vim (version: ) Does not have these errors
- Operating system/version: MacOSX Sierra
- Terminal name/version: iterm2
- `$TERM`:xterm-256color

Error detected while processing function <SNR>106_OnTextChangedInsertMode[5]..provider#python#Call:

**Comment by justinmk** [comment]
> 106_OnTextChangedInsertMode

Use `:scriptnames` to find out what script (plugin) is 106.

And report the issue to that plugin, not here.
