### ISSUE TITLE
Alt key not recognized in kitty terminal emulator

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#7266]
- `nvim --version`: NVIM v0.2.1-867-gd2cbc3118
- Vim (version: ) behaves differently?
- Operating system/version: macos 10.11.6
- Terminal name/version: kitty 0.3.0
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

map <a-s> :echo 'hi'<CR>
press alt <a-s>
```

### Actual behaviour

nothing happens in kitty, but it works in iterm.

### Expected behaviour

should echo `hi` in kitty.

**Comment by justinmk** [comment]
Configure kitty to send ESC when alt is pressed.
