### ISSUE TITLE
cursor does not change shape in insert mode for kitty term emulator

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#7267]
- `nvim --version`: NVIM v0.2.1-867-gd2cbc3118
- Vim (version: ) behaves differently?
- Operating system/version: macos 10.11.6
- Terminal name/version: kitty 0.3.0
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
enter insert mode
```

### Actual behaviour

cursor remains a block

### Expected behaviour

cursor should become skinny

**Comment by justinmk** [comment]
Did you set guicursor?

**Comment by justinmk** [comment]
Are you sure kitty supports cursot shaping? Link to the relevant kitty doc?

**Comment by Alok** [comment]
Apparently it does support it, as @koekeishiya has it working. I wonder what's wrong with my setup then. Something to do with terminfo?
