### ISSUE TITLE
What is the canonical way to open neovim from within a neovim terminal

### ISSUE THREAD

**Issue by Khalian** [neovim/neovim#7268]
I use git rebase interactive from time to time which uses neovim as the editor. 

If I do git rebase -i inside a neovim terminal, i open a vim session inside of a vim session. Simple keys work but Escape works on the outer vim session.

What is the canonical way to open vim inside of a neovim terminal, so that the session can exist as a buffer inside the session that hosts the neovim terminal?

**Comment by justinmk** [comment]
Something like https://github.com/mhinz/neovim-remote could help.

We plan to make this more seamless eventually. 

Note that we generally can't handle usage questions on the issue tracker, please consider https://vi.stackexchange.com

**Comment by KillTheMule** [comment]
Alternatively https://www.reddit.com/r/neovim/

**Comment by Khalian** [comment]
Ok I did not know that. Anyways I was able to solve the problem with the pointer you provided : git config --global core.editor 'nvr --remote-wait-silent'
