### ISSUE TITLE
C: improper indent of structs within return

### ISSUE THREAD

**Issue by 44100hertz** [neovim/neovim#7269]
An example:
```C
struct point point_zero() {
    return (struct point){
        0,
            0,
    };
}
```

It's just treating the `{` as the start of a statement and the `,` as a comma operator and getting confused. I think `return` needs to be treated like an lvalue.

**Comment by justinmk** [comment]
Can you answer the fields in the issue template?

**Comment by hertz4** [comment]
I can assure you this bug is not version, OS, or terminal-specific. If you insist, I will.

**Comment by justinmk** [comment]
It's useful to know if Vim has the same behavior, and the exact version of vim that was tested.

**Comment by hertz4** [comment]
I'm on v0.2.0.

Vim has this behavior. This is a very old bug, I've been using vim and nvim for some time and it's always been there. The bug is actually in many other editors, too.

**Comment by justinmk** [comment]
This is more likely to get attention if report to Vim. Though if you want to send a patch with a test, it's welcome here.

**Comment by hertz4** [comment]
Thanks, I'll be sure to bug them about it, too.

**Comment by justinmk** [comment]
Duplicate of #3234
