### ISSUE TITLE
:w! doesn't work as expected if file has been changed externally

### ISSUE THREAD

**Issue by danielyli** [neovim/neovim#7270]
- `nvim --version`: NVIM v0.2.0, Build type: Release
- Vim (version: 8.0.1100) behaves differently? Behaves the same as vim 8.0.1100
- Operating system/version: macOS 10.12.6
- Terminal name/version: iTerm 3.0.15
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

  1.  `$ nvim -u NORC <some file>`
  1.  Make some changes to that file in another editor.
  1.  In nvim: `:w!`

### Actual behaviour

Displays `WARNING: The file has been changed since reading it!!!`

### Expected behaviour

It should silently write the file, since `:help write` says:

  > Like ":write", but forcefully write when 'readonly' is set **or there is another reason why writing was refused.**

**Comment by justinmk** [comment]
I feel like this has been discussed before but I can't find it on vim_dev nor vim_use. @chrisbra does this sound right?

**Comment by chrisbra** [comment]
I don't remember. But I would say, don't change the current behaviour. It's good to notify the user of possible unexpected changes to the file

**Comment by justinmk** [comment]
In `buf_write()`, `check_mtime()` explicitly after checking `!forceit` (i.e., `forceit` is ignored when checking mtime). So this seems to be intentional. Maybe the documentation could be clarified.

**Comment by justinmk** [comment]
## Proposal

1. change `:write!` (with bang) not to show a warning
2. change `:write` as follows (via @andmis  https://github.com/neovim/neovim/issues/18290#issuecomment-1118869396):
   > We could check for modified status by:
   > 
   > * compare file sizes
   > * if file sizes equal
   >   
   >   * if below some size (10 MB or something), compare hashes
   >   * else use mtime

**Comment by andmis** [comment]
Do we care about trying to upstream this to Vim?

**Comment by clason** [comment]
Sure, knock yourself out.

**Comment by justinmk** [comment]
> Do we care about trying to upstream this to Vim?

afair it was long ago rejected. Probably another option will be added or something.
