### ISSUE TITLE
menu_get should return commands usable "as-is"

### ISSUE THREAD

**Issue by teto** [neovim/neovim#7272]
the newly function menu_get returns commands without prettyprinting special characters such that `<esc>` ends up becoming \27 :
https://github.com/neovim/neovim/blob/3b45f676c0f07aa2826f191f555ba0d5f53e6d7c/test/functional/ex_cmds/menu_spec.lua#L110
It might be better for plugins to get the command as i `inormal<ESC>`. I hit the problem with my own plugin so it might be best changing it before 0.2.1. I can prepare a patch if that sounds sensible.

**Comment by justinmk** [comment]
Hmmm, makes sense I guess. @ZyX-I what's your opinion?

**Comment by ZyX-I** [comment]
My opinion is that the output should be

1. Consistent with nvim_get_keymap(), both lhs and rhs.
2. Unambiguous.
3. Mappable.
4. Mappable to.
5. Backwards compatible.
6. Feddable to `nvim_input()`.
7. Representable to the user.

This does not say it should be `<ESC>` or whatever, but not using `<>` means needing to have yet another representation format for things like `<F1>`, breaking either consistency or existing plugins relying on `nvim_get_keymap()` and requiring to have additional function like `String nvim_translate_keycodes(String)` (or the equivalent in the plugin code which is in many aspects worse) to make that representable to the user and feddable to `nvim_input()`.

**Comment by tjdevries** [comment]
I like `inormal<esc>`. I think it's idiomatic to the (neo)vim world.

**Comment by justinmk** [comment]
Sounds like we all agree. @teto if you have a patch we can block 0.2.1 for this.

**Comment by teto** [comment]
I am sorry but I have some trouble with my current setup; I recently switched to nixos ans while it's great, the lua ecosystem is completely unsupported and my neovim development workflow is kinda broken. Either we let it slip for a next release which would make the feature harder to use or a brilliant mind could takeover.
A patch should mostly consist of sthg like the following +  regenerate the menu test.
```
diff --git a/src/nvim/menu.c b/src/nvim/menu.c
index 0db250d11..a0aff0449 100644
--- a/src/nvim/menu.c
+++ b/src/nvim/menu.c
@@ -707,7 +707,12 @@ static dict_T *menu_get_recursive(const vimmenu_T *menu, int modes)
                        (menu->noremap[bit] & REMAP_NONE) ? 1 : 0);
         tv_dict_add_nr(impl, S_LEN("sid"),
                        (menu->noremap[bit] & REMAP_SCRIPT) ? 1 : 0);
-        tv_dict_add_dict(commands, (char *)&menu_mode_chars[bit], 1, impl);
+                 str2special();
+        // TODO might need to free the string afterwards
+        tv_dict_add_dict(commands,
+                        str2special_save((const char **)&menu_mode_chars[bit], from, false),
+                         1, impl
+                         );
       }
     }
   } else {

```

Sorry for that.
