### ISSUE TITLE
Feature request: file:line support from command line

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7274]
*Please correct me if my assumption that this cannot be implemented via a plugin isn't correct*

I would like to suggest adding support for opening a file and jumping to a line via the file:line_no syntax, so that `nvim foo.bar:42` from the command line would open foo.bar and jump to line 42.

filename:line_number is a defacto standard for representing locations in a project, and is emitted by a great number of linters, search tools, and more. It would be convenient if this shortcut could be supported by neovim.

Thanks for considering.

**Comment by chrisbra** [comment]
see #1281
