### ISSUE TITLE
How I can connect to remote RPC process via socket?

### ISSUE THREAD

**Issue by zdm** [neovim/neovim#7278]
Hi, guys.
This is not a bug report, just a question.
Can I connect to already running RPC process, using sockets?
I want to have single RPC, that can serve multiple neovim instances.
In vim I can use channels, but in neovim I can only spawn new job and communicate, using STDIN/OUT.
Is this correct, or I am missed something?
If this is true, do you have a plans to implement this functionality?

**Comment by bfredl** [comment]
What is an "single RPC"? Each nvim instance listens to one (or multiple, `serverstart()` ) sockets.

**Comment by zdm** [comment]
"single RPC" means single RPC process, that can be hosted anywhere and listening socket.
For example, usually I am using several vim windows and have single RPC, that provides source formatting, checking, cleanup and lot of other functionality. I don't want to run new instance of this RPC for each vim/nvim, because it requires a lot of resources and I will need to share some data between multiple processes, that will make everything more complex.

**Comment by bfredl** [comment]
Multiple clients have always been able to connect to the same nvim server instance.

**Comment by bew** [comment]
I think he wants 1 client to connect to multiple nvim server instances.

**Comment by zdm** [comment]
Yes, I understand this, but iI need to connect FROM nvim to the other process.

**Comment by justinmk** [comment]
@zdm for this you will need https://github.com/neovim/neovim/pull/6844 

And I think this is covered by an open issue, so closing this one.

**Comment by bfredl** [comment]
Everything concrete mentioned in this thread is already possible. #6844 improves non-RPC support.
