### ISSUE TITLE
Using :Explore in one window and clicking back in another tries to open the line as a file

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7284]
Sorry about the length of the title (and its ambiguity). Basically, if you use netrw in one window with `mouse=a` and then you click back in the other window, neovim attempts to open the contents of the line in the newly-clicked window as a path (but only if the contents match a certain pattern?)

```
neovim -u NORC /usr/share/dict/words
i
build .cache/themes_md5sum: md5sum bower_components/prism/themes | bower_components
#make sure there is no trailing new line, i.e. the cursor is on the same line as the text that was just entered
<ESC>
:set mouse=a
:vsp
# click in right window
:Explore
# click in left window
:!echo % 
#:!echo /home/mqudsi/build .cache/themes_md5sum: md5sum bower_components/prism/themes | bower_components
```

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/5375#issuecomment-249275732

Does it happen in vim with the same settings (mouse=a)?

**Comment by mqudsi** [comment]
No, does not reproduce in vim.

I don't think this is a duplicate of #5375 since this happens in normal mode while #5375 is in insert mode (and caused by insert mode).

**Comment by justinmk** [comment]
> No, does not reproduce in vim.

With `mouse=a` ... ?

**Comment by mqudsi** [comment]
Yup.

**Comment by mqudsi** [comment]
Scratch that, I spoke too soon. Simply clicking back in the first pane does not trigger the `gf`, but clicking on the text in the first pane does (in vim).

**Comment by mhinz** [comment]
I can't reproduce this on master anymore, so I consider this fixed unless someone says otherwise.

FWIW, master is on-par with Vim master runtime-wise now.
