### ISSUE TITLE
split() does not handle empty items correctly

### ISSUE THREAD

**Issue by xuhdev** [neovim/neovim#7288]
- `nvim --version`:
```
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-wew7PE/neovim-0.1.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-wew7PE/neovim-0.1.7/build/config -I/build/neovim-wew7PE/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include-I/usr/include -I/usr/include -I/build/neovim-wew7PE/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-wew7PE/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently? No
- Operating system/version: Debian Stretch
- Terminal name/version: gnome-terminal
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
Then, within nvim
```
:echo split('accb', 'c')
```

### Actual behaviour

Output `['a', '', 'b']`.

### Expected behaviour

Output `['a', 'b']`.

### Note

The document of `split()` reads

                Other empty items are kept when {pattern} matches at least one
                character or when {keepempty} is non-zero.

My understanding is that when `keepempty` is zero or not given, empty items are not kept.

**Comment by jamessan** [comment]
It's behaving exactly as the documentation you quoted states it should.

> Other empty items are kept when `{pattern}` matches at least one character

`{pattern}` is `'c'` in your example, and it matches at least one character.
