### ISSUE TITLE
Support attributes that contain `>` for the tag text object

### ISSUE THREAD

**Issue by andreiglingeanu** [neovim/neovim#7301]
- `nvim --version`: v0.2.1-885-g460aab395 (compiled master
- Vim (version: ) behaves differently? No, behaves the same
- Operating system/version: OS X
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

1. Go in INSERT mode `i`
1. Put `<div onClick={test => console.log(test)}>text</div>` into the empty buffer (note the `>` into the onClick attribute)
1. Go in NORMAL mode `C-c`
10. Put the cursor somewhere on the `div` tag and type `cit`

### Actual behaviour
You would see that the content would be, which is incorrect:

```
<div onClick={test =>|CURSOR_HERE|</div>
```

### Expected behaviour

```
<div onClick={test => console.log(test)}>|CURSOR_HERE|</div>
```

<hr>

I have tried to compile locally the editor itself and even succeeded at it. I do not have any idea on how to approach fixing/patching that incorrect behavior (which may make sense for those who are familiar with editor internals). Is there any way I could help getting that narrowed down at least? 

I could even try my hand at filling a pull request for this fix but I would need quite some assistance form someone in here.

This bug was observed [here](https://github.com/tpope/vim-surround/issues/136) too.

Thanks for considering that!

**Comment by justinmk** [comment]
One could always implement a custom text object in VimL, but this is really a Vim bug. Consider reporting it to https://github.com/vim/vim

Although, is that valid HTML? Shouldn't the `>` be `&gt;` ?

**Comment by andreiglingeanu** [comment]
I will definitely do that. Thanks!

I did considered implementing a custom text object but having that fixed from the roots of the problem would be best.
