### ISSUE TITLE
Session.vim does not restore the session correctly if arglist is utilized

### ISSUE THREAD

**Issue by DarkDeepBlue** [neovim/neovim#7304]
The argument list (arglist) holds the files provided to neovim via the comand line. If such a list is stored into the session file, it is not restored correctly. This leads to a certain corruption of the restored session.

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC -p file1 file2 file3 file4
```
Files appear in the correct order in the tabbar and also if issuing `:args`.
We create a session and exit neovim. Then, we restore the session again.
```
:mksession
:qa

nvim -S
```
The files appear now in a different order in the tabbar and also in the arglist, which can be verified by issuing `:args`. The first file is on its place, but the rest of the files are in reverse order. Filetypes and other settings are assigned to the files as if they were in the correct order.

In the above example this means that the arglist would be
```
[file1] file4 file3 file2
```
and `file4` would have the filetype of `file2`, `file3` would have its original filetype and `file2` would have the filetype of `file4`.

### Actual behaviour

While saving the session, `ex_mkrc()` is called in `ex_docmd.c`. It then calls `put_view()`, which in turn calls `ses_arglist()`, which stores the arglist to the session file. In order to do so, it puts the vim command `argadd` to the file. The documentation to that command says in particular:
> If [count] is omitted, the {name}s are added just
> after the current entry in the argument list.

This explains the current behaviour.

### Expected behaviour
We expect to put `$argadd` instead of `argadd` to the session file. This will add the files in correct order to the arglist while restoring the session. This is also what vim does in its session file.

I will submit a PR shortly.

**Comment by jamessan** [comment]
This sounds similar to an issue that may have already been fixed in Vim.  Can you check to see if it works there first?

**Comment by DarkDeepBlue** [comment]
I already checked that. Vim uses `$argadd` correctly and does not have this issue.
I will search the according commit in the vim repository.
It is actually only an addition of `$` in `ex_docmd.c:9381`.

**Comment by jamessan** [comment]
Ok, then you'll want to use `scripts/vim-patch.sh` to [merge](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) the patch into Neovim.

**Comment by DarkDeepBlue** [comment]
It is commit ``.
Thank you for your support.
