### ISSUE TITLE
Reduce number of alias to same command

### ISSUE THREAD

**Issue by alphaCTzo7G** [neovim/neovim#7318]
I suggested this to the main VIM branch, but thought this might be helpful to NeoVIM too.

https://github.com/vim/vim/issues/2157

What do you guys think about reducing the number of aliases available, trimming the number of commands open to users? It seesm VIM has a major issue of feature creep, which very few people use, but makes it harder and more confusing for new users...

**Comment by jamessan** [comment]
Removing commands from (n)vim with no justification other than "It's an alias for another command" doesn't help anyone.  All it does is risk breaking scripts that are using the commands.

**Comment by alphaCTzo7G** [comment]
Hi James,

Thanks for your careful comments..

Maybe I didnt clarify what I proposed, I detailed those in the original thread at VIM, and I thought a reference would be good enough, and poeple would read that refernece. I will try to explain a little better and also provided the original text below:

If I understand the philosophy/background of NeoVIM correctly, it seems NeoVIM is not necessarily trying to be backward compatible with VIM, and is similar to a hardfork.

In all software packages, there are always functions/classes/aliases deprecated over time, sometimes its to reduce complexity, UI etc etc.. What I proposed in the original thread is that we have a poll for a few months, to see which aliases are being used least. With such a poll, we can gain some understanding of what aliases are least used by users. Ofcourse, there is no gain without some pain. The point is to have highest amount of gain with the minimal amount of pain.  

Heres the original posting from the VIM site:

> I think for a opensource tool to gain wide audience going forward, especially in a competitive marketplace with sublimeText, atom, vscode, pycharm, IDEs all vying for the same/similar set of users, we need to make VIM easy to use for new users. Maybe when VIM/Vi started it was very easy to use, and the feature creep has made it more complicated. Nobody starts off as an expert user or contributor to VIM. Everybody will start off as a new user. Overtime as they find the product more useful, they will start using that product more and perhaps start contributing more towards making the product more successful for themselves as well as others. This is especially true for opensource software, where the producers and consumers of software is the same. If overtime, new users prefer to use sublimeText, atom, VScode over vim, the number of users of VIM will decrease, as a result, VIM will dive in popularity, the featureset will decrease which will result in fewer users preferring to use VIM over other products, and VIM will go in a downward spiral of death.
> 
> One simple thing that I noticed could help reduce a lot of confusion is to reduce the number of aliases. This would reduce the number of options available to the new user. I am guessing very few users use these options, if at all. Can we start cutting down on these aliases? Almost all the commands have tonnes of them. I posted an example screenshot below:
> 
> ![vim_alias](https://user-images.githubusercontent.com/29691914/30820162-f283e606-a1d5-11e7-8ae0-a1985ff40afd.png)

Some questions:

1. Do you think that the large number of aliases available from VIM help files makes it difficult and intimidating for new users?

2. If after running the poll for a few months, if instead of immediately removing the aliases, we put in a warning such that the users of the plugins or NVIM are alerted to the fact that that alias is deprecated, would that be a better approach?

3. Do you we should ask new users of NeoVIM/VIM about this rather than expert users? I would expect that the requirements/experience of expert users of VIM who are very familiar with VIM are very different from new users of VIM, especially when there are a lot of friendlier editors available.

4. Do you think we could re-open this issue, to see if other users feel the same way or not? If not, what medium do you think would be an appropriate place to discuss this?

Thanks for your comments and work in making (n)vim better.

**Comment by ZyX-I** [comment]
I think you do not understand what is going on there: there are *no* aliases to remove, this is simply a matter of how command finding is coded: in case of ambiguous match (like `:a` starting either `:all` or `:append` in addition to some others) it takes the first one from the list (which happens to be `:append` in this case). There is no way you can just go and remove any of the alternatives without a very huge refactoring and nobody wants to have this pain in ass for no real reason.

The second thing to consider is that you *must not* ask *users* of all people about removing aliases. Average user may happily agree on removing some particular alias until he realizes that his favourite plugin is using the one. For example, one of the rather popular plugins, ctrl-p, is coded like if his author was short on bytes: it is using shortest alias possible, sometimes ones which I will never use even when I type a write-only use-once one-liner. And I am not referring here to new/expert users, just any users: I am myself using a bunch of plugins I never saw source code of.

The third thing is that asking users such question is generally bad idea: not only they do not know all aliases which they happen to be using (which is not limited to plugins, but also to vimrc copy-pasted from the internet), they are mostly not proficient enough to give a useful advice on the usability. For such cases other methods were developed, though I only know about A/B testing (which returns to the first point, but worse: nobody will want to perform a huge refactoring which will be thrown away).

---

I have exactly no problems with those “aliases” until I come to reading some plugins’ sources which abuse the feature: my opinion is that plugins should prefer the longest form always, short form for some most common cases like `:syn` or `:hi` is allowed, but not a nightmare like ctrlp has. But these are rare, most common commands found in plugins are easily recognizeable even in shortests forms and in non-common cases there always is `:help`.

But unlike plugins “aliases” are rather useful when typing use-once one-liners, so I would not want them removed.

**Comment by ZyX-I** [comment]
Though big refactoring is only needed to make a thing efficient and implement white-list; simple black-list is easy: add a generated hash, add a check.
