### ISSUE TITLE
Vimscript/VimL expression extensions

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#7321]
While implementing #7234 I came up with a few ideas which may prove useful I think. I am not going to implement them right in #7234 though:

1. If you know about bash function exporting capability and how it evolved after shellshock then you may know that it now uses variables like `BASH_FUNC_foo%%`. Vim can’t process such variables (at least not without tainting &isident which does not look like a good idea, and dependency on &isident in VimL expressions is going to be removed in #7234 anyway), but neither Vim can swallow curly braces in pretty much anything, but regular variables. So proposal is to extend syntax so that `${"BASH_FUNC_foo%%"}` is allowed, though basically only adding support for curly braces names. This is backwards compatible - it is not going to make something which used to be a valid syntax rejected or change its meaning.
2. Add VAR_REGEXP. May be just something internal, used purely as optimization, or something available for the users who care about efficiency. In most places this shows just the same behaviour as VAR_STRING (also VAR_REGEXP concatenated with anything is VAR_STRING; be it another VAR_REGEXP or VAR_STRING), with the exceptions of certain built-in functions like `match()`, `type()` (if it is exposed to the user). (I am in any case going to try highlighting regexes as regexes, in #7234 or later if it proves too difficult to mess with the parsing part of regexp code.) If exposed, should introduce a new literal and additional function `re_compile :: VAR_STRING -> VAR_REGEXP`.
3. Add `try!(possibly_throwing_expr1[ ? regexp_expr9 -> catch_expr1[, regexp_expr9 -> catch_expr1…]][ : finally_expr1])`. This may prove useful for lambdas, but it is more useful for testing out exceptions implementation of VM or whatever will be executing expressions before it has chance to go for executing Ex commands; such testing is the main reason I want this.
4. Make comparison operators associative, with essentially the same semantic Python has (`a cmp b cmp c` equals `a cmp b and b cmp c`). Allows things like `if 0 <= x < 100`.

The amount of work needed in order from easiest to hardest should be 4 (may be as well marked as “entry level” I think), 1, 2, 3. 3 and 1 are what I think is actually needed for one reason or another.

**Comment by justinmk** [comment]
:+1: 

> The amount of work needed in order from easiest to hardest should be 4 (may be as well marked as “entry level” I think), 1, 2, 3. 

3 is the hardest?

**Comment by ZyX-I** [comment]
@justinmk Given that it is for whatever will be the new executor? It is the hardest because this thing is non-existent, syntax extension is not going to cause much troubles though, but even considering only additions to syntax `try!` is the most complex one: syntax-wise first needs only the acceptance of curly braces after `$…` token, second needs no or “just check whether `r` actually starts a string literal” addition to the lexer and a minor one to the parser which should be processing strings and regexes, third is the whole bloody new token `try!` and most likely sorting out operator precedence, fourth is just making comparison operators associative. (Considering the imaginary state of #7324 being finished.)

**Comment by lewis6991** [comment]
Improving vimscript is no longer a goal. Effort has redirected to improving the Lua domain.
