### ISSUE TITLE
Suggestion: expose uname as a variable

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7329]
This is just a minor feature request to expose the value of `uname -a` (from build time) as a statically compiled variable in a similar vein to `v:progpath` so that environment-sensitive plugins and configuration scripts can obtain that info without needing to execute an external command.

**Comment by jamessan** [comment]
There is no `uname -a` on Windows.

What information do you actually need?  Note that there are various `has()` checks that can be used to see what platform you're running on.  See `:help feature-list`.

**Comment by mqudsi** [comment]
It's with regards to setting the clipboard provider under WSL (https://github.com/neovim/neovim/issues/7031)

It's Ubuntu but it's not. I don't like neovim depending on the output of `uname` at run time to detect WSL whenever native clipboard support for WSL is merged.

**Comment by mqudsi** [comment]
Maybe this should just be a PR to add support for `has("wsl")`

**Comment by janlazo** [comment]
Can this feature check be included in regular Vim even if the implementation is different in Neovim?

**Comment by jamessan** [comment]
@janlazo Someone would need to send a patch to Vim.
