### ISSUE TITLE
Enhancement: native swap words feature

### ISSUE THREAD

**Issue by voyeg3r** [neovim/neovim#7347]
Easy text exchange operator for Nvim like in https://github.com/tommcdo/vim-exchange

### Actual behavior

If I want to exchange two words in neovim or vim, I have to:
yiw (jump to next word) viwp (jump back) viwp

This way I have a cumbersome task of taking two steps, thus it makes me press undo twice when I change my mind.

### Expected behavior
The plugin vim-exchange allows me to:

cxiw  (mark inner word to change - it highlights the word for change)
jump to the next word and press "." 

I can use undo in one step

### Why we need this?
Many other editors end up creating new features like multiple-cursors, org-mode, narrow-region and so on. It would be greaat to see neovim bringing to new users great ideas like this nativally. Many Emacs users brag about beating vimgolf challenges, although we know ergnomics also count.

**Comment by ZyX-I** [comment]
Exchanging is far easier then what you posted: delete current word, jump, paste. I do not see this job being too common and if it is already implemented with a plugin, why should it be in the codebase? C code is significantly harder to maintain.

**Comment by mschilli87** [comment]
@ZyX-I: Your delete-jump-paste approach might work to swap *adjacent* words, but when it comes to exchanging two words that have other text in between, I guess @voyeg3r's approach would be the 'easiest' way to do that without plugins.
