### ISSUE TITLE
Loading after/plugin/abolish.vim is very slow compared to vim

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#7348]
- `nvim --version`: 
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```
- Vim (version: ) behaves differently? yes
- Operating system/version: macOS 10.12.6 Sierra
- Terminal name/version: iTerm2 Build 3.1.20170928-nightly
- `$TERM`: `tmux-256color` in tmux otherwise `xterm-256color` 

---

I was profiling my neovim startup & found that one the biggest bottlenecks was [`after/plugin/abolish.vim`](https://github.com/ahmedelgabri/dotfiles/blob/ce5f60e8a54e55a870d4e6441c5d892e51af0312/vim/.vim/after/plugin/abolish.vim)

Here is some numbers from neovim & vim (I used [startuptime.vim](https://github.com/tweekmonster/startuptime.vim))

### Neovim:
<img width="442" alt="neovim-1" src="https://user-images.githubusercontent.com/63876/31057765-3b1860ce-a6e8-11e7-981a-a3908441e52f.png">
<img width="661" alt="neovim" src="https://user-images.githubusercontent.com/63876/31057764-3b17e040-a6e8-11e7-8210-88c574477712.png">
<img width="713" alt="neovim-2" src="https://user-images.githubusercontent.com/63876/31057766-3b2c2140-a6e8-11e7-99f2-c8ccd35cbc30.png">

### Vim:
<img width="401" alt="vim" src="https://user-images.githubusercontent.com/63876/31057775-51062cb8-a6e8-11e7-8c26-f1a098952ce2.png">
<img width="465" alt="vim-1" src="https://user-images.githubusercontent.com/63876/31057774-5105122e-a6e8-11e7-83be-9eead5f6b223.png">
<img width="708" alt="vim-2" src="https://user-images.githubusercontent.com/63876/31057776-51062010-a6e8-11e7-810d-ba6f227764f5.png">

So I wonder why it's very slow in neovim compared to vim & how can I reduce this if possible?

**Comment by ZyX-I** [comment]
You need to use `:profile` to get useful results, `--startuptime` is too imprecise to find a specific issue: run with `--cmd 'profile start /tmp/profile.log' --cmd 'profile func *' --cmd 'profile file *'` and check `/tmp/profile.log` after quiting or dumping profile.

**Comment by ahmedelgabri** [comment]
Thanks, I didn't know that `--startuptime` was not very accurate. So according to `:profile` it doesn't look like an issue at all.

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.226642   0.000986  <SNR>42_genesis()
    1   0.223749   0.001066  startify#insane_in_the_membrane()
   52   0.184624   0.001091  statusline#gitInfo()
   52   0.157095   0.000554  gina#component#repo#preset()
   52   0.156541   0.001155  <SNR>129_preset_fancy()
  156   0.146783   0.013003  gina#core#get()
  156   0.098638   0.004416  <SNR>137_get_from_bufname()
    4   0.095158   0.005505  provider#python#Call()
  156   0.094222   0.004916  <SNR>137_get_from_path()
    1   0.089652   0.000059  remote#host#Require()
    1   0.089593   0.089582  provider#pythonx#Require()
  156   0.089306   0.080804  <SNR>131_new()
   29   0.087337   0.001638  <SNR>130_import()
   29   0.085147   0.015270  <SNR>130__import()
    2   0.080363   0.000781  <SNR>127_display_by_path()
    2   0.079120   0.005141  <SNR>127_filter_oldfiles()
    1   0.078679   0.000047  <SNR>127_show_files()
   52   0.073374   0.000986  gina#component#repo#name()
    1   0.072859   0.003424  <SNR>127_init_env()
    1   0.068175   0.067802  <SNR>127_get_env()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1   0.089593   0.089582  provider#pythonx#Require()
  156   0.089306   0.080804  <SNR>131_new()
    1   0.068175   0.067802  <SNR>127_get_env()
   29   0.085147   0.015270  <SNR>130__import()
  156   0.146783   0.013003  gina#core#get()
  270   0.018286   0.011532  <SNR>152_match()
   18   0.032027   0.011069  projectionist#query_raw()
   17   0.025475   0.008687  <SNR>130__runtime()
   22              0.008678  <SNR>47_has()
    6   0.009856   0.006692  <SNR>130__sid()
   45   0.016706   0.006487  <SNR>44_expand_braces()
  156   0.008195   0.005595  <SNR>150_StatusForListFormat()
    4   0.095158   0.005505  provider#python#Call()
  376              0.005349  <SNR>39_addMapping2()
    9              0.005307  <SNR>130__redir()
    2   0.079120   0.005141  <SNR>127_filter_oldfiles()
  156   0.094222   0.004916  <SNR>137_get_from_path()
  156   0.098638   0.004416  <SNR>137_get_from_bufname()
  156   0.005046   0.004372  gina#core#buffer#parse()
  133              0.004192  <SNR>80_hi()

```
