### ISSUE TITLE
Airline corrupted themes

### ISSUE THREAD

**Issue by YanDoroshenko** [neovim/neovim#7361]
- `nvim --version`: `NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser`

- Operating system/version: Arch Linux
- Terminal name/version: Guake 0.8.10
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

1. Install powerline fonts
2. Install airline plugin
3. Add `let g:airline_powerline_fonts = 1` to `init.vim`
4. Launch Neovim 

### Actual behaviour
![image](https://user-images.githubusercontent.com/13915536/31307061-b1934bce-ab5c-11e7-9733-53bd5e485ed3.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/13915536/31307066-c6ccf382-ab5c-11e7-97eb-8545746e7219.png)

**Comment by justinmk** [comment]
Does it happen in Vim, and what's the exact version of Vim you tested?

Can you try master?

In general this is unlikely to be a Nvim bug. Nvim doesn't do anything with fonts.

**Comment by YanDoroshenko** [comment]
Tied Vim 8.0.1159, same stuff. Will try getting some help from the plugin developers.
