### ISSUE TITLE
Manual `:syntax on` required to get colors

### ISSUE THREAD

**Issue by hiqsol** [neovim/neovim#7365]
- `nvim --version`: 0.2.0
- Vim (version: 7/8) behaves differently? Yes
- Operating system/version: Ubuntu 16.04.3
- Terminal name/version: zsh
- `$TERM`: screen

Sorry for possibly known problem. I couldn't find answer here or in google.
I'm just trying to move from vim to nvim following exactly `:help nvim-from-vim`
I'm vim user for long time and I have substantial vim config with 20+ plugins.

### Actual behaviour

There are no colors in nvim just after start with `nvim`.
Then I do `:syntax on` and the colors get on.

### Expected behaviour

I have `syntax on` command in the very end of my `.vimrc`
So I want to have colors without running `:syn on` manually.

### 0.1.7 behavior

Works as expected - colors are on without manual `:syn on`, with exactly same config.

All config files available here:
https://github.com/hiqsol/dotfiles

**Comment by justinmk** [comment]
Maybe you need `:filetype plugin indent on` in the vimrc also?

> 0.1.7 ... Works as expected - colors are on without manual :syn on, with exactly same config

I can't think of anything in 0.2.0 that would have changed this.

> All config files available here: https://github.com/hiqsol/dotfiles

To get reduced steps, you need to bisect your config. Remove half of it, see if the problem is there, add half back, repeat, ....

**Comment by hiqsol** [comment]
Thanks for quick answer.

> Maybe you need `:filetype plugin indent on` in the vimrc also?

I have it and already played with it.

I'll try with bisect.

**Comment by hiqsol** [comment]
Strangely it was TERM...
I've changed TERM to xterm (was screen) and everything's ok now.

**Comment by justinmk** [comment]
@hiqsol please read https://neovim.io/doc/user/term.html#$TERM (available as `:help $TERM` in Nvim 0.2.1).

**Comment by hiqsol** [comment]
And now `brown` is displayed as `red`... In vim it's ok

Thank you for the link!
Playing with TERMs...
