### ISSUE TITLE
inccommand: plugin support ( :[range]normal , :global, ...)

### ISSUE THREAD

**Issue by bfredl** [neovim/neovim#7370]
Before implementing `incommand` for `:[range]normal` as more c code, I wanted to see how possible it was to implement as a plugin. The following piece of madness is the result https://github.com/bfredl/nvim-incnormal/blob/master/plugin/incnormal.vim It acually works quite resonable, as a "safeguard" it only activates for `:[range]norma ` spelled with exactly 5 letters (not `normal` or `norm` ). 

Given this, I think a reasonable way forward would be to add stuff to core to make inccommand plugins easier to implement. A checklist:

- [x] [CmdlineEnter and CmdlineLeave]( https://github.com/neovim/neovim/compare/master...bfredl:cmdlineenter?expand=1)
- [x] Callback for changed text. currently this abuses `g:Nvim_color_cmdline` + timers, which won't scale to more than one plugin.
- [ ] Even better: be able to register preview for commands in `cmd_can_preview`, which will invoke callbacks conditionally
- [ ] make the dedicated inccomand preview buffer and window accessible by plugin, so each don't need to manage their own. (imagine one implementation for `g/stuff` and one other takes over the buffer for `g/stuff/normal xx`)
- [ ] parsing commands without executing them would help (so one can identify  `:g/`, `g/stuff[/]` and `g/stuff/normal xx` without regex trickery)
- [ ] make more info of command execution available programatically. for instance for `:normal` list of changed lines and final cursor positions. I imagine this will have other uses as well.
- [x] #4419 would add convenience, though it can be faked with `<Expr>`+ timers
- [x] `:undo!` to not mess up `g+`/`g-` history
- [x] command for `undo_and_forget` => `:undo!` in https://github.com/neovim/neovim/pull/18157

**Comment by justinmk** [comment]
Probably makes sense to wait for @ZyX-I parser.

**Comment by bfredl** [comment]
@justinmk I didn't mean this to be a single PR that "enables incommand in plugins" and thus should "wait for the best time". Rather these plugins are already in some sense possible, if quite hacky and duplicated logic. We should instead think in small stepwise improvements.  A callback for "cmdline changed" conditioned  on what would be the command to execute is already possible with the current limited parsing abilities, after all incommand does this to identify substitution. ( CmdlineTextChanged is quite possible, but I wouldn't like 10 autocomands all trying to parse the cmdline in different ways at the same time)

**Comment by famiu** [comment]
> Before implementing `incommand` for `:[range]normal` as more c code, I wanted to see how possible it was to implement as a plugin. The following piece of madness is the result https://github.com/bfredl/nvim-incnormal/blob/master/plugin/incnormal.vim It acually works quite resonable, as a "safeguard" it only activates for `:[range]norma ` spelled with exactly 5 letters (not `normal` or `norm` ).
> 
> Given this, I think a reasonable way forward would be to add stuff to core to make inccommand plugins easier to implement. A checklist:
> 
>     * [x]  [CmdlineEnter and CmdlineLeave](https://github.com/neovim/neovim/compare/master...bfredl:cmdlineenter?expand=1)
> 
>     * [x]  Callback for changed text. currently this abuses `g:Nvim_color_cmdline` + timers, which won't scale to more than one plugin.
> 
>     * [ ]  Even better: be able to register preview for commands in `cmd_can_preview`, which will invoke callbacks conditionally
> 
>     * [x]  [[RFC] implement <Cmd> key #4419](https://github.com/neovim/neovim/pull/4419) would add convenience, though it can be faked with `<Expr>`+ timers
> 
>     * [ ]  make the dedicated inccomand preview buffer and window accessible by plugin, so each don't need to manage their own. (imagine one implementation for `g/stuff` and one other takes over the buffer for `g/stuff/normal xx`)
> 
>     * [ ]  `undo_and_forget` to not mess up `g+`/`g-` history
> 
>     * [ ]  parsing commands without executing them would help (so one can identify  `:g/`, `g/stuff[/]` and `g/stuff/normal xx` without regex trickery)
> 
>     * [ ]  make more info of command execution available programatically. for instance for `:normal` list of changed lines and final cursor positions. I imagine this will have other uses as well.

Update, `undo_and_forget` added in the form of `undo! in #18157
