### ISSUE TITLE
Documentation specifies incorrect `init.vim` path on Windows

### ISSUE THREAD

**Issue by BatmanAoD** [neovim/neovim#7374]
The documentation on [transitioning to nvim from vim](https://neovim.io/doc/user/nvim.html#nvim-from-vim) states that `~/.vimrc` should be symlinked or copied to `~/.config/nvim/init.vim`, when in fact (on my machine at least) NeoVim apepars only to look for `C:\Users\<username>\AppData\Local\nvim\init.vim` (which is typically `~/AppData/Local/nvim/init.vim`).

If the path changes depending on configuration or version, an easy way to check where NeoVim is looking for config files is `:echo &rtp`.

**Comment by janlazo** [comment]
Replace `~/config` with the value of `$LOCALAPPDATA` (or `%LOCALAPPDATA%` in cmd.exe) in Windows
