### ISSUE TITLE
Support for :Termdebug or any gdb integration

### ISSUE THREAD

**Issue by phcerdan** [neovim/neovim#7379]
- `nvim --version`: `v0.2.0`
- `vim --version`: `8.0 Included patches: 1-1159  with +terminal`

`vim` has added [:Termdebug](https://github.com/vim/vim/blob/master/runtime/doc/terminal.txt#L325) to integrate `gdb` in the terminal. I haven't really used it though, but are you planning to support this or something in this line with the `neovim` terminal? Is there any plugin using the integrated terminal with gdb?
I have been using the plugin [Conque-GDB](https://github.com/vim-scripts/Conque-GDB)  but mostly I run an external `gdb`. I am curious about any other approach to integrating a debugger in `neovim`. Thanks.

**Comment by jamessan** [comment]
`contrib/gdb/` has a similar plugin, but it's specific to debugging neovim.  It could probably be generalized.

**Comment by justinmk** [comment]
Integrating Vim's :Termdebug shouldn't be difficult , though the toolbar feature is a disappointment.

**Comment by mcepl** [comment]
With the merge of #8364 (even without the toolbar), shouldn't this be closed?
