### ISSUE TITLE
termguicolors + underline/bold: garbage escape sequence chars

### ISSUE THREAD

**Issue by xeyownt** [neovim/neovim#7381]
- `nvim --version`: NVIM v0.2.1-dev
- `dpkg -l | grep neovim`: 0.2.0ubuntu1+git201710092056+3676+26~ubuntu16.04.1
- Vim (version: ) behaves differently? Yes.
- Operating system/version: Ubuntu 16.04
- Terminal name/version: gnome-terminal/3.18.3-1ubuntu1, xterm/322-1ubuntu1
- `$TERM`: xterm-256color
- `$COLORTERM`: gnome-terminal

### Steps to reproduce using minimal `.vimrc` + minimal `.vim`
(edit 1: Add dependency on ~/.vim/after/syntax/c.vim)
(edit 2: Removed dependency on any plugin/colorscheme)

* The minimal `.vimrc`:
``` vim
if has('nvim')
  set termguicolors
endif
hi! Normal gui=NONE cterm=NONE guifg=#657b83 ctermfg=11 guibg=#fdf6e3 ctermbg=15
hi! MatchParen gui=NONE,underline,bold cterm=NONE,underline,bold guifg=#dc322f ctermfg=1 guibg=#eee8d5 ctermbg=7
" The 2 following lines here or in ~/.vim/after/syntax/c.vim
syn match cBraces display "[{}]"
hi def link cBraces Delimiter
```
Optionally, the last 2 lines above can be moved into `~/.vim/after/syntax/c.vim`.

* Create a file named `tmp.c`, containing 128 lines full of stuff, like:
``` bash
for((j=0;j<128;j++)); do echo "{ $(for((i=0;i<17;i++)); do echo -n '0x00, '; done) }"; done > tmp.c
```

* Maximize terminal window (it must display at least 50 lines or such).

* Edit the file:
```
nvim tmp.c
```

### Actual behaviour

We see garbage (escape sequence character):
* In xterm:
```
{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
{ 0x00, 0x00, 0x00, [?25l255m0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
```
![image](https://user-images.githubusercontent.com/16546024/31531596-484f33c2-afe8-11e7-8f89-0b33411fbe4c.png)

* In gnome-terminal:
```
40 { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
41 { 0x00, 0x00, 0x00, 0x00?38:2:101:123:131m, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
42 { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, }
```
![image](https://user-images.githubusercontent.com/16546024/31531460-8b3e4200-afe7-11e7-9151-d6e98ad7d9bd.png)
The garbage appears in black when using file `.vim/after/syntax/c.vim`. Otherwise it will appear in the same color as surrounding text.

### Expected behaviour

There should be no garbage character

### Analysis
* The garbage is always at the same position.
* The bug does not occur when reducing the number of characters on the line. For instance, the bug disappear if we use `i<16` in the bash line to generate tmp.c. But it comes back with `i<16` when using `set numbers` for instance. So it looks like an overflow bug.
* The bug does not occur when removing the last line in minimal .vimrc, or removing `underline` like in:
```
hi! MatchParen gui=NONE,bold cterm=NONE,bold guifg=#dc322f ctermfg=1 guibg=#eee8d5 ctermbg=7
```

**Comment by xeyownt** [comment]
For info, I have another system with same .vimrc config but different OS that does *not* have the issue:
* Debian stretch 9.0
* Neovim 0.2.0debian1-git20170619123516 (build from source, commit date/time)
* xterm 327-2.

**Comment by justinmk** [comment]
In 0.2.1, check `:help $TERM` and try with the TERM value recommend there for your terminal. xterm-foo is not recommend for gnome terminal.

**Comment by xeyownt** [comment]
I checked TERM value and tried all suggested values, but to no avail.

I however pushed further because indeed I had some issues to get the truecolors/italics/cursor to work correctly on my laptop. In fact, my minimal .vimrc above was not enough because I forgot to remove my .vim. 

So I searched further the culprit in my .vim/ folder, and it was a `after/syntax/c.vim` plugin. I updated the minimal config above. The setting is the one that sets the highlight for the braces, exactly the one for which underline is enabled.

My guess is that maybe neovim loads the settings asynchronously, and the setting kicks in while displaying the file, and maybe this corrupt the display (this is *wild* *wild* guess ;-) ).

**Comment by justinmk** [comment]
I guess your terminfo file(s) are missing the entry for underline, and the one we have built-in is wrong.

**Comment by xeyownt** [comment]
I had some difficulty to reproduce the bug on another laptop (almost identical) with my minimal config + after/syntax files above.

However it helps to pgdn/pgup in the tmp.c file. After some tries, we see that the garbage appears in the middle of the screen.

Regarding terminfo, please not that underline works (they are displayed).

**Comment by rhssk** [comment]
Having a similar issue here. NVIM v0.2.1-922-g01487d438 on termite v12-37-g68b92d3 (tried xterm, rxvt, gnome-terminal as well, same problem). No issues when using VIM the the same config.
Minimal config:
```vim
call plug#begin()
Plug 'morhetz/gruvbox'                                                  
call plug#end()
set number
colorscheme gruvbox
````
After resizing the window some characters are displayed in wrong places and statusline tends to jump to the top if resizing is done at the end of file.
From [https://i.imgur.com/6GoTD2E.png](https://i.imgur.com/6GoTD2E.png) to [https://i.imgur.com/xctNkUz.png](https://i.imgur.com/xctNkUz.png)
From [https://i.imgur.com/RaePFkd.png](https://i.imgur.com/RaePFkd.png) to [https://i.imgur.com/cfi1PcE.png](https://i.imgur.com/cfi1PcE.png)

Issue disappears after removing `set number`

**Comment by xeyownt** [comment]
I edited the first post to _minimalize_ further the `.vimrc` to remove all dependency on external plugins. The use of `.vim/after/syntax/c.vim` is now optional (the effect is to change the color of the garbage).

I also added two _screenshots_ of the issue.

**Comment by justinmk** [comment]
Maybe @jdebp could comment.

**Comment by justinmk** [comment]
This may be related to the "bce" terminal capability. Can you try https://github.com/neovim/neovim/pull/7624 ?

**Comment by xeyownt** [comment]
Hi Justin,
Just tried commit 0b93bab from your fork, but still get similar issue.

I noticed some changes though (from git201710092056+3676, aka v3676). In v3676 and xterm, the garbase message is `[?25l123:131m`, whereas in commit 0b93bab, the message is now only `123:131m`. This is not the only message, but with the new commit, the garbage are always shorter.

I don't see any changes in gnome-terminal though (even when changing TERM).

Also, it is not always easy to reproduce the problem. In fact one should make the test file bigger (like 1280 lines), and press and maintain PgDn, then PgUp keys.

``` bash
for((j=0;j<1280;j++)); do echo "{ $(for((i=0;i<17;i++)); do echo -n '0x00, '; done) }"; done > tmp.c
```

**Comment by justinmk** [comment]
This is a regression of #3875 which was fixed by #5436.

Possible causes are de8a9f6c338b and/or cdfaecb25f6a .

**Comment by sherzinger** [comment]
I'm not involved in the development, but I want to help getting this fixed.
This is what I can see:

current HEAD: can reproduce issue
git checkout 2c236fc\~1: can reproduce issue
git checkout cdfaecb\~1: **cannot** reproduce issue

Hope this helps!

**Comment by cstrahan** [comment]
FWIW, I can confirm that:

* cdfaecb~1 **doesn't** reproduce the issue
* cdfaecb **does** reproduce the issue

**Comment by xeyownt** [comment]
I just upgraded to a recent build and confirm that the issue is fixed for me as well.
