### ISSUE TITLE
How can we specify a custom clipboard provider?

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#7385]
I looked at `:help provider-clipboard`, but it doesn't say much.

I'm in Chrome OS Crouton (Ubuntu chroot), and I can copy text from the command line like this:

```
> echo hello | croshclip -copy
```

then I can `ctrl+v` to paste in Chrome OS apps. 

Is there some way I could set `croshclip -copy` as the clipboard provider?

I know I can just `map yy`, etc, but that doesn't feel clean.

**Comment by justinmk** [comment]
A custom provider can be made by putting some other provider on the runtime path, which overwrites the existing one. To override the existing clipboard provider it would need to be at `autoload/provider/clipboard.vim` somewhere on the runtime path.

But that's a lot of work/duplicate effort, so Nvim 0.2.1 offers the `g:clipboard` option. Read `:help g:clipboard` and replace the `tmux ...` values with the equivalent values for the tool you want to use.

**Comment by trusktr** [comment]
Is this a new neovim-only feature?

**Comment by trusktr** [comment]
Oh I see, 0.2.1 is a pre-release. Looking forward to it!
