### ISSUE TITLE
Nvim leaves stale socket when xterm is closed

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#7386]
- `nvim --version`: v0.2.0
- Vim (version: ) behaves differently? Does not apply.
- Operating system/version: RHEL6, ancient stuff
- Terminal name/version: xterm from X.Org 6.8.99.903(253)
- `$TERM`: xterm

I'm using neovim-remote to have nvim connect to a socket. This mostly works well, except when I close the xterm that holds nvim by clicking on the little 'x' in the upper right corner. In that case, nvim leaves the socket behind, without anything connected to it. I've talked a bit with @mhinz on gitter about that, and he agrees that this is something that should not happen.

I'm not sure what other info I should give, let me know if something's missing.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/3517

**Comment by justinmk** [comment]
can't reproduce. Tested by running a nested `nvim` inside `:terminal` then `:bwipe!` the terminal.
