### ISSUE TITLE
"hasmapto" returning wrong information

### ISSUE THREAD

**Issue by phmarek** [neovim/neovim#7387]
- `nvim --version`:   v0.2.1-946-g91de5a79f
- Vim (version: ) behaves differently? no idea, seems to be a bug in nvim
- Operating system/version: Linux, Debian AMD64
- Terminal name/version: tmux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
Not sure. Not that easy to reproduce.

Using the "vlime" plugin I have the problem that <tab>-completion (in insert mode) doesn't work in a buffer; at the same time it works in another buffer.

I could find out that the difference is an `:imap` mapping.

### Actual behaviour
```
:imap
i  <CR>        *@<CR><C-R>=vlime#plugin#VlimeKey("cr")<CR>
i  <Space>     *@<Space><C-R>=vlime#plugin#VlimeKey("space")<CR>
i  <C-Space>   * <C-X><C-O><C-P>
i  <Nul>         <C-Space>
i  <Up>        * pumvisible() ? "\<C-P>" : "\<Up>"
i  <S-Tab>     * pumvisible() ? "\<C-P>" : "\<S-Tab>"
i  <Down>      * pumvisible() ? "\<C-N>" : "\<Down>"
!  <SNR>47_(restore-marks) * <SNR>47_restore_marks()
!  <SNR>47_(save-marks) * <SNR>47_save_marks()
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
i  <C-^>         <C-O><C-^>
:echo hasmapto('i', '<C-R>=vlime#plugin#VlimeKey("tab")<CR>')
1
```

### Expected behaviour
```
:echo hasmapto('i', '<C-R>=vlime#plugin#VlimeKey("tab")<CR>')
0
```

That would make the detection in `vim/autoload/vlime/ui.vim` whether the command is already mapped to a key see that there's no key mapping set yet, and so it should be created.

Hmmm, actually
```
:echo hasmapto('i', 'fasdfsafda')
1
```
so it seems to be a more general problem.

**Comment by bew** [comment]
(please use ```` ``` ```` around code blocks)

**Comment by phmarek** [comment]
Update: I've got the order of `hasmapto` arguments wrong in my transcription.
Using the right order gives the correct return codes in the running instance right now.

The script correctly uses `hasmapto(a:cmd, a:mode)`, but still doesn't "repair" the mapping when asked to re-map the keys.

Manually overriding via a `:imap` commandline works, though.

**Comment by phmarek** [comment]
Ok, some more investigation gives a bit more data.

Upon starting nvim with a lisp file my `:imap` shows this:
```
i  <Tab>       *@<C-R>=vlime#plugin#VlimeKey("tab")<CR>
i  <CR>        *@<CR><C-R>=vlime#plugin#VlimeKey("cr")<CR>
i  <Space>     *@<Space><C-R>=vlime#plugin#VlimeKey("space")<CR>
i  <C-Space>   * <C-X><C-O><C-P>
i  <Nul>         <C-Space>
i  <Up>        * pumvisible() ? "\<C-P>" : "\<Up>"
i  <S-Tab>     * pumvisible() ? "\<C-P>" : "\<S-Tab>"
i  <Down>      * pumvisible() ? "\<C-N>" : "\<Down>"
!  <SNR>47_(restore-marks) * <SNR>47_restore_marks()
!  <SNR>47_(save-marks) * <SNR>47_save_marks()
i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
i  <C-^>         <C-O><C-^>
```

`<tab>` is mapped to `Vlime` - but the other mapping from `YouCompleteMe` is shown at the same time.

Later on, on opening another file, it looks like only the `pumvisible` keybinding is set in the new buffer/window; while `Vlime`s `if !hasmapto(a:cmd, a:mode)` clause still says "binding needed", the `if len(maparg(kk, a:mode)) <= 0` line sees that `<tab>` is already in use and won't set the right binding.

Now the questions are -- what are the `*` and `@` flags in the `:imap` output? Are two bindings to the same key allowed at all?
Further on there'll be -- why is only one binding active in the new window, or is the second binding lost at some time?

I guess that one good change would be to not care about existing bindings to the given key... just set it. This should at least help a bit.

**Comment by justinmk** [comment]
Buffer local mapping.
