### ISSUE TITLE
Cannot highlight text with mouse after adding a tab 

### ISSUE THREAD

**Issue by JuanPotato** [neovim/neovim#7390]
- `nvim --version`:  v0.2.0
- Vim 8.0 behaves differently: The expected behaviour occurs
- Operating system/version: Arch Linux
- Terminal name/version: rxvt-unicode (urxvt) v9.22
- `$TERM`: rxvt-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set mouse=a
:tabe
```
Now highlight something by click + dragging.
**It selects text as it should.**
Now click with your mouse on a tab to change tabs.
Try highlighting text, it doesn't work.

### Actual behaviour
It moves the current tab right or left.

### Expected behaviour
Text to highlight like before

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/5400

Use something other than rxvt.
