### ISSUE TITLE
nvim.appimage not working in Ubuntnu 16.04

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#7391]
I'm in Ubuntu 16.04.3, and I get this:

```js
❯ ~/Downloads/nvim.appimage 
/home/trusktr/Downloads/nvim.appimage: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory
```

**Comment by justinmk** [comment]
See https://github.com/AppImage/AppImageKit/issues/12#issuecomment-56594521 AppImage expects libfuse to be installed by default. Try `sudo apt install libfuse2`.

**Comment by justinmk** [comment]
Will re-open if more information becomes available.
