### ISSUE TITLE
Swap file dialog does not offer (D)elete option without discernible reason

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7397]
- `nvim --version`: v0.2.1-915-g01e53a5
- Vim (version: ) behaves differently? unknown
- Operating system/version: Linux/WSL (N/A)
- Terminal name/version: Conhost (n/a)
- `$TERM`: xterm-256color (n/a)

### Steps to reproduce using `nvim -u NORC`
Unclear

### Actual behaviour
Sometimes the swap file dialog does not offer a delete option:

```
E325: ATTENTION
Found a swap file by the name "~/.local/share/nvim/swap//%mnt%c%Users%Mahmoud%Downloads%fish here.reg.swp"
          owned by: mqudsi   dated: Sun Oct 15 09:41:53 2017
         file name: /mnt/c/Users/Mahmoud/Downloads/fish here.reg
          modified: no
         user name: mqudsi   host name: ZBook
        process ID: 12214 (still running)
While opening file "./fish here.reg"
             dated: Mon Sep 25 00:13:22 2017

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r ./fish here.reg"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/home/mqudsi/.local/share/nvim/swap//%mnt%c%Users%Mahmoud%Downloads%fish here.reg.swp"
    to avoid this message.

Swap file "~/.local/share/nvim/swap//%mnt%c%Users%Mahmoud%Downloads%fish here.reg.swp" already exists!
```

### Expected behaviour
It's unclear why sometimes the delete option is there and sometimes it is not. In the case where the swap file is unmodified (#7137 aside, which would probably obviate this discussion entirely), why would the option to delete not be present?

(This was a swap file that was created when I aborted an exit session for a large file without modifying it at all.)

**Comment by chrisbra** [comment]
> 12214 (still running)

that's why

**Comment by justinmk** [comment]
Tossing this in with https://github.com/neovim/neovim/issues/1455
