### ISSUE TITLE
help syntax don't support help tags with unicode characters

### ISSUE THREAD

**Issue by mildred** [neovim/neovim#7402]
Here is defined the syntax highlighting pattern for help tags:

https://github.com/neovim/neovim/blob/2f4647e77b7e8271aad1b45eb07fbabed78d9fe6/runtime/syntax/help.vim#L22-L24

This pattern doesn't match utf-8 unicode characters. More specifically, the `[`...`+-~]` matches the pure ASCII alphabet but not any alphabetic character beyond that. Specifying negative character class using `[^ "*\t]` instead of `[#-)!+-~]` would match all unicode charactes (and control characters, but those are not supposed to be present in text files except for tabs)

A ASCII table would show that out of the `#`-`)` range, and out of `+`-`~` with the `!` character excluded there are only control characters below 32, space ` `, double quote`"`, and the star `*`

**Comment by mildred** [comment]
Note that the `:helptags` commands already supports tags with unicode characters.

**Comment by mildred** [comment]
I am using this in my vimrc:

```
augroup vimrc_filetype_help
  au FileType help syn match helpHyperTextJump	"\\\@<!|[^ \þ!*]\+|" contains=helpBar
  au FileType help syn match helpHyperTextEntry	"\*[^ \t!*]\+\*\s"he=e-1 contains=helpStar
  au FileType help syn match helpHyperTextEntry	"\*[^ \t!*]\+\*$" contains=helpStar
augroup END
```

**Comment by justinmk** [comment]
We don't want to fork the Vim runtime plugins in most cases (especially syntax plugins), unless there's a very good reason. Because if Vim changes something in the same file, it takes time to figure out the differences.

Probably this change will be accepted at https://github.com/vim/vim, could you report it there?

**Comment by justinmk** [comment]
this was rejected at https://github.com/vim/vim/issues/2213 , and we're not going to diverge here, since we merge Vim's runtime updates. And this can be overridden in one's vimrc as shown above.
