### ISSUE TITLE
<M-"> mapping does not work

### ISSUE THREAD

**Issue by lePerdu** [neovim/neovim#7410]
- `nvim --version`:
NVIM v0.2.0
Build type: Release

- Vim (version: 8.0) behaves the same?
- Operating system/version:
  Voidlinux/rolling release
- Terminal name/version:
  Termite/v12-34
- `$TERM`:
  xterm-termite

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:imap <M-"> metaquote
```

### Actual behaviour
The key combination (in insert mode) Alt-quote (Alt-Shift-apostrophe) does nothing while typing the literal characters sequence `<M-">` triggers the mapping and inserts `metaquote`.

### Expected behaviour
The key combination Alt-quote triggers the mapping and inserts `metaquote`

### Description
This issue appears in the AutoPairs repository (jiangmiao/auto-pairs#187) but I didn't see it here. The output of `:imap` shows the mapping in a different color, indicating that it is literal text instead of a special character (as opposed to the same mapping with a single quote, which works correctly).

**Comment by justinmk** [comment]
Confirmed (with `:inoremap`). Seems specific to `"`. Weird.

**Comment by lePerdu** [comment]
Searching the code, there is a test for it (bottom on [src/nvim/testdir/test_mapping.vim](https://github.com/neovim/neovim/blob/master/src/nvim/testdir/test_mapping.vim)), so it may work on some terminals, as I would assume it worked for whoever put it there.

**Comment by justinmk** [comment]
I don't think it's terminal-related. `<C-V><M-">` in bash (outside of nvim) correctly prints `^["`.

And using the Nvim API to send input doesn't trigger the mapping:

    :call nvim_input('<M-">')

so this means there's a bug, most likely in `keymap.c` or `getchar.c`.

**Comment by justinmk** [comment]
For reference, this affects TUI because we translate raw input into Vim keycodes in `tui/input.c:forward_modified_utf8()` :

     termkey_strfkey(input->tk, buf, sizeof(buf), key, TERMKEY_FORMAT_VIM);

then it is sent to `input_enqueue()`. 

#7411 is the correct fix, thanks @lePerdu !
