### ISSUE TITLE
Kaspersky delete the NVIM.exe from folder for twice - File hash should be provided

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7415]
- `nvim --version`:v0.2.1-1031-g91586d1
- Vim (version: ) behaves differently? 
- Operating system/version: Windows 10
- Terminal name/version: CMD
- `$TERM`:

### Actual behaviour
Kaspersky delete NVIM.EXE from the folder
### Expected behaviour
I have download twice from github release page. I have checked for the hash as follows:
```
b171150c64c366b794123e972924e5d3c6415f9b4799ca0a957286359630f6825f51baf0b08bc8611f7c87b317ec25eaa3c5845abae7bf7be69d850a2d7ec491 *nvim-win32.zip
```
File info is:
```
NVIM v0.2.1-1031-g91586d1
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-1341.local

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```
Please check whether the files was **tampered**. 

My Kaspersky Internet security delete the file for twice, rescan and restart the system. After that, I found no nvim.exe in the Neovim\bin folder.

Should the hash/signature be given for the downloads?

Thanks

Regards

TN

**Comment by jamessan** [comment]
You state your OS is Windows 10 and mention nvim.exe, yet your "File info" is from an OSX build.  That's confusing.

Regardless, there's nothing we can do about what the fact that Kaspersky software is deleting the binary.

**Comment by duytrung** [comment]
The file info was displayed as it was in the github releases page. I just copy it down here.

**Comment by duytrung** [comment]
![image](https://user-images.githubusercontent.com/2046672/31800441-77e08e4c-b588-11e7-9939-f0b7ac051e3b.png)
