### ISSUE TITLE
Installation instruction for Ubuntu Artful don't work.

### ISSUE THREAD

**Issue by retorquere** [neovim/neovim#7418]
Working from [these instruction](https://github.com/neovim/neovim/wiki/Installing-Neovim) on the wiki:

```
sudo add-apt-repository ppa:neovim-ppa/stable
```

creates `neovim-ppa-ubuntu-stable-artful.list` with

```
deb http://ppa.launchpad.net/neovim-ppa/stable/ubuntu artful main
# deb-src http://ppa.launchpad.net/neovim-ppa/stable/ubuntu artful main
```

but when I run `apt-get update` I get a 404 error. Replacing `artful` with `zesty` in the file resolves the error.

**Comment by justinmk** [comment]
Artful was just released about 5 seconds ago. Package updates don't happen immediately, it will become available as part of the normal PPA process. 

https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

**Comment by jamessan** [comment]
Artful also has the current neovim release -- https://packages.ubuntu.com/artful/neovim.

**Comment by jesstelford** [comment]
It looks like Artful only has 0.2.0, not 0.2.1.

Given that the installation instructions don't work:

```
[...]
❯ sudo apt-get update
[...]
Err:7 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu artful Release          
  404  Not Found
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
[...]
```

Is there any way to get 0.2.1 without building from source?

**Comment by jamessan** [comment]
> It looks like Artful only has 0.2.0, not 0.2.1.

Yes, because 0.2.1 was only released a couple days ago, but Artful was released a few weeks ago.

> Is there any way to get 0.2.1 without building from source?

Give us some time to get the PPA updated, use the AppImage, or build from source.  When you're not using the development release of a Linux distribution, it takes time to get updates.

I'm working through [issues](https://github.com/neovim/neovim/issues/7522) that have come up in Debian and will update the PPA after those are resolved.

**Comment by jesstelford** [comment]
No worries, thanks for the help 👍

Keep up the really great work - loving neovim 🎉
