### ISSUE TITLE
Replace substitute command with surround command [Feature Request] 

### ISSUE THREAD

**Issue by wongjiahau** [neovim/neovim#7421]
## Introduction
To be honest, after a few months of using Vim, I found myself not really using the `s` key. Because I could simply use `xi` to achieve the samething.   

## What I was looking for 
I was hoping that the **surround** feature could be integrated inside Vim by default. Yes, although there is a surround-vim extension written by T-pope, I still thought some of the command is not really natural. For example, to surround a word with bracket I need to type `ysawb` which is not really intuitive because `y` stands for `yank` (to copy a word).

## Suggestion
Therefore I suggest to allow an options such as `allow-surround` which would turn `s` key into the following commands : (all of them are in Normal mode)    

| Description                                 | Mode   | Command       | Example                                  |
|---------------------------------------------|--------|---------------|------------------------------------------|
| Surround a word with bracket                | Normal | sawb          | `hello => (hello)`                       |
| Surround a line with bracket                | Normal | ssb           | ` This is a line => (This is a line)`    |
| Surround two words with bracket             | Normal | s2wb          | ` two words => (two words)`              |
| Surround a word with symbols (such as ")    | Normal | saw"          | `hello => "hello"`                       |
| Surround a line with symbols (such as ")    | Normal | ss"           | `This is a line => "This is a line"`     |
| Surround a word with tag                    | Normal | sawt<tag><CR> | `hello => <tag>hello</tag>`              |
| Surround two words with symbols (such as ") | Normal | s2w"          | `two words => "two words"`               |
| Delete surround                             | Normal | ds"           | `"surrounded words" => surrounded words` |
| Visual select inside surround               | Normal | vis           | -                                        |
| Delete inside surround                      | Normal | dis           | `" word " => ""`                         |
| Yank inside surround                        | Normal | yis           | -                                        |
| Surround a selection with a symbols         | Visual | s"            | -                                        |
| Surround a selection with tag               | Visual | st<tag><CR>   | -                                        |
## Conclusion
This will make the `s` command more useful. 
By the way, the most wanted feature is to surround **visually selected words** with something.

**Comment by justinmk** [comment]
`vis` doesn't work, it's used for the "sentence" text object (`:help is`).

Not opposed to building-in surround-like functionality if someone sends a PR that isn't just a plugin dumped into the runtime, and has full test-coverage.

More generally, this discussion is much more involved than just figuring out mappings. So forget about discussing mappings at all, until code is written to actually add "surround" feature.

**Comment by ZyX-I** [comment]
surround.vim *does* provide a way to surround visually selected something. And `xi` is *not* a replacement for `s`, try `sfoo<Esc>j.` vs `xifoo<Esc>j.`, then undo in both cases.

**Comment by wongjiahau** [comment]
@ZyX-I Is that a frequent use case?

**Comment by wongjiahau** [comment]
@justinmk But to be honest, when had you actually used `is` ?

**Comment by wongjiahau** [comment]
@ZyX-I Do you mind to give me a reference on that? That would be great because I wanted that feature.

**Comment by ZyX-I** [comment]
@wongjiahau All you need is searching for `visual` in surround.vim documentation.

**Comment by wongjiahau** [comment]
@ZyX-I Thanks dude!! That's the reason why i brought up this issue actually
