### ISSUE TITLE
test/unit: `cimport` breaks on "__float128"

### ISSUE THREAD

**Issue by lePerdu** [neovim/neovim#7423]
- `nvim --version`:
NVIM v0.2.1-1032-g82c3d76ee
Build type: Debug

- Operating system/version: Voidlinux/rolling release

### Steps to reproduce

```sh
make distclean && make && make unittest
```

### Actual behaviour
The following error occurs (before any tests are run):
```
./test/unit/helpers.lua:256: declaration specifier expected near '__float128' at line 386
/home/user/workspace/neovim/.deps/usr/bin/luajit: ...rkspace/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:99: attempt to concatenate local 'message' (a table value)
stack traceback:
	...rkspace/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:99: in function 'fn'
	...ch/workspace/neovim/.deps/usr/share/lua/5.1/mediator.lua:103: in function 'publish'
	....deps/usr/share/lua/5.1/busted/modules/helper_loader.lua:21: in function 'helperLoader'
	...rkspace/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:147: in function <...rkspace/neovim/.deps/usr/share/lua/5.1/busted/runner.lua:11>
	...deps/usr/lib/luarocks/rocks/busted/2.0.rc12-1/bin/busted:3: in main chunk
	[C]: at 0x00404320
```

### Expected behaviour
The unit tests will be run.

### Other information
The same error occurs if I build with local libraries (not the ones installed into the `.deps` directory) or if I run `ffi.cdef('typedef __float128 _Float128;')` from a luajit prompt.

**Comment by justinmk** [comment]
Weird. Looks like a busted bug. Does `make functionaltest` work?

**Comment by lePerdu** [comment]
Yes. The other tests work. The error comes from ffi not recognizing the type `__float128` (a GNU extension, I think)

**Comment by justinmk** [comment]
Right, I should have read more carefully. Our `cimport` needs to be adjusted for this new edge-case.

**Comment by lePerdu** [comment]
I tried a couple things and looked through the `gcc` documentation and some standard library headers but as far as I can tell there is no way to disable `__float128` (the `-mno-float128` option is only for PowerPC and throws an error on x86) or its use in standard library function/type definitions.

The unit tests run fine when using `clang` (which does not have `__float128`, at least by default).

**Comment by jamessan** [comment]
Does this help at all?

```diff
diff --git i/test/unit/helpers.lua w/test/unit/helpers.lua
index 4b9f18515..ac5e394a5 100644
--- i/test/unit/helpers.lua
+++ w/test/unit/helpers.lua
@@ -138,6 +138,7 @@ local function filter_complex_blocks(body)
   for line in body:gmatch("[^\r\n]+") do
     if not (string.find(line, "(^)", 1, true) ~= nil
             or string.find(line, "_ISwupper", 1, true)
+            or string.find(line, "_Float128")
             or string.find(line, "msgpack_zone_push_finalizer")
             or string.find(line, "msgpack_unpacker_reserve_buffer")
             or string.find(line, "UUID_NULL")  -- static const uuid_t UUID_NULL = {...}
```

**Comment by lePerdu** [comment]
Yes, that fixes it.
