### ISSUE TITLE
conhost color corrupted on line scroll

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7425]
- `nvim --version`: NVIM v0.2.1-1046-gd7594f9
- Vim (version: ) behaves differently? n/a
- Operating system/version: Windows 10 1709 (build 17017.1000)
- Terminal name/version: conhost
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

This is either a regression or a bug that only appears on the latest builds of Windows 10.

```vim
nvim -u NORC /usr/include/c++/7/chrono
:set ft=cpp
:set mouse=a
# scroll down a line or two with the mouse/trackpad/crtrl+e
```

### Actual behaviour

Initial screenshot before scroll:

![image](https://user-images.githubusercontent.com/606923/31858048-cad3c4a8-b6b3-11e7-82fe-778c6f42186f.png)

After scroll:

![image](https://user-images.githubusercontent.com/606923/31858049-d264f16a-b6b3-11e7-83e7-1e648076543e.png)

Pressing ctrl+l to clear the background corrects the display.

### Expected behaviour

The coloration is not corrupted on scroll. Using ctrl+b/ctrl+f does not result in the same behavior. (Mouse scroll is obviously the same behavior as simply ctrl+y/ctrl+e/ctrl+j/etc)

**Comment by mqudsi** [comment]
Putty does not display this bug, but [terminus](https://github.com/Eugeny/terminus) does. Checking out v0.2.0 has the same issue, so perhaps not a regression.

**Comment by justinmk** [comment]
Is xterm-256color the correct TERM? We don't do anything different for conhost, so ... if conhost really claims to be xterm, it should behave like xterm, which doesn't have this bug.

**Comment by mqudsi** [comment]
That does sound logical, though I do wonder why both conhost and terminus exhibit the same behavior here.

I imagine the difference between ctrl+e & co and ctrl+f/b is that one drops a line + pushes a line and the other completely redraws the screen?

If I unset `TERM` entirely before running neovim the issue goes away (and surprisingly without introducing any other problems that I can see).

Is there any way to force `:redraw!` on scroll?

**Comment by justinmk** [comment]
> If I unset TERM entirely before running neovim the issue goes away

That's worth more investigation. Is there some other TERM recommended for conhost? I have a feeling we're doing an xterm-related optimization that we skip otherwise.

> Is there any way to force :redraw! on scroll?

That's pretty extreme. Maybe do it on CursorHold instead, or just mash CTRL-L occasionally...

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7624 defaults the built-in terminfos to disable BCE. But that only helps here if Nvim doesn't find a terminfo in your environment. If the terminfo in your environment claims BCE then Nvim will use that feature.

**Comment by mqudsi** [comment]
I'm not clear on whether justinmk/tui now acts per your comment above (BCE will be used if the terminal claims it is supported) or if per #7624 only on real xterm even if support for BCE is advertised?

I ask because #7624 doesn't seem to be working for me under conhost. I get the same behavior where a manual refresh (Ctrl+L) is needed to get the background color redrawn correctly.

**Comment by justinmk** [comment]
Perhaps instead this is related to the `ccc` capability as in https://github.com/martanne/vis/issues/456

**Comment by mqudsi** [comment]
I can confirm this is now fixed under the same/earlier Windows builds but with the latest neovim (`v0.2.3-935-g88e62f239`).

Tested under conemu/WSL 16299 with `xterm-256color`. Haven't had this pop up in a while (months, probably).

**Comment by justinmk** [comment]
@mqudsi Thanks for the followup!
