### ISSUE TITLE
Nvim run but disappear from the screen

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7426]
- `nvim --version`: 0.2.1 
- Vim (version: ) behaves differently? yes
- Operating system/version: Windows 10
- Terminal name/version: CMD
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Nvim runs normally with the above parameters
### Actual behaviour
Nvim installed with spacevim just show up and disappear from the screen even with the CMD. The task manager does show nvim processes but I'm not sure why the screen does not show up as usual.

![image](https://user-images.githubusercontent.com/2046672/31858418-a943080e-b73e-11e7-83c7-c2ea812fe019.png)

**Comment by justinmk** [comment]
Is this the machine that has [antivirus](https://github.com/neovim/neovim/issues/7415) which thinks nvim is a trojan?

Did you try `nvim-qt.exe` (GUI) instead?

**Comment by duytrung** [comment]
nvim scan and it is clean
the problem is it have been installed with spacevim.

**Comment by justinmk** [comment]
Can this be closed? Still not clear what you are reporting.
