### ISSUE TITLE
Redraw bug when a vertical split containing UTF8 characters is closed on the right of a terminal buffer

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7427]
- `nvim --version`: NVIM v0.2.1-1046-gd7594f9c3
- Operating system/version: Linux 4.12.12-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`

```
echo '"😆"   U' | nvim -u NONE - -c ':vs term://sh'
:bw! 1
```

### Actual behaviour
When the buffer containing unicode characters is wiped, the letter 'U' will keep being displayed. Asking for a redraw using <C-L> makes the character disappear.

### Expected behaviour
'U' shouldn't be displayed after the buffer containing it is closed.

**Comment by blueyed** [comment]
Tried to reproduce this, but could not.
Using rxvt-unicode master and my patched version.

**Comment by glacambre** [comment]
I can reproduce in both urxvt and xterm but not in alacritty.
This might be a terminal emulator problem though as neither urxvt nor xterm can display emojis on my machine but alacritty can.
I'm not sure how to further investigate this issue. If there's anything you'd like me to do in order to help pinpoint the problem feel free to ask.

**Comment by glacambre** [comment]
I think this is the same issue as described here: https://github.com/jwilm/alacritty/issues/696 .
I guess there's nothing Neovim can do about it.
