### ISSUE TITLE
Buffer-specific autocommand is triggered on unrelated buffer wipe

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7429]
- `nvim --version`: NVIM v0.2.1-1046-gd7594f9c3
- Operating system/version: Linux 4.12.12-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
Open neovim with a normal buffer and a term buffer. Get the cursor into the normal buffer, open a help buffer, move it to the right and wipe it.
```
nvim -u NORC -o term://sh normal --cmd "au TermOpen * au BufEnter <buffer> startinsert"
<C-\><C-n>
:h help
<C-w>L
:bw!
```

### Actual behaviour
When closing the vertical help window, the cursor will enter insert mode in the "normal" buffer. However, if the window is wiped without being moved, the cursor will be left in normal mode in the "normal" buffer.

### Expected behaviour
Insert mode should never be entered if the cursor ends up in the "normal" buffer.

**Comment by justinmk** [comment]
Confirmed. Somehow the `BufEnter` autocmd for the terminal buffer is fired even though the cursor doesn't end up there. Also happens with `-u NONE`.

Somewhere in the window-choosing logic there must be a bug.
