### ISSUE TITLE
`zc` with count doesn't behave as documented

### ISSUE THREAD

**Issue by danielyli** [neovim/neovim#7434]
- `nvim --version`: NVIM v0.2.0
- Vim (version: ) behaves differently? Behaves the same
- Operating system/version: High Sierra
- Terminal name/version: iTerm2
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC <file with at least two levels of folding>

:set foldmethod=syntax
zR

" Navigate to a top-level fold
2zc
```

### Actual behaviour
Only the fold at the cursor level is folded.

### Expected behaviour
The fold at the cursor level and the level below that should be folded.

`:help zc` says:

> Close one fold under the cursor.  *When a count is given, that many folds deep are closed.*

**Comment by justinmk** [comment]
> Navigate to a top-level fold

This explains the behavior. `zc` (and `zC`) work for folds that "contain the cursor line". This hint is in `:help zC`. I agree that the help is a bit confusing.

Move the cursor to an inner fold and it works as described: `2zc` closes that fold and the surrounding one..
