### ISSUE TITLE
Avoid saving :lcd in views

### ISSUE THREAD

**Issue by EricR86** [neovim/neovim#7435]
- `nvim --version`: Current HEAD and all previous versions
- Vim behaves differently?: No

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e new_buffer
:lcd /some/dir
:mkview
:e some_other_buffer
:mkview
:q

nvim -u NORC
:e some_other_buffer
:loadview
:pwd "is now /some/dir
```

### Actual behaviour
:mkview saves the local current directory for the window in a view (which is associated with the filename). If you open another buffer in the same window and save the view, woe to you and now you  have the same :lcd saved for that associated filename. Can't unset the :lcd, and so you can't remove it from the view unless you manually edit it. If any other plugin, script, autocmd sets the :lcd, your views get absolutely mangled with odd working directories putting you in working directories you probably didn't want to be in. Often I found myself changing buffers and ending up in different working directories and I had no idea why/when it happened until I tracked down this specific behavior.

### Expected behaviour
Not have views (which are associated with a filename) save the local current directory/:lcd (which are associated with a vim window).

I wouldn't mind submitting a PR for this, but I'm not even sure what would be the best solution for this. I'd have 4 options in mind when it comes to fixing this issue:

1. Remove :lcd being saved for views. In ex_docmd.c, at the end of put_view there's the following:
```c
  /*
   * Local directory.
   */
  if (wp->w_localdir != NULL) {
    if (fputs("lcd ", fd) < 0
        || ses_put_fname(fd, wp->w_localdir, flagp) == FAIL
        || put_eol(fd) == FAIL)
      return FAIL;
    did_lcd = TRUE;
  }
```
That's the offending code I wish had not existed in the first place.

2. Add an option in viewoptions to avoid saving the lcd. The only issue I saw is that they are tied with sessionoptions. Not only that but the number of options were made to fit into 1 byte and there's no extra room without changing the type.

3. Add buffer local directories. Having the view save a directory that's tied to the buffer/filename is much more preferable than one tied to the current window.

4. Add options to unset tcd/lcd. It would be great if these could get unset (I suppose :tcd included) and so when the view is saved again, the option is removed.

I have stopped using views for now since they have been so polluted with :lcd options unbeknownst to me. Views in general are pretty great though so I'd be willing to help out to try and resolve this issue.

**Comment by justinmk** [comment]
see https://github.com/kopischke/vim-stay

@kopischke maybe you have insight/comments about this?

**Comment by kopischke** [comment]
In my experience, Vim’s not-so-great working directory handling breaks down entirely when interacting with view files, and you need convoluted workarounds to avoid that (see the discussion in [this vim-stay issue thread](https://github.com/kopischke/vim-stay/issues/10)). Integrating a way to exempt local working directory state from view saving into core would be a much more viable solution, though I would err in favour of putting it behind another `viewoptions` switch, as complaints are not so prevalent that I would swear nobody actually relies on that specific behaviour.
