### ISSUE TITLE
Code folding, mkview

### ISSUE THREAD

**Issue by victoriastuart** [neovim/neovim#7442]
There is an issue saving code folds / folding (Vim views) in Neovim 0.2.0-2 (installed via `pacman` in Arch Linux).

Per this StackOverflow thread,

https://stackoverflow.com/questions/2142402/code-folding-is-not-saved-in-my-vimrc

I tried every permutation of 

    autocmd BufWrite * mkview
    autocmd BufRead * silent loadview

e.g.

    autocmd BufWrite *.* mkview
    autocmd BufRead *.* silent loadview

etc.  I cannot persistently save folds in Neovim across sessions without errors appearing, when switching to/from buffers or opening files that have not previously been saved in

    ~/.local/share/nvim/view/

I get these error messages (for example), in my Neovim status line:

    Error detected while processing BufReadPost Auto commands for "*":
    E484: Can't open file /home/victoria/.local/share/nvim/view/~=+projects=+shortcuts=+rename.sh=
    E484: Can't open file /home/victoria/.local/share/nvim/view/~=+projects=+shortcuts=+rename.sh=
    Press ENTER or type command to continue

As indicated, this appears to be an issue with the filenames that are saved in this folder:

    ~/.local/share/nvim/view/

Here is a sampling of the files saved in that directory:

    =+mnt=+Vancouver=+Programming=+scripts=+sed_sentence_chunker=+-MiniBufExplorer-=
    =+mnt=+Vancouver=+Programming=+scripts=+sed_sentence_chunker=+NERD_tree_1=
    ~=+.bashrc=
    ~=+.tmux.conf=
    ~=+.vim=+bundle=+vim-snippets=+snippets=+_.snippets=
    ~=+.vim_favs=
    ~=+.vimrc=
    ~=+new=
    ~=+projects=+nb-nlp.html=
    ~=+projects=+shortcuts=+clipboards=+Personal.txt=

**Comment by jamessan** [comment]
> I cannot persistently save folds in Neovim across sessions without errors appearing

`silent` doesn't suppress errors.  You need `silent!` for that.

**Comment by victoriastuart** [comment]
Wow, that did the trick!  Thank you: very much appreciated! :-D

Updated ~/.vimrc:

    autocmd BufWrite * mkview
    autocmd BufRead * silent! loadview
