### ISSUE TITLE
tui: restore 'termencoding'

### ISSUE THREAD

**Issue by CKD4XXH** [neovim/neovim#7445]
neovim, seemingly, supports any file encoding.
But in effect, as I found, supports exclusively the utf-8 encoding.
-- So I cannot use neovim. What a pity..

This is because if one has many iso-8859-2 (or iso-8859-1 or ..) files, then, as far as I know, h/she would set the "terminal" (the locale) to iso-8859-2 too. In order to use grep, sed etc. To see the file contents properly.

**Comment by bfredl** [comment]
If you already accept to change the terminal encoding between latin1 and latin2, why can't you also change it to utf-8 to run nvim?

**Comment by chrisbra** [comment]
> then, as far as I know, h/she would set the "terminal" (the locale) to iso-8859-2 too. In order to use grep, sed

That is true but has nothing to do with neovim and I am not sure how this relates to neovim. It should still be possible to use neovim (even though it uses internally the utf-8 encoding) and it can still read and write iso-8859-2 encoding for files.

**Comment by bfredl** [comment]
Their issue is the encoding of the terminal. But it can be changed.

**Comment by jamessan** [comment]
> Their issue is the encoding of the terminal. But it can be changed.

That's not a useful answer.  Having to change the encoding just to run nvim, when everything else respects the environment means that we're doing something wrong.

When I brought up the idea of requiring `encoding=utf-8` on the Vim list years ago, my suggestion was to then have the environment's encoding set the default value for `'tenc'`, since that is what controls the encoding for input/output with the terminal.

**Comment by bfredl** [comment]
@jamessan That was _not_ an answer to the user, rather to @chrisbra, as you clearly can see by the use of pronoun. My response to the user was my _first_ response, which was silently invalidated by changing the issue, without mentioning this is a message so I couldn't _possibly_ see my answer was invalid on mobile.

**Comment by justinmk** [comment]
Vim 7.4.852 removed 'termencoding' on Windows. https://github.com/vim/vim/commit/ac360bf2ca293735fc7c6654dc2b3066f4c62488

**Comment by justinmk** [comment]
Haven't seen a strong case for this, relative to implementation effort.
