### ISSUE TITLE
Pasting 11k lines of cpp code in neovim, makes it unresponsive.

### ISSUE THREAD

**Issue by vivektiwary** [neovim/neovim#7455]
- `nvim --version`: 0.2.0
- Vim (version: ) behaves differently?
- Operating system/version: MacOs high sierra
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. Go to `https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp` and copy the file.
2. Try to paste that in neovim
```
nvim -u NORC

```

### Actual behaviour

NeoVim stucks with `--INSERT (paste) --` status.

### Expected behaviour

It should not hang. FYI sublime is handling this part elegantly.

**Comment by justinmk** [comment]
Did you set the `paste` option beforehand? If so, try without it.

**Comment by justinmk** [comment]
Nevermind, I can reproduce it even with `nvim -u NONE`. `vim -u NONE -N` also takes a long time, though it at least shows visual feedback.

There's massive room for improvement here.

**Comment by blankname** [comment]
It seems to me like the perf problem only occurs when pasting is done while in Insert mode.
Normal mode pasting is pretty much instantaneous.
Does it have something to do with the way the text scrolls while pasting?

**Comment by blankname** [comment]
The perf difference seems to be in the `process_interrupts` function in `src/nvim/os/input.c` (the RBUFFER_EACH_REVERSE macro/loop).

The function only shows up in the profile when the pasting is done in insert mode.

I guess Normal mode pasting (`:put +`) circumvents input processing on the pasted text.
Don't know if something could/should be changed, I don't know the code very well.

**Comment by justinmk** [comment]
Thanks for looking. The nature of the problem is known. I have an old PR that I need to revisit which will address this.

**Comment by blankname** [comment]
@justinmk: Is the PR posted anywhere? I would like to look at it in case I'm capable of picking it up.

**Comment by justinmk** [comment]
@blankname https://github.com/neovim/neovim/pull/4448  . see also for the direction we want to go https://github.com/neovim/neovim/pull/4448#issuecomment-196424051 . Essentially just balloon everything into a big buffer then pass it as an argument to some VimL callback (user-configurable), and let the callback put the contents into the buffer (this can be extremely fast as demonstrated already by `"+p`). 

N.B.: "streaming" would be better that ballooning a big buffer but not worth the complication for now.
