### ISSUE TITLE
rxvt: Slow redraw with wildmode=list:longest,list:full

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#7467]
I'm noticing slow redraws / input processing when using `set wildmode=list:longest,list:full` from time to time.

After e.g. `:b <Tab>` two lines with buffers get displayed, but this is behaving sluggish often, i.e. the existing windows get "scrolled up" to make room, but this is only filled with the buffer names sometimes 2-3 seconds later.

`:e <Tab>` behaves usually better: it displays the 9 lines of files directly, and might only have minor redraw slowness when redrawing the statusline in the end.  But it can also trigger it.

It also happens after e.g. `:set <Tab>` (less likely), so should not be related to the file system.

It is related to the number of vertical splits: it does not happen with a single one, but more often with e.g. 4.  `&columns` is 190.

I am using rxvt-unicode, and tried setting `TERM=xterm` therein without success.

It does not happen in gnome-terminal nor xterm itself: gnome-terminal behaves well, and with xterm it looks like you can actually see the drawing process (which is fast and fine though).

- `nvim --version`: v0.2.1-1122-g54b79f19d
- Operating system/version: Arch Linux
- Terminal name/version: urxvt / rxvt-unicode
- `$TERM`: rxvt-unicode-256color

**Comment by justinmk** [comment]
cc @jdebp

**Comment by justinmk** [comment]
@blueyed Any improvement here? Wondering if https://github.com/neovim/neovim/pull/7624 or https://github.com/neovim/neovim/pull/7676 helped this.

**Comment by blueyed** [comment]
@justinmk 
Yes, it seems to be better now - thanks!

Will close it for now.
