### ISSUE TITLE
TUI: kitty: broken 'termguicolors'

### ISSUE THREAD

**Issue by schaden-freude** [neovim/neovim#7473]
- `nvim --version`: 0.2.1-dev
- Vim version:  8.0 ; behaves differently? **Yes.** 
- Operating system/version: Ubuntu 17.10
- Terminal name/version: [kitty](https://github.com/kovidgoyal/kitty/)
- `$TERM`: xterm-kitty

### Actual behaviour

Nvim borks when `termguicolors` is set. 
Vim on the left and nvim on the right. 

![2017-11-01-173522_1366x768_scrot](https://user-images.githubusercontent.com/17528465/32274147-8be758a6-bf2b-11e7-8096-c1bfc13f67d9.png)

### Expected behaviour
Neovim should display colors similar to vim.

I was told by @kovidgoyal at kovidgoyal/kitty#160 that neovim should be using semicolon as the delimiter instead of colon.

**Comment by justinmk** [comment]
What's the output of:

    infocmp xterm-kitty | grep rgb

**Comment by schaden-freude** [comment]
Output of `infocmp xterm-kitty | grep rgb` is

```
initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
```
Changing `TERM` to the said values doesn't make any difference. :(

**Comment by justinmk** [comment]
Replied at https://github.com/kovidgoyal/kitty/issues/160#issuecomment-341190176

I'm starting to agree with @DarkDefender that the colon thing was a waste of time.

**Comment by DarkDefender** [comment]
Yes, I still think it introduces unnecessary complexity that doesn't need to be there.

To me, it looks like the de facto standard is semi colons and that it is here to stay. So even if colons are more correct, it is a waste of time to support something that doesn't bring any visible benefit to the end user...

**Comment by DarkDefender** [comment]
@schaden-freude can you try out #7482 and see if that fixes this for you?

**Comment by XVilka** [comment]
Moreover, from all the terminals I checked only a few of them supporting colon as a delimeter. So it is safer to drop its support at all. Probably even make sense to open a bug to remove their support in those terminals.

**Comment by schaden-freude** [comment]
@DarkDefender Yeah. That fixes it for me. :)

**Comment by justinmk** [comment]
For reference, regarding the colon question see https://bugzilla.gnome.org/show_bug.cgi?id=685759 

>  We overlooked the detail about ":" as a subparameter delimiter (documented
>  in 5.4.t2 in ECMA-48).  Some discussion in KDE in mid-2006 led Lars Doelle
>  to discuss the issue with me.  Lars' initial concern dealt with the fact
>  that a sequence such as
>       CSI 38 ; 5 ; 1 m
>  violated the principle that SGR parameters could be used in any order.
>  Further discussion (see KDE #107487) resolved that the standard expected
>  that the sequence would look like
>       CSI 38 ; 5 : 1 m
>  which still violates that principle, since the "5:1" parameter has to
>  follow the "38" to be useful.
> 
>  This function accepts either format (per request by Paul Leonerd Evans).
>  It also accepts
>       CSI 38 : 5 : 1 m
>  according to Lars' original assumption.

And https://bugzilla.gnome.org/show_bug.cgi?id=704449 discusses the ambiguous cases:

> accepting ':' instead of ';' as the delimiter after CSI 38/48, something we should do too. The problem with semicolon is that it's supposed to delimit properties that are independent from each other and take no additional parameters. E.g. vte currently doesn't recognize ^[[38;2;1;3;4 as a true color escape sequence (rgb:1/3/4), but instead it switches to bold(1), italic(3) and underline(4) since it has no clue how many parameters 38;2 is supposed to take.

**Comment by justinmk** [comment]
@schaden-freude What does `$TERM_PROGRAM` report for you?

> Changing TERM to the said values doesn't make any difference. :(

You tried `TERM=kitty-256color` and it still used colons? That doesn't make sense.

**Comment by egmontkob** [comment]
kitty's terminfo entry should be irrelevant. ncurses/terminfo maintainer refused to even "officially" allocate a capability for emitting truecolor fg/bg colors. The quoted part is about OSC 4 which dynamically redefines the entries of the 256-color palette.

**Comment by egmontkob** [comment]
See also https://github.com/mobile-shell/mosh/pull/939#issuecomment-340203507.

**Comment by schaden-freude** [comment]
> What does $TERM_PROGRAM report for you?

Nothing. What should it ideally say by the way, if anything?

> You tried TERM=kitty-256color and it still used colons?

Yeah.

>Is $VTE_VERSION set ...?

`env | grep VTE` gives me `VTE_VERSION=4804`.

**Comment by justinmk** [comment]
@schaden-freude  Why on earth is `VTE_VERSION=4804` being reported for kitty?

I just tried nvim with kitty 0.4.2 and it works fine:

    nvim --cmd 'set termguicolors'

So it seems the real problem here is we need more duct-tape to deal with people's broken environments.

**Comment by schaden-freude** [comment]
> @schaden-freude Why on earth is VTE_VERSION=4804 being reported for kitty?

I am sorry I don't have the any technical understanding of these things.

What should it ideally say?

**Comment by kovidgoyal** [comment]
@justinmk probably because schaden-freude is launching kitty from inside a libvte based terminal :) One of the problems with env vars.

**Comment by justinmk** [comment]
This particular case was an environment issue.

Created https://github.com/neovim/neovim/issues/7490 to track the more general problem of better terminal-type detection.
