### ISSUE TITLE
Windows 10 :term strange behavior - No input is shown in opened terminal

### ISSUE THREAD

**Issue by sp0ng3w0rthy** [neovim/neovim#7474]
- `nvim --version`: **NVIM v0.2.1-25-g2e3b78d1**
- OS: **Windows 10 64bit**
- Terminal: **Powershell**
#### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:term
<attempt to input ANY command in opened terminal>
```
### Actual behaviour
No input is shown in the opened `cmd.exe` after running `:term`, see the following gif:

![nvim-term-min](https://user-images.githubusercontent.com/10582405/32276167-b5cd21ba-bf16-11e7-9fa5-85d956020c71.gif)

Also, after attempting to terminate the terminal using `exit <C-j>`, and then hitting `<Return>`, `nvim` remains completely unresponsive:

![nvim-non-responsive-after](https://user-images.githubusercontent.com/10582405/32276819-10a02d2e-bf19-11e7-91a6-a4eb48dca13e.gif)

**Comment by jamessan** [comment]
> `nvim --version`: NVIM v0.2.1-25-g2e3b78d1

That's a very old build, from just after 0.2.0 was released.  You'll notice that the 0.2.0 release notes say

> `:terminal` is not supported on Windows, yet. (Planned for 0.2.1)

If you update to a recent build, this will work much better because `:terminal` support was merged.

**Comment by sp0ng3w0rthy** [comment]
Thank you for the reply @jamessan , I have seen the Windows `:terminal` thread, and I have updated to latest build (please notice I specified that my `nvim` version is: NVIM **v0.2.1**-25-g2e3b78d1).

**Comment by sp0ng3w0rthy** [comment]
Thank you for the reply @jamessan , But I'm a bit confused: I have seen the Windows :terminal thread, and I have updated to latest build.

Please notice I specified that my nvim version is: NVIM v0.2.1-25-g2e3b78d1, and you quoted it as well, so can you please clarify this further?

**Comment by jamessan** [comment]
That build is from commit 2e3b78d1, which is from 6 months ago.  You would need to get the [nightly](https://github.com/neovim/neovim/releases/tag/nightly) build to get a current build.

**Comment by sp0ng3w0rthy** [comment]
Ahh I see I mistakenly thought you were referring to a **Release** version, my apologies, thanks.
