### ISSUE TITLE
tui: support styled and colored underlines/undercurl

### ISSUE THREAD

**Issue by kovidgoyal** [neovim/neovim#7479]
It would be nice to have the ability to use styled and colored underlines in the terminal. I have created a terminal with support for this https://github.com/kovidgoyal/kitty

Spec at: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc#colored-and-styled-underlines. It includes a way to detect support for the feature.

Corresponding vim ticket: https://github.com/vim/vim/issues/1306

**Comment by egmontkob** [comment]
If neovim implements this, this would be a good reason for us to add support to VTE too, which I'd be happy to do :) See https://bugzilla.gnome.org/show_bug.cgi?id=721761 comments 16-18. There'd be disagreements about the escape sequence though, see there.

**Comment by justinmk** [comment]
PR welcome, if anyone wants to.

**Comment by kovidgoyal** [comment]
@justinmk If you can give me an indication of whereabouts in the neovim source code I should focus, I will look at it the next time I have some spare time.

**Comment by teto** [comment]
@kovidgoyal that would be cool; highlights are sent to UIs via https://github.com/neovim/neovim/blob/b57d9a4ff08fc1ef8db79d422b441b792493ff4e/src/nvim/syntax.c#L8248 and the TUI receives them via https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L955, you will have to insert some code in tui.c

**Comment by kovidgoyal** [comment]
Just to note, Bram has implemented this in vim (since vim already had t_Cs, t_Ce settings for it, it was a trivial patch).

**Comment by kovidgoyal** [comment]
@egmontkob since neovim is probably going to try to detect support for this rather than leave configuring it up to the user. It would be good if we can agree on the final escape codes to use. I am open to changing them in kitty, as currently no external programs (that I am aware of) use them.

**Comment by KillTheMule** [comment]
cc @leonerd maybe he's interested in that :)

**Comment by leonerd** [comment]
Underline colour should be the SGR 50-59 values. (I suspect also high-brightness under SGR 110-117 but in practice you'd probably just use the 256-palette SGR 58:5:nnn)

**Comment by kovidgoyal** [comment]
underline color is 50-59 already. I haven't bothered with high brightness, but I am willing to add it if needed.

**Comment by leonerd** [comment]
I wouldn't necessarily bother with high-brightness in the 110-117 region. Just handle 58:5:nnn and that should be OK. We can just say "use that rather than the 110-117 region"

**Comment by kovidgoyal** [comment]
High brightness is not actually equivalent to 256 colors, since the high bright colors are often remapped/configured by the user, while the 256 color table is not. And color code parsing is the same as for all other SGR color codes, which means it support 256 colors and 24bit colors.

**Comment by egmontkob** [comment]
> It would be good if we can agree on the final escape codes to use. I am open to changing them in kitty, as currently no external programs (that I am aware of) use them.

It was not me but VTE's main developer expressing his concerns about reusing SGR 6, we should loop him in.

> underline color is 50-59 already.

So far I lived under the impression that underline color was 58 & 59 only (and in kitty 0.4.2 that's indeed the case). According to https://en.wikipedia.org/wiki/ANSI_escape_code 51-55 are already allocated. Konsole already supports 53 for overline, and VTE also has a pending feature request filed for this. I don't feel good conflicting with them, and honestly I don't feel good allocating so many numbers for such a relatively marginal feature.

SGR 58 allows you to choose from the 256-color palette, and the first 8/16 entries of them are _almost_ the same as SGR 50-57 in your proposal.

The only slight difference in some terminal emulators is: the app cannot tell whether the bold attribute also brightens the colors, that is, whether the legacy indices 0-7 are equivalent of colors 0-7 or colors 8-15 of the 256-color palette if combined with bold.

I personally wouldn't mind keeping 58 & 59 only.

On a somewhat relevant note, 59 means "the same as the foreground color of the cell", and it has to remain this way for backwards compatibility. There's no way to specify "the default foreground color of the terminal emulator" for the underline if a non-default text color is being used. I don't mind this limitation too much, but let's mention it for the record.

> High brightness is not actually equivalent to 256 colors, since the high bright colors are often remapped/configured by the user, while the 256 color table is not.

Could you please elaborate on this? As far as I know, xterm, VTE and other popular emulators don't have 8+256 or 8+8+256 palette slots, they only have 256. If you redefine a color of index 0-15, you redefine both the legacy and the 256-color palette versions of them.

The only difference between the legacy (SGR 30-37) and 256-color (SGR 38;5;0-7) notation is that the former might go bright (remap to color indices 8-15) if bold is enabled, while the latter always stays at the same color and just gets bolder.

I don't think the second 8 colors can become different at all, I believe SGR 100-107 and SGR 38;5;8-15 always result in the same 8 colors.

**Comment by kovidgoyal** [comment]
@egmontkob Sorry you are right, it is 58/59 only. I was posting in too much of a hurry yesterday and for some reason I read 50-59 as 58-59 :)

And yes, changing the first 16 colors also changes the first 16 colors of the 256 color table. So I suppose  we can live with no 16 color specification. 

So the only controversial one is 6m? Personally, I dont see the harm in re-using it. I've never heard of/come across anything that uses rapid blink and I doubt many terminal emulators even support it. However, I am fine with changing it to something else, if it is a sticking point for someone.

**Comment by leonerd** [comment]
While we're on the subject of terminal controls, I might draw your attention to a project I've been trying to get started which is trying to survey what everyone is using code-wise, so as to identify where common things are, where gaps are, and so on. If you're intending these things to be relatively standard offerings, perhaps you could add them to

https://docs.google.com/spreadsheets/d/19W-lXWS9jYwqCK-LwgYo31GucPPxYVld_hVEcfpNpXg/edit#gid=1724051764

**Comment by kovidgoyal** [comment]
@leonerd Sure, once they are finalised, I will be happy to add them.

**Comment by kovidgoyal** [comment]
@egmontkob An alternative to using 6m is to instead extend 4m. So 4m and 4:1m set the underline style to straight lines, while 4:2m sets it to curly. This has the advantage of restricting underlines to a single leading number. The disadvantage is that I dont know what terminals that dont support colons in SGR codes will do with it. In the ideal case they will simply ignore the part after the colon and use straight underlines. In the worst case they will ignore the entire SGR sequence the code is a part of.

**Comment by egmontkob** [comment]
I love this idea :) (and at the same time feel so stupid that it didn't occur to me :)).

This would also slightly push terminal emulators towards implementing colon as a separator, hopefully for true colors too. I just came across the fact that CCITT Recommendation T.416 mentions optional 6th, 7th and 8th parameters for RGB colors. So, strictly speaking, all terminal emulators that parse `^[[38;2;10;20;30;48;2;40;50;60m` as foreground(10,20,30) and background(40,50,60), which includes all terminal emulators that I'm aware of supporting true colors, get it wrong. No doubt colon separator would be a much cleaner approach – if everyone supported it.

Back to underline: For a moment I was thinking that the parameters should start at 0, but then seeing that at the SGR codes 0 means "implementation defined (only applicable for the character foreground colour)" I guess practically this parameter is also 1-based, so I'm fine with this.

> In the ideal case they will simply ignore the part after the colon and use straight underlines. In the worst case they will ignore the entire SGR sequence the code is a part of.

I'd rather guess the "worst" case scenario: they'd ignore it, which is still not worse than an unsupported SGR 6.

**Comment by kovidgoyal** [comment]
Cool, 4:2 it is. I'll push the changes to kitty for it soonish.

**Comment by egmontkob** [comment]
Just to make sure we're on the same side: colon would be mandatory here, not an alternative to semicolon, correct? That is, 4;1m would still be straight underlined and bold, 4;2m would be straight underlined and dim, essential for backwards compatibility.

**Comment by kovidgoyal** [comment]
Yes, of course.

**Comment by egmontkob** [comment]
On '4:2m', the Linux konsole and KDE's konsole print "2m" (that is, the colon terminates the otherwise unrecognized escape sequence), enlightenment's terminology goes underlined and dim (treats the colon equivalent to a semicolon), and urxvt turns the background green (the colon is omitted and it becomes 42).

If we end up going this way, we'll have to file bug reports against them, and alas the worst case is worse than we thought above.

**Comment by kovidgoyal** [comment]
Ah that's probably why I chose 6m in the first place. Well let's see if Christian has any comments. The third alternative is to use a completely new code, beyond 100.

**Comment by leonerd** [comment]
My latest libtickit driver code tries to detect on startup whether the terminal it's talking to actually understands such things as colon-separated CSI parameters, and uses that to tune what things it sends.

In the specific case of colon-separated things, what I do is emit a control sequence that could only successfully apply with a correct colon-parsing terminal then query back the state I just set. The entire operation is ended with an "Erase-in-Line" sequence, so even in the worse case where the terminal literally prints it, it would only be visible as a very brief flash, once on startup, before disappearing. Almost certainly the user won't notice that as it will happen just before I turn on altscreen mode and clear the display anyway.

See the entire code around

  http://bazaar.launchpad.net/~leonerd/libtickit/trunk/view/566/src/termdriver-xterm.c#L451

**Comment by leonerd** [comment]
+1 to the idea of using 4:2 by the way. It really is a nice idea.

Don't be put off by badly-implemented terminals that don't understand colon separators. They are buggy and need to be fixed, but also they can be detected and worked-around. If a terminal doesn't support colons it's not going to understand this styled underline feature either, so you learn both of those facts by this kind of dynamic probing.

**Comment by egmontkob** [comment]
xterm and perhaps a few others support SGR 21 for double wide underline. If we stick at the "4:2" notation, I guess the existing single and double underlines should take "4:1" and "4:2", and the new curly one should be "4:3", what do you think? It's also pretty intuitive that 1 means single, 2 means double, and 3 is a curly digit :-)

Whenever I'll add curly underline to VTE, I'll probably add double underline too. It won't take up additional storage since there'd be 4 underlines modes altogether (including none) which still requires 2 bits.

**Comment by kovidgoyal** [comment]
Double underline is fine by me, it's easy to implement in kitty as well, where the underline style is also stored in two bits. As for using 4:2 at all, I am also +1 for it (IMO it is technically the most elegant). It remains to be seen if Christian Perch objects, or the vim/neovim developers object.

**Comment by leonerd** [comment]
The historical encoding of double-underline as SGR 21 does leave a little complication here.

While in theory it would be nice to consider SGR 21 as an alternative spelling of SGR 4:2 for double underline and accept 4:1 and 4:3 for single and curly (which I think is neat), it does raise the awkward question of what does DECRQSS(SGR) have to say on the subject?

Primarily, what is the reply to either of

    SGR 4:2 DECRQSS(SGR)
    SGR 21 DECRQSS(SGR)

given as we want them to render identically. Does the reply mention both things?

**Comment by kovidgoyal** [comment]
My vote is -- ignore SGR 21. DECQRSS returns 4:x for underlines.

**Comment by kovidgoyal** [comment]
I have changed kitty to use 4:x see https://github.com/kovidgoyal/kitty/commit/e81ba3b2078eb71098e8738b5d9883af41077d69

Let me know if the protcol documentation needs clarification.

**Comment by leonerd** [comment]
@kovidgoyal - yeah that documentation looks good.

I have an unrelated question to ask about terminal sequences and documentation, but I fear the neovim folks might start getting annoyed at us continuing here. Perhaps could you ping me an email - `leonerd <at> leonerd <dot> org <dot> uk` and I'll explain more. Thanks.

**Comment by kovidgoyal** [comment]
Sure, pinged as requested. You can also find my email address at the top of any kitty source code file.

**Comment by mintty** [comment]
I came across this issue while investigating about colon-separated SGR parameters for a catch-up of the mintty terminal with xterm. Just for information, mintty already supports these non-standard SGRs: 2 (dim), 3 (italic), 6 (rapidly blinking), 9 (strikeout), 11..19/20 (alternative fonts), 21 (double underline), 53 (overline) and 51/52 (framed/encircled) reinterpreted as emoji style preference.
The next version will support underline styles 4:0..4:5 (off/solid/double/wavy/dotted/dashed).
It will also support colour specifications in original ISO/IEC 8613-6 format 38/48:5:P 38/48:2::R:G:B plus xterm-double-colon tolerance 38/48:2:R:G:B, and including ISO/IEC 8613-6 CMY(K) formats 38/48:3:F:C:M:Y and 38/48:4:F:C:M:Y:K where F sets the 100% scaling value.

**Comment by leonerd** [comment]
Those are some interesting new SGRs. Can you please ensure they get added to the sheet?

https://docs.google.com/spreadsheets/d/19W-lXWS9jYwqCK-LwgYo31GucPPxYVld_hVEcfpNpXg/edit#gid=0

**Comment by blueyed** [comment]
There is some WIP in #9052, but for some reason it does not work in tmux (https://github.com/neovim/neovim/pull/9052#issuecomment-424694981).
