### ISSUE TITLE
[question] how to comment out selected text or block of texts at a time?

### ISSUE THREAD

**Issue by narutowindy** [neovim/neovim#7481]
line 1
line 2
...
line10

comment out with # (hash) in fornt of all those lines?

tried method :1 

>press Esc (to leave editing or other mode)
>hit ctrl+v (visual block mode)
>use the up/down arrow keys to select lines you want (it won't highlight everything - it's OK!)
>Shift+i (capital I)
>insert the text you want, i.e. '# '
>press Esc

not working (link: https://stackoverflow.com/questions/1676632/whats-a-quick-way-to-comment-uncomment-lines-in-vim)

**Comment by teto** [comment]
this should work though.
This plugin is the best option imo https://github.com/tpope/vim-commentary, you can comment a line with `gcc` or `gc{word}`
Nerdcommenter is another one

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Comment by scimad** [comment]
Any way to do without plugin? 

> not working (link: https://stackoverflow.com/questions/1676632/whats-a-quick-way-to-comment-uncomment-lines-in-vim)

Not working for me too

**Comment by yantongl** [comment]
I encountered the same issue today. After 30 min search & experiment, finally got a good understanding. Gonna share what I found here, hopefully it can help other people to save some time.

If I launch nvim in *Windows Terminal*, Ctrl-V cannot enter visual block mode. Using Ctrl-Q solved the issue. Probably Windows Terminal binds Ctrl-V to paste as other windows programs. If I launch nvim in cmd.exe, or launch nvim-qt, then Ctrl-V works.

**Comment by chrisbra** [comment]
> If I launch nvim in Windows Terminal, Ctrl-V cannot enter visual block mode. Using Ctrl-Q solved the issue. Probably Windows Terminal binds Ctrl-V to paste as other windows programs. The linked post mentioned this by saying "or Ctrl-Q for gVim", but actually it should be "try Ctrl-Q if Ctrl-V doesn't work on your terminal".

You can configure Windows Terminal to use different keys for copy and pasting: https://docs.microsoft.com/en-us/windows/terminal/customize-settings/actions#clipboard-integration-commands

I use those:

        {"command": "copy", "keys": ["ctrl+insert"]},
        {"command": "paste", "keys": ["ctrl+shift+insert"]},

**Comment by Jeremiah-Roise** [comment]
> line 1 line 2 ... line10
> 
> comment out with # (hash) in fornt of all those lines?
> 
> tried method :1
> 
> > press Esc (to leave editing or other mode)
> > hit ctrl+v (visual block mode)
> > use the up/down arrow keys to select lines you want (it won't highlight everything - it's OK!)
> > Shift+i (capital I)
> > insert the text you want, i.e. '# '
> > press Esc
> 
> not working (link: https://stackoverflow.com/questions/1676632/whats-a-quick-way-to-comment-uncomment-lines-in-vim)

for any future visitors it's worth mentioning that you have to use shift+i, regular i won't work, and then you have to press escape(or whatever key you have bound to that eg: jk) to actually see the effects.
