### ISSUE TITLE
:terminal + TUI: Redraw bug when resizing

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7483]
- `nvim --version`: NVIM v0.2.1-1124-g739bc5124
- Operating system/version: Linux 4.12.12-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21/XTerm(327)/alacritty 0.1.0
- `$TERM`: rxvt-unicode-256color/xterm-256color/xterm-256color

### Steps to reproduce using `nvim -u NORC`
First, start nvim with two horizontal windows, the upper one should be a term and bottom one a regular buffer. Reset syntax highlighting, set cterm=NONE. Append a few characters to the regular buffer. You can do all of that with the following command:
```
echo -n "aaa" | nvim -u NONE -c "syntax reset | highlight Normal ctermfg=213 ctermbg=213 cterm=NONE | sp term://sh | wincmd j"
```
Then, "violently" resize your terminal emulator (the one holding the nvim tui): you should see redraw bugs on the upper line.
I can 100% trigger this bug by using i3wm and opening/closing a new window (this divides the nvim window's width by 2 and then resizes it to its previous size).

### Actual behaviour
The right half of the first line of the terminal buffer won't be properly redrawn: it will be the default color of the terminal emulator rather than the color set using the highlight Normal command.
Please note that the bug won't be triggered if the cursor is not in the normal buffer or if it is on the first column on the normal buffer.

### Expected behaviour
Everything should be the same color.

Edit: Here's a [screenshot](https://a.lainfile.pw/kt/file.png) of what's happening. The upper right corner is black but it should be pink.

**Comment by justinmk** [comment]
Thanks for the clear repro!

With Terminal.app it happens but then fixes itself after ~1s. 

Does CTRL-L in normal-mode work around the issue for you?

**Comment by glacambre** [comment]
Indeed, CTRL-L does fix the display on all three terminal emulator, however waiting for a few seconds doesn't.

**Comment by justinmk** [comment]
@glacambre could you try https://github.com/neovim/neovim/pull/7624 ? And also try disabling the "bce" capability in your terminfo db.

**Comment by glacambre** [comment]
Still happens for urxvt (haven't tried other terminal emulators). I may have made a mistake while testing, please let me know if I should do something differently:
```
$ git rev-parse HEAD
1bd78400f020d20f499d7c6e52f60762e98bff51
$ echo $TERM
rxvt-unicode-256color
$ if tput bce; then; echo enabled; else; echo disabled; fi
disabled
$ echo -n "aaa" | build/bin/nvim -u NONE -c "syntax reset | highlight Normal ctermfg=213 ctermbg=213 cterm=NONE | sp term://sh | wincmd j"
```

**Comment by justinmk** [comment]
@glacambre Thanks. If bce is already disabled then #7624 won't make a difference. Good to rule that out.

**Comment by glacambre** [comment]
I can still reproduce this on kitty+nvim 3.1 but I can't anymore with kitty+nvim 3.2 so I assume this is fixed, probably by https://github.com/neovim/neovim/commit/1adb01c120d04bdbf25cd4ea6151ecd5f2de3a72 . Thanks @bfredl !
