### ISSUE TITLE
Inccomand crash

### ISSUE THREAD

**Issue by blankname** [neovim/neovim#7485]
Version:
```
NVIM v0.2.1-1118-g60b1e8ad1
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

### Reproduce using `nvim --noplugin -u test.vim test.vim`

With a file named test.vim:
```
set gdefault
set hidden
syntax enable

set inccommand=split

call feedkeys('vjj:s/\%V')  " :'<,'>s/\%V after selecting multiple lines causes the crash

```

**Comment by justinmk** [comment]
@KillTheMule any chance you have time to look at this?

**Comment by KillTheMule** [comment]
Yes, I will look into it.

I don't get a crash though. Neovim ends, but there's no core file written, even though I've enabled them.

@blankname I don't fully understand the reproduction steps. I made that file test.vim and ran `nvim --noplugin -u test.vim test.vim`, but neovim ends, so I can't select multiple lines in any way. Could you elaborate?

**Comment by jamessan** [comment]
With `CLANG_ASAN_UBSAN` enabled, I get this:

```
../src/nvim/ex_cmds.c:6134:19: runtime error: value -inf is outside the range of representable values of type 'int'
SUMMARY: AddressSanitizer: undefined-behavior ../src/nvim/ex_cmds.c:6134:19 in 
```

https://github.com/neovim/neovim/blob/739bc5124ad2fafdee32d33e1340a73b3778e37e/src/nvim/ex_cmds.c#L6134

**Comment by KillTheMule** [comment]
Just as my clang finished compiling :D Thanks @jamessan.
