### ISSUE TITLE
Make :CheckHealth pluggable

### ISSUE THREAD

**Issue by cweagans** [neovim/neovim#7492]
In a plugin (or my custom vimrc), I'd like to add additional checks. For instance, if my personal vimrc depends on `typescript-language-server` being executable, I'd like it to be flagged as an error in :CheckHealth if it's not.

This way, I can verify that all of the external tools that I depend on are available.

**Comment by Shougo** [comment]
It is already pluggable.
Deoplete uses checkhealth feature in `autoload/health/deoplete.vim`.

**Comment by justinmk** [comment]
Yes as @Shougo said, it is easy to create new checkers. See `:help health-dev`.

Also demo'd here: https://www.youtube.com/watch?v=gvjp0YKQycE&t=3s

**Comment by cweagans** [comment]
Oh, awesome! Thanks for the info and sorry for the noise!
