### ISSUE TITLE
<C-\><C-n> doesn't leave terminal mode

### ISSUE THREAD

**Issue by jfhc** [neovim/neovim#7495]
- `nvim --version`: 
```
NVIM v0.2.1-1125-g04b3c3277
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-f8bc11eb-6588-44e5-acc2-2126c544b28c

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? not relevant bc doesn't have `:terminal`
- Operating system/version: CentOS 7.2.1511
- Terminal name/version: tried with same results in xterm X.Org 7.6.0(295) and Konsole 2.10.5
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
<C-\><C-n>
```

### Actual behaviour
Nothing happens. If in terminal-insert mode, leaves insert mode but stays in terminal mode. 

This sequence successfully exits insert mode in a normal buffer (i.e. not in the emulated terminal).

It behaves the same way done raw, with the sequence mapped to `<Esc>` in the config file, with the sequence mapped to `<Esc>` in the open editor - all the same.

### Expected behaviour
Should exit terminal mode and go to normal mode.

**Comment by justinmk** [comment]
> . If in terminal-insert mode, leaves insert mode but stays in terminal mode.

What does this mean? There is only 1 terminal mode: insert mode in a terminal buffer. Leaving that takes you to normal mode.

**Comment by ZyX-I** [comment]
And, by the way, Vim does have `:terminal`.

**Comment by justinmk** [comment]
No reply, description is incomprehensible.
