### ISSUE TITLE
open terminal failed: not a terminal

### ISSUE THREAD

**Issue by NikosEfthias** [neovim/neovim#7501]
- `nvim --version`:`0.2.0`

- Vim (version:8.0 ) behaves differently?  yes no problem in vim 
- Operating system/version: osx high sierra
- Terminal name/version: iterm
- `$TERM`:xterm-color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:!tmux a -t vim "assuming you have a previous session opened with name vim

```

### Actual behaviour

![](https://i.imgur.com/yoIhZ3h.png)

### Expected behaviour

attaching a tmux pane like vim does

**Comment by justinmk** [comment]
`:!` uses pipes. Your example wouldn't work in gvim, either.

https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes
