### ISSUE TITLE
test/ci: ruby_spec.lua failure

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7504]
Just noting this for tracking. I've seen this error a couple times on travis (not appveyor nor quickbuild: neither installs the ruby gem), recently:

```
[32m[2m[ RUN      ][0m[0m :ruby command supports nesting: [1m[31mERR[0m[0m
./test/functional/helpers.lua:93: Key 'set_by_nested_ruby' not found

stack traceback:
	./test/functional/helpers.lua:93: in function 'get_var'
	...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:43: in function <...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:41>
```

~~@bfredl maybe related to https://github.com/neovim/neovim/pull/6544 ?~~

In #7540 this was seen also:

```
[1m[31m[  ERROR   ][0m[0m [36m...ild/neovim/neovim/test/functional/provider/ruby_spec.lua[0m @ [36m36[0m: [1m:ruby command evaluates ruby[0m
./test/functional/helpers.lua:93: Key 'set_by_ruby' not found

stack traceback:
	./test/functional/helpers.lua:93: in function 'get_var'
	...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:38: in function <...ild/neovim/neovim/test/functional/provider/ruby_spec.lua:36>
```

IOW there's not a consistent failure, instead `ruby_spec` seems to be generally flaky.

**Comment by bfredl** [comment]
I wouldn't think so, the test uses requests only, not notifications.

**Comment by justinmk** [comment]
@alexgenco Any idea of changes that might have happened in the ruby client in the last 2~3 weeks which might be related to this? I think we are pulling the latest gem on CI, we don't pull a specific version.

**Comment by alexgenco** [comment]
I did a refactor that could have caused this, I'll take a look

**Comment by alexgenco** [comment]
Oh actually I guess I never released the refactor. If you're pulling from rubygems, that hasn't changed since July.

In debugging I was consistently reproducing this for about 5 minutes and now it's passing again and I can't figure out why. It definitely feels like a race condition involving notifications instead of responses, potentially at the ruby layer. I'll keep digging.

**Comment by alexgenco** [comment]
I actually don't think I ever successfully reproduced this; it was failing for other reasons when I first started looking into it. Besides some [extra test coverage](https://github.com/alexgenco/neovim-ruby/commit/6a22c3171c149f43403ab1a80394e3ec132efbbd), I didn't really get anywhere in my investigation. I released a new minor version update, which I don't necessarily expect to fix the issue, but was long overdue. I'll revisit if the flakiness continues with the new version.

**Comment by justinmk** [comment]
@alexgenco Thanks, appreciated!

**Comment by justinmk** [comment]
This seems to have cleared up. Thanks again @alexgenco for looking at it.

**Comment by janlazo** [comment]
Doesn't work in Appveyor https://github.com/neovim/neovim/issues/7655
