### ISSUE TITLE
:teminal calls au Filetype

### ISSUE THREAD

**Issue by plexigras** [neovim/neovim#7508]
i have this in my vimrc
```vim
autocmd FileType * call matchadd('ErrorMsg', '\%>80v.\+')
```
and it should not trigger in the terminal and it doesn't in vim but does in neovim

**Comment by justinmk** [comment]
What other buffer-types do _not_ trigger `au FileType *`? This seems unusual.

**Comment by mhinz** [comment]
I'm don't get it. `FileType` is only triggered when `'filetype'` gets set. `:term` doesn't set `'filetype'`.

When columns >80 get highlighted in your terminal, it means that some _other buffer in the same window_ triggered the autocmd before. Mind that `matchadd()` works on the window, not buffer.

**Comment by plexigras** [comment]
oh ok @mhinz how do i only do buffer specific highlighting?

**Comment by mhinz** [comment]
I can only think of the nvim-specific way of doing:

```vim
:for line in range(line('$')) | call nvim_buf_add_highlight(bufnr(''), 0, 'ErrorMsg', line, 79, 500) | endfor
```

This has the big drawback that it works on _columns_, not _virtual columns_, so if you have fancy unicode drawings in your file, it will probably highlight much earlier in the line.

Or something like:

```vim
:highlight ColorColumn ctermbg=1 cterm=NONE
:set colorcolumn=81
```

**Comment by tjdevries** [comment]
@plexigras I'm not 100% sure this will work, but you could try this plugin (insert shamless plug for my own plugin): https://github.com/tjdevries/overlength.vim

If it doesn't work, you can leave an issue for me and I"ll try and fix it :)

**Comment by plexigras** [comment]
i think this should be the solution

```vim
function! s:addOverlenght()
  if !exists('w:overlenght')
    let w:overlenght = matchadd('ErrorMsg', '\%>80v.\+')
  endif
endfunction

function! s:removeOverlenght()
  if exists('w:overlenght')
    call matchdelete(w:overlenght)
    unlet w:overlenght
  endif
endfunction

augroup highlights
  autocmd BufEnter,WinEnter * if &ft!=''|call s:addOverlenght()|endif
  autocmd FileType * call s:addOverlenght()
  autocmd BufLeave * call s:removeOverlenght()
augroup END
```

**Comment by tjdevries** [comment]
Yup, that's pretty close to my plugin ;) That should work. The only thing would be I don't think you'll see the highlights when you're not in the buffer anymore. Not sure if that makes a difference for you.

**Comment by ZyX-I** [comment]
I have the following in my vimrc:

```VimL
highlight TooLongLine term=reverse ctermbg=52 guibg=#440000
autocmd BufEnter,WinEnter * if &tw && !exists('b:DO_NOT_2MATCH') |
            \                 execute '2match TooLongLine /\S\%>'.(&tw+1).'v/' |
            \               endif
autocmd BufLeave,WinLeave * 2match

command -nargs=0 -bar Dm let b:DO_NOT_2MATCH=1 | 2match
command -nargs=0 -bar Sm execute '2match TooLongLine /\S\%>'.(&tw+1).'v/' |
            \            silent! unlet b:DO_NOT_2MATCH
```

Much simpler, though too long lines are highlighted in the current buffer only; do not remember whether that was intentional or just a simplicity trade-off. `:2match` can be replaced with `matchadd()`/`matchdel()` with a fixed ID, but currently it works as-is.

BTW, note that I did *not* hardcode 80. There already is &textwidth which is a good idea to set if you need specific column. Also note that I intentionally not highlight spaces this way, line ending with space in 81’th column is fine.
