### ISSUE TITLE
Make netrw optional package

### ISSUE THREAD

**Issue by hauleth** [neovim/neovim#7511]
Move `netrw` package to `pack/dist/opt`. This would make `netrw` opt-in package instead of opt-out.

This is breaking change as it would require users of `netrw` to add `packadd! netrw` in their respective `$MYVIMRC`.

**Comment by justinmk** [comment]
I don't think this passes our usual benchmark of benefit vs cost. Users that want to opt out can do so. But many more users will just be confused.

**Comment by mhinz** [comment]
I agree with Justin.

If you don't actively use netrw, only `plugin/netrwPlugin.vim` will be sourced which is around 200 lines. Even less if you opt-out with `let g:loaded_netrwPlugin = 1` in your vimrc.

The cost of explaining that breaking change to users is higher than the above mentioned benefit.

**Comment by janlazo** [comment]
Downloading the spell file depends on `plugin/netrwPlugin.vim` and nvim doesn't come with spell file (on Windows) so netrw is mandatory.

**Comment by mhinz** [comment]
@janlazo Very good argument. That makes it a no-go.

In the future I'd like to see smaller more specialized plugins instead, e.g. for dirvish for navigation, another one for remote editing via scp, and maybe yet another just for fetching files.

These are netrw's main features that would have to be there. Other people probably come up with other features.

As long as there's no better replacement for netrw, we'll have to roll with it.

**Comment by hauleth** [comment]
@janlazo yep, that is solid argument against. I forgot about that.

@mhinz I just started thinking about creating plugin for fetching files. This shouldn't be very complex one. I will mention it here when I will finish.

**Comment by jamessan** [comment]
@hauleth Might be worth looking at https://github.com/godlygeek/netlib.

**Comment by chrisbra** [comment]
is godlygeek actually still around? Last commit is from 2013, so one would probably need an active fork of that

**Comment by hauleth** [comment]
I will check that out an maybe I will try to revive the project. 

--
Łukasz Jan Niemier

**Comment by jamessan** [comment]
> is godlygeek actually still around?

Unfortunately (for the community), he got a pretty time-intensive job and hasn't had much time to keep developing his Vim stuff, iirc.

However, I meant it more as a reference than something to directly use.

> I will check that out an maybe I will try to revive the project.

If it looks worthwhile, you could probably talk to him about transferring ownership or collaborating on it.
