### ISSUE TITLE
Weird stuff in the message row in 0.2.1

### ISSUE THREAD

**Issue by YanDoroshenko** [neovim/neovim#7512]
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? Vim 8.0.1272 prints other symbols, but that was even before the Neovim upgrade.
- Operating system/version: Arch Linux
- Terminal name/version: guake 0.8.11, cool-retro-term 1.0.1
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`
Run nvim, type `:`.
```
nvim -u NORC
:
```

### Actual behaviour
Weird stuff is shown (embedded in the message row).
![image](https://user-images.githubusercontent.com/13915536/32546941-f1c37394-c480-11e7-837b-fed469bb808b.png)

### Expected behaviour
Weird stuff is not shown at all.

**Comment by justinmk** [comment]
What $VTE_VERSION ?

**Comment by wdv4758h** [comment]
I can confirm this issue, I have similar system, probably @YanDoroshenko 's guake is based on the same version.

I don't have those wierd stuff in `xterm`, `urxvt` and `lxterminal-gtk3`. Howerver, I get those wierd stuff in `lxterminal`, it's based on `VTE` **0.28.2** for use with GTK2. On the other hand, the `lxterminal-gtk3` is based on `VTE` **0.50.2** for use with GTK3.

**Comment by teto** [comment]
Cursor support arrived in VTE 0.39. To disable the strange characters, either use `:set guicursor` or export an old VTE_VERSION so that neovim can check it.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/7513
