### ISSUE TITLE
nvim displays utf-8 missing glyphs

### ISSUE THREAD

**Issue by ggl** [neovim/neovim#7513]
- `nvim --version`:
NVIM v0.2.2-1-gc46d6f8da
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-829f802e-d125-45c0-be17-a8e9639157a2

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

- Vim (version: ) behaves differently? No
- Operating system/version: 4.4.0-98-generic #121-Ubuntu SMP x86_64 GNU/Linux
- Terminal name/version: xfce4-terminal
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

Open nvim, press : for command mode

### Actual behaviour

Displays UTF-8 missing glyphs. Attempts to use the editor will litter the terminal with missing UTF-8 glyphs making the editor unusable.

### Expected behaviour

Should display : and should work as expected (like Vim 8).

![screenshot_2017-11-08_20-28-52](https://user-images.githubusercontent.com/3610557/32567681-ae79f524-c4c4-11e7-83e9-4f08e56317bf.png)

**Comment by bfredl** [comment]
What version of the terminal? IIRC this is a known issue with old VTE versions.

**Comment by bfredl** [comment]
Could be related to `guicursor`, does `set guicursor=` help?

**Comment by ggl** [comment]
Yes it works after set guicursor=
Shouldn't this be the default?

**Comment by bfredl** [comment]
Nvim assumes that a terminal that calls itself `xterm` can properly handle the sequences an actual xterm can handle. Is this not reasonable? This is a bug in old versions of VTE, fixed in 0.39 according to https://github.com/neovim/neovim/issues/7512#issuecomment-342861543
