### ISSUE TITLE
UI/API: ext_tabline: 'showtabline'

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7516]
Haven't checked yet, but https://github.com/equalsraf/neovim-qt/issues/355 suggests that externalized tabline does not respect 'showtabline'. I think at least this isn't covered in the tests.

cc @dzhou121

**Comment by bfredl** [comment]
Alternatively we could send `showtabline` option to the ui. I will open a PR for ui_call_set_option anyway soon. I would figure there are ~10 options that would make sense to ui, like `guifont` and `imstyle`

**Comment by justinmk** [comment]
Sounds good, but  `ext_tabline` should behave as dictated by 'showtabline' in any case.

**Comment by bfredl** [comment]
Must it? Noshowtabline should mean it shouldn't occupy screen space in the external ui either, but it could make the info displayed in some other way or on demand in some way.

**Comment by justinmk** [comment]
Ah, interesting.

**Comment by bfredl** [comment]
Just noticed, closed by #7520
