### ISSUE TITLE
Windows: Neovim-Qt modifies 'runtimepath'

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7517]
@janlazo [described](https://github.com/neovim/neovim/issues/7433#issuecomment-342702386) an issue with 'runtimepath' modification by nvim-qt:

> Nothing breaks but it's an extra directory in `runtimepath` that shouldn't be there and is specific to nvim-qt because the binary doesn't know that the gui shim plugin is included in nvim's runtime directory. nvim-qt attempts to cd `../share/nvim-qt/runtime` but that doesn't exist in shipped zip. It doesn't check if this directory is in the runtimepath already so setting `NVIM_QT_RUNTIME_PATH` to `..\share\nvim\runtime` adds a duplicate.

Reference:
https://github.com/equalsraf/neovim-qt/blob/master/src/gui/app.cpp#L224

**Comment by janlazo** [comment]
Moving [gui_shim.vim](https://github.com/neovim/neovim/blob/master/runtime/plugin/gui_shim.vim) to `nvim_root_dir/share/nvim-qt/plugin` should solve the problem and avoid loading the shim on the TUI.

Why is it in `$VIMRUNTIME/plugin` to begin with?
