### ISSUE TITLE
Nvim not getting correct terminal size opening session in tmux

### ISSUE THREAD

**Issue by Guitarflier** [neovim/neovim#7519]
MacOS Sierra 10.12.6 + iTerm2, build 3.1.4 + NeoVim 0.2.0_1.  
I run on iTerm a Tmux session loaded with

    teamocil [session]
In one of tmux windows there's an instance of nvim working smoothly, everything is displayed in its own place in all of the bottom three lines, from last one: tmux status bar, nvim command line, nvim status line.
Here's the relevant shot:

[![Everything in place][1]][1]

In another tmux window I want to use a nvim session, sourced with 

    nvim -S [path to session.vim]
But here, in this nvim restored session, Tmux does not allow nvim to display messages in its command line, leaving no free lines between Tmux and nvim status lines. Whatever message displayed ovelaps status line, getting an unreadable mess. See following shot:

[![nvim session mess][2]][2]

It looks like nvim is not getting the correct terminal size when it starts session, either it is not reading it correctly or it is missing the WINCH signal.
Sending a 

    kill -WINCH $PID

signal from another shell solves the problem, so I adopted this as a temporary workaround, sending above command as a slightly delayed background process when opening tmux session.
But I think this is a neovim related issue and has to be fixed. 

Just to make it clear the problem appears only sourcing an existing nvim session inside Tmux.
Thank you.
 

  [1]: https://i.stack.imgur.com/LUlR3.jpg
  [2]: https://i.stack.imgur.com/WOA9O.jpg

**Comment by justinmk** [comment]
"NeoVim 0.2.0_1" looks like 0.2.0, from 6 months ago. There were TUI changes since then. Please try the latest release (0.2.1) or master.

**Comment by Guitarflier** [comment]
Yes I'd like to see if this issue is solved in 0.2.1.
Just waiting to be able to upgrade it from homebrew. At the time it's not available.

**Comment by nateozem** [comment]
@Guitarflier, does it happen if `teamocil` is not used? As @justinmk asked, have you tried this with `Vim`? Homebrew should have that package.

**Comment by Guitarflier** [comment]
@justinmk  and @nateozem. Back to the console, some magic happened in a new shell.
That is, I'm not able to reproduce the problem anymore.
What's strange, I didn't make any changes on my machine since many hours, the only thing I noticed was some homebrew dependencies missing when asking
`brew info neovim`
among which luajit, cmake, lua@5.1, and just installed these. I don't know if the issue could have been somehow related, but I'm really, really relieved.
The only thing I'm still missing is why if I do
`brew upgrade neovim`
I have
`Error: neovim 0.2.0_1 already installed`.
Tank you

**Comment by justinmk** [comment]
> brew upgrade neovim
> Error: neovim 0.2.0_1 already installed.

Try

     brew reinstall neovim

**Comment by mhinz** [comment]
2.1 is not in homebrew yet, but will be in a few hours: https://github.com/Homebrew/homebrew-core/pull/20397

**Comment by Guitarflier** [comment]
@mhinz Tks
