### ISSUE TITLE
Neovim 0.2.1 vim-vinegar bug

### ISSUE THREAD

**Issue by siphiuel** [neovim/neovim#7527]
Hi all!

Thank you for your work on Neovim.

I've just upgraded to Neovim 0.2.1 and noticed that navigating up in netrw using vim-vinegar's shortcut ('-') does not work anymore. It brings the following error message:

```
Error detected while processing function <SNR>37_opendir:
line    7:
E21: Cannot make changes, 'modifiable' is off: <Plug>NetrwBrowseUp
```

Tried reproducing the same with stock macOS Vim (8.0.642), no issues. I'm using Terminal.app, no difference whether running in tmux on not.

Also, when comparing to Vim, I've noticed that navigation in Neovim is slower for some reason.

**UPDATE**: did some investigation, the error is thrown at this line in `s:opendir(cmd)` function from vim-vinegar:
```
execute s:netrw_up
```

**Comment by jamessan** [comment]
Vim 8.0.642 is kinda old.  Can you try with a recent Vim?  I'd wager the same problem exists there, since we just sync runtime files from Vim.

**Comment by siphiuel** [comment]
Just tried Vim 8.0.1250, same thing.

**Comment by jamessan** [comment]
Yeah, this is https://github.com/tpope/vim-vinegar/issues/87.

**Comment by siphiuel** [comment]
Thanks, got it. Switched to vim-dirvish.
