### ISSUE TITLE
Neovim build fails on Debian 9.2.1 while building luarocks

### ISSUE THREAD

**Issue by termonio** [neovim/neovim#7535]
- Fresh install of Debian 9.2.1
- Installed prerequisites
	- `sudo apt-get install libtool libtool-bin autoconf automake cmake g++ pkg-config unzip`
- Cloned git repository
	- `git checkout v0.2.1`
- `make CMAKE_BUILD_TYPE=RelWithDebInfo`

## Expected behavior

Build Neovim for installation (`sudo make install`)

## Actual behavior

- make fails while building `luarocks`

```
[ 87%] Performing configure step for 'luarocks'
Lua version detected: 5.1
Lua interpreter found: /home/auser/neovim/.deps/usr/bin/luajit...
Checking Lua includes... lua.h found in /home/auser/neovim/.deps/usr/include/luajit-2.0/lua.h
Checking if Lua header version matches that of the interpreter... yes
curl found at /usr/bin
md5sum found at /usr/bin
unzip found at /usr/bin
Configuring for system... Linux
Configuring for architecture... x86_64
Using unversioned rocks dir: /home/auser/neovim/.deps/usr/lib/luarocks/rocks
Writing configuration...

Installation prefix: /home/auser/neovim/.deps/usr
LuaRocks configuration directory: /home/auser/neovim/.deps/usr/etc/luarocks
Using Lua from: /home/auser/neovim/.deps/usr

Done configuring.
- Type 'make build' and 'make install':
  to install to /home/auser/neovim/.deps/usr as usual.
- Type 'make bootstrap':
  to install LuaRocks in /home/auser/neovim/.deps/usr as a rock.

[ 88%] No build step for 'luarocks'
[ 89%] Performing install step for 'luarocks'
make[4]: Entering directory '/home/auser/neovim/.deps/build/src/luarocks'
make[4]: Leaving directory '/home/auser/neovim/.deps/build/src/luarocks'
[ 90%] Completed 'luarocks'
make[3]: Leaving directory '/home/auser/neovim/.deps'
[ 90%] Built target luarocks
make[3]: Entering directory '/home/auser/neovim/.deps'
Scanning dependencies of target mpack
make[3]: Leaving directory '/home/auser/neovim/.deps'
make[3]: Entering directory '/home/auser/neovim/.deps'
[ 92%] Generating usr/lib/luarocks/rocks/mpack
make[3]: usr/bin/luarocks: Command not found
CMakeFiles/mpack.dir/build.make:60: recipe for target 'usr/lib/luarocks/rocks/mpack' failed
make[3]: *** [usr/lib/luarocks/rocks/mpack] Error 127
make[3]: Leaving directory '/home/auser/neovim/.deps'
CMakeFiles/Makefile2:571: recipe for target 'CMakeFiles/mpack.dir/all' failed
```

- it seems that luarocks expects `make build` and not just `make`:
	- the following steps fix this issue

```
cd ~/neovim/.deps/build/src/luarocks`
make build
make install
cd ~/neovim
```

- after these steps, `make CMAKE_BUILD_TYPE=RelWithDebInfo` succeeds

**Comment by justinmk** [comment]
in `third-party/cmake/BuildLuarocks.cmake` we do `make bootstrap`. luarocks still supports that, and anyways for the bundled version we have it pinned to 2.4.2 (see `third-party/CMakeLists.txt`).

Could you try again with VERBOSE=1 and  post the verbose cmake log (in a gist please).

    VERBOSE=1 make CMAKE_BUILD_TYPE=RelWithDebInfo

**Comment by termonio** [comment]
I guess I found the culprit. I used the following command to compile Neovim when I experienced the compile error:

`make CMAKE_BUILD_TYPE=RelWithDebInfo -j 4`

If I do not use the switch `-j 4`, the compilation succeeds. Whenever I use `-j 4` the compilation fails while building `luarocks` (tested with `v0.2.1` and `v0.2.2`). I have saved the `cmake` logs in case they are still needed. Just let me know.

**Comment by justinmk** [comment]
Thanks. I think we try to work around this for luarocks, it's a known issue, luarocks breaks in parallel builds. @jszackmeister do you recall?

**Comment by justinmk** [comment]
@termonio could you try https://github.com/neovim/neovim/pull/7697 to see if it works with `-j4`? Remove existing build cache, e.g.:

```
rm -rf build
rm -rf .deps
make CMAKE_BUILD_TYPE=RelWithDebInfo -j4
```

**Comment by termonio** [comment]
@justinmk I can confirm that [https://github.com/neovim/neovim/pull/7697](https://github.com/neovim/neovim/pull/7697) indeed solves this issue (works with `-j4`).
