### ISSUE TITLE
Netrw_gx stopped working on 0.2.1

### ISSUE THREAD

**Issue by gadkadosh** [neovim/neovim#7536]
Since upgrading to 0.2.1 the `gx` key mapping doesn't work for me on macOS anymore. It used to open a url under the cursor automatically in the default browser. Now it downloads it with curl to a temp directory. 
There are no settings related to it in vimrc and it's the same with `nvim -u NORC`.
It used to work in 0.2.0 and still works in Vim.

**Comment by jamessan** [comment]
> It used to work in 0.2.0

Well, the runtime files were updated between 0.2.0 and 0.2.1.

> and still works in Vim.

I doubt that's the case with the latest Vim, since we merge runtime files from Vim.  You're likely using an older version of Vim which doesn't have the same version of netrw as is in Neovim.

**Comment by gadkadosh** [comment]
The Vim I have installed is `Included patches: 1-1250`, which is about a week old. Haven't tried a newer version, as I don't actually use it. But I can try if it's helpful.

**Comment by jamessan** [comment]
The runtime [update](https://github.com/vim/vim/commit/b0d45e7f5354375edd02afafde3bd37dac1515ff) that included netrw was after 8.0.1250, so that's why you aren't seeing the issue in Vim.

**Comment by gadkadosh** [comment]
Just compiled a newer one, and it doesn't work there indeed

**Comment by jamessan** [comment]
Ok, so this needs to be resolved upstream with Vim.  The maintainer (listed at the top of runtime/plugin/netrw.vim) should be notified and he'll send the fix to Bram when it's ready.

**Comment by victoriastuart** [comment]
Just a note that I am also now experiencing this issue, with NVIM v0.2.1 (Arch Linux x86_64).  `gx` on a link opens the link in a temp file (file:///...) in the browser, WHILE also closing that buffer in Neovim.  :-(  Worked perfectly, before.

**Comment by ykrivopalov** [comment]
I also got an issue with netrw after updating to nvim 0.2.1, but a different one. It reproduces with autochdir set. I'm not sure is it neovim or netrw bug, I just decided to switch to dirvish and try to live without autochdir :)

How to reproduce (just for case):
1. Use init.vim with only "set autochdir"
2. Open nvim
3. `<C-w>v`
4. `:Explore` ; open file in a current dir
5. `<C-w>l` ; `:Explore` ; open subdirectory
= one window immediately closes

Also after this condition (with my full vimrc), I got a crash:
```
                #0  0x000055dbb3a4f080 n/a (nvim)
                #1  0x000055dbb3a522eb syntax_clear (nvim)
                #2  0x000055dbb3a53cf8 n/a (nvim)
                #3  0x000055dbb3a525ef ex_syntax (nvim)
                #4  0x000055dbb3939ec4 do_cmdline (nvim)
                #5  0x000055dbb38f7274 call_user_func (nvim)
                #6  0x000055dbb38f7c8c call_func (nvim)
                #7  0x000055dbb38fce38 n/a (nvim)
                #8  0x000055dbb390195a ex_call (nvim)
                #9  0x000055dbb3939ec4 do_cmdline (nvim)
                #10 0x000055dbb3956911 n/a (nvim)
                #11 0x000055dbb39575d7 apply_autocmds (nvim)
                #12 0x000055dbb39d0b86 n/a (nvim)
                #13 0x000055dbb39d762c do_set (nvim)
                #14 0x000055dbb3939ec4 do_cmdline (nvim)
                #15 0x000055dbb3900197 ex_execute (nvim)
                #16 0x000055dbb3939ec4 do_cmdline (nvim)
                #17 0x000055dbb3956911 n/a (nvim)
                #18 0x000055dbb39575d7 apply_autocmds (nvim)
                #19 0x000055dbb39d0bf8 n/a (nvim)
                #20 0x000055dbb39d5497 set_option_value (nvim)
                #21 0x000055dbb3939ec4 do_cmdline (nvim)
                #22 0x000055dbb3956911 n/a (nvim)
                #23 0x000055dbb395bb83 readfile (nvim)
                #24 0x000055dbb38c0dba open_buffer (nvim)
                #25 0x000055dbb391f465 do_ecmd (nvim)
                #26 0x000055dbb393da0d do_exedit (nvim)
                #27 0x000055dbb3939ec4 do_cmdline (nvim)
                #28 0x000055dbb393c74f do_cmdline (nvim)
                #29 0x000055dbb3900197 ex_execute (nvim)
                #30 0x000055dbb3939ec4 do_cmdline (nvim)
                #31 0x000055dbb38f7274 call_user_func (nvim)
                #32 0x000055dbb38f7c8c call_func (nvim)
                #33 0x000055dbb38fce38 n/a (nvim)
                #34 0x000055dbb38fac75 n/a (nvim)
                #35 0x000055dbb38fb7e1 n/a (nvim)
                #36 0x000055dbb38fbb14 n/a (nvim)
                #37 0x000055dbb38fc7b1 n/a (nvim)
                #38 0x000055dbb38fc951 n/a (nvim)
                #39 0x000055dbb38fcc3a n/a (nvim)
                #40 0x000055dbb390195a ex_call (nvim)
                #41 0x000055dbb3939ec4 do_cmdline (nvim)
                #42 0x000055dbb39b3928 n/a (nvim)
                #43 0x000055dbb39bce88 n/a (nvim)
                #44 0x000055dbb3a4ba56 state_enter (nvim)
                #45 0x000055dbb39b42da normal_enter (nvim)
                #46 0x000055dbb389dfba main (nvim)
                #47 0x00007f38da5f8f6a __libc_start_main (libc.so.6)
                #48 0x000055dbb389ee4a _start (nvim)
```
if crash will reproduce without netrw, then I'll create an issue

**Comment by swalladge** [comment]
This issue is back... (master at time of writing)

**Comment by blueyed** [comment]
@swalladge 
Can you git-bisect it, please?

**Comment by swalladge** [comment]
@blueyed Yep for sure - as soon as I have time I'll do that and open a new issue. :+1:

**Comment by janlazo** [comment]
Fixing this requires porting https://github.com/vim/vim/issues/4738 which is currently not merged.
