### ISSUE TITLE
Update to type 2 AppImage

### ISSUE THREAD

**Issue by probonopd** [neovim/neovim#7537]
https://twitter.com/dahanbn/status/928948089737670656 says:

> Nvim.appimage fails due to missing libfuse.so. 2. 

This is because it is still a type 1 AppImage. Type 2 is newer and supports cool tricks like the `--appimage-extract` switch which makes it possible to extract the content of an AppImage even on systems where FUSE is not present.

While we are at it, we may consider to switch from a bash script to using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) for generating the AppImage.

**Comment by justinmk** [comment]
@probonopd Thank you for the notice! Great to know about that feature.

Hope someone can work on this, I won't have time right now.

Previous work: https://github.com/neovim/neovim/pull/6638 , https://github.com/neovim/neovim/pull/6676

**Comment by gwerbin** [comment]
Is there a workaround in the meantime? Would love to use Neovim on my company's server.

**Comment by probonopd** [comment]
```
sudo mount -o loop Some.AppImage /mnt
/mnt/AppRun
```

**Comment by gwerbin** [comment]
I take if there's no way to do it without `sudo` access? This is on a shared server where I'm not an admin, hence the AppImage install.

**Comment by probonopd** [comment]
A type-1 AppImage is an ISO, so

```
sudo apt install libarchive-tools
mkdir AppDir
cd AppDir
bsdtar xfp /home/me/Downloads/Some.AppImage
./AppRun
```
also works.

**Comment by sohnryang** [comment]
Should we use [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) for this? It seems pretty unstable.

**Comment by probonopd** [comment]
> Should we use linuxdeployqt for this? 

Yes, why not. Should remove the need for much of the manual work.

> It seems pretty unstable.

If you are running into trouble, please open an issue at https://github.com/probonopd/linuxdeployqt/issues. There are many examples of projects happily using it.

**Comment by sohnryang** [comment]
Thanks, @probonopd!

**Comment by justinmk** [comment]
linuxdeployqt looks good, just need someone to shave the yak...

**Comment by raghur** [comment]
Know very little of AppImage internals - but does type 2 also support updates? Today I used the AppImageUpdate on neovim app image and it basically said it couldn't find update info.

```
Could not find update information in the AppImage. Please contact the author of the AppImage and ask them to embed update information.
```

**Comment by jamessan** [comment]
> does type 2 also support updates

Yes.

> I used the AppImageUpdate on neovim app image and it basically said it couldn't find update info

That's because we haven't defined the metadata that `AppImageUpdate` expects, as the message you posted explains.
