### ISSUE TITLE
Unicode test failure on neovim-0.2.1/OpenBSD

### ISSUE THREAD

**Issue by vext01** [neovim/neovim#7542]
```
NVIM v0.2.1
Build type: Release
Lua 5.1
Compilation: /usr/ports/pobj/neovim-0.2.1/bin/cc -O2 -pipe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/usr/ports/pobj/neovim-0.2.1/build-amd64/config -I/usr/ports/pobj/neovim-0.2.1/neovim-0.2.1/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/ports/pobj/neovim-0.2.1/build-amd64/src/nvim/auto -I/usr/ports/pobj/neovim-0.2.1/build-amd64/include
Compiled by edd@wilfred.home

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

When running the old tests:

```
Test results:


From test_startup_utf8.vim:
Found errors in Test_read_fifo_utf8():
function RunTheTest[13]..Test_read_fifo_utf8 line 24: Expected ['テスト', '€ÀÈÌÒÙ'] but got []
TEST FAILURE
```

Any ideas?

Thanks

**Comment by vext01** [comment]
What's funny about this, is that not everyone can reproduce it.

I can on both my desktop and under a virtual machine, but a friend (who also uses OpenBSD) cannot. We have tried a few different `LC_CTYPE`s and `TERMs` and even different terminals, but thus far have not been able to figure this out...

Do the neovim devs have any ideas?

**Comment by justinmk** [comment]
For the lua tests we set LC_ALL : https://github.com/neovim/neovim/pull/7087/files#diff-6aeb5c8ef067f3817682ee92fd59b77fR2

Maybe we need to do that for oldtest (`src/nvim/testdir`) as well. (I didn't check if we already try to, somewhere.)

**Comment by vext01** [comment]
I'll give that a go, thanks.

**Comment by vext01** [comment]
Hrm, I'm running the tests for a port Makefile like this:

```
do-test:
        cd ${WRKSRC} && env LC_ALL=en_US.UTF-8 ${MAKE_PROGRAM} \
                -C src/nvim/testdir NVIM_PRG=${WRKBUILD}/bin/nvim ${MAKE_FLAGS}
```

And I'm still getting:

```
From test_startup_utf8.vim:
Found errors in Test_read_fifo_utf8():
function RunTheTest[13]..Test_read_fifo_utf8 line 24: Expected ['テスト', '€ÀÈÌÒÙ'] but got []
TEST FAILURE
```

**Comment by jamessan** [comment]
Could be useful to compare ktraces for a successful execution of that specific test and a failing one.

I probably won't be able to look into this until after next week.

**Comment by mulander** [comment]
Hi,

I executed the test as following

```
$ pwd
/usr/local/pobj/neovim-0.2.1/neovim-0.2.1/src/nvim/testdir
$ ktrace VIMRUNTIME='ktrace ../../../runtime'; export VIMRUNTIME;  /usr/local/pobj/neovim-0.2.1/build-amd64/bin/nvim -u unix.vim -U NONE --headless --noplugin -u NONE -S runtest.vim test_startup_utf8.vim 
ktrace: exec of 'VIMRUNTIME=ktrace ../../../runtime' failed: No such file or directory
"test_startup_utf8.vim" "test_startup_utf8.vim" 64L, 1366C
Executing Test_read_fifo_utf8()
Executing Test_read_stdin_utf8()"test_startup_utf8.res" "test_startup_utf8.res" 0L, 0C"test_startup_utf8.res" "test_startup_utf8.res" 0L, 0C written
Executed 2 tests"messages" "messages" 815L, 23885C"messages" "messages" 820L, 23996C written$ echo $?
0
$ 
```

then ran `kdump > /home/mulander/neovim.txt`. The output of this command is attached to this comment.
[neovim.txt](https://github.com/neovim/neovim/files/1483776/neovim.txt)

**Comment by vext01** [comment]
And here's my kdump using the same command.
[edds-kdump.txt](https://github.com/neovim/neovim/files/1483903/edds-kdump.txt)

I'll take a look at the differences once I get a moment.

**Comment by vext01** [comment]
Doing the same a mulander:

```
arrakis:testdir> VIMRUNTIME='../../../runtime'; export VIMRUNTIME;  ktrace /usr/local/pobj/neovim-0.2.1/build-amd64/bin/nvim -u unix.vim -U NONE --headless --noplugin -u NONE -S runtest.vim test_startup_utf8.vim
"test_startup_utf8.vim" "test_startup_utf8.vim" 64L, 1366C
Executing Test_read_fifo_utf8()
Executing Test_read_stdin_utf8()"test.log" "test.log" 9L, 347C"test.log" "test.log" 13L, 520C written
Executed 2 tests
1 FAILED:"messages" "messages" 781L, 23305C"messages" "messages" 789L, 23570C written
```

[fail.txt](https://github.com/neovim/neovim/files/1483910/fail.txt)

**Comment by vext01** [comment]
Sorry, I had to delete my ktrace as it contained the contents of files that I had been editing, including emails. That's scary. No idea why that kind of thing should be in the trace!

**Comment by vext01** [comment]
Anyway, this suggests that nvim is not running in a clean environment. Could this be the issue?

**Comment by mulander** [comment]
I did the same as @vext01  and decided to remove the file - why does neovim touch those files on startup? It seems to be chunking them in with mmap, is there a purpose for this?

**Comment by mhinz** [comment]
Yup, `shada` is an improved `viminfo`, which is used by Vim. If you don't want it, put `set shada=` in your vimrc or disable it only temporarily via `nvim -i NONE`.

**Comment by vext01** [comment]
OK, here's why mulander didn't see the test failure:

```
  if executable('bash')
    set shell=bash
  elseif executable('zsh')
    set shell=zsh
  else
    return
  endif
```

He had neither bash, nor zsh installed. He was using ksh.

So this test just fails on OpenBSD.

**Comment by vext01** [comment]
FWIW, I have both installed. The test twill use bash.

I'm using:
```
GNU bash, version 4.4.12(1)-release (x86_64-unknown-openbsd6.2)
```

**Comment by vext01** [comment]
Emulating the test by hand under zsh:

```
$ cat Xtestin                                                                                             
テスト
€ÀÈÌÒÙ
$ vim --cmd "set enc=utf-8 | set fencs=cp932,utf-8" -c "write ++enc=utf-8 Xtestout | quit"  <(cat Xtestin)
$ 
```

This is the problem I think.

**Comment by vext01** [comment]
What the test suite does is actually a bit more like this:
```
wilfred:/tmp> cat Xtestin 
 テスト
€ÀÈÌÒÙ

wilfred:/tmp> r2 Xtestin 
 -- If you want to open the file in read-write mode, invoke r2 with '-w'
[0x00000000]> px
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  20e3 8386 e382 b9e3 8388 0ae2 82ac c380   ...............
0x00000010  c388 c38c c392 c399 0a0a ffff ffff ffff  ................
0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000030  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000040  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000050  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000080  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00000090  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x000000f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
^D
wilfred:/tmp> cat before.vim
set enc=utf-8
set fencs=cp932,utf-8

wilfred:/tmp> cat after.vim 
write! ++enc=utf-8 Xtestout
quit

wilfred:/tmp> vim --cmd "so before.vim" -S after.vim  <(cat Xtestin)
wilfred:/tmp> cat Xtestout
```

If we simplify this to:

```
$ vim --cmd "so before.vim" <(cat Xtestin)
```

I see in the status area:

```
"/dev/fd/11" is not a file
````

I was really surprised to see that this file exists on my OpenBSD laptop. I've never heard of `/dev/fd/*`:

```
$ file /dev/fd/11
/dev/fd/11: character special (22/11)
```

I'm not really sure why you would use these device nodes instead of a plain `open()` syscall, but it seems to be something wrong with the nvim code that opens/reads these dev nodes.

Incremental progress...

**Comment by jamessan** [comment]
> I'm not really sure why you would use these device nodes

It's testing detection of encoding when reading from a fifo.  That's why it's going through the hassle of using `<(cat Xtestin)`.



> "/dev/fd/11" is not a file

This shouldn't be happening.  That means that [this code](https://github.com/neovim/neovim/blob/d9b3ebfede6439aab4148c4bbf117b8950ed6aa0/src/nvim/fileio.c#L434-L436) isn't considering that a fifo.

When I run `stat -L <(ls)` on my Linux system, it says the file is a fifo.  Is there an equivalent for OpenBSD?

**Comment by jamessan** [comment]
Also, does Vim's own test succeed?

**Comment by vext01** [comment]
Quick test of `/dev/fd/*` to check for the possibility that it's bust on OpenBSD:

```
wilfred:/tmp> cat fd.c
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>

int
main(int argc, char **argv)
{
        int fd, fd2, rv;
        char *p;
        char buf[16];
        ssize_t r;

        fd = open("/tmp/a", O_RDONLY);
        printf("fd=%d\n", fd);

        rv = asprintf(&p, "/dev/fd/%d", fd);
        printf("path=%s\n", p);

        fd2 = open(p, O_RDONLY);
        printf("fd2=%d\n", fd2);

        r = read(fd2, buf, 1);
        printf("read %zd bytes\n", r);
        printf("%c\n", buf[0]);

        return (EXIT_SUCCESS);
}
wilfred:/tmp> cat a
zzz
wilfred:/tmp> ./a.out 
fd=3
path=/dev/fd/3
fd2=4
read 1 bytes
z
```

Seems ok to me.

As for your above test:
```
wilfred:edd> stat -L <(ls)
1040 1820047 crw-rw-rw- 1 root wheel 5643 0 "Nov  7 17:30:38 2017" "Nov  7 17:30:38 2017" "Nov  7 17:30:38 2017" 65536 0 0 /dev/fd/11
```

I suppose the `c` in the mode means "character device".

Vim's own test? You mean regular vim?

**Comment by jamessan** [comment]
> Quick test of /dev/fd/* to check for the possibility that it's bust on OpenBSD

That's not testing the same thing.  The test isn't whether Vim can open `/dev/fd/...`.  That filename is an implementation detail of the command substitution (`<(ls)`) that the shell is performing.

The test is checking whether (n)vim can properly detecting the encoding when editing a _fifo_.

> Vim's own test? You mean regular vim?

Correct.

From a git clone, you can run the test with `make && make -C src/testdir test_startup_utf8.res`.

Then `cat src/testdir/messages` will show the results.

**Comment by jamessan** [comment]
What does `stat -L -f "%N: %HT%SY" <(ls)` show?

**Comment by justinmk** [comment]
os_nodetype was recently changed (it should behave exactly like vim now....). Does reverting it to the 0.2 0 version fix the issue?

**Comment by vext01** [comment]
@jamessan
```
wilfred:edd> stat -L -f "%N: %HT%SY" <(ls)
/dev/fd/11: Character Device
```

@justinmk At the time I imported neovim-0.2.0 into ports, all old tests passed. @mulander was saying the other day that this test is new though.

**Comment by vext01** [comment]
WRT the original vim tests, it's broken there too:

```
From test_startup_utf8.vim:
Executing Test_read_fifo_utf8()
Executing Test_read_stdin_utf8()
Executed 2 tests
1 FAILED:
Found errors in Test_read_fifo_utf8():
function RunTheTest[38]..Test_read_fifo_utf8 line 24: Expected ['テスト', '€ÀÈÌÒÙ'] but got []
```

**Comment by vext01** [comment]
I confirm that this fix causes the test to pass.

```
From test_startup_utf8.vim:
Executing Test_read_fifo_utf8()
Executing Test_read_stdin_utf8()
Executed 2 tests
```

And, just to be sure, when I do the test manually, all is well:
```
wilfred:/tmp>  vim --cmd "so before.vim" -S after.vim  <(cat Xtestin)
wilfred:/tmp> cat Xtestout
 テスト
€ÀÈÌÒÙ
```

Yay :)

So shall we close this?

**Comment by vext01** [comment]
And thank you to the neovim devs for this :)

**Comment by jamessan** [comment]
Which commit did you test?  The initial commit in the PR was the obvious fix, but the second commit changes to a hopefully more blanket fix.

**Comment by vext01** [comment]
They both work :)
