### ISSUE TITLE
API: expose fold info; UI: display virtual chars beyond EOL

### ISSUE THREAD

**Issue by andreyorst** [neovim/neovim#7544]
## Preface

This is not an issue, or really a feature request, but a question of possibility. 

So, about indentation lines (shortly):
Indentation line is a thin column that goes from the begining of the code block to the end of it to help visually detect scopes, folds etc. It really helps to read code with deep indented constructions. All modern IDEs and editors provide this functional out of the box.

## Plugins

There is at least two plugins which can provide such thing [Vim Indent Guides](https://github.com/nathanaelkane/vim-indent-guides) and [IndentLine](https://github.com/Yggdroot/indentLine), but they have some problems. IndentLine woks only with spaces and it's getting slow on big and deeply indented files, Indent Guides feels a bit distracting for me. I prefer using tab for indentation, and spaces for alignment, so I use custom listchars in my init.vim to display some kind of indentation lines. But the most common problem of all those methods is that there is no way to display continuous line if there is an empty line in the code. For example:

![image](https://user-images.githubusercontent.com/19470159/32697010-3302378c-c797-11e7-935b-1dc41040d262.png)

And another editor to compare:
![image](https://user-images.githubusercontent.com/19470159/32697016-73d4b4e2-c797-11e7-8306-f34d1c4865b0.png)
(don't judge the code, it was first what came to mind, we're all have a real code with a lot worse indentation mess)

You can think, that this is not that important, but it is, because when doing a quick lookup on a code from other person wrote it really helps not to get lost in indentation mess.

So the question is: Is it possible to use folding engine to do such a thing?
----
I use vim folds a lot, because unfortunately I need to work with damn long files of code. The settings that I use are simple:

```
set foldmethod=indent    " syntax doesn't work as i usually expect it to
set foldlevelstart=20    " to prevent automatically closing folds on file open
```

And the folds work pretty well already. Empty lines don't broke folding, and every thing can be folded separately.

Given that, I've came to a question: If vim can detect folds based on indentation (and syntax), and another editors commonly display indentation lines over structures that also can be folded, can we use vim fold detector to get an information about indentation, and display indentation lines based on this?

Because upon file open we are already detected all folds (and closed them automatically) why can't we use this information again? Newly folds get detected on the fly, so it shouldn't be a problem.

**Comment by justinmk** [comment]
IIUC you're asking for a API that exposes folds info. Seems reasonable.

**Comment by bfredl** [comment]
The question is also how to display it. I think the ability to do "virtual conceal" i e display chars outside the ends of the line has been discussed before. Of course, with external ui we could add something like `ui_call_vectical_line(x,ystart,yend,color)`

**Comment by KillTheMule** [comment]
> IIUC you're asking for a API that exposes folds info. Seems reasonable.

I found that I'd be interested in that as well. Hopefully not just info, but manipulation possibilities beyond "move the cursor where you need it and send `zd`" or similar.

**Comment by andreyorst** [comment]
> IIUC you're asking for a API that exposes folds info. Seems reasonable.

Yes.

> The question is also how to display it. I think the ability to do "virtual conceal" i e display chars outside the ends of the line has been discussed before.

What about empty lines itself? I mean, when IndentLine draws a `|` it does the drawing on a certain whitespace, depending, i believe, on `shiftwidth` setting. The problem is that the empty lines are containing only `eol` character, so we cant draw `|` there, because there is no whitespace after eol, am I right?

>  Of course, with external ui we could add something like ui_call_vectical_line(x,ystart,yend,color)

I'm not very familiar with designing TUI and ncurses, but i thought, that such thing should be handled by ncurses drawing system.

**Comment by bfredl** [comment]
We "can't" in the sense that the code is not there. But I see no hindrance to add it other than "win_line is already hideously complex"

ncurses is a library;nvim doesn't use it. Question is what the _terminal_ can, I don't think any of the commonly used ones implements vlines between cells. We can of course use unicode border chars, but it will be the middle of a cell, just like pipe char.

**Comment by andreyorst** [comment]
> We can of course use unicode border chars, but it will be the middle of a cell, just like pipe char.

`|▏¦┆│⎸`
There are plenty of thin vertical bars in unicode, For example this one `▏` is higher than a regular `|` and it appears slightly to the left in the cell. I use this one in my listchars to display tabs .

But it depends on the font and linespacing, so in other terminal it may appear not like the line, but like the "dotted line". So this is not the best way.
For example this text:
```
void foo()
{
▏   int a;
▏   while(a > 0) {
▏   ▏   a++;
▏   cout << a << '\n';
}
```
will apperar in my terminal like so:
![image](https://user-images.githubusercontent.com/19470159/32699939-fd485d96-c7ce-11e7-84a1-676ec64702ff.png)
Solid left aligned lines. But if I'll change font it possibly will break (I tried a lot of fonts, and it still solid).

**Comment by bfredl** [comment]
Yes that's true; I mainly meant it will always occupy a cell, which is fine in this case. But there is there is other cases we might want to draw a thin line between cells. For instance, thin window borders and less intrusive colorcolumn.

**Comment by andreyorst** [comment]
> The question is also how to display it.

I think that it could be done in the same way how colorcolumn id doing this. Yes it is thick, but it is not occupying a cell, and i believe can change color on the fly for active _fold/indented block_, and also can be drawn on empty lines.
something like this:
![image](https://user-images.githubusercontent.com/19470159/35209237-bc1c4d34-ff5d-11e7-86df-9816af22c3e1.png)
but we need to draw it in the vertical range of the fold, like `ui_call_vectical_colorcolumn(x,ystart,yend,color)` with cell coordinates, but not displaying it on actual `{}` symbols.

**Comment by SicariusNoctis** [comment]
Just linking a corresponding discussion on reddit:

https://www.reddit.com/r/vim/comments/8gxqoc/better_looking_indent_guides

**Comment by justinmk** [comment]
> "virtual conceal" i e display chars outside the ends of the line

Addressed in https://github.com/neovim/neovim/pull/8180 . Currently only supports in-line. More general virtual text tracked in https://github.com/neovim/neovim/issues/1767 .

> API: expose fold info

Tracked in https://github.com/neovim/neovim/issues/8538

**Comment by banderlog** [comment]
Alas, proper indent guides still absent in vim/neovim

**Comment by bfredl** [comment]
@banderlog you will have better luck checking recent issues rather than necroposting an issue closed three years ago
