### ISSUE TITLE
In Neovim ,how switch command mode on terminal mode 

### ISSUE THREAD

**Issue by diqye2014** [neovim/neovim#7549]
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Expected behaviour

:terminal enter TERMINAL MOD ，I want switch to command mod by shortcut key

**Comment by justinmk** [comment]
`:help terminal`

Please use issue tracker for bug reports only.

**Comment by KillTheMule** [comment]
To elaborate, it's better to ask questions at e.g. https://www.reddit.com/r/neovim/. Also see https://neovim.io/community/.
