### ISSUE TITLE
Feature Request: change order of buffers in buffer list

### ISSUE THREAD

**Issue by gibfahn** [neovim/neovim#7558]
Hope this is the right way to do this.

See https://github.com/ap/vim-buftabline/issues/8#issuecomment-124977497.

Given that buffers are really what we'd call tabs in other programs (e.g. browsers or terminals), it'd be ideal if it was possible to treat them the same way.

- [vim-buftabline](https://github.com/ap/vim-buftabline) allows you to see a "buffer bar".
- `:bn`, `:bp`, and `:b 5` allow you to easily switch between them

But there isn't a good way (as far as I know) to change the order of the buffers in the buffer list, maybe a move buffer and a swap buffer command.

I know some plugins get around this by implementing their own virtual buffer list, but that seems bug-prone.

Does this seem reasonable? Sorry if it's a duplicate, had a look but didn't find anything.

**Comment by justinmk** [comment]
> Given that buffers are really what we'd call tabs in other programs

Why not use actual tabs for that?

The buffer list is just a list. The fact that `:ls` shows them one way doesn't mean you can't list them another way, with a plugin.

Buffer numbers are ids, they cannot and must not be changed.

> :bn, :bp, and :b 5 allow you to easily switch between them

No need to memorize buffer numbers, `:buffer` accepts partial names. E.g. `:b foo` switches to `/blah/foo.txt`.

 Try this mapping:

    nnoremap <C-b> :set nomore<bar>ls<bar>set more<cr>:buffer<space>

**Comment by gibfahn** [comment]
>Why not use actual tabs for that?

Because they don't really make sense for that.

https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs
http://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/

>No need to memorize buffer numbers, :buffer accepts partial names. E.g. :b foo switches to /blah/foo.txt.

Yeah I do use that. However I rarely find I need more than five or six open buffers, so It's still quicker to just use <kbd>Tab</kbd> and <kbd>Shift</kbd><kbd>Tab</kbd> (`:bn` and `:bp`) to switch between them, and <kbd>Leader</kbd><kbd>d</kbd> to delete (`:bd`), so being able to reorder would be nice.

>>I know some plugins get around this by implementing their own virtual buffer list

>The buffer list is just a list. The fact that :ls shows them one way doesn't mean you can't list them another way, with a plugin.

Yeah, as I said I know you can implement your own list, but as this is the only case in which you can't just use the built-in one it seemed worth asking whether changing the order was possible.

>Buffer numbers are ids, they cannot and must not be changed.

Okay, sounds pretty conclusive, thanks.

**Comment by ap** [comment]
> Buffer numbers are ids, they cannot and must not be changed.

But mustn’t they really? What depends on the number staying unchanged?

**Comment by ap** [comment]
@justinmk:

> Buffer numbers are ids, they cannot and must not be changed.

But mustn’t they really? What depends on the number staying unchanged?

**Comment by justinmk** [comment]
@ap plugins often store it. 

NB. This was discussed in more detail in another issue.

**Comment by bfredl** [comment]
Changing buffer numbers would also imply breaking the buffer number = API handle identity. Certainly we want to avoid that.

**Comment by jmbeach** [comment]
Came here looking for the answer, but just dawned on me that something that mostly solves the problem for me is having a quick way to move the buffer to the end of the list: you can make a shortcut to close the buffer and open a new buffer with the same file and that will effectively move it to the end.
