### ISSUE TITLE
Cursor no longer changing on macOS High Sierra (0.2.0 -> 0.2.1)

### ISSUE THREAD

**Issue by gibfahn** [neovim/neovim#7559]
- `nvim --version`: 0.2.1 +
- nvim (version: ) behaves differently? 0.2.0 (`/usr/local/Cellar/neovim/0.2.1/bin/nvim`)
- Operating system/version: macOS High Sierra 
- Terminal name/version: `Terminal.app` (and `Alacritty`)
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

`nvim -u NORC`

### Actual behaviour

Cursor is what it was in the shell before running vim (usually I-bar).

### Expected behaviour

Cursor starts as a block (normal mode), and becomes an I-bar when you go into insert mode.

### Other info

`set guicursor` returns `guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20` for both 0.2.0 and 0.2.1

I know there have been some changes here, so sorry if I just need to set something different now. 

I can't reproduce this on my Linux box, but I can reproduce by building from source on the latest master (30a21830d06f1e99431c2a632133577841b10c32).

**Comment by justinmk** [comment]
Terminal.app does not support cursor shaping. For alacritty see https://github.com/neovim/neovim/issues/7550#issuecomment-343840499
