### ISSUE TITLE
:terminal-mode <C-o> (CTRL-o)

### ISSUE THREAD

**Issue by hiberabyss** [neovim/neovim#7565]
Now, we could exit `Terminal` mode via `<C-\><C-n>`. Is there any way to temporarily exit `Terminal` mode like `<C-o>` in VIM insert mode?

The scenario is that we may want to run a VIM command for the terminal buffer, and we expect the buffer keep `Terminal` mode after command finished.

Thanks!

**Comment by KillTheMule** [comment]
I thought 'good idea', but then I realized what I'd utilize is the opposite: Be in normal mode in a terminal buffer, press `<C-o>`, fire off a command, and after pressing enter have returned to normal mode.

**Comment by GCorbel** [comment]
I agree with this feature. Do a `<C-o>` in insert mode on the terminal can be super useful.

**Comment by vsudakov** [comment]
I got very surprised - there is no `<C-o>` in neovim. I use that in pure vim very often...

**Comment by bfredl** [comment]
hmm not sure if we want a default binding but we could a command so you could `tnoremap <whatever> <C-\><C-n><cmd>restartedit<cr>` and have it behave similarily to `<c-o>`

**Comment by seandewar** [comment]
Implemented in #19584
