### ISSUE TITLE
Interactive terminal command not working properly in 0.2.1

### ISSUE THREAD

**Issue by YanDoroshenko** [neovim/neovim#7566]
Interactive terminal commands (`:!git add -p %`) not working properly after upgrade to 0.2.1.
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? `Vim 8.0.1297` works fine (same as Neovim 0.2.0).
- Operating system/version: Arch Linux
- Terminal name/version: `guake 0.8.11`, `gnome-terminal 3.26.2`.
- `$TERM`: `xterm`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:! git add -p %

```

### Actual behaviour
Neovim does not ask for any input and just prints the terminal output.
![image](https://user-images.githubusercontent.com/13915536/32836201-523ec4b6-ca09-11e7-9448-30bd6610bba4.png)

### Expected behaviour
Neovim prompts for input as it should (screenshot from Vim):
![image](https://user-images.githubusercontent.com/13915536/32836314-9dbf2278-ca09-11e7-8c39-7d4ff7b95801.png)

**Comment by jamessan** [comment]
Neovim 0.2.0 does not behave as you expect either.  This has been a long-standing change in behavior from Vim.  See the [FAQ](https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes).

Try `:term git add -p` or [fugitive](https://github.com/tpope/vim-fugitive)'s `:Gstatus` command.

**Comment by YanDoroshenko** [comment]
@jamessan Tried. Both `term git add -p` and `:Gstatus p` open the terminal output as a new buffer which does not do much for me. Does it mean there's no way to do a `git add -p` from Neovim now?

**Comment by ZyX-I** [comment]
@YanDoroshenko What do you mean by “does not not do much”? It is exactly how this is supposed to work now. In some cases though additional code will be needed to restore pre-terminal-buffer-opening state, don’t know whether fugitive has code with this purpose and just using `:terminal` definitely does not.

With floating windows support the job of opening and closing temporary buffer without disturbing the view should be easier, and there were proposals to use that for `:!` as request to run interactive apps is not uncommon, but at the time being Neovim does not have anything which may be used for your task, but `:terminal`.
