### ISSUE TITLE
Echoing iterm2 escape codes does not work

### ISSUE THREAD

**Issue by remofritzsche** [neovim/neovim#7567]
Thanks a bunch for having a look at this. It's the only think stopping me from switching to nvim :) Keep up the amazing work you're doing 🥇 

- `nvim --version`: NVIM v0.2.0
- Vim (version: 8.0) behaves differently
- Operating system/version: macOs 10.13 (17A405) High Sierra
- Terminal name/version: iTerm Build 3.1.4.beta.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
!echo "\e]1;Hello World\a"
```

### Actual behaviour

Nothing happens but a "bell".

### Expected behaviour

The escape sequence should be recognized by iTerm2 and change the window title to "Hello World". In `vim`, the exact same command works as expected and without producing any bell.

**Comment by justinmk** [comment]
`:!` uses pipes, it is not connected to the tty. You would find the same behavior in gvim, for example.

Use `'guicursor'` to configure the cursor style (works in the TUI, not just GUIs).

See also https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes

**Comment by remofritzsche** [comment]
Thanks a lot for your answer. I'm not just using these escape sequences for setting cursor but also for window title and for switching the iTerm2 profile when entering and exiting vim. Is there no way of "communicating" to the current tty / process within neovim?
