### ISSUE TITLE
neovim reload '~/.vimrc' on write when editing 'init.vim'

### ISSUE THREAD

**Issue by cinghiopinghio** [neovim/neovim#7570]
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.0 ) behaves differently? It behave as expected
- Operating system/version: Arch linux (uptodate)
- Terminal name/version: termite
- `$TERM`: `xterm-termite`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC ~/.config/nvim/init.vim
```
or
```
nvim ~/.config/nvim/init.vim
```
do something (or even nothing ... ) and save `:w`

### Actual behaviour

nvim source `~/.vimrc` (with or without `-u NORC`).

### Expected behaviour

nvim should no nothing if using `-u NORC` and should source `~/.config/nvim/init.vim` otherwise.
Moreover `$MYVIMRC` points to the right place (`~/.config/nvim/init.vim`) when I read `init.vim` and is empty when I use `-u NORC`, as expected.
Any clue?

**Comment by ZyX-I** [comment]
This just looks like you have a plugin which automatically sources vimrc when it is written. Note that -u NORC does not disable your plugins if you place them where expected by default.

**Comment by justinmk** [comment]
There's no feature in Nvim that sources `~/.vimrc`. Sounds like a configuration/plugin/environment issue. Please ask those questions on https://vi.stackexchange.com/ , not the issue tracker.

**Comment by cinghiopinghio** [comment]
Sorry for the fuss, I'll be investigating.

**Comment by justinmk** [comment]
@cinghiopinghio What does this show:

    :verbose set exrc?

**Comment by cinghiopinghio** [comment]
@justinmk I get:
```
noex
```

Using `nvim -u NONE path/to/init/vim` works as expected: do not reload on write.
I'll investigate what local config reload `.vimrc`, I don't think I have any plugin installed that does that.
