### ISSUE TITLE
Neovim 0.2.1 results in an increase in memory of gnome-terminal-server

### ISSUE THREAD

**Issue by YorickPeterse** [neovim/neovim#7573]
When using neovim 0.2.1 in combination with gnome-terminal switching between tabs (and possibly other window related operations) results in the memory of gnome-terminal-server increasing quite rapidly. I ran into this when at some point the total memory used was around 2 GB, when normally gnome-terminal-server hardly goes above 100 MB.

I did some manual testing with other terminals (e.g. tilix and roxterm) and they seem to suffer from the same problem. I haven't tested non libvte terminals though. Seeing how the nvim process itself is not increasing in memory usage I think neovim is spitting something out these terminals don't like.

Neovim 0.2.0 does not suffer from the mentioned problem.

- `nvim --version`: v0.2.1
- Vim (version: ) behaves differently?
- Operating system/version: Arch Linux, kernel 4.9 LTS
- Terminal name/version: gnome-terminal 3.26.2 VTE version 0.50.2
- `$TERM`: xterm-256color

### Requirements To Reproduce

* Python 3
* gnome-terminal
* https://github.com/neovim/python-client installed

### Steps to reproduce

1. `curl -s https://gist.githubusercontent.com/YorickPeterse/ec9262060d4aaaff48e7304e8cc14034/raw/2e79bd1dc3bd023a6cd9ff09eae1c54113f67ba0/reproduce.vim -o /tmp/reproduce.vim`
2. `curl -s https://gist.githubusercontent.com/YorickPeterse/ec9262060d4aaaff48e7304e8cc14034/raw/2e79bd1dc3bd023a6cd9ff09eae1c54113f67ba0/reproduce.py -o /tmp/reproduce.py`
3. Run `env NVIM_LISTEN_ADDRESS=127.0.0.1:9999 nvim -u /tmp/reproduce.vim` in one gnome-terminal instance
4. Run `python /tmp/reproduce.py` (requires python 3) in another instance
5. Wait until the Python script completes

### Actual behaviour

Memory of gnome-terminal-server (but weirdly enough not nvim itself) increases over time.

On 0.2.0 the script output is:

```
Memory start: 89.63671875 MB
Memory increase: 0.0 MB
```

On 0.2.1:

```
Memory start: 90.5625 MB
Memory increase: 45.60546875 MB
```

### Expected behaviour

Memory does not increase drastically.

**Comment by justinmk** [comment]
So `set termguicolors` is required? The problem does not occur if you don't set that? 

- What is `$VTE_VERSION`?
- Does the problem occur if you use `TERM=gnome-256color` instead? (Recommended by `:help $TERM` ... this is not a dodge, just for debugging)

**Comment by YorickPeterse** [comment]
@justinmk Disabling `termguicolors` seems to result in memory remaining stable. Enabling `termguicolors` but setting `TERM` to `gnome-256color` still results in memory increasing. The value of `$VTE_VERSION` is 5002.

**Comment by justinmk** [comment]
@YorickPeterse Last question, could you try with `$VTE_VERSION` and `$XTERM_VERSION` un-defined.

**Comment by guyzmo** [comment]
Just for the note, I noticed about a month ago a similar issue (that was about the last time I did a thorough update on my system), where I had `gnome-terminal-server` eat up to 50% (8GB) of my RAM. I have been trying to reproduce the issue and understand the cause, and I never found out the cause (I just blamed lennart, because it's always his fault 😁). I think the problem stopped when I started to run nvim in tmux (so I could restart gnome-terminal and keep my editing sessions alive).

Also, I'm not a tab user, but I'm an heavy window splitter, and I load hundreds of buffers, with usually several `:term` sessions.

I ran the above script, and its output was: 

```
Memory start: 259.6953125 MB
Memory increase: 86.953125 MB
```

I run `NVIM v0.2.1-899-ge085a50c5`, `GNOME Terminal 3.24.1 Using VTE version 0.48.3 +GNUTLS` and I have `set termguicolors` enabled with `xterm-256color`. I'm also running Arch with kernel `4.12.8-2`.

Thank you @YorickPeterse for noticing that!

**Comment by guyzmo** [comment]
ok, so I tried with both `VTE_VERSION` and `XTERM_VERSION` unset. The second one wasn't set in my environment. And here's the result:

```
Memory start: 349.51171875 MB
Memory increase: 0.0 MB
```

**Comment by guyzmo** [comment]
as asked by @justinmk I just tried latest from master, commit eb40b7ec404e8651137513ced43d503bc6656f17,

and it's a success:

```
Memory start: 351.55078125 MB
Memory increase: 0.0 MB
```

🍻👍🙌😁

**Comment by justinmk** [comment]
@egmontkob this might be a libvte bug.

**Comment by egmontkob** [comment]
Nice catch, thanks a lot guys! Indeed a [libvte bug](https://bugzilla.gnome.org/show_bug.cgi?id=790539).

**Comment by egmontkob** [comment]
[... and it's gone](https://git.gnome.org/browse/vte/commit/?id=dda73cc)

**Comment by YorickPeterse** [comment]
Thanks a lot!
