### ISSUE TITLE
segmentation fault when closing a neovim split while a terminal split is open

### ISSUE THREAD

**Issue by hunter-** [neovim/neovim#7574]
If I do the following:
- open a new neovim split (I'll call this split 1)
- open a new terminal split (I'll call this split 2)
- switch to split 1
- quit split 1 (via `:q`)

I get the following:
![image](https://user-images.githubusercontent.com/3286900/32922611-43ee09de-caf0-11e7-9f7d-30db7d23493f.png)

Not sure why this is happening but I'm able to replicate the behavior. Any idea what's going on?

**Comment by justinmk** [comment]
Thanks for the report. This was fixed on master. Will release 0.2.2 in a day or 2.

see https://github.com/neovim/neovim/pull/7547

**Comment by hunter-** [comment]
Awesome — thanks for the response and the great work!
