### ISSUE TITLE
TUI: interleave builtin-terminfo with system terminfo

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7575]
ref https://github.com/jwilm/alacritty/issues/736#issuecomment-323512752

We trust terminfo too much. For example, xterm-256color on macOS is outdated. 

At `:help nvim-features-changed` it is noted that we don't "fill in" missing terminfo entries from our builtin terminfos: 

> Nvim uses either one or the other of an external terminfo entry or the built-in one.  It does not attempt to mix data from the two. 

Maybe we should merge missing entries from the builtin terminfos. (Vim does so already: `'ttybuiltin'` option). Not sure, though: might be better to keep it simple, and try to improve the builtin definitions--and ignore system-provided terminfos entirely!

**Comment by geekodour** [comment]
@justinmk how to see current terminfo, is there any requirement for an api for that? and I can see `terminfo_from_builtin`. I am looking into this issue.

**Comment by geekodour** [comment]
In ref to jwilm/alacritty#736
How will only merging missing entries from the builtin terminfos help? what if there are special modifications to be made, a [`ttybuiltin`](http://webcache.googleusercontent.com/search?q=cache:P3_3H-BnO4kJ:vimdoc.sourceforge.net/htmldoc/options.html#'ttybuiltin') like implementation can be more useful I guess as you described. 

In that `patch_terminfo_bugs` is rewriting term specific issues already. If a `ttybuiltin` like feature is implemented should it be built upon `patch_terminfo_bugs` or separately. 

ps: very new to this, sorry for being so naive :stuck_out_tongue:

**Comment by mhinz** [comment]
Okay, so Neovim tries to work for 99% of the users by providing good defaults.

I'm for [keeping the built-in terminfo database up-to-date](https://github.com/neovim/neovim/pull/7981) and forcing it on the users by default. And the minority of users with handcrafted terminfo entries should be able to opt-out of it by using an option.

Shouldn't this be good enough? Is merging really needed?

**Comment by justinmk** [comment]
Let's start with https://github.com/neovim/neovim/pull/7981 , don't want to change many things at once.

> If a ttybuiltin like feature is implemented should it be built upon patch_terminfo_bugs or separately.

Let's start with #7981 and continue to make any tweaks in `patch_terminfo_bugs` and `augment_terminfo`. 

Would prefer to avoid `ttybuiltin`, most users don't understand it and it's a cop-out.

**Comment by justinmk** [comment]
## Resolution/Summary

https://github.com/neovim/neovim/pull/7981 and other `patch_terminfo_bugs` fixes have improved the situation, so this is not so urgent. And it's easier to reason about the behavior if we don't do this.

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
