### ISSUE TITLE
urxvt: focus reporting (FocusLost, FocusGained)

### ISSUE THREAD

**Issue by madbence** [neovim/neovim#7578]
- `nvim --version`:

```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: 8.0, 1-839) behaves differently?

yes, `FocustLost` works with [`amerlyq/vim-focus-autocmd`](https://github.com/amerlyq/vim-focus-autocmd) and [`amerlyq/urxvt-ext-evolved`](https://github.com/amerlyq/urxvt-ext-evolved)

- Operating system/version: 

```sh
$ uname -a
Linux voyager 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux
```

- Terminal name/version: `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
- `$TERM`: `rxvt-unicode-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:au FocusLost * echo "lost"
```

### Actual behaviour

Doesn't print anything.

### Expected behaviour

Should print `lost`.

The main use-case for this is autosave on lost focus:

```
au FocusLost * :wa
```

**Comment by justinmk** [comment]
https://github.com/amerlyq/vim-focus-autocmd/blob/0093b17b666f571a593030d75c77c0d5cf4b57c1/autoload/focau/events.vim#L27 suggests rxvt expects some other sequence to enable focus reporting.

BTW where is this documented? No mention of it in https://www.freebsd.org/cgi/man.cgi?query=urxvt&manpath=ports&sektion=7 . 

Can you try this patch:

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 8e0e905bcd8b..0c21ac0242aa 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1635,9 +1635,9 @@ static void augment_terminfo(TUIData *data, const char *term,
   data->unibi_ext.disable_bracketed_paste = (int)unibi_add_ext_str(ut, NULL,
       "\x1b[?2004l");
   data->unibi_ext.enable_focus_reporting = (int)unibi_add_ext_str(ut, NULL,
-      "\x1b[?1004h");
+      "\x1b]777;focus;on\x7");
   data->unibi_ext.disable_focus_reporting = (int)unibi_add_ext_str(ut, NULL,
-      "\x1b[?1004l");
+      "\x1b]777;focus;off\x7");
   data->unibi_ext.enable_mouse = (int)unibi_add_ext_str(ut, NULL,
       "\x1b[?1002h\x1b[?1006h");
   data->unibi_ext.disable_mouse = (int)unibi_add_ext_str(ut, NULL,
```

**Comment by madbence** [comment]
thanks, i'm going to try this out, if i manually echo this in the terminal, it turns those focus events on, so it should work!

**Comment by mox-mox** [comment]
This uses an urxvt perl extension. `man urxvtperl` documents the perl callback function that gets called when the terminal encounters a certain type of escape sequence:
```
       on_osc_seq_perl $term, $args, $resp
           Called whenever the ESC ] 777 ; string ST command sequence (OSC = operating system command) is processed.
           Cursor position and other state information is up-to-date when this happens. For interoperability, the
           string should start with the extension name (sans -osc) and a semicolon, to distinguish it from commands
           for other extensions, and this might be enforced in the future.

           For example, "overlay-osc" uses this:

              sub on_osc_seq_perl {
                 my ($self, $osc, $resp) = @_;

                 return unless $osc =~ s/^overlay;//;

                 ... process remaining $osc string
              }

           Be careful not ever to trust (in a security sense) the data you receive, as its source can not easily be
           controlled (e-mail content, messages from other users on the same system etc.).

           For responses, $resp contains the end-of-args separator used by the sender.
```
Therefore, for an urxvt extension named "focus" to receive the escape codes, they will have to conform to the specified format.
After installing the perl extension and a patched version of nvim, the `FocusGained` and `FocusLost` autocommands are called in nvim without any need to install the vim plugin [1].

This is the perl extension I use for urxvt, derived from [2]:
`~/.urxvt/ext/focus`
```
use strict;
use warnings;
use Time::HiRes qw(usleep);


# NOTE: Default xterm/iTerm2 enable/disable: CSI ? 1004 h/l
#   e.g.: <Esc>[?1004l / <Esc>[?1004h

# ENABLE:  echo -ne "\033]777;focus;on\007"
# DISABLE: echo -ne "\033]777;focus;off\007"

# Escape sequences could be custom, like:
# my $csi_in = "\033[UlFocusIn";
# my $csi_out = "\033[UlFocusOut";

my $csi_in = "\033[I";
my $csi_out = "\033[O";

sub on_start {
    my($self) = @_;
    $self->{focus_activated} = 0;
    $self->{has_focus} = 0;
}

sub on_osc_seq_perl {
	my ($self, $osc, $resp) = @_;

	# Only act on the "\033]777;focus;XXX\007" sequence
	return unless $osc =~ s/^focus;//;
	# Note the subscription/unsubscription
	$self->{focus_activated} = $osc eq 'on' ? 1 : 0;
	# If subscribed and the terminal has focus, send first focus event to the program
	if (($self->{focus_activated}) && ($self->{has_focus})) {
		usleep(16000);
		$self->tt_write($csi_in);
	}
}

sub on_focus_in {
    my($self) = @_;
    $self->{has_focus} = 1;
    if ($self->{focus_activated}) {
        # Delay this event 16 ms, so it is after the focus_out from the previous window.
        usleep(16000);
        $self->tt_write($csi_in);
    }
}

sub on_focus_out {
    my($self) = @_;
    $self->{has_focus} = 0;
    if ($self->{focus_activated}) {
        $self->tt_write($csi_out);
    }
}
```
Don't forget to activate the extension: `URxvt*perl-ext-common: focus`

[1] https://github.com/amerlyq/vim-focus-autocmd
[2] https://github.com/amerlyq/urxvt-ext-evolved/blob/master/ext/focus-events

**Comment by mox-mox** [comment]
And could I suggest renaming this issue to change the "rxvt" to "urxvt" or "urxvt-unicode"? When I first saw this issue, I ignored it because I thought it was about the non-unicode rxvt.

**Comment by justinmk** [comment]
Non-unicode rxvt isn't support by Nvim, in case anyone actually uses it ...

**Comment by justinmk** [comment]
@mox-mox @madbence so this requires some sort of urxvt extension. What happens if we emit those codes and the extension isn't installed? Are they silently ignored (hopefully)?

**Comment by mox-mox** [comment]
I just tested it (removed the extension folder from the .urxvt directory, removed the line in .Xdefaults that enabled the extension, started a new terminal, launched vim), there is no problem.
The sequence "\x1b]777;focus;off\x7" is specifically for the urxvt-extension named focus. If there is no such extension, well, bad luck, nothing happens.
Might it be worthwhile to try to get this functionality into the normal urxvt codebase?

**Comment by blueyed** [comment]
urxvt development version (to become 9.23) will support the standard xterm sequence (https://github.com/exg/rxvt-unicode/commit/75264fa544529a21ff79d3da26eb3130c43444a5#diff-2c8f5590ce4fa7495edcf7572c89c77b).
See https://github.com/neovim/neovim/issues/8695 about handing this in Neovim proper.
