### ISSUE TITLE
Terminal needs reset for paste to work

### ISSUE THREAD

**Issue by ggl** [neovim/neovim#7582]
- `nvim --version`:

NVIM v0.2.2-1-gc46d6f8da
Build type: RelWithDebInfo
LuaJIT 2.0.5

- Vim (version: ) behaves differently?

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056

- Operating system/version:

Linux 4.4.0-98-generic #121-Ubuntu SMP x86_64

- Terminal name/version: xfce4-terminal 0.6.3 (Xfce 4.12)
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

Start nvim
Exit nvim
Start vim and enter insert mode
Copy/paste

### Actual behaviour

Copy/Paste strign gets truncated at the beginning. Resetting the terminal with the reset command fixes the problem.

### Expected behaviour

Copy/Paste string should not get truncated.
![screenshot_2017-11-18_14-04-33](https://user-images.githubusercontent.com/3610557/32980118-7aaf3ffe-cc69-11e7-8582-d1ee5986e7ee.png)
![screenshot_2017-11-18_14-03-52](https://user-images.githubusercontent.com/3610557/32980119-7acc74a2-cc69-11e7-9d9a-e2a9b2cc1c46.png)

**Comment by justinmk** [comment]
The steps aren't sufficient.
