### ISSUE TITLE
Statusbar colors not updating after highlight change

### ISSUE THREAD

**Issue by and3rson** [neovim/neovim#7583]
- `nvim --version`:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src
/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently? no
- Operating system/version: ArchLinux x64
- Terminal name/version: termite v12
- `$TERM`: screen-256color

### Steps to reproduce

1. Paste this into your `.vimrc`:

```
function SetStatusLineColor()
    let m = mode()
    if (m ==# 'i')
        exe 'hi! StatusLine ctermfg=197'
    elseif (m ==# 'v' || mode() ==# 'V')
        exe 'hi! StatusLine ctermfg=81'
    else
        exe 'hi! StatusLine ctermfg=118'
    endif
    redraw!
    return m
endfunction

set statusline=%{SetStatusLineColor()}
set laststatus=2
set nolazyredraw
```

2. Restart vim and switch between insert/normal/visual modes.

### Actual behaviour

Statusbar color update is always delayed. If you enter insert mode, the content of statusline changes, but the color remains the same until you trigger redraw, for example, by a keystroke. Same reproduces for switching between any two modes. `lazyredraw`/`nolazyredraw` do not solve this issue, same goes for `redraw!`.

### Expected behaviour

The statusline color should update instantly.

**Comment by justinmk** [comment]
`:help :redrawstatus`

(as always with Vim, there's a special case for everything ...)

**Comment by and3rson** [comment]
Nice!
I've googled this problem a *lot* and didn't find this info. Thank you!

**Comment by and3rson** [comment]
Uh... Unfortunately that doesn't work either.

**Comment by and3rson** [comment]
For anyone having the same problem:
I've found a better way by reading the sources of airline. Instead of calling SetStatuslineColor in status line definition I set statusline to `%!MakeStatusline()` and return the generated statusline definition string with colors (using `%#XXX#` and `%X*` from the custom MakeStatusLine function. It's clean, fast and works perfectly.
