### ISSUE TITLE
Sending ANSI escape sequences to the terminal emulator (the one nvim is running in)

### ISSUE THREAD

**Issue by mox-mox** [neovim/neovim#7584]
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5       
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-s
trong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/i
nclude
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"         

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim" 

Run :checkhealth for more info         
```
- `Vim version`:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 14 2017 20:05:55)
Included patches: 1-1297
Compiled by Arch Linux
...
```
- `Vim  behaves differently?` Yes

- `Operating system/version`: Archlinux
- `Terminal name/version`: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!echo -ne "\033]777;focus;on\007" 
```

### Actual behaviour
The escape sequence is echoed to the status line
### Expected behaviour
The escape sequence is sent to the terminal (urxvt)

### Explanation
I am trying to get proper focus events to work in urxvt, based on a perl extension [1] that calls al perl function when urxvt gains or loses focus (differing from the linked tutorial, I'll try to have urxvt call a vim function instead of simulating a keypress).
On start nvim should inform the terminal, that nvim is running, so that urxvt will send the focus rpc calls.

To verify if the escape sequence is sent, I added calls to notify-send into the perl plugin[2]. When starting vim, I'll get a pop-up notification telling me that vim has requested the focus notifications and a notification telling me that vim stopped the notifications when I close vim.
For nvim, there is no notification, the code is echoed on the bottom line and that is it.

[1] http://artisan.karma-lab.net/creer-plugin-urxvt-sauvegarder-vim-automatiquement
[2]`~/.urxvt/perl/focus `
```
#!/usr/bin/perl

# Hook called on urxvt startup
sub on_start {
	my($term) = @_;
  	# le mode "focus" est désactivé par défaut
  	$term->{focus_activated} = 0;
	system "notify-send focus start";
}

# Interception function for "OSC 777 xxx BEL" escape codes
sub on_osc_seq_perl {
	my ($term, $osc, $resp) = @_;
  	return unless $osc =~ s/^focus;//;
  	$term->{focus_activated} = $osc eq 'on'?1:0;
	system "notify-send focus $osc";
}

# Hook called on focus gain
sub on_focus_in {
	system "notify-send focus gained";
	#my($term) = @_;
  	## Si le mode focus est activé, on envoie la notification
  	#if ($term->{focus_activated}) {
  	#  $term->tt_write("\033[UlFocusIn");
  	#}
}

# Hook called on focus loss
sub on_focus_out {
	system "notify-send focus lost";
	#my($term) = @_;
  	## Si le mode focus est activé, on envoie la notification
  	#if ($term->{focus_activated}) {
  	#  $term->tt_write("\033[UlFocusOut");
  	#}
}
```
`~/.Xdefaults`
```
!# On dit ou se trouvent nos extensions
!URxvt.perl-lib : /home/mox/.urxvt/perl
!# Et on active l'extension "focus"
!URxvt.perl-ext-common: focus
```
`Extract from init.vim and .vimrc`
```
" Initialisation du mode "focus"
exe 'silent !echo -ne "\033]777;focus;on\007"'
" Désactivation du mode focus en partant
autocmd VimLeavePre * exe 'silent !echo -ne "\033]777;focus;off\007"'
```

**Comment by ZyX-I** [comment]
FocusGained/Lost events in rxvt should be supported in C code, #7578. The `:!` command is no longer supposed to echo anything to the terminal Neovim is in, this is by design and will not be fixed, though it is likely that in the future this would write to built-in terminal emulator in a floating window. Writing to `/dev/stderr` or `/dev/stdout` via `writefile()` is currently working AFAIK though, but you should not rely on that doing the right thing always: it is going to be possible to use Neovim as server with its TUI as a client, and generally this variant is terminal-specific.

**Comment by mox-mox** [comment]
Note to later readers: There is C code in nvim that already does send the appropriate escape sequences to the terminal to subscribe to the focus events. So there is no need to do this in vimscript.
These codes just happen to be wrong for urxvt, #7578 proposes a patch to fix this and get the autocommands working.

**Comment by masaeedu** [comment]
Could you please reopen this issue? The issue referred to in the title is more broadly applicable than just fiddling with focus events. For example escape codes for setting the cursor color aren't built into neovim (they can't be, they're specific to the terminal emulator), and you need a way to send escape codes to the outer terminal emulator.

**Comment by justinmk** [comment]
'guicursor' does attempt cursor coloring. See the FAQ. 

Otherwise use `chansend(v:stderr, ...)`

**Comment by zezic** [comment]
If I want to use the equivalent of escape sequences which are sent by [konsoleprofile](https://invent.kde.org/kde/konsole/blob/3465b8fb8d72cf2a1a1bb647c1712c74075368d6/tools/konsoleprofile) how should I do it in NeoVim?
I'm not sure, but it looks like the sequences produced by `chansend(v:stderr, ...)` are not handled by my terminal emulator (Konsole).

**Comment by justinmk** [comment]
@zezic sending standard xterm sequences will work for most things. It's up to you to figure out what your terminal supports.
