### ISSUE TITLE
abort on file changed warning

### ISSUE THREAD

**Issue by muller0** [neovim/neovim#7586]
- `nvim --version`:
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
```

- Vim (version: ) behaves differently?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
```

- Operating system/version:
macOS 10.13.1

- Terminal name/version:
`$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
```
Open any file:
nvim -u NORC file

Write into the file from outside neovim:
echo anything >> file

Try to save file in neovim:
:w

It will warn you about file changes.
Do not press 'y' or 'n'.
Press CTRL+Z instead.
```

### Actual behaviour
It crashes with Abort Trap 6

### Expected behaviour
Not to crash.

**Comment by justinmk** [comment]
Good catch. CTRL-Z during y/n prompt  in Vim just repeats the y/n prompt. Whereas we blindly handle the CTRL-Z.

**Comment by justinmk** [comment]
Bisected to e82cb5de4adc. cc @bfredl

**Comment by justinmk** [comment]
Bisected to 7d6af9985c05 cc @bfredl
