### ISSUE TITLE
Calling synID() breaks third return value from synconcealed()

### ISSUE THREAD

**Issue by lucc** [neovim/neovim#7589]
- `nvim --version`: v0.2.1 (from the Arch Repos) and d6f9d1df0
- Vim (version: 8.0, patches 1-1297, also from Arch Repos) behaves differently? YES
- Operating system/version: Arch Linux (uname -a: `Linux tp 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`
- Terminal name/version: [termite](https://github.com/thestinger/termite/) v12 (from Arch Repos)
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

We need a minimal config folder with a simple syntax file, so:

```
mkdir -p testfolder/syntax
cp example.vim testfolder/syntax
cp test.vim test.txt testfolder/
cd testfolder
```
with these files:

*example.vim* syntax file:
```vim
syn match tutorSampleTextMark /^--->/ conceal cchar=→
```
the *test.vim* script to demonstrate the problem
```vim
if !has('nvim')
  se nocp
endif
set cole=2
syntax on
filetype on

let lnum = 1

for cnum in range(1, len(getline(lnum)))
  echo synconcealed(lnum, cnum)
  " TODO Comment the following line in or out to see the bug:
  echo synID(lnum, cnum, 1)
endfor

quitall!
```
and the *test.txt* data file:
```
--->
vim: ft=example
```

### Actual behaviour

The output from `nvim --headless -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
88
[1, '→', 2]
88
[1, '→', 3]
88
[1, '→', 4]
88
```

### Expected behaviour

The output from `vim -T dumb -u NONE --cmd 'se rtp+=.' -S test.vim test.txt` is:
```

"test.txt" 2 lines, 21 characters
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
[1, '→', 1]
87
```

If the synID() call in test.vim is commented out both nvim and vim produce this output:

```
"test.txt" "test.txt" 2L, 21C
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
```

In my opinion this demonstrates that a call to `synID()` will somehow mess up the third return value from `synconcealed()` which per the docs should be
```
[...] a unique number representing the
specific syntax region matched. This allows detection of the
beginning of a new concealable region if there are two
consecutive regions with the same replacement character.
```

**Comment by nateozem** [comment]
From what I can analyze, I think the problem is with `synconcealed()`.
The change I've made to `test.vim`, is calling `synconcealed()` twice:

``` vim
" test.vim
if !has('nvim')
  se nocp
endif
set cole=2
syntax on
filetype on

let lnum = 1

echo 'file: '.expand('%')
echo 'string len: '.len(getline(lnum))
for cnum in range(1, len(getline(lnum)))
  echo synconcealed(lnum, cnum)
  echo synconcealed(lnum, cnum)
endfor

quitall!
```

I'd get different results between `nvim` & `vim` after I made the change.

with `nvim`:
```
$ nvim --headless -u NONE --cmd 'se rtp+=.' -S test.vim test.txt
"test.txt" "test.txt" 2L, 21C
file: test.txt
string len: 4
[1, '→', 1]
[1, '→', 2]
[1, '→', 2]
[1, '→', 3]
[1, '→', 3]
[1, '→', 4]
[1, '→', 4]
[1, '→', 5]%
```

with `vim`:
```
$ vim -T dumb -u NONE --cmd 'se rtp+=.' -S test.vim test.txt

"test.txt" 2 lines, 21 characters
file: test.txt
string len: 4
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
[1, '→', 1]
```

I'll dive deeper into the cause.

**Comment by nateozem** [comment]
To note, tested up to v0.1.0 and all have the same issue.

**Comment by justinmk** [comment]
Vim  8.0.0672 might have fixed this. Found it like this:

    git log --grep synconcealed

**Comment by chrisbra** [comment]
some more information: 
https://groups.google.com/d/msg/vim_dev/CSGDAMyHo5k/BXDLz1PZBAAJ
https://github.com/vim/vim/pull/1783
