### ISSUE TITLE
`sudo make install` changes ownership of files in build subdirectory to root

### ISSUE THREAD

**Issue by KurtPfeifle** [neovim/neovim#7603]
When running *`sudo make install`* for current Git sources ownership of files in the build subdirectory changes to *`root:root`*.  This obstructs the next iteration of running *`make`* as an unprivileged user.

### Steps to reproduce

I'm building neovim (as a user) from current Git sources on a Debian Stretch system. 

#### Preparation

<pre>
 kp@stretch:~> git clone https://github.com/neovim/neovim.git  git.neovim
    [....]
 kp@stretch:build>

 kp@stretch:build> cd git.neovim
 kp@stretch:build>

 kp@stretch:git.neovim> mkdir build
 kp@stretch:build>

 kp@stretch:git.neovim> cd build
 kp@stretch:build>

 kp@stretch:build> cmake ..
    [....]
 kp@stretch:build>

 kp@stretch:build> make
    [....]
 kp@stretch:build>
</pre>
 
#### Build phase, first time

This phase works fine:

<pre>
kp@stretch:build>  make
[....]
[100%] Built target nvim
[100%] Built target translations
[100%] Built target shell-test
[100%] Built target tty-test
[100%] Built target printargs-test
[100%] Built target vimball-tags
[100%] Built target helptags
[100%] Built target runtime
</pre>

No files in the build sub-directory belong to root:

<pre>
 kp@stretch:build>  find . -user root
 kp@stretch:build>  
</pre>

#### Installation phase

<pre>
 kp@stretch:build>  sudo make install
    [100%] Built target nvim
    [100%] Built target translations
    [100%] Built target shell-test
    [100%] Built target tty-test
    [100%] Built target printargs-test
    [100%] Built target vimball-tags
    [100%] Built target helptags
    [100%] Built target runtime
    Install the project...
    -- Install configuration: "Debug"
    -- Up-to-date: /usr/local/share/man/man1/nvim.1
    -- Up-to-date: /usr/local/bin/nvim
    -- Up-to-date: /usr/local/share/locale/ja.euc-jp/LC_MESSAGES/nvim.mo
    -- Up-to-date: /usr/local/share/locale/cs.cp1250/LC_MESSAGES/nvim.mo
    -- Up-to-date: /usr/local/share/locale/sk.cp1250/LC_MESSAGES/nvim.mo
    [....]
    -- Up-to-date: /usr/local/share/nvim/runtime/print/prolog.ps
    -- Up-to-date: /usr/local/share/nvim/runtime/tutor/en/vim-01-beginner.tutor
    -- Up-to-date: /usr/local/share/nvim/runtime/tutor/tutor.tutor
 kp@stretch:build>  

 kp@stretch:build>  find . -user root
    ./runtime/pack/dist/opt/vimball/doc/vimball.txt
    ./runtime/pack/dist/opt/vimball/autoload/vimball.vim
    ./runtime/pack/dist/opt/vimball/plugin/vimballPlugin.vim
    [....]
    ./runtime/doc/ui.txt
    ./runtime/doc/repeat.txt
    ./runtime/doc/pi_netrw.txt
    ./runtime/doc/pi_matchit.txt
 kp@stretch:build>  
</pre>

#### Build phase, second time

Because the previous build's installation has changed ownership of the files, a renewed attempt to build the same (or *`git pull`*-ed new) sources fails:

<pre>
 kp@stretch:build>  make
    [100%] Built target nvim
    [100%] Built target translations
    [100%] Built target shell-test
    [100%] Built target tty-test
    [100%] Built target printargs-test
    [100%] Built target vimball-tags
    Error removing directory "/home/kp/svn-stuff/git.neovim/build/runtime/doc".
    runtime/CMakeFiles/helptags.dir/build.make:57: recipe for target 'runtime/CMakeFiles/helptags' failed
    make[2]: *** [runtime/CMakeFiles/helptags] Error 1
    CMakeFiles/Makefile2:7368: recipe for target 'runtime/CMakeFiles/helptags.dir/all' failed
    make[1]: *** [runtime/CMakeFiles/helptags.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2
</pre>

### Actual behaviour

*`sudo make install`* changes the ownership of files in the build subdirectory.

### Expected behaviour

*`sudo make install`* preserves the ownership of files in the build subdirectory.

**Comment by cangscop** [comment]
running `make preinstall` before `sudo make install` prevents the issue

**Comment by justinmk** [comment]
can you send a PR?

**Comment by cangscop** [comment]
my bad, i made a mistake in repeating the bug. you solved the issue with 06b7561e785afc9ad0bb66b789a450b96605fd97
