### ISSUE TITLE
Please put version info into name of downloadable "nvim.AppImage"

### ISSUE THREAD

**Issue by KurtPfeifle** [neovim/neovim#7604]
The currently released *`nvim.AppImage`* is based on the *v0.2.3-dev* release.

This fact is hidden from users, unless they (know to) run *`./nvim.appimage --version`*, which would give them the needed info.

It would be nice if the release version would show up in the AppImage name as well, like *`./nvim-0.2.3-dev.appimage`* to save the extra effort from running above command to find out.

This way an additional benefit of AppImage builds could easily play out as well: keeping two or more different versions of nvim AppImages around and also running them side-by-side (good for bug hunting, good for many more things...)

**Comment by justinmk** [comment]
> to save the extra effort from running above command to find out.

`nvim.appimage -v` also works, as does `:version` command. If that's too much work, one isn't going to like vim ...

Storing info in filenames is unpleasant: 

- instructions/discussions are more cumbersome to communicate
- URLs become stale or require redirects to be configured
- users have to update aliases or do an extra "rename" step when downloading a new version

`nvim.appimage` is intended to avoid those problems.

> an additional benefit of AppImage builds could easily play out as well: keeping two or more different versions of nvim AppImages around and also running them side-by-side

But then everyone else has to do the "rename" step. Not worth the tradeoff.

**Comment by KurtPfeifle** [comment]
@justinmk: I'm sorry for having failed to substatiate my reasoning well enough to convince you. I'll try one more time, but I'm not re-opening this request, though:

> *"`nvim.appimage -v` also works, as does `:version` command.`"*

I know that and I'm (forced to) using it much more often than I'd like to.

> *"*If that's too much work, one isn't going to like vim ..."*

You couldn't be more wrong here: I DO like *`vim`*, and started to like *`nvim`* even more, and I'm using them daily since many years. One of my main reasons to use them, is: I'm trying to *SAVE* me from doing needless work; both are making me more productive.

One of the reasons why I use AppImages for many apps I'm testing + using is this: they not only let me keep different versions around, but I don't need to compile from sources every time a new release has happened, and they let me run them side-by-side without a problem. And when they have a hint in their respective names, I can quickly identify which is which, be it in *`"ps aux2"`* outputs, or in window title bars, or in automatically generated logfile names or contents, or whereever.

> *"Storing info in filenames is unpleasant:"*

Did you think this argument through, completely through? Why then do you use *"nvim"* and not *"vim"* as the filename of your exe?!? Why you have a different *number* for each release? Why do we all not name every file just "file" then?

I guess you meant it's unpleasant to store *TOO MUCH* info in filenames alone. With that one I agree. But I still think for AppImages the version would be a very useful additional info to have provided already when downloading.

> * *"instructions/discussions are more cumbersome to communicate"*

I don't get that statement of yours. So I cannot argue with it, and therefor it may even be valid.

> * *"URLs become stale or require redirects to be configured"*

Why so, the "stale"? Ok, you may have to do *something* when you want to always offer a "latest" nvim.AppImage. If that's too much work, one isn't going to like offering stuff for download anyway...

> * *"users have to update aliases or do an extra "rename" step when downloading a new version"*

Why so? They can keep their "versioned" filenames and always be aware which version they have.
They also could create a symlink with an unversioned name pointing to the real thing, should they desire this.

> *"`nvim.appimage` is intended to avoid those problems."*

This *intention* doesn't work for me in real life. It *CREATES* some additional problems for me. (Ok, these are not sooo big, and I can work around them.)

> *"But then everyone else has to do the "rename" step."*

No. They don't *HAVE* to. Or only if they prefer to absolutely have unversioned file names. And they have to re-check the versions of their nvim.AppImage everytime they need to know it...

----

Anyway, as I said: I won't reopen the issue.

But let me take the opportunity to say a **BIIIIIG THANK YOU** for the awesome work you and your team are putting into NeoVim!  <3
