### ISSUE TITLE
fzf gives empty buffer on :GFiles, :Files, :Ag etc..

### ISSUE THREAD

**Issue by joereynolds** [neovim/neovim#7605]
- `nvim --version`: NVIM v0.2.3-1-gd6f9d1df0
- Vim (version: 8.0 ) behaves differently? Yes, works as intended
- Operating system/version: Ubuntu 16.04
- Terminal name/version: gnome-terminal 3.18.3
- `$TERM`: xterm-256color

I have reported this issue with fzf however they directed me here.

### Steps to reproduce using `nvim -u NORC`

Add this to the NORC file (assuming vim-plug is installed)
```
call plug#begin()
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
call plug#end()
```
Then `:PlugInstall`

Once installed, re-open nvim with `nvim -u NORC` and call `:GFiles`, navigate to a file and press enter

### Actual behaviour

An empty buffer is created

### Expected behaviour

The file under the cursor is opened

Below is a gif of the issue:

![gif](https://user-images.githubusercontent.com/9536682/32826800-b8d561ee-c9e1-11e7-8d49-ddfe27c305ff.gif)

Here is the linked issue
https://github.com/junegunn/fzf.vim/issues/505#issuecomment-345748079

Thanks :)

**Comment by justinmk** [comment]
`:GFiles` works for me. I don't use the "preview" feature of FZF though. Without reduced steps, I don't see a Nvim bug here.
