### ISSUE TITLE
[Bug] automatically enter paste mode when paste with line break

### ISSUE THREAD

**Issue by hiberabyss** [neovim/neovim#7608]
- OS: `macOS 10.13.1`
- neovim version: `NVIM v0.2.3-5-g7d24a95b4`
- Vim (8.0) has different behaviour
- iTerm 3.0.15

### How to reproduce in neovim

Open neovim with `nvim -u NORC`, input following line:

```
let a = 1
```

- The result of `set paste?` is `nopaste`;
- Press `V` to select the whole line, then press `"*y` to copy the line into system's clipboard;
- Press `:` to enter command mode, then press `<Command-v>`;
- The result of `set paste?` now becomes `paste`.

### VIM has different behaviour

When open VIM with `vim -u NONE`, replay the same steps, will get following result:

![image](https://user-images.githubusercontent.com/2898670/33053572-3a990d3a-ceaf-11e7-9b22-1035d8ec31b6.png)

PS: Sometimes, when I paste content from clipboard into neovim, it will automatically enter paster mode and string `<Paste>` is appended, it's very annoying.

Thanks!

**Comment by kiooss** [comment]
I have the same problem.

**Comment by jeaye** [comment]
I also have this problem, with NVIM v0.2.2 (Arch repos).

**Comment by nimitbhardwaj** [comment]
On my Linux PC, it happens in this way, 
`nvim -u NORC` open a blank buffer, write some thing like `Hello world` then do this `vll"*y` (now `Hel` will be copied in clipboard), then press `:<ctrl-p><ctrl+shift-p>` then the text in the commandline will `<Paste>hel`

**Comment by justinmk** [comment]
Merging this with https://github.com/neovim/neovim/issues/7994
