### ISSUE TITLE
Cannot scroll up when at end of large line

### ISSUE THREAD

**Issue by JuanPotato** [neovim/neovim#7610]
- `nvim --version`: NVIM v0.2.1-953-g3e502fd7d
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# have first line empty so you know when you sucessfully scrolled up
# write some huge line (at least covering your screen)
$ # move to end of line
:set mouse=a # to be able to scroll
# scroll up
```

### Actual behaviour
nvim does not scroll up to the next line

### Expected behaviour
nvim should scroll up

You may be thinking "this is because the line is bigger than your screen and thus you cant see your next line", but if you have a line that is bigger than your screen, it will still work. Until a point where its too big that it suddenly stops. So it does not seem to be due to not seeing the above line.

[absolutely overkill example](http://0x0.st/s-t0.txt)

**Comment by JuanPotato** [comment]
https://gfycat.com/gifs/detail/MarvelousWarmheartedFurseal

A weird consequence

**Comment by justinmk** [comment]
This is the same as https://github.com/neovim/neovim/issues/7172
