### ISSUE TITLE
[Bug] cannot work "Jump back"

### ISSUE THREAD

**Issue by swpark706** [neovim/neovim#7614]
- `nvim --version`: NVIM v0.2.1
- OS: Ubuntu 16.0.4

Hi, I am making translations of help for Korean users.
So I have testing some basic functions, but a problem occured..

In share/nvim/runtime/doc/help.txt, It says
Jump back: Type CTRL-T or CTRL-O. repeat to go further back.
But actually CTRL-T  is equals with input 'tab', CTRL-O doesn't work at all.

![image](https://user-images.githubusercontent.com/28581713/33116288-9127f7d0-cfa7-11e7-9b40-5a245aa2be3c.png)

**Comment by justinmk** [comment]
> But actually CTRL-T is equals with input 'tab', CTRL-O doesn't work at all.

That's in insert-mode. You must switch to normal-mode.

Use https://vi.stackexchange.com/ for usage questions.
