### ISSUE TITLE
Can't find help-dev

### ISSUE THREAD

**Issue by Sunha03** [neovim/neovim#7615]
- `nvim --version`: v0.2.1
- Operating system/version: ubuntu 16.04
- Terminal name/version: GNOME Terminal 3.18.3

In CONTRIBUTING.md
Developer guidelines said Nvim developers should read :help dev-help
External UI developers should read :help dev-ui

So I tried it. But it doesn't work. There aren't any 'dev-help' in develop.txt
![image](https://user-images.githubusercontent.com/33214969/33116527-749b6a88-cfa8-11e7-98cb-5708cbfc2478.png)

Thanks!

**Comment by Shougo** [comment]
`:help dev-help` does not work for me.
I think it should be `:help dev`.

`:help dev-ui` does work.

**Comment by Sunha03** [comment]
Can I update ':help dev-help' to ':help dev' in CONTRIBUTING.md??

**Comment by KillTheMule** [comment]
> Can I update ':help dev-help' to ':help dev' in CONTRIBUTING.md??

A PR would surely be appreciated.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/7555
