### ISSUE TITLE
nvim.appimage weird behavior with fzf.vim

### ISSUE THREAD

**Issue by danihodovic** [neovim/neovim#7620]
- `nvim --version`:
```
$ nvim --version
Alias tip: v --version
NVIM v0.2.3-3-gde8b1fd1d
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-dd94525f-1851-4022-be86-7b6447d76df7

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
Yes the most recent version of vim works as expected.

For what it's worth, it works perfect with the neovim version that's in the Ubuntu repositories. The recent appimage (v0.2.3-3-gde8b1fd1d) breaks it however.

```
$ nvim --version
Alias tip: v --version
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UFyCc4/neovim-0.1.7=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UFyCc4/neovim-0.1.7/build/config -I/build/neovim-UFyCc4/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-UFyCc4/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-UFyCc4/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system/version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```
- Terminal name/version:
```
$ xfce4-terminal --version
xfce4-terminal 0.8.4 (Xfce 4.12)
```
- `$TERM`:
```
$ echo $TERM
screen-256color
```
- FZF version
```
$ fzf --version
0.17.1 (0b33dc6)
```

### Minimal vimrc config
```
$ cat ~/alt_vimrc
set rtp+=~/.fzf
call plug#begin('$HOME/.config/nvim/plugged')
Plug 'junegunn/fzf.vim'
call plug#end()
```

### Steps to reproduce 
1. Open two files
```
nvim -u ~/alt_vimrc zshrc zlogin
```
2. Run `:Buffers`. Neovim will open a terminal window for fzf. Once you select an option (zshrc buffer) the opened terminal window will freeze.

### Actual behaviour
The opened terminal window freezes when attempting to open the buffer.

### Expected behaviour
The terminal window should not freeze.

**Comment by justinmk** [comment]
Works for me.

**Comment by danihodovic** [comment]
Any idea on how I can further debug the issue?

**Comment by justinmk** [comment]
The only thing that really changed with `:terminal` is that it starts in normal-mode.

Need to know what exactly "freeze" means.

**Comment by danihodovic** [comment]
> Need to know what exactly "freeze" means.

Is unresponsive for an indefinite amount of time. Sometimes the fzf window closes and a buffer window is open with the new file. I'm trying to replicate it using asciirecorder, but since it stop the entire terminal window I can't get a proper recording.

**Comment by justinmk** [comment]
Can you bisect to the commit that is associated with the problem?

**Comment by danihodovic** [comment]
> Can you bisect to the commit that is associated with the problem?

I bisected the commits and came up empty handed. I then tried to build the latest master and it turns out that I have no issue. I downloaded the latest appimage (v2.3.3-dev) and when I run the appimage this problem occurs. Strange.

Additionally when opening a buffer using fzf's `:Buffers` command I only encounter this when running the command the first time. After that it seems responsive...

**Comment by justinmk** [comment]
@danihodovic Thanks, I can reproduce with nvim.appimage. But it's not frozen: you can escape to normal-mode in the terminal-buffer via `CTRL-\ CTRL-N`.

Running `:Buffers` again and selecting some other buffer then switches to the previously-chosen buffer. 

Seems like some internal state in fzf.vim is broken. Bisecting fzf.vim might be the next step.

**Comment by danihodovic** [comment]
Thanks. I'll report it to fzf.

**Comment by justinmk** [comment]
Re-opening this, but need someone to actually debug it.

**Comment by danihodovic** [comment]
> Re-opening this, but need someone to actually debug it.

I might have some time this weekend if you can provide me with guidelines on how to debug it and what may be wrong.

**Comment by justinmk** [comment]
Maybe updating to the latest AppImage type (#7537) will make this problem go away. Would be nice if someone spent a few hours to get that working

**Comment by danihodovic** [comment]
> Maybe updating to the latest AppImage type (#7537) will make this problem go away. Would be nice if someone spent a few hours to get that working

The latest appimage doesn't solve the issue, however it seems like the situation has improved:
- the issue only shows up the first time you open an FZF window.
- changing windows with my window manager causes the problem to go away and the window to close.

**Comment by justinmk** [comment]
The comment wasn't about the latest appimage, rather the latest appimage _type_. Hasn't been implemented, see #7537 .

**Comment by justinmk** [comment]
I can't reproduce this in the [latest appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) which is now a "type 2" AppImage (https://github.com/neovim/neovim/issues/7537).

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/8737
