### ISSUE TITLE
Bufhl docs don't match implementation

### ISSUE THREAD

**Issue by keidax** [neovim/neovim#7622]
The `nvim_buf_add_highlight()` function is described in [the help file](https://github.com/neovim/neovim/blob/51637f4256353e513f262572bcb786b54d250e11/runtime/doc/api.txt#L720) as operating on columns, but the implementation actually uses bytes.

I guess bytes are probably what's intended (some discussion in #6270) so the docs should make that clear.

**Comment by justinmk** [comment]
`:help col()` says "byte index of the column", I'll add that to https://github.com/neovim/neovim/pull/7555 @bfredl ?

**Comment by keidax** [comment]
I hadn't checked `:help col()`, that makes more sense now.

**Comment by justinmk** [comment]
added to https://github.com/neovim/neovim/pull/7555
