### ISSUE TITLE
Link error in insert.txt

### ISSUE THREAD

**Issue by mang1375** [neovim/neovim#7627]
in ~/neovim/runtime/doc/insert.txt line 47, 
http://georgevreilly.com/vim/ctags.html

This page is not exist(404 not found).

**Comment by mhinz** [comment]
Please [create an issue for Vim](https://github.com/vim/vim/issues) in this case, since we merge their runtime patches: https://github.com/vim/vim/blob/master/runtime/doc/insert.txt#L1299

When they change it, it will come to Neovim as well.

**Comment by chrisbra** [comment]
Such things should really be reported to the upstream vim repository (ideally with a patch, so we don't have to go hunting for the correct URL ourselves).
Anyway, posted a patch here:
https://groups.google.com/d/msg/vim_dev/1a74UP8j1y4/oKuFaL5fAgAJ

**Comment by chrisbra** [comment]
(can be closed, since there is now vim/vim#2370)
