### ISSUE TITLE
neovim crashes after cd and using the + register on windows

### ISSUE THREAD

**Issue by arnoud999** [neovim/neovim#7629]
- `nvim --version`: v0.2.3-24-gd9b3ebfed
- Vim (version: 8.0) behaves differently?: Yes, the problem, does not occur.
- Operating system/version: Windows 10
- Terminal name/version: cmd
- `$TERM`: I have tried both nvim via cmd, and nvim-qt.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
cd ..
"+p
```

If I try to use the system clipboard, by using `"+p` or `:registers`, for example, nvim works fine. However, when I changed to a different folder using `cd` and then try to access the `+` or `*` register, nvim immediately crashes. The log file only says:

`Neovim fatal error "The Neovim process has crashed"`

**Comment by justinmk** [comment]
Assuming this was alleviated by https://github.com/neovim/neovim/commit/df019cebd59a456d6f7dc5948703fdd2059c4b04

ref https://github.com/neovim/neovim/issues/7642 https://github.com/neovim/neovim/issues/7643
