### ISSUE TITLE
Calls to fgets should be retried when error is EINTR

### ISSUE THREAD

**Issue by mattwidmann** [neovim/neovim#7632]
- `nvim --version`: NVIM v0.2.2
- Vim behaves differently? Not sure.
- Operating system/version: macOS / 10.12.6 (16G29)
- Terminal name/version: Terminal.app / Version 2.7.3 (388.1.1)
- `$TERM`: xterm-256color-it-cs (256 color with italics and cursor shape)

The calls to `fgets` in `src/nvim/if_cscope.c` can fail if a signal is delivered during any of the system calls it makes. In my particular case, a SIGCHLD is *always* interfering with calls into `fgets`. The caller should retry when NULL is returned with `errno` set to EINTR.

I don't know how to reproduce this without a configuration. Here's how I noticed it:

1. Install [fzy](https://github.com/jhawthorn/fzy) and the plugin [vim-picker](https://github.com/srstevenson/vim-picker).
2. Generate a cscope database for a C project and `:cscope add` it to nvim. Verify that cscope is hooked up with `:cscope show`.
3. Route `:tag` requests through cscope first with `:set cscopetag` and `:set cscopetagorder=0`.
4. Use the vim-picker plugin's buffer tag search with `:PickerBufferTag`.
5. Select a known tag to jump to in the current file.

I expected to jump to that tag, but instead, I got a generic cscope communication error:

```
Error detected while processing function 11[5]..10:
line    4:
E262: error reading cscope connection 0
```

I built a debug version of neovim, put a breakpoint on `cs_reading_emsg`, and noticed that `errno` was set to EINTR. I then set lldb to print when signals occur with `process handle --notify true --pass true`, and saw only SIGCHLD signals getting delivered, likely since fzy is exiting after making the selection.

I hit this every time I select a tag using vim-picker. I'm not sure if or when this regressed, or if it's an issue in vim.

**Comment by justinmk** [comment]
note to self, revisit these cscope issues: #7175 #6891 #6229

**Comment by justinmk** [comment]
This happens is because Nvim explicitly unblocks all signals (SIGCHLD in particular) in `signal_init()`. https://github.com/neovim/neovim/pull/5243

https://github.com/neovim/neovim/blob/0b93bab6c22edf7a07cf965ebbbf631b93e1dc1b/src/nvim/os/signal.c#L38-L44 

Thanks for debugging this @mattwidmann !

**Comment by mattwidmann** [comment]
At least on Darwin, you can also use kevent(2) (or libdispatch's `dispatch_source` APIs) to monitor child processes for exits. See EVFILT_PROC in [kevent's man page](x-man-page://2/kevent). This probably doesn't help much, with cross-platform compatibility to consider, but maybe libuv could adopt this instead of relying on signals.
