### ISSUE TITLE
brew upgrade neovim --with-python issues

### ISSUE THREAD

**Issue by AbhimanyuAryan** [neovim/neovim#7637]
I was using neovim installed by homebrew earlier but it wasn't using python. Please check this [issue](https://github.com/nicknisi/dotfiles/issues/70) for errors I got with omnisharp-vim & neovim support.

Then what I did was `brew upgrade neovim --with-python` to fix this error. Now I get new errors. Please help me with what's wrong. Thanks 

```
❯ nvim
function <SNR>61_InitializePythonBuiltin[23]..provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):E475: Invalid argument: Channel id must be a positive integer
Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
Error detected while processing /Users/abhimanyuaryan/.dotfiles/config/nvim/plugged/ale/after/plugin/ale.vim:
line   28:
E605: Exception not caught: ALE conflicts with Syntastic. Uninstall it, or disable this warning with `let g:ale_emit_conflict_warnings = 0` in your vimrc file, *before* plugins are loaded.
Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
Where did `brew upgrade neovim --with-python` come from? 

`:checkhealth` explains what to do, as does the FAQ https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working
