### ISSUE TITLE
Crash when calling matchparen

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#7642]
- `nvim --version`: NVIM v0.2.3-52-ga043899ba
- Vim (version: ) behaves differently?: NA
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: `xterm-256color`

### Steps to reproduce

- load `pandoc` filetype plugin from vim-pandoc/vim-pandoc
- write
```
word other another
```
- place cursor over `other`.
- type `<localleader>iw` (emphasize word under cursor - the result should be `word *other* another`.)

### Actual behaviour

```
Error detected while processing function <SNR>49_Highlight_Matching_Pair:fish: “/usr/bin/nvim” terminated by signal SIGABRT (Abort)
```

### Expected behaviour

No crash. The problem does not occur in neovim 0.2.2, so this is a regression.

The function in vim-pandoc `<localleader>iw` calls is https://github.com/vim-pandoc/vim-pandoc/blob/master/autoload/pandoc/keyboard/styles.vim#L61-L116, which makes use of the selection and registers only.

**Comment by Shougo** [comment]
Please test  0b93bab version.

neovim have merged the big PR recently.
https://github.com/neovim/neovim/pull/6844
It may be the regression.

**Comment by fmoralesc** [comment]
@Shougo, indeed, the 0b93bab version seems to work fine.

**Comment by Shougo** [comment]
OK.  It is the related issue.

https://github.com/neovim/neovim/issues/7643

**Comment by fmoralesc** [comment]
Yes. I was just `strace`ing nvim's HEAD, and the crash didn't follow through, but I got the error
```
E685: Internal error: hash_add()
```
which is consistent with that report.

**Comment by Shougo** [comment]
Please test HEAD version.
The commit is reverted by @bfredl .

**Comment by fmoralesc** [comment]
I can confirm that fixes it.
