### ISSUE TITLE
Running bash as terminal emulator on Windows

### ISSUE THREAD

**Issue by superDuperCyberTechno** [neovim/neovim#7644]
How would I go about running bash as the default terminal when executing `:term`?

**Comment by KillTheMule** [comment]
Try `:term bash`, as long as `bash` is in your path, that should work. Or better yet, `:term bash -i`.

Usage questions should not be on this issue tracker, btw. Try https://www.reddit.com/r/neovim/, which some of the neovim devs read as well.

**Comment by superDuperCyberTechno** [comment]
Thanks. It works. I had a feeling it would be rudimentary.
