### ISSUE TITLE
ruby provider does not support nesting in Windows

### ISSUE THREAD

**Issue by janlazo** [neovim/neovim#7655]
- `nvim --version` https://github.com/neovim/neovim/commit/2d732a11b1ef12b3a3458f45f2f170954ad3bdc6
- Vim (version: ) behaves differently?
  Not tested
- Operating system/version: Appveyor (x86-64)
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

Patch to enable in Appveyor: https://github.com/neovim/neovim/pull/7412/commits/19f1569c86fbe02598f56127ed3dc60ad7a51416

Test shown in https://github.com/neovim/neovim/pull/7412/commits/fe42f9a59af29b1d08fcfe748ae5a9b47a73a144 but without the added line to disable the test.

### Actual behaviour

https://ci.appveyor.com/project/neovim/neovim/build/16911/job/w9iwbr905o5gdowq

```
[00:10:58] [  ERROR   ] C:/projects/neovim/test/functional\provider\ruby_spec.lua @ 41: :ruby command supports nesting
[00:10:58] .\test\functional\helpers.lua:93: Vim(return):ch 3 sent an invalid message, closed.
[00:10:58] 
[00:10:58] stack traceback:
[00:10:58] 	.\test\functional\helpers.lua:93: in function 'request'
[00:10:58] 	.\test\functional\helpers.lua:167: in function 'command'
[00:10:58] 	C:/projects/neovim/test/functional\provider\ruby_spec.lua:42: in function <C:/projects/neovim/test/functional\provider\ruby_spec.lua:41>
```

### Expected behaviour

Pass test in Appveyor.

**Comment by justinmk** [comment]
cc @alexgenco

**Comment by alexgenco** [comment]
I'm looking into this but it will take me some time as I figure out how to reproduce.

**Comment by alexgenco** [comment]
Still haven't fixed it, but I've been debugging on appveyor and am getting weird phantom responses from nvim to RPC message I didn't send (consistently with request id "13"). Nvim then seems to close the connection, which is probably what's causing `ch 3 sent an invalid message, closed.`. Here's an example log line: (https://ci.appveyor.com/project/alexgenco/neovim-ruby/build/1.0.66#L328).

So it seems something is leaking a malformed message to the host process's stdout, potentially only on nested RPC calls. I'll keep digging this weekend.

**Comment by alexgenco** [comment]
It seems like maybe a msgpack issue. In the neovim-ruby acceptance test suite, when the msgpack session gets up to request ID 10, neovim responds with the invalid message response (for request id 13, which was never sent). If I can get a smaller repro case, I'll open an issue with msgpack-ruby. Off the bat, this seems like it might be relevant: https://github.com/msgpack/msgpack-ruby/issues/127

**Comment by alexgenco** [comment]
Ok I think I found the issue, it had to do with setting all IO objects to binary mode (https://ruby-doc.org/core-2.3.1/IO.html#method-i-binmode), among other things. The full neovim-ruby test suite (including tests around nested invocations) is now passing on appveyor, so I'm hoping it resolves this issue is well. Is it easy to try it on neovim-ruby master, or should I release a new version?

**Comment by janlazo** [comment]
I install neovim-ruby via gem so I prefer that I can try the latest changes by reverting the commit to enable the nesting test and run another build,

**Comment by alexgenco** [comment]
Just pushed 0.6.2.

**Comment by janlazo** [comment]
It passes now. Thank you.
