### ISSUE TITLE
Weird unicode / font char 

### ISSUE THREAD

**Issue by chrissound** [neovim/neovim#7656]
I've recently upgraded neovim (0.2.0-2 -> 0.2.2-1), and I'm getting these weird charecters show up:

![2017-11-29-09 48 54](https://user-images.githubusercontent.com/1499652/33369044-4a42f560-d4eb-11e7-8156-ee0dcc829b77.jpeg)

If I have a file with:
  7 example
  8 example
  9 example

Line 8 is when I went into insert mode:
Line 9 is when I yanked the line:
  7 example
  8 [6 qle
  9 [2 qle

**Comment by chrissound** [comment]
https://github.com/neovim/neovim/issues/6041

Seems a workaround is to add `set guicursor=` to your config...

**Comment by justinmk** [comment]
Can you answer the questions from the issue template?

**Comment by spicysomtam** [comment]
Me too. On ubuntu 16.04 (mint 18.2). Seems 0.2.0-3ppa1~ubuntu16.04.2 has been removed from the repo so I can't downgrade!

**Comment by jamessan** [comment]
As has been stated, you can disable the cursor shaping (which is what's causing you to see how buggy the terminal is) by putting `set guicursor=` in your init.vim.

**Comment by spicysomtam** [comment]
Well wierdness. I downgraded and with `set guicursor=` in my init.vim, still oddities (using Terminator). Closed down and restarted Terminator, all ok. Upgraded neovim, and all is good again. Anyhoo, thanks for the quick response, and its worth keeping the older version in the repo just incase.

**Comment by jamessan** [comment]
That's not the way repos work.

**Comment by odiumediae** [comment]
I have the same problem:

![screenshot_2017-11-29_18-04-45](https://user-images.githubusercontent.com/11424407/33388450-53035cea-d530-11e7-9220-01ccddac0099.png)

I'm using xfce4-terminal 0.6.3 in Linux Mint 18.2. The seemingly random bunch of characters was also automatically added in ex mode while writing commands which rendered Neovim unusable.

Adding `set guicursor=`  as mentioned by @chrissound and @spicysomtam made the problem disappear.

**Comment by justinmk** [comment]
The solution is `set guicursor=` or use a terminal emulator that isn't incompetent.

This has been covered multiple times.
