### ISSUE TITLE
Use isatty

### ISSUE THREAD

**Issue by jD91mZM2** [neovim/neovim#7659]
Idea (sorry if duplicate, I couldn't find one):

Sometimes I accidentally pipe into `nvim` instead of `nvim -` worry how much I've just ruined my system.  
What if neovim could use isatty to make both commands equivalent, or at least show a warning for a few seconds (like vim does)? My very knowledgable friend also informed me that you can create a pty to bypass this in scripts, so no functionality would really be lost.

EDIT: Still not convinced? `echo ":\!rm -rf ~" | nvim`

**Comment by justinmk** [comment]
A 2 second warning is not going to help much there. I wouldn't mind neutering it entirely though, make it opt in with a new arg.

**Comment by jD91mZM2** [comment]
A 2 second warning is enough time to hit Ctrl+C
