### ISSUE TITLE
travis: test on OSX too

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#766]
Travis is getting awesomer and awesomer. We once again see the possibility of augmenting our test capability: travis seems to support OSX now:

**NOTE:** I haven't been able to find if it's now possible to specify all that is necessary in one `.travis.yml` file. This used to be impossible in earlier betas. Information seems scarce.

- https://github.com/travis-ci/travis-ci/issues/216 (people usually link to this when they have a PR for their project, so we can look at examples there)
- http://docs.travis-ci.com/user/osx-ci-environment/
- https://github.com/citra-emu/citra/pull/7 (this seems like a good example to follow)

It seems one needs the `os` key:

```yaml
os:
  - osx
  - linux
```

I don't see a need of building all our current lines on OSX though, just one should be enough. Ideally there would also come a FreeBSD build with time. Travis [doesn't support FreeBSD at the moment, though](https://github.com/travis-ci/travis-ci/issues/1818).

**Comment by Pyrohh** [comment]
@aktau Does this need to be open anymore?

**Comment by tarruda** [comment]
> @aktau Does this need to be open anymore?

no need, we've been running OSX tests for some time now
