### ISSUE TITLE
wincmd with :lcd involved during FileType messes up :pwd

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#7662]
- `nvim --version`: v0.2.3-66-ge0466dc59
- Vim (version: ) behaves differently? Yes
- Operating system/version: Arch Linux

When moving back and forth to a window with `:lcd` in a FileType autocommand, `:pwd` gets messed up.

Vim prevents this since patch-8.0.0677 (https://github.com/vim/vim/commit/1814183b8).

I've noticed this with vim-grepper together with vim-qf_resize for when the location list has a local dir (not intentionally, but still a by-product of using vim-stay with views where `:lcd` was stored with).

I've tried to find previous discussion(s) regarding this, but could not (although there were some, but no way to reproduce it).

```vim
" Changing windows back and forth to one with :lcd messes up :pwd.
"
let p = execute('pwd')

" Create a quickfix window with :lcd.
laddexpr ''
lopen
let tmpdir = tempname()
call mkdir(tmpdir)
exe 'lcd '.tmpdir

" Go back
wincmd p

" Trigger the bug by changing windows during the FileType autocommand.
autocmd FileType qf wincmd k | wincmd p

" Ensure we're in the first window.
call assert_equal(winnr(), 1)

" Trigger FileType.
call setloclist(0, [])

call assert_equal(winnr(), 1)
" This fails.
call assert_equal(p, execute('pwd'))

echom string(v:errors)
exe empty(v:errors) ? 'qa' : 'cq'
```

```
% nvim -u t-pwd-with-autocmd.vim
['…/t-pwd-with-autocmd.vim line 26: Expected ''\n/foo'' but got ''\n/tmp/nvimmSSlKs/1''']
```

**Comment by justinmk** [comment]
> Vim prevents this since patch-8.0.0677 (vim/vim@1814183).

Why not just port that patch?

**Comment by blueyed** [comment]
@justinmk 
Initially I've hoped that Neovim might skip this patch, but makes no sense probably.

On the other hand given `:tcd` etc I've thought that this indicates some issue in Neovim (that is different from what the Vim patch tries to avoid).
I have not checked if Vim would behave the same (i.e. have this bug) without the patch (8.0.0677), but my impression was that it would not have problems with the above test case.

After all, `:pwd` and `getcwd()` not being in sync is a serious issue I think?!

**Comment by blueyed** [comment]
I've just seen that `ex_pwd` (uses `uv_cwd`) and `f_getcwd` ( are implemented in different ways altogether.
I think it might make sense to assert that `:pwd` is the same as `:echo getcwd()` e.g. during tests?

**Comment by justinmk** [comment]
Sure. Or refactor to a shared implementation, if possible.

**Comment by blueyed** [comment]
Closing this specific issue due to it being protected by `curbuf_lock` now also in Neovim (patch 8.0.0677).
