### ISSUE TITLE
fzf causes nvim to freeze

### ISSUE THREAD

**Issue by rajukv** [neovim/neovim#7665]
### Actual behaviour
After starting nvim and running ":FZF" shows up the list of files. Selecting a file or pressing ESC will freeze nvim. I have to kill it externally using kill -9

### Expected behaviour
vim and older versions of neovim(NVIM 0.1.7) work file. I am able to open selected files or close FZF by pressing ESC.

Tested with nightly and v0.2.2 appimage. Both of these have this issue. Works fine with vim and newovim 0.1.7

- ./nvim.appimage  --version
NVIM v0.2.3-68-g10c3b206c
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-bf23a1af-2e01-4687-ae74-9d407e47dd7e

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"
- Tested on following vim versions and it works fine:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 12 2017 03:11:25)
Included patches: 1-197, 322, 377-378, 550, 703, 706-707

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:00:20)
Included patches: 1-160

OS tested:
- debian sid and CentOS Linux release 7.3.1611

Terminals tested:
MATE terminal, xshell

$TERM values tested with are "screen", "screen-256color", "xterm-256color"

### Steps to reproduce using `nvim -u NORC`

Cannot be reproduced with "nvim -u NORC" as it requires FZF

**Comment by justinmk** [comment]
It's not frozen, just hit CTRL-\ CTRL-N. Only happens with the appimage. See https://github.com/neovim/neovim/issues/7620#issuecomment-346767016
