### ISSUE TITLE
Improve nvim translation to your native language.

### ISSUE THREAD

**Issue by elmart** [neovim/neovim#767]
You can help neovim by updating/completing translation to your native language.
To do that, once you have downloaded the project and are able to build it, do the following:

### Language update procedure
```
cd src/nvim/po
make clean
make <language>
```
where `<language>` is the usual two-letter code for a language (en, es, fr, etc.).
Procedure above will update `<language>.po` and sync it to current code.

It's recommended that you commit at this point, so that PR will contain two commits:
- First one with automatic changes, just syncing po file to current code. Call this, for example: <br/>
  `Update <language> translation: Sync to <sha>.`.
- Second one with your improvements. Call this, for example: <br/>
  `Update <language> translation: Improve translations.`.

Doing this makes reviewing far easier (GitHub doesn't show big diffs, and as we are updating source line's references everywhere in the first step, you wouldn't be able to see anything in GitHub if you don't separate commits as explained).

Then, you can inspect `<language>.po` file and make your improvements.

Most important thing is to complete missing translations. To find them:
- Search for `msgstr ""`. These are messages for which a translation was not provided, and no one could be guessed from previous translations.
- Search for `fuzzy`.  These are messages for which a translation was not provided, but for which the system was able to guess a tentative translation, though they still need human supervision/correction. Once you've checked/corrected the system provided translation, remove the fuzzy-marker line.

Then, you can proceed by checking the file for incorrect translations (having a different number of %<spec> placeholders than the original string, for example).
To do that:
- Type `make <language>.ck`.
- Inspect resulting `check.log` file.
- To repeat check, do `make checkclean` first.

Last, you can correct existing translations you think can be improved.

Before committing, please pay attention to this:
- Make sure your first commit includes the sha of the commit you are syncing translations up to. Take care not to include generated nvim.pot file here.
- Include only *.po files in your second commit. Take care not to include generated files (nvim.pot, *.ck, etc.).
- Do not delete commented out lines at the end of po files. They are used by gettext to provide tentative translations.

Thanks for your help!

**Comment by fwalch** [comment]
My question is actually similar to the one by @Konafets: Running `make update-po`, for some languages only one file is updated (e.g. only `ru.po`, not `ru.cp1251.po`), for others multiple ones are updated (e.g. `zh_CN.UTF-8.po`, `zh_CN.cp936.po`, `zh_CN.po`).

Is this an oversight (for `ru`)? Are the multiple `po`s really required (e.g. for `zh`)? (cc @elmart)

**Comment by elmart** [comment]
It's been sometime since I looked at this, and build has radically changed since. So, take what I say with a grain of salt. From what I remember:
- There are primary files and generated files.
- Primary files are named `lang(_country)?(.UTF-8)?\.po`. This is, primary files use the most common  non-utf-8 encoding for that locale, or utf-8.
- All locales have only one primary file (be it utf-8 or not), except China chinese (zh_CN) and Taiwan chinese (zh_TW). Those have two primary files. I honestly don't know the reason for this. I guess it could have something to do with using simplified/not-simplified chinese, or some other kind of problem whereby one is not completely convertible from the other one. It seems the utf-8 version should be enough (see [this](http://en.wikipedia.org/wiki/Chinese_character_encoding)). But as I said, I am not sure about this.
- Then, files with some other encodings are generated from primary files. I guess they are other encodings common in those locales, convertible from the primary ones. So we generate them to allow vim run in platforms where default locale uses those encodings.

So, some investigation would be required. And someone acquainted with chinese encodings would be needed to be sure. 
I hope that helps.

**Comment by cre8tor** [comment]
I cannot understand first comment.
"your first commit includes the sha of the commit you are syncing translations up to."
How can I get the sha of the commit syncing translations up to?

**Comment by cristobalcl** [comment]
How is the current status of the locale build?

After normally building, with no errors, there is no `.mo` files in `build/src/nvim/po`, which contradicts the [instructions](https://github.com/neovim/neovim/wiki/Building-Neovim#localization-build). What strikes me is that when I run `nvim` it shows me the correct language. I have no idea where it is taking, but I suppose it's from the system installation of vim or nvim (installed from the ppa repository)... somehow...

**Comment by cristobalcl** [comment]
Last update:

I found that nvim is taking the locale file from `/usr/share/locale-langpack/es/LC_MESSAGES/vim.mo` instead of `/usr/share/locale/es/LC_MESSAGES/nvim.mo` (which I suppose should be the correct one). I'm on Kubuntu 14.04, and installed nvim from the repo, but I compiled from git also, by the way.

The solution was:

```bash
sudo cp /usr/share/locale/es/LC_MESSAGES/nvim.mo /usr/share/locale-langpack/es/LC_MESSAGES/
```

And:

```diff
diff --git a/src/nvim/vim.h b/src/nvim/vim.h
index 17f9cbc..f57ee60 100644
--- a/src/nvim/vim.h
+++ b/src/nvim/vim.h
@@ -43,7 +43,7 @@ Error: configure did not run properly.Check auto/config.log.
 
 /* Can't use "PACKAGE" here, conflicts with a Perl include file. */
 #ifndef VIMPACKAGE
-# define VIMPACKAGE     "vim"
+# define VIMPACKAGE     "nvim"
 #endif
 
 #include "nvim/os/os_defs.h"       /* bring lots of system header files */
```

I don't know if the `VIMPACKAGE` def keeps the old name for some reason. Also, I didn't try to `make install` my compiled version, so I don't know if the `vim.mo` file is overwritten or something like that.

**Comment by justinmk** [comment]
@cristobalcl Thank you.

**Comment by justinmk** [comment]
Closing until someone takes ownership of this. In the meantime it should not appear in the `entry-level` list.
