### ISSUE TITLE
Could not execute an autocmd when a terminal buffer is created

### ISSUE THREAD

**Issue by JulioJu** [neovim/neovim#7678]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently? irrelevant
- Operating system/version: Arch Linux
- Terminal name/version: GNOME Terminal 3.26.2 Using VTE version 0.50.2 +GNUTLS  or TTY
- `$TERM`: xterm-256color or linux

### Steps to reproduce using
With:
- shell: zsh with or without `.zshrc` or sh
- With the fallowing vimrc: `autocmd BufWinEnter,WinEnter term://* startinsert`
```
nvim -u ~/minimalVimrc +term
```
or 
```
nvim
:terminal
```

### Actual behaviour
No enter in insert mode.
I've also tested with `autocmd BufCreate,BufWinEnter,WinEnter term://* startinsert`
or with `autocmd TermOpen term://* startinsert`.
I've tested with other `autocmd`, doesn't work. 
### Expected behaviour
Execute the `autocmd` and enter in insert mode.
Works with a vimrc with only `autocmd BufWinEnter,WinEnter * startinsert`
\[note: should not be the same as https://github.com/neovim/neovim/issues/4100 \]

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/7429

**Comment by JulioJu** [comment]
@justinmk it's not the same as #7429. 
This issue is a regression between neovim 0.2.0-2 and neovim 0.2.1-2.

**Comment by justinmk** [comment]
Can you bisect?

**Comment by nateozem** [comment]
Here is what I get from bisect
```
$ git bisect good
7d183e89f7c055c8f5217e91294123a5aa0a5e2d is the first bad commit
commit 7d183e89f7c055c8f5217e91294123a5aa0a5e2d
Date:   Thu May 25 10:11:34 2017 +0100

    Use Normal mode as default when opening a new terminal

:040000 040000 47cc6937abad47e6ff0f5b1b4204d16351b58453 ea00dac367cad2bb8ee92a5bc04f186b6a9da34c M       src
```

**Comment by justinmk** [comment]
autocmd TermOpen * startinsert

**Comment by nateozem** [comment]
@justinmk 
awe ... that makes sense. I should've known.

**Comment by JulioJu** [comment]
@justinmk Thanks for the explanation :-). 
@nateozem I must learn how to use `git bisect`. Very powerful ! I've lost lot of time to find the good commit (I've found, but have posted before me). I'm interested if you have  the script ?

**Comment by nateozem** [comment]
@JulioJu I have no script. It was a manual process when using `git bisect`. You may check the manpage (`man git-bisect`)  or probably find some article around the internet that explains it better. I'm not sure if there is a better way than going through each potential commit, then build, and test.

**Comment by JulioJu** [comment]
Ok thanks !
