### ISSUE TITLE
The choco installation script trying to download an unexisting zip from github

### ISSUE THREAD

**Issue by josian** [neovim/neovim#7682]
- `nvim --version`: `0.2.2`
- Operating system/version: Windows 10 64bit
- Terminal name/version: cmd
- `$TERM`: `choco install neovim`

### Actual behaviour

I've tried installing neovim using chocolatey, as described [here](https://github.com/neovim/neovim/wiki/Installing-Neovim).

```
choco install neovim
```

But it tries to download `https://github.com/neovim/neovim/releases/download/v0.2.1/nvim-win64.zip` which doesn't exist in the releases.  This file naming convention started in 0.2.2.  Also, looks like 0.2.2 is the latest stable version, but chocolatey still thinks it's 0.2.1, at least for Windows 10 64bit.

### Expected behaviour

When running `choco install neovim`, I expect to have the current stable version installed.

**Comment by ZyX-I** [comment]
#7635
