### ISSUE TITLE
Lilyterm defaults use the wrong terminal for nvim 

### ISSUE THREAD

**Issue by magks** [neovim/neovim#7686]
- `nvim --version`: 0.2.2
- Vim (version: 8.0.1297) behaves differently?
- Operating system/version: Arch Linux/ 4.13.12-1-ARCH 
- Terminal name/version: Lilyterm 
- `$TERM`: xterm 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:
```

### Actual behaviour
Command line displays the following characters after the colon:
:[2 q

### Expected behaviour
Expecting just a colon -->  :

The issue isn't there when opening nvim from gnome-terminal, terminology, or xterm (only other three terminals I tried). 

I looked in the documentation on terminfo and I saw that different terminals need different settings as for `term`. Lilyterm is a libvte based terminal so running 'export TERM=vte' fixed the issue, as mine was set to `xterm`.

Lilyterm's settings (in /etc/lilyterm.conf) allow setting the terminal to use. (By default, it uses xterm.) Changing the setting to vte allowed me to fix the issue without adding an `export TERM=vte` to an environment init file.

**Comment by justinmk** [comment]
Not sure what "use the wrong terminal" means. Also confused by the solution.

Regardless, if your term claims to be xterm-compatible, it would not sure that escape sequence. This has been covered zillions of times in closed, duplicate issues.
