### ISSUE TITLE
ext_cmdline and tabbing through results prints dots in message/cmd line

### ISSUE THREAD

**Issue by deomitrus** [neovim/neovim#7689]
- `nvim --version`: 0.2.2 & 0.2.3-80-ga494c9991
- Vim (version: ) behaves differently?
- Operating system/version: Mac OS 10.12.6
- Terminal name/version: external GUI
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

Set `ext_cmdline: true` when calling `nvim_ui_attach`

I put together a minimal remote-ui implementation demonstrating this behavior in the following repo: https://github.com/deomitrus/nvderp

### Actual behaviour

When using external command line and pressing wildchar (e.g. `nvim_input('<Tab'>)` ) the messages line prints out dots:

![](https://deomitrus.github.io/nvderp/dots.gif)

### Expected behaviour

I would expect no dots to be printed out.

I'm not sure if i'm missing some option that enables/disables this? Am I doing something wrong? Anything else I can test out? Do I have a bug in both of my remote-ui implementations? Has anyone else observed this while using `ext_cmdline`?

I have tested both in 0.2.2 and master (built at the time of this post). I tried it in my own GUI implementation and in a new repo using only the node neovim library (linked above).

I have only observed this to happen on wildchar triggers. There does not seem to be any difference if wildmenu is set to external or not.

Thoughts?

**Comment by bfredl** [comment]
I can reproduce in python-gui.

**Comment by bfredl** [comment]
it does `MSG_PUTS("...")` to show "that it is busy". We can just disable it for ext_wildmenu.

**Comment by bfredl** [comment]
should be fixed on master.

**Comment by deomitrus** [comment]
I have verified that this issue is fixed on master. 

Thanks for the quick fix! You guys rock!
