### ISSUE TITLE
Ctrl-C while :make does not kill the process the make started.

### ISSUE THREAD

**Issue by EzoeRyou** [neovim/neovim#7691]
- `nvim --version`:NVIM v0.2.0
- Vim (version: 8.0) behaves differently? yes
- Operating system/version: Ubuntu 17.10
- Terminal name/version: Gnome Terminal 3.24.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Let `program` be a executable file which continuously run:

~~~
$ cat program.c
int main() { while(true) ; }
$ gcc program.c -o program
~~~

Write a `Makefile` file with a target which execute the `program`:

~~~
run:
	./program
~~~

Invoke :make in Neovim.

~~~
:make run
~~~

Press `Ctrl-C` to terminate the make.

### Actual behaviour

The process for `./program` is not killed in Neovim.

### Expected behaviour

The process for `./program` is killed, that is the behavior of Vim.

**Comment by miuirussia** [comment]
Any news?

**Comment by nimitbhardwaj** [comment]
Its running fine, error is resolved

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/8107
