### ISSUE TITLE
:set spell fails to download spellfile, for an unknown reason.

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [neovim/neovim#7694]
- `nvim --version`: **v0.2.0**
- Vim (version: ) behaves differently? **Yes**
- Operating system/version: macOS Sierra **10.12.6**
- Terminal name/version: **Terminal.app**
- `$TERM`: **xterm-256color**

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set spell
```

### Actual behaviour
```
spellfile#LoadFile(): No (writable) spell directory found.
Created /Users/ec/.local/share/nvim/site/spell
No spell file for "en" in utf-8
Download it?

Downloading en.utf-8.spl...
:!links 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl' -source > '/var/folders/3b/mxfmd44s6zn50_1wmkrxs19w0000gn/T/nvimZnbKEi/
1.spl'

"/var/folders/3b/mxfmd44s6zn50_1wmkrxs19w0000gn/T/nvimZnbKEi/1.spl" 0L, 0C
Could not find it, trying en.ascii.spl...
:!links 'http://ftp.vim.org/pub/vim/runtime/spell/en.ascii.spl' -source > '/var/folders/3b/mxfmd44s6zn50_1wmkrxs19w0000gn/T/nvimZnbKEi/
1.spl'

"/var/folders/3b/mxfmd44s6zn50_1wmkrxs19w0000gn/T/nvimZnbKEi/1.spl" 0L, 0C
Download failed
Warning: Cannot find word list "en.utf-8.spl" or "en.ascii.spl"
```

`curl`'ing the same file at the terminal by hand seems to work fine.

### Expected behaviour
Presumably, that NVim would either explain the error, and hopefully offer alternatives when the server cannot be reached.

**Comment by fmoralesc** [comment]
The `spellfile` plugin uses the `NRead` command fro `netrw` to download the file. For some reason, it seems to be trying to use `links` instead of `curl`, `wget` or `fetch`, and that is failing.  Can you test downloading the file with
``` sh
!links 'http://ftp.vim.org/pub/vim/runtime/spell/en.utf-8.spl' -source > 'spell.spl'
```

**Comment by justinmk** [comment]
Yes, we depend on netrw. Avoiding that dependency is covered by https://github.com/neovim/neovim/issues/7189

Other than that please try what @fmoralesc mentioned. Or say what steps can reproduce the issue.

**Comment by ELLIOTTCABLE** [comment]
This is strange — the reported invocation in the original post works for me, now. (I'm on a roadtrip, and using a different network — but I'm on the same VPN, so it shouldn't make a difference?)

Perhaps this Issue should be about providing better error-messages in the case of a network failure when downloading the spellfile, then! 🤣
