### ISSUE TITLE
Cursor disappear when using termguicolors

### ISSUE THREAD

**Issue by meijieru** [neovim/neovim#7696]
- `nvim --version`: v0.2.3-dev
- Vim (version: ) behaves differently? No
- Operating system/version: Win10
- Terminal name/version: MobaXterm
- `$TERM`: xterm-256color

### Steps to reproduce

Using this `.vimrc`

```
syntax on
colorscheme desert
set termguicolors
```
### Actual behaviour

![image](https://user-images.githubusercontent.com/9511136/34382601-005a2858-eb4b-11e7-95a9-e18c86dc6ddf.png)

Cursor disappeared

### Expected behaviour

Cursor should exist

**Comment by justinmk** [comment]
Does changing the `Cursor` highlight fix it? 

    :hi Cursor guibg=red guifg=white

With `termguicolors` Nvim will color the cursor if possible, and if specified by your `guicursor` setting. 

What does this report:

    :verbose set guicursor?

**Comment by meijieru** [comment]
It does not work.

The output is `guicursor=n-v-s-sm:block,i-ci-ve:ver25,r-cr-o:hor20`

**Comment by meijieru** [comment]
@justinmk It seems a problem of linux client.
When I ssh to a ubuntu 16.04, it works well. But it failed on ubuntu14.04 version.

**Comment by justinmk** [comment]
With Nvim 0.2.3 (current HEAD) you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  

> When I ssh to a ubuntu 16.04, it works well. But it failed on ubuntu14.04 version

In each of those cases, on the remote ubuntu machines, try this (again, requires latest HEAD):

    nvim -V3log
    :q

(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

Then the file named `log` will have a `--- Terminal info ---` section. Please post it for each case.

This will tell us exactly the difference between the terminfo values for the machine that works and the machine that doesn't.

**Comment by meijieru** [comment]
Sorry, I miss load vimrc file, so both of them have this problem

**Comment by janlazo** [comment]
Is mobaxterm using "Ubuntu Bash" (WSL) or regular bash.exe from cygwin/msys2?

**Comment by justinmk** [comment]
@meijieru Your steps to reproduce mention `set cursorline`. Without that setting, the problem doesn't occur?

**Comment by meijieru** [comment]
@janlazo I don't use WSL

**Comment by meijieru** [comment]
@justinmk It still occurs.

**Comment by janlazo** [comment]
Are you using mobaxterm to ssh to an Ubuntu server that has neovim instead of running neovim on mobaxterm directly?

From trying out the portable version, it's looks like Cygwin bash running on mintty.
```
[2017-12-16 22:56.33]  /drives/c/Neovim/bin
[janlazo] > ./nvim.exe
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...

Vim: Finished.
```

**Comment by meijieru** [comment]
@janlazo The previous one.

**Comment by meijieru** [comment]
@justinmk @janlazo This problem comes from `termguicolors`, as I set this in vim, it behave the same.

**Comment by justinmk** [comment]
That suggests that it's a bug in mobaxterm RGB support.

**Comment by idvorkin** [comment]
@meijieru  Did you find a fix for this?

**Comment by janlazo** [comment]
Did you try on master and does this happen with putty (ie. ssh with mintty terminal emulator) as well or only mobaxterm?

**Comment by idvorkin** [comment]
No it does **not** happen with putty/windows console.  I'm confident this is a mobaxterm issue because it also repros with normal vim. I was hoping the issue creator had a work around.

**Comment by jdhao** [comment]
I have also met with this problem when using mobaxterm v10.9 to ssh to my remote Linux servers. The cursor in Nvim disappear if I use `set termguicolors`. Without that option, the cursor will show up.  For more info, see [here](https://github.com/neovim/neovim/issues/3692#issuecomment-422284227)

**Comment by dulinux** [comment]
I can confirm this with mobaxterm + nvim + set termguicolors. Should be a mobaxterm issue.
