### ISSUE TITLE
system() function misbehaves when given escaped arguments

### ISSUE THREAD

**Issue by AdnoC** [neovim/neovim#7698]
- `nvim --version`: NVIM v0.2.3-94-gaec81f44d
- Vim (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version: cmd.exe/powershell.exe/nvim-qt
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

Start in a directory with some file `foo`.

```
nvim -u NORC
:echo system('"cat" "foo"')
```

### Actual behaviour

The error message below is printed.

> 'cat" "Makefile' is not recognized as an internal or external command,
> operable program or batch file.

### Expected behaviour

The contents of file `foo` should be printed to the terminal.

### Additional info

Interestingly, if the command you are passing to system takes more than one arguments, if you did `:echo system('"cat" foo bar foobar "otherfoo" otherbar otherfoobar')` for example, it fails. But if you leave either the executable name or all of the arguments unquoted its fine. Quoting both `foo` and `bar` runs the command correctly, as does quoting only the executable.

Additionally, running

```
:echo system('"cat" foo "bar" foobar')
```

produces the following error message:

> 'cat" foo "bar' is not recognized as an internal or external command,
> operable program or batch file.

Which makes me think that something is being cut off.

### Difference from Vim

After some experimenting, it seems like Vim (using version `vim 8.0.604` from chocolatey) has this issue to a lesser degree. It happens if you try using `type` or `dir`, but not when running `cat`, `ctags`, or `rustc`. (which kinda makes sense since those are apparently `cmd.exe` internal commands).

**Comment by janlazo** [comment]
See https://github.com/neovim/neovim/pull/7343

**Comment by AdnoC** [comment]
Good to know that its being worked on.

**Comment by janlazo** [comment]
https://github.com/junegunn/fzf/commit/c4185e81e86e339ae2c18e5d9b596b7992ec179b is how I did it in golang.
