### ISSUE TITLE
Camelcase & underscore motion as a feature

### ISSUE THREAD

**Issue by hos** [neovim/neovim#770]
This plugin for vim summarizes the idea: https://github.com/bkad/CamelCaseMotion
I have seen in other editors, and I find this feature very handy, i.e. motion and editing that recognizes camelCase words and words with underscore. 
Maybe it could be developed as an optional built-in feature?

**Comment by amitlevy21** [comment]
@justinmk So its been a while since this, maybe reconsider it?
