### ISSUE TITLE
quickfix: custom format

### ISSUE THREAD

**Issue by euclio** [neovim/neovim#7701]
I'd like to be able to change the format of the quickfix list. In particular, I'd like to be able to set the filenames to be short, instead of always showing the full path. Setting the line/col format, etc. would be useful as well.

**Comment by SevereOverfl0w** [comment]
Fwiw, I have this in my plugin which conceals long .m2 filenames:

```
setlocal concealcursor=nvic
setlocal conceallevel=2

call matchadd('Conceal', 'zipfile:.*::', 99, -1, {'conceal': ''})
```

There is also this plugin: https://github.com/MarcWeber/vim-addon-qf-layout which rewrites the quickfix buffer in various ways for alignment, etc.

So it appears there is already some mechanism for doing this. However, having this available behind a supported API would be fantastic.

**Comment by wsdjeg** [comment]
@euclio two months ago I send a same feature request in vim_dev mail list, and there is a user work a patch about this feature. please check:

https://groups.google.com/forum/?nomobile=true#!topic/vim_dev/l38lbzvWd1w

**Comment by YorickPeterse** [comment]
https://github.com/vim/vim/issues/4425#issuecomment-640123274 mentions some patches merged into upstream Vim that make this possible. It would be nice to also have these changes in NeoVim :smiley:

**Comment by SevereOverfl0w** [comment]
The vim-qf plugin is already able to do this in neovim, it uses the `module` property which is already in neovim.

**Comment by YorickPeterse** [comment]
@SevereOverfl0w I'm not aware of vim-qf being able to do so. IIRC all it can do is shorten file paths, or is there perhaps a feature that I overlooked?

**Comment by SevereOverfl0w** [comment]
@YorickPeterse the original request was for shorter file paths.

The same strategy can be used for any kind of transformation.

**Comment by YorickPeterse** [comment]
@SevereOverfl0w

> The same strategy can be used for any kind of transformation.

I'm not sure if that's entirely true. Looking at how [vim-qf formats the quickfix list](https://github.com/romainl/vim-qf/blob/fac7a84b50de99a739e91045c8a59649f639d9fb/autoload/qf.vim#L149), it appears that you can overwrite/change data (e.g. the file path), but you can't change how that is displayed. For example, it seems you can't use this to change something like this:

```
runtime/tests/test/std/test/test_error.inko|9 col 3| TestFailure.new(message: 'oops', location: frame)
runtime/src/std/test/test.inko|77 col 18| @failure = TestFailure.new(
```

into something like this:

```
File                                        Line Column
runtime/tests/test/std/test/test_error.inko 9    3      TestFailure.new(message: 'oops', location: frame)
runtime/src/std/test/test.inko              77   18     @failure = TestFailure.new(
```

**Comment by SevereOverfl0w** [comment]
Seems like there's two different use cases being discussed here :)

**Comment by reportaman** [comment]
@SevereOverfl0w I guess people are requesting vim's "quickfixtextfunc"

**Comment by kevinhwang91** [comment]
Should this be closed?

**Comment by janlazo** [comment]
Yes.
@kevinhwang91 Thanks for the reminder and your port of `quicktextfunc`.
