### ISSUE TITLE
Issue with tcomment plugin (Python new line indentation)

### ISSUE THREAD

**Issue by victoriastuart** [neovim/neovim#7702]
Hello - this appears to be Nvim-related, as I just tried it in Vim, and there it seemed to not be an issue.

In indented Python code (in Nvim), when I open a new line (O, o, or entering Insert mode) and type the hashtag (#), that hashtag moves to column position 1 (non-indented).  I have to manually move to the start of the line, and properly indent those commented lines.

I am using the tcomment plugin (https://github.com/tomtom/tcomment_vim).

**Comment by jamessan** [comment]
What does `:verbose set smartindent? cindent? cinkeys? indentexpr? indentkeys?` show?

**Comment by victoriastuart** [comment]
Hi: sorry, this was my fault.  It turns out I had "set smartindent" in my ~/.vimrc.  My "issue" / solution is discussed here, http://vim.wikia.com/wiki/Restoring_indent_after_typing_hash

Basically, replace

    set smartindent
with

    set cindent
    set cinkeys-=0#
    set indentkeys-=0#
in .vimrc

My apologies!  :-)

Aside: I mentioned .vimrc, above; I symlink my ~/.vimrc for use with nvim, as follows:

    ln -s ~/.vim ~/.config/nvim
    ln -s ~/.vimrc ~/.config/nvim/init.vim

**Comment by jamessan** [comment]
My suggestion would be simpler.  Only put `set autoindent` in your init.vim and then let the filetype-specific indenting (enabled by default in nvim, requires `filetype indent on` in vim) do the rest.

**Comment by victoriastuart** [comment]
@jamessan:  I like it; done!  :-D
