### ISSUE TITLE
Weird terminal title after quitting nvim

### ISSUE THREAD

**Issue by silenc3r** [neovim/neovim#7711]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? no
- Operating system/version: Fedora 26
- Terminal name/version: gnome-terminal, xterm
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
add:
PROMPT_COMMAND=""
to your ~/.bashrc

then run:
nvim -u NORC -c 'set title' -c 'quit'
```

### Actual behaviour

After quitting nvim terminal title is set to some weird string looking like this:  
```
Project-Id-Version: Vim(UK English) Report-Msgid-Bugs-To: POT-Creation-Date: 2014-05-26 14:21+0200 PO-Revision-Date: 2003-02-25 11:05+0000 Last-Translator: Mike Williams...
```

### Expected behaviour

No weird string is set as terminal title.

**Comment by justinmk** [comment]
> After quitting nvim terminal title is set to some weird string looking like this:

That really happens after `nvim -u NORC -c 'set title' -c 'quit'` ...? 

> Terminal title is restored to default after quitting nvim

What "default"? Querying the terminal for its title is supported by almost no terminal emulator, and is disabled by default in xterm for "security reasons". So Nvim doesn't support that at all, it's not worth the bother. 

You can use `:set titleold=...` to manage the restored title on exit. 

Please read `:help 'title'`, `:help 'titleold'`, and `:help 'titlestring'`, and verify that you or a plugin is not setting any or all of those. 

See also this note in Vim's `:help 'title'`:

```
  When Vim was compiled with HAVE_X11 defined, the original title will                                                                                    
        be restored if possible.  The output of ":version" will include "+X11"                                                                                  
        when HAVE_X11 was defined, otherwise it will be "-X11".  This also                                                                                      
        works for the icon name 'icon'.                                                 
```

**Comment by silenc3r** [comment]
It turns out the problem was my ~/.bashrc file. I was overwriting PROMPT_COMMAND variable instead of appending to it.

Nevertheless the title set by neovim is a bit weird. You can see this title when you add
```
PROMPT_COMMAND=""
```
at the end of your ~/.bashrc file.

Vim behaves the same way.

**Comment by justinmk** [comment]
> I've tested other applications, namely ipython and tmux and they both manage to restore preexisting terminal title after exiting even when with overwritten PROMPT_COMMAND.

I just tried tmux 2.3, it doesn't restore the window title.

If you know of some widely-supported way to query the terminal for its title or somehow restore it, please do link to the tmux source that does so, or let us know the termcodes.

**Comment by silenc3r** [comment]
My bad, they don't restore the title. I must've commented out the wrong parts of .bashrc when testing.
