### ISSUE TITLE
'cursorline': highlight screen line instead of text line

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#7716]
- `nvim --version`: v0.2.3-99-g873af01
- Vim (version: ) behaves differently? no
- Operating system/version: N/A
- Terminal name/version: N/A
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set cursorline

```

### Actual behaviour
Longer lines that wrap around the screen have the `cursorline` highlight applied to all screen lines instead of only the screenline the cursor is actually on.

### Expected behaviour
Since the primary benefit of `cursorline` is to help in locating the cursor in a buffer, and as far as I can tell, it serves no benefit to extend that past the current screen line to the remainder of the physical line.

In addition, `cursorcolumn` doesn't make sense outside the context of screen lines, and `cursorcolumn` and `cursorline` obviously go hand-in-hand and logic that applies to one should extend to the other.

**Comment by justinmk** [comment]
> it serves no benefit to extend that past the current screen line to the remainder of the physical line.

Many would disagree, it's a useful visual signal, specially for people who `:set nonumber`.

**Comment by mqudsi** [comment]
Ah, I did not consider `nonumber`. Very good point!

**Comment by justinmk** [comment]
Also it's fairly easy to achieve what you want using `matchadd()`:

    :call matchadd('CursorLine', '.*\%#.\{,'.winwidth('').'}', 10)

(do that in a WinEnter autocmd or whatever)

Might be a better way, but  I would say this can be robustly achieved in a plugin so not worth adding to core.

**Comment by chrisbra** [comment]
I have a written [cursorscreenline](https://github.com/chrisbra/vim-mq-patches/blob/master/cursorscreenline) patch. It's old so it might not be apply cleanly without changes

**Comment by teto** [comment]
some solutions have been provided. can we close ?

**Comment by chrisbra** [comment]
As of Vim https://github.com/vim/vim/releases/tag/v8.1.2029

Vim has the feature to highlight screenlines. Not sure, if Neovim merged that patch.

**Comment by teto** [comment]
not yet thanks for the pointer.

**Comment by zeertzjq** [comment]
Implemented in #15226.
