### ISSUE TITLE
How to use Command key in key mappings?

### ISSUE THREAD

**Issue by ericandrewlewis** [neovim/neovim#7721]
Hi! I read that neovim [has support](https://github.com/justinmk/neovim/commit/99d4c8c29c4a9371c268cc20e4805709d86fb686) for using the command key in key mappings.  I've searched for how to get this working in the neovim terminal but cannot find anything on the topic.

Thanks a lot for neovim, I'm enjoying it!  🙂

- `nvim --version`: `NVIM v0.2.2`
- Vim (version: 8.0) behaves differently? No
- Operating system/version: macos Sierra 10.12.6
- Terminal name/version: iTerm2
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
" Create a key mapping to indent text when pressing Command+]
:nmap <D-]> >>
" Add text to a line and then press Command+]
```

### Actual behaviour

One of iTerm2's application-level keyboard shortcut handlers "Select Next Pane" attempts to run.

### Expected behaviour

The current line is indented in neovim.

**Comment by wsdjeg** [comment]
you should disable the key binding of item2 itself.  otherwise the key will not be send to neovim.

BTW, you can test with `:call nvim_input("\<D-]>")`, if it works well, I think it is issue with terminal itself.

**Comment by ericandrewlewis** [comment]
I was able to find a workaround for this. In iTerm2 under Preferences > Profiles > Default > Keys I'm able to add a key mapping for a specific shortcut `⌘]` and tell iTerm to take the action "Send Text" with the keys I want to execute, `>>`

<img width="1034" alt="screen shot 2017-12-12 at 10 19 27 am" src="https://user-images.githubusercontent.com/1087646/33892129-00e5c86c-df26-11e7-8efa-aa666c3547a1.png">

**Comment by YassineGherbi** [comment]
How can I disable the key binding inside iTerm2 itself? @wsdjeg  Currently, this command `:call nvim_input("\<D-]>")` does nothing for me
