### ISSUE TITLE
Garbage characters

### ISSUE THREAD

**Issue by paddor** [neovim/neovim#7722]
Possibly related to #5990 or #6154 or #7381, but those issues have all been closed.

- `nvim --version`: 
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /home/p/.linuxbrew/Library/Homebrew/shims/linux/super/gcc-5 -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/tmp/neovim-20171213-3645-loe0db/build/config -I/tmp/neovim-20171213-3645-loe0db/src -I/home/p/.linuxbrew/include -I/home/p/.linuxbrew/include -I/home/p/.linuxbrew/include -I/home/p/.linuxbrew/include -I/home/p/.linuxbrew/include -I/home/p/.linuxbrew/include -I/usr/include -I/tmp/neovim-20171213-3645-loe0db/build/src/nvim/auto -I/tmp/neovim-20171213-3645-loe0db/build/include
Compiled by p@px

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/p/.linuxbrew/Cellar/neovim/HEAD-3405704/share/nvim
"

Run :checkhealth for more info
```
Also happens with 0.2.2.

- Vim (version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 13 2017 17:57:19)`) behaves correctly.
- Operating system/version: Xubuntu 16.04.3 LTS
- Terminal name/version: xfce4-terminal 0.6.3
- `$TERM`: `xterm` and `xterm-256color` and `xterm-color`. (see below)

The "Emulation setting" in the terminal preferences is "xterm". Anything else (like "xterm-256color" or "xfce4-terminal" scrambles the terminal up badly rendering it unable to use.)

### Steps to reproduce using `nvim -u NORC`

```
touch foobar
nvim -u NORC foobar
```

Also tried with a config file containing nothing but this:
```
filetype plugin indent off
syntax off
```
and specified it with `-u`. I also tried with `--noplugin -m -n -u scramble-bug.vim` so the output of `:set` is merely:

```
--- Options ---
  columns=270         helplang=en         lines=65          noloadplugins         scroll=31           scrollback=-1       updatecount=0       window=64         nowrite
```

### Actual behaviour
As soon as I enter the command mode using `:`, I see some weird stuff on the command line. Copy pasted into here (the first character looks different in terminal though):
```
:[2 q
```
Same stuff appears in the buffer when I enter insert mode. Pressing ctrl-L (redraw) removes the garbage.

I just realized that if I set `TERM=xfce4-terminal`, it works fine with NeoVim (at least HEAD). But then Vim complains about not knowing that terminal type. 

### Expected behaviour
No scrambling.

**Comment by paddor** [comment]
Working with `TERM=xfce4-terminal` also changed the colors in my fish shell and makes the cursor inside the nvim buffer run around like crazy while scrolling with ctrl-u/ctrl-d or using the mouse wheel. So I really think that's not the right setting, even though it solves the issue with the scrambling characters.

**Comment by justinmk** [comment]
That means the terminal (xfce4) is broken. 

- It claims to be xterm-compatible (`TERM=xterm-256color`), yet doesn't implement this basic xterm feature. 
- It doesn't ignore unknown termcodes. Instead it prints them. 

AFAIK xfce uses libvte, and this is fixed in newer versions of libvte.

You can workaround this issue by disabling 'guicursor' in your Nvim config:

    set guicursor=

Or use a different terminal.

Added to the FAQ:

https://github.com/neovim/neovim/wiki/FAQ#terminal-shows-weird-symbols-2-q-when-changing-modes
