### ISSUE TITLE
test / assert_spec.lua fails with a symlink

### ISSUE THREAD

**Issue by Jun-T** [neovim/neovim#7724]
I have an external HDD which is mounted at `/Volumes/D` (I'm using macOS),
and the nvim source (clone of the latest git master) is in `/Volumes/D/dev/src/nvim/neovim/`
I also have a symlink: `/Users/jt/dev/ --> /Volumes/D/dev/`
If I run:
`$ cd  /Users/jt/dev/src/nvim/neovim/`
`$ make test`
then the test fails as follows.
In short, the message from nvim includes the real pathname while what is expected the symlink name.

> [  FAILED  ] ...v/src/nvim/neovim/test/functional/legacy/assert_spec.lua @ 157: assert function: v:errors should have file names and passed messages
> ...v/src/nvim/neovim/test/functional/legacy/assert_spec.lua:8: Expected objects to be the same.
> Passed in:
> (table) {
>  *[1] = '/Volumes/D/dev/src/nvim/neovim/Xtest-tmpdir/nvim-test-lua-546 line 1: 'equal assertion failed''
> ---snip--- }
> Expected:
> (table) {
>  *[1] = '/Users/jt/dev/src/nvim/neovim/Xtest-tmpdir/nvim-test-lua-546 line 1: 'equal assertion failed''
> ---snip--- }
> 
> stack traceback:
> 	...v/src/nvim/neovim/test/functional/legacy/assert_spec.lua:8: in function 'expected_errors'
> 	...v/src/nvim/neovim/test/functional/legacy/assert_spec.lua:166: in function <...v/src/nvim/neovim/test/functional/legacy/assert_spec.lua:157>

**Comment by zeertzjq** [comment]
Fixed by #16064
