### ISSUE TITLE
GUI: add a 'quit' notification

### ISSUE THREAD

**Issue by stacksmith** [neovim/neovim#7727]
NVIM v0.2.2 xubuntu 17.04 zesty no terminal/messagepack only.

Quitting neovim running inside a gui causes a silent disconnect (in my case, closed handles).

It would be helpful to send some notification that allows the GUI to shut down gracefully.

**Comment by justinmk** [comment]
One can use `rpcrequest()` or `rpcnotify()` from a `VimLeavePre` autocmd. 

    nvim_command('autocmd VimLeavePre * call rpcnotify(...)')

More generally I would like to expose the existing vim autocmds as subscribable RPC events so that the above (ugly) dance can be avoided.

**Comment by justinmk** [comment]
As mentioned `VimLeavePre` already covers this.

The more general task of exposing a nicer mechanism for remote clients to listen to non-UI events, is a different issue.
