### ISSUE TITLE
Expression register calculations incorrect with leading zeros

### ISSUE THREAD

**Issue by KNejad** [neovim/neovim#7731]
When using the expression register in NVIM, calculations with a leading 0 **sometimes** give an incorrect output.

- `nvim --version`: 
```
NVIM v0.2.3-244-gbfb21f3e0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/keeyan/projects/neovim/build/config -I/home/keeyan/projects/neovim/src -I/home/keeyan/projects/neovim/.deps/usr/include -I/home/keeyan/projects/neovim/.deps/usr/include -I/home/keeyan/projects/neovim/.deps/usr/include -I/home/keeyan/projects/neovim/.deps/usr/include -I/home/keeyan/projects/neovim/.deps/usr/include -I/home/keeyan/projects/neovim/.deps/usr/include -I/usr/include -I/home/keeyan/projects/neovim/build/src/nvim/auto -I/home/keeyan/projects/neovim/build/include
Compiled by keeyan@thinkpad-yoga

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Debian 9
- Terminal name/version: xfce4-terminal 0.8.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i<C-r>= 300 - 044 <return>
```

### Actual behaviour

output is 264

### Expected behaviour

output should be 256

**Comment by jamessan** [comment]
It's doing exactly what is intended.  The number is being interpreted as octal, exactly as intended.

```
							*octal*
Conversion from a String to a Number is done by converting the first digits to
a number.  Hexadecimal "0xf9", Octal "017", and Binary "0b10" numbers are
recognized.  If the String doesn't start with digits, the result is zero.
Examples:
	String "456"	-->	Number 456 ~
	String "6bar"	-->	Number 6 ~
	String "foo"	-->	Number 0 ~
	String "0xf1"	-->	Number 241 ~
	String "0100"	-->	Number 64 ~
```

```
:echo 044
36
```

**Comment by ZyX-I** [comment]
By the way, with that version you should’ve seen a hint by highlighting system if you typed that: zero is colored differently from the rest of the number precisely for this reason.

**Comment by KNejad** [comment]
I suspected that it might be some feature that I didn't know about and not a bug but I couldn't find it anywhere so I figured it was worth posting. I believe it is quite obscure if you don't know about it and could easily lead to people making incorrect calculations. The highlighting that @ZyX-I pointed to doesn't appear for me but even if it did it would be easy to miss when pasting a long string from a register. Maybe there could be some way of making it more obvious?

I think the reason I couldn't find it was because I didn't know it was called the expression register until right before posting. I'll make sure I read the help me page more clearly before posting next time.

**Comment by justinmk** [comment]
@KNejad we default 'nrformats' option to exlcude "octal" for this reason.

@jamessan @ZyX-I why would 'nrformats' not be the authority in this case?

**Comment by jamessan** [comment]
`'nrformats'` only applies to how `<C-a>`/`<C-x>` interpret the number.

**Comment by ZyX-I** [comment]
@justinmk I would like to get rid of as many options controlling parsing process as possible, not the exact opposite, would actually be more happy to get rid of the influence of other options like &ignorecase, &magic, &gdefault on scripts. The more options are affecting plugins the less possible it is for plugin authors to create a robust plugin.
