### ISSUE TITLE
Inconsistent behavior depending on where NVIM_LISTEN_SOCKET is set

### ISSUE THREAD

**Issue by deepakjois** [neovim/neovim#7741]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) behaves differently?
N/A
- Operating system/version:
Arch Linux
- Terminal name/version:
Tilix 1.7.3

- `$TERM`:

`xterm-256color`

### Steps to reproduce using `nvim -u NORC`
First set NVIM_LISTEN_ADDRESS  in `.bashrc` to `/tmp/nvimsocket`
```
nvim -u NORC
echo v:servername
/tmp/nvimzEMgT9/0
```

Now export NVIM_LISTEN_ADDRESS on the bash prompt

```
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
nvim -u NORC
echo v:servername
/tmp/nvimsocket
```

### Actual behaviour
Neovim sets the socket address differently depending on whether the NVIM_LISTEN_ADDRESS variable is set in `.bashrc` or on the bash prompt

### Expected behaviour
Neovim should set the socket address to NVIM_LISTEN_ADDRESS regardless of where it is set.

**Comment by jamessan** [comment]
Are you exporting `NVIM_LISTEN_ADDRESS` in your bashrc?  If not, then it won't be inherited by children.

**Comment by deepakjois** [comment]
Sorry, my bad! I did forget to export it.
