### ISSUE TITLE
No option to delete the swap file and start editing

### ISSUE THREAD

**Issue by Marwes** [neovim/neovim#7748]
- `nvim --version`:
```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/config -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/src/nvim/auto -I/tmp/neovim-20171109-46118-9kky38/neovim-0.2.1/build/include
Kompilerad av brew@Sierra.local
```
- Vim (version: ) behaves differently? Yes, vim gives an option to delete the file
- Operating system/version: OSX
- Terminal name/version: fish/bash/zsh
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Open a file which is already open/has crashed and left the swap file.

### Actual behaviour
Neovim gives no option to delete the file and start editing the file.

### Expected behaviour

An option to delete the swap file and immediately start editing it.

Perhaps this is intentional and one is suppose to delete it manually? But if that is the case then there is a separate issue in that the path displayed to the swap file is wrong.

```
Users/user/.local/share/nvim/swap//%Users%username%Code%src%lib.rs.swp
//                               ^ Extra / here

Users/user/.local/share/nvim/swap/%Users%username%Code%src%lib.rs.swp
```

Third, a minor papercut. I use https://fishshell.com which is addmittedly non-standard but I will mention the papercut anyway. The use of `%` in the path does not play well with it as `%` needs to be escaped in the path which prevents the path from being copy-pasted :/

**Comment by ZyX-I** [comment]
Can you paste the exact message? Normally both Vim and Neovim refer to an already-open process which is supposed to be “the other editor instance editing the same file” if they do not give the option.

Though I must say that neither actually do check whether the mentioned process belongs to Vim/Neovim and process identifiers are being reused: AFAIK the judjment is that the process of checking process name given PID is highly system-dependent, may be forbidden or outright wrong (I mean the case when checking process name gives result which could not possibly have anything to do with the source of the PID being checked: PID namespaces, just NFS with users from different machines, …) and the event in which PID is reused while being not unlikely is not too often to worth the hassle.

---

As for “papercut”: shells are normally configurable, if it was zsh I would say for sure you can create a keyboard shortcut which does escape pasting, and, probably, after learning how url-quote-magic and bracketed-paste-magic work, make that automatic on regular paste (though I would not normally bother as shortcut is much simpler). And it is not like we have many options here given that maximal path length is limited and different shells have loads of different special characters, some even controlled by an option (e.g. I can make zsh use `%` for history expansion in place of `!`). (And we cannot escape the path for pasting as well, nobody knows where you paste to.)

**Comment by Marwes** [comment]
```
Hittade en växlingsfil med namnet "~/.local/share/nvim/swap//%Users%USERNAME%Code%common.rs.swp"
          ägd av: USERNAME   daterad: Wed Dec 20 10:58:49 2017
         filnamn: ~USERNAME/Code/common.rs
          modifierad: nej
         användarnamn: USERNAME   värdnamn: USERNAME
        process-ID: 95382 (körs fortfarande)
Vid öppning av fil "../common.rs"
             daterad: Tue Dec 19 13:47:09 2017

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) En redigeringssession för den här filen kraschade.
    Om så är fallet, använd ":recover" eller "vim -r ../common.rs"
    för att återskapa förändringarna (se ":help recovery").
    Om du redan har gjort det, ta bort växlingsfilen "/Users/USERNAME/.local/share/nvim/swap//%Users%USERNAME%Code%common.rs.swp"
    för att undvika det här meddelandet.

Växlingsfil "~/.local/share/nvim/swap//%Users%USERNAME%Code%common.rs.swp" existerar redan!
                                                                
[Ö]ppna skrivskyddad, (R)edigera ändå, (Å)terskapa, (A)vsluta, A(v)bryt:
```

So I missed that it actually said that another process was editing the file, is that why there is no option to delete the swap? That is, the option to delete and edit only exists if the swap file is from a process that has crashed earlier? I know for sure that vim has given me this option but maybe I never had another instance if it still holding a buffer in memory.

**Comment by ZyX-I** [comment]
Yes for both questions. And note my second paragraph, it checks only for existence of the process with PID recorded in swap file, it does *not* check whether PID belongs to Neovim.

**Comment by chrisbra** [comment]
I believe this was done because there was no portable way to check, that the given PID belongs to Vim

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1455

**Comment by AntonC9018** [comment]
> Yes for both questions. And note my second paragraph, it checks only for existence of the process with PID recorded in swap file, it does _not_ check whether PID belongs to Neovim.

Is there a way to force it to always be there, maybe?
