### ISSUE TITLE
Strange corruption in terminal

### ISSUE THREAD

**Issue by doozr** [neovim/neovim#7749]
Since upgrading to 0.2.2 I've been getting strange character corruption on the screen. Reproducible by starting nvim and pressing `:`. This has been duplicated on several terminals including Terminator, XFCE terminal and Mate terminal. The problem does not appear when using xterm or urxvt.

[Screenshot of corruption](https://imgur.com/a/1xPys)

It disappears if I hit ctrl-L to refresh the terminal so it's a transient thing, not part of the actual rendered output.

```
$ nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

- Operating system/version: Ubuntu 16.04
- Terminal name/version: Various, as described

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

press :
```

### Actual behaviour

Corruption on screen.

### Expected behaviour

No corruption.

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes.
