### ISSUE TITLE
netrw leaves non-unlisted buffer after editing directory if "set hidden"

### ISSUE THREAD

**Issue by JohanAR** [neovim/neovim#7750]
- `nvim --version`:

NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui 

- Vim (version: ) behaves differently? Yes. Issue not present with VIM 7.3 with netrw v140
- Operating system/version: Ubuntu 16.04.3 LTS derivate
- Terminal name/version: GNOME Terminal 3.18.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set hidden
:e .
<select a text file and press enter to edit it>
:ls
```

### Actual behaviour
```
:ls
  1  h   "~/"                           line 1
  3 %a   "~/sethidden.vim"              line 1
```
netrw file browser buffer (1) is not unlisted as it should be. The buffer is also flagged as modifiable

### Expected behaviour
**nvim without set hidden:**
```
:ls
  3 %a   "~/sethidden.vim"              line 1

:ls!
  2u#h-  "~/"                           line 74
  3 %a   "~/sethidden.vim"              line 1
```
Without set hidden it almost behaves like vim 7 (see below) but buffer enumeration is still different.

**vim 7 with set hidden:**
```
:ls
  2 %a   "~/sethidden.vim"              line 1

:ls!
  1u# -  "~/"                           line 1
  2 %a   "~/sethidden.vim"              line 1
```
netrw buffer has number 1, it's unlisted, it's the alternative buffer and it's not modifiable.

**nvim with set hidden works if I use :Explore instead of :e .**
```
:ls
  2 %a   "~/sethidden.vim"              line 1

:ls!
  1u#h-  "~/"                           line 74
  2 %a   "~/sethidden.vim"              line 1
```

**Comment by justinmk** [comment]
> Issue not present with VIM 7.3 with netrw v140

netrw has added a lot of ~features~ bugs since then.

Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

Please report to https://github.com/vim/vim. Thanks!
