### ISSUE TITLE
Feature request: PlugUndefined

### ISSUE THREAD

**Issue by stellarhoof** [neovim/neovim#7754]
We've got `CmdUndefined` and `FuncUndefined`. https://github.com/junegunn/vim-plug offers loading plugins on demand via `<plug>` maps, but it cannot handle if the `<plug>` mapping is an operator.

**Comment by justinmk** [comment]
CmdUndefined and FuncUndefined and both near-useless and were replaced by other mechanisms (e.g. "autoload").

**Comment by stellarhoof** [comment]
Scripts are only autoloaded for undefined functions, not commands. Is there a mechanism that will allow me to achieve the same as `CmdUndefined` does?
In defense of `FuncUndefined`: sometimes plugin authors don't follow best practices and dump all their API in their plugin file and having a way to load the plugin on-demand is very handy.
Would something like `<Plug>script#func` (to mimic autoloaded functions) be terribly hacky?

**Comment by bfredl** [comment]
Trouble is `<Plug>` has no idea where the mapping would end. You would need something like

`map <expr> <Leader>x LazyMap("<Plug>TheMapping", "theplugin")`

But I'm not sure `LazyMap` could do the right thing in nonnormal modes...

**Comment by stellarhoof** [comment]
> Trouble is <Plug> has no idea where the mapping would end
I'm not sure I follow. Doesn't <Plug> get triggered exactly when the mapping ends? Note that vim-plug doesn't need to know what's mapped to the <plug> mapping, since it executes `feedkeys("\<plug>...")` after loading the plugin.

The problem I think is when <plug> is an operator. Doing simply `feedkeys("\<plug>...")` leaves one in operator-pending mode, because there is no way to know on which motion was the handler function called.

> But I'm not sure LazyMap could do the right thing in nonnormal modes...
I'm not sure this is an exhaustive list, but for insert mode one needs to take care to return to the state previous to loading the plugin. In insert mode, this is achieved with `<C-O>`, in visual mode, one can do `gv` to set up the region for the loaded plugin.

**Comment by justinmk** [comment]
I don't think anyone's going to take up this task.  Probably mappings should have a richer API in general.
