### ISSUE TITLE
option to make 'cw' delete the trailing space

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#776]
In Vim, `cw` acts like `ce`, unless cursor is on the last character of a word. Consider adding a `cpo` option to make `cw` behave analogously to `dw`/`yw`.
- https://groups.google.com/d/msg/vim_use/aaBqT6ECkA4/42BkI0qV-aAJ
- https://groups.google.com/d/msg/vim_dev/Dpn3xtUF16I/bSu0KOHDCSUJ
- http://www.reddit.com/r/vim/comments/26nut8/why_does_cw_work_like_ce/

Probably reasonable to also submit this to upstream Vim.

**Comment by justinmk** [comment]
@elmart Feature requests like this are in the "vNext" milestone so that it is clear they aren't related to the current milestone.

**Comment by benmp** [comment]
I think this was resolved by #6234?

**Comment by justinmk** [comment]
:)
