### ISSUE TITLE
File not found on save with QFileSystemWatch

### ISSUE THREAD

**Issue by rcorre** [neovim/neovim#7760]
- `nvim --version`: `0.2.2`
- Vim (version: 8.0) behaves differently
- Operating system/version: `Linux 4.14.7-1-ARCH`
- Terminal name/version: `st 20170303.3a720a3-1`
- `$TERM`: `st-256color`

### Steps to reproduce using `nvim -u NORC`

1. Put the following in `~/test.py`

```
import sys
from PyQt5.QtCore import QFileSystemWatcher
from PyQt5.QtWidgets import QApplication, QWidget

def changed(path):
    print('opening ', path)
    with open(path, 'r') as f:
        print(f.read())

if __name__ == '__main__':
    
    app = QApplication(sys.argv)
    w = QWidget()

    watcher = QFileSystemWatcher()
    watcher.addPath(sys.argv[1])
    watcher.fileChanged.connect(changed)

    w.show()
    
    sys.exit(app.exec_())
```

2. 

```
cd ~
echo foo > foo.txt
nvim -u NORC foo.txt
```

3. 

```
python test.py foo.txt
```

4. Save from `nvim`

### Actual behaviour

```
  File "thing.py", line 7, in changed
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'foo.txt'
```

### Expected behaviour

```
opening  foo.txt
foo bar baz
```

I haven't tried another filesystem watcher, but I _do_ get the expected behavior with `vim -u NORC`. Is there anything you can think of where `nvim` would cause `python`/`Qt` to think the file doesn't exist right after writing it?

Note that this _doesn't_ repro under my `/` partition (e.g. in `/tmp`). It only happens in my `/home` partition. Both are `ext4` partitions. `/home` is 60% full.

**Comment by justinmk** [comment]
When saving files N/Vim will write to a temp file and rename it. @chrisbra do you know if this is controlled by an option?

I thought there was an existing issue for this but I can't find it. Certainly it's been reported on vim_dev or https://github.com/vim/vim/ .  

> I do get the expected behavior with vim -u NORC

`-N` is always needed, if not running with a user config. Try `vim -N -u NORC` .

**Comment by chrisbra** [comment]
there is the 'backupcopy' option, that should control this.

**Comment by rcorre** [comment]
`backupcopy=no` does not resolve this. However, `vim` has the 'broken' behavior with `-N`, so I guess this is not an nvim-specific issue

**Comment by rcorre** [comment]
Ah, I should have tried `backupcopy=yes`. That resolves the issue. I guess the problem is that I'm checking the file in the short interval between renaming it and writing the new one, in which case there isn't really a bug here?
