### ISSUE TITLE
tmux + neovim + termguicolors strange background color.

### ISSUE THREAD

**Issue by karambaq** [neovim/neovim#7764]
I've searched and tried everything.
- `nvim --version`: NVIM v0.2.2
- Vim (version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24))
- Operating system/version: Mac OS High Sierra
- Terminal name/version: iTerm2 3.1.5
- `$TERM`: screen-256color

<img width="802" alt="2017-12-25 0 35 10" src="https://user-images.githubusercontent.com/14233969/34329399-70805988-e90f-11e7-8f47-821059bf2038.png">

**Comment by justinmk** [comment]
Tmux version? Does it happen without tmux?

**Comment by karambaq** [comment]
@justinmk tmux version: 2.6
No, only in tmux.

**Comment by karambaq** [comment]
Nevermind. I found the [solution](https://www.reddit.com/r/vim/comments/5416d0/true_colors_in_vim_under_tmux/). Than you for great nvim.

For guys who'll face this issue add following lines to you .tmux.conf:

    set -g default-terminal 'screen-256color'
    set -ga terminal-overrides ',screen-256color:Tc'

**Comment by tim-phillips** [comment]
I had to do the following in my `.tmux.conf`:

```
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'
```

**Comment by nyngwang** [comment]
> I had to do the following in my `.tmux.conf`:
> 
> ```
> set -g terminal-overrides ',xterm-256color:Tc'
> set -g default-terminal "tmux-256color"
> set -as terminal-overrides ',xterm*:sitm=\E[3m'
> ```

Could you explain each lines? In my case I use Alacritty instead of Terminal.app(MacOS), then how should I modify these commands?

**Comment by harrisoncramer** [comment]
If I'm trying to use these settings with Alacritty it messes up what I'm typing in the terminal, e.g.
<img width="1034" alt="Screen Shot 2022-01-03 at 7 49 40 PM" src="https://user-images.githubusercontent.com/32515581/147995493-e3cf93c5-8a16-4a1b-a50d-f73cc9f33248.png">

**Comment by kessejones** [comment]
@harrisoncramer I had the same problem and solved it with it https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95

**Comment by harrisoncramer** [comment]
Thank you!! Worked like a charm.
