### ISSUE TITLE
Terminal not resized when its window is resized

### ISSUE THREAD

**Issue by bohrshaw** [neovim/neovim#7767]
- `nvim --version`: 0.2.3 dev 20171206

### Steps to reproduce:
```
nvim -u NORC
:exe 'term' | call chansend(&channel, "for i in {1..99}; do echo $i; done\n") | set bufhidden=hide | e _ | sb 1 | startinsert
```

### Actual behaviour
The terminal's cursor is hidden below its window.
My another `nvim` instance compiled at Sep 20 doesn't have this issue.
### Expected behaviour
The terminal should be resized properly.

**Comment by nateozem** [comment]
@bohrshaw Are you sure it works when you compiled the build around September 20? Because the command failed with error of `Unknown option: channel`. The commit I tested with is 68bc73b10.

**Comment by bohrshaw** [comment]
@nateozem The sub-command should fail but the terminal behavior then is right.

**Comment by GCorbel** [comment]
I have the same behavior.

**Comment by satiani** [comment]
I'm seeing similar behavior when I resize the window smaller than its original height.

**Comment by justinmk** [comment]
Hmm, still happens in some cases.

**Comment by bfredl** [comment]
@justinmk steps to reproduce?

**Comment by justinmk** [comment]
```
nvim -u NORC
:te 
:split 
5@:  " split five times
i    " enter terminal-mode in the top window
ls   " shell command that adds scrollback lines  
```

After these steps most of the terminal windows will have cursor position off-by-one from the end of buffer. Now continue with these steps:

```
:split
<c-w><c-j>
i    " off-by-one, cursor is one row below bottom of window
```

**Comment by bfredl** [comment]
@justinmk cannot reproduce. Maybe depends on height, what is `&lines` ?

**Comment by bfredl** [comment]
@justinmk Now can reproduce. I guess the terminal code does nothing to follow cursor when terminal is bigger than window. Maybe minimum size should preferred over maximum size, as suggested in #9551? This would be more similar to what tmux does (ideally with some fillchar for the border like tmux).

**Comment by justinmk** [comment]
@bfredl 	SGTM. The only purpose IMO of preferring max size is to hack around the "text truncation" effect #7303, and given that we haven't solved that, any choice that improves something, wins.

**Comment by bfredl** [comment]
Though @leonerd is working now/soon-ish on implementing reflow. Maybe we should wait a little on that before changing this.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8325 fixes this. I'll write a test for it then merge it.
