### ISSUE TITLE
CheckHealth miss activation of (tox or venv) created virtualenv

### ISSUE THREAD

**Issue by vlcinsky** [neovim/neovim#7770]
- `nvim --version`:
```
$ nvim --version
NVIM v0.2.3-313-gdee78a409
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-15964bbe-5389-4cd5-a2c0-6a618ae410cd

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"
```
- Vim (version: ) behaves differently? Did not test with vim, simplified my life by using only neovim.
- Operating system/version: Debian 9 Stretch
- Terminal name/version: 
```$ byobu --version
byobu version 5.112
tmux 2.3
```
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
Install pyenv, install python 3.6.3 into it, create pyenv virtualenv for neovim3 and neovim.

Use `.vimrc` as follows:
```
let g:python_host_prog = '/home/javl/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/home/javl/.pyenv/versions/neovim3/bin/python'
```
Create `tox.ini`:
```
[tox]
envlist = py36
skipsdist = True

[testenv]

```
and use it to create virtualenv:
```
$ tox
```
This creates virtualenv in `.tox/py36` directory. Activate it:
```
$ source .tox/py36/bin/activate
(py36)$
```
Running checkhealth:
```
nvim -u .vimrc -c checkhealth

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: pyenv: /home/javl/.pyenv/libexec/pyenv
  - INFO: pyenv root: /home/javl/.pyenv
  - INFO: Using: g:python_host_prog = "/home/javl/.pyenv/versions/neovim2/bin/python"
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654/5229
  - INFO: Executable: /home/javl/.pyenv/versions/neovim2/bin/python
  - INFO: Python2 version: 2.7.14
  - INFO: python-neovim version: 0.2.0
  - OK: Latest python-neovim is installed: 0.2.0

## Python 3 provider (optional)
  - INFO: pyenv: /home/javl/.pyenv/libexec/pyenv
  - INFO: pyenv root: /home/javl/.pyenv
  - INFO: Using: g:python3_host_prog = "/home/javl/.pyenv/versions/neovim3/bin/python"
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654/5229
  - INFO: Executable: /home/javl/.pyenv/versions/neovim3/bin/python
  - INFO: Python3 version: 3.6.3
  - INFO: python-neovim version: 0.2.0
  - OK: Latest python-neovim is installed: 0.2.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v9.3.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

```

### Actual behaviour
Despite the virtualenv from `.tox/py36` is activated, the `healthcheck` complains `$VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.`

### Expected behaviour

At least for python3 I would expect no complains about not activated virtual env.

Hint: The problem might be in the way I activate the virtualenv. I get the same problem even when I create the virtualenv using `$ python -m venv venv`. Anyway, from command line there are no problems (packages install, py.test suites run...).

**Comment by justinmk** [comment]
@vlcinsky Did you read http://vi.stackexchange.com/a/7654 (mentioned in ADVICE)?

>  from command line there are no problems (packages install, py.test suites run...).

The command line isn't the problem, see the explanation at http://vi.stackexchange.com/a/7654 . E.g. what does this report (from Nvim):

    :echo system('which python')

**Comment by justinmk** [comment]
@vlcinsky If you still think the warning is mistaken, can you check [this logic](https://github.com/neovim/neovim/blob/2851bb9effafda599e21e3b639e99c636ce70ba6/runtime/autoload/health/provider.vim#L376-L385) to see what conditions there apply to your case, and how can we adjust them?

**Comment by vlcinsky** [comment]
@justinmk I think, [the logic](https://github.com/neovim/neovim/blob/2851bb9effafda599e21e3b639e99c636ce70ba6/runtime/autoload/health/provider.vim#L376-L385) shall be corrected.

# Types of virtulalenvs: pyenv (global) and venv (local)
"Classical" python virtualenv as created by `$ python -m venv myvenv` or  by `tox` are what most people consider "virtualenv". It makes local python environment and the local means, it is typically located in directories local to given project or deployment and not into some globally share directory.

On the other hand, "pyenv virtualenv" combines the power of `pyenv` with creation of named python environments. Provided function is as with local virtualenvs but the differences are:
- managed using different commands
  - to activate: `$ pyenv activate <short_name>`
  - to deactivate `$ pyenv deactivate`
- they are installed into shared directory (typically `~/.pyenv/versions`)

# Proposed resolution
Great thing is, that even virtualenv activated via `pyenv activate` behaves the same as if it was ordinary virtualenv, at least the `$VIRTUAL_ENV` value is set properly.

From this point of view, we may skip the part of logic related to `pyenv` and use only the `$VIRTUAL_ENV` part.

# Crucial question
The healthcheck is trying to check, if python virtualenv is activated properly. The crucial question is: what does it really mean from neovim point of view?

My understanding is, that `:!which python` shall find the python from virtualenv as defined by `$VIRTUAL_ENV` variable.

I think, this python may also differ from the one, used by `:py` and `:py3` as these are the ones, where `neovim` package is installed.

# What to do next?
Let's first agree on correct answer to the crucial question above.

As I am not proficient in vim-script and use appimage installed neovim, it would take me longer to create a pull request. On the other hand, I shall have no problem to install development version of neovim (using appimage) and test it.

**Comment by justinmk** [comment]
Yes, so what do these report in your case?

    :echo system('which python')
    :echo system('which python3')

**Comment by vlcinsky** [comment]
In both cases it prints path to python from local virtualenv created by tox
or 'python -m venv venv' what is what I consider proper result as I called
the 'activate' script from these dirs before starting neovim.

**Comment by justinmk** [comment]
Yes, but how can the check verify that it looks correct?

**Comment by vlcinsky** [comment]
One way can be to simplify existing code:

	if exists('$VIRTUAL_ENV')
	  if !empty(pyenv)
	    let pyenv_prefix = resolve(s:trim(s:system([pyenv, 'prefix'])))
	    if $VIRTUAL_ENV != pyenv_prefix
	      let virtualenv_inactive = 1
	    endif
	  elseif !empty(pyname) && exepath(pyname) !~# '^'.$VIRTUAL_ENV.'/'
	    let virtualenv_inactive = 1
	  endif
	endif

into a test, completely ignoring any `pyenv` logic (untested code):

	if exists('$VIRTUAL_ENV')
	  if !empty(pyname) && exepath(pyname) !~# '^'.$VIRTUAL_ENV.'/'
	    let virtualenv_inactive = 1
	  endif
	endif

Alternative test could be to check, that full path to python interpreter starts with `$VIRTUAL_ENV`.

More precise alternative is to check, that directory of python interpreter is subdirectory of `$VIRTUAL_ENV`. It is possible that existing code does exactly that (I will have to look at vimscript at least quickly).

**Comment by justinmk** [comment]
> Alternative test could be to check, that full path to python interpreter starts with $VIRTUAL_ENV

That sounds good, and that's what `exepath(pyname) !~# '^'.$VIRTUAL_ENV.'/'` already does if I'm not mistaken.

So one last question, why does `pyenv prefix` not return the correct thing for your environment?

**Comment by vlcinsky** [comment]
Having the virtualenv activated (using `source .tox/py36/bin/activate`):

	$ which python
	/home/javl/sandbox/pytest_xfiles/.tox/py36/bin/python
	(py36) javl@T810:~/sandbox/pytest_xfiles$ pyenv prefix
	/home/javl/.pyenv/versions/3.6.3

The reason is simple, I do not use pyenv to manage virtualenvs (which I called "global" ones), but I use common python tools for it and these relate to what I called "local virtualenv").

I guess, the `pyenv prefix` test will work only for those, who use the pyenv globall virtualenvs.
