### ISSUE TITLE
Neovim FTBFS on Fedora

### ISSUE THREAD

**Issue by Dridi** [neovim/neovim#7774]
- `nvim --version`: master
- Vim (version: ) behaves differently? I don't know :)
- Operating system/version: Fedora 27

In order to make sure my problem wasn't fixed in master before opening #7772 I tried to build neovim from source and initially failed. The one dependency I couldn't get is `lua-bit` so I took a look at the Fedora package and found 2 patches for Neovim (I didn't need the second one on master).

https://src.fedoraproject.org/rpms/neovim/blob/master/f/neovim-0.1.7-bitop.patch

I'm not CMake-savvy and don't have much experience with Lua, so I don't know how/whether you could look for `lua-bit` and fall back to `lua-bit32` (especially on the Lua side). I couldn't find a reference to this problem in your issue tracker, even though the neovim maintainer from Fedora should have reported that. Ironically the syntax plugin for Lua is aware of bit32 ;)

```
$ git grep -l bit32
runtime/syntax/lua.vim
```

I tried to build without the bundled third-party software and got the following warning:

```
$ cmake -DUSE_BUNDLED=NO -DUSE_BUNDLED_DEPS=NO ..
[...]
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_BUNDLED
    USE_BUNDLED_DEPS
```

Anyway, even without setting the variable CMake would complain about the couple dependencies I was missing (and in particular `lua-bit` before applying the patch). Maybe it's just me not understanding this part of the README.

Then when I tried to run `nvim` from the build tree I got this error message:

```
$ build/bin/nvim 
Error detected while processing function plug#end:
line   74:
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
Press ENTER or type command to continue^C
```

I could trick it with a symbolic link, and the error was gone:

```
$ sudo ln -s $PWD/runtime /usr/local/share/nvim
```

I'm wondering whether I missed something in the wiki to successfully run a build of neovim without installing it. Maybe sourcing a shell script to tweak the environment before running `build/bin/nvim`?

Thanks!

**Comment by Dridi** [comment]
The error message without my `vimrc`:

```
$ build/bin/nvim -u NORC
E484: Can't open file /usr/local/share/nvim/syntax/syntax.vim
Press ENTER or type command to continue^C
```

Also disappears when I create the symbolic link.

**Comment by justinmk** [comment]
> run a build of neovim without installing it

    VIMRUNTIME=runtime build/bin/nvim

**Comment by Dridi** [comment]
Check. Thanks @justinmk!

**Comment by justinmk** [comment]
So what is this issue about otherwise ?

**Comment by Dridi** [comment]
Sorry, the main issue is that I need to patch the `lua-bit` parts otherwise it won't build against system dependencies. Looking at the RPM spec for Fedora it's likely also the case on CentOS.

**Comment by justinmk** [comment]
If there's a change we can make to improve that, please send a PR. Otherwise not much to say.

**Comment by justinmk** [comment]
My guess is you're building with lua 5.2. We require lua 5.1 or luajit.

**Comment by Dridi** [comment]
Actually, lua 5.3 and after a quick look I found that `bit32` was introduced in 5.2 and back-ported to 5.1:

http://lua-users.org/wiki/BitwiseOperators

However since this is a back-port, it won't work with 5.1 unless you have a recent-enough release (which arguably one should have). And `luajit` doesn't seem to have the `bit32` package yet.

I'll try to submit a pull request, the fallback I was suggesting is indeed possible:

```
local bit = bit32
if (bit == nil) then
    bit = require 'bit'
end
```

Feel free to make this change if you think it doesn't need a pull request and an extensive review: tested successfully on Fedora 27 :)

```
$ cat test.lua 
local bit = bit32
if (bit == nil) then
    bit = require 'bit'
end
print("bit32:", bit32)
print("bit:", bit)
$ lua test.lua
bit32:	table: 0x562447c7afd0
bit:	table: 0x562447c7afd0
$ luajit test.lua
bit32:	nil
bit:	table: 0x41004270
```

Now I'll need a closer look at the CMake build to tolerate the lack of `bit` when `bit32` is available.

**Comment by justinmk** [comment]
I think building with 5.2/5.3 in general is just a bad idea. Even if it appears to work, it could lead to problems later, those are different languages (with breaking changes) than Lua 5.1.
