### ISSUE TITLE
in iterm2 cursor style not restore

### ISSUE THREAD

**Issue by gatspy** [neovim/neovim#7775]
## Environment Information
- OS: osx `10.12.6`
- neovim version: `NVIM v0.2.2`
- iterm2: `3.1.5`

now, iterm2 used curor style is `underline blink`,when exit `nvim`,  cursor style changed to 
`block blink`, how restore cursor style?
and another question: when open `nvim`, how set cursor shape to `underline blink`?
I try to set `au VimLeave * set guicursor = a: ver25-blinkon10`, but no effect.

**Comment by justinmk** [comment]
au VimLeave * set guicursor=a:ver25-blinkon10

That would make a vertical cursor. Use "hor" for horizontal (underline).

    :au VimLeave * set guicursor=a:hor25-blinkon10

This is documented at `:help 'guicursor'`.
