### ISSUE TITLE
TabClosed: <afile> not expanded to tab page number with :bd

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#7781]
Given `t-tabclose-non-current.vim`:

```vim
let s:closed = []
autocmd TabClosed * let s:closed += [expand('<afile>')]
" Not displayed.
autocmd TabClosed 2 echom 'TabClosed: 2'

tabnew
file bufname
let buf1 = bufnr('')

tabnew
tabnew

tabclose
normal! 1gt
3tabclose

exe 'silent! bd' buf1

" Should be [4, 3, 2], but is [4, 3, ''].
" For some reason it is not 'bufname' here, but with Vader, where I've noticed
" this issue.
echom string(s:closed)
```

Running `nvim -u t-tabclose-non-current.vim` displays:
```
"bufname" [Not edited] --No lines in buffer--
['4', '3', '']
```

According to `:h TabClosed` `<afile>` should expand to the tab page number:

> TabClosed			After closing a tab page. <afile> can be used
				for the tab page number.

This appears to be a Neovim specific feature, and seems to not work when the tab page is closed due to `:bd`.

- `nvim --version`: v0.2.3-324-g061b942dc

**Comment by blueyed** [comment]
TabClosed seems to have been added first in Neovim (v0.1.0~599^2(3ffc5d81c)).

**Comment by fmoralesc** [comment]
@blueyed I must have missed that case when I worked on that. It seems that the code for retrieving the tab number might execute too late in that case, but I'm not sure where it should run instead.

Anyway, it made sense to me to use `<afile>` for this purpose, and I think when I sent the original patches to Bram (along with `TabNew` and `TabNewEntered`) it did that too. It seems that Vim did not follow that design.

**Comment by blueyed** [comment]
@fmoralesc 
Thanks.
See #7782 for where it is needed - it was added there in v0.2.0~328^2(2b56cf099) by @lonerover.

**Comment by blueyed** [comment]
As for Vim: it's sad that it was not adopted.
There seems to be a general problem with the current behavior in both Vim and Neovim, which is that there is only a single autocommand even if more than one tab page was closed (via this code path).

**Comment by fmoralesc** [comment]
The new PR LGTM. 

> there is only a single autocommand even if more than one tab page was closed

Well, that is a larger oversight , I admit :p 

(Btw, why the interest? What are you using `TabClosed` for?)

**Comment by blueyed** [comment]
@fmoralesc 
I've looked into while debugging an issue with Vader, where its workbench tab gets closed for some reason.  I've used `TabClosed` for debugging, and plan to use it for an assertion in the future probably.

As for this PR: I will add some test(s) to `test/functional/autocmd/tabclose_spec.lua`.
