### ISSUE TITLE
man.vim: write tests

### ISSUE THREAD

**Issue by nhooyr** [neovim/neovim#7785]
Something to do in the future.

**Comment by AMaini503** [comment]
I see this is a good first issue. Can you guide me how can I begin with this ?

**Comment by KillTheMule** [comment]
The first thing you'll need to do is learn how to run individual functional test files (see the wiki), and then produce a new one, that has a test that does nothing (start with an already existing file and trim it down as far as possible). Then you can start making that test do something, for reference see the tests in `test/functional/ui`, which should contain most of what you need. For further support join the gitter channel, or open a PR with your progress.

**Comment by geekodour** [comment]
@AMaini503 are you working on this?

**Comment by prakashdanish** [comment]
@AMaini503 I'm starting to work on this due to inactivity. @geekodour hope it's ok.

**Comment by ashis0013** [comment]
I don't understand the issue. Please help me out

**Comment by nhooyr** [comment]
@ashis0013 This issue is about writing tests for the man.vim plugin used to view man pages. See `:help man.vim`. What specifically do you not understand?

**Comment by justinmk** [comment]
This issue is attracting a lot of question and no contributions.
