### ISSUE TITLE
Escape key is not registered if typing very fast

### ISSUE THREAD

**Issue by dylan-chong** [neovim/neovim#7789]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/config -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-94210-1gi9ez6/neovim-0.2.2/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"
```

- Vim (version: ) behaves differently?
- Operating system/version: mac 10.13.2
- Terminal name/version: iterm 2 3.0.8
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

1. Enter insert mode
2. Very quickly press `<esc>a` (on my computer the keys must be pressed within 10-20ms of each other)

### Actual behaviour

However pressing the `a` key prevents the escape key from being registered, so an `a` is type into the buffer.

This is rather annoying as I am using some dictation software to type out sequences of keys. That types out the sequence of keys very quickly so this bug is a problem when trying to type out the escape key followed by some other keys.

### Expected behaviour

Step two should (if this bug was fixed) leave insert mode and then go back into insert mode - `a` should not be typed into the buffer.

**Comment by justinmk** [comment]
Are you using tmux? Try `:checkhealth`, and read the "tmux" section of the report.

Explained in the FAQ: https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
