### ISSUE TITLE
Comparing float values in Windows fail

### ISSUE THREAD

**Issue by lambdalisue** [neovim/neovim#7793]
Float comparison on Windows fail. It is ok on macOS and Vim.

- `nvim --version`: v0.2.2 (installed with chocolatey)
- Vim (version: from v7.3 to HEAD) behaves differently? Yes
- Operating system/version: Windows
- Terminal name/version: PowerShell
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC test.vim
:source %
```

```
" test.vim
function! s:round(float, digits) abort
  let n = pow(10.0, a:digits)
  return round(a:float * n) / n
endfunction

echo s:round(123, -2)
echo s:round(123, -2) == 100.0
echo str2float(string(s:round(123, -2))) == 100.0
```

### Actual behaviour
```
100.0
0
1
```

### Expected behaviour
```
100.0
1
1
```

### Version

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by justinmk** [comment]
Look like you are using the 32bit version. Does this also happen for the 64bit Windows build? Or vice versa?

> Vim (version: from v7.4 to HEAD) 

32bit or 64bit?

**Comment by lambdalisue** [comment]
> Look like you are using the 32bit version. Does this also happen for the 64bit Windows build? Or vice versa?

OK. I'll try (I'm not familiar with Windows so I have to find a way to install 64bit build)
 
> 32bit or 64bit?

Not sure but prob both on Linux, 64 bit on Windows.

The corresponding test exists on [vim-jp/vital.vim](https://github.com/vim-jp/vital.vim) since 2015 (https://github.com/vim-jp/vital.vim/commit/7b79415403e720377ff594561d0877a5c2e84a5b)
At that time, Vim was 7.3 and 32 bit I think (https://travis-ci.org/vim-jp/vital.vim/jobs/59508346).

Additionally it was/is tested with 64-bit Vim 7.3, 7.4 and 8.0 on Windows (https://ci.appveyor.com/project/vim-jp/vital-vim/build/12, https://ci.appveyor.com/project/vim-jp/vital-vim/branch/master)

**Comment by lambdalisue** [comment]
It seems my nvim on Windows is 64 bit?

```
nvim --cmd 'echo has("win32") | echo has("win64")' --cmd 'quit'
1
1
```

Right?

**Comment by lambdalisue** [comment]
I download 32/64 bit Vim and Neovim from

https://github.com/vim/vim-win32-installer/releases
https://github.com/neovim/neovim/wiki/Installing-Neovim

And source the script above for each combination.

```
Offical Vim (cmd.exe)           8.0.1427 32bit OK
Offical Vim (powershell.exe)    8.0.1427 32bit OK
Offical GVim                    8.0.1427 32bit OK

Offical Vim (cmd.exe)           8.0.1427 64bit OK
Offical Vim (powershell.exe)    8.0.1427 64bit OK
Offical GVim                    8.0.1427 64bit OK

nvim (cmd.exe)                  0.2.2    32bit OK
nvim (powershell.exe)           0.2.2    32bit OK
nvim-qt                         0.2.2    32bit OK

nvim (cmd.exe)                  0.2.2    64bit No
nvim (powershell.exe)           0.2.2    64bit No
nvim-qt                         0.2.2    64bit No
```

It seems 64-bit support is broken on Neovim.

**Comment by justinmk** [comment]
@jamessan is this expected?

**Comment by lambdalisue** [comment]
Additionally, it is a bit strange but Vim 8.0.0027 was OK. I didn't investigate it deeply so not sure exact version but it seems Vim 8.0.0028 ~ Vim 8.0.1426 has that issue and Neovim as well.

**Comment by justinmk** [comment]
Most likely it's just a missing patch from Vim. Thanks for investigating!

**Comment by lambdalisue** [comment]
Thanks. I don't have building env on Windows so bisecting is really hard for me so could you give me which patch introduce the bug and solve the bug once found?

**Comment by justinmk** [comment]
> ### Expected behaviour
> ```
> 100.0
> 1
> 1
> ```

Seems to be fixed. Tested Nvim 0.5 6f073ccbf
