### ISSUE TITLE
Prevent neovim from placing cursor at the command line

### ISSUE THREAD

**Issue by damage220** [neovim/neovim#7799]
### Environment
- `nvim --version`: NVIM v0.2.3-dev
- Vim (version: ) behaves differently? Yes, I have `expected behavior` in VIM 8.0
- Operating system/version: Ubuntu 16.04
- Terminal name/version: xfce4-terminal 0.6.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC ~/.vimrc
:w
```

### Actual behaviour
When saving a file the cursor is placed at the command line. Sometimes it happens when enter insert mode with `set showmode`, the cursor is placed after "-- INSERT --". Sometimes when text is printed using echo. This makes cursor to blink. For previews, please visit [SO](https://stackoverflow.com/questions/47978751/how-to-prevent-neovim-from-placing-cursor-at-the-last-line).

### Expected behaviour
The cursor stay at the same position.

**Comment by justinmk** [comment]
Looks like your terminal is very slow. All terminal apps place the cursor to draw on the screen, the fact that you can see it sometimes is only cosmetic.

We did make significant changes to improve TUI performance. https://github.com/neovim/neovim/pull/6366 might help further.

**Comment by damage220** [comment]
So what terminal should I use? I have currently installed several terminals. There is no difference which one I use (I tested in Teminology, xfce4-terminal, gnome-terminal, Konsole, xterm).

#6366 sounds tempting but does it mean I have to compile it manually? Why is this PR not merged yet?

**Comment by justinmk** [comment]
Is your entire system slow?

**Comment by justinmk** [comment]
> Why is this PR not merged yet?

Read the discussion there.

**Comment by damage220** [comment]
> Is your entire system slow?
I do not think so. As I mentioned above I have no issue in vim.

**Comment by wsdjeg** [comment]
you need reproduce it with `nvim -u NONE`

**Comment by damage220** [comment]
Of course I did it with `nvim -u NONE` too. I have tested yesterday with files stored on my SSD and there is no problem but still the fact that my HDD response time is larger than SSD do not cancel the fact that in vim I have no issue. Also cursor could be placed after each echoed text.

Correct me if I got it wrong. The cursor for each command is placed at the command line and if command takes some time the blink could be possible.

**Comment by justinmk** [comment]
> the fact that my HDD response time is larger than SSD does not cancel the fact that in vim I have no issue. 

Vim doesn't fsync in as many cases as Nvim. Try `:set nofsync` if you want.

So yeah, this is indeed system slowness.

**Comment by bfredl** [comment]
I wouldn't expect a slow terminal to only cause the cursor to "linger" in the wrong like in the SO gifs. We might lack an `ui_flush()`, or even have one too much: `ui_flush()` must not be called after popupmnu is drawn but before `setcursor()` is called, which would explain the visible behaviour. This could be investigated using `redraw_debug` in the lua tests.

**Comment by damage220** [comment]
> Vim doesn't fsync in as many cases as Nvim. Try :set nofsync if you want.

Well, the problem is gone. I am not sure this is what I want since this option is pretty useful. I guess I should use SSD for my project files instead (I do not know why I did not do this before).

What about SO gif (the last one), the problem is the slow algorithm which takes 100ms for each keystroke. But why the cursor should be placed after popup menu? For blocking code I would except no reaction for new key presses (or adding to typeahead) until the code be executed. Keep in mind, I have no idea how terminal emulators actually work. Again, this is not an issue since the algorithm should be rewritten anyway, it is just an illustration that neovim has different behavior on how the cursor works since I have no problem with vim for echoed text or popupmenu. But have another tui issues which make me switch to neovim)
