### ISSUE TITLE
Support XDG directory specification

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#78]
From #26, but I am talking not only about configuration files.

1. Configuration:

    1. populate runtimepath from `XDG_CONFIG_DIRS`, `XDG_DATA_DIRS`, `XDG_DATA_HOME` and `XDG_CONFIG_HOME` (and `$VIMRUNTIME` as well):

        $XDG_CONFIG_HOME/nvim
        $xdg_config_dir/nvim (for each directory in $XDG_CONFIG_DIRS)
        $XDG_DATA_HOME/nvim
        $xdg_data_dir/nvim/site (for each directory in $XDG_DATA_DIRS)
        $VIMRUNTIME (looks something like /usr/share/nvim/runtime)
        $xdg_data_dir/nvim/site/after (for each directory in $XDG_DATA_DIRS, reverse order)
        $XDG_DATA_HOME/nvim
        $xdg_config_dir/nvim/after (for each directory in $XDG_CONFIG_DIRS, reverse order)
        $XDG_CONFIG_HOME/nvim/after

    2. `init.vim` should be taken from the first directory in `$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS` where it was found (e.g. first from `~/.config/nvim/init.vim`, then from `/etc/xdg/nvim/init.vim`).

2. Default `&directory` option (it holds swap files there) to `$XDG_DATA_HOME/nvim/swap//`.
3. Default `&backupdir` to `.,$XDG_DATA_HOME/nvim/backup`.
4. Default `&undodir` to `$XDG_DATA_HOME/nvim/undo//`.
5. Default ShaDa location is `$XDG_DATA_HOME/nvim/shada/main.shada`.
6. Default `&viewdir` to `$XDG_DATA_HOME/nvim/view`.

OS defaults:

1. On \*nix operating systems default XDG_\* variables according [XDG base directory specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).
2. On windows default XDG_CONFIG_HOME and XDG_DATA_HOME to `%APPDATA%`, XDG_CACHE_HOME and XDG_RUNTIME_DIR to `%TEMP%` (just in case) and XDG_CONFIG_DIRS to empty (as VIMRUNTIME is handled separately).

Some other notes:

1. In any case respect existing values on any operating system.
2. Entry separator is a colon on any system. It is expected that path separator is a forward slash inside these variables on systems where path separator is a colon.
3. On startup absent environment variables (only XDG_CONFIG_HOME and XDG_DATA_HOME) should be set to their default values for use in scripts. Code that sets default options this will not have to handle this on its own.
4. On startup invalid values (XDG base directory specification says that paths *must* be absolute, relative paths are to be ignored) are replaced with default ones.
5. Code that sets those variables should live in `src/nvim/os/env.c`, alongside with restored `init_homedir` (which currently lives in `misc1.c` and lacks code for Windows).

Note some renamings: `vim74` to `7.4`, `vimfiles` to `site-contrib`, `.vimrc` to `init.vim`. Reasoning behind this: to avoid duplicating data. We already know this directory contains files for neovim since it is named `/usr/share/nvim`, why should this information be repeated in the subdirectory? Also it is hard to tell from the directory name what is the difference in `vim74` and `vimfiles` contents, but it is easy for `7.4` and `site-contrib` (names are taken from `/usr/share/zsh`). Extension designates file type, so no need to remove it, it is for separate purpose.

**Update**: Renamed `rc.vim` to `startup.vim`. Reasoning: this way config file name resembles its purpose. See also #235.

**Update 2**:
- Renamed `neovim` to `nvim` as it is new convention.
- Moved `&directory`, `&backupdir` and `&undodir` defaults to `$XDG_DATA_HOME`.
- Made `&undodir` use trailing `//` as well.
- Removed `~/tmp`/`$TEMP`/etc defaults from `&backupdir` (backups in `%TEMP%`?!).
- Removed current directory from `&undodir` default. If `&backupdir` was supporting trailing `//` I would happily remove current directory from there as well: nobody likes spamming working directory with files that are needed only by vim and hardly ever by user.

**Update 3**: All options sharing the same `$XDG_DATA_HOME/nvim` directory were supplied with distinct subpaths.

**Update 4**: Added OS defaults and notes.

**Update 5**: Renamed `startup.vim` to `init.vim`.

**Update 6**: Added default for ShaDa.

**Update 7**: Added default for viewdir.

**Update 8**: Updated `init.vim` search path, as discussed in some of the PRs.

**Comment by spaghetti2514** [comment]
Is there anything going on with this anymore?

>Vim itself will be adding support for this pretty soon, so we'll probably just merge that.

This was 8 months ago, and I still can't find any reports or active plans for vim to add support for the XDG spec.
I for one really want to see Neovim have this, and it'd be a shame if it lacks it for too much longer just because vim is dragging its feet.

>XDG is irrelevant to Windows and OS X

As an OS X user who has the XDG environment variables defined and frequently uses several utilities that correctly support the XDG spec, I have to disagree and would like to say :+1: for XDG over ~/Library/ on OS X

**Comment by justinmk** [comment]
@spaghetti2514 This feature is a time-sink that has lower priority than other things we are working on right now. I would still like to see it in the first release, but really, it may not make it in. There are simply other things that need to be done right now.

**Comment by shmerl** [comment]
Follow the discussion, I didn't quite get the result. Does the current neovim master supprot XDG config spec or not? I'd prefer not to clutter my home directory with any config files.

**Comment by justinmk** [comment]
Not yet.

**Comment by mseeber** [comment]
I just wondered after reading...
shouldn't the swp files go to $XDG_CACHE_HOME/nvim/swap/

instead of $XDG_DATA_HOME/nvim/swap//

I guess the swp files do qualify as "user-specific non-essential (cached) data" as described in the spec.

**Comment by ZyX-I** [comment]
@mseeber Reading what? It was my initial suggestion and I was then convinced that XDG_DATA_HOME is better, see @kopischke comment.

**Comment by mseeber** [comment]
Ah, I found it. OK, with that comment, I understand the point. Sorry for the noise.

**Comment by Yamakaky** [comment]
The /tmp/nvim* socket should be moved to $XDG_RUNTIME_DIR (/run/user/1000 for me).

**Comment by mrak** [comment]
You have to be somewhat careful with using `XDG_RUNTIME_DIR` for sockets. If you have a tmux server with neovim running outside of a user session the socket will be destroyed when the user detaches and logs out.

**Comment by Yamakaky** [comment]
WIP !
https://github.com/Yamakaky/neovim/commit/43a3abceb95c6e97842cf4d8258a75fbf7b2eba7
https://github.com/Yamakaky/neovim/commit/5bfa1616f2d9feacc82fbf93ff2307a596e1e998
RFC !

**Comment by jck** [comment]
@Yamakaky Please create a PR for XDG compliance so that we can try to get it merged ASAP.

**Comment by Yamakaky** [comment]
In fact, I wait for #2578 to be merged.

**Comment by nagisa** [comment]
> You have to be somewhat careful with using XDG_RUNTIME_DIR for sockets. If you have a tmux server with neovim running outside of a user session the socket will be destroyed when the user detaches and logs out.

Sounds like something tmux should be dealing with rather than everybody who could get their sockets destroyed after detach+log out.

**Comment by mrak** [comment]
I used tmux as an example situation that is common for remote work.

The point I wanted to make is that XDG_RUNTIME_DIR should only be used by programs bound to a login session. This is why applications like tmux put their sockets under /tmp or TMPDIR instead

**Comment by nagisa** [comment]
tmux (and similar tools) could as well just set $XDG_RUNTIME_DIR to `/tmp` or any other directory as well. There’s tons of applications that already use $XDG_RUNTIME_DIR out there and I believe adding a few more might finally make tmux (and similar tools) set/not inherit some environment variables to become more independent of user session.

**Comment by tomprince** [comment]
Regarding OSX/Windows equivalents of XDG, [this](https://github.com/ActiveState/appdirs/blob/master/appdirs.py) python package has some equivalents, along with rationales for each.

**Comment by woegjiub** [comment]
Putting OS X dotfiles in that location is a bad idea; it's mode for pure-GUI stuff.

Unixy tools use dotfiles in the home directory, and in .config just like on Linux (see: .ssh, .emacs.d, etc)

It makes it much easier to use one set of dotfiles for Linux and OS X; you just need to keep .config in version control once everyone's onboard the XDG bandwagon.

**Comment by jck** [comment]
@justinmk I think that the decision to move this from 0.1 to 0.3 milestone is wrong.
Lots of people might start using nvim after the first public release and we would be stuck with unnecessary backward compatibility baggage for a while.

**Comment by spaghetti2514** [comment]
I have to agree with @jck. This is a relatively small change code-wise and benefits from being made sooner rather than later

**Comment by Pyrohh** [comment]
@jck

> Lots of people might start using nvim after the first public release and we would be stuck with unnecessary backward compatibility baggage for a while

Would we? I thought the whole point of having all these milestone versions being pre-1.0 was to indicate a lack of backwards compatibility (semantic versioning).

**Comment by vially** [comment]
> I thought the whole point of having all these milestone versions being pre-1.0 was to indicate a lack of backwards compatibility

I thought the same about Atom and then, while it was still in beta, they came out and [said](https://github.com/atom/atom/issues/2199#issuecomment-72920669):
> changing the default location at this point is unlikely given how many Atom installs are already out there

I really hope neovim doesn't follow the same path.

**Comment by justinmk** [comment]
@Pyrohh correct. 

>  This is a relatively small change code-wise 

Not sure we can make that assumption. Anyways, getting the details right will need careful attention. Reaching a goal means choosing priorities. This particular issue is an example of something that should _not_ push back a general release.

**Comment by Earnestly** [comment]
If you're making general releases then you should probably get the defaults
down beforehand.  Sadly humans control semver notation, you will be just adding
needless legacy requirements and I fear you won't have the courge to break
compatability even though it's pre 1.0.  This has happened to many projects and
history usually repeats itself.

**Comment by spaghetti2514** [comment]
@justinmk 
>Not sure we can make that assumption

Can't we? Isn't the code already written and waiting for a PR ala https://github.com/Yamakaky/neovim/commit/f372e5bbc08b759bf6f41535580e8e2dbb9b45c1?
Even if not, I think it's pretty fair to assume that any decent implementation of *changing the default location of a config file* won't require a particularly large amount of code.

**Comment by bfredl** [comment]
> Lots of people might start using nvim after the first public release and we would be stuck with unnecessary backward compatibility baggage for a while.

Remember that the question of "backwards compatibility", in the cases where it is relevant, also includes compatibility with _vim_ No matter if/when we do this in `0.1` or `0.2` or later, someone moving (or trying out) vim 7.4 -> nvim 0.1 -> nvim 0.2 -> ... will experience the breaking change somewhere ( if it ends up being breaking)

**Comment by justinmk** [comment]
> the code already written and waiting for a PR ala Yamakaky@f372e5b?

Does that meet all of the criteria specified in the top post of this issue?https://github.com/neovim/neovim/issues/78#issue-28120804

> changing the default location of a config file won't require a particularly large amount of code.

Even changing the default `'encoding'` had surprising corner cases. I'm speechless that anyone would hop onto a thread and just offer unsupported opinions like this.

**Comment by mrak** [comment]
I, too, would like to see something like this implemented as _early as possible_, while not intending that it hold back a release.

Neovim has had so much hard work and great improvements made that I'd love to see get more traction with a public release. I'm a huge proponent of the XDG style of file organization, but I can content myself with using `VIMINIT` and some `nvimrc` settings to emulate the behavior for now.

**Comment by Yamakaky** [comment]
My code isn't waiting for a PR, I was waiting for #2578 to be merged. I will restart my changes from scratch, including this #2578.

**Comment by Yamakaky** [comment]
I pushed some of the changes.
https://github.com/Yamakaky/neovim/tree/xdg-support

**Comment by jck** [comment]
@Yamakaky can you create the PR now?

**Comment by Yamakaky** [comment]
Yes, sorry. With the holidays, I forgot.

**Comment by Yamakaky** [comment]
Done : https://github.com/neovim/neovim/pull/3120

**Comment by ZyX-I** [comment]
Updated 1.i suggestion.

**Comment by Yamakaky** [comment]
Why not execute init.vim in &runtimepath in reverse order ? Currently, SYS_VIMRC_FILE then the first USR_VIMRC_FILE* found are executed. Executind all the init.vim in &runtimepath would be more flexible.

**Comment by ZyX-I** [comment]
Yes, this is logical. Problem is that `init.vim` usually *modifies &runtimepath* (e.g. by `pathogen#infect`, `vam#ActivateAddons` or by directly modifying `&runtimepath`), so executing all of them is not doable.

**Comment by justinmk** [comment]
@ZyX-I `1.ii` mentions `~/.config/nvim/startup.vim`, should it be `~/.config/nvim/init.vim` ?

**Comment by ZyX-I** [comment]
@justinmk Yes, it should.

**Comment by ZyX-I** [comment]
Added ShaDa file location. Strange, but I did not mentioned viminfo before.

**Comment by ZyX-I** [comment]
**Update 8**: Updated `init.vim` search path, as discussed in some of the PRs.
