### ISSUE TITLE
API: nvim_command('stopinsert') doesn't work in terminal buffer

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#7807]
- `nvim --version`: NVIM v0.2.3-369-g09b9f9b7c
- Operating system/version: Linux 4.12.5-gentoo
- Terminal name/version: rxvt-unicode (urxvt) v9.21
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
Just run `nvim -u init.vim term://bash -c startinsert` with the following vimrc:
```sh
call execute('!(sleep 2; echo -ne "import neovim\\nn=neovim.attach(\"socket\", path=\"' . $NVIM_LISTEN_ADDRESS . '\")\nn.command(\"stopinsert\")\nn.stop_loop()" | python3) &')
```

### Actual behaviour
Neovim doesn't leave insert mode. Using `normal <C-n><C-\>` instead of `stopinsert` throws an exception with the following message:
```
 neovim.api.nvim.NvimError: b"Vim(normal):Can't re-enter normal mode from terminal mode"
```

This looks like a bug to me but if it isn't maybe the fact that you can't use `stopinsert` through RPC should be added to `stopinsert`'s doc?

**Comment by justinmk** [comment]
`:normal` can't be used in a terminal buffer. But `:stopinsert` should work. There's no such restriction for RPC in general.
