### ISSUE TITLE
tests: stderr output contains `cp` noise

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#7811]
Travis build

```
-- Output to stderr:
cp: cannot stat â€˜/home/travis/build/neovim/neovim/Xtest-tmpdir/nvim-test-lua-682â€™: No such file or directory
cp: cannot stat â€˜/home/travis/build/neovim/neovim/Xtest-tmpdir/nvim-test-lua-682â€™: No such file or directory
```

AppVeyor build:

```
-- Output to stderr:
The system cannot find the path specified.
'cp' is not recognized as an internal or external command,
operable program or batch file.
'cp' is not recognized as an internal or external command,
operable program or batch file.
...
```

@ZyX-I looks like this is from 6b45dbca0429

**Comment by janlazo** [comment]
Is `cp` necessary? I used [copy](https://ss64.com/nt/copy.html) in https://github.com/neovim/neovim/pull/7412/files#diff-c242fd01cffb1bb154a84d682e3915b1R509

**Comment by justinmk** [comment]
I think maybe we can remove the line in question, just want to wait for @ZyX-I to confirm.

https://github.com/neovim/neovim/commit/6b45dbca0429c52cb70908497bc7a0fed9db2d8d#diff-d5922401566cf746bc7bb0f1a2bd58c1R40
