### ISSUE TITLE
Strange superscripted labels in tabline

### ISSUE THREAD

**Issue by nhynes** [neovim/neovim#7814]
- `nvim --version`: NVIM v0.2.3-384-g7c4bb23
- Operating system/version: x86_64-unknown-linux-gnu
- Terminal name/version: iTerm2/HEAD, tmux 2.1 
- `$TERM`: tmux-256color

### Unexpected behaviour

The superscripts to the left of the buffer names wasn't present before upgrading nvim to HEAD.

<img width="169" alt="screen shot 2018-01-05 at 12 33 47 pm" src="https://user-images.githubusercontent.com/2353785/34627469-78fd0228-f215-11e7-9298-270f75c65462.png">

I thought this might be with the airline plugin but this seems unrelated to their buffer_nr option.

### Steps to reproduce

```
" minimal_init.vim
call plug#begin('~/.config/nvim/plugged')
Plug 'vim-airline/vim-airline'
call plug#end()
let g:airline#extensions#tabline#enabled = 1

" optional, below. shows that numbers are not the actual buffer numbers
e buf1
e buf2
bp
bd
e buf3
```

**Comment by justinmk** [comment]
Can you bisect?

**Comment by chrisbra** [comment]
It is an airline issue. Those are the buffer_idx_mode. please read the [documentation](https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L712-L736)

**Comment by nhynes** [comment]
Thanks @chrisbra and @justinmk for the quick response and helpful solution!
