### ISSUE TITLE
Yanked visual block of text put into wrong place when clipboard=unnamed

### ISSUE THREAD

**Issue by invertigo** [neovim/neovim#7815]
- `nvim --version`: NVIM v0.2.1
- Vim (version: 8.0) behaves differently? Yes
- Operating system/version: Mac OS X 10.13.2
- Terminal name/version: iTerm2 3.1.5
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set clipboard=unnamed
```

Create a few columns of text
```
###
###
###
```

Go to the top of the document `gg`, visual-block-select `^v`, go to the bottom of the document `G`, yank the first column(`y`), and put it (`p`)
```gg<Ctrl-v>Gyp```

### Actual behaviour
```
#
#
#
###
###
###
```

### Expected behaviour
```
####
####
####
```

Unsetting the clipboard (`:set clipboard=`) returns nvim to the expected behaviour.

**Comment by justinmk** [comment]
What are the exact steps ?

**Comment by invertigo** [comment]
Updated description

**Comment by nimitbhardwaj** [comment]
Its working fine with me, `nvim --version`: `NVIM v0.2.3-703-g0f1bc5ddc`

**Comment by justinmk** [comment]
Depends on the clipboard backend (`:help provider`). Visual block requires a backend that supports custom text types.

Should work with `xclip` and `xsel`, see what `:checkhealth` says is being used.
