### ISSUE TITLE
how to fix the error :Reason: Incompatible library version: nvim requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

### ISSUE THREAD

**Issue by luofei614** [neovim/neovim#7818]
when run  nvim command , show the error:
dyld: Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /usr/local/bin/nvim
  Reason: Incompatible library version: nvim requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

**Comment by justinmk** [comment]
Where did you get the nvim build from? Also, please answer the things requested in the issue template.
