### ISSUE TITLE
Tutorial formatting problem?

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [neovim/neovim#7823]
- `nvim --version`: 0.2.1
- Operating system/version: macOS El Capitan
- Terminal name/version: macOS Terminal.app
- `$TERM`: xterm-256color

Please see screenshot and confirm that the `{normal}` markers should be displayed, _ie_ that they are not markup. Thank you.

![untitled](https://user-images.githubusercontent.com/2132260/34644890-c358a81a-f30d-11e7-8939-b86040498158.png)

**Comment by justinmk** [comment]
Not sure how you got 0.2.1, but you should definitely upgrade to at least 0.2.2. Assuming you are using homebrew:

```
brew update
brew upgrade neovim
```

`:Tutor` has had several fixes on master (0.2.3, unreleased), I think your issue is already fixed.

**Comment by glacambre** [comment]
@justinmk I can reproduce this issue with `nvim -u NORC` on `NVIM v0.2.3-394-g4fedad6c5` but I have to search for the string `Te` in order to have `{normal}` appear in the buffer.

**Comment by i-s-o-g-r-a-m** [comment]
@justinmk I got 0.2.1 through homebrew. I'm on 0.2.2 now though. I look forward to 0.2.3, thanks.

**Comment by fmoralesc** [comment]
@glacambre `{normal}` is usually concealed, but conceals are disabled when one is searching it seems.
 
@i-s-o-g-r-a-m This issue is indeed fixed in the latest patches for `:Tutor`.
