### ISSUE TITLE
Highlighting FIXME

### ISSUE THREAD

**Issue by fbruetting** [neovim/neovim#7824]
Would be cool if this could get highlighted just as TODO, maybe in a slightly different way (red would be cool). :)

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Comment by fbruetting** [comment]
Well, that works for TODO out of the box, so I have the feature request to do this for FIXME, too…? Because it just makes perfect sense.

**Comment by jamessan** [comment]
That's up to the maintainers of the individual syntax scripts. They're listed at the top of each file, if you'd like to propose such a change for the filetypes you use.

Assuming they agree, we'll get the changes as we regularly merge the running updates from Vim.
