### ISSUE TITLE
More flexible mappings

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#7827]
This might already exist but I can't figure it out. Suppose I want to do the following:
`inoremap <CR>`  `<C-R>='i` don't like CR'`<CR>`
but still have `<CR>`
 behave like usual when it is not invoked directly. That is any insert mode command that uses `<CR>` uses the original `<CR>`, except when invoked directly: the user that presses enter in insert mode gets: i don't like CR.

This is just an example. It would be nice to have even more flexibility of the following sort. Lets call such a mapping flexmap with the following properties:

flex[mode]map lhs rhs [exception]
where [exception] is a a comma separated list of  [mode] command strings in which the remapping lhs to rhs is allowed to take place.

For example in the example at the top the pseudocode is
`(nore)fleximap  <CR>  <C-R>='i don't like CR'<CR> <CR>`

**Comment by justinmk** [comment]
> any insert mode command

What do you mean by this, exactly. Please give an example.

**Comment by yashamon** [comment]
Sure, the following behavior is needed:
we have inoremapped `<CR>` to `<C-R>='i don't like CR'`<CR>`
but <C-R>='pinapples'`<CR>`  inserts pinapples at cursor, instead of composite of pinapples and i don't like CR.

**Comment by bfredl** [comment]
Doesn't it behave like that already? Also, `<expr>` mappings can already be used to define flexible/conditional mappings

**Comment by fmoralesc** [comment]
@bfredl I think `map` will work like that, since it maps in the command line as well (which I think `i<C-R>=` uses).

**Comment by bfredl** [comment]
Hmm, I thought that was `noremap!`, maybe I mixed up, but the requested behavior should be possible already

**Comment by fmoralesc** [comment]
Yeah, I meant the `map`/`noremap` mappings instead of `imap/inoremap` as in the issue description.

**Comment by bfredl** [comment]
Not sure I follow. I think `inoremap` as @yashamon mentioned already works as they want, and `noremap!` has the (here) unwanted behavior.  Mappings thus already are as flexible as they want at least for this example. How is plain `noremap` relevant?

**Comment by fmoralesc** [comment]
Sorry, I'm just causing confusion :p You are right, of course. I meant the *family* of maps for mapmode-i (imap/inoremap/inoremap!) vs maps for mapmode-ic (map/noremap/noremap!). I thought he wanted something akin to inoremap but which also worked as `noremap!` does (basically, a variant of inoremap, then), which as you point out, should be enough.

**Comment by justinmk** [comment]
I really don't understand what's being requested here, but I'll mention:

- `:set paste` prevents remapping if that's what you want. Set it temporarily, then un-set it with `:set nopaste`.
- `<expr>`, `:cnoremap`, `getcmdline()`, etc. allow you to go nuts with whatever other edge cases you want to support.

I don't see a compelling use-case here for inventing an entirely new mapping namespace.

In the future if you want to ask about _how_ to accomplish something, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/issues/992 and https://github.com/neovim/neovim/issues/3253

**Comment by yashamon** [comment]
Hi I just retested. The issue in my use case scenario was that <C-i> is apparently the same thing as <Tab>,
this is with -U norc, i have no idea why that is.
As i had <C-i>, <Tab>, and <CR> remappings I was getting some counterintuitive results, and seemed like noremap was not behaving as it should have been. But it seems like it does provided one is aware of this identification of <Tab>. So yes I am ok with you closing it.
