### ISSUE TITLE
:! does not show 2-byte characters

### ISSUE THREAD

**Issue by tjdoc** [neovim/neovim#7830]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? yes (VIM 7.4)
- Operating system/version: macOS 10.12.6
- Terminal name/version: iTerm2 / 3.1.5
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!echo "abc 한글 abc"
```

### Actual behaviour

2-byte characters are not shown. 

![screen shot 2018-01-09 at 2 03 50 pm](https://user-images.githubusercontent.com/5180801/34705742-10469882-f546-11e7-9d8e-316c80e85a9a.png)

### Expected behaviour

VIM correctly shows all characters

![screen shot 2018-01-09 at 2 04 18 pm](https://user-images.githubusercontent.com/5180801/34705743-106e8626-f546-11e7-911c-939bdc3fdb94.png)

**Comment by justinmk** [comment]
Try `:te` instead.

    :te echo "abc 한글 abc"

**Comment by tjdoc** [comment]
`:te` works as expected.

**Comment by bfredl** [comment]
Related: #1496

**Comment by bfredl** [comment]
The shell implementation should use `msg_puts` instead of feeding raw data to the screen. (as a quick fix until `:terminal` is connected). I marked it as TODO in #6618 but forgot about it...
