### ISSUE TITLE
win32yank stops working after using Nvim-Qt for a while

### ISSUE THREAD

**Issue by arnoudplantinga** [neovim/neovim#7831]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently?: Yes
- Operating system/version: Windows 10
- Terminal name/version: Nvim-Qt
- `$TERM`: -

After using Nvim-Qt for a while, I cannot use the * and + register anymore. Instead, I get the following error:

    clipboard: failed to execute: win32yank -i --crlf

When I restart Nvim-Qt, I can use the registers again.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/7377 has more hints. 

It's a very annoying issue, would be great if someone could look into it.
