### ISSUE TITLE
I have some problems with clipboard。

### ISSUE THREAD

**Issue by Dcryfm** [neovim/neovim#7834]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently?
- Operating system/version: elementary os 0.4.1
- Terminal name/version: elementary terminal
- `$TERM`:
Steps to reproduce using `nvim -u NORC`: yes

In visual mode, neither y nor Ctrl-c can update data in xsel, but when I select with mouse, whether y or Ctrl-c can update data in xsel.
My English is bad, if the description is not clear enough, please tell me.
thanks.

**Comment by justinmk** [comment]
Please check https://github.com/neovim/neovim/issues?q=is%3Aopen+is%3Aissue+label%3Aclipboard

I'm guessing your issue might be https://github.com/neovim/neovim/issues/2325

Otherwise, please read `:help clipboard` and run `:checkhealth`.
