### ISSUE TITLE
Statusline scrolls instead of redrawing when running inside byobu

### ISSUE THREAD

**Issue by rnorris7756** [neovim/neovim#7835]
- `nvim --version`:
```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-yDhEcn/neovim-0.2.2=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-yDhEcn/neovim-0.2.2/build/config -I/build/neovim-yDhEcn/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-yDhEcn/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-yDhEcn/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim and Neovim 0.2.0 do not display this behavior.
- Operating system/version: Ubuntu 17.04
- Terminal name/version: bash
- `$TERM`:

### Steps to reproduce: The following can be run on a regular Ubuntu 17.04 system, or in a docker container with `docker run -it ubuntu:17.04 "/bin/bash"`:

```
apt update && apt install -y software-properties-common byobu locales
add-apt-repository ppa:neovim-ppa/stable
apt update && apt install -y neovim
byobu
nvim -u NORC

```

### Actual behaviour

After nvim opens, the statusline in byobu scrolls up instead of updating in-place.

![nvim-bug-1](https://user-images.githubusercontent.com/879574/34738695-b21dabfe-f52e-11e7-9a73-1eabd7b7f8dc.png)

After exiting, the characters `qq` appear on the shell prompt.  Typing `clear` in the shell clears them, but they reappear after a couple seconds.  This persists until the shell session is terminated.

![nvim-bug-2](https://user-images.githubusercontent.com/879574/34738700-b7098f02-f52e-11e7-8c09-062b3e974ba3.png)

I observed this on multiple installs of Ubuntu 17.04.  It can be reproduced from a clean install, and inside an Ubuntu 17.04 docker container.  Observed when installing Neovim from source as well as the stable PPA.

### Expected behaviour

The statusline should update in-place as it does under vim and neovim 0.2.0.  Extra characters should not appear after exiting.

**Comment by justinmk** [comment]
`$TERM` is important in such bug reports. If it's really blank, well, Nvim has to guess. Seems that it guessed wrong. Please read `:help $TERM` and 
https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes
