### ISSUE TITLE
GuiLinespace of gui_shim.vim not accepting negative numbers

### ISSUE THREAD

**Issue by Leandros** [neovim/neovim#7845]
- `nvim --version`: v0.2.2
- Operating system/version: Windows 10 Version 1703 (OS Build 15063.540)
- Terminal name/version: nvim-qt.exe
- `$TERM`: xterm-256color

### Steps to reproduce

- Install the gui shims (github.com/equalsraf/neovim-gui-shim)
- Execute the following in nvim: `GuiLinespace -2`

### Actual behaviour

Linespace is changed to -2.

### Expected behaviour

Linespace stays at 0.

### Notes

Calling `call rpcnotify(0, 'Gui', 'Linespace', -2)` has the correct behavior, though.

**Comment by jamessan** [comment]
Why is this opened here instead of in neovim-qt's repo?

**Comment by jamessan** [comment]
This sounds like a request for enhancement to neovim-qt.  Nothing in the `GuiLinespace` [documentation](https://github.com/equalsraf/neovim-qt/blob/539522cf19633163f72a8c567960b06e133048da/src/gui/runtime/doc/nvim_gui_shim.txt#L43-L46) implies it can take negative numbers.

**Comment by Leandros** [comment]
I did not realize those were to separate projects. Will open it over there.
