### ISSUE TITLE
Keystrokes are sometimes echoed in the command line in normal mode

### ISSUE THREAD

**Issue by cespare** [neovim/neovim#7847]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/config -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/include
Compiled by brew@ElCapitan-2.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? Yes, vim (8.0) does not exhibit this issue.
- Operating system/version: OS X 10.11.5 (El Capitan)
- Terminal name/version: Terminal.app (2.6.1)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

* Run `nvim -u NORC somefile.txt`
* Scroll up and down by holding down `j` and `k`

### Actual behaviour

`j` and `k` occasionally flicker on the right-hand side of the command-line.

### Expected behaviour

Nothing appears in the command-line as I enter input in normal mode.

---

This happens with any input, and sometimes it's accompanied by a more annoying white cursor-like flash at the same location (this usually happens when I undo/redo changes with `u` and `^r`).

The problem is more visible and annoying in vimr, but since it also happens in terminal nvim I figure it's some neovim issue, not a vimr issue.

**Comment by cespare** [comment]
Here's a gif:

![nvim](https://user-images.githubusercontent.com/318501/34911583-4122a740-f882-11e7-9f15-26bace8618ef.gif)

It's such a brief flicker that the capture misses some of them, but this should show what I'm talking about.

**Comment by justinmk** [comment]
:set noshowcmd

**Comment by cespare** [comment]
@justinmk thanks! None of the stuff I could think to google told me about showcmd :(
