### ISSUE TITLE
[feature request] faster better syntax highlighting

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#7866]
Achieving certain syntax highlighting in Vim/NeoVim (f.e. nested languages) is very slow. For example, see [this issue](https://github.com/posva/vim-vue/issues/95).

That plugin does the following which seems to be the source of inevitable extreme sluggishness:

https://github.com/posva/vim-vue/blob/master/syntax/vue.vim#L27-L54

Other editors like Atom and VSCode seem to work great with Vue syntax, at least after searching I was not able to find issues of slowness regarding syntax highlight with Vue for those editors, while with the `vim-vue` plugin its very own README file warns about slowness.

**Comment by trusktr** [comment]
related: https://github.com/neovim/neovim/issues/614

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/719#issuecomment-353728782

> [tree-sitter](https://github.com/tree-sitter) (see also [video](https://youtu.be/a1rC79DHpmY)) looks like a viable option.

> - C lib with minimal dependencies
> - more momentum (and more grammars) than scintillua just by association with Atom editor
> - advanced features like incremental parsing and error recovery (not sure if scintillua has those)

**Comment by liujoey** [comment]
can't wait for this, is there any plan or progress so far?
