### ISSUE TITLE
Git Bash opens in a new window on Windows 10

### ISSUE THREAD

**Issue by dustinboston** [neovim/neovim#7870]
nvim: 0.2.2 (running nvim-qt)
vim: 8.0
os: Windows 10

I understand that you can specify what terminal you can use with `:e term://<terminal>`. Using this approach I have been able to use the Windows Subsystem for Linux (`:e term://bash`) and Powershell (`:e term://powershell`). But when I run `:e term://git-bash.exe`, Git Bash opens in a window outside of NeoVim. I can't find documentation regarding Git Bash and NeoVim, specifically. Am I doing something wrong?

**Comment by justinmk** [comment]
You would need to find out what arguments `git-bash.exe` wants.  There's nothing special about how Nvim invokes the process.

For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks!
