### ISSUE TITLE
man.vim: no completions with ":vertical Man acc<Tab>"

### ISSUE THREAD

**Issue by oceans112** [neovim/neovim#7872]
- `nvim --version`: NVIM v0.2.2
- Operating system/version: Archlinux

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:vertical Man <Tab>
```
### Actual behaviour
No completion whatsoever.
### Expected behaviour
The same in 
```
:Man <Tab>
```
With the standalone version of the plugin, I was able to
nnoremap K :Vnman <c-r><c-w>
and have vertical split and autocompletion on the command line (also for the page section).

**Comment by justinmk** [comment]
This is a limitation of Vim.

**Comment by oceans112** [comment]
Let me be more specific.
If, for example I start do: 
```
:vertical Man acc<Tab>
```
nothing happens, but if do:
```
:vertical Man acc(<Tab> // notice the '('
```
then completion kicks in. So I don't get you when you say it's a Vim limitation.
Besides this, I wonder if you could provide a command like Vnman (from Neoman).

Thanks.

**Comment by oceans112** [comment]
Holy moly, it's the very same bug!
I am sorry, I promise you I did research for a related bug, I used the wrong search keywords I guess.
Is there any workaround I can use in the meantime?
