### ISSUE TITLE
man.vim: q doesn't quit, but it tries to close

### ISSUE THREAD

**Issue by oceans112** [neovim/neovim#7873]
- `nvim --version`: NVIM v0.2.2
- Operating system/version: Archlinux

### Steps to reproduce using `nvim -u NORC`
from the shell:
```
man man
```
and then, inside neovim:
```
q
```

### Actual behaviour
```
E444: Cannot close last window
```
### Expected behaviour
From :help man
```
q  :quit if invoked as $MANPAGER, otherwise :close.
```

**Comment by justinmk** [comment]
Works for me. Tested with 0.2.3.

**Comment by oceans112** [comment]
In made a rc file with only those 2 lines:
```
syntax on
filetype plugin on
```
Odd enough, if i invert those 2 lines, it works.
Can you confirm this?

**Comment by justinmk** [comment]
Maybe https://github.com/neovim/neovim/pull/7809 fixes that? Can you try one of the dev builds here: https://github.com/neovim/neovim/releases

**Comment by justinmk** [comment]
Thanks for the repro, confirmed on 0.2.3.
 
https://github.com/neovim/neovim/commit/94f4469638590ca5cc724ab6459f2cfc78c621a4 should fix it.

**Comment by beardedsakimonkey** [comment]
@nhooyr i'm hitting this issue as of lastest HEAD. seems reverting e8ccd0f2347feb26071e8667d24f3281db79ede3 fixes it

**Comment by nhooyr** [comment]
@beardedsakimonkey What does `:eval bufnr('%')` print in the man.vim buffer?

**Comment by beardedsakimonkey** [comment]
@nhooyr `:echo bufnr('%')` prints `1` when opening a man page from the CLI.

**Comment by nhooyr** [comment]
Ah my bad. Looks like my open PR fixes it: https://github.com/neovim/neovim/pull/12483

Can you please try that and can you reopen this issue @tjdevries

**Comment by nhooyr** [comment]
FYI the commit I reverted from @justinmk didn't directly solve the problem but my new PR does. It only occurs if your syntax file is loaded before the ftplugin which shouldn't happen normally unless you have a line in your init.vim that loads the syntax first.

**Comment by nhooyr** [comment]
My new PR moves the pager state into a buffer variable instead so it doesn't matter what runs first.

**Comment by beardedsakimonkey** [comment]
@nhooyr your PR fixes the issue for me

**Comment by jtheoof** [comment]
Side note, I had this issue which led me to this github issue.

My problem was that I had an autocmd that looked like below. Removing `man` from the list fixed the problem.

```
vim.cmd [[
  augroup _general_settings
    autocmd!
    autocmd FileType qf,help,man,netrw,lspinfo nnoremap <silent> <buffer> q :close<CR> 
  augroup end
]]
```
