### ISSUE TITLE
 [ 40%] Performing install step for 'libuv' gcc: error: 1.12.0": No such file or directory -

### ISSUE THREAD

**Issue by blancha** [neovim/neovim#7874]
Hi, 

My build of Neovim 0.2.2 from source fails on Centos 7 with GCC 5.4.0, at libuv installation step.
I get the following error message.
"gcc: error: 1.12.0": No such file or directory"

I've posted more of the output of the installer below.

[ 39%] No build step for 'libuv'
[ 40%] Performing install step for 'libuv'
make[4]: Entering directory '/project/6000762/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv-build'
libtool: compile:  /cvmfs/soft.computecanada.ca/custom/bin/cc -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.12.0\" "-DPACKAGE_STRING=\"libuv 1.12.0\"" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.12.0\" -DSUPPORT_FLAG_VISIBILITY=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_LIBNSL=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1 -I. -I/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv -I/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv/include -I/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv/src -I/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv/src/unix -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -D_GNU_SOURCE -g -O2 -pedantic -g -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wstrict-prototypes -MT src/libuv_la-fs-poll.lo -MD -MP -MF src/.deps/libuv_la-fs-poll.Tpo -c /home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv/src/fs-poll.c  -fPIC -DPIC -o src/libuv_la-fs-poll.o
gcc: error: 1.12.0": No such file or directory
make[4]: *** [Makefile:1879: src/libuv_la-fs-poll.lo] Error 1
make[4]: Leaving directory '/project/6000762/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv-build'
make[3]: *** [CMakeFiles/libuv.dir/build.make:74: build/src/libuv-stamp/libuv-install] Error 2
make[3]: Leaving directory '/project/6000762/modules/software/neovim/neovim-0.2.2/.deps'
make[2]: *** [CMakeFiles/Makefile2:604: CMakeFiles/libuv.dir/all] Error 2
make[2]: Leaving directory '/project/6000762/modules/software/neovim/neovim-0.2.2/.deps'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/project/600

Thank you for your help, 

Alexis

**Comment by justinmk** [comment]
`make` can't handle spaces. There's a space in "libuv 1.12.0", you need to figure out where that came from.

**Comment by blancha** [comment]
How can I figure it out?

I've tried another version of gcc, gcc 6.40.
I've tried an older version of Neovim, 0.2.1, and the latest nightly build.
I tried make distclean, and rebuilding.
I always get the same error message.

If I look at all the files, this is the only line where 1.12.0 is mentioned.
<[blancha@cedar5 neovim-0.2.2]$ pwd
/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2
[blancha@cedar5 neovim-0.2.2]$ grep -rF 1.12.0 *
third-party/CMakeLists.txt:set(LIBUV_URL https://github.com/libuv/libuv/archive/v1.12.0.tar.gz)>

I've also downloaded and built libuv myself, so I'm wondering if there was a flag I could specify during the build for the Neovim installation to use the version of libuv I installed.

/home/blancha/projects/def-kleinman/modules/software/libuv/1.19.0
<[blancha@cedar5 1.19.0]$ ls
include  lib
>

**Comment by blancha** [comment]
The variable PACKAGE_STRING is defined as "libuv 1.12.0" in the Makefile for the libuv build.
Should I change the value here?
Am I the only one having this issue?

`
[blancha@cedar5 libuv-build]$ pwd
/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/build/src/libuv-build
[blancha@cedar5 libuv-build]$ grep PACKAGE_STRING Makefile 
DEFS = -DPACKAGE_NAME=\"libuv\" -DPACKAGE_TARNAME=\"libuv\" -DPACKAGE_VERSION=\"1.12.0\" -DPACKAGE_STRING=\"libuv\ 1.12.0\" -DPACKAGE_BUGREPORT=\"https://github.com/libuv/libuv/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libuv\" -DVERSION=\"1.12.0\" -DSUPPORT_FLAG_VISIBILITY=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBDL=1 -DHAVE_LIBNSL=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBRT=1
PACKAGE_STRING = libuv 1.12.0
`

**Comment by blancha** [comment]
Correcting the Makefile by removing the extra space at the2 locations actually worked!
But,I only got stuck at a later stage. :(
This time Unibilium is missing.

`
-- Found LibUV: /home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/usr/lib/libuv.a  
-- Found Msgpack: /home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/usr/lib/libmsgpackc.a (found suitable version "2.1.3", minimum required is "1.0.0") 
-- Found LuaJit: /home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/.deps/usr/lib/libluajit-5.1.a  
-- Performing Test MSGPACK_HAS_FLOAT32
-- Performing Test MSGPACK_HAS_FLOAT32 - Success
-- Could NOT find unibilium (missing:  UNIBILIUM_LIBRARY) 
-- Performing Test UNIBI_HAS_VAR_FROM
-- Performing Test UNIBI_HAS_VAR_FROM - Failed
CMake Error at /cvmfs/soft.computecanada.ca/nix/store/j6sfh5gl95hhaxxd02g2cvkpvrvjq4xy-cmake-cursesUI-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibTermkey (missing: LIBTERMKEY_LIBRARY)
Call Stack (most recent call first):
  /cvmfs/soft.computecanada.ca/nix/store/j6sfh5gl95hhaxxd02g2cvkpvrvjq4xy-cmake-cursesUI-3.8.2/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibTermkey.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:364 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/build/CMakeFiles/CMakeOutput.log".
See also "/home/blancha/projects/def-kleinman/modules/software/neovim/neovim-0.2.2/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:71: build/.ran-cmake] Error 1
`
