### ISSUE TITLE
ARM64 (AArch64) Lua "bad light userdata pointer"

### ISSUE THREAD

**Issue by myfreeweb** [neovim/neovim#7879]
Looks like the infamous light userdata issue https://github.com/LuaJIT/LuaJIT/pull/230 https://groups.google.com/forum/#!topic/openresty-en/Gp0NGN9lMXk etc. is affecting Neovim.

Raspberry Pi 3, FreeBSD 12-CURRENT, LuaJIT 2.1.0-beta3. Crashes when running any lua command, like `:lua x`, or when running `--version`:

```
$ nvim --version
NVIM v0.2.2
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```
Looks like light userdata is only used for the old vim lua API (`src/nvim/lua/executor.c`). I actually managed to install all my plugins so clearly that API is not used very much. But this is still a problem.

**Comment by justinmk** [comment]
From reading https://github.com/LuaJIT/LuaJIT/pull/230 it sounds like the issue can be avoided by changing how we use this feature, or avoiding it entirely. Patch or guidance welcome.

**Comment by myfreeweb** [comment]
Yeah, I'm not familiar with Lua at all, I'm not sure how else you'd pass arguments for `pushcfunction` - `call`.

What is the purpose of the `NLUA_CALL_C_FUNCTION` thing? Why are these functions called as if they were called by Lua code?

**Comment by ZyX-I** [comment]
Do not remember exactly, this for sure has something to do with Vim behaviour: it uses pushcclosure with argument 1 with cache table as upvalue in place of calling those functions directly (and I have no idea why the thing exists at all for anything, but buffer and window objects: lua-referenced lists and dictionaries are way easier to store in something like linked list as lua C API is not an example of a sane C API), I use pushcfunction which is the same thing as pushcclosure with argument 0. But can’t say whether I chose to use NLUA_CALL_C_FUNCTION because I *needed to* or only because it is how Vim does things.

**Comment by myfreeweb** [comment]
Confirming that the patch fixed the issue. thanks!

**Comment by z3ntu** [comment]
This is again an issue (0.3.1), see https://git.alpinelinux.org/cgit/aports/commit/community/neovim?id=397b9a65ad6c7cd0981d651a5e9c6bb15a2a69c8 . ArchLinuxARM also doesn't have aarch64 neovim builds, but I didn't find where they blacklist packages. Can also reproduce it on my aarch64 board.

**Comment by justinmk** [comment]
Well, if that's the case it should be easy to bisect.

https://git.alpinelinux.org/cgit/aports/commit/community/neovim?id=397b9a65ad6c7cd0981d651a5e9c6bb15a2a69c8 mentions 0.2.2 so I don't understand why you linked to it

**Comment by z3ntu** [comment]
So it looks like it should've been working with v0.3.0, correct? That version also doesn't compile for me.

**Comment by z3ntu** [comment]
In `v0.2.0` the error is at https://github.com/neovim/neovim/blob/v0.2.0/scripts/gendeclarations.lua#L210 and on `master` it's at https://github.com/neovim/neovim/blob/dadcfe22cab6c4c5e838c0127303bc81638b7283/src/nvim/generators/gen_api_ui_events.lua#L15

Full error message:
```
pine-a64lts:~/neovim/build$ make
/usr/bin/cmake -H/home/user/neovim -B/home/user/neovim/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/user/neovim/build/CMakeFiles /home/user/neovim/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/user/neovim/build'
make -f src/nvim/CMakeFiles/nvim.dir/build.make src/nvim/CMakeFiles/nvim.dir/depend
make[2]: Entering directory '/home/user/neovim/build'
[  0%] Generating auto/ui_events.generated.h, auto/ui_events_call.generated.h, auto/ui_events_remote.generated.h, auto/ui_events_bridge.generated.h, auto/api/private/ui_events_metadata.generated.h
cd /home/user/neovim/build/src/nvim && /usr/bin/luajit /home/user/neovim/src/nvim/generators/gen_api_ui_events.lua /home/user/neovim/src/nvim /home/user/neovim/src/nvim/api/ui_events.in.h /home/user/neovim/build/src/nvim/auto/ui_events.generated.h /home/user/neovim/build/src/nvim/auto/ui_events_call.generated.h /home/user/neovim/build/src/nvim/auto/ui_events_remote.generated.h /home/user/neovim/build/src/nvim/auto/ui_events_bridge.generated.h /home/user/neovim/build/src/nvim/auto/api/private/ui_events_metadata.generated.h
/usr/bin/luajit: bad light userdata pointer
stack traceback:
        [C]: in function 'match'
        /home/user/neovim/src/nvim/generators/gen_api_ui_events.lua:15: in main chunk
        [C]: at 0xaaaae25062e4
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:1237: src/nvim/auto/ui_events.generated.h] Error 1
make[2]: *** Deleting file 'src/nvim/auto/ui_events.generated.h'
make[2]: Leaving directory '/home/user/neovim/build'
make[1]: *** [CMakeFiles/Makefile2:2671: src/nvim/CMakeFiles/nvim.dir/all] Error 2
make[1]: Leaving directory '/home/user/neovim/build'
make: *** [Makefile:155: all] Error 2
```

**Comment by justinmk** [comment]
We can't fix bugs in 0.2 ...

**Comment by z3ntu** [comment]
It also doesn't work in master... 

Looking at the Alpine commit history, it seems that it has worked on 0.2.2 (with older versions of the dependencies). To my understanding some package update between 2018-02-27 and 2018-04-28 broke it.

**Comment by justinmk** [comment]
@z3ntu  If it was not fixed at any time between 0.2.2 and master then something is wrong with your environment, or it's a different issue. So far the information you've given is unclear, I don't know how to help you.

**Comment by mcepl** [comment]
@justinmk what's wrong with my environment ([build of ``master``](https://build.opensuse.org/package/show/home:mcepl:neovim/neovim) with this [build log](https://github.com/neovim/neovim/files/2615212/_log.txt))?

**Comment by justinmk** [comment]
git grep userdata

returns nothing relevant in the Neovim source tree. We _aren't using that feature_. 

@mcepl I looked at your build log. Some things I noticed:

```
[   79s] Patch #2 (neovim-0.1.7-bitop.patch):                                          
[   79s] + /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0                         
[   79s] patching file CMakeLists.txt                                                  
[   79s] patching file src/nvim/ex_cmds.lua                                            
[   79s] + echo 'Patch #3 (neovim-0.2.0-gcc-prototype.patch):'                                                                                              
[   79s] Patch #3 (neovim-0.2.0-gcc-prototype.patch):                                  
[   79s] + /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
```

What is `neovim-0.1.7-bitop.patch`  and why is it being applied to Nvim 0.3.2?

And most important:

```
[  158s] [  0%] Generating auto/ui_events.generated.h, auto/ui_events_call.generated.h, auto/ui_events_remote.generated.h, auto/ui_events_bridge.generated.h, auto/api/private/ui_events_metadata.generated.h
[  158s] /usr/bin/luajit: bad light userdata pointer
```

That is happening before Nvim has even compiled, so it's unrelated to this ticket. It's happening in `/usr/bin/luajit` which we have no control over.  It is a problem with your distribution/environment.

**Comment by jamessan** [comment]
I just tried building nvim on one of Debian's arm64 porterboxes and ran into the same problem.  As @justinmk points out, this is happening when running luajit itself, so that's where the bug lies.

Seems https://github.com/LuaJIT/LuaJIT/pull/435 (or something like it) will be needed to use LuaJIT on arm64/aarch64, and possibly even x86_64 in the future.

**Comment by bfredl** [comment]
When not using bundled deps, should the code generator default to using lua (not luajit)? I don't think generator step is speed critical for building dist package.

**Comment by jamessan** [comment]
We should avoid luajit altogether on arm64 until that issue is fixed upstream.  Using lua for the generator scripts would avoid _that_ issue but doesn't guarantee that there won't be runtime issues with nvim itself.

**Comment by bfredl** [comment]
@jamessan I was thinking like some of the generator dependency (lika lpeg) was using userdata while nvim doesn't, but indeed the issue will re-arise when someone does `require'lpeg'` or similar inside nvim (as we want to support). (In general luajit echosystem seems to be `x64_86` first, the most active(?) fork `raptorjit` even nuked everything but x86 from the codebase ...)

**Comment by mcepl** [comment]
@justinmk https://build.opensuse.org/package/show/home:mcepl:neovim/neovim is the repository with all patches.

  * [neovim-0.1.7-bitop.patch](https://github.com/neovim/neovim/files/2616072/neovim-0.1.7-bitop.patch.txt) - for building with Lua 5.1 (e.g., LuaJIT) we need external dependency on lua-bit32 library
  * [neovim-0.2.0-gcc-prototype.patch](https://github.com/neovim/neovim/files/2616074/neovim-0.2.0-gcc-prototype.patch.txt) - fixes a build issue on ppc64
  * [neovim-lua-compatibility.patch](https://github.com/neovim/neovim/files/2616080/neovim-lua-compatibility.patch.txt) - just the opposite, for compatibility with Lua >5.2 where ``unpack`` is ``table.unpack``.

**Comment by justinmk** [comment]
> neovim-0.1.7-bitop.patch - for building with Lua 5.1 (e.g., LuaJIT) we need external dependency on lua-bit32 library

Seems outdated. Why isn't that necessary in our CI//ubuntu env (which builds without LuaJit)? `LUA_DEPENDENCIES` is a list of luarocks packages, so should not be platform-dependent.

> neovim-0.2.0-gcc-prototype.patch - fixes a build issue on ppc64 (I am not the author of the patch, so I am not sure why it does what it does).

Should not be needed, it implies a bug in our code generator (very unusual) or maybe header/include ordering ...

> neovim-lua-compatibility.patch - just the opposite, for compatibility with Lua >5.2 where unpack is table.unpack.

It's going to be a bad time trying to support Lua 5.2. We have a hard dependency on Lua 5.1, so I don't understand why any distro is patching-in Lua 5.2 support. Though the patch is harmless enough, no objection to including it.

**Comment by mcepl** [comment]
> > neovim-0.1.7-bitop.patch - for building with Lua 5.1 (e.g., LuaJIT) we need external dependency on lua-bit32 library

Builds on Fedora fails spectacularly without the patch (that's Lua 5.3).

> > neovim-0.2.0-gcc-prototype.patch - fixes a build issue on ppc64 (I am not the author of the patch, so I am not sure why it does what it does).
> 
> Should not be needed, it implies a bug in our code generator (very unusual) or maybe header/include ordering ...

Unfortunately, I have currently PPC64 LuaJIT builds broken, so I cannot help you test it ATM.

> > neovim-lua-compatibility.patch - just the opposite, for compatibility with Lua >5.2 where unpack is table.unpack.
> 
> We have a hard dependency on Lua 5.1, so I don't understand why any distro is patching-in Lua 5.2 support. Though the patch is harmless enough, no objection to including it.

Because that's what many Linux distributions (e.g., Fedora) have as their default Lua implementation. I know, Lua versions are not upward compatible, but it seems to work nevertheless.

**Comment by Shatur95** [comment]
I have the same issue on the latest master right now.

**Comment by ruifm** [comment]
@Shatur95 I got it working by installing first the luajit compiled from the HEAD of the 2.1 branch: https://github.com/LuaJIT/LuaJIT

If you are using archlinuxarm, I used this AUR package to automate it: https://aur.archlinux.org/packages/luajit-2.1-git/

**Comment by Shatur95** [comment]
Thanks, worked for me!

[luajit-openresty](https://aur.archlinux.org/packages/luajit-openresty) package also works (was suggested by default in #13741).

**Comment by ruifm** [comment]
> [luajit-openresty](https://aur.archlinux.org/packages/luajit-openresty) package also works (was suggested by default in #13741).

Thanks for the suggestion! I just tried it and works great. If it's well maintained then it should be the better option.

**Comment by madskjeldgaard** [comment]
> @Shatur95 I got it working by installing first the luajit compiled from the HEAD of the 2.1 branch: https://github.com/LuaJIT/LuaJIT
> 
> If you are using archlinuxarm, I used this AUR package to automate it: https://aur.archlinux.org/packages/luajit-2.1-git/

I had the same problem and this seems to solve it
