### ISSUE TITLE
Powershell is fine, ISE is not…

### ISSUE THREAD

**Issue by kierun** [neovim/neovim#7899]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? Unknown.
- Operating system/version: Windows 10 v1907.
- Terminal name/version: PowerShell or PowerShell ISE.
- `$TERM`: N.A.

### Steps to reproduce using `nvim -u NORC`

N.A.

### Actual behaviour

 1. Instlal neovim via chocolatey.
 1. Install PowerShell via chocolatey.
 1. `nvim.exe` runs fine when run via the PowerShell. It does nothing (just hangs) when ran from the PowerShell ISE.

### Expected behaviour

`nvim.exe` runs fine on both PowerShell and PowerShell ISE.

**Comment by justinmk** [comment]
Nvim needs a pty (or console on Windows) to work. Are you sure PowerShell ISE can run programs that require that? What other interactive programs work correctly in PowerShell ISE?
