### ISSUE TITLE
Ubuntu Xenial (stable and unstable) PPA sources - same files in neovim-runtime deb

### ISSUE THREAD

**Issue by seefood** [neovim/neovim#7901]
- `nvim --version`:
NVIM v0.2.3-dev
Build type: RelWithDebInfo
Lua 5.1

- Operating system/version: Ubuntu 16.04.3 LTS

### Actual behaviour
```
> sudo apt install neovim-runtime 
[...]
dpkg: error processing archive /var/cache/apt/archives/neovim-runtime_0.2.2-1ppa1~ubuntu16.04.3_all.deb (--unpack):
 trying to overwrite '/usr/share/nvim/runtime/tutor/tutor.tutor', which is also in package neovim 0.2.2ubuntu1+git201801222018-84d4e4a-7e4bb0d-c243e56~ubuntu16.04.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/neovim-runtime_0.2.2-1ppa1~ubuntu16.04.3_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

If I try installing neovim-runtime and then neovim it fails on nvim.png, so there are multiple files accidentally packaged in both. this was fine a few weeks ago and then one of the updates failed with this and has not been fixed since.

### Expected behaviour
get neovim-runtime installed

**Comment by seefood** [comment]
Label distribution etc (don't have rights to add those_

**Comment by jamessan** [comment]
You're mixing the neovim package from the PPA with the neovim/neovim-runtime packages from Ubuntu.  That's a bad idea.  Choose one or the other.

**Comment by jamessan** [comment]
I'll look into adjusting the unstable PPA to make transitioning easier, but the simplest thing for now is to uninstall, change/remove the PPA, and then reinstall.

**Comment by seefood** [comment]
but they are both from the ppa as far as I can tell.

**Comment by jamessan** [comment]
There are two PPAs.  One for the nightly builds from master and one to allow people to install the latest release on older versions of Ubuntu.

They're built by two different mechanisms.  The nightly (unstable) PPA bundles everything into one neovim package.  The stable PPA is essentially a backport of the Debian packaging, which creates both a neovim package and a neovim-runtime package.

**Comment by jamessan** [comment]
I've updated the packaging for the unstable PPA.  The next time it updates the packaging, switching between the PPAs should be smoother.

**Comment by seefood** [comment]
sorry, my bad, the unstable source was also enabled in a separate file.
