### ISSUE TITLE
term emulation doesn't work for powershell that runs in docker container

### ISSUE THREAD

**Issue by mallochine** [neovim/neovim#7904]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? Vim8's terminal doesn't have this bug.
- Operating system/version: Centos 6, but I think can be repro'd on CentOS 7
- Terminal name/version: 
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
docker run -i -t --rm microsoft/powershell
```

### Actual behaviour

The characters are mangled in the powershell. Type anything. A character 'e' for instance.

```
PS />
5;1R5;1R5;7R5;7Re
```

### Expected behaviour

should just type normally

**Comment by mallochine** [comment]
appears as if these escape codes are:

http://www.climagic.org/mirrors/VT100_Escape_Codes.html
```
getcursor DSR         Get cursor position                    ^[6n
cursorpos CPR            Response: cursor is at v,h          ^[<v>;<h>R
```

**Comment by mallochine** [comment]
Sad to say but I just thought of testing this on Vim8, and Vim8 does not have this bug. Have to use Vim8 for now.

**Comment by mallochine** [comment]
Interestingly, it works when I run pwsh inside Vim8's terminal inside Neovim. So I'm still going to use Neovim but use pwsh with Vim8's terminal. Trippy! Inception?

**Comment by justinmk** [comment]
@mallochine 	Does this happen with 0.3.4 or current HEAD? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by justinmk** [comment]
Closing for lack of followup.
