### ISSUE TITLE
BUG: hostname on windows don't care character case

### ISSUE THREAD

**Issue by zhaozg** [neovim/neovim#7909]
Version: HEAD

https://github.com/neovim/neovim/blob/15119f943ab8c2d089f45969da06b6b58b4d0036/test/functional/eval/hostname_spec.lua#L14

`helpers.eq(expected, actual)` => `helpers.eq(expected:upper(), actual:upper())`

![image](https://user-images.githubusercontent.com/542599/35323702-6fd358e6-0129-11e8-9797-8b64f93923c2.png)

**Comment by justinmk** [comment]
Why not just send a PR?

**Comment by zhaozg** [comment]
@justinmk maybe I later
