### ISSUE TITLE
wildmode=longest:full,full behaves different then in vim

### ISSUE THREAD

**Issue by doubleloop** [neovim/neovim#7926]
The behavior of vim vs nvim is different in the following case:

```
nvim -u NORC
:set wildmenu
:set wildmode=longest:full,full
:cd ~/<tab>
```
vs
```
vim -u NORC
:set nocompatible
:set wildmenu
:set wildmode=longest:full,full
:cd ~/<tab>
```

Like in vim, nvim probably should not highlight the first occurrence until completion is selected.

```
$ nvim --version
NVIM v0.2.1-885-g460aab395
Build type: Release
$ echo $TERM
xterm-256color
```

**Comment by justinmk** [comment]
Works the same in Vim 7.4.1689.

**Comment by mhinz** [comment]
@justinmk 

On first `<tab>`, both show the candidates without completing, but only Nvim already highlights the first choice.

**Comment by justinmk** [comment]
For me, Vim 7.4.1689 highlights the first choice.

**Comment by doubleloop** [comment]
https://github.com/vim/vim/commit/ef8eb0897819099fb00d675afb9bffe1d008c45e ?

**Comment by mhinz** [comment]
@doubleloop 

Yup, that's the one. Do you want to port the patch? (It's just a one-liner after all.) Otherwise I'll do it.

**Comment by doubleloop** [comment]
https://github.com/neovim/neovim/pull/7927
