### ISSUE TITLE
TUI: Switching termguicolors at runtime in tmux breaks colors until resized

### ISSUE THREAD

**Issue by johnmiked15** [neovim/neovim#7929]
- `nvim --version`: NVIM v0.2.3-527-g499c9a155
- Vim (version: 8.0.688) does not exhibit the behavior
- Operating system/version: SLES 11.3, Ubuntu 16.04, Windows
- Terminal name/version: GNOME Terminal 3.18.3, also occurs in MinTTY
- `$TERM`: screen-256color

### Steps to reproduce
1. Open a tmux (or screen) session and ensure `$TERM` is `screen-256color`.
1. Create a simple rc file with the following:
```vim
set termguicolors
colorscheme desert
```
2. Open it with `nvim -u bug-vimrc --noplugin`
3. Try to disable termguicolors with `:set notermguicolors` and notice that colors are wrong.
4. Resize the window, colors immediately get redrawn correctly.

This issue does not occur in vim, nor does it seem to occur in nvim when in a normal `xterm-256color` terminal.

Support for changing `termguicolors` at runtime was completed in #7520

**Comment by justinmk** [comment]
Try CTRL-L or  `:mode` as a workaround.

**Comment by johnmiked15** [comment]
I suppose `:mode` does do the same thing as resizing the window, should have tried that as well. Anyway, I confirmed that it also gets the colors working again after `termguicolors` is toggled.

**Comment by bfredl** [comment]
It is possible that #7520 doesn't uphold the necessary condition that the reconfiguration of the bridge comes before the caused redraw. That termguicolors has the redraw flag `'everything'` was probably a mistake, copied without thought from vim (where it makes sense, as its TUI is less decoupled). Rather the bridge should schedule a redraw event. Likewise a future remote TUI implementation will need to use `nvim_ui_set_option('rgb',  true/false)`, we should check that triggers a proper redraw.

Or actually/potentially in the future, the "proper" refactor would be that nvim _always_ calculates both 256 and rgb colors, and transmits them both over the UI protocol (which is not known to be bandwidth preserving anyway...). Then switching between the modes would solely be a UI/TUI affair, no screen.c redraw needed.

**Comment by bfredl** [comment]
I have a WIP branch that does some highlighting refactors, including using attrentry_T as HlAttrs so TUI can switch color mode without full redraw, I will push it as soon as I have fixed some visual glitches...
