### ISSUE TITLE
Default color scheme

### ISSUE THREAD

**Issue by frankie-loves-jesus** [neovim/neovim#793]
https://github.com/altercation/vim-colors-solarized

![untitled-1](https://cloud.githubusercontent.com/assets/4778127/3143463/b1b5929a-e9fb-11e3-9e31-ef89de3248a0.png)

(using [Windows Classic Vs](http://xxinightxx.deviantart.com/art/Windows-Classic-Vs-8-1-Update-1-457573957))

**Comment by justinmk** [comment]
https://github.com/morhetz/gruvbox looks like a robust theme, and works well in the terminal.

**Comment by justinmk** [comment]
Closing in favor of https://github.com/neovim/neovim/issues/14790
