### ISSUE TITLE
mouse: broken on xterm with ncurses 6.1

### ISSUE THREAD

**Issue by yan12125** [neovim/neovim#7932]
- `nvim --version`: v0.2.3-559-g397ff2c35
- Vim (version: ) behaves differently? 8.0.1436 works fine
- Operating system/version: Arch Linux x86_64 with [testing] repo enabled (ncurses 6.1 is still in [testing])
- Terminal name/version: xterm 331
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

1. ```nvim -u NORC foobar.txt```. foobar.txt can be any long text file. Here I use /usr/include/stdio.h as an example.
2. ```:set mouse=a```
3. Click on row 1, col 2

### Actual behaviour
The cursor goes to middle of the screen (like the effect of hitting `M`), and there's an error
```
E349: No identifier under cursor
```

### Expected behaviour
The cursor is now at row 1, col 2

### Analysis & Possible solution

In libtermkey's terminfo driver (driver-ti.c), a TYPE_MOUSE key is handled by peekkey_mouse():

https://github.com/neovim/libtermkey/blob/d31dbdf4a57981b757cd8c0e40503a8a9fa2bc4c/driver-ti.c#L435

peekkey_mouse() appears to handle X10 encoding protocol only:

https://github.com/neovim/libtermkey/blob/d31dbdf4a57981b757cd8c0e40503a8a9fa2bc4c/termkey.c#L1004-L1020

In other words, libtermkey assumes key_mouse entries in terminfo databases always use X10 encoding protocol. This is not true. Since ncurses 6.1, xterm 1006 info (SGR) is added. As neovim uses the 1006 protocol:

https://github.com/neovim/neovim/blob/397ff2c35b7e6ec2db13442b193bfe34f12beda4/src/nvim/tui/tui.c#L1725-L1727

neovim's mouse function is broken.

I'm not sure if libtermkey will be updated to handle SGR encoding in driver-ti.c, but at least there's a workaround - hide the key_mouse entry from driver-ti. Here's the patch I'm using:

```Diff
From ccda9f3ac1ba14c5c8a01303ed62aca17c766f67 Mon Sep 17 00:00:00 2001
From: Chih-Hsuan Yen <yan12125@gmail.com>
Date: Mon, 29 Jan 2018 22:47:25 +0800
Subject: [PATCH] Don't use libtermkey's terminfo driver for key_mouse if it's
 SGR encoding

---
 src/nvim/tui/tui.c | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 2dfe7faa04c..eff62d1e43a 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -1813,6 +1813,14 @@ static const char *tui_tk_ti_getstr(const char *name, const char *value,
     if (value != NULL && strequal(stty_erase, value)) {
       return stty_erase[0] == DEL ? CTRL_H_STR : DEL_STR;
     }
+  } else if (strequal(name, "key_mouse")) {
+    DLOG("libtermkey:kmous=%s", value);
+    // libtermkey assumes mouse encoding protocol is always X10 in its
+    // terminfo driver (driver-ti.c), which is wrong. Don't use it if it's SGR
+    // encoding. XXX how about other encodings (UTF-8, URXVT...)?
+    if (value != NULL && strequal("\033[<", value)) {
+      return NULL;
+    }
   }
 
   return value;
```

**Comment by justinmk** [comment]
If your patch doesn't regress anything, please send a PR and we'll merge it. Don't care about URXVT.

**Comment by yan12125** [comment]
Done -> #7948

I've used this patch for 2 days, so I guess it's fine. Not tested on other terminals, though.

**Comment by leonerd** [comment]
Ah, that's where it's complicated.

The terminfo driver (used by non-xterm terminals) indeed presumes X10 encoding. But the CSI driver which known xterm-alikes (detected by the `$TERM` string) detects almost all of them.
