### ISSUE TITLE
Timeout to start nvim-qt

### ISSUE THREAD

**Issue by adelarsq** [neovim/neovim#7934]
- `nvim --version`: NVIM v0.2.3-533-g9a36337d3
- Vim (version: 8.0 patch 1418) behaves differently? On Vim (GVim) works
- Operating system/version: Windows
- Terminal name/version: none (using on Gui)
- `$TERM`: none (using on Gui)

### Steps to reproduce using `nvim -u NORC`

There are no steps.

### Actual behaviour

Since I have many plugins (206 plugins) when starting nvim-qt gives timeout and shows this message:

![image](https://user-images.githubusercontent.com/430272/35566412-707a6ce8-05a8-11e8-9188-e2dbafff8d41.png)

Gvim take 9 seconds to start.

### Expected behaviour

Even that there are some delay to start the editor have to start normally.

**Comment by equalsraf** [comment]
Hi @adelarsq, for reference you can submit issues in equalsraf/nvim-qt.

The default timeout is 10000 ms (10s). You can override this value with `nvim-qt --timeout 20000` (time is in ms)

Just to be sure this is an issue with the timeout and not something else, does it open when you do `nvim-qt -- -u NORC`.

> Since I have many plugins (206 plugins)

Valid point, maybe we should default to a higher value.

**Comment by bfredl** [comment]
Closed as not actionable in this repo.
