### ISSUE TITLE
Global system clipboard (yank, paste) stopped working

### ISSUE THREAD

**Issue by rafaponieman** [neovim/neovim#7945]
- `nvim --version`: NVIM v0.2.3-dev
- Vim (version: ) same output (NVIM v0.2.3-dev)
- Operating system/version: Kubuntu 17.10
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

Enter some text. Yank, paste on another application.
```

### Actual behaviour
Yank doesn't affect the system clipboard, only works inside Nvim (from one buffer to another), but not to/from system clipboard.

### Expected behaviour
It should yank & paste directly from Nvim to system clipboard.

This was working perfectly, suddenly, without making any changes on my config, it stopped working (and it's also happenning with NORC). Tried different changes to clipboard setting but nothing solved the problem. Currently my clipboard value is clipboard=

Thank you!!

**Comment by jamessan** [comment]
You haven't specified how you're yanking.  (n)vim doesn't copy to the system clipboard by default.  You need to explicitly tell it to by yanking to the `+` register -- e.g. `"+yy`.

If you want normal yanks to use the system clipboard, too, then you need to `set clipboard=unnamedplus`.

**Comment by rafaponieman** [comment]
Hi @jamessan, I guess the config I'm using (liuchengxu/space-vim) had set that, so yanks and pastes to system clipboard were working by default.

Currently, if I run nvim -u NORC, and yank with "+yy it still doesn't affect my system clipboard, and setting set clipboard=unnamedplus also has no effect (I checked with set clipboard? and it did show clipboard=unnamedplus).

**Comment by jamessan** [comment]
You should run `:checkhealth` then.  You likely don't have a tool installed to allow nvim to talk to the X clipboard.  See `:help clipboard`.

**Comment by rafaponieman** [comment]
That was it, installing xsel solved it. I have no idea though why it did work previously and it suddenly stopped, seems like I had one of the providers installed but it was removed or stopped working. Thanks a lot!!!

**Comment by zekefast** [comment]
Installation of `xsel` helped me as well! Thanks a lot, @rafaponieman!
