### ISSUE TITLE
how to install neovim with lower libc.so.6

### ISSUE THREAD

**Issue by zuo000** [neovim/neovim#7952]
I'm working on a workstation and no root access, and dynamic library of libc is very low(libc-2.11.3.so).
I tried with installing the latest gcc and cmake under my home directory, but seems it depends many other things, like curl(ssl supported), lpeg, but the instrcution is not very detailed about this. and it is hard to get cmake to use curl provided by me instead of system.
Do you have some easy way to build source, or some detailed instruction?

**Comment by justinmk** [comment]
did you read https://github.com/neovim/neovim/wiki/Building-Neovim ? It has notes on this. Feel free to update it.
