### ISSUE TITLE
functional test 'connecting to its own pipe address does not deadlock' hangs on Linux

### ISSUE THREAD

**Issue by sohnryang** [neovim/neovim#7956]
- `nvim --version`: master branch
- Vim (version: ) behaves differently? N/A
- Operating system/version: Linux Mint 18.2 x86_64
- Terminal name/version: Gnome Terminal 3.18.3
- `$TERM`:xterm-256color

The 'connecting to its own pipe address does not deadlock' in functionaltest hangs in Linux too.

**Comment by KillTheMule** [comment]
I've had this problem for quite some time, varying over different commits, PRs, versions, none have been ok for quite some time locally.

**Comment by justinmk** [comment]
I thought we marked that test as pending()?  @bfredl

**Comment by bfredl** [comment]
@justinmk only on quickbuild. #68r1 On travis it seems to work. I suppose on some systems pipe addresses can have synonyms not recognizable with `fix_fname` . Also it is not reliable in general I realize if someone `mv`:s a pipe endpoint....

**Comment by aktau** [comment]
Thanks for fixing it!

**Comment by justinmk** [comment]
@sohnryang is this still an issue?

**Comment by sohnryang** [comment]
I can't confirm since I moved from Linux to macOS as my current platform... Sorry! 😢

**Comment by aufarg** [comment]
Hi, can we reopen this issue? I'm facing the same problem as OP on my platform.

- `nvim --version`: master
- `vim -u DEFAULTS` (version: ) behaves differently? N/A
- Operating system/version: Arch Linux/5.7.11.arch1-1
- Terminal name/version: alacritty/0.5.0
- `$TERM`: tmux-256color
