### ISSUE TITLE
xclip clipboard test fails with `target STRING not available`

### ISSUE THREAD

**Issue by teto** [neovim/neovim#7958]
- `nvim --version`: current head 6452831cf985bd31d16eb5a04b345038f45d203f
- Operating system/version: nixos
- Terminal name/version: termite

When trying to run the functionaltests in nixos with lua5.1, I get:
```
[ SKIPPED  ] ...cratch/neovim/test/functional/provider/ruby_spec.lua @ 18: Missing neovim RubyGem.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] .../scratch/neovim/test/functional/eval/system_spec.lua @ 330: system() with a program that doesn't close stdout will exit properly after passing input
.../scratch/neovim/test/functional/eval/system_spec.lua:332: Expected objects to be the same.
Passed in:
(string) 'Error: target STRING not available
'
Expected:
(string) 'clip-data'

stack traceback:
	(tail call): ?
	.../scratch/neovim/test/functional/eval/system_spec.lua:332: in function <.../scratch/neovim/test/functional/eval/system_spec.lua:330>

[  FAILED  ] .../scratch/neovim/test/functional/eval/system_spec.lua @ 515: systemlist() with a program that doesn't close stdout will exit properly after passing input
.../scratch/neovim/test/functional/eval/system_spec.lua:518: Expected objects to be the same.
Passed in:
(table) {
 *[1] = 'Error: target STRING not available' }
Expected:
(table) {
 *[1] = 'clip'
  [2] = 'data' }

stack traceback:
	(tail call): ?
	.../scratch/neovim/test/functional/eval/system_spec.lua:518: in function <.../scratch/neovim/test/functional/eval/system_spec.lua:515>

```

According to https://unix.stackexchange.com/questions/316715/xclip-works-differently-in-interactive-and-non-interactive-shells, it doesn't seem to be nixos specific but might happen on other platforms.

If I transpose what happens in the functionaltest to shell, it fails too:
```
sh -c 'echo "clip-data" | xclip -i -loops 1 -selection clipboard'
sh -c 'xclip -o -selection clipboard'
Error: target STRING not available
```
With `sh -i -c` flag the previous test fails too.
I wonder if the root cause an be fixed or if xclip should be replaced by xsel in the test as it seems more robust according to SO.

**Comment by justinmk** [comment]
Can you `:set shell` in that specific test?

**Comment by teto** [comment]
Seems to work fine with lua5.1 but not with luajit. I admit I don't quite understand why. What do you suggest to set shell to since interactive mode doesn't seem to work either ?

**Comment by teto** [comment]
Duplicate of https://github.com/neovim/neovim/issues/2642 (I thought the trigger was different but it might end up being the same bug)

**Comment by PovarovDenis** [comment]
The problem is in the xclip library - https://github.com/astrand/xclip/issues/38

**Comment by blueyed** [comment]
Not really / alone.
For me it happens due to using a clipboard manager, which takes ownership of the clipboard (see https://github.com/neovim/neovim/issues/4900#issuecomment-501866842).

**Comment by liushapku** [comment]
> * `nvim --version`: current head [6452831](https://github.com/neovim/neovim/commit/6452831cf985bd31d16eb5a04b345038f45d203f)
> * Operating system/version: nixos
> * Terminal name/version: termite
> 
> When trying to run the functionaltests in nixos with lua5.1, I get:
> 
> ```
> [ SKIPPED  ] ...cratch/neovim/test/functional/provider/ruby_spec.lua @ 18: Missing neovim RubyGem.
> [  FAILED  ] 2 tests, listed below:
> [  FAILED  ] .../scratch/neovim/test/functional/eval/system_spec.lua @ 330: system() with a program that doesn't close stdout will exit properly after passing input
> .../scratch/neovim/test/functional/eval/system_spec.lua:332: Expected objects to be the same.
> Passed in:
> (string) 'Error: target STRING not available
> '
> Expected:
> (string) 'clip-data'
> 
> stack traceback:
> 	(tail call): ?
> 	.../scratch/neovim/test/functional/eval/system_spec.lua:332: in function <.../scratch/neovim/test/functional/eval/system_spec.lua:330>
> 
> [  FAILED  ] .../scratch/neovim/test/functional/eval/system_spec.lua @ 515: systemlist() with a program that doesn't close stdout will exit properly after passing input
> .../scratch/neovim/test/functional/eval/system_spec.lua:518: Expected objects to be the same.
> Passed in:
> (table) {
>  *[1] = 'Error: target STRING not available' }
> Expected:
> (table) {
>  *[1] = 'clip'
>   [2] = 'data' }
> 
> stack traceback:
> 	(tail call): ?
> 	.../scratch/neovim/test/functional/eval/system_spec.lua:518: in function <.../scratch/neovim/test/functional/eval/system_spec.lua:515>
> ```
> 
> According to https://unix.stackexchange.com/questions/316715/xclip-works-differently-in-interactive-and-non-interactive-shells, it doesn't seem to be nixos specific but might happen on other platforms.
> 
> If I transpose what happens in the functionaltest to shell, it fails too:
> 
> ```
> sh -c 'echo "clip-data" | xclip -i -loops 1 -selection clipboard'
> sh -c 'xclip -o -selection clipboard'
> Error: target STRING not available
> ```
> 
> With `sh -i -c` flag the previous test fails too.
> I wonder if the root cause an be fixed or if xclip should be replaced by xsel in the test as it seems more robust according to SO.

I also got the same problem. For me, the error can be more easily identified by doing `echo abc | xclip -loop 1 -quiet`, which directly quits without waiting for a selection. If I change the loops to 2, then the output is 
```
Waiting for 2 selection requests, Control-C to quit
  Waiting for selection request 1 of 2.
  Waiting for selection request 2 of 2.           <--- waiting here
```
It seems some other process consumes one paste request.

This phenomenon is observed using ubuntu 20.04 with xclip 0.13. 
With xclip 0.12, the problem, I need to change to `-loop 3` in order to get a chance to paste (i.e. some other process consumes two paste requests.

Don't whether it has something to do with this: [https://stackoverflow.com/questions/22686866/why-has-xclip-loop-1-stopped-working]()
