### ISSUE TITLE
neovim conifg in windows 10 ?ginit.vim and init.vim

### ISSUE THREAD

**Issue by yylays** [neovim/neovim#7962]
i am trying to use neovim in windows, since i want to use powerline for it i need to config the font, i found it is not working in init.vim, and i have to do it in ginit.vim . so i thought i may have both two config files,but this nvim cannot start, i am wondering how do i do with these two config files ginit.vim and init.vim?

**Comment by teto** [comment]
powerline doesn't support neovim and neovim doesn't support guifont. neovim-qt has a shim you can use to set fonts there.

**Comment by justinmk** [comment]
neovim 0.2.3 supports guifont. It's up to the UI to implement it.
