### ISSUE TITLE
Feature Request: Make it so I don't have to use pip

### ISSUE THREAD

**Issue by jordwalke** [neovim/neovim#7964]
I don't want to have to use/install pip. Just getting a solid and compatible python setup is the most difficult part of using neovim and I know I'm not the only one that feels this way. I would like to use my system's host python (OS X) but I don't appear to have pip, and pip is how I am to install the neovim python support. Can you please bundle the python plugin support with neovim (even if you don't bundle python itself, bundle whatever it is that neovim requires to bridge to python).

I just tried installing python via brew just so that I could get pip, and it failed to install due to permissions issues. The number of things that can go wrong just installing python are endless.

**Comment by jordwalke** [comment]
For example just trying to install python with `brew` I hit this issue: https://github.com/Homebrew/homebrew-core/issues/19286

**Comment by jordwalke** [comment]
And then even when I do finally get pip working, I try to install the neovim plugin with it and it gives me this error:

```
  creating /Library/Python/2.7/site-packages/msgpack
    error: could not create '/Library/Python/2.7/site-packages/msgpack': Permission denied
```

I am 100% convinced that global installs of software that hijack system paths like `/user/bin/`, `/user/local/bin`, or any "Frameworks", or "/Library" paths are going to fail for people. If not now then in the next stupid Mac OS X upgrade when Apple decides to wipe them out or change the default permissions on them.

Sandboxing and isolation the only way to get reliable software installs. Disk space is cheap, developer time is extremely expensive.

**Comment by jordwalke** [comment]
And then I fixed that errors, and there was yet another problem when trying to install the neovim plugin (another permissions error!)

**Comment by ZyX-I** [comment]
Normally system package managers are fully capable of installing pip packages themselves if somebody packages them, sometimes having a dedicated utility library to help with packaging (e.g. like distutils-r1 eclass in Gentoo). If you are not fine with `--user` installation it is possible to create a package for neovim pip package, otherwise pip-based variant is dealing with package dependencies in a saner way. E.g. Gentoo does have `dev-python/neovim-python-client` package.

**Comment by justinmk** [comment]
@jordwalke I completely agree about the difficulties of python and its packaging. But what happens if you want to use jedi or other vim-python plugins that have pip dependencies? It's more of the same.

Ultimately this is a python failure. We could do contortions to work around it, but after all of that, users will often need pip anyways.

Nvim provides Lua as an alternative always-available runtime, so plugin authors can avoid this issue.

**Comment by jordwalke** [comment]
I've used tons of plugins that require python. None of them have required that I use pip. I am not against package management, I'm just against terrible package management. Not all plugins that use python require pip (it seems like a minority even). Right now neovim puts a requirement that anyone - to use any amount of python in any plugin - must use pip. I think that's a problem for neovim. If pip was as ubiquitous and fool proof as npm, and didn't clobber all over your global paths by default - maybe it would be a different story.

**Comment by jamessan** [comment]
We don't require anyone to use pip. Installing the neovim module through pip is simply a suggestion, since that's the most likely way one would install it without a system package manager.  If the module is available through your system's package manager, then certainly use that.

**Comment by jordwalke** [comment]
I understand but might it also be a good idea to not even require that it be installed? Why not include it with neovim. That wouldn’t prevent other plugins from using pip.

**Comment by ZyX-I** [comment]
@jordwalke Neovim Python package has its dependencies as well, it would be a hell to maintain and let `pip install` on the dependencies work correctly at the same time.

**Comment by ZyX-I** [comment]
And also neither Python nor Ruby, nor anything but VimL and lua are first-class citizens here. We have more languages supported, maintained by other people.

**Comment by jordwalke** [comment]
Does Python not have a way to trivially vendor a source tree like node does (you would simply copy the node_modules directory into the release). Today, Vim doesn't require that I install anything from pip (or anywhere else) to be able to write plugins in Python. Neovim is improving up on Vim, so wouldn't it make sense that an improvement upon Vim not put more in the way of being used?

**Comment by justinmk** [comment]
> Today, Vim doesn't require that I install anything from pip (or anywhere else) to be able to write plugins in Python. Neovim is improving up on Vim, so wouldn't it make sense that an improvement upon Vim not put more in the way of being used?

Vim instead requires linking to shared libraries, which is often a source of user headaches. 

The use-case presented here is a user that wants to use python, wants to write python plugins, ... yet doesn't want to deal with the python ecosystem. 

Help with improving this is welcome.  But it needs to arrive in the form a pull request, not a change order.

**Comment by bfredl** [comment]
I don't think "vendoring" is the way to go, rather promoting the python client to be in whatever popular system package repos.

When people say "vim+python works without configuration" they typically have installed a distro compiled version of vim-huge that has been linked properly to the python libraries in the same distro. (when I compiled vim8 myself from sources python did not work "without configuration", I needed to change the compiler flags manually) The corresponding scenario would be `neovim` + `python-neovim` available in the same distro package set.

When compiling neovim oneself, needing to use pip (or installing python-msgpack through the distro + using `setup.py` in python-client repo) is not unreasonable.

**Comment by bfredl** [comment]
Of course this doesn't apply to windows. But for windows, gvim.exe seems to require the user to obtain the correct version of python (2.7 and 3.5 as it happens) themselves. But the official python binaries on windows include pip (with correctly set up permissions, at least when I tried), so our story is not different more than one extra step.

Of course, anyone should feel free to construct a one-click installer for platform X. But this should be best seen as a platform-specific binary distribution project (similar to Cream offerering up-to-date convenient installers for gvim on windows) , and shouldn't change our source builds or packaging story for distros.
