### ISSUE TITLE
"E73: tag stack empty" breaks scrolling with mouse

### ISSUE THREAD

**Issue by MichaelAquilina** [neovim/neovim#7970]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently? yes - it doesnt have this issue
- Operating system/version: OpenSUSE Tumbleweed
- Terminal name/version: tilix 1.7.6
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```
* Scroll with mouse
* Notice "E73: tag stack empty" error message
* Notice that scrolling does not work

I can reproduce the same issue with `nvim -u NONE -U NONE -N` which from what I understand disables all configuration.

### Actual behaviour
Cannot scroll page with scroll on mouse

### Expected behaviour
No error message and scrolling to work

**Comment by MichaelAquilina** [comment]
Just tried this on version `0.2.3` from the `releases` tab and it doesnt seem to be an issue there

**Comment by MichaelAquilina** [comment]
Sometimes I get `E5555: at the bottom of tag stack`

**Comment by hansgans** [comment]
nvim --version: NVIM v0.2.2
Vim (version: ) behaves differently? yes - it doesnt have this issue
Operating system/version: MacOS 10.13
Terminal name/version: iterm
$TERM: xterm-256color

Same problem here:
```
mouse click: E426: tag not found: actions
mouse scrolling: E555: at bottom of tag stack
```
The same happen when I start it via the ```--noplugin``` option
I'm using neovim installed via MacPorts:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -pipe -Os -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/config -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/neovim-0.2.2/src -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/src/nvim/auto -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/include
Compiled by macports@highsierra.internal.macports.net
```

**Comment by justinmk** [comment]
> Cannot scroll page with scroll on mouse

    :set mouse=a

**Comment by hansgans** [comment]
No :set mouse=a is set. Please reopen the issue.

**Comment by MichaelAquilina** [comment]
I also have `set mouse=a` set. As I mentioned, this bug is also not present in standard vim and neovim `0.2.3` so it seems like its something specific to 0.2.2. Is there anything we can check to see what is going on? Debugging vim issues is somewhat alien to me.

**Comment by neachdainn** [comment]
For what it's worth, I am also having this issue.

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -pipe -Os -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/config -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/neovim-0.2.2/src -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/src/nvim/auto -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_editors_neovim/neovim/work/build/include
Compiled by macports@sierra.internal.macports.net

Features: +acl +iconv +jemalloc +tui 
```
Vim behaves differently? Yes. Does not have this issue.
Operating system/version: MacOS 10.12.3
Terminal name/version: iterm 2.7.1
$TERM: xterm-256color
I have also `set mouse=a`.

**Comment by hansgans** [comment]
v0.2.3 solved the issue for me

**Comment by thymbahutymba** [comment]
I am also having this issue
NVIM v0.2.2
I have `set mouse=a`

**Comment by marvinbernhardt** [comment]
Same issue for me with NVIM v0.2.2

**Comment by yan12125** [comment]
This is most likely the same issue as https://github.com/neovim/neovim/issues/7932
