### ISSUE TITLE
visual block mode yank to clipboard adds newline

### ISSUE THREAD

**Issue by kinghrothgar** [neovim/neovim#7975]
- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
Does the same thing
- Operating system/version:
Arch Linux with everything up-to-date as of 2018-02-06 21:00 UTC
- Terminal name/version:
termite 13
- `$TERM`:
xterm-termite and in tmux (screen-256color)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set clipboard=unnamedplus
```
Now type anything, go into visual block mode, select the text (not including a trailing newline), yank it.

### Actual behaviour
The text copied into the X-Org clipboard has a newline

### Expected behaviour
The clipboard to contain only the text I yanked.

**Comment by justinmk** [comment]
Not sure what you expect. It depends on  what is the "receiving end". That's a rather important detail to omit ...

Anyways we can't  deviate from Vim behavior for clipboard.
