### ISSUE TITLE
win32yank.exe doesn't work, stays open when yanking to '*'/'+' registers

### ISSUE THREAD

**Issue by youngmit** [neovim/neovim#7989]
- `nvim --version`:
```
C:\Users\myoung\.config\nvim>nvim --version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Windows 10 15063.850

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

insert some text

"*yy
```

### Actual behaviour
New cmd window appears, running win32yank.exe. Window stays open and accepts input. Manually closing the window produces the message `clipboard: error invoking win32yank:`.

If I type anything into the win32yank window before closing it, that text ends up on the system clipboard, but none of the text that was yanked from nvim. So it appears that the win32yank executable isn't getting anything from stdin from nvim?

### Expected behaviour
Yanked text should be stored in the system clipboard. No win32yank window should pop up at all, I would think, though I've never used this feature on a functional installation in windows, so I don't know what the nominal behavior should be.

**Comment by justinmk** [comment]
You really tried `nvim -u NORC` ? It sounds like your 'shell' or related options are messed up.

**Comment by youngmit** [comment]
Absolutely positive. Reproduced on another machine. Same issue; win32yank pops up and just stays there.

**Comment by KillTheMule** [comment]
Could not reproduce with a vanilla 0.2.2 on windows 7.

**Comment by youngmit** [comment]
I might have stumbled upon something; I had been using neovim installed through the `scoop` package manager. If I remove that version, and run through the regular zip file, it works fine. So there must be something up with the way that scoop adds the neovim shim. Think this is something I should report to them?

**Comment by justinmk** [comment]
> So there must be something up with the way that scoop adds the neovim shim. 

Maybe check if they are changing shell settings:

    :verbose set shell? shellcmdflag? shellquote? shellredir? shellxquote? shellxescape? shellpipe?

> Think this is something I should report to them?

Yes.

**Comment by oblitum** [comment]
The same error [has appeared here](https://github.com/rhysd/NyaoVim/issues/131). I just use terminal and I started to get it too recently, I use neovim from pacman (ArchLinux on WSL).

**Comment by oblitum** [comment]
This is my `win32yank` script on WSL:

```
#!/bin/bash
/mnt/c/Users/francisco/Documents/WSL-Terminal/bin/win32yank.exe "$@" 2>/dev/null
```

I always worked flawless up to now.

**Comment by oblitum** [comment]
Ah, sorry, false alarm, my bad. I've upgraded [WSL-Terminal](https://github.com/goreliu/wsl-terminal) folder recently and forgot to add back the `win32yank.exe` executable.

**Comment by jsamuel1** [comment]
> ... I had been using neovim installed through the `scoop` package manager. ...

Did you get a solution to this @youngmit ?

neovim installed with scoop's environment:
`:verbose set shell? shellcmdflag? shellquote? shellredir? shellxquote? shellxescape? shellpipe?`

```
shell=cmd.exe
shellcmdflag=/s /c
shellquote=
shellredir=%s 2>&1
shellxquote="
shellxescape=
shellpipe=>%s 2>&1
```

**Comment by jsamuel1** [comment]
For anyone else getting this issue when using scoop.
It appears to be caused by scoop install win32yank .
If you remove the win32yank scoop package, then neovim will correctly use the version that is bundled with it, and succeed.
(I had installed win32yank explicitly for my Windows Subsystem for Linux environment)

**Comment by goyalyashpal** [comment]
> Think this is something I should report to them?

did you file it? if yes, then link?

**Comment by goyalyashpal** [comment]
> Ah, sorry, false alarm, my bad. I've upgraded [WSL-Terminal](https://github.com/goreliu/wsl-terminal) folder recently and forgot to add back the `win32yank.exe` executable.

hi @oblitum can you merge ur 3 comments into one 😃 and delete the remains?
