### ISSUE TITLE
Not a single screenshot on the website

### ISSUE THREAD

**Issue by dr3adl04d** [neovim/neovim#7997]
Not a single screenshot on the website, and today, look and feel of something people are spending time with a lot is really important. Most people don't ever install apps which they can't see first.
I suggest that this is looked into, as it drove me away already.

**Comment by justinmk** [comment]
It's planned, but we also need help. If you have a professional-looking screenshot please submit a PR at https://github.com/neovim/neovim.github.io

**Comment by bfredl** [comment]
Also terminal nvim doesn't really look anything different than vim. But I guess we can include screenshots from "fancy" UIs like gonvim and oni  to show what is possible.
