### ISSUE TITLE
:help command triggers FileType autocmds twice

### ISSUE THREAD

**Issue by bluekaiser** [neovim/neovim#8002]
- `nvim --version`: NVIM v0.2.3-244-gbfb21f3
- Vim (version: 8.0.960) behaves differently? yes
- Operating system/version: Linux/Ubuntu

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:autocmd FileType help echo "testing"
:help autocmd
```

### Actual behaviour
"autocmd.txt" [readonly] 1522L, 62595C
testing
testing
Press ENTER or type command to continue

### Expected behaviour
"autocmd.txt" [readonly] 1522L, 62595C
testing
Press ENTER or type command to continue

Would appear that :help command triggers FileType help autocmds twice, confirmed setting filetype manually to help (:set ft=help) only triggers once

**Comment by justinmk** [comment]
confirmed on  `0.2.3-610-ga6052c7`. And doesn't happen on Vim `8.0.1451` nor `7.4.1689`. Can someone bisect?

**Comment by stsewd** [comment]
I think https://github.com/vim/vim/commit/9049298f8d0bbc237b7c666c7ad6cdabe738e8fc and https://github.com/vim/vim/commit/868831f1224cfc17a4de21fb7386873254592308 solve this.

**Comment by nimitbhardwaj** [comment]
I want to work on this issue

**Comment by mhinz** [comment]
@nimitbhardwaj 

Sure, you can backport the patches [mentioned above](https://github.com/neovim/neovim/issues/8002#issuecomment-364817463). Read [Merging patches from upstream Vim](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim) on how to do that.
