### ISSUE TITLE
test/win: :diffget test fails on appveyor

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#8005]
https://github.com/neovim/neovim/pull/7917 contains a new test which tests the interaction of diffget/diffput with buffer updates. It fails on appveyor, due to reasons that seem unrelated to buffer updates. It doesn't fail on any other system, nor does it fail when manually trying to reproduce, so it somewhat looks like it's a problem of the environment. Should probably be investigated.

Here are some findings/ideas:
- The C code creates a file`tmp_diff` (among others) to test if diff works, and this file stays empty, although it should contain the diff. That's the reason `diffthis` throws an error and the test fails.
- The diff tool (which is shipped with neovim) on appveyor returns 0 (that is, the C function call that calls the shell that calls... returns 0, which should be the return value of the diff tool... it's ignored though), while when locally testing on linux it returns 1. Seems the tool is aware that there's a problem.
- Tried :let &shcf='/s /c' and :let &sxq='"' per justinmks suggestion to no avail.
- janlazo says:

> How does :diff escape the filenames for diff.exe? If the problem is shellescape, then setting diffexpr with a custom shellescape (ca5f2d7) for each filename, including the tempfile, should fix it. set shellcmdflag=/s/c shellxquote=\" is still required. That shellescape is not bullet-proof because of cmd.exe quirks (I have my own version to handle the quirks) but it should be enough for diff.exe

I did not investigate further because it does not seem like it's a problem of buffer updates, and I really want to land that PR.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/8378#issuecomment-434126716
