### ISSUE TITLE
Cannot map <c-/> or <c-?>

### ISSUE THREAD

**Issue by tterranigma** [neovim/neovim#8021]
- `nvim --version`: NVIM v0.2.3-712-g8b543d09d
- Vim (version: ) behaves differently? no
- Operating system/version: Arch linux
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:map <c-/> :blahblah
```

### Actual behaviour
When I hit Ctrl-/, it just searches.

### Expected behaviour
It should put :blahblah in neovim's command prompt.

I think this should have been reported before, but it was impossible for me to find the relevant issue using github's search.

**Comment by justinmk** [comment]
Depends on your terminal. Use https://vi.stackexchange.com/ for usage questions, not the bug tracker.

**Comment by tterranigma** [comment]
I didn't know it was a usage question.
