### ISSUE TITLE
Nvim characters are not cleared after exit

### ISSUE THREAD

**Issue by Sk11p1** [neovim/neovim#8025]
- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser


Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.0.1476) behaves differently? Yes
- Operating system/version: Arch Linux
- Terminal name/version: tmux/2.6
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
exit nvim
```

### Actual behaviour
The nvim ui characters aren't cleared
### Expected behaviour
There should not be nvim characters left in the terminal

This is what it looks like:
![main - zsh_003](https://user-images.githubusercontent.com/35905768/36357941-ca261492-14d3-11e8-83fe-82ce183fa3e7.png)

Other editors like vim and nano clear their ui after exit.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/7798#issuecomment-366547176
