### ISSUE TITLE
nvim not on alternate buffer and home/end keys not working with ncurses 6.1 in tmux

### ISSUE THREAD

**Issue by wilriker** [neovim/neovim#8027]
- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?
- Operating system/version: Arch Linux 4.15.3-2 with `ncurses` 6.1
- Terminal name/version: `st` 0.7 with `fish` 2.7.1 (also with `bash` 4.4.19(1)-release)
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
1) :e <any file with content><CR>
2) <End>
3) <Home>
4) :q<CR>
```

### Actual behaviour
1) File is opened
2) nothing
3) nothing
4) `nvim` TUI is scrolling one line up and the shell prompt appears below it.

### Expected behaviour
1) File is opened
2) Cursor moves to end of line
3) Cursor moves to beginning of line
4) `nvim` disappears and reveals the shell prompt as it looked before opening `nvim`.

------------------------------------------------
This issue started happening for me with the upgrade of `ncurses` to 6.1 and the terminfo files coming with it. I have a backup of the previous terminfo file for `tmux-256color` and it does not happen with this one.

I tried the following setups:
st -> (fish|bash) -> nvim: working
st -> (fish|bash) -> tmux -> (fish|bash) -> nvim: **not** working with `ncurses` 6.1 terminfo
st -> (fish|bash) -> tmux -> (fish|bash) -> nvim: working with `ncurses` pre 6.1 terminfo

I am not exactly sure if this is an issue of `nvim`, `tmux` or `ncurses` but as there were already issues in the past with `ncurses'` `tput (smkx|rmkx)` with `nvim` and `st` (which are solved by now) I start here. If this is **not** an issue of `nvim` please tell me (if you can) where to file this issue instead.

Best regards
Manuel

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/7798

can you try Nvim HEAD (0.2.3, development version)? We would like to confirm that the recent upgrade to unibilium fixes this.  Pre-builds here: https://github.com/neovim/neovim/releases/tag/nightly

**Comment by wilriker** [comment]
Hi @justinmk 

I tried the appimage version of the nightly build and it works there as expected. Any plans when it will be released? "No idea" is an accepted answer, too. ;-)

**Comment by wilriker** [comment]
P.S.: I have just checked the `neovim` package in Arch Linux and see that it already depends on `unibilium`. This is currently still version 1.2.1 but has been flagged out-of-date and 2.0.0 is currently in testing. So I guess as soon as `unibilium` package will be upgraded to 2.0.0 in Arch everything should work again also with `neovim` 0.2.2, shouldn't it?

**Comment by justinmk** [comment]
Soft deadline of the next milestone is always listed on https://github.com/neovim/neovim/milestones

**Comment by frol** [comment]
unibilium 2.0 from the community-testing repo does the trick (though I had to symlink `libunibilium.so` to `libunibilium.so.0` locally).

**Comment by jamessan** [comment]
> though I had to symlink libunibilium.so to libunibilium.so.0 locally

That's a bad idea.  The reason that the new version has a file named `libunibilium.so.4` is because it doesn't provide a compatible binary interface.  Things using unibilium need to be rebuilt against the new one.

**Comment by wilriker** [comment]
> Things using unibilium need to be rebuilt against the new one.
This is done altogether in community-testing, i.e. `neovim` and `libtermkey` are both rebuilt against the new `unibilium` and they will be released together into community repo once testing is finished.

**Comment by frol** [comment]
I know that it is a bad idea and usually that doesn't work, but it worked in this case.

I installed both neovim (0.2.2-2) and unibilium (2.0.0-1) from the community-testing, so it seems that neovim needs to be rebuilt once again:

```
$ ldd /usr/bin/nvim
        linux-vdso.so.1 (0x00007ffe9a7e3000)
        libuv.so.1 => /usr/lib/libuv.so.1 (0x00007f328444c000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f328422e000)
        libmsgpackc.so.2 => /usr/lib/libmsgpackc.so.2 (0x00007f3284027000)
        libvterm.so.0 => /usr/lib/libvterm.so.0 (0x00007f3283e18000)
        libtermkey.so.1 => /usr/lib/libtermkey.so.1 (0x00007f3283c0e000)
        libunibilium.so.4 => /usr/lib/libunibilium.so.4 (0x00007f32839fb000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f32836af000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f32834ac000)
        libluajit-5.1.so.2 => /usr/lib/libluajit-5.1.so.2 (0x00007f328323b000)
        libjemalloc.so.2 => /usr/lib/libjemalloc.so.2 (0x00007f3282dbc000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3282a05000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f32827fd000)
        libnsl.so.1 => /usr/lib/libnsl.so.1 (0x00007f32825e5000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f32823e1000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f3284b62000)
        libunibilium.so.0 => not found
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f32821ca000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3281e43000)
```

**Comment by wilriker** [comment]
For the sake of completeness: `unibilium` has been updated to 2.0.0 in Arch together with rebuilds of `neovim` and `libtermkey` and now everything is working again.

**Comment by DrPoldo** [comment]
I have installed neovim-0.2.2-6 and unibilium-2.0.0-1 on archlinux. It seams the problem is still there:

```
 ldd /usr/bin//nvim
        linux-vdso.so.1 (0x00007ffc65944000)
        libuv.so.1 => /usr/lib/libuv.so.1 (0x00007f2b53326000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f2b53108000)
        libmsgpackc.so.2 => /usr/lib/libmsgpackc.so.2 (0x00007f2b52f01000)
        libvterm.so.0 => /usr/lib/libvterm.so.0 (0x00007f2b52cf2000)
        libtermkey.so.1 => /usr/lib/libtermkey.so.1 (0x00007f2b52ae8000)
        libunibilium.so.4 => /usr/lib/libunibilium.so.4 (0x00007f2b528d5000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f2b52589000)
        libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f2b52386000)
        libluajit-5.1.so.2 => /usr/lib/libluajit-5.1.so.2 (0x00007f2b52115000)
        libjemalloc.so.2 => /usr/lib/libjemalloc.so.2 (0x00007f2b51c96000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f2b518df000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f2b516d7000)
        libnsl.so.1 => /usr/lib/libnsl.so.1 (0x00007f2b514bf000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2b512bb000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f2b53a40000)
        libunibilium.so.0 => not found
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f2b510a4000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f2b50d1d000)
```
```
$nvim
nvim: error while loading shared libraries: libunibilium.so.0: cannot open shared object file: No such file or directory
```

**Comment by jamessan** [comment]
@DrPoldo You need to talk to the Arch folks, not us.  Something is still trying to load the older version of unibilium, as the error message states.  Whatever that is needs to get rebuilt against the new unibilium.  There's nothing we can do about that.

**Comment by DrPoldo** [comment]
@jamessan Ok, thanks. Anyway @frol workaround works:
`sudo ln -s /usr/lib/libunibilium.so.4 /usr/lib/libunibilium.so.0`

**Comment by jamessan** [comment]
@DrPoldo And as I mentioned earlier, that's a terrible idea.  Fix the actual problem instead. :)

**Comment by wilriker** [comment]
FYI: I cannot reproduce this issue on any of my Arch machines.

**Comment by z3ntu** [comment]
I have the same problem on Alpine Linux

* neovim-0.3.1-r1
* unibilium-2.0.0-r0
* ncurses-6.1_p20180818-r1

And `$TERM` is `tmux-256color`

**Comment by jamessan** [comment]
> I have the same problem on Alpine Linux
> 
>     * neovim-0.3.1-r1
> 
>     * unibilium-2.0.0-r0
> 
>     * ncurses-6.1_p20180818-r1

That's possibly related to https://github.com/mauke/unibilium/pull/39 then.  Does it work better if you apply my patch and rebuild unibilium?

**Comment by z3ntu** [comment]
@jamessan Yes, that fixes the issue! Should I send a PR to Alpine to include this patch in the repos?
