### ISSUE TITLE
Cannot get clipboard to work through SSH, lemonade, -X xsel, -X xclip

### ISSUE THREAD

**Issue by onaret** [neovim/neovim#8028]
- `nvim --version`:

> NVIM v0.2.3-718-g00665d3c7
> Build type: RelWithDebInfo
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/user/tools/neovim/build/config -I/home/onaret/unshared_tools/neovim/src -I/home/user/tools/neovim/.deps/usr/include -I/usr/include -I/home/user/tools/neovim/build/src/nvim/auto -I/home/user/tools/neovim/build/include
> Compiled by usert@pc
> 
> Features: +acl +iconv +jemalloc +tui 
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/local/share/nvim"

- Operating system/version: Debian 9
- Terminal name/version:rxvt-unicode-256color
- `$TERM`:rxvt-unicode-256color

### Steps to reproduce

```
nvim -u NORC any_file.txt  
```

If I try to copy some text to the clipboard by doing

```
"*y
```

It does not work. 
I tried with different clipboard implementations, here are the different errors I've got:

- Through ssh using lemonade, it returns this error:

> clipboard: error invoking lemonade: 2018/02/19 14:06:35 dial tcp [::1]:2489: getsockopt: connection refused 2018/02/19 14:06:35 Fall back to localhost exit status 1

- Through ssh using -X and xsel, it returns this error:

> clipboard: error invoking xsel: xsel: BadAccess (attempt to access private resource denied): Resource temporarily unavailable

- Through ssh using -X after uninstalling xsel and installing xclip, it returns this error

> clipboard: error invoking xclip: Waiting for selection requests, Control-C to quit   Waiting for s...angeProperty)   Serial number of failed request:  12   Current serial number in output stream:  13

**Comment by justinmk** [comment]
Is this a usage question or a bug report?

**Comment by onaret** [comment]
Hello,
This is a bug report a priori

**Comment by bfredl** [comment]
Easy to check: does xsel also have the same issue outside nvim? Then it is not nvim bug. I would guess some kind of xauth problem with ssh X11 forwarding.

**Comment by justinmk** [comment]
Please keep bug reports "a posteriori", i.e. please do the work of confirming that it's a bug in Nvim before reporting to the Nvim bug tracker.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/xsel-error-in-ssh-neovim-0-5/960/1

**Comment by sisrfeng** [comment]
I am using `nvim`  inside `tmux`, and `ssh` to remote machine through `mobaxterm` ,  and `xsel` can copy. But this error (false alarm? )  appears every time I copy in nvim, and the error does not appear outside nvim (but still in tmux. I  have tmux-yank installed)
![image](https://user-images.githubusercontent.com/53520949/141642605-0e7f6c54-74ba-4872-a0b3-94c284aaa7c5.png)

![image](https://user-images.githubusercontent.com/53520949/141642675-80ca23c4-586e-4842-a81b-fea4c699c984.png)

**Comment by sisrfeng** [comment]
put
```
ForwardX11 yes
ForwardX11Trusted yes
```
in  file ~/.ssh/config
Solved
