### ISSUE TITLE
Home and End keys not working in Tmux and TERM=screen-256color

### ISSUE THREAD

**Issue by frol** [neovim/neovim#8032]
- `nvim --version`: v0.2.2
- Vim (version: 8.0.1476) behaves as expected (in contrast to neovim)
- Operating system/version: Arch Linux (Gnome 3)
- Terminal name/version: tmux 2.6 in Gnome Terminal 3.26.2
- `$TERM`: `screen-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
i1234<ESC><HOME>
```

### Actual behaviour

`<HOME>` (and `<END>`) doesn't put the cursor to the beginning of the line while `<CTRL>+<HOME>` works fine (moves the cursor to the beginning of the *file*).

### Expected behaviour

`<HOME>` should put the cursor to the beginning of the line.

### Extra notes

I have read the related issues (#4308 and #6014) and FAQ on this matter, but given that I already have                 `TERM=screen-256color`, they didn't help.

In the same session, vim works as expected.

I have tried setting `TERM` to `xterm-256color`, `xterm`, and `screen` and it turned out that `screen` value fixes the issue with `<HOME>` / `<END>` buttons, but it doesn't seem correct to me, so I decided to report it.

I want to also note that everything used to work just fine up until a few days ago, and I haven't touched any configs and I don't recall updates either to neovim nor tmux, but the fact that everything but neovim works just fine forced me to write this issue just in case if I am not alone.

Any idea on how I can inspect the issue?

**Comment by mhinz** [comment]
Does `TERM=tmux-256color` make a difference?

**Comment by frol** [comment]
@mhinz `TERM=tmux-256color` doesn't help, but `TERM=tmux` does the trick just like `TERM=screen`.

**Comment by mhinz** [comment]
The next release will automatically use a built-in termcap entry if tmux is detected but `$TERM` is not `tmux-256color`. That should avoid such issues.

Tmux used to use `screen` and `screen-256color` in the past because it was widely available. But it was still meant for screen. Modern ncurses versions ship with `tmux` and `tmux-256color`.

**Comment by justinmk** [comment]
> I want to also note that everything used to work just fine up until a few days ago

https://github.com/neovim/neovim/issues/8027

**Comment by frol** [comment]
@justinmk Oh, thank you! Sorry for the duplicate.

I confirm that unibilium 2.0 fixes the issue (installed from the community-testing Arch repo)

**Comment by cemeyer** [comment]
Hm, the autodetection seems kind of broken in GNU screen:

nvim: 0.4.2
unibilium: 2.0.0
term: terminology 1.4.1
screen: 4.7.0

.screenrc: `term screen-256color`

Outside screen: `TERM` is `xterm`, HOME/END keys work in nvim.

Inside screen: `TERM` is `screen-256color`, HOME/END keys do not work.  It seems nvim ignores `TERM`?  From an example in 7798,

```
nvim -V3log
:q
```

Shows:

```
--- Terminal info --- {{{
&term: builtin_xterm
Description: xterm with 256 colors
Aliases: xterm-256color
...
```

With the wrong (xterm) codes for key_home and key_end.  `infocmp` in the same screen session shows the correct `kend` and `khome` sequences.

Why does nvim think it knows better than my (correct) `$TERM`?  Here's the wrinkle: `XTERM_256_COLORS=1` is inherited from the parent environment inside `screen`.  And apparently that overrides `TERM` for nvim's purposes.

`unset XTERM_256_COLORS ; nvim -V3log` ⇒

```
--- Terminal info --- {{{
&term: builtin_screen
Description: GNU Screen with 256 colors
Aliases: screen-256color
```

So... I can hack around this with `unsetenv XTERM_256_COLORS` in `.screenrc`.  But I wonder if ignoring `TERM` if `XTERM_256_COLORS` is set is really the right thing to do here?
