### ISSUE TITLE
doc: add NVIM_LOG_FILE to man page

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8043]
I think it would be good to mention `NVIM_LOG_FILE` in the man page with the other `ENVIRONMENT` variables.

The description should be base on what `:h $NVIM_LOG_FILE` (https://github.com/neovim/neovim/blob/ec02d9aad6b3015b1802476521a65234c70b0574/runtime/doc/starting.txt#L1386-L1392) has, which could need some revisit, e.g. how this can be used by plugins - should they just write to the file or are there wrapper functions?

**Comment by justinmk** [comment]
> should they just write to the file or are there wrapper functions?

The plan is to add a real API. For use by rplugins, too.
