### ISSUE TITLE
TUI: wrong terminfo value for "standout"

### ISSUE THREAD

**Issue by shaggyrogers** [neovim/neovim#8054]
### Issue description

NVIM v0.2.3 does not correctly send particular terminfo entries to the terminal.

- Version
NVIM v0.2.3-dev (22 Feb 2018, [full version info](https://github.com/neovim/neovim/files/1750804/nvim-version-info.txt))

- Does not affect VIM
Vi IMproved 8.0 (2016 Sep 12, [full version info](https://github.com/neovim/neovim/files/1750742/vim-version-info.txt))

- Operating system/version
Ubuntu 17.10 x86_64 

- Kernel version
4.13.0-32-generic

- Terminal name/version
kitty 0.7.1

- `$TERM`
xterm-kitty

### Steps to reproduce
```
git clone https://github.com/kovidgoyal/kitty kitty
cd kitty/terminfo
nvim kitty.terminfo
rmso=\E[27m, --> rmso=\E[24m,
smso=\E[7m, --> smso=\E[58;2;233;32;32m,
:wq
tic kitty.terminfo -s
nvim -u NORC
:hi CursorLine cterm=standout,underline term=standout,underline gui=standout,underline
:set cursorline
```
### Actual behaviour

'standout,underline' is displayed as 'reverse,underline'.

```
nvim -u NORC
:hi CursorLine cterm=standout,underline term=standout,underline gui=standout,underline
:set cursorline
```
![screenshot from 2018-02-23 17-53-45](https://user-images.githubusercontent.com/8199291/36581732-64a9e01c-1866-11e8-85c7-249d03588150.png)

### Expected behaviour

'standout,underline' should be displayed as a red underline.

```
vim -u NONE
:hi CursorLine cterm=standout,underline term=standout,underline gui=standout,underline
:set cursorline
```

![screenshot from 2018-02-23 17-53-57](https://user-images.githubusercontent.com/8199291/36581735-67edb014-1866-11e8-8e99-4882b626e7f6.png)

**Comment by mhinz** [comment]
Please try `nvim -V3log`, `:echo &term`. Then quit and have a look at the `Terminal` section in the `log` file.

Does it show the proper escape sequences?

**Comment by justinmk** [comment]
This is just something we never implemented, should be easy to fix.

https://github.com/neovim/neovim/blob/f3f1970597211c784190c4a1e1990d2386ac76a1/src/nvim/tui/tui.c#L453

**Comment by shaggyrogers** [comment]
Ah, that explains it. The escape sequences are correct:
```
enter_standout_mode       smso       = <Esc>[58;2;233;32;32m
exit_standout_mode        rmso       = <Esc>[24m
```
I'll try the changes @justinmk suggested and report back soon.

**Comment by blueyed** [comment]
Standout was not working for me: can you please review/check https://github.com/neovim/neovim/pull/8708?
