### ISSUE TITLE
luacheck-scm-1.rockspec doesn't exist so 0.2.x doesn't build

### ISSUE THREAD

**Issue by xentac** [neovim/neovim#8056]
- `nvim --version`: v0.2.0 to v0.2.2
- Vim (version: ) behaves differently?
Not sure
- Operating system/version: Alpine Linux 3.7 (built with Docker image python:3.6.2-alpine)
- Terminal name/version: xfce4-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Build neovim from source with no dependecies downloaded
(Snipped from my Dockerfile)
```
RUN cd /root \
    && git clone https://github.com/neovim/neovim \
    && cd neovim && git checkout $NEOVIM_VERSION \
    && make CMAKE_EXTRA_FLAGS="-DENABLE_JEMALLOC=OFF -DCMAKE_INSTALL_PREFIX=/usr/local" CMAKE_BUILD_TYPE=RelWithDebInfo \
    && make install \
    && python3 -mpip install neovim
```

### Actual behaviour
Snipped from build output:
```
mediator_lua 1.1.2-0 is now installed in /root/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)
                                                                                                                                            
busted 2.0.rc12-1 is now installed in /root/neovim/.deps/usr (license: MIT <http://opensource.org/licenses/MIT>)
                                                                  
make[3]: Leaving directory '/root/neovim/.deps'   
[ 51%] Built target busted                             
make[3]: Entering directory '/root/neovim/.deps'
Scanning dependencies of target luacheck                                                                                          
make[3]: Leaving directory '/root/neovim/.deps'                                               
make[3]: Entering directory '/root/neovim/.deps'                        
[ 52%] Generating usr/bin/luacheck               

Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/mpeterv/luacheck/master/luacheck-scm-1.rockspec - luacheck-scm-1.rockspec
make[3]: *** [usr/bin/luacheck] Error 1
CMakeFiles/luacheck.dir/build.make:60: recipe for target 'usr/bin/luacheck' failed
make[3]: Leaving directory '/root/neovim/.deps'
CMakeFiles/Makefile2:322: recipe for target 'CMakeFiles/luacheck.dir/all' failed
make[2]: Leaving directory '/root/neovim/.deps'
```
### Expected behaviour
Not an error

A [recent commit](https://github.com/mpeterv/luacheck/commit/3e42d4238602ad9aa6bda561add41773cd3e1b14) to luacheck changed the name of the rockspec file so neovim has been unbuildable since then.

**Comment by xentac** [comment]
https://github.com/neovim/neovim/commit/e2afcfb020fa16b465dd25d3455cd00487e68915 was the fix in nightly

**Comment by jamessan** [comment]
We can't go back in time and re-release older versions.  Either don't use the bundled dependencies (which is what I would recommend for anything other than neovim development) or build from git.

As you mentioned, this has already been fixed so there's no reason for a new issue.

**Comment by xentac** [comment]
I was kind of hoping you would release a v0.2.3 with the fix in it so I didn't have to follow nightly... I was under the impression that nightly had a lot more changes in it than v0.2.
