### ISSUE TITLE
Cursor shape glitches in Konsole terminal windows, but only when running as root

### ISSUE THREAD

**Issue by lpar** [neovim/neovim#8057]
- `nvim --version`:

NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_UNIBI_HAS_VAR_FROM -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.2.2/build/config -I/builddir/build/BUILD/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.2.2/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.2.2/build/include
Compiled by mockbuild

- Operating system/version: Fedora 27
- Terminal name/version: Konsole
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
/usr/bin/nvim -u NORC
# Type `a`, verify correct behavior, quit
sudo -i
/usr/bin/nvim -u NORC
# Type `a`, see incorrect behavior, quit
```

### Actual behaviour

When running as my user ID, cursor changes shape and nvim goes into append mode.

When running as root (after `sudo -i`), cursor does not change shape, and I get a `q` under the cursor due to cursor shape change control codes not being interpreted correctly.

Same terminal, different tabs. Same $TERM.

### Expected behaviour

I would expect the behavior to be the same whether running as me or as root.

Obviously there's the workaround of disabling `guicursor`, but I'm really curious why it only does it when running as root.

**Comment by justinmk** [comment]
There must be something in your shell config that isn't sourced by the root user. It's up to you to compare your environment and narrow it down, nothing we can do here.

Note that Nvim 0.2.3 (current HEAD/unreleased) supports `TERM=konsole-256color` which should help avoid fragile situations like this. https://neovim.io/doc/user/term.html#$TERM
