### ISSUE TITLE
Neovim core dumped

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#8058]
- `nvim --version`: NVIM v0.2.3-747-g6bbec71fd
- Vim (version: ) behaves differently? yes
- Operating system/version: archlinux
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

sorry I can not reproduce from `nvim -u NONE`

```
nvim -u NORC

```

### Actual behaviour

neovim core dumped

```
nvim: /home/wsdjeg/sources/neovim/src/nvim/api/private/helpers.c:89: try_leave: Assertion `current_exception == NULL' failed.
```

**Comment by bfredl** [comment]
related: #7876 #7881

**Comment by wsdjeg** [comment]
sorry for duplicate issue
