### ISSUE TITLE
How to remove status bar 

### ISSUE THREAD

**Issue by KnownAsDon** [neovim/neovim#8059]
- Neovim Version 0.2.2
- Operating system: Manjaro i3 17.1.2
- Terminal name/version: rxvt-unicode 

I have moved from vim to neovim for about 6 months and I freeking love it. I have alawys used gnome terminal and I've decorated it to my likings. But now I have switched to rxvt-unicode and the theme I've installed on it seems enough for neovim too, it is just clean. If you can help me remove that and I can have the line:charcter and the position percentage at the very right bottom of the neovim I'd greatly appreciate it.

**Comment by mhinz** [comment]
Use `:set laststatus=0 ruler`.

And please understand that we use GitHub for development. For usage questions use [SO](stackoverflow.com) or visit [our Gitter channel](gitter.im/neovim/neovim).
