### ISSUE TITLE
Failed to parse ShaDa file

### ISSUE THREAD

**Issue by pgrekovich** [neovim/neovim#8064]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently?  Vim 8.0 works well
- Operating system/version: Fedora 27
- Terminal name/version: GNOME terminal 3.26.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 86
Press ENTER or type command to continue
```
nvim will open and work well, but after the `:q`
```
E576: Failed to parse ShaDa file: extra bytes in msgpack string at position 86
E136: Did not rename /home/MY_USER_NAME/.local/share/nvim/shada/main.shada.tmp.j because /home/MY_USER_NAME/.local/share/nvim/shada/main.shada does not looks like a ShaDa file
E136: Do not forget to remove /home/MY_USER_NAME/.local/share/nvim/shada/main.shada.tmp.j or rena
me it manually to /home/MY_USER_NAME/.local/share/nvim/shada/main.shada.
```
### Expected behaviour

nvim don't show me annoying messages and work well

**Comment by blueyed** [comment]
For debugging the contents of `~/.local/share/nvim/shada/main.shada` would be required.

Can you provide it here, please?  (should only need the first 100 bytes probably).

**Comment by pgrekovich** [comment]
@blueyed 
```
01ce 5a91 c786 4885 a967 656e 6572 6174
6f72 c404 6e76 696d a776 6572 7369 6f6e
c40b 4e56 494d 2076 302e 322e 32a9 6d61
785f 6b62 7974 650a a370 6964 cd67 16a8
656e 636f 6469 6e67 c405 7574 662d 3808
ce5a 91c7 7f24 82a1 66c4 1c74 6572 6d3a
2f2f 2e2f 2f32 3633 3932 3a2f 7573 722f
6269 6e2f 7a73 68a1 6c00 08ce 5a91 c786
2181 a166 c41c 7465 726d 3a2f 2f2e 2f2f
3236 3339 323a 2f75 7372 2f62 696e 2f7a
7368 0300 0391 c400 0ace 5a91 c786 2181
a166 c41c 7465 726d 3a2f 2f2e 2f2f 3236
3339 323a 2f75 7372 2f62 696e 2f7a 7368
0ace 5a91 c780 2482 a166 c41c 7465 726d
3a2f 2f2e 2f2f 3236 3339 323a 2f75 7372
2f62 696e 2f7a 7368 a16e 2e0b ce5a 91c7
8021 81a1 66c4 1c74 6572 6d3a 2f2f 2e2f
2f32 3633 3932 3a2f 7573 722f 6269 6e2f
7a73 6804 ce5a 91c7 8605 9200 c401 71
```

**Comment by ZyX-I** [comment]
Can you reproduce with a latest master? With this main.shada my Neovim only complains about mark entry having invalid line number (error is gone after quiting and using the same file again, AFAIR this jumplist issue was already fixed) and is otherwise fine. Generally such error is expected in case of damaged ShaDa file and complaining about it is useless without providing steps to *create* such file in first place, but in your case file does not look like damaged.

**Comment by pgrekovich** [comment]
@ZyX-I ok, I built last version from master, and neovim works well. Looks like its 0.2.2 version problem, or rpm-package. Thanks for the help.
