### ISSUE TITLE
Floobits warnings all the time

### ISSUE THREAD

**Issue by tekknolagi** [neovim/neovim#8065]
- `nvim --version`:
```
willow% nvim --version
NVIM v0.2.3-532-g2569fabf0
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/max/Documents/Dev/neovim/build/config -I/home/max/Documents/Dev/neovim/src -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/home/max/Documents/Dev/neovim/.deps/usr/include -I/usr/include -I/home/max/Documents/Dev/neovim/build/src/nvim/auto -I/home/max/Documents/Dev/neovim/build/include
Compiled by max@willow

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
Vim doesn't have these errors at all.
- Operating system/version:
```
willow% lsb_release -irc
Distributor ID:	Ubuntu
Release:	18.04
Codename:	bionic
```
- Terminal name/version: **terminator 1.91**
- `$TERM`: **xterm-256color**

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

It happens when running that command. Same thing. Just no color.

### Actual behaviour

I get warnings about floobits at every keystroke:

https://asciinema.org/a/t6uGPFkdCgCBiR2jPuGaYHF74

### Expected behaviour

Just... normal editing.

**Comment by blueyed** [comment]
Try `:UpdateRemotePlugins`.

**Comment by blueyed** [comment]
Also pasting the actual errors (via `:messages`) would be easier to review and find them.

**Comment by tekknolagi** [comment]
Holy cow, `:UpdateRemotePlugins` fixed it. Thank you! I've been wrestling with this for a while.

How come this sort of thing popped up with no warning? I hadn't touched anything Floobits-related in many months.

**Comment by blueyed** [comment]
I don't know what Floobits is after all, but know these kind of errors from when a remote plugin needs to be updated.
Please consider closing this issue then.

**Comment by tekknolagi** [comment]
Thank you for closing -- sorry for missing this.
