### ISSUE TITLE
Text overlays

### ISSUE THREAD

**Issue by SevereOverfl0w** [neovim/neovim#8068]
It would be very useful to have a safe API for text overlays.

This could be used by plugins to implement behaviour like this without actually modifying the buffer, which has corruption risks.

![](https://camo.githubusercontent.com/de52369c7356b9121f6983fd574c329470836e28/687474703a2f2f692e696d6775722e636f6d2f384167726449332e676966)

A further extension to this might be to support rich ui types (dropdowns) here, for graphical editors built on top of neovim. This is implemented in an Atom plugin in the same ecosystem, for example:

![](https://github.com/jasongilman/proto-repl/raw/master/images/inline_results.gif)

I can't see a real-world example of this being implemented mid-line, so perhaps it's sufficient to support "ghost" text at the end of lines, as `conceal` can already be used to overlay onto text which already exists (see vim-sneak for an example).

This perhaps has some overlap with work to implement highlights beyond the end of line, see the limitation in https://github.com/mhinz/vim-halo with the shapes which aren't `line`.

**Comment by bfredl** [comment]
Displaying text after end of line should be feasible (there was even a bug in `matchaddpos()` that allowed this vim/vim#2388, but of course doesn't count as "safe API"). `win_line` already has code for adding `extra` text for various occations (it also allowed in middle of line, but then it messes up cursor position, so much more complicated), in addition we probably want flexible highlighting to work (`matchaddpos()` hack only supports `Conceal`).

For dropdowns, building on floating windows #6619 could be an idea. First iteration doesn't have any reliable way to "tie" a float to a buffer position, but it something that could be added.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/1767

**Comment by SevereOverfl0w** [comment]
I saw 1767, but it didn't actually mention text overlays in the description, so I wasn't certain it covered this.

On February 26, 2018 8:48:52 AM GMT+00:00, "Justin M. Keyes" <notifications@github.com> wrote:
>see https://github.com/neovim/neovim/issues/1767
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neovim/neovim/issues/8068#issuecomment-368429227

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bfredl** [comment]
@SevereOverfl0w The basic functionallity (post-EOL annotations) is now available in master (#8180)
