### ISSUE TITLE
:terminal flooded by output (`yes`) does not respond to input

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#8071]
- `nvim --version`: NVIM v0.2.3-768-gf72630b78

### Steps to reproduce using `nvim -u NORC`

Just run some terminal command that produces a lot of output, enter normal mode, and try to scroll up. The cursor in normal mode used to not track the last line of terminal output, but as of a recent commit, it does.

**Comment by justinmk** [comment]
What do you mean "try to scroll up"? A single `k` or any other means of moving away from the last line, should be enough to stop following output.

**Comment by Alok** [comment]
I realize that the issue I'm thinking of is different from how I phrased it.

If I run a command that prints a lot of output (like `yes`) and then enter normal mode, the text output is fast enough that my vim instance locks up and becomes laggy. This is happening with the latest build from `master` on 2 machines running macos 10.11.6 and ubuntu 16.04.

**Comment by justinmk** [comment]
> If I run a command that prints a lot of output (like yes) and then enter normal mode, the text output is fast enough that my vim instance locks up and becomes laggy

Confirmed using my personal config with master as well as 27a577586eac (didn't try going further back).

Does _not_ happen with `nvim -u NONE` nor `nvim -u NORC`, so maybe it's related to autocmds or other settings which further slow things down.

https://github.com/neovim/neovim/pull/5396 addressed a similar problem for `:!` (try `:!yes`, you should have no problem canceling it via ctrl-c).

**Comment by Alok** [comment]
`!:yes` floods in a similar way.

**Comment by justinmk** [comment]
How long is "a while"? Did you map ctrl-c?

**Comment by Alok** [comment]
A few seconds, though I do have a few mappings that use <c-c> as a prefix, so that's probably it.

**Comment by justinmk** [comment]
A few seconds isn't bad. It used to take minutes. `yes` produces GB of data ...

**Comment by nimitbhardwaj** [comment]
This is working fine, where is the problem?
