### ISSUE TITLE
Neovim build error with unibilium 2.0.0

### ISSUE THREAD

**Issue by xentac** [neovim/neovim#8078]
- `nvim --version`: nightly
- Vim (version: ) behaves differently? N/A
- Operating system/version: Alpine 3.7 (from docker image python:3.6.4-alpine)
- Terminal name/version: xfce4-terminal 0.8.5.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Have unibilium 2.0.0 installed. Build neovim.
Snip from my dockerfile
```
RUN cd /root && \
  git clone https://github.com/neovim/libtermkey.git && \
  cd libtermkey && \
  make && \
  make install && \
  cd ../ && rm -rf libtermkey

RUN cd /root && \
  git clone https://github.com/neovim/libvterm.git && \
  cd libvterm && \
  make && \
  make install && \
  cd ../ && rm -rf libvterm

RUN cd /root && \
  git clone https://github.com/neovim/unibilium.git && \
  cd unibilium && \
  make && \
  make install && \
  cd ../ && rm -rf unibilium

RUN cd /root \
    && git clone https://github.com/neovim/neovim \
    && cd neovim && git checkout $NEOVIM_VERSION \
    && make CMAKE_EXTRA_FLAGS="-DENABLE_JEMALLOC=OFF -DCMAKE_INSTALL_PREFIX=/usr/local" CMAKE_BUILD_TYPE=RelWithDebInfo \
    && make install \
    && python3 -mpip install neovim
```

### Actual behaviour
Many errors with macro expansion of .i member
```
/root/neovim/src/nvim/tui/tui.c:990:9: note: in expansion of macro 'UNIBI_SET_NUM_VAR'
         UNIBI_SET_NUM_VAR(data->params[0], (int)count);
         ^
/root/neovim/src/nvim/tui/tui.c:62:42: error: 'unibi_var_t {aka struct <anonymous>}' has no member named 'i'
 #define UNIBI_SET_NUM_VAR(var, num) (var).i = (num);
                                          ^
/root/neovim/src/nvim/tui/tui.c:997:9: note: in expansion of macro 'UNIBI_SET_NUM_VAR'
         UNIBI_SET_NUM_VAR(data->params[0], -(int)count);
         ^                               
/root/neovim/src/nvim/tui/tui.c: In function 'unibi_goto':
/root/neovim/src/nvim/tui/tui.c:62:42: error: 'unibi_var_t {aka struct <anonymous>}' has no member named 'i'
 #define UNIBI_SET_NUM_VAR(var, num) (var).i = (num);    
                                          ^
/root/neovim/src/nvim/tui/tui.c:1260:3: note: in expansion of macro 'UNIBI_SET_NUM_VAR'
   UNIBI_SET_NUM_VAR(data->params[0], row);
   ^                         
/root/neovim/src/nvim/tui/tui.c:62:42: error: 'unibi_var_t {aka struct <anonymous>}' has no member named 'i'
 #define UNIBI_SET_NUM_VAR(var, num) (var).i = (num);
                                          ^            
/root/neovim/src/nvim/tui/tui.c:1261:3: note: in expansion of macro 'UNIBI_SET_NUM_VAR'
   UNIBI_SET_NUM_VAR(data->params[1], col);
```
### Expected behaviour
A successful build

https://github.com/mauke/unibilium/commit/b42315b792e48b10602eec1a4cc8e4f12d5db667 changed the members of unibi_var_t and was merged into 2.0.0.

https://github.com/mauke/unibilium/commit/e3b16d6219ca1cb92d98b1d9cc416b49a3ac468e mentions the only official access method is through helpers now.

Taking another look, it seems that I'm building from neovim/unibilium which shouldn't have the 2.0.0 code... I'm now more confused. Suggestions welcome.

**Comment by jamessan** [comment]
You're installing dependencies manually but then not disabling Neovim's own build of its dependencies.  Our build already detects whether unibilium has the accessors and uses them, if available.

https://github.com/neovim/neovim/blob/611351677dba450fc1a312061572c44c7e3d6482/CMakeLists.txt#L354-L365

It looks like we're basing the detection on the version of unibilium you already installed but then build against the bundled unibilium.

The simple fix is for your Dockerfile to either stop building the bundled dependencies we'll already build or to tell us not to build the ones that you've decided to manually build (`DEPS_CMAKE_FLAGS="-DUSE_BUNDLED_UNIBILIUM=OFF -DUSE_BUNDLED_LIBTERMKEY=OFF -DUSE_BUNDLED_LIBVTERM=OFF`).

I think we may have another issue tracking this confusion of system vs. bundled dependencies.

**Comment by xentac** [comment]
Interestingly, if I remove the hand built dependencies neovim complains that it can't find them during the configure step. Even though I see the deps being built higher up. When I get a chance I will upload a build log, possibly that's a different issue.

Disabling the bundled libs with your DEPS_CMAKE_FLAGS suggestion worked great.

**Comment by hasufell** [comment]
I have the same problem. I passed `-DUSE_BUNDLED_UNIBILIUM=OFF -DUSE_BUNDLED_LIBTERMKEY=OFF -DUSE_BUNDLED_LIBVTERM=OFF` and also removed `third-party` directory, but I get the same error: https://gist.github.com/hasufell/cccc04d49ca7cff39d7d9d88022f8ed0
