### ISSUE TITLE
Em-dash width is one character

### ISSUE THREAD

**Issue by BatmanAoD** [neovim/neovim#8082]
- `nvim --version`:
```
NVIM v0.2.3-770-gb55c2b2e5
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
- Vim (8.0: ) behaves differently? No
- Operating system/version: Windows 10
- Terminal name/version: ConEmu (but I *believe* this is irrelevant)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

Copy this character: `—`

Then paste:

```
"+p
```

(In a non-Windows environment, the character may be in a different register.)

### Actual behaviour

Dash character takes up exactly one column.

### Expected behaviour

Dash character width exceeds one column.

**Comment by jamessan** [comment]
According to [Unicode](https://github.com/neovim/neovim/blob/611351677dba450fc1a312061572c44c7e3d6482/unicode/EastAsianWidth.txt#L902), U+2014 is ambiguous width.

You can use the [`'ambiwidth'`](https://neovim.io/doc/user/options.html#'ambiwidth') option to control how Vim treats characters with ambiguous width.

**Comment by BatmanAoD** [comment]
@jamessan Thanks; I didn't know about that option!

...looks like I don't have a font installed that permits the dash character to fill the entire space, though, unfortunately.

**Comment by BatmanAoD** [comment]
Actually, it appears that the column-width for a given font is the width of the widest character in the font (or something like that), so as far as I can tell it's impossible to make the em-dash actually cover more than a single column's worth of space, regardless of font. (Forcing `Guifont! Arial` is how I tested this.)
