### ISSUE TITLE
jobs: stdout and stderr callbacks are triggered always

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8083]
`call jobstart(['true'], {'on_stdout': {->execute('echom string(a:000)', 1)}})` should not display anything, i.e. the callback get not triggered, but it gets triggered with `['']` for a:2.

(via https://github.com/neovim/neovim/issues/7913#issuecomment-369395660)

- `nvim --version`: v0.2.3-754-g4a8f08197
- Vim (version: 8.0.1542) behaves differently? Yes. the callback is not triggered.

**Comment by bfredl** [comment]
This signals EOF and is documented behavior.

**Comment by blueyed** [comment]
@bfredl 
Is it really needed though?

FWIW, Vim also does not trigger it with `'mode': 'raw'` (what is more compatible to Neovim's mode).

**Comment by bfredl** [comment]
How would the user otherwise know when the stream has no more data? What would be the point of hiding information in the stream API in the first place? If you don't care about streamed output use `stdout_buffered`.

**Comment by blueyed** [comment]
With `stdout_buffered` you also get `['']` - which at least is consistent.
The user would know when also listening for the `exit` callback.

You have a point that it can be useful when only listening on the streams though, and it is the documented behaviour (`:h on_data`), so I am closing it for now.

Thanks for your input!

**Comment by bfredl** [comment]
Also note a process can close its streams long before it exits, so `on_exit` doesn't really cover this.

**Comment by blueyed** [comment]
Makes sense, and I see it as an advantage over Vim by now.. :)
