### ISSUE TITLE
Running shell commands in previous screen

### ISSUE THREAD

**Issue by skywind3000** [neovim/neovim#8087]
- `nvim --version`: v0.2.3-776-g3d2f4154b
- Vim (version: ) behaves differently? yes
- Operating system/version: Debian 9 x64
- Terminal name/version: SecureCRT 8.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:! ls
```

### Actual behaviour

the `ls` displays its output right below the vim's tui, and the tui has been scrolled up.

### Expected behaviour

Vim's behaviour
Switch to the previous screen (which is before starting vim), run the command, and return back to vim's tui screen.

**Comment by bfredl** [comment]
Note for the moment nvim behaves more or less the same as gvim. We don't want to add code just to replicate all differences between terminal vim and gvim. What is planned however is using `:terminal` for `:!` so interactive commands are supported (regardless of GUI/TUI).

**Comment by bfredl** [comment]
Ref #1496 #5431. Covered by existing issues so closing. Please continue discussion there.
