### ISSUE TITLE
Incorrect fixed-height window behavior

### ISSUE THREAD

**Issue by mrbiggfoot** [neovim/neovim#8096]
- `nvim --version`:
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/lib64/ccache/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/andrew/projects/neovim/neovim-nightly/build/config -I/home/andrew/projects/neovim/neovim-nightly/src -I/home/andrew/projects/neovim/neovim-nightly/.deps/usr/include -I/usr/include -I/home/andrew/projects/neovim/neovim-nightly/build/src/nvim/auto -I/home/andrew/projects/neovim/neovim-nightly/build/include

Features: +acl +iconv +jemalloc +tui
```
- Vim (version: ) behaves differently?
N/A

- Operating system/version:
CentOS release 6.9 (Final)

- Terminal name/version:
iterm2

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:split
<C-w><Down> (the focus is on the bottom window now)
:set winfixheight
:terminal
i (enter insert mode)
less <some_file_with_enough_content> (all lines in the lower window are used by the 'less' output)
<C-\><C-n>
:aboveleft 10new
```

### Actual behaviour
Only 10 lines of the 'less' output remain in the terminal window, the rest becomes empty.

### Expected behaviour
The terminal window's content should not be affected by new window creation.

**Comment by mrbiggfoot** [comment]
To add some context how I stumbled upon it and why I want it fixed: I wanted to make `fzf` open preview in a separate neovim window if fzf is executed from neovim terminal. But every time a new neovim window gets created, the fzf window gets screwed up. Apparently it's not a fzf issue since it also happens with `less`.

**Comment by giuscri** [comment]
I can reproduce this.
```
$ nvim -v
NVIM v0.2.3-788-g1d5eec2c6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/g/hack/neovim/build/config -I/home/g/hack/neovim/src -I/home/g/hack/neovim/.deps/usr/include -I/usr/include -I/home/g/hack/neovim/build/src/nvim/auto -I/home/g/hack/neovim/build/include
Compiled by g@x220

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

![screenshot 6642320c53e5ac01593afc0145fc5525](https://user-images.githubusercontent.com/4048120/37050867-4a35be28-2175-11e8-8f91-18e30d03534e.png)

**Comment by giuscri** [comment]
@justinmk would you provide me some hints on how to fix this?

**Comment by mrbiggfoot** [comment]
Found a workaround. When terminal window is in focus, do `res +1` followed by `res -1` to restore the contents. It's a hack, but works for my project. @justinmk please let me know if there's a better workaround to use until this bug is fixed. Thanks!

**Comment by mrbiggfoot** [comment]
Actually, that workaround only works when done by hand. From vim script it has no effect.

**Comment by mrbiggfoot** [comment]
winsaveview()/winrestview() on the terminal window seem to do the trick.

**Comment by mrbiggfoot** [comment]
...only for the first time. Second time it does not work for some reason. Wondering if there's any other spell I can try.

**Comment by wahahab** [comment]
I would like to try fixing this issue!

**Comment by justinmk** [comment]
@wahahab Feel free to post a (incomplete) PR, you can also find us on https://gitter.im/neovim/neovim for questions.  Build notes are at https://github.com/neovim/neovim/wiki/Building-Neovim

**Comment by wahahab** [comment]
@justinmk thanks for guiding me

After hours of review. I found that when calling win_split() function. Wp and oldwin are point to the same terminal, so when further calling win_new_height(), it will sliently call terminal_resize() and cause problem

Should I fix this by not point to same terminal when use “new” command?

**Comment by mrbiggfoot** [comment]
Please review: https://github.com/neovim/neovim/pull/8247

**Comment by mrbiggfoot** [comment]
Unfortunately the issue still exists for different commands:
```
nvim -u NORC
:aboveleft 10new
:set winfixheight
:terminal
i
less <nvim_repo>/src/nvim/terminal.c
```
<img width="1280" alt="screen shot 2018-04-27 at 11 22 39 pm" src="https://user-images.githubusercontent.com/12175496/39392836-110aa994-4a72-11e8-9b0f-c3342784d799.png">


```
<C-\><C-n>:belowright 20new
```
Now what happens (due to `win_split_ins()` specifics and #8249) is that the terminal gets resized to match the bigger window, and the smaller window stops showing the lines at the bottom:
<img width="1280" alt="screen shot 2018-04-27 at 11 23 22 pm" src="https://user-images.githubusercontent.com/12175496/39392848-4f296792-4a72-11e8-9a85-d7745c7403eb.png">
See, there's no `:` prompt in the terminal window now, because it got pushed out of the viewport.

**Comment by mrbiggfoot** [comment]
Created a separate issue to track that: https://github.com/neovim/neovim/issues/8324
