### ISSUE TITLE
[feature request] panels UI

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#8101]
All "panels" nowadays (like NERDTree, etc) are just windows inside a tab.

It'd be interesting to have some sort of left/right/bottom panel feature that could live outside of tabs, and always attached to the left/right/bottom of the application. The panels could persist no matter which tab you're in. Maybe these panels can even have tabs themselves.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/7541 https://github.com/neovim/neovim/pull/6619
