### ISSUE TITLE
nvim.appimage: fzf window does not close on ESC

### ISSUE THREAD

**Issue by CT075** [neovim/neovim#8104]
- `nvim --version`: `v0.2.3-1-gd6f9d1df0`
- Vim behaves differently? Not applicable
- Operating system/version: Arch Linux 4.14 and RHEL 7.4
- Terminal name/version: zsh 5.4 (for arch) and zsh 5.0 (for RHEL)
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

1. Open terminal mode with :term
2. Exit terminal session from terminal (such as `i<C-d>`)

### Expected behaviour

Terminal closes and returns to previous buffer (same behavior as package/full install)

### Actual behaviour

Terminal pane locks up, accepting no input other than ESC (which returns to normal mode). Normal mode will accept commands (other than <C-\\><C-n>) as usual.

**Comment by justinmk** [comment]
It's not really "locked up". The job ended, so input is ignored in terminal-mode.  Not sure why it would behave differently in the appimage, but it sounds similar to https://github.com/neovim/neovim/issues/7620

**Comment by justinmk** [comment]
@CT075 could you try the latest `nvim.appimage`? It is now a "type 2" AppImage (https://github.com/neovim/neovim/issues/7537).

**Comment by probonopd** [comment]
Someone writes

> I can't reproduce this in the latest appimage which is now a "type 2" AppImage (#7537).

https://github.com/neovim/neovim/issues/7620#issuecomment-372021658

To debug, please run

```
sudo strace -f ./Your.AppImage
```

and compare its output with

```
./Your.AppImage --appimage-extract
sudo strace -f ./squashfs-root/AppRun
```

**Comment by justinmk** [comment]
@probonopd That comment was outdated, I corrected it above https://github.com/neovim/neovim/issues/8104#issuecomment-372021505 .

**Comment by probonopd** [comment]
Thanks @justinmk, please run the commands I posted and compare the lines around where the error happens.

**Comment by justinmk** [comment]
@probonopd Not sure how strace can be used for an interactive program, but here's the traces:

https://gitlab.com/justinmk/gist/snippets/1725213

https://gitlab.com/justinmk/gist/snippets/1725212

**Comment by probonopd** [comment]
THanks @justinmk, in which lines does the crash happen?

**Comment by justinmk** [comment]
Neither, they both get stuck because strace doesn't work with interactive programs.

**Comment by jamessan** [comment]
> they both get stuck because strace doesn't work with interactive programs

I've used strace a lot on (n)vim.  You can use `-o` to dump its output into a file.

**Comment by justinmk** [comment]
Should have mentioned that I did try `-o`, but just got a hang and nothing was written.

...ah, but `-o` works _without_ the appimage. 

So I'm stuck there.

**Comment by probonopd** [comment]
Please use an absolute path for `-o` and see if that works.

**Comment by justinmk** [comment]
Guess I was in a rush earlier, here's where the nvim.appimage gets stuck on startup with strace:

https://gitlab.com/justinmk/gist/snippets/1725258

    sudo strace -f -o nvim.appimage.2.strace ./nvim.appimage -u NONE -i NONE -n

**Comment by dimbleby** [comment]
This wants tracking at the appimage repository, doesn't it?  Both:

* symptoms per this issue
* strace gets stuck, when trying to debug this issue

are things that work fine outside of appimage, and work fine on a unpacked appimage - but fail on a packed appimage.    

I'm going to raise an issue over there.

**Comment by TheAssassin** [comment]
Please see my analysis in https://github.com/AppImage/AppImageKit/issues/812#issuecomment-403993980. This is most likely an issue within nvim, not the AppImage runtime. Looking at the strace log, I assume it has something to do with nvim trying to e.g., write some files in the mounted AppImage directory. Please reopen the issue in AppImageKit if you still think this is an AppImage issue.
