### ISSUE TITLE
Neovim is taking too long to respond after adding Python3 support

### ISSUE THREAD

**Issue by anson2416** [neovim/neovim#8105]
- `nvim --version`: **v0.2.2**
- Vim (version: ) behaves differently? **no**
- Operating system/version: **windowns 10**
- Terminal name/version: **windowns command line**
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. Install python3 support by command below. After done, i got "Successfully installed neovim-0.2.3".
`pip3 install neovim`

2. Add config  `init.vim`

```
" Python 3 support
let g:python3_host_prog = 'D:/Python/Python35/python.exe'
" i try diff parth:
" 'D:/Python/Python35/'
" 'D:\Python\Python35\python.exe'
```

3. Start nvim-qt.ext, but hit error (see Actual behaviour).

_**P.S.** nvim runs normally in command line._ 

### Actual behaviour
NVIM can't start up with error:
**Neovim is taking too long to respond**
### Expected behaviour
NVIM can start up.

**Comment by janlazo** [comment]
That happens to me on nvim-qt (not nvim) regardless of the timeout. It's set to 5 seconds by default but increasing it to 10-20 seconds has no effect. Maybe it will work after 1 minute?

**Comment by anson2416** [comment]
@janlazo how to change the timeout timer?

**Comment by janlazo** [comment]
Use `--timeout`. Check https://github.com/equalsraf/neovim-qt/pull/389.

**Comment by justinmk** [comment]
The python client is broken on windows. https://github.com/neovim/python-client/issues/306

**Comment by bfredl** [comment]
I partially reverted the change for now. Latest PyPI release should work again.

**Comment by anson2416** [comment]
@bfredl shall i re-install neovim?

**Comment by bfredl** [comment]
Something like `pip3 install neovim --upgrade`
