### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by vikramdurai** [neovim/neovim#8106]
- `nvim --version`: 0.2.3-dev
- Vim (version:) behaves differently?
- Operating system/version: Ubuntu 16.04 LTS
- Terminal name/version: fish 2.2.0
- `$TERM`: xterm-256color

### Steps to reproduce

```
git clone https://github.com/neovim/neovim
cd neovim
make CMAKE_BUILD_TYPE=RelWithDebInfol

```

### Actual behaviour
Crashing with an error saying that `libtoolize` isn't installed on my system
### Expected behaviour
It would build fine.

**Comment by justinmk** [comment]
libtoolize should be included when you install `libtool`. 

`libtool` is a build prerequisite. https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites
