### ISSUE TITLE
Neovim clear primary clipboard after enter insert mode

### ISSUE THREAD

**Issue by pickfire** [neovim/neovim#8114]
- `nvim --version`: v0.2.2
- Vim (version: 8.0) / Old neovim (IIRC) behaves differently?
- Operating system/version: Linux arch 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux
- Terminal name/version: st 0.7 (1f24bde)
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

1. `nvim -u NORC`
2. copy something to primary clipboard by highlighting text
3. `i` to enter insert mode in neovim
4. middle click to paste primary clipboard content

### Actual behaviour

Nothing is pasted and neovim clears the primary clipboard content.

### Expected behaviour

Primary clipboard is pasted and clipboard content stays.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? This sounds like something that was fixed though I could not find the discussion.

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by pickfire** [comment]
Yup, this is fixed in nvim v0.2.3-dev.
