### ISSUE TITLE
weird characters after installing with RelWithDebInfo flag

### ISSUE THREAD

**Issue by mrbig033** [neovim/neovim#8119]
- `nvim --version`: NVIM v0.2.3-820-g9cefd83cc
- `Vim` (version: ) behaves differently? 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38). Vim does not have any problem.
- `Operating system/version`: MX Linux 17
- `$TERM`
- with the problem
  - lxterminal 0.3.0
  - Guake Terminal 0.8.8. 
- without the problem
  - terminator 1.90
  - xfce4-terminal 0.8.3 (Xfce 4.12)
  - st 0.7 (c) 2010-2016 st engineers

### Steps to reproduce using `nvim -u NORC`
just open nvim on guake or lxterminal and type `:` . But there's something weird going on: even with the `-u NORC` option, nvim seems to be using my custom keymaps. I don't how how that's possible. I should point out that I installed nvim using Gnu Stow, so nvim is available via simlynks on `nvim: /usr/local/bin/nvim /usr/share/nvim`

```
nvim -u NORC

```
### Actual behaviour
![screenshot_2018-03-08_21-39-16](https://user-images.githubusercontent.com/36245777/37184264-35c09d28-2319-11e8-9d13-60045117e027.png)

### Expected behaviour
![2screenshot_2018-03-08_21-40-21](https://user-images.githubusercontent.com/36245777/37184291-530cc5d2-2319-11e8-8aaf-cc2e2af79d0b.png)

**Comment by jamessan** [comment]
https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

**Comment by mrbig033** [comment]
Thanks!
