### ISSUE TITLE
Scons configuration files are Python, not "conf".

### ISSUE THREAD

**Issue by kierun** [neovim/neovim#8130]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? Yes.
- Operating system/version: CentOS 7
- Terminal name/version: urxvt
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim SConscript SConstruct

```

### Actual behaviour

The file type is set to `conf`.

### Expected behaviour

The file type should be `python`.

**Comment by kierun** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 28 2016 06:13:09)
Included patches: 1-17

**Comment by jamessan** [comment]
You left out some important steps from your [stackexchange](https://vi.stackexchange.com/q/15538/15) question.

Neither Vim nor Neovim set the filetype to python by default.  It has to be configured to do so, and that's what you're having trouble with.

**Comment by kierun** [comment]
There are two things: First, the file type is set to `conf`. That is wrong. Second, as as work around, I wanted to change the filetype using `au`. That did not work either.

**Comment by jamessan** [comment]
> First, the file type is set to `conf`

Yes, that's the default behavior when name based detection and content based detection fail and the first few lines start with a `#`.

The reason it isn't working for you is because you're using `setf python` instead of `set filetype=python`.  This is described in item B of `:help new-filetype`.

**Comment by kierun** [comment]
> Yes, that's the default behavior when name based detection and content based detection fail and the first few lines start with a #.

That is fine but it is still the wrong behaviour. A one line fix is possible.

**Comment by jamessan** [comment]
Sure, so send it to Bram and we'll get the fix when we merge the runtime updates.
