### ISSUE TITLE
Fugitive: how to close the terminal buffer by just pressing enter?

### ISSUE THREAD

**Issue by quantonganh** [neovim/neovim#8131]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?
- Operating system/version:

```
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
```

- Terminal name/version: iTerm2 3.1.5
- `$TERM`: xterm-256color

### Steps to reproduce:
- install with fugitive
- run `:Gpush`

### Actual behaviour

The cursor is put at the beginning of the new buffer and I have to press `:bd!` to close it:

```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 725 bytes | 725.00 KiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:quantonganh/salt-osx.git
   96b98cb..348b340  master -> master

[Process exited 0]
```

### Expected behaviour

The cursor is put at the end (after "[Process exited 0]") and I just need to press enter to go back to the previous buffer.

**Comment by Gnouc** [comment]
No issue for me with `vim 8.0`, `Gpush` simply shows nothing and lead me back to main buffer after pushing

**Comment by quantonganh** [comment]
It looks like there is a problem with `terminal` command:
- nvim -u NORC
- :terminal

but it does not switch to terminal competely:
- the cursor is put at the beginning of command prompt
- if I type a vim command (for e.g, `x`), I got "E21: Cannot make changes, 'modifiable' is off"
- I have to press a non-command character to make it switch to terminal completely (`-- TERMINAL --` in the status line)

**Comment by mhinz** [comment]
That's just how the terminal works. See `:h :terminal`:

```
:te[rminal][!] [{cmd}]	Execute {cmd} with 'shell' in a new |terminal-emulator|
			buffer. Without {cmd}, start an interactive 'shell'.

			Type |i| to enter |Terminal-mode|, then keys are sent to
			the job running in the terminal. Type <C-\><C-N> to
			leave Terminal-mode. |CTRL-\_CTRL-N|

			Fails if changes have been made to the current buffer,
			unless 'hidden' is set.

			To enter |Terminal-mode| automatically: >
			      autocmd TermOpen * startinsert
```

**Comment by quantonganh** [comment]
@mhinz What do you mean?

Sounds like you don't understand my problem.
I'm sure it doesn't work like that before.

Let me clarify: after typing `:terminal`, then enter

before:
- the status line shows `--TERMINAL--`
- the cursor is put at the end of command promt `>>> _`
- I can type some commands immediatly

now:
- the status line shows nothing
- the cursor is put at the beginning of the command prompt (`_>>>`)
- I have to press a non-command to make it switch to terminal mode completely

Is it more clear now?

**Comment by mhinz** [comment]
I do understand your problem.

`:term` doesn't switch to terminal mode automatically, it will open a terminal buffer and stay in normal mode. That's what `:h :terminal` says.

The terminal used to switch to terminal mode automatically, but that behaviour changed. It's more akin all the other modes now. Just `:enew` isn't putting you in insert mode as well etc.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/wiki/Following-HEAD#20170821

**Comment by quantonganh** [comment]
```
❯❯❯❯ cat ~/.vimrc.d/neo.vim
autocmd BufEnter term://* startinsert
autocmd BufLeave term://* stopinsert
```

Then:

```
❯❯❯❯ nvim -u ~/.vimrc.d/neo.vim --noplugin
```

but it does not switch to terminal mode automatically. What is the problem?

**Comment by quantonganh** [comment]
I upgraded to v0.2.3-dev.
`:h :te` and saw this:

```
To enter Terminal-mode automatically:
     autocmd TermOpen * startinsert
```

I tried and it works (even after downgraded to 0.2.2).

Why `autocmd BufEnter term://* startinsert` does not? My terminal name is `term://.//69098:/bin/zsh`.
