### ISSUE TITLE
Can't go past "Press ENTER or type command to continue"

### ISSUE THREAD

**Issue by sryze** [neovim/neovim#8133]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? Yes, vim doesn't hang
- Operating system/version: Windows 10
- Terminal name/version: Git Bash
- `$TERM`: cygwin

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

When using `nvim -u NORC` this doesn't happen because none of the plugins are loaded.

### Steps to reproduce:

1. Put this in `init.vim`:

```
colorscheme doesnt_exist
```

2. Run `nvim` from Git Bash or Windows Command Prompt

### Actual behavior

Neovim outputs this:

```
Error detected while processing C:\Users\szx\AppData\Local\nvim\init.vim:
line    1:
E185: Cannot find color scheme 'doesnt_exist'
Press ENTER or type command to continue
```

and when I press enter nothing happens.

### Expected behavior

When enter is pressed it should close the error window and allow to continue editing.

**Comment by sryze** [comment]
Actually there is a simpler way to reproduce without my entire config:

1. Delete everything from init.vim and paste this:

```
colorscheme doesnt_exist
```

2. Run `nvim`

**Comment by justinmk** [comment]
> Vim (version: ) behaves differently? Yes, vim doesn't hang

Why do people ignor the "version: " field here?

Anyways, you are running `vim` that was compiled for cygwin. You're not running `nvim` compiled for cygwin. 

https://github.com/neovim/neovim/issues/6751

**Comment by sryze** [comment]
Vim version is 8.0 (2016 Sep 12, compiled Feb  8 2018 15:00:34)
Sorry, I didn't notice I was supposed to put a version there.

**Comment by sryze** [comment]
@justinmk  What do you mean it should be compiled for cygwin? When I run it from cmd.exe it doesn't respond to enter either.

**Comment by justinmk** [comment]
> When I run it from cmd.exe it doesn't respond to enter either (like I mentioned in step 2).

Oops, I missed that (since Git Bash and `$TERM: cygwin` were reported...).

Try hitting CTRL-C.

**Comment by nzbart** [comment]
@justinmk unfortunately, Ctrl-C kills the process, whereas I'd like to load Neovim despite the error.

**Comment by justinmk** [comment]
Try `nvim.exe -u NORC`.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/7967 looks similar.

**Comment by jdhao** [comment]
I have also met this issue on Windows 10. Press `Enter` does not take effect. Pressing `Ctrl-C` will kill the process and return to command line.

**Comment by justinmk** [comment]
Again, #7967 covers this issue.

**Comment by jdhao** [comment]
Thanks, using `nvim --cmd silent!` suppresses the error message and enters Neovim successfully.
