### ISSUE TITLE
filetype not loaded when sourcing session file

### ISSUE THREAD

**Issue by marene** [neovim/neovim#8136]
- `nvim --version`:
```
  NVIM v0.2.3-52-ga043899
  Build type: Debug
  LuaJIT 2.0.5
```
- Vim (version: 7.4) behaves differently? *Yes* 
- Operating system/version: Ubuntu 16.04.3 LTS
- Terminal name/version: terminator 0.98
- `$TERM`: `xterm`

### Steps to reproduce using `nvim -u NORC`

```
$> cat minimal.vim
set nocompatible
syntax enable
filetype off
filetype plugin on
filetype plugin indent on

exec "source /home/matthieu/.config/nvim/scripts/sessions.vim"

set guicursor=

autocmd VimLeave * mksession! ./.neosession.vim
autocmd VimEnter * if argc() == 0 | exec "source ./.neosession.vim" | endi

$> nvim -u minimal.vim foobar.js # Open random javascript file, to set a ./.neosession.vim file
$> nvim -u minimal.vim # Will source ./.neosession.vim file
```

### Actual behaviour
When starting up the second nvim, it loads the session, but `filetype` is set to nothing: There is no syntax coloring. (running `edit %` actually resets `filetype` to `javascript`)

### Expected behaviour
Ran the same thing with vim (7.4), filetype is properly restored, enabling syntax coloring right after sourcing session file

#### Disclaimer
This is my first time opening an issue here (and actually on an open-source project ever): Hope I did it right, please correct me if something is wrong/ missing in this ticket :pray: 
Cheers!

**Comment by justinmk** [comment]
```
syntax enable
filetype off
filetype plugin on
filetype plugin indent on
```

Try without that stuff, or try latest HEAD (`v0.2.3-52-ga043899 is missing ~800 commits).

**Comment by marene** [comment]
Thanks for the answer @justinmk 
I did upgrade to `v0.2.3-843-gf5b0f5e` (`Release` build), and tried both with and without 'that stuff'
Still does not work :thinking: 

I have too limited knowledge of the internal functioning of vim/ nvim to have any idea of why this wouldn't work, any help will be greatly appreciated :)

**Comment by justinmk** [comment]
autocmd VimEnter * if argc() == 0 | exec "source ./.neosession.vim" | endi

I think you need `nested`. Like this:

    autocmd VimEnter * nested if argc() == 0 | exec "source ./.neosession.vim" | endi

**Comment by marene** [comment]
Jeez, that works!

Thank you so much!

Any idea why this would work in vim but not in nvim though?

**Comment by justinmk** [comment]
> Vim includes the value 'options' in the setting 'sessionoptions'

Ah, good catch. For reference:

https://github.com/neovim/neovim/issues/2676
https://github.com/neovim/neovim/pull/2871
