### ISSUE TITLE
Neovim(Windows) unsuccessfully suspends when <Ctrl-Z> is pressed

### ISSUE THREAD

**Issue by manipnip** [neovim/neovim#8139]
- `nvim --version`:
```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? Works perfectly fine in Vim 8.0. It suspends the current neovim session, sending the user to command line like it should 
- Operating system/version: Windows 10
- Terminal name/version: ConEmu(161206 stable), Windows Command Prompt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
<Ctrl-Z>
```

### Actual behaviour
When pressing `<Ctrl-Z>` in neovim in either Windows Command Prompt or ConEmu a line break is made. After the line break is made, the cursor would just hang there and blink. At this point, pressing `<Ctrl-C>` does nothing, X'ing out to close takes a long time , and the only way to get a quick fast response to close the console is by force through the task manager.
### Expected behaviour
Within neovim when `<Ctrl-Z>` is pressed, the current neovim session is suspended switching the user over to the command line in the current window.

**Comment by justinmk** [comment]
Yep, suspend doesn't work in the Windows TUI yet. See https://github.com/neovim/neovim/issues/6660

If someone wants to find the time to work on this, Nvim now supports MSVC: https://github.com/neovim/neovim/pull/8084#issuecomment-371371654

**Comment by 947942434** [comment]
Nvim now supports MSVC , build xmake?
