### ISSUE TITLE
`packages` & source order 

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#8144]
- `nvim --version`: 

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: 8) behaves differently? yes (because `:h nvim-defaults`)
- Operating system/version: macOS High Sierra 10.3.3
- Terminal name/version: iTerm Build 3.2.20180315-nightly 
- `$TERM`: `xterm-256color` or `tmux-256color` inside tmux.

---

I had a strange issue when I was trying to switch from `vim-plug` to use native `packages` & https://github.com/pangloss/vim-javascript.

The problem is the order of which the plugins are loaded with `packages` vs `vim-plug`.

Here is a screenshot side-by-side where I use vanilla `packages` _left_ (wrong) vs `vim-plug` _right_  (right) with only `vim-javascript` loaded with both. 

![screenshot](https://user-images.githubusercontent.com/63876/34106836-148c0786-e3fa-11e7-84d9-59425b15279a.png)

You can already see the difference. The fix was to add these to my config

```vim
filetype plugin indent on
syntax on
```

But as far as I know these are already turn on by default accroding to `:h nvim-defaults`, so not sure why this is happening in the first place?

_Actually it's very random, if I test this multiple times I get different results. This doesn't always work, which is even more confusing now_

## Vanilla `packages`

`packages.vimrc`

    set runtimepath+=~/.vim-packages
    set packpath^=~/.vim-packages

and installed `vim-javascript` as follows

    git clone https://github.com/pangloss/vim-javascript.git ~/.vim-packages/pack/test/start/vim-javascript

and ran neovim

    $ nvim -u ~/packages.vimrc

and `:scriptnames` 

      1: ~/packages.vimrc
      2: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/filetype.vim
      3: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/ftplugin.vim
      4: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/indent.vim
      5: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/syntax.vim
      6: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/synload.vim
      7: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/syncolor.vim
      8: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/gui_shim.vim
      9: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/gzip.vim
    10: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/health.vim
    11: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/man.vim
    12: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/matchit.vim
    13: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/matchparen.vim
    14: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/netrwPlugin.vim
    15: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/rplugin.vim
    16: ~/.local/share/nvim/rplugin.vim
    17: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/rrhelper.vim
    18: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/shada.vim
    19: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/spellfile.vim
    20: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tarPlugin.vim
    21: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tohtml.vim
    22: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tutor.vim
    23: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/zipPlugin.vim
    24: ~/.vim-packages/pack/test/start/vim-javascript/ftdetect/javascript.vim
    25: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/ftplugin/javascript.vim
    26: ~/.vim-packages/pack/test/start/vim-javascript/after/ftplugin/javascript.vim
    27: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/indent/javascript.vim
    28: ~/.vim-packages/pack/test/start/vim-javascript/indent/javascript.vim
    29: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/javascript.vim
    30: ~/.vim-packages/pack/test/start/vim-javascript/syntax/javascript.vim

## `vim-plug`
`plug.vimrc`

    set runtimepath+=~/.vim-plug
    call plug#begin('~/.vim-plug/plugged')
    Plug 'pangloss/vim-javascript'
    call plug#end()

and ran neovim

    $ nvim -u ~/plug.vimrc

and `:scriptnames` 

      1: ~/plug.vimrc
      2: ~/.vim-plug/autoload/plug.vim
      3: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/filetype.vim
      4: ~/.vim-plug/plugged/vim-javascript/ftdetect/javascript.vim
      5: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/ftplugin.vim
      6: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/indent.vim
      7: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/syntax.vim
      8: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/synload.vim
      9: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/syncolor.vim
    10: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/gui_shim.vim
    11: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/gzip.vim
    12: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/health.vim
    13: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/man.vim
    14: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/matchit.vim
    15: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/matchparen.vim
    16: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/netrwPlugin.vim
    17: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/rplugin.vim
    18: ~/.local/share/nvim/rplugin.vim
    19: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/rrhelper.vim
    20: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/shada.vim
    21: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/spellfile.vim
    22: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tarPlugin.vim
    23: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tohtml.vim
    24: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/tutor.vim
    25: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/plugin/zipPlugin.vim
    26: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/ftplugin/javascript.vim
    27: ~/.vim-plug/plugged/vim-javascript/after/ftplugin/javascript.vim
    28: ~/.vim-plug/plugged/vim-javascript/indent/javascript.vim
    29: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/indent/javascript.vim
    30: ~/.vim-plug/plugged/vim-javascript/syntax/javascript.vim
    31: /usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime/syntax/javascript.vim

### Actual behaviour

When using `packages` syntax is not sourced properly

### Expected behaviour

That the syntax is sourced properly.

**Comment by justinmk** [comment]
Please try master.

**Comment by ahmedelgabri** [comment]
@justinmk tried it with master, same issue.

`nvim --version`

```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180317-54278-xyp3ez/build/config -I/tmp/neovim-20180317-54278-xyp3ez/src -I/usr/local/include -I/usr/local/Cellar/msgpack/2.1.5/include -I/usr/local/Cellar/libtermkey/0.20/include -I/usr/local/Cellar/libvterm/681/include -I/usr/local/Cellar/jemalloc/5.0.1/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180317-54278-xyp3ez/build/src/nvim/auto -I/tmp/neovim-20180317-54278-xyp3ez/build/include
Compiled by ahmed@thebox.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f407a94_1/share/nvim"

Run :checkhealth for more info
```

**Comment by justinmk** [comment]
> The fix was to add these to my config
> filetype plugin indent on
> syntax on

Then add that to your config. There's no performance cost, Nvim is smart about this.

There is another issue with more discussion about how we could help plugin managers avoid this.

**Comment by ahmedelgabri** [comment]
I think you missed the last paragraph after that :)

> You can already see the difference. The fix was to add these to my config
> 
> ```vim
> filetype plugin indent on
> syntax on
> ```
> 
> But as far as I know these are already turn on by default accroding to `:h nvim-defaults`, so not sure why this is happening in the first place?
> 
> **_Actually it's very random, if I test this multiple times I get different results. This doesn't always work, which is even more confusing now_**

**Comment by justinmk** [comment]
> But as far as I know these are already turn on by default accroding to :h nvim-defaults, so not sure why this is happening in the first place?

They are turned on _after_ init.vim (documented in `:help startup`). Any bits and bobs in your config that depend on them being turned on _earlier_ is not anything that can be helped. 

Plugin managers (such as vim-plug) would break if Nvim tried to enable syntax/`:filetype` earlier than it does. See https://github.com/junegunn/vim-plug/issues/615 for discussion.

**Comment by ahmedelgabri** [comment]
> They are turned on after init.vim (documented in `:help startup`). Any bits and bobs in your config that depend on them being turned on earlier is not anything that can be helped.

Thanks didn't know that.

So what do you recommend in this situation then? Would adding them to `after/[ft]plugin/javascript.vim` or `[ft]plugin/javascript.vim` work?

**Comment by joshdick** [comment]
I have the exact same issue with Neovim 0.3.0 and loading pangloss/vim-javascript as a native package.

@ahmedelgabri Did you ever figure out a solution that works consistently?

@justinmk Maybe this issue should be reopened?

**Comment by ahmedelgabri** [comment]
@joshdick no I didn't, I'm currently testing this instead https://github.com/neoclide/vim-jsx-improve

**Comment by joshdick** [comment]
Thanks for the update @ahmedelgabri. Hoping to still get this issue with https://github.com/pangloss/vim-javascript fixed.

**Comment by fer22f** [comment]
This issue is still present. I tried out the latest nightly build and no luck, the vim-javascript plugin is not loaded correctly. I'm using another plugin, `vim-vue` which uses javascript syntax inside `<script>` tags, and it works correctly inside them:
![image](https://user-images.githubusercontent.com/3057302/46052828-67d12080-c116-11e8-8e65-adfb65ada4c4.png)
However, this issue is also present in Vim's default package handling (although I haven't tried the latest Vim build, this is 8.1):
![image](https://user-images.githubusercontent.com/3057302/46052908-bbdc0500-c116-11e8-90bd-900d89f0f5bb.png)
