### ISSUE TITLE
Custom filetype/buftype for :checkhealth buffer

### ISSUE THREAD

**Issue by stsewd** [neovim/neovim#8148]
Would be nice if the `checkhealth` buffer has its own filetype or buftype. I have `setlocal spell` for `markdown` filetype, and I don't need it for the `:checkhealth` result.

### Actual behaviour

- `:checkhealth`
- `set filetype?`
- `markdown`

### Expected behaviour

- `:checkhealth`
- `set filetype?`
- `checkhealth`?

**Comment by justinmk** [comment]
Could set a buffer name, but I think a new filetype is too much (that was intentionally avoided).

**Comment by ZyX-I** [comment]
`:checkhealth` buffer does have its custom syntax highlighting. It is logical to find its definition in `$VIMRUNTIME/syntax/checkhealth.vim` and not somewhere else. With filetype one could also write plugins for `:checkhealth` like e.g. plugin to execute the advices without forcing Neovim to load plugin file at startup. Why is filetype too much?

**Comment by justinmk** [comment]
@ZyX-I It's noise to add filetypes for every little thing, and it increases risk of conflict with new filetypes that are actually used by files edited by users. If others disagree then I won't insist on it.

**Comment by ZyX-I** [comment]
Risk of conflict is easily eliminated by namespacing. And `:checkhealth` is not too little to not matter. When I was creating aurum I had no troubles adding a bunch of filetypes like aurumannotate, aurumcommit, aurumlog, etc. Also filetype on its own produces exactly no additional noise save for a single line with something like `set filetype=…`, so if you are uncomfortable with having a bunch of little files (there are already 55 files in syntax and 138 in ftplugin less then or equal to 1 KiB though) you don’t need to.

**Comment by ahauser31** [comment]
While this an older topic, I have a similar issue - I have a linter for markdown in use that makes the result of `:checkhealth` very difficult to read, as each line has some issue the linter complains about. I use a CoC extension based on markdownlint, for my case the issue goes away by modifying health.vim and inserting a `call setline(1, '<!-- markdownlint-disable -->')` into the report generating function do disable linting for the file. That does not solve @ZyX-I 's issue, but I agree that it's not ideal that `:checkhealth` produces a markdown file.
