### ISSUE TITLE
job/channel: stdout_buffered as a callback

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8150]
`:help buffered` (tag name is too generic IMO) implies that `stdout_buffered` can be a callback:

```
not partial data. Futhermore if {stream}_buffered is set but not a callback,
the data is saved in the options dict, with the stream name as key. For this
```

But I don't see any tests for that and attempting it gives `E703: Using a Funcref as a Number`:

```
:let o=[] | call jobstart(['stty'], {'pty':v:true, 'stdout_buffered':{a, b, c -> extend(g:o,b)} })
```

**Comment by bfredl** [comment]
No, it refers to the callback param mentioned earlier in the same paragraf. How about "`if {stream}_buffered is set, but the callback on_{stream} is not set,`". The tests show the intended usage.
