### ISSUE TITLE
Proposal: Project to make neovim connect to a remote instance(GSOC).

### ISSUE THREAD

**Issue by Anirudh-C** [neovim/neovim#8154]
I am an avid vim user and neovim user. I hope to be able to implement the daemon-client like behaviour for neovim because I feel the need to use such a system and I'm sure many will as well.
Please comment on how I can start off with the project.

**Comment by ArifRoktim** [comment]
Already a thing: https://github.com/mhinz/neovim-remote

**Comment by justinmk** [comment]
@Anirudh-C Thanks for your interest. GSoC proposals should be submitted through the GSoC website.

https://developers.google.com/open-source/gsoc/faq

> Please comment on how I can start off with the project.

Do you have a specific question?
