### ISSUE TITLE
win: Vim(diffthis):E810: Cannot read or write temp files

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8156]
In the AppVeyor builds (which run the `oldtest` target but silently ignore its failures), there are many lines like this:

```
Caught exception in Test_filler_lines(): Vim(diffthis):E810: Cannot read or write temp files @ function RunTheTest[35]..Test_filler_lines, line 8
```

`:diffthis` seems to have problems on the Windows build. 

This was also noticed by @KillTheMule in https://github.com/neovim/neovim/pull/7917

**Comment by janlazo** [comment]
That's because `unix.vim` wasn't sourced for the new-style tests. It passes in https://github.com/neovim/neovim/pull/8160

**Comment by justinmk** [comment]
Hmm, but diffthis was also failing in Lua tests.

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/pull/8160 is merged now so this issue happens in the Lua tests only.

**Comment by dumblob** [comment]
This error (`E810`) together with the error `E97` prevent nvim-qt launching the diff. I could not find any reason why does it started behaving like this (it worked for me few weeks ago - see https://github.com/equalsraf/neovim-qt/issues/405#issuecomment-384895354 - and I'm not aware of any system change I could have done in the meantime).

I'm getting the errors (see the screenshot below) with the latest nightly:

~~~~
NVIM v0.3.0-1282-g1642917f9
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
~~~~

as well as with the stable version:

~~~~
NVIM v0.2.3-561-g395a3ac04
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
~~~~
![nvim_err00](https://user-images.githubusercontent.com/2451044/40314119-d8d17810-5d17-11e8-9f5d-77e5b963a559.jpg)

Any ideas?

**Comment by janlazo** [comment]
@dumblob I need a minimal vimrc (or `nvim -u NORC`) and the full command to run for nvim-qt.exe and diff 2 files.

**Comment by dumblob** [comment]
Thanks for the immediate help! I hope I didn't disturb you much from your studies.

Yep, you nailed it! I can't remember adding `set shell=sh\ -l` (run as login shell), but it's in my vimrc and commenting that solves the issue. I wrote a comment to the line, that it shall ensure reading my environment variables (containing my shell and apps configuration and behavior). By commenting that line I'll potentially lose this functionality. Any ideas?

**Comment by janlazo** [comment]
@dumblob Is sh in `PATH`? If you installed git, then you may have to append the `/usr/bin/` to `PATH`. See https://github.com/janlazo/dotvim8/blob/300c400b3a6f7e8a2c61a83dfe8d9c0ceaa38252/shared.vim#L186-L200 to shell options for sh/bash.

**Comment by dumblob** [comment]
That's not a bad idea. What I'm though not sure about is why is the `shell` variable not defined (`:echo shell` and `:echo a:shell` both return "E121: Undefined variable: shell" and "E15: Invalid expression: shell`).

**Comment by justinmk** [comment]
@dumblob That's invalid syntax. You need `:echo &shell` for options. Try https://vi.stackexchange.com/ for usage questions.

**Comment by dumblob** [comment]
Yeah, I should learn again the vimscript basics - I'm myself surprised how easy it disappears after few years of not using it 😢 

Anyway, `shell` is set to `cmd.exe` on Windows 10 (I just copied my `init.vim` from Arch Linux to the Windows machine for the first time).

Thank you for you patience!

Now I'm on a hunt for another potential bug of `nvim.exe -d`...

**Comment by janlazo** [comment]
@blueyed @erw7  Is this fixed? I don't see this happen in the CI builds nowadays.

**Comment by blueyed** [comment]
@janlazo 
If it's not in the logs anymore it should be fixed, yes.
Closing.
