### ISSUE TITLE
Support moving through display lines

### ISSUE THREAD

**Issue by marak8** [neovim/neovim#8158]
You can use `gj` and `gk` to move cursor through display lines as opposed to physical file lines. There's no equivalent for move commands though, that is for Ctrl-E, Ctrl-Y, Ctrl-B, Ctrl-F, Ctrl-D, Ctrl-U. These still scroll the screen by physical lines.

Why? For writing text like emails, blog posts, etc. Modern text interfaces reflow text. Text editor I'm writing this issue in is one example. Text is one big line and the renderer formats it into paragraph on any device of any width. For writing such text, `gj` and `gk` can be mapped to `j` and `k`, but scrolling through it is not possible.

format=flowed is highly unsupported.

https://superuser.com/questions/647060/move-display-line-with-ctrl-e-in-vim

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/7172
