### ISSUE TITLE
cursorline drastically slows down up/down line movement

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8159]
- `nvim --version`: NVIM v0.2.3-878-g535bf89
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: Windows 10/17120
- Terminal name/version: conhost/17120
- `$TERM`: cmd/conemu

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC somebigfile.tex
:set cursorline
:syntax on
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
```

### Actual behaviour
neovim has a hard time changing lines, and stutters/hangs repeatedly

### Expected behaviour
Line changes are fast and fluid. Perhaps an asynchronous delay of 5-10ms should be added before the cursorline is redrawn.

----

Note that I have a "slow" terminal emulator probably due to a WSL bug, which makes it all the more obvious.

I'm not sure why but files with certain syntax or highlighting are more affected by this.

**Comment by KillTheMule** [comment]
Not sure what constitutes a big file for your, but I've tried just now with a 180MB text file, and did not see any stutter. When I enabled syntax highlighting though (which is especially expensive for this file type), the stutters are very obvious and make it basically unusable. Did you try disabling syntax highlighting?

**Comment by mqudsi** [comment]
@KillTheMule I _just_ updated my post to indicate that syntax highlighting somehow has a pathological effect on cursorline. 👍

**Comment by bfredl** [comment]
To me the bug seems to be that the entire window is redrawn, and not just the two lines that would be needed to be redrawn.

Ref https://github.com/vim/vim/issues/2584

**Comment by mqudsi** [comment]
@bfredl I agree, I don't think the bisected commit is directly the cause of the slowdown. I also don't see how speeding up `hl_combine_attr` for the cursorline attributes would help here (though I could be wrong) as that would only speed up the calculation of the single line (as opposed to the behavior with cursorline off).

**Comment by mqudsi** [comment]
It's definitely a (neo)vim bug. Too much is being unnecessarily redrawn, which is why drawing speed becomes a bottleneck. The fastest code is the code that doesn't run.

**Comment by adrianoviana87** [comment]
> The fastest code is the code that doesn't run.
Totally agree.
> Note that the version of vim tested in original report was 7.4, which does not exhibit this pathological behavior.
The performance of vim 7.4 running on conemu is poor. On Windows, I have to run vim/neovim in GUI mode to get an acceptable performance.

**Comment by adrianoviana87** [comment]
I checked again and, really, neovim's performance on conemu is way worst than vim (8.0). You kinda see the cursor moving and drawing everything again. This happens regardless of cursorline/cursorcolumn settings.

**Comment by adrianoviana87** [comment]
[Here](https://youtu.be/qL7QlwUlVL4) is a screen recording I made to demonstrate the issue.
It's possible to see both versions in the video.

**Comment by justinmk** [comment]
@adrianoviana87 I'm not going to scrutinize a video. When reporting bugs, please just mention the exact version of Nvim.

**Comment by adrianoviana87** [comment]
# Nvim
--version
```
NVIM v0.2.2                                                                                                             
Build type: RelWithDebInfo                                                                                              
LuaJIT 2.0.5                                                                                                            
Compilation: C:/msys64/mingw32/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMI
N_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough
 -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/pro
jects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr
/include -IC:/msys64/mingw32/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/
projects/neovim/.deps/usr/include -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include -IC:/projects/neovim/build/src
/nvim/auto -IC:/projects/neovim/build/include                                                                           
Compiled by appveyor@APPVYR-WIN                                                                                         
                                                                                                                        
Features: -acl +iconv -jemalloc +tui                                                                                    
```

:CheckHealth
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim_typescript#check
========================================================================
## Find Node
  - OK: node is in $PATH

## Find Local Typescript
  - WARNING: No local server found, using global
    - ADVICE:
      - Install typescript locally for more accurate tooling
          $ npm install typescript --save-dev

## Find Global Typescript
  - OK: global tsserver is found

## Check for deoplete
  - OK: Deoplete is found!

## Check for python 3 bindings
  - OK: has("python3") was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $COLORTERM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "C:/Python27/python.exe"
  - INFO: Executable: C:/Python27/python.exe
  - INFO: Python2 version: 2.7.14
  - INFO: python.exe-neovim version: 0.2.4
  - OK: Latest python.exe-neovim is installed: 0.2.4

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:/Python36/python.exe"
  - INFO: Executable: C:/Python36/python.exe
  - INFO: Python3 version: 3.6.4
  - INFO: python.exe-neovim version: 0.2.4
  - OK: Latest python.exe-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]
  - INFO: Host: ruby C:/Ruby24/lib/ruby/gems/2.4.0/gems/neovim-0.7.1/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node provider (optional)
  - INFO: Node: v9.4.0
  - INFO: Host: C:\Users\adria\AppData\Roaming\npm\neovim-node-host.cmd
  - OK: Latest "neovim" npm is installed: 3.5.2

```

# Conemu
Version: 171025 preview

**Comment by chrischen** [comment]
Neovim: NVIM v0.5.0-3de9452

I'd like to add that I don't see this problem (at least unnoticeable) with cursorline turned off in `nvim --clean`, however it becomes it becomes extremely laggy if I have syntax on and plugins enabled. If i turn off cursorline with plugins, it fixes scrolling.

**Comment by levirs565** [comment]
The problem is in terminal emulator. When i use CmdEd rendring is slow and have lag. When i use Alacritty/Windows Terminal/WozTerm rendering is fast and does not have a lag.

**Comment by mqudsi** [comment]
@levirs565 A fast terminal hides the pathological behavior, that does not mean there is no bug.

**Comment by reportaman** [comment]
@mqudsi @bfredl @levirs565 

Related, but more involved is a issue I just filed. It further slows down to make it noticeably laggy after adding a line to file file and undoing it. Check this out: https://github.com/neovim/neovim/issues/14818

**Comment by lewis6991** [comment]
Can't reproduce anything here. 

Setting `set wd=10 rdb=nodelta` shows the cursorline is redrawn efficiently (with or without syntax highlighting).

@mqudsi is this still an issue for you?

**Comment by lewis6991** [comment]
`wd=10 rdb=nodelta` slows down the drawing so you can see exactly what is being redrawn regardless of how fast your terminal is. With it enabled it shows only the necessary lines are redrawn.

**Comment by zeertzjq** [comment]
This can further reduce redraw with `[N]gg`:
```
diff --git a/src/nvim/move.c b/src/nvim/move.c
index 27cc2b341..eaa518220 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -112,12 +112,11 @@ void redraw_for_cursorline(win_T *wp)
       redraw_later(wp, VALID);
     }
     if (win_cursorline_standout(wp)) {
+      // "w_last_cursorline" may be outdated, worst case we redraw
+      // too much.  This is optimized for moving the cursor around in
+      // the current window.
       if (wp->w_redr_type <= VALID && wp->w_last_cursorline != 0) {
-        // "w_last_cursorline" may be outdated, worst case we redraw
-        // too much.  This is optimized for moving the cursor around in
-        // the current window.
-        redrawWinline(wp, wp->w_last_cursorline);
-        redrawWinline(wp, wp->w_cursor.lnum);
+        redraw_later(wp, VALID);
       } else {
         redraw_later(wp, SOME_VALID);
       }
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 7182e69d0..80fa17162 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -1601,6 +1601,8 @@ static void win_update(win_T *wp, DecorProviders *providers)
    * End of loop over all window lines.
    */
 
+  // Update w_last_cursorline even if Visual mode is active.
+  wp->w_last_cursorline = wp->w_cursor.lnum;
 
   if (idx > wp->w_lines_valid) {
     wp->w_lines_valid = idx;
@@ -2380,8 +2382,6 @@ static int win_line(win_T *wp, linenr_T lnum, int startrow, int endrow, bool noc
       }
       area_highlighting = true;
     }
-    // Update w_last_cursorline even if Visual mode is active.
-    wp->w_last_cursorline = wp->w_cursor.lnum;
   }
 
   memset(sattrs, 0, sizeof(sattrs));
```
