### ISSUE TITLE
<C-\><C-n> Doesn't Close Terminal

### ISSUE THREAD

**Issue by IllyaStarikov** [neovim/neovim#8170]
`<C-\><C-n>` (or the suggested tmapping) does not close the terminal. As of this time, there is no way to exit the terminal without just quitting nvim. 

- `nvim --version`: v0.2.3-dev
- Vim (version: ) behaves differently?
- Operating system/version: macOS 10.13.3
- Terminal name/version: iTerm2 Build 3.1.6beta3 (also tested on Terminal.app Version 2.8 (400))
- `$TERM`: xterm-256color-italic

### Steps to reproduce using `nvim -u NORC`
Enter terminal with `:terminal` command. Attempt to exit with `<C-\><C-n>`.

### Actual behaviour
The terminal session does nothing, no feedback is given.

### Expected behaviour
The terminal session to close .

**Comment by mhinz** [comment]
It's not supposed to close the terminal.

1. `:terminal` opens a terminal buffer in normal mode.
1. `i` switches to terminal mode.
1. `<c-\><c-n>` leaves terminal mode again.
1. Then you close the window like any other Vim window.

**Comment by TamaMcGlinn** [comment]
For people coming across this issue after nvim 0.11.1 which made `ESC` and `<C-[>` no longer equivalent - [that's intentional](https://github.com/neovim/neovim/issues/33711). Just map both:

```
" Enable <ESC> to go back to normal mode
tnoremap <ESC> <C-\><C-n>
tnoremap <C-[> <C-\><C-n>
```
