### ISSUE TITLE
The italic characters were displayed incorrectly

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#8176]
- `nvim --version`:0.2.3.896
- Vim (version: ) behaves differently?
- Operating system/version: Win 10
- Terminal name/version: Neovim-qt
- `$TERM`:

### Actual behaviour
![image](https://user-images.githubusercontent.com/2046672/37872997-eed36194-305a-11e8-882f-aebb8358778c.png)

The italic chars were not displayed correctly as if they were in the box/grid.
### Expected behaviour
The italic characters displayed correctly.

Please fix this thanks.

**Comment by justinmk** [comment]
https://github.com/equalsraf/neovim-qt/issues/154
