### ISSUE TITLE
Fuzzy match in completion popup

### ISSUE THREAD

**Issue by mrbiggfoot** [neovim/neovim#8178]
<s>https://github.com/mrbiggfoot/neovim/commit/4a86ae74f2c74721e57165326d0b827ee290edb0</s>
https://github.com/mrbiggfoot/neovim/commit/2499dbf875cc1f7c1c317233b8ee8b48d5276d90

I implemented this small patch which brings https://github.com/jhawthorn/fzy/blob/master/src/match.c algorithm to neovim completion popup. It can be enabled by setting `set completeopt+=fuzzy`. The reason why I implemented it is because I like fuzzy matching but I'm not satisfied with external plugins performance on huge tag files.

I understand that the diff might be raw and not even functionally correct in all cases - after all, it's my first contribution to neovim - but conceptually, is it something that can be merged to neovim after required polishing? If you think it can potentially meet neovim standards, please kindly provide your thoughts on how to reach them. Otherwise, I'll just keep it in my fork. Thanks!

**Comment by mrbiggfoot** [comment]
Looks like find_tags() has to be modified to read candidates based on match score too.

**Comment by justinmk** [comment]
Definitely interesting. 

> might be raw and not even functionally correct in all cases

How about making it "pluggable" instead? So that your matching algorithm could be used, or any other one. And it could be implemented in Lua.

Even if you want to keep your algorithm in C, couldn't `has_match` and `sort_matches` be "hook points" for other implementations?

Example of calling Lua code from C: https://github.com/neovim/neovim/commit/a034d4b69d6032b3431c10b8a11c998551700fc2#diff-09dda282c4c37768c819b2661ed15f14R1550

Note: another reason in favor of using a "hook" approach instead of baking-in more C code is that Vim (Bram) is planning a refactor of edit.c, specifically the completion code.

**Comment by mrbiggfoot** [comment]
Thanks for the response @justinmk!

> How about making it "pluggable" instead? So that your matching algorithm could be used, or any other one. And it could be implemented in Lua.

Implementing it in a scripting language kind of defeats the purpose why I started doing this. It would be not much different from the existing async autocompletion plugins, which I don't find perfect.

> Even if you want to keep your algorithm in C, couldn't has_match and sort_matches be "hook points" for other implementations?

Are you suggesting just to move them to a separate file, or load the specified dynamic library and call these functions from it? Like, make it a binary plugin? The latter approach is a major PITA to support because of cross-platformness :)

And another thing that I realized after posting my 1st comment is that edit.c has to handle tags differently than the current find_tags() call. In the current implementation, find_tags() returns at most 300 matches and they are matched using prefix match. Also, it reads the tags file on every call (why?!!). We need to use fuzzy match, which would imply processing all the tags. Since I/O is noticeably slow on several hundred MB file (that's my normal tags size), it would require to build a cache of tag names in memory. The cache would take significantly less (I'd say on average 10 times less than the tags file size) since all the auxiliary info would be stripped from tags.

**Comment by justinmk** [comment]
> Implementing it in a scripting language kind of defeats the purpose why I started doing this. It would be not much different from the existing async autocompletion plugins

How does it defeat the purpose? Lua(Jit) is as fast C, or faster depending on the data structures you use. With LuaJit you get dynamic string interning and other optimizations for free.  No where does that exist in Nvim/Vim C codebase.

> Are you suggesting just to move them to a separate file, or load the specified dynamic library and call these functions from it? 

I'm suggesting _at least_ to make changes to edit.c as minimal/surgical as possible, but also to expose clear hook points so at least someone else can pick up the work of exposing them to Lua.

> Like, make it a binary plugin

No. 

> it would require to build a cache of tag names in memory.

One thing at a time, leave that for later.

**Comment by mrbiggfoot** [comment]
> Lua(Jit) is as fast C, or faster depending on the data structures you use. 

I don't believe it. Though I'll do a research on LUA to see if it meets my requirements.

**Comment by justinmk** [comment]
LuaJit. Not Lua.

**Comment by mrbiggfoot** [comment]
How about this plan:
1. Minimize edit.c changes
2. Replace `find_tags()` call in edit.c if `compl_fuzzy` is set to, say, find_tags_cached(). It would internally compare modification timestamp of the tags files to the cached one and rebuild the cache if needed.
3. Try replacing the matcher with a luajit-based plugin, leaving an option to use the default c-based implementation.

I can do 1 and 2 for sure, 3 is not guaranteed.

**Comment by justinmk** [comment]
I will be eager to review (1). It's ok if you don't want to do (3), but I would like to focus on exposing the hooks to Lua/VimL before spending any time on tags caching.

> Replace find_tags() call in edit.c if compl_fuzzy is set with, say, find_tags_cached().

@jamessan would know better than I, but I thought this was discussed on vim_dev at some point.

**Comment by mrbiggfoot** [comment]
Without tags caching, fuzzy search is crippled. It will only do fuzzy search only on the tags that start with the fuzzy pattern.

**Comment by justinmk** [comment]
So let's move forward with the crippled version. That makes it easier to review, merge, and focus on the next part, instead of being a mega-PR that takes forever to discuss.

**Comment by jamessan** [comment]
> I thought this (tags caching) was discussed on vim_dev at some point.

Not that I can recall (or find in some quick searches).

Figuring out when to invalidate caches is one of those "hard" things in CS.  Knowing when to _update_ the cache is easy, as @mrbiggfoot already described.

What if fuzzy matching were a new "state"?  While you're in that state, the data is cached but it gets dropped when the state is left.

In the general case, parsing the tags file every time isn't a significant issue, especially since `find_tags()` is no longer quadratic.

**Comment by mrbiggfoot** [comment]
@jamessan so the only difference from what I described in (2) is freeing the cache when "fuzzy" option is removed from `completeopt`? Or there's something else?

**Comment by mrbiggfoot** [comment]
https://github.com/neovim/neovim/pull/8184

**Comment by jamessan** [comment]
> so the only difference from what I described in (2) is freeing the cache when "fuzzy" option is removed from `completeopt`?

No, because that doesn't really buy anything.  If people decided to use this functionality, they will likely _always_ have the "fuzzy" setting enabled.

The reason for the cache is to avoid having to reparse the tags file every time the user types a character, right? My suggestion therefore is that as soon as the user makes their choice, the cache can be dropped.  There's no need to persist it longer than that interaction with the fuzzy matcher.

This likely also removes the need to determine when to _update_ the cache because the cache is tied to a specific, short-lived user interaction.

**Comment by mrbiggfoot** [comment]
@jamessan I disagree. Reading a 200MB file on each autocompletion is not optimal.

**Comment by justinmk** [comment]
For reference, from our discussion in chat:

* What does this solve that is not possible with `completefunc`?
* `completefunc` doesn't get internal candidates. Can we expose these to `completefunc`? 
  * Or should there be new hooks for matching & sorting the built-in completion candidates (`matchfunc`, `sortfunc`)
* To call a C implementation one may use `libcall()` (VimL function)

**Comment by bfredl** [comment]
> To call a C implementation one may use libcall() (VimL function)

using the luajit cffi interface is much nicer (IIRC there is a non-jit reimplementaion also), alternatively wrap the c library in a lua API.

**Comment by mrbiggfoot** [comment]
I think it's better to have `matchfunc`/`sortfunc` kind of functionality. Then all the existing vim-based autocompletion plugins (like AutoComplPop, VimCompletesMe or mucomplete) can benefit from it without any changes.

**Comment by mrbiggfoot** [comment]
@bfredl So we have a list of C structures that needs to be sorted. Can it be passed to Lua by reference? Or we have to create a copy, pass it to Lua, sort it there, pass it back and then replace the existing C list with the returned one?

**Comment by mrbiggfoot** [comment]
Feel free to use my fork https://github.com/mrbiggfoot/neovim for fuzzy completion functionality.

**Comment by Shougo** [comment]
> I think it's better to have matchfunc/sortfunc kind of functionality. Then all the existing vim-based autocompletion plugins (like AutoComplPop, VimCompletesMe or mucomplete) can benefit from it without any changes.

It is useful.  i'm concerned about the performance.

**Comment by Shougo** [comment]
And the feature should also be implemented in Vim8.

**Comment by mrbiggfoot** [comment]
> It is useful. i'm concerned about the performance.

Let me know if you have any performance problems. So far it's working fine for me on a ~150MB tag file, ~230K unique completion candidates (that is, after filtering and removing redundant words).

**Comment by mrbiggfoot** [comment]
> And the feature should also be implemented in Vim8.

I had hard time convincing even the relatively liberal neovim community. No way I'm trying to merge this into vim. Sorry. :)

**Comment by Shougo** [comment]
I'm concerened about matchfunc/sortfunc feature performance.
completeopt fuzzy is builtin feature, so it is faster.

**Comment by mrbiggfoot** [comment]
@Shougo oh, I see what you mean. Also, there's a room for perf improvement - fuzzy match scores could be calculated by multiple threads.

**Comment by mrbiggfoot** [comment]
I implemented multithreaded fuzzy match scores calculation, also fixed a couple of bugs. Now the fuzzy search is really fast after the tags cache is built (i.e. after the first completion). And even building the tags cache is barely noticeable and bottlenecked by the disk I/O.

**Comment by astier** [comment]
Is there any chance that this feature would be implemented?

**Comment by mrbiggfoot** [comment]
@astier at the moment I have no interest in neovim since I stopped using it quite a while ago. I can't speak for the maintainers, but IIRC they were quite skeptical.

**Comment by wsdjeg** [comment]
this feature can be done with deoplete or other completion plugin easily.

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [neovim/neovim] Fuzzy match in completion popup (#8178)
发件人：Andrew Pyatkov
收件人：neovim/neovim
抄送：Subscribed


@astier<https://github.com/astier> at the moment I have no interest in neovim since I stopped using it quite a while ago. I can't speak for the maintainers, but IIRC they were quite skeptical.

―

**Comment by mrbiggfoot** [comment]
@wsdjeg no it can't, at least last time I checked.
https://github.com/mrbiggfoot/neovim#how-is-it-different-from-using-deopletenvim-completion-manageretc

**Comment by Shougo** [comment]
I have read your code.
But it is C++ based.
It cannot be merged.

**Comment by mrbiggfoot** [comment]
@Shougo sorry, I don't have enough motivation to reinvent the wheel and implement STL in C. I'm perfectly happy with using my own vim fork.

**Comment by bfredl** [comment]
My impression was that the vimL API for completion has been substantially improved recently, with `complete_info()` , `complete_add()` etc. Couldn't fuzzy matching be implemented by a plugin now with these features, or is some piece still missing?

**Comment by mrbiggfoot** [comment]
perhaps it could be done... though it would still require calling an external library function. I don't think vimL can handle tens of thousands candidates efficiently enough.

**Comment by bfredl** [comment]
Sure, but many completion frameworks are already implemented as external processes like deoplete. To me it seems the API would support e.g. deoplete to implement fuzzy matching in its own process and send/update the end result to nvim. Though the API might not support fuzzing of "internal" matches yet, something like matchfunc/sortfunc would still be relevant for that.

**Comment by mrbiggfoot** [comment]
Internal matches work for me in 90% of the cases, why would I want to reimplement them in an external process? All I wanted was to combine fuzzy search with MuComplete.

**Comment by bfredl** [comment]
I didn't say anything about what you should do. I just responded to the claim that this couldn't be done "by deoplete or other completion plugin", which I don't think is strictly true anymore.
