### ISSUE TITLE
Unable to highlight some lines in diff file for some color schemes in bare tty

### ISSUE THREAD

**Issue by nimitbhardwaj** [neovim/neovim#8179]
- `nvim --version`: v0.2.3-879-gce3bc12e2
- Vim (version: 7.4) behaves differently? yes
- Operating system/version: Ubuntu 16.04 LTS
- Terminal name/version: Bare TTy
- `$TERM`: linux
- colorscheme: peaksea

### Steps to reproduce using `nvim -u NORC`
Press `Ctrl + Alt + F1` to enter the tty mode, then create a diff file, for which I used following named `a.diff`
```diff
diff --git a/src/nvim/diff.c b/src/nvim/diff.c
index 0ee1c3815..2e86b617b 100644
--- a/src/nvim/diff.c
+++ b/src/nvim/diff.c
@@ -11,7 +11,7 @@
 #include "nvim/vim.h"
 #include "nvim/ascii.h"
 #include "nvim/diff.h"
-#include "nvim/buffer.h"
+#nclude "nvim/buffer.h"
 #include "nvim/charset.h"
 #include "nvim/cursor.h"
 #include "nvim/eval.h"
```
Then in tty, open it.
```
nvim -u NORC a.diff

```

### Actual behaviour
From the chat at Gitter, for some of the colorschemes the lines which were removed having a `-` were not highlighted.
### Expected behaviour
The colors should be highlighted properly, same colorscheme when used in vim, highlights all required lines properly

**Comment by justinmk** [comment]
Depends on the colorscheme. Fix the colorscheme.

**Comment by nimitbhardwaj** [comment]
Ok cool
