### ISSUE TITLE
:bn / :bp cycles through netrw buffer not created by user

### ISSUE THREAD

**Issue by solutionroute** [neovim/neovim#8181]
- `nvim --version`: v0.23-dev released yesterday; using appimage.
- Vim (version: ) behaves differently? v0.22
- Operating system/version: Linux Debian 9
- Terminal name/version: Gnome-terminal
- `$TERM`: xterm-256color

### Actual behaviour

Open one or more files; Buffer next/previous will cycle through a netrw buffer window not created by the user; :bd said window and cycle through :bn / :bp and the netrw window is there again.

This issue crept in the latest (v0.23-dev) release; v0.22 does not exhibit the problem.

### Expected behaviour

netrw should not be auto-created due to :bn / :bp

**Comment by justinmk** [comment]
Does it happen with `nvim -u NORC` ?

**Comment by solutionroute** [comment]
Apologies, pressed enter on issue before noting that - no, it doesn't occur with -u NORC.

I had been using an older v0.1.7-4 release (Debian packages) but had to grab a newer version yesterday due to one my my Go related plugins.

I've disabled all plugins, am running 
0.23-dev via 
https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage

... with the rest of my init file intact (Plug completely commented out) the problem persists. v0.22 is fine with or without my modified init file.

**Comment by justinmk** [comment]
Then it's almost certainly related to whatever plugins or configuration you have. 
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. 

Or it's a netrw bug, which should be reported to https://github.com/vim/vim/

**Comment by solutionroute** [comment]
I've managed to reproduce it by carving out huge swaths of my init file. The following continues to show the reported behaviour.

```
" Neovim config

" tuning
set noerrorbells				" no beeps
set visualbell
set noshowmode					" lightline plugin shows us mode
set noswapfile					" don't use swapfile
set nobackup					" reduce clutter
set nostartofline				" don't jump to start of line when scrolling
set nocursorcolumn       		" do not highlight column
syntax sync minlines=256 		" start highlighting from 256 lines backwards
set synmaxcol=300        		" do not highlight long lines
set ignorecase					" search case insensitive
set incsearch                   " jump to match as typing
set hlsearch                    " highlight search result 
set inccommand=split			" open preview window for search and replace ops


set hidden						" allows buf switch even if modified
set scrolloff=3					" keep n lines of context while scrolling
set completeopt+=noinsert
set completeopt+=noselect

set pastetoggle=<F2>			" Insert "Paste" mode toggle

" tabs 
set tabstop=4 
set shiftwidth=4
set softtabstop=4

" encoding and file formats
set encoding=utf-8
set ffs=unix,dos,mac

" Wrapping and formatting
set autoindent
set backspace=indent,eol,start
set wrap
set textwidth=79
set formatoptions=qrn1
```

Go figure.

**Comment by solutionroute** [comment]
A one line init file will cause the behaviour described:
```
set hidden
```

**Comment by solutionroute** [comment]
As I've long mapped keys to `:bp!` and `:bn!`, I'm deleting the `set hidden` global option from my init file. FYI should any one else stumble across this.
