### ISSUE TITLE
paused timers consume CPU

### ISSUE THREAD

**Issue by andymass** [neovim/neovim#8188]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently?  Cannot reproduce in vim 8.1542
- Operating system/version: Arch linux/recent
- Terminal name/version: konsole/17.12.3
- `$TERM`: xterm-256color

### Steps to reproduce:

Here is an example init.vim:
```vim
set nocompatible

if 0     " toggle to enable vim-airline
	let &rtp  = '~/.config/nvim/bundle/vim-airline,' . &rtp
endif

filetype plugin indent on
syntax on 

function! CallBack(tid)
	echo 'callback'
endfunction

let g:timer = timer_start(10, 'Callback',
            \ {'repeat': -1})

call timer_pause(g:timer, 1)

nnoremap <space> :<c-u>call timer_stop(g:timer)<cr>
```

run:
```
nvim -u init.vim init.vim
```
and `htop` or similar.

This is probably related to: https://github.com/neovim/neovim/issues/7871, though that was primarily about a memory leak.

### Actual behavior

- Without vim-airline, neovim consumes 1%--2% CPU.  Pressing space to stop the timer makes the CPU go to 0%.

- With vim-airline, neovim consumes 10%--12% CPU.  Again, pressing space makes the CPU go to 0%.  

To emphasize, I am not claiming this is any bug in vim-airline, but the presence of vim-airline exacerbates the issue many-fold, which may help in determining the cause.

### Expected behaviour

There should be no CPU activity when timers are paused.  In vim, there is apparently no cost to having timers paused.

**Comment by bfredl** [comment]
probably `time_watcher_stop` or `time_watcher_start` should be called in `f_timer_paused` (conditional on that the state actually changed).
