### ISSUE TITLE
how to start neovim with command :terminal

### ISSUE THREAD

**Issue by arstum** [neovim/neovim#8198]
- `nvim --version`:NVIM v0.2.2
- Vim (version: ) behaves differently?
- Operating system/version:Mac High Sierra 10.13.2
- Terminal name/version:zsh Terminal
- `$TERM`:

**Comment by arstum** [comment]
nvim -c "terminal"

**Comment by UtkarshMe** [comment]
Hi @arstum!
As you found out, it's `nvim -c ":terminal"`.
If you have any further questions, talk to us on Gitter, IRC, reddit: [community](https://neovim.io/community/)
