### ISSUE TITLE
The third character of the 'tab' suboption of 'listchars'

### ISSUE THREAD

**Issue by pragmb** [neovim/neovim#820]
Hello,

There is a discussion thread about using a third character to the 'tab' suboption of the 'listchars' option.
It enables you to specify a third character for tab, which in turn enables vim to display tabs as '<-->' or '--->' (if the tab takes four spaces).

I attached a patch in this thread: https://groups.google.com/forum/#!msg/vim_dev/bq9vyCYm7CU/CoVI3DDNPBsJ

However, it won't be integrated into vim anytime soon because Bram gives priority to bug fixes.

Thus, I can port it to neovim if you are interested.

Note: I don't know how to write unit tests for neovim, but I'll be glad to do so if you explain me how they work.

Regards,
Pragmb

**Comment by fmoralesc** [comment]
I resurrected the PR at https://github.com/neovim/neovim/pull/3088

**Comment by natbraun** [comment]
Hello, if you guys are still interested I can resume working on this

**Comment by fmoralesc** [comment]
@natbraun Sure, you can take over from my PR, I just rebased it to master.

**Comment by tterranigma** [comment]
This is implemented right?

**Comment by justinmk** [comment]
@tterranigma Thanks for the hint. https://github.com/neovim/neovim/pull/9539
