### ISSUE TITLE
Neovim can't load Python, even though everything is installed. It was working fine yesterday.

### ISSUE THREAD

**Issue by mrbig033** [neovim/neovim#8202]
- `nvim --version`: NVIM v0.2.3-879-gce3bc12e2
- Vim (version: ) behaves differently? I don't have Vim on this machine.
- Operating system/version: MX Linux 17
- Terminal name/version: xfce4-terminal 0.8.3 (Xfce 4.12)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
The problem does not occur when running with the NORC option, but the [checkhealth](https://github.com/mrbig033/nvim/blob/master/checkhealth.vim) shows that neovim cant' find Python or Ruby, even though I already checked their presence on the system and ran `pip2 install neovim && pip3 install neovim && pip2 install --upgrade && neovim pip3 install --upgrade neovim` for good measure.

these are my [neovim configuration files](https://github.com/mrbig033/nvim)

### Actual behaviour
neovim gives the following error message when I try to open a Python file:

```
"25_regex.py" 0L, 0C                                                                                                                          
function pymode#init[2]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4               
Vim(if):ch 3 was closed by the client                                                                                                         
Traceback (most recent call last):                                                                                                            
  File "<string>", line 1, in <module>                                                                                                        
ImportError: No module named 'neovim'                                                                                                         
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.                                                                                           
```
This is the output of the checkhealth command [without the `-u NORC` option](https://github.com/mrbig033/nvim/blob/master/checkhealth_no_norc.vim)

I should note I'm using the Youcompleteme plugin. It gives this error message when I open any file:
```
function youcompleteme#Enable[5]..<SNR>88_SetUpPython[39]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..pr
ovider#Poll, line 4                                                                                                                           
Press ENTER or type command to continue 
```
When I disable it everything seems okays, but I get a Pymode error if I try to open a python file:

```
"28_regex_program.py" 41L, 1058C                                                                                                              
function pymode#init[2]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Poll, line 4               
Vim(if):ch 3 was closed by the client                                                                                                         
Traceback (most recent call last):                                                                                                            
  File "<string>", line 1, in <module>                                                                                                        
ImportError: No module named 'neovim'                                                                                                         
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.                                                                                           
```
I tried running `nvim $NVIM_PYTHON_LOG_FILE`, like the error message instructed, but got no results. `echo $NVIM_PYTHON_LOG_FILE` gives me nothing.

One might think this is a plugin problem, but the checkhealth with the `-u NORC` option shows that neovim can't find Python on the system (even though I double checked its existence). It happened all of a sudden too, I wasn't making any changes to my config files.

### Expected behaviour

I expect for neovim to correctly load the python binaries so Youcompleteme and pythom-mode (pymode) work correctly.

**Comment by Shougo** [comment]
```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2.7"
  - INFO: Executable: /usr/bin/python2.7
  - ERROR: Command error (job=7): '/usr/bin/python2.7' '-c' 'import neovim; print(neovim.__file__)'
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python2 version: 2.7.13
  - INFO: python2.7-neovim version: unable to load neovim Python module
  - ERROR: Neovim Python client is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip2 install neovim

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3.5"
  - INFO: Executable: /usr/bin/python3.5
  - ERROR: Command error (job=10): '/usr/bin/python3.5' '-c' 'import neovim; print(neovim.__file__)'
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named 'neovim'
  - INFO: Python3 version: 3.5.3
  - INFO: python3.5-neovim version: unable to load neovim Python module
  - ERROR: Neovim Python client is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
- Run in shell: pip3 install neovim
```

I think your `pip2` and `pip3` Python and neovim using `pip3` is different.

You can check `python2` and `import neovim`.
You can check `python3` and `import neovim`.

**Comment by mrbig033** [comment]
I just ran those commands and there were no error messages.

**Comment by Shougo** [comment]
Please test the command.

```
/usr/bin/python3.5 -c 'import neovim; print(neovim.__file__)'
```

I think it does not work.

**Comment by mrbig033** [comment]
It ran with no problems.
```
$ /usr/bin/python3.5 -c 'import neovim; print(neovim.__file__)'
~/.local/lib/python3.5/site-packages/neovim/__init__.py
```

**Comment by Shougo** [comment]
Really?  You should check `:checkhealth` again.
It should work.

**Comment by mrbig033** [comment]
Thanks, but I just reinstalled and now the problem is gone. Probably something corrupted.

**Comment by Shougo** [comment]
If so, it should be closed.

**Comment by albfan** [comment]
Hope this help others:

    sudo pip2 install --upgrade pynvim
    sudo pip3 install --upgrade pynvim

**Comment by mschilli87** [comment]
@albfan:
> Hope this help others:
> 
> ```sh
> sudo pip2 install --upgrade pynvim
> sudo pip3 install --upgrade pynv
> ```

I don't think `sudo pip` should be the default suggestion for other users (unless they know exactly what they are doing).

Maybe

```sh
pip[2|3] install --user [--upgrade] pynvim
```

is a safer suggestion?

**Comment by albfan** [comment]
@mschilli87 indeed, I'm agreed with you.

**Comment by meunierd** [comment]
I think a bad pynvim was published because the neovim dir in site-packages doesn't contain any code.

**Comment by thistlillo** [comment]
I have the same problem on Windows 11, neovim 0.8.3 installed via chocolatey, and python 3.10 installed via MS Store. I can run python and import both pynvim and neovim without problems (and print (neovim|pynvim.__file__). However nvim does not detect the python provider.
