### ISSUE TITLE
ctrl-c instead of enter at error prompt causes infinite polling in uv__io_poll

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8210]
- `nvim --version`:  v0.2.3-935-g88e62f239
- Vim (version: 7.4) behaves differently? yes, does not hang on error in first place
- Operating system/version: Linux/WSL (N/A)
- Terminal name/version: conhost/WSL 16299 (N/A)
- `$TERM`: xterm-256color (N/A)

### Steps to reproduce using `nvim -u NORC`

I'm sorry but I don't have a plugin-free reproduction, though I _have_ boiled it down to a single plugin (fzf.vim) in the attached [min.vim](https://github.com/neovim/neovim/files/1865960/min.vim.txt)

```
nvim -u min.vim # see attachment
ctrl+p
#error dialog pops up about unknown command
ctrl+c
```

### Actual behaviour
neovim hangs in a tight loop polling in libuv. There is no way to interrupt this, further ctrl+c has no effect and all input is ignored. It is necessary to kill neovim externally at this point.

### Expected behaviour
`ctrl+c` at the error prompt about an undefined command should be the same as `<enter>`, or at least should not cause this pathological behavior.

Suspicion: sigint is not being blocked and results in some sort of invalid state internally at this point.

Note that while I tested against vim 7.4 and was not able to reproduce this problem, that is because vim didn't/doesn't prompt on `:echoerr` so this opportunity was not presented.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9829 may fix this.

**Comment by erw7** [comment]
I think this problem occurs after `nvim` starts up. Therefore #9829 does not solve this problem.

**Comment by justinmk** [comment]
@mqudsi are you still able to repro this?

**Comment by mqudsi** [comment]
I believe it's fixed now. Ctrl-C doesn't function to ignore the error, but an "Interrupted" is `echoerr`d to the prompt and then a subsequent enter continues past the error. The "Interrupted" message seems to indicate that the previously ignored Ctrl-C is now being handled.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/17199

**Comment by mqudsi** [comment]
I'm not sure if it's related to #17199, @justinmk. That issue is for error prompts that can't be dismissed by pressing ENTER, this particular issue was about pressing ctrl-c instead of ctrl-j/enter at a prompt that would only close with ENTER. 

The only change to neovim there was gated behind an `if (headless_mode && ...)` precondition which would never be live in the case described here.

**Comment by justinmk** [comment]
Yes, I'll start saying "similar" instead of "related" in those cases :)

**Comment by mqudsi** [comment]
Understood and sorry for the pedantry. Cheers!
