### ISSUE TITLE
insert-mode: interpret META as ESC if meta chord is not mapped

### ISSUE THREAD

**Issue by dylnmc** [neovim/neovim#8213]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? **yes**

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 22 2018 22:28:30)
Included patches: 1-1531
Compiled by dylnmc@xps
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby              +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.26/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.26/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc    -lruby -lpthread -lgmp -ldl -lcrypt -lm     
```

- Operating system/version:

Arch / Rolling Release

- Terminal name/version:

URxvt `version 9.22`

- `$TERM`:

`rxvt-unicode-256color`

### Steps to reproduce using `nvim -u NORC`

`<m-l>` or, in human-speak <kbd>alt</kbd>+<kbd>l</kbd>

### Actual behaviour

It inserts an `l`.

### Expected behaviour

Since nvim receives `<esc>l`, it should spit back `<esc>l` (**as vim does**). If do `read -r` in a terminal, you should see `^[l` when you type `<m-l>` since the terminal gets `<esc>l` when you type `<m-l>`

This is far from an issue merely about meta-key-codes. I have tried to use neovim for my purposes today, and I could not stand the fact that when I type `<esc>l` really quickly (for example, I do `<esc>la` a lot to move the character right one), nvim thinks I typed `<m-l>a` and so I get `la` inserted rather than escaping to normal mode, moving over one then going back into insert with `a`.

### Fix

What, in my humble opinion, should be done to fix the issue is *not* report back `l` when `<esc>l` or even `<m-l>` is pressed. Rather it should report back `<esc>l`. The `<esc>` is important!! Sometimes fast typers actually type an `<esc>` rather than a meta+key. It's perfectly fine to capture this if the user or a plugin maps `<m-l>` with `inoremap`, etc, but to just strip off the `<esc>` when I type `<esc>l` really quickly is causing me a lot of anguish; in fact, I am going to switch back to vim until this issue is resolved.

### Questions?

Since this issue may be a little murky (despite my best intentions to illuminate the issue), please ask any questions you might have, if this is still unclear.

Thanks so much for all the hard work,
dylnmc

**Comment by justinmk** [comment]
For your purposes you could just set a very small 'ttimeoutlen' (note the `tt`, this is different than 'timeoutlen').

To completely disable meta chords, that's tracked in https://github.com/neovim/neovim/issues/7972

For tmux see also https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

**Comment by dylnmc** [comment]
yeah, I do set ttimeoutlen to 50, but the crux of the issue is that when neovim sees `<esc><char>` it returns `<char>` and this is a *bad* philosophy.

Pay no heed if you do not wish to.

I shall keep using vim.

**Comment by justinmk** [comment]
@dylnmc you want this "meta means non-chorded ESC" behavior only in insert-mode, or all modes?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/pull/8226

> The way it works now, is that nvim sees `<esc><char>` and if they are pressed under the ttimeoutlen, it uses **only** `<char>` and completely disregards the `<esc>`.

It doesn't disregard it, it interprets it as a meta chord. But without a mapping, the modifier has no effect, so it looks like `l`.  It would be weird to re-encode that as ESC internally, just to satisfy a historical quirk.  But I think it's fine to _behave_ as ESC in insert-mode (as opposed to insisting that it _is_ escape in the internal representation).

**Comment by oblitum** [comment]
Why did it start to be interpreted as a meta chord under such specific conditions? It looks quite weird for me to type `<esc><char>` and expect `<m-anything>` out of it by default.

**Comment by justinmk** [comment]
@oblitum To support ALT (META) chords in the terminal.  This is a historical quirk of terminals, let's not discuss it here, it's been discussed many times in other issues and across the internet.

If you don't care about ALT chords, https://github.com/neovim/neovim/issues/7972 will allow disabling them. 

Some terminals support 8bit mode which will fix the ambiguity, see https://github.com/neovim/neovim/issues/6279

**Comment by oblitum** [comment]
@justinmk ah ok, I get it, because alt doesn't work in many occasions in terminal emulators, still, to provide a solution for meta chords in detriment of the very relevant esc key, doesn't sound as a good trade off. Anyway, hopping there's a fix.

**Comment by jamessan** [comment]
> It doesn't disregard it, it interprets it as a meta chord. But without a mapping, the modifier has no effect, so it looks like `l`

Why was that choice made?  If someone presses `<M-l>` (or `<Esc>l` fast enough to be detected as a meta chord, doesn't really matter) and there's no mapping, then we shouldn't do _anything_.  Inserting `l` makes _no_ sense.

**Comment by jamessan** [comment]
> or <Esc>l fast enough to be detected as a meta chord, doesn't really matter

Actually, that does matter.  If we are able to detect `<Esc>l`, we should treat it as `<Esc>l`.  However, my point still stands for when we see `<M-l>`.

**Comment by justinmk** [comment]
> Why was that choice made?

It wasn't an active choice, just something that never got attention.

**Comment by dylnmc** [comment]
I will say that I have jerry-rigged a vimrc once upon a midnight dreary to check if `has('gui_running')` and if it did imap `<m-*>` and if it didn't imap `<esc>*`; so, I think that this change that nvim is making is for the better.

I also just want to be able to type unimpinged and think that this is on the right track now.
