### ISSUE TITLE
CMake-2.8.7 produces warnings

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#8219]
- `nvim --version`: 1fc09b5b984e0963b5550310dd5d614d3007ba5a  (#7593)

### Steps to reproduce 

Try to build Neovim using CMake-2.8.7

### Actual behaviour

```
CMake Warning (dev) at src/nvim/po/CMakeLists.txt:142 (if):
  given arguments:

    "ja" "IN_LIST" "LANGUAGES"

  Unknown arguments specified
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/nvim/po/CMakeLists.txt:147 (if):
  given arguments:

    "cs" "IN_LIST" "LANGUAGES"

  Unknown arguments specified
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/nvim/po/CMakeLists.txt:152 (if):
  given arguments:

    "sk" "IN_LIST" "LANGUAGES"

  Unknown arguments specified
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/nvim/po/CMakeLists.txt:162 (if):
  given arguments:

    "nb" "IN_LIST" "LANGUAGES"

  Unknown arguments specified
This warning is for project developers.  Use -Wno-dev to suppress it.

-
```

### Expected behaviour

No warnings for project developers are reported. Note that top-level CMakeLists.txt still requires 2.8.7 which is the only reason I am using this outdated version almost each time I build Neovim.

**Comment by justinmk** [comment]
The policy said it would be ignored in older versions, guess that doesn't preclude a warning. Need to check the list some other way.

**Comment by fwalch** [comment]
Don't know why it's an error there and not a warning, but this also broke the Ubuntu PPA builds:

> CMake Error at src/nvim/po/CMakeLists.txt:142 (if): if given arguments: "ja" "IN_LIST" "LANGUAGES" Unknown arguments specified

https://launchpadlibrarian.net/362814283/buildlog_ubuntu-trusty-arm64.neovim_0.2.2ubuntu2+git201803312032-98e7112-f2f288d-804b559~ubuntu14.04.1_BUILDING.txt.gz
