### ISSUE TITLE
Can't build under Windows / MSVC... Missing LIBUV error

### ISSUE THREAD

**Issue by TheGamingKill** [neovim/neovim#8229]
I'm a beginner and I don't know how to use cmake...
When I'm trying to configure x86-Relase (or any other one), I get this error:
`
Error		CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibUV (missing: LIBUV_LIBRARY LIBUV_INCLUDE_DIR)		C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake	137	
`
I don't really get what it means, so help would be appreciated.

**Comment by justinmk** [comment]
Not enough info. Did you follow the steps at https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc  ?

What is the exact commit you are building from? Please always mention that.

**Comment by TheGamingKill** [comment]
"Merge #8226 from justinmk/insert-mode-meta" is the last commit.
Yes I followed the steps, up to step 3 when the configuration fails.

**Comment by justinmk** [comment]
32 bit windows or 64?

The steps work for me, can't do anything without more information.

**Comment by TheGamingKill** [comment]
x64

**Comment by TheGamingKill** [comment]
I discarded changes, for some reason present. Now there is no error on configuration but
in the 4th step, there is no CMake -> Build All option.

**Comment by TheGamingKill** [comment]
I discarded changes, for some reason present. Now there is no error on configuration but
in the 4th step, there is no CMake -> Build All option.

**Comment by yveslange** [comment]
Worked for me on my desktop (WSL) but not for my laptop (surface pro 4, WSL):

```
[...]
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/kursion/neovim/.deps/usr/include'
 /usr/bin/install -c -m 644 /home/kursion/neovim/.deps/build/src/libuv/include/uv.h /home/kursion/neovim/.deps/build/src/libuv/include/uv-errno.h /home/kursion/neovim/.deps/build/src/libuv/include/uv-threadpool.h /home/kursion/neovim/.deps/build/src/libuv/include/uv-version.h /home/kursion/neovim/.deps/build/src/libuv/include/uv-unix.h /home/kursion/neovim/.deps/build/src/libuv/include/uv-linux.h '/home/kursion/neovim/.deps/usr/include'
 /bin/mkdir -p '/home/kursion/neovim/.deps/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 libuv.pc '/home/kursion/neovim/.deps/usr/lib/pkgconfig'
make[2]: Leaving directory '/home/kursion/neovim/.deps/build/src/libuv-build'
make[1]: Leaving directory '/home/kursion/neovim/.deps/build/src/libuv-build'
ninja: build stopped: subcommand failed.
Makefile:80: recipe for target 'deps' failed
make: *** [deps] Error 1
```

**Comment by yveslange** [comment]
Pretty strange, I did `make` multiple times (5 times) and now it's working O_o

**Comment by justinmk** [comment]
@yveslange That sounds like a build-order problem. @jszakmeister mentioned that he thinks we may have a dependency ordering problem.

**Comment by whfyzg** [comment]
i also have this problem. and after delete .deps and .build under project folder, try again with vs2017. it worked fine
