### ISSUE TITLE
Fix for "q" appearing at the end of lines while using tmux

### ISSUE THREAD

**Issue by xyproto** [neovim/neovim#8234]
Hi,

I wanted to comment on #6403 or #7002, but those issues have been locked.

Could a section please be added to the documentation for how to fix the "q appears at the end of the line" issue that happens with tmux + neovim?

Many of the proposed fixes does not fix the issue, I had to try many things before ending up with the following, for fixing it. At this point I don't even know exactly which option fixes the issue, but I know I have a working fix.

Suggested text for the FAQ:

---

Add these lines to **.tmux.conf**:

```
# fix escape in tmux, for neovim
set -sg escape-time 0

# set the default TERM for tmux
set -g default-terminal "screen-256color"

# fix cursor in tmux, for neovim
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

Add these lines to **.config/nvim/init.conf**:

```
" fix issue with spurious q's appearing
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=0
set guicursor=
```

---

Some of the configuration settings may be redundant or no longer needed, if so, please don't include them in the FAQ.

I'm so relieved that the "q" issue is finally gone here, that I wanted to share the solution.

Thanks for creating and maintaining neovim!

**Comment by justinmk** [comment]
It's already in the FAQ, which was mentioned in #7002.

https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

`set -g default-terminal "screen-256color"` is the only thing that's needed, this is already explained in the FAQ which mentions `:help $TERM`.

`set guicursor=` would be needed if your terminal is broken, which is also mentioned in the FAQ.

NVIM_TUI_ENABLE_CURSOR_SHAPE does nothing, so it's not mentioned in the FAQ.

**Comment by xyproto** [comment]
If only using:

set -g default-terminal "screen-256color"

And:

set guicursor=

Then the Escape key does not work properly.

Most users just want tmux and nvim to work. How about adding a point at the top of the FAQ that most tmux + nvim users wants to add the following to **.tmux.conf**:

```
# fix escape in tmux, for neovim
set -sg escape-time 0

# set the default TERM for tmux
set -g default-terminal "screen-256color"
```

And the following to **.config/nvim/init.conf**:

```
set guicursor=
```

This would make life so much easier, and also give a much better impression of nvim for long time tmux and vim users.

**Comment by justinmk** [comment]
ESC key is a separate issue and is addressed by https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes 

> How about adding a point at the top of the FAQ

There's only 1 "top". The item(s) already at the top of the FAQ are there for good reason.

The fact that this config works for you does not mean it can be indiscriminately recommended to all users.

> And the following to .config/nvim/init.conf:
> set guicursor=

Most users _should not_ want to add `set guicursor=`. That is a workaround for old/broken terminal emulators, as I already mentioned. And this is explained in the FAQ.

**Comment by xyproto** [comment]
Thanks for the reply, I see your point of view.

I just wanted to add that I am using the latest version of `konsole`, `tmux` and `nvim`, and that this combination should be relatively common and not so quickly dismissed as "old/broken". From a user point of view, `konsole` works without a hitch for all terminal applications I've thrown at it so far.

The only issue I've ever seen has been related to the specific combination of `tmux` + `nvim`. You are right that this may very well be caused by Konsole, though.

In any case, I'm glad to have configuration that solved my issues. You can add me to the global list of happy Neovim users. :)

My hope is that Neovim can one day become the default "vi-like" editor on distros like Arch, but by policy, Arch applies as few patches as possible and normally ships with no or only minimal default configuration. It would be great if Neovim could work correctly "out of the box" on Arch Linux, without having to configure anything, even if the cause of the problems does not lie with Neovim.

Peace out and Neovim 4 life.
