### ISSUE TITLE
emoji width mismatch

### ISSUE THREAD

**Issue by scull7** [neovim/neovim#8248]
- `nvim --version`:
```sh
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
https://github.com/reasonml-community/bs-express
```
- Vim (version: ) behaves differently?
  Artifacts are not rendered.
- Operating system/version: macOS High Sierra 10.13.3 (17D102)
- Terminal name/version: iTerm2 Build 3.1.5 and Terminal 2.8 (400)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
Does not occur.

### Actual behaviour
![screenshot 2018-04-08 12 00 37](https://user-images.githubusercontent.com/234352/38471350-be8db302-3b24-11e8-8e97-19703f95dc4e.png)

### Expected behaviour
Rendering artifacts are not present.

**Comment by mhinz** [comment]
Does it also happen if you tell your linter plugin to use non-unicode signs?

**Comment by scull7** [comment]
That seems to resolve the issue.

**Comment by mhinz** [comment]
I think this has something to do about Nvim and the terminal not agreeing on the same size of width (1 or 2 cells) for certain unicode characters.

/me summons @tweekmonster

**Comment by teto** [comment]
try setting ambiwidth to 2 ? `:h ambiwidth` but then it might refuse to use the emoji as  character

**Comment by tweekmonster** [comment]
If you aren't using tmux, you should be able to fix this by making sure `Use Unicode version 9 widths` is checked in iTerm2's preferences under `Profiles > Text`.

What @mhinz is pinging me about is something I tried to troubleshoot with him: https://share.esdf.io/ocMGWduoYv/Screen-Recording-2018-04-09-01-34-24.mp4

Seems like if nvim and tmux disagree about a glyph width, the screen might render incorrectly.  It seems that the Heavy Multiplication symbol (and a couple others) is being mistaken as double width.  Pretty sure it's tmux that's causing the issue since everything in that video works fine without it.

**Comment by justinmk** [comment]
> Vim (version: ) behaves differently?

It's important to mention the exact version of Vim. Vim had some changes related to emoji widths, which Nvim also merged.

**Comment by garrettqmartin8** [comment]
@tweekmonster I was encountering the artifacts outside of tmux, but your solution of using Unicode 9 widths in iTerm solved it for me. Thanks.
