### ISSUE TITLE
inccommand: very long substitution wraps (cmdline) incorrectly

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#8254]
- `nvim --version`: NVIM v0.2.3-969-g2ec94eb23
- Operating system/version: Linux 4.14.0-3-amd64 SMP Debian 4.14.17-1
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:set inccommand=nosplit
:%s/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...
```

### Actual behaviour
When the cursor reaches the last column of the terminal and you press 'a' again, the cursor will be on a second line. Press 'a' a few times more and the cursor will be brought back on the first line and the second line will be hidden.

### Expected behaviour
The second line should be visible.

Another bug which I feel has the same root cause can be reproduced like this:
Add the following to your command line and make sure it is at least two lines high:
```
%s/COLLECT_GCC_OPTIONS='-Wall' '-Wextra' '-Wlogical-op' '-Wjump-misses-init' '-Wshadow' '-Wduplicated-cond' '-Wduplicated-branches' '-Wnull-dereference' '-v' '-save-temps' '-mtune=generic' '-march=x86-64'/COLLECT_GCC_OPTIONS='-Wall' '-Wextra' '-Wlogical-op' '-Wjump-misses-init' '-Wshadow' '-Wduplicated-cond' '-Wduplicated-branches' '-Wnull-dereference' '-v' '-save-temps' '-mtune=generic' '-march=x86-64'
```
Then move back before the last `/` and try adding a few `/`. You should see the command line being duplicated multiple times and asking for a redraw with `<C-l>` doesn't change anything.

**Comment by nimitbhardwaj** [comment]
I want to work on this issue.

**Comment by MichaHoffmann** [comment]
@nimitbhardwaj are you still working on this? If not i would like to try to solve it.

**Comment by nimitbhardwaj** [comment]
Why would I work on it now. I thought it was gsoc project. May be some gsocer can do it.

**Comment by glacambre** [comment]
I tried to fix this bug but couldn't find what the culprit might be. However, I found out that if you apply the following patch to master (currently 773bdd41ec19c9909e979c4580cf098d71d168d7 ), the command line will stop collapsing. This isn't a proper fix since it also makes the statusline disappear, but I believe it means that neovim isn't preserving some of the globals it needs to preserve when calling do_cmdline.
```patch
diff --git a/src/nvim/ex_getln.c b/src/nvim/ex_getln.c
index 3de7204fd..1a7727f41 100644
--- a/src/nvim/ex_getln.c
+++ b/src/nvim/ex_getln.c
@@ -1935,6 +1935,8 @@ static int command_line_changed(CommandLineState *s)
              && cmdline_star == 0   // not typing a password
              && cmd_can_preview(ccline.cmdbuff)
              && !vpeekc_any()) {
+    int s_msg_scrolled = msg_scrolled;
+    int s_cmdline_row = cmdline_row;
     // Show 'inccommand' preview. It works like this:
     //    1. Do the command.
     //    2. Command implementation detects CMDPREVIEW state, then:
@@ -1945,6 +1947,9 @@ static int command_line_changed(CommandLineState *s)
     do_cmdline(ccline.cmdbuff, NULL, NULL, DOCMD_KEEPLINE|DOCMD_NOWAIT);
     emsg_silent--;  // Unblock error reporting

+    msg_scrolled = s_msg_scrolled;
+    cmdline_row = s_cmdline_row;
+
     // Restore the window "view".
     curwin->w_cursor   = s->save_cursor;
     curwin->w_curswant = s->old_curswant;
@@ -1954,7 +1959,6 @@ static int command_line_changed(CommandLineState *s)
     curwin->w_botline  = s->old_botline;
     update_topline();

-    redrawcmdline();
   } else if (State & CMDPREVIEW) {
     State = (State & ~CMDPREVIEW);
     update_screen(SOME_VALID);  // Clear 'inccommand' preview.
```
