### ISSUE TITLE
Embedding Neovim into a Chrome NaCl application.

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#8264]
Does anyone know of any effort/attempt to embed neovim in a Chrome NaCl [1] application, run it headless, and have a Javascript UI?

[1] https://developer.chrome.com/native-client

**Comment by justinmk** [comment]
Why NaCl specifically? AFAIK it's deprecated. https://groups.google.com/forum/#!topic/Native-Client-Discuss/wgN2ketXybQ

If the idea is to avoid a separate electron install, check out https://github.com/tweekmonster/nmux by @tweekmonster . Has an awesome logo too.

There are of course numerous javascript UIs. https://github.com/neovim/neovim/wiki/Related-projects#gui .  I've been impressed by [oni](https://github.com/onivim/oni/) , recently.

**Comment by llpamies** [comment]
Thanks justinmk for the response, I didn't know it was deprecated.

The idea wasn't to avoid a separate electron install, but to have the buffer in the client when one does remote development. Right now, when I use nvim over ssh on mobile networks, I still feel too much lag. It's bas to type and do not see the text coming up right away. 

nmux is great, but the buffer is still held in the server...

Thanks again!

**Comment by justinmk** [comment]
> It's bas to type and do not see the text coming up right away.

Oni has done some work towards "optimistic input" IIRC. And I think it supports connecting to a remote instanc. cc @bryphe

**Comment by llpamies** [comment]
Awesome, I'll follow these Oni features closely.

**Comment by bryphe** [comment]
Cool, would be interested in your case @llpamies ! We've had some discussion here about remote possibilities: https://github.com/onivim/oni/issues/247
