### ISSUE TITLE
Should rtp include XDG config folder when launched with -u NORC?

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8275]
- `nvim --version`: 0.2.3-992-g27e26b1
- Vim (version: 7.4) behaves differently? no
- Operating system/version: n/a
- Terminal name/version: n/a
- `$TERM`: n/a

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo &rtp
```

### Actual behaviour
`~/.config/nvim` is included in the runtime path

### Expected behaviour
If the purpose of `-u NORC` is to (mostly) prevent user customization on init, shouldn't this path be excluded here?

For example, all github issues require a repro case with `-u NORC` presuming that most users install plugins with a plugin manager that dynamically sets `rtp`. But if a user has manually installed a plugin, it'll still be loaded (verified with `:scriptnames`).

**Comment by jamessan** [comment]
`-u NORC` intentionally disables loading of only the rc file.  [`--noplugin`](https://neovim.io/doc/user/starting.html#--noplugin) will also disable `plugin/`.
