### ISSUE TITLE
Haron-Prime/evening_vim is slow

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8278]
- `nvim --version`: v0.2.3-992-g27e26b1
- Vim (version: 7.4) behaves differently? yes
- Operating system/version: Linux/WSL
- Terminal name/version: conemu
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
wget https://raw.githubusercontent.com/Haron-Prime/evening_vim/master/colors/evening.vim
nvim -u NORC --startuptime nvim_startup.log -u evening.vim +q
vim -u NORC --startuptime vim_startup.log -u evening.vim +q
```

### Actual behaviour
Excerpt from nvim_startup.log (attached):

```
⋮
016.787  002.195  002.195: sourcing /usr/local/share/nvim/runtime/colors/evening.vim
280.772  274.011  270.910: sourcing ./evening.vim
280.851  000.434: sourcing vimrc file(s)
⋮
```

### Expected behaviour
Vim loads the same file (which does not contain any code conditional upon the version of (neo)vim) in half the time:

```
⋮
007.774  000.396  000.396: sourcing /usr/share/vim/vim74/colors/evening.vim
141.118  137.182  136.333: sourcing ./evening.vim
141.188  000.388: sourcing vimrc file(s)
⋮
```

It was very suspicious that it is _actually_ half the time, but repeated tests don't indicate that is always the case.

[vim_startup.log](https://github.com/neovim/neovim/files/1911070/vim_startup.log)
[nvim_startup.log](https://github.com/neovim/neovim/files/1911072/nvim_startup.log)

**Comment by justinmk** [comment]
NORC for Vim is quite different than Nvim because Nvim has different defaults. A closer comparison would enable Vim's `defaults.vim` thing.

Nevertheless, I couldn't reproduce the issue the issue. I got this:

Nvim v0.3.0-996-g4bb1ee5dcda9:

```
008.077  001.670  001.670: sourcing /usr/local/share/nvim/runtime/colors/evening.vim
144.056  140.642  138.685: sourcing evening.vim
```

Vim 7.4.1689:

```
005.145  000.369  000.369: sourcing /usr/share/vim/vim74/colors/evening.vim
147.830  146.120  145.102: sourcing evening.vim

```

**Comment by justinmk** [comment]
In any case that Haron-Prime/evening_vim fork of "evening" is ridiculously slow. molokai on my machine takes 3ms (_three milliseconds_). 

Are you sure the exact same codepaths are being run? You can check by runing `:profile file` (see the help).

**Comment by mqudsi** [comment]
With the caveat that this in on a different PC, vim 8.0 and neovim `master` both load it in ~170ms, so I'm not sure.

I never realized how expensive general viml scripting (function calls and math) was. I managed to prune the script down to ~15ms, and the neovim experience is _much_ improved! https://github.com/mqudsi/nvim-config/blob/master/colors/evening.vim

But I'm still having a problem with neovim loading the colorscheme twice?

```vim
003.495  000.779: init highlight
004.047  000.119  000.119: sourcing /usr/local/share/nvim/runtime/ftoff.vim
004.297  000.091  000.091: sourcing /usr/local/share/nvim/runtime/syntax/nosyntax.vim
004.924  000.324  000.324: sourcing /home/mqudsi/.config/nvim/bundle/repos/github.com/Shougo/dein.vim/autoload/dein.vim
005.848  000.387  000.387: sourcing /home/mqudsi/.config/nvim/bundle/repos/github.com/Shougo/dein.vim/autoload/dein/autoload.vim
006.925  000.790  000.790: sourcing /home/mqudsi/.config/nvim/bundle/repos/github.com/Shougo/dein.vim/autoload/dein/util.vim
007.346  000.044  000.044: sourcing /usr/local/share/nvim/runtime/ftoff.vim
008.558  000.474  000.474: sourcing /home/mqudsi/.config/nvim/bundle/repos/github.com/Shougo/dein.vim/autoload/dein/types/git.vim
009.046  001.215  000.741: sourcing /home/mqudsi/.config/nvim/bundle/repos/github.com/Shougo/dein.vim/autoload/dein/parse.vim
048.233  000.247  000.247: sourcing /home/mqudsi/.config/nvim/lightline.vim
062.720  014.023  014.023: sourcing /home/mqudsi/.config/nvim/colors/evening.vim
093.479  009.592  009.592: sourcing /home/mqudsi/.config/nvim/bundle/.cache/init.vim/.dein/ftdetect/ftdetect.vim
093.858  030.762  021.170: sourcing /usr/local/share/nvim/runtime/filetype.vim
094.227  000.093  000.093: sourcing /home/mqudsi/.config/nvim/bundle/.cache/init.vim/.dein/ftplugin.vim
094.353  000.043  000.043: sourcing /usr/local/share/nvim/runtime/ftplugin.vim
094.670  000.094  000.094: sourcing /usr/local/share/nvim/runtime/indent.vim
096.561  000.506  000.506: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
098.450  000.457  000.457: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
112.006  016.784  015.821: sourcing /home/mqudsi/.config/nvim/colors/evening.vim
112.190  017.109  000.325: sourcing /usr/local/share/nvim/runtime/syntax/synload.vim
112.249  017.411  000.302: sourcing /usr/local/share/nvim/runtime/syntax/syntax.vim
112.267  108.609  042.966: sourcing /home/mqudsi/.config/nvim/init.vim
```

This wasn't with manually loading the colorscheme with `-u `, I only ran `nvim --startuptime startup.log init.vim`

**Comment by mqudsi** [comment]
I didn't know that `syntax on` forces a reevaluation of the colorscheme. Instead of calling `colo` from `init.vim`, I'm instead assigning `g:colors_name` and relying on `syntax on` to apply the colorscheme in question, and now `evening.vim` is not being called twice.

Is this the intended behavior?

**Comment by Shougo** [comment]
You should upload `init.vim`.

**Comment by mqudsi** [comment]
@Shougo my init.vim is public here: https://github.com/mqudsi/nvim-config but I've tried to keep everything I report here self-contained.

My latest question isn't config specific, I used to call `colo evening.vim` and some lines later call `syntax on` which caused `evening.vim` to be loaded twice due to this line: https://github.com/neovim/neovim/blob/5a304b78647d1a3913cbab197ccde033ae0510cd/runtime/syntax/synload.vim#L19

This is the workaround: https://github.com/mqudsi/nvim-config/commit/78700d9d7997e250e12833790ecdd341bc1d6a2b

**Comment by jamessan** [comment]
> I used to call colo evening.vim and some lines later call syntax on which caused evening.vim to be loaded twice due to this line:

Call `syntax on` first.

**Comment by mqudsi** [comment]
Thanks @Shougo  and @jamessan. I thought leaving `syntax on` to the end would stop any plugins from causing an invalidation/redraw.
