### ISSUE TITLE
syncolor and theme file are repeatedly loaded during colorscheme load

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8279]
- `nvim --version`: v0.2.3-992-g27e26b1
- Vim (version: 7.4) behaves differently? yes
- Operating system/version: Linux/WSL
- Terminal name/version: conemu/17133
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
wget https://raw.githubusercontent.com/Haron-Prime/evening_vim/master/colors/evening.vim
neovim -u NORC --startuptime nvim_startup.log -u evening.vim +q
vim -u NORC --startuptime vim_startup.log -u evening.vim +q
```

### Actual behaviour
As observed in nvim_startup.log:

```
⋮
010.734  001.228  001.228: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim # <-------HERE
016.182  002.283  002.283: sourcing /usr/local/share/nvim/runtime/colors/evening.vim # <-------HERE
231.057  224.770  221.259: sourcing ./evening.vim # <-------HERE
231.143  000.366: sourcing vimrc file(s)
252.614  020.862  020.862: sourcing /usr/local/share/nvim/runtime/filetype.vim
253.451  000.202  000.202: sourcing /usr/local/share/nvim/runtime/ftplugin.vim
254.244  000.187  000.187: sourcing /usr/local/share/nvim/runtime/indent.vim
258.464  000.913  000.913: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim # <-------HERE
263.993  001.207  001.207: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim # <-------HERE
265.351  009.456  007.336: sourcing /usr/local/share/nvim/runtime/colors/evening.vim # <-------HERE
⋮
```

### Expected behaviour

The first load of `evening.vim` on line 2 of the excerpt above can be ignored, as that is #8277 at play.
However, the latter two loadings of `syncolor.vim` and the last load of `evening.vim` are apparently a bug, as loading the same script in vim does not result in this behavior:

```
⋮
005.049  000.318  000.318: sourcing /usr/share/vim/vim74/syntax/syncolor.vim
007.413  000.406  000.406: sourcing /usr/share/vim/vim74/colors/evening.vim
128.010  124.235  123.511: sourcing ./evening.vim
⋮
```

Vim also has the same "load all matching file names" bug, but if you set aside the load of `/usr/share/vim/vim74/colors/evening.vim`, `syncolor.vim` is only loaded once and `evening.vim` is only loaded one other time.

If the custom `evening.vim` were copied to rtp instead of manually specified (as is normally the case), it would be loaded again. Together with #8278, that makes neovim startup take a whopping 500+ ms only loading this (fairly simple) colorscheme. (I added an initialization variable to `evening.vim` with an early abort in case the colorscheme hasn't changed to stop it from going through the motions the second time, that reduced the second load of evening.vim from ~270ms to ~6ms).

[vim_startup.log](https://github.com/neovim/neovim/files/1911081/vim_startup.log)
[nvim_startup.log](https://github.com/neovim/neovim/files/1911082/nvim_startup.log)

**Comment by justinmk** [comment]
Because you explicitly `:source`'d the theme as a VimL file before Nvim started. This wouldn't happen if `:colors evening` was used in a vimrc.

This is just an accident of the ad-hoc design of Vim colorschemes.

**Comment by mqudsi** [comment]
Actually, I'm still seeing syncolor loaded repeatedly (though not evening.vim):

```
042.244  000.734  000.734: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
043.017  002.069  001.335: sourcing /usr/local/share/nvim/runtime/syntax/synload.vim
043.240  003.037  000.968: sourcing /usr/local/share/nvim/runtime/syntax/syntax.vim
045.427  000.998  000.998: sourcing /home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/dein.vim/autoload/dein/autoload.vim
049.093  002.349  002.349: sourcing /home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/dein.vim/autoload/dein/util.vim
052.279  000.642  000.642: sourcing /home/mqudsi/.config/nvim/lightline.vim
126.436  073.734  073.734: sourcing /home/mqudsi/.config/nvim/clipboard.vim
127.720  000.632  000.632: sourcing /home/mqudsi/.config/nvim/bufferclose.vim
128.546  000.309  000.309: sourcing /home/mqudsi/.config/nvim/fzf.vim
131.609  000.783  000.783: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
134.598  000.715  000.715: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
136.827  000.669  000.669: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
360.523  231.260  229.093: sourcing /home/mqudsi/.config/nvim/dein/.cache/init.vim/.dein/colors/evening.vim
```

I only call `syntax enable` at the very end of init.vim

**Comment by Congee** [comment]
Is there a solution?
