### ISSUE TITLE
build: Travis CI: use OS deps where possible

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8281]
On Travis CI we build "bundled" deps from source, instead of installing OS packages. But building the bundled deps takes a _long_ time (5+ minutes). We try to use [travis' cache feature](https://github.com/neovim/neovim/blob/f01fa5660e9092c1d1ce7a8f5cc5ccb59a57b1dc/ci/before_cache.sh), but it often doesn't work, and the caches are hugh (1-2 GB) so we are at risk of exceeding quota (plus it's slow).

It's good to cover both cases (bundled and non-bundled) on Travis CI, but we only need to do it on 1 build (+1 macOS build?). The other builds could use OS packages, which should save a lot of time.

packages to install:

    gperf jemalloc unibilium libtermkey libvterm libuv msgpack luajit luarocks luv

These should be installable from `.travis.yml` in `addons` section:

https://github.com/neovim/neovim/blob/f01fa5660e9092c1d1ce7a8f5cc5ccb59a57b1dc/.travis.yml#L92-L113

If any packages aren't whitelisted by travis, we need to request it at https://github.com/travis-ci/apt-package-whitelist

---

(It's possible we are doing something wrong in [before_cache.sh](https://github.com/neovim/neovim/blob/f01fa5660e9092c1d1ce7a8f5cc5ccb59a57b1dc/ci/before_cache.sh) or [here](https://github.com/neovim/neovim/blob/f01fa5660e9092c1d1ce7a8f5cc5ccb59a57b1dc/ci/common/build.sh#L29-L37). If so, an improvement there is also welcome ...

**Comment by m-srk** [comment]
@justinmk I want to work on this issue and have some questions if you don't mind. 
What I have understood is you want to run one job (per OS) with both the cases i.e; with bundled dependencies and OS packages. Are you considering this approach because your caching efforts didn't seem to make any difference with the job run time ? This is because the cached files are not network- local and retrieving cached files is essentially pulling them over network and hence is bandwidth dependent. 
Reference : https://docs.travis-ci.com/user/caching/#How-does-caching-work%3F

This is what I could understand, in case I've misunderstood can you give a brief description ?

**Comment by justinmk** [comment]
@m-srk Network-local isn't the problem, the problem is that the `.deps` are often built again.

> What I have understood is you want to run one job (per OS) with both the cases

Not exactly. Look at [any build](https://travis-ci.org/neovim/neovim/builds/369467345) for example.  

Currently we have:

- 5 linux builds (including the builds in the "Flaky builds" section) using bundled deps
- 2 macOS builds using bundled deps

The goal of this issue is:

- 1 linux build (`CLANG_SANITIZER=ASAN_UBSAN`) using bundled deps
- All other linux builds using OS packages (`FUNCTIONALTEST=functionaltest-lua` , `BUILD_32BIT=ON`, `GCOV=gcov`, `CLANG_SANITIZER=TSAN`)
- 1 macOS build using bundled deps
- 1 macOS build using OS packages (will need to use homebrew "bottles")

**Comment by m-srk** [comment]
@justinmk Can I submit my PR (first one)?

**Comment by justinmk** [comment]
@m-srk certainly!

**Comment by justinmk** [comment]
@m-srk will you be able to send the PR today?

**Comment by m-srk** [comment]
@justinmk Sure, although the macOS builds doesn't seem to get efficient even after the change. I'll just look into that and create a PR.

Thanks

**Comment by justinmk** [comment]
@m-srk maybe the macOS builds aren't restoring from cache because they always fail (because of #8102), so they never were able to successfully run `before_cache.sh`
