### ISSUE TITLE
Implement `-X` option for Vim compatibility

### ISSUE THREAD

**Issue by spacewander** [neovim/neovim#8285]
- `nvim --version`: NVIM v0.2.0
- `vim --version`: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 28 2018 14:57:49)

### Steps to reproduce using `nvim -u NORC`

```
nvim -X -u NORC
```

### Actual behaviour

```
nvim: Unknown option argument: "-X"
More info with "nvim -h"
```

### Expected behaviour

Create a new Vim instance.

Is there a plan to support Vim's `-X` option for the compatibility?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/701

Though it's kind of pointless: Vim's `-X` should be used with plugins _disabled_, and most features disabled. Given that encrypted files should be edited in very limited circumstances, with most features disabled, why not just use `vim -X`?

**Comment by justinmk** [comment]
@spacewander If nvim implements `-X` it would just ignore it. Is that what you want?

**Comment by spacewander** [comment]
@justinmk 
Yes! If `-X` means nothing for nvim, just ignore it.
