### ISSUE TITLE
Neovim can't read the file list when in OneDrive folder

### ISSUE THREAD

**Issue by draganczukp** [neovim/neovim#8287]
- `nvim --version`
```:NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.0) behaves differently? Yes, it works as expected
- Operating system/version: Windows 10 1709
- Terminal name/version: ConEmu 171109 and nvim-qt
- `$TERM`: empty
- Tried without any plugins with the same result
- My init.vim: [gist](https://gist.github.com/draganczukp/0894b36a209db0c5404fa18224ddb004)

### Steps to reproduce using `nvim -u NORC`
Open vim in a local OneDrive folder
```
nvim -u NORC
:!dir // To make sure there are files
:e <Tab> // To start editing enything
```

### Actual behaviour
 
- `:e <Tab>` does not autocomplete file names.
- `:e file` works as expected and opens the file
- `gf` does not go to file whose name is under cursor and shows `E477: Can't find file "file" in path`
- `:NERDTreeToggle` shows errors and does not open

### Expected behaviour

- `:e <Tab>` shows filenames based on files in the current directory
- `gf` opens the file under cursor
- `:NERDTreeToggle` opens the directory tree

The weird thing is, it worked fine yesterday on the same init.vim.

**Comment by justinmk** [comment]
Can you compare the output of this in both Nvim and Vim:

    :set path?
    :set isfname?

**Comment by draganczukp** [comment]
The nightly does not change anything.

Vim:
```
:set path? => path=.,,
:set isfname? => isfname=@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=
```

Nvim:
```
:set path? => path=.,/usr/include,,
set isfname? => isfname=@,48-57,/,\,.,-,_,+,,,#,$,%,{,},[,],:,@-@,!,~,=
```

**Comment by justinmk** [comment]
> it worked fine yesterday on the same init.vim.

Going to need more info.

**Comment by draganczukp** [comment]
Yesterday on same machine, same config and nothing changed it worked perfectly fine as if it was in any other folder. I turned my PC off, went to sleep and today it doesn't work. There was no Windows update (at least that I'm aware of).

**Comment by draganczukp** [comment]
I just updated to the latest windows version (Spring Creators Update) and it seems to be working fine again, so I'm closing for now.
