### ISSUE TITLE
IO: use uv_fs_copyfile()

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8288]
libuv now has an efficient (or _instant_ on some systems) copy operation: `uv_fs_copyfile()`

https://github.com/libuv/libuv/pull/1465
https://github.com/libuv/libuv/issues/925

Copying files isn't really a bottleneck in a text editor, but  this would be low-risk and "nice to have" if someone wants to work on it.

Task outline:

- Find place(s) where file copy is implemented
- Tests
- Use CMake to feature-detect `uv_fs_copyfile`; if not found (older version of libuv), fall back to ye olde copy procedure.

**Comment by sivasama** [comment]
@justinmk Can I work on this ?

**Comment by justinmk** [comment]
@sivasama Sure, no need to ask permission.

**Comment by traintraveler** [comment]
@y2s82 Sure, seems to complicated for me.
