### ISSUE TITLE
tabstop becom 8 instead of 4 as set

### ISSUE THREAD

**Issue by peter-jerry-ye** [neovim/neovim#8292]
- `nvim --version`: 0.2.2
- Vim (version: 8.0) behaves differently? Yes
- Operating system/version: Ubuntu 17.10 Wayland Gnome-Session
- Terminal name/version: Gnome Terminal 3.24.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC

:set tabstop=4

insert mode: 
<tab>
<left arrow>
<right arrow>
<backspace>

```

### Actual behaviour
The cursor arrives at 1,3-9 instead of 1,2-5
Using left arrow can arrive at 1,2-5
Using backspace at 1,3-9 cause the cursor returns to 1,1

### Expected behaviour
The cursor arrives at 1,2-5 since tabstop=4.

**Comment by janlazo** [comment]
This is expected because of `set smarttab`.  Besides, `shiftwidth` should be configured, not `tabstop`.

**Comment by justinmk** [comment]
> Vim (version: 8.0) behaves differently? Yes

Vim has different defaults. 

For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.
