### ISSUE TITLE
Can't `nunmap` man.vim bindings

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8294]
- `nvim --version`: v0.2.3-935-g88e62f239
- Vim (version: ) behaves differently?
- Operating system/version: WSL/Linux
- Terminal name/version: conemu
- `$TERM`: xterm-256color (N/A)

I'm trying to use neovim as a man page viewer directly from the command line. The problem is that this won't work:

```vim
nvim -u NORC -c ":set fileignorecase" -c ":Man fsync" -c ":silent :only" -c "nmap q :q!<CR>"
````

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c ":set fileignorecase" -c ":Man fsync" -c ":silent :only"
:nunmap q
:nmap q
```

### Actual behaviour
> E31: No such mapping

then
> n  q           *@:lclose<CR><C-W>c

### Expected behaviour
The binding is found and `nunmap q` is allowed. `nmap q` should then report no bindings.

**Comment by justinmk** [comment]
The mapping is buffer local, try in a Filetype autocmd.

**Comment by chrisbra** [comment]
> n q *@:lclosec

The `@` indicates a buffer-local mapping. So you need to do `:nunmap <buffer> q`

**Comment by justinmk** [comment]
This works:

    nvim -u NORC -c ":set fileignorecase" -c ":Man fsync" -c ":silent :only" -c 'nunmap <buffer> q'

**Comment by mqudsi** [comment]
Thank you both.
