### ISSUE TITLE
Error detected while processing Dirchange auto commands for "*"

### ISSUE THREAD

**Issue by kdurant** [neovim/neovim#8295]
- `nvim --version`:
v0.2.2
- Vim (version: ) behaves differently? No
- Operating system/version:
win7

1. add statement into ` init.vim`
```viml
    autocmd VimLeave * exec  "mksession! ~/PluginConfig/nvim_session.vim"
    map     <F7>        :so ~/PluginConfig/nvim_session.vim<cr>
```
2. open nvim-qt.exe and open two file. example 1.c, 2.c

3. close nvim-qt

4. reopen nvim-qt, and open 3.c

5. now, press key **F7**
![default](https://user-images.githubusercontent.com/2704364/38969488-2887d994-43c3-11e8-90cb-ba5382fa3d83.png)

**Comment by justinmk** [comment]
This is a usage question.
