### ISSUE TITLE
Konsole 18.07.70 now has support for DECSCUSR escape sequences

### ISSUE THREAD

**Issue by ahmadsamir** [neovim/neovim#8300]
Hello.

FWIW, Konsole master branch now has support for Set Cursor Style (DECSCUSR) escape sequences[1]; including all the cursor shapes xterm added on top of the ones supported by VT520.

The change will most likely be included in the next stable release, 18.08. This is just a heads up.

Related issue:
https://github.com/neovim/neovim/issues/7002

Thanks :)

[1] https://bugs.kde.org/show_bug.cgi?id=347323

**Comment by justinmk** [comment]
@ahmadsamir Cool, thanks for the notice! But without a way to detect it, I am not sure how we can take advantage of this.

**Comment by ahmadsamir** [comment]
You can now add a condition to check konsole version, DECSCUSR is supported starting from konsole 18.07.70, it'll be release with the next KDE applications stable release, version 18.08.

Thanks.

**Comment by justinmk** [comment]
> You can now add a condition to check konsole version,

How? Is there an environment variable?

**Comment by z3ntu** [comment]
@justinmk Yes, see https://github.com/KDE/konsole/commit/b0d3d83eca4f523a9e4acd3989da6be96033536a
