### ISSUE TITLE
flaky test: job-control: failed jobwait() test

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8302]
QB failure noticed in https://github.com/neovim/neovim/pull/8296 (but unrelated to that PR; possibly related to #8273 , or a side-effect of the recent quickbuild system upgrade):

```
05:05:00,790 INFO  - not ok 389 - jobs jobwait will run callbacks while waiting
05:05:00,790 INFO  - # test/functional/core/job_spec.lua @ 521
05:05:00,790 INFO  - # Failure message: test/functional/core/job_spec.lua:544: Expected objects to be the same.
05:05:00,790 INFO  - # Passed in:
05:05:00,790 INFO  - # (table) {
05:05:00,790 INFO  - #   [1] = 'notification'
05:05:00,790 INFO  - #   [2] = 'wait'
05:05:00,790 INFO  - #  *[3] = {
05:05:00,790 INFO  - #    *[1] = 3 } }
05:05:00,790 INFO  - # Expected:
05:05:00,790 INFO  - # (table) {
05:05:00,790 INFO  - #   [1] = 'notification'
05:05:00,791 INFO  - #   [2] = 'wait'
05:05:00,791 INFO  - #  *[3] = {
05:05:00,791 INFO  - #    *[1] = 4 } }
05:05:00,791 INFO  - # stack traceback:
05:05:00,791 INFO  - # >test/functional/core/job_spec.lua:544: in function <test/functional/core/job_spec.lua:521>
```

Are the streams all closed somehow before the process exits? Or is `proc->status` not set correctly (`>=0`) in some case? cc @bfredl

**Comment by bfredl** [comment]
I can't recall that we positively made sure that `on_exit` gets invoked inside `jobwait()`, the documentation doesn't promise it either. It is more that we do a lot of event processing in `jobwait()` so it is very likely. If we want this behavior, it should be explicity ensured, and then we should also document it.

**Comment by blueyed** [comment]
Another one:
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ...is/build/neovim/neovim/test/functional/core/job_spec.lua @ 549: jobs jobwait will run callbacks while waiting
...is/build/neovim/neovim/test/functional/core/job_spec.lua:572: Expected objects to be the same.
Passed in:
(table) {
  [1] = 'notification'
  [2] = 'wait'
 *[3] = {
   *[1] = 3 } }
Expected:
(table) {
  [1] = 'notification'
  [2] = 'wait'
 *[3] = {
   *[1] = 4 } }
stack traceback:
	...is/build/neovim/neovim/test/functional/core/job_spec.lua:572: in function <...is/build/neovim/neovim/test/functional/core/job_spec.lua:549>
```

https://travis-ci.org/neovim/neovim/jobs/546371095#L7189 (OSX)

**Comment by blueyed** [comment]
The exit handler appears to be called via decref, right?
https://github.com/blueyed/neovim/blob/f22934376eef152c028cc7125e4f57daa31e74a1/src/nvim/event/process.c#L299

I am not sure which behavior we want here really, but we should really fix the flaky test at least already.
