### ISSUE TITLE
nvim fails to build with ninja installed on macOS

### ISSUE THREAD

**Issue by javian** [neovim/neovim#8312]
- `nvim --version`: ffb890491 (HEAD -> master)
- Operating system/version: macOS High Sierra
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

### Steps to reproduce
Following the build instructions for macOS I installed all the dependencies and finished it off with `ninja` . 
```
➜  neovim git:(master) brew install ninja
➜  neovim git:(master) make
ninja  -C .deps
ninja: Entering directory `.deps'
ninja: error: loading 'build.ninja': No such file or directory
make: *** [deps] Error 1
➜  neovim git:(master)
➜  neovim git:(master) brew remove ninja
Uninstalling /usr/local/Cellar/ninja/1.8.2... (7 files, 273.2KB)
➜  neovim git:(master) make
/Library/Developer/CommandLineTools/usr/bin/make  -C .deps
[  9%] Built target luajit
[ 18%] Built target libuv
[ 27%] Built target luv-static
[ 36%] Built target luarocks
[ 37%] Built target mpack
... (ending with a successful compile)
```
If ninja is installed it won't build since ninja can't find the build files.

### Expected behaviour
Compiling would work with Ninja installed assuming that the build instructions are correct.

Am I missing something here ?

**Comment by bfredl** [comment]
Have you tried `make distclean; make` with ninja installed?

**Comment by javian** [comment]
That seems to have solved the issue - thanks @bfredl ! I had only run `make clean` before which did not solve the issue.

**Comment by WhiteBlackGoose** [comment]
That's funny how that comment already received over 20 "+1"s :laughing:
