### ISSUE TITLE
TUI: StatusLineNC in st with termguicolors

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#8318]
- `nvim --version`: v0.3.0-1094-gd7f7cef
- Vim behaves differently? Not tested
- Operating system/version: Red Hat Linux 6
- Terminal name/version: st 0.7 (with the solarized light, scrollback-mouse-altscreen patches, and the no_bold_colors patch because solarized depends on it)
- `$TERM`:  st-256color

I've asked this on reddit before, but only now found the time to install a recent nvim, as well as produce a minimal example.

### Steps to reproduce

Using the following `init_min.vim`:

```viml

function Highlight_Statusline()
  hi clear StatusLine
  hi clear StatusLineNC
  hi User1 guifg=#eee8d5 guibg=#002b36
  hi StatusLine guibg=#002b36
  hi StatusLineNC guibg=#586e75
endfunction

set termguicolors

set statusline+=%1*%t%*                            " file name

```

Run `nvim -u init_min.vim tmp` and call `:call Highlight_Statusline()|vs`. [Here's how it looks for me.](https://imgur.com/a/DcXy6ua) Colors are from the terminal (see the st patches I mentioned above), but the thing to note is the file name in the status line.

### Actual behaviour

File name in the statusline in the nonactive window is somewhat greyish or something.

### Expected behaviour

File name should just stay white.

Note that this example is minified, my actual statusline contains more things, and all are affected like this. For example, a green item I have in there will not stay green for the inactive statusline, but exhibit the same greyish color as the file name you can see above. The `gui=bold` attribute seems to be preserved, though.

Another thing to note is that this statusline configuration isn't new, I've just switched to st + termguicolors recently, which exhibits this problem. Wasn't a problem before, so I suspect it's either a problem of `termguicolors` or its combination with st.

**Comment by justinmk** [comment]
can't reproduce.

**Comment by KillTheMule** [comment]
I tried again on a recent system, and I could reproduce the issue with xterm (337),  `$TERM=xterm` and recent nvim (I'm somewhat unclear on the truecolor support of the terminal, the test script from [here](https://gist.github.com/XVilka/8346728) seems to suggest that I have truecolor support indeed).

It's not a real problem though, I don't mind having the issue closed.
