### ISSUE TITLE
Problem when installing Neovim on Ubuntu 18.04

### ISSUE THREAD

**Issue by vancanhuit** [neovim/neovim#8319]
I just freshly installed Ubuntu 18.04 LTS yesterday and then installed Neovim as instructions [here](https://github.com/neovim/neovim/wiki/Installing-Neovim). But when I added repository and performed update, a problem occurred:

```text
Err:15 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic Release        
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I guess that Neovim is not available for Ubuntu 18.04 right now. So when is it available for installing?

**Comment by jamessan** [comment]
Did you try simply installing neovim from Ubuntu?  The version in Ubuntu is the same version that _would_ be in the PPA, if an upload had been made for bionic yet.

**Comment by vancanhuit** [comment]
@jamessan Oh, thank you. I forgot that.

**Comment by jamessan** [comment]
An upload to the stable PPA has been made for bionic.
