### ISSUE TITLE
PPA raises error with Ubuntu 18.04

### ISSUE THREAD

**Issue by fcanela** [neovim/neovim#8321]
### Steps to reproduce using `nvim -u NORC`

Add the PPA, proceed to apt-get update. bash_history content:
```
   41  sudo apt-get install     apt-transport-https     ca-certificates     curl     software-properties-common
   42  sudo add-apt-repository ppa:neovim-ppa/stable
   43  sudo apt-key fingerprint 0EBFCD88
   44  sudo apt-get update
```

### Actual behaviour

It fails with 404:
```
Get:1 http://es.archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Ign:2 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic InRelease                                   
Err:3 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic Release                                     
  404  Not Found [IP: 91.189.95.83 80]
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                    
Hit:5 http://es.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:6 http://es.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Expected behaviour

Update without error so I can install neovim from ppa.

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/issues/8319.

**Comment by fcanela** [comment]
Yes, that could fix the problem to people who prefer freezing his neovim version to the current one for 4 years. I prefer neovim-ppa because it will ensure I always have an updated version of my editor.

Thanks for the tip anyway!

**Comment by justinmk** [comment]
Thanks for the report, but we don't track package manager details here. The PPA will be updated as the maintainer has time, or if additional maintainers are found.

The [releases page](https://github.com/neovim/neovim/releases) has an AppImage also.

**Comment by jamessan** [comment]
An upload to the stable PPA has been made for bionic.
