### ISSUE TITLE
Extra characters appear on the first line when maximizing terminal

### ISSUE THREAD

**Issue by fatihict** [neovim/neovim#8322]
- `nvim --version`: v0.2.2 
- Vim (version: ) behaves differently? 8.0 Included patches: 1-1542. Yes, behaves differently (as expected).
- Operating system/version: Arch Linux with KDE on X (both latest versions as of April 28th)
- Terminal name/version: konsole 18.04.0 (Same issue in different terminals however)
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
iaaaa<cr>bbbbbbbbbbb

Now we have a file containing the following:
aaaa
bbbbbbbbbbb

:colorscheme blue

Now stand on the 2nd/3rd/4th 'a' and resize terminal by maximizing or tiling the terminal to the left/right half of the screen.

```

### Actual behaviour
This results in the buffer filled with the following text (the 'b's on the first line are visual glitches):
aaaabbbbbbb
bbbbbbbbbbb

### Expected behaviour
aaaa
bbbbbbbbbbb

### Extra information
- Not all colorschemes are affected by this, but atleast blue, darkblue, morning and a custom colorscheme I use are.
- Same issue is not present in Vim 8.0
- Somehow only happens to the top most line, but the extra characters will stay if you scroll up on the same line until the line is completely out of the current view.
- Doest not persist the extra characters to a file when saving

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by fatihict** [comment]
I reproduced the same issue with the universal "binary" `nvim.appimage` on the releases page just now.

**Comment by justinmk** [comment]
Well, I couldn't reproduce it.

**Comment by fatihict** [comment]
I also tested it on Windows just now and can't reproduce it there. I have two Linux machines where the issue does occur.

**Comment by frangio** [comment]
I've been having this issue as well on 0.2.2.

I can reproduce the issue with the reported steps but only the first time I maximize the window.

Adding a second line of `b`s I can reproduce it every time I maximize the window. (Sometimes not the first maximize...)

```
aaaa
bbbbbbbb
bbbbbbbb
```

It doesn't happen with the default color scheme, and it does with the blue color scheme (I haven't tried others).

I tried to reproduce it by setting the `columns` and `lines` options instead of window resizing but couldn't do it.

**Comment by frangio** [comment]
Using `columns` and `lines` I can reproduce an issue that I think might be related.

```VimL
:color blue
:set columns=0
:set columns=20
```

The first line will look different from the rest.

<img src="https://user-images.githubusercontent.com/481465/39410472-15d1ed4e-4bcf-11e8-8c7b-c0eb178ee7af.png" width="400px">

**Comment by fatihict** [comment]
Hmm interesting @frangio 
The reason this issue is bugging me so much is because it also happens when I create a `tmux` split or resize the tmux split. If my cursor in neovim is on the first character or "a" in my example then it doesn't happen.

**Comment by fatihict** [comment]
When I run into this issue I can run `:redraw!` and it will redraw my screen correctly, but `:redraw` without the exclamation mark does not. Also `:mode` works to redraw my screen correctly.

**Comment by justinmk** [comment]
CTRL-L also will redraw the screen.

**Comment by fatihict** [comment]
I was able to reproduce this issue by setting `:hi Normal ctermbg=green` instead of a colorscheme

**Comment by sinapinto** [comment]
for others with this issue, one workaround is to add to your vimrc: `autocmd VimResized * redraw!`

**Comment by justinmk** [comment]
@sinapinto which Nvim `:version` ? Is this still an issue in 0.3.2+? @frangio  @fatihict

**Comment by fatihict** [comment]
Awesome! Seems to be resolved now! :+1:
