### ISSUE TITLE
Navigation commands intermittently flash under status bar

### ISSUE THREAD

**Issue by nwaywood** [neovim/neovim#8332]
- `nvim --version`: v0.2.3-901-ga9c94f7bb
- Vim (version: 8, patches 1-1765) behaves differently? Yes
- Operating system/version: MacOS 10.12.3
- Terminal name/version: iTerm2, 3.1.5
- `$TERM`: screen-256color

### Actual behaviour

When navigating around the screen (`j`, `k`, `C-e`, `C-y` etc), sometimes the character/s being pressed flash under the status bar. For example when scrolling down, `gj` intermittently flashes below the line count in the right hand side of the status bar, as shown in the gif below:
 
![apr-30-2018 15-11-04](https://user-images.githubusercontent.com/3773641/39415618-c4ee0de4-4c88-11e8-8b8b-2721e20abcd2.gif)

### Expected behaviour

The navigation command should never flash below the status bar like this.

### Extra notes

- This that not seem to happen for me in `vim`, only `neovim`
- This also happens when `-u NORC` is set, although admittedly less often

**Comment by justinmk** [comment]
This is just how 'showcmd' works.

    :set noshowcmd

See `:help nvim-defaults`.

**Comment by nwaywood** [comment]
Yes that fixed the issue, thank you! I assumed it was a bug because it only appears intermittently.
