### ISSUE TITLE
[Feature request] TextEdit and snippet support for completion item

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8334]
The completion item from LSP server could have `TextEdit` field for further text edit and it could be `snippet` kind

Official documentation of LSP completion request:
https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#completion-request

Documentation of LSP snippet syntax:
https://github.com/Microsoft/language-server-protocol/blob/master/snippetSyntax.md

Part of LSP completion item definition:
``` typescript
    /**
     * An [edit](#TextEdit) which is applied to a document when selecting
     * this completion. When an edit is provided the value of
     * [insertText](#CompletionItem.insertText) is ignored.
     *
     * *Note:* The text edit's range must be a [single line] and it must contain the position
     * at which completion has been requested.
     */
    textEdit?: TextEdit;
    /**
     * An optional array of additional [text edits](#TextEdit) that are applied when
     * selecting this completion. Edits must not overlap with the main [edit](#CompletionItem.textEdit)
     * nor with themselves.
     */
    additionalTextEdits?: TextEdit[];
    /**
     * The format of the insert text. The format applies to both the `insertText` property
     * and the `newText` property of a provided `textEdit`.
     */
    insertTextFormat?: InsertTextFormat;
```

Definition of `TextEdit`:
``` typescript
/**
 * A text edit applicable to a text document.
 */
export interface TextEdit {
    /**
     * The range of the text document to be manipulated. To insert
     * text into a document create a range where start === end.
     */
    range: Range;
    /**
     * The string to be inserted. For delete operations use an
     * empty string.
     */
    newText: string;
}
```
Definition of `insertTextFormat`
``` typescript
/**
 * Defines whether the insert text in a completion item should be interpreted as
 * plain text or a snippet.
 */
export declare namespace InsertTextFormat {
    /**
     * The primary text to be inserted is treated as a plain string.
     */
    const PlainText: 1;
    /**
     * The primary text to be inserted is treated as a snippet.
     *
     * A snippet can define tab stops and placeholders with `$1`, `$2`
     * and `${3:foo}`. `$0` defines the final tab stop, it defaults to
     * the end of the snippet. Placeholders with equal identifiers are linked,
     * that is typing in one will update others too.
     *
     * See also: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md
     */
    const Snippet: 2;
}
```

Unfortunately,  the complete item of vim/neovim `:h complete-items` have no support for text edit before completion done. And make use of `CompleteDone` autocmd could be buggy for this kind of task, since undo/redo could be broken. 

## The benefit of use experience:
* User could get complete from the middle of a function call, and after completion, the original function call get automically removed
* The snippet could just expanded after complete without the need of special key.

**Comment by justinmk** [comment]
> Unfortunately, the complete item of vim/neovim :h complete-items have no support for text edit before completion done. And make use of CompleteDone autocmd could be buggy for this kind of task, since undo/redo could be broken.

Can we focus on fixing CompleteDone or add a new event?

The rest of the feature request doesn't actually make a specific proposal except "make things better".

**Comment by chemzqm** [comment]
@justinmk I've tried use completeDone, it could works, although it (change buffer in complete done) could cause some issue for some complete plugin.

Maybe add an extra field to complete item for disable vim change buffer after complete item select would be enough, other works could be done by using `user_data`.

**Comment by bfredl** [comment]
You can already set the inserted text different than the displayed, thus to the empty string. There was a blog post that implemented hierarchical menus by using the pum in this way (but I'm to lazy to find it right now)

**Comment by chemzqm** [comment]
@bfredl Thanks, but if set word to empty, vim would not insert text on select item change

![1](https://user-images.githubusercontent.com/251450/39495727-28be0c16-4dce-11e8-9b70-3c7f0b4258a3.gif)

I think it's bad.

**Comment by justinmk** [comment]
@chemzqm So what needs to change in CompleteDone or `v:completed_item` or whatever else? Can we add a flag or something?

**Comment by chemzqm** [comment]
@justinmk Add a flag to complete item indicate that vim should not change the buffer content after this item was selected should be enough.

**Comment by bfredl** [comment]
> Add a flag to complete item indicate that vim should not change the buffer content after this item was selected 

@chemzqm I already pointed out that this is already possible, but then suddenly it was a bad thing. If you have changed your mind again, it can be done by setting `abbr` to the text and `word` to the empty string.

**Comment by bfredl** [comment]
Ah, it is a bit messier than I thought, one _both_ needs to set empty `word` _and_ `empty` flag to 1, to really convince vim one wants an empty string (not sure why, vim first cleaning up for broken plugins, which then messed up for plugins that wants this pattern?), and also `dup`. Though with prefix only `dup` is needed: (emulates complete of `Ju`, so try with `iJu<c-k>`)
`inoremap <C-k> <Cmd>call complete(col('.')-2, [{'word': 'Ju', 'abbr': 'July'}, {'word': 'Ju', 'abbr': 'June', 'dup': 1}])<CR>`

**Comment by bfredl** [comment]
What is the difference between "select" and "complete"? You want to defer the buffer change (done by vim) until CompleteDone?

**Comment by bfredl** [comment]
> I would like to keep the text insert behaviour on complete item navigation, but avoid buffer change on item selected.

 I see you edit now. Essentially that would mean undoing the last insertion before invoking `CompleteDone`. But I don't see how that would be a useful addition. If you already are going apply a sequence of changes, can you not just as well undo the effect of the last insertion if need be before that, the same way as the edits are done inside `CompleteDone`?

**Comment by chemzqm** [comment]
@bfredl Looked into the source code, seems that vim could also do some indent stuff on compltetion complete. Yes, I want to disable the buffer change from complete item selected (using `<C-y>`) until CompleteDone.

**Comment by chemzqm** [comment]
@bfredl It would be hard to undo the change made by vim on completion complete when there is any indent change.  Actually I can just apply changes to the buffer content saved on completion start and replace buffer with differences. The extra flag would makes the saving of buffer content unnecessary and avoid unnecessary buffer change.

**Comment by justinmk** [comment]
> seems that vim could also do some indent stuff on compltetion complete.

 https://github.com/neovim/neovim/pull/8349 should fix that if I'm not mistaken.

Based on the rest of the discussion above, IIUC we can close this.
