### ISSUE TITLE
:Man not working on OpenBSD

### ISSUE THREAD

**Issue by devmsv** [neovim/neovim#8341]
- `nvim --version`: NVIM v0.2.2
Build type: Release
Lua 5.1
Compilation: /usr/obj/ports/neovim-0.2.2/bin/cc -O2 -pipe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/usr/obj/ports/neovim-0.2.2/build-amd64/config -I/usr/obj/ports/neovim-0.2.2/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/obj/ports/neovim-0.2.2/build-amd64/src/nvim/auto -I/usr/obj/ports/neovim-0.2.2/build-amd64/include
Compiled by _pbuild@amd64-3.ports.openbsd.org

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

- Vim (version: ) VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 27 2018 12:55:26)
Included patches: 1-1589

In VIM its working.

- Operating system/version: OpenBSD 6.3 GENERIC.MP#1 amd64
- Terminal name/version: st 0.8
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`
in command mode try to launch `Man man` or `Man 1 man`

```
nvim -u NORC
:Man man
man.vim: command error (4) env MANPAGER=cat MANWIDTH=136 man /usr/share/man/man1/man.1
/usr/share/man/man7/man.7: man: No entry for /usr/share/man/man1/man.1
/usr/share/man/man7/man.7 in the manual.

:Man 1 man
man.vim: command error (4) env MANPAGER=cat MANWIDTH=136 man /usr/share/man/man1/man.1: man: No entry for /usr/share/man/man1/man.1 in t
he manual.
```

### Actual behaviour

Man doesn't pass -l as an argument on OpenBSD

### Expected behaviour

Man should pass -l as an argument to read manual pages with the path.

`MANPAGER=cat MANWIDTH=136 man  -l /usr/share/man/man1/man.1`
it's working ok on the cli

I have take a look in /usr/local/share/nvim/runtime/autoload/man.vim but I don't have the  vimscript knowledge needed to fix the issue myself :(

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/6766 should have fixed this

**Comment by jamessan** [comment]
That fix was part of 0.2.1, so it should definitely be part of the build that's being used.

**Comment by nhooyr** [comment]
Ah, I think the issue is that when finding a manpage without specifying the section, OpenBSD's man returns all candidates instead of the first. So we need to trim until only the first.

That's why @devmsv's error has man.7 in it it too.

**Comment by devmsv** [comment]
yes, @nhooyr  ```-w        List the pathnames of all matching manual pages instead of displaying any of them.```
