### ISSUE TITLE
Ctrl+Shift and AltGr+Shift incorrectly identified in Neovim-Qt

### ISSUE THREAD

**Issue by ArenaL5** [neovim/neovim#8342]
- `nvim --version`: v0.3.0-dev. (I'm using the unstable PPA for Ubuntu AMD64, and the prepackaged AMD64 version for Windows)
- GVim version 8.0 doesn't have this bug.
- Operating system/version: Ubuntu Desktop Artful Aardvark, AMD64; and Windows 10, AMD64
- This problem never occurs in a terminal, it's strictly a problem in Neovim-Qt GUI.

### Steps to reproduce using `nvim -u NORC`
I used `nvim -u NONE` and `nvim-qt -- -u NONE`.

The error is apparent when inserting text, and pressing Ctrl+Shift, without any other key.

I'm using the default keyboard layout for Spanish (Spain), if that matters.

### Actual behaviour
Ctrl+Shift behaves like Ctrl+Space. I confirmed this by using Ctrl+V in insert mode, and then pressing Ctrl+Shift.

In Windows 10, there's an additional error: AltGr+Shift behaves like Space.

### Expected behaviour
Nothing should happen unless I press a non-modifier key. In fact, nothing happens in the terminals.

**Comment by jamessan** [comment]
Neovim-qt is developed in its own [repo](https://github.com/equalsraf/neovim-qt).  Issues should be reported there.

This one looks like https://github.com/equalsraf/neovim-qt/issues/344.
