### ISSUE TITLE
API: nvim_input('<c-Ñ>') unrecognized

### ISSUE THREAD

**Issue by ArenaL5** [neovim/neovim#8343]
I've sent a [similar issue](https://github.com/neovim/neovim/issues/8342) recently, but this one has a different setup and maybe a different cause, so I preferred to send them separately. Feel free to merge them if it helps.

This error happens with european letters outside the basic English alphabet. My tests were done with both lowercase and uppercase N-tilde; they're listed in Unicode as:
- U+00F1 LATIN SMALL LETTER N WITH TILDE
- U+00D1 LATIN CAPITAL LETTER N WITH TILDE

### Debug data

- `nvim --version`: v0.3.0-dev. (I'm using the unstable PPA for Ubuntu AMD64, and the prepackaged AMD64 version for Windows).
- GVim version 8.0 doesn't have this bug.
- Operating system/version: Ubuntu Desktop Artful Aardvark, AMD64; and Windows 10, AMD64
- Terminal name/version: `gnome-terminal` and `cmd.exe`
- `$TERM`: `xterm-256color` for Linux. Didn't check Windows, but I'm using the default.

### Steps to reproduce

Because I've used some repetitive mappings, I tested this bug with `nvim -u bugs.txt --noplugin` and `nvim-qt -- -u bugs.txt --noplugin`. `bugs.txt` contains solely the following mappings:

```
map ñ :echo 'ñ'<CR>
map Ñ :echo 'Ñ'<CR>
map <c-ñ> :echo 'c-ñ'<CR>
map <c-Ñ> :echo 'c-Ñ'<CR>
map <C-ñ> :echo 'C-ñ'<CR>
map <C-Ñ> :echo 'C-Ñ'<CR>
map <s-ñ> :echo 's-ñ'<CR>
map <s-Ñ> :echo 's-Ñ'<CR>
map <S-ñ> :echo 'S-ñ'<CR>
map <S-Ñ> :echo 'S-Ñ'<CR>
map <m-ñ> :echo 'm-ñ'<CR>
map <m-Ñ> :echo 'm-Ñ'<CR>
map <M-ñ> :echo 'M-ñ'<CR>
map <M-Ñ> :echo 'M-Ñ'<CR>
map <a-ñ> :echo 'a-ñ'<CR>
map <a-Ñ> :echo 'a-Ñ'<CR>
map <A-ñ> :echo 'A-ñ'<CR>
map <A-Ñ> :echo 'A-Ñ'<CR>
map <d-ñ> :echo 'd-ñ'<CR>
map <d-Ñ> :echo 'd-Ñ'<CR>
map <D-ñ> :echo 'D-ñ'<CR>
map <D-Ñ> :echo 'D-Ñ'<CR>
map t :echo 't'<CR>
map T :echo 'T'<CR>
map <c-t> :echo 'c-t'<CR>
map <c-T> :echo 'c-T'<CR>
map <C-t> :echo 'C-t'<CR>
map <C-T> :echo 'C-T'<CR>
map <s-t> :echo 's-t'<CR>
map <s-T> :echo 's-T'<CR>
map <S-t> :echo 'S-t'<CR>
map <S-T> :echo 'S-T'<CR>
map <m-t> :echo 'm-t'<CR>
map <m-T> :echo 'm-T'<CR>
map <M-t> :echo 'M-t'<CR>
map <M-T> :echo 'M-T'<CR>
map <a-t> :echo 'a-t'<CR>
map <a-T> :echo 'a-T'<CR>
map <A-t> :echo 'A-t'<CR>
map <A-T> :echo 'A-T'<CR>
map <d-t> :echo 'd-t'<CR>
map <d-T> :echo 'd-T'<CR>
map <D-t> :echo 'D-t'<CR>
map <D-T> :echo 'D-T'<CR>
```

Then, I tried the above mappings in normal mode.

### Actual behaviour

Pressing Ñ displays the message `ñ` or `Ñ`, depending on Caps Lock.

Pressing Shift+Ñ doesn't display anything, regardless of Caps Lock.

Any other modifier keys plus Ñ display `ñ`, `Ñ`, or nothing in the terminal; and nothing in Neovim-Qt.

This doesn't only affect mappings. I can't type an uppercase Ñ using Shift+Ñ; I need to use Caps Lock or an indirect method like `^Vu00d1`. Ç (U+00C7 LATIN CAPITAL LETTER C WITH CEDILLA) doesn't work either, and other capital letters outside the English alphabet like Ä, Ö, Å are unlikely to work.

On the other hand, mappings with T and modifier keys work as well as can be reasonably expected. (Not all of them work in the terminals, and Win+T is captured by Windows). Neovim considers `T` and `<S-T>` to be the same mapping, so `:map T` displays `T        :echo S-T<CR>`

### Expected behaviour

Shift + letter and capital letters should not be able to be distinguished. (They aren't.)

All of the other combinations above should write a different message to the screen. (Except the ones with Alt, and Win+T in Windows).

<Shift+Ñ> should work to type Ñ.

**Comment by glacambre** [comment]
`:nnoremap <c-Ñ> :echo <c-Ñ>` and then `:call nvim_input('<c-Ñ>')` works on master, so I'll close this issue. @ArenaL5 let me know if you can still reproduce this with neovim nightly and I'll reopen :).
