### ISSUE TITLE
Neovim-qt “takes too long to respond” if there is an error message on initialization.

### ISSUE THREAD

**Issue by ArenaL5** [neovim/neovim#8344]
### Debug data

- `nvim --version`: v0.3.0-dev. (I'm using the unstable PPA for Ubuntu AMD64, and the prepackaged AMD64 version for Windows).
- GVim version 8.0 showed a dialog on error E325. I can't find the original GVim now, but I don't remember hang-ups with E492, either.
- Operating system/version: Ubuntu Desktop Artful Aardvark, AMD64; and Windows 10, AMD64
- This is strictly a bug in the QT GUI. The terminal versions don't show this error.

### Steps to reproduce:

Force a Vim error on intialization. Two easy ways of doing this are:
- Opening a file with nvim on terminal, then opening the same file with the GUI. This raises an error E325 (Found a swap file).
- Using a bad configuration file with the `-u` flag. This raises a E492 (Not an editor command).

The first method is compatible with `-u NORC`, and for the second, you can use a simple configuration file and `--noplugin`.

### Actual behaviour

A small, blank window for Neovim pop-ups. Some seconds later, this window changes size and a very professional-looking message appears: “Neovim is taking too long to respond”, with a button to Retry.

Pressing this button blanks out the window, and some seconds later, the same message appears.

![I'm serious. It really looks nice.](https://user-images.githubusercontent.com/37388405/39487706-64cf3264-4d80-11e8-922b-e4ab376c5f0b.png)

### Expected behaviour

Neovim-qt should be able to resolve these errors like the terminal version does, either by using a dialog in a separate window (like GVim does) or displaying the error in the main window like it does when I raise E325 at mid-session.

**Comment by jamessan** [comment]
Already [reported](https://github.com/equalsraf/neovim-qt/issues/78) in the neovim-qt repo and it references the relevant neovim issues.
