### ISSUE TITLE
Incorrect behavior if the indent is adjusted while popup is open

### ISSUE THREAD

**Issue by mrbiggfoot** [neovim/neovim#8345]
Initially [reported in mucomplete](https://github.com/lifepillar/vim-mucomplete/issues/99), but turned out to be a neovim bug.

- `nvim --version`: latest
- Vim (version: ) behaves differently? Yes, vim does not change the alignment until `<C-y>` is pressed (see the sequence below). Or maybe I have a different vim config? Need to find out.
- Operating system/version: CentOS 6.9
- Terminal name/version: iterm2 3.1.6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Create this file and name it `a.vim` (don't worry about its correctness):
```
function enh
endfunction

function F()
```
Run this sequence:
```
nvim -u NORC a.vim
Goen<C-n><BS>d<C-y>
```

### Actual behaviour
The buffer has "eendfunction":
![screen shot 2018-05-01 at 11 57 28 am](https://user-images.githubusercontent.com/12175496/39488358-dd08d2fc-4d36-11e8-828c-5c3adc5e7504.png)

### Expected behaviour
"endfunction"
Also, it would be nice to make autocompletion popup change the position after the word alignment is changed (after `d` in the sequence above).

**Comment by mrbiggfoot** [comment]
I just verified that `vim` behaves differently indeed:
```
vim
source ~/neovim/share/nvim/runtime/indent/vim.vim
set autoindent smartindent
e a.vim
Goen<C-n><BS>d<C-y>
```
In `vim`, the word's indent is not changed while the completion popup is open. Not sure which way is better though.

**Comment by mrbiggfoot** [comment]
Here is my version of the fix, based on https://github.com/neovim/neovim/pull/8349:
```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index eaa7844..7ca6232 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -1704,6 +1704,15 @@ change_indent (
       ai_col = 0;
     else
       ai_col -= insstart_less;
+
+    if (pum_visible()) {
+      if (compl_col <= insstart_less)
+        compl_col = 0;
+      else
+        compl_col -= insstart_less;
+      pum_undisplay();
+      ins_compl_show_pum();
+    }
   }

   /*
```
https://github.com/mrbiggfoot/neovim/commit/580f4a4467dcb4d1db1bfeb68a87f909fdf36e19

**Comment by justinmk** [comment]
Did you send a PR?

**Comment by mrbiggfoot** [comment]
@justinmk I did not. I was under impression that the preferred fix is to make the behavior in line with `vim`. Also, I thought that @lePerdu would pick it up in #8349 if needed. But I can send a PR if you are going to merge my fix.

**Comment by justinmk** [comment]
@mrbiggfoot Understood, thanks. Replied in #8349.
