### ISSUE TITLE
window-local 'path' option

### ISSUE THREAD

**Issue by leeren** [neovim/neovim#8346]
### Background
Paths (see `:h paths`) provide fast and seamless project browsing using commands like `gf`, `:find`, and `:sfind`, whereby the specified file to be found is searched for within the directories delineated by `set path?`. Currently, however, the `path` can only be made global to all buffers via `:set path=path/to/dir`, or local to a specific buffer or window via `:setlocal path=path/to/dir` (see `:h global-local`). 

### Benefit of feature
Utilizing local paths that allow path sharing between windows would allow for discrete separation of project browsing when working with multiple project directories. This would be very much analogous to the current functionality of being able to create new argument lists specific to the current window (see `:h arglocal`). Right now, to incorporate multiple paths for working with multiple projects, the best a user can do is manually add (`:set path+=`) or remove (`:set path-=`) from the current `path`. The problem with this is that searching for files within your project necessitates going through all project file paths, which also may contain duplicate files. The alternative approach of creating a bunch of buffer-local paths (`:setlocal path=`) for every buffer in your project is wasteful and inefficient.

### Implementation Interface
I believe this functionality could be achieved by adding the below four functions:
```
:pathl[ocal]                  Make a local copy of the global buffer path.
:pathl[ocal] {path}           Define a new path, which is local to the current window.
:pathg[lobal]                 Use global buffer path for the current window.
:pathg[lobal] {path}          Define new global buffer path and use it for the current window.
```
### Closing remarks
As an avid Vi user, I strongly believe that adding this particular feature would greatly bolster the ability to use Neovim as a lightweight IDE. The `path` variable is a quintessential component of vim which lets users browse projects quickly and efficiently. By incorporating window-shareable local paths, users can manage a clear _**separation of directory browsing**_ when working with multiple projects.

**Comment by justinmk** [comment]
> The alternative approach of creating a bunch of buffer-local paths (:setlocal path=) for every buffer in your project is wasteful and inefficient.

Wasteful in what sense? If it's a question of RAM, you'll be shocked to learn how Vim undo is implemented...

> By incorporating window-shareable local paths, users can manage a clear separation of directory browsing when working with multiple projects.

Clear in what sense? 

Have you considered https://github.com/tpope/vim-projectionist ? What's missing from it? I would use it as a basis for any discussion of a "project" concepts in N/Vim.

**Comment by justinmk** [comment]
> Vim has localized settings for managing buffers (the arg list), localized settings for managing working directories (the "tab-local" or "window-local" working directories), but not localized settings for paths.

'path' _is localized_ to buffer. It's confusing that you say "localized" when you mean "window-local".

> The biggest reason I am advocating this over many other features which can be easily be fixed by plugins or mappings is because it so clearly fulfills an essential means of multiplexing projects that Vim otherwise excels at.

I think you're the first person I've met who actually likes Vim's _window-local_ option behavior :) 

I don't think making 'path' window-local is going to solve the project-multiplexing use-case for most people. It would also be backwards-incompatible AFAICT.

**Comment by leeren** [comment]
> 'path' is localized to buffer. It's confusing that you say "localized" when you mean "window-local".

You're right. I should have said "window-local" paths that support inheritance. 

> I think you're the first person I've met who actually likes Vim's window-local option behavior :)

I am trying very hard to use all of Vim's essential features as they were designed for!

> I don't think making 'path' window-local is going to solve the project-multiplexing use-case for most people. It would also be backwards-incompatible AFAICT.

I agree it would probably be backwards-incompatible. And yes, it would not, but I think it would be a pretty big leap forward to doing so. On the other hand, based off your comments, it does seem that this feature is pretty under-utilized. Hopefully we can keep this thread open to see other feedback?

**Comment by justinmk** [comment]
Merging this issue with https://github.com/neovim/neovim/issues/8610
