### ISSUE TITLE
"set termguicolors" breaks my colors

### ISSUE THREAD

**Issue by vjsingh** [neovim/neovim#8352]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently? Unknown
- Operating system/version: OSX 10.13
- Terminal name/version: iTerm2 build 3.1.6
- `$TERM`: Not set?

### Steps to reproduce using `nvim -u NORC`

```
In .vimrc:  set termguicolors
nvim

```

### Actual behaviour

<img width="598" alt="screenshot 2018-05-02 13 45 32" src="https://user-images.githubusercontent.com/318312/39539935-314fd8be-4e0f-11e8-9e61-c4f1825abd39.png">

### Expected behaviour

<img width="586" alt="screenshot 2018-05-02 13 45 13" src="https://user-images.githubusercontent.com/318312/39539931-2dca494a-4e0f-11e8-9523-415d384c8aa7.png">

### Notes

When I add "set termguicolors" to my .vimrc my colors seem to break. I believe it is mostly working without "set termguicolors," but I presume without all the colors. If I remove the "set termguicolors" line I get the "expected" screenshot.

I am using the vim-colors-solarized plugin with vim-plug for the syntax colors. Perhaps that is related, because I get a different result with "nvim -u NORC" which it seems is disabling the plugin?

This is what my .vimrc looks like:
set background=dark
colorscheme solarized
set termguicolors

I tried adding the below fixes to my .vimrc and they don't fixed the problem:
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set t_Co=256
set background=dark
colorscheme solarized
set termguicolors

**Comment by vjsingh** [comment]
It looks like solarized doesn't support truecolor. Switched to Solarized8 and everything is good. Had a hell of a time finding that (guess I'm outdated) so leaving this up in case it helps anyone

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/colorscheme-highlight-differ-from-vim/3034/3
