### ISSUE TITLE
Tab line not redrawed properly when using commands with huge output

### ISSUE THREAD

**Issue by andreyorst** [neovim/neovim#8354]
- `nvim --version`: NVIM v0.3.0-1193-ge46534b42  
Package: [neovim-git](https://aur.archlinux.org/packages/neovim-git/) from AUR
- Vim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:02:12)
Included patches: 1-1542 
  - behaves differently: yes
- Operating system/version: Arch Linux
- Terminal name/version: termite, konsole, termux
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`
1. `nvim -u NORC`
2. `:tabnew test` <kbd>Cr</kbd>  
Look at the top bar - it should show `[No Name] test` tabs, like so:  
![image](https://user-images.githubusercontent.com/19470159/39560878-4f8d5234-4eaa-11e8-9138-3352588912ec.png)
3. `:echo system("ls /usr/share")` <kbd>Cr</kbd> (or `:version`<kbd>Cr</kbd>, it doesn't matter actually)  
Screen should contain output from top to botom:
![image](https://user-images.githubusercontent.com/19470159/39560861-3d0ca272-4eaa-11e8-94d1-4988d1a66ea5.png)
4. Press <kbd>Esc</kbd>  
See tab line not redrawed:  
![image](https://user-images.githubusercontent.com/19470159/39560897-7f7b289a-4eaa-11e8-8866-b4db75c712d8.png)

### Actual behaviour
Tab bar not redrawed properly.
### Expected behaviour
Tab bar redrawed properly. In Vim for sure. Same steps for `vim -u NONE` work well.

---
This issue also affects plugins like airline. See https://github.com/vim-airline/vim-airline/issues/1718

**Comment by justinmk** [comment]
Ctrl-L is a workaround.

**Comment by andreyorst** [comment]
> Ctrl-L is a workaround.

Yeah, or switching tab back and forth. But it's not ok. Because I rely on such output im my plugin, and it works good in vim, but results in this issue in neovim.

**Comment by bfredl** [comment]
Does this patch help:

```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 2e64eb864..b615f69cd 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -309,6 +309,9 @@ void update_screen(int type)
         if (wp->w_winrow + wp->w_height + wp->w_status_height > valid) {
           wp->w_redr_status = true;
         }
+        if (valid == 0) {
+          redraw_tabline = true;
+        }
       }
     } else if (msg_scrolled > Rows - 5) {  // clearing is faster
       type = CLEAR;
```

**Comment by andreyorst** [comment]
![image](https://user-images.githubusercontent.com/19470159/40370732-953f1e5e-5de9-11e8-99d2-09042eaba4b7.png)
![image](https://user-images.githubusercontent.com/19470159/40370760-ab19ceea-5de9-11e8-90d4-a41be5022901.png)
Still happens on NVIM v0.3.0-1282-g1642917f9

**Comment by dyllandry** [comment]
This is still happening on NVIM v0.4.3 as well.
