### ISSUE TITLE
after `inoremap jk <esc>` `jk` leaves artifact on buffer

### ISSUE THREAD

**Issue by osa1** [neovim/neovim#8357]
- `nvim --version`: HEAD
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 18.04
- Terminal name/version: st
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

After adding this binding `inoremap jk <esc>`, `jk` leaves an artifact (the character `k`) on the screen.

### Expected behaviour

After `jk` I shouldn't see anything on the buffer.

**Comment by osa1** [comment]
Happens with xterm as well.

**Comment by osa1** [comment]
![screenshot_2018-05-04_11-50-37](https://user-images.githubusercontent.com/448274/39619680-633af1fa-4f91-11e8-8037-32e0ef61302d.png)

**Comment by KillTheMule** [comment]
I tried with xterm too, both with `TERM=xterm-256color` and `TERM=xterm`, but it did not happen.

**Comment by osa1** [comment]
Perhaps related with dependencies. I'm on Xubuntu 18.04.

**Comment by KillTheMule** [comment]
I'm actually not at HEAD, but at gd7f7cef. Maybe you could give that a shot to see if it's a recent problem? I can't easily upgrade here, otherwise I'd jump to HEAD to try...

**Comment by justinmk** [comment]
Confirmed with HEAD. Can you bisect?

**Comment by mhinz** [comment]
Broken since d42f934bcb3e9e876e5e7ba0ab5cd824175fd10c

@ZyX-I

**Comment by justinmk** [comment]
@mhinz Thanks. One could now bisect the changes from that commit :)
