### ISSUE TITLE
Make $PATHS work with runtimepath

### ISSUE THREAD

**Issue by Warpulis** [neovim/neovim#8359]
- `nvim --version`:0.2.2
- Vim (version: ) behaves differently? idk
- Operating system/version: Windows 7
- Terminal name/version: n/a

### Actual behaviour
A short detour before describing the issue:
the following line in the init.vim allows you to use nerdtree(example):
set runtimepath^=C:/temp/nerdtree-master/
what isn't working:
set runtimepath^=C:\temp\nerdtree-master\

This makes the following not possible:
execute "set runtimepath^=".$HOME."/nerdtree-master/"

instead i have to do the following:
set good_path = substitute($HOME, "\\", ”/”, "g")
execute "set runtimepath^=".good_path."/nerdtree-master/"

The reason for this is that on windows, all PATHs (like $HOME, $VIM etc.) from Neovim have \ in their string.
### Expected behaviour
Simply being able to concenate the two paths into a valid runtimepath.

**Comment by jamessan** [comment]
> what isn't working:
> set runtimepath^=C:\temp\nerdtree-master\

Yes, because backslashes are special in `:set` -- `:help option-backslash`.

You can either use the example you already gave or use `let &rtp = ...`.

**Comment by huynle** [comment]
I'm trying to solve similar issues with my neovim, when trying `:set option-backslash`, nvim throws an error saying it is an unknown option. Can someone help me understand why it is not working?

**Comment by jamessan** [comment]
It's a help topic, not an option -- `:help option-backslash`.
