### ISSUE TITLE
SIGABRT on C-\ (control-backslash) in minibuffer

### ISSUE THREAD

**Issue by wchargin** [neovim/neovim#8361]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently?
- Operating system/version: Linux Mint 18.2 Sonya
- Terminal name/version: gnome-terminal 3.18.3
- `$TERM`: xterm-256color-italic

### Steps to reproduce using `nvim -u NORC`

 1. Invoke `nvim -u NORC some_file`.
 2. Insert some text and write the file.
 3. Insert some more text; do not write the file.
 4. In a separate terminal, `echo "something else" >some_file`.
 5. In Neovim, attempt to write the file. The standard warning "The file
    has been changed since reading it!!!" appears, prompting for `y/n`.
 6. Press `C-\` (control-backslash).

### Actual behaviour

Neovim exits with `SIGABRT`; all unsaved changes to all buffers are lost.

### Expected behaviour

Pressing `C-\` should be the same as pressing `n`, or at the very least
should do nothing. Note that `C-c` in this case does not kill Neovim
with SIGINT.

**Comment by justinmk** [comment]
This was fixed on master.
