### ISSUE TITLE
Kubuntu 18.04: A 'q' is placed before all inputs and commands.

### ISSUE THREAD

**Issue by soundconjurer** [neovim/neovim#8373]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? Yes, the bug doesn't appear.
- Operating system/version: Kubuntu 18.04 LTS
- Terminal name/version: konsole 17.12.3
- `$TERM`:

### Steps to reproduce
1) In terminal, (only) as root, open a new or existing file.
2) Hit 'i' for insert.
3) Then hit 'Esc'.
4) A 'q' will appear wherever the cursor is when it enters insert mode.
5) When going to exist, ':q', it will appear as ':qq'.

### Actual behaviour
The 'q' is entirely a visual affect. It doesn't appear when saving and exiting a document when in the text body.
It does not interfere with saving a document. It does however, make it quite confusing and alarming if one doesn't know it's visual error.
![screenshot_20180507_232500](https://user-images.githubusercontent.com/6320302/39738101-af2d94f4-524e-11e8-9f86-d5cce90641b1.png)

### Expected behaviour
No 'q's should appear.

**Comment by KillTheMule** [comment]
See https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes.
