### ISSUE TITLE
nvim-qt always throw "Press Enter or type command to continue" message!

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#8380]
- `nvim --version`: 
```
NVIM v0.3.0-1228-g7efece4da
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
```
- Vim (version: ) behaves differently? yes
- Operating system/version: windows 7
- Terminal name/version: N/A
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

run nvim-qt.exe through double click, input the below command:
```vim
:au VimLeave * py3 import subprocess; subprocess.Popen("cd", shell=True)
```
then quit nvim by typing `:q`,  "Press Enter or type command to continue" message is displayed at the bottom, if you press enter, there are endless such messages.

### Expected behaviour
nvim quit silently.

**Comment by KillTheMule** [comment]
You should report that at the neovim-qt repository. There are already some issues about quitting, maybe this one's already there.

**Comment by adelarsq** [comment]
@Yggdroot @KillTheMule Can this issue already be closed?
