### ISSUE TITLE
neovim got stuck with error message "clipboard: error invoking win32yank".

### ISSUE THREAD

**Issue by Yggdroot** [neovim/neovim#8382]
- `nvim --version`:
```
NVIM v0.3.0-1228-g7efece4da
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/gcc.exe -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
```
- Vim (version: ) behaves differently? yes
- Operating system/version: windows 7
- Terminal name/version: nvim-qt.exe
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

enter nvim-qt.exe, run the following vim command:
```vim
:redir @+
:version
```
neovim got stuck with error message "clipboard: error invoking win32yank".

### Expected behaviour
no error.

**Comment by Yggdroot** [comment]
Due to it is a bug of neovim-qt, close it here.

**Comment by darylducharme** [comment]
I see this whenever I use :Vexplore

Not stuck, but it opens it. Then today, downloaded the latest veonim and called Vexplore with the same effect.

**Comment by michael-angelozzi** [comment]
Get the same error, when trying to use the built in file browser (:Lex)
