### ISSUE TITLE
set colorcolumn=+1 only works in *.vim files

### ISSUE THREAD

**Issue by iasj** [neovim/neovim#8384]
- `nvim --version`: 
```console
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Arch Linux (rolling release)
- Terminal name/version: `termite v13`
- `$TERM`: `screen-256color`

### Actual behaviour

I noticed that neovim's `colorcolumn=+1` is working only with vim files. 

Just to be sure, I logged as root (whose home directory doesn't have any nvim settings, i. e. blank config, no plugins) and opened two files

`#nvim file.vim`
![file vim](https://user-images.githubusercontent.com/7888397/39972537-a983eb90-56e8-11e8-9052-875db41c2eda.png)

`#nvim file.c`
![file c](https://user-images.githubusercontent.com/7888397/39972536-a94e9c88-56e8-11e8-926c-39f185c237d3.png)

Is this a bug? I was expecting to have the highlighted column for every filetype.

Regards!

**Comment by chrisbra** [comment]
> Is this a bug? I was expecting to have the highlighted column for every filetype.

`colorcolumn=+1` only makes sense, when the `textwidth` option is set, so check that your other file has actually `textwidth` option set (e.g. it is not 0)

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.
