### ISSUE TITLE
Wildmenu remains visible.

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#8385]
### Steps to reproduce
```
nvim -u NORC
:h<Tab><Space>
```

### Actual behaviour
Wildmenu remains visible.

### Expected behaviour
Wildmenu should disappear. According to the docs and Vim behavior:
> The "wildmenu" mode is abandoned when a key is hit that is not used for selecting a completion.

Note that `wildmenumode()` does return 0.

NVIM v0.3.0-1211-g3a6b80f2f (also happening on NVIM v0.2.2)
Vim 8.0 behaves differently.
Linux, Termite. `$TERM` = `xterm-termite`.

**Comment by justinmk** [comment]
Confirmed. Doesn't happen with Vim:

    vim -N -u NORC +"set wildmenu wildmode laststatus=2"

**Comment by akarle** [comment]
I would like to try to tackle this as a first contribution!
