### ISSUE TITLE
luacheck rockspec is down?

### ISSUE THREAD

**Issue by PabloReszczynski** [neovim/neovim#8387]
I'm getting this error when compiling v0.2.2:
`Error: Error fetching file: Failed downloading https://raw.githubusercontent.com/mpeterv/luacheck/master/luacheck-scm-1.rockspec - luacheck-scm-1.rockspec`

The url is returning 404.

**Comment by justinmk** [comment]
this was fixed in https://github.com/neovim/neovim/commit/e2afcfb020fa16b465dd25d3455cd00487e68915 .
