### ISSUE TITLE
Visual increment (v_CTRL-A) does not always increment the last number in selection

### ISSUE THREAD

**Issue by JohanAR** [neovim/neovim#8392]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently? The Vim I have doen't support v_CTRL-A
- Operating system/version: Ubuntu 16.04 LTS derivate
- Terminal name/version: Gnome Terminal 3.18.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

5i1<CR><Esc>ggvG<C-A>
```

### Actual behaviour

2
2
2
2
1

### Expected behaviour

2
2
2
2
2

The visual mode cursor is on the empty line after the last 1 so it should be inside the selection. If I do the same procedure but with a letter instead of 1 and tilde instead of Ctrl-A it changes the case of all of them. If I use Shift-V instead of V it behaves as expected. Ctrl-X exhibits the same behaviour.

**Comment by justinmk** [comment]
Still present on 0.3.0

**Comment by justinmk** [comment]
Fixed in 0.3.2.
