### ISSUE TITLE
[Feature request] Completion item select change event

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8396]
## Why this event is needed?

Some css omni completion would insert text like `padding: `, they always have `: ` inserted at the end without check current line, what I want implement is when the completion item selection change, check the line and add `: ` if necessary.  But it can't be done well with `TextChangeP` and `CompleteDone` events. 
 
The `TextChangeP` event (implemented in #8377) could fired by user input, or when `<C-n>` or `<C-p>` used to change the completion item.  On the plugins side, it seems no way to figure out the reason, so it's hard to decide what to do with current inserted text.

The `CompleteDone` also have it's problem for this job, if the user change item by `<C-n>` and then press `<space>` the `CompleteDone` would then fired just before character inserted, it's desired behavior, but it would be wired if plugin insert  extra text at this time.

One possible solution is make completion item word empty to force user confirm with the items (since no text inserted when using `<C-n>` or `<C-p>`),  the problem is that an extra key stroke is required.

A variable like `v:complete_seleted_item` could also be helpful.

**Comment by Shougo** [comment]
> Some css omni completion would insert text like padding:, they always have : inserted at the end without check current line, what I want implement is when the completion item selection change, 

It seems omnifunc problem.

**Comment by chemzqm** [comment]
I found the event sequence of `InsertCharPre` and `CompleteDone` depends on what user typed, so I think I could make use of it.
