### ISSUE TITLE
Windows: E739 with multibyte HOMEPATH

### ISSUE THREAD

**Issue by folx** [neovim/neovim#8398]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently? As far as I remember.
- Operating system/version: Windows 10 - 1709
- Terminal name/version: any, actually

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

C:\Users\følx>nvim -u NORC
Error detected while processing function <SNR>14_LoadRemotePlugins[1]..<SNR>14_GetManifest[1]..<SNR>14_GetManifestPath:
line   16:
E739: Cannot create directory C:\Users\f<f8>lx: operation not permitted
Press ENTER or type command to continue

### Expected behaviour

Pressing ENTER or any other don't actually produce anything.

I guess the ø within the %HOMEPATH% is misinterpreted as <f8> somehow, but don't have any clue on how to avoid that.

**Comment by justinmk** [comment]
This might be related to https://github.com/neovim/neovim/pull/7920 . Could you try the [artifact](https://ci.appveyor.com/project/neovim/neovim/build/18076/job/914hxo752xi16mq7/artifacts) from that PR and see if it fixes your issue?

**Comment by janlazo** [comment]
Is this still happening with the mingw build on nightly?

**Comment by justinmk** [comment]
I can reproduce some similar behavior in `NVIM v0.3.0-1184-g4744142fa`, and it does seem to be fixed in #7920 .

**Comment by folx** [comment]
Behaviour still present on 0.3.1 and v0.3.2-338-ga466bd292 from chocolatey

**Comment by mattia72** [comment]
I had the same issue. 
As workaround, I set XDG_DATA_HOME environment variable to another directory. (#3470)

**Comment by justinmk** [comment]
@mattia72 does this artifact fix the problem? https://ci.appveyor.com/project/neovim/neovim/builds/22604657/job/g4haobypi4l1b9lw/artifacts

**Comment by mattia72** [comment]
> @mattia72 does this artifact fix the problem? https://ci.appveyor.com/project/neovim/neovim/builds/22604657/job/g4haobypi4l1b9lw/artifactsx
Unfortunately not. It works only if I set XDG_DATA_HOME

**Comment by justinmk** [comment]
@mattia72 what is the exact error you see?

Also, I just pushed an update to https://github.com/neovim/neovim/pull/7920 which was reported to fix #9267 which is similar to this issue. Once the AppVeyor build is done, please try the artifact: https://ci.appveyor.com/project/neovim/neovim/builds/22670269/job/xvavudi6odwymjt3/artifacts

**Comment by justinmk** [comment]
@mattia72 please try this: https://ci.appveyor.com/project/neovim/neovim/builds/22685106/job/0m3l013ywtgjynic/artifacts

**Comment by mattia72** [comment]
> @mattia72 please try this: https://ci.appveyor.com/project/neovim/neovim/builds/22685106/job/0m3l013ywtgjynic/artifacts

It works 👍 Thank you!
