### ISSUE TITLE
Rendering bug [blank lines] when using kitty terminal

### ISSUE THREAD

**Issue by MachFour** [neovim/neovim#8400]
Hi, I recently migrated to Kitty and have been having the missing line issue (https://github.com/kovidgoyal/kitty/issues/160). Looks like it was resolved for some people but still is present for me. The developer of Kitty suggests that it is a bug in neovim.

- `nvim --version`: `NVIM v0.3.0-1233-gde7a0bdc3` (built using AUR neovim-git package today)
- Vim (version: ) behaves differently? Yes, with `&t_ut=''` workaround.
- Operating system/version: Linux 4.16.8-1-ARCH
- Terminal name/version: `kitty --version: 0.9.1.r71.g082c771-1` (built using AUR kitty-git package yesterday)
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set relativenumber
:colors morning
iddd<ESC>
yy12p
o<CR>
```

### Actual behaviour
Line below the cursor is not drawn properly (completely black but the background is white, numbering not visible)
### Expected behaviour
Line below the cursor is drawn with correct background colour and numbering visible.

**Comment by justinmk** [comment]
> The developer of Kitty suggests that it is a bug in neovim.

That was in regards to BCE, which is no longer done unless $XTERM_VERSION is defined.

> Vim (version: ) behaves differently? Yes, with `&t_ut=''` workaround.

That suggests it's BCE-related, which as I mentioned in https://github.com/kovidgoyal/kitty/issues/160 , is no longer used in Nvim unless $XTERM_VERSION is defined. 

And most of the reports there later turned into "oops, it works now" somehow.

**Comment by MachFour** [comment]
I'm not sure where to go from here in terms of avoiding this problem, because as I said I'm still experiencing it in latest builds of both programs.

When I mentioned that the developer of Kitty suggested that it is a bug in neovim, I'm referring to the issue I raised yesterday about precisely this bug, at https://github.com/kovidgoyal/kitty/issues/542.

So are you saying that this is _not_ a bug in neovim?

**Comment by MachFour** [comment]
Also, I played with defining $XTERM_VERSION or explicitly not defining it when running neovim, but this bug still happened whether or not it was defined

**Comment by justinmk** [comment]
I can't reproduce and I'm not going to spend my time on it. Patch is definitely welcome.

Alternatives are to use Vim or use a different terminal emulator.

**Comment by MachFour** [comment]
Fair enough, thanks for your response and for all your incredible work on Neovim.

I'll dig into it further if I can find the time :)

**Comment by MachFour** [comment]
Just putting some working here since I've spent the last few hours investigating this.

These are the raw commands (printed using `kitty --dump-bytes`) that Kitty receives at the moment that the blank line appears. They correspond to the before and after screenshots I've included below; the only key I pressed in between them was Enter

Before:
![2018-05-17-22 25 43](https://user-images.githubusercontent.com/5557146/40177331-9b4e30b2-5a21-11e8-91a6-0682f363099d.png)

After: 
![2018-05-17-22 23 37](https://user-images.githubusercontent.com/5557146/40177325-963408ae-5a21-11e8-9f36-cbe697cffd22.png)

```
screen_reset_mode 25 1
screen_cursor_position 1 3
screen_designate_charset 0 66
select_graphic_rendition 0 
select_graphic_rendition 38 5 130 
draw 4
screen_cursor_position 2 3
draw 3
screen_cursor_position 3 3
draw 2
screen_set_margins 5 24
screen_cursor_position 3 4
screen_carriage_return
screen_linefeed
screen_linefeed
screen_insert_lines 1
screen_set_margins 0 0
screen_cursor_position 5 1
screen_cursor_position 3 4
screen_designate_charset 0 66
select_graphic_rendition 0 
screen_carriage_return
screen_linefeed
screen_linefeed
screen_erase_in_line 0 0
screen_cursor_position 3 4
screen_carriage_return
screen_linefeed
select_graphic_rendition 38 5 130 
draw   1 
screen_carriage_return
screen_linefeed
draw   0 
screen_set_mode 25 1
```
Then there are a few commands to update the line number in the statusline, but the blank line has already appeared at this point:
```
screen_reset_mode 25 1
screen_cursor_position 25 115
screen_designate_charset 0 66
select_graphic_rendition 0 
select_graphic_rendition 1 
select_graphic_rendition 7 
draw 5
screen_cursor_position 5 5
screen_set_mode 25 1
```

So it looks line neovim doesn't even touch the blank line (line 6). Though neither does it touch any line after that, and the others get shifted down fine.

**Comment by MachFour** [comment]
Okay apologies Justin, it was actually a bug in Kitty.

But I have to say, neovim code is very nicely written! It was pleasant to step through ;)

**Comment by justinmk** [comment]
No worries, thanks for investigating !
