### ISSUE TITLE
I see other issuse, but I still don't know how to this "set clipboard+=unnamed" yet.

### ISSUE THREAD

**Issue by seaweedman** [neovim/neovim#8407]
- `nvim --0.30`

I can't use neovim's clipboard with windows10's clipboard.

![image](https://user-images.githubusercontent.com/22971135/40223192-c8b10b0e-5ab4-11e8-9eaa-43b22394a5c2.png)

**Comment by justinmk** [comment]
The issue tracker is not for usage questions.

**Comment by seaweedman** [comment]
!
