### ISSUE TITLE
Using any command inserts 'q' character at current cursor position in some terminals

### ISSUE THREAD

**Issue by jplatte** [neovim/neovim#8412]
- nvim version: 0.2.2 (from arch linux repositories)
- Vim (version: 8.0, also from arch repositories) doesn't have this issue
- Operating system/version: arch linux
- Terminal name/version: several (see below)
- `$TERM`: several (see below)

### Steps to reproduce using `nvim -u NORC`

```
# Log in at virtual console
nvim -u NORC
# Press i
```

### Actual behaviour

A 'q' is inserted at the beginning of the buffer. With 'inserted', I only mean visually; when I type it is actually overwritten and these auto-inserted characters disappear when saving and reloading a file.

### Expected behaviour

No character should appear ^^"

### Details

I started having this issue outside of the virtual console, in my default Terminal konsole. I found out it only happens with my current font Hasklig, which is Source Code Pro patched with ligatures. I haven't tried other ligature-containing fonts yet, but this problem is also not reproducible with `-u NORC`, which I just found out while writing this bug report. This problem is however reproducible for me in virtual consoles (`Ctrl+Alt+F<n>`) even with `-u NORC`. Nothing of this sort happens with vim (or any other program).

`$TERM` on virtual console: `linux`
`$TERM` in konsole: `xterm-256color`

**Comment by justinmk** [comment]
As the issue template mentions, please check the FAQ before reporting.

https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

**Comment by jplatte** [comment]
@justinmk: that FAQ entry says this should only happen for seemingly xterm-compatible terminals though. For me it happens on the virtual console with TERM=linux.

**Comment by justinmk** [comment]
It works in Linux console on the machines I've tried. And the FAQ says clearly how to disable the behavior if not.
