### ISSUE TITLE
segfault on redo buffer replace from shell command

### ISSUE THREAD

**Issue by DrRibosome** [neovim/neovim#8424]
In a fairly long running session with a number of open buffers, tabs, etc, I replaced a file contents with `0,$!yapf`, which ran successfully. However, after running an undo `u` followed by `<c-r>` to redo, i got a segfault. 

I was unable to reproduce this in a fresh neovim process however (I tried creating one/several files, splits, buffers, etc and running the yapf buffer filter command), so I suspect it might have something to do with the accumulated state

```
% nvim --version
NVIM v0.3.0-1250-ge121b1d
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/xxx/git/neovim/build/config -I/home/xxx/git/neovim/src -I/home/xxx/git/neovim/.deps/usr/include -I/usr/include -I/home/xxx/git/neovim/build/src/nvim/auto -I/home/xxx/git/neovim/build/include
Compiled by xxx

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```
% echo $TERM 
screen
```

### Actual behaviour
segfault

### Expected behaviour
undo/redo successfully

**Comment by justinmk** [comment]
Thanks, but we need a backtrace. [wiki](https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux) explains how.

**Comment by DrRibosome** [comment]
got it - ill alias `ulimit -c unlimited` to run before and report back if i encounter it again
