### ISSUE TITLE
segfault with 'autochdir' after fugitive commit

### ISSUE THREAD

**Issue by ironhouzi** [neovim/neovim#8427]
- `nvim --version`: NVIM v0.3.0-1280-g35cc15e15 (also tested on v0.2.2)
- Operating system/version: Arch Linux
- Terminal name/version: kitty 0.8.0
- `$TERM`: `screen256-color` in shell, `xterm256-color` in `:term`

### Steps to reproduce using `nvim -u NORC`

Cannot reproduce with stripped plugins.

### Actual behaviour

When making a git commit using `vim-fugitive`, I mark the file(s) to commit and hit `C` to perform the commit and get the message: `error detected while processing function <SNR>21_commit invalid range call`. The commit buffer remains open, but completely empty. When I exit NeoVIm, I get a [segfault](https://gist.github.com/ironhouzi/fab88a27cb25b0a8fb937efa5e45dac2). `autochdir` is enabled BTW.

### Expected behaviour

Display commit buffer and not segfault when exiting.

**Comment by justinmk** [comment]
can you provide your vimrc (or a dockerfile as you mentioned)?

**Comment by ironhouzi** [comment]
[init.vim](https://gist.github.com/ironhouzi/6733d705fd1bc46fcdb0a624bdb9f8b7)

**Comment by ironhouzi** [comment]
Since upgrading to v0.3.0, I'm not able to consistently reproduce the segfault any longer, but I still get errors about `autochdir` after saving and exiting the fugitive commit buffer.

Don't know how relevant this information is, but if I avoid loading `g:python_host_prog`/`g:python3_host_prog`, the error does not occur.

**Comment by justinmk** [comment]
>  I still get errors about autochdir after saving and exiting the fugitive commit buffer.

What is the full, exact error message?

**Comment by zeertzjq** [comment]
Does this bug still exist?
