### ISSUE TITLE
:terminal events: TermEnter/TermLeave (like InsertEnter/InsertLeave)

### ISSUE THREAD

**Issue by mox-mox** [neovim/neovim#8428]
Is there any progress for a `TermEnter` and `TermLeave` autocommands?
And could we get something like `<C-o>` `<C-\><C-o>` for terminal mode?

### Actual behaviour
Not implemented
### Expected behaviour
`TermEnter` autocommand is triggered when in a terminal buffer and entering terminal mode.
`TermLeave` autocommand is triggered when in a terminal buffer and leaving terminal mode.
`<C-o>` When in a terminal buffer and in terminal mode, execute one command in normal mode then return to terminal mode.
`<C-\><C-o>` Like `<C-o>` but do not change the cursor position.

It might be desirable to prefix those two commands with another `<C-\>` so this sequence will not clash with other terminal operation.

**Comment by usama54321** [comment]
Hi,

This is my first issue on neovim, and am quite new to the neovim codebase. I am hoping to get started contributing to the repo. 

I went through the codebase, and was able to implement the autocommands `TermEnter` and `TermLeave`. However, I went through the code base for `<C-o>`, and it seems to have a number of edge cases about where the cursor should be positioned after normal mode exits. I am trying to understand the edge cases, and will try implementing it in terminal. However, this might not be the best issue to work on for someone new to the code base.

Regards,
Usama Hameed

**Comment by justinmk** [comment]
@usama54321 ctrl-o does not exist terminal-mode, so I don't think that's relevant.

**Comment by fran496** [comment]
Hello, I see that this issue hasn't been solved yet. I want to contribute to the project, how should I proceed?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8550
