### ISSUE TITLE
`set expandtab` breaks blockwise-insert

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#8429]
- `nvim --version`: NVIM v0.3.0-dev
- Vim (version: ) behaves differently? Can't reproduce this bug on Vim built from 0b0f0992d46ef02fdfc1240744bef91d4299c1df (Tue May 22 21:41:30 2018).
- Operating system/version: Linux 4.13.0-41-generic #46-Ubuntu SMP x86_64
- Terminal name/version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- `$TERM`: rxvt-unicode-256color

### Steps to reproduce using `nvim -u NORC`
Use the following file:
```vimscript

function! SuspendIfInShell()
    let parent_name=substitute(system("ps -o comm= $(ps -p '" . getpid() . "' -o ppid=)"), '\n$', '\1', '')
    if (match([
                \ 'Eterm', 'alacritty', 'aterm', 'gnome-terminal', 'kitty',
        'konsole', 'login', 'lxterminal', 'mate-terminal', 'nvim-gtk',
        'qterminal', 'roxterm', 'rxvt', 'st', 'terminator', 'terminology',
        'terminte', 'termit', 'urxvt', 'urxvtc', 'urxvtcd', 'urxvtd',
        'uxterm', 'x-terminal-emulator', 'xfce4-terminal', 'xterm']
        parent_name) != -1)
        echo "Suspend: Not suspended because running in " . parent_name
    else
        :suspend
    endif
endfunction
```
First, `set expandtab` and `set ft=vim`.
Then, place your cursor on the `'` on the line that begins with "konsole" and then press <kbd>\<C-v></kbd><kbd>3</kbd><kbd>j</kbd><kbd>I</kbd><kbd>\\</kbd><kbd>\<Esc></kbd>.

### Actual behaviour
"konsole" is inserted on every line, like this:
```vimscript
                \ 'Eterm', 'alacritty', 'aterm', 'gnome-terminal', 'kitty',
                \'konsole', 'login', 'lxterminal', 'mate-terminal', 'nvim-gtk',
        'qtermin\'konsoleal', 'roxterm', 'rxvt', 'st', 'terminator', 'terminology',
        'termint\'konsolee', 'termit', 'urxvt', 'urxvtc', 'urxvtcd', 'urxvtd',
        'uxterm'\'konsole, 'x-terminal-emulator', 'xfce4-terminal', 'xterm']
        parent_name) != -1)
```
### Expected behaviour
"konsole" isn't inserted.

Additional info: Probably unrelated but I reported [another bug regarding blockwise-mode](https://github.com/vim/vim/issues/2825) to vim a month ago. It was fixed by [this patch](https://github.com/vim/vim/commit/35e802e713382d7e76232ad344af7dcd577e43de).

**Comment by glacambre** [comment]
> the message raw text would be needed

I'm not sure I understand. I can reproduce this issue by copy-pasting the text from this github issue, is there something else I should have done?

>along with the various indentation settings

Is this really needed? I thought the indentation settings were always the same when you run `nvim -u NORC`?

**Comment by chrisbra** [comment]
Yeah i figured that from the content. And Vim did re-indent after pressing `\`, right? I suppose that [patch v8.0.1682](https://github.com/vim/vim/commit/8c87a2b1fec85e4) is missing

**Comment by glacambre** [comment]
Yup, Vim correctly re-indented the block. I tried to apply the patch you linked to neovim but couldn't get it to fix this issue, I probably don't understand the code well enough to do that :/

**Comment by KillTheMule** [comment]
You could put up a PR and we'd help you through it :)

**Comment by glacambre** [comment]
This has been fixed in https://github.com/neovim/neovim/pull/8892 . Thanks @janlazo !
