### ISSUE TITLE
reStructuredText indentation bug(s) in indent/rst.vim

### ISSUE THREAD

**Issue by AWPelican** [neovim/neovim#8430]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? No, this file looks as though it has not been changed for a while.
- Operating system/version: Windows 10 and Solus Linux 3.9997
- Terminal name/version: GNOME Terminal 3.28.1, nvim-qt
- `$TERM`: xterm-256color

Good morning! I'm seeing that the filetype of `rst` always assumes you want to create a sub-list when you press <Enter>. I believe this could be classified as a bug, as it is unexpected/counterintuitive to have the filetype always creating a sub-list rather than continuing the current list. The `markdown` filetype, in contrast, has no such behavior.

The file is here: [neovim/runtime/indent/rst.vim](https://github.com/neovim/neovim/blob/946c2a8ee85830c543e389724575ae531e89b170/runtime/indent/rst.vim)

It appears that most of the purpose of this 60-line file is to implement this strange list-indent behavior. As I've mentioned in my [Vi and Vim Stack Exchange post](https://vi.stackexchange.com/questions/16190/why-does-the-rst-filetype-automatically-indent-subsequent-list-items), I believe (most of) the features in this file could be handled by native indentation settings in Neovim and `:set formatoptions+=n`.

As I see it, the file only provides two features:

1. The strange indentation behavior for lists, described above.
2. Automatic indentation of subsequent lines after `:field:` lines (however, this too saves very little work, because the function doesn't actually know when to stop indenting. You have to manually reset the indentation just like you would have to manually increase it if this were not there.)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set filetype=rst
```

### Actual behaviour

```
- First item<Enter>
  | <-- Cursor here.

- Item one<Enter>
  - Item two<Enter>
    - Item three

1. This is list item one<Enter>
   2. This is list item two<Enter>
         3. This is three<Enter>
                     4. This is four<Enter>
                                             5. This is five
```

### Expected behaviour

```
- Item one<Enter>
- Item two<Enter>
- Item three

1. This is list item one<Enter>
2. This is list item two<Enter>
3. This is three<Enter>
4. This is four<Enter>
5. This is five
```

I think other reStructuredText writers have experienced similar confusion, with this question as an example: https://vi.stackexchange.com/questions/12687/how-to-avoid-indenting-after-a-line-that-starts-with-a-number?noredirect=1&lq=1. It appears this is another user who was familiar with the `'formatoptions'` setting and with reStructuredText, but was confused by the logic set up in `indent/rst.vim`.

The fix that has worked for me is to simply comment out ``setlocal indentexpr=GetRSTIndent()``.

At least for me, this file could be two or three lines long instead of 60. I know a primary purpose of Neovim is to refactor and make the code base smaller where possible. I think the `rst` filetype is one place where this could happen. The features implemented here appear to be mostly duplication of other features already present in Neovim.

I have not yet contributed to an open source project, so I must say up front I am inexperienced at this. If it would be helpful and worthwhile, I would be happy to try to create a pull request. Or, if there are too many "landmines" that you would recommend against this as a first project to contribute to, just let me know that as well. No problem either way.

Also, anyone disagrees with my assessment of the `rst` filetype, please let me know! I know the whole "every change breaks someone's workflow," and I'm sure this is no exception. Does what I'm saying seem reasonable? Also, if this seemingly bizarre indent file somehow needs to remain for legacy compatibility, I'll understand. Since it is on the periphery of what Neovim does, and not the core functionality, I was hoping it may not be too much of a big deal.

**Comment by KillTheMule** [comment]
Hey, thanks for offering to contribute.

You've picked a bit of an odd spot though. Neovim prefers to keep up on runtime files with vim itself, so any pull requests should go there. BUT this file isn't maintained by vim, but has a maintainer, who is mentioned in the file. The first thing would be to contact him. If you don't get an answer (latest revision is quite some time ago), you might contact Bram about taking over maintainership. In that case, I think the procedure is that you make & test your changes, and simply send the to Bram, who will include them in some vim patch, which then at some point will be merged into neovim.

Sorry it's such a complicated process, but you'll have to realized the number of runtime files is huge and quite a maintainance burden, so we're pretty eager to not to additional work on the neovim side, if possible.

In the meantime, you can of course just use your ideas locally, until the changes have found their way into neovim.

**Comment by chrisbra** [comment]
I think Nikolai isn't actively maintaining any Vim runtime files anymore So basically all files where he is still mentioned maintainer are basically orphaned.
On the other hand that also means it is your possibility to step up and improve those files :)

**Comment by AWPelican** [comment]
I didn't realize that the runtime files are synced with Vim. It certainly makes sense, though. Thanks for pointing me in the right direction!
