### ISSUE TITLE
Garbage/unprintable characters emitted for every command

### ISSUE THREAD

**Issue by fritzr** [neovim/neovim#8440]
When typing any command into nvim after a fresh install (built from source) I see garbage characters emitted (see below). I have a fairly vanilla setup, but likely something is wonky with my environment as I assume v0.2.2 works for some people.

- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /data/gcc-trunk/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/data/src/neovim/build/config -I/data/src/neovim/src -I/data/src/neovim/.deps/usr/include -I/data/src/neovim/.deps/usr/include -I/data/src/neovim/.deps/usr/include -I/data/src/neovim/.deps/usr/include -I/data/src/neovim/.deps/usr/include -I/data/src/neovim/.deps/usr/include -I/usr/include -I/data/src/neovim/build/src/nvim/auto -I/data/src/neovim/build/include

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/support/share/nvim"

Run :checkhealth for more info
```
- Vim (7.4) behaves normally
- Operating system/version: CentOS 6.9 2.6.32-696.23.1.el6.centos.plus.x86_64
- Terminal name/version: gnome-terminal 2.31.3
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

* `nvim -u NORC`
* type any command (:, R, I, O, C, etc...)

### Actual behaviour
* typing `:` causes `:\x01b2 q` to appear at the bottom-left in the command bar:
![nvim-colon](https://user-images.githubusercontent.com/2230564/40557367-db5a899c-601d-11e8-92a8-e48bc0307996.png)

* typing any other command injects similar garbage. shown below are I, C, R, Y, D, ^C, gg...
![nvim-garbage](https://user-images.githubusercontent.com/2230564/40557753-29a06864-601f-11e8-9b69-0812d9ad4bb9.png)

* pressing ^L clears the garbage
![nvim-garbage2](https://user-images.githubusercontent.com/2230564/40557774-3d514aae-601f-11e8-9957-efe5c3f02608.png)

### Expected behaviour
* When typing ':' only a colon appears (as with vim):

![vim-colon](https://user-images.githubusercontent.com/2230564/40557374-df962ce6-601d-11e8-8fc7-7cde1f623178.png)

* typing any other command... shouldn't inject garbage into the screen buffer

**Comment by justinmk** [comment]
please check the FAQ before reporting. https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

**Comment by fritzr** [comment]
Sorry, I looked over the FAQ but missed that particular section. Thanks.
