### ISSUE TITLE
<Cmd> is not listed in vim-differences

### ISSUE THREAD

**Issue by frangio** [neovim/neovim#8442]
This feature added in #4419 is not listed in [vim-differences](https://github.com/neovim/neovim/blob/2aa308c6852b7c51caef5dd6dc4e809719ca7a55/runtime/doc/vim_diff.txt).
https://github.com/neovim/neovim/blob/2aa308c6852b7c51caef5dd6dc4e809719ca7a55/runtime/doc/map.txt#L277

**Comment by justinmk** [comment]
thanks for the note, it's in https://github.com/neovim/neovim/pull/7783 , which admittedly has sat around for too long.
