### ISSUE TITLE
Sync runtime files with vim

### ISSUE THREAD

**Issue by kutsan** [neovim/neovim#8443]
When you guys going to sync major runtime files with vim? Some of them have some bugs fixed and it needs to be updated.

For example `syntax/zsh.vim` is almost one year old.

**Comment by justinmk** [comment]
zsh.vim was updated in 39fa2782168f which was in November. 0.3 will be released soon.

The tone of your request is pretty entitled, by the way. It also wastes my time when you don't mention the version you're using, and ignore the issue template entirely.
