### ISSUE TITLE
NeoVim cursor not changing from Block to Bar when going from insert to normal mode in ConEmu

### ISSUE THREAD

**Issue by Epaenetus** [neovim/neovim#8444]
- `nvim --version`: 0.2.2.20180420
- Vim (version: ) behaves differently? Yes
- Operating system/version: Windows
- Terminal name/version: Conemu
- `$TERM`: buitin_ansi

### Steps to reproduce using `nvim -u NORC`
Get fresh install of ConEmu on Windows 10.
Run NeoVim from ConEmu
```
nvim -u NORC

```

### Actual behaviour
No, cursor changes seem to be taking place. NeoVim is just using the default cursor that ConEmu provides.
### Expected behaviour
Cursor should change based upon modes.

**Comment by justinmk** [comment]
> $TERM: (Not sure what this is)

Nvim depends on the TERM environment variable to guess whether your terminal actually supports cursor-shaping. Check this:

    :echo $TERM

Also please try the [prerelease](https://github.com/neovim/neovim/releases) of Nvim, then check:

    :echo &term

> Cursor should change based upon modes

Depends on `$TERM` and depends on your terminal.

**Comment by Epaenetus** [comment]
Thanks for the quick reply! I tried doing 
`echo $TERM`
in the 0.2.2 version and that displayed nothing.

After installing prerelease, I used:
`:echo &term`
and I received "builtin_ansi".

**Comment by justinmk** [comment]
>  I used: `:echo &term` and I received "builtin_ansi".

Well, that's because TERM isn't set. I explained above why that matters.

**Comment by Epaenetus** [comment]
Thank you for the help! I was able to get it working by following information on this wiki: https://conemu.github.io/en/AnsiEscapeCodes.html

Also, if anyone else has this issue, ConEmu doesn't actually set the TERM environment variable even if you enable these options. You will need to manually set it in the start up settings with:

`set TERM=xterm-256color`
