### ISSUE TITLE
Broken mapping of custom escape sequences

### ISSUE THREAD

**Issue by daskol** [neovim/neovim#8445]
I am trying to migrate from vim to neovim but I have an issue with key mappings. In order to move between tabs I am using <C-Tab> and <C-S-Tab> in vim. I have `.Xresources` for my urxvt as following.
```
urxvt.keysym.C-Tab:                     ^[[control~tab$
urxvt.keysym.C-S-ISO_Left_Tab:          ^[[control~shift~tab$
```
And there is such lines in my `~/.config/nvim/init.vim`.
```
nmap ^[[control~tab$ :tabn<CR>
nmap ^[[control~shift~tab$ :tabp<CR>
```
This solution works pretty well with vim but somehow fails in nvim.

- `nvim --version`:
```NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
Features: +acl +iconv +jemalloc +tui
```
- Vim (version: 8.0-8.1 ) behaves differently? Yes.
```VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:52:08)
Included patches: 1-22
Compiled by Arch Linux
```
- Operating system/version:
```
$ uname -a
Linux hostname 4.16.11-1-ARCH #1 SMP PREEMPT Tue May 22 21:40:27 UTC 2018 x86_64 GNU/Linux
```
- Terminal name/version: `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
- `$TERM`: `rxvt-unicode`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:tabnew
<C-Tab>
```

### Actual behaviour

It prints part of custom escape sequence like `ntrol~tab$` into terminal instead on executing `:tabnext` command.

### Expected behaviour

I expect neovim change tab.

**Comment by justinmk** [comment]
nmap ^[[control~tab$ :tabn<CR>

ESC (`^[`) means ALT. Try this:

    nmap <M-[>control~tab$ :tabn<CR>

If that doesn't work then you may want to subscribe to https://github.com/neovim/neovim/issues/7972

**Comment by daskol** [comment]
@justinmk `<M-[>` does not fix the issue.

**Comment by justinmk** [comment]
> It prints part of custom escape sequence like `ntrol~tab$`

Since `ntrol~tab$` is printed, maybe `co`  was included in the "chord". So try this:

   nmap <M-[co>ntrol~tab$ :tabn<CR>

Or some permutation thereof.

Ultimately you can configure `.Xresources` to send any arbitrary sequence, so you could make life easier by choosing something than doesn't involve ESC... or you can wait for #7972.

**Comment by daskol** [comment]
Escape sequence like `!@#control-tab$` solves the issue. Thanks.

> Since ntrol~tab$ is printed, maybe co was included in the "chord".

It has no any impact.
