### ISSUE TITLE
win: ConEmu: visual selection artifacts 

### ISSUE THREAD

**Issue by Epaenetus** [neovim/neovim#8447]
- `nvim --version`:v0.3.0-1295
- Vim (version: ) behaves differently? Yes
- Operating system/version: Windows10
- Terminal name/version: ConEmu
- `$TERM`: xterm-256color (However, I have add issues with this in the past: https://github.com/neovim/neovim/issues/8444#issuecomment-392351685)

### Steps to reproduce using `nvim -u NORC`
Run vim in ConEmu.
Enable xterm 256 colors
Use ctrl V to do vertical visual selection.
```
nvim -u NORC

```

### Actual behaviour
Before visual selecting:
![image](https://user-images.githubusercontent.com/11667856/40589478-c3c6afb4-61a2-11e8-8d3e-261810fd0b9f.png)

After visual selecting:
![image](https://user-images.githubusercontent.com/11667856/40589453-47df6d14-61a2-11e8-985e-a5bbc710a953.png)
Visual selection appears to mess with line numbers as well as the text itself, by shifting it over.
### Expected behaviour
Should just do normal vertical visual selection and not have any side effects like mentioned above.

**Comment by janlazo** [comment]
Run bash to use the right terminfo and then run `nvim -u NORC` to get a fair comparison with Vim.

**Comment by Epaenetus** [comment]
Thank you for the reply. Since TUI is not usable without bash, can only use nvim on WSL?

**Comment by justinmk** [comment]
> can I only use nvim on WSL?

No, nvim-qt (or any other GUI) works as well.

**Comment by erw7** [comment]
It is necessary to have a terminfo of cygwin etc. But it is not required to run bash to use the right terminfo. There is no problem as long as `TERM` and `TERMINFO` environment variables are properly set.

Libuv currently does not use ANSI X 3.64 and Xterm 256 colors support of ConEmu. Therefore, I do not recommend setting `TERM=xterm-256color` for ConEmu.

I recommend you to set as follows on Windows.

- ConEmu or Console(cmd.exe) on earlier Windows 8.1
    + Have terminfo
       `TERM=cygwin`
       `TERMINFO=path to terminfo`
    + Don't have terminfo
      `TERM=`
      `TERMINFO=`
- Console(cmd.exe) on Windows 10
  `TERM=xterm-256color`
  `TERMINFO=`

For Console on Windows 10, I think it will work as well as neovim on WSL. In other cases, I think that it is difficult to daily use TUI.

**Comment by erw7** [comment]
I tried it with ConEmu version 180528 preview and the phenomenon did not reproduce.

- nvim --version:v0.3.0-1308-g3585df3f0
- Operating system/version: Windows10.0.15063
- Terminal name/version: ConEmu 180528 preview
- $TERM: xterm-256color

![windows10_conemu](https://user-images.githubusercontent.com/11682285/40884602-aa19fea4-6751-11e8-94b2-dfc2e594217f.jpg)

**Comment by Epaenetus** [comment]
@erw7 So I am able to use nvim without running bash? So can I use it in powershell? Regarding this issue, I'm not entirely sure if nvim is at fault. I ended up switching my font in ConEmu and haven't seen the issue since. I'm going to close the issue until I can see it again.

**Comment by erw7** [comment]
> So I am able to use nvim without running bash? So can I use it in powershell?

I think so.  I do not understand why @janlazo says it needs bash.
