### ISSUE TITLE
clipboard provider can no longer access /dev/tty in 0.3.0

### ISSUE THREAD

**Issue by agriffis** [neovim/neovim#8450]
- `nvim --version`: v0.3.0-1304-gf711b6351
- nvim v0.2.2 behaves differently
- Operating system/version: Fedora 28
- Terminal name/version: tmux/mosh/hterm.js
- `$TERM`: tmux-256color

The clipboard provider has lost the ability to access `/dev/tty` which is needed for OSC 52. So my clipboard provider worked in 0.2.2 and no longer works in 0.3.0

### Steps to reproduce using `nvim -u NORC`

This is just a demonstration of losing `/dev/tty` not really the clipboard provider which is more involved.

```
nvim -u NORC
!!echo hi > /dev/tty
```

### Actual behaviour

```
/bin/bash: /dev/tty: No such device or address
```

### Expected behaviour

Well, this reproducer actually makes some garbage in the terminal in 0.2.2, and no error message. But the important part is that the clipboard provider doesn't have access to `/dev/tty` either.

**Comment by kristofferhagen** [comment]
On neovim commit c7e6bb246715c9f1bef4d0ebe0ec361da9c3a07e (current master)
```
:!echo hi > /dev/tty
/bin/bash: /dev/tty: No such device or address

shell returned 1

Press ENTER or type command to continue
```

After commenting out `uvproc->uvopts.flags |= UV_PROCESS_DETACHED;`
```
:!echo hi > /dev/tty
hi

Press ENTER or type command to continue
```

**Comment by justinmk** [comment]
> The clipboard provider has lost the ability to access /dev/tty which is needed for OSC 52. So my clipboard provider worked in 0.2.2 and no longer works in 0.3.0

Slightly off-topic: @agriffis are you speaking of the Nvim default clipboard provider, or did you set `g:clipboard` to something different? We don't use OSC 52 directly, I'm wondering if there's some improvement we can make for the default provider there.

**Comment by agriffis** [comment]
@justinmk I define `y` to yank to tmux, so that I can yank and paste between vims, and `Y` additionally yanks to the system clipboard via OSC 52.

```viml
let g:clipboard = {
      \ 'name': 'myClipboard',
      \     'copy': {
      \         '+': 'clipboard-provider copy',
      \         '*': 'env COPY_PROVIDERS=tmux clipboard-provider copy',
      \     },
      \     'paste': {
      \         '+': 'clipboard-provider paste',
      \         '*': 'env COPY_PROVIDERS=tmux clipboard-provider paste',
      \     },
      \ }

" Yank to tmux normally
set clipboard=unnamed

" Yank to system clipboard with Y
nmap YY "+yy
nmap Y "+y
vmap Y "+y
```

The script `copy-provider` looks like this:

```
#!/bin/bash
#
# clipboard provider for neovim
#
# :help provider-clipboard

#exec 2>> ~/clipboard-provider.out
#set -x

: ${COPY_PROVIDERS:=tmux osc52}
: ${PASTE_PROVIDERS:=tmux}

main() {
    declare buffer status=1

    case $1 in
        copy)
            buffer=$(base64)
            internal() { base64 -d <<<"$buffer"; }
            for p in $COPY_PROVIDERS; do
                internal | $p-provider copy && status=0
            done ;;
        paste)
            for p in $PASTE_PROVIDERS; do
                $p-provider paste && status=0 && break
            done ;;
    esac

    exit $status
}

tmux-provider() {
    [[ -n $TMUX ]] || return
    case $1 in
        copy) internal | tmux load-buffer - ;;
        paste) tmux save-buffer - ;;
    esac
}

osc52-provider() {
    # HACK: this ignores stdin and looks directly at the base64 buffer
    case $1 in
        copy) printf $'\e]52;c;%s\a' "$buffer" > /dev/tty ;;
        paste) return 1 ;;
    esac
}

main "$@"
```

**Comment by agriffis** [comment]
@justinmk Also I have this in `.tmux.conf`

```
# Ms modifies OSC 52 clipboard handling to work with mosh, see
# https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
set -ag terminal-overrides "vte*:XT:Ms=\\E]52;c;%p2%s\\7,xterm*:XT:Ms=\\E]52;c;%p2%s\\7"

# enable OSC 52 clipboard
# https://medium.freecodecamp.org/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b
set -g set-clipboard on
```

There are drawbacks to OSC 52. Generally terminal emulators don't implement reading the system clipboard for security reasons. And writing is sometimes capped, for example mosh caps at 4 kB. Still, it's quite a nice solution for yanking text from vim over mosh and tmux, and pasting it, for example all the snippets I provided above ;-)

**Comment by justinmk** [comment]
@agriffis Good info, thanks!

> lost the ability to access /dev/tty which is needed for OSC 52

Nvim 0.3.0 provides `v:stderr` which is available as a [channel](https://neovim.io/doc/user/channel.html), so you can write to it. For example, if you do this in Nvim TUI, you should see some blinking text:

    :call chansend(v:stderr, '^[[5mxxx')

That's equivalent to writing to `/dev/tty`.

I'm tagging this as `wontfix` for the reasons mentioned in https://github.com/neovim/neovim/issues/8217#issuecomment-402152307 , but  https://github.com/neovim/neovim/issues/8678 outlines a potential path to restoring the Vim-compatible behavior.

**Comment by agriffis** [comment]
@justinmk Thanks for the tip about `v:stderr`. Unfortunately that doesn't play well with `g:clipboard` because it refers to external commands rather than internal functions/commands. So I'm using this hack for now in my `clipboard-provider` script:

```
TTY=$(tty < /proc/$PPID/fd/0)
```

and then sending OSC 52 commands to `$TTY`
