### ISSUE TITLE
Support sam/vim Structured Regular Expressions?

### ISSUE THREAD

**Issue by vvug** [neovim/neovim#8457]
Does or will neovim support structured regular expressions?

https://github.com/martanne/vis/wiki/FAQ#what-are-structural-regular-expressions

**Comment by justinmk** [comment]
It's not unthinkable. But also requires more thinking. "Nice to have" is boring, needs a real cost-benefit analysis, weighed against other mechanisms like macros, Vim regex, and multicursor.

Closing this request since it lacks any of that.

**Comment by bfredl** [comment]
Perhaps this could reasonably be implemented by embedding vis (or other implementation) as an rplugin, in analogy with how vscode-vim can embed nvim to execute ex commands.

**Comment by mcepl** [comment]
I have been playing with vis for the last fortnight and it is really interesting, it is very different, but after just brief period it is obvious that the vim’s old fashioned line-centred view of the world is just wrong. It doesn’t work very well even for programming text and it is even worse for other texts, which are even more difficult to squeeze into line-centred world (I am just in the middle of writing a large fanfiction as a rST document).

I am tempted to switch to vis completely, but it is really hard. Structured regular expressions are really nice, but vis doesn’t have much more than that. vim/neovim has just so much convenience built-in, spellchecking, dict integration, automatic reformatting, or LSP integration, and so many other tools that it is impossible to regenerate it in vis, and on the top of that @martanne is rightfully concerned that he would be alone weighted with the maintenance of the giant codebase he doesn’t need and use.

Embedding whole vis into neovim is I am afraid exactly the bloat which makes @martanne dislike the mammoths to which vim/neovim has tendency to grow. Some compromise would be lovely. Would it be possible to rewrite at least part of vis into some kind of library, which would be used by neovim?

On the UI side, could we get some alternate command line to ``:``? E.g., ``\`` would lead to the “vis command line”, which is not compatible with old sed/ex/vi commands?

**Comment by justinmk** [comment]
> it is obvious that the vim’s old fashioned line-centred view of the world is just wrong

Ex commands are line-centered only by historical accident. I don't see why they could not support something like:

    :`<,`>foo

instead of:

    :'<,'>foo

Meanwhile this still lacks wha I asked for 2 years ago: 

> a real cost-benefit analysis, weighed against other mechanisms like macros, Vim regex, and multicursor.

**Comment by chrisbra** [comment]
relevant upstream issue: https://github.com/vim/vim/issues/3292

**Comment by mcepl** [comment]
> > a real cost-benefit analysis, weighed against other mechanisms like macros, Vim regex, and multicursor.

If the real question was: how much it would cost to build something equivalent while preserving the current technology underneath, then of course, the answer is I have no idea. And yes, probably, it is possible with sufficient level of patches (in the non-computer sense of the word, mends) to build anything. However, there is somewhere a moment when one should admit that the underlying technology is wrong. And I know, that’s the beauty of neovim is that it actually works. Yes.

**Comment by justinmk** [comment]
> If the real question was: how much it would cost to build something equivalent while preserving the current technology underneath,

What I'm asking for is a thorough side-by-side comparison of cases where SREs shine (and where they are weak), vs existing mechanisms (macros, `:g`, `:s`, multicursor, ...). Otherwise we're just speculating.

**Comment by mcepl** [comment]
> What I'm asking for is a thoughtful side-by-side comparison of cases where SREs shine (and where they are weak), vs existing mechanisms (macros, `:g`, `:s`, multicursor, ...). Otherwise we're just speculating.

I won’t claim this [blogpost](https://matej.ceplovi.cz/blog/on-structured-regular-expressions-and-neovim-and-vis.html) is thoughtful, but it is what just goes through my head.

**Comment by mcepl** [comment]
I wonder whether it would be possible to write a plugin, which when activated would spawn vis in a separate process, pass the content of the current buffer to it, and when it ends it would reread changed content back.

**Comment by bfredl** [comment]
This was what I suggested before, but then it was "too bloated" :)

**Comment by mcepl** [comment]
> This was what I suggested before, but then it was "too bloated" :)

Sorry, I understood you meant trying to compile somehow vis inside of neovim. That would be bloated.

**Comment by mcepl** [comment]
Just an interesting discussion on the related theme https://www.reddit.com/r/vim/comments/g69fvx/vimlibmodal_create_new_modes_for_vim/fo9i6zp/

**Comment by tmccombs** [comment]
for substitution specifically, vim does have the `\%V` atom in patterns, which will only match inside the selected area. although other things are more tricky, like [yanking](https://vim.fandom.com/wiki/Copy_search_matches#Copy_matches).

**Comment by mcepl** [comment]
> for substitution specifically, vim does have the `\%V` atom in patterns, which will only match inside the selected area. although other things are more tricky, like [yanking](https://vim.fandom.com/wiki/Copy_search_matches#Copy_matches).

Yes, but I couldn't combine it. E.g.:
```
:x g/^foo/ v/bar$/ x/[0-9]+/ d
```
i.e., select all lines, from these select just those starting with "foo`, from those just those ending with "bar", then select just numbers in these lines, and delete them. And it is possible to run it either on one line, all at once, or one command at the time, so you see what you have selected.

**Comment by justinmk** [comment]
> Yes, but I couldn't combine it. E.g.:
> 
> ```
> :x g/^foo/ v/bar$/ x/[0-9]+/ d
> ```

"Piping" of all ex comands is definitely something I would like. Only needed for interactive `:` cmdline, scripts can (should) use functions and variables.

**Comment by mcepl** [comment]
> "Piping" of all ex comands is definitely something I would like to see.

Except for that you need multiple selections as well, which neovim still doesn’t have (and yes, it probably goes quite against the vi-nature), don’t you?

**Comment by drwilly** [comment]
> Except for that you need multiple selections as well, which neovim still doesn’t have (and yes, it probably goes quite against the vi-nature), don’t you?

While multiple selections are perfect to make sam's editing model interactive, they are not a requirement for command-line usage. You can represent `x` and `y` as loops or iterators, e.g:
> ```
> :x g/^foo/ v/bar$/ x/[0-9]+/ d
> ```
```
foreach().filter('^foo').filter('bar', invert=True).foreach('[0-9]+').exec(delete)
```

**Comment by justinmk** [comment]
It is agreed that piping/filtering of ex commands etc is useful. https://github.com/neovim/neovim/issues/8457#issuecomment-903465370
