### ISSUE TITLE
decode_cursor_entry() return value without being initialized.

### ISSUE THREAD

**Issue by CuteLasty** [neovim/neovim#8459]
- `nvim --version`:
NVIM v0.3.0-1308-g3585df3f0
Build type: Debug
LuaJIT 2.0.5

- Operating system/version:
Windows 7 SP1

- Terminal name/version:
CMD.exe

### Steps to reproduce
Use VS2017 build as debug mode
run it

### Actual behaviour
Visual Studio shows:
Run-time check failure #3 - the variable 'r' is being used without being initialized.

### Expected behaviour
Value 'r' should be initialized.

Call stacks:
nvim.exe!decode_cursor_entry(Dictionary args) Line 864
	at d:\work\neovim\neovim\src\nvim\tui\tui.c(864)
nvim.exe!tui_mode_info_set(ui_t * ui, bool guicursor_enabled, Array args) Line 880
	at d:\work\neovim\neovim\src\nvim\tui\tui.c(880)
nvim.exe!ui_bridge_mode_info_set_event(void * * argv) Line 50
	at d:\work\neovim\neovim\vs2017\src\nvim\auto\ui_events_bridge.generated.h(50)
nvim.exe!multiqueue_process_events(multiqueue * this) Line 152
	at d:\work\neovim\neovim\src\nvim\event\multiqueue.c(152)
nvim.exe!loop_poll_events(loop * loop, int ms) Line 66
	at d:\work\neovim\neovim\src\nvim\event\loop.c(66)
nvim.exe!tui_main(ui_bridge_data * bridge, ui_t * ui) Line 362
	at d:\work\neovim\neovim\src\nvim\tui\tui.c(362)
nvim.exe!ui_thread_run(void * data) Line 105
	at d:\work\neovim\neovim\src\nvim\ui_bridge.c(105)

value 'r' dump:

-	r	{full_name=0xcccccccccccccccc <Error reading characters of string.> shape=0xcccccccc mshape=0xcccccccc ...}	cursor_entry
+	full_name	0xcccccccccccccccc <Error reading characters of string.>	char *
	shape	0xcccccccc	CursorShape
	mshape	0xcccccccc	int
	percentage	0xcccccccc	int
	blinkwait	0xcccccccc	long
	blinkon	0xcccccccc	long
	blinkoff	0xcccccccc	long
	id	0xcccccccc	int
	id_lm	0xcccccccc	int
+	name	0xcccccccccccccccc <Error reading characters of string.>	char *
	used_for	0xcc '?'	char

**Comment by justinmk** [comment]
does this fix it?

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index 65957626cbc9..2b822f5471c1 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -845,7 +845,7 @@ CursorShape tui_cursor_decode_shape(const char *shape_str)
-
 static cursorentry_T decode_cursor_entry(Dictionary args)
 {
-  cursorentry_T r;
+  cursorentry_T r = shape_table[0];
-
   for (size_t i = 0; i < args.size; i++) {
     char *key = args.items[i].key.data;
```
