### ISSUE TITLE
last character can not be displayed in neovim's statusline

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#8466]
- `nvim --version`: v0.3.0-1314-g39a03c0fe
- Vim (version: ) behaves differently? yes
- Operating system/version: archlinux
- Terminal name/version: termite
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u test.vim`

test.vim

```vim
set nocompatible
syntax on
set ls=2
let &statusline = '%#String# Git log popup %#Comment#'
```

### Actual behaviour

in neovim, I can not see the last character  "  " on statusline, but in vim it works well.

### Expected behaviour

neovim should has same behavior as vim

### screenshorts

**vim**

![2018-06-02_219x70](https://user-images.githubusercontent.com/13142418/40871199-d931ce5c-65fc-11e8-800d-97d42824674f.png)

**neovim**

![2018-06-02_216x71](https://user-images.githubusercontent.com/13142418/40871206-ecb53a18-65fc-11e8-960e-e956ca32dff7.png)

**Comment by wsdjeg** [comment]
and I use SpaceVim, here is how I find this issue, in SpaceVim, we have a build-in statusline plugin, but it behaves differently in vim and neovim.

in vim8 it works well

![2018-06-02_227x48](https://user-images.githubusercontent.com/13142418/40871227-90136374-65fd-11e8-8ce5-7ef6065c5711.png)

but in neovim, I can not see the last character

![2018-06-02_240x50](https://user-images.githubusercontent.com/13142418/40871228-9068c27e-65fd-11e8-9da5-639d07307ad9.png)

**Comment by chemzqm** [comment]
<img width="216" alt="screen shot 2018-06-02 at 10 40 27 pm" src="https://user-images.githubusercontent.com/251450/40877607-5d1b2ede-66b6-11e8-9fda-f8d9e8a25c2b.png">
it works as expected in vim.

**Comment by justinmk** [comment]
can someone please bisect?

**Comment by wsdjeg** [comment]
@chemzqm In current version of neovim, if you want to avoid this issue, you can add a space at the end of status, so  `set statusline=你好\ ` should works.

**Comment by kristofferhagen** [comment]
```
0d7daaad98d5874b345453073f6e21b024ee42d4 is the first bad commit
commit 0d7daaad98d5874b345453073f6e21b024ee42d4
Author: ZyX <kp-pav@yandex.ru>
Date:   Sun Apr 8 16:01:19 2018 +0300

    charset,*: Refactor transstr()

:040000 040000 fed04dff845838b2472f28ac61c80614f2d7131e 1045866edc2e7a99114e6790db6eea9a857e76c7 M      src
```
@justinmk

**Comment by MichaHoffmann** [comment]
Can i work on this?

**Comment by justinmk** [comment]
@MichaHoffmann Certainly, no one else is working on it. One can check https://github.com/neovim/neovim/pulls to look for related work if in doubt.

**Comment by MichaHoffmann** [comment]
@justinmk cool, thanks. Is there a convention so that i can find a PR for an Issue?

**Comment by justinmk** [comment]
@MichaHoffmann There are different search features of GitHub, but usually I just look the backreferences. For example in this issue you can see above there are two backlinks, neither of which is a pull request.

**Comment by MichaHoffmann** [comment]
@justinmk Thats very helpful! Thank you.

**Comment by MichaHoffmann** [comment]
I would want to write a functional test and im not quite sure how to start. My first intuition is using the screen.lua helper, writing something like `feed('set statusline=你好')` and asserting that the screen contains this statusline. 
Is that the canonical way?

**Comment by justinmk** [comment]
Sure, just copy an `it()` block in some `foo_spec.lua` file. 

You can [run the locally](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/foo_spec.lua make functionaltest

**Comment by MichaHoffmann** [comment]
I have the problem that this test: 
`    it('last char of statusline shows', function()                                   
      local screen = Screen.new(20, 4)                                               
      screen:attach()                                                                
      command('set statusline=abc')                                                  
      screen:expect([[                                                               
      ^                   |                                                          
      ~                   |                                                          
      abc                 |                                                          
                          |                                                          
      ]])                                                                            
    end) `
fails. 
Does the Test screen implementation show the statusline? If not is there another way to access its status?

**Comment by justinmk** [comment]
@MichaHoffmann call `command('set laststatus=2')` also. The tests have laststatus=1 by default for historical reasons. Also please open a PR , it's easier to discuss there :)

**Comment by wsdjeg** [comment]
Thanks for working on this issue.
