### ISSUE TITLE
Getting weird errors when pasting after yank

### ISSUE THREAD

**Issue by jeffschwartz** [neovim/neovim#8469]
- `nvim --v0.2.2`:
- Vim (version: ) behaves differently?
- Operating system/version: MacOS 10.13.4 
- Terminal name/version: iTerm2 Build 3.1.6
- `$TERM`: xterm-256colo

### Steps to reproduce using `nvim -u NORC`
in edit mode type some text
go to normal mode
yank text just typed
paste text just yanked
```
nvim -u NORC

```

### Actual behaviour
warning: reattach-to-user-namespace: unsupported new OS, trying as if it were 10.6-10.9
  2 warning: _vprocmgr_move_subset_to_user failed
  3 warning: reattach-to-user-namespace: unable to reattach

### Expected behaviour
text to have been pasted

### My init.vim file:

" {{ Plugins via vim-plug
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
"
call plug#begin('~/.local/share/nvim/plugged')

" Surround plugin
Plug 'tpope/vim-surround'

" Cobalt2 color scheme plugin
Plug  'herrbischoff/cobalt2.vim'

" Initialize plugin system
call plug#end()
" }}

" copy & paste to the clipboard
set clipboard=unnamedplus

" colorscheme
colorscheme cobalt2

" support gui colors
set termguicolors

" {{ Automatic toggling between line number modes
set number relativenumber
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
" }}

" display the ruler in the status bar
set ruler

" {{ hybrid cursor support
set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
		  \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
		  \,sm:block-blinkwait175-blinkoff150-blinkon175
" }}

**Comment by justinmk** [comment]
Are you using tmux? What version?

**Comment by jeffschwartz** [comment]
No, @justinmk , I'm not using tmux though I do have an old version of it installed.

**Comment by jeffschwartz** [comment]
I installed with brew if that helps. Also, I am not aliasing nvim and `$ type nvim` reports:

    nvim is hashed (/usr/local/bin/nvim) 
    /usr/local/Cellar/neovim/0.2.2_1

**Comment by jeffschwartz** [comment]
More info for you if this helps:

    $ echo executable 'pbcopy'
    executable pbcopy
    /usr/local/Cellar/neovim/0.2.2_1
    $ pbcopy
    warning: reattach-to-user-namespace: unsupported new OS, trying as if it were 10.6-10.9
    warning: _vprocmgr_move_subset_to_user failed
    warning: reattach-to-user-namespace: unable to reattach

**Comment by justinmk** [comment]
If `pbcopy` doesn't work, then clipboard pasting definitely can't work in Nvim.

I'm guessing that you installed `reattach-to-user-namespace` with homebrew at some point, and now it's broken for whatever reason.

I found this by searching for `pbcopy warning: reattach-to-user-namespace: unsupported new OS`: https://gist.github.com/henrik/3181718

**Comment by jeffschwartz** [comment]
Yup, you nailed it :) That was the problem. I ran the following to install the latest version of `reattach-to-user-namespace` :

    brew upgrade reattach-to-user-namespace
    brew link --overwrite reattach-to-user-namespace

Thank you, @justinmk. You da man :)!
