### ISSUE TITLE
Unmapped chords (e.g. :noremap q:) will revert back to the default after a TIMEOUTLEN delay

### ISSUE THREAD

**Issue by lanza** [neovim/neovim#8476]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? No, same behavior.
- Operating system/version: macOS 10.13.5
- Terminal name/version: iTerm
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:noremap q: <NOP>
q      "wait TIMEOUTLEN
:

```

### Actual behaviour

The command history panel pops up if you wait `TIMEOUTLEN` or longer enough between the `q` and the `:`

### Expected behaviour

The command history panel should not pop up since it is unbound from `q:`. `nvim` registers the `q`, waits up to `TIMEOUTLEN` for the `:` to combine the two to map to `<NOP>`. If `TIMEOUTLEN` passes then `nvim` decides this was not your custom bound mapping and thus reverts back to default mappings and `q:` to the command history panel.

**Comment by justinmk** [comment]
Looks like https://github.com/neovim/neovim/issues/6241 .  Maybe you can try https://github.com/neovim/neovim/pull/6419
