### ISSUE TITLE
Add a way to force true-color mode

### ISSUE THREAD

**Issue by canndrew** [neovim/neovim#8477]
- `nvim --version`:

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /nix/store/487kalv9jm8g5fs3bm5yhby63mcpnbfv-gcc-wrapper-7.3.0/bin/gcc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/source/build/config -I/build/source/src -I/nix/store/asanpcrx4mwzqg7s5p48qs3d12bw8lxf-libuv-1.19.2/include -I/nix/store/sjn4dhhbqs54may1jikwqhzhyagmj5xv-libmsgpack-2.1.5/include -I/nix/store/brc7mvaclm4v7x44br45rjaw3xjnasjc-unibilium-2.0.0/include -I/nix/store/0cswcg1q1q01wa7qyibfr7657sxxj9h2-libtermkey-0.20/include -I/nix/store/rnzc7gq9h5sjag4k2k0dwbd8mk6gmbaz-neovim-libvterm-2017-11-05/include -I/nix/store/wiimy8pkpf9v57gvqaa1npqk17965pym-jemalloc-5.0.1/include -I/nix/store/lb3kkvyylnbcxn5jad9i11szxlhkpkjq-glibc-2.27-dev/include -I/build/source/build/src/nvim/auto -I/build/source/build/include
Compiled by nixbld

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/gjg3ah9ywdgkscbg7rh2lmwz4qyx0h8n-neovim-unwrapped-0.2.2/share/nvim"

Run :checkhealth for more info
```

- Operating system/version: NixOS 18.09.git.af55a0c3002M (Jellyfish)
- Terminal name/version: xfce4-terminal 0.8.6
- `$TERM`: xterm-256color

I can't for the life of me figure out why neovim is refusing to use true color mode. Rather than list everything I've tried and try to fix the problem here, I think it would be nice if neovim had a way to force true color mode. My understanding from reading `:help true-color` is that if neovim sees that `termguicolors` is set then it runs a bunch of checks to see whether true colors are really supported. For whatever reason those checks are failing on my machine so I would like a way to just bypass them and be done with this sh*t. I know my terminal supports setrgbf escape codes.

Is this an option you would consider adding?

**Comment by justinmk** [comment]
Try 0.3
