### ISSUE TITLE
matchit.vim pollutes jumplist despite keepjumps

### ISSUE THREAD

**Issue by ilAYAli** [neovim/neovim#8478]
- tested from: nvim --version: `NVIM v0.2.3-12-g7b686881a`
- to: nvim --version:  `NVIM v0.3.0-1346-g3585df3f0`
- Vim (version: )  8.0 (unaffected)
- Operating system/version: MacOs
- Terminal name/version: iTerm
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Paste the following function to e.g /tmp/foo.vim:

```
norm 0gg
execute "silent! keepjumps norm /{\<cr>"
clearjumps
echom "jumps pre: " | jumps
keepjumps norm %
"norm %
echom "jumps post: " | jumps
```
observe that the jumplist is updated:
`nvim /tmp/foo.vim -u NORC --headless -c 'so %|q'`

## output
```"/tmp/foo.vim" 12L, 175C
jumps pre:
 jump line  col file/text
>
jumps post:
 jump line  col file/text
   1     1   33 execute "silent! keepjumps norm /{\<cr>"
>
```
### Notes
1) vim8 is unaffected.

2) The bug is _not_ triggered if -u NONE (note NONE vs NORC) is supplied:
`nvim -u NONE /tmp/foo.vim -c 'so %'`

**Comment by justinmk** [comment]
which version of vim8 exactly? it could be that we're missing a vim patch.

**Comment by ilAYAli** [comment]
vim --version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 10 2018 11:23:42)
Included patches: 1-1806
```

**Comment by ilAYAli** [comment]
The bug is triggered due to lading of `matchit.vim`

This file sets up a mapping for `%`:
`nnoremap <silent> %  :<C-U>call <SID>Match_wrapper('',1,'n') <CR>`

Which means that `Match_wrapper` is called when `%` is pressed.

In this function, the line that clutters the jumplist is:
 `normal! m'`

_Setting_ marks should not affect the jumplist, but replacing the line with
`keepjumps normal! m'` hides the reported symptoms but does not fix the actual problem.

This can be verified  by running these commands, and seeing that the jumplist is updated:
```
clearjumps
normal m'
jumps
```

`src/nvim/mark.c` seems to be a plausible scapegoat, but I haven't done any further digging.

**Comment by justinmk** [comment]
cc @chrisbra

**Comment by chrisbra** [comment]
as far as I can say, this is intentionally:
https://github.com/vim/vim/blob/ca851593a660f08aba5c134f90c238d4a3e983e6/src/mark.c#L135-L140

```c
/*
 * Set the previous context mark to the current position and add it to the
 * jump list.
 */
    void
setpcmark(void)
{
```

**Comment by ilAYAli** [comment]
I see that vim8 also updates the jumplist when setting the `'` mark, so this is not neovim specific.
This is not mentioned in `:h marks`, and setting other marks [a-zA-Z0-9]... does not update the jumplist.
I have not looked at the code yet, but I assume that there might be some confusion related to handling the difference between _setting_ mark `'` and _jumping_ to a mark with `'<mark>`, as both involve the same character.

**Comment by chrisbra** [comment]
as I said, this happens intentionally. Perhaps adding to the documentation should be okay?

**Comment by ilAYAli** [comment]
@chrisbra that is fine by me.
In that case, this should be a sufficient fix for neovim:

```
diff --git a/runtime/plugin/matchit.vim b/runtime/plugin/matchit.vim
index e3171e5cb..ccb1e60e7 100644
--- a/runtime/plugin/matchit.vim
+++ b/runtime/plugin/matchit.vim
@@ -276,7 +276,7 @@ function! s:Match_wrapper(word, forward, mode) range
   let final_position = "call cursor(" . line(".") . "," . col(".") . ")"
   " Restore cursor position and original screen.
   call winrestview(view)
-  normal! m'
+  keepjumps normal! m'
   if sp_return > 0
     execute final_position
   endif
```

**Comment by justinmk** [comment]
> Setting marks should not affect the jumplist, but replacing the line with `keepjumps normal! m'` hides the reported symptoms

`m'` also updates `:jumps` in Vim 8.1.0001. This is most likely expected behavior, the `'` mark is by definition a jump.

@ilAYAli Feel free to send a patch for matchit.vim, I will merge it.

**Comment by ilAYAli** [comment]
I don't think that the above fix is sufficient, as it will prevent `%` from updating the jumplist regardless of `keepjumps` state. 
So, `<c-o>` will not bring you back when moving to a matching parameter with `%`.
`matchit.vim` should only do so if `keepjumps` is true, and AFAIK, that is not exposed to vimscript?

**Comment by chrisbra** [comment]
it is only exposed for `:commands` with the `<mods>` replacement text.

**Comment by ilAYAli** [comment]
I could probably expose `keepjumps` and do something like this for `matchit.vim`:

```
let should_keep_jumps = &keepjumps
...
if should_keep_jumps:
    keepjumps normal! m'
else
    normal! m'
endif
```

But:
1) I don't know if this is an acceptable solution?
1) My intention was to submit a bug report ;)

**Comment by chrisbra** [comment]
>  &keepjumps

keepjumps is no option.

**Comment by justinmk** [comment]
m' by definition updates the jumplist. That is the entire purpose of the ' mark.

**Comment by ilAYAli** [comment]
@justinmk so `keepjumps normal %` should update the jumplist?

`:h keepjumps`
```
:keepj[umps] {command}
                        Moving around in {command} does not change the '',
                        '. and '^ marks, the jumplist or the
                        changelist.
                        Useful when making a change or inserting text
                        automatically and the user doesn't want to go to this
                        position.  E.g., when updating a "Last change"
                        timestamp in the first line:

                                :let lnum = line(".")
                                :keepjumps normal gg
                                :call SetLastChange()
                                :keepjumps exe "normal " . lnum . "G"

                        Note that ":keepjumps" must be used for every command.
                        When invoking a function the commands in that function
                        can still change the jumplist.  Also, for
                        ":keepjumps exe 'command '" the "command" won't keep
                        jumps.  Instead use: ":exe 'keepjumps command'"
```

**Comment by justinmk** [comment]
@ilAYAli `:h keepjumps` mentions `Moving around in {command} does not change ...`. "Moving around" does not include the `m` command, which explicitly sets a mark. 

It also says:

```
When invoking a function the commands in that function
can still change the jumplist.
```

If you don't want to invoke matchit, use `:normal` with a bang:

    keepjumps normal! %
