### ISSUE TITLE
:terminal tests should hardcode shell to use

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#8484]
- `nvim --version`: master
- Vim (version: ) behaves differently? n/a
- Operating system/version: n/a
- Terminal name/version: n/a
- `$TERM`: n/a

If you run `make test` with a different shell as your default, the shell-related tests will fail since they rely on shell-specific behavior. `set shell=bash` or `set shell=sh` should probably be specified before running these tests.

(e.g. my default shell is fish, and it does not support the syntax used in the terminal tests which then fail.)

**Comment by justinmk** [comment]
Yes, thanks. This was reported in https://github.com/neovim/neovim/issues/6172 but no one worked on it.
