### ISSUE TITLE
timer causes long commands to replicate upwards

### ISSUE THREAD

**Issue by svalaskevicius** [neovim/neovim#8490]
- `nvim --version`:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

- Vim (VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)) behaves differently? Yes. command stays in the status line.

- Operating system/version: osx
- Terminal name/version: iTerm 2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

" create empty function.. ANY function
: function AAA(ticker)
: endfunction

" start timer
: call timer_start(1000, 'AAA', {'repeat': -1})

" start typing a long command. so long it doesnt fit in the window, e.g.
: echo "123451234512345123451234512345123451234512345123451234512345123451234512345123451234512345"

```

### Actual behaviour
once the above command reaches the end of the window, the starts replicating upwards, once every timer tick..

this behaviour is back to normal if timer is stopped (e.g. after `:call timer_stopall()`)

### Expected behaviour

only single copy of the command being entered is shown at the bottom. screen above the status line should stay unchanged

**Comment by svalaskevicius** [comment]
<img width="725" alt="screen shot 2018-06-06 at 22 46 14" src="https://user-images.githubusercontent.com/893660/41066887-792b0d10-69db-11e8-9e53-9946ddbfa256.png">

**Comment by justinmk** [comment]
Confirmed in `NVIM v0.3.0-1356-g36ac80d5dd58`. If `cmdheight=2` then one needs to type a command that is longer than 2 screen-lines.
