### ISSUE TITLE
Trying to open a file results in E488: Trailing characters; v0.2.2

### ISSUE THREAD

**Issue by Senevri** [neovim/neovim#8494]
NVIM version 0.2.2, gnome terminal (xterm-256color), Linux Mint 18.1 Cinnamon 64-bit. installed with apt-get from Ubuntu repo, after uninstalling vim, as per 
https://github.com/neovim/neovim/wiki/Installing-Neovim

:version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security
 -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_
FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-pa
rameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATE
D_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2
/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/
build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include

Features: +acl +iconv +jemalloc +tui

### Steps to reproduce using `nvim -u NORC`

From command mode, enter 
    :o . 
(The open command for current directory).
similarily trying to open any given file, say
    :o index.js
gives the same result.

### Actual behaviour

Results in E488: Trailing characters

### Expected behaviour
opening a view of current files in directory.

**Comment by justinmk** [comment]
`:open` was removed in Nvim, see `:help nvim-features-removed`.

Use `:edit` instead.
