### ISSUE TITLE
API: refactor "Invalid method" spaghetti code 

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8495]
described at https://github.com/neovim/neovim/pull/8489#discussion_r193561218

**Comment by MichaHoffmann** [comment]
May i start to work on this? Would be my first issue.

**Comment by bfredl** [comment]
@MichaHoffmann Yes, just go ahead.

**Comment by MichaHoffmann** [comment]
@bfredl Okay, thank you. I just started working and created a [WIP] PR.

**Comment by MichaHoffmann** [comment]
How can i proceed in this issue?

**Comment by bfredl** [comment]
@MichaHoffmann added two comments at the PR, otherwise LGTM.
