### ISSUE TITLE
neovim ftdetect giving different (incorrect) results compared to vim

### ISSUE THREAD

**Issue by 5paceToast** [neovim/neovim#8504]
- `nvim --version`: v0.2.2
- Vim (version: 8.1 (1-22)) behaves differently? yes
- Operating system/version: Arch Linux (Updated to June 7)
- Terminal name/version: Konsole (18.04.2) + tmux 2.7
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```sh
mkdir -p ~/.vim/pack/default/start
git clone https://github.com/sheerun/vim-polyglot ~/.vim/pack/default/start/vim-polyglot
ln -s ~/.vim ~/.config/nvim
# create a ferm file ending in .ferm with ferm syntax in it
nvim -u NORC myfile.ferm
# notice how the autodetected syntax is `conf`
:setf ferm # notice how the highlighting is correct
:q
vim -Nu /dev/null -c 'syntax on' myfile.ferm
:q # notice how the filetype is correctly detected on the first try
```

### Actual behaviour

Neovim detects the file as `conf`, which is incorrect.

### Expected behaviour

Neovim detects the file as `ferm`, which is correct, and is what vim does.

### Notes:
Polyglot used in this example because that's what I use. I haven't tested with [upstream](https://github.com/vim-scripts/ferm.vim) alone, but, ultimately, vim behaves differently.

**Comment by justinmk** [comment]
Try with 0.3.0

**Comment by 5paceToast** [comment]
Confirming 0.3.0 fixes this behavior.
