### ISSUE TITLE
Prebuilt appimage for ARM linux?

### ISSUE THREAD

**Issue by wxdao** [neovim/neovim#8512]
If I’m not mistaken the prebuilt appimage is for x64 only, thus on my raspberry pi and ARM VPS I have to manually build it to use the latest version. Versions provided by system repository are too old. Could you please consider to release ARM binaries too?

**Comment by dcervenkov** [comment]
Several years later, ARM is much more prevalent, but there are still no ARM binaries in the appimage. ARM CI is now readily available, so could this be reopened?

**Comment by clason** [comment]
> ARM CI is now readily available, so could this be reopened?

[Citation needed]

If you can provide a PR to add ARM CI easily, that would be welcome!

**Comment by dcervenkov** [comment]
I'm sure it would; personpower is always an issue. Unfortunately, I don't think I'll find time to do that anytime soon.

In case somebody else wants to pick this up, here are a few thoughts that might be useful:
- The neovim CI uses GitHub runners, which do not include ARM
- It might be possible to use this [GitHub ARM runner action](https://github.com/marketplace/actions/arm-runner) instead

**Comment by danielnolan** [comment]
Sounds like Github will have ARM runners soon! https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/#unlock-the-power-of-arm-in-actions

**Comment by clason** [comment]
only on macOS (at least for free)

**Comment by dundargoc** [comment]
Duplicate of https://github.com/neovim/neovim/issues/15143
