### ISSUE TITLE
nvim-qt.exe doesnt't give any error feedback

### ISSUE THREAD

**Issue by lluke777** [neovim/neovim#8525]
- `nvim --version`: 0.22 and 0.3
- Vim (version: ) behaves differently? yes 8.1
- Operating system/version: Windows 7
- Terminal name/version: cmd.exe
- `$TERM`:

### Steps to reproduce using `nvim-qt.exe`
Lets consider simple example at `init.vim`:
```
if has('nvim')
 ....do something
else
 ....do something
endif
```
For ex: if  I delete closing statement  `endif`  

### Actual behaviour
at vim 8.1 I get error feedback at the start of vim 8.1, but nvim-qt don't give me any feedback only window  with white background and `retry` button. At console nvim version there is some feedback error

### Expected behaviour
Is there a `logerror` or some way to display errors at the nvim-qt start?

**Comment by justinmk** [comment]
Thanks for reporting. This is a known issue. https://github.com/neovim/neovim/issues/1984
