### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by BurhanDanger** [neovim/neovim#8527]
- `nvim --version`: 0.3.0
- nvim (version: 0.2.2 ) behaves differently? Yes
- Operating system/version: Archlinux
- Terminal name/version: st
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim /etc/hosts
<modify file>
:w !sudo tee % > /dev/null
sudo: no tty present and no askpass program specified

shell returned 1

Press ENTER or type command to continue
```

### Expected behaviour

```
:w !sudo tee % > /dev/null
[sudo] password for username:

W12: Warning: File "filename" has changed and the buffer was changed in Vim as well
See ":help W12" for more info.
"filename" [readonly] 527L, 25460C
Press ENTER or type command to continue

```

**Comment by BurhanDanger** [comment]
Similar https://github.com/neovim/neovim/issues/8217

**Comment by justinmk** [comment]
Yep, known issue.

**Comment by BurhanDanger** [comment]
Didn't see that when issued. Close this one if you like.

**Comment by dtcyganok** [comment]
Still relevant for version 0.3.1. Probably worth re-opening the bug.

**Comment by BurhanDanger** [comment]
This is duplicate thread. There's hardly a point it still being open.

Now the actual bug is "wontfix" as mentioned in https://github.com/neovim/neovim/issues/8217#issuecomment-402310332 . They'll try to make this vim compatible as of https://github.com/neovim/neovim/issues/8678 , but (maybe) not in near future.

In the meantime you can use https://github.com/lambdalisue/suda.vim
