### ISSUE TITLE
Recursive :global

### ISSUE THREAD

**Issue by lahwran** [neovim/neovim#8529]
also mentioned at https://github.com/vim/vim/issues/1760. this is a pretty trivial issue, but I thought I'd bring it up.

### Actual behaviour

```
#!/bin/bash
cat << END > file.txt
hello, world, my old friend
I've come to talk with you again
because a vision softly creeping
left it's scenes while I was sleeping
and the vision
that was planted
in my brain
still remains
within the hello world
END

nvim file.txt
```
in nvim:
```
:g/hello/g/,/p
```

prints:

    E147: Cannot do :global recursive

### Expected behaviour

should print:

    hello, world, my old friend

**Comment by jamessan** [comment]
> also mentioned at vim/vim#1760. this is a pretty trivial issue, but I thought I'd bring it up.

There's no need to bring up specific Vim patches.  We have a [process](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-vim) for merging upstream patches, so this will get handled when [8.0.0630](https://github.com/vim/vim/commit/f84b122a99da75741ae686fabb6f81b8b4755998) gets merged.

**Comment by lahwran** [comment]
I'm mentioning it here because the vim team seems to have rejected it.

**Comment by chrisbra** [comment]
you mentioned the relevant vim issue in your initial message from which can be seen that the patch has been included in Vim.
