### ISSUE TITLE
yank flashes a vertical line

### ISSUE THREAD

**Issue by llpamies** [neovim/neovim#8530]
I did not have this problem in v0.1.0, but I recently updated to v0.3.1-1-gfa2ad305e and I get this weird flickering column every time I yank a line. This is a video of the problem:

https://drive.google.com/file/d/1X7iKGrqBa_fZepbUdPaInw1UnaEGzfoG/view

This only seem to happen with SecureShell from Chrome, and it is not dependent of my current nvim configuration or tmux. It appears without tmux, and without any nvim config/plugins.

**Comment by justinmk** [comment]
With Nvim 0.3.0+ you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Try this:

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post it.

(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

**Comment by llpamies** [comment]
I attach the log file.
[log.txt](https://github.com/neovim/neovim/files/2094634/log.txt)

**Comment by justinmk** [comment]
The FAQ for your terminal emulator suggests `TERM=xterm`. 

https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md#why-does-the-color-scheme-look-funny-in-emacs_vi_vim

Although it also says it's putty-based, so perhaps try `TERM=putty-256color` as recommended at `:help $TERM`.

You should read the docs for your terminal emulator.

**Comment by llpamies** [comment]
The reason why my log shows tmux-256color is because I'm running from tmux. Without using tmux, the TERM variable is set to xterm-256color, and setting it to xterm, putty or putty-256color does not make the yank glitch disappear.

You should not assume that people had not read the docs of their terminal emulator.

**Comment by justinmk** [comment]
I can't do anything but make assumptions when almost no information is given.

**Comment by llpamies** [comment]
As my last comment said, the error happens in tmux, and without tmux. So it is not a tmux problem. It seems to be a nvim bug.

The information I provided is all the information I have, and the bug can be reproduced by using SecureShell + v0.3.1 in different machines.

**Comment by llpamies** [comment]
Can we reopen the bug?

**Comment by justinmk** [comment]
What I mean is: since it *does* happen in tmux, it's not because of any terminfo or terminal workarounds that Nvim does. 

Report it to your terminal emulator.

**Comment by llpamies** [comment]
My concern here is that the problem is non-existent with v0.1.0 for the same terminal emulator. So there is something that nvim did to introduce this problem.

**Comment by justinmk** [comment]
We changed TUI logic but that doesn't mean we did something invalid. It's possible, but unlikely. Or maybe we're doing something that is worked around in all other terminal emulators. 

Not going to spend my time investigating it, instead SecureShell  can investigate it
