### ISSUE TITLE
Feature request: Substitute with confirm flag - center replacement candidates

### ISSUE THREAD

**Issue by sullyj3** [neovim/neovim#8532]
A frustrating issue that I often run into is that when I do something like
`:%s/foo/bar/gc`
in a long file with many occurrences of foo, as I make my way forwards, `y`ing or `n`ing, eventually the matches will be shown at the bottom of the screen. This often means that I don't have the necessary context to decide whether to substitute that match, necessitating a whole bunch of presses of `ctrl-e` to scroll forward. This is especially true if `foo` is actually a complex regex matching a large amount of text.

In my opinion, a better default, UX wise, would be to center each match of foo in the viewport when the user is prompted to confirm substitution of that match. This would give the user the necessary context to make a decision with minimal scrolling.

**Comment by sullyj3** [comment]
In any case, I assume at some point the confirm UI will be externalised anyway, right?

**Comment by chrisbra** [comment]
See `:h 'scrollof'`

**Comment by sullyj3** [comment]
Oh, thanks! This is a nice workaround for me. However, I don't want it on all the time, so this solution comes with the inconvenience of having to enable it before `:s` and disable it after.

**Comment by justinmk** [comment]
> the inconvenience of having to enable [scrolloff] before :s and disable it after

The new CmdLineEnter/CmdlineLeave add some potential for scripting this.

Eventually we'll have a full VimL command parser (similar to the VimL expression parser) which may help with that as well.
