### ISSUE TITLE
Provide bash wrapper that can be used for update-alternatives purpose

### ISSUE THREAD

**Issue by marxin** [neovim/neovim#8535]
vim package (in openSUSE) provides following binaries:

```
/bin/ex
/bin/vi
/bin/vim
/usr/bin/edit
/usr/bin/ex
/usr/bin/gvimtutor
/usr/bin/rview
/usr/bin/rvim
/usr/bin/vi
/usr/bin/view
/usr/bin/vim
/usr/bin/vimdiff
/usr/bin/vimtutor
/usr/bin/vitmp
/usr/bin/xxd
```

Would it be please possible to come up with neovim wrappers so that one can used update-alternatives?

**Comment by justinmk** [comment]
Why? Those aliases are useless and just add more for users to learn. 

`nvim -h` describes the options.
