### ISSUE TITLE
Clipboard: faild to execute: win32yank -i --crlf

### ISSUE THREAD

**Issue by lluke777** [neovim/neovim#8537]
- `nvim --version`: 0.3.0-1429-g6b0f63eba
- Vim (version: ) behaves differently?yes nad nvim-qt 0.22
- Operating system/version: Windows 7 64
- Terminal name/version: nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
set clipboard+=unnamedplus in init.vim

- yank line (yy)
```
nvim -u NORC

```

### Actual behaviour
Clipboard: faild to execute: win32yank -i --crlf
at nvim 0.2.2 works fine
### Expected behaviour
Copy text from neovim-qt to system clipbard and to other applications

**Comment by justinmk** [comment]
> yank line (yy)

That obviously won't use the clipboard with `nvim -u NORC`, so you must have done `set clipboard=unnamed` before.

It works for me with Nvm 0.3.0 on Windows. 

However, it will "eventually" break after some time, see   https://github.com/neovim/neovim/issues/7000 and https://github.com/neovim/neovim/issues/7377.
