### ISSUE TITLE
UI: window state event stream, win_attach()

### ISSUE THREAD

**Issue by lunixbochs** [neovim/neovim#8539]
It would be useful to have an event stream per window, for events such as cursor update, viewport change, and fold changes. Related to https://github.com/neovim/neovim/issues/8538

This is similar to fully externalizing windows, but not really mutually exclusive.

This is most of the information ActualVim queries constantly: https://github.com/lunixbochs/ActualVim/blob/master/neo.py#L328-L345

```
nvim_win_attach(window, [opts: dict])

possible notifications:
"cursor", win, [(line, col, vline, vcol), ...] # preemptive array so API won't break for multi-cursor
"viewport", win, [top, left, width, height, topfill?, skipcol?]
"fold", "add | remove | expand | collapse", win, fold_desc # (fold_desc from #8538)
```

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/pull/8455

**Comment by justinmk** [comment]
@lunixbochs  Nvim 0.5 includes `win_viewport` UI event. `:help ui`: 

```
["win_viewport", grid, win, topline, botline, curline, curcol]
	Indicates the range of buffer text displayed in the window, as well
	as the cursor position in the buffer. All positions are zero-based.
	`botline` is set to one more than the line count of the buffer, if
	there are filler lines past the end.
```

`:help ui-linegrid` and `:help ui-ui-multigrid` addresses the other features requested here.
