### ISSUE TITLE
--embed: write errors to stderr

### ISSUE THREAD

**Issue by igorgladkoborodov** [neovim/neovim#8541]
- `nvim --version`: v0.3.1-dev
- Operating system/version: macOS 10.13.4

### Steps to reproduce using `nvim -u NORC`

When you start nvim with `--embed` flag it does not send anything on stderr.

Here is example in Javascript:
```
import { spawn } from 'child_process';

const nvimProcess = spawn(
  'nvim',
  ['--embed', '-u', 'NONE', '+', 'call wrong_function()'],
);
nvimProcess.stderr.on('data', (data) => {
  console.log(`Error data: ${data}.`); // No output
});
```

If user have errors in init.vim, there is no way to see them when you run nvim with `--embed`.

### Actual behaviour

Stderr does not receive anything.

### Expected behaviour

When you do the same with `--headless` it will work as expected:
```
import { spawn } from 'child_process';

const nvimProcess = spawn(
  'nvim',
  ['--headless', '-u', 'NONE', '+', 'call wrong_function()'],
);
nvimProcess.stderr.on('data', (data) => {
  console.log(`Error data: ${data}.`); // Error data: "call wrong_function()" [New File]
});
```

So now the only workaround to catch startup errors is to use `--headless` and then `stdioopen`.

**Comment by justinmk** [comment]
Is this a regression from 0.2 ?

**Comment by igorgladkoborodov** [comment]
No, the same was on 0.2.2

**Comment by bfredl** [comment]
So `nvim --embed` works different from `nvim --headless --cmd "call stdioopen({'rpc': v:true})"` ? That is very interesting (and not intended).

**Comment by justinmk** [comment]
stderr would be useful for out-of-band visibility.

But the goal of your request as I interpret it will be solved by _not blocking_ on startup (for `--embed` but possibly in general (any errors will be available via `:messages` and possibly other mechanisms). Which is something we plan to explore.

**Comment by justinmk** [comment]
> will be solved by _not blocking_ on startup (for `--embed` but possibly in general); any errors will be available via `:messages` and possibly other mechanisms. This is something we plan to explore.

We took a different approach ( https://github.com/neovim/neovim/pull/8754 , https://github.com/neovim/neovim/pull/9024 ) which solves the motivation for this ticket: `--embed` blocks until RPC request is received.  This prevents a race between Nvim startup vs UI startup.

We could redirect `log.c` messages to stderr for `--embed`, but I can't think of any reason why that would be preferred instead of `$NVIM_LOG_FILE` (which can be set to `/dev/stderr` if wanted).
