### ISSUE TITLE
Neovim resets the Blur effect in Plasma 5

### ISSUE THREAD

**Issue by gagbo** [neovim/neovim#8551]
![peek 14-06-2018 14-16](https://user-images.githubusercontent.com/10496163/41411843-802f51f8-6fde-11e8-9f5a-33e208f639dc.gif)

When neovim launches, it resets the blur effect from Plasma, and I have to change the size of the window to force some sort of redraw from Plasma and get the blur back. This does not happen with vim, so I thought it may be a neovim issue and not just me being bad at Plasma config.

- `nvim --version`: 
   neovim.x86_64  0.3.0-1.fc29
- Vim (version: ) behaves differently? Vim does behave differently, see the gif
   VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 13 2018 22:07:44)
    Rustines incluses : 1-55
- Operating system/version: Fedora 29 (Rawhide)
- Terminal name/version: konsole 18.04.2 (on Plasma 5.12.90 - aka 5.13 "Beta")
- `$TERM`: xterm-256color (I don't think I changed it anywhere, and I have the same issue anyway when I do `TERM=konsole-256color ; nv -u NONE`, with `:echo $TERM` giving konsole-256color)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
The nvim part of the gif

### Expected behaviour
the vim part of the gif

**Comment by justinmk** [comment]
Most likley the same root cause as https://github.com/neovim/neovim/issues/6798 . 

Try disabling cursor-styling, as a workaround:

    set guicursor=
