### ISSUE TITLE
stdpath('config_dirs') crashes on windows

### ISSUE THREAD

**Issue by tjdevries** [neovim/neovim#8553]
- `nvim --version`: 0.3.0-1211
- Vim (version: ) behaves differently? Doesn't have the feature
- Operating system/version: Windows
- Terminal name/version: nvim-qt
- `$TERM`: cmd.exe

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:echo stdpath('config_dirs')
```

### Actual behaviour
Crashes

### Expected behaviour
Not crashes

**Comment by tjdevries** [comment]
Same with `data_dirs` as well

**Comment by justinmk** [comment]
This was fixed in https://github.com/neovim/neovim/pull/8406

**Comment by tjdevries** [comment]
Woops.... I was downloading head and installed to the wrong folder on extract. Thought I had checked the latest master but it was actually just still the old one :)
