### ISSUE TITLE
:terminal prompt is one line too low

### ISSUE THREAD

**Issue by E5ten** [neovim/neovim#8556]
- `nvim --version`:
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U
_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FRO
M -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-pro
totypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-
color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-41002-1capld4/neovim
-0.3.0/build/config -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.0/src -I/usr/local/
include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-41002-1c
apld4/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-41002-1capld4/neovim-0.3.
0/build/include
Compiled by brew@ElCapitan-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
- Operating system/version:
OS X 10.11
- Terminal name/version:
Alacritty scrollback branch
- `$TERM`:
xterm-256color
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
:terminal
split nvim in some way e.g. `:sp | :e .config/nvim/init.vim`

### Actual behaviour
when using the terminal afterwards once it has filled once the lowest visible line will be one above the prompt
### Expected behaviour
the prompt will be the lowest visible line.

I didn't see this happen until 0.3.0.

**Comment by glacambre** [comment]
This happened to me a lot since at least 2.0 and maybe before. I believe this is caused by the way the height of the window is computed when your terminal has an odd number of lines because pressing `<C-w>=` while in normal mode in the terminal buffer will fix it and using `<C-w>=` in the text buffer will cause the issue to happen again.
I believe there's another issue open for this.

**Comment by justinmk** [comment]
can you try https://github.com/neovim/neovim/pull/8325 ?

**Comment by glacambre** [comment]
It looks like #8325 fixes this issue for me. This is great, thank you @mrbiggfoot and @justinmk!
