### ISSUE TITLE
set columns stops neovim from filling the entire terminal window

### ISSUE THREAD

**Issue by RageKnify** [neovim/neovim#8559]
- `nvim --version`:v0.3.0
- Vim (version: ) v8.1
- Operating system/version: Arch Linux 4.16.13-2
- Terminal name/version: kitty 0.11.0
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
I can't reproduce with `-u NORC` because it is a problem with the `set columns` config option.
in my config I have `set columns=87`, I tried commenting it out and the bug didn't happen anymore, but I'd like to be able to use it.

Open nvim/vim on a terminal with more than 23 lines
### Actual behaviour - nvim behaviour
nvim only uses the first 20 something lines of the terminal window as can be seen here
![2018-06-15-120240_1920x1080_scrot](https://user-images.githubusercontent.com/24737605/41465015-41e0125a-7094-11e8-91ec-684f5ee1d8f9.png)

### Expected behaviour - vim behaviour
vim uses up it's entirety 
![2018-06-15-120250_1920x1080_scrot](https://user-images.githubusercontent.com/24737605/41465045-541f0584-7094-11e8-9655-362366794b22.png)

**Comment by justinmk** [comment]
why are you setting columns at all?

Most likely same as https://github.com/neovim/neovim/issues/2403
