### ISSUE TITLE
`echo file | xargs nvim` creates empty buffer 1

### ISSUE THREAD

**Issue by gibfahn** [neovim/neovim#8561]
- `nvim --version`: `0.3.0`
<details><summary>Full version output:</summary>

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

</details>

- Vim (version: ) behaves differently? v0.2.2
- Operating system/version: macOS 10.13.5
- Terminal name/version: Terminal.app (and [Kitty.app](https://github.com/kovidgoyal/kitty))
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```console
$ echo README.md | xargs /usr/local/Cellar/neovim/0.3.0/bin/nvim -u NONE +ls
```

### Actual behaviour

```console
$ echo README.md | xargs /usr/local/Cellar/neovim/0.3.0/bin/nvim -u NONE +ls
```

```
  1 %a   "[No Name]"                    line 0
  2      "README.md"                    line 0
Press ENTER or type command to continue
```

### Expected behaviour

```console
echo README.md | xargs /usr/local/Cellar/neovim/0.2.2_1/bin/nvim -u NONE +ls
```

```
Output:
"README.md" 130L, 4129C
  1 %a   "README.md"                    line 0
Press ENTER or type command to continue
```

It's more obvious if you have a buffer view in your tab line (e.g. using [vim-buftabline](https://github.com/ap/vim-buftabline)):

![image](https://user-images.githubusercontent.com/15943089/41475745-7b321eb8-70b7-11e8-8395-ada93d0de68c.png)

**Comment by jamessan** [comment]
This was introduced by neovim/neovim@905d4d78f.

**Comment by justinmk** [comment]
We could be a bit smarter when stdin returns nothing (as in this case), then don't create empty buffer 1.

Meanwhile the workaround is just `:bn`.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8576 changes this so that buffer 2 is selected if nothing was read from stdin. There will still be an empty buffer 1.

**Comment by Morantron** [comment]
I'm having the same issue when running this script https://pastebin.com/DQpEg1mK

Ran it like, for example `find . -iname /tmp | /path/to/that-script-from-pastebin`
