### ISSUE TITLE
MSVC2017 build neovim 

### ISSUE THREAD

**Issue by CuteLasty** [neovim/neovim#8564]
- `nvim --version`:
master (c990d65c37ded9ad9f4002a6eb6ec36aa29b4fe3)

- Vim (version: ) behaves differently?
build .deps failed

- Operating system/version:
window 10 17134

- Terminal name/version:
cmd.exe

### Steps to reproduce
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug ..\third-party\
cmake --build . --config Debug

### Actual behaviour
Build libtermkey failed when apply patch

### Expected behaviour
apply done

-----
It's seems CRLF / LF problem, and I modified libtermkey.vcxproj, added --binary after git apply.

**Comment by justinmk** [comment]
Not sure what we can do with this. Clearly, it builds for other people. If you found a problem and can send a PR to fix it, please do.
