### ISSUE TITLE
AppImage: fzf window will not close if pressing esc

### ISSUE THREAD

**Issue by probonopd** [neovim/neovim#8566]
Please note: I am not experiencing this myself (have not tried to reproduce) but am merely reporting an issue I read about at https://github.com/kjelly/auto_config/commit/42d517a7ea6960d5c6aa55e0ff13b727e3f80fcc

### Steps to reproduce using `nvim -u NORC`

When you use nvim from the AppImage, the fzf window will not close if pressing
esc.

But the issue will be gone if you extract nvim from appimage.

### Actual behaviour

When you use nvim from the AppImage, the fzf window will not close if pressing
esc.

### Expected behaviour

When you use nvim from the AppImage, the fzf window will close if pressing
esc.

**Comment by justinmk** [comment]
Thanks for passing this along. We are aware of this: https://github.com/neovim/neovim/issues/8104 , https://github.com/neovim/neovim/issues/7620

> But the issue will be gone if you extract nvim from appimage

I have no idea what we're supposed to do about this. @probonopd you would know more about the potential interactions of appimage than anyone else, right? :)

**Comment by probonopd** [comment]
Sorry for having opened a duplicate; will follow up in the linked ticket(s).

**Comment by justinmk** [comment]
Closed by https://github.com/neovim/neovim/pull/8737
