### ISSUE TITLE
Remove old Ex-mode and replace with Improved Ex-mode

### ISSUE THREAD

**Issue by ryvnf** [neovim/neovim#8568]
Vim has two types of Ex Mode. The normal (old) Ex Mode is entered using the `-e` command flag, or by the normal mode command `Q`. The new and improved Ex Mode is entered using the `-E` command flag, or by the normal mode command `gQ`.

The difference is that the old Ex Mode has very limited command line editing functionality. The user cannot use any command-line mappings from `cmap` or `cnoremap` and cannot use any command line completion features.

I think one of the reasons Ex Mode is so annoying for users, is that it has so limited editing functionality. By switching to improved Ex Mode by default, users might find it more useful.

I propose that the old Ex-mode is to be removed and aliased to the Improved Ex-mode.

This means that `-e` flag will be equivalent to using the `-E` flag, and `Q` will be equivalent to using `gQ`.

**Comment by bfredl** [comment]
Dup of #8520 ?

**Comment by ryvnf** [comment]
Yes, this is a duplicate. So I close this issue now.
