### ISSUE TITLE
How to enable PowerShell syntax highlighting?

### ISSUE THREAD

**Issue by passboltUser** [neovim/neovim#8586]
I downloaded nvim-win64.zip, drag&dropped a .ps1 file, but unfortunately there's no syntax highlighting. How to enable syntax highlighting for .ps1 files?

**Comment by jamessan** [comment]
> How to enable syntax highlighting for .ps1 files?

1. Find someone to write and maintain a syntax script for PowerShell.
2. Convince them to submit the script to Bram for inclusion with Vim's runtime files.
3. Wait for the runtime update to get merged into Neovim.

**Comment by passboltUser** [comment]
Quite an unfriendly reply. I hope not all neovim users are so unfriendly. You offer neovim for windows, so you should expect such questions. PowerShell under windows is important, why not support it. (and no, I don't like windows, it's proprietary OS, but I have to use it here)

**Comment by bitraid** [comment]
You can use [this plugin](https://github.com/PProvost/vim-ps1.git).

**Comment by jamessan** [comment]
> PowerShell under windows is important, why not support it.

This had nothing to do with PowerShell. What I described is the process that would be required for any new runtime file to be distributed with (Neo)Vim.

If you look at the top of any syntax script (any runtime file for that matter), you'll see that it's maintained by someone. That maintenance happens independently from (Neo)Vim. When the maintainer thinks the cumulative changes are appropriate to be part of the standard runtime, they send the updated file to Bram.

There are also numerous runtime files that are maintained completely independently from the standard runtime. Nothing prevents you from finding an existing syntax script and installing it yourself.
