### ISSUE TITLE
`:h sponsor` gives a bunch of Vim-specific info

### ISSUE THREAD

**Issue by bruce-hill** [neovim/neovim#8603]
- `nvim --version`: NVIM v0.3.0
- Vim (version: ) behaves differently? no
- Operating system/version: Mac OSX 10.13.5
- Terminal name/version: iTerm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:h sponsor
```

### Actual behaviour
When Vim launches without a file, it displays either "Help poor children in Uganda! type :help iccf<Enter> for information" or "Sponsor Vim development! type :help sponsor<Enter> for information". Going to either help page gives a lot of information about donating to charity on behalf of Vim, and Vim sponsors getting to vote on features that Bram works on.

### Expected behaviour
Since NeoVim a different project from Vim, it's confusing for NeoVim to refer to itself as Vim, and have information that implies that Bram is looking at feature requests and bug fixes for NeoVim. It's up to the NeoVim developers how much of that information they want to preserve, but I would recommend at least revising sponsors.txt so that it properly distinguishes between Vim and NeoVim. I think it's probably good to keep the original information about donating to the ICCF on behalf of Vim, though, since NeoVim is a fork of Vim, and it's a good cause. It might be worth editing more of the help docs for clarity as well, like `:h credits` and `:h www`.

**Comment by Asheq** [comment]
What if `:h sponsor` simply has a link to https://neovim.io/sponsors (and https://www.vim.org/sponsor)? It could include as little other information as possible (e.g. only clarifying why there two links; that Neovim and Vim are two separate projects that mutually benefit each other)?
It would mean one less place to keep information up to date.

**Comment by mission712** [comment]
Maybe separating into `:h sponsor` and `:h vim-sponsor` is a good idea? `:h sponsor` could contain what @Asheq said, while `:h vim-sponsor` would contain the original contents of Vim's `:h sponsor` with an added header describing what it's about.
