### ISSUE TITLE
[RFC] Versioning, compatibility, support

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#862]
There is another question related to #700, but that looks like it is about _packaging_ (despite its title), it is about _releasing_. Vim has rather strange releases: there are minor and major version numbers and a list of patches which does not form patch number (if you saw Vim on CentOS you may have mentioned they do not include all patches). VimL and Vim keys compatibility is kept always, with bindings compatibility Bram relies on the sense of bindings maintainer. Major version bumps and minor version bumps happen when there are enough _features_ as Vim is meant to be compatible always (except for incompatible changes which were accepted as a bugs).

As we are going to have more then one release (never saw a piece of software that is both not dead and has only one release with no plans for next one) then it would be good to decide in advance:
1. Version scheme. I think it makes sense to not invent our own and take semantic versioning.
2. What releases will we support? I.e. if we released `1.0` and `1.1` with new features will we backport bug fixes to `1.0`? What about `1.*` and `2.*`?
3. Will there be dates when we must do a new release (like Ubuntu always releasing in April)? I personally do not like such things.
4. How often do bug fixes form a new release (with updated patch number if semantic versioning is accepted)?
5. How often do features form a new release? Vim may add new feature in any of `7.0`, `7.4` and `7.4.100`, but semantic versioning (if accepted) requires us to postpone this until new minor version update.
6. How likely and how often backwards incompatible changes will be accepted?
7. Will we like `git` bump major version due to rather minor, but still backwards incompatible changes? It will be required by semantic versioning if it is accepted.

**Comment by justinmk** [comment]
Moving this to 0.2, though I will post a proposal hopefully later today.

**Comment by justinmk** [comment]
> with bindings compatibility Bram relies on the sense of bindings maintainer.

We addressed this in `:help api-contract` .

> Major version bumps and minor version bumps happen when there are enough features as Vim is meant to be compatible always

When Nvim reaches `1.x` we should try to stay there as long as possible. In particular we will never break the API (i.e. remove deprecated API functions) until `2.0`, i.e. indefinitely.

> What releases will we support? I.e. if we released 1.0 and 1.1 with new features will we backport bug fixes to 1.0? 

We describe this in [MAINTAIN.md](https://github.com/neovim/neovim/blob/master/MAINTAIN.md): we support the current stable release, via a `release-x.y` branch. 

> Will there be dates when we must do a new release

Releases are driven by [milestones](https://github.com/neovim/neovim/milestones). We should _try_ to release every 3 months; some bigger releases push out to 6 months.

> How likely and how often backwards incompatible changes will be accepted?

We make a distinction between API vs user workflow. 

- API should never break
- User workflow should not break unless the benefit:cost ratio is high

> Will we like git bump major version due to rather minor, but still backwards incompatible changes?

After `1.0`, if we break the API: yes.
