### ISSUE TITLE
API: buffer update "threshold"

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#8620]
https://github.com/neovim/neovim/issues/1114#issuecomment-53344006 mentions the idea of a "threshold" for the buf-updates API, such that very big changes are only sent as metadata. So if the client wants the change it can request it. This may entail keeping a MRU in Nvim so that clients can request recent changes.

Presumably,  giant changes may not be useful for some applications. Or some applications may only care about the visible changes.

**Comment by KillTheMule** [comment]
I'll just copy in my comment from gitter:

> 1) My experiments seem to indicate that the rpc overhead per message is worse than that per size, so introducint an additional message to signal "there stuff here" to save on communication traffic seems a bit weird. 2) I have trouble imagining a plugin that might say "Huh, there's large buffer update, let's not fetch it, I only look at smaller ones" 3) We c an already send larger updates in smaller chunks, although we're not doing that atm

**Comment by bfredl** [comment]
I presume clients care about eventual consistency? How would that be ensured when some large changes are not sent? Every delta can depend on any previous one.

**Comment by justinmk** [comment]
@bfredl There would need to be some sort of MRU in the Nvim server, which could be queried by clients. 

Based on our discussion, I think this can be closed.

**Comment by bfredl** [comment]
I don't see how the MRU would help with anything (events are not reorderable etc) but if the proposal is withdrawn I guess the question is moot.
