### ISSUE TITLE
Linked 32-bit Windows .zip doesn't exist

### ISSUE THREAD

**Issue by khs26** [neovim/neovim#8625]
[This](https://github.com/neovim/neovim/releases/download/nightly/nvim-win32.zip) is the link to the 32-bit zip file containing neovim, which is prominently highlighted on the front page. There doesn't seem to actually be a 32-bit nightly build though, only 64-bit.

**Comment by jamessan** [comment]
The nightly artifacts depend on the relevant build completing.  That didn't happen for the 32-bit Windows build, so you'll have to wait for the next nightly.

**Comment by khs26** [comment]
Ack. Is there a stable build available for each platform? If so, it might make more sense for that to be the link presented from [the install instructions](https://github.com/neovim/neovim/wiki/Installing-Neovim)

**Comment by jamessan** [comment]
I'll change those to point to the latest stable release.  Thanks.

**Comment by jamessan** [comment]
@khs26 FWIW, I did some more poking around and there were indeed some issues with our handling of the nightly Windows binaries.  Those should be fixed once https://github.com/neovim/bot-ci/pull/133 gets merged.  Thanks for bringing it up!
