### ISSUE TITLE
listchars now disallows unicode chars ·

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#8626]
- `nvim --version`: _NVIM v0.3.1-94-g7f7802e64_
- Vim (version: ) behaves differently?  _NVIM v0.3.0-1184-g4744142fa_
- Operating system/version: _Darwin sanji.local 17.7.0 Darwin Kernel Version 17.7.0_
- Terminal name/version: _iTerm2 Build 3.1.6beta5_
- `$TERM`: _screen-256color_

### Steps to reproduce using `nvim -u NORC`

Can't repro with NORC however, reduce init.vim to two lines:

```
set list
set listchars=tab:,trail:_,extends:>,precedes:<,nbsp:+
```

Start vim

If using `nvim -u NORC` and setting listchars manually to `set listchars=tab:··,trail:_,extends:>,precedes:<,nbsp:+`  then it works fine

### Actual behaviour

Error:

```
Error detected while processing /Users/daniel/.config/nvim/init.vim:
line    2:
E474: Invalid argument: listchars=tab:<b7><b7>,trail:_,extends:>,precedes:<,nbsp:+
Press ENTER or type command to continue
```

### Expected behaviour

no error and it works fine like when setting it manually

**Comment by bfredl** [comment]
Hmm, I can see no multibyte chars in the init.vim snippet? To debug this I like to see the exact byte representation.

**Comment by danielb2** [comment]
[Interpunct] `·`  is 183

[Interpunct]: https://en.wikipedia.org/wiki/Interpunct

**Comment by bfredl** [comment]
Yes, but how it is represented in the init.vim? UTF-8? latin-1? Does the init.vim has a `scriptencoding`?

**Comment by danielb2** [comment]
[init.vim.gz](https://github.com/neovim/neovim/files/2129125/init.vim.gz)

**Comment by bfredl** [comment]
What happens is that nvim doesn't recognize the file as latin-1 while sourcing it, however it does when opening. Either open the init.vim, `:set fenc=utf-8` and then write it (recommended), or add `scriptencoding latin-1` to fix it.

**Comment by danielb2** [comment]
This works with vim, and has worked with all versions of nvim before. Why should I need to change something ?

**Comment by danielb2** [comment]
fyi though, `:set fenc=utf-8` did solve the issue

**Comment by bfredl** [comment]
In the past `listchars` would freely accept single latin-1 bytes even with UTF-8 scripencoding (in a way that I strongly doubt was intentional behavior, even composing chars would be accepted and then thrown away), so I guess it was a case of two wrongs (in vim/nvim) making one right. If scriptenc should be smarter to detect latin-1 configs is something we can discuss, but for now unless there is a good reason not to, keeping config in UTF-8 it is what we would recommend.

**Comment by jamessan** [comment]
> keeping config in UTF-8 it is what we would recommend.

Or using the right `scriptencoding` (which should be done anyway for compatibility).

**Comment by danielb2** [comment]
ok. thanks :)

**Comment by chrisbra** [comment]
> This works with vim, and has worked with all versions of nvim before. Why should I need to change something ?

Even with Vim it is recommended to set `:scriptencoding`

**Comment by BatmanAoD** [comment]
> What happens is that nvim doesn't recognize the file as latin-1 while sourcing it, however it does when opening. Either open the init.vim, :set fenc=utf-8 and then write it (recommended), or add scriptencoding latin-1 to fix it.

This information should probably be added somewhere prominent, such as the "getting started from vim" page.

**Comment by justinmk** [comment]
@BatmanAoD Adding those two sentences will certainly confuse the 99% of users that don't have latin-1 encoded vimrcs, and adding, say, an entire paragraph explaining this possibly will be quite a lot of screen space used to explain something that doesn't apply to 99.99% of users.

**Comment by BatmanAoD** [comment]
@justinmk There should probably be a "troubleshooting" section of that document, and possibly even a Windows-specific section.

I would imagine I am not the only Windows user who doesn't realize their `.vimrc` file is in Latin-1 but is being _treated as_ UTF-8. So maybe something as simple as:

 > Nvim (and Vim) silently treat config files in Latin-1 encoding as being in UTF-8 encoding. If you are a Windows user, ensure that your config files are encoded in UTF-8 by opening the files, specifying the encoding using `:set fenc=utf-8`, and writing them.
