### ISSUE TITLE
Proxy icon in Terminal.app

### ISSUE THREAD

**Issue by aramisgithub** [neovim/neovim#8630]
In [this post](https://alerante.net/features/vim-title/), it is described in detail how to display a proxy icon of the file being edited in the window title. This works perfectly in vim. However, as neovim removed the t_XX series of options, the code given in the post does not work anymore. Is there a way to remedy this?

I have [posted this question](https://www.reddit.com/r/neovim/comments/8t8l5q/proxy_icon_in_terminalapp_mac/) on [r/neovim](https://reddit.com/r/neovim), and was directed to post here.

Edit: fix link

**Comment by bfredl** [comment]
It is possible to send a sequence of raw bytes to the terminal using `chansend(2, string or array)`

**Comment by aramisgithub** [comment]
Thanks! I have solved the problem using a custom function.
