### ISSUE TITLE
`set clipboard+=unnamedplus` adds 250+ms to startup time on mac

### ISSUE THREAD

**Issue by bruce-hill** [neovim/neovim#8631]
- `nvim --version`: 0.3.0
- Vim (version: 8.1) behaves differently? vim does not get slowed down by `set clipboard+=unnamedplus`
- Operating system/version: Mac 10.13.5
- Terminal name/version: iTerm
- `$TERM`: xterm

### Steps to reproduce

```
echo "set clipboard+=unnamedplus" > slow.vim
nvim -u slow.vim --startuptime slow.log
```

### Actual behaviour
NeoVim takes roughly 10x longer to launch (~300ms vs ~30ms), thanks to this line from the startup log:
```
304.391  280.173  280.173: sourcing /usr/local/stow/neovim-0.3.0/share/nvim/runtime/autoload/provider/clipboard.vim
```

### Expected behaviour
There is no reason for it to take so long to set up the clipboard.

### Workaround
I poked around in the clipboard provider code, and figured out that the slow startup time can be completely fixed by manually setting `g:clipboard` before `set clipboard+=unnamedplus` like this:

```
let g:clipboard = {'copy': {'+': 'pbcopy', '*': 'pbcopy'}, 'paste': {'+': 'pbpaste', '*': 'pbpaste'}, 'name': 'pbcopy', 'cache_enabled': 0}
set clipboard+=unnamedplus
```

My guess is that there is something very slow in this line from `nvim/runtime/autoload/provider/clipboard.vim`:
```
  elseif has('mac') && executable('pbpaste') && s:cmd_ok('pbpaste')
```

**Comment by justinmk** [comment]
Thanks for debugging! Sounds like #7237 .

**Comment by yhkaplan** [comment]
I can also confirm that this affects me and that the workaround significantly improved my startup time 👍
