### ISSUE TITLE
balloonevalterm

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8646]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? Yes
- Operating system/version: MacOS
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

This feature could be really helpful for user to get the documentation of a symbol by just moving the mouse, without moving cursor.

Seems not a easy job as neovim have dropped the support for `balloon` from beginning.

It's also a bit tricky to make `balloonevalterm` works in vim, the `balloon_show` have to be invoked in async way like this:

``` vim
let s:timer = -1

function! s:BalloonShow(...)
  let s:message =
          \ 'Cursor is at line ' . v:beval_lnum .
          \', column ' . v:beval_col .
          \ ' of file ' .  bufname(v:beval_bufnr) .
          \ ' on word "' . v:beval_text . '"'
  call balloon_show(s:message)
endfunction

function! MyBalloonExpr()
  call timer_stop( s:timer )
  let s:timer = timer_start(100, function('s:BalloonShow'))
  return ''
endfunction

set mouse=a
set ttymouse=sgr
set balloonexpr=MyBalloonExpr()
set balloondelay=300
set balloonevalterm
```

**Comment by bfredl** [comment]
Is there a vim issue for the indirection through timer needed? Doesn't seem like intentional behavior (the built-in balloon delay should do this, no?)

**Comment by chemzqm** [comment]
I think that it's intended, in order not to block vim when evaluating the value for `balloon_show `

**Comment by bfredl** [comment]
I just don't see why two different delays (300 ms + 100 ms) are needed instead of one, isn't `balloondely` implemented by defering the eval to the main loop, just like a timer would? If not, what is the interpretation of the two different times 300 ms and 100 ms?

**Comment by justinmk** [comment]
It's not really necessary for Nvim to restore _all_ of the ballooneval garbage (which is truly an atrocious API). 

We only need:

- `balloon_show()` (or `nvim_popup_show()`, whatever)
- it should work always, without any options or other nonsense
- it should take screen-offset coordinates or window + window-offset

**Comment by bfredl** [comment]
@justinmk Correct me if I'm wrong, but I don't think vim  has any form of mouse hover events (just press, drag and release) apart from the one tied to `balloneval`/`ballonevaldelay`. So if not `balloneval` _per se_ we would want to add that in a way disentangled from the ballon feature, maybe a `MouseHover` event (e can ask the terminal to listen for such events if the number of autocmds are nonzero), and then it is up to the plugin to connect the two, or use either for a different purpose.

**Comment by justinmk** [comment]
Nvim 0.4 (unreleased) has floating windows. https://github.com/neovim/neovim/pull/6619

"Sugar" for the low-level floating window API is tracked in https://github.com/neovim/neovim/issues/9663
