### ISSUE TITLE
Missing jemalloc on Fedora 28 server package

### ISSUE THREAD

**Issue by pmpbar** [neovim/neovim#8649]
Using Fedora 28 Server. 
`Linux mlady 4.16.3-301.fc28.x86_64 #1 SMP Mon Apr 23 21:59:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Packages are missing dep `jemalloc` when installed from dnf.

Fixed with `# dnf install jemalloc`

**Comment by jamessan** [comment]
Packaging for distributions isn't handled by the neovim project.  You'll need to discuss that with the Fedora maintainers.

**Comment by pmpbar** [comment]
I saw on the wiki you guys were packing it. Where can I put an issue up for them?

**Comment by jamessan** [comment]
That part of the wiki is contributed to by the people doing the work.  @dperson seems to be the one maintaining that.  As far as actual Fedora communication, I don't know.  I don't use Fedora.
