### ISSUE TITLE
Character get removed when join lines

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8655]
- `nvim --version`: NVIM v0.3.1-120-g12481781a
- Vim (version: ) behaves differently? Yes
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Add lines with:

```
<string, DocumentSelector> = new Map<
> ()
```
And press `J` at first line

### Actual behaviour

`>` of second line would be removed, which resulted in:
```
<string, DocumentSelector> = new Map< ()
```

### Expected behaviour

It should be
```
<string, DocumentSelector> = new Map< >()
```

The character remove only happens with some certain characters in first line.
vim don't have this bug.

**Comment by bfredl** [comment]
minimal test case:
```
x>y
>z
```

Could it be related to the code that handles comment chars when joining lines? I could imagine `>` getting similar treatment when used as diff mark in a diff file.

**Comment by jamessan** [comment]
This is controlled by `'formatoptions'`, in particular the `j` setting.  When `'fo'` contains `j`, then the comment leader will be removed when joining the lines.

By default, `'comments'` contains `n:>`, so that's probably related.

**Comment by jamessan** [comment]
Also of interest would be how `'commentstring'` is set in your buffer.

**Comment by chemzqm** [comment]
I'm using `nvim -u NORC`, so the `formatoptions` is `tcqj` be default.
I tried to set same `formatoptions` in vim, and I could get the same issue.

Just don't understand why would `>` considered as a comment start?

**Comment by jamessan** [comment]
Compare the values of `'comments'` and `'commentstring'`.

**Comment by chemzqm** [comment]
Understand, I should get `>` removed from `comments`
