### ISSUE TITLE
nvim_buf_set_lines() doesn't play well with unloaded buffers

### ISSUE THREAD

**Issue by phodge** [neovim/neovim#8659]
- `nvim --version`: v0.3.0
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu 18.04

### Steps to reproduce using `nvim -u NORC`

I wrote some lua test code to verify that `nvim_buf_set_lines()` will work with a buffer that has been `:bunload`'ed. It doesn't :-( I experienced two incorrect behaviours:

1. A line range such as `0, -1` is always constrained to `0, 1` because internally `normalize_index()` thinks there is only 1 line in the buffer. Attempting to replace all lines in the file will only replace the first line.
2. You should be able to use a single `:undo` to revert the changes from `nvim_buf_set_lines()`, however if the buffer was unloaded then the undo information gets mangled and using :undo puts the buffer in weird states that it never even transitioned through.

You can paste the test code into e.g. `test/functional/api/buffer_spec.lua` to flag both bugs:

    it('set_lines works correctly for unloaded buffers', function()
      -- we'll need to know our bufnr for when it gets unloaded
      local bufnr = buffer('get_number', 0)
      -- replace the buffer contents with these two lines
      buffer('set_lines', bufnr, 0, -1, 1, {'line1', 'line2', 'line3'})
      -- confirm that getting lines works
      eq({'line2', 'line3'}, buffer('get_lines', bufnr, 1, 3, 1))
      -- save the file then unload it
      command('file some-test-file.txt')
      command('write')
      command('new')
      command('bunload '..bufnr)
      -- attempting to get lines now gives empty list
      eq({}, buffer('get_lines', bufnr, 1, 3, 1))
      -- use nvim_buf_set_lines() to override the entire file contents
      buffer('set_lines', bufnr, 0, -1, 1, {'LINE A', 'LINE B'})
      -- open the buffer again
      command('sbuf '..bufnr)
      -- entire file contents should have been replaced
      eq({'LINE A', 'LINE B'}, buffer('get_lines', bufnr, 0, -1, 1)) -- THIS FAILS
      -- undo should put everything back how it was
      command('undo')
      eq({'line1', 'line2', 'line3'}, buffer('get_lines', bufnr, 0, -1, 1)) -- THIS ALSO FAILS
    end)

### Actual behaviour

The test code fails at the lines mentioned.

### Expected behaviour

The test should pass - i.e. `nvim_buf_set_lines()` always works correctly with unloaded buffers. Or possibly `nvim_buf_set_lines()` could just raise an error if the buffer isn't loaded.

**Comment by justinmk** [comment]
> You should be able to use a single :undo to revert the changes from nvim_buf_set_lines(), however if the buffer was unloaded then the undo information gets mangled

That might be expected, `set nohidden` destroys undo info if the buffer is hidden (unloaded). That is, unloading a buffer loses its in-memory undo info, by design.
