### ISSUE TITLE
Strange issue with utf8 symbols in completion menu

### ISSUE THREAD

**Issue by lervag** [neovim/neovim#8664]
- `nvim --version`: 0.3.0
- Vim (version: 8.1.22) behaves _correctly_
- Operating system/version: Arch Linux (recently updated)
- Terminal name/version: urxvt v9.22
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

1. Create file test with content:

    ```
    testø
    testæ
    testå
    ```

2. Go to last line, do `o<c-n>` to open keyword completion menu.

### Actual behaviour

The letters `æøå` are not displayed correctly, see screenshot:

![screen](https://user-images.githubusercontent.com/998898/42123559-648dc736-7c54-11e8-99da-dfd21eb724f8.png)

### Expected behaviour

The letters are displayed correctly.

**Comment by KillTheMule** [comment]
urxvt has been troublesome in the past. Did you try different values for `$TERM`? Search brought up `rxvt-unicode-256color` to try, maybe there are others.

**Comment by lervag** [comment]
I've used urxvt for a lot of years, and neovim for perhaps 1 year. I started experiencing this issue recently, but I can't say exactly when and if it was due to an update with urxvt or neovim. However, considering that urxvt v9.22 is ~1 year old, I think the issue must have started with an update of neovim.

Changing `$TERM` does not help.

**Comment by KillTheMule** [comment]
Ok, this is out of thing-I-understand, so someone else needs to chime in. But it would probably be helpful if you could try with a different terminal with correct  `$TERM` setting (I mean, you probably have xterm lying around, right?), just to see what happens. Of course, I guess a bisect would be most welcome, too.

I can try to reproduce later, just need to find out how to get those weird chars into a buffer :D

**Comment by lervag** [comment]
It should suffice to copy the content listed above to a file, then type `test<c-n>`.

I get the same behaviour in `xterm`.

**Comment by KillTheMule** [comment]
Could reproduce, the bad commit is https://github.com/neovim/neovim/commit/0d7daaad98d5874b345453073f6e21b024ee42d4 cc @ZyX-I

**Comment by justinmk** [comment]
@KillTheMule thanks for bisecting! This is also the cause of https://github.com/neovim/neovim/issues/8466 .

**Comment by lervag** [comment]
Thanks, @KillTheMule. I can live with the inconvenience, but I'll be happy to see this fixed. :)
