### ISSUE TITLE
Make it possible to force linewise operation on custom text objects

### ISSUE THREAD

**Issue by wellle** [neovim/neovim#8667]
For (most) built in text objects it's possible to force operation on them to be linewise, for example by using `dVab` (`:h o_V`, `motion_force`). When using custom text objects (defined as mappings by plugins for example), this doesn't currently work.

For example, put this in your `init.vim`:
```vim
onoremap x viw
```
Open any file with a few lines each containing some words. With the cursor on any word, try these:
1. `dw` (builtin) deletes some characters
2. `dVw` (builtin) deletes linewise
3. `dx` (from mapping) deletes some characters
4. `dVx` (from mapping) deletes some characters, but should delete linewise

Neovim should fix that and operate linewise when the operation was invoked with `o_V`.

Some notes: As far as I'm aware plugins use visual mode to select text objects in operator-pending mode. This is done either in visual mode `:normal v` or visual line mode `:normal V`. I'd expect neovim to be able to recognize whether these selections were done linewise or not. Then the user can force the motion `dvab`, `dVab` or not `dab`. If not forced, the mode used by the plugin should be used. If forced, the selection might need to be changed accordingly before applying the pending operator.

For reference, this came up in https://github.com/wellle/targets.vim/issues/214 and was discussed a bit in https://gitter.im/neovim/neovim?at=5b379ff7f1664406610e7483.

Thank you!

**Comment by wellle** [comment]
Hey, quick update: The corresponding vim issue https://github.com/vim/vim/issues/3490 has been closed and a solution has been released in https://github.com/vim/vim/commit/5976f8ff00efcb3e155a89346e44f2ad43d2405a as patch 8.1.0648. 🎉 

So I guess the same solution could now be integrated into Neovim too.

**Comment by justinmk** [comment]
Thanks. If anyone wants to send a patch: https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim
