### ISSUE TITLE
API: "signs" (place, unplace, etc.)

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8668]
There're some issues when working with the signs in vim:

1. Different plugins share same sign id group, which possibly lead conflict.
2. Remove signs one by one could be quite slow, so most plugin use `sign unplace *` to optimize, but that cause signs from other plugins get removed.
3. When using `sign unplace  {id} buffer={bufnr}` for a list of signs, sometimes it could failed to work for some of them.

### Expected behaviour

Provide API like `nvim_buf_add_signs` that works like `nvim_buf_add_highlight`, which could get an initialized src_id and could be used to remove all associated signs.

**Comment by jamessan** [comment]
> Remove signs one by one could be quite slow

I have plans to fix the performance issues of sign usage, so that should help with this.

One other thing that comes to mind would be the ability for a user to specify priority for signs.  For example, if I'm using both Neomake and Signify, I would want Neomake's signs to override Sy's.  Sy defaults to not overriding other plugin signs, but it can be configured to do so.  However, the actual ordering of the `sign place` calls may mean that Sy's sign _still_ gets overridden.

**Comment by prabirshrestha** [comment]
As for api's can we port vim's sign apis to neovim? https://github.com/vim/vim/commit/162b71479bd4dcdb3a2ef9198a1444f6f99e6843. More links to vim issues and PRs can be found at https://github.com/prabirshrestha/vim-lsp/issues/260

I have already ported vim-lsp to use the new sign api and waiting for neovim to have the same api before I merge the PR.  https://github.com/prabirshrestha/vim-lsp/pull/294 Best part about the sign api is I no longer need to maintain extra state in vim variable. Makes synchronizing signs lot easier.

**Comment by bfredl** [comment]
@prabirshrestha The sign implementation code in nvim is largely unchanged from vim, so there shouldn't be anything inhibiting a direct port. The only change of representation is addition of `numhl` attribute in nvim, but it can be optional key to `sign_define` dict arg.

**Comment by prabirshrestha** [comment]
We are using the new signs apis in vim-lsp - `sign_getplaced`, `sign_undefine`, `sign_unplace` instead of the old `execute :sign place`.

**Comment by mhinz** [comment]
@janlazo Maybe you could port the [above mentioned patches](https://github.com/neovim/neovim/issues/8668#issuecomment-465510045) next? :)

**Comment by justinmk** [comment]
Anyone who's interested can port the patches. Porting patches is very amenable to distributed the work, and would go 10x faster if we  had 10x as many people doing it.

**Comment by jerdna-regeiz** [comment]
> Anyone who's interested can port the patches. Porting patches is very amenable to distributed work, and would go 10x faster if we had 10x as many people doing it.

Okay, I gave it a shot. Implemented the patches mentioned and each I could find related to the signs api up to 8.1.0772. Created a PR: #10059
First time ever seen and touched (neo)vim code, thus there may still be a lot to do...

**Comment by jerdna-regeiz** [comment]
I guess when #10078 is merged,this can be closed as well. At least vim-lsp works for me.

**Comment by justinmk** [comment]
Many thanks @jerdna-regeiz
