### ISSUE TITLE
Neovim can't find "neovim" npm package if npm log level is "info"

### ISSUE THREAD

**Issue by craftzdog** [neovim/neovim#8674]
- `nvim --version`:

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? No
- Operating system/version: macOS 10.13.5
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

If you have `~/.npmrc` with loglevel configuration like:

```
loglevel=info
```

`neovim` npm package can not be found correctly.

### Actual behaviour

```
function remote#define#AutocmdBootstrap[1]..remote#host#Require[10]..provider#node#Require の処理中にエラーが検出されました:
行    2:
Cannot find the "neovim" node package. Try :checkhealth
function remote#define#AutocmdBootstrap の処理中にエラーが検出されました:
行   10:
Host " node" for "BufEnter" autocmd is not available
```

### Expected behaviour

Detect neovim npm package correctly.

* * *

https://github.com/neovim/neovim/blob/3cc350696576f26fe1e978ef78125a1a6c7410ab/runtime/autoload/provider/node.vim#L31

I guess this line causes this problem.
`global_modules_dir` will be always `npm info it worked if it ends with ok` because npm's loglevel is info.

**Comment by janlazo** [comment]
`npm --loglevel silent root -g` should fix it.
What about yarn?

**Comment by justinmk** [comment]
Can someone send a PR?

**Comment by craftzdog** [comment]
```
npm --loglevel silent root -g
```

It worked! I believe yarn doesn't have loglevel except for [verbose option](https://github.com/yarnpkg/yarn/issues/763).
I'll send a PR later.
