### ISSUE TITLE
shortmess+=F suppresses output from :echom in ftplugin

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8675]
In b7514493a0c4a4389a5921f15b0b429dae5c75e7 the default for shortmess was changed to include `F`:

>	  F	don't give the file info when editing a file, like `:silent`
>		was used for the command

However, this suppresses also output from `:echom` during ftplugin handling.

I'm using `echohl + echom` in jedi-vim to display errors when loading Jedi (Python) fails, but `shortmess+=F` suppresses this.

I think jedi-vim can be improved in this regard anyway, but changing this default has some rather serious impact I would say - given that it behaves as expected/documented.
I could also imagine that Vim/Neovim could be fixed here to not suppress output from echo/echom, but only suppress the file info really.
(Vim behaves the same when `shortmess+=F` is used)

**Comment by justinmk** [comment]
Isn't this a Vim bug?

**Comment by blueyed** [comment]
Yes.
I just reported it here since the changed defaults triggered it.
(and I think the defaults should not be changed until this is fixed)

**Comment by KillTheMule** [comment]
> Should ftplugins really use :echom for anything important? (Or for anything at all...)

What would be the alternative to communicate with the user?

**Comment by justinmk** [comment]
ftplugins generally should not be "communicating". They are only for setting filetype-specific settings and other initialization.

**Comment by blueyed** [comment]
And what should happen in case of errors?
Use `:echoerr` in general, and report it in another way otherwise (like done for jedi-vim now in https://github.com/blueyed/jedi-vim/commit/cfe1668d72152667e7da43ff0e2d38903ba1e6dc)?

**Comment by blueyed** [comment]
I think in general using `:silent` should be avoided, and `shortmess+=F` basically does this (according to the help at least).

**Comment by justinmk** [comment]
> And what should happen in case of errors?

Why would a ftplugin have errors? They are supposed to be simple.

> :silent should be avoided, and shortmess+=F basically does this 

Good point, `:silent edit ...` has a more drastic effect that I had thought. But, I'm still not sure it's so bad.

**Comment by blueyed** [comment]
> Why would a ftplugin have errors? They are supposed to be simple.

In the case of jedi-vim it might load Jedi (via Python), and that can cause various errors.

**Comment by justinmk** [comment]
`: silent` should not hide errors.

**Comment by blueyed** [comment]
The errors are handled and displayed using echohl/echom.

**Comment by justinmk** [comment]
I think I suggested we should change that once. I don't remember if there was a reason for it. I'm in favor of changing it.

**Comment by jamessan** [comment]
> The errors are handled and displayed using echohl/echom.

Is that because `echoerr` doesn't show up in `:messages`?

**Comment by blueyed** [comment]
@jamessan 
In general `:echoerr` could be used, but it has sideeffects and therefore I've sticked to echohl/echom back then.
In the jedi-vim case it is something to warn the user about, but not e.g. prevent other plugins from loading.

**Comment by justinmk** [comment]
So they currently appear in messages, right?

**Comment by blueyed** [comment]
Not with `shortmess+=F` anymore.
https://github.com/davidhalter/jedi-vim/pull/840/files is a workaround for jedi-vim (and good in general), but this changing of the default might affect others.

**Comment by blueyed** [comment]
This new default setting has been released by now, and jedi-vim was fixed to not use echom anymore for reporting errors.
Closing.

**Comment by blueyed** [comment]
JFI: `:unsilent echom` can be used.
This is useful for multiline output, since you can only have one `:echoerr`.

**Comment by justinmk** [comment]
@blueyed haha, I looked for `:nosilent` and really thought I remembered something like this. Shall we do this?

**Comment by blueyed** [comment]
@justinmk 
Not clear to me what you mean to do here.. I've only meant to mention a workaround here.

**Comment by blueyed** [comment]
Another use case: DidYouMean, which uses `inputlist()` via `BufNewFile` autocommand.
The fix here is also to use `nosilent` (https://github.com/EinfachToll/DidYouMean/pull/12).
