### ISSUE TITLE
No colors for errors during startup (ftplugin)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8676]
Given a ftplugin:

t_ftplugin/ftplugin/python.vim:
```vim
echom 'ftplugin'
echoerr 'ftplugin error'
```

t_ftplugin/minimal-t_plugin.vimrc:
```vim
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath = script_dir.','.&rtp.','.script_dir.'/after'

syntax on
filetype plugin indent on
```

Running `nvim -u t_ftplugin/minimal-t_plugin.vimrc t.py`will display:

```
Error detected while processing /…/t_ftplugin/ftplugin/python.vim:
line    2:                                                                             
ftplugin error
Press ENTER or type command to continue
```

This output however is not colored.

Using Vim (8.1.22) will color the output.

Neovim will also color the output when not passing `t.py` as argument, but editing it after startup (`:e t.py`).

**Comment by justinmk** [comment]
Pretty soon we aren't going to show these errors at all (at least, not until after VimEnter). They will be collected and then shown after a UI (TUI or GUI) connects.

**Comment by justinmk** [comment]
@blueyed The steps seem incomplete. Is there a 'rtp' step missing?

**Comment by blueyed** [comment]
@justinmk 
Yes, sitll happens on master.

No rtp should be necessary, I can still reproduce it using `nvim -u t_ftplugin/minimal-t_plugin.vimrc t.py` and the following layout:

```
% tree t_ftplugin
t_ftplugin
├── ftplugin
│   └── python.vim
└── minimal-t_plugin.vimrc
```

**Comment by blueyed** [comment]
Updated my comment above.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9829 may fix this.
