### ISSUE TITLE
line_breakcheck taking up a lot of time in find_tags?

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#868]
Trying out running nvim as my main binary again, and this time I get a different profile than the last time. There are a few culprits to the extreme slowness I experience, but this one jumped out (see screenshot).

![screen shot 2014-06-19 at 15 12 20](https://cloud.githubusercontent.com/assets/189413/3327708/5eaaaffc-f7b3-11e3-8177-7428d15bd4da.png)

Close up:

![screen shot 2014-06-19 at 15 13 40](https://cloud.githubusercontent.com/assets/189413/3327722/8c63cb7c-f7b3-11e3-9b4f-6aa98b9c7ad2.png)

I could compile a vanilla vim without python support and thus find out if vim-easytags also has this problem on vanilla vim (vim-easytags has a python codepath that's faster). But since this touches one of the hearts of the new event layer I thought I'd ping @tarruda to see if he has any insights.

**EDIT**: without knowing anything more about the problem, the first fix I'd suggest to myself is to only call `line_breakcheck` after 10ms or something:

```c
proftime_T current = os_hrtime();
for (...) {
  // zyx will most definitely point out that overflow is possible here and I should use one of the profile compare functions, I will agree with him.
  if (os_hrtime() - current > 10 * MSEC_TO_NSEC) { 
    current = os_hrtime();
    line_breakcheck();
  }
  // ...
}
```

Or could `line_breakcheck` be optimized in another way so this hack isn't necessary?

**EDIT 2**:

Digging in vanilla vim, this is the `mch_breakcheck` code:

```c
    void
ui_breakcheck()
{
#ifdef FEAT_GUI
    if (gui.in_use)
	gui_mch_update();
    else
#endif
	mch_breakcheck();
}

/*
 * Check for CTRL-C typed by reading all available characters.
 * In cooked mode we should get SIGINT, no need to check.
 */
    void
mch_breakcheck()
{
    if (curr_tmode == TMODE_RAW && RealWaitForChar(read_cmd_fd, 0L, NULL))
	fill_input_buf(FALSE);
}
```

And `RealWaitForChar` predictably calls `select()` to wait for the character. The equivalent action libuv takes on OSX is calling kqueue's `kevent()` with a zero timeout struct. Perhaps `kevent()` is just slower than `select()` for polling (timeout = 0)? That really shouldn't be though, they could switch to `select` inside of `kevent()` too...

Even still, on the apple mailing list I found a hint that `kqueue` should be faster than `select` in this case too: http://lists.apple.com/archives/Unix-porting/2008/Nov/msg00061.html

**Comment by justinmk** [comment]
@jamessan Is working on this and it should be fixed soon. https://github.com/vim/vim/pull/1046
