### ISSUE TITLE
word completion hangs when netrw buffer is open in tree mode

### ISSUE THREAD

**Issue by macciocu** [neovim/neovim#8683]
For long I've been fighting with the word completion menu, it fails frequently (does not appear, hangs in SCANNING mode) and it is difficult to exactly detect why. I'm 100% secure that it only happens when I have netrw open in either an existing or hidden buffer. With the method described below I'm able to reproduce the erroneous behaviour 100% of the time.

- `nvim --version`: 0.2.3-dev
- Vim 8.0: Not reproduced
- OS: MacOS 10.13.5 High Sierra
- Terminal: iTerm2

### Steps to reproduce:

init.vim must contain the following:
```
let g:netrw_liststyle = 3
```
Perform the following
```
touch test.js
echo "require1" >> test.js
echo "require2" >> test.js
nvim test.js
:vs.
```
now below the which contains "require2", type re and press CTRL+n to popup the word completion menu.

### Actual behaviour

The completion menu does not pop up, instead the message SCANNING keeps displaying in the statusbar.

### Expected behaviour

The completion menu must popup providing work completion option "require1" and "require2"

**Comment by justinmk** [comment]
Could be related to netrw's promiscuous use of the clipboard. Merging with https://github.com/neovim/neovim/issues/6695.
