### ISSUE TITLE
Terminal buffer has incorrect width

### ISSUE THREAD

**Issue by iclanzan** [neovim/neovim#8686]
- `nvim --version`:
  ```
  NVIM v0.3.0
  Build type: Release
  LuaJIT 2.1.0-beta3
  ```
- Vim (version: ) behaves differently?
- Operating system/version: NixOS/18.03
- Terminal name/version: Alacritty/0.1.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set number
:autocmd TermOpen * setlocal nonumber
:split | terminal
```

### Actual behaviour

Executing `tput cols` in the newly opened terminal reports an incorrect number of columns as if the `number` option was still set. Executing any application with a TUI such as `top`, a gap can be seen at the right edge.

### Expected behaviour

`tput cols` should report the correct number of colors; `top` and any other TUI should extend all the way to the right edge of the terminal buffer.

**Comment by justinmk** [comment]
`:terminal` width is not aggressively changed after the buffer is initialized. This is discussed at length in many other issues.

**Comment by iclanzan** [comment]
I have searched existing issues before opening this one but couldn't find anything related. Can you show me one such issue?
