### ISSUE TITLE
Cannot figure out autocmd to enter insert mode when <LeftMouse> a terminal pane?

### ISSUE THREAD

**Issue by benjie** [neovim/neovim#8691]
<details>
<summary>`nvim --version`: NVIM v0.2.2</summary>

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_
HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-prote
ctor-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-9240
7-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/
local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/
build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

</details>

- Operating system/version: macOS 10.13.4
- Terminal name/version: iTerm2 v3.1.5 (also occurs in Oni)
- `$TERM`: `screen-256color` (inside tmux) or `xterm-256color` (in iTerm directly)

### Steps to reproduce

Use the short custom vimrc below:

```bash
cat > test-init.vim <<HERE
set mouse=a
augroup terminal
  autocmd!
  "autocmd TermOpen * setlocal nonumber norelativenumber
  autocmd TermOpen * startinsert
  autocmd FocusGained,BufEnter,BufWinEnter,WinEnter term://* startinsert
  "autocmd BufEnter * if &buftype == 'terminal' | :startinsert | endif
augroup END
HERE

nvim -u test-init.vim
```

```viml
:sp
:terminal
echo Hello
<C-\><C-n> " to escape from terminal mode
<C-w><C-j> " to move to non-terminal split
<LeftClick> on terminal pane
<Enter> " expecting 'echo Hello' command to run
```

### Actual behaviour

Need to press `i` to enter insert mode to be able to type into the terminal after clicking.

(It seem from cursor movement like it enters insert mode and then _something else_ happens and it immediately exits insert mode. I've no idea how to debug this, it might just be a phantom visual?)

### Expected behaviour

Should be in insert mode and able to type commands immediately in the same way that you can if you use <C-w><C-k> to return focus to the terminal split from the non-terminal split.

### Possibly related

Not sure if #7164 is related?

**Comment by KillTheMule** [comment]
I was able to reproduce it using a post-0.3.0 neovim version, terminal st.

Note that `autocmd BufEnter * if &buftype == 'terminal' | :startinsert | endif`  does the deed when not using the mouse to switch back to the window containing the terminal buffer. If using the mouse, I can confirm that

> (It seem from cursor movement like it enters insert mode and then something else happens and it immediately exits insert mode.

is exactly what it looks like to me, to. I've made sure to not accidentally activate visual mode when using the mouse.

**Comment by benjie** [comment]
<details>
<summary>I've reproduced in v0.3.0 also</summary>

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```
</details>

**Comment by justinmk** [comment]
Another oddity: if I try this:

    :autocmd FocusGained,BufEnter,BufWinEnter,WinEnter * call feedkeys('i')

After clicking on a `:term` window, the char `i` is feed into the terminal job (it appears at the shell prompt), but the cursor remains in normal mode.

So the problem(s) could be that FocusGained,BufEnter,BufWinEnter,WinEnter (some or all of them) are fired before cursor placement or `terminal.c` redraw. Some sort of ordering issue there.

**Comment by rofrol** [comment]
Solution https://github.com/neovim/neovim/issues/9483#issuecomment-569417862
