### ISSUE TITLE
neovim 0.30 work with cscope verbose 

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [neovim/neovim#8693]
- `nvim --version`: 0.30
- Vim (version: ) behaves differently? 8.0
- Operating system/version: macos 10.13
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
if has("cscope")

    " add any cscope database in current directory 
       cs add $CSCOPE_DB
    " not show msg when any other cscope db added
    set nocsverb  
endif
```

### Actual behaviour
i want to add cscope db at neovim start , but every time i start vim , the cscope db added verbose shows and ask me to press enter to continue, even i set nocsverb.
i don't know which part is responsible for this problem, but neovim 0.2.2 works fine.
### Expected behaviour
no verbose show .

**Comment by mhinz** [comment]
See `:h 'cscopeverbose'`: _Enabled by default. Use `:silent` instead._

I use a similar approach:

https://github.com/mhinz/dotfiles/blob/master/.vim/vimrc#L466

**Comment by justinmk** [comment]
Yes, Vim's default of `nocscopeverbose` is a historical accident. If you invoke `:cscope` and there's a problem, there is no feedback about the problem. That's very confusing, and no other command behaves like that. Why would you want this?

For your personal config, if you want to ignore errors of a particular command, you prefix it with `:silent!` and @mhinz mentioned. Just like _every other command_.
