### ISSUE TITLE
Can't get contents of Neovim version

### ISSUE THREAD

**Issue by JAffleck** [neovim/neovim#8697]
- `nvim --version 3.0` FWIW this is nvim-qt:
- Vim (version: ) behaves differently?
- Operating system/version Windows 10 x64:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

I can run the following command, but I can't copy it (i.e. the text, not the image) to a buffer to report a bug on a plugin I'm using.
It just shows `press enter or enter command to continue`
```
:version
![image](https://user-images.githubusercontent.com/5248068/42401406-b96a68d0-8132-11e8-9e40-a3de7e664c9f.png)

```

**Comment by justinmk** [comment]
:help :redir
