### ISSUE TITLE
api fail to get current window statusline option

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#8706]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) N/A
- Operating system/version: Linux 4.4.0-127
- Terminal name/version: gnome-terminal 3.18.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
With test.vim as follows:
```vim
echo nvim_win_get_option(nvim_get_current_win(), 'statusline')
``` 
Start nvim with
```
nvim -u NORC
```
```vim
:source test.vim
```

### Actual behaviour
Error detected while processing /home/shihming/test.vim:
line    1:
Unable to get value for option "statusline"
0

### Expected behaviour
Should output the statusline.
Note that if test.vim is changed to
```vim
echo nvim_get_option('statusline')
```
No error is produced.

**Comment by justinmk** [comment]
I think this was fixed in 0.3

**Comment by ipod825** [comment]
I tried the v0.3.1 appimage, but still got the same problem.
Did you succeed in other version?

**Comment by bfredl** [comment]
It seems if only global value and not local value is set it throws an error. It should probably return the empty string, which is what `setl statusline` shows in this situation.

**Comment by justinmk** [comment]
This is working as designed, I think it was discussed thoroughly last time.

@ipod825 Use `nvim_get_option` (not `nvim_win_get_option`) to get _global_ option values.

**Comment by jamessan** [comment]
That's not very ergonomic for local-global options when there's no local option set.  Although, it does make clear _where_ the option is set.

**Comment by justinmk** [comment]
If the goal is to just reuse the implementation of `getbufvar({nr}, '&foo')`, then why don't we do that instead of whatever implementation we have ended up with.

**Comment by bfredl** [comment]
It would be slightly more ergonomic if sentinel value (either `""` or `nil`, not 100% sure `""` is sentinel for all string options) is returned instead of error thrown. Unset local option is not an error, but a valid and distinct state.
