### ISSUE TITLE
can not open nvim-qt with Right click menu

### ISSUE THREAD

**Issue by ystyle** [neovim/neovim#8711]
- `nvim --version`: v0.2.2
- Vim (version: ) behaves differently?
- Operating system/version: windows 10 pro 
- Terminal name/version:  nvim-qt 
- `$TERM`: 

### Steps to reproduce 
install Right click menu: save as `install-neovim.reg`
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\Open with Nvim]
"Icon"="D:\\Application\\Neovim\\bin\\nvim-qt.exe"

[HKEY_CLASSES_ROOT\Directory\Background\shell\Open with Nvim\command]
@="D:\\Application\\Neovim\\bin\\nvim-qt.exe \"%v\""

```
Right click in empty folder， Open with Nvim , then the qt window are white screen and display 

`neovim is taking too long to respond retry`
![](http://osloqpukl.bkt.clouddn.com/20180709/1700-S.png)
![](http://osloqpukl.bkt.clouddn.com/20180709/1658-F.png)

**Comment by KillTheMule** [comment]
First thing to do, upgrade to Neovim 0.3, it's been released lately and contains a lot of fixes.

**Comment by janlazo** [comment]
Is nvim.exe in `PATH`?

**Comment by ystyle** [comment]
@janlazo  it cant work on desktop width right click 
but D:\Programming it's not work . 
Less part of folder cant work

**Comment by ystyle** [comment]
@KillTheMule @janlazo I upgrade  to Neovim 0.3 , it works , 
 Just ask, how to set the initial window size of nvim-qt ？ 
open some  folder, the window it's too small 
![](http://osloqpukl.bkt.clouddn.com/201818092337-o.png)

**Comment by janlazo** [comment]
See https://github.com/equalsraf/neovim-qt/issues/106#issuecomment-359467499

**Comment by ystyle** [comment]
thanks
