### ISSUE TITLE
Weird windows resize behaviour

### ISSUE THREAD

**Issue by huangyingw** [neovim/neovim#8714]
- `nvim --version`: Compiled from latest master branch
- Vim (version: ) behaves differently? Yes
- Operating system/version: macOS High Sierra 10.13.5
- Terminal name/version: iTerm2/3.1.7
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim`
Launch nvim from iTerm
Open this file: .git/index (any index file inside .git folder is ok)
Open another file(any file is ok, say ~/.vimrc) use ‘vs’ command, and maximize it ‘vert resize’
Switch to other app(say chrome), and then switch back to iTerm

### Actual behaviour
~/.vimrc window is a little smaller, make room for another window .git/index. .git/index a little larger.
### Expected behaviour
~/.vimrc is still fully maximize.

**Comment by mhinz** [comment]
I can't reproduce that with `nvim -u NORC` in iTerm2. The small window is always 1 character wide.

**Comment by justinmk** [comment]
What are the minimal steps to reproduce starting with `nvim -u NORC` ?

**Comment by huangyingw** [comment]
nvim -u NORC

**Comment by justinmk** [comment]
Vim has different defaults than Nvim. This is documented at `:help nvim-defaults`.

**Comment by huangyingw** [comment]
@justinmk @mhinz 
Maybe it is related to vim-fugitive. 
After removing this plugin, this issue disappear in nvim.
But, in vim, with this plugin, no this issue.
Could you install vim-fugitive plugin, and try again ? 

So, the repro steps are:
install vim-fugitive
Launch nvim from iTerm
Open this file: .git/index (any index file inside .git folder is ok)
Open another file(any file is ok, say ~/.vimrc) use ‘vs’ command, and maximize it ‘vert resize’
Switch to other app(say chrome), and then switch back to iTerm

**Comment by justinmk** [comment]
I do use vim-fugitive. You haven't provided minimal steps to  reproduce the issue.

**Comment by huangyingw** [comment]
install vim-fugitive
Launch nvim from iTerm
nvim ~/loadrc/.git/index (any index file inside .git folder is ok)
:vs ~/.vimrc
:vert resize

Switch to other app(say chrome), and then switch back to iTerm

-----------
Could you repro from this steps ?

**Comment by huangyingw** [comment]
@justinmk 
I could later prepare an AWS machine, and try to reproduce from that machine, and give you access.

**Comment by mhinz** [comment]
Yeah, it happens on `:call fugitive#ReloadStatus()` which is triggered automatically on the `FocusGained` event, so when you switch back to the iTerm2 window.

Mystery solved!

**Comment by huangyingw** [comment]
@mhinz great.
So, is this nvim issue or fugitive issue ? 
I will also try to fix it. I would be very happy if I could fix it myself :)

**Comment by mhinz** [comment]
It's a fugitive thing, but it's no bug either.

Read `:h 'winminwidth'` and `:h 'winwidth'`. The defaults for these are 1 and 20.

When you do `:vert resize`, the one window will be resized to the width of 1. When you switch to that window (e.g. `<c-w>w`), then it will be resized to 20.

And `fugitive#ReloadStatus()` cycles through your windows, so you're left with windows that all have a width of at least 20.

**Comment by huangyingw** [comment]
@mhinz Great thanks for your explanation.
