### ISSUE TITLE
:source buffer contents without saving file

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#8722]
Right now, you can only `:source` files. I would be totally great if we could `:source` strings, in particular for usage in the remote API. A current workaround in the functionaltests is to write a temporary file and source that, but that comes with a set of drawbacks of course. To achieve that goal, one might look at `f_source` in `eval.c` to see if it can't be properly refactored that a possible `f_source_str` function is basically just another callee.

I want this, but I don't want to do it myself, so I'm putting up this issue ;) 

@justinmk Is this easy enough for a "good first issue", or something like that? I'd appreciated it if you could put some roughly appropriate tags on this :)

**Comment by justinmk** [comment]
Should also add `nvim_source` API function.

**Comment by wsdjeg** [comment]
so what is the difference between `:source {string}` and `:exe {string}`

**Comment by bfredl** [comment]
@wsdjeg `:exe` and `nvim_command` supports some multiline constructs, but not all. For instance heredocs (`:py3 << EOF`) will not be supported IIRC.

**Comment by wsdjeg** [comment]
@bfredl Thanks, I got it.

**Comment by Siddhant085** [comment]
I would like to take this up. I don't understand the expected behavior. Do you want to do `:source bufferName` or `:source {string}`, where string is a set of vim commands.

**Comment by bfredl** [comment]
Do we even need to extend the command? If `nvim_source` were available, it would be directly usable as `:call nvim_source(...)` in vimL?

Also do we maybe want to to supply a name like `nvim_source(code, "name")` so vimL tracebacks can have a meaningful name (currently the name is the empty string for `nvim_command("nonexistingcmd")` which just looks weird).

**Comment by KillTheMule** [comment]
> Do we even need to extend the command? If nvim_source were available, it would be directly usable as :call nvim_source(...) in vimL?

Sure, I think that's I was only talking about refactoring in my initial post :) Probably a good idea not to overload `:source` :+1:


> Also do we maybe want to to supply a name like nvim_source(code, "name") so vimL tracebacks can have a meaningful name (currently the name is the empty string for nvim_command("nonexistingcmd") which just looks weird).

Not sure if that helps, are people going to set this to something meaningfull? Maybe it could just contain "nvim_source" instead of the name, that makes it clear where it comes from. Better even if it said "from commandline" or "from file x on line y", but let's not burden @Siddhant085  with that on his first issue :)

**Comment by Siddhant085** [comment]
@KillTheMule  from what I have understood is that you want a new function `nvim_source` that accepts vimL code and executes it. Also I had this doubt, can't we do :{string}, where string is a vimL code to execute it.

**Comment by bfredl** [comment]
> Not sure if that helps, are people going to set this to something meaningfull? Maybe it could just contain "nvim_source" instead of the name, that makes it clear where it comes from. Better even if it said "from commandline" or "from file x on line y", but let's not burden @Siddhant085 with that on his first issue :)

I hoped it was clear my point was getting the interface right, not to burden someone before even starting. All intended functionality of a API function is typically not included in the first prototype...

**Comment by KillTheMule** [comment]
> I hoped it was clear my point was getting the interface right, not to burden someone before even starting.

Yeah, no, that was only meant for my implicit call of "we could rework all error messages". My main point was supposed to be "I don't think passing a name for a string you want to source is helpfull", sorry if that was unclear!

**Comment by bfredl** [comment]
Yes, It would be better if the lua executor layer would supply the context automatically, but this cannot be known from an rplugin. But maybe if it was possible to introspect the entire code block by itself, that would be enough context already.

**Comment by Siddhant085** [comment]
There is no `f_source` function in `eval.c`. `:source` gets implemented by `ex_source` in `ex_cmds2.c` which in turn calls `do_source`. My doubt is, so we are overloading `do_source` to accept both filename and string, how should we differentiate between the two options. I am thinking we can see if the filename is not found we attempt to execute it as vimL command. For example `do_source( ls)`, we first look for a file named `ls` if not found we execute it as vimL command. Another option is to have a new function `do_source_str` to accept and handle strings independent of `do_source`.

**Comment by KillTheMule** [comment]
> There is no f_source function in eval.c. :source gets implemented by ex_source in ex_cmds2.c which in turn calls do_source.

Ah yeah, my bad, you're right.



> Another option is to have a new function do_source_str to accept and handle strings independent of do_source.

That's the way to go for sure.

**Comment by Siddhant085** [comment]
We can use do_source_str to source str. Now should I implement nvim_source API from which this function will get called to source vimL code.

**Comment by bfredl** [comment]
Btw, here is a minimal test case for what `nvim_source` should support

```
let x = "lua <<EOF\ny=3\nEOF"
" this gives an error:
call nvim_command(x)

" when nvim_source is added, this should work:
call nvim_source(x)
echo luaeval("y")
```

**Comment by cyberntype** [comment]
Looking through the source code a bit, I thought I'd take this up (unless there's an active pull request) but I have a few questions about how to go about it.

The two existing code paths to go through are openscript or do_cmdline. From a prior message it sounds like do_cmdline is somewhat limited and it would need to be consumed in a loop.

Openscript expects some sort of file which it consumes via vgetorpeek. I haven't looked into how the source reads a file into a buffer. Possibly putting the string into the same buffer files reads use
and then calling more or less the same functions could work. Alternatively, and no idea if this would work on Windows, is to create a memory file and just pass that to openscript.

Let me know if I missed another way to do this.

**Comment by norcalli** [comment]
Should this be extended to making `:h nvim_parse_expression` multiline as well? It also seems like one could add a `nvim_execute_ast` function and then implement `nvim_source` as `nvim_execute_ast(nvim_parse_expression(expression))` approximately.

**Comment by bfredl** [comment]
@norcalli that would certainly be interesting, but the effort here is not "just" make existing expression code support multiline, but rather implement a full parser also for Ex commands. (it was @ZyX-I:s original plan, but he stopped working on this after implementing expressions). Though this is not specifically related to `nvim_source`, if we had a complete ast parser/executor we would aim to use it for everything.
