### ISSUE TITLE
Rapid output to hidden :terminal buffer breaks rendering in other buffers

### ISSUE THREAD

**Issue by andreyorst** [neovim/neovim#8723]
- `nvim --version`:  
  ```
  NVIM v0.3.1-120-g12481781a
  Build type: RelWithDebInfo
  LuaJIT 2.0.5
  Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/aorst/.cache/yay/neovim-git/src/neovim-git/build/config -I/home/aorst/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/aorst/.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/aorst/.cache/yay/neovim-git/src/neovim-git/build/include
  Compiled by aorst@s06  
  
  Features: +acl +iconv +jemalloc +tui 
  See ":help feature-compile"  
  
  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
  ```
- Vim version:
  ```
  VIM - Vi IMproved 8.1 (2018 May 17, compiled May 25 2018 00:52:08)
  Included patches: 1-22
  Compiled by Arch Linux
  ```
  Behaves differently - yes.
  Vim opens terminal in a horizontal split by default. With such setup there is no problems neither in Vim nor in neovim. However if I open terminal in another buffer, as soon as I exit insert mode terminal stops its live updating. So there is no issue in oter buffer.
- Operating system: Arch Linux
- Terminal name/version: Termite v13
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`  
```
nvim -u NORC test
:set hidden
:terminal tree /
:bn
```
Input several lines of text while tree prints your entire disk tree.

### Actual behaviour
See video:
[simplescreenrecorder-2018-07-11_13.54.57.tar.gz](https://github.com/neovim/neovim/files/2184147/simplescreenrecorder-2018-07-11_13.54.57.tar.gz)
The buffer contents are moving around, showmode string is flickering, cursor sometimes moves around. Also it segfolts sometimes.

### Expected behaviour
Regular usage of neovim.

As a proposed solution maybe neovim should not update terminal buffer contents if it is hidden until user switches back to it.

**Comment by justinmk** [comment]
The buffer still needs to be updated (this could matter for scripts). But it definitely should not ever cause a redraw of any sort, if it's not visible to the user.

I had addressed this in the past but I guess something slipped through.

**Comment by andreyorst** [comment]
I've noticed this, because I often run builds in the background, while editing the code. With plugins like airline, and UI settings enabled (relative number, cursorline) the glitches become more worse. It also affects syntax highlighting AFAICS.

**Comment by sras** [comment]
I am also affected by this issue. It is very annoying and almost breaks most of my workflow. I am on 0.3.0 version. 

I have a terminal where live compiling is going on. So I have this hidden most of the time. When I make a change in the source, it triggers the compilation in the hidden terminal. Then the lines in my source buffer starts scrolling up as if affected by the hidden terminal's output. The line numbers are also messed up. It gets restored as the terminal stops output. But until then, you can do very little editing with screen constantly jumping around in an unpredictable way.

**Comment by sras** [comment]
Another thing I notice is that this issue only happens after using nvim for a while, as if triggered by some buffer getting filled up.

**Comment by sras** [comment]
This issue has become so bad that the buffers are completely messed up (lines gets shifted up) that I having to do a compete reload of the file after switching back to neovim from another application, to resume editing.

@justinmk Any chance this is related to https://github.com/neovim/neovim/issues/8782 ?

**Comment by andreyorst** [comment]
> do a compete reload of the file after switching back to neovim

<kbd>Ctrl</kbd>+<kbd>L</kbd> or `:redraw` doesn't help?

**Comment by sras** [comment]
@andreyorst 

I haven't tried them. I have now switched back to Neovim 2.2 and it seems that the issue is not present in that branch.

**Comment by sras** [comment]
@andreyorst 

Ctrl + L seems to restore the screen. But it is of little help as the screen keeps on scrolling right after.

**Comment by justinmk** [comment]
#9674 may have fixed this. e386e51d9e284ece5fe78a6dbcc0c8c4f166e48a
