### ISSUE TITLE
log: include milliseconds

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8727]
Neovim's log currently only includes the seconds, but for debugging it is often useful to have a finer granulation, and therefore milliseconds should be included for this.

**Comment by jamessan** [comment]
Is this solely for logging or is it related to #4433?

**Comment by blueyed** [comment]
It's for Neovim's own log, but I also remembered #4433 and were just looking at https://github.com/neovim/neovim/pull/5189 from there, where a function should be available already.
