### ISSUE TITLE
`syntax <opt>` inside false branch of `if` running prior to loaded scripts disables syntax highlighting

### ISSUE THREAD

**Issue by aw1621107** [neovim/neovim#8728]
- `nvim --version`:
```
NVIM v0.3.1-162-g9adb6ed74
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/home/awang/code/neovim/build/config -I/home/awang/code/neovim/src -I/home/awang/code/neovim/.deps/usr/include -I/usr/include -I/home/awang/code/neovim/build/src/nvim/auto -I/home/awang/code/neovim/build/include
Compiled by awang@sid

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr///////share/nvim"
```
The slash abuse for the `$VIM` fall-back was because I only found out after compiling that neovim uses `/usr/local/share/nvim` by default for the fall-back, instead of what the version of neovim installed through apt uses (`/usr/share/nvim`). The lazy fix was to just replace `local` with `/////` using `sed -i -e 's/\/usr\/local\/share/\/usr\/\/\/\/\/\/\/share/g'`. I'm hoping that that didn't break anything else (the problem is also present on the apt-installed version of neovim, for what it's worth)...

- Vim (version: ) behaves differently? Don't think it's applicable, because regular vim doesn't have syntax highlighting on by default?
- Operating system/version: Debian sid
- Terminal name/version: Konsole 18.04.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
awang@sid:~/code/neovim/build/bin$ echo "int main() { return 0; }" > test.cpp
awang@sid:~/code/neovim/build/bin$ ./nvim -u NORC -c "if has('foo') | syntax on | endif" test.cpp
awang@sid:~/code/neovim/build/bin$ ./nvim -u NORC --cmd "if has('foo') | syntax on | endif" test.cpp
```

### Actual behaviour

No syntax highlighting present with `--cmd` flag when `syntax on`, `syntax off`, or `syntax enable` is present between `|` characters. Syntax highlighting present with `--cmd` flag if anything else is present between `|` characters, or regardless of text between `|` characters when `-c` flag is used.

### Expected behaviour

Syntax highlighting observed regardless of text between `|` characters and whether `-c` or `--cmd` is used

----

I originally came across this because I wanted to put something like this in my vimrc:

```
if has('nvim')
    " neovim-specific settings
else
    syntax on
    " other vim-specific settings
endif
" other common settings
```

But I found that `syntax on` in that location would cause neovim to no longer have syntax highlighting. I could still turn it on by placing `syntax on` in the neovim-specific branch of the if statement, or after the else branch, but that seemed to be redundant to me given that neovim should have syntax highlighting on by default.

**Comment by justinmk** [comment]
This was a Vim bug. It should have been fixed by b58c17f8df95 .
