### ISSUE TITLE
nvim doesn't entirely fit a nerdtree bottom menu window

### ISSUE THREAD

**Issue by idanko** [neovim/neovim#8735]
- `nvim --version`: ```NVIM v0.3.1-162-g9adb6ed
Build type: Release
LuaJIT 2.0.5```
- Vim (version: ```VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2018 06:52:49)
macOS version
Included patches: 1-150``` ) Works as expected;
- Operating system/version: MacOS High Sierra, Ubuntu 18.04 amd64
- Terminal name/version: iterm2(but doesn't matter: the issue is reproduced on ubuntu too)
- `$TERM`: xterm-256color

### Steps to reproduce using Plug:
- add to the init.vim file nerdtree repo:
```
call plug#begin()
	Plug 'scrooloose/nerdtree'
call plug#end()
```
- PlugInstall;
- open a new nvim window;
- open a NerdTree right panel;
- select any directory on the penel;
- hit `ma` shortcut, which is going to add a file/folder to the selected directory.

### Actual behaviour
The opened bottom window shrinks and truncates the message partially.
<img width="911" alt="actual" src="https://user-images.githubusercontent.com/8293386/42641207-b65c29de-85fc-11e8-9135-f5c51cf078bc.png">

### Expected behaviour
The opened bottom window shouldn't shrink or truncate the message.
<img width="910" alt="expected" src="https://user-images.githubusercontent.com/8293386/42640797-c0967c34-85fb-11e8-83f0-54bfb6354684.png">

Note that I can't reproduce the issue on NVIM v0.2.3-1-gd6f9d1d

**Comment by idanko** [comment]
Note that I can't reproduce the issue on NVIM v0.2.3-1-gd6f9d1d

**Comment by idanko** [comment]
Update: the issue is reproduced even on the nerdtree tag 5.0.0 (Fri Nov 13)

**Comment by KillTheMule** [comment]
Maybe related to https://github.com/neovim/neovim/pull/8088?

**Comment by idanko** [comment]
To make nerdtree works as it is in vim, need to `set display-=msgsep`
