### ISSUE TITLE
Trace settings in debug

### ISSUE THREAD

**Issue by nyarly** [neovim/neovim#8739]
This is a feature request. It would incredibly useful to me if I could set a tracepoint in debug mode (i.e. `nvim -D` or `:debug`) on an nvim settting. In particular, my `'number'` setting gets unset somehow, and greps of my plugins don't give any clues.

I'd love to be able to say `:trace number` and have debug mode break when the setting was about to be changed.

Likewise, it might be handy to be able to trace global and buffer variables.

**Comment by jamessan** [comment]
Have you tried `:verbose set number?` to see why it changed?

**Comment by jamessan** [comment]
You could probably also use the `OptionSet` autocmd to tell you what you want.  Something like `au OptionSet number echom execute('verbose set number?')`.

**Comment by justinmk** [comment]
> trace global and buffer variables.

You can trace `g:`, `b:` and any other dictionary with `dictwatcheradd()`.

For options, what @jamessan said.

A more powerful/comprehensive trace feature would be nice but is probably better achieved by adding log statements and recompiling.

**Comment by nyarly** [comment]
Thanks all.
