### ISSUE TITLE
nvim_buf_attach doesn't work for all listed buffers.

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8741]
- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently? vim don't have buffer update
- Operating system/version: Mac
- Terminal name/version: iterm2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Javascript code:

``` js
function bindBuffer(buffer) {
  let cb = (buf, tick, firstline, lastline, linedata, more) => {
    console.error('----------')
    console.error('result:', tick, firstline, lastline, linedata, more)
  }
  buffer.listen('lines', cb)
  buffer.listen('detach', buf => {
    console.error('detached')
  })
}

async function setup(nvim) {
  let buffers = await nvim.buffers
  for (let buf of buffers) {
    console.error('bind ' + buf.id)
    bindBuffer(buf)
  }
}

module.exports = (plugin) => {
  let {nvim} = plugin
  plugin.registerAutocmd('VimEnter', setup.bind(null, nvim), {pattern: '*'})
}
```
Save to `~/.config/nvim/rplugin/node/notify.js`

Run `:UpdateRemotePlugins`

```
nvim a b
```

### Actual behaviour

Change of file a work as expected, the buffer update events is fired, but when switched to b by `edit b` or `buffer 2`, buffer update events never get fired.

### Expected behaviour

The hidden buffer should be attached as well.

**Comment by bfredl** [comment]
I don't think `b` is hidden in `VimEnter`, rather listed and unloaded.

**Comment by chemzqm** [comment]
@bfredl Yes, it's not. It's just not loaded and node-client should be improved to handle this behavior.
It could check the return value of `nvim_buf_attach`.
