### ISSUE TITLE
autoload not loading inside a plugin

### ISSUE THREAD

**Issue by dylnmc** [neovim/neovim#8748]
I recently made [a small, simple plugin](https://gitlab.com/dylnmc/lyne-vim). Even though `plug` puts `~/.config/nvim/plugged/lyne-vim/` in vim's `&rtp`, `~/.config/nvim/plugged/lyne-vim/autoload/lyne.vim` is not getting loaded. It works in vim but not in neovim.

---

Inside nvim just after booting up session:

```
Error detected while processing BufWinEnter Auto commands for "*":
E117: Unknown function: lyne#update
Press ENTER or type command to continue
```

---

`:echo &rtp`:

```
/home/dylnmc/.config/nvim,/home/dylnmc/.config/nvim/plugged/lyne-vim/,/etc/xdg/nvim,/home/dylnmc/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/home/dylnmc/.local/share/nvim/site/after,/etc/xdg/nvim/after,/home/dylnmc/.config/nvim/after
```

---

`$ ls ~/.config/nvim/plugged/lyne-vim/**`:

```
autoload:
lyne.vim

plugin:
lyne.vim
```

---

mini-`init.vim`:

```

let $VIMDIR = expand($HOME) . (has('win32') ? '/vimfiles' : has('nvim') ? '/.config/nvim' :  '/.vim')

filetype plugin indent on

if !isdirectory($VIMDIR.'/autoload')
	call mkdir($VIMDIR.'/autoload', 'p')
endif
if empty(glob($VIMDIR.'/autoload/plug.vim'))
	execute 'silent !curl -fLo '.$VIMDIR.'/autoload/plug.vim --create-dirs'
	\	'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

" plug
call plug#begin($VIMDIR.'/plugged')

let g:plug_url_format = 'https://@gitlab.com/%s.git'
Plug 'dylnmc/lyne-vim'

call plug#end()
```

---

`nvim --version` (on arch): `NVIM v0.3.1-159-gec6e78e77`

**Comment by mhinz** [comment]
I can't reproduce it. I did this:

Put your minimal vimrc to `/tmp/mini.vim` and switched to `/tmp`. I only altered the first line to say `let $VIMDIR = '/tmp/vimmy'`.

Then I did:

```
nvim -u mini.vim +PlugInstall +qa && nvim -u mini.vim +scriptnames
```

This throws no error for me and shows this in the last line of `:scriptnames`:

```
/tmp/vimmy/plugged/lyne-vim/autoload/lyne.vim
```

**Comment by dylnmc** [comment]
I don't know if it is an issue with the package (I installed aur/neovim-git, which builds from github repo using `cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_JEMALLOC=ON ..; make`, but I see `~/.config/nvim/autoload/lyne.vim` in `:scriptnames` also.

I, also, just tried to build using the first set of instructions from [install-from-source on the readme](https://github.com/neovim/neovim#install-from-source), and I seem to get the same issue.

**Comment by dylnmc** [comment]
The issue is just me being an idiot. I must have been working on something inside of `~/.config/nvim/autoload/lyne.vim` ... This must have been overruling or taking the place of the plugin's autoload.

Sorry to waste your time with a trivial error.

Thanks for all of your hard work
