### ISSUE TITLE
Add function sandboxing from Vim

### ISSUE THREAD

**Issue by w0rp** [neovim/neovim#8756]
- `NVIM v0.2.0` 
- Vim 8.1.0177 changes the behavior of `:sandbox`
- Operating system/version: Linux
- Terminal name/version: N/A
- `$TERM`: N/A

I opened [an issue for Vim](https://github.com/vim/vim/issues/3182) which led to Bram changing the behavior of `:sandbox`. Introducing lambdas into Vim meant that you could define functions from the sandbox. That could cause some security issues, so Bram made it so all functions can be defined in the sandbox, but functions defined in the sandbox are themselves sandboxed.

### Steps to reproduce using `nvim -u NORC`

`nvim -u NORC`

```vim
:sandbox let g:X = {-> system('echo hello world')}
:echo g:X()
:sandbox function Foo()  
```

### Actual behaviour

The lambda executes the system call, then you get an error when you try to define a function in the sandbox.

### Expected behaviour

The system call shouldn't be allowed, as the lambda execute as a sandboxed function. You should be able to define the function in the sandbox.

### Rationale

There are many plugins that execute functions passed in settings, and any one of those plugins could execute a lambda function after it escapes the sandbox. I just pushed a commit to ALE so you can't define linters from the sandbox at all, but the `g:ale_fixers` variable can accept lambda functions, and that requires a patch in Vim and NeoVim.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9776
