### ISSUE TITLE
hardcopy does not handle unicode by default

### ISSUE THREAD

**Issue by tkerber** [neovim/neovim#8758]
- `nvim --version`: `NVIM v0.3.0`
- Vim (version: ) behaves differently? Untested (but the internet says no)
- Operating system/version: NixOS 18.09-pre
- Terminal name/version: kitty 0.11.2
- `$TERM`: `xterm-kitty`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
iσ<esc>
:hardcopy<return>
```

### Actual behaviour

Page has printed upside down question mark

### Expected behaviour

Page has printed greek letter sigma

**Comment by justinmk** [comment]
I don't know the specifics of hardcopy, but usually a question mark means your font (or printer?) doesn't have that glyph. Vim just sends the bytes ...

**Comment by jamessan** [comment]
See also the `'printencoding'` option.

**Comment by tkerber** [comment]
Vim definitely doesn't just send bytes (`hardcopy.c` is a 3000 line file for crying out loud!), I've sent raw text to printers before, and it's formatted differently. Vim also gets basic syntax highlighting across, etc.

Setting `printencoding` to `utf-8` does not fix the issue. Searching the issue only leads to multiple threads on this being an issue in vim with no resolution. This is not a printer issue, as the glyph does not show up in postscript viewers either. If this is a font issue (and it may well be), then a) why are fallback fonts not used? And b) why does the `printfont` option explicitly not work under anything but windows?

I understand that this is a legacy carry over, but it really should be standard in a modern program to support utf-8; this makes printing from vim borderline unusable in any language but english.

**Comment by bfredl** [comment]
> Vim definitely doesn't just send bytes

I think they meant the actual utf-8 bytes of the text

If there was a simple way to get all syntax highlights on a line-by-line basis, all of `hardcopy.c` could essentially be reimplemented outside vim/nvim, right? And probably in less than 3000-lines, using some reasonable postscript library, I would suspect.

**Comment by chrisbra** [comment]
> If there was a simple way to get all syntax highlights on a line-by-line basis, all of hardcopy.c could essentially be reimplemented outside vim/nvim, right? And probably in less than 3000-lines, using some reasonable postscript library, I would suspect.

As a workaround, I tend to use `:TOhtml` plugin. It's a bit scarry to setup correctly, but printing from a browser usually works much better.
