### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by daniele-orlando** [neovim/neovim#8759]
System: MacOS
Neovim: **0.3.0**
Python: **3.7**
Python 3 client (neovim): **0.2.6**

> DeprecationWarning: the **imp** module is deprecated in favour of **importlib**; see the module's documentation for alternative uses

It is triggered by the plugin `vim-visual-multi` when using the `python3` api.

**Comment by jamessan** [comment]
This is covered by the [issue](https://github.com/neovim/python-client/issues/351) you filed in python-client.  Neovim itself has very little Python in its code base, none of which uses the imp module.

**Comment by daniele-orlando** [comment]
Thanks for the clarification. I was not sure what project was the right one for reporting the issue.
