### ISSUE TITLE
Closing terminal emulator buffer does not kill process

### ISSUE THREAD

**Issue by ldelossa** [neovim/neovim#8760]
- `nvim --version`:
❯ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
- Vim (version: ) behaves differently?
- Operating system/version:
MacOS High Sierra
- Terminal name/version:
Iterm2/zsh
- `$TERM`:
~
❯ echo $TERM
xterm-256color

### Actual behaviour
I'm using vim-go to GoRun my go application. I have a signal handler in this application which catches ctrl-c and gracefully shuts down my code. When I quick the terminal emulator using "q!" the go application continues to run in the backend. What signal does the terminal emulator send to the process that it exec's  ? 

### Expected behaviour
Existing the terminal emulator sends a SIG-INT to the process that it has exec's or forked.

**Comment by justinmk** [comment]
Upgrade to 0.3

**Comment by ldelossa** [comment]
@justinmk you closed too quickly

```
❯ lsof -nP -i4TCP:8003 | grep LISTEN
main    19723 louis   10u  IPv6 0x140c114c1839d223      0t0  TCP *:8003 (LISTEN)

~
❯ nvim --version
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/config -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/src/nvim/auto -I/tmp/neovim-20180612-71518-1f95nfa/neovim-0.3.0/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.0/share/nvim"

Run :checkhealth for more info
```


still occuring. my main app still runs after closing the terminal emulator.

**Comment by ldelossa** [comment]
Referenced vim-go ticket also for review.

**Comment by justinmk** [comment]
If you didn't exit nvim and didn't delete the buffer then the process still runs. You need to `:bdelete!` or `:bwipeout!` the buffer to kill the terminal job. Or exit Nvim. Please say _exact_ steps, not a description of steps.

**Comment by ldelossa** [comment]
@justinmk 

Little bit more digging determined that :q of the terminal window sends a SIGHUP to the spawned process, and my application was not catching this for exiting.

**Comment by justinmk** [comment]
@ldelossa Does `:set hidden?` return 'nohidden' for you?

**Comment by ldelossa** [comment]
Let me provide you with full steps first:

- Open neovim with go source code in buffer
- Using vim-go command I do "GoRun" which launches the go binary in a terminal emulator
- I move into the terminal emulator and place my curser at bottom of the emulator to watch scrolling, testing is done
- I now use "q!" to kill the terminal window
- Immediately after this, I check if go process is still running. It is
- I kill neovim all together and check if go process is running, it is.

I'm able to fix this issue by catching SIGHUP in my go process and gacefully killing my code. 

ctrl-c not working was my fault, I was hitting control-c without being in insert mode.

**Comment by jamessan** [comment]
You shouldn't have to explicitly handle SIGHUB.  Unless you explicitly ignore the signal (or install a no-op signal handler), it should cause your program to stop.

**Comment by ldelossa** [comment]
This is my event loop that winds up working with the terminal emulator:

```
	// block on grpcErrChan and sigChan. this is out event loop
	for {
		select {
		case sig := <-sigChan:
			switch sig {
			case os.Interrupt, syscall.SIGHUP:
				// received interupt gracefully kill server
				log.Printf("received interrupt signal. gracefully stopping service")
				grpcServer.GracefulStop()
				os.Exit(0)
			case os.Kill:
				log.Printf("recived kill signal. exiting ungracefully")
				os.Exit(1)
			default:
				log.Printf("received unhandled signal: %v", sig)
			}
		case err := <-grpcErrChan:
			log.Printf("received grpc server error. exiting: %s", err)
			os.Exit(1)
		}
	}
```

**Comment by jamessan** [comment]
Right, that would be the "or install a no-op signal handler" part of my previous comment.

**Comment by ldelossa** [comment]
@jamessan ahh yes I see what you are saying, yes I usually handle signals in the application to run some kind of code, so in my predicament I do need to catch the SIGHUP. My assumptions would be that a SIGINT or SIGKILL would be sent to any processes launched from neovim  if neovim itself is closed.

**Comment by jamessan** [comment]
`SIGHUP` is the standard signal for when the connection to the terminal is lost.  That's why the `nohup` command exists for running something but allowing the controlling terminal to close.
