### ISSUE TITLE
Unwanted characters appearo n screen whenever window resized or font size is changed

### ISSUE THREAD

**Issue by yedhink** [neovim/neovim#8772]
(most likely to be related to #8322.cc  @fatihict)

- `nvim --version`:NVIM v0.3.0-1304-gf711b6351
- Vim (version: ) behaves differently?   no issues with vim. works as expected
- Operating system/version: Arch Linux 4.17.8-1-ARCH
- Terminal name/version: Simple Terminal(st) v 0.7
- `$TERM`:st-256color

### Steps to reproduce using `nvim -u NORC`
was not able to reproduce with NORC.  

but can be reproduced with this simple config
Contents of sample.vim:-
```
" reproduce error using this config!
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim/
if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
    call dein#add('~/.cache/dein')
    call dein#add('nanotech/jellybeans.vim')
    call dein#end()
    call dein#save_state()
endif
" set a colorscheme.
colorscheme jellybeans
" Turn on line numbers(relative or normal)
set relativenumber
```  
Contents of check.js:-  
```
#!/usr/bin/env node
const http = require('http');
const mysql = require('mysql');

const con = mysql.createConnection({
  host: 'localhost',
  user: 'user',
  password: 'pass',
  database: 'db',
});
```  

```
nvim -u sample.vim check.js

```

### Actual behaviour
unwanted characters are being drawn to the screen when either terminal window is resized or terminal font is changed. not able to set both colorscheme and relativenumbers together. setting one of them at a time fixes the issue.  
[relavant gif to show what's happening](https://imgur.com/3TVjSCn)  

### Expected behaviour
no unexpected characters should be drawn on the screen. redrawing removes the unwanted characters. but redrawing screen everytime with ```<C-L>``` is kinda annoying. Any workaround for this?

**Comment by justinmk** [comment]
Already discussed in https://github.com/neovim/neovim/issues/8322
