### ISSUE TITLE
How to open the menu which generated by the mouse of right click ?

### ISSUE THREAD

**Issue by Abson** [neovim/neovim#8776]
One use question：

As I used in vim8.0, the following figure shows：
![image](https://user-images.githubusercontent.com/13198014/43178540-9147b4f2-9000-11e8-97de-72f55b9a3038.png)

How to use the same function in Neovim ?

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com and the resources listed at https://neovim.io/community/. The issue tracker is for bugs and feature requests. Thanks.
