### ISSUE TITLE
Bash code highlighting issue

### ISSUE THREAD

**Issue by papallas** [neovim/neovim#8777]
Nested quotes in a string in bash script causes inconsistent code formatting in NeoVim.

- `nvim --version`: v0.3.2-dev
- Vim (version: 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)) behaves differently? Yes. Vim formats the code correctly.
- Operating system/version: Ubuntu 10.04.05
- Terminal name/version: Gnome Terminal 3.12.3 (see footnote [1])
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
test_function_1() {
    echo "alias catkin_make_boost='catkin_make ADDITIONAL_VERSIONS=\"1.64;1.64.0\"'" >> ~/.bashrc
}

test_function_2() {
    echo "test" >> ~/.bashrc
}
```

Set syntax highlighting: `:set syntax=sh`.

### Actual behaviour
Code formatting is broken.

![screenshot from 2018-07-25 10 49 00](https://user-images.githubusercontent.com/6514550/43193645-73fd8adc-8ff8-11e8-9dbd-4f43cd42fbf3.png)

### Expected behaviour
Code formatting to be consistent:
![screenshot from 2018-07-25 10 50 45](https://user-images.githubusercontent.com/6514550/43193690-97e84f7c-8ff8-11e8-9723-0b1428ca8d85.png)

If I escape the string like so:

```bash
echo "alias catkin_make_boost=\'catkin_make ADDITIONAL_VERSIONS=\"1.64;1.64.0\"\'" >> ~/.bashrc
```

NeoVim highlight the code correctly but this is now an invalid command.

[1] To get 24-bit colouring in Ubuntu 14.04 Gnome Terminal I needed to get the terminal from `gnome-staging` repository:
```bash
sudo add-apt-repository ppa:gnome3-team/gnome3-staging -y
sudo apt-get update
sudo apt-get install gnome-terminal -y
sudo add-apt-repository -r ppa:gnome3-team/gnome3-staging -y
```

**Comment by justinmk** [comment]
besides what @mhinz said, read:

    :help ft-bash-syntax

and try

    let g:is_bash      = 1
