### ISSUE TITLE
python3_host_prog does not appear to be used correctly during CheckHealth

### ISSUE THREAD

**Issue by naiveai** [neovim/neovim#8778]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? N/A
- Operating system/version: Arch Linux
- Terminal name/version: kitty v0.11.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Run `let g:python3_host_prog='/some/path/to/python'`
(In my case, I set it to `~/.config/nvim/python3-neovim-env/bin/python`)
Run `checkhealth`

### Actual behaviour

Spits out this, for the Python 3 provider:

![ss](https://user-images.githubusercontent.com/40498911/43207648-25fa67ee-9046-11e8-8c0f-c1ec7a6a0e02.png)

At first, it notices the variable. Then it forgets that it exists, and then it uses the wrong executable at the end. Note that if I go to that particular directory and run `./python -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` using the python that I pointed to in `g:python3_host_proc`, it works completely fine and prints the right path.

### Expected behaviour

Uses the executable in `g:python3_host_proc` correctly, and I'm able to run my python plugins.

**Comment by justinmk** [comment]
@blueyed any insight?

**Comment by blueyed** [comment]
See https://github.com/neovim/neovim/pull/8784.

`~/.config/nvim/python3-neovim-env/bin/python` is not supported currently.  You have to use `expand()` around it or use `$HOME .'/.config/nvim/python3-neovim-env/bin/python'` instead.

**Comment by naiveai** [comment]
@blueyed Thanks so much for the quick answer! That works.
