### ISSUE TITLE
py3eval returns 0 but does not throw with invalid g:python3_host_prog

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8785]
Given `t-py3eval-error.vim`:

```vim
try
  echo py3eval('1')
catch
  echom 'error 1: '.v:exception
endtry

try
  echo py3eval('1')
catch
  echom 'error 2: '.v:exception
endtry

echom v:errmsg
echom string(v:errors)
```

Running `nvim --cmd 'let python3_host_prog = "invalid"' -u t-py3eval-error.vim` will display:

```
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
0
0
[]
```

I.e. it displays some error about failing to load the python3 host, but then `py3eval` will return `0` always, instead of raising an exception.

In Vim you will get the following output, in case `python3` is not available:
```
error 1: Vim(echo):E117: Unknown function: py3eval
error 2: Vim(echo):E117: Unknown function: py3eval
```

Also `py3 print(1)` will silently do nothing.

NVIM v0.3.2-37-gb67232c52

**Comment by glacambre** [comment]
Neovim correctly throws error messages on each py3eval on master, so let's close this :).
