### ISSUE TITLE
confirm doesn't show options when used with autocmd's

### ISSUE THREAD

**Issue by ColinRyan** [neovim/neovim#8788]
- `nvim --version`: 0.3.1
- Operating system/version: Arch
- Terminal name/version: alacritty 0.1.0
- `$TERM`: screen-256color 

### Steps to reproduce using

```
cat > test-init.vim <<HERE
autocmd BufNewFile * call confirm('test')
HERE
```
```
nvim -u test-init.vim

```

run the following command
```
:e myfile.we
```

### Actual behaviour

Nothing seems to happen. File doesn't open. No confirm dialog is displayed but, if you hit enter you will go to the file. Seems that confirm is working but not being visually displayed.

### Expected behaviour
I expected to see a confirm dialog at the bottom of the screen, like if I ran the following by itself (which does work)
```
:call confirm('test')
```

Appreciate you people for looking into this :)

**Comment by justinmk** [comment]
Confirmed. Doesn't affect Vim. 

Does it happen in Nvim 0.3.0 or earlier?

**Comment by kinghrothgar** [comment]
I can verify that this bug does not exist in 0.2.2, I have not tried 0.3.0.

**Comment by MichaHoffmann** [comment]
I tried to debug and traced it to 
```
msg_puts_attr_len (str=0x7fe738c9bfb0 "\ntest\n[O]k: ", len=-1, attr=23)
    at ../src/nvim/message.c:1631
```
with 
```
  // Don't print anything when using ":silent cmd".                                                                                                                            
  if (msg_silent != 0) {                                                                                                                                                       
    return;                                                                                                                                                                    
  } 
```
and 
```
(gdb) p msg_silent
$10 = 1
```

**Comment by MichaHoffmann** [comment]
Okay, i'll bisect this one in the afternoon, if it helps!
