### ISSUE TITLE
inccommand: causes "E171: Missing :endif" - fails to parse one-line "if … endif"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8796]
Given `t.vim`:

```vim
set inccommand=split

fun! F(...)
  echom 'called: '.&buftype
  if &buftype != '' | return | endif
endfun

call timer_start(3000, function('F'))
```

Calling `nvim -u t.vim` and quickly typing `:%s/` (before the timer times out) will result in:

```
called:                                                                            
Error detected while processing function F:
line    2:
E171: Missing :endif
:%s/
```

For some reason the `if … endif` gets not parsed properly in this case.

This happens with both `set inccommand=split` and `nosplit`, but not without inccommand.

Is this related to something similar to `-bar` for commands?!

NVIM v0.3.2-52-g9abe0bdb5 (master).
Also happens with v0.3.1.

**Comment by KillTheMule** [comment]
> ... will result in:

To be clear, the error happens when the timer finishes, right? So if you type fast, you have to wait longer for the error to appear, and if you press `<Enter>` before the error, all is well.

I also could NOT reproduce using

```viml
if &buftype != ''
  return
endif
```

**Comment by janlazo** [comment]
@blueyed Does it happen before https://github.com/neovim/neovim/commit/57fafcea23e2609e40ecacf27b2d68add9b1f7e9?

**Comment by blueyed** [comment]
@KillTheMule 
Yes.

@janlazo 
Yes, and also with v0.3.0.

**Comment by blueyed** [comment]
git-bisecting it now.

**Comment by blueyed** [comment]
Caused by 51af911a271eb95c0032d25bef5e9313b81648b9:

    inccommand: do not execute trailing commands #8256
    
    fix #7494

**Comment by justinmk** [comment]
Can someone see if adding a check for `KeyTyped` to https://github.com/neovim/neovim/commit/51af911a271eb95c0032d25bef5e9313b81648b9#diff-e5a85cda52db26f01de2cf7c1f2107cfR607 fixes this?

**Comment by jamessan** [comment]
It does fix it, but is that too localized?  Is there a place where `CMDPREVIEW` can be disabled/restored when handling non-interactive commands?

**Comment by bfredl** [comment]
Around `multiqueue_process_events`? Though it would be better if CMDPREVIEW was reset already at that point; it should only cover the actual execution of the preview command, not when preview window happens to be visible afterwards. (If needed that should have a distinct bool flag)

**Comment by jdhao** [comment]
Is this fixed yet? I am seeing the same error with the following config:

```
function! s:empty_message(timer)
  if mode() ==# 'n' | echo '' | endif
endfunction

augroup cmd_msg_cls
    autocmd!
    autocmd CursorHold * call timer_start(25000, funcref('s:empty_message'))
augroup END
```

**Comment by shade-of-noon** [comment]
For the record, stuff like the minimal config below will also produce the `missing endif` errors:
```
fun! DetectBug()
  if v:false | return | endif
endfun

au BufWinEnter * call DetectBug()

set inccommand=nosplit
```

After these commands, starting from normal mode, typing `:s/` and then entering command window via `<C-F>` will always trigger the error.

**Comment by dsummersl** [comment]
I'm seeing variations of this frequently with the https://github.com/kiteco/vim-plugin plugin.
