### ISSUE TITLE
provider/pythonx: only look at stdout for the version

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8801]
I just had a hard time figuring out why py2 in Neovim on Travis was not working, when being used with pytest-cov, which handles subprocess tracking with Coverage.py.

The reason was some warning that Coverage.py emitted on stderr, and that Neovim picked up when checking the version with `has('python')`.

The code is currently using `python -c` with `system()`: https://github.com/neovim/neovim/blob/a2253744c9bcd9229be9533540075e977f0be2cd/runtime/autoload/provider/pythonx.vim#L70-L76

Should this use something similar to `s:system` in runtime/autoload/health/provider.vim, or should it get wrapped into a shell where stderr is redirected then?

Example build: https://travis-ci.org/davidhalter/jedi-vim/jobs/409614258#L840

Output:

> - provider/pythonx: Could not load Python 2:^@          /home/travis/virtualenv/python2.7.14/bin/python2 is Python Coverage.py warning: --include is ignored because --source is set (include-ignored)^@          2.7

**Comment by justinmk** [comment]
> Should this use something similar to s:system in runtime/autoload/health/provider.vim, or

Yes, that.

**Comment by blueyed** [comment]
Do we want to move it to some central place then (utils?), or should a stripped-down version be copied?

**Comment by justinmk** [comment]
Either way is fine IMO. I think we should eventually add the behavior as a optional feature of `system()`.

**Comment by mqudsi** [comment]
Yeah, this was discussed for the clipboard stderr problems under Windows too, I believe.

**Comment by blueyed** [comment]
Should this be put into `runtime/autoload/provider.vim`?
I think `runtime/autoload/utils.vim` might be too unspecifc?  Maybe add `runtime/autoload/system.vim`?

**Comment by justinmk** [comment]
@blueyed why not add it as an optional parameter to `system()`?

**Comment by blueyed** [comment]
Would make it incompatible (with Vim), and should use a dict then probably to handle more optional things in the future.  And then it should probably also be suggested to Vim first (to avoid incompatibility).
I.e. it would be more involved, but likely worth it.
What do you think?

**Comment by justinmk** [comment]
> Would make it incompatible (with Vim), 

An extra parameter would not break compatibility. 

> And then it should probably also be suggested to Vim first (to avoid incompatibility).

We don't need to do double work for every single thing. We have a completely separate "job control" subsystem, we don't need to confer with Vim on enhancements to system().

**Comment by blueyed** [comment]
> we don't need to confer with Vim on enhancements to system().

I am thinking about users / plugin authors here: having a single interface would avoid problems that exist currently with regard to jobstart/job_start (where you have a different function name "at least").  Different arguments to `system` would be even worse.

**Comment by justinmk** [comment]
We already have extra feature for system(): list parameter invokes the job without shell, just like `jobstart()`. In any case adding a parameter to system() is much better than introducing vimscript utility functions, IMO.

More generally if conferring with Vim slows this decision down then we don't confer with Vim. Would rather make progress on this and eliminate that extra step.

**Comment by justinmk** [comment]
- Rearranged by https://github.com/neovim/neovim/commit/443cd04d5b00c57d791681065b2016cbe4228044
- Still want to enhance system() so that it has an interface like jobstart() and returns a structured result instead of a string. https://github.com/neovim/neovim/blob/497046466e4a969cefce5fc2b7992dde157aa1a5/runtime/autoload/health/provider.vim#L64
