### ISSUE TITLE
Writing file overwrites '[ and '] marks, despite :lockmarks/:keepmarks

### ISSUE THREAD

**Issue by kevinlawler** [neovim/neovim#8807]
This breaks autosaving functionality that many of us are using.

The `:wall` command and its family overwrite the '[ marks, but we want to avoid this using `:lockmarks` or similar. 

- `nvim --version`: NVIM v0.3.1
- Vim (version: 8.1 ) behaves differently? No
- Operating system/version: MacOS 10.13.6
- Terminal name/version: Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC file.txt<CR>
i abcdef<ESC>
yy
ppppppppppp
kk
`[
`]
:lockmarks wall<CR>
`[
`]
```

### Actual behaviour
Cursor moves to top of file since entire file was written and this overwrites the corresponding marks

### Expected behaviour
Cursor moves toward bottom of file where the last line was pasted

**Comment by justinmk** [comment]
see https://groups.google.com/d/msg/vim_dev/IOrR9_ZF6Jo/fIS5pBF-f9UJ

**Comment by jamessan** [comment]
I've been (slowly) working on a [fix](https://github.com/jamessan/vim/tree/lockmarks-change-mark) for this upstream as well as adding more [thorough testing](https://github.com/vim/vim/pull/2271) of how marks are affected by various actions.

**Comment by jamessan** [comment]
The upstream patches are 8.0.1269 (which has already been ported to neovim) and 8.1.2302.
