### ISSUE TITLE
Double-spaced (variable-spaced) option for hardcopy printing

### ISSUE THREAD

**Issue by kevinlawler** [neovim/neovim#8808]
There is no option to set line spacing for printing. Double-spacing at a minimum would be useful.
See discussion at https://groups.google.com/forum/#!topic/vim_use/jHy4irIUJPQ

- `nvim --version`: NVIM v0.3.1
- Vim (version: 8.1 ) behaves differently? No
- Operating system/version: MacOS 10.13.6
- Terminal name/version: Terminal
- `$TERM`: xterm-256color

**Comment by justinmk** [comment]
We'll merge that feature if/when Vim implements it.
