### ISSUE TITLE
Map <ESC> at different :terminal sub-modes?

### ISSUE THREAD

**Issue by marrs** [neovim/neovim#8810]
Forgive me if I've missed something in the implementation or documentation.

In terminal mode, I'd like to be able to hit `<ESC>` once to leave *terminal-insert mode*, and then `<ESC>` again to leave *terminal mode*.  From what I can tell, the suggested mapping `:tnoremap <Esc> <C-\><C-n>` will take you directly from *terminal-insert mode* to *normal mode*.

Is there something like `:tnnoremap` or `:tinoremap` to provide bindings in terminal sub-modes (normal and insert respectively), or some other functionality that I'm missing?

**Comment by justinmk** [comment]
There's only terminal-mode and normal-mode. I don't know what other mode you're referring to. In `:terminal`, when you hit `i`, that goes to terminal-mode (AKA "insert" mode). When you leave that mode you're in normal-mode.

**Comment by marrs** [comment]
So, in that case, I'd like to turn this into a feature request.

>  In :terminal, when you hit i, that goes to terminal-mode (AKA "insert" mode). When you leave that mode you're in normal-mode.

So what mode am I in after hitting `<C-\><C-n>`?  I would call *that* normal mode.

If I'm in terminal-mode (what I'd call *terminal-insert mode*) and I hit escape, `j` and `k` scroll through history; `/` searches through history, and so on.  I wouldn't call that *normal mode* behaviour.   That's what I was calling terminal-mode in my original post.  Even more so, normal-mode commands like `<C-W><C-W>` don't work until you hit `<C-\><C-n>`.  Now I'm in what *I* consider to be normal-mode, where `j` and `k` move up and down through the buffer lines, as I'd expect.

So what I was expecting to be able to do as a newbie to this feature was to be able to move freely between these modes.  That way I could do something like `ls` to see the directory contents, then `<ESC>12kyWpIcat ` to cat the filename listed 12 lines above my cursor.

Or maybe `<ESC>12kyW<ESC><C-W><C-l>` to use the word in my other buffer, to go back to my original query.

I hope that's clearer.

**Comment by jamessan** [comment]
> If I'm in terminal-mode (what I'd call terminal-insert mode) and I hit escape, j and k scroll through history; / searches through history, and so on.

That sounds like you're using a shell's vi-mode, which has nothing to do with whether you're using nvim's terminal or a standalone terminal.

Either you want to pass the `<Esc>` through to the shell or you don't.  If you do, then you can't map it in nvim because nvim has no idea what the state of the underlying application is.

**Comment by marrs** [comment]
Ah, I see. You're right, I am using the shell's vi-mode.  Sorry, I'd thought this was something that neovim was doing.
