### ISSUE TITLE
Make Terminal default mode insert 

### ISSUE THREAD

**Issue by rjshrjndrn** [neovim/neovim#8816]
- `nvim --version`: NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5

- Operating system/version: Linux work 4.17.11-arch1 #1 SMP PREEMPT Sun Jul 29 10:11:16 UTC 2018 x86_64 GNU/Linux

- Terminal name/version: zsh 
- `$TERM`: xterm-256color

Hi,

Simple question.

I have ` nnoremap <expr> <leader>t ":call Term()\<CR>"`
to call 
```
function! Term()
  exec winheight(0)/4."split" | terminal
endfunction
```
so that I'll get something like this. 
![nvim issue](https://user-images.githubusercontent.com/2563385/43683647-e26b9000-98ad-11e8-8aac-e1b35fc4dda3.png)

Everything works awesome, but have a small inconvenience. Whenever I am switching to the terminal mode it's in `normal mode`. Is there anyway, I can change the default behavior to `insert mode`?

**Comment by whitebyte** [comment]
Hi, AFAIK it should be easily accomplished by putting something like 
```
:au BufEnter * if &buftype == 'terminal' | :startinsert | endif
```
into your vimrc

**Comment by rjshrjndrn** [comment]
Hi,
Thank you for your awesome reply. But I already have 
```
if has('nvim')
    autocmd BufEnter,BufNew term://* startinsert
endif
```
The problem is, terminal is not in insert mode if I call the function.
If I jump back to the previous split and goes back terminal will be in insert mode. I am missing something here.

**Comment by justinmk** [comment]
see `:help :terminal`

**Comment by rjshrjndrn** [comment]
Got it. Thank you @justinmk @whitebyte .
```
if has('nvim')
    autocmd TermOpen term://* startinsert
endif
```

**Comment by Kethku** [comment]
For any using this as reference, this makes it hard to bind normal mode commands for some functions as vim will switch to insert mode mid command. My solution to this was to only switch to insert if the terminal wasn't focused before.

```
let g:previous_window = -1
function SmartInsert()
  if &buftype == 'terminal'
    if g:previous_window != winnr()
      startinsert
    endif
    let g:previous_window = winnr()
  else
    let g:previous_window = -1
  endif
endfunction

au BufEnter * call SmartInsert()
```

This way if the bufenter event is called after already having the terminal focused, the editor won't switch to insert mode.

**Comment by cup** [comment]
https://github.com/neovim/neovim/issues/2815

**Comment by cup** [comment]
For me just adding `startinsert` to `init.vim` did it.

**Comment by rjshrjndrn** [comment]
the question is not to start vim in insert mode, that in my openion is not antipattern, but to start terminal in insert mode.
