### ISSUE TITLE
:file command doesn't work.

### ISSUE THREAD

**Issue by purpleposeidon** [neovim/neovim#8817]
- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently? Yes.
- Operating system/version: Ubuntu, Linux 4.15.0-22-generic
- Terminal name/version: Konsole, 18.07.70
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC /some/long/path/asdf.txt
:file
```

### Actual behaviour
Apparently nothing.

### Expected behaviour
```
"/some/long/path/asdf.txt" [New file] --No lines in buffer--
```

**Comment by wsdjeg** [comment]
@purpleposeidon This is because neovim `set shortmess+=F` by default. if you want to see this, add `set shortmess-=F` into your config.

**Comment by justinmk** [comment]
Use `:file!` or ctrl-g or do as @wsdjeg said.

**Comment by justinmk** [comment]
Maybe we should change this. See https://github.com/neovim/neovim/issues/8873#issuecomment-414360145 .
