### ISSUE TITLE
jobs: merge output from stdout and stderr

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8823]
It does not appear to be possible to merge stdout and stderr currently from job output, without using a shell and redirection in there, is it?

Vim appears to support this by using `callback` instead of separate `out_cb` and `err_cb`:

```vim
let cmd = ["/usr/bin/bash", "-c", 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']

if exists('*jobstart')
  call jobstart(cmd, {
        \ 'on_stdout': {->execute('echom string(a:000)', 1)},
        \ 'on_stderr': {->execute('echom string(a:000)', 1)},
        \ })
elseif 0
  call job_start(cmd, {
        \ 'callback': {->execute('echom string(a:000)', 1)},
        \ })
else
  call job_start(cmd, {
        \ 'out_cb': {->execute('echom string(a:000)', 1)},
        \ 'err_cb': {->execute('echom string(a:000)', 1)},
        \ })
endif
```

Neovim will not display the output in order:
```
[105, ['1:stderr', ''], 'stderr']
[105, ['3:stderr', ''], 'stderr']
[105, ['2:stdout', ''], 'stdout']
[105, [''], 'stderr']
[105, [''], 'stdout']
```

**Comment by jamessan** [comment]
> Neovim will not display the output in order:

stderr typically isn't buffered, while stdout typically is.  Unless you change that, I don't think there can be any expectation of the order matching the order of your commands.

**Comment by jamessan** [comment]
> Vim appears to support this by using callback instead of separate out_cb and err_cb:

You can do the same thing with nvim by having `on_stdout` and `on_stderr` use the same callback which caches the data in the same place.  That doesn't change that nvim may receive data "out of order".

```viml
let cmd = ["/usr/bin/bash", "-c", 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']
let job = { 'output': [''] }

func! job.on_stdout(_job_id, data, _event) dict
  let self.output[-1] .= a:data[0]
  call extend(self.output, a:data[1:])
endfunc

let job.on_stderr = function(job.on_stdout)

call jobstart(cmd, job)
```

Changing `cmd` to

```viml
['stdbuf', '-e', 'L', '/usr/bin/bash', '-c', 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']
```
is one way to force the same buffering.

**Comment by blueyed** [comment]
> stderr typically isn't buffered, while stdout typically is. Unless you change that, I don't think there can be any expectation of the order matching the order of your commands.

Good point.
My use case is the output from `make`, which uses both stdout/stderr (https://github.com/neomake/neomake/issues/1884).  I assume/guess that `make` should handle this already to be unbuffered then though?

And using `stdbuf -e L` like you suggested (`let cmd = ['stdbuf', '-e', 'L', '/usr/bin/bash', '-c', 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']`) still displays `['1:stderr', '3:stderr', '2:stdout', '']` for me in your example, when using
```vim
func! job.on_exit(_job_id, data, _event) dict
  echom string(self.output)
endfunc
```

I am thinking about wrapping commands in Neomake with a shell, and using `( … ) 2>&1` around the cmd, but would rather like to avoid that.

**Comment by jamessan** [comment]
I've wanted finer grained control of the file descriptors available to jobs, e.g. creating some extra ones for different channels of communication (c.f., gnupg's various `--*-fd` switches), but have never gotten around to it.  Partly because I haven't thought of a nice way to expose that in the API and partly because of lack of time.

However, I do think it would be a useful middle-ground to at least have an easy way to express "use the same fd for stdout and stderr", without having to resort to the shell.

**Comment by blueyed** [comment]
What about doing it like with Vim, where `callback` is used to read any part of output?

**Comment by blueyed** [comment]
Would appreciate some feedback here how to address this best.
I still think having an additional `callback` job option that would get both stdout and stderr (in order) would be great to have here.

**Comment by bfredl** [comment]
I basically agree, but `callback` is not a very good name. I'd rather have `on_stdout` and a flag to reuse the same pipe for stderr (this is more consistent with pty jobs)

**Comment by blueyed** [comment]
Ok.  Maybe `on_stderr` could then have a special value to mean `pipe to stdout`?
Would we still be able to distinguish the source then? ("stdout" or "stderr", for the "name" in the callback)

OTOH how/why would this be different from using the same callback for `on_stderr` in Vimscript?

```vim
let cmd = ['stdbuf', '-e', 'L', '/usr/bin/bash', '-c', 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']

let job = { 'output': [''] }

func! job.on_stdout(_job_id, data, _event) dict
  let self.output[-1] .= a:data[0]
  call extend(self.output, a:data[1:])
endfunc

let job.on_stderr = function(job.on_stdout)

func! job.on_exit(_job_id, data, _event) dict
  echom string(self.output)
endfunc

call jobstart(cmd, job)
```

**Comment by justinmk** [comment]
> OTOH how/why would this be different from using the same callback for `on_stderr` in Vimscript?

Functionally it wouldn't be any different. It just avoids  boilerplate for the user.

> stderr typically isn't buffered, while stdout typically is. Unless you change that, I don't think there can be any expectation of the order matching the order of your commands.

Vim uses "nl" (line-buffered) mode by default (took awhile to deduce this from Vim's `:help channel`). Line-buffering is likely to add some semblance of "order" to interleaved stdout/stderr.

Maybe the main request here is line-buffering ?

**Comment by bfredl** [comment]
I presumed the use case was to use the same pipe (will make a difference for some situations) ? Otherwise you can just use the same callback already.

**Comment by blueyed** [comment]
Using the same callback does not fix it, so it's about using the same pipe then.
I've just wondered if the original source would be / could be made available still (in terms of a hack it would be like prefixing each output line with either "stdout:" or "stderr:" and using this then in the handler for the merged pipe).

As for Vim, using raw vs nl mode does not seem to make a difference there:
```
[['channel 76 closed', '2:stdout'], ['channel 76 closed', '1:stderr'], ['channel 76 closed',
'3:stderr']]
```
```
[['channel 71 closed', '2:stdout^@'], ['channel 71 closed', '1:stderr^@3:stderr^@']]
```

Using:
```vim
let cmd = ['stdbuf', '-eL', '-oL', '/usr/bin/bash', '-c', 'echo 1:stderr >&2; echo 2:stdout; echo 3:stderr >&2']

let job = { 'output': [''] }

if has('nvim')
  func! job.on_stdout(_job_id, data, _event) dict
    let self.output[-1] .= a:data[0]
    call extend(self.output, a:data[1:])
  endfunc

  let job.on_stderr = function(job.on_stdout)

  func! job.on_exit(_job_id, data, _event) dict
    echom string(self.output)
  endfunc

  call jobstart(cmd, job)
else
  let s:args = []
  func! s:callback(...)
    call add(s:args, a:000)
  endfunc
  func! s:exit_cb(...)
    echom string(s:args)
  endfunc
  let options = {
        \ 'callback': function('s:callback'),
        \ 'exit_cb': function('s:exit_cb'),
        \ }
  let options.mode = 'nl'
  call job_start(cmd, options)
endif
```

This also shows that Vim's `callback` also does not handle this "correctly" (in order) - unlike I've assumed initially.

Adding some `sleep` inbetween makes it work for both nvim and vim:
```vim
let cmds = ['echo 1:stderr >&2', 'sleep 0.1', 'echo 2:stdout', 'sleep 0.1', 'echo 3:stderr >&2']
let cmd = ['stdbuf', '-eL', '-oL', '/usr/bin/bash', '-c', join(cmds, '; ')]
```
(Vim is still flaky with `sleep 0.09`, but nvim works mostly with `sleep 0.08` already.  This could indicate that it is not that much / only related to bash / the process, but also how it is handled internally)

**Comment by justinmk** [comment]
> wondered if the original source would be / could be made available still (in terms of a hack it would be like prefixing each output line with either "stdout:" or "stderr:" and using this then in the handler for the merged pipe).

What is the advantage of having 1 pipe going to the same handler which then must switch on the source-type?

**Comment by bfredl** [comment]
This does not make any sense. By definition when using one pipe it is not possible to distinguish between stderr and stdout. It would work the same as pty output in this respect.

**Comment by blueyed** [comment]
> What is the advantage of having 1 pipe going to the same handler which then must switch on the source-type?

I've meant that it would be useful to know in general, i.e. errors vs. normal output.

Keep in mind that the underlying issue is that `make` will output its entering-directory messages on stderr, but other output is on stdout then, and the order there needs to be preserved.
It _might_ still be useful to see where it is coming from in general - i.e. Neomake has a feature to report unexpected output (when only using stdout normally - but that would not have to use the merged streams then).

> By definition when using one pipe it is not possible to distinguish between stderr and stdout. It would work the same as pty output in this respect.

I see.

It seems like using flags to setup redirection is the way to go there then.
I think only having `redirect_stderr_to_stdout` might be too inflexible when this needs to be extended later.  Maybe something like a dict (`redirect_pipes = {2: 1}`)?

**Comment by lewis6991** [comment]
This is already possible in Lua with `vim.uv.spawn`. Just set `stdio = { nil, pipe, pipe }`.
