### ISSUE TITLE
Neovim+Tmux rendering issues

### ISSUE THREAD

**Issue by Fetz** [neovim/neovim#8826]
- `nvim --version`: NVIM v0.3.2-30-g72ddbb6
- Vim (version: ) behaves differently? it handles better
- Operating system/version: Mac OS Sierra 10.12.6 (16G29)
- Terminal name/version: can replicate in Alacritty, ITerm2 and Hyper
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Can't replicate with -u NORC without using some plugins, but installing SpaceVim https://spacevim.org/quick-start-guide/. 
Using it without TMUX looks fine, but the moment I use nvim inside TMUX I start having rendering issues. Even more when the pane where nvim is, is zoomed (using tmux zoom to focus that pane only)

I tried to use different fonts, terminals, and I tried changing the options of iTerm2 regarding unicode widths.

### Actual behaviour
- status line doesn't get the right side
- resizing of splits leaves artifacts on the other splits
- lines when update (by tools like neomake to add a warning), doesn't update the full line showing the wrong text

### Expected behaviour
- status line to fit perfectly
- resizing should leave artifacts
- text to show the exact text

### Screenshoots

how the text should look
![screen shot 2018-08-08 at 12 31 43](https://user-images.githubusercontent.com/1071113/43834907-d53b44a0-9b07-11e8-9f9b-7d39559a0688.png)

how is looking
![screen shot 2018-08-08 at 12 31 17](https://user-images.githubusercontent.com/1071113/43834920-de0c718a-9b07-11e8-9699-5d8ade1947c8.png)

some other rendering issues
![screen shot 2018-08-08 at 12 33 28](https://user-images.githubusercontent.com/1071113/43834908-d5569976-9b07-11e8-8cf9-533762c7a398.png)
![screen shot 2018-08-08 at 12 36 22](https://user-images.githubusercontent.com/1071113/43834909-d56c37ea-9b07-11e8-9d00-25b6a3cb4401.png)

### Possible related issues
#8768
maybe #8322?

**Comment by wsdjeg** [comment]
SpaceVim author here, can you reproduce this isssue in vim8?

**Comment by Fetz** [comment]
Hi @wsdjeg, I have some issues with vim8 but not so obvious:

relative lines are shifted to the left
![screen shot 2018-08-08 at 13 54 01](https://user-images.githubusercontent.com/1071113/43838378-157b72d2-9b13-11e8-8690-2b18ec0d096e.png)

duplicated letter
![screen shot 2018-08-08 at 13 53 47](https://user-images.githubusercontent.com/1071113/43838468-53fe0f92-9b13-11e8-94ff-c8e853436d90.png)

statusline not fully correct but at least doesn't go to the next line
![screen shot 2018-08-08 at 14 00 02](https://user-images.githubusercontent.com/1071113/43838489-6510c23e-9b13-11e8-9aae-ff162a4ffd20.png)

the guide buffer (when the pane is zoomed in tmux) mode renders better in vim8
![screen shot 2018-08-08 at 14 02 32](https://user-images.githubusercontent.com/1071113/43838749-283a20a2-9b14-11e8-926d-af131a055b4f.png)

![screen shot 2018-08-08 at 14 02 51](https://user-images.githubusercontent.com/1071113/43838750-28545d64-9b14-11e8-864f-bce39fda5706.png)

**Comment by wsdjeg** [comment]
sorry, I can not reproduce this issue in temite which is the terminal I am using, and I start tmux via `tmux -2`. here is my tmux config, and it is simple:

```
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -s escape-time 0
set -g default-terminal "screen-256color"
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\ select-pane -l
```

**Comment by Fetz** [comment]
I used your tmux config and how your start tmux, but I still have the same issue :(.
I can try to use the same terminal that you use to see if I can replicate with that one. Is your terminal this one `thestinger/termite`?

By the way I'm using the latest (2 weeks ago) master version of tmux

**Comment by wsdjeg** [comment]
Yeah, it is `thestinger/termite`, my tmux version is 2.7

**Comment by Fetz** [comment]
@wsdjeg looks like the problem was not with nvim or with the terminal, but with tmux.
After installed the version 2.7 everything looks ok.

I update afterwards with the latest --HEAD of tmux and looks the problem is fixed.
So or was a bad installation or was something that they fixed on tmux.

Thanks @wsdjeg for you help. Closing the issue
