### ISSUE TITLE
E325 freeze neovim when using api

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#8840]
- `nvim --version`: v0.3.1-dev
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Actual behaviour
In terminal A:
```bash
nvim foo
```
In terminal B:
```bash
nvim bar
```
Then run (in terminal B):
```
:call nvim_command('e foo')
```
will freeze neovim unless pressing any key.
### Expected behaviour
neovim should display E325 error message.

**Comment by ipod825** [comment]
0.3.0 seems to work fine.

**Comment by jamessan** [comment]
This sounds like https://github.com/vim/vim/issues/3221.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8898 is related but it's not enough, there's a missing redraw, possibly from one of the UI refactors in the last few weeks.

Thanks for the simple repro steps!
