### ISSUE TITLE
What's wrong with nvim-qt.exe?

### ISSUE THREAD

**Issue by hscnhs** [neovim/neovim#8849]
- `nvim --version`:NVIM v0.3.2-77-g2b9fc9a13
- Vim (version: ) behaves differently? No
- Operating system/version: windows10
- Terminal name/version: everyone
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
![snipaste_2018-08-11_08-34-14](https://user-images.githubusercontent.com/24327531/43986308-b304903a-9d41-11e8-9491-f606384324c6.png)

### Expected behaviour

nvim-qt cant't read file, when call :wq, it says no name

**Comment by janlazo** [comment]
You didn't pass a file and your steps to reproduce the problem is using `nvim`, not `nvim-qt`. I don't see `:e myfile.txt` in your steps so it looks like a usage issue to me. You need to pass `--` to pass `nvim` command-line arguments through `nvim-qt`.

**Comment by hscnhs** [comment]
ok, everything about nvim.exe is fine

**Comment by justinmk** [comment]
This is a really vague report, I'm going to assume it's the same as https://github.com/equalsraf/neovim-qt/issues/423
