### ISSUE TITLE
API/UI: emit scroll event

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8854]
It's not possible to detect window scroll right now, I've request vim to have scroll autocmd, but no response.

Since neovim have buffer update events, maybe it could be easier to have window scroll events for clients.

Scroll event could be used for improve performance, for example, we can add highlight only to visible lines and update the highlight on scroll.

**Comment by bfredl** [comment]
just merged `win_viewport` event contains the topline (among other things), so should be possible to detect scrolling.
