### ISSUE TITLE
Normalize path - remove // ...

### ISSUE THREAD

**Issue by PaperMountainStudio** [neovim/neovim#8862]
- `nvim --version`:
NVIM v0.3.0
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.3.0/build/config -I/builddir/build/BUILD/neovim-0.3.0/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.0/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.0/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui 
- vim behaves similarly
- Operating system/version: Fedora/28
- Terminal name/version: sakura/3.5
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e ~/.config//nvim/init.vim
```

### Actual behaviour
on status-line: .config//nvim/init.vim

### Expected behaviour
on status-line: .config/nvim/init.vim

By POSIX multiple slashes (/) in path are ignored, so normalize the path before opening.

**Comment by justinmk** [comment]
'statusline' is configurable, you could use `simplify()` and friends. But I agree this would be a nice improvement.

> By POSIX multiple slashes (/) in path are ignored, so normalize the path before opening

Is that the case for BeOs, Amiga, etc.? Maybe that's why Vim doesn't collapse slashes. But it's probably OK. 

Patch welcome!

**Comment by dread-uo** [comment]
I'd like to take on this one! May I?

**Comment by justinmk** [comment]
@dread-uo see https://github.com/neovim/neovim/pull/8868 , maybe ask @bauerjoseph  what their progress is.

**Comment by bauerjoseph** [comment]
Go for it bud, I'm not making much progress.

**Comment by Xynkt99** [comment]
can i try this one ??

**Comment by gbrunofranco** [comment]
I can't reproduce this bug at all, no matter how I start nvim nothing appears on the statusline. 
What's your setup?

This is my `nvim --version`:
NVIM v0.3.1
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.3.1/build/config -I/builddir/build/BUILD/neovim-0.3.1/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.1/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.1/build/include
Compiled by mockbuild

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by justinmk** [comment]
@ZyX-I Thanks, can't believe I forgot about UNC paths.

Closing this as `wontfix`.
