### ISSUE TITLE
nvim_buf_detach throw error with unloaded buffer

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#8865]
- `nvim --version`:  v0.3.2-286-g374572612
- Vim (version: ) behaves differently? no
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Actual behaviour

```
2018-08-16T18:05:39.591 DEBUG (pid:71470) [plugin] - Autocmd: [ 'BufUnload', 11 ]
2018-08-16T18:05:39.660 ERROR (pid:71470) [server] - unhandledRejection  Promise {
  <rejected> Error: nvim_buf_detach: Invalid buffer id
    at transport.request (/Users/chemzqm/vim-dev/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/Users/chemzqm/vim-dev/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:107:13)
    at DecodeStream.Transport.decodeStream.on (/Users/chemzqm/vim-dev/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:41:18)
    at DecodeStream.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
```

### Expected behaviour

It should not thrown for unloaded buffer, but just return false value according to documentation `:h nvim_buf_detach()`.

**Comment by justinmk** [comment]
`find_buffer_by_handle` sets the Error. I guess `nvim_buf_detach ` should use `handle_get_buffer` directly instead of calling `find_buffer_by_handle`.

**Comment by bfredl** [comment]
`find_buffer_by_handle` should handle unloaded buffer just fine. Are you sure the buffer wasn't already wiped at the point the handler was executed?

Also, nvim_buf_detach() shouldn't be needed to be called when buffer is unloaded (if I understand the log correctly), this happens automatically.

**Comment by chemzqm** [comment]
> Also, nvim_buf_detach() shouldn't be needed to be called when buffer is unloaded (if I understand the log correctly), this happens automatically.

I just unbind the event listeners when the buffer is unload to prevent the listeners called twice when buffer with same buffer number loaded again and node-client calls `nvim_buf_detach` automatically.

**Comment by bfredl** [comment]
> I just unbind the event listeners when the buffer is unload to prevent the listeners called twice when buffer with same buffer number loaded again and node-client calls nvim_buf_detach automatically.

This sounds like node-client is not prepared for how nvim manages subscription lifetimes. Instead, maybe node-client should drop the existing batch of listeners on `nvim_buf_detach_event`. Then the plugin can just rebind as usual when it sees a buffer reloaded.

**Comment by chemzqm** [comment]
> node-client should drop the existing batch of listeners 

It does drop the listeners on detach event, but it doesn't change internal `isAttach` property, I can fix that.

**Comment by justinmk** [comment]
Assuming this will be addressed by https://github.com/neovim/node-client/pull/93
