### ISSUE TITLE
:terminal leads to have a blank first character, no matter the character.

### ISSUE THREAD

**Issue by miguelsaldivar** [neovim/neovim#8870]
- `nvim --version`: v0.3.0
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
Simply typing `:terminal` then typing leads to this error.
```
nvim -u NORC

```

### Actual behaviour
No matter the command, the first character always seems to be "blank". Blank in quotes because, the command is still there, and can be executed. 
### Expected behaviour
All characters to show up within the buffer.

**Comment by bfredl** [comment]
v0.3.0 is not the latest version. What about v0.3.1 ? Also it might be useful to know what shell you use.

**Comment by miguelsaldivar** [comment]
I use `zsh`, I just thought it was very odd because my work machine is setup almost entirely the same (Only difference is hardware)., and I don't have issues. I can update when I get home later.

**Comment by justinmk** [comment]
@miguelsaldivar did 0.3.1 or the 0.3.2 pre-release change anything? https://github.com/neovim/neovim/releases

**Comment by miguelsaldivar** [comment]
Hmmm, seems like it was an issue with the `zsh` theme I was using.
