### ISSUE TITLE
[RFE] system-wide configuration file on Unix (with merging-in options)

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#8871]
- `nvim --version`:

    NVIM v0.3.2-dev
    Build type: RelWithDebInfo
    Lua 5.3
    Compilation: /usr/bin/cc -Wconversion -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic
    -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla
    -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds
    -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
    -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM
    -I/home/abuild/rpmbuild/BUILD/neovim-0.3.1+git.1534330940.b5cfac089/build/config
    -I/home/abuild/rpmbuild/BUILD/neovim-0.3.1+git.1534330940.b5cfac089/src -I/usr/include
    -I/home/abuild/rpmbuild/BUILD/neovim-0.3.1+git.1534330940.b5cfac089/build/src/nvim/auto
    -I/home/abuild/rpmbuild/BUILD/neovim-0.3.1+git.1534330940.b5cfac089/build/include
     
     Features: +acl +iconv +jemalloc +tui 
     See ":help feature-compile"
     
     systémový vimrc soubor: "$VIM/sysinit.vim"
     implicitní hodnota $VIM:"/usr/share/nvim"
    
    Run :checkhealth for more info

- Vim (version: ) behaves differently?

No, exactly the same problem.

- Operating system/version:

Linux, openSUSE Tumbleweed 20180812, but the issue is non-distro specific, applies to any Unix-like system (perhaps Windows as well)

- Terminal name/version: gnome-terminal, but that's really unnecessary
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Well, that's exactly the point. Many Unix utilities (``mutt`` is one nice example) uses two-tier system of configuration files. To quote [MuttGuide](https://gitlab.com/muttmua/mutt/wikis/MuttGuide/Syntax):

    Mutt reads its configuration by default 1st from a system-wide
    config-file ("/etc/Muttrc"), which normally controls system settings and
    provides viable default personal settings for all users, then it reads
    the personal config file ("~/.muttrc" or "~/.mutt/muttrc"). This way the
    personal settings override system settings as needed.

I would love to see the same behaviour for neovim. Currently ``:he vimrc`` repeats couple of times something in style:

    The files are searched in the order specified above and only the first
    one that is found is read.

Which is true, but exactly the behaviour which I don't like. **ALL** configuration files (in the given order, and the list shouldn't be too long, configurable during the compile time preferably) should be read in the given order and their values incrementally merged.

### Actual behaviour

See above, only one file is considered.

### Expected behaviour

All files should be read, and values merged.

I would think that the bug like this should have been already filed here, but I really couldn't find. There was a lot of discussion about location of files (XDG specification), but not about this merging values. Or at least I wasn't able to find one.

**Comment by fmoralesc** [comment]
The system wide vimrc *is* read, if present. nvim doesn't provide one by default, unlike vim.

Try creating an empty `$VIM/sysinit.vim` (in linux, this is /usr/share/nvim/sysinit.vim`, and run nvim. If you have a personal init.vim file, the first entries in the output of `:scriptnames` should be something like

```
  1: /usr/share/nvim/sysinit.vim
  2: ~/.config/nvim/init.vim
```

**Comment by mcepl** [comment]
And is it only ``/usr/share/nvim/sysinit.vim`` or would ``/etc/xdg/nvim/sysinit.vim`` work as well?

**Comment by janlazo** [comment]
With the resolution of https://github.com/vim/vim/issues/2042, this is a `wontfix` and I hope I don't have to add `alias nvim="$(command -v nvim) -Nu $HOME/.config/nvim/init.vim"` in my `~/.bashrc` as I do with Vim.

**Comment by fmoralesc** [comment]
@mcepl If the local file sets the same settings as the system one, they should override them or extend them, depending of what the script is doing. Conceptually, it is the same as having the `set ` commands done in sequence in the command line.

The location of `sysinit.vim` will depend on the value of `$VIM`, as you can see in the output of `:version`. I'm not sure if the system file should follow the xdg spec.

**Comment by fmoralesc** [comment]
At any rate, it seems like this is a problem with the documentation more than with nvim's behaviour.

**Comment by jamessan** [comment]
> With the resolution of vim/vim#2042, this is a wontfix

Vim's problem is completely different.  The issue there is that _some_ of the defaults are provided by defaults.vim, rather than being builtin.  The "defaults" in defaults.vim are loaded after the system-wide config, since they are only loaded if the user doesn't have a vimrc.  In effect, this means that although Vim supports a system-wide configuration file, it is completely ignored in terms of how that interacts with the second-tier defaults.

Since nvim's defaults are all builtin, this is a non-issue.  The correct precedence is still followed, where the system-wide configuration is overridden by the user's configuration (and plugins).

**Comment by jamessan** [comment]
In terms of the original issue, config files (like all vim scripts) are just a series of commands.  Unless there is an explicit guard to stop processing a file (as is typical in plugins), then files sourced later will override overlapping settings from files sourced earlier.

So, yes, settings are merged.

**Comment by jamessan** [comment]
> The files are searched in the order specified above and only the first one that is found is read.

To @fmoralesc's point, this is leftover from Vim's help since Vim will look for the _user's_ vimc in multiple places:

```
	Places for your personal initializations:
		Unix		$HOME/.vimrc or $HOME/.vim/vimrc
		OS/2		$HOME/.vimrc, $HOME/vimfiles/vimrc
				or $VIM/.vimrc (or _vimrc)
		MS-Windows	$HOME/_vimrc, $HOME/vimfiles/vimrc
				or $VIM/_vimrc
		Amiga		s:.vimrc, home:.vimrc, home:vimfiles:vimrc
				or $VIM/.vimrc
```

Vim uses the first _user_ vimrc that it finds and ignores the rest.  Neovim standardized on XDG locations, so there is only _one_ location.

**Comment by mcepl** [comment]
Thank you very much your help.

**Comment by mcepl** [comment]
@jamessan sorry, one last question: I understand that the location of ``sysinit.vim`` is given by the ``$VIM`` variable, but it defaults to something, doesn't it? Where is this default location configured? Could I set it to something else than a directory in ``/usr/share/``? That sounds like a bad location for the configuration file. Could I set it somewhere to ``/etc``?

**Comment by mcepl** [comment]
Thanks, I did the same now.

**Comment by jdhao** [comment]
@mcepl , according to `:h sysinit.vim`:

> The system vimrc file is read for initializations.  If                                                                                                                                                                                                    
        nvim/sysinit.vim file exists in one of $XDG_CONFIG_DIRS, it will be     
        used.  Otherwise, the system vimrc file is used. The path of this file  
        is shown with the ":version" command.  Mostly it's "$VIM/sysinit.vim"

Since `XDG_CONFIG_DIRS` defaults to `/etc/xdg`, it means that `/etc/xdg/nvim/sysinit.vim` will be used as the default system config if it exists.  `$VIM/sysinit.vim` will only be used if `/etc/xdg/nvim/sysinit.vim` does not exist.

If you install Neovim to a non-standard location, for example `/opt/tools/nvim`, `$VIM` will be `/opt/tools/nvim/share/nvim`.
