### ISSUE TITLE
Suggestion: Make 'cursorline' take care of the visual indent generated by 'breakindent'?

### ISSUE THREAD

**Issue by slmjkdbtl** [neovim/neovim#8874]
- `nvim --version`: v0.3.1
- Vim (version: 8.1) behaves differently? no
- Operating system/version: macOS High Sierra 10.13.6
- Terminal name/version: iTerm 2.3.0
- `$TERM`: xterm-256color

(I'm not sure if I should post this here or the vim's issue board, sorry if it's the wrong place)
![1](https://user-images.githubusercontent.com/9929523/44315359-6ca50500-a3f1-11e8-8ccc-89e74209151a.jpg)

Now is has this hideous gap between the number column and the text visually indented by `'breakindent'`, hoping the visual indents could be rendered with the cursorline color

**Comment by justinmk** [comment]
Hmm. Yes, you might want to send that request to https://github.com/vim/vim/ . Better that they spend the time to fix it.
