### ISSUE TITLE
Rendering issue with tmux and vim-airline

### ISSUE THREAD

**Issue by purejoy** [neovim/neovim#8890]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? 8.0.1283
- Operating system/version: MacOS 10.13.6
- Terminal name/version: iterm2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
1. Install vim-airline and vim-airline-themes via vim-plug.
2. Add let g:airline_powerline_fonts = 1 to init.vim then randomly select an airline theme.
3. Open iterm2 with Tmux enabled, then launch nvim.

### Actual behaviour
![2018-08-23 3 19 29](https://user-images.githubusercontent.com/3711998/44513304-9743d600-a6ef-11e8-916a-ac6bdfeb6c37.png)
![2018-08-23 3 20 23](https://user-images.githubusercontent.com/3711998/44513323-9f9c1100-a6ef-11e8-9ac6-38ded8a19485.png)
![2018-08-23 3 20 39](https://user-images.githubusercontent.com/3711998/44513526-281ab180-a6f0-11e8-8cfd-785f415fe7e2.png)
![2018-08-23 3 20 58](https://user-images.githubusercontent.com/3711998/44513547-31a41980-a6f0-11e8-9422-19b29196d61d.png)
### Expected behaviour
![2018-08-23 4 19 30](https://user-images.githubusercontent.com/3711998/44513615-6a43f300-a6f0-11e8-92e2-34dad62d9688.png)
![2018-08-23 4 19 53](https://user-images.githubusercontent.com/3711998/44513651-7def5980-a6f0-11e8-870c-1f02bedce5f6.png)

There is no issue with Tmux disabled.

**Comment by purejoy** [comment]
Tmux built with utf8proc enabled caused this issue.
Maybe I should submit this issue to Tmux team.

**Comment by justinmk** [comment]
Related: https://github.com/neovim/neovim/issues/6313
