### ISSUE TITLE
custom filetypes detection is different between vim and nvim

### ISSUE THREAD

**Issue by jeanguyomarch** [neovim/neovim#8900]
- `nvim --version`: NVIM v0.3.2-2026-gc0157e8fe
- Vim (version: 8.0) behaves differently? **yes**
- Operating system/version: Ubuntu 18.04.1 LTS
- Terminal name/version: terminology 1.2.99
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Not applicable.

### Actual behaviour

I've written a syntax coloration plugin at a non-standard location in my filesystem:

```
/home/xxx/src/config/vim
├── ftdetect
│   └── kat.vim
└── syntax
    └── kat.vim
``` 

I use the minimal vim init script (`my_init.vim`):

```vim
filetype plugin indent on
syntax on
set rtp+=/home/xxx/src/config/vim
```

Then run the following command:

```bash
nvim -u my_init.vim my.kat
```

The file is displayed without coloration, which seems to be a problem. The result of

```vim
set filetype?
```

is:

```
  filetype=
```

If I run:

```vim
set filetype=kat
```

then the file is properly colorized. It seems that the `ftdetect/kat.vim` file is never sourced, which seems to be confirmed after running `nvim` with the `-V` option.

If I run the same command than above with `vim` instead of `nvim` (`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)`), then the file is properly colorized when it is initially loaded, as I would expect.

### Expected behaviour

I expected the file to be colorized automatically on load, like what `vim` does.

**Comment by janlazo** [comment]
Do you have a custom `filetype.vim`?

**Comment by jeanguyomarch** [comment]
I don't think so. I don't modify the files installed by `vim`/`nvim`. How could I be sure of that?

**Comment by janlazo** [comment]
For `filetype.vim`, you can check `:edit $VIMRUNTIME/filetype.vim`. Check if it's global variable, `g:did_load_filetypes` is set.

What are the contents of `ftdetect/kat.vim`?

**Comment by janlazo** [comment]
Example of an ftdetect file is https://github.com/janlazo/dotvim8/blob/master/ftdetect/ftdetect.vim. `ftdetect/*.vim` files are sourced and are expected to have an autocmd to match a filename glob to a filetype but there's no stopping a user from dumping all of their autocmds in one file like what I have.

**Comment by jamessan** [comment]
> filetype plugin indent on
> syntax on
> set rtp+=/home/xxx/src/config/vim

This is the wrong order.  You're running commands that will enable filetype detection before you're added your custom ftdetect script to the runtime path.  If you change `&rtp` first, then it should work since nvim will know to load `ftdetect/kat.vim`.

**Comment by jeanguyomarch** [comment]
@jamessan thanks a lot for your help; moving the `set rtp` was indeed the solution.
I was just puzzled by the behavior difference between vim and nvim.

**Comment by huangc28** [comment]
> For `filetype.vim`, you can check `:edit $VIMRUNTIME/filetype.vim`. Check if it's global variable, `g:did_load_filetypes`, is set.
> 
> What are the contents of `ftdetect/kat.vim`?

Get the right path of `filetype.vim` solved my problem!
