### ISSUE TITLE
Cannot enter insert mode using autocmd while entering terminal buffer

### ISSUE THREAD

**Issue by blahgeek** [neovim/neovim#8905]
- `nvim --version`:

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? N/A
- Operating system/version: macOS 10.13.6
- Terminal name/version: iTerm2 3.2

### Steps to reproduce using `nvim -u NORC`

```
:autocmd BufWinEnter,WinEnter,BufEnter term://* startinsert
:e term://bash
<C-\><C-N>:new term://bash
exit  # exit bash
<Enter>  # confirm "Process exited"
```

### Actual behaviour

Enter the first terminal buffer in normal mode

### Expected behaviour

Enter the first terminal buffer in insertion mode

**Comment by justinmk** [comment]
Please search existing issues.

**Comment by blahgeek** [comment]
@justinmk Thanks for your response, but could you please give me a link to such existing issues? I've read #8816, #7678, #6144, none of them seems related. My issue here is that, with `au BufWinEnter,WinEnter,BufEnter term://* startinsert` set, a terminal buffer would not enter insertion mode if it's followed by exiting another terminal buffer.

**Comment by blahgeek** [comment]
Update: It works if I type `<C-\><C-n>:q<CR>` to exit the finished terminal pane, but not if I press any other keys to exit it

**Comment by ggustafsson** [comment]
I am also experiencing issues with this. If I have two split terminal windows open and exit one of the programs then the autocmd rule is not triggered when focus is moved to the other split window. It is however triggered when closed outside of the program as @blahgeek mentioned.

Pretty niche issue but it does indeed seem to be real. Or are we just missing a specific autocmd group? I've tried a bunch of different combos of BufEnter, BufWinEnter, TermOpen, TermEnter, etc and it is all the same.
