### ISSUE TITLE
"Error detected while processing modelines" when opening text file

### ISSUE THREAD

**Issue by fekir** [neovim/neovim#8906]
- `nvim --version (appimage)`: v0.3.2-356-gc0157e8fe
NVIM v0.3.2-356-gc0157e8fe
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-0cc076f3-c731-4221-a5af-666170db7372

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

- `nvim --version (package manager)`: v0.2.2 (other info omitted for brevity since reproducible also with appimage)
- Vim (version: 8.1.229) behaves differently? Yes
- Operating system/version: Debian testing
- Terminal name/version: tried on different terminal emulator, can also reproduce on xterm
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim.appimage -u NORC test.txt
```

### Actual behaviour
When opening the test file [test.txt](https://github.com/neovim/neovim/files/2320579/test.txt) (smallest test file i was able to create in order to trigger the behavior) , following message appears on screen:
````
Error detected while processing modelines:
line    1:
E518: Unknown option: a
Press ENTER or type command to continue
````

### Expected behavior
No error message

**Comment by justinmk** [comment]
`ex:` is a synonym for `vi:` and `vim:`, as far as modelines are concerned. 

modelines are kind of dumb. If you don't want modelines enabled, add this to your vimrc:

    :set modeline

Or do it only for text files using an ftplugin (though I sometimes use modelines for text files anyway).
Or just ignore the error.

**Comment by fekir** [comment]
Hi @justinmk, thank you for your feedback, did not know modelines, learned something new.

Wouldn't it make sense to disable such mode by default (just checked, it's disabled in vim)

My original file has a line similar to (indented with tab):
````
	Here is some text, for ex: Lorem ipsum
````

But even with `vi` and `vim` I think it's a confusing behavior, if I have a readme with something like
````
	enable colors in vim: bla bla bla
````
it will trigger the same error/warning.

I also read on http://vim.wikia.com/wiki/Modeline_magic that for security reason modeline are disabled by default.
I think that those are two good reasons for changing the default behavior, I already saw some discussion about saner default settings, but I did not see anything about modeline.
Or has it already been discussed?

**Comment by justinmk** [comment]
> just checked, it's disabled in vim

No, it's disable in _vi_. Use the `-N` flag of vim to test vim, otherwise it is vi-compatible.

    vim -u NORC -N

> for security reason modeline are disabled 

That's done by the distros but not by Vim. See `:help 'modeline'` in Vim, which of course will be confusing for anyone using their distro's Vim-defaults flavor.

I don't feel strongly about modelines and would also love to remove the `'exrc'` option. But modelines are rather commonly used, and any [reported vulnerabilities](https://www.reddit.com/r/vim/comments/5fizr0/cve20161248_may_result_in_the_execution_of/) have been fixed.

Not to mention, Vim is full of security holes, it even has `test_*` functions (not present in Nvim) which can undetectably change the state of the program.

**Comment by fekir** [comment]
>> just checked, it's disabled in vim
>
>No, it's disable in _vi_. Use the `-N` flag of vim to test vim, otherwise it is vi-compatible.
>
>    vim -u NORC -N
>
>> for security reason modeline are disabled
>
>That's done by the distros but not by Vim. See `:help 'modeline'` in Vim, which of course will be confusing for anyone using their distro's Vim-defaults flavor.

Thank you for the clarification, tested with `-N` and I get the behavior you described.
Seem to me that then the page I linked is out of date then.

>I don't feel strongly about modelines and would also love to remove the `'exrc'` option. But modelines are rather commonly used, and any [reported vulnerabilities](https://www.reddit.com/r/vim/comments/5fizr0/cve20161248_may_result_in_the_execution_of/) have been fixed.

I do not know modelines enough, and the limitation it has.
At first I thought you where able to execute any command and that's why distribution disabled it by default.

>Not to mention, Vim is full of security holes, it even has `test_*` functions (not present in Nvim) which can undetectably change the state of the program.

Gasp!
