### ISSUE TITLE
index.txt documentation link broken

### ISSUE THREAD

**Issue by HaleTom** [neovim/neovim#8907]
On the page:
https://neovim.io/doc/user/index.html

The link for:
`|index.txt|	alphabetical index of all commands`

is `404`:

https://neovim.io/doc/user/vimindex.html

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/blob/c0157e8fe0b9b25d9004b3f10a0ef5d33e4ff027/runtime/doc/makehtml.awk#L9  explains why it's "vimindex".

https://github.com/neovim/neovim/pull/8908 should fix this, though it make take a few hours to see it on the website.
