### ISSUE TITLE
[ci] Appveyor: ignore/fix MINGW_64-gcov job

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8911]
It appears to fail always, due to a lot of coverage issues:

> profiling:C:\projects\neovim\build\src\nvim/CMakeFiles\nvim.dir\api\buffer.c.gcda:Data file mismatch - some data files may have been concurrently updated without locking support
> profiling:C:\projects\neovim\build\src\nvim/CMakeFiles\nvim.dir\api\private\dispatch.c.gcda:Merge mismatch for function 67

It has been allowed to fail in 2017 already by @jamessan:
https://github.com/neovim/neovim/commit/9a9d9a187f5f78600e9fe41e25c2846403a8ae97

It should either get fixed quickly, or get disabled completely - it takes a lot of time, and causes AppVeyor builds to queue up more than necessary.

**Comment by justinmk** [comment]
"gcda:Data file mismatch" is a common gcov problem that appears with multithreaded or async codepaths, IIRC. Not sure why it fails consistently on appveyor. @jamessan added it to increase coverage, but if it never succeeds then that doesn't help. +1 for disabling it for now.
