### ISSUE TITLE
test_override: support overriding starting / v:starting

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#8923]
I want to test something with regard to the OptionSet autocommands, but those are only emitted when not starting anymore.

The tests use Vader, which is invoked via `+Vader` from the command line, and starting is only set to 0 afterwards.

I believe `test_override('starting', 1)` could be supported by Neovim, but another option might be to have `v:starting` reflect the `starting` global, and allow for setting it manually.

The workaround is to trigger `OptionSet` manually in the tests using `doautocmd`, but it would be nice if that wasn't necessary.

**Comment by justinmk** [comment]
I'm really uncomfortable about `test_override()`. If invariants are made variant by `test_override()`, what was the point of the invariants? Might as well make `v:starting` writable.

> The workaround is to trigger OptionSet manually in the tests using doautocmd, but it would be nice if that wasn't necessary

Can't the test framework start a new `nvim` instance for this type of test? Then it tests the actual conditions, instead of fake conditions.

**Comment by blueyed** [comment]
> Might as well make `v:starting` writable.

Would that be something to consider?
Should I suggest this upstream for Vim itself?

> Can't the test framework start a new `nvim` instance for this type of test? Then it tests the actual conditions, instead of fake conditions.

It's not trivial, at least with some simple test runner like Vader, and when testing things manually etc.

I've done something in this regard for deoplete (https://github.com/Shougo/deoplete.nvim/pull/807, based on the pytest fixture used with python-neovim itself) though, and really liked to not have all kind of hacks with feedkeys etc. But that is basically due to internals like the above, where commands from `-c`/`+` are handled in a special way, and the main loop in general which handles other types of autocommands only when run interactively.
Having to run a `nvim` instance also makes it more complicated to test with both Neovim and Vim, but it could be done with an extra layer that provides an API for both Vim and Neovim (using the `--remote-server` feature then for Vim (https://github.com/davidhalter/jedi-vim/pull/861/files#diff-89b422673bd1516bbc12e76db05c04ee).

**Comment by justinmk** [comment]
> Would that be something to consider?

Invariants are nice to have, so I also wouldn't like that solution :)

Testing some conditions is difficult but that's the job of the test framework. We've adhered to that in the Nvim Lua tests, avoiding the `test_` magic functions by provoking or faking the necessary conditions.
