### ISSUE TITLE
nvim-qt opens in terminal instead of stand-alone window

### ISSUE THREAD

**Issue by SalahuddinAsh** [neovim/neovim#8938]
- `nvim --version`:

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -
D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter
 -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/bu
ild/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-H
JnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Operating system/version:
`Ubuntu 16.04`

- `$TERM`:
`xterm`

### Actual behaviour
nvim-qt opens in terminal

### Expected behaviour
nvim-qt opens in stand-alone window (as it does in Windows)

**Comment by justinmk** [comment]
No idea what this means. It sounds like you're running `nvim.exe`, so I'll assume that since you didn't give steps to reproduce. You need to run `nvim-qt.exe` instead.

**Comment by SalahuddinAsh** [comment]
@justinmk
I'm using Ubuntu 16.04
I want to run nvim-qt as a stand-alone app. I don't want to run it in terminal.
When I launch nvim in Ubuntu, it opens a terminal window and run inside it.
Is there a way to run nvim-qt in Ubuntu?
This is what I'm asking about.

**Comment by justinmk** [comment]
Sounds like a configuration question, maybe the `.desktop` file that nvim-qt ships with, or is packaged with by your distro, needs to be adjusted.
