### ISSUE TITLE
AppImage: set process name to "nvim"

### ISSUE THREAD

**Issue by niklaas** [neovim/neovim#8947]
This is just a suggestion.

Having issues with plugin `vim-tmux-navigator`, I realised that the process name of NVim isn't really informative when using the AppImage. It is simply `AppRun`. Probably, this should be improved to better keep track of NVim in `ps`, `top` et. al.

See the conversation at https://github.com/christoomey/vim-tmux-navigator/issues/213#issuecomment-411638338 for reference.

**Comment by jamessan** [comment]
Does `env TARGET_APPIMAGE=nvim nvim.appimage` change the process name?  If I'm understanding the [PR](https://github.com/AppImage/AppImageKit/pull/764) correctly, that should work if libbsd is installed.

**Comment by asavill** [comment]
I would love this to be implemented soon, I need my bleeding edge Nvim working with tmux-navigator.

**Comment by justinmk** [comment]
If I run the appimage like this:

```
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
```

and then do this:

    ps -e -o pidns,pid,rss,vsz,command

I see `nvim.appimage` in the process list. Also with `ps -e` and `ps aux` and `htop`.

If this is still an issue then we need clear steps to reproduce.
