### ISSUE TITLE
error in saving shada file

### ISSUE THREAD

**Issue by liushapku** [neovim/neovim#8956]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? vim does not have this feature
- Operating system/version: ubuntu/14.04
- Terminal name/version: gnome 3.12.3
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:e $HOME/.local/share/nvim/shada/main.shada
:w
```

### Actual behaviour
error detected

    Error detected while processing function 
    shada#get_binstrings[1]..shada#strings_to_sd[9]..
    <SNR>184_shada_convert_strings[87]..
    <SNR>184_shada_eval[1]..msgpack#eval:
    line   65: 
    E716: Key not present in Dictionary: "py    <----- the key may differ
    E116: Invalid arguments for function add
    Error detected while processing BufWriteCmd Auto commands for "*.shada": 
    E686: Argument of writefile() must be a List

The string after "Key not present in dictionary" may differ depending on what is currently in your shada"

### Expected behaviour
finish writing since no change is made

### Analyzing
The error was found when I followed Hotschke's suggesting to solve a [problem](https://vi.stackexchange.com/questions/17227/how-to-remove-entries-from-voldfiles-list-in-neovim)

The code surrounding line 65 of `runtime/autoload/msgpack#eval` reads

    elseif s =~# '-\?\%(inf\|nan\)'
      if s[0] is# '-'
        call add(expr, '-')
        let s = s[1:]
      endif
      call add(expr, s:MSGPACK_SPECIAL_OBJECTS[s[0:2]])
      let s = s[3:]

I think it is because the regex is not correct `'-\?\%(inf\|nan\)'`. For my case, I echoed `s` just before the call to `add(expr...)` and found that `s="py3 print(sys.version_info)"` which matches the regex but should have not.

I changed the regex to `^-\?\(inf\|nan\|)` and the error is gone.

The regex is in its present form since the time the vim script was added to the project.

**Comment by jamessan** [comment]
> I changed the regex to `^-\?\(inf\|nan\|)` and the error is gone.

Shouldn't that be `^-\?\(inf\|nan\)$`?  @ZyX-I, do you have time to handle this?
