### ISSUE TITLE
Allow shada to be a symlink

### ISSUE THREAD

**Issue by rightaway** [neovim/neovim#8957]
When I move my shada file to a different location and have ~/.local/share/nvim/shada/main.shada be a symlink to that location, neovim overwrites the symlink with a file. It should respect symlinks and update the file referred to by the symlink rather than overwriting the symlink itself.

**Comment by justinmk** [comment]
duplicate of #1674

> Vim intentionally doesn't follow symlinks for .viminfo, because that can
be used for a symlink attack, a security issue.

You can work around this by simply setting the "n" flag of 'shada' option.

**Comment by rightaway** [comment]
The value of my shada option is by default `shada=!,'100,<50,s10,h`. I see in the docs "The 'n' flag in the 'shada' option can be used to specify another ShaDa file name |'shada'|." but I don't understand how to use it, could you give me an example of how I can use the flag please?

**Comment by rightaway** [comment]
The value of my shada option is by default shada=!,'100,<50,s10,h. I see in the docs "The 'n' flag in the 'shada' option can be used to specify another ShaDa file name |'shada'|." but I don't understand how to use it, could you give me an example of how I can use the flag please?

**Comment by alopatindev** [comment]
> could you give me an example

```viml
set shada='30,\"500,:30,%,n~/hello.bin
```
