### ISSUE TITLE
Allow linebreak and list to coexist.

### ISSUE THREAD

**Issue by kevincox** [neovim/neovim#896]
In vim it is documented that `linebreak` is not used when `list` is set.  It would be nice to be able to have intelligent word wrapping even when showing whitespace characters.

**Comment by tterranigma** [comment]
This is solved right?

**Comment by roryokane** [comment]
To follow up on my previous comment suggesting various ways to accomplish this, it appears that the chosen solution consisted of these changes:

- Add an optional `space` setting (not set by default) to Neovim’s [`'listchars'`]['listchars'].
- Change the [`'linebreak'`]['linebreak'] option to not disable itself when [`'list'`]['list'] is on (a backwards-incompatible change).

['list']: 
https://neovim.io/doc/user/options.html#'list'
['listchars']: 
https://neovim.io/doc/user/options.html#'listchars'
['linebreak']: 
https://neovim.io/doc/user/options.html#'linebreak'
