### ISSUE TITLE
Windows:  F1 in insert mode inserts an "A" 

### ISSUE THREAD

**Issue by rlouage** [neovim/neovim#8965]
- `nvim --version`: NVIM v0.3.2-402-ge30ccd56d
- Operating system/version: Windows 10
- terminal: standard windows command prompt

### Actual behaviour
When I press F1 in insert mode, an \"A\" charachter gets inserted. 
When I press F2-F5 a \"B,C,D\" and  E charchter gets inserted.
When pressing the F6-F12 charachters  \<F6\>  -  \<F12\>  gets inserted.

### Expected behaviour
I want ,and I think this is the normal behaviour, that F1-F5 behave like the F6-F12 keys. That is when pressing them in insert mode they just display their code namely:   \<F1\> -  \<F5\>  like the other F-keys do.

**Comment by mschilli87** [comment]
How does vim behave?

**Comment by justinmk** [comment]
@rlouage is this with `nvim.exe` or `nvim-qt.exe`? If it's the TUI (`nvim.exe` running in the Windows Console (cmd.exe)) then maybe we just need to update the builtin terminfo.

**Comment by rlouage** [comment]
@justinmk This is with nvim.exe. If I open a nvim-qt.exe all function keys seem te behave properly. I run nvim.exe in the standard cmd.exe in windows.

**Comment by rlouage** [comment]
@mschilli87 in vim the fuction keys behave like expected.

**Comment by justinmk** [comment]
merging with https://github.com/neovim/neovim/issues/11773
