### ISSUE TITLE
Please support closing term window when command exits

### ISSUE THREAD

**Issue by joshtriplett** [neovim/neovim#8975]
- `nvim --version`:

```
NVIM v0.3.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-XJHVyS/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-XJHVyS/neovim-0.3.1/build/config -I/build/neovim-XJHVyS/neovim-0.3.1/src -I/usr/include -I/build/neovim-XJHVyS/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-XJHVyS/neovim-0.3.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim (version: 8.1 + patches 1-320) behaves differently? Yes
- Operating system/version: Debian, latest unstable
- Terminal name/version: `GNOME Terminal 3.30.0 using VTE 0.54.0`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
exit
```

### Actual behaviour
nvim displays `[Process exited 0]` in the terminal and waits for a keypress.

### Expected behaviour
Terminal automatically closes when running a default shell.

vim's default feels right here: `:term` with no specified command will close the terminal buffer when the command exits, while `:term somecommand` will keep the terminal buffer open after the command exits (such as to allow reviewing output).

**Comment by justinmk** [comment]
I agree we should do this, but it's going to require some delicate changes, in particular we need to change `:terminal` to open a new-window, which will require updating docs and a bunch of tests. Non-trivial amount of work. It also could help to get more brainer/no-brainer opinions.

> Where's the movement on this? Vim 8 is killing it with ++close. This is a no-brainer.

👍 Don't forget that Vim 8 has `:smile` too.

**Comment by mcepl** [comment]
I was also told, that this issue indirectly covers support for ``:tab term``. Just a note for those who wonder why they have to do ``:tabnew |term`` instead.

**Comment by lucc** [comment]
If the default is changed to open a new window, I vote for `++curwin` from vim to undo this change.

I also would like to have a `++no-trailing-lines` (and also a better name for that option).  This is also some behaviour from vim where there are no extra lines in the buffer after the last line of output from the command.  I tried to find a solution to this [on vi.SE](https://vi.stackexchange.com/questions/16624/use-terminal-to-display-file-with-ansi-escape-codes) but without success.

**Comment by justinmk** [comment]
@lucc yes we would need `++curwin`  (or `:curwin` from https://github.com/vim/vim/pull/3251 )

**Comment by jfelchner** [comment]
Just to link the issues, this is related to: https://github.com/neovim/neovim/issues/4713

**Comment by mark-i-m** [comment]
Any update on this? It looks like it keeps getting moved to later milestones. I don't mind trying to implement it myself if it's not too much work and somebody can guide me (I don't really know anything about the codebase yet).

Some quick searching makes me think that these are the key lines:

https://github.com/neovim/neovim/blob/6ab83f35724737a7b74cfee0d21abe7c815f0a1a/src/nvim/channel.c#L685-L689

We would want to add some sort of config that gets plumbed through to indicate whether to exit with a message or not, right? i.e. depending on the config, we would call `terminal_close(chan->term, NULL)`?

**Comment by justinmk** [comment]
With #15440 , `:terminal` is closed if the command exits without error.
