### ISSUE TITLE
bracket python

### ISSUE THREAD

**Issue by roberbnd** [neovim/neovim#8981]
- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently?n
- Operating system/version:Archlinux
- Terminal name/version: Tilix
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
open a file type python (.py) and type ->   { <cr> 
and that's it, the cursor is moved to the next level

```
nvim -u NORC

```

### Actual behaviour
![python](https://user-images.githubusercontent.com/4907027/45363739-e6b64d00-b59d-11e8-8deb-97f8f737db1b.png)

### Expected behaviour
![java](https://user-images.githubusercontent.com/4907027/45363747-eb7b0100-b59d-11e8-8944-02c4ff4939c5.png)
Just open the brackets and when you <cr> between the brackets it must to be in the same level.

**Comment by justinmk** [comment]
Issue tracker is not for usage questions.

**Comment by roberbnd** [comment]
I believe this is an issue because only happen with files type of python in fact exist a plugin to fix this
https://github.com/Vimjas/vim-python-pep8-indent

if you open a file .js you are going to get:
{
}
