### ISSUE TITLE
What is released appimage architecture?

### ISSUE THREAD

**Issue by ali-hardan** [neovim/neovim#8991]
Hello. In releases page, not exists any information about appimage release architecture. is it on x86_64, or x86, or both of them?
I suggest to write the architecture in releases page.

**Comment by justinmk** [comment]
x86_64. It's kind of assumed that very few people run 32-bit Linux, at least for the purposes of the AppImage. Are you using 32-bit Linux?

**Comment by ali-hardan** [comment]
Yes, my old laptop cpu not supports x86_64, so I use 32-bit debian.

**Comment by justinmk** [comment]
Did you try building from source? Should not be too difficult if you have at least CMake 2.8.12.

See [here](https://github.com/neovim/neovim/wiki/Building-Neovim#ubuntu--debian).

```
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
git clone https://github.com/neovim/neovim.git
cd neovim
# Note: This builds a "Debug" build by default
make
./build/bin/nvim
```
