### ISSUE TITLE
How to disable native plugin?

### ISSUE THREAD

**Issue by rawaludin** [neovim/neovim#8999]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? Yes
- Operating system/version: Mac OS
- Terminal name/version: alacritty
- `$TERM`: screen-256color

### Actual behaviour
I want to disable builtin phpcomplete plugin because it causing neovim to slow.

https://gist.github.com/rawaludin/a6c6b40145ab1f75e039eb6631411395

```
 4403              2.119816  phpcomplete#GetTaglist()
 6   3.234129   0.533313  phpcomplete#GetCurrentNameSpace()
```

Is it possible?

### Expected behaviour
Removing/disabling this plugin should speed things up.

https://github.com/w0rp/ale/issues/1912

**Comment by tssm** [comment]
Try the following in the command line in a PHP buffer: `:set omnifunc=`. `omnifunc` is a local option and the idea is to set a different for each buffer according to its `filetype`. If it works then you could use and [autocommand](https://neovim.io/doc/user/autocmd.html) in your `.config/nvim/init.vim` file to set it persistently (something like `au BufNewFile,BufRead *.php set omnifunc=`), but I would try and [after filetype plugin](https://neovim.io/doc/user/filetype.html#ftplugin-overrule) (see the third point).

**Comment by eknowlton** [comment]
Did this work for anyone? It doesn't seem to have fixed this issue for me.

**Comment by mhinz** [comment]
@eknowlton 

Can you provide a file to test and say _when_ it is slow?

By default, `phpcomplete` functions are only used when explicitly requesting a completion. So, make sure to disable all PHP and maybe linting plugins before testing.

**Comment by eknowlton** [comment]
I'm not necessarily concerned about what is making it slow. In my specific situation it's slow while in being used with `w0rp/ale`.  I'm pretty sure i've used `phpcomplete` before Ale and it seemed to work fine.

I'm not completely sure, but it seems that `phpcomplete` is included in neovim. which is what is causing me issues. I'd for the plugin to be removed, but that seems to be something thats being discussed elsewhere. 

Here is a some profiling that might help. This could very well be something Ale should deal with, but I think disabling phpcomplete would do the trick.

https://gist.github.com/eknowlton/6c12f39e267b1ead9910f1154fd36f3b

**Comment by mhinz** [comment]
`phpcomplete` is a small library that is shipped with Vim as well. Have a look at `:e $VIMRUNTIME/autoload/phpcomplete.vim` from either Vim or Nvim.

The comment at the top of that file also lists a few options. @rawaludin mentioned `phpcomplete#GetCurrentNameSpace()` being slow, so this option looks interesting:

```
"		let g:phpcomplete_min_num_of_chars_for_namespace_completion = n [default 1]
"			This option controls the number of characters the user needs to type before
"			the tags will be searched for namespaces and classes in typed out namespaces in
"			"use ..." context. Setting this to 0 is not recommended because that means the code
"			have to scan every tag, and vim's taglist() function runs extremly slow with a
"			"match everything" pattern.
"
```

Put `let g:phpcomplete_min_num_of_chars_for_namespace_completion = 0` in your vimrc and see if it makes a difference.

**Comment by chrisbra** [comment]
> Put let g:phpcomplete_min_num_of_chars_for_namespace_completion = 0 in your vimrc and see if it makes a difference.

That will make it even slower, right?

**Comment by eknowlton** [comment]
Thanks for the advice @mhinz, I've definitely learned a bit from this discussion. I'm not having any luck but I don't develop in PHP much these days so i'm going to just use VS Code I guess haha
