### ISSUE TITLE
highlight group for completed text

### ISSUE THREAD

**Issue by 257** [neovim/neovim#9000]
- `nvim --version`:
- Vim (version: ) behaves differently?
No, see here https://github.com/vim/vim/issues/3433
- Operating system/version:
NA
- Terminal name/version:
NA
- `$TERM`:
NA
### Steps to reproduce using `nvim -u NORC`

NA 

### Actual behaviour
NA
### Expected behaviour

this is for having first candidate from pumvisible to be inserted in front of the cursor _tentatively_.

it really just comes down to the difference between autocompletion (we already have that) and typeahead as loosely define here: 
https://www.flextras.com/blog/index.cfm/2011/3/11/The-Difference-Between-AutoComplete-and-LookAhead

here is an animation of typeahead in action:
https://www.arungudelli.com/wp-content/uploads/2013/10/Twitter-Typeahead-js.gif

xcode, apparently, has this implemented already:
https://i.stack.imgur.com/k8PRF.png

**Comment by justinmk** [comment]
What does Xcode do if there's existing text to the right?

**Comment by jamessan** [comment]
Quoting from my response in the upstream issue:

> This is how completion already works.  With the default value for `'completeopt'`, the full text for the first match is inserted.
> 
> If you press `<C-e>` to cancel the completion, then whatever text you've explicitly typed remains, instead of what was inserted by the completion.
> 
> If you press `<C-y>` to accept the completion, it remains and the cursor is at the end of the text.
> 
> Otherwise, you can continue to type to refine the matches.
> 
> The only difference is that the animations you show leave the cursor at the end of the text that the user has typed and shows the completed text after the cursor (and faded).  There's no functional difference, just eye candy.

**Comment by glepnir** [comment]
Currently this is easily implemented in any completion plugin. You only need to find the first complete item in CompleteOnchagne and then add it as inline through the nvim_buf_set_extmark api. Just pay attention to some clean.
