### ISSUE TITLE
Can't redraw from a timer in an `<expr>` mapping

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#9006]
- `nvim --version`:      NVIM v0.3.2-331-g3807520 Build type: RelWithDebInfo
 - Vim (version: ) behaves differently?
   Yes, Vim `8.1.391` correctly executes `:redraw` from a timer in an `<expr>` mapping.
 - Operating system:     Ubuntu 16.04.5 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.8
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.6.2-dev-0 (x86_64-pc-linux-gnu)

Consider this minimal `vimrc`:

    cno  <expr>  <c-d>  Func()
    fu! Func() abort
        call timer_start(0, {-> execute('redraw') + feedkeys("\<c-d>", 'int')})
        return ''
    endfu

Now, start Neovim like this:

    $ nvim -Nu /tmp/vimrc

And type on the command-line (without executing the command):

    :h dir

Finally, press `C-d`.
It should list all the help tags containing the keyword `dir`.
But the list is not displayed.
You have to cause a redraw, for example by moving the cursor with the left arrow key, for the list to be displayed.

![gif](https://user-images.githubusercontent.com/8505073/45598264-59c62600-b9d9-11e8-86a5-19856f50dc19.gif)

It doesn't happen in Vim, because the timer executes a `:redraw` before pressing `C-d`.
![gif_1](https://user-images.githubusercontent.com/8505073/45598270-8b3ef180-b9d9-11e8-8663-e7c762e79dd0.gif)

---

The reason for executing a `redraw` before pressing `C-d`, is to erase a possible previous list.

**Comment by justinmk** [comment]
Does this make any difference:

    :set display-=msgsep

**Comment by lacygoill** [comment]
Unfortunately, it doesn't fix the issue.
But I will try to read the link you provided, maybe there's something in that will help.
Thank you very much.

**Comment by bfredl** [comment]
I've noticed this too. Sometimes `:redraw!` works in these situations when `:redraw` redraws too little, but it also clears the screen, which causes unnecessary flicker. Sometimes I think there should be a `:redraw all` middle grounds that redraws everything NOT_VALID but not CLEAR, which should be what one typical wants for `redraw!` (unless an external process actually messed up your terminal, or something).

**Comment by justinmk** [comment]
> (unless an external process actually messed up your terminal, or something).

@bfredl Perhaps `:redraw!` 's clear-screen behavior is a vestige of Vim's assumptions about how `:!` and other mechanisms work (by switching between cooked/raw modes). I noticed this recently  and removed some related calls in https://github.com/neovim/neovim/pull/8985

**Comment by bfredl** [comment]
Well, If I were to decide only for myself, I would nuke every single use of CLEAR from the codebase, except for a single command for emergency purposes (`:mode` maybe), as well as TUI resize (but this could be done internally in the tui.c module, external UI could have it defined what happens with the grid on resize instead, like "preserve top-left corner").

**Comment by justinmk** [comment]
> I would nuke every single use of CLEAR from the codebase, 

👍 

> except for a single command for emergency purposes (:mode maybe),

I would still vote to let CTRL-L (as well as `:mode`) clear the screen, it is what users reach for when the TUI or the host terminal has a redraw bug.

**Comment by bfredl** [comment]
> I would still vote to let CTRL-L (as well as :mode) clear the screen, it is what users reach for when the TUI or the host terminal has a redraw bug.

Makes sense, I have remapped CTRL-L to other stuff so I did not think of it. There is also `:suspend`, but I would treat it the same way as TUI resize.

**Comment by lacygoill** [comment]
I don't know whether it's linked to the current issue but I noticed another difference between Vim and Neovim.
If you set the `'lazyredraw'` option then press `:` immediately after Neovim starts, before it has the time to fully draw the statusline, it prints something like this:

    [No Name]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^0,0-1^^^^^^^^^^All

![gif1](https://user-images.githubusercontent.com/8505073/47537236-d8f62600-d8c4-11e8-9d7a-7a08d3886e6c.gif)

In Vim, if you press `:` before the statusline is drawn, nothing is printed.
![gif2](https://user-images.githubusercontent.com/8505073/47537239-ddbada00-d8c4-11e8-88f1-cc102b960a1a.gif)

**Comment by justinmk** [comment]
Why does it need to be "dealt with"? :) `^^^^^^^` is the default listchar.  If you do things before colorscheme/etc are loaded, display will show the defaults. No big deal.

**Comment by justinmk** [comment]
Still present on 0.4.0-902 b65a7b7f6692 (after https://github.com/neovim/neovim/pull/9804).

**Comment by gelguy** [comment]
Apologies for the late reply, but I only just saw this issue. I have been encountering this bug too, but found a workaround by returning `"\<Insert>\<Insert>"` in the expression.

```vim
cno  <expr>  <c-d>  Func()
fu! Func() abort
    call timer_start(0, {-> execute('redraw') + feedkeys("\<c-d>", 'int')})
    return "\<Insert>\<Insert>"
endfu
```
`\<Insert>` toggles the cursor between cursor and overstrike.

**Comment by zeertzjq** [comment]
#17257 looks more general. I guess this can be closed in favor of that one?
