### ISSUE TITLE
HOME and END keys don't work when running tmux

### ISSUE THREAD

**Issue by swertz** [neovim/neovim#9012]
- `nvim --version`: `NVIM v0.3.2-550-g32ad52a` Build type: `Debug`
- Vim (version: ) behaves differently? version `7.4.629`; I have the same issue with vim
- Operating system/version: Scientific Linux release 6.6
- Terminal: Konsole 17.12.3
- Terminal multiplexer: tmux (master)
- `$TERM`: konsole-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Go to insert mode
type "test"
Press HOME key
```

### Actual behaviour
Cursor stays at same position; the text is duplicated (becomes "testtest")

### Expected behaviour
Cursor goes at beginning of line.

When done in normal mode, nothing happens (and the cursor still doesn't go to the beginning). Also with the END key, nothing happens.

I'm aware that many issues have been opened around this subject, but they don't seem relevant here... I've tried with many different values for TERM: screen-256color, screen, tmux. None solve the problem.

When not running tmux, there is no issue (for all the TERM given above).

I have the following options set in my `.tmux.conf` to make the HOME and END keys work when just typing in the terminal, but commenting them does not seem to impact the behaviour in neovim:
```
bind-key -n End send-key C-e
bind-key -n Home send-key C-a
```

**Comment by justinmk** [comment]
> options set in my .tmux.conf to make the HOME and END keys work when just typing in the terminal, but commenting them does not seem to impact the behaviour in neovim

For tmux settings changes to take effect you need to restart tmux or re-source the config. Or enter the setting manually in the tmux `:` prompt (`CTRL-b :`).

Regarding your general issue, it sounds like the terminfo found on your system for your `$TERM` has missing or incorrect entries for HOME/END. And in fact, if you're using `TERM=konsole-256color` within tmux, then that's incorrect. Inside tmux, tmux is your terminal, the "outer" terminal is completely irrelevant to applications running inside tmux, and telling those applications the wrong TERM will do wrong things.

**Comment by swertz** [comment]
Thanks for your feedback.

> For tmux settings changes to take effect you need to restart tmux or re-source the config. Or enter the setting manually in the tmux : prompt (CTRL-b :).

I did properly re-load the config.

> And in fact, if you're using TERM=konsole-256color within tmux, then that's incorrect.

Fair enough, but as I said, setting `TERM=screen-256color` does not solve the issue.
(I tried setting it to `konsole-256color` because of some issue with the cursor, and it actually seemed to work, despite your concern, but that's a separate story)

**Comment by justinmk** [comment]
> I should probably add that I'm running over ssh, in case that's relevant

Very relevant, because:

- ssh doesn't forward any env vars except `$TERM`
- the terminfo files on the remote system could be outdated or just plain wrong
    - Vim and Nvim try to work around this by having builtin terminfos, with varying success

**Comment by swertz** [comment]
OK, but when I run over `ssh` and _without_ `tmux`, the HOME and END keys work fine if, _both_ with `TERM=konsole-256color` and `TERM=screen-256color`. So it seems the terminfos on the remote system are not in cause?

It's only when running `tmux` that I run into this issue, as I said, even with `TERM=screen-256color`.

**Comment by justinmk** [comment]
That's weird. Well, there is at least a way to check what's going on: with Nvim 0.3.0+ you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Try this:

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post that section.

(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

And in Vim (not Nvim), try this:

    :set termcap

In both cases look for `end`, `home`, and maybe `kend` and `khom`. Compare these results "with tmux" and "without tmux".

**Comment by swertz** [comment]
Here are the results with `TERM=screen-256color` in `tmux`, and `TERM=konsole-256color` outside of `tmux`.

### Neovim:

I don't see any of `end` or `home`, but:

/  | tmux | no tmux 
----------- | ----------- | -----------
`kend` | `<Esc>[4~` | `<Esc>OF`
`khome` | `<Esc>[1~` | `<Esc>OH`

### vim:

I don't see any of `(k)end`, or `(k)home`, but:

/  | tmux | no tmux 
----------- | ----------- | -----------
`<End>` | `^[[4~` | `^[OF`
`<Home>` | `^[[1~` | `^[OH`

When I use `TERM=screen-256color` _without_ tmux, I do see the same results as with it, but I'm running into other issues... Again, using either value for `TERM` will always result in END/HOME working outside of `tmux`, but not working inside of it.

Some further checks:

### Running `tput khome/kend | cat -v; echo`:

/  | tmux | no tmux 
----------- | ----------- | -----------
`kend` | `^[[4~` | `^[OF`
`khome` | `^[[1~` | `^[OH`

### Running `tput home/end | cat -v; echo`:

/  | tmux | no tmux 
----------- | ----------- | -----------
`end` | unknown | unknown
`home` | `^[[H` | `^[[H`

### Running `cat -v` then typing END or HOME:

/  | tmux | no tmux 
----------- | ----------- | -----------
`END` | `^E` | `^[[F`
`HOME` | `^A` | `^[[H`

**Comment by swertz** [comment]
I have tried one further thing: I have retrieved the terminfo config file for `tmux-256color` (since that TERM was not available on the remote machine I'm ssh'ing into) [https://raw.githubusercontent.com/jez/dotfiles/master/tmux-256color.terminfo](here) and compiled it with `tic`. 

In that file, the `kend` and `khome` entries seem to correspond to what I'm getting when using the `tput` commands above.

When I set `TERM=tmux-256color`, it does not complain about missing terminfo file.

... but HOME/END still don't work in (neo)vim...

**Comment by justinmk** [comment]
> the issue only appears inside of (neo)vim, not in the terminal itself or in python or lua prompts...

Because those prompts/shells all use readline library, which does what you want when it sees CTRL-e or CTRL-a. So I think your collection of workarounds will be complete if you do this in your vimrc/init.vim:

    inoremap <C-a> <Home>
    inoremap <C-e> <End>

**Comment by swertz** [comment]
Awesome, that did the trick! Thanks a lot!
