### ISSUE TITLE
Man.vim: mentioned manpages are not detected correctly when they span over several lines

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#9017]
- `nvim --version`: 
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.1) behaves differently? No
- Operating system/version: Arch Linux
- Terminal name/version: Urxvt
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Man 2 fork " Just an example, not all manpages show this behaviour
```

### Actual behaviour

'Links' to other man pages at the `SEE ALSO` section at the bottom of the page which span over several lines are not detected by the plugin. This affects not only the syntax these words get but also the possibility to jump to those manpages when they are under the cursor - with `CTRL-]`/`K`.

### Expected behaviour

Every manpage 'Link' is detected and available for jumping to it with `CTRL-]`/`K`.

### Solution suggestion

What if we'll use `wrap` and `linebreak` with `breakindent` instead of creating hard wraps when the man page is read? This would have an additional benefit - resizing the window where there's the man page won't require reloading the man page in order to fix the fake (hard) wrappings.

**Comment by justinmk** [comment]
> What if we'll use wrap and linebreak with breakindent instead of creating hard wraps when the man page is read?

Good idea, but I think the problem is that the "layout" (including hard wraps) is done by nroff or whatever. Not sure if there's an option to prevent hard wraps. cc @nhooyr

**Comment by nhooyr** [comment]
Not sure either if there is an option. I'm not familiar with roff and the associated software.

A hack we could do is make the window width the size of the manage in bytes. Then we could wrap it ourselves.

See https://github.com/neovim/neovim/blob/8b60253ce747183a1896a8f0057519a1e2e517a1/runtime/autoload/man.vim#L152

**Comment by justinmk** [comment]
I was thinking that the layout might get messed up if we specify a bigger width and wrap it ourselves, but it's possible that `breakindent` is good enough.

**Comment by doronbehar** [comment]
I've just tested it and `env MANWIDTH=10000000 man 2 fork` works great. I guess it means this issue can be worked around with `breakindent`, `wrap` and `linebreak`  in my local `ftplugin/man.vim` and `MANWIDTH=10000000` in my shell rc files.

I still think though that `$MANWIDTH` shouldn't even be considered when creating the manpage buffers and `breakindent`, `wrap` and `linebreak` should be set by default in `Man.vim`.

**Comment by doronbehar** [comment]
The PR for the new behaviour is ready, should we keep the old behaviour an option?

**Comment by nhooyr** [comment]
> The PR for the new behaviour is ready, should we keep the old behaviour an option?

Nah, don't see the value in another knob.
