### ISSUE TITLE
Cursor getting stuck in `:Tutor` invisible hypertext

### ISSUE THREAD

**Issue by makmm** [neovim/neovim#9025]
- `nvim --version`:
```
NVIM v0.3.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-XJHVyS/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-XJHVyS/neovim-0.3.1/build/config -I/build/neovim-XJHVyS/neovim-0.3.1/src -I/usr/include -I/build/neovim-XJHVyS/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-XJHVyS/neovim-0.3.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Vim behaves differently? N/A
- Operating system/version: Debian sid
- Terminal name/version: N/A (breaks in any terminal)
- `$TERM`: N/A

### Steps to reproduce using `nvim -u NORC`

I sadly don't know how to use this

### Actual behaviour

You go into `:Tutor`, and when navigating through one of the "links" (stuff like `<Esc>`, etc) the cursor gets "stuck" with the invisible hypertext characters.

### Expected behaviour

The cursor doesn't get stuck.

**Comment by justinmk** [comment]
Thanks for the report!

This is a limitation and/or design decision of how the `:help conceal` feature works.

**Comment by makmm** [comment]
that's a horrible user experience. anyway, i guess i'll stay on vscode then :P

**Comment by makmm** [comment]
that's a horrible user experience. anyway, i guess i'll stay on vscode then :P
