### ISSUE TITLE
Windows: GUI popup menu does not obey colorscheme highlighting / formatting

### ISSUE THREAD

**Issue by DrZingo** [neovim/neovim#9026]
Popup menu does not obey highlighting in nvim-qt 0.3.2-557 on Windows
It appears that only GUI is affected, as TUI (cmd.exe -> nvim) works as it should.
GUI popup menu worked as expected around a month ago, so the problem should be in a later commit.

---
:checkhealth (all checks are identical in both versions)

health#nvim#check

 Configuration
  - OK: no issues found

 Performance
  - OK: Build type: RelWithDebInfo

 Remote Plugins
  - OK: Up to date
---

- `nvim --version`: NVIM v0.3.2-557-g8b60253ce
- Operating system/version: Win 10
- Terminal name/version: cmd.exe

### Actual behaviour
 **nvim-qt v0.3.2-557-g8b60253ce**

![image](https://user-images.githubusercontent.com/6590732/45877982-cce7e780-bd9f-11e8-9691-877af9af8af2.png)

### Expected behaviour
**nvim-qt v0.3.1**

![image](https://user-images.githubusercontent.com/6590732/45878013-eab54c80-bd9f-11e8-80b8-6253875bd2fc.png)

**Comment by clason** [comment]
That's an issue specifically with neovim-qt's implementation of the external popupmenu (which can be disabled via `GuiPopupmenu 0` in `init.vim`), see https://github.com/equalsraf/neovim-qt/commit/b2b5aa2cf4d9f509fd30b8912ed58d4398e8d141

**Comment by DrZingo** [comment]
> GuiPopupmenu 0

Thank you. I have struggled with this issue today. `GuiPopupmenu 0` did the work.

**Comment by artkpv** [comment]
I put `GuiPopupmenu 0` in my "vimrc" file and it writes:

> E492: Not an editor command: GuidPopupmenu 0

Under Windows 8, neovim 0.3.7. How to fix it?

**Comment by clason** [comment]
@artkpv `GuiPopupmenu` is a neovim-qt specific option and not handled by neovim -- you need to put it in `ginit.vim` or behind a `exists('g:GuiLoaded')` guard.

**Comment by artkpv** [comment]
@clason Thank you for the answer. I managed to run it using `autocmd VimEnter` as above.
