### ISSUE TITLE
Editing a file in silent mode suppresses the "Found a swap file" message but still waits for user input

### ISSUE THREAD

**Issue by afn** [neovim/neovim#9027]
- `nvim --version`: v0.3.2-566-gac4d5d993
- Vim (version: 8.0.1453-1ubuntu1) behaves the same
- Operating system/version: Linux
- Terminal name/version: gnome-terminal 3.30.0
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC foo.txt
# suspend
nvim -u NORC
:silent! e foo.txt
```

### Actual behaviour

The "Found a swap file" attention message is suppressed, but neovim waits for user input (Enter, `O`, `E`, etc) before proceeding.

### Expected behaviour

I would expect one of the following:
1. In silent mode, the swap message is suppressed and the file opens in read-only mode.
2. Even in silent mode, the swap message is always shown, and it waits for user input.

See also https://github.com/junegunn/fzf/issues/1365 for the actual affected use case: when opening a file in fzf, silent mode is enabled implicitly by virtue of `shortmess` including the `F` flag, which causes the swap file message to be suppressed. So a possible third option, if this is really the desired behavior of `silent!`, would be to change the behavior only for the case where `msg_silent` is enabled by `SHM_FILEINFO`. (In fact, based on the documentation, I would expect `shortmess+=F` to behave like `:silent e foo.txt` --- which does NOT suppress the message --- rather than behaving like `:silent! e foo.txt`, which is what it currently does.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8898 is related but it's not enough, there's a missing redraw, possibly from one of the UI refactors in the last few weeks.
