### ISSUE TITLE
[RFC] Rewrite luajit+ffi tests with C

### ISSUE THREAD

**Issue by ZyX-I** [neovim/neovim#903]
Due to my inability to debug the problem with luajit failing to run the tests (#471) I started to seek whether there are other acceptable variants of testing my code. First thing I looked at was obviously writing tests in C with some macros helpers. After rewriting `expr.moon` with C I got funny results:

1. Difference between C and moonscript version in a number of characters of main test body is negligible: moonscript

        it 'parses number 0', ->
          eqn 'N[+0+]', '0'

    changed to

    ```c
    IT("parses number 0",
       EQN("N[+0+]", "0", DEF))
    ```

    : only added two pairs of parenthesis and `DEF`. Some very long single line strings (they are single line, but for readability I need to wrap them) are expressed better with C.
2. Necessary definitions (macros and imports) take only 81 lines. In comparison:
    - there are 16 lines of function definitions necessary to call test function.
    - 25 lines to call all necessary initializers (just as many as in C though if you forget about some unnecessary things)
    - 57 lines (without comments) of functions and other things in helpers.moon
    - about a hundred (without comments) in preprocess.moon

    These lines are needed mainly to fight luajit to make it what we want (mainly to get `#include` equivalent) and this fight is still not finished: including random files (e.g. uncomment and fix cimports needed to declare initializer functions) leads to nothing, but error and test failure.
3. Luajit cannot run inside valgrind.
4. With luajit ffi you are lucky if you were able to set breakpoint in nvim source code and it worked. It sometimes work (mainly after I caused failure), sometimes does not. Last few times I tried it was not going to work, failure or not.
5. If it is luajit who fails you are completely out of lack: luajit internals are way too complex.
6. Inside luajit no macros like SIZE_MAX are available.
7. Luajit is slow. I am not joking: \:commands tests with my `eqn` function doing absolutely nothing useful (specifically not calling my parser) complete in 4.8 seconds, normal runs complete in 5.6 seconds. Only 14% of time it is doing something useful.
8. You cannot add test stage to Gentoo ebuilds with busted because busted (and a number of its dependencies) is not  available in portage. In fact there is no package for busted in any distribution I know.

The main my reason is obviously inability to debug tests.

Good thing is that due to luajit we are going to have decent linter (using structs was just asking for trouble, so I had to make testhelpers that output strings and only strings).

Macros I used were:

```c
#define DEF -1

#define START_TEST \
    int main(int argc, char **argv) \
    { \
      int ret = 0; \
      int indent_level = 0; \
      mch_early_init(); \
      mb_init(); \
      eval_init(); \
      init_normal_cmds(); \
      allocate_generic_buffers(); \
      win_alloc_first(); \
      init_yank(); \
      init_homedir(); \
      set_init_1(); \
      set_lang_var();
#define END_TEST \
      return !!ret; \
    }
#define DESCRIBE(msg, block) \
    { \
      printf("%*s%s\n", indent_level*2, "", msg); \
      indent_level++; \
      block \
      indent_level--; \
    }
#define IT(msg, block) \
    { \
      printf("%*s%s: ", indent_level, "", msg); \
      indent_level++; \
      int prev_ret = ret; \
      do { \
        block \
      } while (0); \
      if (prev_ret == ret) { \
        puts("ok"); \
      } \
      indent_level--; \
    }
#define EQN(expected_result, toparse, expected_offset) \
    { \
      char *parsed = srepresent_parse0(toparse, false); \
      size_t exp_offset = expected_offset; \
      char expected[sizeof(exp_offset) * 2 + sizeof(expected_result) + 1]; \
      if (expected_offset == DEF) { \
        exp_offset = sizeof(toparse) - 1; \
      } \
      sprintf(expected, "%X:%s", (int) exp_offset, expected_result); \
      if (strcmp(expected, parsed) != 0) { \
        printf("\n%*sLine %u:\n%*sexpected %s,\n%*s but got %s\n", \
               indent_level, "", __LINE__, \
               indent_level, "", expected, \
               indent_level, "", parsed); \
        ret++; \
      } \
      free(parsed); \
    }
#define ITN(toparse, expected_result, expected_offset) \
    IT("parses " toparse, \
       EQN(expected_result, toparse, expected_offset))
```

It is probably better to find some C testing framework though.

**Comment by justinmk** [comment]
I think we can close this. Most problems with the lua tests can be fixed.
