### ISSUE TITLE
Permanently overrides terminal cursor colour

### ISSUE THREAD

**Issue by realh** [neovim/neovim#9032]
- `nvim --version`:
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

- Vim (version: 8.1) behaves differently? Yes
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal 3.28.2 and roxterm 3.6.2 (both based on vte 0.52.2)
- `$TERM`: xterm-256-color

### Steps to reproduce using `nvim -u NORC`

Use the following options:
```
set termguicolors
colorscheme torte
set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50
    \,a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor
    \,sm:block-blinkwait175-blinkoff150-blinkon175
```

### Actual behaviour

The cursor colour changes even if I use a colorscheme which doesn't explicitly set the Cursor highlight. It keeps its new colour even after nvim exits and I can't change it back with the terminal settings.

### Expected behaviour

When nvim exits the cursor should be reset to how it was before nvim changed it and allow itself to be changed from the terminal settings again.

**Comment by justinmk** [comment]
Since https://github.com/neovim/neovim/pull/8572 was merged this should be fixed on HEAD.
