### ISSUE TITLE
patches: split out userfunc/evalfunc?

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#9037]
Vim has split parts of `eval.c` out into `userfunc.c` (https://github.com/vim/vim/commit/a9b579f3d) and `evalfunc.c` (https://github.com/vim/vim/commit/73dad1e64).

Why has Neovim not followed this?  Should it be done?
This constantly fails when trying to apply patches for me.

**Comment by justinmk** [comment]
Patches would not apply even if we did that.   Use tags (`ctrl-]`) to find  a function and paste the relevant lines. 

Bram split those files only to work around a performance problemwith codecov's web UI.  @ZyX-I has been rearranging things in a different way.

**Comment by justinmk** [comment]
@blueyed Note however that to avoid confusion we could do a "fixup" in `preprocess_patch()`, like we already do for other files such as matchit: https://github.com/neovim/neovim/blob/8872fce120b0d38d50254c82407038d40da84647/scripts/vim-patch.sh#L179

**Comment by blueyed** [comment]
> Patches would not apply even if we did that.

Not in general - or what do you mean?

I've meant that we would manually align the functions once, creating userfunc.c/evalfunc.c also in Neovim.  Due to different linting etc I see that patches would not necessarily apply cleanly of course, but at least `patch` would find the file(s).

Fixup in vim-patch.sh sounds OK - although lines would be off a lot?!

**Comment by justinmk** [comment]
> Due to different linting etc I see that patches would not necessarily apply cleanly of course, but at least patch would find the file(s).

Yes but I've never actually seen a patch apply in a useful manner. Sometimes it even does completely wrong things. I usually just open up the `*.patch` file, copy the lines and `<C-]>` to the function.

**Comment by jamessan** [comment]
> Due to different linting etc I see that patches would not necessarily apply cleanly of course, but at least `patch` would find the file(s).

It's not just due to linting.  ZyX completely rewrote much of the typval related code.
