### ISSUE TITLE
Question: Incompatibility with `none` colors between Neovim and Vim?

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#9045]
- `nvim --version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: 8.1) behaves differently? **yes**
- Operating system/version:
- Terminal name/version:
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

Add to your colorscheme a `ctermfg=none` or `ctermbg=none` attribute to one of the highlighting groups and launch `nvim` in a terminal.

### Actual behaviour

Neovim won't complain.

Vim does complain with the following error:
```
E254: Cannot allocate color none
```

### Expected behaviour

Both Vim and Neovim should complain?

### Background

I wanted to test the compatibility of my configuration with Vim and when launching Vim I have encountered lots of these errors since my colorscheme contains a lot of these. While searching for help on this error I've encountered https://github.com/vim/vim/issues/1400 which seemed to discuss this issue but apperently somehow Vim and Neovim behave differently.

### Question

Assuming I don't care much about the inconsistency as a user, how can I convert my colorscheme to look the same in both Neovim and Vim? What is the equivalent of the "virtual `none`" color of Neovim in Vim?

**Comment by justinmk** [comment]
> What is the equivalent of the "virtual none" color of Neovim in Vim?

I think it's just a casing issue, Vim wants `NONE`.

**Comment by doronbehar** [comment]
Right, thanks.
