### ISSUE TITLE
build fails with OSX Mojave

### ISSUE THREAD

**Issue by FuzzOli87** [neovim/neovim#9050]
Attempting to build from master fails on OSX mojave. 

### Actual behaviour
make CMAKE_BUILD_TYPE=Release

<details>
<summary>build output</summary>

```
In file included from unibilium.c:22:
./unibilium.h:25:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:69: unibilium.lo] Error 1
gmake[1]: Leaving directory '/Users/daniel.olivares/Development/neovim/.deps/build/src/unibilium'
[13/66] Performing install step for 'libvterm'
FAILED: build/src/libvterm-stamp/libvterm-install
cd /Users/daniel.olivares/Development/neovim/.deps/build/src/libvterm && /usr/local/bin/gmake CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc PREFIX=/Users/daniel.olivares/Development/neovim/.deps/usr CFLAGS=-fPIC CFLAGS+=-Og CFLAGS+=-g install && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E touch /Users/daniel.olivares/Development/neovim/.deps/build/src/libvterm-stamp/libvterm-install
gmake[1]: Entering directory '/Users/daniel.olivares/Development/neovim/.deps/build/src/libvterm'
install -d /Users/daniel.olivares/Development/neovim/.deps/usr/include
install -m644 include/vterm.h include/vterm_keycodes.h /Users/daniel.olivares/Development/neovim/.deps/usr/include
install -d /Users/daniel.olivares/Development/neovim/.deps/usr/lib/pkgconfig
sed -e "s,@PREFIX@,/Users/daniel.olivares/Development/neovim/.deps/usr," -e "s,@LIBDIR@,/Users/daniel.olivares/Development/neovim/.deps/usr/lib," -e "s,@VERSION@,0.0," <vterm.pc.in >/Users/daniel.olivares/Development/neovim/.deps/usr/lib/pkgconfig/vterm.pc
CC src/encoding.c
In file included from src/encoding.c:1:
In file included from src/vterm_internal.h:4:
include/vterm.h:9:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:63: src/encoding.lo] Error 1
gmake[1]: Leaving directory '/Users/daniel.olivares/Development/neovim/.deps/build/src/libvterm'
[14/66] Performing install step for 'luajit'
FAILED: build/src/luajit-stamp/luajit-install
cd /Users/daniel.olivares/Development/neovim/.deps/build/src/luajit && /usr/local/bin/gmake CFLAGS=-fPIC CFLAGS+=-DLUAJIT_DISABLE_JIT CFLAGS+=-DLUA_USE_APICHECK CFLAGS+=-DLUA_USE_ASSERT CCDEBUG+=-g Q= install CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc PREFIX=/Users/daniel.olivares/Development/neovim/.deps/usr && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E touch /Users/daniel.olivares/Development/neovim/.deps/build/src/luajit-stamp/luajit-install
gmake[1]: Entering directory '/Users/daniel.olivares/Development/neovim/.deps/build/src/luajit'
==== Building LuaJIT 2.0.5 ====
/usr/local/bin/gmake -C src
gmake[2]: Entering directory '/Users/daniel.olivares/Development/neovim/.deps/build/src/luajit/src'
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
In file included from lj_arch.h:9:
In file included from ./lua.h:16:
./luaconf.h:145:10: fatal error: 'assert.h' file not found
#include <assert.h>
```
</details>

### Expected behaviour

For the build process to succeed.

I tried doing the typical xcode stuff ```xcode-select --install``` and the license accepting stuff. But so far nothing has worked.

**Comment by jamessan** [comment]
I would suggest trying `make distclean` first.  From what I've read, Mojave has moved standard header files out of `/usr/include`, so CMake may need to re-run to find where they are.

If that doesn't work, there's not much we can do.  This is clearly a macOS issue, not an nvim issue.

**Comment by clason** [comment]
I can't check right now, but I think starting with Mojave the headers are an additional install -- look for an error message telling you to install a package called something like `.../macos10.14_headers.pkg`.

**Comment by FuzzOli87** [comment]
@jamessan That did not work. What @clason recommended got me past that struggle.

@clason This got me closer to it! It got passed that error but now it's failing somewhere else and I'm not really sure where.

**Comment by clason** [comment]
@FuzzOli87 Have you tried homebrew? This works for me (using https://github.com/Homebrew/homebrew-core/pull/32204).

**Comment by jamessan** [comment]
> the build system on macOS will have to be adapted to look for headers in the SDK

Any help making that happen is appreciated -- pointers to documentation or PRs.  I'm not familiar with what would be needed here.

**Comment by clason** [comment]
@jamessan I'd have to understand neovim's build system first; from the release notes, the headers are now no longer installed in `/usr/include` but in either
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
```
(with a full Xcode install) or 
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```
(with only the command line tools installed). Having to special case macOS (>=10.14) will be a pain...

**Comment by jamessan** [comment]
According to [CMake's documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html#variable:CMAKE_OSX_SYSROOT), it seems the end-user building the software should be setting `CMAKE_OSX_SYSROOT` appropriately for the SDK they're targeting.

However, it's supposed to default to `$SDKROOT` or, if that's not set, get calculated based on `$MACOSX_DEPLOYMENT_TARGET`.  Are these no longer set in your build environment?

**Comment by FuzzOli87** [comment]
After some digging, I finally got it to build locally by running:
```export MACOSX_DEPLOYMENT_TARGET=10.14```
I was led to this by:
https://github.com/Homebrew/homebrew-core/issues/31483
Which led to this:
https://luajit.org/install.html


And finally, led to my experimentation which worked. I don't know anything about the build process or how/when this variable is set, if even, but that worked for me.

**Comment by jamessan** [comment]
Ok, well that correlates with the CMake documentation I linked earlier.  I guess the question is why this isn't being set in your build environment.

My assumption (never having built anything on macOS) is that there are certain environment variables set based on the SDK you're building with, which CMake should be able to pick up.  Maybe that's not the case and everyone used to just get away with it because the headers were installed to `/usr/include`.

In which case, maybe there's a "run terminal with SDK environment set" button somewhere that people should be using to perform builds.  I know there is on the Windows side of the world, since you can have multiple SDKs installed, so you start a cmd prompt targeting the SDK you're trying to build with.

**Comment by clason** [comment]
Note that @FuzzOli87 seems to have had already installed the compatibility package at this point.

macOS is a bit of a walled garden; Apple assumes that people are building macOS apps with the macOS tools, which know the correct path... (I share your suspicion on why other things mostly "just work".) I myself rely on homebrew for compiling open source software.

Unfortunately, there's no "developer terminal"; the used developer environment is selected from the command line via an `xcode-select` utility (or from within Xcode, if that is installed). This includes the SDKs; the command line tools should automatically pick up the right SDK (I have no idea how cross-compilation works on macOS). Why this doesn't happen here is not clear to me; either (a not Mojave-aware version of) cmake overrides this with "default" settings, or some settings were cached before upgrading to Mojave and were still being picked up.

Ideally, it suffices to do 
```bash
MACOSX_DEPLOYMENT_TARGET=10.14 make
```
(and, if so, add this to the build instructions), but it's apparently not that easy. (CMake seems to be picking up the correct SYSROOT, though, so something else must be going on.)

**Comment by jamessan** [comment]
If there's a way to query the running macOS for the version, then we could default `MACOSX_DEPLOYMENT_TARGET` to that, if it isn't already set.

**Comment by jamessan** [comment]
Does this diff help?

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 02b555d54..8fb213638 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,6 +2,10 @@
 #   intro: https://codingnest.com/basic-cmake/
 #   best practices (3.0+): https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1
 
+if(APPLE AND NOT DEFINED ENV{MACOSX_DEPLOYMENT_TARGET} AND NOT DEFINED ENV{SDKROOT})
+  set(CMAKE_OSX_DEPLOYMENT_TARGET ${CMAKE_SYSTEM_VERSION})
+endif()
+
 cmake_minimum_required(VERSION 2.8.12)
 project(nvim C)
 
```

**Comment by clason** [comment]
@jamessan Unfortunately not.

But that's not the problem -- I can compile `libuv` and `luajit` individually from the respective source directories in `.deps/build/src` (setting the `$MACOSX_DEPLOYMENT_TARGET` for luajit first), but `make deps` fails.

**Comment by jamessan** [comment]
Ah, right.  What if add those 3 lines to `third-party/CMakeLists.txt` before `project(NVIM_DEPS)`?

**Comment by clason** [comment]
Still no luck 😞

**Comment by jamessan** [comment]
Ok, then someone will need to do some more investigation. :)

**Comment by clason** [comment]
And probably see why homebrew's https://github.com/Homebrew/homebrew-core/blob/master/Formula/neovim.rb works while `make` doesn't :) 

(Honestly, I'm fine with relying on homebrew for compiling neovim on macOS. And if anything needs to be changed on the neovim side to keep this working later on, I'm sure the brew community will open a much more detailed issue.)

**Comment by danilo-augusto** [comment]
@clason Both builds crash for me though

**Comment by FuzzOli87** [comment]
@clason I installed the header stuff that you pointed too earlier. And I also ran brew reinstall to reinstall everything, including the listed dependencies to build neovim.

@jamessan If you need to find out anything else about my environment, let me know and I can provide.

**Comment by danilo-augusto** [comment]
Solved for me by installing the newest version of Xcode and its tools. 🎉

**Comment by zhaozg** [comment]
I meet same issue after install Mojave

1. after xcode-select --install,  issue exist

**Comment by dm1try** [comment]
ok, one more working recipe just arrived :) 
  - install dev tools using `xcode-select --install`
  - clean build using `make distclean`
  - provide `SDKROOT` and  `MACOSX_DEPLOYMENT_TARGET` env vars explicitly on building
```
make SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14
```

it works without installing the compatibility package mentioned above, though I'm still not sure who to blame; will investigate this later

**Comment by dm1try** [comment]
Hi, there! So I did some investigation^

Actually, the providing two additional environment variables(`MACOSX_DEPLOYMENT_TARGET` and `SDKROOT`) points that we have ✌️ problems  :
1. the first one, that was already mentioned above,`luajit` sets `MACOSX_DEPLOYMENT_TARGET ` to `10.4` if it is not provided(see [the docs](http://luajit.org/install.html), [code](https://github.com/LuaJIT/LuaJIT/blob/b025b01c5b9d23f6218c7d72b7aafa3f1ab1e08a/src/Makefile#L301-L303)).
 IMHO the implicit setting of this value leads to inconsistency(some components are built with the default target if the value is not provided, but the `luajit` is built with `10.4`)
for this target value on Mojave `clang` cannot find system lib:
```
# 10.4
MACOSX_DEPLOYMENT_TARGET=10.4 cc -lgcc_s.1
ld: library not found for -lgcc_s.10.4

# default
cc -lgcc_s.1
Undefined symbols for architecture x86_64:
  "_main", referenced from:
  ...
```
So if `MACOSX_DEPLOYMENT_TARGET` is not provided we can set `CMAKE_OSX_DEPLOYMENT_TARGET` value to it while building `luagit` here:
https://github.com/neovim/neovim/blob/e568ac7a68d3b7a05af34d931fad1d2c18fa396c/third-party/cmake/BuildLuajit.cmake#L53-L54
In the case `MACOSX_DEPLOYMENT_TARGET/CMAKE_OSX_DEPLOYMENT_TARGET` is empty, it looks like `clang` will fallback to a default value
```
MACOSX_DEPLOYMENT_TARGET= cc -lgcc_s.1
Undefined symbols for architecture x86_64:
  "_main", referenced from:
  ...
```

So all components should depend on `CMAKE_OSX_DEPLOYMENT_TARGET` at least, otherwise, a user must provide `MACOSX_DEPLOYMENT_TARGET` explicitly for solving the issue^

2. the second issue is related to the latest changes(also mentioned above) in the management of system headers(they moved from `/usr/include` to MacOS SDK path). the trick is what how this path is resolved by `clang`.
if you run `clang` directly from toolchain without providing `isysroot` option it cannot resolve the sdk path, that leads to the build errors:
```
configure:3481: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftes
 conftest.c  >&5
configure:3485: $? = 0
configure:3507: result:
configure:3529: checking whether we are cross compiling
configure:3537: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o conftes
 conftest.c  >&5
conftest.c:11:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
```
```
host/minilua.c:34:10: fatal error: 'math.h' file not found
#include <math.h>
```
So to make the compiler happy we should provide sdk path to the compiler in `isysroot` option(does it sound like a proper solution?). On my machine those values are properly resolved by `cmake`
```
cmake -LA &> /dev/null| grep 'COMPILER\|SDK'
CMAKE_C_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
```
 but sdk path is not passed to the compiler.

OK. But why does the explicit `SDKROOT` value also solve the problem? `SDKROOT` is just another way to pass sdk path to the `clang`; internally it is used by `xcrun` tool
```
       xcrun provides a means to locate or invoke developer tools from the command-line, without requiring users to modify Makefiles or otherwise take inconvenient measures to support multiple Xcode tool chains.
```
```
       SDKROOT
          Specifies the default SDK to be used when looking up tools (some tools may have SDK specific versions).
          ....
          For example, if xcrun is used to invoke clang via:
              xcrun --sdk macosx clang test.c
          then xcrun will provide the full path to the macosx SDK in the environment variable SDKROOT. That in turn will be used by clang(1) to automatically select that SDK when compiling the test.c file.
```

so according to all this information, the updated snippet to make the build on Mojave is:
```bash
# make clang happy and trick luajit 😄 
make SDKROOT=`xcrun --show-sdk-path` MACOSX_DEPLOYMENT_TARGET=
```

I'm still not sure about the proper solution for the second problem, though

**Comment by justinmk** [comment]
Nice. Can you send a patch?

**Comment by dm1try** [comment]
> Nice. Can you send a patch?

sure, I'm going to continue tomorrow(check the possible solution for the second problem) and make a PR

**Comment by nyngwang** [comment]
I'm using macOS Monterey 12.2.1, and I encountered build error minutes ago. This resolves my problem:

```
sudo make distclean
```

**Comment by Sleepful** [comment]
thank you @nyngwang
