### ISSUE TITLE
:Man starts at the end of the file

### ISSUE THREAD

**Issue by flemingfleming** [neovim/neovim#9057]
- `nvim --version`: NVIM v0.3.2-600-gfc18fad74
- Vim (version: ) behaves differently? Yes
- Operating system/version: Arch Linux

`nvim -u NORC`
```vim
Man nvim
```

The first and last line of any manpage  is now around 5000 characters long when displayed by neovim, meaning that any manpage appears at first glance to be just the heading and then a blank page. Setting norwap fixes the issue but the rest of the manpage is then unreadable.

**Comment by flemingfleming** [comment]
Ok so I force deleted neovim's runtime directory, then reinstalled the package, and it works as expected...

Still displaying manpages starting at the end of the file however, but I guess that's unrelated.
I guess I'll close this.

**Comment by justinmk** [comment]
No that's my fault. Will fix.
