### ISSUE TITLE
API: No nvim_buf_lines_event after :checktime in autocmd

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#9058]
- `nvim --version`: NVIM v0.3.2-462-gf2b555c9e
- Vim (version: ) behaves differently? No
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Create mini.vim with:
```
set nocompatible

filetype plugin indent on
syntax on

set termguicolors
set laststatus=2
set autoread
set updatetime=300

autocmd FocusGained,BufEnter,CursorHold * checktime %
```

Open `tmp.js` with command:
```
nvim -u mini.vim tmp.js
```
Change `tmp.js` outside neovim:
```
echo "window.alert('test')" > tmp.js
```
Go back to `tmp.js`

### Actual behaviour

The file get reloaded, but without any buffer update events, including:

* `nvim_buf_lines_event`
* `nvim_buf_detach_event`

and `BufReadPost` autocmd, when using `checktime` command without `%`, the `BufReadPost` would fired so a plugin could detect the file get reloaded.

Vim would only fire `TextChanged` event on this situation.

### Expected behaviour

Fire either `nvim_buf_lines_event` or `nvim_buf_detach_event` after `:checktime`

Related vim issue: https://github.com/vim/vim/issues/3487

**Comment by justinmk** [comment]
@tonymec is correct, but `:help api-buffer-updates` is not part of the autocommand feature. API events are a separate mechanism, and by design are not restricted by the terms of `autocmd-nested`, `:noautocmd`, `'eventignore'`, etc.

@chemzqm Is this not the same as https://github.com/neovim/neovim/issues/8648 ?

**Comment by chemzqm** [comment]
Yes, the same, just need `checktime` with reload to send `nvim_buf_lines_event`
