### ISSUE TITLE
TUI: pos1/end do not work in tmux when server was started with kitty (because of $TERMINFO)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#9071]
When the tmux server gets started from kitty, `<Home>`/`<End>` is not recognized in Neovim.

I am using `tmux -f /dev/null -L new` to use tmux defaults and ensure there is a new session.

When running `tmux -f /dev/null -L new new nvim` from a urxvt terminal, Home/End keys are working, and also when attaching to this server from kitty (`tmux -f /dev/null -L new new nvim`).

But they are not recognized when the tmux server is started from a kitty terminal.

There are differences when using `nvim -V3log` (left is started from kitty, right is from urxvt):
```
< &term: builtin_screen
< Description: GNU Screen with 256 colors
< Aliases: screen-256color
---
> &term: screen
> Description: VT 100/ANSI X3.64 virtual terminal
> Aliases: screen
3661c3661
<   max_pairs                 pairs      = 65536
---
>   max_pairs                 pairs      = 64
3786a3787
>   E3                        = 
3788d3788
<   TS                        = 
3790,3800d3789
<   kDC3                      = 
<   kDC4                      = 
<   kDC5                      = 
<   kDC6                      = 
<   kDC7                      = 
<   kDN                       = 
<   kDN3                      = 
<   kDN4                      = 
<   kDN5                      = 
<   kDN6                      = 
<   kDN7                      = 
3803,3813d3791
<   kLFT3                     = 
<   kLFT4                     = 
<   kLFT5                     = 
<   kLFT6                     = 
<   kLFT7                     = 
<   kRIT3                     = 
<   kRIT4                     = 
<   kRIT5                     = 
<   kRIT6                     = 
<   kRIT7                     = 
<   kUP                       = 
```

So in the case of kitty `&term` is `builtin_screen`, while `screen` otherwise.

Related code:
https://github.com/blueyed/neovim/blob/b697e40347bffc3cf398075a7596b79a9a58fffe/src/nvim/tui/tui.c#L210-L218

In the case of kitty `terminfo_from_builtin` is used, while it is not for urxvt.

The problem appears to be in `unibi_from_term`, which uses `$TERMINFO` (which gets set by kitty), but `screen` is not in there (only xterm-kitty).

This is https://github.com/mauke/unibilium/issues/36.

However, this means that the `builtin_screen` is not behaving like when `TERM=screen` is handled correctly, although I cannot see it from the diff above.

**Comment by blueyed** [comment]
Is unibilium still maintained (last commit from Feb)?
Could we add the patch from https://github.com/mauke/unibilium/issues/36 maybe for Neovim?

**Comment by justinmk** [comment]
We could, but I think that makes life difficult for package maintainers.

This is why Vim inlines everything :)

**Comment by justinmk** [comment]
Is this unblocked since https://github.com/neovim/unibilium/pull/2 was merged?

**Comment by blueyed** [comment]
Yes, https://github.com/neovim/neovim/pull/10677 is expected to fix it then.
