### ISSUE TITLE
Regression for undercurl in gnome-terminal

### ISSUE THREAD

**Issue by fmoralesc** [neovim/neovim#9083]
- `nvim --version`: NVIM v0.3.2-634-g94e585944
- Vim (version: ) behaves differently? NA
- Operating system/version: Arch Linux
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Enable spelling in a file with incorrect words.

### Actual behaviour

The mispellings are underlined by a horizontal line the color of the text.

### Expected behaviour

The mispellings are underlined by a red undercurl.

#9052 worked perfectly for me, but #9080 seems to have regressed the behavior.

**Comment by justinmk** [comment]
Can you suggest a patch?

**Comment by bfredl** [comment]
What was wrong with the original `unibi_add_ext_bool` ? I don't see any rationale for #9080 anywhere, why should this boolean flag be treated differently from every other boolean flag that didn't need this?

**Comment by justinmk** [comment]
I don't know, @blueyed said it fixed something :)

**Comment by fmoralesc** [comment]
I think it was meant to fix the tmux case...

I'm sorry I can't look at it now... I was really happy with the undercurl
feature yesterday, and today I was a bit disappointed after I recompiled :p

**Comment by bfredl** [comment]
> But isn't it odd to use unibi_add_ext_bool as a check for existence?

Looking at the docs you seem to be right, it returns an index, not a bool. So the issue is rather that `xterm-256color` which libvte identifies itself as doesn't announce the capability (I guess xterm itself doesn't add it). So we will need to add a positive detection based on libvte verion, I guess.

**Comment by justinmk** [comment]
Would it hurt anything to _always_ do `ext.set_underline_color` ? (Or, will it help more than hurt?)

**Comment by bfredl** [comment]
I don't know. But I think the issue is primarily with the undercurl sequence. If a terminal doesn't recognize `\x1b[4:3m`, changes are it will display nothing rather that falling back to a plain underline.

**Comment by blueyed** [comment]
> So the issue is rather that xterm-256color which libvte identifies itself as doesn't announce the capability (I guess xterm itself doesn't add it). So we will need to add a positive detection based on libvte verion, I guess.

I agree.

> Would it hurt anything to always do ext.set_underline_color ?

Do you mean `ext.enter_undercurl_mode`?
But I agree that we should use the feature detecting, if it is available / planned like this.

btw: there is discussion at https://github.com/tmux/tmux/issues/1492 to use something like `smulx` for this (at least within tmux).

**Comment by blueyed** [comment]
=> https://github.com/neovim/neovim/pull/9088
