### ISSUE TITLE
Weird characters appearing right after starting neovim or when editing lines

### ISSUE THREAD

**Issue by tecywiz121** [neovim/neovim#9089]
- `nvim --version`: NVIM v0.3.2-dev
- `dpkg-query -W neovim`: `0.3.0~ubuntu1+git201810042052-c1c5c4f-479a1d0-97cfcfb~ubuntu14.04.1`
- Operating system/version: Ubuntu 14.04.5 LTS
- Terminal name/version: GNOME Terminal 3.6.2
- `$TERM`: `xterm-256color`
- `$VTE_VERSION`: `3409`

### Original Report

https://www.reddit.com/r/neovim/comments/9la6mu/weird_characters_when_opening_nvim_with_u_norc/

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/135535/46539756-64ac0200-c885-11e8-94c7-e54ba85dd4bf.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/135535/46539632-067f1f00-c885-11e8-9714-3fde1423f438.png)

**Comment by justinmk** [comment]
Can someone bisect?

**Comment by MichaHoffmann** [comment]
I'll try!

**Comment by tecywiz121** [comment]
I hope you don't mind @MichaHoffmann, but I ended up doing a bisect as well. Looks like 7f990741f7018b5e52833f2da6913b97c6d2d5ee is the first bad commit.

```
git bisect start
# good: [949bcd7810d0fe355d4c6afa5d3ff58a15359673] Merge pull request #8992 from bfredl/cmd-snr
git bisect good 949bcd7810d0fe355d4c6afa5d3ff58a15359673
# bad: [8fd092f3ff15bf70f84ec0d716c5aaa2c7379fa1] vim-patch:8.1.0476: memory leaks in test_escaped_glob (#9127)
git bisect bad 8fd092f3ff15bf70f84ec0d716c5aaa2c7379fa1
# bad: [458a6f58b67298ad3df276ffcc525eb3b32b8a56] globals: arg_had_last is bool
git bisect bad 458a6f58b67298ad3df276ffcc525eb3b32b8a56
# good: [ecdd2df88ab52ed6e39057e2a8fb9eabfbb90bd5] shell/logging: Fix E730 with verbose system({List}) #9009
git bisect good ecdd2df88ab52ed6e39057e2a8fb9eabfbb90bd5
# bad: [1a1164339a07fb0555dfcd0f3ea76b718fb8673c] Merge pull request #9039 from blueyed/undercurl
git bisect bad 1a1164339a07fb0555dfcd0f3ea76b718fb8673c
# bad: [a52c38d79049000577320e11bd88b82852f2cfe6] vim-patch:8.1.0414: v:option_old is cleared when using :set in OptionSet autocmd
git bisect bad a52c38d79049000577320e11bd88b82852f2cfe6
# good: [efbc33cbbc030df3478d051502d1c14c1c73b3df] vim-patch:8.1.0310: file info msg with 'F' in 'shortmess'
git bisect good efbc33cbbc030df3478d051502d1c14c1c73b3df
# bad: [c236e80cf3dfae6df5c43ecfb19c7629c9884f7b] Merge pull request #9024 from bfredl/embed_ui2
git bisect bad c236e80cf3dfae6df5c43ecfb19c7629c9884f7b
# bad: [4da5cb38d396d76d8072815d150725f7c9a85078] startup: always wait for UI with --embed, unless --headless also is supplied
git bisect bad 4da5cb38d396d76d8072815d150725f7c9a85078
# bad: [7f990741f7018b5e52833f2da6913b97c6d2d5ee] TUI: Reset cursor color when applicable #8572
git bisect bad 7f990741f7018b5e52833f2da6913b97c6d2d5ee
# first bad commit: [7f990741f7018b5e52833f2da6913b97c6d2d5ee] TUI: Reset cursor color when applicable #8572
```

**Comment by teto** [comment]
This vte/ubuntu versions are old, the cursor color may not be supported yet (since this seems to be what triggers the error).
Also the term is wrong, declaring xterm when you are using gnome-terminal but once again older versions might have done this.

**Comment by etorth** [comment]
Vim has same issue

**Comment by chrisbra** [comment]
This usually happens when vim does not detect the terminal correctly or $TERM is forcefully set to xterm even when it is not. So try setting the $TERM or term option correctly

**Comment by tecywiz121** [comment]
I checked the following for anything that manually sets `$TERM`:

 * `~/.profile`
 * `~/.bashrc`
 * `~/.bash_profile`

Anywhere else I should look for something setting `$TERM`?

**Comment by tecywiz121** [comment]
If I run the commands:

```
export TERM=
gnome-terminal --disable-factory -e 'nvim -U NORC'
```

Then in the new nvim instance `:echo $TERM` prints `xterm`.

I really don't think I'm messing with `$TERM` anywhere.

**Comment by jamessan** [comment]
Just to be clear, no one meant that _you_ were changing `$TERM`.  gnome-terminal has historically not let the user change what `$TERM` it uses and hard-coded it to `xterm`.  In more recent versions, they've now allowed it to be configured at build time, but last I checked there still wasn't a run-time mechanism to set the proper `$TERM`.

The best option is to upgrade to something more recent than Ubuntu Trusty/14.04.  If that isn't something you're in a situation to do, then we may be able to blacklist old VTE versions (once we find the relevant version information).  However, that won't help in situations where you're using gnome-terminal locally but nvim over ssh, since the way we detect VTE-based terminals/gnome-terminal doesn't survive default configured SSH connections.

**Comment by tecywiz121** [comment]
I believe @MichaHoffmann said that they couldn't reproduce with that VTE version.

**Comment by MichaHoffmann** [comment]
hey, sorry i did not get to bisecting the issue… its been a long week.

**Comment by Shellcat-Zero** [comment]
For anyone else arriving here from Google, the fix that worked for me was `set guicursor=` in init.vim, as suggested in https://github.com/neovim/neovim/issues/5999#issuecomment-314166311, after experiencing this issue on NVIM v0.6.0-dev+164-g50b30de20.

**Comment by justinmk** [comment]
Also mentioned in the FAQ. https://github.com/neovim/neovim/wiki/FAQ

---
_Locked to keep the summary visible. You can always [chat](https://neovim.io/#chat) or open a ticket if you have new information/topics to discuss._
