### ISSUE TITLE
Problem with Ubuntu Snap packages

### ISSUE THREAD

**Issue by 1995parham** [neovim/neovim#9093]
- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently? v0.3.0
- Operating system/version: Ubuntu 18.04
- Terminal name/version: zsh
- `$TERM`: xterm-256color-italize

### Actual behavior
When using the following command:
`!go`
it runs snap command instead of Go command.

**Comment by 1995parham** [comment]
I think app image cases this issue and it isn't relating to Neovim.

**Comment by 1995parham** [comment]
Sorry for reopening this issue, but members of the AppImage team think you can provide more help. As I said [here](https://github.com/AppImage/AppImageKit/issues/861) when I call `!go` in the AppImage release of Neovim 3.1.1 in Ubuntu 18.04 it runs snap command instead of Go command. I installed Go with Ubuntu snap.

**Comment by justinmk** [comment]
snap (I guess?) was added in https://github.com/neovim/neovim/pull/7918 . I don't use it and have no interest in it. Someone else (@kalikiana) needs to maintain it or it will be removed.

**Comment by 1995parham** [comment]
Thanks for your reply, But I installed AppImage release of Neovim but I had to install Go with the snap.

**Comment by justinmk** [comment]
@TheAssassin Ah that explains it, thanks. Though I am pretty sure Nvim doesn't do that, it merely sends the `:!...` command string to `bash -c '...'` via `system()` or whatever.

**Comment by 1995parham** [comment]
I can correct the problem by changing the Neovim shell to `/bin/bash\ -l`.

**Comment by justinmk** [comment]
And what about if you rename your .profile, .bashrc, etc? Sounds like an environment/config issue unrelated to Nvim.

**Comment by 1995parham** [comment]
Yes, I think this is related to environment variables and not related to Neovim. Thanks for your help.
