### ISSUE TITLE
Crash on funcref in skipped code

### ISSUE THREAD

**Issue by dbarnett** [neovim/neovim#912]
I ran into a strange crash in neovim when dead code would have called a function reference. You can reproduce by typing the following code in an nvim session:
```VimL
:if 0
:  call function('foo')()
:endif
```
which immediately crashes neovim (before it even reaches the `:endif`, in fact).

**Comment by noahfrederick** [comment]
FWIW, I can't reproduce the crash in current master (a7aeda8c7a3b2c9854d40c1c9278fd67d94aaf3d).

    :version
    NVIM 0.0.0-alpha+201503090801 (compiled Mar  9 2015 17:10:20)
    Commit: a7aeda8c7a3b2c9854d40c1c9278fd67d94aaf3d
    Build type: RelWithDebInfo

**Comment by dbarnett** [comment]
Me neither. Glad it's fixed, whatever ended up fixing it.
