### ISSUE TITLE
CursorHoldI doesn't trigger if Nvim loses focus

### ISSUE THREAD

**Issue by justinnhli** [neovim/neovim#9125]
The `CursorHoldI` autocmd event doesn't trigger if the terminal loses focus. It works normally if I remain in terminal/nvim, but if I switch to a broswer (for example), the autocmd never triggers.

- `nvim --version`: NVIM v0.3.2-69-ga225374
- Vim (version: 7.3) behaves differently? Yes
- Operating system/version: OS X 10.10.5
- Terminal name/version: Kitty 0.12.0 ([patched for OSX 10.10](https://github.com/justinnhli/kitty/tree/osx10.10.0))
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set updatetime=4000
:autocmd CursorHoldI * echom nonexistent
i
```

Once you've entered insert mode, switch to a different application for more than 4000ms. 

### Actual behaviour

Nothing happens

### Expected behaviour

An error about the non-existent variable `nonexistent`:

```
Error detected while processing CursorHoldI Auto commands for "*":
E121: Undefined variable: nonexistent
Press ENTER or type command to continue
```

**Comment by muniter** [comment]
Cannot reproduce on 0.6


https://user-images.githubusercontent.com/9699804/134821733-c139e028-aaba-4d5e-9034-a885b52e4238.mp4
