### ISSUE TITLE
silent! should be disregarded if prompting for user input

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#9133]
- `nvim --version`:  v0.2.3-935-g88e62f239
- Vim (version: 8.0) behaves differently? no
- Operating system/version: WSL N/A
- Terminal name/version: kitty N/A
- `$TERM`: xterm-kitty N/A

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC ./foo
:w
^Z # suspend nvim
nvim -u NORC 
silent! e ./foo
```

### Actual behaviour
neovim appears to hang indefinitely; in reality it is waiting for a response to the suppressed "swap file exists" recourse prompt.

This is less obvious when not manually executing the command in question, e.g. when using the fzf plugin to load a file or when using a.vim to open the alternate file, both of which use `silent!` before creating a new buffer to load the chosen file into.

### Expected behaviour
Either input should be buffered when `silent!` until a prompt, in which case it is printed before prompting, or the prompt should take some default action, etc. such that user input is not needed.

**Comment by justinmk** [comment]
For swapfiles this was addressed by https://github.com/neovim/neovim/pull/9034 .

For other input dialogs it's `wontfix`.

**Comment by mqudsi** [comment]
Thanks. #9034 looks good.
