### ISSUE TITLE
space appearing/disapearing after insertion on end of line with emoji

### ISSUE THREAD

**Issue by solsticedhiver** [neovim/neovim#9137]
Using neovim v0.3.1-1-g489d32f2b on ubuntu, a simple file like:

    😳 🤦 🕳️ 

Then when I try to add text after those emojis, a space is added at the end of the line (if using A). And then when the file is saved the space is gone.
If I use CTRL-L to force a redraw, one can see the space disappear.

So why is there a space added in the first place, while there should be none ?
It is has if something is wrong with the characters because of the unicode characters.

Note: the file is opened as utf-8

**Comment by justinmk** [comment]
cannot reproduce on `NVIM v0.3.2-826-g87d67814e`

**Comment by solsticedhiver** [comment]
The problem is still there with v0.3.2-827-ga6661178a

So may be I should explain a little better.

Just have a line with emojis like above.
Then type some text after them. Hit CTRL-L, then you will see the text shifting to the left overwriting the last emoji.

If you reload the file, the text is still drawn over the last emoji. It should not as the text was appended after the emojis with `A`.

This is not limited to space. It is just mishandling of utf-8/unicode characters or something like that.

**Comment by solsticedhiver** [comment]
So that's very weird.
I use gnome-terminal 3.30.1-1ubuntu1 but it happens too in termit 3.0-1

What is weird is that it is the hole emoji (U+1F573) 🕳 that does that. Be it inserted by pasting, or with `CTRL-SHIFT U 1F573`

I have tried other emojis and did not encounter that behavir so far.
