### ISSUE TITLE
Appimage missing on latest pre-release

### ISSUE THREAD

**Issue by stsewd** [neovim/neovim#9151]
- `nvim --version`: 0.3.2-dev
- Vim (version: ) behaves differently?
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Actual behaviour

There isn't an appimage for the latest pre-release https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage (404)

![screenshot_2018-10-23 neovim neovim](https://user-images.githubusercontent.com/4975310/47372212-e934b800-d6ae-11e8-8e56-997894ab21aa.png)

### Expected behaviour

There is an appimage

**Comment by justinmk** [comment]
See the latest run of bot-ci: https://travis-ci.org/neovim/bot-ci/branches

The linux nightly job failed with:

```
upload_nightly: delete_old=delete filepath=/home/travis/build/neovim/bot-ci/build/nightly.tar.gz uploadname=nvim-linux64.tar.gz
Deleting old release assets
Error calling repos/neovim/neovim/releases/assets/9348008 (DELETE): Server Error.
Updating release description.
```

I restarted the job, should be done in 20 minutes.

**Comment by stsewd** [comment]
@justinmk thanks!
