### ISSUE TITLE
BCE issue in WSL conhost

### ISSUE THREAD

**Issue by mqudsi** [neovim/neovim#9153]
- `nvim --version`: NVIM v0.3.2-728-g092344309
- Vim (version: ) behaves differently? N/A
- Operating system/version: WSL N/A
- Terminal name/version: conhost, kitty
- `$TERM`: xterm-256color, xterm-kitty

#7624 (and possibly others) had appeared to address my problems with BCE, but I've been running into the same issue again under both conhost and kitty, with `TERM` both `xterm-256color` and `xterm-kitty` (properly installed), with the same basic problem case (`<c-b>`/`<c-f>` are OK, scrolling line-by-line is not).

It seems to be a trickier variant of the original problem, as I'm not able to reproduce it strictly 100% of the time (I failed to bisect it because it seems I prematurely flagged a revision as "good").

**Comment by mqudsi** [comment]
OK, I can definitively say that https://github.com/neovim/neovim/pull/8806 broke this again.

**Comment by mqudsi** [comment]
I verified under WSL.

**Comment by bfredl** [comment]
Can I have a screenshot? I tested very quickly with kitty, and see no problems with scrolling (with colorscheme that sets Normal guibg). Possibly is resize a bit glitchy, but it always reaches the correct final state.

**Comment by bfredl** [comment]
> but kitty only reproduces in special circumstances.

I need to know the specific circumstance, otherwise I can't do much.

> I can always reproduce with scrolling under conemu

Is `xterm-256color` the default `$TERM` for conemu, or does it allow identification by some other means (own env var)? Then we can try blacklist it like kitty.

**Comment by mqudsi** [comment]
> I need to know the specific circumstance, otherwise I can't do much.

Yes, I realize that. I'll let you know when I find something reproducible.


> Is `xterm-256color` the default `$TERM` for conemu, or does it allow identification by some other means (own env var)? Then we can try blacklist it like kitty.

Yes, Microsoft has been pretty adamant about "let's not detect wsl and act differently, instead strive to aim for perfect compatibility," but, well, they're not there yet. 

Some installations/versions of WSL have an exported variable `WSL_ENV` but most don't. In all cases, these wouldn't be available in, say, an SSH session to a Real Linux machine running neovim.

**Comment by bfredl** [comment]
When you say conemu, do you mean https://conemu.github.io/ or rather windows own terminal emulator, i e conhost?

**Comment by mqudsi** [comment]
The latter. Stock bash.exe under WSL.

**Comment by bfredl** [comment]
> Yes, Microsoft has been pretty adamant about "let's not detect wsl and act differently, instead strive to aim for perfect compatibility," but, well, they're not there yet.

But that is for running under WSL vs running under a linux kernel, AFAIK. You could run an xterm inside WSL, or from a conhost terminal ssh into a "real" linux session. (not that non-TERM term variables get automatically copied by SSH, but one can fake it manually). What I need is an indicator for conhost, not one for WSL.

**Comment by bfredl** [comment]
Also MS claims to have fixed BCE in conhost, https://github.com/Microsoft/WSL/issues/1706#issuecomment-308570429. But they could of course missed yet a special case.

**Comment by mqudsi** [comment]
I’m reproducing the issue under 17763 which is freshly minted.

**Comment by bfredl** [comment]
I think we should just change implementation of scrolling to never rely on the state of the scrolled-in area:
- the abstract `grid_scroll` event leaves the state of the scrolled in area _undefined_. `screen.c` promises to to fill in the area with `grid_line` events before the next flush. 
- For a non-BCE terminal this makes redrawing _strictly_ more efficient. Instead of filling the entire area with spaces, and then drawing text on top, we just need to pad the unused area with spaces.
- For a BCE terminal we use ce or ec (the later not implemented yet) to pad each line. This mean one extra sequence per line at maximum, which should be acceptable. We then only rely on the BCE terminal implementing _explicit_ clearing sequences correctly, never implicit clearing with scrolling, newlines or anything.
- A GUI client can then implement `grid_scroll` as a single copy.

This also makes sense when considering `winhl=Normal:MyBackground` windows. For these windows the implicit clearing in `grid_scroll` is useless anyway, and the unused area needs to be cleared an extra time.

**Comment by mqudsi** [comment]
fwiw, terminal.app under macOS Yosemite 10.10 (old version, I know) has background painting problems after `:colo`. It's probably both safe and not a performance issue to force a full repaint after the color scheme is changed.

**Comment by bfredl** [comment]
"full repaint" is what the current code should do already when background color changes. Hard to investigate further with not at least a screenshot.

**Comment by mqudsi** [comment]
Sorry, I thought it did the repaint via BCE. It's the same as my typical BCE problem: cells without characters have the wrong background color.

Before executing the command visible in the status bar (switching from `afterglow` to `0x7A69_dark`):
<img width="697" alt="screen shot 2018-10-31 at 5 46 53 pm" src="https://user-images.githubusercontent.com/606923/47823223-35c66600-dd35-11e8-855f-201d65fa8eb9.png">

After executing the command that was visible in the status bar:
<img width="697" alt="screen shot 2018-10-31 at 5 47 03 pm" src="https://user-images.githubusercontent.com/606923/47823227-3f4fce00-dd35-11e8-8d09-6ec73b39103a.png">

After ctrl+L:
<img width="697" alt="screen shot 2018-10-31 at 5 47 08 pm" src="https://user-images.githubusercontent.com/606923/47823236-4ecf1700-dd35-11e8-9579-d104cce92bb1.png">

**Comment by bfredl** [comment]
> Sorry, I thought it did the repaint via BCE. 

It _happens_ to be BCE-free on master, but for terminals that report BCE (and are not blacklisted), we could implement more efficient repainting that uses ce and ec.

**Comment by bfredl** [comment]
See your "neovim 0.3.1" edit now, please try latest master. If it works on master there is nothing to fix..

**Comment by mqudsi** [comment]
Ok, I can confirm that the macOS 10.10 `colo` issue is gone in `master`. My point was that changing the colorscheme is not part of "normal" editor activity that needs to be optimized, and it would be better to err on the side of caution and not use ce/ec (as is now the case) rather than to do so.

I guess now that `master` is working here at least this is documented so that future efforts to optimizing background paint can know to be wary of this particular test case.

**Comment by bfredl** [comment]
> and it would be better to err on the side of caution and not use ce/ec (as is now the case) rather than to do so.

Missing the point. `ce` is safe in "normal" operation if and only if it is safe when "repainting", the terminal emulator cannot care less. _Avoiding_ a special case for repainting is not somehow "unnecessary optimization", it is just avoiding a special case, and less opportunity for bugs in total. The _only_ way to fix BCE bugs is to detect which terminal support what operations correctly, not doing the same operation in multiple ways in the same terminal.

**Comment by justinmk** [comment]
can this be closed?

**Comment by bfredl** [comment]
There might still be the conhost issue. Based on the report, I think conhost implements the _implicit_ clearing of scrolling wrong, even if they support BCE for any explicit clearing operation (hence my suggestion of only relying on explicit clears). Still, a screenshot to confirm would be nice.

**Comment by bfredl** [comment]
> I'm not sure what the point of providing a screenshot for every platform/terminal I experience this under is,

The point is not to show _that_ it is wrong, but _how_ it is wrong, which is needed to effectively fix the issue.

> Note that the problem isn't with the scroll back buffer, this was skipping forward in the file to a section that hadn't been loaded.

The issue is not with the scrollback buffer, but with scrolling regions. Even when `ctrl-f` is used, a few lines are shared, thus lines 37 and 38 in the screenshot are not redrawn, just moved. The screenshot confirms what I suspected, that conhost doesn't do BCE for the implicit clearing of scrolled-in area, so we should switch to use `ce` also after a scroll, as ce works correctly (otherwise line 37 wouldn't be correct...)

**Comment by mqudsi** [comment]
@bfredl The problems reported in #9193 are still present in `v0.4.0-254-g5e44a5945`. Video attached.


[2019-02-12 13-49-23.zip](https://github.com/neovim/neovim/files/2857433/2019-02-12.13-49-23.zip)

**Comment by justinmk** [comment]
Still an issue?

**Comment by dundargoc** [comment]
@mqudsi Still an issue # 2?

**Comment by justinmk** [comment]
I'm guessing this can be closed, we switched from winpty since this was reported.

**Comment by mqudsi** [comment]
@justinmk After I ran into all the repeated BCE issues, I set my terminal background color and my neovim background color to the same value to work around the problem after a fashion. When you pinged me two months ago, I set them differently and figured I'd give it a few days to be able to verify whether or not the issue is fixed, but completely forgot to report back.

You can guess why I forgot: everything is working smoothly and I haven't experienced any BCD issues or any other repaint problems. This is under both conhost and kitty.

Thanks to all for the ever-improving quality of the codebase!
