### ISSUE TITLE
neovim (nightly) not compiling with gcc 4.4.6

### ISSUE THREAD

**Issue by skrisna** [neovim/neovim#9160]
- `nvim --version`: N/A
- Vim (version: ) behaves differently? N/A
- Operating system/version: Linux 4.9.124, gcc-4.4.6
- Terminal name/version: N/A
- `$TERM`: N/A

### Actual behaviour
I compiled neovim-0.3.1 recently without issues using gcc-4.4.6. I then tried to do the same with the latest neovim commit (112a5b76e). The make command and the resulting error message are given below:

```
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/home/ec2-user/local/opt/neovim-v0.3.2rc -DCMAKE_BUILD_TYPE=Release"
```
```
# Error msg
[ 48%] No patch step for 'libvterm'
[ 50%] No update step for 'libvterm'
[ 51%] No configure step for 'libvterm'
[ 52%] No build step for 'libvterm'
[ 53%] Performing install step for 'libvterm'
make[4]: Entering directory `/home/ec2-user/code/neovim/.deps/build/src/libvterm'
TBL src/encoding/DECdrawing.tbl
TBL src/encoding/uk.tbl
CC src/encoding.c
cc1: error: unrecognized command line option "-Wpedantic"
make[4]: *** [src/encoding.lo] Error 1
make[4]: Leaving directory `/home/ec2-user/code/neovim/.deps/build/src/libvterm'
make[3]: *** [build/src/libvterm-stamp/libvterm-install] Error 2
make[3]: Leaving directory `/home/ec2-user/code/neovim/.deps'
make[2]: *** [CMakeFiles/libvterm.dir/all] Error 2
make[2]: Leaving directory `/home/ec2-user/code/neovim/.deps'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ec2-user/code/neovim/.deps'
make: *** [deps] Error 2
```
The entire error log is attached.

### Expected behaviour
No errors during make. Successful compile.
[log.txt](https://github.com/neovim/neovim/files/2521498/log.txt)

**Comment by teto** [comment]
gcc 4.4.6 is quite old (https://www.gnu.org/software/gcc/gcc-4.4/ => 2012), no way you can update it ? 
else you have to remove the -Wpedantic, not sure how easy it can be.

**Comment by jamessan** [comment]
Detecting whether we can use `-Wpedantic` would be pretty straight-forward for our _own_ build files.  However, that specific error is coming from one of our third-party dependencies.

@skrisna Can you use the AppImage build that we provide?

**Comment by justinmk** [comment]
The Neovim build automatically builds dependencies as a convenience.  If your system can't build those, then you can set `USE_BUNDLED=NO` and install the required dependencies using your system package manager.

Or you can use the pre-built appimage as mentioned. https://github.com/neovim/neovim/releases

**Comment by skrisna** [comment]
Thanks a lot. I will try using the pre-built app-image. Tx.

**Comment by skrisna** [comment]
The pre-built app from https://github.com/neovim/neovim/releases does not
work  - I tried nvim-linux64.tar.gz. I am getting this error:
./nvim: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by
./nvim)
./nvim: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by
./nvim)

I will try the USE_BUNDLED=NO option as you suggested. Changing the gcc is
not an option, unfortunately.

Tx.

**Comment by skrisna** [comment]
If someone else is facing this issue, I was able to solve this issue as follows -- 

```
# https://github.com/neovim/neovim/wiki/Building-Neovim#third-party-dependencies
mkdir .deps
cd .deps
cmake ../third-party
make
```

It fails while installing libvterm. Edit `build/src/libvterm/Makefile` and remove `-Wpedantic` from the the gcc command. Continue with `make` and let it complete. 

After this, go back to the parent directory and run the make command as usual. In my case, it is - 

```
make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=<prefix> -DCMAKE_BUILD_TYPE=Release"
make install
```

This worked without issues. 

Thanks for all the help.
