### ISSUE TITLE
Windows GUI : Opens an empty nvim-qt window instead of opening the file passed as argument

### ISSUE THREAD

**Issue by saurabhsangpal** [neovim/neovim#9165]
- `nvim --version`: 0.3.1 RelWithDebInfo
- `Compiled by`: appveyor@APPVYR-WIN
- `Vim (version: 8.1 64 bit)` works as expected.
- Operating system/version: Windows 10 Pro

### Actual behavior
Opens an empty nvim-qt window when we pass a filename as argument.
### Expected behavior
Should open the file in nvim-qt.

![one](https://user-images.githubusercontent.com/43683481/47617283-7df24800-daeb-11e8-96c5-0c9553ce5c8d.JPG)
![two](https://user-images.githubusercontent.com/43683481/47617286-85195600-daeb-11e8-9830-4ed97662dee5.JPG)
![three](https://user-images.githubusercontent.com/43683481/47617288-88acdd00-daeb-11e8-8628-06113af784d1.JPG)
![four](https://user-images.githubusercontent.com/43683481/47617289-8c406400-daeb-11e8-927c-a2986a6f12f1.JPG)
![five](https://user-images.githubusercontent.com/43683481/47617292-8e0a2780-daeb-11e8-95e3-53808913ef52.JPG)
![six](https://user-images.githubusercontent.com/43683481/47617293-91051800-daeb-11e8-9698-11d9527d7893.JPG)

**Comment by justinmk** [comment]
What does `:ls!` show?

Most likely this is https://github.com/equalsraf/neovim-qt/issues/417 which was fixed but requires the latest HEAD of nvim-qt and nvim.
