### ISSUE TITLE
provider: code intel (navigation, refactoring)

### ISSUE THREAD

**Issue by tarruda** [neovim/neovim#917]
I'm currently experimenting with #895 and a [custom YouCompleteMe branch](https://github.com/tarruda/YouCompleteMe/tree/nvim-support) that uses API events to provide asynchronous completions using a mechanism similar to [this one](https://gist.github.com/tarruda/e33a5b87c0b1bfdf9beb).

Other than some bugs with the python client(which is why I didn't merge #895 yet), it's working very smoothly, even for big files like eval.c where YouCompleteMe normally starts to hang(completions/errors may take a while to popup for big files, but they never block the UI)
#895 introduces the concept of service providers to Neovim, and this could be used to expose extension points for plugins implementing real-time "code intel" features such as:
- completion
- highlighting(ref #719)
- code analysis
- jumping/finding code constructs
- code formatting/folding(?)

These features must be implemented with asynchronous APIs so the editor will never block while the plugin is doing it's job of parsing/analysing the file. I opened this thread for discussing what interface these "code intel providers" should have.

It would be great to have input from @Shougo / @Valloric which have experience in the field.

**Comment by Shougo** [comment]
I implemented async auto completion using neovim remote APIs https://github.com/Shougo/deoplete.nvim.

**Comment by torpak** [comment]
I said this before in a different (not so fitting) issue:
Wouldn't it be good to define a single api as an interface between language agnostic folding, coloring, autocompletion, error/warning-display,... plugins on one side and syntax/semantic-aware language-backends that provide the needed information on the other side. 
At the moment for example there is exactly one plugin, that does c++ autocompletion right: YCM it can not do coloring, it only does rudimentary error/warning display and it implements all it's own frontend.
Then there is color_coded, which can do syntax aware coloring for c++ but it can not use the same ast, even though both use libclang.
So the code is needlessly parsed twice.
If you want acurate Error and warning information (YCM ignores some errors to speed up parsing), you would need a third plugin to parse the code yet again.

I think it would be better if there was one backend for c++ that provides the information and features all those usecases need, and one for python, lua,...
We would need in such an api:
* A hook to locally configure the backend via some kind of project file, so it can do useful preprocessing and cacheing (in the background).
* Some kind of language neutral ast abstraction for coloring.
* A position aware completion hook for autocompletion.
* A call that delivers detailed error/warning information with positions and cross references for useful diagnostics.
* Optionally calls for simple refactorings (rename, extract function/local)

The great benefit would be that someone wanting to support a new programming language would not have to think of their own api and ui. And someone who just wants completion with a different look and feel wouldn't need to implement their own language backends.
And the code wouldn't have to be parsed quite so often.

**Comment by justinmk** [comment]
See also https://github.com/neovim/neovim/issues/5522

**Comment by justinmk** [comment]
Closed by #5522 .

Further enhancements such as hooks for following l filtering completions, or new presentation/layout ideas, should go in dedicated tickets.
