### ISSUE TITLE
stop including vim.h in header files

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#918]
While trying to fix the Lua header file cacher and hitting more snags than I anticipated, I investigated. I can't even verify it 100% with some issues (that should tell us something), but many problems are caused by header over-inclusion and clever header tricks. For example, including `vim.h` is often problematic. It happens a few time that a file includes `vim.h` and `vim.h` includes that file. It mostly works by accident.

The reasons these problems come forward in test code and not in the main binary is because it includes only what it needs to test (for example `buffer.h`). This should be sufficient, but inside of the binary, `vim.h` is often included one way or another before `buffer.h`. Some thing included by this file relies on `vim.h`, thus the test explodes while the main binary doesn't.

I hope to be able to fix the headers to such a level that we can run more tests, but it won't solve the problem (this is almost impossible to do in one PR without an automated tool, I think). But we should at least stop the problem from exacerbating. Two easy-to-remember bullet points that go for **any new files or files you are refactoring**:

- for the `.h` portion of a new module, only include the bare minimum. For example, if you need `size_t`, include `stddef.h`, not `vim.h`.
- don't forget to check what might be needed by the `*.h.generated.h` file. This basically boils down to: make sure you have properly included all the scalar types pass to functions defined in the `*.c` file. For example: `size_t foobar(time_t time) { /* ... */ };`. In the corresponding `.h` file you will need to include both `stddef.h` and `time.h`.

This issue will probably be corrected, I'm just writing a stream of thoughts now as I debug this problem. Comments more than welcome. 

ref: #904.

**EDIT 1**: if you want to find out what you header file is including, you can use the `-H` switch on gnu-like compilers such as gcc and clang:

```bash
$ cd github/aktau/neovim
# ignore header files in /usr/* as we don't control them anyway and they make the output hard to read
$ (echo '#include "./src/nvim/buffer.h"' | clang -I.deps/usr/include -Isrc -std=c99 -P -E -H - 2>&1 1>/dev/null | grep -v '/usr/'
```

Output:

```
. ././src/nvim/buffer.h
.. src/nvim/ex_cmds_defs.h
... src/nvim/pos.h
... src/nvim/normal.h
.... src/nvim/buffer_defs.h
..... src/nvim/garray.h
...... src/nvim/log.h
..... src/nvim/option_defs.h
...... src/nvim/types.h
..... src/nvim/mark_defs.h
..... src/nvim/undo_defs.h
..... src/nvim/hashtab.h
...... src/nvim/vim.h
....... src/nvim/memory.h
....... src/nvim/os_unix_defs.h
....... src/nvim/ascii.h
....... src/nvim/keymap.h
....... src/nvim/term_defs.h
....... src/nvim/macros.h
....... src/nvim/buffer_defs.h
....... src/nvim/ex_cmds_defs.h
....... src/nvim/globals.h
........ src/nvim/ex_eval.h
........ src/nvim/mbyte.h
........ src/nvim/menu.h
..... src/nvim/eval_defs.h
..... src/nvim/memline_defs.h
...... src/nvim/memfile_defs.h
..... src/nvim/regexp_defs.h
..... src/nvim/syntax_defs.h
..... src/nvim/sign_defs.h
..... src/nvim/os/fs_defs.h
```

Quite quickly we see that `hashtab.h` includes `vim.h`. That might be something we can help...

**Comment by justinmk** [comment]
Covered by #549
