### ISSUE TITLE
<c-c> can be mapped but g<c-c> cannot be mapped

### ISSUE THREAD

**Issue by liushapku** [neovim/neovim#9185]
- `nvim --version`: neovim 0.3.1
- Vim (version: ) behaves differently?  neither `<c-c>` and `g<c-c>` can be mapped
- Operating system/version: ubuntu 14.04
- Terminal name/version: xtem
- `$TERM`: xtem-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

map <c-c> :<c-u>echo 1<cr>
map g<c-c> :<c-u>echo 2<cr>
```

### Actual behaviour
typing `<c-c>` can display the number 1.
typing `g<c-c>` displays `Type :qa! and press <Enter> to abandon all changes and exit Nvim`

### Expected behaviour
display 1 and then display 2

**Comment by justinmk** [comment]
ctrl-c I'd the only way to cancel a mapping, script, etc. It will take some effort to figure out what the user intended if ctrl-c is input after `g` . 

Not worth the effort. And you really shouldn't remap ctrl-c ...

**Comment by liushapku** [comment]
IMHO, there is also `g<esc>` to cancel the `g`, if `g<esc>` is not remapped.
remapping `g<c-c>` will not hinder the use of `<c-c>` to cancel a script.

I actually want to create a key mapping to interrupt a running job launched using `jobstart` by sending `<c-c>` to it. I feel a key involving `<c-c>` (such as `g<c-c>` or `<leader><c-c>` should be the most natural choice. Simply using `c-c>` to send this char to the channel may cause other inconvenience since `<c-c>` is used to cancel incomplete mappings and also running scripts.
