### ISSUE TITLE
Error detected while processing function <SNR>43_Match_wrapper[92]..<SNR>43_Wholematch:

### ISSUE THREAD

**Issue by olalonde** [neovim/neovim#9187]
- `nvim --version`:

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/config -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?
- Operating system/version: MacOS Mojave
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

When I `Shift-% ` on a matching character, e.g. `({[`, etc. I sometimes get this error:

```
Error detected while processing function <SNR>43_Match_wrapper[92]..<SNR>43_Wholematch:
line    5:
E872: (NFA regexp) Too many '('
E51: Too many \(
Error detected while processing function <SNR>43_Match_wrapper:
line   93:
E872: (NFA regexp) Too many '('
E51: Too many \(
```

I am not sure how to reproduce as it happens seemingly randomly. If I clone nvim and re-open on the same file the error usually disappears.

### Expected behaviour

No error.

**Comment by chrisbra** [comment]
I think this comes from the matchit plugin. Please try to come up with a reproducible example. It most likely depends on the file content as well as the cursor position. Then I can try to fix it in my version https://github.com/chrisbra/matchit (if it hasn't been fixed yet)

**Comment by justinmk** [comment]
Thanks for reporting. This bug is in the runtime plugins (which we import from Vim). We prefer not to track individual runtime-related issues in the Neovim issue tracker, because it's redundant with the Vim issue tracker and it adds an administrative cost. The issue will go away as soon as we merge the relevant runtime update from Vim.

**Comment by HarrisonB** [comment]
Do you know if this has been reported on the Vim issue tracker? I was unable to find anything.

**Comment by chrisbra** [comment]
If you can reproduce it with my latest version report it on my repository. I have seen this error once for  js files and it was the fault of another plugin that modified b:match_words 
But that should be fixed now.
