### ISSUE TITLE
spurious q characters still appear in newer release

### ISSUE THREAD

**Issue by s-sajid-ali** [neovim/neovim#9190]
- `nvim --version`: 0.3.1
- Vim (version: 7.4) behaves differently? Yes
- Operating system/version: RHEL 7.4
- Terminal name/version: ssh into a workstation, `/bin/bash` , version 4.2.46(2)-release
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:
```

### Actual behaviour
Spurious q character appears for no reason when trying to do anything. Same as https://github.com/neovim/neovim/issues/7049. Could not comment there so had to start a new issue. 
### Expected behaviour
Works as vim and no q symbols appear

I tried to see what my Vte version was and I see nothing : 
```
[sajid@xrm exercises]$ echo $VTE_VERSION

[sajid@xrm exercises]$ 
```
I'm not an admin and can't change `vimrc`.

**Comment by justinmk** [comment]
FAQ: https://github.com/neovim/neovim/wiki/FAQ#nvim-shows-weird-symbols-2-q-when-changing-modes

> I'm not an admin and can't change vimrc.

You can either use a different terminal, or set TERM correctly (see `:help $TERM`, mentioned in the FAQ), or use Vim.
