### ISSUE TITLE
:terminal Ctrl-L does not put cleared lines into scrollback

### ISSUE THREAD

**Issue by achalddave** [neovim/neovim#9199]
- `nvim --version`: v0.3.0
- Operating system/version: CentOS 7
- Terminal name/version:
- zsh / 5.0.2

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
> echo 1
1
> echo 2
2
> echo 3
3
[Hit C-l to clear screen]
```

### Actual behaviour
After clearing screen, the terminal history is deleted from the buffer entirely.

### Expected behaviour
In tmux and in most terminal emulators, `ctrl-l` just clears the "visible screen" and moves all but the current prompt beyond the visible screen, but keeps things around in the history. neovim seems to read `ctrl-l` as "delete all lines between the current line and the top of the screen".

**Comment by bfredl** [comment]
Do you exit terminal mode first? Otherwise the C-L is interpreted by zsh.

**Comment by achalddave** [comment]
No, I don't. Admittedly, this could be considered "an issue with the shell", but given that tmux, iterm, and other "shell containers" behave in one way when a user issues `ctrl-L`, I would expect neovim to behave the same way. Perhaps the easy fix is to have `ctrl-l` map to something that exits terminal mode, moves the buffer up, and re-enters terminal mode, like `<Ctrl-\><Ctrl-N>zta`, but this does not work as re-entering terminal mode just moves the buffer back into its original place.

**Comment by bfredl** [comment]
Could be a libvterm issue then. Does it work differently in xterm? (libvterm tries to model the common features of an xterm)

**Comment by leonerd** [comment]
This is all to do with altscreen. Most (I've no idea if "all" but at least every one I know) terminals will only append to the offscreen backbuffer when not in altscreen mode. This keeps the "command prompt" backscroll history separate from whatever fullscreen application (e.g. less or vim) you were running. Whatever Ctrl-L is doing, if the terminal is in fullscreen mode at the time, it wouldn't affect the buffer, but if not then it would.

Does that help?

**Comment by justinmk** [comment]
@leonerd But this issue is about the case where the window height was not exceeded. Notice the repro steps.

xterm and pangoterm have the same behavior as Nvim `:terminal`, as does Vim `:terminal`. 

The behavior requested by @achalddave is present in tmux and gnome-terminal. But not xterm.

If anyone wants to send a PR to implement this in Nvim or libvterm, please do. Otherwise this is `wontfix`.

P.S. @achalddave what terminal are you using (as requested by the issue template)?

**Comment by achalddave** [comment]
Oops, I somehow completely missed the terminal part of the template, my bad. I'm using iTerm2 on OSX.

**Comment by mkscrg** [comment]
Just stumbled into this. It's odd behavior, unlike any other (modern) terminal I've used. IMO `bug` is the correct label here!

**Comment by gegoune** [comment]
That isn't entirely true. Wezterm has exactly same behaviour and its author argues that it is correct one [here](https://github.com/wez/wezterm/issues/2405#issuecomment-1214400220) and [here](https://github.com/wez/wezterm/issues/2405#issuecomment-1279773701) while another user explains what's going [here](https://github.com/wez/wezterm/issues/2405#issuecomment-1214418211).
