### ISSUE TITLE
"clipboard: error invoking xclip: Error: Can't open display: :0" when nvim is started as $MANPAGER

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#9200]
I have set $MANPAGER to `nvim +Man!` in my shell, but whenever I run man ls¹, and try to yank something to clipboard, I get the error `clipboard: error invoking xclip: Error: Can't open display: :0`.
Running nvim normally and using the :Man command does not cause this error, and explicitly piping with `man ls | nvim +Man!` doesn't cause it to happen either.

¹ It happens with any man page, I just used ls as an example here.

- `nvim --version`:
```
NVIM v0.3.2-827-ga6661178a
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by luna@lunar-base

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? N/A
- Operating system/version: Ubuntu-MATE 18.04.1
- Terminal name/version: MATE Terminal 1.20.0
- `$TERM`: xterm-256color
- Clipboard provider: xclip 0.13

### Steps to reproduce using `nvim -u NORC`

```
MANPAGER='nvim -u NORC +Man!'
man ls # could be anything, though
# Any attempt to write to "+ or "* will fail.
# This will persist even if you try closing the manpage and use nvim normally (i.e. :enew)
# Trying to paste will result in a "register empty" error, too.
```

**Comment by justinmk** [comment]
> Running nvim normally and using the `:Man` command does not cause this error, and explicitly piping with `man ls | nvim +Man!` doesn't cause it to happen either.

Weird. It must be the way that `man` invokes `nvim`. I don't think there's anything we can do about this. If `xclip` can't open the display ... then it can't access the clipboard.

Maybe try installing `xsel`, and see if it better handles the situation?

**Comment by KillTheMule** [comment]
FWIW I could not reproduce this while using xsel. So it's worth a shot :)

**Comment by LunarLambda** [comment]
I installed xsel, checkhealth lists xsel as clipboard provider, tried it.. still gives me an error about xclip :upside_down_face: 

Very crudely uninstalled xclip, tried again, error no longer shows up (i assume it must be using xsel), but, it still doesn't actually copy anything

**Comment by LunarLambda** [comment]
Set up g:clipboard as such:
```
let g:clipboard = {
    \ 'name': 'xsel',
    \ 'copy': {
    \     '+': 'xsel -ib',
    \     '*': 'xsel -ip'
    \ },
    \ 'paste': {
    \     '+': 'xsel -ob',
    \     '*': 'xsel -op'
    \ },
    \ 'cache_enabled': 1
    \ }

``` 

Get error `clipboard: error invoking xsel: xsel: Can't open display: (null) : Permission denied` now when trying to copy/paste from nvim invoked by man. I'd suggest adding a disclaimer to the help files for now.

**Comment by KillTheMule** [comment]
> 
> 
> xsel (1.2.0) works in normal mode, but when started from man it doesn't copy anything

Works for me when running `MANPAGER='nvim -u NORC +Man!' man ls` as well (although there's a different problem because of the `!`, maybe my nvim is a tad older).

**Comment by justinmk** [comment]
> I'd suggest adding a disclaimer to the help files for now.

The error clearly says what's wrong, so mentioning in the help that "paste might not work for this or that circumstance" is just noise.

**Comment by LunarLambda** [comment]
> > I'd suggest adding a disclaimer to the help files for now.
> 
> The error clearly says what's wrong, so mentioning in the help that "paste might not work for this or that circumstance" is just noise.

I believe if _exactly_ following something the help files mention (filetype.txt L518,519) introduces a bug (or deviation from expected behavior in general), then it should be mentioned.

**Comment by LunarLambda** [comment]
I've finally got it to work with a fun shell hack
If anyone else happens to run into this issue, this is the closest thing to a fix we'll get, it seems.

```sh
export MANPAGER='nvim +Man!'

function man {
    eval "command man $@ | $MANPAGER"
}
```

**Comment by LunarLambda** [comment]
I contacted the maintainer for man-db on Debian, and he sent me a fix. I've updated the issue with the fix.
