### ISSUE TITLE
ignore <Plug>(xxx) mapping in paste mode

### ISSUE THREAD

**Issue by roxma** [neovim/neovim#9202]
I post this feature request because of a hard to fix issue in one of my plugins.

1. As mentioned in the PR https://github.com/ncm2/ncm2/pull/95, at the time the plugin checks `&paste` flag, nvim may not be in `paste` mode. But it may be in `paste` mode when the keys is actually being executed.
2. `<Plug>(xxx)` is only used for custom mapping. It's meaningless to "insert" it in `&paste` mode.

**Comment by dimbleby** [comment]
Maybe related to #7994?  

Just a guess, I don't know how the code works, but perhaps the symptoms of the ncm2 issue could be explained by `nopaste` not happening when it ought to have done?

**Comment by justinmk** [comment]
#7994 is not related.

Where is `<Plug>(xxx)` coming from? Mappings are disabled in paste mode so I don't understand the request.

**Comment by dimbleby** [comment]
[here](https://github.com/ncm2/ncm2/blob/4aaf9e1e313109d32fd2b64a5299416357d901b2/autoload/ncm2.vim#L369), via `feedkeys`.

**Comment by justinmk** [comment]
`feedkeys()` and `nvim_input()` are essentially equivalent to raw user input. 

`feedkeys(..., 'm')` (with the "m" flag) specifically says "enable mappings", does not make sense during `paste` mode. Seems like even during `paste` mode, specifying "m" for `feedkeys()` should still invoke mappings.

So the current behavior of `feedkeys(..., 'm')` during `paste` mode doesn't necessarily make sense.

I'm not sure. But if that's going to be changed it should be decided by Vim. cc @chrisbra @brammool

> As mentioned in the PR ncm2/ncm2#95, at the time the plugin checks &paste flag, nvim may not be in paste mode. But it may be in paste mode when the keys is actually being executed.

@roxma Can't you use `OptionSet paste ...` autocmd?

**Comment by roxma** [comment]
> @roxma Can't you use OptionSet paste ... autocmd?

Unfortunately OptionSet paste doesn't help.

The following vimrc shows my point. Without  `autocmd InsertEnter * set paste`, I get `t` in the buffer. But with  `autocmd InsertEnter * set paste`,  I get `<Plug>t` in the buffer.


```vim
autocmd VimEnter * call feedkeys('i')
autocmd InsertEnter * call feedkeys("\<Plug>t")
autocmd InsertEnter * set paste

imap <Plug>t t

func! Foo(...)
    if &paste
        return
    endif
    call feedkeys("\<Plug>t")
endfunc

```

**Comment by chrisbra** [comment]
Aren't you missing the call to `Foo()`?

**Comment by justinmk** [comment]
@roxma In that example vimrc `set paste` is done _after_ `feedkeys("\<Plug>t")`: autocmds are evaluated in declaration-order. But the keys are queued in "typeahead" , because you did not use the 'x' flag of `feedkeys()`.

Try `feedkeys("\<Plug>t", 'x')` instead.

**Comment by roxma** [comment]
> Aren't you missing the call to Foo()?

@chrisbra My mistake. But the result is the same.

> Try feedkeys("\<Plug>t", 'x') instead.

@justinmk With `'x'` I get nothing in the buffer. My understanding is that `'x'` make the keys executed before the feedkeys return. But this is not the desired behavior.

Say, I want to trigger auto completion as long as I get into insert mode, the best practice seems to be using the `InsertEnter`. But unfortunately, when `InsertEnter` is triggered, the editor is not in insert mode at the moment, so  `feedkeys("\<Plug>(xxx)", "x")` will be executed in normal mode. It won't work.

**Comment by justinmk** [comment]
> But unfortunately, when InsertEnter is triggered, the editor is not in insert mode at the moment, 

My mistake. Then maybe `InsertEnterPost` or the elusive `ModeChange` event should be implemented.

**Comment by brammool** [comment]
> `feedkeys()` and `nvim_input()` are essentially equivalent to raw user input. 
> 
> `feedkeys(..., 'm')` (with the "m" flag) specifically says "enable mappings", does not make sense during `paste` mode. Seems like even during `paste` mode, specifying "m" for `feedkeys()` should still invoke mappings.
> 
> So the current behavior of `feedkeys(..., 'm')` during `paste` mode doesn't necessarily make sense.
> 
> I'm not sure. But if that's going to be changed it should be decided by Vim. cc @chrisbra @brammool
> 
> > As mentioned in the PR ncm2/ncm2#95, at the time the plugin checks &paste flag, nvim may not be in paste mode. But it may be in paste mode when the keys is actually being executed.
> 
> @roxma Can't you use `OptionSet paste ...` autocmd?

The feedkeys() function is very low level.  The caller should make sure
it's called with the right arguments.  It's also used in tests, where we
want to control exactly what happens.

Is the real problem that you don't know wheter pasting is currently
happening.

-- 
You know you use Vim too much when you have this alias in your
~/.bashrc file: alias :e=/bin/vim             (Eljay Love-Jensen)

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by roxma** [comment]
> Is the real problem that you don't know wheter pasting is currently happening.

@brammool  I believe it is.

But as one's config file geting complicated, when different parts interleave they may break each other. This make `feedkeys("\<Plug>(xxx)")` unreliable.

An alternative is to execute all  typeahead before actually entering paste mode, but I guess this is even more complicated.
