### ISSUE TITLE
Disable “Insert (paste)” mode 

### ISSUE THREAD

**Issue by victoriastuart** [neovim/neovim#9203]
Cross-posted at:

* https://stackoverflow.com/questions/53123297/disable-insert-paste-mode
* https://www.reddit.com/r/vim/comments/9uerhp/disable_insert_paste_mode/
* https://www.reddit.com/r/neovim/comments/9ufg11/disable_insert_paste_mode/

--- 

I have this in my ~/.vimrc: `set nopaste`.

Often when copying and pasting text from the web to Vim (Nvim v.0.3.1), Nvim enters the **`Insert (paste)`** mode, in which:

* the pasted text has `<paste>` appended at the end;
* my normal `jj` (`Esc`) keymapping is disabled: I need to press the `Esc` key to exit that `Insert (paste)`mode; and,
* my snippets (`vim-snippets`, `vim-snipmate` packages) do not work.

It's very annoying, as I need to

* stop my editing;
* `Esc` out of Insert mode;
* select/delete that added text ("&lt;paste&gt;");
* make any other corrections; and
* manually re-set `:set nopaste`.

What, if anything, can I add to my ~/.vimrc to permanently disable the **`"Insert (paste)`** mode?

I am using `xfce4-terminal`, in which I have mapped `Ctrl-Shift-V` as my insert (paste) command.

I also have these, in my ~/.vimrc:

    nnoremap <c-v> <Nop>
    nnoremap <C-S-V> <Nop>
    inoremap <C-S-V> <Nop>
    nmap <C-v> <Nop>

**Comment by justinmk** [comment]
> It's very annoying

Yes, it is. Sorry. Known issue. https://github.com/neovim/neovim/issues/7994
