### ISSUE TITLE
Update systemd runtime file to not piggypack on DOSINI format

### ISSUE THREAD

**Issue by alxpettit** [neovim/neovim#9208]
Editing systemd files with mere INI syntax highlighting is a pain because it doesn't show you when you've made an error. This is what I mean:

![nvim-issue0](https://user-images.githubusercontent.com/28266167/48063037-cc5db180-e191-11e8-8cce-04b4d9f09ada.png)

![nvim-issue1](https://user-images.githubusercontent.com/28266167/48063046-d1bafc00-e191-11e8-96b3-f7782dedafa1.png)

The first is stock `nvim` highlighter as of the current revision, and the second is from my personal `vim` setup with [my preferred systemd syntax highlighter](https://github.com/alxpettit/fedora-vim-scripts/blob/master/syntax/systemd.vim).

I went further and actually tested my systemd syntax highlighter as a drop-in replacement for the current nvim one, and it seems to work fine.

Can we just replace the built-in neovim file with this syntax highlighter?

**Comment by justinmk** [comment]
@alxpettit did you send this request to Vim? We don't want to fork the runtime files in most cases .

**Comment by alxpettit** [comment]
@justinmk Oh, so all your runtime files are maintained upstream? I'm sorry, I didn't realize. Who do I contact about this?

**Comment by alxpettit** [comment]
I'll reopen if the upstream doesn't accept this file and y'all are interested in upgrading your syntax highlighting.

On a side note, what's the best way to override neovim's prepackaged runtime files? The original systemd file keeps trumping my preferred one for whatever reason.
