### ISSUE TITLE
Wayland clipboard support

### ISSUE THREAD

**Issue by htfy96** [neovim/neovim#9213]
- `nvim --version`: NVIM v0.3.1
- Vim (version: ) behaves differently? No. Also doesn't work under Wayland.
- Operating system/version: Archlinux, gnome-shell 3.30.1 running on wayland 1.16.0-1
- Terminal name/version: Guake 3.3.2-2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# use v to select a range of text
# press "+y
```

### Actual behaviour
Nothing is copied

### Expected behaviour
Text are copied clearly

### More information
There is a project similar to `xclip`, but in wayland named [`wl-clipboard`](https://github.com/bugaevc/wl-clipboard). I was wondering if Neovim can add support to this program.

**Comment by mhinz** [comment]
I'm not sure how many people are running Wayland here, but a good first step would be to see if manually setting `g:clipboard` makes it work already.

See `:h clipboard-tool`.

If you get it working this way, I'm sure we can quickly get it added here: https://github.com/neovim/neovim/blob/769d164c70bee1877d101447ba41730147a2f127/runtime/autoload/provider/clipboard.vim#L55-L110

**Comment by justinmk** [comment]
It's trivial to add support for https://github.com/bugaevc/wl-clipboard as @mhinz noted.

If you're using wayland, just make the changes, test them, and send a pull request.

**Comment by bepolymathe** [comment]
Is there is a progress for that ?

**Comment by justinmk** [comment]
@bepolymathe check the link above. https://github.com/neovim/neovim/pull/9229 was included in 0.3.2

**Comment by CristianArean** [comment]
I know it was included in 0.3.2 but it does not work even after a few years. Any integrated solution?
