### ISSUE TITLE
add appendbufline, setbufline, deletebufline

### ISSUE THREAD

**Issue by liushapku** [neovim/neovim#9216]
- `nvim --version`:
- Vim (version: ) behaves differently?  `added in vim 8`
- Operating system/version:
- Terminal name/version:
- `$TERM`:

I want to request for the addition of these functions which already exist in vim 8. 
They allow for manipulating an arbitrary buffer other than the current buffer. 

Currently, only the current buffer can be updated. Therefore, for an async job to update an buffer which is deactivate (hidden) after starting the async job, we need to switch to the buffer waiting to be updated and switch back after finishing. This will have a lot of side effects, including at least the followings:

1. change the jump list
1. change the alternative buffer
1. stop insert/visual mode
1. cause screen flickering

**Comment by bfredl** [comment]
This is nice for compatibility, but nvim async plugins can already use `nvim_buf_set_lines` (which does all mentioned functions) for a long time.

**Comment by liushapku** [comment]
How to call that api using vimscript?

Björn Linse <notifications@github.com> 于 2018年11月8日周四 下午5:02写道：

**Comment by bfredl** [comment]
Just call the function, it has the same name, and bufnr is the first arg.

**Comment by liushapku** [comment]
I use jobstart combined with vimscript; not an async plugin

Xinkele Liu <dev.xinkele@gmail.com> 于 2018年11月8日周四 下午5:03写道：

**Comment by bfredl** [comment]
Vimscript can call nvim API functions since two years.

**Comment by justinmk** [comment]
fixed in 9358979d096a6bfde371bbc
