### ISSUE TITLE
Visual delimiter/cue for active and inactive buffers in black and white colorschemes

### ISSUE THREAD

**Issue by hahanein** [neovim/neovim#9217]
- `nvim --version`: NVIM v0.3.2-851-gc4c74c388
- Vim (version: ) Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2018 12:41:20)
- Operating system/version: Ubuntu 16.04.5 LTS
- Terminal name/version: tmux
- `$TERM`: xterm-mono

### Steps to reproduce

```
nvim -u NONE
:hi StatusLine     cterm=NONE       ctermfg=NONE  term=NONE
:hi StatusLineNC   cterm=NONE       ctermfg=NONE  term=NONE
```

### Actual behaviour

No matter which buffer I'm in there's no visual delimiter/cue for active and inactive buffers. So I get this:

```
1
~
~
[No Name]                                         0,0-1          All

```

### Expected behaviour (vim)
```
1
~
~
[No Name]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^0,0-1^^^^^^^^^^All

```

Split view:

```
1                              |1
~                              |~
~                              |~
[No Name]^^^^^^^0,0-1^^^^^^^All^[No Name]=========0,0-1=========All

```

`^^^` for active, `===` for inactive.

**Comment by bfredl** [comment]
You want `StatusLineNC` to have a different color than `StatusLine` per default?

**Comment by hahanein** [comment]
I want StatusLineNC to show `===` and StatusLine to show `^^^` so I can disable colors.

**Comment by bfredl** [comment]
The `'fillchars'` option should do this, try

`set fcs+=stl:^,stlnc:=`
