### ISSUE TITLE
listchars=lead

### ISSUE THREAD

**Issue by dannycolin** [neovim/neovim#9233]
- `nvim --version`:
0.1.7
- Vim (version: ) behaves differently?
No. It's not implemented yet. See: https://github.com/vim/vim/pull/3156
- Operating system/version:
Debian Stretch
- Terminal name/version:
Xterm 327
- `$TERM`:
xterm-256color

### Actual behaviour

listchars can only show all spaces or trailing spaces

### Expected behaviour

Be able to show only leading spaces

**Comment by jamessan** [comment]
Isn't this addressed by `'listchars'`'s "space" setting?

**Comment by jamessan** [comment]
Ah, no.  That shows up for _all_ spaces, not just leading ones.
