### ISSUE TITLE
relativenumber cause fold line flash

### ISSUE THREAD

**Issue by zgpio** [neovim/neovim#9236]
- `nvim --version`: v0.3.2
- Vim (version: 8.1 Included patches: 1-467) behaves differently? Yes
- Operating system/version: Ubuntu
- Terminal name/version: 
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

1. nvim -u NORC
2. :set relativenumber
3. input as follow:
![image](https://user-images.githubusercontent.com/19503791/48524412-24479700-e8bb-11e8-9004-d01307de14b2.png)
4. :set foldmethod=indent
5. fold it as follow:
![image](https://user-images.githubusercontent.com/19503791/48524434-404b3880-e8bb-11e8-8d10-4f58f9be34c1.png)
6. move cursor next line, the fold line not refreshed properly
![image](https://user-images.githubusercontent.com/19503791/48526009-10069880-e8c1-11e8-88e6-eb8b849b3c88.png)

**Comment by justinmk** [comment]
what is the exact version of vim that you tested?

**Comment by janlazo** [comment]
Does vim-patch:8.1.0449 fix it?

**Comment by zgpio** [comment]
There is no such problem in VIM.

**Comment by justinmk** [comment]
cannot reproduce on 0.4.x bcbb96e31b88eff7a1629c7c8a5f1d4eacb32829
