### ISSUE TITLE
ppa: package for amd64 not updated

### ISSUE THREAD

**Issue by sascha-andres** [neovim/neovim#9237]
Current version 0.3.0-2

### Actual behaviour

apt update does not show a new package (I am still on 0.3.0-2)

### Expected behaviour

Show package to install: 0.3.1-1

The go-vim extension complains on wanting at least 0.3.1 on each start and does behave not well with the older version.

It seems the build for the amd64 package is broken:

![image](https://user-images.githubusercontent.com/3052075/48532602-52b87880-e8a1-11e8-9306-4832a8478283.png)

**Comment by justinmk** [comment]
It's a known issue. If it were not a known issue, you would report it to the package maintainer, not us.
