### ISSUE TITLE
Cant't find where plugin should be stored to be taken into account by neovim on a Windows 8 box

### ISSUE THREAD

**Issue by psychoslave** [neovim/neovim#9239]
On a Windows 8 box, with neovim installed via scoop, the configuration file stored in `C:\Users\USERNAME\AppData\Local\nvim\init.vim` is well read at neovim launch. However having copied [ShowMark](https://vim8.org/scripts/script.php?script_id=2142] plugin into the same directory, trying to run `DoShowMarks` doesn't work. 

The documentation of the plugin specify to unzip the archive to `$vim_dir`. I supposed that it would be the directory where the init.vim file is red, but it appears it's not the case or at least it's not automatically made available at neovim launch.

How can I make this plugin, and any plugin in general, works in this environment?

Cheers

**Comment by justinmk** [comment]
`C:\Users\USERNAME\AppData\Local\nvim\plugin\` is one option. See `:help add-global-plugin` for details.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
