### ISSUE TITLE
 Neovim Unstable PPA overridden in cosmic by older ubuntu package

### ISSUE THREAD

**Issue by BonaBeavis** [neovim/neovim#9241]
See [Neovim Unstable : “Neovim PPA” team](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable) in "Overview of published packages" it says for cosmic there is "newer" version avaible.

**Comment by justinmk** [comment]
https://launchpad.net/~neovim-ppa

https://github.com/neovim/neovim/issues/9237

**Comment by jamessan** [comment]
This is different than #9237.  I incorrectly set the nightly PPA version to one that sorts less than 0.3.1.  I'll fix that.

**Comment by fszymanski** [comment]
> This is different than #9237. I incorrectly set the nightly PPA version to one that sorts less than 0.3.1. I'll fix that.

@jamessan this issue still persists.

**Comment by jamessan** [comment]
Next time the builds run, it should be fixed.
