### ISSUE TITLE
`nvim_list_bufs` does not honor buffer deletions

### ISSUE THREAD

**Issue by d-e-s-o** [neovim/neovim#9242]
- `nvim --version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0/x86_64-pc-linux-gnu-gcc -march=native -O2 -fomit-frame-pointer -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1_build/config -I/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1/src -I/usr/include -I/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1_build/src/nvim/auto -I/tmp/portage/app-editors/neovim-0.3.1/work/neovim-0.3.1_build/include
Compiled by root@vaio

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Vim (version: ) behaves differently?
N/A (this issue is about a Neovim API)
- Operating system/version:
Gentoo linux
- Terminal name/version:
xterm/tmux
- `$TERM`:
screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:tabnew
:ls
  1 #a   "[No Name]"                    line 1
  2 %a   "[No Name]"                    line 1
:echo nvim_list_bufs()
  [1, 2]
:bd
:ls
  1 %a   "[No Name]"                    line 1
:echo nvim_list_bufs()
  [1, 2]
```

### Actual behaviour
```
:echo nvim_list_bufs()
  [1, 2]
```

### Expected behaviour
```
:echo nvim_list_bufs()
  [1]
```

I don't understand why `nvim_list_bufs()` would return a buffer that has been deleted. I certainly could not find documentation that indicates that it would do that and I found it vastly surprising. What's the purpose of an API reporting stale data? Can somebody confirm whether that's a bug or by design?

**Comment by bfredl** [comment]
It is by design, and behavior inherited from vim. The buffer has to be wiped `:bw` to be removed from the buffer list. The terminology might be unfortunate but changing it would be a breaking change.

**Comment by justinmk** [comment]
`nvim_list_bufs` is like `:ls!`. Use `:bwipeout` as mentioned if you want to eradicate a buffer.

Note that Nvim 0.3.2 has `nvim_buf_is_loaded()` which can be used to check if the buffer is unloaded/deleted.

**Comment by d-e-s-o** [comment]
Thanks for the clarification and for adding a note! I was actually unaware of `:bwipeout`. As long as there is a way to make it return the correct buffer list (in my case by using `:bw` instead of `:bd`), that should be sufficient for my use case.
