### ISSUE TITLE
`torsocks nvim` hangs

### ISSUE THREAD

**Issue by zsugabubus** [neovim/neovim#9254]
- `nvim --version`: v0.3.1 (also: v0.3.2-dev)
- Vim (version: ) behaves differently? Yes.
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
torsocks nvim -u NORC
```

### Actual behaviour
```
$ torsocks strace nvim -u NORC
...
futex(0x7f92562ff048, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f9256749280, FUTEX_WAIT_PRIVATE, 2, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
futex(0x7f9256749280, FUTEX_WAIT_PRIVATE, 2, NULL) = ...
```

**EDIT:** [Full strace output.](https://gist.github.com/zsugabubus/480996027ccd9bd2ce536f46465401c5)

### Expected behaviour
No hanging.

**Comment by jamessan** [comment]
That worked just fine for me.  Can you try with `nvim -u NORC --noplugin`?  If you don't experience a hang with that, then you'll need to find what plugin is causing problems.

**Comment by zsugabubus** [comment]
It didn't work for me... probably because this hang happens at the very beginning of the process start. I was in hurry, so I've just now updated my comment with the full strace output.

I don't know, but maybe it has something to do with the kernel?

**Comment by zsugabubus** [comment]
Works with NVIM v0.3.8, so close the issue.
