### ISSUE TITLE
:term unable to scroll in terminal mode after deleting a different buffer

### ISSUE THREAD

**Issue by mpjuers** [neovim/neovim#9260]
- `nvim --version`: 
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/build/config -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?
Unknown.

- Operating system/version:
macOS 10.14

- Terminal name/version:
iTerm2 3.1.6

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

1. 
```
nvim -u NORC
:sp | term
:tabnew
:bd
```

2.
```
ctrl-\ ctrl-n
```

3.
```
a
```

4.
```
select term window and ctrl-w + / -
```

### Actual behaviour
after 1. Fill terminal window with text and note that once the active line is beyond the bottom of the split, it is no longer visible; the view is stuck at the top of the terminal history.

after 2. Now, notice that the window is scrollable in normal mode.

after 3. Terminal window scrolls back to top obscuring the active line again.

after 4. Resizing the window returns normal functionality.

### Expected behaviour
Bottom of terminal history and prompt are visible when in terminal mode.

**Comment by justinmk** [comment]
Sounds like #7767 .
