### ISSUE TITLE
helptags

### ISSUE THREAD

**Issue by seannaswell** [neovim/neovim#9268]
- `nvim --version`: 0.3.1
- Vim (version: ) N/A
- Operating system/version: DragonFlyBSD 5.2
- Terminal name/version: urxvt 9.22
- `$TERM`: rxvt

### Steps to reproduce using `nvim -u NORC`

Install plugin manually by copying to plugin directory, restart nvim, test plugin functionality successfully. Attempt to import help file using `:helptags /path/to/doc`

### Actual behaviour
No errors. Attempt to load help file `:help emmet-vim` produces Error 149, no help file available 
### Expected behaviour
Open help file

**Comment by justinmk** [comment]
Works for me. Works for all of our CI envs, including FreeBSD (we don't yet have a DragonFlyBSD CI env). 

> Vim (version: ) N/A

It is worth comparing the same steps in Vim.

Since I can't reproduce the issue, we need to know the exact steps, not pseudo steps like /path/to/doc.

**Comment by justinmk** [comment]
Is the plugin in your runtimepath?

    :set rtp+=/path/to/emmet

**Comment by seannaswell** [comment]
Your assumption was correct, a usage issue. 

New user, a vim tutorial stated that adding a path was done thru .vimrc as opposed to live, which apparently is not accurate or does not apply to Neovim. Thanks.

**Comment by justinmk** [comment]
> vim tutorial stated that adding a path was done thru .vimrc as opposed to live, 

what exactly did it say? Everything related to plugin installation works the same in Nvim/Vim.

**Comment by seannaswell** [comment]
> what exactly did it say? Everything related to plugin installation works the same in Nvim/Vim.

Even though I know it's not good referring to random websites rather than official documentation, that is what I did in this case. During troubleshooting I had a number of references open, but this site is what mentions putting the runtimepath directive in .vimrc: [install vim plugins without plugin manager](https://howchoo.com/g/ztmyntqzntm/how-to-install-vim-plugins-without-a-plugin-manager)

The issue, I believe, was rather than using the plugin path mentioned in the article (`~/.vim/bundle/`), I was using (`~/.local/share/nvim/site/plugin`). 

So, the issue was operator error. Thanks again.
