### ISSUE TITLE
Underline not displayed in TUI

### ISSUE THREAD

**Issue by 0xC0FFEE** [neovim/neovim#9270]
- `nvim --version`: NVIM v0.3.2-913-g108566e7b
- Vim (version: ) /
- Operating system/version: Arch Linux
- Terminal name/version: tmux in termite
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Use any highlighting with uses `gui=underline` so e.g. SpellBad or: 

```
nvim -u NORC
:term
echo -e "\e[4munderline\e[0m"
```

### Actual behaviour
Neither spelling mistakes nor the word ´underline´ are underlined

### Expected behaviour
Spelling mistakes and ´underline´ are underlined. Outside of neovim this works as expected.

This used to work in 5ff90a100 and broke for me in 8ac44984c.

**Comment by justinmk** [comment]
8ac4498 itself cannot be the root cause.
We need you to bisect to the exact commit between  5ff90a1 and  8ac4498.

**Comment by 0xC0FFEE** [comment]
You are absolutely right, that 8ac4498 itself probably didn't cause the issue. The referenced commits were just the good and bad points I could provide. Sorry for not being more clear.

I'll bisect the exact commit when I have some free time. Thank you for your fast response :+1:

**Comment by 0xC0FFEE** [comment]
It seems like bbd8f4e9a broke the functionality for me.

**Comment by justinmk** [comment]
So the issue is _not_ present on c4006a621eff1761208b0aa38057f4668b4a6ba8 ?

**Comment by 0xC0FFEE** [comment]
In c4006a6 text is correctly underlined for me.

**Comment by justinmk** [comment]
Does this change fix it:

```diff
diff --git a/src/nvim/tui/tui.c b/src/nvim/tui/tui.c
index d2ddd98fd46a..12013446f991 100644
--- a/src/nvim/tui/tui.c
+++ b/src/nvim/tui/tui.c
@@ -545,15 +545,6 @@ static void update_attrs(UI *ui, int attr_id)
   if (undercurl && data->unibi_ext.enter_undercurl_mode) {
     unibi_out_ext(ui, data->unibi_ext.enter_undercurl_mode);
   }
-  if ((undercurl || underline) && data->unibi_ext.set_underline_color) {
-    int color = attrs.rgb_sp_color;
-    if (color != -1) {
-        UNIBI_SET_NUM_VAR(data->params[0], (color >> 16) & 0xff);  // red
-        UNIBI_SET_NUM_VAR(data->params[1], (color >> 8) & 0xff);   // green
-        UNIBI_SET_NUM_VAR(data->params[2], color & 0xff);          // blue
-        unibi_out_ext(ui, data->unibi_ext.set_underline_color);
-    }
-  }
   if (ui->rgb) {
     if (fg != -1) {
       UNIBI_SET_NUM_VAR(data->params[0], (fg >> 16) & 0xff);  // red
```

And if so, let's check your terminfo. With Nvim 0.3.0+ you can see terminal debugging info when the 'verbose' level is >=3 (see `:help 'verbose')`.  Do this:

    nvim -V3log
    :q

Then the file named `log` will have a `--- Terminal info ---` section. Please post that section.
(Note: invoke `:q` manually, so that the builtin UI has a chance to start up. Don't add `-c "q"` in the command-line args.)

**Comment by justinmk** [comment]
`ext.set_underline_color` is set, which implies that `unibi_find_ext_bool(ut, "Su")` returned something, which implies that "Su" extension was set in your tmux config. @blueyed  is this expected?

**Comment by 0xC0FFEE** [comment]
The tmux version is 2.8.

**Comment by justinmk** [comment]
termite obviously doesn't support `ext.set_underline_color`. So the question is where did that "Su" entry come from?

**Comment by 0xC0FFEE** [comment]
> termite obviously doesn't support `ext.set_underline_color`.

Are you sure about that? If I run neovim in termite directly I have support for colored underlines [1].

> So the question is where did that "Su" entry come from?

IDK, is there any way to find this out? Underlines are also not working in tmux with the default config. 

[1] https://imgur.com/a/WQMbBXS

**Comment by blueyed** [comment]
Please provide the output from `infocmp -x | grep Su` within tmux and outside of it.

@justinmk 
https://github.com/neovim/neovim/commit/bbd8f4e9a407022e89463852e76ed7426607a760 being the commit implies that `has_colon_rgb` is maybe wrong only?!

**Comment by 0xC0FFEE** [comment]
> Please provide the output from `infocmp -x | grep Su` within tmux and outside of it.

The output is empty in *both* cases.

**Comment by justinmk** [comment]
@blueyed Hmm. I wonder if `set_underline_color` always expects colons. Do we need the non-colon form at all?

**Comment by egmontkob** [comment]
For undercurl, the newly invented escape sequence is `4:3` strictly with a colon, as with a semicolon it means single underlined and italic.

For colored underline, the newly invented escape sequence `58:...` is meant to follow the pattern of `38` and `48`. [ITU T.416](https://www.itu.int/rec/T-REC-T.416-199303-I/en) § 13.1.8 clearly specifies the colon only as the separator (and the well-known ECMA-48 § 8.3.117 just points to this standard).

Using semicolon instead was/is a frequent misinterpretation of this standard, and is commonly used in the wild – for 38 and 48. More and more emulators are catching up and beginning to support colon, in addition to semicolon. Semicolon is pretty fragile; in case an emulator doesn't recognize a sequence (let's say doesn't recognize the new extension of `58`), subsequent numbers are interpreted as other attributes. E.g. if 256-color mode is chosen then the next numeric parameter is `5` which turns on blinking.

So, luckily, the standard is the technically better solution, the frequent practice of using semicolons is technically the worse. Therefore the direction we should be going is clear.

I believe it's a fair requirement for anyone adopting colored underline to support colons too, and it's a reasonable move from applications to slightly push the world forward, force developers to catch up with the recent changes, that is: 1) recognize and at least ignore colon-delimited parameters even if they aren't supported, 2) recognize and support colon wherever they support the nonstandard semicolon instead.

Should you come across any terminal emulator that supports 58 with semicolons but not with colons, I think the cleanest you can do is report a bug against them and ignore the problem; they should fix it.

**Comment by blueyed** [comment]
Thank you for the detailed description, @egmontkob !

I've created https://github.com/neovim/neovim/pull/9279 to address/fix this.

**Comment by egmontkob** [comment]
Hang on, there's one more thing. (I missed that you had problems with the RGB notation in particular.)

It's yet another common misunderstanding that the truecolor syntax is `38`/`48`/`58` followed by `:2:rrr:ggg:bbb`. The wording of T.416 is terrible, but if you read carefully, there's another parameter of color-space-id preceding the three color channels. Assuming you don't care about color-space-id (I don't really know what this is), the syntax is `38`/`48`/`58` followed by `:2::rrr:ggg:bbb` and of course the trailing `m`.

This is only for true-color, the 256-color format doesn't have such a parameter, it's `38`/`48`/`58` followed by `:5:index` and the final `m`.

Some terminals might accept both formats for RGB, based on the number of parameters. (This is another case where using colons is useful, with semicolons it'd be practically impossible to make such guesses, you'd never know when the intent was to start a brand new attribute.)

**Comment by egmontkob** [comment]
(To summarize: the common practice of `38/48;2;rrr;ggg;bbbm` is doubly wrong :))

**Comment by blueyed** [comment]
So instead of `"\x1b[58:2:%p1%d:%p2%d:%p3%dm"` it should be `"\x1b[58:2::%p1%d:%p2%d:%p3%dm"` ?

**Comment by egmontkob** [comment]
Yup, thanks!

**Comment by justinmk** [comment]
> This is only for true-color, the 256-color format doesn't have such a parameter, it's 38/48/58 followed by :5:index and the final m.

So we need a different form for non-truecolor terminals? Or is that unnecessary, given that most terminals which support colored underline, would also support RGB?

**Comment by 0xC0FFEE** [comment]
> Great.
> @0xC0FFEE
> Can you test #9279, please?

This solves the issue for :+1:

Underlines are working correctly now, but I cannot use colored underlines. But this might be the expected behavior, as the `Su` is not present in my terminfo description.

**Comment by ArchiFleKs** [comment]
@0xC0FFEE for me it is working outside tmux. But inside (with latest master) it is only working without `set termguicolor`.

**Comment by 0xC0FFEE** [comment]
> @0xC0FFEE for me it is working outside tmux. But inside (with latest master) it is only working without `set termguicolor`.

Works on my machine with `set termguicolor`.
