### ISSUE TITLE
:Man : cannot find tag if MANSECT/MANPATH contains colon 

### ISSUE THREAD

**Issue by petobens** [neovim/neovim#9271]
- `nvim --version`: NVIM v0.3.2-913-g108566e7b
- Vim (version: ) behaves differently? Don't know
- Operating system/version: 4.19.2-arch1-1-ARCH
- Terminal name/version: alacritty 0.2.3
- `$TERM`: tmux-256color
- man version: 2.8.4

### Steps to reproduce using `nvim -u NORC`

Using `nvim -u NORC` and then `Man startx` I can jump between tags with `Ctrl-]`. On the other hand if i set `export MANPAGER='nvim -u NORC +Man!'` and run `man startx` I get the following error when trying to jump to tag:
```
man.vim: command error (6) man -w xinit: No manual entry for xinit
```
![peek 2018-11-24 13-25](https://user-images.githubusercontent.com/2583971/48970573-78a1f380-efec-11e8-84b5-6bf396c3d201.gif)

Seems to be related to #9156 but it doesn't seem to be solved with latest nvim.

**Comment by justinmk** [comment]
@petobens what does `echo $MANSECT` report?

This looks similar to https://github.com/neovim/neovim/issues/9156#issuecomment-433240875 , where @lacygoill came up with a nice minimal repro:

```
export MANSECT=1:n:l:8:3:2:3posix:3pm:3perl:5:4:9:6:7
export MANPAGER='nvim -Nu NONE -'
man man
:!man -w mount

No manual entry for mount
```

See also: https://github.com/neovim/neovim/issues/9156

**Comment by petobens** [comment]
`MANSECT` is empty but when looking into that I removed this line from by bashrc:
```sh
export MANPATH="$MANPATH:/usr/local/texlive/2018/texmf-dist/doc/man"
```
and the problem disappeared. Am i setting wrong the manpath or is something on neovim end? Thanks for the help with this.

**Comment by justinmk** [comment]
Can you try the steps I gave above, and say what `:!man -w mount` reports?

**Comment by petobens** [comment]
With the above steps I also get `No manual entry for mount`

**Comment by justinmk** [comment]
So it's the same root cause as discussed in #9159.

**Comment by petobens** [comment]
Personally I can reproduce it (and "fix" it) by changing the `MANTPATH` as I mentioned in the comment above. No idea what part does `MANSECT` play on this. In fact I always get `No manual entry for mount` with and without modifying MANPATH whereas my original problem (jumping to tags) disappears once I remove that MANPATH line from my bashrc.

**Comment by nhooyr** [comment]
I cannot reproduce this.

I'm guessing `man` is truncating MANSECT on your systems to the colon for some reason. We have no code that modifies MANSECT

The simplest fix is to reset MANSECT when invoking `man` like #9159.

**Comment by justinmk** [comment]
> The simplest fix is to reset MANSECT

That doesn't really solve the problem since the problem is actually the presence of a colon. It also happens with a colon exists in `MANPATH` as mentioned in https://github.com/neovim/neovim/issues/9271#issuecomment-443445162 .

**Comment by nhooyr** [comment]
> That doesn't really solve the problem since the problem is actually the presence of a colon. It also happens with a colon exists in MANPATH as mentioned in #9271 (comment) .

Yea, this is unfortunate. I'm not sure if we can really do anything. We can't really reconstruct MANPATH if its trimmed. This is a bug that should be filed upstream, the truncation shouldn't be happening.

**Comment by nhooyr** [comment]
As a work around for now, anyone experiencing this could set MANPATH/MANSECT in their `init.vim` and that should make things work.

**Comment by justinmk** [comment]
We could maybe clobber MANSECT/MANPATH if we find a colon in it? I might be forgetting the order of operations though.

**Comment by nhooyr** [comment]
We can't since the colon was already truncated.

See https://github.com/neovim/neovim/issues/9156#issuecomment-433429173

**Comment by nhooyr** [comment]
I can't reproduce with a colon in $MANPATH.

i.e:

```
export MANPATH="$MANPATH:/usr/local/texlive/2018/texmf-dist/doc/man"
```

Works as expected.

I can however reproduce the $MANSECT truncation issue.

**Comment by nhooyr** [comment]
Please assign me @tjdevries!
