### ISSUE TITLE
Is it possible nvim-qt opens files in single instance

### ISSUE THREAD

**Issue by ilkerhk** [neovim/neovim#9273]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently?
- Operating system/version: Kubuntu
- Terminal name/version: N/A
- `$TERM`: 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
When I open a file (either from dolphin using "open with nvim-qt" or from terminal using "nvim-qt filename.txt") a new instance and a window of nvim-qt is created. 
Is there a way to open the new file in the existing instance instead of a new one?
thanks.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
