### ISSUE TITLE
Unite broken, Cannot make changes, modifiable is off

### ISSUE THREAD

**Issue by tex** [neovim/neovim#9286]
I bisected that this commit bec5e4cb6183f3b403aca35ef55c3798a48dc64b is causing issues with Unite:
E21: Cannot make changes, 'modifiable' is off
is showing when Unite is opened (any buffer works if there is enought candidates) in insert mode and moving up or down to select candidate. If its position is bottom it is always on first try, when position is top then it needs 20 moves down to show the error message.

**Comment by justinmk** [comment]
"vim behaves ok" is meaningless without knowing the exact version.

**Comment by Shougo** [comment]
I have tested unite.vim with neovim.
It works.  So it depends your configuration.
The minimal init.vim is needed for it.

**Comment by tex** [comment]
init.vim:
```
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/Shougo/unite.vim' |
    Plug 'https://github.com/Shougo/vimproc', { 'do': 'make -f make_unix.mak' }
call plug#end()
```

Open neovim in folder that has more than 50files...
:Unite -start-insert file_rec

Now hit and hold arrow key up or down and wait. After short time you see the error message.

Or Open neovim in folder that has more than 50files...
:Unite -start-insert -direction=dynamicbottom file_rec

Now press arrow key up or down  once and you see the error message.

It is important to use arrow keys. Sorry for such heresy ;-)

As I said, identified commit is where it first starts behaving in such manner.

**Comment by justinmk** [comment]
@tex Thanks for the effort. But "install unite" doesn't help narrow down the problem. It could be a timing issue with `feedkeys()` trickery. 

Without a minimal repro using `nvim -u NORC` (without installing huge plugins), this is unlikely to get attention.

**Comment by Shougo** [comment]
>  It could be a timing issue with feedkeys() trickery.

It seems timing issue.
But current unite.vim does not use `feedkeys()` trick.
It uses timer feature instead.

**Comment by justinmk** [comment]
@Shougo is it possible to disable the code (maybe by commenting-out some lines in Unite) so @tex could try to disable the timer, then see if the issue persists?

**Comment by Shougo** [comment]
I have tested the problem and I have reproduced it.
It seems not timer problem and in Vim the problem also exists.

I will research the reason.

**Comment by Shougo** [comment]
It only `<Down>` is broken.
`<Up>` is not broken.  It seems Vim's bug.

**Comment by Shougo** [comment]
I have tested it in Vim 8.1.540.

**Comment by Shougo** [comment]
I think it is reproduce-able without unite.vim.
I will try it later.

**Comment by tex** [comment]
Great Shugo! Thanks!
Just note that with `:Unite -start-insert -direction=dynamicbottom file_rec` arrow `<Down>` and also arrow `<Up>` are broken. Not just `<Down>`.

**Comment by Shougo** [comment]
I have fixed the problem in unite.vim side.
I have removed unite.vim's modifiable hack.
Please test the latest version.

**Comment by Shougo** [comment]
So it is not Vim's bug.  Vim's behavior is changed recently though.

**Comment by justinmk** [comment]
Thanks  @Shougo .
