### ISSUE TITLE
[RPM] Packaging for Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [neovim/neovim#929]
[ignatenkobrain/neovim](https://copr.fedorainfracloud.org/coprs/ignatenkobrain/neovim/)
## Packaging status
- ☑ `unibilium` ([Review Request #1327160](https://bugzilla.redhat.com/show_bug.cgi?id=1327160))
- ☑ `termkey` ([Review Request #1327198](https://bugzilla.redhat.com/show_bug.cgi?id=1327198))
- ☑ `libvterm` ([Review Request #1327218](https://bugzilla.redhat.com/show_bug.cgi?id=1327218))
- ☑ `lua-msgpack` ([Review Request #1117961](https://bugzilla.redhat.com/show_bug.cgi?id=1117961))
- ☒ `lua-bit` (https://github.com/neovim/neovim/issues/4575)
- ☐ `neovim`

**Comment by ninrod** [comment]
How is this issue going? Is there a RPM package to install neovim? There's surely no way to get it on Centos without a RPM. And building it from source is out of the scope when you're working behind a proxy.

**Comment by fwalch** [comment]
@ninrod On the [wiki](https://github.com/neovim/neovim/wiki/Installing-Neovim), there's a link to a [Copr repo](https://copr.fedorainfracloud.org/coprs/dperson/neovim/) which provides "Epel for CentOS" (no idea what that means, though).

**Comment by ninrod** [comment]
Hum, I think epel is like a more bleeding edge repo of the yum package manager. That could work.

**Comment by ninrod** [comment]
Nope, did not work. maybe on fedora it could work. And that's iffy. You would have to have access to the copr from your corporate proxy. That's not a given.

**Comment by equalsraf** [comment]
Another option is to build the packages through [OBS](https://build.opensuse.org) there are already several [third-party RPMs for neovim](http://software.opensuse.org/package/neovim) but only for OpenSUSE.

None for Fedora though. OBS does support Fedora but does not allow you to download files during the build so all dependencies need to be available as packages or the sources are shipped with the build recipe and it seems fedora lacks packages for unibilium/termkey/others.

**Comment by ninrod** [comment]
@equalsraf I find that not having to download packages during the build is a god send. That's keeping us from using nvim on our shop. Corporate proxy rules. As a comparison, I can download the latest vim source and build it with easily available standard unix libraries.

**Comment by ignatenkobrain** [comment]
> it seems fedora lacks packages for unibilium/termkey/others.

which means that someone should start packaging it. I would be glad to review them.

**Comment by jszakmeister** [comment]
@ninrod 
> Nope, did not work. maybe on fedora it could work. And that's iffy. You would have to have access to the copr from your corporate proxy. That's not a given.

We can't workaround every policy a corporation sets up.  You should probably talk to them and see if you can get it amended to include the Copr repositories--I'm sure there is more than just Neovim you would find useful.  I know that fighting the powers that be can be hard and frustrating, but it's generally worth the effort.  FWIW, I've had to climb that particular mountain several times.

> I find that not having to download packages during the build is a god send. That's keeping us from using nvim on our shop. Corporate proxy rules. As a comparison, I can download the latest vim source and build it with easily available standard unix libraries.

You don't have to do the downloads--that was just done as a convenience for developers--especially new contributors.  If you have all the right things installed, use `make USE_BUNDLED_DEPS=false`.  I believe that should get you quite far.  Neovim (necessarily) has more libraries and we're unwilling to give up what they offer (cross-platform portability, terminal emulation, high-speed serialization/deserialization, etc.).  But if you have the dependencies already present on the system, and they are suitable versions, then you should be able to build.

**Comment by ignatenkobrain** [comment]
[unibilium](https://bugzilla.redhat.com/show_bug.cgi?id=1327160)

**Comment by justinmk** [comment]
Neovim is in fedora 25, so I think this can be closed.

https://admin.fedoraproject.org/pkgdb/package/rpms/neovim/
