### ISSUE TITLE
Executing multiple vim commands at once via lua api method nvim_command

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9305]
* nvim --version: NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5

I'm writing a lua plugin that makes a lot of calls to vim.api.nvim_command.  I'm trying to combine multiple commands together to reduce the number of RPC requests, but am having trouble getting multiple commands to run.

The following works fine:

```lua
vim.api.nvim_command("set nofoldenable\nset shiftwidth=5\nset cursorcolumn")
```

But when I use normal commands it seems to pass the newlines to the normal command instead of starting a new command

```lua
vim.api.nvim_command("set nofoldenable\nnormal! j\nnormal! j")
```

When this is executed it produces the following output:

```

rmal! j
```

Because the 'o' in the second normal is actually executed as if o key is pressed.

In writing up this issue I've realized that I can do this as a workaround:

```lua
vim.api.nvim_command("set nofoldenable\nexec \"normal! j\"\nexec \"normal! j\"")
```

Is that the correct way to do this?

**Comment by svermeulen** [comment]
Actually this also doesn't work:

```lua
vim.api.nvim_command("Guifont! Consolas\nset foldenable")
```

So it seems using newlines is not the right way to delimit commands even though it does work when just changing options.  Is there a better way to do it?

**Comment by teto** [comment]
maybe nvim_call_atomic ?

**Comment by bfredl** [comment]
Note `vim.api.nvim_command` is for in process lua code (which still could be invoked by an rpc plugin), for such lua code one could use multiple `nvim_command()` statements in a row without that much overhead. 

Later on we should have a `nvim_source` function #8765.

**Comment by svermeulen** [comment]
Ok sounds like nvim_source will eventually be the correct way to do this so I'll close this
