### ISSUE TITLE
Suggestion: Add option to change default window splitting behavior of commands

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#9308]
## What we have:

Many commands that split the window:

:terminal, :help, :Man, \<C-w>f, :new

Commands that allow us to tweak the splitting behavior:

:leftabove, :rightbelow, :vertical

And the options to go with them:

splitright, splitbelow, and uhm.. nothing.

## Why does this matter?

Pretty much every terminal is much wider than it is high.
On my 160x40 Terminal, opening a normal :help gives me less than 20 lines to read, which isn't really great since most people (I think) tend to skim around the help files a lot. In :terminal, again, output has much more lines than columns, but :vert ter everytime is far from nice, and more often or not we forget it. Or when I jump to a different file with \<C-w>f, again, I'm gonna need way more lines on screen at once than the ~17-ish my setup will effectively give me.

## Workarounds?

- :vert all the things (bothersome)
- mappings (my keymap's getting crowded)
- split, then move windows (does anyone even memorize how to do that?)
- stop whining (no)

## Proposal

Adding a 'verticalsplit' ('vs'?) option.
This can take one of two forms:
A boolean, which simply dictates whether commands whose splitting direction is _not_ intrinsic, should split vertically or not.

By intrinsic I mean things like :split, :vsplit, \<C-w>s, \<C-w>v, etc should be unaffected.

Or, have it be a flag option, which overrides it for only some commands, i.e.

t - :terminal
h - :help
M - :Man
w - \<C-w> commands
etc.

## What to consider

This could potentially break plugins which must (for whatever reason) use a horizontal split. A :horizontal (:hor?) counterpart to vertical may be added, and plugins could simply check if has('verticalsplit') and disable it temporarily, if needed.

## Costs:

Code: low-medium
Maintenance: very low

## Rationale

We already have plenty of options to customize how windows behave, including their splitting behavior. It feels odd and incomplete that there's so little I can do beyond slapping :vert in front of things or adding more stuff to my config.
I feel this would be a nice quality of life feature for people who make frequent use of the commands I've listed.

**Comment by justinmk** [comment]
Thanks for the thorough description. This was requested in #8350 (`splitvertical`).

Meanwhile you could approximate this with the `WinNew` command, e.g.:

    :au WinNew * wincmd H
