### ISSUE TITLE
FileType autocmd aren't fired

### ISSUE THREAD

**Issue by purpleP** [neovim/neovim#9313]
- `nvim --version`: 0.3.1 and latest master
- Vim (version: ) 8 fires autocmd as it should
- Operating system/version: ubuntu 18.10
- Terminal name/version: konsole
To reproduce
`nvim -u NONE -c 'filetype on'` `-c` just to use the same command as in vim.

PS
I've found out that if I issue `set filetype=java` for example than filetype autocmd is triggered. So it's not working only when filetype set automatically...

**Comment by justinmk** [comment]
This is nonsense.
