### ISSUE TITLE
shortmess=F: nvim_command skips :echoerr in FileType autocmd

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9314]
* nvim --version: NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5

Repro steps

Case 1
* nvim -u NORC
* `:au FileType python :echoerr 'foo'`
* `:e C:/Temp/Foo.py`
* Observe error

Case 2
* nvim -u NORC
* `:au FileType python :echoerr 'foo'`
* `:lua vim.api.nvim_command("e C:/Temp/Foo.py")`
* Observe no error
* `set ft=python`
* Observe error

**Comment by svermeulen** [comment]
Just want to mention that the same problem seems to occur when using throw as well

I can't imagine why that would be intentional since this can cause errors to go unnoticed.  In my case it took me a long time to figure out since the only symptom was that the python file was no longer able to be saved.  For whatever reason, after an exception is throw during the FileType autocommand, if you try to write the file to disk you get an error "File exists (add ! to override)" so that was the only clue I had that something went wrong

**Comment by justinmk** [comment]
> Is this related to `set shortmess+=F`? (#8675)

:+1:

Related: https://github.com/neovim/neovim/issues/10116
Related: https://github.com/neovim/neovim/issues/10008
