### ISSUE TITLE
Vim syntax highlighting doesn't highlight endif, endwhile, for, and endfor keywords

### ISSUE THREAD

**Issue by LunarLambda** [neovim/neovim#9316]
![image](https://user-images.githubusercontent.com/38919842/49507982-e9b19880-f881-11e8-8c68-96d004a73819.png)

Happens with nvim -u NORC and nvim -u NONE
Doesn't happen in Vim.

Also function keyword isn't highlighted until the signature is completed, unlike in Vim.

Neovim:
![image](https://user-images.githubusercontent.com/38919842/49508214-6ba1c180-f882-11e8-9dbe-b6ebcb209c6d.png)

Vim:
![image](https://user-images.githubusercontent.com/38919842/49508234-7ceace00-f882-11e8-808b-e2eb7972afc0.png)

Also a bunch other commands aren't highlighted as keywords, although I guess that's intentional.

**Comment by justinmk** [comment]
This obviously isn't the case for other users, so we need more info. What's sample text that causes this? That would be part of the "steps to reproduce starting from `nvim -u NORC`".

**Comment by LunarLambda** [comment]
ls -l /usr/share/nvim/runtime/syntax/vim.vim gives
-rw-r--r-- 1 root root 48758 Jul 18 13:44 /usr/share/nvim/runtime/syntax/vim.vim

(File wasn't modified)

nvim -u NORC file.vim
ifunction hello<esc>

nvim -u NORC file.vim
iif 1<cr>endif<esc>

nvim -u NORC file.vim
ifor x in [1]<cr>endfor<esc>

nvim -u NORC file.vim
iwhile 1<cr>endwhile<esc>

OR

nvim -u NORC
{sample text}
:setf vim

Both don't highlight the keywords (for functions, I have to add the opening parens, making it `function hello(` to work)
![image](https://user-images.githubusercontent.com/38919842/49508859-1a92cd00-f884-11e8-92e7-55c3731670ea.png)
![image](https://user-images.githubusercontent.com/38919842/49508994-7bbaa080-f884-11e8-8495-b627a8de84e5.png)

I noticed this because the end of my vimrc had an endif that wasn't highlighted and I thought it was a syntax error. I'm on a6661178a.

**Comment by justinmk** [comment]
Seems like a runtime issue, maybe Nvim wasn't installed fully. Where does this go:

    :edit $VIMRUNTIME/syntax/vim/generated.vim

**Comment by LunarLambda** [comment]
/usr/local/share/nvim/runtime/syntax/vim/generated.vim
(installed from source)
Repo version goes into /usr/share/... instead.

I tried sourcing $VIMRUNTIME/syntax/vim.vim on top of the sample text but that didn't change anything either

**Comment by bfredl** [comment]
Note if you run nvim directly from the repo as `./build/bin/nvim` you need to add both `./runtime`  and `./build/runtime` to `'rtp'`. Myself I do it by setting `VIM=~/dev/neovim/` and also append `set rtp+=~/dev/neovim/build/runtime/` to the cmdline (I have a wrapper script for running nvim in various configs). Maybe there is (should be) a simpler way.

**Comment by LunarLambda** [comment]
running nvim with

`VIM=./ ./build/bin/nvim -u NORC --cmd 'set rtp+=./build/runtime' file.vim` and trying the sample text indeed works correctly (it seems), it appears my local install didn't have the $VIMRUNTIME/syntax/vim/generated.vim file, for some reason.

Running `sudo make install` on the new build has installed it properly now. Thank you, closing.

Perhaps the syntax/vim/generated.vim should be removed/merged into syntax/vim.vim, dunno what the rationale for it being there like that really is.

**Comment by bfredl** [comment]
> Perhaps the syntax/vim/generated.vim should be removed/merged into syntax/vim.vim, dunno what the rationale for it being there like that really is.

The rationale is, as the name suggests, to generate some syntax info from the actual implementation (which contains a list of commands, for instance), rather than duplicate the information (so it can become out-of-sync after impl changes). Perhaps we can add some kind of check so that `syntax/vim.vim` shows an error if `generated.vim` is missing or empty, or a more general check for `build/runtime` stuff. Further changes will be in the general direction of generating more stuff, not less.

**Comment by gwd666** [comment]
I also ran into this issue recently on WINDOWS 10 with Neovim 0.4.4    
when I run  `:edit $VIMRUNTIME/syntax/vim/generated.vim` it opens up a nice looking file but when I do a search in it for eg `endif` there are no hits?  
Is there potentially a way to somehow regenerate this file?
