### ISSUE TITLE
Neovim at flathub.org

### ISSUE THREAD

**Issue by Peque** [neovim/neovim#9318]
It would be great if Neovim could be distributed as a Flatpak package through [flathub.org](https://flathub.org).

**Comment by justinmk** [comment]
see https://github.com/flathub/flathub/pull/640

**Comment by mcepl** [comment]
However, it would be nice if the Flatpak package could be verified. @CleoMenezesJr, what would be needed?

https://github.com/flathub/io.neovim.nvim/issues/111
