### ISSUE TITLE
nvim_buf_add_highlight / nvim_buf_set_virtual_text share ids

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#9323]
The following will print the same ID (typically 1) twice, but should return differents IDs probably (to allow for clearing them separately):

```
let b = bufnr('%')
echom nvim_buf_add_highlight(b, 0, '', 0, 0, -1)
echom nvim_buf_set_virtual_text(b, 0, 0, [['foo', 'Error']], {})
```

Neovim v0.3.2-971-g769762834.

**Comment by bfredl** [comment]
Thanks for the report, I made a fix #9324
