### ISSUE TITLE
Issue revisit request: https://github.com/neovim/neovim/issues/5382

### ISSUE THREAD

**Issue by bitshiftnetau** [neovim/neovim#9329]
There should be a section in Getting started called "Config files" and the text from the following link should go there:

https://neovim.io/doc/user/nvim.html#nvim-from-vim

I actually still have no idea how to navigate to that link from the index page found here:

https://neovim.io/doc/user/index.html

The only way I know that page even exists is because someone mysteriously found it and linked it on the issue in the title. I know that sounds silly but I just spent like an hour trying to find out why neovim isn't reading from ~/.vimrc

It took me way too long to find the answer to a simple question: How to set a configuration file for neovim? 

I'd appreciate the change, if not I'd love a reason :)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/5382 was revisited many times, and we've tweaked it in various ways. 

You want it in "getting started", sure why not :) Send a PR showing what you have in mind.

> It took me way too long to find the answer to a simple question: How to set a configuration file for neovim?

- It's at the top of the [Install page](https://github.com/neovim/neovim/wiki/Installing-Neovim)
  > For config (vimrc) see the FAQ.
- It's item 3 in [the FAQ](https://github.com/neovim/neovim/wiki/FAQ):
  > Where should I put my config (vimrc)?
- It's at `:help vimrc`
- It's linked from `:help nvim`

**Comment by justinmk** [comment]
`:help config` doesn't exist, so I created it at #9288
