### ISSUE TITLE
The default value of selection is exclusive

### ISSUE THREAD

**Issue by doffltmiw** [neovim/neovim#9332]
The default value of [`selection`](https://neovim.io/doc/user/options.html#'selection') is documented as `inclusive`, and vim uses the same default. But it reports `exclusive` on my Windows 10, and I had to manually change it to `inclusive`.

I'm using [the 64-bit pre-built binary]( https://github.com/neovim/neovim/releases/download/nightly/nvim-win64.zip).

**Comment by mhinz** [comment]
My nightly build from a few days ago reports `inclusive`. Check with `:verb set sel?` if another plugin set it.

**Comment by mhinz** [comment]
Hah, no problem!
