### ISSUE TITLE
Sign location is not recovered on undo

### ISSUE THREAD

**Issue by jurov** [neovim/neovim#9333]
When deleting line with a sign, sign moves to next line (line number stays the same). But when undoing, the sign moves down to line+1 (now it does not point to previously deleted line but next one). This behavior is the same in vim, so I'm not sure if it is a bug. And if it should be changed, it's debatable what should the sign point to when line is deleted, maybe it should be removed too (like marks are)?

Sign location is denoted by SS:
#### Sign set
Line1
SS Line2
Line3

#### Line2 deleted by dd
Line1
SS Line3

#### After undo
Line1
Line2
SS Line3

#### Sign set
Line1
SS Line2
Line3

#### Line2 deleted by dd 
Line1
SS Line3

#### After undo
Line1
SS Line2
Line3

**Comment by justinmk** [comment]
related: #5031 
related: #9295 

Given that (1) Vim has the same behavior and (2) there's a lot of work happening in this area, I don't want to keep this ticket open, because it's likely to be forgotten and isn't going to be addressed directly, but indirectly by the aforementioned ongoing work.
