### ISSUE TITLE
str2float('3.3') result is locale-dependent

### ISSUE THREAD

**Issue by cvlmtg** [neovim/neovim#9340]
- `nvim --version`: NVIM v0.3.2-dev
- Vim (version: ) behaves differently? doesn't apply
- Operating system/version: macOS Mojave
- Terminal name/version: kitty 0.13.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:checkhealth
```

### Actual behaviour

```

health#provider#check
========================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    function health#check[21]..health#provider#check[3]..<SNR>33_check_python,     riga 154
    Vim(if):E806: uso di un Numero-a-virgola-mobile come Stringa
```

### Background

I recently upgraded from macOS 10.13 to 10.14 and reinstalled homebrew from scratch. I installed nvim with `brew install --HEAD nvim` and installed python 3. previously I had both python 3 and python 2 installed with brew, now I installed just python 3 since python 2 is already provided by macOS.

I suspect checkhealth doesn't work because I screwed up my python environment, but I need some help to figure out what's wrong because I really have no idea :(

here's some additional info that I hope might help

```
 ~ python --version
Python 2.7.10
 ~ python2 --version
Python 2.7.10
 ~ python2.7 --version
Python 2.7.10
 ~ python3 --version
Python 3.7.1
 ~ python3.7 --version
Python 3.7.1
 ~ pip list | grep pynvim
pynvim                                 0.3.1   
 ~ pip3 list | grep pynvim
pynvim     0.3.1  
```

thanks in advance!

**Comment by cvlmtg** [comment]
It doesn't print anything, however with some trial and error I think I've pinpointed the error source. it's on line 411:

```
    if a:version == 3 && str2float(pyversion) < 3.3
      call health#report_warn('Python 3.3+ is recommended.')
    endif
```

If I comment this piece of code I have no errors (and your debug messages get printed). however if I remove the `str2float` call I still get the error...

**Comment by mhinz** [comment]
Yeah, I know. The error happens because `str2float()` gets a float although it should get a string. (Simple test: `:echo str2float(1.0)`).

The question is why `pyversion`, which is returned by `s:version_info()` (same file), doesn't return a string in the first place.

**Comment by cvlmtg** [comment]
if I remove `str2float` I get

```

health#provider#check
========================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    function health#check[21]..health#provider#check[3]..<SNR>71_check_python, riga 154
    Vim(if):E806: uso di un Numero-a-virgola-mobile come Stringa
```

If I change the line to `if a:version == 3` I get

```

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.10
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - WARNING: Python 3.3+ is recommended.
  - INFO: Python version: 3.7.1
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.14.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

**Comment by cvlmtg** [comment]
this is strange...

```
    if a:version == 3 && 3.3 < 3.3
```

gives the error, but

```
    if a:version == 3 && 3 < 3
```

does not... 🙄

**Comment by justinmk** [comment]
> and BTW :echo str2float('3.3') returns 3,0 so it seems it might be a problem with locales?

That's definitely a problem. Does that happen in Vim (not Neovim), on your system?

**Comment by justinmk** [comment]
Root cause is likely #6474 . That issue doesn't need to be fully resolved, we could at least fix this case in the meantime.

**Comment by jamessan** [comment]
Actually, I think vim overrides an `LC_*` setting internally so all math happens in the C locale, specifically to avoid things like different decimal specifiers.

**Comment by jamessan** [comment]
Yeah, here it is.

https://github.com/vim/vim/blob/ded5f1bed7ff2d138b3ee0f9610d17290b62692d/src/main.c#L1569-L1572

**Comment by bfredl** [comment]
The issue can't be reproduced on linux. I think the issue is the extra `setlocale(LC_ALL, "");` for OS X only in `os/lang.c` that overshadows the earlier `setlocale(LC_NUMERIC, "C");` in `main.c`. The quick fix would be to just duplicate that line after also the OS X specific `setlocale()`.

**Comment by mhinz** [comment]
@cvlmtg 

Can you paste the output of `locale`? I tried to reproduce it with the `it_IT` locale, but I only get the expected result.

**Comment by cvlmtg** [comment]
```
 ~ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I was also going to give you the version of the terminal I'm using and this is what happens:

```
 ~ kitty --version
[347 12:58:31.530138] Failed to set locale with LANG: en_IT.UTF-8
kitty 0.13.1 created by Kovid Goyal
```

never heard of `en_IT` 🤔 so I did more checks and the culprit seems to be kitty... If I open nvim in terminal.app `:checkhealth` works...

I'm sorry for the wrong bug report :|

**Comment by dm1try** [comment]
actually this can be reproduced by `LANG="" LC_NUMERIC="it_IT" vim` ^

**Comment by bfredl** [comment]
Yes, the code path is for empty LANG.

**Comment by cvlmtg** [comment]
just for reference, this is what says locale on terminal.app

```
 ~ locale
LANG="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_CTYPE="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_ALL=
```
