### ISSUE TITLE
Feature request: Markdown syntax optional citation in image caption

### ISSUE THREAD

**Issue by cbcoutinho** [neovim/neovim#9343]
```shell
$ nvim --version
NVIM v0.3.2-964-g7e97587da
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/chris/Software/neovim/build/config -I/home/chris/Software/neovim/src -I/home/chris/Software/neovim/.deps/usr/include -I/usr/include -I/home/chris/Software/neovim/build/src/nvim/auto -I/home/chris/Software/neovim/build/include
Compiled by root@hak14099

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently? no
- Operating system/version: OpenSUSE Leap 15.0
- Terminal name/version: Alacritty 0.2.3
- `$TERM`: screen-256color

### Example link:

    ![My caption [@my_citation]](/path/to/image.png)

### Actual behaviour

Image links are essentially a `![]()` pattern, where the caption is text in the square brackets. Pandoc makes it possible to cite sources, and it is useful to add citations in the captions of figures directly.

Currently adding an inner level of square brackets removes the syntax highlighting for image links

I think [these](https://github.com/neovim/neovim/blob/55c5185884d707e6c59d1900a4d921038f360807/runtime/syntax/markdown.vim#L73-L76) are the offending lines.

Example link:

    ![My caption [@my_citation]](/path/to/image.png)

### Expected behaviour

Adding a second/inner level of brackets shouldn't break the syntax highlighting

**Comment by chrisbra** [comment]
Such requests should be discussed with the syntax file maintainers.

**Comment by cbcoutinho** [comment]
ping @tpope

**Comment by justinmk** [comment]
Please send to https://github.com/tpope/vim-markdown.
