### ISSUE TITLE
API: method to set v: variables,  nvim_set_vvar

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9349]
* nvim --version: NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5

I noticed there is an api method `nvim_get_vvar` but no corresponding `nvim_set_vvar`.  And yet the other get_var methods have set_var counterparts.

I was planning on using this to set `v:errmsg` from lua.  I can just use a command instead for this but thought I'd report it since thought it might be an oversight.

**Comment by justinmk** [comment]
`v:` vars are generally readonly.

**Comment by Shougo** [comment]
> `v: vars` are generally readonly.

Some `v:vars` are writable though...

**Comment by lmnotran** [comment]
Would it be okay if I tackled this as a first issue?

**Comment by justinmk** [comment]
@lmnotran There is no need to ask. Just send a PR.

**Comment by KillTheMule** [comment]
Pro tip: If you're afraid of duplicate work, send an empty PR to declare your intention to work on this. You can put `[ci skip]` as a commit message to avoid running some of the CI.

**Comment by pqzx** [comment]
#9395 I had a go at this.
I didn't find any tests for nvim_get_vvar and I didn't add tests for this one. Do we want tests for these methods?

**Comment by justinmk** [comment]
> Do we want tests 

Yes
