### ISSUE TITLE
Consistent URL for the current stable AppImage?

### ISSUE THREAD

**Issue by howardcochran** [neovim/neovim#9356]
Hello.  
The URL for the current nightly appimage is constant:
https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage

However, the URL that I have for the current stable appimage contains a version number:
https://github.com/neovim/neovim/releases/download/v0.3.1/nvim.appimage

I am writing a script which needs to download "the current stable appimage", so I wonder if there is an alternative constant URL which always points to the current stable one?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/releases/latest always redirects to the current tag:

https://github.com/neovim/neovim/releases/tag/v0.3.1

From that you can predict the appimage URL:
https://github.com/neovim/neovim/releases/download/v0.3.1/nvim.appimage

That shouldn't be too hacky to script using `curl` for example. 

AFAIK setting up a 302 redirect on [the website](https://neovim.io) will be difficult. Although maybe we could do it [with cloudflare](https://support.cloudflare.com/hc/en-us/articles/200172286-How-do-I-perform-URL-forwarding-or-redirects-with-CloudFlare-) @tarruda ?

**Comment by justinmk** [comment]
> constant URL which always points to the current stable one

Now the current stable release is pushed to the `stable` tag:

- https://github.com/neovim/neovim/releases/tag/stable
- https://github.com/neovim/neovim/releases/download/stable/nvim.appimage

**Comment by howardcochran** [comment]
THANK YOU!

**Comment by howardcochran** [comment]
@justinmk, The stable URL to the appimage that you posted above is 404 Not Found.  It looks like the latest stable release only got source code and a tarball but no appimage?

**Comment by justinmk** [comment]
@howardcochran Yes, there's a known issue with the nightly script. I'll fix it hopefully this week.

**Comment by justinmk** [comment]
@howardcochran This should be fixed now (hopefully permanently). 

https://github.com/neovim/neovim/releases/tag/stable
