### ISSUE TITLE
Clarify the :terminal documentation surrounding shell interactive-mode

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [neovim/neovim#9359]
**Update:** Solved the problem, which was, of course, on my end. Below is an updated request for a corresponding docfix!

----

I feel like there's no way this bug has made it this far — I *must* be using this wrong, somehow. Tell me if I'm being an idiot!

Quoth `:help :terminal`,

```
:te[rminal][!] [{cmd}]	Execute {cmd} with 'shell' in a new |terminal-emulator|
			buffer. Without {cmd}, start an interactive 'shell'.
```

But: allowing `:terminal` to open a shell, and then inspecting `$PATH`, yields the normal path constructed by my interactive-mode shell … whereas running a command directly, with `:terminal inspect-path-command`, yields the `$PATH` of the *neovim executable itself*. It does not appear to execute inside a shell at all.

### Steps to reproduce using `nvim -u NORC`

```
env -i nvim -u NORC
:set shell=/usr/local/bin/YOURSHELL
:terminal
<insert 'echo $PATH'>
```

vs.

```
env -i nvim -u NORC
:set shell=/usr/local/bin/YOURSHELL
:terminal echo $PATH
```

### Expected behaviour
Prints the same path, because the `ARG` in `:terminal ARG` is documented as being executed *inside a shell*.

### Actual behaviour
Prints two different paths — a full one, initialized by YOURSHELL, in the former case, but an abbreviated, one, reset by `env -i`, in the latter case.

![](http://i.ell.io/genmTn+)

**Comment by ELLIOTTCABLE** [comment]
Versions, etc:

```
❯ ~ nvim --version
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/config -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

```
- Operating system/version: **macOS 10.14 Mojave**
- Terminal name/version: Originally seen in **VimR.app**; reproduced in Mojave's **Terminal.app**
- `$TERM`: `xterm-256color`

**Comment by mhinz** [comment]
Well, do you initialize your $PATH in a config that is only read by interactive shells? (bashrc, zshrc, etc.)

When you run a shell without a command, you start an interactive session. Compare `bash -c 'echo $-'` vs. `bash -i -c 'echo $-'` (check for `i` which stands for "interactive").

Workarounds would be sourcing the `bashrc` (or similar) from `.bash_profile` or using `:set shell=YOURSHELL\ -i`.

IMHO, `$PATH` should be set up in `.bash_profile`, but they're your dotfiles. ;-)

**Comment by ELLIOTTCABLE** [comment]
That's odd. I have a pretty painstakingly-designed “setup the `$PATH` for various shell-initialization methods” system. Clearly I screwed that up years ago! I'mma go take a gander.

**Comment by mhinz** [comment]
Hmm, well, when you run a one-off command, you're obviously not using an interactive shell. When you start a shell for working, you do.

The doc states:

```
:te[rminal][!] [{cmd}]	Execute {cmd} with 'shell' in a new |terminal-emulator|
			buffer. Without {cmd}, start an interactive 'shell'.
```

This kind of implies that using `{cmd}` starts a non-interactive shell. But yes, we could add an explicit `non-interactive` as well.

BTW, Vim's `:!echo $-` is non-interactive as well.

**Comment by mhinz** [comment]
> Thus, let's call this a documentation-request for the following patch?

We will do! We collect these small doc changes in an own PR: https://github.com/neovim/neovim/pull/9335

I'll add the diff there and close this issue. Thanks!
