### ISSUE TITLE
wrong cursor position with wrapped doublewidth chars

### ISSUE THREAD

**Issue by 0mco** [neovim/neovim#9360]
- `nvim --version`: NVIM v0.3.2-996-g55c518588
- Vim (version: ) behaves differently? Vim does not suffer from this.
- Operating system/version: Ubuntu 16.04
- Terminal name/version: GNU bash, Version 4.3.48
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
To trigger the bug you have to satisfy two requirements:
1. `set nu` in neovim
2. the sentence has to be mixed with Chinese and English (maybe other languages is ok)
```
nvim -u NORC
e demo.txt
possibly adjust terminal's width to let neovim show multiple lines.
set nu
append text
```
demo:
![peek 2018-12-13 12-08](https://user-images.githubusercontent.com/13941218/49915376-45a69d80-fed0-11e8-8b64-300fd639d239.gif)
demo text:
```
 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 這是一個測試. 
```
### Actual behaviour
text appear on the wrong line.
### Expected behaviour
text appear on the right line.

**Comment by justinmk** [comment]
As a workaround, CTRL-L fixes it.

**Comment by 0mco** [comment]
@justinmk I cannot reproduce it without `set nu`, but the English words can be omitted. CTRL-L is not a workaround, you just cannot press CTRL-L every time you edit a word.

**Comment by bfredl** [comment]
What terminal is used? Is it a literal xterm? I cannot reproduce with pangoterm, at least.

**Comment by 0mco** [comment]
@bfredl it's `GNU bash`, if you cannot reproduce, you may need to add some text at the beginning, like what I did in the demo (there I added 'a, '). You may need to add more text.

**Comment by bfredl** [comment]
Tried the same steps with master `nvim -u NONE` + `set nu` in both gnome-terminal and pangoterm, adding ASCII text in various places. The issue can be seen in gnome-terminal but not in pangoterm, so seems terminal dependent. The issue seems to disappear with `'linebreak'`, so if is linebreak is acceptable, it works as a workaround.
