### ISSUE TITLE
Wayland clipboard integration in neovim

### ISSUE THREAD

**Issue by shmerl** [neovim/neovim#9365]
I find it quite useful when nvim integrates with system clipboard (by using xsel in X11 environment). I recently started experimenting with KDE Plasma Wayland session, checking what features are still missing in the overall experience. One thing I noticed is that obviously xsel is useless for Wayland clipboard so nvim loses system clipboard feature.

Is there any plan to implement Wayland clipboard integration?

**Comment by shmerl** [comment]
Hm, one thing I noticed though, xsel itself still works with Wayland clipboard, since there is some interop with xwayland I suppose.

For example this works even with Wayland session:

    printf test | xsel -i -b

There is also something called wl-paste / wl-copy, but it's not working at all for me.

**Comment by bfredl** [comment]
> There is also something called wl-paste / wl-copy, but it's not working at all for me.

What is the error? or just empty text? Are you sure you are testing against a proper wayland app, and not another x11 app via xwayland?

**Comment by shmerl** [comment]
Reported it [here](https://github.com/bugaevc/wl-clipboard/issues/19). It seems to be an issue with wl-clipboard itself.

**Comment by bfredl** [comment]
unactionable in neovim then.

**Comment by shmerl** [comment]
Hm, I was able to work around it, using xsel itself, adding this to `/usr/share/nvim/runtime/autoload/provider/clipboard.vim` before first xsel / DISPLAY part:

```
  elseif exists('$WAYLAND_DISPLAY') && executable('xsel') && s:cmd_ok('xsel -o -b') 
    let s:copy['+'] = 'xsel -i -b' 
    let s:paste['+'] = 'xsel -o -b' 
    let s:copy['*'] = 'xsel -i -p' 
    let s:paste['*'] = 'xsel -o -p' 
    return 'xsel'
```
With that, it's working! I suppose using Xwayland interop. Ideally it should use wl-clipboard though, when it will be working.

**Comment by bugaevc** [comment]
Hi, wl-clipboard maintainer here

> Are you sure you are testing against a proper wayland app, and not another x11 app via xwayland?

I don't do anything special for XWayland in wl-clipboard, but if the compositor supports syncing between Wayland and X11 clipboards — and AFAIK, all major ones do — you should be able to copy-paste from/to XWayland windows using wl-clipboard, and if it doesn't work, it's a bug (e.g. https://github.com/bugaevc/wl-clipboard/issues/7), so do report 'em to me. Thanks 😀

**Comment by shmerl** [comment]
I don't think this should be closed yet.

**Comment by bfredl** [comment]
@shmerl `wl-copy`/`wl-paste` is already configured for wayland as clipboard provider. You can use `g:clipboard` as a temporary workaround until wl-clipboard fixes the bug.

**Comment by shmerl** [comment]
Ah, good to know. Thanks!

**Comment by JasonGrace2282** [comment]
I managed to work around this with installing the `wl-clipboard-x11` package, leaving this here in case it helps anyone.

**Comment by shmerl** [comment]
What's `wl-clipboard-x11`? It works fine for me with `wl-clipboard` itself.

**Comment by JasonGrace2282** [comment]
It's basically a bash script that allows you to use `xclip` and other xorg clipboard programs, but as a wrapper for `wl-clipboardq

**Comment by LumaC0** [comment]
> Reported it [here](https://github.com/bugaevc/wl-clipboard/issues/19). It seems to be an issue with wl-clipboard itself.

I just ran into this issue when updating to KDE Plasma 6 on Arch (default display server is Wayland). `pacman -S wl-clipboard` solved the issue.

**Comment by travisddavies** [comment]
> > Reported it [here](https://github.com/bugaevc/wl-clipboard/issues/19). It seems to be an issue with wl-clipboard itself.
> 
> I just ran into this issue when updating to KDE Plasma 6 on Arch (default display server is Wayland). `pacman -S wl-clipboard` solved the issue.

This worked, thank you!!
