### ISSUE TITLE
Not sure if patch 8.0.0210 is applicable

### ISSUE THREAD

**Issue by afnanenayet** [neovim/neovim#9373]
So I'm a little confused as to the status of this patch, and just wanted to check with you guys.

I suspect patch 8.0.0210 is not applicable (it's a commit to enable bracketed paste). When I tried to apply the patch, almost every patch hunk was rejected, and it seems like there's some heavy modification of `term.[ch]`,  which neovim doesn't use.

I saw another PR was raised for this, which was #8237, but it's empty and was closed, so I'm not entirely sure what's going on there.

Sorry for the confusion! I'm just getting started with neovim's codebase/workflow.

**Comment by fmoralesc** [comment]
Nvim is supposed to enable bracketed paste by default (see `:help bracketed-paste-mode`), at least since sometime in 2015 (https://github.com/neovim/neovim/blame/7a8dadbedb0ba15e67b198774bb87caad1e22828/runtime/doc/term.txt#L260). So 8.0.0210 is not applicable.

**Comment by jamessan** [comment]
I'm pretty sure there are some behavioral differences between Vim and Neovim in the bracketed paste implementations.  What someone needs to do is look into _that_ and see whether any relevant changes should be made to Neovim.
