### ISSUE TITLE
Suggestion: New autocommand to intercept echom

### ISSUE THREAD

**Issue by svermeulen** [neovim/neovim#9374]
* nvim --version: NVIM v0.3.2-707-g082e14557, LuaJIT 2.0.5

As far as I can tell, there's no way to observe changes to the `:messages` buffer.  What would be great is if there was an autocommand for whenever an `:echom` or `:echoerr` occurs.

In my case, I'd find this useful because I use a custom log file that I'd like to also contain general vim messages.  If this autocommand existed I could hook into it and then call `:1messages` to get the most recent message

**Comment by bfredl** [comment]
Dup of #9158
