### ISSUE TITLE
Native Neovim support for displaying search match index like `(n of N)`

### ISSUE THREAD

**Issue by rburny** [neovim/neovim#9378]
When iterating through search matches with the `n` mapping, could vim display the match count and index of the current match in the list of matches? Instead of just displaying `/in` in the message area when you search for `in`, it could display `[1/7] /in`, `[2/7] /in`, etc. as you step through.

There are plugins https://github.com/google/vim-searchindex and https://github.com/henrik/vim-indexed-search that implement this somewhat effectively in vimscript, but they have a lot of quirks to work around.

----

This issue is a mirror of an analoguous [Vim issue](https://github.com/vim/vim/issues/453). Although @chrisbra has created [a working patch](https://github.com/vim/vim/issues/453#issuecomment-446274867), it was not merged into Vim for 3 years. Would it be possible to merge it into Neovim?

**Comment by justinmk** [comment]
That patch will land in Vim pretty soon, I bet. Or feel free to send a PR. Don't need an issue for this.
