### ISSUE TITLE
Dependencies not building static versions on Clear Linux 

### ISSUE THREAD

**Issue by ngaloppo** [neovim/neovim#9380]
- `nvim --version`: master branch
- Operating system/version: Clear Linux 26800

### Steps to reproduce

```
mkdir .deps && cd .deps
cmake ../third-party
make
```

### Actual behaviour

```
$ ls usr/lib
cmake  libjemalloc.a  libjemalloc_pic.a  libluajit-5.1.a  libluv.a  libmsgpackc.a  libtermkey.la  libunibilium.la  libuv.a  libuv.la  libvterm.la  lua  luarocks  pkgconfig
```

### Expected behaviour

On an Ubuntu system: libunibilium.a is present.
```
$ ls usr/lib
cmake  libjemalloc.a  libjemalloc_pic.a  libluajit-5.1.a  libluv.a  libmsgpackc.a  libtermkey.a  libtermkey.la  libunibilium.a  libunibilium.la  libuv.a  libuv.la  libvterm.a  libvterm.la  lua  luarocks  pkgconfig
```

This seems to be related to the fact that libtool is creating `.a` archives on an Ubuntu system, but not on the Clear Linux system. Both systems have libtool version 2.4.6 installed, so there must be some other environmental or dependent tool that's causing this. In particular, when comparing the `make` build output from both systems, the last two lines in the following are present on the Ubuntu system, but not on the Clear system (both systems produce the unibilium shared library .so's in the end, though).

```
libtool --mode=link --tag=CC cc  -rpath '/usr/local/lib' -version-info 4:0:0 -o libunibilium.la unibilium.lo uninames.lo uniutil.lo^M
libtool: link: gcc -shared  -fPIC -DPIC  .libs/unibilium.o .libs/uninames.o .libs/uniutil.o      -Wl,-soname -Wl,libunibilium.so.4 -o .libs/libunibilium.so.4.0.0^M
libtool: link: (cd ".libs" && rm -f "libunibilium.so.4" && ln -s "libunibilium.so.4.0.0" "libunibilium.so.4")^M
libtool: link: (cd ".libs" && rm -f "libunibilium.so" && ln -s "libunibilium.so.4.0.0" "libunibilium.so")^M
libtool: link: ar cru .libs/libunibilium.a  unibilium.o uninames.o uniutil.o^M
ar: `u' modifier ignored since `D' is the default (see `U')^M
```

**Comment by justinmk** [comment]
This is most likely a question for CMake or Clear Linux. If there's a specific change we need to make, let us know.
