### ISSUE TITLE
missing inspirational dog.

### ISSUE THREAD

**Issue by mick-io** [neovim/neovim#9385]
- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently? 8.1
- Operating system/version: Mac OS Mojave
- Terminal name/version:
- `$TERM`: iTerm2

### Actual behaviour

![screen shot 2018-12-21 at 11 09 23 am](https://user-images.githubusercontent.com/23181878/50356867-06e89700-0511-11e9-841b-de3a1bc4e2ec.png)

### Expected behaviour

![screen shot 2018-12-21 at 10 35 01 am](https://user-images.githubusercontent.com/23181878/50356913-30092780-0511-11e9-999c-477f49494e13.png)

**Comment by mschilli87** [comment]
1. [It's a cow!](https://en.wikipedia.org/wiki/Cowsay)
2. Is this really relevant? There are > 650 open issues right now. This doesn't really strike me as important. Maybe I'm missing something. If this is is just for the record great. If this is a request to make somebody else spend time fixing this, I surely hope other issues get priority over this. :wink:

**Comment by mhinz** [comment]
Maybe you have installed [mhinz/vim-startify](https://github.com/mhinz/vim-startify) for Vim but not Nvim?

It's certainly not an Nvim issue. ;-)

**Comment by mick-io** [comment]
@mhinz I didn't notice it was a plugin, I thought it was part of the update. I'll close the ticket.
@mschilli87 You're right, it is a cow and it's not a priority.
