### ISSUE TITLE
Exiting nested nvim buffers return to the terminal from which they were started

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [neovim/neovim#9387]
This feature suggestion relies a lot on https://github.com/mhinz/neovim-remote.

### Steps to reproduce

```
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get install neovim python3-pip
pip3 install neovim-remote

echo "alias vi='nvr -s'" >> ~/.bashrc 
echo "alias vim='nvr -s'" >> ~/.bashrc 

echo dummy_content > dummy_content_file
vi
:terminal
vi dummy_content_file
:wq 
```

### Actual behavior

Once the final `:wq` is pressed there is no more instances of vim running.

### Expected behavior

Given that `:wq` was triggered from a conceptually nested nvim, on exit it should exit to the nvim
terminal from where it was originally called.

### Reasoning

To put it into context, perhaps think about the flow if the application you were starting wasn't another nvim instance. You probably don't want the terminal window to close once you've exited the app.

**Comment by mhinz** [comment]
I don't understand the rationale behind this suggestion.

The whole point of `nvr` is not to start a nested nvim process. A `nvr file` will imply use the API to tell the current nvim process to `:edit file`.

There is no way to distinguish between a `:edit file` typed in by the user or a `:edit file` command sent through the API.

But you want to _not_ start a nested process on purpose, but `:wq` to behave as if it was? That makes sense at all to me. :)

> To put it into context, perhaps think about the flow if the application you were starting wasn't another nvim instance. You probably don't want the terminal window to close once you've exited the app.

No process other than nvim could ever be _not_ "nested". Do I miss the point? Can you give a concrete example?

**Comment by TheMeaningfulEngineer** [comment]
@mhinz 
I seem to have been unskillfully using the term `nested` sorry.

> The whole point of nvr is not to start a nested nvim process.

Yes, you are correct. My perspective of the idea behind it is that it solves nesting problems:
* no additional processes spawned
* no key-press ambiguity (parent reacting to the key-press intended for the child)  

> But you want to not start a nested process on purpose, but :wq to behave as if it was? That makes sense at all to me. :)

Yes! :) 
I am arguing for a distinction between a file opened by `:e file` versus `nvr file` invoked from the nvim terminal. 

* `:e file` - is a first class buffer that is behaving as you'd expect in the nvim world
* `nvr file` invoked from the nvim terminal - is conceptually a child of the terminal otherwise why not just start it with `e file`

I think the base of our misunderstanding is on the nature of the terminal. You're perhaps looking at it more technically as a buffer in nvim and that it how it should act. I'm perceiving it primarily as terminal that has the best possible nvim integration, but when needing to behave as "a terminal" vs "a vim buffer" it resembles the behavior of a terminal.

If you start `nvim` in a regular (not from `:terminal`), you would expect typing `wq` would bring you back to the prompt you were before, no?

> No process other than nvim could ever be not "nested". Do I miss the point? Can you give a concrete example?

For example the flow of doing a `git commit`. Once you type it into the neovim terminal, the buffer to insert the message overtakes the terminal it was started from.

**Comment by mhinz** [comment]
Ah, I see. You're referring to https://github.com/mhinz/neovim-remote/issues/96.

E.g. you want `:x` to close the `COMMIT_EDITMSG` buffer opened by `git commit`, no matter whether it was typed in a regular shell or `:terminal`. You don't want the outer process to exit in the latter case. Correct?

If it's just for the commit message, I would not use nvr at all in your case. A nested process in `:terminal` can get treated the same way as when started form a regular shell.

Anyway, you probably mean a general solution and I honestly don't see that happening. This would be super hard to get right. Alone all the commands that somehow effect the buffer or window would have to be changed to take this `virtually_nested = true` flag into account.

The use cases simply don't justify that amount of changes (and hence all the bugs). Maybe the tooling around `:terminal` can be improved, but I see no way something like this ever lands in the core editor.

Sorry. :-)

**Comment by ELLIOTTCABLE** [comment]
So, I don't think default commands should be modified as per the OP, here; but I *do* think this sort of use-case can be better implemented.

What about having a setting that can be referred to, when 'remote' windows are opened from a terminal? `nvr` could do the work (possibly supported by much-less-intense changes upstream, here, in Neovim) to determine which buffer the invocation ‘came from’; and then pass along that information to opened buffers as a buffer-local variable/setting/whatever.

That would give us the *tools* to do things like what the OP wants, in plugins or little VimL snippets. For instance, a user-command like `:WQ` to close and delete *all* buffers opened by the most recent `nvr` invocation, and immediately switch to the tabpage/buffer that that invocation occurred in, would be eminently possible … whereas doing it right now would be really painful.

Does that make sense?

**Comment by mhinz** [comment]
When you use nvr with any of the _wait_ options, like in the case of `git commit`, all buffers waited for will have `b:nvr`. It has a list of all connected clients for broadcasting purposes.

So... I guess you could do something like:

```vim
command! WQ execute 'bdelete' join(map(filter(getbufinfo(), {_, buf -> has_key(buf.variables, 'nvr')}), {_, buf -> buf.name}))
```
