### ISSUE TITLE
:terminal : latest libvterm allows us to avoid "palette index" hack

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9393]
via @leonerd :

> latest libvterm has changes to VTermColor API - new functions required otherwise colours will be all wrong. But as a plus side: you now get per-cell index information if available

related https://github.com/neovim/neovim/pull/7406 https://github.com/neovim/neovim/issues/4099  https://github.com/neovim/neovim/issues/4696  https://github.com/neovim/neovim/issues/7018  https://github.com/neovim/neovim/pull/7406 https://github.com/neovim/neovim/issues/8301

**Comment by leonerd** [comment]
Working on a fix at https://github.com/neovim/neovim/pull/9494
