### ISSUE TITLE
Use of '%{ }' not workin in 'titleold' but works in 'titlestring'

### ISSUE THREAD

**Issue by fszymanski** [neovim/neovim#9396]
- `nvim --version`:
```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b/build/config -I/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b/src -I/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b/.deps/usr/include -I/usr/include -I/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b/build/src/nvim/auto -I/build/neovim-6owSoW/neovim-0.3.1+ubuntu2+git201812232022-e9685d9-7936b7b/build/include
Compiled by buildd@lcy01-amd64-006

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? I did not check
- Operating system/version: Ubuntu 18.10
- Terminal name/version: kitty 0.11.3
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC

:set title
:set titlestring=%{'nvim:'.getpid().':'.getcwd()}
:set titleold=%{fnamemodify(&shell,':t')}
```

### Actual behaviour
The `titlestring` is evaluated to ex: `nvim:11087:/home/username` but after `:q` the window title is set to `%{fnamemodify(&shell,':t')}`.

### Expected behaviour
The `titleold` should be evaluated and window title set to ex: `bash`, `zsh`, etc.

**NOTE**: I know that I can achieve the desired result with `let &titleold = fnamemodify(&shell, ':t')` but I was just curious why `%{ }` works in `titlestring` but not in `titleold`.

**Comment by justinmk** [comment]
Vim 8.1 has the same behavior.

> I was just curious why %{ } works in titlestring but not in titleold.

`titleold` is a fallback, most likely it wasn't worth the effort. Patch welcome if it includes a test, otherwise this is wontfix.

**Comment by fszymanski** [comment]
Thanks @justinmk.
