### ISSUE TITLE
UpdateRemotePlugins crashes when printing in pynvim plugin constructor

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#9397]
Given `~/.config/nvim/rplugin/python/debug_issue3757.py`:
```python
import pynvim


@pynvim.plugin
class Limit(object):
    def __init__(self, vim):
        print(vim.current.window)
```

Calling `:UpdateRemotePlugins` crashes Neovim:
```
remote/host: python3 host registered plugins []                                                                                                                                     
remote/host: python host registered plugins []
remote/host: generated rplugin manifest: /home/user/.local/share/nvim/rplugin.vim
Press ENTER or type command to continuenvim: ../src/nvim/event/wstream.c:78: wstream_write: Assertion `!stream->closed' failed.
                                                                                                                               [2]    8049 abort (core dumped)  nvim ~/.config/nvim/rplugin/python/debug_issue3757.py
```

I assume that you should not print from there, but it should also not crash I assume?

NVIM v0.3.2-1045-g9ac1e2db7

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/8883 may help, or is at least related.

**Comment by bfredl** [comment]
This is essentially https://github.com/neovim/pynvim/issues/60. `stdout` should really always be renamed in an rplugin context, subprocess stdout is just a special case of any stdout.

**Comment by justinmk** [comment]
https://github.com/neovim/pynvim/pull/377

**Comment by roro47** [comment]
Hi, this error still exists on neovim on mac.

**Comment by justinmk** [comment]
@roro47 Review the discussion above. Report exact version of pynvim. Use `:checkhealth` .

**Comment by roro47** [comment]
pynvim version: 0.3.2 for python2 and python3

**Comment by bfredl** [comment]
maybe the issue that are affecting you is really https://github.com/neovim/pynvim/pull/384 .  I will try to fix the travis issues there and merge it.
