### ISSUE TITLE
Buffer KeyError Crash with deoplete/fzf/airline

### ISSUE THREAD

**Issue by duganchen** [neovim/neovim#9399]
- `nvim --version`:

Output:

    NVIM v0.3.2-1045-g9ac1e2db7
    Build type: RelWithDebInfo
    LuaJIT 2.0.5
    Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
    Compiled by travis@travis-job-0d168c86-bcf7-4eae-9d2f-8e4f7c2f3072

    Features: +acl +iconv +jemalloc +tui
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "
    /home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
    "

    Run :checkhealth for more info

- Vim (version: ) behaves differently? YES

Output:

    VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec  1 2018 08:42:39)
    Included patches: 1-552
    Compiled by <volkerdi@slackware.com>
    Huge version without GUI.  Features included (+) or not (-):
    +acl               +extra_search      +mouse_netterm     +tag_old_static
    +arabic            +farsi             +mouse_sgr         -tag_any_white
    +autocmd           +file_in_path      -mouse_sysmouse    -tcl
    +autochdir         +find_in_path      +mouse_urxvt       +termguicolors
    -autoservername    +float             +mouse_xterm       +terminal
    -balloon_eval      +folding           +multi_byte        +terminfo
    +balloon_eval_term -footer            +multi_lang        +termresponse
    -browse            +fork()            -mzscheme          +textobjects
    ++builtin_terms    +gettext           +netbeans_intg     +timers
    +byte_offset       -hangul_input      +num64             +title
    +channel           +iconv             +packages          -toolbar
    +cindent           +insert_expand     +path_extra        +user_commands
    +clientserver      +job               +perl              +vartabs
    +clipboard         +jumplist          +persistent_undo   +vertsplit
    +cmdline_compl     +keymap            +postscript        +virtualedit
    +cmdline_hist      +lambda            +printer           +visual
    +cmdline_info      +langmap           +profile           +visualextra
    +comments          +libcall           +python/dyn        +viminfo
    +conceal           +linebreak         +python3/dyn       +vreplace
    +cryptv            +lispindent        +quickfix          +wildignore
    +cscope            +listcmds          +reltime           +wildmenu
    +cursorbind        +localmap          +rightleft         +windows 
    +cursorshape       -lua               -ruby              +writebackup
    +dialog_con        +menu              +scrollbind        +X11
    +diff              +mksession         +signs             +xfontset
    +digraphs          +modify_fname      +smartindent       -xim
    -dnd               +mouse             +startuptime       -xpm
    -ebcdic            -mouseshape        +statusline        +xsmp_interact
    +emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
    +eval              +mouse_gpm         +syntax            -xterm_save
    +ex_extra          -mouse_jsbterm     +tag_binary
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -fPIC -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc

- Operating system/version: Slackware64-Current and OS X

- Terminal name/version: Alacritty 0d47cd2 
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

Sorry, this is the minimal ~/.config/nvim/init.vim to reproduce this reliably:

    set runtimepath+=~/.fzf

    packadd minpac
    call minpac#init()

    call minpac#add('Shougo/deoplete.nvim')
    call minpac#add('junegunn/fzf.vim')
    call minpac#add('vim-airline/vim-airline')
    let g:deoplete#enable_at_startup = 1
    nnoremap <leader>b :buffers<cr>:b<space>

If I do: "\b\<ESC\>:Buffers\<ENTER\>\b\<ESC\>:Buffers\<Enter\>", then I get a crash. I do not get this crash with the same vimrc in Vim 8!

### Actual behaviour

    error caught in async handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'BufDelete', 'sources': []}]'
    Traceback (most recent call last):
      File "/home/dugan/.config/nvim/pack/minpac/start/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 47, in on_event
        self._deoplete.on_event(context)
      File "/home/dugan/.config/nvim/pack/minpac/start/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 125, in on_event
        self._context._init_cached()
      File "/home/dugan/.config/nvim/pack/minpac/start/deoplete.nvim/rplugin/python3/deoplete/context.py", line 74, in _init_cached
        bufname = self._vim.buffers[int(bufnr)].name
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/api/nvim.py", line 475, in __getitem__
        raise KeyError(number)
    KeyError: 3

### Expected behaviour

The buffer list is displayed

(As mentioned, I can reproduce this very reliably with Neovim, but it does not happen with Vim 8. Did Neovim's buffer-handling, or something similar, change?)

**Comment by mhinz** [comment]
cc @Shougo

**Comment by Shougo** [comment]
I don't know why `vim.buffers` does not have the item.
I think deoplete should not use the object directly.

I have fixed it in deoplete side.
Please update deoplete.

**Comment by mhinz** [comment]
@Shougo 

Was it merely a bug in deoplete or is there anything that has to be fixed in pynvim? The compatablity layer for `vim.buffers` seems to work as expected in my quick tests.

**Comment by duganchen** [comment]
Well. Now I no longer have issues with deoplete, but now if I do ":list\<c\r>:b\<space\>\<esc\>:Buffers\<enter\>" _three_ times, then I get a similar crash from Chromatica.

init.vim:

    set runtimepath+=~/.fzf

    packadd minpac
    call minpac#init()

    call minpac#add('arakashic/chromatica.nvim')
    call minpac#add('junegunn/fzf.vim')
    call minpac#add('vim-airline/vim-airline')
    nnoremap <leader>b :buffers<cr>:b<space>

    if filereadable('/usr/local/opt/llvm/lib/libclang.dylib')
            let g:chromatica#libclang_path='/usr/local/opt/llvm/lib/libclang.dylib'
    elseif filereadable('/usr/lib64/libclang.so')
            let g:chromatica#libclang_path='/usr/lib64/libclang.so'
    endif
    let g:chromatica#enable_at_startup=1

The crash:

    error caught in async handler 'chromatica_parse [{'bufnr': 4, 'filename': '', 'changedtick': 2, 'position': [1, 1], 'highlight_tick': 0, 'range': [1, 1], 'rpc': 'chromatica_parse'}]'
    Traceback (most recent call last):
      File "/home/dugan/.config/nvim/pack/minpac/start/chromatica.nvim/rplugin/python3/chromatica/__init__.py", line 44, in parse
        self.__chromatica.parse(context)
      File "/home/dugan/.config/nvim/pack/minpac/start/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 125, in parse
        if not self._init_context(context): return ret
      File "/home/dugan/.config/nvim/pack/minpac/start/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 106, in _init_context

        filetype = buffer.options["filetype"]
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/api/common.py", line 88, in __getitem__
        return self._get(key)
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/api/common.py", line 51, in request
        return self._session.request(name, self, *args, **kwargs)
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
        res = self._session.request(name, *args, **kwargs)
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
        raise self.error_wrapper(err)
    pynvim.api.nvim.NvimError: b'Invalid buffer id'

I do want to point out that in both cases, I have airline in the minimal init.vim to reproduce it. That's not an oversight. Neither crash happens if I remove airline.

**Comment by Shougo** [comment]
@mhinz I think it is pynvim's problem.
If remote plugins uses buffer object asynchronously, it sometimes fail.

**Comment by Shougo** [comment]
Similar problem is occurred in deoplete buffer source.

**Comment by mhinz** [comment]
Okay, thanks to both of you.

@neovim/core Please transfer this issue to pynvim.

**Comment by justinmk** [comment]
To avoid a race when requesting buffer data, use server-side Lua or VimL, or use `nvim_call_atomic`:

```
if bufvalid(...) then ... | end
```
