### ISSUE TITLE
clipboard.vim hangs during startup

### ISSUE THREAD

**Issue by hugomg** [neovim/neovim#9402]
Sometimes, when I start up neovim it hangs there displaying just a blank screen. Output from `nvim -V` revealed that the culprit was clipboard.vim, which appears to be stuck in an infinite loop, or waiting forever for some blocking operation to complete. I am not proficient enough with vimscript to pinpoint the exact problem though.

This might be related to bug #7184, but is probably something else. The fix for that issue is included in my clipboard.vim but I still have problems. My neovim is also hanging up at a different time (during startup). 

Here is what I know so far:
* The bug seems to be related to system state. If nvim hangs at startup in one terminal window it will hang in all terminal windows. If it is working fine then it will also work fine if I open it in another window.
* It doesn't matter what file I am trying to open.
* Logging out and logging back in again can make the problem go away.
* Changing the contents of the system clipboard can make the problem go away.
* Commenting out the `set clipboard=unnamedplus` line from my init.vim makes the problem go away.

I still don't know how to reliably reproduce the issue though. If I encounter it again I will try to remember to see what the contents of the clipboard are, and whether that can affect it. It certainly doesn't help that I only find this bug intermittently...

----------------------------------

- `nvim --version`: v0.3.1
- Vim (version: ) behaves differently? Not applicable
- Operating system/version: Fedora 29
- Terminal name/version: gnome-terminal
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I'm still trying to find a reliable reproduction. Suggestions welcome :)

That said, one of the times the problem showed up I managed to reduce my init.vim to the following, while still displaying the bug:

    set shell=/bin/sh "vim gets confused by fish shell
    set clipboard=unnamedplus

### Actual behaviour

Neovim hangs at startup, displaying nothing but a black screen. Keyboard shortcuts don't work so I must close by exiting the terminal.

### Expected behaviour

I expected it not to get stuck at startup.

**Comment by justinmk** [comment]
What does `:checkhealth` report for the "clipboard" section?

> seems to be related to system state. If nvim hangs at startup in one terminal window it will hang in all terminal windows

Almost certainly this is xclip or xsel fighting some other program for ownership of the X clipboard. 

There were some clipboard improvements in 0.3.2, please try it: https://github.com/neovim/neovim/releases

Thanks for the thoughtful and detailed report!

**Comment by justinmk** [comment]
No reply, closing.

**Comment by hugomg** [comment]
I was waiting for the problem to manifest again before replaying (it only shows up every couple of days)

When everything is working fine (as right now) the `:checkhealth` says

```
## Clipboard (optional)
  - OK: Clipboard tool found: xsel
```

**Comment by justinmk** [comment]
yeah, it might work better with xclip. Nvim 0.3.2 defaults to xclip instead of xsel.

**Comment by hugomg** [comment]
Maybe xsel's timeout flag could come in handy:

```
 -t ms, --selectionTimeout ms
              Specify the timeout in milliseconds within which  the  selection
              must  be  retrieved.  A  value  of 0 (zero) specifies no timeout
              (default).
```

**Comment by justinmk** [comment]
did you try xclip?

**Comment by hugomg** [comment]
Yes but I will only be able to try it "for real" when the intermittent bug shows up again.

**Comment by hugomg** [comment]
Problem showed up again today.

Neovim managed to launch successfully with xclip. However, if both xclip and xsel were installed, xsel would take precedence. I had to uninstall xsel.

**Comment by justinmk** [comment]
> if both xclip and xsel were installed, xsel would take precedence. I had to uninstall xsel.

Not since Nvim 0.3.2

**Comment by sisrfeng** [comment]
> Changing DISPLAY causes Neovim to hang at launch. Removing NERDTree solves the problem.
+1

`apt remove xsel && apt install xclip`  saved me
