### ISSUE TITLE
Windows: exepath() does not include $PATHEXT extension

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#9403]
- `nvim --version`: 0.3.2
- Vim (version: ) behaves differently? yes
- Operating system/version: win7
- Terminal name/version: neovim-qt
- `$TERM`: cmd.exe

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo exepath('cmd')
```

### Actual behaviour

In gvim, I can see `C:\Windows\system32\cmd.EXE`, but in neovim, only see `C:\Windows\system32\cmd`

### Expected behaviour

as the help file said, exepath() returns the full path, so It should included `.EXE` or `.exe`

**Comment by janlazo** [comment]
In `src/nvim/os/fs.c`, `os_can_exe` uses `is_executable_ext` for going through the `PATHEXT` values but it does not return the matched extension. Adding an additional parameter to `is_executable_ext` to return the matched extension or the resolved executable name should fix it.

**Comment by sameshl** [comment]
Hello,I am new here and would like to start contributing.Can I start with this issue?
