### ISSUE TITLE
no user config (vimrc) with LC_CTYPE=C

### ISSUE THREAD

**Issue by moshen** [neovim/neovim#9405]
- `nvim --version`: 

```
NVIM v0.3.2-1045-g9ac1e2db7
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Vim (version: ) behaves differently?

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 31 2018 11:16:13)
Included patches: 1-22
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby/dyn          -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -I/usr/include/ncursesw  -march=x86-64 -mtune=generic -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector -pipe -Wl,--as-needed -o vim.exe        -lm    -lncursesw -liconv -lacl -lintl   -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

- Operating system/version: Microsoft Windows 10 Pro
- Terminal name/version: cmd
- `$TERM`:  (Does this apply on Windows?)

### Steps to reproduce using `nvim -u NORC`

Not sure if this applies?

### Actual behaviour

`git commit` using Git for Windows (msys) from https://git-scm.com/ spawns `nvim` and Neovim doesn't load my vimrc.  `echo $MYVIMRC` returns nothing.

Launching `nvim` by itself works fine.

### Expected behaviour

`git commit` spawns `nvim` and my init is loaded.

### Other notes

Initially I thought this was a neovim-qt issue, but found that bare nvim does the same thing: https://github.com/equalsraf/neovim-qt/issues/481

**Comment by justinmk** [comment]
well, git is changing the environment somehow. Vim does more backflips to guess the home directory AFAIR.

To see what's different about the environment, compare this result in each case:

    :put =execute('!set')

**Comment by moshen** [comment]
Made a ticket because this used to work on a Windows 7 machine.  First time trying this in Windows 10 (don't do that much work on Windows) and it doesn't seem to work.

Notable differences bet `!set` between `nvim` and the msys built-in `vim` are:

- `nvim` has `USERPROFILE` unquoted, vs `vim` single quotes (otherwise correct)
  - Same for `LOCALAPPDATA`
- `nvim` does not have `VIMHOME` set at all
- `nvim` does not have `MYVIMRC` set at all

Even specifying `VIMHOME` and `VIMINIT` globally, my vimrc is not loaded (however the environment exists in `nvim` at runtime).

**Comment by moshen** [comment]
![image](https://user-images.githubusercontent.com/168513/50531457-40547000-0ad8-11e9-8aa5-ebcd06941855.png)

Also noticed that when I set `core.editor` to something like `nvim -u "C:/Users/moshen/vimrc"` that `nvim` segfaults.

**Comment by justinmk** [comment]
Looks like $HOME is missing on the right side.

In any case, the Windows build of `nvim.exe` currently isn't equipped to run in mintty/cygwin/msys2, though there is work being done.

**Comment by moshen** [comment]
The right side is just calling `nvim` directly.

Through process of elimination I figured out that having `LC_CTYPE=C` set, would cause `nvim` to not load my init.  I wrapped launching Neovim from git in a script which unsets that environment variable and it works as expected.  All other environment is left unmodified.

**Comment by mhinz** [comment]
@justinmk 

yrp (from Freenode) mentioned that this issue is probably fixed by https://github.com/neovim/neovim/pull/9493 as well.

**Comment by moshen** [comment]
That is correct.  To test in a windows cmd shell:

```
set LC_CTYPE=C
nvim
```

**Comment by yrp604** [comment]
Just as a kinda weird datapoint, this build: https://ci.appveyor.com/project/neovim/neovim/builds/21577611/job/kqurmwd4omc8ek0g/artifacts does _not_ exhibit this bugged behavior, while the v.0.3.4 release build does.

In the build I linked above, when spawning from `git commit` the `LC_CTYPE=C` as well.

**Comment by justinmk** [comment]
@yrp604 Thanks, that could be a clue. It's a MINGW build, whereas the releases are MSVC builds.

**Comment by yrp604** [comment]
Yeah, that appears right. The MINGW builds of v0.3.4 don't exhibit this behavior while the MSVC ones do. v0.3.1 with MSVC also wasn't affected, so something changed between then and now.

**Comment by yrp604** [comment]
Some more details: I think this is also what will cause nvim to create '~' directories everywhere. Or at least, switching to the mingw fixes this issue as well.

**Comment by justinmk** [comment]
The good thing about the MSVC build is that it is easy to debug using MSVC. Would be quite helpful if someone could do so.

**Comment by mletterle** [comment]
> The right side is just calling `nvim` directly.
> 
> Through process of elimination I figured out that having `LC_CTYPE=C` set, would cause `nvim` to not load my init. I wrapped launching Neovim from git in a script which unsets that environment variable and it works as expected. All other environment is left unmodified.
> 
> My script looks like this (and is in my `$PATH`):
> 
> nvim-launcher
> 
> ```shell
> #!/bin/bash
> 
> export LC_CTYPE=""
> nvim-qt --maximized "$*"
> ```
> 
> And is referenced in my `.gitconfig` like so:
> 
> ```
> [core]
>   editor = nvim-launcher
> ```

Thank you for this! I actually popped a similar script in git's `usr/bin` directory and named it `nvim-qt` and my sanity is restored!

**Comment by p-groarke** [comment]
on windows, fix it with
`git config --global core.editor "set LC_CTYPE='en_US.UTF-8';nvim"`

**Comment by 3N4N** [comment]
> Made a ticket because this used to work on a Windows 7 machine. First time trying this in Windows 10 (don't do that much work on Windows) and it doesn't seem to work.
> 
> Notable differences bet `!set` between `nvim` and the msys built-in `vim` are:
> 
>     * `nvim` has `USERPROFILE` unquoted, vs `vim` single quotes (otherwise correct)
>       
>       * Same for `LOCALAPPDATA`
> 
>     * `nvim` does not have `VIMHOME` set at all
> 
>     * `nvim` does not have `MYVIMRC` set at all
> 
> 
> Even specifying `VIMHOME` and `VIMINIT` globally, my vimrc is not loaded (however the environment exists in `nvim` at runtime).

Seems the problem was with "`nvim` does not have `MYVIMRC` set at all."  I came to this assumption because the output of `::put =execute('!set')` now contains `MYVIMRC` and the problem this ticket describes does not arise anymore.

My system specs are:

```
Neovim: NVIM v0.9.0
OS:  Windows 11 Pro Version 22H2 Build 22621.1702
Git-for-Windows: version 2.38.0.windows.1
```
