### ISSUE TITLE
Custom margin between line numbers and text

### ISSUE THREAD

**Issue by malyutinegor** [neovim/neovim#9410]
Can I customize space between line numbers and code?

**Comment by justinmk** [comment]
Duplicate of https://github.com/neovim/neovim/issues/6092 

(to find that issue I searched for "margin" : https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+margin )

**Comment by malyutinegor** [comment]
It has not been updated since 2017
