### ISSUE TITLE
Source $MYVIMRC doesn't apply changes in all windows

### ISSUE THREAD

**Issue by astier** [neovim/neovim#9412]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? No.
- Operating system/version: Arch
- Terminal name/version: GNOME Terminal 3.30.2
- `$TERM`: bash: xterm-256color

### Steps to reproduce using

0. Disable numbers in vimrc: *set nonu*
1. Restart nvim
1. Create two windows in nvim
2. Open in one window vimrc
3. Enable numbers: *set nu*
3. Source vimrc: *:so $MYVIMRC*

### Actual behaviour

Only in the window where the source-command was executed the numbers appear. In the other window however not. One has to source the vimrc in every window in order to apply the changes from the vimrc.

### Expected behaviour

When the vimrc is sourced in one window then it also should be sourced in all the other windows.

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
