### ISSUE TITLE
System remote plugin manifest

### ISSUE THREAD

**Issue by timokau** [neovim/neovim#9413]
I'm not sure if the issue tracker is the right place for this, please close if it isn't.

The [Nix](https://nixos.org/nix/) package manager allows users to install (neo-)vim with plugins. Currently, the user will then have to manually call `UpdateRemotePlugins`. I would like to fix that by providing a system `rplugin.vim`.

However I don't want to completely override the user rplugin.vim. That would be confusing for the user who may have additional plugins installed manually. So I want

- `UpdateRemotePlugins` to work as before
- both the system `rplugin.vim` and the user `rplugin.vim` to be read

One possible approach would be to set `NVIM_RPLUGIN_MANIFEST` to point to the system manifest, which then has `source stdpath('data') . '/rplugin.vim')` as its last line. That will break `UpdateRemotePlugins` however and will likely fail because neovim throws an exception when the same plugin is registered twice.

Instead I am now experimenting with patching neovim like this:

```patch
diff --git a/runtime/autoload/remote/host.vim b/runtime/autoload/remote/host.vim
index 6266b312b..965fabf1e 100644
--- a/runtime/autoload/remote/host.vim
+++ b/runtime/autoload/remote/host.vim
@@ -71,7 +71,8 @@ function! remote#host#RegisterPlugin(host, path, specs) abort
 
   for plugin in plugins
     if plugin.path == a:path
-      throw 'Plugin "'.a:path.'" is already registered'
+      " plugin already registered
+      return
     endif
   endfor
 
diff --git a/runtime/plugin/rplugin.vim b/runtime/plugin/rplugin.vim
index 122d8d47f..83fbf8b57 100644
--- a/runtime/plugin/rplugin.vim
+++ b/runtime/plugin/rplugin.vim
@@ -54,6 +54,10 @@ function! s:GetManifest() abort
 endfunction
 
 function! s:LoadRemotePlugins() abort
+  if exists('$NVIM_SYSTEM_RPLUGIN_MANIFEST')
+    let g:system_remote_plugins = fnamemodify($NVIM_SYSTEM_RPLUGIN_MANIFEST, ':p')
+    execute 'source' fnameescape(g:system_remote_plugins)
+  endif
   let g:loaded_remote_plugins = s:GetManifest()
   if filereadable(g:loaded_remote_plugins)
     execute 'source' fnameescape(g:loaded_remote_plugins)
```

With that patch, I can set `NVIM_SYSTEM_RPLUGIN_MANIFEST` and have the behaviour I want. I generate the system manifest with

```
    NVIM_RPLUGIN_MANIFEST=system-rplugin.vim nvim -N -u systemrc.vim -i NONE -n -E -s +UpdateRemotePlugins +quit!
```

Is that a bad idea for some reason? Would there be interest to upstream some version of this?

**Comment by jamessan** [comment]
This is definitely something that should be figured about.  I had started thinking about how to manage rplugins for Debian, since I'm working on a new plugin management tool.  However, I've been focusing on the basic "packages" management for now.

**Comment by timokau** [comment]
Yes, https://github.com/neovim/neovim/issues/5532 would  be great. Apparently that solution would also have issues with `RegisterPlugin` throwing an exception when double-registering a plugin. Is there a reason it does this instead of just silently ignoring the second attempt?

**Comment by justinmk** [comment]
> Is there a reason it does this instead of just silently ignoring the second attempt?

I would read the `git log` history to find out the answer to that. Most likely it was just defensive coding.

**Comment by timokau** [comment]
That was added in tarruda's initial rplugin commit 6b17082d3cf1f2e6c9eddb4f5ec0154f0f7286b0, which doesn't have any more details. I'll apply that patch for now. Hopefully one day #5532 will make it unnecessary.

Should I create a PR for it (or just the exception part?) or just keep it a distro specific patch?

**Comment by timokau** [comment]
> I could break out that part from the host aware part

That would be nice. That way the only custom patch I'd still need would be the `NVIM_SYSTEM_RPLUGIN_MANIFEST` and that should be perfectly harmless.

**Comment by justinmk** [comment]
> the only custom patch I'd still need would be the NVIM_SYSTEM_RPLUGIN_MANIFEST and that should be perfectly harmless.

would prefer to avoid a new env var, if possible. Maybe we could do something similar to https://github.com/neovim/neovim/pull/9077 instead.

**Comment by timokau** [comment]
I agree, using the xdg spec would be even better.

**Comment by justinmk** [comment]
This is out of scope because the remote plugin "manifest" should be eliminated entirely: https://github.com/neovim/neovim/issues/27949
