### ISSUE TITLE
packadd autocmd

### ISSUE THREAD

**Issue by timokau** [neovim/neovim#9415]
I would like to be able to run some code after a plugin was loaded. One example use-case would be `call neomake#configure#automake('nrwi', 500)` which is necessary to configure `neomake`. Currently it is hard to do that when `neomake` is an optional plugin.

I imagine something like this:

```
autocmd PackLoaded neomake call neomake#configure#automake('nrwi', 500)
```

The autocommand should only be triggered on the first load. If there was also a `PrePackLoad` than it would be possible to chain `packadd`s, i.e. make sure dependencies are loaded before a plugin is loaded.

The natural place to call these autocommands seems to be here:

https://github.com/neovim/neovim/blob/1e8d2bdc487cdebf152eb228ed936720cfed3a76/src/nvim/ex_cmds2.c#L2740

**Comment by justinmk** [comment]
Did you try the `SourcePre` event?

Vim plugins are a collection of files which may be cross-referenced by other plugins. They are not isolated, so it might be difficult to meaningfully say "this plugin was loaded". And the namespaces are not "owned" by one plugin: any other plugin can modify another plugin's namespace.

Bram is flirting with the idea of  [half-baked dependency management](https://vimconf.org/2018/slides/Vim_From-hjkl-to-a-platform-for-plugins.pdf) (`PluginDepend()`, `PluginLoad()`).

**Comment by timokau** [comment]
Continued in https://github.com/vim/vim/issues/3739.
