### ISSUE TITLE
Strange cursor behavior on deleting list symbol with formatoptions 'a', 'n' flags

### ISSUE THREAD

**Issue by msuperdock** [neovim/neovim#9424]
Note: I also filed this as a vim issue [here](https://github.com/vim/vim/issues/3748).

- `nvim --version`: 0.3.1
- Vim (version: 8.1.146) behaves differently? no
  - (To reproduce in vim, start with `:set bs=2`.)
- Operating system/version: NixOS 18.09
- Terminal name/version: st-0.8.1
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

Create a list of at least three items, where the third item has some more space between the list symbol and the actual item than the first two items. Then turn on automatic formatting and delete the third list symbol. The cursor ends up in a strange location.

Here are the exact keystrokes; note that there are two spaces between "3." and "ghi".

```
nvim -u NORC
i1. abc<cr>2. def<cr>3.  ghi<esc>:set fo=tan<cr>hhhhi<bs><bs>
```

### Actual behaviour

The final text is as follows (using '|' to denote the cursor location). The text is exactly what I would expect, but the cursor location is strange.

```
1. abc
2. de|f ghi
```

(The cursor jumps back to before the "f".)

### Expected behaviour

We should get the same text, but the cursor should end up just after the 'f'.

### Notes

- The formatoptions 't' flag is not necessary to reproduce this error; `set fo=an` has the same effect.
- If you put an additional space between the "3." and the "ghi", the cursor moves an additional space backwards towards the beginning of the line. If you put enough spaces, the cursor ends up at the very beginning of the line, but no further back than that.
- If you do the same thing without the first line "1. abc", starting with "2. def" instead, this error doesn't occur. The cursor ends up just before the 'g'. (I think just after the 'f' would make more sense, but I wouldn't consider this a bug on its own.)
- If you do the same thing but with "-" in place of "1.", "2.", "3.", and you change the list pattern to "-", then you can get the error with just two lines instead of three:

```
i- abc<cr>-  def<esc>:set formatlistpat=-<cr>:set fo=tan<cr>hhhhi<bs>
```

The result is that the cursor jumps back to before the 'c'. I would expect it to end up just before the 'd'.

### A related issue and workaround

A related issue is that it's hard to even type a list with `:set fo=tan` or `:set fo=an`, since vim automatically reflows new list items into previous ones, even if the list pattern is just one character. To workaround this, I'm currently using (for Markdown lists using "-" as the list pattern):

```
autocmd BufWinEnter *.md inoremap <silent> <buffer> - <c-\><c-o>:set formatoptions-=a<cr>-<C-o>:set formatoptions+=a<cr>
```

(I'm happy to write out a separate issue for this last part if it's wanted.)

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/pull/9729
