### ISSUE TITLE
Enhancement: Support for highlighting blank line

### ISSUE THREAD

**Issue by yariamslk** [neovim/neovim#9428]
Many modern text editor support it now
https://github.com/nathanaelkane/vim-indent-guides/issues/23
https://github.com/Yggdroot/indentLine/issues/25

**Comment by bfredl** [comment]
You can using `nvim_buf_set_virtual_text` in version 0.3.2

**Comment by gggggtj** [comment]
Is it possible to implement built-in visually indent displaying feature?
I think it difficult to plugin developers follow function only for Neovim,  and this feature may be demand for many people.

**Comment by justinmk** [comment]
Besides what @bfredl said, see also https://github.com/neovim/neovim/issues/9337 .

> I think it difficult to plugin developers follow function only for Neovim, and this feature may be demand for many people.

What are you asking for?
