### ISSUE TITLE
[RFC] remove trailing whitespace from files that have it

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#944]
Some files, like `eval.c`, are a pain to edit for some people (like me) that have their editors set to trimming trailing whitespace by default. I either have to edit with `vim -u NONE`, or use a special `git addnw` to add non-whitespace changes (but this is tricky and buggy and doesn't work for merge conflicts).

Luckily, most of the files in neovim are whitespace clean, but some aren't. With this issue I'd like to ask if there would be popular support for performing this change, perhaps with some [shell-scripting](http://stackoverflow.com/questions/10711051/trailing-whitespace-elimination-script-for-multiple-files)?

**Comment by justinmk** [comment]
Lint will take care of this, or if not then it's out of scope.
