### ISSUE TITLE
Elflord selection colors are broken in Urxvt

### ISSUE THREAD

**Issue by AGitBoy** [neovim/neovim#9441]
- `nvim --version`:
NVIM v0.3.1
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.3.1/build/config -I/builddir/build/BUILD/neovim-0.3.1/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.1/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.1/build/include
Compiled by mockbuild

Features: +acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

- Vim (version: 8.1) behaves differently? Yes
- Operating system/version: Fedora 29 Workstation
- Terminal name/version: rxvt-unicode 9.22
- `$TERM`: rxvt-unicode (behavior persists when $TERM is set to the 256 color version as well)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:colorscheme elflord
:e <File with syntax highlighting support>
v (or V)
select a few lines
```

### Actual behaviour
In Neovim, the colorscheme elflord will not highlight the selected area in visual mode when in urxvt (it will in gnome-terminal), resulting in something like this:
![urxvt-neovim](https://user-images.githubusercontent.com/30708886/50578891-ca207800-0e0d-11e9-88a7-e8c6d980a551.png)

### Expected behaviour
In vim, using no configuration, and following the steps above (although `:syntax enable` must be called before as well), It will look like this:
![urxvt-vim](https://user-images.githubusercontent.com/30708886/50578773-4914b100-0e0c-11e9-94b1-8d11156f3640.png)

This problem does not occur in gnome-terminal with neovim (with the exact same terminal colorscheme) either:
![gnome-term-neovim](https://user-images.githubusercontent.com/30708886/50578842-26cf6300-0e0d-11e9-8031-6efdac64edbe.png)

**Comment by justinmk** [comment]
Try 0.3.2.
