### ISSUE TITLE
Tmux terminal-override suggestion in FAQ brings 'q' at end of lines in bare TTY

### ISSUE THREAD

**Issue by doronbehar** [neovim/neovim#9448]
- `nvim --version`: 
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? Irrelevant
- Operating system/version: Arch Linux kernel 4.20
- Terminal name/version: More on that below

### Steps to reproduce using `nvim -u NORC`

1. Add this to your `~/.tmux.conf` according to [this FAQ](https://github.com/neovim/neovim/wiki/FAQ#cursor-shape-doesnt-change-in-tmux):
```
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```
2. Launch a tmux session in a bare TTY and run `nvim -u NORC`.

### Actual behaviour

The famous `'q'` letter appears at end of lines and when ESC is pressed as already known.

### Expected behaviour

No `q` letters are printed.

### Question

This is not necessarily a bug report, I know many reports like this were already submitted in this bug tracker in the past, I'm just wondering if it's even fixable. My suspicion is that this behaviour is not avoidable if one wants the cursor to change shape in Tmux. If it's not fixable perhaps only a small addition to the FAQ should be added in regard to this matter. Or perhaps this line which is safer IMO should be suggested instead:
```
if-shell '[[ $TERM != "linux" ]]' "set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'"
```

**Comment by justinmk** [comment]
that FAQ item is a "last resort. It should not normally be needed. I don't use it, and cursor shaping works just fine for me in tmux.

> My suspicion is that this behaviour is not avoidable if one wants the cursor to change shape in Tmux

cursor shaping works fine with Nvim + tmux.

> Or perhaps this line which is safer IMO should be suggested instead:

feel free to change the FAQ item. I don't even know why it's there.

**Comment by doronbehar** [comment]
Does the cursor shaping works fine for you with Nvim + tmux on a `linux` terminal as well? I mean on a bear TTY.

**Comment by justinmk** [comment]
> Does the cursor shaping works fine for you with Nvim + tmux on a linux terminal as well

Whether it does or does not is up to _tmux_. When an application is running in tmux it must treat tmux as the terminal, and _tmux_ makes all decisions about behavior with respect to the "outer" terminal.

**Comment by doronbehar** [comment]
Thanks for your comment, I was just wondering if you've somehow managed to enable cursor shaping in tmux inside a TTY terminal and I'm missing something. I'm just wondering perhaps the documentation could be improved even further besides the FAQ..
