### ISSUE TITLE
jobstart() incorrectly moves cursor

### ISSUE THREAD

**Issue by KeyboardFire** [neovim/neovim#9449]
- `nvim --version`: v0.3.2
- Vim behaves differently? N/A
- Operating system/version: Arch Linux
- Terminal name/version: tested in `urxvt` v9.22, `xterm` v340
- `$TERM`: `screen-256color`

(also reproduced on Windows with `nvim` v0.4.0)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
5otest<esc>
:exe jobstart('sleep 1')
:exe jobstart('sleep 1')
:exe jobstart('sleep 1')
```

### Actual behaviour

Cursor moves to line *2+n* after the *n*th invocation of `jobstart`. For example, running it the first time moves the cursor to line 3. Running it again moves the cursor to line 4, and so on.

This occurs regardless of what the command is (here `sleep 1` as an example).

### Expected behaviour

Cursor does not move.

**Comment by jamessan** [comment]
`jobstart()` returns the id of the job that was started.  `:exe` evaluates the rest of the command line as an expression and then runs the command that the expression evaluates to.

So, `jobstart('sleep 1')` returns 2, which results in `:exe 2`, which is the same as the command `:2`.  That moves to line 2.

If you just want to call `jobstart()` and don't care about the returned id, then use `:call jobstart()`.
