### ISSUE TITLE
Default colorscheme using bright colours

### ISSUE THREAD

**Issue by E5ten** [neovim/neovim#9455]
- `nvim --version`:
```
NVIM v0.4.0-70-g292b1790c
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/lib/ccache/bin/clang -march=native -O2 -pipe -fstack-protector-strong -fno-plt -fcolor-diagnostics -Qunused-arguments -stdlib=libc++ -rtlib=compiler-rt -Wshadow -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/e5ten/sdfm/AUR/neovim-git/src/neovim-git/build/config -I/home/e5ten/sdfm/AUR/neovim-git/src/neovim-git/src -I/usr/include -I/home/e5ten/sdfm/AUR/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/e5ten/sdfm/AUR/neovim-git/src/neovim-git/build/include
Compiled by e5ten@clevo

Features: +acl +iconv -jemalloc +tui
```
(also occurs with the arch build of 0.3.2)
- Operating system/version: Arch Linux
- Terminal name/version: alacritty
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
`nvim -u NORC`
### Actual behaviour
Neovim default colorscheme uses brighter colours like in the right of the picture.
### Expected behaviour
Neovim default colorscheme uses darker colours like in the left, like it always has for me before.
![screenshot 2019-01-04 14-29-55](https://user-images.githubusercontent.com/24554283/50707138-e8fd5500-102d-11e9-8608-90a91f5448b3.png)

**Comment by bfredl** [comment]
What is the bug? The right is clearly a better default. You can recover the old behavior with `set bg=light`.

**Comment by E5ten** [comment]
Ok, thanks.

**Comment by littlenaut** [comment]
> What is the bug? The right is clearly a better default.

Looking good is just a side effect. This is also happening for me in macOS 10.13.6 + iTerm 3.2.6 + neovim 0.3.4 (installed through Homebrew).
```
$ nvim --version
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-54117-y16422/neovim-0.3.4/build/config -I/tmp/neovim-20190113-54117-y16422/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190113-54117-y16422/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-54117-y16422/neovim-0.3.4/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

Run :checkhealth for more info
```

Left terminal is using your suggestion of `set bg=light` right after `colorscheme default`. Right terminal is using just `colorscheme default`. Both using iTerm's default Solarized Light theme.

<img width="591" alt="neovim-default-colorscheme" src="https://user-images.githubusercontent.com/41801303/51214656-6a9a9000-1916-11e9-88f3-87f1362ac646.png">

I can also reproduced the same behaviour even if I `nvim -u NONE` and then manually turn on the syntax highlighting `:syntax on`.

@E5ten Can you please reopen this issue?
@bfredl Thanks for the suggestion! It is a good fix for the meantime.

**Comment by bfredl** [comment]
@littlenaut the only "scalable" solution would be detection, I think there is an open issue for that already.
