### ISSUE TITLE
drawing area not fit the entire screen.

### ISSUE THREAD

**Issue by xbrent** [neovim/neovim#9457]
please check the screen shot.
the green background.

<img width="1280" alt="screen shot 2019-01-06 at 3 47 53 am" src="https://user-images.githubusercontent.com/3114264/50729190-99737200-1170-11e9-944f-14c30db86d2b.png">

```
nvim -u NORC

```

**Comment by bfredl** [comment]
sure this is not a terminal issue? does it persist if you resize the terminal (in normal mode)?

**Comment by justinmk** [comment]
You're using a Terminal.app "profile" with a green background. (Please mention those kinds of details, next time.)

In Terminal.app if I choose Shell > New Window > Red Sands, get a new window with a red background, and I see the same behavior with Vim 8.1.50 and Emacs.
