### ISSUE TITLE
insert mode enter will call ctrl-m is this correct?

### ISSUE THREAD

**Issue by chenjie199234** [neovim/neovim#9469]
- `nvim --version`:0.3.3
- Vim (version: ) behaves differently?
- Operating system/version:archlinux newest
- Terminal name/version:urxvt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```
init.vim
imap c-m ESC:echo(1)CR
### Actual behaviour
in inseart mode input enter key will call ctrl-m and echo 1
### Expected behaviour
in inseart mode input enter key create a new line

**Comment by mhinz** [comment]
This is no Nvim issue.

Your terminal emulator reports the same sequence for `<c-m>` and `<cr>` ("enter"), so Nvim can't distinguish between them. They _do_ the same. Both, `<cr>` and `<c-m>`, enter a new line in Vim's insert mode as well.

You can test this in insert mode with `<c-v><c-m>` and `<c-v><cr>`. You'll get `^M` in both cases.

For further user issues, please visit us at: https://gitter.im/neovim/neovim
