### ISSUE TITLE
Blocking nvim_get_mode call from Oni since nvim 0.3.2

### ISSUE THREAD

**Issue by delkano** [neovim/neovim#9473]
The update from neovim 0.3.1 to 0.3.2 broke Oni. 0.3.3 still has the issue.

The issue has been tracked ( https://github.com/onivim/oni/issues/2704#issuecomment-452170811 ) to a call to `nvim_get_mode`  which never returns.

- `nvim --version`: 0.3.2 (and 0.3.3)
- Vim (version: ) behaves differently? 0.3.1
- Operating system/version: ArchLinux
- Terminal name/version: N/A (Oni is a GUI)
- `$TERM`: N/A

**Comment by justinmk** [comment]
https://github.com/onivim/oni/pull/2613 is still pending. As explained there, Oni should call `nvim_ui_attach` after starting `nvim --embed`.

`nvim_get_mode` is (currently) "best effort", but inherently racy: if `nvim_get_mode` request is sent at just the "right" time then it could block. The best solution is to remove the need for `nvim_get_mode`  , which is what https://github.com/onivim/oni/pull/2613 should do.
