### ISSUE TITLE
Terminal-Window which gets focus via mouse-click doesn't respect 'au BufEnter term://* star'

### ISSUE THREAD

**Issue by astier** [neovim/neovim#9483]
- `nvim --version`: 0.3.3
- Vim (version: ) behaves differently? Don't know
- Operating system/version: Arch
- Terminal name/version: GNOME Terminal 3.30.2
- `$TERM`: xterm-256color

### Actual Behavior

I don't know if this behavior is intentional but when I define in my vimrc `au BufEnter term://* star` to force windows with an open terminal to automatically enter the insert-mode whenever it gets focus it only respects it when I navigate to the respective window via C-w h/j/k/l. However, when I left-click in such a window one can see that the terminal indeed enters the insert-mode for a moment but immediately leaves it again.

### Expected Behavior

When a window with an open terminal gets focus via left-click it should not automatically exit the insert-mode but stay in the insert-mode when the user defines it in its vimrc for example by putting `au BufEnter term://* star` in its vimrc.

**Comment by justinmk** [comment]
For reference, this doesn't work:

     :nnoremap <expr> <LeftMouse> &buftype ==# 'term' ? '<cmd>startinsert<cr>' : ''

seems like that mapping is evaluated while the cursor is still in the non-terminal buffer. Then BufEnter is triggerd in the terminal buffer. Then insert-mode is exited.

**Comment by lanza** [comment]
Any idea of where this problem might come from? Been thinking about trying a starter bug and I just ran into this one.

**Comment by dm1try** [comment]
I was able to reproduce the issue and have noticed that the insertion mode is enabled before you release a left mouse button(I used touchpad).

I'm not certainly sure about the core problem, but if you map `LeftRelease` to `Nop` in terminal buffer it somehow helps :
```
tmap <LeftRelease> <Nop>
```

I'm going to explore the codebase a little bit later :)

**Comment by dm1try** [comment]
It is not clear that is the best way to fix the issue.

right after entering into insert mode of a terminal buffer([1](https://github.com/neovim/neovim/blob/f6faeea41c70015f6d9b63fecaf80d106cd2636d/src/nvim/edit.c#L1325-L1335), [2](https://github.com/neovim/neovim/blob/f6faeea41c70015f6d9b63fecaf80d106cd2636d/src/nvim/terminal.c#L368)) we start receiving mouse events and handle them appropriately(?):
https://github.com/neovim/neovim/blob/f6faeea41c70015f6d9b63fecaf80d106cd2636d/src/nvim/terminal.c#L439-L449
https://github.com/neovim/neovim/blob/f6faeea41c70015f6d9b63fecaf80d106cd2636d/src/nvim/terminal.c#L972-L974

should we somehow ignore the first mouse release event if it does not have any predecessor or should we ignore it at all in the terminal buffer? I'm thinking about use cases 🤔

**Comment by justinmk** [comment]
@dm1try 	Good observation. But I would guess the answer is "we should handle it similar to how we handle it for insert-mode in a normal buffer". 

Mouse-click in a normal buffer places the cursor without leaving insert-mode. I don't see why clicking in a terminal-buffer in terminal-mode (insert-mode) should exit terminal-mode.

**Comment by rofrol** [comment]
This helped me:

```viml
if has('nvim')
    augroup terminal_setup | au!
        autocmd TermOpen * nnoremap <buffer><LeftRelease> <LeftRelease>i
        " more stuff
    augroup end
endif
```

https://vi.stackexchange.com/questions/22307/neovim-go-into-insert-mode-when-clicking-in-a-terminal-in-a-pane/22327#22327
