### ISSUE TITLE
Automatic line number does not work inside tmux?

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#9486]
- `nvim --version`:  v0.3.2-745-g5fbc2eeac
- Vim (version:  7.4) behaves differently: No
- Operating system/version: CentOS Linux release 7.4.1708 (Core)
- Terminal name/version: zsh 5.6.2
- `$TERM`:  `screen-256color` inside tmux

### Steps to reproduce using `nvim -u NORC`
+ Open tmux and create two split side by side
+ Open a file with nvim in one pane `nvim -u init.vim`, with the following setting in `init.vim`:
```
set number                                                           
augroup numbertoggle                                                   
autocmd!                                                             
autocmd BufEnter,FocusGained,InsertLeave * set relativenumber        
autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
```
+ click the other tmux pane

### Actual behaviour
Relative number does not change to absolute line number.

### Expected behaviour
Relative number change to absolute line number.

**Comment by justinmk** [comment]
Works for me. Need this in `~/.tmux.conf`:

    set-option -g focus-events on

**Comment by jdhao** [comment]
Thanks a lot, it works now. 😃 

Now, when I click the the pane to switch panes, the relative number in nvim changes to absolute number.
