### ISSUE TITLE
Build failed with luajit on macOS Mojave

### ISSUE THREAD

**Issue by cosmtrek** [neovim/neovim#9488]
I just run `make distclean; make CMAKE_OSX_DEPLOYMENT_TARGET=10.14` on macOS Mojave, and cannot build luajit.

The errors:

```
...
/Library/Developer/CommandLineTools/usr/bin/cc -g  -dynamiclib -single_module -undefined dynamic_lookup -fPIC -install_name /Users/cosmtrek/Code/neovim/.deps/usr/lib/libluajit-5.1.2.dyl
ib -compatibility_version 2.0 -current_version 2.0.5 -image_base 7fff04c4a000   -o libluajit.so lj_vm.o lj_gc.o lj_err.o lj_char.o lj_bc.o lj_obj.o lj_str.o lj_tab.o lj_func.o lj_udata.
o lj_meta.o lj_debug.o lj_state.o lj_dispatch.o lj_vmevent.o lj_vmmath.o lj_strscan.o lj_api.o lj_lex.o lj_parse.o lj_bcread.o lj_bcwrite.o lj_load.o lj_ir.o lj_opt_mem.o lj_opt_fold.o
lj_opt_narrow.o lj_opt_dce.o lj_opt_loop.o lj_opt_split.o lj_opt_sink.o lj_mcode.o lj_snap.o lj_record.o lj_crecord.o lj_ffrecord.o lj_asm.o lj_trace.o lj_gdbjit.o lj_ctype.o lj_cdata.o
 lj_cconv.o lj_ccall.o lj_ccallback.o lj_carith.o lj_clib.o lj_cparse.o lj_lib.o lj_alloc.o lib_aux.o lib_base.o lib_math.o lib_bit.o lib_string.o lib_table.o lib_io.o lib_os.o lib_pack
age.o lib_debug.o lib_jit.o lib_ffi.o lib_init.o -lm
LINK      luajit
/Library/Developer/CommandLineTools/usr/bin/cc -g   -pagezero_size 10000 -image_base 100000000   -o luajit luajit.o libluajit.a -lm
ld: warning: ignoring file libluajit.a, file was built for archive which is not the architecture being linked (x86_64): libluajit.a
Undefined symbols for architecture x86_64:
  "_luaJIT_version_2_0_5", referenced from:
      _pmain in luajit.o
  "_luaL_callmeta", referenced from:
      _traceback in luajit.o
  "_luaL_checkstack", referenced from:
      _pmain in luajit.o
  "_luaL_loadbuffer", referenced from:
      _pmain in luajit.o
      _dotty in luajit.o
  "_luaL_loadfile", referenced from:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:686: luajit] Error 1
make[2]: Leaving directory '/Users/cosmtrek/Code/neovim/.deps/build/src/luajit/src'
make[1]: *** [Makefile:110: src/luajit] Error 2
make[1]: Leaving directory '/Users/cosmtrek/Code/neovim/.deps/build/src/luajit'
ninja: build stopped: subcommand failed.
make: *** [Makefile:81: deps] Error 1
```

I cannot figure it out why it failed. Could you help me? Thanks!

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/9050

**Comment by cosmtrek** [comment]
Just found a solution: https://github.com/LuaJIT/LuaJIT/issues/466

**Comment by justinmk** [comment]
Thanks for the follwup. Pasting your solution here for reference:

> ```
> ❯ export PATH=/usr/bin:/bin:/usr/sbin:/sbin
> ❯ make
> ==== Building LuaJIT 2.0.5 ====
> /Library/Developer/CommandLineTools/usr/bin/make -C src
> HOSTCC    host/minilua.o
> HOSTLINK  host/minilua
> DYNASM    host/buildvm_arch.h
> HOSTCC    host/buildvm.o
> ...
> ```

That looks to me like maybe a [build prerequisite](https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites) was not installed. Typically PATH would have been fixed by homebrew and/or macOS "commandline tools".

**Comment by cosmtrek** [comment]
@justinmk The problem is my `$PATH` is `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`, something in `/usr/local/bin` may break the build. Because I can install neovim via homebrew. Therefore I check the `$PATH` when homebrew compiles it and find the problem.

**Comment by mpuncel** [comment]
for me it was `/usr/local/bin/ar` causing problems. `brew uinstall binutils` fixed for me

**Comment by xander-ye** [comment]
My system version is Catalina 10.15.6, so set env as fellow: 
exprot MACOSX_DEPLOYMENT_TARGET=10.15.6

**Comment by vinitkumar** [comment]
Thanks for the advice @mpuncel. It fixed the issue for me as well.
