### ISSUE TITLE
background=light is not respected when set in .nvimrc

### ISSUE THREAD

**Issue by ddddavidmartin** [neovim/neovim#9499]
Good day,

I have `set background=light` in my `~/.nvimrc` but it does not have any effect when I start nvim. This used to work fine last I remember in early December 2018. At this point I'm not sure whether it is an issue with my setup, but I have not changed anything other than applying updates.

- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"
```
- Operating system/version: Mac OSX 10.14.2
- Terminal name/version: iTerm2 Build 3.2.6
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

I'm not able to reproduce this with `nvim -u NORC` as it loads without a config file.

### Actual behaviour

nvim starts as if `set bg=dark` even though `set bg=light` is set in `.nvimrc`.

### Expected behaviour

nvim should start with `bg=light`.

I'd be happy to provide any other info as needed. Thanks!

**Comment by ddddavidmartin** [comment]
Meh, I think this is just due to me having the config file in the wrong spot. Running `nvim -u ~/.nvimrc` works fine.

**Comment by mhinz** [comment]
It's not called `.nvimrc` for years; it's `init.vim` nowadays. Please see `:h vimrc`.

**Comment by ddddavidmartin** [comment]
> It's not called .nvimrc for years; it's init.vim nowadays. Please see :h vimrc.

Thanks!

In the end the issue was that I had symlinked `~/.config/init./vim` to `~/.vimrc` and for whatever reason did not have the `set bg=light` in there anymore. The `.nvimrc` must have been from when I first set everything up and it was never actually used and it mislead me.
