### ISSUE TITLE
How to disable touchpad in a nvim instance?

### ISSUE THREAD

**Issue by yashamon** [neovim/neovim#9511]
OS: Ubuntu Linux
Terminal: Termite, xterm ... anything i tried
Vim behavior: same
init.vim: none

This is absolutely driving me insane, my thinkpad touchpad is fairly large and sensitive and I am constantly touching it by accident making cursor jump all over the place. I am already on libinput which has some rudimentary disable while typing features but it is far from enough. Can I just disable touchpad inside neovim? set mouse= does nothing useful. I want no scrolling no pointing. 

edit: it appears that set mouse= 
does disable clicking but not scrolling, but this is no help for me.

**Comment by bew** [comment]
What does `set mouse=` do if it doesn't desactivate mouse support??
Also what is your terminal/os/..?

**Comment by yashamon** [comment]
by the way adding this 
noremap <ScrollWheelUp>      <nop>
does absolutely nothing

**Comment by justinmk** [comment]
When scroll is sent, it may be sent as regular "up" or "down" arrow keys. Nothing a terminal application can do to differentiate this. Sounds like that's what's happening.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by yashamon** [comment]
I don't understand how this is an answer.
It is clearly a bug as per description of set mouse command: 
"set mouse= " does not do what it is supposed to do. There exists no known configuration based solution for this: see for instance: https://vi.stackexchange.com/questions/13566/fully-disable-mouse-in-console-vim

At the very least it is an issue that cannot be solved by any means except a coded solution. (as far as I or anyone else knows)

**Comment by yashamon** [comment]
Justin, this is a huge usability issue. At the very least I suggest the help page for "set mouse" is updated, saying that it does not work with scroll. Workarounds could be suggested. A simple one seems to be to just remap <up> <down> to <nop>. Maybe to an expert this stuff is obvious but not to an average user. (Why does terminal conflate up and down with mouse scroll?)

**Comment by bfredl** [comment]
@yashamon If your terminal emulator maps touchpad to to arrow keys, nvim can do nothing about it. If you consider it a bug, it is a bug of your terminal emulator. `set mouse=`correctly disables all mouse events including the scrollwheel, and touchpad in any terminal emulator that (more reasonably) maps it to scrollwheel events, which for instance `xterm` and `pangoterm` does.

**Comment by yashamon** [comment]
Alas, I thought xterm had same behavior for me, maybe I miss-tested.

**Comment by yashamon** [comment]
yeah I messed up it does work with xterm in terminal, the problem was me
using nvim-qt. For some reason this still does not respect set mouse=
rather it does but not for scroll. But I suppose I need to talk nvim-qt
developer.

**Comment by jallbrit** [comment]
For anyone else on the Internet that finds this issue, here's the solution:

> When scroll is sent, it may be sent as regular "up" or "down" arrow keys. Nothing a terminal application can do to differentiate this

This is exactly correct. Unfortunately the only solution I can figure out is to just disable arrow key movement altogether, in every mode (which isn't a problem if you don't use the arrow keys, which you really shouldn't anyways):

```vim
" disable arrow keys
" also disables two-finger scrolling on laptop trackpads
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop>
```

**Comment by kaiuri** [comment]
this solved it for me.
```vim
map <Up> <Nop>
map <Down> <Nop>
```

**Comment by kaiuri** [comment]
this solved it for me :octocat: 
```lua
map("", "<Up>", "<Nop>", { noremap = false })
map("", "<Down>", "<Nop>", { noremap = false })
```
