### ISSUE TITLE
Feature Request: Trigger balloon via keyboard at cursor position

### ISSUE THREAD

**Issue by marcotrosi** [neovim/neovim#9512]
Hi,

I want to trigger the balloon text via keyboard at cursor position. I read the documentation and it looks like that at the moment the balloon textbox can be triggered only with the mouse, which is in my humble opinion not very Vim-like. Mouse is okay of course, but keyboard should have higher priority, or am I wrong?

It could be a function or a command that I can map (nmap/imap/vmap/xmap/smap) or use in Vimscript. Just the standard Vim solutions.

What do you think?

Thanks for your feedback

Have a great day

--marco

**Comment by marcotrosi** [comment]
My bad, I forgot that the balloon feature has been removed

**Comment by marcotrosi** [comment]
> The balloon feature was only temporarily removed. Work is being done on floating windows, and we will either use that or something similar to Vim's on-demand popup.

Hi Justin, thanks for your feedback.
That's good news. Is it worth to re-open the issue?

--marco

**Comment by justinmk** [comment]
No, there is already an issue for this.

**Comment by marcotrosi** [comment]
> No, there is already an issue for this.

Hi again. Would you be so kind to show me that other "duplicate" issue? Thanks.

**Comment by dm1try** [comment]
search for "floating windows" leads to #6619
