### ISSUE TITLE
[netrw] Cannot map m key in netrw buffer

### ISSUE THREAD

**Issue by damage220** [neovim/neovim#9513]
- `nvim --version`: NVIM v0.3.3
- Vim (version: 8.1) behaves differently? No.
- Operating system/version: 4.20.0-arch1-1-ARCH
- Terminal name/version: xfce4-terminal 0.8.7.4
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC -c "nmap h - | nmap l <CR> | nmap m R | e ."
press h, l or <CR>
```

### Actual behaviour
When pressing one of these keys, renaming dialog is appeared. It happens only with directories, files are handled as expected. I know there is no difference between `<C-m>` and `<CR>`, but `m` and `^M` is definitely different sequences. Unfortunately, I have not found any commands in netrw help page, only these buffer specific mappings.

### Expected behaviour
Open directory/file.

### Possible solution
Well, there is `netrw#Call` function for internal calls and `netrw#Expose` to retrieve local variables. It should be possible to get `mapsafecurdir` and call `NetrwLocalRm()` directly, but what about the issue? Is this a bug or I am missing something?

**Comment by justinmk** [comment]
For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by damage220** [comment]
Is this a normal behavior when you bind a key, `m` in this case, and the other keys start to conflict with each other? They are not binded in any way except the netrw internals.
