### ISSUE TITLE
Windows TUI: mouse click to switch window, mouse drag to resize

### ISSUE THREAD

**Issue by jdhao** [neovim/neovim#9514]
- `nvim --version`: 0.3.2
- Vim (version:  8.1.22): behaves differently
- Operating system/version: Windows 10 version 1803
- Terminal name/version: [Cmder](https://github.com/cmderdev/cmder/releases), version 1.3.10
- `$TERM`:  In cmder  `settings -> Startup -> Environment `, I use `set TERM=xterm-256color`, `echo &term` inside Neovim shows `builtin_xterm` (for Vim it shows `xterm-256color`).

### Steps to reproduce using `nvim -u NORC`

1.  Use the following minimum setting in `init.vim`:

```
set mouse=a
```

2. open nvim with the above setting:

```
nvim -u init.vim
```

3. Open two files side by side in nvim and use mouse click to try to change panes. try to use mouse drag to resize the window

### Actual behaviour
Can not use mouse click to change windows and can not use mouse drag to resize window in nvim.

But for vim, using mouse click to change windows works (using mouse drag to resize window does not work).

For nvim-qt (using `nvim-qt -- -u init.vim` to open it),  I can switch windows and resize window with mouse correctly.

### Expected behaviour

I can use mouse to change windows and resize window when I use `set mouse=a`.

**Comment by erw7** [comment]
Please try the artifacts of #9094. As it works with legacy console and ConEmu, it should work with new console in Windows 10.

**Comment by hummeleBop** [comment]
Hi,

I use neovim (from the Windows binaries package) in the new «Windows Terminal» on Windows 10. In my environement, the `$TERM` variable is equal to `xterm-256color`. Everything works except for the mouse, the entry `set mouse=a` doesn't change anything.
