### ISSUE TITLE
update v:oldfiles at runtime

### ISSUE THREAD

**Issue by randomizedthinking** [neovim/neovim#9523]
- `nvim --version`: v0.3.3
- Vim (version: ) behaves differently? same
- Operating system/version: Debian
- Terminal name/version: rxvt-unicode
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:oldfiles
:e another-new-file
:oldfiles                      # the oldfile list is unchanged
```

### Actual behaviour
The `v:oldfiles` is read from shada at startup, and is not updated during the session, so a user cannot access recently closed files in the same nvim-instance. If one quits then re-enters, these files will appear in the `v:oldfiles` variable.

### Expected behaviour
The `v:oldfiles` should be updated on the fly once new files are opened.

**Comment by justinmk** [comment]
Technically this would be a breaking change, but probably still welcome.

**Comment by mhinz** [comment]
I just want to mention that `v:oldfiles` is writable as well. vim-startify uses this by default:

```vim
function! s:update_oldfiles(file)
  if g:startify_locked || !exists('v:oldfiles')
    return
  endif
  let idx = index(v:oldfiles, a:file)
  if idx != -1
    call remove(v:oldfiles, idx)
  endif
  call insert(v:oldfiles, a:file, 0)
endfunction

autocmd startify BufNewFile,BufRead,BufFilePre *
          \ call s:update_oldfiles(expand('<afile>:p'))
```

**Comment by justinmk** [comment]
@mhinz 	that might be a good thing for us to put in a standard `nvim.vim` plugin. Except do it on `:bdelete` instead of `BufNewFile,BufRead,BufFilePre`.

**Comment by randomizedthinking** [comment]
@mhinz since many plugins will open utility buffers for certain tasks, I wonder whether the code you have will filter them out?

**Comment by mhinz** [comment]
@randomizedthinking 

Yes, the plugin does the filtering when it's run, not when that autocmd gets triggered. But buffers that are not backed by files won't trigger these events in the first place. I just wanted to show that's it's another approach.

It's probably not terribly hard to make this change in Nvim, but the real question is if we really want to break with Vim's behaviour here.

**Comment by xiongmao86** [comment]
Since oldfiles is taken care by shada, update v:oldfiles with an autocmd will be enough, am I right?

**Comment by randomizedthinking** [comment]
@xiongmao86 Yes, I am using minhz's approach with some minor changes, and it works out nicely.

**Comment by xiongmao86** [comment]
@randomizedthinking , thank you very much for your answer. And there’s one question at last, where should I put the function that update v:oldfiles, should I create a ‘nvim.vim’ file, and place it in the ‘runtime/autoload’ directory?

**Comment by randomizedthinking** [comment]
@xiongmao86 Having it in your init.vim file would be fine.

**Comment by randomizedthinking** [comment]
Closing it now since it is rather a minor item, and there is a solution without touching the system. Thanks @justinmk and @mhinz for the help.
