### ISSUE TITLE
redraw! do not clear cmdline

### ISSUE THREAD

**Issue by wsdjeg** [neovim/neovim#9524]
- `nvim --version`: master
- Vim (version: ) behaves differently? yes
- Operating system/version: Win 7
- Terminal name/version: 
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:nnoremap <silent> <C-l> :redraw!<cr>
:echom 1111
" then press <c-l>
```

### Actual behaviour

I am using neovim-qt, the cmdline should be cleared, but now it can not be cleared.

### Expected behaviour

`redraw!` should be able to clear cmdline.

**Comment by bfredl** [comment]
`redraw!` clearing the cmdline was a consequence of clearing the entire screen, the latter is still available as unmapped `<c-l>` (whose behavior hasn't changed) and `:mode`.

In general, clearing the entire screen just to clear the cmdline seems wasteful. `:echo` without args seems to work to only clear the cmdline.

**Comment by justinmk** [comment]
Mapping `:nnoremap <silent> <C-l> :redraw!<cr>` makes no sense, the default CTRL-L behavior is more powerful.

> :echo without args seems to work to only clear the cmdline.

Yes, specifically:

    :echo '' | redraw

**Comment by bfredl** [comment]
@justinmk already `:echo` without `''` works. It supports an arbitrary number of args, so zero args consequentially also work.

**Comment by wsdjeg** [comment]
@justinmk my issue is on neovim-qt, I use `redraw!` in my plugin, but it do not clear cmdline. the reproduce is just a simple example. BTW, my os is windows.

**Comment by justinmk** [comment]
@wsdjeg If you want to clear the cmdline, use the approach given above. Plugins should not use `:redraw!` except in extreme cases, even in Vim.
