### ISSUE TITLE
F1 doesn't work correctly in fish in :terminal

### ISSUE THREAD

**Issue by YaLTeR** [neovim/neovim#9529]
- `nvim --version`: 0.3.4
- Vim (version: 8.1) behaves differently? No
- Operating system/version: Arch Linux x64
- Terminal name/version: Alactritty, Konsole, nvim-gtk
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:term
fish # Launch fish if it's not your default shell
cat<F1>
```

### Actual behaviour
Parts of previous fish command inserted.

### Expected behaviour
`cat` man page is opened.

### Additional info
nvim seems to insert wrong sequences for F1-F4. To compare, launch `cat` and press F1-F4. What I get in a regular terminal:
```
^[OP^[OQ^[OR^[OS
```
What I get in the nvim terminal:
```
^[[P^[[Q^[[R^[[S
```

**Comment by YaLTeR** [comment]
I'm not sure if I'm doing anything wrong, but on `NVIM v0.4.0-496-gd13803f64` I'm getting the exact same issue, even though it is supposed to be fixed?

**Comment by YaLTeR** [comment]
cc @erw7 should I reopen this?

**Comment by erw7** [comment]
How did you install that nvim? Does the issue occur on the [releases page](https://github.com/neovim/neovim/releases) [appimange](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage)?

**Comment by YaLTeR** [comment]
Huh, odd. The issue does not occur in the appimage. My local nvim is installed from the [neovim-git](https://aur.archlinux.org/packages/neovim-git/) AUR package.

**Comment by YaLTeR** [comment]
Ah, I see, it must be that `libvterm` in Arch isn't updated with that fix yet. I suppose I'll need to build the neovim fork of that or use the appimage.
