### ISSUE TITLE
deps: unwind libvterm patches

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9540]
After we update to latest libvterm (which has breaking changes), we can remove these patches from our fork:

- https://github.com/neovim/libvterm/commit/b45b648cab73f9667bde7c0c6045b285e22b3ecd

Update: only 1 remaining: https://github.com/neovim/neovim/tree/master/cmake.deps/patches

**Comment by dundargoc** [comment]
Is this still relevant? We don't use libvterm from our fork anymore.

**Comment by dundargoc** [comment]
Doesn't look relevant anymore. Closing.

**Comment by justinmk** [comment]
(I've updated the URL in the description, which was outdated)

@dundargoc  we still have a path for libvterm: https://github.com/neovim/neovim/tree/master/cmake.deps/patches

We can close this when we eliminate that patch.

**Comment by clason** [comment]
Closed by #17329
