### ISSUE TITLE
Implement tests for improved lua messages

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#9541]
See https://github.com/neovim/neovim/pull/7969#issuecomment-456960271.

@justinmk How about a "good first issue" tag or so?

**Comment by sameeriitkgp** [comment]
Hey there.
I'm new to the neovim project. I'm still going through the contributor's guide.
Would love to start contributing.
I can start with this bug/issue, if no one else is looking into it.

**Comment by justinmk** [comment]
@sameeriitkgp Thanks for your interest. Note the above PR which links to this issue.

**Comment by tedbauer** [comment]
If someone wants to grab this issue-- just closed my PR; will not have time to work on this in the near future :(

**Comment by justinmk** [comment]
Lua messages were improved since then, look for `pcall_err` to find test coverage.
