### ISSUE TITLE
Tmux underline support broke since 0.3.2

### ISSUE THREAD

**Issue by ArchiFleKs** [neovim/neovim#9545]
- `nvim --version`: 0.3.1 - 0.3.2
- Vim (version: ) behaves differently?
- Operating system/version: ArchLinux
- Terminal name/version: Tilix/1.8.9
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:set spell
```

### Actual behaviour

In 0.3.1 underline is displayed in tmux but in 0.3.2 underline are not (maybe because it seems to have switched to undercurl in 0.3.2 but were not in 0.3.1 and tmux does not support undercurl (https://github.com/tmux/tmux/issues/1492).

In 0.3.1 outside tmux, underline world are not curly, but in 0.3.2 they are and it is working outside tmux

### Expected behaviour
Underlined word when inside tmux

### Comments

I think it is more a tmux issue, but is there a configuration option to switch back to old underlining method and not use undercurl when inside tmux ?

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/9270#issuecomment-442913869

**Comment by ArchiFleKs** [comment]
@justinmk thanks, I can confirm itś working in latest tmux, but not in true color with `set termguicolors`
