### ISSUE TITLE
inccommand with slow 'foldexpr' (vimtex) 

### ISSUE THREAD

**Issue by KillTheMule** [neovim/neovim#9557]
Copied from https://www.reddit.com/r/neovim/comments/akgizu/inccommand_very_slow_in_tex_files/

Neovim 0.3.4 is slow when using vimtex with `let g:vimtex_fold_enabled=1` which uses `fold-expr`. There's a delay at every keypress. Working theory is that folds are recomputed on every substitution. Can we suppress that? Should be enough to recompute after the substitution has really happened...

[Minimal init.vim](https://pastebin.com/v2sj97va) 
[Example tex file](https://pastebin.com/FQg6AHRs) -- use `%s/accusam/` to trigger the problem

**Comment by justinmk** [comment]
> Can we suppress that?

Would not be a good idea to special-case this for 'inccommand'.

However if it's true that the delay happens at "every keypress" then it does raise the question of why 'redrawtime' is not disabling inccommand after the first 2-second delay. 

Maybe the slowdown is slightly less than 2 seconds, so the 'redrawtime' limit is not triggered. So try setting it to something smaller:

    :set redrawtime=200

**Comment by KillTheMule** [comment]
Disabling `inccomand` seem unsatisfactory here though, doesn't it? From a user's perspective, it's simply a "visual aid" that does not change the buffer, so there's no need to recompute the folds on every keypress. We are already disabling errors for the duration of inccomand, so I'd think another special-casing wouldn't hurt (and maybe it's not as much a special case as one would think, because further live commands should inherit that behavior, right?).

**Comment by justinmk** [comment]
Maybe. Don't know. Depends on whether folds can be affected by search-and-replace. If they can, then disabling re-computation isn't a good idea. If they can't, then it doesn't need to be a special-case: we can disable fold-recomputation for `:substitute` _always_.

Still wondering about the behavior with smaller `redrawtime`.

> Disabling inccomand seem unsatisfactory here though

Note that it is only disabled temporarily until the user leaves the `:` prompt.

**Comment by KillTheMule** [comment]
> If they can, then skipping fold-recomputation could result in display bugs

I very much assume the can.  But what but should happen during an `inccomand`, we're not modifying the buffer during it, so the folds don't need to change. Or am I missing something here?

> Note that it is only disabled temporarily until the user leaves the : prompt.

Technically true, but the next time the user tries an `inccomand`, the same will happen, so it's effectively disabled in this case.

> Still wondering about the behavior with smaller redrawtime.

Can't test myself before tomorrow, but I've asked the reddit user to try.

**Comment by KillTheMule** [comment]
Ahhh right, I was thinking of `icm=split` where we copy the lines into a new buffer, but did not remember that the original buffer shows the changed state as well!

We could open the folds before `:s` and then recompute after... no, let's not go down that rabbit hole :D But it seems disabling via `redrawtime` does not work here, so we should probably "just" fix that.

**Comment by bfredl** [comment]
Perhaps an option to _only_ display changes in split but not in orginal buffer would be an useful addition anyway?

**Comment by bfredl** [comment]
@KillTheMule If the necessary feedback can be duplicated in two places, and some users have an issue with one of the two redundant views, the buffer view, being too slow, wouldn't it be very useful for that user to only enable the split view feedback and thus get some useful feedback but without the speed issue?  What would be the reason to make the quickly redrawn view to be optional, but then keep _slowly_ redrawn view mandatory to get any feedback at all?

**Comment by KillTheMule** [comment]
Ok, so, yeah, it would be useful to solve the speed issue we're seeing here, but you said "anyways" so I figured there was something else I did not see. Might not be too easy to implement...

**Comment by bfredl** [comment]
@KillTheMule mostly a completeness thing, of all four possible combinations, I don't see why specifically split-only would need an extra motivation over the other three. If implementation complexity was the original reason, the speed issue could be shifting the cost-benefit tradeoff now. Someone would still need to do the work, of course :]
