### ISSUE TITLE
Issue with nightly appimage: syntax error: newline expected

### ISSUE THREAD

**Issue by minuta** [neovim/neovim#9559]
- `nvim --version`:  nightly/nvim.appimage
- Operating system/version: Linux Mint 19.1 Tessa
- Terminal name/version: terminator 1.91

### Actual behaviour
Today after trying to get a new nvim.appimage:
```
curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
```

i've got following error:
`
./nvim.appimage: 2: ./nvim.appimage: Syntax error: newline unexpected
`

**Comment by justinmk** [comment]
what are the contents of the `nvim.appimage` file ?

**Comment by minuta** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>16408992/83f20200-2342-11e9-86df-bce83f226b4b</Key><RequestId>13EA33BA43E899BB</RequestId><HostId>xDG2g+OVeh+BrWHiJNnjRMqU4lqmFqpYFiYuhEbu4qQf2D2lcU0kuJXqV+nNT/jTJwZpVWqL4yg=</HostId></Error>%

**Comment by minuta** [comment]
Ok, thanks, it works again!
