### ISSUE TITLE
add a VimL event or autocmd for SIGUSR1

### ISSUE THREAD

**Issue by sharethewisdom** [neovim/neovim#9562]
in [this question on stackexchange](https://vi.stackexchange.com/questions/18346/updating-running-neovims-setting-background-using-a-terminal-response?noredirect=1#comment32318_18346) I woundered how to "refresh" running neovims when the terminal's colorscheme would change. Someone suggested to open an issue here. 

I think this also ties into issue https://github.com/neovim/neovim/issues/6279

**Comment by mhinz** [comment]
I think making it trigger `FocusGained` would make sense.

**Comment by bew** [comment]
@mhinz how would you know it has been triggered from a SIGUSR1 signal?

**Comment by mhinz** [comment]
@bew 

You wouldn't. But does that really matter?

Many plugins do refreshing tasks on `FocusGained`, so I figured it would make sense to reuse that event. The code run on `FocusGained` should decide on whether a given condition changed or not.

This approach seems more general, but I'm open for arguments against it.

**Comment by bew** [comment]
Well OP gave a usecase to do a refresh on SIGUSR1, but maybe I want to do something completely different than a refresh (like update a specific buffer only when it receives SIGUSR1).

Having SIGUSR1 trigger a generic event (FocusGained) means you can't have very specific behavior for what you want..

Same reasoning for SIGUSR2 i guess

**Comment by sharethewisdom** [comment]
@mhinz @justinmk thanks! :+1:
