### ISSUE TITLE
clipboard.vim takes a long time to start 

### ISSUE THREAD

**Issue by taigacute** [neovim/neovim#9570]
- `nvim --version`:0.3.4
- Vim (version: ) behaves differently?N/A
- Operating system/version:mac os high serria 10.13.6
- Terminal name/version: iterm2 the latest
- `$TERM`:xterm-256color

### Steps to reproduce using `nvim -u NORC`
`nvim --startuptime ~/vimstart_up.log`
### Actual behaviour
First
```
184.853  014.465: VimEnter autocommands
223.115  038.132  038.132: sourcing /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/clipboard.vim

```
Second 
```
123.482  015.762: VimEnter autocommands
167.129  043.377  043.377: sourcing /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/clipboard.vim
```

Is it because I installed through brew?
### Expected behaviour
faster

**Comment by KillTheMule** [comment]
See https://www.reddit.com/r/neovim/comments/ab01n8/improve_neovim_startup_by_60ms_for_free_on_macos/

**Comment by justinmk** [comment]
Missing steps to reproduce with `nvim -u NORC`. clipboard.vim won't be sourced _at all_ on startup unless you have something like `set clipboard=unnamed`.

Here's what I see with current HEAD (0.4.0) on macOS HFS+ spinning rust HDD (not SDD):

    nvim -u NORC +'set clipboard=unnamed' --startuptime foo.txt

    053.261  000.596  000.596: sourcing /usr/local/Cellar/neovim/HEAD-f89d0d8/share/nvim/runtime/autoload/provider/clipboard.vim

> Is it because I installed through brew?

No. Homebrew-installed Neovim is the same as any other Neovim, unless you explicitly changed the build type to DEBUG or something like that ...

**Comment by taigacute** [comment]
> 请参阅https://www.reddit.com/r/neovim/comments/ab01n8/improve_neovim_startup_by_60ms_for_free_on_macos/


thank you very much. It helped me

**Comment by taigacute** [comment]
> 缺少重现的步骤`nvim -u NORC`。clipboard.vim不会采购_都_在启动，除非你有类似的东西`set clipboard=unnamed`。
> 
> 这是我在macOS HFS +旋转生锈HDD（不是SDD）上使用当前HEAD（0.4.0 [f89d0d8](https://github.com/neovim/neovim/commit/f89d0d8230f34dca49eddbea179d274955b572b9)）看到的内容：
> 
> ```
> nvim -u NORC +'set clipboard=unnamed' --startuptime foo.txt
> 
> 053.261  000.596  000.596: sourcing /usr/local/Cellar/neovim/HEAD-f89d0d8/share/nvim/runtime/autoload/provider/clipboard.vim
> ```
> > 是因为我是通过brew安装的吗？
> 
> 不，Homebrew安装的Neovim与任何其他Neovim相同，除非您明确地将构建类型更改为DEBUG或类似的东西......

`nvim -u NORC +'set clipboard=unnamed' --startuptime ~/foo.txt`
i got these
```
028.571  000.161: VimEnter autocommands
064.434  035.717  035.717: sourcing /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/clipboard.vim
```
i set `set clipboard=unnamed`  Turns out that this file tries to find my clipboard provider — which is obviously pbcopy on macOS — by doing `s:cmd_ok` which does a system( call. System calls are slow.）Solve by setting it up
```
let g:clipboard = {
  \ 'name': 'pbcopy',
  \ 'copy': {
  \    '+': 'pbcopy',
  \    '*': 'pbcopy',
  \  },
  \ 'paste': {
  \    '+': 'pbpaste',
  \    '*': 'pbpaste',
  \ },
  \ 'cache_enabled': 0,
  \ }
```

**Comment by mzr1996** [comment]
According above method, I tried to add the following script before `set clipboard=unnamed` on Windows. It works well and imporved my startup time by about 800ms! Really thank you.
```
  let g:clipboard = {
  \ 'name': 'win32yank',
  \ 'copy': {
  \    '+': 'win32yank.exe -i --crlf',
  \    '*': 'win32yank.exe -i --crlf',
  \  },
  \ 'paste': {
  \    '+': 'win32yank.exe -o --lf',
  \    '*': 'win32yank.exe -o --lf',
  \ },
  \ 'cache_enabled': 0,
  \ }
```

**Comment by jaghaimo** [comment]
For those looking for a lua equivalent:
```
vim.g.clipboard = {
  name = 'win32yank',
  copy = {
     ["+"] = 'win32yank.exe -i --crlf',
     ["*"] = 'win32yank.exe -i --crlf',
   },
  paste = {
     ["+"] = 'win32yank.exe -o --lf',
     ["*"] = 'win32yank.exe -o --lf',
  },
  cache_enabled = 0,
}
```
