### ISSUE TITLE
Error message output twice

### ISSUE THREAD

**Issue by chrisbra** [neovim/neovim#9574]
I have seen the following behaviour for a while now (and even sometimes with Vim, but I am not sure yet what causes it) and I am only being able to reproduce it reliably with Neovim. 

- `nvim --version`:  NVIM v0.2.2 (Debian package) as well as `NVIM v0.4.0-218-gf89d0d823`
- Vim (version: ) behaves differently? yes (8.1.630, self compiled)
- Operating system/version: Debian
- Terminal name/version: does not matter
- `$TERM`: tmx-256color

### Steps to reproduce using `nvim -u NORC`

Place the following script inside ~/.vim/plugins (or whatever the equivalence is on neovim):
```viml
if exists("g:loaded_vpager") || &cp
  finish
elseif !(v:version > 801 || v:version == 801 && has("patch1647"))
  echomsg "ERROR needs at least Vim 8.1.1647"
  finish
endif
```

Start nvim: `nvim` output:
```
ERROR needs at least Vim 8.1.1647
ERROR needs at least Vim 8.1.1647
```
### Actual behaviour
Note, output is shown twice, interestingly, nvim -u NORC does show it only once.

### Expected behaviour

Note, error output is shown only once.

**Comment by mhinz** [comment]
It's only shown once for me as well (using master), so, you might have to put some comments in your vimrc. :>

**Comment by chrisbra** [comment]
Ah, a wrong `rtp` setting on my side. Sorry, my bad.
