### ISSUE TITLE
:Man badly wraps text since 0.3.2

### ISSUE THREAD

**Issue by programble** [neovim/neovim#9583]
- `nvim --version`: NVIM v0.3.4
- Vim (version: ) behaves differently?
- Operating system/version: macOS 10.14.2
- Terminal name/version: Terminal.app
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:Man regex
```

### Actual behaviour

Text is wrapped, cutting words in half:

```
     These routines implement IEEE Std 1003.2 (``POSIX.2'') regular expressions
      (``RE''s); see re_format(7).  The regcomp() function compiles an RE, writte
     n as a string, into an internal form.  regexec() matches that internal form
      against a string and reports results.  regerror() transforms error codes f
     rom either into human-readable messages.  regfree() frees any dynamically-a
     llocated storage used by the internal form of an RE.
```

Tag lists are misaligned:

```
     REG_NOSPEC    Compile with recognition of all special characters turned off
     .  All characters are thus considered ordinary, so the ``RE'' is a literal
      string.  This is an extension, compatible with but not specified by IEEE St
     d 1003.2 (``POSIX.2''), and should be used with caution in software intende
     d to be portable to other systems.  REG_EXTENDED and REG_NOSPEC may not be
      used in the same call to regcomp().
```

### Expected behaviour

Word-aware wrapping, like `MANPAGER=less man`:

```
     These routines implement IEEE Std 1003.2 (``POSIX.2'') regular expres-
     sions (``RE''s); see re_format(7).  The regcomp() function compiles an
     RE, written as a string, into an internal form.  regexec() matches that
     internal form against a string and reports results.  regerror() trans-
     forms error codes from either into human-readable messages.  regfree()
     frees any dynamically-allocated storage used by the internal form of an
     RE.
```

Proper tag list alignment, like `MANPAGER=less man`:

```
     REG_NOSPEC    Compile with recognition of all special characters turned
                   off.  All characters are thus considered ordinary, so the
                   ``RE'' is a literal string.  This is an extension, compati-
                   ble with but not specified by IEEE Std 1003.2
                   (``POSIX.2''), and should be used with caution in software
                   intended to be portable to other systems.  REG_EXTENDED and
                   REG_NOSPEC may not be used in the same call to regcomp().
```

This behaviour was present before v0.3.2, specifically #9023.

**Comment by justinmk** [comment]
> Text is wrapped, cutting words in half:

Can be fixed with `setlocal linebreak`, which I will do now.

> Tag lists are misaligned:

I see this on macOS but not ubuntu, depends on the manpage structure. #9017 is more important than this minor cosmetic regression, so this is `wontfix`.

**Comment by programble** [comment]
Would you consider adding an option to restore the previous behaviour? I'd rather have hard-wrapped text and the occasional broken link.

**Comment by programble** [comment]
Please reconsider this issue. It is more than a minor cosmetic regression. For example, compare the formatting of `printf(3)` in less:

<img width="682" alt="screen shot 2019-02-20 at 11 23 06" src="https://user-images.githubusercontent.com/166462/53107127-63146b00-3502-11e9-83cd-11bb406b1738.png">

with that of nvim:

<img width="682" alt="screen shot 2019-02-20 at 11 22 41" src="https://user-images.githubusercontent.com/166462/53107163-79222b80-3502-11e9-803f-f34bb222ea05.png">

The latter offers a degraded reading experience and frankly looks like a mess.

I'd also like to point out that the original problem of manual page references being split across lines is a non-issue on systems which use the modern mdoc format (macOS and any BSD). For these, groff knows not to insert line breaks in references and will move the whole thing to the next line. On such systems, this change produces worse results and provides no benefit.

I'm willing to submit a pull request adding an option to restore the previous behaviour.

**Comment by justinmk** [comment]
> I'm willing to submit a pull request adding an option to restore the previous behaviour.

Ok.
