### ISSUE TITLE
'scrollback' crash

### ISSUE THREAD

**Issue by alok** [neovim/neovim#9588]
If I open a terminal, nvim immediately crashes. I'm not sure how to get debug info that would be useful for figuring out what's going on.

This is a combination of a bug report and a note to self since I'm not really sure what's causing it. I know it has some relation to my config, since `nvim NORC` makes it disappear, and some relation to #9563, since previous commits did not have this issue. Weirdly, if I set the scrollback to 100,000 explicitly, nothing happens.

**Comment by alok** [comment]
It seems setting the scrollback to -1 is what causes the issue, since if I set it to 100,000 explicitly, nothing happens.

**Comment by justinmk** [comment]
which system? backtrace should be easy to get, see [wiki](https://github.com/neovim/neovim/wiki/Development-tips#debugging).

Thanks for bisecting!

cc @mhinz

**Comment by alok** [comment]
Ubuntu 18.04 and Mac 10.13.6

**Comment by justinmk** [comment]
```
sudo apt install systemd-coredump
2>&1 coredumpctl -1 gdb | tee -a bt.txt
thread apply all bt full
```

Post the `bt.txt` file here.

**Comment by alok** [comment]
Do I run nvim, then that command? Nvim doesn't give a core dump, it just immediately closes.

**Comment by justinmk** [comment]
> Do I run nvim, then that command? 

Provoke the crash using `nvim`, then run that command. Your OS keeps a global list of coredumps.



> Nvim doesn't give a core dump

What leads you to believe that? With newer systems there is no `core` file. Hence the instructions I gave above.

on macOS you can just do this:

    open -a Console

Read https://github.com/neovim/neovim/wiki/Development-tips#debugging if you still have questions.

**Comment by alok** [comment]
When I run nvim and then the command above, I get: `no match found`.

**Comment by justinmk** [comment]
Sounds like OOM (out of memory) rather than a segfault. 

Can you try this patch and then check `$NVIM_LOG_FILE` ?

```diff
diff --git a/src/nvim/memory.c b/src/nvim/memory.c
index b49b521bc965..3f6719daaab8 100644
--- a/src/nvim/memory.c
+++ b/src/nvim/memory.c
@@ -102,6 +102,7 @@ void *xmalloc(size_t size)
 {
   void *ret = try_malloc(size);
   if (!ret) {
+    ELOG("XXX");
     mch_errmsg(e_outofmem);
     mch_errmsg("\n");
     preserve_exit();
```

**Comment by alok** [comment]
`ERROR 2019-02-09T16:42:03.813 17277 xmalloc:105: XXX`

That's the whole file when I run `NVIM_LOG_FILE=file nvim`

**Comment by justinmk** [comment]
Thanks, that confirms OOM. 

Roughly how much free RAM is on your system before running Nvim?

**Comment by alok** [comment]
24GB

**Comment by justinmk** [comment]
Can you try https://github.com/neovim/neovim/pull/9605 ?
