### ISSUE TITLE
Windows: After trying to add a init.vim i get error E84

### ISSUE THREAD

**Issue by Drunkenpanda2000** [neovim/neovim#9591]
- `nvim --version`: LATEST (cant open vim socantsee)
- Vim (version: ) behaves differently?
- Operating system/version: Windows 10
- Terminal name/version: cmder
- `$TERM`: Powershell

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour

uppon launching vim i get the following error.

E484: Can't open file C:\Users\nicta\.config\nvim\syntax\syntax.vim
Press ENTER or type command to continue

see https://imgur.com/fSIgBwV

EDIT:
When i Enter or try to enter a command nothing happens
### Expected behaviour

Vim launches and uses my init.vim wich is located at  C:\Users\nicta\.config\nvim\

### evrything i have done.

i have ran:
(installing plug.vim)

```
md ~\AppData\Local\nvim\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile(
  $uri,
  $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
    "~\AppData\Local\nvim\autoload\plug.vim"
  )
)
```

I made a init.vim located at C:\Users\nicta\.config\nvim

it has the following code 

```
"##########################&|  General   |&###########################"

set number

"##########################&| vimplugged |&###########################"

call plug#begin('~\AppData\local\nvim\plugged')

plug 'https://github.com/luochen1990/rainbow.git

```
Vim Env is set at  VIM                            C:\Users\nicta\.config\nvim

### What i've tried to do as a fix

i have tried placing the init.vim file at C:\Users\nicta\.config\nvim\config This did not help.

**Comment by JamsNJellies** [comment]
Does the file it is looking exist?
If it doesn't, have you run :PlugInstall
Not sure if you need too or not

**Comment by Drunkenpanda2000** [comment]
The file exists.
It's not an issue with plug.vim i think (i could be wrong)
also i can't run :PlugInstall becouse i cant acces vim.

Becouse when i get the error 

E484: Can't open file C:\Users\nicta.config\nvim\syntax\syntax.vim
Press ENTER or type command to continue

i cant actually pres enter or type a command.

See https://imgur.com/fSIgBwV

**Comment by JamsNJellies** [comment]
Try commenting out your init.vim line by line to find the issue

**Comment by Drunkenpanda2000** [comment]
commenting evrything out and deleting the file do not fix the issue. 

It keeps looking for a file that isent there and if there is file there it stil doesnt load.
(or is synthax here not used as a wildcard?)

**Comment by erw7** [comment]
@Drunkenpanda2000  What happens if you set `C:\Users\nicta\.config` to `XDG_CONFIG_HOME` environment variable without setting the `VIM` environment variable?

**Comment by Drunkenpanda2000** [comment]
can put `init.vim` in `C:\Users\nicta\AppData\Local\nvim` without setting either environment variable. : Same issue

set `C:\Users\nicta\.config` to `XDG_CONFIG_HOME` environment: This **solved the issue**.

##however init.vim is stil not being loaded. Do i make a new issue or do can we keep troubleshooting here ?

**Comment by buahaha** [comment]
Helpful. Great!
