### ISSUE TITLE
Mac: can't print an unprintable character

### ISSUE THREAD

**Issue by mblsha** [neovim/neovim#9592]
- `nvim --version`:
NVIM v0.3.4 (from Homebrew)

- Vim (version: VIM - Vi IMproved 8.1) behaves differently?
Yes

- Operating system/version:
macOS Version 10.14.3 (Build 18D42)

- Terminal name/version:
iTerm2 Build 3.2.7

- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:!echo -e '\a'
```

### Actual behaviour
No bell is audible in NVim.

### Expected behaviour
Bell is audible (as it is in Vim).

**Comment by justinmk** [comment]
In Nvim, `:!` goes to a pipe, not a pty. Control characters have no effect on the terminal.

If you really want to do this for some reason, you can write directly to the stderr channel:

    :call chansend(v:stderr, "\007")
    
See also [the FAQ](https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes).

See also https://github.com/neovim/neovim/issues/4102 and https://github.com/neovim/neovim/issues/4338 which I found by [searching for "bell"](https://github.com/neovim/neovim/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+bell).
