### ISSUE TITLE
Can't assign function argument to global variable in job callback

### ISSUE THREAD

**Issue by ausernamethatisnttaken** [neovim/neovim#9594]
- `nvim --version`: NVIM v0.3.1, 0.3.4, 0.4.0-250-g3ff1228f7
- Vim (version: ) behaves differently? Yes
- Operating system/version: OSX 10.13.6
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

I have a job I want to run in the background of vim, and update my status line with the periodic results of that job.

I'm able to setup the timer, call the external job and get my response back. I'm able to `echom` the response and see it in `:messages`.

I am unable to get my global variable to take hold of the new value though.

Initially I thought I was just mis-understanding vimscript but it seems like the code works in VIM (with some compatibility changes for `job_start`, `out_cb`, can provide RC if required).

### Steps to reproduce using `nvim -u NORC`

Place this in `argument_bug.vim`

    let g:some_global = 'an echo example'
    let g:another_global = -1

    " timer calls this regularly to start background job
    function! TimerRun(timer)
      call jobstart('date', {'on_stdout': 'TimerCallback'})
    endfunction

    " when job completes it will send stdout here
    function! TimerCallback(j, d, e)
      " proof we receive something
      echom a:d[0]
      " update external global
      let g:another_global = a:d[0]
    endfunction

    let timer = timer_start(2000, 'TimerRun', {'repeat': -1})

Run via `nvim -u argument_bug.vim` to load it as your vimrc.

### Actual behaviour

`:echo g:some_global`, you'll see the response, 'an echo example'. 

`:messages`, you'll see a repeated output of the date.

**`:echo g:another_global` you will see no/empty output.**

### Expected behaviour

`:echo g:another_global` should output the last recorded output of the job.

**Comment by justinmk** [comment]
`deepcopy(a:d)` doesn't help:

    let g:another_global = deepcopy(a:d)

Using concatenation (`.=`) shows results:

    let g:another_global .= a:d[0]

Hmm.

**Comment by bfredl** [comment]
Is there anything weird with this at all? `let g:another_global = a:d[0]` _will_ discard output with multiple `on_stdout` calls, how could it not?

@ausernamethatisnttaken you might want `stdout_buffered` if you want to get all output in a single call (reasonable with one-shot low-bandwidth calls like `date` ).

**Comment by justinmk** [comment]
@ausernamethatisnttaken  What happens is that the global gets overwritten with an empty line, and it happens that when you evaluate it, the value happens to be empty. 
 This fixes it:

```vim
  if len(a:d[0])
    let g:another_global = a:d[0]
  endif
```

`TimerCallback` (which is actually a job callback, not timer) gets called quickly in succession, and the last call is always an empty line (in this case). 

You don't see the empty line in the `:echom` because of how `:echom` works: even if you added an extra call, it would not appear in `:messages` : 

    echom ''

**Comment by bfredl** [comment]
> This fixes it:

```
if len(a:d[0])
 let g:another_global = a:d[0]
endif
```

This is an anti-pattern though, the output is allowed to be split up at any byte position into multiple calls, so it is not safe. Rather `stdout_buffered` is preferred for this situation, at least if the output is not expected to be very large.

**Comment by ausernamethatisnttaken** [comment]
Ah thank you so much. Sorry for the noise! I asked on Stackoverflow and got some "looks ok to me, maybe bug" and the fact that it behaved as *intended* (though possibly incorrectly?) in VIM took me here. Reading the docs on `on_stdout` properly makes it clear why things were happening the way they are.

**Comment by mhinz** [comment]
@ausernamethatisnttaken 

Vim added their own implementation of jobs after Nvim added theirs based on [libuv](https://github.com/libuv/libuv). Just don't assume them to work the same. :-)

Both get the job done (pun indended) but are implemented differently, often act differently and take different options.
