### ISSUE TITLE
win/TUI: drawing errors, artifacts,  improper sizing

### ISSUE THREAD

**Issue by NicTanghe** [neovim/neovim#9596]
Vim version: NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5

- Vim (version: ) behaves differently?
- Operating system/version: Windows10
- Terminal name/version: cmder / Powershell / cmd

### Steps to reproduce

```
enable numbered in init.vim
```

### Actual behaviour

When selecting lines drawing errors occur.

drawing errors
https://i.imgur.com/HD9U9Y1.png

### Expected behaviour

below is unselected
https://i.imgur.com/uSj6RPa.png

**Comment by justinmk** [comment]
Can you try the appveyor artifact from https://github.com/neovim/neovim/pull/9094 ?

**Comment by Drunkenpanda2000** [comment]
i'm sorry but i don't understand what you mean.

**Comment by erw7** [comment]
I think this is the same phenomenon as #9461.

@Drunkenpanda2000 Have you set the `TERM` environment variable to `xterm` or `xterm-256 color`? If so, please do not set the `TERM` environment variable.

**Comment by justinmk** [comment]
@Drunkenpanda2000 here's a direct link: https://ci.appveyor.com/project/neovim/neovim/builds/22156610/job/k7c0xjr21dpox7ro/artifacts

can you try the artifact there?

**Comment by justinmk** [comment]
No reply, so closing.
