### ISSUE TITLE
'pumblend' doesn't handle gui=reverse well

### ISSUE THREAD

**Issue by jamessan** [neovim/neovim#9597]
- `nvim --version`: v0.4.0-252-gb3ce0019a
- Vim (version: ) behaves differently? n/a
- Operating system/version: Debian
- Terminal name/version: KiTTY
- `$TERM`: xterm-kitty

When `Pmenu` highlighting uses the reverse attribute, instead of specific colors, the color ends with the text instead of extending for the whole line.

### Actual behavior

![reverse-pmenu](https://user-images.githubusercontent.com/112971/52536762-ccd78c80-2d2c-11e9-9e0c-5c8b14c4affd.png)

### Expected behavior

Setting the highlight to specific colors works.

![color-pmenu](https://user-images.githubusercontent.com/112971/52536766-db25a880-2d2c-11e9-9b2c-9a0da8c712c5.png)

**Comment by bfredl** [comment]
`get_colors_force` should check reverse attribute and replace it by its effect (swap rgb_bg  and rgb_fg), I will fix it.
