### ISSUE TITLE
command line is hided by windows 10 task bar

### ISSUE THREAD

**Issue by ShuguangSun** [neovim/neovim#9604]
- `nvim --version`: 0.3.4 and 0.4.0
- Operating system/version: Windows 10

### Steps to reproduce 

run nvim-qt.exe and then maximize the window
or nvim-qt --maximized
or put `call GuiWindowMaximized(1)` in ginit.vim

### Actual behaviour
The nvim-qt is really maximized but it fit the whole screen (some kind like of fullscreen). And the windows taskbar (with start menu and those shortcut icons) hide the status/command line. I need to `set cmdheight=2` to make the area above windows task bar.

The fontsize and dpi has some impact.

### Expected behaviour
I expect the bottom of nvim-qt windows fit windows taskbar.

**Comment by justinmk** [comment]
https://gitter.im/equalsraf/neovim-qt

**Comment by rkrishnaan** [comment]
What is the solution for this issue? It still happens when I create a new tab in neovim.

**Comment by tstopak** [comment]
I am also experiencing this on Windows 10. Is there a solution, or should this issue be reopened?
