### ISSUE TITLE
fsync() usage

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9611]
[Recent discussion](https://news.ycombinator.com/item?id=19126495) about `fsync()` led me to check if Nvim uses it correctly.

https://wiki.postgresql.org/wiki/Fsync_Errors
https://fosdem.org/2019/schedule/event/postgresql_fsync/
https://danluu.com/file-consistency/

There's at least three concerns:

1. `fsync()` on Linux before 4.13 (and maybe other unixes) may not report hardware failures to userspace.
   - Not much we can do about this[1].
2. `sync()` by another process [may potentially clear fsync() error](https://news.ycombinator.com/item?id=19130070) 
   - Nothing we can do about this.
3. macOS (OS X) requires `fcntl(F_FULLFSYNC)` to flush the disk's own buffers[2].
    - libuv [does that](https://github.com/libuv/libuv/issues/1579) for us.

@brammool @chrisbra Vim does not use `F_FULLFSYNC` on macOS. The recommended pattern is `F_FULLFSYNC` and fallback to `fsync()` if that fails:

    r = fcntl(fd, F_FULLFSYNC);
    if (r != 0 && errno == ENOTTY) {
      r = fsync(fd);
    }

---

[1] Reference: https://lwn.net/Articles/752063/

> Google has its own mechanism for handling I/O errors. The kernel has been instrumented to report I/O errors via a netlink socket; a dedicated process gets those notifications and responds accordingly. This mechanism has never made it upstream, though.

> For [older kernels], there is little that can be done to help PostgreSQL detect I/O errors. It may come down to running a daemon that scans the system log, looking for reports of I/O errors there.

[2] [golang](https://github.com/golang/go/commit/be10ad762289943638efb279fc7e04c73b8d7cee) had this bug as well.

**Comment by brammool** [comment]
Justin M. Keyes wrote:

> [Recent discussion](https://news.ycombinator.com/item?id=19126495) about `fsync()` led me to check if Nvim uses it correctly.
> 
> https://wiki.postgresql.org/wiki/Fsync_Errors
> https://fosdem.org/2019/schedule/event/postgresql_fsync/
> https://danluu.com/file-consistency/
> 
> There's at least three concerns:
> 
> 1. `fsync()` on Linux before 4.13 (and maybe other unixes) may not report hardware failures to userspace.
>    - Not much we can do about this[1].
> 2. `sync()` by another process [may potentially clear fsync() error](https://news.ycombinator.com/item?id=19130070) 
>    - Nothing we can do about this.
> 3. macOS (OS X) requires `fcntl(F_FULLFSYNC)` to flush the disk's own buffers[2].
>     - libuv [does that](https://github.com/libuv/libuv/issues/1579) for us.
> 
> @brammool @chrisbra Vim does not use `F_FULLFSYNC` on macOS. The recommended pattern is `F_FULLFSYNC` and fallback to `fsync()` if that fails:
> 
>     r = fcntl(fd, F_FULLFSYNC);
>     if (r != 0 && errno == ENOTTY) {
>       r = fsync(fd);
>     }

Thanks for looking into this.  Let's just include that code.
I'll make a vim_fsync() function to keep it central.

-- 
FIRST SOLDIER:  So they wouldn't be able to bring a coconut back anyway.
SECOND SOLDIER: Wait a minute! Suppose two swallows carried it together?
FIRST SOLDIER:  No, they'd have to have it on a line.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
