### ISSUE TITLE
SignColumn extends into EndOfBuffer zone but LineNr does not

### ISSUE THREAD

**Issue by wincent** [neovim/neovim#9613]
This screenshot shows how the sign column (the one with the "m" mark in it) is drawn all the way down to into the "EndOfBuffer" region, but the "LineNR" area is not:

<img width="1440" alt="nvim" src="https://user-images.githubusercontent.com/7074/52814062-7efbb500-309b-11e9-913f-8134d7b5d335.png">

So not sure whether this is a bug report or a feature request, but one of two things should probably happen in the name of consistency ( either "the sign column should not extend into the EndOfBuffer zone" or "the LineNr columns should be drawn in the EndOfBuffer area just like the SignColumn is").

I suspect that, given that the ColorColumn stuff on the right also doesn't extend down into the end of buffer area, then perhaps the SignColumn should not extend. (Either that or ColorColumn *should* extend all the way down; I'd actually prefer it if they all extended all the way down, but above all I mostly just want something consistent.)

Screenshot was taken on macOS 10.13.6 (High Sierra) in iTerm2 (Build 3.3.20190212-nightly) with a `$TERM` of `xterm-256color`. Neovim is:

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```

Same issue exists on Vim. Upstream report is at: https://github.com/vim/vim/issues/3964

**Comment by mhinz** [comment]
There are 3 special columns: fold column, sign column, and number column. The former two extend to the end of the window and only the number column goes until the end of the buffer.

For the latter it makes kind of sense. Why would you want to see further line numbers after the end of the buffer?

So, yes, IMHO the fold and sign column should only go to the end of the buffer as well. And somehow I have the feeling I once sent a patch for this very thing to vim_dev... I can't really remember, but if so, it was many years ago.

**Comment by mhinz** [comment]
Long story short: Some people wanted A and some B. No decision was ever made. I gave up.

**Comment by wincent** [comment]
Thanks for the link.

Just to be clear, when I mentioned the possibility of the line number column extending all the way down, I meant the *background* of it; like you say, is would be wrong to have *numbers* there.

**Comment by mhinz** [comment]
@neovim/core 

Would you agree with extending the number column to the end of the screen? If so, I'd have another look at it.

**Comment by justinmk** [comment]
@mhinz 	given how much test coverage we have compared to then, it's much lower-risk (except performance regressions). No objection from me.

Maybe make it non-optional, unless someone objects, then maybe throw it into 'display' option.

**Comment by wincent** [comment]
Upstream fix for this landed in Vim: https://github.com/vim/vim/commit/8ee4c01b8c79a29065c1af05e5d9c0721069765f

**Comment by wincent** [comment]
Thanks @mhinz!
