### ISSUE TITLE
Javascript Syntax Highlight Problem

### ISSUE THREAD

**Issue by KsRyY** [neovim/neovim#9627]
Not a real problem that acts wrong, but a small syntax highlight problem.

The `javascript` syntax highlight does not support arrow function like this:
``` javascript
var func = () => {}
```
Neovim does not highlight the arrow.

**Comment by teto** [comment]
neovim just uses the runtime from vim so this is best reported to vim or in this case, the maintainer of the javascript syntax: https://github.com/neovim/neovim/blob/ece19b459c082eae05b5c480f6ee91181f002c02/runtime/syntax/javascript.vim#L3

**Comment by mhinz** [comment]
What teto said. Or if you just want to get it done: https://github.com/pangloss/vim-javascript.
