### ISSUE TITLE
Double click + drag selection broken in Neovim (works in Vim).

### ISSUE THREAD

**Issue by trusktr** [neovim/neovim#9628]
Re-opening https://github.com/neovim/neovim/issues/4754

See comment there: https://github.com/neovim/neovim/issues/4754#issuecomment-464493984

I'm in NeoVim v0.3.1 (which I verify by running the `:version` command).

here's a video showing it not working: https://youtu.be/dFDsHjVdRSg

**Comment by justinmk** [comment]
If you're going to reopen bugs, you should fill out the issue template. That issue was closed because I can't reproduce it in iTerm2, which is the terminal that was reported.

> here's a video showing it not working: https://youtu.be/dFDsHjVdRSg

That video does not use `nvim -u NORC`.

**Comment by trusktr** [comment]
Sorry, here's more info:

- My terminal is bash.exe (Ubuntu 16.04 in WSL, Windows 10)
- Using the same vimrc with the same plugins, here's a video showing that it works in Vim: https://youtu.be/k0ywCmHWzEA
- Video showing version number and it not working in `nvim -u NONE`

Here's my vimrc (and the select word-by-word with mouse works in Vim while using it): https://github.com/trusktr/.vimrc/blob/8af722054c7e6c221f173e7d5a09bb550923cbb4/.vimrc

**Comment by justinmk** [comment]
Reopened https://github.com/neovim/neovim/issues/4754 since it has better info.
