### ISSUE TITLE
Unwanted CSS Key Frame Property highlighting in SCSS property names

### ISSUE THREAD

**Issue by zezic** [neovim/neovim#9632]
- `nvim --version`:
```
NVIM v0.4.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be/build/config -I/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be/src -I/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be/.deps/usr/include -I/usr/include -I/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be/build/src/nvim/auto -I/build/neovim-ms78Zg/neovim-0.4.0+ubuntu1+git201902182021-ece19b4-eada8be/build/include
Compiled by buildd@lgw01-amd64-033

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system/version: Ubuntu 18.04
- Terminal name/version: MATE Terminal 1.20.0
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`

```
echo -e ".myclass {\n  bottom: 0;\n}" > style.scss
nvim -u NORC style.scss
```

### Actual behaviour
![actual](https://user-images.githubusercontent.com/1945127/53101950-cec6fa00-353b-11e9-8a56-da97d5f76bb1.png)

### Expected behaviour
![expected](https://user-images.githubusercontent.com/1945127/53101957-d1c1ea80-353b-11e9-85ee-954c69cb7ad9.png)

### Notes
Probably, this is happens because we have `css.*Prop` here: https://github.com/neovim/neovim/blob/master/runtime/syntax/sass.vim#L20-L21 which is also matches `cssKeyFrameProp` which matches `/\d*%\|from\|to/`

**Comment by mhinz** [comment]
Hi.

You need to report that to the maintainer of the syntax file: https://github.com/neovim/neovim/blob/master/runtime/syntax/sass.vim#L3

Then it will get merged into Vim and we merge Vim's runtime patches.
