### ISSUE TITLE
has-patch does not work as intended

### ISSUE THREAD

**Issue by jreybert** [neovim/neovim#9635]
- `nvim --version`: v0.3.4
- Vim (version: all) behaves differently?: yes
- Operating system/version: Centos 7.6
- Terminal name/version: mate-terminal
- `$TERM`: xterm

I did not look into `has-patch` implementation, but I suspect that it relies on `v:version`. As neovim get patches from vim, but not all, you did get 8.1 patches, but you did not upgraded `v:version`.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:echo has("patch-8.0.1445")
:echo has("patch-8.1.0662")
```

### Actual behaviour

```
:echo has("patch-8.0.1445")
1
:echo has("patch-8.1.0662")
0
```

### Expected behaviour

```
:echo has("patch-8.0.1445")
1
:echo has("patch-8.1.0662")
1
```

**Comment by justinmk** [comment]
Nvim has some Vim 8.1 patches, but until _all_ Vim 8.0 patches are included (so `v:version` becomes 801), `v:version` must stay at 800. If you want to check for a feature, check the Nvim version (`has('nvim-x.y.z')`) or use actual feature-detection.

There's nothing we can reasonably do about this.  We sure could use more help merging 8.0 patches, though.

**Comment by jreybert** [comment]
> There's nothing we can reasonably do about this. We sure could use more help merging 8.0 patches, though.

Actually, a comment about it in the `has-patch` help would be welcomed, at least to warn that 8.1 patch detection won't work.

> If you want to check for a feature, check the Nvim version (`has('nvim-x.y.z')`) or use actual feature-detection.

I want to check this vim 8.1 patch: [8.1.0864](https://github.com/vim/vim/commit/375e3390078e740d3c83b0c118c50d9a920036c7). I can not rely on nvim version nor feature name.

**Comment by justinmk** [comment]
> a comment about it in the `has-patch` help would be welcomed, at least to warn that 8.1 patch detection won't work.

That doesn't make sense. `v:version` is at 800 so there is nothing inconsistent. This is how Vim works.

> I want to check this vim 8.1 patch: [8.1.0864](https://github.com/vim/vim/commit/375e3390078e740d3c83b0c118c50d9a920036c7). I can not rely on nvim version nor feature name.

If that patch is merged into Nvim 0.4.0 then yes, you can rely on `has('nvim-0.4.0')`. No one sent a patch to merge it though :(

**Comment by jreybert** [comment]
> That doesn't make sense. v:version is at 800 so there is nothing inconsistent. This is how Vim works.

As a help reader, I don't have to be aware that v:version == 800 if I want to use `has("patch-8.1.0662")`. If I look in the neovim log, [patch-8.1.0662](https://github.com/neovim/neovim/commit/fa5182489a660e672bac6ea78ba4eefcbba9d6eb) has been merged in 0.3.4, but still `has("patch-8.1.0662")` returns 0.

Maybe you won't fix it because neovim development is not compatible with vim has-patch behavior, but then, help should highlight it.

Futhermore, this is inconsistent as patch number is reset to zero for each number version. Then, the following example in help is wrong:
```
v:version == 602 && has("patch148")
```
Let say there is a patch 123 in both vim 8.0 and 8.1, you merge both or only 8.1 one, but v:version stays at 800, there is something inconsistent.

I understand you don't to bother much with that, but if it does not work, user must be warn.

Final hint: not sure how [included_patches](https://github.com/neovim/neovim/blob/40f5a6c4dafe4bbca227d4c6bda0d9a94d817d71/src/nvim/version.c#L74) works, but having one array per vim version would solve the issue.

**Comment by justinmk** [comment]
> If I look in the neovim log, [patch-8.1.0662](https://github.com/neovim/neovim/commit/fa5182489a660e672bac6ea78ba4eefcbba9d6eb) has been merged in 0.3.4, but still `has("patch-8.1.0662")` returns 0.

`has("patch-8.1.0662")` will work as soon as `v:version` reaches 801. There's a window of time where it will be false. One can either check `has('nvim-0.3.4')` or wait until `v:version` reaches 801.

> Maybe you won't fix it because neovim development is not compatible with vim has-patch behavior, but then, help should highlight it.

Again, that's not the case. Everything works the same. The fact that the patch was merged before `v:version` is an implementation detail.

> Let say there is a patch 123 in both vim 8.0 and 8.1, you merge both or only 8.1 one, but v:version stays at 800, there is something inconsistent.

Vim works _the same way_.

> Final hint: not sure how [included_patches](https://github.com/neovim/neovim/blob/40f5a6c4dafe4bbca227d4c6bda0d9a94d817d71/src/nvim/version.c#L74) works, but having one array per vim version would solve the issue.

Of course. But that will be difficult to maintain. The only reasonable approach is to finish merging 8.0 patches so that we can bump `v:version`.

**Comment by jreybert** [comment]
First, I must admit this is a minor inconvenience, and I may be the only one affected by this.

> has("patch-8.1.0662") will work as soon as v:version reaches 801. There's a window of time where it will be false. One can either check has('nvim-0.3.4') or wait until v:version reaches 801.

OK, this is right. But has-patch help does not warn me that `has("patch-8.1.0662")` will work under some condition relative to nvim development.

> > Let say there is a patch 123 in both vim 8.0 and 8.1, you merge both or only 8.1 one, but v:version stays at 800, there is something inconsistent.

> Vim works _the same way_.

For this specific case, I disagree: vim resets `included_patches` at each new release: there can't be any confusion about a patch number between two vim versions. Again, chances that it happens AND someone is bothered by that are really small.

**Comment by bfredl** [comment]
Another direction would be to enhance semantic feature detection. Maybe there should be a function to check what scopes an option works for. This is also relevant for other changes, like win-local listchars introduced by nvim. There is no vim-patch number for that.
