### ISSUE TITLE
brew install on Mac gets segmentation fault 11

### ISSUE THREAD

**Issue by zpz** [neovim/neovim#9636]
Similar to issue https://github.com/neovim/neovim/issues/9134, but that issue says "brew install" works fine. My case is `brew install neovim` installs 0.3.4 on my Mac 10.13.x. Trying to launch neovim binary gets `segmentation fault 11` error.

**Comment by justinmk** [comment]
The relevant issue is pinned: https://github.com/neovim/neovim/issues/9630

#9134 is completely unrelated.
