### ISSUE TITLE
textobject selection not valid when `selection=exclusive`

### ISSUE THREAD

**Issue by ZSaberLv0** [neovim/neovim#9640]
- `nvim --version`: v0.3.1 and v0.3.4 both has this issue (I have no other nvim version to test)
- Vim (version: ) behaves differently?
see https://github.com/vim/vim/issues/4024
- Operating system/version: MacOS 10.14
- Terminal name/version: MacOS's builtin Terminal 2.9 (421)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
set selection=exclusive
```

1. assume we have text: `'ab|c'`, and `|` is the cursor position
2. stay in `normal mode`, use `vi"` or vi` to select (double quote or back quote, that does not match)
    * `vi]` or `vi}` won't cause the issue

### Actual behaviour

cursor moved left, result to `'a|bc'`

### Expected behaviour

no match, the cursor stays at old position

**Comment by justinmk** [comment]
How about merging the vim patch ?

https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim

**Comment by pierre87** [comment]
#9658
