### ISSUE TITLE
Neovim sometimes unable to call functions defined in ~/.bashrc

### ISSUE THREAD

**Issue by jacob-emery** [neovim/neovim#9648]
- `nvim --version`: latest Arch Linux version
- Vim (version: ) behaves differently? Not tried yet
- Operating system/version: Arch Linux
- Terminal name/version: GNOME Terminal

hello everyone, I have a question regarding neovim not loading functions defined by me in my ~/.bashrc file. I think it is a bug with neovim, but I could be wrong... maybe I simply didn't set up everything as I should have.

The following two lines are in my ~/.bashrc
m() { local f="$1"; env MATLAB_JAVA=/usr/lib/jvm/java-8-openjdk/jre matlab -nosplash -nodesktop -r "run('$f');";}
export -f m

The following code is in my init.vim file:
let &shell='/usr/bin/bash --login'

Case 1
If I enter the following command in the terminal, it will work:
m [optional path/]somefile.m

Case 2
When I open the terminal and I start neovim from there, and afterwards I load a file (to be clear, from neovim's interface), then I am able to correctly execute the following command:
:term m %

Case 3
If I open a file using neovim from the terminal interface, i.e. if i enter:
nvim [optional path/]somefile.m
then I am able to correctly execute the following command from neovim:
:term m %

Case 4
When I double click on a file directly from my file manager (GNOME Files in my case) the file is opened with neovim (since neovim is my default text editor). In this case the following command will not be working:
:term m %
This is the error it gives:
/usr/bin/bash: m: command not found.

Does anyone know how to fix the error in the 4th case? Thank you for reading.

**Comment by justinmk** [comment]
Depends on how your desktop (GNOME) launches the application. Has nothing to do with Neovim.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
