### ISSUE TITLE
Default neovim plugins are quite heavy? 

### ISSUE THREAD

**Issue by cottrell** [neovim/neovim#9664]
On MacOS with latest neovim installed via brew. Might be an interesting corner case or a known issue. 

I am imagining you strive to keep things under 100ms in the default case so something has probably drifted?

```
353.547  318.819  318.657: sourcing /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/python3.vim
354.150  319.728  000.909: sourcing /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/ftplugin/python.vim
```

All other logs items are around 1ms with one or two almost 10ms.

**Comment by KillTheMule** [comment]
See https://www.reddit.com/r/neovim/comments/ab01n8/improve_neovim_startup_by_60ms_for_free_on_macos/

**Comment by teto** [comment]
Setting `g:python_host_prog` or `g:python3_host_prog` should boost your startup time as neovim won't have to look for the interpreter.

**Comment by justinmk** [comment]
see also https://github.com/neovim/neovim/issues/9570

> I am imagining you strive to keep things under 100ms in the default case so something has probably drifted?

As the issue template requested, `nvim -u NORC` would not show this. It is triggered by a plugin that uses python.
