### ISSUE TITLE
Checkhealth: Do not fail if python file looks executable but is not

### ISSUE THREAD

**Issue by ujeropoc** [neovim/neovim#9672]
When executing `:checkhealth`, I get the following error and then nothing more

    health#provider#check
    ========================================================================
      - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
        function health#check[21]..health#provider#check[3]..<SNR>45_check_python[149]..<SNR>45_version_info[1]..<SNR>45_latest_pypi_version[2]..<SNR>45_download[15]..<SNR>45_system, line 11
        Vim(let):E903: Process failed to start: no such file or directory: "python"

The Problem is in nvim\runtime\autoload\health\provider.vim `s:download(url)`
In my setup `cygdrive/bin` is on the PATH but the various python installations are not.
`python` is a `cygwin-symlink` which `executable('python')` deems good enough but windows can not handle so `system()` throws the E903

The problem is solved if I surround the `system` in `s:download` with a try catch to look like this

    try
        let rv = s:system(['python', '-c', script])
    catch /E903/
        return "python present but not executable"
    endtry

**Comment by justinmk** [comment]
>     return "python present but not executable"

How is that any better than the current behavior?

**Comment by ujeropoc** [comment]
with the try catch I get all the interesting output from `health#provider#check` without it, only one message about python not being executable (which was highly confusing to me because I have python 2 disabled and `python3_host_prog` set to the full path)

`s:latest_pypi_version` can deal with the error string (not json parseable), but not with an exception. The exception trickles all the way up to `health#check` which displays the Exception and nothing else from `health#provider#check`

With the try-catch, the pypi-version check fails and prints an error message but the rest of the checks can continue so the relevant output looks like this:

    health#provider#check
    ========================================================================
    ## Clipboard (optional)
     ...
    
    ## Python 2 provider (optional)
      ...
    
    ## Python 3 provider (optional)
      - INFO: Using: g:python3_host_prog = "c:/program files/python37/python.exe"
      - INFO: Executable: c:\program files\python37\python.exe
      - INFO: Python version: 3.7.0
      - INFO: pynvim version: 0.3.0
      - WARNING: Could not contact PyPI to get latest version.
      - ERROR: HTTP request failed: error: python present but not executable
    
    ## Ruby provider (optional)
      ...
    
    ## Node.js provider (optional)
      ...
    

The error string returned from the catch shows up in the last line of the Python 3 section.

**Comment by justinmk** [comment]
I would guess that improving `executable()` on Windows will solve this. https://github.com/neovim/neovim/pull/9516
