### ISSUE TITLE
`StatusLineNC` to have a different color than `StatusLine` 

### ISSUE THREAD

**Issue by Pablo1107** [neovim/neovim#9677]
> You want `StatusLineNC` to have a different color than `StatusLine` per default?

I came across issue #9217 when trying to acomplish what you ask, @bfredl 

This is how my current and non-current buffer status line looks like in Vim 8.1:
![imagen](https://user-images.githubusercontent.com/17091659/53780258-5caec780-3ee2-11e9-95d0-6edb226e9db1.png)

And this is how it looks like Neovim v0.3.4
![imagen](https://user-images.githubusercontent.com/17091659/53780346-c333e580-3ee2-11e9-9a31-920339ede616.png)

How can I make Neovim not using User1, User2, etc highlight groups inverse colors and respect StatusLineNC guibg colors?

**Comment by KillTheMule** [comment]
Maybe related to https://github.com/neovim/neovim/issues/8318?

**Comment by Pablo1107** [comment]
> 
> 
> Maybe related to #8318?

Maybe, I'll try to post a function like you posted there for anyone to try and reproduce.

**Comment by Pablo1107** [comment]
Ok, fiddeling around with a little more, I notice that setting the StatusLine highlight group to guifg=#000000 and guibg=#FFFFFF almost achieve what I expect to happen except for the User2

```
function! StatusLineColors()
        set termguicolors

        hi User1 NONE
        hi User2 NONE
        hi User3 NONE
        hi StatusLineNC NONE

        set laststatus=2
        set statusline=
        set statusline+=%2*\ %l
        set statusline+=\ %*
        set statusline+=%1*\
        set statusline+=%3*\ ৰ\
        set statusline+=%1*\ %f\ %*
        set statusline+=%1*\ %m

        hi User1 guifg=#FFFFFF guibg=#191f26 gui=BOLD
        hi User2 guifg=#000000 guibg=#959ca6
        hi User3 guifg=#00A8C6 guibg=#131920
        hi StatusLine guibg=#000000 guifg=#FFFFFF
        hi StatusLineNC guifg=#00A8C6 guibg=#131920
endfunction
```

Now it looks like this (Neovim top, Vim 8.1 bottom):
![imagen](https://user-images.githubusercontent.com/17091659/53823046-b5687980-3f4f-11e9-9827-edd6099c1b68.png)

The only thing that annoy me a little bit is that white character in the Split, but it's good enough for my use.
