### ISSUE TITLE
filewritable('C:/Program Files') should return 0

### ISSUE THREAD

**Issue by jalvesaq** [neovim/neovim#9683]
- `nvim --version`: v0.4.0-335-g2816bc862
- Vim (version: 8.1) behaves differently? yes
- Operating system/version: Windows 10
- Terminal name/version: Neovim-Qt
- `$TERM`: ""

### Steps to reproduce using `nvim -u NORC`

```
nvim.exe -u NORC -c "echo filewritable('C:/Program Files')"

```

### Actual behaviour

Number `2` in the status bar.

### Expected behaviour

Number `0` in the status bar.

**Comment by justinmk** [comment]
Not sure what to do about this since libuv doesn't mention any Windows-specific caveats regarding `uv_fs_stat`, AFAICT.

Possibly it is related to the need for ACL: https://github.com/neovim/neovim/issues/1200
