### ISSUE TITLE
'set linebreak' breaks listchars with double width characters

### ISSUE THREAD

**Issue by nkakouros** [neovim/neovim#9690]
- `nvim --version`: 
```
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
Compiled by nikos@nikos-laptop

Features: +acl +iconv +tui 
```
- Vim (version: ) behaves differently? No
- Operating system/version: Arch linux latest
- Terminal name/version: Konsole 18.12.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set listchars=tab:
:set list
:set linebreak
```

### Actual behaviour
The third character is never displayed.

### Expected behaviour
I would expect the last character to be displayed.

The characters that I have set are the following ones from the FuraCode Nerd Font from the [nerdfonts](https://github.com/ryanoasis/nerd-fonts) project. Using `ga` on each one of them, I got:

```
<> 63192, Hex f6d8, Octal 173330
<> 62532, Hex f444, Octal 172104
<> 58882, Hex e602, Octal 163002
```

**Comment by justinmk** [comment]
cc @chrisbra

**Comment by chrisbra** [comment]
I'll have a look. Unfortunately, I am very busy with other things and have currently not much time to spend on vim.

**Comment by zeertzjq** [comment]
Is this bug still present? If it is, can you provide a screenshot?

**Comment by nkakouros** [comment]
I can't reproduce this anymore.
