### ISSUE TITLE
Broadcasting to multiple terminals windows

### ISSUE THREAD

**Issue by rednaks** [neovim/neovim#9694]
I'm wondering if there is a way to broadcast what's typed in to other terminals, a very well know feature in many terminals, like terminators, tilix ...

I tried to play with the api to build a plugin, but it seems I can't really modify in a terminal buffer, the doc says it's a normal buffer but I'm wondering how far.

This is the exception I get with (pynvim)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pynvim/api/buffer.py", line 61, in __setitem__
    return self.request('nvim_buf_set_lines', i, i + 1, True, lines)
  File "/usr/local/lib/python2.7/dist-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: Failed to save undo information
```
So two questions:
1. is there a way to broadcast a message across windows ?
2. If not, is this feature planned ?

**Comment by justinmk** [comment]
>  a very well know feature in many terminals, like terminators, tilix ...

What steps do you take in those cases? It is not clear what you're asking for.

> This is the exception I get with (pynvim)

After what steps?

Nvim (and Vim) can show the same buffer by just opening multiple windows. 

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by dm1try** [comment]
sorry if this is kind of off-topic.

the info below from [terminator docs](https://terminator-gtk3.readthedocs.io/en/latest/grouping.html#broadcasting-input-to-multiple-terminals):
> Broadcasting is the act of sending your input to multiple terminals. 
> ...
> This can be an invaluable time-saver when having to do active investigation across multiple machines where you would be repeating the same commands on each of them.

> is there a way to broadcast a message across windows ?

job API could be helpful:
- each terminal buffer has an id
- you can send a message to the terminal buffer using `jobsend`
```viml
" send `ls` command to the current terminal buffer
call jobsend(b:terminal_job_id, "ls\n")
```

btw, some events are not implemented for terminal buffers, see https://github.com/neovim/neovim/issues/5018

**Comment by bfredl** [comment]
If I understand correctly what would be needed is something like `InsertCharPre` but for terminal mode (which gives the exact bytes as part of the event), then the bytes could be repeated to to a list of job handles as mentioned by @dm1try

**Comment by justinmk** [comment]
Re-opened #5018 for `InsertCharPre` since it should be straightforward to implement.

**Comment by dm1try** [comment]
I had thought about using `InsertCharPre` and `TextChangedI`(in the case of shell completion) and then found #5018 later. and then I thought: "if we need only repeat the command but not a keystrokes when we can remap Enter key in the terminal to the action which will copy the command and send to the group of terminals, not sure if this is possible though :) )

**Comment by rednaks** [comment]
Sorry if I was not clear to express the issue and thanks to @dm1try for the helpful comment. I'll take a look at jobsend as well.  it may solve partially the problem, the command will be broadcasted not the input as you type.

Thanks.
