### ISSUE TITLE
Neovim drawing fails when resizing terminal

### ISSUE THREAD

**Issue by christianpoveda** [neovim/neovim#9696]
- `nvim --version`: v0.3.4
- Vim (version: ) behaves differently?
- Operating system/version: Arch Linux
- Terminal name/version: GNOME Terminal 3.30.2 using VTE 0.54.3 +GNUTLS
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`
- Start gnome-terminal without maximizing it
- Run `nvim -u NORC`
- Enter insert mode
- Resize gnome terminal repeatedly

### Actual behaviour
neovim stops drawing correctly: https://imgur.com/a/tB6uZbH

### Expected behaviour

neovim should draw itself correctly

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? I cannot reproduce this with 0.4.x 8ba484ab6 in Terminal.app. 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by christianpoveda** [comment]
Thank you for your answer, I just tested v0.4.0-346-g5f84b1dc4 and it stills happens
