### ISSUE TITLE
Terminal window does not scroll to bottom after opening file through pynvim :tabedit

### ISSUE THREAD

**Issue by JudgeGregg** [neovim/neovim#9697]
- `nvim --version`: nvim version: 0.3.1 Release
- Vim (version: ) behaves differently? N/A
- Operating system/version: Archlinux 4.19
- Terminal name/version: kitty 0.13.2 also tested with urxvt
- `$TERM`: xterm-256color 
 
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
split window `:sp`
open terminal in upper window `:terminal`
run python script `python test_pynvim.py`
```
test_pynvim.py:
```py
from pynvim import attach
import os

listen_addr = os.getenv('NVIM_LISTEN_ADDRESS')
nvim = attach('socket', path=listen_addr)
nvim.command('tabedit ~/.zshrc')
```

### Actual behaviour

File opens in a new tab.
If I go back to the previous tab, the upper terminal window is scrolled to the top in terminal "insert" mode only.
If i switch to normal mode in term window, scrolling is fine. But it gets messed up again whenever I enter terminal "insert" mode.

Scrolling is restored in insert mode if I resize the window, or change the layout to vertical.

 It works fine with "split" and "vsplit" rather than "tabedit".

### Expected behaviour

Term window in which I ran the script should be scrolled to bottom rather than top.

### Demo

![simplescreenrecorder-2019-03-08_11 27 48_edit](https://user-images.githubusercontent.com/1673740/54024340-d0c5c580-4197-11e9-8d62-c6c6f917da38.gif)

**Comment by justinmk** [comment]
This sounds like https://github.com/neovim/neovim/pull/8325 .

Thanks for the report. Can you try the development version? This is mentioned in https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#reporting-problems .

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by JudgeGregg** [comment]
Thank you. It works fine with 0.4.0. Sorry for the noise.
