### ISSUE TITLE
Should vim.api.nvim_call_dict_function be blocking?

### ISSUE THREAD

**Issue by hmgibson23** [neovim/neovim#9698]
This might well be the wrong place to ask this, but I've scoured the docs and there's nothing about it. So feel free to close it this is not the place to put this.

I'm trying to develop a Lua plugin that makes use of `fzf.vim`, but when I call `vim.api.nvim_call_dict_function` and want to wait for user input to get the result, the function call does not seem to be blocking.

I'm new to neovim so maybe it shouldn't be at all?

### Steps to reproduce

```
 local ret = vim.api.nvim_call_dict_function(args, "fzf#run", {args})
 return ret

```

### Actual behaviour

The return statement is executed, then fzf is run and prompts for user input

### Expected behaviour
The call is blocking and waits for the user to make a choice

**Comment by justinmk** [comment]
It doesn't "block" in VimL either:

    :echo fzf#run()

So this the API and Lua isn't relevant. fzf runs in a terminal window in a separate process.
