### ISSUE TITLE
floating window: not cleared when buffer changed

### ISSUE THREAD

**Issue by chemzqm** [neovim/neovim#9699]
- `nvim --version`: NVIM v0.4.0-359-g76cb1da40
- Vim (version: ) behaves differently? N/A
- Operating system/version: MacOS
- Terminal name/version: iTerm2

### Steps to reproduce using `nvim -u NORC`

Create file float.vim:
``` vim
let s:buf = nvim_create_buf(1,1)

let s:win = nvim_open_win(s:buf, v:false, 73, 2, {
      \ 'col': 0,
      \ 'row': 1,
      \ 'relative': 'cursor',
      \})

call nvim_buf_set_lines(s:buf, 0, -1, v:false, ['a', 'b'])
call setwinvar(s:win, '&signcolumn', 'no')
call setwinvar(s:win, '&number', 0)
call setwinvar(s:win, '&relativenumber', 0)
call setwinvar(s:win, '&winhl', 'NormalNC:Pmenu')

function! s:config()
  call nvim_buf_set_lines(s:buf, 0, -1, v:false, ['a', 'b'])
  call nvim_win_config(s:win, 73, 2, {
        \ 'col': 0,
        \ 'row': 1,
        \ 'relative': 'cursor',
        \})
endfunction


augroup test
  autocmd!
  autocmd CursorMoved * call s:config()
augroup end
```

```
nvim -u NORC float.vim
source float.vim
```

then move cusor quickly by hold any arrow key.

### Actual behaviour
<img width="483" alt="screen shot 2019-03-09 at 1 20 54 am" src="https://user-images.githubusercontent.com/251450/54044317-a01e7400-4209-11e9-9c50-af5d76160a4e.png">

**Comment by justinmk** [comment]
moved to 0.5

**Comment by bfredl** [comment]
I cannot reproduce this on master, assumed fixed.
