### ISSUE TITLE
Is there a plan to add functions of vim8.1?

### ISSUE THREAD

**Issue by epheien** [neovim/neovim#9702]
Vim 8.1 introduces the following functions
```
All the term_ functions.

assert_beeps()
assert_equalfile()
assert_report()
balloon_show()
balloon_split()
ch_canread()
getchangelist()
getjumplist()
getwinpos()
pyxeval()
remote_startserver()
setbufline()
test_ignore_error()
test_override()
trim()
win_screenpos()
```

I think add some new viml functions for plugin author is necessary.
And I need getjumplist() to get jumplist efficiently.

**Comment by KillTheMule** [comment]
Sure, we're porting patches from vim, see [here](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim). We usually try to do so in order, as that makes things much easier, but if you have something specific you're interested in, a PR might be accepted.

**Comment by bfredl** [comment]
Some of these has already been merged as well, such as `pyxeval()` and `win_screenpos()`

**Comment by justinmk** [comment]
Also `setbufline()` is redundant with Nvim's own `nvim_buf_set_lines()`, though we will add a compat wrapper for it.

`balloon_xx()` functions will be restored and there's already a ticket for it.
