### ISSUE TITLE
oldtest failure on OpenBSD

### ISSUE THREAD

**Issue by vext01** [neovim/neovim#9704]
Hey guys,

We are updating the neovim package for OpenBSD to 0.3.4. Just one test failure:

```
...
Test results:


From test_cscope.vim:
Found errors in Test_cscopeWithCscopeConnections():
Caught exception in Test_cscopeWithCscopeConnections(): Vim(cscope):E262: error reading cscope connection 0 @ function RunTheTest[35]..Test_cscopeWithCscopeConnections, line 31
Found errors in Test_withoutCscopeConnection():
function RunTheTest[35]..Test_withoutCscopeConnection line 1: Expected 1 but got 0
function RunTheTest[35]..Test_withoutCscopeConnection line 3: Expected 'E567:' but got 'E259: no matches found for cscope query s main of main'
function RunTheTest[35]..Test_withoutCscopeConnection line 5: Pattern 'no cscope connections' does not match ' # pid    database name                       prepend path\n\n 0 26553  /usr/local/pobj/neovim-0.3.4/neovim-0.3.4/src/nvim/testdir/Xcscope.out  <none>'
TEST FAILURE
```

Let me know if I can provide more info.

Cheers

**Comment by vext01** [comment]
I wonder if this is related to this discussion:
http://openbsd-archive.7691.n7.nabble.com/editors-vim-and-job-control-td356041.html

We should also certainly port this patch to neovim:
https://github.com/vim/vim/commit/76ab4fd619

I've already had a user report that he's seen lines like this in his log when using fugative:
```
2019/02/18 21:37:56 ERROR 92592 os_proc_tree_kill:104: getpgid(88152) returned -1
```

I *think* the change would look something like this:
```diff
Index: src/nvim/os/process.c
--- src/nvim/os/process.c.orig
+++ src/nvim/os/process.c
@@ -89,21 +89,16 @@ bool os_proc_tree_kill(int pid, int sig)
 bool os_proc_tree_kill(int pid, int sig)
 {
   assert(sig == SIGTERM || sig == SIGKILL);
-  int pgid = getpgid(pid);
-  if (pgid > 0) {  // Ignore error. Never kill self (pid=0).
-    if (pgid == pid) {
-      ILOG("sending %s to process group: -%d",
-           sig == SIGTERM ? "SIGTERM" : "SIGKILL", pgid);
-      int rv = uv_kill(-pgid, sig);
-      return rv == 0;
-    } else {
-      // Should never happen, because process_spawn() did setsid() in the child.
-      ELOG("pgid %d != pid %d", pgid, pid);
-    }
+  if (pid != 0) {  // Never kill self (pid=0).
+    ILOG("sending %s to PIDs %d and %dp",
+      sig == SIGTERM ? "SIGTERM" : "SIGKILL", pid, -pid);
+
+    int rv1 = uv_kill(pid, sig);
+    int rv2 = uv_kill(-pid, sig);
+    return (rv1 == 0) && (rv2 == 0);
   } else {
-    ELOG("getpgid(%d) returned %d", pid, pgid);
+    return false;
   }
-  return false;
 }
 #endif
```

Right?

**Comment by vext01** [comment]
By the way, the cscope test still fails with the job control change.

**Comment by justinmk** [comment]
> wonder if this is related to this discussion:
http://openbsd-archive.7691.n7.nabble.com/editors-vim-and-job-control-td356041.html
>> but on OpenBSD getpgid(2) will fail and return EPERM (-1) if the process is not part of the same session. 

Good info, thanks! For reference: https://github.com/vim/vim/commit/76ab4fd61901090e6af3451ca6c5ca0fc370571f

> By the way, the cscope test still fails with the job control change.

Because `if_cscope.c` doesn't use the `os/` layer, it is has mostly home-grown junk from Vim (where it also doesn't consistently use Vim's own `mch_` layer).

So your patch is worth adding, but `cs_create_connection` also needs to be revisited. Or remove `if_cscope.c` completely and spend our time on LSP stuff :)

Perhaps `uv_kill(-pid,..)` should go before `uv_kill(pid,..)`, as Vim does so.

**Comment by vext01** [comment]
> cs_create_connection also needs to be revisited.

Well, patching it to use always use setpgid, as sugested in that mailing list post doesn't seem to help. Also that hunk was never committed to upstream vim.

> Or remove if_cscope.c completely and spend our time on LSP stuff :)

I don't use cscope integration with nvim, and I don't even know what LSP is :P

**Comment by vext01** [comment]
Hrm, the test failure is odd:

```
func Test_withoutCscopeConnection()                                                 
  call assert_equal(cscope_connection(), 0)                                         
                                                                                    
  call assert_fails('cscope find s main', 'E567:')                                  
  let a=execute('cscope show')                                                      
  call assert_match('no cscope connections', a)                                     
endfunc
```

The test creates 0 connections, then makes a query expecting to hit E567 in `cs_find()`:
```
  static int cs_find(exarg_T *eap)                                                     
  {                                                                                    
    char *opt, *pat;                                                                   
                                                                                       
    if (cs_check_for_connections() == FALSE) {                                         
      (void)EMSG(_("E567: no cscope connections"));                                    
      return FALSE;                                                                    
    }
    ...
```

But for some reason it instead gets further along to E259 in `cs_find_common()`. This implies that there is a cscope connection, or the counter is wrong.
```

I've ogled the kill code, and tried a negative pid, like before, but alas, no joy.

**Comment by vext01** [comment]
```
function RunTheTest[35]..Test_withoutCscopeConnection line 1: Expected 1 but got 0
```

^ This is actually the first failure, which I think comes from:
```
call assert_equal(cscope_connection(), 0)
```

(The logic in the error msg is back to front, we expected 0, but got one).

But anyway, this tells us that there is a connection (or at least `csinfo_size` != 0) when the test starts. I can't immediately see why.

Do all of the cscope tests share one instantiation of nvim, or does each test get a fresh instance? In the former case, this test would need to run first, or the connections from prior tests would still be around. It looks like connections are only killed when you exit vim.

I tried moving the test first in the file, but that didn't help.

**Comment by justinmk** [comment]
related to this, macOS travis build logs always look like this:

```
$NVIM_LOG_FILE: /Users/travis/build/neovim/neovim/build/.nvimlog
(last 999 lines)
ERROR 2019-03-17T18:39:09.243 60019 os_proc_tree_kill:104: getpgid(60020) returned -1
ERROR 2019-03-17T18:39:09.273 60021 os_proc_tree_kill:104: getpgid(60023) returned -1
ERROR 2019-03-17T18:39:09.298 60024 os_proc_tree_kill:104: getpgid(60025) returned -1
ERROR 2019-03-17T18:39:09.375 60030 os_proc_tree_kill:104: getpgid(60031) returned -1
ERROR 2019-03-17T18:39:12.826 60154 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-03-17T18:39:12.828 60154 libuv_process_spawn:79: uv_spawn failed: no such file or directory
ERROR 2019-03-17T18:39:13.199 60177 os_proc_tree_kill:104: getpgid(60179) returned -1
ERROR 2019-03-17T18:39:25.756 60635 socket_watcher_init:45: Invalid port: 65536
ERROR 2019-03-17T18:40:03.976 61400 libuv_process_spawn:79: uv_spawn failed: no such file or directory
```

**Comment by vext01** [comment]
I'm not sure if it's related, but `getpgid` works differently on OpenBSD (and maybe OSX?) to Linux.

It can return:
```
     [EPERM]            The current process and the process pid are not in the
                        same session.
```

Whereas this can't happen on Linux.

**Comment by vext01** [comment]
[I'm also not sure if this is still an issue for OpenBSD by the way. Either another failure is masking this (#10420) or it no longer fails.

**Comment by blueyed** [comment]
The Vim patch for the removal of `getpgid` is in https://github.com/neovim/neovim/pull/10660.

As for the initial problem / this issue: do those tests work in Vim for you after all?  (`Test_cscopeWithCscopeConnections`)

**Comment by justinmk** [comment]
assuming https://github.com/neovim/neovim/pull/10660 fixes this until otherwise noted.
