### ISSUE TITLE
Tabline is messed up with double width characters

### ISSUE THREAD

**Issue by nkakouros** [neovim/neovim#9711]
- `nvim --version`:
```
NVIM v0.4.0-367-gef5037e7f
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
```
- Vim (version: ) behaves differently? Probably not
- Operating system/version: Arch linux version
- Terminal name/version: konsole 18.12.12
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

I have installed the [vim-airline](https://github.com/vim-airline/vim-airline/) extension and [devicons](https://github.com/ryanoasis/vim-devicons). I have the following in my vimrc:

```
  let g:airline_extensions += ['tabline']
  let g:airline#extensions#tabline#enabled = 1
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {}
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['yml'] = 'ﲇ'
```

### Actual behaviour
![Screenshot_20190310_143713](https://user-images.githubusercontent.com/11805218/54090590-a2014800-436d-11e9-9eb1-cbbde9bb3f5e.png)

The icon for `gibson.yml` displays on the `filetypes.vim` tab.

See also [this](https://github.com/vim-airline/vim-airline/issues/1886).

**Comment by zeertzjq** [comment]
Does this bug still exist?
