### ISSUE TITLE
Floating windows: query window properties ("config")

### ISSUE THREAD

**Issue by TaDaa** [neovim/neovim#9723]
This is more of a question / feature request and apologies if this is already provided.  I am looking for a way to determine which windows are floating windows.

My experience with floating windows so far is that they seem to behave slightly different from normal windows, but regardless show up in the "vim.windows" python object (not sure if this is expected behavior -- to me it would have made more sense to have separated this a bit -- e.g. vim.floating_windows).  This can be problematic for plugins that may currently rely on "vim.windows".  Is there is a win_var that is already set for floating windows or another means to distinguish them?

**Comment by bfredl** [comment]
Note that floating windows are vim windows, and display buffer contents the same way. This is an important point of nvim's UI design. An  "ordinary" window (i e a split window) can be converted to a float and vice versa.

> how up in the "vim.windows" python object (not sure if this is expected behavior -- to me it would have made more sense to have separated this a bit -- e.g. vim.floating_windows). This can be problematic for plugins that may currently rely on "vim.windows".

Python is not really special, it is just an interface of `nvim_list_wins()`. Making floats suddenly disappear from `vim.windows` would be problematic for plugins that expect all windows to be in `vim.windows` .

As you say we need to make float state introspectable in some way, perhaps as part of some existing interface for window layout information.

**Comment by justinmk** [comment]
> Making floats suddenly disappear from vim.windows would be problematic for plugins that expect all windows to be in vim.windows .

It's also just needless entropy. Floating windows _are windows_, they are not a separate special concept.

Windows have "config", so `nvim_win_get_config` could solve this. I guess we should also add info to the VimL `getwininfo()` function.

**Comment by TaDaa** [comment]
Thanks for the comments and adding this -- works great!
