### ISSUE TITLE
Weird folds and jumps with foldmethod=marker

### ISSUE THREAD

**Issue by tterranigma** [neovim/neovim#9727]
- `nvim --version`: 
```
NVIM v0.4.0-370-gc0a29c365
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-nikos/aur-neovim-git/src/neovim-git/build/include
Compiled by nikos@nikos-laptop
```
- Vim (version: ) behaves differently? perhaps
- Operating system/version: ARch linux latest
- Terminal name/version: konsole 18.12.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Create the following file:
```
" vim:foldmethod=marker:foldlevel=0:
" sdfsdf {{{
df
" }}}
```

```
nvim -u NORC path/to/file

```

Then type: `jlo`

### Actual behaviour
The fold closes automatically, instead of staying open and placing the cursor at the new empty line in insert mode.

### Expected behaviour
The fold should not close.

**Comment by justinmk** [comment]
Not sure exactly what you're describing, but vim 8.1.1005 behaves exactly the same way as nvim 0.4.x 7fcf2f926fc6. Make sure to use  `vim -N -u NORC --cmd 'set modeline'` .

> The fold closes automatically, instead of staying open and placing the cursor at the new empty line in insert mode.

For me the fold starts closed, the `jlo` opens the fold and it stays open.

**Comment by tterranigma** [comment]
I am sorry, but `NVIM v0.4.0-381-g7fcf2f926` has that weird behavior. I tried with vim as you describe and it behaves normally. After pressing `o`, in nvim, the fold closes, instead of staying open. I ran nvim with `\nvim -u NORD path/to/file`.
