### ISSUE TITLE
Stable ppa is still at 0.3.1

### ISSUE THREAD

**Issue by diravan** [neovim/neovim#9732]
Installing neovim from the stable ppa (https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable) provides neovim 0.3.1 instead of 0.3.4. Would it be possible to have the new version?

**Comment by justinmk** [comment]
The ppa maintainer is aware and will address this as they are able. 

Alternatively,  the appimage on the  [Releases](https://github.com/neovim/neovim/releases) page is automatically updated and always available.
