### ISSUE TITLE
ex commands line invisible with multiple tabs

### ISSUE THREAD

**Issue by bon-ami** [neovim/neovim#9734]
- `nvim --version`: 0.3.4
- Vim (version: ) behaves differently? 8.x
- Operating system/version: Windows 10
- Terminal name/version: -
- `$TERM`: -

### Steps to reproduce using `nvim -u NORC`.
only reproduced with nvim-qt.exe, not nvim.exe

```
open one tab only. tab row not shown.
maximize neovim now or later.
open a second tab. tab row shows.
maximize neovim previously or now.
":" to enter ex commands mode and enter any characters.
```
### Actual behaviour
the command row out of sight.
![image](https://user-images.githubusercontent.com/19204158/54413289-17836480-4730-11e9-9d50-799c59721a05.png)
### Expected behaviour
the command row visible in full.
![image](https://user-images.githubusercontent.com/19204158/54413356-53b6c500-4730-11e9-9388-0e44c91cddae.png)

**Comment by justinmk** [comment]
cannot reproduce with `nvim -u NORC` on 0.4.x . Could be a https://github.com/equalsraf/neovim-qt issue.
