### ISSUE TITLE
crash on windows10(win64 version has this problem)

### ISSUE THREAD

**Issue by chenjie199234** [neovim/neovim#9738]
The win64 version has this problem,but the win32 version is ok.
I'm sure my system is a x64 version,because i checked it brfore i write these words.
WIN10 version:1809
Neovim version:0.3.4/0.4.0(maybe more not tested)
I'm using neovim on a new and clear windows10 pc.
I download the neovim from the release page.
I double click the neovim-qt.exe.
Then this happened.
I tryed 0.3.4 and 0.4,the behaviour is same.
Here is the screenshot:
![screenshot](https://user-images.githubusercontent.com/29348971/54471172-bfac3280-47ef-11e9-9ab9-dca14c77b62c.png)

**Comment by justinmk** [comment]
What is the exact output of

    nvim -v

**Comment by chenjie199234** [comment]
@justinmk same problem
![screenshot](https://user-images.githubusercontent.com/29348971/54474314-5a236a80-481e-11e9-9b6f-1532476df326.png)

**Comment by justinmk** [comment]
What is the english translation of that Windows error? Or at least paste the text here. Do not post screenshots.

**Comment by chenjie199234** [comment]
@justinmk the translation is:
Application can't start(0xc000007b).Please click the "OK" button to close the application.

**Comment by justinmk** [comment]
What about the other questions I asked?

**Comment by chenjie199234** [comment]
@justinmk 
I download the prebuild from the release page,both win32 and win64
I did the same option "double click the nvim-qt.exe"
win32 version works fine.
win64 version crash.
I have no MSVC env.
![1](https://user-images.githubusercontent.com/29348971/54502147-1aff3180-4964-11e9-8f83-83d2337f20ee.PNG)

**Comment by erw7** [comment]
@chenjie199234 Is `Microsoft Visual C++ 2017 Redistributable (x64)` installed? If it is not installed, please download and install `vc_redist.x64.exe` from [this page](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
