### ISSUE TITLE
CMAKE_INSTALL_PREFIX being ignored

### ISSUE THREAD

**Issue by dammmn** [neovim/neovim#9743]
- `nvim --version`: NVIM v0.4.0-413-g9ef8d0d
- Vim (version: ) behaves differently? Yes, can not recall version which worked earlier.
- Operating system/version: Linux Mint 18.3
- Terminal name/version: xterm (322)
- `$TERM`: xterm-256color

### Steps to reproduce 
run `make CMAKE_INSTALL_PREFIX=$HOME/Work/Tools/neovim/ MAKE_BUILD_TYPE=Release`
then `make install` 

Installation will fail with customized prefix. cmake ignores CMAKE_INSTALL_PREFIX.

### Actual behaviour

```
 make install

error: CMAKE_INSTALL_PREFIX '/home/dan/Work/Tools/neovim/' does not match cached value '/usr/local'
       Run this command, then try again:
         cmake build -DCMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim/
Makefile:169: recipe for target 'checkprefix' failed
make: *** [checkprefix] Error 1
```

Tried:
```
make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim/ CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_MANDIR=/home/dan/Work/Tools/neovim/
```
This failed with:
```
 make install

error: CMAKE_INSTALL_PREFIX '/home/dan/Work/Tools/neovim/' does not match cached value '/usr/local'
       Run this command, then try again:
         cmake build -DCMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim/
Makefile:169: recipe for target 'checkprefix' failed
make: *** [checkprefix] Error 1
```
Also w/o `CMAKE_INSTALL_MANDIR`, this failed with very first error above.

### Expected behaviour

`make install` will install binaries, man pages and scripting into CMAKE_INSTALL_PREFIX directory.

**Comment by mhinz** [comment]
cmake caches variables in `build/CMakeCache.txt`. You probably ran `make` without `CMAKE_INSTALL_PREFIX` first and thus cmake cached the default location of `/usr/local`.

Another note: `CMAKE_INSTALL_PREFIX` is a cmake thing and only works with `make` because our `Makefile` explicitly passes it to cmake. That won't work for `CMAKE_INSTALL_MANDIR`, though.

So, the correct way to do what you had in mind:

```
$ rm -r build
$ make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_MANDIR=/home/dan/Work/Tools/neovim"
```

If this works for you, we can probably improve that error message.

**Comment by justinmk** [comment]
How about trying the command given by the error message...?

```
Run this command, then try again:
         cmake build -DCMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim/
```

**Comment by dammmn** [comment]
> How about trying the command given by the error message...?
> 
> ```
> Run this command, then try again:
>          cmake build -DCMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim/
> ```

This ended up with the same error message as I reported at the very beginning.

**Comment by dammmn** [comment]
> cmake caches variables in `build/CMakeCache.txt`. You probably ran `make` without `CMAKE_INSTALL_PREFIX` first and thus cmake cached the default location of `/usr/local`.
> 
> Another note: `CMAKE_INSTALL_PREFIX` is a cmake thing and only works with `make` because our `Makefile` explicitly passes it to cmake. That won't work for `CMAKE_INSTALL_MANDIR`, though.
> 
> So, the correct way to do what you had in mind:
> 
> ```
> $ rm -r build
> $ make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_MANDIR=/home/dan/Work/Tools/neovim"
> ```
> 
> Alternatively, if you intend to build more often from source, you can put these things in a `local.mk` in the root directory:
> 
> ```
> CMAKE_INSTALL_PREFIX = ${HOME}/Work/Tools/neovim
> CMAKE_EXTRA_FLAGS = -DCMAKE_INSTALL_MANDIR=${HOME}/Work/Tools/neovim
> ```
> 
> Afterwards, only `make && make install` is needed.
> 
> If this works for you, we can probably improve that error message.

Thank you for elaborated reply. Unfortunately none of the steps you described lead to the successful `make install`. After modifying variables as per your recommendation I ended up with following:
```
make install
ninja  -C .deps
ninja: Entering directory `.deps'
[2/2] cd /home/dan/Work/Sources/neovim/.deps && /usr/bin/cmake -E touch .third-party
ninja  -C build
ninja: Entering directory `build'
ninja: no work to do.
ninja  -C build install
ninja: Entering directory `build'
[0/1] Install the project...
-- Install configuration: "Debug"
-- Installing: /home/dan/Work/Tools/neovim/man1/nvim.1
-- Installing: /usr/local/bin/nvim
CMake Error at src/nvim/cmake_install.cmake:78 (file):
  file INSTALL cannot copy file
  "/home/dan/Work/Sources/neovim/build/bin/nvim" to "/usr/local/bin/nvim".
Call Stack (most recent call first):
  cmake_install.cmake:85 (include)
  


FAILED: CMakeFiles/install.util 
cd /home/dan/Work/Sources/neovim/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
Makefile:143: recipe for target 'install' failed
make: *** [install] Error 1
```
So judging based on very quick closure from @justinmk it looks like there are more pressing issues in this project so I am going back to my cave and learn a bit about `cmake` and will try to bring a fix for this as I am not the only one who is experiencing this.

Thank you again for your help @mhinz !

**Comment by mhinz** [comment]
What's the output of:

```
$ rm -rf build
$ make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim
$ grep ^CMAKE_INSTALL_PREFIX build/CMakeCache.txt
```

**Comment by dammmn** [comment]
> What's the output of:
> 
> ```
> $ rm -rf build
> $ make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim
> $ grep ^CMAKE_INSTALL_PREFIX build/CMakeCache.txt
> ```

Here is the requested output. 
```
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  grep ^CMAKE_INSTALL_PREFIX build/CMakeCache.txt
CMAKE_INSTALL_PREFIX:PATH=/usr/local
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  

```

**Comment by justinmk** [comment]
Have you actually done `rm -rf build' ?

**Comment by dammmn** [comment]
> Have you actually done `rm -rf build' ?

yes, I have.

```
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  pwd
/home/dan/Work/Sources/neovim
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  ls -ld build/
drwxrwxr-x 12 dan dan 4096 Mar 17 15:15 build/
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  rm -vrf build/                                                                                                                                                                                           
removed 'build/CPackSourceConfig.cmake'
removed directory 'build/lib'
removed 'build/.ran-cmake'
removed directory 'build/errors/src'
....
removed 'build/runtime/syntax/vim/generated.vim'
removed directory 'build/runtime/syntax/vim'
removed directory 'build/runtime/syntax'
removed 'build/runtime/cmake_install.cmake'
removed directory 'build/runtime'
removed directory 'build/'
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  pwd
/home/dan/Work/Sources/neovim
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  ls -ld build/
ls: cannot access 'build/': No such file or directory
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $   dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  make CMAKE_INSTALL_PREFIX=/home/dan/Work/Tools/neovim
mkdir -p .deps
cd .deps && \
        cmake -G 'Ninja'   \
         /data/home/dan/Work/Sources/neovim/third-party
-- Found GNU Make at /usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dan/Work/Sources/neovim/.deps
mkdir -p build
touch build/.ran-third-party-cmake
ninja  -C .deps
ninja: Entering directory `.deps'
[2/2] cd /home/dan/Work/Sources/neovim/.deps && /usr/bin/cmake -E touch .third-party
cd build && cmake -G 'Ninja' -DCMAKE_BUILD_TYPE=Debug  /data/home/dan/Work/Sources/neovim
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
....
-- Performing Test HAVE_BE64TOH_MACROS
-- Performing Test HAVE_BE64TOH_MACROS - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dan/Work/Sources/neovim/build
touch build/.ran-cmake
ninja  -C build
ninja: Entering directory `build'
[301/301] Generating doc/tags
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  grep ^CMAKE_INSTALL_PREFIX build/CMakeCache.txt
CMAKE_INSTALL_PREFIX:PATH=/usr/local
 dan  desktop-pc  home  dan  Work  Sources  neovim  master  $  

```

**Comment by mhinz** [comment]
I can reproduce it.

@justinmk Passing it directly via `CMAKE_INSTALL_PREFIX` isn't working anymore. Probably since the `checkprefix` changes.

**Comment by justinmk** [comment]
I can reproduce this on macOS but not ubuntu. It's easy to see what will happen by noticing this line at the start of the build:

    -- CMAKE_INSTALL_PREFIX=/usr/local

**Comment by justinmk** [comment]
@dammmn what does `make --version` say?

**Comment by dammmn** [comment]
> @dammmn what does `make --version` say?

```
 make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by justinmk** [comment]
@dammmn can you try https://github.com/neovim/neovim/pull/9748

**Comment by dammmn** [comment]
> @dammmn can you try #9748

Bingo ! No error.

```
nvim -v
NVIM v0.4.0-419-gf3e7815
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/dan/Work/Sources/neovim/build/config -I/home/dan/Work/Sources/neovim/src -I/home/dan/Work/Sources/neovim/.deps/usr/include -I/usr/include -I/home/dan/Work/Sources/neovim/build/src/nvim/auto -I/home/dan/Work/Sources/neovim/build/include
Compiled by dan@desktop-pc

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dan/Work/Tools/neovim/share/nvim"

Run :checkhealth for more info
```

**Comment by tkkcc** [comment]
Just hard code the `CMAKE_FLAGS` in Makefile
```
CMAKE_FLAGS := -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vis/tongchaoyu/bin/nvim -DCMAKE_INSTALL_MANDIR=/home/vis/tongchaoyu/bin/nvim
```
