### ISSUE TITLE
beginning-of-a-line bug in Konsole

### ISSUE THREAD

**Issue by jacob-emery** [neovim/neovim#9756]
- `nvim --version`: 0.3.4
- Vim (version: ) behaves differently? Vim behaves differently
- Operating system/version: Arch Linux, all package are up to date
- Terminal name/version: Konsole (default)
- `$TERM`: xterm-256color

Running Neovim from Konsole on both sessions Plasma and Plasma Wayland (I guess on each DE) presents the very annoying and confusing below described bug.
This bug does not happen in GNOME Terminal.
This bug also does not happen if running Vim in Konsole (also because Vim's editing is different than Neovim's one).

### Actual behaviour
The "cursor |" sign appears if pressed the I/Insert button at the beginning of the line (it can be any line) and while moving the "cursor", a "copy" of the sign remains at the beginning of the line.
If I/Insert is pressed at position 2+ there is no issue.
It goes away after pressing ESC.
To better understand, I also recorded a video featuring this issue.
https://drive.google.com/file/d/1Dk3sWjk3Uyl55c_FpK2_q_nxjGs6V0JX/view?usp=sharing

### Expected behaviour
This sign should not be there.

Thank you in advance for your support.

**Comment by justinmk** [comment]
If the cursor is "ghosting" that your terminal's problem. Terminal applications such as Nvim have zero control over that.
