### ISSUE TITLE
possible to relieve the dilemma between tabs and buffers?

### ISSUE THREAD

**Issue by ryenus** [neovim/neovim#9759]
The dilemma between tabs and buffers in vim has been a long time itch, even considered more of a feature over a bug, but it indeed cause confusions and inconveniences, especially for new uses. Maybe there's a chance to scratch it?

**Comment by bfredl** [comment]
What change, concretely, is it that you have in mind? Better intro docs? or some deeper change?

**Comment by mhinz** [comment]
He probably asks for tab-local buffer lists, but I wouldn't want that until Vim does it as well. This would probably break the work flow of a lot of users who are used to the current behaviour.

**Comment by justinmk** [comment]
This isn't actionable. And there is no dilemma.  Tabs are _views_. Why would you want to remove that feature?

If you really want something like this, it can be addressed in a plugin. For example some Neovim UIs like https://github.com/onivim/oni have a "tab == buffer" mode.
