### ISSUE TITLE
Vim patch 8.1.0619: make "echom dict" work

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#9762]
I've just tried to port https://github.com/vim/vim/commit/461a7fcfce3cd6414f990037e6468af3b5ccf119, but it was not clear to me how/if `f_string` can be called from non-function functions (without `FunPtr fptr` in its arguments), and there appear to be differences between using `char` / `char_u` in Vim/Neovim in this regard in general?

Short story short, I've not managed to do it myself, but would like to have it ported.. :)

**Comment by justinmk** [comment]
the `tv_stringify` function from that patch isn't needed, Nvim already has great facilities for marshalling VimL values to/from string, msgpack, etc.

In this case the function to use would be `encode_tv2string`. So it isn't necessary to call `f_string` (which is a hack anyway).

**Comment by justinmk** [comment]
I think we need `tv_get_string_buf_chk` variant that doesn't "check".

**Comment by justinmk** [comment]
3c12ee333a51
