### ISSUE TITLE
My neovim broke when I updated pip3's neovim and now there's no docs on that??

### ISSUE THREAD

**Issue by chris-fran** [neovim/neovim#9764]
Setting up neovim always carries some pain because the docs seem to be scattered away. I remember when I set up about 6 months ago or more that at some point I had to install `pip3 install --user --upgrade neovim` so that my plugins work.

Today I ran `:checkhealth`, it said my python support was outdate so I ran the command above. Everything broke. Ran `:PlugInstall!` to force a recompile of things that use python, nothing.

Funny thing, I can't find any docs on command that anymore. The only docs I have are the ones on my own repo and maybe some outdated articles. I do see, however, something called `pynvim`. Is this a replacement? if so, why is it never mentioned?

I tried running this with no luck. 
```bash
pip3 install --user --upgrade pynvim
```

Here's some info. Not sure what's missing
```bash
$ which python
/usr/bin/python

$ which python3
/usr/local/bin/python3

$ nvim
UltiSnips requires py >= 2.7 or py3
YouCompleteMe unavailable: unable to load Python.
Press ENTER or type command to continue
```

**Comment by KillTheMule** [comment]
Always mention your neovim version :) Although it might not matter in this case. See https://github.com/neovim/neovim/wiki/Following-HEAD#20181118.

**Comment by mhinz** [comment]
`:checkhealth` _should_ warn about this issue.

If upgrading (as described in the link above) doesn't work, what is actual output of `:checkhealth provider` for Python?

**Comment by lorenzo** [comment]
I’m also experiencing this problemz it complains that no neovim module could be found.

**Comment by justinmk** [comment]
Please mention the exact Nvim `:version` , as requested by the issue template.

**Comment by lorenzo** [comment]
```:version
NVIM v0.3.2-590-g044cd24
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pe
dantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_
FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/u
sr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-1284.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by justinmk** [comment]
`:checkhealth` in 0.3.4 has better advice and detection for this. Can't do anything about 0.3.2.

We will also add a note to `:help provider-python`, but again, that will require upgrading to the latest stable version.

**Comment by justinmk** [comment]
- This is now mentioned in `:help provider-python`: https://github.com/neovim/neovim/commit/eeb19a346a6afac2672b47f5d15e4ea0cf7737aa
- Also committed to the `release-0.3` branch, so this will be included in the next stable release.
