### ISSUE TITLE
chechheath: "node -v"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ShuguangSun** [neovim/neovim#9766]
- `nvim --version`:
- Vim (version: ) behaves differently?
- Operating system/version: Windows 10
- Terminal name/version: NVIM v0.4.0-430-g8698830cb
- `$TERM`:

### Steps to reproduce 

```
:checkhealth

```

### Actual behaviour
It reports:

> ## Node.js provider (optional)
>   - ERROR: Command error (job=9, exit code 1): `node -v` (in 'path')
>     Output: '"node -v"' is not recognized as an internal or external command,
> operable program or batch file.
>     Stderr: '"node -v"' is not recognized as an internal or external command,
> operable program or batch file.
>   - INFO: Node.js: '"node -v"' is not recognized as an internal or external command,
> operable program or batch file.
> 

### Expected behaviour

node is installed and in the seach PATH. 
My confusion is whether it takes "node -v" as a command to be exe-finded?

**Comment by erw7** [comment]
@ShuguangSun Do the following steps reproduce the problem?

```
nvim -u NORC
:checkhealth
```

I think one of the settings such as `shcf`, `shq`, `sxe`, `sxq` is probably wrong.

**Comment by ShuguangSun** [comment]
It is my fault. I try to start nvim-qt from Emacs and then got the issue and some others. And If start nvim-qt with double click, then there is no issue.

Sorry for the mis-findings.
