### ISSUE TITLE
coq-au-vim support

### ISSUE THREAD

**Issue by adimanea** [neovim/neovim#9770]
- `nvim --version`: 0.3.4
- Vim (version: 8.1) behaves differently? Yes.
- Operating system/version: Manjaro Illyria (18.0.3-stable)
- Terminal name/version: `st`.
- `$TERM`: `st-256color`.

I tried using [`coq-au-vim`](https://framagit.org/manu/coq-au-vim), including [`jvoorhis/coq.vim`](https://github.com/jvoorhis/coq.vim/), via the native `pack/mypacks/start` install.

I get the errors below in neovim, but vim works as intended.
```
Error detected while processing function coqtop#Start[1]..36[21]..5:
line    2:
E121: Undefined variable: v:none
E116: Invalid arguments for function 6
Error detected while processing function coqtop#Start[1]..36[22]..11[2]..8:
line    3:
E716: Key not present in Dictionary: return_queue, [a:command, a:000, a:callback, a:dict])
E116: Invalid arguments for function add
line    4:
E716: Key not present in Dictionary: channel, xml)
E116: Invalid arguments for function ch_sendraw
Press ENTER or type command to continue
```

I'm not sure whether this is neovim's fault or Coq's and I am not very experienced in vim either. But the fact that vim works and neovim doesn't, I'm thinking this is neovim related. 

I didn't make any supplementary modifications or configurations, I just `git clone`d the packages in `pack/mypacks/start`. Coq, CoqIDE, and `coqtop` work OK as well.

I am loading a basic Coq example, namely:
```coq
Example and_example: 3 + 4 = 7 /\ 2 * 2 = 4.
Proof.
	split.
	- reflexivity.
	- reflexivity.
Qed.
```

**Comment by justinmk** [comment]
https://framagit.org/manu/coq-au-vim uses `v:none` for no good reason. It should use `v:null` instead.

`v:none` was intentionally not included in Nvim because it's a misfeature.

**Comment by mhinz** [comment]
Also note that Nvim and Vim use different job implementations: `E116: Invalid arguments for function ch_sendraw`

`ch_sendraw()` is a Vim-specific function, so that plugin doesn't seem to support Nvim in the first place.

**Comment by adimanea** [comment]
> Also note that Nvim and Vim use different job implementations: `E116: Invalid arguments for function ch_sendraw`
> 
> `ch_sendraw()` is a Vim-specific function, so that plugin doesn't seem to support Nvim in the first place.

Okay, I understand. At least now I know who's responsible, thank you. :) I'll move my request to coq-au-vim then.
