### ISSUE TITLE
:drop on unopen file adds extra jump to jumplist

### ISSUE THREAD

**Issue by abdelhakeem** [neovim/neovim#9775]
- `nvim --version`:
> NVIM v0.3.4
> Build type: Release
> LuaJIT 2.0.5
> Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
> Compiled by builduser
> 
> Features: +acl +iconv +jemalloc +tui 
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info

- Operating system/version:
> 4.20.11-arch2-1-ARCH <span>#</span>1 SMP PREEMPT Fri Feb 22 13:09:33 UTC 2019

- Terminal name/version:
> <span>#</span> GNOME Terminal 3.30.2 using VTE 0.54.3 +GNUTLS
- `$TERM`: xterm-256color

### Issue

When a file is not open in a window and is to be edited in the current window, `:drop` adds an extra jump, which is a duplicate of the current position, at the tail of the jumplist.
This makes it necessary to press `<CTRL-O>` twice to go back to the previous cursor position.

### Steps to reproduce using `nvim -u NORC`

Given the following two files:
```
#file1
file1 contents

#file2
file2 contents
```

The following does not work as expected:

```
nvim -u NORC file1
:drop file2
<CTRL-O>
```

### Actual behaviour

```
nvim -u NORC file1
:clearjumps
:drop file2
:jumps

 jump line  col file/text
   2     1    0 file1
   1     1    0 file2 contents
>
```

### Expected behaviour

```
nvim -u NORC file1
:clearjumps
:drop file2
:jumps

 jump line  col file/text
   1     1    0 file1
>
```

**Comment by justinmk** [comment]
> This makes it necessary to press `<CTRL-O>` twice to go back to the previous cursor position

This is fairly common in Vim. Would be nice to fix it for more than just `:drop`.

**Comment by abdelhakeem** [comment]
> This is fairly common in Vim. Would be nice to fix it for more than just :drop.

Can you point me to any more general related issues? I'd like to see if I can tackle this one.

> Although, in your case it looks like the column differs between the jumps, so that's not exactly a "duplicate" jump.

Actually it's the same column, no further jumping movements are needed after `:drop` to reproduce this behavior. Both jumps refer to the first line and the first column.

**Comment by justinmk** [comment]
> Can you point me to any more general related issues? I'd like to see if I can tackle this one.

I've been too lazy to track down minimal steps to reproduce the issue. But anyways, I think it's reasonable to never add duplicate adjacent jumps. So just preventing that should prevent all cases.

Based on recent Vim discussions about duplicate _undo_ steps, I wouldn't be surprised if duplicates _jump_ behavior is considered "the way Vi does it, therefore Vim must do it". But I think Neovim doesn't need to maintain such "compatibility": it won't break scripts (because (1) the behavior is nonsensical and undefined, and (2) Vim sometimes changes the behavior anyways).

**Comment by kiryph** [comment]
Following question on vi.stackexchange.com might be related to this:

https://vi.stackexchange.com/questions/19038/pressing-ctrl-o-twice-is-required-to-return-to-previous-entry-in-jumplist

**Comment by abdelhakeem** [comment]
> Following question on vi.stackexchange.com might be related to this:
> 
> https://vi.stackexchange.com/questions/19038/pressing-ctrl-o-twice-is-required-to-return-to-previous-entry-in-jumplist

Thanks a lot for your input. Just confirmed the issue mentioned in the link.
@justinmk This [one](https://vi.stackexchange.com/questions/19038/pressing-ctrl-o-twice-is-required-to-return-to-previous-entry-in-jumplist) will most probably require the fix you talked about
