### ISSUE TITLE
inccommand: redraw from timer clears preview window and substitutions

### ISSUE THREAD

**Issue by gelguy** [neovim/neovim#9777]
- `nvim --version`: `v0.4.0-401-g5c836d2ef`
- Operating system/version: `Windows 10 WSL`
- Terminal name/version: `wsltty`
- `$TERM`: `xterm`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

set inccommand=split

autocmd CmdlineChanged * call timer_start(1000, {-> execute('redraw')})
```

Open a buffer with text and type `%s/.`
### Actual behaviour
Preview window and substitutions disappear after a while.

### Expected behaviour
Preview window and substitutions do not disappear.

Also happens for `inccommand=nosplit`, with `redrawstatus` and when `redraw` is called from async actions.

Use case: Async action finishes and calls `redraw`/`redrawstatus` when `inccommand` preview is active.

**Comment by justinmk** [comment]
Forcing a redraw from a timer is undefined and makes no sense.

**Comment by justinmk** [comment]
I'm not sure why we even allow timers to fire during 'inccommand'. I think that should be prevented.

**Comment by bfredl** [comment]
For the "redraw" part of the issue, an alternative could be to keep the preview window around longer. Right now we split, redraw, and close the window immediately on every valid keypress, so we rely on stale screen state to be kept to be displayed to the user. The alternative would be to not close the preview window until the user either makes the cmdline invalid (not a substitution) or exiting cmdline mode. 

`nosplit` mode would be more tricky though, one option could be to disable redraw for that one window for the same duration, unless the window was moved/resized or something. Though "eventually" maybe the preview can be re-implemented as virtual text, at least for changes that doesn't change line splits.

**Comment by justinmk** [comment]
> an alternative could be to keep the preview window around longer. 

+1, unfinished todo from https://github.com/neovim/neovim/pull/5561 .
