### ISSUE TITLE
:help terminal" says 'bufhidden' defaults to "hide"

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#9778]
- `nvim --version`: NVIM v0.4.0-dev
- Operating system/version: Ubuntu 18.04
- Terminal name/version: st terminal commit head 21367a040f05
- `$TERM`: st-256color

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC

:terminal
:set bufhidden?

```

### Actual behaviour

The output of `:set bufhidden?` is `bufhidden=`

### Expected behaviour

`:h terminal` says :
```
Terminal buffers behave like normal buffers, except:
- 'bufhidden' defaults to "hide".
```

So, there seems to be a alteration in documentation or something a little ambiguous or obscure for common folk to understand.

**Comment by justinmk** [comment]
Thanks for the report. https://github.com/neovim/neovim/pull/6280 will fix this.
