### ISSUE TITLE
TUI: Redraw bug with multiple windows and special characters

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#9795]
- `nvim --version`: NVIM v0.4.0-457-g281c011d4
- Vim (version: ) behaves differently? Yes, Vim built from the master branch doesn't have this issue.
- Operating system/version: Linux 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
- Terminal name/version: kitty 0.13.1 
- `$TERM`: xterm-kitty

### Steps to reproduce using `nvim -u NORC`

Copy the following string to `/tmp/file.txt`:
```
­؀؁؂؃؄؅؜۝܏᠎​‌‍‎‏‪‫‬‭‮⁠⁡⁢⁣⁤⁦⁧⁨⁩⁪⁫⁬⁭⁮⁯﻿￹￺￻𑂽𛲠𛲡𛲢𛲣𝅳𝅴𝅵𝅶𝅷𝅸𝅹𝅺󠀁󠀠󠀡󠀢󠀣󠀤󠀥󠀦󠀧󠀨󠀩󠀪󠀫󠀬󠀭󠀮󠀯󠀰󠀱󠀲󠀳󠀴󠀵󠀶󠀷󠀸󠀹󠀺󠀻󠀼󠀽󠀾󠀿󠁀󠁁󠁂󠁃󠁄󠁅󠁆󠁇󠁈󠁉󠁊󠁋󠁌󠁍󠁎󠁏󠁐󠁑󠁒󠁓󠁔󠁕󠁖󠁗󠁘󠁙󠁚󠁛󠁜󠁝󠁞󠁟󠁠󠁡󠁢󠁣󠁤󠁥󠁦󠁧󠁨󠁩󠁪󠁫󠁬󠁭󠁮󠁯󠁰󠁱󠁲󠁳󠁴󠁵󠁶󠁷󠁸󠁹󠁺󠁻󠁼󠁽󠁾󠁿
```

```
nvim -u NORC
:sp /tmp/file.txt
<C-l>
```

### Actual behaviour

The statusline is redrawn one line too high. Moving the cursor to the bottom window redraws the statusline at the right place, but the previous statusline doesn't disappear.

**Comment by justinmk** [comment]
Is this really TUI-only?

**Comment by glacambre** [comment]
I believe so, I'm not experiencing this issue with my own [gui](https://github.com/glacambre/firenvim).

**Comment by bfredl** [comment]
Can reproduce with pangoterm

**Comment by glacambre** [comment]
This is fixed on master as Neovim now prints the hex representation of these characters instead of the characters themselves.
