### ISSUE TITLE
Ignore patch with fix for old code?

### ISSUE THREAD

**Issue by LTKills** [neovim/neovim#9801]
I'm working to port [vim-patch:8.0.0705](https://github.com/vim/vim/releases/tag/v8.0.0705):

> **Problem:** Crash when there is an error in a timer callback. (Aron Griffis, Ozaki Kiichi)
> **Solution:** Check did_throw before discarding an exception.  NULLify current_exception when no longer valid.

I'm not sure whether this should be ported or not. One of the functions it modifies (`check_due_timer` from file `src/nvim/ex_cmds2.c`) no longer exists.

**Comment by mhinz** [comment]
The change from `ex_cmds2.c` can be ignored, since our implementation of timers is different.

The safety checks from `ex_eval.c` are fine, though.
