### ISSUE TITLE
The shared library shouldn't log

### ISSUE THREAD

**Issue by aktau** [neovim/neovim#981]
I've been trying to create tests for #978 and I have some logging in there. Logging from within the shared library seems to be difficult to get right. At the moment I'm doing this:

```lua
  setup(function()
    -- the logging functions are complain if I don't do this
    shell.allocate_generic_buffers() -- initialize NameBuff
    shell.init_homedir()

    shell.event_init()

    -- os_system() can't work when the p_sh and p_shcf variables are unset
    shell.p_sh = to_cstr('/bin/bash')
    shell.p_shcf = to_cstr('-c')
  end)
```

Yet I still get things like:

```
2014/07/22 21:01:14 [error @ open_log_file:84] 30038 - Couldn't open USR_LOG_FILE, logging to stderr! This may be caused by attempting to LOG() before initialization functions are called (e.g. init_homedir()).
```

I think logging should actually just be disabled for the shared library, as this is getting very finnicky to get right. What do you guys say and how do you see it happen?

Ping @jszakmeister and @philix

**Comment by justinmk** [comment]
Covered by https://github.com/neovim/neovim/issues/2913
