### ISSUE TITLE
Unexpected CursorMoved event when entering a buffer

### ISSUE THREAD

**Issue by ipod825** [neovim/neovim#9838]
- `nvim --version`: NVIM v0.4.0-495-gf793c578b
- Vim (version: )  VIM - Vi IMproved 8.1 (behaves differently)
- Operating system/version: 5.0.5-arch1-1-ARCH
- Terminal name/version: GNOME Terminal 3.32.0 using VTE 0.56.0 +GNUTLS
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:new
:autocmd CursorMoved * echom "cursor moved"
:q
```

### Actual behaviour
nvim echos "cursor moved" after entering the first buffer (after ":q").

### Expected behaviour
Surprisingly, if ran on vim, vim echos "cursor moved" after `:autocmd CursorMoved * echom "cursor moved"`. However, more importantly, it does not echo "cursor moved" after entering the first buffer (after ":q"), which is more reasonable.

**Comment by mhinz** [comment]
IMHO, there are multiple approaches that all make sense:

- _Never_ trigger `CursorMoved` on entering a window. When we imagine that every window has its own cursor, then merely switching between windows doesn't move any cursor.
- _Always_ trigger `CursorMoved` on entering a window (current default). Treat the cursor like Vim does. That means, there's only one global cursor, so even when we just switch windows, the cursor needs to move.
- Do _not_ trigger `CursorMoved` for the first window but all the others. A lot of other events are _not_ triggered for the first window either, e.g. `WinEnter`, `BufEnter`, etc.

That said, Vim _does_ trigger `CursorMoved` for the first window as well:

    vim --cmd 'au CursorMoved * echomsg "foo"'

**Comment by bfredl** [comment]
Vim will also trigger `CursorMoved` in the situation in the issue description if the cursor position is not exactly the same `(1,1)`. Try insert a single char `ix<esc>` before `:q`.

**Comment by mhinz** [comment]
We made this change to _always_ trigger `CursorMoved` on entering a window on purpose. Vim's behaviour of not triggering it only because the cursor location is the same between both windows, even when they display two different buffers, makes no sense at all.
