### ISSUE TITLE
escape key stopped working in insert mode (nightly build)

### ISSUE THREAD

**Issue by bc2009** [neovim/neovim#9839]
- `nvim --version`: NVIM v0.4.0-517-g8eaa45207 (as well as the nightly build in yesterday)
- Vim (version: ) behaves differently? Yes. ESC key looks to stop working in insert mode, where ESC cannot go back to normal mode.
- Operating system/version: Ubuntu 16.04 LTS, Red Hat Enterprise Linux Server release 7.2, and MacOS Mojave 10.14.3 (happened on all these)
- Terminal name/version: iterm2 / xterm
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
In insert mode, (i.e. press "i" to enter insert mode after startup), then press ESC cannot go back to normal mode.

### Expected behaviour
Pressing ESC expects to enter normal mode like before.

**Comment by justinmk** [comment]
cannot reproduce with NVIM v0.4.0-501 35362495c in Terminal.app.

**Comment by bc2009** [comment]
This looks to start to happen from this week's nightly build. I had some v0.40-50x before, which was fine.

**Comment by justinmk** [comment]
@bc2009 when this happens, what does this show:

    :set paste?

I noticed this happened when 'paste' got stuck. This could be a duplicate of https://github.com/neovim/neovim/issues/7994 . Even though the particular symptom only started recently, the root cause is still the same.

**Comment by bc2009** [comment]
@justinmk I didn't try what you said, but it looks like it is fixed for this week's nightly builds. Now escape key works again on all my OS envs.

BTW, ":set paste?" shows "nopaste" now.

**Comment by gmankab** [comment]
same problem on 0.9.5
