### ISSUE TITLE
Floating window minimal width

### ISSUE THREAD

**Issue by tbo** [neovim/neovim#9846]
I've been playing around with floating windows and noticed, that their minimal width is limited to 2. This behavior is in line with the documentation, but I could not find any reason why one column wide floating windows cannot be supported. To find out more, I simply changed the related code in `window.c` from:

``` 
wp->w_width = MAX(fconfig.width, 2);
```
to: 
``` 
wp->w_width = MAX(fconfig.width, 1);
```
This seems to work at least for my use case. Is there any technical reason, that prohibits a minimal width of 1?

**Comment by bfredl** [comment]
This was just based on my experience that a 2-width window works somewhat sanely (a 3-col line takes 2 screen rows) while a 1-width window doesn't (a 2-col line takes ∞ screen rows). Though it might depend on options. What is the usecase?

**Comment by tbo** [comment]
I'm writing an [easymotion](https://github.com/easymotion/vim-easymotion) clone, that doesn't rely on changing the buffer content. The alternative would have been to conceal the jump targets like [vim-sneak's
](https://github.com/justinmk/vim-sneak)  label mode does, but this approach is limited to a single character. @justinmk implemented a workaround for this, but I rather avoid the additional complexity. The floating windows solve this problem very elegantly:
<img width="459" alt="Screenshot 2019-04-04 at 22 18 09" src="https://user-images.githubusercontent.com/264745/55589497-433eac80-5728-11e9-8bb6-5314dc95b647.png">
As you can see I have no direct interaction with the floating windows. They are not even focusable.

**Comment by justinmk** [comment]
@tbo That's a good use of floating windows IMO, because during "label mode" there is no risk of the user accidentally switching to any of the temporary windows.

**Comment by bfredl** [comment]
Let's change this then. You can get the broken behavior in a split window anyway.

**Comment by bfredl** [comment]
It is now allowed on master.
