### ISSUE TITLE
neovim netrw causes screen flickering under sway/wayland

### ISSUE THREAD

**Issue by puresick** [neovim/neovim#9847]
- `nvim --version`: v0.3.4
- Vim (version: 8.1.1073) behaves differently? (in this case, it behaves correctly)
- Operating system/version: Arch Linux with Linux 5.0.1-arch1-1-ARCH kernel
- Terminal name/version: alacritty v0.2.9 & termite v14
- `$TERM`: alacritty: xterm-256color, termite: xterm-termite
- Shell: fish 3.0.2
- Window Manager: Sway v1.0

### Steps to reproduce using `nvim -u NORC`

```
1. nvim -u NORC
2. :ex .
```

### Actual behaviour
Screen flickers heavily.

### Expected behaviour
Screen will not flicker.

Trying the same with a different shell (bash and zsh) will not produce any flickering, but netrw wont show up - instead an empty nvim window is displayed.

I attached some gif showing the problem visually:

![flicker](https://user-images.githubusercontent.com/2714266/55632746-34eda080-57bb-11e9-98f5-6722e06a83d5.gif)

**Comment by justinmk** [comment]
This looks the same as https://github.com/neovim/neovim/issues/9806 , so I reopened that and am thinking about what to do.
