### ISSUE TITLE
startup: -es/-ES  (silent/batch mode): Exit without reading the input from TTY

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#9848]
- `nvim --version`: NVIM v0.4.0-529-gfb555c689
- Vim (version: ) behaves differently? Yes(8.0.1207)
- Operating system/version: CentOS Linux 7 (Core)
- Terminal name/version: tmux/2.6
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -es
```

### Actual behaviour
Exit normally.

### Expected behaviour
Wait for the input of the command from TTY.

**Comment by justinmk** [comment]
Can you give an example of a use-case that this breaks?
This is a feature, so that `-c q` is not needed. Nvim processes input and then exits. 

If you want "interactive" behavior (i.e. wait on TTY input) don't specify `s`:

     nvim -u NORC -e

**Comment by erw7** [comment]
I noticed this while checking the startup process for #9829. I created an issue because the behavior is different from vim, but I am not particularly troubled with this behavior.
