### ISSUE TITLE
Ex Mode: Can't finish the :insert command

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#9849]
- `nvim --version`: NVIM v0.4.0-529-gfb555c689
- Vim (version: ) behaves differently?  Yes(8.0.1207)
- Operating system/version: CentOS Linux 7 (Core)
- Terminal name/version: tmux/2.6
- `$TERM`:  screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
Q
insert
foo
<C-c>
```

### Actual behaviour
The insert command does not finish.

### Expected behaviour
Exit the insert command.

In vim, the insert command ends with `<C-c>`.

**Comment by justinmk** [comment]
To finish `:insert`, insert a line only containing `.` (dot), see `:help :insert`.
`gQ` in Vim works the same way.
`Q` in Nvim is alias to `gQ`, see `:help Q`.

**Comment by erw7** [comment]
Oops.
