### ISSUE TITLE
Scroll Lock Key- support

### ISSUE THREAD

**Issue by SRGOM** [neovim/neovim#9850]
I am not sure if this is the right place to request this feature but I'd love to be able to map Scroll Lock key to something. 

Why waste keys when they are so precious for vim? I would love to see vim support keycode also so multimedia keys can also be used. 

I have something in mind for scroll lock, I will set it to toggle `scrollbind` and `cursorbind`. Maybe you can have this functionality as default.

**Comment by justinmk** [comment]
N/vim gets input. You can map any input to any command or keycode in N/vim. 

Unless there's some "scroll lock" terminfo key we're missing, there's nothing actionable here. Tell your OS, terminal, or GUI to send `foo` when you press scroll lock, then map `foo` in nvim.

    nnoremap foo blah

You can also map a foot pedal, car horn, SNES controller, and any other input device. Tell it to send something, then map that something using the N/vim mapping system.
