### ISSUE TITLE
Backspacing autoindent removes multiple spaces

### ISSUE THREAD

**Issue by marcelgoh** [neovim/neovim#9851]
- `nvim --version`: 0.3.4
- Vim (version: 8.1) behaves differently? YES
- Operating system/version: Mac OS Mojave
- Terminal name/version:
- `$TERM`: iTerm and Terminal.app

### Steps to reproduce
Make sure `~/.vimrc` file contains the following lines. Note that `softtabstop` is not set.
```
set autoindent
set shiftwidth=4
set expandtab
```

Create a new file called `foo.c` and type `int main() {` followed by a newline. It will autoindent with four spaces.

### Actual behaviour
Trying to delete these autoindented spaces deletes all 4 at a time. 

### Expected behaviour
Delete the spaces one at a time, unless `softtabstop=4` is set in `.vimrc`. (The Vim behaviour)

**Comment by mhinz** [comment]
```
:set nosmarttab
```

See `:h 'smarttab'` and `:h vim-diff`.

**Comment by marcelgoh** [comment]
Thanks for the help and sorry for not seeing the previous one!
