### ISSUE TITLE
SHM_ALL only contains 'x' when built with RelWithDebInfo

### ISSUE THREAD

**Issue by ernestask** [neovim/neovim#9855]
- `nvim --version`: 0.3.4
- Vim (version: 8.1) behaves differently? Yes.
- Operating system/version: Fedora 30
- Terminal name/version: Tilix 1.9.1
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

Any character from `SHM_ALL` except `x` will do:
```
nvim -u NORC
:set shortmess=c
```

Attaching gdb and looking at `p` after https://github.com/neovim/neovim/blob/c5e8924f4e72f46679cff52ac075e3eb023883d5/src/nvim/option.c#L3239 yields only `x`, so my guess is that GCC 9 is being more aggressive with optimizations. There is already a hack for a similar problem: https://github.com/neovim/neovim/blob/c5e8924f4e72f46679cff52ac075e3eb023883d5/src/nvim/option.c#L2492

### Actual behaviour
`E539: Illegal character <c>: shortmess=c`

### Expected behaviour
No error.

**Comment by jamessan** [comment]
Then isn't this a gcc bug?

**Comment by justinmk** [comment]
> There is already a hack for a similar problem:

@ernestask can you check if that hack works, and if so send a PR?

**Comment by jamessan** [comment]
Ah, I think I see the problem.

**Comment by jamessan** [comment]
GCC should really emit one of its "you're using a pointer to a value that's no longer in scope" diagnostics to make this easier to triage.
