### ISSUE TITLE
Yanking to + register on windows breaks pasting from + register

### ISSUE THREAD

**Issue by darylducharme** [neovim/neovim#9860]
- `nvim --version`: 0.4.0 and also 0.3.4
- Vim (version: ) behaves differently? Version 8.0 works fine
- Operating system/version: Windows 10
- Terminal name/version: PowerShell but also from nvim-qt
- `$TERM`:

### Steps to reproduce using `nvim -u NORC`
1. Copy something outside of neovim
2. In Neovim in normal mode press "+p to paste it
3. On any other line in normal mode press "+yy
4. Try to paste into some other windows app
5. Try to copy something else outside of neovim
6. Try to paste it again using "+p

### Actual behaviour
A command window titled "<path to>\neovim\bin\win32yank.exe" pops up at step 3
- in my case this is c:\tools\neovim\neovim\bin\win32yank.exe

The + register no longer gets new updates to paste from windows. It keeps the previous value.

### Expected behaviour
A command window shouldn't pop up and stay open
The yank and paste functionality should not break when pasting to/from neovim

**Comment by justinmk** [comment]
Thanks for reporting.

> A command window titled "\neovim\bin\win32yank.exe" pops up at step 3

Not sure what nvim-qt version you're using (in the future please report it and also the exact 0.4.x commit hash when possible), but the newest (or maybe current master) has a new "native" clipboard that can be enabled with:

    :call GuiClipboard()

However see also https://github.com/equalsraf/neovim-qt/issues/298#issuecomment-445456882 .

Regarding your issue,  I guess it's the same as https://github.com/neovim/neovim/issues/7000 , or in any case it requires someone to say what's different. If you want to debug it, [building Nvim with MSVC is easy](https://github.com/neovim/neovim/wiki/Building-Neovim#windows--msvc).

**Comment by darylducharme** [comment]
For completion:
GuiClipboard is only available in nvim-qt as it is in a qt specific shim file. So, when I run this in powershell it is still an issue.

Also, I seem to have to call it after <neovim path>\share\nvim-qt\runtime\plugin\nvim_gui_shim.vim but that seems to be last on the runtimepath without a way for me to set something after it. So, I have to make the call in Ex mode after startup.

It does work in nvim-qt though. And I can call it after win32yank.exe opens and I still get the fix. So, it is a usable workaround.

**Comment by darylducharme** [comment]
My nvim-qt says it is product version 0.2.10.0 BTW

**Comment by justinmk** [comment]
> Also, I seem to have to call it after \share\nvim-qt\runtime\plugin\nvim_gui_shim.vim but that seems to be last on the runtimepath without a way for me to set something after it. So, I have to make the call in Ex mode after startup.

I think nvim-qt supports ginit.vim or something like that. We will also have a `UIEnter` event soon.
