### ISSUE TITLE
Weird color highlighting with Folded

### ISSUE THREAD

**Issue by Pablo1107** [neovim/neovim#9863]
- `nvim --version`: v0.3.4
- Vim (version: vim-8.1.1073-1 ) behaves differently? Yes.
- Operating system/version: Arch Linux x64, Ubuntu 18.04 and Windows 10 WSL
- Terminal name/version: Termite on Linux distros, Mintty in Windows 10
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

:setlocal foldmethod=marker
:set relativenumber
```
You can also set highlight numbers but I didn't so I get minimum setup

Then, write some fold like this:

´´´
" Something {{{
}}}
´´´

### Actual behaviour
Sometimes the Folded color gets on top of the LineNr column and sometimes it don't. In Vim8, the folded always gets on tom of the LineNr column.

This is how it looks on my config. 
<details>
  <summary>Screenshot</summary>

  ![imagen](https://user-images.githubusercontent.com/17091659/55693941-05d85a00-5988-11e9-9ce7-de27aff8dfd8.png)

</details>

This is with default nvim -u NORC. 
<details>
  <summary>Screenshot</summary>

  ![imagen](https://user-images.githubusercontent.com/17091659/55694024-839c6580-5988-11e9-9e5e-4f717651c775.png)

  ![imagen](https://user-images.githubusercontent.com/17091659/55694057-9ca51680-5988-11e9-8eef-6273bb09267c.png)

</details>

### Expected behaviour
Folded color always gets on top of LineNr column.

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? Either this was already fixed, or AFAIR there's already an existing issue.

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by Pablo1107** [comment]
Thanks for the fast reply. I'll try the development version and get back here with the results.

**Comment by Pablo1107** [comment]
> 
> 
> Thanks for the report. Can you try the development version? Either this was already fixed, or AFAIR there's already an existing issue. Perhaps #9573 .
> 
> The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

I test this on nvim 0.4.0 prerelease and it's fixed there.

Thanks. :)
