### ISSUE TITLE
<m-<> can not mapped

### ISSUE THREAD

**Issue by luzhlon** [neovim/neovim#9864]
gvim can map it on Windows. Equivalently pressed `Alt+Shift+,`

**Comment by justinmk** [comment]
Works for me. Also try:

    nn <m-lt> :echo 'ok'<cr>

What does `<c-v><m-<>` show for you in insert-mode?
What does `cat -v` show in a shell?

Next time please fill out the issue template, so that version, terminal, etc is known.

**Comment by luzhlon** [comment]
Thanks. But `<m-lt>` is also not worked for me. And `<c-v><m-<>` show `<`, maybe it is a bug of nvim-qt.
