### ISSUE TITLE
Copy to system clipboard in GCE instance

### ISSUE THREAD

**Issue by pgurazada** [neovim/neovim#9865]
- `nvim --version`: 0.2.2
- Vim (version: ) behaves differently? version 8, does not behave differently
- Operating system/version: Ubuntu 18.04 on Google Compute Engine (GCE)
- Terminal name/version: byobu
- `$TERM`: screen-256color

Vim newbie here. I am using Neovim in a Google Compute Engine (GCE) instance as my primary editor. One common workflow for me is to split screen into two using `byobu` and open up `nvim` code editor in one window and an `ipython` console at the other. I wish to copy paste code to and from these two windows as I go along developing.   

I wish to copy code from the code window (neovim) using `"+y` or `"*y` and paste it into the `ipython` console to verify the logic. I particularly want to paste function definitions into the `ipython` console using the `%edit` magic (that opens up a temporary file in vim).  However, when I try to paste code from neovim into the vim interface in ipython, nothing happens, i.e., selected text is not pasted. 

I do a visual selection (`shift-v`) then do `"+y` and move to the `ipython %edit` console and do `"+p`. However, no selection is pasted.

After reading up prior issues that mention `xsel` and `xclip`, I installed them both `sudo apt-get install` and then ran a `:checkhealth`  in `nvim`. This returns for the clipboard section: `OK: Clipboard tool found: tmux`

What additional steps are required so I can paste from a neovim code window to an ipython console?

**Comment by justinmk** [comment]
You could use X forwarding over ssh, I think. Alternatively something like https://github.com/lemonade-command/lemonade . See also `:help clipboard-tool`.

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.
