### ISSUE TITLE
`echom` is suppressed in some autocmd

### ISSUE THREAD

**Issue by natebosch** [neovim/neovim#9870]
- `nvim --version`: Tested with both NVIM v0.4.0-567-gae2401621, NVIM v0.3.3
- Vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 11 2018 16:57:11)
Included patches: 1-577

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:au BufNewFile * echom 'Hello'
:edit /tmp/some_new_file
:messages
```

### Actual behaviour

No echoed message. Nothing in `:messages`

### Expected behaviour

See `Hello` echoed, and see it in `:messages`.

This is making it difficult to report problems when writing a plugin that uses `BufNewFile` and `BufReadPost`. I'm not sure what other autocmds are impacted. Some like `CursorHold` seem to work fine.

In `vim` these messages appear as expected.

**Comment by justinmk** [comment]
:set shortmess-=F
