### ISSUE TITLE
leak sanitizer report

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#9872]
git version 35362495c
- `nvim --version`:

<pre>
NVIM vcom
Build type: Debug
LuaJIT 2.0.5
Compilation: /home/wangxinyu/.local/bin/clang -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/config -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/src/nvim/auto -I/tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/build/include
Compiled by wangxinyu@archlinux

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
</pre>

- Operating system/version:
archlinux 64bit 
- Terminal name/version:
run from nvim-qt

<pre>
=================================================================
==9465==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 94 byte(s) in 1 object(s) allocated from:
    #0 0x4f06c8 in malloc /home/wangxinyu/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cc:145:3
    #1 0x891bfa in try_malloc /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/memory.c:69:15
    #2 0x891bfa in xmalloc /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/memory.c:103
    #3 0x891e82 in xmallocz /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/memory.c:178:15
    #4 0x891f37 in xmemdupz /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/memory.c:196:17
    #5 0xa8f77b in shada_read_next_item /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/shada.c:3791:9
    #6 0xa76130 in shada_read_when_writing /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/shada.c:2151:22
    #7 0xa76130 in shada_write /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/shada.c:2905
    #8 0xa71637 in shada_write_file /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/shada.c:3164:35
    #9 0x84ac8c in getout /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/main.c:671:5
    #10 0x75a007 in ex_exit /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ex_docmd.c:6456:7
    #11 0x73992b in do_one_cmd /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ex_docmd.c:2242:5
    #12 0x72ec97 in do_cmdline /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/ex_docmd.c:593:20
    #13 0x90c83a in nv_colon /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:4586:18
    #14 0x902017 in normal_execute /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:1128:3
    #15 0xaef96f in state_enter /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/state.c:73:26
    #16 0x8eb349 in normal_enter /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/normal.c:462:3
    #17 0x848495 in main /tmp/yaourt-tmp-wangxinyu/aur-neovim-git/src/neovim-git/src/nvim/main.c:597:3
    #18 0x7f98aefcf222 in __libc_start_main (/usr/lib/libc.so.6+0x24222)

SUMMARY: AddressSanitizer: 94 byte(s) leaked in 1 allocation(s).

</pre>

I'm using tig inside nvim (outer one) terminal , and do a commit, now tig opens  nvim(inner one) to edit commit message. after commit , using ":wq" to quite the inner nvim, now leak sanitizer report leak. (outer nvim didn't crash ,but I'm not sure if it will add some environment variable which my affect inner one so I mention it)

**Comment by justinmk** [comment]
Thanks. Known issue: https://github.com/neovim/neovim/issues/8223

It's a rather small leak that only happens on exit, so no one has spent time on it.
