### ISSUE TITLE
How to disable folding feature altogether for everything

### ISSUE THREAD

**Issue by 3N4N** [neovim/neovim#9877]
Is there any way to disable or discard folding feature from neovim? I am having trouble using `:Gdiff` from vim-fugitive because of folding. And there are some other plugins that uses folding. I want to disable folding totally from neovim. The same way you can enable features in vim when building, I want to disable `:h +folding` in neovim.

**Comment by nabn** [comment]
try :set nofoldenable

**Comment by 3N4N** [comment]
I want to remove the feature of folding. Not manually (or with `autocmd`) disable everytime.

**Comment by nabn** [comment]
Sorry if I'm not understanding you correctly, but you can append it to your .vimrc. Isn't that an option?

**Comment by 3N4N** [comment]
Even if I append it in my vimrc, vim-fugitive enables it. Or I can enable it manually with `zi`. I don't want there to be *any* way whatsoever for anything to use folds. I want to just clean remove folding feature.

**Comment by nabn** [comment]
Are you sure fugitive is overriding it? I'm using it and it seems fine.

**Comment by 3N4N** [comment]
Yes, I'm sure vim-fugitive is overriding it. I am testing with the following init.vim:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()

set nofoldenable
```

Also, it's not about vim-fugitive only. I want to just ditch folding. So, that neovim doesn't even know that there is something called folding.

**Comment by nabn** [comment]
I don't think it's neovim's fault that fugitive is turning folds on. Wouldn't you rather patch fugitive?

Also, curious why you don't want to go[ the `autocmd` route](https://github.com/tpope/vim-fugitive/issues/146#issuecomment-3733461).

**Comment by 3N4N** [comment]
I have no objection to use autocmd. There are many other situations where folds are bugging me. I now instinctively do `:w<CR>zi` and that's just annoying. I just want to remove folding. And I am reiterating, this is not about vim-fugitive. I have opened an issue there also, but that only is about `:Gdiff` command. I'm opening an issue here because I would love to have an way that folding is removed from my neovim. I'm saying once more, it's not about vim-fugitive, I just want folding removed.

**Comment by Shougo** [comment]
Unfortunately it is not possible in neovim.
It is possible in Vim.
You can disable folding feature in the compile time.

**Comment by justinmk** [comment]
autocmd BufEnter * set nofoldenable

For questions about usage/configuration, try https://vi.stackexchange.com or https://neovim.io/#chat. The issue tracker is for bugs and feature requests. Thanks.

**Comment by 3N4N** [comment]
@justinmk , sorry about posting here. I knew that neovim didn't have vim's compile time feature selection building. That's why I posted here, so that the devs might have an idea if it'll ever be allowed or not. If I was confused about whether or not it was possible to disable features I would not post here. This was more of a feature-request. Anyway, thanks.

**Comment by justinmk** [comment]
There is zero reason to make this a compile-time choice.

**Comment by 3N4N** [comment]
Okay, don't mind then. The autocmd's would be enough. Thanks.
