### ISSUE TITLE
Setting shortmess not possible: Illegal character

### ISSUE THREAD

**Issue by sedrubal** [neovim/neovim#9885]
- `nvim --version`: NVIM v0.3.4
- Vim (version: ) behaves differently? Yes
- Operating system/version: Fedora 30 (beta)
- Terminal name/version: konsole 18.12.2
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set shortmess
# returns: shortmess=filnxtToOF
:set shortmess=filnxtToOF
# returns: E539: Illegal character <f>: shortmess=filnxtToOF
```

### Actual behaviour
Every legal character is reported as illegal when setting `shortmess`. 

### Expected behaviour
The characters A, F, I, O, T, W, a, c, f, i, l, m, n, o, q, r, s, t, w, x should be legal characters as documented in `:help shortmess`.

**Comment by justinmk** [comment]
fixed by https://github.com/neovim/neovim/pull/9859 . @jamessan this should probably go in the release branch right?

**Comment by jamessan** [comment]
> @jamessan this should probably go in the release branch right?

Yeah, I should have thought about that so we could just merge the fix.  Cherry-pick will have to do.

**Comment by justinmk** [comment]
merged https://github.com/neovim/neovim/commit/9a5488c2a67e0066d4f2f8aeaf8058deaa58ce7a
