### ISSUE TITLE
:stopinsert should not leave next terminal mode

### ISSUE THREAD

**Issue by mars90226** [neovim/neovim#9889]
- `nvim --version`: NVIM v0.4.0-570-gddd0eb6f5
- Vim (version: ) behaves differently? yes
- Operating system/version: Ubuntu 18.04 Linux 4.18.20-041820-generic
- Terminal name/version: MobaXterm v11.1
- `$TERM`: xterm-256color. But in neovim, $TERM is screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:terminal
:stopinsert
i
```

### Actual behaviour
Do not enter terminal mode

### Expected behaviour
Enter terminal mode

I think the problem is that `:stopinsert` leave the next terminal mode. And I think [this commit](https://github.com/neovim/neovim/commit/d928b036dc2be8f043545c0d7e2a2b2285528aaa) is the reason.

**Comment by bfredl** [comment]
`stop_insert_mode = false` shouldn't be inside `terminal_check`, rather before `state_enter` in `terminal_enter`, to be consistent with `edit.c`.
