### ISSUE TITLE
`:set wildoptions+=tagfile` many times will append many "tagfile" to 'wildoptions'

### ISSUE THREAD

**Issue by mars90226** [neovim/neovim#9890]
- `nvim --version`: NVIM v0.4.0-570-gddd0eb6f5
- Vim (version: ) behaves differently?
Yes, vim 8.1.346 will raise exception `E474: Invalid argument: wildoptions+=tagfile`.
But I think it's probably because vim only allow "tagfile" in `'wildoptions'`.
- Operating system/version: Ubuntu 18.04 Linux 4.18.20-041820-generic
- Terminal name/version: MobaXterm v11.1
- `$TERM`: xterm-256color. But in neovim, $TERM is screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:set wildoptions+=tagfile
:set wildoptions+=tagfile
:set wildoptions?
```

### Actual behaviour
print `wildoptions=tagfile,tagfile`

### Expected behaviour
print `wildoptions=tagfile`

This bug also applies to `:set wildoptions+=pum`.

**Comment by mhinz** [comment]
Huh, that seems to be a regression. It works as expected with the 0.3.4 release.
