### ISSUE TITLE
Multigrid UI :quit closes multiple windows in tab

### ISSUE THREAD

**Issue by akiyosi** [neovim/neovim#9899]
- `nvim --version`: v0.4.0-321-g9a1675b06

- Vim (version: ) behaves differently? yes
- Operating system/version: macOS

- Terminal name/version: Not using a terminal

### Steps to reproduce using `nvim -u NORC`

```
gonvim [-u NONE]
:e /path/to/somefile.vim
:tabnew
gt
:vsp
:q
```

### Actual behaviour
The first tab disappears when you do the abobe steps

### Expected behaviour
The first tab should remain because it split the window with `:vsp`.

The following is the state of reproduction.
I'm testing with [gonvim](https://github.com/akiyosi/gonvim/tree/multigrid)

nvim `commit: 9a1675b06`:
![Apr-13-2019 18-33-25](https://user-images.githubusercontent.com/8478977/56080314-707f0f00-5e3a-11e9-92af-43bb19f40519.gif)

nvim `commit: 0aba4d825`:
![Apr-13-2019 18-32-55](https://user-images.githubusercontent.com/8478977/56080313-69f09780-5e3a-11e9-84e9-deef5fa8a240.gif)

**Comment by justinmk** [comment]
is there something significant about 9a1675b06 and 0aba4d825? Was the behavior bisected to one of those commits? I can't tell from the gifs.

**Comment by akiyosi** [comment]
I haven't seen enough of these commit differences, but the behavior of the GUI in multigrid UI seems to change between those commits.

**Comment by justinmk** [comment]
Can you write a Lua screen test showing the problem? See `test/functional/example_spec.lua` for an example.

You can [run the test](https://github.com/neovim/neovim/blob/master/test/README.md#running-tests) like this:

    TEST_FILE=test/functional/example_spec.lua make functionaltest

**Comment by akiyosi** [comment]
I confirmed that this issue can be detected by neovim's test `test/functional/ui/multigrid_spec.lua`. That is, even with the following operations in `multigrid_spec.lua`, problems occur on the GUI side but the test succeeds.

```
vsplit
wincmd l
split
wincmd h
q
```

I trace the events notified to the GUI side in detail, and it seems that `grid_destroy` has been sent for two grids by the operation `q` in the GUI. I have not identified the cause why it is sent twice.

I continue to investigate this issue.

**Comment by akiyosi** [comment]
I'm very very sorry.😓
This was a bug on the GUI side. I was sending `close` command to nvim on the `win_close`.
@Mariappan solved this problem.
