### ISSUE TITLE
sign column: variable width

### ISSUE THREAD

**Issue by freeo** [neovim/neovim#990]
Vim sets the width of the sign column to 2 with no possiblity to change that. It would be nice, if someone could change this to being variable (width of 1 or 2). 
This issue made me aware of the fixed value (vim help 'signs.txt' doesn't mention an option to change the width value)
https://github.com/tomtom/quickfixsigns_vim/issues/27

Anyone else here using the sign column who would be interested in this enhancement?

**Comment by alem0lars** [comment]
Is there someone interested in implementing @ZyX-I idea?

I'd love to have both gitgutter and marks visible in the lines..

Can we place a bounty on that? I can contribute economically

**Comment by zchee** [comment]
@ZyX-I +1
Hard code of the UI field is too bad.
I expectant.

**Comment by teto** [comment]
I've started looking into it. I have changed the code so that the width of the sign column is a function instead of hardcoded: I can change its width via recompiling. 
I will try to look for options as how to improve the column handling to sthg similar to what @ZyX-I proposes.

**Comment by dsummersl** [comment]
I love this idea - I'd love to have a signs column on the left for traditional vim plugins (signify, neomake, etc), and one on the right (that magic 'macro' mode column you see in intelij/chrome when searching for text).

**Comment by flowchartsman** [comment]
Has there been any movement on this? I would love to be able to see not only the sigils from Ale/Neomake, but also from gitgutter.

**Comment by da-x** [comment]
Hi all, 

Please try out the changes in my Neovim branch: https://github.com/da-x/neovim/pull/new/multiple-sign-columns ,  - it enables automatic resizing of the sign column to accommodate all the signs, so they don't run over each other.

Here's an example of mark + GitGutter + ALE:

![image](https://user-images.githubusercontent.com/321273/49253108-84e3e180-f42e-11e8-8fc1-ef35e4732e03.png)

**Comment by justinmk** [comment]
@da-x Cool, thanks for sharing. See also https://github.com/neovim/neovim/pull/6196 , which is stalled. Perhaps it is useful to see how to write screen tests.

**Comment by da-x** [comment]
Thanks. I've added a change to supplement this that merits further discussion: [for the removal of signs on deleted lines](https://github.com/neovim/neovim/commit/7c3383a099c24b1a6700c1580b7613687202f372).

Should this go for an `[RFC]` PR stage or should we continue further discussion here?

**Comment by fmoralesc** [comment]
@da-x If you opened the pull request, it would be helpful ;)

**Comment by blueyed** [comment]
Just for reference: sign columns are still a multiple of 2, i.e. you cannot just use a single column with e.g. signs that use a signle character only.
(I've tried to work on that in https://github.com/neovim/neovim/pull/9788 a while ago, but closed it by now)

**Comment by markstos** [comment]
Thanks for this feature.  Having read the docs for `signcolumn` and the issue above, it's not clear how Neovim knows when to overwrite an existing character vs add an additional character. For example, if I use `git-gutter` and `ALE`, how does it know that the ALE character should be next to the `git-gutter` character and not on top of it?

This topic is being discussed on StackExchange: https://vi.stackexchange.com/questions/21222/how-to-break-up-gutter-fights

Thanks.

**Comment by da-x** [comment]
@markstos, sign sorting is made according to sign-id, and sorting also prioritizes signs when there's no space for all of them to fit in. As each plugin determines the numbers for the sign id independently, the resulting behavior may be unpredictable. However I've made some plans to resolve this. See the discussion regarding sorting at: https://github.com/neovim/neovim/pull/9295 . Your input is appreciated.

**Comment by maharjanaman** [comment]
Hi @da-x , did your PR got merged and released? If yes, how do I use those features?

**Comment by da-x** [comment]
@maharjanaman, in Neovim 0.4.0. See [signcolumn](https://neovim.io/doc/user/options.html#'signcolumn').

**Comment by maharjanaman** [comment]
thanks @da-x

**Comment by avemilia** [comment]
As of 0.4.4 with `set signcolumn=yes:1` or `set signcolumn=auto:1` and `let g:ale_sign_error = '>' let g:ale_sign_warning = '-'` still produces 2 columns. Am I missing something?
![2020-10-16-064928_93x73_scrot](https://user-images.githubusercontent.com/46303212/96214438-c1198000-0f7b-11eb-9eaf-b95f7f71ca20.png)

**Comment by savchenko** [comment]
> in Neovim 0.4.0. See signcolumn.

- Neovim 0.4.4 and 0.5.0, `set signcolumn=auto:1` 
- Latest Ale and GitGutter:
  ```vim
  let g:ale_sign_error = 'E'
  let g:ale_sign_warning = 'W'
  let g:gitgutter_sign_allow_clobber = 1
  ``` 

Results in Ale using 2 characters nevertheless and overlapping with the GitGutter:

![image](https://user-images.githubusercontent.com/300146/131202985-84f50e4a-c685-43f2-b834-8a3b3c982623.png)

References:

- https://github.com/dense-analysis/ale/issues/1015
- https://github.com/airblade/vim-gitgutter/commit/9bf988bd1d2d8001f84126d8bf74036bab33bb9b 
- https://github.com/neovim/neovim/commit/36762a00a8010c5e14ad4347ab8287d1e8e7e064
- https://github.com/neovim/neovim/pull/9295

**Comment by winkee01** [comment]
I want to change signcolumn size from 2 characters to 1 charactor. Also, if there are multiple signcolumns, I want them ordered by priority or other options.  and how many sign columns that a specific plugin can have.
