### ISSUE TITLE
mode indicator no updating on remapped key

### ISSUE THREAD

**Issue by Sparki2002** [neovim/neovim#9908]
- `nvim --version`: 0.3.4
- Operating system/version: Arch Linux (Kernel 5.0.7)
- Terminal name/version: Termite v14
- `$TERM`: xterm-termite

### Steps to reproduce

1. Remap key
```
nnoremap ; :
vnoremap ; :
```

2. Press `:` in normal or visual mode

See [https://github.com/itchyny/lightline.vim/issues/357](https://github.com/itchyny/lightline.vim/issues/357)

### Actual behaviour

mode() does not update

### Expected behaviour

mode() should update to command mode

**Comment by justinmk** [comment]
Confirmed. Test case:

    nvim -u NONE -N -c 'set statusline=%{mode()} laststatus=2' -c 'nnoremap ; :'

**Comment by carloabelli** [comment]
`mode()` would actually return the correct value.

The problem occurs because `KeyTyped` is false, so the status line is not redrawn:

https://github.com/neovim/neovim/blob/53cef34f16635aba04d4443c4d94a18a34a38eca/src/nvim/ex_getln.c#L369-L372

**Comment by justinmk** [comment]
@carloabelli nice catch. 3a6b80f2f44dcb5cd050bbbaacce4fc8a638aede see https://github.com/neovim/neovim/pull/8347#issuecomment-387885663 for the background.

Could change to check `cmd_silent`, but this means that _any_ non-silent mapping containing `:` will redraw statusline, which may cause flicker (and is just wasteful).

However `<cmd>` and `<silent>` are workarounds, so I guess the answer is that users/plugins wanting to avoid flicker should use those in their mappings.
