### ISSUE TITLE
DirChanged behavior is inconsistent with Vim

### ISSUE THREAD

**Issue by notskm** [neovim/neovim#9909]
- `nvim --version`: v0.4.0-603-gd81b510ec
- Vim version: 8.1
- Operating system/version: Windows 10 1809
- Terminal name/version: conhost
- `$TERM`: 

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:vsplit
:lcd ..
:autocmd DirChanged * echo "Directory changed!"
```
In Neovim, switching between windows with `<c-w><c-w>` triggers the autocmd and prints "Directory changed!". This does not happen in Vim.

### Actual behaviour
The DirChanged event triggers when switching between tabs and windows. This does not happen in vim.

### Expected behaviour
The DirChanged event should only trigger when `cd`, `lcd`, and `tcd` are used to change the working directory. This seems to be how it works in Vim.

### Additional info
I'm currently writing a plugin for Vim and Neovim. I need to read a file and reset a few variables whenever the user changes the working directory. In Neovim, DirChanged triggers whenever the user switches windows/tabs after using `tcd`/`lcd`. This results in variables being reset when they shouldn't be. It also results in extra file reads. In my case, there doesn't seem to be an easy workaround.

### Proposed solutions
1. Make DirChanged behave like it does in vim.
    * A new event could be added to mimic Neovim's current behavior if necessary.
2. Keep the current behavior and add a new event that behaves like DirChanged does in vim.
3. Keep the current behavior and add a flag to v:event that is nonzero only when switching between tabs and windows.

**Comment by mhinz** [comment]
Just for the record: We added `DirChanged` over a year before Vim did, so some differences are to be expected. :)

That said, I don't think there is any code that relies on `DirChanged` triggering so often, so.. we should change it to work as in Vim.

**Comment by mhinz** [comment]
@justinmk Do we want to behave like Vim here?

Apparently we added the current behavior on purpose: https://github.com/neovim/neovim/issues/6054

**Comment by justinmk** [comment]
> Apparently we added the current behavior on purpose: #6054

Right, and for good reason.

> The DirChanged event should only trigger when `cd`, `lcd`, and `tcd` are used to change the working directory. This seems to be how it works in Vim.

Based on what? The event was never intended to just listen for `:cd` command. For that we would implement something more generic like `CommandInvoked` event.

**Comment by justinmk** [comment]
> 3\. Keep the current behavior and add a flag to v:event that is nonzero only when switching between tabs and windows.

That seems reasonable.

**Comment by tristone13th** [comment]
It seems currently we don't support PreDirChanged/PostDirChanged events as in vim, do we have a plan for this?

**Comment by zeertzjq** [comment]
> It seems currently we don't support PreDirChanged/PostDirChanged events as in vim, do we have a plan for this?

What do you mean?

**Comment by tristone13th** [comment]
> > It seems currently we don't support PreDirChanged/PostDirChanged events as in vim, do we have a plan for this?
> 
> What do you mean?

Add support for `autocmd! PreDirChanged * do_something`

**Comment by zeertzjq** [comment]
`DirChangedPre`?

**Comment by tristone13th** [comment]
> `DirChangedPre`? That's already supported.

Oh Thanks, I misspelled it :)
