### ISSUE TITLE
E886: System error while opening ShaDa file for writing: no such file or directory

### ISSUE THREAD

**Issue by hubitor** [neovim/neovim#9912]
- `nvim --version`: v0.4.0-609
- Vim (version: ) behaves differently? 8.1.1073 - Yes
- Operating system/version: Antergos (Arch Linux)
- Terminal name/version: terminator 1.91-6
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
I've configured Neovim on my main system and it works fine, so I've copied everything from   `~/.local/share/nvim/` and pasted into the same location on a VM I've got and installed Neovim on the VM. Now, when I open Neovim I see no errors but when I close it, I get this error:

`E886: System error while opening ShaDa file for writing: no such file or directory
`

There is this file:

`~/.local/share/nvim/shada/main.shada`

already. I don't understand why Neovim is complaining.
I have deleted and re-installed Neovim in case it gets recreated but that was not the case. I'm still getting the same error.

### Expected behaviour

No errors...

**Comment by bnjbvr** [comment]
Same here.

**Comment by mhinz** [comment]
The problem is known and we discussed it internally. It happens since: https://github.com/neovim/neovim/pull/9907

Fix will follow very soon.

**Comment by comfortablynick** [comment]
I solved this problem temporarily by explicitly defining this in my vimrc:
```vim
let &viminfofile = expand('$XDG_DATA_HOME/nvim/shada/main.shada')
```
That has silenced the errors and has seemingly given me access to history again.

**Comment by mhinz** [comment]
Should work again.

@comfortablynick `&shadafile`, please. :)

**Comment by sajusat** [comment]
> NVIM v0.2.2
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
> Compiled by pkg-vim-maintainers@lists.alioth.debian.org
> 
> Features: +acl +iconv +jemalloc +tui 
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info

I still get the error.

**Comment by mhinz** [comment]
@sajusat You're using Nvim v0.2.2, but the latest release is v0.4.3. You're missing over 4000 patches.

**Comment by sajusat** [comment]
> @sajusat You're using Nvim v0.2.2, but the latest release is v0.4.3. You're missing over 4000 patches.
@mhinz Sorry about the confusion. I just installed neovim using *sudo apt-get install neovim* with Ubuntu 18.04.3 LTS. I was expecting that they were updating it regularly. I didn't see the difference in versions.

**Comment by hiagop** [comment]
I got this error on elementaryOS 5.1, Neovim v0.2.2. For some reason the following files came with their ownership set to the `root` user: 
``` bash
/home/<user>/.local/share/nvim
/home/<user>/.local/share/nvim/swap
/home/<user>/.local/share/nvim/shada
/home/<user>/.local/share/nvim/shada/main.shada
```

Running 
``` bash
sudo  find . -not -user <user> -exec chown -R <user>:<group> {} \;
```
solved the problem.

**Comment by IvanStanul** [comment]
OS - macOS Mojave. 
Installed dev version of neovim `brew install --HEAD neovim`. Double-checked that version isn't outdated:
```
nvim -version 
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
```
Tried running as normal user `nvim test` - got an error:
```
Error detected while processing function <SNR>14_LoadRemotePlugins[1]..<SNR>14_G
etManifest[1]..<SNR>14_GetManifestPath:
line   10:
E739: Cannot create directory /Users/velfess/.local/share: permission denied
E886: System error while opening ShaDa file /Users/velfess/.local/share/nvim/sha
da/main.shada for reading: permission denied
E303: Unable to create directory "/Users/velfess/.local/share" for swap file, re
covery impossible: permission denied
E303: Unable to open swap file for "test", recovery impossible
E886: System error while opening ShaDa file /Users/velfess/.local/share/nvim/sha
da/main.shada for reading: permission denied
Press ENTER or type command to continue
```

Ran as root later on - didn't any errors. But running as regular user still gives me error. Removed `.local/share/nvim` directory in hopes it would recreate when I ran as normal user again - nope, still an error.

**Comment by Lucretiel** [comment]
Confirm, I get this issue on a regular brew install:

```
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info
```

```
vim ~/test
E886: System error while opening ShaDa file /Users/nathanwest/.local/share/nvim/shada/main.shada for reading: permission denied
E303: Unable to create directory "/Users/nathanwest/.local/share/nvim/swap" for swap file, recovery impossible: permission denied
E303: Unable to open swap file for "/Users/nathanwest/test", recovery impossible
E886: System error while opening ShaDa file /Users/nathanwest/.local/share/nvim/shada/main.shada for reading: permission denied
Press ENTER or type command to continue
```

**Comment by tlightsky** [comment]
same here, 
```
❯ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/config -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/include
Compiled by brew@BigSur
```

**Comment by xplosionmind** [comment]
Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?

**Comment by IvanStanul** [comment]
> Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?

This fixed it for me on macOS: 

> sudo chown {username} ~/.local
> sudo chown {username} ~/.local/share
> sudo chown {username} ~/.local/share/nvim
> sudo chown {username} ~/.local/share/nvim/shada
> sudo chown {username} ~/.local/share/nvim/shada/main.shada
> sudo chown {username} ~/.local/share/nvim/swap

**Comment by solotim** [comment]
I get this error suddenly out of nowhere.  None of the solutions listed here work for me. I removed the main.shada and recreated it, nothing changed.

`E886: System error while closing ShaDa file: Unknown system error -122`

**Comment by nick-bull** [comment]
> > Hello, I am having the same issue and I could not find a way to fix it. @Lucretiel could you specify the exact `chown` command you performed? @tlightsky I get the same output when I run `nvim --version`. Were you able to solve it?
> 
> This fixed it for me on macOS:
> 
> ```
> sudo chown {username} ~/.local
> sudo chown {username} ~/.local/share
> sudo chown {username} ~/.local/share/nvim
> sudo chown {username} ~/.local/share/nvim/shada
> sudo chown {username} ~/.local/share/nvim/shada/main.shada
> sudo chown {username} ~/.local/share/nvim/swap
> ```

These commands can be reduced to `sudo chown -R "${USER}" ~/.local` if you don't mind `chown`ing the entire directory for your user, which likely is the case given that it's in your user directory

**Comment by bluebrown** [comment]
chown didnt help for me

**Comment by vedantroy** [comment]
I still get the error on quitting about the shada file not being writeable due to permissions issues.

**Comment by ivanovsaleksejs** [comment]
I have the same issue with NVIM v0.8.1. Files in ~/.local/share/nvim and subdirs belong to my user and group, and permissions are 0600.

**Comment by zeertzjq** [comment]
It's now `~/.local/state/nvim`

**Comment by dverzolla** [comment]
`sudo chown -R "${USER}" ~/.local` worked here for fixing E303.

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```

Running on macOS Ventura.

**Comment by ShailMahan012** [comment]
I got the same error.
It was because permissions of ~/.local/state/nvim/shada/shada.main were not right.
Check the permission of shada and shada.main file.
execute this to add read and write permission for file `chmod +r ~/.local/state/nvim/shada/*`
