### ISSUE TITLE
make `getqflist()` return a non-empty dictionary when asking for the property of a quickfix list which doesn't exist

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#9914]
- `nvim --version`:      NVIM v0.4.0-610-g773bdd41e Build type: RelWithDebInfo
 - Vim (version: 8.1-1176) behaves differently? Yes.
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

### Steps to reproduce using `nvim -u NORC`

Consider this shell command:

    $ nvim -Nu NONE +'echo getqflist({"id": 0})'

### Actual behaviour

It outputs:

    {}

The same command in Vim:

    $ vim -Nu NONE +'echo getqflist({"id": 0})'

Outputs a non-empty dictionary with a key matching the property which was asked:

    {'id': 0}

In practice, it means that every time you need to inspect the value of a quickfix property, you have to invoke `get()` in Nvim:

    :echo get(getqflist({'id': 0}),'id')
          ^^^^                    ^^^^^^
Otherwise, you raise `E716: Key not present in Dictionary: id`.

OTOH, in Vim, you don't need to:

    :echo getqflist({'id': 0}).id

I have run the same command after replacing the `'id'` property with the `'size'` one, and the difference persists; so it doesn't seem to be specific to a property in particular.

### Expected behaviour

If `getqflist()` could return a non-empty dictionary when there's no quickfix list, it would be more consistent with Vim, and the code one has to write to inspect a quickfix property would be a little less verbose.

**Comment by mhinz** [comment]
Yup, it will happen sooner or later. Our quickfix code doesn't differ from Vim's and we port Vim's patches (that also apply to Nvim's changed codebase) on a regular basis. The patches you're after were simply not merged yet. :)

**Comment by justinmk** [comment]
is this still a problem on latest master?
