### ISSUE TITLE
Spurious " appears on the command-line when `setcmdpos()` is invoked

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#9917]
- `nvim --version`:      NVIM v0.4.0-610-g773bdd41e Build type: RelWithDebInfo
 - Vim (version: 8.1-1176) behaves differently? Yes, no undesired quotation mark on Vim's command-line.
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

### Steps to reproduce using `nvim -u NORC`

Consider this shell command:

    $ nvim -Nu NONE +'nno cd :tabe $MYVIMRC<c-r>=setcmdpos(14)[-1]<cr>'

It installs a mapping, triggered by the sequence `cd`, wich populates the command-line with `:tabe $MYVIMRC` and positions the cursor to the 14th byte.

### Actual behaviour

If you press `cd`, the command-line is populated with:

    :tabe $MYVIMRC"
                  ^

Note the quotation mark at the end. It's drawn on the command-line, but I don't think it's really there; if it was, the mapping would fail to edit the `init.vim` file after pressing Enter (provided you started Nvim without `-Nu NONE`).

I bisected the issue to [`3b7a4f2`](https://github.com/neovim/neovim/commit/3b7a4f233bd53eb901904992227be3fffe5e621a).

The example given here is contrived, because you don't need `<c-r>=setcmdpos(n)[-1]`. But I do in a plugin where I install a key binding which cycles through a set of arbitrary commands to populate the command-line. I need something like `<c-r>=setcmdpos(stridx(cmdline, special_char))[-1]`.

Every time the command-line is populated by a command, there's a spurious quotation mark somewhere in the middle or at the end.

![MPdvU4W](https://user-images.githubusercontent.com/8505073/56265356-9847ce80-60e9-11e9-8594-67ce26a2ade2.gif)

And if you move the cursor, it gets worse, you can have multiple quotation marks anywhere.

![gif](https://user-images.githubusercontent.com/8505073/56265251-620a4f00-60e9-11e9-8e8b-1ab54da7e8f0.gif)

### Expected behaviour

No spurious quotation mark on the command-line after invoking `setcmdpos()` through the expression register to set the position of the cursor.

**Comment by blueyed** [comment]
Bisected this to https://github.com/neovim/neovim/commit/3b7a4f233bd53eb901904992227be3fffe5e621a /cc @LTKills 

I am using a mapping where this occurs with: `nnoremap ,ee :e <C-R>=expand("%:p:h") . "/" <CR>`

**Comment by LTKills** [comment]
Thx for the cc @blueyed. The problem seems to be in `<C-R>`, rather than `setcmdpos`. It seems the special character `"` isn't NULlified after other characters get typed -- the same behavior occurs with `<C-K>` (`?`) and `<C-O>` (`^`), but in these cases I didn't forget to `ccline.special_char = NUL`. I think I removed that line from `<C-R>` before commiting and forgot to put it back.
