### ISSUE TITLE
Cursor color changes after Tab completing `:help`

### ISSUE THREAD

**Issue by lacygoill** [neovim/neovim#9918]
- `nvim --version`:      NVIM v0.4.0-610-g773bdd41e Build type: RelWithDebInfo
 - Vim (version: 8.1-1176) behaves differently? Yes, the cursor is correctly drawn.
 - Operating system:     Ubuntu 16.04.6 LTS
 - Terminal emulator:    rxvt-unicode v9.22
 - Terminal multiplexer: tmux 2.9
 - `$TERM`:              tmux-256color
 - Shell:                zsh 5.7.1-dev-0 (x86_64-pc-linux-gnu)

### Steps to reproduce using `nvim -u NORC`

Consider this shell command:

    $ nvim -Nu NONE +'colo evening'

### Actual behaviour

If you type `:help` then press Tab to complete the command, the wildmenu appears and suggests:

    help  helpclose  helpgrep  helptags

But the color of the cursor changes from black to light grey, and the next 2 cells are colored in white, while they should be colored like the rest of the line (i.e. dark grey).
If you insert 3 characters, the cursor color is properly restored.
If you press Tab to get the next suggestion (`helpclose`), the cursor color is, again, properly restored.
If you press Escape, the cells 5, 6 and 7 on the command-line stay in white.

![gif](https://user-images.githubusercontent.com/8505073/56268545-df39c200-60f1-11e9-9fa4-d99dbc8c7ade.gif)

I bisected the issue to [`7ede14d`](https://github.com/neovim/neovim/commit/7ede14d191b1220ac872a24433825997d62ff7ec).

It seems related to some colorschemes, because I can't reproduce with the default one, but I can with [seoul256.vim](https://github.com/junegunn/seoul256.vim). OTOH, the terminal doesn't seem relevant, because I can reproduce in st, urxvt, xfce4-terminal and gnome-terminal, inside/outside tmux.

### Expected behaviour

The cursor color should not change after tab completing `:help`.

**Comment by bfredl** [comment]
> I bisected the issue to 7ede14d.

We should probably get rid of that macro. It is just a for loop at this point.

**Comment by bfredl** [comment]
Interestingly, I can reproduce in xterm, but not pangoterm (libvterm), urxvt or gnome-terminal. But this could just be that nvim still believes "real" xterm is more capable, and uses some invalid branch only there.

**Comment by justinmk** [comment]
@lacygoill  Which change specifically in https://github.com/neovim/neovim/commit/7ede14d191b1220ac872a24433825997d62ff7ec causes this?

**Comment by lacygoill** [comment]
@justinmk  I don't know C, so I simply tried to check out the parent commit ([`a70fde1`](https://github.com/neovim/neovim/commit/a70fde1b45859bbe557261493bfff40aa90d469a)), then restore the commit [`7ede14d`](https://github.com/neovim/neovim/commit/7ede14d191b1220ac872a24433825997d62ff7ec) line by line, to see at which point does the issue appear.

Unfortunately, the 4 lines seem to depend on each other. That is, if I change one, and only one of the 4 lines, then the compilation fails, and I can't test whether Nvim has the current issue.

**Comment by justinmk** [comment]
@lacygoill it should compile if you remove `-Wshadow` in CMakeLists.txt, which was added in the parent https://github.com/neovim/neovim/commit/a70fde1b45859bbe557261493bfff40aa90d469a#diff-af3b638bc2a3e6c650974192a53c7291R177

**Comment by lacygoill** [comment]
I have edited `CMakeLists.txt` to remove the `-Wshadow` option:

    $ sed -i 's/-Wshadow//' CMakeLists.txt

Which worked, because this `$ grep` command outputs nothing:

    $ grep -i -- '-Wshadow' CMakeLists.txt

Then I have manually restored the first line of the commit in `src/nvim/tui/tui.c`:

    $ sed -i '1177s/\<col/curcol/' src/nvim/tui/tui.c

But the compilation still fails. Here's [the output of `$ make`](https://0x0.st/zblY.txt).

It still fails after restoring, in addition to the first line, [the second line](https://0x0.st/zblU.txt) (`$ sed -i '1286s/\<col/curcol/' src/nvim/tui/tui.c`), and [the third](https://0x0.st/zbld.txt) (`$ sed -i '28s/\<col/curcol/g' src/nvim/ugrid.h`).

I [can compile](https://0x0.st/zbl4.txt) only after restoring the fourth line (`$ sed -i '29s/\<col/curcol/' src/nvim/ugrid.h`).

**Comment by justinmk** [comment]
It must be the case in `cursor_goto` , rather than the cases actually _modified_ by 7ede14d.

**Comment by justinmk** [comment]
could you please try this path (applied to 7ede14d):

```diff
+++ b/src/nvim/tui/tui.c
@@ -700,7 +700,7 @@ static void cursor_goto(UI *ui, int row, int col)
       int n = col - grid->col;
       if (n <= (row == grid->row ? 4 : 2)                                                                                 
           && cheap_to_print(ui, grid->row, grid->col, n)) {                                                                                 
-        UGRID_FOREACH_CELL(grid, grid->row, grid->col, col, {
+        UGRID_FOREACH_CELL2(grid, grid->row, grid->col, col, {
           print_cell(ui, cell);
         });
       }
diff --git a/src/nvim/ugrid.h b/src/nvim/ugrid.h
index 19c2e99ebb3b..4d40b8ce9ef2 100644
--- a/src/nvim/ugrid.h
+++ b/src/nvim/ugrid.h
@@ -32,6 +32,16 @@ struct ugrid {
     } \
   } while (0)
 
+#define UGRID_FOREACH_CELL2(grid, row, startcol, endcol, code) \
+  do { \
+    UCell *row_cells = (grid)->cells[row]; \                                 
+    for (int col = startcol; col < endcol; col++) { \  
+      UCell *cell = row_cells + col; \
+      (void)(cell); \
+      code; \
+    } \                                                         
+  } while (0)
+                                            
 #ifdef INCLUDE_GENERATED_DECLARATIONS                
 # include "ugrid.h.generated.h"       
 #endif
```

If that doesn't work, try changing each case of `UGRID_FOREACH_CELL` to `UGRID_FOREACH_CELL2`. Only change one case at a time. Then we can see exactly which case expects this weird side-effect.

**Comment by lacygoill** [comment]
I have manually applied the patch, and in my limited testing, it seems to have fixed the issue. That is, when I start Nvim like this:

    $ ./build/bin/nvim -Nu NONE +'colo evening'

Then tab completing `:help` doesn't change the color of the cursor. Thank you very much @justinmk.

**Comment by justinmk** [comment]
`build/src/nvim/auto/tui/tui.i` shows that `UGRID_FOREACH_CELL2` expands to:

```c
do {
  UCell *row_cells = (grid)->cells[grid->row];
  for (int col = grid->col; col < col; col++) {
    UCell *cell = row_cells + col;
    (void)(cell);
    {
      print_cell(ui, cell);
    };
  }
} while (0);
```

In other words, that for-loop was never entered (because `col < col` is always false) ...

**Comment by justinmk** [comment]
can you try https://github.com/neovim/neovim/pull/9952 ?

**Comment by lacygoill** [comment]
It works on all the terminals I could try (urxvt, xterm, st, xfce4-terminal), inside/outside tmux.
