### ISSUE TITLE
:terminal insert autocmd potential regression

### ISSUE THREAD

**Issue by YaLTeR** [neovim/neovim#9919]
I have the following lines in my rc for automatically starting insert mode when entering a `:terminal` buffer:
```vim
autocmd BufEnter term://* startinsert
autocmd BufLeave term://* stopinsert
```
Starting from commit d928b036dc2be8f043545c0d7e2a2b2285528aaa they started behaving improperly: the first time I focus a `:terminal` buffer it goes into insert mode, but any subsequent time I focus a `:terminal` buffer it doesn't. I was able to solve the issue by commenting out the `BufLeave` autocmd, but this behavior (works only the first time) doesn't seem intended.

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
:autocmd BufEnter term://* startinsert | autocmd BufLeave term://* stopinsert
C-w v, :term
C-w l, C-w h (observe how it went into insert mode)
C-\ C-n, C-w l, C-w h (observe how it doesn't go into insert mode the second time, and how it does before that commit)
```

**Comment by bfredl** [comment]
dup of  #9889 ?

**Comment by YaLTeR** [comment]
Ah yeah, seems like it.
