### ISSUE TITLE
`:checkhealth provider` fails with a curl without HTTPS support

### ISSUE THREAD

**Issue by mhinz** [neovim/neovim#9925]
`:checkhealth provider` uses `s:download('https://pypi.python.org/pypi/pynvim/json')` which fails with a curl without HTTPS support.

Possible solutions:

- Change the URL to use HTTP right away.
- Test if `curl -V` includes `https` and fall back to HTTP otherwise.
- If curl doesn't support HTTPS, fall back to the Python approach using `urlopen`.

Relevant code:

https://github.com/neovim/neovim/blob/773bdd41ec19c9909e979c4580cf098d71d168d7/runtime/autoload/health/provider.vim#L109-L126

**Comment by justinmk** [comment]
Let's test if `curl -V` includes https and show an error if not. We don't need to dance around trying to fall back to HTTP, HTTPS is a reasonable requirement.
