### ISSUE TITLE
Crash when searching for column with number between 2^64 - 1 and 2 ^ 64 - 2 ^ 31

### ISSUE THREAD

**Issue by rgreenblatt** [neovim/neovim#9930]
NVIM v0.4.0-dev
VIM - Vi IMproved 8.1 compiled from source today does not crash.
- Operating system/version: Ubuntu 18.10
- Terminal name/version: st
- `$TERM`: xterm-256color and st-256color both reproduce the problem

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
/\v%18446744071562067968c
```
Will yield: 
```
nvim: /build/neovim-5zUQcT/neovim-0.4.0+ubuntu1+git201904202022-43356a4-eada8be/src/nvim/regexp_nfa.c:5926: nfa_regmatch: Assertion `t->state->val >= 0 && reginput >= regline && (uintmax_t)(reginput - regline) <= UINTMAX_MAX - 1' failed.
                                               
[1]    30948 abort (core dumped)  /usr/bin/nvim -u NORC
```

Any number between 18446744071562067968 (2^64 - 2^31) and 18446744073709551615 (2^64 - 1) causes a crash for me. The issue doesn't reproduce for 2^64 - 2^32 but I am not sure where the issue stops occuring between 2^64 - 2^31 and 2^64 - 2^32.

I ran into this while generating patterns using c++ and overflowing a size_t value. I can't imagine this is a problem for anyone, but it does seem at least to me like something that should get fixed if possible.

**Comment by mhinz** [comment]
This assert is hit: https://github.com/neovim/neovim/blob/43356a43d00ff69e90afd5186e066b4d27b66d9d/src/nvim/regexp_nfa.c#L5924-L5926

**Comment by justinmk** [comment]
Should show an `EMSG` error instead of asserting.

**Comment by gafeol** [comment]
Hi, I was trying to solve this issue, but I’ve been unable to create an error message on the `regexp_nfa.c` file.
My biggest problem is figuring out where to create the error message with `EMSG`, I've tried substituting the `assert` on line 5924 for an `if`:
![Screenshot from 2019-05-13 21-46-02](https://user-images.githubusercontent.com/12179028/57663021-8e21ce80-75c8-11e9-864f-4fecfa82be08.png)
But then when reproducing the issue I get these errors:
![Screenshot from 2019-05-13 21-41-33](https://user-images.githubusercontent.com/12179028/57662881-ead0b980-75c7-11e9-952e-0c56ea3f49e7.png)
![Screenshot from 2019-05-13 21-41-58](https://user-images.githubusercontent.com/12179028/57662893-f91ed580-75c7-11e9-8e80-981ec6661e9c.png)

Should I stop the execution of the function `nfa_regmatch` with some return value other than just `false`?

**Comment by justinmk** [comment]
> But then when reproducing the issue I get these errors:

That is what I would expect. What else is the editor supposed to do with such a column?

**Comment by jamessan** [comment]
[v8.1.0908](https://github.com/vim/vim/releases/tag/v8.1.0908) is relevant.
