### ISSUE TITLE
Windows 10 Neovim terminal doesn't properly display 256 colors

### ISSUE THREAD

**Issue by moshen** [neovim/neovim#9937]
- `nvim --version`:
```
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently? Doesn't have the :terminal functionality
- Operating system/version: Windows 10
- Terminal name/version: Powershell
- `$TERM`: N/A ?

### Steps to reproduce using `nvim -u NORC`

Using `AnsiColors256.ans` from https://github.com/Maximus5/ConEmu/blob/master/Release/ConEmu/Addons/AnsiColors256.ans

```
nvim -u NORC
:term wsl
cat AnsiColors256.ans
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/168513/56701092-89ee4980-66cb-11e9-8bd1-dff5e0dfc286.png)

Also broken inside neovim-qt:

![image](https://user-images.githubusercontent.com/168513/56626096-471a6c00-660e-11e9-9572-c316bdf9a3a2.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/168513/56701104-91155780-66cb-11e9-8280-eafb445d1b1e.png)

Using the WSL terminal and nvim inside WSL, this appears to work properly:

![image](https://user-images.githubusercontent.com/168513/56701124-a5f1eb00-66cb-11e9-816e-4e8c7ed651df.png)

![image](https://user-images.githubusercontent.com/168513/56701126-ab4f3580-66cb-11e9-8ace-230406d21c97.png)

**Comment by justinmk** [comment]
Try the development version (0.4.0). The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS.

> Using the WSL terminal and nvim inside WSL, this appears to work properly:

Nvim 0.4.0 supports more `TERM` values, see `:help $TERM` and try the various Windows values mentioned there.

**Comment by moshen** [comment]
@justinmk No, I meant using the WSL terminal (A Console Window Host? Process looks the same as a cmd window and I don't know that much about it) with the linux version of neovim running within WSL, 256 colors appear properly within the neovim `:terminal`.

When running the windows version of neovim, regardless of the terminal emulator the neovim `:terminal` does not show 256 colors properly.

I just tried 0.4.0 and I get the exact same result.

**Comment by justinmk** [comment]
@moshen The last screenshot shows 256 colors working in a `:terminal`, doesn't it?

**Comment by moshen** [comment]
@justinmk The last screenshot is the example of the linux version of neovim running within wsl.  I've been attempting to use that (but that setup has unrelated issues).  Running the windows version doesn't appear to work as expected.

`:echo &term` for various setups:

- nvim-qt
  - `nvim`
- nvim in powershell
  - `builtin_vtpcon`
- nvim in powershell in Fluent Terminal
  - `builtin_xterm`

When I change `$TERM` to something like `xterm-256color` in powershell, it appears to be set correctly in neovim (shows as `builtin_xterm`).

All these result in the same thing.

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/9937#issuecomment-487294477
see `:help $TERM`. Try the recommended Windows TERM values mentioned there.

**Comment by justinmk** [comment]
Actually if `term=builtin_vtpcon` doesn't show improvement then that settles it.

**Comment by moshen** [comment]
I tried the build from here: https://ci.appveyor.com/project/neovim/neovim/builds/22156610/job/k7c0xjr21dpox7ro/artifacts

Same issue.

Reviewed the `$TERM` list again and yes, `vtpcon` seems like it is appropriately set.  Also when I load my init the 256 colorscheme seems to work.  It is just colors within `:terminal` seem to be stuck in a 16 color mode.

**Comment by erw7** [comment]
This is limitation with `winpty`. As discussed in rprichard/winpty#152, we need to make `winpty` correspond to `ConPTY`, or if `ConPTY` is available, we need to change neovim to use `ConPTY` instead of `winpty`.
