### ISSUE TITLE
INSERT (paste) Mode still contains indentation

### ISSUE THREAD

**Issue by gukz** [neovim/neovim#9939]
- `nvim --version`: NVIM v0.2.2
- Vim (version: ) behaves differently? YES  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
- Operating system/version: Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-36-generic x86_64)
- Terminal name/version:
- `$TERM`: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Actual behaviour
after I <C-c> from the website, then go to nvim to <C-v>(in INSERT paste mode), the text contains many space.
### Expected behaviour
after my <C-v>, all text just like what they are in the website.
here is the [website](https://raw.githubusercontent.com/wdicarlo/vim-notebook/master/plugin/notebook.vim) that I want to copy.

**Comment by gukz** [comment]
[nvim_paste.vim.txt](https://github.com/neovim/neovim/files/3115403/nvim_paste.vim.txt)
I name this file to nvim_paste.vim, but I can only upload file ends with txt, so I add `.txt` to the file name.

**Comment by justinmk** [comment]
Nvim uses bracketed-paste by default, there is no need to set 'paste'.

Meanwhile this is a known issue, covered in existing tickets.
