### ISSUE TITLE
neovim doesn't recognise win32yank as a clipboard tool

### ISSUE THREAD

**Issue by Irubataru** [neovim/neovim#9940]
- `nvim --version`: v0.3.4
- Operating system/version: Ubuntu 18.04.2 LTS (Windows WSL)
- Terminal name/version: Windows WSL terminal

### Steps to reproduce using `nvim -u NORC`

1. Install `win32yank` and link it somewhere in `PATH` (I have it linked to `/usr/bin`) [following the FAQ instructions](https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl).
2. Run `:checkhealth` in neovim

### Actual behaviour

neovim doesn't find any clipboard tool.

### Expected behaviour

neovim should find the clipboard tool. 

This worked until very recently when I updated, but I am not sure which version of neovim I was using when it worked. Anyway, naming the executable `win32yank.exe` instead of `win32yank` makes neovim find it, so you should either recognise both executables, or update the wiki.

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/pull/9263 . But I wonder if that is still necessary after https://github.com/neovim/neovim/pull/9516 (requires 0.4.0, current prerelease).

Closing this, but if anyone finds that https://github.com/neovim/neovim/pull/9263 is not necessary on current master (0.4.0), please send a PR.
