### ISSUE TITLE
Full-width chars in virtual text shift colorcolumn

### ISSUE THREAD

**Issue by heftig** [neovim/neovim#9941]
- `nvim --version`:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim does not have virtual text
- Operating system/version: Arch Linux
- Terminal name/version: `# GNOME Terminal 3.32.1 using VTE 0.56.2 +GNUTLS`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NONE
:set colorcolumn=80
:echo nvim_buf_set_virtual_text(nvim_get_current_buf(), -1, line(".") - 1, [["Ａ🔍"]], {})
```

### Actual behaviour
Colorcolumn highlight on the current line is shifted to the right one column per full-width char.
![Screenshot from 2019-04-26 11-32-56](https://user-images.githubusercontent.com/204006/56798795-d21a8280-6817-11e9-882b-6f527b838b99.png)

### Expected behaviour
Colorcolumn highlight does not move.

**Comment by Boodleboy** [comment]
Cursorcolumn is also affected by this bug. Virtual text shifts the cursorcolumn highlight, as long as the cursorcolumn is to the right of the virtual text.

**Comment by bfredl** [comment]
Seems to be an error with vcol counting https://github.com/bfredl/neovim/commit/b9bc41d3c0d9c650788ddb5c4941035e8b1729b3

**Comment by whitebyte** [comment]
Somehow it still happens. Tested with `nvim -u NONE`, reproduces on `:checkhealth`

NVIM v0.12.0-dev-1039+g25bc41847e
Build type: RelWithDebInfo
LuaJIT 2.1.1753364724

Win10

<img width="1009" height="743" alt="Image" src="https://github.com/user-attachments/assets/07ec3ee4-2782-4258-b464-97ca9e94956f" />

When I put cursor on it and call `:Inspect`, it claims it on the col 79, even though it's "80" in the statusline
@bfredl

**Comment by justinmk** [comment]
@whitebyte It is usually related to a wrong `$TERM` or wrong terminfo. Since you're on Windows, possibly our builtin terminfo needs to be updated, but try another terminal to confirm.

**Comment by whitebyte** [comment]
Looks like it occurs only on WezTerm. Anything else looks fine

**Comment by whitebyte** [comment]
...it actually occurs on other terminals too, such as Konsole or Cmder. It does't appear on Windows Terminal app

**Comment by justinmk** [comment]
> ...it actually occurs on other terminals too, such as Konsole or Cmder. It does't appear on Windows Terminal app

The details matter. Windows Terminal is recognized as "vtpcon" https://github.com/neovim/neovim/blob/3afe0c67401b6191aa4ae53cc3b8a4d67b130ecb/scripts/windows.ti#L50

Depending on how you are running konsole (via X-Window?), maybe they don't use vtpcon. Not sure what builtin terminfo they would be mapped to. Is `$TERM` set?

**Comment by whitebyte** [comment]
Konsole has a native Windows binary. $TERM is xterm-256color. But I don't believe it's Konsole-specific, the issue occurs in other terminals. Funnily enough, in Windows Terminal $TERM is not set at all, `$env:TERM` prints nothing

**Comment by justinmk** [comment]
> in Windows Terminal $TERM is not set at all

That's an expected special-case, it's detected as `vtpcon`. For other cases, `$TERM` is the main decider.

**Comment by whitebyte** [comment]
So is it actionable from my side or it's a Neovim issue after all?

**Comment by justinmk** [comment]
First step would be to confirm, on Windows with konsole, if this code detects konsole and gets the konsole terminfo: https://github.com/neovim/neovim/blob/9e32031b904a69d22eedf800cca447d9c95d1e13/src/nvim/tui/tui.c#L396

You can add `ELOG()` logging messages and check them in `$NVIM_LOG_FILE`.
