### ISSUE TITLE
Tutor always overrides highlighting links

### ISSUE THREAD

**Issue by AlxHnr** [neovim/neovim#9945]
- `nvim --version`:
```
NVIM v0.3.3
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/build/BUILD/neovim-0.3.3/build/config -I/builddir/build/BUILD/neovim-0.3.3/src -I/usr/include -I/builddir/build/BUILD/neovim-0.3.3/build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.3.3/build/include
Compiled by mockbuild

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Vim 8.1 doesn't ship tutor syntax files on my system
- Operating system/version: `Fedora 29`
- Terminal name/version: `rxvt-unicode v9.22`
- `$TERM`: `rxvt-unicode-256color`

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC
:Tutor
:hi! link TutorOk Error
:Tutor
```

### Actual behaviour

After linking the highlighting group, it looks as it is supposed to. Invoking `:Tutor` again overrides the links. This makes maintaining colorschemes less enjoyable.

### Expected behaviour

User-defined highlighting groups are not overridden.

### Possible solution

Use `default` in tutors syntax files to prevent overriding links. See [tutor.vim](https://github.com/neovim/neovim/blob/1039e0621d4c23d42d513efdf413d4767db9bccb/runtime/syntax/tutor.vim#L52).
```diff
- hi! tutorOK ctermfg=green guifg=#00ff88 cterm=bold gui=bold
- hi! tutorX ctermfg=red guifg=#ff2000 cterm=bold gui=bold
+ hi def tutorOK ctermfg=green guifg=#00ff88 cterm=bold gui=bold
+ hi def tutorX ctermfg=red guifg=#ff2000 cterm=bold gui=bold
```

**Comment by justinmk** [comment]
> Use `default` in tutors syntax files to prevent overriding links. See [tutor.vim](https://github.com/neovim/neovim/blob/1039e0621d4c23d42d513efdf413d4767db9bccb/runtime/syntax/tutor.vim#L52).

Yes, that seems reasonable. Can you send a PR?

cc @fmoralesc

**Comment by AlxHnr** [comment]
> Yes, that seems reasonable. Can you send a PR?

Yes.

**Comment by fmoralesc** [comment]
Sounds reasonable to me.
