### ISSUE TITLE
Type ENTER in edit mode or 'o' in normal mode will cause display goes wrong

### ISSUE THREAD

**Issue by cos-ss** [neovim/neovim#9950]
- `nvim --version`: NVIM v0.3.4
- Vim (version: ) behaves differently? Yes, vim display correct.
- Operating system/version: CentOS Linux 7
- Terminal name/version: xterm (I don't know how to check it)
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

The problem can be fix using  `nvim -u NORC` . But when I set number, it happens again.
So, follow shows without "-u NORC"

```

### Actual behaviour
Type ENTER in edit mode 
![image](https://user-images.githubusercontent.com/12772673/56860069-c7512080-69c4-11e9-90db-188da9a7cec7.png)

Type 'o' in normal mode
![image](https://user-images.githubusercontent.com/12772673/56860075-dc2db400-69c4-11e9-98b8-b17fcee1741a.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/12772673/56860083-ed76c080-69c4-11e9-9a14-db96943b2feb.png)

**Comment by cos-ss** [comment]
When I use tmux, 
$TERM: screen-256color
And neovim shows as the second picture.
Meanwhile, vim shows as the first picture.
Otherwise without tmux, it shows just like I described on the top.

**Comment by cos-ss** [comment]
It seems only occur in '#', ' " ' ... auto indent line

**Comment by justinmk** [comment]
Thanks for the report. Can you try the development version? 

The [Releases](https://github.com/neovim/neovim/releases) page has pre-built archives for Linux/Windows/macOS. (No installation needed, just unzip and run. For Linux, [nvim.appimage](https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage) is a universal "binary", just `chmod u+x nvim.appimage && ./nvim.appimage`)

**Comment by cos-ss** [comment]
Do you mean NVIM 0.4.0 ?
By the way, I use ./nvim.appimage --appimage-extract because I don't have FUSE.

**Comment by cos-ss** [comment]
@justinmk  Do you have any idea where the bug is? Anything can I do for contribution?

**Comment by justinmk** [comment]
I don't know. Thanks for the offer :)

**Comment by cos-ss** [comment]
I think maybe my Terminal Emulator or tmux ‘s problem.
I close this issue, thx.
