### ISSUE TITLE
Cursor color reversed, and cannot be undone

### ISSUE THREAD

**Issue by jonhoo** [neovim/neovim#9962]
- `nvim --version`: `v0.4.0-680-g53cef34f1` (53cef34f16635aba04d4443c4d94a18a34a38eca)
- Vim (version: `8.1`) behaves the same
- Operating system/version: Arch Linux x86_64
- Terminal name/version: Alacritty 0.3.2 + tmux 2.9
- `$TERM`: `tmux-256color`

### Steps to reproduce using `nvim -u NORC`

```console
$ cat x.rs
// foo
xxx
$ nvim -u NORC x.rs
```

Notice that cursor is always the same color. Then execute `:colors darkblue`. Notice that `reverse` coloring is now applied to the cursor (when moving over `foo`, the background turns red and the foreground black). Now try to undo that using:

```
hi clear Cursor
hi clear lCursor
set guicursor=
```

### Actual behaviour

Cursor colors remains reversed. This is also the case if `Cursor` is explicitly set to `guibg=white ctermbg=white`.

EDIT: the behavior _can_ be reversed it seems by running `colors desert`, though I'm not sure why that works.

### Expected behaviour

Cursor should no longer have `reverse` flag set.

This could be related to #2884, #6425, and #3379.

**Comment by jonhoo** [comment]
Oh, here's something really weird -- this seems to only happen in a terminal after I've been using it for a while, so there's definitely something larger at play here.

**Comment by justinmk** [comment]
sounds similar to https://github.com/neovim/neovim/issues/9918 but it looks like you already have that patch.

The repro steps don't work for me, and seem incomplete: cursor-color is not changed unless 'termguicolors' is enabled.

> the behavior can be reversed it seems by running colors desert

see https://github.com/neovim/neovim/issues/6425#issuecomment-291498121 

> Vim (version: 8.1) behaves the same

Just to be clear, you are saying that Vim has the same behavior?

**Comment by jonhoo** [comment]
Yeah, as mentioned, if I start a new terminal, the problem goes away, so there's definitely something odd going on here. The reproduction steps above were all I did, and I definitely did not have `termguicolors` enabled. And yes, when it happened, it also happened in Vim. I will keep an eye out for the next time it happens and see if I can spot what is different between the terminal where I observe it and a fresh one where I do not.

**Comment by justinmk** [comment]
Sounds like a bug in Alacritty.
