### ISSUE TITLE
Highlight for slash search not applied in terminal

### ISSUE THREAD

**Issue by cideM** [neovim/neovim#9964]
- `nvim --version`: 0.3.5
- Vim (version: ) 8.1 same behavior
- Operating system/version: Linux yuuki-antergos 5.0.10-arch1-1-ARCH
- Terminal name/version: alacritty 0.3.2
- `$TERM`: `tmux-256color` (same outside of tmux)

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC --cmd "hi Search ctermfg=3"
:term
$ ls
/searchSomething
```

### Actual behaviour
Search match does not always get the specified color. It seems to work for some matches, which look like they have just my normal foreground color. But the ones that `ls` colors in bold for example retain their own color, leading to legibility issues.

### Expected behaviour
`ctermfg` is applied to *all* search matches.

Sorry if this behavior is specified somewhere but I couldn't find anything with `:h` nor in the issues here on Github

**Comment by justinmk** [comment]
did you try disabling bold

    hi Search ctermfg=3 cterm=NONE

**Comment by cideM** [comment]
Wow that was fast <3
