### ISSUE TITLE
nvim_win_set_cursor not working

### ISSUE THREAD

**Issue by pwntester** [neovim/neovim#9965]
- `nvim --version`: 0.4.0-dev
- Vim (version: ) behaves differently? vim doesnt has this function
- Operating system/version: MacOS Mojave
- Terminal name/version: iTerm
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

Try to change the cursor of an inactive window using  nvim_win_set_cursor
if window handle is 0, it will change the cursor of active window
else it will complain about window id being invalid

### Actual behaviour
Cant change cursor of arbitrary window

### Expected behaviour
Should be able to change cursor of arbitrary windows.

Im writing to a background buffer using nvim_buf_set_lines. I also want to scroll to the botton of that buffer after writing to it.

Thanks.

**Comment by mhinz** [comment]
Are you sure you're using the window _ID_ (1000+) as reported by `win_getid()` or `nvim_list_wins()`?

If I have two windows, I can set the cursor of the other window's buffer just fine.

**Comment by pwntester** [comment]
oh, my bad, I was using winnr() to populate a list of windows. Is there a way to get the buffer shown on each window by the window handle (1000+)? Something similar to winbufnr()?

Thanks!

**Comment by pwntester** [comment]
Scratch that, seems like winbufnr works with window handles

Thanks!
