### ISSUE TITLE
Terminal hides command line when inserting

### ISSUE THREAD

**Issue by jrwrigh** [neovim/neovim#9971]
- `nvim --version`:
```

$ nvim -v
NVIM v0.3.1-1-g489d32f2b
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-ecc960f4-8e53-44e6-a8e8-9587ed80f885

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```
- Operating system/version: Oracle Linux Server 7.5
- Terminal name/version: MobaXterm through SSH
- `$TERM`: `xterm-256color`

### Actual behaviour
If I create a terminal that has a bunch of output on it and then do a horizontal split, I can't see the command line as I'm typing it; the terminal moves down 1 line to obscure it when I go into insert mode. See screen cap gif:
![NeovimTerminalISsues_20190503](https://user-images.githubusercontent.com/20801821/57151122-1ff63400-6d9e-11e9-8838-6dce4c107b29.gif)

To document the gif:
1. Open up `nvim -u NORC`
2. Start terminal, then run commands till a lot of the STDOUT is taken up (in this case, a command called `whatsfree` does the trick)
3. Horizonal split and open a new text file
4. Go back to terminal, type in `ls` (note this is not visible)
5. Go to normal mode to show that `ls` was written even though it's not shown
6. Go back to terminal mode and hit enter to show that it still works
7. Go back back and forth between terminal mode and normal mode to show the terminal moving up and down.

### Expected behaviour
When I'm in a horizontal split with the terminal window open, I want to see the actual command line when I'm typing.

**Comment by justinmk** [comment]
This was fixed in 0.4.0 and backported to 0.3.5, the current stable release.
