### ISSUE TITLE
0.3.2-0.3.5 Break Syntax Checkers

### ISSUE THREAD

**Issue by naftulikay** [neovim/neovim#9975]
**NeoVim Version:**

I have tested this on:

 - 0.3.1 :+1: (works)
 - 0.3.2 :x: (broken)
 - 0.3.3 :x:
 - 0.3.4 :x:
 - 0.3.5 :x:

I have compiled these from source, but typically I'm using NeoVim from the Ubuntu PPA.

```
NVIM v0.3.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/naftuli/devel/src/github.com/neovim/neovim/build/config -I/home/naftuli/devel/src/github.com/neovim/neovim/src -I/home/naftuli/devel/src/github.com/neovim/neovim/.deps/usr/include -I/usr/include -I/home/naftuli/devel/src/github.com/neovim/neovim/build/src/nvim/auto -I/home/naftuli/devel/src/github.com/neovim/neovim/build/include
Compiled by naftuli@cosmos

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
**OS Info:**

Ubuntu 18.04/amd64, elementary OS Juno

**Terminal Info:**

- Terminal application: [Pantheon Terminal](https://launchpad.net/pantheon-terminal)
- `$TERM`: `screen-256color`

**`nvim -u NORC`:**

I'm unable to access the features I need in `nvim -u NORC`.

**Plugin Info:**

 - Using [vim-plug](https://github.com/junegunn/vim-plug)

Plugs:
 - `altercation/vim-colors-solarized`
 - `autozimu/LanguageClient-neovim`
 - `cespare/vim-toml`
 - `elzr/vim-json`
 - `hashivim/vim-terraform`
 - `juliosueiras/vim-terraform-completion`
 - `junegunn/fzf`
 - `junegunn/fzf.vim`
 - `naftulikay/vim-gnupg`
 - `scrooloose/nerdcommenter`
 - `scrooloose/nerdtree`
 - `scrooloose/nerdtree-git-plugin`
 - `Shougo/deoplete.nvim`
 - `tpope/vim-eunuch`
 - `tpope/vim-surround`
 - `vim-airline/vim-airline`
 - `vim-airline/vim-airline-themes`
 - `vim-syntastic/syntastic`
 - `w0rp/ale`
 - `fatih/vim-go`
 - `mdempsky/gocode`
 - `zchee/deoplete-go`
 - `rust-lang/rust.vim`

All plugs are up to date as of time of post and vim-plug is also up to date.

A full description of my setup can be found in [this repository](https://github.com/naftulikay/ansible-role-vim-personal).

---

### Expected Behavior

I'm currently working on a Rust project and when I open and work on files, I expect that completion and syntax checking will work like it did in NeoVim 0.3.1: syntax checking appeared in its own window at the bottom and when the cursor was over the line with the issue.

### Actual Behavior

[![Screenshot from 2019-05-02 14 04 07](https://user-images.githubusercontent.com/347571/57244997-9d17e800-6fee-11e9-9650-bfd5d328c01e.png)](https://www.youtube.com/watch?v=kWbpNQMfGjM)

[(Video)](https://www.youtube.com/watch?v=kWbpNQMfGjM)

I observed the issue on two different machines both running the same Linux distribution.

Prior to upgrading, syntax errors would be hidden as expected. Post upgrade, syntax errors get thrown around making it really difficult to write code.

After a lot of compiling (compiled 0.3.1 to 0.3.5 and tested each), v0.3.5 does fix the issue, but this version has not been made available in the PPA yet. I'll be closing this issue immediately upon creation.

**Comment by naftulikay** [comment]
Perhaps I'll actually leave this open to track when 0.3.5 hits the PPA.

**Comment by justinmk** [comment]
Good to know that v0.3.5 fixes your issue. But it's too much work for us to investigate how 10 plugins are interacting. We would need some reduced series of steps, or a hint about which Nvim commit caused the change.

**Comment by naftulikay** [comment]
@justinmk 0.3.5 does not fix it, unfortunately.

**Comment by naftulikay** [comment]
What would meet your standards of reproducibility? Let me know and I'm happy to attempt to provide steps.

**Comment by naftulikay** [comment]
As noted, unfortunately this bug still exists in 0.3.5, I was wrong about it being fixed.

**Comment by justinmk** [comment]
Well, to start with:

> I expect that completion and syntax checking will work like it did in NeoVim 0.3.1

This doesn't really mean anything, because Nvim doesn't do that stuff. Some plugin does it. It would be more productive to report your experience to the relevant plugin(s).

**Comment by justinmk** [comment]
Another idea is to bisect exactly which commit in Nvim changed the behavior. You would need to build from source and use `git bisect`.

If you narrow it down to a specific commit, we can probably provide a clue.

**Comment by naftulikay** [comment]
`git-bisect` yields 32405de7df965174f0aad19692b8d988bae83a44 as the commit that broke things.

**Comment by mhinz** [comment]
Are we talking about the pinkish lines? They're called virtual text. I was introduced around ~3.2, so maybe it's just your LSP plugin (languageClient-neovim) using it by default if available.

https://github.com/autozimu/LanguageClient-neovim/blob/0ed9b69dca49c415390a8317b19149f97ae093fa/autoload/LanguageClient.vim#L147-L160

**Comment by bfredl** [comment]
https://github.com/neovim/neovim/commit/32405de7df965174f0aad19692b8d988bae83a44 just introduced an alias for an API function. What happens is that your plugin will invoke different default behaviors based on detecting this API function. You have to configure your plugin to behave the way you want, it is not a Nvim issue.
