### ISSUE TITLE
idea: fuzzer based auto test/coverage ?

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#9998]
Hello , during using neovim I've hit crash several times. vim is complex , maybe special operate flow is needed to trigger bugs. so I wonder if we can use fuzzer to auto test/coverage vim code. fuzzer is very helpful for syntax/format parser , it feeds much more input variants to coverage more code path. maybe this approach can also be applied to nvim,  what we need to do is just to convert fuzzer input to deterministic nvim input. so I take a quick demo like this:

```C
void *fuzz_input(void *arg){

    sleep(3);
    ioctl(0, TIOCSTI, "i");

    usleep(200000);

    char p[] ="hello world";
    for(int i=0;i<strlen(p);++i){
        ioctl(0, TIOCSTI, p+i);
        usleep(200000);
    }

    sleep(1);
    char esc='\e';
    ioctl(0, TIOCSTI, &esc);
    sleep(1);

   
    char p1[] = ":q!\n";

    for(int i=0;i<strlen(p1);++i){
        ioctl(0, TIOCSTI, p1+i);
        usleep(200000);
    }
        
    return NULL;
}


int main(int argc, char *argv[])
{
  pthread_t input_thread;
  pthread_create(&input_thread, NULL, fuzz_input, NULL);
  return nvim_main(argc,argv);
}
``` 

it simply run nvim_main and emulate user input by ioctl from another thread. this can be turned into libFuzzer testcase easily as 
```C
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  map_data_into_input_in_another_thread(Data,Size);
  return nvim_main(argc,argv);
}
```

libFuzzer feeds byte array into every testcase, we map it to user input by rules (for example):

1. any valid terminal character passed directly into nvim
2. any invalid terminal character mapped to a time sleep
3. we can also map character into frequency input sequences 

libFuzzer has experimental support for 'fork mode' ,which can ignore memory leaks and also not killed by OOM.   so we can focus on critical crash only.  but I think this also needs neovim builtin support. for example nvim should operate under a fake root ( if not, nvim is able to modify any file, leads individual testcase affect each other,  it can also modify fuzzer result) . with this approach ,  we can also use google oss fuzzer. this can emulate much more user input than human input.

**Comment by justinmk** [comment]
Thanks for your reports. We're aware of the crashes, but we need more people spending time investigating them.

**Comment by comicfans** [comment]
any guide on how neovim handle file io ? does all neovim file io go through common code path so I can easily hook into it ?  I'd like to create fuzzer test for neovim, but I need to force nvim only read/write file under particular dir (as fake root). chroot or simply running as a restrict user is not enough.

**Comment by justinmk** [comment]
setting `$TMPDIR` , `$XDG_CONFIG_HOME`, and `$XDG_DATA_HOME` should be enough to control the various output directories.

**Comment by comicfans** [comment]
since it is fuzz based , nvim may open and modify any file (if possible). for example multi nvim instance (forked from single testcase) can modify same file ( they got different fuzzer input, but mapped user input may lead to same file operation), which leads testcase unpredictable. for every fuzzer input, we need to create a seperate dir , and all file (write) operations of this nvim instance only allowed under this dir. this make every input sequence test behave exactly same

**Comment by justinmk** [comment]
maybe preparing a submission for https://github.com/google/oss-fuzz would avoid some steps.

**Comment by comicfans** [comment]
yes, according to [Fuzzer execution environment ](https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md) , only /tmp is writable is great, but still not enough.  libfuzzer also need to write its 'Corpus' files (same process space with testcase), without some sort of sandbox filesystem , we always have such problem that nvim may modify such unexpect file.

**Comment by justinmk** [comment]
In the meantime, note that even without reproducible steps, if you can provoke a crash while debugging with [rr](https://rr-project.org/) then you can step backwards through the entire state of the program, and step forward taking different codepaths.

rr is very easy to install/use, would be very helpful to have more people looking into these bugs.
