### ISSUE TITLE
Add support to :inccommand for :global

### ISSUE THREAD

**Issue by lpil** [neovim/neovim#9999]
- `nvim --version`: `NVIM v0.3.4`
- Operating system/version: Chrome OS 74, Debian 9 Linux container
- Terminal name/version: gnome-terminal
- `$TERM`: xterm

### Steps to reproduce using `nvim -u NORC`
```
nvim -u NORC
:set inccommand=split
```

### Actual behaviour
`:g` does not work with inccommand

### Expected behaviour

`:g` works with inccommand and shows the update as the command is typed

**Comment by justinmk** [comment]
covered by https://github.com/neovim/neovim/issues/7370

**Comment by lpil** [comment]
Brilliant, thank you.
